### ISSUE TITLE
Systemd should not fail to execute when seccomp is disabled in the kernel

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#3882]
### Submission type
- Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Debian
### In case of bug report: Expected behaviour you didn't see

Successful boot on a systemd built with seccomp support but without kernel support (ie, CONFIG_SECCOMP unset).
### In case of bug report: Unexpected behaviour you saw

Failure to boot as several services had SystemCallFilters applied in 231.

This was reported [downstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832713). The debian kernels on arm\* do not have SECCOMP enabled (not sure why), and this failure to boot as logind and journald fail to execute.

I think the fix would be to have an equivalent to `mac_selinux_use` for seccomp, and skip the setup in case it is not available.

**Comment by evverx** [comment]
https://github.com/systemd/systemd/blob/409093fe10685ed55915ef256f09cdf144b6528b/README#L76

> Optional but strongly recommended:
> ...
>     CONFIG_SECCOMP

:-)

> I think the fix would be to have an equivalent to mac_selinux_use for seccomp, and skip the setup in case it is not available.

Well, you can enable/disable SElinux/AppArmor at boot. So, we should handle this situation.
But you can't enable/disable seccomp at boot.  So, I think `./configure --disable-seccomp` is the right solution.

BTW
I've seen your [patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=832713;filename=skip-seccomp.patch;msg=128). I think this

``` c
+bool is_seccomp_enabled() {
+        _cleanup_free_ char* field = NULL;
+        return get_proc_field("/proc/self/status", "Seccomp", "\n", &field) == 0;
+}
+
```

should go into https://github.com/seccomp/libseccomp

**Comment by evverx** [comment]
`v232`, ok

Well, I think `--enable-seccomp`, `CONFIG_SECCOMP=n` is misconfiguration.
But, indeed, this doesn't really matter.

**Comment by fsateler** [comment]
> But you can't enable/disable seccomp at boot. So, I think ./configure --disable-seccomp is the right solution.

That is problematic for general-purpose distros as at  build time you do not know the kernel you will run under. I don't know why SECCOMP is not enabled ([bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833183)), but even if that is fixed there is no guarantee that the final user will use a distro-provided kernel.

> I've seen your patch. I think this should go into https://github.com/seccomp/libseccomp

Agreed. https://github.com/seccomp/libseccomp/issues/45

**Comment by evverx** [comment]
> That is problematic for general-purpose distros as at build time you do not know the kernel you will run under.

Agreed. Sorry for the noise.

Actually, we ignore the `ima_setup`-errors too

``` c
int ima_setup(void) {
#ifdef HAVE_IMA
        _cleanup_fclose_ FILE *input = NULL;
        _cleanup_close_ int imafd = -1;
        unsigned lineno = 0;
        char line[page_size()];

        if (access(IMA_SECFS_DIR, F_OK) < 0) {
                log_debug("IMA support is disabled in the kernel, ignoring.");
                return 0;
        }
```

So,  let's be consistent:)

**Comment by gdamjan** [comment]
But I'd print a warning if the administrator (the service files) configured security options but they were ignored.

**Comment by poettering** [comment]
i think we should really work on any kernel we find. And always log about issues where we can't apply the requested security features. However, it should be at LOG_DEBUG and non-fatal if the feature is explicitly not enabled in the kernel, and LOG_ERROR and fatal in all other cases.

**Comment by fsateler** [comment]
This is still broken when CONFIG_SECCOMP=y but CONFIG_SECCOMP_FILTER=no.

Patch waiting at https://github.com/systemd/systemd/pull/4087
