### ISSUE TITLE
report when coredump is truncated in coredumpctl

### ISSUE THREAD

**Issue by thiagomacieira** [systemd/systemd#3883]
### Submission type
- [ ] Bug report
### systemd version the issue has been seen with

> 228
### Used distribution

> OpenSUSE Tumbleweed 20160728
### In case of bug report: Expected behaviour you didn't see

The man page for coredump.conf says:

```
       ProcessSizeMax=
           The maximum size in bytes of a core which will be processed. Coredumps exceeding this size will be logged, but the
           backtrace will not be generated and the core will not be stored.
```

I would expect that for a core dump that exceeds the max, the dump itself would not get stored, just logged.
### In case of bug report: Unexpected behaviour you saw

When using coredumpctl gdb on a given, stored coredump, gdb says:

>  BFD: Warning: /var/tmp/coredump-SMKP0B is truncated: expected core file size >= 2608939008, found: 2147483648.

I believe the process size did exceed the max, but coredump uselessly stored this truncated core anyway. Moreover, it spent 150 seconds of CPU time compressing it.
### In case of bug report: Steps to reproduce the problem

Crash a very large process. This happened with plasmashell for me.

**Comment by thiagomacieira** [comment]
This could be the same as https://bugs.freedesktop.org/show_bug.cgi?id=59623, but that one is marked as closed/fixed as the limit was increased.

**Comment by poettering** [comment]
Truncated coredumps are not useless coredumps. Of course you cannot use the to look at the missing parts, but the stuff that is there might still be interesting. I mean, that's the reason why RLIMIT_CORE has existed the way it always existed: so that you get some data but not too much data in your coredumps.

The docs are pretty much out of sync with this though.

**Comment by thiagomacieira** [comment]
I don't see how if the thing that is missing in the core dump is the stack of the main thread. At least gdb can't make sense of this coredump.

Do you have some hints of what I could do get some information out of it?

**Comment by F0REacH** [comment]
Had same issue on openSUSE Tumbleweed 20160901
Fixed by editing **/etc/systemd/coredump.conf**
systemctl daemon-reload
Also added 

> \*  soft  core  unlimited

to **/etc/security/limits.conf** just to be sure ulimit -a are ok

**Comment by keszybz** [comment]
The messages were improved in 73a9916. Like Lennart said, the coredump is not useless. But instead we should still do better and report the fact of truncation and the full size in coredumpctl. Let's re-purpose this bug for that.

I'll probably work on that, but not in the immediate future. I wouldn't mind somebody else taking this over.

**Comment by poettering** [comment]
@keszybz please don't drop issues from milestones entirely they were marked for. Please just move them to the next milestone instead...

**Comment by keszybz** [comment]
IIUC, the only thing remaining is the RFE that I described… I don't see the point of marking that for a milestone, since it's hardly blocking, and will get merged as-soon-as / if anybody writes the code.

**Comment by poettering** [comment]
ok, dropped the milestone
