### ISSUE TITLE
systemd-timesyncd forces synchronization on DHCP lease renewal 

### ISSUE THREAD

**Issue by sitsofe** [systemd/systemd#3888]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd-229-9.fc24.x86_64
### Used distribution

> Fedora 24
### Expected behaviour you didn't see

> Time synchronization being forced only when brand new/not previously used network details are received via DHCP. 
### Unexpected behaviour you saw

> Every time a lease is renewed to the same details (in my case every five minutes) the following occurs:
> systemd-timesyncd[529]: Synchronized to time server ip:123 (ip).
### Steps to reproduce the problem

> 1. Set a DHCP server to serve leases with a maximum lease time of 10 minutes and a recommended renewal time of five minutes.
> 2. Configure a Fedora 24 VM to request DHCP leases using networkd.
> 3. After initial lease is obtained wait for the lease to be renewed (in my case five minutes) and check the journal for systemd-timesyncd messages.

**Comment by poettering** [comment]
@yuwata suggested that this is fixed by #8611. I think I agree. Closing hence. Please test and report back if this is still an issue with that PR applied.
