### ISSUE TITLE
TimeoutStopSec and KillSignal seem to be ignored

### ISSUE THREAD

**Issue by jamespharvey20** [systemd/systemd#3901]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> v231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> Using TimeoutStopSec, only a 5 second delay manually stopping service or after Reached target Shutdown, rather than 90 seconds.
> Using KillSignal, practically no delay manually stopping service or after Reached target Shutdown, rather than 90 seconds.
### In case of bug report: Unexpected behaviour you saw

> The same default 90 second delay.
### In case of bug report: Steps to reproduce the problem

> Commit d450612 changed the timeout on waiting for a SIGTERM before sending a SIGKILL from 10 to 90 seconds.
> 
> I think that's great, just it turns out lvm2-lvmetad.service always times out on me, and I'm hoping it doesn't do anything useful after the first split second to the 90 second timeout, so I just want it to get killed early.
> 
> Edited /usr/lib/systemd/system/lvm2-lvmetad.service to be;
> (I've tried TimeoutStopSec and KillSignal separately, together, and together with KillMode as shown below - none change the 90 second delay.)
> 
> I even tried rebooting twice after changing the .service file, in case the change wouldn't take effect until reloaded.

```
[Unit]
Description=LVM2 metadata daemon
Documentation=man:lvmetad(8)
Requires=lvm2-lvmetad.socket
After=lvm2-lvmetad.socket
DefaultDependencies=no
Conflicts=shutdown.target
KillMode=process
TimeoutStopSec=5
KillSignal=SIGKILL

[Service]
Type=simple
NonBlocking=true
ExecStart=/usr/bin/lvmetad -f
Environment=SD_ACTIVATION=1
Restart=on-abort
PIDFile=/run/lvmetad.pid

[Install]
WantedBy=sysinit.target
```

**Comment by poettering** [comment]
KillMode, TimeoutStopSec and KillSignal belong in the [Service] section. See systemd.kill(5):

>  The kill procedure configuration options are configured in the [Service], [Socket], [Mount] or [Swap] section, depending on the unit type.

If you place them in [Unit] they have no effect except resulting at a warning message in the logs.
