### ISSUE TITLE
A way to list users with lingering enabled

### ISSUE THREAD

**Issue by michalrus** [systemd/systemd#3907]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 231
### Used distribution

> NixOS
### Feature request

To implement declarative lingering configuration module for NixOS, I need to be able to read current state of lingering enabled/disabled status.

**Most probably `loginctl` should have a command that would list user names (UIDs?) with lingering currently enabled.**

Currently, I’m using `ls /var/lib/systemd/linger` to get account names with lingering enabled, as suggested by @falconindy in freenode/#systemd:

```
17:06 <michalrus> Hey, how can I get a list of users with lingering enabled in loginctl?
17:08 <dreisner> michalrus: i don't know that loginctl can do that for you, but there's
                 always: ls /var/lib/systemd/linger
17:08 <michalrus> Great, thank you!
17:10 <michalrus> dreisner: and the files named after usernames are there always,
                  it doesn’t matter if this particular user’s processes are running?
17:12 <dreisner> right
17:12 <dreisner> if they're there, lingering is enabled. it's stored on disk.
18:06 <michalrus> dreisner: okay, thank you. :)
```

I’m opening this RFE, as suggested by @gdamjan:

```
18:04 <damjan> michalrus: I'd open a feature request against loginctl for that
               /var/lib/systemd/linger is implementation detail
18:06 <michalrus> damjan: will do that. :) Thank you, too.
```

**Comment by Abdull** [comment]
*systemd* `v252` introduced an additional *LINGER* column for the output of `loginctl list-users`.

Example output:

```
$ loginctl list-users
 UID USER   LINGER
1000 abdull yes
1001 guest  no

2 users listed.
```
