### ISSUE TITLE
Document sd_bus_set_fd

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#391]
I can't figure out why you'd ever want to set the `output_fd` different to the `input_fd`. All examples I can find have them as the same.
Additionally, `sd_bus_get_fd` no longer works when they are different.

There is currently no man page for this function, could one be added with a rationale for why they might want to be different?

**Comment by poettering** [comment]
Specifying different fds for input and output is useful for tools who want to create a bus connection out of stdin/stdout, they way systemd-stdio-bridge does it to implement bus connections via ssh. But yeah, we should document that.

**Comment by poettering** [comment]
I guess we can track this issue in #235, no need to keep two open issues about this.
