### ISSUE TITLE
Even in Service section, TimeoutStopSec seems to be ignored

### ISSUE THREAD

**Issue by jamespharvey20** [systemd/systemd#3912]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> v231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> Using "TimeoutStopSec=5", possibly also with "KillMode=process" only a 5 second delay manually stopping service or after Reached target Shutdown, rather than 90 seconds.  I'd prefer not to use KillSignal, so if it does anything useful it gets that chance.  (Same problem with dmeventd, which I'm more nervous about than lvmetad.)
### In case of bug report: Unexpected behaviour you saw

> The same default 90 second delay.
### In case of bug report: Steps to reproduce the problem

> You were absolutely right in #3901, I had everything in the wrong section.  (Sorry...) But, having "TimeoutStopSec=5" in the Service section still doesn't shorten the 90 seconds.
> 
> I'm not sure if "KillMode=process" is needed here, but adding it to the Service section doesn't shorten the 90 seconds either.
> 
> Using "KillSignal=SIGKILL" in the Service section does immediately kill lvmetad.  It never kills dmeventd, as descirbed below. I'd prefer not to use this anyway, at least giving it a few seconds to execute in case it does anything useful.  I'm also having dmeventd never close itself too, and I'm even less sure on that than lvmetad that it can be immediately killed.
> 
> I am running systemctl daemon-reload before rebooting.
> 
> The shutdown log shows it is changing lvm2-lvmetad.service to stop-sigterm, then waits 90 seconds before sending SIGKILL.
> 
> Strangely, the shutdown log doesn't show it ever even changes dm-event.service to stop-sigterm, just after that 90 seconds, it sends dmeventd a SIGKILL.  Even if I use "KillSignal=SIGKILL" in both of these Service sections, it never changes the dm-event.service to stop-sigterm.
> 
> There are a ton of "Failed to send unit remove signal for @: Transport endpoint is not connected" which maybe has something to do with it.
> 
> Log using "KillMode=process" and "TimeoutStopSec=5", containing
> [shutdown-log.new.txt](https://github.com/systemd/systemd/files/404856/shutdown-log.new.txt)

```
[31.279031] lvm2-lvmetad.service: Changed running -> stop-sigterm
[122.687266] systemd-shutdown[1]: Sending SIGKILL to PID 501 (lvmetad).
[122.687349] systemd-shutdown[1]: Sending SIGKILL to PID 505 (dmeventd).
```

> Log using "KillSignal=SIGKILL", containing
> [shutdown-log.newSigKill.txt](https://github.com/systemd/systemd/files/404860/shutdown-log.newSigKill.txt)

```
[20.873034] systemd[1]: lvm2-lvmetad.service: Killing process 508 (lvmetad) with signal SIGKILL.
{{ no such line for dm-event.service }}
[112.340213] systemd-shutdown[1]: Sending SIGKILL to PID 512 (dmeventd).
```

> Edited /usr/lib/systemd/system/lvm2-lvmetad.service to be;

```
[Unit]
Description=LVM2 metadata daemon
Documentation=man:lvmetad(8)
Requires=lvm2-lvmetad.socket
After=lvm2-lvmetad.socket
DefaultDependencies=no
Conflicts=shutdown.target

[Service]
Type=simple
NonBlocking=true
ExecStart=/usr/bin/lvmetad -f
Environment=SD_ACTIVATION=1
Restart=on-abort
PIDFile=/run/lvmetad.pid
KillMode=process
TimeoutStopSec=5

[Install]
WantedBy=sysinit.target
```

> And, edited /usr/lib/systemd/system/dm-event.service to be;

```
[Unit]
Description=Device-mapper event daemon
Documentation=man:dmeventd(8)
Requires=dm-event.socket
After=dm-event.socket
Before=local-fs-pre.target
DefaultDependencies=no

[Service]
Type=simple
ExecStart=/usr/bin/dmeventd -f
Environment=SD_ACTIVATION=1
PIDFile=/run/dmeventd.pid
OOMScoreAdjust=-1000
KillMode=process
TimeoutStopSec=5

[Install]
WantedBy=sysinit.target
```

**Comment by arvidjaar** [comment]
Your units have `DefaultDependencies=no` and no explicit ordering against shutdown.target which means systemd does not wait for them to stop, but immediately is replaced by systemd-shutdown.

```
[   31.279031] systemd[1]: lvm2-lvmetad.service: Changed running -> stop-sigterm
...
[   32.006008] systemd[1]: Shutting down.
...
[   32.667256] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  122.680017] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  122.687266] systemd-shutdown[1]: Sending SIGKILL to PID 501 (lvmetad).
[  122.687349] systemd-shutdown[1]: Sending SIGKILL to PID 505 (dmeventd).
```

systemd-shutdown waits default timeout before sending final SIGKILL.

You need to add explicit ordering against shutdown.target to make sure systemd waits for services to stop before starting shutdown.target.

**Comment by jamespharvey20** [comment]
Thanks.  The service files are from upstream, except for my trying to make them timeout in 5 seconds.

To give lvmetad and dmeventd 5 seconds to stop then be SIGKILL'ed, I'm adding "Before=shutdown.target reboot.target halt.target kexec.target", keeping "TimeoutStopSec=5", omitting "KillMode=process", and to dm-eventd.service adding "Conflicts=shutdown.target" (lvm2-lvmetad.service already has it) and that seems to be doing the trick.

Does that sound like the changes you'd make, if you were trying to accomplish the same thing?

**Comment by poettering** [comment]
LVM is special, it wants to be excluded from the normal shutdown logic by setting DefaultDependencies=no, and not adding Conflicts=shutdown.target plus After=shutdown.target instead. I am not sure why they do it though. But that means TimeoutStopSec= or ExecStop= of the service have no effect when shutting down, as the service is actually never shut down during the normal startup phase.

Any processes remaining during the normal startup phase are cleaned up at shutdown in a killing spree that however only cares about processes and has no concept of services or service configuration anymore. Hence during that final phase TimeoutStopSec= has no effect either anymore.

Hence, yes, if you want TimeoutStopSec= and ExecStop= and KillMode= to have an effect on your service then you need to add Conflicts=shutdown.target and After=shutdown.target to its [Unit] section. Only then it will be stopped during the usual shutdown phase.
