### ISSUE TITLE
systemd-run does not handle spawn failure gracefully

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#3915]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

git as of today.

When testing the new PrivateUsers functionality from #3884, if spawning fails, systemd-run -t keep the terminal open:

$ systemd-run -p PrivateUsers=1 -p User=foobar -t /bin/sh
Running as unit: run-rc18948239aa74a28a8a5733d3e4cd888.service
Press ^] three times within 1s to disconnect TTY.
(waits forever)

while

```
Aug 06 16:59:04 laptop systemd[32614]: run-rc18948239aa74a28a8a5733d3e4cd888.service: Failed at step USER spawning /bin/sh: No such process
Aug 06 16:59:04 laptop systemd[1]: run-rc18948239aa74a28a8a5733d3e4cd888.service: Main process exited, code=exited, status=217/USER
Aug 06 16:59:04 laptop systemd[1]: run-rc18948239aa74a28a8a5733d3e4cd888.service: Unit entered failed state.
Aug 06 16:59:04 laptop systemd[1]: run-rc18948239aa74a28a8a5733d3e4cd888.service: Failed with result 'exit-code'.
```

Ideally, systemd-run would return with an error immediately.

**Comment by poettering** [comment]
Fix waiting in #4973.
