### ISSUE TITLE
RFE: make systemd.show_status=auto delay longer when waiting for a password

### ISSUE THREAD

**Issue by thiagokokada** [systemd/systemd#3916]
### Submission type
- [X] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> I am using systemd in initramfs and my setup is a LUKS+LVM one. systemd provides the password input for me, instead of the old method that uses a shell script or something. Until this point it all works well.
> However I like to have a quiet boot (without systemd showing service status). Passing `quiet` or explicitly `systemd.show_status=auto` (default in `quiet`) does not work 100% of time, because if I take too long to type my password (something like 10s I think), systemd thinks that the decrypt service is taking too long and change to show everything, ruining my quiet boot.
> One workaround is to use `systemd.show_status=false`, however in this case it never shows anything, even if a service fails. I would like to see when a service fails, however I don't want a verbose boot just because I take too long to type my LUKS password (that is quite long BTW).
> It would be interesting to have some way to set this delay time or even disable it. Maybe make `systemd.show_status` support numeric values, so if you use a numeric value (say 30) it would wait 30 seconds until considering that the service is taking too long.
### In case of bug report: Unexpected behaviour you saw

> `systemd.show_status=auto` showing service status even when a service is not failing.
### In case of bug report: Steps to reproduce the problem

> Look at "Expected behavior you didn't see".

**Comment by poettering** [comment]
Consider setting `x-systemd.device-timeout=infinity` or so in /etc/fstab for the mount point you don't want to timeout. Does that sufficiently fix your issue?

**Comment by poettering** [comment]
Closing due to lack of response, and that the suggested option should likely fix your issue

**Comment by CottonEaster** [comment]
It seems to me that one might, sensibly, want a non-infinity timeout on mounts, without wanting any mount problems to be displayed during boot.

**Comment by keszybz** [comment]
If there is no job finished in JOBS_IN_PROGRESS_WAIT_USEC (5 s), show_status is set to enabled. One solution would be to make  JOBS_IN_PROGRESS_WAIT_USEC configurable. Another would be make pid1 notice that it is starting a unit that requires human input, and increase the timeout. E.g. maybe we could make the delay longer if /run/systemd/ask-password is non-empty?

**Comment by baltitenger** [comment]
Is there a solution for this problem?

> Consider setting `x-systemd.device-timeout=infinity` or so in /etc/fstab for the mount point you don't want to timeout.

The problem isn't that the mount actually times out, but that systemd thinks that some unit is taking too long, and `ShowStatus=auto` turns on terse service status updates on bootup.

[A proposed solution](https://github.com/systemd/systemd/issues/11447#issuecomment-454775058) on #11447 could help in this case too: there should be a mechanism for detecting interactive units and not counting delays in them as errors.
