### ISSUE TITLE
systemd-networkd: failed with "Argument list too long"

### ISSUE THREAD

**Issue by huiyiqun** [systemd/systemd#3922]
### systemd version the issue has been seen with

```
$ systemctl --version
systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```
### Used distribution

Latest ArchLinux with:

```
$ uname -a
Linux ancient 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```
### In case of bug report: Unexpected behaviour you saw

After recent update of systemd, systemd-networkd failed with:

```
...
Aug 08 10:00:15 ancient systemd[1]: Starting Network Service...
Aug 08 10:00:15 ancient systemd-networkd[429]: Failed to parse file '/etc/systemd/network/ol.network': Argument list too long
Aug 08 10:00:15 ancient systemd-networkd[429]: Could not load configuration files: Argument list too long
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 10:00:15 ancient systemd[1]: Failed to start Network Service.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Unit entered failed state.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart.
Aug 08 10:00:15 ancient systemd[1]: Stopped Network Service.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Start request repeated too quickly.
Aug 08 10:00:15 ancient systemd[1]: Failed to start Network Service.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Unit entered failed state.
Aug 08 10:00:15 ancient systemd[1]: systemd-networkd.service: Failed with result 'start-limit-hit'.
...
```
### In case of bug report: Steps to reproduce the problem

In fact, I have a very long `ol.network` with 1346 routes configured with following format:

```
[Route]
Gateway=10.233.0.5
Destination=223.248.0.0/14

[Route]
Gateway=10.233.0.5
Destination=223.252.128.0/17
...
```

This configuration used to work with last version of systemd.

**Comment by evverx** [comment]
8c34b963076a1ce

>  networkd: enforce a limit on the number of statically assigned addresses/routes/fdb entries
>      We should put a limit on everything, hence also on these resources.

There is a `STATIC_ROUTES_PER_NETWORK_MAX`:

> #define STATIC_ROUTES_PER_NETWORK_MAX 1024U

**Comment by huiyiqun** [comment]
Why should we put that limit over users?

**Comment by evverx** [comment]
See https://github.com/systemd/systemd/pull/3431#issuecomment-224029704

Hm, are there any docs? I can't find.

**Comment by ssahani** [comment]
No I don't think so. The idea evolved from protecting the system from flood attacks such as 
IPv6 RA attack #2977 . But I think we can should make it configurable for genuine case .

**Comment by huiyiqun** [comment]
@ssahani I agree with you.

**Comment by ssahani** [comment]
I will prepare a PR @poettering ?

**Comment by johannbg** [comment]
Cant this be implemented a little bit smarter and be done dynamically by counting the relevant line(s) in .network files or something so the administrator never encounters this limit in the first place and the resource usage is kept at minimum at the same time? This whole thing of having administrators having to manually configure some static value on the 21 century to overcome some resource limit sounds somewhat backwards and is a relic from the time when people where punching holes in paper and call it coding.

**Comment by poettering** [comment]
@huiyiqun how many routes are you adding there, if 1024 is not enough?

The limit is supposed to be a safety  feature for run-away cases. It shouldn't be configurable. Instead it should be as low as possible but as high as necessary. If 1024 is too low IRL, then let's bump it to the next exponent of 2 that is at least twice as high as what you need in your case. Hence: how many routes do you expect in your case?

**Comment by poettering** [comment]
Also, we probably should add a nicer log message at the same time as bumping the limit.

**Comment by johannbg** [comment]
@poettering If manufactures make network/routing devices/servers and network OS which uses systemd and utilize networkd you seriously cant be expecting networkd administrators in such deployment to come running here upstream and ask for the limit to be "bumped" when ever they encounter this issue then wait for that change to be backported to the network os and redeployed on all the routing/network devices/servers . This needs more intelligent and transparent handling ( read as without any involvement of the administrator ) or the change which introduced this limit in the first place needs to be reverted.

If you desperately need a number to default on you can set it to 600k which is what large routing table are growing into these days ( they have crossed the 500k mark ).

**Comment by johannbg** [comment]
Is there no variable in kernel network stack that can be used to determine this and or set this ( the value would be same as that ) or used as an base reference to calculate an value and set that so network administrators will have to increase that kernel value ( via syctl ) which would then be reset when networkd is restarted. That way you would guarantee that they always hit the kernel limit first before hitting the limit in networkd ( which would be the same or more ).

**Comment by arvidjaar** [comment]
@johannbg 

> Is there no variable in kernel network stack that can be used to determine this

`net.ipv4.route.max_size` sounds like it fits the bill. I believe there is direct counterpart for IPv6,

**Comment by keszybz** [comment]
Let's defer to the kernel here: if too many routes are specified, the kernel will reject that. We don't need to do anything, i.e. let's just drop the check.

(We could read net.ipv4.route.max_size and net.ipv6.route.max_size and reject routes above this number... but meh, there's just so many different ways for the administrator to exhaust resources, and guarding against this one which is a) unlikely to be done accidentally, b) likely to cause problems when people experiment with large systems, it just doesn't seem worth the trouble.)

**Comment by huiyiqun** [comment]
I scratched the network list from [here](http://www.nirsoft.net/countryip/cn.html). The total number is 1200+.

But in my opinion, the number makes no sense. In the future, I may append network addresses of another countries to the route table, so the number may be doubled or tripled sooner or later.

I understand that this limit is for safety, but should it be uncontrollable even if I know what I'm doing?

I agree that the variable of kernel(`net.ipv6.route.max_size`) is a better place to handle the safety issue and we could control that just like what `IPForward` did with `net.ipv6.conf.all.forwarding`. For better security, we could give it a lower default value but we should not impose that on users.

**Comment by poettering** [comment]
@keszybz i am still very much of the opinion that we should limit whatever we load, and hence should have a limit for routes too. Note that the kernel will only apply a limit on routes actually set up, but we should also enforce a limit on routes we keep in memory non-applied (i.e. linked from a Network structure, without actually being applied).

I'd be fine to read the limit off the kernel, so that we adapt automatically. For example, a single function max_routes() or so might make sense, that determines the sum of the ipv4 and ipv6 kernel route setting and uses that, maybe with an additional check to permit at least 4K or so would make sense.
