### ISSUE TITLE
[timesyncd] reduce synchronization

### ISSUE THREAD

**Issue by mattia-b89** [systemd/systemd#3926]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux

I'd like to see the ability to reduce the times that timesyncd synchronizes the time.
The best solution IMHO is to do it once, at boot time, or the first period available
This has two positive effect: 1. doesn't waste time and network resources (e.g. I rely on a 1Mbit ADSL and every saved bit counts!) 2. doesn't write the updated time on the disk (/var/...), this means no write cycles (useful for SSD and other...) and doesn't require the location to be read-write capable

**Comment by poettering** [comment]
what's the freq you are seeing and what's the freq you'd like to see?

**Comment by mattia-b89** [comment]
sorry for this delay in the answer
I was checking the frequency more in deep...

the result is: the first synchronization happens at boot, the second after an hour (more or less) and then every five minutes

**Comment by poettering** [comment]
and what frequency would you rather like to see?

**Comment by mattia-b89** [comment]
I'd like to have a mandatory check on boot (and this is already done, perfect!)
the next checks should be done at least six hours later or if the difference between synchronized clocks is big...

**Comment by yuwata** [comment]
Setting `PollIntervalMinSec=` in timesyncd.conf may help you. The setting was added in #7268 (v236).

**Comment by yuwata** [comment]
Let's close this. Please reopen if #7268 does not help you.
