### ISSUE TITLE
journalctl: --follow doesn't work with --machine

### ISSUE THREAD

**Issue by iaguis** [systemd/systemd#3927]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

Arch linux
### In case of bug report: Expected behaviour you didn't see

`--follow` works when used in combination with `--machine`
### In case of bug report: Unexpected behaviour you saw

New journal entries weren't shown after starting `journalctl --machine WHATEVER --follow`.
### In case of bug report: Steps to reproduce the problem
1. Start a container with nspawn
   
   ```
   # systemd-nspawn -bD arch
   ...
   ```
2. Run journalctl in another terminal
   
   ```
   # journalctl --machine arch --follow
   ...
   ```
3. Back to the container, write something in the journal
   
   ```
   [root@arch ~]# logger hello
   ```
4. Check that nothing gets printed in the journal terminal
5. Run journalctl again to see it printed
   
   ```
   # journalctl --machine arch --follow
   ...
   Aug 08 15:25:07 arch root[42]: hello
   ```

**Comment by evverx** [comment]
Fix waiting in #3934

This regression was introduced by d38c62cc76a1
