### ISSUE TITLE
Prefer DMI chassis info to OSPM

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#3930]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

git master

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

N/A
### In case of bug report: Expected behaviour you didn't see

Convertible laptop detected as laptop
### In case of bug report: Unexpected behaviour you saw

Convertible laptop detected as tablet
### In case of bug report: Steps to reproduce the problem

GNOME has different PM behaviours depending on whether a device is a tablet or not, eg. when locking the display, a tablet would be suspended.

This causes problems on convertible laptops such as the Lenovo Yoga 3 Pro, which is tagged as having a preferred "tablet" PM behaviour, rather than a laptop one.

Currently, systemd prefers the OSPM information from ACPI, rather than the more precise DMI information which would allow us to tag such a device as a laptop.

My preferred way of fixing this problem would be:
- prefer DMI information to the less precise OSPM information
- tag "convertible" chassis ("1Fh") as having laptop chassis (unless we want to add a convertible chassis type, but I don't see the use for it)

I'm also opened to other means of fixing this, such as using udev to quirk the OSPM for that device to laptop ("2/mobile" I think). Note that using `/etc/machine-info` is a known work-around but I'd rather the bug was fixed out-of-the-box.

My Surface 3 tablet is correctly tagged as a tablet device, the convertible type is only for laptops with non-detachable keyboards.

**Comment by hadess** [comment]
See also:
https://bugzilla.gnome.org/show_bug.cgi?id=764723#c0
and the linked Fedora forum post for more information on the affected systems.

**Comment by benkreuter** [comment]
Laptop is still incorrect for convertible systems; on my Panasonic CF-MX5 I am seeing the system suspend whenever I switch from tablet to laptop form.  If it is possible to add a "convertible" type that would more accurately describe this kind of system, great, let's do it, because none of the current chassis types are correct.

**Comment by hadess** [comment]
> Laptop is still incorrect for convertible systems; on my Panasonic CF-MX5 I am seeing the system suspend whenever I switch from tablet to laptop form.

This is likely completely unrelated.

> If it is possible to add a "convertible" type that would more accurately describe this kind of system, great, let's do it, because none of the current chassis types are correct.

Given that we would only have 2 different types of behaviour, one for tablets, one for non-tablets (eg. laptops), I doubt that adding a new device type is going to solve this particular problem.

**Comment by poettering** [comment]
should be simple enough. Patch always welcome:

https://github.com/systemd/systemd/blob/master/src/hostname/hostnamed.c#L150

**Comment by poettering** [comment]
Fix waiting in #4071.

**Comment by hadess** [comment]
@poettering thanks for looking into that, other things got in the way in the meanwhile...
