### ISSUE TITLE
Unable to use S3 for hybrid-sleep with no swap partition

### ISSUE THREAD

**Issue by bgamari** [systemd/systemd#3937]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230
### Used distribution

> Debian testing
### Description

This laptop has no swap partition and a fair bit of memory so saving an image to disk isn't desirable. Consequently, I have configured `/etc/systemd/sleep.conf` as,

```
[Sleep]
HybridSleepMode=suspend platform
HybridSleepState=mem

SuspendMode=suspend
SuspendState=mem disk
```

Running `sudo /lib/systemd/systemd-sleep hybrid-sleep` works fine. However, attempting to enter hybrid sleep with `systemctl` fails with,

```
$ sudo systemctl hybrid-sleep
Failed to put system into hybrid sleep via logind: Sleep verb not supported
```

Perhaps this is due to a swap partition check?

It seems like it should be easier to use upower/systemd on a swapless system. Perhaps the solution here is simply for `upower` to allow use of normal `sleep` as `CriticalPowerAction`.

**Comment by arvidjaar** [comment]
The obvious question is - what is the reason to use hybrid-sleep instead of simply suspend if you are going to always do suspend anyway.

**Comment by poettering** [comment]
hmm, not following here, what is hybrid-sleep supposed to mean if you turn off suspending-to-disk? I don't follow?

**Comment by bgamari** [comment]
Sorry for the latency!

The problem is that the `CriticalPowerAction` key of `UPower.conf` only accepts `PowerOff`, `Hibernate`, and `HybridSleep`. This ticket stemmed from my attempt at working around this limitation by overriding the behavior of hybrid sleep. That being said, in hindsight it would likely have been better to simply try fixing the upower limitation by allowing `CriticalPowerAction=Sleep` in `UPower.conf`. I've opened [freedesktop bug #97534](https://bugs.freedesktop.org/show_bug.cgi?id=97534) to track this.

**Comment by poettering** [comment]
OK, closing this one then.
