### ISSUE TITLE
logind cannot assume all session can release DRM_MASTER instantly

### ISSUE THREAD

**Issue by mildred** [systemd/systemd#3938]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

chromiumos & debian sid chroot
### Description of the problem

The issue happens when trying to run wayland on chromiumos (see dnschneid/crouton#605). ChromiumOS doesn't have ttys, and they use the DRM device directly, through a layer called freon. They allow to release DRM MASTER using dBus calls to this freon service.

Because such architecture is devoid of tty, logind is a perfect fit to manage the DRM device that might be used my multiple display managers. Weston is compatible with logind and with a minor fix it doesn't require a tty.

Integrating freon with logind is possible my creating a wrapper session. a dBus endpoint that will be seen as a session by logind and that will represent the freon display manager to logind. This wrapper will register to logind, asking for the DRM device. When another session asks logind to get the DRM device, logind will then tell the freon wrapper to pause the device, which will then tell the actual freon display manager to release the DRM MASTER on the device.

The issue is that logind assumes that it can take the device away forcefully, which it can't in this configuration. it's a matter of few milliseconds, but enough that the other display managers notice this and fail to start.

A simple solution would be to have a way to tell logind that the wrapper session cannot release the DRM device immediatly, and instead logind should wait acknowledgement from the session before reusing the device.

Another solution is to change the other display managers to retry acquiring the DRM MASTER a few times at startup before failing. But it may require modifications to many display managers. As such, a solution in logind might be best.
### Details

The problem comes from the signal `org.freedesktop.login1.Session.PauseDevice` when `type` is `"force"`. The session doesn't have any time to release the device as logind already assumes the device is released.

Then, the return value from `org.freedesktop.login1.Session.TakeDevice` to another session contains a valid file descriptor pointing to a DRM device, but lacking the MASTER bit. The return value `inactive` is also true. Weston isn't prepared to be given an inactive device.

As a side note, how is the display manager is supposed to ask logind to activate the device when given an inactive device ? The only way seems to release the device and take it again hoping for an activated one.

See dbus api: https://freedesktop.org/wiki/Software/systemd/logind/

**Comment by poettering** [comment]
@dvdhrm any chance you can explain what is going on here?

**Comment by dvdhrm** [comment]
Wait, what? This does not make sense to me. Is this in any way reproducible or just a theoretical analysis of the scenario? I see the following issues:

1) "force" is never used actively by logind. If you switch sessions by calling into logind, then logind always uses the "try-pause" mechanism, so the display server can release resources.

2) In case of "force", logind releases DRM Master manually. So I cannot see how your scenario can happen. That is, on a session switch, the new session will _always_ get DRM Master. Why would it lack the DRM Master bit? Please elaborate.

3) Why does forcefully dropping DRM Master cause anything to fail? A display server should be able to deal with that. If a page-flip/modeset returns EACCES, it should assume someone else took over. All other resource management ioctl still work (otherwise, please fix the DRM drivers), so this is really just about modesetting.

**Comment by mildred** [comment]
This is not only reproducible but the analysis was done on a live system to try making weston work on a chromiumos distribution on a chrome device (cyan model). See my last comments on dnschneid/crouton#605 which summarize this work.

> 1) "force" is never used actively by logind. If you switch sessions by calling into logind, then logind always uses the "try-pause" mechanism, so the display server can release resources.

My experiments showed me that logind did not wait enough for chrome/freon to be able to release the DRM_MASTER in a timely manner and resumed weston before the device was properly released.

> 2) In case of "force", logind releases DRM Master manually. So I cannot see how your scenario can happen. That is, on a session switch, the new session will always get DRM Master. Why would it lack the DRM Master bit? Please elaborate.

We are in a situation where there is a host operating system (chromiumos) running a guest distribution in a namespace (say fedora, debian, arch, ...) The guest is the one running logind. The chromiumos host is running upstart with a modified chromium browser version that opens directly the DRM device.

As such, we are in a situation where logind is not authoritative. It is started after chrome/freon that already opened the DRM device. It cannot close the DRM device used by chrome/freon because the file descriptor isn't shared.

Fortunately, chrome/freon exposes a dbus API that allows it to release the DRM_MASTER so we can run something else. But this is not instantaneous.

To integrate those two, I wrote a simple wrapper program that runs in the guest operating system and that assumes to be a display manager to logind. This wrapper is the first to start and takes the device from logind but does not uses it. Instead, it reacts to logind pause requests by calling chrome/freon and asking it to release DRM_MASTER.

The issue is that because chrome/freon cannot take a drm file descriptor through dbus, but it can only be instructed to drop or release DRM_MASTER, when logind resumes the wrapper session, the wrapper drops the DRM_MASTER from it ans then instructs chrome/freon to take it. As such, when logind wants to pause the session, logind cannot dropped DRM_MASTER because this file descriptor isn't master. The master is another descriptor in the chrome/freon process that has never been shared with logind.

The wrapper code is there and is still pretty much a work in progress: https://github.com/mildred/crouton/blob/master/src/freonsession.c

See https://github.com/mildred/crouton/blob/master/src/freonsession.c#L586 where the wrapper release the DRM_MASTER as soon as it is resumed from logind.

> 3) Why does forcefully dropping DRM Master cause anything to fail? A display server should be able to deal with that. If a page-flip/modeset returns EACCES, it should assume someone else took over. All other resource management ioctl still work (otherwise, please fix the DRM drivers), so this is really just about modesetting.

Because the file descriptor in logind is not the master when logind drops DRM_MASTER. It's another file descriptor obtained through open(/dev/dri/card0) in a completely separate process that is the master. For a few milliseconds, this device is still master until the dbus call to suspend it finishes.

**Comment by mildred** [comment]
I dropped a bug in the chromiumos bug tracker explaining the issue and providing them with a good solution which would make them compatible with logind: https://bugs.chromium.org/p/chromium/issues/detail?id=643093

**Comment by poettering** [comment]
Closing this, as this appears to be something to fix in the consumers in logind, not in logind self. I hope that makes sense.
