### ISSUE TITLE
journalctl: --directory does not work with --user/--system: Failed to open /var/log/journal: Invalid argument

### ISSUE THREAD

**Issue by blueyed** [systemd/systemd#3949]
I've noticed some inconsistencies when `--user`/`--system` is used with `--file` or `--directory`.

`journalctl --system -D /var/log/journal` fails: "Failed to open /var/log/journal: Invalid argument", but it makes sense to filter user/system messages from there, doesn't it?

On the other hand you can use `--user` and `--system` with `--file`, although it does not appear to be used there (even when not passing in `flags=0` explicitly to `sd_journal_open_files`).  In this case there should be an error (or warning to not break existing scripts)) probably?!
Or would it be possible to actually make use of `--user` and `--system` in that case (although it looks like files are already split into user/system ones by default).

As for the issue with `--directory`:
This comes from the `assert_return` in `sd_journal_open_directory` (last changed in https://github.com/systemd/systemd/commit/d077390#diff-0b3820b06e3db8f255b4a5c7d313aefeR1812).

It seems to never have been supported (https://github.com/systemd/systemd/blob/c85a5a2/src/journal/sd-journal.c#L1752-L1753), but commenting this `assert_return` seems to make it behave as expected.

**Comment by poettering** [comment]
I figure this can be closed now as #3952 and #3946 got merged. Closing. If something isn#t covered yet, please reopen.
