### ISSUE TITLE
systemd-network [Match] Driver=veth does not match interface

### ISSUE THREAD

**Issue by ostcar** [systemd/systemd#395]
I use systemd 221 and there is no configuration file in /etc/systemd/network/. The only systemd-network configuration is the one installed with systemd in /usr/lib/systemd/network. Especial  https://github.com/systemd/systemd/blob/master/network/80-container-ve.network

This configuration does not match the interface created with systemd-nspawn --network-veth. I only works as excepted, when I remove the line "Driver=veth". 

```
$ ethtool -i ve-archlinux
driver: veth
version: 1.0
firmware-version: 
expansion-rom-version: 
bus-info: 
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

**Comment by poettering** [comment]
The code in networkd looks for the ID_NET_DRIVER udev property. And that property is set by the net_setup_link udev builtin, which uses the ethtool apis to get the info.

Can you run this command please:

```
udevadm test-builtin net_setup_link /class/net/ve-archlinux
```

Does this report the ID_NET_DRIVER property properly?

And what about:

```
udevadm info udevadm info /sys/class/net/ve-archlinux
```

**Comment by ostcar** [comment]
In the meantime I installed systemd 222 and now it works.

Here are the output you ask for:

```
$ udevadm test-builtin net_setup_link /class/net/ve-archlinux
calling: test-builtin
=== trie on-disk ===
tool version:          222
file size:         6832754 bytes
header size             80 bytes
strings            1751722 bytes
nodes              5080952 bytes
Load module index
timestamp of '/etc/systemd/network' changed
Parsed configuration file /usr/lib/systemd/network/99-default.link
Created link configuration context.
ID_NET_DRIVER=veth
Assertion 'udev_device' failed at src/libudev/libudev-device.c:126, function udev_device_get_driver(). Ignoring.
Config file /usr/lib/systemd/network/99-default.link applies to device ve-archlinux
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
Unload module index
Unloaded link configuration context.
```

```
$ udevadm info udevadm info /sys/class/net/ve-archlinux
Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
```

**Comment by keszybz** [comment]
> udevadm info udevadm info /sys/class/net/ve-archlinux

Try 'udevadm info /sys/class/net/ve-archlinux'

**Comment by ostcar** [comment]
```
$ udevadm info /sys/class/net/ve-archlinux
Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
```

**Comment by poettering** [comment]
> $ udevadm info /sys/class/net/ve-archlinux
> Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.

That suggests that at the time you invoked that command you didn't actually have a network interface around by that name...

Closing, since you said all works now.
