### ISSUE TITLE
make compilation of bootctl optional

### ISSUE THREAD

**Issue by Flow-It** [systemd/systemd#3959]
#### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
#### systemd version the issue has been seen with

> 231 and earlier

There are many alternatives to bootctl and to me it is an optional feature in systemd. Therefore it should be possible to skip compilation of bootctl via a --disable-bootctl compile option.

**Comment by keszybz** [comment]
It's can be disabled with --disable-efi. This single switch is used for both bootctl and systemd-boot, which is reasonable since they work together.

**Comment by Flow-It** [comment]
Thanks for the commit, this clarifies it.
