### ISSUE TITLE
Periodic timers loop indefinitely when a service fails a condition

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#3963]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

I expected the timer to treat the service with a failed condition as a successful start attempt and wait another timeout.
### In case of bug report: Unexpected behaviour you saw

It keeps trying to start the associated service which keeps failing the condition.
### In case of bug report: Steps to reproduce the problem
1. Make a timer unit and set it to activate `OnUnit{Inactive,Active}Sec`.
2. Make a service unit and set some impossible condition on it.
3. Observe as systemd repeatedly tries to start the service.

Note: I can't just add the condition to the timer because I want the timer to keep trying every timeout (just not every millisecond).

**Comment by evverx** [comment]
I can't reproduce

``` sh
-bash-4.3# systemctl cat hola.timer --no-pager
# /etc/systemd/system/hola.timer
[Timer]
OnBootSec=15min
OnUnitActiveSec=1m

-bash-4.3# systemctl cat hola.service --no-pager
# /etc/systemd/system/hola.service
[Unit]
ConditionPathExists=/some/non/existent/path

[Service]
ExecStart=/bin/sh -x -c 'sleep 1000'

-bash-4.3# journalctl -b --no-hostname -u 'hola*'
Aug 13 18:20:16 systemd[1]: hola.timer: Changed running -> waiting
Aug 13 18:21:16 systemd[1]: hola.timer: Timer elapsed.
Aug 13 18:21:16 systemd[1]: hola.service: Trying to enqueue job hola.service/start/replace
Aug 13 18:21:16 systemd[1]: hola.service: Installed new job hola.service/start as 858
Aug 13 18:21:16 systemd[1]: hola.service: Enqueued job hola.service/start as 858
Aug 13 18:21:16 systemd[1]: hola.timer: Changed waiting -> running
Aug 13 18:21:16 systemd[1]: hola.service: ConditionPathExists=/some/non/existent/path failed.
Aug 13 18:21:16 systemd[1]: hola.service: Starting requested but condition failed. Not starting unit.
Aug 13 18:21:16 systemd[1]: hola.service: Job hola.service/start finished, result=done
Aug 13 18:21:16 systemd[1]: hola.timer: Got notified about unit deactivation.
Aug 13 18:21:16 systemd[1]: hola.timer: Monotonic timer elapses in 59.989538s.
Aug 13 18:21:16 systemd[1]: hola.timer: Changed running -> waiting
Aug 13 18:22:17 systemd[1]: hola.timer: Timer elapsed.
Aug 13 18:22:17 systemd[1]: hola.service: Trying to enqueue job hola.service/start/replace
Aug 13 18:22:17 systemd[1]: hola.service: Installed new job hola.service/start as 906
Aug 13 18:22:17 systemd[1]: hola.service: Enqueued job hola.service/start as 906
Aug 13 18:22:17 systemd[1]: hola.timer: Changed waiting -> running
Aug 13 18:22:17 systemd[1]: hola.service: ConditionPathExists=/some/non/existent/path failed.
Aug 13 18:22:17 systemd[1]: hola.service: Starting requested but condition failed. Not starting unit.
Aug 13 18:22:17 systemd[1]: hola.service: Job hola.service/start finished, result=done
Aug 13 18:22:17 systemd[1]: hola.timer: Got notified about unit deactivation.
Aug 13 18:22:17 systemd[1]: hola.timer: Monotonic timer elapses in 59.964622s.
Aug 13 18:22:17 systemd[1]: hola.timer: Changed running -> waiting
and so on
```

Can you provide your logs and your unit files?

**Comment by Stebalien** [comment]
Sorry, I should have tested more thoroughly. I need a path unit as well to trigger the bug.

`test.path`

```
[Path]
PathExists=/tmp/missing
```

`test.service`

```
[Unit]
ConditionPathExists=/tmp/missing

[Service]
Type=oneshot
ExecStart=/bin/sh -x -c 'sleep 5'
```

`test.timer`

```
[Timer]
OnUnitInactiveSec=30s
#OnBootSec=1s # works with or without this.
```

To reproduce,
1. Start the timer and path units: `systemctl start test.{timer,path}`
2. `touch /tmp/missing`
3. `rm /tmp/missing`
4. Wait for the timer to elapse.

**Comment by vmspike** [comment]
As a temporary workaround you can add the same `Condition`'s to timer's `Unit` section, it helped me.

**Comment by dtardon** [comment]
I think this is fixed by https://github.com/systemd/systemd/pull/21030.

**Comment by Stebalien** [comment]
At the very least, I can no longer reproduce it.
