### ISSUE TITLE
Allow more characters, including Unicode characters, unescaped

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#3966]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 229
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora release 24 (Twenty Four)

This RFE proposes that systemd allow Unicode characters in unit names, as well as other characters like `-`, and that `systemd-escape` not escape such names.  The escaped characters show up in logs and make the logs hard to read.  More importantly, users for whom English is not their native language probably want to be able to write the characters in their language directly in unit files.

**Comment by poettering** [comment]
No, sorry, unit names are on purpose limited to a subset of 7bit ASCII. If you want user-friendly, possibly localized, full-unicode strings use Description=, but not the unit name for that.

Unit names are supposed to be something that may be safely embedded in other strings, protocols and data streams, and that really means that we should stick to a very small subset of the general character set. If we wouldn't then we'd have to deal with a mess of problems regarding normalization, unsafe character checking and so on.

Sorry, but I am strongly against this.

**Comment by DemiMarie** [comment]
Should unit names be considered non-human-readable?  If so (and the closing
of this issue suggests so) they should be unescaped in log files and in
filenames on the filesystem.

**Comment by DemiMarie** [comment]
The other problem is that it is the unit name, not the description, that
the systemd tools take as a parameter.  So users will need to deal with
unit names anyway.

(Your message seems imply that unit names are for systemd's use, not the
user.  In that case, users should not need to read unit names themselves —
they should be unescaped before passing to contexts where users will need
to read them, such as human-readable tool output and in log files.)

On Aug 17, 2016 14:41, "Demi Obenour" demiobenour@gmail.com wrote:

Should unit names be considered non-human-readable?  If so (and the closing
of this issue suggests so) they should be unescaped in log files and in
filenames on the filesystem.

**Comment by keszybz** [comment]
DemiMarie, systemd effectively requires the administrator of the machine to use basic English: not only unit names, but also configuration and commands and logs and status responses are all in English. And even if we allowed unicode unit names, the units provided by systemd itself and the distribution would still be as they are now, so this wouldn't solve anything, but just lead to a mix of English-esque names and localized names. So the benefits from such a change would be small, but it would make everything more complicated. Sorry, systemd is not designed to be an end-user-facing localized application, and it doesn't make much sense to try to make it into one.

**Comment by DemiMarie** [comment]
I know that systemd is not intended to be localized.

Nevertheless, I feel that having filenames that include backslash is
extremely user-unfriendly (it is a shell metacharacter, for one), as is
escaping dash (which often appears in GUIDs and the like).

At the same time, I think I understand where you are coming from: systemd's
existing rules ensure that there is absolutely no ambiguity whatsoever.

My thought process is basically this: systemd is meant to be used on Linux
(only).  Any modern (read: still supported) Linux distribution will
properly handle UTF-8 in output.

So here is my proposal: provide a flag that will cause systemd (and
systemctl) t
- auto-escape unit names passed as command line arguments
- auto

**Comment by DemiMarie** [comment]
Also, I suggest that another flag tell systemd to log the unescaped unit
name alongside the escaped one.

**Comment by DemiMarie** [comment]
Sorry for the incomplete message.  I am on mobile and sending via email.

**Comment by poettering** [comment]
Please note that boot-up and systemctl show generally show _only_ the description string or _also_ the description string. It's only logs which are generally terser. Description strings are never escaped, they are always shown as is.

I'd be fine with putting more emphasis on the description strings, but I don't think we should automatically process unit names. They are supposed to be fixed, constant tokens. They should be identifiers in systemd's dependency processing, but not user-friendly informational strings. 

Many systemctl commands permit users to be sloppy and will escape implicitly if invalid unit names are specified. However, this is really a one-way operation: we cannot reliably know if a unit name is result of such escape-because-sloppy logic or was written the way it was written in the first place...

Hence, if you feel we should show the Description= string at more places, please let us know at which ones precisely, but I am very sure unit names should stay the reduced character set tokens they already are.
