### ISSUE TITLE
systemd-journald does not resume automatically after failed rotation (no free disk space)

### ISSUE THREAD

**Issue by hese10** [systemd/systemd#3968]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Fedora 24 + systemd 231
### In case of bug report: Expected behaviour you didn't see

When root partion is full, journal log rotation fails, and no new logs are seen in "journal -f" output. When disk space is freed, journal logging shuold resume without user restartingservices.
### In case of bug report: Unexpected behaviour you saw

journal logging did not resume when disk space was freed. Only by giving service restart it resumed:
systemctl restart systemd-journald
### In case of bug report: Steps to reproduce the problem

1) delete journal logs from /var/log/journal/_/_
  `rm /var/log/journal/*/*`
2) restart systemd-journald service
   `systemctl restart systemd-journald`
3) check the free space with  df -h -BM /

```
# df -h -BM
Filesystem     1M-blocks  Used Available Use% Mounted on
devtmpfs           3986M    0M     3986M   0% /dev
/dev/vda1          9540M 2822M     6248M  32% /
```

4) fill the root file system with dd command so that we get error "no space left on device"
`# dd if=/dev/zero of=/var/log/journal/fillfile.bin bs=1M count=6244`

5) start logging continuously to journal:
`while [ 1 == 1 ]; do logger -p 3 "testlogging to fill journal current file"  ; sleep 0.01; done;`

6) wait that journal rotation happens, journal -f stops taking new logs, and dmesg output shows error:
`4990.275879] systemd-journald[21722]: Failed to create new system journal: No space left on device`

7) delete the fillfile:
`rm /var/log/journal/fillfile.bin`

8) check the "journal -f" command again, no new logs are seen in journal output

**Comment by hese10** [comment]
@poettering , can this issue be re-opened, as the original correction did not correct totally the situation?

**Comment by davestechshop** [comment]
@poettering I am seeing this issue on Arch Linux with latest updates.
