### ISSUE TITLE
journalctl -n -- wrong output

### ISSUE THREAD

**Issue by jaystrictor** [systemd/systemd#397]
I am running ArchLinux on a Raspberry Pi 2 with
systemd 221
including some cherry-picked [patches](https://github.com/archlinuxarm/PKGBUILDs/blob/3e41f9f654580b5fea80eb45302a1cfd299ddd0d/core/systemd/PKGBUILD#L37-L55).

Strange thing is that `journalctl -e` and `journalctl -e -n100` do not end with the same log messages:

```
[root@gemipi ~]# journalctl -e | tail
Jan 01 01:00:08 gemipi kernel: usbcore: registered new interface driver usbfs
Jan 01 01:00:08 gemipi kernel: usbcore: registered new interface driver hub
Jan 01 01:00:08 gemipi kernel: usbcore: registered new device driver usb
Jan 01 01:00:08 gemipi kernel: Switched to clocksource arch_sys_counter
Jan 01 01:00:08 gemipi kernel: FS-Cache: Loaded
Jan 01 01:00:08 gemipi kernel: CacheFiles: Loaded
Jan 01 01:00:08 gemipi kernel: NET: Registered protocol family 2
Jan 01 01:00:08 gemipi kernel: TCP established hash table entries: 8192 (order: 3, 32768 bytes)
Jan 01 01:00:08 gemipi kernel: TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
Jan 01 01:00:08 gemipi kernel: TCP: Hash tables configured (established 8192 bind 8192)
[root@gemipi ~]# journalctl -e -n100 | tail
Jun 28 16:06:01 gemipi kernel: usb 1-1.2: Product: RF USB Controller
Jun 28 16:06:01 gemipi kernel: usb 1-1.2: Manufacturer: U-COMM
Jun 28 16:06:01 gemipi kernel: input: U-COMM RF USB Controller as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:062A:1A9E.0004/input/input3
Jun 28 16:06:01 gemipi kernel: hid-generic 0003:062A:1A9E.0004: input,hidraw0: USB HID v1.10 Mouse [U-COMM RF USB Controller] on usb-3f980000.usb-1.2/input0
Jun 28 16:06:01 gemipi kernel: input: U-COMM RF USB Controller as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.1/0003:062A:1A9E.0005/input/input4
Jun 28 16:06:01 gemipi kernel: hid-generic 0003:062A:1A9E.0005: input,hidraw1: USB HID v1.10 Keyboard [U-COMM RF USB Controller] on usb-3f980000.usb-1.2/input1
Jun 28 16:06:01 gemipi kernel: input: U-COMM RF USB Controller as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:062A:1A9E.0006/input/input5
Jun 28 16:06:01 gemipi kernel: hid-generic 0003:062A:1A9E.0006: input,hidraw2: USB HID v1.10 Gamepad [U-COMM RF USB Controller] on usb-3f980000.usb-1.2/input2
Jun 28 16:10:26 gemipi systemd[1]: Starting Cleanup of Temporary Directories...
Jun 28 16:10:26 gemipi systemd[1]: Started Cleanup of Temporary Directories.
[root@gemipi ~]# 
```

The second output is correct according to `journalctl -f`.

**Comment by rumpelsepp** [comment]
I can confirm this on my RsapberryPi2 as well.

**Comment by jaystrictor** [comment]
Seems like this is not a problem with the `-e` option, but rather with the `-n` option.

The command `journalctl -nall` works well, so does `journalctl -n193`. In general, any number below or equal to 193 works, while `journalctl -n194` and above seem to seek to the wrong location inside the journal and print the wrong output.

**Comment by poettering** [comment]
Any chance you can provide journal files this is triggered by here? instead of appending all journal files you have, can you look into reducing this to the minimal set of files in your /var/log/journal/ dir, that still causes this issue?

**Comment by jaystrictor** [comment]
GitHub does not support attachments to issues, so I put it here:
https://github.com/jaystrictor/logfiles/raw/master/journal.tar.gz

**Comment by jaystrictor** [comment]
**Ping**

Any update about this?

**Comment by rumpelsepp** [comment]
<s>https://docs.sevenbyte.org/bugreports/journal.tar.gz</s>
edit: not online any more.

**Comment by jaystrictor** [comment]
This issue is still present in systemd 227.
Any news about this?

**Comment by jaystrictor** [comment]
It has now been over a year, since the report. @rumpelsepp and me provided distinct sets of example journal files.

The issue is still present in systemd 231. Are there any plans for fixing this?

**Comment by ryukinix** [comment]
Almost three years and nothing. Systemd being systemd as always.

Great job! :heart:

**Comment by Keensyst** [comment]
I can't get fund's on my bitcoin wallet

**Comment by Chexier** [comment]
https://artixlinux.org/download.php
