### ISSUE TITLE
Confusing documentation referring to `loaded` units, but not actually talking about their load state.

### ISSUE THREAD

**Issue by chaoren** [systemd/systemd#3971]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 231
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Unexpected behaviour you saw

> Confusing documentation referring to `loaded` units, but not actually taking about their load state.
> See https://github.com/systemd/systemd/pull/3967#issuecomment-239996340 for explanation.
### In case of bug report: Steps to reproduce the problem

> ```
> $ systemctl --help | grep loaded
>   -a --all            Show all loaded units/properties, including dead/empty
>   list-units [PATTERN...]         List loaded units
>   list-sockets [PATTERN...]       List loaded sockets ordered by address
>   list-timers [PATTERN...]        List loaded timers ordered by next elapse
> ```

**Comment by poettering** [comment]
Well, it will only list loaded units (as unloaded unit are not known to systemd, that's why they are called unloaded), but not necessary all loaded units. That it only does does when --all is specified.

I think the wording is actually OK the way it is. "list-units" says it shows loaded units, not specifying whether they are all or only some, and what the precise rules are. And then "--all" says it shows all.

I mean, this is all pretty terse, this is after all the --help text, not the full man page. And in the man page this is actually explained in a lot of detail, specifying the precise rules what is shown if --all is not specified.

I'd claim that the --help text and the man page are actually quite OK already. Or do you have specific suggestions what we should print in the --help text instead, that is still terse and precise?

**Comment by chaoren** [comment]
> Well, it will only list loaded units (as unloaded unit are not known to systemd, that's why they are called unloaded), but not necessary all loaded units. That it only does does when --all is specified.

See this [PR I made](https://github.com/systemd/systemd/pull/3967) to enforce that reality, but was told that the `loaded` in the documentation meant something different than the load state. Currently, `not-found` (therefore, not `loaded`) units show up as well with `--all`.

The problem isn't that it doesn't show all loaded units without `--all`, I think that can be inferred with the existence of `--all`, the problem is that it shows units that's not loaded as well, making the description meaningless.

**Comment by poettering** [comment]
Oh, I see what you mean. We have a unit load state called "loaded", but in the --help text we mean by "loaded" that we have the thing in memory, which could also mean "masked" and "not-found".

Hmm, may be can find a better word for "loaded" in the context of the --help text. Maybe we could say "List units currently in memory" there? Does that make sense?

**Comment by chaoren** [comment]
List known units? Discovered units?

**Comment by poettering** [comment]
Hmm, still prefer "in memory" over "known" or "discovered", as the latter would suggest we actually attempted to know them all or discover them all, but of course we never did...

**Comment by chaoren** [comment]
"In memory" sounds very implementation-ey, and doesn't mean much to a non-developer user. I think we should use simple English adjectives in the help text that's at least correct, but possibly nuanced (but not loaded, since that's confusing).

> the latter would suggest we actually attempted to know them all or discover them all

I dunno, did loaded imply that you attempted to load them all?

**Comment by arvidjaar** [comment]
> "In memory" sounds very implementation-ey, and doesn't mean much to a non-developer user.

I second that. What about `list-units - list units currently known to systemd`? This does not convey (to me at least) any sense of discovery and accurately describes what happens in non-technical terms. Besides, next sentence clarifies what "known units" means.

> did loaded imply that you attempted to load them all?

Not to me at least. But I am not unbiased :)

**Comment by poettering** [comment]
fix waiting in #4348.
