### ISSUE TITLE
hostnamectl can not set a hostname when the 64 char is a dot

### ISSUE THREAD

**Issue by toabctl** [systemd/systemd#3979]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> current git version (622a0f628cee51851ad00856f9efddedf0799edb)
### Used distribution

> openSUSE Tumbleweed
### In case of bug report: Expected behaviour you didn't see

I expect that the following command works:

```
hostnamectl set-hostname au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstack.local
```
### In case of bug report: Unexpected behaviour you saw

The error is:

```
Could not set property: Invalid static hostname 'au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstack.'
```
### In case of bug report: Steps to reproduce the problem

Call:

```
hostnamectl set-hostname au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstack.local
```

which fails

but the following commands all work:

```
hostnamectl set-hostname au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstackl.ocal
hostnamectl set-hostname au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstac.klocal
```

This was working with older systemd version (version 210)

**Comment by poettering** [comment]
Note that the hostname you chose is not actually valid for usage as a kernel hostname (Linux only allows hostnames with a max length of 64). hostnamectl hence sets the selected name as "pretty" name, which can be any utf8 string, and sets the kernel hostname to a "cleaned-up" version, that is truncated to a point where it becomes a valid hostname.

**Comment by poettering** [comment]
Hmm, so the thing is that your command actually doesn't result in the error you suggest here, with current git. What you are experiencing suggests you are running a hostnamectl lacking 46e1a2278116e2f5067c35127ccbd8589335f734. Are you sure you have upgraded both hostnamed and hostnamectl from current git?

**Comment by toabctl** [comment]
Hm. Maybe I didn't run the correct versions. So let's simplify the reproducer with adding a unittest:

```
$ git diff
diff --git a/src/test/test-hostname-util.c b/src/test/test-hostname-util.c
index 17fde9f..867772a 100644
--- a/src/test/test-hostname-util.c
+++ b/src/test/test-hostname-util.c
@@ -28,6 +28,7 @@
 static void test_hostname_is_valid(void) {
         assert_se(hostname_is_valid("foobar", false));
         assert_se(hostname_is_valid("foobar.com", false));
+        assert_se(hostname_is_valid("au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstack.local", false));
         assert_se(!hostname_is_valid("foobar.com.", false));
         assert_se(hostname_is_valid("fooBAR", false));
         assert_se(hostname_is_valid("fooBAR.com", false));
```

Now:

```
$ make check
```

Snipped the output but here's the relevant part from `test-suite.log`:

```
FAIL: test-hostname-util
========================

Assertion 'hostname_is_valid("au-xph5-rvgrdsb5hcxc-47et3a5vvkrc-server-wyoz4elpdpe3.openstack.local", false)' failed at src/test/test-hostname-util.c:31, function test_hostname_is_valid(). Aborting.
FAIL test-hostname-util (exit status: 134)
```

Am I missing something?

**Comment by poettering** [comment]
Again, on Linux kernel hostnames are limited to 64chars, and the one you are using is 69 chars long! Run the following to verify this limits from your shell:

```
$ getconf HOST_NAME_MAX
64
```

Note that hostname_is_valid() does _not_ validate whether something is a valid DNS hostname, but whether something is suitable as a local host name to be written into the kernel with sethostname(). DNS permits 255 chars, but the Linux kernel only 64!

Hence, it makes a ton of sense to add your proposed change to the test cases, but it needs to be inverted, as the name you specify is _not_ OK.

**Comment by poettering** [comment]
I posted #3992 now, that explicitly documents the 64char limit. I figure there's nothing else to really to fix here, is there?

**Comment by toabctl** [comment]
Ok. Got it. Thanks!
