### ISSUE TITLE
Support pointing StandardInput/StandardOutput/StandardError to file

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#3991]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

I think it would be useful if the `systemd.exec(5)` options `StandardInput=`, `StandardOutput=` and `StandardError=` supported reading from / writing to files. Of course, this can already be emulated using

``` desktop
ExecStart=/bin/sh -c 'exec /path/to/program arg1 arg2 < inputfile > outputfile'
```

but I think it would be convenient to also support this in the dedicated directives.

Suggested syntax:

``` desktop
StandardInput=</read/from/this/file
StandardOutput=>/write/to/this/file
StandardError=>>/append/to/this/file
```

One open question is that of permissions. What should happen when a service with these options is started?

``` desktop
User=nobody
StandardInput=</etc/shadow # not readable by user
StandardOutput=>/etc/sudoers # not writable at all
```
1. Don’t allow this. Open the file after changing user and group, so that the permissions will be checked against the unit’s user and group and the redirection will fail. (Alternatively, have systemd itself check permissions before changing user and group, but it’s probably best to leave this to the kernel.)
2. Allow this. Open the file before changing user and group. This could be convenient to service authors, but could also be a giant security hole if any user can create or edit service files. On the other hand, this potential security hole probably already exists (`ExecStart=cp /protected/file /public/location`).
3. Allow this, but require explicit specification of the intent to ignore permissions with some special syntax like `StandardInput=!</read/this/protected/file`.

**Comment by davide125** [comment]
:+1: We've seen issues in the past where processes logging a copious amount of data would end up stuck or receive SIGPIPE if systemd-journald becomes too slow or otherwise unhealthy. Being able to bypass it and write directly to files would make things more reliable and simpler for a lot of usecases.

**Comment by lucab** [comment]
I had a similar requirement for rkt (being able to separately redirect stdin/stdout/stderr) and I submitted https://github.com/systemd/systemd/pull/4179 for that. While it doesn't implement the direct write to file syntax suggested above, I think it provides an effective fix for the same usecase.

To demonstrate how it works, I setup a small playground at https://github.com/lucab/systemd-named-fd.

**Comment by lucaswerkmeister** [comment]
That’s a very interesting way to solve the problem, thanks! But does it actually support regular files without a helper program to, e. g., copy from a named pipe to disk?

**Comment by lucab** [comment]
Directly, probably not. As `ListenFIFO=` wants to create a fifo file and `ListenSpecial=` is not happy about regular files. But it may be possible via some workarounds (loop-mounting a file and using the device file) or by growing support for regular files in socket/other units.

**Comment by keszybz** [comment]
There is no need to worry about unprivileged users writing unit files: the security model of systemd requires that only privileged users are allowed to write/start/stop units, so option 2. (always allow opening the file) seems best. In particular this would open the interesting use case of giving access to a file which would otherwise be inacessible to the process.

**Comment by towolf** [comment]
Remember seeing this email from 2012:

https://lists.freedesktop.org/archives/systemd-devel/2012-March/004703.html

**Comment by poettering** [comment]
PR #7198 implements this and is waiting for reviewers!
