### ISSUE TITLE
fix handling/ordering of seccomp(), selinux/aa during service exec

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#3993]
A follow-up from #3970: let's clean up the handling/ordering of post-seccomp code in the service execute path. In particular:
- we should probably set up seccomp last, and do selinux/aa first
- when seccomp is enabled the error path should refrain from logging in order not to trigger any seccomp collisions on its own

**Comment by poettering** [comment]
also, we need to think about no-new-privileges in relation to seccomp (which it often implies) and selinux

**Comment by evverx** [comment]
> we need to think about no-new-privileges in relation to ... selinux

Related:
- [NoNewPrivileges=yes prevents selinux process transitions](https://github.com/systemd/systemd/issues/3845)
- [NoNewPrivileges=yes applied before SELinuxContext=](https://github.com/systemd/systemd/issues/3852)

Some helpful links:
- https://github.com/torvalds/linux/blob/d011a4d861ce583466a8ae72a0c8e7f51c8cba4e/security/selinux/hooks.c#L2318
- https://github.com/torvalds/linux/blob/c540521bba5d2f24bd2c0417157bfaf8b85e2eee/Documentation/prctl/no_new_privs.txt#L28

**Comment by poettering** [comment]
My proposed fix is waiting in #4483
