### ISSUE TITLE
systemd update broke usb_modeswitch

### ISSUE THREAD

**Issue by mar04** [systemd/systemd#400]
Hi, recent update of systemd in Arch Linux from 219 to 221 broke usb_modeswitch (at least for me and some other users) - it no longer automatically switches modem's mode, however it still works when executed manually. [Here](https://bbs.archlinux.org/viewtopic.php?pid=1540444) is an Arch forum  thread with some details, please have a look at that.

**Comment by foutrelis** [comment]
According to that forum thread, it's an incompatibility of usb_modeswitch with current systemd and is fixed in version 2.2.3. I have updated the relevant package in Arch so it would be helpful if you checked whether the issue is fixed.

**Comment by mar04** [comment]
Version 2.2.3 works properly, thanks!
