### ISSUE TITLE
When reboot via IPC fails, mention that reboot via signals to PID 1 might still work

### ISSUE THREAD

**Issue by haasn** [systemd/systemd#4002]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

(Although it could be considered a RFE instead, depending on whether you think this is intended behavior or not)
### systemd version the issue has been seen with

> systemd-231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Gentoo Hardened
### In case of bug report: Expected behaviour you didn't see

> `/sbin/reboot`, `/sbin/poweroff` etc. work
### In case of bug report: Unexpected behaviour you saw

> `/sbin/reboot`, /`sbin/poweroff` etc. fail opening some socket (I forgot the exact message)
### In case of bug report: Steps to reproduce the problem
1. Nuke /run (accidentally)
2. Try to reboot the system to fix it

Since logind/systemd is not responsive, the `/sbin/reboot` commands do not work.
### Additional info

Work-around for me is to send signals (SIGRTMIN+5 etc.) to pid1. I think it would be a good idea to have the binaries also do that if the sockets are gone, since it's clearly an emergency situation and letting the user reboot the system as best as possible would be a good idea (IMO).

**Comment by poettering** [comment]
well, it's probably safer to just use "kill" explicitly in this case, in particular as that's usually a shell builtin command, and thus doesn't require an external binary which might not exist either anymore.

I am not sure it's really a good idea to be too automatic when desaster already happened...

**Comment by arvidjaar** [comment]
> Work-around for me is to send signals

`reboot -f` works for me in this case, even when both /run is wiped out and D-Bus is killed. Not sure how TBH, I expected I would need `-ff`.

**Comment by poettering** [comment]
@arvidjaar my educated guess is that the initctl fallback worked for you. systemctl has has a fallback client, and at least older versions of systemd had a fallback server too, so it probably was routed through that for you.

**Comment by haasn** [comment]
@poettering Fair enough, I think you're right. If something really bad happened, it's probably best to let the user know about it explicitly rather than making it seem like things are better than they are and perhaps leaving the user wondering why something broke.

That being said, do you think it would be worth at least adding a small note to the `systemctl` error messages that appear on failure to contact pid1, indicating what signal they can send to pid1 to forcibly trigger the thing they wanted to do?

At best, it saves one angry `man` invocation, and also communicates the fact that `systemctl` is intentionally not doing this automatically (to prevent people from thinking it's a bug). Minor benefit, but the cost doesn't seem high.
