### ISSUE TITLE
older systemd is not able to deal with the new mixed hierarchy

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#4008]
Houston, we have a problem:

```
Spawning container fedora-25 on /var/lib/machines/fedora-25.
Press ^] three times within 1s to kill container.
Failed to mount /etc/resolv.conf in the container, ignoring: No such file or directory
systemd 231 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 25 (Twenty Five)!

Cannot determine cgroup we are running in: No data available
Failed to allocate manager object: No data available
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

@htejun

**Comment by keszybz** [comment]
I'm <strike>not</strike>now working on updating nspawn to autodetect if the systemd inside is new enough.

Update: I typoed now above, which really destroyed the meaning of this sentence. Sorry.

**Comment by htejun** [comment]
Hah, yeah, if the inner systemd doesn't know about cgroup v2, it wouldn't be able to work. I wonder what the right solution is here. Make systemd-nspawn default to always setting up v1 hierarchy?

**Comment by keszybz** [comment]
We discussed this in Berlin, and the tentative idea is to peek into the container root (see my comment above), and unless we confirm that we have a new systemd inside, use v1.

**Comment by martinpitt** [comment]
> peek into the container root

Do we actually have a reasonably safe, decent, and fast way how to do that? There is no `/sbin/init --version`, so this could at most verify if that resolves to anything `/systemd`, call `--version` on that, and parse the version out of that. Is there a less ugly way?

**Comment by wsw70** [comment]
I have the same problem on Ubuntu 16.04 (host and guest). What exactly is going on and, more importantly, is there a way to recover?
