### ISSUE TITLE
minor error in systemd.network man page

### ISSUE THREAD

**Issue by tchernomax** [systemd/systemd#401]
Search for ip_forward in the [man page of systemd.network](https://github.com/systemd/systemd/blob/master/man/systemd.network.xml#L379).

```
     globally turned on in the kernel, with the
      <filename>net.ipv4.ip_forward</filename> and
      <filename>net.ipv4.ip_forward</filename> sysctl
      options.</para>
```

two "net.ipv4.ip_forward" ; I think it should be :

```
      globally turned on in the kernel, with the
      <filename>net.ipv4.ip_forward</filename> and
      <filename>net.ipv4.conf.all.forwarding</filename> sysctl
      options.</para>
```

Or maybe "net.ipv6.conf.all.forwarding".

**Comment by dvdhrm** [comment]
Fixed: https://github.com/systemd/systemd/commit/e2bccc9d9974eb1290653ecfa3ccfd03c313842b
