### ISSUE TITLE
RFE: Teach networkd to configure a bridge without STP

### ISSUE THREAD

**Issue by smurfix** [systemd/systemd#4011]
Configuring a bridge with "brctl", I can tell a bridge to not do STP. I'd like to configure my bridges with systemd-networkd and I need the same feature.

Rationale: When the bridge is used solely to connect a couple of systemd-nspawn-ed vhosts to at most one external port, STP is superfluous.
Worse, some data centers forbid bridged hosts, as in "immediately disable the switch port", causing the system in question to become unreachable until somebody goes there and physically pulls the network plug. This makes sense in general, but not if all one does is to bridge virtual hosts onto a port.

**Comment by poettering** [comment]
Use the STP=no option, see #3903.
