### ISSUE TITLE
systemctl should inform user about lack of [Install] section on disable

### ISSUE THREAD

**Issue by jez9999** [systemd/systemd#4012]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_

When you run `systemctl enable xyz.service` and there is no `[Install]` section for the service, systemd will inform the user about this fact.  However when you `disable` for that service, systemd quietly does nothing.  It should output a similar message informing the user about there being no `[Install]` section, otherwise the user might be confused that, having disabled the service, it still runs (as it is being started up by another service) - and the user instead needs to mask the service.

Also when you try and `disable` a non-existent service, systemd is also silent.  It should display "Failed to execute operation: No such file or directory".

**Comment by poettering** [comment]
Well, "systemctl disable" doesn't care about [Install] at all. It remvoes any appropriate symlinks regardless if they were created manually or via "systemctl enable" (and thus the [install section). As such I think it would be quite misleading if we'd complain here...

**Comment by jez9999** [comment]
Are you meant to ever create the symlinks manually?

**Comment by poettering** [comment]
@jez9999 sure, absolutely. [install] just contains a suggested set of hooks. People can set up services as they wish, and hook them into completely different conditions if they like.

**Comment by keszybz** [comment]
systemctl prints stuff when it disables a service. So when there's nothing to do, the lack of output is informative too. Should we just close this?

**Comment by YHNdnzj** [comment]
Fixed by https://github.com/systemd/systemd/pull/25437
