### ISSUE TITLE
swap unit files will not load if location (What=) has a dash in it

### ISSUE THREAD

**Issue by Buddlespit** [systemd/systemd#4014]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> When creating a swap unit file for mounting, if the location (What=) has a dash in it, the filename will not match location and a swap isn't created:
> /dev/disk/by-label/Swap, unit file name dev-disk-by-label-Swap.swap will give me 'systemd[1]: dev-disk-by-label-Swap.swap: Value of What= and unit name do not match, not loading.'.

If I drop the dash in by-label:
/dev/disk/bylabel/Swap, unit file name dev-disk-bylabel-Swap.swap will give me 'systemd[1]: dev-disk-bylabel-Swap.swap: Job dev-disk-bylabel-Swap.swap/start failed with result 'dependency'.'.
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> Create a .swap unit file that has a location with a dash in it

**Comment by arvidjaar** [comment]
Not a bug. Dash is special in unit names and must be escaped; use `systemd-escape -p` to convert path to the form that can be used as part of unit name.

**Comment by Buddlespit** [comment]
Still doesn't work.

`[root@Pats_Main pat]# cd /dev/disk/by-label
[root@Pats_Main by-label]# ls
Boot  Home  Raid0  Swap  Win10`

`[root@Pats_Main pat]# systemd-escape -p /dev/disk/by-label/Swap
dev-disk-by\x2dlabel-Swap`

Unit filename: dev-disk-by\x2dlabel-Swap.swap
Unit file contents:

`[Unit]
Description=Mount swap at boot

[Swap]
What=/dev/disk/by-label/Swap
Options=default
Priority=100
TimeoutSec=30

[Install]
WantedBy=multi-user.target`

result:

`[root@Pats_Main pat]# systemctl status dev-disk-by\x2dlabel-Swap.swap
dev-disk-byx2dlabel-Swap.swap - /dev/disk/byx2dlabel/Swap
   Loaded: loaded
   Active: failed (Result: exit-code) since Sun 2016-08-21 14:33:22 EDT; 2min 2s ago
     What: /dev/disk/byx2dlabel/Swap
  Process: 2254 ExecActivate=/sbin/swapon /dev/disk/byx2dlabel/Swap (code=exited, status=255)

Aug 21 14:33:22 Pats_Main systemd[1]: Activating swap /dev/disk/byx2dlabel/Swap...
Aug 21 14:33:22 Pats_Main swapon[2254]: swapon: cannot open /dev/disk/byx2dlabel/Swap: No such file or directory
Aug 21 14:33:22 Pats_Main systemd[1]: dev-disk-byx2dlabel-Swap.swap: Swap process exited, code=exited status=255
Aug 21 14:33:22 Pats_Main systemd[1]: Failed to activate swap /dev/disk/byx2dlabel/Swap.
Aug 21 14:33:22 Pats_Main systemd[1]: dev-disk-byx2dlabel-Swap.swap: Unit entered failed state.`

Now, it looks like it might be ignoring the '\' in 'by\2xdlabel'

**Comment by Buddlespit** [comment]
Holy crap! I had to kung-foo the dog-poo out of this!
this is the filename: /etc/systemd/system/dev-disk-by\x2dlable-Swap.swap
I had to:
`#systemctl start dev-disk-by\\x2dlable-Swap.swap  <--note the second '\' .`
`#systemctl enable dev-disk-by\x2dlable-Swap.swap  <--note the lack of the second '\'`

I'm not going to close this because there is ABSOLUTELY NO documentation showing that this maze needs to be traversed. If I add the second front slash to the unit name, then it can't be enabled, it can't find the filename. If I don't add the second front slash to the start command, it won't start.

**Comment by arvidjaar** [comment]
> systemctl status dev-disk-by\x2dlabel-Swap.swap

You do know that `\` has special meaning for _shell_ and that it must be escaped in _shell_ to prevent interpretation by _shell_, do not you?

> there is ABSOLUTELY NO documentation

There is documentation, both in `systemd.swap(5)` and `systemd.unit(5)`, including reference to `systemd-escape(1)`. Do you have constructive suggestions how to improve it?

> If I add the second front slash to the unit name, then it can't be enabled, it can't find the filename.

I can't reproduce it - it works correctly here. It says `no such file or directory` exactly if I _omit_ second backslash (as in your example).

> If I don't add the second front slash to the start command, it won't start.

Of course not. May be you need to read basic tutorial on Unix shell?

**Comment by Buddlespit** [comment]
You're saying that both of the systemctl commands I posted to enable and start are both documented somewhere?
Or are you saying that something else is wrong with my system that makes the systemctl commands (enable and start) require different file patterns?
`filename: /etc/systemd/system/dev-disk-by\x2dlable-Swap.swap`
`#systemctl start dev-disk-by\\x2dlable-Swap.swap <--note the second '\' .`
`#systemctl enable dev-disk-by\x2dlable-Swap.swap <--note the lack of the second '\'`

**Comment by arvidjaar** [comment]
> systemctl commands (enable and start) require different file patterns?

They do not require different file patterns. Please copy and paste full command invocations and their output, as well as `ls -l /etc/systemd/system/multi-user.target.wants` output after `systemctl enable`.

BTW swap units usually are pulled in by swap.target.

**Comment by Buddlespit** [comment]
http://paste.ubuntu.com/23078110/

**Comment by arvidjaar** [comment]
What `type systemctl` shows? Just to be sure it is not aliased to some weird function.

**Comment by Buddlespit** [comment]
[root@Pats_Main pat]# type systemctl
systemctl is hashed (/usr/bin/systemctl)

[pat@Pats_Main ~]$ type systemctl
systemctl is hashed (/usr/bin/systemctl)

**Comment by arvidjaar** [comment]
What shows

```
strace -e trace=execve -f systemctl enable dev-disk-by\\x2dlabel-Swap.swap
strace -e trace=execve -f systemctl enable dev-disk-by\x2dlabel-Swap.swap
```

**Comment by Buddlespit** [comment]
`[root@Pats_Main pat]# strace -e trace=execve -f systemctl enable dev-disk-by\\x2dlabel-Swap.swap
execve("/usr/bin/systemctl", ["systemctl", "enable", "dev-disk-by\x2dlabel-Swap.swap"], [/* 21 vars */]) = 0
Failed to enable unit: No such file or directory
+++ exited with 1 +++`
`[root@Pats_Main pat]# strace -e trace=execve -f systemctl enable dev-disk-by\x2dlabel-Swap.swap
execve("/usr/bin/systemctl", ["systemctl", "enable", "dev-disk-by\x2dlabel-Swap.swap"], [/* 21 vars */]) = 0
+++ exited with 0 +++`

I have to replace a compressor, I'll be gone for about 5-8hrs.

**Comment by arvidjaar** [comment]
Results you get are consistent with strace output. systemctl correctly works with unit names it receives. _Why_ it receives these names is really outside of systemd scope and is something that your shell does.

Oops. Now you edited output and we cannot trust it anymore. Please upload raw unedited output.

**Comment by Buddlespit** [comment]
Actually, i just edited the code tags and added my leaving statement. But, since then, I decided to try the tried and true system repair tool, 'reboot' and everything appears to be working correctly. Sorry to have wasted your time...
