### ISSUE TITLE
[bug] going to rescue (from multi-user) and then back to multi-user causes unusual slowdowns

### ISSUE THREAD

**Issue by msoltyspl** [systemd/systemd#4020]
### systemd version the issue has been seen with

231 (also 230, possibly earlier ones)
### Used distribution

Archlinux
### In case of bug report: Expected behaviour you didn't see

Normally responsive logins.

All log messages are releated to pam_systemd having issues with establishing session (which seem to be related to systemd-logind.service).

Fragment of logs, in which:
- login locally
- do systemctl rescue
- ^D and login locally again (see **connection timeout and ~25s** time jumps at those points)

Aug 22 21:42:29 hakai systemd[1]: Stopping Rescue Shell...
Aug 22 21:42:29 hakai systemd[1]: Listening on Device-mapper event daemon FIFOs.
Aug 22 21:42:29 hakai systemd[1]: Started Forward Password Requests to Wall Directory Watch.
Aug 22 21:42:29 hakai systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
Aug 22 21:42:29 hakai systemd[1]: Started Daily verification of password and group files.
Aug 22 21:42:29 hakai systemd[1]: Started Daily Cleanup of Temporary Directories.
Aug 22 21:42:29 hakai systemd[1]: Listening on D-Bus System Message Bus Socket.
Aug 22 21:42:29 hakai systemd[1]: Reached target Sockets.
Aug 22 21:42:29 hakai systemd[1]: Started Daily rotation of log files.
Aug 22 21:42:29 hakai systemd[1]: Reached target Slices.
Aug 22 21:42:29 hakai systemd[1]: Starting dhcpcd on eno1 (modified)...
Aug 22 21:42:29 hakai systemd[1]: Reached target Paths.
Aug 22 21:42:29 hakai systemd[1]: Reached target Basic System.
Aug 22 21:42:29 hakai systemd[1]: Started D-Bus System Message Bus.
Aug 22 21:42:29 hakai systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.login1': Device or resource busy
Aug 22 21:42:29 hakai systemd[1]: Reached target Timers.
Aug 22 21:42:29 hakai systemd[1]: Starting Login Service...
Aug 22 21:42:29 hakai systemd[1]: Reached target Remote File Systems.
Aug 22 21:42:29 hakai systemd[1]: Starting Permit User Sessions...
Aug 22 21:42:29 hakai systemd[1]: Starting Save/Restore Sound Card State...
Aug 22 21:42:29 hakai systemd[1]: Stopped Rescue Shell.
Aug 22 21:42:29 hakai systemd[1]: Started Permit User Sessions.
Aug 22 21:42:29 hakai systemd[1]: Started Getty on tty1.
Aug 22 21:42:29 hakai systemd[1]: Reached target Login Prompts.
Aug 22 21:42:29 hakai systemd[1]: Started Save/Restore Sound Card State.
Aug 22 21:42:29 hakai systemd-logind[496]: New seat seat0.
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event4 (Power Button)
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event12 (Video Bus)
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event11 (Video Bus)
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event2 (Power Button)
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event1 (Lid Switch)
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event3 (Sleep Button)
Aug 22 21:42:29 hakai systemd-logind[496]: Watching system buttons on /dev/input/event6 (Dell WMI hotkeys)
Aug 22 21:42:29 hakai systemd[1]: Removed slice User Slice of root.
Aug 22 21:42:30 hakai systemd[1]: Reached target Network.
Aug 22 21:42:41 hakai login[501]: pam_unix(login:session): session opened for user root by LOGIN(uid=0)
Aug 22 21:42:41 hakai login[501]: pam_systemd(login:session): pam-systemd initializing
Aug 22 21:42:41 hakai login[501]: pam_systemd(login:session): Asking logind to create session: uid=0 pid=501 service=login type=tty class=user desktop= seat= vtnr=0 tty=tty1 display= remote=no remote_use
Aug 22 21:42:41 hakai systemd-logind[496]: New session c1 of user root.
Aug 22 21:43:06 hakai login[501]: pam_systemd(login:session): Failed to create session: Connection timed out
Aug 22 21:43:06 hakai login[501]: ROOT LOGIN ON tty1
Aug 22 21:43:30 hakai sshd[530]: Accepted publickey for nozo from ...
Aug 22 21:43:30 hakai sshd[530]: pam_unix(sshd:session): session opened for user nozo by (uid=0)
Aug 22 21:43:30 hakai sshd[530]: pam_systemd(sshd:session): pam-systemd initializing
Aug 22 21:43:30 hakai sshd[530]: pam_systemd(sshd:session): Asking logind to create session: uid=1000 pid=530 service=sshd type=tty class=user desktop= seat= vtnr=0 tty= display= remote=yes remote_user=
Aug 22 21:43:30 hakai systemd-logind[496]: New session c2 of user nozo.
Aug 22 21:43:55 hakai sshd[530]: pam_systemd(sshd:session): Failed to create session: Connection timed out
Aug 22 21:43:59 hakai systemd[1]: systemd-logind.service: Start operation timed out. Terminating.
Aug 22 21:44:00 hakai systemd[1]: Failed to start Login Service.
Aug 22 21:44:00 hakai systemd[1]: systemd-logind.service: Unit entered failed state.
Aug 22 21:44:00 hakai systemd[1]: systemd-logind.service: Failed with result 'timeout'.
Aug 22 21:44:00 hakai systemd[1]: systemd-logind.service: Service has no hold-off time, scheduling restart.
Aug 22 21:44:00 hakai systemd[1]: Stopped Login Service.
Aug 22 21:44:00 hakai systemd[1]: Starting Login Service...
Aug 22 21:44:00 hakai systemd-logind[539]: New seat seat0.
Aug 22 21:44:00 hakai systemd-logind[539]: Watching system buttons on /dev/input/event4 (Power Button)

After that log messages "Connection timed out" change to:

Aug 22 21:50:21 hakai login[565]: pam_systemd(login:session): Cannot create session: Already occupied by a session

While this "solves" slow login times, there's still delay between logout and login prompt. _Also attempt to do 'systemctl restart systemd-logind.service' at any point always hangs until the timeout is reached._

Workaround that fixes everything, is systemctl daemon-reload. Furthermore it can even be executed during rescue target (or even added to rescue.service).
### In case of bug report: Steps to reproduce the problem

1) login into fresh system
2) systemctl rescue
3) ^D / logout / etc.

After that it takes a while until login prompt shows or actual login succeedes.

**Comment by poettering** [comment]
When this hangs do you see "dbus-daemon" around? (consider enabling debug-shell.service, so that you get an extra shell on tty9 to check this from, that stays around all the time). If you then issue "busctl", does that finish quickly, or hang, too?

I figure some code here doesn't like if dbus-daemon suddenly disappears.

**Comment by msoltyspl** [comment]
Did some test, it looks as follows:

1) After: normal boot up and console login (to multiuser target):
```
UID        PID  PPID  C    SZ   RSS PSR STIME TTY      STAT   TIME CMD
root         1     0  0 13274  6516   0 12:05 ?        Ss     0:00 /sbin/init
root       155     1  0  5125  3396   3 12:05 tty9     Ss+    0:00 /bin/sh
root       162     1  0 16496 19188   3 12:05 ?        Ss     0:00 /usr/lib/systemd/systemd-journald
root       181     1  0 10932  4192   2 12:05 ?        Ss     0:00 /usr/lib/systemd/systemd-udevd
root       324     1  0 11232  4708   1 12:05 ?        Ss     0:00 /usr/lib/systemd/systemd-logind
dbus       325     1  0  9937  3748   3 12:05 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root       328     1  0 23720  4652   1 12:05 ?        Ss     0:00 login -- root
root       456   328  0  5969  4940   3 12:05 tty1     Ss     0:00  \_ -bash
root       417     1  0  1685   304   2 12:05 ?        Ss     0:00 /usr/bin/dhcpcd -q -w eno1
root       418     1  0 11678  4556   1 12:05 ?        Ss     0:00 /usr/bin/sshd -D
unbound    421     1  0  9152  9452   1 12:05 ?        Ss     0:00 /usr/bin/unbound -d
root       424     1  0 13162  6036   2 12:05 ?        Ss     0:00 /usr/lib/systemd/systemd --user
root       435   424  0 25862  1676   1 12:05 ?        S      0:00  \_ (sd-pam)
```

busctl --system - works normally
busctl --user - works normally

2) After isolate rescue:

```
UID        PID  PPID  C    SZ   RSS PSR STIME TTY      STAT   TIME CMD
root         1     0  0 13307  6588   3 12:05 ?        Ss     0:00 /sbin/init
root       155     1  0  5125  3396   3 12:05 tty9     Ss+    0:00 /bin/sh
root       162     1  0 16496 19596   1 12:05 ?        Ss     0:00 /usr/lib/systemd/systemd-journald
root       181     1  0 10932  4192   1 12:05 ?        Ss     0:00 /usr/lib/systemd/systemd-udevd
root       612     1  0  5705  3320   0 12:08 tty1     Ss     0:00 /bin/sh -c /usr/bin/sulogin; /usr/bin/systemctl --job-mode=fail --no-block default
root       614   612  0  5937  4604   1 12:08 tty1     S      0:00  \_ bash
```
busctl: Failed to connect to bus: Connection refused

3) After return (^D) and subsequent login

notable difference - no systemd --user with child (sd-pam)
```
UID        PID  PPID  C    SZ   RSS PSR STIME TTY      STAT   TIME CMD
root         1     0  0 13340  6632   0 12:26 ?        Ss     0:00 /sbin/init
root       155     1  0  5158  3440   0 12:26 tty9     Ss     0:00 /bin/sh
root       647   155  0  9829  3088   3 12:28 tty9     R+     0:00  \_ ps -eF f
root       158     1  0 17261 20712   3 12:26 ?        Ss     0:00 /usr/lib/systemd/systemd-journald
root       184     1  0 10915  4124   2 12:26 ?        Ss     0:00 /usr/lib/systemd/systemd-udevd
dbus       562     1  0  9937  3860   0 12:26 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root       569     1  0 23720  4476   3 12:26 ?        Ss     0:00 login -- root
root       632   569  0  5937  4476   1 12:27 tty1     Ss+    0:00  \_ -bash
root       624     1  0  1642   288   2 12:27 ?        Ss     0:00 /usr/bin/dhcpcd -q -w eno1
root       625     1  0 11678  4832   1 12:27 ?        Ss     0:00 /usr/bin/sshd -D
unbound    628     1  0  9151 10984   0 12:27 ?        Ss     0:00 /usr/bin/unbound -d
root       646     1  0  9089  2212   3 12:28 ?        Ss     0:00 /usr/lib/systemd/systemd-logind
```

busctl --system works fine
busctl --user: Failed to connect to bus: Connection refused

**Comment by intelfx** [comment]
@poettering Same problem, v232.

A few more clarifications: the "slowdowns" are caused by `Type=dbus` services stuck in "activating" state. Among them there is systemd-logind, NetworkManager and whatever else. At login time, pam_systemd tries to contact systemd-logind and fails, yielding a timeout (I don't quite understand why exactly this happens, but it falls in line with other symptoms).

Could you please give a few pointers which code in PID 1 depends on dbus-daemon not disappearing? This is something to fix; I've just ran into this.

**Comment by intelfx** [comment]
@poettering Ineed, performing a daemon-reexec or daemon-reload after isolating `sysinit.target` helps. I suppose something inside systemd does not watch for system bus going away.

BTW, I noticed that isolate is not fully synchronous — `systemctl isolate` returns a bit earlier before every stop job completes. Is this intended (just want to know before I file a separate bug for that)?

**Comment by poettering** [comment]
@intelfx it's supposed to return as soon as the job for the specified unit is complete. At that point there might very well be further jobs in the queue that haven't been dispatched yet.

So yes, if you notice that "systemctl isolate foobar.target" returns before "foobar.target" is started, then that'd be a bug indeed and deserves a bug report. However, if there are jobs for other units still queued when that succeeds, then that's not considered a bug.

**Comment by intelfx** [comment]
@poettering 

> So yes, if you notice that "systemctl isolate foobar.target" returns before "foobar.target" is started, then that'd be a bug indeed and deserves a bug report. However, if there are jobs for other units still queued when that succeeds, then that's not considered a bug.

OK, sounds sane. But how do I synchronously get to the single-user mode? I cannot write a generic Conflicts= to any other unit.

**Comment by intelfx** [comment]
BTW, which exact feedback on the main issue do you need? I can reproduce this.
