### ISSUE TITLE
Better error reporting when machine-id contains a newline

### ISSUE THREAD

**Issue by K900** [systemd/systemd#4025]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

Arch Linux ARM, on a Scaleway VPS
### Description

I've run into a rather weird issue which took me a while to debug: my `/etc/machine-id` has somehow got a newline mixed in, which led to journald not starting with a generic error: `Failed to open runtime journal: invalid argument`, and blocking half of my system from starting along with it. I regenerated the machine-id with `systemd-firstboot`, but it would be much easier to troubleshoot this kind of stuff if there was a message saying "invalid machine-id" or something like that.

**Comment by falconindy** [comment]
Why not go one step further and just ignore trailing newlines?

**Comment by K900** [comment]
I think trailing newlines may be ignored already. In my case, the newline was inside the machine-id string (I'm still not sure how it got there, and it being a personal throwaway server, I don't exactly care).

**Comment by poettering** [comment]
Hmm, normally, we actually refuse to boot when the machine ID is set but invalid. Did you change the ID during runtime?

But yeah, a nicer error would definitely make sense...

**Comment by K900** [comment]
I'm not exactly sure what happened there. I belive the custom initramfs Scaleway uses fucked up somehow and generated an incorrect machine-id or corrupted it after PID1 startup, but before journald. I didn't dig into it much, but it seems other Scaleway C1 machines experience the same issue with their default Arch image. At a quick glance, it looks like they run systemd-machine-id-setup in a unit, which might be causing a race condition if you're unlucky?

**Comment by poettering** [comment]
it's not supported to change machine IDs during runtime. we have various ways how the machine id can be passed into the machine so that it is in effect during the entire runtime, but changing the machine ID after PID 1 started forking off stuff is explicitly not supported.

**Comment by rdorsch** [comment]
A side effect of this is that all Debian jessie upgrades to stretch break on scaleway and need a manual change of /etc/machine-id:

The user needs to remove the second line of

```
root@scw-790923:~# cat /etc/machine-id 
9d1b906dd5ea40359e2071d29c12aabe
71f
root@scw-790923:~# 
```

manually before the upgrade to stretch.

Otherwise he will see messages like

`logger: socket /dev/log: Connection refused`

and many packages do not upgrade properly.

I hope scaleway can handle this issue properly and not all users on scaleway break their systems after Debian Stretch is released.

**Comment by evverx** [comment]
Related: https://github.com/systemd/systemd/issues/4475

**Comment by poettering** [comment]
Yeah #4475 iskinda the same issue. Closing this one
