### ISSUE TITLE
hwdb: Lenovo Ideapad 500S 13 touchpad

### ISSUE THREAD

**Issue by pilophae** [systemd/systemd#4027]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

The Y-axis resolution for the Lenovo Ideapad 500S 13" touchpad is far too low, which is confirmed by udev reporting the size as 102x28 mm, while the real size is 104x70.

New touchpad hwdb rule:

```
# Lenovo ideapad 500S 13"
evdev:name:AlpsPS/2 ALPS GlidePoint:dmi:*svnLENOVO:*pvrLenovoideapad500S-13ISK*
 EVDEV_ABS_00=125:3953:39
 EVDEV_ABS_01=105:1959:29
 EVDEV_ABS_35=125:3953:39
 EVDEV_ABS_36=105:1959:29
```

Output of `udevadm info /dev/input/event13` after new rule:

```
P: /devices/platform/i8042/serio1/input/input7/event13
N: input/event13
E: DEVNAME=/dev/input/event13
E: DEVPATH=/devices/platform/i8042/serio1/input/input7/event13
E: EVDEV_ABS_00=125:3953:39
E: EVDEV_ABS_01=105:1959:29
E: EVDEV_ABS_35=125:3953:39
E: EVDEV_ABS_36=105:1959:29
E: ID_BUS=i8042
E: ID_INPUT=1
E: ID_INPUT_HEIGHT_MM=28
E: ID_INPUT_TOUCHPAD=1
E: ID_INPUT_TOUCHPAD_INTEGRATION=internal
E: ID_INPUT_WIDTH_MM=102
E: LIBINPUT_DEVICE_GROUP=11/2/8/700:isa0060/serio1
E: LIBINPUT_MODEL_ALPS_TOUCHPAD=1
E: LIBINPUT_MODEL_FIRMWARE_VERSION=700
E: MAJOR=13
E: MINOR=77
E: SUBSYSTEM=input
E: USEC_INITIALIZED=2787401
```

Is any more information required?

**Comment by poettering** [comment]
cc @whot 

Could you please file this as proper PR? If so, the addition will be attributed to you and everything.

**Comment by whot** [comment]
(3953 - 125)/39 == 98 - not the 104mm you specified
(1959-105)/29 == 64 - not the 70mm you specified

shouldn't the resolution be 37 and 27, respectively? A little bit of rounding error is expected, but this seems out of whack

**Comment by pilophae** [comment]
I used the numbers and formula specified by `touchpad-edge-detector`. I haven't seen your formula anywhere. Is [this page](https://wayland.freedesktop.org/libinput/doc/latest/absolute_coordinate_ranges.html) not the authorative resource for this procedure?

**Comment by whot** [comment]
i had a bug in the most recent version of touchpad-edge-detector (libevdev 1.5.3), so if it gave you the resolution directly it was wrong. sorry about that. That page is still correct though, hence my formula above, filled in with your values would be:
(3953 - 125)/104= 37
(1959-105)/70 = 27

unless there's some other bug that t-e-d didn't print out the right width/height?

**Comment by pilophae** [comment]
It did not give me the resolution directly, but it gave me a formula with the numerator filled in, only to add the physical dimensions. The size reported was wrong, which is why I did the calibration. I will run it again and attach the output.

**Comment by pilophae** [comment]
```
touchpad-edge-detector 104x70 /dev/input/event13 
Touchpad AlpsPS/2 ALPS GlidePoint on /dev/input/event13
Move one finger around the touchpad to detect the actual edges
Kernel says:    x [125..3953], y [105..1959]
Touchpad sends: x [132..3954], y [104..1957] |^C

Touchpad size as listed by the kernel: 98x63mm
User-specified touchpad size: 104x70mm
Calculated ranges: 3828/1854

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:AlpsPS/2 ALPS GlidePoint:dmi:bvnLENOVO:bvrDCCN34WW(V2.03):bd12/01/2015:svnLENOVO:pn80Q2:pvrLenovoideapad500S-13ISK:rvnLENOVO:rnLenovoideapad5:rvrSDK0J40709WIN:cvnLENOVO:ct10:cvrLenovoideapad500S-13ISK:*
 EVDEV_ABS_00=132:3954:37
 EVDEV_ABS_01=104:1957:26
 EVDEV_ABS_35=132:3954:37
 EVDEV_ABS_36=104:1957:26
```

It seems I am in the wrong, but I could swear that the resolution numbers were not filled and I was asked to calculate them by simply substituting the physical sizes in mm.

**Comment by pilophae** [comment]
Ah, the previous output must've been from libevdev 1.5.2. I'll open a new PR.
