### ISSUE TITLE
Add --with-support-url to DISTRO_PORTING?

### ISSUE THREAD

**Issue by stefan-it** [systemd/systemd#4032]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

With 4b930ded8391c7552820f8f162b4e6ceebf50ca4 the `--with-support-url` option was added to provide a distribution specific bug report url for catalog entries. So I would like to ask if it makes sense to add this option to `DISTRO_PORTING`? So hopefully every distribution will set their bug tracker url, as I saw several "bug reports" on the `systemd` mailinglist (which is often not the correct place). I could provide a PR is that idea seems reasonable!

**Comment by poettering** [comment]
True! PR very welcome!
