### ISSUE TITLE
RFE: Flag to disable nspawn's directory lock 

### ISSUE THREAD

**Issue by axgkl** [systemd/systemd#4037]
### Submission type
- [x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd-229
### Used distribution

> Fedora 24

---

Heya, 

nspawn sets a dev/inode based lock on the directory containing the filesystem it spawns (except `--read-only` is set).

Avoiding double namespace spawns of the same directory tree w/o a copy on write layer on top of it for sure makes sense to do by default.
But there are, imho, a lot of valid use cases where reusing a filesystem to run different applications within makes a lot of sense. 

So I propose a switch to disable that lock, maybe with a warning. Especially when the container is not booted but used like chroot, as filesystem environment only, for applications to have their required libs around.

Thanks, nspawn in generally totally rocks!

PS:
My current workaround is to create an empty directory and bindmount all top level directories of the other one over (except proc, dev....), then nspawn it. While it works for my use cases I would totally appreciate a future w/o that hack ;-)

**Comment by poettering** [comment]
I figure it would be OK to add an env var or so that would permit turning off the locking nspawn is doing. Not sure it should be documented, since it appears quite hackish to me to disable it, but nevertheless I figure it would be OK to have.

**Comment by axgkl** [comment]
dankeschoen.I'm with you not documenting it prominently - especially not on the `-h` output since it will be used then w/o understanding the implications. On `man` output I suggest to give it (with a warning) since it is always a bit irritating when you discover such things only when reading the source code ;-)

**Comment by poettering** [comment]
Implemented in #4693.

**Comment by axgkl** [comment]
Awesome!

**Comment by poettering** [comment]
Please leave the PR open. #4693 is not merged yet, and when it is merged github will close this issue automatically.
