### ISSUE TITLE
networkd: support for /31 IPv4 addresses (rfc3021)

### ISSUE THREAD

**Issue by jwh** [systemd/systemd#4038]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> systemd 231
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Arch
### In case of bug report: Expected behaviour you didn't see

> When configuring a network address with /31 using networkd, a /31 without a broadcast specified should be present in the route table.
### In case of bug report: Unexpected behaviour you saw

> networkd makes the same wrong assumption that OpenVPN does, that is, all prefix lengths have a broadcast address - this is untrue of a /31 which has neither a network nor a broadcast address.  iproute2 does the correct thing when presented with addresses using cidr notation.

[Note: the workaround by using Peer= isn't appropriate as a /31 should be treated as a normal prefix length such as /30, sans the broadcast address rather than a point to point.]
### In case of bug report: Steps to reproduce the problem

> Configure .network file with Address=1.2.3.4/31, observe incorrect configuration where the broadcast is the same as the second bit of the prefix.

**Comment by joeholden** [comment]
I fixed it in the meantime on my machine with the following horribleness, but it does the job and doesn't seem to break existing configs:

`diff --git a/src/network/networkd-address.c b/src/network/networkd-address.c
index 5498e35..b693f1b 100644
--- a/src/network/networkd-address.c
+++ b/src/network/networkd-address.c
@@ -501,7 +501,10 @@ static int address_acquire(Link *link, Address *original, Address **ret) {
                 in_addr.in.s_addr = in_addr.in.s_addr | htobe32(1);
 
                 /* .. and use last as broadcast address */
-                broadcast.s_addr = in_addr.in.s_addr | htobe32(0xFFFFFFFFUL >> original->prefixlen);
+                if (original->prefixlen > 30)
+                        broadcast.s_addr = 0;
+                else
+                        broadcast.s_addr = in_addr.in.s_addr | htobe32(0xFFFFFFFFUL >> original->prefixlen);
         } else if (original->family == AF_INET6)
                 in_addr.in6.s6_addr[15] |= 1;
 
@@ -601,9 +604,11 @@ int address_configure(
                         return log_error_errno(r, "Could not append IFA_ADDRESS attribute: %m");
         } else {
                 if (address->family == AF_INET) {
-                        r = sd_netlink_message_append_in_addr(req, IFA_BROADCAST, &address->broadcast);
-                        if (r < 0)
-                                return log_error_errno(r, "Could not append IFA_BROADCAST attribute: %m");
+                        if (address->prefixlen < 31) {
+                                r = sd_netlink_message_append_in_addr(req, IFA_BROADCAST, &address->broadcast);
+                                if (r < 0)
+                                    return log_error_errno(r, "Could not append IFA_BROADCAST attribute: %m");
+                        }
                 }
         }`

**Comment by jwh** [comment]
I have fixed it in the meantime on my own machines with the following quick hack and probably not the best solution but it does work and doesn't appear to break existing configs:

```
diff --git a/src/network/networkd-address.c b/src/network/networkd-address.c
index 5498e35..b693f1b 100644
--- a/src/network/networkd-address.c
+++ b/src/network/networkd-address.c
@@ -501,7 +501,10 @@ static int address_acquire(Link *link, Address *original, Address **ret) {
                 in_addr.in.s_addr = in_addr.in.s_addr | htobe32(1);

                 /* .. and use last as broadcast address */
-                broadcast.s_addr = in_addr.in.s_addr | htobe32(0xFFFFFFFFUL >> original->prefixlen);
+                if (original->prefixlen > 30)
+                        broadcast.s_addr = 0;
+                else
+                        broadcast.s_addr = in_addr.in.s_addr | htobe32(0xFFFFFFFFUL >> original->prefixlen);
         } else if (original->family == AF_INET6)
                 in_addr.in6.s6_addr[15] |= 1;

@@ -601,9 +604,11 @@ int address_configure(
                         return log_error_errno(r, "Could not append IFA_ADDRESS attribute: %m");
         } else {
                 if (address->family == AF_INET) {
-                        r = sd_netlink_message_append_in_addr(req, IFA_BROADCAST, &address->broadcast);
-                        if (r < 0)
-                                return log_error_errno(r, "Could not append IFA_BROADCAST attribute: %m");
+                        if (address->prefixlen < 31) {
+                                r = sd_netlink_message_append_in_addr(req, IFA_BROADCAST, &address->broadcast);
+                                if (r < 0)
+                                    return log_error_errno(r, "Could not append IFA_BROADCAST attribute: %m");
+                        }
                 }
         }
```

**Comment by jwh** [comment]
Any chance of this being fixed?

**Comment by q2dg** [comment]
Come on guys...nearly one year ago...
