### ISSUE TITLE
CAN bus networking support in networkd

### ISSUE THREAD

**Issue by hmvp** [systemd/systemd#4042]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> All
### Used distribution

> Custom

I manage my network interfaces with systemd-networkd and the files in systemd/network. I would like to manage my socketcan interfaces in the same way.

This would mean bringing the interface up and configuring it. Can interfaces need (among other settings) to be told the bitrate. See also section 6.5 of https://www.kernel.org/doc/Documentation/networking/can.txt

My proposal would be to add a [SocketCan] section for .network files and maybe some [Match] and [Network] options.

Currently socketcan devices are already visible in networkctl and as .device

**Comment by ssahani** [comment]
@hmvp I have a minimal code but don't have a device to test it with . It would be great if you can 
test it out .

 cat eth0.network

```
[Match]
Name=can0

[CAN]
BitRate=100
```

https://github.com/systemd/systemd/compare/master...ssahani:can?expand

**Comment by mzanders** [comment]
@ssahani I was able to test but it seems that the bitrate is not propagated to the netlink interface as I got a "bitrate not defined yet" error message from the driver upon restarting systemd-networkd with the .network file as you suggested (with BitRate=125000).
I added a UDEV rule to set the bitrate manually (without bringing the interface up) and now the interface is brought up automatically by systemd

Added UDev rule:
`SUBSYSTEM=="net", KERNEL=="can0", RUN+="/usr/sbin/ip link set can0 type can bitrate 125000"
`
I'm very new to systemd so don't know where to start to help debugging.
I'm testing on ArchLinuxArm (beagleboard) with an 8devices usb2can interface on socketcan.

**Comment by ssahani** [comment]
@mzanders  "bitrate not defined yet"  comes from driver I guess that means the netlink messages are going to the driver there it's not able to set or something. I have added more debug messages and pushed a new commit. 

by running 
`SYSTEMD_LOG_LEVEL=debug  ./systemd-networkd`  

we can see these debug messages 

```
vcan0: link_set_can
vcan0: Setting bitrate = 12500
vcan0: link_set_can done
```

Please share your email id so that we can debug this off line  susant@redhat.com.

**Comment by hmvp** [comment]
@ssahani I will try to test it. I just need to figure out how to build a more up to date systemd for our target. (Using Yocto at the moment) It might take a while but I'd really like this to work

**Comment by hmvp** [comment]
Finally got around to properly test this.

I needed to add some stuff to make it compile against the 234 tag (which unfortunately I need to use)
https://github.com/hmvp/systemd/commit/4ae65bc4e445c008297fc603133f6d0aff3ee3de

I also added support for restart-ms and sample point

I get
```
can0: Link state is up-to-date
can0: found matching network '/lib/systemd/network/10-can.network'
can0: link_set_can
can0: Setting bitrate = 250000
can0: Setting sample point = 250000
can0: Setting restart ms = 100
can0: link_set_can done
can0: Bringing CAN link up
can0: Can Set link
can0: Could not set netlink properties CAN : Operation not supported
can0: Failed

```

**Comment by bbergshaven** [comment]
Any updates on this?

**Comment by ssahani** [comment]
```
can0: Could not set netlink properties CAN : Operation not supported
```

U sure the can module is in ?

**Comment by hmvp** [comment]
> U sure the can module is in ?

Yes, I tried figuring out what happens on setting settings. It seems that some message is constructed and send to another program but I cannot find the other side that is supposed to call the ioctls..

**Comment by marckleinebudde** [comment]
I've hacked a bit on this. It's kind of working: https://github.com/marckleinebudde/systemd/commits/can

**Comment by ssahani** [comment]
Ahhh nice  could you please give a PR with original code with your changes another PR.

**Comment by marckleinebudde** [comment]
I'm not sure if I understand what you mean.

**Comment by marckleinebudde** [comment]
Will do, after more testing and cleaning uo.

**Comment by ssahani** [comment]
Ok for  synchronously I think you can put something in the context like the ```link``` address so that you know kind is ```CAN```  you can call this to down if it's up then in the down callback you can recover and do what you want to do. Does that makes sense ?

**Comment by marckleinebudde** [comment]
I think it's working now. :dancing_men:

**Comment by marckleinebudde** [comment]
https://github.com/systemd/systemd/pull/9185
