### ISSUE TITLE
RFE: systemd-resolved: Please add d.f.ip6.arpa to the DNSSEC default negative trust anchors

### ISSUE THREAD

**Issue by canvon** [systemd/systemd#4049]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 230-7 in Debian, systemd master on GitHub

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian stretch/testing

This is a forward of Debian wishlist bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834453 filed by me. Slightly adapted:

`dnssec-trust-anchors.d(5)` says:

> Negative trust anchors are useful to support private DNS subtrees that are not referenced from the Internet DNS hierarchy, and not signed.
> 
> If no negative trust anchor files are configured a built-in set of well-known private DNS zone domains is used as negative trust anchors.

The DNSSEC default negative trust anchors for systemd-resolved seem to be defined in [1]. There are reverse DNS domains for the RFC 1918 address space (10.0.0.0/8, 192.168.0.0/16 etc.) listed, but not for IPv6 Unique Local addresses [2], the equivalent for IPv6.

That means that, when systemd-resolved's DNSSEC support is enabled, site-locally defined reverse DNS for IPv4 private addresses will resolve with systemd-resolved out-of-the-box, while site-locally defined reverse DNS for IPv6 Unique Local addresses will not. It has to be configured as a DNSSEC negative trust anchor, first, which also makes it necessary to configure the systemd-resolved default negative anchors explicitly, too. (This happens as *.negative files in /etc/dnssec-trust-anchors.d/ )

[...]

[2] says:

> Reverse (address-to-name) queries for locally assigned IPv6 Local addresses MUST NOT be sent to name servers for the global DNS, [...].

IPv6 Unique Local addresses reverse DNS should also qualify as a "well-known private DNS zone domain[]", and will "not [be] referenced from the Internet DNS hierarchy" anytime soon. So please include d.f.ip6.arpa in the list of default negative trust anchors.

References:

[1] https://github.com/systemd/systemd/blob/master/src/resolve/resolved-dns-trust-anchor.c#L101

[2] RFC 4193 "Unique Local IPv6 Unicast Addresses", e.g., https://tools.ietf.org/html/rfc4193

**Comment by grawity** [comment]
Shouldn't that also include `c.f.ip6.arpa`? (Last I checked the whole /7 is ULA.)

**Comment by canvon** [comment]
In the RFC, section 3.1, that would be the "L" bit:

> Set to 1 if the prefix is locally assigned. Set to 0 may be defined in the future.

So c is not defined yet, but reserved for central allocation, which I think might have Internet rDNS, then. On the other hand, section 3.2. says:

> Apart from the allocation method, all Local IPv6 addresses behave and are treated identically.

So I don't know. I'd avoid the not-yet-defined c for now, though. (I'm not an RFC expert, though, and can't be completely sure I didn't miss something.)

**Comment by poettering** [comment]
Fix waiting in #4071.
