### ISSUE TITLE
make .mount TimeoutSec= configurable from extended fstab mount options

### ISSUE THREAD

**Issue by disaster123** [systemd/systemd#4055]
### Submission type
- [ x ] Bug report
- [ X ] Request for enhancement (RFE)

It's may be both - i don't know how to solve this.
### systemd version the issue has been seen with

systemd 215 (Debian Jessie) and systemd git master
### Used distribution

Debian Jessie
### In case of bug report: Expected behaviour you didn't see

big btrfs volumes may take up to 10 minutes to mount or in case of ctree regeneration even 4 hours. Big in this case means 40TB+
### In case of bug report: Unexpected behaviour you saw

Aug 28 20:51:18 cloud5-1379 systemd[1]: vmbackup.mount mounting timed out. Killing.
Aug 28 20:52:49 cloud5-1379 systemd[1]: vmbackup.mount mount process still around after SIGKILL. Ignoring.
Aug 28 20:52:49 cloud5-1379 systemd[1]: Failed to mount /vmbackup.

There is no option for fstab to set a timeout on a specific mount point. How can i mount my big btrfs volumes at boot with systemd?
### In case of bug report: Steps to reproduce the problem

create big btrfs volume > 10TB and fill it with data. Then add an entry to fstab and try to boot.

**Comment by johannbg** [comment]
This is neither a bug report nor a feature request and is already covered in systemd see man systemd.mount for details how you can configure your system.

**Comment by disaster123** [comment]
I'm sorry if i missed something. I reread man systemd.mount but can't find the answer. TimeoutSec doesn't seem to be a fstab setting and x-systemd.device-timeout isn't for the mount timeout. What's missing.

**Comment by poettering** [comment]
(Please note that 215 is pretty old, we only track issues with the two most recent systemd versions upstream. )

There's currently no way to encode the mount timeout in fstab. However, you can set it via a .mount drop-in file. Something like this:

``` sh
# mkdir -p /etc/systemd/system/$(systemd-escape --suffix=mount -p /foo/bar/baz).d/
# cat > /etc/systemd/system/$(systemd-escape --suffix=mount -p /foo/bar/baz).d/timeout.conf <<EOF
[Mount]
TimeoutSec=2h
EOF
```

I'll convert this into an RFE to make the same configurable within fstab now, under the assumptions this is what you are asking for. And I figure it's indeed a good idea to add that.

**Comment by johannbg** [comment]
Administrators usually just add the fstab mount options noauto,x-systemd.automount if the mount point is not required in the boot process itself and or create a dropin mount-unit in /etc/systemd/system/, named the same
(encoded-mountpoint.mount) as the dynamically generated mount unit 
located in /run/systemd/generator/ with the following content
[Mount]
TimeoutSec=<10m or 4h in your case> 

Yeah sure having this an fstab option which eliminates the requirement for a mount drop in snippet with just that overwrite would be nice.

In his case it should just be sufficient to add noauto,x-systemd.automount to the fstab entry for /vmbackup

**Comment by disaster123** [comment]
thanks would be a great RFE. Thanks you all.

Will try noauto,x-systemd.automount too.

**Comment by disaster123** [comment]
noauto,x-systemd.automount fails the same way. The same timeout of 90s applies. So a timeout.conf seems to be the only way to fix it right now.
