### ISSUE TITLE
journalctl --disk-usage may report back memory usage instead but call it "on disk". 

### ISSUE THREAD

**Issue by markstos** [systemd/systemd#4059]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229
> _NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.04
### In case of bug report: Expected behaviour you didn't see

> journalctl --disk-usage should not conflate disk usage with memory usage.
### In case of bug report: Unexpected behaviour you saw

`journalctl --disk-usage` reported that 1.3 Gigs of disk were in use, but as seen below, in fact no disk is being used but 1.3 Gigs of _memory_ are in use. The current design can contribute to a belief that your logs are stored on disk when in fact they are not. If a service is crashing and causing your box to reboot, you may be very surprised and dismayed to find you have no persistent logs, despite `journalctl` reporting "disk usage". 

> $ journalctl --disk-usage
> Archived and active journals take up 1.2G on disk.
> $ du -hs /var/log/journal
> du: cannot access '/var/log/journal': No such file or directory
> $ du -hs /run/log/journal
> 1.3G    /run/log/journal
### In case of bug report: Steps to reproduce the problem

> See above.

The kind of output I would expect instead from `--disk-usage` would look like this:

>  Archived and active journals take up 1.2G of memory at /run/log/journal.
> Archived and active journals take up 0G of  at /var/log/journal
### Other references
- [Example of user who is confused why the can't find their logs after reboot](http://unix.stackexchange.com/questions/305926/how-to-log-systemd-watchdog-restarts/306497#306497)

**Comment by poettering** [comment]
Yeah, we could use better wording here. THough I am not sure I like the wording "in memory", as that suggests actually allocated memory to me, and not stuff that is exposed in the file system which /run is... In particular as neither is necessarily in memory but might actually be on disk after all, if swapping is used...

**Comment by markstos** [comment]
@poettering Perhaps use "storage" as a catch-all phrase to cover both memory and disk? It's still useful to know how much is being stored in /var/ vs /run if you are trying to minimize space usage in one or the other, or are in the process of changing settings to or from persistent and want check where the logs are being stored and where they are growing.

**Comment by poettering** [comment]
I think the wording "in the file system" would be a better term that would work, right?

**Comment by markstos** [comment]
Using the wording "in the file system" is technically correct and could apply to either memory or disk depending on the file system, although there may be an assumption that "file system" implies on-disk storage for those less aware of in-memory file systems. I thought the more vague wording "storage" was likely be interpreted as implying disk-only storage, but either wording is better than "on disk".
