### ISSUE TITLE
Protect efivars

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4062]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

Continuing #2402, I think that this issue is serious and requires fixing.
One suggested way to do it is mounting the efifs read-only, and remounting it rw and back only when writing.
The other suggestion is to alter efifs in a way that would disallow removing the files from it.
This issue is really dangerous and I believe that it needs to be fixed, as it may pose serious damage to the system.

**Comment by poettering** [comment]
please do not warm up this discussion again. This is only accessible with privileges, and the kernel has been changed to make this even more difficult to access (as uncommon vars cannot be removed anymore)

Closing hence.
