### ISSUE TITLE
systemd-timesyncd.service has dependency of network.target

### ISSUE THREAD

**Issue by neofang7** [systemd/systemd#4065]
### Submission type
- [ v] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ostro
### In case of bug report: Expected behaviour you didn't see

> The time consumption of system poweroff should be stable, and systemd-timesyncd should not block shutdown procedure.
### In case of bug report: Unexpected behaviour you saw

> System shutdown is blocked by timesyncd, around 5 ~ 8 seconds. Because during shutting down, the network services have stopped, but timesyncd still tries to connect to sync the system time.
>     ~50% reproduce ratio.
### In case of bug report: Steps to reproduce the problem

> type 'systemctl poweroff' serveral times, and check the shutdown logs.

**Comment by geissonator** [comment]
A new bug may be required here but I've been chasing an intermittent hang issue on our openbmc distribution.  My latest update on it can be found here - https://github.com/openbmc/openbmc/issues/1161#issuecomment-311741093

Basically, in around 1 out of every 15 reboots, we're getting the following hang:
```
[  195.434323] systemd[1]: Stopped Permit User Sessions.
[  195.464330] systemd[1]: Stopped target Network.
[  195.494618] systemd[1]: Stopping Network Service...
[  195.524360] systemd[1]: Stopped target Remote File Systems.
[  195.554330] systemd-timesyncd[671]: Network configuration changed, trying to establish connection.
...
[  196.234502] systemd[1]: Reached target System Time Synchronized.
...
[  196.344450] systemd[1]: Starting Network Service...
...
[  198.564437] systemd[1]: Reached target Network.
```

It looks like the systemd-timesyncd is detecting the network service shutdown, and then it's trying to re-establish contact.  It sends a dbus message (before the dbus servers has been shutdown), which seems to then start the systemd-networkd service back up?  This then completely hangs the shutdown process on our system.

We're running v232

**Comment by geissonator** [comment]
I tried a simple fix where I put the systemd-networkd.service as an After= for the systemd-timesyncd.service but hit this:
```
[   10.370000] systemd[1]: systemd-timesyncd.service: Found ordering cycle on systemd-timesyncd.service/start
[   10.370000] systemd[1]: systemd-timesyncd.service: Found dependency on systemd-networkd.service/start
[   10.370000] systemd[1]: systemd-timesyncd.service: Found dependency on dbus.service/start
[   10.370000] systemd[1]: systemd-timesyncd.service: Found dependency on dbus.socket/start
[   10.370000] systemd[1]: systemd-timesyncd.service: Found dependency on sysinit.target/start
[   10.370000] systemd[1]: systemd-timesyncd.service: Found dependency on systemd-timesyncd.service/start
[   10.370000] systemd[1]: systemd-timesyncd.service: Breaking ordering cycle by deleting job systemd-networkd.service/start
[ SKIP ] Ordering cycle found, skipping Network Service
```

**Comment by mbiebl** [comment]
@geissonator systemd-timesyncd.service has ```Before=sysinit.target```, on the other hand networkd requires dbus which requires sysinit.target. This can't work.

If you drop the ```Before=sysinit.target``` I would guess that this should fix the cycle.
This said, systemd-timesyncd is supposed to run rather early before other services so it can fix the clock via /var/lib/systemd/clock, even if it doesn't have network yet at this point.

**Comment by geissonator** [comment]
Thanks @mbiebl , that helped prove it was not the problem (i.e. the change above did what I wanted but I still hit the hang).  Investigation still ongoing in my bug.

**Comment by yuwata** [comment]
I expect #8611, which is already merged, fixes this. Could you test a recent snapshot?

**Comment by yuwata** [comment]
Let's close this. Please reopen if you can reproduce with a recent version.
