### ISSUE TITLE
systemd-networkd doesn't look for unit files generated by systemd-generator

### ISSUE THREAD

**Issue by thinxer** [systemd/systemd#4066]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> ArchLinux
### In case of bug report: Expected behaviour you didn't see

> systemd-networkd discovers and sets up interfaces requested by generated .network file
### In case of bug report: Unexpected behaviour you saw

> systemd-networkd didn't do anything with generated network file
### In case of bug report: Steps to reproduce the problem

> This can be reproduced by generating a `.network` file. The generated file cannot be seen with `systemctl`. However, normal `.network` files in `/etc/systemd/network` and other generated unit files, such as `.mount`, are available with `systemctl`.

**Comment by poettering** [comment]
Hmm? systemd generators are for creating systemd unit files, i.e. .service, .socket, .target and thelike. 

networkd otoh reads .network and .netdev files, which are very different and should not be written by generators. If you want to write them dynamically, simply write a normal tool that is run before networkd.

"systemctl" only lists systemd unit files, it will never list .network files. 

Hence, This bug report is very confusing, I have no idea what you actually are trying to say...

**Comment by thinxer** [comment]
My mistake.  I just noticed that `.network` files are not systemd unit files.  Just writing a `.service` that generates `.network` files and making it run before `network-pre.target` works perfect. Sorry for the confusion.
