### ISSUE TITLE
systemd-init: container's PIDs incorrectly moved to root cgroup (memory/devices/cpu/blkio/cpuacct subsystems)

### ISSUE THREAD

**Issue by audiocricket** [systemd/systemd#4079]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 215-17+deb8u4
### Used distribution

> Debian GNU/Linux 8.5 (jessie) / Kernel 4.4
### In case of bug report: Unexpected behaviour you saw

> When we run LXC containers that otherwise run perfectly fine with their own cgroups and limits set (under /lxc/container_name hierarchy and memory/cpu/blkio/devices/cpuacct subsystems), systemd-init (PID 1 of host system) somehow decides to move all PIDs of those containers into root cgroups of respective subsystems.
> 
> This effectively renders correct containers limits useless. And it happens totally randomly, for what we have seen it can happen minutes after container being started, or yesterday it happened after 12+ hours of containers being run. We really don't know what triggers this, but read on.
> 
> This is correct cgroups setting (run from container):

`cat /proc/1/cgroup`
`11:debug:/lxc/testcontainer`
`10:pids:/lxc/testcontainer`
`9:perf_event:/lxc/testcontainer`
`8:net_cls,net_prio:/lxc/testcontainer`
`7:freezer:/lxc/testcontainer`
`6:devices:/lxc/testcontainer`
`5:memory:/lxc/testcontainer`
`4:blkio:/lxc/testcontainer`
`3:cpu,cpuacct:/lxc/testcontainer`
`2:cpuset:/lxc/testcontainer`
`1:name=systemd:/user.slice/user-0.slice/session-c137.scope/init.scope`

> And this is incorrect:

`cat /proc/1/cgroup`
`11:debug:/lxc/testcontainer`
`10:pids:/lxc/testcontainer`
`9:perf_event:/lxc/testcontainer`
`8:net_cls,net_prio:/lxc/testcontainer`
`7:freezer:/lxc/testcontainer`
`6:devices:/`
`5:memory:/`
`4:blkio:/`
`3:cpu,cpuacct:/`
`2:cpuset:/lxc/testcontainer`
`1:name=systemd:/user.slice/user-0.slice/session-c137.scope/init.scope`

> This is part of strace log of PID 1 (systemd-init on host running containers) where it can be clearly seen that it moves processes into root cgroup (PID 14907 is one of the container's processes, in the strace log there are all of them and for every mentioned subsystem - memory, cpu/cpuacct, devices, blkio):

`1     open("/sys/fs/cgroup/systemd/user.slice/user-0.slice/session-c137.scope/init.scope/cgroup.procs", O_RDONLY|O_CLOEXEC) = 16`
`1     fstat(16, {st_dev=makedev(0, 18), st_ino=404, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=0, st_size=0, st_atime=2016/08/31-22:31:43, st_mtime=2016/08/31-22:31:43, st_ctime=2016/08/31-22:31:43}) = 0`
`1     mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x359789f1000`
`1     read(16, "14907\n", 4096)         = 6`
`1     access("/sys/fs/cgroup/memory", F_OK) = 0`
`1     open("/sys/fs/cgroup/memory/cgroup.procs", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 20`
`1     fstat(20, {st_dev=makedev(0, 22), st_ino=2, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=0, st_size=0, st_atime=2016/08/30-20:25:45, st_mtime=2016/09/01-10:27:18, st_ctime=2016/09/01-10:27:18}) = 0`
`1     mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x359789f0000`
`1     write(20, "14907\n", 6)           = 6`
`1     close(20)                         = 0`

> Can please somebody explain to us why systemd behaves like this? Is this some feature or possible bug? If this is a feature of systemd, how do we prevent this from happening? Also if you think I should pass this issue to Debian folks, please let me know.
### In case of bug report: Steps to reproduce the problem

> Create your favourite container with lxc-create. Apply limits. Start container with lxc-start and wait for this nasty surprise to happen.

**Comment by poettering** [comment]
Sorry, but this is simply not supported. If services want to manage their own cgroup subhierarchy they can do that, but they should do so below their own cgroup and set Delegate=yes on it. See https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/ for details (last section).

It's fine if multiple daemons manage their own subhierarchies of the cgroup tree, but it's not OK to do so in the top of the tree. 

Closing hence.

**Comment by audiocricket** [comment]
Okay, thanks for the explanation. Will play with the Delegate property on services that manage containers. But it's interesting that other subsystems are left intact...
