### ISSUE TITLE
PrivateTmp= doesn't account for symlinked /tmp

### ISSUE THREAD

**Issue by cgwalters** [systemd/systemd#4082]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd-231-3.fc25.x86_64

`tmp.mount` has `ConditionPathIsSymbolicLink=!/tmp`, but if a service specifies `PrivateTmp=yes`, it will fail for e.g. ostree which uses `/tmp -> /sysroot/tmp`.

I'm still a bit uncertain about whether to change ostree or systemd (or both) for this.  We could move ostree to a model where all of / is a tmpfs, and just bind mount in `/usr` like bubblewrap is doing.  Or teach systemd how to follow symlinks for the case of `/tmp`.

**Comment by poettering** [comment]
Hmm, why do you support non-tmpfs /tmp? sounds weird to me...

Coincidentally this should be fixed by #4018.

**Comment by cgwalters** [comment]
https://pagure.io/fedora-atomic/pull-request/13

**Comment by poettering** [comment]
@cgwalters note that #4018 (which fixes your PrivateTmp=) issue also gives you reason to use the ProtectXYZ= stuff on ostree: it adds ProtectSystem=strict which ensures everything is r/o except for a few things that you whitelist. i.e. the blacklist becomes a whilelist, and your /sysroot gets monted r/o hence too.

**Comment by evverx** [comment]
> why do you support non-tmpfs /tmp? sounds weird to me...

https://lists.ubuntu.com/archives/ubuntu-cloud/2016-January/001009.html

> /tmp on tmpfs on cloud-images is not a practical choice today, and
> it's not forward-looking, given the impeding hardware advances.

**Comment by poettering** [comment]
well, /tmp is not for storing huge data. And tmpfs is backed by swap, hence with a tmpfs file system you get the page cache, possibly backed by disk if necessary. With a normal file system you also get the page cache, definitely backed by disk. The only difference is that tmpfs relieves the kernel from actually commiting the stuff to disk, while normal file systems require the kernel to sync everything to disk. Hence, tmpfs almost definitely the better choice in all cases.

**Comment by poettering** [comment]
Closing since #4185 got merged a while back
