### ISSUE TITLE
[RFE][journald]: disabling logging by journal for specific service or set loglevel for service

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4089]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

Hello,
I had the following problem today. My system was remounted in read-only mode because of a strange kernel/firmware/hardware bug (I still don't know the reason for it.. but here are some logs: https://paste.archlinux.de/m-ee6hf/). When I boot again, the bios said 'No HDD'. I tried it two times and then I plugged-out my laptop from the dockingstation and everything was fine. Now everything is operating normal. Strange..

I am afraid that it is a disk-crash. Maybe because of some services who write too often and too much to the journal..

Is there any way to disable logging to a journal? I am looking for a something like `disableJournal=True` in service files or something like: "Do not log normal messages only critical stuff".
I can't find something in the man-page.. maybe you can prove me wrong. If there is really not such a feature I would appreciate it for reducing noise .

**Comment by poettering** [comment]
This is currently not available.

(But do note that journald applies per-service rate-limiting to all log msgs, to make sure that one service running amok cannot fill the disk unbounded and starve other service's log needs)

**Comment by shibumi** [comment]
Does this log limit also apply to oneshot services that are activated via timer every 2-5 seconds? The service has no output, but my journal is full of 'started' 'stopped' 'started' 'stopped'..

**Comment by poettering** [comment]
ah, nah, in that case it is PID1 that is logging, not the service itself...

**Comment by shibumi** [comment]
Yes, and that was the noise I meant. Is there a way to turn off this PID1 logging for a specific service? When a timer activates a service every 2-5 seconds or even just 1-5minutes  it makes a lot of noise.. Would be nice to have a keyword in the service file to turn off this 'start' 'stop' logging.

**Comment by poettering** [comment]
Nope, there's no way to turn this off, currently.

**Comment by peter-w-remote** [comment]
Got the same issue: I have a timer unit which runs every minute to create sar statistics. My journal is filled with Starting... Started., Starting... Started., Starting... Started., 
Wish I could set "MaxLevelStore=<priority level>" specific for each service.

**Comment by james-lawrence** [comment]
general logging configuration for a particular service would be useful.
i.e.) one service we only care about crit level messages, another service we may want debug.

**Comment by aog2000a** [comment]
See also #3045 for per service logging level or maxUse configuration.

**Comment by poettering** [comment]
Fix waiting in #7246
