### ISSUE TITLE
tmpfiles: Too many levels of symbolic links

### ISSUE THREAD

**Issue by blaskovic** [systemd/systemd#4097]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Centos 7.2
### In case of bug report: Expected behaviour you didn't see

```
# success
```
### In case of bug report: Unexpected behaviour you saw

```
Adjusting owner and mode for /run/hello2/hello2.link failed: Too many levels of symbolic links
```
### In case of bug report: Steps to reproduce the problem

```
cat <<\EOF > /etc/tmpfiles.d/hello2.conf
D /run/hello2  1777 foo bar -
f /run/hello2/hello2.test  1777 root bar -
L+ /run/hello2/hello2.link - root bar - /run/hello2/hello2.test
z /run/hello2/hello2.test 1777 root root - -
z /run/hello2/hello2.link - foo bar - -
EOF
systemd-tmpfiles --create
```

**Comment by evverx** [comment]
https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#z

> z
> Adjust the access mode, group and user, and restore the SELinux security context of a file or directory, if it exists. Lines of this type accept shell-style globs in place of normal path names. **Does not follow symlinks.**

**Comment by keszybz** [comment]
Hm, does "does not follow symlinks" mean that we adjust the context/mode/ownership of the symlink itself, or that we refuse to look at the file? I'd think that the former is more useful, but it seems that we implement the latter.

**Comment by poettering** [comment]
either way, the error message definitely could need some love?

**Comment by klausenbusk** [comment]
> Hm, does "does not follow symlinks" mean that we adjust the context/mode/ownership of the symlink itself, or that we refuse to look at the file? I'd think that the former is more useful, but it seems that we implement the latter.

I just experienced this today, so it seems like I need to stick to good only `chown` instead of `tmpfiles.d`. I will open a new issue later.

**Comment by klausenbusk** [comment]
Issue submitted.. https://github.com/systemd/systemd/issues/7509
