### ISSUE TITLE
[hwdb] [Mouse Logitech 300s] Some physical buttons do not work

### ISSUE THREAD

**Issue by valeriodean** [systemd/systemd#4099]
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 219
### Used distribution

> Fedora 24

Hi,
I see often patches from pointer devices merged here, so I thought this is the right place to post my issue, if it isn't then sorry and feel free to ignore the following.

The game mouse in topic is this one: 
http://gaming.logitech.com/it-it/product/g300s-gaming-mouse

Basically the buttons G6, G7, G8, G9 (see the link) are not recognised as button but as event of type 3.
This is the evtest output:

[valerio@valerio-casa ~]$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:      Power Button
/dev/input/event1:      Power Button
/dev/input/event2:      Logitech USB Keyboard
/dev/input/event3:      Logitech USB Keyboard
/dev/input/event4:      Logitech G300s Optical Gaming Mouse
/dev/input/event5:      Logitech G300s Optical Gaming Mouse
/dev/input/event6:      HDA Intel PCH Front Mic
/dev/input/event7:      HDA Intel PCH Rear Mic
/dev/input/event8:      HDA Intel PCH Line
/dev/input/event9:      HDA Intel PCH Line Out Front
/dev/input/event10:     HDA Intel PCH Line Out Surround
/dev/input/event11:     HDA Intel PCH Line Out CLFE
/dev/input/event12:     HDA Intel PCH Front Headphone
/dev/input/event13:     HDA NVidia HDMI/DP,pcm=3
/dev/input/event14:     HDA NVidia HDMI/DP,pcm=7
/dev/input/event15:     HDA NVidia HDMI/DP,pcm=8
/dev/input/event16:     HDA NVidia HDMI/DP,pcm=9

When I select the event4, I can see the input coming from the left click button, right click button, wheel up, wheel down, wheel click, G4 and G5. These are the functionality that works out of the box.
The event type I can see are as follow:
Event: time 1473098119.954954, -------------- SYN_REPORT ------------
Event: time 1473098131.142799, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1473098131.142799, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1473098131.142799, -------------- SYN_REPORT ------------
Event: time 1473098131.320795, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1473098131.320795, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1473098131.320795, -------------- SYN_REPORT ------------
Event: time 1473098152.812500, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1473098152.812500, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1473098152.812500, -------------- SYN_REPORT ------------
Event: time 1473098153.010495, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1473098153.010495, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1473098153.010495, -------------- SYN_REPORT ------------
Event: time 1473098154.404464, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1473098154.404464, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1473098154.404464, -------------- SYN_REPORT ------------
Event: time 1473098155.260465, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1473098155.260465, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0

When I select event5, I can see the input coming from all the buttons that do not work out of the box and the evtest show the following for them:

Select the device event number [0-16]: 5
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x46d product 0xc246 version 0x110
Input device name: "Logitech G300s Optical Gaming Mouse"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 129 (KEY_AGAIN)
    Event code 130 (KEY_PROPS)
    Event code 131 (KEY_UNDO)
    Event code 132 (KEY_FRONT)
    Event code 133 (KEY_COPY)
    Event code 134 (KEY_OPEN)
    Event code 135 (KEY_PASTE)
    Event code 136 (KEY_FIND)
    Event code 137 (KEY_CUT)
    Event code 138 (KEY_HELP)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 186 (KEY_F16)
    Event code 187 (KEY_F17)
    Event code 188 (KEY_F18)
    Event code 189 (KEY_F19)
    Event code 190 (KEY_F20)
    Event code 191 (KEY_F21)
    Event code 192 (KEY_F22)
    Event code 193 (KEY_F23)
    Event code 194 (KEY_F24)
    Event code 240 (KEY_UNKNOWN)
  Event type 3 (EV_ABS)
    Event code 40 (ABS_MISC)
      Value      0
      Min        0
      Max      164
    Event code 41 (?)
      Value      0
      Min        0
      Max      164
    Event code 42 (?)
      Value      1
      Min        0
      Max      164
    Event code 43 (?)
      Value      2
      Min        0
      Max      164
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Key repeat handling:
  Repeat type 20 (EV_REP)
    Repeat code 0 (REP_DELAY)
      Value    250
    Repeat code 1 (REP_PERIOD)
      Value     33
Properties:
Testing ... (interrupt to exit)
Event: time 1473098197.384890, type 3 (EV_ABS), code 40 (ABS_MISC), value 128
Event: time 1473098197.384890, type 3 (EV_ABS), code 42 (?), value 0
Event: time 1473098197.384890, type 3 (EV_ABS), code 43 (?), value 0
Event: time 1473098197.384890, -------------- SYN_REPORT ------------
Event: time 1473098197.387888, type 3 (EV_ABS), code 40 (ABS_MISC), value 0
Event: time 1473098197.387888, type 3 (EV_ABS), code 43 (?), value 4
Event: time 1473098197.387888, -------------- SYN_REPORT ------------
Event: time 1473098218.633599, type 3 (EV_ABS), code 41 (?), value 1
Event: time 1473098218.633599, type 3 (EV_ABS), code 43 (?), value 8
Event: time 1473098218.633599, -------------- SYN_REPORT ------------
Event: time 1473098219.017593, type 3 (EV_ABS), code 41 (?), value 0
Event: time 1473098219.017593, -------------- SYN_REPORT ------------
Event: time 1473098221.653556, type 3 (EV_ABS), code 41 (?), value 1
Event: time 1473098221.653556, type 3 (EV_ABS), code 43 (?), value 12
Event: time 1473098221.653556, -------------- SYN_REPORT ------------
Event: time 1473098222.795541, type 3 (EV_ABS), code 41 (?), value 0
Event: time 1473098222.795541, -------------- SYN_REPORT ------------
Event: time 1473098227.542474, type 3 (EV_ABS), code 40 (ABS_MISC), value 128
Event: time 1473098227.542474, type 3 (EV_ABS), code 43 (?), value 13
Event: time 1473098227.542474, -------------- SYN_REPORT ------------
Event: time 1473098227.545470, type 3 (EV_ABS), code 40 (ABS_MISC), value 0
Event: time 1473098227.545470, type 3 (EV_ABS), code 43 (?), value 5
Event: time 1473098227.545470, -------------- SYN_REPORT ------------
Event: time 1473098235.226368, type 3 (EV_ABS), code 40 (ABS_MISC), value 32
Event: time 1473098235.226368, type 3 (EV_ABS), code 43 (?), value 1
Event: time 1473098235.226368, -------------- SYN_REPORT ------------
Event: time 1473098235.506344, type 3 (EV_ABS), code 40 (ABS_MISC), value 0
Event: time 1473098235.506344, -------------- SYN_REPORT ------------
Event: time 1473098237.846333, type 3 (EV_ABS), code 40 (ABS_MISC), value 32
Event: time 1473098237.846333, -------------- SYN_REPORT ------------
Event: time 1473098238.640322, type 3 (EV_ABS), code 40 (ABS_MISC), value 0
Event: time 1473098238.640322, -------------- SYN_REPORT ------------

So, the difference I can notice is that the type of event is no more 1 or 4 but 3 (EV_ABS).

REQUEST:
Is it possible to modify the hardware database related to this mouse in order to have all the buttons recognised as mouse buttons instead of something else? 
Thank you.

P.s.
I can provide other detailed info in case you need it.

**Comment by whot** [comment]
this isn't something that we can fix in the hwdb or in systemd. the G303 has configurable profiles and for some reason it seems to be configured to send abs events for those buttons. To change this you need to change the in-device profiles to send button events instead.

Have a look at https://github.com/libratbag/libratbag, it's a generic library designed for these devices and from a quick check of the git log the G303 is supported so you should be able to reconfigure the mouse.
