### ISSUE TITLE
skip uaccess rules if configured without libacl

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#4107]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

```
$ systemd --version
systemd 231
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT +GNUTLS -ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Linux From Scratch with systemd
### In case of bug report: Expected behaviour you didn't see

> I expected to see no warnings/errors in the journal.
### In case of bug report: Unexpected behaviour you saw

> The log contained the warning below.
> 
> ```
> systemd-udevd[241]: Invalid rule /lib/udev/rules.d/73-seat-late.rules:15: RUN{builtin}: 'uaccess' unknown
> ```
### In case of bug report: Steps to reproduce the problem

> Build systemd with support for file attributes, install it, and start the system with it.

For the archive, here is the rules file.

```
$ nl -ba /lib/udev/rules.d/73-seat-late.rules
     1  #  This file is part of systemd.
     2  #
     3  #  systemd is free software; you can redistribute it and/or modify it
     4  #  under the terms of the GNU Lesser General Public License as published by
     5  #  the Free Software Foundation; either version 2.1 of the License, or
     6  #  (at your option) any later version.
     7  
     8  ACTION=="remove", GOTO="seat_late_end"
     9  
    10  ENV{ID_SEAT}=="", ENV{ID_AUTOSEAT}=="1", ENV{ID_FOR_SEAT}!="", ENV{ID_SEAT}="seat-$env{ID_FOR_SEAT}"
    11  ENV{ID_SEAT}=="", IMPORT{parent}="ID_SEAT"
    12  
    13  ENV{ID_SEAT}!="", TAG+="$env{ID_SEAT}"
    14  
    15  TAG=="uaccess", ENV{MAJOR}!="", RUN{builtin}+="uaccess"
    16  
    17  LABEL="seat_late_end"
```

**Comment by grawity** [comment]
Your systemd was compiled without ACL support (libacl) – it's required since the main point of the uaccess feature is setting device ACLs.

**Comment by paulmenzel** [comment]
Yes, it’s intentionally compiled without ACL support. Can’t the build system remove statements, not working without ACL support, when systemd is build without ACL support?

**Comment by keszybz** [comment]
We could make the uaccess rules optional. libacl is defined as optional.

**Comment by ajeddeloh** [comment]
This has been bugging me for some time. Because the errors come from the rules being parsed and not when the rule is run, all rules with `uaccess` must be seperate/standalone even if they could never be run.

In `73-seat-late.rules` there are the three other lines that change the environment and `TAG`. Are these solely for uaccess's sake and are safe to drop, or does `73-seat-late.rules` need to be broken into two rules files, one of which can be disabled?

It also looks like `70-uaccess.rules` can be dropped when libacl is disabled as well, since all it does is set the `TAG` to include `uaccess`.

**Comment by poettering** [comment]
@ajeddeloh the other stuff in 73-seat-late.rules is about assigning devices to seats, logind uses that information independently of the uaccess stuff...

but yeah if libacl isn't there all of 70-uacess.rules plust that one like of 73-seat-late.rules should go

**Comment by ajeddeloh** [comment]
Should this be closed since https://github.com/systemd/systemd/pull/7992 is merged?

**Comment by keszybz** [comment]
Looks like it. There's just one uaccess refence left:
```
build/src/login/71-seat.rules
12:TAG=="uaccess", SUBSYSTEM!="sound", TAG+="seat"
```
but this shouldn't generate any warnings.
