### ISSUE TITLE
Systemd crash with secure boot enabled on kernel 4.7.2 on Toshiba Satellite

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#4113]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 229
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora 24
### In case of bug report: Expected behaviour you didn't see

> Tolerate problems in the kernel loading of X.509 certificates
### In case of bug report: Unexpected behaviour you saw

> Kernel panic - not syncing: Attempted to kill init! Exit code = 0x0000000b
### In case of bug report: Steps to reproduce the problem

> Boot Fedora 24 on a Toshiba Satellite with Secure Boot enabled and using kernel 4.7.2

This may be a kernel problem, but since the panic message is "Attempted to kill init!" that means that systemd crashed.

**Comment by davidstrauss** [comment]
> "Attempted to kill init!" that means that systemd crashed.

No, it means the kernel attempted to kill init. systemd cannot survive a kernel panic, nor should it try to. This is not a systemd bug.

**Comment by brlin-tw** [comment]
Is there any pointers for the "Attempted to kill init" kernel panic message?

IMO the systemd init process somehow quit itself and the kernel panics because of it, rather than another way around.

Assuming the "Exit code = 0x0000000b" follows is the exist status of systemd init process, is it anywhere in the systemd code that returns 0x0000000b?
