### ISSUE TITLE
rfkill: save/load logic handles the hci0 (bluetooth) device on my Thinkpad X230 incorrectly when the hardware rfkill switch is used

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#4117]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

Debian stretch (testing)
### In case of bug report: Expected behaviour you didn't see

Enabling and then disabling the hardware rfkill button should return things to the previous state.
### In case of bug report: Unexpected behaviour you saw

In https://github.com/systemd/systemd/issues/3026#issuecomment-211980702 @poettering describes the basic function of systemd-rfkill as follows:

> To explain this in different words: systemd-rfkill.service WRITES to a device's rfkill state only when a device is hotplugged (regardless if that is the initial boot-time "hotplug" – which sometimes is called "coldplug" – or actual runtime hotplug), but it SAVES a device's rfkill state each time it changes.

This description appears accurate when looking at [the corresponding source code](https://github.com/systemd/systemd/blob/v231/src/rfkill/rfkill.c#L400).

However, the logic described above fails when I enable the hardware rfkill switch on my Thinkpad X230 and then disable it again. This is because the bluetooth chip (and only that) disappears completely when the hardware rfkill switch is enabled (i.e. all radio devices are turned **off**)  and only reappears when it is disabled again (i.e. all radio devices are turned **on**), presumably because it simply has its power cut off (it's internally connected via USB and you can see the USB disconnect/reconnect clearly in the dmesg).

Unfortunately, it seems that just before turning off, the bluetooth chip changes to "blocked" and systemd-rfkill notices this changes and updates the saved state accordingly. When the device reappears it would normally be unblocked, but systemd-rfkill remembers and applies the previously saved "blocked" state.

Please see the following log for more details:

```
root@shepard:~# # Let's start: Everything is unblocked, the hardware rfkill switch is disabled, i.e. all radios are enabled.
root@shepard:~# rfkill list
0: tpacpi_bluetooth_sw: Bluetooth
    Soft blocked: no
    Hard blocked: no
1: tpacpi_wwan_sw: Wireless WAN
    Soft blocked: no
    Hard blocked: no
3: phy0: Wireless LAN
    Soft blocked: no
    Hard blocked: no
6: hci0: Bluetooth
    Soft blocked: no
    Hard blocked: no
root@shepard:~# grep . /var/lib/systemd/rfkill/*
/var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth:0
/var/lib/systemd/rfkill/pci-0000:03:00.0:wlan:0
/var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth:0
/var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan:0
root@shepard:~# # Everything fine so far, let's monitor systemd-rfkill and then enable the hardware rfkill switch (i.e. disable all radios)
root@shepard:~# journalctl --follow --lines=0 --unit systemd-rfkill
-- Logs begin at Tue 2015-07-14 16:46:04 CEST. --
Sep 09 15:53:56 shepard systemd[1]: Started Load/Save RF Kill Switch Status.
Sep 09 15:57:36 shepard systemd[1]: Starting Load/Save RF Kill Switch Status...
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 3 and type wlan
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'phy0'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '0' to /var/lib/systemd/rfkill/pci-0000:03:00.0:wlan.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 0 and type bluetooth
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'tpacpi_bluetooth_sw'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '0' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 1 and type wwan
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'tpacpi_wwan_sw'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '0' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 0 and type bluetooth
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'tpacpi_bluetooth_sw'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '1' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 1 and type wwan
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'tpacpi_wwan_sw'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '1' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 3 and type wlan
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'phy0'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '1' to /var/lib/systemd/rfkill/pci-0000:03:00.0:wlan.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has changed state with index 6 and type bluetooth
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Operating on rfkill device 'hci0'.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: Saved state '1' to /var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth.
Sep 09 15:57:36 shepard systemd[1]: Started Load/Save RF Kill Switch Status.
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has been removed with index 6 and type bluetooth
^C
root@shepard:~# rfkill list
0: tpacpi_bluetooth_sw: Bluetooth
    Soft blocked: yes
    Hard blocked: yes
1: tpacpi_wwan_sw: Wireless WAN
    Soft blocked: yes
    Hard blocked: yes
3: phy0: Wireless LAN
    Soft blocked: yes
    Hard blocked: yes
root@shepard:~# grep . /var/lib/systemd/rfkill/*
/var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth:1
/var/lib/systemd/rfkill/pci-0000:03:00.0:wlan:1
/var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth:1
/var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan:1
root@shepard:~# # Still, everything fine. Now lets monitor systemd-rfkill again and disable the hardware rfkill button (i.e. enable wireless devices)
root@shepard:~# journalctl --follow --lines=0 --unit systemd-rfkill
-- Logs begin at Tue 2015-07-14 16:46:04 CEST. --
Sep 09 15:57:36 shepard systemd-rfkill[5507]: An rfkill device has been removed with index 6 and type bluetooth
Sep 09 15:58:58 shepard systemd[1]: Starting Load/Save RF Kill Switch Status...
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 3 and type wlan
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'phy0'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '1' to /var/lib/systemd/rfkill/pci-0000:03:00.0:wlan.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 0 and type bluetooth
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'tpacpi_bluetooth_sw'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '1' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 1 and type wwan
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'tpacpi_wwan_sw'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '1' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 0 and type bluetooth
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'tpacpi_bluetooth_sw'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '0' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 1 and type wwan
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'tpacpi_wwan_sw'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '0' to /var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 3 and type wlan
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'phy0'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '0' to /var/lib/systemd/rfkill/pci-0000:03:00.0:wlan.
Sep 09 15:58:58 shepard systemd[1]: Started Load/Save RF Kill Switch Status.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: A new rfkill device has been added with index 7 and type bluetooth.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'hci0'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Loaded state '1' from /var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: An rfkill device has changed state with index 7 and type bluetooth
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Operating on rfkill device 'hci0'.
Sep 09 15:58:58 shepard systemd-rfkill[5584]: Saved state '1' to /var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth.
^C
root@shepard:~# # Let's have a look at the result
root@shepard:~# rfkill list
0: tpacpi_bluetooth_sw: Bluetooth
    Soft blocked: no
    Hard blocked: no
1: tpacpi_wwan_sw: Wireless WAN
    Soft blocked: no
    Hard blocked: no
3: phy0: Wireless LAN
    Soft blocked: no
    Hard blocked: no
7: hci0: Bluetooth
    Soft blocked: yes
    Hard blocked: no
root@shepard:~# grep . /var/lib/systemd/rfkill/*
/var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth:1
/var/lib/systemd/rfkill/pci-0000:03:00.0:wlan:0
/var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth:0
/var/lib/systemd/rfkill/platform-thinkpad_acpi:wwan:0
root@shepard:~# # Hmmm, hci0 has been soft-blocked by systemd-rfkill even though it wasn't blocked in the beginning.
root@shepard:~# 
```
### In case of bug report: Steps to reproduce the problem

This should be reproducible with any machine which:
- has a bluetooth chip connected over USB
- has a hardware rfkill switch
- implements this hardware switch by simply cutting off the power

**Comment by AlexanderKurtz** [comment]
Judging from [this comment](https://bugzilla.gnome.org/show_bug.cgi?id=755967#c7) on another bug report, it seems like @mbiebl might be able to reproduce this; CCing.

**Comment by poettering** [comment]
> Unfortunately, it seems that just before turning off, the bluetooth chip changes to "blocked" and systemd-rfkill notices this changes and updates the saved state accordingly. When the device reappears it would normally be unblocked, but systemd-rfkill remembers and applies the previously saved "blocked" state.

But this really indicates a broken driver, no? Why expose an rfkill device at all if it goes away as soon as you actually use it? I mean: for retrieving the rfkill state of the device it would be useless as it should never show up in "disabled" state for a longer time, because it is either there and "enabled" or entirely gone. And it's also not useful for inducing rfkill changes, because you could only turn it off that way, but never get it back because the entire device is gone when you try to enable it.

To me it really appears as if your laptop driver should be fixed to either provide the rfkill all the time, or not at all, but making it disappear when it is set to off sounds really broken.

Can you please contact the author of that driver about this? This really appears as something to fix in the driver, not work-around in systemd.

**Comment by Frank-Steiner** [comment]
I've the same problem with my Lenovo T520 and I don't think it's sth. that should be fixed in the driver. 

> I mean: for retrieving the rfkill state of the device it would be useless as it should never show up in 
> "disabled" state for a longer time, because it is either there and "enabled" or entirely gone.

This isn't true. The hardware killswitch en-/disables all radio devices at once. So if I only want to use wlan, I must enable it with the hardware switch, and this will enable bluetooth, too. But if I don't want to use that, it should stay soft-blocked. If the bluetooth driver couldn't do that, I had no chance to use wlan while keeping bluetooth blocked (or the other way around).

> To me it really appears as if your laptop driver should be fixed to either provide the rfkill all the 
> time, or not at all, but making it disappear when it is set to off sounds really broken.

When the hardware switch turns devices off, the bluetooth chip is completely removed from linux' POV. Just like it was physically taken out of the laptop.  So what could the driver do about that? The device simply isn't there anymore.

The only way to fix it would be preventing the bluetooth chip being set to "blocked" just before it disappears. I've no idea if that is done by the Linux driver or by a signal from the BIOS. In the latter case I don't think there is any chance that Lenovo would change the bios for all its models...l

At the moment, I must disable systemd-rfkill completely to be able to auto turn-on my bluetooth chip because even soft-enabling in some udev rule doesn't help as systemd-rfkill jumps in after udev and blocks it again. It will take some time as e.g. SLES 12 has systemd-rfkill only in SP2, but I'm sure there will be more and more Lenovo users stepping on this.

Maybe one could solve this in systemd if it was possible to detect if a state change was triggered by the hardware killswitch and ignore the change in this case.

**Comment by poettering** [comment]
As I understood it not only the actualy bluetooth device disappears if rfkill is triggered, but the rfkill device itself too, and that's the bit tht isborked...
