### ISSUE TITLE
Masked units can be started via a non-masked alias

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#4122]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian
### In case of bug report: Expected behaviour you didn't see

Masking `systemd-hostnamed.service` results in hostnamed not being run by dbus activation
### In case of bug report: Unexpected behaviour you saw

Running `hostnamectl` successfully starts the `systemd-hostnamed.service`. One needs to additionally mask `dbus-org.freedesktop.hostname1.service` for the expected behavior to occur.

I think systemd should resolve the alias `dbus-org.freedesktop.hostname1.service` to the final unit, and use the final unit mask status to determine if it should start it or not.

**Comment by mbiebl** [comment]
I've slightly retitled the bug report. This issue is not strictly about dbus activation, but in general an issue that one can start a masked service via a non-masked symlink/alias

**Comment by poettering** [comment]
Yeah, this has been a long-standing issue, and I have no idea to fix this. systemd lazy-loads units, i.e. only follows names actually referenced. Now if you mask a unit under one name, but only reference it under different names, then the masking will not have any effect...

Not sure what we could do about this. One option could be to at least check the [install] section of the unit and use it to at least mask all aliases declared there. While this would fix the dbus issue at hand, it wouldn't be a full fix, as any additional manually created aliases would be unaffected...

**Comment by mbiebl** [comment]
@poettering why not follow the symlink as @fsateler suggested and (also) check the masked state of the resolved unit?

**Comment by poettering** [comment]
The current code doesn't do such a wide search: it just follows the chain of symlinks behind the originally requested name. If additional names are discovered that way they are added to the unit as alias names, but they aren't used for search on their own. We could add that of course, but that would still not cover all cases of masking.

**Comment by fsateler** [comment]
> The current code doesn't do such a wide search: it just follows the chain of symlinks behind the originally requested name.

Maybe it should (I have no idea how much extra work that is). I always understood the idea behind the symlink farm was that the actual symlink target was meaningless, except when pointing outside the unit search path. I think the only way to make that true, is to actually do a full lookup for the new unit name.

**Comment by bpkroth** [comment]
> The current code doesn't do such a wide search: it just follows the chain of symlinks behind the originally requested name. If additional names are discovered that way they are added to the unit as alias names, but they aren't used for search on their own. We could add that of course, but that would still not cover all cases of masking.

I was looking at that a bit, and it seemed like what you're describing mostly happens as a result of the third call to `load_from_path()` from `unit_load_fragment()` in `load-fragment.c`.

I was thinking each of those symlink manual traversals could be turned into something like a `load_from_path()` on the basename of the symlink target instead.  If the unit was found in any of those steps, the source symlink name could be added as an alias and inherit whatever masking or not properties that were found for it.  If the unit wasn't found at all it could "just" fallback to reading the symlink target file directly, which should handle cases like the unit file not being in the default search paths.

Anyways, I was curious why you say that something like that wouldn't cover all masking cases?  It seems like then any name that was requested would (eventually) trigger the loading of the base name and source unit file before the requested name could be listed as loaded and so should handle all lazily loaded units (by induction), no?

I'll also note that the simple suggestion (make sure all aliases listed in the [Install] section are also masked) wouldn't handle this particular case as `dbus-org.freedesktop.hostname1.service` isn't listed as an alias in `systemd-hostnamed.service`.

Thanks,
Brian

**Comment by poettering** [comment]
> Anyways, I was curious why you say that something like that wouldn't cover all masking cases? I

Well, let's say there's one symlink chain a.service → b.service → real.service. And then there's another one c.service → d.service → real.service. All these chains are stored entirely below /usr/lib. Now somebody masks d.service. In this case, requests for c.service and d.service would be recognized as masked. But requests for a.service, b.service or real.service would not be, but probably should be?

**Comment by fsateler** [comment]
> Well, let's say there's one symlink chain a.service → b.service → real.service. And then there's another one c.service → d.service → real.service. All these chains are stored entirely below /usr/lib. Now somebody masks d.service. In this case, requests for c.service and d.service would be recognized as masked. But requests for a.service, b.service or real.service would not be, but probably should be?

I think the behavior you describe is correct. A mask should apply to all "downstream" aliases, but not "upstream" ones. Using the original report units:
- Masking `dbus-org.freedesktop.hostname1.service` should disable dbus activation, but not manual activation
- Masking `systemd-hostnamed.service` should disable all activations.

**Comment by mbiebl** [comment]
> I think the behavior you describe is correct. A mask should apply to all "downstream" aliases, but not "upstream" ones. Using the original report units:
> 
>     Masking dbus-org.freedesktop.hostname1.service should disable dbus activation, but not manual activation
>     Masking systemd-hostnamed.service should disable all activations.

That makes a lot of sense to me. It seems intuitive and like the correct solution.

**Comment by keszybz** [comment]
I think I implemented this when doing the alias/mask/install patches earlier this year (it was a bunch of commits in multiple PRs, so I'm not linking to a specific one).

```console
$ ln -s cake.service ~/.config/systemd/user/cake2.service
$ systemctl --user mask cake
Created symlink /home/zbyszek/.config/systemd/user/cake.service → /dev/null.
$ systemctl --user cat cake2
# /dev/null
$ systemctl --user start cake2
Failed to start cake2.service: Unit cake.service is masked.
```

So at least the general behaviour described in https://github.com/systemd/systemd/issues/4122#issuecomment-254936820 is implemented. If something specific doesn't work, please open a new issue.
