### ISSUE TITLE
Restart counter

### ISSUE THREAD

**Issue by freeseacher** [systemd/systemd#4126]
Provide a metrics for systemd restart feature. 
I want to know how many times systemd already restart my service. 
Taking than data from logs looks like an awful way for me.

Currently there is no metrics for systemd at all. 
That will be a good one for start.

**Comment by evverx** [comment]
> I want to know how many times systemd already restart my service. 

Why?

> Currently there is no metrics for systemd at all. 

What do you mean by "metrics"?
Try `perf probe`+`perf stat/record`, `systemtap` or so to measure (almost) everything

**Comment by freeseacher** [comment]
Restart feature is wonderful thing but it masks problems.  

`systemtap` and `perf` are good enough but they about another side of service. i just want to know 
- how many services online
- how often they are restarted
- how much time timered action took 
  and so on. that metrics not about systemd they are about services that run under it. and of cause i can get that info with external scripting. but in my opinion that is just metrics of systemd

**Comment by keszybz** [comment]
I guess we could export the state of the service-restart machine. We already export various state-change timestamps, but not the restart counter.

**Comment by davidstrauss** [comment]
Why not use `OnFailure=` with a `Type=oneshot` unit specified if you want to notice failure events?

**Comment by freeseacher** [comment]
So to monitor every service on machine i have to double count of services ? 
That definitely not looks like a plan for understanding if my servers goes well or not.

**Comment by arvidjaar** [comment]
@freeseacher you can use templates and pass original unit name as parameter, but I agree that it does not quite answer your request.

**Comment by evverx** [comment]
@freeseacher , do you want to reset these counters?
I mean:
- You see "10 restarts per 5 mins"
- You fix the issue

How does your monitoring tool detect these two cases
- "10 restarts per 5 mins"/fixed
- "10 restarts per 5 mins"/not fixed

?

Anyway, it would be great if you can demonstrate a real life example of the Restart-counter usage

**Comment by poettering** [comment]
I figure we could add this indeed. And I think this was already requested elsewhere before.

(The only problem I see with this is that PID 1 unloads units aggressively, hence we'd keep the counter in memory only as long as the unit is not explicitly stopped)

**Comment by keszybz** [comment]
As an in-between solution, we could extend the restart logs to include a field that specifies which restart in the sequence that is. Then one could just look at the last log entry, without going through the logs and counting.

**Comment by freeseacher** [comment]
Guys, parsing logs to extract metrics ? that is not about 2016 year. 
metrics, metrics!!! they are everywhere
`journalctl --disk-usage` step to the right direction...

**Comment by nysan** [comment]
I guess one usecase could be to attempt self-healing.

1. After X crashes of one application or a group of applications, reboot.
2. After Y crashes within X minutes of application or application group restart, reboot.

**Comment by moonlight16** [comment]
Just having this information is useful on so many levels. 

If you built a daemon service that's never supposed to restart, and a single restart has other impacts throughout the system, but then you found it restarted 1 hour ago.  It sure would be nice to tell if that was just a one time thing (i.e. in the past 30 days it restarted only once), OR has been it restarting a lot (i.e. in the past 24 hours it restarted a dozen times).  The latter would indicate the service (code) is not very stable.  And then other scripts/crons could be implemented to take action for self-healing as was previously suggested.

**Comment by moonlight16** [comment]
...just a followup thought (see previous comment from me).  I suppose one could easily count number of start attempts as follows:

journalctl -u <service_name>.service | grep Starting | wc -l

Note: you can also substitute 'Started' or 'Failed' as the search string as appropriate. 

The only downside I can think of is that system logs can wrap on a very busy system.

**Comment by spiderkeys** [comment]
I would also like to see a feature for tracking number of restarts as well. It is indeed a useful metric for services that are set to auto-restart simply for gauging overall health system health, especially across multiple releases of a piece of software set up to be a restarting service. As @jacohn16 mentions, knowing whether something is a one time odd failure or a general occurrence can help track down problems in my system. 

I don't intend to take any actions directly as a result of this information, but I would like to send this information off of products that have been deployed up to an administration service for software release monitoring purposes.

**Comment by poettering** [comment]
Fix waiting in #6495
