### ISSUE TITLE
Http remote api

### ISSUE THREAD

**Issue by freeseacher** [systemd/systemd#4127]
Hi, 
I am running a cluster with mixed linux distributions. centos/ubuntu/debian. We are using microservices architecture in our app. I am curious is there a way how i can make a dashboard of services running on my cluster.

**Comment by mbiebl** [comment]
I'd say this is out-of-scope for systemd. You can build a solution on top of systemd though, ideally using its D-Bus API. Cockpit might be what you are looking for http://cockpit-project.org/

**Comment by keszybz** [comment]
Yeah, http remote api is out of scope. systemctl can use ssh as transport to access remote servers, but still uses the d-bus api above that. For http cockpit is probably the right answer.
