### ISSUE TITLE
FSS key generation malformed output

### ISSUE THREAD

**Issue by hi117** [systemd/systemd#4134]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Archlinux
### In case of bug report: Expected behaviour you didn't see

> Private part is printed clearly
### In case of bug report: Unexpected behaviour you saw

> Private part is not printed clearly
### In case of bug report: Steps to reproduce the problem

> Ran command journalctl --setup-keys as root.

In setup_keys() in journalctl.c, in the fprintf call containing the string "The new key pair has been generated", additional formatting should be added to prevent confusion. In the current state, the secret key is jammed next to the file name printed, making them non-trivially distinguishable.

I have also confirmed that this issue is present on the latest git version of systemd.

**Comment by keszybz** [comment]
Hm, what exactly is unclear in the message?
In the future in such cases it really helps if you paste the command output instead of describing it in words.
