### ISSUE TITLE
FSS private part leak when ran using sudo

### ISSUE THREAD

**Issue by hi117** [systemd/systemd#4135]
### Submission type
- [ ] Bug report
- [x ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Archlinux
### In case of bug report: Expected behaviour you didn't see

> NA
### In case of bug report: Unexpected behaviour you saw

> NA
### In case of bug report: Steps to reproduce the problem

> NA

When the verification command is run using sudo, a log entry like below is generated by default leaking the private key.
Sep 13 14:25:05 HOST_HERE sudo[28510]:    hi117 : TTY=pts/1 ; PWD=/home/hi117 ; USER=root ; COMMAND=/usr/bin/journalctl --verify --verify-key PRIVATE_KEY_HERE
This log entry cannot be removed because FSS is in place, preventing modification of the logs. A documentation entry should be added noting this and a new flag allowing for interactive input of the private key part should be added to prevent this issue.

**Comment by hi117** [comment]
It was mentioned in #5081 that this was not actually fixed. Was an actual fix added?

**Comment by lucaswerkmeister** [comment]
No, sorry, I should’ve phrased that message differently so GitHub didn’t interpret it to close this issue…
