### ISSUE TITLE
Preventing using the pager at default at "inconvenient" locations

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4136]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

I'm noticing that for example on a virtual terminal commands like "systemctl list-unit-files" use a pager at default. This is useful at places where scrolling back is tricky and a mouse is normally not available like on the console but on a virtual terminal this is in my opinion a bit annoying to scroll trough a pager with the keyboard first while the scrolling capabilities of the virtual terminal are more efficient. So maybe the pager should not be used at default on virtual terminals.

**Comment by keszybz** [comment]
The pager also provides other functions, like horizontal scrolling that the terminal provides. You can always disable the pager on some terminal types by using a conditional in .bashrc or similar, but it seems that the current default is OK for the majority of users.
