### ISSUE TITLE
RFE: in systemctl list-units (and related commands) make unit-type grouping clearer somehow

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4137]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

The output of commands like "systemctl list-unit-files" is at default not sorted. But for example having the unit files sorted alphabetically makes it more easy to make a look at them so maybe this could be the default behavior for commands where it is useful.

**Comment by keszybz** [comment]
Yeah, definitely. It's a bit surprising that we're not doing that already.

**Comment by lucaswerkmeister** [comment]
Is it not already sorted? At least `systemctl list-units` and `systemctl list-unit-files` look to me like they’re sorted – first by unit type (`automount`, `device`, …, `service`, …, `timer`), then by name (case insensitive – see e. g. `NetworkManager.service`).

EDIT: in `src/systemctl.c`, `list_units`, `list_sockets`, `list_timers`, `list_unit_files`, `list_dependencies_one`, `list_machines`, and `show_all` all call `qsort_safe` before doing output, with varying comparison functions (some specific to the unit type).

**Comment by keszybz** [comment]
On Wed, Sep 14, 2016 at 04:22:47AM -0700, Lucas Werkmeister wrote:

> Is it not already sorted? At least `systemctl list-units` and `systemctl list-unit-files` look to me like they’re sorted – first by unit type (`automount`, `device`, …, `service`, …, `timer`), then by name (case insensitive – see e. g. `NetworkManager.service`).

Indeed, they are sorted by service type first, and the alphabetically second.
But that's not very useful, I think we should change it to sort
alphabetically.

**Comment by lucaswerkmeister** [comment]
Well, I disagree, grouping by unit type seems useful to me. If you want to find a specific unit, you should use the pager’s search function IMO (`/` – even `more` has it!).

**Comment by Sworddragon** [comment]
Maybe the issue is then just that it is not obvious when and which new unit type begins. Just an idea: If a new unit type begins the type gets printed in uppercase with an empty STATE and all units are indented (for example by 1 space). That makes it easy to distinguish between the different types and see the units in them easily sorted alphabetically.

**Comment by poettering** [comment]
so, yeah, everything is sorted by default, but takes unit types into account as first sort key. I think that makes a ton of sense the way it is. Not sure how we can make clearer where a new type begins. Given that people process the output of these commands with their scripts I am not convinced we can change the output too drastically (i.e adding additional lines to the output for purely decorative purposes sounds suboptimal to me)

One option might be to to use the ANSI sequences for underlining to insert horizontal lines between the table header and between the blocks for each unit type. As we strip ANSI sequences automatically when being invoked for a pipe this is probably an OK solution. Any other ideas?

**Comment by Sworddragon** [comment]
That applications try to not change the format of their existing output to not break scripts of others seems to be not that uncommon. While relying on the output of applications is valid I think it is also risky and the developers should expect any breakage soon as application output is not as reliable as an API.

But I'm fine with simple improvements that keep compatibility. The alternative would be maybe to use a deprecating concept for the output like command line options that toggle between it (or allow direct formatting) which defaults to the old output but deprecates it and switches to the new output after some time.
