### ISSUE TITLE
Typos in the manpage

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4142]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev
### In case of bug report: Unexpected behaviour you saw

> "man systemctl" contains the string "This commands expects a unit uname only".
### In case of bug report: Expected behaviour you didn't see

> I think "commands" should be "command" and "uname" should be "name" here.

**Comment by keszybz** [comment]
Feel free to open a pull request with those changes. You can even use the github web editor for such changes…

**Comment by kristbaum** [comment]
https://github.com/systemd/systemd/pull/4151 
This pull request should fix it

**Comment by martinpitt** [comment]
Merged that, thanks!
