### ISSUE TITLE
mount executed from an udev rule does not mount

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4144]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev
### In case of bug report: Steps to reproduce the problem

> 1. Create the udev rule `ENV{DISK_EJECT_REQUEST}=="", SUBSYSTEM=="block", KERNEL=="sdf1", RUN+="/bin/sh -c '/bin/sleep 5; /bin/mount /dev/sdf1 /mnt 2>&1 > /tmp/test.txt'"` (change sdf1 to your USB flash drive if needed) for example in /etc/udev/rules.d/99-test.rules.
> 2. Restart udev to cause the rule to get loaded.
> 3. Insert your USB flash drive.
### In case of bug report: Unexpected behaviour you saw

> The file /tmp/test.txt got created as empty file indicating that the mount command got executed but "cat /proc/mounts" does not list the USB flash drive and nothing is available in /mnt.
### In case of bug report: Expected behaviour you didn't see

> "cat /proc/mounts" should show the USB flash drive and /mnt should contain its content.

I noticed that an udev rule I have written some time ago to automount devices did stop working so I have created this testcase to demonstrate this. Interestingly if I'm executing "/bin/mount /dev/sdf1 /mnt" all is working fine so I'm wondering why executing mount from an udev rule does then not work anymore.

**Comment by mbiebl** [comment]
This is deliberate. udev rules have their own namespace via MountFlags=slave, so those mounts are only visible to processes started by udev.
What you really want to use is something like udisks2 for your use case.

**Comment by Sworddragon** [comment]
That looks weird to me that explicitly requesting /bin/mount to mount a device does not work. I'm also wondering why this did work in the past. Or is using an own namespace a recent change from udev?

**Comment by arvidjaar** [comment]
@mbiebl 

> This is deliberate. udev rules have their own namespace

Then this should be at least documented. This should be reopened as documentation bug.

@Sworddragon 

> is using an own namespace a recent change from udev?

Added in v212. See NEWS file.

**Comment by mbiebl** [comment]
MountFlags are documented in systemd.exec
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#MountFlags=

**Comment by arvidjaar** [comment]
@mbiebl 

do you expect users to read all unit definitions that come with systemd? When user needs to write rules for udev, user reads `udev(7)` and this should be enough. `udev(7)` does not mention anything about detached namespace.

**Comment by Sworddragon** [comment]
> Added in v212. See NEWS file.

On reading the related documentation mbiebl linked I would now think that the slave namespace was eventually not in effect for me a few days before with udev 231 as I was still on upstart and service files were not used. But is there a special reason why udev is being setup for the slave namespace? It looked useful to me to listen on device events with udev and do local userspace stuff based on them like using an own automounter.

Edit: I have now edited /lib/systemd/system/udev.service to use shared for MountFlags and after a reboot all works fine again. But there was probably a reason why slave got the default and I wonder now which negative side effects could appear.
