### ISSUE TITLE
Unit file with mountpoint dependency gets executed while the mountpoint never exists

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4147]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev
### In case of bug report: Steps to reproduce the problem

> Create the following file in /etc/systemd/system/test.service and then enabled it and reboot the system or execute "systemctl start test.service":
> `[Install]
> RequiredBy=default.target

[Service]
ExecStart=/bin/sh -c 'echo 1 > /tmp/test.txt'

[Unit]
RequiresMountsFor=/does_never_exist`
### In case of bug report: Unexpected behaviour you saw

> /tmp/test.txt got created.
### In case of bug report: Expected behaviour you didn't see

> Because /does_never_exist doesn't exist but its mountpoint is a requirement for the unit file /tmp/test.txt should not be created.

**Comment by mbiebl** [comment]
Is /does_never_exist an actual mount point which is listed in /etc/fstab or has systemd .mount unit?

**Comment by Sworddragon** [comment]
It has none of them. This is why I expect the unit not to be executed as the requirements are not met.

**Comment by arvidjaar** [comment]
@Sworddragon 

You misunderstand what `RequiresMountsFor` does. It adds dependency to mount units that are needed to access this path - _if_ there are mount units covering this path. Otherwise it simply adds requirement for `/` mount point.

**Comment by Sworddragon** [comment]
My next ideas were:
1. Using Restart=always and RestartSec=0 for [Service] and AssertPathIsMountPoint=/media/sdf1 (sdf1 is here an USB flash drive which automounts if inserted). A potential guess was that the unit file asserts and restarts in a loop as long as /media/sdf1 is not mounted but this seems to be not the case.
2. Using OnFailure=test.service (the name of the service itself) and StartLimitIntervalSec=0 to cause the unit file to call itself in a loop as long as /media/sdf1 is not mounted but this seems to be again not the case.

Hm, maybe I will find tomorrow some other variants to cause an unit file to execute if a specific mountpoint appears that is not pre-configured like in /etc/fstab.
