### ISSUE TITLE
Adding ExecStopPre

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4148]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

I'm noticing that https://www.freedesktop.org/software/systemd/man/systemd.service.html lists Execs for a pre-start and a post-start but for stopping there is only a post-stop but not a pre-stop so maybe ExecStopPre could be implemented.

**Comment by arvidjaar** [comment]
Please describe your use case.

**Comment by Sworddragon** [comment]
I had nothing specific in mind. It looks just plausible to me to have ExecStopPre as all the other variants exist too (was there a special reason why this didn't got implemented at the time the others got implemented or got it just missed?). But for example this could be used to post a shutdown message to a running game server to inform the users about shuting down in a minute so that they can prepare for it before ExecStop gets executed to terminate the server.

**Comment by vladlosev** [comment]
We are running a Consul cluster and I would like an ability to tell the server to leave the cluster before stopping it down (it doesn't do that automatically).

```
ExecStopPre=/usr/local/bin/consul leave
```

**Comment by arvidjaar** [comment]
@vladlosev you already can have multiple `ExecStop` lines. What different semantic `ExecStopPre` should have and why using additional `ExecStop` does not work?

**Comment by Sworddragon** [comment]
So it would not make a difference if there would be ExecStopPre since ExecStop can be used multiple times and there would not even be differences in dependencies behavior since the SIGKILL used after the last ExecStop is the actual exit, am I seeing this right? If yes the current ExecStop is probably more like already an ExecStopPre. If this is not wrong maybe ExecStopPre should then be an alias of ExecStop (eventually by keeping a logical ordering).

**Comment by vladlosev** [comment]
My mistake - I didn't know ExecStop can be specified multiple times. Are the ExecStop invocations serialized?

**Comment by arvidjaar** [comment]
@vladlosev Yes, multiple command lines are executed sequentially.

**Comment by vladlosev** [comment]
Thanks!

**Comment by bothra90** [comment]
@arvidjaar: We have an important use case for this. Expectation is for the behavior to be same as that of upstart pre-stop stanza (http://upstart.ubuntu.com/cookbook/#id190). We utilize this to determine if the service was stopped via 'sudo service <name> stop' or if it crashed by itself. In the former case, we take some action. If not for ExecStopPre, is there a way to accomplish this in systemd?

**Comment by poettering** [comment]
@bothra90 this is not a support forum. If you need help with systemd, please contact the systemd mailing list. Thank you for your understanding.

**Comment by bothra90** [comment]
@poettering: Thanks for the pointer. Since this issue seemed related, I thought it'd give more context. Anyway, I'll post on the mailing list

**Comment by ReubenM** [comment]
I have a question regarding the ordering of the ExecStop (and lack of ExecStopPre).

I'm wanting to modify a service using a service.d drop-in in /etc/systemd. I want to run a short cleanup script before the default ExecStop process runs, but with this being in a separate file, how am I to be sure it will run first? Does systemd explicitly append elements from the drop-ins before or after the corresponding elements in the default service file, or is there no such guarantee to ordering?

If there is no means to assure the ExecStop in the drop-in is run first then I would like to request that you consider re-opening this RFE.

Thanks.

**Comment by lewisst** [comment]
@ReubenM It appears that systemd appends the drop-in file and hence will run the additional ExecStop commands after those main unit file.

If the main unit file is within /usr/lib/systemd/system, then a service file within /etc/systemd/system or the drop-in directory will override the original, leaving you will just the ExecStop lines configured within /etc/systemd/system.

There doesn't appear to be a way to order ExecStop line using drop-in, something that I to am looking for.

**Comment by robertmathews** [comment]
As additional feedback, I also was looking for a way to execute an extra ExecStop command from a drop-in file **before** the service's real ExecStop runs. Without something like "ExecStopPre", it seems this is not possible -- I have to modify the main unit file provided by the upstream packager, which isn't necessary when using "ExecStartPost" or "ExecStopPost".

So something like ExecStopPre would seem to have a use case.

**Comment by gcoxmoz** [comment]
Similar to the last comment, "take this node out of the loadbalancer pool" is a great pre-shutdown step, and would make a clean drop-in file.  Without ExecStopPre, we're going to be cloning the distro's file just to add 1 line to it.

**Comment by tonobo** [comment]
@poettering Are there any plans to keep this up again? I had exactly the same issue as described by @robertmathews

**Comment by bugfood** [comment]
It should still be possible to use a drop-in with ExecStop as-is, without modifying or cloning the unit file from upstream. Something like:

File: `/etc/systemd/system/myservice.service.d/override.conf`
```
[Service]
# clear parameter
ExecStop=
# run custom command
ExecStop=/usr/local/bin/pre-stop.sh
# run default stop command (copied from upstream unit file)
ExecStop=/usr/bin/stop-myservice
```

I do think there is still a use case for having ExecStopPre, though; that would reduce the above to:
```
[Service]
# run custom command
ExecStopPre=/usr/local/bin/pre-stop.sh
```
...and the drop-in would then be immune to any changes of ExecStop from upstream.

**Comment by MikeyCarter** [comment]
Was just looking for an option like this.   My use case.  I want to run a troubleshooting-dump.sh script before regular shutdown.  If someone is running a systemctl stop <service> it means there's a problem so want a common script to gather the stats of the machine state before it was shutdown.

**Comment by hseg** [comment]
> It should still be possible to use a drop-in with ExecStop as-is, without modifying or cloning the unit file from upstream. Something like:
> ...
> ...and the drop-in would then be immune to any changes of ExecStop from upstream.

This is precisely my use case: [Upstream](https://github.com/ltratt/pizauth) ships a server that can dump/restore its state, and a .service for setting up/tearing down the server. However, it is up to downstream users to drop-in configuration to save/restore the state dumps in a format that's useful to them. The latter is easy, just
```ExecStartPost=-/bin/sh -c 'age --decrypt --i AGE_PRIV_KEY -o - "$PIZAUTH_STATE_FILE" | pizauth restore'```
However, the former only makes sense while the server is running, and would benefit from a `ExecStopPre`.

Although now I consider it, one can work around this situation by creating a separate unit responsible for whatever behaviour needs to happen during the lifetime (ie StartPost, StopPre) of the parent unit -- standard ordering directives will then do the rest.

**Comment by insanie** [comment]
I have a different case: my unit file doesn't have any ExecStop entry and it's being handled with a default behavior which is kill -15. And I'm totally fine with it. However, if I want to define any custom pre-termination routine I'd have to define at least two ExecStop entries where the last one is basically a replica of default behavior.
While it's not a bug or anything it's quite inconvenient. Having ExecStopPre would allow me to define any pre-termination routine without touching actual ExecStop.

**Comment by akarasulu** [comment]
At least give us an `ExecStopPre=` to use in drop-in files that prepends to the effective ExecStop list. The use cases make perfect sense. I thought the directive was there until I needed it. Surprising to see it was not implemented. Has real value. I ask that this issue be reopened. Thanks in advance.

**Comment by philcerf** [comment]
For the records, I'd also have at least in principle a use case for a `ExecStopPre=`, as described in https://github.com/systemd/systemd/issues/39364#issuecomment-3650238304.

@davidstrauss Would you mind re-opening this? Or at least explaining why it's a no-go and whether alternatives were possible? :-)

**Comment by davidstrauss** [comment]
@philcerf Wanting to do a specific alteration with a drop-in file isn't really a use case, and it's not clear to me for the examples given by others why lacking this specific override is blocking them.

Nevertheless, I'll explain why I personally think `ExecStopPre` is bad.

It's already been discussed (and you probably already understand) that `ExecStop` can be used multiple times sequentially. External (out of service) pre-termination needs can also be satisfied with a separate unit and dependencies as long as they don't need to share execution context with the main service. So, this request isn't so much about the capability of unit files but their native (in systemd) composability.

The way drop-ins affect unit files is, specifically, a decorator pattern for composability, which is lightweight and easy to understand but one of the least robust when there's contention over the same concern (like command sequence to stop a service). Decorators aren't that robust under contention for the very reason you're asking for `ExecStopPre`: you end up special-casing the conflict resolution for things under contention.

(For context, `ExecStartPre` is not a directive for the sake of composability conflict resolution but because it behaves differently from `ExecStart`, which typically launches the main, long-running daemon.)

I also dislike special cases for decorator composability because they're rarely the final word. Consider if the original unit file used `ExecStopPre`. Do we then introduce `ExecStopPrePre` for drop-ins? And also `ExecStopPostPre` if you want to add a command after the original unit's `ExecStopPre`? At a certain point, the composition process belongs outside of systemd.

Finally, if you are confident enough in understanding the service's behavior that you're willing to surgically alter the shutdown sequence, you ought to be confident enough to copy the whole unit file and make a custom one that reflects your needs or at least override the entire `ExecStop` sequence. After all, the only upside a drop-in gives you is inheriting upstream changes, but you should already be reviewing every one of those if you're doing surgery on the service behavior this way.

**Comment by philcerf** [comment]
Well if you take my example, disabling the network of NM on stop (which has to happen however before it's stopped), why do you think it's no use-case?
It's not so much different from what countless units to in `ExecStopPost=` cleaning up things and brining everything in a properly stopped state.

Of course there are other ways theory, I could e.g. patch NM itself, but practically usable ones I don't really see in my case.
Instead the override mechanism seem to be pretty well suited.

Yes it's clear that `ExecStop=` can be used multiple times, but that has its limits when one cannot insert a first command before what the main unit file would do (again, NM's right now doesn't set it, so at least currently I'm good).
And really what my command does isn't stopping (and thus I merely abuse `ExceStop=`, even if I could make sure to insert in the beginning). What I do is actually preparing the stop.

With "External (out of service) pre-termination" you mean something like having a separate unit, which has e.g.:
```
[Unit]
BindsTo=NetworkManager.service
After=NetworkManager.service
[Service]
ExecStop=`nmcli networking off`
```
?

Might work. I mean one downside is that one would loose all information from the job that actually stops `NetworkManager.service` (which I use, my actual unit file does a bit more ;-) ).

Apart from my use case, there might however still be use cases for which an `ExecStopPre=` would be (the only easy?) way to go.
Consider e.g. you have a DB server, that runs in a container and you want to make sure a backup is written right before stopping it and you need the exec context. Maybe a bit constructed, but I guess one gets the point.

Arguably, your point with PrePre and so on is indeed not invalid. ;-)

But I'd agree less with your final point. I mean if you take my example (`nmcli networking off` before it's stopped):
This isn't really going deep into NM (it's merely using exposed CLI functionality) and it doesn't touch its *actual* start/stop procedure at all, at least not conceptually. It's as if the admin would simply call the command just before stopping it.
So for such case I'd still very much prefer to have a drop-in an inherit any other upstream changes automatically.

And the reviewing of upstream changes is not something which seems practically really feasible and which is IMO also a downside of the whole config schema as done by systemd, as nice as it is and as well as it works for many cases.
*Changes to these files in `/usr` will most likely go completely unnoticed for many users when they upgrade, whereas if these would have been place in something like `/etc/systemd/system/{for-admins,for-packages}` the package management systemd can typically be made informing a user, if there's a change).*
