### ISSUE TITLE
[RFE] Implement basic firewall into systemd/networkd

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#4155]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### Description

Since there is already a networkd daemon for managing network configuration being part of systemd, why not also implement at least a basic firewall? Or maybe consider merging [firewalld](http://www.firewalld.org) into systemd?

**Comment by johannbg** [comment]
Well there exist already a very basic firewall implementation in networkd based on nftables ( but networkd still lacks dbus support which kinda has hindered it's progress somewhat ) and it could probably be extended to something way better than firewalld.

**Comment by poettering** [comment]
See #6764

**Comment by poettering** [comment]
#6764 got merged a while back. Closing.
