### ISSUE TITLE
freedesktop.org wiki: Add link to Arch Linux bug tracker

### ISSUE THREAD

**Issue by stefan-it** [systemd/systemd#4160]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

At the moment there's no link to the bug tracker of Arch Linux for `systemd` on the freedesktop.org wiki page for `systemd`, see [here](https://secure.freedesktop.org/cgit/www/tree/Software/systemd.mdwn) - or properly rendered [here](https://www.freedesktop.org/wiki/Software/systemd/).

So it would be great if the following entry could be added to the [bug tracker list](https://secure.freedesktop.org/cgit/www/tree/Software/systemd.mdwn#n102):

``` markdown
* [[Arch Linux|https://bugs.archlinux.org/?project=1&cat%5B%5D=31&string=systemd]] 
```

**Comment by poettering** [comment]
Done! Thanks!
