### ISSUE TITLE
logind does not re-start `user@.service` (if stopped) on login, if a user has lingering enabled

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#4162]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

v231-341-g0b9cb24
### In case of bug report: Expected behaviour you didn't see

If I manually stop `user@.service` for a lingering user, logind should re-start it on next login (at least).
### In case of bug report: Unexpected behaviour you saw

logind does not attempt to re-start `user@.service` for lingering users, failing any subsequent logins if it gets accidentally stopped.
### In case of bug report: Steps to reproduce the problem
- create a test user
- run `loginctl enable-linger USER`
- run `systemctl stop user@UID.service`
- try to login as USER

**Comment by intelfx** [comment]
A few comments for myself (would be nice if somebody commented):
- if user manager dies, probably all sessions should die as well (because they will hold many invalid resource handles);
- when user manager dies, the user object should be _destroyed (and reinstated, for lingering users)_, so that listeners to the UserNew/UserRemoved signals will have a chance to refresh their resource handlers, if any;
- attention must be paid to protection against restarting logind itself (it should recover all the state at startup, e. g. "logind dies → user manager dies → logind restarts → logind must see that a user exists without a user manager, and perform the above dance");
- probably, reinstation of the user object/manager should not happen immediately but at next login (what if I want to do some maintenance and the user manager gets in the way?).

**Comment by poettering** [comment]
Hmm, you make good points. The least we should do I figure is re-enqueue a start job for the user@.service of the user each time he or she logs in.

**Comment by intelfx** [comment]
@poettering Maybe this is something better done via Required/After dependencies from `session-$id.scope` to `user@$uid.service`?

**Comment by poettering** [comment]
Indeed, that's a really good idea.

**Comment by intelfx** [comment]
OK, I'll see what I can do. The plan is to ensure:
1. when the user manager dies, all sessions are killed as well (via dependencies);
2. when a session is started, the user manager must be started as well (again, via dependencies);
3. when the user manager dies, the user is removed from logind, even if it's "lingering" (via special handling in logind).

Sounds fine?

**Comment by poettering** [comment]
I guess 1 + 2 can be implemented through a simple BindsTo= from the scope units to the user service.

But yes, sounds good.

**Comment by intelfx** [comment]
@poettering I'm finally around implementing this.

1. Why `BindsTo=` — isn't `Requires=` sufficient? I'm not sure I grasp the difference between these.

2. Is (3) from the above list actually OK — i. e. will you accept a patch that does this change?

**Comment by intelfx** [comment]
Proposed fix waiting in #5546.

**Comment by intelfx** [comment]
BTW, I think this is a bug, not RFE.

**Comment by poettering** [comment]
Should be fixed by #9824.
