### ISSUE TITLE
Showing all non-exclusive states on listing unit files

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4171]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

I'm noticing that masking a service does not apply the disabled state and for example masking and unmasking 2 services can result that one is now disabled and the other is enabled. Maybe commands like "systemctl list-unit-files" can get enhanced to show for the state all non-exclusive states.

**Comment by poettering** [comment]
I am sorry, but I cannot parse this.

What do you mean by "does not apply the disabled state"? If you mask a unit, then it is masked, not disabled. Masking is stronger than disabling...

Can you elaborate on what precisely you are trying to say here? Example status messages by systemctl would be useful for example.

**Comment by Sworddragon** [comment]
I'm aware that masking and disabling are different things and not mutually-exclusive. And thats the point: For example if you have 2 masked units "systemctl list-unit-files" does show them as masked but it does not show if they are additionally disabled. test1.service could be masked and disabled while test2.service could be only masked but you don't know this if you make a look at "systemctl list-unit-files".

**Comment by poettering** [comment]
Uh oh, I am not convinced that distinguishing this in the output would really be a good idea. It's difficult enought to explain the difference of "LoadState" and "ActiveState" to people, and further splitting up the "LoadState" and making it multidimensional doesn't strike me an improvement...

**Comment by Sworddragon** [comment]
Time for a --verbose option?^^

**Comment by keszybz** [comment]
Nah, I don't think adding ever more substates makes sense. This is all maintained by a simple set of symlinks, so it's OK to just list all files in /etc+/usr/lib+... and do any logic you need based on that. Similar issue came up in #6892 recently, and here too I think that we can't and shouldn't try to exactly describe all the state in systemctl output.
