### ISSUE TITLE
systemctl preset-all should implement policy, not disable getty@tty1.service

### ISSUE THREAD

**Issue by ackalker** [systemd/systemd#4177]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

231-1

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Arch Linux (x86_64)
### In case of bug report: Expected behaviour you didn't see

`systemctl preset-all` should leave service `getty@tty1.service` enabled according to preset policy, which in this case (stock `/usr/lib/systemd/system-preset/90-systemd.preset`) includes `enable getty@.service`, which in turn should `enable getty@tty1.service` because `getty@.service` has an `[Install]` section with `DefaultInstance=tty1`.
### In case of bug report: Unexpected behaviour you saw

`systemctl preset-all` disables `getty@tty1.service` contrary to preset policy.
### In case of bug report: Steps to reproduce the problem

In a test VM running a freshly installed Arch Linux (using `pacstrap`, only `base` group installed):

Show default policy:

```
# cat /usr/lib/systemd/system-preset/99-default.preset
disable *
```

Show preset policy wrt. `getty`, should result in `getty@.service` being enabled:

```
# grep getty /usr/lib/systemd/system-preset/90-systemd.preset
enable getty@.service
disable console-getty.service
```

Verify preset policy wrt. `getty@tty1`, should be `vendor preset: enabled`:

```
# systemctl --no-pager status getty@tty1.service
* getty@tty1.service - Getty on tty1
   Loaded: loaded (/usr/lib/systemd/system/getty@.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-09-18 13:54:56 UTC; 4min 7s ago
     Docs: man:agetty(8)
           man:systemd-getty-generator(8)
           http://0pointer.de/blog/projects/serial-console.html
 Main PID: 212 (agetty)
   CGroup: /system.slice/system-getty.slice/getty@tty1.service
           `-212 /sbin/agetty --noclear tty1 linux

Sep 18 13:54:56 localhost systemd[1]: Started Getty on tty1.
```

Try and implement preset policy, should not disable `getty@tty1.service`:

```
# systemctl preset-all
Removed /etc/systemd/system/getty.target.wants/getty@tty1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.service -> /usr/lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/machines.target -> /usr/lib/systemd/system/machines.target.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service -> /usr/lib/systemd/system/systemd-timesyncd.service.
```

Verify that manually enabling `getty@.service` enables `getty@tty1.service` :

```
# systemctl enable getty@.service
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service -> /usr/lib/systemd/system/getty@.service.
```

Show that `systemctl preset-all` disables `getty@tty1.service` once more:

```
# systemctl preset-all
Removed /etc/systemd/system/multi-user.target.wants/systemd-resolved.service.
Removed /etc/systemd/system/getty.target.wants/getty@tty1.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.service -> /usr/lib/systemd/system/systemd-resolved.service.
```

**Comment by keszybz** [comment]
It's already fixed. Please try systemd git.

**Comment by ackalker** [comment]
@keszybz Thanks for the very quick reply :smile:
