### ISSUE TITLE
sysv-generator: "$foo" name can't be assumed to be the same as "foo" one

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#4178]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with HEAD

We currently ignore the '$' prefix when parsing sysv service names.

This looks wrong since in the old good days we used (and still use for some distros) "$named"  referring to the facility (and thereby with "nss-lookup.target") and "named" without the '$' prefix referring to the service defined by /etc/init.d/named.

So at least for this case we cannot ignore the "$" prefix it seems.

**Comment by poettering** [comment]
Well, see the comments here:

https://github.com/systemd/systemd/blob/master/src/sysv-generator/sysv-generator.c#L250

**Comment by fbuihuu** [comment]
Yes I saw them but they seem to be wrong as I described "$named" != "named".

**Comment by poettering** [comment]
It's probably easier to simply add a native unit file for named, then to fix this corner case...

**Comment by fbuihuu** [comment]
Technically speaking, I agree ;)

But I must admit that I fail to see the point of making "$foo" equivalent to "foo" as _facilities_ has always been different from _services_.

Do you have an example where this choice did make sense ?

**Comment by poettering** [comment]
git history might know more...

**Comment by fbuihuu** [comment]
commit a7d3cc26f9694053712458615006ea79cd7a7cb4 doesn't really help

**Comment by poettering** [comment]
The sysv-generator is now deprecated and on its way out, also see #28179. Let's not bother with further tweaks on it. If people in 2023 still have issues with this, they should really update their scripts to become proper unit files.

Closing hence.
