### ISSUE TITLE
Document full effect of DefaultDependencies=yes for all unit types, as well as all implicit deps that are generated even when it is off

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#418]
`systemd.service(5)` currently does not tell what implicit dependencies are added when one specifies the `Sockets` directive. The code seems to imply `Wants` and `After`, which is weird considering that `Service` in `systemd.socket` doesn't. It would be great to have this documented and maybe the reasoning as well.

**Comment by poettering** [comment]
Actually, we don't document the effect of DefaultDependencies=yes comprehensively for any of the types, not just for sockets. But we should.

**Comment by fsateler** [comment]
@poettering note that this is similar but not the same. Specifying Sockets is different from DefaultDependencies between a socket unit and its corresponding service.

**Comment by poettering** [comment]
True, we should document all implicit deps. The ones generated due to DefaultDependencies=yes and the ones generated even if DefaultDependencies=no.

**Comment by poettering** [comment]
This was added a while back in c129bd5df3ca08eb352cf69d01d2f374552624ae
