### ISSUE TITLE
journald: when flushing, the assumption that the persistent journal is empty is incorrect

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#4190]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> v231

The issue can easily be reproduced:

First switch to the volatile journal (step only needed if the persistent journal is in use):
`systemctl stop systemd-journald && rm -fr /var/log/journal && systemctl start systemd-journald`

Then switch back to the persistent one:
`systemctl stop systemd-journald && mkdir /var/log/journal && systemctl start systemd-journald`

And now make sure that the flushed journal is consistent:
`journalctl --verify`

This fails with:

> 3914e0: Entry timestamp out of synchronization  
> File corruption detected at /var/log/journal/d7ac416fb7b9443aaf4e89ff00e038cb/system.journal:3914e0 (of > 8388608 bytes, 44%).

This is due to the fact that journald assumes that when flushing, the persistent journal is empty or older than the volatile journal.

This assumption is incorrect because when journald is _(re)started_, it will emit a message (via server_init() -> system_journal_open() -> determine_space_for()) before flushing making the first entry younger than the flushed one.

**Comment by fbuihuu** [comment]
https://github.com/fbuihuu/systemd/tree/fix-4190 is an attempt to solve this issue.

Please note  that it's mostly a RFC thing for the moment.

Most of the changes are cleanup material only (mostly by introducing 2 new structures) so the code becomes easier to split. More specifically a dedicated function has been created to emit a space status message when appropriate instead of doing this each time the journal is opened.

It's currently based on v228 but if those changes appear to make sense, I'll rebase them on top of master.

Could anybody give them a look ?

Thanks

**Comment by poettering** [comment]
Hmm, could you post RFCs also as regular PRs here, marking them as RFC in the subject? That way we can use our usual review tools. Thanks!

**Comment by fbuihuu** [comment]
@poettering , sure please see https://github.com/systemd/systemd/pull/4327.

As said it's based on v228 currently but I'll happily rebase it on top of master if thoses changes make sense.
