### ISSUE TITLE
"systemctl --failed" is not documented

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4197]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev
### In case of bug report: Steps to reproduce the problem

> Execute "systemctl --failed" and make a look for this option on executing "man systemctl" and "systemctl -h".
### In case of bug report: Unexpected behaviour you saw

> "systemctl --failed" is known but it is not documented.
### In case of bug report: Expected behaviour you didn't see

> "man systemctl" and "systemctl -h" should document the option --failed.

This issue has already appeared on the debian tracker ( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=767267 ) and should be fixed there. Not sure if they added just a patchset for debian as the NEWS file here doesn't mention deprecating the --failed option. I noticed this issue because "systemctl --failed -all" has not listed failed jobs while I have seen jobs failing on booting so I wanted to look in the manpage if there are exceptions for --failed.

**Comment by falconindy** [comment]
It's intended. See 036359ba8d0aba7db7eac75d10073a849a033fd1.

**Comment by Sworddragon** [comment]
So --state=failed replaces --failed (and --state=failed does not list any exceptions but it seems to not list failed jobs which are the result of other masked units).

**Comment by martinpitt** [comment]
Thanks for pointing out, I replaced the remaining usage of `--failed` in Debian (in the Apport hook and in one test case): https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=82cb1c6
