### ISSUE TITLE
networkd's BindCarrier setting does not propagate down state if a link just disappears

### ISSUE THREAD

**Issue by aroig** [systemd/systemd#4202]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> arch linux
### In case of bug report: Expected behaviour you didn't see

> I have a virtual network interface `wifi-sta` configured as a slave in a bond. The bond is configured with `BindCarrier=eth0 wifi-sta`. When `wifi-sta` is deleted and `eth0` has no carrier, the bond interface should be brought down to the no-carrier state. 
### In case of bug report: Unexpected behaviour you saw

> When the virtual interface `wifi-sta` is deleted, the bond keeps having routable state, despite none of its slaves has carrier.
### In case of bug report: Steps to reproduce the problem

> In my current setting, I use a virtual interface `wifi-sta` for my wifi interface `wifi`. The virtual interface `wifi-sta` is bonded to `bd-net`. Additionally, `bd-net` is configured with `BindCarrier=eth0 wifi-sta`.
> 
> I bring up the virtual wifi device `wifi-sta` as follows

```
    /usr/bin/iw wifi interface add wifi-sta type station
```

> And then remove the virtual interface with

```
   /usr/bin/iw %I-sta del 
```

> It turns out that when removing the interface, the device just disappears, it is not brought down. This caused `bd-net` to remain in the routable state, despite having no slaves with carrier. 
> 
> I now I can bring down `wifi-sta` before deleting it (and wait for it entering the down state), but it looks like a job for networkd, to notice vanishing interfaces and propagate state.
> 
> I'm not sure what happens in other circumstances, like for example when you unplug a USB ethernet adapter.

**Comment by dkg** [comment]
fwiw, this appears to still be the case in 244.3-1 (debian testing)

My use case is a little different than the original reporter's case, but it's still relevant.  I want to bring up a wireguard interface whenever a particular USB ethernet device is connected, and bring it down again when that USB ethernet device is unplugged.  Instead, the wireguard interface is left up when the ethernet device is unplugged, even though the route that the wireguard traffic would travel over isn't available any longer.

**Comment by yuwata** [comment]
I am not sure when this is fixed, but it seems this is already fixed.
