### ISSUE TITLE
systemctl - Useless error message - "Failed to enable unit: Invalid Argument"

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4209]
- [x] Request for enhancement (RFE)

> systemd 231
> 
> Arch

Running "systemctl enable ...", with a faulty unit file returns:

Failed to enable unit: Invalid Argument

So then, what "argument" would that be?  systemctl does not say!

When there is some kind of parse error, systemctl should return the line found in error.
Otherwise, the error may be very difficult to identify.

**Comment by keszybz** [comment]
The argument is the unit file. This second part of the error comes from strerror(), and it's not very easy to change this without writing our own error messages, which, while useful in many cases, also increases the required amount of code. So, while it would be possible to change this, I don't find current output particularly bad .

**Comment by thx1111** [comment]
On second thought, since the "argument" must be somewhere within the Install section itself - Is that true? - I'll agree generally.  A better error message, though, would point-out this obvious-in-retrospect fact, such as:
Failed to enable unit - Install section: Invalid Argument

It is otherwise not entirely or immediately obvious that the error would be from some statement within the Install section.

**Comment by poettering** [comment]
Yeah, we should fix the install logic to propagate parsing errors back to the clients in a more expressive form.

**Comment by jwatte** [comment]
I thoroughly agree with this.
Good error messages to the end user and administrator is the badge of a good project!

**Comment by iaroslav-ai** [comment]
+1

**Comment by calder** [comment]
+1

**Comment by rjhornsby** [comment]
In the mean time, I came across a new-to-me command for possibly resolving `invalid argument` errors:

`sudo systemd-analyze verify <unit>`

**Comment by elboletaire** [comment]
I'm facing with this right now, and using `systemd-analyze verify` doesn't help (its output is empty).

So +1 in improving the error messages.

**Comment by bendavis78** [comment]
I came across this issue when adding to the [Install] section. No details as to what was invalid or why it was invalid.

**Comment by karolyi** [comment]
+1

**Comment by hamid-nazari** [comment]
+1

**Comment by CvR42** [comment]
+1

**Comment by 3pns** [comment]
+1

**Comment by stolenmoment** [comment]
And I just discovered that using WakeSystem=true caused "systemctl start xx.timer" to fail this same way.  I *hope* that's because the VM I use for debugging can't be put to sleep (how do you ask that question?), but perhaps the bug is more obscure than that.

**Comment by whackyhack** [comment]
I get this on one particular server among many that do not show this error.  Service unit file is exactly same.

**Comment by jessikaduquette** [comment]
Thanks to the comments here, I managed to find what was wrong in my service file. I was going through all the lines in my unit and service and didn't check the Install section and that an unwanted s was added to .target. Just lost 6 hours on this so happy I am not the only one that didn't know what to do with this error message hehe.

**Comment by DictumMortuum** [comment]
Same log, had an erroneous [install] section due to copy/paste.

```
❯ git diff
diff --git a/systemd/servus.service b/systemd/servus.service
index fbb3b43..8eb2bc7 100644
--- a/systemd/servus.service
+++ b/systemd/servus.service
@@ -2,7 +2,7 @@
 Description=servus personal assistant service

 [Install]
-WantedBy=multi-user.target[Service]
+WantedBy=multi-user.target

 [Service]
 Type=simple
```

**Comment by lockejan** [comment]
I had this same issue and tried the systemd-analyze cmd
```
sudo systemd-analyze verify gunicorn-88.88.111.111.service
/etc/systemd/system/gunicorn-88.88.111.111.service:8: Ignoring unknown escape sequences: "\"
/etc/systemd/system/gunicorn-88.88.111.111.service:9: Missing '='.
gunicorn-88.88.111.111.service: Failed to create gunicorn-88.88.111.111.service/start: Unit gunicorn-88.88.111.111.service is not loaded properly: Invalid argument.
Attempted to remove disk file system, and we can't allow that.
```

Turned out that in my jinja-template was an additional whitespace after one of the multilinebreak sequences " \ ".

**Comment by ErikBjare** [comment]
FWIW, I got the same error when trying to do this: `systemctl enable zfskey@tank/dataset`

The solution here was kinda obvious, as I didn't really expect the unit argument (or whatever it's called) to support slashes in the first place.

**Comment by donomii** [comment]
If you are worried about the amount of code, why not remove the error messages completely?  It would make no difference to my ability to debug the problem.  The current messages are completely unhelpful.

**Comment by ahmedwarwani** [comment]
I just fixed this issue, there was a typo error in my celeryd.service. 

WantedBy: There is a typo in the last line of the [Install] section: multi-user.targeti should be multi-user.target. This should not cause an encoding issue, but it's a typo that should be corrected.

just renamed it and it worked.
