### ISSUE TITLE
systemctl enable - Install section dependencies "Also=" and "DefaultInstance=" fail to accept any "specifier"

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4210]
- [x] Bug report

> systemd 231
> 
> Arch
### In case of bug report: Expected behaviour you didn't see

> "If the user requests installation/deinstallation of a unit with this option configured, systemctl enable and systemctl disable will automatically install/uninstall units listed in this option as well."
> "Many settings resolve specifiers which may be used to write generic unit files referring to runtime or unit parameters that are replaced when the unit files are loaded. The following specifiers are understood: ... "
### In case of bug report: Unexpected behaviour you saw

> Error message: Failed to enable unit: Invalid Argument
### In case of bug report: Steps to reproduce the problem

> It is sufficient to create a service unit file with just the Install section:
> ## testing@.service
> 
> [Install]
> WantedBy= default.target
> Also= sometemplateunitfile@%p.service

Otherwise, "systemctl enable ..." will have to be run multiple times, once for each service unit file.

"Also=" will accept an explicit file name, but that defeats the purpose of having and using "specifiers".

With DefaultInstance=%..., the specifier is treated as "blank".

Other install directives have no problem with the use of "specifiers".

**Comment by poettering** [comment]
Yes, Also= doesn't support specifier expansion at all right now. And DefaultInstance= does support it, but doesn't generate proper error messages if it doesn't work.

**Comment by keszybz** [comment]
OK, this is fixed now. I didn't get closed automatically because I didn't use canonical "Fixed #...." spelling.
