### ISSUE TITLE
systemd-networkd: attempts to configure bridge despite non-[Match] in container

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#4211]
### Submission type
- Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> _Host:_ Debian 8.5, systemd-215, Kernel 4.1.15 (Hetzner Rescue System)
> _Guest:_ Gentoo, systemd-231 (systemd-nspawn container)
### In case of bug report: Expected behaviour you didn't see

> Running a systemd-nspawn container to bootstrap a server's OS.
> While running as container for bootstrapping purposes, a different network configuration should be used as the "productive" one, which should be achieved by corresponding `[Match]` criteria in `systemd-networkd`'s configuration
> Content in `/etc/systemd/network/00-vmbridge.network`:
> 
> ``` INI
> [Match]
> Virtualization=!systemd-nspawn
> Name=public
> 
> [Network]
> Description=A bridge providing connectivity for the VMs
> Bridge=vmbridge
> ```
> 
> I'd expect this configuration to be completely ignored, as in my container there's nether an interface named `public` nor does the `Virtualization=` condition produce a `true` result.
> 
> Despite this, `systemd-nspawn` logs this error on startup:
> 
> ```
> [/etc/systemd/network/00-vmbridge.network:8] Bridge could not be found, ignoring assignment: vmbridge
> ```
### In case of bug report: Unexpected behaviour you saw

> `systemd-nspawn` ignoring the `[Match]` criteria of a `*.network` file and trying to apply a `Bridge=` configuration nonetheless.
### In case of bug report: Steps to reproduce the problem

> - Create the file `/etc/systemd/network/00-vmbridge.network`:
>   
>   ``` INI
>   [Match]
>   Virtualization=!systemd-nspawn
>   Name=public
>   
>   [Network]
>   Description=A bridge providing connectivity for the VMs
>   Bridge=vmbridge
>   ```
> - Execute `systemctl restart systemd-networkd`
> - Execute `systemctl status systemd-networkd` or manually check it's journal
> - The error (red highlighted) `[/etc/systemd/network/00-vmbridge.network:8] Bridge could not be found, ignoring assignment: vmbridge` is logged

**Comment by poettering** [comment]
So, did I get this right: all you see is the above error, you don't actually see networkd doing something with the bridge interface, do you?

I figure the error is simply misleading: networkd will always parse all configuration files, and link them up as written down, but that doesn't mean it will actually also apply it. That's a second, separate step. Now, in your case the error is generated by the first step, and tells you your config is inconsistent. It doesn't mean networkd would actually apply the specified config...

Does that explain your issue?

**Comment by poettering** [comment]
(and I'd argue that networkd's behaviour isn't even broken in this regard, after all your config _is_ incomplete)

**Comment by eliasp** [comment]
> So, did I get this right: all you see is the above error, you don't actually see networkd doing something with the bridge interface, do you?

That's correct

> I figure the error is simply misleading: networkd will always parse all configuration files, and link them up as written down, but that doesn't mean it will actually also apply it. That's a second, separate step. Now, in your case the error is generated by the first step, and tells you your config is inconsistent. It doesn't mean networkd would actually apply the specified config...

Yes, I wanted to point out that the behavior/error message is misleading. It suggests it tries to process the configuration, although it shouldn't be due to the `ConditionVirtualization=` restriction.

> (and I'd argue that networkd's behaviour isn't even broken in this regard, after all your config is incomplete)

What's missing in this configuration to be complete?

**Comment by poettering** [comment]
> What's missing in this configuration to be complete?

Well, do you have a vmbridge netdev file?

**Comment by eliasp** [comment]
> Well, do you have a vmbridge netdev file?

Yes, I do. But this is also "disabled" using `ConditionVirtualization=` which might cause this situation.

**Comment by poettering** [comment]
> Yes, I do. But this is also "disabled" using ConditionVirtualization= which might cause this situation.

Ah, i see, so this is a bit ugly indeed. If both are conditioned out there shouldn't be such a message.

**Comment by yuwata** [comment]
Fix is waiting in #11780.
