### ISSUE TITLE
udev TAG-="systemd" does not undo effect of TAG+="systemd"

### ISSUE THREAD

**Issue by networkimprov** [systemd/systemd#4214]
### Submission type
- [x] Feature request
### systemd version the issue has been seen with

> 231
### Used distribution

> Arch Linux ARM
### Expected behavior you didn't see

> This usb driver emits online/offline uevents, and we need to bring services up/down on these.  The first of these rules works; the second does not deactivate dev-xyz.device as expected:

```
DRIVERS=="twl4030_usb", ACTION=="online",  TAG+="systemd", ENV{SYSTEMD_ALIAS}="/dev/xyz", ENV{SYSTEMD_WANTS}="..."
DRIVERS=="twl4030_usb", ACTION=="offline", TAG-="systemd"
```

**Comment by keszybz** [comment]
The first rule pulls in a unit, so it is started. If that rule ceases to exist, this does not cause the unit to stop. You need some mechanism that would stop the unit.

You could add BindsTo=dev-xyz.device (or BindsTo=/dev/xyz) to have systemd stop your unit automatically. (I'm not 100% sure, but I think this should work ;) )

**Comment by martinpitt** [comment]
I don't think so -- I've never actually seen `online` and `offline` `ACTION`s -- maybe @networkimprov means `add` and `remove`, or some other attribute? In the former case (`ACTION==remove`), `BindsTo` will work, but if it's an attribute change only, then the device itself is still present. Then you either need to run `systemctl stop`, or start another unit which conflicts to the one you start in `online`.

**Comment by keszybz** [comment]
Oh, right, I forgot that the device does not go away. `RUN+=/bin/systemctl stop --no-block whatever.service` should work.

**Comment by networkimprov** [comment]
@keszybz I am not suggesting TAG-="systemd" should stop the wanted unit, just remove the devices created by +=. I would use BindsTo=dev-xyz.device in the unit, but that requires systemd to remove the device on ACTION=="offline". ENV{SYSTEMD_ALIAS}="" does not do that.

@martinpitt ACTION=="remove" implies unloading the USB driver, which isn't correct here. Yes you can RUN+="/bin/systemctl start|stop xzy" but the point of TAG+="systemd" is to avoid that. See https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/include/linux/kobject.h#n44

**Comment by keszybz** [comment]
You cannot remove an Alias from an existing unit. The only way to do that (for normal units), is to change the configuration that adds the alias and do systemctl daemon-reload, which re-creates all units from scratch. For device units, the alias is initially added based on udev configuration and cannot be removed after that.

SYSTEMD_READY=0 does the first half of what you want (makes systemd delay the starting of services), but afaik, we have no equivalent provision for stopping units when some condition stops being true.

**Comment by networkimprov** [comment]
Then I suppose this is a feature request (for either TAG-="systemd" or ENV{SYSTEMD_READY}="0" with broader scope) rather than a bug report; I've amended report...

**Comment by poettering** [comment]
Not sure what precisely is being requested here. But the idea is that services requiring some device to be around should use BindsTo= from the service unit towards the device unit. (i.e. the device unit pulls in the service via Wants= configured via the SYSTEMD_WANTS udev property and the other direction is a BindsTo= configured in the service's unit file). This is how many services do it, including the gettys for example.

If you want to manage when a device unit is marked "actvie" in systemd use the SYSTEMD_READY udev property, it's directly reflected in the device unit's state.

SYSTEMD_ALIAS cannot be undone really, that's a known issue, but if you are using it you probably are doing something wrong anyway...

Note that "offline" and "online" aren't really actions systemd looks for. Normally, the action "change" is issued for all kinds of change events.

I am not sure I grok what this issues is supposed to be about. What precisely are you asking for?

**Comment by networkimprov** [comment]
@poettering I am suggesting TAG-="systemd" should remove the persistent configuration created by TAG+=, and remove the related SYSTEMD_ALIAS. I wish to use BindsTo=dev-xyz.device in the unit, but that requires systemd to remove at least the alias via a udev rule.

This USB driver issues online/offline uevents because that's the correct status, and we can react to it in udev rules. We can write `RUN+="/bin/systemctl start|stop xzy"` but the point of TAG+="systemd" is to avoid that.

**Comment by arvidjaar** [comment]
@networkimprov Current logic is that `systemd` tag is set on devices that are "of interest" to systemd. So removing it sounds wrong.

> I wish to use `BindsTo=dev-xyz.device` in the unit, but that requires systemd to remove at least the alias via a udev rule.

It should be enough to toggle `SYSTEMD_READY`. Setting it to `0` should cause systemd to assume device is gone. You need to carefully design you rules to actually set `SYSTEMD_READY=1` when again appropriate.

**Comment by networkimprov** [comment]
If TAG+= makes something interesting to systemd, then TAG-= seems like it would undo that.

Sure, you could implement this RFE by allowing SYSTEMD_READY=0 after the device was readied by a different rule. Note, that makes _READY a persistent property (like _ALIAS), vs its current scope as a flag on a specific rule meaning "defer startup".

**Comment by arvidjaar** [comment]
> current scope as a flag on a specific rule

You misunderstand what `SYSTEMD_READY` does. It is just as persistent as any other device property and is not tied to any specific rule. And it does not say "defer startup" but simply makes systemd pretend device does not exist.

**Comment by networkimprov** [comment]
My mistake, but one need not write SYSTEMD_READY=1 as that is implicit in TAG+=systemd, nor does one write SYSTEMD_READY=0 in rules without said tag. The tag is thus the most user-apparent entity to toggle.

**Comment by poettering** [comment]
So we now agreed upstream that udev tags shall henceforth be "sticky", i.e. something that can only be added, and that never goes away. this also means a TAG-= syntax doesn't really make sense, since that is the opposite to "sticky".

See #16853.

Closing hence.
