### ISSUE TITLE
Not storing syslog messages in journal

### ISSUE THREAD

**Issue by suezzelur** [systemd/systemd#4227]
Is there a way to not store the syslog messages forwarded to syslog service in journal? I have ForwardToSyslog=yes set in journald.conf.

**Comment by vcaputo** [comment]
No

**Comment by utezduyar** [comment]
Storage=none (https://www.freedesktop.org/software/systemd/man/journald.conf.html)

**Comment by poettering** [comment]
This is not a support forum btw. If it is used as such I#d prefer to close the bug immediately with a friendly redirect to a better forum (for example the systemd ML).
