### ISSUE TITLE
Document better systemd-user requirements wrt. resource limits

### ISSUE THREAD

**Issue by ao2** [systemd/systemd#4232]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian

Hi,

the documentation (`systemd.exec(5)` and `systemd-user.conf(5)`) does not make it very clear how resource limits in **user** units are related to "system-wide" limits.

See for example this Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838191 Debian was forgetting to load `pam_limits.so` when starting `systemd-user`, and so the limits specified in `/etc/security/limits.conf` were not honored by **user** units.

I see that the files in `factory/etc/pam.d` do not refer to `pam_limits.so` either, and from the history it looks like it's intentional, however Fedora does load it in its `/etc/pam.d/system-auth` which is included by `/etc/pam.d/systemd-user`.

My doubt is basically: is `systemd-user` supposed to honor the limits from `/etc/security/limits.conf`?
Is this deliberately left as a choice for admins and system-integrators?

This could be clarified in the man pages, and maybe also with a comment in `src/login/systemd-user.m4`.

Thanks,
   Antonio

**Comment by poettering** [comment]
> My doubt is basically: is systemd-user supposed to honor the limits from /etc/security/limits.conf?
> Is this deliberately left as a choice for admins and system-integrators?

The latter. If distros want pam_limits they should add it to the PAM stack. systemd doesn't really care about it though, we are happy with and without it.

Generally we assume that distros will have to alter the PAM snippets to match how they set up PAM. This is nothing we can ship upstream that covers everything the distros want.

I doubt we should mention pam_limits in the docs anywhere. Maybe in the README targeted for distro integrators, but this is nothing admins should really have to deal with...

**Comment by ao2** [comment]
> I doubt we should mention pam_limits in the docs anywhere. Maybe in the README targeted for distro integrators, but this is nothing admins should really have to deal with...

I see your point, not mentioning pam_limits in the user facing docs is fine.
A note for distro builders wouldn't hurt tho.

In user docs it may be still worth stressing that limits for user units (even `Default*` ones in `/etc/systemd/user.conf`) are valid only within _system-wide_ limits, either specified in `/etc/systemd/system.conf` or with “_other mechanisms_”.
That was not immediately clear to me when I started writing user units.

Thanks,
   Antonio

**Comment by poettering** [comment]
docfix waiting in #4348

**Comment by ao2** [comment]
Thanks.
