### ISSUE TITLE
Crashing systemd with user rights

### ISSUE THREAD

**Issue by StefanoD** [systemd/systemd#4247]
I have found this [video](https://www.youtube.com/watch?v=Ixo_jTGt86A).
This is the summary:
### Submission type
- [X] Bug report
### systemd version the issue has been seen with

> Latest in Red Hat 7
### Used distribution

> Red Hat 7
### In case of bug report: Expected behaviour you didn't see

> It shouldn't crash.
### In case of bug report: Unexpected behaviour you saw

> Crash
### In case of bug report: Steps to reproduce the problem

``` bash
while true; do
    NOTIFY_SOCKET=/run/systemd/notify ""
done
```

**Comment by martinpitt** [comment]
Duplicate of #4234

**Comment by zdzichu** [comment]
Hi,

This is not a RHEL issue tracker. Please open a case with Red Hat if you have problem with software they ship.
Upstream systemd is not vulnerable to this DoS (since 531ac2b).

**Comment by StefanoD** [comment]
So, you fixed this two days ago and I am not allowed to report this. Okay...

**Comment by zdzichu** [comment]
This is not about allowing or not. It just that we have no control on downstream distributors of the software, so we can't fix them.
Also, in this case, the issue was already reported, so your ticket was a duplicate noise, not really useful.

**Comment by glensc** [comment]
also the reproducer is useless (just sets `NOTIFY_SOCKET` env var in loop), that does not trigger the bug

**Comment by StefanoD** [comment]
I see, I had to come two days earlier then you guys wouldn't have this big mouth, about downstream, because this bug was really new.
