### ISSUE TITLE
systemd-resolved does not follow CNAMEs with DNS server stub

### ISSUE THREAD

**Issue by rfc1036** [systemd/systemd#4254]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Debian unstable (231-9)
### In case of bug report: Expected behaviour you didn't see

Getting the target of the CNAME in the answer section, e.g.:

> www.linux.it.     21600   IN  CNAME   picard.linux.it.
> picard.linux.it.  86400   IN  A   213.254.12.146
### In case of bug report: Expected behaviour you saw

Only the CNAME is returned:

> www.linux.it.     21600   IN  CNAME   picard.linux.it.

And queries made by libnss-dns do not work:

> $ ping www.linux.it
> ping: www.linux.it: Nome o servizio sconosciuto
### In case of bug report: Steps to reproduce the problem

Query a DNS label which is a CNAME:

> dig www.linux.it @127.0.0.53

**Comment by martinpitt** [comment]
`libnss-resolve` and `systemd-resolve` work fine here for `www.linux.it` -- for me this only affects querying the stub server on `127.0.0.53`.

**Comment by VMatrix1900** [comment]
> if you wish to use the local DNS stub resolver of systemd-resolved (and thus use LLMNR and DNS merging per interface), replace dns with resolve in `/etc/nsswitch.conf`: 
> `hosts: files resolve myhostname`

from [Arch Linux wiki](https://wiki.archlinux.org/index.php/Systemd-networkd#Required_services_and_setup)

This solves the problem for me.

**Comment by fsateler** [comment]
Probably related to https://github.com/systemd/systemd/issues/3981

**Comment by zdzichu** [comment]
Looks like #3826

**Comment by poettering** [comment]
Duplicate of #3826 indeed. Closing as duplicate.
