### ISSUE TITLE
DNSSEC=allow-downgrade may be triggered if the first query is for a broken DNSSEC domain

### ISSUE THREAD

**Issue by rfc1036** [systemd/systemd#4255]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Debian unstable (231-9)
### In case of bug report: Unexpected behaviour you saw

DNSSEC should not be disabled forever just because the first query systemd-resolved saw is for a non-validable (broken) domain.

> Oct  1 11:47:18 bongo systemd-resolved[19124]: Switching to system DNS server 127.0.0.1.
> Oct  1 11:47:18 bongo systemd[1]: Started Network Name Resolution.
> Oct  1 11:47:55 bongo systemd-resolved[19124]: Processing query...
> Oct  1 11:47:59 bongo systemd-resolved[19124]: Using degraded feature set (UDP+EDNS0+DO) for DNS server 127.0.0.1.
> Oct  1 11:48:00 bongo systemd-resolved[19124]: Processing query...
> Oct  1 11:48:30 bongo systemd-resolved[19124]: message repeated 4 times: [ Processing query...]
> Oct  1 11:48:31 bongo systemd-resolved[19124]: Server 127.0.0.1 does not support DNSSEC, downgrading to non-DNSSEC mode.

(127.0.0.1 is a BIND 9 server with DNSSEC validation enabled.)
### In case of bug report: Steps to reproduce the problem

> systemctl restart systemd-resolved
> dig www.dnssec-failed.org (times out)
> dig www.linux.it
> dig www.dnssec-failed.org (returns the A records instead of SERVFAIL as expected)

This is NOT reliably reproducible.

**Comment by poettering** [comment]
There are many ways in which DNSSEC lookups can be broken. We try to figure out when servers are borked and when simply the served DNS data is borked. We'll downgrade only when the servers are borked, but continue if the DNS data is borked.

Hence, in your case we'd have to figure out why precisely resolved came to the conclusion that your DNS server can't do DNSSEC. Could you please turn on debug logging for resolved and provide a log output generated when you start it and do the failing lookup that causes the issue?

I.e. create `/etc/systemd/system/systemd-resolved.service.d/50-debug.conf` and add:

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

then issue `systemctl daemon-reload && systemctl restart systemd-resolved && systemd-resolve $THEOFFENDINGDOMAIN`.

And then please provide the logs this created: `journalctl -u systemd-resolved`.

Thanks!

**Comment by poettering** [comment]
Closing, due to lack of response.
