### ISSUE TITLE
invalid ownership of pseudoterminal after machinectl shell

### ISSUE THREAD

**Issue by webczat** [systemd/systemd#4260]
Hello.

The usage of sudo and su programs has the problem that, when switching between two unprivileged accounts, we are still using the same pseudoterminal that is owned by the account that originally logged into the system, so programs that need to open the terminal like gpg-agent/pinentry do not work.
machinectl shell is supposed to be a better su, that connects to the shell of the machine as root or a different user, and it gives a fresh pseudoterminal for that. The problem is the pts is owned by root, so using machinectl shell does not solve the above.
I would suggest machinectl shell to chown the pseudoterminal to the user of a newly spawned shell, to allow such programs to work.

**Comment by poettering** [comment]
Hmm, yeah, this appears broken, the tty should be owned by the user, not root.
