### ISSUE TITLE
systemd-resolved does not try other DNS servers if the first server returns REFUSED

### ISSUE THREAD

**Issue by andreyv** [systemd/systemd#4264]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 231
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

systemd-resolved should try the next configured DNS server if the first server fails.
### In case of bug report: Unexpected behaviour you saw

If the first configured DNS server returns a REFUSED reply to a query, systemd-resolved does not try the configured second or third DNS server, and  instead fails to resolve the name. 
### In case of bug report: Steps to reproduce the problem
- Set up `/etc/resolv.conf`:<pre>nameserver [address of the refusing server]
  nameserver 8.8.8.8
  nameserver 8.8.4.4</pre>
- Start `systemd-resolved`
- `systemd-resolve google.com` outputs<pre>google.com: resolve call failed: Could not resolve 'google.com', server or network returned error REFUSED</pre>

**Comment by poettering** [comment]
Hmm, I figure we indeed should not consider REFUSE fatal for the full lookup.

**Comment by halvors** [comment]
Yeah, if possible it should try both servers, if one goes down, keep track of that so that the host know that it may not respond and to use the other instead.

**Comment by poettering** [comment]
Fix waiting in #5276.
