### ISSUE TITLE
IOSchedulingClass and IOSchedulingPriority cannot be changed using dropin

### ISSUE THREAD

**Issue by sergey-safarov** [systemd/systemd#4267]
### In case of bug report: Expected behaviour you didn't see

Created test.service like
[Unit]
DefaultDependencies=no
Wants=local-fs.target
After=local-fs.target
Before=sysinit.target shutdown.target

[Service]
Type=oneshot
ExecStart=/bin/true
IOSchedulingPriority=2

And created test.service.d/10-dropin.conf like 
[Service]
IOSchedulingPriority=
IOSchedulingPriority=4

Execution of "systemctl show test.service | grep IOScheduling" must return "IOScheduling=4"

**Comment by poettering** [comment]
So, the property exposed on the bus is actually the combination of IOSchedulingPriority= and IOSchedulingClass= the way the C macro IOPRIO_PRIO_VALUE() calculates it. See ioprio_set(2) for details about this.

This is a bit confusing. Basically IOSchedulingClass= and IOSchedulingPriority= are the split up, normalizes values, exposed to the user, while the "IOSchedule" property is more low-level and shows both merged into one.

Internally IOPRIO_PRIO_VALUE() just does a shiftleft of the priority value, hence with a bit of right shifting you can extract the original value. And this works correctly here, I just verified this.

Yupp, this is confusing, but there's a bit of logic behind the behaviour.
