### ISSUE TITLE
systemd-nspawn: add zfs snapshot support

### ISSUE THREAD

**Issue by mfischer-zd** [systemd/systemd#4272]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

It should be possible to use a zfs snapshot as the template for a container via `systemd-nspawn --template`.

**Comment by poettering** [comment]
That's unlikely to happen as long as ZFS has no perspective of ever getting merged into the upstream kernel. Sorry.

**Comment by mfischer-zd** [comment]
OK, but a significant proportion (if not a majority) of Linux users will have a ZFS-enabled kernel over the next few years, and the functionality will be useful to them.

**Comment by georgyo** [comment]
Just came here to put a request for the same thing. 

ZFS is gaining quite a bit of steam, with:
Mainlined DKMS support in ubuntu and debian
EPEL support in both el6 and el7
Archlinux has pretty decent AUR support.

ZFS and ZFSonLinux solves so many hard storage problems. That aren't solved nearly as completely or as well on Linux yet. LVM and BTRFS are pieces, but even if you combine their feature sets, it still falls miles short of ZFS. 

It's a fair amount of effort, but I currently hack support for this by doing all the ZFS actions before and after. But really, systemd should be doing this for me like it does with BTRFS.

EDIT: Also noteworthy, docker supports ZFS out of the box.

**Comment by joeblackwaslike** [comment]
would love to see this too, whether technology is the mainstream is completely unrelated to how useful and effective it is.

**Comment by BlauerHunger** [comment]
I recently moved two of my containers from btrfs to zfs (I need stable raid5 support and virtual block devices in the same pool) and stumbled over this missing feature because my containers were configured as --ephemeral and they didn't start anymore until I removed this option. 

I'd really like to see this implemented in systemd since resetting the containers to a known state regularly has security benefits.

**Comment by bunnitech** [comment]
I too would like to see ZFS support, and I suspect it wouldn't hurt with efforts to bring over users from Docker. As an Archer I was looking forward to the combined benefits of ZFS and systemd management. Now I must evaluate whether systemd-nspawn is correct for my use case. I've lost data to btrfs, the only file system to lose data on me in 30 years, I don't want to continue relying on it.

**Comment by johnramsden** [comment]
I would like to see this as well. I've been manually creating my datasets when using ZFS with systemd-nspawn, and it would be great to see this automated. I've been very impressed with ZOL, as I'm sure others are and would love to see better integration with linux tools.

**Comment by ngortheone** [comment]
+1

**Comment by sandhoners123** [comment]
+1

**Comment by poettering** [comment]
btw, has anyone suggested to the ZFS people to simply implement btrfs compatible ioctls for snapshotting?

btrfs ioctls get adopted by other file systems all the time, for example the file clone ones became generically supported. If ZFS added compatible support for btrfs snapshotting ioctls, things would just work...

**Comment by kpetrilli** [comment]
Hi, is there any update to this issue?

Ubuntu has implemented ZFS support since 19.10

**Comment by poettering** [comment]
So, I am pretty sure here too, this should be considered a zfs issue: if they add support for the btrfs ioctls, then things generally should just work.

There's a bug filed for it over on zfs, discussion should be continue there:

https://github.com/openzfs/zfs/issues/10681
