### ISSUE TITLE
Mount unit reaches active state when mount command times out

### ISSUE THREAD

**Issue by edolstra** [systemd/systemd#4275]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> NixOS 16.09
### In case of bug report: Expected behaviour you didn't see

Given an `/etc/fstab` containing:

```
130.161.158.5:/dxs/users4/group/buildfarm /backup nfs4 defaults 0 2
```

where the specified NFS server doesn't respond, causing the NFS mount to time out, I would expect `backup.mount` to reach a failed state. In particular, units that have `RequiredMountsFor=/backup` should not be started.
### In case of bug report: Unexpected behaviour you saw

Instead the unit starts:

```
Oct 03 14:08:33 wendy systemd[1]: Mounting /backup...
Oct 03 14:10:04 wendy systemd[1]: backup.mount: Mounting timed out. Stopping.
Oct 03 14:10:04 wendy systemd[1]: Mounted /backup.
```

```
# systemctl status backup.mount
● backup.mount - /backup
   Loaded: loaded (/etc/fstab; generated; vendor preset: enabled)
   Active: active (mounted) (Result: timeout) since Mon 2016-10-03 14:47:09 CEST; 2min 49s ago
    Where: /backup
     What: 130.161.158.5:/dxs/users4/group/buildfarm
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 63871 ExecMount=/nix/store/6hkiwc8rzfn225yimfp6gj0w6656n0jz-util-linux-2.28.1-bin/bin/mount 130.161.158.5:/dxs/users4/group/buildfarm /backup -t nfs4 (code=killed, signal=TERM)
   Memory: 0B
      CPU: 7ms
   CGroup: /system.slice/backup.mount

Oct 03 14:45:39 wendy systemd[1]: Mounting /backup...
Oct 03 14:47:09 wendy systemd[1]: backup.mount: Mounting timed out. Stopping.
Oct 03 14:47:09 wendy systemd[1]: Mounted /backup.
```

Also, systemd proceeds to start units that have `RequiredMountsFor=/backup`, causing them to write to the mount point directory rather than to the remote file system.
### In case of bug report: Steps to reproduce the problem

Add an `/etc/fstab` entry as above and run `systemctl start backup.mount`.
### Workaround

A workaround is to create a mount unit with `TimeoutSec` greater than `mount`'s timeout. That way, `mount` returns a non-zero exit code (rather than being killed by systemd) and systemd correctly marks the mount unit as failed:

```
# systemctl status backup.mount
● backup.mount - /backup
   Loaded: loaded (/nix/store/gvm9c0fn3hga7ss63hk4yrm3vpindr05-unit-backup.mount/backup.mount; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2016-10-03 15:34:08 CEST; 9min ago
    Where: /backup
     What: 130.161.158.5:/dxs/users4/group/buildfarm
  Process: 61605 ExecMount=/nix/store/6hkiwc8rzfn225yimfp6gj0w6656n0jz-util-linux-2.28.1-bin/bin/mount 130.161.158.5:/dxs/users4/group/buildfarm /backup (code=exited, status=32)

Oct 03 15:29:53 wendy systemd[1]: Mounting /backup...
Oct 03 15:34:08 wendy mount[61605]: mount.nfs: Connection timed out
Oct 03 15:34:08 wendy systemd[1]: backup.mount: Mount process exited, code=exited status=32
Oct 03 15:34:08 wendy systemd[1]: Failed to mount /backup.
Oct 03 15:34:08 wendy systemd[1]: backup.mount: Unit entered failed state.
```

```
```

**Comment by poettering** [comment]
Hmm, when the mount fails but the unit enters the active state anyway, what does /proc/self/mountinfo report about the mount?
