### ISSUE TITLE
systemd-udevd: 80-net-setup-link.rules requires AF_INET address family in RestrictAddressFamilies=

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#4293]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> If I remember correctly, since cc23859.
> At least, reverting cc23859 fixes this problem.

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora 24 (x86_64)
### In case of bug report: Expected behaviour you didn't see

> The error messages below are not shown.
### In case of bug report: Unexpected behaviour you saw

> The following error messages are shown.

```
# journalctl -b --no-hostname
(snip)
Oct 06 13:47:45 systemd-udevd[197]: link_config: could not connect to ethtool: Protocol not supported
Oct 06 13:47:45 systemd-udevd[197]: link_config: could not connect to ethtool: Protocol not supported
Oct 06 13:47:45 systemd-udevd[197]: Could not set offload features of lo: Protocol not supported
(snip)
Oct 06 13:47:47 systemd[1]: Started udev Coldplug all Devices.
Oct 06 13:47:47 systemd[1]: Started udev Kernel Device Manager.
Oct 06 13:47:47 systemd-udevd[315]: link_config: could not connect to ethtool: Protocol not supported
Oct 06 13:47:47 systemd-udevd[315]: link_config: could not connect to ethtool: Protocol not supported
Oct 06 13:47:47 systemd-udevd[315]: Could not set offload features of lo: Protocol not supported
Oct 06 13:47:48 systemd-udevd[311]: link_config: could not connect to ethtool: Protocol not supported
Oct 06 13:47:48 systemd-udevd[311]: link_config: could not connect to ethtool: Protocol not supported
Oct 06 13:47:48 systemd-udevd[311]: Could not set offload features of eth0: Protocol not supported
(snip)
```
### In case of bug report: Steps to reproduce the problem

> boot the system.

**Comment by yuwata** [comment]
0c28d51ac84973904e5f780b024adf8108e69fa1 causes the problem.
If the line `RestrictAddressFamilies=AF_UNIX AF_NETLINK` in systemd-udevd.service is commented out, then the error messages are not shown.

**Comment by yuwata** [comment]
`IMPORT{builtin}="net_setup_link"` in 80-net-setup-link.rules calls `ethtool_connect(fd)` and it fails if `RestrictAddressFamilies=AF_UNIX AF_NETLINK` is enabled.

**Comment by yuwata** [comment]
`ethtool_connect()` calls `socket(PF_INET, SOCK_DGRAM, 0)` in https://github.com/systemd/systemd/blob/master/src/udev/net/ethtool-util.c#L62

So, one of the minimal workaround for this problem is to add `AF_INET` to `RestrictAddressFamilies=`. This works at least for me.

**Comment by poettering** [comment]
indeed.

**Comment by poettering** [comment]
A patch adding AF_INET there would be very welcome!
