### ISSUE TITLE
systemctl: show: properly print contents of more properties (instead of generic "[unprintable]" output)

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#4295]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> latest git snapshot

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora 24 (x86_64)

Currently, `systemctl show` outputs raw value or `[unprintable]`, e.g.,

```
# systemctl -p CPUWeight,RestrictAddressFamilies,MountFlags show systemd-udevd.service
CPUWeight=18446744073709551615
MountFlags=524288
RestrictAddressFamilies=[unprintable]
```

It is hard to understand their meaning.
So, I think `systemctl show` should outputs reader friendly values e.g.

```
# systemctl -p CPUWeight,RestrictAddressFamilies,MountFlags show systemd-udevd.service
CPUWeight=-1
MountFlags=slave
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET
```

**Comment by poettering** [comment]
Yes, it would be a good idea to add more dissectors for properties where we currently show `[unprintable]`. I am a bit concerned however to alter the existing output for properties we already show values, after all the stuff is supposed to be used in scripts, the output is intended to be processed, and if we change the output there things might break for people. Hence: making values that are currently not displayed at all shown is a good thing, but changing the output of fields already shown is something I am not convinced would be a good idea...

or in other words: in your example above, yes we should show RestrictAddressFamilies= in a more useful way. But I am not convinced we should alter the CPUWeight= and MountFlags= output...
