### ISSUE TITLE
RFE: drop console-shell.service

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#4298]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> OpenSUSE
### In case of bug report: Expected behaviour you didn't see

I'm actually not sure the purpose of console-shell service so maybe I'm missing something.

But on regular x86 system where by default the console is the current tty (let's say tty1), this tty is usually acquired by getty@tty1.service at boot. If console-shell.service is enabled both services will fight for acquiring the same tty.

console-shell.service (aka sulogin) looks nicer though during the fight since it will leave getty@tty1.service alone and both services will share the same tty which is already not expected. That said this nice behavior is weird though as console-shell.service uses "StandardInput=tty-force" so I would have expected getty@tty1.service to be kicked up somehow.

However if console-shell.service is started first, then getty@tty1.service will make console-shell.service exit when it will acquire the terminal. This will lead to a shutdown of the system since console-shell.service uses "ExecStopPost=-/usr/bin/systemctl poweroff".

As said I don't really see the purpose of console-shell.service at the beginning therefore maybe a possible fix would be to remove it entirely as it doesn't seem to be broadly used.
### In case of bug report: Steps to reproduce the problem

> systemctl enable console-shell.service
> reboot

**Comment by poettering** [comment]
well, console-shell.service is pretty much an alternative to logind/getty@tty1.service. use either c-s.s or the logind/getty combination, but not both at the same time...

But maybe we should just drop it, I doubt anyone is using that in real-life.

**Comment by fbuihuu** [comment]
> well, console-shell.service is pretty much an alternative to logind/getty@tty1.service. use either c-s.s or the > logind/getty combination, but not both at the same time...

In this case wouldn't it better to make it static and only usable via the kernel command line ?

BTW this service doesn't work well if plymouth is also used: it seems that a "plymouth quit" is missing...

> But maybe we should just drop it, I doubt anyone is using that in real-life.

rescue.target seems very similar to me, so I would tend to think that dropping it should be fine.

That said and as I already described earlier, during my experiment, "StandardInput=tty-force" doesn't look to have any effects since if enabled, console-shell.service will share the same tty with getty@tty1.service.

Is this expected ?

**Comment by poettering** [comment]
rescue.target is boots the system in "rescue" mode, i.e. normal system services are not started at all in this case.

console-shell.service is supposed to be useful for normal clean boots (i.e. multi-user.target or so), as a replacement for logind.service/getty@.service for simpler use cases.

StandardInput=tty-force means that the service will use the tty, regardless if blocked or not. It will take possession of the tty, and this might kick other processes from the tty, but it ultimately doesn't care about that. StandardInput=tty-force is a way to say "fuck tty ownership", it's not a way to say "make sure nobody but I owns the tty", if you follow what i mean.

**Comment by poettering** [comment]
I have converted this issue now into an RFE for removing the unit. The way it is right now it is not usable, as you have pointed out, and I doubt anyone uses it, hence let's kill it

**Comment by fbuihuu** [comment]
Ok I'll send a patch to kill it. Thanks.

**Comment by wlhlm** [comment]
I think this can be closed now.
