### ISSUE TITLE
[systemctl] --user service don't start up automatically but manually

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4301]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

I have two --user service files:

`/etc/systemd/user/dwupdate.service`

```
[Unit]
Description=DWM statusbar
After=dwupdate-audit.service

[Service]
Type=simple
ExecStart=/usr/bin/dwupdate

[Install]
WantedBy=default.target
```

`/etc/systemd/user/dwupdate-audit.service`

```
[Unit]
Description=dwupdate support script
Before=dwupdate.service

[Service]
Type=simple
ExecStart=/usr/bin/dwupdate-audit

[Install]
WantedBy=default.target
```

Both services are `enabled`. But only `dwupdate.service` starts up when I login with my user. What is the problem and why does `dwupdate.service` starts up without `dwupdate-audit.service` although I have set `After=dwupdate-audit.service` in `/etc/systemd/user/dwupdate.service`

When I start them both manually via `systemctl --user start dwupdate.service` and `systemctl --user start dwupdate-audit.service` everything is fine. I have no logs from `dwupdate-audit.service`. The service didn't even tried to start up.
### In case of bug report: Unexpected behaviour you saw

> one of two user services doesn't start up although it's a dependency of another service.
### In case of bug report: Steps to reproduce the problem

Install both services in `/etc/systemd/user/` and enable them with `systemctl --user enable <service` then reboot.

**Comment by martinpitt** [comment]
Can you paste the output of `systemctl --user status dwupdate-audit dwupdate` ? Just to confirm that they are actually both enabled? If so, please check `journalctl --user-unit dwupdate.service --user-unit dwupdate-audit.service`.

Note that having one of the `After=`/`Before=` is enough, you don't need to specify the same relation from both ways.

Also, in general it makes not much sense to enable/disable those both independently. I figure you want to drop `[Install]` from `dwupdate-audit.service` and instead say `Requires=dwupdate-audit.service` in `dwaudit.service` (This also implies the `After=`).

**Comment by arvidjaar** [comment]
> This also implies the `After=`

Are you sure? This implicit dependency is added only for target units to my best knowledge.

**Comment by poettering** [comment]
> Are you sure? This implicit dependency is added only for target units to my best knowledge.

@arvidjaar is right: implicitl After= is only added between units and target units if Wants= or Requires= is used and neither has DEfaultDependencies=no set.

**Comment by martinpitt** [comment]
Ack, thanks So @shibumi, do add `Requires/After=dwupdate-audit.service`, the rest of my qestions are still valid.

**Comment by shibumi** [comment]
Output of `systemctl --user status dwupdate-audit dwupdate`:

```
● dwupdate-audit.service - dwupdate support script
   Loaded: loaded (/etc/systemd/user/dwupdate-audit.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

● dwupdate.service - DWM statusbar
   Loaded: loaded (/etc/systemd/user/dwupdate.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-10-07 15:37:02 CEST; 7h ago
 Main PID: 3052 (dwupdate)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dwupdate.service
           ├─ 3052 /bin/bash /usr/bin/dwupdate
           └─10116 sleep 5

Oct 07 15:37:02 motoko systemd[441]: Started DWM statusbar.
```

Output of `journalctl --user-unit dwupdate.service --user-unit dwupdate-audit.service` (this boot)

```
Oct 07 15:37:02 motoko systemd[441]: Started DWM statusbar.
```

**Comment by poettering** [comment]
Can you run `systemctl show --user default.target` and paste the output here? That should show us whether the dependencies on both services are properly created.

Do you see any relevant log messages by your systemd user instances about any of this? i.e. anything relevant in `journalctl -b _UID=1000 _COMM=systemd` (replace 1000 by your numeric UID).

**Comment by shibumi** [comment]
Ok I have checked the default.target. `Wants=` doesn't include my two user services. But why? They are at the same location and they have both `WantedBy=default.target`. I can't see any differences to my pulseaudio.service or my selfcreated gpg-agent.service.

```
systemctl --user show default.target                                                                                                                                                                                                                                             3 ↵  4094  17:48:24 
Id=default.target
Names=default.target
Requires=basic.target
Wants=gpg-agent.service pulseaudio.service
Conflicts=shutdown.target
After=pulseaudio.service basic.target gpg-agent.service
Documentation=man:systemd.special(7)
Description=Default
LoadState=loaded
ActiveState=active
SubState=active
FragmentPath=/usr/lib/systemd/user/default.target
UnitFileState=static
UnitFilePreset=enabled
StateChangeTimestamp=Mon 2016-10-10 17:13:21 CEST
StateChangeTimestampMonotonic=90631000
InactiveExitTimestamp=Mon 2016-10-10 17:13:21 CEST
InactiveExitTimestampMonotonic=90631000
ActiveEnterTimestamp=Mon 2016-10-10 17:13:21 CEST
ActiveEnterTimestampMonotonic=90631000
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=yes
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=yes
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Mon 2016-10-10 17:13:21 CEST
ConditionTimestampMonotonic=90630998
AssertTimestamp=Mon 2016-10-10 17:13:21 CEST
AssertTimestampMonotonic=90630999
Transient=no
StartLimitIntervalSec=10000000
StartLimitBurst=5
StartLimitAction=none
```

`journalctl -b _UID=1000 _COMM=systemd` has nothing relevant. But an old timer was still active that started `dwupdate.service` before. Maybe this has to do with it. I have disabled it now.

**Comment by poettering** [comment]
Did you run "systemctl --user enable" on both of those units?

**Comment by shibumi** [comment]
Yes both are enabled:

```
● dwupdate.service - DWM statusbar
   Loaded: loaded (/etc/systemd/user/dwupdate.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-10-10 17:14:20 CEST; 1h 20min ago
 Main PID: 3712 (dwupdate)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dwupdate.service
           ├─ 3712 /bin/bash /usr/bin/dwupdate
           └─29911 sleep 5

Oct 10 17:14:20 motoko systemd[2145]: Stopped DWM statusbar.
Oct 10 17:14:20 motoko systemd[2145]: Started DWM statusbar.

● dwupdate-audit.service - dwupdate support script
   Loaded: loaded (/etc/systemd/user/dwupdate-audit.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
```

**Comment by poettering** [comment]
do you see the relevant links having been created in ~/.config/systemd/user/default.target.wants?

**Comment by shibumi** [comment]
No. Just these too:

```
gpg-agent.service:  symbolic link to /etc/systemd/user/gpg-agent.service
pulseaudio.service: broken symbolic link to /etc/systemd/user/pulseaudio.service
```

I have disabled and enabled both services again. Now both links were created. 
When I removed the links I got this messages:

```
Removed /home/chris/.config/systemd/user/graphical.target.wants/dwupdate.service.
Removed /home/chris/.config/systemd/user/multi-user.target.wants/dwupdate-audit.service.
Removed /home/chris/.config/systemd/user/graphical.target.wants/dwupdate-audit.service.
```

Seems like `systemctl --user daemon-reload` doesn't update the links when I edit the service files and I need to disable and enable manually.

**Comment by poettering** [comment]
yes, "systemctl daemon-reload" makes no changes to installation status. in order to reapply installation status use "systemctl reenable foobar.service"

**Comment by poettering** [comment]
So, all is good now? Can we close this?

**Comment by shibumi** [comment]
Yes we can close this. My mistake sorry for the noise.

**Comment by Visor1933** [comment]
@shibumi I don't get how you solved the problem.
I've been going the steps described here, but none of them solved the same issue.
my service was working nicely before and started at boot just like it should. but now it isn't even trying to start.
after I reenabled the service, right after reboot the SELinux has thrown a warning, and I added an exception for my service to SELinux, but still on the next reboot the service hasn't started and again; no log messages in systemctl

**Comment by shibumi** [comment]
@Visor1933 do you see the relevant links having been created in `~/.config/systemd/user/default.target.wants`?

**Comment by Visor1933** [comment]
@shibumi as my service is not a user service, they are created not there, but still, I see them being removed and created

**Comment by shibumi** [comment]
@Visor1933 well this whole issue is about user services..Are you sure that your issues has something todo with this issue?

If they are system services there should be a link in `/etc/systemd/system/` somewhere.. check the `wants` folders.. and you need to enable the services with `systemctl enable <service-name>`
