### ISSUE TITLE
Zone= in [Network] section of *.nspawn files is ignored

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#4303]
### Submission type
- Bug report
### systemd version the issue has been seen with

> 231 (git/master, cfaf4b75)
### Used distribution

> Gentoo, Kernel 4.5.0
### In case of bug report: Expected behaviour you didn't see

> When setting in an `*.nspawn` file
> 
> ```
> [Network]
> Zone=some-zone
> ```
> 
> I'd expect the corresponding `systemd-nspawn` process to be started with `--network-zone=some-zone`, which doesn't happen, although it should (according to [systemd.nspawn#Zone=](https://www.freedesktop.org/software/systemd/man/systemd.nspawn.html#Zone=))
### In case of bug report: Steps to reproduce the problem

> - Create a corresponding `*.nspawn` file for a machine, containing at least:
>   
>   ```
>   [Network]
>   Zone=some-zone
>   ```
> - Start the machine using `machinectl start $machine`
> - Check how `systemd-nspawn` was invoked: `machinectl status $machine`

**Comment by poettering** [comment]
Oh, this is a misunderstanding! nspawn reads configuration from its command line, and combines it with the configuration of an .nspawn file if there is one. Both sources of configuration are equal however, i it doesn't try to funnel the settings from the .nspawn file back into the command line (UNIX doesn't really allow processes to change their command line displayed in ps fully). 

In fact, with --settings= you can configure in detail how the cmdline and the .npsawn settings file are combined (for example, you can control whether the nspawn file wins or the cmdline wins, if both are used for the same particular setting).

Or in other words: even if the settings don't show up in the cmdline, they are applied just fine.

**Comment by eliasp** [comment]
Thanks for clearing this up!

So far I simply assumed `*.nspawn` settings would be translated to the corresponding `systemd-nspawn` arguments, but I should've found out that's not the case on my own :)
