### ISSUE TITLE
Change CtrlAltDelBurstAction= to accept "none" instead of "ignore"

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#4306]
In order to match FailureAction= settings.

See https://github.com/systemd/systemd/pull/4105#issuecomment-252255034 for details

**Comment by keszybz** [comment]
@lnykryn ping

**Comment by lnykryn** [comment]
I have a patch that uses failure_action, but I am now not happy with the name failure_action and its log_messages. https://github.com/lnykryn/systemd/commit/a0bc16b5bf19da93c55f6c88dd7566f6db9ba8a8

**Comment by keszybz** [comment]
I like the commit: that's a nice reduction in LOC ;)
I think you should, preferably as a separate commit, rename `FailureAction` to something more generic. `SpecialAction`?

**Comment by poettering** [comment]
Yes, feel free to rename the concept/source file to something more generic. SpecialAction, ShutdownAction, EmergencyAction, would all work for me. (slight pref for EmergencyAction, but any would work for me...)
