### ISSUE TITLE
Enhancing the journal

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4309]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

If the user wants to disable the systemd-journald daemon for example to minimize ressource usage this has some side effects like he isn't able to see anymore which processes have failed during the boot and journalctl would be not the centralized logging utility of his choice anymore as dmesg would be more reliable in this case. I think this can be enhanced a bit:
- Since logging the journal with systemd-journald and reading it with journalctl are independent to each other I wonder why systemd-journald has its own process. Wouldn't it make more sense to merge the logging capabilities into init to make it more reliable and to minimize the resource usage?
- Alternatively maybe systemd-journald can be designed to run optionally as non-daemon. In this case it would just spawn to log a new received message and terminate afterwards.
- Alternatively I think journalctl should try to get as much information as possible even without systemd-journald running. For example if systemd-journald was not running for the current boot and no log exists for it journalctl could fallback to show at least the kernel messages. And if the information is still available showing which jobs have failed at booting could be helpful too.

**Comment by poettering** [comment]
We don't support journal-less systems. If you disable it, you are on your own. This is well documented,and communicated. And we have no intention to change that, really.

Sorry.

**Comment by Sworddragon** [comment]
Does this also apply if Storage is set to none in journald.conf? If not the last alternative could be an enhancement. And the first 2 points are possibilities if the journal is not disabled (but I noticed now huge memory usage from systemd-journald and I assume this comes from loading the journal into an own cache so maybe the first one is out).

**Comment by poettering** [comment]
@Sworddragon journald doesn't really do much caching. It simply maps the journal files it access into memory using mmap(), and leaves all caching to the usual kernel pagecache. How did you determine "memory usage"? It will use a lot of address space, sure, but "address space usage" is very different from "memory usage", as the address space is usually not backed by RAM, but only on demand, by disk.

If you turn off storage in journald, then you won't get journalctl, I think that's a fair deal.

**Comment by Sworddragon** [comment]
I have read at some site that systemd-journald intends to be a centralized logging daemon to simplify logging on Linux (not sure is this is the real intention but cases that require falling back to dmesg would be a weak spot if this is true). The huge memory usage from possibly the own cache I was pointing to was meant to be the RES usage I have noticed from systemd-journald. It has begun with a few MiB and increased a bit after every boot (RES is currently at 20 MiB after some boots) but I'm assuming this is normal.

Anyways, I'm going to disable systemd-journald on my systems as there is no much use for me to have it permanently running (but I'm enabling it temporary if needed). The tricky part is that masking the related service file causes some [ FAIL ] to appear on booting and since the lines are printed too fast there is no way to tell what it caused so I have to try some things out a bit (though, this reminds me on the pre - OS-boot pause function and now I'm wondering if such a function exists in Linux too. I'm checking this later and if such a function is missing I have a new feature request, but for the kernel in this case, so you have not to "fear" that I bother you with this in another ticket - for now :) ).
