### ISSUE TITLE
networkd: make TCP Segmentation Offload configurable

### ISSUE THREAD

**Issue by morfikov** [systemd/systemd#432]
Is there a way to disable TCP Segmentation Offload (TSO) using systemd's network mechanism/files? I need one container that is able to produce "normal" packets (1514 bytes), but this TSO feature is enabled by default on the virtual interfaces, at least when it comes to LXC containers.

I can disable it using the following command (on both ends of the container):

```
# ethtool --offload veth10-sid tso off ufo off gso off gro off
```

I've been trying to find some info on this subject, but unfortunately I couldn't find anything useful.

**Comment by poettering** [comment]
We currently do not support setting this with networkd. But I'd be open to add a patch that adds a .network and .link file option for this.

**Comment by dvdhrm** [comment]
I added this to the TODO list now. However, I have no clue how to test this or where to start implementing this. We recently added 'VNetHeader=' to configure this for TAP devices in f5f07dbf06f6df9d12e092c05ad8cfbe244d203f, not sure whether this applies to veth, too.

Maybe @ssahani knows more about this, or @teg.

**Comment by ssahani** [comment]
I am working on it.
https://github.com/systemd/systemd/compare/master...ssahani:ethtool

**Comment by teg** [comment]
@ssahani any progress on that stuff?

**Comment by ssahani** [comment]
I have not looked into this. I need to figure out how to implement this which @michich mentioned.
