### ISSUE TITLE
pathchange triggers always show "systemd[1]: Started foo" in the logs.

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#4324]
### Submission type
- [ X] Bug report
### systemd version the issue has been seen with

All of them

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Irrelevant
### In case of bug report: Expected behaviour you didn't see

When path changes occur the associated type service unit file should 
a) Start the type service file if not running and accurately represent that action in the journal ( works )
b) If the type service is already running tried reloading it instead and accurately represent that action in the journal ( fails )
c) If the type service file is already running and does not support reload use restart instead ( reload-or-restart ) and accurately represent that action in the journal ( fails )
### In case of bug report: Unexpected behaviour you saw

The log always shows "systemd[1]: Started test." even if the service is already running.
### In case of bug report: Steps to reproduce the problem

Create the following type units 

test.service
[Unit]
Description=test
Documentation= man:systemd.service

[Service]
Type=oneshot
ExecStart=/usr/bin/echo "test"
RemainAfterExit=yes

test.path
[Unit]
Description=Test
Documentation= man:systemd.path

[Path]
PathModified=/tmp/foo.test

Start both type units

Run journalctl -f in one terminal window and touch /tmp/foo.test in another
Observer that the log output is always showing "systemd[1]: Started test." but never "systemd[1]: Reloaded test." or "systemd[1]: Restarted test." when the test file gets touched.

**Comment by poettering** [comment]
So the usecase I presume is about changing configuration files? I am really not convinced that that's a good usecase, due to atomicity issues.

**Comment by stephankn** [comment]
It sounds like a cosmetic bug to show repeatedly "started" for services already in the state running. I disagree that the service should get reloaded. At least not without further conditional checks in the unit.

It would break existing things.
I have a similar issue here. Triggering the service with PathExists. As inotify() also fires on a touch of the path, this would lead to unwanted restarts.
Maybe supporting some "PathCreated" statements which fire _only_ on creation of a new file could supplement the idea of this ticket. Would need some further testing of what O_CREAT exactly means for inotify, as for example touch uses this in its open() call. Shoudl not trigger systemd when file exists.
http://man7.org/linux/man-pages/man7/inotify.7.html

What is requested here is sort of a definition of what action to take when the Path triggers. Whether to start a service, restart/reload it or stop it. Similar was requested here: https://github.com/systemd/systemd/issues/3642

**Comment by johannbg** [comment]
@poettering right was testing this after the configuration discussion to see what might need fixing since you seem to have decided to support file association in type unit files ( configuration file in the case of that Red Hat product which will obviously never fly with upstream services so downstream distribution will have to ship a snipped for all service supported by or for that product ) administrators will want to take some action based upon that if they are supposed to gain anything from defining it in the first place.

**Comment by dominic-p** [comment]
Sorry to dredge up an old issue, but I thought I would contribute my use case. I use systemd to [manage node.js applications](https://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/).

As it is now, after I push updates to the server, I have to manually restart the service to pick them up. Having the ability to automatically restart a service on file/directory changes would really simplify this use case.

**Comment by johannbg** [comment]
Closing this RFE since even the crickets are dead at this point ;)
