### ISSUE TITLE
 systemd-remount-fs fails if data=writeback is specified in /etc/fstab

### ISSUE THREAD

**Issue by calendulish** [systemd/systemd#4333]
journal:

```
Out 10 13:41:13 Amora systemd-remount-fs[113]: mount: / não está montado ou opção inválida
Out 10 13:41:13 Amora systemd-remount-fs[113]:        Em alguns casos, informações úteis são encontradas no
Out 10 13:41:13 Amora systemd-remount-fs[113]:        syslog - tente "dmesg | tail" ou algo assim.
```

dmesg:
`[  100.992331] EXT4-fs (sda6): Cannot change data mode on remount`

fstab:

```
/dev/sda1       /boot       vfat        defaults                                              1 2
/dev/sda6       /           ext4        noatime,norelatime,data=writeback,commit=120          0 1
/dev/sda2       /home       ext4        noatime,norelatime,data=writeback,commit=120          0 1
/dev/sda7       none        swap        defaults                                              0 0
```

The kernel doesn't allow changing data=writeback during runtime, but my system is mounted without data=writeback? It's not right...

---

systemd 231
Gentoo x86_64

**Comment by poettering** [comment]
if the kernel doesn't permit changing a mount option during runtime, then you'll get the error you see. In this case, make sure to pass the right mount optoins right when mounting the file system...

How that works for the root directory really depends on your initrd/distro. Sometimes you have to alter rootflags= on the kernel cmdline for that, and on other systems you need to rebuild your initrd to make it aware of the changed option.

Either way, this is nothing we can do anything about in systemd. It's between the kernel, the initrd, the bootloader and you...

Closing. Hope this makes sense.
