### ISSUE TITLE
SetLinkDNS does not override old DNS server

### ISSUE THREAD

**Issue by emanuele-f** [systemd/systemd#4334]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231-4
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> SetLinkDNS should make systemd-resolved use new provided DNS servers
### In case of bug report: Unexpected behaviour you saw

> Old DNS server it's still used for DNS queries. SetLinkDNS inserts new DNS servers _after_ old DNS server in /run/systemd/resolve/resolv.conf
### In case of bug report: Steps to reproduce the problem

> Command: `sudo busctl call "org.freedesktop.resolve1" "/org/freedesktop/resolve1" "org.freedesktop.resolve1.Manager" SetLinkDNS 'ia(iay)' INTERFACE_HERE 2 2 4 208 67 222 222 2 4 208 67 220 220`
> 
> Look at /run/systemd/resolve/resolv.conf
> 
> _Before SetLinkDNS_
> nameserver 192.168.1.1
> search lan
> 
> _After SetLinkDNS_
> nameserver 192.168.1.1
> nameserver 208.67.222.222
> nameserver 208.67.220.220
> search lan

**Comment by poettering** [comment]
what do "systemd-resolve --status" report before and after the call?

**Comment by emanuele-f** [comment]
```
Global
         DNS Servers: 192.168.1.1
          DNS Domain: lan
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 9 (tun0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 208.67.222.222
                      208.67.220.220

Link 4 (dummy0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlan0)
      Current Scopes: LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (eth0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
```

**Comment by poettering** [comment]
So you have per-link and global DNS servers configured. resolved will collect all per-link DNS servers (from all links) as well as the global DNS servers and write them to resolv.conf in one list...

How precisely did you configure the 192.168.1.1 DNS server?

**Comment by emanuele-f** [comment]
I use wicd as a network manager, and my network uses DHCP for IP/DNS configuration.

After I connect to my network, I see /etc/resolv.conf being written with

```
# Generated by resolvconf
domain lan
nameserver 192.168.1.1
```

So I think wicd is using resolvconf rather than systemd dbus API.

My /etc/nsswitch.conf uses "resolve" and not "dns". My /etc/resolv.conf is not linked to /run/systemd/resolve/resolv.conf.

**Comment by poettering** [comment]
Well, in that case the global configuration is read from /etc/resolv.conf, then augmented with the per-link configuration and written to /run/systemd/resolve/resolv.conf, hence everything works as intended.

Generally, either push DNS configuration to resolved per link or use global configuration, but not both. Local configuration extends global configuration, it does not override it.

resolved is either consumer of /etc/resolv.conf or its provider. In your case it is consumer of it, and it will write whatever it reads from there to /run/systemd/resolve/resolv.conf as long as that file exists...
