### ISSUE TITLE
systemd-logind assertion triggered

### ISSUE THREAD

**Issue by danpovey** [systemd/systemd#4341]
### Submission type

This happened on debian 8.5 on a Dell rack server.
A machine was not responding to ssh connections, and on the console I saw this:
  assertion 'f' failed at ../src/journal/journal-file.c:116, function journal_file_close().  
There were also fairly normal messages about hung tasks, like:
  task nnet3-compute blocked for more than 120 seconds.  Aborting  
[not sure if that could be due to a failure in systemd-logind?]  
I copied this from the console by hand.  I can't find anything obviously wrong with the server and there is nothing particularly interesting looking in the logs.

I am not sure if the following is relevant (we got it when rebooting):

Oct 10 22:08:01 b01 kernel: Initializing cgroup subsys cpuset
Oct 10 22:08:01 b01 systemd-journal[626]: Runtime journal is using 8.0M (max allowed 4.0G, trying to leave 4.0G free of 56.7G available <E2><86><92> 
Oct 10 22:08:01 b01 systemd-journal[626]: Runtime journal is using 8.0M (max allowed 4.0G, trying to leave 4.0G free of 56.7G available <E2><86><92> 
-- Reboot --
Oct 10 21:35:13 b01 /usr/sbin/irqbalance[45370]: irq 139 affinity_hint subset empty
Oct 10 21:35:13 b01 /usr/sbin/irqbalance[45370]: irq 137 affinity_hint subset empty
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> …
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
Which version of systemd is this?

**Comment by poettering** [comment]
The assert you pasted suggesta this is actually a crash in journald, not logind?

**Comment by cpupa** [comment]
Hello, the system in question uses Debian 8, systemd versions 215-17+deb8u4.

**Comment by keszybz** [comment]
> task nnet3-compute blocked for more than 120 seconds. Aborting

This looks like some kernel trouble. Anyway, anything related to systemd-215 should be handled in the distribution bugtracker. Please take it up with Debian.
