### ISSUE TITLE
PAM: user@1000.service: Failed at step PAM spawning /usr/lib/systemd/systemd: Operation not permitted

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#4342]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> I guess that from baed1fedba161d7db89636a417751891831c432a. The git snapshot ec72b96 has the issue, and 084f580 does not.

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora 24 x86_64
### In case of bug report: Expected behaviour you didn't see

> The error message below is not shown.
### In case of bug report: Unexpected behaviour you saw

> The following error message is shown.
> 
> ```
> $ journalctl -b
> (snip)
> lightdm[666]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
> systemd[1]: Created slice User Slice of lightdm.
> systemd[1]: Starting User Manager for UID 988...
> systemd-logind[505]: New session c1 of user lightdm.
> systemd[1]: Started Session c1 of user lightdm.
> systemd[669]: user@988.service: Failed at step PAM spawning /usr/lib/systemd/systemd: Operation not permitted
> systemd[1]: Started User Manager for UID 988.
> (snip)
> systemd[1]: Starting User Manager for UID 1000...
> systemd[718]: user@1000.service: Failed at step PAM spawning /usr/lib/systemd/systemd: Operation not permitted
> systemd-logind[505]: New session 1 of user watanabe.
> systemd[1]: Started User Manager for UID 1000.
> systemd[1]: Started Session 1 of user watanabe.
> lightdm[711]: pam_unix(lightdm:session): session opened for user watanabe by (uid=0)
> (snip)
> ```
> 
> Note that if we use the previous pam.d/systemd-user, called fedora-specific one, then the above error message is not shown.
### In case of bug report: Steps to reproduce the problem

> boot the system and login.

**Comment by poettering** [comment]
do you have selinux enabled?

**Comment by poettering** [comment]
(note that the new PAM file is minimal, and it is expected that distros make changes to it before it is really usable. That said it should be complete enough so that you can boot with, except if you use some MAC or so.)

**Comment by yuwata** [comment]
No. In my machines, selinux is disabled by the kernel command line.

**Comment by poettering** [comment]
@fsateler any idea?

**Comment by yuwata** [comment]
@poettering OK. If this is expected behavior, please close this issue. Thanks.

**Comment by fsateler** [comment]
@poettering I see I left no account modules in the bare-bones PAM config. Maybe it is pam_acct_mgmt failing then?

@yuwata what happens if you add `account required pam_unix.so` ?

I'm not at the machine I can test ATM.

**Comment by yuwata** [comment]
@fsateler Thanks. By adding the line, user sessions successfully start without the error messages. Do you think the line should be added to the minimal PAM file?

**Comment by fsateler** [comment]
I think so. I'll prep a patch.

@poettering I think we should also offer a configure flag for skipping installing the pam config. This way using `make install` doesn't destroy the current distro config.

**Comment by poettering** [comment]
Yeah, yes to both. Yes, we should ship a minimal version that works I guess, hence the pam_unix.so line should indeed be added. And yes, a configure switch to disable installing of the whole fragment makes sense, too
