### ISSUE TITLE
initrd-cleanup.service: killed by SIGTERM and goes to emergency shell

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#4343]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> git snapshot 084f580 works fine, but ec72b96 has the following problem.

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora 24 x86_64
### In case of bug report: Expected behaviour you didn't see

> boot system fine without goes to emergency shell.
### In case of bug report: Unexpected behaviour you saw

> The booting process is stopped and goes to the emergency shell. The following error messages are found in the journal.
> 
> ```
> # journalctl
> (snip)
> systemd[1]: Reached target Initrd File Systems.
> systemd[1]: Reached target Initrd Default Target.
> systemd[1]: Starting Cleaning Up and Shutting Down Daemons...
> systemd[1]: Stopped target Remote File Systems.
> systemd[1]: Stopped target Remote File Systems (Pre).
> systemd[1]: Stopped target Timers.
> systemd[1]: initrd-cleanup.service: Main process exited, code=killed, status=15/TERM
> systemd[1]: Stopped Cleaning Up and Shutting Down Daemons.
> systemd[1]: initrd-cleanup.service: Unit entered failed state.
> systemd[1]: initrd-cleanup.service: Triggering OnFailure= dependencies.
> systemd[1]: initrd-cleanup.service: Failed with result 'signal'.
> systemd[1]: Starting Setup Virtual Console...
> systemd[1]: Stopped target Initrd Default Target.
> systemd[1]: Stopped target Basic System.
> systemd[1]: Stopped target System Initialization.
> systemd[1]: Stopped target Swap.
> systemd[1]: Stopped udev Coldplug all Devices.
> systemd[1]: Stopping udev Kernel Device Manager...
> systemd[1]: Stopped Apply Kernel Variables.
> systemd[1]: Stopped target Local File Systems.
> systemd[1]: Stopped target Sockets.
> systemd[1]: Stopped target Slices.
> systemd[1]: Stopped target Paths.
> systemd[1]: Stopped Dispatch Password Requests to Console Directory Watch.
> systemd[1]: Stopped target Initrd Root Device.
> systemd[1]: Started Setup Virtual Console.
> systemd[1]: Starting Emergency Shell...
> systemd[1]: Stopped udev Kernel Device Manager.
> systemd[1]: Stopped Create Static Device Nodes in /dev.
> systemd[1]: Stopped Create list of required static device nodes for the current kernel.
> systemd[1]: Closed udev Kernel Socket.
> systemd[1]: Closed udev Control Socket.
> systemd[1]: Starting Cleanup udevd DB...
> systemd[1]: Started Cleanup udevd DB.
> ```
> 
> In the emergency shell, `systemctl start initrd-switch-root.service` does not work. By manually calling `/usr/bin/systemctl --no-block --force switch-root /sysroot` the system can continue to boot. 
### In case of bug report: Steps to reproduce the problem

> install the latest systemd and reboot the system

**Comment by arvidjaar** [comment]
`initrd-cleanup.service` calls `systemctl --no-block isolate initrd-switch-root.target`. Because `initrd-cleanup.service` itself is not dependency of `initrd-switch-root.target`, it is scheduled to be stopped. What happens further is race condition. It is possible that last commit changed timings so systemd now has chance to kill process before it exits itself.

**Comment by yuwata** [comment]
So, what do you think is a workaround for this problem? I do not know about 'shutting down' process well. What kind of dependency should be added?

**Comment by yuwata** [comment]
@arvidjaar Thanks. Adding `Wants=initrd-cleanup.service` to initrd-switch-root.target works fine!

**Comment by arvidjaar** [comment]
@yuwata No, that's really wrong. Adding `IgnoreOnIsolate=true` to `initrd-cleanup.service` seems more appropriate. And it should really be accompanied by good comment explaining why it is needed.

**Comment by yuwata** [comment]
@arvidjaar Thank you for your comment. What is the merit of using `IgnoreIsolate` instead of adding `Wants=initrd-cleanup.service`? At least, my PR which is already merged works fine for me. Again, I do not understand well about isolating a target. So, could you explain why we should use `IgnoreIsolate` and submit another PR if needed?
