### ISSUE TITLE
systemd-vconsole-setup: KD_FONT_OP_GET failed, fonts will not be copied: No space left on device

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#4344]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> I guess since eb22d84b47f16bedb60824b441900715fd79841d. At least ec72b963666020003d780fcc0751bc84da14e258 still has the following issue.

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> fedora 24 x86_64
### In case of bug report: Expected behaviour you didn't see

> The error messages below are not shown.
### In case of bug report: Unexpected behaviour you saw

> My several machines (not all) sometimes (not always) show the following error messages during the boot process.
> 
> ```
> # journalctl -b | grep systemd-vconsole
> systemd-vconsole-setup[398]: KD_FONT_OP_GET failed, fonts will not be copied: No space left on device
> systemd-vconsole-setup[399]: KD_FONT_OP_GET failed, fonts will not be copied: No space left on device
> ```
### In case of bug report: Steps to reproduce the problem

> Boot the system.

**Comment by keszybz** [comment]
@msoltyspl

Can this error come from
https://github.com/torvalds/linux/blob/master/drivers/tty/vt/vt.c#L4087 ?
Should we read the number of chars in the font first, and then allocate the buffer of specified size?

**Comment by msoltyspl** [comment]
Yea, it looks like it might be necessary - so first call with null buffer to get correct values, then with actual buffer to get the actual font data.

I'll try to do this (I remember about man patch too), just had a bit much work at hands recently.

**Comment by msoltyspl** [comment]
~~Actually looking at that function's flow, it seems we can simply set the values to 0.~~

**Comment by msoltyspl** [comment]
I did some tests with suggested approach - to first get font info and then to copy it, but ... even with buffer set to null I got -ENOSPC ... occasionally.

This is weird.

**Comment by keszybz** [comment]
If I'm reading the kernel code correctly, it also tests that `font.width > op->width || font.height > op->height` is false, and might return -ENOSPC in that case. Could you be hitting that?

**Comment by msoltyspl** [comment]
Yea, looks like you're right - op.data is not tested in this case. TBH I'd think it's a bug - the whole block testing for count/width/height should only be done if op.data is not NULL.

But regarding Yuwata's bug - it's still weird. 32/32/512 are formally maximum values. If any of the 'if' comparisons trigger, that would suggest that:

rc = vc->vc_sw->con_font_get(vc, &font);

call at line 4076 fills some of the 'font' fields with larger values than formally allowed (or there is some new/old bug getting triggered).

**Comment by msoltyspl** [comment]
I did some tests with suggested approach - to first get font info and then to copy it, but ... even with buffer set to null I got -ENOSPC ... occasionally.

This is weird.

**Comment by msoltyspl** [comment]
Anyway, my idea is this
- 1st ioctl - with UINT_MAX values and NULL buffer to get the values as reported by kernel; as far as I can see this should never fail this way
- sanitize provided values - if they go beyond 32/32/512 - complain in logs (possible kernel bug, etc.) and abort copying, otherwise
- 2nd ioctl - actual get fonts call

**Comment by msoltyspl** [comment]
Think I got the culprit, basically once I get in logs:
Oct 21 15:15:09 hakai kernel: [drm] Memory usable by graphics device = 2048M
Oct 21 15:15:09 hakai kernel: [drm] Replacing VGA console driver
Oct 21 15:15:09 hakai kernel: Console: switching to colour dummy device 80x25
Oct 21 15:15:09 hakai kernel: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
Oct 21 15:15:09 hakai kernel: [drm] Driver supports precise vblank timestamp query.

The lovely dummy driver implements con_fon_get() (and majority of other functions) as:

static int dummycon_dummy(void)
{
    return 0;
}

So the arguments normally passed to the function are left with whatever junk was in them originally, for example:

Oct 21 15:15:09 hakai lt-systemd-vconsole-setup[350]: Invalid font parameters - width: 443606400 (max 32), height: 4294936580 (max 32), count: 0 (max 512), fonts will not be copied

Once proper drm driver takes over, udev repeats the call and everything is fine.

Anyway, this clearly need a simple fix in the kernel, on our side we can only left some sensible message in logs (such as the one above).

Actually, I think we can exclude call to systemd-vconsole-setup in udev rules as well for that particular case.

**Comment by AndydeCleyre** [comment]
What device is running out of space here? I am currently getting this log, and on some boots my chosen font is only used for TTY1, while TTYs 2-6 use a different font. But on some boots, despite this message, TTYs 1-6 seem to use the correct font anyway.

I'm creating this font, but I'm not sure what's too big about it, or what size to target. The compressed `.gz` is ~6.6Ki, and the uncompressed `.psf` is ~54Ki.

**Comment by AndydeCleyre** [comment]
I'm still experiencing this, and happy to provide any info that can shed light, if someone can let me know what that would be.
