### ISSUE TITLE
Make C-A-D combination do what the user wants instead of hardcoding rebooting

### ISSUE THREAD

**Issue by GiedriusS** [systemd/systemd#4346]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Archlinux

Currently pressing C-A-D 7 times in 2 seconds immediately triggers a reboot. This is annoying if the user started a shutdown sequence and then they press C-A-D 7 times in 2 seconds because the system restarts instead of shutting down and thus afterwards they have to power off the machine e.g. by pressing the power button. What I am proposing is this: in the case of C-A-D being pressed 7 times in 2 seconds make the action taken depend on the user choice. If the user wanted to reboot then reboot the system, if the user wanted to shutdown the system then shutdown the system.

**Comment by GiedriusS** [comment]
Oops, looks like it is already fixed upstream by https://github.com/systemd/systemd/commit/24dd31c19ede505143833346ff850af942694aa6. Sorry.

**Comment by GiedriusS** [comment]
Thinking about this more... maybe it would still be nice to make the behaviour depend on what the user currently wants to do instead of making it configurable? Because after that commit it is still possible to run into such situation as described by the original post.

**Comment by killermoehre** [comment]
@GiedriusS CAD7in2 is like »DO IT! NOW!« and designed to do the configured thing regardless of the current system state. So unconditionally doing it is the expected action. Also why do you need to CAD your shutdown/reboot process? Sounds broken to me.

**Comment by poettering** [comment]
@GiedriusS i figure expediting the operation currently in process instead of always rebooting on the 7in2 CAD case makes sense. Please consider filing a separate RFE issue about that.
