### ISSUE TITLE
Incorrect (double) escaping of pathes in RequiresMountsFor=

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#435]
```
$ systemctl cat test.target
# /etc/systemd/system/test.target
[Unit]
RequiresMountsFor=/test-directory

$ systemctl show -p Requires,After test.target
Requires=-.mount test\x5cx2ddirectory.mount
After=-.mount test\x5cx2ddirectory.mount
```

It says `test\x5cx2ddirectory.mount` instead of `test\x2ddirectory.mount`, i. e. the string is escaped twice.

**Comment by intelfx** [comment]
In fact, after a reboot, I get:

```
$ sudo systemctl show -p Requires,After test.target
Requires=-.mount
After=-.mount
```

So the first time the required `.mount`-unit has been found (under a wrong name? wtf?), but the second time it has not been even found.

**Comment by arvidjaar** [comment]
> It says test\x5cx2ddirectory.mount instead of test\x2ddirectory.mount, i. e. the string is escaped twice.

It was recently discussed on ML, strings are escaped on output and there is no information whether they are already escaped.

As for second question it looks correct - /test-directory is in /, so the only mount that has to be present is / itself.

**Comment by intelfx** [comment]
I have a mountpoint `/test-directory` in fstab, which somewhy doesn't get pulled in by the test target... but if this double escaping is "display only", then I suppose my problem is somewhere else.

**Comment by arvidjaar** [comment]
> I have a mountpoint /test-directory in fstab, which somewhy doesn't get pulled in by the test target... 

But is it mounted? Could you show /etc/fstab?

**Comment by intelfx** [comment]
No, it isn't (and doesn't get mounted).

It says `none /test-directory tmpfs noauto 0 0`.

**Comment by mbiebl** [comment]
If it's "noauto", then it won't be mounted automatically, i.e. hooked up in local-fs.target

**Comment by intelfx** [comment]
I know, but I wanted the target to pull in the mount...

...but well. I've missed this sentence in the man.

> Mount points marked with noauto are not mounted automatically and will be ignored for the purposes of this option.

Ok, so this whole report is invalid.
