### ISSUE TITLE
DPI settings for Logitech G502 Prometheus

### ISSUE THREAD

**Issue by attilakinali** [systemd/systemd#4356]
Hi,

I have new DPI settings for a Logitech G502 Gaming mouse. I am not 100% sure whether the update frequency setting is correct, but that's the closest "even" value.

mouse:usb:v046dpc07d:name:Logitech Gaming Mouse G502:
 MOUSE_DPI=1200@550 2400@550 *3200@550 6400@550

**Comment by poettering** [comment]
@attilakinali any chance you can submit this as proper PR adding this to the hwdb? That way the commit will be attributed to you, and everything.

cc @whot

**Comment by phomes** [comment]
The G502 can have DPI and frequency settings configured on the device. The mouse can also switch between a few different profiles on the mouse. Are these the values all the default values and for the default profile. if we can call one profile that?

The idea of these settings here are to make sure that all mice have similar sensitivity out of the box. That is why this must be measured from a "factory reset" mouse.

**Comment by poettering** [comment]
@attilakinali any chance you can respond to @phomes question?

**Comment by poettering** [comment]
Closing due to lack of response,
