### ISSUE TITLE
core/execute: regression in setting groups for root-namespaced services

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#4357]
### Submission type
- Bug report
### systemd version the issue has been seen with

master (18e51a022c632344c4a48ba6ccb3475fad2a2c3b)
### In case of bug report: Steps to reproduce the problem

This has been caught by rkt CI on systemd master: https://github.com/coreos/rkt/issues/3262

I was also able to reproduce with a bare service unit on systemd master:

```
[Unit]
Description=Test suppgid

[Service]
RootDirectory=/root/chroot
ExecStart=/bin/bash -c 'echo ok'
SupplementaryGroups=50
MountFlags=shared
```

Where `/root/chroot` is a bare chroot only containing a static bash binary and gid 50 exists on the host.
### In case of bug report: Unexpected behaviour you saw

```
● suppgid.service - Test suppgid
   Loaded: loaded (/etc/systemd/system/suppgid.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2016-10-12 13:44:09 UTC; 48s ago
 Main PID: 118 (code=exited, status=216/GROUP)

Oct 12 13:44:09 xantho systemd[1]: Started Test suppgid.
Oct 12 13:44:09 xantho bash[118]: suppgid.service: Failed at step GROUP spawning /bin/bash: No such file or directory
Oct 12 13:44:09 xantho systemd[1]: suppgid.service: Main process exited, code=exited, status=216/GROUP
Oct 12 13:44:09 xantho systemd[1]: suppgid.service: Unit entered failed state.
Oct 12 13:44:09 xantho systemd[1]: suppgid.service: Failed with result 'exit-code'.
```
### Notes

This used to work in v231, and still works after removing the `MountFlags=shared` option from the unit above. I didn't bisect this, but 096424d1230e0a0339735c51b43949809e972430 looks suspiciously close to be relevant. Does `enforce_groups()` rely on `/etc/group` or similar files which are not anymore available once the new root has been established via the mount namespace?

/cc @poettering @tixxdz as commit/PR authors

**Comment by lucab** [comment]
As a sidenote, since #4185 I'm also seeing a regression in rkt (`TestAppUserGroup` in the log linked above) when using systemd-nspawn `--private-users=X:Y` and setting uid/gid on service units inside such nspawn environment, but I'm having an hard time isolating it and I'm not sure if it is just another side effect of the same bug here.

I'll probably revisit that once this is patched, if nothing else obvious emerges in the meanwhile.

**Comment by evverx** [comment]
BTW: there are so many good tests there: https://github.com/coreos/rkt/tree/master/tests

I wonder why not to run those tests against every our PR?
I.e.

```
xenial-amd64 ...
xenial-i386 ...
xenial-s390x ...
default ...
semaphoreci ...
--> rkt <---
```

**Comment by tixxdz** [comment]
@lucab hey thank you for the report! so there is a fix at https://github.com/systemd/systemd/issues/4373 could you try it please, and for the other issue do you have more information ? otherwise will try to check later.

Thanks!

**Comment by lucab** [comment]
So your PR fixes the gid regression, but I'm still seeing the regression related to `--private-users`. 

However, I'm not able to isolate it outside of rkt invocation, so I'm just adding more details here:
- This happens always when invoking a rkt run with `--private-users` and `--user=xxx`, which in turn calls systemd-nspawn with `--private-users=nnn:65536` and pass `User=xxx` to the service unit. Only on systemd master though, v231 is fine.
- When this fails, exit status is 203 (`EXIT_EXEC`)
- When this fails, execve return with a `-ENOENT`, even though the executable file is there
- Disabling all `ReadOnlyDirectories` and `InacessibleDirectories` from the service unit makes it working again

**Comment by evverx** [comment]
> but I'm still seeing the regression related to --private-users

I've reproduced:

> 6b7c9f8bce4679c89f3b89cacfd4932c0aeadad4 is the first bad commit

How to reproduce:

``` sh
systemd-nspawn -D /some/cont/with/systemd/inside -U -b
...
# inside the container
mkdir /chroot
cp $(type -P busybox) /chroot
ln -s busybox /chroot/sh
cat <<'EOF' >/etc/systemd/system/hola.service
[Service]
ExecStart=/sh -c 'echo Hey'
RootDirectory=/chroot
WorkingDirectory=/
User=1
ReadOnlyDirectories=-/chroot/proc
EOF
/prepare-app /chroot # https://github.com/coreos/rkt/blob/v1.17.0/stage1/prepare-app/prepare-app.c
systemctl start hola

```

https://github.com/systemd/systemd/pull/4372/commits/399ca8ccd62c276c0664e92fa7951d29925a3aac fixes the issue

BTW:
I used:

```
./configure --with-stage1-flavors=src --with-stage1-systemd-version=BRANCH-NAME --with-stage1-systemd-src=PATH-TO-SYSTEMD-SRC --enable-functional-tests
```

is there any reason why I can't pass COMMIT-SHA instead of the BRANCH-NAME?
What is the best way to bisect `systemd` against `rkt`?
I ran something like

```
cd rkt
./autogen.sh
./configure --with-stage1-flavors=src --with-stage1-systemd-version=regress --with-stage1-systemd-src=PATH-TO-SYSTEMD-SRC --enable-functional-tests
make
make functional-check GO_TEST_FUNC_ARGS='-run TestAppUserGroup'
```

where `regress` is the "fake" branch (marked by `git bisect run` inside the `systemd` source directory)
But this looks ugly to me :-)

**Comment by lucab** [comment]
@evverx Thanks a lot for looking into this! I somehow managed to miss reproducing it, probably because I didn't fiddle with procfs.

> Is there any reason why I can't pass COMMIT-SHA instead of the BRANCH-NAME?
> What is the best way to bisect systemd against rkt?

I'll look if it is possible to make it is easier to bisect systemd from rkt configure, as it is something we don't do so often.

**Comment by evverx** [comment]
@lucab , thanks!

Anyway

``` sh
hola.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
hola.service: Executing: /sh -c 'echo Hey'
hola.service: Failed at step EXEC spawning /sh: No such file or directory
hola.service: Failed to send unit change signal for hola.service: Connection reset by peer
hola.service: User lookup succeeded: uid=1 gid=1
hola.service: Failed to send unit change signal for hola.service: Transport endpoint is not connected
hola.service: Child 49 belongs to hola.service
hola.service: Main process exited, code=exited, status=203/EXEC
hola.service: Changed running -> failed
hola.service: Unit entered failed state.
hola.service: Failed with result 'exit-code'.
```

Do we really want to ignore the `setup_namespace`-errors?
In this particular case:
- the `setup_namespace` fails
- we don't `chroot` into the `RootDirectory`
- we ignore this
- we try to run `ExecStart=/sh` (from the real root directory)
- this fails (but I can put anything I want to the `/sh` and we run it)

**Comment by lucab** [comment]
@tixxdz I just re-run the test-suite on current systemd master, and the second regression also seems to be fixed. As per @evverx comment above, I think https://github.com/systemd/systemd/pull/4372 did it.

**Comment by tixxdz** [comment]
@lucab ah thanks , and thanks @evverx closing then.
