### ISSUE TITLE
journactl follow not working correctly on remote logs folder

### ISSUE THREAD

**Issue by Weihrauch** [systemd/systemd#4359]
### Submission type
- Bug report

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 229
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
> ### Used distribution
> 
> ubuntu 16.04
> ### In case of bug report: Expected behaviour you didn't see

I have configured journald remote service. On server where logs are uploaded I would like to follow log of all of my server.

> journalctl -f -D /var/log/remote
> ### In case of bug report: Unexpected behaviour you saw

Only logs of one hosts are shown. 
### In case of bug report: Steps to reproduce the problem

Make two hosts (A and B) upload their journald logs to another server C.
On C

> journalctl -f -D /var/log/remote
> On A
> logger testA
> On B
> logger testB
> You will see only testA or testB instead of both.

**Comment by poettering** [comment]
Please try this again with a current version of systemd. We generally only track issues with the two most recent systemd versions upstream, which are at this moment 230 and 231. As there have been many journal-related fixes since 229, this is particularly relevant.

Thank you for understanding.
