### ISSUE TITLE
Dependencies for hwdb/parse_hwdb.py

### ISSUE THREAD

**Issue by phomes** [systemd/systemd#4365]
### Submission type
- [ ] Bug report
- [ x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora 25

It would be nice to mention somewhere the dependencies for running parse_hwdb.py

On fedora I installed python3-pyparsing and previously also python-evdev from gvalkov's copr. The latter only has releases up to F24 though.

**Comment by keszybz** [comment]
Oops, indeed.
