### ISSUE TITLE
Please reconsider ConditionPathIsReadWrite in systemd-sysctl.service.in

### ISSUE THREAD

**Issue by zeha** [systemd/systemd#4370]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> HEAD, 215-17+deb8u5
### Used distribution

> Debian jessie in LXC container
### In case of bug report: Expected behaviour you didn't see

> net.\* sysctl be applied
### In case of bug report: Steps to reproduce the problem

LXC containers have /proc/sys mounted R/O. They /proc/sys/net mounted R/W.

units/systemd-sysctl.service.in has ConditionPathIsReadWrite=/proc/sys/

This prevents any net.\* sysctls from being applied in LXC containers, and more so, silently.

Please consider dropping the ConditionPathIsReadWrite again (has been introduced in f2a46f8da51aeab1a34dd250e8ac48f2465bf095)

**Comment by martinpitt** [comment]
This seems to be a "damned if you do, damned if you don't" case -- A lot of sysctls will actually fail because they cannot actually be applied in containers.

**Comment by zeha** [comment]
IIRC on Debian, there are no sysctls set by default. So any changes are either by the local admin or by packages - in any case, it's then useful to know they are not applied.

**Comment by poettering** [comment]
@keszybz hmm, how is this a regression?

**Comment by keszybz** [comment]
I misread the original bug report.

**Comment by zeha** [comment]
Not sure what the criteria are for regressions, but before f2a46f8 containers would get those sysctls applied...?

**Comment by poettering** [comment]
So I figure we can simply change the offending line to ConditionPathIsReadWrite=/proc/sys/net, right?

**Comment by poettering** [comment]
Fix waiting in #4425

**Comment by keszybz** [comment]
f2a46f8 is from 2012, so no, that's not a regression. By now it's a well established tradition ;)

**Comment by dawncold** [comment]
I found my Ubuntu 16.04.2 `/proc/sys` is `dr-x r-x r-x`, it works fine, but in lxc container, it doesn't work with `ConditionPathIsReadWrite=/proc/sys/ was not met`, `/proc/sys` is `dr-x r-x r-x`
