### ISSUE TITLE
Core dump crash when adding VTI interfaces with IPv6 addresses

### ISSUE THREAD

**Issue by halvors** [systemd/systemd#4371]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.10
### In case of bug report: Expected behaviour you didn't see

> ...
### In case of bug report: Unexpected behaviour you saw

> Core dump.
### In case of bug report: Steps to reproduce the problem

> Add VTI interface with IPv6 remote and local adresses.

**Comment by halvors** [comment]
When adding a VTI6 (Or just VTI for that matter) with IPv6 addreses on the Remote= and Local= fields. The whole systemd-networkd daemon crashes.

This is the device that crashes:

```
[NetDev]
Name=vti2
Kind=vti6

[Tunnel]
Local=2001:DB8:0:0:0:0:0:1
Remote=2001:DB8:0:0:0:0:0:2
Key=2
```

**Comment by halvors** [comment]
Messages i get in the log:

```
Oct 14 04:34:53 Router01 systemd[1]: Started Network Service.
Oct 14 04:34:53 Router01 systemd-networkd[5325]: Assertion 't' failed at ../src/network/networkd-netdev-tunnel.c:210,
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=6/ABRT
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Unit entered failed state.
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart.
Oct 14 04:34:54 Router01 systemd[1]: Stopped Network Service.
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Start request repeated too quickly.
Oct 14 04:34:54 Router01 systemd[1]: Failed to start Network Service.
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Unit entered failed state.
Oct 14 04:34:54 Router01 systemd[1]: systemd-networkd.service: Failed with result 'start-limit-hit'.
```

**Comment by halvors** [comment]
This is a IPv6 problem only, IPv4 works fine, so i'm sure it's a quick fix ;)

**Comment by halvors** [comment]
Please let me know if you need any more information on this matter.

**Comment by poettering** [comment]
@ssahani could you look into this one please?
