### ISSUE TITLE
do not install .busname units

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#4376]
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 231
> +PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

> Arch Linux (but with custom configure flags):

```
      --libexecdir=/usr/lib
      --localstatedir=/var
      --sysconfdir=/etc

      --enable-lz4
      --disable-gnuefi
      --disable-audit
      --disable-ima
      --disable-resolved
      --disable-selinux
      --disable-apparmor
      --disable-smack
      --disable-importd
      --disable-qrencode
      --disable-microhttpd
      --disable-quotacheck
      --disable-efi
      --disable-firstboot
      --disable-libiptc
      --disable-coredump
      --disable-hibernate
      --disable-nls
      --disable-utmp
      --disable-kdbus


      --with-sysvinit-path=
      --with-sysvrcnd-path=
      --with-ntp-servers="${timeservers[*]}"
      --with-dbuspolicydir=/usr/share/dbus-1/system.d
```
### Detailed Description

There's no manual (`systemd.busname`) documenting busname units. However, the `sd_bus_negotiate_fds` manual appears to refer to this missing manual.

Also, these units are shipped even if kdbus is disabled (which originally led me to believe that they were used by systemd's dbus integration).

**Comment by Stebalien** [comment]
Also, the `busname.target` unit claims that it's documented in `systemd.special` but it isn't.

**Comment by keszybz** [comment]
Busname units were added for kdbus. Kdbus has now been dropped. But there's a plan to reuse .busname units within systemd to provide our own support for dbus. When that happens, the documentation will be updated. Currently it's not possible.

**Comment by Stebalien** [comment]
Then in the meantime the existing units should probably not be installed by `make install`. Really, if they're only for kdbus, they should never be installed when `--disable-kdbus` is passed to `configure`. This obviously isn't exactly high priority but finding random undocumented files on one's system is kind of annoying.

**Comment by keszybz** [comment]
meson build does not install .busname units. So should be already fixed with v234 if you use the recommended installation method, and meson will probably be the only supported installation method in v235, so I'm treating this as fixed.
