### ISSUE TITLE
[resolved]: support for specifing a port for the dns-server like in dnsmasq

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4377]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231 +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux

I have at the moment the following setup:

dnscrypt-proxy listening on 127.0.0.1 Port 40
dnsmasq (DNS server) listening on 127.0.0.1 Port 53, who gets the result from dnscrypt-proxy

I would like to replace dnsmasq with systemd-resolved. Is there any way there I can specify the dns port in the resolved.conf? dnsmasq supports something like: 127.0.0.1#40 for specifing a destination port.
Moreover can systemd-resolved forward dnssec queries? I would get them via dnscrypt-proxy and from there to  systemd-resolved. 

Even better would be dnscrypt support in systemd-resolved, But I don't think there is chance due to it's not a accepted standard.. am I right?

**Comment by poettering** [comment]
dnscrypt support in resolved is indeed unlikely...

If you want to connect resolved to talk to a local dnscrypt proxy, I'd recommend making the proxy listen on 127.0.0.54:53 or so (i.e. use a different IP address from the 127.0.0.0/8 range rather than a different port nr). Wouldn't that suffice?

**Comment by shibumi** [comment]
@poettering Awesome Idea! Thanks for this. It's working with systemd-resolved now. I will close this issue.

**Comment by edward2a** [comment]
@poettering Why the decision to force port 53 for the target resolvers?

**Comment by drzraf** [comment]
This should be reopened.
[Many resolvers](https://www.privacytools.io/providers/dns/) use a different port, be it for firewall purposes or for providing different features (eg: ads hosts blacklisting).

**Comment by f0o** [comment]
I'm confused about this issue...

The Docs (https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNS=) state:
>[...] Each address can optionally take a port number separated with ":" [...]

However doing so results in:
```
Failed to add DNS server address '127.0.0.1:8600', ignoring: Invalid argument
```

And now stumbling across this recent comment (https://github.com/systemd/systemd/issues/4377#issuecomment-720217605) makes me believe that it's not actually fully implemented.

Or am I missing something?

systemd-version:
```
systemd 245 (237-12140-g29cb7c4+)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy
```

**Comment by NyaMisty** [comment]
> I'm confused about this issue...
> 
> The Docs (https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNS=) state:
> 
> > [...] Each address can optionally take a port number separated with ":" [...]
> 
> However doing so results in:
> 
> ```
> Failed to add DNS server address '127.0.0.1:8600', ignoring: Invalid argument
> ```
> 
> And now stumbling across this recent comment ([#4377 (comment)](https://github.com/systemd/systemd/issues/4377#issuecomment-720217605)) makes me believe that it's not actually fully implemented.
> 
> Or am I missing something?
> 
> systemd-version:
> 
> ```
> systemd 245 (237-12140-g29cb7c4+)
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy
> ```

Well that's because it's introduced in systemd 246 (see https://lwn.net/Articles/827675/):
```
       * systemd-resolved's DNS= configuration option now optionally accepts a
          port number (after ":") and a host name (after "#"). When the host
          name is specified, the DNS-over-TLS certificate is validated to match
          the specified hostname. Additionally, in case of IPv6 addresses, an
          interface may be specified (after "%").
```
