### ISSUE TITLE
systemd.resource-control manual page should be renamed

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4379]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.10
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> There are documented options for resource control in _systemd.exec_ too like **IOSchedulingClass**. Yes, I know **Control Groups** are mentioned in the manual page but still I find current name to be misleading. Maybe _systemd.cgroups-control_?

**Comment by keszybz** [comment]
Renaming a page is not free — that name has been used for a long while and certainly there are various references on the net to it, and people are accustomed to that name. And I don't think changing the name would really solve the problem. We can instead make it easier to go from on page to the other. I'll submit a PR to do that.

**Comment by lzbthlsn** [comment]
In the new systemd.resource-control, you added **systemd.slice** instead of **systemd.exec**.

**Comment by poettering** [comment]
It actually used to be called "systemd.cgroups". However, I am pretty sure "cgroups" is a low-level concept that users shouldn't really have to know about. I mean, it's fine mentioning the relationship _in_ the man page, but I doubt the man page should be named _after_ it.

**Comment by keszybz** [comment]
I doubt that there are many users of the API who do not know what cgroups are... So "systemd.cgroups" is probably a better name, succinct and clearly distinguishable from "systemd.exec". But the name is always a bit arbitrary, and stability is more important, hence I think current patch is OK.
