### ISSUE TITLE
The Wacom CTH-460 is not a joystick (likely applies to other tablets)

### ISSUE THREAD

**Issue by ShadowKyogre** [systemd/systemd#438]
The culprit code: https://github.com/systemd/systemd/blob/3a3701f03360f9a292dcab31fda1f6e0e0629c64/src/udev/udev-builtin-input_id.c#L183-L224

My attempt at fixing it with the udev rules generated with libwacom's `generate-udev-rules`:  https://gist.github.com/ShadowKyogre/3e3b4d347f71a97a1956#file-99-fix-wacom-really-rules-L138-L141

Here's the mailing list indicator indicating the issue with udev's joystick detection: http://sourceforge.net/p/linuxwacom/mailman/message/33349499/

Even though I tried forcing udev to say it's not a joystick despite this, it still refuses to treat it as not-a-joystick because it still shows up as `/dev/input/js${some_number}`

**Comment by ShadowKyogre** [comment]
https://gist.github.com/ShadowKyogre/3e3b4d347f71a97a1956#file-udev-my-tablet-is-not-a-joystick-txt Here's the output of `udevadm monitor -p`

**Comment by ShadowKyogre** [comment]
Did some more research and it turns out it's a kernel bug. I found this out by killing udev and noticing the phantom joystick was still being created: https://gist.github.com/denilsonsa/978f1d842cf5430f57f6

**Comment by dvdhrm** [comment]
I cannot follow, sorry. Can you describe the problem in more detail?

**Comment by ShadowKyogre** [comment]
@dvdhrm: So, what's going on is:
1. When I plug in the Wacom CTH-460, a joystick device (`/dev/input/js${num}`) for it is created
2. Also of note is that udev assigns ID_INPUT_JOYSTICK based on some things that aren't exclusive to controllers, like BTN_1 (as mentioned in the linuxwacom mailing list, I also double-checked the merged upstream code for the wacom drivers in the kernel). I don't think udev is contributing to it anymore because
3. I killed udev to check how the joystick device is created. The kernel creates it.
4. So, it looks like a symptom of a bug mentioned in [denilsonsa's gist](https://gist.github.com/denilsonsa/978f1d842cf5430f57f6) rather than udev, where the kernel would be happy to create a kernel device for something that's clearly not a joystick. Several other devices suffer from this kernel bug, but the only way to solve this on udev's end is to just make the node inaccessible. I hadn't realized it was a kernel bug until three days ago.

**Comment by dvdhrm** [comment]
Just because a joydev device is created doesn't necessarily mean that it is a joystick. Furthermore, the ID_INPUT_\* properties are just hints. We try to do our best, but user-space input drivers really need to double check, perform white/black-listing and so on.
As long as the wrong ID doesn't break any applications, I don't think it's worth fixing.

Closing this now. Feel free to re-open, if you think this should be fixed in udev.
