### ISSUE TITLE
resolve breaks under fakeroot

### ISSUE THREAD

**Issue by g2p** [systemd/systemd#4383]
### Submission type
- [✓] Bug report
### systemd version the issue has been seen with

> 213
### Used distribution

> Arch, Ubuntu 16.10
### Expected behaviour you didn't see

> Name resolution works
### Unexpected behaviour you saw

On Ubuntu and Arch

```
$ fakeroot systemd-resolve example.com
resolve call failed: Access denied
```

On Arch only:

```
$ fakeroot getent hosts bbuseruploads.s3.amazonaws.com
# No output
```

The Arch issue (using a recommended nsswitch configuration line):

```
hosts: files mymachines resolve
```

is vexing, because it breaks the Aura package manager (in -A mode for AUR support, and possibly other AUR managers too).

**Comment by poettering** [comment]
Well, first of all, please don't file bugs upstream about such old systemd versions, we only track bugs in the two most recent releases here. For everything else, please contact downstream packagers.

That said, "fakeroot" will fake uid credentials via LD_PRELOAD for the purpose of creating tarballs. The UID of a process running that way will be different from the OS kernel PoV (as the fakeroot effect doesn't apply there) than from the process' own PoV (where the fakeroot effect applies). Now, during D-Bus authentication the UID sent in the datagram payload is compared with the metadata about the connection as retrieved from the kernel. If they don't match, dbus-daemon will refuse the connection. And in this case they won't match, as the dbus client that is getent/systemd-resolve will send along fake data, that is necessarily out-of-sync with the actually used kernel credentials.

Or in other words: fakeroot is systematically incompatible with D-Bus, and should not be used with any dbus client.

**Comment by g2p** [comment]
Sorry, I meant 231 (the latest in Arch and Ubuntu).
There's still a getent issue that doesn't involve DBus, but I don't know if you can reproduce it (someone on IRC couldn't; system is a bog standard Arch in a VM).

**Comment by poettering** [comment]
nss-resolve internally uses dbus for communicating with systemd-resolved, hence nss-resolve will fail too. Now, NSS is by default configured to ignore errors of nss-resolve and proceed. That's what you are seeing most likely

**Comment by stefan-it** [comment]
On Arch Linux (with 231):

``` bash
[stefan@arch-64-glaukon ~]$ fakeroot getent hosts bbuseruploads.s3.amazonaws.com
54.231.121.43   s3-1-w.amazonaws.com bbuseruploads.s3.amazonaws.com s3-directional-w.amazonaws.com
```

Works for me...

**Comment by keszybz** [comment]
You most likely have dns in the hosts line in /etc/nsswitch.conf, so getent works.
