### ISSUE TITLE
MountFlags= documentation could use some love

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#4393]
We probably should rearrange systemd.exec(5) a bit, and add a separate section for fs namespacing options. 

See #4145 for background why this is probably a good idea.

**Comment by lucab** [comment]
A couple of related quirks I saw while navigating the code:
- if no other protection options are used, the direct way of setting up a as-plain-as-possible mount-ns seems to be setting `MountFlags=shared`, eg in [rkt apps](https://github.com/coreos/rkt/blob/v1.17.0/stage1/init/common/units.go#L354-L356).
- but using the option above together with `RootDirectory=`, the root mountpoint is turned to [slave propagation](https://github.com/systemd/systemd/blob/v231/src/core/namespace.c#L461-L466). This should be documented as well (and perhaps tweakable? A possible usecase is https://github.com/coreos/rkt/issues/3272).
- docs says that `MountFlags=` defaults to `shared`, but setting `MountFlags=shared` explicitly on a unit turns up side-effects such as the one above which are not default behavior. Looking at the code, the default seems to be a nil-flag, which is special-cased to `MS_SHARED` only [much later](https://github.com/systemd/systemd/blob/v231/src/core/namespace.c#L377-L378).

**Comment by poettering** [comment]
So, the man page has been reorganized a while back, implementing what was initially requested. However we should still document @lucab's findings properly, hence renaming the bug to that.

**Comment by keszybz** [comment]
This behaviour is so messy… I wonder how much we should document it, and how much we should try to make it less surprising before documenting.

**Comment by poettering** [comment]
@keszybz I am tempted to say: let's deprecate the whole option. Instead let's add "PrivateMounts=yes|no" or so. (following a similar naming as PrivateUsers= and PrivateNetwork=, which create a private user and network namespace). And this new option should probably open the namespace and mount everything to MS_SLAVE and the MS_SHARED right after. i.e. this would disconnect mount point and all mounts, but for everything further down we'll be MS_SHARED again.

In general, I think turning off propagation entirely and leaving it on entirely (i.e. just mount MS_PRIVATE or MS_SHARED once) makes very little sense, as turning off propagation means the namespace can keep mounts pinned and busy which is highly problematic, and MS_SHARED means no actual isolation takes place.

**Comment by poettering** [comment]
Working on a comprehensive fix for this one now

**Comment by poettering** [comment]
A comprehensive fix is waiting in #9153 now. PTAL
