### ISSUE TITLE
'Restart' property not available from systemd-run

### ISSUE THREAD

**Issue by rcurtin** [systemd/systemd#4402]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> ubuntu 16.10

I'd like to start a transient service that will automatically restart on failure.  The use case here is that I have an application which will fire up an unknown number of daemons periodically.  Transient services are perfect for this---I wait for the condition that requires me to launch a new daemon then I fire it off with `systemd-run`.

Ideally I would be able to run with

```
systemd-run --lots-of-options --property Restart=on-failure /some/daemon --and-its-options
```

but if I try to do that I get

```
Unknown assignment Restart=on-failure.
Failed to create bus message: Invalid argument
```

Is there a reason that `Restart` isn't a usable property?  I couldn't find any documentation about which properties were and weren't accessible for transient services.

Thanks for your time!

**Comment by poettering** [comment]
yeah, not all properties have been opened up for transient units yet. This is mostly because we didn't find the time to open this up yet, and yes, we should support this one too.

**Comment by rcurtin** [comment]
Thanks for the response.  If the support becomes available it will be very nice and I will definitely make use of it. :)

Maybe it would be better to close this ticket and instead create a "grand" ticket for all properties?  I searched for such a thing but I couldn't find anything.

I will see if I can find time to look into this to give a patch but it's probably highly unlikely that I'll be able to get this done anytime soon; I'm pretty busy right now---have to pet my cats and all.

**Comment by poettering** [comment]
well, if you leave this open, this helps us know which ones people care about... 

given that there are quite a number of properties not yet covered and it is unlikely that somebody will sit down any time soon adding support for every single one of them it's probably a good idea to leave this open...

**Comment by poettering** [comment]
Fix waiting in #4727

**Comment by rcurtin** [comment]
Thanks, I appreciate your time in fixing this.

**Comment by boucman** [comment]
v219 was tagged in febuary 2015, this was fixed in dec 2016.

Please upgrade to a recent systemd or open a centos-side bug to have the fix backported.
