### ISSUE TITLE
systemd.service(5) does not fully document dependencies implied by Sockets=

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#4410]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Arch Linux

Socket units listed in a service unit’s `Sockets=` directive gain `Wants=` and `After=` dependencies on those sockets:

``` c
// load-fragment.c, config_parse_service_sockets, line 1739 as of 0afc6d4
r = unit_add_two_dependencies_by_name(UNIT(s), UNIT_WANTS, UNIT_AFTER, k, NULL, true);
if (r < 0)
        log_syntax(unit, LOG_ERR, filename, line, r, "Failed to add dependency on %s, ignoring: %m", k);
```

The `Wants=` dependency is not documented in `systemd.service(5)`. The `After=` kinda is, with the following sentence in the Automatic Dependencies section:

> Socket activated service are automatically ordered after their activated .socket units via an automatic `After=` dependency.

However, I think it could be phrased better, since in the `Sockets=` case, it’s possible that the service pulls in the socket, which I wouldn’t call “socket activated”.

**Comment by poettering** [comment]
Of course, patches for cases like these (and any others, in fact) are greatly appreciated!

**Comment by lucaswerkmeister** [comment]
I wasn’t sure if I could find a good way to phrase the improved version myself, but I think I have something, so pull request imminent :)
