### ISSUE TITLE
systemd-cryptsetup v220 breaks non-LUKS devices with unspecified type

### ISSUE THREAD

**Issue by kevinoid** [systemd/systemd#442]
On a system running the Debian testing distribution, I recently upgraded the `systemd` package from 215-18 to 220-7.  The system now fails to open the swap device (/dev/sda7) on boot with the following message:

```
systemd-cryptsetup[23252]: crypt_load() failed on device /dev/sda7.
systemd-cryptsetup[23252]: Failed to activate: Invalid argument
```

The device is configured as a plain (non-LUKS) device using a keyfile with the following line in `/etc/cryptsetup`:

```
sda7_crypt /dev/sda7 /sda7_crypt.keyfile discard,hash=ripemd160
```

I tracked the issue down to a change in [commit 7376e83528 at line 408](https://github.com/systemd/systemd/commit/7376e83528#diff-c53043ff881b77c89dd35400b0d9a0ffR408) which now causes systemd-cryptsetup to fail rather than retry as plain for devices of unspecified type.  Since there is no mention of this change in [Bug 66396](https://bugs.freedesktop.org/show_bug.cgi?id=66396), I assume the change was inadvertent.  If the change was intentional, I would highly suggest documenting it as a breaking change for system administrators in the upgrade notes.

Thanks,
Kevin

**Comment by poettering** [comment]
Yeah. That change was not intended afaics. would be happy to take a patch that restores old behaviour on this one.

**Comment by sledges** [comment]
Seeing exactly the same behaviour, I wonder how come only two of us affected (not a common setup?), and google hasn't indexed "crypt_load() failed on device" to point to this issue, so spent whole evening yesterday trying to bring my laptop back up :) (by downgrading systemd for now :/) ArchLinux here

**Comment by sledges** [comment]
adding "plain," before "cipher=" to crypttab solves the problem, so this issue is only for backwards compatibility to avoid nasty surprises :)

**Comment by daryltucker** [comment]
The [Archlinux Wiki](https://wiki.archlinux.org/index.php/Dm-crypt/System_configuration#crypttab) mentions a workaround for this issue, for those looking.

**Comment by poettering** [comment]
Hmm, I hope it's OK if I close this now. This changed 5 years back, most likely everybody arranged for this by now, given this hasn't been coing up since. 

If anyone still cares, by all means, still happy to take a PR, but I think if noone cares the new status quo is as good as the old...
