### ISSUE TITLE
nspawn: Regression in user namespacing

### ISSUE THREAD

**Issue by s-urbaniak** [systemd/systemd#4421]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

master (https://github.com/systemd/systemd/commit/5368222db6093195dbbd5fc7418508b154b1b769)
### In case of bug report: Expected behaviour you didn't see

With systemd v231 user namespacing works.

```
$ systemctl --version
systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
$ sudo systemd-nspawn -U -D ~/tmp/debian-sid
Spawning container debian-sid on /home/sur/tmp/debian-sid.
Press ^] three times within 1s to kill container.
Selected user namespace base 1401094144 and range 65536.
root@debian-sid:~# 
```
### In case of bug report: Unexpected behaviour you saw

With systemd-nspawn in master user namespacing doesn't work.
### In case of bug report: Steps to reproduce the problem

```
$ sudo debootstrap --variant=minbase sid debian-sid http://httpredir.debian.org/debian
$ sudo ~/src/systemd/systemd-nspawn -U -D ~/tmp/debian-sid
Spawning container debian-sid on /home/sur/tmp/debian-sid.
Press ^] three times within 1s to kill container.
Child died too early.
Selected user namespace base 1401094144 and range 65536.
Failed to mount cgroup on /sys/fs/cgroup/net_cls (MS_NOSUID|MS_NODEV|MS_NOEXEC "net_cls"): No such file or directory
```

I discovered this while working on https://github.com/systemd/systemd/pull/4395. I did not dig deeper into this, but apparently some cgroup initialization fails.

/cc @lucab who had similar issues while working on another feature.

**Comment by evverx** [comment]
What is the output of the

```
cat /proc/version
```

on the host?

[`>= 4.8`](https://github.com/systemd/systemd/issues/4352)?

**Comment by s-urbaniak** [comment]
@evverx yes

```
$ cat /proc/version 
Linux version 4.8.2-1-userns (sur@t460s) (gcc version 6.2.1 20160830 (GCC) ) #1 SMP PREEMPT Wed Oct 19 11:56:59 CEST 2016

$ cat /etc/os-release 
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

This is the stock (Arch) Linux kernel (https://git.archlinux.org/svntogit/packages.git/tree/linux/trunk) with `USER_NS` enabled.

**Comment by s-urbaniak** [comment]
@evverx ahh, this is a duplicate then. I am closing this in favor of https://github.com/systemd/systemd/issues/4352.
