### ISSUE TITLE
systemd-udevd: Error changing net interface name to caused startup ubuntu os too slow

### ISSUE THREAD

**Issue by thorlin** [systemd/systemd#4423]
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

229 (package version 229-4 from ubuntuStretch/testing)
NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!
### Used distribution

Ubuntu Stretch/testing

My os is ubuntu 16.04.1 kernel version is 4.4.0.31,kernel startup will show this message to caused kernel  startup time to slow. 

76.733908] systemd-udevd[132]: seq 1476 '/devices/pci0000:00/0000:00:13.0/0000:01:00.0/net/eth0' is taking a long time
[  107.147576] systemd-udevd[135]: error changing net interface name 'eth0' to 'eno1': File exists
[  107.147596] systemd-udevd[135]: could not rename interface '2' from 'eth0' to 'eno1': File exists

use command :systemd-analyze 
Startup finished in 6.108s (firmware) + 4.523s (loader) + 2min 28.902s (kernel) + 2.176s (userspace) = 2min 41.711s

how can i fix this issue? Thanks

**Comment by poettering** [comment]
it appears some udev rule you have in place is taking overly long. Please work with your downstream distro to track this down, as the issue at hand is neither in the two most recently released versions of systemd (and we only track issues with those upstream), nor appears to be an issue in systemd at all, but much rather is an issue in your kernel driver or udev rules or such.

Thanks.
