### ISSUE TITLE
assertion failed in systemd-logind when passing it options leads to coredump

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#4431]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231, master

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> CentOS 7, Fedora 24
### In case of bug report: Expected behaviour you didn't see

> it shouldn't coredump
### In case of bug report: Unexpected behaviour you saw

> it fails an assetion and coredumps
### In case of bug report: Steps to reproduce the problem

```
sh-4.3# /usr/lib/systemd/systemd-logind --help
This program takes no arguments.
Assertion 'm' failed at src/login/logind.c:129, function manager_free(). Aborting.
Aborted (core dumped)
sh-4.3# 
```

**Comment by poettering** [comment]
fix waiting in #4433
