### ISSUE TITLE
systemd treats 0 byte unit files as masked

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#4436]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231, master

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> CentOS 7, Fedora 24
### In case of bug report: Expected behaviour you didn't see

> an error explaining that the unit file is empty or invalid
### In case of bug report: Unexpected behaviour you saw

> the unit is detected as masked
### In case of bug report: Steps to reproduce the problem

```
sh-4.3# touch /etc/systemd/system/foo.service
sh-4.3# systemctl is-enabled foo
masked
sh-4.3# systemctl start foo
Failed to start foo.service: Unit foo.service is masked.
sh-4.3# 
```

**Comment by mbiebl** [comment]
That's not a bug, that's by design. See the systemd.unit man page:

```
       If a unit file is empty (i.e. has the file size 0) or is symlinked to /dev/null, its configuration will not be
       loaded and it appears with a load state of "masked", and cannot be activated. Use this as an effective way to
       fully disable a unit, making it impossible to start it even manually.
```

**Comment by davide125** [comment]
I missed that, thanks. This behavior is a bit problematic for us, as 0 byte files are one of the effects of RPM corruption (in case e.g. of power loss in the middle of a package install) and this caused some reporting confusion, but we should be able to work around it.

**Comment by keszybz** [comment]
FWIW, I think this overloading was a bad idea — symlinking to `/dev/null` should have been the only option. And in fact that's what everybody uses exclusively from what I have seen. But it's too late to change this.
