### ISSUE TITLE
RFE: add --wait to systemd-mount

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#4437]
Akin to #3984 and #4098, add a `--wait` option to `systemd-mount` to block and wait for the created unit to finish.
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> master

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_

**Comment by poettering** [comment]
hmm, it already blocks until the mount point is established anyway. Are you suggesting that if --wait is specified it should also wait until the mount point is removed again? What's the usecase for that? Not following?

**Comment by davide125** [comment]
Oh you're right of course, I remembered testing this a while ago and it didn't seem to block but it definitely is now. Nothing to see here then, move along :)
