### ISSUE TITLE
mounting over /sys/fs/cgroup breaks systemctl status (and probably other stuff)

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#4439]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231, master

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> CentOS 7, Fedora 24
### In case of bug report: Expected behaviour you didn't see

> `systemctl status` and other tools should continue to work (and/or print a warning)
### In case of bug report: Unexpected behaviour you saw

> `systemctl status` returns bogus information
### In case of bug report: Steps to reproduce the problem

```
sh-4.3# systemctl status
● image.raw
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Thu 2016-10-20 17:48:39 PDT; 16min ago
   CGroup: /machine.slice/machine-image.raw.scope
           ├─init.scope
           │ └─1 /usr/lib/systemd/systemd
           ├─system.slice
           │ ├─dbus.service
           │ │ └─23 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopi
dfile --systemd-activation
           │ ├─systemd-journald.service
           │ │ └─14 /usr/lib/systemd/systemd-journald
           │ ├─systemd-resolved.service
           │ │ └─24 /usr/lib/systemd/systemd-resolved
           │ ├─systemd-logind.service
           │ │ └─22 /usr/lib/systemd/systemd-logind
           │ └─console-getty.service
           │   └─26 /sbin/agetty --noclear --keep-baud console 115200,38400,9600 xt
erm
           └─user.slice
             └─user-0.slice
               ├─user@0.service
               │ ├─foo.service
               │ │ └─146 /bin/yes
               │ └─init.scope
               │   ├─141 /usr/lib/systemd/systemd --user
               │   └─142 (sd-pam)
               └─session-518537.scope
                 ├─140 -bin/sh
                 ├─147 (sd-
                 ├─164 systemctl status
                 └─165 more
sh-4.3# mount -t tmpfs foo /sys/fs/cgroup
sh-4.3# systemctl status
● image.raw
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Thu 2016-10-20 17:48:39 PDT; 16min ago
   CGroup: /machine.slice/machine-image.raw.scope
sh-4.3# systemd-cgls
Failed to get root control group path: No such file or directory
sh-4.3# systemd-cgtop
Failed to determine supported controllers: No such file or directory
sh-4.3# 
```

**Comment by mbiebl** [comment]
You're deliberately breaking systemd by mount stuff over /sys/fs/cgroup.
It's a bit like deleting a library a binary depends on. It's no surprise that the result is non-functional.

**Comment by davide125** [comment]
fwiw, what prompted reporting this is actually a non-malicious usecase we hit in production -- we had an internal daemon that would unconditionally attempt to mount the cgroups (v1) hierarchy on /sys/fs/cgroup, even when v2 was enabled and systemd was using it. I think in this case having at least `systemctl status` print a warning would be nice, but agreed that we likely shouldn't worry about deliberate breakage.
