### ISSUE TITLE
systemd-nspawn -U seems incompatible with invocation IDs

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#4441]
With v231-727-gd9b8ea5448, booting in a container with `systemd-nspawn --network-veth --private-users=pick -M … -b` yields the following:

```
Oct 20 23:27:29 systemd[1]: systemd-networkd.service: Failed to set invocation ID on control group /system.slice/systemd-networkd.service, ignoring: Operation not permitted
Oct 20 23:27:29 systemd[1]: systemd-logind.service: Failed to set invocation ID on control group /system.slice/systemd-logind.service, ignoring: Operation not permitted
…
```

and similarly for all other services.

**Comment by poettering** [comment]
urks, just urks... how ugly... not sure what a nice fix for that could be...

**Comment by man-FIRE** [comment]
what is  invocation ID  ? whyy the system do that ?

**Comment by evverx** [comment]
@man-FIRE , [core: add "invocation ID" concept to service manager](https://github.com/systemd/systemd/commit/4b58153dd22172d817055d2a09a0cdf3f4bd9db3)

BTW: I guess the mailing list https://lists.freedesktop.org/mailman/listinfo/systemd-devel is the better place to ask questions

**Comment by man-FIRE** [comment]
thx you so much for your fast respond the problem is i have a production more 100 server with this error after a "stupid update to sid debian" I just want to know to stop it , it just log ? can be dangerous? more 48 hours of investigation and I found nothing :\

**Comment by man-FIRE** [comment]
Status: "Processing requests..."
   CGroup: /system.slice/systemd-logind.service
           └─437 /lib/systemd/systemd-logind
create session non stop ??

**Comment by georgyo** [comment]
Started running into this problem with Fedora 26 container starting pki-tomcat. Both the host (archlinux) and the container are running systemd version 233, kernel 4.9.36.

I turned off user namespacing for these IPA containers,and things are working now. However as -U is part of the default systemd-nspawn config now, this should get looked at. If more services try to get their invocation IDs, this is going to get painful.

**Comment by poettering** [comment]
Fix waiting in #7246

**Comment by evverx** [comment]
@poettering, now that #7246 has been merged, would it make any sense to downgrade the log level of the "`Failed to set invocation ID`" error messages to `debug`? They seem to be a little intimidating.

**Comment by poettering** [comment]
@evverx sure absolutely. please post a PR!

**Comment by evverx** [comment]
I've just posted https://github.com/systemd/systemd/pull/7422.
