### ISSUE TITLE
Assertion 's->type == SERVICE_ONESHOT' failed at ../systemd-229/src/core/service.c:1727, function service_enter_start(). Aborting

### ISSUE THREAD

**Issue by hkjn** [systemd/systemd#4444]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

```
systemd 229
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```
### Used distribution

CoreOS stable:

```
# cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.3.0
VERSION_ID=1122.3.0
BUILD_ID=2016-10-20-2045
PRETTY_NAME="CoreOS 1122.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### In case of bug report: Expected behaviour you didn't see

No issues with systemd services.
### In case of bug report: Unexpected behaviour you saw

Failed assertion, followed by unresponsive systemd:

```
# journalctl --all -f
systemd[1]: Assertion 's->type == SERVICE_ONESHOT' failed at ../systemd-229/src/core/service.c:1727, function service_enter_start(). Aborting.

# systemctl status sshd
[.. time passes .. ]
Failed to get properties: Connection timed out
#
# systemctl cat sshd
[.. time passes .. ]
Failed to get FragmentPath: Connection timed out

# systemctl
[.. time passes .. ]
Failed to list units: Connection timed out
```

There were no other systemd log output that I could find indicating what led to the issue was. Speculating, it could potentially be unusual interaction (e.g. race condition) with CoreOS folks `fleet`, which writes `.service` files and otherwise interacts with systemd.
### In case of bug report: Steps to reproduce the problem

I can't repro yet, only got one node into this state. I'll try switching to Beta or Alpha channel of CoreOS in case there's different systemd versions there.

**Comment by poettering** [comment]
Fix waiting in #4447.
