### ISSUE TITLE
Allow all control characters in env vars set via SetEnvironment on the bus API

### ISSUE THREAD

**Issue by AeliusSaionji** [systemd/systemd#4446]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

Archlinux
### In case of bug report: Steps to reproduce the problem

$ dbus-update-activation-environment --systemd --all
`dbus-update-activation-environment: warning: error sending to systemd: org.freedesktop.DBus.Error.InvalidArgs: Invalid environment assignments`

$ busctl monitor --user
http://sprunge.us/cNWK

A number of these variables are being set by grml-zsh-config http://grml.org/zsh/#grmlzshconfig

**Comment by poettering** [comment]
I am sorry, but this sounds like an utterly unconvincing request. Your tool "grml-zsh-config" appears pretty broken if it wants to stash control chars in an env var. Sure, UNIX makes no restrictions there, but I am pretty sure that's a mistake, and systemd should not permit that... Sorry.

**Comment by grawity** [comment]
@poettering That doesn't sound like a good argument, since [the validation function](https://github.com/systemd/systemd/blob/master/src/basic/env-util.c#L87) literally says "we allow `\t` because bash allows that". Well, bash allows `\e` and everything else too, so shouldn't systemd allow it as well?

It's specifically `\e` that is being blocked here, and it's not that uncommon really – I happen to use it in $LESS_TERMCAP_foo, $MANLESS, $SUDO_PROMPT myself.

(The other control characters are really rare, though. Well, my $MANLESS has `\a` as part of the "set terminal title" seq, but I could easily replace it with `\e\\` if I had to.)

**Comment by poettering** [comment]
allowing to embed escape codes in env vars sounds very wrong to me, i am sorry. I mean, there are some control codes that are safer than others (tab for example is pretty safe I'd argue), but ESC is certainly the worst of all...

**Comment by adrelanos** [comment]
@poettering:

> In the light of the "shellshock" vulnerability and things, I am still not convinced permitting such complex env vars to be pushed into systemd is a good idea...

What about a `--force` parameter relaxing these checks?

**Comment by edgar-bonet** [comment]
@poettering:
> allowing to embed escape codes in env vars sounds very wrong to me

This is your personal opinion and I very much respect it. You should not, however, _impose this as a rule_ to all systemd users.

You will not prevent people from doing it anyway: this is just forcing them to move their env settings from .profile to .bashrc. It's nothing more than a pointless annoyance.

**Comment by gnarendran** [comment]
[Ref: Environment variables with control characters vanished.](https://gitlab.gnome.org/GNOME/gnome-session/issues/45) 

Control sequences in environment variables have been in use for long, for example in less's LESS_TERMCAP_*= configuration. Disallowing them in systemd makes the environment of terminal shell under GNOME/systemd, different from that of a console login shell.

If systemd's restriction on the environment is here to stay, kindly document it prominently (say man environment.d) to avoid surprises to the user, and to let the user make workarounds. Regards.

**Comment by gnarendran** [comment]
[Environment variables with control characters vanished.](https://gitlab.gnome.org/GNOME/gnome-session/issues/45)

Control sequences in environment variables have been in use for long, for example in less's LESS_TERMCAP_*= variables. Disallowing them in systemd makes the environment of a terminal shell in GNOME+systemd different from the unrestricted console login shell.

If the restriction on environment variables in systemd is here to stay, kindly document it prominently (say in environment.d) to avoid surprises to the user and to let the user make workarounds. Regards.
