### ISSUE TITLE
systemd-nspawn "global" locks will not reliably detect device/inode number if image path is a root dir shared via NFS

### ISSUE THREAD

**Issue by syndtr** [systemd/systemd#4457]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> systemd-nspawn should be able to start correctly.
### In case of bug report: Unexpected behaviour you saw

> systemd-nspawn reports that resource is currently busy.
### In case of bug report: Steps to reproduce the problem

> Most filesystems(if not all?) use fixed inode number for its root, combined with NFS which shares same device number, entirely different mount points would have same device/inode number. This also apply to btrfs subvol shared via NFS.

**Comment by poettering** [comment]
Not sure what you are saying? we only use device/inode numbers in a local context? and each nfs will get a different device id exposes in stat(). 

Really not sure what you are saying?

**Comment by syndtr** [comment]
~~This turns out due to `no_subtree_check`.~~ And nfs4 does seem to share device id when mounting non-explicitly exported subdir. Sorry for the noise :)

```
/nfs                    10.0.0.0/20(rw,async,fsid=root,no_subtree_check)
/nfs/test               10.0.0.0/20(rw,async,no_subtree_check,no_root_squash)

10.0.4.1:/test/vol1 on /mnt/export_vol1 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.0.1.1,local_lock=none,addr=10.0.4.1)
10.0.4.1:/test/vol2 on /mnt/export_vol2 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.0.1.1,local_lock=none,addr=10.0.4.1)
10.0.4.1:/test on /mnt/export type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.0.1.1,local_lock=none,addr=10.0.4.1)

  File: 'export'
  Size: 16          Blocks: 0          IO Block: 32768  directory
Device: 47h/71d Inode: 256         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-24 17:46:28.666601840 +0700
Modify: 2016-10-24 17:45:27.950958371 +0700
Change: 2016-10-24 17:45:27.950958371 +0700
 Birth: -
  File: 'export_vol1'
  Size: 0           Blocks: 0          IO Block: 32768  directory
Device: 47h/71d Inode: 256         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-24 17:51:13.631704114 +0700
Modify: 2016-10-24 17:46:52.164011928 +0700
Change: 2016-10-24 17:46:52.164011928 +0700
 Birth: -
  File: 'export_vol2'
  Size: 0           Blocks: 0          IO Block: 32768  directory
Device: 47h/71d Inode: 256         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-24 18:05:00.061318520 +0700
Modify: 2016-10-24 17:46:53.780108911 +0700
Change: 2016-10-24 17:46:53.780108911 +0700
 Birth: -

  File: 'export/vol1'
  Size: 0           Blocks: 0          IO Block: 32768  directory
Device: 47h/71d Inode: 256         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-24 17:51:13.631704114 +0700
Modify: 2016-10-24 17:46:52.164011928 +0700
Change: 2016-10-24 17:46:52.164011928 +0700
 Birth: -
  File: 'export/vol2'
  Size: 0           Blocks: 0          IO Block: 32768  directory
Device: 47h/71d Inode: 256         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-24 18:05:00.061318520 +0700
Modify: 2016-10-24 17:46:53.780108911 +0700
Change: 2016-10-24 17:46:53.780108911 +0700
 Birth: -
```

EDIT: I was wrong about `no_subtree_check`. So nfs just pass inode number to the client, for example if two/more sub-directories are btrfs subvols (all btrfs subvol root dir has inode id 256), those two/more directories will have same inode id and since they are in the same nfs mount they would also shares device id.

**Comment by poettering** [comment]
Well, so let me get this right: nfs4 exposes the very same st_dev _and_ st_info for two local, completely unrelated mounts? That sounds seriously borked in the file system, no?

I mean, if it at least would report a dev_t of 0 or -1 or so,

**Comment by syndtr** [comment]
> Well, so let me get this right: nfs4 exposes the very same st_dev and st_info for two local, completely unrelated mounts?

Only if the directory is two different btrfs subvol root shares same block device.
Forget about nfs4 and two different mount. What I need is to be able to use multiple btrfs subvol as nspawn rootdir shared via nfs on a single nfs mount, I don't want to define and mount nfs exports of each subvol. Maybe add ability to disable locking?

**Comment by poettering** [comment]
well, btrfs actually changes the st_dev for each subvol you create, hence everything works correctly. As it appears nfs shouldn't permit exposing multiple subvols via the same nfs share, as then the inodes end up being reused... I doubt there's anything to fix here in nspawn, this sounds like something to fix in nfs when used in conjunction with btrfs...

I'd be fine with adding some special (undocumented) env var to nspawn that permits disabling locking, to work around issues like this. Patch welcome for that. But quite frankly this appears like borkage in the nfs implementation, they should really treat each subvol superblock exposed by a fs as a different mount and not expose it to clients as one.

**Comment by poettering** [comment]
An RFE for such an env var is already tracked in #4037.

**Comment by poettering** [comment]
I am closing this one, as I doubt we should fix anything in nspawn here, except add a hack via env var to overriding locking if you have borked st_dev/st_ino semantics on your fs.

**Comment by syndtr** [comment]
Fair enough. Thanks!
