### ISSUE TITLE
[resolved] Wrong statistics with systemd-resolve --statistics

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4461]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux

This is my `systemd-resolve --statistics`-Output:

```
DNSSEC supported by current servers: no

Transactions
Current Transactions: 0
  Total Transactions: 1187

Cache
  Current Cache Size: 0
          Cache Hits: 0
        Cache Misses: 3718

DNSSEC Verdicts
              Secure: 746
            Insecure: 760
               Bogus: 9
       Indeterminate: 0
```

As you can see I have over 3700 Cache Misses.

My `/etc/systemd/resolved.conf` looks like this;

```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
DNS=127.0.0.54
FallbackDNS=127.0.0.54
#Domains=
#LLMNR=yes
DNSSEC=allow-downgrade
Cache=yes
```

My `/etc/resolv.conf`:

```
# This file is managed by systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known DNS servers.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.54
nameserver 127.0.0.1
```

**127.0.0.54** is a dnscrypt-proxy.

My Questions are:
- Why does `systemd-resolve --statistics` shows that my dns-server would not support dnssec, although I have statistics about dnssec and this dnssec test shows everything is fine: https://dnssec.vs.uni-due.de/ . Moreover when I do `systemd-resolve www.fedoraproject.org` I see the following output:

```
www.fedoraproject.org: 140.211.169.196
                       140.211.169.206
                       152.19.134.142
                       152.19.134.198
                       174.141.234.172
                       185.141.165.254
                       209.132.181.15
                       209.132.181.16
                       67.219.144.68
                       (wildcard.fedoraproject.org)

-- Information acquired via protocol DNS in 771.3ms.
-- Data is authenticated: yes
```

This means that dnssec is running. Seems like `--statistics` is wrong.
- Why does systemd-resolved not cache?
- Why do I have two nameserver in my resolv.conf? There should be only 127.0.0.1 or am I wrong? The dns traffic should go over systemd-resolved thats running on port 127.0.0.1:53 to 127.0.0.54:53 and then to my dnscrypt-resolver..
- How can I make sure that the dns traffic runs first over systemd-resolved and then over my dnscrypt-proxy? At the moment it looks like it runs directly over the dnscrypt-proxy..
- When I try to resolve a hostname via `hostip -r 127.0.0.1 <testdomain>` the request times out..

**Comment by poettering** [comment]
systemd-resolved won't cache if the DNS server is on a localhost IP address. This is documented in resolved.conf, see Cache= there. The assumption is that if you have a local DNS server running and you redirect resolved to it there's no point in caching twice.

Can you provide the "systemd-resolve --status" output, please?

**Comment by wlhlm** [comment]
I have a similar setup where dnscrypt-proxy is running locally. I can see the problem of potentially having double caching, but I'd like to be able to explicitly enable caching ("I know what I'm doing"). Currently, there is no way to do that (except for ditching resolved entirely).

What is the reason behind implicitly disabling it? I would assume that a distro would catch the double caching in case they decide to run a resolver on localhost by default, and if a user explicitly installs a resolver they would have to change the settings in `resolved.conf` anyway and one could assume they are aware of the caching issue.

**Comment by shibumi** [comment]
@poettering I understand. The problem here is that the dnscrypt-proxy has no caching. So I thought that I could use the caching of systemd-resolved. 

This is my  `systemd-resolve --status`:

```
Global
         DNS Servers: 127.0.0.54
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 4 (ve-work)
      Current Scopes: LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: allow-downgrade
    DNSSEC supported: yes

Link 3 (wlp3s0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: allow-downgrade
    DNSSEC supported: no
         DNS Servers: 127.0.0.1

Link 2 (enp0s25)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: allow-downgrade
    DNSSEC supported: yes
         DNS Servers: 127.0.0.1
```

Funny.. Why is DNSSEC unsupported for wlp3s0 although I have the same DNS-Server as for enp0s25?

@wlhlm 
I Agree. It would be nice to have systemd-resolved caching even for local dns-servers. Otherwise I would need to disable systemd-resolved again and go with dnsmasq..

**Comment by poettering** [comment]
> Funny.. Why is DNSSEC unsupported for wlp3s0 although I have the same DNS-Server as for enp0s25?

we assume DNSSEC support is available until proved otherwise. Since your link 2 is apparently not up (it has not "Scopes" attached, which is a concept existing on an interface as long as an interface is up and running), we thus will assume DNSSEC support was available there still

**Comment by poettering** [comment]
> Why do I have two nameserver in my resolv.conf? There should be only 127.0.0.1 or am I wrong? The dns traffic should go over systemd-resolved thats running on port 127.0.0.1:53 to 127.0.0.54:53 and then to my dnscrypt-resolver..

The --status output shows that you have global config for 127.0.0.54 but interface-local config for 127.0.0.1. When writing out resolv.conf we'll merge the global config with all local configs, thus you get both in the file.

**Comment by shibumi** [comment]
Mhh Ok I understand. What about enabling caching for local dns servers? Would it be a RFE worth?

**Comment by shibumi** [comment]
@wlhlm 
I found a solution. Seems like resolved doesn't prase the loopback device. You can add some garbage address like `192.168.53.53` to the loopback device and bind your dnscrypt-proxy to this address. Therefore you can use systemd-resolved's caching with a local dns server. It's a really dirty hack. I would prefer if we could excplicit enable caching for a local dns resolver. For a persistent bind you can use a `lo.network` file with:

```
[Match]
Name=lo

[Network]
Address=192.168.53.53/32
```

I will close this issue. My first question about `systemd-resolve --statistics` is clear now.
