### ISSUE TITLE
[networkd] networkd does not verify dns ip address

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4462]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### How to reproduce:

Set an invalid DNS-Server in `/etc/systemd/network/wlp3s0.network`:

I get a invalid IP-Address for DNS-Server in the output `networkctl status wlp3s0`:

```
● 2: wlp3s0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/wlp3s0.network
            Type: wlan
           State: routable (configured)
            Path: pci-0000:03:00.0
          Driver: iwlwifi
          Vendor: Intel Corporation
           Model: Centrino Advanced-N 6205 [Taylor Peak] (Centrino Advanced-N 6205 AGN)
      HW Address: XXXXXXXXXX (Intel Corporate)
         Address: 192.168.2.103
                  XXXXXXXXXXX
         Gateway: 192.168.2.1 (Arcadyan Technology Corporation)
             DNS: 127.0.0.5553
```

DNS: 127.0.0.5553 is an invalid IP-Address.

Shouldn't systemd-networkd or systemd-resolved verify the IP address format? I wonder what else I could specify there..

HINT: It's also working with stuff like: " THIS IS A TEST" or "OK.I.WONDER.THAT.THIS.WORKS.AAAAAAAAAAAAAAAAAAAAA"

**Comment by poettering** [comment]
what precisely did you specify in your .network file?

**Comment by shibumi** [comment]
My .network file looks for example like this:

```
[Match]
Name=wlp3s0

[Network]
DHCP=ipv4
DNS=THIS.IS.AN.INVALID.IP.ADDRESS

[DHCP]
UseDNS=no
```
