### ISSUE TITLE
networkd: handle MTU field in IPv6 RA

### ISSUE THREAD

**Issue by Waldteufel** [systemd/systemd#4464]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### Suggested Enhancement

If you put a custom MTU (1280 in this example) in your router advertisements (e.g., with AdvLinkMTU in radvd.conf), the following happens…

This is the routing table generated by _disabling_ systemd-networkd and letting the kernel handle router advertisements – the custom MTU announced by the router is put into the routing table:

> [redacted]/64 dev wl0 proto kernel metric 256  expires 86396sec **mtu 1280** pref medium
> fe80::/64 dev wl0 proto kernel metric 256  **mtu 1280** pref medium
> default via fe80::[redacted] dev wl0 proto ra metric 1024  expires 1796sec **mtu 1280** hoplimit 64 pref medium

With systemd-networkd handling the router advertisements, the routing table looks like this – the custom MTU is missing. This can cause various issues when other network components down the route expect the client to already know the lower MTU – which apparently happens with some DSL providers.

> [redacted]/64 dev wl0 proto ra metric 1024  pref medium
> fe80::/64 dev wl0 proto kernel metric 256  pref medium
> default via fe80::[redacted] dev wl0 proto ra metric 1024  pref medium

The option is parsed in [ndisc_router_parse](https://github.com/systemd/systemd/blob/4e5a239fb86149ff8f370dbe99430e3244bfad44/src/libsystemd-network/ndisc-router.c#L202), but is not used in [ndisc_router_handler and its subroutines](https://github.com/systemd/systemd/blob/4e5a239fb86149ff8f370dbe99430e3244bfad44/src/network/networkd-ndisc.c#L561).
As far as I understand, it should be passed to the kernel via an [RTA_METRICS](https://github.com/systemd/systemd/blob/4e5a239fb86149ff8f370dbe99430e3244bfad44/src/libsystemd/sd-netlink/netlink-types.c#L512)/RTAX_MTU attribute when creating the respective routes.

**Comment by poettering** [comment]
Fixes by #4719.
