### ISSUE TITLE
systemd-resolved appends interface index for globally routeable addresses

### ISSUE THREAD

**Issue by akarl10** [systemd/systemd#4465]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> ubuntu 16.10
### In case of bug report: Unexpected behaviour you saw

> systemd-resolved appends the interface index on ipv6 addresses even for globally routeable addresses (i.e. 2001:db8::2%3 instead of 2001:db8::2)
> This is useful for interface local addresses but breakes for example nfs4 kerberos mounts since reverse dns resolutions does not work with this addresses
### In case of bug report: Steps to reproduce the problem

> put resolve in nsswitch

**Comment by poettering** [comment]
hmm? where do we append that? can you explain where precisely you see the suffix added? and what commands we have to type in to see the effect?

**Comment by akarl10** [comment]
I see this for example when ssh to a host (it asks me to trust ipv6%interfaceindex instead of ipv6)
Another case where i have problems is when mount a nfs by hostname: here it seams to see ipv6%interfaceindex somewhere. As nfs4 does a reverse dns lookup to get the kerberos service principal this the mount fails

looking at the code I thing it could be in _nss_resolve_gethostbyname4_r
r_tuple->scopeid = ifindex;

**Comment by poettering** [comment]
hmm, not sure i follow. Are you saying nfs4 can't deal with the iface index in the sockaddr_in6 structure set?

If so, it would be incompatible with link-local IPv6 addresses. Shouldn't this be fixed in nfs4?

**Comment by akarl10** [comment]
nfs handles the ifindex. Non kerberized nfs works, but kerberized nfs always needs a way to reverse lookup the ip address to a host. If nss returns a something that can be converted to a valid
`nfs/<returned string>@REALM`, the mount should work, else it will fail. Currently somehow it tries to reverse lookup 2001:db8::2%2 and fails doing so.

sure, if every application could handle the presence of the ifindex setting it whould be a plus.
The problem is that currently it breaks ubuntu 16.10 using resolve in nsswitch.
For now I am forced to disable resolve in nsswitch after every upgrade (I use ipv6 addresses)

In the ssh case I think it would be nice if ssh would ignore the ifindex for host key matching

**Comment by poettering** [comment]
Why does it fail to reverse lookup "2001:db8::2%2" for you? Does the reverse lookup work on "getent hosts" for you?

**Comment by akarl10** [comment]
no, it does not work.

`/etc/nsswitch:`
`hosts:          files resolve dns`

`ip a`
`2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000`
`link/ether 54:ee:75:52:59:34 brd ff:ff:ff:ff:ff:ff`
`inet 172.1.2.3/16 brd 172.27.255.255 scope global eth0`
`valid_lft forever preferred_lft forever`
`inet6 2001:db8::24fc:3e10:d69b:7eef/64 scope global temporary dynamic`
`valid_lft 86235sec preferred_lft 14235sec`
`inet6 2001:db8::5/64 scope global mngtmpaddr noprefixroute dynamic`

`getent hosts 2a00:1450:4006:803::2004`
`2a00:1450:4006:803::2004 mrs04s09-in-x04.1e100.net`

`getent hosts 2a00:1450:4006:803::2004%2`
`2a00:1450:4006:803::2004 2a00:1450:4006:803::2004`

*the local ip addresses here in `ip a` are replaced, but both ipv6 and ipv4 internet connections are working

**Comment by poettering** [comment]
hmm, if "getent hosts" also fails like this we really should fix this indeed.

**Comment by akarl10** [comment]
I see this for example when ssh to a host (it asks me to trust 
ipv6%interfaceindex instead of ipv6)
Another case where i have problems is when mount a nfs by 
hostname: here it seams to see ipv6%interfaceindex somewhere. 
As nfs4 does a reverse dns lookup to get the kerberos service 
principal this the mount fails

looking at the code I thing it could be in 
_nss_resolve_gethostbyname4_r
r_tuple->scopeid = ifindex;

**Comment by poettering** [comment]
Fix waiting in #5276.
