### ISSUE TITLE
Journal follow silently fails if it can't set up an inotify watch

### ISSUE THREAD

**Issue by Bob131** [systemd/systemd#4479]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

`systemd-231-10.fc25.x86_64`
### Used distribution

Fedora 25 Beta
### Expected behaviour you didn't see

`journalctl -f` tells me that it can't follow due to inotify watch exhaustion
### Unexpected behaviour you saw

`journalctl -f` sits idle, almost as though it had hung
### Steps to reproduce the problem
1. Start tracker
2. Run `journalctl -f`

This problem had me very confused for a couple of months. It'd be great if journalctl would let the user know if it can't follow, rather than just sitting idle. Thanks.

**Comment by fsateler** [comment]
duplicate of #1296?

**Comment by Bob131** [comment]
Oh, so it is. Sorry, I have trouble making GitHub's issue search thing go, I couldn't find a dup.
