### ISSUE TITLE
[networkd] support setting dhcp client listen port

### ISSUE THREAD

**Issue by jackmitch** [systemd/systemd#4482]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

Allow setting custom port for the DHCP client to listen on in networkd.

/\* Default */
[DHCP]
ListenPort=67

/\* Custom */
[DHCP]
ListenPort=6677

**Comment by poettering** [comment]
what's the usecase for this?

**Comment by jackmitch** [comment]
DHCP servers on non-standard ports. My reasoning is for a custom product which shouldn't register with the consumers DHCP server. However in a more contrived example I could imagine custom DHCP ports being used to segregate containers into address spaces.

**Comment by poettering** [comment]
what's the purpose of that? I mean, dhcp is about auto-configuration. By changing the port you require client side configuration, defeating the whole concept...

**Comment by jackmitch** [comment]
Added a bit more context above.

**Comment by poettering** [comment]
for your containers case a VLAN-based concept or so might be a better choice, or even independent networks altogether...

But yeah, I accept the custom product usecase

**Comment by ssahani** [comment]
As the RFE merged let's close it .
