### ISSUE TITLE
System boots only once every 3-4 attempts unless quota.service is masked

### ISSUE THREAD

**Issue by sergiocallegari** [systemd/systemd#4486]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.10 (yakkety)
### In case of bug report: Expected behaviour you didn't see

> System boots reliably
### In case of bug report: Unexpected behaviour you saw

> Only 1 boot every ~4 attempts succeeds. In all the other cases the units corresponding to the fstab devices timeout and fail. The system is then dropped in an emergency prompt.
### In case of bug report: Steps to reproduce the problem

> Boot the system.

The architecture of the machine where the issue occurs may be relevant. This is a system with
- 2 rotating disks managed via an intel fake raid in raid1. Intel fake raid is managed by mdadm that now supports the intel metadata.
- 1 ssd
- one partition of the ssd is /boot. Another partition of the ssd is swap. The rest of the ssd is a physical volume for lvm2. Root is in here as a logical volume. Opt is also here as another logical volume.
- One partition of the raid is another lvm2 physical volume in another volume group. Homes are here.

This looks very much like a race somewhere, because when the machine succeeds in booting everything is fine, but most of the time the boot fails.

It is also a regression. Ubuntu 16.04 with systemd 229 used to boot reliably. The issue appeared on an upgrade from 16.04 to 16.10.

**Comment by sergiocallegari** [comment]
Is the info above sufficient? What can I do to help debugging the issue?

**Comment by sergiocallegari** [comment]
Here is the journal

[journal.txt](https://github.com/systemd/systemd/files/552729/journal.txt)

Interesting bits are the sigterm to plymouthd as well as the timeouts in finding the fstab devices,
e.g.

dev-disk-by\x2dlabel-BOOT.device: Job dev-disk-by\x2dlabel-BOOT.device/start timed out

Interestingly:

1) This happens either on all the fstab devices (when boot fails) or on none (when it succeeds), but commenting out the fstab entries related to the slow device (the lvm logical drives on raid), the boot success ratio seems to improve. When things fail, the swap is not activated either...

2) When systemd drops to the emergency prompt all the local devices that could not be mounted are there, alive and mountable

**Comment by sergiocallegari** [comment]
Please disregard the last part of point 2 in my previous comment. It was my mistake. It should have read
2) When systemd drops to the emergency prompt all the local devices that could not be mounted are there, alive and mountable.

**Comment by sergiocallegari** [comment]
Masking quota.service aka the initial quota check seems to make the system boot reliably, but I don't know the reason.

Still, I have noticed that at shutdown systemd fails to properly disable the mounted partitions in some occasions.

**Comment by fsateler** [comment]
quota.service is not shipped by systemd.

**Comment by sergiocallegari** [comment]
Thanks for providing a hint pointing to the distro. That will make it easier to assure that they do not wait the upstream on this. I'll report it in the distro bug asap, so you do not get further spurious reports on it.

I take the occasion for a favor.  I'm quite inexpert in trying to debug the boot with systemd, and particularly baffled right now, with an issue that does not systematically repeat every time. Is there some pointer at what I can do to try to understand what is going on? I tend to suspect that something that should start /after/ all the fstab stuff is mounted starts too early and makes it impossible for the systemd mount to work with the entries in the fstab. What I do not understand is why /all/ the entries (including swap) start having issues and not the only one that should be interested by the quotas.

Is there any way to add verbosity to the fstab generator and the dev-disk-by & co processes?

**Comment by poettering** [comment]
uh oh. LVM and fakeraid do weird stuff with ready notifications for devices. If they never show up and the .device units time out, then that's something you should contact your distro about, and specifically there the LVM/fakeraid maintainers. This is nothing we can do anything about upstream, we don't know LVM/fakeraid at all...

Sorry, but I hope this makes sense. Closing.

**Comment by sergiocallegari** [comment]
I understand, and I had already moved in my distro the bug from systemd to quota.
Unfortunately, there does not seem to be much activity there... hence any hint at how to try to debug this would be more than welcome. Since systemd is new to me, how to debug the new boot process is an experience that I need to build...

A few items that could help you developers help me, if you feel you can do so:
1. Intel fake raid (the one I have) is now managed by the `mdadm` tools, so it should be no different from standard linux software raid in setup and notifications. I do not know if this helps...
2. The `mdadm` and `lvm2` parts of the boot seems to be OK on their own. Only when the `quota` package is installed the system fails to boot. Specifically, the boot seems to be prevented by the initial `quotacheck` (this is what the `quota.service` unit seems to do in ubuntu).
3. and **most important**. The thing that is _totally_ weird to me is that when the quota thing triggers the issue, **all the devices time out, not only those that are under raid/lvm**. For instance, `boot` times out, while being on a regular partition of a disk (`/dev/sdc1`). So does the activation of `swap` that is also a regular partition (`/dev/sdc3`). To me this seems to indicate a certain lack of robustness of the device units, because a problem on the raid and lvm items ends up blocking devices that are not managed by raid and lvm. Ideally, issues should remain as confined as possible.

So, my questions are:
- What can the device units block upon until they timeout?
- Are these units autogenerated somehow from reading the `fstab`? If so, how can one check them/tap into them, to provide some more verbosity on what is actually going on?
- Shouldn't the initial `quotacheck` happen after the .device units have completed?

I apologize if I am abusing your time with these questions... In my defense, I hope that if I can succeed in isolating the issue, this is going to be time saved on other spurious reports of the same problem...

**Comment by poettering** [comment]
really, i have no clue how mdadm/lvm does its stuff, please contact those maintainers.

.device units are show up as soon as they are reported by udev, ave the "systemd" tag in the udev db and as long as they do _not_ have SYSTEMD_READY=0 property set. How LVM/mdadm manage that flag is really up to them in their udev rules.

systemd autogenerates .mount units depending on /etc/fstab. However, we are not in the business of dealing with LVM/mdadm, that's an extension on top not provided by us.

quotacheck is run after all file systems listed in /etc/fstab have shown up.

if you want to debug your boot process, consider reading this:

https://freedesktop.org/wiki/Software/systemd/Debugging/
