### ISSUE TITLE
allow networkd to start in early boot

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#4504]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

Commit 1346b1f038 introduced an ordering of networkd to run after D-Bus. This was further refined in commit bcbca8291f. This effectively forces networkd to start in late boot (after `basic.target`), as `dbus.service` runs in late boot and networkd orders itself after that. So networkd's `DefaultDependencies=no` is effectively useless. In https://launchpad.net/bugs/1636912 the cloud-init developers asked for providing a way to make networking available in early boot, similar to what we had with Debian's ifupdown (`networking.service`).

For a similar reason (using resolved in early boot) I recently tried to make D-Bus run earlier (https://bugs.freedesktop.org/show_bug.cgi?id=98254), to get a little closer to the spirit of kdbus ("D-Bus is always available"). But discussion showed that D-Bus services are at least potentially not ready for this, so it was rejected (of course these issues would hit again if/when something like kdbus or systemd-dbus actually becomes a reality).

It seems to me that networkd is actually meant to have very little dependencies, given that you can even run it in the initrd (for iSCSI, remote root and the like). And that generally works, except for the `UseHostname: yes` case as then it needs to talk to hostnamed for setting the transient hostname.

Would it be feasible to drop the  `After=dbus.service` and instead queue/postpone the setting of the transient hostname until D-Bus starts up? The current code (commit bcbca8291f) entirely ignores the sent hostname if D-Bus isn't running, but by postponing this we would make networkd independent of dbus.service, allow it to start from initrd even, and still keep the transient hostname feature.

**Comment by keszybz** [comment]
That's a tough nut to crack. So far the philosophy in all tools except for pid1 and systemctl has been to assume the bus is present, fail if it is not. Changing that would complicate the implementation quite a bit. We could do it, but only if we give up on the replacement dbus. This requires making this level decision first.

**Comment by martinpitt** [comment]
> We could do it, but only if we give up on the replacement dbus.

I don't understand this -- I thought the whole idea of kdbus, or a "systemd-dbus" (as discussed on systemd.conf) was that the bus is available early already, so that systemd can stop having to jump through this "connect to the bus once it becomes available" hoop? I. e. all instances of "replacement bus" would actually already solve this problem instead of blocking it?

**Comment by keszybz** [comment]
Sorry, I wasn't clear. By "we could do it" I meant "we could do it internally in systemd-networkd". If we have kdbus/systemd-dbus/whatever, then there is no issue.

**Comment by utezduyar** [comment]
I think there were plans of accepting private connections until the dbus is available. Just like systemd does. In fact, wouldn't it be a good idea to have a library out of this logic?

**Comment by keszybz** [comment]
That'd require adding private dbus to both systemd-hostnamed and systemd-networkd. Ugh.

Maybe we should instead make the communication bidirectional, and have systemd-hostnamed query systemd-networkd for a transient hostname when starting up? systemd-networkd might have to trigger a start job for systemd-hostnamed if it cannot connect to it immediately.

**Comment by poettering** [comment]
i am pretty sure we should first to systemd-dbus-daemon (or whatever we call it), then all these issue kinda solve themselves...

**Comment by martinpitt** [comment]
In the meantime, would it be acceptable to teach networkd to reattempt to connect to D-Bus and set the DHCP-acquired hostname on `SIGHUP` or `SIGUSR1`? Then we could set that as `ExecReload=` and reload networkd after `dbus.service` is started, instead of completely restarting it. A complete restart has some side effects, like re-acquiring DHCP leases or touching existing connections in other ways.

This is blocking cloud-init, thus I'm looking for an intermediate solution that doesn't block on systemd-dbus.

**Comment by mbiebl** [comment]
And if there are concerns to expose that via ExecReload=, I guess this part is not crucial. One can still use`systemctl kill -s HUP systemd-networkd.service` rather easily. The important part would be to hook-up the reattempt to connect to D-Bus

**Comment by keszybz** [comment]
systemd uses SIGUSR1 so systemd-networkd should probably follow that example.

It's ugly, since there's no systemd-dbus or other solution in sight, I think this would be an acceptable interim workaround. I wonder how much code it'd be.

**Comment by martinpitt** [comment]
Hah, nevermind -- This already was done as a side effect in commit 9c0a72f9: If you start networkd without dbus, it shows a loop of

```
$ sudo SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-networkd
Failed to connect to bus, trying again in 5s: No such file or directory
Failed to connect to bus, trying again in 5s: No such file or directory
[..]
```

Then once you start dbus.socket, it connects, and you can call it fine:

```
$ busctl get-property org.freedesktop.network1 /org/freedesktop/network1 org.freedesktop.network1.Manager OperationalState 
s "routable"
```

So, this is actually just fine, no need to send/handle a signal even, and we could just drop the `After=dbus.service`. I'll look into fixing issue #4646 so that I can actually check how transient hostnames behave -- it could still be that this needs to be queued/postponed until it connects to D-Bus.

**Comment by mbiebl** [comment]
2016-11-18 15:06 GMT+01:00 Martin Pitt notifications@github.com:

> Hah, nevermind -- This already was done as a side effect in commit 9c0a72f
> https://github.com/systemd/systemd/commit/9c0a72f961e00b0447767973e7117e131bea5b5d:
> If you start networkd without dbus, it shows a loop of
> 
> $ sudo SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-networkd
> Failed to connect to bus, trying again in 5s: No such file or directory
> Failed to connect to bus, trying again in 5s: No such file or directory
> [..]
> 
> Does it try forever or fail after a timeout?
> Somehow I think it still would be nice if networkd could be signalled
> explicitly.
> I mean, 5s is as long as my complete boot process lasts. I think we can do
> better here.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by martinpitt** [comment]
> Does it try forever or fail after a timeout?

It currently tries forever.

> Somehow I think it still would be nice if networkd could be signalled explicitly.

Yes, I agree. If we wire that up properly, we could even drop that automatic retry loop.
