### ISSUE TITLE
Allow user-configurable sysctl.d path in systemd-sysctl

### ISSUE THREAD

**Issue by mmuehlenhoff** [systemd/systemd#4514]
Request for enhancement (RFE):
It would be useful if systemd-sysctl would gain an option to pass an alternate sysctl.d config directory, e.g systemd-sysctl --sysctldir=/etc/servicefoo/sysctl.d

This would allow to reuse systemd-sysctl for setting sysctl values for a service which is started after the initial setup of /etc/sysctl.d.

**Comment by falconindy** [comment]
Do you really need an entire directory for this? Why not just a single arbitrary file, which systemd-sysctl already supports?

**Comment by eliasp** [comment]
sysctl.d values are a global resource which cannot be controlled in a scoped/restricted way to affect only a single service/namespace.

Therefore I would argue against implementing this RFE as it would imply otherwise.

**Comment by keszybz** [comment]
@mmuehlenhoff systemd-sysctl already allows an arbitrary file to be specified by giving a full path. Wouldn't this be enough for you?

**Comment by mmuehlenhoff** [comment]
Giving it some more thought I tend to agree that a complete directory hierarchy might be too confusing or overkill in the general case. For my use case I'll workaround it with a wrapper that collates the directory entries to a single file which is then passed to systemd-sysctl. Closing.

**Comment by keszybz** [comment]
Note that you can also pass multiple file names to sysctl. No need to collate this into a single file.
