### ISSUE TITLE
LogColor not being respected on boot

### ISSUE THREAD

**Issue by emvigo** [systemd/systemd#4518]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux x86_64
### In case of bug report: Expected behaviour you didn't see

> LogColor is commented out as 'yes' in /etc/systemd/system.conf, meaning this is the default. This means on boot systemd should show output in color.
### In case of bug report: Unexpected behaviour you saw

> Output is not colored.
### In case of bug report: Steps to reproduce the problem

> Leave 'LogColor=yes' commented out. (Uncommenting it does make the output being shown in color).

**Comment by keszybz** [comment]
This might have been fixed in 158fbf7661912adf0f42c93155499119811dde82. Please retry with current git or systemd-232 when it is released.

**Comment by emvigo** [comment]
I would have to test this on a VM, not on my primary system (for obvious reasons). I'll report back when it's done.

**Comment by jlsalvador** [comment]
Tested in my system (arch-testing mkinitcpio), systemd-232 works correctly!

**Comment by keszybz** [comment]
Great! Thanks for testing.
