### ISSUE TITLE
Type oneshot without ExecStart and ExecStop - behavior does not match documentation

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4521]
- [ ] Bug report

> systemd 231-4
> 
> Arch

For a service unit file with:
[Service]
Type= oneshot
RemainAfterExit= yes

but no ExecStart or ExecStop, `daemon-reload` gives:
dynamic@bond0.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.

Now, man systemd.service says, for ExecStart=:
"When Type=oneshot is used, zero or more commands may be specified."

and for ExecStop=:
"Use of this setting is optional."

This is some unconventional use of the terms "zero" and "optional".

In this case, the service unit file is used to control start, stop, and restart ordering between other unit files, but does not "Start" or "Stop" any process itself.

A "useless" job can be enqueued and run, as a work-around: `ExecStart= /usr/bin/true`.

But still, either change the documentation, or change the error test.

**Comment by arvidjaar** [comment]
> In this case, the service unit file is used to control start, stop, and restart ordering between other unit files, but does not "Start" or "Stop" any process itself.

target sounds more suitable for this. What is the reason to use service instead target?

**Comment by thx1111** [comment]
1) Conceptually, this unit file is a service-initiator, run _before_ these services, not a service-flag, from _after_ theses services have been run.  Superficially, using the .target name will be misleading.
2) Conceptually, the term "target" connotes a stable fixed state.  The services started by this unit file are started with Wants, not Requires, and so there is no expectation that the state of the services as having been started will remain stable in that sense, should the started units terminate for whatever reason.
3) Where "target units will implicitly complement all configured dependencies of type Wants= or Requires= with dependencies of type After=", this is not desired.
4) The documentation at systemd.target is silent as to whether an explicit Before=some.service will override the default After=some.service when a Wants or Requires dependency exists.
5) Possibly an explicit DefaultDependencies=no will have to be written - though this is not worse than writing a dummy service section - but the need for this is unclear because of point 4.
6) When installing or otherwise referencing this unit, the default .service extension could not be assumed, and an explicit .target extension would have to be manually added with every command entered.

It would be nice to update systemd.target to address point 4.

Of course, whether or not a .target extension is or should be used, the issue of using ExecStart with Type=oneshot must be addressed.

**Comment by arvidjaar** [comment]
> It would be nice to update systemd.target to address point 4.

What is missing in current manual? "Unless explicit ordering dependency is defined" looks pretty clear?

> Unless ... explicit ordering dependency is already defined, target units will implicitly complement all configured dependencies of type Wants= or Requires= with dependencies of type After=.

**Comment by thx1111** [comment]
Oops, thanks.  Yes, it is there - sort-of.  Hmm - well, a "jog" to the reader's attention might be had with "Unless ... , or an explicit ordering dependency is defined with Before=, target units ...".  The explicit comma there is to dissuade reading "is set to no in either ... or an explicit ordering dependency ...".  "Either/or" is a common construction in the English language, and technically, that is the construction as written.  And an explicit reference to the single possible condition being implied, "Before=", makes this much less difficult to read.

Actually, I have no idea what "set to no in either of releated units" even means, which reading would be implied by your reading, that "... is already defined ..." is the alternate condition preceding the main statement "target units will implicitly complement", even though that comma before "or" is missing.  Presumably, "releated" is a misspelling of "related".

Thinking about it, I suppose that that means that if DefaultDependencies=no is set in _any_ of the units specified in the Wants or Requires dependencies in this unit, then this .target unit will not create the complementary After dependencies.  Or, is that inhibition of the After= compliment applied "one to one", so that After= is only applied to the specific Wants or Requires unit which has set DefaultDependencies=no, but not to others?  I suppose that "either" means "each" here, instead of "any".

And then, thinking about it some more, what that does _not_ say is that setting DefaultDependencies=no in _this_ unit file will do anything to inhibit the "complement all configured dependencies of type Wants= or Requires= with dependencies of type After=", which was sort of the assumption I made, just skimming the paragraph.  I am suspicious that that is not what was actually meant, though I can not say.

If that is correct, then "being clever", using cryptic phrases which require detailed inference, does not make for good documentation.  That style just makes the documentation tedious and error prone to read.

So instead, the man page should be edited to say:
"Target units will implicitly complement all configured dependencies of the type Wants= or Requires= with ordering dependencies of the type After=, with the exception that no implicit After= dependency will be set when an explicit ordering dependency is defined with Before= in this unit file, or when, for a specified unit, DefaultDependencies=no is set in the unit file specified in the Wants= or Requires= dependency in this unit file.  Note that setting DefaultDependencies=no in this target unit file will not inhibit the creation of the implicit After= dependencies in this unit file.

Also note that Wants= or Requires= must be defined in the target unit itself.  If, for example, Wants=some.target is defined in some.service, the implicit ordering After=some.service will not be added to this target unit."

Unless, of course, that bit about setting DefaultDependencies=no in the target unit file is not true, in which case, remove "not" from the sentence, to invert the meaning.

**Comment by poettering** [comment]
Yeah, we could definitely clarify the docs here.

But please do not misuse services for purposes where targets are supposed to be used. Targets is our way of grouping units, and they do not require implicit After= ordering. We have many targets in place by default that are ordered in either way (see systemd.special) for examples.

Hence: yupp documentation should be clarified on this, but the usecase is borked, I think.

**Comment by inkhey** [comment]
Possibility related to this issue but a bit different. I have a use case where I do need a "target" that became inactive  when all the requirements are activated (in fact, it's a group of oneshot service).  For now i used a oneshot with a dummy ExecStart but there is maybe a better solution ?
