### ISSUE TITLE
RFE: Allow arbitrary/supported Kind= types for NetDev

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#4523]
### Submission type
- Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Gentoo, Kernel 4.8.1
### RFE

Currently, `*.netdev` definitions only support a [hardcoded set of values](https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#Supported%20netdev%20kinds) for `Kind=`, while e.g. `iproute2`/`ip` supports whatever the Kernel currently supports.

This prevents using `systemd-networkd` to setup a netdev for using [WireGuard](https://www.wireguard.io/quickstart/) and currently requires a workaround using `ip link add dev wg0 type wireguard` to create the required netdev.

It looks like `ip` queries the Kernel via Netlink for supported link types, while `systemd-networkd` has a hardcoded table in [`src/network/networkd-netdev.c` → `netdev_kind_table`](https://github.com/systemd/systemd/blob/master/src/network/networkd-netdev.c#L61)

So this RFE asks for supporting a "dynamic lookup" of supported types just as `ip` does it.

**Comment by poettering** [comment]
Hmm, I wonder how useful this would be if we cannot actually configure the thing. The fewest network device kinds actually work without any configuration...

**Comment by eliasp** [comment]
Well, in this case the network configuration could even be done by systemd-networkd, where currently `ip` is used:

```
ip address add dev wg0 192.168.2.1 peer 192.168.2.2
```

All the further configuration is then handled by WireGuard itself, but I can't tell whether something similar  applies to other/similar scenarios or whether this is a rather unique case.

Besides that, I wonder how WireGuard's service unit could interact with systemd/systemd-network to start/stop depending on whether the interface is up/configured or not etc. - but that's a completely different issue to think about :)

**Comment by Mic92** [comment]
@eliasp I am ẃorking on full wireguard support btw: https://github.com/systemd/systemd/pull/4191
It is already functional, but I want to do more testing.

**Comment by eliasp** [comment]
> @eliasp I am ẃorking on full wireguard support btw: #4191
> It is already functional, but I want to do more testing.

This is beyond awesome. Thanks a lot.

So for my usecase #4191 will suffice and I'll leave it to @poettering or @teg to decide whether this RFE still makes sense or can be closed.
