### ISSUE TITLE
Setting of log_level in udev.conf affects everything

### ISSUE THREAD

**Issue by izh1979** [systemd/systemd#4525]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> At least >= 225
### Used distribution

> Sailfish OS
### In case of bug report: Expected behaviour you didn't see

> Setting of log_level in udev.conf should affect only udev
### In case of bug report: Unexpected behaviour you saw

> Setting of log_level in udev.conf affects systemd and some other tools/daemons
### In case of bug report: Steps to reproduce the problem

> Set one log_level in system.conf, set another log_level in udev.conf and note that the latest overrides the first.

The problem is that `main()` -> `manager_new()` -> `udev_new()` -> `log_set_max_level()` is called later than any other log-level settings in systemd. So udev's log_leve overrides any previously level set. Also `udev_new()` is used in many other tools like umount or journald-server. I suppose that `udev_new()` shouldn't call `log_set_max_level()`.

**Comment by evverx** [comment]
> At least >= 225

`>= 218` : https://github.com/systemd/systemd/commit/25e773eeb4f853804e1b

I think this is a regression

**Comment by evverx** [comment]
` log_level` in `udev.conf` doesn't affect `systemd`. Sadly, it doesn't affect `udev` too: https://github.com/systemd/systemd/issues/5419
