### ISSUE TITLE
regression – supplementary groups not set anymore

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#4531]
Somewhere between 5c4624e082c0c153df63c0d11e31a85c73f770b7 and 52028838a1bc5f55f623f5f0344ee685d87d1fd0, systemd stopped loading supplementary groups when starting services as non-root users. This particularly creates problems for `user@.service`.

I suspect commit 4d885bd326d958827d926512ecc5e0d21f6ad76b.

### systemd version the issue has been seen with

> v231-830-g52028838a1bc

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

In all apps:

    $ id
    uid=1000(grawity) gid=1000(grawity) groups=1000(grawity),3(sys),4(adm),10(wheel),50(games),100(users),108(vboxusers),150(wireshark)

### In case of bug report: Unexpected behaviour you saw

In gnome-terminal, which is launched via systemd --user:

    $ id
    uid=1000(grawity) gid=1000(grawity) groups=1000(grawity)

### In case of bug report: Steps to reproduce the problem

    unit=$(sudo systemd-run --uid=grawity id 2>&1 | sed "s/.* //")
    output=$(sudo journalctl -b -u "$unit" -o cat | grep 'uid=')
    [ "$output" == "$(id grawity)" ]

**Comment by evverx** [comment]
> I suspect commit 4d885bd.

Indeed. 4d885bd~1 works fine
cc @tixxdz

**Comment by poettering** [comment]
@tixxdz can you have a look?

**Comment by tixxdz** [comment]
@grawity thanks , could you please try the fix at https://github.com/systemd/systemd/pull/4533 ?
