### ISSUE TITLE
systemd crashes when systemd-run generates very large error message

### ISSUE THREAD

**Issue by dcbaker** [systemd/systemd#4534]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

debian testing

### In case of bug report: Unexpected behaviour you saw

When receiving a particularly large error message, systemd[1] crashes in xsprintf, leaving the system in a state that even rebooting cleanly is impossible.

### In case of bug report: Steps to reproduce the problem

call systemd-run with a command that will generate a particularly large error message, in my particulary case saltstack calls systemd-run with apt-get to install packages, one of those packages doesn't exist and apt returns an error message longer than MAX_LINE.

### Journal
This is the message in journald.

```txt
Nov 01 15:37:37 computer systemd[1]: Assertion 'xsprintf: buf[] must be big enough' failed at ../src/core/job.c:771, function job_log_status_message(). Aborting.
Nov 01 15:37:37 computer systemd[1]: Caught <ABRT>, dumped core as pid 3316.
Nov 01 15:37:37 computer systemd[1]: Freezing execution.
Nov 01 15:37:37 computer salt-minion[619]: [ERROR   ] Command '['systemd-run', '--scope', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'insta [truncated]
Nov 01 15:37:37 computer salt-minion[619]: :i386', 'sudo', 'openjdk-8-jre', 'libwayland-egl1-mesa', 'libgcrypt20:i386', 'libxcb-dri2-0-dev:i386', 'libxcb-dri3-dev', 'libegl1-mesa', 'libxcb-glx0-dev', ' [truncated]
```

**Comment by evverx** [comment]
Oh, I can confirm:

``` sh
$ sudo systemd-run --description $(perl -le 'print "a"x10000') id
Broadcast message from systemd-journald@localhost.localdomain (Wed 2016-11-02 00:11:02 UTC):

systemd[1]: Caught <ABRT>, dumped core as pid 4076.


Broadcast message from systemd-journald@localhost.localdomain (Wed 2016-11-02 00:11:02 UTC):

systemd[1]: Freezing execution.
```

This regression was introduced by d054f0a4d451120c26494263fc

**Comment by evverx** [comment]
> /src/core/job.c:771, function job_log_status_message(). Aborting

But that's not about a long error message. `job_log_status_message` prints `unit_description(u)`

**Comment by evverx** [comment]
https://github.com/systemd/systemd/pull/4540#discussion_r86224598

```
-bash-4.3# systemd-run --service-type=notify --description="$(printf "a%10000s" "a")" sleep 10000
Warning! D-Bus connection terminated.
Broadcast message from systemd-journald@systemd-testsuite (Wed 2016-11-02 10:33:52 UTC):

systemd[1]: Caught <ABRT>, dumped core as pid 188.


Failed to wait for response: Connection reset by peer

Broadcast message from systemd-journald@systemd-testsuite (Wed 2016-11-02 10:33:52 UTC):

systemd[1]: Freezing execution.

-bash-4.3# journalctl | grep Assert
systemd-testsuite systemd[1]: Assertion 'xsprintf: buf[] must be big enough' failed at src/core/unit.c:1453, function unit_status_log_starting_stopping_reloading(). Aborting.
```
