### ISSUE TITLE
DynamicUser=yes doesn't respect SupplementaryGroups=

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#4539]
Based on https://github.com/systemd/systemd/pull/4533#issuecomment-257782530

```
DynamicUser=yes
User=hola
SupplementaryGroups=1
```
```
systemd[1]: a.service: User lookup succeeded: uid=1001 gid=1001
...
sh[184]: uid=1001(hola) gid=1001(hola) groups=1001(hola)
...
```

https://github.com/systemd/systemd/pull/4533#issuecomment-257925625
> And I have the suspicion that we should use the same codepaths for this regardless if DynamicUsers= is set or not. After all, DynamicUsers= means "use a dynamic user if there is no static user for this". It does not mean "use a dynamic user, and fail if there is a static user"

**Comment by tixxdz** [comment]
@evverx I pushed a fix but yeh pretty sure you will notice another issue... ;-)

Thanks!

**Comment by evverx** [comment]
@tixxdz , thanks!

I'll take a look tomorrow

**Comment by gdamjan** [comment]
It seems that the supplementary group is aplied to the process, but is not reflected in `getent passwd hola` / `id hola`? (systemd 238 Arch)
