### ISSUE TITLE
timesyncd gives no error message if it can not reach servers

### ISSUE THREAD

**Issue by f4hy** [systemd/systemd#454]
I had a setup which for months the NTP servers in /etc/systemd/timesyncd.conf were not reachable, yet nothing in the journal about it. Doing `journalctl --unit=systemd-timesyncd.service
` gives me weeks of nothing but:

```
    Jun 25 08:15:43 f4hy systemd[1]: Starting Network Time Synchronization...
    Jun 25 08:15:43 f4hy systemd[1]: Started Network Time Synchronization.
    Jun 26 01:03:07 f4hy systemd[1]: Stopping Network Time Synchronization...
    Jun 26 01:03:07 f4hy systemd[1]: Stopped Network Time Synchronization.
    -- Reboot --
    Jun 26 08:15:20 f4hy systemd[1]: Starting Network Time Synchronization...
    Jun 26 08:15:20 f4hy systemd[1]: Started Network Time Synchronization.
    Jun 27 03:12:59 f4hy systemd[1]: Stopping Network Time Synchronization...
    Jun 27 03:12:59 f4hy systemd[1]: Stopped Network Time Synchronization.
    -- Reboot --
```

with no synchronized messages updating the time, but also no messages that the time servers were unreachable. Eventually when I figured out the servers in the config were not reachable from the network I was on I set them to the usual ntp pool and it synchronized immediately after restarting the service.

I had some difficult diagnosing the problem as well since I couldn't tell if it simply wasn't checking to update very often or something larger. This could have been avoided if there was better error logging or some way to force timesyncd to check now rather than wait for it to check on its own so I could diagnose that something was actually wrong.

**Comment by kaysievers** [comment]
Do you run networkd? Timesyncd needs to know about that there is a network connection:

Jul 09 12:15:03 ank systemd-timesyncd[527]: Network configuration changed, trying to establish connection.

**Comment by f4hy** [comment]
Ah so networkd is a requirement? I do not believe I am running it. I guess it should check for networkd is running and give some sort of error if it is not, ya?

**Comment by martinpitt** [comment]
> Ah so networkd is a requirement?

It shouldn't be, at least it's not intended. I'm using timesyncd with NetworkManager on a desktop, and I get "Synchronized to time server ..." from timesyncd as soon as NM connects to a network.

**Comment by f4hy** [comment]
I am not using NetworkManager either.

**Comment by dvdhrm** [comment]
timesyncd monitors the network configuration via APIs provided by systemd-networkd. It is _NOT_ required to use systemd-networkd to manage your links, however, it must be enabled. If it is not enabled, someone other network manager needs to provide a compatibility API. Maybe NetworkManager does this, maybe it doesn't. Regardless, we do not support such setups, sorry.

Closing this now. Please include networkd and enable it, if you want to make use of timesyncd.
