### ISSUE TITLE
systemd-resolved.service fails at boot

### ISSUE THREAD

**Issue by rbirt** [systemd/systemd#4541]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
231
> …

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
buildroot
> …

### In case of bug report: Expected behaviour you didn't see
systemd-resolved.service should start with no error
> …

### In case of bug report: Unexpected behaviour you saw
systemd-resolved.service fails at boot.  The error message is:

Jul 25 12:50:00 WAND9876 systemd-resolved[315]: Failed to start manager: Cannot assign requested address
Jul 25 12:50:00 WAND9876 systemd[1]: systemd-resolved.service: Main process exited, code=exited, status=1/FAILURE
Jul 25 12:50:00 WAND9876 systemd[1]: Failed to start Network Name Resolution.
Jul 25 12:50:00 WAND9876 systemd[1]: systemd-resolved.service: Unit entered failed state.

I put in some logging:

Jul 25 12:50:00 WAND9876 systemd-resolved[315]: Using system hostname 'WAND9876'.
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: SOCKET RETURNED 15
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: FIRST SETSOCKETOPT RETURNED 0
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: SECOND SETSOCKETOPT RETURNED 0
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: THIRD SETSOCKETOPT RETURNED 0
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: FOURTH SETSOCKETOPT RETURNED 0
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: BIND of 15 RETURNED -1
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: MANAGER_DNS_STUB_UDP_FD RETURNED -99
Jul 25 12:50:00 WAND9876 systemd-resolved[315]: MANAGER_DNS_STUB_START RETURNED -99
> …

### In case of bug report: Steps to reproduce the problem
fails on every system boot
> …

**Comment by poettering** [comment]
do you have anything else listening on port 53 locally?

**Comment by poettering** [comment]
your bind() appears to return EADDRNOTAVAIL, now I wonder how that could happen. According to the man page:

```
  EADDRNOTAVAIL
          A nonexistent interface was requested or the requested address was not local.
```

Do you have something configured weirdly in your kernel regarding IPv4 or loopback devices or so?

**Comment by rbirt** [comment]
Nothing using 53, netstat shows:

[root@WAND9876 ~]# netstat -uavn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State  
udp        0      0 0.0.0.0:68              0.0.0.0:\*                          

File system loopback is enabled in the kernel but that should have no effect on this.  I don't believe there's any weird configuration.  I have tried 2 kernels, one I have used with systemd successfully in the past and it shows the same error.

Anything I can test or do to get more information?

**Comment by poettering** [comment]
what kernel is this?

is ipv6 compiled out of the kernel?

i was referring to the loopback networking device, not the file system. Does it show up properly in "ifconfig" with an IP address and everything?

**Comment by rbirt** [comment]
kernel 4.1.15
IPv6 is compiled in
ifconfig output is normal, there is an IP address and the machine can communicate over the network

**Comment by poettering** [comment]
how does your routing table look like? how does "ifconfig lo" look like? (or the iptools equivalent...)

**Comment by rbirt** [comment]
sorry for the delay, got busy at other things.

i checked 'ifconfig lo' as you suggested and there was no IP address assigned to it.  i modified /etc/network/interfaces to make lo static and assigned 127.0.0.1 to it and now systemd-resolved.service runs without error.

is that a good fix or should the IP address get set another way?

**Comment by poettering** [comment]
Well, PID 1 actually configures "lo" during early boot, before it even forks off the first userspace process. As such, if the IP address went missing for you, you have some userspace component in place that actively drops it. Try tracking down which component that is.

Either way, this appears not to be a systemd problem. Closing hence.
