### ISSUE TITLE
pkg-config files do not respect --define-variable=prefix option for pkg-config

### ISSUE THREAD

**Issue by pspacek** [systemd/systemd#4549]
### Submission type

  - [X] Bug report
  - [] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232, Git head b2c82a7f2f7c8ae426a9208fb79c5abbd5e3181c

### Used distribution

> upstream Git

### In case of bug report: Expected behaviour you didn't see

> Output of command `pkg-config --define-variable=prefix=/foo --variable=systemdsystemunitdir systemd` should print path which respects given prefix, e.g. `/foo/lib/systemd/system`.

### In case of bug report: Unexpected behaviour you saw

> Output of command `pkg-config --define-variable=prefix=/foo --variable=systemdsystemunitdir systemd` still prints `/usr/lib/systemd/system` and ignores prefix `/foo`

### In case of bug report: Steps to reproduce the problem

> Call `pkg-config --define-variable=prefix=/foo --variable=systemdsystemunitdir systemd` and check if prefix `/foo` is respected.

### Use-case:

> This gets very handy when systemd's pkg-config variables are used by other software packages in configure. Respecting the prefix allows the packages to use --prefix=/tmp/somewhere and operate on this new sub-tree in tests etc.

Thank you for fixing this!

**Comment by keszybz** [comment]
The big complication is the fact that during ./configure phase, the user is allowed to override both `prefix` and other variables which depend on it, e.g. `systemdutildir`, or just either of them. So the pkgconfig variable `systemdutildir` would have to be defined as `${prefix}/lib/systemd`, _unless_ it was configured individually. Autotools does something like that, allowing various variables to be overridden during `make install`, but it's not trivial.

**Comment by poettering** [comment]
@keszybz hmm, why did you set "has-pr"? did you actually push that PR?

**Comment by keszybz** [comment]
Indeed I didn't. Thanks for catching this.
