### ISSUE TITLE
man pam_systemd is quite outdated

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#4550]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Own

### In case of bug report: Expected behaviour you didn't see

> https://www.freedesktop.org/software/systemd/man/pam_systemd.html seems to be quite outdated.

From the man page:
On login, this module ensures the following:
1 If it does not exist yet, the user runtime directory /run/user/$USER is created and its ownership changed to the user that is logging in. UMUT: This is not true. It is logind creating this directory.
3 A new systemd scope unit is created for the session. If this is the first concurrent session of the user, an implicit slice below user.slice is automatically created and the scope placed into it. An instance of the system service user@.service, which runs the systemd user manager instance, is started. UMUT: AFAIK, this is also done by logind. It is logind creating the user session and the user session service file creating the pam session.

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

**Comment by keszybz** [comment]
If you could submit a patch that'd be great...

**Comment by utezduyar** [comment]
@keszybz Do you mean me or Lennart, Zbigniew?

**Comment by keszybz** [comment]
You, @utezduyar. It's one of those "if you notice something, send a PR" cases ;)

**Comment by utezduyar** [comment]
@keszybz No problem. :) I am not so proficient with the per user part of systemd but I can throw out something and we get comments.
