### ISSUE TITLE
Discussion: Reliable way of notification of coredump generations | extending coredump service

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#4552]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> OpenEmbedded

### In case of bug report: Expected behaviour you didn't see

> 

How can we retrieve a reliable way of coredump generations? 
How can we extend the things done on coredump generation?

We really like how coredump is an instantiated service and how compression is integrated with it. But we like to do more with the coredumps when they are generated. The plan is disabling coredump's cleaning functionality and doing the cleaning through an external service which will do more with the dumps (like sending them over to a remote server over proprietary communication etc.) What are our options?
A) External service watches /var/lib/systemd/coredump through inotify
B) Listen on JobRemoved signal from systemd and try to figure out which file is added last.
C) Send a signal on coredumpd as soon as the file is written on the file system.
D) systemd-coredump forks a configurable processes (ex: ABRT) and pipes the dump to the process and stays alive until the child processes exits. 

Just threw out my ideas. What are the thoughts?

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
coredumps are recorded in the journal. The journal api notifies you when new entries are added, and you can filter to only see coredumps via its MESSAGE_ID. moreover, there's a concept of "cursors" in the journal which permits you to continue watching wherever you left off, so that you do not miss a single coredump even if you are interrupted in the middle or not running continiously.

To get a live view on coredumps happening, use `journalctl -f MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1` on the command line. And you can hack up something similar in C using sd-journal relatively easily. 

What else do you need?

**Comment by utezduyar** [comment]
We don't have journal on for storage, not even volatile. Even if we did, the storage would be minimum. We cannot solely rely on journal api to retrieve dumps in case journal has been rotated. Then we also need to look at the file system on startup. journald, inotify, JobRemoved all kind of notify you on a new dump file. Do we really want to couple coredumping with journal?

**Comment by poettering** [comment]
yes, that's how it is designed. coredumps are primarily loggable events for us. If we actually keep the blob around, that's great, but that's optional and secondary to the stuff stored in the journal. 

coredumpctl and those things are really just frontends to the journal, nothing else.

**Comment by jfilak** [comment]
@umuttl Have a look at https://www.mankier.com/1/abrt-dump-journal-core This tool watches journald for coredumps and if it spot any, it notifies ABRT whose major goal is to notify users about crashes:
https://github.com/abrt/abrt/wiki/ABRT-local-problem-detection-notification-channels

**Comment by poettering** [comment]
Let's close this here, as this is already implemented via the journal. And to get those events you don't even need to enable persistant journal, the in-RAM volatile version sufficies,
