### ISSUE TITLE
v232 fails to build

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#4559]
### Submission type

  - [X ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

### Used distribution

Arch Linux

Build log attached
[systemd-232-build.txt](https://github.com/systemd/systemd/files/569859/systemd-232-build.txt)

**Comment by poettering** [comment]
hmm, something wrong with the xml stylesheets on arch?

(btw, we'd love to have archlinux-based CI hooked up with our github!)

**Comment by falconindy** [comment]
@grawity mentioned that this might be a libxslt bug in Arch's package.

**Comment by falconindy** [comment]
Yep, not a systemd bug.

**Comment by falconindy** [comment]
For posterity, this is actually a docbook-xsl bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765567
