### ISSUE TITLE
systemd-nspawn networking best practices

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#456]
Also posted on https://bbs.archlinux.org/viewtopic.php?pid=1541228#p1541228

I think I followed the guide https://wiki.archlinux.org/index.php/Systemd-nspawn correctly.

I have the guide's `/etc/systemd/network/50-containers.network` setup on my host.

But I can't get network working from a container.

<img src=http://s.natalian.org/2015-07-01/no-network-in-container.png>

http://ix.io/jpm is a log of how I started the container.

On https://wiki.archlinux.org/index.php/Systemd-networkd there is talk of setting up a container on a **bridge**. I am not sure what's the _right way_ to do it, but I don't really like bridge since I feel I need the host to dispatch everything to the containers anyway.

So what I was hoping to do was with https://wiki.archlinux.org/index.php/Systemd-nspawn#nsswitch.conf I would be running containers for different httpd services. Like foobar container would be set off with nginx running on the host like so:

```
server { 
    server_name foobar.example.com;
      location / {
        proxy_pass http://foobar;
      }
  }
```

Ideally there was some lightweight systemd configuration to dispatch various services to containers, be it http or via a certain port to a container. Since I can't be bothered to run nginx really. Be nice if systemd had some sort of **networking vision** for containers.

**Comment by poettering** [comment]
If you run networkd on the host and in the container and use nspawn's -n switch things should just wor modulo DNS config. We ship two .network files by default, one that only applies to the host, and automaticalyl picks a free IP range, does DHCP serving on it as well as IP masquerading. The other one applies only to containers where it does a DHCP client. If you the configure your internal's DNS server to something like 8.8.8.8 all should just work. No need to configure networkd explicitly.

If you install resolved (with nss-resolve) on the host and in the container you will also get automatic host name resolution of the host and container names work without further configuration.

We plan to propagate DNS server info eventually at which time everything should be fully automatic requiring zero manual configuration.

I hope this makes sense.

**Comment by kaihendry** [comment]
Thanks, but I am still wondering about the default practice. For example without `-n` there is no virtual interface. It just binds to the hosts IP IIUC. Ok, that sounds fine really. It's not "isolated" by default, but I guess it's easiest to use and seamlessly integrates when people use it like `chroot`.

However with `-n` is specified, I was just curious to know what the grand scheme of things were.  I guess it just grabs an IP as the host's systemd-networkd is configured and that's that. Though I was wondering if there was an easier way of routing virtual host HTTP requests to containers in the works.

Thank you!

**Comment by poettering** [comment]
@kaihendry yes, there's nspawn's --port= switch to allow port forwarding from the host to the container.
