### ISSUE TITLE
user session fails with long-strarting units

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#4561]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> user session should start successfully regardless of how long individual unit takes to start

### In case of bug report: Unexpected behaviour you saw

> systemd --user session fails with timeout

### In case of bug report: Steps to reproduce the problem

> create bunch of .service files in .config/systemd/user which have long startup time. In my case it was emacs but I'm pretty sure any unit which takes long enough to start will do.

As a workaround - is there a way to configure the timeout, after which systemd --user is killed?

**Comment by heftig** [comment]
This one is really easy to hit because any misbehaving user service holding up the start until the timeout triggers will cause the user manager to get killed. (Recent bug: https://bugs.archlinux.org/task/54396)

Because `user@.service` and user units use the same (default) timeout, it's effectively useless for any units in the initial transaction.

IMO this should be band-aid-fixed by giving `user@.service` a few more seconds to start. Dealing with longer non-default timeouts in the user units can come later.

**Comment by heftig** [comment]
Hmm, unfortunately just extending the timeout isn't enough, as the user manager immediately tries to start the service *again* (possibly because of socket activation), continues waiting and then gets killed.

```
Jun 11 22:21:46 philomeena systemd[25185]: gpg-agent.service: Start operation timed out. Terminating.
Jun 11 22:21:46 philomeena systemd[25185]: Failed to start Gnupg Agent.
Jun 11 22:21:46 philomeena systemd[25185]: gpg-agent.service: Unit entered failed state.
Jun 11 22:21:46 philomeena systemd[25185]: gpg-agent.service: Failed with result 'timeout'.
Jun 11 22:21:46 philomeena systemd[25185]: Starting Gnupg Agent...
Jun 11 22:22:15 philomeena systemd[1]: user@1001.service: Start operation timed out. Terminating.
```

Any ideas?

**Comment by ghost** [comment]
> Any ideas?

Rather obvious idea would be not to kill user@ session at all. Ever. The user@ session is the main reason I boot computer in a first place - killing it under any circumstances (except for computer shutdown) is fatal error which simply should not happen.

**Comment by poettering** [comment]
I am pretty sure this is already fixed by 0c2826c60c508a0300f9978ae3818d6f4c00d53a. Closing. If this is still a problem even with that fix, please reopen.

**Comment by ghost** [comment]
Great news, thanks! Which release it'll be part of?

**Comment by poettering** [comment]
v236
