### ISSUE TITLE
A new type in  tmpfiles.d syntax

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4564]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>systemd 231
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

>Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

It would be nice to have a type so that: if a directory doesn't exist, don't create it; if it exists, its contents will be removed when i use **/bin/systemd-tmpfiles --remove**. Yes, I know there are other ways to solve this problem, but I think an _enriched_ tmpfiles.d syntax is the way to go.

**Comment by keszybz** [comment]
You mean like `e`?

```
   d
       Create a directory. The mode and ownership will be adjusted if specified and
       the directory already exists. Contents of this directory are subject to time
       based cleanup if the time argument is specified.

   D
       Similar to d, but in addition the contents of the directory will be removed
       when --remove is used.

   e
       Similar to d, but the directory will not be created if it does not exist.
       Lines of this type accept shell-style globs in place of normal path names.
```

**Comment by ghost** [comment]
But there's no mention about _--remove_ at **e** definition.

**Comment by ghost** [comment]
Guys, I just tried the type **e** and **/bin/systemd-tmpfiles --remove**: it doesn't erase the contents of my directories unless the type is **D**.

**Comment by keszybz** [comment]
Indeed.

**Comment by ghost** [comment]
So I still think it would be nice to have a type so that: if a directory doesn't exist, don't create it; if it exists, its contents will be removed when i use **/bin/systemd-tmpfiles --remove**.
