### ISSUE TITLE
`ID_BUS` empty for ThinkPad X1 Mouse

### ISSUE THREAD

**Issue by CircleCode** [systemd/systemd#4566]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

`systemctl --version` output:
```
systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP
+GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

I own a ThinkPad X1 Wireless Touch Mouse (http://shop.lenovo.com/us/en/itemdetails/4X30K40903/460/0E80436C80A748E6AA76791FC42C9CA3).
This mouse can both be connected through the provided dongle (which works fine) or through bluetooth. While connected through bluetooth, hwdb custom rules are not used.
After investigations with @whot , this seems to be related with `ID_BUS` not being defined when the mouse is connected through bluetooth.

here is the output of `udevadm info`:
```
P: /devices/virtual/misc/uhid/0005:17EF:6088.0004/input/input21/event20
N: input/event20
E: DEVNAME=/dev/input/event20
E: DEVPATH=/devices/virtual/misc/uhid/0005:17EF:6088.0004/input/input21/event20
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_MOUSE=1
E: ID_SERIAL=noserial
E: LIBINPUT_DEVICE_GROUP=5/17ef/6088/2112:44:85:00:10:3A:9B
E: MAJOR=13
E: MINOR=84
E: SUBSYSTEM=input
E: USEC_INITIALIZED=2451762910
```

here is the output for `udevadm info -a`:
```
  looking at device '/devices/virtual/misc/uhid/0005:17EF:6088.0004/input/input21/event20':
    KERNEL=="event20"
    SUBSYSTEM=="input"
    DRIVER==""

  looking at parent device '/devices/virtual/misc/uhid/0005:17EF:6088.0004/input/input21':
    KERNELS=="input21"
    SUBSYSTEMS=="input"
    DRIVERS==""
    ATTRS{name}=="ThinkPad X1 Mouse"
    ATTRS{phys}=="44:85:00:XX:XX:XX"
    ATTRS{properties}=="0"
    ATTRS{uniq}=="F4:D5:41:XX:XX:XX"

  looking at parent device '/devices/virtual/misc/uhid/0005:17EF:6088.0004':
    KERNELS=="0005:17EF:6088.0004"
    SUBSYSTEMS=="hid"
    DRIVERS=="hid-generic"
    ATTRS{country}=="00"

  looking at parent device '/devices/virtual/misc/uhid':
    KERNELS=="uhid"
    SUBSYSTEMS=="misc"
    DRIVERS==""
```

Note: adding an explicit rule `ATTRS{name}=="ThinkPad X1 Mouse", ENV{ID_BUS}="bluetooth", GOTO="persistent_input_end"` to `60-persistent-input.rules` made the hwdb custom definition work

**Comment by poettering** [comment]
I figure this essentially is the same as #3072 -- We have no support for bluetooth busses so far. Closing as duplicate

**Comment by CircleCode** [comment]
Not sure I fully understand

> We have no support for bluetooth busses so far.

because https://github.com/systemd/systemd/blob/master/rules/60-persistent-input.rules#L5
tags `ENV{ID_BUS}="bluetooth"`

**Comment by ObiWahn** [comment]
@CircleCode

How did you manage to connect the mouse via bluetooth in the fist place? I am able to find it in blueman-manager but not in /dev/input. My system is a up-to-date Debian SID.

**Comment by CircleCode** [comment]
@ObiWahn I did nothing special: gtnome saw it in the bluetooth control center, and once paired, everything went fine (excepted this problem with ID_BUS)

**Comment by whot** [comment]
fwiw, the udev rule you linked to only applies in case any of the parents has SUBSYSTEM 'bluetooth'. the udevadm output shows that this isn't the case (hid and uhid), that's why it doesn't get applied. This looks like we need something more sophisticated, possibly hooking onto something like parsing KERNELS

**Comment by whot** [comment]
I'm wondering if something simple like the below is enough to add under the current bluetooth check:
    ATTRS{id/bustype}=="0005", ENV{ID_BUS}="bluetooth", GOTO="persistent_input_end"

**Comment by CircleCode** [comment]
do you want me to test the line `ATTRS{id/bustype}=="0005", ENV{ID_BUS}="bluetooth", GOTO="persistent_input_end"`?
(for my culture: where does this `ATTRS{id/bustype}=="0005"` check? (I do not see these attributes in the udevadm output…)

**Comment by whot** [comment]
"attributes" are really just files in the /sys/ tree, so this basically checks for a file called id/bustype in one of the parents, which will be the input node. You can get there manually through /sys/class/input/event0/device, for your event node. and yes, please test that line, because that would be a quite simple fix for the issue.

**Comment by CircleCode** [comment]
sorry for the long delay.
I've tested adding `ATTRS{id/bustype}=="0005", ENV{ID_BUS}="bluetooth", GOTO="persistent_input_end"` to `/usr/lib/udev/rules.d/60-persistent-input.rules` and my hwdb rule is now taken into account.
Is there a way i can make this change persistent (because `/usr/lib/udev/rules.d/60-persistent-input.rules` is erased at each update), or will it be included in a future systemd release?

**Comment by whot** [comment]
easiest way is to copy it into /etc/udev/rules.d until we figure out what to do for upstream

**Comment by whot** [comment]
I'm de-duplicating this bug because it's a separate issue than #3072. That bug is related to the symlinks which are intentionally skipped for bluetooth devices. This bug is about the lack of an ID_BUS label, the two issues are orthogonal.
