### ISSUE TITLE
mounting /sys/fs/fuse/connections fails due to failing condition, probably racy

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4574]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

uname -a
Linux pluto 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 GNU/Linux

### In case of bug report: Expected behaviour you didn't see

sys-fs-fuse-connections.mount being properly started

### In case of bug report: Unexpected behaviour you saw
```
$ systemctl status sys-fs-fuse-connections.mount 
● sys-fs-fuse-connections.mount - FUSE Control File System
   Loaded: loaded (/lib/systemd/system/sys-fs-fuse-connections.mount; static; vendor preset: enabled)
   Active: inactive (dead) since Fri 2016-11-04 15:45:06 CET; 1min 50s ago
Condition: start condition failed at Fri 2016-11-04 14:59:01 CET; 47min ago
    Where: /sys/fs/fuse/connections
     What: fusectl
     Docs: https://www.kernel.org/doc/Documentation/filesystems/fuse.txt
           http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems

$ lsmod | grep fuse
fuse                   98304  2

$ ls -ld /sys/fs/fuse/connections/ 
dr-xr-xr-x 2 root root 0 Nov  4 14:59 /sys/fs/fuse/connections/
```
### In case of bug report: Steps to reproduce the problem

This looks like a race condition to me, when the fuse module is loaded and we trigger the start via

/lib/udev/rules.d/99-systemd.rules:SUBSYSTEM=="module", KERNEL=="fuse", TAG+="systemd", ENV{SYSTEMD_WANTS}+="sys-fs-fuse-connections.mount"

When the start attempt is made by systemd, /sys/fs/fuse/connections/ does not *yet* exist.

**Comment by poettering** [comment]
Well, that would be a kernel bug then. The module should make /sys/fs/fuse/connections/ available before returning from its initializatoin function. We cannot work around that in userspace, sorry.

Closing hence. Please file a bug against the kernel.

**Comment by mbiebl** [comment]
@poettering before going on and filing a bug report against the kernel, can you give me some pointers (say kernel documentation) which confirm that this behaviour is a kernel bug.
Maybe we are making assumpitions which we shouldn't make.

**Comment by mbiebl** [comment]
I've filed https://bugzilla.kernel.org/show_bug.cgi?id=187421 fwiw.

**Comment by mbiebl** [comment]
In case, anyone else runs into this issue. I've applied the following hack until the kernel bug is fixed
/etc/udev/rules.d/60-fuse.rules

```
# Workaround until https://bugzilla.kernel.org/show_bug.cgi?id=187421 is fixed
ACTION=="add", SUBSYSTEM=="module", KERNEL=="fuse", RUN+="/bin/sleep .5"
```

**Comment by JDuchniewicz** [comment]
This looks like race condition. Out of nowhere (after updating to 242) I started to get a lot of such problems.
```
⟩ uname -a
Linux archie 5.1.3-arch1-1-ARCH #1 SMP PREEMPT Thu May 16 20:59:36 UTC 2019 x86_64 GNU/Linux

⟩ systemctl --version
systemd 242 (242.29-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```
