### ISSUE TITLE
Inconsistencies between 'systemctl show' output and  /etc/systemd/system.conf

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4576]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>systemd 231
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem
I found one inconsistency but there may be more:  **DefaultTimeoutStopUSec** option in the output of _systemctl show_ and  **DefaultTimeoutStopSec** in the file _/etc/systemd/system.conf_.

**Comment by poettering** [comment]
"systemctl show" is decidedly more low-level than the configuration file, and that's because it just shows the normalized, low-level unit properties exported on the bus.

Internally, we only handle time in microseconds units, and the bus property shows that.

So, this is really on purpose, and not a bug.

**Comment by evverx** [comment]
@poettering , well, `man systemctl` says:

> Show properties of one or more units, jobs, or the manager itself. If no argument is specified, properties of the manager will be shown

It doesn't say

> Show the normalized, low-level unit properties exported on the bus

And this issue looks like a documentation bug

**Comment by poettering** [comment]
> And this issue looks like a documentation bug

ok, I added an issue for this now in #4654 so that we don't forget to extend the docs on this.
