### ISSUE TITLE
systemd not picking up plugged mapper device

### ISSUE THREAD

**Issue by dasJ** [systemd/systemd#4577]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>231 (initrd)

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> When a LUKS device is decrypted with systemd, `systemd-cryptsetup@devname.service` and `dev-mapper-devname.device` should become active and the device should be found at `/dev/mapper/devname`.

### In case of bug report: Unexpected behaviour you saw

> systemd actually activated the service and the device file is found, but the device unit is still inactive.

### In case of bug report: Steps to reproduce the problem

> Try to unlock a cryptsetup device in initrd where other units depend on the device unit.

**Comment by dasJ** [comment]
Oh, `udevadm info /dev/mapper/devname` shows that it has the `systemd` tag.

**Comment by poettering** [comment]
this usually indicates problems with the devicemapper udev rules, but those are out of focus for systemd itself. They use the SYSTEMD_READY udev property (which systemd looks for) to make the device unavailable for systemd.

Not sure what we can do about this, please contact your downstream distro or the cryptsetup maintainers for help. Sorry

**Comment by dasJ** [comment]
@poettering I finally traced it down the problem to a udev rule found in this repository: https://github.com/systemd/systemd/blob/dd8352659c9428b196706d04399eec106a8917ed/rules/99-systemd.rules.in#L18

My keystore doesn't have a filesystemd and I understand why this rule exists.
So do you recommend removing/altering this rule or do you just recommend me to override it?

**Comment by poettering** [comment]
@dasJ you could drop in your own rules file, that is ordered befor 99-systemd.rules and simply sets ID_FS_USAGE="other" or so, so that the rule systemd ships doesn't take effect...
