### ISSUE TITLE
Multiseat is not working after upgrade of systemd from 215-17 to 220-7

### ISSUE THREAD

**Issue by abiuan** [systemd/systemd#458]
I have a machine with 2 nvidia graphic cards, configured as multiseat, with 2 seats.
Debian version is testing (stretch). I use nouveau driver for nvidia cards.
The output of "loginctl seat-status seat1" is normal.

seat1
         Devices:
                  ├─/sys/devices/pci0000:00/0000:00:07.0/0000:03:00.0/drm/card1
                  │ [MASTER] drm:card1
                  │ ├─/sys/devices/pci0000:00/0000:00:07.0/0000:03:00.0/drm/card1/card1-DP-2
                  │ │ [MASTER] drm:card1-DP-2
                  │ └─/sys/devices/pci0000:00/0000:00:07.0/0000:03:00.0/drm/card1/card1-DVI-I-2
                  │   [MASTER] drm:card1-DVI-I-2
                  ├─/sys/devices/pci0000:00/0000:00:07.0/0000:03:00.0/graphics/fb1
                  │ [MASTER] graphics:fb1 "nouveaufb"
                  └─/sys/devices/pci0000:00/0000:00:1d.1/usb6
                    usb:usb6
                    ├─/sys/devices/pci0000:00/0000:00:1d.1/usb6/6-1/6-1:1.0/0003:04B3:3025.0003/input/input27
                    │ input:input27 "LITE-ON Technology USB NetVista Full Width Keyboard."
                    └─/sys/devices/pci0000:00/0000:00:1d.1/usb6/6-2/6-2:1.0/0003:045E:0040.0004/input/input28
                      input:input28 "Microsoft Microsoft 3-Button Mouse with IntelliEye(TM)"

During an upgrade of Debian, systemd was updated from version 215-17 to
220-7. After that multiseat stopped working.
X server for seat1 is not started.
Using keyboard on seat1 affects seat0. The mouse does not have this behaviour.
Downgrade to 215-17 is a nightmare due too many dependencies.

I tried:
- loginctl flush-devices and the loginctl attach to redo multiseat
  configuration
- move of keyboard and mouse on another usb ports
- change of display manager (from gdm3 to lightdm)
- upgrade of systemd and udev to 221-1 from unstable
- search on internet for known bugs or anomalies

**Comment by poettering** [comment]
Well, systemd/udev just maintain a list of seat assignments for each device, that's all. The x server then uses this information to actually put something on screen. if "loginctl seat-status" show the right seat device-to-seat assignments, than all should be good for systemd's/udev's side, since that really just shows the udev data.

WHich means this is somewhere between X and gdm. Please ask them for help.

Sorry we can't help you in systemd upstream.

**Comment by mbiebl** [comment]
@poettering apparently there were changes in logind though which broke the users setup between v215 and v220/v221. Any idea what that could be?

If gdm and X need changes, what changes would that be?

**Comment by poettering** [comment]
@mbiebl "users setup"? what do you mean?

I don't see what could have changed. If the "loginctl seat-status" info shows the right assignments, then everything should be good. X uses the assignments to figure otu which devices to open, but it opens them on its own.

Consider checking the X and gdm logs for details.

**Comment by mbiebl** [comment]
@poettering  user = @abiuan 
Apparently he had a working setup with v215 and that regressed with v220/v221.

**Comment by poettering** [comment]
@abiuan did you update anything else at the same time?

what do the X or gdm logs say about this, when this happened?

**Comment by abiuan** [comment]
I have to check. The computer is (turned off) at work therefore I'm
unable to do anything.
Monday I will try to find the "guilty".

Regards

**Comment by abiuan** [comment]
I checked the log and I found:
libwayland updated from 1.7.0-2 to 1.8.1-1
gdm updated from 3.14.1-7 to 3.14.1-8.

Therefore the best suspected is libwayland. I already opened a debian bug
for that package.

Thanks

Best regards

**Comment by mbiebl** [comment]
@abiuan Have you tried downgrading libwayland back to 1.7.0-2 and checked if that works with v220/v221?
