### ISSUE TITLE
TEST-03-JOBS fails sometimes

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#4582]
https://github.com/systemd/systemd/pull/4483#issuecomment-257954540

```
Nov 02 09:24:55 systemd-testsuite test-jobs.sh[164]: + START_SEC=1478078695
Nov 02 09:24:55 systemd-testsuite test-jobs.sh[164]: + systemctl start --wait wait2.service
Nov 02 09:24:59 systemd-testsuite test-jobs.sh[164]: ++ date -u +%s
Nov 02 09:24:59 systemd-testsuite test-jobs.sh[164]: + END_SEC=1478078699
Nov 02 09:24:59 systemd-testsuite test-jobs.sh[164]: + ELAPSED=4
Nov 02 09:24:59 systemd-testsuite test-jobs.sh[164]: + [[ 4 -ge 2 ]]
Nov 02 09:24:59 systemd-testsuite test-jobs.sh[164]: + [[ 4 -le 3 ]]
Nov 02 09:24:59 systemd-testsuite test-jobs.sh[164]: + exit 1
```

**Comment by martinpitt** [comment]
Yep, on my list for next week.

**Comment by martinpitt** [comment]
When I wrote this I originally intended to use sub-second precision. But floating point arithmetic in shell is downright impossible, and I don't think it's worth to invoke something as heavy as python or perl for that.

This could happen if the start happens at an "unlucky" time such as 1000.9 seconds -- if it then runs for 2.6 s (sleep 2 plus the overhead of starting the unit and waiting for it) the END_SEC would be 1003.5s which would again round to 1004, making the difference 4. I don't hit this locally, but on the more busy openstack VMs the overhead apparently can take a bit more than 0.5s. The main point is really that it doesn't wait that much longer, so `-le 4` seems perfectly fine. We allow up to 1.5s in the "wait5fail" test below as well.

**Comment by evverx** [comment]
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20161209_061610_5f4b5@/log.gz
```
Dec 09 06:06:28 systemd-testsuite sh[68]: + systemctl poweroff --no-block
Dec 09 06:06:28 systemd-testsuite test-jobs.sh[27]: + END_SEC=1481263588
Dec 09 06:06:28 systemd-testsuite test-jobs.sh[27]: + ELAPSED=10
Dec 09 06:06:28 systemd-testsuite test-jobs.sh[27]: + [[ 10 -ge 5 ]]
Dec 09 06:06:28 systemd-testsuite test-jobs.sh[27]: + [[ 10 -le 7 ]]
Dec 09 06:06:28 systemd-testsuite test-jobs.sh[27]: + exit 1
```

**Comment by evverx** [comment]
I haven't seen any failures for a long time, so I suppose the issue should be closed.
