### ISSUE TITLE
systemd not mounting PrivateTmp if process is chrooted

### ISSUE THREAD

**Issue by danielniccoli** [systemd/systemd#4587]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 215
> +PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR

### Used distribution

> Debian 8.6

### Expected behaviour you didn't see

/var/www/site1/tmp should have been mounted to /tmp/systemd-private-*-php5-fpm.service-*/

### Unexpected behaviour you saw

Option 4a: /var/www/site1/tmp is a regular folder
Option 4b: /var/www/site1/tmp is mounted to (non-private) /tmp

### Default PHP5-FPM Unit for Debian 8

```
[Unit]
Description=The PHP FastCGI Process Manager
After=network.target

[Service]
Type=notify
PIDFile=/var/run/php5-fpm.pid
ExecStartPre=/usr/lib/php5/php5-fpm-checkconf
ExecStart=/usr/sbin/php5-fpm --nodaemonize --fpm-config /etc/php5/fpm/php-fpm.conf
ExecReload=/bin/kill -USR2 $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

### Steps to reproduce the problem

1. Install php5-fpm
2. Add a pool /etc/php5/fpm/pool.d/site1.conf
3. In the site1.conf, set `chroot = /var/www/site1`
4. Prepare tmp directory (a or b)
  a. `mkdir /var/www/site1/tmp`
  b. `mkdir /var/www/site1/tmp && mount --bind /tmp /var/www/site1/tmp`
5. Add PrivateTmp=true to the service file.
6. `systemctl daemon-reload && service php5-fpm restart`

In words: `PrivateTmp=true` is working as long as you don't chroot php5-fpm.

As soon as you chroot php5-fpm into any directory, whether you bind-mount /tmp into the the chrooted directory or not, it is not working as I would expect it to work.

When /tmp is mounted into the chroot (as in option a), the process will see the contents of /tmp instead of /tmp/systed-private-*-php5-fpm.service-*/ despite the folder being present.

If I do not mount /tmp into the chroot (as in option b), the tmp directory within the chroot is a regular folder.

**Comment by falconindy** [comment]
You haven't posted the php5-fpm unit, so this is just a guess... You aren't asking systemd to perform the chroot, so this seems like an order of operations issue. The PrivateTmp exists for the service, but it isn't accessible because you've chrooted away from it. By binding /tmp into /var/www/site1/tmp _before_ the service starts, you get the real /tmp and not the bind mounted privatetmp from the mount namespace that systemd creates during service startup.

**Comment by Borkason** [comment]
Thanks for clearing this up. It makes sense to me now.

**Comment by evverx** [comment]
Well, I think we can reword the description a bit: "RootDirectory fails maybe on some or all options that create a mount namespace"

See https://github.com/systemd/systemd/pull/4533#issuecomment-258327773

```
-bash-4.3# systemctl cat hola --no-pager
# /etc/systemd/system/hola.service
[Service]
ExecStart=/busybox id
RootDirectory=/chroot
PrivateTmp=yes

-bash-4.3# journalctl -b -u hola --no-pager
-- Logs begin at Fri 2016-11-04 04:38:23 UTC, end at Fri 2016-11-04 04:40:07 UTC. --
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Trying to enqueue job hola.service/start/replace
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Installed new job hola.service/start as 194
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Enqueued job hola.service/start as 194
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Passing 0 fds to service
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: About to execute: /busybox id
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Forked /busybox as 197
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Changed dead -> running
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Job hola.service/start finished, result=done
Nov 04 04:40:06 systemd-testsuite systemd[1]: Started hola.service.
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Child 197 belongs to hola.service
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Main process exited, code=exited, status=226/NAMESPACE
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Changed running -> failed
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Unit entered failed state.
Nov 04 04:40:06 systemd-testsuite systemd[1]: hola.service: Failed with result 'exit-code'.
```

**Comment by evverx** [comment]
I think I should file a new issue :-)
There is https://github.com/systemd/systemd/issues/4567. But that's about `chase_symlinks`
