### ISSUE TITLE
/etc/resolv.conf sym-linked to incorrect file

### ISSUE THREAD

**Issue by cvmiller** [systemd/systemd#4589]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> after deleting  /etc/resolv.conf  and rebooting, /etc/resolv.conf was recreated but was **not** linked to /run/systemd/resolve/resolv.conf

### In case of bug report: Unexpected behaviour you saw

> /etc/resolv.conf was linked to /usr/lib/systemd/resolv.conf

### In case of bug report: Steps to reproduce the problem

1. boot system
2. ```rm /etc/resolv.conf```
3. reboot system
4. ```ln -l /etc/resolv.conf```

/usr/lib/systemd/resolv.conf is **never** updated with DHCP/RDNSS information. Therefore the DNS resolution can become broken (e.g. in an IPv6-only network, where there is no IPv4 connectivity, resolved will not work when pointed at 127.0.0.53, the default value of /usr/lib/systemd/resolv.conf)

The daemon which repopulates /etc/resolv.conf at boot, should point to the dynamic file: /run/systemd/resolve/resolv.conf

**Comment by grawity** [comment]
resolved isn't _pointed_ at 127.0.0.53 – resolved _listens on_ 127.0.0.53.

In other words, this new default configuration is intended to make other programs (ones which directly use DNS) go through the local systemd-resolved daemon, which provides local caching – similar to e.g. having a local unbound or dnsmasq.

These defaults are applied via tmpfiles.d, and only when resolv.conf is missing.

**Comment by cvmiller** [comment]
You are correct. It is listening. However this still results in a broken DNS situation if the host is in an IPv6-only network. resolved with the line `nameserver 127.0.0.53` will not resolve on an IPv6-only network.

And the correct resolution information is in /run/systemd/resolve/resolv.conf, which will **not** be used since tmpfiles.d doesn't create the sym-link to it.

**Comment by keszybz** [comment]
What addresses are available on the external network is irrelevant for the loopback interface. Local programs should be able to communicate with 127.0.0.53 through loopback. Then, systemd-resolved will communicate with the nameservers using IPv4 or IPv6, depending on what is configured.

**Comment by cvmiller** [comment]
Sounds reasonable. However, what nameservers will systemd-resolved communicate with if /etc/resolv.conf has the line `nameserver 127.0.0.53`? Are there hard coded name servers in systemd-resolved? If not, then I don't see where systemd-resolved knows where to connect?

**Comment by keszybz** [comment]
It gets this data from networkd (DNS=, etc.). It does not use `resolv.conf`.
