### ISSUE TITLE
[RFE] Add ConditionSystemLoad unit file conditional

### ISSUE THREAD

**Issue by sgallagher** [systemd/systemd#4604]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 25 x86_64

I would like to be able to conditionalize certain timer units based on the load currently on the system. For example, I might want to schedule a filesystem TRIM at a time that *usually* experiences low system load, but I'd like to be able to detect an atypical load and skip it.

(Other examples could include a backup routine or scheduling a reboot for applying queued package updates).

**Comment by poettering** [comment]
uh, oh, i can't say I like second guessing the kernel's own CPU scheduler like this...

**Comment by sgallagher** [comment]
It's not really about CPU scheduling. Perhaps I chose a bad example when I mentioned TRIM. My original use-case was: "I want to apply pending patches on the first Tuesday of the month at 2am, which I know is usually a low-traffic time, except that if we're dealing with high load, I'll skip it (and run it manually later)"

**Comment by poettering** [comment]
Exists these days with ConditionCPUPressure=.
