### ISSUE TITLE
[232 regression] systemd-nspawn --help or --version exits with nonzero

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#4605]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian, Ubuntu

```
$ systemd-nspawn --version ; echo $?
systemd 231
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
0

# systemd-nspawn --version ; echo $?
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
1
```

Same for --help. This breaks things like rkt (https://bugs.debian.org/843509).

I'll look at this later tonight.

**Comment by martinpitt** [comment]
This was introduced in commit b006762524, this part:

```
-        int r, n_fd_passed, loop_nr = -1;
+        int r, n_fd_passed, loop_nr = -1, ret = EXIT_FAILURE;
         char veth_name[IFNAMSIZ] = "";
         bool secondary = false, remove_subvol = false;
-        sigset_t mask_chld;
         pid_t pid = 0;
-        int ret = EXIT_SUCCESS;
```

In 

```
       r = parse_argv(argc, argv);
        if (r <= 0)
                goto finish;
```

we immediately jump to the end, which never changes the default `ret = EXIT_FAILURE`, which causes this bug. @keszybz , was this a deliberate change to robustify some logic, or just an oops? If it was deliberate, how about making `parse_argv()` return a special exit code for "handled internally, exit successfully" (for `--version` and `--help`) or even make it `exit(EXIT_SUCCESS)` by itself?

We had regressions of exit codes before, so as soon as this is fixed, I'll commit these new tests to make sure they stay sane: http://paste.ubuntu.com/23443600/

**Comment by keszybz** [comment]
No, not on purpose obviously. Thanks for tracking this down.
