### ISSUE TITLE
Systemd-networkd zerconf doesn't work

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#4623]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

229

### In case of bug report: Expected behaviour you didn't see

Zero conf address should have been configured.

### In case of bug report: Unexpected behaviour you saw

Zero Config IP was not configured.

### In case of bug report: Steps to reproduce the problem

  1) in (/etc/systemd/network/.network) file, configure the DHCP=yes and LinkLocalAddressing=yes.
  2) In the local network there should not be any dhcp server
  3) Reboot the system/network
  4) Expectation was as there is no dhcp server in the network then system should have been configured with zero configured address.

**Comment by ratagupt** [comment]
Can somebody help in how to do the zero conf through systemd-networkd?
LinkLocalAddressing=yes/ipv4 in network section works for me but it doesn't work with DHCP..

**Comment by poettering** [comment]
note that we only track issues with the two most recent systemd versions here, which currently means 231+232...

That said, please provide your exact .network file, and what "networkctl status -a" reports. Thanks!

**Comment by poettering** [comment]
Clsoing due to lack of response.

**Comment by ratagupt** [comment]
HI lennart,Sorry for the delayed response,I didn't responded as earlier we were using the old systemd version,But Still with the systemd 232 version,I can see that zeroconf still doesn't work.

networkctl status -a
● 1: lo
       Link File: /lib/systemd/network/99-default.link
    Network File: n/a
            Type: loopback
           State: carrier (unmanaged)
         Address: 127.0.0.1
                  ::1

[[0;1;32m●[[0m 2: eth0
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/00-abc-eth0.network
            Type: ether
           State: [[0;1;32mroutable[[0m ([[0;1;32mconfigured[[0m)
            Path: platform-1e660000.ethernet
          Driver: ftgmac100
      HW Address: 70:e2:84:14:20:72
         Address: 9.3.185.164
                  fe80::72e2:84ff:fe14:2072
         Gateway: 9.3.185.1

systemctl --version 
systemd 232

cat /etc/systemd/network/00-abc-eth0.network
[Match]
Name=eth0
[Network]
DHCP=yes
LinkLocalAddressing=yes

**Comment by ratagupt** [comment]
Hi Lennart,seems with systemd 232 it is working fine.

**Comment by ratagupt** [comment]
is it expected that zeroconf address will allways be there,even though Interface is configured with static/Dynamic address?

**Comment by poettering** [comment]
yes, ipv4ll may be used in parallel to any static address. This is similar to ipv6ll where the addresses are all used in parallel too.
