### ISSUE TITLE
Make it possbile to have more than SOMAXCONN (128) pending connections on a socket unit

### ISSUE THREAD

**Issue by phako** [systemd/systemd#4629]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with
origin on 225, confirmed on master

When configuring a socket service, the default backlog of its listen() call is set to SOMAXCONN which is hard-coded to 128. This hard limit has been removed for quite some time now and is configurable with net.ipv4.tcp_max_syn_backlog and/or net.core.somaxconn. And unfortunately, sometimes 128 just isn't enough.

**Comment by lucaswerkmeister** [comment]
Can’t you change this with the `Backlog=` option on the `.socket` unit?

**Comment by phako** [comment]
Whoops. Blind. I'll double check but that should be it

**Comment by poettering** [comment]
We make no restrictions on `Backlog=`. You should be able to set anything there you like, including any value > 128...

Closing.

**Comment by phako** [comment]
Just for clarification: I still have to bump the net.core.somaxconn value somewhere, right?

**Comment by poettering** [comment]
@phako don't know, please try and report back!

**Comment by phako** [comment]
Confirmed. It is clamped to that value by the kernel in [./net/socket.c:1391 (4.9-rc4)](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/net/socket.c?id=refs/tags/v4.9-rc5#n1391)
Default is set to SOMAXCONN (from [./include/linux/socket.h:257](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/linux/socket.h?id=refs/tags/v4.9-rc5#n256)) in[ ./net/core/sysctl_net_core.c:433](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/net/core/sysctl_net_core.c?id=refs/tags/v4.9-rc5#n429)
