### ISSUE TITLE
Wrong default for --enable-bzip2 or wrong help text, inconsistent with other options

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4636]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian unstable

### In case of bug report: Unexpected behaviour you saw

The ./configure --help output prints
```
  --disable-xz            Disable optional XZ support
  --disable-zlib          Disable optional ZLIB support
  --enable-bzip2          Enable optional BZIP2 support
  --disable-lz4           Disable optional LZ4 support
 ```

This suggests, that XZ, zlib and lz4 support are enabled by default and can be disabled, whereas BZIP2 support is disabled and needs to be enabled explicitly.

Looking at configure.ac though, BZIP2 is handled exactly like the other options, i.e. defaults to yes.

Either this default should be changed, or the help text.

**Comment by poettering** [comment]
yeah, we should reverse the option, and make it behave exactlylike the others.

**Comment by mbiebl** [comment]
Ok, will prep a patch for that.

While at it, I see, that we don't use capitalization consistently

```
  --disable-apparmor      Disable optional AppArmor support
  --disable-adm-group     disable adm group
  --disable-wheel-group   disable wheel group
  --disable-xz            Disable optional XZ support
  --disable-zlib          Disable optional ZLIB support
```

Do you want all upper or lowercase?

**Comment by mbiebl** [comment]
fwiw, configure's own options seem to be all lower case, so for consistencies sake we should probably follow that

**Comment by poettering** [comment]
i prefer uppercase, but if configure's own options use lowercase, that's fine too.
