### ISSUE TITLE
kdbus: exchange full

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#464]
Looks like kdbus is responsible for this, I am not sure though. Happens from time to time on kdbus-enabled system, have not seen it without.

systemctl and other systemd-tool just give "Exchange full" messages:

```
root@git01 ~ # systemctl reboot
Failed to start reboot.target: Exchange full
```

And journal reports the same for pam_systemd

```
sshd[23357]: pam_unix(sshd:session): session opened for user git by (uid=0)
sshd[23357]: pam_systemd(sshd:session): Failed to create session: Exchange full
```

**Comment by zonque** [comment]
This is a kdbus issue, yes. What happens is that the pool of the receiver of a message runs full, either because too many messages are received in a short period of time, or because messages remain in the pool that should be freed. It could also mean the sender is issuing a sync reply request but can't receive the answer, for similar reasons.

Do you happen to see any pattern in when that occurs?

**Comment by eworm-de** [comment]
Not sure what the exact cause is. This happens on a git server with lots of simultaneous ssh connections (via sshd.socket). The repositories are managed by gitolite, but I do not think this matters, no?

**Comment by dvdhrm** [comment]
This looks like a memory-leak of sd_bus_message somewhere in libsystemd (and as such, it does not free the pool memory). Especially the fact that it only happens for systemd services (which are native), and not for proxies is a bit suspicious.

How long does your machine run for you to hit these errors?
What distribution are you on?
Any other special setup?
(and the obligatory: which kdbus tree and systemd version?)

If you're used to "valgrind", you might give it a try for logind (or PID1, but logind seems easier).

**Comment by eworm-de** [comment]
I hit this twice yesterday. Not sure about the exact time it needs to trigger after a reboot.

This is with Arch Linux, [systemd 221-2](https://www.archlinux.org/packages/core/x86_64/systemd/) and Linux 4.1.1 with kdbus from Greg's char-misc tree (last commit is b69af624).

Currently I am back on legacy dbus as this server is in use...

**Comment by dvdhrm** [comment]
This is now fixed by: https://github.com/systemd/systemd/commit/0c9cc10dcca6cc260b293c2732e7a4833280272e

Thanks!
