### ISSUE TITLE
systemd-boot ordering incorrect for debian kernel versioning

### ISSUE THREAD

**Issue by sjoerd-ccu** [systemd/systemd#4641]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Debian unstable

### In case of bug report: Expected behaviour you didn't see

Kernels are ordered based on their version and the latest is selected by defualt

### In case of bug report: Unexpected behaviour you saw
My system has the following versions (form the loader snippets):

version    4.8.0-1-amd64
version    4.8.0-2-amd64
version    4.8.0-rc5-amd64
version    4.8.0-rc8-amd64
version    4.8.0-trunk-amd64

systemd-boot orders them in this order as well, meaning the rc kernels will be picked up before the release kernels. The same goes for -trunk, which in the debian kernel versioning are experimental.

I don't know what e.g. fedora does with their kernel versioning, but it seems we might need to either tune the version that ends up in the boot snippets or change the systemd-boot ordering so it just works.

**Comment by poettering** [comment]
but isn't debian's naming a bit weird here?

**Comment by sjoerd-ccu** [comment]
Not for me, but i'm used to it :p 

In any case that versioning policy of debian is unlikely to change, so we either have to tweak the systemd-boot ordering or tweak the calls to kernel-install from the debian side to adjust the naming to make sd-boot happy.

**Comment by poettering** [comment]
iirc, the version sorting algorithm used by sd-boot originates in debian actually. @msekletar, @kaysievers might now more. The code is here:

https://github.com/systemd/systemd/blob/master/src/boot/efi/boot.c#L871

**Comment by medhefgo** [comment]
Version sorting (and selection) have changed recently. I now get this order (highest to lowest priority):
```
version 4.8.0-2-amd64
version 4.8.0-1-amd64
version 4.8.0-trunk-amd64
version 4.8.0-rc8-amd64
version 4.8.0-rc5-amd64
```

**Comment by keszybz** [comment]
The order listed by @medhefgo seems correct and expected.

I don't think there's anything to do here on our side. I'm cleaning up the sorting algorithm and its description in #23504, but the changes in that pull request doesn't impact the cases here. Segments with letters compare lower to segments with numbers. The algorithm we implement is generic, and we can't have special support for things like "-trunk" or "-rc".  `~` and `^` are supported for pre- and post-releases, and those should be used if appropriate to get the appropriate ordering. (I'd expect something like `4.8.0~rc5-`1, `4.8.0~rc8-`1, `4.8.0-1`, `4.8.0-2` here.) It is up to the packagers to provide the appropriate version string, e.g. with `-Dversion-tag=`.
