### ISSUE TITLE
Systemd-232: Peer network connection is broken

### ISSUE THREAD

**Issue by ReubenM** [systemd/systemd#4644]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Gentoo

### In case of bug report: Unexpected behaviour you saw

After updating to systemd-232, a direct peer network connection between two computers no longer works.

The .network file from computer A:
```
[Match]
MACAddress=00:1f:5b:33:bc:69

[Link]
MTUBytes=9000

[Network]
Address=192.168.16.9/24

[Address]
Address=192.168.16.9
Peer=192.168.16.8
```

Corresponding .network file from computer B:
```
[Match]
MACAddress=00:1f:5b:33:70:11

[Link]
MTUBytes=9000

[Network]
Address=192.168.16.8/24

[Address]
Address=192.168.16.8
Peer=192.168.16.9
```

The links are on both machines are up with addresses assigned, but the addresses of the peer does not respond (e.g. I cannot ping the peer interface, by name or by IP address)

After downgrading back to systemd-231 the peer connection resumes expected functionality.

**Comment by poettering** [comment]
@ssahani any chance you can look into this?

**Comment by ReubenM** [comment]
I just noticed that under 232 the link has NOARP set.

I added

```
ARP=yes
```

to the link section and that seems to have fixed the issue.

**Comment by ssahani** [comment]
I am not able to reproduce this able to ping.  

```
2: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:40:aa:db brd ff:ff:ff:ff:ff:ff
    inet 10.65.193.147 peer 10.65.193.182/8 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet 10.65.193.147/23 brd 10.65.193.255 scope global dynamic enp0s8
       valid_lft 86399sec preferred_lft 86399sec
    inet6 fe80::a00:27ff:fe40:aadb/64 scope link 
       valid_lft forever preferred_lft forever
[root@Max1 network]# ping 10.65.193.182
PING 10.65.193.182 (10.65.193.182) 56(84) bytes of data.
64 bytes from 10.65.193.182: icmp_seq=1 ttl=64 time=0.520 ms
64 bytes from 10.65.193.182: icmp_seq=2 ttl=64 time=0.304 ms
64 bytes from 10.65.193.182: icmp_seq=3 ttl=64 time=0.301 ms
64 bytes from 10.65.193.182: icmp_seq=4 ttl=64 time=0.672 ms
64 bytes from 10.65.193.182: icmp_seq=5 ttl=64 time=0.300 ms
```

```
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:a0:2d:76 brd ff:ff:ff:ff:ff:ff
    inet 10.65.193.182 peer 10.65.193.147/8 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet 10.65.193.182/23 brd 10.65.193.255 scope global dynamic enp0s3
       valid_lft 85648sec preferred_lft 85648sec
    inet6 fe80::a00:27ff:fea0:2d76/64 scope link 
       valid_lft forever preferred_lft forever
sus@Max network $ ping 10.65.193.147
PING 10.65.193.147 (10.65.193.147) 56(84) bytes of data.
64 bytes from 10.65.193.147: icmp_seq=1 ttl=64 time=0.187 ms
64 bytes from 10.65.193.147: icmp_seq=2 ttl=64 time=0.294 ms
```

`ARP=`  should not matter as it's only used if this being set. Defaults to unset.

**Comment by ReubenM** [comment]
Without the ARP=yes I get the following for the interface:

```
3: enp7s0f1: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1f:5b:33:bc:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.16.9/24 brd 192.168.16.255 scope global enp7s0f1
       valid_lft forever preferred_lft forever
    inet6 fe80::21f:5bff:fe33:bc69/64 scope link 
       valid_lft forever preferred_lft forever
```

So, I noticed that this lists a broadcast address rather than a peer address. I was wondering if perhaps it was because I set a 24bit mask in the address line, but removing it didn't change anything. (I also changed everything to 32bit mask, but I don't think that matters here.) So I removed the network section completely. That helped a little by showing the peer address rather than broadcast address. But I still can't connect to the peer without setting ARP=yes

Current network.conf:

```
[Match]
MACAddress=00:1f:5b:33:bc:69

[Link]
MTUBytes=9000
ARP=yes

[Address]
Address=192.168.16.9/32
Peer=192.168.16.8/32

[Route]
Destination=192.168.16.8/32
Scope=link
Gateway=192.168.16.8
```

ip addr:

```
3: enp7s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1f:5b:33:bc:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.16.9 peer 192.168.16.8/32 scope global enp7s0f1
       valid_lft forever preferred_lft forever
    inet6 fe80::21f:5bff:fe33:bc69/64 scope link 
       valid_lft forever preferred_lft forever
```

I remove ARP=yes I can't connect. I also noticed the scope is still set to global even though I set it to link, for whatever that is worth.

If I can provide any other info let me know.

**Comment by maikzumstrull** [comment]
Same thing here, Debian system. Package updated to systemd 232-3 and network stopped working because the interface gets set NOARP.

I enabled debug logging for networkd and it says:

```
enp4s0: Flags change: +NOARP
```

but I see no indication in the log why it thought it should do that.

Removing the [Link] section from my network file entirely works as well as adding ARP=yes.

I guess in some cases it mistakenly defaults to ARP=no instead of "don't touch"?

**Comment by ssahani** [comment]
Ok got it . `config_parse_iec_size` overwrites the next variable that is `ARP` when MTUBytes is set.
