### ISSUE TITLE
networkd fails to set transient hostname

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#4646]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian

While investigating issue #4504 and what would break when networkd starts before D-Bus, I noticed that the only reason why networkd currently runs after `dbus.service` is setting a transient hostname received through DHCP. But this doesn't actually seem to work: When DHCP does send a hostname, networkd says
```
systemd-networkd[516]: ens3: Could not set hostname: Interactive authentication required.
```
Presumably because networkd drops its privileges to user `systemd-network` and the polkit policy of hostnamed only allows root to change the host name.

FTR, I reproduced this in QEMU with `-net nic,model=virtio -net user,hostname=fizzy` which will send a hostname along with DHCP.

Fixing this should go along with actually testing this in `test/networkd-test.py`, as this is quite a subtle problem that isn't obvious when reviewing PRs for privilege reduction.

**Comment by poettering** [comment]
i figure adding the "systemd-network" user to the default PK file should be relatively easy. At least for folks who grok PK policy well, which I don't ;-)

**Comment by martinpitt** [comment]
Confirming that this works if you set `<allow_any>yes</allow_any>` for `org.freedesktop.hostname1.set-hostname` in `/usr/share/polkit-1/actions/org.freedesktop.hostname1.policy` (this is of course only for testing). `*.policy` files don't have a syntax for "also grant this policy to Unix users, that's where the pklocalauthority(8) files come in -- and unfortunately there's _two_ formats around: the old ini-style declarative ones (`Identity=systemd-network\nAction=org.freedesktop.hostname1.set-hostname\nResultAny=yes`) and the "free-form JavaScript" ones from newer polkits. IMNSHO these have been a ridiculously bad idea for several reasons and Debian/Ubuntu never got those, but Fedora did. So we could auto-detect the available polkit version during package build, or ship both files and the distro picks, or we provide a `./configure` switch for those.

**Comment by martinpitt** [comment]
https://github.com/martinpitt/systemd/commit/a3ccebcca fixes this with both the pkla-based and JS rules based polkit. I think we should just ship both, as (1) they don't really get into each other's way, (2) there is no sensible build-time detection for it, and (3) the user may upgrade polkit at runtime.

I will write a test case for this before I post a PR.

**Comment by keszybz** [comment]
Agreed.

**Comment by dachshund-digital** [comment]
This issue is back in Debian 9 (Stretch).  Just enabled network configuration via systemd-networkd in Debian 9,6 and Raspbian (Pi) OS, and this breaks DHCP host-name option use.   This should not happen, DHCP provided host-name should be honored by ANY network configuration method.  It works under interfaces use, dhcpcd use, etc.  Only systemd-networkd is broken it appears.

# systemctl --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Comment by yuwata** [comment]
I have not catch your issue yet, but if the issue still exists in a recent version, then please file this as a new issue. Otherwise, we easily forget your comment, as this page is already closed.
When you file a new issue, please provide your configs and relevant logs.
Thank you.
