### ISSUE TITLE
/etc/resolv.conf handling in nspawn is now broken

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#4649]
Since #4622 ordering between nspawn and resolved is required. And we really shouldn't have this. See discussion in that PR

**Comment by eworm-de** [comment]
All this is broken since 3539724c. `/usr/lib/systemd/resolv.conf` exists if `systemd-resolved` has been started any time.

**Comment by eworm-de** [comment]
Issue #4595 is related.

**Comment by poettering** [comment]
@eworm-de well, the change i made with that commit just says: if resolved is enabled, use its resolv.conf thus relying on activation to make it available any time.

**Comment by fsateler** [comment]
@poettering `/usr/lib/systemd/resolv.conf` exists != `systemd-resolved` enabled. For example, debian installs `systemd-resolved` in the main `systemd` package but does not enable it by default.

**Comment by keszybz** [comment]
True, there's a race. OTOH, not everybody enables resolved, so the check wasn't enough: it'd return true if systemd-resolved is installed at all, which we know at compile time, but which doesn't mean that'll be actually running.

Maybe nspawn units should get an ordering after systemd-resolved.service? Or maybe we make a systemd-resolved-domain.socket and order nspawn after it and have it check it is active before doing the bind-mount?

**Comment by poettering** [comment]
Hmm, so i wasn't aware that resolved is something we permit enabling off. In that case I think we should probably do the following:

1. check if the resolved bus name is active or activatable on the bus
2. order nspawn@.service after resolved (for now at least)

I think checking the bus name is the best option, as in the long run it permits both activatable and non-activatable scenarios, and bus names are cleaned up automatically (in contrast to /run/systemd/resolv.conf) when the service goes away.

**Comment by poettering** [comment]
Ah, grmbl, the dbus thing won't work, as we install the dbus .service file for it unconditionally, hence the name will always appear activatable, even if it isn't supposed to be... I figure I'll leave the access() based check in then.

**Comment by poettering** [comment]
ah, nah, I think it would still be better to check whether resolved's name is active then the access() based check, since that automatically is cleaned up...

**Comment by poettering** [comment]
OK, my proposal to resolve this is waiting in #5369.
