### ISSUE TITLE
After upgrading to systemd 232, IPv4 TCP segmentation offload is disabled by default

### ISSUE THREAD

**Issue by mamarley** [systemd/systemd#4650]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Ubuntu 17.04 Zesty

### In case of bug report: Unexpected behaviour you saw

> After upgrading to systemd 232, IPv4 TCP segmentation offload ("tso" in ethtool) is disabled by default.  This was previously enabled by default in the e1000e driver, among others.  Downgrading udev (the "udev" and "libudev1" packages) back to 231 works around the problem.  Also, the value can still be adjusted using the "ethtool -K <dev> tso on" command.

### In case of bug report: Steps to reproduce the problem

> Upgrade to systemd 232 on a system with an e1000e card or another card with a driver that enables TSO by default.  Check to see that TSO is now disabled by default instead.

**Comment by mamarley** [comment]
I expect this issue may be caused by https://github.com/systemd/systemd/commit/50725d10e3417fd357abe1df2f177b8458027ac7, but I don't understand the code well enough to be sure.

**Comment by poettering** [comment]
@ssahani can you please look into this?

**Comment by maksqwe** [comment]
I think https://github.com/systemd/systemd/pull/4639 fix is related to this issue.

**Comment by poettering** [comment]
Fixed by #4639.
