### ISSUE TITLE
systemd under systemd-nspawn waits for already defunct processes with grsec kernel

### ISSUE THREAD

**Issue by svvac** [systemd/systemd#4653]
### Environment
Running a nested systemd using `systemd-nspawn`. The container is pristine, freshly pacstrapped and updated.
```
# systemctl --version
systemd 231                                                         
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
# hostnamectl
   Static hostname: n/a
Transient hostname: test
         Icon name: computer-container
           Chassis: container
    Virtualization: systemd-nspawn
  Operating System: Arch Linux
            Kernel: Linux 4.8.7.201611102210-1-grsec
      Architecture: x86-64
```

The container was started using:

    /usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=%i

Host info:

```
# systemctl --version
systemd 231
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
# hostnamectl
   Static hostname: host
         Icon name: computer-server
           Chassis: server
  Operating System: Arch Linux
            Kernel: Linux 4.8.7.201611102210-1-grsec
      Architecture: x86-64
```

### Issue
I'm trying to run postfix in the container. After installation, I can start `postfix.service` and it runs, but issuing `systemctl stop postfix.service` hangs until the tasks times out.

Looking at the process tree, postfix has shut down and its processes are gone. However, `systemctl status` reports waiting on the (already defunct) master PID.

Starting and stopping postfix by hand goes smoothly, suggesting that perhaps systemd has missed the process termination event somehow and will then wait until the timeout garbages the unit.

`systemctl kill postfix` reports: `Failed to kill unit postfix.service: No such process`.

I could not reproduce the behaviour on the host.

**Comment by poettering** [comment]
hmmm, you are using a grsec kernel. Is this also an issue if you use a normal kernel?

**Comment by svvac** [comment]
No it isn't.

**Comment by poettering** [comment]
how does postfix.service look like on the system in your container?

**Comment by svvac** [comment]
```
# systemctl cat postfix
# /usr/lib/systemd/system/postfix.service
[Unit]                       
Description=Postfix Mail Transport Agent
After=network.target

[Service]                       
Type=forking
PIDFile=/var/spool/postfix/pid/master.pid
ExecStart=/usr/bin/postfix start
ExecStop=/usr/bin/postfix stop
ExecReload=/usr/bin/postfix reload
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by poettering** [comment]
is "/var/spool/postfix/pid/master.pid" really the right PID file? while running, does "systemctl status postfix" actually show the right process a main PID?

**Comment by svvac** [comment]
Yes. `PIDFile`, `systemctl status` and `postfix status` all agree on the PID. It appears in the process tree until `systemctl stop postfix` is called. At that point it exits correctly, but systemd is still waiting.

**Comment by svvac** [comment]
I may have found a clue. When `ls -al /`, we can see all dirs below `/` are owned by `root`, except for `/proc` which is owned by `65634`, which seems to be an UID outside of the user namespace attributed to the container. For the host, the dir in `/var/lib/machines` is owned by `1091698688`.

Also, I don't know if it's relevant, but since `/proc` is a mountpoint, `mount` errors may be related. `systemctl --failed` lists `dev-hugepages.mount`, for which the journal gives simply `mount[11]: mount: permission denied`

`mount` reports the following for `/proc`:

```
# mount | grep proc
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys/net type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /proc/sys/kernel/random/boot_id type tmpfs (ro,nosuid,nodev,mode=755,uid=1091698688,gid=1091698688)
tmpfs on /proc/kmsg type tmpfs (rw,nosuid,nodev,mode=755,uid=1091698688,gid=1091698688)
```

**Comment by svvac** [comment]
Continuing the investigation, I ruled out the `hidepid=2` mount option on the host's `/proc`.

Obviously, chowning and remounting `/proc` in the containers fails with insufficient permissions.

**Comment by svvac** [comment]
Did further testing. Removing the `ExecStop` directive from the unit file changes nothing. The postfix master process still gets killed (directly by systemd this time I guess), and the unit still waits for the process to die even though it's gone already.

```
Nov 22 15:18:13 arch-mail-2 postfix/master[123]: terminating on signal 15
Nov 22 15:18:13 arch-mail-2 systemd[1]: Stopping Postfix Mail Transport Agent...
-- Subject: Unit postfix.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postfix.service has begun shutting down.
Nov 22 15:19:44 arch-mail-2 systemd[1]: postfix.service: State 'stop-sigterm' timed out. Killing.
Nov 22 15:19:44 arch-mail-2 systemd[1]: postfix.service: Killing process 123 (n/a) with signal SIGKILL.
Nov 22 15:21:14 arch-mail-2 systemd[1]: postfix.service: Processes still around after SIGKILL. Ignoring.
Nov 22 15:22:44 arch-mail-2 systemd[1]: postfix.service: State 'stop-final-sigterm' timed out. Killing.
Nov 22 15:22:44 arch-mail-2 systemd[1]: postfix.service: Killing process 123 (n/a) with signal SIGKILL.
Nov 22 15:24:14 arch-mail-2 systemd[1]: postfix.service: Processes still around after final SIGKILL. Entering failed mode.
Nov 22 15:24:14 arch-mail-2 systemd[1]: Stopped Postfix Mail Transport Agent.
-- Subject: Unit postfix.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postfix.service has finished shutting down.
Nov 22 15:24:14 arch-mail-2 systemd[1]: postfix.service: Unit entered failed state.
Nov 22 15:24:14 arch-mail-2 systemd[1]: postfix.service: Failed with result 'timeout'.
```

The logs seem to indicate that the process dies *before* `Unit postfix.service has begun shutting down.`...

Also, `KillMode=process` changes nothing.

**Comment by svvac** [comment]
BTW, any pointers on how to speed-up the timeout for the unit so that testing becomes bearable?

**Comment by svvac** [comment]
I think we can rule out user namespacing after all. Starting a fresh container without `-U` (and hence without the `/proc` ownership mismatch) doesn't fix the problem. Same behavior occurs.

So we're back at square 1 I guess.

**Comment by svvac** [comment]
@poettering Is there anything else (tests, configs, whatnot) I may provide?

**Comment by poettering** [comment]
could you provide the relevant output of "systemct show postfix.service" before you issue "systemctl stop" on the unit. Then run this a second time, but when systemd is hanging.

Also, please turn on debug logging when doing all this.

And please run this on a vanilla kernel, nothing with grsec or anything like that please.

**Comment by svvac** [comment]
Well, the problem *is* with grsec. Could not reproduce with a vanilla linux...

To recap:
```
 KERNEL     POSTFIX    STATUS
========  ===========  ======
vanilla   host         OK
vanilla   container    OK
grsec     host         OK
grsec     container    HANGS
```

**Comment by svvac** [comment]
Also how do I tell my nspawned systemd to spit debug output?

```
Connected to machine arch-test-1. Press ^] three times within 1s to exit session.
[root@arch-test-1 ~]# systemctl status postfix 
* postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@arch-test-1 ~]# systemctl start postfix
[root@arch-test-1 ~]# systemctl status postfix
* postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-11-30 10:05:38 CET; 7s ago
  Process: 47 ExecStart=/usr/bin/postfix start (code=exited, status=0/SUCCESS)
 Main PID: 113 (master)
   CGroup: /machine.slice/systemd-nspawn@arch-test-1.service/system.slice/postfix.service
           |-113 /usr/lib/postfix/bin/master -w
           |-114 pickup -l -t unix -u
           `-115 qmgr -l -t unix -u

Nov 30 10:05:37 arch-test-1 systemd[1]: Starting Postfix Mail Transport Agent...
Nov 30 10:05:38 arch-test-1 postfix/master[113]: daemon started -- version 3.1.3, configuration /etc/postfix
Nov 30 10:05:38 arch-test-1 systemd[1]: Started Postfix Mail Transport Agent.
[root@arch-test-1 ~]# postfix status
postfix/postfix-script: the Postfix mail system is running: PID: 113
[root@arch-test-1 ~]# systemctl stop postfix
^C
[root@arch-test-1 ~]# systemctl status postfix
* postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; disabled; vendor preset: disabled)
   Active: deactivating (stop-sigterm) since Wed 2016-11-30 10:06:22 CET; 13s ago
  Process: 130 ExecStop=/usr/bin/postfix stop (code=exited, status=0/SUCCESS)
  Process: 47 ExecStart=/usr/bin/postfix start (code=exited, status=0/SUCCESS)
 Main PID: 113
   CGroup: /machine.slice/systemd-nspawn@arch-test-1.service/system.slice/postfix.service

Nov 30 10:05:37 arch-test-1 systemd[1]: Starting Postfix Mail Transport Agent...
Nov 30 10:05:38 arch-test-1 postfix/master[113]: daemon started -- version 3.1.3, configuration /etc/postfix
Nov 30 10:05:38 arch-test-1 systemd[1]: Started Postfix Mail Transport Agent.
Nov 30 10:06:22 arch-test-1 systemd[1]: Stopping Postfix Mail Transport Agent...
[root@arch-test-1 ~]# postfix status 
postfix/postfix-script: the Postfix mail system is not running
[root@arch-test-1 ~]# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0  52936  6576 ?        Ss   10:05   0:00 /usr/lib/systemd/systemd
root        14  0.0  0.0  52616  9992 ?        Ss   10:05   0:00 /usr/lib/systemd/systemd-journald
root        20  0.0  0.0  38436  4532 ?        Ss   10:05   0:00 /usr/lib/systemd/systemd-logind
dbus        21  0.0  0.0  32880  3108 ?        Ss   10:05   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --
systemd+    22  0.0  0.0  40728  3880 ?        Ss   10:05   0:00 /usr/lib/systemd/systemd-networkd
systemd+    28  0.0  0.0  38548  3972 ?        Ss   10:05   0:00 /usr/lib/systemd/systemd-resolved
root        31  0.0  0.0   6332  1560 console  Ss+  10:05   0:00 /sbin/agetty --noclear --keep-baud console 115200,38400,9600 vt220
root        37  0.0  0.0  14180  3352 pts/0    Ss   10:05   0:00 -bin/sh
root        42  0.0  0.0 104588  1524 pts/0    S    10:05   0:00  \_ (sd-
root       161  0.0  0.0  32848  2740 pts/0    R+   10:07   0:00  \_ ps faux
root        38  0.0  0.0  52412  5888 ?        Ss   10:05   0:00 /usr/lib/systemd/systemd --user
root        39  0.0  0.0  98408  1488 ?        S    10:05   0:00  \_ (sd-pam)
```

**Comment by poettering** [comment]
Ah, so thisis grsec after all. I figure you need to work with the grsec folks then. If you have trouble with an out-of-tree kernel patch we don't really consider that a systemd project. Closing hence. I hope that makes sense.

> Also how do I tell my nspawned systemd to spit debug output?

Set `$SYSTEMD_LOG_LEVEL=debug` to turn on debug logging for nspawn itself. Add `systemd.log_level=debug` to the nspawn command line to turn on debug logging for PID 1 in the container. (this is basically how you pass "kernel command line arguments" to nspawn in a container).

**Comment by svvac** [comment]
It does make sense, but I have to admit I fail to see why the grsec patches would screw systemd's ability to see if a process is dead. Other programs' process control capabilities don't seem to be impacted in any way, so my initial guess would be some corner-case in systemd. Especially since it works correctly with other daemons.

Of course that would just be a wild guess, I ain't competent enough on the matter to say.

For reference, I have reported the bug [upstream](https://forums.grsecurity.net/viewtopic.php?f=3&t=4623)

(PS: that bug being grsec-specific was my first answer to you ;—)

**Comment by poettering** [comment]
Ah... i misread your first answer... no idea how grsec breaks SIGCHLD handling in containers... that's something to ask the grsec folks. Maybe they  added some extra protection in pid namespaces or so. But i can only guess. Something to discuss with the grsec folks
