### ISSUE TITLE
Gaps in systemd-cgtop data regarding distccd.service

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#4657]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231

### Used distribution

> Arch x86_64

### In case of bug report: Expected behaviour you didn't see

> I would expect systemd-cgtop to show the the corresponding CPU and memory load for all `distccd.service` loads like `htop` or `uptime` do, but  `systemd-cgtop` shows nothing at all.  I have modified `/usr/lib/systemd/system/distccd.service` to contain `CPUAccounting=1 MemoryAccounting=1 BlockIOAccounting=1` under the "Unit" section.

```% systemd-cgtop
Control Group                                                                            Tasks   %CPU   Memory  Input/s Output/s
/                                                                                            -      -   269.3M        -        -
/init.scope                                                                                  1      -        -        -        -
/system.slice                                                                               32      -        -        -        -
/system.slice/cronie.service                                                                 1      -        -        -        -
/system.slice/dbus.service                                                                   1      -        -        -        -
/system.slice/distccd.service                                                               23      -        -        -        -
/system.slice/gpm.service                                                                    1      -        -        -        -
/system.slice/smartd.service                                                                 1      -        -        -        -
/system.slice/sshd.service                                                                   1      -        -        -        -
/system.slice/system-getty.slice                                                             1      -        -        -        -
/system.slice/system-getty.slice/getty@tty1.service                                          1      -        -        -        -
/system.slice/systemd-journald.service                                                       1      -        -        -        -
/system.slice/systemd-logind.service                                                         1      -        -        -        -
/system.slice/systemd-networkd.service                                                       1      -        -        -        -
/system.slice/systemd-resolved.service                                                       1      -        -        -        -
/system.slice/systemd-timesyncd.service                                                      2      -        -        -        -
/system.slice/systemd-udevd.service                                                          1      -        -        -        -
/user.slice                                                                                  7      -        -        -        -
/user.slice/user-1000.slice                                                                  7      -        -        -        -
/user.slice/user-1000.slice/session-c1.scope                                                 5      -        -        -        -
/user.slice/user-1000.slice/user@1000.service                                                2      -        -        -        -
```
However:
```
% cat /proc/loadavg
3.79 3.80 3.55 5/125 23136
```

### In case of bug report: Unexpected behaviour you saw

> No output for CPU or memory is given for `distccd.service`

### In case of bug report: Steps to reproduce the problem

> Simply run `distccd.service` and feed it work to do while inspecting the output of `htop` and of `systemd-cgtop` to observe the disconnect.  As mentioned in `man systemd-cgtop` and `man systemd.resource-control` I think the upstream provided services needs to be modified to enable the resource usage as I described above.

**Comment by poettering** [comment]
do you have the memory andcpu cgroup controllers turned on in your kernel? have you properly reloaded systemd's config after setting CPUAccounting=1 for distccd.service?

Usually you'd just call "systemctl set-property distccd.service CPUAccount=1" and be done with it (which does all this automatically, and needs no further commands).

Do you see the "memory" and "cpu" cgroup hierarchies mounted in the "mount" command?

Are you using cgroupsv2 or cgroupsv1? (if you don't know you are using cgroupsv1)

What does "systemd-cgls memory:/" output?

**Comment by graysky2** [comment]
> do you have the memory andcpu cgroup controllers turned on in your kernel? 

I am running the stock Arch Linux kernel [config here](https://git.archlinux.org/svntogit/packages.git/tree/trunk/config.x86_64?h=packages/linux).

>  have you properly reloaded systemd's config after setting CPUAccounting=1 for distccd.service?

Yes, I ran `systemctl daemon-reload` after modifying distccd.service.

> Do you see the "memory" and "cpu" cgroup hierarchies mounted in the "mount" command?

Yes:

```
% mount | grep cgroup
...
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
...
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
...
```

> Are you using cgroupsv2 or cgroupsv1? (if you don't know you are using cgroupsv1)

No idea so probably v1 :grin:

> What does "systemd-cgls memory:/" output?

```
Controller memory; Control group /:
├─   1 /sbin/init
├─ 191 /usr/lib/systemd/systemd-journald
├─ 223 /usr/lib/systemd/systemd-udevd
├─ 419 /usr/lib/systemd/systemd-timesyncd
├─ 422 /usr/sbin/rpc.idmapd
├─ 425 /usr/bin/crond -n
├─ 428 /usr/lib/systemd/systemd-logind
├─ 430 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
├─ 436 /usr/lib/systemd/systemd-networkd
├─ 437 /usr/bin/gssproxy -D
├─ 453 /usr/bin/sshd -D
├─ 459 /usr/lib/systemd/systemd-resolved
├─ 461 /sbin/agetty --noclear tty1 linux
├─ 463 /usr/sbin/rpc.statd --no-notify
├─ 464 /usr/bin/rpcbind -w
├─ 466 /usr/sbin/rpc.mountd
├─ 539 /usr/sbin/mysqld
├─ 594 /usr/lib/polkit-1/polkitd --no-debug
├─ 669 sshd: facade [priv]
├─ 671 /usr/lib/systemd/systemd --user
├─ 672 (sd-pam)
├─ 676 sshd: facade@pts/0
├─ 677 -zsh
├─1728 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─1730 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─1732 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─1736 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─1737 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─2579 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─2637 /usr/bin/distccd --no-detach --daemon --allow 10.0.0.93/24 --log-level warn --log-file /tmp/distccd.log
├─2641 systemd-cgls memory:/
└─2642 less
```

**Comment by graysky2** [comment]
> Usually you'd just call "systemctl set-property distccd.service CPUAccount=1" and be done with it (which does all this automatically, and needs no further commands).

Now this is interesting... if I run the following, then reload daemon, the output of systemd-cgtop is as expected with distccd displaying CPU load.

```
# systemctl set-property distccd.service CPUAccounting=1
```

1) Where does systemd store the setting?  It did not modify `/usr/lib/systemd/system/distccd.service`
2) Why doesn't hard-coding the setting into the service unit not give the expected behavior?

EDIT: Here is the service unit in full:

```
[Unit]
Description=A distributed C/C++ compiler
Documentation=man:distccd(1)
After=network.target
CPUAccounting=1
MemoryAccounting=1
BlockIOAccounting=1

[Service]
User=nobody
EnvironmentFile=/etc/conf.d/distccd
ExecStart=/usr/bin/distccd --no-detach --daemon $DISTCC_ARGS

[Install]
WantedBy=multi-user.target
```

**Comment by candlerb** [comment]
> 1. Where does systemd store the setting? It did not modify /usr/lib/systemd/system/distccd.service

Look under `/etc/systemd/system/distccd.service.d/`. You should see files like
`/etc/systemd/system/distccd.service.d/50-MemoryAccounting.conf` etc.

(Aside: there is also `systemctl edit distccd.service` which lets you create a config snippet to override parts of the unit file. This is stored in `/etc/systemd/system/distccd.service.d/override.conf`)

> 2. Why doesn't hard-coding the setting into the service unit not give the expected behavior?

I believe the settings need to go under `[Service]` rather than `[Unit]`, as you'll see if you cat those settings files:

~~~
[Service]
MemoryAccounting=yes
~~~

systemd is not very good about warning about unknown or misspelled settings. For example, if you write `[service]` instead of `[Service]` then the whole section is silently ignored.

**Comment by poettering** [comment]
> For example, if you write [service] instead of [Service] then the whole section is silently ignored.

That's not actually true. We'll log about it to syslog.

**Comment by poettering** [comment]
Closing, as memory accounting simply wasn#t enabled for the service in quetsion.
