### ISSUE TITLE
systemd-nspawn -x flag not working with raw images

### ISSUE THREAD

**Issue by wlipa** [systemd/systemd#4664]
On Ubuntu 16.10, with systemd 231, the -x flag is not working properly with raw image containers.  They are not actually ephemeral, but no error message is seen.  Additionally, some leftovers are kept in /tmp, even though the nspawn completes successfully.

Create the raw image:

    $ sudo machinectl pull-raw https://cloud-images.ubuntu.com/releases/16.10/release/ubuntu-16.10-server-cloudimg-amd64.img ubuntu-16.10
    $ machinectl list-images
    NAME         TYPE RO  USAGE CREATED MODIFIED
    ubuntu-16.10 raw  no  1.0G  n/a     Sun 2016-11-13 09:07:21 PST

Nothing in /tmp much:

    $ ls /tmp
    ssh-bKx7pVrzFj

List contents of container.

    $ sudo systemd-nspawn -x -M ubuntu-16.10 ls
    Spawning container ubuntu-16.10 on /var/lib/machines/ubuntu-16.10.raw.
    Press ^] three times within 1s to kill container.
    bin   dev  home        lib    lost+found  mnt  proc  run   snap  sys  usr  vmlinuz
    boot  etc  initrd.img  lib64  media	  opt  root  sbin  srv	 tmp  var
    Container ubuntu-16.10 exited successfully.

See if we can leave a file around.

    $ sudo systemd-nspawn -x -M ubuntu-16.10 touch wombat
    Spawning container ubuntu-16.10 on /var/lib/machines/ubuntu-16.10.raw.
    Press ^] three times within 1s to kill container.

    Container ubuntu-16.10 exited successfully.

The 'wombat' file is kept despite the -x flag.

    $ sudo systemd-nspawn -x -M ubuntu-16.10 ls
    Spawning container ubuntu-16.10 on /var/lib/machines/ubuntu-16.10.raw.
    Press ^] three times within 1s to kill container.
    bin   dev  home        lib    lost+found  mnt  proc  run   snap  sys  usr  vmlinuz
    boot  etc  initrd.img  lib64  media	  opt  root  sbin  srv	 tmp  var  wombat
    Container ubuntu-16.10 exited successfully.

And there's some junk leftover in the host /tmp.

    $ ls /tmp
    nspawn-root-aXNOnq  nspawn-root-v3DZnL  nspawn-root-WyZ1Uq  ssh-bKx7pVrzFj

Original thread at https://lists.freedesktop.org/archives/systemd-devel/2016-November/037699.html

**Comment by wlipa** [comment]
Here's the btrfs volume info:

```
$ sudo btrfs filesystem show /var/lib/machines
Label: none  uuid: 7747283c-fd9b-49da-bf2b-4ac3f06a22f2
    Total devices 1 FS bytes used 1.05GiB
    devid    1 size 4.00GiB used 2.05GiB path /dev/loop0
```

**Comment by poettering** [comment]
So as it turns out nspawn so far actually didn't support --ephemeral with disk images at all. All it supported was the switch with --directory=. However, there was a bug that if the image wasn't explicitly configured with --directory= but only discovered via --machine= then we wouldn't notice that and not complain, but simply ignore --ephemeral.

**Comment by poettering** [comment]
I now prepped PR #4693 which adds support for ephemeral snapshots of disk images, too.
