### ISSUE TITLE
turn on unified cgroups by default again, and add configure switch for it

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#4669]
Don't turn the unified cgroups stuff on and of every second version. Instead, leave it on for good (as that's the future), but add a configure switch so that it is easy for distros to turn it off if they desire to do so.

This is an issue to block v233 until this is properly fixed.

**Comment by poettering** [comment]
(this is a follow-up for #4628 btw)

**Comment by evverx** [comment]
> add a configure switch so that it is easy for distros to turn it off if they desire to do so

@poettering , just to be sure. Is this about https://github.com/systemd/systemd/pull/4368 ?
