### ISSUE TITLE
TEST RUN: https://github.com/systemd/systemd/issues/2467 [FAILED]

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#4672]
Environment:
```
$ nc --version
Ncat: Version 7.12 ( https://nmap.org/ncat )

$ cat /proc/version
Linux version 4.8.6-201.fc24.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 6.2.1 20160916 (Red Hat 6.2.1-2) (GCC) ) #1 SMP Thu Nov 3 14:38:57 UTC 2016
```
(`TEST-10-ISSUE-2467` fails on Xenial too https://github.com/systemd/systemd/pull/4395#issuecomment-260545707)
```sh
$ cd test/TEST-10-ISSUE-2467
$ sudo make run
...
-rw-r-----+ 1 root systemd-journal 4845568 Nov 14 15:35 /var/tmp/systemd-test.7KDeGd/journal/6563ddb26aab4db7ab43ca46f7ce3301/system.journal
TEST RUN: https://github.com/systemd/systemd/issues/2467 [FAILED]
Makefile:10: recipe for target 'run' failed
make: *** [run] Error 1

$ sudo journalctl -u testsuite -D /var/tmp/systemd-test.7KDeGd/journal/6563ddb26aab4db7ab43ca46f7ce3301

-- Logs begin at Mon 2016-11-14 15:34:28 UTC, end at Mon 2016-11-14 15:35:03 UTC. --
Nov 14 15:34:49 systemd-testsuite sh[189]: + rm -f /tmp/nonexistent
Nov 14 15:34:50 systemd-testsuite sh[189]: + systemctl start test.socket
Nov 14 15:34:49 systemd-testsuite systemd[1]: testsuite.service: Passing 0 fds to service
Nov 14 15:34:49 systemd-testsuite systemd[1]: testsuite.service: About to execute: /bin/sh -e -x -c 'rm -f /tmp/nonexistent; systemctl start test.socket; echo a | nc -U /run/test.ctl; >/testok'
Nov 14 15:34:49 systemd-testsuite systemd[1]: testsuite.service: Forked /bin/sh as 189
Nov 14 15:34:49 systemd-testsuite systemd[1]: testsuite.service: Changed dead -> start
Nov 14 15:34:49 systemd-testsuite systemd[1]: Starting Testsuite service...
Nov 14 15:34:49 systemd-testsuite systemd[189]: testsuite.service: Executing: /bin/sh -e -x -c 'rm -f /tmp/nonexistent; systemctl start test.socket; echo a | nc -U /run/test.ctl; >/testok'
Nov 14 15:34:51 systemd-testsuite sh[189]: + echo a
Nov 14 15:34:51 systemd-testsuite sh[189]: + nc -U /run/test.ctl
Nov 14 15:34:53 systemd-testsuite sh[189]: Ncat: Connection reset by peer.
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: Child 189 belongs to testsuite.service
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: Main process exited, code=exited, status=1/FAILURE
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: Changed start -> failed
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: Job testsuite.service/start finished, result=failed
Nov 14 15:34:53 systemd-testsuite systemd[1]: Failed to start Testsuite service.
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: Unit entered failed state.
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: Failed with result 'exit-code'.
Nov 14 15:34:53 systemd-testsuite systemd[1]: testsuite.service: cgroup is empty
Nov 14 15:34:58 systemd-testsuite systemd[1]: testsuite.service: Failed to send unit remove signal for testsuite.service: Transport endpoint is not connected
```

`Ncat: Connection reset by peer.` is OK. We should ignore this.

**Comment by evverx** [comment]
Hm, I can't reproduce this on Xenial. But I use the `nc` from the `netcat-openbsd` package.
`nc` from the `netcat-traditional` fails, of course:

```
$ nc -U /run/test.ctl
nc: invalid option -- 'U'
nc -h for help
```

**Comment by martinpitt** [comment]
@evverx: FTR, the test uses `netcat-openbsd` (that's the only netcat variant in Ubuntu main, -traditional is unsupported in universe).

**Comment by evverx** [comment]
@martinpitt , good to know. Thanks!
But `netcat-openbsd` doesn't produce `Ncat: Connection reset by peer` (it simply returns `0`).
Hm, and I'm not sure why https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20161114_201202_06ec4@/log.gz

> TEST RUN: #2467 [FAILED]
> Makefile:8: recipe for target 'run' failed
> make: Leaving directory '/tmp/autopkgtest.Dw5D5f/build.zhW/systemd-debian/test/TEST-10-ISSUE-2467'

**Comment by evverx** [comment]
For the record. This test failed there https://github.com/systemd/systemd/pull/5225

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20170206_155949_9f0fe@/log.gz
```
TEST RUN: https://github.com/systemd/systemd/issues/2467 [FAILED]
Makefile:8: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.SFzKtH/build.eZP/debian/test/TEST-10-ISSUE-2467'
```

**Comment by Siosm** [comment]
I'm trying to replace OpenBSD nc by socat in this test. So far I'm able to make this test pass but I'm not sure that the test will fail properly. Do you have any idea about how I should test for failure?

**Comment by evverx** [comment]
Thanks for working on this.

I think the simplest way is to add [`TriggerLimitIntervalSec=0 or TriggerLimitBurst=0`](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#TriggerLimitIntervalSec=) to `test.socket` temporarily so that the activation of `test.service` will take longer than 10 seconds.

**Comment by evverx** [comment]
The test apparently stopped testing what it is supposed to test when 9b45c2bf02a43e3e1b42de1ab0c3fe29c64dc5f5 was merged.

**Comment by evverx** [comment]
`nc` is no longer used there so I suppose the issue can be closed.
