### ISSUE TITLE
systemd-shutdown failed to finalize filesystem

### ISSUE THREAD

**Issue by i5um41ru** [systemd/systemd#4673]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

> ...

### In case of bug report: Unexpected behaviour you saw

> ![20161115_131243](https://cloud.githubusercontent.com/assets/8899813/20295068/b717c64e-ab3d-11e6-8043-c84219dc3eb7.jpg)

### In case of bug report: Steps to reproduce the problem

> this happen after doing fresh install ubuntu 16.04 on Acer Aspire E 11. This happen when shutting down, and the system stuck on there, can't `Ctrl` + `Alt` + `Del` alias hang.

**Comment by poettering** [comment]
Please note that we only track bus in the two most recentupstream versions upstream. In older versions and cases like yours please contact your distro of choice who maintain this downstream. Thank you!
