### ISSUE TITLE
About ".../dev/ should be an empty directory"

### ISSUE THREAD

**Issue by safinaskar** [systemd/systemd#4676]
- [x] Bug report

### systemd version the issue has been seen with

> 232

Please, change this:

".../dev/ should be an empty directory"

to something like this:

"error: ../dev/ is mounted and it is not empty"

Rationale here: https://github.com/systemd/systemd/issues/3695#issuecomment-258689000 (and see previous discussion).

**Comment by poettering** [comment]
Fix waiting in #4971
