### ISSUE TITLE
machinectl does not honour drop-ins for machines whose name contains a hyphen

### ISSUE THREAD

**Issue by aeneby** [systemd/systemd#4677]
AFAICT this is a bug, and a regression, since it used to work (e.g. in systemd 225 and possibly later) but no longer does (e.g. in systemd 231 and possibly earlier). This brokenness was seen in CoreOS beta 1192.2.0:

`# systemctl edit $(systemd-escape --template=systemd-nspawn@.service 'machine-name')`

As expected, this drops me to an editor where I can create my drop-in override for the machine "machine-name" (`systemd-nspawn@machine-name.service`). Doing so results in the file `/etc/systemd/system/systemd-nspawn@machine\x2dname.service.d/override.conf` being created, which seems correct so far.

`# machinectl start machine-name`

This results in the machine being started, but without the overrides in effect. I would expect the drop-in to take effect when starting a machine like this. Instead, to start the machine with the drop-in, one must start the machine using `systemctl`:

`# systemctl start $(systemd-escape --template=systemd-nspawn@.service 'machine-name')`

Removing the hyphen from the machine name resolves the issue. Unsure if there are other characters which have the same effect when used in the machine's name.

**Comment by evverx** [comment]
There are two related PRs:
https://github.com/systemd/systemd/pull/2752 - Don't escape the name of the container nspawn service (v230)
https://github.com/systemd/systemd/pull/3554 - machinectl: do not escape the unit name (v231)

@eliasp , please take a look

**Comment by eliasp** [comment]
Citing Lennart in #3554:

> indeed, "systemd-nspawn@.service" uses "%i" to reference the machine name, which means it doesn't unescape it. And there's no reason to escape it really, as the valid machine names are a subset of what is allowed in the instance part of unit names.

So the question to @aeneby is: why use `systemd-escape` for the machine name in the 1st place instead of simply concatenating `systemd-nspawn@` and `machine-name`? This just causes your file to be named `systemd-nspawn@machine\x2dname.service.d/override.conf` instead of `systemd-nspawn@machine-name.service.d/override.conf`.
Are there any cases where a machine name contains a value which would need to be escaped?

**Comment by aeneby** [comment]
I guess the issue here is that, somewhere along the line, `systemd-nspawn@.service` went from using `--machine=%I` to `--machine=%i` in its service definition (and probably some related changes to escaping behaviour). This means that nspawn overrides written for earlier versions of systemd won't work when transferred to versions which incorporate these changes.

But, if this is expected behaviour, then I suppose it is not a bug and I will just have to update my overrides. Thanks for the clarification, feel free to close the issue.

**Comment by keszybz** [comment]
Yeah, this was a backwards incompatible change. But it was a while ago, so at this point we should just tell people to update if they hit this, to late to add any workarounds.
