### ISSUE TITLE
DHCPv6 option 39 Client FQDN not sent

### ISSUE THREAD

**Issue by Qowy** [systemd/systemd#4682]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ArchLinux ARM

### In case of bug report: Expected behaviour you didn't see

> A DHCPv6 request should contain option 39 Client FQDN

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> I have a DHCPv6 server and the Router advertisements have both the O and M flag set.
systemd-networkd correctly requests an IPv6 address from the server (and successfully receives one).
The eth0.network file contains DHCP=yes and IPv6AcceptRA=yes (but this seems irrelevant since DHCPv6 is obviously working and according to https://www.freedesktop.org/software/systemd/man/systemd.network.html I can't find something that would be explicitly needed to send the FQDN)

DHCPv6 Request from my Linux machine:
![image](https://cloud.githubusercontent.com/assets/18251934/20375653/c097024a-ac80-11e6-89f2-c18a5d6e2633.png)

DHCPv6 Request from (for example) a Windows client:
![image](https://cloud.githubusercontent.com/assets/18251934/20375694/06a6119a-ac81-11e6-91b7-4f46a41b0b3d.png)

**Comment by poettering** [comment]
So, what is your hostname precisely?

Note that we do not send any hostname at all if it is unset or "localhost" (or a flavour thereof). Also, we do not send the FQDN field at all, if the hostname consists of a single label only (in which case we set the traditional hostname field instead).

Hence, what is the precise contents of /proc/sys/kernel/hostname for you?

**Comment by Qowy** [comment]
```
[marco@pi-tv-marco ~]$ cat /proc/sys/kernel/hostname
pi-tv-marco.home.qowy.de
```

**Comment by Qowy** [comment]
Do you need anything else? (since it is still flagged as needs feedback)

**Comment by cvmiller** [comment]
+1, I see the same thing on my Arch Linux machine

[systemd_dhcp6.pcap.zip](https://github.com/systemd/systemd/files/677929/systemd_dhcp6.pcap.zip)

[root@alarm alarm]# cat /proc/sys/kernel/hostname
alarm

Please see attached pcap file of DHCP6 transaction

**Comment by Qowy** [comment]
pinging this one last time, just to know if the provided information is enough @poettering

**Comment by sanseihappa** [comment]
+1.  I see this with 231 also.  Furthermore, it seems that clients like dhcpcd _do_ send this and ultimately end up with DDNS AAAA record (at least, under Microsoft DHCP/DNS server), enabling addressing by hostname under IPv6.

**Comment by Qowy** [comment]
Update: Error seems to still be present in 232

Ubuntu 16.10 (with I think dhcpcd) working fine
Gentoo with also dhcpcd is also working

**Comment by martyg77** [comment]
Hello,  Just ran across this issue on 233, running Arch.

Is there a workaround I can apply on the client, or is it best just to tweak the DHCPv6 server?

How do you determine the default DUID sent to the server, short of breaking out tcpdump?
