### ISSUE TITLE
`coredumpctl list` should indicate when a coredump is being processed

### ISSUE THREAD

**Issue by pwithnall** [systemd/systemd#4685]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Debian derivative

### In case of bug report: Expected behaviour you didn't see

If I run `coredumpctl list` while `systemd-coredumpd` is being run to process a new crash, there is no indication in the list output that a new crash has happened but is not ready to view in `coredumpctl` yet. This is especially pronounced on slow hardware, where it can take several minutes to process a new core dump — and during those minutes I could be trying to debug the problem, and could be mislead by `coredumpctl list` not listing any crashes.

**Comment by keszybz** [comment]
We write the journald entry with all the data at the very end, so this way we won't learn anything useful. But we could simply list all `systemd-coredump@.service`s running. This should be pretty easy to implement!
