### ISSUE TITLE
The network interface inside of a container is called host0@ifX, not just host0.

### ISSUE THREAD

**Issue by fpqc** [systemd/systemd#4689]
### Submission type

  - [x] Bug report

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> host0 interface inside of the nspawn container simply named host0

### In case of bug report: Unexpected behaviour you saw

> host0 interface called host0@ifX, where X=4+n, where n is the number of times I have started and stopped a container

### In case of bug report: Steps to reproduce the problem

> Starting from a base install of Arch, create any tree for an nspawnable distro (one started with systemd) in `/var/lib/machines/containername`, and launch with 

`systemd-nspawn -M containername -b -n`

login as root, and type in 

`ip link show`

The link's name inside of the container is followed by an @ sign with an if number.  Since I'm trying to create a container out of a terrible and old distro that does not work well with networkd and uses init scripts, I need the name, at least inside the view of the container, to be exactly host0, or at least stable, rather than being regenerated on every reboot of the container.

Is this because the Arch kernel does not support user namespaces?

**Comment by poettering** [comment]
THis is a misunderstanding. It's simply how the "ip" tool shows information about the peer interface of a veth link. it normally shows "foo@bar" for them where "foo" refers to the local interface name, and "bar" to the other side of it. Now, in the context of containers "bar" is actually outside of the container namespace, in which case "ip" only can show the ifindex but not the actual name, as that is information that is not available inside the container about interfaces that are outside of it.

Hence, everythong is the way it should. Closing.

**Comment by fpqc** [comment]
Ah, thanks! Cheers, Lennart!  Could you add this to the documentation perhaps?
