### ISSUE TITLE
Detection of lz4 doesn't work anymore with lz4 1.7.3

### ISSUE THREAD

**Issue by bachp** [systemd/systemd#4690]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

> 231

### Used distribution

> NixOS

### In case of bug report: Expected behaviour you didn't see

> Systemd compiles with all lz4 versions >= 125

### In case of bug report: Unexpected behaviour you saw

> Systemd can't be compiled with version 1.7.3 (the successor of 131). Configures says that lz4 is not found.

The issue seems to be that lz4 changed their version schema from whole numbers to semantic versions.
This means this check: https://github.com/systemd/systemd/blob/master/configure.ac#L624 doesn't work properly anymore.

### In case of bug report: Steps to reproduce the problem

> Build against lz4

**Comment by poettering** [comment]
Oh, christ...
