### ISSUE TITLE
vconsole-setup not run properly

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#4699]
### Submission type

- [X] Bug report

### systemd version the issue has been seen with
232

### Used distribution
Arch

### In case of bug report: Expected behaviour you didn't see

initrd boot shows proper font after i915 driver loads.

### In case of bug report: Unexpected behaviour you saw

Proper font not set until well into post-initrd boot. Initrd console is nearly unreadable due to tiny font.

### In case of bug report: Steps to reproduce the problem

mkinitcpio with `i915` in `MODULES`.
The hooks I used were `systemd sd-encrypt sd-vconsole autodetect keyboard modconf block filesystems strip`.

mkinitcpio worked around this problem in the past by ordering `systemd-vconsole-setup.service` after `systemd-modules-load.service` and loading i915 using the latter. However, this does not work since v232 because `systemd-vconsole-setup.service` is no longer wanted by `sysinit.target`.

Maybe `systemd-vconsole-setup` doesn't get triggered correctly because i915 is loaded via systemd-modules-load instead of udev? Or maybe because it replaces the UEFI GOP fbcon instead of creating a new fbcon?

**Comment by poettering** [comment]
@msoltyspl hmm, any idea?

**Comment by mus65** [comment]
Probably related: on my Arch Linux system, the console keymap is not loaded anymore in early boot since v232. I noticed this because my password for the LUKS root device was not accepted anymore since my german keyboard layout was not loaded.

Similiar report by another Arch User: https://bbs.archlinux.org/viewtopic.php?id=219382

**Comment by msoltyspl** [comment]
Hmmm,

Neither in:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/initcpio-install-systemd?h=packages/systemd

nor in:

https://git.archlinux.org/mkinitcpio.git/tree/install/sd-vconsole

... I see any 90-vconsole.rules being added to the resulting initramfs image - and this one is needed for udev to actually act on vtconsole related events.

Could you double check if the mkinitpcio image generated on your arch has or hasn't that file ? In the (probably) latter case, could you add it and verify if it works fine ? If so, you will likely need to file the bug report against arch's systemd package (initcpio-install-systemd) and/or mkinitcpio (sd-vconsole).

For the record, systemd-vconsole-setup.service is no longer a dependency to anythying (and vice versa). It won't be started by any means other than manually by the user or internally by systemd (e.g. localectl).

(as an Arch user myself, I wish they stoped resisting dracut .... =) )

**Comment by heftig** [comment]
Thanks; I'm a bit embarrassed I missed the missing rule. With the rule it indeed works as expected. I've sent a patch to mkinitcpio.

(Because mkinitcpio is "good enough" it seems unlikely we'll add dracut—though that might change if dracut is demonstratively better or someone wants to maintain it.)
