### ISSUE TITLE
Adding support for a request to do a filesystem check at the next boot

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4700]
### Submission type

  - [ x ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Ubuntu 17.04 dev

It looks like systemd does not support the filesystem checks at boot if /forcefsck exists. Currently I'm wondering how it would be possible to request a one-time filesystem check at the next boot (for example without user interaction from a maintenance script out of tune2fs's count and interval cycles). Maybe a way to do this can be implemented.

**Comment by poettering** [comment]
Hmm? We do honour /forcefsck. That said. It's a very broken concept as you really shouldn't touch the fs that you want to check. After all if you want to check the root fs you have the suspicion that something is wrong with it, and then you better shouldn't write to it.

You can also request a forced fsck via the kernel cmdline option fsck.mode=force which is a much safer alternative.

**Comment by Sworddragon** [comment]
> Hmm? We do honour /forcefsck.

I have read at several locations systemd seems to doesn't and on creating this file and rebooting my system I'm not seeing any filesystem check (while this is the case with fsck.mode=force) and the booting speed is normal so I thought that the rumors are true. But the /forcefsck file is removed after the boot so I'm wondering what went wrong.


> That said. It's a very broken concept as you really shouldn't touch the fs that you want to check. After all if you want to check the root fs you have the suspicion that something is wrong with it, and then you better shouldn't write to it.

Indeed, writing to a filesystem that is assumed to be damaged should not be written to. But in this case I'm not assuming any damage but doing safety scans instead to fix potential unnoticed problems (bugs in specific components, race conditions, special cases, etc.) which is not more dangerous than using/writing to the filesystem in all other common ways if you do not assume any damage.
