### ISSUE TITLE
logind.conf(5) contains wrong default for KillUserProcesses if compiled using --without-kill-user-processes

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4705]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian

### In case of bug report: Unexpected behaviour you saw

If systemd is compiled using  --without-kill-user-processes, the logind.conf man page incorrectly states:
```
KillUserProcesses=
           Takes a boolean argument. Configures whether the processes of a
           user should be killed when the user logs out. If true, the scope
           unit corresponding to the session and all processes inside that
           scope will be terminated. If false, the scope is "abandoned", see
           systemd.scope(5), and processes are not killed. Defaults to "yes",
```

It should say no in this case

**Comment by poettering** [comment]
Well, we do not generate man pages dynamically, and I am pretty sure we shouldn't start to. We document the upstream defaults really, and have always. If we'd start generating man pages exposing the exact config set people enabled or disabled or configured at build time we go crazy.

If you care, then that's something to patch around downstream, but I am not convinced we should provide docs that don't match the upstream defaults.

Sorry.
