### ISSUE TITLE
systemctl disable --now fails for aliased D-Bus services

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4706]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian sid

### In case of bug report: Unexpected behaviour you saw
systemctl disable --now foo.service is supposed to stop and disable a
service (there is also an equivalent enable --now command).
I just tried that with firewalld and got:

```
# systemctl disable --now firewalld
Synchronizing state of firewalld.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install disable firewalld
insserv: warning: current start runlevel(s) (empty) of script `firewalld' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `firewalld' overrides LSB defaults (0 1 6).
Removed symlink /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
Failed to stop dbus-org.fedoraproject.FirewallD1.service: Unit dbus-org.fedoraproject.FirewallD1.service not loaded.
```

The firewalld service is not stopped as a result

firewalld.service has
```
[Install]
WantedBy=basic.target
Alias=dbus-org.fedoraproject.FirewallD1.service
```
systemd/systemctl seems to stop the service via the aliased name and we
remove the symlink beforehand. Seems to me, that systemctl should
actually try to stop firewalld.service, and not
dbus-org.fedoraproject.FirewallD1.service.

I first suspect that this might be caused by our downstream (Debian) systemd-sysv-install integration.
So I added ```exit 0``` to systemd-sysv-install, but the problem remained

```
# systemctl disable --now firewalld
Synchronizing state of firewalld.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable firewalld
Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
Failed to stop dbus-org.fedoraproject.FirewallD1.service: Unit dbus-org.fedoraproject.FirewallD1.service not loaded.
```

**Comment by fmitha** [comment]
Related or possible dupe: https://bugs.debian.org/870350

**Comment by mbiebl** [comment]
So, with v241 I just tried this again and `systemctl disable firewalld --now` works as expected.

What doesn't work is `systemctl disable dbus-org.fedoraproject.FirewallD1.service --now`, i.e. tryping `disable --now` with the aliased name. But this is less of an issue

**Comment by poettering** [comment]
Ok, let's close this. disabling via symlink is not supported and is unlikely to be, people should disable units by their primary name, since alias names are often managened by [Install] in the first place.
