### ISSUE TITLE
socket stays active even though its service cannot start (is masked)

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#4708]
This can be reproduced on Fedora 25, systemd-231-10.fc25.x86_64.

1. Make sure a socket and its service are both "active (running)":
    `systemctl start avahi-daemon.{socket,service}`
2. Mask only the service:
    `systemctl mask avahi-daemon.service`
3. Stop the service:
    `systemctl stop avahi-daemon.service`
4. Check the resulting statuses:
    `systemctl status avahi-daemon.{socket,service}`

#### Actual result
Though the service is now inactive, the socket unit is still "active (running)". This is an inconsistency.

#### Expected result
The socket should be at most "active (listening)", so it can go into "failed" by itself when a connection is attempted.

#### Additional info
I think the socket failed to notice the death of the service because socket_trigger_notify() returns early if the service's load state is UNIT_MASKED (!= UNIT_LOADED).

Original report: https://bugzilla.redhat.com/show_bug.cgi?id=1068542#c5

**Comment by poettering** [comment]
Fix waiting in #14527
