### ISSUE TITLE
nspawn fails to spawn container from read-only image

### ISSUE THREAD

**Issue by Nilix007** [systemd/systemd#4711]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> v232

### Used distribution

> Debian Testing

`systemd-nspawn -i $IMAGE` fails when $IMAGE is a disk image with a squashfs partition as root partition. Squashfs is a read-only filesystem. nspawn prints the following error message:

```
Failed to create directory /tmp/nspawn-root-ljEDam/sys: Read-only file system
```

The error message is misleading. Strace reveals that the actual failing syscall is `lchown` in https://github.com/systemd/systemd/blob/v232/src/nspawn/nspawn-mount.c#L313:

```
[pid 31768] mkdir("/tmp/nspawn-root-okzg3u/sys", 0755) = -1 EEXIST (File exists)
[pid 31768] lchown("/tmp/nspawn-root-okzg3u/sys", 0, 0) = -1 EROFS (Read-only file system)
[pid 31768] writev(2, [{iov_base="Failed to create directory /tmp/"..., iov_len=77}, {iov_base="\n", iov_len=1}], 2) = 78
```

Maybe, `lchown` should be skipped if no uid shift is applied, i.e. `uid_shift == 0`?

**Comment by poettering** [comment]
Fix waiting in #4693.
