### ISSUE TITLE
Read only filesystem and disk errors when booting with any 4.8.x Fedora kernel. 4.7.9 works as expected

### ISSUE THREAD

**Issue by kgillibrand** [systemd/systemd#4714]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
> 229, 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
> Fedora 24 then 25 (x86_64)

### In case of bug report: Expected behaviour you didn't see
> System doesn't boot with any 4.8 kernel and complains that the file system is read only.
Booting with kernel 4.7.9 works as expected.

### In case of bug report: Unexpected behaviour you saw
> Journald fails at flushing it's logfiles to disk with a few Ext4 errors showing and then start jobs for partitions begin that never finish.
Booting with kernel 4.7.9 works perfectly.

I've already checked that my SSD shows no signs of failure as per smartctl as well as the gnome-disks smart data check.

I have an AskFedora post here with more information (pictures of error messages mostly): https://ask.fedoraproject.org/en/question/96616/systemd-disk-errors-booting-fails-with-certain-kernels/#

### In case of bug report: Steps to reproduce the problem
> Might depend on certain circumstances, I'm not sure how reproducible this is.

1. Boot a system with an encrypted LUKS disk that is running a 4.8 Fedora kernel (the disk was encrypted by Fedora's Anaconda installer).
2. Enter your encryption passkey
3. After the disk is decrypted you will start to see Ext4 and Journald disk errors
4. Start jobs for the disk partitions will begin and never finish

**Comment by poettering** [comment]
Uh oh, those fs log messages dumped by the kernel suggest a kernel or file system issue. Please contact your distro or kernel maintainers, this doesn't look at all like an issue systemd is involved.

systemd relies on the kernel's file system and block device code to work. If that already fails there's little else we can do. Sorry.

**Comment by kgillibrand** [comment]
Fair enough, thanks for the tip
