### ISSUE TITLE
systemd-resolved fails to resolve domains with DNSSEC=true after switching wlans

### ISSUE THREAD

**Issue by alexanderkjall** [systemd/systemd#4715]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 231 +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> name resolution through systemd-resolved working

### In case of bug report: Unexpected behaviour you saw

> The name resolution through systemd-resolved was very flaky, i managed to get some answers but most of them failed.

### In case of bug report: Steps to reproduce the problem

> Configure the system to use systemd-resolved as the nameserver by adding 127.0.0.53 in /etc/resolve.conf.
Configure /etc/systemd/resolved.conf like this:
[Resolve]
DNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
DNSSEC=true

close the laptop so that it sleeps, move to another location and wlan.
try to resolve a domain.

attached is the debug log from resolved from when I tried to access facebook.com
[ITpKZ.txt](https://github.com/systemd/systemd/files/607643/ITpKZ.txt)

The problem goes away if I restart resolved with:
systemctl restart systemd-resolved.service

**Comment by poettering** [comment]
Hmm, so the logs you provided suggest that the for some reason resolved came to the conclusion that your DNS server in fact does not support DNSSEC. Hopwever, the logs do not show how precisely it came to the conclusion they are missing that bit. Any chance you can reproduce this but include a longer exceprt of the logs, including the last a lookup still worked until the first lookup that fails?

**Comment by alexanderkjall** [comment]
The issue doesn't happen that often, my initial guess that it happens when i switch wlan might be true but it doesn't happen every switch. When I'm not out traveling I see the bug roughly once a week, I'll  make sure to grab the logs when it happens next time, but it might take a while.

**Comment by alexanderkjall** [comment]
Now it happened again, I'll attach a complete (large) log file, look at 20:23:51 in it to see when it happened
[resolved.log.zip](https://github.com/systemd/systemd/files/804803/resolved.log.zip)

**Comment by poettering** [comment]
@alexanderkjall any chance you could check with resolved from git (or the upcoming 233)? It contains a ton of resolved fixes, and if it might fix this all for you anyway.

**Comment by alexanderkjall** [comment]
I'll try, but as this is my main working machine i need to make sure that I don't break the installation. I'll report back if the issue happens with 233. Or close it if I can't reproduce it.

**Comment by poettering** [comment]
ok, let's close this, given this is three years old now
