### ISSUE TITLE
systemd-nspawn: poweroff and immediate restart of a machine fails due to leftover bridge

### ISSUE THREAD

**Issue by wsw70** [systemd/systemd#4718]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.04 (xenial)

### In case of bug report: Expected behaviour you didn't see

> powering off and immediately restarting a machine should work

### In case of bug report: Unexpected behaviour you saw

> the restart of the machine fails, then is possible after some time. This is due to an existing (leftover) bridge which is removed from the system after some time

### In case of bug report: Steps to reproduce the problem

(`delug` is the name of the machine)

`machinectl poweroff delug`

right after that

`machine start delug` 

The error message:

> Job for systemd-nspawn@delug.service failed because the control process exited with error code. See "systemctl status systemd-nspawn@delug.service" and "journalctl -xe" for details.

`journalctl -xe` shows

`Nov 23 09:10:19 srv systemd-nspawn[5210]: Failed to add new veth interfaces (vb-delug:host0): File exists`

**Comment by poettering** [comment]
This has been fixed a while back in nspawn 230. Please update.

(Also, in general, we only track bugs in the two most recent upstream versions here, which is 232 and 231 right now. Before filing bugs against 229 hence always update first.)

**Comment by wsw70** [comment]
@poettering : thanks. I updated from 229 to 230 a while ago and it broke the cgroups on my install (there was a bug filed on that but I never managed to have it working, even with the help of the upstream ubuntu maintainer who was of truly extraordinary help). I will try to upgrade now and check this out.
