### ISSUE TITLE
journalctl --list-boots still hangs with newer patches

### ISSUE THREAD

**Issue by hese10** [systemd/systemd#4720]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
231 + pull request 4362

### Used distribution

fedora 24

### In case of bug report: Expected behaviour you didn't see

> journalctl --list-boots shuold output boot ids and not hang.

### In case of bug report: Unexpected behaviour you saw

> journalctl --list-boots hangs

### In case of bug report: Steps to reproduce the problem

> 
Setup fedora in virtualbox, so that during boot up the VM gets the time from host.
Inside fedora 24, set default target to multi-user.target
 add normal user to system. disable ntp:
timedatectl set-ntp 0

Startup fedora VM
login as root, change time backwards 8 hours
delete journal files from /var/log/journal/*/*
restart systemd-journald service
log something to journal with logger 
logout root
login as nornal user and log something to journal with logger
logout normal user
login root
shutdown fedora
start fedora VM
loging as root, log something to journal with logger
logout root
login as nornal user and log something to journal with logger
logout normal user
login as root, change time backwards 8 hours
Log something to journal with logger 
logout root
login as nornal user and log something to journal with logger
logout normal user
shutdown fedora VM
start fedora VM
login as root, change time backwards 8 hours
give "journalctl --list-boots", it shuold now hang

**Comment by hese10** [comment]
I cannot load now the journal files as zip, this github.com says "we don't support that file type".

**Comment by hese10** [comment]
Here is tar gzipped journal files:
[journal_files.tar.gz](https://github.com/systemd/systemd/files/609167/journal_files.tar.gz)

**Comment by poettering** [comment]
After unpacking your tarball and changing into the dir with the journal files:

```
$ journalctl -D . --list-boots
-2 f39aba135cc84965a36bb6e069908fc6 Wed 2016-11-23 12:35:44 CET—Wed 2016-11-23 12:36:53 CET
-1 0f6f8fe85f0c47918a6dc317d393997b Wed 2016-11-23 20:37:10 CET—Wed 2016-11-23 12:40:13 CET
 0 c150441c7b8046448c71b157faced5ea Wed 2016-11-23 20:40:26 CET—Wed 2016-11-23 12:41:57 CET
$
```

This works fine here... Are you saying this fails for you? Any chance you can try this with v232?

**Comment by hese10** [comment]
Yes, it will work for v232 because it has that journalctl fix to avoid forever loop. But the journal files could be still in bad shape. Is pull request 4362 included in v232? I will test it with v232, but without journalctl fix.

**Comment by hese10** [comment]
I tried to test with v232, but fedora does not now work correctly when I installed (using make install) this newer systemd. For example journald stops every time during boot. Is there something special that shuold be done when switching from v231 to v232?  I even installed v231 back (using make install), and then system worked again, also journald.
here are journal output as text (inside tar.gz) from this v232 problem
[journals.tar.gz](https://github.com/systemd/systemd/files/610727/journals.tar.gz)

**Comment by hese10** [comment]
Sorry, I used default configure options, but those were set to different values in v231 vs v232 (selinux options). Now that I disabled selinux via configure option, then journal started to work. Now I will try to test this case again without journalctl fix.

**Comment by hese10** [comment]
with systemd v232 (and removing journalctl fix) I managed to repeat the fault situation. Thus journalctl  hangs, so journal files are not in good shape.
[journal_files2.tar.gz](https://github.com/systemd/systemd/files/610949/journal_files2.tar.gz)

**Comment by poettering** [comment]
Hmm? Sure if you undo the patches then journalctl will of course be broken again in this regard? What are you trying to do? I don#t follow at all.

generally, we try to fix issues with newer systemd versions, but stuff that is already released is already released the way it is...

Totally not grokking what you are saying?

**Comment by hese10** [comment]
As we have also cursor problem with journalctl command in these same time change cases, I thought that there is some generic problem still with journal files. Ok. I will make separate issue for "--cursor" problem.

**Comment by poettering** [comment]
OK, I take it all is good with current systemd then. Closing this bug hence.

**Comment by poettering** [comment]
OK, I take it all is good with current systemd then. Closing this bug hence.
