### ISSUE TITLE
Sometimes sys-subsystem-net-devices-ens2.device is wrongly GCed

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#4725]
For about two weeks now, the boot-and-services integration test randomly fails because it detects a failed `ifup@ens2.service` unit after boot (we enforce that in a default systemd install there are no failed units):

```
Nov 23 20:42:00 autopkgtest systemd[1]: Started ifup for ens2.
Nov 23 20:42:00 autopkgtest systemd[1]: ifup@ens2.service: Unit is bound to inactive unit sys-subsystem-net-devices-ens2.device. Stopping, too.
Nov 23 20:42:00 autopkgtest systemd[1]: Stopping ifup for ens2...
Nov 23 20:42:00 autopkgtest ifdown[712]: /sbin/ifdown: waiting for lock on /run/network/ifstate.ens2
[...]
Nov 23 20:42:03 autopkgtest systemd[1]: Stopped ifup for ens2.
Nov 23 20:42:03 autopkgtest systemd[1]: ifup@ens2.service: Unit entered failed state.
Nov 23 20:42:03 autopkgtest systemd[1]: ifup@ens2.service: Failed with result 'exit-code'.
```

([full log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20161123_205854_3d9e6@/log.gz))

The unusual bit is "Unit is bound to inactive unit  .. .device". I haven't seen this downstream (yet), and never before ~ 2 weeks ago, so at first sight this looks like either a regression with udev, or maybe exposing a problem with [ifup@.service](https://anonscm.debian.org/cgit/collab-maint/ifupdown.git/tree/debian/ifup@.service) -- this is triggered *from* a [udev rule](https://anonscm.debian.org/cgit/collab-maint/ifupdown.git/tree/debian/ifupdown.udev), so I don't believe that the problem is that udev isn't running yet.

I haven't succeeded in reproducing this interactively yet, so I'm opening this to collect information and have a proper place to refer to when encountering this in tests.

**Comment by martinpitt** [comment]
As a first step I changed the test to output the complete journal on failures, not just the journal for the failed units.

**Comment by martinpitt** [comment]
On the console of an instance that fails that way I see:
```
[[0;1;39m INFO [0m] Unecessary job for sys-subsystem-net-devices-ens2.device was removed.
[[0;32m  OK  [0m] Started ifup for ens2.
         Stopping ifup for ens2...
[...]
[[0;32m  OK  [0m] Stopped ifup for ens2.
```
This would correspond to commit c5a97ed13 ("core: GC redundant device jobs from the run queue", from issue #1921) which landed a week ago -- that time fits, that's around when we started seeing these failures.

**Comment by martinpitt** [comment]
FTR, this is also the cause of tests taking so long now -- the tests do three handfuls of reboots, and this is prone to break networking at boot. If the instance does not come back, the test is automatically restarted, but I've seen it take four or five attempts (and each one takes about two hours, as there's another regression with not respecting `CFLAGS=-O0` any more -- it always builds with `-O2`; but that's another topic).

**Comment by poettering** [comment]
Hmm, any chance you can isolate this out somehow so that I can reproduce this here easily (on my fedora system)?

What are the precise dependencies of the .service unit and the .device unit in question? i.e. what "systemctl show" reports?

**Comment by evverx** [comment]
```sh
-bash-4.3# systemctl cat binds-to-dev-zero.service
# /etc/systemd/system/binds-to-dev-zero.service
[Unit]
BindsTo=sys-devices-virtual-mem-zero.device

[Service]
ExecStart=/bin/sh -c 'sleep 10'

-bash-4.3# cat /lib/udev/rules.d/99-dev-zero.rules
ACTION=="remove", GOTO="dev_zero_end"

SUBSYSTEM=="mem", KERNEL=="zero", TAG+="systemd", RUN+="/bin/systemctl start binds-to-dev-zero.service"

LABEL="dev_zero_end"

-bash-4.3# udevadm trigger --action=add /dev/zero
```

`v232`
```
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Trying to enqueue job binds-to-dev-zero.service/start/replace
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Installed new job binds-to-dev-zero.service/start as 994
Nov 24 00:00:44 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Installed new job sys-devices-virtual-mem-zero.device/start as 1058
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Enqueued job binds-to-dev-zero.service/start as 994
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Passing 0 fds to service
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: About to execute: /bin/sh -c 'sleep 10'
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Forked /bin/sh as 2473
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Changed dead -> running
Nov 24 00:00:44 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Job binds-to-dev-zero.service/start finished, result=done
Nov 24 00:00:44 ubuntu-zesty systemd[1]: Started binds-to-dev-zero.service.
Nov 24 00:00:44 ubuntu-zesty systemd[2473]: binds-to-dev-zero.service: Executing: /bin/sh -c 'sleep 10'
Nov 24 00:00:44 ubuntu-zesty systemd[1]: dev-zero.device: Changed dead -> plugged
Nov 24 00:00:44 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Changed dead -> plugged
Nov 24 00:00:44 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Job sys-devices-virtual-mem-zero.device/start finished, result=done
Nov 24 00:00:44 ubuntu-zesty systemd[1]: Found device /sys/devices/virtual/mem/zero.
Nov 24 00:00:54 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Child 2473 belongs to binds-to-dev-zero.service
Nov 24 00:00:54 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Main process exited, code=exited, status=0/SUCCESS
Nov 24 00:00:54 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Changed running -> dead
Nov 24 00:00:54 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: cgroup is empty
Nov 24 00:00:54 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Collecting.
```
`master`
```
Nov 23 23:42:57 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Trying to enqueue job binds-to-dev-zero.service/start/replace
Nov 23 23:42:57 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Installed new job sys-devices-virtual-mem-zero.device/start as 1104
Nov 23 23:42:57 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Installed new job binds-to-dev-zero.service/start as 1030
Nov 23 23:42:57 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Enqueued job binds-to-dev-zero.service/start as 1030
Nov 23 23:42:57 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Collecting job.
Nov 23 23:42:57 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Job sys-devices-virtual-mem-zero.device/start finished, result=collected
Nov 23 23:42:57 ubuntu-zesty systemd[1]: Unecessary job for sys-devices-virtual-mem-zero.device was removed.
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Passing 0 fds to service
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: About to execute: /bin/sh -c 'sleep 10'
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Forked /bin/sh as 2561
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Changed dead -> running
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Job binds-to-dev-zero.service/start finished, result=done
Nov 23 23:42:58 ubuntu-zesty systemd[1]: Started binds-to-dev-zero.service.
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Unit is bound to inactive unit sys-devices-virtual-mem-zero.device. Stopping, too.
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Trying to enqueue job binds-to-dev-zero.service/stop/fail
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Installed new job binds-to-dev-zero.service/stop as 1105
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Enqueued job binds-to-dev-zero.service/stop as 1105
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Changed running -> stop-sigterm
Nov 23 23:42:58 ubuntu-zesty systemd[1]: Stopping binds-to-dev-zero.service...
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Child 2561 belongs to binds-to-dev-zero.service
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Main process exited, code=killed, status=15/TERM
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Changed stop-sigterm -> dead
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Job binds-to-dev-zero.service/stop finished, result=done
Nov 23 23:42:58 ubuntu-zesty systemd[1]: Stopped binds-to-dev-zero.service.
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Collecting.
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Failed to send unit change signal for binds-to-dev-zero.service: Transport endpoint is not connected
Nov 23 23:42:58 ubuntu-zesty systemd[1]: binds-to-dev-zero.service: Failed to send unit remove signal for binds-to-dev-zero.service: Transport endpoint is not connected
Nov 23 23:42:58 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Collecting.
Nov 23 23:42:58 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Failed to send unit remove signal for sys-devices-virtual-mem-zero.device: Transport endpoint is not connected
Nov 23 23:42:58 ubuntu-zesty systemd[1]: dev-zero.device: Changed dead -> plugged
Nov 23 23:42:58 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Changed dead -> plugged
Nov 23 23:42:58 ubuntu-zesty systemd[1]: sys-devices-virtual-mem-zero.device: Failed to send unit change signal for sys-devices-virtual-mem-zero.device: Transport endpoint is not connected
Nov 23 23:42:58 ubuntu-zesty systemd[1]: dev-zero.device: Failed to send unit change signal for dev-zero.device: Transport endpoint is not connected
```

**Comment by martinpitt** [comment]
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20161124_000702_0bc7d@/log.gz has a run with a full journal.

But thanks @evverx, that looks exactly like this failure!  (The actual thing starts systemctl with `--no-block`, though).

The "Unecessary job for ... reproduces reliably when running current master (I used the built debs from a [recent run](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20161122_172658_cdf2e@/artifacts.tar.gz) for convenience: download, untar, `sudo dpkg -iO binaries/*.deb`).

**Comment by martinpitt** [comment]
I can reproduce with @evverx' recipe, but not really with `udevadm trigger`, just with rebooting. But in every case I now get
```
systemd[1]: Unecessary job for sys-subsystem-net-devices-ens3.device was removed.
systemd[1]: Unecessary job for sys-devices-virtual-mem-zero.device was removed.

systemd[1]: b.service: Unit is bound to inactive unit sys-devices-virtual-mem-zero.device. Stopping, too.
```
And `b.service` (the `sleep 10` one above that binds to mem-zero) gets killed immediately. Curiously ` sys-devices-virtual-mem-zero.device` actually *is* "active/plugged" after boot.

**Comment by poettering** [comment]
that the .device job is GC'ed looks right in @evverx's test run. After all the service only has BindsTo= on the device, but no ordering. Hence we drop the job as nothing will be waiting for it. 

That said, GC'ing the *job* shouldn't mean the *unit* is also GC'ed. And that's where things are weird here: the job ending in "collected" shouldn't have any effect on any unit with BindsTo= on it...

**Comment by poettering** [comment]
So, in @evverx systemd is actually doing the right thing. The service is bound to the device but not ordered against it. This means startup of the service will not be delayed, as there's nothing to wait for. But as soon as it is up we notice that the device isn't around yet, and are stopped again. This is because at the time the udev rule is run the .device is not yet visible to PID 1. The fix for that is easy: just add After= in additoin to BindsTo= on the device.

@martinpitt does the `ifup@.service` service have After= or also just BindsTo=?

If so, this should be fixed in `ifup@.service`. However we should probably do something about this in systemd too. We could do one of:

 a) warn if BindsTo= is used without ordering
 b) add in After= if BindsTo= is used without ordering
 c) if a unit is upped that bindsto another unit, fail it immediately is the requirements aren't met, with a proper error message in the logs.

Kinda leaning towards c).

**Comment by martinpitt** [comment]
@poettering: current [ifup.service](https://anonscm.debian.org/cgit/collab-maint/ifupdown.git/tree/debian/ifup@.service) does *not* have the After=. This is indeed a bit counter-intuitive as this unit is triggered from a udev rule, so I'd expect that .device to be active already; this seems to have worked for a long time, but I do see the race between systemd "importing" that and starting the bound unit.

I made a quick commit to add this with a drop-in: https://git.launchpad.net/~pitti/+git/systemd-debian/commit/?id=f82a1804 . If this works,  this should of course move to the actual unit, but that takes a bit longer. So let's try this for a day or two, it should be fairly evident that tests do not need half a day any more. :-)

Thanks for investigating this!

**Comment by poettering** [comment]
@martinpitt how precisely do you start `ifup@.service` from the udev rule?

**Comment by martinpitt** [comment]
The udev rule starts a [script](https://anonscm.debian.org/cgit/collab-maint/ifupdown.git/tree/debian/ifupdown-hotplug)
```
SUBSYSTEM=="net", ACTION=="add|remove", RUN+="ifupdown-hotplug"
```
That checks if it's running under SysV/upstart (irrelevant here) or systemd, in which case it runs `systemctl --no-block start $(systemd-escape --template ifup@.service $INTERFACE)`. It's very similar to @evverx' reproducer, except for the `--no-block` (but that should be irrelevant here).

**Comment by poettering** [comment]
@martinpitt i see. anyway, i prepped #4733 which make the job actually fail when this case is hit, which is a bit nicer for error checking, but doesn't fix any real problem.

**Comment by martinpitt** [comment]
Seems this did help; no more looping tests, no failures any more, and test results come back after the usual time again.

I committed that to ifupdown now: https://anonscm.debian.org/cgit/collab-maint/ifupdown.git/commit/?id=3dfd3590 and also backported that patch into the [overlay PPA](https://launchpad.net/~pitti/+archive/ubuntu/systemd-semaphore) that we use for CI.

There is still some discussion in #4733 what the desired behaviour should be, so I don't close this myself yet. If you are sure that this is correct behaviour, please close.

**Comment by evverx** [comment]
Well,  #4678 breaks some services in the wild (wrt #4733)
I think this should be documented at least

**Comment by evverx** [comment]
Personally, I think #4678 doesn't respect the `BindsTo=`-definition:
> BindsTo=
Configures requirement dependencies, very similar in style to Requires=, however in addition to this behavior, it also declares that this unit is stopped when any of the units listed
suddenly disappears. Units can suddenly, unexpectedly disappear if a service terminates on its own choice, a device is unplugged or a mount point unmounted without involvement of systemd.

But I'm not sure what to do about it

**Comment by poettering** [comment]
> Personally, I think #4678 doesn't respect the BindsTo=-definition:

Why do you say this? Not sure I follow?

**Comment by evverx** [comment]
@poettering , sorry. I mean
> You mostly want to say "stop b if a goes away", but don't care about the ordering

https://github.com/systemd/systemd/pull/4733#discussion_r89572157

**Comment by poettering** [comment]
OK, let's close htis one, and continue discussion in #4733.
