### ISSUE TITLE
hwdb: HP Pavilion dv7 touchpad

### ISSUE THREAD

**Issue by jvpeetz** [systemd/systemd#4731]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

For the clickable touchpad (ClickPad) of HP Pavilion dv7 17" notebook the x/y-axis values are outside the expected range.
The output of `udevadm info /dev/input/event12` is

```
P: /devices/platform/i8042/serio1/input/input9/event12
N: input/event12
E: DEVNAME=/dev/input/event12
E: DEVPATH=/devices/platform/i8042/serio1/input/input9/event12
E: EVDEV_ABS_00=1068:5805:44
E: EVDEV_ABS_01=1197:4890:57
E: EVDEV_ABS_35=1068:5805:44
E: EVDEV_ABS_36=1197:4890:57
E: ID_BUS=i8042
E: ID_INPUT=1
E: ID_INPUT_HEIGHT_MM=51
E: ID_INPUT_TOUCHPAD=1
E: ID_INPUT_TOUCHPAD_INTEGRATION=internal
E: ID_INPUT_WIDTH_MM=91
E: LIBINPUT_DEVICE_GROUP=11/2/7/1b1:isa0060/serio1
E: LIBINPUT_MODEL_JUMPING_SEMI_MT=1
E: LIBINPUT_MODEL_SYNAPTICS_SERIAL_TOUCHPAD=1
E: MAJOR=13
E: MINOR=76
E: SUBSYSTEM=input
E: USEC_INITIALIZED=6892449

```

The size in mm^2 is actually 107x65 (not 91x51). Therefore, a new touchpad hwdb rule was created as described [here](https://wayland.freedesktop.org/libinput/doc/1.5.1//absolute_coordinate_ranges.html):

```
# HP Pavilion dv7
evdev:name:SynPS/2 Synaptics TouchPad*:dmi:*svnHewlett-Packard:pnHPPaviliondv7*
 EVDEV_ABS_00=1068:5805:44
 EVDEV_ABS_01=1197:4890:57
 EVDEV_ABS_35=1068:5805:44
 EVDEV_ABS_36=1197:4890:57

```
Could this rule be added to 60-evdev.hwdb?

Regards,
jvp.

**Comment by poettering** [comment]
@jvpeetz please file that as proper PR to make it easier to merge.

/cc @whot
