### ISSUE TITLE
journalctl doesn't follow rotated files properly

### ISSUE THREAD

**Issue by sschindler89** [systemd/systemd#474]
Reproduced on Systemd 219 (Kubuntu 15.04) and 221 (Fedora 21)

If you follow a file or directory via 
- journalctl --directory /path/to/logs/ -f
- journalctl --file /path/to/logs/my.journal -f

files that get rotated won't be followed in the journalctl view.
I witnessed this issue with induced rotation (due to non monotonic timelogs) as well as rotation caused by file size (by spamming the system journal). Below I'll post the code so you can reproduce both cases.
I understand that this might be desired for the --file option, because the formerly targeted file stopped to exist for a moment, but I think this is definitely not desired for the --directory option.
#### induced rotation

this needs journal-remote to work:
- create a directory to log into
- follow this directory via journalctl

```
mkdir ~/logtest
journalctl --directory ~/logtest/ -f
```
- now log something into this directory that creates a .journal entry and then immediately log something that causes this file to rotate

```
echo "__CURSOR=s=b8251891acca4dc290d740f6d17e6e65;i=1248;b=7f272978644b4ee1bf5d375ff2bdda57;m=ac1b0c94a;t=514b03d810138;x=d9bf4c3b3d82d447
__REALTIME_TIMESTAMP=1430122062217528
__MONOTONIC_TIMESTAMP=46199261514
_BOOT_ID=7f272978644b4ee1bf5d375ff2bdda57
_UID=1000
_GID=1000
_MACHINE_ID=dca72f9011fc456b8c70371ad5ecdd52
_HOSTNAME=virtual-fedora-sbs
_TRANSPORT=syslog
SYSLOG_FACILITY=1
PRIORITY=5
SYSLOG_IDENTIFIER=tpiadmin
MESSAGE=a
_PID=9617
_SOURCE_REALTIME_TIMESTAMP=1430122060575304

__CURSOR=s=b8251891acca4dc290d740f6d17e6e65;i=1247;b=7f272978644b4ee1bf5d375ff2bdda57;m=ac197cd91;t=514b03d68057c;x=da399a0b1e105d04
__REALTIME_TIMESTAMP=1430122060580220
__MONOTONIC_TIMESTAMP=46197624209
_BOOT_ID=7f272978644b4ee1bf5d375ff2bdda57
_UID=1000
_GID=1000
_CAP_EFFECTIVE=0
_SYSTEMD_CGROUP=/
_MACHINE_ID=dca72f9011fc456b8c70371ad5ecdd52
_HOSTNAME=virtual-fedora-sbs
_TRANSPORT=syslog
SYSLOG_FACILITY=1
PRIORITY=5
SYSLOG_IDENTIFIER=tpiadmin
_COMM=logger
MESSAGE=b
_PID=9621
_SOURCE_REALTIME_TIMESTAMP=1430122062218315

" | /lib/systemd/systemd-journal-remote -o  ~/logtest/test.journal -
```

You should only see the first entry in the journalctl view.
#### rotation by file size

This requires your willingness to spam your system journal for a short time:
- follow your system journal by explicitly calling the directory

```
journalctl --directory /var/log/journal/[machine-id] -f
```

OR

```
journalctl --directory /run/log/journal/[machine-id] -f
```

now the fun part:
- spam like there's no tomorrow

```
while true; do logger spam; done
```

This should trigger rotation because of file size soon enough which in term should stop the journalctl view to show new entries.

**Comment by sschindler89** [comment]
Update: This does not occur if the logs are in a subdirectory in the followed directory with a name that has the format of a machine id. 

Example: 
- The location of the journal file is ~/logtest/dca72f9011fc456b8c70371ad5ecdd53/test.journal
- Follow logtest: journalctl --directory ~/logtest -f

**Comment by wraithm** [comment]
I'm having this exact same issue. Is there any update on this issue? @sschindler89, did you find a work around?

**Comment by poettering** [comment]
BTW, I am pretty sure this is fixed now, if all the changes up to and including #8222 are applied. Let's close this hence. Please reopen if this remains an issue even after #8222.
