### ISSUE TITLE
(REF) Create a target for shutdown application before OS processes initiate to stop

### ISSUE THREAD

**Issue by standby24x7** [systemd/systemd#4740]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

>systemd-229-16.fc24

### Used distribution

> Fedora 24

###  Symptom Summary
OS processes start to stop at the very same timing as application start to shutdown.
User want to have a control to shutdown the application _FIRST_, and then stop 
OS processes _LATER_.

### Detail
An applications needs some OS resources to run the process.
In case of application startup, we can control the application's startup order 
to the "very last" moment so that all the resources are ready to use.

But in case of application shutdown,  even if I set  "After=default.target" 
and make the application to shutdown _FIRST_,  still other OS related process
also started to stop simultaneously.
In some case,  the application shutdown failed because of  OS resources shutdown
too early.
I hope developer create a "dummy target" for application shutdown.
Then application use  "Before = dummy.target"  to execute the stop script very first
order of the shutdown.
And once the application completely stop, then dummy.target is called.
Then OS related processes may start to shutdown.

**Comment by poettering** [comment]
If services provide services to user sessions and shall not be started after the user sessions are started up and not be stopped before the user sessions are down, then they need to be ordered before systemd-user-sessions.service, which kinda acts as the requested barrier already.
