### ISSUE TITLE
hwdb: clarify documentation regarding  overriding of hwdb entries

### ISSUE THREAD

**Issue by norbusan** [systemd/systemd#4750]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian/sid

### In case of bug report: Expected behaviour you didn't see

> Properties as defined in /etc/udev/hwdb.d/ are properly applied.

### In case of bug report: Unexpected behaviour you saw

> Although `systemd-hwdb` reports the correct values, the device does not work as expected.

### In case of bug report: Steps to reproduce the problem

I have a Microsoft Natural Ergonomic Keyboard 4000 which has two keys that are mapped to zoomin/out in /lib/udev/hwdb.d/60-keyboard.hwdb:
`````
# Microsoft Natural Ergonomic Keyboard 4000
evdev:input:b0003v045Ep00DB*
 KEYBOARD_KEY_c022d=zoomin
 KEYBOARD_KEY_c022e=zoomout
`````

I want these keys to work as page up/down instead. so I have created a file `/etc/udev/hwdb.d/61-local.hwdb` that contains the updated definitions:
`````
# Microsoft Natural Ergonomic Keyboard 4000 - remap zoom in/out to page up/down
# one can use up/down for line scrolling
evdev:input:b0003v045Ep00DB*
 KEYBOARD_KEY_c022d=pageup
 KEYBOARD_KEY_c022e=pagedown
`````

Reading through the man pages of hwdb(7) and systemd-hwdb(8) I would expect that any later configuration overrides earlier definitions, and indeed, after running `udevadm hwdb --update` I can see that the correct entries are used:
`````
$ systemd-hwdb query evdev:input:b0003v045Ep00DB
KEYBOARD_KEY_c022d=pageup
KEYBOARD_KEY_c022e=pagedown
$
`````

Unfortunately this does not work when I plug in the kbd itself, or boot with the kbd connected.

This was originally reported in Debian bug report [845442](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845442), where Michael Biebl suggested that the internal version of udev might behave differently to the calls of `systemd-hwdb`.

Till now the only option I have found is creating a file `/etc/udev/hwdb.d/60-keyboard.hwdb` which overrides the one under `/lib/udev`. With this change the kbd is working properly when plugged in or connected during boot, but this is a unsatisfying solution and contrary to the documentation.

Thanks for any hint

Norbert

**Comment by mbiebl** [comment]
This is either a documentation issue, where we need to make clear that overriding single entries is not supported. Or simply a bug in IMPORT{builtin}="hwdb". The bug report should be repurposed accordingly.

**Comment by poettering** [comment]
This is a bug and RFE tracker, not a support forum. If you have questions, then please direct them to the ML instead. Thanks.

To answer the question: hwdb is a simple static key-value storage engine. The data it contains is imported into the udev property sets. if you want to override the data please do so via udev rules, not via hwdb entries.

**Comment by mbiebl** [comment]
@poettering I asked @norbusan  to file this issue upstream.
Either this is a bug or documentation issue. Either way this should be addressed
If you look at 60-evdev.hwdb for example, it explicitly says this:

```

# To add local entries, create a new file
#   /etc/udev/hwdb.d/61-evdev-local.hwdb
# and add your rules there. To load the new rules execute (as root):
#   udevadm hwdb --update
#   udevadm trigger /dev/input/eventXX
# where /dev/input/eventXX is the device in question. If in
# doubt, simply use /dev/input/event* to reload all input rules.
```

**Comment by mbiebl** [comment]
Or 60-keyboard.hwdb
```
# To update this file, create a new file
#   /etc/udev/hwdb.d/70-keyboard.hwdb
# and add your rules there. To load the new rules execute (as root):
#   udevadm hwdb --update
#   udevadm trigger /dev/input/eventXX
# where /dev/input/eventXX is the keyboard in question. If in
# doubt, simply use /dev/input/event* to reload all input rules.
```

**Comment by mbiebl** [comment]
I took the liberty to reopen the bug report and retitle it accordingly.
If existing hwdb entries are supposed to be overwritten via udev rules, we should say so in the man page, ideally with an example how to do so.

**Comment by martinpitt** [comment]
This is easier to investigate in a VM, so I picked a model name from 20-pci-vendor-model.hwdb from the emulated PCI card:
```
$ ls -l /etc/udev/hwdb.bin
ls: cannot access '/etc/udev/hwdb.bin': No such file or directory

$ udevadm info --path=/devices/pci0000:00/0000:00:01.0 | grep -E 'ID_MODEL|MODALIAS'
E: ID_MODEL_FROM_DATABASE=82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)
E: MODALIAS=pci:v00008086d00007000sv00001AF4sd00001100bc06sc01i00

$ cat <<EOF | sudo tee /etc/udev/hwdb.d/21-hack.hwdb
pci:v00008086d00007000sv00001AF4sd00001100*
 ID_MODEL_FROM_DATABASE=muhahaha
 BLABLA=bla
EOF

$ sudo systemd-hwdb update
$ ls -l /etc/udev/hwdb.bin
-r--r--r-- 1 root root 8441068 Nov 29 15:02 /etc/udev/hwdb.bin

$ systemd-hwdb query pci:v00008086d00007000sv00001AF4sd00001100bc06sc01i00
ID_PCI_CLASS_FROM_DATABASE=Bridge
ID_PCI_SUBCLASS_FROM_DATABASE=ISA bridge
ID_VENDOR_FROM_DATABASE=Intel Corporation
ID_MODEL_FROM_DATABASE=82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)
BLABLA=bla

$ sudo udevadm trigger --verbose --sysname-match=0000:00:01.0
$ udevadm info --path=/devices/pci0000:00/0000:00:01.0 | grep -E 'ID_MODEL|MODALIAS|BLA'
E: BLABLA=bla
E: ID_MODEL_FROM_DATABASE=82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)
E: MODALIAS=pci:v00008086d00007000sv00001AF4sd00001100bc06sc01i00
```

So the *new* field `BLA` does get added, but it does not change the existing field. I also tried to make the modalias prefix more specific by appending `bc06` (before the `*`), no difference. This differs from @norbusan's result apparently.

Adding an entirely new match is fine however:
```
cat << EOF | tee --append /etc/udev/hwdb.d/21-hack.hwdb

pci:v00001234d00007000sv00001AF4sd00001100*
 ID_MODEL_FROM_DATABASE=muhahaha
EOF

$ sudo systemd-hwdb update
$ systemd-hwdb query pci:v00001234d00007000sv00001AF4sd00001100bc06sc01i00
ID_PCI_CLASS_FROM_DATABASE=Bridge
ID_PCI_SUBCLASS_FROM_DATABASE=ISA bridge
ID_MODEL_FROM_DATABASE=muhahaha
```

Overriding existing entries does work in general in hwdb -- we do it all the time in `60-keyboard.hwdb` to e. g. set a per-vendor keymap which works on most devices, and then add model specific tweaks. .. Or at least we *think* that works :-)

Copying the entire `20-pci-vendor-model.hwdb` to /etc/ and then modifying it works fine (for this example anyway); but this should then completely shadow the original file in `/usr` instead of amending it, so that's an easier case.

@norbusan, I figure the keyboard actually works, so you didn't just check `systemd-hwdb query`, but the udev database as well, and udev actually poked the right key codes into the driver? The description you gave here ("does not work at all") is different from the one given in the Debian report ("works after calling `--update`, but not after  reboot"), and these would be quite different to investigate.

**Comment by keszybz** [comment]
I'm working on a fix.

**Comment by mbiebl** [comment]
@martinpitt The new keycodes are not applied during boot, if you use say 61-keyboard.hwdb to only override a single entry. You need to override 60-keyboard.hwdb completely.

**Comment by norbusan** [comment]
Hi all,
@martinpitt My "this does not working" meant that the two keys I want to override do not send the correct events. The rest of the kbd works of course.

@keszybz Does your fix mean that after that I can have a file 61-local.hwdb that overrides single entries?

Thanks everyone.

**Comment by keszybz** [comment]
> Does your fix mean that after that I can have a file 61-local.hwdb that overrides single entries?

Yes. I added a commit which adds some examples to the man page. Let me know if anything is still unclear.

**Comment by norbusan** [comment]
Thanks, I checked the changes in the man page, that sounds great.

**Comment by norbusan** [comment]
@poettering I really love your attitude of discarding proper reports straight ahead without first thinking about it. I'm very grateful to @keszybz who used his brain first before judging. thanks for your great support.

**Comment by keszybz** [comment]
@norbusan chill, man. @poettering handles an insane number of bugs, and there's no need to be snarky. We have multiple maintainers so that if one missed something, the other catches it.
