### ISSUE TITLE
"Requisite" dependency fails with "device" units - and with "After" ordering, produces "crazy" errors

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4756]
- [ ] Bug report
  - [ ] Request for enhancement (RFE)

> systemd 232-3

> Arch

When it is convenient to have a WantedBy=some-other-unit dependency in addition to a
WantedBy= sys-subsystem-net-devices-%p.device

then it would seem necessary to qualify the Start from some-other-unit with a
Requisite= sys-subsystem-net-devices-%p.device

so that the unit does NOT actually start when no such device actually exists yet.

Instead, the Requisite=...device dependency has no effect whatsoever, and systemd will attempt to start the unit whether the device exists or not.

Additionally, in issue https://github.com/systemd/systemd/issues/4256, there is the statement that, "we should also point out in the man page explicitly that Requisite needs to be combined with After= to be useful".

Instead, combining:
Requisite= sys-subsystem-net-devices-%p.device
After= sys-subsystem-net-devices-%p.device

produces "crazy" systemd errors, in the nature of:
 systemd[1]: enp0s7@bond0.service: Main process exited, code=killed, status=15/TERM
 systemd[1]: Stopped Enslaved enp0s7@bond0.
 systemd[1]: enp0s7@bond0.service: Unit entered failed state.
 systemd[1]: enp0s7@bond0.service: Failed with result 'signal'.
 systemd[1]: Requested transaction contradicts existing jobs: Resource deadlock avoided
 systemd[1]: Requested transaction contradicts existing jobs: Resource deadlock avoided
 systemd[1]: Requested transaction contradicts existing jobs: Resource deadlock avoided

such that the entire unit start fails.  What this "Resource deadlock" might be is a unknown, with a useless "opaque" error message.

It is reasonable to expect that systemd would not "try" to start a unit with a Requisite device dependency when that device does not exist!

And it makes no sense to involve some ordering dependency when Start/Stop dependencies are expected to be "orthogonal" to, and independent of, ordering dependencies!

**Comment by poettering** [comment]
Can you provide the full unit file, a longer log excerpt, and "systemctl show" for the service unit in question? Otherwise we cannot track this down?

**Comment by thx1111** [comment]
Let us begin with a simple service unit file which demonstrates the error, and leave out the After= ordering dependency for now.

```
/etc/systemd/system/B@.service
```

```
[Unit]
Description= Service Unit %P@%I
BindsTo= sys-subsystem-net-devices-%i.device
Requisite= sys-subsystem-net-devices-%i.device

[Service]
Type= oneshot
RemainAfterExit= yes
ExecStart= /usr/bin/ip link show dev %I

[Install]
WantedBy= sys-subsystem-net-devices-%i.device
```

```
$ sudo systemctl enable B@none

$ sudo systemctl start B@none
Job for B@none.service failed because the control process exited with error code.
See "systemctl status B@none.service" and "journalctl -xe" for details.

$ journalctl -ab
...
 systemd[1]: Starting Service Unit B@none...
 ip[1067]: Device "none" does not exist.
 systemd[1]: B@none.service: Main process exited, code=exited, status=1/FAILURE
 systemd[1]: Failed to start Service Unit B@none.
 systemd[1]: B@none.service: Unit entered failed state.
 systemd[1]: B@none.service: Failed with result 'exit-code'.
... (+90 seconds)
 systemd[1]: sys-subsystem-net-devices-none.device: Job sys-subsystem-net-devices-none.device/start timed out.
 systemd[1]: Timed out waiting for device sys-subsystem-net-devices-none.device.
 systemd[1]: sys-subsystem-net-devices-none.device: Job sys-subsystem-net-devices-none.device/start failed with result 'timeout'.
```

As requested:
```
$ systemctl show B@none
[show-B@none.txt](https://github.com/systemd/systemd/files/622356/show-B.none.txt)

$ systemd-analyze --require dot B@none.service
digraph systemd {
        "B@none.service"->"system-B.slice" [color="black"];
        "B@none.service"->"sysinit.target" [color="black"];
        "B@none.service"->"sys-subsystem-net-devices-none.device" [color="darkblue"];
        "B@none.service"->"shutdown.target" [color="red"];
        "sys-subsystem-net-devices-none.device"->"B@none.service" [color="grey66"];
}
```

man systemd.unit
Requisite=
           Similar to Requires=. However, if the units listed here are not started already, they **will not be started** *and* **the transaction will fail** immediately.

I take that to mean:
1) "sys-subsystem-net-devices-none.device" is the "listed unit" that will not be started,
2) with "systemctl start B@none", "start" is "the transaction", and
3) "B@none.service" is the unit for which "the [start] transaction will fail".

INSTEAD,
1) "Starting Service Unit B@none..." is the log message saying that "the transaction" has NOT failed and is being run, evidenced by the ExecStart process log message, and
2) "sys-subsystem-net-devices-none.device: Job sys-subsystem-net-devices-none.device/start timed out" is the log message implying that systemd "tried" to start the nonexistent device unit.

The "Requisite=sys-subsystem-net-devices-none.device" dependency can be plainly seen in both the "systemd-analyze" and "systemctl show" output.

And also, *why* is systemd trying to "start" a device unit, regardless of the presence or absence of a Requisite dependency?!  There is no "sys-subsystem-net-devices-none.device" unit file "[Service]" section defining some process to execute to "start" a device!

**Comment by poettering** [comment]
Requisite= without After= makes no sense. you enqueue a check that a unit is started up properly, but then don't wait for the result of the check, but permit the unit you place this in to immediately start... I am not sure what you are trying to say?

**Comment by thx1111** [comment]
The way this "Requisite" operates is very counter-intuitive.

What I expect:
When something activates "start" on a unit file which has a Requisite dependency, then, *at that moment*, systemd would check for the state of the listed unit, and would only need to examine that the listed unit was active or inactive.  If the listed unit is *not* active, then the "start" is abandoned, or it is "failed".

What seems to be happening:
As you say, the After= dependency is examined in the context of the listed unit.  All this does is cause the "start" to pointlessly hang for the timeout period.  The unit being "started" literally *waits* for the listed unit to become active.  This is *not* what the documentation says.  In which case, this dependency should be called "WaitFor=" and NOT "Requisite=".  

And this still takes me back to the beginning - systemd is trying to "start" a nonexistent device unit, along with any service unit on which it has a Wants dependency.  **Why?**

**Comment by thx1111** [comment]
Assuming that systemd operates with some kind of start dependency tree, then there must exist a test for a nonexistent device unit, and the tree must be pruned if that device unit does not exist.

It sounds like that step is missing.

**Comment by poettering** [comment]
uh? Requisite= is really about making dependency checks within the usual dependency system and job queue. That's all it is. All of systemd's requirement and ordering dependency are based on that. And after all we are a dependency-based job queue system hence of course that's how we implement these things...

One major concept behind jobs is that they can be merged: if multiple transactions enqueue something for the same units, we try to merge their jobs. Thus, if a transaction A includes a Requisite= dependency and transaction B includes a Wants= or so on the same unit, then this will result only in one job: a start job, as that way both jobs can succeed. Sure transaction A didn't ask for it to be pulled in, but B did, and hence it makes sense to merge them and turn them into a start job.

Please note again, that Requisite= alone does *not* imply ordering. Hence naming it "WaitFor=" sounds very strange to me, as it it will explicitly *not* wait for anything. After= otoh will.

devices are exposed in systemd as .device units. They exist primarily to order stuff properly at boot, for example so that we can fsck/mount a block device only after it has shown up. As such device units are primarily useful as a synchronization concept: you enqueue a job for a device which isn't around yet, and the job will succeed as soon as it shows up.

BindsTo= is an enhanced Requires=. As such it pulls in depending units. if that is a device unit, then this means the device is pulled in, and if you add After= the same device unit then requesting a unit to start means the device first has to show up for a start job to succeed.

I am not sure what you are assume device units to be, but they are really just synchronization objects, and little else

**Comment by thx1111** [comment]
> if a transaction A includes a Requisite= dependency and transaction B includes a
> Wants= or so on the same unit, then this will result only in one job: a start job,
> as that way both jobs can succeed.

Simple enough - but that just says that Requisite and After may be the wrong place to be looking for this issue with nonexistent device units.

This is a subtle point, the way in which After= may be required to make a start/stop dependency active.  Usually, it's the other way, where a start/stop dependency has to exist for an ordering to do something.  So, I just tried doing this differently, by leaving off the Requisite, but including just the After=.  This changes things.  But there is still a problem:

> As such device units are primarily useful as a synchronization concept:
> you enqueue a job for a device which isn't around yet, and the job will
> succeed as soon as it shows up.

No, that is not what is happing, watching the journal as the units are stopped and started, now using this After=...device dependency and leaving off the Requisite.  The device unit does not wait around, and the jobs which depend upon the device unit do not wait around for the device unit to show up.  Instead, the device unit times-out, and the units which now have this After= dependency are "failed".

 systemd[1]: sys-subsystem-net-devices-wlp0s3f3u2.device: Job sys-subsystem-net-devices-wlp0s3f3u2.device/start timed out.
 systemd[1]: Timed out waiting for device sys-subsystem-net-devices-wlp0s3f3u2.device.
 systemd[1]: Dependency failed for Enslaved wlp0s3f3u2@bond0.
 systemd[1]: wlp0s3f3u2@bond0.service: Job wlp0s3f3u2@bond0.service/start failed with result 'dependency'.
 systemd[1]: Dependency failed for wpa_supplicant on wlp0s3f3u2.
 systemd[1]: supplicant@wlp0s3f3u2.service: Job supplicant@wlp0s3f3u2.service/start failed with result 'dependency'.
 systemd[1]: sys-subsystem-net-devices-wlp0s3f3u2.device: Job sys-subsystem-net-devices-wlp0s3f3u2.device/start failed with result 'timeout'.

*None of these units should even have been enqueued for start.  The device does not exist.  The interface wlp0s3f3u2 does not exist.*  This seems like such a simple concept to me.  How is this not a simple concept?

> device units ... are really just synchronization objects, and little else

Consider the target unit.  Target units are a kind of  synchronization object.  If a service unit has a dependency on a target unit, and the target unit is not yet active, then the service unit is simply not enqueued for start.  The target unit does not time-out and the dependent service units do not fail waiting for the target unit.  That is the nature of a synchronization object.

Device units are not acting like synchronization objects in that same way.  *But they should be*.  It would certainly be nice if they did.  It is a simple idea:  When a device unit does not yet exist, then no dependent service unit should be enqueued yet to start.

**Comment by arvidjaar** [comment]
`Requisite` documentation says:

> if the units listed here are not started already, they will not be started and the transaction will fail immediately

That's not what happens in reality.

```
localhost:/etc/systemd/system # systemctl start A@dummy.service
A dependency job for A@dummy.service failed. See 'journalctl -xe' for details.
```

It lies. Because journalctl says

```
Dec 01 06:15:00 localhost systemd[1]: Created slice system-A.slice.
Dec 01 06:15:00 localhost systemd[1]: Starting Service Unit A@dummy...
Dec 01 06:15:00 localhost systemd[1]: Dummy service is not active.
Dec 01 06:15:00 localhost systemd[1]: Dependency failed for Service Unit A@dummy.
Dec 01 06:15:00 localhost systemd[1]: A@dummy.service: Job A@dummy.service/start failed with result 'dependency'.
Dec 01 06:15:00 localhost systemd[1154]: A@dummy.service: Failed at step EXEC spawning /usr/bin/ip: No such file or directory
Dec 01 06:15:00 localhost systemd[1]: A@dummy.service: Main process exited, code=exited, status=203/EXEC
Dec 01 06:15:00 localhost systemd[1]: A@dummy.service: Unit entered failed state.
Dec 01 06:15:00 localhost systemd[1]: A@dummy.service: Failed with result 'exit-code'.
```

So even though systemd knows that dependency failed, it still attempts to run `ExecStart`.

At the same time in current systemd

```
localhost:/etc/systemd/system # cat B@.service
[Unit]
Description=Service Unit %P@%I
Requisite=sys-subsystem-net-devies-%i.device

[Service]
Type=oneshot
ExecStart=/usr/bin/ip link show dev %I
localhost:/etc/systemd/system # systemctl start B@dummy.service
A dependency job for B@dummy.service failed. See 'journalctl -xe' for details.
localhost:/etc/systemd/system # 
```
Seemingly the same. But looking at logs

```
Dec 01 06:15:08 localhost systemd[1]: sys-subsystem-net-devies-dummy.device is not active.
Dec 01 06:15:08 localhost systemd[1]: Dependency failed for Service Unit B@dummy.
Dec 01 06:15:08 localhost systemd[1]: B@dummy.service: Job B@dummy.service/start failed with result 'dependency'.
Dec 01 06:15:08 localhost systemd[1]: Created slice system-B.slice.
```

**Comment by thx1111** [comment]
Ha!  Thank you Andrei!

Also, it seems to me that the *explicit* "Requisite=sys-subsystem-net-devies-%i.device" should not be needed, since systemd should *not* be propagating a "start" on a nonexistent device, whatever the circumstances.  At the least, this should be one of the "Default Dependencies".

What do you think?

Now I wondering if this change will also resolve the other problem I was seeing, where a "WantedBy=sys-subsystem-net-devices-%p.device" or a "BindsTo= sys-subsystem-net-devices-%p.device" in a unit file - I'm still not sure which one - would cause that unit to be enqueued for start even when the listed device did not exist.  Do you know if that is the same issue, or different?  I suppose that I should download the current systemd and try it...

**Comment by thx1111** [comment]
Ok, I have git v232-278-g3099caf.

Running B@dummy.service, there is:
```
 ip[6247]: Device "dummy" does not exist.
 systemd[1]: Created slice system-B.slice.
 systemd[1]: Starting Service Unit B@dummy...
 systemd-udevd[6251]: Could not generate persistent MAC address for dummy0: No such file or directory
 systemd[1]: B@dummy.service: Main process exited, code=exited, status=1/FAILURE
 systemd[1]: Failed to start Service Unit B@dummy.
 systemd[1]: B@dummy.service: Unit entered failed state.
 systemd[1]: B@dummy.service: Failed with result 'exit-code'.
```
Again, `Starting Service Unit` and `result 'exit-code'`, and not `result 'dependency'`.

Andrei, do I have the same "current systemd" that you are testing?  It would seem not.

I cloned from: `https://github.com/systemd/systemd.git`.  Is that correct?

**Comment by arvidjaar** [comment]
@thx1111 
If you use service definition from https://github.com/systemd/systemd/issues/4756#issuecomment-263936104, this is expected.

**Comment by thx1111** [comment]
I don't understand - what is expected?  Which service definition?

You showed:
```
[Unit]
Description=Service Unit %P@%I
Requisite=sys-subsystem-net-devies-%i.device
[Service]
Type=oneshot
ExecStart=/usr/bin/ip link show dev %I
```
What is different?

**Comment by arvidjaar** [comment]
> What is different?

Your service definition also contains `BindsTo`. `BindsTo` adds start job for device, which apparently satisfies `Requisite`. Check `systemctl list-jobs`.

**Comment by thx1111** [comment]
Ah - No.  I see now, as Lennart has been saying, `Requisite=` does not work without `After=`.  I am wondering if the service file you tested is actually the service file you are showing?

Of course, this `After=` requirement goes against the assertion that start/stop dependencies are "orthogonal" to ordering dependencies.  Without `After=`, then `Requisite=` does nothing at all.  It seems to me that this way of things is broken still, though I suppose there is a "hack" to make it work, using `After=`.
```
[Unit]
Description=Service Unit %P@%I
Requisite=sys-subsystem-net-devies-%i.device
After=sys-subsystem-net-devies-%i.device
[Service]
Type=oneshot
ExecStart=/usr/bin/ip link show dev %I
```
The command is: `$ sudo systemctl start B@dummy.service`.

This gives `failed with result 'dependency'`.  The journal log shows:
```
 systemd[1]: sys-subsystem-net-devies-dummy.device is not active.
 systemd[1]: Dependency failed for Service Unit B@dummy.
 systemd[1]: B@dummy.service: Job B@dummy.service/start failed with result 'dependency'.
```
Without `After=`, the journal log gives `Failed with result 'exit-code'`.

Under any circumstances, before or after the 90 second timeout, and with or without `After=`, there is:
```
$ systemctl list-jobs
No jobs running.
```
Regardless,
`BindsTo=sys-subsystem-net-devies-%i.device`
and
`WantedBy= sys-subsystem-net-devices-%i.device`
are essential to "enabling/installing" and operating a pluggable/removable device, which is the entire reason for fiddling with `Requisite=` at all. 

There would be no value in having a functioning `Requisite=` dependency if it failed to work correctly in the context of a `BindsTo=` dependency.

And then, including `BindsTo=sys-subsystem-net-devies-%i.device` in the service file, in combination with the apparently required `After=sys-subsystem-net-devies-%i.device`, things get ugly, because systemd still tries to "start" the nonexistent/"removed" removable device, and the command hangs for the entire time out period.  The journal then shows:
```
 systemd[1]: sys-subsystem-net-devies-dummy.device: Job sys-subsystem-net-devies-dummy.device/start timed out.
 systemd[1]: Timed out waiting for device sys-subsystem-net-devies-dummy.device.
 systemd[1]: Dependency failed for Service Unit B@dummy.
 systemd[1]: B@dummy.service: Job B@dummy.service/start failed with result 'dependency'.
 systemd[1]: sys-subsystem-net-devies-dummy.device: Job sys-subsystem-net-devies-dummy.device/start failed with result 'timeout'.
```
When this happens on boot, the boot process hangs for 90 seconds, and not even the login process is available during the timeout, let alone hanging the command line.

`sys-subsystem-net-devies-dummy.device` **is not a proper "Job", despite what  the journal says.  A *device* has no `[Service]` section, and has no `ExecStart` command.**

As it is, this is ridiculous anyway, because `BindsTo=` is only interesting as a Reverse Stop dependency.  "Overloading" it with a Forward Start function is entirely unnecessary, since, if a Forward Start was really really needed, a `Wants=` dependency could already be written into the service file.  Is anybody actually using the Forward Start function of `BindsTo=`?

As I argued in https://github.com/systemd/systemd/issues/4787, systemd is propagating a "start" from a "failed" unit, **and**, in this case, this is not a situation where "`Wants` are evaluated at job scheduling time, not at job execution time".  Here, there is an ordering, because, for some unclear reason, `Requisite=` does not work without `After=`.  So, the job being scheduled is already well past the point at which `failed with result 'dependency'` has been determined.

Obviously the systemd scheduler is oblivious to this failed state.

Interestingly, at least systemd did not try to run the `[Service]` section of the service file.

It seems to me that the simple fix is to not have the `After=` ordering on the *device*, and then there would be no hanging the boot process or command line and no pointless waiting for a nonexistent/removed device.

If `Requisite=` were correctly operating upon the "projected"/"job scheduling time" state of the start/stop dependencies, then an evaluation would be based upon the existence or nonexistence of the listed device *at job scheduling time*.  When the device does not exist, the start dependency fails, as `result 'dependency'`, and the job start is not scheduled.  There should be no need to consider ordering, with `After=`, or otherwise.

Why does `Requisite=` *not* already operate that way?
Did you actually get it work without `After=`?

**Comment by thx1111** [comment]
@arvidjaar
Hey Andrei - Have you thought any more about what the issue is here, why I'm getting a different result?  Are you using a different code base?  Or was there something else?

**Comment by thx1111** [comment]
Also with git systemd 232.r278.g3099caf, I see:
```
 systemd[1]: Started bond0 Interface Master.
 systemd[1]: master@bond0.service: Unit is bound to inactive unit sys-subsystem-net-devices-bond0.device. Stopping, too.
 systemd[1]: Requested transaction contradicts existing jobs: Transaction is destructive.
 systemd[1]: master@bond0.service: Failed to enqueue stop job, ignoring: Transaction is destructive.
 systemd[1]: Unecessary job for sys-subsystem-net-devices-wlp0s26u1u1.device was removed.
 systemd[1]: Unecessary job for sys-subsystem-net-devices-bridge0.device was removed.
 systemd[1]: Unecessary job for sys-subsystem-net-devices-wlp0s26u1u2.device was removed.
```

`master@bond0.service` is the unit which creates the device `sys-subsystem-net-devices-bond0.device`, so running the unit is the correct action.  But then, `master@bond0.service` does *not* have any `Requisite=sys-subsystem-net-devices-bond0.device` dependency, and something else must have triggered the "stop job".  To my earlier thought that `Requisite=` should be a default dependency, then this is an example where a default `Requisite` causes this "Requested transaction contradicts existing jobs".  It might be better to just have a policy which says that `Requisite` has to be explicit.

And then, later in the journal log, there are those entries like `Unecessary job for sys-subsystem-net-devices-wlp0s26u1u1.device was removed.`, and yet still, there is later:
```
 ip[399]: Cannot find device "wlp0s26u1u2"
 systemd[1]: wlp0s26u1u2@bond0.service: Main process exited, code=exited, status=1/FAILURE
 ip[400]: Cannot find device "wlp0s26u1u1"
 systemd[1]: Failed to start Enslaved wlp0s26u1u2@bond0.
 systemd[1]: wlp0s26u1u2@bond0.service: Unit entered failed state.
 systemd[1]: wlp0s26u1u2@bond0.service: Failed with result 'exit-code'.
 systemd[1]: wlp0s26u1u1@bond0.service: Main process exited, code=exited, status=1/FAILURE
 systemd[1]: Failed to start Enslaved wlp0s26u1u1@bond0.
 systemd[1]: wlp0s26u1u1@bond0.service: Unit entered failed state.
 systemd[1]: wlp0s26u1u1@bond0.service: Failed with result 'exit-code'.
```
where these units *do* have the `Requisite=...device` dependency, but systemd is running the `[Service]` section anyway, with `result 'exit-code'`.  Here though, there is no `After=...device` dependency, and so the units to not hang start-up or generate a time-out.

Presumably, in the current code base, these units would not run the service, and would see `result 'dependency'`?

**Comment by arvidjaar** [comment]
> Without `After=`, then `Requisite=` does nothing at all.

`Requisite` (and other similar directives) define, which jobs are additionally queued when you submit start/stop job for a unit. `After` (and other similar directives) define ordering *between these jobs*. What documentation does not tell, `Requisite` also queues a job - "check if other unit is active *or is being activated*". So _if_ both units are started as part of the same transaction, _then_ you indeed need `After` because otherwise condition "is being activated" is satisfied immediately, without waiting for other unit to become active.

The fact that question "is this unit active" is satisfied by "this unit is being activated" is certainly subject to discussion.

> `BindsTo=` is only interesting as a Reverse Stop dependency. "Overloading" it with a Forward Start function is entirely unnecessary, since, if a Forward Start was really really needed, a `Wants=` dependency could already be written into the service file.

Yes, another example where this more simple semantic appears to be useful is in #4733.

> Is anybody actually using the Forward Start function of `BindsTo=`?

It is more complicated. As was mentioned several times recently, systemd really is job engine and ordering dependencies are defined between jobs. So to wait for a device, it needs (to fake) start job for this device - otherwise there is nothing to wait for. In this respect, every use of `BindsTo` today relies on forward start function to queue this (fake) start job.

**Comment by thx1111** [comment]
> Requisite ... define[s] which jobs are additionally queued when you
> submit start/stop job for a unit.

man systemd.unit: "Requisite= ... if the units listed here are not started already, they will not be started".

There appears to be a contradiction there.  I am inferring that "which jobs" are the same "units listed" and that "queued when you submit start" means "queued to start" which contradicts "will not be started".

> What documentation does not tell, Requisite also queues a job -
> "check if other unit is active *or is being activated*" ... /if/ both units
> are started as part of the same transaction

I am guessing that this refers to some internal systemd mechanism for tracking the activation state of the set of units?

> otherwise condition "is being activated" is satisfied immediately,
> without waiting for other unit to become active.
>
> The fact that question "is this unit active" is satisfied by
> "this unit is being activated" is certainly subject to discussion.

This is an issue of the "proper time" reference, whether at the end of the prior transaction, or at the end of "this" transaction.  I am left with the impression that "proper time" has something to do with all the talk about `After=`, but I am not familiar with the actual code.  Presumably, `After=` would shift the point of view from "the end of the previous transaction" to "the end of *this* transaction".  But then, that would suggest a design problem, and a lack of consistency with the definition of the "proper time" reference.

I still do not see that this has anything *inherently* to do with `BindsTo` and `Requisite`.  `BindsTo` should not be creating any device unit that would be satisfying `Requisite`, either at the end of the previous transaction, or at the end of the present transaction.  If I understand, you agree, and are just explaining how the code actually works at the moment.

We are getting ahead of ourselves.  Your test case does NOT have a `BindsTo` dependency.  So this question of how `BindsTo` will interact with `Requisite` is hypothetical.  I have not been able to reproduce your test results, with or without `After=`.  We must be working from some different code base.  And I do not know how systemd is going to act after all the changes being made, from https://github.com/systemd/systemd/pull/4733.  If what has been proposed initially is carried out, then systemd will become useless for properly managing devices.  At least now, systemd works, and just has "quirks".

**Comment by arvidjaar** [comment]
> This is an issue of the "proper time" reference, whether at the end of the prior transaction, or at the end of "this" transaction.

I apologize for confusion. I'll try once more.

Systemd is job manager. User submits job to start unit (implicitly or explicitly, does not matter). Systemd collects all `Requires`, `Requisite` etc in unit definition and queues *additional* jobs to start (for `Requires`) or check (for `Requisite`) units mentioned in these directives. Collectively all such jobs form transaction, although it is more or less implementation detail.

After all those jobs have been queued systemd goes and picks up jobs for execution. The order in which it selects jobs is determined by `After` and `Before` directives. If A has `After=B` then systemd executes job for A only after job for B has finished. This applies to both "start" and "check" job.

Which means that I was wrong and `Requisite` *does* require `After` to work properly. If A has `Requisite=B` but does not have `After=B` both start job for A and check job for B are chosen for execution concurrently. It is unpredictable which job will be selected first or whether one job will be selected before or after another job completes. Which explains why we see different results - because on my system order of execution happened to be the "right" one, on yours - not. So to actually delay starting of A until check for B is complete you *must* use `After=B`.

> I still do not see that this has anything inherently to do with BindsTo and Requisite. BindsTo should not be creating any device unit that would be satisfying Requisite

If A has both `Requisite=B` and `BindsTo=B`, then starting of A causes two additional jobs to be queued - start of B and check of B. The second job gets dropped as redundant (I am not sure if this happens across transactions on only inside single transaction but that's irrelevant in this case). So you are left with a single additional job to start B - which in case of device means "wait for device B to appear".

>  I have not been able to reproduce your test results, with or without After=.

You have enough information to analyze *full* dependency chain on your system to find out what happens.

**Comment by thx1111** [comment]
> I'll try once more.

Thanks very much for that.

> Systemd is job manager.  ...
> Systemd collects ... and queues additional jobs to ... check (for Requisite)
> units mentioned in these directives.
> ...
> If A has Requisite=B but does not have After=B both start job for A and
> check job for B are chosen for execution concurrently.
> It is unpredictable which job will be selected first

Aha - that helps clarify what is happening.  And yet:

I am uncomfortable with this way of describing job management.  In the end, systemd does - presumably - exactly two things: Starting and Stopping a "job".  The *mechanism* that systemd uses to determine when and how to do that starting and stopping is more of an "internal" matter, and not something that the administrator should have to consider.  We could say that systemd "abstracts" the process of starting and stopping, using a language of "dependencies" and "ordering".

Here, there is introduced a third fundamental action, "checking".  I am uncomfortable with the idea that "checking" should be in the same class of actions as "starting" and "stopping".  I would think that "job checking" is more of an internal mechanism.

The reason I describe all that pedantic "nit picking" is because there has been this talk about `After=` having to be written explicitly in a unit file, to have `Requisite=` function properly.  Effectively, it seems to me that `After=` is being used improperly, in this case, to remedy an improper implementation of "checking".

More simply, where proper operation demands that "checking" must occur *after* "starting", that is an implementation detail that should not be exposed to the administrator.

But then, there is still something else wrong here, where writing an explicit `After=` causes the "checking" to hang for the timeout period.  It seems to me that there are two different kinds of "After" being confused in this discussion.  One kind of "After" is needed for the proper operation of "checking", only applies to the "dependency state", and is an internal implementation mechanism.  Another kind of "After" applies to "service execution", invokes the "DefaultTimeoutStopSec" routine, and is an element of the external, administrator visible interface.

It is the conflation of these two distinct kinds of "After" that would be a reason for the difficulties.  An explicit `After=` ordering, written into the unit file, is not an appropriate "band-aid" for an improper implementation of "checking".  Often, this kind of conflation suggests that too few variables are being used to cover the actual number of degrees-of-freedom.

> ... starting of A causes two additional jobs to be queued - start of B and check of B.
> The second job gets dropped as redundant
> which in case of device means "wait for device B to appear".

Again, this sounds to me like a problem with considering "checking" to be in the same class as "starting".  In this case, given the choice of which "job" to drop, and which "job" to "queue", checking and starting are not at all of the same nature.

Clearly - clearly - "wait for device B to appear" is not at all like "check for the existence of B".

Can you be sure that this is what systemd is really doing?  What is being described seems so glaringly inappropriate as to not be possible, choosing "wait" instead of "check" in this case.

**Comment by thx1111** [comment]
The documentation for "Requisite=" reads: "Similar to Requires=. However, if the units listed here are not started already, they will not be started and the starting of this unit will fail immediately."

The "Requisite=" dependency description is misleading, in that it seems not to function this way with "device" units.

However, the dependency "ConditionPathExists= /sys/class/net/%i" in combination, as for instance:
```
After= sys-subsystem-net-devices-%i.device
BindsTo= sys-subsystem-net-devices-%i.device
ConditionPathExists= /sys/class/net/%i
```
instead of "Requisite=", is effective in preventing systemd from attempting to start the dependent unit when the referenced device unit does not exist.

This issue seems to now have been addressed indirectly in systemd.unit(5), with the added section at "Requires=":
>Note that this dependency type does not imply that the other unit always has to be in active state when this unit is running. Specifically: failing condition checks (such as ConditionPathExists=, ConditionPathIsSymbolicLink=, ... — see below) do not cause the start job of a unit with a Requires= dependency on it to fail. Also, some unit types may deactivate on their own (for example, a service process may decide to exit cleanly, or a device may be unplugged by the user), which is not propagated to units having a Requires= dependency. Use the BindsTo= dependency type together with After= to ensure that a unit may never be in active state without a specific other unit also in active state (see below).
