### ISSUE TITLE
RFC: add command to show leases currently handed out to clients of DHCP server

### ISSUE THREAD

**Issue by fpqc** [systemd/systemd#4759]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with
232

### Used distribution

> Arch

It would be extremely convenient if there was a /proc interface for active DHCP leases when systemd-networkd is acting as a DHCP server.  Lots of el-cheapo home routers create a table showing active DHCP leases, but right now there is no way to see the current DHCP leases from a DHCP server.  

It would be even cooler, maybe, if you could send a FORCERENEW to a DHCP client by writing to one of these proc entries.  

If not a proc mount, it would be nice to be able to do this with some sort of commandline like 

`networkctl renew dhcp --force 10.1.0.25`

**Comment by poettering** [comment]
uh? networkd is not a kernel module, and cannot provide file systems hence. (And even if so, file system APIs are highly problematic for many reasons).

But yeah, we should make this data available somehow, but not as "/proc"

**Comment by AlbertVos** [comment]
I think this is part of a more general problem: A general framework for retrieving information from systemd is missing. There should be a general interface for requesting information from systemd. I think there should a away to address a module/service and get information from it, eg: a mqtt like interface.

But anyway I'm also very interested in the leases list.

**Comment by mdzw** [comment]
It looks like the "extra credit" feature request of `forcerenew` is now available in networkctl (although you can't aim it at a specific client).

However, listing the bound leases is still unavailable. I may give it a shot, unless this is already a work-in-progress for someone else.

**Comment by kerberizer** [comment]
Sorry if I'm missing something here, but just to point out that `networkctl status DEVICE` seems to already list the DHCP leases.
```
(...)
           Offered DHCP leases: 172.31.4.10 (to f0:fe:6b:*redacted*)
                                172.31.3.251 (to f0:fe:6b:*redacted*)
                                172.31.4.19 (to f0:fe:6b:*redacted*)
(...)
```

**Comment by yuwata** [comment]
That's in my TODO list https://github.com/yuwata/systemd/blob/todo-yuwata/TODO-yuwata.
