### ISSUE TITLE
/dev/disk/by-uuid/* and /dev/disk/by-label/* symbolic links missing after udev upgrade

### ISSUE THREAD

**Issue by zlinuxman** [systemd/systemd#476]
After upgrading udev from version 215 to version 220, I found that the
symbolic links in the /dev/disk/by-uuid and /dev/disk/by-label directories
are no longer being created on my system.  I traced the problem to
/lib/udev/rules.d/60-persistent-storage.rules.  Under 215, there was a
line in this file which read like this:

KERNEL=="fd_|mtd_|nbd_|gnbd_|btibm_|dm-_|md_|zram_|mmcblk[0-9]*rpmb", GOTO="persistent_storage_end"

under 220, this had been changed to

KERNEL!="loop_|mmcblk_[0-9]|msblk_[0-9]|mspblk_[0-9]|nvme_|sd_|sr_|vd_|bcache*", GOTO="persistent_storage_end"

In other words, the old rule gave a list of device categories that will be skipped.
All other device categories are included by default.  The new rule gives a list
of device categories that will _not_ be skipped.  All other device categories are
skipped by default.  But you've left some out.  I see that already in 221 you've
added xvd\* to the list.  And there's a commit not yet included in a release for cciss*
devices.  My hardware needs i2o\* to be in the list.  (i2o hardware
RAID device).  And I see that dasd\* isn't there either (mainframe disk devices for
the s390x architecture).  I'll bet there's more that need to be added.  For now,
I've reverted to the old rule and everything works fine again.  Of course, I'll
have to remember to change it again every time the package is upgraded.  :-(

It's up to you whether it's easier to list the device categories that you want,
or the device categories that you don't want.  But creating unnecessary symbolic
links really doesn't do any harm.  Not creating ones that are depended on may
result in an unbootable system.  Think about it.

At a minimum, please add i2o\* and dasd\* devices to the list.  More generally,
consider whether the list should exclude unwanted devices or include wanted ones.

Respectfully submitted,

Stephen M. Powell

P.S. Reference Debian bug number 790823
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790823)

**Comment by poettering** [comment]
Yeah, we turned this from a blacklist into a whitelist.

Any chance you can prep a patch that adds the i20 and dasd matches?

**Comment by kaysievers** [comment]
There are too many devices which should not be accessed by udev, and they are added to new kernels, hence the whitelist and not a blacklist.

I cannot find any i2o block devices in the kernel sources. How are they actually named in /sys?

**Comment by zlinuxman** [comment]
On Sun, 05 Jul 2015 10:22:01 -0400 (EDT), Kay Sievers wrote:

> There are too many devices which should not be accessed by udev,
> and they are added to new kernels, hence the whitelist and not
> a blacklist.

I see.

> I cannot find any i2o block devices in the kernel sources.
> How are they actually named in /sys?

The naming pattern is /sys/block/i2o!hd*

I've heard rumors, though I have not confirmed it myself, that
i2o support has been removed starting with kernel 4.2.  So depending
on what kernel version you are looking at, that may be true.
If true, this is a disappointment to me, as I regularly use a machine
that has an i2o RAID device.  I may have to create a custom kernel that
has i2o support added back.  But that's another subject.  I currently
use a 3.16 kernel, which does support i2o.  Here is the output of

   udevadm info -a /dev/i2o/hda6

which is the root partition on my system:

---

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/pci0000:00/0000:00:02.0/0000:01:1d.0/0000:02:02.0/iop0/0:207/block/i2o!hda/i2o!hda6':
    KERNEL=="i2o/hda6"
    SUBSYSTEM=="block"
    DRIVER==""
    ATTR{alignment_offset}=="0"
    ATTR{discard_alignment}=="0"
    ATTR{inflight}=="       0        0"
    ATTR{partition}=="6"
    ATTR{ro}=="0"
    ATTR{size}=="39059456"
    ATTR{start}=="17774592"
    ATTR{stat}=="   20926    11427   947618   358336     6532    18245   200728   194008        0   109352   552612"

  looking at parent device '/devices/pci0000:00/0000:00:02.0/0000:01:1d.0/0000:02:02.0/iop0/0:207/block/i2o!hda':
    KERNELS=="i2o/hda"
    SUBSYSTEMS=="block"
    DRIVERS==""
    ATTRS{alignment_offset}=="0"
    ATTRS{capability}=="10"
    ATTRS{discard_alignment}=="0"
    ATTRS{events}==""
    ATTRS{events_async}==""
    ATTRS{events_poll_msecs}=="-1"
    ATTRS{ext_range}=="16"
    ATTRS{inflight}=="       0        0"
    ATTRS{range}=="16"
    ATTRS{removable}=="0"
    ATTRS{ro}=="0"
    ATTRS{size}=="286748672"
    ATTRS{stat}=="   43983    13061  4691784   722004   145254   780184 10189010  6771428        0   528888  7492920"

  looking at parent device '/devices/pci0000:00/0000:00:02.0/0000:01:1d.0/0000:02:02.0/iop0/0:207':
    KERNELS=="0:207"
    SUBSYSTEMS=="i2o"
    DRIVERS=="block-osm"

  looking at parent device '/devices/pci0000:00/0000:00:02.0/0000:01:1d.0/0000:02:02.0/iop0':
    KERNELS=="iop0"
    SUBSYSTEMS==""
    DRIVERS==""

  looking at parent device '/devices/pci0000:00/0000:00:02.0/0000:01:1d.0/0000:02:02.0':
    KERNELS=="0000:02:02.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="PCI_I2O"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x0e0001"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0xa501"
    ATTRS{dma_mask_bits}=="64"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="4"
    ATTRS{irq}=="28"
    ATTRS{local_cpulist}=="0-7"
    ATTRS{local_cpus}=="ff"
    ATTRS{msi_bus}==""
    ATTRS{subsystem_device}=="0xc066"
    ATTRS{subsystem_vendor}=="0x1044"
    ATTRS{vendor}=="0x1044"

  looking at parent device '/devices/pci0000:00/0000:00:02.0/0000:01:1d.0':
    KERNELS=="0000:01:1d.0"
    SUBSYSTEMS=="pci"
    DRIVERS==""
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{d3cold_allowed}=="0"
    ATTRS{device}=="0x1460"
    ATTRS{dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="0"
    ATTRS{local_cpulist}=="0-7"
    ATTRS{local_cpus}=="ff"
    ATTRS{msi_bus}=="1"
    ATTRS{subsystem_device}=="0x0000"
    ATTRS{subsystem_vendor}=="0x0000"
    ATTRS{vendor}=="0x8086"

  looking at parent device '/devices/pci0000:00/0000:00:02.0':
    KERNELS=="0000:00:02.0"
    SUBSYSTEMS=="pci"
    DRIVERS==""
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{d3cold_allowed}=="0"
    ATTRS{device}=="0x2543"
    ATTRS{dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="0"
    ATTRS{local_cpulist}=="0-7"
    ATTRS{local_cpus}=="ff"
    ATTRS{msi_bus}=="1"
    ATTRS{subsystem_device}=="0x0000"
    ATTRS{subsystem_vendor}=="0x0000"
    ATTRS{vendor}=="0x8086"

  looking at parent device '/devices/pci0000:00':
    KERNELS=="pci0000:00"
    SUBSYSTEMS==""
    DRIVERS==""

---

I can provide similar information for dasd devices if needed.

## 

  .''`.     Stephen Powell    <zlinuxman@wowway.com>
 : :'  :
`. `'`
   `-

**Comment by gregkh** [comment]
Yes, i2o has been removed for 4.2.  But, we still have the old dpt_i2o driver around, if you are using that one, you should be fine as it has survived.

If you rely on i2o hardware, please work with the kernel community to maintain it, as it is long out of support from what we could tell, so that is why it was removed (that, and there was no maintainer for the kernel code...)

**Comment by kaysievers** [comment]
The dasd block devices are added to the list, the i2o ones are gone from the kernel. Closing.

**Comment by zlinuxman** [comment]
On Sun, 05 Jul 2015 20:30:18 -0400 (EDT), Greg Kroah-Hartman wrote:

> Yes, i2o has been removed for 4.2.  But, we still have the old dpt_i2o
> driver around, if you are using that one, you should be fine as it has
> survived.

No such luck.  I need kernel modules i2o_core, i2o_block, and i2o_config.

> If you rely on i2o hardware, please work with the kernel community to
> maintain it, as it is long out of support from what we could tell,
> so that is why it was removed (that, and there was no maintainer for
> the kernel code...)

I would be happy to do that, in principle.  In practice, I'm not sure that
I will meet your requirements as a maintainer.  I do not have any
specialized knowledge of i2o hardware or software.  I have a server in
active use that uses i2o, and I can certainly test new kernels for you,
but I don't feel confident enough to put myself forward as an official
maintainer of a device driver for the official kernel.  I might try to
create an out-of-kernel-source-tree kernel module source package for my
own use; and if it works, I'd be willing to publish it under GPL, on an
as-is basis.  But whether I can pull it off or not remains to be seen.

## 

  .''`.     Stephen Powell    <zlinuxman@wowway.com>
 : :'  :
`. `'`
   `-

**Comment by thomasmey** [comment]
Same here for the UML block device. Any ideas how to fix this?

**Comment by thomasmey** [comment]
diff --git a/rules/60-persistent-storage.rules b/rules/60-persistent-storage.rules
index 5ab03fc..0b14bb4 100644
--- a/rules/60-persistent-storage.rules
+++ b/rules/60-persistent-storage.rules
@@ -6,7 +6,7 @@
 ACTION=="remove", GOTO="persistent_storage_end"

 SUBSYSTEM!="block", GOTO="persistent_storage_end"
-KERNEL!="loop_|mmcblk_[0-9]|msblk_[0-9]|mspblk_[0-9]|nvme_|sd_|sr_|vd_|xvd_|bcache_|cciss_|dasd_", GOTO="persistent_storage_end"
+KERNEL!="loop_|mmcblk_[0-9]|msblk_[0-9]|mspblk_[0-9]|nvme_|sd_|sr_|vd_|xvd_|bcache_|cciss_|dasd_|ubd*", GOTO="persistent_storage_end"

 # ignore partitions that span the entire disk
 TEST=="whole_disk", GOTO="persistent_storage_end"

**Comment by poettering** [comment]
@thomasmey could you file a separate PR regarding the UML block devices please, if this is still any issue?
