### ISSUE TITLE
networkd: ProxyARP= vs. ARPProxy= confusion

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#4768]
.netdev files have an ARPProxy= option (for the vxlan stuff) right now, and .network files a ProxyARP= option. Now, the question is how both relate. @ssahani can you elaborate on this? What do the two options do precisely?

I have the suspicion we should rename at least one of them, if they refer to the same concept just on different levels (which I think they do?).

Note that we prefixed most IPV6-specific networkd settings with "IPv6" (i.e. `IPv6AcceptRouterAdvertisements=` and so on). Following this logic, we should probably rename both options, so that they become `IPv4ProxyARP=` or so.

@ssahani any chance you can cook up a patch for that?

This came up in the discussions around: https://github.com/systemd/systemd/pull/4744#discussion_r89864520

**Comment by Mic92** [comment]
There is also no documentation for `ARPProxy`.

**Comment by poettering** [comment]
@Mic92 hmm, there is, in networkd.netdev(5). It's not overly useful (as it just says: "A boolean. When true, enables ARP proxying."), but it's there...

**Comment by ssahani** [comment]
VxLan ARP proxy is different as we are sending the whole encapsulate MAC-based inside a UDP packet .
We deal with two network segments http://events.linuxfoundation.org/sites/events/files/slides/2013-linuxcon.pdf

**Comment by poettering** [comment]
It might be good to explain this briefly in the man page...

**Comment by ssahani** [comment]
Sure :)

**Comment by poettering** [comment]
the options should still be renamed...

**Comment by poettering** [comment]
Reopening since ProxyARP= should still be renamed to IPv4ProxyARP=, and #4891 didn't fix that.

**Comment by flokli** [comment]
@poettering: I think there are still some small places where 'proxy_arp' is used without the 'ipv4' prefix, namely `link_set_proxy_arp` and `link_proxy_arp_enabled` in `networkd-link.c` and `proxy_arp` in `networkd-network.c|h`.

**Comment by andrejpodzimek** [comment]
Out of curiosity, how is `IPv4ProxyARP` supposed to work without static IP addresses configured in all proxied networks? The `[DHCPServer]` section doesn't seem to support the assignment of larger subnets to individual hosts than those derived from static IPv4 addresses of the router's interfaces. For example, for IPv4 proxy ARP on two networks, one would need to configure

* static addresses `10.0.1.1/24` and `10.0.0.1/24` on the router's interfaces `A` and `B`. [easy]
* dynamic DHCP addresses from subnet `10.0.0.0/23` with actual address pool `10.0.1.0/24` for clients behind interface `A`. [can't be configured in systemd-networkd]
* dynamic DHCP addresses from subnet `10.0.0.0/23` with actual address pool `10.0.0.0/24` for clients behind interface `B`. [can't be configured in systemd-networkd]

Do I understand it well that although the ARP proxy can be switched on (in terms of writing the corrseponding `sysctl` variables), it is currently impossible to create a DHCP-configured ARP-proxied network setup?

**Comment by flokli** [comment]
I'm not sure if I understand the question correctly.

Enabling `IPv4ProxyARP` on interfaces `A` and `B` would make sense if you configured `10.0.0.0/24` on the routers interface `A` and `10.0.1.0/24` on `B`, but still have some clients on one or both sides configured with a `/23` netmask, and possibly sending ARP requests outside their `/24`.

With enabled `IPv6ProxyARP`, the router would proxy those ARP requests to the other interface, thus creating a pseudo-bridge between `A` and `B`.

See also [here](http://www.tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.bridging.proxy-arp.html).

**Comment by andrejpodzimek** [comment]
The key question was: How do I configure ProxyARP in combination with a DHCP server? At the moment it appears to be impossible to set a /24 subnet on both server interfaces, but to announce a /23 subnet using DHCP. It looks like the only option would be to use an external DHCP server instead of networkd’s built-in one. (Or a static configuration for all clients.)

**Comment by flokli** [comment]
Yes, this might be not supported. In those cases, I'd suggest to use another DHCP server.

I see Proxy ARP merely as a a workaround, like when you want to slowly segment a subnet with a lot of machines statically configured to a smaller size, or when you have to support legacy CPEs not supporting the desired netmask (like /32 host routes).
