### ISSUE TITLE
Automatically pre-select the last used boot entry in the systemd-boot EFI boot menu

### ISSUE THREAD

**Issue by doraskayo** [systemd/systemd#477]
When no default boot option is set in loader.conf ("default" is omitted) and the "LoaderEntryDefault" efivar isn't set, automatically pre-select (highlight) the last used boot entry in the EFI boot menu. In the case of a first-time boot, keep the current behavior of selecting the last suitable boot entry.

Use cases:
- Restarting an OS without having to manually select it again on boot. A system restart would always return to the same OS from which it was executed.
- Returning from hibernation would highlight the hibernated OS on boot, reducing the chance of accidental boot failures when a different OS tries to boot and mount a locked filesystem.

(The above use cases assume the OS was initially boot using systemd-boot)

Note that this functionality should apply to any OS boot entry, including auto-detected ones. (Windows and OSX, for example)

**Comment by kaysievers** [comment]
We do not want to write to the EFI variables unless such action is explicitly requested by the user. The EFI variable store is fragile on some machines and it should not be touched by any action during normal operations.

There is the 'd' key for for default, to set the default manually.

**Comment by AlexWayfer** [comment]
@kaysievers May be it can be optional? Under the responsibility of the user.

**Comment by mirh** [comment]
#5739?

**Comment by AlexWayfer** [comment]
@mirh `command to modify default loader entry` ≠ `Automatically pre-select the last used boot entry in the systemd-boot EFI boot menu`

I found #909, but it also closed :(

**Comment by cecton** [comment]
Is it possible to boot the last booted entry now? Or is it still a problematic thing to implement?

To be clear on the behavior: it's **not** about adding a hotkey to change the default boot entry, it's about updating the default boot entry when the user boots a different entry than the default one.

It's particularly useful for Windows dual-boot nowadays because when you do a Windows Update and select "Update and shutdown", currently Windows reboots to finish the updates and then only shutdown. It works great when you have a single OS on the machine but it's super annoying when you have a dual-boot because the other OS gets booted and the PC does not shut down as the user requested.

**Comment by blefev** [comment]
I think this is possible now using @saved. 

[See the docs here](https://man.archlinux.org/man/loader.conf.5#OPTIONS)

Also see [this Reddit comment](https://www.reddit.com/r/EndeavourOS/comments/1009rr8/comment/j2h024d/?utm_source=share&utm_medium=web2x&context=3)

**Comment by NatoBoram** [comment]
> I think this is possible now using `@saved`.
> 
> * https://man.archlinux.org/man/loader.conf.5#OPTIONS

Thanks @blefev.

Configuring this is a bit hard and unintuitive, so for the uninitiated that's following this thread, here's how to do it in Pop OS:

```sh
nano /boot/efi/loader/loader.conf
```

```conf
default @saved
timeout 5
```

I suspect the steps are about the same regardless of the distribution.

**Comment by blefev** [comment]
Yes thanks for the simplified instructions! That's exactly it. Confirmed this works like a charm in Arch with systemd-boot.

**Comment by alexfrostdev** [comment]
> here's how to do it in Pop OS:

Pop Os 22.04  has systemd 249 and `@saved` added after 251. The next Pop Os release date is unknown
