### ISSUE TITLE
machinectl --no-legend list-images lists 'No Images'

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4777]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see
```
# machinectl --no-legend list-images
dokuwiki   directory no  n/a   n/a     n/a     
repository directory no  n/a   n/a     n/a     
work       directory no  n/a   n/a     n/a     
```

### In case of bug report: Unexpected behaviour you saw
```
# machinectl --no-legend list-images
dokuwiki   directory no  n/a   n/a     n/a     
repository directory no  n/a   n/a     n/a     
work       directory no  n/a   n/a     n/a     
No images.
```

### In case of bug report: Steps to reproduce the problem

Create some machines and execute `machinectl --no-legend list-images`

**Comment by poettering** [comment]
Fixed by #4593.
