### ISSUE TITLE
systemd-networkd uses physical interface's MAC Address for VLAN interface

### ISSUE THREAD

**Issue by akoeltringer** [systemd/systemd#4783]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231

### Used distribution

> CoreOS 1235.0.0

### In case of bug report: Expected behaviour you didn't see

> According to [this post](http://serverfault.com/questions/787350/systemd-networkd-mac-address-generation-for-vlan-interfaces) and the [netdev man page](https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#) the MAC Address of a VLAN interface 
>> is generated based on the interface name and the machine-id(5)
>
> ... which should(?) result in a different MAC Address than the one of the underlying interface.

### In case of bug report: Unexpected behaviour you saw

> The MAC Address of the VLAN interface is the **same** as the MAC Address of the underlying interface:
![screenshot_coreos_ip_address_output](https://cloud.githubusercontent.com/assets/20040973/20790671/ac09c2f6-b7b9-11e6-8f1c-00236bd53358.png)

> So, I guess this is either a bug or the documentation is outdated?
>
> I have a problem with this because I have `systemd-networkd` unit files with matching 
> * based on the `MACAddress` for physical interfaces
> * based on the `Name` for the `vlan` interfaces
>
> But, as the `vlan` interfaces now have the same `MACAddress`, the wrong unit file gets applied.

### In case of bug report: Steps to reproduce the problem

> Create the following unit files in `/etc/systemd/network`:
> * `10-vlan3.netdev`
> ```
> [NetDev]
> Name=vlan3
> Kind=vlan
> [VLAN]
> Id=3
> ```
>
> * `20-nic.network` (replace `eth4` with your interface name)
> ```
> [Match]
> Name=eth4
> [Network]
> VLAN=vlan3
> ```
>
> * `30-vlan3.network`
> ```
> [Match]
> Name=vlan3
> [Network]
> Address=10.1.0.10/24
> ```
>
> Restart `systemd-networkd`.

**Comment by poettering** [comment]
@ssahani any idea?

**Comment by ssahani** [comment]
I don't think we are generating new MAC Address of a VLAN interface according to the code.
The behaviour is same as we create 

` sudo ip link add link eth1 name eth1.8 type vlan id 8`


```
     if (!netdev->mac && netdev->kind != NETDEV_KIND_VLAN) {                                                                                                                               
                r = netdev_get_mac(netdev->ifname, &netdev->mac);                                                                                                                                                                                                                                                                                                                    
```


output created from ip link and networkd

```
5: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:40:aa:db brd ff:ff:ff:ff:ff:ff
6: eth1.8@eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:40:aa:db brd ff:ff:ff:ff:ff:ff
7: vlan3@eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:40:aa:db brd ff:ff:ff:ff:ff:ff
```

**Comment by ssahani** [comment]
We should update the man page about it.

**Comment by akoeltringer** [comment]
With `systemd` version 229 this worked as expected - i.e. the VLAN MACAddress was **different** than the one of the pysical interface (used on CoreOS 1068.8.0). 

I did a quick check with the `ip link add` command on CoreOS 1068.8.0: with this command, both MACAddresses are the **same**.

**Comment by ssahani** [comment]
https://github.com/systemd/systemd/pull/1573 is the issue.

**Comment by ssahani** [comment]
Also I looked at the kernel code `vlan.c:register_vlan_device`
It says 

 /*  Attach a VLAN device to a mac address (ie Ethernet Card).                                                                                                                                 
 *  Returns 0 if the device was created or a negative error code otherwise.                                                                                                                   
 */   

That I think this is the defined behaviour and we should close this issue.

**Comment by ssahani** [comment]
@aadamowski  Should we close this ?

**Comment by ssahani** [comment]
We need to close this issue.
