### ISSUE TITLE
systemd-stdio-bridge is not documented

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#4784]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

> git master

### In case of bug report: Expected behaviour you didn't see

A man page for all binaries installed into `/usr/bin`

### In case of bug report: Unexpected behaviour you saw

`systemd-stdio-bridge` is missing a manpage.

**Comment by poettering** [comment]
it's an internal tool, it's never supposed to be called directly. The only reason it's in $PATH, is that we invoke it on a remote system for the ssh dbus transport, where we don't know whether systemd's private directory is /usr/lib/systemd or /lib/systemd or anything else, and hence prefer relying on the search path.

I don't think this should have a man page. It's really not user-facing, and we generally don't document all internal files of systemd via man pages.

**Comment by fsateler** [comment]
I think it should be moved to `$rootlibdir/systemd` then, and always invoked via `/lib/systemd/systemd-stdio-bridge`. Or does systemd want to support systems with merged-usr but where `/lib` does not point to `/usr/lib` ?

> I don't think this should have a man page. It's really not user-facing, and we generally don't document all internal files of systemd via man pages.

By virtue of placing it in a public path, you make it user-facing.

**Comment by boucman** [comment]
would it be possible to mention in --help that it's an internal systemd tool ?

**Comment by madscientist42** [comment]
Even internal use tools need DOCUMENTATION, guys.
