### ISSUE TITLE
journald: request configured sudo privilege escalation type before giving sudo users access to system/other user logs

### ISSUE THREAD

**Issue by smithfred** [systemd/systemd#4786]
### Submission type

  - [*] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 25

### In case of bug report: Expected behaviour you didn't see

> Sudoer can't see log entries for other user (which may include e.g. sensitive file names) without following same privilege escalation as for sudo (e.g. entering password).

### In case of bug report: Unexpected behaviour you saw

> Running journalctl as member of wheel group (sudoer) showed log entries (in this case, for tracker) that contained sensitive file names for another user (files not normally visible by the user running journalctl). For the user of journalctl, sudo is configured to require password.

### In case of bug report: Steps to reproduce the problem

> Configure a user as a member of the wheel group; configure sudo access for wheel group members to require a password; run journalctl as that user, without ever escalating privileges.

I'm not sure if 'wheel' is a magic group name in journald; the man page for journald suggests it is (along with adm and systemd-journal). The latter two are groups specifically related to log access, but the former in other scenarios has privileges tied to sudo configuration, so the system administrator would expect that any privileged access is protected by that config; with journald's current behaviour that is not the case.

**Comment by gdamjan** [comment]
Access to the logs is configured with standard Linux permissions and ACLs,
groups `adm`, `wheel` and `systemd-journal` have read access to the logs.
Additionally, the user has access to its own log file.

Don't give a person `wheel` group rights if you don't want them to read your logs.

```
damjan $ getfacl /var/log/journal/xxx/system.journal 
getfacl: Removing leading '/' from absolute path names
# file: var/log/journal/xxx/system.journal
# owner: root
# group: systemd-journal
user::rw-
group::r-x                      #effective:r--
group:adm:r--
group:wheel:r--
mask::r--
other::---

damjan $ getfacl /var/log/journal/xxx/user-1000.journal 
getfacl: Removing leading '/' from absolute path names
# file: var/log/journal/xxx/user-1000.journal
# owner: root
# group: systemd-journal
user::rw-
user:damjan:r--
group::r-x                      #effective:r--
group:adm:r-x                   #effective:r--
group:wheel:r-x                 #effective:r--
mask::r--
other::---
```

**Comment by smithfred** [comment]
Are wheel rights on the journal part of journald's default config, or is that distro-specific? If it's the latter then I'll file a bug downstream.

> Don't give a person wheel group rights if you don't want them to read your logs.

This ignores the point of the bug report. If I'm wrong tell me, but the wheel group is for sudo purposes. sudo gives access to privileged resources, but *only after the authentication configured in sudoers*.

If journald's default is wheel group access to the journal, then why? It breaks the semantics of the wheel group, and access without escalation can be controlled/granted by either of the other two more semantically suitable groups (adm, systemd-journal).

**Comment by poettering** [comment]
You can configure the ACLs on the journal files the way you want. By default systemd gives users in "wheel" read access to the system journal and the journals of other users, as "wheel" is generally a mechanism to distribute privileges to users, and read access doesn't sound too wrong then.

it's up to you to change the ACLs, but note that you need to override /usr/lib/tmpfiles.d/systemd.conf if you do, as that applies /var/lib/journal ACLs on startup. Simply copy /usr/lib/tmpfiles.d/systemd.conf to /etc/tmpfiles.d/systemd.conf and comment the relevant lines. And then use setfacl to set the ACLs of your choice, dropping wheel.

But I think the current defaults make a lot of sense, and don#t think we should change them.

**Comment by smithfred** [comment]
Hi Lennart, thanks for your response. But it doesn't address either of the points raised in the original bug either:

* Why is wheel given read privileges to system/other user journals by default? Especially when there are two existing and more semantically appropriate groups that already have read access by default (adm and systemd-journal)?
* Why is it worth breaking the widely understood semantics of wheel (i.e. members can *gain* additional privileges *after* the configured sudo privilege escalation method) by making this the default?

Can you please explain *why* the current defaults make a lot of sense, given the described drawback, one which results in unexpected access to sensitive information without the privilege escalation expected from wheel membership?

**Comment by poettering** [comment]
We grant read access only, the idea is that if somebody is privileged enough to be "wheel", then read access to the logs is the baseline of things he should be able to do. There's a difference between being able to "see" something, and being able to "do" something. We just permit the former, not the latter, after all.

**Comment by smithfred** [comment]
> if somebody is privileged enough to be "wheel", then read access to the logs is the baseline of things he should be able to do

* Why should they be able to have privileged access to logs when other privileges associated by convention with wheel are contingent on the configured method of sudo privilege escalation first?
* Why aren't the other two groups that exist specifically for log access sufficient?

Can you explain what would be lost by removing wheel from the list of groups with default read access to system and other user logs? The gain would be that wheel membership would no longer confer unexpected read access to logs without privilege escalation, which is contrary to what a user would reasonably expect based on standard sudo mechanics.

**Comment by poettering** [comment]
> Why aren't the other two groups that exist specifically for log access sufficient?

"adm" is not available on all distros. and "systemd-journal" is about being able to *see* what root can see, while "wheel" is about being able to *do* what root can do. And as the latter usually is assumed to imply the former, we honour both.

> Why should they be able to have privileged access to logs when other privileges associated by convention with wheel are contingent on the configured method of sudo privilege escalation first?

Well, you configure your groups and ACLs any way you want, we just ship defaults which make sense to us. It's not unlike the sudo configuration.

Quite frankly, I *do* expect that being in "wheel" does give me certain powers. You do not think that. Which is fine. But I doubt it's right to assume that the general userbase of systemd-based system expects what you expect. I mean, i can only guess, but given the feedback we got so far on the groups thing most people weren#t too surprised by this...

**Comment by smithfred** [comment]
> "systemd-journal" is about being able to see what root can see, while "wheel" is about being able to do what root can do. And as the latter usually is assumed to imply the former, we honour both.

"wheel" is about being able to _do_ what root can do _after_ completing the configured escalation step, which is not a super-set of unconditional read access.

> Quite frankly, I do expect that being in "wheel" does give me certain powers. You do not think that. Which is fine. But I doubt it's right to assume that the general userbase of systemd-based system expects what you expect. I mean, i can only guess, but given the feedback we got so far on the groups thing most people weren#t too surprised by this...

My report/comments don't support the characterisation of this bug as arbitrary preference; the wheel group has (again, correct me if I'm wrong) long-established semantics/behaviour linking it to sudo, for which as said their is a (configurable) escalation step to access wheel powers.

For a wheel member, if wheel log read access is dropped:

`journalctl` would show the user's logs (i.e. no privileged access, same as other non-sudo commands a wheel member might run)
`sudo journalctl` would show all logs after escalation is passed (privileged access after escalation, same as any other privileged action a wheel member wants to carry out)

This is a default configuration _consistent with existing wheel/sudo behaviour_. From what you have said, the current _less consistent_ behaviour is based on personal preference (unless I'm missing a precedent for expecting wheel-conferred powers without passing sudo's escalation process first).

Has there been active/reasoned feedback agreeing with the current behaviour?

**Comment by mbiebl** [comment]
Related to this is #2492
Fwiw, in Debian we patch out the use of wheel [1], so if this was dropped altogether, I wouldn't mind at all.

I'm inclined to agree with @smithfred here. The semantics of wheel do not fit naturally here and we shouldn't overload it with a different meaning. We have clear semantics with group systemd-journal and at least on Debian derived distros, group adm has clear semantics regarding log files (/var/log/* is owned by root:adm, 640) which matches the expected behaviour. The wheel group not so much


[1] https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/rules#n232

**Comment by smithfred** [comment]
Lennart, can you give a response to the last two posts?

**Comment by poettering** [comment]
Note that on PolicyKit "wheel" permits admin rules too. See /etc/polkit-1/rules.d/50-default.rules

Maybe debian patches that out too. But I am not convinced that debian's definition is so much better than anything else and evreybody should stick to that...

**Comment by smithfred** [comment]
Yes, polkit does have that stanza. And if I run e.g. "pkexec $privileged_command" as a wheel member, I have to enter my password (i.e. as configured in sudoers)...

So actually, polkit is another example of the expected privilege escalation behaviour for wheel members.

I'm not using Debian or a derivative by the way. And mbiebl's mention of the patching out of wheel was orthogonal to his support of my assertions re. wheel semantics.
