### ISSUE TITLE
"Failed" service unit propagates start dependency

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4787]
- [ ] Bug report
  - [ ] Request for enhancement (RFE)

> systemd 232-4

> Arch

A "failed" service unit will still pointlessly propagate a Forward Start dependency.  This seems like the wrong thing to do, and the wrong way to be doing things.  Consider:

Here is a way to add some semblance of "hot plug" support to the parallel printer port.

---
[Unit]
Description=CUPS Scheduler
Documentation=man:cupsd(8)
After=network.target
BindsTo=sys-subsystem-ppdev-devices-%i.device
Wants=printer.target
[Service]
ExecStart=/usr/bin/grep -q "CLASS:PRINTER" /proc/sys/dev/parport/%I/autoprobe
[Install]
DefaultInstance=parport0
WantedBy=sys-subsystem-ppdev-devices-%i.device

---

where another unit file has a WantedBy=printer.target to start cupsd.

This does not work because, despite any failure grep'ing for "CLASS:PRINTER", systemd will still propagate the start from sys-subsystem-ppdev-devices-%i.device to printer.target.  This would start cupsd even when there was no printer attached, which defeats the entire purpose of the unit file.

If there is some other "canonical" way to do this, I want to know about it.

systemd-udevd seems to have no mechanism to grep the contents of a file, and parport_pc seems not to communicate to udev or the kernel anything about its probe of any attached device.

Another alternative is to *not* use the Wants=printer.target, and to instead use:

`ExecStart=/usr/bin/sh -c '/usr/bin/grep -q "CLASS:PRINTER"
/proc/sys/dev/parport/%I/autoprobe &&
/usr/bin/systemctl start printer.target'`

That works, but my understanding is that that is not "the systemd way".  Or, is it?  Or must it be?

Regardless - what is the point of propagating a Forward Start dependency from a *failed* service unit?  *The unit **failed**.  The unit is **not** in a "started" state.  It cannot "Want" some other unit.*

And, no, it is not a solution to go modify all the "downstream" unit files with Reverse dependencies on the "upstream" unit.  The different unit files should generally not have to know anything about each other.  Please, don't go there.

**Comment by fsateler** [comment]
> The unit failed. The unit is not in a "started" state. It cannot "Want" some other unit.

Well, `Wants` are evaluated at job scheduling time, not at job execution time. In fact, printer.target will be brought up at the same time as the unit you describe, so the failure of your unit may well be after cups has already been started.

**Comment by thx1111** [comment]
Hmm - thanks.  So, `&& /usr/bin/systemctl start printer.target` then?  Is that the best alternative?

**Comment by poettering** [comment]
systemd is a job engine, and Wants is a command that adds jobs to the job engine. Jobs are executed in order, and the result of a service execution hence doesn't really apply to to a Wants= anymore, as that's way later...

So, sorry, this is not how systemd works, and this is not going to change.

if you want to execute some check, and then pull in some service, then do so with "systemctl --no-block start" or so, but dependencies are really not for that. Sorry
