### ISSUE TITLE
Run depmod during boot

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#4788]
### Submission type

- [X] Request for enhancement (RFE)
- [ ] Bug report

Today my parents' computer booted up in emergency mode. Upon investigation the `modules.dep` and `modules.dep.bin` files had disappeared. This caused the boot to fail because `/boot/efi` could not be mounted (in turn, because the `vfat` kernel module could not be loaded). In addition, `systemd-modules.load.service` was also in the failed state.
 
The fix was straightforward: run `depmod` and reboot.

Please run `depmod --quick` unconditionally during boot. This is a noop if `modules.dep` and friends are up to date, and where they are missing this change would allow systems to boot successfully.

**Comment by poettering** [comment]
Hmm... I am not convinced this should be in systemd. I mean, this is something that should always be called from the package installation scripts, but there's really no reason to ever delay this to boot. I mean, systemd is not really the place to work around packaging mishaps...

Also, if this is indeed a good idea to have, then it should probably be part of modules-init-tools, but not really of systemd.

I am closing this now, I hope this is understandable. Sorry.
