### ISSUE TITLE
journal reports 0 usage on startup

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#4790]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

v232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

Accurate journal usage. e.g.

```
Jul 30 13:49:38 rampage systemd-journald[248]: System journal (/var/log/journal/) is 4.0G, max 4.0G, 0B free.
```

This works on v231.

### In case of bug report: Unexpected behaviour you saw

```
Nov 15 21:20:04 rampage systemd-journald[171]: System journal (/var/log/journal/f2987b1c316d1e4e496bd04f00000087) is 0B, max 0B, 0B free.
```

### In case of bug report: Steps to reproduce the problem

Seems like there were a number of patches that messed with disk space usage reporting (#4360). Unclear which is the culprit, but I'll blame 23aba343498f3cbe0bdce6c841a0c34339d1be90 since I see the word "cache".

**Comment by falconindy** [comment]
@fbuihuu

**Comment by fbuihuu** [comment]
Weird, I really thought that this part was working.

I'll track this down.
