### ISSUE TITLE
broken unicode while shutdown process

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4794]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

Hello,
Following behaviour: Everytime when I execute `systemctl poweroff` I have weird systemd messages during the poweroff process. It looks like a mix of broken unicode with korean. When I look in the journald log it's fine. I can read it. But during poweroff I can't read whats happening. As far as i can see everything behave normal, just the display of the text seems broken. I will try to add a picture when I reboot/poweroff my machine next time. I am not sure if this is a systemd bug in general or if it has something todo with my locales or something else.

```
# localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```

**Comment by poettering** [comment]
hmm? are you talking ot the text console? maybe it's X11 switching back to your console that causes this?

**Comment by shibumi** [comment]
I am talking about the text console. The last messages that are shown after stopping X11, stopping last services, etc. I don't have this always, just sometimes. I will try to make a picture of it next time when it occurs. The journallog is fine, just on the screen I see just garbage.

**Comment by mattia-b89** [comment]
I have a similar issue: � character in the boot process

originally reported on the Arch Linux bug tracker: https://bugs.archlinux.org/task/52017
where there is a screenshot and other information, too

**Comment by shibumi** [comment]
@poettering
Here is a Screenshot:
https://paste.archlinux.de/M9DLle/

**Comment by keszybz** [comment]
Those look to be completely different issues.

In 52017 the ellipsis glyph is not displayed properly. This means that the encoding is utf8 as understood by systemd and the kernel, but the kernel is missing the font for some reason.

Here, it looks like the terminal has been "corrupted", probably by something writing control characters to it.

**Comment by mattia-b89** [comment]
could this bug related to this https://github.com/systemd/systemd/issues/6443 ?

**Comment by bl33pbl0p** [comment]
I happen to see such stuff when I `cat /dev/urandom` on to the console, and it goes away when i do a `reset`, probably this would give some insight as to why this happens.

**Comment by keszybz** [comment]
#6443 seems to be the same as arch 52017, see https://github.com/systemd/systemd/issues/4794#issuecomment-267764377.

**Comment by mattia-b89** [comment]
@keszybz I am the one who reported arch 52017 ...

**Comment by poettering** [comment]
Is this still relevant? Or can we close this? I doubt systemd has anything to do with this, we never touch console settings anymore after boot-up. It's probably either a distro-provided service fucking this up, or X11. In either case not our fault. I am hence tempted to just close this, given it has been 3 years...

**Comment by poettering** [comment]
Oh, well, let's just close this. If this is still an issue on current systems, and there's reason enough to believe this is a systemd issue (and not a downstream distro script/service issue or X11 issue), then please file a new bug, with details on all services that are stopped during shutdown).

**Comment by shibumi** [comment]
@poettering from my side: we can close this :)
