### ISSUE TITLE
calendar spec *:* not properly expanded, never advances

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#4804]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

Issue present at git head

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

`OnCalendar=*:*` should be equivalent to `*-*-* *:*:00/1`.

### In case of bug report: Unexpected behaviour you saw

An OnCalendar setting of `*:*` never advances as it's equivalent to `*-*-* *:*:*`, repeating forever at the current time.

### In case of bug report: Steps to reproduce the problem

I wrote a tool to expand calendar specs and show subsequent runs, which illustrates the problem.

```txt
$ systemd-parse-calendarspec '*:*'
Showing next 5 runs for: *-*-* *:*:*
  1: Fri 2016-12-02 08:35:13 EST
  2: Fri 2016-12-02 08:35:13 EST
  3: Fri 2016-12-02 08:35:13 EST
  4: Fri 2016-12-02 08:35:13 EST
  5: Fri 2016-12-02 08:35:13 EST

$ systemd-parse-calendarspec '*-*-* *:*:*'
Showing next 5 runs for: *-*-* *:*:00/1
  1: Fri 2016-12-02 08:36:01 EST
  2: Fri 2016-12-02 08:36:02 EST
  3: Fri 2016-12-02 08:36:03 EST
  4: Fri 2016-12-02 08:36:04 EST
  5: Fri 2016-12-02 08:36:05 EST
```

**Comment by poettering** [comment]
Well the "seconds" part actually has µs granularity, hence this is a bit more complicated. But yeah, we probably should handle this differently...
