### ISSUE TITLE
[RFE] Implement graphical bootsplash into systemd

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#4805]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### Description

Almost any modern (desktop) GNU/Linux distribution uses some kind of graphical [bootsplash](https://en.wikipedia.org/wiki/Bootsplash#Linux_distributions). It would be nice if this would be possible without using any external tools like Plymouth.

**Comment by grawity** [comment]
I'm not sure why having it in systemd would be better? Besides, systemd already has built-in Plymouth integration (status; password prompts; etc.)

**Comment by dmedri** [comment]
Why should we have this tool in the systemd suite? What advantages could offer a renewed and integrated Plymouth?
