### ISSUE TITLE
mkosi arch linux build issues:

### ISSUE THREAD

**Issue by james-lawrence** [systemd/systemd#4816]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with
git rev-parse HEAD
3099caf2b5bb9498b1d0227c40926435ca81f26f

### Used distribution
arch linux

### In case of bug report: Unexpected behaviour you saw
Dec 03 16:22:23 arch.raw journalctl[19]: /usr/bin/journalctl: error while loading shared libraries: libqrencode.so.3: cannot open shared object file: No such file or directory
Dec 03 16:23:56 arch.raw systemd-tmpfiles[19]: Failed to create file /sys/devices/system/cpu/microcode/reload: Read-only file system

### In case of bug report: Steps to reproduce the problem
```
[Distribution]
Distribution=arch

[Output]
Format=raw_gpt
Bootable=yes

[Partitions]
RootSize=2G

[Packages]
Cache=/var/cache/pacman/pkg/
BuildPackages=
	base
        acl
        autoconf
        automake
        bzip2
        cryptsetup
        curl
        dbus
        docbook-xsl
        elfutils
        gcc
        git
        gnu-efi-libs
        gnutls
        gperf
        intltool
        iptables
        kmod
        libcap
        libgcrypt
        libidn
        libmicrohttpd
        libseccomp
        libtool
        libutil-linux
        libxkbcommon
        libxslt
        lz4
        make
        pam
        pkgconfig
        python
        python-lxml
        qrencode
        xz
	vim
	htop
```
```
sudo mkosi --force -o arch.raw
```

resolutions:
for libqrencode: within the image `pacman -Syu qrencode` why it doesn't install properly during image creation I am unsure.
for the systemd-tmpfiles edit `/usr/lib/systemd/system/systemd-tmpfiles-setup.service` by adding `--exclude-prefix=/sys` I assume this is because the image is running a container

**Comment by poettering** [comment]
You need `Packages=qrencode` at least. Note that `BuildPackages=` only declares packages needed for the *build* of the image, but not for the runtime. Hence, if it's necessary at runtime, then you also need to add it to `Packages=`...

(And I figure you want to add "vim" to Packages= instead of BuildPackages=...)

The tmpfiles thing is a problem we haven't found a good solution to yet, but it's already being tracked.

Closing, as this appears to be a misconfiguration (also, better place to report this would be the mkosi github I figure...)

**Comment by james-lawrence** [comment]
haha derp =) thanks.

**Comment by james-lawrence** [comment]
well its based on the configuration file inside the systemd repo. so problem is actually in systemd's configuration.

**Comment by poettering** [comment]
Oh, hmm, yeah could be... so, how does that work on arch? if i install nothing but let's say "coreutils", will it pull in systemd anyway? if so why wouldn't it pull in qrcode then? Not an Arch user myself, but this could be a bug in the mkosi file indeed, that needs some fixing...

**Comment by james-lawrence** [comment]
Ill look into it. Just havent used mkosi before. Ill see if i can get it working properly using `packages=` and file the appropriate issues upstream if necessary.
