### ISSUE TITLE
Docs for StartLimitInterval 

### ISSUE THREAD

**Issue by guettli** [systemd/systemd#4826]
### Submission type

  - [ X] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 229 (but I guess the same issue is on master)

### Used distribution

> Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

> man systemd.unit

/StartLimitInterval  no match
### In case of bug report: Unexpected behaviour you saw

I wanted to see docs about `StartLimitInterval`

I found docs in blog posts and github issues, but up to now I could not find official docs.

Here is one comment about StartLimitInterval from Lennart Poettering: https://github.com/systemd/systemd/issues/2416#issuecomment-174556535

**Comment by keszybz** [comment]
See https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=.
(Note: the setting was renamed to have the "Sec" suffix in systemd-230.)
