### ISSUE TITLE
Missing pieces of information in manual pages for systemd.unified_cgroup_hierarchy

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4827]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>systemd 231
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

>Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

>Pieces of information about systemd.unified_cgroup_hierarchy in manual pages.

### In case of bug report: Unexpected behaviour you saw

>Lack of pieces of information about systemd.unified_cgroup_hierarchy in manual pages.

### In case of bug report: Steps to reproduce the problem

I use systemd 231 and I didn't find anything relevant. I browsed online manual pages and nothing. I'm strictly talking about manual pages.

**Comment by keszybz** [comment]
Indeed, this should be documented in systemd(1) and kernel-command-line(7).
