### ISSUE TITLE
NVMe symlinks broken by spaces in NVMe model number strings

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#4833]
The udev rules added in bug https://github.com/systemd/systemd/issues/1453 add creation of symlinks using NVMe drive model and serial strings, but unfortunately they don't take into account whitespace, so any drives that include whitespace in their model (or serial) string breaks the symlink creation - e.g. if the model string is "XYZ Corp NVMe drive" then instead of creating:
/dev/disk/by-id/nvme-XYZ Corp NVMe drive_SERIAL -> ../../nvme0n1
it creates:
/dev/disk/by-id/nvme-XYZ -> ../../nvme0n1
/dev/Corp -> nvme0n1
/dev/NVMe -> nvme0n1
/dev/drive_SERIAL -> nvme0n1

this isn't an issue with SCSI/ATA drives, because the scsi_id/ata_id programs are used to get their model/serial strings, and those programs internally do whitespace conversion.  With NVMe, it uses the $attr{model} and $attr{serial} directly, and $attr{} internally whitelists spaces:
src/udev/udev-event.c udev_event_apply_format():
                case SUBST_ATTR: {
...
                        count = util_replace_chars(vbuf, UDEV_ALLOWED_CHARS_INPUT);
                        if (count > 0)
                                log_debug("%i character(s) replaced" , count);

and:
src/libudev/libudev-private.h:#define UDEV_ALLOWED_CHARS_INPUT        "/ $%?,"

it looks to me like that is the opposite of what should happen, as none of those chars should be allowed in a symlink...should $attr{} be changed to replace those chars as well?  or is there a builtin function that could be used by the rule to perform whitespace (and other char) replacement?

It seems like this will be a problem for any rule that creates a symlink based on a device $attr{} value.

**Comment by ddstreet** [comment]
A bit of digging shows that this is a very old problem, in general; and it was "fixed" for md and dm devices *only* way, way back with commit ee173c5927649e8f2e6f42046315e84eb8e55e1b ("replace spaces in dm and md name symlinks").

However, this is just a bug waiting to happen for all other device types, too; there is no case where a rule is actually wanting to add multiple symlinks with a single SYMLINK+="" statement; the default should be to replace spaces, not require all rules to specify OPTIONS+="string_escape=replace".

Please see my pull request above that fixes this problem by changing the default to replace spaces for all SYMLINK values.

**Comment by msekletar** [comment]
I've opened a pull request about the same problem a while ago, https://github.com/systemd/systemd/pull/4077

Kay is suggesting that we should by default use escaping is order to keep symlink names reversible. Of course that is technically superior solution compared to mapping every unsuitable character to ```_```, however I have doubts if it is practical. I personally would rather see name that has bunch of underscores in it (but it is still readable) instead of ugly escaped name. I think that people don't really care about unescaping because they can always gather original data from sysfs.

**Comment by ddstreet** [comment]
> Of course that is technically superior solution compared to mapping every unsuitable character to _

adding the string_escape=replace option to the NVMe rules is not a technically superior solution - it is 100% a workaround of a broken design.  And you are mischaracterizing the issue - all invalid characters are *already* replaced by default in any SYMLINK value, it's only spaces that are left, *by design*.  That's what is broken; not replacing spaces (and only spaces) by default in SYMLINK values.

**Comment by msekletar** [comment]
> adding the string_escape=replace option to the NVMe rules is not a technically superior solution - it is 100% a workaround of a broken design.

I meant it other way around, i.e. proper escaping is technically better than ``` string_escape=replace```, but I think that no one actually cares about unescaping symlinks. Hence, why bother in the first place. IOW, I'd be glad if this PR is merged.

**Comment by msekletar** [comment]
Thinking about this a bit more I am wondering whether we shouldn't just add workaround for NVMe case and be done with it. My point is that changing the default has a potential to break user defined rules that may have been working for someone since years ago.

Disclaimer: I work on RHEL/CentOS. Nevertheless, if this is merged but turns out to be problematic in the future we would have to revert it downstream anyway.

**Comment by ddstreet** [comment]
> Thinking about this a bit more I am wondering whether we shouldn't just add workaround for NVMe case
> and be done with it

definitely not; that's just kicking the bug down the road, to be hit again later on by other rules that aren't expecting whitespace in their symlink variable substituion values.  And manually updating each and every symlink rule to add "string_escape=replace" hardly seems better than changing the default.

I updated my pull request based on comments from keszybz, to replace whitespace by default only in the substitution values - not in any hardcoded whitespace in symlink rules.  This seems like a much better approach; keep any whitespace that clearly is intended in the symlink value, but by default replace all whitespace that is unexpectedly introduced by variable substitution.  Hopefully that updated pull request can be merged.
https://github.com/systemd/systemd/pull/4837

**Comment by zviratko** [comment]
This change broke 65-drbd.rules from drbd-utils:

```
IMPORT{program}="/usr/sbin/drbdadm sh-udev minor-%m"
# Use symlink from the environment if available
ENV{SYMLINK}!="", SYMLINK="$env{SYMLINK}", GOTO="have_symlink"

```
the output of drbdadm sh-udev looks like this:

```
root@zfs1:/var/lib/blackstor.d/resources# drbdadm sh-udev -c 05bb6f3c-87cf-4c0d-b7e1-c542cbc122a1.bs minor-3002
DEVICE=drbd3002
SYMLINK=drbd/by-res/05bb6f3c-87cf-4c0d-b7e1-c542cbc122a1/0 drbd/by-disk/zvol/drbdpool/05bb6f3c-87cf-4c0d-b7e1-c542cbc122a1
```

I have no idea how this should be fixed - there can (theoretically, not with drbd) an arbitrary number of symlinks to create...

**Comment by ddstreet** [comment]
```
> IMPORT{program}="/usr/sbin/drbdadm sh-udev minor-%m"
> # Use symlink from the environment if available
> ENV{SYMLINK}!="", SYMLINK="$env{SYMLINK}", GOTO="have_symlink"
```

a "more correct" way to do it, is use the built-in $result value,
which handles whitespace itself, so like:

```
PROGRAM="/usr/sbin/drbdadm sh-udev minor-%m", SYMLINK="$result", GOTO="have_symlink"
```

however, that would also need drbdadm to change its behavior:
1) make the program return return success (0) if the symlink should be created, and return failure (!0) if not
2) return only the plain-text symlinks strings; no "SYMLINK=" assignment


Alternately, the current rule could be fixed; just append this (before the GOTO, I think), and it should leave the space alone, which will go back to the original behavior of creating multiple symlinks.

```
OPTIONS+="string_escape=none"
```

**Comment by keszybz** [comment]
> `OPTIONS+="string_escape=none"`

Yeah, this should work with current and previous versions of systemd-udev.
