### ISSUE TITLE
[RFE] Functionalities for third-party apps and their configuration files

### ISSUE THREAD

**Issue by dmedri** [systemd/systemd#4847]
### Submission type

  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

231

### Used distribution

misc

Systemd already provides internal functions to read its configuration file and the options contained therein. There are also internal functions to interpret and evaluate whether strings fall into certain datatypes (eg. IP addresses). Why not make it available to third-party developers for their Apps?

Some common needs:
- Know where are the configuration files (PATH for system, user);
- .conf: read, load, save and backup old versions;
- Read key:value from .conf files (numbers, text values);
- Datatype checks:
   * Are numbers in range (eg. is in [1-10]?)
   * Are valid IP address (IPv4, IPv6)?
   * ect...

I know, it's a boring RFE. There are many libraries for that, but no standard solutions.

**Comment by poettering** [comment]
Sorry, but we are not in the business of providing generic "glib"-like APIs to users. We supply some, such as sd-event or sd-bus, not I am very sure that parsing tools and suchlike should be something we make available publicly as a shared library.

Doing APIs of shared libraries is hard, very hard, as it means you need to commit to stability and compatibility, and I am not sure we really want that for much of the internal stuff of the systemd codebase.

The code is open source of course, hence copy out whatever you need.

Sorry if this is disappointing!

**Comment by dmedri** [comment]
Ok, leave out the checks on datatypes, if this could add problems and increase complexity. Take the rest for a public API. The functions helpful to know (system,user) configuration PATH, the actions on files (try-existence, load, backup, save) and how to read key:values in basic text/number form without checks or casting.

Probably, the 80% of the work already exists in "private" form.
