### ISSUE TITLE
Setting of realtime scheduler for user service fails

### ISSUE THREAD

**Issue by dvzrv** [systemd/systemd#4851]
### Submission type

  - [ ] Bug report

### systemd version the issue has been seen with

232

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

Setting a realtime scheduler for a user service.

### In case of bug report: Unexpected behaviour 

Failed at step SETSCHEDULER spawning /usr/bin/jackd: Operation not permitted

### In case of bug report: Steps to reproduce the problem

When using the following unit file, usually a "rr" CPUSchedulingPolicy will be used with a CPUSchedulingPriority of "71". Starting with systemd 232 this fails (maybe something underlying has changed).

```
[Unit]
Description=JACK Audio
After=sound.target local-fs.target

[Service]
EnvironmentFile=-/etc/jack/%i
EnvironmentFile=-%h/.config/jack/%i
ExecStart=/usr/bin/jackd $REALTIME -p $PORTMAX -d $DRIVER -d $DEVICE $DRIVER_SETTINGS
CPUSchedulingPolicy=rr
CPUSchedulingPriority=70
LimitRTPRIO=71
LimitRTTIME=infinity

[Install]
WantedBy=default.target
```

I am still able to set realtime schedulers and their priorities using tuna, so this is most likely not a kernel issue.
I've tried Arch's vanilla (4.8.12) and realtime (4.8.11-rt) kernel.
For reproducability you can use this service with your user (you might have to use a different device name, instead of hw:PCH, depending on your aplay -l output):

```
[Unit]
Description=JACK Audio
After=sound.target local-fs.target

[Service]
ExecStart=/usr/bin/jackd -R -p 512 -d alsa -d hw:PCH -n 2 -p 512 -r 44100
CPUSchedulingPolicy=rr
CPUSchedulingPriority=70
LimitRTPRIO=71
LimitRTTIME=infinity

[Install]
WantedBy=default.target
```

Downgrading to systemd 231 fixes this issue.

**Comment by poettering** [comment]
How do you gran RT scheduling privileges to your user instance? Via pam_limits? If so, are you sure it's included in the PAM fragment in /etc/pam.d/systemd-user? Make sure it's there.

**Comment by dvzrv** [comment]
Before systemd 232 I didn't use PAM for that (at least not knowingly). My /etc/pam.d/systemd-user looked like this:

```
# This file is part of systemd.
#
# Used by systemd --user instances.

account required pam_unix.so

session  required pam_loginuid.so
session optional pam_systemd.so
```

Now, with 232, I'm using this to make it work:

```
# This file is part of systemd.
#
# Used by systemd --user instances.

account required pam_unix.so

session  required pam_loginuid.so
session  required pam_limits.so
session optional pam_systemd.so
```

The following limits.conf setting for the audio group (while this user obviously is part of the audio group) from /etc/security/limits.d/ had been around beforehand though:

```
@audio 	- rtprio 	99
@audio 	- memlock 	unlimited
```

Just to get some background on this and make me help understand:
What exactly changed between 231 and 232, that made adding the pam_limits.so necessary?
I wonder how systemd pulled in the required PAM limits before and if the change to /etc/pam.d/systemd-user should be added downstream to Arch Linux's package for systemd (after all there should be no harm in doing this, right?).

**Comment by poettering** [comment]
See NEWS file, for v232.
