### ISSUE TITLE
sd_bus vtable initialization macros for C++

### ISSUE THREAD

**Issue by TheJJ** [systemd/systemd#4858]
### Submission type

  - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Gentoo Linux

I'm writing a C++14 program using `sd_bus`.
When i create the dbus vtable with

``` cpp
static const sd_bus_vtable rofl_vtable[] = {
	SD_BUS_VTABLE_START(0),
	SD_BUS_METHOD("start", "xx", "x", nullptr, SD_BUS_VTABLE_UNPRIVILEGED),
	SD_BUS_VTABLE_END
};
```

then the macros expansions generate loads of warnings like:

```
/home/jj/devel/horst/src/satellite.cpp:118:2: warning: designated initializers are a C99 feature [-Wc99-extensions]
        SD_BUS_VTABLE_START(0),
        ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/systemd/sd-bus-vtable.h:87:17: note: expanded from macro 'SD_BUS_VTABLE_START'
                .type = _SD_BUS_VTABLE_START,                           \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jj/devel/horst/src/satellite.cpp:118:2: warning: designated initializers are a C99 feature [-Wc99-extensions]
        SD_BUS_VTABLE_START(0),
        ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/systemd/sd-bus-vtable.h:88:17: note: expanded from macro 'SD_BUS_VTABLE_START'
                .flags = _flags,                                        \
                ^~~~~~~~~~~~~~~
/home/jj/devel/horst/src/satellite.cpp:118:2: warning: designated initializers are a C99 feature [-Wc99-extensions]
        SD_BUS_VTABLE_START(0),
        ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/systemd/sd-bus-vtable.h:89:17: note: expanded from macro 'SD_BUS_VTABLE_START'
                .x.start.element_size = sizeof(sd_bus_vtable),          \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(..... and many more)
```

This is of course because we're on C++ and not C99. Wrapping `extern "C" { /* vable init */ }` does not help, unfortunately :)

Please provide some way where the struct and the entries can be setup in C++ without requiring the designated initializers.

**Comment by poettering** [comment]
Hmm, I am not sure I know C++ well enough to know how to do this better? A patch for this would be very welcome!

**Comment by keszybz** [comment]
It'd suggest -Wno-c99-extensions. This is a case of C++ committee being obtuse, because of NIH and to push people to use classes.

I don't think we can use `#pragma` in public headers. So the only solutions seems to be to switch to positional initializers.

**Comment by keszybz** [comment]
Only we have a union here, so positional initializers are extremely painful.

So maybe the proper solution is add a C++ constructor (guarded by proper `#ifdef`s).

**Comment by pyBlob** [comment]
This patch uses a slighty other format for the defines that is understood by the C++ compiler.

Is there already an issue for the mentioned C++ approach? If not, how would you go about implementing this?

[gcc_sd_bus_fix.patch.txt](https://github.com/systemd/systemd/files/787648/gcc_sd_bus_fix.patch.txt)

**Comment by poettering** [comment]
@pyBlob if that syntax works on both C++ and on C, then we should adopt that. Could you post a proper github PR for that? The CI will validate that this compiles fine on C for us.

**Comment by keszybz** [comment]
It would be good to include a C++ test case and check our headers. C++ compatibility *is* important, we should be doing that, even if it costs us an additional dependency and a bit of compilation time. Also for this patch: without adding tests we won't know if it really does the job.

**Comment by poettering** [comment]
@keszybz we could also make it an optional test: if c++ support is available, test this, otherwise don't... I figure for embedded envs it might make sese to support non-C++ builds, dunno.

(I'd happily merge a patch that makes the cpp compiler a hard dep too though)

**Comment by poettering** [comment]
Closing this as #5397 got merged.
