### ISSUE TITLE
systemd-journald drops all bytes after '\0'

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#4863]
I'm sorry for not being specific. I will have to update the description so that it won't cause confusion like https://github.com/systemd/systemd/pull/6838#issuecomment-329808846.

```sh
$ printf '<13>Sep 15 15:07:58 HOST: null\0here' | nc -w1 -u -U /run/systemd/journal/dev-log

$ journalctl -t HOST -o verbose
...
    MESSAGE=null
```
From https://github.com/systemd/systemd/pull/1460
> Of course, this will make the patch more complicated, as this means we have to patch much further down to ensure we always keep the ptr+length bit intact.

**Comment by poettering** [comment]
<strike>Fix waiting in #6838.</strike>

**Comment by evverx** [comment]
It's not fixed. That's why I wrote in the description that I should update it and we discussed it in https://github.com/systemd/systemd/pull/6838#issuecomment-329818840.

**Comment by poettering** [comment]
ah, indeed. ok, let's clarify on this issue hence, that the offending command is this:

```
printf '<13>Sep 15 15:07:58 HOST: null\0here' \| nc -w1 -u -U /run/systemd/journal/dev-log
```

And that indeed remains unfixed.

Sorry for the confusion

**Comment by poettering** [comment]
Hmm, so while I agree that simply ignoring everything coming after a NUL byte in a BSD syslog message is definitely the wrong approach, I am not sure what the *right* approach though is. If we get an UDP or AF_UNIX datagram with an embedded NUL byte, does this means the datagram contains two log records and the NUL is the separator? or does it mean that NUL shall be considered part of the log message?

**Comment by evverx** [comment]
I think the latter. According to https://tools.ietf.org/html/rfc5424
> This document does not impose any mandatory restrictions on the MSG
   or PARAM-VALUE content.  As such, they MAY contain control
   characters, including the NUL character.

>  In some programming languages (most notably C and C++), the NUL
   character (ABNF %d00) traditionally has a special significance as
   string terminator.  Most implementations of these languages assume
   that a string will not extend beyond the first NUL character.  This
   is primarily a restriction of the supporting run-time libraries.
   This restriction is often carried over to programs and script
   languages written in those languages.  As such, NUL characters must
   be considered with great care and be properly handled.  An attacker
   may deliberately include NUL characters to hide information after
   them.  Incorrect handling of the NUL character may also invalidate
   cryptographic checksums that are transmitted inside the message.

`rsyslog` seems to [replace control characters while receiving messages by default](https://www.rsyslog.com/doc/rsconf1_escapecontrolcharactersonreceive.html), but it's configurable via other knobs like [`escape-cc`, `drop-cc` and `escape-cc`](https://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html#property-options).

**Comment by evverx** [comment]
As shown in https://github.com/systemd/systemd/pull/10918, `journald` still uses string functions to handle binary messages and therefore loses everything after the first null byte. I guess the issue should be reopened.

**Comment by evverx** [comment]
The issue was also reported in https://github.com/systemd/systemd/issues/12484. I don't think it makes much sense to keep this one open.
