### ISSUE TITLE
networkd [Link] section ARP default behavior changed

### ISSUE THREAD

**Issue by joejulian** [systemd/systemd#4870]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> With a macvlan bridge, I expected my network to continue to function. Previously, a `network` assigned to a macvlan bridge `netdev` would function normally.

### In case of bug report: Unexpected behaviour you saw

> Could not communicate on the network. Any attempts to do so would leave the arp table empty. This seems to be due to a new default requiring an ARP=yes `link` configuration.

### In case of bug report: Steps to reproduce the problem

> Create a macvlan bridge
```ini
[NetDev]
Name=br0
Kind=macvlan

[MACVLAN]
Mode=bridge
```
> Attach a physical network device to it
```ini
[Match]
Name=enp*

[Network]
MACVLAN=br0
IPForward=yes
```
> Attach a macvlan interface
```ini
[Match]
Name=br0

[Network]
DNS=127.0.0.1
IPForward=yes
LinkLocalAddressing=yes
IPv6PrivacyExtensions=yes
IPv6AcceptRouterAdvertisements=yes

[Address]
Address=192.168.1.10/24

[Route]
Gateway=192.168.1.254
```
> Ping the gateway and check the arp table
```bash
$ ping 192.168.1.254
PING 192.168.1.254 (192.168.1.254) 56(84) bytes of data.
^C
--- 192.168.1.254 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 5008ms
$ arp -n
$
```

**Comment by ssahani** [comment]
Please take a look https://github.com/systemd/systemd/issues/4644.
Does that fix your issue ?

**Comment by joejulian** [comment]
Missed that one, thanks.
