### ISSUE TITLE
Reminder: bump `libmount` dependency to `2.30`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#4871]
https://github.com/karelzak/util-linux/commit/0a14cc8bcc151e03c8979ed1ff4a3bee9672365b
```
libmount: revert X-* and x-* meaning
Let's hope this is last change necessary to cleanup x-* usage:

  x-*  persistent option, stored in utab, available for umount, etc.
  X-*  fstab comment only

mount(8) supports x-mount.mkdir= as well as newly recommended X-mount.mkdir=

Advantages:

 * less invasive
 * does not require exception for x-systemd
 * does not require rename x-initrd to X-initrd

The systemd and dracut users will get the new (=fixed) functionality without a
change in fstab configuration. This is the primary goal.

Disadvantages:

 * not 100% compatible libmount behavior, x-* options have not been
   previously stored in utab. The API is the same, options will be still
   available, but on x-* libmount will write to /run/mount/utab. For now
   it seems only systemd uses x-*, and they like this behavior, so...
```

Related:
https://github.com/systemd/systemd/issues/4817
https://github.com/systemd/systemd/pull/4515

**Comment by poettering** [comment]
Hmm, so f25 doesn't have the new libmount yet (which is what I am using). I think it's OK to leave this at the old libmount version for now, will move this to v234 hence.

**Comment by keszybz** [comment]
Even F26 has libmount-2.29. Let's wait a bit more.

**Comment by evverx** [comment]
`2.30-rc2` was released three days ago, but `2.30` has not been released yet, so, yes, let's wait.

**Comment by marcosfrm** [comment]
2.30 is out (released last week).

**Comment by evverx** [comment]
@marcosfrm thanks for pointing this out. I have just removed the postponed label.

`2.30` is also required by `umount -c`. See https://github.com/systemd/systemd/issues/6115#issuecomment-307993369.

**Comment by marcosfrm** [comment]
https://github.com/karelzak/util-linux/commit/ce6e269447ce86b0c303ec2febbf4264d318c713  (@neilbrown 's patch)
and
https://github.com/karelzak/util-linux/commit/9f1af33141556df9f0fa75e6c357499952fcb880
https://github.com/karelzak/util-linux/commit/f8416301c195d50a21cb54d9ea9abeccc40f9ee7
https://github.com/karelzak/util-linux/commit/11573ac0c840e5189873fcd897a14356942172cf

are not in 2.30. @karelzak can probably put them in 2.30.1 though.

**Comment by evverx** [comment]
@marcosfrm , thank you. It seems that I misunderstood https://github.com/systemd/systemd/commit/83897d5470190a9818df50026cf38cd97114f77d

> So "-c" is safe to use now, and once util-linux v2.30 is in use,
it will allow mounts from non-responsive NFS servers to be
unmounted.

and https://github.com/systemd/systemd/issues/6115#issuecomment-307993369

> You also need util-linux newer than v2.30

I am sorry for the confusion.

**Comment by marcosfrm** [comment]
@keszybz F26 now has util-linux 2.30 (updates-testing). It is also in Arch's testing repo.

This can go in 234, no?

**Comment by keszybz** [comment]
I'd prefer to wait until it's widely available as stable packages in distributions. Pushing for deps that have **just** been released makes it harder for our testers and users.

**Comment by poettering** [comment]
pr has been filed as #6795
