### ISSUE TITLE
time-sync.target is still passed even if the unit that calls it fails 

### ISSUE THREAD

**Issue by ryran** [systemd/systemd#4880]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231

### Used distribution

> Fedora 25 (`systemd-231-10.fc25.x86_64`)

### In case of bug report: Expected behaviour you didn't see

> The standard chrony-wait.service pulls in time-sync.target (`Before=` & `Wants=`) and runs a `chronyc waitsync` command that blocks until the chrony daemon has synchronized to an acceptable degree or until a timeout is reached. In the latter case, `chronyc` exits with a non-zero exit code (1) and chrony-wait.service of course enters a failed state
> 
> Even though chrony-wait.service failed, time-sync.target still gets pulled in (I call targets like this gateway targets so I say it was "passed", though I have no idea if anyone else uses such terminology) ... and thus other units that have `After=time-sync.target` & `Require=time-sync.target` still get run.
> 
> I propose that this end-result is a bug .. though I don't know how to address it.
> 
> I can work-around this by adding `After=chrony-wait.service` & `Requires=chrony-wait.service` to my unit (or `BindsTo=chrony-wait.service`), but I propose that the whole point of of time-sync.target is to have a one-stop shop -- i.e., to have a single method-agnostic (ntp vs chronyd vs whatever else) pre-requisite that any unit can require to ensure time-syncing has completed.

### In case of bug report: Steps to reproduce the problem

> 1. Prevent chronyd from getting to its servers (using firewall on host or outer host/network to block) or just edit `Server` line(s) in `chrony.conf` to point to nonsense.
> 2. Create a service that depends on time-sync.target, e.g.:
>     ```
>     [root@f25 ~]# cat >/etc/systemd/system/my.service <<E  
>     > [Unit]
>     > After=time-sync.target
>     > Requires=time-sync.target
>     > 
>     > [Service]
>     > Type=oneshot
>     > ExecStart=/bin/wall started my.service
>     > 
>     > [Install]
>     > WantedBy=multi-user.target
>     > E
>     [root@f25 ~]# systemctl daemon-reload
>     [root@f25 ~]# systemctl enable my
>     ```
> 3. Enable chrony-wait.service & optionally lower chrony-wait.service timeout from 10 minutes to 1min, e.g.:
>     ```
>     [root@f25 ~]# mkdir /etc/systemd/system/chrony-wait.service.d
>     [root@f25 ~]# echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/chronyc -h 127.0.0.1,::1 waitsync 60 0.1 0.0 1' >/etc/systemd/system/chrony-wait.service.d/waitsync.conf
>     [root@f25 ~]# systemctl daemon-reload
>     [root@f25 ~]# systemctl enable chrony-wait
>     ```
> 4. Reboot and watch that service start after chrony-wait fails.

**Comment by poettering** [comment]
if you do RequiredBy=time-sync.target in the [Install] section of your chrony-wait.service, then you should get the behaviour you want (after reenabling it of course), no?

**Comment by ryran** [comment]
@poettering 
Thanks Lennart -- a quick test shows that your suggested change does indeed lead to the desired behavior (and also works as expected when ntp-syncing is allowed).

That said, in Fedora, neither `chrony-wait.service` nor `ntpdate.service` are configured like this. Would your recommendation be that distro maintainers add `RequiredBy=time-sync.target` to their ntp-wait service units? Should the the time-sync.target section in **systemd.special(7)** be updated?

**Comment by ryran** [comment]
PS: One annoying thing about this approach for end-users is that, as you know, the `[Install]` section can't be modified with drop-in cfg files... So when giving admins a work-around I'll probably have them do a drop-in for time-sync.target instead.

**Comment by poettering** [comment]
I am not sure that time-sync.target should fail like that by default. If the clock can't be corrected, then the system should just proceed booting I think, and not make everything fail...

**Comment by ryran** [comment]
@poettering said:
> I am not sure that time-sync.target should fail like that by default. If the clock can't be corrected, then the system should just proceed booting I think, and not make everything fail...

I'm with you if a unit just **Wants** time-sync.target ... but in my opinion if a unit **Requires** it, that's a different story. If we've got cluster or grid nodes that can ONLY do their post-bootup work if we're sure time has synced, well........
.

**Comment by poettering** [comment]
@ryran well, sure, but that's your specific case, not the general case. In your case, simply drop in the requires dependency via a unit drop-in. But I am very sure this shouldn't be the default. most machines should not fail to work when NTP is not reachable...

I hope this makes sense. Closing hence.
