### ISSUE TITLE
systemd v232 breaks boot as udev fails to start

### ISSUE THREAD

**Issue by CounterPillow** [systemd/systemd#4882]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

The system booting

### In case of bug report: Unexpected behaviour you saw

udev not starting, the child process dies as it's started.
systemd emergency shell being useless because the keyboard doesn't work

### In case of bug report: Steps to reproduce the problem

It's probably very dependant upon configuration, so this is hard to say. I will however be glad to provide you with any additional debug output if you tell me how to obtain it.

[This is what I see without any debug options on](https://0x0.st/9iu.jpg), you'll have to deal with photographs because I don't have any other way to get output out of this system considering I cannot get a working shell, cannot write to any disks, and it doesn't have a serial port like most devices made in this millenium.

I've asked the Arch Linux bug tracker people for any ways to get useful debug info out of this, and your IRC channel the same, but I haven't gotten a reply at either place, so before saying "I can't do anything with more logs", please tell me how to obtain those logs in this situation.

Booting works fine with systemd v231, which is what I'm using for now.

Setting the boot options "systemd.log_level=debug systemd.log_target=console" results in no useful information, all it says is that the udev process died.

**Comment by poettering** [comment]
which architecture is this? 32bit x86?

if you remove the following three lines from your systemd-udevd, does it work then? 

```
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6
```

**Comment by CounterPillow** [comment]
>which architecture is this? 32bit x86?

no. x86_64. Haswell.

>if you remove the following three lines from your systemd-udevd, does it work then?

No, error remains unchanged.

**Comment by poettering** [comment]
Consider booting with "systemd.debug-shell" on the kernel cmdline, and then starting udevd by hand. Does that work?

Also see: https://freedesktop.org/wiki/Software/systemd/Debugging/

**Comment by CounterPillow** [comment]
>Consider booting with "systemd.debug-shell" on the kernel cmdline

I'll try tomorrow. Does the early debug shell provide me with a working keyboard (unlike the emergency shell)?

**Comment by poettering** [comment]
i don't see why the kbd shouldn't work. or is that some weird stuff? bluetooth?

**Comment by CounterPillow** [comment]
nope, integrated laptop keyboard. Can't see it on lsusb so I'm assuming it's connected through something like ps/2?

I've also tried plugging in a USB keyboard, but that didn't help. In fact, it didn't even light up.

**Comment by poettering** [comment]
maybe your kernel is weird and you compiled the kbd drivers as loadable module or so?

**Comment by CounterPillow** [comment]
stock arch kernel. How would I check if that's the case?

**Comment by CounterPillow** [comment]
Adding "systemd.debug-shell" to my kernel options doesn't give me a debug shell.

```
✓ fratti@archbook ~ $ cat /proc/cmdline
initrd=\intel-ucode.img initrd=\initramfs-linux.img elevator=noop systemd.debug-shell quiet video.use_native_backlight=1 acpi_osi= resume=UUID=e3a957e4-6a55-4490-b9cc-3fe217b86e89 root=UUID=b19b2880-f4c5-481a-aabd-e84deaea2713 rw
```

**Comment by CounterPillow** [comment]
Removing quiet does not change the output, here's a screenshot with "systemd.log_level=debug systemd.log_target=console"

![](https://0x0.st/9Kz.jpg)

**Comment by poettering** [comment]
exit code 127 is pretty strange, we never generate that...

If you add "systemd.journald.forward_to_console=1" to the kernel cmdline, does it get anymore interesting?

**Comment by CounterPillow** [comment]
oh we got somewhere alright

`[89]: /usr/lib/systemd/systemd-udevd: error while loading shared libraries: libz.so.1: cannot enable executable stack as shared object requires: Operation not permitted`

What's happening here?

**Comment by CounterPillow** [comment]
Solved it. The issue was caused by having the package `zlib-asm` installed instead of the Arch Linux default `zlib` package.
