### ISSUE TITLE
systemd-journal-gatewayd: Provide a since/untill option

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#4883]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> ArchLinux

Hello

It could be very useful if the gateway had a API parameter to show log events between two timestamp (like journalctl --since and --until).
The only option currently seems to be pulling a lot unnecessary log events and do the filtering client side, which is unnecessary and a waste of cpu/memory.

Regards Kristian

**Comment by jrollins** [comment]
Hi, yes, this would be a very useful feature.  Thanks!
