### ISSUE TITLE
automount : df -h hangs forever

### ISSUE THREAD

**Issue by overweight** [systemd/systemd#4886]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
> systemd-219

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> CentOS-AARCH64

### In case of bug report: Expected behaviour you didn't see
> …
### In case of bug report: Unexpected behaviour you saw
> df -h , ls /proc/sys/fs/binfmt_misc hangs forever

the pid of df -h is 19999
Storage:/usr/lib/systemd/system # cat /proc/19999/stack 
[<ffffffc000204ebc>] __switch_to+0x84/0xa0
[<ffffffc0003fdfe4>] autofs4_wait+0x364/0x710
[<ffffffc0003fcc14>] autofs4_mount_wait+0x44/0x70
[<ffffffc0003fccbc>] autofs4_d_manage+0x7c/0x190
[<ffffffc000389fb0>] follow_managed+0xc0/0x2c8
[<ffffffc00038c3f8>] lookup_fast+0x148/0x358
[<ffffffc00038ec60>] path_lookupat+0xf8/0x7a8
[<ffffffc00038f348>] filename_lookup+0x38/0xf0
[<ffffffc000390d48>] user_path_at_empty+0x78/0xd0
[<ffffffc000390dbc>] user_path_at+0x1c/0x28
[<ffffffc000384514>] vfs_fstatat+0x7c/0xe8
[<ffffffc000384b98>] SyS_newfstatat+0x38/0x70
[<ffffffc000203e8c>] __sys_trace_return+0x0/0x4
[<ffffffffffffffff>] 0xffffffffffffffff

strace info.

read(3, ",noexec,relatime,freezer 0 0\ncgr"..., 1024) = 1024
read(3, "er_bin ext3 rw,noatime,nodiratim"..., 1024) = 273
read(3, "", 1024)                       = 0
close(3)                                = 0
munmap(0x7f9fc51000, 65536)             = 0
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=600, ...}, 0) = 0
newfstatat(AT_FDCWD, "/proc", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/dev", {st_mode=S_IFDIR|0755, st_size=5780, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/kernel/security", {st_mode=S_IFDIR|0755, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/dev/shm", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=60, ...}, 0) = 0
newfstatat(AT_FDCWD, "/dev/pts", {st_mode=S_IFDIR|0755, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/run", {st_mode=S_IFDIR|0755, st_size=840, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup", {st_mode=S_IFDIR|0755, st_size=260, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/systemd", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/cpuset", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/blkio", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/memory", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/devices", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/freezer", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/net_cls", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/sys/fs/cgroup/perf_event", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/proc/sys/fs/binfmt_misc", 

the output of mount is ,
Storage:/usr/lib/systemd/system # mount
rootfs on / type rootfs (rw,size=1886344k,nr_inodes=235793)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=943172k,nr_inodes=235793,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=26,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
/dev/md2 on /startup_disk/conf type ext3 (rw,noatime,nodiratime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
/dev/md3 on /OSM/coffer_log type ext3 (rw,noatime,nodiratime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
/dev/md6 on /crash type ext3 (rw,noatime,nodiratime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
/dev/md5 on /OSM/coffer_data type ext3 (rw,noatime,nodiratime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
/dev/md1 on /startup_disk/image type ext3 (ro,noatime,nodiratime,sync,errors=continue,user_xattr,acl,barrier=1,data=ordered)
/dev/md4 on /OSM/coffer_bin type ext3 (rw,noatime,nodiratime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime)
cgroup on /cgroup/dfx_long_stress type cgroup (rw,relatime,name=kernel_precise)
none on /dev/cpuacct type cgroup (rw,relatime,cpuacct)

Storage:/usr/lib/systemd/system # systemctl show proc-sys-fs-binfmt_misc.automount 
Id=proc-sys-fs-binfmt_misc.automount
Names=proc-sys-fs-binfmt_misc.automount
WantedBy=sysinit.target
Before=sysinit.target proc-sys-fs-binfmt_misc.mount systemd-binfmt.service
After=-.mount
Triggers=proc-sys-fs-binfmt_misc.mount
RequiresMountsFor=/proc/sys/fs
Documentation=https://www.kernel.org/doc/Documentation/binfmt_misc.txt http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
Description=Arbitrary Executable File Formats File System Automount Point
LoadState=loaded
ActiveState=active
SubState=running
FragmentPath=/usr/lib/systemd/system/proc-sys-fs-binfmt_misc.automount
UnitFileState=static
InactiveExitTimestamp=Thu 1970-01-01 08:00:02 CST
InactiveExitTimestampMonotonic=2639625
ActiveEnterTimestamp=Thu 1970-01-01 08:00:02 CST
ActiveEnterTimestampMonotonic=2639625
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=no
OnFailureIsolate=no
IgnoreOnIsolate=yes
IgnoreOnSnapshot=no
NeedDaemonReload=no
JobTimeoutUSec=0
ConditionTimestamp=Thu 1970-01-01 08:00:02 CST
ConditionTimestampMonotonic=2639510
ConditionResult=yes
Transient=no
Where=/proc/sys/fs/binfmt_misc
DirectoryMode=0755
Result=success

### In case of bug report: Steps to reproduce the problem

> … I don't know how to reproduce.

**Comment by poettering** [comment]
sorry, 219 is too old. We only track issues the two most recent systemd versions upstream. For everything else please contact your downstream distros. Sorry.

(This is very explicilty mentioned on the contribution guidelines text linked from the issue submission form btw)
