### ISSUE TITLE
Cannot automatically recognize usb partition table Unless use "partprobe"

### ISSUE THREAD

**Issue by WallanceLee** [systemd/systemd#489]
I use linux kernel 4.1.0 in my Gentoo Linux.
I think it is something about udev.
Whenever I insert my USB-HDD into USB-port, kernel cannot read the partition table automatically.
But when I use the partprobe command, it can read my partition table.
I want to know whether it is a bug.

As the following, the output of the "dmesg|tail":
dmesg | tail 
[ 5384.806237] usb-storage 1-4:1.0: USB Mass Storage device detected 
[ 5384.807159] scsi host8: usb-storage 1-4:1.0 
[ 5386.440476] scsi 8:0:0:0: Direct-Access     hp       v250w            1100 PQ: 0 ANSI: 4 
[ 5386.440660] sd 8:0:0:0: Attached scsi generic sg2 type 0 
[5386.440899] sd 8:0:0:0: [sdb] 31506432 512-byte logical blocks: (16.1 GB/15.0 GiB) 
[ 5386.441314] sd 8:0:0:0: [sdb] Write Protect is off 
[ 5386.441319] sd 8:0:0:0: [sdb] Mode Sense: 43 00 00 00 
[ 5386.441758] sd 8:0:0:0: [sdb] No Caching mode page found 
[ 5386.441762] sd 8:0:0:0: [sdb] Assuming drive cache: write through 
[ 5386.445789] sd 8:0:0:0: [sdb] Attached SCSI removable disk

ls /dev/sd*
/dev/sda  /dev/sda1  /dev/sda2  /dev/sda3  /dev/sda4  /dev/sda5  /dev/sda6  /dev/sda7  /dev/sda8  /dev/sdb
As above, there is not /dev/sdbX(X=1,2,3...)
Then, I use "sudo partprobe" 
ls /dev/sd*
/dev/sda  /dev/sda1  /dev/sda2  /dev/sda3  /dev/sda4  /dev/sda5  /dev/sda6  /dev/sda7  /dev/sda8  /dev/sdb  /dev/sdb1
As above, the /dev/sdb1 occurred.

I want to know whether it is a bug.I didn't want to insert "partprobe" command whenever I use my USB devices.

Yours sincerely
Thanks.

**Comment by kaysievers** [comment]
udev does not do anything with devices, or partition scanning, all that happens inside the kernel.

**Comment by poettering** [comment]
Please file a bug to the kernel bugzilla. Partition scanning and device node creation are done in the kernel (the latter in devtmpfs) and userspace is not involved. Closing hence.

**Comment by WallanceLee** [comment]
Oh,sorry.I know it because I closed a kernel option.
