### ISSUE TITLE
 /usr/lib/systemd/system-shutdown folder missing and, if created, useless

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#4894]
### Submission type

  - [X ] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu Server 16.04 LTS 64 bits

### In case of bug report: Expected behaviour you didn't see

> In https://www.freedesktop.org/software/systemd/man/systemd-halt.service.html is said:

 Immediately before executing the actual system halt/poweroff/reboot/kexec systemd-shutdown will run all executables in /usr/lib/systemd/system-shutdown/ and pass one arguments to them: either "halt", "poweroff", "reboot" or "kexec", depending on the chosen action. All executables in this directory are executed in parallel, and execution of the action is not continued before all executables finished.

I just NEED this feature, but:

- /usr/lib/systemd/system-shutdown doesn't exist
- I've created manually and I've put inside this script:

#!/bin/bash
salida=/home/usuario/test
fecha=`/bin/date`
/bin/echo "$fecha - Ejecución del script test $1" >>$salida
sleep 30
fecha=`date`
echo -e "$fecha - Termina la ejecución\n" >>$salida

- Doing an init 0 the system stops immediatelly (so, obviously, script doesn't run)

### In case of bug report: Unexpected behaviour you saw

> Script should run (according to documentation) but it's not

Thanks!!

**Comment by fsateler** [comment]
This is because debian/ubuntu enable `split-usr`, and thus the folder is `/lib/systemd/systemd-shutdown`.

This is not an upstream bug, and can be closed.

**Comment by poettering** [comment]
@fsateler i invited you to the github admin team now. Please go ahead and close bugs like this right-away if you are confident that that's the right thing!

**Comment by fsateler** [comment]
@poettering thanks!

**Comment by q2dg** [comment]
Ooh, you're superfast closing and resolving things!! 
Thanks a lot! You're right!
And sorry a lot for the inconveniences.

**Comment by fsateler** [comment]
@q2dg We have updated the documentation downstream-side a bit, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826297 for more details.

**Comment by fkbreitl** [comment]
1. I want to add a small correction: The folder name is `/lib/systemd/system-shutdown`.

2. My script place there does not not get executed on a Raspbian 8.0 Jessie and a Debian 9.0 testing system. It seems to me Systemd is still broken. Can we open the issue again?

**Comment by ryancasler** [comment]
I tried this and it did not execute the script before shutdown.  the script is extremely simple
```
#!/bin/bash

curl -s -o /dev/null <URL with private data>
```

**Comment by poettering** [comment]
@ryancasler scripts in that directory are executed very very late at shutdown, at a time the network is already down, hence curl is unlikely to work

**Comment by ryancasler** [comment]
Ugh... If I'd known that I wouldn't have spent so many hours reworking and debugging all the things I thought I was doing wrong. At least now I know I'm not crazy. Thank you.  Any ideas/advice on what might work?

**Comment by fkbreitl** [comment]
@ryancasler In fact you have encountered the problem described at https://unix.stackexchange.com/q/347306/159562 .
The solution is to create a systemd service as described at https://unix.stackexchange.com/a/347686/159562 .

**Comment by fkbreitl** [comment]
@ryancasler In fact you have encountered the problem described at https://unix.stackexchange.com/q/347306/159562.
The solution is to create a systemd service as described at https://unix.stackexchange.com/a/347686/159562.
