### ISSUE TITLE
Lower priority of 'Time has been changed' log message because of very high frequency on mobile devices

### ISSUE THREAD

**Issue by kimmoli** [systemd/systemd#4896]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

208 but codebase is similar in latest, see references below

### Used distribution

Sailfish

### Background

When kernel resumes from suspend, all timers are cleared. This causes systemd watch time to trigger due TFD_TIMER_CANCEL_ON_SET flag, which causess the mentioned log entry to appear on every resume.

On mobile systems, suspend and resume occurs at ten-fold rate compared to desktops, and causes this to spam journal logs, e.g. in situation where another console session over network is used to monitor `journal -f` and another is used to give user input/test commands, while mobile device has screen turned off, and on every keypress in another console causes journal to log "Time has been changed" message from PID1 and user space process. This kinda renders log unusable.

Lowering overall logging level is not a option, as systemd LOG_INFO provides some interesting entries too.

```
May 22 12:10:28 localhost systemd[1]: Time has been changed
May 22 12:10:28 localhost systemd[1033]: Time has been changed
May 22 12:10:30 localhost systemd[1]: Time has been changed
May 22 12:10:30 localhost systemd[1033]: Time has been changed
```

### References

**HEAD at time of writing this**

https://github.com/systemd/systemd/blob/161f1ee134ed405c2d87a0dcae4ae0d0882779b4/src/core/manager.c#L363
-->
https://github.com/systemd/systemd/blob/161f1ee134ed405c2d87a0dcae4ae0d0882779b4/src/core/manager.c#L2170

**Historical 208**

https://github.com/systemd/systemd/blob/1434ae6fd49f8377b0ddbd4c675736e0d3226ea6/src/core/manager.c#L344
-->
https://github.com/systemd/systemd/blob/1434ae6fd49f8377b0ddbd4c675736e0d3226ea6/src/core/manager.c#L1733

**Latest Kernel** 
timekeeping_resume() --> hrtimers_resume() --> clock_was_set() --> timerfd_clock_was_set()

here'ish https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/kernel/time/hrtimer.c?id=refs/tags/v4.9#n743

### Request

Lower priority of "Time has been changed" log message from LOG_INFO to LOG_DEBUG

**Comment by evverx** [comment]
> Lower priority of "Time has been changed" log message from LOG_INFO to LOG_DEBUG

Why not to fix that downstream?

**Comment by kimmoli** [comment]
Yes, we can fix it downstream, but maintainers prefer to use upstream patches. 

If systemd has future focus on mobile devices, it could benefit getting some feedback from mobile OS distributions.

**Comment by evverx** [comment]
@kimmoli , sorry for the previous reply.

> it could benefit getting some feedback from mobile OS distributions

Sure. Thanks for the feedback.

**Comment by kimmoli** [comment]
thanks
