### ISSUE TITLE
Add template specifier for unit start timestamp

### ISSUE THREAD

**Issue by ymartin59** [systemd/systemd#4898]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### Request

For service template, a specifier providing unit start timestamp (for instance in ISO format) would be convenient for various usages, for instance to create a per-startup log file name.

As a use case, I am used to start JVM processes with -Xloggc option and to prevent previous execution log to be replaced, the best way is to include a timestamp in log file name.

**Comment by evverx** [comment]
Related https://github.com/systemd/systemd/issues/4519#issuecomment-257576390

**Comment by poettering** [comment]
the specifiers are expanded at configuration load time. And i am pretty sure thats good that way and should stay that way. Hence i dont think adding what you ask for would be a good idea, sorry.

That said, systemd git passes a 128bit id that uniquely identifies a service invocation to each forked of process in $INVOCATION_ID. I figure that could work for your usecase too. This field is also implicitly attached to all log messages the journal collects and hence has the benefit of permitting matching up service invocation cycles.

Hope this is useful.

**Comment by ymartin59** [comment]
Thank you for this idea... There is still a work-around consisting in creating a shell script just for that configuration task.
When used to old Debian sysv init system based on shell script allowing any customization in "/etc/default/service" file, switching to systemd raw key/value pair environment file requires some compromise.

**Comment by evverx** [comment]
> systemd git passes a 128bit id that uniquely identifies a service invocation to each forked of process in $INVOCATION_ID

@poettering , the invocation id is the good idea. But it's not reliable: https://github.com/systemd/systemd/issues/4441 (and https://github.com/systemd/systemd/pull/4806 also incompatible with containers )

**Comment by evverx** [comment]
@ymartin59 
> I am used to start JVM processes with -Xloggc option and to prevent previous execution log to be replaced

https://bugs.openjdk.java.net/browse/JDK-8009444
> GC logging has been migrated to unified logging and log files are now opened in with O_APPEND

Does it work?

**Comment by evverx** [comment]
Hm, I was wrong, of course. The `INVOCATION_ID` works fine for that particular usecase. Sorry
