### ISSUE TITLE
unable to set log level via environment for logind

### ISSUE THREAD

**Issue by oliverhenshaw** [systemd/systemd#4900]
### Submission type

  - [ x] Bug report
  - [ x] Request for enhancement (RFE)

### systemd version the issue has been seen with
systemd-231-10.fc25.x86_64
(and git, by code inspection)

### Used distribution
Fedora 25

### In case of bug report: Expected behaviour you didn't see

Enabling debug logs for logind via:
$ cat /etc/systemd/system/systemd-logind.service.d/debug.conf 
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug

does not work. Since there's no debug setting in logind.conf and aiui logind does not take any command-line arguments, the only way to enable debug messages for logind is by adding "systemd_log_level=debug" to the kernel commandline - however this will also make PID1 and all other systemd-xxx tools just as chatty.

The reason for this is the use of secure_getenv in src/basic/log.c:log_parse_environment() - since systemd-logind.service restricts the Capabilities of the binary this will always return NULL instead of the environment string. Patching logind to use getenv() makes "Environment=SYSTEMD_LOG_LEVEL=debug" work as expected.

There will be a similar problem with the other SYSTEMD_LOG_XXX env variables. Also other systemd tools may have the same issue:

$ grep Capability /usr/lib/systemd/system/systemd-*.service
/usr/lib/systemd/system/systemd-hostnamed.service:CapabilityBoundingSet=CAP_SYS_ADMIN
/usr/lib/systemd/system/systemd-journald.service:CapabilityBoundingSet=CAP_SYS_ADMIN CAP_DAC_OVERRIDE CAP_SYS_PTRACE CAP_SYSLOG CAP_AUDIT_CONTROL CAP_AUDIT_READ CAP_CHOWN CAP_DAC_READ_SEARCH CAP_FOWNER CAP_SETUID CAP_SETGID CAP_MAC_OVERRIDE
/usr/lib/systemd/system/systemd-localed.service:CapabilityBoundingSet=
/usr/lib/systemd/system/systemd-logind.service:CapabilityBoundingSet=CAP_SYS_ADMIN CAP_MAC_ADMIN CAP_AUDIT_CONTROL CAP_CHOWN CAP_KILL CAP_DAC_READ_SEARCH CAP_DAC_OVERRIDE CAP_FOWNER CAP_SYS_TTY_CONFIG
/usr/lib/systemd/system/systemd-modules-load.service:ConditionCapability=CAP_SYS_MODULE
/usr/lib/systemd/system/systemd-networkd.service:ConditionCapability=CAP_NET_ADMIN
/usr/lib/systemd/system/systemd-networkd.service:CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW CAP_SETUID CAP_SETGID CAP_SETPCAP CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER
/usr/lib/systemd/system/systemd-resolved.service:CapabilityBoundingSet=CAP_SETUID CAP_SETGID CAP_SETPCAP CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_NET_RAW CAP_NET_BIND_SERVICE
/usr/lib/systemd/system/systemd-timedated.service:CapabilityBoundingSet=CAP_SYS_TIME
/usr/lib/systemd/system/systemd-timesyncd.service:ConditionCapability=CAP_SYS_TIME
/usr/lib/systemd/system/systemd-timesyncd.service:CapabilityBoundingSet=CAP_SYS_TIME CAP_SETUID CAP_SETGID CAP_SETPCAP CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER
/usr/lib/systemd/system/systemd-tmpfiles-setup-dev.service:ConditionCapability=CAP_SYS_MODULE

**Comment by poettering** [comment]
hmm, secure_getenv() returns NULL if we are root but *lack* some privs? that's strange, no?

**Comment by arvidjaar** [comment]
Well, according to manual page, it returns NULL if "the process has a nonempty permitted capability set" among other things. Nothing is said about being root. This sounds like what happens here.

**Comment by keszybz** [comment]
See also #4525.

**Comment by poettering** [comment]
I wonder if we should add our own secure_getenv() replacement that only checks for actual suid-invocation and caps above what a process really should have...
