### ISSUE TITLE
should_umount() is wrong

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#4902]
Just an issue to mkae sure @evverx's comments aren't forgotten:

https://github.com/systemd/systemd/pull/4515#issuecomment-266789802

**Comment by fbuihuu** [comment]
@evverx just in case, ping me if you want me to sort this out. Thanks.

**Comment by evverx** [comment]
@fbuihuu , it would be great. Thanks!

**Comment by evverx** [comment]
https://github.com/systemd/systemd/pull/4901#issuecomment-267626571
>@fbuihuu btw I invited you to the github systemd maintainers group

oh, and welcome!

**Comment by fbuihuu** [comment]
@evverx thanks :)

**Comment by fbuihuu** [comment]
I'm working on this currently and I'm stumbling on the fact that in `mount_setup_unit()` we set unconditionally `MOUNT(u)->from_proc_self_mountinfo = true;`.

I wouldn't have expected it as mount unit loaded from a fragment will also have this flag set.

For example:

> $ systemd-analyze dump
> ...
> -> Unit opt.mount:
> ...
>        Documentation: man:systemd-fstab-generator(8)
>        Fragment Path: /run/systemd/generator/opt.mount
>        From /proc/self/mountinfo: yes
>        From fragment: yes
> ...

Is this expected ?

**Comment by poettering** [comment]
@fbuihuu yes, it is. from_proc_self_mount_info is true if the mount point is being listed in /proc/self/mountinfo, and from_fragment if there's a fragment file for it.

from_proc_self_mount_info is hence true whenever something is actually mounted. from_fragment only if there's a unit file for it. They are pretty much independent of each other: there may be a unit file which isn't active and hence no /proc/self/mountinfo entry for. And there may be active mounts that aren't defined in any fragment file (for example because somebody simply invoked /bin/mount on the command line...)

**Comment by fbuihuu** [comment]
@poettering, I see ... I was a bit mislead by the flag names.

Another thing I'm wondering is how the code should (and does) handle the following use case:

> mount -t tmpfs none /mnt
> mount -o remount,x-initrd.mount /mnt

Adding specific mount flags later and the relevant deps don't seem to be updated accordingly.

Is it really the case or am I miss reading the code ?

Thanks.

**Comment by poettering** [comment]
@fbuihuu there's the general problem that we cannot "update" deps right now. We can only add deps, never lose them, until the next full daemon-reload. This is not only a problem with x-initrd.mount, but also with dependencies declared in udev rules for ".device" units.

This is fixable, but so far noone bothered sitting down and actually doing something about this. The reason this is not available right now is simply that we don't track in the dependency "Set*" objects who created a dependency: was it the source unit's unit file, was it the destination unit's unit file, was it a udev rule, was it a mount option? As long as we don't track that we don't know what to flush out again when something changes: after all we shouldn't flush out dependencies created via a unit file if you you issue a "remount" command...

My plan to fix this is by changing the Set* objects we track dependencies in into Hashmap* objects, and the lookup destination would be a bitset that encodes which piece of code created a dependency, so that we know what to flush out. But that hasn't happened yet, hence for now, please ignore the issue, and just keep adding deps, even though that's a bit ugly...

**Comment by fbuihuu** [comment]
@poettering thanks for the details !

I'm going to push a fix.
