### ISSUE TITLE
boot: EFI stub too eager to replace built-in command line

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#4903]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch Linux

The EFI stub included with `systemd-boot` (`src/boot/efi/stub.c`, installed to `/lib/systemd/boot/efi/linux<EFI-MACHINE-TYPE-NAME>.efi.stub`) silently replaces the kernel command line built into the image with one supplied at runtime if the length of that command line (the `LoadOptions`, if I understand correctly) is nonzero. This caused me a bit of grief, in a combination of two factors:

- When booting from UEFI Shell (v2, though I don’t think it matters), the command line wasn’t empty, but the name of the booted image:
  ```sh
  $ cat /proc/cmdline
  linux.img
  ```
  (Where `linux.img` was the name of the combined file, directly under the ESP root, called as such in the UEFI shell.)
- When booting from an UEFI boot entry directly, the command line apparently still wasn’t empty. `/proc/cmdline` displayed as a blank line (and I assume the newline is added by the kernel and wasn’t part of the `LoadOptions` from UEFI), but for some reason the stub still didn’t use the cmdline in the executable. I can try to investigate what exactly the `LoadOptions` was tomorrow. (Vague guess for now: `"\0"`?)

I think it would be helpful if the stub tried a bit harder to determine if the command line it’s going to use instead of the built-in one makes sense: does it contain anything except for the name of the executable itself and whitespace? If not, ignore it and keep using the cmdline in the executable.

(I suppose this somehow conflicts with the desire to support a functional boot with an empty command line – with discoverable partitions and everything – and to test that…)

**Comment by poettering** [comment]
@msekletar any idea?

**Comment by mythi** [comment]
I've been hit by this too. However, the first bullet seems like a valid use-case, IMO.

The second bullet seems more problematic because (for me at least), I get ```LoadOptionsSize > 0``` but ```*LoadOptions == 0```.

My proposal to fix this would be
```
-        if (!secure && loaded_image->LoadOptionsSize > 0) {
+        if (!secure && loaded_image->LoadOptionsSize > 0 && *(CHAR16 *)loaded_image->LoadOptions != 0) {
```

Tested on two different Intel NUCs that failed for me.
