### ISSUE TITLE
systemctl show ... -p ... -p ...: no way to order output

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4907]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807460

No way to order output. No matter which of
```
systemctl show * -p Id -p TimeoutStopUSec
systemctl show *  -p TimeoutStopUSec -p Id
systemctl show *  -p TimeoutStopUSec -p Names
systemctl show *  -p Names -p TimeoutStopUSec
```
we use, TimeoutStopUSec always comes out first.

**Comment by poettering** [comment]
well, "-p" is a filter that limits the output. It's not a mechanism for ordering things, and I really doubt it should be... Parsing the output by order sounds very wrong to me, we tag the fields with field names for a reason...
