### ISSUE TITLE
systemctl man page needs full examples for multiple property assignment

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4908]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807464

File: /usr/share/man/man1/systemctl.1.gz

We read:
```
           --runtime is passed, in which case the settings only apply until
           the next reboot. The syntax of the property assignment follows
           closely the syntax of assignments in unit files.

           Example: systemctl set-property foobar.service CPUShares=777

           Note that this command allows changing multiple properties at the
           same time, which is preferable over setting them individually. Like
           unit file configuration settings, assigning the empty list to list
           parameters will reset the list.
```
OK but you then need to add a further example:

   ```systemctl set-property foobar.service nurdbar.servive CPUShares=777```

Or

 ```systemctl set-property foobar.service CPUShares=777 BlaBoo=888```

Or

  ```systemctl set-property foobar.service nurdbar.servive CPUShares=777 BlaBoo=888```

to clarify.

Also give an example of assigning the empty list.

Since the syntax "follows closely" but not exactly, hence full examples
are needed.

**Comment by poettering** [comment]
Fix waiting in #13036
