### ISSUE TITLE
systemctl status should propagate through PartOf

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4909]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826041

We have a few services, which use templates (and a generator).
To control all instances in one go, the instances foo@.service declare to be PartOf=foo.service
Most of them also use ReloadPropagatedFrom=foo.service

It would be nice, if using "status" on such a foo.service which is composed by several sub-services via PartOf propagates the status request and merges that into a single output.

Or instead of doing it automatically, we add a dedicated key, like PropagatesReloadTo, say ProgatesStatusTo

**Comment by poettering** [comment]
hmmpf, I am not sure I am overly convinced by this request, but well...

**Comment by petercolberg** [comment]
> To control all instances in one go, the instances foo@.service declare to be PartOf=foo.service

I kind of wish Debian would not have gone down this road, since it is quite confusing for the administrator to have these dummy services with `ExecStart=/bin/true`. The same can be achieved with a wildcard query, e.g., `systemctl status foo@*.service` (which may need to be quoted depending on the shell).

**Comment by poettering** [comment]
Oh, I didn't see that PartOf=foo.service was proposed here. That sounds really wrong to me. They only case where PartOf makes sense if the specified unit is a target unit.

Doing dummy services with ExecStart=/bin/true is pretty much always an indication that something is off, and can be solved differently in a better way.

And yes, doing systemctl status with a glob (which is already supported) sounds like the much better option here...

I am inclined to close this issue I must say, after reading @petercolberg's comment.

@mbiebl, why isn't "systemctl status foo@*.service" a better idea? Why fake these dummy services?

**Comment by mbiebl** [comment]
@poettering what would be the alternative if you want to (re)start, reload and stop all instances in one go? Problem is, that target units as-is are incomplete in that regard, so dummy units are currently the only way.

**Comment by mbiebl** [comment]
see e.g. #710

**Comment by mbiebl** [comment]
so, I agree that such dummy units are ugly, but there is no alternative atm afaics

**Comment by poettering** [comment]
"systemctl reload foobar@*.service" should work too. Globbing appears an OK way out.

So far this never came up on Fedora btw. I am curious what Fedora packages do where Debian packages are trying to use this.

**Comment by mbiebl** [comment]
```systemctl reload foobar@.service``` is really crude syntax. ```systemctl reload foobar``` is just so much more intuitive.
Besides, it would only work if that compound service only consists of instances of the same template.
I might have a foo.service(or foo.target) and two services bar.service and baz.service which have PartOf=foo.service (or foo.target)

**Comment by mbiebl** [comment]
Fwiw, services can be part of a target which are not instances of a template.

Say you have A.target, and B.service and C.service are PartOf=A.target, so the globbing syntax  won't help in this case
