### ISSUE TITLE
systemd.network man page does not document MACVTAP

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4914]
### Submission type

  - [X] Bug report

### systemd version the issue has been seen with

> 232 (Debian), but also present in upstream master

### Used distribution

> Debian Sid

### In case of bug report: Expected behaviour you didn't see

> systemd.network manual page documents MACVTAP (like MACVLAN).

### In case of bug report: Unexpected behaviour you saw

> systemd.network manual page does not document MACVTAP. How do attach a MACVTAP to a link is undocumented.

### In case of bug report: Steps to reproduce the problem

> 'man systemd.network'

**Comment by ssahani** [comment]
Please try like below config
```
network]# cat macvtap.netdev 
[NetDev]
Name=macvtap-test
Kind=macvtap
[root@maximus network]# cat macvtap.network
[Match]
Name=macvtap-test
[root@maximus network]# cat enp0s25.network 
[Match]
Name=enp0s25

[Network]
MACVTAP=macvtap-test
```

**Comment by ghost** [comment]
ssahani, I don't know what you are on about. I know that MACVTAP option in [Network] works. But it's undocumented, and that's a bug (IMHO).

**Comment by ssahani** [comment]
@courmisch Wanted a confirmation before I document it . Does this conf works for you ? Thanks for confirming .

**Comment by ghost** [comment]
Yes, it seems to work.

**Comment by ssahani** [comment]
Great I will add  a example .
