### ISSUE TITLE
systemd-run does not always terminate with --wait option

### ISSUE THREAD

**Issue by larsch** [systemd/systemd#4920]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

```
systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

`systemd-run --wait true` should always exit

```
# systemd-run --wait true
Running as unit: run-u91.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 5ms
```

### In case of bug report: Unexpected behaviour you saw

`systemd-run --wait true` hangs indefinitely

```
# systemd-run --wait true
Running as unit: run-u93.service
...
```

### In case of bug report: Steps to reproduce the problem

```
# while true; do systemd-run --wait true; done
```

**Comment by poettering** [comment]
Fix waiting in #4973.
