### ISSUE TITLE
IPv6AcceptRA also enabled DHCPv6

### ISSUE THREAD

**Issue by halvors** [systemd/systemd#4921]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

### Used distribution

> Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> None

### In case of bug report: Unexpected behaviour you saw

> When "IPv6AcceptRA" is true, DHCP=ipv6 is also enabled. There is no way to disable this.

### In case of bug report: Steps to reproduce the problem

> Configure interface with IPv6AcceptRA enabled.

**Comment by poettering** [comment]
well, IPv6 RA contains a flag that tells us to retry with DHCPv6, which we honour, and hence start DHCPv6 as response of it. This is documented in the man page:

> When RAs are accepted, they may trigger the start of the DHCPv6 client if the relevant flags are set in the RA data, or if no routers are found on the link.

This hence well-defined, documented, RFC-mandated behaviour. Closing hence.
