### ISSUE TITLE
[systemd-networkd] In VM with virtual: "$interface : Detected Tx Hung "

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4922]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

### My Distribution

Arch Linux

### The Bug:

I have several Virtualmachines with the following Settings:

Hypervisor: Virtualbox
Guest-OS: Arch Linux
Host-OS: Arch Linux

In my Guests I have the problem that i have an error-loop in every TTY with the message:
```
enp3s0: Detected Tx Hung
[...]
enp3s0: Reset adapter
```

This is only the case when I enable systemd-networkd with the following configuration for enp3s0:

```
[Match]
Name=enp3s0

[Network]
DHCP=ipv4
```

**Comment by poettering** [comment]
This really appears to be a kernel/driver/VM problem, not a networkd problem, we just configure the device, but other than that are not involved in tx/rx or irq management at all. Please contact the kernel developers about this.

Sorry!
