### ISSUE TITLE
systemd-boot bootctl: Option to install loader files to any directory, not just 'valid' boot ESP

### ISSUE THREAD

**Issue by morgib** [systemd/systemd#4925]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch Linux

### Feature Request

This request proposes a `bootctl` flag to install the boot file structure to any directory without requiring a check of the mounted fs or interaction with efi vars.

I am originally motivated here by the fact that VirtualBox supports EFI boot from a non-partitioned FAT-formatted volume, but `bootctl` refuses to install to the supplied path when it can't probe a partition table for that mount.  Copying the files from a successful `bootctl` install on a GPT volume onto a bare FAT volume results in an identically functioning system.

Additionally, in this specific use case, the nvram efi variables cannot be used (not persistent across shutdowns), so setting up the files and relying on the default `bootx64.efi` path is all that needs to be done anyway.

I see that the `/boot` fs dir structure can be manually created and the loader image copied in from `/usr/lib/systemd/boot/efi`.  However, for this and most likely other extant edge cases, exposing the `install_binaries` function as `--install-binaries` or `--install-files-only` etc would be beneficial, as it gives you the ability to generate a correct `/boot` structure matching the system `bootctl` version, for whatever purpose is needed.

An additional interface option would be to skip the checks on partition type or turn them into warnings when running with the `--no-variables` option, as that efi var setting appears to be the only function of the program that actually needs a partition number to proceed.

**Comment by poettering** [comment]
we already implicitly turn off the udev checks and the EFI variable access when we detect we are being run in a container. 

I am not sure we should expose proper parameters for what you suggest, but I'd be fine with adding some additional env vars that permit turning off specific functionality of bootctl individually.
