### ISSUE TITLE
libmount-dev needs to be added to the list of dependencies

### ISSUE THREAD

**Issue by ecarew** [systemd/systemd#4932]
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
72d17ce680a22b958b4c074f62d9fa44bc1f54e0

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see
Configure titn'd complete

### In case of bug report: Unexpected behaviour you saw
configure: error: *** libmount support required but libraries not found

### In case of bug report: Steps to reproduce the problem
run configure

**Comment by evverx** [comment]
https://github.com/systemd/systemd/issues/4931#issuecomment-268285482
> dev" is how Debian names the development part of the upstream "libcap" package. Since we are agnostic to distributions (in fact, are fine even with systems where no distro is involved at all, but everything build from upstream), we do not make any reference to the distro-specific names or subpackages in our README, and I am pretty sure we shouldn't.

@ecarew , why not to read https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/control#n13 ?
