### ISSUE TITLE
70-pointingstick.hwdb has instructions for putting in the vendor string, but absolutely no hint on how to actually obtain it

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4938]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
> systemd 231
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 25

### In case of bug report: Expected behaviour you didn't see

> 70-pointingstick.hwdb clarifies on how to obtain `<vendor> is the firmware-provided string from the kernel DMI modalias` since neither xinput list or libinput-list-devices seem to provide the required information. Similarly, for "bZZZZvYYYYpXXXXeWWWW-VVVV" there is an explanation on how a non-kernel developer can obtain this information with the use of a regular terminal / TTY

### In case of bug report: Unexpected behaviour you saw

> 70-pointingstick.hwdb mentions `<vendor> is the firmware-provided string from the kernel DMI modalias` but gives absolutely no hint on how the average user can actually obtain this information. Also, "bZZZZvYYYYpXXXXeWWWW-VVVV" mentions some kernel source files on format details but doesn't actually state how I can easily obtain this information when using a regular terminal as a regular user who doesn't poke around in the kernel all day. I'm sure there are some ways maybe with /proc or others, but unless I spend hours searching I will probably not figure this out easily

### In case of bug report: Steps to reproduce the problem

> Step 1: Open /usr/lib/udev/hwdb.d/70-pointingstick.hwdb and read instructions on top on how to add new matches

**Comment by poettering** [comment]
@whot something to document in the hwdb file via comments?

**Comment by ghost** [comment]
Thanks, the additions are very appreciated :smile:
