### ISSUE TITLE
no eye-of-cylon animation when waiting for remote mount, no feedback when waiting for the mount to show up

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4939]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian

### In case of bug report: Expected behaviour you didn't see

If a remote mount takes too long, the eye of cylon animation is shown

### In case of bug report: Unexpected behaviour you saw

I have an fstab entry for an NFS mount where the server is no reachable. I use "quiet" by default
Upon boot, systemd is completely silent and I simply see a black screen for 90 seconds.

Tried booting with "quiet" removed from the kernel command line. No eye of cylon animation was shown either.

With older systemd version, this was shown automatically, even when using quiet.

### In case of bug report: Steps to reproduce the problem

Add a NFS mount to /etc/fstab where the server is not reachable, like
```does-not-exist:/srv/nfs /mnt nfs auto```

**Comment by mbiebl** [comment]
for a local mount, it still works as expected

**Comment by poettering** [comment]
can you check with the debug shell what "systemctl show" says about the system state when this happens? what jobs are queued with "systemctl list-jobs"?

basically, we show the animation only as long as we'd ask for the spawn confirmation question too. And that we turn off when we decided the system is far enough "up". Which "systemctl show" should tell us...

Note that remote mounts are generally in late boot, which makes them quite different from local mounts.

**Comment by mbiebl** [comment]
[list-jobs.txt](https://github.com/systemd/systemd/files/746456/list-jobs.txt)
[show.txt](https://github.com/systemd/systemd/files/746458/show.txt)
[status.txt](https://github.com/systemd/systemd/files/746457/status.txt)

requested information attached

**Comment by poettering** [comment]
ok, this is weird... hmmm no idea. can you maybe attach gdb to it, and check if `manager_dispatch_jobs_in_progress()` ever gets called when this happens? and if it is, can you check what the manager object's value of "show_status", and "confirm_spawn" are, as well as "no_console_output"?

**Comment by mbiebl** [comment]
@poettering are you not able to reproduce the problem with the fstab entry I posted?

**Comment by poettering** [comment]
well, I haven't tried it... kinda was hoping to let somebody else do the testing here for me ;-)

**Comment by mbiebl** [comment]
fair enough. Just another observation: When I enable NetworkManager-wait-online.service, the problem does not occur. Which suggests this is a timing related problem / race condition.

**Comment by poettering** [comment]
any update? otherwise let's close this.

**Comment by dimyme** [comment]
> any update? otherwise let's close this.

negative. On current   _systemctl --version systemd 244 (244-139-gfb4b046+)_ I used the suggested "non-existing mount" fstab entry but there was neither a delay nor the Cylon animation. v244 booted up like a charm instead. issue closing seems **justified**. :+1:
