### ISSUE TITLE
Allow entering journal messages with custom MESSAGE_ID from command line

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#4951]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch Linux

I think it would be useful to have a way to enter journal messages with a custom `MESSAGE_ID` from the command line, for use in scripts, or also in languages that can’t (easily) interface with the `sd-journal` C API (e. g. Java, Node.js).

At first, I thought this could be an option added to `systemd-cat`, but then I looked at the source code and saw that `systemd-cat` is mostly just a thin wrapper around `sd_journal_stream_fd`. That function doesn’t offer a way to customize message fields, and for a stream, it doesn’t really make as much sense either.

So perhaps a new tool exclusively for entering a single message might be a good idea? Perhaps `systemd-echo` or `systemd-printf`:

```sh
systemd-printf \
    'MESSAGE_ID=…' \
    'CUSTOM_FIELD=abc' \
    'Reticulated spline #%d "%s" (%f %f %f)' \
    "$splineNo" "$splineName" "${splineCoords[@]}"
```

**Comment by evverx** [comment]
Try `logger --journald`

[`man logger`](https://github.com/karelzak/util-linux/blob/d673b74e9d8f484f361ab7c1e8c7e527d7d1753d/misc-utils/logger.1#L83) says:


> --journald[=file]
              Write a systemd journal entry.  The entry is read from the given file, when specified, otherwise from standard input.  Each line must begin with a field that is accepted  by  journald;
              see systemd.journal-fields(7) for details.  The use of a MESSAGE_ID field is generally a good idea, as it makes finding entries easy.  

 Examples:

                  logger --journald <<end
                  MESSAGE_ID=67feb6ffbaf24c5cbec13c008dd72309
                  MESSAGE=The dogs bark, but the caravan goes on.
                  DOGS=bark
                  CARAVAN=goes on
                  end

                  logger --journald=entry.txt

**Comment by lucaswerkmeister** [comment]
Huh, I didn’t even think to look for systemd-specific stuff in `logger`, I thought that was a “legacy” interface. I guess this issue can be closed then. Thanks!
