### ISSUE TITLE
systemd-tmpfiles: chown failed (No such file or directory)

### ISSUE THREAD

**Issue by MingcongBai** [systemd/systemd#4954]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

[AOSC OS](https://aosc.io/)

### In case of bug report: Expected behaviour you didn't see

I should be able to create temporary/daemon directories regardless if I am in systemd-nspawn, booted system, or in chroot. 

### In case of bug report: Unexpected behaviour you saw

The following error occurs when I try to create daemon directory for `stunnel` in chroot:

```
root@thinkpad [ ~ ] # chroot /buildroots/general/
root@thinkpad [ / ] # systemd-tmpfiles --create stunnel.conf
chown(/var/run/stunnel) failed: No such file or directory
```

While the directory is created, the directory has incorrect permissions and owner (given that chown failed...).

```
root@thinkpad [ / ] # ls -la /var/run/stunnel/
total 8
drwxrwx---  2 root root 4096 Dec 22 00:03 .
drwxr-xr-x 17 root root 4096 Dec 22 00:03 ..
```

### In case of bug report: Steps to reproduce the problem

- Chroot.
- Run `systemd-tmpfiles --create <foo>` and attempt to create temporary/daemon directories.

**Comment by evverx** [comment]
Try:
```
mkdir -p /buildroots/general/proc
mount -t proc proc /buildroots/general/proc
chroot /buildroots/general/proc
systemd-tmpfiles --create stunnel.conf
```
Does it work?

**Comment by poettering** [comment]
Also, can you run the command like this please:

```
SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --create stunnel.conf
```

That will enable debug logging for it. Please provide the additional output this generates!

**Comment by MingcongBai** [comment]
> That will enable debug logging for it. Please provide the additional output this generates!

```
root@thinkpad [ / ] # SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --create stunnel.conf
Reading config file "stunnel.conf".
Running create action for entry d /var/run/stunnel
Found existing directory "/var/run/stunnel".
"/var/run/stunnel" has right mode 40770
chown "/var/run/stunnel" to 983.983
chown(/var/run/stunnel) failed: No such file or directory
```

> Does it work?

Yes, it does work with `/proc` mounted, but I just don't seem to get the reasoning behind it...

**Comment by evverx** [comment]
> but I just don't seem to get the reasoning behind it

Well, `systemd-tmpfiles` runs something like `fd = open(path); chown(/proc/self/fd/$fd)`. This doesn't work if `/proc` doesn't exists.

Maybe, we should complain. Similar to `ps`
```
bash-4.3# ps
Error, do this: mount -t proc proc /proc
```

**Comment by floppym** [comment]
I'm wondering why it needs to do that /proc/self/fd hack at all...

There's a comment in the code reading:

```
        /* We open the file with O_PATH here, to make the operation
         * somewhat atomic. Also there's unfortunately no fchmodat()
         * with AT_SYMLINK_NOFOLLOW, hence we emulate it here via
         * O_PATH. */
```

However, according to man-pages-4.09, both fchownat and fchmodat do accept `AT_SYMLINK_NOFOLLOW` in the flags parameter.

**Comment by evverx** [comment]
@floppym , man page [says](https://github.com/mkerrisk/man-pages/blob/35deeb870300933e3ece9bbf96036be2e4afe2ad/man2/chmod.2#L222):
> AT_SYMLINK_NOFOLLOW
If pathname is a symbolic link, do not dereference it: instead operate on the link itself.  This flag **is not currently implemented**.

`glibc-2.24` contains
```c
int
fchmodat (int fd, const char *file, mode_t mode, int flag)
{
  if (flag & ~AT_SYMLINK_NOFOLLOW)
    return INLINE_SYSCALL_ERROR_RETURN_VALUE (EINVAL);
#ifndef __NR_lchmod             /* Linux so far has no lchmod syscall.  */
  if (flag & AT_SYMLINK_NOFOLLOW)
    return INLINE_SYSCALL_ERROR_RETURN_VALUE (ENOTSUP);
#endif

  return INLINE_SYSCALL (fchmodat, 3, fd, file, mode);
}
```

**Comment by floppym** [comment]
Ah, that certainly explains it.

**Comment by poettering** [comment]
so, there is no bug here afaics. Howerver the log message could use some improvement, and clarify that it is /proc that cannot be accessed...

Ultimately though: you called the tool in a broken environment. Our tools generally assume that /proc is accessible.

**Comment by poettering** [comment]
I have filed #4969 now that improves the error message a bit.
