### ISSUE TITLE
systemd-networkd attempts to start at shutdown, systemd does not accept dbus connection, shutdown hangs

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#4955]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

> Container shuts down successfully

### In case of bug report: Unexpected behaviour you saw

Container hangs after shutting down systemd-networkd

### In case of bug report: Steps to reproduce the problem

I have not tried to reproduce on a fresh container, but this happens on a current debian sid container having both systemd-networkd and ifupdown (networking.service) enabled. It appears something is doing netlink traffic that wakes networkd at shutdown. This breaks the shutdown process and the container is eventually killed due to timeout.

Some further investigations

1. Having `systemd-networkd.socket` `Conflicts=shutdown.target` and `Before=shutdown.target` seems to fix the issue. Or at the very least, it reduces the reactivation window enough for the problem to not show on my system.
2. Disabling either networkd or `networking.service` fixes the issue too.

I think the "fix" in 1 is good no matter what. But I think the issue runs deeper: the shutdown should not hang because of these issues. systemd should somehow (but I have no idea how) detect this, stop networkd and continue the shutdown process.

**Comment by fsateler** [comment]
Here is a debug log of the shutdown process.

[broken-shutdown.txt](https://github.com/systemd/systemd/files/671519/broken-shutdown.txt)


I don't see anything obviously wrong there...

**Comment by poettering** [comment]
Humm... something is issuing "systemctl daemon-reload" during shutdown? That looks very wrong...

**Comment by poettering** [comment]
Most likely this is caused by the daemon-reload is my educated guess. If you remove that, does it fix the issue?

**Comment by fsateler** [comment]
Hmmpf. I can no longer reproduce. Thus this bug is not very actionable anymore...

**Comment by sknsean** [comment]
I'm able to reproduce this consistently on a imx6ull:
$ mkdir /run/systemd/network/
$ vi /run/systemd/network/something.network
corrupt the file! make it look something like
```
[Match]                                                                                                                                                                                                                                                                                                                       
Name=eth*                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                           
[Net
```
$ systemctl restart systemd-networkd; systemctl start systemd-reboot

And systemd continues to service the watchdog :-(

https://gist.github.com/sknsean/8f7264da154d4f7764e73a1735f9b41d

**Comment by sknsean** [comment]
@poettering @keszybz care to take a look? :-)

**Comment by sknsean** [comment]
Another similar case:
https://gist.github.com/sknsean/06733ff88a2130ee674bf91824286ecb

A reboot timer, runs after 3h:
`
[Unit]
Description=Reboot after 3h uptime
ConditionPathExists=!/data/conf/reboot-timer-disable

[Timer]
OnBootSec=3h
Unit=reboot.target

[Install]
WantedBy=timers.target
`
at the same time our services is requesting ofono to restart this leads us to hang with almost all shutdown and umounted... and ofono started
Systemd is continuing to service the watchdog

**Comment by hundeboll** [comment]
I've reproduced the issue on latest master using QEMU with KVM disabled:

```shell
Arch Linux 5.1.16-arch1-1-ARCH (ttyS0)

archlinux login: root
Last login: Tue Jul  9 14:10:34 on ttyS0
root@archlinux ~ # systemctl --version
systemd 242 (242-1199-gd8c72e8)
+PAM +AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
root@archlinux ~ # cat start.sh               
#!/bin/bash

do_term() {
        echo waiting
        systemctl restart systemd-networkd
        sleep 10
        echo exiting
}
trap do_term SIGTERM

while sleep 1; do
        :
done
root@archlinux ~ # cat something.network
[Match]
Name=eth*

[Netwo
root@archlinux ~ # mkdir /run/systemd/network/
[shutdown-hang.journal.zip](https://github.com/systemd/systemd/files/3372909/shutdown-hang.journal.zip)


root@archlinux ~ # cp something.network /run/systemd/network
root@archlinux ~ # systemd-run /root/start.sh -p TimeoutStopSec=15
Running as unit: run-r1071cfe9368542b5bf7b701139183831.service
root@archlinux ~ # systemctl start systemd-reboot
         Stopping /root/start.sh -p TimeoutStopSec=15...
         Starting Generate shutdown-ramfs...
[  OK  ] Stopped target Remote Encrypted Volumes.
[  OK  ] Stopped target Host and Network Name Lookups.
         Stopping Session 1 of user root.
[  OK  ] Stopped target Timers.
[1]    341 terminated  systemctl start systemd-reboot
[  OK  ] Stopped Daily verification of password and group files.
[  OK  ] Stopped Daily Cleanup of Temporary Directories.
[  OK  ] Unset automount EFI System Partition Automount.
[  OK  ] Stopped target Graphical Interface.
[  OK  ] Stopped target Multi-User System.
[  OK  ] Stopped target Login Prompts.
         Stopping Serial Getty on ttyS0...
         Stopping Getty on tty1...
[  OK  ] Stopped target Containers.
[  OK  ] Stopped Daily rotation of log files.
[  OK  ] Stopped target System Time Synchronized.
[  OK  ] Stopped target System Time Set.
[  OK  ] Stopped Getty on tty1.
[  OK  ] Stopped Serial Getty on ttyS0.
[  OK  ] Stopped Session 1 of user root.
```

At which point it simply hangs.

I've attached the relevant journal file with systemd debugging enabled.

Let me know if there is anything else that would be useful to dig out.

**Comment by sknsean** [comment]
@poettering ping

**Comment by ssahani** [comment]
> I'm able to reproduce this consistently on a imx6ull:
> $ mkdir /run/systemd/network/
> $ vi /run/systemd/network/something.network
> corrupt the file! make it look something like
> 
> ```
> [Match]                                                                                                                                                                                                                                                                                                                       
> Name=eth*                                                                                                                                                                                                                                                                                                                     
>                                                                                                                                                                                                                                                                                                                            
> [Net
> ```
> 
> $ systemctl restart systemd-networkd; systemctl start systemd-reboot
> 
> And systemd continues to service the watchdog :-(
> 
> https://gist.github.com/sknsean/8f7264da154d4f7764e73a1735f9b41d
```
       Starting [0;1;39mNetwork Service[0m...
[  137.015154] systemd-networkd[263]: /run/systemd/network/something.network:3: Invalid section header '[Net'
[  137.093838] systemd-networkd[263]: /run/systemd/network/something.network:3: Failed to parse file: Bad message
[  137.114202] systemd-networkd[263]: Could not load configuration files: Bad message
[[0;1;31mFAILED[0m] Failed to start [0;1;39mNetwork Service[0m.

```

looking at you logs seems something not right in the conf. can you paste them.

**Comment by sknsean** [comment]
It’s already there, see the section where I create a corrupt file :)
The corrupt file is needed to trigger this race

**Comment by ssahani** [comment]
yeah I can reproduce 
```
/usr/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
/usr/lib/systemd/network/something.network:1: Invalid section header '[aaaaaaaaaMatc'
/usr/lib/systemd/network/something.network:1: Failed to parse file: Bad message
Could not load configuration files: Bad message
Bus bus-api-network: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freed
```

yes I can reproduce them but what you expect and why

**Comment by sknsean** [comment]
If you have a slow enough machine systemd will hang in the shutdown process as described by me & @hundeboll

Run:
$ systemctl restart systemd-networkd; systemctl start systemd-reboot

**Comment by ssahani** [comment]
will try to reproduce interesting how networkd failure affecting the systemd reboot and seems like any process failed to start  via systemctl will lead to this ?

**Comment by sknsean** [comment]
@poettering ping^2

**Comment by sverdlin** [comment]
I can reproduce this with v246.5. It looks like systemd-networkd.socket reacts on a network traffic and starts systemd-networkd.service again, which pulls half of the world back from the dead. Half of the dependencies fail, but system remain in this zombie state:
```
systemd-networkd.socket: Incoming traffic
systemd-networkd.service: Trying to enqueue job systemd-networkd.service/start/replace
Added job systemd-networkd.service/start to transaction.
Pulling in system.slice/start from systemd-networkd.service/start
Added job system.slice/start to transaction.
```
Full shutdown log with debug level:
[bad_shutdown.txt](https://github.com/systemd/systemd/files/6331767/bad_shutdown.txt)

**Comment by sverdlin** [comment]
#19348 well, boils down to the proposal of the bug reporter.

**Comment by sknsean** [comment]
Still possible to reproduce with @hundeboll script above :(
```
[root@archlinux arch]# uname -a
Linux archlinux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux
[root@archlinux arch]# systemctl --version
systemd 249 (249.4-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
[root@archlinux ~]# systemctl start systemd-reboot
         Stopping Session 1 of User arch...
[  OK  ] Removed slice Slice /system/modprobe.
[  OK  ] Stopped target Graphical Interface.
[  OK  ] Stopped target Multi-User System.
[  OK  ] Stopped target Login Prompts.
[  OK  ] Stopped target Containers.
[  OK  ] Stopped target Network is Online.
[  OK  ] Stopped target Host and Network Name Lookups.
[  OK  ] Stopped target Remote Encrypted Volumes.
[  OK  ] Stopped target Timer Units.
[  OK  ] Stopped Daily verification of password and group files.
[  OK  ] Stopped Daily Cleanup of Temporary Directories.
[  OK  ] Stopped target System Time Set.
[  OK  ] Closed Process Core Dump Socket.
         Stopping Getty on tty1...
         Starting Generate shutdown-ramfs...
         Stopping /root/start.sh -p TimeoutStopSec=15...
         Stopping Serial Getty on ttyS0...
         Stopping OpenSSH Daemon...
[  OK  ] Stopped Wait for Network to be Configured.
         Stopping Load/Save Random Seed...
[  OK  ] Stopped Getty on tty1.
[  OK  ] Stopped OpenSSH Daemon.
[  OK  ] Stopped Serial Getty on ttyS0.
[  OK  ] Stopped Load/Save Random Seed.
```
Hangs there ^

**Comment by yuwata** [comment]
So, at least this is not a issue in networkd (nor resolved). And also different from the original issue.

**Comment by yuwata** [comment]
@sknsean Could you open a new issue page with the above log and script?
