### ISSUE TITLE
systemctl status should point that there are other unit files with the same name

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#4956]
Hi,

When running `systemctl status foo` shouldn't the output point the user that there are also other unit files with the same "name" but other types (specifically thinking about .socket here but might also be .timer,...).

For example it might not be obvious if a .service is/can be socket activated or not.

Might also be interesting to show all the units if the "type" is not specified, ie user using foo instead of foo.service

**Comment by GyrosGeier** [comment]
Also, related units that do not necessarily have the same name. As it is now, I can add another listening socket to any daemon, and `systemctl` won't show it.

**Comment by mbiebl** [comment]
This is related to #4909

**Comment by dtardon** [comment]
`systemctl status` shows triggered and triggering units these days, like this:
```
systemctl status cups.socket
○ cups.socket - CUPS Scheduler
     Loaded: loaded (/usr/lib/systemd/system/cups.socket; enabled; preset: enabled)
     Active: inactive (dead) since Wed 2023-04-05 15:25:58 CEST; 59s ago
   Duration: 23h 34min 46.280s
   Triggers: ● cups.service
```
```
systemctl status cups.service
○ cups.service - CUPS Scheduler
     Loaded: loaded (/usr/lib/systemd/system/cups.service; enabled; preset: disabled)
     Active: inactive (dead) since Wed 2023-04-05 15:25:58 CEST; 2min 19s ago
   Duration: 23h 34min 22.640s
TriggeredBy: ○ cups.socket
             ○ cups.path
```
