### ISSUE TITLE
Clarify CAPABILITIES exec error

### ISSUE THREAD

**Issue by Hello71** [systemd/systemd#4959]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

### Used distribution

Gentoo/Arch

### In case of bug report: Expected behaviour you didn't see

"ProtectKernelModules is not valid in user service" or similar (not entirely sure what security provision is being violated)

### In case of bug report: Unexpected behaviour you saw

Failed at step CAPABILITIES spawning /usr/bin/mpd: Operation not permitted

(wtf does that mean)

### In case of bug report: Steps to reproduce the problem

start user service with ProtectKernelModules=yes

see mpd bug https://bugs.musicpd.org/view.php?id=4608

**Comment by keszybz** [comment]
After  70dd455 I see:
```
Mar 23 14:29:10 krowka systemd[1784]: Started capcheck.service.
Mar 23 14:29:10 krowka systemd[12599]: capcheck.service: Failed to drop capabilities: Operation not permitted
Mar 23 14:29:10 krowka systemd[12599]: capcheck.service: Failed at step CAPABILITIES spawning /bin/true: Operation not permitted
Mar 23 14:29:10 krowka systemd[1784]: capcheck.service: Main process exited, code=exited, status=218/CAPABILITIES
Mar 23 14:29:10 krowka systemd[1784]: capcheck.service: Failed with result 'exit-code'.
```
I think that's clear enough.

**Comment by mengtanhzc** [comment]
@jzacsh Thank you!  I just set the `CapabilityBoundingSet=CAP_NET_ADMIN` in a `--user` file.
```
[Unit]
        Description=print
[Service]
        CapabilityBoundingSet=CAP_NET_ADMIN
        Type=forking
        ExecStart=/hack/test
[Install]
        WantedBy=multi-user.target
```

And I get the error message when I start this service via systemctl --user:
```
print.service: Failed to drop capabilities: Operation not permitted
print.service: Failed at step CAPABILITIES spawning /hack/test: Operation not permitted
print.service: Control process exited, code=exited, status=218/CAPABILITIES
print.service: Failed with result 'exit-code'.
```
But I don't understand why it failed, are there any implied restrictions? Can you help me with this error? Thanks a lot!

**Comment by carmenbianca** [comment]
For anyone who got here via @jzacsh 's comment regarding borgmatic. Given the [current systemd sample service](https://projects.torsion.org/borgmatic-collective/borgmatic/src/commit/cd234b689d9577a20ca4eec4b2c7a391433ed448/sample/systemd/borgmatic.service), comment out:

- `PrivateDevices`
- `ProtectClock`
- `ProtectControlGroups`
- `ProtectKernelLogs`
- `ProtectKernelModules`
- `ProtectKernelTunables`
- `CapabilityBoundingSet`
