### ISSUE TITLE
[RFE] [Documentation] Recommend systemd.mount instead of fstab mounts

### ISSUE THREAD

**Issue by fpqc** [systemd/systemd#4961]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch

### Submission:

The systemd documentation still recommends against doing with systemd mount units instead of fstab.  This seems like a sort of pointless warning nowadays, since systemd.mount units are stable and work very well (have been using them for the past year or so with fewer problems than fstab).  I was talking about it in the Archlinux IRC channel, and they said the only reason Arch doesn't recommend direct systemd.mount units is that upstream (systemd) documentation still recommends against it.

Could we have an update to the documentation to recommend systemd mounts, or at least not to prefer fstab mounts?

**Comment by poettering** [comment]
Well, for most cases /etc/fstab is actually good enough, and it's certainly a simpler format, and terser.

Using .mount units is fine, and you can use either, but I doubt we should really get people off using /etc/fstab, as simplicity I think is actually a benefit...

Moreover, there are some bits we currently do not expose in mount units. Specifically, in /etc/fstab you can configure mount options for /proc, /sys and /dev, and "systemd-remount-fs.service" will apply them early at boot (by remounting the kernel mounts). It's the official way to change mount options for those three dirs. This cannot be done with .mount units, as we don't expose any mount units for API VFS including these three mounts...

Hence, I am not really convinced we should push people towards using .mount exclusively. I think plurality is fine here: use one, use the other, whatever floats your boat. We can certianly drop the "In general, configuring mount points through /etc/fstab is the preferred approach. " sentence, but I am not convinced we should replace it by a different one suggesting that native .mount units are the perfect way to go now...

I hope this make sense?

**Comment by fpqc** [comment]
Sounds good!

**Comment by poettering** [comment]
Fix waiting in #4968.

**Comment by keszybz** [comment]
See https://github.com/systemd/systemd/pull/4968#issuecomment-271984876.
