### ISSUE TITLE
systemd-build-scan does not work

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#4964]
~~https://scan.coverity.com/projects/350 Last Analyzed Apr 17, 2016~~
Fixed: https://github.com/systemd/systemd/issues/4964#issuecomment-270601825

http://systemd.github.io/systemd-build-scan/ (Mon Dec 5 04:12:32 2016)
https://github.com/systemd/systemd-build-scan Latest commit ad9ee54  18 days ago

**Comment by poettering** [comment]
thanks for the pointer. I logged into coverity now, and have been watching it for a while today. I constantly says that either 17 or 18 other tasks are queued before systemd will be analyzed. It keeps going up and down all the time... I figure coverity is really broken on their side...

**Comment by evverx** [comment]
@poettering , thanks

> I figure coverity is really broken on their side

Did you contact `scan-admin@coverity.com`?

**Comment by poettering** [comment]
no, not yet. wanted to monitor this for a few more days before i contact them

**Comment by evverx** [comment]
OK, makes sense, thanks

Not sure about http://systemd.github.io/systemd-build-scan/ ? Does it matter? Or nobody cares?

**Comment by poettering** [comment]
i think it would be good to make that work again, but i don't remember the details and who set it up...

**Comment by phomes** [comment]
@zonque set it up

**Comment by poettering** [comment]
I contacted coverity a few days ago, and they fixed it now. It's working again since yesterday!

**Comment by evverx** [comment]
Something went wrong :-)

![screen shot 2017-03-02 at 04 05 22](https://cloud.githubusercontent.com/assets/10195800/23488416/83077912-fefd-11e6-8f71-70efd83ffdcd.png)

**Comment by evverx** [comment]
I think this issue can be closed. It would be great to [get `coverity` worked](https://github.com/systemd/systemd/issues/5577) though.
