### ISSUE TITLE
pid1 crashes with assert at ../src/core/manager.c:1192 (manager_add_job(unit = NULL))

### ISSUE THREAD

**Issue by kaysievers** [systemd/systemd#498]
Jul 06 20:57:27 ank systemd-logind[555]: Power key pressed.
Jul 06 20:57:27 ank NetworkManager[546]: <info>  sleep requested (sleeping: no  enabled: yes)
Jul 06 20:57:27 ank NetworkManager[546]: <info>  sleeping...
Jul 06 20:57:27 ank NetworkManager[546]: <info>  (wwp0s20u4): device state change: disconnected -> unmanaged (reason 'sleeping') [30 10 37]
Jul 06 20:57:27 ank NetworkManager[546]: <info>  (wlp3s0): device state change: activated -> unmanaged (reason 'sleeping') [100 10 37]
Jul 06 20:57:27 ank systemd-networkd[560]: wwp0s20u4: Lost carrier
Jul 06 20:57:27 ank systemd-timesyncd[529]: Network configuration changed, trying to establish connection.
Jul 06 20:57:27 ank NetworkManager[546]: <info>  (wlp3s0): canceled DHCP transaction, DHCP client pid 1183
Jul 06 20:57:27 ank NetworkManager[546]: <info>  (wlp3s0): DHCPv4 state changed bound -> done
Jul 06 20:57:27 ank NetworkManager[546]: <info>  (wlp3s0): canceled DHCP transaction
Jul 06 20:57:27 ank kernel: wlp3s0: deauthenticating from bc:05:43:9e:7d:c3 by local choice (Reason: 3=DEAUTH_LEAVING)
Jul 06 20:57:27 ank avahi-daemon[559]: Withdrawing address record for 192.168.178.139 on wlp3s0.
Jul 06 20:57:27 ank avahi-daemon[559]: Leaving mDNS multicast group on interface wlp3s0.IPv4 with address 192.168.178.139.
Jul 06 20:57:27 ank avahi-daemon[559]: Interface wlp3s0.IPv4 no longer relevant for mDNS.
Jul 06 20:57:27 ank avahi-daemon[559]: Withdrawing address record for fd00::eab1:fcff:fe3d:fb5d on wlp3s0.
Jul 06 20:57:27 ank NetworkManager[546]: <info>  NetworkManager state is now ASLEEP
Jul 06 20:57:27 ank systemd-networkd[560]: wlp3s0: Lost carrier
Jul 06 20:57:27 ank systemd-timesyncd[529]: No network connectivity, watching for changes.
Jul 06 20:57:27 ank kernel: cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
Jul 06 20:57:27 ank systemd[1]: Assertion 'unit' failed at ../src/core/manager.c:1192, function manager_add_job(). Aborting.
Jul 06 20:57:27 ank NetworkManager[546]: <warn>  Failed to GDBus.Error:fi.w1.wpa_supplicant1.NotConnected: This interface is not connected: disconnect.
Jul 06 20:57:27 ank NetworkManager[546]: <info>  (wwp0s20u4): link disconnected
Jul 06 20:57:27 ank kernel: systemd-coredum[3804]: segfault at 0 ip 000055fb2928758b sp 00007ffc363d1800 error 6 in systemd-coredump[55fb2925d000+6c000]
Jul 06 20:57:27 ank systemd[1]: Caught <ABRT>, dumped core as pid 3803.
Jul 06 20:57:27 ank systemd[1]: Freezing execution.
Jul 06 20:57:27 ank evolution-addressbook-factory[1018]: g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
Jul 06 20:57:27 ank rtkit-daemon[551]: Exiting cleanly.
Jul 06 20:57:27 ank systemd-bus-proxyd[565]: Failed to start bus client: No such file or directory

**Comment by kaysievers** [comment]
systemd-coredump no longer crashes:
  https://github.com/systemd/systemd/commit/de8763b6d23963e14787556de159d813e863043f

**Comment by poettering** [comment]
I don't think we can do anything about this without backtrace. I will close this now. Please reopen if this happens again and we get a useful backtrace with the now working coredumping logic.
