### ISSUE TITLE
_nss_systemd_getpwnam_r should not return EINVAL for invalid usernames

### ISSUE THREAD

**Issue by johnfawcett** [systemd/systemd#4983]
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
Archlinux 2016.12.01

### In case of bug report: Expected behaviour you didn't see

getpwnam_r system call should return 0 if the username is not found

### In case of bug report: Unexpected behaviour you saw

getpwnam_r system call returns EINVAL when the username does not meet the requirements defined in basic/user-util.c function valid_user_group_name. This is not compliant with POSIX standards, see http://pubs.opengroup.org/onlinepubs/9699919799/

### In case of bug report: Steps to reproduce the problem

You may compile the getpwnam_r test program shown at https://linux.die.net/man/3/getpwnam_r
When running this program with a username such as x.y it produces EINVAL instead of 0.

**Comment by benjarobin** [comment]
The POSIX standard said that : "If an error has occurred, an error number shall be returned to indicate the error.". The example (in the man page) that you used handle it perfectly. I do not see any violation of the standard. This is clearly an error to pass an invalid formatted username

**Comment by johnfawcett** [comment]
Just before that the standard states: the getpwnam_r() function shall return zero on success or if the requested entry was not found and no error has occurred. 

Programs calling this system library will expect to receive 0 if the user does not exist. They will not expect to receive 0 or EINVAL. While that extension is arguable useful, it is not documented and therefore calling programs are not going to implement it, particularly when up to now this distinction has not been provided by other nss mechanisms which systemd nss functions are replacing.

How should calling programs know what exactly is acceptable and not acceptable as a local user name? Even the systemd nss code is not consistent when answering this question:

For example on the archlinux platform _SC_LOGIN_NAME_MAX is 256 so local names up to 255 in length should be acceptable. However, the systemd nss library returns EINVAL for these names.

Another example is that on archlinux, local usernames cannot accept upper case characters, but systemd nss library supplies 0 return code for those.

Thanks for looking into this.

**Comment by poettering** [comment]
So, I don't see how we'd conflict with POSIX regarding the error codes here. But I also would say that it isn't our business to refuse broken user names, but should be done by libc. Hence I figure we should just filter them out early, and indeed say "don't know" rather than "invalid" in this case.

(does archlinux increase UT_NAMESIZE? i doubt so, hence using names longer than that is problematic, as utmp will be incomplete)

**Comment by johnfawcett** [comment]
Thanks, that will certainly stop programs that use getpwnam_r from unexpectedly changing behaviour when systemd is put into /etc/nsswitch.conf instead of files.

For archlinux (latest distro at least) UT_NAMESIZE is 32.

Would you change the title of the issue to "_nss_systemd_getpwnam_r should not return EINVAL for invalid usernames"
The ommission of "not" makes it seem that the issue is requesting the actual behaviour.

thanks

**Comment by poettering** [comment]
oh, sorry, that was a typo.
