### ISSUE TITLE
Cannot indicate to EFI to boot into setup mode: No such file or directory

### ISSUE THREAD

**Issue by neheb** [systemd/systemd#499]
I get this error by running 'systemctl --firmware-setup reboot'

On Arch Linux with kernel 4.0.7 

Not sure if the error is in systemd or the kernel. FWIW this works in Windows :.

edit: the error in the title is obtained when running the command as an unprivileged user. when ran as root the error becomes

'Cannot indicate to EFI to boot into setup mode: Unknown object '/org/freedesktop/login1'.'

**Comment by kaysievers** [comment]
That works just fine here. Unprivileged, it asks for authorization and then reboots into the firmware menu.

**Comment by poettering** [comment]
@neheb do you have booted the system and kernel in EFI mode?

**Comment by neheb** [comment]
@poettering currently the system is booted in "Ultra-fast" mode. No keyboard drivers loaded means I have to use the OS.

**Comment by poettering** [comment]
@neheb that's not the question I asked. Are you booting in MBR or in EFI mode?

What does "ls -al /sys/firmware/efi/efivar" show?

**Comment by neheb** [comment]
It's in EFI with systemd-boot. The full output shown below. 

-rw-r--r-- 1 root root   12 Jul  6 12:37 AcpiAslPtr-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root    8 Jul  6 12:37 AcpiGlobalVariable-af9ffd67-ec10-488a-9dfc-6cbf5ee22c2e
-rw-r--r-- 1 root root   12 Jul  6 12:37 AcpiGlobalVariable-c020489e-6db2-4ef2-9aa5-ca06fc11d36a
-rw-r--r-- 1 root root   37 Jul  6 12:37 AMITSESetup-c811fa38-42c8-4579-a9bb-60e94eddfb34
-rw-r--r-- 1 root root   32 Jul  6 12:37 ASRockTimerSmiData-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root    5 Jul  6 12:37 ASR_TIMERSMI-2781600e-9df9-4ef8-a5a4-66501ae55c41
-rw-r--r-- 1 root root    7 Jul  6 12:37 ASR_USER_DEF_TSE-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root    5 Jul  6 12:37 ASR_USER_DEF_VER-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root  164 Jul  6 12:37 Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    6 Jul  6 12:37 BootCurrent-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   40 Jul  6 12:37 Boot_Dev_name-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    5 Jul  6 12:37 Boot_Last_Device-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root    8 Jul  6 12:37 BootOptionSupport-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    6 Jul  6 12:37 BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    5 Jul  6 12:37 CaseOpenVsSetup-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   88 Jul  6 12:37 ConIn-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   48 Jul  6 12:37 ConOut-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   48 Jul  6 12:37 ConOutDev-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    5 Jul  6 12:37 ConsoleLock-368cda0d-cf31-4b9b-8cf6-e7d1bfff157e
-rw-r--r-- 1 root root   37 Jul  6 12:37 CPUS3APICID-1456cc6e-22ac-5289-33ba-2e13bbdabaee
-rw-r--r-- 1 root root    6 Jul  6 12:37 DefaultBootOrder-45cf35f6-0d6e-4d04-856a-0370a5b16f53
-rw-r--r-- 1 root root 1284 Jul  6 12:37 DmiArray-4b3082a3-80c6-4d7e-9cd0-583917265df1
-rw-r--r-- 1 root root   20 Jul  6 12:37 DmiVar0200020700-4b3082a3-80c6-4d7e-9cd0-583917265df1
-rw-r--r-- 1 root root   48 Jul  6 12:37 ErrOut-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    8 Jul  6 12:37 EzConfigData-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root  152 Jul  6 12:37 FastBootOption-b540a530-6978-4da7-91cb-7207d764d262
-rw-r--r-- 1 root root    6 Jul  6 12:37 FB_SIO_DEV_STATUS_VAR-b540a530-6978-4da7-91cb-7207d764d262
-rw-r--r-- 1 root root    8 Jul  6 12:37 FPDT_Variable-01368881-c4ad-4b1d-b631-d57a8ec8db6b
-rw-r--r-- 1 root root    5 Jul  6 12:37 GoodNightLed-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   32 Jul  6 12:37 HddBootDev-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   12 Jul  6 12:37 HiiDB-1b838190-4625-4ead-abc9-cd5e6af18fe0
-rw-r--r-- 1 root root   12 Jul  6 12:37 HobRomImage-dde1bc72-d45e-4209-ab85-14462d2f5074
-rw-r--r-- 1 root root   78 Jul  6 12:37 IccAdvancedSetupDataVar-7b77fb8b-1e0d-4d7e-953f-3980a261e077
-rw-r--r-- 1 root root    7 Jul  6 12:37 Lang-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   28 Jul  6 12:37 LangCodes-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   14 Jul  6 12:37 LastBoot-b540a530-6978-4da7-91cb-7207d764d262
-rw-r--r-- 1 root root   78 Jul  6 12:37 LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   14 Jul  6 12:37 LoaderEntrySelected-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   56 Jul  6 12:37 LoaderFirmwareInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   24 Jul  6 12:37 LoaderFirmwareType-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   70 Jul  6 12:37 LoaderImageIdentifier-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   38 Jul  6 12:37 LoaderInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   20 Jul  6 12:37 LoaderTimeExecUSec-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root   20 Jul  6 12:37 LoaderTimeInitUSec-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
-rw-r--r-- 1 root root    5 Jul  6 12:37 LoadSetupDefault-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   30 Jul  6 12:37 MeBiosExtensionSetup-1bad711c-d451-4241-b1f3-8537812e0c70
-rw-r--r-- 1 root root    8 Jul  6 12:37 MemCeil.-40312829-7891-4abd-b200-0c541b061939
-rw-r--r-- 1 root root   68 Jul  6 12:37 MemoryTypeInformation-4c19049f-4137-4dd3-9c10-8b97a83ffdfa
-rw-r--r-- 1 root root    8 Jul  6 12:37 MonotonicCounter-01368881-c4ad-4b1d-b631-d57a8ec8db6b
-rw-r--r-- 1 root root 3990 Jul  6 12:37 MrcS3Resume-87f22dcb-7304-4105-bb7c-317143ccc23b
-rw-r--r-- 1 root root   24 Jul  6 12:37 NBPlatformData-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root  494 Jul  6 12:37 NetConfigData-8f132913-6907-4192-a227-6cbcd7a50e6c
-rw-r--r-- 1 root root    8 Jul  6 12:37 NetworkStackVar-d1405d16-7afc-4695-bb12-41459d3695a2
-rw-r--r-- 1 root root    6 Jul  6 12:37 NumOfPState-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   28 Jul  6 12:37 OA3MSDMvariable-01368881-c4ad-4b1d-b631-d57a8ec8db6b
-rw-r--r-- 1 root root   12 Jul  6 12:37 OsIndicationsSupported-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    8 Jul  6 12:37 PchInit-e6c2f70a-b604-4877-85ba-deec89e117eb
-rw-r--r-- 1 root root   12 Jul  6 12:37 PchInitPei-a31b27a4-cae6-48ff-8c5a-294221e6f389
-rw-r--r-- 1 root root   20 Jul  6 12:37 PchS3Peim-e6c2f70a-b604-4877-85ba-deec89e117eb
-rw-r--r-- 1 root root  264 Jul  6 12:37 PetAlertCfg-d54f49f6-0dd4-4276-b09c-dfe1fd8085f0
-rw-r--r-- 1 root root   10 Jul  6 12:37 PlatformLang-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   54 Jul  6 12:37 PlatformLangCodes-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    7 Jul  6 12:37 PNP0400_0_NV-560bf58a-1e0d-4d7e-953f-2980a261e031
-rw-r--r-- 1 root root    7 Jul  6 12:37 PNP0501_0_NV-560bf58a-1e0d-4d7e-953f-2980a261e031
-rw-r--r-- 1 root root    7 Jul  6 12:37 PNP0501_1_NV-560bf58a-1e0d-4d7e-953f-2980a261e031
-rw-r--r-- 1 root root    7 Jul  6 12:37 PNP0510_0_NV-560bf58a-1e0d-4d7e-953f-2980a261e031
-rw-r--r-- 1 root root    7 Jul  6 12:37 PNP0604_0_NV-560bf58a-1e0d-4d7e-953f-2980a261e031
-rw-r--r-- 1 root root   68 Jul  6 12:37 PreviousMemoryTypeInformation-4c19049f-4137-4dd3-9c10-8b97a83ffdfa
-rw-r--r-- 1 root root    5 Jul  6 12:37 Q_ASR_QUICKON-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   12 Jul  6 12:37 S3SS-4bafc2b4-02dc-4104-b236-d6f1b98d9e84
-rw-r--r-- 1 root root    8 Jul  6 12:37 SbAslBufferPtrVar-01f33c25-764d-43ea-aeea-6b5a41f3f3e8
-rw-r--r-- 1 root root    5 Jul  6 12:37 SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    5 Jul  6 12:37 SetupAmtFeatures-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root 1116 Jul  6 12:37 Setup-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root    5 Jul  6 12:37 SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   20 Jul  6 12:37 SetupPlatformData-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   84 Jul  6 12:37 SignatureSupport-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root   86 Jul  6 12:37 StageChk-8f132913-6907-4192-a227-6cbcd7a50e6c
-rw-r--r-- 1 root root 2271 Jul  6 12:37 StdDefaults-4599d26f-1a11-49b8-b91f-858745cff824
-rw-r--r-- 1 root root    5 Jul  6 12:37 TcgInternalSyncFlag-f3ed95df-828e-41c7-bca0-16c41965a634
-rw-r--r-- 1 root root    5 Jul  6 12:37 TdtAdvancedSetupDataVar-7b77fb8b-1e0d-4d7e-953f-3980a261e076
-rw-r--r-- 1 root root    6 Jul  6 12:37 Timeout-8be4df61-93ca-11d2-aa0d-00e098032b8c
-rw-r--r-- 1 root root    6 Jul  6 12:37 UsbMassDevNum-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   20 Jul  6 12:37 UsbMassDevValid-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root   12 Jul  6 12:37 USB_POINT-c811fa38-42c8-4579-a9bb-60e94eddfb34
-rw-r--r-- 1 root root   37 Jul  6 12:37 UsbSupport-ec87d643-eba4-4bb5-a1e5-3f3e36b20da9
-rw-r--r-- 1 root root    5 Jul  6 12:37 WdtPersistentData-78ce2354-cfbc-4643-aeba-07a27fa892bf
-rw-r--r-- 1 root root   68 Jul  6 12:37 WriteOnceStatus-4b3082a3-80c6-4d7e-9cd0-583917265df1

**Comment by zonque** [comment]
`Cannot indicate to EFI to boot into setup mode: Unknown object '/org/freedesktop/login1'` seems to be the culprit. What's the output of `busctl` and `systemctl status systemd-logind.service`?

**Comment by neheb** [comment]
the latter indicated that it is active and "Processing Requests". The former's output is here: http://pastebin.com/zMJattmr

**Comment by poettering** [comment]
Hmm, that error you got suggests that logind and loginctl might not be compatible? is it possible you have a mix of an old systemd version and a new loginctl tool running, or vice versa?

Can you run "busctl tree org.freedesktop.login1", and paste the output here?

**Comment by neheb** [comment]
```
└─/org/freedesktop/login1
  ├─/org/freedesktop/login1/seat
  │ ├─/org/freedesktop/login1/seat/seat0
  │ └─/org/freedesktop/login1/seat/self
  ├─/org/freedesktop/login1/session
  │ ├─/org/freedesktop/login1/session/c4
  │ ├─/org/freedesktop/login1/session/c5
  │ └─/org/freedesktop/login1/session/self
  └─/org/freedesktop/login1/user
    ├─/org/freedesktop/login1/user/_1000
    ├─/org/freedesktop/login1/user/_120
    └─/org/freedesktop/login1/user/self
```

this installation started with systemd 219 and then upgraded to 221.

edit: scratch that, it's always been 221. 219 didn't come with systemd-boot.

**Comment by poettering** [comment]
hmm, that output looks fine. Can you also paste "busctl introspect org.freedesktop.login1 /org/freedesktop/login1"?

**Comment by neheb** [comment]
No such file or directory

**Comment by poettering** [comment]
That is seriously weird...

What happens if you do "busctl call org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.DBus.Introspectable Introspect"? Does this fail, or give you some XML output?

If it gives you the XML output, does it mention the strings "CanRebootToFirmwareSetup" and "SetRebootToFirmwareSetup"?

If this provides you with XML output, could you please run "strace -o /tmp/log -s500 -p $PID" for the logind PID, while you issue the "busctl introspect" line above? 

My educated guess tells me that for some reason logind cannot read the firmware property and incorrectly propagates that to the client side. Specifically, property_get_reboot_to_firmware_setup() is borked...

**Comment by neheb** [comment]
some relevant XML output:

http://pastebin.com/4pVTd4Js

the strace output: http://pastebin.com/CCGm5W11

**Comment by poettering** [comment]
XML output looks fine.

The strace output looks incomplete? Are you sure that's all that was generated while you ran "busctl introspect org.freedesktop.login1 /org/freedesktop/login1" from another window?

**Comment by poettering** [comment]
any chance you can gdb attach to logind, then set a breakpoint on property_get_reboot_to_firmware_setup and continue execution. Then, issue the introspect command from another terminal. It should break in that function, now step through it, see efi_get_reboot_to_firmware() inside it fails, and with what error. Might be useful to step through that function, too.

**Comment by neheb** [comment]
Oh I ran the XML command. my bad. Attempt 2:

http://pastebin.com/7XAM6ifq

**Comment by poettering** [comment]
Any chance you can repaste this without all lines chopped off at the right?

**Comment by neheb** [comment]
hmm i tried gdb but i just managed to crash logind which also kills gdm.

also here: http://pastebin.com/g8LwdKGK didn't realize it was chopped.

edit: there is no OsIndications file as stated in the strace. However I do have an OsIndicationsSupported file.

**Comment by poettering** [comment]
Please test if #559 fixes your issue!

**Comment by neheb** [comment]
#559 fixes my issue. I can get into the setup screen again. Thanks!
