### ISSUE TITLE
Deleted units can no longer be managed

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#4995]
It seems that when a template unit is physically deleted, its running instances can no longer be properly inspected nor can it be disabled.

### Seen with

systemd 232-6 (Arch Linux)

### In case of bug report: Expected behaviour you didn't see

In older versions, after removing `foo@.service` and calling `daemon-reload`:

 * `systemctl status foo@bar` would show running unit information and the process list;
 * `systemctl disable foo@bar` would forcefully remove all .wants/ symlinks for that unit.

### In case of bug report: Unexpected behaviour you saw

In the current version:

 * `systemctl status foo@bar` shows basic information but fails to show the process list;
 * `systemctl disable foo@bar` refuses to do anything.

```
$ systemctl status openvpn@test
● openvpn@test.service
   Loaded: not-found (Reason: No such file or directory)
   Active: active (running) since Mon 2016-11-07 18:03:08 EET; 1 months 20 days ago
 Main PID: 30992 (openvpn)
   CGroup: /system.slice/system-openvpn.slice/openvpn@test.service
Failed to dump process list, ignoring: Unit openvpn@test.service not found.
```

### In case of bug report: Steps to reproduce the problem

```
cat > /etc/systemd/system/test@.service <<EOF
[Service]
ExecStart=/bin/sleep inf

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload

systemctl enable test@foo test@bar
systemctl start test@foo

rm /etc/systemd/system/test@.service
systemctl daemon-reload

systemctl status test@foo
systemctl stop test@foo
systemctl disable test@foo test@bar
```

**Comment by poettering** [comment]
These are actually two distinct bugs. Both fixed in #5303.
