### ISSUE TITLE
bridge interface can not get ipv6 address.

### ISSUE THREAD

**Issue by KalelCooper** [systemd/systemd#4996]
systemd 232
Without using bridge, ipv6 address can be assigned.
With using bridge, ipv6 address can not be assigned.

configuration files: 
```
# /etc/systemd/network/br0.netdev
[NetDev]
Kind=bridge
Name=br0
MACAddress=32:12:54:30:81:99
```
```
# /etc/systemd/network/en0.network
[Match]
Name=en*

[Network]
Bridge=br0
```
```
# /etc/systemd/network/br0.network
[Match]
Name=br0

[Network]
DHCP=yes
```

Thanks

**Comment by ssahani** [comment]
Please take a look . https://github.com/systemd/systemd/issues/2572

**Comment by yuwata** [comment]
Is this still relevant with a recent release? If so, please provide debugging logs of networkd, which can be generated by creating the following drop-in config with `sudo systemctl edit systemd-networkd.service`:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by poettering** [comment]
Let's close due to lack of response.
