### ISSUE TITLE
RouteMetric for IPv6 Stateless Autoconfiguration

### ISSUE THREAD

**Issue by mweinelt** [systemd/systemd#5002]
### Submission type
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with
> systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution
> Archlinux

### Description

Routes that are received by DHCP have RouteMetric from the DHCP block set. 
Routes that are received by router advertisments and configured through stateless autoconfiguration currently cannot have their metric set through systemd-networkd.

A very popular metrics setup is to prefer wired over wireless connectivity, and this is achievable for IPv4, but not for IPv6 (through radv, I didn't check for DHCPv6).

/etc/systemd/network/20-en0.network
```
[Match]
Name=en0

[Network]
DHCP=ipv4

[DHCP]
RouteMetric=512
```

```
# ip -6 r
fe80::/64 dev wl0 proto kernel metric 256  pref medium
fe80::/64 dev en0 proto kernel metric 256  pref medium
default via fe80::de9f:dbff:fe80:1e8 dev wl0 proto ra metric 1024  pref medium
default via fe80::de9f:dbff:fe80:1e8 dev en0 proto ra metric 1024  pref medium
# ip -4 r
172.23.97.0/24 dev wl0 proto kernel scope link src 172.23.97.52 
172.23.97.0/24 dev en0 proto kernel scope link src 172.23.97.31 
default via 172.23.97.254 dev en0 proto dhcp src 172.23.97.31 metric 512 
default via 172.23.97.254 dev wl0 proto dhcp src 172.23.97.52 metric 1024 
```

While on IPv4 the route over the wired connection is prefered, but on IPv6 both are equal.

**Comment by Gigadoc2** [comment]
Sorry to necro this, but how is this setting used? `RouteMetric` is not a valid key for `IPv6AcceptRA`, it seems the metric for IPv6 routes is taken from the DHCPv4 section?
