### ISSUE TITLE
systemctl enable results in two polkit prompts (one for enable, one for daemon-reload)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5013]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian

### In case of bug report: Expected behaviour you didn't see

Running ```systemctl enable foo``` should result in a single polkit prompt

### In case of bug report: Unexpected behaviour you saw

Running ```systemctl enable foo``` results in one polkit prompt for the actual enable and afterwards a polkit prompt for daemon-reload.

### In case of bug report: Steps to reproduce the problem

Run ```systemctl enable``` or ```systemctl disable``` as unprivileged user

**Comment by mbiebl** [comment]
Related #4124

**Comment by poettering** [comment]
i figure we could use the imply stanza of polkit so that authenticting org.freedesktop.systemd1.manage-unit-files also implies org.freedesktop.systemd1.reload-daemon...

**Comment by electricbrass** [comment]
On Raspberry Pi OS with systemd v252, I still have to authenticate twice.
