### ISSUE TITLE
systemd crashes on daemon-reexec if /run is full

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5016]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian
This was originally reported as 
http://bugs.debian.org/850074

### In case of bug report: Expected behaviour you didn't see

```systemctl daemon-reexec``` failing with a clear error message and systemd not aborting when /run is full

### In case of bug report: Unexpected behaviour you saw

```systemctl daemon-reexec``` on a system with a full /run leads to a crash of systemd

### In case of bug report: Steps to reproduce the problem

```
# cat /dev/zero > /run/eatspace
cat: write error: No space left on device
# systemctl daemon-reexec
Broadcast message from systemd-journald@kenaz (Tue 2017-01-03 16:16:42 EST):

systemd[1]: Freezing execution.


Message from syslogd@kenaz at Jan  3 16:16:42 ...
 systemd[1]: Freezing execution.
```

**Comment by mbiebl** [comment]
The log contains
```
Jan  3 13:59:01 kenaz systemd[1]: Failed to serialize state: Input/output error
Jan  3 13:59:01 kenaz systemd[1]: Freezing execution.
```
When /run is full, a "daemon-reload" also fails with a rather unspecific error message
```
Jan  3 13:59:01 kenaz systemd[1]: Reloading.
Jan  3 13:59:01 kenaz systemd[1]: Failed to reload: Input/output error
```

**Comment by poettering** [comment]
I figure we could remove this issue by moving this over to memfd...

**Comment by poettering** [comment]
(But let's not kid ourselves: /run being full will necessarily mean a DoS, there's no way around that, as we use that for communication primitives and a lot of other stuff)

**Comment by vcaputo** [comment]
It would be reasonable to refuse attempting /run-dependant operations if it's full (or very nearly full) though, which leaves the user in a much better position than
```
Jan  3 13:59:01 kenaz systemd[1]: Freezing execution.
```

**Comment by poettering** [comment]
@vcaputo yeah, indeed we could add a small safety check that indeed refuses a reexec or reload if /run is overly full. good point.

**Comment by poettering** [comment]
Fix waiting in #5219. Please have a look

**Comment by CHENZENGHU** [comment]
@poettering Why is the spaced needed for systemd's reload/reexec is calculated as 16M?

**Comment by poettering** [comment]
@CHENZENGHU this is not a support forum, please direct questions like yours to the systemd-devel mailing list.

(Shirt answer though: it's a "safety buffer", see commit msg of the fix. It's set to 16M because it has to be set to something, and it sounded like a reasonably value, and so far we got no feedback to the contrary)
