### ISSUE TITLE
journald does not handle a full partition gracefully

### ISSUE THREAD

**Issue by zackw** [systemd/systemd#5017]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

231, 232

### Used distribution

Debian unstable

### In case of bug report: Unexpected behaviour you saw

If the filesystem partition to which journald is writing logs is full, journald will go into an infinite loop broadcasting log messages about how it can't save log messages.  It should instead broadcast *one* such log message and then silently stop trying to write logs to disk.

**Comment by mbiebl** [comment]
#2339 looks related

**Comment by poettering** [comment]
Duplicate of #2339.
