### ISSUE TITLE
journald doesn't rotate logs when Storage=auto and /var/log/journal doesn't exist

### ISSUE THREAD

**Issue by zackw** [systemd/systemd#5018]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

### Used distribution

Debian unstable

### In case of bug report: Unexpected behaviour you saw

The default journald configuration for Debian unstable is `Storage=auto` without `/var/log/journal`, thus journal-format logs are written to `/run/log/journal`.  That's fine.  What's not fine is that, under these conditions, the logs are never rotated, so eventually `/run` will be completely full of log files.  Many system components are not prepared to handle a full `/run` — see for instance issue #5016 and issue #5017.

### In case of bug report: Steps to reproduce the problem

 * Install Debian unstable on a scratch computer.
 * Check that the default configuration is still the same: `Storage=auto`, `/var/log/journal` does not exist, and `/run` is an 128MB ramdisk.
 * Ensure `cron` is installed.
 * Define a user (not root) cron job that runs once a minute and does nothing.
 * Leave the computer running for approximately one week.
 * Files in `/run/log/journal` will have consumed all available space on the partition.

The cron job is just a straightforward way of generating lots and lots and lots of log entries reasonably quickly.

**Comment by poettering** [comment]
Well, we actually have two sets of rotation parameters to cover for /run/log/journal and /var/log/journal seperately. That's what is configured via:

```
RuntimeMaxUse=…
RuntimeKeepFree=…
RuntimeMaxFileSize=…
RuntimeMaxFiles=…
```

independently of:

```
SystemMaxUse=…
SystemKeepFree=…
SystemMaxFileSize=…
SystemMaxFiles=…
```

configured in /etc/systemd/journald.conf.

What are the value you have set for these four RuntimeXYZ= settings on your system?

Note that the effective values chosen are also logged early on, when journald initializes. What does that show for you?

**Comment by zackw** [comment]
> What are the value you have set for these four RuntimeXYZ= settings on your system?

All are at their defaults:

```
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#SystemMaxFiles=100
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
#MaxRetentionSec=
#MaxFileSec=1month
```

The manpage gives me the impression that this *should* cause the journal files to consume no more than 15% of the available space in `/run`, but that is very much not what happened.

> Note that the effective values chosen are also logged early on, when journald initializes.

Those logs do not get forwarded to the traditional syslog.

```
# zgrep journal `find /var/log -name apache2 -prune -o -type f` | grep -vE 'bcache|addgroup'
/var/log/apt/term.log.8.gz:Installing new version of config file /etc/systemd/journald.conf ...
/var/log/messages.4.gz:Dec  5 15:05:01 kenaz kernel: [1207958.127968] systemd-journal: 282160 output lines suppressed due to ratelimiting
/var/log/kern.log.4.gz:Dec  5 15:05:01 kenaz kernel: [1207958.127968] systemd-journal: 282160 output lines suppressed due to ratelimiting
```

I can't look in the journal itself because I am working around this problem with `Storage=none` at present, and I can't change that for a couple days because the computer is currently tied up with a major backup operation which I would rather not be tinkering underneath.

**Comment by evverx** [comment]
Note that https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/patches doesn't contain 3099caf2b5bb94.

So, this
> Note that the effective values chosen are also logged early on, when journald initializes. What does that show for you?

doesn't work

**Comment by arvidjaar** [comment]
> Those logs do not get forwarded to the traditional syslog.

That's true, `ForwardToSyslog` is false since quite some time. Both rsyslog and syslog-ng support pulling logs from journal, but they must be configured to do so (as example on openSUSE one is and another is not by default). Also I am not sure whether they support both run-time and persistent journal location. 

> I am working around this problem with `Storage=none` at present

Then you need enable `ForwardToSyslog` in any case. But note, that it will likely miss early boot messages until syslog daemon starts.

**Comment by poettering** [comment]
Well, can you ask your distro to include that patch?

Also, does this get properly rotated if you ask for it explicitly via "journalctl --rotate"?

**Comment by evverx** [comment]
@mbiebl included that patch https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=ae9173d29103d937d1a59850e5a44e7a1432b600 (`v232-14`)

**Comment by flamein** [comment]
@zackw: maybe it's worth a try to try and reproduce it on ubuntu 17.04, as it also features systemd 232. 
as far as i can see i'm not able to reproduce your issue there, implying something would be off in that particular version of the debian unstable package.

**Comment by poettering** [comment]
It appears to me this issue is fixed. If it isn't on current systemd, please reopen.
