### ISSUE TITLE
Assertion in `device_is_bound_by_mounts()` when device is inaccessible

### ISSUE THREAD

**Issue by dhke** [systemd/systemd#5025]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 228, but code is unchanged in 233

### Used distribution

> SUSE Linux Enterprise Server 12 SP2  (x86_64)

### In case of bug report: Expected behaviour you didn't see

System remains useable

### In case of bug report: Unexpected behaviour you saw

Dell (and other) servers come with a virtual USB device in their remote access controllers.
These frequently get mounted under `/tmp/SECUPD` by the official utilities, usually from `/dev/sdb?`.

However, the device sometimes seems to disappear while still mounted. As of [suse-ru-20170013-1](https://www.suse.com/de-de/support/update/announcement/2017/suse-ru-20170013-1.html), which imports commit [ebc8968bc0b6fc460099041f5ae1262ca17eeb6e](https://github.com/systemd/systemd/commit/ebc8968bc0b6fc460099041f5ae1262ca17eeb6e), this results in a unusable machine.

relevant journal entries:
```
systemd[11505]: Assertion 'dev' failed at src/core/device.c:301, function device_is_bound_by_mounts(). Aborting.
FAT-fs (sdc): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
systemd[1]: Assertion 'dev' failed at src/core/device.c:301, function device_is_bound_by_mounts(). Aborting.
systemd[1]: Caught <ABRT>, dumped core as pid 30128.
systemd[1]: Freezing execution.
```

It looks like it is valid for `dev` to be `NULL` in `device_setup_unit(Manager *m, struct udev_device *dev, const char *path, bool main)`. At least there are various guards with `if (dev)` in the source.

This is not checked before the (new) call to `device_is_bound_by_mounts()`, which itself does `assert(dev)`. As a result, PID1 aborts and the system cannot be managed any more. I'm not familiar with the new logic, but the fix may be a simple guard condition inside `device_is_bound_by_mounts()`.

### In case of bug report: Steps to reproduce the problem

> Have a dell server with SLES12 SP2, install suse-ru-20170013-1.
Probably is also triggered by removing any mounted USB device (untested).

**Comment by dhke** [comment]
However, the culprit code path seems to be in [`device_found_node()`](https://github.com/systemd/systemd/blob/ebc8968bc0b6fc460099041f5ae1262ca17eeb6e/src/core/device.c#L811), all other code paths seem (assert) guarded for `dev != NULL`.
However, in `device_found_node()`, if the device does not have a `/dev` node or if `udev_device_new_from_devnum()` returns `NULL`, `device_setup_unit()` maybe called with `dev == NULL`.
```
diff --git a/src/core/device.c b/src/core/device.c
index bd481c8..44b30ab 100644
--- a/src/core/device.c
+++ b/src/core/device.c
@@ -290,11 +290,12 @@ static bool device_is_bound_by_mounts(Unit *d, struct udev_device *dev) {
         int r = false;
 
         assert(d);
-        assert(dev);
 
-        bound_by = udev_device_get_property_value(dev, "SYSTEMD_MOUNT_DEVICE_BOUND");
-        if (bound_by)
+        if (dev) {
+            bound_by = udev_device_get_property_value(dev, "SYSTEMD_MOUNT_DEVICE_BOUND");
+            if (bound_by)
                 r = parse_boolean(bound_by) > 0;
+        }
 
         DEVICE(d)->bind_mounts = r;
         return r;
```

But I am a little confused, since `device_is_bound_by_mounts()` actually seems to have the side effect of updating `->bind_mounts`, which is ... unexpected.

**Comment by fbuihuu** [comment]
@dhke thanks for reporting. I've created PR#5033 to fix this issue.

**Comment by fbuihuu** [comment]
> But I am a little confused, since device_is_bound_by_mounts() actually seems to have the side effect of updating ->bind_mounts, which is ... unexpected.

->bind_mounts is used to save the fact that the device wants the BindTo dep for mount units. This is needed as "udev_device" structure won't be available for future mounts happening on this device.

**Comment by dhke** [comment]
> ->bind_mounts is used to save the fact that the device wants the BindTo dep for mount units. This is needed as "udev_device" structure won't be available for future mounts happening on this device.

Thanks for the clarification. From reading, I would have classified `device_is_bound_by_mounts()` as a predicate function that should be idempotent without side effects.

 Does it seem reasonable to move the update to `device_upgrade_mount_deps()`, so that `device_is_bound_by_mounts()` is side effect free?

**Comment by fbuihuu** [comment]
> Does it seem reasonable to move the update to device_upgrade_mount_deps(), so that device_is_bound_by_mounts() is side effect free?

That was originally the case but @poettering asked to hide it in device_is_bound_by_mounts(), see PR#4515.
