### ISSUE TITLE
test-execute fails if /dev/mem is not present

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#5027]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd-219 (but applies to upstream version as well)

### Used distribution

> Red Hat Enterprise Linux 7

### In case of bug report: Expected behaviour you didn't see

> Test passes

### In case of bug report: Unexpected behaviour you saw

> Test fails due to abort()

### In case of bug report: Steps to reproduce the problem

> Run ```make check``` on system that doesn't have /dev/mem

Part of the ```test-execute``` that checks whether ```PrivateDevices``` stanza works as expected assumes that ```/dev/mem``` is available (see ```test/test-execute/exec-privatedevices-no.service```) However I've seen ARM64 systems that doesn't provide raw memory access via ```/dev/mem``` character device. It didn't dig into this too much, IOW I don't know if this is kernel config issue or not, but I found this Linaro wiki page that talks about ```/dev/mem``` removal.

https://wiki.linaro.org/LEG/Engineering/Kernel/dev-mem

Nevertheless, I think it would be better to check for ```/dev/kmsg``` because we don't support systems w/o it.

**Comment by poettering** [comment]
Fixed by #5028.
