### ISSUE TITLE
errno-to-name.h missing from make rules

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#503]
Running e.g. `make journalctl` fails with:

```
src/basic/errno-list.c:30:27: fatal error: errno-to-name.h: No such file or directory
compilation terminated.
Makefile:14173: recipe for target 'src/basic/libbasic_la-errno-list.lo' failed
make: *** [src/basic/libbasic_la-errno-list.lo] Error 1
```

(it works fine for a `make all`, which will spit out `GEN      src/basic/errno-to-name.h`)

It appears that a necessary make rule is missing.

**Comment by kaysievers** [comment]
I don't know of a nice way to specify that.

"It might be important to emphasize that BUILT_SOURCES is honored only by ‘make all’, ‘make check’ and ‘make install’. This means you cannot build a specific target (e.g., ‘make foo’) in a clean tree if it depends on a built source. However it will succeed if you have run ‘make all’ earlier, because accurate dependencies are already available."

http://www.gnu.org/software/automake/manual/automake.html#Sources

**Comment by daurnimator** [comment]
> I don't know of a nice way to specify that.

...

> http://www.gnu.org/software/automake/manual/automake.html#Sources

From your link:

> Usually people are happy enough with BUILT_SOURCES because they never build targets such as ‘make foo’ before ‘make all’, as in the previous example. However if this matters to you, you can avoid BUILT_SOURCES and record such dependencies explicitly in the Makefile.am.
> 
> ```
> bin_PROGRAMS = foo
> foo_SOURCES = foo.c
> nodist_foo_SOURCES = bindir.h
> foo.$(OBJEXT): bindir.h
> CLEANFILES = bindir.h
> bindir.h: Makefile
>         echo '#define bindir "$(bindir)"' >$@
> ```
> 
> You don’t have to list all the dependencies of foo.o explicitly, only those that might need to be built. If a dependency already exists, it will not hinder the first compilation and will be recorded by the normal dependency tracking code. (Note that after this first compilation the dependency tracking code will also have recorded the dependency between foo.o and bindir.h; so our explicit dependency is really useful to the first build only.)
> 
> Adding explicit dependencies like this can be a bit dangerous if you are not careful enough. This is due to the way Automake tries not to overwrite your rules (it assumes you know better than it). ‘foo.$(OBJEXT): bindir.h’ supersedes any rule Automake may want to output to build ‘foo.$(OBJEXT)’. It happens to work in this case because Automake doesn’t have to output any ‘foo.$(OBJEXT):’ target: it relies on a suffix rule instead (i.e., ‘.c.$(OBJEXT):’). Always check the generated Makefile.in if you do this.

**Comment by kaysievers** [comment]
Yeah, I know, but I don't want to add that everywhere. We heavily depend on code we create during build, and it will make the mess, that the autofoo already is, even uglier.

We could add:
  built-sources: $(BUILT_SOURCES)
so that:
  make built-sources
would trigger the build and all later custom targets would work.

**Comment by dvdhrm** [comment]
We can also add:

```
built-sources: $(BUILT_SOURCES)
DUMMY := $(shell $(MAKE) built-sources)
```

Via the immediate assignment ':=' we force `make built-sources` on each invocation of `make`. Now we just need a way to avoid the recursion here... Might not be worth it to investigate.

**Comment by dvdhrm** [comment]
I added the "built-sources:" target in 7ee7b225bd2fc3e7a3980f5fb7b10dfc6e205578 now. It does indeed look handy for scripts.

I don't think we should force it on all targets, though. It just doesn't make sense for most and it's an issue that automake should solve, not us.

**Comment by daurnimator** [comment]
That helps; but it doesn't solve the initial issue.

It at least needs instructions or a note....

**Comment by dvdhrm** [comment]
Why? automake clearly documents that you cannot use direct targets if your project uses BUILT_SOURCES.
