### ISSUE TITLE
systemd-networkd creates extra interface with Kind=dummy

### ISSUE THREAD

**Issue by mrschyte** [systemd/systemd#5034]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> The functionality works, however an extra interface is created beyond what is specified.

### In case of bug report: Unexpected behaviour you saw

> An extra interface is created with the name "dummy0" besides the "dmz0" dummy interface defined below. This happens only when Kind=dummy is specified.
> Additionally I see the following error in journalctl: "systemd-udevd[357]: Could not generate persistent MAC address for dummy0: No such file or directory" which seems to be related.

### In case of bug report: Steps to reproduce the problem

> Create the following netdev and network files then reload systemd-networkd:
> dmz0.netdev
> [NetDev]
> Name=dmz0
> Kind=dummy
>
> dmz0.network
> [Match]
> Name=dmz0
> Bridge=brdmz0
>
> brdmz0.netdev
> [NetDev]
> Name=brdmz0
> Kind=bridge

**Comment by poettering** [comment]
well, this is created automatically by dummy.ko when it is loaded. It's stupid legacy behaviour. Most distros turn this off. If you distro doesn't, then please ask them to. Locally, you can turn this off by dropping in a fragment in /etc/modprobe.d/ that setts the "numdummies=" parameter of dummy.ko to 0...

Anyway, this is nothing we can do anything about in systemd. Closing hence. Please contact your distro.

**Comment by mrschyte** [comment]
Much appreciated. I didn't know that was the default behavior for dummy.ko. I'll raise the issue on the bugtracker for ArchLinux.
