### ISSUE TITLE
introduce TimerAction=

### ISSUE THREAD

**Issue by zdzichu** [systemd/systemd#5035]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> v232

I'd like to ask for introducing `TimerAction=` (or just `Action=`) setting in timer units. It should:
- tell what to do with Unit= when timer fires
- default to 'start'
- accept all verbs from `job_state_table` (src/core/job.c:1443)

**Comment by poettering** [comment]
Duplicate of #3866
