### ISSUE TITLE
Systemd DHCP does not request on VLANs 

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5037]
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> arch linux arm 

### In case of bug report: Expected behaviour you didn't see

> getting a dhcp assigned address on vlan eth2.132

### In case of bug report: Unexpected behaviour you saw

> when i boot the machine or restart systemd-networkd, i lose the ip on eth2.132, but the managed port (same device) for the ISP (eth2) gets an IP

### In case of bug report: Steps to reproduce the problem

> 
[root@alarm network]# ifconfig eth2
eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.30.39  netmask 255.255.128.0  broadcast 172.22.127.255
        inet6 fe80::250:43ff:fe21:4003  prefixlen 64  scopeid 0x20<link>
        ether 00:50:43:21:40:03  txqueuelen 532  (Ethernet)
        RX packets 18814  bytes 1212610 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 175  bytes 17071 (16.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 40  

[root@alarm network]# ifconfig eth2.132
eth2.132: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::250:43ff:fe21:4003  prefixlen 64  scopeid 0x20<link>
        ether 00:50:43:21:40:03  txqueuelen 1000  (Ethernet)
        RX packets 18375  bytes 855978 (835.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 2632 (2.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@alarm network]# cat 30-eth2.132.netdev 
[NetDev]
Name=eth2.132
Kind=vlan

[VLAN]
Id=132
[root@alarm network]# cat 40-eth2.network 
[Match]
Name=eth2

[Network]
VLAN=eth2.132
DHCP=ipv4
DNS=77.109.148.137
[root@alarm network]# cat 80-eth2.132.network 
[Match]
Name=eth2.132

[Network]
DHCP=ipv4
DNS=77.109.148.137

[root@alarm network]# dhcpcd eth2.132
DUID 00:01:00:01:1f:c1:df:85:00:50:43:00:2a:1d
eth2.132: IAID 43:21:40:03
eth2.132: soliciting an IPv6 router
eth2.132: ipv6nd_sendrsprobe: sendmsg: Operation not permitted
eth2.132: rebinding lease of 83.xx.7.127
eth2.132: probing address 83.xx.7.127/24
eth2.132: leased 83.xx.7.127 for 7200 seconds
eth2.132: adding route to 83.xx.7.0/24
eth2.132: adding default route via 83.xx.7.1
forked to background, child pid 2851
[root@alarm network]# dhcpcd eth2.132
dhcpcd already running on pid 2851 (/run/dhcpcd-eth2.132.pid)
[root@alarm network]# kill 2851
[root@alarm network]# systemctl restart systemd-networkd
Warning: systemd-networkd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[root@alarm network]# systemctl daemon-reload
[root@alarm network]# systemctl restart systemd-networkd
[root@alarm network]# ifconfig eth2.132
eth2.132: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::250:43ff:fe21:4003  prefixlen 64  scopeid 0x20<link>
        ether 00:50:43:21:40:03  txqueuelen 1000  (Ethernet)
        RX packets 37108  bytes 1745436 (1.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 103  bytes 15487 (15.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

As you can see, dhcpcd works (so the connection is fine, i am online with this right now), but dhcp from systemd does not request that or so...?

**Comment by ssahani** [comment]
@blahmutz I see that `DHCP CLIENT (0xc127d092): DISCOVER` are being sent but don't see any response are coming back . Captured packets with wireshark , don't see any response is coming back.


Same thing with `dhcpd`

```/root/dhcpcd eth2.132
DUID 00:01:00:01:1f:3f:a3:f4:08:00:27:f8:62:01
eth2.132: IAID 56:78:9a:bc
eth2.132: soliciting an IPv6 router
eth2.132: soliciting a DHCP lease
eth2.132: no IPv6 Routers available
timed out
dhcpcd exited
```

**Comment by ghost** [comment]
Did i attach a log file or where did you see that 0xc127d092 ?

> Same thing with dhcpd

Do you mean dhcp**c**d ?

**Comment by ssahani** [comment]
>> Do you mean dhcpcd ?

      yes. These logs are from my testing .

**Comment by ghost** [comment]
Ah thats nice, so you were able to reproduce. Maybe some developer of systemd can take a look at it.
Also, it seems that the routing informations sent by the dhcp server are not handled as they should from systemd's dhcp client.

**Comment by poettering** [comment]
Could you check if #5281 fixes things for you, please?

**Comment by ghost** [comment]
i am not using systemd at the moment. When i go back to arch linux arm (i am not sure if i do), i will check that.

**Comment by poettering** [comment]
OK, let's close this due to lack of response. If there's still an issue, please file a new issue!
