### ISSUE TITLE
Can't anything bad be detected when given gibberish?

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#504]
Can't anything bad be detected when given e.g.,
 # systemctl disable zzzzzzzzzzzz.servicezzzzz ; echo $?
 0

**Comment by poettering** [comment]
it can be detetect and is. However ther's a logic in place to turn invalid unit names into valid ones by escaping invalid chars and suffixing .service if the unit name lacks any valid unit name. This is done to make things easier for the user.

Also, note that "systemctl disable" is a NOP but no error for unit files that are missing to make the call idempotent. If you try the same unit name for "systemctl start" you will in fact get an error.

I hope this makes sense. Closing hence.

**Comment by jidanni** [comment]
All I know is this is just as bad as if I did
$ rm file
but mistyped the file name, only to come back the next week with customers complaining I did not remove the file.

Anyway this is all one big black box where one can only cross ones fingers things worked.

Or I suppose dig in and do things manually.

At least add an option like perl has:
  -w                enable many useful warnings
  -W                enable all warnings

**Comment by godzillante** [comment]
@poettering  wrote:

> I hope this makes sense

well, IMHO it doesn't.

**Comment by jidanni** [comment]
disable X && is-enabled X proves something is wrong

```
# systemctl --help | egrep Disable\|enabled
  disable NAME...                 Disable one or more unit files
  is-enabled NAME...              Check whether unit files are enabled
# systemctl is-enabled sshd
enabled
# systemctl disable sshd
# systemctl is-enabled sshd
enabled
```

**Comment by poettering** [comment]
@jidanni That appears unrelated to the original issue. Could you file a seperate issue for that, and please include information on the distro you use, and of the contents of /usr/lib/systemd/system and /etc/systemd/system when it comes to files named _ssh_? Also, please paste the sshd.service unit file contents. Thanks.

**Comment by jidanni** [comment]
Perhaps you could give me a script to run to gather this information, i.e., "shd.service unit file " = ?

I will also append reportbug --template.

**Comment by jidanni** [comment]
Wait, I see reportbug includes all that. OK, never mind.

**Comment by poettering** [comment]
```
find /usr/lib/systemd/system /etc/systemd/system -iname '*ssh*'
cat /etc/os-release
systemctl cat sshd
```

**Comment by jidanni** [comment]
OK thanks. That will save 500 KB.
