### ISSUE TITLE
resolved: does not resolve FQDN version of machine hostname

### ISSUE THREAD

**Issue by bits01** [systemd/systemd#5041]
### Submission type

  - [x] Bug report
  
### systemd version the issue has been seen with

> systemd 232-6

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Cannot resolve FQDN of machine hostname

### In case of bug report: Unexpected behaviour you saw

>For a machine that has the hostname set to `host.domain` (FQDN form) as returned by `hostname` or `hostnamectl`, only the *short* name of the machine can be resolved, but not the FQDN name, i.e. *host* can be resolved to the correct IP of the machine itself, but not *host.domain*

### In case of bug report: Steps to reproduce the problem

> /etc/nsswitch.conf by default on Arch has this line:
`hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname`

If `[!UNAVAIL=return]` is removed then FQDN works too, but that's probably because `myhostname ` ends up doing it.

The expectation is for `resolved` to be able to resolve both the short and FQDN forms of the machine hostname, in particular when the hostname of the machine is configured as FQDN.

**Comment by poettering** [comment]
fix waiting in #5276.
