### ISSUE TITLE
"machinectl shell" always allocates a pty, and probably shouldn't when used in a pipeline

### ISSUE THREAD

**Issue by jkufner** [systemd/systemd#5042]
### Submission type

Bug report

### systemd version the issue has been seen with

232

### Used distribution

Debian

### In case of bug report: Expected behaviour you didn't see

```
# echo pwd | /bin/bash -v
pwd
/tmp
```

### In case of bug report: Unexpected behaviour you saw

```
# echo pwd | machinectl shell debian-testing /bin/bash -v
Connected to machine debian-testing. Press ^] three times within 1s to exit session.

Connection to machine debian-testing terminated.
```

### In case of bug report: Steps to reproduce the problem

See above.

### Description

machinectl shell does not handle stdin, stdout and stderr correctly. Instead of waiting for the process to finish, it kills it instantly as `stdin` is closed. It should close stdin of the child process and wait for rest of stdout, stderr, and other filedescriptors to finish (yes, there may be more than two). The process will terminate on its own and only then it is safe to close all remaining opened filedescriptors and to terminate machinectl.

Also, `stderr` is not displayed at all.

When the same command is executed using `systemd-nspawn` (without booting up the container) instead of `machinectl shell`, everything works as expected. When connecting via ssh, everything works too.

**Comment by poettering** [comment]
"machinectl shell" creates a pty, and ttys are either hung up as a whole or not hung up at all. You cannot hang them up in one direction only. This means that a hangup on stdin will also mean there's a hangup on stdout, immediately, if you so will.

I doubt there's much we can do about this...

**Comment by jkufner** [comment]
SSH can deal with it. Obviously this problem has a solution.

`machinectl shell` loses/corrupts user's data when piped to another process. Therefore it is broken.

**Comment by poettering** [comment]
So, a new "--pipe" mode has been implemented in systemd-run now, which should deliver what you want. 

Closing, see 5dca7739e862eae50a162b0cc7f8613f7fd33c81 for details.
