### ISSUE TITLE
networkd: ethernet interfaces participating in a bridge are stuck in "configuring", failing wait-online

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#5043]
### Submission type

  - Bug report

### systemd version the issue has been seen with

> systemd 232
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Arch

### In case of bug report: Expected behaviour you didn't see

When an ethernet interface is linked with a bridge by a `Bridge=` directive (and no other configuration present), it should transition to "configured" as soon as it is added to that bridge.

### In case of bug report: Unexpected behaviour you saw

That interface is stuck in "configuring" state, failing wait-online.

### In case of bug report: Steps to reproduce the problem

1. Consider a system with a single Ethernet interface in a network managed by DHCPv4.

2. Place following files in `/etc/systemd/network`:
  - `/etc/systemd/network/br0.netdev`:
```
[NetDev]
Description=Bridge for libvirt
Name=br0
Kind=bridge
```
  - `/etc/systemd/network/br0.network`:
```
[Match]
Name=br0

[Network]
DHCP=ipv4

[DHCP]
UseDomains=yes
```
  - `/etc/systemd/network/ethernet.network`:
```
[Match]
Name=en*

[Network]
Bridge=br0
```

3. Restart networkd and get this output (wlp2s0 disabled, tun0 manually managed):
```
$ networkctl
IDX LINK             TYPE               OPERATIONAL SETUP
  1 lo               loopback           carrier     unmanaged
  2 enp4s0           ether              carrier     configuring
  3 wlp2s0           wlan               off         unmanaged
  4 br0              ether              routable    configured
 14 tun0             none               routable    unmanaged

5 links listed.
```

**Comment by enihcam** [comment]
same issue here.

**Comment by chrsmrtnx** [comment]
The same underlying issue affects bonded interfaces. If I have eth0 and eth1 forming bond0, then I get the network-online.target timeout unless I override systemd-networkd-wait-online.service's default behaviour and tell it to ignore eth0 and eth1. They are "stuck" in "configuring" status according to networkctl:

> IDX LINK             TYPE               OPERATIONAL SETUP     
...
  2 eth0             ether              carrier     configuring
  3 eth1             ether              carrier     configuring
...
  5 bond0            ether              routable    configured

For reference, eth0.network is very simple (and eth1 is the same except for the number):

> [Match]
Name=eth0
>
> [Network]
Bond=bond0

**Comment by delacroix0815** [comment]
Same issue here with bridge interface. My systemd version:
systemd 233
+PAM +AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN default-hierarchy=hybrid

**Comment by madman2003** [comment]
Still a problem with systemd 234 (arch linux), what is needed to get this fixed? What can I do to help?

**Comment by BtbN** [comment]
Two of my systems are also affected by this.

**Comment by TCB13** [comment]
+1 on this!

**Comment by ssahani** [comment]
@intelfx https://github.com/systemd/systemd/commit/ccad03a4ccf8043f0cb698abcb32bbd87856b15f

**Comment by ghost** [comment]
I have exactly same problem on my router.
I decide to bridge local ethernet with wifi card into one local network. Finally I did find right configuration but shorewall is not starting until ...wait-online.service timeout.

```
Oct 24 17:44:24 skriatok systemd-networkd-wait-online[429]: Event loop failed: Connection timed out
Oct 24 17:44:24 skriatok systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 17:44:24 skriatok systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
Oct 24 17:44:24 skriatok systemd[1]: Failed to start Wait for Network to be Configured.
Oct 24 17:44:24 skriatok systemd[1]: Reached target Network is Online.
Oct 24 17:44:24 skriatok systemd[1]: Starting Shorewall IPv4 firewall...
```

Network start to work correctly (I mean service on router as dns, dhcp, routing ....) After shorewall is started. Well, expect that local interface is still in **configuring**

```
networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 br0             ether              routable    configured
  3 locnet          ether              carrier     configuring
  4 gateway            ether              routable    configured
  5 wifinet           wlan               degraded    unmanaged
```

Of course, trying to find whats going on I did came here after some searching web.
I can see some changes / commits, hope those will came to update soone.

I am running archlinux with systemd 235.8-1

**Comment by BtbN** [comment]
The commit was made 28 days ago, 235 was released 18 days ago.
I'd expect the fix to be in there.

**Comment by ghost** [comment]
checking packages again
```
pacaur -Qs systemd
local/libsystemd 235.8-1
    systemd client libraries
local/netctl 1.14-1 (base)
    Profile based systemd network management
local/systemd 235.8-1 (base-devel)
    system and service manager
local/systemd-sysvcompat 235.8-1 (base)
    sysvinit compat for systemd
```
looks that last update 7days ago
https://www.archlinux.org/packages/core/x86_64/systemd/

SO
what can be problem that ...wait-online.service take so long and interface is still in configuring?
```
systemd-analyze blame 
      2min 149ms systemd-networkd-wait-online.service
           999ms asd.service
```

looks that it is still not fixed

**Comment by ssahani** [comment]
it's not merged yet https://github.com/systemd/systemd/pull/6918/commits/5971cb9de9081b537945d28895df70992e5664d0 
https://github.com/systemd/systemd/pull/6918

**Comment by ssahani** [comment]
Can you still reproduce this with current git ?

**Comment by ghost** [comment]
sorry, I did leave that configuration of myrouter, not using bridge now ...

**Comment by madman2003** [comment]
I still have a bridge configuration, but it takes multiple checks to be sure these kind of problems are really fixed. I run archlinux, so my systemds are pretty recent, although not git.

**Comment by andrewwebber** [comment]
Are there any work-arounds or do we need to wait for a systemd release? This issue stopped OpenStack on CoreOS bridging a single network interface. This feels like a regression because it was actually working 2 years ago with a Veth interface on a bridge

https://gist.github.com/andrewwebber/f788790772cef47ed5bff39aae2212cf#file-kolla-coreos-L25

```yaml
write_files:
  - path: /etc/systemd/network/10-virt.netdev
    permissions: 0644
    owner: root
    content: |
      [NetDev]
      Name=virbr0
      Kind=bridge
  - path: /etc/systemd/network/20-static.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      Name=ens13f0

      [Network]
      Bridge=virbr0
  - path: /etc/systemd/network/30-virt.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      Name=virbr0

      [Network]
      DNS=172.20.20.20
      Address=172.20.30.167/24
      Gateway=172.20.30.1

  - path: /etc/systemd/network/40-veth.netdev
    permissions: 0644
    owner: root
    content: |
      [NetDev]
      Name=veth0
      Kind=veth

      [Peer]
      Name=veth1

  - path: /etc/systemd/network/50-virt.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      Name=veth0

      [Network]
      Bridge=virbr0
```

**Comment by ssahani** [comment]
@andrewsoutar did you tested with current git ?

**Comment by andrewwebber** [comment]
I am testing on CoreOS 
I have the following versions avaliable - https://coreos.com/releases/
On IRC they state a couple of weeks before an Alpha update :(

**Comment by r7vme** [comment]
Any progress / ideas so far? We use systemd 238 and still see this issue.

Seems issue that i've reported https://github.com/systemd/systemd/issues/10118 can be a duplicate of this one. We have our bonding slaves in configring state and on every restart we are getting downtime, because networkd does up/down for slaves (as far as i understood from logs).

**Comment by akrus** [comment]
I can see #6918 is merged now, but the problem is still present in latest releases. No fix yet?

**Comment by yuwata** [comment]
I hope #11767 helps this issue.

**Comment by skoehler** [comment]
I still have this issue, sort of. I have 4 interfaces attached to a bridge. One of the 4 interfaces has a carrier. The remaining 3 don't have a carrier. All are stuck in the configuring state. How can I tell networkd to ignore that 3 of the 4 interfaces don't have a carrier?
I tried `RequiredForOnline=no`, but it doesn't work.

**Comment by skoehler** [comment]
`ConfigureWithoutCarrier=yes` did the trick
