### ISSUE TITLE
 atkbd serio0: Unknown key pressed (translated set 2, code 0x88 on isa0060/serio0)

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#5047]
At each time pressing the WiFi Fn key on Dell Latitude E7270 laptop, the system reports the following error/warning messages:

>  atkbd serio0: Unknown key pressed (translated set 2, code 0x88 on isa0060/serio0).
>  atkbd serio0: Use 'setkeycodes e008 <keycode>' to make it known.

This was reported here https://bugzilla.opensuse.org/show_bug.cgi?id=1010220.

Apparently this is due to commit 0e336347 which was added to fix https://bugs.launchpad.net/ubuntu/+source/udev/+bug/1441849.

A potential fix could consist in adding the following rule:

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnDell*:pnLatitude*E7*:pvr*
KEYBOARD_KEY_88=unknown               # Fn-PrtScr - revert to N/A
```

so we restore the old behavior for Dell Latitude E7* models but I'm wondering if the rule added initialy by commit 0e336347 wasn't a bit too loose.

@martinpitt could you give your feeling here ?

Thanks.

**Comment by poettering** [comment]
@martinpitt, @whot and idea?

**Comment by martinpitt** [comment]
@fbuihuu: I can't look at the opensuse bug, it says "not authorized" -- not a public bug?

Anyway, [that commit](https://github.com/systemd/systemd/commit/0e336347dedc3577214484ec3d97f0f799dd81fd) only fixed the release event, it did *not* change the keymap. Also, it's not possible to quiesce the "unknown key" warnings by setting a value of `unknown`, as that's the value that it apparently already has :-) (at least that was true for similar cases that I've looked into).

Some questions:
 - Does this key actually work as a wifi killswitch? If so, then presumably it's already being handled in the BIOS or in hardware. If not, then it could be assigned `KEY_RFKILL` or so to.
 - Does your proposed rule actually make the warning go away? (That'd surprise me -- you can certainly assign a sensible value to it, but if it gets handled in hardware then that would not make sense)
 - Does reverting the original commit really make the warning go away?

**Comment by fbuihuu** [comment]
@martinpitt , sorry for the delay.

Here I'm only the messenger so I can't really answer your questions. I'll try to get some answers from the original reporter and hopefully give you some feedback next week.

**Comment by fbuihuu** [comment]
@martinpitt I finally got some answers:

 > Does this key actually work as a wifi killswitch? If so, then presumably it's already being handled in the BIOS or in hardware. If not, then it could be assigned KEY_RFKILL or so to.

The hardware has a specific driver (dell_wmi) to handle rfkill in the hardware level; i.e. it's a rfkill hard-block, not a soft-block.  If we handle KEY_RFKILL in software, this will doubly-flip the rfkill and it may make things worse.  Often it results in the contradicting state when started from the blocked state, for example.

So, as long as the hardware handles, the best is to leave as is.

> Does your proposed rule actually make the warning go away? (That'd surprise me -- you can certainly assign a sensible value to it, but if it gets handled in hardware then that would not make sense)

Yes, it works, at least on openSUSE-42.2.  I reconfirmed it now.
- I removed my two lines stored in /usr/lib/udev/hwdb/61-dell.hwdb, and run systemd-hwdb update, reboot, and retest Fn-PrtScr: the warning appears again.
- I restored 61-dell.hwdb, systemd-hwdb update, reboot and retest: the warning disappears.

> Does reverting the original commit really make the warning go away?

Yes, it makes the warning disappearing, too.

**Comment by Nerdherdx** [comment]
I know this is an old thread. But I have the same issue, only in my case it was a VM. I'm thinking that disabling local keyboard input on the VM would be one way to get around it. I'm just sticking with turning starting the VM, and using SSH to connect to it.  Its a small issue, but occasionally gathers a bunch of unnecessary logs.
