### ISSUE TITLE
stub resolver (127.0.0.53) and systemd-resolve have different defaults for search domains

### ISSUE THREAD

**Issue by Gamberoni** [systemd/systemd#5051]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

Or gotcha, perhaps.

### systemd version the issue has been seen with

> 231

### Used distribution

> Kubuntu 16.10, with local changes to use systemd-resolved instead of dnsmasq for local dns caching.

### In case of bug report: Expected behaviour you didn't see

> Same and expected results from any way of resolving an unqualified hostname when a search domain is configured: append the search domain to the hostname and resolve the resulting FQDN.
> I expect a `dig <hostname_without_dots>` to resolve with the search domain(s) appended.
> This is what dnsmasq, systemd-resolve and libnss_resolve do.

### In case of bug report: Unexpected behaviour you saw

> The stub resolver provided by systemd-resolved at 127.0.0.53 differs: it behaves strictly according to dig documentation: `man dig` states
> `+[no]search
           Use [do not use] the search list defined by the searchlist or domain directive in resolv.conf (if
           any). The search list is *not* used by default.'`
> The surprise arises from long exposure to dnsmasq as local dns cache behaviour.
> I would not have submitted this bugreport if systemd-resolve and libnss_resolve were consistent with their stub resolver, but they adopt dnsmasq behaviour, so the expectation is not only mine.

### In case of bug report: Steps to reproduce the problem

Have systemd-resolved running, no local dnsmasq active, the backend libnns_resolve for glibc nss installed and configured in /etc/nsswitch.conf. Have some dns search domain active. 
```
$ cat /run/systemd/netif/state 
# This is private data. Do not parse.
OPER_STATE=routable
DNS=192.168.139.1
NTP=192.168.139.1
DOMAINS=lan
```
Here I have a "lan" search domain, handed out by the dhcp server implemented by an OpenWrt router.
The hostname of the router is "tplink"
This is unexpected:
```
$ dig @127.0.0.53 tplink # FAILURE, unexpected.
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.53 tplink
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57749
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;tplink.                                IN      A

;; Query time: 790 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jan 09 16:13:58 CET 2017
;; MSG SIZE  rcvd: 35
```
in the following context:
```
$ dig +short @127.0.0.53 gateway
192.168.139.1

$ dig +short @127.0.0.53 tplink.lan 
192.168.139.1

$ dig +short +search @127.0.0.53 tplink
192.168.139.1

$ systemd-resolve tplink
tplink: 192.168.139.1
        (tplink.lan)

$ systemd-resolve --search false tplink
tplink: resolve call failed: No appropriate name servers or networks for name found

$ systemd-resolve --search false tplink.lan
tplink.lan: 192.168.139.1

$ getent hosts tplink
192.168.139.1   tplink.lan
```

**Comment by piotr-dobrogost** [comment]
How does your /etc/resolv.conf look like? Is it a symlink? What's the output of `systemd-resolve --status`?

**Comment by Gamberoni** [comment]
In data marted� 10 gennaio 2017 01:25:20 CET, Piotr Dobrogost ha scritto:
> How does your /etc/resolv.conf look like? Is it a symlink? What's the output of `systemd-resolve --status`?
> 
> 

marco@p3:~$ systemd-resolve --status 
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 3 (wlan0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 192.168.139.1
          DNS Domain: lan

Link 2 (eth0)                                                                      
      Current Scopes: none                                                         
       LLMNR setting: yes                                                          
MulticastDNS setting: no
      DNSSEC setting: no


marco@p3:~$ ls -l /etc/resolv.conf
lrwxrwxrwx 1 root root 32 gen  9 11:35 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf


marco@p3:~$ cat /etc/resolv.conf 
# This file is managed by systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known DNS servers.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 192.168.139.1
search lan


marco@p3:~$ dpkg -l libnss-resolve 
Voluto=U (non noto)/I (installato)/R (rimosso)/P (rimosso totale)/H (in attesa)
| Stato=Non/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(nessuno)/R (reinstallazione richiesta) (Stato,Err: maiuscolo=grave)
||/ Nome                                 Versione                Architettura            Descrizione
+++-====================================-=======================-=======================-=============================================================================
ii  libnss-resolve:amd64                 231-9ubuntu2            amd64                   nss module to resolve names via systemd-resolved


marco@p3:~$ grep hosts /etc/nsswitch.conf 
hosts:          files resolve [!UNAVAIL=return] mdns4_minimal [NOTFOUND=return] dns mdns4

The libnss-resolve package provides the libc nss "resolve" backend, which if available is used in preference to the stub resolver, and actually works, as of jan 2017 systemd v 231 on Ubuntu.

Beware: I saw no error with "resolve" in nsswitch.conf but the libnss package not installed. In this state DNS resolution was troublesome, both for search domains and for CNAMES.


Marco Gamberoni

_________

PGP Fingerprint: 945C CE09 7D11 E1A0 5D8D  306E DAE1 C4A6 0BB3 7A16

**Comment by Gamberoni** [comment]
In the above, the fact that I am trying to resolve the name of an OpenWrt router is important: it is a system NOT responding over LLMNR protocol.
The stub resolver on 127.0.0.53 resolves unqualified hostnames ONLY through LLMNR protocol, it succeeds if the name refers to a machine within the broadcast domain which is responding to LLMNR queries (such as another machine running systemd-resolved).

**Comment by piotr-dobrogost** [comment]
> The stub resolver on 127.0.0.53 resolves unqualified hostnames ONLY through LLMNR protocol (...)

Do you infer this from the following statement from [man systemd-resolved](http://man7.org/linux/man-pages/man8/systemd-resolved.8.html) (emphasis mine):

> **Single-label names** are routed to all local interfaces capable of
> IP multicasting, **using the LLMNR protocol**.

?

**Comment by Gamberoni** [comment]
In data mercoled� 11 gennaio 2017 13:22:08 CET, Piotr Dobrogost ha scritto:
> > The stub resolver on 127.0.0.53 resolves unqualified hostnames ONLY through LLMNR protocol (...)
> 
> Citation needed :)
> 
> 

man systemd-resolved:
	Single-label names are routed to all local interfaces capable of IP multicasting, using the LLMNR protocol.

To have almost everything working, I have just come up with this. Describing in plain words is too long, in bash:
	cat /etc/systemd/network/99dhcp_wlan0.network 
		[Match]
		Name=wlan0 
		[Network]
		DHCP=yes
		[DHCP]
		UseDomains=true

	sudo ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf
	sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolvconf/resolv.conf.d/base

Activated the change to the .network file with 
	systemctl restart systemd-networkd
and the change to the symlinks with
	resolvconf -u

Then I get (tplink does not implement LLMNR, but is an OpenWrt router where dnsmasq is authoritative for the local domain "lan"):
	dig +short +search tplink
		192.168.139.1

	dig  tplink
		; <<>> DiG 9.10.3-P4-Ubuntu <<>> tplink
		;; global options: +cmd
		;; Got answer:
		;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 12123
		;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

		;; OPT PSEUDOSECTION:
		; EDNS: version: 0, flags:; udp: 65494
		;; QUESTION SECTION:
		;tplink.                                IN      A

		;; Query time: 835 msec
		;; SERVER: 127.0.0.53#53(127.0.0.53)
		;; WHEN: Wed Jan 11 22:48:43 CET 2017
		;; MSG SIZE  rcvd: 35

	systemd-resolve tplink
		tplink: 192.168.139.1
	        (tplink.lan)

		-- Information acquired via protocol DNS in 4.9ms.
		-- Data is authenticated: no


Marco Gamberoni

_________

PGP Fingerprint: 945C CE09 7D11 E1A0 5D8D  306E DAE1 C4A6 0BB3 7A16

**Comment by piotr-dobrogost** [comment]
Still, I would appreciate some *plain words* in addition as I'm not sure what's going on :) How does using *resolvconf* help here?
