### ISSUE TITLE
Removing settings via override

### ISSUE THREAD

**Issue by PAStheLoD** [systemd/systemd#5059]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

After searching issues, checking the changelog and the documentation, this problem so far only appears to have come up on [stackoverflow](http://stackoverflow.com/questions/34802345/systemd-how-to-clear-an-entry-when-overriding-a-unit-file).

systemd should offer a way to reset a unit parameter/setting to its default value. (Like with list typed settings.)

Currently the only workaround is using a full unit override, which does not play nice when package provided unit files are updated by the distribution/upstream.

Of course, if there is a way to accomplish this, it should be documented. And if it's documented then please provide some instructions for locating the corresponding text.

Thanks for considering this RFE.

**Comment by poettering** [comment]
We support that already for many settings, simply add a drop-in that sets the relevant value to the empty string.

For technical reasons this is not supported for dependencies and very few others, and is unlikely to be added, but for most this should just work. If you encounter an option where it doesn't please file a bug about it specifically and we'll look into it.

**Comment by PAStheLoD** [comment]
Thanks for the quick response!

I encountered problems trying to reset `PIDFile` and `Type`. I'll try to reproduce them again and open issues for them.
