### ISSUE TITLE
Don't see any events using journal-gateway

### ISSUE THREAD

**Issue by bronislav** [systemd/systemd#506]
I can't get `systemd-journal-gatewayd` working. It's started successfully and `lsof` shows that it reads system log, but `curl localhost:19532/entries` returns empty response.

I have no idea where to look. Any suggestions?

```
# uname -a
Linux ip-10-4-1-150.ec2.internal 4.0.5 #2 SMP Sat Jun 27 01:21:24 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux 
```

```
# systemctl --version
systemd 220
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

I'm willing to provide any additional debug info. Just tell me what you need.

**Comment by zonque** [comment]
FWIW, I can reproduce this on my machine.

**Comment by bronislav** [comment]
@zonque, Also, this was introduced some when after 219, cause with 219 gateway works as expected.

**Comment by zonque** [comment]
This should be fixed in #510. Care to check?

**Comment by zonque** [comment]
The fix is merged now, but it didn't make it into v222. If you still see the problem with current systemd.git, please reopen this issue.

**Comment by zonque** [comment]
Ah, and thanks for reporting this, much appreciated :)

**Comment by bronislav** [comment]
I have rollback to the v219. I'm ok with waiting for the release.
