### ISSUE TITLE
Enabling persistent storage prevents systemd-journal-gatewayd from returning log entries

### ISSUE THREAD

**Issue by pawelulita** [systemd/systemd#5062]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232 (also tested on v229)

### Used distribution

Ubuntu 17.04 (also tested on Ubuntu 16.04)

### Expected behaviour

After enabling persistent storage `systemd-journal-gatewayd` is still returning log entries.

### Unexpected behaviour you saw

Enabling persistent storage prevents `systemd-journal-gatewayd` from returning any entries. 

### Steps to reproduce the problem

1. Enable persistent storage by setting `Storage=persistent` in `/etc/systemd/journald.conf` or by creating directory `/var/log/journal`.
2. Restart `systemd-journald`.
3. Enable `systemd-journal-gatewayd`.
4. Run `curl localhost:19531/entries`.

**Comment by poettering** [comment]
Does the "systemd-journal" user have access to /var/log/journal and its subdirs?

**Comment by poettering** [comment]
Note that "systemd-tmpfiles" will adjust ACLs on the dir on boot to make sure s-j-g can access the dir. But this won't happen during runtime if you just restart journald.

**Comment by poettering** [comment]
Closing this, as I am pretty sure this is simply the perms problem.

**Comment by pawelulita** [comment]
Yes, it was a permissions problem. Restarting the machine solved the problem.
