### ISSUE TITLE
bash completion for "systemd-nspawn --bind" should handle regular files, too

### ISSUE THREAD

**Issue by safinaskar** [systemd/systemd#5076]
### Submission type

  - Bug report

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian

bash completion for "systemd-nspawn --bind" should handle regular files, too (not only directories).
It can be useful to mount files. For example, --bind /etc/resolv.conf:/etc/resolv.conf .
Check zsh completion, too. And check other similar options of systemd-nspawn.

**Comment by poettering** [comment]
patches very welcome for things like this

**Comment by safinaskar** [comment]
It seems I can do this so: https://github.com/systemd/systemd/commit/76b00edbb5dd6f9f97255a87d4a41410f9446fbb . But I'm not sure. And still this is possible other options should be changed. And zsh.
