### ISSUE TITLE
networkd: configuring wired with static IP makes wireless unusable

### ISSUE THREAD

**Issue by Soukyuu** [systemd/systemd#5080]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd 232-7

### Used distribution

arch linux x64

### In case of bug report: Expected behaviour you didn't see

getting a working wireless connection 

### In case of bug report: Unexpected behaviour you saw

only able to ping the DHCP server, local PCs / remote IP end up with "Destination host unreachable"

### In case of bug report: Steps to reproduce the problem

- configure `wired.network` with a static IP
- configure `wireless.network`  with `DHCP=ipv4`
- unplug the network cable
- enable wifi
- restart systemd-networkd.service, systemd-resolvd.service, wpa_supplicant\@_interface_.network
- attempt to ping the DHCP server (e.g. 192.168.1.1) -> works
- attempt to ping any local PCs (e.g. 192.168.1.2) -> "Destination host unreachable"
- attempt to ping any remote IPs (e.g. 8.8.8.8) -> "Destination host unreachable"

Webpages also do not load, nor are any domains resolved. Plugging in the network cable revives the connection, as does setting a dynamic IP for the `wired.network` profile

I actually found [this thread](https://bbs.archlinux.org/viewtopic.php?id=200759) on the arch linux forums, which helped me work around the issue, so this is an older bug and I don't seem to be the only one.

/etc/resolv.conf (symlink) contains
```
192.168.1.1
8.8.8.8
```

**Comment by poettering** [comment]
This bug report is not very useful. Have you configured the right netmask for your system? How does .network look like? Do you see anything incorrectly set up if you type "ip addr" and "ip route"?

Note that we can't really provide support for basic IP networking configuration. This is a bug tracker, not a support forum, we simply don't have the resources for that.

Hence, unless you can show that the IP configuration networkd sets up is different from what you asked it to set up, I fear we we should close this bug here.

**Comment by Soukyuu** [comment]
the wired.network looks like this:
```
[Match]
Name=enp0s25

[Network]
Address=192.168.1.9/24
Gateway=192.168.1.1
DNS=8.8.8.8
```
The wireless.network looks like this:
```
[Match]
Name=wlp3s0

[Network]
DHCP=ipv4
```
ip addr shows that my LAN interface has an IP assigned, while my WLAN does not. Cable is not connected.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 7c:e9:d3:f4:a9:3b brd ff:ff:ff:ff:ff:ff
3: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 3c:97:0e:15:36:1f brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.9/24 brd 192.168.178.255 scope global enp0s25
       valid_lft forever preferred_lft forever
```
ip route only shows routes for the LAN card:
```
default via 192.168.178.1 dev enp0s25 proto static linkdown                                                                                                          
192.168.178.0/24 dev enp0s25 proto kernel scope link src 192.168.178.9 linkdown
```
I don't think the problem lies in my WLAN configuration, else I don't understand why changing wired.network to DHCP instead of fixed IP solves the issue for wireless. It's as if wired.network is affecting wireless.network somehow. 

If I need to provide more information, please tell me what you need.

**Comment by poettering** [comment]
well, your wifi device is shown as NO_CARRIER.

How do you connect to your wifi network? with wpa_supplicant? Are you sure it#s configuring evertyhing properly? NO_CARRIER is how the kernel tells you that there's no actual link in place. For wifi, networkd can't establish that for you. You have to set it up explicitly with wpa_supplicant.

**Comment by Soukyuu** [comment]
I am really sorry, I seem to have deleted my wpa_supplicant configuration, which is why it's showing NO_CARRIER.

With the same .network files above, the actual output is now:
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 7c:e9:d3:f4:a9:3b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.40/24 brd 192.168.1.255 scope global dynamic wlp3s0
       valid_lft 863995sec preferred_lft 863995sec
3: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 3c:97:0e:15:36:1f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.9/24 brd 192.168.1.255 scope global enp0s25
       valid_lft forever preferred_lft forever
```
```
# ip route
default via 192.168.1.1 dev enp0s25 proto static linkdown 
default via 192.168.1.1 dev wlp3s0 proto dhcp src 192.168.1.40 metric 1024 
192.168.1.0/24 dev enp0s25 proto kernel scope link src 192.168.1.9 linkdown 
192.168.1.0/24 dev wlp3s0 proto kernel scope link src 192.168.1.40 
192.168.1.1 dev wlp3s0 proto dhcp scope link src 192.168.1.40 metric 1024
```
```
# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 192.168.1.9 icmp_seq=1 Destination Host Unreachable
From 192.168.1.9 icmp_seq=2 Destination Host Unreachable
From 192.168.1.9 icmp_seq=3 Destination Host Unreachable
From 192.168.1.9 icmp_seq=4 Destination Host Unreachable
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 0 received, +4 errors, 100% packet loss, time 5021ms
```

With `wired.network` changed as follows:
```
[Match]
Name=enp0s25

[Network]
DHCP=ipv4
```
then restarting `systemd-networkd.service` and `wpa_supplicant@wlp3s0`, I get
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 7c:e9:d3:f4:a9:3b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.40/24 brd 192.168.1.255 scope global dynamic wlp3s0
       valid_lft 863997sec preferred_lft 863997sec
3: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 3c:97:0e:15:36:1f brd ff:ff:ff:ff:ff:ff
```
```
# ip route
default via 192.168.1.1 dev wlp3s0 proto dhcp src 192.168.1.40 metric 1024 
192.168.1.0/24 dev wlp3s0 proto kernel scope link src 192.168.1.40 
192.168.1.1 dev wlp3s0 proto dhcp scope link src 192.168.1.40 metric 1024
```
```
# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=48 time=32.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=48 time=33.0 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=48 time=30.9 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=48 time=31.0 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3001ms
rtt min/avg/max/mdev = 30.907/31.910/33.030/0.953 ms
```
So again, just by changing `wired.network` to `DHCP=ipv4` makes `wireless.network` work as expected...

**Comment by yuwata** [comment]
This should be already fixed. As addresses and routes on an interface are dropped when it lost its carrier. Closing.
