### ISSUE TITLE
Huge CPU load during system upgrades (Debian Jessie)

### ISSUE THREAD

**Issue by azurit** [systemd/systemd#5082]
### Submission type

  - [ x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 215-17+deb8u6 (Debian Jessie)

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian Jessie

### In case of bug report: Expected behaviour you didn't see

> Do not take down the whole server during system upgrades.

### In case of bug report: Unexpected behaviour you saw

> Huge CPU load during upgrades, seen on several servers, started after upgarde from Debian Wheezy to Jessie.

### In case of bug report: Steps to reproduce the problem

> It happens during almost all system upgrades (aptitude update/upgrade), usually when there are higher number of packages to upgrade (no matter what packages). Here is what happens to the server (upgrade was between cca 17:49 and 18:02, you see):
http://watchdog.sk/server00-cpu-load.png

This happen everytime i'm doing an upgrade, sometimes it's better, sometimes worse and few times it took down the whole server (it stopped responding and needs to be rebooted). I'm observing this behavior on multiple different servers and it started after dist-upgrade from Wheezy to Jessie. I'm sure it's related to systemd because, during upgrade, there are usually some errors related to systemd, for example (i will add more error messages when i encounter them):
Job for systemd-logind.service failed. See 'systemctl status systemd-logind.service' and 'journalctl -xn' for details.
I'm trying to get more info everytime it happens, i will post anything interesting here.

**Comment by poettering** [comment]
Sorry, but we only track issues with the two most current systemd versions upstream, and that's 231 and 232 right now, 215 is way too old for that.

I am pretty sure any issue with what you describe has already been fixed with current versions of systemd. Please rretry with something newer. Thanks!

I will close this now. I hope that makes sense. Sorry!
