### ISSUE TITLE
[Environment] section (syntactic sugar)

### ISSUE THREAD

**Issue by flungo** [systemd/systemd#5088]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Arch Linux

### Request for enhancement (RFE)

Since `EnvironmentFile`s are not the recommended way of setting environment variables and they should be set in the service file or through drop-ins, I think it would be nice to introduce an `[Environment]` section that can make the definition of environment variables much cleaner.

The proposed changes would make an `[Environment]` section which would act as an optional and interchangeable alternative to the current method of setting the environment variables as part of the `[Service]` section. The section would work as syntactic sugar providing the same functionality as defining in the service section (also providing backwards compatibility).

I would suggest for simplicity to only support one environment variable per line when using the `[Environment]` section, additionally eliminating the need for quotation marks to be used (except to denote that it should be treated as a single positional argument when used with `$VAR` in a command) and maintaining consistency with other sections.

The following examples would be equivalent drop-ins where the latter essentially implies the former:

```
[Service]
Environment='FOO=bar'
Environment='BAZ=Hello world!'
```

```
[Environment]
FOO=bar
BAZ=Hello world!
```

Thanks in advance for your consideration.

**Comment by poettering** [comment]
Sorry, but I don't think this would be a good change. Currently, the sections roughly follow the object structure inside of systemd, they are not mere syntactic sugar. The [Unit] section applies to all unit types, and then there are specific section for each type. The [Install] section otoh is only read by the unit file installer and is in many ways disconnect from the unit definition itself.

I am not convinced that blurring the lines here would be a good choice, in particular as the syntax of env var assignments in shell (which you are going for here, afaiu) is actually quite different from the unit file assignments right now, when it comes to quoting/escaping. Creating a hybrid parser for both sounds less than ideal to me...

Sorry!
