### ISSUE TITLE
Please change default qdisc from fq_codel to fq

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#5090]
### Submission type

  - [*] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> …

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

The Linux fq_codel qdisc does not implement pacing, so fq_codel would not be sufficient.
Many congestion control algorithms (like BBR) without pacing would not function properly, and may incur unnecessary high packet loss rates.

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
We started setting this to codel in e6c253e363dee77ef7e5c5f44c4ca55cded3fd47, which was supplied by @michich. 

I'd like to see a discussion about this somewhere, whether fq or fq_codel is the better choice, and I am also wondering about @michich ideas about this. @michich?

**Comment by enihcam** [comment]
https://groups.google.com/forum/#!topic/bbr-dev/4jL4ropdOV8
FYI

**Comment by hannes-zz** [comment]
Indeed, fq would be a better choice for end hosts because of it supports tcp pacing, which is a requirement for the bbr congestion control algorithm. Though fq-codel would be a better choice for forwarding/routers which don't originate local traffic.

**Comment by ivanbaldo** [comment]
So nothing happens if @michich never answers @poettering ?

**Comment by enihcam** [comment]
BBR will support fq_codel after linux-4.13.

**Comment by SimonIremonger** [comment]
@enihcam -- We have noticed this fq_codel default introduction, now found its' way into ubuntu LTS for example.
However, in order to make best used of this we really need ECN-enablement (sysctl net.ipv4.tcp_ecn) on end-hosts, this essentially seems to be the final-piece of the bufferbloat-fixes puzzle.
Please see new issue  #9087  .

**Comment by enihcam** [comment]
@SimonIremonger do you have benchmark data?

**Comment by reddwarf69** [comment]
Ignore all this. https://github.com/systemd/systemd/issues/9725 is a better discussion.
