### ISSUE TITLE
Incorrect use of the term "link" when referring to a "network interface" in man systemd.network.

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#5094]
- [ ] Bug report
  - [ ] Request for enhancement (RFE)

> systemd 232

From commit https://github.com/systemd/systemd/commit/2ae7505f011441d4209216e99398e677d7dbbcab

Originally Issue https://github.com/systemd/systemd/issues/964

> systemd.network(5)
BindCarrier=
A link name or a list of link names.  ...

Hmm - I'd say that, more precisely, the term "link", as in "link layer" or "data link layer", refers to the network "wire", or to communication on that wire, between network "nodes".  The closest thing to a "link name" would be the "network name", in the form of an IP address - which is *not* what is being called-for here.  So then, I'd say that the edit to the documentation is "wrong".

The correct term needed here would be "interface", as in "the linux network interface name", which is the way in which linux references "physical network ports/devices/interfaces".  Of course, this is actually an indirect reference, referencing the physical device by way of the name being used by the linux kernel and the device driver.  

Generally, the term "device" is used in respect to entries found in the "/dev/" directory.  "Network interfaces" are usually not "devices" in that sense.  The term "port" has different meanings in context, sometimes referencing TCP "software ports", and sometimes referencing physical "network ports".

To gain a better understanding of the way in which the term "interface" is used in practice, please do a search on the term "linux interface name", and review the results.

Please try again...

**Comment by poettering** [comment]
Yeah, this might be confusing, but we didn't come up with the terminology here. We are just following what is otherwise established, see in particular the "ip link" command.

Or to say this different: the term "link" used this way is firmly established on Linux, and we are not the ones who get to redefine it. Sorry.

Closing hence, I hope that makes sense.

**Comment by thx1111** [comment]
> see in particular the "ip link" command.

Ha!  I might suggest that you do the same, Lennart.  In particular, you might try running the command "ip link show".  You should then notice that the closest thing to an *interface* "link name" will be the *MAC address* of the physical network device interface.

Did you mean to suggest that the `BindCarrier=` option will require a list of MAC addresses?

Was I mistaken in supposing that the `BindCarrier=` option required a list of network interface names?
