### ISSUE TITLE
test-seccomp fails under asan

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5100]
```
sudo ./libtool --mode=execute ./test-seccomp
...
Testing @file-system
Operating on architecture: x86
Failed to add rule for system call newfstatat, ignoring: Numerical argument out of domain
...
==29329==ERROR: AddressSanitizer failed to allocate 0x10000 (65536) bytes of memory at address 0x610000020 (error code: 117)
==29329==AddressSanitizer CHECK failed: ../../../../libsanitizer/sanitizer_common/sanitizer_procmaps_linux.cc:20 "((ReadFileToBuffer("/proc/self/maps", &proc_maps->data, &proc_maps->mmaped_size, &proc_maps->len))) != (0)" (0x0, 0x0)
ERROR: Failed to mmap
@file-system failed with error code 1.
Assertion 'wait_for_terminate_and_warn(syscall_filter_sets[i].name, pid, true) == EXIT_SUCCESS' failed at src/test/test-seccomp.c:132, function test_filter_sets(). Aborting.
```
That's OK. We block `open` and `mmap` after all. Shouldn't we skip some filters under `asan`?

**Comment by poettering** [comment]
well, is there a nice way to detect whether we are running under asan?

(I am not sure this is really a "bug" though. It's more an incompatibility with a development tool...)

**Comment by evverx** [comment]
@poettering , sorry about the delay.

>  is there a nice way to detect whether we are running under asan?

Yes, there is.

https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html#Common-Predefined-Macros
> __SANITIZE_ADDRESS__
This macro is defined, with value 1, when -fsanitize=address is in use.

Anyway, I think we shouldn't skip the test. I'm closing.

**Comment by evverx** [comment]
fwiw `test-fileio` fails on `i686`. See https://github.com/google/sanitizers/issues/778
