### ISSUE TITLE
Feature request: join network namespace

### ISSUE THREAD

**Issue by fabiocannizzo** [systemd/systemd#5101]
I created and configured a separate network namespace `ns1` with the appropriate interfaces, DNS and firewall manually.

I would like to run some services in this separate network namespace as user `myuser`,
who does not have permission to run `ip netns exec`

I can run `ip netns exec` as root, then change user with `runuser`:

```
User=root
ExecStart=/usr/bin/ip netns exec ns1 runuser -u myuser whoami
```

It would be much nicer if I could just write:

```
User=myuser
JoinNetworkNamespace=ns1
ExecStart=whoami
```

**Comment by evverx** [comment]
Duplicate of https://github.com/systemd/systemd/issues/2741
