### ISSUE TITLE
systemd-journal uses too much CPU

### ISSUE THREAD

**Issue by phemmer** [systemd/systemd#5102]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> CentOS/7

### In case of bug report: Expected behaviour you didn't see

> Less than 10% CPU usage

### In case of bug report: Unexpected behaviour you saw

> 100% CPU usage

### In case of bug report: Steps to reproduce the problem

> base64 /dev/urandom | pv -L 1000000 | logger -t flood

### Additional info

Running syslog-ng, with `logger` feeding to it on a TCP port, I am able to feed 1MB/s of data and it uses about 9% CPU. With the above command, journald bottle necks at 100% CPU and around 450KB/s. So it's about 20x slower.

When I do an `strace` on the process, the vast majority of the time spent is stating, opening, reading, and closing the various files in `/proc/$pid`

There was a PR the author claimed would help with this, #2280, but it has been closed.

This is causing a lot of pain for us as we have very log-heavy servers, such as internet-facing web servers. Here the `systemd-journald` process is generally consuming about 30% CPU.

**Comment by initcore0** [comment]
we are able to reproduce this issue on CoreOS 1068.9.0 with systemd 229. When application begins to write extensively the CPU usage goes up to 100%. strace shows most of the time is spent in `read`, `clock_gettime` and `open` calls. Is there any explanation why would writing logs result in such big processor usage? And more important, is there anything we can do to reduce the CPU usage?  We tried to [control the CPU time quota with cgroups](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#CPUQuota=) and it seems to work, however are there any caveats?

**Comment by binarykitchen** [comment]
i have this problem on ubuntu 17.04 too. systemd-resolved taking 100% cpu and dnsmasq around 50%. too much for a desktop machine. 

what's the official solution here?

**Comment by phemmer** [comment]
@binarykitchen This issue is about journald, not resolved.

**Comment by nise** [comment]
I have the same problem on ubuntu 17.04!

**Comment by pabl0** [comment]
Have you tried disabling compression (Compress=no in journald.conf)?

**Comment by binarykitchen** [comment]
just now, thanks - see how it goes then

**Comment by vcaputo** [comment]
https://github.com/systemd/systemd/pull/6392 should make a substantial difference with regard to journald CPU usage under continuous logging.

There's no tagged release containing the commit yet, but if you're up for building your own, it's in master.

**Comment by poettering** [comment]
Indeed #6392 should substantially speed things up under log flood. I will close this bug now because of that. I am sure there's more room for optimization, but for that we need more info about specific bottlenecks, and suggestions where to improve things, and I don't think there's much value in keeping a vague "needs to be faster" issue issue open until then. Hence, please try the new code, and if you identify specific bottlenecks or have specific ideas for optimizations, please file new, separate bugs. Thank you!

**Comment by FreDeluz** [comment]
Same problem on ubuntu 18.04. Has someone found the solution?

**Comment by keszybz** [comment]
I get 1MB/s with about 50% cpu usage (current git, compiled with -O0). As @poettering said when closing this issue: please open new bugs about specific things that should be improved if there's some bottleneck that we can fix.

**Comment by sabrehagen** [comment]
Same problem Ubuntu 18.10.

**Comment by keszybz** [comment]
Please read @poettering's comment above. Saying "Same problem on some old version" in the upstream bugtracker is not going to have any effect.

**Comment by moussaidOualid** [comment]
ADD pcie_aspm=off parameter to the GRUB_CMDLINE_LINUX_DEFAULT and GRUB_CMDLINE_LINUX property by running sudo nano /etc/default/grub after

$ sudo update-grub 
$ reboot

**Comment by wellington1993** [comment]
@moussaidOualid Like that?
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pci=nomsi,pcie_aspm=off"`

Thanks!

**Comment by moussaidOualid** [comment]
separate with space
Like that 
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pci=nomsi pcie_aspm=off"
