### ISSUE TITLE
hwdb: Touchpad Scaling w/ Lenovo Y700-15ISK (hwdb entry included)

### ISSUE THREAD

**Issue by greghjones** [systemd/systemd#5104]
### Submission type

  - [x ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232-7

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
Arch Linux

Touchpad scaling issue with Lenovo Y700-15ISK. Fixed with custom hwdb entry:

evdev:name:AlpsPS/2 ALPS GlidePoint:*svnLENOVO:*pvrLenovoideapadY700-15ISK*
 EVDEV_ABS_00=164:3958:36
 EVDEV_ABS_01=114:1959:26
 EVDEV_ABS_35=164:3958:36
 EVDEV_ABS_36=114:1959:26

Not super familiar with git, so putting this here hoping someone can commit/submit a pull request/get it fixed more generally.

Thanks!
Greg

**Comment by poettering** [comment]
@bapride11 any chance you can prep a proper PR for this?

cc @whot

**Comment by whot** [comment]
what are the axis ranges like compared to the kernel ones? Are they close enough? If so, we can leave it and just use the resolution

**Comment by poettering** [comment]
@bapride11 please report back.

**Comment by poettering** [comment]
Closing due to lack of response.
