### ISSUE TITLE
systemctl show -pUnkown exits with a failed status now

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#5118]
Hi,

Issue #3856 is quite similar but this one is about the exit status that "systemctl show -pUnknown" which has also changed.

Not sure what is the best behavior in this case but since we used to return success in this case (prior to commit 3dced37b7c2c9a5c7, i.e. versions < v232) and `systemctl show` is supposed to be scriptable, this behavior change looks incorrect.

This was detected due to some scripts starting to break with v232 at Suse.

Thanks for the feedback.

**Comment by poettering** [comment]
Yeah, this looks like a bug.
