### ISSUE TITLE
Assertion 'subsystem' failed at src/libsystemd/sd-device/sd-device.c:1194, function device_get_id_filename(). 

### ISSUE THREAD

**Issue by crrodriguez** [systemd/systemd#512]
Once every full moon.. I am getting the following assertion

Assertion 'subsystem' failed at src/libsystemd/sd-device/sd-device.c:1194, function device_get_id_filename(). 

I have not found a way to reproduce it..this report was opened on Lennart's request in order to track down exactly why it happens.

**Comment by zonque** [comment]
Any error message before that, such as `sd-device: could not set subsystem for …`? Which task is crashing, and did you catch a coredump?

**Comment by dvdhrm** [comment]
Fixed in bf4c113e179650c07a8f95a14d71f365dbfe66e4. Thanks for the report!
