### ISSUE TITLE
To add info from 'systemd-analyze blame' command to 'systemctl status' output

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#5121]
### Submission type

  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 228 in openSUSE 42.2

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> openSUSE 42.2

### Description

```Preamble:```

While tracking a unexpected behavior on https://bugzilla.opensuse.org/show_bug.cgi?id=1014757 , I've notices, that some other services are not shown on ```systemd-analyze blame``` command.

In particual, I have a user-defined service ```open-km.service```, which I use, but ```systemd-analyze blame``` command also doesn't even know about this service:

``` k_mikhail@linux-mk500:~> systemd-analyze blame | grep open-km```
```k_mikhail@linux-mk500:~>```

At the same time:
```k_mikhail@linux-mk500:~> systemctl status open-km.service```
```● open-km.service - OpenKM Service
   Loaded: loaded (/etc/systemd/system/open-km.service; enabled; vendor preset: disabled)
   Active: active (running) since Птн 2017-01-20 17:08:38 EET; 33min left
 Main PID: 1572 (java)
    Tasks: 88 (limit: 512)
   CGroup: /system.slice/open-km.service
           └─1572 /opt/openkm/java/bin/java -Dnop -Djava.util.logging.manager...

Янв 20 15:10:57 linux-mk500 catalina.sh[1572]: 2017-01-20 15:10:57,575 [lo...
Янв 20 15:10:59 linux-mk500 catalina.sh[1572]: 2017-01-20 15:10:59,493 [ma...
Янв 20 15:10:59 linux-mk500 catalina.sh[1572]: 2017-01-20 15:10:59,509 [ma...
Янв 20 15:10:59 linux-mk500 catalina.sh[1572]: 2017-01-20 15:10:59,512 [ma...
Янв 20 15:15:58 linux-mk500 catalina.sh[1572]: 2017-01-20 15:15:58,138 [Up...
Янв 20 15:15:58 linux-mk500 catalina.sh[1572]: 2017-01-20 15:15:58,141 [Up...
Янв 20 15:15:58 linux-mk500 catalina.sh[1572]: 2017-01-20 15:15:58,428 [Up...
Янв 20 15:30:00 linux-mk500 catalina.sh[1572]: 2017-01-20 15:30:00,151 [Th...
Янв 20 16:00:00 linux-mk500 catalina.sh[1572]: 2017-01-20 16:00:00,221 [Th...
Янв 20 16:30:00 linux-mk500 catalina.sh[1572]: 2017-01-20 16:30:00,065 [Th...
Hint: Some lines were ellipsized, use -l to show in full.
k_mikhail@linux-mk500:~>
```
```Idea for RFE:```

To make  search process for the reasons of such unexpected behavior more easy, the idea is to display ```systemd-analyze blame``` output for each service in separate field -- ```Load-Time:```, which will contain output from ```systemd-analyze blame | grep foo-bar.service | awk '{print $1}'``` command. 

For example:

```● foo-bar.service - Foo-Bar Service
   Loaded: loaded (/etc/systemd/system/foo-bar.service; enabled; vendor preset: disabled)
   Load-Time:  some value | unknown
   Main PID: $MAINPID
... and so on
```

If ```Load-Time``` status is ```unknown```, that will be as a marker of a bug.

Thanks!

**Comment by poettering** [comment]
I am not sure we really should show that information in "systemctl status". It is available in a more "raw" way in "systemctl show" though, and of course in "systemd-analyze"...

**Comment by MikhailKasimov** [comment]
In current use-case we have **no info** about ```open-km.service``` via ```systemd-analyze blame``` command. What parameter should I accent on ```systemctl show open-km.service``` output?

The main idea is to minimize user's hand-moves by adding one string only to ```systemctl``` output (```Load-Time```, which is based on ```systemd-analyze blame | grep %service-name.service% | awk '{print $1}```-like mechanism).

BTW, this can really help to track troubles on upgrading systemd versions in this or another distro...

**Comment by poettering** [comment]
Note that systemd will GC units away if they exited cleanly and there's no further dependency on them that keeps them in memory.... This means you'll lose all time info on these units anyway as soon as they exit.

**Comment by MikhailKasimov** [comment]
```k_mikhail@linux-mk500:~> systemctl status open-km.service
● open-km.service - OpenKM Service
   Loaded: loaded (/etc/systemd/system/open-km.service; enabled; vendor preset: disabled)
   Active: active (running) since Пнд 2017-01-23 19:21:49 EET; 1 weeks 2 days ago
 Main PID: 1522 (java)
    Tasks: 89 (limit: 512)
   CGroup: /system.slice/open-km.service
           └─1522 /opt/openkm/java/bin/java -Dnop -Djava.util.logging.manager...

Фев 01 19:28:51 linux-mk500 catalina.sh[1522]: 2017-02-01 19:28:51,478 [Up...
Фев 01 19:28:51 linux-mk500 catalina.sh[1522]: 2017-02-01 19:28:51,813 [Up...
Фев 01 19:30:00 linux-mk500 catalina.sh[1522]: 2017-02-01 19:30:00,022 [Th...
Фев 01 20:00:00 linux-mk500 catalina.sh[1522]: 2017-02-01 20:00:00,075 [Th...
Фев 01 20:30:00 linux-mk500 catalina.sh[1522]: 2017-02-01 20:30:00,028 [Th...
Фев 01 21:00:00 linux-mk500 catalina.sh[1522]: 2017-02-01 21:00:00,039 [Th...
Фев 01 21:30:00 linux-mk500 catalina.sh[1522]: 2017-02-01 21:30:00,073 [Th...
Фев 01 22:00:00 linux-mk500 catalina.sh[1522]: 2017-02-01 22:00:00,047 [Th...
Фев 01 22:30:00 linux-mk500 catalina.sh[1522]: 2017-02-01 22:30:00,053 [Th...
Фев 01 23:00:00 linux-mk500 catalina.sh[1522]: 2017-02-01 23:00:00,055 [Th...
Hint: Some lines were ellipsized, use -l to show in full.

k_mikhail@linux-mk500:~> systemd-analyze blame | grep open-km.service
k_mikhail@linux-mk500:~> 
```
Service is running, not exited (if I understand your words correctly)...

**Comment by fsateler** [comment]
My guess is that `open-km.service` is `Type=simple`. Those unit types are not shown in the blame output since systemd considers them up instantaneously. It would show up always as 0ms...

**Comment by MikhailKasimov** [comment]
You're right - ```Type=simple```.

``` Those unit types are not shown in the blame output since systemd considers them up instantaneously. It would show up always as 0ms...``` -- hmm, these units also spend some time to be started, I suppose. Especially, when they're based on user-defined scripts...

Ok, let's not display them by default, but personally, schema like ```systemd-analyze blame -t simple``` looks pretty good in case of using ```systemd-analyze blame``` command. In ore common way: ```-t|--type=simple|forking|dbus|oneshot|notify|idle```.

And, anyway, ```Load-Time:``` in ```systemctl status``` output  independently on unit-type. This should make tracking unit start delays in more easy way for admins. The reason: ```systemctl status``` command became a reflex, admins type this command automatically in any case, instead of ```systemd-analyze blame``` command. And displaying +1 useful string like ```Load-Time:``` for units will be really appreciated.

Thanks!

**Comment by fsateler** [comment]
> hmm, these units also spend some time to be started, I suppose. 

Probably, but systemd has no way of knowing that.

**Comment by poettering** [comment]
Yeah, Type=simple really means that systemd won't know how long initialization takes... There's no way around that, it's how it is defined...

**Comment by MikhailKasimov** [comment]
Ok, let's put this note to https://www.freedesktop.org/software/systemd/man/systemd-analyze.html documentation.

Was:

> systemd-analyze blame prints a list of all running units, ordered by the time they took to initialize. This information may be used to optimize boot-up times. Note that the output might be misleading as the initialization of one service might be slow simply because it waits for the initialization of another service to complete.

Will be:

> systemd-analyze blame prints a list of all running units, ordered by the time they took to initialize. This information may be used to optimize boot-up times. Note that the output might be misleading as the initialization of one service might be slow simply because it waits for the initialization of another service to complete. 
> 
> **Important**: systemd-analyze blame output doesn't display results for services with Type=simple (see https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=), because systemd won't know how long initialization takes for such services and no way around to let it know.

M?

**Comment by poettering** [comment]
Such an addition to the man page would be welcome. Any chance you can create a proper PR for this? I'd be attributed to you then!

(But I'd drop the "Important" prefix. It's relevant information, but I am not sure it deserves such a strong attribute as "important")

**Comment by MikhailKasimov** [comment]
It'll be my first PR. ;) So, it can take a lot of time from my side... :(

While I'm handling with Git docs, see attached sample, plz.

[man_systemd-analyze_blame_for_simple-type_services.txt](https://github.com/systemd/systemd/files/755384/man_systemd-analyze_blame_for_simple-type_services.txt)
