### ISSUE TITLE
Cryptic status=200/CHDIR when WorkingDir=~ and no User= specified

### ISSUE THREAD

**Issue by jefft** [systemd/systemd#5124]
Using `WorkingDirectory=~` _without_ also specifying `User=` results in a non-startable service, with a cryptic 'status=200/CHDIR'. Since the default for `User` is `root`, I would expect the root directory's home to be used.

### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231-9ubuntu1 

### Used distribution

> Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

Expected the '~' in `WorkingDirectory=~` to be interpreted as root's home directory if `User=` is unspecified. Or at least a decent error message.

### In case of bug report: Unexpected behaviour you saw

Service fails with `status=200/CHDIR`

### In case of bug report: Steps to reproduce the problem

To replicate, create a simple service:
```
# cat > /etc/systemd/system/test.service <<EOF
[Service]
Type=oneshot

ExecStart=/bin/bash -c 'echo hello'
WorkingDirectory=~
EOF
# systemctl daemon-reload
```
and start while watching the logs:
```
# journalctl -u test -f &
# systemctl start test
Jan 21 04:04:04 testsystemd systemd[1]: Starting test.service...
Jan 21 04:04:04 testsystemd systemd[1]: test.service: Main process exited, code=exited, status=200/CHDIR
Jan 21 04:04:04 testsystemd systemd[1]: Failed to start test.service.
Jan 21 04:04:04 testsystemd systemd[1]: test.service: Unit entered failed state.
Jan 21 04:04:04 testsystemd systemd[1]: test.service: Failed with result 'exit-code'.
```
By contrast, if we set `User=root` the service works:
```
# cat > /etc/systemd/system/test.service <<EOF
[Service]
Type=oneshot

ExecStart=/bin/bash -c 'echo hello'
WorkingDirectory=~
User=root
EOF
# systemctl start test
Jan 21 03:59:15 testsystemd systemd[1]: Starting test.service...
Jan 21 03:59:15 testsystemd bash[757]: hello
Jan 21 03:59:15 testsystemd systemd[1]: Started test.service.
```

**Comment by evverx** [comment]
Indeed, we don't get user info if `User=` is empty
https://github.com/systemd/systemd/blob/5b3637b44a28d3fb2ba8b272905c64d9dbae4d26/src/core/execute.c#L818
```c
        if (!c->user)
                return 0;

        /* Note that we don't set $HOME or $SHELL if they are not particularly enlightening anyway
         * (i.e. are "/" or "/bin/nologin"). */

        name = c->user;
        r = get_user_creds_clean(&name, uid, gid, home, shell);
        if (r < 0)
                return r;
```
