### ISSUE TITLE
systemd-resolved, allow to add domains to NTA

### ISSUE THREAD

**Issue by gfa** [systemd/systemd#5128]
### Submission type

  - [ X] Request for enhancement (RFE)

### systemd version the issue has been seen with
232

### Used distribution
Debian

Hello, I'd like to be able to add a, configurable, domain name to "Negative trust anchors" list regardless of the nic configurations.

I use systemd-networkd and systemd-resolved in my laptop. At home and at least another home the local dns zone is published under .casa domain (home in spanish) so I'd like to disable dnssec for the domains under .casa. Similar how .lan, .home, corp, etc are disabled.

I don't expect you guys to add *home* in all the  languages  in the world, so I'd like to be able to do it myself.

thanks

**Comment by gfa** [comment]
Let me add a second use case, 
I want to disable DNSSEC for my local zones in my datacenter as they won't be ever signed, but I want to check DNSSEC for other zones (google.com, etc).
Some zones may be "local" to a particular interface (DNSSECNegativeTrustAnchors) but other may not be directly associated with the server but with servers on a different region, dc, environment, etc.

I'll update #2683 as I'd need changes there as well.

edited: for clarity

**Comment by poettering** [comment]
Not sure I follow. There's already a global system-wide NTA configuration directory in  /etc/dnssec-trust-anchors.d/*.negative. And there's per-interface local NTA configuration via .network files. 

What else do you need?

**Comment by gfa** [comment]
Cool, I missed /etc/dnssec-trust-anchors.d/*.negative

I dont want systemd-resolved to mark my DNS server as not-DNSSEC capable if it does not support any of UDP+EDNS0+DO+LARGE while resolving domains in NTA

I need systemd-resolved to be dumb while resolving domains from the NTA and smart when resolving any other domain

**Comment by poettering** [comment]
OK, closing then, as the requested feature already exists.
