### ISSUE TITLE
logind changes from #509 break gdm

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#513]
Since the merge of #509 , gdm 3.14 is broken.
When I log out, gdm is just stuck and no display prompt is shown.
Reverting the two commits from #509 makes the problem go away.

**Comment by kaysievers** [comment]
It is too late, v222 is already out. Needs to be sorted out after the release.

**Comment by kaysievers** [comment]
I guess you need a newer gdm to work with the current work-around/fix in logind, specifically this:
https://git.gnome.org/browse/gdm/commit/?id=806f2de647803a4f5890dc56d5ffe93ac489946b

Edit: Nah, I'm confused. We look for session class, not session type. That should be fine.

**Comment by poettering** [comment]
#536 probably tracks the same issue, let's follow discussions there. Closing this own hence as duplicate.

**Comment by mbiebl** [comment]
@dvdhrm I built the latest git master including 281033284352ed7651e84d228dad780dc2ef299f and I can no longer reproduce the problem.

**Comment by mbiebl** [comment]
@dvdhrm That said, there are a multitude of commits. If I wanted to fix that for v222, which commits would I have to cherry-pick?

**Comment by dvdhrm** [comment]
Already discussed on IRC: We are going to release 223 soon. If you plan to use 222 in a distro, I recommend reverting the two changes on logind. They're only required if you run kdbus (or, generally, if you run GUI tools from withint `--user` units).
