### ISSUE TITLE
Send dhcp options with networkd

### ISSUE THREAD

**Issue by Toniob** [systemd/systemd#5134]
### Submission type

  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> debian testing (stretch)

I'm trying to switch from NetworkManager to networkd on my debian router.
My ISP needs a specific configuration to accept DHCP request and send back my ip address. Currently, with NM, I use a /etc/dhclient-orange.conf which is used to send dhcp options. The content of the file is this one :

send dhcp-client-identifier 01:xx:xx:xx:xx:xx:xx;
send vendor-class-identifier "sagem";
send user-class "+FSVDSL_livebox.Internet.softathome.Livebox3";
option rfc3118-authentication code 90 = string;
send rfc3118-authentication 00:00:00:00:00:00:00:00:00:00:00:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx;
request subnet-mask, routers, domain-name-servers, domain-name, broadcast-address, dhcp-lease-time, dhcp-renewal-time, dhcp-rebinding-time, rfc3118-authentication;

From what I understand, networkd can send ClientIdentifier and VendorClassIdentifier dhcp options. Will it be possible to had the other ones, or even better, being able to send custom options, like dhclient permits ?

**Comment by susanin-ivan** [comment]
Hi,

How do I make systemd-networked to send  "request subnet-mask, routers, domain-name-servers, domain-name, broadcast-address, dhcp-lease-time, dhcp-renewal-time, dhcp-rebinding-time, rfc3118-authentication;" to DHCP server on DHCP request???

I did not found any way to request options beside already defined (but useless for given situation)...

**This is request system send to DHCP - bad, as option 119 does not requested :**

  TIME: 2018-03-28 15:58:03.007
    IP: 10.137.86.11 (0:50:56:1b:56:b) > 10.7.77.122 (0:0:5e:0:1:1)
    OP: 1 (BOOTPREQUEST)
 HTYPE: 1 (Ethernet)
  HLEN: 6
  HOPS: 0
   XID: 807bef2d
  SECS: 10347
 FLAGS: 0
CIADDR: 10.137.86.11
YIADDR: 0.0.0.0
SIADDR: 0.0.0.0
GIADDR: 0.0.0.0
CHADDR: 00:50:56:1b:56:0b:00:00:00:00:00:00:00:00:00:00
 SNAME: .
 FNAME: .
OPTION:  53 (  1) DHCP message type         3 (DHCPREQUEST)
OPTION:  61 ( 19) Client-identifier         ff:bc:9a:4a:2d:00:02:00:00:ab:11:89:1f:d3:0a:71:81:69:59
OPTION:  55 (  9) Parameter Request List      1 (Subnet mask)
                                              3 (Routers)
                                             12 (Host name)
                                             15 (Domainname)
                                              6 (DNS server)
                                             33 (Static route)
                                            121 (Classless Static Route)
                                             42 (NTP servers)
                                            101 (MDHCP)
                                            
OPTION:  57 (  2) Maximum DHCP message size 576
OPTION:  12 ( 11) Host name                 l-hyu04-011

**And reply - also bad, as no search-domains returned:**
---------------------------------------------------------------------------

  TIME: 2018-03-28 15:58:03.007
    IP: 10.7.77.122 (b4:99:ba:3c:2:0) > 10.137.86.11 (0:50:56:1b:56:b)
    OP: 2 (BOOTPREPLY)
 HTYPE: 1 (Ethernet)
  HLEN: 6
  HOPS: 0
   XID: 807bef2d
  SECS: 10347
 FLAGS: 0
CIADDR: 10.137.86.11
YIADDR: 10.137.86.11
SIADDR: 10.7.77.108
GIADDR: 0.0.0.0
CHADDR: 00:50:56:1b:56:0b:00:00:00:00:00:00:00:00:00:00
 SNAME: .
 FNAME: pxelinux.0.
OPTION:  53 (  1) DHCP message type         5 (DHCPACK)
OPTION:  54 (  4) Server identifier         10.7.77.122
OPTION:  51 (  4) IP address leasetime      3600 (60m)
OPTION:   1 (  4) Subnet mask               255.255.0.0
OPTION:   3 (  4) Routers                   10.137.0.1
OPTION:  12 ( 11) Host name                 l-hyu04-011
OPTION:  15 ( 13) Domainname                some.domain.name
OPTION:   6 ( 16) DNS server                10.7.77.192,10.x.x.x,10.3x.x.x,10.2x.x.x
OPTION:  42 (  4) NTP servers               10.x.x.134
---------------------------------------------------------------------------

**This is request system send to DHCP by dhclient - good + option 119 requested :**

  TIME: 2018-03-28 15:58:48.247
    IP: 10.137.86.11 (0:50:56:1b:56:b) > 10.7.77.122 (0:0:5e:0:1:1)
    OP: 1 (BOOTPREQUEST)
 HTYPE: 1 (Ethernet)
  HLEN: 6
  HOPS: 0
   XID: 464dc056
  SECS: 0
 FLAGS: 0
CIADDR: 10.137.86.11
YIADDR: 0.0.0.0
SIADDR: 0.0.0.0
GIADDR: 0.0.0.0
CHADDR: 00:50:56:1b:56:0b:00:00:00:00:00:00:00:00:00:00
 SNAME: .
 FNAME: .
OPTION:  53 (  1) DHCP message type         3 (DHCPREQUEST)
OPTION:  12 ( 11) Host name                 l-hyu04-011
OPTION:  55 ( 13) Parameter Request List      1 (Subnet mask)
                                             28 (Broadcast address)
                                              2 (Time offset)
                                              3 (Routers)
                                             15 (Domainname)
                                              6 (DNS server)
                                            119 (Domain Search)
                                             12 (Host name)
                                             44 (NetBIOS name server)
                                             47 (NetBIOS scope)
                                             26 (Interface MTU)
                                            121 (Classless Static Route)
                                             42 (NTP servers)
---------------------------------------------------------------------------
                                            
**And a good reply:**

  TIME: 2018-03-28 15:58:48.247
    IP: 10.7.77.122 (b4:99:ba:3c:2:0) > 10.137.86.11 (0:50:56:1b:56:b)
    OP: 2 (BOOTPREPLY)
 HTYPE: 1 (Ethernet)
  HLEN: 6
  HOPS: 0
   XID: 464dc056
  SECS: 0
 FLAGS: 0
CIADDR: 10.137.86.11
YIADDR: 10.137.86.11
SIADDR: 10.7.77.108
GIADDR: 0.0.0.0
CHADDR: 00:50:56:1b:56:0b:00:00:00:00:00:00:00:00:00:00
 SNAME: .
 FNAME: pxelinux.0.
OPTION:  53 (  1) DHCP message type         5 (DHCPACK)
OPTION:  54 (  4) Server identifier         10.7.77.122
OPTION:  51 (  4) IP address leasetime      3600 (60m)
OPTION:   1 (  4) Subnet mask               255.255.0.0
OPTION:  28 (  4) Broadcast address         10.137.255.255
OPTION:   3 (  4) Routers                   10.137.0.1
OPTION:  15 ( 13) Domainname               some.domain.name
OPTION:   6 ( 16) DNS server                10.7.77.192,10.x.x.x,10.3x.x.x,10.2x.x.x
OPTION: 119 ( 54) Domain Search             xxxxxxxxxxxxxxxx .xxx.xx
                                            xxxxxxxxxxxxxxxx x.xxx..
                                            xxxxxxxxxxxxxxxx xxxx.xxx
                                            xxxxxxxxxxxxxxxx x..xxxx.
                                            xxxxxxxxxxxxxxxx .xxx.xxx
                                            xxxxxxxxxxxxxxxx .xxx.xx
                                            xxxxxxxxxxxxxxxx x.xxx.
OPTION:  12 ( 11) Host name                 l-hyu04-011
OPTION:  42 (  4) NTP servers               10.7.77.134
---------------------------------------------------------------------------

**Comment by susanin-ivan** [comment]
That it, as usual - no response from systemD devs... 
To break - you are first, to fix - you are not here...

**Comment by bluca** [comment]
Would adding the following new options to network conf files be an acceptable solution?

[dhcp]
SendOptions=key0:value key1:value
RequestOptions=key2 key3

This is very similar to what busybox's udhcp client, for example, already provides: https://git.busybox.net/busybox/tree/networking/udhcp/dhcpc.c#n1228

There are many use cases where nodes in a datacentre need to send (or request) raw options via dhcp, and currently there's no way to do that via systemd-networkd. And given one can't use systemd-networkd with an external dhcp client, the only available solution is to stop using networkd entirely, which is a pity.

I'd be happy to do the work and send a PR with the implementation, if the above approach is acceptable.

**Comment by susanin-ivan** [comment]
Hi bluca,

As you can see, one year plus passed already - nobody gives a sh.t! 
SystemD devs break stuff to right and left and did not bother to fix it, but pushing useless systemD junk into every linux system it can reach... 

The best solution for now - run away from that junkD infected system and use normal sysV approach. 
**At least everything will work as it should, without broken by some curved hands system daemons and services...**

Br,
Ivan

**Comment by susanin-ivan** [comment]
Yes, and that is the way to accept criticism - just delete it.
Right, that is the way.

What a miserable and childish behaviouir...

**Comment by susanin-ivan** [comment]
With all respect to devs, but if you break something working for years, then ignore what user reports - don't be surprised that people hate your product and advocate against it...

**Comment by susanin-ivan** [comment]
Pfffff... 
You have no balls to accept responsibility. Well. Good luck in your hard way.
