### ISSUE TITLE
systemd reports "bad" unit file state for instantiated unit file alias names

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#5136]
### Submission type
  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with
current master

### Used distribution
Fedora Rawhide (nspawn container)

### In case of bug report: Expected behaviour you didn't see
Output of ```systemctl list-unit-files``` shouldn't list unit files being in "bad" state unless there is really something wrong with them.

### In case of bug report: Unexpected behaviour you saw
$subject 

### In case of bug report: Steps to reproduce the problem
Have following unit files present, 

```
$ systemctl list-unit-files getty*
UNIT FILE      STATE  
getty@.service enabled
getty.target   static 

2 unit files listed.
```

Then create following symlink and reload systemd,

```
$ ln -s /usr/lib/systemd/system/getty@.service /usr/lib/systemd/system/getty@tty9.service
$ systemctl daemon-reload
```

Observe that systemd claims that ```getty@tty9.service``` unit file is in a "bad" state. However that unit file is perfectly fine, since it is an alias to ```getty@.service``` and we didn't do anything with ```getty@.service``` template.

```
$ systemctl list-unit-files getty*
UNIT FILE          STATE  
getty@.service     enabled
getty@tty9.service bad              <--- BUG
getty.target       static 
```

**Comment by poettering** [comment]
Fix waiting in #5263.

**Comment by piotr-dobrogost** [comment]
When would someone want to instantiate template in /usr/lib?

**Comment by ecki** [comment]
This also happens for init.d-compatible generated units (at least in SLES12.2 syystemd228)

    Loaded: loaded  (/etc/init.d/srv; bad; vendor preset: disabled)

**Comment by keszybz** [comment]
228 is very old (and actually predates #5263).

**Comment by asiro85** [comment]
Well, I noticed that different symbolic links (serv1.service and serv2.service) in the etc/systemd/system directory must not point to files with the same name (serv.service), even if they are in different directories. It's been a long time, but maybe this will help someone.
