### ISSUE TITLE
autocompletion for "systemctl show --property=" is borked

### ISSUE THREAD

**Issue by agross** [systemd/systemd#5137]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 231
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Fedora 25

### In case of bug report: Expected behaviour you didn't see

I want to show the `EnvironmentFile` property value of a unit:

```
$ systemctl show nginx.service | grep EnvironmentFile
EnvironmentFile=/usr/local/src/systemd-docker-nginx/nginx.service.conf (ignore_errors=no)
```

The expected output would thus be `/usr/local/src/systemd-docker-nginx/nginx.service.conf`.

### In case of bug report: Unexpected behaviour you saw

```
$ systemctl show -p EnvironmentFile nginx.service
Property EnvironmentFile does not exist.
```

### In case of bug report: Steps to reproduce the problem

1. Create service unit `foo.service`
1. `systemctl edit foo.service`
1. In the editor, add 
   ```
   [Service]
   EnvironmentFile=/usr/local/src/systemd-docker-nginx/nginx.service.conf
   ```
1. Run commands above

**Comment by evverx** [comment]
> Property EnvironmentFile does not exist

Try:
```sh
systemctl show -p EnvironmentFiles
```

See 33d2308c1fb8d18400
> Note that the properties shown by the command are generally more low-level, normalized versions of the original configuration settings and expose runtime state in addition to configuration.

**Comment by agross** [comment]
@evverx Thank you. 

In this case I think systemctl should suggest variable  names. From the man page (which I read before posting here) I didn't get the idea to append the "magic `s`". While it technically isn't a bug, I think it's a usability issue. Do you agree?

**Comment by evverx** [comment]
> From the man page (which I read before posting here) I didn't get the idea to append the "magic s"

Indeed, that's not so obvious. You can run
```
busctl introspect org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/nginx_2eservice
```
to get all "raw" properties.

> While it technically isn't a bug, I think it's a usability issue

Well, `systemctl show -p Environment<TAB>` shows
```
Environment      EnvironmentFile
```
So, autocompletion is broken.

**Comment by evverx** [comment]
@agross , feel free to edit the description. I'm not sure that "systemctl show --property does not show drop-in properties" is right

**Comment by fsateler** [comment]
`systemctl show` is supposed to be for machine consumption, wouldn't this break consumers? 

Also, completion uses `systemd --dump-configuration-items`:

```
% systemd --dump-configuration-items | grep EnvironmentFile
EnvironmentFile=FILE
EnvironmentFile=FILE
EnvironmentFile=FILE
EnvironmentFile=FILE
```

**Comment by poettering** [comment]
I am pretty sure we should not automatically search for related options. This is a machine readable interface, not more. Talking about user-friendliness here doesn't sound right.

If the autocompletion is borked, then that's a bug though, and should be fixed.
