### ISSUE TITLE
Systemd-networkd drop-in conf directory -- configs overwrite each other

### ISSUE THREAD

**Issue by msg7086** [systemd/systemd#5141]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

> systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Debian Stretch
> systemd                       232-8                       amd64

### In case of bug report: Expected behaviour you didn't see

> All files in drop-in directory (`*.network.d/*.conf`) should take effects.
That being said, if I have 2 IP address and 2 routing rules in each of 2 files, I should get 4 addresses and 4 rules.

### In case of bug report: Unexpected behaviour you saw

> Configs sort of randomly overwrite each other.

### In case of bug report: Steps to reproduce the problem

1. Go to working directory `/etc/systemd/network/`

2. Create `internal.network`
```
[Match]
Name=ens160

[Network]
Address=100.64.10.1/10
```

3. Create `internal.network.d/`

4. Create `internal.network.d/a.conf`
```
[Address]
Address=100.64.123.33/10

[Address]
Address=100.64.123.37/10

[Address]
Address=100.64.123.39/10
```

5. Create `internal.network.d/b.conf`
```
[Address]
Address=100.64.43.222/10

[Route]
Destination=12.12.12.0/24
Gateway=100.64.11.22

[Address]
Address=100.64.43.226/10
```

6. Run `systemctl restart systemd-networkd`

7. Run `ip a`

8. Unexpectedly see the following
```
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:50:56:14:ac:d2 brd ff:ff:ff:ff:ff:ff
    inet 100.64.10.1/10 brd 100.127.255.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet 100.64.43.222/10 brd 100.127.255.255 scope global secondary ens160
       valid_lft forever preferred_lft forever
    inet 100.64.123.37/10 brd 100.127.255.255 scope global secondary ens160
       valid_lft forever preferred_lft forever
    inet 100.64.123.39/10 brd 100.127.255.255 scope global secondary ens160
       valid_lft forever preferred_lft forever
    inet 100.64.43.226/10 brd 100.127.255.255 scope global secondary ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe14:acd2/64 scope link 
       valid_lft forever preferred_lft forever
```

9. Same issue arises when you have multiple routing rules in multiple drop-in files, i.e., `(Route) + (Route) = 1 Route`; `(Match + Route) + (Route) = 2 Routes`, `(Match + Route) + (Match + Route) = 1 Route`, etc.

**Comment by msg7086** [comment]
Having our engineering team spent couple hours did we find the potential cause.

The code parsing multiple config files seems to record section header with their line numbers, and if 2 headers happen to be sitting on the same line number in two different files, the former one gets overwritten by the latter. A workaround for this is to add enough new lines on top of the second file, and then it works as expected -- assigning all addresses and routes to the nic.

**Comment by ssahani** [comment]
The conf should be like this . 


internal.network.d/a.conf
```
[Network]
Address=100.64.123.33/10
Address=100.64.123.37/10
Address=100.64.123.39/10
```

Since internal.network you have defined in the [Network] section.

**Comment by mybaldbird** [comment]
Clearly there are multiple ways to write the drop-ins for msg's example, but that doesn't change the fact that there is a bug. It was written that way merely for illustration. The bug can be worked around by simply padding the file with empty lines.

**Comment by msg7086** [comment]
@ssahani Originally the problem was discovered due to multiple sections of `[Route]` that overwrites each other rules. We used `[Address]` for demonstration purpose as they behaved the same and is easier to read.

**Comment by poettering** [comment]
looks like a bug in networkd indeed.

**Comment by ssahani** [comment]
If I read the code write the `[Address]` section is not designed to handle multiple addresses. Rather the `[Network]` section for it  .

FIrst we put all the addresses from the `[Network]` section into the hash table and we add to the interface.  `[Address]`  section is used to configure options such as `Peer=` `Label=` which should be unique.

```
[Address] Section Options
Specify several "[Address]" sections to configure several addresses.
```
which I interpret as each `[Address]` section from each static address .

**Comment by msg7086** [comment]
@ssahani That would be a bit off-topic as we are discussing a bug that has a workaround of padding with some empty lines. If what you said is the problem, simply padding lines shouldn't have corrected the problem.

---

Let me explain it more precisely,
```
# a.conf
[Address]
Address=AAAAA
```

```
# b.conf
[Address]
Address=BBBBB
```
↑ This results in only latter address being configured.
```
# b.conf
# A blank line or a comment or whatever, try it yourself ;) -- resulting the section header to be 1 line off from the one in a.conf
[Address]
Address=BBBBB
```
↑ This results in both addresses being configured.

---

Besides, I would say allowing addresses to be specified only in `[Address]` section would make more sense.

---

And again as I explained before, we discovered the issue when we were testing multiple `[Route]` sections in drop-in directory, and your comment won't apply to that. We just found that `[Address]` sections **also** have that same problem **after** we discovered the phenomenon, as well as **all other sections that are allowed to be specified multiple times** if any in the future.

**Comment by ssahani** [comment]
The reason why it's working it we keep track of the line numbers of the 
`[Address]` section . When you are padding it thinks it's a new `[Address]` section not the same one.
And this one inserted to the static addresses.

So let's say file `a.conf`  line number 10 we put a address section into the HT. Next time another file `b.conf`  line number we try to get the `[Address]` section by line which is 10 we find the `[Address]` section and we are overwriting this one . So the last one always there.

Need to have unique line numbers  while reading dropin files.

**Comment by msg7086** [comment]
Yes, that's exactly what we are reporting. As an end user, I think overwriting by line number does not make much sense in this use case, and would hope to see it fixed.

Thank you.

**Comment by poettering** [comment]
@ssahani this is broken in networkd since support for dropins was added. Using the line number alone is simply broken. It's a bug in networkd. And yes, of course multiple Address= and [Address] sections are permissible and support. And if things break then, then it's a bug that needs fixing.
