### ISSUE TITLE
Support vxlan unicast configuration

### ISSUE THREAD

**Issue by joejulian** [systemd/systemd#5145]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch

Sometimes network providers do not allow multicast communication. In this instance, vxlans need to be configured using multiple unicast endpoints. This is done by appending additional zero MAC entries to the fdb.

Please add support for configuring these in netdev.

**Comment by ssahani** [comment]
Could you please give a example for  it ? Thanks !

**Comment by joejulian** [comment]
https://joejulian.name/blog/how-to-configure-linux-vxlans-with-multiple-unicast-endpoints/

**Comment by joejulian** [comment]
I would expect to configure it such as:

```
[VXLAN]
Id=42
Endpoint=10.0.0.1
Endpoint=10.1.0.1
Endpoint=10.2.0.1
```

**Comment by ssahani** [comment]
> https://joejulian.name/blog/how-to-configure-linux-vxlans-with-multiple-unicast-endpoints/

since it's a bridge fdb I have added to the ```[BridgeFDB]``` section also Please see the example conf how to apply to vxlan.
