### ISSUE TITLE
[RFE] teach systemd-cgls to show hierarchy of the specified unit

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#5156]
Currently (systemd master, commit a27f0651a06c3ad13bcafe72566479482c846532) ```systemd-cgls``` shows the complete hierarchy, it would be nice if it could take a unit and only show the hierarchy for that specific unit, i.e. the user.slice.

**Comment by evverx** [comment]
Why not
```
systemd-cgls /user.slice
```
?
Or something like this
```
systemd-cgls $(systemctl show -p ControlGroup --value user.slice)
```
?

**Comment by jsynacek** [comment]
The first is only really usable (read user friendly) for the top level slices. I know about the latter, but that's pretty cumbersome and besides that, you have to distinguish between ```systemctl``` and ```systemctl --user```.  Consider, for example, this:
```
systemd-cgls $(systemctl show -p ControlGroup --value --user gnome-terminal-server.service)
```
It would be much more usable if I could just use ```systemd-cgls gnome-terminal-server.service``` and it would figure out the rest for me.

**Comment by poettering** [comment]
well, we already have "systemd-cgls --machine=", hence adding "systemd-cgls --unit=" would indeed make a lot of sense.

**Comment by keszybz** [comment]
I'm working on it.

**Comment by poettering** [comment]
btw... "systemd-cgls --user=" and "systemd-cgls --session=" might make sense too, using the relevant info from logind... ;-)

**Comment by evverx** [comment]
Regarding `--machine`.
`systemd-cgls --machine some-machine` doesn't work as expected sometimes: https://github.com/systemd/systemd/pull/3965#issuecomment-259845768

How will `systemd-cgls --machine some-machine --service some-service` work?

**Comment by poettering** [comment]
> How will systemd-cgls --machine some-machine --service some-service work?

Well, one can make things as complicated as one wants... For the beginning I'd either suggest that this results in an error, or is treated as if --machine=, --service=, --session= and --user= are exclusive to each other, and only one of them is honoured... Yeah, systemd-cgls could also enter the container and retrieve the data there, but I am not sure this complexity is really warranted for now...

**Comment by keszybz** [comment]
Yeah, `-M`  + `-u` is out of scope. We'd need to communicate with systemd inside of the container, and I have no appetite for that.
