### ISSUE TITLE
systemd-networkd does not accept IPv6 RAs on bond interface

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#5161]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian stretch

### In case of bug report: Expected behaviour you didn't see

> Configuring a `bond0` interface should cause the interface to appear with accepted router advertisements, say `/proc/sys/net/ipv6/conf/bond0/accept_ra` shouldn't be `0`

### In case of bug report: Unexpected behaviour you saw

> /proc/sys/net/ipv6/conf/bond0/accept_ra is 0, even after explicitly setting `IPv6AcceptRA=yes` in the `bond0.network` file. This will cause the bond device to not accept any IPv6 router advertisements, this killing IPv6 connectivity.

### In case of bug report: Steps to reproduce the problem
`bond0.netdev`
```
[NetDev]
Name=bond0
Kind=bond

[Bond]
Mode=802.3ad
MIIMonitorSec=1s
LACPTransmitRate=fast
UpDelaySec=2s
DownDelaySec=8
```

`bond0.network`
```
[Match]
Name=bond0

[Network]
DHCP=yes
IPv6AcceptRA=yes
```

`en_add_to_bond0.network`
```
[Match]
Name=en*

[Network]
Bond=bond0
DHCP=no
```

**Comment by ssahani** [comment]
`networkd`  handles router advertisements by itself hence we write `0` to proc.
More see `link_set_ipv6_accept_ra`.

```
9: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 28:d2:44:b0:6a:32 brd ff:ff:ff:ff:ff:ff
    inet 10.XX.XX.110/23 brd 10.65.193.255 scope global dynamic bond0
       valid_lft 86393sec preferred_lft 86393sec
    inet6 2001:db8:1:0:2ad2:44ff:feb0:6a32/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 86392sec preferred_lft 14392sec
    inet6 fe80::2ad2:44ff:feb0:6a32/64 scope link 
       valid_lft forever preferred_lft foreve

```

**Comment by flokli** [comment]
>`networkd`  handles router advertisements by itself hence we write `0` to proc.
>More see `link_set_ipv6_accept_ra`.

Missed this, thanks for the hint! It seems like I there is also weird
interaction with ancient switch hardware on the other side going on,
probably looping the machine's own neighbor solicitation packets back
via the other port, causing IPv6 DAD detection to kick in…
I will close this issue for now and test with another switch, highly
likely this one is the culprit :-D
