### ISSUE TITLE
nspawn: Allow whitelisting syscalls in seccomp filter

### ISSUE THREAD

**Issue by nhlfr** [systemd/systemd#5163]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> every version

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora

systemd-nspawn has a defined list of syscalls which are blocked by seccomp:

https://github.com/systemd/systemd/blob/8d3eafa161af22bb04dc0210885ffe79560a59ee/src/nspawn/nspawn-seccomp.c

However, sometimes users would like to whitelist some of them. The good example is keyctl. This syscall is needed i.e. when you want to execute runc inside systemd-nspawn container, because runc is using it. This could be useful i.e. for "nested containerization" (running Docker/runc inside nspawn).

What I would like to propose is to have a CLI arg like `--whitelist-seccomp-syscalls` in which user could provide syscalls which he/she would like to use and not include in the seccomp filter.

**Comment by lucab** [comment]
A similar request coming from a rkt usecase https://github.com/coreos/rkt/issues/3557.

**Comment by poettering** [comment]
Sounds like a great thing to add.

**Comment by poettering** [comment]
In fact, I figure nspawn should provide a generic SystemCallFilter= setting, much like service units have it, and both permit adding and removing syscalls from the list. Doing that should be relatively straighforward as much of the difficult stuff is already available in seccomp-util.c seccomp_add_syscall_filter_set() and friends...

**Comment by evverx** [comment]
> However, sometimes users would like to whitelist some of them. The good example is keyctl. This syscall is needed i.e. when you want to execute runc inside systemd-nspawn container, because runc is using it.

[Given that allowing `keyctl` can make `systemd` unusable inside a container](https://github.com/systemd/systemd/pull/6876), I'm a bit puzzled about
* why `--no-new-keyring` isn't passed when `runc` is launched inside a container with blocked `keyctl`
* why `runc` fails when `keyctl` returns `EPERM`

Would it make more sense to advise users to pass `no-new-keyring` instead of unblocking `keyctl`?
