### ISSUE TITLE
please downgrade logging about masked units that cannot be added to a transaction

### ISSUE THREAD

**Issue by wavexx** [systemd/systemd#5179]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232

### Used distribution

> debian unstable

Debian ships with a system-wide user socket for the gnupg-agent in ``/usr/lib/systemd/user/gpg-agent.socket``. This is all fine and dandy, but on server systems I want to mask these without deleting the package's files.

First, there's no way to mask these from systemctl mask. You can create links manually in /etc/systemd/user, but then systemd emits a warning for each new user session:

    systemd[1604]: gpg-agent-ssh.socket: Cannot add dependency job, ignoring: Unit gpg-agent-ssh.socket is masked.

Since I disabled this intentionally, I consider the warning inappropriate.

**Comment by poettering** [comment]
So, is this simply about the log level?

**Comment by poettering** [comment]
And are you saying "systemctl mask --user gpg-agent.socket" doesn't work for you?

**Comment by wavexx** [comment]
On Wed, Feb 01 2017, Lennart Poettering wrote:
> And are you saying "systemctl mask --user gpg-agent.socket" doesn't work for you?

Please note: this disables gpg-agent.socket for the current user only.
I want to disable it for _all_ users by default.

**Comment by poettering** [comment]
doesn't "systemctl mask --global gpg-agent.socket" work for you?

**Comment by wavexx** [comment]
On Wed, Feb 01 2017, Lennart Poettering wrote:
> doesn't "systemctl mask --global gpg-agent.socket" work for you?

I wasn't aware of global - sorry. Yes, this creates the symlink
correctly. At this point, like you say, if the unit is masked globally,
it's just an issue of the logging level. It shouldn't warn.

**Comment by poettering** [comment]
So, I am not entirely sure I agree with downgrading this to nothing. masking after all is an exceptional operation, it always is kind of a "hack", not the default... Due to this we currently log at LOG_WARNING about it... I'd be open to downgrading this to LOG_NOTICE, or even LOG_INFO, but LOG_DEBUG appears too low...

**Comment by wavexx** [comment]
On Wed, Feb 01 2017, Lennart Poettering wrote:
> So, I am not entirely sure I agree with downgrading this to nothing.
> masking after all is an exceptional operation, it always is kind of a
> "hack", not the default... Due to this we currently log at LOG_WARNING

I cannot fully agree here. I mask several units for multiple reasons.
Packages may ship unit files that make no sense in your setup. This is
no different than customization. masking is a first class operation for
me.

> about it... I'd be open to downgrading this to LOG_NOTICE, or even
> LOG_INFO, but LOG_DEBUG appears too low...

The main issue that I have is that this warning gets triggered at *each*
new user session, for something that is absolutely intentional on my
part. In the case of debian's gnupg-agent, counting all sockets (5), and
a marginal user count (~40 users) this creates an unduly amount of
useless warnings that are downright bogus for my setup.

I actually decided to elide the unit files directly with a post-install
hook to silence it, and *that* is a hack.

**Comment by poettering** [comment]
> I cannot fully agree here. I mask several units for multiple reasons. Packages may ship unit files that make no sense in your setup. This is no different than customization. masking is a first class operation for me.

Well, for that level of configuration we have "systemctl enable" and "systemctl disable". 

Enabling/disabling is the regular operation. "systemctl mask" however, is the heavy hammer you normally don't need. And if you do, then you are already outside of the intended use...

**Comment by wavexx** [comment]
On Wed, Feb 01 2017, Lennart Poettering wrote:
>> I cannot fully agree here. I mask several units for multiple reasons.
>> Packages may ship unit files that make no sense in your setup. This
>> is no different than customization. masking is a first class
>> operation for me.
>
> Well, for that level of configuration we have "systemctl enable" and "systemctl disable".

How do I disable the socket activation of an unit which is packaged like
this without resorting to mask?

/usr/lib/systemd/user/gpg-agent.socket
/usr/lib/systemd/user/sockets.target.wants/gpg-agent.socket

**Comment by poettering** [comment]
well, they shouldn't package it like that, but instead ship this with an [install] section and enable it at package install time with "systemctl preset --global gpg-agent.socket"... that you way can "systemctl disable --global gpg-agent.socket" whenever you like.

**Comment by keszybz** [comment]
Yeah, that's clearly a bug in packaging.

Nevertheless, I agree we should downgrade the warning. After all, we're warning as a result of an explicit configuration choice made by the admin, which isn't very useful: if they decided to mask some unit, they probably had a reason.

**Comment by poettering** [comment]
@keszybz i can accept that.

**Comment by keszybz** [comment]
Actually, the original report was wrong: we already downgraded the warning to info a while back. There was some mismatch in error codes, I'll submit a PR to clean that up, but in the few cases I checked, we always use log_info. Nothing to do here.

**Comment by keszybz** [comment]
See #5204.
