### ISSUE TITLE
systemd does not serialize/deserialize the ExecStart= or ExecStartPre= line number across daemon reloads

### ISSUE THREAD

**Issue by antoineco** [systemd/systemd#518]
(systemd 220)

I use a systemd unit to load and start fleet units inside a CoreOS cluster. The unit is pretty straightforward but I observe strange behaviours with successive `ExecStart` directives:

```
[Unit]
Description=Deploy Kubernetes units via fleet
Requires=fleet.service
After=fleet.service

[Service]
ExecStart=/usr/bin/bash -c '/usr/bin/fleetctl load /opt/fleet/*.service'
ExecStart=/usr/bin/fleetctl start \
    kube-apiserver.service \
    kube-scheduler.service \
    kube-controller-manager.service \
    kubelet.service \
    kube-proxy.service
Type=oneshot
RemainAfterExit=true
```

The first `ExecStart` exits in 2-3s but the second `ExecStart` is not executed, the unit simply exits after the first command:

```
# systemctl status kube-fleet
● kube-fleet.service - Deploy Kubernetes units via fleet
   Loaded: loaded (/etc/systemd/system/kube-fleet.service; static; vendor preset: disabled)
   Active: active (exited) since Wed 2015-07-08 14:01:23 UTC; 2s ago
 Main PID: 1230 (code=exited, status=0/SUCCESS)

Jul 08 14:01:21 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Triggered global unit kubelet.service load
Jul 08 14:01:21 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Triggered global unit provision-k8s-secrets.service load
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit kube-scheduler.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit kube-controller-manager.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit generate-k8s-certs.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit generate-k8s-tokens.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit kube-addons.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit kube-apiserver.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal bash[1230]: Unit get-kubectl.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:01:23 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Started Deploy Kubernetes units via fleet.
```

It works if I replace the first `ExecStart` directive with `ExecStartPre`:

```
# systemctl status kube-fleet
● kube-fleet.service - Deploy Kubernetes units via fleet
   Loaded: loaded (/etc/systemd/system/kube-fleet.service; static; vendor preset: disabled)
   Active: active (exited) since Wed 2015-07-08 14:04:43 UTC; 2s ago
  Process: 1416 ExecStart=/usr/bin/fleetctl start kube-apiserver.service kube-scheduler.service kube-controller-manager.service kubelet.service kube-proxy.service (code=exited, status=0/SUCCESS)
  Process: 1392 ExecStartPre=/usr/bin/bash -c /usr/bin/fleetctl load /opt/fleet/*.service (code=exited, status=0/SUCCESS)
 Main PID: 1416 (code=exited, status=0/SUCCESS)

Jul 08 14:04:41 ip-10-0-21-132.eu-west-1.compute.internal bash[1392]: Unit kube-scheduler.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:04:41 ip-10-0-21-132.eu-west-1.compute.internal bash[1392]: Unit kube-apiserver.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:04:41 ip-10-0-21-132.eu-west-1.compute.internal bash[1392]: Unit generate-k8s-tokens.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:04:41 ip-10-0-21-132.eu-west-1.compute.internal bash[1392]: Unit kube-addons.service loaded on 3d5044dd.../10.0.21.132
Jul 08 14:04:41 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1416]: Triggered global unit kubelet.service start
Jul 08 14:04:41 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1416]: Triggered global unit kube-proxy.service start
Jul 08 14:04:43 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1416]: Unit kube-apiserver.service launched on 3d5044dd.../10.0.21.132
Jul 08 14:04:43 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1416]: Unit kube-controller-manager.service launched on 3d5044dd.../10.0.21.132
Jul 08 14:04:43 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1416]: Unit kube-scheduler.service launched on 3d5044dd.../10.0.21.132
Jul 08 14:04:43 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Started Deploy Kubernetes units via fleet.
```

From my understanding of the [documentation](http://www.freedesktop.org/software/systemd/man/systemd.service.html) both directives should behave the same way as long as the Service type is `oneshot`.

Another confusing detail: if I replace the first `ExecStart` by another, faster to execute, bash command like `bash -c 'echo hello'` both commands are executed.

**Comment by zonque** [comment]
Is that the same issue as #493 ?
Not sure why that would be systemd's fault - could you try the simple unit file listed in the other issue?

**Comment by antoineco** [comment]
Isn't systemd supposed to invoke each `ExecStart` command sequentially until it meets a non-zero exit code? Even though it is not systemd's fault, it doesn't explain why `ExecStart` and `ExecStartPre` behave differently inside a oneshot service.

The test unit works just fine:

```
$ systemctl cat test.service
# /etc/systemd/system/test.service
[Service]
Type=oneshot
ExecStartPre=-/usr/bin/echo ExecStartPre 1
ExecStartPre=-/usr/bin/echo ExecStartPre 2
ExecStartPre=-/usr/bin/echo ExecStartPre 3
ExecStart=-/usr/bin/echo ExecStart
ExecStartPost=-/usr/bin/echo ExecStartPost 1
ExecStartPost=-/usr/bin/echo ExecStartPost 2
ExecStartPost=-/usr/bin/echo ExecStartPost 3

core@ip-10-0-21-132 ~ $ sudo systemctl start test.service

core@ip-10-0-21-132 ~ $ systemctl status test.service
● test.service
   Loaded: loaded (/etc/systemd/system/test.service; static; vendor preset: disabled)
   Active: inactive (dead)

Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Starting test.service...
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4583]: ExecStartPre 1
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4586]: ExecStartPre 2
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4588]: ExecStartPre 3
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4589]: ExecStart
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4590]: ExecStartPost 1
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4597]: ExecStartPost 2
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal echo[4599]: ExecStartPost 3
Jul 08 17:21:54 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Started test.service.
```

**Comment by arvidjaar** [comment]
> Is that the same issue as #493 ?

On the first glance, not quite - in #493 commands are executed. Log with debug level would be useful.

**Comment by antoineco** [comment]
I'd be glad to post it. Would it be enough to add `LogLevel=debug` to _system.conf_? When I do so I can't see any difference in the journal after a reboot.

**Comment by zonque** [comment]
Just add `debug` to your kernel command line parameters.

**Comment by antoineco** [comment]
Thanks @zonque. I think that's the best I have right now:

```
Jul 08 18:55:12 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Collecting.
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Trying to enqueue job kube-fleet.service/start/replace
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Installed new job kube-fleet.service/start as 2231
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Enqueued job kube-fleet.service/start as 2231
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: About to execute: /usr/bin/bash -c '/usr/bin/fleetctl load /opt/fleet/*.service'
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Forked /usr/bin/bash as 1041
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Changed dead -> start
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Starting Deploy Kubernetes units via fleet...
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal systemd[1041]: kube-fleet.service: Executing: /usr/bin/bash -c '/usr/bin/fleetctl load /opt/fleet/*.service'
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Triggered global unit consume-k8s-tokens.service load
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Triggered global unit kube-proxy.service load
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Triggered global unit kubelet.service load
Jul 08 18:55:35 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Triggered global unit provision-k8s-secrets.service load
Jul 08 18:55:38 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Reinstalled deserialized job kube-fleet.service/start as 2231
Jul 08 18:55:38 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Changed dead -> start
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit generate-k8s-certs.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit get-kubectl.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit generate-k8s-tokens.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit kube-addons.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit kube-apiserver.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit kube-controller-manager.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal bash[1041]: Unit kube-scheduler.service loaded on 3d5044dd.../10.0.21.132
Jul 08 18:55:39 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Started Deploy Kubernetes units via fleet.
```

```
# systemctl status kube-fleet -l
● kube-fleet.service - Deploy Kubernetes units via fleet
   Loaded: loaded (/etc/systemd/system/kube-fleet.service; static; vendor preset: disabled)
   Active: active (exited) since Wed 2015-07-08 19:03:10 UTC; 17s ago
 Main PID: 1218 (code=exited, status=0/SUCCESS)

Jul 08 19:03:08 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Triggered global unit kubelet.service load
Jul 08 19:03:08 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Triggered global unit provision-k8s-secrets.service load
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit generate-k8s-certs.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit kube-apiserver.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit kube-controller-manager.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit kube-scheduler.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit get-kubectl.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit generate-k8s-tokens.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal bash[1218]: Unit kube-addons.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:03:10 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Started Deploy Kubernetes units via fleet.
```

**Comment by antoineco** [comment]
With `ExecStartPre` it doesn't fork bash:

```
Jul 08 19:10:48 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Starting Deploy Kubernetes units via fleet...
Jul 08 19:10:48 ip-10-0-21-132.eu-west-1.compute.internal systemd[1445]: kube-fleet.service: Executing: /usr/bin/bash -c '/usr/bin/fleetctl load /opt/fleet/*.service'
Jul 08 19:10:49 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Triggered global unit consume-k8s-tokens.service load
Jul 08 19:10:49 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Triggered global unit kube-proxy.service load
Jul 08 19:10:49 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Triggered global unit kubelet.service load
Jul 08 19:10:49 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Triggered global unit provision-k8s-secrets.service load
Jul 08 19:10:53 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Reinstalled deserialized job kube-fleet.service/start as 4453
Jul 08 19:10:53 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Changed dead -> start-pre
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit generate-k8s-tokens.service loaded
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit generate-k8s-certs.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit kube-scheduler.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit kube-controller-manager.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit kube-apiserver.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit kube-addons.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal bash[1445]: Unit get-kubectl.service loaded on 3d5044dd.../10.0.21.132
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal systemd[1461]: kube-fleet.service: Executing: /usr/bin/fleetctl start kube-apiserver.service kube-scheduler.service kube-controller-manager.service kubelet.service kube-proxy.service
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1461]: Triggered global unit kubelet.service start
Jul 08 19:10:54 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1461]: Triggered global unit kube-proxy.service start
Jul 08 19:10:55 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1461]: Unit kube-controller-manager.service launched
Jul 08 19:10:55 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1461]: Unit kube-apiserver.service launched on 3d5044dd.../10.0.21.132
Jul 08 19:10:55 ip-10-0-21-132.eu-west-1.compute.internal fleetctl[1461]: Unit kube-scheduler.service launched on 3d5044dd.../10.0.21.132
Jul 08 19:10:55 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: Started Deploy Kubernetes units via fleet.
```

**Comment by arvidjaar** [comment]
>  `Jul 08 18:55:38 ip-10-0-21-132.eu-west-1.compute.internal systemd[1]: kube-fleet.service: Reinstalled deserialized job kube-fleet.service/start as 2231`

Where does it come from? Does "fleetclt load" perform daemon-reload?

**Comment by antoineco** [comment]
`fleetctl load` is used to schedule one or more systemd units inside a fleet cluster.

For example `fleetctl load kubelet.service` will create the kubelet.service unit on the appropriate nodes without starting it.

It might perform a daemon reload indeed.

**Comment by zonque** [comment]
Ok, so if your `ExecStart*` directives call into `systemctl daemon-reload`, subsequent commands will likely not be executed or course. The reason for this is that systemd will spawn the first command and then wait until it returns, which PID1 is notified of through `SIGCHLD` signals. While waiting, it continues dispatching other things from its main loop, which is where the `org.freedesktop.systemd1.Manager.Reload` DBus command is received and dispatched.

As we can't block daemon reloading while we're waiting for a command to finish, I can't see how that can be solved on systemd's side. One solution is wrapping all commands in a shell script and using that as exec command.

**Comment by antoineco** [comment]
Ok that totally makes sense, and as you said there   are workarounds. But I'd like to ask a question from a previous comment again: why does it work with `ExecStartPre`?

**Comment by zonque** [comment]
Does that always work for you in that case? This is a race condition, after all, so it might not be strictly reproducible.

**Comment by haraldh** [comment]
it should probably do "systemctl --no-block daemon-reload"

**Comment by antoineco** [comment]
Surprisingly yes, unless I'm extremely lucky because I've tried each scenario around 10 times in a row.

**Comment by antoineco** [comment]
Write me in private if you need an ssh access to an isolated system.

**Comment by arvidjaar** [comment]
> Ok, so if your ExecStart\* directives call into systemctl daemon-reload, subsequent commands will likely not be executed or course.

Why is it "of course"?
- systemd spawns child for the first command
- child calls "systemctl daemon-reload"
- systemd serializes current state, which includes child PID and information that child was running ExecStart
- systemd loads configuration
- systemd deserializes current state

At this point systemd knows about pending command, knows PID it has to wait for and knows that it has multiple commands to run. So at which point exactly it "forgets" about further commands?

**Comment by poettering** [comment]
So, this is a known issue, has been raised on the ML many times. The problem is that we don't serialize which command we execute if there are multiple ExecStartPre=, ExecStartPost=, ExecStop=, ExectStopPost=. The reason is that there's not a nice way how to recognize what we are executing after we come back, if the unit file was changed in between.

Let's say with have a service with five ExecStartPost= lines, and we are currently executing the third one of them. Now we reload the daemon, hence serialize + deserialize things. Where should we continue execution after getting the SIGCHLD for the command? we could do this numerically, and serialize/deserialize "3", and then continue execution on the 4th line after the SIGCHLD. However, if somebody added a new ExecStartPost= in the beginning in the meantime, then we'd execute the same line twice... Hence serializing the line number as-is might not be a good idea. Instead we could try to find the line again by searching for the full command line (after seriliazing/deserializing it), but what happens if the user just added a new switch to it, and we cannot find the line again? Or what happens if the identical command line is used multiple lines?

it's a bit of black magic trying to find the line to continue execution at. So far we hence ignored the problem, and just restarted execution at the first line again of the specific type. This of course is nasty for many cases, but at least it is kinda deterministic...

Not sure what to do about this. Maybe we can make this smarter, and serialize both the numeric line number and the precise command we executed last, and then continue execution at the numeric line number if it matches the command line. If it doesn't, we continue execution on the first line that matches the command line precisely.  If there's none, we continue execution on the numeric line we saved. This would still be black magic, but probably in most cases result in the right result. Also, we should log about this, to help the admin track down issues with this.

Would be willing to take a patch for this.

**Comment by xnox** [comment]
haven't looked deep into systemd serialisation, but e.g. in upstart once equivalent of the unit has started we'd keep in memory all the processes/commands to exec, and serialise/desiriale all of them and continue executing them as we originally started and never switch to a different config. (e.g. if somebody rewrites post-stop exec lines during re-exec, the old post-stop commands would be used, as that's what the service had when it starting its exec flow). That's the most conservative thing to do. But upstart would always read all configs (not lazy) and only read new config into stand-by for next time a given unit would be started and never modify mid-flight config of any running units.

**Comment by arvidjaar** [comment]
> So far we hence ignored the problem, and just restarted execution at the first line again of the specific type.

The problem is, it does not explain what happens. If it restarts from the beginning, why it does not execute second ExecStart line?

**Comment by zonque** [comment]
On 07/09/2015 04:11 PM, Andrey Borzenkov wrote:

> The problem is, it does not explain what happens. If it restarts from
> the beginning, why it does not execute second ExecStart line?

Because the 2nd line might not be there anymore in the unit file after
the restart, or 1st line could have been removed, and the former 2nd
line is now the 1st etc.

As @poettering wrote, this can get really nasty when the logic is only
based on remembering the index of the last executed command.

This can become arbitrarily complex if you think of the corner cases.
After all, reloading unit files is one of the reasons why users reload
the daemon.

**Comment by arvidjaar** [comment]
> Because the 2nd line might not be there anymore in the unit file after the restart

Sorry, I do not speak about theoretical case. I speak about case reported in this issue. Here we have no evidence that original unit kube-fleet.service had been changed during reload. @antoineco - could please clarify whether original unit is unchanged?

**Comment by antoineco** [comment]
@arvidjaar yes this unit remains absolutely unchanged, it's just used to start other units in my cluster.

**Comment by zonque** [comment]
Sure, but as @poettering said, systemd does not currently pick up execution of command lists after a reload. It would be easy to implement for simple cases, assuming that unit files remain unchanged. Restoring the index would suffice then, but that doesn't cover the corner cases.

Again, one common reason for reloading is to make the daemon look at the unit files again, so there's a high probability such details have changed after a reload. If we want to support this, we have to do it properly IMO.

**Comment by arvidjaar** [comment]
> Sure, but as @poettering said, systemd does not currently pick up execution of command lists after a reload. 

Sorry for being insistent, but I do not understand this. @poettering said "we restart from the beginning" which I interpret as "we restart _execution_ of command list from the beginning". If "restart" in this context does not mean "restart executing" then what "restart" here refers to?

**Comment by zonque** [comment]
I'm not following. Yes, as the code currently stands, starting `foo.service` with

```
[Service]
Type=oneshot
ExecStart=/usr/bin/echo '1'
ExecStart=/usr/bin/systemctl daemon-reload
ExecStart=/usr/bin/echo '2'
```

will only execute up the daemon reload command. `echo '2'` will likely not be ran. When the daemon reload is finished, `systemctl start foo.service` will 'restart' execution of the command list from the beginning, not where it left off.

**Comment by arvidjaar** [comment]
@zonque Do you mean we have a loop? Yes, that was I thought initially, but I was confused by service status. @antoineco could you show "systemctl list-jobs"? For the wrong case? Also service status should show different PIDs basically every time you call it.

**Comment by antoineco** [comment]
@arvidjaar the PID doesn't change, the status remains `Main PID: 1628 (code=exited, status=0/SUCCESS)`, and it starts displaying the following fields only after 30sec:

```
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/kube-fleet.service
```

No jobs are running

```
# systemctl list-jobs
No jobs running.
```

**Comment by arvidjaar** [comment]
OK, so in case of Type != forking systemd does not resume (or restart) running ExecStart at all. In this case service_enter_start() sets main_command, not control_command, and systemd does not serializes main_command value.

```
       if (s->type == SERVICE_FORKING) {
                s->control_command_id = SERVICE_EXEC_START;
                c = s->control_command = s->exec_command[SERVICE_EXEC_START];

                s->main_command = NULL;
        } else {
                s->control_command_id = _SERVICE_EXEC_COMMAND_INVALID;
                s->control_command = NULL;

                c = s->main_command = s->exec_command[SERVICE_EXEC_START];
        }
```

This is just as good in this case, otherwise we'd enter endless loop. But this also means that we still are in danger of endless loop in case of forking service.

Still, as several time @poettering stated that commands are restarted from the beginning, it is probably not expected behavior. But that finally explains what happens here.

**Comment by kayrus** [comment]
Looks similar. Steps to reproduce (copy-paste from https://github.com/coreos/fleet/issues/1000):

We can reproduce similar behavior using these bash commands:

save `myapp.service` unit:

``` ini
[Unit]
Description=MyApp
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill busybox1
ExecStartPre=-/usr/bin/docker rm busybox1
ExecStartPre=/usr/bin/docker pull busybox
ExecStart=/usr/bin/docker run --name busybox1 busybox /bin/sh -c "while true; do echo Hello World2; sleep 1; done"
ExecStop=/usr/bin/docker stop busybox1
ExecStopPost=/usr/bin/echo Hello from stop
```

``` sh
sudo cp myapp.service /etc/systemd/system && sudo systemctl daemon-reload && sudo systemctl start myapp
```

stop unit, destroy it, reload systemd (in parallel):

``` sh
sudo systemctl stop myapp.service & sudo rm /etc/systemd/system/myapp.service & sudo systemctl daemon-reload
```

When systemd reloads stopping units - it doesn't take into consideration defined `ExecStopPost=` hooks.

**Comment by sjoerd-ccu** [comment]
For reference this issue seems to reliably break booting on one of my small arm boards. The standard systemd-udev-trigger.service has the following ExecStart:
>  ExecStart=@rootbindir@/udevadm trigger --type=subsystems --action=add ; @rootbindir@/udevadm trigger --type=devices --action=add

Seemingly while the udevadm trigger is running for the subsystems type a daemon reload is triggered,  In turn causing the triggering of device to never happen, which means boot ends up going wrong as various devices never turn up.
