### ISSUE TITLE
systemd-cryptsetup and clevis

### ISSUE THREAD

**Issue by haraldh** [systemd/systemd#5182]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232 

### Used distribution

> Fedora

### RFE
The clevis/tang project ( https://github.com/latchset/clevis ) needs additional options in /etc/crypttab for:
- "network" - for a luksOpen a network connection is needed and the network has to be up and running, ala remote-fs in /etc/fstab

- "systemd-noquery" - systemd should not ask for a password
- "systemd-noopen" - systemd should not try to luksOpen the device (but it should probably luksClose the device)

The last two options are probably not necessary, if systemd-cryptsetup recognizes the luksmeta information in the luksheader for clevis/tang (see https://github.com/latchset/luksmeta )

The UUID in luksmeta is defined here: https://github.com/latchset/clevis/blob/master/dracut/clevis-hook.sh#L22

**Comment by zdzichu** [comment]
Related #4642

**Comment by poettering** [comment]
> "systemd-noquery" - systemd should not ask for a password

Where would the password then come from?

**Comment by poettering** [comment]
> "systemd-noopen" - systemd should not try to luksOpen the device (but it should probably luksClose the device)

I don't follow? what's the purpose of this?

Also note that systemd-cryptsetup actually already is a NOP if the relevant crypto device it is called for already exists. Hence you already have something like this.

Anyway, this RFE needs longer explanations for the rationale. This looks very random right now, except for the networking thing, but for that we already have RFE #4642.

**Comment by poettering** [comment]
> The last two options are probably not necessary, if systemd-cryptsetup recognizes the luksmeta information in the luksheader for clevis/tang (see https://github.com/latchset/luksmeta )

We don't bother with reading LUKS superblocks ourselves. libcryptsetup does that for us. Hence: get your stuff supported by that, and we can support it too.

**Comment by poettering** [comment]
I talked to @npmccallum in person at FOSDEM about this. And we agreed that systemd-cryptsetup should check a udev property and exclude itself from activating a specific crypt devce in that case, and the clevis folks can set that instead and take over with their own tools.

Closing this hence.
