### ISSUE TITLE
Add UID and GID based conditions

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#5187]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

For user units, it would be nice to be able to add conditions based on the current user's UID or GIDs. In particular, being able to skip the root user would be nice.

I understand that systemd should not consult the nss user database, but I wonder if for the user manager this restriction could be skipped?

**Comment by poettering** [comment]
You mean something like "ConditionUser=root" or "ConditionGroup=root"?

I figure that would be OK to add...

**Comment by fsateler** [comment]
Actually, the main use case would be `ConditionUser=!root`, but yeah, that's the idea.

**Comment by martinpitt** [comment]
Would `ConditionPathIsReadWrite=!/root` be too ugly for this? I do appreciate that in theory root's home dir could be something else, but then someone could also rename UID 0 to something else. `ConditionPathIsReadWrite=!/run` is more robust in that regard, but less obvious what the intention is.

**Comment by fsateler** [comment]
Using `/root` would have the problem of conflicting with read-only images. `/run` does not have that problem, but as you note, it is less clear why is it necessary.

**Comment by fsateler** [comment]
Hmm. `ConditionPathIsReadWrite` is not usable either because it tests for the filesystem being writable, not if the user can write the given path.

**Comment by poettering** [comment]
There's a PR waiting for this in #5926.

**Comment by fsateler** [comment]
Ah, sorry. I forgot I had already filed this issue.
