### ISSUE TITLE
Document or implement multi-line logging via stdout

### ISSUE THREAD

**Issue by bryanburgers** [systemd/systemd#5188]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemctl --version
> systemd 229
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD-IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.04

### Request for enhancement

In [new style daemons][daemons], the recommendation for logging is

> Instead of using the syslog() call to log directly to the system syslog service, a new-style daemon may choose to simply log to standard error via fprintf(), which is then forwarded to syslog by the init system.

However, there is no direction on how to log an entry with newlines in it. If the newlines are printed normally, syslog will pick this up as independent log entries.

While it typically makes sense to have one line per log entry, there are certain cases (especially stack traces) where it makes sense to have multiple lines in a single message.

The request is to (1) either document how to do this in an appropriate location, or (2) implement the functionality to allow logging multiple lines in a single log entry when logging via stdout/stderr.

[daemons]: https://www.freedesktop.org/software/systemd/man/daemon.html#New-Style%20Daemons

**Comment by bryanburgers** [comment]
Upon reading more documentation, systemd 231 introduced the `JOURNAL_STREAM` environment variable, so maybe the better option is to check if the application is connected to the journal and use `sd_journal_print` instead.

**Comment by poettering** [comment]
So, I am pretty sure, that if any fancier kind of logging shall take place, then the best option is to use sd_journal_print() and related calls instead. It permits passing all kinds of metadata, and also doing multiline log events.

And as you found out, we make it possible to detect whether stdout/stderr is connected to the journal these days, thus permitting an easy upgrade.

Hence, I think you can already do what you are looking for. Closing this, I hopt that's OK.

**Comment by positron96** [comment]
Hi! Sorry to dig up this old thread, but I would find this feature very useful. The difference between stdout and sd_journal_print  is that writing to stdout/stderr is extremely easy from any programming language, while using sd_journal_print will depend on systemd bindings and libraries available for that language, presumably from 3rd parties.

As stdout parsing for new-style daemons is inspired by printfk interface, it can borrow one feature from it as well. Apparently, in addition to `<0>`..`<7>` log levels, printfk supports `<c>` prefix that has a meaning of appending line to a previous log message. So this can be used to create assemble a log event from multiple lines of stdout output.
