### ISSUE TITLE
Starting services with PrivateTmp=yes triggers mounting tmpfs on /tmp directory

### ISSUE THREAD

**Issue by d-hatayama** [systemd/systemd#5189]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see

Startring services with PrivateTmp=yes doesn't trigger mounting tmpfs
on /tmp directory , and the services fail to start.

### In case of bug report: Unexpected behaviour you saw

Starting services with PrivateTmp=yes triggers mounting tmpfs on /tmp
directory, and the services succeed in starting.

### In case of bug report: Steps to reproduce the problem

  1. Check if tmp.mount is inactive.
  2. Start some service with PrivateTmp=yes.
  3. Check if tmp.mount is active.

Unconditionally mounts tmpfs on /tmp directory could hide files under
/tmp directory from the processes that use the /tmp directory before
the service with PrivateTmp=yes starts.

For example, if some service with PrivateTmp=yes starts between the
following two lines, then there's no $tmpdir directory at the 2nd line
and the 2nd line fails to execute due to No such file or directory.

    tmpdir=$(mktemp --directory --tmpdir foobar.XXXXXX)
    echo foobar >$tmpdir/foobar

The cause of this issue seems that the dependency internally given to
the service with PrivateTmp=yes, RequiresMountsFor=/tmp, is too strong
meaning that this triggers mounting tmpfs on /tmp directory. It seems
that a variant of PartOf=, e.g. PartOfMountsFor=/tmp?, is appropriate
in this case.

**Comment by floppym** [comment]
Do you have tmp.mount masked? Or just inactive (unmounted)?

**Comment by fsateler** [comment]
Debian doesn't ship the upstream `tmp.mount` precisely for this reason[1].

I don't think there is a bug here. Your distro should not ship `tmp.mount` in the system unit path if `/tmp` should not be a `tmpfs` by default.

[1] Actually, we do, but not in the systemd unit path.

**Comment by d-hatayama** [comment]
Sorry, I found that this was a issue specific to RHEL7 version of systemd. I overlooked the following line in the RPM spec file that deletes Wants= dependency from local-fs.target to tmp.mount:

    # No tmp-on-tmpfs by default in RHEL7. bz#876122
    rm -f %{buildroot}%{_prefix}/lib/systemd/system/local-fs.target.wants/tmp.mount

I reproduced the issue by building upstream version of v237 but on a RHEL7 system so unit configurations were falsely the one on RHEL7.

So, according to the dependency, I understand that processes running before local-fs.target should not use /tmp dirctory because tmp.mount could mount some filesystem on the /tmp directory.

I close this issue because this issue doesn't exit on upstream.
