### ISSUE TITLE
option to disable systemd's “Time has been changed” message spam in journal log

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#5207]
### Submission type

  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

debian

### issue description

Due to combined use of Debian stretch, that uses systemd by default, and [sdwdate](https://github.com/Whonix/sdwdate) (that uses [Slow Clock Adjuster](https://github.com/Whonix/sdwdate/blob/master/usr/lib/sdwdate/sclockadj) ( [gh](https://github.com/Whonix/Whonix/issues/169) )), my system clock is frequently changed.

As a result `journalctl -f` gets endlessly spammed by.

```
    [...]
    Nov 07 13:46:49 host systemd[766]: Time has been changed
    Nov 07 13:46:50 host systemd[766]: Time has been changed
    Nov 07 13:46:51 host systemd[766]: Time has been changed
    [...]
```

It may be possible to disable this by switching from `LogLevel=info` to `LogLevel=notice`, but that is not a great solution, because then a lot other messages that are fine would be lost.

# feature request

Please provide an option to drop-in a configuration snippet that allows to disable the `Time has been changed` messages.

# Related code 
https://github.com/systemd/systemd/blob/master/src/core/manager.c#L1888

```
        log_struct(LOG_DEBUG,
                   LOG_MESSAGE_ID(SD_MESSAGE_TIME_CHANGE),
                   LOG_MESSAGE("Time has been changed"),
                   NULL);
```

**Comment by poettering** [comment]
As you the code you pasted shows this has already been downgraded to debug:

a80c1575065c3e3cbf97fd97993ff98598fa01bb

Closing.
