### ISSUE TITLE
gpt-auto-discovery shouldn't check no-auto-mount GPT flag for the ESP

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#5218]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> current git HEAD

### Used distribution

> exherbo

### In case of bug report: Expected behaviour you didn't see

> /boot is automounted on first access (like when calling kernel-install)

### In case of bug report: Unexpected behaviour you saw

> /boot remains not mounted

With systemd-232

```
Lou ~ # systemctl cat boot.mount                           
# /run/systemd/generator.late/boot.mount
# Automatically generated by systemd-gpt-auto-generator

[Unit]
Description=EFI System Partition Automount
Documentation=man:systemd-gpt-auto-generator(8)
Requires=systemd-fsck@dev-nvme0n1p1.service
After=systemd-fsck@dev-nvme0n1p1.service

[Mount]
What=/dev/nvme0n1p1
Where=/boot
Type=vfat
Options=umask=0077,noauto,rw
Lou ~ # systemctl cat boot.automount                       
# /run/systemd/generator.late/boot.automount
# Automatically generated by systemd-gpt-auto-generator

[Unit]
Description=EFI System Partition Automount
Documentation=man:systemd-gpt-auto-generator(8)
[Automount]
Where=/boot
TimeoutIdleSec=120
```

With current git HEAD

```
Lou ~ # systemctl cat boot.mount     
No files found for boot.mount.
Lou ~ # systemctl cat boot.automount 
No files found for boot.automount.
```

**Comment by poettering** [comment]
do you have a mount point /efi maybe?

Can you run this and report what it outputs and generates in /tmp/thisisatest:

``` sh
mkdir /tmp/thisisatest
SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/system-generators/systemd-gpt-auto-generator  /tmp/thisisatest /tmp/thisisatest /tmp/thisisatest
 ```

**Comment by Keruspe** [comment]
I do not have a /efi

```
Lou ~ # mkdir /tmp/thisisatest                                                                                                             
SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/system-generators/systemd-gpt-auto-generator  /tmp/thisisatest /tmp/thisisatest /tmp/thisisatest
Found container virtualization none.
Adding /: /dev/gpt-auto-root n/a
/dev/nvme0n1p2: root device /dev/nvme0n1.
Lou ~ # tree /tmp/thisisatest                                                                                                              
/tmp/thisisatest
├── local-fs.target.requires
│   └── -.mount -> /tmp/thisisatest/-.mount
├── local-fs.target.wants
│   └── systemd-fsck-root.service -> /usr/x86_64-pc-linux-gnu/lib/systemd/system/systemd-fsck-root.service
└── -.mount

2 directories, 3 files 
```

**Comment by poettering** [comment]
hmm, can you strace the generator call (strace -o log -s500 /usr/lib/systemd/system-generators/systemd-gpt-auto-generator …), and paste the output here?

**Comment by Keruspe** [comment]
Logs available here: https://gist.githubusercontent.com/raw/a80ad6087a78b62e93fcb5aaa2afb3db

**Comment by poettering** [comment]
Hmm, could you also provide the output of `/usr/lib/systemd/systemd-dissect /dev/nvme0n1` please?

**Comment by Keruspe** [comment]
Here is the output on the disk, on both partitions and the listing from gdisk fwiw

```
Lou ~ # /usr/lib/systemd/systemd-dissect /dev/nvme0n1                                                                                                  
Found writable 'root' partition (UUID c3bc931724634fdc9ea4f16ff0852081) of type crypto_LUKS for x86-64 without verity on partition #2 (/dev/nvme0n1p2)
Lou ~ # /usr/lib/systemd/systemd-dissect /dev/nvme0n1p1                                                                                                
Found writable 'root' partition of type vfat without verity (/dev/block/259:1)
Lou ~ # /usr/lib/systemd/systemd-dissect /dev/nvme0n1p2                                                                                                
Found writable 'root' partition of type crypto_LUKS without verity (/dev/block/259:2)
Lou ~ # gdisk -l /dev/nvme0n1                                                                                                                          
[...]
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          534527   260.0 MiB   EF00  EFI system partition
   2          534528      1000215182   476.7 GiB   8304  Linux x86-64 root (/)
```

**Comment by poettering** [comment]
hhmm, the dissector doesn't recognize your ESP as it appears. question is why...

what does "blkid -p /dev/nvme0n1p1" say?

**Comment by Keruspe** [comment]
```
/dev/nvme0n1p1: SEC_TYPE="msdos" UUID="BCAD-FA98" VERSION="FAT16" TYPE="vfat" USAGE="filesystem" PART_ENTRY_SCHEME="gpt" PART_ENTRY_NAME="EFI system partition" PART_ENTRY_UUID="95b9d7ae-5c3b-4edc-a8e2-b6545dae2d80" PART_ENTRY_TYPE="c12a7328-f81f-11d2-ba4b-00a0c93ec93b" PART_ENTRY_FLAGS="0x8000000000000001" PART_ENTRY_NUMBER="1" PART_ENTRY_OFFSET="2048" PART_ENTRY_SIZE="532480" PART_ENTRY_DISK="259:0"
```

The PART_ENTRY_TYPE looks ok from a quick git grep for GPT_ESP

**Comment by poettering** [comment]
Hmm, so this ESP is borked. fat16 is not permissible for ESP IIRC. It needs to be fat32 according to the EFI spec IIRC.

But: gpt-auto-discovery doesn't actually care about that, it has no problem with fat16. However, in its current incarnation it does care about the partition flags you are using. Specifically: PART_ENTRY_FLAGS="0x8000000000000001". This as bit 63 set, which the generator interprets aus "do not automount", in accordance to the ms "basic data partition" spec. However, I figure we shouldn't check that for the ESP really.

If you need a quick local fix, just unset that high bit. (i.e. that the flags field becomes just "1"). But we should fix that in gpt-auto-discovery

Thanks for helping to track this down.

**Comment by poettering** [comment]
Patch pending in #5224. Any chance you can verify that it fixes the issue for you?

**Comment by Keruspe** [comment]
That indeed fixes the issue.

**Comment by Keruspe** [comment]
Thanks for the help!
Now trying to figure out why mkfs.fat does fat16 and not fat32, but that is no longer systemd-related. Thanks for pointing that out too, though

**Comment by poettering** [comment]
> Now trying to figure out why mkfs.fat does fat16 and not fat32

It picks the file system type depending on the partition size. You can force it into fat32 mode with -F 32...
