### ISSUE TITLE
Default dependencies for swap units don't match docs

### ISSUE THREAD

**Issue by glasser** [systemd/systemd#5226]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

Current master (b4a8c5d)

### Used distribution

Reading the source

### Description

In current master, the doc for swap units' default dependencies say:

```
    <para>Swap units with <varname>DefaultDependencies=</varname> in the <literal>[Unit]</literal> section enabled
    implicitly acquire a <varname>Conflicts=</varname> and an <varname>After=</varname> dependency on
    <filename>umount.target</filename> so that they are deactivated at shutdown, unless
    <varname>DefaultDependencies=no</varname> is specified.</para>
```

The source code for `swap_add_default_dependencies` says:

```

        /* swap units generated for the swap dev links are missing the
         * ordering dep against the swap target. */
        r = unit_add_dependency_by_name(UNIT(s), UNIT_BEFORE, SPECIAL_SWAP_TARGET, NULL, true);
        if (r < 0)
                return r;

        return unit_add_two_dependencies_by_name(UNIT(s), UNIT_BEFORE, UNIT_CONFLICTS, SPECIAL_UMOUNT_TARGET, NULL, true);
```

If I read this correctly, there are two problems with the docs:

(a) The Before= dependency on swap.target is not mentioned.
(b) The docs say that it creates an After= dependency on umount.target but the code makes it appear to be a Before= dependency.

I haven't actually ran this, just examined the source, but it seems wrong. Happy to submit a docs PR if you agree.

**Comment by poettering** [comment]
Yes, a PR fixing the docs would be very welcome!

**Comment by glasser** [comment]
Great, #5278.

I guess that the Before/After thing doesn't actually matter since for shutdown/startup conflicts, the direction is irrelevant.
