### ISSUE TITLE
user.slice: Failed to set invocation ID on control group /user.slice, ignoring: Operation not supported

### ISSUE THREAD

**Issue by jcdr** [systemd/systemd#5236]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>232-15

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

>Debian Stretch armhf

### In case of bug report: Expected behaviour you didn't see

> none

### In case of bug report: Unexpected behaviour you saw

Every services generate a message like this:
Feb 06 01:09:11 OrangePI systemd[1]: user.slice: Failed to set invocation ID on control group /user.slice, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: media-boot.mount: Failed to set invocation ID on control group /system.slice/media-boot.mount, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-sysctl.service: Failed to set invocation ID on control group /system.slice/systemd-sysctl.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: heartbeat.service: Failed to set invocation ID on control group /system.slice/heartbeat.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: rc-local.service: Failed to set invocation ID on control group /system.slice/rc-local.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: system-getty.slice: Failed to set invocation ID on control group /system.slice/system-getty.slice, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: dbus.service: Failed to set invocation ID on control group /system.slice/dbus.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-udevd.service: Failed to set invocation ID on control group /system.slice/systemd-udevd.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: ntp.service: Failed to set invocation ID on control group /system.slice/ntp.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-random-seed.service: Failed to set invocation ID on control group /system.slice/systemd-random-seed.service, ignoring: Operation not
Feb 06 01:09:11 OrangePI systemd[1]: systemd-remount-fs.service: Failed to set invocation ID on control group /system.slice/systemd-remount-fs.service, ignoring: Operation not s
Feb 06 01:09:11 OrangePI systemd[1]: run-user-107.mount: Failed to set invocation ID on control group /system.slice/run-user-107.mount, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: networking.service: Failed to set invocation ID on control group /system.slice/networking.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-udev-trigger.service: Failed to set invocation ID on control group /system.slice/systemd-udev-trigger.service, ignoring: Operation n
Feb 06 01:09:11 OrangePI systemd[1]: power-mon.service: Failed to set invocation ID on control group /system.slice/power-mon.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-logind.service: Failed to set invocation ID on control group /system.slice/systemd-logind.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: kmod-static-nodes.service: Failed to set invocation ID on control group /system.slice/kmod-static-nodes.service, ignoring: Operation not sup
Feb 06 01:09:11 OrangePI systemd[1]: sys-fs-fuse-connections.mount: Failed to set invocation ID on control group /system.slice/sys-fs-fuse-connections.mount, ignoring: Operation
Feb 06 01:09:11 OrangePI systemd[1]: run-user-1000.mount: Failed to set invocation ID on control group /system.slice/run-user-1000.mount, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-modules-load.service: Failed to set invocation ID on control group /system.slice/systemd-modules-load.service, ignoring: Operation n
Feb 06 01:09:11 OrangePI systemd[1]: keyboard-setup.service: Failed to set invocation ID on control group /system.slice/keyboard-setup.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: tmp.mount: Failed to set invocation ID on control group /system.slice/tmp.mount, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: sys-kernel-debug.mount: Failed to set invocation ID on control group /system.slice/sys-kernel-debug.mount, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: system-serial\x2dgetty.slice: Failed to set invocation ID on control group /system.slice/system-serial\x2dgetty.slice, ignoring: Operation n
Feb 06 01:09:11 OrangePI systemd[1]: alsa-restore.service: Failed to set invocation ID on control group /system.slice/alsa-restore.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: polkit.service: Failed to set invocation ID on control group /system.slice/polkit.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: ssh.service: Failed to set invocation ID on control group /system.slice/ssh.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: lightdm.service: Failed to set invocation ID on control group /system.slice/lightdm.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: console-setup.service: Failed to set invocation ID on control group /system.slice/console-setup.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-tmpfiles-setup-dev.service: Failed to set invocation ID on control group /system.slice/systemd-tmpfiles-setup-dev.service, ignoring:
Feb 06 01:09:11 OrangePI systemd[1]: systemd-journald.service: Failed to set invocation ID on control group /system.slice/systemd-journald.service, ignoring: Operation not suppo
Feb 06 01:09:11 OrangePI systemd[1]: systemd-user-sessions.service: Failed to set invocation ID on control group /system.slice/systemd-user-sessions.service, ignoring: Operation
Feb 06 01:09:11 OrangePI systemd[1]: avahi-daemon.service: Failed to set invocation ID on control group /system.slice/avahi-daemon.service, ignoring: Operation not supported
Feb 06 01:09:11 OrangePI systemd[1]: systemd-journal-flush.service: Failed to set invocation ID on control group /system.slice/systemd-journal-flush.service, ignoring: Operation
Feb 06 01:09:11 OrangePI systemd[1]: systemd-tmpfiles-setup.service: Failed to set invocation ID on control group /system.slice/systemd-tmpfiles-setup.service, ignoring: Operati
Feb 06 01:09:11 OrangePI systemd[1]: systemd-update-utmp.service: Failed to set invocation ID on control group /system.slice/systemd-update-utmp.service, ignoring: Operation not
Feb 06 01:09:11 OrangePI systemd[1]: NetworkManager.service: Failed to set invocation ID on control group /system.slice/NetworkManager.service, ignoring: Operation not supported

This is a regression bug: this exact system was working well before upgrading to the new systemd.
There is no hint about what operation is not supported by the system.
There is no documentation about what is required to make the system support this operation.
There is no documentation about what can be done to make this operation working.

### In case of bug report: Steps to reproduce the problem

> Nothing but a regular apt dist-upgrade that installed a new systemd.

**Comment by poettering** [comment]
what kernel version are you using?

**Comment by jcdr** [comment]
3.4.112-rt143 from https://github.com/orangepi-xunlong/orangepi_h3_linux
It's the only existing Linux kernel that currently support camera video input on the Allwinner H3 processor.

**Comment by poettering** [comment]
Sorry, we don't support such old kernels with systemd 232. See README. The minimum required kernel version is 3.12.

Your ancient kernel doesn't support xattrs on cgroupfs, simply because it is too old.

Sorry if htat's disappointing.

**Comment by jcdr** [comment]
Did you understand that I don't have any control on this situation ? New Linux kernel take care to not breaking application, but new systemd don't care to break existing systems. This is disappointing.
At least 231 versions of systemd didn't require this kernel feature, so it's without any possible doubt a regression bug.

**Comment by poettering** [comment]
Please understand that we have very limited maintainance resources. We can't support everything under the sun, we have to draw a line somewhere. We are drawing the line with ancient kernel versions. 3.4 was released 5 years ago, that's older than systemd itself is.

And no, systemd does not work correctly on such old kernels, not even 231. Maybe not in the precise usecase you have, but we do use features of newer kernels, not available back then at various places.

Sorry.

**Comment by jcdr** [comment]
So, are you open to patches that allow systemd to work on kernel that don't have some features. This would also benefit new kernel that are specifically compiled without all features for some reasons (size, performances, attack surface, regression tests, experiment, etc..)

**Comment by poettering** [comment]
Well, yes, we support kernels that have specific features disabled at compile time. We require a certain set of features however, and proper cgroup support is one them. We also support a large set of different kernel versions, but sorry, 3.4 is *way* to old...

Maintenance doesn't just mean to accept a patch. It also means that we can for the future still support it as well.

**Comment by jcdr** [comment]
Kernel support for processors used in embedded systems aren't as fast as then mainline kernel. While more ans more manufacturers understand how important is mainline upstream, the reality is that this kind of effort could take more than 5 years to get the same feature as a hacked board support package. Mainline kernel patches acceptance is actually harder than ever and this don't help the situation. You are not alone to have very limited maintainance resources...

**Comment by poettering** [comment]
yeah, i am sorry for the situation. But this doesn't really change things, please understand my perspective, I don't scale that well, that I could support any old stuff that exists in this world.

I am very sorry.

**Comment by evverx** [comment]
>  but new systemd don't care to break existing systems
> This is a regression bug

This is not a bug. This doesn't break anything.
We can't set some invocation id. But it doesn't really matter. This is why we ignore that. And you can ignore that too.

> There is no documentation about what can be done to make this operation working.

http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=03b1cde6b22f625ae832b939bc7379ec1466aec5 (`3.7`)

**Comment by jcdr** [comment]
Ok evverx, thanks for this useful information. If this doesn't break anything, could I suggest to not spam the journal log with so much messages ? Or at least to have a way to disable this messages ?

**Comment by poettering** [comment]
> This doesn't break anything.

That's not true... It breaks the journal's hookup to the invocation id.

**Comment by poettering** [comment]
> Ok evverx, thanks for this useful information. If this doesn't break anything, could I suggest to not spam the journal log with so much messages ? Or at least to have a way to disable this messages ?

Well, again, you are using systemd outside of its supported environment. Which is entirely fine, it's free software after all, but please make the change locally then, it's nothing we want to support upstream.

Sorry.

**Comment by evverx** [comment]
> It breaks the journal's hookup to the invocation id

Well, this is a new feature. So, it doesn't break existing systems.
Also, see https://github.com/systemd/systemd/issues/4441. So, invocation id doesn't really work sometimes. That's not so critical.

> could I suggest to not spam the journal log with so much messages ?

You can locally apply this patch
```diff
diff --git a/src/core/cgroup.c b/src/core/cgroup.c
index 5789e2a..7d78e79 100644
--- a/src/core/cgroup.c
+++ b/src/core/cgroup.c
@@ -1387,7 +1387,7 @@ static void cgroup_xattr_apply(Unit *u) {
                          sd_id128_to_string(u->invocation_id, ids), 32,
                          0);
         if (r < 0)
-                log_unit_warning_errno(u, r, "Failed to set invocation ID on control group %s, ignoring: %m", u->cgroup_path);
+                log_unit_debug_errno(u, r, "Failed to set invocation ID on control group %s, ignoring: %m", u->cgroup_path);
 }
```

**Comment by evverx** [comment]
But this is true of course
> Well, again, you are using systemd outside of its supported environment. Which is entirely fine, it's free software after all, but please make the change locally then, it's nothing we want to support upstream.

> Sorry.

**Comment by jcdr** [comment]
If I understand correctly, the command that use the journal's hookup to the invocation id must just say that this feature is not available because the kernel don't provides the xattrs on cgroupfs. Seem to be a more clean way.

It's not just the problem of older kernel. There could be not so old kernel, or even new kernel, that was not compiled with some features. There was working fine, and should continue to work fine.

**Comment by evverx** [comment]
> There could be not so old kernel, or even new kernel, that was not compiled with some features.

We do that for **supported** kernels. For example, https://github.com/systemd/systemd/pull/4087

**Comment by jcdr** [comment]
Systemd is now the default on all majors distributions and a very central piece of a working system. Please understand that this imply some car to not break existing systems, especially when simple alternative exists. It's difficult to imagine that you refuse to support some kernel just because this look easy to you... Those kernels was running systemd fine before. There no point in breaking them for a feature that no one needed before. It perfectly logical to disable this new feature if the kernel don't support it. Could you agree to accept a patch that do that ?

**Comment by evverx** [comment]
@jcdr , we don't totally break old systems. This is why that patch exists https://lists.freedesktop.org/archives/systemd-devel/2014-June/020535.html

> [systemd-devel] [PATCH] core: Don't require cgroups xattr support

Again, I don't think we break something. You don't have some feature. But it doesn't crash your system or wipe out your data.

> Could you agree to accept a patch that do that ?

Personally I don't think we need a patch for that. But, maybe, this helps with #4441 somehow

**Comment by jcdr** [comment]
It's only today that I understand that this don't crash the system or wipe out data. Exactly like the guy that reported #4441, I faced a situation that is almost impossible to understand outside of the systemd development team. Please read one more time my initial report: I was unable to find any valuable information about what I see and ask for better message ans documentation. I must thank you for the information you provided. This is really the most helpful part of this issue comments.

Now that you have at least two reports about peoples scared about this messages spam in the journal log, it's certainly a good idea to at least improve the user/admin experience in that case. Is that really so hard ?

**Comment by mbiebl** [comment]
@jcdr that sounds really something which should be fixed by the orangepi maintainers.
They should provide you with a more modern kernel

**Comment by jcdr** [comment]
@mbiebl Agree. There are working on that http://linux-sunxi.org/Linux_mainlining_effort but it's slow and I need the camera support currently only available on Linux 3.4.112-rt143 from https://github.com/orangepi-xunlong/orangepi_h3_linux This is the raw reality.

#4441 prove that there are others situations that require the same kind of care. I just ask for a better information to the user/admin than the actual journal log spam.

**Comment by poettering** [comment]
> It's not just the problem of older kernel. There could be not so old kernel, or even new kernel, that was not compiled with some features. There was working fine, and should continue to work fine.

Well, the standard kernel doesn't make xattr support in cgroupfs a configurable option, hence I don't see why we should. If you run a patched kernel, then I think it#s not too much too ask to also expect from you that you patch your userspace too.

**Comment by jcdr** [comment]
If really xattr support in cgroupfs a not configurable option, then why did you spam the journal log with the error message in the first place to just say that you ignore the error? You better have to silently ignore it and to warn the user when he try to query the journal with invocation ID. This solution will provides a far better understandable experience to user/admin, and it's probably not a big change to do.

**Comment by poettering** [comment]
@jcdr syscalls can fail for tons on reasons, not just because of disabled kernel options. We log about this, indicating the error, so that people figure have an idea what is going wrong, and that something is wrong in the first place. It could be an selinux fuckup, or anything else, and eating up errors blindly is usually not a good idea.

**Comment by jcdr** [comment]
@poettering Agree on that, really. Could I suggest a patch that:
1) Change the error message to explain that the problem is the lack kernel support of xattr support in cgroupfs.
2) Log this message only at the startup of systemd,

**Comment by poettering** [comment]
@jcdr: nope. it might be any of reasons, as I tried to make clear. could be selinux permissions fuckup, anything. and it might not be a transient issue, specific to one occasion, hence coalescing isn't right.

Sorry, but no, I wouldn't accept such a patch. 

We don't add new support for five year old kernels today, sorry. And that's documented. Please accept that. Please patch around as much as you like, but do so downstream. Thank you for your understanding.

**Comment by jcdr** [comment]
Your argument about old kernel is not a good one: you admit yourself that selinux permissions could rise the same problem. Please at least improve the error message to explain that the problem is into a the xattr support in cgroupfs. It's really just a so small modification to help users/admins facing this issue.

**Comment by poettering** [comment]
well, users/admins should never face that message anyway... I mean, if you use a hacked retro-kernel with a modern systemd then that's hardly the typical user/admin thing. You are using something clearly outside of the supported environment, so you better know what you are doing anyway.

That said, I'd be willing to take a patch that changes the message to say that this is about xattr support.

**Comment by jcdr** [comment]
Many thanks for your understanding and for talking about this issue.

**Comment by ozra** [comment]
I was hit with this just yesterday. Updated the Debian versions on two VPS servers, and the messages started pooouuuring. I paniced! Quickly checked git-web, web-mail and sites (the "immediately testable from 'the other side'") - phew - everything seemed to work. A quick web-search gave this page first, that's why I'm here.

- I've used Linux since 1997, and so have done my fair share of updates over the years.
- This is the first time I've experienced such a shit-storm of errors regarding something that doesn't (apparently) hinder the system from working
- Considering the central role of the 1-proc, I'm surprised at the lack of considering ways of reacting to it, code-wise.
    - I assume there are quite a number of O-VZ VPS'es out there
        - and they won't go away in a second, just because there are better solutions today.
        - "don't fix it if it ain't broken"
        - in my view (and likely the VPS providers' too) - systemd is "broken" _in this context_ ("reality", with it's dead lines and only-so-much-time-in-life)
    - and likely other scenarios where an older kernel, or similar discrepancy, might be at play

Personally, I think scenarios like this should be catered to
- As mentioned above: intelligently heuristically coalescing the error messages in a scenario such like this would be more than reasonable.
- Perhaps in combination with configuration: "please don't warn about..."

My other options are of course:
- Just ignore the errors (_ouch! ̣-- the signal to noise ratio there! Dangerous territory to start ignoring messages!_)
- Dig out systemd and replace it with another system- and daemon-management system (_ouch! -- that will be a hell of a job in an existing running system_)
- Re-install the servers with an alternative OS that uses another init (_just ouch!_)

Well, to be honest I'll likely just resort to handling all services I commonly deal with using a daemon-manager "under" systemd, as to avoid interaction with it, or just make a tiny wrapper command around journalctl to filter that out. So of course there are always ways of getting around it. Just feels a bit... hacky.

Anyway, I thought it better to add my 2 mBTC than not, cheers, and keep it up!

**Comment by evverx** [comment]
> As mentioned above: intelligently heuristically coalescing the error messages in a scenario such like this would be more than reasonable.

I think it would make sense to simply downgrade the log level to `DEBUG` when `EOPNOTSUPP` is returned, as it was done in https://github.com/systemd/systemd/issues/5607.

**Comment by tecnogaming** [comment]
I don't know who is the idiot who considered BREAKING perfectly functional VPS with old kernels was SUCH A GOOD IDEA in the merit of "progress".  So much stuff is critizied in Microsoft but truth is, I can still play games that were working on Windows XP on my Windows 10.

Now 5 of my customers VPS are BROKEN without any Mysql functionality because the new systemd and mariadb stopped working.  This is tons of extra work for me, with 0 income and a TON of headache to my customers that sudently, lost all mysql functionality.

I say this again,  who is the IDIOT that think this is a good way of doing upgrades?.  I'm seriously pissed off about this.  Now I need to get a new server and do a MASSIVE migration in 1 day before I start lossing customers because of this "upgrade".

Whenever I see this pathetic attitude on behav of linux programmers I like my WIndows even more.

**Comment by evverx** [comment]
Could you clarify what exactly makes you think that `systemd` and `MariaDB` stopped working because of this issue?

**Comment by tecnogaming** [comment]
I did a simple "apt-get upgrade" on my two debian VPS for customers and  mariadb stopped working on both and there is no way to make it work again... it failes with cgroups and ID errors and this were 2 VPS that were working flawlesly previous to execute the dreaded "apt-get upgrade"

**Comment by vcaputo** [comment]
Perhaps in the future you'll prepare for upgrades using sandboxed throwaway instances seeded from backups before performing on your live environment.  This all strikes me as reckless in the context of providing services for paying customers.

Raise this issue with your distributor and VPS provider, there's only so much upstream developers of individual software components can predict - and nobody is perfect.  The potential combinations of kernel and userspace versions and configurations out there across all linux installations is far too numerous for anything resembling a tractable test matrix to emerge, be realistic.

**Comment by tecnogaming** [comment]
I'm sorry?.  This is the first time 2 VPS completely break because of apt-get upgrade and I've been in the bussiness for 8 years now.  Of course i have backups but BREAKING a mysql perfectly working system doing an UPGRADE is not considered good practice and it shouldn't be happening,  be more profesional if you try to justify "a new feature"

**Comment by tecnogaming** [comment]
Also, this response:

"Your ancient kernel doesn't support xattrs on cgroupfs, simply because it is too old, Sorry if that's disappointing".

completely summarize what is happening.. Linux developers themselves are reckless in the way they add stuff, they completely ignore that there is actual people with actual websites and content working that get affected by their updates.  They should NOT answer like that, ever.  Be responsable with what you add.  Breaking a perfectly working system and then ask people to "upgrade" is not a solution.

**Comment by vcaputo** [comment]
I don't disagree that it's inappropriate for `apt-get upgrade` to break such things, but this is an issue for Debian.  If your VPSs are running non-Debian kernels, it's also an issue for your VPS provider.

It's the role of the distributor to ship a compatible set of software, and prevent breaking upgrades.

Just because systemd ships new software dependent on modern kernel features doesn't mean they magically appear when you run `apt-get upgrade`, the distributor decides what to include in such upgrades.

Now that you've experienced evidence that someone, either Debian or your VPS provider, is dropping the ball, I strongly advise you perform test upgrades in isolation to prevent such negative outcomes in the future.

**Comment by ozra** [comment]
@tecnogaming : Your MariaDB trouble could be completely unrelated to systemd?

I must say, I've never had an issue (worth mention) with initialization in my 20 years with Linux (let alone had to think about it [software at it's best]). I haven't spent a thought on systemd either until now, just been hearing that it was gonna be faster (_sounded good enough for me, not that I restart my computers or VPSes that many times a year, so I wouldn't know, to be honest... besides, I make coffee then_)

Well, now I've checked around a bit, and in the process found that some other nagging problems I've been having on local machines are related to systemd too. So for my case, I found a distro-fork that excludes systemd, called Devuan which apparently _should_ just upgrade, so I'll just try that out, and hopefully things will be back to working smoothly and all that. Fingers crossed. _So, obviously, you can happily and completely disregard my 2 mBTC's above, cheers!_

**Comment by asalminen** [comment]
There was clear warnings during my Debian Stretch update that my kernel is way too old. If recalling correctly even libc update  was saying that please do not complain to upstream if stuff go bad. Many VPS kernels are too old for Debian Stretch.

**Comment by scoobydoowru** [comment]
Anyone who blames an old kernel for causing problems is just being lazy and should not be writing code to begin with.  Especially when they use words like Ancient. Kernels that are only a few years old are not ancient.  Frankly, there is far too much upgradeitis where people think they need to upgrade just for the same of upgrading.  A lot of people prefer stabiliy over the latest and greatest and having the latest kernel is not necessarily a good thing all the time.

Anyways, just wanted to vent about this blame the old kernel nonsense.  That's just a lazy excuse programmers like to use.

**Comment by evverx** [comment]
By the way, the issue was fixed in November 2017. Anyone who isn't too lazy to look at the code might find d3070fbdf6077d7da9dbafa and 0fb84499301ca9c679313 useful.

**Comment by jcdr** [comment]
Many thanks evverx for the fixes references, even if it's about 10 months later, and 18 months after I was reporting here. This bring to me some optimism that systemd might be reliable and nice to use before I die.  But the first step to go in that direction is to listen to the users like you do. I sincerely greatly appreciate this evolution and encourage the whole systemd team to work like this.

**Comment by cjemorton** [comment]
Found this issue by googling the journalctl message spam after setting up a minio s3 server on a vps provider.

I am not in control of which kernel is being used with the host.

This is one of the very reasons I try to avoid using any Linux based systems if at all possible, preferring instead the predictability of FreeBSD. That's just a personal choice however, so when it comes to something like this well I guess I am spoiled. The bottom line is I definitely prefer stability, where things don't just up and break at a simple update, or or spam error messages on install about something I really don't have any control over.

#Venting frustrations. Thanks.
