### ISSUE TITLE
MemoryDenyWriteExecute= may be circumvented on i386

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#5240]
We need to block mmap2() in addition to mmap().

See https://github.com/systemd/systemd/issues/5215#issuecomment-277459655

**Comment by poettering** [comment]
@topimiettinen maybe something for you?

**Comment by poettering** [comment]
I posted #5254 now, which (hopefully) fixes this. Since I don't actually have i386, I just verified it compiles and doesn't break x86-64, and I am relying on the i386 CI to validate it on i386.

**Comment by mbiebl** [comment]
@poettering the CI doesn't run ```make check``` as root, so several tests are skipped atm.
A workaround was added for test-seccomp:
https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=ac866cbd3825e1da615a8bc53fa5eba37cefabda

But test-failures are currently ignored on i386 and s390x
https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=e9cf26fe4ace7f6d2fb2758729fec983c6b6516d

So please keep that in mind

**Comment by poettering** [comment]
hmm, so you are saying that because the memorydenywriteexecute test requires root privs the CI won't let me know whether all worked on i386? humpf...

anyone with an i386 could test #5254 by hand then? If not, the only option is to merge it and wait until people complain...

**Comment by evverx** [comment]
> test requires root privs the CI won't let me know whether all worked on i386? 

CI runs `test-seccomp` as `root` (but ignores the result). We should grep the logs
```
Assertion 'p == MAP_FAILED' failed at ../src/test/test-seccomp.c:390, function test_memory_deny_write_execute(). Aborting.
```

**Comment by martinpitt** [comment]
> the CI won't let me know whether all worked on i386? humpf...

It does, I just currently ignore failure of `test-seccomp` on i386 and s390x to avoid breaking every (unrelated) PR. Once this starts to succeed on these arches, I will of course drop the `|| true` logic and we will start gating on them. So until then one needs to actually look at the log (search for `seccomp: [--`) to see if it succeeded.
