### ISSUE TITLE
process org.freedesktop.systemd1 exited with status 1

### ISSUE THREAD

**Issue by soloturn** [systemd/systemd#5247]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

> $ pacman -Q systemd
systemd 232-8
linux 4.9.6-1-ARCH

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> arch linux

### In case of bug report: Unexpected behaviour you saw

> Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.gtk.vfs.Daemon'
Successfully activated service 'org.gtk.vfs.Daemon'
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.a11y.Bus'
Successfully activated service 'org.a11y.Bus'
Activating service name='org.gnome.Shell.CalendarServer'
Activated service 'org.gnome.Shell.CalendarServer' failed: Process org.gnome.Shell.CalendarServer exited with status 127
Activating service name='org.freedesktop.Telepathy.AccountManager'
Successfully activated service 'org.freedesktop.Telepathy.AccountManager'
Activating service name='org.gtk.vfs.UDisks2VolumeMonitor'
Successfully activated service 'org.gtk.vfs.UDisks2VolumeMonitor'
Activating service name='org.gtk.vfs.MTPVolumeMonitor'
Successfully activated service 'org.gtk.vfs.MTPVolumeMonitor'
Activating service name='org.gtk.vfs.AfcVolumeMonitor'
Successfully activated service 'org.gtk.vfs.AfcVolumeMonitor'
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1

### In case of bug report: Steps to reproduce the problem

> start gnome on command line:
XDG_SESSION_TYPE=wayland nohup dbus-run-session gnome-session

**Comment by poettering** [comment]
this suggests you aren't actually running dbus from the systemd --user instance...

**Comment by CounterfeitLlama** [comment]
I am having the exact same issue as above. Has anyone found a solution to this yet?

**Comment by soloturn** [comment]
lennart, what do you mean with your comment, resp what do you want me to do? i am following what florian müllner suggested here: https://bugzilla.gnome.org/show_bug.cgi?id=774774

**Comment by poettering** [comment]
@soloturn well, is "systemctl --user dbus.service" showing that the user dbus is running as user service off systemd --user?

**Comment by soloturn** [comment]
to add, i was starting gnome wayland for quite a while like this, and there was no systemd error. it showed up recently - i.e. in the last weeks.

$ systemctl --user dbus.service
Unknown operation dbus.service.

$ systemctl --user | grep loaded
...
51 loaded units listed. Pass --all to see loaded but inactive units, too.

$ cat /etc/pam.d/system-login  | grep systemd
-session    optional   pam_systemd.so

i saw:
https://www.archlinux.org/news/d-bus-now-launches-user-buses/
https://wiki.archlinux.org/index.php/D-Bus

**Comment by poettering** [comment]
> $ systemctl --user dbus.service

Sorry, I meant "systemctl --user status dbus.service"...

**Comment by soloturn** [comment]
it says, entered into a gnome terminal:
$ systemctl --user status dbus.service
● dbus.service - D-Bus User Message Bus
   Loaded: loaded (/usr/lib/systemd/user/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2017-03-19 05:58:41 CET; 4h 49min ago
     Docs: man:dbus-daemon(1)
 Main PID: 1773 (dbus-daemon)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.service
           └─1773 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation

would you be able to describe how it is supposed to be, or where this can go wrong? i boot, i log in on text tty, then start gnome as my user with "XDG_SESSION_TYPE=wayland dbus-run-session gnome-session".

**Comment by al-berger** [comment]
@soloturn 

I just had the same symptoms with Gnome not starting on Arch and the problem was resolved by installing 'nvidia' package instead of 'nvidia-340xx-utils'.

**Comment by soloturn** [comment]
nbdsp, do you start it on a command line or you have gdm running?

**Comment by raindev** [comment]
I have exactly the same symptoms when starting GNOME with `XDG_SESSION_TYPE=wayland dbus-run-session gnome-session`. Shell starts successfully anyway and seems to be running without issues.

**Comment by soloturn** [comment]
this one does not seem related but i am putting it here in case there is a relation i cannot see. when i do not log in on the command line but put the command into bash_profile, starting falls into an endless loop, "cannot initialise inotify" and then "dbus-run-session ignoring unknown child process ...". i opened a bug here:
https://bugzilla.gnome.org/show_bug.cgi?id=780801

for the inotify i did something in the lines of:
echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system

**Comment by FranklinYu** [comment]
I met both issues as well.

I suspect that the endless loop issue is caused by the `dbus-run-session` process somehow sourcing `.bash_profile` (`.zprofile` in my case) again, so each message indicates a level of call stack. I avoided this issue by

```shell
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]
then XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
fi
```

**Comment by eliriand** [comment]
I can reproduce this bug too with Arch using systemd 232 and dbus 1.10.18. After running XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
```Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.gtk.vfs.Daemon'
Successfully activated service 'org.gtk.vfs.Daemon'
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Activating service name='org.freedesktop.systemd1'
Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
```

Dbus user service is running fine:

```dbus.service - D-Bus User Message Bus
   Loaded: loaded (/usr/lib/systemd/user/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Tue 2017-04-25 17:10:50 MSK; 18h ago
     Docs: man:dbus-daemon(1)
 Main PID: 1029 (dbus-daemon)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.service
           └─1029 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation```

**Comment by eomanis** [comment]
I am hit by this too since Arch updated to GNOME 3.24 a few days ago.

GDM appears to be unable to start a Wayland-based GNOME session and falls back to Xorg, that's why I started investigating.
When I run XDG_SESSION_TYPE=wayland dbus-run-session gnome-session from one of the system terminals, I get the same result as eliriand. The dbus user service is up and running.

I only got rid of the GNOME Xorg session a few weeks ago. Now my desktop is again insecure, and the activities overview lags again, it owns :-/ It was so smooth when running in Wayland mode

**Comment by FranklinYu** [comment]
@eomanis I believe that's a situation worse than some of us here. In my case, I saw those messages, but GNOME session works fine. Same for @raindev. In you case GNOME session can't even start under Wayland, right (neither from GDM nor from terminal)?

And I'm wondering why this issue is still labeled with "needs-reporter-feedback" although @soloturn has already replied a month ago. Maybe there are way too many issues in the queue (over 600 now).

**Comment by BinaryHexer** [comment]
@franklinyu is there a temporary solution or workaround for this? I cannot now start my wayland Gnome DE and it's the only DE on my Arch installation.

**Comment by keszybz** [comment]
This seems to be an issue with the way the user session is started on arch, i.e. not something that we can solve here. Please move this discussion to the arch bugtracker. (Also, if somebody could later paste a link, for the sake of other people encountering this issue, that'd be appreciated.)

**Comment by FranklinYu** [comment]
@BinaryHexer It shouldn't stop GNOME from being started. Are you trying to start GNOME from GDM or from terminal? Or you tried both?

**Comment by BinaryHexer** [comment]
@franklinyu terminal.  

This is the script I am using
```
#!/bin/bash

export QT_QPA_PLATFORM=wayland
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z $XDG_SESSION_TYPE ]]
  then XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
fi
```

**Comment by FranklinYu** [comment]
@BinaryHexer I assume that the script is neither `.profile` nor `.xsession` nor any dot file? Maybe it's just a script which you run with `./start-gnome`?

**Comment by BinaryHexer** [comment]
@franklinyu yes, correct assumption. It has worked in the past without any problems, I don't know what happened.

**Comment by FranklinYu** [comment]
@BinaryHexer Then how about simply

```shell
XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
```

in log-in shell session? (Note the absence of `exec`.)

**Comment by raindev** [comment]
@franklinyu, sorry I've missed your previous mention.

> In you case GNOME session can't even start under Wayland, right (neither from GDM nor from terminal)?

Actually, that's not the case: I still can successfully Stuart GNOME session both from tty and using GDM.

**Comment by FranklinYu** [comment]
@raindev Yes, I knew about that; I was actually referring to @eomanis's case. I think the behavior on your system is the same as mine, while @eomanis unfortunately met some more issue.

Sorry for causing misunderstanding. (Non-native speaker here.)

**Comment by BinaryHexer** [comment]
@franklinyu thanks for helping me, but
```
XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
```
has the same result as before.

[Here is result of debug](https://pastebin.com/aQZCYJ21)  

I can't figure out how to fix this.

**Comment by polyjitter** [comment]
I'd like to chime in and say I've had a similar problem. For me, any Wayland session immediately crashes back to GDM. 

When I run `dbus-run-session -- gnome-shell --display-server --wayland`, it WILL run a legitimate GNOME Shell wayland session; however, most custom icon theming and gtk2 themes don't work, my touchpad is unresponsive, and some apps (such as Rhythmbox) don't show headerbars.

When I try to run budgie-desktop with the same method, however, I get the error stated in the issue.

I am running a Intel HD/Nvidia laptop. I'm not sure if this is the same symptoms, if it's multiple issues, or where to go from here.

Any help would be appreciated.

**Comment by udovdh** [comment]
$  systemctl --user start  vino-server.service
Failed to start vino-server.service: Process org.freedesktop.systemd1 exited with status 1
See user logs and 'systemctl --user status vino-server.service' for details.
$ systemctl --user status vino-server.service
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1

What is org.freedesktop.systemd1?
What use is it if it exits with status 1 and  does not offer a decent place to find out what is causing this brouha?
Previously we could simply start a daemon.

**Comment by udovdh** [comment]
$ systemctl --user status
Failed to read server status: Process org.freedesktop.systemd1 exited with status 1
$ systemctl --state=failed --all
0 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.

How can this be?

**Comment by dpc** [comment]
On Archlinux, I've enabled `[testing]`, upgraded everything, and the problem went away.

**Comment by stev-it** [comment]
This is not just an arch problem. Im having the same issue on my raspberry pi too now.

**Comment by udovdh** [comment]
$ systemctl --user start vino
Failed to start vino.service: Process org.freedesktop.systemd1 exited with status 1
See user logs and 'systemctl --user status vino.service' for details.

System was taken to runlevel 3 and then to 5.
This impiies that this does not cleanly kill all GUI-related processes and/or does not perfectly start all GUI-related processes.

**Comment by soloturn** [comment]
@poettering the error message meanwhile slightly changed, this is the nohop file after starting gnome on the command line and then immeditaely press "logout".

```
$ XDG_SESSION_TYPE=wayland nohup dbus-run-session gnome-session 
$ cat nohup.out
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.1' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.3' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.5' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.7' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.8' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.gtk.vfs.Daemon' requested by ':1.9' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'org.gtk.vfs.Daemon'
fusermount: failed to access mountpoint /run/user/1000/gvfs: Permission denied
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.8' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.8' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.a11y.Bus' requested by ':1.11' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'org.a11y.Bus'
dbus-daemon[17853]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
dbus-daemon[17853]: Successfully activated service 'org.a11y.atspi.Registry'
SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.gnome.Shell.CalendarServer' requested by ':1.9' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
/usr/lib/gnome-shell-calendar-server: error while loading shared libraries: libecal-1.2.so.19: cannot open shared object file: No such file or directory
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.gnome.Shell.CalendarServer' failed: Process org.gnome.Shell.CalendarServer exited with status 127
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='ca.desrt.dconf' requested by ':1.9' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'ca.desrt.dconf'
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.gtk.vfs.UDisks2VolumeMonitor' requested by ':1.9' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'org.gtk.vfs.UDisks2VolumeMonitor'
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.gtk.vfs.MTPVolumeMonitor' requested by ':1.9' (uid=1000 pid=17820 comm="/usr/bin/gnome-shell ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'org.gtk.vfs.MTPVolumeMonitor'
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.Tracker1' requested by ':1.35' (uid=1000 pid=17989 comm="gdbus call -e -d org.freedesktop.DBus -o /org/free")
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'org.freedesktop.Tracker1'
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.gnome.Terminal' requested by ':1.36' (uid=1000 pid=17987 comm="gnome-terminal ")
Display does not support owner-change; copy/paste will be broken!
dbus-daemon[17775]: [session uid=1000 pid=17775] Successfully activated service 'org.gnome.Terminal'
dbus-daemon[17775]: [session uid=1000 pid=17775] Activating service name='org.freedesktop.systemd1' requested by ':1.8' (uid=1000 pid=17776 comm="/usr/lib/gnome-session-binary ")
dbus-daemon[17775]: [session uid=1000 pid=17775] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
A connection to the bus can't be made
```

```
$ systemctl --user status dbus.service
● dbus.service - D-Bus User Message Bus
   Loaded: loaded (/usr/lib/systemd/user/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Mon 2018-05-21 10:39:42 CEST; 8h ago
     Docs: man:dbus-daemon(1)
 Main PID: 1484 (dbus-daemon)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.service
           ├─ 1484 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
           ├─ 2254 /usr/lib/dconf-service
           └─10765 /usr/bin/nautilus --gapplication-service
```

**Comment by chrissound** [comment]
I'm also encountering this issue on Nixos... Anyone else?

**Comment by chrissound** [comment]
https://serverfault.com/a/887298/135542

`export XDG_RUNTIME_DIR=/run/user/$(id -u)` seems to fix it...

**Comment by udovdh** [comment]
Not here. some dbus process is not properly started in the init 3/init 5 circus.
Same as gnome-shell not being fully killed when doing init 3.

**Comment by caleb-allen** [comment]
Also not working for me on Manjaro

**Comment by bphd** [comment]
Not working on Arch today (Freshly installed `gnome`, normal Arch repo.)

**Comment by adrelanos** [comment]
Issue on Debian `buster`.

    systemd-run --pty --same-dir --wait --collect --service-type=exec --pipe --user --quiet --nice=19 --property=MemoryAccounting=yes --property=MemoryHigh=300M --property=MemoryMax=500M --property=CPUAccounting=yes --property=CPUQuota=5% --property=CPUWeight=1 --property=CPUShares=2 --property=TasksAccounting=yes --property=TasksMax=200 --property=IOAccounting=yes --property=IOWeight=1 '--property=IOReadIOPSMax=/dev/disk/ 1K' -- mousepad

> Failed to start transient service unit: Process org.freedesktop.systemd1 exited with status 1

(related: https://github.com/systemd/systemd/issues/16180)

Resolved by installing package [dbus-user-session](https://packages.debian.org/buster/dbus-user-session).

    sudo apt update
    sudo apt install dbus-user-session

Didn't research security impact yet.

**Comment by machitgarha** [comment]
I don't really know either where to report it, or if it is a bug or not. However, it seems the problem is with the DBus service file, located both in `/usr/share/dbus-1/services/org.freedesktop.systemd1.service` and `/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service`. On my personal system, the file contains the following contents:

```
# Some comments here

[D-BUS Service]
Name=org.freedesktop.systemd1
Exec=/bin/false
User=root
```

As a result, when DBus tries to access it, `/bin/false` gets executed, and obviously, the exit code will be 1. I wonder why there is such a service at all. Perhaps it is an unimplemented stuff, or maybe it is a bug. Most likely the problems are from here.

Anyone can tell us more information on this?

**Comment by machitgarha** [comment]
Found the file in the repository with a simple search: [src/core/org.freedesktop.systemd1.service](https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/core/org.freedesktop.systemd1.service)

Maybe this issue should be reopened?

**Comment by Xavron** [comment]
> Found the file in the repository with a simple search: [src/core/org.freedesktop.systemd1.service](https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/core/org.freedesktop.systemd1.service)
> 
> Maybe this issue should be reopened?

I'm not sure if this should be an issue or not as well. However, I only have a problem when I go to boot older installed kernels even if it was just working and I install a new kernel. This error shows up and gnome fails to start. I feel like people may not be on the right track here.

Despite this, I can get it to boot into gnome desktop if I use an empty xorg.conf but that breaks the latest kernel so I haven't been able to win but only just looking here and there into it. There's a rather big disconnect there as to the actual thing that's happening compared to this log entry we all see.

Probably doesn't clear anything up for you but might as well with more questions possibly. Errors in logs aren't necessarily anything at all. I can put "errors" in logs all day long and they are just for development feedback or something is wrong and not necessarily what we think it might be.

It could be best to look at it from another angle.

**Comment by machitgarha** [comment]
@Xavron

Thanks for your reply. Maybe I didn't get you well, however, personally I think errors and even warnings should not be ignored. Yes, the issue may gone away by some magic tricks, but that doesn't necessarily mean that is the reason. We may find correct issues from unrelated ones as well.

The current issue might be an unrelated one, so I would open a new one on this after ensuring it doesn't already exist.

**Comment by machitgarha** [comment]
As the commit b895fa08e6809ab54e20888f7d01ae848272e981 tells (reverts 07125d24eedb71693b3bf2b1f0730cd01aaac2dd), the file is a stub service, and must be there for things to work properly (e.g. dbus-broker). So, yes, @Xavron, you were right. Also see #13396 and #11246.

**Comment by AlexFolland** [comment]
Why on earth are we letting systemd run `/bin/false` disguised as something that looks essential and produce an unintelligible error on everyone's system?

This has been a source of confusion for my particular issue for a while now, since it's one of only 2 errors that I see and it seemed to be the only one that could explain anything.  Now that I see that it doesn't explain anything because it's supposedly some fake error for no reason, my particular issue is even more confusing.

So since 2019, this .service file tries to launch and is `/bin/false` and always fails?  That's accepted in this project?  It seems insane to me.

**Comment by machitgarha** [comment]
@AlexFolland 

Well, the problem is more complicated than that. What starts a service in a system at boot time? Obviously Systemd. What if the service itself is Systemd (i.e. `org.freedesktop.systemd1`)? Is it possible for Systemd to start itself at boot time? Maybe, but that's not easy.

As far as I know, the sole purpose of the `org.freedesktop.systemd1` service file is to make interactions with Systemd possible. So, the `/bin/false` thing is just a stub executable, because Systemd as a service could not be started.

**Comment by AlexFolland** [comment]
Obviously interactions with systemd are not possible this way.  Whatever's trying to interact with it and getting `/bin/false` needs to be fixed, and it can't be fixed if the error is so cryptic.  I feel lucky that I stumbled upon this github issue ticket and you had posted that the exec line just points to `/bin/false`.  Otherwise, I may never have known why this error appeared.  Why would anything intentionally try to launch something that just leads to `/bin/false` anyway?  It still seems completely insane.  Why not instead just never try to launch this fake `org.freedesktop.systemd1` which just leads to `/bin/false`, and remove it from the project so nothing tries to do it and anything that tries to do it sees that such a thing doesn't exist?

**Comment by AlexFolland** [comment]
I read the introduction and did a page-search for `/bin/false`.  What am I supposed to see here that addresses what I said?

**Comment by machitgarha** [comment]
> Obviously interactions with systemd are not possible this way.

@AlexFolland, this is what you said. `org.freedesktop.systemd1` is an interface to interact with Systemd via DBus, and to my knowledge, it is the only purpose of this service file. The `/bin/false` thing is just a stub thing, it could `/dev/null`, or whatever. The Exec property is just to make the service file a valid one, and have nothing to do with starting or stopping Systemd, or DBus interactions with it.

**Comment by noahtallen** [comment]
I ran into this issue. I was trying to solve the following error which occurs when launching Flatpaks (My main goal has been getting Sway and Flatpak working smoothly together). _This error occurs not on startup, but after logging out and then logging back in._

```sh
$ flatpak run com.visualstudio.code
[2 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[2 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus
```

Following the suggestions in another thread, I added this to my profile to try to give DBUS a 
bit of a head start:

```sh
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
	# Sets the session bus address and another thing:
	export $(dbus-launch)
	export NSS_USE_SHARED_DB=ENABLED
fi
```

While that solved the issue of flatpaks not opening, it causes this error.

```sh
$ systemctl --user status pipewire
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1
```

Which obviously impacts a lot of things :)

It seems I can only have one of the two things working correctly, until I figure out a solution!

Thought I'd post to get more mentions of the issue in the search index. Will update if I find anything.

**Comment by timrichardson** [comment]
I am affected by this ubuntu problem: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491 where something is going wrong with systemd when starting a remote session via in my case nomachine, but other users report problems with vcn and x2go. All these start a session. Snaps don't start because they can't interact as expected with the user dbus, it seems. 
My logs have this, in the case of trying to start the firefox snap. 

in particular:

`Jun 15 13:09:30 ubuntu dbus-daemon[7531]: [session uid=1000 pid=7528] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
`
stood out to me. 
I don't understand this ticket; is this ticket relevant to the problem?
```

tim@ubuntu /usr/share/dbus-1/services $ systemd --version
systemd 249 (249.11-0ubuntu3.1)
```


```

Jun 15 13:09:30 ubuntu dbus-daemon[7531]: [session uid=1000 pid=7528] Activating service name='org.freedesktop.systemd1' requested by ':1.60' (uid=1000 pid=8624 comm="/snap/bin/firefox " label="unconfined")
Jun 15 13:09:30 ubuntu dbus-daemon[7531]: [session uid=1000 pid=7528] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Jun 15 13:09:30 ubuntu audit[8624]: AVC apparmor="DENIED" operation="capable" profile="/snap/core/13308/usr/lib/snapd/snap-confine" pid=8624 comm="snap-confine" capability=12 capname="net_admin"
Jun 15 13:09:30 ubuntu audit[8624]: AVC apparmor="DENIED" operation="capable" profile="/snap/core/13308/usr/lib/snapd/snap-confine" pid=8624 comm="snap-confine" capability=38 capname="perfmon"
Jun 15 13:09:30 ubuntu kernel: audit: type=1400 audit(1655262570.773:81): apparmor="DENIED" operation="capable" profile="/snap/core/13308/usr/lib/snapd/snap-confine" pid=8624 comm="snap-confine" capability=12 capname="net_admin"
Jun 15 13:09:30 ubuntu kernel: audit: type=1400 audit(1655262570.773:82): apparmor="DENIED" operation="capable" profile="/snap/core/13308/usr/lib/snapd/snap-confine" pid=8624 comm="snap-confine" capability=38 capname="perfmon"
```

**Comment by shadycuz** [comment]
I'm seeing something similar as @noahtallen when I open vscode. 

```
Jun 19 12:47:58 La-Laptop-wsl dbus-daemon[55478]: [session uid=1000 pid=55476] Activating service name='org.freedesktop.systemd1' requested by ':1.32' (uid=1000 pid=56281 comm="code -r . ")
```
Not sure what the fix is.

**Comment by linas** [comment]
In my case, either ` systemctl --user` or ` systemctl --user status` results in the dreaded
```
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```
So ... ???

**Comment by tonynajjar** [comment]
> In my case, either ` systemctl --user` or ` systemctl --user status` results in the dreaded
> 
> ```
> Failed to list units: Process org.freedesktop.systemd1 exited with status 1
> ```
> 
> I can fix this with
> 
> ```
> export XDG_RUNTIME_DIR=/run/user/$(id -u)
> ```
> 
> I have no clue why this env var is needed, why it was not set, or why it doesn't use the "obvious" default of the current login.

for me even this doesn't fix this anymore....

```
tony@tony-xmg-22:~$ echo $XDG_RUNTIME_DIR
/run/user/1000
tony@tony-xmg-22:~$ systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```
