### ISSUE TITLE
systemd spams "Failed to canonicalize path ..." (log_level=debug)

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5252]
See https://github.com/systemd/systemd/pull/5225#issuecomment-277883006

https://github.com/systemd/systemd/commit/17e78d1825bcc6cb9af25c9b1598ef32c82da6af#diff-fd9cf04cb73c7bdcada2908051aff13dR137 logs every failure (in debug mode)

30% of the logs looks like
```
Failed to canonicalize path /run/systemd/generator/test.socket.d: No such file or directory
```

I'm not sure this helps to debug something

**Comment by poettering** [comment]
@keszybz ?

**Comment by poettering** [comment]
Fix waiting in #5295

**Comment by evverx** [comment]
Closed by #5295

**Comment by MarcusCaepio** [comment]
Hi all,
I am running in the same problem on Ubuntu 18.04 LTS.
How can I fix this here? 

TIA,
Marcus

**Comment by keszybz** [comment]
@MarcusCaepio ask you distro maintainers to backport https://github.com/systemd/systemd/pull/5295/commits/09c624878abc325fc2768f3385988d6ceeaa2d87.
