### ISSUE TITLE
"localectl set-keymap <map>" doesn't create X11 keyboard snippet

### ISSUE THREAD

**Issue by sndirsch** [systemd/systemd#5256]
"localectl set-keymap <map>" doesn't write X11 keyboard snippet, if such a snippet does not exist yet. Workaround currently is to run

  "localectl set-x11-keymap us"

beforehand. I consider this a bug. Predefined X11 snippet is /etc/X11/xorg.conf.d/00-keyboard.conf

# localectl --version
systemd 228
[...]

**Comment by poettering** [comment]
Hmm? you mean, when the locale setting already is "foo", changing the locale setting to "foo" is a NOP, and doesn't write out the X11 snippet? I wouldn't consider that a bug though. I think it's entirely OK for localed to assume that if changes where made before they were made properly...

**Comment by sndirsch** [comment]
I'm sorry. I haven't tested correctly. This is indeed a duplicate of issue #5221. Feel free to close as such. In case the github issue tracker provides such a feature. Otherwise close as WONTFIX. Thanks for looking into this and prompt feedback!

**Comment by poettering** [comment]
ok, closing then.
