### ISSUE TITLE
Add a target to install tests

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#5257]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

===

Adding a target to install tests (not to be hooked up to install target). This way they can be shipped in a systemd-test package downstream, and can thus be of use in diagnosing user problems. As a side effect, with that package we can hook up the debian CI to run all tests as root.

**Comment by poettering** [comment]
hmm? what do you mean? why would you ever want to install tests? isn't debian running them during build? not grokking this...

If you want to make this installable, isn't this something you should do downstream?

**Comment by fsateler** [comment]
> hmm? what do you mean? why would you ever want to install tests?

We'd like to ship them in a separate systemd-tests package. glib does the same in debian. This has two benefits:

1. This makes it easier to hook up running the tests in CI, and thus run them as root.
2. One could ask users to run the relevant tests for bug reports, without having them recompile systemd.

> isn't debian running them during build?

Yes, but not as root.

> If you want to make this installable, isn't this something you should do downstream?

We could do that,  but I think it would be interesting for other distributions as well.

**Comment by poettering** [comment]
hmm, ok.

**Comment by mbiebl** [comment]
The alternative is to make autopkgtest run the test-suite as root. This requires an additional build in autopkgtest. Something like
```
$ cat debian/tests/build
#!/bin/sh
env -u LD_PRELOAD make check

$ cat debian/tests/control
Tests: build
Depends: @, @builddeps@, systemd
Restrictions: build-needed
```

This requires more ressources though (two addtional builds per commit). So this needs input from @martinpitt 


@martinpitt what approach would you prefer?

**Comment by martinpitt** [comment]
@mbiebl: I'd prefer to only run the tests again as root if we have a built tree already -- that way we'd run them for upstream in PRs, but skip them downstream when running in "download source package" mode. Something like
```
Test-Command: [ ! -e Makefile ] || make check
Depends: @builddeps@
Restrictions: needs-root
Features: test-name=unit-tests-root
```
WDYT?

**Comment by martinpitt** [comment]
@mbiebl: that is, having a `systemd-tests` binary package sounds totally fine to me -- with "prefer" I just meant that I wouldn't want to build the tree again just for this; it takes painfully long as it is already.

**Comment by mbiebl** [comment]
@martinpitt I would really like to run "make check" as root on all downstream (i.e. Debian) architectures

**Comment by keszybz** [comment]
+1 to adding a install-tests target. It should be pretty simple, since all tests are gathered in tests. I guess manual_tests should not be installed.

Note:
```
AM_TESTS_ENVIRONMENT = \
        export SYSTEMD_KBD_MODEL_MAP=$(abs_top_srcdir)/src/locale/kbd-model-map; \
        export SYSTEMD_LANGUAGE_FALLBACK_MAP=$(abs_top_srcdir)/src/locale/language-fallback-map ;\
```
This needs to be adjusted somehow if we are to install tests. Maybe do some `getenv`, and look in the real filesystem otherwise.

**Comment by fsateler** [comment]
@keszybz AFAICT, those environment variables are to allow running the tests without systemd installed. I figure it is ok to require an installed systemd for running the installed testsuite. IE, the functions querying those envvars already have a real filesystem fallback.

**Comment by keszybz** [comment]
Oh, indeed. I copy-pasted without looking what the variables really do.
