### ISSUE TITLE
Permissions on `/var/log/journal` are not correctly set by systemd-tmpfiles

### ISSUE THREAD

**Issue by nlewo** [systemd/systemd#5264]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231, 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> NixOS

### In case of bug report: Expected behaviour you didn't see

> `systemd-journal` group should have `r-x` permissions on `/var/log/journal`

### In case of bug report: Unexpected behaviour you saw

> ACLs permissions on the primary group (which is `systemd-journal`) are `---`:
```
# getfacl /var/log/journal
# file: var/log/journal/
# owner: root
# group: systemd-journal
# flags: -s-
user::rwx
group::---
group:wheel:r-x
group:adm:r-x
mask::r-x
other::r-x
default:user::rwx
default:group::---
default:group:wheel:r-x
default:group:adm:r-x
default:mask::r-x
default:other::---

# ls -l /var/log
total 16
drwxr-sr-x+ 3 root systemd-journal 4096 Feb  7 20:55 journal

```

 I think this is due to:
- `/var/log/journal` has been created with permissions `700`
- the execution order of `tmpfiles.d` directives which has been:
```
...
Running create action for entry a /var/log/journal
Setting default ACL u::rwx,g::---,g:wheel:r-x,g:adm:r-x,m::r-x,o::--- on /var/log/journal.
...
Running create action for entry z /var/log/journal
"/var/log/journal" has right mode 42755
```

The first rule set the primary group to `---` while the second rule only sets the mask.

### In case of bug report: Steps to reproduce the problem

> Create the file `/var/log/journal` with permissions `700`.

**Comment by shaba** [comment]
reopen please.
after this commit i have a issue:
```
# systemd-tmpfiles --create /lib/tmpfiles.d/systemd.conf 
Failed to parse ACL "d:group::r-x,d:group:adm:r-x,d:group:wheel:r-x": Invalid argument. Ignoring
Failed to parse ACL "group::r-x,group:adm:r-x,group:wheel:r-x": Invalid argument. Ignoring

```

**Comment by nlewo** [comment]
@shaba sorry, I'm not able to test it now with `systemd 233` (I only tested it with `systemd 232` and it worked). 
If it is easy for you to try this `/lib/tmpfiles.d/systemd.conf` file with `systemd232`, do you also observe an issue?

**Comment by shaba** [comment]
Yes, systemd-232 run this config without error.

**Comment by poettering** [comment]
@shaba is it possible that your system lacks the system groups mentioned in that ACL expression?

I am not sure why we should leave this specific issue open. The bug it was about appears fixed, but the issue @shaba pointed out appears to be something different.

**Comment by poettering** [comment]
@keszybz do you know more about this?

**Comment by poettering** [comment]
Closing due to lack of response.
