### ISSUE TITLE
test-execute fails if capsh binary is not installed 

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5273]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

git master (8a50cf695)

### Used distribution

Debian unstable

Running test-execute as *root* fails, if the capsh binary is not installed.  In Debian, capsh is provided by libcap2-bin and not installed by default.
The failure is
```
Assertion 'service->main_exec_status.status == status_expected' failed at src/test/test-execute.c:70, function check(). Aborting.
```
Full test-suite log is attached.

I guess the test-suite should not fail if capsh is missing, or the requirement documented in README.

[test-execute.log.txt](https://github.com/systemd/systemd/files/761469/test-execute.log.txt)

**Comment by martinpitt** [comment]
Seems actually better to just add it as a test dep? Otherwise we'd silently run fewer tests?

**Comment by mbiebl** [comment]
I assume the intention of
https://github.com/systemd/systemd/blob/master/src/test/test-execute.c#L364

was to make the capsh dependency optional. I'm fine with making a capsh a hard dependency for running the tests. But in that case, that check can be removed.
