### ISSUE TITLE
sd_bus_slot_get_description should return a const string

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#528]
`sd_bus_slot_get_description` should return a `const char**`

(same as `sd_bus_get_description` already does)

**Comment by poettering** [comment]
#529 is merged, Closing.

**Comment by daurnimator** [comment]
:+1:

**Comment by keszybz** [comment]
> This changes API, but ABI stays stable. I think this is fine, but I
> wouldn't mind bumping SONAME.

No need to bump soname. There is no difference in the compilation output. So it's fine as is.
