### ISSUE TITLE
systemd/units/systemd-nspawn@.service.in comment unclear

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#5286]
Hi,

this is an RFE against the current git HEAD.

The comments in systemd-nspawn@.service.in say:
    # Enforce a strict device policy, similar to the one nspawn configures
    # when it allocates its own scope unit. Make sure to keep these
    # policies in sync if you change them!

It is not clear to the uneducated reader what "keeping in sync" means. In sync with each other? Or in sync with some configuration outside the file?

I'd appreciate if things were a bit more verbose in this regard.

Greetings
Marc

**Comment by poettering** [comment]
I am not sure how to make this clearer: to me it's obvious that the two policies are meant that are described here: the one in the unit file, and the one nspawn configures when it allocates its own scope unit. I am not sure how one could misunderstand them? I mean, we only reference two policies and then refer to "these policies" which should be pretty clear?

**Comment by fsateler** [comment]
Isn't that comment intended for systemd developers? If so, then that comment maybe should not be part of the final unit.
