### ISSUE TITLE
ConditionCapability=!CAP_SYS_ADMIN disables unit also for non-privileged users

### ISSUE THREAD

**Issue by tanuk** [systemd/systemd#5296]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

### Used distribution

Debian testing

### In case of bug report: Expected behaviour you didn't see

Adding `ConditionCapability=!CAP_SYS_ADMIN` to `/usr/lib/systemd/user/pulseaudio.socket` disables the unit for root, while allowing regular users to use the unit.

### In case of bug report: Unexpected behaviour you saw

Adding `ConditionCapability=!CAP_SYS_ADMIN` to `/usr/lib/systemd/user/pulseaudio.socket` makes the socket unit not start. `systemctl --user status pulseaudio.socket` prints the following:

    ● pulseaudio.socket - Sound System
       Loaded: loaded (/usr/lib/systemd/user/pulseaudio.socket; disabled; vendor preset: enabled)
       Active: inactive (dead)
    Condition: start condition failed at Thu 2017-02-09 21:27:34 EET; 15min ago
               └─ ConditionCapability=!CAP_SYS_ADMIN was not met
       Listen: /run/user/1000/pulse/native (Stream)

### In case of bug report: Steps to reproduce the problem

1. Add `ConditionCapability=!CAP_SYS_ADMIN` to `/usr/lib/systemd/user/pulseaudio.socket` (hopefully you already have the file installed).
2. As a regular user: `systemctl --user stop pulseaudio.service pulseaudio.socket`
3. `systemctl --user start pulseaudio.socket`
4. `systemctl --user status pulseaudio.socket`
5. Observe that the unit didn't start, because the start condition failed.

**Comment by poettering** [comment]
This is actually intended. The condition checks the capability bounding set, not the effective capability set.

To quote the man page:

> ConditionCapability= may be used to check whether the given capability exists in the capability bounding set of the service manager (i.e. this does not check whether capability is actually available in the permitted or effective sets, see capabilities(7) for details). Pass a capability name such as "CAP_MKNOD", possibly prefixed with an exclamation mark to negate the check.

The bounding set is what your processes could possibly ever acquire as caps, for example due to SUID privilege acquiring, and not what you already have.

My guess is that your usecase would be better covered by what is requested in #5187.

I am taking the liberty to close this as a RFE duplicated of that issue. I hope that's OK.

**Comment by tanuk** [comment]
I did read the man page, but clearly didn't pay enough attention - sorry for the noise.
