### ISSUE TITLE
`set-log-level debug` breaks SystemCallFilter=whitelist-without-socket-getsockopt

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5299]
```
systemd-analyze set-log-level debug

cat <<'EOF' >/etc/systemd/system/a.service
[Service]
SystemCallFilter=@basic-io seccomp # seccomp is the regression. I'll file a bug soon
ExecStart=/bin/date
EOF

systemctl start a
```
```
SECCOMP auid=4294967295 uid=0 gid=0 ses=4294967295 pid=409 comm="(date)" exe="/usr/lib/systemd/systemd" sig=31 arch=c000003e syscall=41 compat=0 ip=0x7f4990719187 code=0x0
```
`41` is the `socket`
`@network-io` fixes the issue

See the details: https://github.com/systemd/systemd/issues/3970#issuecomment-240423469

**Comment by poettering** [comment]
hmm, yeah, well, we are documenting this already in vague words. From the man page, about SystemCallFilter=

> Note that strict system call filters may impact execution and error handling code paths of the service invocation. Specifically, access to the execve system call is required for the execution of the service binary -- if it is blocked service invocation will necessarily fail. Also, if execution of the service binary fails for some reason (for example: missing service executable), the error handling logic might require access to an additional set of system calls in order to process and log this failure correctly. It might be necessary to temporarily disable system call filters in order to simplify debugging of such failures.

I am not sure this really is a bug. I mean, our options are limited: we could always whitelist socket/setsockopt() and friends. But that sucks, as we'd only whitelist it for an error path and for the clean path it's entirely redundant... hence I opted to just document this (in admittedly vague words). i.e. not treat this as a true error, but more something like a debugging nastiness...

**Comment by evverx** [comment]
> and for the clean path it's entirely redundant

We print this log message:
```
a.service: Executing: /bin/date
```
And I should whitelist `socket/getsockopt` always (not for error path only)

**Comment by evverx** [comment]
It should probably be documented but meh
