### ISSUE TITLE
SystemCallFilter=whitelist requires `seccomp`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5300]
```
[Service]
SystemCallFilter=@basic-io @network-io # why @network-io? see #5299
ExecStart=/bin/date
```
```
Feb 08 08:42:52 audit[207]: SECCOMP auid=4294967295 uid=0 gid=0 ses=4294967295 pid=207 comm="(date)" exe="/usr/lib/systemd/systemd" sig=31 arch=c000003e syscall=317 compat=0 ip=0x7f59af27abf9 code=0x0
```
`317` is the `seccomp`

`v232` works fine

(by "works fine" I mean `systemd` starts the `date`, then `seccomp` blocks `syscall=12` as expected)

**Comment by evverx** [comment]
Environment:
```
$ cat /proc/version
Linux version 4.9.6-200.fc25.x86_64 (mockbuild@bkernel01.phx2.fedoraproject.org) (gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC) ) #1 SMP Thu Jan 26 10:17:45 UTC 2017

$ rpm -q libseccomp
libseccomp-2.3.1-1.fc25.x86_64
```

**Comment by evverx** [comment]
I think this is the result of https://github.com/systemd/systemd/pull/4991
But I didn't bisect.

**Comment by evverx** [comment]
This regression was introduced in 469830d1426a91e0

**Comment by evverx** [comment]
The `x86_64`-"fix"
```diff
diff --git a/src/shared/seccomp-util.c b/src/shared/seccomp-util.c
index e35f184..9d42306 100644
--- a/src/shared/seccomp-util.c
+++ b/src/shared/seccomp-util.c
@@ -38,8 +38,8 @@ const uint32_t seccomp_local_archs[] = {

 #if defined(__i386__) || defined(__x86_64__)
                 SCMP_ARCH_X86,
-                SCMP_ARCH_X86_64,
                 SCMP_ARCH_X32,
+                SCMP_ARCH_X86_64,

```

**Comment by poettering** [comment]
Ah, you mean, the native arch should always be listed last? makes sense...

**Comment by poettering** [comment]
Prepped a fix in #5306.

**Comment by evverx** [comment]
@poettering , why not
https://github.com/systemd/systemd/issues/4575#issuecomment-273572780
> One possible workaround to get you more control over filter creation would be to create multiple filters, one for each arch/ABI, and then merge them at the end using seccomp_merge(3). This would allow you better control and error reporting.

?

**Comment by poettering** [comment]
> why not

well, that works too, but I see no huge benefit of doing that... Happy to review/merge a patch though! ;-)
