### ISSUE TITLE
resolved: when resolv.conf is consumed, detect per-interface nameservers

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#5305]
### Submission type

  - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Arch Linux

### RFE

When `systemd-resolved` reads an existing `/etc/resolv.conf` (independently managed by e. g. NetworkManager), it treats all nameservers as "system DNS servers", i. e. slowly alternates between them in a round-robin mode.

If a user connects to a VPN which has its own DNS server for internal services, it is added to the same list and also considered a "system DNS server". This is incorrect, because:
1. the newly-added nameserver does not resolve Internet domains;
2. if resolved switches to another "system DNS server", internal VPN domains stop resolving.

Because `/etc/resolv.conf` is not going away anywhere soon, I would like to see a heuristic that detects "per-interface" nameservers imported from `/etc/resolv.conf`. For example, if a nameserver's address belongs to the broadcast domain of an existing interface, then it is a per-interface nameserver (or some other heuristic if the above-described is conceptually wrong — I'm not a networking expert).

**Comment by poettering** [comment]
well, NM can push its data to resolved already directly already. That's a much better solution, and works today.

I am not a big fan of such heuristics I must say... And I am pretty sure we should not be overly magic of this, after all /etc/resolv.conf has pretty clear semantics, and we already depart a bit from it, but I am not sure we should depart any further?

**Comment by intelfx** [comment]
I didn't see that NM<->resolved integration. Unfortunately it works for NM only (which is not always the case, e. g. NM's plugin for OpenVPN lacks many useful features). Maybe you will like the idea of adding a resolvconf(8)-like shell-friendly interface for pushing configuration to resolved instead (which could then be used instead of resolvconf(8) in OpenVPN up scripts and suchlike)?

**Comment by intelfx** [comment]
Obsolete due to much improved NM<->resolved integration and resolved itself actually having a `resolvconf`(1) interface, closing.
