### ISSUE TITLE
RFE: Document NOTIFY_SOCKET

### ISSUE THREAD

**Issue by vladev** [systemd/systemd#5307]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch Linux

Please, document how `NOTIFY_SOCKET` works so the notification mechanism can be implemented in other languages and runtimes. Right now, the only way to do that is to reverse-engineer `libsystemd/sd-daemon/sd-daemon.c`

**Comment by poettering** [comment]
It is actually documented, and has been since day one:

https://www.freedesktop.org/software/systemd/man/sd_notify.html#Notes

It's extremely simple, and I am not sure what else we should document of what it actually does...

**Comment by poettering** [comment]
I mean, we are happy to extend the paragraph if there's info missing. But I am not sure what would be missing there. Any suggestion?

**Comment by vladev** [comment]
Oh, I've missed that. Maybe "Notes" isn't the best section name for it. There are some details around when to send credentials and when they are not needed that I'm missing. It might be worth repeating a few sentences from the manpages around unix sockets. Like what should be done when the socket is abstract, how to pass the FDs, when and how to pass the PID and credentials. I know those things are obvious to people doing mostly socket programming, but that's not the case for everyone else. An example implementation in a higher level language (e.g. Python) might be a good addition, too.

Thank you for the quick response.

**Comment by poettering** [comment]
Well, I am not sure it's a good idea to to make the sd_listen_fds() an article about UNIX socket programming, that's after all documented in detail elsewhere already. 

It's actually by intention that the section about internals is brief, as the man page itself is about a specific implementation of this logic. Moreover, it is assumed that folks reimplementing this have a higher level of expertise anyway, and hence already know UNIX socket programm well enough.

That all said, please send a patch for the man page, and we'll merge if it's good!

**Comment by poettering** [comment]
(note btw that you don't actually have to deal with creds at all... the kernel implicitly attaches creds to all AF_UNIX datagrams, hence you can completely ignore the concept exists, and seimply use send()/sendto()/write() to send your message)
