### ISSUE TITLE
kvm is detected as qemu

### ISSUE THREAD

**Issue by rubenk** [systemd/systemd#5318]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> buildroot 2017.02-git

### In case of bug report: Expected behaviour you didn't see

> systemd[1]: Detected virtualization kvm.

### In case of bug report: Unexpected behaviour you saw

> systemd[1]: Detected virtualization qemu.

Looking at the code at https://github.com/systemd/systemd/blob/master/src/basic/virt.c#L166, it checks /sys/class/dmi/id/product_name, which contains qemu-kvm's machine type:
```
# cat /sys/class/dmi/id/product_name
Standard PC (i440FX + PIIX, 1996)
# cat /sys/class/dmi/id/sys_vendor 
QEMU
```

This is with qemu 2.80.

If I recall correctly this used to work, probably because the cpuid flags where checked first before dmi, and this is a regression caused by  050e65ada2e0023a1a4c953522f39846c6bdebf8

**Comment by keszybz** [comment]
Indeed, the same with F25/rawhide.

**Comment by poettering** [comment]
@eworm-de maybe something for you?

**Comment by eworm-de** [comment]
With version 5.0 Virtualbox started to support different hypervisors, including `kvm` on linux. With this change `systemd-detect-virt` (and the library) reported `kvm`, which broke the virtualbox guest service `vboxservice.service` as it has condition `ConditionVirtualization=oracle`.

So we decided to swap order for detecting via `dmi` or `cpuid`.

This fixed the detection of virtualbox and obviously changed the detection of `qemu` from `kvm` to `qemu`. I think this is the correct behaviour, though: In the case described above the machine actually *is* started with `qemu`, no?

We already use this behaviour for the Arch Linux `qemu` package: `QEMU Guest Agent` has a condition `ConditionVirtualization=qemu` to start for `qemu` machines only. ([qemu-ga.service](https://git.archlinux.org/svntogit/packages.git/plain/trunk/qemu-ga.service?h=packages/qemu))

So I do not think this is a regression but expected behaviour.

**Comment by rubenk** [comment]
The machine is started by qemu with kvm acceleration, so the hypervisor used is kvm.
More importantly, it has always been reported as kvm, that's why it is a regression.

One thing this breaks is machine-id-setup, which normally takes the uuid set by kvm as machine-id, but now instead generates a random one. There are probably more services keying on `ConditionVirtualization=kvm`.

qemu can also be used without a hypervisor, just as an emulator with TCG. This is correctly detected as qemu.

**Comment by poettering** [comment]
I tend to agree with @rubenk. I think we should return "kvm" if it's qemu-kvm, return "virtualbox" if it's vbox on kvm or anything else, and "qemu" only if its pure non-kvm qemu.

Yes, it's a bit quirky, but I think it would be most in line with people's expectations and be compatible with the status quo ante.

**Comment by eworm-de** [comment]
Initially my patch added a quirk for virtualbox. It was you @poettering who suggested to simply reverse the cpuid and dmi checks (see #1995).

Reverting the behaviour for qemu would break the use case for the qemu geust agent, though.

As people will continue complaining one way or another... Does it make sense to...
* ... either add the hypervisor to the result, so returning `oracle-kvm` or `qemu-kvm`...
* ... or add a new binary `systemd-detect-hypervisor` along with a new condition `ConditionHypervisor=` that return `kvm` independent from Virtualbox and Qemu?

**Comment by poettering** [comment]
> Initially my patch added a quirk for virtualbox. It was you @poettering who suggested to simply reverse the cpuid and dmi checks (see #1995).

Yeah, I accept the blame for that. The effects of this weren't entirely clear to me then.



> As people will continue complaining one way or another... Does it make sense to...
> 
>     ... either add the hypervisor to the result, so returning oracle-kvm or qemu-kvm...
>     ... or add a new binary systemd-detect-hypervisor along with a new condition ConditionHypervisor= that return kvm independent from Virtualbox and Qemu?

So, both of these options would be admittedly technically more correct, but I am not sure I like it, as it adds even more settings to this, which I'd rather avoid.



> Reverting the behaviour for qemu would break the use case for the qemu geust agent, though.

Could you elaborate on this? What precisely do you mean? If we could only distinguish "qemu on kvm", "pure qemu" and "virtualbox on kvm or not on kvm",  that wouldn't suffice for which usecase precisely?

**Comment by eworm-de** [comment]
> > Reverting the behaviour for qemu would break the use case for the qemu geust agent, though.
>
> Could you elaborate on this? What precisely do you mean? If we could only distinguish "qemu on kvm", > "pure qemu" and "virtualbox on kvm or not on kvm", that wouldn't suffice for which usecase precisely?

As mentioned earlier the Arch Linux `qemu` package has a service file for `qemu guest agent` that depends on `ConditionVirtualization=qemu` (see [qemu-ga.service](https://git.archlinux.org/svntogit/packages.git/plain/trunk/qemu-ga.service?h=packages/qemu)). Reverting the change for qemu requires to change the condition to
```
|ConditionVirtualization=kvm
|ConditionVirtualization=qemu
```
But that would try to start the user agent for non-`qemu` systems that use `kvm`.

**Comment by eworm-de** [comment]
Well, possibly we should just use `ConditionPathExists=/dev/virtio-ports/org.qemu.guest_agent.0` for the service condition? Anybody around who is familiar with `qemu` and how the `guest agent` communicates with the host?

**Comment by rubenk** [comment]
Guest-agent indeed communicates over virtio-serial, so that might be a better solution.

**Comment by rubenk** [comment]
> But that would try to start the user agent for non-qemu systems that use kvm.

What systems are those?

**Comment by eworm-de** [comment]
> > But that would try to start the user agent for non-qemu systems that use kvm.
> 
> What systems are those?

Good question... :) I thought of `libvirt` and friends, but in fact that just depends on `qemu`. So probably there are none.

**Comment by poettering** [comment]
> |ConditionVirtualization=kvm
> |ConditionVirtualization=qemu
> 
> But that would try to start the user agent for non-qemu systems that use kvm.

Well, I'd declare that "kvm" would only be used for qemu-kvm, and not any other kvm-based emulators. For example, should we add support for kvmtool one day, then we should expose it as "kvmtool", and not "kvm"... 

So, the identifier "kvm" would actually always mean qemu-kvm for us. Yes, it's a bit of a misnomer, but I think that's OK and due to history... Wouldn't that be acceptable for your usecase, too?

**Comment by rubenk** [comment]
Thanks for the fix, but unfortunately this breaks other scenarios.

The first is that the dmi info in /sys/class/dmi/id can be overridden from libvirt or the qemu command line. I work for a cloud provider where we did override the product_name and sys_vendor and set it to 'VPS' and 'Tilaa'. Perhaps not the best of ideas, but at the time we did that we had no idea that this could influence systemd's virt detection a few years later. Heh, systemd didn't exist at the time.

Second, we're not the only ones doing that. Red Hat sets the product_name to KVM and the sys_vendor to Red Hat.

I can also imagine that there are companies using KVM that use a different userland tool instead of QEMU to drive it, Google Compute comes to mind.

So I propose we fix this this differently, by assuming that a hypervisor is KVM if it reports "KVMKVMKVM" in its cpuid leaf, except if it reports ""innotek GmbH" in dmi, in which case it is virtualbox.

This logic is somewhat similar to what virt-what does in http://git.annexia.org/?p=virt-what.git;a=blob;f=virt-what.in;h=1a373ed917597a8341bbd3b1c3100c00851046bf;hb=HEAD

This would all have been easier if Virtualbox picked its own cpuid instead of trying to behave like kvm, but not quite, but let's not get into that ;)

**Comment by eworm-de** [comment]
Oh dear... Never ending story. :-p

> This would all have been easier if Virtualbox picked its own cpuid instead of trying to behave like kvm, but not quite, but let's not get into that ;)

Actually Virtualbox does use KVM, so the cpuid is correct.

**Comment by rubenk** [comment]
> Oh dear... Never ending story. :-p

Yeah sorry :)

> Actually Virtualbox does use KVM, so the cpuid is correct.

By that logic, why don't we just report is as KVM?

**Comment by eworm-de** [comment]
> > Actually Virtualbox does use KVM, so the cpuid is correct.
>
> By that logic, why don't we just report is as KVM?

Because Virtualbox guest service depends on it with `ConditionVirtualization=`.

Well, on the other side... We could make `systemd-detect-virt` to report `kvm` even for Virtualbox... This needs proper documentation of course. Virtualbox guest service could depend on `ConditionPathExists=/dev/vboxguest`, which is required for communication anyway.

**Comment by eworm-de** [comment]
Ok, prepared two commits that handle the situation in different ways: ffeee47565b079444aa21b379613196a9e0196b0 and 334d2f56400b0f895163dae06b3376ef5d04ae0f

Any opinion on this?

**Comment by rubenk** [comment]
ffeee47 looks good. I think that also means that we can remove 'KVM' from `dmi_vendor_table[]` right?

**Comment by poettering** [comment]
ffee47 looks good to me.

**Comment by poettering** [comment]
Would be great to submit that as PR!

**Comment by eworm-de** [comment]
Sure, wanted a preference on which one to submit. ;)
