### ISSUE TITLE
.mkosi/mkosi.arch doesn't work, as XSL stylesheets appear to be missing

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#5324]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> master (6818c54ca)

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> It should be possible to build a systemd development image with `mkosi --default .mkosi/mkosi.arch`.

### In case of bug report: Unexpected behaviour you saw

> The build fails when trying to build the documenation, since that seems to require internet access (xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl) and `mkosi` runs `systemd-nspawn` with `--private-network`.

### In case of bug report: Steps to reproduce the problem

> `sudo mkosi --default .mkosi/mkosi.arch`

**Comment by poettering** [comment]
> The build fails when trying to build the documenation, since that seems to require internet access (xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl) and mkosi runs systemd-nspawn with --private-network.

This is easy to fix: the docbook stylesheet package needs to be included in the build. xsltproc only try to acquire them from the network if they are not available locally. On Fedora they are shipped in the "docbook-style-xsl" package.

If we need network for building I'd consider that a bug in our build scripts.

**Comment by lucaswerkmeister** [comment]
Well, the `mkosi.arch` default file includes the `docbook-xsl` package, which includes `/usr/share/xml/docbook/xsl-stylesheets-1.79.1/html/docbook.xsl`, but I still get the build error…

On the other hand – outside of `mkosi`, this succeeds:
```sh
touch man/journalctl.xml && sudo systemd-run -p User=$USER -p PrivateNetwork=yes -t -p WorkingDirectory=$PWD make man/journalctl.1
```

And yet, in `mkosi`, I get this:
```
  GEN      man/systemd.index.xml
  XSLT     man/systemd.index.html
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl"
compilation error: file ./man/custom-html.xsl line 24 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl
make[2]: *** [Makefile:26775: man/systemd.index.html] Error 5
make[1]: *** [Makefile:22615: all-recursive] Error 1
make: *** [Makefile:10163: all] Error 2
```

**Comment by agners** [comment]
I see this issue also every now and then. I can reproduce the issue locally when files in /etc/xml are missing. As far as I can tell this are generated files. Further comparison between working and non-working log output show that when docbook-xsl and docbook-xml are installed towards the end of the rootfs generation the issue does not appear. I assume there are missing dependencies in the ArchLinux packages.

**Comment by agners** [comment]
It seems that sed is missing. I added a bug report in the ArchLinux tracker:
https://bugs.archlinux.org/task/56343

**Comment by agners** [comment]
However, reinstalling docbook-xsl in mkosi.build and using --with-network works around the issue for now:

    pacman -S --noconfirm docbook-xsl

(--with-network does not help to solve the underlying issue, xsltproc seems not actually access the file on the web, even if there is connectivity... but network is required by pacman to reinstall docbook-xsl)

**Comment by lucaswerkmeister** [comment]
Thank you so much for looking into this @falstaff84 – Arch package is fixed and `mkosi --default .mkosi/mkosi.arch -ifT shell` (@poettering’s “favourite command” according to systemd/mkosi@a5cad1f814 ;) ) works!

I did find one other bug, I think, but I’ll create a separate ticket for that (edit: #7367). This one is done IMHO.
