### ISSUE TITLE
tunnel interface down by default

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5327]
### Submission type

  - [ X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231-9ubuntu3

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> the tun0 interface should be UP after boot.

### In case of bug report: Unexpected behaviour you saw

> the tun0 interface is DOWN

### In case of bug report: Steps to reproduce the problem
Create following simple unit tun.network:

[Match]
Name=tun0

[Network]
Address=192.168.0.1
IPMasquerade=yes

The expectation is that this tunnel interface will be always in UP state after boot so it can be used by other programs. Unfortunately I have to manually issue "sudo ip link set tun0 up" to make it work.

This seems to be related to #425 although there it was bridge and here is tunnel. Is there some other way to force particular interface to be always UP besides workaround oneshot unit described in #425?

**Comment by poettering** [comment]
@ssahani any idea?

**Comment by ssahani** [comment]
Ok when we reboot or first create the tun interface we have like this.
```
4: tun0: <NO-CARRIER,POINTOPOINT,MULTICAST,NOARP,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 500
    link/none
```
I assume this is in your case.

But when we attach a userspace program to it the state changes to `UP`. 
```
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 500
    link/none 
    inet6 fe80::170c:9490:6a71:acf0/64 scope link flags 800 
       valid_lft forever preferred_lft forever
```

**Comment by ghost** [comment]
You're right - the issue was indeed with userspace program. The interface is still in state UNKNOWN  ("ip a") but everything else works as expected so closing this for now. Btw, "networkctl" show interface as "routable    configured" so it's likely cosmetic issue with iproute2.

Thank you for clarification!
