### ISSUE TITLE
Provide udev_device_get_sysattr_value_binary to deal with binary attribute values

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#5329]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian

`udev_device_get_sysattr_value` doesn't deal well with binary attributes. There is no way to know the length of the buffer that it returns, so for the following attribute:

```
$ hd /sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6:1.1/0003:0C45:7402.001B/report_descriptor 
00000000  06 00 ff 09 01 a1 01 09  01 15 00 26 ff 00 75 08  |...........&..u.|
00000010  95 08 81 02 09 01 95 08  91 02 05 0c 09 00 15 80  |................|
00000020  25 7f 75 08 95 08 b1 02  c0                       |%.u......|
00000029
```

clients will only be able to safely use the first byte of the result. Something like `const char* udev_device_get_sysattr_value_binary(struct udev_device *udev_device, const char *sysattr, off_t *size)` which writes to `*size` would be handy.

References:
 * https://bugzilla.redhat.com/show_bug.cgi?id=1302359
 * https://github.com/pyudev/pyudev/issues/143

**Comment by poettering** [comment]
ummh, this becomes pretty specific to some kinds of devices, not sure whether involving udev in that is really a good idea. If your attributes are not of the "simple" kind, then libudev can't cache them, and often they come with peculiar semantics (for example the PCI memory ones may trigger hw issues). 

My suggestions would be for folks who want to access these attributes to just do it yourself via the provided syspath...

**Comment by yrro** [comment]
That makes sense. It seems I forgot to ever create a PR to mention this suggestion in the documentation...
