### ISSUE TITLE
Configure option --without-bashcompletion not behaving correctly

### ISSUE THREAD

**Issue by Fredrik89** [systemd/systemd#533]
We don't need to install bash completion files on our target system since it does not use bash (nor zsh). However using the configure option --without-bashcompletion does NOT exclude these files from being installed. Instead they are installed to some default path ending with 'no' 

In './configure --help' it is specified that " --without-PACKAGE        do not use PACKAGE (same as --with-PACKAGE=no)" so that explains where the 'no' comes for, but it is not handled properly.

Same should go for zsh completion files that behaves identically.

**Comment by poettering** [comment]
#888 is merged now, closing.
