### ISSUE TITLE
tx-tcp-segmentation disabled for interfaces with udev 232.15

### ISSUE THREAD

**Issue by hkbakke** [systemd/systemd#5334]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with
> 232.15

### Used distribution
Debian Stretch amd64 (testing)¨
Linux gw 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

### In case of bug report: Expected behaviour you didn't see
TCP segmentation offload should be enabled for all interfaces supporting it, including bonds, by default.

<pre>
tcp-segmentation-offload: on
        tx-tcp-segmentation: on
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp-mangleid-segmentation: off
        tx-tcp6-segmentation: on
</pre>

### In case of bug report: Unexpected behaviour you saw
TCP segmentation offload is disabled by defaults for physical nics (in my case e1000e and igb) and bond-interfaces (and perhaps more interface types). 

Result of ethtool -k <if>
<pre>
tcp-segmentation-offload: on
        tx-tcp-segmentation: off <---- this 
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp-mangleid-segmentation: off
        tx-tcp6-segmentation: on
</pre>
### In case of bug report: Steps to reproduce the problem

I see this on both my Debian Stretch systems (physical hardware) with systemd 232.15. Downgrading udev/libudev1 to 231.10 from Debian snapshots reverts to the old behaviour of not disabling tso.

**Comment by poettering** [comment]
@ssahani sounds like something for you?

**Comment by ssahani** [comment]
This is fixed by 45d34fa7fb9f587f09e8cca882966050b4cbb5be. @hkbakke ?

**Comment by hkbakke** [comment]
That seems exactly like it, yes! Is that fix in any released code except master?

**Comment by poettering** [comment]
$ git describe 45d34fa7fb9f587f09e8cca882966050b4cbb5be
v232-80-g45d34fa

So no, this hasn't been released yet. I is going to be part of the (so far unreleased) v233 only.
