### ISSUE TITLE
Add hwdb rules for USB smartcards

### ISSUE THREAD

**Issue by pwithnall** [systemd/systemd#5349]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

git master (`v232-910-gb1d7520`)

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Fedora 25

### RFE

It would be good to get the equivalent of the following udev rules into the hwdb, which I believe is the right place for them; each device needs tagging with `ID_SMARTCARD_READER`. However, I’m not sure of the best way to put them in the hwdb, since no relevant `.hwdb` file exists yet.

```
SUBSYSTEM!="usb", GOTO="gnupg_rules_end"
ACTION!="add", GOTO="gnupg_rules_end"

# USB SmartCard Readers
## Crypto Stick 1.2
ATTR{idVendor}=="20a0", ATTR{idProduct}=="4107", ENV{ID_SMARTCARD_READER}="1", ENV{ID_SMARTCARD_READER_DRIVER}="gnupg", GROUP+="plugdev", TAG+="uaccess"
## Nitrokey Pro
ATTR{idVendor}=="20a0", ATTR{idProduct}=="4108", ENV{ID_SMARTCARD_READER}="1", ENV{ID_SMARTCARD_READER_DRIVER}="gnupg", GROUP+="plugdev", TAG+="uaccess"
## Nitrokey Storage
ATTR{idVendor}=="20a0", ATTR{idProduct}=="4109", ENV{ID_SMARTCARD_READER}="1", ENV{ID_SMARTCARD_READER_DRIVER}="gnupg", GROUP+="plugdev", TAG+="uaccess"
## Nitrokey Start
ATTR{idVendor}=="20a0", ATTR{idProduct}=="4211", ENV{ID_SMARTCARD_READER}="1", ENV{ID_SMARTCARD_READER_DRIVER}="gnupg", GROUP+="plugdev", TAG+="uaccess"
## Nitrokey HSM
ATTR{idVendor}=="20a0", ATTR{idProduct}=="4230", ENV{ID_SMARTCARD_READER}="1", ENV{ID_SMARTCARD_READER_DRIVER}="gnupg", GROUP+="plugdev", TAG+="uaccess"

LABEL="gnupg_rules_end"
```

**Comment by poettering** [comment]
This appear highly gpg-specific. I am not sure systemd should ship those. Also note that gpg can ship their own hwdb files, not everything has to come in systemd's hwdb.

"plugdev" shounds like a very wrong choice of group btw. gpg should really create its own group.

Closing this, sorry.

**Comment by pwithnall** [comment]
> "plugdev" shounds like a very wrong choice of group btw. gpg should really create its own group.

I think this is probably outmoded by the `uaccess` tag anyway. Thanks for your clarifications. :)

**Comment by pwithnall** [comment]
(Filed a task upstream with GnuPG [here](https://dev.gnupg.org/T3082).)
