### ISSUE TITLE
Support udev events for block device resize events (under e.g., Xen)

### ISSUE THREAD

**Issue by copumpkin** [systemd/systemd#5351]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

NixOS

### Context

There are apparently a few scenarios when a live volume might resize itself, but the one that caused me to want this feature was [this announcement from AWS](https://aws.amazon.com/about-aws/whats-new/2017/02/amazon-elastic-block-store-amazon-ebs-enables-live-volume-modifications-with-elastic-volumes/). They now support live resizing of EBS volumes, which on my Linux (NixOS) guest looks like this in `dmesg`:

```
[429151.233162] xvda: detected capacity change from 53687091200 to 64424509440
```

That message appears to come from [this kernel code](https://github.com/torvalds/linux/blob/2fb78e89405f4321b86274a0c24b30896dd50529/fs/block_dev.c#L1386-L1408) but `udev` doesn't seem to emit any events for it. I was wondering if it could be taught to monitor such events so that I can add triggers to do interesting things (e.g., change partitions, resize filesystems) when volumes are resized.

**Comment by arvidjaar** [comment]
That is really kernel issue  - kernel should send `change` even for this. There is nothing udev can do if kernel is silent.

**Comment by copumpkin** [comment]
Ah, sorry then! I've never filed an issue against the kernel before. Does that mean we'd basically want to call something like `kobject_uevent` from that code to notify userland about the change?

**Comment by poettering** [comment]
Yeah, these events have to come from the kernel. Please contact the kernel community, we are not kernel developers. Sorry.

**Comment by copumpkin** [comment]
@poettering that makes sense, thanks!
