### ISSUE TITLE
slice documentation example unclear.

### ISSUE THREAD

**Issue by james-lawrence** [systemd/systemd#5353]
[documentation](https://www.freedesktop.org/software/systemd/man/systemd.slice.html)
```Example: foo-bar.slice is a slice that is located within foo.slice, which in turn is located in the root slice -.slice.```

I believe this means to say `which in turn is located in the bar (bar.slice) which is contained in the root slice (-.slice)`

**Comment by lucaswerkmeister** [comment]
No, slice paths are left-to-right, just like ordinary file system paths. See e. g. `systemctl list-units -t slice` – you will most likely see a `user.slice` and a `user-1000.slice`, but no `1000.slice`.

**Comment by poettering** [comment]
Yes, the documentation appears right here. "foo" is closer to the root than "bar" in the example.

Closing.

**Comment by james-lawrence** [comment]
ah misread it sorry =)
