### ISSUE TITLE
Use unit names, not descriptions, when generating entries for logs

### ISSUE THREAD

**Issue by wavexx** [systemd/systemd#5356]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### RFE

I started this discussion in the mailing list a while ago:

  https://lists.freedesktop.org/archives/systemd-devel/2017-January/thread.html#38145

When generating the various forms of log output, we should use the unit/service/socket/... name, *not* the description written in the unit itself.

The purpose of the description is fine for the output of systemctl status, or systemctl show, but it's not appropriate for log entries. The log should contain entries that are guaranteed to be unique and that I can directly manipulate through the various command interfaces.

To address a couple of concerns that were raised in the mailing list:

- having an unit "title" wouldn't cut it: a title is still not guaranteed to be unique. A title would be fine to augment the log entry though, in addition to the unit name.
- while the journal has this additional information, the information is lost when forwarding the log to other text-only sources (console, syslog).

The content of the journal is sometimes ridiculous due to this, with entries like "Started A Daemon to keep the system time". Ok, is this ntpd.service? That's the info I want to see in the log.

Some units actually write a description that can be used in a sentence like "Starting ...". Some fail completely, like the systemd-cron generator, that puts (rightly, I would say) the original cron entry in the Description, which in turn generates logs like:

  Feb 13 13:12:52 test systemd[1]: Started [Timer] "0 0 * * * root if [ -d "/run/systemd/system" ]; then systemctl restart atop; else /usr/share/atop/atop.daily \& ; fi".

I'd like to see:

  systemd[1] Started cron-atop-root-0.timer.

If a title is provided, a good entry would look like:

  systemd[1]: Started unit title: unit.name.

**Comment by mbiebl** [comment]
I would simply use both, unit name + description in one-line log messages, i.e.
```
systemd[1] Started nginx.service: A high performance web server and a reverse proxy server
systemd[1] Stopped rsyslog.service: System Logging Service
```

**Comment by poettering** [comment]
hmpf. this has been requested before, but I am still not convinced we should flood the "pretty" console output with this low-level information, dunno.

**Comment by wavexx** [comment]
On Thu, Feb 16 2017, Michael Biebl wrote:
> I would simply use both, unit name + description in one-line log messages, i.e.
>
> systemd[1] Started nginx.service: A high performance web server and a reverse proxy server
> systemd[1] Stopped rsyslog.service: System Logging Service

I would be fine with this.

**Comment by wavexx** [comment]
On Thu, Feb 16 2017, Lennart Poettering wrote:
> hmpf. this has been requested before, but I am still not convinced we
> should flood the "pretty" console output with this low-level
> information, dunno.

I don't see it as low-level, the unit name is the actual stuff that
matters. I know daemons by their program and unit name, not description.

I don't want to grep just to find out unit names.
This is an actual problem, especially for generators.

I generally don't care about the description of the services in most
cases. It's nice to see during startup/shutdown, but prefixing the unit
name would actually be good.

On the desktop at least, most people boot with quiet, they don't see
anything. On servers, I /really/ want the unit names to be visible.

**Comment by arvidjaar** [comment]
> I am still not convinced we should flood the "pretty" console output with this low-level information

Console?!? That is what we get in journalctl output when people report problems with services and that makes it much more harder than it could be to understand what is going on. Having some messages refer to unit name and some to unit description does not make it easier either.

I absolutely do not care about console output which I do not see anyway but please make journalctl output at least remotely more usable for troubleshooting.

**Comment by mbiebl** [comment]
Another use case that was mentioned is forwarding to syslog:
It only get's the description of the service, not the unit name.
This makes grepping the (syslog) log files much harder/unintuitive.

**Comment by mbiebl** [comment]
I might add, that it's a very common complaint by users. This comes up a lot.
So please reconsider @poettering .

**Comment by poettering** [comment]
I am more open to changing the strings in the log output rather than the console output.

**Comment by poettering** [comment]
do note that the necessary information is always available in the log metadata though. "journalctl -u ..." permits you to filter for it, and "journalctl -o verbose" will show it.

**Comment by wavexx** [comment]
On Fri, Feb 17 2017, Lennart Poettering wrote:
> do note that the necessary information is always available in the log
> metadata though. "journalctl -u ..." permits you to filter for it, and

Please note that your own example requires to know the unit before you
can filter it. The common scenario is:

- systemctl list-units | grep 'whatever text I read' to find the unit
  name
- journalctl -u unit to restrict the output

On top of that, very often you want to see the big picture (all the log
around a time point), meaning that you need to use some output when the
unit name is visible.

> "journalctl -o verbose" will show it.

Again, this info is lost when the journal is not used. I'm using a
persistent journal on the desktop because I want to keep the metadata,
but the current performance of journald bars me to use it server-side in
most situations. The current size of the journal is also prohibitive for
long term archival.

And if I may add, "journalctl -o verbose" is an inconvenient output
format. I had more success parsing json. I'd rather have some
format-like expression to be used instead, like this:

  journalctl -f "${_SYSTEMD_UNIT}: ${MESSAGE}"

**Comment by wavexx** [comment]
Just pinging @poettering here to reconsider this, again.

There's a huge mismatch in journal's output compared to unit control with systemctl. As a sysadmin, I know exactly what units are, and their silly descriptions are just getting in the way all the time.

**Comment by vcaputo** [comment]
Can't we just make this configurable and let the distributions decide what to default to, and the sysadmins potentially override with what they want?

It seems like an simple case of general desktop vs. server/expert conflict.

Where end-users are concerned on the desktop, there's cause to hide the "low-level" unit name and instead show the potentially ambiguous (or plain inconsistent with unit name if misconfigured) description.

With experienced sysadmin types as the consumer, they want the unique and always-accurate low-level unit name, and don't care about the prettiness.

**Comment by arvidjaar** [comment]
I cannot think of a single reason to have unit descriptions in log files. Ever. This significantly reduces usability of them, forcing to recreate them with debug (and this is not always possible) and even then making it impossible to correlate "normal" and "debug" entries.

Unit descriptions are for GUI to show. Nor for log entries.

**Comment by wavexx** [comment]
On Sun, Jan 21 2018, Andrei Borzenkov wrote:
> Unit descriptions are for GUI to show. Nor for log entries.

I cannot agree more with this.

I also don't want to fall into the scenario where I get sent a log from
another system which has descriptions turned on as opposed to unit
names, because the distribution has opted for an "user friendly" output
(in fact making system analysis much harder for the maintainers
themselves).

And I say that after debugging a system with two units having the same
description (due to copying), that made me lost half an hour before I
could get my hands on the journal directly.

**Comment by bl33pbl0p** [comment]
+1 for this, I would want it on the console as well, it just makes it easy to pin-point what unit the "Started ... Stopping" message came from with units that have a vague description. (and that's not something to fix in the description, when it's written alongside the unit name, it makes perfect sense.)

**Comment by CRCinAU** [comment]
Yeah - so when looking into syslog forwarding to central logging systems, the logs created by journald to syslog to then forward are useless. There is no mention of the unit the log files came from which leaves the logs created on the central host less than useless.

Yes, they are prefixed by the executable name - which is some help - but not when it shows things like 'run-parts'.

It would be helpful if the output was something like: $date $hostname $unitname $message

**Comment by exuvo** [comment]
I keep getting useless shit like "starting An encrypted network without censorship and monitoring." during boot which says exactly nothing to me. If it instead said "starting freenet" i would immediately know what unit was starting.

I can't be expected to print out a paper sheet with all the unit names and descriptions to use for mapping boot messages so that i know what is happening during system boot. And no i can't use journalctl verbose while the system is still starting.

How many years do we have to wait until our logs and bootmessages become usable? This should be a really simple boolean setting to implement.

**Comment by wavexx** [comment]
Almost three years on, can we please get unit names in log entries, *please*? You know, the stuff that help a sysadmin actually do the work he needs to do?

We can do that though a flag, so that everybody is happy.

What about ``IDontCareAboutPrettyConsole=yes``?
Or ``IAmASysadmin=yes``?
Or ``DumbOutput=no``?
Or ``LogEntryMode=description|name|both``

\</not-so-sarcastic\> &half-smile;

**Comment by boucman** [comment]
journalctl -o with-unit  to have journald display that. 
also man:systemd-system.conf, look for StatusUnitFormat= 
(this bug can probably be closed at this point)

**Comment by wavexx** [comment]
So this was introduced in v243, as I never saw this before.
I upgraded to the experimental build in debian and switched to "name".
I still see the "description" in the console?
Am I doing something wrong?

**Comment by yuwata** [comment]
v243 has a bug about that. Please use the current git master or backport 6327aa9f6c5701e44541e685c6bf44d3a8c40f50.

**Comment by wavexx** [comment]
I wish bugs were closed with a version tag associated with the release that actually fixes the bug. I'm following several open/closed reports, and I'm not really sure which bug got fixed where.

**Comment by yuwata** [comment]
In that sense, 6327aa9f6c5701e44541e685c6bf44d3a8c40f50 closes this.

**Comment by wavexx** [comment]
On Sat, Sep 21 2019, Yu Watanabe wrote:
> In that sense, 6327aa9 closes this.

That's not what I meant. I'm just saying that once a bug or PR is
closed, it's not obvious (especially in retrospect) to know in which
release the bug has been fixed.

**Comment by mbiebl** [comment]
github shows you that information directly under the summary. Currently it only lists master there, which means the commit has not been part of a release yet. If you look at older commits, say
6552c29edb1ebf4016be82a37148a583e086d4d4 you'll see v243 which means this commit is part of the v243 release.

**Comment by wavexx** [comment]
On Sat, Sep 21 2019, Michael Biebl wrote:
> been part of a release yet. If you look at older commits, say
> 6552c29edb1ebf4016be82a37148a583e086d4d4 you'll see v243 which means
> this commit is part of the v243 release.

Thanks!
