### ISSUE TITLE
RFE: allow CPUAffinity override from kernel boot command line

### ISSUE THREAD

**Issue by yarda** [systemd/systemd#5368]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd-231-12.fc25.x86_64

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora, Red Hat Enterprise Linux 7

For realtime we need to keep some CPUs isolated. We do it by utilizing CPUAffinity systemd settings. Unfortunately systemd cannot change CPUAffinity for timers it created when dracut /etc/systemd/system.conf was in effect. Currently the only solution for us is to regenerate dracut images for all available kernels to have the correct CPUAffinity settings in dracut. This is not optimal. Much better would be to have CPUAffinity kernel command line settings which would override /etc/systemd/system.conf settings.

**Comment by poettering** [comment]
make sense to have I guess.

**Comment by bcg62** [comment]
+1 for this. Its a problem when creating pxe boot images which will be distributed to different hardware/configurations. Baking the setting into /etc/systemd/system.conf does not allow a user to change it at boot time.

**Comment by f1linux** [comment]
Any movement on this RFE?

**Comment by poettering** [comment]
So, the kernel already has the `isolcpus=` kernel cmdline option. This sounds like a better approach since it also keeps the kernel itself off the isolated cpus. Is there really a need to duplicate this in systemd, in particular as it can never have the same effect as the kernel's own version since it would only cover systemd and what it manages, but not the kernel?

I am tempted to say that this should really become a documentation issue, and we don't need any new code here.

**Comment by bcg62** [comment]
https://access.redhat.com/solutions/2884991

https://lore.kernel.org/patchwork/patch/846117/

**Comment by joemario** [comment]
Two questions:

1) There is no scheduler load balancing on the cpus in the "isolcpus=nnn" list.   Isn't that the reason tuned intentionally avoided using isolcpus= in the first place?

 Even the "no_balance_cores=" feature in the /etc/tuned/cpu-partitioning-variables.conf file didn't get implemented with "isolcpus=" when it wanted to give the user the option of disabling load balancing.  Instead, tuned implemented it via changing /proc/sys/kernel/sched_domain/cpu*.

2) The "isolcpus=" flag has been marked as "deprecated" for the last year or two.  cpusets is to be used in its place. 

So I'm puzzled how isolcpus would help.

**Comment by poettering** [comment]
Implemented in 68d58f38693. Closing.
