### ISSUE TITLE
networkd: support for /31 IPv4 addresses (rfc3021)

### ISSUE THREAD

**Issue by lemoer** [systemd/systemd#5376]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 230

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian 8.7

### Description

[RFC3021](https://tools.ietf.org/rfc/rfc3021.txt) proposes the usage of `/31` IPv4 addresses. Normally this is impossible, because there are no addresses left in an `/31` network, when you assign a broadcast address and a network address. The rfc proposes to leave broadcast address and network address when we have a p2p link.

I tested whether it's already possible to assign a `/31` with networkd, but it always adds a broadcast address.

I would propose to simply not assign a broadcast address if ip address to assign is `/31` disregarding the link type since I don't know a case where it's useful to assign a `/31` without host IP addresses.

**Comment by zdzichu** [comment]
Would following be sensible?
If user assigns IPv4 /31 or IPv6 /127 (RFC6164) address, network and broadcast address should be disregarded and "the other" address from this pseudo-network should be turned into Peer= setting?

**Comment by keszybz** [comment]
Sounds reasonable. Pull requests welcome ;)

**Comment by jwh** [comment]
I raised this a while back, https://github.com/systemd/systemd/issues/4038

**Comment by keszybz** [comment]
Right, let's close this in favour of #4038 which is older.
