### ISSUE TITLE
ProtectKernelTunables= imply MountAPIVFS=. This breaks TestVolumeSysfs

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5384]
5d997827e2ebe5d introduced `MountAPIVFS=`.

This breaks [`TestVolumeSysfs`](https://github.com/coreos/rkt/blob/master/tests/rkt_volume_nspawn_test.go#L59)
```
        rkt_volume_nspawn_test.go:76: Running test #3: With /sys/class bind-mounted from the host
        rkt_tests.go:410: didn't receive expected output "/sys/class: mode: Dcrw-rw-rw-": image: using image from local store for image name coreos.com/rkt/stage1-src-v233:1.24.0
+git9e63d7e
...

                [150951.177193] rkt-inspect[12]: /sys/class: mode: drwxr-xr-x
                [150951.177395] rkt-inspect[12]: /sys/class: user: 0
                [150951.177484] rkt-inspect[12]: /sys/class: group: 0
...
```
`rkt-inspect.service` contains:
```
RootDirectory=/opt/stage2/rkt-inspect/rootfs
...
ReadOnlyPaths=-/opt/stage2/rkt-inspect/rootfs/sys/class
ProtectKernelTunables=true
...
```

The root cause is 

https://github.com/systemd/systemd/commit/5d997827e2ebe5d4f438748d1ac87c10c29045c6#diff-f315b72505d5f0a92ec2f4d068d4f916R820):
> /* ProtectControlGroups= and ProtectKernelTunables= imply MountAPIVFS=, since to protect the API VFS mounts, they need to be around in the first place... */

BTW why not to document that?

cc @lucab

**Comment by poettering** [comment]
@lucab hmm, so what is rkt precisely testing there that breaks now?

**Comment by poettering** [comment]
I added a brief comment about the documentation issue @evverx pointed out now to the man page in #5411.

**Comment by evverx** [comment]
The documentation has been updated and the test seems to have been fixed in https://github.com/rkt/rkt/commit/161fa3de3bfbbe07182562708eb8efcf566bb48d, so I'm closing the issue.
