### ISSUE TITLE
Don’t use _SYSTEMD_UNIT as example field in journalctl(1)

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#5387]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232 / master (3877500c5bc2daad0437b74eb3a7f707d413c2b0)

The *journalctl(1)* manpage currently uses the field `_SYSTEMD_UNIT` in several examples. I think this is a bad idea, since it may suggest to the user that adding a match for that field is the preferred way to filter for a certain unit’s messages, even though it’s inferior to `--unit`:

- `--unit` matches more fields than just `_SYSTEMD_UNIT`, so you also see “Starting UNIT…” and “Started UNIT.” messages, as well as core dumps and some more messages.
- `--unit` quietly turns itself into `--user-unit` when used in conjunction with `--user`.
- `--unit` (`-u`) is faster to type than `_SYSTEMD_UNIT`, even with tab completion.

I think we should try to find another field that is still useful in examples but doesn’t have a dedicated option, and also add an example for `journalctl -u` in the EXAMPLES section (I’d suggest putting it directly after the “no arguments” example).

(I’m filing this issue, rather than directly submitting a pull request to fix this, because I’m not yet sure what that other field should be, and want to put it up for discussion. Some suggestions: ~~`SYSLOG_IDENTIFIER`~~, `MESSAGE_ID`, `_SYSTEMD_CGROUP`.)

**Comment by keszybz** [comment]
We already have an example with MESSAGE_ID somewhere. SYSLOG_IDENTIFIER is the same as `-t`. Maybe `_PID=` or `_SYSTEMD_CGROUP=`?

**Comment by lucaswerkmeister** [comment]
The example for multiple matches on different fields (third example) uses `_SYSTEMD_UNIT` and `_PID` (and so does the fifth example, which is based on that one), so we’d have to find something different there.

The third example could be rewritten to `-u avahi-daemon.service _PID=28097`, but that doesn’t work for the fifth example: “"+" can only be used between terms”. (I think it would be neat if e. g. `journalctl -t foo + -u bar` worked, but that’s for another issue, and anyways it would be too confusing for a manpage example intended to introduce `+` for normal matches.)
