### ISSUE TITLE
Support globbing in Requires= etc. to depend on any instance of template 

### ISSUE THREAD

**Issue by sebastianst** [systemd/systemd#5388]
## Request for enhancement (RFE)
It would be very helpful to be able to use globbing in `Requiers=` and similar fields to let e.g. a target require any instance of a template, e.g. a `vpn.target` could look like this:
```
[Unit]
Description=VPN Tunnel up
Requires=multi-user.target openvpn-client@*.service
Conflicts=rescue.service rescue.target
After=multi-user.target openvpn-client@*.service
AllowIsolate=yes
```
I couldn't find a way to do this. See also those unanswered questions on SE:

- [How do you tell systemd that a target is satisfied with one of any requirements?](https://unix.stackexchange.com/questions/313473/how-do-you-tell-systemd-that-a-target-is-satisfied-with-one-of-any-requirements)
- [Require any instance of a template](https://stackoverflow.com/questions/36418331/require-any-instance-of-a-template)

### Globbing in `Conflicts=`
As a plus, globbing could also be supported for `Conflicts=`. Say, I have a VPN provider `FooVPN` and several configurations named `FooVPN_us`, `FooVPN_es`, `FooVPN_nl` etc. Now only one instance of this group should be active at a time. Then I could define an override file `openvpn-client@FooVPN*.service` like so:
```
[Unit]
Conflicts=openvpn-client@FooVPN*.service
```
And systemd should be smart enough to not let a unit conflict with itself. Or one could introduce a new `ConflictsOther=` keyword to explicitely conflict with any other instance but itself.

**Comment by poettering** [comment]
Uh, this conflicts with the entire of systemd so far: we only load referenced units, and for that we need to first know the ultimate name for a unit and then go and find a backing unit file for it. Globbing always turns around these things: we first need to know all available units, to then determine the matching subset of it.

Also, how is this even going to work for instances (which appears to be the desired usecase here): they can be (and usually are) created ad-hoc, that's kinda their main feature: there has to be no record of foobar@quux.service until that unit is started, and only then we'll look for a unit file for it, and will likely find foobar@.service. But a wildcard dependency, in particular one that pulls in and actively instantiates other units the way Requires= does it, how can it be generic? I mean, if a unit requires foobar@*.service, what should this actually do? what should it fill into "*"? The * after all could be *anything*, and that's a ridiculous large set... if we'd start *every* possible instance of a unit when another unit is pulled in, that would make really no sense...

Anyway, I am pretty sure what you are looking for is PartOf/ConsistsOf= which permits you to set up the dependency from the other side. Moreover there are .wants/ and .requires/ symlinks which permit to add requires/wants deps to existing unit, from data stored in other units. I think that these concepts are much better solutions to your specific usecase.

I am sorry, but this request is semantically very broken. Closing this, I hope that makes sense. Sorry!

**Comment by Gooberpatrol66** [comment]
So what should I do to ensure that service foo does not run at the same time as any instances of service bar@?
