### ISSUE TITLE
Lock errors when stopping multiple instances at once

### ISSUE THREAD

**Issue by RoiEXLab** [systemd/systemd#5391]
I'm using the latest XUbuntu LTS 16.04.2 version with systemd 229 (this is what `systemd --version` tells me), but I believe this doesn't matter:
I wrote myself a service unit, which launches instances of a "client" aka bots using instances.
In other words I can start and stop bots by using `service bot@<bot_number> start|stop` or the systemctl equivalent...
Those bots require a firewall port to be opened with ufw and closed after those bots are shut down, or at least thats the idea:
```
ExecStartPre=/usr/sbin/ufw allow $PORT
ExecStartPre=/user/sbin/ufw reload
ExecStart=/path/to/script
ExecStopPost=/usr/sbin/ufw deny $PORT
ExecStopPost=/user/sbin/ufw reload
```
When starting and stopping those bots individually, this works fine, but a soon as I try to stop them all using `service 'bot@*' stop` those postexec steps result in errors, stating that another app is holding the xtables lock, which is probably another instance trying to stop itself.

What I'm trying to say is, that in my opinion when multiple services are being stopped at the same time, they shouldn't be stopped at the same time, but stopped one after another, including postexec scripts.

Please let me know if my assumptions are wrong!

**Comment by poettering** [comment]
Hmm, nah, unit instances are about decoupling service context, I am very much of the opinion this means we should ensure the state engines are fully independent, and they currently are.

This really appears to be a bug in your "ufw" software, it should simply add support for acquring the "xtables lock" synchronously (i.e. wait until nothing else has it). Locks are generally understood as a synchronization concept dealing precisely with cases like that, and systemd is certainly not the place to work around broken users of such a concept.

I am not sure what "ufw" is, but if that's just a wrapper around iptables, then please be aware that the iptables "-w" switch will fix the problem for you, and is definitely what you should be using here, and not work-around it in systemd.

Hope this makes sense, closing.
