### ISSUE TITLE
bootctl install fails when running twice

### ISSUE THREAD

**Issue by aszlig** [systemd/systemd#5396]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> NixOS

### Expected behaviour you didn't see

> `bootctl install` succeeding on second run

### Unexpected behaviour you saw

> `Failed to open loader.conf for writing: File exists`

### In case of bug report: Steps to reproduce the problem

> Try running `bootctl install` twice

This has surfaced in one of our installer tests and we currently work around this in NixOS/nixpkgs@dc31a1ea29cae217b71134bf59f888c5a90f630b by removing `loader.conf`  prior to running `bootctl install`.

I'm not sure however, whether this is really a bug or this was intended in d5ff6d6d341d56de725633a38e23778e58140b9e.

What would be the benefit and/or what are the reasons to use the `x` mode flag (unlike `e` - what I wrote in the nixpkgs commit message mentioned) here?

**Comment by poettering** [comment]
Fix waiting in #5411
