### ISSUE TITLE
udev disk locking breaks syslinux/mtools

### ISSUE THREAD

**Issue by joshtriplett** [systemd/systemd#540]
syslinux uses mtools to manipulate disk images when making them bootable. mtools attempts to acquire an exclusive lock on the device when opening it for writing, and fails if that lock acquisition fails.  At the same time, some part of setting up a loopback device (initially set up via losetup on the command line, then manipulated by syslinux) causes udev to open and lock that device, likely as part of the change in udev 214 to lock the disk device node.  This causes a race, and if mtools loses that race, it'll spuriously fail.  (This race was extremely timing-dependent and difficult to debug.)  Some instrumentation in the kernel flock error path produced this:

```
[   83.036178] Non-blocking flock failed: PID abs 4186 ns 2910 current->comm=mcopy holder PID abs 4187 ns 0 holder->comm=systemd-udevd
```

(The mcopy was run inside a PID namespace, and udev wasn't, hence the 0.)  This shows that mcopy's flock failed due to systemd-udevd's lock; systemd-udevd's system-wide PID being one more than mcopy suggests that the udev process that won the race for the lock started at almost the same time that syslinux started mcopy.

Net result: a build script that invokes losetup and then syslinux (which invokes mtools) will spuriously fail due to a timing-dependent race.  This is currently causing spurious build failures in Chrome OS.

I don't see any obvious way that such a build script can work around this.  I'd welcome suggestions for such a workaround to make the build script work with older udev versions, but for new versions, this seems to fall under the note in 214's NEWS saying "if it turns out to cause major problems, we might turn it on only for specific devices, or might need to disable it entirely."

**Comment by joshtriplett** [comment]
cc @jausmus

**Comment by poettering** [comment]
mtools should take a blocking lock of course.  (i.e. not use LOCK_NB)

(udev only takes a non-blocking lock, because it will reprobe anyway if another tool closes the block device after writing)

I don't think there's anything to fix in udev.

**Comment by joshtriplett** [comment]
That would cause mtools to block forever if something else is holding the lock less transiently than udev does. That's not a particularly user-friendly behavior, especially for a tool that is not just called interactively by users, but indirectly by scripts.  (In theory it could attempt with LOCK_NB first, then print a message saying the device seems to be locked and to Ctrl-C if needed, and then retry without LOCK_NB, but that still seems unfriendly to scripting, and would likely require a new non-default option to mtools to request that behavior to avoid breaking existing scripts.)

Loop devices don't (currently) get scanned for partitions by default.  And other than that, what is the purpose of locking a block device while processing udev events?

**Comment by poettering** [comment]
udev should not get confused by tools altering the low-level partition table, it should not propagate data from the disk while the disk is being modified.

Loop devices do get partition block devices created. Among others nspawn actually relies on that.

**Comment by poettering** [comment]
Still: mtools should take a blocking lock. If it is afraid that this might take too long, then it should set a timeout (which is really nasty to do however, you probably require alarm() and sigsuspend() to implement that...), but that's something to fix in the kernel APIs...

But honestly, I wouldn't bother, just make it blocking and forget about the timeout...

**Comment by joshtriplett** [comment]
> udev should not get confused by tools altering the low-level partition table

That much is entirely sensible; reading the partition table should certainly acquire a lock.

> it should not propagate data from the disk while the disk is being modified

This part I'm wondering about; what is it propagating via udev events that could change if a lock isn't held?  As opposed to a program invoked by or receiving udev events acquiring a lock before it relies on some transient aspect of the device state.  (Noting that this still only excludes programs that politely acquire a lock, so it's still possible for things to change underneath udev.)

> Loop devices do get partition block devices created. Among others nspawn actually relies on that.

I was unaware that this happened automatically now; I thought it still required running partx or kpartx.  What do these devices show up as, and does this require some additional udev rule or kernel option to enable?

> If it is afraid that this might take too long, then it should set a timeout (which is really nasty to do however, you probably require alarm() and sigsuspend() to implement that...), but that's something to fix in the kernel APIs...

Or a thread and a pipe, though that's similarly painful.  There should probably be some way to put "able to acquire a lock on an fd" into a poll() loop, though it'd be difficult to do that without a race.

**Comment by poettering** [comment]
@joshtriplett udev reads a lot of metadata from disksas they appear, from partition table info, to disk labels, uuids, ... it then attaches that as metadata to the devices, and propagates that on.

A good chunk of the props shown by this command are generated that way:

```
# udevadm info /dev/sda
```

The loopback partition devices appear as /dev/loop0p1, /dev/loop0p2 and so on.

**Comment by poettering** [comment]
If you use "losetup" you can force the parscan with -P
