### ISSUE TITLE
Poky patch for configurable root folder [Accept or deny?]

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#541]
Poky is carrying over a patch that makes the root folder configurable. I do not remember seeing any discussion about it in the ML. If we are OK with the idea I take a stab at it by updating the patch for 223. If we not taking the patch then I will update the poky systemd recipe as "Upstream-Status (http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)".

http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-core/systemd/systemd/0010-Make-root-s-home-directory-configurable.patch

**Comment by zonque** [comment]
I'm curious - what alternative root home do users of OE set?

**Comment by olof** [comment]
The default in OE is /home/root. Don't know the reason for this, but has been this way since at least 2005 (initial commit in git).

**Comment by xnox** [comment]
@olof  a lot of stuff in Yocto / OE seems to have random things in place for whatever old reasons (e.g. read-only root and only certain things on a RW sdcard and so on)

If one wants to use /home/root wouldn't a symlink with tmpfiles from /root -> /home/root be more sensible?

**Comment by poettering** [comment]
Hmm, I don't think this should be configurable, we should gently push people towards a unified hierarchy, and if they decide to depart from that, the burden for it should be on them, downstream, not us, upstream.

Hence, I am pretty sure we should not merge this upstream. The better option would certainly be to fix Yocto to just use /root, like everybody else...

Closing hence. Sorry!
