### ISSUE TITLE
GPLv3 code provided and no GPLv3 specified on the docs

### ISSUE THREAD

**Issue by nacho** [systemd/systemd#5425]
systemd provides GPLv3 code: https://github.com/systemd/systemd/blob/master/m4/ax_compiler_vendor.m4
it would be great to either specify somewhere about it and or to remove that specific script so it becomes fully gplv2

**Comment by poettering** [comment]
note that this is a build-script only, and the code does not end up in the built versions of systemd.

**Comment by nacho** [comment]
Yes I know about that, though still should be pointed out that systemd provides gplv3 software with it, and probably for big corporates it would be less scary to use it...

**Comment by keszybz** [comment]
Sorry, but I think catering to ignorant people is a waste of time. That build script is a build script, and build scripts are build scripts, and their license does not matter as long as we don't create derived works based on it.

**Comment by mbiebl** [comment]
@keszybz couldn't we just remove the ax_*.m4 files and require autoconf-archive as a build dependency for users running autoreconf, i.e. building directly from git?

**Comment by keszybz** [comment]
Well, that makes OP's problem worse! Instead of one file, you now need a whole archive ;)

If there are technical reasons to prefer that, we could do this. Otherwise, I'd just keep things as they are.
