### ISSUE TITLE
unhelpful ratelimiting during shutdown in systemd-shutdown

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5433]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian sid

Trying to debug a shutdown problem I noticed that with v232, the initial systemd-shutdown binary is ratelimiting it's debug output.
With v215 I get
```
[  OK  ] Reached target Shutdown.
[   58.316619] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[   58.324100] systemd-journald[250]: Received SIGTERM from PID 1 (systemd-shutdow).
[   58.374777] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[   58.379442] systemd-shutdown[1]: Unmounting file systems.
[   58.408311] EXT4-fs (dm-2): re-mounted. Opts: (null)
[   58.409686] systemd-shutdown[1]: Unmounting /var.
[   58.412204] systemd-shutdown[1]: Unmounting /dev/mqueue.
[   58.414012] systemd-shutdown[1]: Unmounting /sys/kernel/debug.
[   58.415990] systemd-shutdown[1]: Unmounting /dev/hugepages.
[   58.432492] EXT4-fs (dm-1): re-mounted. Opts: (null)
[   58.434614] EXT4-fs (dm-1): re-mounted. Opts: (null)
[   58.435419] EXT4-fs (dm-1): re-mounted. Opts: (null)
[   58.436227] systemd-shutdown[1]: All filesystems unmounted.
[   58.437246] systemd-shutdown[1]: Deactivating swaps.
[   58.438967] systemd-shutdown[1]: All swaps deactivated.
[   58.440646] systemd-shutdown[1]: Detaching loop devices.
[   58.442767] systemd-shutdown[1]: All loop devices detached.
[   58.444645] systemd-shutdown[1]: Detaching DM devices.
[   58.446631] systemd-shutdown[1]: Detaching DM 253:5.
[   58.448368] systemd-shutdown[1]: Detaching DM 253:4.
[   58.450030] systemd-shutdown[1]: Detaching DM 253:3.
[   58.451659] systemd-shutdown[1]: Detaching DM 253:2.
[   58.453337] systemd-shutdown[1]: Detaching DM 253:0.
[   58.454787] systemd-shutdown[1]: Could not detach DM /dev/dm-0: Device or resource busy
[   58.456931] systemd-shutdown[1]: Not all DM devices detached, 2 left.
[   58.458654] systemd-shutdown[1]: Detaching DM devices.
[   58.460284] systemd-shutdown[1]: Detaching DM 253:0.
[   58.461589] systemd-shutdown[1]: Could not detach DM /dev/dm-0: Device or resource busy
[   58.463668] systemd-shutdown[1]: Not all DM devices detached, 2 left.
[   58.465342] systemd-shutdown[1]: Cannot finalize remaining DM devices, continuing.
[   58.468228] systemd-shutdown[1]: Failed to finalize  DM devices, ignoring
[   58.469937] systemd-shutdown[1]: Halting system.
[   58.497150] reboot: System halted
```

With the exact same configuration on v232 I get
```
[  OK  ] Reached target Shutdown.
[  111.199245] systemd-shutdow: 37 output lines suppressed due to ratelimiting
[  111.235502] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  111.239139] systemd-journald[279]: Received SIGTERM from PID 1 (systemd-shutdow).
[  111.262011] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  111.264418] systemd-shutdown[1]: Unmounting file systems.
[  111.265332] systemd-shutdown[1]: Remounting '/var' read-only with options 'data=ordered'.
[  111.290348] EXT4-fs (dm-2): re-mounted. Opts: data=ordered
[  111.291289] systemd-shutdown[1]: Unmounting /var.
[  111.292660] systemd-shutdown[1]: Remounting '/' read-only with options 'errors=remount-ro,data=ordered'.
[  111.315820] EXT4-fs (dm-1): re-mounted. Opts: errors=remount-ro,data=ordered
[  111.317818] systemd-shutdown[1]: Remounting '/' read-only with options 'errors=remount-ro,data=ordered'.
[  111.319153] EXT4-fs (dm-1): re-mounted. Opts: errors=remount-ro,data=ordered
[  111.320128] systemd-shutdown[1]: Remounting '/' read-only with options 'errors=remount-ro,data=ordered'.
[  111.321430] EXT4-fs (dm-1): re-mounted. Opts: errors=remount-ro,data=ordered
[  111.322375] systemd-shutdown[1]: All filesystems unmounted.
[  111.323136] systemd-shutdown[1]: Deactivating swaps.
[  111.402096] reboot: System halted
```

Notice the "systemd-shutdow: 37 output lines suppressed due to ratelimiting" line.
This is unhelpful when trying to debug a problem.

**Comment by poettering** [comment]
That ratelimiting is not applied by userspace but by the kernel. See the recently added `printk_devkmsg` kernel cmdline option, to turn it off (and related)

**Comment by mbiebl** [comment]
@poettering ah, ok. I didn't know about that, thanks!
I indeed forgot to mention that one test-VM was using jessie (v215 + kernel 3.16) the other stretch (v232 + kernel 4.9).

**Comment by ghost** [comment]
On my system systemd-shutdown also suppresses messages, but I haven't been able to disable ratelimiting so far.

I tried setting the following options in `/etc/systemd/journald.conf`:

```
RateLimitIntervalSec=0
RateLimitBurst=0
```

Then I issued the following command:

    systemctl restart systemd-journald

I also set the following kernel options:

```
echo on > /proc/sys/kernel/printk_devkmsg
echo 0 > /proc/sys/kernel/printk_ratelimit
echo 0 > /proc/sys/kernel/printk_ratelimit_burst
```

But at shutdown systemd-shutdown still suppresses ratelimited messages. What else should I try?

I also filed a kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=197857

**Comment by mbiebl** [comment]
This issue comes up a lot (on forums, IRC, bug reports). We should at least document it how the (kernel) ratelimiting can be disabled. @poettering Are you ok with reopening and retiteling the bug report accordingly?

**Comment by mbiebl** [comment]
On second thought, we do mention this at https://freedesktop.org/wiki/Software/systemd/Debugging

"When you have systemd running to the extent that it can provide you with a shell, please use it to extract useful information for debugging. Boot with these parameters on the kernel command line:

```systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on```

in order to increase the verbosity of systemd, to let systemd write its logs to the kernel log buffer, to increase the size of the kernel log buffer, and to prevent the kernel from discarding messages."

This seems to work for me to get rid of the kernel rate limiting. @fturco have to tried those instructions?

**Comment by ghost** [comment]
I managed to successfully disable ratelimiting with your set of boot parameters:

    systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on

I also found out that the only boot parameter that is really needed is `printk.devkmsg=on`.

But I noticed that messages are suppressed again if I remove `printk.devkmsg=on` from the boot parameters and run the following command instead:

    echo on > /proc/sys/kernel/printk_devkmsg

Is this a kernel bug or is it normal behavior? I can't really understand from `/usr/src/linux/Documentation/sysctl/kernel.txt`...

Anyway it seems this is not a problem with systemd.

**Comment by ghost** [comment]
Beginners like me should also be aware that one should write `printk.devkmsg=on` instead of `printk_devkmsg=on` as boot parameter (dot separator instead of underscore).

**Comment by kirk86** [comment]
@fturco Hi and thanks for the detailed description, unfortunately for me it hassn't worked. I've tried booting with those params configured in grub and although I get more verbose output from `journalctl` I still see this warning `random: 7 urandom warning(s) missed due to ratelimiting` which I translate that into somehow `ratelimiting` was not disabled with the kernel boot commands?
