### ISSUE TITLE
busctl monitor spits out a confusing error message when run as non-root on kdbus

### ISSUE THREAD

**Issue by mus65** [systemd/systemd#544]
When using kdbus, running `busctl monitor` as a normal user fails with the following message.

```
# busctl monitor
Failed to add match: Invalid argument
```

Running it as root works, but without kdbus it works as a normal user as well.
- Arch Linux
- systemd 222
- kernel 4.1.1
- kdbus compiled from v4.1 branch from github repo

**Comment by heftig** [comment]
Seems the connection to the kernel bus fails because HELLO_MONITOR requires privileges. busctl then proceeds to use the proxied system_bus_socket, which rejects the match.

**Comment by poettering** [comment]
Yeah, on kdbus monitoring requires priviliges, and that's intentional.

We should really fix the message about it though.

**Comment by dvdhrm** [comment]
I don't see how we can easily fix this. The first issue I see, is that we make `sd_bus_set_monitor()` a direct kdbus call by modifying `hello_flags`. I think, we should instead make this a boolean on `sd_bus` just like everything else.
Secondly, we should reject `bus_socket_connect()` and friends if `is_monitor` is set. We might, in the future, decide to implement `DBus.BecomeMonitor()` but we don't right now. So we should properly reject it.

Anyway, the biggest issue I see is `bus_start_address()`: It continues with the next bus-address if it cannot connect to the previous one. It does not care for the type of failure, but simple steps to the next. I'm honestly not sure how we should export such error codes to the caller.

**Comment by dvdhrm** [comment]
This is fixed now:

```
david@david-t2 ~ $ busctl monitor
Failed to connect to bus: Operation not permitted
david@david-t2 ~ $ 
```
