### ISSUE TITLE
systemd-tmpfiles-setup.service is started twice if failed at the first time

### ISSUE THREAD

**Issue by izh1979** [systemd/systemd#5440]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 225

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Sailfish OS / Mer

### In case of bug report: Expected behaviour you didn't see

> systemd-tmpfiles-setup.service must be started only once because it's of oneshot type and doesn't contain Restart option.

### In case of bug report: Unexpected behaviour you saw

> The service is started twice, which breaks some things. On a first start it created directories in /run, then some daemons created files there, then on the second run it deletes some of them because of --remove option.

### In case of bug report: Steps to reproduce the problem

> Make its config containing wrong entries, for example, unsupported kernel's options, so the service fails.

It seems that being oneshot and do not using Restart do not guarantee that a service will be started exactly one time during a system boot. Is it a proper behavior?

In some cases it could break system boot.

P.S. yes, our systemd is v225 yet. But I suppose that this kind of logic didn't change in v232. We are in the process of updating it. But it's not so easy to update it on a mobile devices because of systemd was initially designed for PCs. So if this behavior was already fixed in never versions please tell what commit to find. Thank you.

**Comment by izh1979** [comment]
So the issue is that a failed oneshot service without Restart= option, and without Require dependencies on it (but only After) could b started second time. And being not-idempotent it could break the system boot.

There could be other non-idempotent oneshot services which restarts are not desirable (like running failed fsck after mounting a filesystem). So is there a way to specify that a service should be started exactly one time, no matter failed it or not?

**Comment by izh1979** [comment]
Here is a journal: https://pastebin.ubuntu.com/24058683/
All related lines are indented with tabs. All lines with "@@@" is a debug messages added by me.
You may see the first service start on the line 939 and the second on the line 1158.

**Comment by izh1979** [comment]
So currently it seems that if services B, C and D have After=A, and A fails, then A could be started up to 3 times.

**Comment by arvidjaar** [comment]
The behavior is correct in the sense, that if A `Wants` B and B was not run yet, systemd should attempt to start B. If start of B failed there is no indication that B was run, so it attempts to start it again.

Pragmatic fix is to ignore error exit from `systemd-tmpfiles`:

`ExecStart=-@rootbindir@/systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev`

I am not sure there can be one answer that fits all use cases. For idempotent services that failed to start attempting to start them again looks the right way. systemd itself cannot know whether service is idempotent or not.

**Comment by izh1979** [comment]
The problem is that --remove option is too dangerous. I mean there is no harm in trying to create a directory even if it's already exists (providing the same owner and perms), but removing again files including files created by damons after first start tmpfiles start, is not good. That's why this service shouldn't be started more than once.

**Comment by keszybz** [comment]
This is fixed by cd9f5b68ce08375eb1d68a4ddaa7a24a5092d7ba — systemd-tmpfiles services will run just once, even if there are syntax errors and such.
