### ISSUE TITLE
`systemctl start` and friends should be made working from in RootDirectory=/RootImage= services

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#5446]
When running in mock:
```
<mock-chroot> sh-4.3# systemd-detect-virt --version
systemd 231
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
<mock-chroot> sh-4.3# systemd-detect-virt -r && echo YES
YES
<mock-chroot> sh-4.3# LD_LIBRARY_PATH=.libs .libs/systemd-detect-virt -r && echo YES
<mock-chroot> sh-4.3# LD_LIBRARY_PATH=.libs .libs/systemd-detect-virt -c && echo YES
<mock-chroot> sh-4.3# 
```

I'm not sure if this is a regression, but it seems highly suspicious.

**Comment by poettering** [comment]
so, mock uses fs namespacing but doesn't set `$container`? That means we don#t detect this as neither a container nor a chroot, but that's on purpose.

I mean, it's like using RootDirectory=/foobar in conjunction with any namespace-inducing setting of systemd (e.g. PrivateTmp=yes): we don't consider this a container, but it's also not a chroot.

I am not sure there's a bug here?

**Comment by keszybz** [comment]
I understand why RootDirectory=/foobar isn't technically a chroot, but from users' POV, the details of the mechanism aren't important. What counts is that "/" is not the same as the real "/", and e.g. /run and /sys and whatever do not contain useful stuff.

I think we should redefine `systemd-detect-virt -r` to return true in RootDirectory=/foobar and similar situations.

**Comment by poettering** [comment]
@keszybz hmm, so, there are differences between pure chroots and an fs namespace with a different root (i.e. changing the mount prop flag on a mount point will be private to a process within an fs namespace, but be visible by everything else if chroots are used, and hence propagation too).

But maybe this doesn't matter too much, dunno, and we should detect that as a chroot too.

**Comment by poettering** [comment]
does this really deserve the prio for v233? I am not sure i want to install mock just to fix this issue...

**Comment by keszybz** [comment]
`sudo dnf install -y fedora-packager && sudo usermod -a -G mock $(id -u)` ;)

I'd rather decide it before 233, so that we don't have a released version of `systemd-detect-virt` that is "special".

**Comment by poettering** [comment]
BTW, I changed the running_in_chroot() behaviour for a reason: 295ee9845c801300298d01256eb5a9e3ff117ae0

So, there are two conflicting needs here: "systemctl start" run from a namespaced service should still work, and not be detected as "i am in a chroot" and be refused. (which is what the patch was about)

But in the mock case you want that "systemctl enable" to detect this as chroot and switch to client-side install.

I am not sure how we can resolve this.

**Comment by poettering** [comment]
maybe using running_in_chroot() as discriminator for the systemctl mode is simply suboptimal...

**Comment by keszybz** [comment]
Hm, it *feels* this way. E.g. systemctl operations in mock quite certainly shouldn't do anything. (I'm not saying *how* that's supposed to happen, just that from users' POV, that's the right thing to happen).

Also please consider this: if we have a a chroot environment, we'd detect that as chroot. But if we now open a mount namespace, we suddenly detect it as not a chroot any more. That's just too much magic.

So yeah, I'd prefer to revert 295ee98, update documentation to say that `sd-detect-virt --chroot` is a check if it is running with the same root as PID1, and accept that if `systemctl` is invoked in a different root than PID1, operations are disabled by default. We also have SYSTEMD_IGNORE_CHROOT=1, which one can set if they want to change this.

**Comment by poettering** [comment]
> So yeah, I'd prefer to revert 295ee98, update documentation to say that sd-detect-virt --chroot is a check if it is running with the same root as PID1, and accept that if systemctl is invoked in a different root than PID1, operations are disabled by default.

The issue I have with that is that this systematically breaks our own namespaced services, anything with RootDirectory=/RootImage= set...

**Comment by poettering** [comment]
but anyway, i'd merge a revert, in order not to delay v233

**Comment by poettering** [comment]
posted a revert as #5506 now.

Let's leave this issue open however, so that we look into this again post-release

**Comment by poettering** [comment]
given that the revert is merged now, i renamed this issue and bumped it to v234.

**Comment by keszybz** [comment]
Just to check where we stand:
with mock-1.4.1-1.fc26.noarch, and a chroot with systemd-233-4.fc27.x86_64, with `config_opts['use_nspawn'] = False`, `systemd-detect-virt -r` returns 0. With `config_opts['use_nspawn'] = True` `systemd-detect-virt -r` returns "systemd-nspawn" / 0.
So things are working as they are supposed to.

**Comment by keszybz** [comment]
Hm, this seems hard. The issue is that a process with RootImage= is very hard to distinguish "from inside" from a process running in something like a mock chroot with a namespace. The only option that comes to mind is to feed a special variable in the environment, like `SYSTEMD_SERVICE_ROOT=<dev>:<inode>`. Then we could use this in detect_chroot to do what the reverted patch did, but compare "/" with the contents of that variable. If they match, we'd **not** detect that as chroot.

The advantage would be that existing users like mock would not be affected, and if one opens a mount namespace *inside* of a service with RootDirectory=/RootImage=, `systemd-detect-virt -c` will return true inside of that embedded namespace.

What do you think? Better ideas?

**Comment by poettering** [comment]
hmm, env vars might not inherit down the tree... 

I figure the test needs to be something along the lines: "does the root dir match the root dir systemd set for the unit I am running in?" And I am not entirely sure how to test for that best.

**Comment by poettering** [comment]
Hmm, what about this: we could simply attach the root major/minor to as xattr if it differs from PID1's own. Then a check would be to read this xattr, and compare it with our own root dir, and if they differ we run in some environment.

**Comment by keszybz** [comment]
glibc seems to use 32 31 bit integers for the internal state (see `struct random_data unsafe_state`), but the comments say that it uses 128 bytes by default. It's possible that we screw that up by calling `srand` ;(

**Comment by poettering** [comment]
let's postpone this one to the next release

**Comment by poettering** [comment]
I have thought about this one for a while now, and couldn't come up with a sane solution. doing xattrs on cgroups suffers by the problem that this isn't compatible with userns containers. Similar, if we'd stick the info what the root dir is into the keyring, we also have a problem on containers.

And philosophically I wonder if maybe the chroot check in systemctl is actually the right thing to do when run with RootDirectory= or RootImage=, given that you can't install unit files either in that environment, hence why should you be able to enable them?

Hence, this has no easy answers. And I will thus move this to v236, simply because I see no clear way out. We need to do something about this, but it's not clear to me at all what

**Comment by sourcejedi** [comment]
> I wonder if maybe the chroot check in systemctl is actually the right thing to do when run with RootDirectory= or RootImage=, given that you can't install unit files either in that environment, hence why should you be able to enable them?

I think that's a clear, safe position to take by default.  Pretty fun that running in a different root (to PID 1) gets you the same behaviour as `systemctl --root=/foo`.  I like the idea we have SYSTEMD_IGNORE_CHROOT=1 or raw dbus calls to confuse ourselves with if we want...

We have a different semantic in `systemctl -M foo`.  That does accept `enable`.  Although then you've explicitly asked for something, which is still relatively obscure.

But if there will be use cases you want this for, yet the details aren't giving you a hint...  Isn't the obvious signal whether we have a real `/run/systemd/`?  Like in sd_booted() which checks for `/run/systemd/system`.  That's a nice interface you could establish as a standard if you want one.

Technically `systemctl` is able to do stuff with just dbus access so it's a bit of a deliberate hack, but it seems soo convenient for chroot managers.  All of the options above seem quite obscure, apart from the environment variable which I agree seems unreliable.

People love to play games with chroots and containers and stuff, it seems like it could be nice to let people mess with the system dbus and still have the option to knock out `systemctl`.  Though I don't have anything concrete in mind, maybe there's a different roadblock to such hacks nowadays.

---

If you decide to bind mount /run into a chroot, then you're doing a hack where you get to talk to the host daemons.  And maybe you can eat the consequences?  And apparently we decided that was a sensible default for RootDirectory= services.

You don't need do that for a simple chroot jail.  It's easy for a simple chroot jail to not have `systemctl start` do anything by default.  And if you want the host's /run but without anything in /run/systemd/, you can mount something empty on top of that directory.  If you're a chroot manager, setting up fun bind mounts is core functionality.

Debian chroots traditionally have to do some [special setup](https://wiki.debian.org/chroot#Configuration) to avoid starting conflicting daemons, I think this plays in to the tradition.

I didn't manage to get `schroot` working properly, but its configs are very transparent.  /etc/schroot/default/fstab says

```
# It may be desirable to have access to /run, especially if you wish
# to run additional services in the chroot.  However, note that this
# may potentially cause undesirable behaviour on upgrades, such as
# killing services on the host.
#/run           /run            none    rw,bind         0       0
#/run/lock      /run/lock       none    rw,bind         0       0
#/dev/shm       /dev/shm        none    rw,bind         0       0
#/run/shm       /run/shm        none    rw,bind         0       0
```

which sounds practically like the correct warning already.  There's also a fun "desktop" profile which tries to give access to stuff like dbus and X, but even that does not bind-mount /run by default.

```
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/proc           /proc           none    rw,bind         0       0
/sys            /sys            none    rw,bind         0       0
/dev            /dev            none    rw,bind         0       0
/dev/pts        /dev/pts        none    rw,bind         0       0
/home           /home           none    rw,bind         0       0
/tmp            /tmp            none    rw,bind         0       0

# If you use gdm3, uncomment this line to allow Xauth to work
#/var/run/gdm3  /var/run/gdm3   none    rw,bind         0       0
# For PulseAudio and other desktop-related things
/var/lib/dbus    /var/lib/dbus  none    rw,bind         0       0
```

I checked to see what mock did with /run.  Someone has since brought mock in to the systemd truth.   I don't know what it was doing before.

```
$ rpm -q mock
mock-1.4.9-1.fc27.noarch

<mock-chroot> sh-4.4# ls -l /proc/*/exe
lrwxrwxrwx. 1 root root 0 Feb 22 19:43 /proc/1/exe -> /usr/bin/systemd-nspawn
lrwxrwxrwx. 1 root root 0 Feb 22 19:43 /proc/2/exe -> /usr/bin/bash
lrwxrwxrwx. 1 root root 0 Feb 22 19:43 /proc/self/exe -> /usr/bin/ls
lrwxrwxrwx. 1 root root 0 Feb 22 19:43 /proc/thread-self/exe -> /usr/bin/ls
<mock-chroot> sh-4.4# echo $container
systemd-nspawn
```

[Arch wiki](https://wiki.archlinux.org/index.php/change_root#Using_chroot) mentions `/run` as "optional".

**Comment by sourcejedi** [comment]
One consideration is what distributions do in their "Rescue" instructions.  It's traditional to rescue systems using chroot.  Debian has a [neat option for this in the installer](https://www.debian.org/releases/stable/amd64/ch08s07.html.en), which must be using a chroot shell (as opposed to transitioning to a real PID 1 - this lets the install environment take responsibility for attempting a clean unmount).

I can't think of anything specific either for or against there.  It just seems like a second point on the side of caution.

**Comment by keszybz** [comment]
>>  I wonder if maybe the chroot check in systemctl is actually the right thing to do when run with RootDirectory= or RootImage=, given that you can't install unit files either in that environment, hence why should you be able to enable them?

> Personally I think that's a clear, safe position to take by default. 

OK, that does make sense.

Hence, I guess there's nothing to fix here, let's close this. (Another reason is that things have been this way for a while, and clearly people don't care, so it seems that the current state is good enough.)

>  It's traditional to rescue systems using chroot. 

Yes, but systemd is not running in the chroot, and I don't think one should interact with the systemd from the rescue system at all. I think current behaviour is what we want.

FTR:
```console
$ sudo systemd-run -p RootDirectory=/usr -E LD_LIBRARY_PATH=/lib/systemd/ systemctl
Running as unit: run-r8b3cdfd31cbd43e3a27af09ba3438781.service
$ journalctl -q --no-pager -u run-r8b3cdfd31cbd43e3a27af09ba3438781.service -o cat
Started /bin/systemctl.
System has not been booted with systemd as init system (PID 1). Can't operate.
run-r8b3cdfd31cbd43e3a27af09ba3438781.service: Main process exited, code=exited, status=1/FAILURE
run-r8b3cdfd31cbd43e3a27af09ba3438781.service: Failed with result 'exit-code'.
```
I think this is OK.

**Comment by sourcejedi** [comment]
So regardless of is_chrooted(), `systemctl` already has a sd_booted() check.  And I was thinking wrong, `RootDirectory=` does not automatically bind-mount /run, even if your root directory has a /run directory, and even if you set `MountAPIVFS=yes`.  More results below.

I don't think that contradicts my general hypothesis.  You could still achieve $SUBJECT by effectively replacing the `is_chrooted()` check with `!sd_booted()`.  IMO this is the most relevant level to ask the question:  Is there a reason for `systemctl` to loosen the chroot check, for people who are deliberately bringing socket files from the host in to their chroot/namespace?

> things have been this way for a while, and clearly people don't care

Agreed. I still don't know what a concrete use case is for this RFE/bug.  Opening this up has costs, and personally I don't know that it buys anything.

## more blah

Unifying the condition sounds like a simplification, but it's also dropping the nice specific message about being in a chroot.  (Note the chroot check currently comes first).

We also see it only becomes useful if you have `BindPaths=/run`, which wasn't mentioned up-thread...  So far googling for that returns #3544 (unresolved bug related to doing a more limited bind mount automatically) and one build system ["butterbuild"](https://git.revreso.de/gigadoc2/ansible-roles/commit/5a968fbe05b89db7cc86874aaab060b0624b511d), probably doesn't help reach a conclusion.

> systemd is not running in the chroot, and I don't think one should interact with the systemd from the rescue system at all.

Agreed.  Keeping both checks is slightly more cautious and clear here.

---

## Fun test results

```
$ systemctl --version
systemd 236
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
$ sudo systemd-run --pty -p RootDirectory=/unstable0 systemctl --version
Running as unit: run-u7.service
Press ^] three times within 1s to disconnect TTY.
systemd 236
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

$ sudo systemd-run --pty -p RootDirectory=/unstable0 systemctl
Running as unit: run-u3.service
Press ^] three times within 1s to disconnect TTY.
System has not been booted with systemd as init system (PID 1). Can't operate.
```

It looks like if you make sure to ask for `/proc` to be mounted - which you usually want - then the chroot test is currently hit first.

```
$ sudo systemd-run --pty -p RootDirectory=/unstable0 -p MountAPIVFS=yes systemctl
Running as unit: run-u4.service
Press ^] three times within 1s to disconnect TTY.
Running in chroot, ignoring request.

$ sudo systemd-run --pty -p RootDirectory=/unstable0 -p MountAPIVFS=yes \
  -E SYSTEMD_IGNORE_CHROOT=1 systemctl
[sudo] password for alan-sysop: 
Running as unit: run-u8.service
Press ^] three times within 1s to disconnect TTY.
System has not been booted with systemd as init system (PID 1). Can't operate.
```

But systemd still wasn't mounting `/run` in to the namespace for you, so you wouldn't have been able to talk to anyone.

```
$ sudo systemd-run --pty -p RootDirectory=/unstable0 -p MountAPIVFS=yes findmnt  
Running as unit: run-u5.service
Press ^] three times within 1s to disconnect TTY.
TARGET                                SOURCE                                  FSTYPE    OPTIONS
/                                     /dev/mapper/alan_dell_2016-home[/nspawn/unstable0-clone/unstable0]
|                                                                             ext4      rw,relatime,seclabel,data=ordered
|-/dev                                tmpfs                                   tmpfs     rw,nosuid,seclabel,mode=755
| |-/dev/shm                          tmpfs                                   tmpfs     rw,nosuid,nodev,seclabel
| |-/dev/pts                          devpts                                  devpts    rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=666
| |-/dev/console                      devpts[/3]                              devpts    rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000
| |-/dev/mqueue                       mqueue                                  mqueue    rw,relatime,seclabel
| `-/dev/hugepages                    hugetlbfs                               hugetlbfs rw,relatime,seclabel,pagesize=2M
|-/proc                               proc                                    proc      rw,nosuid,nodev,noexec,relatime
`-/sys                                sysfs                                   sysfs     ro,nosuid,nodev,noexec,relatime,seclabel
  |-/sys/fs/selinux                   selinuxfs                               selinuxfs ro,nosuid,nodev,noexec,relatime
  |-/sys/fs/cgroup                    tmpfs                                   tmpfs     ro,nosuid,nodev,noexec,seclabel,mode=755
...
  | |-/sys/fs/cgroup/net_cls,net_prio cgroup                                  cgroup    ro,nosuid,nodev,noexec,relatime,seclabel,net_cls,net_prio
  | |-/sys/fs/cgroup/unified          cgroup                                  cgroup2   rw,nosuid,nodev,noexec,relatime,seclabel
  | `-/sys/fs/cgroup/systemd          cgroup                                  cgroup    rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd
  `-/sys/fs/fuse/connections          fusectl                                 fusectl   rw,relatime
```

```
$ sudo systemd-run --pty -p RootDirectory=/unstable0 -p MountAPIVFS=yes -p BindPaths=/run \
  -E SYSTEMD_IGNORE_CHROOT=1 systemctl list-units --state=active run-*.service
Running as unit: run-u13.service
Press ^] three times within 1s to disconnect TTY.
UNIT            LOAD   ACTIVE SUB     DESCRIPTION                                           
run-u13.service loaded active running /bin/systemctl list-units --state=active run-*.service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
