### ISSUE TITLE
systemd-networkd: Main Ethernet Interface fails after service restart

### ISSUE THREAD

**Issue by Jo-Jo0** [systemd/systemd#5448]
[dmesg.txt](https://github.com/systemd/systemd/files/800254/dmesg.txt)

### systemd version the issue has been seen with

> 232

### Used distribution

> ArchLinux, Kernel: 4.9.11-1, also seen on Kernel: 4.8.13

### Expected behaviour you didn't see

> IDX LINK             TYPE               OPERATIONAL SETUP     
>  1 lo               loopback           carrier     unmanaged 
>  2 ens3             ether              routable    configured

### Unexpected behaviour you saw

> IDX LINK             TYPE               OPERATIONAL SETUP     
>  1 lo               loopback           carrier     unmanaged 
>  2 ens3             ether              degraded   failed

ens3 config: 

>[Match]
>Name = ens3
>[Network]
>DHCP = ipv4
>Address = $IPv6-Address
>Tunnel = $Tunnel-Interface
>IPForward = ipv4
>IPMasquerade = true

After boot, network works fine, but executing "systemctl restart systemd-networkd" causes ens3 so change to "failed" state and the machine isn't reachable anymore.
Logs say:
> ens3: Could not join netdev: Invalid argument

Rebooting the whole machine, brings the network back up. 

Edit: added dmesg output

**Comment by ssahani** [comment]
hmm please paste `dmesg` output too. thanks !
what is $IPv6-Address and $Tunnel-Interface ?

**Comment by Jo-Jo0** [comment]
$IPv6-Address is the ipv6-Network of the machine
$Tunnel-Interface ist the Name of a gre tunnel interface, i configured on this machine

**Comment by ssahani** [comment]
I can't reproduce this. Looks like some another factor is there.

from dmesg  are using a gre6 tunnel.
```
[    2.629997] IPv6: ADDRCONF(NETDEV_CHANGE): jojovpn.tinc: link becomes ready                                                                                                           
[    2.660310] ip6_gre: GRE over IPv6 tunneling driver 
````

I used this conf for testing.

enp0s25.network
```
[Match]                                                                                                                                                                                  
Name=enp0s25                                                                                                                                                                             
                                                                                                                                                                                         
[Network]                                                                                                                                                                                
DHCP=yes                                                                                                                                                                                 
Tunnel=gre6-tun                                                                                                                                                                          
DHCP = ipv4                                                                                                                                                                              
Address = 2001:db8:f00:baa::b                                                                                                                                                            
IPForward = ipv4                                                                                                                                                                         
IPMasquerade = true   
```

netdev
```
[NetDev]                                                                                                                                                                                 
Name=gre6-tun                                                                                                                                                                            
Kind=ip6gre                                                                                                                                                                              
                                                                                                                                                                                         
[Tunnel]                                                                                                                                                                                 
Local=2001:db8:bad:ee1::a                                                                                                                                                                
Remote=2001:db8:f00:baa::b  
```

ip a 

```
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 28:d2:44:b0:6a:32 brd ff:ff:ff:ff:ff:ff
    inet XXXX/23 brd XXXX scope global dynamic enp0s25
       valid_lft 86176sec preferred_lft 86176sec
    inet6 2001:db8:f00:baa::b/0 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::5684:6ed3:a3b1:46cd/64 scope link 
       valid_lft forever preferred_lft forever

14: gre6-tun@enp0s25: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1448 qdisc noqueue state UNKNOWN group default qlen 1
    link/gre6 20:01:0d:b8:0b:ad:0e:e1:00:00:00:00:00:00:00:0a peer 20:01:0d:b8:0f:00:0b:aa:00:00:00:00:00:00:00:0b
```

**Comment by Jo-Jo0** [comment]
yes, i'm using gre6 tunnels, but they don't come bejond "configuring" in networkctl's output.

The config for the tunnel interface:

```
[NetDev]
Name = gretun01
Kind = ip6gre
MTUBytes = 1400

[Tunnel]
Remote = 2a03:4000:5:XXX::1
```

**Comment by ssahani** [comment]
Please paste the networkctl output.

I guess you are missing another conf file to bring up.
 cat ip6tnl-tun.network 
```
[Match]
Name=ip6tnl-tun
```
See if this works for you.

**Comment by Jo-Jo0** [comment]
networkctl shows this before restarting networkd:

`networkctl`
`IDX LINK             TYPE               OPERATIONAL SETUP`     
`  1 lo               loopback           carrier     unmanaged` 
`  2 ens3             ether              routable    configured`
`  3 ip6tnl0          tunnel6            off         unmanaged` 
`  4 ip6gre0          n/a                off         unmanaged` 
`  5 gretun01  n/a                routable    configuring`

the ip6tnl-tun.network file doesn't exist. I added it, now i got 
`ip6tnl0          tunnel6            degraded    configured`

but it doesn't fix the issue of not being able to restart networkd.

**Comment by ssahani** [comment]
to reload all the configs we need to restart networkd.

**Comment by fooker** [comment]
I've got the same issue as described above. Looks like it can be triggered by having more than one tunnel configured on top of the failing interface.

To clarify this: It's the device with the `Tunnel =` config that is failing, not the tunnel interface itself.

**Comment by fooker** [comment]
I've also reproduced this on latest stable fedora server (systemd-231) and ArchLinux testing (systemd-233) using these configs:
[ens3.network.txt](https://github.com/systemd/systemd/files/985979/ens3.network.txt)
[tun1.netdev.txt](https://github.com/systemd/systemd/files/985980/tun1.netdev.txt)
[tun1.network.txt](https://github.com/systemd/systemd/files/985977/tun1.network.txt)
[tun2.netdev.txt](https://github.com/systemd/systemd/files/985976/tun2.netdev.txt)
[tun2.network.txt](https://github.com/systemd/systemd/files/985978/tun2.network.txt)

The resulting log from the fedora system:
[log.txt](https://github.com/systemd/systemd/files/986435/log.txt)

**Comment by ssahani** [comment]
Sorry for late reply . I am able to reproduce it. If we stack more than one tunnel on a same interface this does happen while restarting networkd that means first time we are able to create and next time this does fail. We should not create the tunnels with the same name if they already exists.  

```
ens3: Could not join netdev: Operation not supported                                                                                                                                                                
ens3: Failed  
```
Does this fix your issue ?
https://github.com/ssahani/systemd/commit/8ab1219f1c80aca81a83bb326a4786c8bd1bcae1

**Comment by fooker** [comment]
The correct link is https://github.com/ssahani/systemd/commit/b9e23e4488956522fda32d597851b9b0dd12b374

**Comment by fooker** [comment]
The patch above fixes the problem for me.

**Comment by ssahani** [comment]
Thanks for verifying . https://github.com/systemd/systemd/pull/6973
