### ISSUE TITLE
When docked and lid closed, login/logout from GNOME causes suspend

### ISSUE THREAD

**Issue by svenpilz** [systemd/systemd#5451]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch

### In case of bug report: Expected behaviour you didn't see

> As `HandleLidSwitchDocked=ignore`, I would expect no automatic suspend when (during) the lid is closed.

### In case of bug report: Unexpected behaviour you saw

> Login and logout using GDM/GNOME or switching to another VT from GNOME sends the machine to suspend, when docked with closed lid and external monitor. I haven't tested it with different desktop environments and am not quite sure if its more related to systemd/logind or GNOME. 

### In case of bug report: Steps to reproduce the problem

> Note: Docked notebook with closed lid and external monitor.
> Login via GDM, logout via gnome-shell or switching to another VT.

**Comment by poettering** [comment]
are you sure your kernel properly reports the "docked" state to userspace?

`busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager Docked`

That will report whether the system is currently considered docked by logind. It either outputs "b true" (if docked) or "b false" (if not docked). Please verify that this works correctly on your system. If it doesn't it's a driver prob, and logind simply doesn't know anything about the docked state.

**Comment by svenpilz** [comment]
It returns `b false`.

What I called a docking station, may actually be a ThinkPad port replicator. And according to http://www.thinkwiki.org/wiki/Docking_Solutions 
> port-replicators have never supported ACPI docking events.
> […] port replicators […] are hidden to the OS.

There only seems to be an (non-standard) event and kernel message by thinkpad_acpi.

Digging deeper into `src/login/logind-dbus.c`, `Docked` returns the result of `manager_is_docked_or_external_displays`. Which returns true if the system is docked or at least one external display is connected. So regardless of the docking status, I would expect `true`.

Is there an easy way to debug `manager_count_external_displays` in `src/login/logind-core.c`? :-)

By the way. If I close the lid, while the external display is connected, the system is _not_ suspending.

**Comment by poettering** [comment]
> Is there an easy way to debug manager_count_external_displays in src/login/logind-core.c? :-)

There's always gdb. And you might be able to get more output by setting SYSTEMD_LOG_LEVEL=debug via an Environment= drop-in for systemd-logind.service.

> By the way. If I close the lid, while the external display is connected, the system is not suspending.

So the counting actually does work correctly?

**Comment by svenpilz** [comment]
> There's always gdb. And you might be able to get more output by setting SYSTEMD_LOG_LEVEL=debug via an Environment= drop-in for systemd-logind.service.

Attached is the debug output of logind, while I switched from GNOME (X session, VT2) to a text terminal (VT3) and back. The switch to the text terminal caused a suspend. Any clues on that or where to look next? I have no idea about the internals of session handling and systemd ;-).
[logind_debug_vt_switch.txt](https://github.com/systemd/systemd/files/815387/logind_debug_vt_switch.txt)

> So the counting actually does work correctly?

I would say so. But I don't see the debug output from `manager_is_docked_or_external_displays`.

**Comment by svenpilz** [comment]
Regarding the external display. Maybe its GNOME preventing the suspend and not logind?

systemd-inhibit --list
>      Who: sven (UID 1000/sven, PID 2752/gnome-settings-)
>     What: handle-lid-switch
>      Why: Multiple displays attached
>     Mode: block
> 
>      Who: gdm (UID 120/gdm, PID 771/gnome-settings-)
>     What: handle-power-key:handle-suspend-key:handle-hibernate-key
>      Why: GNOME handling keypresses
>     Mode: block
> 
>      Who: NetworkManager (UID 0/root, PID 526/NetworkManager)
>     What: sleep
>      Why: NetworkManager needs to turn off networks
>     Mode: delay
> 
>      Who: gdm (UID 120/gdm, PID 771/gnome-settings-)
>     What: sleep
>      Why: GNOME needs to lock the screen
>     Mode: delay
> 
>      Who: sven (UID 1000/sven, PID 2752/gnome-settings-)
>     What: sleep
>      Why: GNOME needs to lock the screen
>     Mode: delay
> 
>      Who: Telepathy (UID 1000/sven, PID 2726/mission-control)
>     What: shutdown:sleep
>      Why: Disconnecting IM accounts before suspend/shutdown...
>     Mode: delay
> 
>      Who: sven (UID 1000/sven, PID 2752/gnome-settings-)
>     What: handle-power-key:handle-suspend-key:handle-hibernate-key
>      Why: GNOME handling keypresses
>     Mode: block
> 
>      Who: gdm (UID 120/gdm, PID 771/gnome-settings-)
>     What: handle-lid-switch
>      Why: Multiple displays attached
>     Mode: block
> 
>      Who: GNOME Shell (UID 1000/sven, PID 2644/gnome-shell)
>     What: sleep
>      Why: GNOME needs to lock the screen
>     Mode: delay

**Comment by mbevc1** [comment]
Any progress on this?

**Comment by keszybz** [comment]
The situation is:
> What I called a docking station, may actually be a ThinkPad port replicator.  […] port replicators […] are hidden to the OS.

and
> It returns `b false`.

and
> If I close the lid, while the external display is connected, the system is not suspending.

So... everything is working as expected considering that we can't detect your system as being docked?

**Comment by mbevc1** [comment]
hm, not sure that's the case:
```
# busctl get-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager Docked
b true
```
Unless there is different method of checking in `systemd`

**Comment by keszybz** [comment]
@mbevc1 your case is different than @svenpilz's then.

OK, let's close this. It seems that for @mbevc1 things are working as expected. We simply don't consider the port replicator to a be a dock.

**Comment by mbevc1** [comment]
Even though it's detecting it via DBus? It's this one: https://www.lenovo.com/gb/en/accessories-and-monitors/top-tech/Basic-Dock-90-W-UK/p/40AG0090UK

**Comment by keszybz** [comment]
@mbevc1, sorry this was addressed to @svenpilz. I edited my comment now.

**Comment by mbevc1** [comment]
No worries. Any solution for my docking - not sure if this qualifies as port replicator only :thinking: 
Feel free to throw any other ideas/workarounds :wink:

**Comment by keszybz** [comment]
@mbevc1 in your case, systemd correctly detects the device as a dock. So your issue is really unrelated to the one that was discussed in this bug. The solution suggested in the downstream bug to wait before suspending is probably right, but somebody needs to figure out the details and write the patch. Let's continue the discussion in #16045.
