### ISSUE TITLE
systemd encountered segfault after virtual machine migration on XEN

### ISSUE THREAD

**Issue by ahriy** [systemd/systemd#5466]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> ubuntu16-04 4.4.0-21-generic

### In case of bug report: Expected behaviour you didn't see

> after vm migration, systemd didn't work well

### In case of bug report: Unexpected behaviour you saw

>after vm migration, systemd 
 [ 1380.067928] PM: late freeze of devices complete after 0.184 msecs
[ 1380.083425] PM: noirq freeze of devices complete after 15.493 msecs
[ 1380.083521] xen:events: Xen HVM callback vector for event delivery is enabled
[ 1380.083521] Xen Platform PCI: I/O protocol version 1
[ 1380.083521] xen:grant_table: Grant tables using version 1 layout
[ 1380.083521] xen: --> irq=9, pirq=16
[ 1380.083521] xen: --> irq=8, pirq=17
[ 1380.083521] xen: --> irq=12, pirq=18
[ 1380.083521] xen: --> irq=1, pirq=19
[ 1380.083521] xen: --> irq=6, pirq=20
[ 1380.083521] xen: --> irq=4, pirq=21
[ 1380.083521] xen: --> irq=23, pirq=22
[ 1380.083521] xen: --> irq=28, pirq=23
[ 1380.083521] xen: --> irq=24, pirq=24
[ 1380.088201] PM: noirq restore of devices complete after 4.493 msecs
[ 1380.088451] PM: early restore of devices complete after 0.159 msecs
[ 1380.090660] rtc_cmos 00:02: System wakeup disabled by ACPI
[ 1380.091549] usb usb1: root hub lost power or was reset
[ 1380.275692] ata2.01: configured for MWDMA2
[ 1380.703941] PM: restore of devices complete after 613.452 msecs
[ 1380.704133] Restarting tasks ... 
[ 1380.704559] show_signal_msg: 6 callbacks suppressed
[ 1380.704563] systemd-logind[2362]: segfault at 0 ip   (null) sp bfe9a374 error 14 in systemd-logind[80090000+99000]
[ 1380.704776] gmain[2400]: segfault at 0 ip 0804c3e0 sp b6d9d0cc error 6 in accounts-daemon[8048000+28000]
[ 1380.705978] done.
[ 1380.720761] Setting capacity to 25165824
[ 1380.721714] apport[2874]: segfault at 4 ip b76f3256 sp bfed81e0 error 4 in ld-2.23.so[b76e3000+22000]
[ 1380.721728] Process 2874(apport) has RLIMIT_CORE set to 1
[ 1380.721731] Aborting core
[ 1380.722836] apport[2875]: segfault at 4 ip b7773256 sp bf90c5e0 error 4 in ld-2.23.so[b7763000+22000]
[ 1380.722849] Process 2875(apport) has RLIMIT_CORE set to 1
[ 1380.722851] Aborting core
[ 1380.722877] apport[2876]: segfault at 4 ip b772f256 sp bf96d440 error 4 in ld-2.23.so[b771f000+22000]
[ 1380.722885] Process 2876(apport) has RLIMIT_CORE set to 1
[ 1380.722886] Aborting core
[ 1380.724406] systemd[1]: systemd-journald.service: Failed with result 'core-dump'.
[ 1380.724565] systemd[1]: accounts-daemon.service: Main process exited, code=killed, status=11/SEGV
[ 1380.725188] systemd[1]: accounts-daemon.service: Unit entered failed state.
[ 1380.725213] systemd[1]: accounts-daemon.service: Failed with result 'signal'.
[ 1380.725663] systemd[1]: systemd-journald.service: Service has no hold-off time, scheduling restart.
[ 1380.726367] systemd[1]: Stopped Flush Journal to Persistent Storage.
[ 1380.726405] systemd[1]: Stopping Flush Journal to Persistent Storage...
[ 1380.726417] systemd[1]: Stopped Journal Service.
[ 1380.732421] systemd[1]: Starting Journal Service...
[ 1380.734417] systemd-journald[2880]: File /run/log/journal/86fa7da55b8474d1cb04304e57c7a816/system.journal corrupted or uncleanly shut down, renaming and replacing.
[ 1380.738076] systemd[1]: Started Journal Service.
[ 4106.782269] systemd[1]: segfault at 288 ip 8013d0b5 sp bff8c5e0 error 4 in systemd[80088000+163000]
[ 4106.788205] apport[3155]: segfault at 4 ip b777b256 sp bf9bb140 error 4 in ld-2.23.so[b776b000+22000]
[ 4106.788220] Process 3155(apport) has RLIMIT_CORE set to 1
[ 4106.788222] Aborting core
[ 4192.595314] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Connection refused
[ 4302.595198] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[ 4372.595240] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[ 4482.595205] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[ 4552.595265] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[ 4662.016645] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[ 4732.595200] systemd-journald[2880]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected

### In case of bug report: Steps to reproduce the problem

> migrate virtual machine( freeze and restore vm)

**Comment by martinpitt** [comment]
This just shows that accounts-daemon and logind crashed, but there is no useful information here. Please retry this with the current systemd version (on Ubuntu zesty preferably) to see if it's still an issue there (the upstream bug tracker only accepts the two most recent versions, as the form points out), and collect a backtrace.

I think this will be much easier for both you and us to use Ubuntu's crash submission system (Apport) and file a report through that. This will automatically collect the necessary information.
