### ISSUE TITLE
Use sd-event in sd-journal instead of poll?

### ISSUE THREAD

**Issue by arianvp** [systemd/systemd#5479]
### Submission type
  - [x] Request for enhancement (RFE)

Currently,   `sd-journal.(c|h)` seem to rely in `<poll.h>` .  

I was wondering if it would be wise to replace the `poll` based event loop in `sd-journal`  with `sd-event` ?

Or at least switch to `epoll` instead of `poll`

**Comment by arianvp** [comment]
~~I see that `sd-event` already supports `POLLIN` fds  . I guess then this is redundant~~

**Comment by poettering** [comment]
you can use any event loop you like. sd-event works fine, as does raw epoll, or poll. the glib or qt event loops work too. it's just a matter of registering for POLLIN/EPOLLIN (which is actually defined to the same value by libc) on the fd returned by sd-journal. Which event loop implementaiton you use doesn't matter as the kernel doesn't care, and select(), poll(), ppoll() and epoll() all work for it.

**Comment by arianvp** [comment]
Thanks! That makes total sense.
