### ISSUE TITLE
systemctl --user import-environment fails on complex environment variable with Failed to import environment: Invalid environment assignments

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#5481]
### Submission type

Bug report

### systemd version the issue has been seen with

232

### Used distribution

Debian

### In case of bug report: Expected behaviour you didn't see

    systemctl --user import-environment

Expected:

* no error message 
* exit code `0`

### In case of bug report: Unexpected behaviour you saw

    systemctl --user import-environment

> `Failed to import environment: Invalid environment assignments`

### In case of bug report: Steps to reproduce the problem

```
export QUBES_KEYMAP='xkb_keymap {
        xkb_keycodes { include "evdev+aliases(qwertz)"  };
        xkb_types { include "complete"  };
        xkb_compat { include "complete" };
        xkb_symbols { include "pc+de+inet(evdev)"       };
        xkb_geometry { include "pc(pc105)"      };
};'

systemctl --user import-environment

echo $?
```
> `Failed to import environment: Invalid environment assignments`
> `1`

**Comment by arvidjaar** [comment]
https://github.com/systemd/systemd/issues/4446
https://github.com/systemd/systemd/issues/3729

Pick your choice for duplicate :)

**Comment by poettering** [comment]
In the light of the "shellshock" vulnerability and things, I am still not convinced permitting such complex env vars to be pushed into systemd is a good idea...

**Comment by poettering** [comment]
Anyway, closing as duplicate of #3729
