### ISSUE TITLE
update DNSSEC root KSK

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#5482]
New root KSK has been published: http://data.iana.org/root-anchors/root-anchors.xml. systemd-233 must be updated to use it.

**Comment by keszybz** [comment]
Pfff, I got the timeline wrong. The old key will be discarded in early 2018. But still it would be really nice to include the new key in 233 so that all F26 installations carry it.

**Comment by poettering** [comment]
Fix waiting in #5486
