### ISSUE TITLE
MountAPIVFS= does not work as documented 

### ISSUE THREAD

**Issue by tixxdz** [systemd/systemd#5488]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> … HEAD c3988e728c11936

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> … Fedora

### In case of bug report: Expected behaviour you didn't see

> … If a service is started with "MountAPIVFS=" and "RootDirectory=" or "RootImage=", then the following /new_root/{proc|sys|dev} paths should automatically show up with their appropriate mounts.

### In case of bug report: Unexpected behaviour you saw

> …  The paths are absent
 `echo /* inside unit`   

```
Feb 28 13:26:20 fedora-tree-24 bash[91]: /bin /lib /lib64 /root /tmp /usr /var 
Feb 28 13:26:20 fedora-tree-24 bash[91]: + echo /bin /lib /lib64 /root /tmp /usr /var
Feb 28 13:26:20 fedora-tree-24 bash[91]: cat: /proc/mounts: No such file or directory
Feb 28 13:26:20 fedora-tree-24 bash[91]: + cat /proc/mounts
```

### In case of bug report: Steps to reproduce the problem

> … Start a unit with MountAPIVFS=yes and RootDirectory=/new_root/ where the paths /new_root/{proc|sys|dev} are missing.

**Comment by poettering** [comment]
Hmm, what is this bug about again? just the missing mkdir()s?

**Comment by tixxdz** [comment]
@poettering Yes.
