### ISSUE TITLE
How to : cgroup

### ISSUE THREAD

**Issue by bcv** [systemd/systemd#5490]
### Submission type

  - [ ] Bug report
  - [X ] Request for enhancement (RFE)

systemd-nspawn creates machine-<name>.scope as a cgroup automatically. Instead how to speify an already created cgroup to use for each controller cpu/memory/freezer etc., ? I want two OS to be inside a same cgroup which share CPU/memory resource and limitations in the higherarchy

**Comment by gdamjan** [comment]
* `man systemd.slice` 
* see `Slice=` in `man systemd.resource-control`
* and `--slice` in `man systemd-nspawn`

**Comment by poettering** [comment]
This is not a support forum. This is even made very clear when submitting an issue. Closing
