### ISSUE TITLE
Use of linux/dm-ioctl.h results in strict dm interface version requirements and failures on older kernels

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5492]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian sid,
filed as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856337

In Debian sid/stretch, the current version of the Linux kernel (and headers) is 4.9, which systemd was compiled against.

This results in the following failure in systemd-shutdown when trying to use a kernel < 4.8

   Could not detach DM dm-11: ioctl mismatch, kernel(4.34.4), user(4.35.4)

As mentioned by @zeha in the downstream bug report:

This is a direct result of the dm-ioctl.h header file shipped by the
Linux kernel (and the linux-libc-dev package) - any program compiled
against that official header file will embed the version number used
to build. Building systemd (or anything else) against a newer kernel
will result in this problem for older kernels.

libdevmapper works around this by embedding an old copy of
dm-ioctl.h ...

and

The exact code in the kernel is:

```
   if ((DM_VERSION_MAJOR != version[0]) ||
       (DM_VERSION_MINOR < version[1])) {
       DMWARN("ioctl interface mismatch: "
              "kernel(%u.%u.%u), user(%u.%u.%u), cmd(%d)",
              DM_VERSION_MAJOR, DM_VERSION_MINOR,
              DM_VERSION_PATCHLEVEL,
              version[0], version[1], version[2], cmd);
       r = -EINVAL;
```
So: patchlevel (4.10.0 vs 4.10.1) does not matter, the 'minor'
version (10 in 4.10) of userspace has to be lower or equal to the
kernel's number. 

The bump from 4.34 to 4.35 happened in linux.git
545ed20e6df68a4d2584a29a2a28ee8b2f7e9547 which was then part of
kernel 4.8.

**Comment by poettering** [comment]
wow, what an amazing interface designed by the kernel people there... great way how not to do "binary compatibility"... i figure we should just hardcode our own versions there.

**Comment by mbiebl** [comment]
I had a big WTF reaction myself...

**Comment by poettering** [comment]
i marked this for v234, since I am not sure this is important enough it needs to high prio to fix before 233...

That said, if you think this is important, please prep a PR and we can merge it before. I figure the way to go would be to simply copy the minimal relevant bits from the DM headers into missing.h, properly protected by `#ifdeffery`, and then stop using to the DM headers altogether...

**Comment by mbiebl** [comment]
I guess adding a dependency on libdevmapper for the few bits we need in src/shared/dissect-image.c and  src/core/umount.c is overkill?

**Comment by poettering** [comment]
in dissect-image.c we try to use libcryptsetup for all things, and we mostly manage with that. But there's one call we need that is available as ioctl but isn't available in libcryptsetup, where we then go for that.

So, if you fix libcryptsetup for us, then we could at least drop the direct ioctl usage in dissect-image.c.

Which would leave the usage in umount.c, but that one I think should definitely stay as a raw ioctl, we shouldn't add a libdevmapper dep just for that, and libcryptsetup isn't appropriate either for that.

**Comment by poettering** [comment]
but do note that the addition to missing.h would be trivial, just a few lines of codes really

**Comment by mbiebl** [comment]
Hm, looking at https://github.com/systemd/systemd/blob/master/src/core/umount.c#L350 and https://github.com/systemd/systemd/blob/master/src/shared/dissect-image.c#L1053 , couldn't we just pass a minor and patchlevel version which is less strict? Why do we always require the latest version and not use say the one from 3.12 (which is the min requirement as specified in README).

**Comment by mbiebl** [comment]
The dm interface version for 3.12.0 is 4.26.0 [1]. Do we require anything newer which would make it necessary to bump the version?

[1] https://github.com/torvalds/linux/blob/v3.12/include/uapi/linux/dm-ioctl.h#L269

**Comment by mbiebl** [comment]
looking at dm-ioctl.h, it says:
```
	/*
	 * The version number is made up of three parts:
	 * major - no backward or forward compatibility,
	 * minor - only backwards compatible,
	 * patch - both backwards and forwards compatible.
	 *
	 * All clients of the ioctl interface should fill in the
	 * version number of the interface that they were
	 * compiled with.
	 *
	 * All recognised ioctl commands (ie. those that don't
	 * return -ENOTTY) fill out this field, even if the
	 * command failed.
	 */
	uint32_t version[3];	/* in/out */
```
So hard-coding the version is probably a bad idea.

@poettering wouldn't it be simpler to just copy dm-ioctl.h verbatim from say v3.12 and use that instead  of copying bits and pieces into missing.h?

**Comment by keszybz** [comment]
Yeah, it seems like copying dm-ioctl.h verbatim would be better. The license matches, and it'll be easier to diff if we ever need to update it. Also missing.h is not really applicable, because that stuff ain't missing, we just choose to ignore it.
