### ISSUE TITLE
test-execute failure

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#5507]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

master (b7a09e35c)

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

All tests succeed.

### In case of bug report: Unexpected behaviour you saw

The `test-execute` test fails.

> ./build-aux/test-driver: line 107: 18908 Aborted                 (core dumped) "$@" > $log_file 2>&1
> FAIL: test-execute

The assertion in the coredump stacktrace is

> ```c
> log_assert_failed (text="service->main_exec_status.status == status_expected", file="src/test/test-execute.c", line=71, func=<__PRETTY_FUNCTION__.16826> "check")
> ```

The failing test from `test_exec_supplementary_groups` is the last one,
```c
test(m, "exec-supplementarygroups-single-group-user.service", 0, CLD_EXITED);
```

The full `test-suite.log` may be found [here](https://gist.github.com/lucaswerkmeister/171d2716a98955816cb2812671885da2); I’ll also be happy to email the coredump file to someone if required.

### In case of bug report: Steps to reproduce the problem

`sudo make check` (`test-execute` is skipped when not running as root)

**Comment by evverx** [comment]
Duplicate of https://github.com/systemd/systemd/issues/4610?

**Comment by lucaswerkmeister** [comment]
Looks like it (line number shifted by two, but it’s the same code line as in 5209e9afd2d5326c78bcc3520ae0476dbd0e834d, a commit with the same date as that bug) – I didn’t see that bug when searching for `test-execute`, my bad. Sorry.
