### ISSUE TITLE
Documentation of networkd not updated after change in behavior in 5e5b137acc7094c9a1b8e7634b426dd445688bf0

### ISSUE THREAD

**Issue by piotr-dobrogost** [systemd/systemd#5517]
Description of commit https://github.com/systemd/systemd/commit/5e5b137acc7094c9a1b8e7634b426dd445688bf0 :
"This is a change in behavior:

Before we would never remove any state, only add to it, we now drop unwanted
state from any link the moment we start managing it.

Note however, that we still will not remove any foreign state added at runtime,
to avoid any feedback loops. However, we make no guarantees about coexisting
with third-party tools that change the state of the links we manage."

However man page for systemd-networkd (231) states this:
"
       Network configurations applied before networkd is started are not removed, and static configuration applied by networkd is not
       removed when networkd exits. Dynamic configuration applied by networkd may also optionally be left in place on shutdown. This
       ensures restarting networkd does not cut the network connection, and, in particular, that it is safe to transition between the
       initrd and the real root, and back."

It looks like documentation was not updated accordingly to behavior change introduced in above commit.

**Comment by keszybz** [comment]
Fixed in 1c12694439ac3227819f5801e1fcc9f6667c820c.
