### ISSUE TITLE
keyctl: Permission denied

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#5522]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> v233

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> This is what `systemd` `v232` behaves:

```
$ keyctl add user test payload @u  
452119659
$ keyctl show @u
Keyring
 653507402 --alswrv   1000 65534  keyring: _uid.1000
 452119659 --alswrv   1000  1000   \_ user: test
$ keyctl read 452119659
7 bytes of data in key:
7061796c 6f6164
```

### In case of bug report: Unexpected behaviour you saw

```
$ keyctl add user test payload @u
729805790
$ keyctl show @u
Keyring
 428373429 --alswrv   1000 65534  keyring: _uid.1000
 729805790 --alswrv   1000  1001   \_ user: test
$ keyctl read 729805790
keyctl_read_alloc: Permission denied
```

### In case of bug report: Steps to reproduce the problem

> See above...

**Comment by eworm-de** [comment]
This is probably caused by 74dd6b515fa968c5710b396a7664cac335e25ca8 & b3415f5daef49642be3d5f417b8880c078420ff7.

I have two services that share their secrets via kernel keyring (and then try to inject a cryptsetup passphrase). I think the commands above are the minimum to show there is an issue with `systemd` `v233` and kernel keyring.

**Comment by jwwalton** [comment]
Confirmed.

```
% echo "12345" | keyctl padd user foobar @u 
498297883
% keyctl pipe "498297883"   
keyctl_read_alloc: Permission denied
```

This worked fine prior to v233.

**Comment by eworm-de** [comment]
Reported more than three weeks ago and still no reaction?

**Comment by poettering** [comment]
> Reported more than three weeks ago and still no reaction?

been travelling. Also, 3 weeks isn't too much actually... We have very limited man power and sometimes things take much longer, sorry.

hmm, so with the examples above the only difference appears to be the owning group, do I see that correctly? As what user/group do you run the keyctl commands? to which user/groups to the numeric UID/GIDs map here?

**Comment by poettering** [comment]
In which context do you invoke these commands btw? normal user context? oder service context? totally not getting what precisely you are trying to show here?

**Comment by eworm-de** [comment]
> been travelling. Also, 3 weeks isn't too much actually... We have very limited man power and sometimes things take much longer, sorry.

Sorry, did not want to bag anybody. I was just wondering, usually first comment are written sooner or tags are added. Just wanted to make sure this is not forgotten.

> hmm, so with the examples above the only difference appears to be the owning group, do I see that correctly? As what user/group do you run the keyctl commands? to which user/groups to the numeric UID/GIDs map here?

Ups, ignore the group. The commands were executed on two systems that I thought have identical setup (except the systemd version). For any reason the groups have a shift of one. So in both cases we have user `eworm` and its primary group `eworm`.

BTW, even `root` is suffering this issue:
```
# keyctl add user test payload @u
439697923
# keyctl show @u                 
Keyring
 546763929 --alswrv      0 65534  keyring: _uid.0
 322881179 --alswrv      0     0   \_ user: cryptsetup
 439697923 --alswrv      0     0   \_ user: test
# keyctl read 439697923
keyctl_read_alloc: Permission denied
```

> In which context do you invoke these commands btw? normal user context? oder service context? totally not getting what precisely you are trying to show here?

The commands are run from user context. This should be the minimum test case: Add a key and value to kernel keyring, then read it.

My real issue is with a more complex setup: `systemd-ask-password` reads a second factor from user to write it to kernel keyring. A udev helper reads the second factor from kernel keyring,  does challenge/response with a security token and feeds the response to cryptsetup. This used to work, but breaks with systemd v233.

**Comment by poettering** [comment]
> Ups, ignore the group. The commands were executed on two systems that I thought have identical setup (except the systemd version). For any reason the groups have a shift of one. So in both cases we have user eworm and its primary group eworm.

So, basically you are saying that the keyctl show output is exactly the same, except that some UIDs/GIDs are assigned slightly differently?

What about the contents of the other keychains? i.e. `@s` and `@us` are they different?

Note that systemd these days sets up a per-service session keyring, that is not linked up to `@us` or anything else, the keychains are kept separate on purpose. If you want to link them up, then you need to do that manually now.

**Comment by Athemis** [comment]
Probably worth mentioning that this issue is suspected to be the cause of failures to start X11 on ArchLinux: https://bugs.archlinux.org/task/53268

**Comment by software-artificer** [comment]
I'm having exact same issue on `Gentoo`.
I'm using keyctl to share keys between pam login and disk mounting service.

I have a PAM script that is storing password into keyring when user logs in and I have a user service that is responsible for mounting encrypted home directory, is using password stored in keyring and is executed just before user@%i.service, where %i is the target user id. Both PAM and service are executed as `root` user.

BUT, you can reproduce this problem even easier, as @eworm-de mentioned: just add anything into user keyring (even as a root user) and then try to access it - it will fail with permission issue.

I can confirm that it is working on 232 (I had to roll back to it to keep things working).

**Comment by oniko** [comment]
> BUT, you can reproduce this problem even easier, as @eworm-de mentioned: just add anything into user keyring (even as a root user) and then try to access it - it will fail with permission issue.

This doesn't have to be a bug at all. Note that user keyring is not searched by default. Only thread, process and session keyrings are. Usually the user keyring gets linked to session keyring but it's not a general rule you should rely on. Just my 2 cents.

**Comment by eworm-de** [comment]
`keyctl read` only accepts a key id, no additional options to specify a keyring. My understanding is that you can read every key by id independent from what keyring it resides in as long as permission is ok. Note that we do not get `key not found` but `permission denied`.

In fact I was not able to read a single key from kernel keyring. If this is not a bug... Can anybody...
* ... give commands that add a key to whatever keyring and read its value?
* ... add a key with `systemd-ask-password --keyname=example ...` and read its value?

**Comment by eworm-de** [comment]
Reverting b3415f5daef49642be3d5f417b8880c078420ff7 does not change the behaviour, so  74dd6b515fa968c5710b396a7664cac335e25ca8 introduced the issue.

**Comment by aroig** [comment]
Here is the contents of my `/proc/keys` after following the reproduction steps:

    $ cat /proc/keys
    019091e3 I--Q---   221 perm 3f030000  1000  1000 keyring   _ses: 1
    0fae1927 I--Q---     1 perm 0b0b0000     0     0 user      invocation_id: 16
    263b99bd I--Q---     2 perm 1f3f0000  1000 65534 keyring   _uid.1000: 1
    3f2dcc3b I--Q---     1 perm 1f3f0000  1000 65534 keyring   _uid_ses.1000: 1
    3f8b0840 I--Q---     1 perm 3f010000  1000  1000 user      test: 7

The permissions on the test key are `3f010000`. `3f` means, all perms for the possessor, and `01` means only view (not read) perms for the user owning the key. That would explain the permission issue, if for some reason I am not considered possessor of my own key.

If I understand http://man7.org/linux/man-pages/man7/keyrings.7.html point (1) in Possesion, I do not posses the key because the user keyring is not searched as @oniko pointed out.

So, I can read the key if I manually link `@us` to `@s` as @poettering suggested

    $ keyctl link @us @s
    $ keyctl read 1066076224    
    7 bytes of data in key:
    7061796c 6f6164

In order to do anything useful with the user keyring, either linking from `@s` or somehow adding keys with more user perms seems to be needed.

**Comment by software-artificer** [comment]
There is a good read on the topic: https://mjg59.dreamwidth.org/37333.html

**Comment by software-artificer** [comment]
So, here what I'm doing:

Adding key into session keyring:
```
fluorite ~ # keyctl add user testkey testdata @s
195216232

fluorite ~ # keyctl list @s
2 keys in keyring:
620322408: ----s-rv     0     0 user: invocation_id
195216232: --alswrv     0     0 user: testkey
```

Changing permission of the key and linking it into user keyring, request works:
```
fluorite ~ # keyctl setperm 195216232 0x3f3f0000
fluorite ~ # keyctl link 195216232 @u
fluorite ~ # keyctl list @u
2 keys in keyring:
 50751586: key inaccessible (Key has been revoked)
195216232: --alswrv     0     0 user: testkey
fluorite ~ # keyctl list @s
2 keys in keyring:
620322408: ----s-rv     0     0 user: invocation_id
195216232: --alswrv     0     0 user: testkey
fluorite ~ # keyctl request user testkey
195216232
```
Unlinking key from session keyring (still linked to user) and trying requesting fails, however search works well:
```
fluorite ~ # keyctl unlink 195216232 @s
fluorite ~ # keyctl request user testkey
request_key: Required key not available
fluorite ~ # keyctl list @u
2 keys in keyring:
 50751586: key inaccessible (Key has been revoked)
195216232: --alswrv     0     0 user: testkey
fluorite ~ # keyctl search @u user testkey
195216232
```

Can anyone explain me why exactly `keyctl request` stops working after I unlink the key from session keyring and link it into the user? `keyctl search` is still working completely fine.

**Comment by eworm-de** [comment]
If this is the way to go... `systemd-ask-password --keyname=example ...` is completely useless atm, no?

**Comment by eworm-de** [comment]
Oh, and as `systemd-ask-password` uses `request_key()` for its caching functionality... This part is broken as well. It breaks the cryptsetup stuff reading known keys for example.

**Comment by poettering** [comment]
#6275 got merged. Closing this one.

**Comment by mikhailnov** [comment]
These changes in systemd broke dracut's integrity module: https://github.com/dracutdevs/dracut/issues/1007 (and seems that nobody uses it because otherwise someone would have already fixed it)

I am wondering if adding `KeyringMode=shared` to dracut's dracut-pre-pivot.service is OK or will introduce security risks, maybe someone who better understand how kernel and systemd work in the sphere of keyrings will be able to comment this...

**Comment by martin3000** [comment]
4 years later:
Doing `sudo su -` and then `bash -c 'keyctl print $(keyctl add user key1 test1 @u)` works fine.
But inside a unit as 
```
ExecStart=bash -c 'keyctl print $(keyctl add user key1 test1 @u)'
```
 I get keyctl_read_alloc: Permission denied.

**Comment by 1fexd** [comment]
Also ran into this issue just now (even though I'm not launching keyctl directly, but rather through a tool launched through a systemd timer)

Running `keyutils-1.6.1` and `systemd 247 (247.3-7+deb11u4)` on `Debian 5.10.218-1` if that is of any help

**Comment by 1fexd** [comment]
Looks like setting setting `KeyringMode=shared` fixes my issue (but this might have security related implications https://github.com/NixOS/nixpkgs/issues/95928#issuecomment-1510424886)
