### ISSUE TITLE
systemd installs polkit policy files in /var

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#5523]
With systemd-233, we install `/var/lib/polkit-1/localauthority/10-vendor.d/systemd-networkd.pkla`. Of the three possibilities — /usr, /etc, /var — /usr is the correct one (which polkit does not support, iiuc, yuck), /etc is the fallback choice, but /var shouldn't be used. The system should work after flushing /var.

@martinpitt ?

**Comment by halfline** [comment]
my understanding is the the localauthority policy database is long deprecated, and policy should be shipped as a rules file in /usr/share/polkit-1/rules.d (though the syntax of .rules files is different than .pkla files, so it would need to be ported). @mtrmac

**Comment by mtrmac** [comment]
\*shrug\*

As you say, polkit ≥ 0.106 (June 2012) as such only supports JavaScript `.rules`, which can be shipped in `/usr` or `/etc`.

Fedora/RHEL ship `polkit-pkla-compat`, which allows recent releases of polkit to support the old `.pkla` files. Those use the same directories as the old polkit reieases, i.e. `/var` and `/etc`.

OTOH Debian has, at least looking at https://packages.debian.org/experimental/libpolkit-agent-1-0 etc, only updated from 0.105 in the “experimental” distribution, so `.pkla` in `/var` is necessary for those Debian versions.

I am honestly not all that enthusiastic about enhancing `polkit-pkla-compat` (I do view JavaScript as a mistake, but we have to live with that now, so enhancing two competing mechanisms simultaneously is rather a waste), but really the Debian situation makes that irrelevant; the Debian 0.105 does not support `/usr`.

---

Um, well, looking at https://github.com/systemd/systemd/commit/2c99aba7260a402e8f81d85aab12ce25d3d8786a , systemd actually seems to always install _both_ `.rules` and `.pkla`. There’s nothing inherently wrong with that (systems with `polkit-pkla-compat` will process both rules, so it is only redundant), and it does result in the broadest compatibility.

I guess, if the `/var` file bothers you, an easily available option would be to check for polkit ≥ 0.106 and skip the `.pkla` installation if so. With 0.105 there is no option but to use one of `/var` and `/etc` for a `.pkla` file AFAICS.

**Comment by martinpitt** [comment]
Right, neither Debian nor Ubuntu have moved to the JavaScript .rules files. Quite frankly, this was a really bad design choice (non-declarative security policies!), which was worsened by the fact that it uses libmozjs which just outright isn't supportable in stable distro releases. So this isn't just a matter of time, D/U will not move to these. Arguably shipping the policy files in /var is broken too, but as you said pkla  files just work like that.

I see two options here: (1) detect the polkit version in configure and ship a .rules file on Fedora, or (2) ship the .pkla in /usr and use tmpfiles.d to install a symlink in /var. The latter feels more like a hack, but I'm happy to work on this.

**Comment by mbiebl** [comment]
Since the  D/U  version of polkit 0.105 is basically a fork of the original polkit anyway, we could just patch it to use /usr instead of /var (I agree that using /var was a bad choice which irked me since I've seen it).
I'm not sure if any (relevant) distro besides D/U still uses pkla files, I would guess not.

**Comment by keszybz** [comment]
> an easily available option would be to check for polkit ≥ 0.106 and skip the .pkla installation if so

I think that's the way to go. I doesn't seem to make sense to install both. Install just pkla on polkit < 0.106, js otherwise.

**Comment by martinpitt** [comment]
> It doesn't seem to make sense to install both. Install just pkla on polkit < 0.106, js otherwise.

The idea was that you could build/install systemd with the old polkit, then upgrade to a newer one, and things would still work. So I'd always ship the js rules. However, it's fine to not install the pkla ones when we detect polkit >= 106 during build, as we don't expect/support a downgrade. That would still be enough to get rid of `/var` in the Fedora build.
