### ISSUE TITLE
khash does not work on Linux 3.16

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#5524]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian experimental

Building systemd 233 in experimental [failed pretty much everywhere](https://buildd.debian.org/status/package.php?p=systemd&suite=experimental), due to the new khash API:
```
FAIL: test-id128
================
Assertion 'sd_id128_get_machine_app_specific(SD_ID128_MAKE(f0,3d,aa,eb,1c,33,4b,43,a7,32,17,29,44,bf,77,2e), &id) >= 0' failed at ../src/test/test-id128.c:157, function main(). Aborting.
random: aba6b71d549e4f2bba390a748ef437b3
waldi: 0102030405060708090a0b0c0d0e0f10
waldi2: 0102030405060708090a0b0c0d0e0f10
waldi3: 01020304-0506-0708-090a-0b0c0d0e0f10
waldi4: 01020304-0506-0708-090a-0b0c0d0e0f10
FAIL test-id128 (exit status: 134)

FAIL: test-hash
===============
Assertion 'khash_new(&h, "foobar") == -EOPNOTSUPP' failed at ../src/test/test-hash.c:33, function main(). Aborting.
FAIL test-hash (exit status: 134)
```

The new "application specific ID" API in id128 uses khash, that's why that fails as well.

Debian's buildds run Debian 8 (latest stable) with Linux 3.16. Our README says:
```
REQUIREMENTS:
        Linux kernel >= 3.12
        Linux kernel >= 4.2 for unified cgroup hierarchy support
```
So supposedly we should bump that?

Right now it seems that `sd_id128_get_machine_app_specific()` isn't actually being used anywhere right now. We won't get 233 into Debian 9, so I'm not too worried about upgrade failures (i. e. upgrading Debian 8 to Debian 9 and thus upgrading to systemd > 233 while still running on 3.16), but not every distribution might be so lucky.

But we should still do something about the tests. Would it be okay to skip these two on `ENOTSUPP`? Or should we patch that downstream?

**Comment by martinpitt** [comment]
As the `test-id128` failure is not so obvious, this is the relevant line from strace:

    socket(AF_ALG, SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = -1 EAFNOSUPPORT (Address family not supported by protocol)

**Comment by evverx** [comment]
According to https://github.com/systemd/systemd/commit/9c7f7d86f86322b76fc903ca8a06b87c4be4bd4a
> Requirements
...
> Kernel crypto/hash API
           CONFIG_CRYPTO_USER_API_HASH
          CONFIG_CRYPTO_HMAC
          CONFIG_CRYPTO_SHA256

**Comment by mbiebl** [comment]
@evverx Those options are enabled in the Debian 3.16 kernel.

**Comment by mbiebl** [comment]
```
$ grep -E "CONFIG_CRYPTO_USER_API_HASH|CONFIG_CRYPTO_HMAC|CONFIG_CRYPTO_SHA256" /boot/config-3.16.0-4-amd64 
CONFIG_CRYPTO_HMAC=m
CONFIG_CRYPTO_SHA256_SSSE3=m
CONFIG_CRYPTO_SHA256=m
CONFIG_CRYPTO_USER_API_HASH=m
```

**Comment by evverx** [comment]
Hm, interesting. AF_ALG was [merged](https://github.com/torvalds/linux/commit/03c8efc1ffeb6b82a22c1af8dd908af349563314) into v2.6.38-rc1 .

Do tests work if you `modprobe` all required modules?

**Comment by mbiebl** [comment]
Hm, so I guess I have a different theory. It's not related to the kernel version but the fact that on the buildds/porterboxes we have
```
$ cat /proc/sys/kernel/modules_disabled 
1
```
As already mentioned, the Debian kernels have the crypto support enabled as modules.
As module loading is disabled, af_alg, algif_hash, sha256_* and hmac are not autoloaded.

**Comment by mbiebl** [comment]
Just built on a Debian 3.16 kernel where module loading is not disabled: The test-suite passed without problems.

**Comment by evverx** [comment]
@mbiebl , thanks! I'm not sure we should work around that in our tests

**Comment by mbiebl** [comment]
fwiw, that's the puppet template which is deployed on the Debian hosts:
https://anonscm.debian.org/cgit/mirror/dsa-puppet.git/tree/modules/debian-org/templates/rc.local.erb#n23

**Comment by evverx** [comment]
```sh
( sleep 60; echo 1 > /proc/sys/kernel/modules_disabled || true) &
```
Such setups cause mysterious failures sometimes :-)

I wonder how the `ppc64`-package was built. Were the `CONFIG_CRYPTO_*`-settings set to `Y`?

Wrt this issue
Do we support such setups? Actually we don't try to autoload all required modules on startup.

**Comment by martinpitt** [comment]
Hmm, I see the upstream perspective of not wanting to support this case. As I don't have control over the buildds I suppose I'll just add that patch downstream for the time being. Thanks for figuring out the root cause!

**Comment by poettering** [comment]
I figure we should just bypass the tests if the kernel functionality is not available. THe stuff isn't precisely at the core what systemd does and compiles fine without it being around in the local kernel
