### ISSUE TITLE
[RFE] need the ability to execute commands prior to ProtectSystem

### ISSUE THREAD

**Issue by FirefighterBlu3** [systemd/systemd#5526]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

Use case: PostgreSQL services.

PostgreSQL is paranoid about SSL certificate ownership and permissions. that in itself is fine, however, it is naive to extended filesystem permissions and relies only on simple filesystem permission checks to determine trust level. i do not wish to engage an advocacy argument about separate certificates for every service. this is a single use case and other use cases exist as well.

for example, if the filesystem permissions are set in such manner:
```
~# chown root:root /etc/letsencrypt/archive/somehost.com/privkey*.pem
~# chmod 400 root:root /etc/letsencrypt/archive/somehost.com/privkey*.pem
~# setfacl -m g:postgres:r /etc/letsencrypt/archive/somehost.com/privkey*.pem
~# stat /etc/letsencrypt/archive/somehost.com/privkey2.pem
  File: /etc/letsencrypt/archive/somehost.com/privkey2.pem
  Size: 1704            Blocks: 8          IO Block: 4096   regular file
Device: fe03h/65027d    Inode: 921405      Links: 1
Access: (0440/-r--r-----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-03-03 00:00:20.818644825 +0000
Modify: 2017-03-01 00:38:04.949318574 +0000
Change: 2017-03-03 00:36:23.393106965 +0000
 Birth: -

~# getfacl /etc/letsencrypt/archive/somehost.com/privkey*.pem
getfacl: Removing leading '/' from absolute path names
# file: etc/letsencrypt/archive/somehost.com/privkey2.pem
# owner: root
# group: root
user::r--
group::r--
group:postgres:r--
group:ldap:r--
mask::---
other::---
```

then attempting to start the postgresql service will fail as the glibc() stat call will return mode 440 for these files even though they're effectively 400 but have extended permissions only for the group postgresql.

``` syslog
Mar 02 23:37:49 somehost.com postgres[32217]: FATAL:  private key file "/etc/letsencrypt/live/somehost.com/privkey.pem" has group or world access
Mar 02 23:37:49 somehost.com postgres[32217]: DETAIL:  Permissions should be u=rw (0600) or less.
```

we used to use an ExecStartPre set of actions that temporarily did a chmod/chown before the ExecStart, then an ExecStartPost to reset the ownership and extended ACLs (there are numerous services that use the same SSL keys).

the distribution unit file has since been updated to take advantage of the ProtectSystem function. this is an excellent move for security but unfortunately, ProtectSystem goes into effect before the ExecStartPre actions are accomplished.

to resolve this without complicating things more by trying to manage moving environment and security functions out of the unit file and into a shell script, it'd be very helpful if we were able to accomplish actions prior to the enforcement of ProtectSystem.

**Comment by lucaswerkmeister** [comment]
You can prefix each `ExecStart=`, `ExecStartPre=` or `ExecStartPost=` command line with a `+`, which will run that command with full privileges (and thus without the effect of `ProtectSystem=`). Alternatively, you can set `PermissionsStartOnly=yes`, which will only apply restrictions to the `ExecStart=` line itself (effectively prefixing all `ExecStartPre=` and `ExecStartPost=` with `+`; this option is older than the `+` flag).

**Comment by poettering** [comment]
Yes please use "+" in current systemd versions, as suggested by @lucaswerkmeister or use PermissionsStartOnly= on older versions.
