### ISSUE TITLE
resolved: mDNS stack conflicts with avahi

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#5530]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> I've found this bug on 4317cf9. Maybe it has been seen since 01c901e.

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 25 x86_64 with almost latest systemd git snapshot.

### In case of bug report: Expected behaviour you didn't see

> systemd-resolved works fine with avahi-daemon.

### In case of bug report: Unexpected behaviour you saw

> If both systemd-resolved and avahi-daemon is enabled, I get the following error messages that states avahi and resolved's mDNS stack conflicts with each other.
```
$ journalctl -b
(snip)
Mar 03 21:36:39 systemd[1]: Starting Avahi mDNS/DNS-SD Stack...
Mar 03 21:36:39 avahi-daemon[7343]: Found user 'avahi' (UID 70) and group 'avahi' (GID 70).
Mar 03 21:36:39 avahi-daemon[7343]: Successfully dropped root privileges.
Mar 03 21:36:39 avahi-daemon[7343]: avahi-daemon 0.6.32 starting up.
Mar 03 21:36:39 avahi-daemon[7343]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Mar 03 21:36:39 dbus-daemon[396]: [system] Successfully activated service 'org.freedesktop.Avahi'
Mar 03 21:36:39 systemd[1]: Started Avahi mDNS/DNS-SD Stack.
Mar 03 21:36:39 avahi-daemon[7343]: Successfully called chroot().
Mar 03 21:36:39 avahi-daemon[7343]: Successfully dropped remaining capabilities.
Mar 03 21:36:39 avahi-daemon[7343]: No service file found in /etc/avahi/services.
Mar 03 21:36:39 avahi-daemon[7343]: *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Mar 03 21:36:39 avahi-daemon[7343]: *** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
(snip)
Mar 03 21:37:45 systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring.
Mar 03 21:37:45 systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring.
Mar 03 21:37:46 systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring.
Mar 03 21:37:46 systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring.
Mar 03 21:37:49 systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring.
Mar 03 21:37:49 systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring.
(snip)
```

### In case of bug report: Steps to reproduce the problem

> start systemd-resolved.service and avahi-daemon.service

**Comment by krob7591** [comment]
Not on you guy's level, but I can hack a little. If you wanna stop the  "systemd-resolved[2379]: Got mDNS UDP packet on unknown scope. Ignoring" annoying messages, edit avahi-daemon.conf...set "disallow-other-stacks= yes".  Check the man page of  avahi-daemon.conf to see what it does.
