### ISSUE TITLE
`systemctl show-environment` isn't suitable for sourcing.

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#5536]
### Submission type

  - [x] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

---

`systemctl show-environment` fails to properly quote environment variables so, e.g., the following will break badly:

```shell
systemctl --user set-environment BAD_THING="do echo 'I could have deleted everything.'"
export "$(systemctl --user show-environment)"
```

This should either be fixed by modifying the manual to not recommend sourcing from a shell script (there are other ways to import the environment):

           Dump the systemd manager environment block. The environment block
           will be dumped in straight-forward form suitable for sourcing into a
           shell script. This environment block will be passed to all processes
           the manager spawns.

Or by correctly shell quoting environment variables.

**Comment by benjarobin** [comment]
Indeed `systemctl --user show-environment` behave exactly like `env`
For example `export BAD_THING="do echo 'I could have deleted everything.'"`
=> `env | grep BAD_THING` output `BAD_THING=do echo 'I could have deleted everything.'`

**Comment by poettering** [comment]
Hmm, I figure we should be more careful there indeed.

**Comment by lucaswerkmeister** [comment]
We could do what GNU coreutils `ls` does with `--quoting-style=shell-escape` (see *info:(coreutils) Formatting the file names*), which is to emit Bash “ANSI-C Quoting” literals (see *info:(bash) ANSI-C Quoting*):

```sh
'bad'$'\n''file'
'tab'$'\t''name'
```

The `ls` documentation refers to this as a “POSIX proposed syntax suitable for most shells”; I don’t know where POSIX proposes it, but at least it is supported by both Bash and zsh. As far as I know there’s no purely POSIX syntax to achieve the same effect, unless we allow command substitution (`var=$(printf 'foo\nbar')`), which is even worse IMO.

**Comment by fsateler** [comment]
> The `ls` documentation refers to this as a “POSIX proposed syntax suitable for most shells”; I don’t know where POSIX proposes it, but at least it is supported by both Bash and zsh.

Dash seems to parse this weirdly:

```sh
a='tab'$'\t''name'
echo "$a"
# prints tab$	name
a='bad'$'\n''file'
echo "$a"
# prints bad$
# file
```

**Comment by arvidjaar** [comment]
> Dash seems to parse this weirdly

It echo who interprets escapes.

```
$ a='tab'$'\t''name'
$ printf %s "$a"
tab$\tname$ 
```

**Comment by lucaswerkmeister** [comment]
Yes, dash doesn’t support this syntax at all. We’d need to clearly document that in the manpage (not just “suitable for sourcing”).

**Comment by llua** [comment]
@lucaswerkmeister http://austingroupbugs.net/view.php?id=249
