### ISSUE TITLE
Can't resolve single-label names in the DNS

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#5549]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

systemd-resolved can not resolve single-label DNS names. For instance:

```
$ dig +short @192.168.2.1 ai.
209.59.119.34

$ systemd-resolve ai
ai: resolve call failed: All attempts to contact name servers or networks failed
```

**Comment by yrro** [comment]
As per comments on #2514 this is a design decision, and probably the correct one.

**Comment by fermulator** [comment]
see https://github.com/systemd/systemd/issues/13763

**Comment by bluppfisk** [comment]
`ResolveUnicastSingleLabel=yes` still does not seem to solve the problem of non-fully-qualified domain names (NFQDN) not being resolved.

I use a single wireguard tunnel to my corporate network (with domain **example.net**) whose dns server at **10.28.0.1** can resolve the NFQDN **test** into an IP address **10.28.0.20**.

1. With non-search domain we get no results:

```bash
resolvectl dns wg0 10.28.0.1
resolvectl domain wg0 ~example.net
resolvectl query test
```

> test: resolve call failed: 'test' not  found

2. Setting it to a search-domain simply qualifies the NFQDN into a FQDN by appending .example.net, which relies on the server doing DNS forwarding of test.example.net to **10.28.0.20**. That's not what we want:

```bash
resolvectl domain wg0 example.net
resolvectl query test
```

> test: 10.28.0.20                             -- link: wg0
>         (test.example.net)
> 
> -- Information acquired via protocol DNS in 15.7ms.
> -- Data is authenticated: no
> 

3. When I specifically tell `resolvectl` to not search (but still use the search domain), we get the desired result:

```bash
resolvectl query --search=no test
```

> test: 10.28.0.20                             -- link: wg0
> 
> -- Information acquired via protocol DNS in 15.2ms.
> -- Data is authenticated: no


Am I still doing something wrong or is `ResolveUnicastSingleLabel=yes` simply not working?

**Comment by poettering** [comment]
*[Canned reply follows]*

We detected you posted your own issue on a long-closed and only vaguely related issue. Please do not do that, to keep noise levels down. Please open your own issue, and let the maintainers handle it/merge it.

Moreover, if you have a support question, or are wondering how to use/do something with systemd, please contact the mailing list instead, as this GitHup issue tracker is a bug and feature tracker only — and not a support forum.

Thank you for understanding.
