### ISSUE TITLE
disable X && is-enabled X proves something is wrong

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#555]
```
# systemctl --help | egrep Disable\|enabled
  disable NAME...                 Disable one or more unit files
  is-enabled NAME...              Check whether unit files are enabled
# systemctl is-enabled sshd
enabled
# systemctl disable sshd
# systemctl is-enabled sshd
enabled

# find /usr/lib/systemd/system /etc/systemd/system -iname 'ssh'; cat /etc/os-release; systemctl cat sshd|cat
find: ‘/usr/lib/systemd/system’: No such file or directory
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"
# /lib/systemd/system/ssh.service
[Unit]
Description=OpenBSD Secure Shell server
After=network.target auditd.service
ConditionPathExists=!/etc/ssh/sshd_not_to_be_run

[Service]
EnvironmentFile=-/etc/default/ssh
ExecStart=/usr/sbin/sshd -D $SSHD_OPTS
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=sshd.service
```

Package: systemd
Version: 222-1
Severity: wishlist

-- Package-specific info:

-- System Information:
Debian Release: stretch/sid
  APT prefers experimental
  APT policy: (990, 'experimental'), (500, 'unstable')
Architecture: i386 (i686)

Kernel: Linux 4.0.0-2-686-pae (SMP w/1 CPU core)
Locale: LANG=zh_TW.UTF-8, LC_CTYPE=zh_TW.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/bash
Init: systemd (via /run/systemd/system)

Versions of packages systemd depends on:
ii  adduser         3.113+nmu3
ii  libacl1         2.2.52-2
ii  libapparmor1    2.9.2-3
ii  libaudit1       1:2.4.2-1
ii  libblkid1       2.26.2-8
ii  libc6           2.21-0experimental0
ii  libcap2         1:2.24-9
ii  libcap2-bin     1:2.24-9
ii  libcryptsetup4  2:1.6.6-5
ii  libgcc1         1:5.1.1-22
ii  libgcrypt20     1.6.3-2
ii  libkmod2        20-1
ii  liblzma5        5.1.1alpha+20120614-2.1
ii  libmount1       2.26.2-8
ii  libpam0g        1.1.8-3.1
ii  libseccomp2     2.2.1-2
ii  libselinux1     2.4-1
ii  libsystemd0     222-1
ii  mount           2.26.2-8
ii  sysv-rc         2.88dsf-59.2
ii  udev            222-1
ii  util-linux      2.26.2-8

Versions of packages systemd recommends:
ii  dbus            1.9.16-2
ii  libpam-systemd  222-1

Versions of packages systemd suggests:
pn  systemd-ui  <none>

-- no debconf information

**Comment by poettering** [comment]
Hmm, Debian appears to have a weird setup, can you try the find command again, but specify /lib rather than /usr/lib in the path passed?

**Comment by jidanni** [comment]
```
# find /lib/systemd/system /etc/systemd/system -iname ssh\*
/lib/systemd/system/ssh.service
/lib/systemd/system/ssh@.service
/lib/systemd/system/ssh.socket
/etc/systemd/system/multi-user.target.wants/ssh.service
/etc/systemd/system/sshd.service
# locate ssh|grep sys
/etc/systemd/system/multi-user.target.wants/ssh.service
/etc/systemd/system/sshd.service
/lib/systemd/system/ssh.service
/lib/systemd/system/ssh.socket
/lib/systemd/system/ssh@.service
/var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/ssh.service
/var/lib/systemd/deb-systemd-helper-enabled/ssh.service.dsh-also
/var/lib/systemd/deb-systemd-helper-enabled/ssh.socket.dsh-also
```

/var/lib/systemd/deb-systemd-helper-enabled/sshd.service

**Comment by poettering** [comment]
THis is all pretty weird... you have both "ssh.service" and "sshd.service." What's going on there? Did you create one of this, or did your distro do that? @mbiebl what's going on here?

**Comment by poettering** [comment]
@jidanni that output is from when the service was enabled, right? Can you poste the same "find" output, after disabling it, when "systemctl is-enabled" still claims it was enabled? Thanks!

**Comment by jidanni** [comment]
```
# systemctl disable sshd
# systemctl is-enabled sshd
enabled
# systemctl enable sshd
Failed to execute operation: No such file or directory
# systemctl is-enabled sshd
enabled
# find /lib/systemd/system /etc/systemd/system -iname ssh\*
/lib/systemd/system/ssh.service
/lib/systemd/system/ssh@.service
/lib/systemd/system/ssh.socket
/etc/systemd/system/multi-user.target.wants/ssh.service
/etc/systemd/system/sshd.service
```

**Comment by jidanni** [comment]
All I know is I used to have this (sshd) installed but not run at boot, and would like too keep things that way with systemd.

**Comment by jidanni** [comment]
```
# dlocate ssh|grep sys
openssh-server: /lib/systemd
openssh-server: /lib/systemd/system
openssh-server: /lib/systemd/system/ssh.service
openssh-server: /lib/systemd/system/ssh@.service
openssh-server: /lib/systemd/system/ssh.socket
```

**Comment by jidanni** [comment]
```
# dlocate sshd
openssh-server: /etc/pam.d/sshd
openssh-server: /usr/lib/tmpfiles.d/sshd.conf
openssh-server: /usr/share/doc/openssh-client/examples/sshd_config
openssh-server: /usr/share/man/man8/sshd.8.gz
openssh-server: /usr/share/man/man5/sshd_config.5.gz
openssh-server: /usr/sbin/sshd
# pstree|grep sshd
        |-sshd
# pstree -al|grep sshd
  |-sshd -D
  |           |           |-grep sshd
# systemctl is-enabled ssh
enabled
# systemctl disable ssh
Synchronizing state of ssh.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install disable ssh
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
Removed symlink /etc/systemd/system/sshd.service.
# systemctl is-enabled ssh
disabled
```

I see, I need to disable ssh not sshd in order to stop sshd.

**Comment by jidanni** [comment]
Anyway, something still needs to be done about my comment 1 above.

**Comment by jidanni** [comment]
i.e.,
```
# systemctl is-enabled sshd
enabled
# systemctl disable sshd
# systemctl is-enabled sshd
enabled
```

**Comment by jidanni** [comment]
OK things are looking up,

```
# systemctl is-enabled sshd
Failed to get unit file state for sshd.service: No such file or directory
```

**Comment by jidanni** [comment]
Anyway, it would be great if systemctl disable would give error messages like systemctl enable does.

**Comment by poettering** [comment]
Still confused by the relationship of sshd.service and ssh.service. Are both shipped by your .deb package? Are both files? Or is one a symlink? And if so, which one and where does it point to?

**Comment by jidanni** [comment]
```
# systemctl enable ssh
Synchronizing state of ssh.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ssh
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
Created symlink from /etc/systemd/system/sshd.service to /lib/systemd/system/ssh.service.
# systemctl is-enabled sshd
enabled
# systemctl is-enabled ssh
enabled
# systemctl disable sshd
# systemctl is-enabled ssh
enabled
# systemctl is-enabled sshd
enabled
# systemctl disable ssh
Synchronizing state of ssh.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install disable ssh
insserv: warning: current start runlevel(s) (empty) of script `ssh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (2 3 4 5) of script `ssh' overrides LSB defaults (empty).
Removed symlink /etc/systemd/system/sshd.service.
```

**Comment by jidanni** [comment]
In the tar.xz on https://packages.debian.org/sid/openssh-server you can see some of what they are doing.

**Comment by poettering** [comment]
OK, so it appears that ssh.service has Alias=sshd.service in its [install] section. This means "ssh.service" is the actual name of the service, and "sshd.service" is only an alias that exists when the unit is enabled, but not otherwise.

This means that enabling/disabling the unit is not symmetric: you cannot use "sshd.service" identical to "ssh.service" when enabling/disabling the unit, because the sshd.service is _managed_ by the enabling/disabling of the unit.

I figure what Debian's ssh package actually wants to do is what PR #382 tries to implement.

**Comment by jidanni** [comment]
Well nobody will know if

# systemctl disable

continues not to even give the slightest hint that something isn't working.

**Comment by mbiebl** [comment]
2015-07-11 20:13 GMT+02:00 Lennart Poettering notifications@github.com:

> THis is all pretty weird... you have both "ssh.service" and
> "sshd.service." What's going on there? Did you create one of this, or did
> your distro do that? @mbiebl https://github.com/mbiebl what's going on
> here?

The old ssh sysv init script was called /etc/init.d/ssh, but had

# Provides: sshd

in its LSB header.

That's why the native .service is called ssh.service and the sshd.service
symlink is there for software which might use the sshd.service name as
dependency.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by poettering** [comment]
I think this can be closed now as "enabling-via-symlink" is implemented since a while, and we thus both have an explanation for the issue, as well as a better way to avoid the issue. Closing.
