### ISSUE TITLE
systemd-resolved negative caching for extended period of time

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#5552]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

231

### Used distribution

Ubuntu 231-9ubuntu3

Over on launchpad (https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1668771), the following bug report was received. I am guessing it related to relatively recent SERVFAIL fixes https://github.com/systemd/systemd/pull/3594 . Is SERVFAIL result cached? And does the cache of such result ever expire?

### Original bug report

If a DNS lookup returns SERVFAIL, systemd-resolved seems to cache the result for very long (infinity?). I have to restart systemd-resolved to have the negative caching purged.

After SERVFAIL DNS server issue has been resolved, chromium/firefox still returns DNS error despite host can correctly resolve the name.

**Comment by poettering** [comment]
We cache SERVFAIL for 30s now. Are you saying it is cached longer for you?

See 201d99584ed7af8078bb243ce2587e5455074713

**Comment by zerkms** [comment]
It's happening to me at this very moment: `systemd 237-3ubuntu10` installed on ubuntu bionic.

The hostname was first resolved before it was added to the local DNS, then even after it was added `systemd-resolve` fails to resolve it even after few minutes.

The systemd-resolve config:

```
[Resolve]
DNS=10.50.5.9 10.50.5.10 
```

and my current observations:

```
$ systemd-resolve hostname.tld.redacted
hostname.tld.redacted: resolve call failed: 'hostname.tld.redacted' not found


$ dig hostname.tld.redacted

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> hostname.tld.redacted
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 49560
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;hostname.tld.redacted.	IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 26 02:16:12 UTC 2018
;; MSG SIZE  rcvd: 53



$ dig hostname.tld.redacted @10.50.5.10

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> hostname.tld.redacted @10.50.5.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36607
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: d14148fba8554e74a9cafb725b31a1fcaf29f9440d12a116 (good)
;; QUESTION SECTION:
;hostname.tld.redacted.	IN	A

;; ANSWER SECTION:
hostname.tld.redacted. 3600	IN	A	10.50.5.9

;; Query time: 0 msec
;; SERVER: 10.50.5.10#53(10.50.5.10)
;; WHEN: Tue Jun 26 02:16:28 UTC 2018
;; MSG SIZE  rcvd: 150
```

**Comment by zerkms** [comment]
While researching it I emitted `getent hosts hostname.tld.redacted` and it presumably cleared the cache.

So the negative cache entry was there for at least an hour.

**Comment by voggur** [comment]
Is it possible to disable negative caching in resolved.conf ?

**Comment by xnox** [comment]
One can flush caches, using
```
$ resolvectl flush-caches 
$ systemd-resolve --flush-caches
```

And one can disable *all* caching in `/etc/systemd/resolved.conf` by setting `Cache=no`, if the key is listed there.

Not sure if we need to change Cache to a tri-state to allow "no, no-negative, yes" values.

**Comment by Spenser309** [comment]
Please allow no-negative.  Caching is useful but in general SOA records are set to 15 min by default which can be long for dynamically changing cloud apps.

**Comment by Spongman** [comment]
I'm seeing the same issue. negative responses are cached and clearing the cache does not remove them. the only fix is to reboot the machine.

**Comment by rhamon** [comment]
Disabling negative caching is crucial when using consul or other service discovery that work on dns, would be sad having to disable caching completely.

**Comment by niedbalski** [comment]
I've submitted a proposal PR for addressing the tri-state cache option. Please check #13047
