### ISSUE TITLE
resolved: not failing back to IPv4 when AAAA returns SERVFAIL

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#5553]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

231

### Used distribution

Ubuntu 231-9ubuntu3

### Bug report

Not an expert in DNS resolution, or specs of what supposed to happen. Will try to reproduce this error independantly of the original bug reporter ( https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1668296 )

### Original Bug report

A reocrd exists, AAAA returns SERVFAIL, in this case resolution fails instead of falling back to IPv4 A record

$ host www.fidelityrewards.com
www.fidelityrewards.com has address 170.135.184.45
Host www.fidelityrewards.com not found: 2(SERVFAIL)

$ wget www.fidelityrewards.com
--2017-02-27 07:41:57-- http://www.fidelityrewards.com/
Resolving www.fidelityrewards.com (www.fidelityrewards.com)... failed: Name or service not known.
wget: unable to resolve host address ‘www.fidelityrewards.com

/etc/nsswitch.conf
hosts: files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns wins

libnss-resolve 231-9ubuntu3

**Comment by xnox** [comment]
I should retest this with 233, as per damjan on irc.

**Comment by poettering** [comment]
Please test with 233 and report back!

**Comment by keszybz** [comment]
I cannot reproduce this now. (Dunno if fidelityrewards.com changed their setup, or if our fixes are enough...). Please reopen if you have a another broken example.
