### ISSUE TITLE
"systemctl --user list-dependencies --recursive default.target" fails with "--recursive requires root privileges."

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#5557]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian stretch

### In case of bug report: Expected behaviour you didn't see

> ```systemctl --user list-dependencies --recursive default.target``` works correctly.

### In case of bug report: Unexpected behaviour you saw

> ```systemctl --user list-dependencies --recursive default.target``` fails with ```--recursive requires root privileges.```.

### In case of bug report: Steps to reproduce the problem

> Run ```systemctl --user list-dependencies --recursive default.target```.

**Comment by poettering** [comment]
Looks like a bug, indeed.

**Comment by keszybz** [comment]
The option to list deps recursively is `--all`. `--recursive` is for showing containers recursively. The documentation states this pretty clearly.

**Comment by AlexanderKurtz** [comment]
Indeed. I could have sworn to have read that ```--recursive``` was the right option, but as you said the manpage is pretty clear. Anyway, thank you very much for your help!
