### ISSUE TITLE
Add property if keyboard has CapsLock/NumLock LED

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#5559]
From https://bugs.freedesktop.org/show_bug.cgi?id=86257
And: https://bugzilla.gnome.org/show_bug.cgi?id=722437

It would be useful for desktop environments to be able to show Caps-Lock/Num-Lock changing when using a keyboard that doesn't have LEDs for this.

For example, my Logitech K750 which charges via little panels doesn't waste energy on LEDs. As we cannot detect this, we'd need to add metadata to say whether a particular input device has LEDs or not.

For completeness sake, the `device/capabilities/led` for my LED-less keyboard says `1f`. Which makes me think that the device isn't being truthful.

CC: @whot @bentiss @garnacho

**Comment by whot** [comment]
yeah, I'd be quite surprised if that was reliable, I think it's one of these things were we can only ever rely on the absence to be accurate, not the presence. @bentiss may know more though, maybe on some devices we can rely on them.

I'd suggest a fixed-string property with a 1/0 value, e.g. KEYBOARD_LED_NUML=0 to indicate absence. That's probably better/safer than having KEYBOARD_LEDS="numl,capsl" or some other string that needs to be parsed correctly

**Comment by hadess** [comment]
Carlos' initial implementation only supported Caps-Lock and Num-Lock, which would be fine by me.

**Comment by bentiss** [comment]
Yeah, that's completely unreliable. The K750 keyboard exports EV_LED / LED_NUML even if it doesn't have one. The Logitech DJ keyboard descriptor is the same for every keyboard they sell (see drivers/hid/hid-logitech-dj.c in the kernel) and I don't think there is a bit indicating if LEDs are there or not.

We'll need some database to know which devices lie.
