### ISSUE TITLE
systemd-firstboot service won't have any chance to run when booting with 'ro'

### ISSUE THREAD

**Issue by fmore-xyz** [systemd/systemd#5562]
Hello,

systemd-firstboot service runs when /etc/machine-id is not present and this service is supposed to create this file according to the manpage.

If the system boots with 'ro', the rootfs is mounted read only when systemd is started and it won't create machine-id (it's supposed to be done by systemd-firstboot after all) and will start the boot process.

However since machine-id file is missing systemd-journald will fail to start and the boot process will fail before systemd-firstboot is started.

I think booting with 'ro' has been a common setup since a while. It's actually the default if neither 'rw' nor 'ro' are specified.

**Comment by evverx** [comment]
Has it ever worked?

Actually, `systemd` [prints](https://github.com/systemd/systemd/commit/86fb9ca7ae49790) this error:
```
System cannot boot: Missing /etc/machine-id and /etc is mounted read-only.
Booting up is supported only when:
1) /etc/machine-id exists and is populated.
2) /etc/machine-id exists and is empty.
3) /etc/machine-id is missing and /etc is writable.
```
But I should pass `systemd.log_target=console` to see it.

**Comment by fmore-xyz** [comment]
On Fri, Mar 10, 2017 at 1:31 AM, Evgeny Vereshchagin <
notifications@github.com> wrote:

> Have it ever worked?
>
> Actually, systemd prints
> <https://github.com/systemd/systemd/commit/86fb9ca7ae49790> this error:
>
> System cannot boot: Missing /etc/machine-id and /etc is mounted read-only.
> Booting up is supported only when:
> 1) /etc/machine-id exists and is populated.
> 2) /etc/machine-id exists and is empty.
> 3) /etc/machine-id is missing and /etc is writable.
>
> But I should pass systemd.log_target=console to see it.
>

Well /etc is not mounted read-only, it's just read-only at the time systemd
is started. I would think this behavior supported as it has been seen on
most distributions.

And the main point of systemd-firstboot is to create machine-id, so I would
have expected it to work in this case specially since
systemd-firstboot.service has:

   After=systemd-remount-fs.service

Thanks.
-- 
Francis

**Comment by evverx** [comment]
> And the main point of systemd-firstboot is to create machine-id

`systemd-firstboot` doesn't create `/etc/machine-id`.

Well, it can [create](https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html#--setup-machine-id) `/etc/machine-id`. But you should use `--root`.

> Initialize the system's machine ID to a random ID. This only works in combination with --root=.

> This is useful to operate on a system image mounted to the specified directory instead of the host system itself.

I think the documentation is misleading.

**Comment by fmore-xyz** [comment]
On Fri, Mar 10, 2017 at 1:31 AM, Evgeny Vereshchagin <
notifications@github.com> wrote:

> Have it ever worked?
>
> Actually, systemd prints
> <https://github.com/systemd/systemd/commit/86fb9ca7ae49790> this error:
>
> System cannot boot: Missing /etc/machine-id and /etc is mounted read-only.
> Booting up is supported only when:
> 1) /etc/machine-id exists and is populated.
> 2) /etc/machine-id exists and is empty.
> 3) /etc/machine-id is missing and /etc is writable.
>
>
also this seems that systemd-firstboot.service can't work at all because

 - it needs that machine-id to be missing from /etc (start condition)
 - journald needs machine-id otherwise it fails to start
 - systemd creates a machine-id file in the 3 cases you described

So either systemd-firstboot.service won't start because machine-id is
present or because the system fails to boot.

-- 
Francis

**Comment by evverx** [comment]
> also this seems that systemd-firstboot.service can't work at all because
>  it needs that machine-id to be missing from /etc

It works if
```
3) /etc/machine-id is missing and /etc is writable.
```

Actually, `systemd`:
* checks `/etc/machine-id`
* creates `/run/systemd/first-boot`
* creates `/etc/machine-id`
* starts everything

, and `ConditionFirstBoot=yes` is the same as `access(/run/systemd/first-boot, F_OK) >= 0`

**Comment by fmore-xyz** [comment]
On Fri, Mar 10, 2017 at 8:24 AM, Evgeny Vereshchagin <
notifications@github.com> wrote:

> also this seems that systemd-firstboot.service can't work at all because
> it needs that machine-id to be missing from /etc
>
> It works if
>
> 3) /etc/machine-id is missing and /etc is writable.
>
>
>
in this case doesn't systemd already create it when systemd is started (see
machine_id_setup()) ?

-- 
Francis

**Comment by evverx** [comment]
Yes, it does. But that's OK because `systemd` [detects](https://github.com/systemd/systemd/blob/48a601fe5de8aa0d89ba6dadde168769fa7ce992/src/core/main.c#L1743) an "empty_etc" before `machine_id_setup`.

Again, `systemd-firstboot` doesn't create `/etc/machine-id`. `systemd` creates `/etc/machine-id`

**Comment by fmore-xyz** [comment]
On Fri, Mar 10, 2017 at 9:10 AM, Evgeny Vereshchagin <
notifications@github.com> wrote:

> Yes, it does. But that's OK because systemd detects
> <https://github.com/systemd/systemd/blob/48a601fe5de8aa0d89ba6dadde168769fa7ce992/src/core/main.c#L1743>
> an "empty_etc" before machine_id_setup.
>
> Again, systemd-firstboot doesn't create /etc/machine-id. systemd creates
> /etc/machine-id
>

oh I see now, I missed previously the fact systemd detects the firstboot
condition before it tries to create machine-id.

Couldn't systemd fail earlier in case /etc is RO and machine-id is missing
instead of proceeding the boot which will fail later ?

Thanks !
-- 
Francis

**Comment by evverx** [comment]
> Couldn't systemd fail earlier in case /etc is RO and machine-id is missing
instead of proceeding the boot which will fail later ?

Well, that's a good question. I think, the "ignore-and-proceed-anyway"-approach is better because there is a chance that we can start all required services (a network, `ssh`...), so somebody/something can fix a problem.

Of course, we can `freeze` (or we can drop a system to the `emergency`-mode). But that's harder to fix.

Maybe I'm missing something.

**Comment by fmore-xyz** [comment]
On Fri, Mar 10, 2017 at 10:30 AM, Evgeny Vereshchagin <
notifications@github.com> wrote:

> Couldn't systemd fail earlier in case /etc is RO and machine-id is missing
> instead of proceeding the boot which will fail later ?
>
> Well, that's a good question.
>
At least one ;)

Anyways thank you for answering and for clarifying.

**Comment by poettering** [comment]
Hmm, so what is this bug really about now? Is this all just a misunderstanding and we can close this now?

**Comment by fmore-xyz** [comment]
On Wed, Mar 29, 2017 at 3:50 PM, Lennart Poettering <
notifications@github.com> wrote:

> Hmm, so what is this bug really about now? Is this all just a
> misunderstanding and we can close this now?
>

You can close it, it's just a misunderstanding sorry.

-- 
Francis
