### ISSUE TITLE
Please update the util-linux built option ``--enable-libmount-force-mountinfo'' to the new name in the README.

### ISSUE THREAD

**Issue by hongyi-zhao** [systemd/systemd#5563]
### Submission type

  - [ ] Bug report

> This is not a bug of systemd, but it will cause systemd failed to compile when we step by step according to the README to compiling systemd.

> In the  README, it says that:

        libmount >= 2.27.1 (from util-linux)
                (util-linux *must* be built with --enable-libmount-force-mountinfo)

> In fact, in the recent versions of util-linux, the above option has been taken over by the following one:
        --enable-libmount-support-mtab

> So, please update the README accordingly.

Regards

**Comment by marcosfrm** [comment]
This change was made in util-linux 2.29:

https://github.com/karelzak/util-linux/commit/e778642a9eb96975fcf3baa61dfa10add628af1a
