### ISSUE TITLE
How to replace the default systemd in my os with the latest version compiled based on source code of git?

### ISSUE THREAD

**Issue by hongyi-zhao** [systemd/systemd#5567]
Hi all,

I use Debian Jessie, which shipped an older version of systemd.  I tried to replace it with the latest version compiled based on source code of git.

But according to the compiling steps noted in the README, I finally destroyed my os and must re-install the whole os, sigh.

I've tried to search google for this type of job, but still cann't figure out it.

Any notes or hints for my issue?

Regards

**Comment by falconindy** [comment]
I would defer to your distro for how to build a package from a git source. Or, create a suitable tarball from git and feed that into your package creation process.

Not really a problem for upstream systemd to solve. Following the directions in the upstream README without regard to the way your distro has integrated systemd into it will definitely lead to pain, as you've found out.

**Comment by mbiebl** [comment]
That's bug tracker, not a help forum.
