### ISSUE TITLE
Encrypted devices 

### ISSUE THREAD

**Issue by AaronBPaden** [systemd/systemd#5568]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

For encrypted devices that fail to unmount cleanly (see #1620), systemd should respect DefaultTimeoutStopSec.

### In case of bug report: Unexpected behaviour you saw

I'm pretty sure that this used to work with a previous version, but for now it's taking the full 90 seconds.

### In case of bug report: Steps to reproduce the problem

Assuming you are affected by #1620, set DefaultTimeoutStopSec in /etc/systemd/system.conf.

**Comment by poettering** [comment]
What precisely is timing out for you? Can you provide a log output that shows the offending timeout?

**Comment by poettering** [comment]
Closing due to lack of response
