### ISSUE TITLE
Monitored kdbus system bus becomes unusable

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#557]
While `busctl monitor` is running, the bus seems unusable. `systemctl start` hangs and `d-feet` gets a timeout on all its attempts at introspection.

Linux 4.1.2 with kdbus-next (systemd/linux@c61382ef278eb8569c87e4be3077f3f9f1f2fc49)
systemd v222

**Comment by dvdhrm** [comment]
Indeed. It's actually pretty subtle and happens only if you monitor with metadata, but the actual message-receiver doesn't want metadata. The actual message payload of the non-monitor message will then contain garbage (information leak, but will not crash).

Applied on kdbus.ko, this fixes the issue for me:

```
diff --git a/ipc/kdbus/message.c b/ipc/kdbus/message.c
index 64763ea..3520f45 100644
--- a/ipc/kdbus/message.c
+++ b/ipc/kdbus/message.c
@@ -946,6 +946,16 @@ struct kdbus_pool_slice *kdbus_staging_emit(struct kdbus_staging *staging,
                ++v;

                msg_size = KDBUS_ALIGN8(msg_size) + meta_size;
+       } else {
+               /* metadata items */
+               v->iov_len = 0;
+               v->iov_base = (void __user *)zeros;
+               ++v;
+
+               /* padding after metadata */
+               v->iov_len = 0;
+               v->iov_base = (void __user *)zeros;
+               ++v;
        }

        /* ... payload iovecs are already filled in ... */
```

I will write a proper commit later on. Thanks for the report!

**Comment by dvdhrm** [comment]
https://github.com/systemd/linux/commit/2cd255dd5ba5ab94d93d07f60f940e1a9133632b

**Comment by dvdhrm** [comment]
This is now merged in kdbus-next in Greg's tree.
