### ISSUE TITLE
Coverity hasn't analyzed systemd since Feb 21, 2017

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5577]
https://scan.coverity.com/projects/350

![screen shot 2017-03-13 at 10 21 54](https://cloud.githubusercontent.com/assets/10195800/23845045/f49bc81c-07d6-11e7-8380-bb1df2eae05a.png)

**Comment by keszybz** [comment]
We used to have a semaphore config (https://semaphoreci.com/systemd/systemd--2), but it's gone. I don't know who deleted it or why. We need to set something up so cov-build gets done twice a week or so.

**Comment by evverx** [comment]
Coverity seems to have started working, so I'm closing the issue.
