### ISSUE TITLE
Make sense of machinectl return code (provide more debug info)

### ISSUE THREAD

**Issue by voxik** [systemd/systemd#5581]
### Submission type

  - [x] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> rpm -q systemd
systemd-233-2.fc27.x86_64

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora Rawhide

### In case of bug report: Unexpected behaviour you saw

Originally, I opened this ticket [[1]] into RH bugzilla. But:

1) The machinectl keeps returning failed state.
2) It is no obvious why.

e.g.:

~~~
$ machinectl list
MACHINE                          CLASS     SERVICE        OS     VERSION ADDRESSES
74c006fc3ec0409d89fcb06a1ea69c9e container systemd-nspawn fedora 27      -

1 machines listed.

$ echo $?
1
~~~

This seems to different issue then [[2]] (since obviously I am running container this time) and it is PITA to submit more information, because there is no problem logged into journal unless I use "debug" kernel option nor there is error reported by machinectl.

### In case of bug report: Expected behaviour you didn't see

I'd appreciate if machinectl did not return error in case it is not obvious why. If there was error returned, I should be able to understand the error from information I have available.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1419501
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1419501#c7

**Comment by lucaswerkmeister** [comment]
I ran `machinectl` with `SYSTEMD_LOG_LEVEL=debug` and saw one “error” message (emphasis added):

> Got message type=error sender=:1.2348 destination=:1.2372 object=n/a interface=n/a member=n/a cookie=64 reply_cookie=4 error=**Machine Arch-Base does not use private networking**

When I added `--private-network` to the `systemd-nspawn` command and re-ran `machinectl`, the error vanished and `machinectl`’s exit code changed to 0. It looks like the error from the dbus call is propagated through `print_addresses` and `list_machines` to `main`. I’m not sure if this is correct – perhaps the `if` case here should reset `r` to 0 in the `if` branch:
```c
                r = print_addresses(bus, machines[j].name, 0, "", prefix, arg_addrs);
                if (r <= 0) /* error or no addresses defined? */
                        fputs("-\n", stdout);
                else
                        fputc('\n', stdout);
```

**Comment by voxik** [comment]
> I ran machinectl with SYSTEMD_LOG_LEVEL=debug

Ha, this is good tip, so there are several errors running one container and one libvirt VM:

~~~
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 error=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2201 object=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 error=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.machine1 object=/org/freedesktop/machine1 interface=org.freedesktop.machine1.Manager member=ListMachines cookie=2 reply_cookie=0 error=n/a
Got message type=method_return sender=:1.311 destination=:1.2201 object=n/a interface=n/a member=n/a cookie=5379 reply_cookie=2 error=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.machine1 object=/org/freedesktop/machine1 interface=org.freedesktop.machine1.Manager member=GetMachineOSRelease cookie=3 reply_cookie=0 error=
Got message type=error sender=:1.311 destination=:1.2201 object=n/a interface=n/a member=n/a cookie=5380 reply_cookie=3 error=Requesting OS release data is only supported on container machines.
Sent message type=method_call sender=n/a destination=org.freedesktop.machine1 object=/org/freedesktop/machine1 interface=org.freedesktop.machine1.Manager member=GetMachineOSRelease cookie=4 reply_cookie=0 error=
Got message type=method_return sender=:1.311 destination=:1.2201 object=n/a interface=n/a member=n/a cookie=5381 reply_cookie=4 error=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.machine1 object=/org/freedesktop/machine1 interface=org.freedesktop.machine1.Manager member=GetMachineAddresses cookie=5 reply_cookie=0 error=
Got message type=error sender=:1.311 destination=:1.2201 object=n/a interface=n/a member=n/a cookie=5382 reply_cookie=5 error=Machine 74c006fc3ec0409d89fcb06a1ea69c9e does not use private networking
Sent message type=method_call sender=n/a destination=org.freedesktop.machine1 object=/org/freedesktop/machine1 interface=org.freedesktop.machine1.Manager member=GetMachineAddresses cookie=6 reply_cookie=0 error=
Got message type=error sender=:1.311 destination=:1.2201 object=n/a interface=n/a member=n/a cookie=5383 reply_cookie=6 error=Requesting IP address data is only supported on container machines.
MACHINE                          CLASS     SERVICE        OS     VERSION ADDRESSES
74c006fc3ec0409d89fcb06a1ea69c9e container systemd-nspawn fedora 27      -
qemu-1-rawhide                   vm        libvirt-qemu   -      -       -

2 machines listed.
~~~
