### ISSUE TITLE
systemd-resolve returns "Operation not supported" when built with --disable-gcrypt and DNSSEC is not disabled

### ISSUE THREAD

**Issue by benkohler** [systemd/systemd#5583]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

systemd-233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Gentoo Linux

### In case of bug report: Expected behaviour you didn't see

``# systemd-resolve google.com``
``google.com: 172.217.6.174``

``-- Information acquired via protocol DNS in 237.6ms.``
``-- Data is authenticated: no``
``#``

### In case of bug report: Unexpected behaviour you saw

``# systemd-resolve google.com``
``google.com: resolve call failed: Lookup failed due to system error: Operation not supported``
``#``

### In case of bug report: Steps to reproduce the problem

Build systemd with --disable-gcrypt and leave DNSSEC setting at its default value or force DNSSEC=allow-fallback in /etc/systemd/resolved.conf .  Then try to use systemd-resolve or any DNS request via resolved.

**Comment by poettering** [comment]
indeed, we should not permit such a setup.
