### ISSUE TITLE
Reenabling ForwardToSyslog option in journal.conf and restarting journald doesn't send logs to syslog

### ISSUE THREAD

**Issue by lewicki-pk** [systemd/systemd#5586]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

230 and 232

### Used distribution

Yocto (morty branch)

### In case of bug report: Expected behaviour you didn't see

After restarting `systemd-journald` logs from all of the services end up in rsyslog log files.

### In case of bug report: Unexpected behaviour you saw

After restarting `systemd-journald` my logs were not sent to rsyslog.

### In case of bug report: Steps to reproduce the problem

1. Change the option `ForwardToSyslog` from yes to no.
2. Restart the systemd-journal service (`systemctl restart systemd-journald`)
3. Check if syslog files are no longer written to (in my case they are not appended).
4. Change the option `ForwardToSyslog` back to yes.
5. Restart the systemd-journal service again (`systemctl restart systemd-journald`)
6. Syslog files are still not appended.
7. After restarting only one of running services you can observe that the logs from that service show up in syslog files and logs from other services do not.

### Comment

I'm using systemd provided by yocto system so it has some extra patches applied. If you're familiar with Yocto project than you can read the recipe here http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_232.bb?h=master and also check the patches here: http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd

My setup info:
I have a system where my systemd-journal uses only volatile storage and I have rsyslog configured to store logs in the persistent directory.

**Comment by evverx** [comment]
I can't reproduce.

@lewicki-pk could you please run
```
PID=$(systemctl --property MainPID --value show systemd-journald)
strace -p $PID -yy -s500 -v |& grep /run/systemd/journal/syslog
```
? Does it print anything?

Do `rsyslog.conf`, `rsyslog.conf.d/*` contain
```
$ModLoad imuxsock
$OmitLocalLogging no
$SystemLogSocketName /run/systemd/journal/syslog
```
?

**Comment by evverx** [comment]
Try to attach `strace` to a process that prints logs. Do you see something like
```
write(1, ...) = 4
```
or something like
```
write(1, ...) = -1 EPIPE (Broken pipe)
```
?

**Comment by lewicki-pk** [comment]
I do not have `strace` on my board. I'll try to create a similar image with development tools and I'll get back to you.

**Comment by evverx** [comment]
OK, thanks.

Do you have `nc`? Could you please check that `rsyslog` really reads data from `/run/systemd/journal/syslog`
```
printf "<13>TEST STRING" | nc -U --udp /run/systemd/journal/syslog
grep -r 'TEST STRING' /var/log/
```
?

**Comment by lewicki-pk** [comment]
@evverx I have checked this issue with `strace`.

This turns out to be my mistake, because toggling `ForwardToSyslog` option works after restarting `systemd-journald`.

Messages are being sent to `/run/systemd/journal/syslog` socket.

Thing is that my `rsyslog` moved all of the messages from `daemon` section to `user` section and that's why I assumed that I don't receive anything.

This is now a problem of my rsyslog configuration or/and rsyslog bug.

Thanks for help. I'm closing the issue.
