### ISSUE TITLE
Systemd-networkd does not parse .network file (or does it incorrectly)

### ISSUE THREAD

**Issue by wsw70** [systemd/systemd#5588]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> fresh install of Ubuntu (yakkety) with systemd updated to 233 

### In case of bug report: Expected behaviour you didn't see

> systemd-networkd sets up the IP on the NIC

### In case of bug report: Unexpected behaviour you saw

> the IP is not set, or set on the wrong NIC

### In case of bug report: Steps to reproduce the problem

Starting from a fresh install of yakkety, my IP is not set:

```
root@srv:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: host0@if17705: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d6:fa:2e:69:dd:30 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

I enable systemd-networkd:

```
root@srv:~# systemctl enable systemd-networkd
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service → /lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket → /lib/systemd/system/systemd-networkd.socket.
```

I create a .network file in /etc/systemd/network:

```
root@srv:/etc/systemd/network# cat host0.network
[Match]
Name=host0

[Network]
Address=10.5.1.1/24
Gateway=10.5.1.254
```

After restarting networkd or rebooting the container, the IP is not set (`ip addr` is the same as above)

I tried to comment the `[Match]` and `Name=`  line and rebooted, the IP was then configured on `lo`:

```
root@srv:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.5.1.1/24 brd 10.5.1.255 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: host0@if17710: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether d6:fa:2e:69:dd:30 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 169.254.229.86/16 brd 169.254.255.255 scope link host0
       valid_lft forever preferred_lft forever
    inet6 fe80::d4fa:2eff:fe69:dd30/64 scope link
       valid_lft forever preferred_lft forever
```

Networking works as expected when using `/etc/network/interfaces` (the IP is set correctly and when appropriate bridging is in place, normal traffic can occur).

**Comment by gdamjan** [comment]
it's probable that `/usr/lib/systemd/network/80-container-host0.network` overrides your .network config file,
make it the same name in /etc/

**Comment by wsw70** [comment]
Thanks, that was it (the file was actually in `/lib/systemd/network/80-container-host0.network`).

**Comment by keszybz** [comment]
Note that `networkctl status host0` will show you the name of the .network file. That helps to diagnose cases like this.
