### ISSUE TITLE
/proc/sys/net/core/somaxconn 128 in the container

### ISSUE THREAD

**Issue by fossxplorer** [systemd/systemd#5592]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with
219-30.el7

### Used distribution
CentOS 7.3

### In case of bug report: Expected behaviour you didn't see
Both host and container to have same value of /proc/sys/net/core/somaxconn

### In case of bug report: Unexpected behaviour you saw
Value of /proc/sys/net/core/somaxconn inside the container differs from host.

### In case of bug report: Steps to reproduce the problem
1.Start the with networking, e.g
[root@config]#systemd-nspawn  --bind /var/data/:/var/data --bind /var/data/ssd960_01:/var/data/ssd960_01 --network-macvlan=enp2s0f0 -bD mariadb_dev/
2. Log into the container and run'
[root@config]# cat  /proc/sys/net/core/somaxconn
128

**Comment by fossxplorer** [comment]
I was confused by the fact that the host had a not-permanent and running value of 1024 for /proc/sys/net/core/somaxconn, while the permanent value was 128.
Closed!

**Comment by tixxdz** [comment]
@fossxplorer 
> I was confused by the fact that the host had a not-permanent and running value of 1024 for /proc/sys/net/core/somaxconn, while the permanent value was 128.

Yes the default value for somaxconn is 128 for each network namespace.

Your host was updated to 1024, but new containers with private network namespaces and their /proc mounts will have 128 as a default value.

If you want to update the value for your mariadb container, you have to do it inside the container and update the root filesystem of the container, two choices here:

1) Update to latest systemd version, 219 is old. There was a patch https://github.com/systemd/systemd/pull/4395 which allowed to rewrite these values using the /etc/sysctl.conf and systemd-sysctl.service during boot. The logic is if you create a new network namespace there will be writable mounts /proc/sys/net/ for your container  (not sure if the path /proc/sys/net is fully virtualized though ... ) . Then you can just set net.core.somaxconn inside sysctl.conf files inside your container filesystem and let systemd-sysctl handle it.

2) With old systemd versions, you can create a new *service* unit, *not mount units*, something like the following to remount /proc/sys writable...
```
[Unit]
Description=Prepare /proc/sys/ for containers
Before=local-fs.target systemd-sysctl.service
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/bin/mount -o remount,rw /proc/sys/

[Install]
WantedBy=sysinit.target
```

Totally untested but you may start from it. Several users did already report this problem in the past. You should add also another unit after sysctl service or sysinit.target to make /proc/sys readonly again. With this you can plug your sysctl configurations and systemd-sysctl.service will write them.
