### ISSUE TITLE
journald: Confirmation that an entry has made it into the journal

### ISSUE THREAD

**Issue by anoo1** [systemd/systemd#5602]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

> v232

### Used distribution

> Yocto embedded Linux

We're using journald to log errors in an embedded system, but when there are a lot of entries being logged into the journal at a time and a query into the journal is made, not all entries are displayed since they haven't made it into the journal.
Looking for some notification that an entry (or all entries) have made it into the journal, or a flush that can be called before querying the journal, etc.
If one of these approaches or some other proposal make sense I can work on submitting a patch.

**Comment by evverx** [comment]
>  or a flush that can be called before querying the journal

Did you try [`journalctl --sync`](https://www.freedesktop.org/software/systemd/man/journalctl.html#--sync)?

> Asks the journal daemon to write all yet unwritten journal data to the backing file system and synchronize all journals. This call does not return until the synchronization operation is complete. This command guarantees that any log messages written before its invocation are safely stored on disk at the time it returns.

**Comment by anoo1** [comment]
Thanks, I'll try that. Is there an sd-journal API equivalent , or otherwise just execute journalctl from a system() call?

**Comment by evverx** [comment]
Sadly, there is no an sd-journal API equivalent, so you have to call `system()` or manually implement the [`send_signal_and_wait`-protocol](https://github.com/systemd/systemd/blob/4f37cbd91164f8cd7dbc90e3b3594697fec50f38/src/journal/journalctl.c#L1871).

**Comment by anoo1** [comment]
`journalctl --sync` seems to do what we were looking for, thanks again for the pointer.
