### ISSUE TITLE
systemd-logind - KillUserProcesses fails with kwin_wayland

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#5603]
- [ ] Bug report
 
> systemd 233-1
> Arch

With, for instance, lxqt and openbox: 1) login to linux terminal, 2) run startx and startlxqt, 3) end lxqt session, 4) logout from linux terminal, and 5) login again to linux terminal.  Previous user processes will have terminated, as expected, where logind.conf has KillUserProcesses=yes.

If instead, doing the same steps, except step 2) with `dbus-launch kwin_wayland --xwayland --exit-with-session startlxqt`, all user processes from the previous login/logout will not have been terminated, and can be seen still running on login.

`man logind.conf` says of `KillUserProcesses`: "If true, the scope unit corresponding to the session and all processes inside that scope will be terminated.

So, has the scope of the user processes run under `kwin_wayland` been "properly" changed to some kind of "non-user" scope?  Or, is this simply some bug in systemd-logind?

**Comment by poettering** [comment]
i have no idea what kwin_wayland is doing. if you use "loginctl user-status" and "loginctl session-status" do you see sessions/users being around when you assume they shouldn't be around?

I have never used KDE and relaly don't know what these tools do and how they behave. I am not sure I can help here much.

**Comment by poettering** [comment]
Hmm, thinking about this, I am pretty sure it would be best to involve the KDE folks in this, and let them escalate this back if they verified it's a bug in logind. Closing hence, I hpoe that makes sense.
