### ISSUE TITLE
Supporting setting /proc/cmdline in systemd-nspawn container

### ISSUE THREAD

**Issue by pwithnall** [systemd/systemd#5605]
### Submission type

Request for enhancement

### systemd version the issue has been seen with

git master (`v233-57-g825fd3c`)

### Used distribution

Fedora 25 (but `systemd-nspawn` is compiled from git)

### Request for enhancement

In order to support running containers which runs software which checks `/proc/cmdline` for certain arguments, `systemd-nspawn` needs to support overmounting it with something which is not `/proc/cmdline` from the host.

The situation I have in mind is when running a non-OSTree system on the host, and running an OSTree system in a container — it checks the `ostree=` argument in `/proc/cmdline` to see which OSTree deployment was booted. The same problem will occur in other situations though — there was a [mailing list discussion in 2013 about it](https://lists.freedesktop.org/archives/systemd-devel/2013-December/015173.html).

The solution suggested in that mailing list thread (`--bind=path/to/temp/cmdline:/proc/cmdline`) will not work, as custom mounts are done before the inner `systemd-nspawn` exec; which then overmounts `/proc` itself.

I suggest this could be fixed either by:
 * adding a `--cmdline=` argument which takes a string for the container’s kernel command line, puts it in a temporary file, and overmounts that on `/proc/cmdline` in the container after the rest of `/proc` has been set up; or
 * adding support for ‘late’ custom mounts (maybe something like `--bind-late=` and `--bind-late-ro=`, or some prefix for `--bind=` similar to `--bind=+`) which are applied in the inner child of `systemd-nspawn`, after all other mounts — though I think they would have to be mounted in two stages (once in the outer child to a temporary location, once in the inner child to move the mount) since the inner child doesn’t have access to the host file system namespace

Given that the only real use for ‘late’ custom mounts would be to override bits of `/proc` and `/sys`, I think it’s probably better to go with a `--cmdline=` argument, since there can’t be many other use cases for overwriting bits of them.

**Comment by poettering** [comment]
systemd's own tools automatically use /proc/1/cmdline instead of /proc/cmdline when detecting they are run in a container. That way we are a lot more compatible with the various container managers around which generally don't overmount /proc/cmdline.

Wouldn't it make more sense to change ostree to do the same? i.e. rather than changing nspawn to make ostree work, change ostree to be more compatible with any type of container manager?

**Comment by pwithnall** [comment]
That’s also a viable option. @cgwalters, what do you think?

**Comment by cgwalters** [comment]
Yep, makes sense to me.

**Comment by poettering** [comment]
(Be aware that /proc/cmdline and /proc/1/cmdline have a different format though. The former you need to split at spaces manually, the latter already comes pre-split with NUL bytes).

(in systemd we also support an env var `$SYSTEMD_PROC_CMDLINE` btw which may be used to override the kernel cmdline used, as a debug tool, you might want to add something similar while you are at it)

**Comment by poettering** [comment]
Closing this given that @cgwalters agreed to make this an ostree issue.

**Comment by pwithnall** [comment]
(Filed as an OSTree bug [here](https://github.com/ostreedev/ostree/issues/785).)

**Comment by XieJiSS** [comment]
What about /proc/cpuinfo then? Seems like the provided workaround is not capable. Maybe we should reconsider the --bind-late solution?
