### ISSUE TITLE
Only when run as root, `systemd-analyze verify` causes the unit to be "changed on disk"

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5609]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*
232 is prev. to last, so I'm good:)

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> no warning during systemctl --no-pager status tmp.mount

### In case of bug report: Unexpected behaviour you saw

> a warning during systemctl --no-pager status tmp.mount
Warning: tmp.mount changed on disk. Run 'systemctl daemon-reload' to reload unit

### In case of bug report: Steps to reproduce the problem

> $ sudo systemctl daemon-reload
> $ systemctl --no-pager status tmp.mount
> see all is good
> $ sudo systemd-analyze verify tmp.mount
> $ systemctl --no-pager status tmp.mount
> see the issue is the warning: `Warning: tmp.mount changed on disk. Run 'systemctl daemon-reload' to reload units.`
>
> To avoid the issue, don't run systemd-analyze as root (remove the `sudo` in above).

One line to reproduce the issue and that shows the file hasn't changed on disk.
```bash
$ sudo systemctl daemon-reload && systemctl --no-pager status tmp.mount && sudo -v && diff -up -- <(stat /usr/lib/systemd/system/tmp.mount; sudo systemd-analyze verify tmp.mount) <(sleep 1;stat /usr/lib/systemd/system/tmp.mount); systemctl --no-pager status tmp.mount
```

**Comment by poettering** [comment]
Can't reproduce this on 233 here. Is this still an issue on 233 for you? please update.

**Comment by ghost** [comment]
Had to use pacman `[testing]` repo in /etc/pacman.conf to get v. 233, but the issue is still reproducible for me after a reboot:

```bash
$ systemctl --no-pager status tmp.mount
● tmp.mount - /tmp
   Loaded: loaded (/etc/fstab; generated; vendor preset: disabled)
   Active: active (mounted) since Wed 2017-03-29 21:43:41 CEST; 33s ago
    Where: /tmp
     What: tmpfs
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 236 ExecMount=/usr/bin/mount tmpfs /tmp -t tmpfs -o rw,nosuid,strictatime,nodev,size=80%,mode=1777 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/tmp.mount
-----------
xftroxgpx@z5 2017/03/29 21:44:15 -bash4.4.12 t:0 j:0 d:3 pp:1149 p:1173 ut37
!6732 4 0  4.10.0-gc470abd4fde4 #141 SMP PREEMPT Wed Mar 29 01:13:04 CEST 2017
/home/xftroxgpx
/home/xftroxgpx $ sudo systemd-analyze verify tmp.mount
[sudo] password for xftroxgpx: 
-----------
xftroxgpx@z5 2017/03/29 21:44:19 -bash4.4.12 t:0 j:0 d:3 pp:1149 p:1173 ut42
!6733 5 0  4.10.0-gc470abd4fde4 #141 SMP PREEMPT Wed Mar 29 01:13:04 CEST 2017
/home/xftroxgpx
/home/xftroxgpx $ systemctl --no-pager status tmp.mount
● tmp.mount - /tmp
   Loaded: loaded (/etc/fstab; generated; vendor preset: disabled)
   Active: active (mounted) since Wed 2017-03-29 21:43:41 CEST; 39s ago
    Where: /tmp
     What: tmpfs
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 236 ExecMount=/usr/bin/mount tmpfs /tmp -t tmpfs -o rw,nosuid,strictatime,nodev,size=80%,mode=1777 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/tmp.mount
Warning: tmp.mount changed on disk. Run 'systemctl daemon-reload' to reload units.
-----------
xftroxgpx@z5 2017/03/29 21:44:21 -bash4.4.12 t:0 j:0 d:3 pp:1149 p:1173 ut43
!6734 6 0  4.10.0-gc470abd4fde4 #141 SMP PREEMPT Wed Mar 29 01:13:04 CEST 2017
/home/xftroxgpx
/home/xftroxgpx $ systemctl --version
systemd 233
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid
-----------
xftroxgpx@z5 2017/03/29 21:44:32 -bash4.4.12 t:0 j:0 d:3 pp:1149 p:1173 ut54
!6735 7 0  4.10.0-gc470abd4fde4 #141 SMP PREEMPT Wed Mar 29 01:13:04 CEST 2017
/home/xftroxgpx
/home/xftroxgpx $ 
```

**Comment by ghost** [comment]
Looks like I should've included the contents of my /etc/fstab too, since tmp.mount is "generated":

```bash
# 
# /etc/fstab: static file system information
#
# <file system>	<dir>	<type>	<options>	<dump>	<pass>
# /dev/sda1
UUID=f836895d-2d40-4225-808b-d43fafdc7f5d	/         	btrfs     	rw,noatime,lazytime,compress-force=lzo,ssd,discard,space_cache,enospc_debug,autodefrag,commit=300 0 0
#XXX: ^ [ 1374.879921] BTRFS info (device sda1): unrecognized mount option 'lazytime'

#,subvolid=5,subvol=/	0 0
#18 march 2017, replaced noatime with strictatime
tmpfs                   /tmp            tmpfs           auto,rw,nosuid,strictatime,nodev,size=80%,mode=1777 0 0
tmpfs                   /var/tmp        tmpfs auto,rw,nosuid,strictatime,nodev,size=80%,mode=1777 0 0


```

Maybe now reproducing would work?

**Comment by poettering** [comment]
Ouch, it appears "systemd-analyze verify" run as root will destroy all generated unit files. That's quite a major bug.

**Comment by ghost** [comment]
But it's worth noting that the generated file(s) like `tmp.mount` aren't actually changed/touched on disk after the `systemd-analize verify`. I attempted to say this in OP. Perhaps there's a database(the thing that `systemctl daemon-reload` is supposed to update) that keeps track of `tmp.mount`&co. which is what is actually changed  - my guess.

**Comment by poettering** [comment]
@xftroxgpx they *are* changed: they are removed. i.e. in your case there should be a file /run/systemd/generator.*/tmp.mount, and after you run the verify it is gone.

**Comment by ghost** [comment]
Oh, I stand corrected.
I thought the generated files are those like `/usr/lib/systemd/system/tmp.mount`
Now I know it's `/run/systemd/generator/tmp.mount`

Thanks.
