### ISSUE TITLE
Could networkd partly break networking?

### ISSUE THREAD

**Issue by wsw70** [systemd/systemd#5612]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

### Used distribution

> Ubuntu 16.10 (yakkety)

### In case of bug report: Expected behaviour you didn't see

I have a working machine which networking is configured via `/etc/network/interfaces`. The networking works fine (I can ping and connect to services, see below for the non-working version with `networkd`).

I wanted to switch it to `systemd-networkd` but, once an interface is configured, "higher level" networking fails

### In case of bug report: Unexpected behaviour you saw

Network configuration:

```
# cat /etc/systemd/network/00-int.network
[Match]
Name=enp3s0

[Network]
Address=192.168.0.10/24
Gateway=192.168.0.254

# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 40:8d:5c:4b:aa:55 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.10/24 brd 192.168.0.255 scope global enp3s0
       valid_lft forever preferred_lft forever
    inet6 2a01:cb00:625:f700:428d:5cff:fe4b:aa55/64 scope global mngtmpaddr noprefixroute dynamic
       valid_lft 865sec preferred_lft 265sec
    inet6 fe80::428d:5cff:fe4b:aa55/64 scope link
       valid_lft forever preferred_lft forever

# ip route
default via 192.168.0.254 dev enp3s0  proto static
192.168.0.0/24 dev enp3s0  proto kernel  scope link  src 192.168.0.10


```
When issuing a `ping 127.0.0.1 -v`, I get

```
# ping 127.0.0.1 -v
socket permission denied, attempting raw socket...
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
```
(it hangs there,)

Surprisingly, running a `tcpdump` on the interface (when pinging the gateway) shows `echo` and `reply` packets (to and from the `192.168.0.254` gateway), but there is no output on the `ping` command (like above).

I did some more tests and `nmap` on the `192.168.0.254` interface shows the available open ports. When trying to do an `ssh` to port `22`, I see a `SYN` packet leaving, a `SYN-ACK` coming back and then nothing more (until a new `SYN` is sent).

This is horribly weird because it looks like that the packets flow freely (so this is not a firewall or routing issue for instance) but then something bad happens and they do not make it up the stack (?). 

Could this be a `networkd` issue? (again, the same commands work fine when the network is configured via the standard way, iptables are empty and all policies are `ACCEPT`)

EDIT: I just spent an hour trying to have networkd running fine in a brand new container. Packets were running fine while they were in the bridge and would not go further. Using `/etc/networking/interfaces` with the same configuration (same IP/mask & gateway + systemd-networkd disabled) immediately fixed the issue.

**Comment by poettering** [comment]
what i find strange is that you loopback device lacks an ipv6 address and that the qlen for it is set to "1"... are you sure you don't have some other service in place that configures networkd? Can you contact your downstream distro about this first, and let them escalate this to us if the verified this is actually a networkd problem?

I'll close this here now, as this really looks as if something is altering the network configuration after systemd set it up initially, and I'd prefer if this could be handled downtsream before this is escalated to us. I hope that makes sense.
