### ISSUE TITLE
IOSchedulingClass as a settable property for systemd-run

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5613]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Antergos Linux release 16.11 (ISO-Rolling)

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> I know it's possible to set IOWeight/IOReadIOPSMax/IOReadBandwidthMax but it's not quite the same thing. Of course, it would be more than nice if IOSchedulingPriority, CPUSchedulingPolicy or other options present in manual page of systemd.exec would become settable.

**Comment by keszybz** [comment]
I'm changing the milestone, as this is just an RFE.

**Comment by poettering** [comment]
Fix waiting in #6200
