### ISSUE TITLE
detect_container() login could be improved for containers running init

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5617]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> … systemd-233-2.fc27.x86_64

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> … fedora rawhide

### In case of bug report: Expected behaviour you didn't see

> …  systemd inside a container running init is set VIRTUALIZATION_NONE if there is no container env variable. People start to use runc to run containers without docker, so could easily NOT set container env variables .
```
        if (getpid() == 1) {
                /* If we are PID 1 we can just check our own environment variable, and that's authoritative. */

                e = getenv("container");
                if (isempty(e)) {
                        r = VIRTUALIZATION_NONE;
                        goto finish;
                }
```
### In case of bug report: Unexpected behaviour you saw

> … systemd inside a container running init is set VIRTUALIZATION_CONTAINER_OTHER even without container env variable. Even pid == 1, it seems better to still run this part of the code.

```
        /* Interestingly /proc/1/sched actually shows the host's PID for what we see as PID 1. Hence, if the PID shown
         * there is not 1, we know we are in a PID namespace. and hence a container. */
        r = read_one_line_file("/proc/1/sched", &m);
        if (r >= 0) {
                const char *t;

                t = strrchr(m, '(');
                if (!t)
                        return -EIO;

                if (!startswith(t, "(1,")) {
                        r = VIRTUALIZATION_CONTAINER_OTHER;
                        goto finish;
                }
```

### In case of bug report: Steps to reproduce the problem

> … 1. export rhel7 or fedora base-image to `pwd`/rootfs.
> ... 2. curl -O http://people.redhat.com/qcai/tmp/config.json
> ... 3. runc run -d root
> ... If you saw output from runc with "Mount failed for selinuxfs on /sys/fs/selinux:  No such file or directory", it means that systemd wrongly think it is running in a non-container and try to load policy.
> ... BTW, if you use a recent git master version of runc, you will need either to skip those 1.0.0-rc5 spec changes to avoid format change or update the config.json to the new format.

**Comment by poettering** [comment]
Well, there's no proper way to detect containers, if they don't let us know via `$container`, it's that simple. An app simply using some form of namespacing doesn't mean we are running inside a container manager, it just means that something is using a namespace for some operation. The only way how a container manager can report that it is fully doing container virtualization is by setting `$container`.

This is documented here:

https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/

My recommendation would be to simply fix `runc` to follow that interface. Without that there's little we can do. Sorry.
