### ISSUE TITLE
Logitech G500 Mouse DPI hwdb entry

### ISSUE THREAD

**Issue by Korvox** [systemd/systemd#562]
Hope this isn't already in hwdb for 222 or 223 already, with the bugtracker changeover its a PITA to read recent bug reports on hardware info like this.

Anywho:

mouse:usb:v046dpc068:name:Logitech G500:
 MOUSE_DPI=3600@505

Of note this mouse has three physical DPI settings buttons, and apparently can be tweaked using the Windows utility to poll at up to 5700 DPI. My mouse has never touched Windows so its running whatever the thing ships factory default. The above is at the highest setting.

The other two rates for the medium / low DPI settings are:

2600@503
1600@504

Theres some polling rate jitter going on, its probably meant to be around 500. I was testing it across a meterstick with a half dozen drags at each DPI setting.

Hope we are supposed to still throw udev hwdb entries on here and all that.

Also not quite sure how to assign a bug to Peter Hutterer on here, but I used your reddit post as a reference to make this bug report while I was playing with libinput 0.19.

**Comment by poettering** [comment]
@Korvox a proper patrch would be greatly appreciated.

@whot, please coment!

**Comment by whot** [comment]
yeah, looks like the poll rate is 500 and the rest is just measuring error. I'd use 500 for the entry. Look at the G500s entry in https://github.com/whot/systemd/blob/master/hwdb/70-mouse.hwdb#L223, that's a similar mouse. The 1600 entry should be marked as the default, it's the closest one to 1000dpi.

**Comment by poettering** [comment]
Closing, since #885 got merged.
