### ISSUE TITLE
machinectl wait <machine_name>

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5620]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

>systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

>Antergos Linux release 16.11 (ISO-Rolling)

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> It would be nice to run a program inside a container as soon as the container (started, in the background, using the command systemd-nspawn and -b option) enters the running state without creating unit files or checking for the state of the container every 2 seconds or simply waiting an arbitrary amount of time in order to successfully connect.
Also, I want to mention that I connect to the same machine/container many times not just once.
I imagined 
`
machinectl wait <machine_name>
`
Just a suggestion.

**Comment by poettering** [comment]
Well, "systemctl start systemd-nspawn@...service" in conjunction with 233`s new `--notify-ready=` switch permits you to do just that.

**Comment by 25pwn** [comment]
> Well, "systemctl start systemd-nspawn@...service" in conjunction with 233`s new `--notify-ready=` switch permits you to do just that.

I don't understand this, can you clarify?
