### ISSUE TITLE
downgrade priority of failures if =- is used

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5621]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

v233

Triggered by the recent PR #5528 I wonder if we couldn't improve the situation a little more generally.
We are/were using
```
ExecStartPre=-/bin/plymouth --wait quit
```
I.e. we were ignoring any errors from the started command. Yet we log an error in the journal which looks like this

![error](https://cloud.githubusercontent.com/assets/3609611/24168869/097dfcb8-0e7c-11e7-9938-887641863279.png)

I'm not surprised that users were concerned about such a log message, being in red and all.

I'm suggesting that we dial down the priority of such log messages to info or debug if ```=-``` is used. After all, it's a concious decision by the maintainer of the unit file to use ```=-``` as an error case is expected.

**Comment by keszybz** [comment]
Yeah, especially if the error is ENOENT. We could downgrade that to log_info and give a custom message that is less scary:
```
rescue.service: Skipped spawning /bin/plymouth: No such file or directory
```
