### ISSUE TITLE
Network device name changing due to other hardware

### ISSUE THREAD

**Issue by cyberdynesoftware** [systemd/systemd#563]
I have a Asus P5B Motherboard with an IDE controller, that may be disabled. I usually have it disabled. Only sometimes I enable it. I do not use the onboard network controller, but an PCI card.

Everytime when I enable the IDE controller in the BIOS, the name of the network device changes (in /sys/class/net) and thus breaking my network configuration.

For more information please have a look at this thread: https://bbs.archlinux.org/viewtopic.php?id=199647

**Comment by zdzichu** [comment]
Looks like disabling IDE changes PCI topology. Have you opened a bug with your motherboard maker?

**Comment by gregkh** [comment]
That's not a bug, PCI topology can change whenever it wants to, it does not have to be deterministic.

I suggest creating a rule based on a mac address if you want this to work properly all the time.

**Comment by kaysievers** [comment]
As Greg said, this is the expected behavior if the firmware works that way. The default network names are only predictable for a stable hardware configuration.
