### ISSUE TITLE
Link-local addresses preferred over global addresses when getaddrinfo is called with AF_UNSPEC

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#5630]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Debian

### Expected behaviour you didn't see

The order of the results of `getaddrinfo` when `hints.ai_family = AF_UNSPEC` should put globally-scoped addresses before link scope in the results:

```
$ getent ahosts $HOSTNAME
fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd STREAM 
fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd DGRAM  
fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd RAW    
2a00:1450:4009:80f::200e STREAM 
2a00:1450:4009:80f::200e DGRAM  
2a00:1450:4009:80f::200e RAW    
fd7a:d0a8:5ecb::1 STREAM 
fd7a:d0a8:5ecb::1 DGRAM  
fd7a:d0a8:5ecb::1 RAW    
fe80::a00:27ff:fe57:10b2 STREAM wintermute
fe80::a00:27ff:fe57:10b2 DGRAM  
fe80::a00:27ff:fe57:10b2 RAW    
fe80::1ce1:62ff:fe6f:9abd STREAM 
fe80::1ce1:62ff:fe6f:9abd DGRAM  
fe80::1ce1:62ff:fe6f:9abd RAW    
192.168.2.102   STREAM 
192.168.2.102   DGRAM  
192.168.2.102   RAW    
```

### Unexpected behaviour you saw

Background: I'm writing a set of scripts for testing the configuration of a mail server, and I want to test the behaviour of the server when accepting connections from particular address ranges. As part of the tests, I create a dummy interface with a globally-scoped IPv6 address and attempt to connect to the server using that address as the source address.

```
$ getent ahosts $HOSTNAME
fe80::a00:27ff:fe57:10b2 STREAM wintermute
fe80::a00:27ff:fe57:10b2 DGRAM  
fe80::a00:27ff:fe57:10b2 RAW    
fe80::1ce1:62ff:fe6f:9abd STREAM 
fe80::1ce1:62ff:fe6f:9abd DGRAM  
fe80::1ce1:62ff:fe6f:9abd RAW    
fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd STREAM 
fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd DGRAM  
fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd RAW    
2a00:1450:4009:80f::200e STREAM 
2a00:1450:4009:80f::200e DGRAM  
2a00:1450:4009:80f::200e RAW    
fd7a:d0a8:5ecb::1 STREAM 
fd7a:d0a8:5ecb::1 DGRAM  
fd7a:d0a8:5ecb::1 RAW    
192.168.2.102   STREAM 
192.168.2.102   DGRAM  
192.168.2.102   RAW    
```

This causes `nc -s 2a00:1450:4009:80f::200e $HOSTNAME 25` to time out as it tries to connect to each of the link-local addresses before it connects to the correct globally-scoped address.

I've also long-noticed that `ssh wintermute` results in a connection to a link-local address rather than the system's global address, which is a bit annoying as I'm forever having to confirm host keys as I ssh around my local network.

Interestingly, `ssh -6` and `nc -6` do what I expect, as evidenced by the output of `getent ahostsv6 wintermute`, where globally-scoped addresses are sorted above the link-local addresses.

### Steps to reproduce the problem

```
$ grep ^hosts: /etc/nsswitch.conf
hosts:          files resolve [!UNAVAIL=return]

$ ip -6 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::a00:27ff:fe57:10b2/64 scope link 
       valid_lft forever preferred_lft forever
3: robots: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1000
    inet6 fdce:7fbe:f572:9c6e:1ce1:62ff:fe6f:9abd/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 2591798sec preferred_lft 604598sec
    inet6 fe80::1ce1:62ff:fe6f:9abd/64 scope link 
       valid_lft forever preferred_lft forever
167: dumm0: <BROADCAST,NOARP> mtu 1500 state DOWN qlen 1000
    inet6 2a00:1450:4009:80f::200e/64 scope global 
       valid_lft forever preferred_lft forever
168: dumm1: <BROADCAST,NOARP> mtu 1500 state DOWN qlen 1000
    inet6 fd7a:d0a8:5ecb::1/128 scope global 
       valid_lft forever preferred_lft forever
```

**Comment by keszybz** [comment]
I can confirm that `getent ahosts $HOSTNAME` returns link-local addresses before global, and `ssh $HOSTNAME` prefers to use the link-local address. Nevertheless, if you use `systemd-resolve $HOSTNAME` or `build/test-nss resolve $HOSTNAME`, you'll see that both of them return addresses in the expected order, i.e. global before link-local.

I believe systemd has no influence over the order you see using glibc APIs. glibc implements RFC3484, which specifes (Sec 5, rule 8) that addresses with smaller scope should be preferred. Thus a link-local addresses are sorted before global, in `getaddrinfo` (see `rfc3484_sort` idem).

I actually had no idea about this, so I first patched `_nss_resolve_gethostbyname4_r` to return addresses in reverse order, but this has no effect whatsoever on `getent ahosts`.

If you want to change this, you'll need to take it up with the glibc folks, but I don't expect this to be easy. It might be possible to convince ssh folks to use non-local addresses to avoid noise in known_hosts, but I don't expect to be easy either ;)

I'll close this. If my analysis is wrong, please reopen.
