### ISSUE TITLE
Support for multiple sessions in the same VT

### ISSUE THREAD

**Issue by mikix** [systemd/systemd#5631]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Ubuntu (17.04 Zesty)

### Background

This is a cross between a bug report and an RFE, but I'm erring on the side of discussion about what should be done.  I assume you may not be up to date on Ubuntu land doings around unity8 and Mir, so I'll give some background.

In Ubuntu land, we've been experimenting with using Mir and our unity-system-compositor (USC) daemon on the desktop, for unity8 sessions.  (We previously have used such sessions with logind on the phone just fine.)

USC is managed by lightdm.  When a user session (or greeter) that declares itself as a Mir session needs to be started, lightdm spins up an instance of USC that owns the graphics hardware and manages drawing for the user session.

There is one USC per seat.  And all Mir sessions live "inside" USC, in the sense that they all live in USC's single VT.

### Unexpected behaviour you saw

When a second user tries to log into a unity8 session, logind refuses to create a session for the user.  (The error is "Already occupied by a session" in src/login/logind-dbus.c.)

This is because in logind, the assumption is that a seat that supports VTs will have one session per VT (barring a little bit of fudging around greeters handing VTs off to sessions and vice versa).

### Path forward

I looked at the code a little bit.  It seems this one-session-one-VT assumption is made in a few places.  I'd be happy to look into a potential patch to make it a bit more flexible in that regard.  But that seems like it would possibly be an involved patch, and I wanted to start the conversation early before I got too far.

### Technical thoughts

One potential wrinkle would be activating the proper session on the VT.  But LightDM listens to logind when sessions become Active and knows how to tell USC to switch to the appropriate session.  So logind wouldn't need to do grow special knowledge of USC, it can rely on LightDM doing the right thing in this scenario.

I'm guessing I'd "just" need to patch logind to allow multiple sessions on the same position/vtnr in certain cases (maybe type=mir, though I think it is also possible to pipe X11 sessions through USC) and in general skip a few checks when dealing with such sessions.  But I haven't deep dived into the code.

**Comment by dvdhrm** [comment]
Ugh, mhhh, I don't think this works. Why not ditch VTs and make USC always run on a seat without VTs? In otherwords: How about a boolean option that tells logind to ignore VTs and treat seat0 like any other seat (i.e., no VTs)?

The issue I see is that you clearly want USC to own exclusive access to the hardware and VTs. So why give access to VTs to the sessions at all? lightdm could just create them as sessions without VT access.

**Comment by robert-ancell** [comment]
@dvdhrm if we made seat0 not use VTs that would stop us being able to switch to text consoles or other windowing systems (e.g. Wayland sessions), right? So I think we have to keep VT support on seat0 for the immediate future.

Regarding sessions without VTs, do you mean creating a session without PAM_TTY set?

**Comment by dvdhrm** [comment]
@robert-ancell I see, you want to support both. Yeah, try creating a session without PAM_TTY set, so `loginctl` reports no `VTNr=` line.

**Comment by martinpitt** [comment]
Using a single VT for multiple sessions breaks the dynamic assignment of device permissions in udev (the `uaccess` tag), as this would then simultaneously grant access to all sessions, even those which are currently "inactive". I. e. the whole concept of "active foreground session" falls down in logind.

So this would need to go along with a reimplementation of that concept to use something more abstract than VTs.

**Comment by robert-ancell** [comment]
@martinpitt sure, the automatic detection doesn't work but since LightDM informs logind of the active session won't it continue to work? Isn't this the equivalent of running multiple sessions on seat1?

**Comment by dvdhrm** [comment]
The logind-code currently requires sessions to be assigned to a VT, if, and only if, their seat supports VTs (that is, if you have CONFIG_VT enabled, 'seat0' has all VTs assigned).

However, it should be possible to change the code to no longer require that. That is, even on VT-enabled seats, sessions should support running without a VT. In this case, we require some manager to use the logind-API to activate a session via DBus, though.

The obvious problem is, there will still be an active VT, and thus there might be a session on it. Hence, it is not clear what to do with it. My suggestion would be to mark it as "inactive", as long as there is another session *without* VT marked as active. As soon as that one is deactivated via DBus, or if it exits, we activate the "underlying" session again.

Please note, though, that currently this means the active session will get access to devices. That is, it gets direct input-device access, DRM, and everything marked with `uaccess`.

Would that serve your use-case?

**Comment by robert-ancell** [comment]
@dvdhrm that sounds pretty reasonable to me. We wouldn't use the session access to the devices with the current architecture, but I don't see it as being a problem and it would open the possibility of switching to using that in the future if the Mir team wanted to.

**Comment by robert-ancell** [comment]
Obviously given recent announcements this feature is probably not required..

**Comment by poettering** [comment]
OK, closing this then... Sorry to hear those recent announcements!
