### ISSUE TITLE
Watchdog pings not rate-limited

### ISSUE THREAD

**Issue by andersm** [systemd/systemd#5633]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

There is no limit to how often systemd pings the hardware watchdog, which is a problem with windowed-type watchdogs. Ideally this would be a configurable setting, but failing that this should at least be mentioned in the documentation.

**Comment by poettering** [comment]
what do you mean by "windowed-type" watchdogs?

Can you explain why it is a problem to ping to often? And if there's some hw limitation, wouldn't it make sense for the kernel driver to fix it?

**Comment by andersm** [comment]
A windowed watchdog is one where pinging too often has the same effect as not pinging often enough. However it turns out the kernel already handles this, but the driver was incorrectly configured to have a minimum heartbeat shorter than the tick rate, which effectively disables the rate limit.

Closing as invalid.
