### ISSUE TITLE
journald: many msgs incorrectly given facility=KERN when fwding to syslog

### ISSUE THREAD

**Issue by ndorf** [systemd/systemd#5640]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232
229
215

### Used distribution

Debian stretch (testing, 2017, systemd 232)
Ubuntu 17.04 (beta, 2017, systemd 232)
Ubuntu 16.04.2 (2016, systemd 229)
Debian jessie (2015, systemd 215)

Downstream reports:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837893 
https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1613751

### In case of bug report: Expected behaviour you didn't see

rsyslogd shouldn't receive messages with facility=KERN except from the kernel

### In case of bug report: Unexpected behaviour you saw

It does in fact receive tons of KERN messages from NetworkManager, gnome-session, pulseaudio, and a growing list of other userspace programs that log directly to the journal instead of syslog.

### In case of bug report: Steps to reproduce the problem

The same problem can be seen out of the box on fresh installs of all four distribution versions listed above; just fgrep -v kernel: /var/log/kern.log. (It's getting worse as more programs join the list.) All four default to ForwardToSyslog=yes for journald and kern.* -/var/log/kern.log for rsyslogd, which should be sufficient to reproduce it elsewhere.

Replacing rsyslogd with syslog-ng (also configured to log kern.* and nothing else to /var/log/kern.log) has no effect ; the problem persists. There is no issue if ForwardToSyslog is set to no, assuming we don't mind using journalctl to view those messages directly, or at least prefer it to having now ~50% of kern.log consist of spam.

When found in the output of journalctl -o verbose, some of the offending entries have no SYSLOG_FACILITY field, while others have it with values like DHCP4 or CORE. (There are no entries whatsoever where it's KERN.) They all have _TRANSPORT=journal.

The problem can't be reproduced with systemd-cat. That produces messages that also have no SYSLOG_FACILITY in the journal, but are correctly forwarded to the USER facility, not KERN. Unlike the offending messages, these have _TRANSPORT=stdout.

Below are the journalctl -o verbose versions of a few of the messages that are forwarded to KERN:

Sun 2017-03-26 01:41:39.700769 MDT [s=1b26ed1d3c0e4fd28638c73382d5a9ce;i=25619;b=243275ba701242d3990fa8288baac520;m=2bb95858d;t=54b9d5b720665;x=2c9fbc688a807a47]
    _UID=1000
    _AUDIT_LOGINUID=1000
    _MACHINE_ID=e6e2c451d3414980a328033266178438
    _HOSTNAME=stretch
    _TRANSPORT=journal
    _GID=1000
    _CAP_EFFECTIVE=0
    _AUDIT_SESSION=3
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_UNIT=user@1000.service
    _SYSTEMD_SLICE=user-1000.slice
    _SYSTEMD_USER_SLICE=-.slice
    PRIORITY=4
    GLIB_DOMAIN=Gtk
    CODE_FUNC=gtk_widget_size_allocate_with_baseline
    _COMM=gnome-terminal-
    _EXE=/usr/lib/gnome-terminal/gnome-terminal-server
    _CMDLINE=/usr/lib/gnome-terminal/gnome-terminal-server
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
    _SYSTEMD_USER_UNIT=gnome-terminal-server.service
    CODE_FILE=/build/gtk+3.0-y2_t3g/gtk+3.0-3.22.9/./gtk/gtkwidget.c
    CODE_LINE=5982
    _SYSTEMD_INVOCATION_ID=76474663cbc24734936f5945754378f3
    _BOOT_ID=243275ba701242d3990fa8288baac520
    MESSAGE=Allocating size to GtkScrollbar 0x5555fcbe0360 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
    _PID=1119
    _SOURCE_REALTIME_TIMESTAMP=1490514099700769

Sun 2017-03-26 01:43:44.823046 MDT [s=3c3ba5e7b6f9429f8cd09ea04eb50783;i=25ab9;b=0d784647ca5a4bf5b7bc4ddf235d2e1f;m=2c749a;t=54b9d62e73b36;x=8f87d80f859e5ad9]
    PRIORITY=5
    _MACHINE_ID=e6e2c451d3414980a328033266178438
    _HOSTNAME=stretch
    _TRANSPORT=journal
    _CAP_EFFECTIVE=0
    _GID=122
    _SYSTEMD_OWNER_UID=116
    _SYSTEMD_SLICE=user-116.slice
    _SYSTEMD_USER_SLICE=-.slice
    _UID=116
    _SYSTEMD_CGROUP=/user.slice/user-116.slice/session-c1.scope
    _SYSTEMD_SESSION=c1
    _SYSTEMD_UNIT=session-c1.scope
    CODE_FILE=gsm-manager.c
    CODE_LINE=1324
    CODE_FUNC=start_phase
    MESSAGE_ID=0ce153587afa4095832d233c17a88001
    MESSAGE=Entering running state
    SYSLOG_IDENTIFIER=gnome-session-binary
    _COMM=gnome-session-b
    _EXE=/usr/lib/gnome-session/gnome-session-binary
    _CMDLINE=/usr/lib/gnome-session/gnome-session-binary --autostart /usr/share/gdm/greeter/autostart
    _BOOT_ID=0d784647ca5a4bf5b7bc4ddf235d2e1f
    _SYSTEMD_INVOCATION_ID=6804af4f95634fd8a3c09048996e4ef6
    _PID=509
    _SOURCE_REALTIME_TIMESTAMP=1490514224823046

Sun 2017-03-26 01:43:48.913613 MDT [s=3c3ba5e7b6f9429f8cd09ea04eb50783;i=25ad5;b=0d784647ca5a4bf5b7bc4ddf235d2e1f;m=6adf60;t=54b9d6325a5fc;x=fa4a34e04177f00d]
    _MACHINE_ID=e6e2c451d3414980a328033266178438
    _HOSTNAME=stretch
    PRIORITY=6
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _TRANSPORT=journal
    SYSLOG_IDENTIFIER=NetworkManager
    SYSLOG_FACILITY=CORE
    NM_LOG_DOMAINS=CORE
    NM_LOG_LEVEL=INFO
    _COMM=NetworkManager
    _EXE=/usr/sbin/NetworkManager
    _CMDLINE=/usr/sbin/NetworkManager --no-daemon
    _CAP_EFFECTIVE=200534e2
    _SYSTEMD_CGROUP=/system.slice/NetworkManager.service
    _SYSTEMD_UNIT=NetworkManager.service
    CODE_FILE=src/nm-manager.c
    CODE_LINE=952
    _PID=451
    SYSLOG_PID=451
    _BOOT_ID=0d784647ca5a4bf5b7bc4ddf235d2e1f
    _SYSTEMD_INVOCATION_ID=da5c1ef2bffd4eee84cf4a9315dfcbc6
    MESSAGE=<info>  [1490514228.9135] manager: startup complete
    TIMESTAMP_MONOTONIC=7.003930
    TIMESTAMP_BOOTTIME=7.003930
    _SOURCE_REALTIME_TIMESTAMP=1490514228913613

**Comment by ndorf** [comment]
I forgot to mention that KERN is syslog facility zero:

#define	LOG_KERN	(0<<3)	/* kernel messages */

Also, as Matijs van Zuijlen [pointed out](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837893#15), there's [code](https://github.com/systemd/systemd/blob/master/src/journal/journald-syslog.c#L190) in systemd which appears to intend to prevent this from happening. That code looks correct; perhaps it's not being invoked in all cases?

**Comment by mbiebl** [comment]
Posted a PR at #5667

**Comment by poettering** [comment]
@mbiebl btw, please set the "has-pr" label for issues where you post a PR for, so that we can track them easily

**Comment by mbiebl** [comment]
@poettering will try to remember it
