### ISSUE TITLE
loopback interface ip address not available after network.target

### ISSUE THREAD

**Issue by nnnn20430** [systemd/systemd#5641]
systemd takes care of setting up loopback interface as part of it's main() function
but it doesn't ensure that ip address (127.0.0.1) has been assigned to lo interface when running services.

on a slow machine the kernel might not add the ip address to the lo interface in time for the services that might try to bind to it are run.

i run a znc service which starts after network.target, it has a configured port that binds on the 127.0.0.1 ip so that it's only available locally and it fails to start some times because the machine is slow (core (I) duo T2350 @ 1.86GHz), and sometimes still doesn't have the ip address assigned to lo after network.target has been reached.

my friend also has the problem when starting transmission-daemon on boot which tries to bind to 127.0.0.1 (he has a Intel Pentium Dual E2180 @ 2GHz, 1996MiB DDR2 RAM), we didn't know what was causing this services to fail half the time and were confused since 127.0.0.1 was available when system was already fully booted and we didn't know how it worked and how lo was setup in first place.

i recently tried to dig linux source and found that it tries to add the ip after inetdev_event event is triggered, so i think maybe on a slow machine the event is not triggered in time?

i think systemd should make sure that loopback is fully setup and has a valid ip assigned before network.target finishes since systemd already takes up the job of bringing up the loopback interface.

i originally submitted a bug report about this on bugzilla.kernel.org but they told me to go bug systemd maintainers: https://bugzilla.kernel.org/show_bug.cgi?id=195045

systemd version: 232
kernel version: 4.10.5
distro: arch

**Comment by poettering** [comment]
We synchronously wait until the kernel reports that the loopback call is finished, see:

https://github.com/systemd/systemd/blob/master/src/core/loopback-setup.c#L41

(sd_netlink_call() is synchronous).

I doubt there's anything we do wrong here... Are you sure you don#t have some other networking scheme in place that simple reconfigures the loopback device after we set it up?

**Comment by nnnn20430** [comment]
@poettering no, nothing, only thing that configures network is dhcpcd@enp2s0.service that just gets ip from router on enp2s0 interface i have no networkd no networkmanager no netctl nothing, current work around for loopback involves creating service:
[Unit]
...
Wants=network.target
Before=network.target
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/ip addr replace 127.0.0.1/8 dev lo
...

i have only tested it twice since adding it and it worked both times usually znc still had no 127.0.0.1 available ~90% of the time i booted
if you want i can test that that solves it with more reboots of my server

**Comment by nnnn20430** [comment]
@poettering 
Just to clarify i think loopback interface IS UP, but kernel has not yet assigned ip to it (127.0.0.1)
i think this /might/ be where it does it ???
https://github.com/torvalds/linux/blob/master/net/ipv4/devinet.c#L1435

**Comment by poettering** [comment]
Hmm, so you are saying that while we synchronously wait for the iface to be UP, and the kernel will implicitly add an IP address when the iface is UPed, it'll do so asynchronously and we don't wait for that to complete?

Yuck, what weird semantics...

I figure we essentialy need to revert @teg's f3fc48150bb443f5b4623a819ebc2b39971a4f66 commit

**Comment by keszybz** [comment]
Fixed by #6179.
