### ISSUE TITLE
RFE: add test for uppercaseness of letters in hwdb patterns

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#5642]
I've seen people get tripped by this a few times before.
https://bugs.freedesktop.org/show_bug.cgi?id=99664#c9

Should be easy enough to add to `parse_hwdb.py`.

**Comment by hadess** [comment]
Wouldn't it be better to accept both upper and lower case?

**Comment by keszybz** [comment]
Yeah, maybe. Could we ever have patterns where we want to distinguish the case?

**Comment by hadess** [comment]
I meant specifically for those sections that are case insensitive. At the very least it needs to match the value in the `udevadm` output, which isn't upper-case.

**Comment by keszybz** [comment]
RIght, but this would mean that `udevd` would have to be smart enough to understand which parts of patters are case-insensitive. Right now it just does a dumb comparison…

**Comment by hadess** [comment]
So, how come the hex numbers need to be in upper case when they aren't in the MODALIAS output of `udevadm`?!

**Comment by dtardon** [comment]
This has been implemented in https://github.com/systemd/systemd/commit/77547d5313ea916d2fb64ca5a8812734e9b50f92.

**Comment by DaanDeMeyer** [comment]
Let's close this then
