### ISSUE TITLE
link-config: ethtool operations are performed before the interface has been opened

### ISSUE THREAD

**Issue by nkss** [systemd/systemd#5645]
Doing ethtool operations before the interface has been opened
is not a defined behavior and will result in an error code in several
ethernet drivers.

Note that the ethtool behavior is completely driver specific,
so performing an ethtool operation on an interface that is DOWN
may succeed, but there is no guarantee that the results are consistent.

The best thing would be to perform all ethtool operations after
the interface has been opened.

Using e.g. the stmicro/stmmac ethernet driver leads to the following warnings:
[ WARNING ] systemd-udevd[236]: link_config: could not get ethtool features for eth0
[ WARNING ] systemd-udevd[236]: Could not set offload features of eth0: Device or resource busy

Simply because link-config tries to set ethtool operations (offloading) before
the interface is opened.

A quick grep for check_if_running shows that the problem will be seen with
(at least) the following drivers:
adaptec/starfire.c
dlink/sundance.c
packetengines/hamachi.c
smsc/smc91c92_cs.c
stmicro/stmmac/stmmac_ethtool.c

**Comment by poettering** [comment]
This smeels like a driver problem to me. ethtool configuration is sometimes necessary to properly up a device. If a driver can't handle that, it should really be fixed I am sure.

Sorry, but this really looks like a kernel driver issue to me. Please ping the kernel folks.

**Comment by nkss** [comment]
That was my initial though as well, but Florian Fainelli, maintainer of the ethernet PHY library as well as several ethernet drivers, tends to disagree:

http://marc.info/?l=linux-kernel&m=149004765114430
http://marc.info/?l=linux-kernel&m=149011400201171
