### ISSUE TITLE
logind.conf(5) slighly misleading wrt to lid switch inhibitor locks

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5647]
The logind.conf man page says
```
       PowerKeyIgnoreInhibited=, SuspendKeyIgnoreInhibited=, HibernateKeyIgnoreInhibited=, LidSwitchIgnoreInhibited=
           Controls whether actions that systemd-logind takes when the power and sleep keys and the lid switch are triggered
           are subject to high-level inhibitor locks ("shutdown", "sleep", "idle"). Low level inhibitor locks
           ("handle-*-key"), are always honored, irrespective of this setting.
```

The last sentence makes it sound as if only ```handle-*-key``` can be blocked. The inhibitor lock for lid switches is called ```handle-lid-switch```, so reading the documented one could think that it's not possible to block ```handle-lid-switch```, while one actually can.
Maybe it should read ("```handle-*-key``` or ```handle-lid-switch```") or simply ("```handle-*```")

**Comment by poettering** [comment]
Patch would be very welcome of course...
