### ISSUE TITLE
[RFE] Drop kdbus-related tests

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#5651]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### Description

See Michael Biebl's comments in #5533.

**Comment by AsciiWolf** [comment]
By the way, it looks like there is still some leftover kdbus-related code in _sd-bus_. It would be nice to drop that code as well.

**Comment by poettering** [comment]
These tests should all be gone these days. Closing
