### ISSUE TITLE
va_list version of sd_bus_call_method?

### ISSUE THREAD

**Issue by FedeDP** [systemd/systemd#5654]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Archlinux

I noticed that in libsystemd, "sd_bus_call_method" (https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-convenience.c#L97) does not use a proper function that accepts a va_list as a parameter.
My idea is that it should indeed; for some reasons i have to pass a va_list as last parameter (instead of a variadic arg); it would be great if a new interface was lying there; moreover, it seems "bus_message_append_ap" is not public (am i wrong?) so i am completely stuck here.
What i am trying to achieve is this: http://dpaste.com/0J4H48W.
Ie: having a nice small interface that does all the error checking and response parsing instead of writing the same code 10 times.

Any idea?

**Comment by FedeDP** [comment]
Only idea i came up with is to make a small loop on va_list and for each va_arg, call "sd_bus_message_append_basic". I cannot test right now but i think that should work.
It would be great if a nicer interface would be provided though.

**Comment by poettering** [comment]
Well, I am not sure we really should export that, as sd_bus_call_method() is redundant, and pure convenience. If you need a different flavour of it, you better call the underlying functions directly. That said, we currently don't expose sd_bus_message_append_ap(), but we probably should, so that you can do what youwant to do.

**Comment by FedeDP** [comment]
Thanks, that would be great! :)
Am i correct in my second comment? That should work too, i guess (even if it is quite inconvenient and ugly).

**Comment by poettering** [comment]
sure, sd_bus_message_append() itself isn't anything else than a loop around sd_bus_message_append_basic() anyway, so you can hack that loop up yourself. But it's not entirely trivial of course..

**Comment by FedeDP** [comment]
Ok...it is not much nice, but it works pretty good: http://dpaste.com/0BK0W6D.
I will wait for systemd 234 for this nice api improvement!

**Comment by poettering** [comment]
@FedeDP uh, oh, if you want this to be fixed in 234, then the best way is to prep a PR that exports sd_bus_message_append_ap(). We have a lot to work on, and we cannot fulfill all wishes each time, due to our limited resources. Best way to get what you ask for is to contribute a patch and push it through the PR process...

**Comment by FedeDP** [comment]
Oh, i see :)
Sure, i'll do this as soon as i got some spare time!

**Comment by FedeDP** [comment]
Should I only put a "_public_" like this:
_public_ int bus_message_append_ap
and move bus_message_append_ap function declaration from bus-message.h to sd-bus.h?
Or should i rename it too, to match sd_bus naming? 
I see it is not used much so a small refactor would be quite simple.

**Comment by poettering** [comment]
@FedeDP all functions export to sd-bus clients should be prefixed with the "sd_" namespace prefix, hence yes: do rename it.
