### ISSUE TITLE
zombie process with PID 1 as parent after 'systemctl restart'

### ISSUE THREAD

**Issue by xogium** [systemd/systemd#5657]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> Systemd 232…

### Used distribution

> ArchLinux…

### In case of bug report: Expected behaviour you didn't see

> Systemd should have restarted the unit without any kind of issue…

### In case of bug report: Unexpected behaviour you saw

> Systemd tried to restart the unit, which miserably failed, causing an infinite hang (until ctrl+c was pressed), and resulted in a zombie process with PID 1 as its parent…

### In case of bug report: Steps to reproduce the problem

> 1. I noticed the screen reader (userspace speech output) Espeakup was not speaking, so went > in GUI to restart it, with systemctl restart espeakup.
> 2. After 5 minutes waiting for it to restart, I pressed ctrl+c and checked top and systemctl status.
> 3. Top was showing the PID of the screen reader as zombie, and systemctl status reported it was unable to kill the process…

Here are the output of pstree, top and systemctl cat:

pstree -sA $(pgrep espeakup)

> systemd---espeakup---{espeakup}

Output of top:

> 474 root      20   0    0,0m   0,0m   0,0  0,0   0:04.23 Z espeakup

Output of systemctl cat espeakup:

> \# /etc/systemd/system/espeakup.service
> [Unit]
> Description=Software speech output system wide settings
> \# espeakup needs to start after the audio devices appear, hopefully this should go away in the future
> Wants=systemd-udev-settle.service
> After=systemd-udev-settle.service sound.target
>
> [Service]
> Type=forking
> EnvironmentFile=/etc/conf.d/espeakup
> PIDFile=/run/espeakup.pid
> ExecStart=/usr/bin/espeakup -V fr+michel
> ExecReload=/bin/kill -HUP $MAINPID
> Restart=always
>
> [Install]
> WantedBy=sound.target

* Notes:
* This is the default unit file that comes with the espeakup package on ArchLinux, only modified to start with the fr+michel variant of espeak voice.

**Comment by poettering** [comment]
Can you please provide a logs of this incident, best with debug mode on? For that, please use "systemd-analyze set-log-level debug" right before reproducing the issue, then provide the logs for it, so that we can see what precisely happens.

**Comment by xogium** [comment]
Hello there,
well, I **hate** this kind of issue, because I suspect I was unlucky in triggering some kind of race condition or something of the kind, because after a reboot, now that the zombie is gone, I can't manage it again. If I manage it, I'll be sure to try exactly what you suggested. Not sure if this is worth mentioning but I tried to use 'sudo kill -17 1' without any result to get rid of the zombie.

**Comment by poettering** [comment]
@xogium so, my educated guess is that the zombie wasn't actually a real zombie, but a process that hit a segfault, and some coredump handler might have been processing it still (systemd-coredump or abrt and thelike). a zombie of that type cannot be reaped yet until the coredump is fully processed...

Anyway, closing this for now, as there's little we can do for now. if you manage to reproduce this issue, please reopen and provide the requested data. Thanks!
