### ISSUE TITLE
sdbus API: problem in sd_bus_message_read handling boolean value

### ISSUE THREAD

**Issue by Andy1978** [systemd/systemd#5658]
- [X ] Bug report
> systemd 232
> Debian GNU/Linux 9.0 (stretch)
> SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux

### In case of bug report: Expected behaviour you didn't see

I expect "sd_bus_message_read(m, "dbb", &myvalue, &b0, &b1);" to read a double and two bits but the first boolean is always false.

### In case of bug report: Steps to reproduce the problem

> git clone https://github.com/Andy1978/sdbus_bool.git
> cd sdbus_bool/
> make && ./receive

in separate terminal: 
> ./emit"

This outputs:
> connected, now waiting...
> myvalue=2.718000 b0=0 b1=1
> receive: receive.c:31: sig_foo: Assertion `b0 == 1' failed.

**So the first boolean value returned is false although it was true when emitted.**

dbus-monitor shows the signal as expected:
>signal time=1490789848.765380 sender=:1.62 -> destination=(null destination) serial=12 path=/de/alluris/test; interface=de.alluris.test; member=foo
>   double 2.718
>   boolean true
>   boolean true

**Comment by poettering** [comment]
for "b" you need to specify a ptr variable of type "int" in sd_message_read(). You may not use "char", and may not use "bool" either, as they have different sizes in memory and thus result in memory corruption. See the table in sd_bus_message_append(3) for details. Closing.
