### ISSUE TITLE
systemd user service manager dbus interface - hangs

### ISSUE THREAD

**Issue by daym** [systemd/systemd#5660]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

 systemd                     229-4ubuntu16      amd64              system and service manager

### Used distribution

Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

`busctl --user --address=unix:path=$XDG_RUNTIME_DIR/systemd/private` should not hang.

### In case of bug report: Unexpected behaviour you saw

`busctl --user --address=unix:path=$XDG_RUNTIME_DIR/systemd/private` hangs.

### In case of bug report: Steps to reproduce the problem

1. Log in using a normal user account
2. Call `busctl --user --address=unix:path=$XDG_RUNTIME_DIR/systemd/private --list`.
3. It hangs

What we are trying to do is to manage user services (in a GUI). We try to use dbus for this - which works fine for system services for us. strace of systemctl gave us the name of the file above.

Should managing user services work using dbus? If not, how to manage user services?

**Comment by poettering** [comment]
Please update to a current version of systemd (233), then, run "busctl" within gdb, and provide a backtrace of it where it hangs. (for that simply hit C-c when it hangs while running it in gdb, then type "bt full" and paste the output that generates).

**Comment by daym** [comment]
This is on a production system and I don't think it's prudent to do that - if it's even possible.

But if you know instructions for some bleeding edge systemd VM (for example from existing documentation?)  we could try that.

Do you think we should report it to Canonical instead?

Does it work for you?

**Comment by martinpitt** [comment]
@daym: You can use a Debian unstable VM and upgrade to systemd 233 from experimental. Or use a Ubuntu 16.10 or zesty and install the packages from https://launchpad.net/~pitti/+archive/ubuntu/systemd  (but I need to update that, running now).

**Comment by daym** [comment]
We used ubuntu-16.10-server-amd64.iso (in qemu) and added the packages from https://launchpad.net/~pitti/+archive/ubuntu/systemd . Invoking `busctl --user --address=unix:path=$XDG_RUNTIME_DIR/systemd/private --list` still hangs as before - so it's reproducible. Screenshot of gdb backtrace is attached.

![screenshot from 2017-03-31 11-34-27](https://cloud.githubusercontent.com/assets/7755349/24545289/f5a35ec6-1606-11e7-8c76-134f82bf4f62.png)

We are trying to manage systemd user services (in order to receive a notice when a service is started/stopped etc) - if there's a better way to do that, we can use that instead.

**Comment by poettering** [comment]
please always install debug symbols when generated backtraces. 

Anyway, can you get a backtrace of the user's dbus-daemon at the same time, please?

**Comment by daym** [comment]
There is no debug symbol package at https://launchpad.net/%7Epitti/+archive/ubuntu/systemd - so we can't install it.

We'll get the backtrace of the user's dbus-daemon on Monday.

Thanks.

**Comment by poettering** [comment]
@martinpitt hmm, any idea about debug symbols for that?

**Comment by martinpitt** [comment]
@daym: Ah, good catch! The PPA didn't have debug symbols enabled. I enabled that now, and uploaded another daily snapshot from today, it's built now.

**Comment by daym** [comment]
We tried the new package 233+upstream20 - however, the gdb backtrace still shows very little debugging information.

We ran strace and that gave us:
```
$ strace -s 32000 busctl --user --address=unix:path=$XDG_RUNTIME_DIR/systemd/private --list
connect(3, {sa_family=AF_LOCAL, sun_path="/run/user/1000/systemd/private"}, 32) = 0
getsockopt(3, SOL_SOCKET, SO_PEERCRED, {pid=1647, uid=1000, gid=1000}, [12]) = 0
fstat(3, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
getsockopt(3, SOL_SOCKET, SO_ACCEPTCONN, [0], [4]) = 0
getsockname(3, {sa_family=AF_LOCAL, NULL}, [2]) = 0
geteuid()                               = 1000
sendmsg(3, {msg_name(0)=NULL, msg_iov(3)=[{"\0AUTH EXTERNAL ", 15}, {..., 8}, {"\r\nNEGOTIATE_UNIX_FD\r\nBEGIN\r\n", 28}], msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 51
gettid()                                = 7562
getrandom("\200\\r\224q\240|\337Z\24\210\274\33\342\210\217", 16, GRND_NONBLOCK) = 16
recvmsg(3, 0x7ffd5978af50, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=3, events=POLLIN}], 1, {24, 999759000}, NULL, 8) = 1 ([{fd=3, revents=POLLIN}], left {24, 998745401})
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"OK ea0d1d50cddd4130ba9eb8de134eda89\r\nAGREE_UNIX_FD\r\n", 256}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 52
sendmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"l\1\0\1\0\0\0\0\1\0\0\0m\0\0\0\1\1o\0\25\0\0\0/org/freedesktop/DBus\0\0\0\3\1s\0\5\0\0\0Hello\0\0\0\2\1s\0\24\0\0\0org.freedesktop.DBus\0\0\0\0\6\1s\0\24\0\0\0org.freedesktop.DBus\0\0\0\0", 128}], msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 128
recvmsg(3, 0x7ffd5978aea0, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=3, events=POLLIN}], 1, {24, 998755000}, NULL, 8) = 1 ([{fd=3, revents=POLLIN}], left {24, 998753982})
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"l\3\1\1,\0\0\0\1\0\0\0G\0\0\0\5\1u\0\1\0\0\0", 24}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\4\1s\0(\0\0\0org.freedesktop.DBus.Error.UnknownObject\0\0\0\0\0\0\0\0\10\1g\0\1s\0\0'\0\0\0Unknown object '/org/freedesktop/DBus'.\0", 108}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 108

```

In any case, we found out how to connect to the user bus. One has to install dbus-user-session and then a file /run/user/1000/bus shows up. When connecting to this socket using DbusConnection, we can manage systemd user services just like we would have managed systemd system services. So our use case works now.

So if the private socket is not intended to work using busctl we consider this issue closed.
