### ISSUE TITLE
RFE: newtorkd: Match based on ID_SERIAL udev attribute

### ISSUE THREAD

**Issue by jharvell** [systemd/systemd#5665]
### Submission type

  - [ ] Bug report
  - [ x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232-r1

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo

I want to be able to use a key in the [Match] Section of a .link file in /etc/systemd/network that matches the udev attribute ID_SERIAL and/or ID_SERIAL_SHORT.

My use case is I want to give a predictable name to a USB Ethernet network device.  In this case, it is a Samsung Galaxy S7 phone connected via USB.  When I look at the keys available in the [Match] Section Options for network.link, None of the options can actually identify the device itself.  The device shows up with a MAC address of all zeros, and the value of the ID_PATH attribute depends on which USB port I plug into.  I am currently using the following....

```
[Match]
Driver=rndis_host

[Link]
Description="RNDIS Ethernet Device"
MacAddressPolicy="random"
Name="gs7"
```

But what I really want to use is something that has the model and serial number so that I can have a network interface name associated with the specific device.  Here is an excerpt from

```
udevadm info --export-db
```

```
P: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/net/_gs7_
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/net/_gs7_
E: ID_BUS=usb
E: ID_MM_CANDIDATE=1
E: ID_MODEL=SAMSUNG_Android
E: ID_MODEL_ENC=SAMSUNG_Android
E: ID_MODEL_FROM_DATABASE=GT-I9070 (network tethering, USB debugging enabled)
E: ID_MODEL_ID=6864
E: ID_NET_DRIVER=rndis_host
E: ID_NET_LINK_FILE=/etc/systemd/network/20-galaxy_s7.link
E: ID_NET_NAME="gs7"
E: ID_NET_NAME_PATH=enp0s26u1u3
E: ID_PATH=pci-0000:00:1a.0-usb-0:1.3:1.0
E: ID_PATH_TAG=pci-0000_00_1a_0-usb-0_1_3_1_0
E: ID_REVISION=0400
E: ID_SERIAL=SAMSUNG_SAMSUNG_Android_126c5003
E: ID_SERIAL_SHORT=126c5003
E: ID_TYPE=generic
E: ID_USB_DRIVER=rndis_host
E: ID_USB_INTERFACES=:e00103:0a0000:ff4201:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=SAMSUNG
E: ID_VENDOR_ENC=SAMSUNG
E: ID_VENDOR_FROM_DATABASE=Samsung Electronics Co., Ltd
E: ID_VENDOR_ID=04e8
E: IFINDEX=11
E: INTERFACE=_gs7_
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/_gs7_ /sys/subsystem/net/devices/_gs7_
E: TAGS=:systemd:
E: USEC_INITIALIZED=50985903220
```

Here is the resulting netdev with the .link file I have now:

```
$ ip link ls dev _gs7_
11: _gs7_: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
```

and systemd journal output:

```
mars 29 20:48:08 akita systemd[1]: Started Network Service.
mars 29 20:48:08 akita systemd-networkd[25779]: work: Configured
mars 29 20:48:08 akita systemd-networkd[25779]: netboot: Configured
mars 29 20:48:08 akita systemd-networkd[25779]: eno1: Configured
mars 29 20:48:10 akita systemd-networkd[25779]: inet: Configured
mars 29 20:53:01 akita systemd-networkd[25779]: eth0: Renamed to _gs7_
```

By the way, shouldn't the netdev name be gs7, not _gs7_?  an shouldn't it have gotten a random, locally administered, unicast MAC?

**Comment by poettering** [comment]
yeah, a `[Match]` directive that would permit checking arbitrary udev props would probably make sense.
