### ISSUE TITLE
Please add support for DNS-over-TLS to systemd-resolved

### ISSUE THREAD

**Issue by gwire** [systemd/systemd#5671]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### Details

Please add support to systemd-resolved for talking to servers that support [RFC 7858](https://tools.ietf.org/html/rfc7858) DNS-over-TLS on port 853.

Publicly available :853 test servers are listed on the [sinodun wiki](https://portal.sinodun.com/wiki/display/TDNS/DNS-over-TLS+test+servers).

**Comment by poettering** [comment]
hmm, that appears quite an exotic protocol so far, that is not commonly in use. Does any other mainstream OS support this?

**Comment by gwire** [comment]
RFC 7858 was published in May 2016, so I wouldn't expect it to be supported in production OS releases yet. There are some [existing clients](https://portal.sinodun.com/wiki/display/TDNS/DNS-over-TLS+clients) listed, as well as further timeline details at dnsprivacy.org.

**Comment by poettering** [comment]
I am not convinced we should support any random RFC posted, but wait until it found some level of deployment. I am not sure this RFC is there quite yet.

**Comment by duckdalbe** [comment]
Google is building this into Android, apparently:
http://www.theregister.co.uk/2017/10/26/android_testing_dns_over_tls/
https://www.xda-developers.com/android-dns-over-tls-website-privacy/

**Comment by ott** [comment]
[RFC 8094](https://tools.ietf.org/html/rfc8094) standardized DNS over DTLS. The IETF DNS Over HTTPS working groupis also [working on standardizing DNS queries over HTTPS](https://datatracker.ietf.org/doc/draft-ietf-doh-dns-over-https/). Geoff Houston of APNIC [summarized](https://blog.apnic.net/2017/11/28/hiding-the-dns/) the current efforts to introduce some confidentiality and integrity to DNS queries.

**Comment by poettering** [comment]
yeah, we really should add dns-over-tls support now, given that quad9 support that now, and the RFC is standard.

@ott dns-over-dtls is not quite yet "standard" yet. afaics RFC 8094 is experimental still

**Comment by ott** [comment]
It seems the Android implementation does not use DTLS at the moment. So perhaps we should make the decision dependent on what Android does.

I have been told that Quad9 uses Unbound and PowerDNS. PowerDNS does not support DNS over TLS at the moment it seems.

**Comment by ott** [comment]
If we implement RFC 7858, we should also implement RFC 7830. Moreover, we should improve TCP connection handling as outlined in #7617.

**Comment by ancarda** [comment]
The newly announced CloudFlare DNS resolver, 1.1.1.1, supports DNS-over-TLS, so that's another implementation in the wild to test using.

https://blog.cloudflare.com/announcing-1111/

**Comment by q2dg** [comment]
Do you know about issue explained here: https://www.internetsociety.org/blog/2018/12/dns-privacy-in-linux-systemd/ ?

**Comment by ctubbsii** [comment]
Does resolved.conf support specifying the port? Or does it *have* to be 853?
