### ISSUE TITLE
[RFE] Logging when KillUserProcesses, RemoveIPC is activated

### ISSUE THREAD

**Issue by konstruktoid** [systemd/systemd#5672]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

```
$ cat /etc/systemd/system/logind.conf 
[Login]
KillUserProcesses=1
KillExcludeUsers=root
IdleAction=lock
IdleActionSec=15min
RemoveIPC=yes
```

When `KillUserProcesses` and/or `RemoveIPC` is activated, it doesn't seem to be logged with `systemd-journald`. 
In order to simplify debugging I believe this would be a helpful `systemd` enhancement.

**Comment by poettering** [comment]
hmm? systemd as a quite a number of config options, I am not convinced it would be a good idea to log every single one of them... And I am not convinced logging these specific two would be a good choice either.

Note that "loginctl show-session" (without further args) shows you the effective value of these two values, too.

Sorry, but I am not convinced this would be a good addition. Closing. I hope that makes sense.

**Comment by konstruktoid** [comment]
Present in 231?
Adding for reference.

https://github.com/systemd/systemd/blob/master/NEWS#L831-L836 :

```
        * systemd will now log about all service processes it kills forcibly
          (using SIGKILL) because they remained after the clean shutdown phase
          of the service completed. This should help identifying services that
          shut down uncleanly. Moreover if KillUserProcesses= is enabled in
          systemd-logind's configuration a similar log message is generated for
          processes killed at the end of each session due to this setting.
```
