### ISSUE TITLE
Manipulating udev hwdb for changing USB keyboard keycode didn't work.

### ISSUE THREAD

**Issue by alaneuler** [systemd/systemd#5677]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch Linux

### Details

I have a Dell keyboard as its details follows:

```
Bus 003 Device 003: ID 413c:2105 Dell Computer Corp. Model L100 Keyboard
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x413c Dell Computer Corp.
  idProduct          0x2105 Model L100 Keyboard
  bcdDevice            3.52
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               70mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              5 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      65
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              24
```

According to /lib/udev/hwdb.d/60-keyboard.hwdb's instruction, I create a file named 70-keyboard.hwdb in /etc/udev/hwdb.d/ with content:

```
evdev:input:b0003v413Cp2105*
  KEYBOARD_KEY_3a=leftctrl
```

I want to map the Caps Lock key to Control key, but this didn't work after executed:

```
udevadm hwdb --update
udevadm trigger
udevadm control --reload
```

I've tested the scancode of my Caps Lock key in console (not under X), it is the 3a when pressed.

A reboot didn't help either. My tutorial comes from [Arch Wiki](https://wiki.archlinux.org/index.php/Map_scancodes_to_keycodes) and 60-keyboard.hwdb

BTW, is there a way to look up the info or just how udev hwdb processes when updating hwdb? I've tried that even if there is syntax error in 60-keyboard.hwdb, still nothing output about the error when updating. I think it is better to have output (maybe I can debug all by myself)

Thank you!

**Comment by amosbird** [comment]
I just ran into this kind of issue. see #5684

**Comment by alaneuler** [comment]
@amosbird could you please tell how to get the keyboard connection information? I think it's may be useful to me, thank you!

**Comment by amosbird** [comment]
@alaneuler  run `udevadm monitor --environment`  and do the plug in operation.

**Comment by jbmorgado** [comment]
I'm having the exact same issue. Tried several methods of addressing the keyboard in the hwdb file (using `keyboard:...`, `evdev:atkbd:dmi:*`, `evdev:input:dmi:(keyboard id)`, etc) but nothing is working.

**Comment by poettering** [comment]
Let's close this here. It's a 3y old issue and actually more of a support question than a bug report. And support questions should be directed to the ML instead. Closing hence.

if this is still an issue, please contact the mailing list!
