### ISSUE TITLE
Lenovo ThinkPad t460p Trackpoint speed unusable slow

### ISSUE THREAD

**Issue by fd0** [systemd/systemd#5685]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

Trackpoint speed is fast and usable. Index finger does not hurt.

### In case of bug report: Unexpected behaviour you saw

Trackpoint speed is very slow (since the recent switch from evdev to libinput).

Index finger hurts.

### In case of bug report: Steps to reproduce the problem

Use a Thinkpad t460p trackpoint with libinput.

This is a similar issue as reported in #4384. I've created a new hwdb file with the following content:
```
$ cat /etc/udev/hwdb.d/71-pointingstick-local.hwdb
# Lenovo Thinkpad t460p
evdev:name:TPPS/2 IBM TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvrThinkPadT460p:*
  POINTINGSTICK_SENSITIVITY=200
  POINTINGSTICK_CONST_ACCEL=3.0
```

After a hwdb update and a udavdm trigger the new values are present:
```
$ udevadm hwdb --test "evdev:name:TPPS/2 IBM TrackPoint:$(cat /sys/class/dmi/id/modalias)"
POINTINGSTICK_CONST_ACCEL=3.0
POINTINGSTICK_SENSITIVITY=200
```

Unfortunately even this does not help. Please let me know if this is not the right place for such a bug report...

Thanks!

**Comment by fd0** [comment]
Setting the `speed` file in sysfs for the device to 190 (instead of the default 97) makes it barely usable, but my finger still hurts after using the trackpoint for a bit.

@whot I also tried configuring the DPI of the trackpoint (just experimentation, mouse-dpi-tool requires moving the device a physical distance, which is hard to do for a trackpoint), but it feels to me that the `MOUSE_DPI` setting is ignored for the trackpoint. Is that possible?

**Comment by poettering** [comment]
@whot can you comment?

**Comment by whot** [comment]
@fd0 yes, the DPI is ignored for trackpoint, we have POINTINGSTICK_CONST_ACCEL instead which is read by libinput. Note that this is likely to change, see https://bugs.freedesktop.org/show_bug.cgi?id=100982 and I'm currently working on https://bugs.freedesktop.org/show_bug.cgi?id=91369.

So for now, the best things is to leave everything at the defaults (except sensitivity which is already set) and let libinput take care of it in the next version (I hope :). Sorry, that's all I can promise for now.

**Comment by fd0** [comment]
Thanks for the information. Please let me know if there's anything I can do to help!

**Comment by fd0** [comment]
I'm sorry to bother you again, but is there anything I can do to speed this up? Or is there an unreleased version or patch that I can try? The pointer is unfortunately not usable for me right now :cry:

**Comment by webmeister** [comment]
I'm not sure what changed, but to my surprise this isn't an issue anymore on my fully updated Arch system. The machine usually sits on its docking station, so it has been some weeks since I last used the trackpoint. Coincidentally, I had just replaced the trackpoint cap, since the old one was completely worn off because of this problem, but I doubt that this is what fixed it :D

**Comment by whot** [comment]
don't know what libinput version arch ships but libinput master has the patches to handle trackpoint acceleration now.

**Comment by fd0** [comment]
Hey, thanks for the hint, I've installed `libinput-git` on Arch. We'll see how that goes :) Thanks for your work!

**Comment by poettering** [comment]
Does this mean we can close this bug now?

**Comment by fd0** [comment]
It's definitely better, I'm still getting used to it. No hurting fingers any more, so I'll close this for now. Thanks @whot!
