### ISSUE TITLE
sd_bus_vtable: offset should be ptrdiff_t not size_t

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#569]
`struct sd_bus_vtable`'s `.x.property.offset` is currently a `size_t` rather than a `ptrdiff_t`.

**Comment by dvdhrm** [comment]
I think `size_t` is appropriate. We're dealing with _positive_ offsets here, and `size_t` is guaranteed to be large enough to hold any object sizes possible on this system.

Why do you think it should be `ptrdiff_t`?

**Comment by daurnimator** [comment]
> Why do you think it should be ptrdiff_t?

The way it's used is as a difference between pointers.
IIRC some arcane bit of C says that you must use `ptrdiff_t` in that use case.

But it really doesn't matter much.

btw, why only positive anyway?
You can pass an arbitary `void*` as the userdata; what if I stored the property data before it?

**Comment by dvdhrm** [comment]
> But it really doesn't matter much.

I agree ;)

> btw, why only positive anyway?
> You can pass an arbitary void\* as the userdata; what if I stored the property data before it?

You're free to make the pointer-arithmetic overflow. But I'd recommend storing the real object-root instead of a pointer somewhere into the middle, if you intend to access other offsets.
