### ISSUE TITLE
DHCP client must ignore default route option if classless static route option is set

### ISSUE THREAD

**Issue by ignatk** [systemd/systemd#5695]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

231 (but according to the source should apply to `master`)

### Used distribution

Debian Jessie (with backports)

### In case of bug report: Expected behaviour you didn't see

According to RFC 3442:
>    If the DHCP server returns both a Classless Static Routes option and
>    a Router option, the DHCP client MUST ignore the Router option.

### In case of bug report: Unexpected behaviour you saw

When DHCP server is configured to send both `SD_DHCP_OPTION_ROUTER` and `SD_DHCP_OPTION_CLASSLESS_STATIC_ROUTE`, DHCP client in `systemd-networkd` sets them both as routes

### In case of bug report: Steps to reproduce the problem

Configure DHCP server as following (example for `dnsmasq`):
```
dhcp-option=3,<default gateway>
dhcp-option=121,<some cidr>,<gateway>
```

**Comment by ssahani** [comment]
Fix is waiting one #5695
