### ISSUE TITLE
documentation for ConditionFirstBoot flag is inaccurate

### ISSUE THREAD

**Issue by majewsky** [systemd/systemd#5696]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

Git master as of the time of this issue's creation

### Used distribution

irrelevant

### Description

The [documentation for ConditionFirstBoot](https://github.com/systemd/systemd/blob/259a75169186d30b4e6962a80b7dc0c0c89d9e25/man/systemd.unit.xml#L976-L982) describes that it checks for an "unpopulated /etc directory". The word "unpopulated" is not defined further, leading to unnecessary confusion over whether this condition can be met when a system is freshly installed, but packages install contents into `/etc` prior to first boot (see for example [this exchange on HN](https://news.ycombinator.com/item?id=14005025)). The wording of the documentation should be clarified, e.g. by describing that the [actual check](https://github.com/systemd/systemd/blob/5978bdd05fed013d301f6d8b089c7c7ea8c0ef8e/src/core/main.c#L1743) is for the existence of the `/etc/machine-id` file.

**Comment by poettering** [comment]
Fix waiting in #6202.
