### ISSUE TITLE
stubinit doesn't send SIGTERM to the child process

### ISSUE THREAD

**Issue by phreaker0** [systemd/systemd#5711]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

debian stretch rc2

### Expected behaviour you didn't see

stubinit should send SIGTERM to the child process if it receives SIGRTMIN+3

### Unexpected behaviour you saw

stubinit process didn't send SIGTERM to the child process, it gets killed after a timeout

### Steps to reproduce the problem

* run any process in a systemd-nspawn started container as pid 2 (pid1 should be the stubinit) like this:

`systemd-nspawn --user=root --kill-signal=SIGRTMIN+3 --as-pid2  -D /var/lib/machines/container/ /opt/print_signals.py`

* power off the container with machinectl:

`machinectl poweroff container`

No signal is sent to the process and it is killed after a timeout.

(i used a debian jessie system for the container but this shouldn't matter)

**Comment by fsateler** [comment]
@poettering There is a commented out line in the pid1 stub doing exactly this. It has been like this [since the stub was introduced](https://github.com/systemd/systemd/commit/7732f92bad5f24a4bd03bb357af46da56b0ac94d#diff-69afa901cbed9b642a979ff0ffbca9ecR164). Any reason this was commented out?

**Comment by poettering** [comment]
Fix waiting in #6167.
