### ISSUE TITLE
 gpt-auto-root symlink not created (again)

### ISSUE THREAD

**Issue by uzytkownik** [systemd/systemd#5712]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> System boots

### In case of bug report: Unexpected behaviour you saw

> Waiting on the /dev/gpt-auto-root times out which causes dracut to fail

### In case of bug report: Steps to reproduce the problem

> Enable gnuefi and boot system. I tried both hostonly and normal dracut. (Ideally lack of gpt-auto-root should not be fatal and even if system boot is interrupted it can still continue).

**Comment by uzytkownik** [comment]
Similar bug posted previously for older version: issue #3440

**Comment by poettering** [comment]
So, which flags do you have set on your ESP?

**Comment by uzytkownik** [comment]
I'm not sure if you mean attributes or parted flags:

No attributes:
Partition GUID code: C12A7328-F81F-11D2-BA4B-00A0C93EC93B (EFI System)
Partition unique GUID: E55DDA6A-17AA-4A54-B8A3-4F24ABB793A6
First sector: 2048 (at 1024.0 KiB)
Last sector: 1050623 (at 513.0 MiB)
Partition size: 1048576 sectors (512.0 MiB)
Attribute flags: 0000000000000000
Partition name: ''"

'boot' and 'esp' flags:
 1      1049kB  538MB   537MB   fat32              boot, esp

**Comment by uzytkownik** [comment]
@poettering Do you need any more information?

**Comment by uzytkownik** [comment]
I could not reproduce it with 232.

@poettering unless more information is needed can you remove `needs-reporter-feedback` flag?

**Comment by poettering** [comment]
Well, the relevant bits are the gpt bits, not sure if parted shows them to you.

But if this is not reproducible anymore, let's close the issue. Thanks for checking and reporting back!

**Comment by uzytkownik** [comment]
@poettering It is reproducable on newer systemd (233) - I just checked that it is regression (it works on 232).

**Comment by software-artificer** [comment]
@poettering: I'm affected by this issue as well. I'm running root on LVM and I'm not able to set ROOT GUID for LVM partition, am I? If you know tools to do so, I will be grateful for the hint.

I'm using dracut with systemd as my initrd system. Until 233 I was able to specify `root=` via `kernel_cmdline` in `dracut.conf` and it was picked up with no issue.

Starting from 233 behaviour has changed and now I'm unable to boot without specifying `root=` via bootloader (I'm using bootctl). If I understand correctly this is new desired behaviour and I just need to set partition type GUID to `4f68bce3-e8cd-4db1-96e7-fbcaf984b709` for my root partition as per DPS. The question then stays, how do I do that?

Please, let me know if my thinking process is correct and if there is any known proper solution to that situation.

@uzytkownik: Try appending `root=` to your bootloader command line parameters.

**Comment by uzytkownik** [comment]
@filakhtov I have `root=` specified in bootloader, not kernel_cmdline. I'll try it.

**Comment by poettering** [comment]
ah, i misunderstood you then. Still would like to know the precise partition flags!

**Comment by poettering** [comment]
@filakhtov thte GPT root stuff as the name suggests only applies to GPT setups. LVM does not qualify. This bug is hence unrelated to your specific issue. In fact, LVM issues please report to LVM we don't know much about that in systemd upstream

**Comment by uzytkownik** [comment]
@poettering I have a roon on LVM on GPT (well LVM on DM-Crypt on GPT) so this is likely relevant. How can I get those flags (as I mentioned before I could not find this term in google)?

**Comment by poettering** [comment]
@uzytkownik ah, uh. in that case: that is unsupported. the gpt auto logic is for gpt-only setups, and this is unlikely to change. Sorry, but what you are trying to do is simply not supported. Auto-discovery of partitions is not available for LVM. If you want such functionality it would need to be implemented in LVM, please contact the LVM folks for that.

Sorry.

**Comment by uzytkownik** [comment]
@poettering Err, running systemd with root= parameter passed to kernel on LVM system is not supported? I don't need/want this logic (or rather - I have no idea what it is suppose to do and why) and I think systemd is not intended to wait on gpt-auto-root but it does. 

In short - I agree that autodetection of configuration might not work on this setup but it should not get in the way of other things.

**Comment by poettering** [comment]
> Err, running systemd with root= parameter passed to kernel on LVM system is not supported?

It is, but the gpt-auto-root symlink has nothing to do with that.

Are you saying that a job for gpt-auto-root is created on your system without you actually having a GPT root partition marked as such, and with root= set on th kernel cmldine?

**Comment by software-artificer** [comment]
@poettering I'm running LVM on top of GPT of course...

**Comment by uzytkownik** [comment]
@poettering yes. I had no idea that autoconfiguration existed before I run into this bug.

**Comment by poettering** [comment]
what's the precise kernel command line you are using? (also, what is the boot log output?)

**Comment by poettering** [comment]
(background: normally systemd-gpt-auto-generator should become a NOP if the kernel cmdline contains a root= directive, and only if it is run a dependecy on the device unit should be pulled in).

**Comment by uzytkownik** [comment]
```
% grep options /boot/loader/entries/rescue-<machine-id>-<kver>.conf
options         rd.luks.uuid=luks-<LUKS-UUID> rd.luks.allow-discards=luks-<LUKS-UUID> rd.lvm.lv=<ROOT LVM> rd.lvm.lv=<SWAP LVM> root=/dev/mapper/<ROOT LVM> rootfstype=btrfs rootflags=<FLAGS> init=/usr/lib/systemd/systemd quiet rd.driver.blacklist=nouveau 
```

I don't have a boot log output ATM. It looked like / had been mounted but the dependency had been generated nonetheless.

**Comment by uzytkownik** [comment]
@poettering Can you reopen the bug? It prevent me from migrating to 233. (I haven't tested 234 because of unrelated bug).

**Comment by poettering** [comment]
@uzytkownik you are booting with LVM, gpt-auto-discovery does not apply to you, and it's entirely fine if the symlink doesn't exist, because that's how it is if you don't use auto-discovery, and you don't.

if you have boot problems that might be caused by something else, but not with the gpt auto symlink really... What made you think that there was a relationship in the first place?

**Comment by uzytkownik** [comment]
@poettering Systemd reporting waiting on gpt-auto-discovery and timing out.

**Comment by uzytkownik** [comment]
I had run into similar issue on 232 where dracut could not find a binary due to misspelled init= parameter. I wonder if it is not a silent failure elsewhere which makes dracut drop to gpt-auto-discovery.

**Comment by uzytkownik** [comment]
I run into this problem when running under Linux compiled into single EFI under systemd 234 but it does not show up when loading kernel and initramfs separatly.
