### ISSUE TITLE
systemd-networkd: bridge vlan: does not remove vlan 1

### ISSUE THREAD

**Issue by tiwe-de** [systemd/systemd#5716]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Debian stretch

### In case of bug report: Expected behaviour you didn't see

    # bridge vlan show dev test
    port    vlan ids
    test     2 PVID Egress Untagged

### In case of bug report: Unexpected behaviour you saw

    # bridge vlan show dev test
    port    vlan ids
    test     1 Egress Untagged
             2 PVID Egress Untagged

### In case of bug report: Steps to reproduce the problem

/etc/systemd/network/00-test.network:

    [Match]
    Name=test
    
    [Link]
    ARP=false
    
    [Network]
    Bridge=br
    
    [BridgeVLAN]
    VLAN=2
    EgressUntagged=2
    PVID=2

/etc/systemd/network/00-br.netdev:

    [NetDev]
    Kind=bridge
    Name=br
    
    [Bridge]
    VLANFiltering=true
    STP=false

/etc/systemd/network/00-br.network:

    [Match]
    Name=br
    
    [Link]
    ARP=false
    
    [Network]
    IPv6AcceptRA=false

then add some link named `test`:

    # ip link add type veth peer name test

**Comment by tiwe-de** [comment]
Already reported for Debian: https://bugs.debian.org/859941

**Comment by poettering** [comment]
@ssahani maybe something for you?

**Comment by ssahani** [comment]
I need to understand first  where the VLAN1  came from. I don't see this is in the conf or I am missing something.

**Comment by tiwe-de** [comment]
To me it seems like this is the default VLAN that is added by the kernel when the port is added to the bridge:

    # ip link set n3 master br
    # bridge vlan show dev n3
    port    vlan ids
    n3       1 PVID Egress Untagged

**Comment by ssahani** [comment]
I am not sure kernel does it automatically.  There must be some conf doing it . What I am trying to say is we just configure what we desired via `networkd`. That should work as expected.

**Comment by tiwe-de** [comment]
The problem occurs on a fresh Debian machine. There is no custom udev/ifupdown/whatever config.

I agree that systemd-networkd just adds the configured VLAN(s).
My point is that it does not remove the default VLAN that is present after adding the port to the bridge.
It can be removed with:

    # bridge vlan del vid 1 dev test

**Comment by tiwe-de** [comment]
I found the kernel code in `net/bridge/br_vlan.c`.

**Comment by ssahani** [comment]
This `vlan1` is not configured using `networkd` and this specific to debian. This does not happen in `fedora`.Similarly other distribution may have some default configuration and to detect them and do some configuration depending upon the distribution I am not pretty sure we should do this in networkd. I think this is out of scope of networkd.

**Comment by toanju** [comment]
@ssahani the vid 1 is as well applied on Fedora since the default in the kernel is to do so. This is because vlan_default_pvid defaults to 1. networkd does not modify this default. Currently there is no way to remove the pvid, since `Bridge.DefaultPVID` is checked to be a valid VID.

It could be prevented by allowing DefaultPVID=0, which leads to the behavior that the kernel does not set the pvid.

**Comment by tiwe-de** [comment]
@toanju does that mean this bug can now count as reproduced because someone finally actually tried to reproduce it?
I checked for Debian patches (didn't find relevant ones) and couldn't believe that fedora had patches fiddling with bridge default VLANs.

setting

    [Bridge]
    DefaultPVID=42

in `00-br.netdev` actually changes the default VLAN that gets added to ports, but this still opens an unwanted communication channel between ports with disjunct sets of VLANs.

**Comment by toanju** [comment]
I wouldn't call it a bug since it's even the default behavior of the kernel, but I agree that this should be handled.

**Comment by toanju** [comment]
@tiwe-de please check if this works for you

Example config:
```
[NetDev]
Kind=bridge
Name=br

[Bridge]
VLANFiltering=true
DefaultPVID=none
```

**Comment by tiwe-de** [comment]
I just applied https://github.com/systemd/systemd/pull/5899/files#diff-1664ee376e7af10de3751a07e49d3d18 to `src/network/networkd-netdev-bridge.c` in the latest Debian unstable version, used `DefaultPVID=0` and it worked.

**Comment by Habbie** [comment]
I am very much aware I'm commenting on a closed ticket. I am writing this comment just in case somebody has a use for it when searching for this problem, following the advice above, and running into another problem.

`DefaultPVID=none` also removes PVID 1 from the bridge itself. If you had the main IP for that machine tied to, say, `br0`, you might suddenly find VLAN 1 coming in tagged on `br0`. The fix then might be to add something like this to `br0.network`:

```
[BridgeVLAN]
PVID=1
EgressUntagged=1
```

Or, put differently, keep in mind that changing `DefaultPVID` on the bridge does not only affect ports connected to the bridge, it also affects the bridge itself, and you need to set `PVID` in every place you care about it.
