### ISSUE TITLE
please help gdm / gnome-shell developers to correctly understand how systemd works

### ISSUE THREAD

**Issue by soloturn** [systemd/systemd#5718]
since 2 month or so logging in via /lib/systemd/system/getty\@.service instead of GDM ends with an endless loop. 
> if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
>   XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
> fi

errors in the line of the following appear:

> "ignoring child process ..."
> "cannot init inotify ..."
> 

interestingly, on tty2 log in and starting gnome works apart from the messages listed in Issue5247.

**Comment by poettering** [comment]
I am pretty sure GDM/gnome developers can escalate the bug here if they need help on their own, and I am also sure they know how to ping us in case they have questions. hence, let's please track any gdm/gnome issues in gnomebugzilla, not here. Thanks!
