### ISSUE TITLE
ExecStart ignore other line when multi line 

### ISSUE THREAD

**Issue by shcaoguilin** [systemd/systemd#5728]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

名称    ：systemd
架构    ：x86_64
版本    ：219
发布    ：19.el7
大小    ：21 M
源    ：installed
来自源：anaconda
简介    ： A System and Service Manager
网址    ：http://www.freedesktop.org/wiki/Software/systemd
协议    ： LGPLv2+ and MIT and GPLv2+
描述    ： systemd is a system and service manager for Linux, compatible with
         : SysV and LSB init scripts. systemd provides aggressive parallelization
         : capabilities, uses socket and D-Bus activation for starting services,
         : offers on-demand starting of daemons, keeps track of processes using
         : Linux cgroups, supports snapshotting and restoring of the system
         : state, maintains mount and automount points and implements an
         : elaborate transactional dependency-based service control logic. It can
         : work as a drop-in replacement for sysvinit.

可安装的软件包
名称    ：systemd
架构    ：x86_64
版本    ：219
发布    ：30.el7_3.7
大小    ：5.2 M
源    ：updates/7/x86_64
简介    ： A System and Service Manager
网址    ：http://www.freedesktop.org/wiki/Software/systemd
协议    ： LGPLv2+ and MIT and GPLv2+
描述    ： systemd is a system and service manager for Linux, compatible with
         : SysV and LSB init scripts. systemd provides aggressive parallelization
         : capabilities, uses socket and D-Bus activation for starting services,
         : offers on-demand starting of daemons, keeps track of processes using
         : Linux cgroups, supports snapshotting and restoring of the system
         : state, maintains mount and automount points and implements an
         : elaborate transactional dependency-based service control logic. It can
         : work as a drop-in replacement for sysvinit.

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

```
ExecStart=/usr/share/elasticsearch/bin/elasticsearch \
                                                -p ${PID_DIR}/elasticsearch.pid \
                                                -Edefault.path.logs=${LOG_DIR} \
                                                -Edefault.path.data=${DATA_DIR} \
                                                -Edefault.path.conf=${CONF_DIR}

-Edefault.path.logs=${LOG_DIR} \
                                                -Edefault.path.data=${DATA_DIR} \
                                                -Edefault.path.conf=${CONF_DIR}
```
be ignored
### In case of bug report: Steps to reproduce the problem

```
ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR}
```
this will be ok

**Comment by poettering** [comment]
We only track issues in the two most recently released upstream versions here. That 232 and 233 at the moment. 219 is waaaay too old for that, please contact your downstream distribution for help instead. Thanks
