### ISSUE TITLE
Failed to read ACL on /var/log/journal/303a7a6e9d3547feac035eb34a618699/user-1000.journal, ignoring: Operation not supported

### ISSUE THREAD

**Issue by rajeshge** [systemd/systemd#5730]
### Submission type

  - [ ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd issue has been seen with

> … I have modified vim /etc/systemd/journald.conf with Storage=persistent
But after reboot,still journal --verify showing /run/log/journal instead of /var/log/journal

using systemd-229 version.
can some one help me to solve this issue.Thanks in advance.

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
Which distro is this?

what happens if you issue "journalctl --flush"? any log output? do the logs get written to /var then?

**Comment by rajeshge** [comment]
Hi,

I am using Fedo Distribution and using systemd-219 version and 229 also.
i am doing board bringup from NAND flash.
I did changes in vim /etc/systemd/journald.conf as Storage=persistent,but there is no affect that journalctl logs are not storing in /var/log after reboot also.

Then i edited /etc/fstab like bellow
/var/persistent.img   /var/volatile/log ext3 rw,loop=/dev/loop1 0 0

now rebooted still there is no afftect untill systemctl restart systemd-journald.

once you do systemctl restart systemd-journald and reboot,now logs are storing in /var/log.But in this scenario there is no use of journald.conf.i.e what ever the option you put for Storage="" ,there is no affect.

simply if i do changes in vim /etc/systemd/journald.conf Storage=persistent,i want journalctl logs should create in /var/log.

How to do this.

Please give me a solution.

Thanks in advance.

**Comment by rajeshge** [comment]
Hi,

I am using systemd 219 version.I want journalctl logs to be persistent.

1. Changed /etc/systemd/journald.conf Storage=persistent.

2. Reboot or power off and on,expected logs should be created in /var/log/journal,but still logs are storing in /run/log/journal.

3. If without reboot or power off and onif you do systemctl restart systemd-journald,logs are storing at /var/log/journal.

4. Is there any Kernel affect on this scenario that var/log/journal is not creating after reboot with the required change storage=persistent.

This is the situation,can you please help me to solve this issue,and please let me know what else information you required.

FYI@
------------------------------------------------------------------------------------------------------------------
root@phycore-am335x:~# systemctl systemd-journald --version
systemd 219
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

-------------------------------------------------------------------------------------------------------------------
**************************************************************************************************************
root@phycore-am335x:~# systemctl restart systemd-journald
[ 2547.423775] systemd-journald[2490]: Received SIGTERM from PID 1 (systemd).
[ 2547.435388] systemd[1]: Stopping Journal Service...
[ 2547.605305] systemd[1]: Starting Journal Service...
[ 2547.697430] audit: type=1305 audit(1492773878.680:38): audit_enabled=1 old=1 auid=4294967295 ses=4294967295 res=1
[ 2547.741292] systemd[1]: Started Journal Service.
root@phycore-am335x:~#

**********************************************************************************************************



Thanks in advance.

**Comment by poettering** [comment]
Sorry, but we don#t really track bugs in such old systemd versions here. 219 is ancient, current is 233. We try to make this very clear from the issue submission bug.

The journald write logic got changed quite a bit since 219. Please try a current version. if the problem remains there, then please reopen this bug. 

Otherwise: please contact your downstream distribution first! Thank you for understanding!

**Comment by rajeshge** [comment]
Hi,

I am using latest version i.e 229 and 230 and i got the same problem. And journalctl --flush there is no log for this command.

**Comment by poettering** [comment]
This bug report is utterly confusing. You appear to mix all kinds of versions here...

You mentioned that you have some fstab line for /var/volatile/log. Why do you mention that? journald won't write to any such dir. It writes to /var/log/journal. Or did you also place a symlink? 

Please summarize comprehensively, concisely and precisely what exactly isn't working, and how you set up /var/log/journal?

**Comment by rajeshge** [comment]
Hi,

PROBLEM :-  After changing Storage=persistent and reboot the device,logs are not storing in /var/log.

Please find the bellow points.

1. I am doing board bring-up from NAND flash. [ ARM architecture based hardware]

2. I am using systemd-229 version and i also tried 230 version also got the same problem.

3. Why i am talking about /etc/fstab means, /var/log/journal requires a disk space which i am mounting on NAND/Flash like bellow.

/var/persistent.img      /var/volatile/log   ext3 rw,loop=/dev/loop1 0 0

Here persistent.img is some space/memory i.e ex: 20 MB and file systemd type EXT3.

4. If you run journalctl --flush,there is no output on the screen.

5. But if you run killall -SIGUSR1 systemd-journald  (OR) systemctl restart systemd-journald ,then you can see /var/log/journal.

Still if you want more information,please let me know.

Thanks.

**Comment by poettering** [comment]
Uh? Again: journald stores its persistent logs in /var/log/journal, not in /var/volatile/log or any other path. Totally not understanding the scenario you are trying to set up?

journalctl --flush does not generate any output on success, i.e. when the data is already flushed to /var, or when it was now flushed and completed.

**Comment by rajeshge** [comment]
Thanks for your patience.

Leave about the /var/volatile/log.

I want to make journalctl logs to be persistent.

Please tell me how to do it.

As per my understanding need to consider Storage=persistent and reboot the device,journalctl logs should be store in /var/log/journal.

But i am not getting that,this is the issue.

NOTE :- I device has only NAND/Flash ,/var/log/journal should require some disk permanent space on memory ??

So how to achieve this also.

Thanks.

**Comment by mbiebl** [comment]
A log from the boot process might be helpful. Can you follow the steps at https://freedesktop.org/wiki/Software/systemd/Debugging/#index1h1 and attach a debug log from the boot.

**Comment by poettering** [comment]
This is not a support forum btw. This is a bug tracker. If you are simply looking for help, then please contact the systemd mailing list.

Normally, journald should log to /var/log/journal as soon as systemd-journald-flush.service is started. However, that only works correctly if /var/log/journal is writable at that point. if that isn't the case, then journald won't write there...

**Comment by rajeshge** [comment]
Finally got the solution.

Thanks.

**Comment by rajeshge** [comment]
Hi,

The problem is in /etc/fstab.

tmpfs    /var/volatile      tmpfs    defaults    0   0

By comment it,i am getting logs in /var/log/journal. 

PROBLEM: i am getting this bellow error message,can you help me to solve this.

Failed to read ACL on /var/log/journal/303a7a6e9d3547feac035eb34a618699/user-1000.journal, ignoring: Operation not supported.


Thanks..............

**Comment by poettering** [comment]
Again, this is a bug tracker, not a support forum. Also, it's really not OK to rename existing issues and turn them into completely different issues. The rule is: one topic — one issue; new topic → new issue.
