### ISSUE TITLE
systemd-boot bootctl: add command to modify default loader entry in efi variables

### ISSUE THREAD

**Issue by japm48** [systemd/systemd#5739]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version
> 232

### Used distribution
> Arch

This is a feature request for modifying the EFI variable `LoaderEntryDefault` that is set by pressing `d` in a bootloader entry. This variable permanently overrides the default set in `/boot/loader/loader.conf`.
In particular, this can be accessed via: 
```/sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f```

It would be something like: `bootctl set-default <entry>`
This would be useful for a "reboot to another OS" command.

I started writing a standalone program for doing this and I came to the conclusion it would be better if this was integrated here (or maybe more general string variables in https://github.com/rhinstaller/efivar ), because I was writing my own UTF-16/UCS-2 conversion, `chattr +-i` equivalent in C and argument prefix handling from efivarfs.

I could probably manage to write the patch myself.

**Comment by poettering** [comment]
A patch for this woud be very welcome of course, and I guess could be implemented easily at the same time with #8574.
