### ISSUE TITLE
nss-resolve: example nsswitch.conf renders myhostname unused

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#5742]
Arch ships `/etc/nsswitch.conf` with the following hosts line:

    hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname

This seems to be in accordance with the example /etc/nsswitch.conf file found in nss-resolve(8).

My understanding is that `dns` is meant as a fallback for nss-resolve when the latter isn't found on the system. An unintended side-effect of this is that `myhostname` will not be used if nss-resolve exists, regardless of whether `systemd-resolved` is running.

The net effect is that I cannot ping `localhost` or my hostname. (Assuming `systemd-resolved` is not running.) This is bad because I like the idea behind `myhostname` and it would be great if it was used.

Maybe myhostname could be moved right before (or immediately after) mymachines?

I'm using systemd 233-3 with 8.8.8.8/8.8.4.4 as my nameservers in /etc/resolv.conf, systemd-resolved is disabled and not running, and my /etc/hosts file is empty.

**Comment by foutrelis** [comment]
It also seems that `!UNAVAIL` is not sufficient to determine if nss-resolve managed to talk to resolved because it falls back to `libnss_dns.so.2` which I'm guessing returns `NOTFOUND` for localhost (when using external nameservers).

**Comment by poettering** [comment]
Hmm, but nss-resolve does return UNVAIL if it can't talk to resolved, hence the dns/myhostname fallback should be used in that case.

(But you are right, we should drop the internal dlopen() shortcut to libnss_dns, it makes no sense anymore)

**Comment by poettering** [comment]
how precisely did you turn off resolved btw? mask it? disable it?

**Comment by foutrelis** [comment]
> Hmm, but nss-resolve does return UNVAIL if it can't talk to resolved, hence the dns/myhostname fallback should be used in that case.

It would return UNAVAIL if the libnss_dns fallback didn't exist. I believe the latter returns NOTFOUND.

> how precisely did you turn off resolved btw? mask it? disable it?

I don't remember doing anything special to disable it. I believe it's just not running by default on Arch.

**Comment by foutrelis** [comment]
I'm starting to understand why `resolved` is not enabled by default on Arch; the systemd PKGBUILD does the following in its package creation step:

```
  # don't write units to /etc by default. some of these will be re-enabled on
  # post_install.
  rm -r "$pkgdir/etc/systemd/system/"*.wants
```

The above removes the `/etc/systemd/system/multi-user.target.wants/systemd-resolved.service` symlink that systemd ships by default. Only `/etc/systemd/system/dbus-org.freedesktop.resolve1.service` remains in the package but that doesn't do anything.

I also noticed that `systemd-resolved.service` is defined as enabled in `90-systemd.preset` but `systemctl preset [..]` isn't called during installation so all services remain disabled.

I can't say I mind `resolved` being disabled by default (it seems unnecessary for my purposes), but the above seems a bit confusing; in particular, the pointless (?) existence of `/etc/systemd/system/dbus-org.freedesktop.resolve1.service` and the presets which are not applied. Perhaps @falconindy could clarify things a bit further.
