### ISSUE TITLE
systemd-resolver not working when adding a local nameserver to resolv.conf

### ISSUE THREAD

**Issue by gadLinux** [systemd/systemd#5745]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with
systemd --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution
Ubuntu 17.04

### In case of bug report: Expected behaviour you didn't see
I have my ethernet adapters configured to bypass NetworkManager. They get the IP via dhcp. And the DNS nameservers are configured from there.

When the system boots the resolv.conf seems to be configured properly 
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 172.16.0.2
nameserver 127.0.0.53
search cloud.level2crm.com
```

This is, go to the nameserver first and then to the local resolver. Could be other way around but this is managed by system boot so I don't see a way to set it.

### In case of bug report: Unexpected behaviour you saw
If the nameserver is first then it doesn't resolv any name. And this is shown in logs. 
```
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: Switching to system DNS server 172.16.0.2.
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question com IN DNSKEY: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question level2crm.com IN DS: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question level2crm.com IN SOA: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question cloud.level2crm.com IN DS: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question cloud.level2crm.com IN SOA: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question red-nas.cloud.level2crm.com IN DS: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question red-nas.cloud.level2crm.com IN SOA: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question red-nas.cloud.level2crm.com IN AAAA: no-signature
Apr 17 18:08:39 gray-compute systemd-resolved[1570]: DNSSEC validation failed for question red-nas.cloud.level2crm.com IN A: no-signature
```

But if I remove the local nameserver everything seems to work. Since systemd-resolver is getting also the network nameserver as source. And it's resolving everything right.

### In case of bug report: Steps to reproduce the problem
Put network resolver in front of the local resolver. That's all. It should work the same than with systemd-resolver but it's not.

**Comment by poettering** [comment]
127.0.0.53 is resolved's own stub resolver. Normally it should either show up alone or not at all in /etc/resolv.conf, but not mixed with other settings...

Either way, the /etc/resolv.conf you have appears to be managed in a distro-specific way with the "resolveconf" tool. We can't really help you with that upstream I fear. Hence, please contact your downstream distro for help about this! Closing this here, I hope that makes sense. Sorry!
