### ISSUE TITLE
uaccess for sysfs files.

### ISSUE THREAD

**Issue by t-8ch** [systemd/systemd#5746]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

systemd 233
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid

### Used distribution

Archlinux (x64)

### Explanation

It is currently not possible to have udev/logind set the acls on files in sysfs the same way this is possible for devnodes.

### Rationale

I would like to allow the currently logged in user to have write access to `/sys/class/{leds,backlight}/*/brightness` to set the brightness of the display/keyboard backlight etc.
On Wayland xbacklight is not available and all documented solutions (short of using fully fledged settings deamons) use suid-root programs or involve static permissions on those files.
It would be great to give only the logged in user access the same way `uaccess` udev tags do this for normal devnodes.

### Example rule

```udev
ACTION=="remove", GOTO="led_rules_end"

SUBSYSTEM=="backlight", TAG+="uaccess"
SUBSYSTEM=="leds", KERNEL=="*kbd_backlight", TAG+="uaccess"

LABEL="led_rules_end"
```

**Comment by falconindy** [comment]
This would first require the kernel to support ACLs on sysfs.

**Comment by poettering** [comment]
Yeah, we can't implement this without ACLs on sysfs. Closing here, as any discussion is moot until that funcitonality is added to the kernel. Sorry.
