### ISSUE TITLE
IPv6 RA flood !

### ISSUE THREAD

**Issue by belahssen** [systemd/systemd#5747]
guys i Have BIG problem how can i solve it !!
i run flood_router6 without configure nothing 
+==> Help please and give me what i shoud configure like ipv6 ? DHCP SERVER ??

**Comment by evverx** [comment]
I'm not sure I understand what the issue is. Did you mean https://github.com/systemd/systemd/issues/2977?

**Comment by evverx** [comment]
I've just seen https://github.com/systemd/systemd/issues/5668. I'm closing this one.
