### ISSUE TITLE
RFE: Add support for creating a macsec netdev and configure equivalent interface in systemd-networkd

### ISSUE THREAD

**Issue by gkarakou** [systemd/systemd#5754]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

latest

### Used distribution

fedora 25

-----
It would be a useful addition to add suport for a macsec netdev in systemd-networkd.
Since support for macsec(IEEE 802.1AE)  is already added in kernel (from 4.6 kernel series[1] ) as a loadable module, fedora doesn't come with a patched iproute package[2]  to support macsec and also lacks  interface configuration from systemd-networkd. 
Therefore it would be wise to implement support for an IEEE standard[3].

Sources:
[1]https://kernelnewbies.org/Linux_4.6
[2] http://man7.org/linux/man-pages/man8/ip-macsec.8.html
[3] https://standards.ieee.org/findstds/standard/802.1AE-2006.html

Some references of interest:
[](url)https://en.wikipedia.org/wiki/IEEE_802.1AE
 [](url)https://developers.redhat.com/blog/2016/10/14/macsec-a-different-solution-to-encrypt-network-traffic/

**Comment by ssahani** [comment]
We need the generic netlink to be in first #5593. This work should be on top of that.

**Comment by yuwata** [comment]
@ssahani #9170 (revised version of #5593) has been already merged. Are you working on this? Or do you have any plan to support this?

**Comment by ssahani** [comment]
I have patches need some time to complete these.

**Comment by ssahani** [comment]
I have started working on this again.  My WIP branch.

https://github.com/systemd/systemd/compare/master...ssahani:macsec

**Comment by ssahani** [comment]
@gkarakou I have opened a PR now could please test.
