### ISSUE TITLE
thinkpad_acpi kernel module load failed

### ISSUE THREAD

**Issue by Konfekt** [systemd/systemd#5758]
### Submission type

  Bug report

### systemd version the issue has been seen with

  systemd 228
  +PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN

### Used distribution

  OpenSUSE 42.2

### In case of bug report: Expected behaviour you didn't see

  systemd-modules-load sucessfully inserts thinkpad_acpi

### In case of bug report: Unexpected behaviour you saw

  systemd-modules-load failed to insert thinkpad_acpi because there is no such file or directory

### In case of bug report: Steps to reproduce the problem

  install the package http://download.opensuse.org/repositories/home:/revealed/openSUSE_Leap_42.2/x86_64/thinkfan-0.9.2-56.3.x86_64.rpm

### sudo journalctl | grep think gives:

  Relevant log obtained:

  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_notify (err 0)
  avril 19 06:28:05 notebook systemd-modules-load[109]: Failed to insert 'thinkpad_acpi': No such file or directory
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_add (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_card_register (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_card_free (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_new1 (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_card_new (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_boolean_mono_info (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_notify (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_add (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_card_register (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_card_free (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_new1 (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_card_new (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_boolean_mono_info (err 0)
  avril 19 06:28:05 notebook kernel: thinkpad_acpi: Unknown symbol snd_ctl_notify (err 0)
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: ThinkPad ACPI Extras v0.25
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: http://ibm-acpi.sf.net/
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: ThinkPad BIOS 6QET70WW (1.40 ), EC 6QHT34WW-1.15
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: Lenovo ThinkPad X201, model 3323DAG
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: detected a 16-level brightness capable ThinkPad
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: radio switch found; radios are enabled
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: possible tablet mode switch found; ThinkPad in laptop mode
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: This ThinkPad has standard ACPI backlight brightness control, supported by the ACPI video driver
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: Disabling thinkpad-acpi brightness events by default...
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: rfkill switch tpacpi_bluetooth_sw: radio is unblocked
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: rfkill switch tpacpi_wwan_sw: radio is blocked
  avril 19 06:28:08 notebook kernel: thinkpad_acpi: Standard ACPI backlight interface available, not loading native one
  avril 19 06:28:08 notebook kernel: input: ThinkPad Extra Buttons as /devices/platform/thinkpad_acpi/input/input8
  avril 19 06:28:08 notebook systemd-modules-load[417]: Inserted module 'thinkpad_acpi'
  avril 19 06:28:08 notebook thinkfan[797]: thinkfan 0.9.1 starting...

**Comment by poettering** [comment]
Well, it appears your module references non-existing symbols. That's an issue between your kernel module and the kernel, systemd is not involved. Please contact the kernel or kernel module vendor/distro for help, we can't help you there. Sorry.
