### ISSUE TITLE
all domains in gov.pl don't resolve regardless of dns server because of dnssec setting

### ISSUE THREAD

**Issue by nbbn** [systemd/systemd#5763]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 17.04 Desktop

### In case of bug report: Expected behaviour you didn't see

I want to receive response for:
> $ nslookup stat.gov.pl
>Server:		127.0.0.53
>Address:	127.0.0.53#53

>Non-authoritative answer:
>Name:	stat.gov.pl
>Address: 194.165.48.116

### In case of bug report: Unexpected behaviour you saw

> $ nslookup stat.gov.pl
Server:		127.0.0.53
Address:	127.0.0.53#53

>** server can't find stat.gov.pl: SERVFAIL

### In case of bug report: Steps to reproduce the problem

Use default settings for systemd-resolve and try to visit any website in *.gov.pl (e.g. stat.gov.pl)
I guess that problem is with dnssec and its implementation either in gov.pl domain or systemd-resolve.
If it is a problem with gov.pl dns authority, please whitelist them or persuade.
When I change `dnssec` in resolved.conf to `no` it works with any dns server.

**Comment by nbbn** [comment]
Ubuntu/Debian maintainers reduced the impact of the issue by changing default setting of `DNSSEC` to `off` (more in [changelog](https://launchpad.net/ubuntu/+source/systemd/232-21ubuntu3)), but problem still exists for those, who want to use DNSSEC.

**Comment by poettering** [comment]
Could you please update to systemd 233? The DNSSEC code got quite some updates in that version, and there's a good chance what you are trying to do already works with the never version!

**Comment by nbbn** [comment]
Not really, I don't want to mix my ubuntu installation up. If you are sure that issue is fixed in new release (lookup for `stat.gov.pl` with `dnssec=yes`) I will make bugreport in ubuntu or/and Debian (I guess both use the same package), and hopefully fix will be backported or at least will be known/invalidated.

**Comment by poettering** [comment]
@nbbn I am not sure, but I think it is very likely.

**Comment by poettering** [comment]
hmm, so, I just tried this here with systemd git, and it failed too. Hence, it appears to be a bug that still exists

**Comment by keszybz** [comment]
```console
$ systemd-resolve stat.gov.pl
stat.gov.pl: 194.165.48.116

-- Information acquired via protocol DNS in 247.9ms.
-- Data is authenticated: no
```
This is with current git, but I don't think anything changed on our side, so it's most likely that `gov.pl` changed their config.
