### ISSUE TITLE
'systemctl -H' is blocking

### ISSUE THREAD

**Issue by TheTesla** [systemd/systemd#5779]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Ubuntu 16.04.2 (x86_64)

### In case of bug report: Expected behaviour you didn't see

command not blocking like:

`systemctl -H root@127.0.0.1 status networking.service
`

### In case of bug report: Unexpected behaviour you saw

command is block, must be stopped with ctrl+c

### In case of bug report: Steps to reproduce the problem

`systemctl -H root@127.0.0.1 status networking.service
`
or all other examples with systemctl -H

**Comment by poettering** [comment]
I am sorry, but I am not sure I understand what you are trying to say. What precisely do you mean by "blocking"?

**Comment by TheTesla** [comment]
That means: if I run this command in an interactive shell, the command is executed but does not end. It is waiting forever.

**Comment by poettering** [comment]
does "ssh root@127.0.0.1" work correctly?

That said can you retry with something newer than 229? We only track issues in the two most recent upstream releases here, and that's 231 and 232 right now. For everything else, please contact your distro/downstream packager for help.

I will close this now. If you manage to reproduce this with something newer (i.e. 231 or 232) please reopen!

**Comment by TheTesla** [comment]
thanks, bug is solved in version 232

**Comment by poettering** [comment]
Ah, very good. Thank you for reporting back!
