### ISSUE TITLE
resolved does not honor v6 and v4 gateways on different interfaces

### ISSUE THREAD

**Issue by hexchain** [systemd/systemd#5782]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### Background

I'm using systemd-networkd and systemd-resolved on a machine that has different interface for v4 and v6. The v4 interface (eth0) connects to ISP, and the v6 interface connects to HE.net Tunnelbroker. Here is the relevant networkd configuration:

```
$ cat default.network 
[Match]
Name=eth0

[Network]
Address=v4.addr/24
Gateway=v4.gateway
DNS=8.8.8.8
DNS=8.8.4.4
Tunnel=he-ipv6

$ cat heipv6.netdev 
[Match]

[NetDev]
Name=he-ipv6
Kind=sit
MTUBytes=1480

[Tunnel]
Local=v4.addr
Remote=he.remote.addr
TTL=255

$ cat heipv6.network 
[Match]
Name=he-ipv6

[Network]
Address=v6::addr/64
Gateway=v6::gateway
DNS=2001:470:20::2
DNS=74.82.42.42
IPForward=ipv6
```

And this line in `/etc/nsswitch.conf`:
```
hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname
```

When it's up and running:
```
$ networkctl status
●        State: routable
       Address: v4.addr on eth0
                v6::addr on he-ipv6
                fe80::xxxxx on eth0
                fe80::xxxxx on he-ipv6
       Gateway: v4.gateway on eth0
                v6::gateway on he-ipv6
           DNS: 2001:470:20::2
                74.82.42.42
                8.8.8.8
                8.8.4.4
```

### Problem

Under this configuration, if the domain to be resolved only has A record (no AAAA), the resolution fails.

```
$ getent -s resolve ahosts www.twitter.com
$ # no output
```

Not a DNS expert but from my point of view, queries concerning AAAA and A should go to different DNS servers, and in this case it shouldn't fail.

**Comment by poettering** [comment]
Hmm, issuing A record lookups via IPv6 is perfectly valid and safe, and doing lookups for AAAA via IPv4 too. Are you saying your DNS services don't permit this? That'd be quite a strange setup. 

Or am I not grokking what you are trying to say? Can you elaborate? What does the IPv6 server respond if you try to resolve a hostname to A?

**Comment by hexchain** [comment]
(sorry for the late reply)

> issuing A record lookups via IPv6 is perfectly valid and safe, and doing lookups for AAAA via IPv4 too.

Yes, and my DNS permits this of course. Checking via `dig` returns perfectly valid results.

The problem is that `resolved` does not seem to allow this:
```
$ networkctl status
●        State: routable
       Address: v4.addr on eth0
                v6::addr on he-ipv6
                fe80::xxxxx on eth0
                fe80::xxxxx on he-ipv6
       Gateway: v4.gateway on eth0
                v6::gateway on he-ipv6
           DNS: 2001:470:20::2
                74.82.42.42
                8.8.8.8
                8.8.4.4
$ dig +short A twitter.com @2001:470:20::2
104.244.42.65
$ dig +short A twitter.com @74.82.42.42
104.244.42.129
$ dig +short A twitter.com @8.8.8.8
104.244.42.193
104.244.42.129
$ dig +short A twitter.com @8.8.4.4
104.244.42.65
104.244.42.1
$ getent -s resolve ahosts www.twitter.com
$ systemd-resolve www.twitter.com
www.twitter.com: resolve call failed: 'twitter.com' does not have any RR of the requested type
```

However explicitly asking for an A record does return something:
```
$ systemd-resolve -t A www.twitter.com
twitter.com IN A 104.244.42.1

-- Information acquired via protocol DNS in 2.2ms.
-- Data is authenticated: no
```

In this case both IPv4 and v6 are routable but through different interfaces. Does that confuse `resolved`?

**Comment by poettering** [comment]
Hmm, so, if you do not specify the address type you are looking for then we'll suppress answers for protocols we consider "unroutable" on the local system. An protocol is considered "routable" if there's at least one IP address configured on at least one interface of that type, and a couple of other requirements hold. Specifically:

https://github.com/systemd/systemd/blob/master/src/resolve/resolved-link.c#L553

It would be good to see the precise configuration on your system, i.e. ip addr, and systemd-resolve --status.

**Comment by hexchain** [comment]
I've checked my configuration and both v4 and v6 are "routable" according to requirements.

```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:16:3e:25:0a:28 brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/24 brd xx.xx.xx.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::xxxxx/64 scope link 
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
4: he-ipv6@eth0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/sit xx.xx.xx.xx peer 216.66.80.30
    inet6 2001:470:xxxxx/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::xxxxx/64 scope link 
       valid_lft forever preferred_lft forever
$ ip r
default via xx.xx.xx.1 dev eth0 proto static 
xx.xx.xx.0/24 dev eth0 proto kernel scope link src xx.xx.xx.xx
$ ip -6 r
2001:470:xxxxx/64 dev he-ipv6 proto kernel metric 256  pref medium
fe80::/64 dev eth0 proto kernel metric 256  pref medium
fe80::/64 dev he-ipv6 proto kernel metric 256  pref medium
default via 2001:470:xxxxx::1 dev he-ipv6 proto static metric 1024  pref medium
```

`sysremd-resolve --status` (removed Global section):
```
Link 4 (he-ipv6)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 2001:470:20::2
                      74.82.42.42

Link 3 (sit0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (eth0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 8.8.8.8
                      8.8.4.4
          DNS Domain: hexchain.org
```

**Comment by poettering** [comment]
Hmm, and what does "networkctl status he-ipv6" say about the interface? What's the reported state?

**Comment by hexchain** [comment]
```
$ networkctl status he-ipv6
● 4: he-ipv6
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/heipv6.network
            Type: sit
           State: routable (configured)
         Address: 2001:470:xxxxx::2
                  fe80::xxxxx
         Gateway: 2001:470:xxxxx::1
             DNS: 2001:470:20::2
                  74.82.42.42
```

**Comment by poettering** [comment]
Hmm, strange, I have no immediate idea then. 

resolved received quite a number of change in v233. Could you try to update first, before we spend more time on tracking this down? After all the issue might already be fixed there.

If the problem persists: could you check with wireshark whether the lookup results in both an A and an AAAA query packet? Or do you only see one of them on the wire?

Next thing then would be gdb through the lookup and figure out what's going on. Do you feel comfortable with gdb? If so, please attach gdb to a running resolved (with debug symbols installed), set a breakpoint on dns_query_candidate_is_routable(), and step through the function for each invocation that is done as result of an offending lookup. It should be called once for each reply resolved gets, and determines if the reply is useful given the local network configuration or not.

**Comment by hexchain** [comment]
Okay, I've updated to systemd 233 and made a [packet capture](https://paste.xinu.at/VsW7/) through `getent -s resolve twitter.com` (no more IP privacy, :-( ).

It seemed to me that the progress went as follow:
1. resolved sent out two requests asking for **twitter.com** at the same time - one for A record, to IPv4 DNS, another for AAAA, to IPv6 DNS.
2. IPv6 DNS returned CNAME first (packet 3)
3. resolved sent out two requests asking for **www.twitter.com** at the same time - one for A record, to IPv4 DNS, another for AAAA, to IPv6 DNS.
4. IPv4 DNS returned CNAME and A for the first query.
5. IPv6 DNS returned no answer RRs for query 3.
6. IPv4 DNS returned A for query 3.

**Comment by docsmooth** [comment]
Simple test anyone can run to see what they're getting:

systemd-resolve --status | awk 'BEGIN{ x=0 }; /DNS Servers/ { x=1; print $NF }; x==1 && $1==$NF && $1!="" { print $NF };' |sort -u  | while read DNS; do echo "# Testing DNS: $DNS" ; dig ANY `dig NS x.x.x.x.x.x.x.x.x.x.x.0.0.6.2.ip6.arpa @$DNS +short` @$DNS +short; done

# Testing DNS: x.x.x.4
x.x.x.5
x.x.x.4
2600::x:b14e
2600::x:809e
# Testing DNS: x.x.x.5
x.x.x.4
x.x.x.5
2600::x:7216
# Testing DNS: 2600::x:b14e
x.x.x.4
x.x.x.5
2600::x:7216
# Testing DNS: 2600::x:7216
x.x.x.5
x.x.x.4
2600::xx:809e
2600::xx:b14e

Remove the @$DNS server part of the query and get:
systemd-resolve --status | awk 'BEGIN{ x=0 }; /DNS Servers/ { x=1; print $NF }; x==1 && $1==$NF && $1!="" { print $NF };' |sort -u  | while read DNS; do echo "# Testing DNS: $DNS" ; dig ANY `dig NS x.x.x.x.x.x.x.x.x.x.x.x.0.0.6.2.ip6.arpa +short` +short; done 
# Testing DNS: x.x.x.4
x.x.x.4
x.x.x.5
# Testing DNS: x.x.x.5
x.x.x.4
x.x.x.5
# Testing DNS: 2600::x:76c:b14e
x.x.x.4
x.x.x.5
# Testing DNS: 2600::x:30b:7216
x.x.x.4
x.x.x.5

Only IPv4 addresses come back from systemd-resolvd.
My config:
$ip route
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 28:f1:0e:41:f4:8e brd ff:ff:ff:ff:ff:ff
    inet x.x.x.46/24 brd x.x.x.255 scope global dynamic enp0s31f6
       valid_lft 1375365sec preferred_lft 1375365sec
    inet6 2600::x:679:74a0/64 scope global temporary dynamic
       valid_lft 597767sec preferred_lft 78817sec
    inet6 2600::x:2b6:65b7/64 scope global mngtmpaddr noprefixroute dynamic
       valid_lft 2351361sec preferred_lft 364161sec
    inet6 fe80::b1e:fbef:542a:e7b8/64 scope link
       valid_lft forever preferred_lft forever
3: wlp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP group default qlen 1000
    link/ether e4:a4:71:f3:01:15 brd ff:ff:ff:ff:ff:ff
    inet x.x.x.49/24 brd x.x.x.255 scope global dynamic wlp1s0
       valid_lft 1210534sec preferred_lft 1210534sec
    inet6 2600::x:2ba:d53/64 scope global temporary dynamic
       valid_lft 604747sec preferred_lft 85861sec
    inet6 2600::x:63e:a1f4/64 scope global temporary deprecated dynamic
       valid_lft 518834sec preferred_lft 0sec
    inet6 2600::x:f5:5b6d/64 scope global temporary deprecated dynamic
       valid_lft 432922sec preferred_lft 0sec
    inet6 2600::x:de2:c883/64 scope global mngtmpaddr noprefixroute dynamic
       valid_lft 2351361sec preferred_lft 364161sec
    inet6 fe80::5557:24ad:c39e:1498/64 scope link
       valid_lft forever preferred_lft forever
4: vmnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:50:56:c0:00:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.25.1/24 brd 192.168.25.255 scope global vmnet1
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fec0:1/64 scope link
       valid_lft forever preferred_lft forever
5: vmnet8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:50:56:c0:00:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.24.1/24 brd 192.168.24.255 scope global vmnet8
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fec0:8/64 scope link
       valid_lft forever preferred_lft forever
$ip route
default via x.x.x.254 dev enp0s31f6 proto static metric 100
default via x.x.x.254 dev wlp1s0 proto static metric 600
169.254.0.0/16 dev enp0s31f6 scope link metric 1000
x.x.x.0/24 dev enp0s31f6 proto kernel scope link src x.x.x.46 metric 100
x.x.x.0/24 dev wlp1s0 proto kernel scope link src x.x.x.49 metric 600
192.168.24.0/24 dev vmnet8 proto kernel scope link src 192.168.24.1
192.168.25.0/24 dev vmnet1 proto kernel scope link src 192.168.25.1
$ ip -6 route
2600:x::/64 dev enp0s31f6 proto ra metric 100  pref medium
2600:x::/64 dev wlp1s0 proto kernel metric 256  expires 432755sec pref medium
2600:x::/64 dev enp0s31f6 proto kernel metric 256  expires 597600sec pref medium
2600:x::/64 dev wlp1s0 proto ra metric 600  pref medium
fe80::a204:60ff:fe3a:2b8e dev enp0s31f6 proto static metric 100  pref medium
fe80::a204:60ff:fe3a:2b8e dev wlp1s0 proto static metric 600  pref medium
fe80::/64 dev vmnet1 proto kernel metric 256  pref medium
fe80::/64 dev vmnet8 proto kernel metric 256  pref medium
fe80::/64 dev wlp1s0 proto kernel metric 256  pref medium
fe80::/64 dev enp0s31f6 proto kernel metric 256  pref medium
default via fe80::x:2b8e dev enp0s31f6 proto static metric 100  pref medium
default via fe80::x:2b8e dev wlp1s0 proto static metric 600  pref medium
$ mtr -r -c 1 -6 ipv6.whatismyipv6.com
Start: Tue Dec  5 16:59:34 2017
HOST: kubuntu10                   Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 2600:x:a204:  0.0%     1    0.4   0.4   0.4   0.4   0.0
  2.|-- 2600:x::1     0.0%     1    4.2   4.2   4.2   4.2   0.0
  3.|-- 2001:x:156  0.0%     1    6.8   6.8   6.8   6.8   0.0
  4.|-- 2001:x::11  0.0%     1    5.2   5.2   5.2   5.2   0.0
  5.|-- 2001:x::4  0.0%     1   10.2  10.2  10.2  10.2   0.0

So I definitely have ipv6 connectivity.  So systemd-resolved's idea of what's a "valid" configuration is incorrect?  or getting confused by VMware?

**Comment by flokli** [comment]
Ran into this as well, in my case with `wlp3s0` as default gateway for IPv4, and a wireguard tunnel to get IPv6 connectivity (not managed via systemd-networkd, "manually" set up).

systemd-resolved assumes IPv6 is unroutable, and doesn't query AAAA records if not specified explicitly. Escpecially when the host to reach is IPv6 only, that's a bit annoying ;-)

```
$ ip -6 a s dev chekov                
10: chekov: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1000
    inet6 2a01:xxx:xxx:22c8::2/128 scope global 
       valid_lft forever preferred_lft forever

$ ip -6 r
::1 dev lo proto kernel metric 256 pref medium
2a01:xxx:xxx:22c8::1 dev chekov metric 1024 pref medium
2a01:xxx:xxx:22c8::2 dev chekov proto kernel metric 256 pref medium
fe80::/64 dev wlp3s0 proto kernel metric 600 pref medium
default via 2a01:xxx:xxx:22c8::1 dev chekov metric 599 pref medium

$ networkctl status chekov
● 5: chekov
       Link File: n/a
    Network File: n/a
            Type: wireguard
           State: n/a (unmanaged)
         Address: 172.20.27.226
                  2a01:xxx:xxx:22c8::2
         Gateway: 2a01:xxx:xxx:22c8::1

$ systemd-resolve google.com          
google.com: 172.217.16.142

-- Information acquired via protocol DNS in 285.6ms.
-- Data is authenticated: no

$ systemd-resolve google.com --type AAAA
google.com IN AAAA 2a00:1450:4001:81c::200e

-- Information acquired via protocol DNS in 189.4ms.
-- Data is authenticated: no
```

cc @ssahani @Mic92

**Comment by flokli** [comment]
I dont think we properly mimic glibc's behaviour by stripping records as written in 011696f76233486bc56c266b18a328924f70269c - default seems to be to query both records:

> Currently, in order to be fully adherent with RFC 2553, getaddrinfo() performs both a AAAA (IPv6 address query) query and a A (IPv4 address query) query to its DNS server.

(see https://bugzilla.redhat.com/show_bug.cgi?id=1027452#c7, stripping unconditionally violates POSIX, which is why RHEL discussed adding a `gai.conf` switch to disable AAAA lookups)

I also think it's quite hard to properly detect adress family reachability - just looking for default routes on all interfaces might also not be enough (given `0.0.0.0/1` and `128.0.0.0/1` together are a valid default route too ;-))

@poettering can we revert 011696f76233486bc56c266b18a328924f70269c?

**Comment by Mic92** [comment]
So the problem in the wireguard case is, that it was not managed by networkd explicitly? Would it not possible to just use netlink to check if an address is routable? `ip route get 2a00:1450:4001:81c::200e`

**Comment by flokli** [comment]
In that setup, networkd knows no DNS server for the wireguard interface, as it's not managed by networkd itself.

After adding a DNS server for that interface, I see AAAA records when explicitly querying on that interface:

```
flokli@tp:~|⇒  resolvectl dns chekov 1.1.1.1
flokli@tp:~|⇒  systemd-resolve -i chekov google.com     
google.com: 216.58.207.78
            2a00:1450:4001:820::200e

-- Information acquired via protocol DNS in 541.7ms.
-- Data is authenticated: no
```

But when no interface is specified explicitly, this doesn't work:
```
flokli@tp:~|⇒  systemd-resolve google.com          
google.com: 216.58.207.78

-- Information acquired via protocol DNS in 213.5ms.
-- Data is authenticated: no
```

… same applies to lookups via glibc -> (nscd ->) NSS, so IPv6-only locations remain unresolvable from higher level userspace.

I'm still not convinced we should skip doing A or AAAA lookups depending on connectivity in first place.

**Comment by Mic92** [comment]
I could imagine that both behaviors would make sense for some people also I don't find the current behavior intuitive.

**Comment by flokli** [comment]
It effectively breaks dualstack resolving for people with IPv6 default route over different interfaces, quite common with 6rd or other IPv6 deployment mechanisms, only for the small (and with caching questionable) performance improvement of not requesting AAAA records too in some non-dualstack environments.

I think glibc and POSIX are right in resolving both records unconditionally by default, and systemd should do the same, at least in default case.

**Comment by liskin** [comment]
One possibly interesting observation: I started experiencing this bug only aftes I crossgraded my Debian testing from i386 to amd64. 32-bit systemd-resolved was behaving correctly, 64-bit one thinks my system doesn't have ipv6 routes.

**Comment by flokli** [comment]
#8017 described a similar usecase as the one reported here.

The current behaviour is simply unintuitive and breaks certain workflows.

We should really copy glibc's behaviour here, at least until a knob in `gai.conf` appears, as suggested in above RHEL bug.
