### ISSUE TITLE
Add IBM USB Travel Mouse to hwdb

### ISSUE THREAD

**Issue by rderooy** [systemd/systemd#5785]
### Submission type

  - [ ] Bug report
  - [ X ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231-14.fc25.x86_64

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 25

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

Could you add the below old IBM USB mouse with wheel (regular 24 clicks rotation).

# IBM USB Travel Mouse (MO32BO)
mouse:usb:v04b3p3107:name:HID 04b3:3107:
 MOUSE_DPI=800@125

**Comment by martinpitt** [comment]
"HID 04b3:3107" is a very unusual name. Every other entry in that file has a proper name, and replicating the vendor/product ID like that looks weird. The documentation at the top says
```
# if name is unavailable, use
# mouse:<subsystem>:v<vid>p<pid>:*
```
Can you please verify that this works well with just
```
mouse:usb:v04b3p3107:name:*
MOUSE_DPI=800@125
```

**Comment by rderooy** [comment]
I just validated and can confirm that using a wildcard works fine.
