### ISSUE TITLE
Automatic storage does not log into /var/log/journal

### ISSUE THREAD

**Issue by rajeshge** [systemd/systemd#5788]
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> … 219

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> …yocto fido

### In case of bug report: Expected behaviour you didn't see

> …/var/log/journal should contain the logs.

### In case of bug report: Unexpected behaviour you saw

> …On booting/rebooting the system /var/log/journal is still empty.

### In case of bug report: Steps to reproduce the problem

> …From the configuration files only /etc/systemd/journald.conf exists with the only non-empty and uncommented line "[Journal]" and /var/log/journal exists as a directory.

I have now added the line "Storage=persistent" to /etc/systemd/journald.conf in the "[Journal]" section but after a reboot /var/log/journal is still empty so the problem seems to be that nothing gets logged at all.

**Comment by evverx** [comment]
@rajeshge , why did you create the issue? You have already opened the same [one]( https://github.com/systemd/systemd/issues/5730).

I'm closing.
