### ISSUE TITLE
Can't login after boot with Kernel 4.10.12, soft lockup in systemd-logind

### ISSUE THREAD

**Issue by machine-mind** [systemd/systemd#5790]
_###_ Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

output of systemd --version:
> systemd 229 +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu Gnome 16.04 with Mainline Kernel **4.10.12**

### In case of bug report: Expected behavior you didn't see

> Successful login after boot on the gnome login screen or over the shell. (Using Mainline Kernel Version 4.10.11, login works fine)

### In case of bug report: Unexpected behavior you saw

> After logging in to the gnome login screen, the system freezes. Trying to login using the shell (Ctr+Alt+F1) also freezes the system. The following ouptut appears on the shell repeatedly:
**MI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd-logind:913]** 

### In case of bug report: Steps to reproduce the problem

> Boot Ubuntu Gnome 16.04 with Kernel 4.10.12 and try to login after boot.

**Comment by poettering** [comment]
Sorry, but that's a kernel problem. Please contact the kernel maintainers of your distro for help. Userspace should not be able to tirgger a soft lockup under any case in the kernel.
