### ISSUE TITLE
Add Fast Open option in .socket

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#5796]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Archlinux

### In case of bug report: Expected behaviour you didn't see

> fast open option to be added in .socket

### In case of bug report: Unexpected behaviour you saw

> no support so far

### In case of bug report: Steps to reproduce the problem

> 
Kernel 4.11 has added a new feature [net/tcp-fastopen: Add new API support](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=19f6d3f3c8422d65b5e3d2162e30ef07c6e21ea2). It is very natural for systemd to support it.

> This patch adds a new socket option, TCP_FASTOPEN_CONNECT, as an
alternative way to perform Fast Open on the active side (client). Prior
to this patch, a client needs to replace the connect() call with
sendto(MSG_FASTOPEN). This can be cumbersome for applications who want
to use Fast Open: these socket operations are often done in lower layer
libraries used by many other applications. Changing these libraries
and/or the socket call sequences are not trivial. A more convenient
approach is to perform Fast Open by simply enabling a socket option when
the socket is created w/o changing other socket calls sequence

**Comment by poettering** [comment]
Hmm? I am not sure I grok this request? This new sockopt appears to be for the client side only, i.e. the side that calls connect(), not the side that calls listen(). systemd .socket units are only for listening on sockets, and hence the sockopt doesn't really apply. What am I missing, can you elaborate?

**Comment by enihcam** [comment]
sorry i misunderstood the feature. ignore me.
