### ISSUE TITLE
http_proxy does not work in Ubuntu 16.04/Systemd 229

### ISSUE THREAD

**Issue by leemgs** [systemd/systemd#5797]
It's strange. I could not normally use http_proxy variable with systemd-based service file. 
In my case, I have written the service file as following: 

$ sudo vi /etc/profile  [enter]
```
#### Setting proxy IP for firewall
export http_proxy=http://10.112.1.100:8080
export https_proxy=http://10.112.1.100:8080
export ftp_proxy=http://10.112.1.100:8080
```

$ sudo vi /lib/systemd/system/my-foo.service [enter]
`EnvironmentFile=/etc/profile`

or 
$ sudo vi /lib/systemd/system/my-foo.service [enter]
`StartExecPre=source /etc/profile `

What is it incorrect? Anyone who has experience the issue like me?

**Comment by leemgs** [comment]
I have found a hint by running system utilities such as ltrace/strace. In case that the developers have to start service files in the restricted firewall, It seems that we can solve the issue. I hope that this comment will be helpful to the developers that use systemd instead systemv init due to up-to-date Linux distributions. 

$ cat /lib/systemd/system/my-foo.service 
```
[Unit]
Description=My foo service
After=network.target

[Service]
Environment="HTTP_PROXY=http://10.112.1.100:8080"
Environment="HTTPS_PROXY=http://10.112.1.100:8080"
Environment="FTP_PROXY=http://10.112.1.100:8080"
Type=simple
User=myid
Group=myid
ExecStart=/usr/bin/my-foo start
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

Note that you have to write "**HTTP_PROXY**" with a capital word to avoid unexepcted situation. And type **appropriate an user and group id**. The default id is "root". 

\CC: @myungjoo , @hataejun, @leechwin, @5hk , @shinasto

**Comment by evverx** [comment]
@leemgs , have you read https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=? What makes you think that you can use `export A=1`?

**Comment by evverx** [comment]
This issue is neither a bug nor RFE. I'm closing.
