### ISSUE TITLE
udev: assign a device to plugdev group

### ISSUE THREAD

**Issue by chfast** [systemd/systemd#5802]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231

### Used distribution

> Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> I have a usb device that is usable by users only if is assigned to plugdev. Is it possible to add default udev rules for the device to be assigned to plugdev group by default? If that's possible I can sent a PR. I just need to know where to store the rules.

### In case of bug report: Unexpected behaviour you saw

> By default the device is assigned to root group.

**Comment by martinpitt** [comment]
You can certainly write your own rules for anything. But I don't think we want to adopt the "plugdev" group concept upstream -- this is what Ubuntu used a dozen years ago before the hal/udev concept of dynamic ACLs came up, and the plugdev group is deprecated since then.

**Comment by chfast** [comment]
If I may ask a question about it... Is there any place where uaccess tag can be added for this devices? I've found https://github.com/systemd/systemd/blob/master/src/login/70-uaccess.rules.

**Comment by martinpitt** [comment]
@chfast: Yes, those are the upstream rules that we ship and are applicable to every system. You can add your own local rules to `/etc/udev/rules.d/71-uaccess-local.rules` (or similar), or if this is about a device class that should be made accessible everywhere, this might also be appropriate for an upstream PR. (You didn't give any details)
