### ISSUE TITLE
systemd-backlight failed to load saved backlight on bootup for acpi_video

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#581]
Just on yestoday night, I come across to solve the backlight control on my asus-notebook with nouveau driver, the key is to set acpi_osi= . Though not understanding well enough , the backlight can be set easily set through related keys, that's good enough for me at least now! 
But then I found the backlight on bootup is set to be the maximum, after tried passing acpi_backlight=vendor to kernel, systemd-backlight begin to work well, but except for the change of backlight, there is no other sign displayed on the desktop to show the backlight is changing. Well, as there is status in gnome top panel, that's ok.
Then, Another problem emerged, the bootup backlight was limitted to be above a minimum value which for me is still a little brighter, after searched for some time, I found a key variable on the freedesktop manual, ID_BACKLIGHT_CLAMP, but where and how can I set it properly?
And if possible, may anybody tell me that what's reason of the above problem?
thanks very much!

**Comment by dvdhrm** [comment]
Please add a udev-rule to `/etc/udev/rules.d/` (eg., `99-custom.rules`) with:

```
SUBSYSTEM=="backlight", ENV{ID_BACKLIGHT_CLAMP}=0
```

This will suppress the automatic clamping to a minimum value.

**Comment by ghost** [comment]
thanks so much! but I'm still wondering why when 'acpi_backlight' was left to be the default value, systemd-backlight doesn't work at bootup? I think this might be a bug, as I see ...

**Comment by dvdhrm** [comment]
This is a kernel bug, not systemd. systemd does not care for the backlight type, it just uses what is there.
Note that there are lots of backlight issues in the kernel. Most of them have been recently solved, but especially with reverse-engineered stuff like nvidia, there're lots of issues left. I'd recommend reporting this to LKML / nouveau.

Closing this now. If you still think this is a systemd bug, please feel free to reopen.

**Comment by ghost** [comment]
thanks so much! I'm just using nvidia, but my graphic card is a little out of date, maybe this issue should be posted to nouveau, and I will keep on solving the problems, thanks!
