### ISSUE TITLE
.service File Priority

### ISSUE THREAD

**Issue by archuserr** [systemd/systemd#5822]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> v232

### Used distribution

> Arch

### In case of bug report: Expected behaviour you didn't see

> .service files in `/etc/systemd/system/` take priority over `/usr/lib/systemd/system/`

### In case of bug report: Unexpected behaviour you saw

> systemd uses the file in `/usr/lib/systemd/system/` when a file with the same name exists in `/etc/systemd/system/`

### In case of bug report: Steps to reproduce the problem

According to https://wiki.archlinux.org/index.php/Systemd, service files in `/etc/systemd/system/` take priority over the files in `/usr/lib/systemd/system/`. If that's correct, it doesn't work that way for me. 

I wanted to modify one of the stock .service files, so I `cp /usr/lib/systemd/system/systemd-journal-upload.service /etc/systemd/system/multi-user.target.wants/` and edited it. `systemctl cat` did not reflect the changes even after `systemctl daemon-reload` and `reboot`.

As a second test, I tried `touch /etc/systemd/system/multi-user.target.wants/systemd-journal-upload.service`. I expected an error from loading a blank file, but systemd successfully ran the service. The service does not run if the .service file doesn't exist in /etc/systemd/system/. 

I tried this with a second service (`systemd-networkd-wait-online.service`) and it had the same behavior.

**Comment by falconindy** [comment]
You meant to copy the file to `/etc/systemd/system`, not into the .wants directory.

**Comment by archuserr** [comment]
Thanks! I'll go learn more about that.
