### ISSUE TITLE
meson test suite failures on Debian buildds (check-help-systemd-cgtop, check-help-systemd-nspawn)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5831]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

git master

### Used distribution

Debian sid

Using git master and the meson build system on a Debian porterbox, which has a buildd like environment, the test suite fails:

```
217/229 check-help-systemd-cgtop                FAIL     0.02 s

--- command ---
/home/biebl/build/systemd/tools/meson-check-help.sh /home/biebl/build/systemd/build-deb/systemd-cgtop
--- stdout ---
Failed to determine supported controllers: No medium found
systemd-cgtop --help prints to stderr
--- stderr ---
Failed to determine supported controllers: No medium found
```
and
```
228/229 check-help-systemd-nspawn               FAIL     0.03 s

--- command ---
/home/biebl/build/systemd/tools/meson-check-help.sh /home/biebl/build/systemd/build-deb/systemd-nspawn
--- stdout ---
Failed to determine whether the unified cgroups hierarchy is used: No medium found
systemd-nspawn --help prints to stderr
--- stderr ---
Failed to determine whether the unified cgroups hierarchy is used: No medium found
-------
```

**Comment by mbiebl** [comment]
I guess this can be considered a bug in systemd-nspawn and systemd-cgtop. ```--help``` should work, regardless if cgroupfs is available or not.

**Comment by evverx** [comment]
https://github.com/systemd/systemd/pull/5801 seems to fix the issue.

**Comment by yuwata** [comment]
I guess #5801 fixes this bug. At least, rpm can be built on fedora with the patches.

**Comment by mbiebl** [comment]
@yuwata, @evverx , indeed, thanks for the pointer

**Comment by poettering** [comment]
CLosing this one as #5801 supposedly fixes this issue
