### ISSUE TITLE
unable to build using meson on mips, stuck in configuration loop

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5835]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

git master

### Used distribution

Debian sid

Trying to build systemd using meson on a Debian mips porterbox fails.
Run ```meson build``` completes successfully, but when running ```ninja -C build```, I get
```
[0/1] Regenerating build files
```
and then meson runs again, and this is repeated over and over again.

**Comment by mbiebl** [comment]
@nirbheek or @jpakkane, can you give me some hints how I can provide more useful logs to debug this further?

**Comment by mbiebl** [comment]
Using ninja -d explain, I get
```
ninja explain: output build.ninja older than most recent input meson-private/coredata.dat (1493311990 vs 1493313722)
[0/1] Regenerating build files
[meson runs]
ninja explain: output build.ninja older than most recent input meson-private/coredata.dat (1493312457 vs 1493314189)
[0/1] Regenerating build files
[meson runs]
```
and so on

**Comment by mbiebl** [comment]
I just noticed that /home is on NFS on that porterbox. Maybe that messes up the timestamps?

**Comment by mbiebl** [comment]
@nirbheek, @jpakkane my gut feeling is, that this is not a bug in systemd itself but either ninja and/or meson. What do you think?

**Comment by nirbheek** [comment]
Ninja is just reading file timestamps, so I wonder if there's an NFS setting that the tinderbox is missing somewhere. Both those files are written out by Meson, and it would be nice to figure out what the filesystem reports their timestamps as.

It might also help to try and reproduce this with a trivial test case inside an NFS mount.

**Comment by jpakkane** [comment]
Running `ninja -d explain all` makes Ninja tell why it runs each step.

**Comment by mbiebl** [comment]
@jpakkane @nirbheek 
Running with ```ninja -d explain all```, I basically get the same error message(s) as in https://github.com/systemd/systemd/issues/5835#issuecomment-297784403
```
ninja explain: output build.ninja older than most recent input meson-private/coredata.dat (1493409236 vs 1493410971)
[0/1] Regenerating build files
[...]
ninja explain: output build.ninja older than most recent input meson-private/coredata.dat (1493409305 vs 1493411040)
[0/1] Regenerating build files
[...]
                              
$ stat build.ninja meson-private/coredata.dat 
  File: 'build.ninja'
  Size: 2871567   	Blocks: 5616       IO Block: 262144 regular file
Device: 13h/19d	Inode: 54791809    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 2820/   biebl)   Gid: ( 2820/   biebl)
Access: 2017-04-28 19:54:58.283544289 +0000
Modify: 2017-04-28 19:55:05.883543860 +0000
Change: 2017-04-28 19:55:05.883543860 +0000
 Birth: -
  File: 'meson-private/coredata.dat'
  Size: 114805    	Blocks: 232        IO Block: 262144 regular file
Device: 13h/19d	Inode: 54791501    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 2820/   biebl)   Gid: ( 2820/   biebl)
Access: 2017-04-28 20:24:00.429243087 +0000
Modify: 2017-04-28 20:24:00.429243087 +0000
Change: 2017-04-28 19:55:07.390210442 +0000
 Birth: -
```

**Comment by nirbheek** [comment]
To me, this looks like python's [`os.utime`](https://docs.python.org/3/library/os.html#os.utime) didn't work correctly. 2 seconds is quite close to the amount of time it would take a slow machine to generate the `build.ninja` file.

See: https://github.com/mesonbuild/meson/blob/b48daeda1a53f0a1a218492e356186846a3abfff/mesonbuild/mesonmain.py#L180

First, we run the interpreter which does all the configuration, then we save the current time, then we generate the build files, and finally we [save the coredata and modify the mtime on it](https://github.com/mesonbuild/meson/blob/b48daeda1a53f0a1a218492e356186846a3abfff/mesonbuild/environment.py#L294). If that last step doesn't happen (or doesn't get synced to the disk), we will get that error.

Maybe we just need to add a filesync() to make it work reliably on NFS. Maybe the function is broken on MIPS. Could you please test and find out? :)

**Comment by mbiebl** [comment]
@nirbheek if you tell me what exactly I'm supposed to do, I'm happy to oblige

**Comment by nirbheek** [comment]
Run `meson`, then run `sync` (which should force a metadata write), then try `ninja`. If this doesn't work, try

`:> somefile && stat somefile && sleep 1 && python3 -c "import os, time; mtime=time.time(); os.utime("somefile", times=(mtime, mtime))" && stat somefile` 

If this doesn't change the mtime on `somefile`, that means `os.utime()` is broken.

**Comment by mbiebl** [comment]
```
(sid_mips-dchroot)biebl@minkus:~/build/systemd$ :> somefile && stat somefile && sleep 1 && python3 -c "import os, time; mtime=time.time(); os.utime('somefile', times=(mtime, mtime))" && stat somefile
  File: somefile
  Size: 0               Blocks: 0          IO Block: 262144 regular empty file
Device: 13h/19d Inode: 53877114    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 2820/   biebl)   Gid: ( 2820/   biebl)
Access: 2017-04-29 07:58:46.477763162 +0000
Modify: 2017-04-29 07:58:46.477763162 +0000
Change: 2017-04-29 07:58:46.477763162 +0000
 Birth: -
  File: somefile
  Size: 0               Blocks: 0          IO Block: 262144 regular empty file
Device: 13h/19d Inode: 53877114    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 2820/   biebl)   Gid: ( 2820/   biebl)
Access: 2017-04-29 08:27:50.804810285 +0000
Modify: 2017-04-29 08:27:50.804810285 +0000
Change: 2017-04-29 07:58:47.657763094 +0000
 Birth: -
(sid_mips-dchroot)biebl@minkus:~/build/systemd$ date
Sat Apr 29 08:28:00 UTC 2017
```
I'll close this bug report. It's clearly not a systemd issue and to me it looks like something is seriously fishy with the time setup on that porter box resp. the NFS server

**Comment by ismaelgv** [comment]
Definitely this is not a systemd issue. I've also found this behaviour on two machines (client/server) sharing a NFS mount with different date configuration. After configuring correctly NTP sync and timedatectl, this problem with meson/ninja was solved. The problem might be also related with sync/async parameters on NFS mount.
