### ISSUE TITLE
[BUG] systemd-networkd: problem with adding vlan interface to bond

### ISSUE THREAD

**Issue by nefelim4ag** [systemd/systemd#5838]
systemd: 232
### Used distribution
Debian 8.7/9
### In case of bug report: Expected behaviour you didn't see
vmbr0.260 added to bond260
### In case of bug report: Unexpected behaviour you saw
vmbr0.260: Could not join netdev: Operation not permitted
### In case of bug report: Steps to reproduce the problem
00-eth0.for.vmbr0.network:
```
[Match]
Name=eth0
[Network]
Bridge=vmbr0
```
10-vmbr0.netdev:
``` 
[NetDev]
Name=vmbr0
Kind=bridge
```
11-vmbr0.vlans.network:
```
[Match]
Name=vmbr0
[Network]
VLAN=vmbr0.260
```
12-vmbr0.260.netdev:
```
[NetDev]
Name=vmbr0.260
Kind=vlan
[VLAN]
Id=260
```
30-bond260.netdev:
```
[NetDev]
Name=bond260
Kind=bond
[Bond]
Mode=balance-alb
MIIMonitorSec=200ms
UpDelaySec=400ms
DownDelaySec=400ms
PrimaryReselectPolicy=better
```
40-vmbr0.260.for.bond260.network:
```
[Match]
Name=vmbr0.260
[Network]
Bond=bond260
```

Logs:
```
systemd-networkd[1733]: vmbr0.260: Could not join netdev: Operation not permitted
systemd-networkd[1733]: vmbr0.260: Failed
```

If i do:
```
# ip l set vmbr0.260 down
# systemctl restart systemd-networkd
```
networkd can add vlan interface to bond and all working good.

**Comment by nefelim4ag** [comment]
JFYI:
as ifenslave can successful add such interface to bond, i read the sources of ifenslave
```
                [ "$VERBOSE" = 1 ] && echo "Adding slave $slave to master $master"
                ip link set "$slave" down
                echo "+$slave" >"/sys/class/net/$master/bonding/slaves" || error "$slave: could not add interface"
```
So i think problem is that systemd-networkd didn't disable interface before adding that to bond

**Comment by rewbycraft** [comment]
As someone who is facing the same problem, I can second the idea that systemd-networkd didn't down the interface before trying to add it to the bond.

My dmesg contains the following lines:
````
[   11.589433] bond1: vlan9 is up - this may be due to an out of date ifenslave
[   11.590520] bond1: vlan8 is up - this may be due to an out of date ifenslave
````
(vlan9 and vlan8 are the vlan interfaces I'm trying to bond. My configuration is very similar to that of @Nefelim4ag )
