### ISSUE TITLE
Timer unit stops after a while

### ISSUE THREAD

**Issue by ahkok** [systemd/systemd#5840]
### Submission type

  - [X] Bug report

### systemd version the issue has been seen with

> v231

### Used distribution

> clearlinux (mostly stock/unmodified)

### In case of bug report: Expected behaviour you didn't see

We have a timer unit that triggers software updates automatically:

```
[Unit]
Description=Automatically Install Software Updates
Documentation=man:swupd_update

[Timer]
OnBootSec=6h
OnUnitActiveSec=6h
AccuracySec=900
RandomizedDelaySec=7200

[Install]
WantedBy=multi-user.target
```

This works great, except that after a while it just stops updating altogether:

```
# date
Thu Apr 27 11:28:00 PDT 2017
# systemctl list-timers --all
NEXT                         LEFT          LAST                         PASSED       UNIT                         ACTIVATES
n/a                          n/a           n/a                          n/a          swupd-update.timer           swupd-update.service
```

but the timer worked fine from boot time:

```
$ uptime
11:25am  up 20 days  1:21,  1 user,  load average: 0.02, 0.02, 0.00
```

so the system was up for 20 days, but the last update was run:

```
# systemctl status swupd-update.timer
● swupd-update.timer - Automatically Install Software Updates
   Loaded: loaded (/usr/lib/systemd/system/swupd-update.timer; enabled; vendor preset: disabled)
   Active: active (elapsed) since Fri 2017-04-07 10:04:07 PDT; 2 weeks 6 days ago
     Docs: man:swupd_update
```
Unsure, but I can see:

```
# ls -ld /usr/share/clear/version
-rw-r--r-- 1 root root 5 Apr 13 09:35 /usr/share/clear/version
```

this was the last time an update actually ran, which is 6 days after the system booted. So, for the first week, this timer ran OK - after that it stopped.

I've done a poll of about 10 clearlinux users with systems between 5 and 20 days uptime, and the failure rate of the timer unit is about half.

**Comment by poettering** [comment]
Normally the timer should be restarted the instant the service it activates terminates again. Hence: what's the precise state of the service that is activated when this happens? What does "systemctl status swupd-update.service" say about your srevice?

**Comment by ahkok** [comment]
Please bear with me, it may take me 3 weeks before I can reproduce this :(

**Comment by ahkok** [comment]
```
clear@clear-clr-nuc ~/test $ sudo systemctl status swupd-update.service
● swupd-update.service - Update Software content
   Loaded: loaded (/usr/lib/systemd/system/swupd-update.service; static; vendor preset: disabled)
   Active: inactive (dead)

clear@clear-clr-nuc ~/test $ sudo systemctl status swupd-update.timer
● swupd-update.timer - Automatically Install Software Updates
   Loaded: loaded (/usr/lib/systemd/system/swupd-update.timer; disabled; vendor preset: disabled)
   Active: active (elapsed) since Mon 2017-04-24 16:06:28 PDT; 1 weeks 1 days ago
     Docs: man:swupd_update

Apr 24 16:06:28 clear-clr-nuc systemd[1]: swupd-update.timer: Adding 1h 23min 36.925993s random time.
Apr 24 16:06:28 clear-clr-nuc systemd[1]: Started Automatically Install Software Updates.
Apr 24 16:07:29 clear-clr-nuc systemd[1]: swupd-update.timer: Adding 1h 43min 57.896567s random time.
Apr 24 16:07:29 clear-clr-nuc systemd[1]: swupd-update.timer: Adding 1h 6min 24.698462s random time.
Apr 24 16:10:36 clear-clr-nuc systemd[1]: swupd-update.timer: Adding 1h 22min 38.988495s random time.

clear@clear-clr-nuc ~/test $ sudo systemctl list-timers --all
NEXT                         LEFT       LAST                         PASSED  UNIT                         ACTIVATES
Wed 2017-05-03 16:26:16 PDT  38min left Tue 2017-05-02 16:26:16 PDT  23h ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Thu 2017-05-04 00:00:00 PDT  8h left    Wed 2017-05-03 00:00:16 PDT  15h ago hprobe.timer                 hprobe.service
n/a                          n/a        n/a                          n/a     swupd-update.timer           swupd-update.service

3 timers listed.
```

The added lines of random time added are suspicious, to say the least.

**Comment by ahkok** [comment]
So we noted that in the above report, the unit shows up as `disabled`, however the enabled symlinks are actually present, and have been enabled since december (as verified through `stat`)

It appears that somehow systemd incorrectly assumes that the unit is `disabled` here even though it isn't?

**Comment by ahkok** [comment]
Is there a relationship between the exit code of the service, and the functionality of the timer unit?

**Comment by VelorumS** [comment]
I've got a target that should be activated by a timer:

```
 11:42:11 up 35 days

NEXT                         LEFT               LAST                         PASSED             UNIT                    ACTIVATES
Wed 2017-12-20 10:03:49 CET  1 weeks 0 days ago Wed 2017-12-20 10:04:11 CET  1 weeks 0 days ago remote-update.timer remote-update.target

● remote-update.target - remote update
   Loaded: loaded (/usr/lib/systemd/user/remote-update.target; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2017-12-20 10:03:19 CET; 1 weeks 0 days ago
```

But it's stuck for a week already.

If I do `daemon-reload`, it goes to `n/a`, and then to somewhere around the boot date:

```
NEXT LEFT LAST                         PASSED   UNIT                    ACTIVATES
n/a  n/a  Wed 2017-12-27 11:43:17 CET  6min ago remote-update.timer remote-update.target
$ systemctl --user restart remote-update.timer
NEXT                         LEFT                LAST                         PASSED   UNIT                    ACTIVATES
Wed 2017-11-22 08:23:52 CET  1 months 4 days ago Wed 2017-12-27 11:49:27 CET  5min ago remote-update.timer remote-update.target
```

Then I've rebooted, and it's fine again.

**Comment by gongzhitaao** [comment]
The same thing happens here.  I used `systemctrl` with `mbsync` in replace of `cron` jobs.  The following image shows that the timer stops (no idea why) about an hour ago.

![image](https://user-images.githubusercontent.com/704995/59386712-03e69a80-8d2d-11e9-9c7b-09fd0ee954de.png)

**Comment by It4lik** [comment]
I have the same problem here, but it's very hard to find any clues on what is going on. 

I have two custom systemd timers on a machine. 
* one is dedicated to a backup service, run once everyday. **It works great.**
* the other one is dedicated to some random webapp on the machine (executing queued jobs), and runs every 5 minutes (no comment...). **This timer fails.**

The backup timer simply call a shell script. 
The second timer executes a rather ugly command (runs a PHP script in a given container) like `/usr/bin/docker exec CT_NAME /path/to/script.php LOTS_OF_ARGS`. 

Now that I noticed this behaviour, I'll try to get indicators from the app side in order to know exactly when does the timer stopped to see if this correlates to something else.

I suspect this may be related to some ugly characters on the `ExecStart=` line. I'll try to wrap the `ExecStart` command in a shell script if ever it fails again.

**Comment by dimas** [comment]
@ahkok, hi, have you found any solution in the end?
We have the very same problem as you describe but with systemd v239.

It does not look like other commenters here experiencing exactly the same issue judging from their timers either do not work at all or being in `active (waiting)` state but in our case the timer after first working properly goes into `active (elapsed)` and never fires again. Very much like in your case.

Given it happens with an embedded device which is not super easy to get into to fix things, it is worrying.

So have you found any workarounds by any chance or do you have any clues on what is happening?

Thanks

**Comment by izapper** [comment]
Dear,

 

great to hear, that this problem have much of people.
Sorry, but i did not have a solution for this problem of stopping timer or service.

So actually i do not use timer any more i use only the .service, but also this service

stops after a day or after some hours. I did not figure out why. For me and many

other no experts this is very difficult to find a solution that works every time.

 

I also thinking of a further service that works like a watchdog to look every x-minutes
if the main service or main timer is still working and if not (maybe by getting an failure

from exit code) restarting the service  to continue. But i think if this happens its just

a dirty way to keep main timer or main service still working, but did not solve the basic

problem.

 

Hope we find others, they find the problem and a not so complicate solution to get

timer or service working all the time. This raspberry pi has soo much possibilities i

would not miss, but programming a Arduino is much simpler and works 100% all the time.

Lets see other user if they find out a solution or the problem of stopping,

 

let stay in contact

thank you and wish you all the best and great projects

Thomas from south germany

 

Gesendet: Donnerstag, 03. Oktober 2019 um 08:58 Uhr
Von: "Dmitry Andrianov" <notifications@github.com>
An: systemd/systemd <systemd@noreply.github.com>
Cc: izapper <izapper@gmx.net>, Comment <comment@noreply.github.com>
Betreff: Re: [systemd/systemd] Timer unit stops after a while (#5840)


@ahkok, hi, have you found any solution in the end?
We have the very same problem as you describe but with systemd v239.

It does not look like other commenters here experiencing exactly the same issue judging from their timers either do not work at all or being in active (waiting) state but in our case the timer after first working properly goes into active (elapsed) and never fires again. Very much like in your case.

Given it happens with an embedded device which is not super easy to get into to fix things, it is worrying.

So have you found any workarounds by any chance or do you have any clues on what is happening?

Thanks

**Comment by ahkok** [comment]
>  hi, have you found any solution in the end?

I maintain `systemd` for `Clear Linux OS` which aggressively moves to new versions. We have not encountered the issue for a while. While I can't confirm the issue is fixed, since it wasn't ever root caused, I would suspect that newer versions have resolved this problem.

**Comment by dimas** [comment]
Thanks for the update. So there is not clear solution yet.

JFYI, some result of googling today, maybe one will find this useful.
1. There is a similar bug report here https://github.com/systemd/systemd/issues/6680 and couple of people there said that this did solve issue for them: https://serverfault.com/questions/775246/systemd-timer-not-starting-its-service-unit/775363#775363 - I haven't tried this myself as we decided to move away - see below.
2. In the same issue there is a comment from @poettering that effectively says that `OnUnitActiveSec` with a `oneshot` service is not even expected to work. Honestly, I do not know how to read it because the internet is full of configurations like that and it somehow works for people. Also, our units do work with a very rare exceptions
https://github.com/systemd/systemd/issues/6680#issuecomment-326228938

Either way, without a clear steering from official systemd guides on what to do and with a buggy behaviour we are observing now, we are leaning towards not using `OnUnitActiveSec` at all and convert the timer to use `OnCalendar` + `RandomizedDelaySec` because this approach feels more robust - it should keep firing regardless of what is happening with the service unit.

Good luck everyone

**Comment by dresken** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1764908
