### ISSUE TITLE
systemd-networkd-wait-online is always timing out for PPPoE

### ISSUE THREAD

**Issue by software-artificer** [systemd/systemd#5841]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 233
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN default-hierarchy=hybrid

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

Interface is up:
```
# ip a show dev ppp0
5: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 3
    link/ppp 
    inet xxx.xxx.xxx.xxx peer yyy.yyy.yyy.yyy/zz scope global ppp0
       valid_lft forever preferred_lft forever
```
running:

```
# systemd-networkd-wait-online -i ppp0 --timeout 60
```
detects that ppp0 is up and reports success.

### In case of bug report: Unexpected behaviour you saw

```
 # /usr/lib/systemd/systemd-networkd-wait-online -i ppp0 --timeout 60
ignoring: wlp3s0
ignoring: enp0s1
Event loop failed: Connection timed out
```

### In case of bug report: Steps to reproduce the problem

Simply set-up PPPoE connection and execute `systemd-networkd-wait-online` with PPP interface and see timeout.

**Comment by software-artificer** [comment]
## Update:
After a bit more debugging it turns out that the problem is not so much in PPPoE interface itself, but rather in the fact that PPPoE interface has no IPv6 address associated with that.

It seems that it is related to #2713

**Comment by poettering** [comment]
Do you have ipv6 disabled entirely? or just on the iface in question?

**Comment by software-artificer** [comment]
I don't have IPv6 disabled at all. It is just that my provider does not provide an IPv6 and PPPoE is not automatically receiving link-local address, even if I've tried to set LinkLocalAddressing=ipv6

**Comment by software-artificer** [comment]
@poettering: any news on that? I would really like to get this moving. Thanks.

**Comment by ssahani** [comment]
@filakhtov Could we close this.

**Comment by software-artificer** [comment]
@ssahani, yes, sure, thanks! Fixed by https://github.com/systemd/systemd/pull/7012
