### ISSUE TITLE
inconsistent detection of python scripts, fails to find tools/xml_helper.py in non-UTF8 locale

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5855]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

git master

### Used distribution

Debian sid

Contrary to what 86b3ca7a667baef407ccfa28166638ed0e64c26c says, mosts python scripts in tools/ are marked as executable.
This means, ```find_program``` acts on them differently
```
Program generate-gperfs.py found: YES (/usr/bin/python3 /home/michael/git/systemd/src/basic/generate-gperfs.py)
...
Program tools/make-directive-index.py found: YES (/home/michael/git/systemd/tools/make-directive-index.py)
```
If a python script doesn't have the executable bit set, meson will try to detect the interpreter. In case of tools/xml_helper.py this can be problematic if a non-UTF8 locale is used, as that file contains unicode characters and so the autodetection fails:

```
$ export LANG=C
$ meson build
...
Program tools/make-man-index.py found: YES (/home/michael/git/systemd/tools/make-man-index.py)
Program tools/xml_helper.py found: NO

Meson encountered an error in file meson.build, line 2253, column 0:
Program "tools/xml_helper.py" not found.
```

Since all our python scripts have a proper python3 shebang, I don't see a benefit of letting meson try to autodetect them and would simply mark them all as executables. This would have the added benefit, that we don't fail for non-UTF8 locales

**Comment by keszybz** [comment]
My reasoning was that if meson autodetects the script, it'll use the same python interpreter that is used to run meson itself. But actually I don't even know if this is true. So the proposed change sounds reasonable.

**Comment by nirbheek** [comment]
> My reasoning was that if meson autodetects the script, it'll use the same python interpreter that is used to run meson itself. But actually I don't even know if this is true. So the proposed change sounds reasonable.

That is only done on Windows for Python3 scripts. On Linux, we assume that the shebang is correct and let `exec()` handle things.
