### ISSUE TITLE
keyboard and mouse error after compiling and "make install" systemd

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5858]
No mouse and no keyboard detected after compiling and "make install" systemd. I tried with USB and PS/2 keyboard, none of these works.

Maybe I forgot to install some additional development package which is required for systemd, but I don't know which is responsible for basic keyboard&mouse handling.

**Comment by poettering** [comment]
systemd does not provide mouse or keyboard driver support. That's between your kernel and your distribution. Please contact your distribution for further help. Thank you.
