### ISSUE TITLE
machinectl pull-raw / import-raw fails: No space left on device

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#5859]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v231, v232, v233

### Used distribution

Tested on Fedora 25 and Debian sid.

Trying to run ```machinectl import-raw or pull-raw``` fails.
I pulled the image from https://cloud-images.ubuntu.com/zesty/current/zesty-server-cloudimg-amd64.img and then ran

```
# machinectl import-raw /home/michael/zesty-server-cloudimg-amd64.img
Enqueued transfer job 2. Press C-c to continue download in background.
Importing '/home/michael/zesty-server-cloudimg-amd64.img', saving as 'zesty-server-cloudimg-amd64'.
Imported 0%.
Imported 3%.
Imported 6%.
Imported 10%.
Imported 12%.
Imported 15%.
Imported 18%.
Imported 21%.
Imported 24%.
Imported 27%.
Imported 30%.
Imported 33%.
Imported 36%.
Imported 39%.
Imported 42%.
Imported 45%.
Imported 48%.
Imported 51%.
Imported 54%.
Imported 57%.
Imported 60%.
Imported 63%.
Imported 66%.
Imported 69%.
Imported 72%.
Imported 75%.
Grew /var/lib/machines btrfs loopback file system to 1021.0M.
Imported 79%.
Imported 82%.
Imported 85%.
Imported 88%.
Imported 91%.
Imported 94%.
Imported 97%.
Unpacking QCOW2 file.
Failed to convert qcow2 image: No space left on device
Exiting.

# qemu-img info /var/lib/machines.raw 
image: /var/lib/machines.raw
file format: raw
virtual size: 1.0G (1070678016 bytes)
disk size: 955M

# qemu-img info /home/michael/zesty-server-cloudimg-amd64.img 
image: /home/michael/zesty-server-cloudimg-amd64.img
file format: qcow2
virtual size: 2.2G (2361393152 bytes)
disk size: 329M
cluster_size: 65536
Format specific information:
    compat: 0.10
    refcount bits: 16
```

Apparently, machinectl creates a filesystem which is too small and then fails with a rather vague error message. My / filesystem has plenty of space free. I had to fiddle with ```qemu-img resize``` to resize /var/lib/machines.raw, ```btrfs filesystem resize``` to grow the file system and ```machinectl set-limit```.
After that I was finally able to import the image.
This is a total failure from a user experience POV.
First of all, the error message was completely misleading (after all I have plenty of space available) and more importantly, machinectl shouldn't have failed in the first place and created /var/lib/machines big enough or grow it dynamically automatically.

**Comment by mbiebl** [comment]
There is also this downstream bug report: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1510511

**Comment by dongsupark** [comment]
I have been seeing this issue since more than a year.
Today I managed to fix a part of the issue. Please see https://github.com/systemd/systemd/pull/10153.
Though with that PR applied, import will work still only for raw images, not for qcow2 images mentioned in this issue.

**Comment by poettering** [comment]
So we dropped the automatic btrfs loopback file support in machined a while back. Let's close this hence.
