### ISSUE TITLE
RFE: optionally require WATCHDOG=1 messages during the service start-up phase too

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#5868]
### Submission type

  - [X] Request for enhancement (RFE)

### systemd version the issue has been seen with

231

### Used distribution

Fedora (but relevant everywhere)

### In case of bug report: Expected behaviour you didn't see

A mariadb.service file with Type=notify has been written for a while. Stumbling back onto an old bug https://jira.mariadb.org/browse/MDEV-9202 we have a problem that in some cases involving large synchronisation TimeoutStartSec isn't sufficient and a sane default value can't be predicted as the size of a users data can vary greatly. A disabled value 0 isn't really sane either as stalls due to programming errors are still possible.

Can the timeouts be measured from the last sd_notify message? Pushing STATUS= messages is easy enough.

**Comment by mbiebl** [comment]
See the recent discussion on the mailing list
https://lists.freedesktop.org/archives/systemd-devel/2017-April/038647.html

**Comment by grooverdan** [comment]
WATCHDOG=1 works for me for startup and hopefully shutdown too. I'll look to see if any other complains in that thread need to be addressed on the MariaDB/MySQL side. Apologies for not checking the list first.

**Comment by poettering** [comment]
Yeah, as discussed on the ML I think it would make sense to permit WATCHDOG=1 during startup phase. REnaming this issue to becomean RFE for that

**Comment by grooverdan** [comment]
Would it make sense to do this in the shutdown phase as well?

**Comment by poettering** [comment]
Sure. Absolutely. If somebody works on adding this for startup it would be trivial to add it for shutdown too at yhe same time
