### ISSUE TITLE
RFE: machinectl systemd-nspawn: unable to get stdout, stderr and return code

### ISSUE THREAD

**Issue by jscotka** [systemd/systemd#5879]
### Submission type

  - [ X] Request for enhancement (RFE)

### systemd version the issue has been seen with
systemd-231-14.fc25.x86_64 (same in upstream)

## Steps:
actually there does not exist any way how to get
  * return code of command
   * stdout
   * stderr
   * allow also runnig commands at background

my actual ugly solution: 
```
# machinectl shell root@{machine} /bin/bash -c "({comm})>{pin}/stdout 2>{pin}/stderr; echo $?>{pin}/retcode; sleep 2
# bash -c "cat {chroot}{pin}/stdout; cat {chroot}{pin}/stderr > /dev/stderr; exit `cat {chroot}{pin}/retcode`"'
{pin} = relative path to file (in changeroot env)
{chroot} = chroot directory of machine
{comm} = command to run
```

so actual solution is to store all data inside nspawn to files, and then on host paste them to proper streams and exit proper RC

it is bad and ugly. and would be nice to have some direct solution (via machine shell, or some other option, or passing more argumets, to have these streams on proper paces and proper RC of command inside)

**Comment by poettering** [comment]
"machinectl shell" is an interactive tool, it involves allocating a tty and everything, which make it hard to integrate things into a shell pipline.

Please use systemd-run instead in that case. This is documented in the "machinectl shell" documentation btw.

Also, please make sure to run a v233 for this, as only then systemd-run will propagate the exit code.

**Comment by jscotka** [comment]
Hi @poettering,
Yes. I've read this doc for machine shell and thats why I wrote this issue, because ```systemd-run``` has worse behavior than ```machinectl shell```
It seems that my description was not clear, so I will write it again.
I need some tool what provides me:
 - **return code of command**
 - **stdout of command**
 - **stderr of command**
 - **allow run commands at backgroud and let them running.**

### ```machinectl shell``` GOOD:
 - provides stdour/stderr directly (but mixed together this is BAD)
 - able to run commands at backgroud and let them running

### ```machinectl shell``` BAD:
 - does not provide return code
 - mixed stdout/stderr together

### ```systemd-run ``` GOOD:
 - provides return code

### ```systemd-run ``` BAD:
 - does not provide stdour/stderr directly
 - allow stdour/stderr via journal, but mixed stdout/stderr togetger (unable to differenciate)
 - possible to use just in case journald is running (otherwise much worse)
 - does not allow to run general command at background

## conclusion
**Both solution does not provide what I want, but machinectl shell is winner**

**Comment by lnykryn** [comment]
Let's reopen this for reevaluation. Reason for RFE was a use-case where I would like to use nspawn as a part of test suite. I would like to have some minimal system booted without any unnecessary packages and run some commands from the tests scripts that would be installed on the hosts.

So from the hosts we want to run some commands inside the container and get the output and return code.
So let's say that I am writing a test suite for apache and I would like to run "apachectl configtest" inside the container but I would like to do it from the host and get the output.

My original recommendation was to run systemd-run --wait. There you will get return code and name of the unit, so in theory you can get all of those data you need. But this approach has two problems. The unit is short-lived, so again we have the problem that in journal we might not have the information about unit and also I think that you can't distinguish if the message was sent to STDOUT or STDERR, which is quite impractical especially for test suites.

**Comment by poettering** [comment]
I figure we can close this as systemd-run can now do everything requested by @lnykryn , with the "--pipe" option, see 5dca7739e862eae50a162b0cc7f8613f7fd33c81.
