### ISSUE TITLE
systemd-netword - [Address] address not added to table

### ISSUE THREAD

**Issue by zktech** [systemd/systemd#5887]
### Submission type

  - [1] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 2.33

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> coreos

### In case of bug report: Expected behaviour you didn't see
> [Address]
>  Address=192.168.116.21/24
>  Table=10
>The address should be bound to the NIC and then a route entry should be entered into the ip table 10 and no route should be added to ip table 0

### In case of bug report: Unexpected behaviour you saw

> Table=X is being ignored and a route is added to ip table 0. 

### In case of bug report: Steps to reproduce the problem

>    [Address]
>      Address=192.168.116.21/24
>      Table=10

**Comment by ssahani** [comment]
the `Table=` goes in [Route] section not in address section.

**Comment by zktech** [comment]
Susant
  
 Much thanks for your reply and insights.
  
 This is more detail on the issue. We need the address routes added to a table #.
 The problem is that when you place an address using the [Address] or [Network] blocks there is a route entry automatically added in the 0 table example  (192.168.116.0/24 dev vlan60  proto kernel  scope link  src 192.168.116.21)
  
 We need that entry to be added to a predefined table and right now there is no way to stop that entry being added to the ip route table 0. As soon as you specify an address the entry is added. 
  
 This could be corrected in two different ways. Add the ability to specify the Table=# and Proto values into the [Address] blocks, or add a flag to the address block that would stop the addition of the route entry into  the zero table. This would allow us to do all entries in [Route] blocks and not place an unwanted entry into the 0 ip route table.  
  
 Also please note we have been bumping up against issues with [Route] blocks not correctly placing entries and supporting needed values. I have opened bug reports for these as well.
  
 Thanks

Bryant Zimmerman (ZK Tech Inc.)
616-855-1030 Ext. 2003
  

----------------------------------------

**Comment by zktech** [comment]
I have also been fighting to get ip rule entries to add using systemd. Right now we are having to resort to oneshot scripts. 

Thanks

Bryant Zimmerman (ZK Tech Inc.)
616-855-1030 Ext. 2003

**Comment by ssahani** [comment]
If I get this right could you give a example how to add addresses to a table  via `ip` command  and show in the output.

**Comment by ssahani** [comment]
I am not sure how this can be done. I think we can close this.
