### ISSUE TITLE
systemd-networkd - [Route] Source IP not applied

### ISSUE THREAD

**Issue by zktech** [systemd/systemd#5888]
### Submission type

  - [1 ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> coreos

### In case of bug report: Expected behaviour you didn't see

>   [Route]
>      Destination=192.168.116.0/24
>      Source=192.168.116.21/32
>      Table=1
>      route should have a value in src 192.168.116.21
>
>  [Route]
>      Gateway=192.168.116.250
>      Destination=0.0.0.0/0
>      Source=192.168.116.21/32
>      Table=1
>      route should have a value in src 192.168.116.21

### In case of bug report: Unexpected behaviour you saw

> Neither of the routes end up with a value in the src position. 

### In case of bug report: Steps to reproduce the problem

> >   [Route]
>      Destination=192.168.116.0/24
>      Source=192.168.116.21/32
>      Table=1
>
>  [Route]
>      Gateway=192.168.116.250
>      Destination=0.0.0.0/0
>      Source=192.168.116.21/32
>      Table=1
> Neither route gets a src value applied causing issues.
> There also needs to be a way to set the dev value from the [Route] when setting outside of a unit file without a [Match] directive routes get ignored and are not run.

**Comment by poettering** [comment]
@ssahani something for you?

**Comment by ssahani** [comment]
Could you please write the ip route which does the same thing ? 
might be similar  to https://github.com/systemd/systemd/issues/5882

**Comment by grawity** [comment]
@zktech The equivalent of src value in `ip route` is actually PreferredSource=, have you tried that?

(Source= in networkd corresponds to `from`, which is used for source-based routing – i.e. where the route is selected _based on_ source&destination. It only works with IPv6.)

**Comment by poettering** [comment]
Let's close this due to lack of response.
