### ISSUE TITLE
systemd-networkd - [Route] specify proto "value"

### ISSUE THREAD

**Issue by zktech** [systemd/systemd#5889]
### Submission type

  - [ ] Bug report
  - [1] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> coreos

### In case of bug report: Expected behaviour you didn't see
> [Route]
>      Destination=192.168.116.0/24
>      Source=192.168.116.21/32
>      Proto=Kernel
>      Table=1
> The value for proto would be set to kernel
### In case of bug report: Unexpected behavior you saw

> There appears to be no support for setting the proto value

### In case of bug report: Steps to reproduce the problem

> See expected behavior. The ability to set the proto value appears to be completely missing. 
> All possible values should be available from both the [Route] and [Address] directives

**Comment by ssahani** [comment]
fix is waiting on #5890 .

**Comment by keszybz** [comment]
@zktech please see https://github.com/systemd/systemd/pull/5890/files#r115106408. For some reason github seems to ignore your nick there.
