### ISSUE TITLE
systemd memory leak

### ISSUE THREAD

**Issue by andreiiar** [systemd/systemd#5896]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Debian 9

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> Memory for the process is too high and continues to increase (forever)

```
  RSS COMMAND
341952 /lib/systemd/systemd --system --deserialize 18
```

### In case of bug report: Steps to reproduce the problem

> Unknown

**Comment by poettering** [comment]
Sorry, but "top" is not suitable for finding memory leaks. Please use a tool such as valgrind's memory leak finder or any other tool for that purpose, but top's RSS is highly misleading, as it doesn't account for allocation caches and suchlike. For example, in systemd we make use of allocation caches for all our hash tables which we use heavily, and are not leaked.

I will close this bug for now, please feel invited to reopen this if you can find actual leaks with proper tools. Thank you for your understanding.
