### ISSUE TITLE
[BUG] systemd-networkd ignore LinkLocalAddressing=no

### ISSUE THREAD

**Issue by nefelim4ag** [systemd/systemd#5898]
### Submission type
Bug report
### systemd version the issue has been seen with
systemd 232
### Used distribution
Debian 8.7/9
### In case of bug report: Expected behaviour you didn't see
systemd will not set IPv6LL Address
### In case of bug report: Unexpected behaviour you saw
systemd assign IPv6LL Address
### In case of bug report: Steps to reproduce the problem
```
# 00-eth0.network
[Match]
Name=eth3

[Link]
MTUBytes=9014

[Network]
LinkLocalAddressing=no
VLAN=eth3.260
```

```
# 05-eth3.260.network
[Match]
Name=eth3.260

[Network]
LinkLocalAddressing=no
Bond=bond260
```

Both interfaces get IPv6LL on every reboot, if i try globally disable IPv6LL Globaly
```
# 00-disable.IPv6LL.network
[Network]
LinkLocalAddressing=no
```
It's work's but then no one interface configured

Thanks

**Comment by poettering** [comment]
this suggests that the two .network files aren't applied correctly. Does "networkctl status -a" show that they are applied correctly? i.e. the "Network File:" line needs to show that they are applied.

**Comment by nefelim4ag** [comment]
Sorry, at now i don't have resources and servers to continue push info for that issues, so i close that for now.
