### ISSUE TITLE
Predictable device names

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#590]
udev has predictable network interface names which made me thought that it could be useful to have this also for other devices like hard disk drives and optical drives. For example on my system I have a hard disk drive (sda) and 4 card readers (sdb - sde). If I now plug in an usb stick it gets registered as sdf but if the usb stick was already plugged in at booting it gets registered as sdb which shifts then the card readers one letter up (sdc - sdf).

**Comment by mbiebl** [comment]
you want /dev/disk/by-*/ created by /lib/udev/rules.d/60-persistent-storage.rules
