### ISSUE TITLE
udev event timeout counts time spent in system suspend

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#5903]
Submission type: Bug report

Systemd version the issue has been seen with: git 6cb484cc06

Used distribution: Fedora 25

### In case of bug report: Expected behaviour you didn't see

udev event timeout should use CLOCK_MONOTONIC, so that it does not counnt time spend in system suspend.

### In case of bug report: Unexpected behaviour you saw

udev event timeout uses CLOCK_BOOTTIME, which counts time spent in system suspend:

        (void) sd_event_add_time(e, &event->timeout_warning, clock_boottime_or_monotonic(),
                                 usec + arg_event_timeout_warn_usec, USEC_PER_SEC, on_event_timeout_warning, event);

        (void) sd_event_add_time(e, &event->timeout, clock_boottime_or_monotonic(),
                                 usec + arg_event_timeout_usec, USEC_PER_SEC, on_event_timeout, event);

### In case of bug report: Steps to reproduce the problem

I have a sporadic bug where some udev events time out around system suspend, which breaks stuff.  Specifically udisks loses lots of information about disk devices.  Running `udevadm trigger` effectively re-runs the events and fixes udisks.

https://unix.stackexchange.com/questions/347085/udisks-smart-apm-stopped-working

I am able to reproduce the event timeouts by

1. running `udevadm trigger` a few times in quick succession
2. `systemctl suspend`
3. Wait 180 seconds before waking the system.

[If anyone is wondering why I originally got udev events triggered just before the suspend - it's because of a custom suspend script I have.  Described [here](https://unix.stackexchange.com/questions/347085/udisks-smart-apm-stopped-working)]

---

May 06 11:25:17 alan-laptop systemd-udevd[640]: seq 30642 '/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sda/sda5' killed

May 06 11:25:17 alan-laptop systemd-udevd[640]: seq 30642 '/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sda/sda5' is taking a long time

May 06 11:25:18 alan-laptop systemd-udevd[640]: worker [6387] terminated by signal 9 (Killed)
May 06 11:25:18 alan-laptop systemd-udevd[640]: worker [6387] failed while handling '/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/b
lock/sda/sda5'

**Comment by poettering** [comment]
Fix waiting in #6198.
