### ISSUE TITLE
systemd-bus-proxyd.service has no ExecReload

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#591]
I was quite surprised to discover that the systemd-bus-proxyd services have no `ExecReload=` directive. Apparently the only way to reload it is to call `org.freedesktop.DBus.ReloadConfig`.

`busctl --system call …` cannot be used because the service does not own the `org.freedesktop.DBus` name on the kernel bus. I suppose this is proper since multiple proxies can exist.

`busctl --address=unix:path=/run/dbus/system_bus_socket call …` cannot be used because it fails with `Access denied.` Strace shows that the error description is `Client tried to send a message other than Hello without being registered.` I think this means `busctl --address` expects a non-bus peer, because I've had the same trouble with `gdbus call -a`.

`env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket busctl --user call …` can be used, but feels like a terrible hack.

`dbus-send --system …` can be used, but is an external tool.

`gdbus call -y …` can be used, but is an external tool.

Is there a way to get busctl to print the errors without having to use strace?
Does systemd-bus-proxyd reload the policy on its own when it changes, like dbus-daemon does?

Maybe systemd-bus-proxyd should just reload on `SIGHUP`. I don't think there's a way to use a DBus call in ExecReload since the unit doesn't know the address used and the service's socket isn't passed to ExecReload.

**Comment by dvdhrm** [comment]
Indeed, the `--address` option is pretty useless if you want to connect to a bus. Never looked at this in detail. But I really think it just lacks a call to `sd_bus_set_bus_client(b, true)`. I cannot imagine a use-case where it makes sense to use `busctl` as server.

Leaving this to Lennart to comment on, as he wrote it.

Regardless: The thing about re-loading legacy config is that we want it to be fully compatible to dbus-daemon. We don't want to introduce an additional way to reload the configuration. It should be the exact same call as for dbus-daemon. Right now, this is `dbus-send`, which works for both. If we convert that to `busctl`, we should use `--address` (or the env-var you posted).
If we start using SIGHUP and friends, then we still need the fallback for the dbus-daemon case. Thus, we end up with two calls instead of one.

IMO, we should just fix `--address`..

**Comment by heftig** [comment]
Unlike kdbus, DBus over sockets also knows the busless case (pid1 w/o kdbus even makes use of this in form of the private socket). If you change `--address` to behave as a bus client, you would break communicating with these sockets.

Probing for a bus and falling back to busless would be an option, but maybe the peer won't expect this and terminate the connection.

ExecReload would still be nice to have if just to trigger manually. dbus-daemon also reacts to SIGHUP.

**Comment by dvdhrm** [comment]
> Unlike kdbus, DBus over sockets also knows the busless case (pid1 w/o kdbus even makes use of this in form of the private socket). If you change --address to behave as a bus client, you would break communicating with these sockets.

Indeed. It's a bit unfortunate that we cannot distinguish both cases in the 'address' format. I wonder why there is no `bus={true,false}` key in there.
Anyway, that leaves us with the env-variable or adding `--client` command-line option.

> ExecReload would still be nice to have if just to trigger manually. dbus-daemon also reacts to SIGHUP.

Ok, that I can agree on. For debugging, it seems like a nice option.

**Comment by heftig** [comment]
Arch has been relying on dbus-daemon automatically reloading itself when the configuration (services or policies) changed.

With kdbus, this requires reloading systemd (so the busnames and services get regenerated) and reloading the bus-proxy (so the policies get reloaded). I expect we'll have to:
- Reload pid1 for packages installing system units or DBus system services. This can be done via `systemctl daemon-reload`.
- Reload the system bus-proxy for packages installing DBus system policies. This can be done via dbus-send or gdbus, but it would be nicer if `systemctl reload systemd-bus-proxyd` worked.
- Reload all systemd user instances for packages installing user units or DBus session services. This can be done via `pkill -HUP -f '^/usr/lib/systemd/systemd --user'`, but maybe there is a better way. I wish I had something like `systemctl --global daemon-reload`.
- Reload all user bus-proxies for packages installing DBus session policies. I'm not sure how to do this. If the bus proxy would reload on SIGHUP this could be done via pkill, too. I wish I had something like `systemctl --global reload systemd-bus-proxyd`.

By the way, `systemctl --global` in combination with non-enable/disable commands is accepted but fails with a DBus error.

Perhaps loginctl could be extended to broadcast commands to active systemd user instances.

**Comment by poettering** [comment]
Adding busctl --bus-client makes a lot of sense to me.

Adding reload-on-SIGHUP makes sense to me too, but only for debugging. It's not useful for ExecReload= since it is asynchronous, and we should make this synchronous.

**Comment by dvdhrm** [comment]
`busctl` now sets `bus-client` by default. If anyone needs support for direct connections, we can add that later on.

I don't really see the benefit in SIGHUP, so I didn't implement it. `busctl --address ... ReloadConfig` works just fine now.
