### ISSUE TITLE
Fails to build with tests enabled on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by glaubitz** [systemd/systemd#5918]
Trying to build _systemd_ on an up-to-date openSUSE Tumbleweed with:

```bash
$ ./autogen.sh
$ ./configure CFLAGS='-g -O0 -ftrapv' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64  --with-rootprefix=/ --with-rootlibdir=/lib64
$ make
```

fails with:

```bash
  CC       src/test/test_execute-test-execute.o
  CC       src/test/test-copy.o
  CC       src/test/test_cap_list-test-cap-list.o
  CC       src/test/test-sigbus.o
In file included from src/test/test-execute.c:34:0:
./src/shared/seccomp-util.h:22:21: fatal error: seccomp.h: No such file or directory
 #include <seccomp.h>
                     ^
compilation terminated.
make[2]: *** [Makefile:21204: src/test/test_execute-test-execute.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:22687: all-recursive] Error 1
make: *** [Makefile:10185: all] Error 2
```

Consequently, openSUSE builds _systemd_ with ```--disable-tests``` [1] and adding ```--disable-tests``` to the above ```configure``` line makes _systemd_ build just fine.

Looking at the problem, it seems that ```pkg_cv_SECCOMP_CFLAGS=-I/usr/include/libseccomp``` is not passed to ```CFLAGS``` when building the tests. On openSUSE, both _libseccomp_ and _libkmod_ have their headers in the ```libseccomp``` and ```kmod``` sub-directories in ```/usr/include```, respectively. So, we have to use ```pkg-config``` to get the proper ```CFLAGS``` for these headers.

This issue affects the Meson build as well, although in a slightly different manner, so I'm going to open a separate issue for that.

> [1] https://build.opensuse.org/public/build/Base:System/openSUSE_Tumbleweed/x86_64/systemd/_log

**Comment by glaubitz** [comment]
I'm working on a fix now.

**Comment by glaubitz** [comment]
Patch is in #5924.

**Comment by poettering** [comment]
#5924 has been merged. Closing. (@glaubitz, next time please add a `Closes: #5918` line to your commit msgs or github PR cover letter, github will then automatically close any issues associated that way when the PR is merged)

**Comment by glaubitz** [comment]
@poettering Ok, will do. I was already wondering why this wasn't closed automatically. Didn't know github has a mechanism like this.

Btw, github somehow mangled the commit associated to this PR. Although I committed it with my @suse.com address (because I did it during work hours), it still used my @physik.fu-berlin.de address. It's still @suse.com in my local ```suse2``` branch. Strange.

**Comment by poettering** [comment]
@glaubitz we used github's "squash and merge" feature for this case, in which case all your commits are squashed into one and rewritten using your gihub credentials rather than the original commit credentials. I am pretty sure this is pretty broken bheaviour of github though, in particular if the PR only consisted of a single commit anyway. 

In previous releases I spent some time trying to fix up github's brokeness via the ".mailmap" file in the repo, which makes sure "git shortlog" will map this back to the proper commit account details, and we get the stats right (of course, this won't actually rewrite any commits, but it will fix up the stats, and the contributors list we put together for the NEWS file). 

Consider changing your github creds though, so that such squashes won't result in such rewrites next time...

**Comment by glaubitz** [comment]
On Fri, May 12, 2017 at 05:50:35AM -0700, Lennart Poettering wrote:
> @glaubitz we used github's "squash and merge" feature for this case, in which case all your commits are squashed into one and rewritten using your gihub credentials rather than the original commit credentials. I am pretty sure this is pretty broken bheaviour of github though, in particular if the PR only consisted of a single commit anyway. 

Ah, that explains it.

> In previous releases I spent some time trying to fix up github's brokeness via the ".mailmap" file in the repo, which makes sure "git shortlog" will map this back to the proper commit account details, and we get the stats right (of course, this won't actually rewrite any commits, but it will fix up the stats, and the contributors list we put together for the NEWS file). 

Ok, maybe we should add my SUSE address to the .mailcap file
then. It's glaubitz@suse.com.

> Consider changing your github creds though, so that such squashes won't result in such rewrites next time...

I do have my SUSE address added to github, but I don't use it for all
commits, just for the stuff I do at work.

**Comment by poettering** [comment]
> Ok, maybe we should add my SUSE address to the .mailcap file then. It's glaubitz@suse.com.

Ah, you are a suse guy now? Congrats to your new job!

Anyway, best way to make sure this is added is simply by filing a PR for it... ;-) The .mailmap file is part of the normal git repo after all

**Comment by poettering** [comment]
(https://github.com/systemd/systemd/blob/master/.mailmap)

**Comment by glaubitz** [comment]
On Fri, May 12, 2017 at 06:17:05AM -0700, Lennart Poettering wrote:
> > Ok, maybe we should add my SUSE address to the .mailcap file then. It's glaubitz@suse.com.
> 
> Ah, you are a suse guy now? Congrats to your new job!

Yes :-). Thanks a lot!

> Anyway, best way to make sure this is added is simply by filing a PR for it... ;-) The .mailmap file is part of the normal git repo after all 

Good idea. Will do!

-- 
 .''`.  John Paul Adrian Glaubitz
: :' :  Debian Developer - glaubitz@debian.org
`. `'   Freie Universitaet Berlin - glaubitz@physik.fu-berlin.de
  `-    GPG: 62FF 8A75 84E0 2956 9546  0006 7426 3B37 F5B5 F913

**Comment by fsateler** [comment]
> we used github's "squash and merge" feature for this case, in which case all your commits are squashed into one and rewritten using your gihub credentials rather than the original commit credentials. I am pretty sure this is pretty broken bheaviour of github though, in particular if the PR only consisted of a single commit anyway.

BTW, github also has a "rebase and merge" option. In this case, there was no need to actually squash, as the PR was a single commit anyway, and the rebase should have preserved the commit credentials.

**Comment by poettering** [comment]
> BTW, github also has a "rebase and merge" option. In this case, there was no need to actually squash, as the PR was a single commit anyway, and the rebase should have preserved the commit credentials.

But that will always insert an additional merge commit, no? we kinda like the squash logic, i.e. that really just results in a single commit, and the reference to the github issue is inserted in the commit msg itself

**Comment by fsateler** [comment]
> But that will always insert an additional merge commit, no?

No. It rebases and then does a fast-forward, creating a linear history.

> we kinda like the squash logic, i.e. that really just results in a single commit,

What I suggest would of course only work on single-commit PRs.

> and the reference to the github issue is inserted in the commit msg itself

Ah, that indeed would be missing in the rebase case.
