### ISSUE TITLE
easier way of sd-bus connection sharing

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#593]
It is relatively hard to share a connection if objects should detach from the connection cleanly. Lets say we have an object that gets initialized with the given sd-bus. Then object sends few async messages and waits for their reply. Then, a higher level API decides to yank the object off the bus and dispose it. Then object has to make sure it won't get a late callback of its async requests. (Same thing if object has registered a vtable etc.)

We have a way to do that and the way is using non floating slots. However, application constantly has to keep track of the slots. For example every time it gets a callback to its async request, it needs to unref the slot that was associated with the async request. 

However, this would be redundant implementation for all the cases where sd-bus is shared and objects might appear/disappear.

I believe this is a common API usage and we should provide an easier way in the library, what do you guys think?

**Comment by poettering** [comment]
I am note sure I grok what you are proposing? THere are floating slots for the cases where you don't want to keep track of async calls, and there are non-floating slots for the cases where you do want to keep track of them. WHat are you asking for? An object that contains refs to multiple slots at once? Or a way to unref slots by userdata rather than slot ptr?

What's the precise problem with keeping track of bus slots in the objects you pass as userdata to them? why wouldn't that work?

Can you elaborate on the usecase?

**Comment by utezduyar** [comment]
The usecase is to make it simpler for an object to leave the bus connection gracefully.

As you have said non-floating slots are used to be able to do a cleanup when leaving the bus. But if you only care about cleaning everything at once, then the task of keeping track of non-floating slots is going to be redundant by API users. 

My propose is to implement an "anchor-floating slot" type. 

```
sd_bus_slot* slot = sd_bus_slot_get_anchor ();
// Make first call
sd_bus_call_async (bus, &slot, ....)
// Make the second call - with the same slot
sd_bus_call_async (bus, &slot, ....)
// Register a vtable - with the same slot
sd_bus_add_object_vtable(bus, &slot, ...)
// We decided to cancel our contribution on the bus. This cancels our vtable registration, and 2 async calls we made in one shot
sd_bus_slot_unref (slot)
```

**Comment by poettering** [comment]
The slot parameter is currently defined as purely a return parameter and we will override was previously stored in them, ignoring the old value. We cannot change the behaviour without breaking API...

I can see what you are trying to do though, not sure how to best expose this without having to duplicate the existing API a second time...

**Comment by dvdhrm** [comment]
I'm closing this now as I see little point in keeping this hanging around. I'm certainly open to review ideas how to simplify this, but that needs someone to come up with an idea..

TBH, I'm perfectly fine with tracking slots. The memory requirements are minimal, as the slots are needed _somewhere_, anyway. Whether that's hidden or not, doesn't matter much (except, obviously, for usability). So I'm not very eager to work on this. But please, feel free to propose an API!
