### ISSUE TITLE
Option for avoid logging syslog facilities in journald

### ISSUE THREAD

**Issue by rfrail3** [systemd/systemd#5937]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> v232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch

As the journal have the options MaxLevelStore=, MaxLevelSyslog=, MaxLevelKMsg=, MaxLevelConsole=, MaxLevelWall= that can control the limit of the severity level, it would be helpfull a similar option for the facility level (Section 4.1.1 in https://tools.ietf.org/html/rfc3164)
Maybe better than a max level, a definition of which of all you do not want to keep

**Comment by keszybz** [comment]
This doesn't seem to be useful enough on modern systems, see longer comment in https://github.com/systemd/systemd/pull/6361#issuecomment-424781750.
