### ISSUE TITLE
localed could determine appropriate console font on keymap/locale change

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#595]
We received bug report about "squares" being printed on console after keyboard and locale were set to option which outputs non-latin characters. I wondering if there is any possibility for localed to know which font might contain all glyphs needed to properly support given keymap/locale combination?

https://bugzilla.redhat.com/show_bug.cgi?id=1238683

**Comment by dvdhrm** [comment]
Doing font-selection based on a locale is wrong. It's the job of the UI to do proper fallback-font handling (like fontconfig+pango do). Fonts are selected based on shape-preference, not based on coverage.

The fact that the linux-console is so limited in functionality, but still pretends to be UTF-8 read, is just one more hint to stop using it. Imo, we're not responsible of fixing the linux-console. The `localectl` utility provides a low-level interface to change its properties, but apart from that, I'd not add any black magic. Use one of the legacy tools like `setfont` if you really care.

Anyway, closing this now, as we can continue discussing this on bugzilla.
