### ISSUE TITLE
Add IBM/Lenovo UltraNav SK-8845 TrackPoint to hwdb

### ISSUE THREAD

**Issue by charles-plessy** [systemd/systemd#5952]
Hello,

to get a reasonable trackpoint speed on my computer, I had to add the following lines in a snippet in `/etc/udev/hwdb.d/`:

    evdev:input:b0003v06CBp0009e0020*
     POINTINGSTICK_CONST_ACCEL=2.5
     POINTINGSTICK_SENSITIVITY=200

Can you add support for this keyboard in `systemd/hwdb/70-pointingstick.hwdb` ?  Please let me know if you need additional details.  For an `evdev:name` entry, I could not find by myself what to enter as _input device name_ and _vendor_.

Related issue in libinput: <https://bugs.freedesktop.org/show_bug.cgi?id=100965>.

**Comment by whot** [comment]
Any chance you can submit a pull request for this? it goes into the hwdb/70-pointingstick.hwdb file, just add a # comment with the human readable name of the device. Skip the e0020 bit btw, it doesn't add anything.
