### ISSUE TITLE
Cannot reset resource-control property

### ISSUE THREAD

**Issue by yunchih** [systemd/systemd#5965]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

I want to toggle resource control on systemd unit but I have not found a straight-forward way to unset a property.  If I leave the `[xx]` field blank in `systemctl set-property [unit] [property]=[xx]`, strange number will appear .... (as shown below)  I am not sure if this is a bug...  Maybe point me to somewhere so that I know how to correctly unset a property.

### In case of bug report: Unexpected behaviour you saw

```
$ sudo systemctl set-property --runtime user-66965.slice CPUQuota=400%
$ cat /run/systemd/transient/user-66965.slice.d/50-CPUQuota.conf
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Slice]
CPUQuota=400%
$ sudo systemctl set-property --runtime user-66965.slice CPUQuota=
$ cat /run/systemd/transient/user-66965.slice.d/50-CPUQuota.conf
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Slice]
CPUQuota=1844674407370955%
```

**Comment by poettering** [comment]
hmm, this is definitely a bug...

**Comment by keszybz** [comment]
Not really a bug, but I filed a PR anyway.
