### ISSUE TITLE
networkd creates bond0, yet does not apply parameters to it

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#5971]
### Submission type

  - [ ] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v229-4ubuntu17 on 4.4.0-77-generic

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

Yes, will retest with more recent stuff.

### Used distribution

Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

```
May 15 17:38:37 xnox-iad-nr5 systemd-networkd[934]: bond0: netdev ready
May 15 17:38:37 xnox-iad-nr5 systemd-networkd[934]: Enumeration completed
May 15 17:38:37 xnox-iad-nr5 kernel: bond0 (uninitialized): Setting MII monitoring interval to 100000
May 15 17:38:37 xnox-iad-nr5 kernel: bond0 (uninitialized): Setting xmit hash policy to layer3+4 (1)
May 15 17:38:37 xnox-iad-nr5 kernel: bond0 (uninitialized): Setting resend_igmp to 1
```

### In case of bug report: Unexpected behaviour you saw

```
May 15 16:27:50 ubuntu systemd-networkd[977]: bond0: netdev ready
May 15 16:27:50 ubuntu systemd-networkd[977]: Enumeration completed
May 15 16:27:50 ubuntu systemd-networkd[977]: bond0: netdev exists, using existing without changing its parameters
```

### In case of bug report: Steps to reproduce the problem

1. Specify bond .netdev unit named bond0 with non-default Mode TransmitHashPolicy MIIMonitorSec LACPTransmitRate e.g.:
```
Mode=802.3ad
TransmitHashPolicy=layer3+4
MIIMonitorSec=1s
LACPTransmitRate=fast
```
2. Make sure bonding module is not loaded by default, e.g. it is _not_ listed in modules-load.d or similar
3. Observe that networkd auto-creates the bond0 device, yet does not set its settings

### Similar bug reports
* https://bugs.freedesktop.org/show_bug.cgi?id=82956

* This is affects cloud-init as it now can generated networkd config via nplan, which results in bond0 configs. Also i think people migrating to networkd would want to use bond0 still out of the box.

### Possible fixes
* ship [/usr]/lib/modprobe.d/ snippet to set `options bonding max_bonds=0` to prevent bond0 autocreation

* somehow check before-hand that bond0 does not exist, and when it get magically autocreated, force apply settings onto it anyway. I got lost in the networkd code a bit to figure out where all these things are happening via VTABLE callbacks =/

**Comment by ssahani** [comment]
if we don't set `max_bonds=0` the kernel automatically creates the bond0 . Networkd does not do anything here . Hence the netlink parameters does not get set.  Bestway is to set `max_bonds=0` and create bond0 via networkd. and that should work as expected.

**Comment by xnox** [comment]
@ssahani 
1. there is no bonding module loaded in the kernel
1. networkd reads bond0.netdev
1. attemps to create it via rtln
1. which triggers bonding kernel module to be loaded (not sure about this one)
1. networkd gives up finishing bond0.netdev setup, despite the fact, that networkd caused (indirectly) for it to be created

when networkd causes for the bonding module to load why does networkd not set max_bonds=0?

Does that explain better the problem I see? I only created bond0.netdev for networkd to process and did no other changes to the system (bonding module is not built-in, nor loaded in any other way, but by networkd)

**Comment by ssahani** [comment]
>which triggers bonding kernel module to be loaded (not sure about this one)
  
 whenever bonding feature is requested if not loaded already in kernel networkd or via something else it's gets autoloaded.  So if we don't set max_bonds=0 bond0 gets created. Later we try to change via networkd that does not work. 

>  why does networkd not set max_bonds=0?

  This is a specific use case. 

>>Does that explain better the problem I see? I only created bond0.netdev for networkd to process and did no other changes to the system (bonding module is not built-in, nor loaded in any other way, but by networkd)

  Please see  https://cgit.freedesktop.org/systemd/systemd/commit/?id=7c1cff4

**Comment by poettering** [comment]
@xnox i am pretty sure distros should generally set max_bonds=0 for the entire module. Creating a bond device just because the module is loaded is almost always a bad idea, and just a historical left-over.

(on fedora "modprobe bonding" results in a device being creating too... meh...)

**Comment by poettering** [comment]
Will close this now, as this is weird kernel behaviour and either the distros or the kernel should just stop doing this...

**Comment by ioquatix** [comment]
I'm glad this is now being set by default, it was causing all sorts of issues for me.
