### ISSUE TITLE
systemd-networkd fails to bring up netdev if an MTUBytes is specified

### ISSUE THREAD

**Issue by oliv3r** [systemd/systemd#5972]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 226
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> VLAN is not created

### In case of bug report: Unexpected behaviour you saw

> mei 15 21:53:53 7of9 systemd[1]: Started Network Service.
mei 15 21:53:53 7of9 systemd-networkd[831]: enp3s0f1: Configured
mei 15 21:53:53 7of9 systemd-networkd[831]: enp3s0f0: enp3s0f0        : could not join netdev: Invalid argument
mei 15 21:53:53 7of9 systemd-networkd[831]: enp3s0f0: Failed

### In case of bug report: Steps to reproduce the problem

> Created the following netdev:
[NetDev]
Description=XS4all Internet VLAN 6
Name=xs4all_vlan6
Kind=vlan
MTUBytes=1508

[VLAN]
Id=6

this should create a vlan with an MTU of 1508. However the previous output already seen, it refuses to work. Removing the MTUBytes altogether brings up the device. Manually then doing ip link set vlan_6 mtu 1508 works as expected.

**Comment by ssahani** [comment]
I did a test Kernel is not permitting  after creating 
```
11: vlan1@enp0s25: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 28:d2:44:b0:6a:32 brd ff:ff:ff:ff:ff:ff
```

```
 sudo ip link set mtu 1508 dev vlan1
RTNETLINK answers: Numerical result out of range
```

**Comment by ssahani** [comment]
@poettering i am not able to set the MTU via ip command too. Kernel rejects 1508 value. Don't think this is a bug.

**Comment by poettering** [comment]
maybe the MTU is too short for VLANs? i have little clue about vlans I must say... maybe check the kernel sources why it refuses thta?

**Comment by ssahani** [comment]
yes I see at 
```
static int vlan_dev_change_mtu(struct net_device *dev, int new_mtu)                                                                                                                            
{                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                             
        if (netif_reduces_vlan_mtu(real_dev))                                                                                                                                                  
                max_mtu -= VLAN_HLEN;                                                                                                                                                          
        if (max_mtu < new_mtu)                                                                                                                                                                 
                return -ERANGE;                                                                                                                                                                
                                                                                                                                                                                               
        dev->mtu = new_mtu;                                                                                                                                                                    
                                                                                                                                                                                               
        return 0;                                                                                                                                                                              
}                                                                                                                                                                                              

```

**Comment by poettering** [comment]
OK, and what is max_mtu and VLAN_HLEN?

Anyway, it appears indeed as if networkd is not at fault here, the configuration is simply not supported by the kernel. Closing hence.

**Comment by oliv3r** [comment]
@poettering thanks for atleast checking back with me before closing the bug. :roll_eyes: but I guess I was not clear in my report (the template is horrible I suppose and I should have not followed it exaclty :) but the last sentence does mention 'manually works' :+1: )

6: xs4all_vlan6@enp3s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1508 qdisc noqueue state UP group default qlen 1000
    link/ether 2c:53:4a:01:24:60 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::2e53:4aff:fe01:2460/64 scope link 
       valid_lft forever preferred_lft forever


On my NIC/kernel the MTU changing works fine manually. (I actually use the MTU setting in my .network files on my regular interfaces.

This in case, is a .netdev file for a VLAN 'ethernet' device (created by systemd-networkd). So I guess either systemd doesn't set a max_mtu when creating the device (can it even?) or the kernel has no max_mtu for VLAN devices?

I now have simply added:
ExecStartPre=/bin/ip link set xs4all_vlan6 mtu 1508
To my pppoe dialin service as a hack, but lets agree that that's not pretty :)

edit: P.S. I can't seem to find these defines nor the function on master@https://github.com/systemd/systemd.git, where can I find this function? It is part of systemd right?

**Comment by poettering** [comment]
So what happens if you try the commands @ssahani tried?

Your case appears to be different from @ssahani's anyway, as the error you are getting is EINVAL, and @ssahani is getting EDOM.

**Comment by poettering** [comment]
Hmm, so I just reopened this, but now I am noticing that your systemd is ancient. Can you please try with current systemd? (i.e. we only track issues in the two most recent systemd versions here). Also, which kernel is this?

**Comment by oliv3r** [comment]
@poettering well since I can manually configure the vlan, it works, so i just get a valid vlan :)

e.g. my dial-in service now has this:
ExecStartPre=/bin/ip link set xs4all_vlan6 mtu 1508
which works fine. So no error at all.

As I did (or possibly forgot to mention) I did upgrade my systemd and am running at 233 currently.

systemd 233
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN default-hierarchy=hybrid

The kernel is: Linux 7of9 4.9.24-hardened #2 SMP Wed May 17 21:52:44 CEST 2017 x86_64 AMD Athlon(tm) II Neo N36L Dual-Core Processor AuthenticAMD GNU/Linux

But since this 'works' with a manual ip link set, I imagine it's unrelated to the kernel?

**Comment by oliv3r** [comment]
@poettering is there anything else that I should check? I see that gentoo does not have 234 so I can't check that version just yet.

**Comment by oliv3r** [comment]
@poettering I am available to try and debug this too, if you can point out where to add debug statements or the like?

**Comment by biax** [comment]
i can confirm this issue is present in archlinux too with systemd 234

**Comment by multun** [comment]
still present

**Comment by yuwata** [comment]
I confirm that `MTUBytes=1508` does not work, but `1000` works fine. I am not sure the exact value of `real_dev->mtu`, and what `real_dev` is... Note that `VLAN_HLEN` is 4.

**Comment by yuwata** [comment]
As `VLAN_HLEN` is 4, `MTUBytes=1496` works fine.
```
15: test1: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 4e:e3:82:f4:1a:96 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 0 maxmtu 0 
    dummy addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
16: vlan99@test1: <BROADCAST,NOARP> mtu 1496 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 4e:e3:82:f4:1a:96 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 0 maxmtu 65535 
    vlan protocol 802.1Q id 99 <REORDER_HDR,GVRP,MVRP,LOOSE_BINDING> addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```

**Comment by yuwata** [comment]
When MTU of the base(?) interface is increased, then MTU of vlan can be set higher.
```
$ cat 21-vlan.netdev
[NetDev]
Name=vlan99
Kind=vlan
MTUBytes=2000

$ cat 13-dummy.netdev
[NetDev]
Name=test1
Kind=dummy
MTUBytes=2004

$ cat 21-vlan.network
[Match]
Name=test1
[Network]
VLAN=vlan99
```
```
21: test1: <BROADCAST,NOARP,UP,LOWER_UP> mtu 2004 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 4e:e3:82:f4:1a:96 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 0 maxmtu 0 
    dummy addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
22: vlan99@test1: <BROADCAST,NOARP> mtu 2000 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 4e:e3:82:f4:1a:96 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 0 maxmtu 65535 
    vlan protocol 802.1Q id 99 <REORDER_HDR,GVRP,MVRP,LOOSE_BINDING> addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```

So, @oliv3r Please try to set MTU of `enp3s0f0` 1512 (=1508+4) or higher.

**Comment by sedrubal** [comment]
Even if it is not systemds fault, is it the best behavior to get stuck with invalid configs? Shouldn't there be a useful error message?

**Comment by yuwata** [comment]
Any suggestions or PRs are welcome.
