### ISSUE TITLE
Systemd not honoring the ordering dependency on auth.socket file during shutdown/reboot

### ISSUE THREAD

**Issue by Bharateesha** [systemd/systemd#5974]
### Submission type

  - [ ] Bug report
  
### systemd version the issue has been seen with

1.4.3-41.el7.x86_64

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> 

[authclient.zip](https://github.com/systemd/systemd/files/1006724/authclient.zip)

### In case of bug report: Expected behaviour you didn't see
authd should honour the ordering dependency and accept/respond to the new connections before test.service has stopped

### In case of bug report: Unexpected behaviour you saw

>authd did not honor the ordering dependency mentioned in the test service.

### In case of bug report: Steps to reproduce the problem

The problem is seen on Redhat7 with authentication daemon (authd-1.4.3-41.el7.x86_64). In Redhat 7, authd service and socket files are managed under systemd (auth used to be configured under xinetd in Redhat 6). When started, auth.socket starts a listener on port 113. We have written a test service to help reproduce the issue.

In the following test service, /usr/bin/connect_authd is a utility program that tries to connect to auth and expects a response. This service is started up when the system/node starts up and it does nothing else. But when a systemctl reboot is issued, the ExecStop command is issued i.e. during shutdown sequence, the ExecStop forces a connect to the authd and expects a response.

The ordering dependency in the test.service file is such that, during system startup, test.service waits until auth.socket is started up. However, during shutdown, test.service must be stopped first before the auth.socket is stopped. Therefore, the expectation is that when a connect is issued to the authd as part of ExecStop command, the authd must still be running and needs to respond back.

# cat /usr/lib/systemd/system/test.service
[Unit]
Description=Test Script to connect auth during shutdown
After=auth.socket
Requires=auth.socket
 
[Service]
ExecStart=/bin/true
ExecStop=/usr/bin/connect_authd
Type=oneshot
RemainAfterExit=yes
 
[Install]
WantedBy=multi-user.target

Steps to Reproduce:
1. 
# systemctl status test.service
test.service - Test Script to connect auth during shutdown
   Loaded: loaded (/usr/lib/systemd/system/test.service; enabled)
   Active: active (exited) since Wed 2015-07-29 18:14:40 IST; 16s ago
Main PID: 11833 (code=exited, status=0/SUCCESS)
 
Jul 29 18:14:40 nala2 systemd[1]: Starting Test Script to connect auth during shutdown...
Jul 29 18:14:40 nala2 systemd[1]: Started Test Script to connect auth during shutdown.
#

2.
# journalctl -u test
-- Logs begin at Tue 2015-07-28 12:25:30 IST, end at Wed 2015-07-29 18:14:52 IST. --
Jul 29 18:14:40 nala2 systemd[1]: Starting Test Script to connect auth during shutdown...
Jul 29 18:14:40 nala2 systemd[1]: Started Test Script to connect auth during shutdown.
#

3.
# systemctl reboot 

4. 
# journalctl -u test
-- Logs begin at Tue 2015-07-28 12:25:30 IST, end at Wed 2015-07-29 18:17:01 IST. --
Jul 29 18:14:40 nala2 systemd[1]: Starting Test Script to connect auth during shutdown...
Jul 29 18:14:40 nala2 systemd[1]: Started Test Script to connect auth during shutdown.
Jul 29 18:15:41 nala2 systemd[1]: Stopping Test Script to connect auth during shutdown...
Jul 29 18:15:42 nala2 connect_authd[11895]: connect to server 127.0.0.1 sock_auth 768.
Jul 29 18:15:42 nala2 connect_authd[11895]: error message of -1 length received with errno=Connection reset by peer
Jul 29 18:15:42 nala2 systemd[1]: test.service: control process exited, code=exited status=1
Jul 29 18:15:42 nala2 systemd[1]: Stopped Test Script to connect auth during shutdown.
Jul 29 18:15:42 nala2 systemd[1]: Unit test.service entered failed state.
-- Reboot --
Jul 29 18:16:15 nala2 systemd[1]: Starting Test Script to connect auth during shutdown...
Jul 29 18:16:15 nala2 systemd[1]: Started Test Script to connect auth during shutdown.

**Comment by poettering** [comment]
First of all, we only track issues with the two most current systemd versions here, this is made clear in the issue submission form. RHEL7's version's are waaaay to old for that, please contact RH support for help on that.

That said, your service should order itself not only after the socket but also after the service. In systemd start-up order is always the inverse of the shutdown order. Hence if you configure that your service is started after both the socket and the service you want to use, you can be sure at shutdown you are also stopped before both.
