### ISSUE TITLE
mkosi: Debian build broken since switch to Meson

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/systemd#5987]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> master

### Description

The current _mkosi.debian_ settings file is broken, probably since switch to Meson. The problems I have found so far are:
1. Missing g++ package and bad libidn2 package name. **(fixed)**
2. Failed assertions of test-bus-vtable and test-bus-vtable-cc tests. **(fixed)**
3. Some dependencies [showing as missing](https://pastebin.com/9yDxUE1M) although they are in the mkosi.debian file. **(fixed)**
4. [Failed assertion](https://pastebin.com/yL2SKXSj) of text-execute test. **(fixed)**

I am working on it, but it will probably take some time because I am quite busy with other things lately.

**Comment by AsciiWolf** [comment]
I cannot get the tests working. Still the same "_Assertion `sd_bus_start(bus) >= 0' failed._" error. Any ideas?
Everything seems to work fine after commenting out these tests (_test-bus-vtable_ and _test-bus-vtable-cc_) in meson.build.

**Comment by keszybz** [comment]
I'd guess that sd_bus_start fails because the dbus daemon is not active. My bad — I did not think about this case when writing the tests. #5997 seems to good to go, even though it does not fix the issue completely.

**Comment by AsciiWolf** [comment]
Points one and two are fixed, point three is still an issue; some dependencies are still [showing](https://pastebin.com/9yDxUE1M) as missing. But there is also a new problem, _text-execute_ seems to be [failing](https://pastebin.com/yL2SKXSj).

**Comment by keszybz** [comment]
Dependency libselinux found: NO → OK, not specified in mkosi.debian, useless without policy anyway
Dependency libapparmor found: NO → OK, not specified in mkosi.debian, useless without policy anyway
Dependency polkit-gobject-1 found: NO → OK, not specified in mkosi.debian, not needed
Dependency libidn2 found: NO → the version in debian doesn't support pkg-config
Dependency glib-2.0 found: NO → OK, not specified in mkosi.debian, only for tests
Dependency gobject-2.0 found: NO → OK, not specified in mkosi.debian, only for tests
Dependency gio-2.0 found: NO → OK, not specified in mkosi.debian, only for tests
Dependency bash-completion found: NO → OK, not specified in mkosi.debian, not needed

So I think everything works as expected. libidn2 in debian either needs upgrading or just needs to package the .pc file. Other deps don't seem too important.

I can see test-execute failing too. It fails in a debian-unstable container too.

**Comment by evverx** [comment]
> But there is also a new problem, text-execute seems to be failing

> I can see test-execute failing too.

I'm sorry about that. I didn't run `mkosi` while I was reviewing https://github.com/systemd/systemd/pull/6017. The fix is waiting in https://github.com/systemd/systemd/pull/6068. Please, take a look.

**Comment by keszybz** [comment]
Thanks @evverx. I think we can close this now?

**Comment by AsciiWolf** [comment]
I can confirm that #6068 fixed the issue.
