### ISSUE TITLE
systemd-networkd fails to configure bonding on boot with linux 3.14

### ISSUE THREAD

**Issue by unitrq** [systemd/systemd#599]
Starting system with recent kernel (4.0.7) works just fine, but when systemd-networkd starts on boot with 3.14.48 kernel (linux-lts), bonding interface fails with cryptic message in journal:

> Jul 16 11:19:36 hive-l systemd-networkd[352]: bond0: bond0           : could not join netdev: Operation not supported
> Jul 16 11:19:36 hive-l systemd-networkd[352]: bond0: Failed
> Jul 16 11:19:36 hive-l systemd-networkd[352]: br-vlan54: br-vlan54       : could not bring up interface: Invalid argument

Issuing "systemctl restart systemd-networkd" after system boot brings networking up to a working state.
Systemd version is 221, network is configured as follows:
/etc/systemd/network/br-vlan54.netdev

> [NetDev]
> Name=br-vlan54
> Kind=bridge

/etc/systemd/network/bond0.network

> [Match]
> Name=bond0
> 
> [Network]
> DHCP=no
> LinkLocalAddressing=no
> BindCarrier=enp6s0f0 enp6s0f1
> VLAN=vlan54

/etc/systemd/network/enp6s0f.network

> [Match]
> Name = enp6s0f*
> 
> [Network]
> Bond=bond0

/etc/systemd/network/br-vlan54.network

> [Match]
> Name=br-vlan54
> 
> [Network]
> Address=`<ip address/mask>`
> Gateway=`<gateway ip>`
> DNS=8.8.4.4
> DNS=8.8.8.8
> LinkLocalAddressing=no

/etc/systemd/network/vlan54.network

> [Match]
> Name=vlan54
> 
> [Network]
> Bridge=br-vlan54
> LinkLocalAddressing=no
> DHCP=no

/etc/systemd/network/bond0.netdev

> [NetDev]
> Name=bond0
> Kind=bond
> 
> [Bond]
> Mode=802.3ad
> TransmitHashPolicy=layer2+3
> LACPTransmitRate=fast
> MIIMonitorSec=1000

/etc/systemd/network/vlan54.netdev

> [NetDev]
> Name=vlan54
> Kind=vlan
> 
> [VLAN]
> Id=54

**Comment by poettering** [comment]
Maybe bonding is compiled as .ko and is not autoloaded on old kernels? do you have bonding.ko?

if you add "ExecStartPre=/usr/sbin/modprobe bonding" to your systemd-networkd.service file, does it work then?

**Comment by eliasp** [comment]
I saw an issue like this on CentOS 7.1 (systemd 219), where a bonding interface was seemingly configured by `systemd-networkd` (output of `ip a s`, `ip r s` looked all ok) but was never able to receive any packets.
I can't analyze the situation much further right now, but on this system, bonding is provided by a module - so your suspicion might point into the right direction.

**Comment by unitrq** [comment]
Bonding driver is packed into initrd for both kernels:

> # grep ^MODULES /etc/mkinitcpio.conf
> MODULES="radeon bonding"

I suppose those modules are loaded before systemd-networkd starts.
Anyway, I'll try explicit modprobe on service start later today, along with systemd 222

**Comment by unitrq** [comment]
Overriding unit with "ExecStartPre=/usr/bin/modprobe bonding" didn't help, tested with systemd 223

**Comment by unitrq** [comment]
Problem still persist, with linux-lts 3.14.51 and systemd 225. Any suggestions on how to debug an issue to figure out more details?

**Comment by johannbg** [comment]
@ldkfa there is a strong indicator that this is a bug in the kernel, difference in kernel configuration or you are using unsupported bonding option since kernel version "A" works but not kernel version "B". 

Can you remove that ExecStartPre= line @poettering had you adding,  create /etc/modules-load.d/bonding.conf which contains 
 # Load bonding at boot
 bonding

Reboot and attach the full output from dmesg on the report.

**Comment by unitrq** [comment]
Running original systemd-networkd.service with following /etc/modules-load.d/bonding.conf:

> # Load bonding module on boot
> bonding

Links to dmesg and configs for both kernels:
4.1.6 dmesg: http://ix.io/kGP
4.1.6 config: http://ix.io/kGR
3.14.51 dmesg: http://ix.io/kGQ
3.14.51 config: http://ix.io/kGS

**Comment by johannbg** [comment]
@idkfa   The 3.14 kernel does not seem to be loading the 8021q module necessary for vlan trunks ( 8021q: VLANs not supported on bond0 ) 

Can you create another  /etc/modules-load.d/8021q.conf  file ( or simply add this to the bonding.conf file ) which contains

# Load 8021q at boot

8021q

which will ensure the module is loaded

And add to /etc/modules-load.d/bonding.conf
options bonding miimon=1000
options bonding lacp_rate=1
options bonding mode=4
( note if this does not work try remove everything but the module and add "options bonding max_bonds=0 to rule out "conflicts you can also rename your interface to bond1 to do that""

And reboot

Now your 4.1 kernel complaints "Warning: No 802.3ad response from the link partner for any adapters in the bond"
Which indicates your switch(es) do not support 802.3ad or are not configured for MLAG/LACP

**Comment by unitrq** [comment]
Thank you for your help, the following configuration starts bonding interface on boot succesfully:

> # cat /etc/modules-load.d/bonding.conf
> # Load bonding module on boot
> bonding
> # cat /etc/modules-load.d/8021q.conf
> # Load 8021q at boot
> 8021q
> # cat /etc/modprobe.d/bonding.conf
> options bonding miimon=1000 lacp_rate=1 mode=4

dmesg: http://ix.io/kJh

**Comment by johannbg** [comment]
@idkfa you should see and update ( if available ) your system firmware and/or BIOS on that supermicro board since it assigns the ioatdma device to the incorrect iommu causing faults when the driver initializes ( BIOS assigned incorrect VT-d unit for Intel(R) QuickData Technology device followed by an trace ).

**Comment by unitrq** [comment]
@johannbg Updating bios to the latest available version available from vendor site didn't help, this seems to be typical for older supermicro motherboards
