### ISSUE TITLE
networkd tries to set address/route too early for interfaces with BindCarrier=

### ISSUE THREAD

**Issue by michaelolbrich** [systemd/systemd#6007]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> PTXdist

### In case of bug report: Expected behaviour you didn't see

> networkd starts without errors

### In case of bug report: Unexpected behaviour you saw

> networkd reports: `eth0: Could not set route: Network is unreachable`

### In case of bug report: Steps to reproduce the problem

> Configure an interface with BindCarrier=... and make sure it start before the interface it is bound to.

The problem is in `link_joined()`. It calls `link_enter_set_addresses()` unconditionally even if the link is set to down by `link_handle_bound_to_list()`. Setting the address works but setting any route that uses this address as gateway fails with "Network is unreachable".

This is not fatal: The address and route are set again after the interface gains carrier. I'm not sure what the correct fix is. The whole thing is a bit inconsistent. At the beginning the address is set immediately after `link_up()`. Later, networkd waits for carrier before setting the address.

**Comment by keszybz** [comment]
This might be fixed by c1835a427fddac41dcc780cf733b53e01721e8f2. Any chance you could check?

**Comment by michaelolbrich** [comment]
I just tested this. c1835a4 does fix this problem.
