### ISSUE TITLE
resolved should not treat failures to parse user configuration as fatal

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6014]
Failure to parse user provided configuration data should not be made a fatal error.
See the comment at
https://github.com/systemd/systemd/pull/5999#issuecomment-303368593

**Comment by keszybz** [comment]
> If you are ok with this change, I would apply a similar change to resolved as well.

@mbiebl ping

**Comment by mbiebl** [comment]
@keszybz are we mixing up different issues here? I'm a bit confused tbh

**Comment by keszybz** [comment]
This is from https://github.com/systemd/systemd/pull/5999#issuecomment-303507388.
