### ISSUE TITLE
WorkingDir doesn't work, status=200/CHDIR

### ISSUE THREAD

**Issue by outluch** [systemd/systemd#6019]
### Submission type

 - Bug report

### systemd version the issue has been seen with
229.4 ubuntu 16.04 default version

It seems it is not latest 2 version, but how can i upgrade this base service in ubuntu? Latest is 229.4 in default repo.
*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

I want it to change working directory to specified. And it absolutely exists.

### In case of bug report: Unexpected behaviour you saw

`WorkingDir=<abs. path>` causes weird:
```
Started Node.js Server
edu.service: Main process exited, code=exited, status=200/CHDIR                                      │
edu.service: Unit entered failed state.                                                              │
edu.service: Failed with result 'exit-code'.   
```
### In case of bug report: Steps to reproduce the problem

Create a service with WorkingDir directive.
Here is my not woeking config:
```
[Unit]
Description=Node.js Server
#Requires=After=mysql.service       # Requires the mysql service to run first

[Service]
WorkingDirectory=~/test  # Required on some systems
#ExecStart=/usr/local/bin/node /home/edu/edu/index.js >> /home/edu/log/edu.sys.log 2>&1
ExecStart=/usr/local/bin/node /home/edu/test/t1.js
#Restart=always
#RestartSec=3                       # Restart service after 10 seconds if node service crashes
#StandardOutput=syslog               # Output to syslog
#StandardError=syslog                # Output to syslog
#SyslogIdentifier=edu
User=edu
Group=edu
Environment=NODE_PATH=/home/edu/edu/app

[Install]
WantedBy=multi-user.target

```

PS. Head is exploding. Google not helping.

**Comment by outluch** [comment]
It is crazy. I removed that "comments" and magic happened. 4 hours of fighting with this. Hope it will help somebody.

**Comment by poettering** [comment]
You have to create the specified working directory first, and make sure it has the right permissions.

Given that this is fixed now, will close.

**Comment by jefmwols** [comment]
So, what are the "right permissions"?

**Comment by jinliming2** [comment]
> So, what are the "right permissions"?

@jefmwols I tried 0755, it works. `chmod 0755 dir`

**Comment by Swimburger** [comment]
Thank you for that @outluch. 
I guess when the file is parsed, it doesn't see your comments as comments but part of the value you are setting. I was having this issue too.
I'm putting all my comments on a separate line now and the issue is fixed.

**Comment by leo9223** [comment]
> It is crazy. I removed that "comments" and magic happened. 4 hours of fighting with this. Hope it will help somebody.

2 days of fighting and the comments !!!!!!!

**Comment by georgiosd** [comment]
For anyone getting here from a Google search, another reason for this error can be the permissions being correct on the folder itself but wrong on its parent.

I had 755 on `/opt/svc` and 700 on `/opt`

**Comment by AliDo-t** [comment]
> It is crazy. I removed that "comments" and magic happened. 4 hours of fighting with this. Hope it will help somebody.

i abosutley love you. and hate chatgpt for his unncessary comments

**Comment by adamhaley** [comment]
This same thing happened to me, removed the chat GPT-added comments and now working -thx to this thread

**Comment by jikkelstikkel** [comment]
> It is crazy. I removed that "comments" and magic happened. 4 hours of fighting with this. Hope it will help somebody.

Oh my GOOD GAWD!!!! From May 2017 and can you believe it is now 2026 and this is still an issue with a Systemd ".service" file !
Only 4 hours for some but inexperienced ppl like me a whole flipping day. 
For me it was to get a script to run on a raspberry pi on startup. I moved 'comments' to the next line.
