### ISSUE TITLE
make reading /dev/kmsg optional

### ISSUE THREAD

**Issue by celesteking** [systemd/systemd#6022]
My dev system is generating hell lot of kernel info. As much as I enjoy journald, I'd still like to have an option to prevent it from opening and reading kmsg. I've got another more appropriate app that's dealing with kernel msgs. Seems like `server_open_dev_kmsg()` is hard-coded into init code. Just introduce a small toggle that would switch it off, maybe a hidden one. Thanks.

**Comment by basav1989** [comment]
That would be excellent.
For disabling /dev/log listening , I commented out the symlink in *-dev-log.socket file.

Now, the custom dameon listens on /dev/log socket and journald listens on /run/journald/dev-log socket.

have to check how to separate kernel logs from journald
