### ISSUE TITLE
Unable to open file: /etc/ima/ima-policy (-2)

### ISSUE THREAD

**Issue by caravena** [systemd/systemd#6027]
Open bug in launchpad.net:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1693327

"dmesg:
[ 4.496266] Unable to open file: /etc/ima/ima-policy (-2)
[ 4.496274] IMA: policy update failed"

**Comment by mbiebl** [comment]
Should be fixed by a2c74c0ce83ff16fad95fe18d8e7ae0e2817f672

**Comment by evverx** [comment]
This was fixed by a2c74c0ce83ff16.
