### ISSUE TITLE
networkd fails to get IPv4 address via DHCP

### ISSUE THREAD

**Issue by Jesin** [systemd/systemd#6028]
I built and installed systemd b23aec0d6b98bc99998786506a8769e1a1ea1841 and rebooted my laptop. When it booted, wpa_supplicant authenticated and associated with my (IPv4 only) wi-fi network, but systemd-networkd did not retrieve an IP address. The problem remained when I restarted wpa_supplicant and when I rebooted my computer.

I then built and installed systemd from the previous commit (a083537e5d11bce68639c492eda33a7fe997d142) and rebooted, and my system immediately obtained an IPv4 address, so this bug must have been introduced in b23aec0d6b98bc99998786506a8769e1a1ea1841.

Here is my only `.network` file in case it helps:
```
[Match]
Name=*

[Network]
DHCP=ipv4
IPv6AcceptRA=yes
```

**Comment by wonderfly** [comment]
Can you post the related journal log for `systemd-networkd`? Also, what does `networkctl status -a` say?

**Comment by wonderfly** [comment]
Can I ask what you needed `IPv6AcceptRA=yes` for? Most likely disabling it would just work...

**Comment by Jesin** [comment]
`IPv6AcceptRA=yes` is the setting that allows my computer to use IPv6 when it is available, without filling my logs with complaints about IPv6 being unavailable the rest of the time.

**Comment by wonderfly** [comment]
Thanks. Any logs that can help with root causing?

**Comment by wonderfly** [comment]
b23aec0 only touched `link_set_dhcp_routes`, which is a static function and called only once within the file by `dhcp4_address_handler`. The function's behavior was not changed in any way - if there is an address, it will happily proceed just like before; if there isn't an address, it won't get called at all thanks to the checks in `dhcp4_address_handler` and its sole caller `dhcp4_update_address`.

I'm not convinced the change would cause any damage, not without compelling logs.

**Comment by Jesin** [comment]
I just built and installed systemd 3e7d14d78c4d15ec7789299216cbf5c58e61547b, and it works. Whether the bug was in systemd or some other part of my setup, it seems to be fixed now. I am closing this.
