### ISSUE TITLE
When inotify watches are used up, "No space left on device" is shown...

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#6030]
... which is totally expected for programmers, but not for users.

```
# systemctl start test
Failed to add /run/systemd/ask-password to directory watch: No space left on device
```

There are two problems with this error message.

1) The "No space left on device" is completely misleading for users. Programmers who know that inotify_add_watch() sets errno to ENOSPC and this errno is then translated using strerror() to that message may find it ok, but it's not.

My suggestion here would be to change the error message for this special case (when inotify_add_watch() returns < 0 and errno is set to ENOSPC) to something like "Failed to add /run/systemd/ask-password to directory watch: inotify watch limit reached", that is, not use strerrno(errno) in this case.

2) The error message looks as if it came from systemctl, but it didn't, which, for users, is even more confusing than 1). The message came from `tty-ask-password-agent`, which is forked off and exec'd by systemd. This took me a while to debug and figure out.

Here I would suggest to simply identify itself in the error message, since `tty-ask-password-agent` seems to be used a lot for a lot of operations.

#### Expected result
So, the final error message in this case would look like:

`/usr/bin/systemd-tty-ask-password-agent: Failed to add /run/systemd/ask-password to directory watch: inotify watch limit reached`

Yes, it's a bit lengthy, but it makes the error much less confusing. Also, this makes debugging a lot easier, since it's very obvious where the error is coming from.

For a complete reproducer, see https://bugzilla.redhat.com/show_bug.cgi?id=1452933#c2.

**Comment by poettering** [comment]
Also see #1296.

**Comment by poettering** [comment]
@jsynacek as usual, a patch would be greatly appreciated.

**Comment by jsynacek** [comment]
Patch posted for review in https://github.com/systemd/systemd/pull/10305.
