### ISSUE TITLE
man: don't claim your env var expansion was "very shell-like" because its not

### ISSUE THREAD

**Issue by mingo-dango** [systemd/systemd#6035]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232-8

### Used distribution

> Arch Linux

### In case of bug report: Unexpected behaviour you saw

systemd parses and interprets ${variable} diffrent than shells do
in every shell ${variable} ensures that only the variable is expanded even if var exists.
but instead systemd passes the entirety of variable as a single argument.
so here the argv and argc are wrong.

we've had to workaround 
> EnvirementFile=-/etc/default/...
ExecStart=/bin/bash -c "/bin/echo ${daemon-opts} && /usr/sbin/... ${deamon_opt}"

otherwise it would randomly eat parts of ${deamon-opts}.

**Comment by evverx** [comment]
It's quite hard to understand what you're trying to accomplish without knowing what your `/etc/default/...` contains and what exactly you have to work around with `/bin/bash -c ...`.

Could you describe the issue more precisely, please?

> ${daemon-opts}

Do you mean [${parameter-word}](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion)?

**Comment by mingo-dango** [comment]
the issue is very clear, i got caught by limits of variable expansion that you guys implemented, instead of using only ${V} it treats it as a single argument so it breaks argc and argv.
conflicting with very common syntax is a serious issue.

https://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by evverx** [comment]
As far as I understand you mean the behavior described in https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines
> Basic environment variable substitution is supported. Use "${FOO}" as part of a word, or as a word of its own, on the command line, in which case it will be replaced by the value of the environment variable including all whitespace it contains, resulting in a single argument.

I think the mailing list is more appropriate place to discuss issues like this. Here is the address https://lists.freedesktop.org/mailman/listinfo/systemd-devel.

**Comment by dhke** [comment]
Side note: I feel obliged to state that after basically seeing something like "dismissed to the mailing list" here, I'm quite reluctant to add my 2 ¢ ... but nonetheless.

While one can argue about the nature of the problem, the current state of afairs clearly seems to cause confusion. In particular, the [documentation states](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines) that

> This syntax is intended to be very similar to shell syntax

Unfortunately, while the syntax is similar, the semantics are subtly different. In particular

- with systemd `$X` causes word splitting and quote stripping, while the shell only does word splitting, retaining quotes. This is a semantic mismatch.
- with systemd `${X}` does no word splitting and no quote stripping, while in the shell, `${X}` is no different from `$X`. This is another semantic mismatch.

From only the documentation, it is unclear to me, if `"$X"` still results in a single word or if the result is equivalent to `${X}`. In which case, the only reason for `$X` to behave differently than `${X}` is (implicit) quote stripping. From the thread [here](https://lists.freedesktop.org/archives/systemd-devel/2014-October/023677.html), this actually seems to have happened by accident.

The long-standing agreement (at least with bash and zsh) seems to have been to use `${VAR:modifier}` or similar constructs to perform other-than-default variable expansion. systemd instead has chosen a different path. 

Re-using the same syntax for different semantic interpretations in a single system, especially at a point where two modules (systemd and the shell) closely interact, seems unfortunate. The divergence from the well-known shell semantics is screaming for subtle security bugs, e.g. when a developer assumes shell semantics in unit files and vice versa.

It might really be a good idea to explicitly and unambiguously mention in documentation, that the semantics of variable expansion are distinctively different from what the shell does.  Systemd's expansion semantics are not (only) **more limited**, but they are **different**.

So yes, I think this is a BUG, not a discussion topic for the mailing list.

**Comment by mike-hamza** [comment]
this is a real issue not a design suggestion, you need handle it, and sending him to the mailing list is not a good idea.
but then again as he said it conflicting with very common syntax is a serious issue.
you guys broke the compatibility layer with everything more then any other project.

**Comment by evverx** [comment]
@dhke , I agree that documentation might be improved, but I'm not sure that

> conflicting with very common syntax is a serious issue

is about documentation.

**Comment by mikeps** [comment]
from the documentation even the "<", "<<", ">", and ">>", and piping "|" and "&" are broke, all of them, and there's no clarification.
in my opinion it's like you are developing backwards.
this is wrong technically and from user/admin perspective.

**Comment by dhke** [comment]
@evverx  To be frank, I consider the way variable expansion happens in systemd unit files to be ... less than satisfactory.

But changing the existing method to something that more closely resembles what long-standing Unix users (and that includes me) would expect, seems problematic on its own given systemd's present deployment base on production systems. At least over here, that change would require inspecting every single unit file. Making it a documentation issue might be the pragmatic solution.

**Comment by mingo-dango** [comment]
@evverx mailing-list then documentation, it's the easiest solution yeah better then inspecting the interpreter, because obviously it's not interpreted by a shell anymore.
problem solved with purging arch and installing **Gentoo**. cause i don't have time to figure out other solutions, especialy when the documentation is somewhat confusing and misleading.

**Comment by BSDfolk** [comment]
stripped very basic syntax essentials that are necessary for passing special arguments to daemons for no technical reason!!! forcing daemons to implement other ways for doing very basic things. i'm kinda confused here.
but congratulation folks. linux finally got turned into a windows machine successfully, and now u can can expect market share for linux desktop to shine against windows and mac ;) 
what an awful implementation for a daemon launching interpreter. simply it's an ignorance at it's best for **25 years of development**.

**Comment by poettering** [comment]
systemd is not a shell. if you want a shell, use a shell, but don't consider systemd to be one, it really is not. It's not a generic macro processor either, btw. 

It's very easy to run shell programs from systemd unit files, if you need to. Simply specify them as the executable to start in ExecStart= command lines.

Hence, if you want to put together command line dynamically, involving conditionals and/or complex variable expansion then please use a tool that is designed to do that, such as a shell. 

systemd unit files are supposed to be parseable in a stateless, declarative way, and any complex variable expansion contradict that goal. One could argue out language is already more complex than is good, but we really don't want to turn it into a complex shell, that's precisely what we want to step away from.

Note that I am not telling you your usecase wasn't valid. I am just trying to make clear that systemd unit files is not supposed to cover all usecases a shell covers, and that there's nothing wrong with using a shell when you need to one.

Anyway, the documentation is indeed misleading, we should not claim to "be very similar to shell syntax", because we indeed aren't and we really shouldn't attempt to be.

**Comment by dhke** [comment]
Given the comment and the proposed fix, I fill obliged to note that a documentation update doesn't make the semantic mismatch go away. To put it more frankly, from a user interface perspective, this is still borked for anybody used to shell-like semantics.

Even if you stick to the pure declarative approach, the semantic changes are problematic. 

- The assumption that `$X` and `${X}` have the same result doesn't carry over. `Σx` does rounding, but `Σ(x)` doesn't ... Mix that with the fact that systemd also does support quoting to prevent word expansion and you also have an orthogonality violation. 
- Shell users would also expect for single quotes to disable variable expansion, which they don't in unit files.

I don't really understand the justification behind this divergence (Chesterton's fence!), but having this very explicit in the docs is at least a significant improvement.
