### ISSUE TITLE
systemd-resolved does not follow CNAME

### ISSUE THREAD

**Issue by f3flight** [systemd/systemd#6041]
### Submission type
 - Bug report

### systemd version the issue has been seen with
232

### Used distribution
Arch Linux

### In case of bug report: Expected behaviour you didn't see
DNS name resolved

### In case of bug report: Unexpected behaviour you saw
DNS reply returns no IP address

### Example of problem:
[root@localhost ~]# dig auth.mirantis.com @127.0.0.53

; <<>> DiG 9.11.1 <<>> auth.mirantis.com @127.0.0.53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41570
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;auth.mirantis.com.             IN      A

;; ANSWER SECTION:
auth.mirantis.com.      2978    IN      CNAME   drzdq.x.incapdns.net.

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sat May 27 09:55:55 PDT 2017
;; MSG SIZE  rcvd: 80

### Example of how it should work:
[root@localhost ~]# dig auth.mirantis.com @8.8.8.8

; <<>> DiG 9.11.1 <<>> auth.mirantis.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50461
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;auth.mirantis.com.             IN      A

;; ANSWER SECTION:
auth.mirantis.com.      3599    IN      CNAME   drzdq.x.incapdns.net.
drzdq.x.incapdns.net.   29      IN      A       199.83.131.92                 # <--- this is missing in systemd-resolved reply

;; Query time: 72 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat May 27 09:57:17 PDT 2017
;; MSG SIZE  rcvd: 96

--------------------

[root@localhost ~]# pacman -Qi systemd
Name            : systemd
Version         : 232-8
Description     : system and service manager
Architecture    : x86_64
URL             : https://www.github.com/systemd/systemd
Licenses        : GPL2  LGPL2.1
Groups          : None
Provides        : nss-myhostname  systemd-tools=232  udev=232
Depends On      : acl  bash  dbus  iptables  kbd  kmod  hwids  libcap  libgcrypt  libsystemd  libidn  lz4  pam  libelf  libseccomp  util-linux  xz
Optional Deps   : cryptsetup: required for encrypted block devices [installed]
                  libmicrohttpd: remote journald capabilities
                  quota-tools: kernel-level quota management
                  systemd-sysvcompat: symlink package to provide sysvinit binaries [installed]
                  polkit: allow administration as unprivileged user
Required By     : device-mapper  dhcpcd  libpulse  libusb  lvm2  mkinitcpio  netctl  pcmciautils  systemd-sysvcompat
Optional For    : None
Conflicts With  : nss-myhostname  systemd-tools  udev
Replaces        : nss-myhostname  systemd-tools  udev
Installed Size  : 17.26 MiB
Packager        : Dave Reisner <dreisner@archlinux.org>
Build Date      : Sat 28 Jan 2017 02:32:41 PM PST
Install Date    : Sat 27 May 2017 08:26:59 AM PDT
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature

**Comment by f3flight** [comment]
oops, looks like a dup (https://github.com/systemd/systemd/issues/3826), but why closed? Issue is still present.

**Comment by grawity** [comment]
Issue is not present in the current release (v233), which is still in Arch's [testing].

**Comment by f3flight** [comment]
Oh I see, ok, need to try that. Closing, thanks.
