### ISSUE TITLE
support Mutex in service unit files

### ISSUE THREAD

**Issue by LionNatsu** [systemd/systemd#6043]
### Submission type

 - Request for enhancement (RFE)

### Support Mutex in service unit files

I found  when the system was initializing the startup (aka status 'activating') for some services have heavy loads with parallelization for HDD. It's because parallelization slow down the throughput in such serial access IO device. Indeed we can use `After=` so far to define the order to make them come and go one-by-one. But we have to know and define not elegantly, what should be the service before certain service.

Mutex can solve the problem in this way:
```ini
# heavy-load-1.service
[Unit]
...
MutexActivating=hdd-sda2.mutex
...
```

```ini
# heavy-load-2.service
[Unit]
...
MutexActivating=hdd-sda2.mutex
...
```

```ini
# hdd-sda2.mutex
[Unit]
Description=Access HDD /dev/sda2
```
And there maybe a generalized form:
```ini
...
[Mutex]
MaxConsumer=1
```
(MaxConsumer should be optional. If MaxConsumer>1, the Mutex is acting as a semaphore)

After that, we can simply `systemctl enable hdd-sda2.mutex` to serialize these services.

**Comment by poettering** [comment]
There have been previous requests for permitting to delay service activation based on number of instances or load. To me this all appears like second guessing the kernel's own scheduling though, as well as a recipe for deadlocking. Hence I am not convinced adding this would be really the best choice. If the kernel is not handling the load put on it nicely, I think it's best to use controls such as per-service Nice= or CPUShares= settings to indicate what has priority and what hasn't and then let the kernel do its job.

**Comment by LionNatsu** [comment]
> To me this all appears like second guessing the kernel's own scheduling though

I looked back again and I am on your side now. It was indeed a bad idea to "guess" IO scheduling. Closing this.
