### ISSUE TITLE
FUSE filesystem breaks boot

### ISSUE THREAD

**Issue by k-hristov** [systemd/systemd#6044]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 229
*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.04.1 Server

### In case of bug report: Expected behaviour you didn't see

> Proper boot of OS

### In case of bug report: Unexpected behaviour you saw

> http://prntscr.com/fdat99

Unable to start udev and on next reboot FUSE filesystem

I am not sure how to reproduce it. This is an HP Proliant DL360 G6 server. Uptime was 214 days before rebooting and see the printscreen above. I have tried some debugging but everything dies with signal 11. Emergency console does not shows up. If i start single user mode (init=/bin/bash) i get a console.

I will be glad to provide any debugging information in order to resolve this. The server was running nothing else but LXD containers. The version was 2.0.4 (stable).

Thanks in advance! I would appreciate some help.

**Comment by poettering** [comment]
Sorry, but this doesn't appear to be an upstream systemd problem. Moreover, we only track issues with the two most rcently released systemd versions upstream (this is made very clear in the submission form btw). Please report this downstream at your distribution, instead. Thank you for your understanding.
