### ISSUE TITLE
remove heredoc usage in systemd-sulogin-shell 

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#6052]
Usage of heredocs in systemd-sulogin-shell is problematic, as bash will uses temporary files for heredocs (dash doesn't apparently). If your /tmp directory is not writable, this will lead to the following error message:
```
/usr/lib/systemd/systemd-sulogin-shell: line 7: cannot create temp file for here-document: Read-only file system
```
A quick fix is to use echo.

This is an issue because people might legitimately have /tmp on /, and / can be ro when sulogin shell is needed.

From https://github.com/systemd/systemd/issues/5674.

**Comment by Jesin** [comment]
Why not use `printf %s\\n` for its more portable and predictable behavior compared to `echo`?

**Comment by keszybz** [comment]
`echo` works well too, it doesn't really matter in this case.
