### ISSUE TITLE
[RFE] systemctl list-paths

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#6054]
### Submission type

 - Request for enhancement (RFE)

systemctl currently supports `list-{units,sockets,timers}`

The addition of `systemctl list-paths` would help simplify reviewing existing path watchers.

### systemd version the issue has been seen with

> 233

### Used distribution

> Fedora

**Comment by ghost** [comment]
That's a great idea. When I'm creating a new service "systemctl --failed" "systemctl list-timers" are my first ports of call. I find paths harder to manage.

**Comment by arianvp** [comment]
I would really like to see this implemented. It seems very useful! however, I wonder what the output should look like. Given that each `.path` unit can have multiple `PathExists, PathChanged` etc directives.
I would suggest just repeating the same path multiple times.  
```
PATH      TYPE              UNIT       ACTIVATES
/x/y/z    FIleChanged       xyz.path   xyz.service
/x/y/z    PathExists        xyz.path   xyz.service
/b/y/z    FileChanged       byz.path   byz.service
/b/y/z    PathExists        byz.path   byz.service
```
