### ISSUE TITLE
[RFE] systemctl list-automounts

### ISSUE THREAD

**Issue by jcpunk** [systemd/systemd#6056]
### Submission type

 - Request for enhancement (RFE)

systemctl currently supports `list-{units,sockets,timers}`

The addition of `systemctl list-automounts` would help simplify reviewing existing automounts.

### systemd version the issue has been seen with

> 233

### Used distribution

> fedora

**Comment by boucman** [comment]
what would you like to see listed here as extra info compared to `systemctl --type=automount` ?

**Comment by jcpunk** [comment]
Something akin to:
```
WHAT      WHERE       MOUNTED(Y/N)     TIMEOUT      UNIT
```

Column names are obviously flexible, but the "is this currently mounted?" and "what is the timeout?" would be very useful to me in addition to `WHAT` and `WHERE`.
