### ISSUE TITLE
(RFE) logs for the manipulation of files

### ISSUE THREAD

**Issue by ShalokShalom** [systemd/systemd#6075]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> … 233

### Used distribution

> … KaOS

Hi there :)

I frequently get issues, where config files are messed up and I think it's a smart idea to see, which app/process cause that.

Is that a task for systemd?

I guess just for files outside of /home, which make less sense then?

**Comment by keszybz** [comment]
In general: no. Systemd is not going to trace all processes in the system on the off chance that they decide to write to some configuration file; this is the job of each individual program to do the right thing and log it as necessary.

That said, it might make sense for systemd to log unit enablement/disablement/mask/unmask/add-wants/remove-wants operations/link in the journal. In the beginning those operations were done by creating symlinks manually, but nowadays things go through systemctl or systemd. Having logs could be quite useful, especially for distribution packaging operations, which use systemctl and which we would be able to log consistently.

**Comment by poettering** [comment]
note that the audit tools are supposed to provide you with exactly that. Please have a look at auditd/auditctl, and ping the audit community for help.

**Comment by ShalokShalom** [comment]
@poettering and do you know such a tool for a file in home as well? I know, a little bit offtopic

**Comment by poettering** [comment]
@ShalokShalom auditd/auditctl works on any file on the system. Also, there's @martinpitt's excelent "fatrace" tool

**Comment by ShalokShalom** [comment]
Thanks a lot
