### ISSUE TITLE
efi-boot-generator: Reloading systemd removes units

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#608]
When boot.automount and/or boot.mount is active and systemd is reloaded, efi-boot-generator will not generate them again.

This is especially bad if the system relies on boot.automount to ensure /boot is mounted when it wants to update the kernels, boot.automount is running but boot.mount is missing already. I've had various failures trying to access /boot ranging from EHOSTDOWN and hanging to ENODEV and proceeding with an unmounted /boot. As a result, I've had silently messed up kernel updates.

I think this is noticeable now because of 163ab29 introducing automount expire, so /boot is not staying mounted after getting mounted early.

**Comment by heftig** [comment]
Maybe the already-a-mountpoint logic should be changed this way:

``` diff
diff --git i/src/efi-boot-generator/efi-boot-generator.c w/src/efi-boot-generator/efi-boot-generator.c
index e6b15c9..5093bdc 100644
--- i/src/efi-boot-generator/efi-boot-generator.c
+++ w/src/efi-boot-generator/efi-boot-generator.c
@@ -69,13 +69,13 @@ int main(int argc, char *argv[]) {
         }

         r = path_is_mount_point("/boot", AT_SYMLINK_FOLLOW);
-        if (r > 0) {
-                log_debug("/boot is already a mount point, exiting.");
-                return EXIT_SUCCESS;
-        }
-        if (r == -ENOENT)
+        if (r > 0)
+                log_debug("/boot is already a mount point, continuing.");
+        else if (r == -ENOENT)
                 log_debug("/boot does not exist, continuing.");
-        else if (dir_is_empty("/boot") <= 0) {
+        else if (dir_is_empty("/boot") > 0)
+                log_debug("/boot is empty, continuing.");
+        else {
                 log_debug("/boot already populated, exiting.");
                 return EXIT_SUCCESS;
         }
```

If /boot is already a mountpoint, the generator should generate the units and rely on systemd's own mechanisms to override the configuration.

I think this just leaves the case where /boot is already mounted before systemd boots. I believe boot.automount will fail instead of screwing up the mount. Not pretty, but not fatal.

**Comment by kaysievers** [comment]
https://github.com/systemd/systemd/pull/777
