### ISSUE TITLE
Add a way to preserve CAP_AUDIT_WRITE for systemd user sessions

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#6080]
Hi,

Now that b3fb3c01eeedd1995c74dbe30fe33f189bc828e2 has been merged, I'm trying to preserve the `CAP_AUDIT_WRITE` capability on the `systemd --user` processes.

I tried, multiple things: `setcap cap_audit_write=ep /usr/lib/systemd/systemd` file on disk (which is surprisingly not working and break GDM O_o), set `CapabilityboundingSet=CAP_AUDIT_WRITE` in the `user@.service` file and finally set `AmbientCapabilities=CAP_AUDIT_WRITE`.

With the `AmbientCapabilities` option set, the `systemd --user` process ends with the audit write capability.

The problem is that this is leaking to the other processes started by systemd in the user session and this can be a problem.

In the status file on /proc of a `systemd --user` process, I can see:

```
CapInh:	0000000020000000
CapPrm:	0000000020000000
CapEff:	0000000020000000
CapBnd:	0000003fffffffff
CapAmb:	0000000020000000
```

With dbus, setting the `cap_audit_write` to the dbus-daemon file on disk is doing what it's supposed to do and is not leaking the capability to the child processes.

I see two issues here, something is going really wrong when a capability is set on the systemd executable file (and not only for `cap_audit_write`) is there any reason for that?

Shouldn't be an option in .service files to modify the other capability sets (effective, permitted,...)?

Edit: to be clear this is also happening without b3fb3c01eeedd1995c74dbe30fe33f189bc828e2 and 6d395665e5ce7b64f3de4c9550c0779843e6cc44 applied too

**Comment by poettering** [comment]
I am not sure I follow. Are you trying to run unprivileged user code with CAP_AUDIT_WRITE? That's really not intended to be used that way, and the kernel will reset it on each execve() anyway. On Linux you cannot pass caps to unprivileged process and expect them to be inherited down the tree indefinitely...

Or is this about the --user instance of the root user?

What are you trying to do?

**Comment by bigon** [comment]
My bug was maybe a bit to broad.

I'm indeed trying to give `systemd --user` instance for non-privileged user the CAP_AUDIT_WRITE capability (and just the systemd process, not the other processes spawned by it).

Using `setcap cap_audit_write=ep /usr/lib/systemd/systemd` should work (except of course if systemd is explicitly dropping the capabilities in the code). And it's working with the dbus-daemon.

My main request here is to preserve the audit_write capability if the process already has it.

In addition for some reasons setting __any__ capability (with setcap) to /usr/lib/systemd/systemd things are starting to break, I'll try to investigate that more. Even if systemd drops the capabilities at runtime the fact that they are granted to the executable shouldn't break anything.

**Comment by bigon** [comment]
I think I found the reason of why something is breaking when at least a capability is set to the executable.

It's due to the fact that systemd is using secure_getenv() at some places (especially in https://github.com/systemd/systemd/blob/master/src/core/dbus.c#L980) so the following code returns:

```C
                e = secure_getenv("XDG_RUNTIME_DIR");
                if (!e) {
                        log_error("Failed to determine XDG_RUNTIME_DIR");
                        return -EHOSTDOWN;
                }
```

**Comment by poettering** [comment]
secure_getenv() is glibc API... And if you pass priviliges the way you do it appears right that secure_getenv() does what it does... I am not sure we really should change anything here, caps aren't really designed for your purpose, and neither is secure_getenv()... 

Sorry, but I will close this, I am not convinced there's anything to fix here. Or if there is, then it would be something to discuss with the glibc folks regarding the implementation of secure_getenv(), instead of redefining this semantics in systemd only.

Sorry!

**Comment by bigon** [comment]
secure_getenv() is doing exactly what its supposed to do (aka not returning anything if we cannot trust the environment because the process is gaining new privileges via SUID or capabilities). This is usually interesting in the case of libraries where the privileges cannot be altered (quote from the getenv(3) manpage: `The  secure_getenv() function is intended for use in general-purpose libraries to avoid vulnerabilities that could occur if set-user-ID or set-group-ID programs accidentally trusted the environment.`)

In this case the code controls the complete execution of the process and could perfectly check and drop the (unwanted) capabilities or check uid != euid and fix that or completely refuse to work instead of just crashing/misbehaving like now.

And yes (file) capabilities are designed for this, aka gain extra privileges for processes that the original user doesn't have (like setuid bit but in a granular way).
