### ISSUE TITLE
"File exists" when trying to start a unit in systemd-222, if two units have same BusName

### ISSUE THREAD

**Issue by AdamWill** [systemd/systemd#609]
In Fedora, we have both timedatex and systemd-timedated. In Fedora 23+, with systemd 222, it seems that trying to start timedatex fails:

```
[root@adam system]# systemctl restart timedatex.service
Failed to restart timedatex.service: Unit timedatex.service failed to load: File exists. See system logs and 'systemctl status timedatex.service' for details.
```

It seems this happens because both `timedatex.service` and `systemd-timedated.service` specify the same `BusName`. Note, `systemd-timedated.service` doesn't have to be _running_ for the problem to occur - it only has to be _there_. If I move it out of the way and do a `systemctl daemon-reload`, I can load `timedatex.service` fine.

I simplified both unit files a bit to demonstrate this. If you make them simply:

```
[root@adam system]# cat systemd-timedated.service 
[Unit]
Description=Time & Date Service

[Service]
ExecStart=/usr/lib/systemd/systemd-timedated
BusName=org.freedesktop.timedate1

[root@adam system]# cat timedatex.service 
[Unit]
Description=System clock and RTC settings service

[Service]
ExecStart=/usr/sbin/timedatex
BusName=org.freedesktop.timedate1
```

and do a `systemctl daemon-reload`, the problem persists. However, if you then just comment out the `BusName` line in `systemd-timedated.service` (and do `systemctl daemon-reload` again), `timedatex.service` starts fine.

This behaviour has changed somewhere between systemd 219 and systemd 222. Fedora 22 (with systemd 219) has the same stuff - it has both timedatex and timedated, and they both specify the same `BusName` in their service files - but this problem doesn't happen there; `timedatex.service` runs fine. In fact you can even start both services at once with no apparent problems (though presumably only one of them gets the dbus interface...)

Note this is a release-blocking bug for Fedora, as it causes gnome-initial-setup to crash, which in turn makes an installed system stick at a blank screen.

**Comment by AdamWill** [comment]
Downstream bug for the gnome-initial-setup crash: https://bugzilla.redhat.com/show_bug.cgi?id=1244023

**Comment by AdamWill** [comment]
I guess the bug could actually be in dbus too; F22 has dbus 1.8, F23/Rawhide has dbus 1.9.

**Comment by poettering** [comment]
Yeah, bus names must be unique. systemd tracks the service status of bus services by their bus names (BusName= binds the status of the unit to the status of the name on the bus, hence the unit name and the bus name must be unique and their mappings bijective).

The stuff "timedatex" is doing is simply not supported, and never was.

We should improve the error messages in this case however, will work on that.

**Comment by poettering** [comment]
The error message has been rewokred in PR #697 now.
