### ISSUE TITLE
Clarify the documentation of ExecStartPost and After

### ISSUE THREAD

**Issue by michalpalka** [systemd/systemd#6097]
### Submission type

 - Bug report (documentation)

### systemd version the issue has been seen with

> v233

### Used distribution

> NixOS

### In case of bug report: Expected behaviour you didn't see

As mentioned previously in #6049, I would recommend clarifying two things in the documentation:

- Currently, the `systemd.service` man page says:
   > `ExecStartPost=` commands are only run after the service has started successfully

  This suggests that a service will be considered started even before the `ExecStartPost=` commands are run, which is not the case and could be made clearer.
 - It would be good to mention that a service specified to start `After` another service will be started after the first service either succeeded or failed to start. This is mentioned in the description of `Wants` of the `systemd.unit` man page:
   > A weaker version of `Requires=`. Units listed in this option will be started if the configuring unit is. However, if the listed units fail to start or cannot be added to the transaction, this has no impact on the validity of the transaction as a whole.

   All the available documentation discusses `After`, `Wants` and `Requires` separately, without giving any examples, which makes it difficult to understand how services will behave when different combinations of these are used.

**Comment by poettering** [comment]
Fix waiting in #6202

**Comment by michalpalka** [comment]
Thanks a lot! 👍
