### ISSUE TITLE
udevadm trigger does not trigger all specified devices

### ISSUE THREAD

**Issue by hramrach** [systemd/systemd#6098]
### Submission type

 - Bug report

### systemd version the issue has been seen with
master since 80877656a557 ("udevadm trigger: allow matching by device name")

### Used distribution

OpenSUSE Leap 42.2

### In case of bug report: Expected behaviour you didn't see

` # systemd/udevadm trigger --verbose /dev/input/event{0,3,9}`
/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input0/event0
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:413C:301A.001C/input/input97/event3
/sys/devices/pci0000:00/0000:00:1b.0/sound/card0/input12/event9

### In case of bug report: Unexpected behaviour you saw
only last device triggers:

` # systemd/udevadm trigger --verbose /dev/input/event{0,3,9}`
/sys/devices/pci0000:00/0000:00:1b.0/sound/card0/input12/event9
` # systemd/udevadm trigger --verbose /dev/input/event{0,3}`
/sys/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/0003:413C:301A.001C/input/input97/event3

**Comment by yuwata** [comment]
(Still not fixed in v240)
