### ISSUE TITLE
path_is_mount_point() fails for SYMLINKS

### ISSUE THREAD

**Issue by haraldh** [systemd/systemd#61]
commit 5d409034017e9f9f8c4392157d95511fc2e05d87 broke the test suite

condition = condition_new(CONDITION_PATH_IS_MOUNT_POINT, "/bin", false, false);
assert_se(!condition_test(condition));

with /bin being a symlink to usr/bin and /usr being a symlink

path_get_parent("/bin") -> "/"
and then "/" is compared to "/usr/bin"

with AT_FOLLOW_SYMLINK we should probably
path_get_parent(readlink("/bin"))

https://github.com/systemd/systemd/commit/5d409034017e9f9f8c4392157d95511fc2e05d87#diff-1e0521b9fbd642fe79e03e479c7b9559R650

**Comment by haraldh** [comment]
would be cool to have a test case for this

**Comment by martinpitt** [comment]
Ah, so symlink → symlink → file ? Aye, will write a test and fix for that ASAP (on Monday, I'm off until Sunday).

**Comment by haraldh** [comment]
/bin -> usr/bin
path_is_mount_point("/bin") first gets the parent without following the symlink first -> "/"
then "/" is compared to "/usr/bin" and because "/usr" is a mountpoint, the comparison in fd_is_mount_point() find different devices for "/" and "/bin" (which is symlink followed) in fd_is_mount_point().

**Comment by martinpitt** [comment]
Harald, I now have a test case which reproduces this particular layout, and it indeed fails as you described. But to be sure, it'd be great if you could test the PR on your particular system again? Thanks!

**Comment by martinpitt** [comment]
This got merged, so closing now.

**Comment by haraldh** [comment]
Thanks! Test suite finally passes again :+1:
