### ISSUE TITLE
sd_pid_notify_with_fds: cmsg_space -> cmsg_len

### ISSUE THREAD

**Issue by cyxgun** [systemd/systemd#6100]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd.x86_64                          219-30.el7_3.8

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> CentOS 7

### In case of bug report: Expected behaviour you didn't see

> sd_pid_notify should work

### In case of bug report: Unexpected behaviour you saw

> Reports EINVAL

### In case of bug report: Steps to reproduce the problem

> Attempt to use sd_pid_notify with NOTIFY_SOCKET env var set.
> Note that at line 526 of sd-daemon.c the use of cmsg_space to set msghdr.msg_controllen instead of cmsg_len can cause the values of msghdr.msg_controllen and cmsg->cmsg_len to be different.

**Comment by evverx** [comment]
Thanks for reporting the issue.

Do you know whether the package you are using contains a5bd3c32abb00ad9 or not? Could you show how to reproduce the issue using systemd >= 227?

**Comment by cyxgun** [comment]
That changeset does not seem to be in my package; I'll test with something recent.  Thanks.

**Comment by cyxgun** [comment]
Retested with version 232 on Ubuntu 17.04 and it seems to work fine.  Sorry for the confusion.

**Comment by evverx** [comment]
The bug causes a serious issue described in https://github.com/systemd/systemd/issues/2236, so I'm a bit surprised that a5bd3c32abb00ad945 has not been backported yet.

**Comment by poettering** [comment]
> The bug causes a serious issue described in #2236, so I'm a bit surprised that a5bd3c3 has not been backported yet.

@lnykryn, @msekletar do you know anything about this?

**Comment by msekletar** [comment]
That commit was already backported but fixed package was not released yet.
