### ISSUE TITLE
logind (KillUserProcesses) issues with glusterfsd/fuse mounts

### ISSUE THREAD

**Issue by konstruktoid** [systemd/systemd#6104]
### Submission type

 - Bug report

### systemd version the issue has been seen with

```
systemd-219-30.el7_3.9.x86_64
systemd-libs-219-30.el7_3.9.x86_64
systemd-sysv-219-30.el7_3.9.x86_64
```

### Used distribution

`Red Hat Enterprise Linux Server release 7.3 (Maipo)`
`3.10.0-514.21.1.el7.x86_64`

### Issues with glusterfsd/fuse mounts

When /etc/systemd/logind.conf are configured with the following

```
[Login]
KillUserProcesses=1
KillExcludeUsers=root
IdleAction=lock
IdleActionSec=15min
RemoveIPC=yes
```

and the `gluster` mounts are mounted via /etc/fstab:

```
/dev/mapper/datavg-lvyyyyy /gluster/yyyyy               xfs    defaults        0 0
xxx:/yyyyy    /mnt/gluster/yyyyy  glusterfs       defaults,_netdev  0       0
```

the mounts are unmounted as `glusterfd` shuts down.

```
[glusterfsd.c:1332:cleanup_and_exit] (-->/lib64/libpthread.so.0(+0x7dc5) [0x7f640c8b3dc5] -->/usr/sbin/glusterfs(glusterfs_sigwaiter+0xe5) [0x7f640df4bfd5] -->/usr/sbin/glusterfs(cleanup_and_exit+0x6b) [0x7f640df4bdfb] ) 0-: received signum (15), shutting down. 
````

This behavior does not show up when setting `KillUserProcesses=0` in `logind.conf`.

`Red Hat Enterprise Linux Server release 7.3 (Maipo)`
`3.10.0-514.21.1.el7.x86_64`

```
systemd-219-30.el7_3.9.x86_64
systemd-libs-219-30.el7_3.9.x86_64
systemd-sysv-219-30.el7_3.9.x86_64
```

Tested all stable gluster versions >= 3.7

Finding this behavior would have been easier if logging when KillUserProcesses, RemoveIPC is activated had been available (https://github.com/systemd/systemd/issues/5672).

Could be related https://github.com/systemd/systemd/issues/5878#issuecomment-301324167

**Comment by poettering** [comment]
I am sorry, but 219 is really ancient, and we only track issues in the two most current systemd versions upstream (this is made explicitly clear in the issue submission form btw), and that's 232 and 233 right now. Moreover we have no expertise in gluster.

Please contact your downstream distro and the gluster project for help on this one.

Sorry!
