### ISSUE TITLE
`systemctl disable` does not mention when a service will still be activated by a socket

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6107]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

Debian unstable

### Request for enhancement:

`systemctl stop dbus` provides an educational message about socket activation.

However, no such message is seen if you instead use `systemctl disable dbus` (and then reboot).

```
Warning: Stopping dbus.service, but it can still be activated by:
  dbus.socket
```

Possible message:

```
Notice: Disabling dbus.service.  It can still be activated by:
  dbus.socket
```

This report originates from a question on [unix.stackexchange.com](https://unix.stackexchange.com/questions/369937/fedora-25-and-disabling-whatever-is-listening-on-port-111/369943#369943).  In summary, using Fedora 25, you get a listener on the rpcbind port by default, which shows up in `netstat -l`, `nmap` etc.  If you seek to disable the listener (perhaps you're also disabling firewalld, because it gets in the way of systemd-nspawn networking) then you need to know about socket activation.  And if you run a quick `disable rpcbind` and reboot (to double-check the listener is not started on a new boot), you won't see the helpful `stop` message which points out `rpcbind.socket`.

Then you're inclined to complain about systemd breaking things.  Which is a shame, because I think when you're familiar with managing systemd services, they're really really nice.

(You still then have to work out what `rpcbind.socket` is, or at least how it can be disabled.  But something is better than nothing).

#5750 is vaguely relevant.  `rpcbind.service` is disabled by default.  Highlighting that would have at least shown some other action is required, and avoided a wasted reboot cycle.

**Comment by YHNdnzj** [comment]
Fixed by #29333
