### ISSUE TITLE
systemctl can't execute stop actually, when service is startted by other way

### ISSUE THREAD

**Issue by fishes9595** [systemd/systemd#6117]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

>systemd 210

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see

>systemctl can execute stop actually, when service is startted by other way

### In case of bug report: Unexpected behaviour you saw

> systemctl can't execute stop actually, when service is startted by other way

### In case of bug report: Steps to reproduce the problem

>for example: nscd
1.execute: systemctl stop nscd.service
stop nscd process actually
>2. execute: /usr/bin/nscd
start nscd by shell command
>3. execute: systemctl status nscd.service
inactive(dead)
systemctl can't know nscd is running
>4. excute: systemctl stop nscd.service
nscd process still exist, it seems that systemctl does not execute stop actually
How can I stop nscd.service when it start not by systemctl?

**Comment by evverx** [comment]
```sh
$ man nscd
...

       -K,--shutdown
              Shut the server down
...
```

The issue is neither a bug report nor a request for enhancement. Please use the mailing list https://lists.freedesktop.org/mailman/listinfo/systemd-devel or Q&A sites to ask questions.

**Comment by fishes9595** [comment]
What is the  Q&A sites to ask questions?  thank you.

**Comment by evverx** [comment]
It is something like https://unix.stackexchange.com/help/on-topic.

**Comment by poettering** [comment]
You may also use the systemd mailing list if you have questions or need help on systemd.

**Comment by fishes9595** [comment]
I use the systemd mailing list by my email 624001899@qq.com, but no one reply me. Why?

**Comment by poettering** [comment]
@fishes9595 in order to send a message to the mailing list you need to subscribe first. You are not among the subscribers right now.

Please visit https://lists.freedesktop.org/mailman/listinfo/systemd-devel it says that explicitly.
