### ISSUE TITLE
[RFE] Extend the udev sensor database to inform about the physical location of a sensor

### ISSUE THREAD

**Issue by fkroener** [systemd/systemd#6125]
### Submission type

 - Request for enhancement (RFE)

It'd be useful to support devices with accelerometers in both keyboard and display section as to indicate positioning relative to eachother for consumption in daemons like iio-sensors-proxy.

This would be useful as to indicate to the daemon which sensor to monitor for rotation purposes - right now iio-sensors-proxy unfortunately picks the wrong one in my case.

Maybe this field could be named `ACCEL_LOCATION` and have `display|keyboard` as possible values while defaulting to "display".

https://github.com/hadess/iio-sensor-proxy/issues/166 is the consuming issue of this RFE.

**Comment by poettering** [comment]
We really need a PR for this to be implemented.

Also, @hadess is really the champion for the sensors stuff. @hadess do you have an opinion on this?

**Comment by hadess** [comment]
I'm the one who mentioned using a property for this, seems like a good idea though I'd really like to have more data on the possible locations, comparison with this type of information in ACPI data, and how Windows handles it on that machine as well. I'm sure there's some MS design docs which explains how OEMs are supposed to handle this case, and building on top of that would having us making the worst mistakes.

**Comment by fkroener** [comment]
I booted Windows on the device. Attached you will find an image of the device manager.

It appears that Windows is properly differentiating between Display and Base.
Playing around a little with it, it appears to be using the sensors' relative positioning to eachother to enter tablet mode. 

For example: keeping the display upright and moving the keyboard around is detected properly and leads to disabling of keyboard/touchpad and entering tablet mode.

Please advise anything you'd like tested so I can remove the image asap.

<img width="960" alt="windows-devices" src="https://user-images.githubusercontent.com/28690007/33688756-d4079cbe-dadc-11e7-9d69-e75208797e4b.png">

**Comment by ljmf00** [comment]
Reference to kernel patch [#1057409](https://lore.kernel.org/patchwork/patch/1057409/)

**Comment by ljmf00** [comment]
This issue should be closed too due to #12322 PR.

**Comment by poettering** [comment]
ok
