### ISSUE TITLE
Inconsistent semantic for daemon-reload

### ISSUE THREAD

**Issue by amarao** [systemd/systemd#6130]
All regular systemctl commands use semantics [verb] [noun] (restart foobar, is-active foobar, status foobar, cat foobar.service, list-units, list-timers, reset-failed, etc).

Command daemon-reload use reverse semantic [noun][verb] and this is confusing.

I think adding alias 'reload-daemon' for daemon-reload would make command-line syntax more streamlined.

**Comment by poettering** [comment]
Hmm, I am not sure I like adding a redundancy like that. It's a bit of a bikeshedding thing.

**Comment by amarao** [comment]
But could you provide justification for using noun-verb combination for a single command from a long list of verb-noun?

I feel that consistency in human-facing interfaces is crucial for 'smoothness of use'. Just to show you how bad it may become - look at openstack command line. They call it 'instance' at some places, 'server' at other. They can put 'key' on flavor, but they call it 'meta' in other places, and 'property' at third. Overall it leaves user at lost. Should it be 'instance' or 'server'? Which verb to use? 'Dump' or 'cat' or 'show' or 'get'? Oh, now, that time they used 'details'. And at next place it is a 'describe'. I'm not joking, it's actual openstack commands. And they look horrible.

I don't want a key software in modern linux distros to become like openstack cli. Consistency is key to smooth experience.

**Comment by bl33pbl0p** [comment]
If this is being done, then it needs to be done to `daemon-reexec` too.

**Comment by keszybz** [comment]
I'd be against changing it. While consistency is important, this is a very well known verb, and having "daemon" first makes it slightly easier for tab-completion.

**Comment by poettering** [comment]
OK, I hope this makes some sense. Closing, sorry!
