### ISSUE TITLE
Update HACKING - qemu-kvm isn't a separate binary anymore.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#6131]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> …

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo Linux

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

Update `qemu-kvm` to `qemu-system-x86_64 -enable-kvm` as it is not a separate binary anymore, in https://github.com/systemd/systemd/blob/master/HACKING, line number 33.

**Comment by bl33pbl0p** [comment]
Pull request #6138 has been submitted by @AsciiWolf. Closing.

**Comment by keszybz** [comment]
This will get closed when the PR is merged.
