### ISSUE TITLE
failed to start ntpd ,or  timedatectl , hostnamectl

### ISSUE THREAD

**Issue by todaygood** [systemd/systemd#6135]
### Submission type
 - Bug report

### systemd version the issue has been seen with

systemd-219-30.el7_3.8.x86_64
systemd-sysv-219-30.el7_3.8.x86_64
systemd-libs-219-30.el7_3.8.x86_64

### Used distribution
Centos7.3
 

### In case of bug report: Expected behaviour you didn't see
the following command   can return right value as usual.

### In case of bug report: Unexpected behaviour you saw
[root@cloud-sz-master-b12-03 _data]# timedatectl 
Failed to query server: Connection timed out
[root@cloud-sz-master-b12-03 neutron]# systemctl start ntpd
Job for ntpd.service failed because a timeout was exceeded. See "systemctl status ntpd.service" and "journalctl -xe" for details.
[root@cloud-sz-master-b12-03 neutron]# hostnamectl 
[root@cloud-sz-master-b12-03 neutron]# 

### In case of bug report: Steps to reproduce the problem
I don't know , but often happened in my several servers.

**Comment by todaygood** [comment]
[root@cloud-sz-master-b12-03 _data]# busctl --system
NAME                                   PID PROCESS         USER             CONNECTION    UNIT                 
:1.0                                     1 systemd         root             :1.0          -                    
:1.1                                 56758 tuned           root             :1.1          tuned.service        
:1.2                                 56778 polkitd         polkitd          :1.2          polkit.service       
:1.7                                 30270 busctl          root             :1.7          session-1225.scope   
com.redhat.tuned                     56758 tuned           root             :1.1          tuned.service        
fi.epitest.hostap.WPASupplicant          - -               -                (activatable) -                    
fi.w1.wpa_supplicant1                    - -               -                (activatable) -                    
org.freedesktop.DBus                     - -               -                -             -                    
org.freedesktop.PolicyKit1           56778 polkitd         polkitd          :1.2          polkit.service       
org.freedesktop.hostname1                - -               -                (activatable) -                    
org.freedesktop.import1                  - -               -                (activatable) -                    
org.freedesktop.locale1                  - -               -                (activatable) -                    
org.freedesktop.login1                   - -               -                (activatable) -                    
org.freedesktop.machine1                 - -               -                (activatable) -                    
org.freedesktop.systemd1                 1 systemd         root             :1.0          -                    
org.freedesktop.timedate1                - -               -                (activatable) -

**Comment by poettering** [comment]
Sorry, but we only track issues in the two most recently released systemd versions upstream, and that's currently 232 and 233. 219 is waaaaay to old. This is made abundantly clear in the issue submission form btw.

Please contact your distro for help with issues in older systemd versions.

Thank you for understanding

**Comment by boucman** [comment]
had to debug that recently for a customer, I was not able to fix it, but restarting systemd (systemctl daemon-reexec) will get rid of the problem. the real fix is, of course, to use a newer version.

**Comment by todaygood** [comment]
It doesn't wok after run "systemctl daemon-reexec" , ok, I will test the new version
