### ISSUE TITLE
Setting Type=oneshot for LSB/SysV init scripts does not change the Timeout

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6143]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v232

### Used distribution

Debian sid

The systemd.service man page says:
```

       TimeoutStartSec=
           Configures the time to wait for start-up. If a daemon service does not signal start-up completion
           within the configured time, the service will be considered failed and will be shut down again. Takes a
           unit-less value in seconds, or a time span value such as "5min 20s". Pass "infinity" to disable the
           timeout logic. Defaults to DefaultTimeoutStartSec= from the manager configuration file, except when
           Type=oneshot is used, in which case the timeout is disabled by default (see systemd-system.conf(5)).
```

I just tried to change the type of a SysV init script via a drop-in snippet to Type=oneshot:
```
$ cat /etc/systemd/system/sysv.service.d/override.conf
[Service]
Type=oneshot
```
Contrary to the documentation, this did *not* change the timeout to infinity:
```
$ systemctl show -p TimeoutStartUSec -p TimeoutStopUSec
TimeoutStartUSec=5min
TimeoutStopUSec=5min
```
I assume this is a result of 
```
$ grep Timeout /run/systemd/generator.late/sysv.service 
TimeoutSec=5min
```

We should either document this shortcoming for SysV init scripts or fix the sysv-generator somehow.

**Comment by arvidjaar** [comment]
> `TimeoutSec=5min`

This directly corresponds to `DEFAULT_SYSV_TIMEOUT_USEC` before sysv-generator was factored out. So the behavior was always to have special hard-coded timeout for sysv services. Not sure if we can change it now (by removing explicit `TimeoutSec`), as it will lower timeout and may cause failures.

**Comment by poettering** [comment]
uh, i am not sure this is worth documenting. This appears to be an absolute corner case. People shouldn't assume that SysV scripts are extensible like native units. And if you really go as far as doing that, then you should be knowledgeable enough to understand what's going on and why this is not applied.

Moreover, the usecase is seriously flawed. A SysV script that is Type=oneshot makes no sense. there's no such concept as a oneshot service in SysV... 

Sorry, but I really don't think we need to document every corner case on the planet, in particular ones where the usecase is so obviously synthetic.

Extensive document is good, but documentation that loses itself in exotic corner cases stops being helpful and just makes things hard to read. Also, who'd even look for this in the docs?

Sorry, but I am closing this bug. I hope this makes sense.

**Comment by mbiebl** [comment]
> uh, i am not sure this is worth documenting. This appears to be an absolute corner case. People shouldn't assume that SysV scripts are extensible like native units. And if you really go as far as doing that, then you should be knowledgeable enough to understand what's going on and why this is not applied.
> 
> Moreover, the usecase is seriously flawed. A SysV script that is Type=oneshot makes no sense. there's no such concept as a oneshot service in SysV...

Well, there are SysV init scripts which start long running daemons for which ```Type=forking``` makes sense and then there are the ones which only run a series of commands without actually starting a daemon. ```Type=oneshot``` makes a lot more sense for those init scripts.

> Sorry, but I really don't think we need to document every corner case on the planet, in particular ones where the usecase is so obviously synthetic.
> 
> Extensive document is good, but documentation that loses itself in exotic corner cases stops being helpful and just makes things hard to read. Also, who'd even look for this in the docs?
> 
> Sorry, but I am closing this bug. I hope this makes sense.

I don't find your arguments convincing in this case, but ok, your call.
