### ISSUE TITLE
systemd - "PartOf" unit file option has no effect

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#615]
systemd version 222 on Arch Linux.

Attempting to create a dependency, having wpa_supplicant start and stop with insertion and removal of an associated pcmcia/pccard wireless network card, using "PartOf" in the unit file, fails.

The documentation at man 5 systemd.unit says:

PartOf=
... When systemd stops or restarts the units listed here, the action is propagated to this unit. ...

Using wpa_supplicant-nl80211@wlp6s0.service with:

[Unit]
Description=WPA supplicant daemon (interface- and nl80211 driver-specific version)
After=sys-subsystem-net-devices-%i.device
PartOf=sys-subsystem-net-devices-%i.device
[Service]
Type=simple
ExecStart=/usr/bin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-nl80211-%I.conf -Dnl80211 -i%I
[Install]
Alias=multi-user.target.wants/wpa_supplicant-nl80211@%i.service

then:
$ systemctl --reverse list-dependencies wpa_supplicant-nl80211@wlp6s0.service
wpa_supplicant-nl80211@wlp6s0.service
● ├─sys-subsystem-net-devices-wlp6s0.device
● └─multi-user.target
●   └─graphical.target

but plugging the card, with wpa_supplicant stopped manually, " systemctl list-units|grep wlp" gives:

 sys-devices-pci0000:00-0000:00:1e.0-0000:05:01.0-0000:06:00.0-net-wlp6s0.device
  loaded    active   plugged   AR5416 Wireless Network Adapter [AR5008 802.11(a)bgn]
 sys-subsystem-net-devices-wlp6s0.device
  loaded    active   plugged   AR5416 Wireless Network Adapter [AR5008 802.11(a)bgn]
 wpa_supplicant-nl80211@wlp6s0.service
  loaded    inactive dead      WPA supplicant daemon (interface- and nl80211 driver-specific version)

and removing the card, with wpa_supplicant started manually, gives:

 sys-subsystem-net-devices-wlp6s0.device
  loaded    inactive dead      AR5416 Wireless Network Adapter [AR5008 802.11(a)bgn]
 wpa_supplicant-nl80211@wlp6s0.service
  loaded    active   running   WPA supplicant daemon (interface- and nl80211 driver-specific version)

**Comment by heftig** [comment]
Removing a device makes the unit disappear without actively "stopping" it. You want BindTo, not PartOf.

**Comment by poettering** [comment]
@heftig is right. Closing.
