### ISSUE TITLE
LLDP messages containing padding are dropped

### ISSUE THREAD

**Issue by speakinghedge** [systemd/systemd#6150]
### Submission type

Bug report

### systemd version

232-25

### Used distribution

Debian 9.0

### Expected behavior

- networkctl lldp shows information taken from LLDP messages containing padding after EndOfLLDPDUTLV, see note in standard IEEE Std 802.1AB-2016, p. 42, sec. 8.5.1: 
```
For example, the IEEE 802.3 MAC adds pad octets to complete a minimum length data field if the 
user’s data is less than the minimum required length. Since pad octets are unspecified, an End Of  
LLDPDU TLV can be used to prevent non-zero pad octets from being interpreted by the receiving 
LLDP agent as another TLV.
```

### Unexpected behavior

- LLDP messages containing padding after EndOfLLDPDUTLV are ignored/dropped

### Steps to reproduce the problem

- configure interface X to accept LLDP reports
- switch interface to promiscuous mode (AFAIK already covered by another issue) 
- send short LLDP DU ( < 60 bytes, just ChassisID = 'A' / PortID = 'B', TTL and EndOfTLV - no capabilities TLV - padding applied) from external device to interface X (see [lldp-with-padding.pcapng.base64.txt](https://github.com/systemd/systemd/files/1086538/lldp-with-padding.pcapng.base64.txt) - contains 32 bytes padding after EndOfTLV)
- networkctl lldp shows **no** entry for  ChassisID = 'A' / PortID = 'B' ...
- replay trace [lldp-no-padding.pcapng.base64.txt](https://github.com/systemd/systemd/files/1086539/lldp-no-padding.pcapng.base64.txt)
 -> entry ChassisID ='A01234567890123456789012345678901' / PortID = 'B' present

**Comment by speakinghedge** [comment]
just from a quick view on the code in lldp-neighbor.c:
- 802.1q tags are ignored / not handled
- the order of the TLVs is not enforced - standard says ChassisID/PortID/TTL ... EndOfTLV

Is this an expected behavior or should I open new tickets?

**Comment by poettering** [comment]
please open separate bugs for separate issues. Of course we try to follow the spec, but try to be permissive in what we accept.

**Comment by ssahani** [comment]
Precisely which manufacturer sending these LLDP messages ?

**Comment by speakinghedge** [comment]
> please open separate bugs for separate issues. 

will do.

> Of course we try to follow the spec, but try to be permissive in what we accept.

agree.

**Comment by speakinghedge** [comment]
> Precisely which manufacturer sending these LLDP messages ?

This is not a manufacturer specific issue - but I agree that my example looked like some synthetic edge case. 

Better example:

```
ChassisID(type=MAC, name='01:02:03:04:05:06')/PortID(type=INTERFACE_NAME, name='port-0')/TTL()/SystemCapabilities()/SystemName(name='tor-sw-00')/End()
```

This message reflects a common scenario but even if the LLDP message contains the capabilities TLV and system name TLV all string based TLVs need to consume a total of 26 bytes or padding will be applied (in this case we will get 5 bytes of padding on top).
