### ISSUE TITLE
RFE: Support seamless service restarts

### ISSUE THREAD

**Issue by OlafvdSpek** [systemd/systemd#6161]
1. Start new service instance
2. Once new instance is ready and accepting new connections, stop old instance from accepting connections. Might require kernel support to ensure no connections get lost.
3. Have old instance stop itself once it's done servicing all existing connections.

Benefits:
Old instance remains available if new instance fails to start (for whatever reason).
Slow starts of new instance don't cause service disruptions.

**Comment by zdzichu** [comment]
This would require support from the service itself, won't it? I know that nghttpx (from nghttp2) works this way. 
Alternatively, service can store open fd's in systemd and deserialize them in new instance - just like systemd-logind does.

**Comment by OlafvdSpek** [comment]
> This would require support from the service itself, won't it?

Yes, but I think it requires updates to systemd and maybe the kernel as well.
Or does systemd already support this? If so, I could use some pointers.

**Comment by zdzichu** [comment]
Any more pointers? Check logind's source code wrt to sd_pid_notify_with_fds() usage. Check nghttpx code in [nghttp2](https://github.com/nghttp2/nghttp2)

**Comment by poettering** [comment]
This is all supported just fine to the level we can support that, and the rest has to be implemented in the services themselves.

The per-service "fd store" (see FileDescriptorStoreMax= in systemd.service(5) for details) exists precisely to make this happen: serialize your state into a memfd, and push it and any other fds (such as connection sockets) into the fd store and exit. Then, after the restart you'll get the same fds passed back in. Deserialize your state from the memfd and make use of the fds and you should be happy. 

Closing, as we already implement this.

**Comment by OlafvdSpek** [comment]
I'm not sure I agree.
If I understand you correctly you're saying to stop before starting.. I'm requesting to start before stopping.

If one uses systemd to create the sockets (which I do) the transferring of sockets doesn't seem to be necessary as it's already taken care of nicely.

**Comment by poettering** [comment]
So you want to instances run in parallel for a possibly very long time, possibly even an eternity if a client doesn't ever disconnect? I am not sure I like the concept. I am all for making restarts seamless, but I think it's essential that connections are handed over too, and that means stopping before starting is a much nicer, simpler solution as services can remain true singletons that way.

**Comment by OlafvdSpek** [comment]
> So you want to instances run in parallel 

Yes

> for a possibly very long time, possibly even an eternity if a client doesn't ever disconnect?

That's up to the design / implementation of the services. 
For a HTTP server, not accepting new connections, closing idle connections and finishing requests seems good and a connection handler in the old process probably isn't much more expensive then the same connection handler in the new process.

>  but I think it's essential that connections are handed over too, and that means stopping before starting is a much nicer, simpler solution as services can remain true singletons that way.

For at least haproxy that doesn't appear to cover all cases: https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/
Transferring all state might be complex too.

I agree that start before stop isn't a good idea for all cases but I'm sure for some cases it's the right solution.

For example, what if the daemon is lightweight but for whatever reason the new instance can't be started properly? With this the old daemon would still be around.

**Comment by poettering** [comment]
> For a HTTP server, not accepting new connections, closing idle connections and finishing requests seems good and a connection handler in the old process probably isn't much more expensive then the same connection handler in the new process.

Well, there are long-running HTTP requests, for SSE and things, I am not convinced its that easy.

But more importantly: systemd makes strict guarantees around the lifecylce of services: when you restart a service we'll kill every single process created by it, we clean up properly, regardles how many times the service forked away, regarldess how many CGI processes or whatnot it might have started as subprocesses which tried to detach. That's a guarantee we make to the admin, so that he knows that nothing remains of the previous run. 

Now if we'd permit processes to stick around during a restart, then we#d throw this guarantee out of the window: a restart would *not* clean up all processes anymore — it would have to leave at least some around (and how would you determine which ones are those "some"?). And that's why I really really don't like the idea... I hope that makes some sense?

**Comment by poettering** [comment]
Note that systemd knows two distinct verbs: service restarts and service reloads. The former make the process clean-up guarantee, the latter OTOH assumes processes stay running. The latter also covers cases where the service forks a new process during reload, and then lets the old process die — all that is require to make this work is that the new main process of the service tells systemd about it using an sd_notify("MAIN_PID=4711") message...

Hence I have the suspicion that you are looking for reloads, not restarts?

**Comment by zdzichu** [comment]
> the service forks a new process during reload, and then lets the old process die — all that is require to make this work is that the new main process of the service tells systemd about it using an sd_notify("MAIN_PID=4711") message

And this is exactly what [nghttpx does](https://github.com/nghttp2/nghttp2/commit/fdb75ba5fe341454853c6335e349d348ba99d69b). If only OlafvdSpek followed the pointers I gave in the first comment, this whole discussion would be unnecessary.

**Comment by OlafvdSpek** [comment]
> If only OlafvdSpek followed the pointers I gave in the first comment, 

I was hoping for proper documentation / guides. Surely  nghttpx isn't the best documentation for systemd is it?

**Comment by OlafvdSpek** [comment]
> I hope that makes some sense?

It does and it doesn't. The guarantee is good, wouldn't it be nice if it extended to my scenario?

> Hence I have the suspicion that you are looking for reloads, not restarts?

Maybe, I don't know.
Reloading is traditionally associated with reloading configuration files and reopening log files, not with restarting processes (as far as I know).
What if the daemon can't start a new instance of itself, for example due to (SELinux) permissions or something else?
