### ISSUE TITLE
meson: make it possible to install test-udev without running it on "ninja test"

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6163]
Currently the test-udev test is marked as manual, as it requires root privileges to run successfully, which typically isn't the case in a buildd environment.

In Debian we run test-udev as part of the autopkgtest tests though, for that the test needs to be installed into the systemd-tests package.
This is currently done manually in
https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/rules#n250

Unfortunately this no longer works under meson, as test-udev now links libsystemd-shared and requires a properly set RUNPATH. The binary in the build directory has the RUNPATH set to $ORIGIN/src/shared so no longer works when installed manually via cp.

We can either make test-udev link against libsystemd-shared statically (as was done with autotools), or maybe better, install test-udev on "ninja install" but not run it on "ninja test".

**Comment by mbiebl** [comment]
@keszybz Looking at https://github.com/systemd/systemd/blob/master/meson.build#L2205, I wonder how to best implement this: should we add another type besides "manual" and "unsafe", say "install"?

Or do we just add an explicit ```executable()``` for test-udev instead of defining it via the tests array.

Thoughts?

**Comment by keszybz** [comment]
I think we should take a different approach — just install all manual tests in a separate subdir (`/usr/lib/systemd/tests/manual` probably). The reason is that if `test-udev` is installed `/usr/lib/systemd/tests` then you need special knowledge that this test cannot be run automatically, etc. So I think it should be separated, and then there's no reason not to install all of them.

**Comment by mbiebl** [comment]
Works for me, I'll cancel #6172 then.
What about unstafe tests? Install them as well as ```/usr/lib/systemd/tests/manual```?

**Comment by mbiebl** [comment]
Or rather ```/usr/lib/systemd/tests/unsafe```

**Comment by keszybz** [comment]
Yeah, I don't see why not…
