### ISSUE TITLE
machinectl pull-tar fails when an nspawn settings file is given

### ISSUE THREAD

**Issue by azenla** [systemd/systemd#6188]
### Submission type
 - Bug report

### systemd version the issue has been seen with

> systemd 233
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid

### Used distribution

> Arch Linux

### Expected behaviour you didn't see

> Expected pull-tar to copy the settings file successfully.

### Unexpected behaviour you saw

> Got 94% of https://env.fork.run/raptor/build.txz. 4s left at 5.6M/s.
Got 95% of https://env.fork.run/raptor/build.txz. 3s left at 5.6M/s.
Got 97% of https://env.fork.run/raptor/build.txz. 2s left at 5.6M/s.
Got 98% of https://env.fork.run/raptor/build.txz. 1s left at 5.6M/s.
Got 99% of https://env.fork.run/raptor/build.txz. 69ms left at 5.6M/s.
Download of https://env.fork.run/raptor/build.txz complete.
SHA256 checksum of https://env.fork.run/raptor/build.txz is valid.
SHA256 checksum of https://env.fork.run/raptor/build.txz.nspawn is valid.
gpg: Signature made Fri 23 Jun 2017 10:42:20 PM EDT
gpg:                using RSA key 218FB54BEB42FFEC
gpg: Good signature from "Kenneth Endfinger (Spinlock Labs) <kaendfinger@gmail.com>" [unknown]
gpg: WARNING: Using untrusted key!
Signature verification succeeded.
Assertion 'i->settings_path' failed at src/import/pull-tar.c:366, function tar_pull_job_on_finished(). Aborting.

### Steps to reproduce the problem

> gpg --no-default-keyring --keyring /etc/systemd/import-pubring.gpg --keyserver hkp://pgp.mit.edu --recv-keys EB42FFEC
machinectl pull-tar https://env.fork.run/raptor/build.txz raptor

**Comment by poettering** [comment]
Fix waiting in #6203
