### ISSUE TITLE
Please consider implementing bash-like parameter-expansion options

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#619]
Hi,

I would like to be able to write in a unit file:

```
[Service]
EnvironmentFile=-/etc/default/nifty
ExecStart=/usr/sbin/nifty -f ${NIFTYCONF:-$OLDERCONF}
```

with the semantics that, if NIFTYCONF is defined in /etc/default/nifty, the contents of NIFTYCONF is substituted, and if NIFTYCONF is not defined, the contents of OLDERCONF is substituted. This is a common idiom when a configuration option gets renamed to preserve backwards compatibility to older versionf of the configuration file.

Additionally, I would like to be able to write something along the line of:

```
nifty@.service:
[Service]
ExecStart=/usr/sbin/nifty -f nifty${%i:+-%i}.conf 
```

Which would start nifty -f nifty.conf if started as nifty@, and nifty -f nifty-foo.conf if started as nifty@foo. Without this construct, the config files would either need to be called nifty-.conf or niftyfoo.conf for either case.

Please consider adding some basic expansion options.

Greetings
Marc

**Comment by dvdhrm** [comment]
Service files are not scripts. We do not want conditionals in service file parsers, nor any code execution. Furthermore, the bash variable expansions are the least readable string manipulation functions I've seen so far, so I'd strongly object to adding those.

`EnvironmentFile` is used for limited backwards compatibility. It's not something we want to endorse, nor do we intend to extend support for it.

If there is an explicit use-case that is not supported by systemd right now, please describe it in detail. But we don't add new constructs just for the sake of it. Please elaborate on your use-cases.

**Comment by poettering** [comment]
I agree with @dvdhrm, we should not create another shell language, also see my reasoning for this in https://github.com/systemd/systemd/issues/618#issuecomment-123808429

Sorry.

**Comment by Zugschlus** [comment]
Fine. I'll note that as "systemd upstream wants the unit file to be this ugly" with a reference here in my code. I can live with that.
