### ISSUE TITLE
systemd-journal-upload does not working - systemd-journal-upload.service: Watchdog timeout (limit 3min)!

### ISSUE THREAD

**Issue by tears-of-noobs** [systemd/systemd#6195]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> On receiver, log files in /var/log/journal/remote are not updated
> On sender, process systemd-journal-upload - does not upload new changes from local journal files

### In case of bug report: Unexpected behaviour you saw

> On sender:
```
Jun 26 16:22:26 msdos.s systemd[1]: systemd-journal-upload.service: Watchdog timeout (limit 3min)!
Jun 26 16:22:26 msdos.s systemd[1]: systemd-journal-upload.service: Killing process 8078 (systemd-journal) with signal SIGABRT.
Jun 26 16:22:26 msdos.s systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jun 26 16:22:26 msdos.s systemd[1]: Started Process Core Dump (PID 9920/UID 0).
Jun 26 16:22:26 msdos.s systemd[1]: systemd-journal-upload.service: Main process exited, code=dumped, status=6/ABRT
Jun 26 16:22:26 msdos.s systemd[1]: systemd-journal-upload.service: Unit entered failed state.
Jun 26 16:22:26 msdos.s systemd[1]: systemd-journal-upload.service: Failed with result 'watchdog'.
Jun 26 16:22:26 msdos.s systemd-coredump[9923]: Process 8078 (systemd-journal) of user 996 dumped core.
                                                
                                               Stack trace of thread 8078:
                                                0  0x00007f2d94fa4230 poll (libc.so.6)
                                                1  0x00007f2d954c2599 n/a (libcurl.so.4)
                                                2  0x00007f2d954bcff2 curl_multi_wait (libcurl.so.4)
                                                3  0x00007f2d954b5750 curl_easy_perform (libcurl.so.4)
                                                4  0x00005573fa0a8871 n/a (systemd-journal-upload)
                                                5  0x00007f2d94ee143a __libc_start_main (libc.so.6)
                                                6  0x00005573fa0a98da n/a (systemd-journal-upload)
```
### In case of bug report: Steps to reproduce the problem

* Install ArchLinux
* On receiver configure systemd-journal-remote to listen external interface  with http protocol and start the service
* On sender configure systemd-journal-upload, set the -u/--url argument argument equal to the host receiver and start the service.
* Trying to follow remote log files on receiver - `journalctl -D /var/log/journal/remote -f`
* Make sure that new entries do not appear
* View logs on sender - `journalctl -u systemd-journal-upload`
* Аfter some time you will see - ` systemd-journal-upload.service: Watchdog timeout (limit 3min)!`

**Comment by evverx** [comment]
This issue is the same as https://github.com/systemd/systemd/issues/5744.
