### ISSUE TITLE
"systemctl -q is-enabled $service" prints misc. info messages on stderr despite the -q flag for legacy services

### ISSUE THREAD

**Issue by KimBrodowski** [systemd/systemd#6196]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233

### Used distribution

> Debian
### In case of bug report: Expected behaviour you didn't see

> With the "-q" flag set I would not expect any output apart from actual error messages.

### In case of bug report: Unexpected behaviour you saw

> The following line was printed: `Executing: /lib/systemd/systemd-sysv-install is-enabled $service`

### In case of bug report: Steps to reproduce the problem

> 1. Install squid/squid3
> 2. Run `systemctl -q is-enabled squid`
> 3. Take a look at the explanation given if you run it without the "-q" flag. `systemctl is-enabled squid` `squid.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install is-enabled squid
enabled`

**Comment by evverx** [comment]
The issue seems to have been fixed by https://github.com/systemd/systemd/commit/689e4e6a94222b4d58a8b9cb3c51cc2f82268aa9. Could you check again that `v233` is really being used?

**Comment by KimBrodowski** [comment]
That's what I was being told on #debian. I don't have a version that recent running myself.

**Comment by KimBrodowski** [comment]
Also this is only about the line `Executing: /lib/systemd/systemd-sysv-install is-enabled squid enabled` which does not appear to be affected by the commit.

**Comment by evverx** [comment]
https://github.com/systemd/systemd/commit/689e4e6a94222b4d58a8b9cb3c51cc2f82268aa9 partially fixes `-q is-enabled`. `systemctl` still prints `Executing: ...` https://github.com/systemd/systemd/blob/6c223c67190d1ba069f82c8c4d19ce88bda712be/src/systemctl/systemctl.c#L5915

**Comment by mbiebl** [comment]
fwiw, there is this old bug report for mine #3813

**Comment by mbiebl** [comment]
I guess the fix for #3813 was incomplete and  the ```!arg_quiet``` condition  should also be applied to the Executing... log line

**Comment by poettering** [comment]
Fix waiting in #6199.
