### ISSUE TITLE
Remote busctl retrieves some information from the host

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#6207]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemctl --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Debian Testing

### In case of bug report: Expected behaviour you didn't see

> 

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> Execute "busctl -H x@y". I believe busctl retrieves information from the remote target and tries to figure out its process name and service name from the host. 

Example output is this: 

:1.161                                      924 avahi-daemon    216              :1.161        avahi-daemon.service      -          -                  

It turns out both host and target have processes with same id, 924. Remote machine doesn't have a process called "avahi-daemon", doesn't have a service called "avahi-daemon.service.

**Comment by poettering** [comment]
Fix waiting in #6217.
