### ISSUE TITLE
RFE: poweroff some time after hybrid-sleep

### ISSUE THREAD

**Issue by gfa** [systemd/systemd#621]
when I used pm-utils to suspend-hybrid my laptop I was able to configure the laptop to shutdown after some time of suspend-hybrid. I used an hour or two as the time to poweroff.

the usecase for this feature is simple, if I use the laptop soon enough it will be suspended and resume will be fast, if I don't use it for hours it will be off instead of wasting battery (ok, not much but still) suspended.

I would like to do the same with systemd

**Comment by arvidjaar** [comment]
Hybrid suspend using system will hibernate system some time after suspend to RAM. I'm not sure whether timeout is configurable though.

**Comment by gfa** [comment]
@arvidjaar not in my experience, I left the laptop a whole night and it didn't fully poweroff.
I'm not using gnome or anything else. just systemd on debian
systemd 221 

I will left it hybrid-sleep tonight again to see if newer systemd behaves differently. even if it does and poweroff after some time my RFE stills, I want  to configure that time

**Comment by arvidjaar** [comment]
You are probably right. I'm using openSUSE 13.2 which still redirects suspend to pm-utils, so I guess pm-utils do it.

**Comment by arvidjaar** [comment]
@gfa 

> I left the laptop a whole night and it didn't fully poweroff

What is in /sys/power/disk? It determines what kernel does when hibernation is requested.

**Comment by gfa** [comment]
$ cat /sys/power/disk 
platform shutdown reboot [suspend] 
$ systemctl hybrid-sleep 
_resume from sleep_
$ cat /sys/power/disk 
platform shutdown reboot [suspend] 

$ echo shutdown | sudo tee /sys/power/disk
shutdown
$ cat /sys/power/disk
platform [shutdown] reboot suspend
$ systemctl hybrid-sleep
_resume from sleep :(_
$ cat /sys/power/disk
platform shutdown reboot [suspend] 

looks like systemd is overriding the setting

if you can think on any information that may be useful, I'm happy to provide/test it

**Comment by arvidjaar** [comment]
> looks like systemd is overriding the setting

man systemd-sleep.conf

**Comment by gfa** [comment]
if I set 

```
 cat /etc/systemd/sleep.conf 
[Sleep]
HybridSleepMode=shutdown
```

systemd will turn off my laptop right away, I don't want that. I want the laptop to be suspended for NN configurable time then shutdown

**Comment by gfa** [comment]
i'm looking for something like PM_HIBERNATE_DELAY=1800 setting on pm-utils

**Comment by arvidjaar** [comment]
Yes, I understand that. It could be implemented using script in /usr/lib/systemd/system-sleep/ and careful selection of options in sleep.conf. Unless this will be the only script run during sleep, it should be close enough match.

**Comment by poettering** [comment]
I am not convinced this is really something we should support natively in systemd. In particular as you can implement this on top of systemd's own logic the way @arvidjaar suggested with some scripts in /usr/lib/systemd/system-sleep/.

**Comment by gfa** [comment]
if implement as an script it would need to watch all the other scripts there in case of something breaks it. It should be ported to all kind of hardware and their RTC clocks 

implementation in systemd should be straightforward, if some flag is there (config option A) just put an RTC alarm and after the alarm do something (config option B). systemd knows the state and can handle failure (it could fallback to option C) 

I think this functionality is basic plumbing, and that's what systemd provides.

**Comment by gfa** [comment]
scripts in  /usr/lib/systemd/system-sleep/ need to finish before action can be taken. in order to implement the functionality in a script, that script should save the state somewhere to read it when the computer is awaken (by rtc or external factor) then decide what to do. that's pure pain and i remember more than once that failed on pm-utils leaving my laptop powered on in my backpack.

if hybrid-sleep and shutdown delay (to put a name on it) are configured, systemd should not fully resume the computer (after rtc alarm or external factor) but do the configured action (most likely hibernate, but fallback options should be considered). that cannot be done from /usr/lib/systemd/system-sleep/ script 

think about all things need to be resumed before /usr/lib/systemd/system-sleep/ scripts are run, that would be useful, prone to error and incorrect. the correct way to handle a power level change is down in systemd

**Comment by arvidjaar** [comment]
> It should be ported to all kind of hardware and their RTC clocks
> implementation in systemd should be straightforward

Implementation in systemd would need to be ported to all kind of hardware and their RTC clocks as well; how exactly it makes it more straightforward?

> think about all things need to be resumed before /usr/lib/systemd/system-sleep/ scripts are run

Actually those scripts are run as the very first thing after resume, so it is no different from what pm-utils does. Otherwise I agree that it is not perfect. Executing scripts in defined order would almost make it though ...

**Comment by gfa** [comment]
On 2015-07-24 11:58, Andrey Borzenkov wrote:

> ```
> It should be ported to all kind of hardware and their RTC clocks
> implementation in systemd should be straightforward
> ```
> 
> Implementation in systemd would need to be ported to all kind of
> hardware and their RTC clocks as well; how exactly it makes it more
> straightforward?

i think systemd has to do that work anyway to support systemd-timesyncd

> ```
> think about all things need to be resumed before
> /usr/lib/systemd/system-sleep/ scripts are run
> ```
> 
> Actually those scripts are run as the very first thing after resume, so
> it is no different from what pm-utils does. Otherwise I agree that it is
> not perfect. Executing scripts in defined order would almost make it
> though ...

i wish something better than pm-utils, i've mentioned before pm-utils
sometimes failed leaving my laptop power on in my backpack

i wish systemd would catch the rtc alarm and decided what to do _before_
fully wake the machine

**Comment by medhefgo** [comment]
Am I the only one who thinks this ought to be implemented by the kernel itself?
