### ISSUE TITLE
lightdm crashes and cannot start graphical session

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#6219]
### Submission type

 - Bug report

### systemd version the issue has been seen with

f62c9e50b (#6099). Its parent f9ce1a4a41b293d4a8e17794265490c9bdb3ace9 works fine.

### Used distribution

fedora 26 x86_64

### In case of bug report: Expected behaviour you didn't see

lightdm works fine and user can login graphically.

### In case of bug report: Unexpected behaviour you saw

lightdm starts but no keyboard input is accepted, mouse cursor ~~is not shown~~ does not move. So, I cannot change console neither shutdown system by mouse.

### In case of bug report: Steps to reproduce the problem

Boot the system with lightdm.

**Comment by yuwata** [comment]
~~I am not sure, but I guess the commit eca2995c5146fe9b15521633352214c140b23dde (#6210) cause this problem.~~

**Comment by yuwata** [comment]
Sorry the commit is not related. This bug is caused by f62c9e50ba51f5dafc358aed10485d42e84a34aa (#6099). Its parent f9ce1a4a41b293d4a8e17794265490c9bdb3ace9 works fine.

**Comment by whot** [comment]
do you have any logs from lightdm that could hint at what's going on here?

**Comment by yuwata** [comment]
@whot Unfortunately, all lightdm related log files are size 0. I guess that logs and journal are not flushed to disk because system crashes soon after lightdm starts.
Do you have any idea to get logs?

**Comment by hramrach** [comment]
You can also bisect the commits of pr #6099 to get an idea what change broke lightdm. Personally I am not aware of any change visible outside udev that would happen unless you add custom configuration.

Also what version of lightdm do you use? lightdm 1.22.0 works for me even with the patched systemd.

**Comment by yuwata** [comment]
@hramrach I've bisected the commits of PR #6099. The result is the following:
- 1b8332371 Use same script to build key list in Makefile and meson: OK
- c6dce2457 hwdb: support pressing buttons on a keyboard: OK
- 3ee4e61b1 hwdb: fix help text in 60-keyboard.hwdb: OK
- 38887d1bd rules: move input_id rule to a separate file: CRASH!!!

Note that I do not customize udev configuration.

**Comment by yuwata** [comment]
The current master HEAD 980cb558dc0293cc387597581a130542754195a0 with reverting 38887d1 works fine.

**Comment by yuwata** [comment]
Note that 38887d1bd5eb037a532279b2b75d6a87ce381419 does not break CUI sessions, that is, booting systemd with the kernel command option `3` works fine.

**Comment by hramrach** [comment]
Presumably what can happen is that some keyboard properties are added to non-keyboard evdev device handled by atkbd driver (does such thing exist?), lightdm assumes the device is a keyboard based on that property and crashes because of that. There is nothing else that should change as a result of 38887d1

**Comment by yuwata** [comment]
@hramrach Do you have any idea to check whether such thing actually happens or not?

**Comment by hramrach** [comment]
Yes, if you build with meson you will not get 60-input-id.rules

Which would mean lightdm crashes without input devices.

**Comment by yuwata** [comment]
Fixed by #6222. Thank you.
