### ISSUE TITLE
RFE: systemd-mount could support discovery of plain files

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#6226]
Another thing which we might make `systemd-mount` a bit nicer to use (now that #6211 is done ;)):
```console
$ systemd-mount  /var/tmp/image
Discovery only supported for block devices, don't know what to do.
```
but in principle we could run discovery the on the file, or even just use the file name as the mount point name (`/run/media/system/image` in this case).

/cc @yuwata

**Comment by yuwata** [comment]
@keszybz OK. I'll try it.
