### ISSUE TITLE
RFE: Add ability to trigger start of service on AC changes

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6229]
This is a follow-up to #6228. There are various use cases for a facility to start/stop services once the system is on AC (or battery)
Take services for example which have ```ConditionACPower=true``` set and missed to run during boot as the system was unplugged.
Or think of a backup or other CPU intensive or long running tasks.
In a lot of cases, such services don't start a long running daemon to listen for power events themselves.
So we need something else to trigger the start of such services. I think this should ideally be built into systemd directly, the same way we can trigger the start of services via udev rules using ```SYSTEMD_WANTS```.

Taking a trip down memory lane, this is something upstart solved very elegantly, as one could easily feed new events in and let jobs react to them.

**Comment by poettering** [comment]
Hmm. I am sorry but i dont think this really fits into systemd. I dont think we should have triggers for all random kinds of system events in systemd. Its very easy to write an external tool to that watches for some kind of event and then tells systemd to start something. This isnt any different than for the upstart case really. That knd of trigger really shouldnt be done by systemd itself, but could be done in upower or whatever you like

I will close this now, as I really dont think we should watch for AC states. And yeah ConditionACPower= i wouldnt to these days either...

**Comment by mbiebl** [comment]
The problem is, that we don't have such external daemon which can react on events. So we don't have a solution for use cases our users ask for rightfully so.

**Comment by poettering** [comment]
Upower sounds like a good place to do this, no? Consuder filing an RFE there?

**Comment by mbiebl** [comment]
@poettering I'm unclear how would this work. Can you share your ideas here.

In the past, upower supported pm-utils which could be extended via hook scripts that could trigger on ac and suspend/resume changes. This was ripped out though with the explanation that systemd could already do all that for us.

**Comment by mbiebl** [comment]
@poettering I didn't want to make my reply sound so snide. Sorry.
I'm honestly interested how you envision this should work:
- How would package register an interest in being started/stopped/restarted/reload on those events?
  - Do we describe that declaratively somewhere or provide hooks for scripts again?
  - If declaratively, should this be something inside the .service file or an external file?
- How would upower execute those requests, call the systemd D-Bus interface directly?

**Comment by poettering** [comment]
What#s the precise usecase for this btw?

Note that for suspend/resume these hook scripts exist. But for power plug/unplug they don't and I actually have the suspicion there really shouldn't be any.

**Comment by mbiebl** [comment]
@poettering some examples were in the initial bug report. anacron.service has ConditionACPower as it might run CPU intensive tasks which you don't necessarily want to run on battery.

**Comment by poettering** [comment]
Hmm, but that usecase appears to be better handled with a logic that just slightly delays those jobs and doesn't skip them entirely. I.e. maybe something like a setting in timer units "DelayNoACPower=" or so, where you can specify some time value, and which is then added in if AC power is not available or so...

I mean, after all, it should be a bounded delay really, and nothing more.

**Comment by boucman** [comment]
could that be done by marking some sort of udev device to appear as a .device in systemd and then binding to it ? that would have been my approch...
