### ISSUE TITLE
-k no longer causes a dry run for shutdown

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#623]
ref: https://bugs.archlinux.org/task/45710

Expected behavior: calling `shutdown -k` doesn't actually shutdown
Observed behavior: the system shuts down after the default delay.

I suspect f0efea232a582660b25ee992853c78cf825721b6 broke this, as it no longer respects 'arg_dry'.

**Comment by zonque** [comment]
@falconindy thanks for the report! Care to give my branch a quick check?

**Comment by falconindy** [comment]
I backported your two commits onto 222, rebooted, and ran `shutdown -k now foo`. It no longer issues a shutdown (so the dry run bits work again), but the wall message isn't displayed. For that matter, even without the `-k`, I don't see a wall message (on ttyS0). Using wall(1) does show a message written to my TTY, though. Sounds like a separate bug?

**Comment by dvdhrm** [comment]
Wall messages work perfectly fine for me. `shutdown -h` displays one and `shutdown -c` as well (except for the TTY that issues the request). Can you try narrowing it down? Is only ttyS0 affected? If yes, can you run strace on logind?

**Comment by zonque** [comment]
The problem is about a missing dry run feature for shutdowns in logind. My approach back then (#646) was to introduce boolean properties, but that was admittedly a hack. I will implement that as new methods in the DBus spec in the next days. Sorry for the delay.
