### ISSUE TITLE
UEFI boot stub loader uses racy mechanism for obtaining payload under Secure Boot

### ISSUE THREAD

**Issue by mjg59** [systemd/systemd#6230]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

The stub loader will be read by the firmware, relocated, have its signature validated and then be executed. It will then obtain the path it was loaded from and re-open that file in order to obtain the kernel, ramdisk and command line. If the storage device then returns different contents, this will allow booting untrusted code without failing signature validation.

**Comment by poettering** [comment]
Thats not really what happens. Thr stub only queries the source file to parse out the offsets. It doesnt actually use anyhting else. Hence exploting this would be very very hard. But yeah i figure these offsets could be parsed out of the already mapped image too

**Comment by kaysievers** [comment]
The entire image including the header seems to be loaded in memory, so we can try to read the PE section offsets from the already loaded image.

**Comment by mjg59** [comment]
Ok, I've got a working patch that implements that, just tidying it up and I'll post a PR.
