### ISSUE TITLE
Create /varl/log/lastlog in /usr/lib/tmpfiles.d/var.conf

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6234]
This was originally filed downstream as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866313 

Could you extend /usr/lib/tmpfiles.d/var.conf as follows?

f /var/log/lastlog 0664 root utmp -

systemd already creates /var/log/wtmp and /var/log/btmp if they do not
exist. For custom live-boot images that exclude files under /var/log/,
it would be nice to also create /var/log/lastlog, e.g., for sshd:

```
grep lastlog /var/log/auth.log
Jun 27 20:00:00 huron sshd[1234]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
```

**Comment by poettering** [comment]
Wouldnt it be better if ssh/pam would create the file if it is missing?

**Comment by mbiebl** [comment]
hm, apparently there are more tools then I expected which have a reference to /var/log/lastlog:
https://codesearch.debian.net/search?q=%2Fvar%2Flog%2Flastlog&perpkg=1
