### ISSUE TITLE
Command quoting rules are unclear

### ISSUE THREAD

**Issue by tgr** [systemd/systemd#624]
According to the systemd (215-17+deb8u1) man page `ExecStart` section:

> Each command line is split on whitespace, with the first item being the command to execute, and the subsequent items being the arguments. Double quotes ("...") and single quotes ('...') may be used, in which case everything until the next matching quote becomes part of the same argument. Quotes themselves are removed after parsing.

What systemd actually seems to be doing is only remove quotes which are next to whitespace. I. e. `'--foo=bar'` will be parsed as `--foo=bar` but `--foo='bar'` is parsed as `--foo='bar'`. This is unintuitive and different from how shells work; at the very least the documentation should clearly warn about it.

**Comment by poettering** [comment]
This was actually left unspecified intentionally, as we wanted some liberty to change behaviour in some details on this. However, that change has taken place now, so we really should coument this now.
