### ISSUE TITLE
When path pointed to by InaccessiblePaths doesn't exist, service fails to start

### ISSUE THREAD

**Issue by WGH-** [systemd/systemd#6243]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 233

### Used distribution

> Gentoo Linux

When `InaccessiblePaths` option points to nonexistent path, service fails to start with rather obscure error:
```
systemd[1]: Started foo.service.
systemd[3631]: foo.service: Failed at step NAMESPACE spawning /bin/true: No such file or directory
systemd[1]: foo.service: Main process exited, code=exited, status=226/NAMESPACE
systemd[1]: foo.service: Unit entered failed state.
systemd[1]: foo.service: Failed with result 'exit-code'.
```
Note that this happens even when only the last component doesn't exists, e.g. `/bin/foobar` when `/bin` exists.

Apparently, the error is caused by this check: https://github.com/systemd/systemd/blob/16a5d4128f853b6ed4080db78d9ce9e50773bc44/src/core/namespace.c#L727
```c
if (lstat(mount_entry_path(m), &target) < 0)
    return log_debug_errno(errno, "Failed to lstat() %s to determine what to mount over it: %m", mount_entry_path(m));
```
systemd checks file type in order to mount inaccessible file of matching type (directory, regular file, etc.).

I think that the check is over-restrictive. What the problem with mounting some inaccessible file there anyway, even though file type might mismatch in the future?

If systemd mounted some arbitrary file type, it would allow using InaccessiblePaths to prevent access to files that may appear later on. And by extension, it would also eliminate obscure and hard to debug error.

**Comment by poettering** [comment]
Note that you may prefix paths with `-` to ensure that missing paths are ignored. To quote to the man page:

> Paths in ReadWritePaths=, ReadOnlyPaths= and InaccessiblePaths= may be prefixed with "-", in which case they will be ignored when they do not exist. If prefixed with "+" the paths are taken relative to the root directory of the unit, as configured with RootDirectory=/RootImage=, instead of relative to the root directory of the host (see above). When combining "-" and "+" on the same path make sure to specify "-" first, and "+" second.

Closing this, as this is documented behaviour, and there's a documented option to get the behaviour you are asking for.

(unless I misunderstood you, and you are saying that the `-` prefixing is borked and doesn't work. If so, please say something and we'll reopen the bug)
