### ISSUE TITLE
TEST-01-BASIC regression: Failed to allocate manager object: Read-only file system

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#6253]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> master

Apparently someone recently let a regression land that breaks our upstream test/TEST-01-BASIC (and perhaps the subsequent ones, as it now never gets past that):
```
+ env --unset=UNIFIED_CGROUP_HIERARCHY systemd-nspawn --register=no --kill-signal=SIGKILL --directory=/var/tmp/systemd-test.bntMGf/nspawn-root /lib/systemd/systemd root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd ro console=ttyS0 selinux=0
Spawning container nspawn-root on /var/tmp/systemd-test.bntMGf/nspawn-root.
Press ^] three times within 1s to kill container.
Timezone Etc/UTC does not exist in container, not updating container timezone.
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to [1mUbuntu 16.04.2 LTS[0m!

Set hostname to <systemd-testsuite>.
Initializing machine ID from container UUID.
Got address error code: Operation not permitted
Got address error code: Operation not permitted
Got start error code: Operation not permitted
Using cgroup controller name=systemd. File system hierarchy is at /sys/fs/cgroup/systemd/../../../machine.slice/nspawn-root.scope.
Failed to install release agent, ignoring: No such file or directory
[0;1;31mFailed to create /../../../machine.slice/nspawn-root.scope/init.scope control group: Read-only file system[0m
[0;1;31mFailed to allocate manager object: Read-only file system[0m
[[0;1;31m!!!!!![0m] Failed to allocate manager object, freezing.
[0;1;31mFreezing execution.[0m
```
This happens on every recent PR, e. g. in [this log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20170630_235331_f030a@/log.gz).

**Comment by martinpitt** [comment]
Some data:
 - PR #6214 from 4 days ago was apparently the last CI run that succeeded; PR #6215 also succeeded this test still.
 - in PR #6223 the test failed this way on i386
 - In between those (`git shortlog 980cb5..56892b0`) there are only three  commits, none of which are related to nspawn boots:
```
Michael Biebl (1):
      Merge pull request #6222 from keszybz/input-id-rules-installation

Stefan Schweter (1):
      man: update reference for binfmt documentation (#6223)

Zbigniew Jędrzejewski-Szmek (2):
      build-sys: fix installation of new 60-input-id.rules
      resolved: drop unnecessary comparison (#6220)
```
 - Given the fact that it sometimes seems to succeed, and affects i386 or amd64, this suggests a race condition, so it's not entirely obvious when it was introduced.
 - This perfectly reproduces locally (tested on Fedora 26) with `sudo make -C test/TEST-01-BASIC clean setup run`.
 - After the above, the hang can be reproduced in split-seconds by just running the nspawn command:
```
$ sudo env --unset=UNIFIED_CGROUP_HIERARCHY ../../systemd-nspawn --register=no --kill-signal=SIGKILL --directory=/var/tmp/systemd-test.1Czp1u/nspawn-root /usr/lib/systemd/systemd root=/dev/sda1 raid=noautodetect loglevel=2 init=/usr/lib/systemd/systemd ro console=ttyS0 selinux=0
Got address error code: Operation not permitted
Got address error code: Operation not permitted
Got start error code: Operation not permitted
Unified cgroup hierarchy is located at /sys/fs/cgroup/unified/../../../../machine.slice/nspawn-root.scope. Controllers are on legacy hierarchies.
Failed to create /../../../../machine.slice/nspawn-root.scope/init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```
The unified vs. split hierarchy line looks slightly different in the CI vs. local case, but the overall bug seems to be the same.

**Comment by evverx** [comment]
@martinpitt could you try
```
sudo env UNIFIED_CGROUP_HIERARCHY=no ...
```
instead of
```
sudo env --unset=UNIFIED_CGROUP_HIERARCHY ...
```
?

Do you know if the kernel used by the CI has been updated recently?

**Comment by keszybz** [comment]
I'd suspect cd2dfc6faea2a1e2370ae52460247bb6c8c553b1.

**Comment by evverx** [comment]
@keszybz , thanks for the link. I'm puzzled about why `UNIFIED_CGROUP_HIERARCHY=no` always works and where `init.scope control group: Read-only file system`  comes from.

**Comment by martinpitt** [comment]
FTR, I'm still bisecting (mostly not at home, just flying by for a few minutes in each round). Will confirm in a bit.

**Comment by martinpitt** [comment]
Took a little longer as just a bisect misled me (I should have run the test more than once, as this isn't 100% reliable).

 * Confirmed that it is commit https://github.com/systemd/systemd/commit/cd2dfc6faea2a1e2370ae52460247bb6c8c553b1 aka PR #6166. nspawn immediately fails with that, and with the commit before it successfully ran it 20 times. Curiously https://github.com/systemd/systemd/pull/6166#issuecomment-310920729 even already detected this, but it was merged anyway. CI even succeeded there (so nobody is to blame here), but as noted above this only seems to happen sometimes.

 * The kernel was changed a bit (4.4.0-81-generic vs. -83-generic), but these are only security updates and shouldn't affect the general behaviour of cgroups. Also, I reproduce this locally on F26 with kernel 4.11.7.

 * sudo `env UNIFIED_CGROUP_HIERARCHY=no` *does* work fine.

**Comment by evverx** [comment]
I managed to reproduce the issue on F26. I haven't seen `Read-only file system` though. It doesn't seem to be caused by the delegation, which was mentioned in https://github.com/systemd/systemd/pull/6166#issuecomment-310985370, because the following patch makes `--register=no` work without `UNIFIED_CGROUP_HIERARCHY=no`:
```diff
index ffdf1239f..5faa25956 100644
--- a/src/nspawn/nspawn-register.c
+++ b/src/nspawn/nspawn-register.c
@@ -334,6 +334,7 @@ int allocate_scope(
                 log_error("Failed to allocate scope: %s", bus_error_message(&error, r));
                 return r;
         }
+        sleep(5);

         return 0;
 }
```

**Comment by martinpitt** [comment]
@evverx: confirmed here

**Comment by keszybz** [comment]
> Curiously #6166 (comment) even already detected this, but it was merged anyway.

Yeah, my bad. Sorry.
