### ISSUE TITLE
systemd-netword - [DHCP] Request support for blacklisting servers

### ISSUE THREAD

**Issue by jokogr** [systemd/systemd#6260]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

### Used distribution

> NixOS

### Details

dhcpcd is allowed to ignore all packets from a certain DHCP server address via the `blacklist` option ([man 5 dhcpcd.conf](https://www.daemon-systems.org/man/dhcpcd.conf.5.html)). I would like to see this feature on systemd-networkd, too.

**Comment by poettering** [comment]
wouldn't a firewall do a better job for this?

**Comment by jokogr** [comment]
@poettering you do have a point. I thought that systemd-networkd starts much earlier than the firewall, but at least for NixOS this is not the case: `firewall.service` wants `network-pre.target`, whereas `systemd-networkd.service` wants `network.target`.

Therefore, it might be more efficient to just block UDP packets coming from ports 67-68 of a certain source.

**Comment by jokogr** [comment]
I have tried to use iptables as a firewall to block DHCP offers from a certain server and it appears this is not possible.

I have tried the following approaches, one MAC-based and another IP-based:

```
iptables -A INPUT -m mac --mac-source <DHCP_SERVER_MAC> -p udp --sport 67:68 -j DROP
```

and:

```
iptables -A INPUT -s <DHCP_SERVER_IP> -p udp --sport 67:68 -j DROP
``

After searching for a while, I have found [this](https://unix.stackexchange.com/questions/447440) which mentions that it is impossible to filter a DHCP server via iptables. Maybe something similar applies to the DHCP server.

@poettering So, could a `blacklist` functionality added for DHCP client configuations, please?
