### ISSUE TITLE
No output from systemd-journal-gatewayd

### ISSUE THREAD

**Issue by vmatyushin** [systemd/systemd#627]
I have just compiled version from git.
I run systemd-journal-gatewayd as root.
When I open http://localhost:19531/entries I see nothing.
When I open http://localhost:19531/browse I see only predefined html but no log entries.

I can successfully enumerate journal entries in request_handler_entries().
But then request_reader_entries() is called, and this is where the issue occurs.
sd_journal_next() returns 0 after it's first call which means we receive no entries.
Both functions access the journal using the same sd_journal \* pointer. Can it somehow get corrupted?

**Comment by kaihendry** [comment]
I can confirm this issue on Archlinux 222.

**Comment by zonque** [comment]
I recently debugged this and fixed it with 9e19c04f3. This was past v222 though. @vmatyushin, are you sure you had that commit in your tree when you compiled?

**Comment by vmatyushin** [comment]
Yes, I cloned the repo today and checked that there was "fdopen(fd, "w+");" string.

**Comment by zonque** [comment]
Ok, that seems to be a different bug then. And probably also something different from what @kaihendry reports.

**Comment by vmatyushin** [comment]
I forgot to mention that I am on Arch Linux too, I guess me and @kaihendry probably observe the same issue.

**Comment by zonque** [comment]
Hmm, so on a VM with a freshly installed Arch, with system built from git, `http://localhost:19531/entries` show the full content of the journal. Any hints what I'm missing in order to reproduce this issue?

**Comment by vmatyushin** [comment]
I have just built systemd from git on my home arch system and result is the same - no entries.
Here is the contents of my `/etc/systemd/journald.conf`:

```
[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitInterval=30s
#RateLimitBurst=1000
SystemMaxUse=1000M
#SystemKeepFree=
#SystemMaxFileSize=
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
```

`http://localhost:19531/browse` shows this:

```
Operating system is Arch Linux.
Running on bare metal.
Journal begins at 01/01/1970, 03:00:00 and ends at 01/01/1970, 03:00:00.
Machine ID is 608d895b4332400fb692fed16e6f8603, current boot ID is 8dbcc0e12dbf42b084529e17212c8cd4.
Disk usage is 0 B.
Showing 30 entries.
```

**Comment by zonque** [comment]
And `http://localhost:19531/entries/`?
I triggered a strange behavior earlier today where i needed to check and uncheck the "only this boot" checkbox in `/browse`. I'll check again tomorrow, but that'd be a JS bug then.

**Comment by vmatyushin** [comment]
`http://localhost:19531/entries/` outputs `Not found.`
I launch ./systemd-journal-gatewayd as root.

I've inserted the following code in the beginning of `request_reader_entries()`:

``` C
int entriesNum = 0;
while (true) {
    int res = sd_journal_next(m->journal);
    if (res < 0) {
        printf("Failed to iterate to next journald entry.\n");
        break;
    }
    if (res == 0) {
        // Reached the end.
        break;
    }
    entriesNum++;
}
printf("%d entries\n", entriesNum);
sd_journal_seek_head(m->journal);
```

It outputs `0 entries` every time I reload `http://localhost:19531/entries/`

I tried to debug the issue without any code modifications and saw that `while` loop inside `request_reader_entries()` terminates right after the first iteration, returning `MHD_CONTENT_READER_END_OF_STREAM`.
That's why no entries show up in the browser, I suppose.
Can you reproduce it?

**Comment by zonque** [comment]
The URL is `http://localhost:19531/entries`, without the trailing slash.

But I still can't reproduce it, sorry. Neither when executed from the service file, nor when started directly as root as you describe. To rule out some things, could you move all files in `/var/log/journal/` out of the way recursively, reboot and then test again? And just to avoid that common mistake: are you sure you're really executing the binary you built yourself?

**Comment by vmatyushin** [comment]
I have deleted `/var/log/journal/` contents, rebooted and was able to reproduce the issue.
I'm launching `[systemd source directory]/systemd-journal-gatewayd` as root.

**Comment by poettering** [comment]
This kinda suggests that your journal-gateway binary cannot access any journal files. If you use strace the tool, do you see the journal files successfully opened?

**Comment by vmatyushin** [comment]
Right, strace journalctl shows several `openat(AT_FDCWD, "/run/log/journal...`
But I can't see anything like this when stracing journal-gatewayd.
But why, if I run it as root?

**Comment by zonque** [comment]
Could you post the entire output of `strace ./systemd-journal-gatewayd` somewhere, including an attempt to read the entries via `http://localhost:19531/entries`?

**Comment by vmatyushin** [comment]
I was wrong. It does open the journal (I missed `-f` parameter for strace).
Here I open `http://localhost:19531/entries` and `http://localhost:19531/browse`.
http://pastebin.ca/3072081

**Comment by vmatyushin** [comment]
Also I've installed fresh Arch in VirtualBox, compiled systemd from git and I can reproduce the issue. I receive no entries when visiting `/entries` and `/browse` shows no entries too. Am I doing something fundamentally wrong? %)

**Comment by poettering** [comment]
Each time when the journal file is opened it is closed again right away. Do you see any interesting output if you set SYSTEMD_LOG_LEVEL=debug for the process?

If you run "journalctl -D /var/log/journal", does that work correctly?

**Comment by vmatyushin** [comment]
With `LogLevel=debug` I see lots of systemd messages but nothing erratic.
`journalctl -D /var/log/journal` works ok.
But the same command with `./journalctl` compiled from git does not work:
`Error was encountered while opening journal files: Protocol not supported`

**Comment by poettering** [comment]
@vmatyushin does gatewayd work if you run it from the command line in a shell instead of as a systemd service?

The "Protocol not supported" error probably happens because your journal files were generated with compression, and your new build had compression support turned off (probably missing dep on the compression lib you used).

**Comment by vmatyushin** [comment]
Alright, I got it working.
I compiled systemd with lz4 and audit support.
Some of that was missing, that's why it silently produced zero entries.
I wish there was some verbose message about missing support in runtime.
I think this issue can be closed now.

**Comment by zonque** [comment]
Ha, nice. I guess #695 should improve the logging situation.

**Comment by manimuthu-m-a** [comment]
@vmatyushin: Even I am facing a similar issue, I have some hard time in understanding the relationship between enabling lz4 and audit and sd_journal_next. It would be really helpful if you could give some insight into the issue. 

#My problem:
 I wanted to listen to remote journal logs ( logs which we receive from another machine, using systemd-journal-remote) and take some action accordingly. For that i wrote a small application which opens remote journal directory (sd_journal_open_directory(j,"/var/log/journal/remote/",0) and parse through all the logs using sd_journal_next() and whenever sd_journal_next  returns 0 (no new logs), i wait on sd_journal_wait(). 

I ran this process as root, sd_journal_wait() wakes up whenever journal remote receives new logs but sd_journal_next always returns 0. But journalctl works, it could able to read.

If I stop systemd-journal-remote and restart my application, My application works properly, it reads all the logs properly.
