### ISSUE TITLE
machined: provide more details to polkit auth

### ISSUE THREAD

**Issue by lnussel** [systemd/systemd#6279]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

git master

### description

src/machine/machine-dbus.c doesn't pass any details to
bus_verify_polkit_async(). So custom polkit rules can't e.g. allow
only certain users to operate on certain machines using
org.freedesktop.machine1.shell.

I'd like to suggest to always pass the unit ie machine name for all
actions where it is applicable, like it's done for
org.freedesktop.systemd1.manage-units.

**Comment by poettering** [comment]
A patch adding the props you need would be very welcome!

**Comment by poettering** [comment]
Implemented by 09364a8043a2f9b698e49a172094d658ae289ac6. Closing.
