### ISSUE TITLE
bootctl: GPT type UID

### ISSUE THREAD

**Issue by maggu2810** [systemd/systemd#628]
If I understand "The Boot Loader Specification" (https://wiki.freedesktop.org/www/Specifications/BootLoaderSpec/) correctly the following GPT type GUID are valid for $BOOT:
- bc13c2ff-59e6-4262-a352-b275fd6f7172 (Extended Boot Partition)
- c12a7328-f81f-11d2-ba4b-00a0c93ec93b (EFI System Partition)

The bootctl tool accept "EFI System Partition" only:
https://github.com/systemd/systemd/blob/ab822b624bc48410c8d7bd3be1c88c399a44adae/src/boot/bootctl.c#L142

Shouldn't we support both types?

**Comment by karelzak** [comment]
It's all about ESP -- the partition required by UEFI standard for EFI compatible firmwares. 

The extended boot partition is just a hack recommended by freedesktop.org  for additional system specific data (for example another kernels, etc.) if the installer/boot loader is so stupid it cannot use normal shared EPS or so...  UEFI standard and firmwares have no clue about it.

**Comment by poettering** [comment]
Yeah, the bootctl tool is about the ESP only. It installs the boot loader into the ESP, and nothing else. Placing it anywhere else defeats is purpose.

**Comment by maggu2810** [comment]
No problem at all.

I read the man page of bootctl and so the referenced boot loader spec.
The boot loader spec states "The installer program should pick $BOOT according to the following rules:".
The rules contains EBP in front of ESP, so I thought, if this is preferred, let's change my type UID of boot... After that bootctl was not working anymore, so I changed the type back to ESP and checked the sources.

All fine, but the referenced spec and the rule that contains EBP in ESP confused me a little bit.
Should the spec prefer ESP before EBP?

**Comment by poettering** [comment]
We should probably drop he EBP stuff entirely from that spec, since we have zero intention to ever implement that in sd-boot and friends anyway...

**Comment by sielicki** [comment]
The Boot Loader Specification still references EBP and does not make clear that this is an unsupported setup, 

>  since we have zero intention to ever implement that in sd-boot and friends anyway...

@poettering has this changed this since 2015?

Thanks,
Nicholas

**Comment by poettering** [comment]
@sielicki yeah, I think we should teach sd-boot to read kernels from the other partition and hence also support the gpt-auto logic and everything else to do the right thing with it.
