### ISSUE TITLE
Cannot run a network interface without source validation

### ISSUE THREAD

**Issue by pqarmitage** [systemd/systemd#6282]
### Submission type
- Bug report

### systemd version the issue has been seen with
219, 232, 233

### Used distribution
Fedora, ArchLinux, Centos 7

### In case of bug report: Expected behaviour you didn't see
Able to run a network interface with rp_filter providing no source validation 

### In case of bug report: Unexpected behaviour you saw
Cannot make a network interface run with rp_filter providing no source validation

### In case of bug report: Steps to reproduce the problem
Read the documentation of rp_filter:
`The max value from conf/{all,interface}/rp_filter is used	when doing source validation on the {interface}.`
so if /proc/sys/net/ipv4/conf/all/rp_filter = 1, the minimum value of source validation on any interface is 1.

The problem is caused by the following entry in sysctl.d/50-default.conf:
`net.ipv4.conf.all.rp_filter = 1`
introduced in commit 1836bf9e1d70, with the comment:
```
sysctl: always write net.ipv4.conf.all.xyz= in addition to net.ipv4.conf.default.xyz=

Otherwise we have a boot-time race, where interfaces that popped up
after the sysctl service would get the settings applied, but all others
wouldn't.
```

If the purpose of the patch is to close a boot-time race condition, then it shouldn't affect the operation of the system subsequently. If, on the other hand, the purpose of the patch is to ensure some sort of source route validation on all interfaces, then the patch is reasonable, but it doesn't meet the stated purpose of the patch.

If I want to run an interface with no source validation, the only way I can do it is to set net.ipv4.conf.all.rp_filter=0, but then that undoes the effect of the commit. It transpires that if I want to be able to receive an IPv4 packet on an interface with no IPv4 address configured on it then rp_filter has to be 0.

What I think should be done to avoid the race condition is set net.ipv4.conf.default.rp_filter = 1, and then iterate through all the existing interfaces setting net.ipv4.conf.{interface}.rp_filter = 1 where it is currently 0, and net.ipv4.conf.all.rp_filter should not be set. If this were done, then all interfaces by default would still have rp_filter = 1, thereby leaving all interfaces working as they do now, but it would allow interfaces to be set to operate without source validation when required.

The same should apply to
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.promote_secondaries = 1
where the .all. option should not be set, but the value should be set in the individual interfaces.

**Comment by johannbg** [comment]
Given that I came across this when parsing keepalived upstream change log and it's seems to have stagnated @poettering  @yuwata @ssahani based the ouput of sysctl -ar 'rp_filter' and if I'm understanding @pqarmitage correctly that a better default is to enables this per interfaces ( as opposed to all ) by default so this can be disabled per interface via knob in type network files in networkd, Is there any reason it should or should not be done that way?
