### ISSUE TITLE
Setting NOCOW attribute fails systemd-tmpfiles

### ISSUE THREAD

**Issue by wuxb45** [systemd/systemd#629]
The service should not fail. The failure should be ignored because it's not a problem at all on most of the file systems.
Please refer this commit (and the comment).
https://github.com/systemd/systemd/commit/3a92e4ba470611ceec6693640b05eb248d62e32d

**Comment by floppym** [comment]
See also #560.

**Comment by poettering** [comment]
Closing, as this is already tracked in #560.
