### ISSUE TITLE
systemd-nspawn@.service can leave a container image partially converted to private user namespace

### ISSUE THREAD

**Issue by marienz** [systemd/systemd#6292]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian Stretch

### Expected behaviour I didn't see

When starting a container using `systemctl start systemd-nspawn@machinename`, it should either start the container or leave the filesystem unmodified.

### Unexpected behaviour I saw

Starting the container timed out, leaving some files with private and others with public (host) UIDs/GIDs because the `--private-users-chown` conversion was interrupted.

### Steps to reproduce the problem

- Create a container image containing many files in `/var/lib/machines`, which is backed by storage that is not very fast.
- Start this container using `systemctl start systemd-nspawn@machinename`.

Because `systemd-nspawn@.service` passes `-U` to systemd-nspawn (looks like current Git still does this, not just the Debian systemd I encountered this problem on), and the container's root directory is owned by the host's root user, systemd-nspawn picks a new UID/GID range and starts recursively chowning the container image.

Because `systemd-nspawn@.service` leaves timeouts alone, the default service start timeout (90 seconds?) is applied. This timeout is normally more than sufficient, but not when systemd-nspawn needs to chown the entire container image before it can really start. So systemd kills systemd-nspawn, leaving the image partially converted.

I do not see an easy way to recover once you've gotten yourself into this state. If I just start the container again, systemd-nspawn checks the container's root directory, which has already been converted. So it doesn't convert again, and unconverted UIDs/GIDs get mapped to nobody (65534) in the container (confirmed by entering the container manually using `systemd-nspawn --network-veth -U --machine=machinename /bin/bash` and running `ls` inside it). And I'm not aware of any systemd-provided tool that completes the conversion. Scripting that doesn't look like it'll be too difficult (although I'll have to learn how to find and fix any file ACLs), but it'd be nice if I didn't have to :).

This can bite users unexpectedly when upgrading systemd from a version that did not pass `-U` in `systemd-nspawn@.service` to one that does (that's not quite how I hit this, but close).

Suggested alternatives:

- Drop `systemd-nspawn@.service` from `-U` to just `--private-users`. When run on a container image already set up for private users from a kernel that does not support user namespaces, this will fail: that's OK, since trying to start anyway without namespacing will probably not work anyway. Require that users explicitly convert the image in advance to take advantage of `--private-users`, for example by running `systemd-nspawn -U --machine=machinename /bin/true` once by hand (probably not exactly the right command but you get the idea). This is my preferred alternative: I think triggering `--private-users-chown` at service startup is too surprising/different from normal startup.

- Significantly increase the start timeout. I don't like this option, since whenever systemd-nspawn does not need to convert the filesystem the timeout is fine.

- Somehow resume the conversion the next time the container is started. One approach might be to convert the root directory last, and have the conversion code assume that it can just replace the upper 16 bits of the UID/GID (even if they're not consistent across the image it operates on). But because the conversion process picks the upper 16 bits randomly, this doesn't so much resume the conversion as restart it. If it somehow knew to reuse the same upper 16 bits as the previous attempt, and skips files that already have the right UID/GID, this might work.

Please let me know if you need more information. And with that, I'll go back to kicking myself for not snapshotting the container before triggering the conversion, while writing a script to recover...

**Comment by marienz** [comment]
I missed a fairly obvious way to get systemd to fix up the container image: chown the root directory back to the host's root user, then run systemd-nspawn again. That would trigger the conversion again, and (having now looked at nspawn-patch-uid.c) the conversion doesn't care that the container identifier part of the UIDs/GIDs is not consistent, it just overwrites them (which is what I want in this case).

**Comment by Mic92** [comment]
I wish we would already have [shiftfs](https://lwn.net/Articles/713640/) to not having to alter the filesystem at all.

**Comment by poettering** [comment]
Fix waiting in #7365
