### ISSUE TITLE
GPG Signature Security

### ISSUE THREAD

**Issue by NicoHood** [systemd/systemd#6295]
GPG signed Systemd releases can be found here:
https://github.com/systemd/systemd/releases

There are currently two problems with the way those releases are signed:

a) Minor: The tarball was automatically generated by Github and could change in the future. It was reported to me that this already happened. Thatswhy we should not rely on github generated tarballs.

b) Major: Signing the Github Tarball without additional verification does not provide any better security. The main developer has to sign his git archive locally in order to provide best possible security. Signing a Github release is like downloading it as packager and signing it yourself. If Github gets hacked you have no additional security. And that is what we aim for.

In order to solve this, the tarball should be generated locally. Information on how to do this and also an automated script can be found here:
https://github.com/NicoHood/gpgit

Using .tar.xz archives also helps to reduce download time for countries with instable and slow internet connection. 

Furthermore from the web UI it seems no git commits are GPG signed. In order to provide better security for git builds at least the head commit should always be signed.
https://github.com/systemd/systemd/commits/master

Thanks for paying attention.

**Comment by poettering** [comment]
We generally sign our git tags. We highly recommend using those for building downstream systems, instead of indirecting things through tarballs.

**Comment by NicoHood** [comment]
That in general is a valid point and its good that you sign tags too.

However if you do publish signed tarballs, it should be done secure. The current way gives no extra security with the mentioned arguments. It rather gives the user a wrong impression about security.

About git tags itself:
Those can be also faked with git metadata manipulation. A good presentation about this can be found here (just FYI):
https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/torres-arias

This was also discussed here:
https://www.spinics.net/lists/arch-general/msg43833.html

So please be aware that git might not give best security and a comparison with a truly signed tarball would make sense for such an essential system component.

**Comment by poettering** [comment]
github publishes tarballs, we don't. tars aren't really reproducible unless you stick to one specific implementation in one version, and everyone knows that. Hence I am not convinced we should really revert back to tarballs, since they are worse than signed git tags really, not better.

If git is currently vulnerable to not correctly verifying tags, then that appears to be something to fix in git, not work-around on our side by reverting back to tarballs for everything.

**Comment by NicoHood** [comment]
I dont see any problem in creating a tarball. On different systems the tarfile might not be bit identical, but the extracted content is. And the content is what matters, so tarballs should be signed.

Git created tarballs, not you. But you create signatures on top of the git tarballs. And this does only give a limited security addition. So the only thing I request is to generate a locally signed tarball. This is really simple and can be done with [gpgit](https://github.com/NicoHood/gpgit) if you wish.

Relying on (partly vulnerable) signed git tags but saying the problem needs to be fixed on the git side is not correct to me. You cannot fix git, correct. But you can provide both a tarball and a git signature and then one can compare those two contents. And this would increase security.

**Comment by poettering** [comment]
I just realized that this is a duplicate of #2926, closing as duplicate hence.

**Comment by poettering** [comment]
> You cannot fix git

Hmm? Why can't git be fixed? Not following?
