### ISSUE TITLE
Do not make any syscalls 279 when the kernel command line has audit=0

### ISSUE THREAD

**Issue by debiangamer** [systemd/systemd#6298]
### Submission type
 - Bug report

### systemd version the issue has been seen with

systemd --version
systemd 233
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid

### Used distribution

Debian testing Xfce arm64

### In case of bug report: Expected behaviour you didn't see

No systemd syscall 279 traces in the terminal or in dmesg.

### In case of bug report: Unexpected behaviour you saw

When booting to the terminal mode, the terminal  is filled with systemd syscall 279 traces that disturbs login to the system and Armbian user setup procedure. When booting to the desktop, you have in dmesg:

[ 2722.600266] systemd[1]: syscall 279
[ 2722.600424] Code: aa0503e4 aa0603e5 aa0703e6 d4000001 (b13ffc1f) 
[ 2722.604841] CPU: 4 PID: 1 Comm: systemd Not tainted 3.14.29+ #49
[ 2722.610973] task: ffffffc0001a0000 ti: ffffffc0653fc000 task.ti: ffffffc0653fc000
[ 2722.618473] PC is at 0x7f93eb4754
[ 2722.621954] LR is at 0x7f941dcaec
[ 2722.625349] pc : [<0000007f93eb4754>] lr : [<0000007f941dcaec>] pstate: 20000000
[ 2722.632828] sp : 0000007fcc957910
[ 2722.636297] x29: 0000007fcc957910 x28: 00000055876ce000 
[ 2722.641581] x27: 00000055960df990 x26: 00000055876d0000 
[ 2722.647042] x25: 0000000000000001 x24: 00000055876ce000 
[ 2722.652427] x23: 0000007fcc957e68 x22: 00000055876d0000 
[ 2722.657890] x21: 0000005587668b38 x20: 0000007fcc9579b0 
[ 2722.663294] x19: 0000005587687450 x18: 0000000000000000 
[ 2722.668729] x17: 0000007f93eb4730 x16: 0000007f9430dca8 
[ 2722.674164] x15: 3a216e7e07020f19 x14: ff00000000000000 
[ 2722.679602] x13: 0000000000000000 x12: 0000000000000003 
[ 2722.685031] x11: 000000000000000e x10: 0101010101010101 
[ 2722.690466] x9 : 7f7f7f7f7f7f7f7f x8 : 0000000000000117 
[ 2722.695963] x7 : 0000005596154760 x6 : 0000005596154760 
[ 2722.701336] x5 : 0000005596193a10 x4 : 00000055960e1130 
[ 2722.706766] x3 : 0000007fcc9578c0 x2 : d7d35154d4d04000 
[ 2722.712199] x1 : 0000000000000001 x0 : 0000005587687450 

[ 2723.420270] systemd[1]: syscall 279
[ 2723.420306] Code: aa0503e4 aa0603e5 aa0703e6 d4000001 (b13ffc1f) 
[ 2723.424570] CPU: 0 PID: 1 Comm: systemd Not tainted 3.14.29+ #49
[ 2723.430662] task: ffffffc0001a0000 ti: ffffffc0653fc000 task.ti: ffffffc0653fc000
[ 2723.438306] PC is at 0x7f93eb4754
[ 2723.441700] LR is at 0x7f941dcaec
[ 2723.445159] pc : [<0000007f93eb4754>] lr : [<0000007f941dcaec>] pstate: 20000000
[ 2723.452711] sp : 0000007fcc957910
[ 2723.456104] x29: 0000007fcc957910 x28: 00000055876ce000 
[ 2723.461519] x27: 00000055960df990 x26: 00000055876d0000 
[ 2723.466966] x25: 0000000000000001 x24: 00000055876ce000 
[ 2723.472387] x23: 0000007fcc957e68 x22: 00000055876d0000 
[ 2723.477821] x21: 0000005587668b38 x20: 0000007fcc9579b0 
[ 2723.483254] x19: 0000005587687450 x18: 0000000000000000 
[ 2723.488688] x17: 0000007f93eb4730 x16: 0000007f9430dca8 
[ 2723.494122] x15: 3a216e7e07020f19 x14: ff00000000000000 
[ 2723.499556] x13: 0000000000000000 x12: 0000000000000003 
[ 2723.505000] x11: 000000000000000e x10: 0101010101010101 
[ 2723.510423] x9 : 7f7f7f7f7f7f7f7f x8 : 0000000000000117 
[ 2723.515868] x7 : 0000005596193a10 x6 : 0000005596193a10 
[ 2723.521291] x5 : 0000005596262850 x4 : 00000055960e1130 
[ 2723.526724] x3 : 0000007fcc9578c0 x2 : d7d35154d4d04000 
[ 2723.532158] x1 : 0000000000000001 x0 : 0000005587687450 

[ 2738.575627] systemd[1]: syscall 279
[ 2738.575701] Code: aa0503e4 aa0603e5 aa0703e6 d4000001 (b13ffc1f) 
[ 2738.580018] CPU: 6 PID: 1 Comm: systemd Not tainted 3.14.29+ #49
[ 2738.586123] task: ffffffc0001a0000 ti: ffffffc0653fc000 task.ti: ffffffc0653fc000
[ 2738.593684] PC is at 0x7f93eb4754
[ 2738.597130] LR is at 0x7f941dcaec
[ 2738.600584] pc : [<0000007f93eb4754>] lr : [<0000007f941dcaec>] pstate: 20000000
[ 2738.608085] sp : 0000007fcc957910
[ 2738.611535] x29: 0000007fcc957910 x28: 00000055876ce000 
[ 2738.616894] x27: 00000055960df990 x26: 00000055876d0000 
[ 2738.622329] x25: 0000000000000001 x24: 00000055876ce000 
[ 2738.627828] x23: 0000007fcc957e68 x22: 00000055876d0000 
[ 2738.633196] x21: 0000005587668b38 x20: 0000007fcc9579b0 
[ 2738.638629] x19: 0000005587687450 x18: 0000000000000000 
[ 2738.644057] x17: 0000007f93eb4730 x16: 0000007f9430dca8 
[ 2738.649491] x15: 3a216e7e07020f19 x14: ff00000000000000 
[ 2738.654924] x13: 0000000000000000 x12: 0000000000000003 
[ 2738.660358] x11: 000000000000000e x10: 0101010101010101 
[ 2738.665814] x9 : 7f7f7f7f7f7f7f7f x8 : 0000000000000117 
[ 2738.671225] x7 : 0000005596262850 x6 : 0000005596262850 
[ 2738.676659] x5 : 0000005596138790 x4 : 00000055960e1130 
[ 2738.682092] x3 : 0000007fcc9578c0 x2 : d7d35154d4d04000 
[ 2738.687527] x1 : 0000000000000001 x0 : 0000005587687450 

### In case of bug report: Steps to reproduce the problem

Run systemd with the 3.14.29 kernel that is the only usable kernel with the Amlogic S912 tv box. Meson mainline  kernel (http://linux-meson.com/doku.php)  does not support usb nor audio yet and has problems with the display resolution.
[    0.000000] Linux version 3.14.29+ (root@carrizo) (gcc version 4.9.4 (Linaro 
GCC 4.9-2017.01) ) #49 SMP Wed Jul 5 07:53:42 EEST 2017
[    0.000000] Kernel command line: root=LABEL=ROOTFS rootflags=data=writeback r
w console=ttyS0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.rep
air=yes net.ifnames=0 mac=C4:2F:AC:99:32:19 audit=0

**Comment by benjarobin** [comment]
It looks like that the syscall 279  `#define __NR_memfd_create 279`  was introduce in kernel 3.17

**Comment by keszybz** [comment]
One option would be to add a wrapper in memfd_new that'd call memfd_create just once. But that wouldn't solve your issue entirely, because it's probably not only pid1 but other executables which use memfds. So you really want to compile without support for memfd. Your best option is to tweak the wrapper in
`src/basic/missing_syscall.h` to always return -ENOSYS. I don't think this is something to do upstream — I don't even think debian will want to do it. Please just patch locally.

**Comment by debiangamer** [comment]
On Thu, 6 Jul 2017 13:30:00 +0000
Benjamin Robin <notifications@github.com> wrote:

> It looks like that the syscall 279  `#define __NR_memfd_create 279`
> was introduce in kernel 3.17
> 

So, there is no other kernel that has Amlogic drivers. Armbian 3.14.29
kernel is from Android probaly and Armbian has ported to Linux easily.

**Comment by keszybz** [comment]
Actually, I don't think you need to patch. If you compile with `-D__NR_memfd_create=0` in CFLAGS that should do the trick (untested).

**Comment by debiangamer** [comment]
I do not want compile systemd or patch is. I have read that systemd developers do not care users and your response proves it. You check  audit kernel parameter already, without it systemd calls syscall 279  every second. Just make it work fully, but no.

**Comment by keszybz** [comment]
Even if we added a compilation option to disable memfd_create, you'd need to compile with that option. Whether memfd_create will be available can only be detected at run time, because it depends on the kernel version, and the default must always be to use it, because that's the proper choice for the big majority of users. So either way you're going to have your own systemd. In my previous comment I suggested a way to do this without patching anything, just through configuration switches.

You are using a very new systemd with a very old kernel. You have a very specific itch, and it's on you to scratch it.

**Comment by debiangamer** [comment]
I  plan to use sysvinit. systemd is the same shit that almost everything from redhat: pulseaudio, networkmanager, gnome3.

**Comment by debiangamer** [comment]
" If you compile with -D__NR_memfd_create=0 in CFLAGS that should do the trick (untested)."

Redhat does not know how to use the if statement instead of compiler flags. This is user selectable runtime feature.

"proper choice for the big majority of users."

There are millions of Android tv boxes and single board computers and many people like to run desktop Linux instead of Android. See armbian.com.

I managed to run Debian testing Xfce without systemd running. Highlights:
apt-get install sysvinit-core sysvinit-utils
cp /usr/share/sysvinit/inittab /etc/inittab
Add to the kernel command line: init=/lib/sysvinit/init console=hvc0 console=ttyS0

sed -i "s/HEED_DEFAULT_DISPLAY_MANAGER=true\?/HEED_DEFAULT_DISPLAY_MANAGER=false/" /etc/init.d/lightdm
			update-rc.d lightdm remove
			update-rc.d lightdm defaults
			update-rc.d lightdm enable
			reboot

**Comment by floppym** [comment]
It seems like `audit=0` should be disabling the audit sub-system, which should prevent those messages regardless of what systemd is doing.

This seems like a kernel bug?

**Comment by debiangamer** [comment]
It is not a kernel bug, because with audit=0 systemd stops calling syscall269 after boot. Many services take long time to complete (like expanding the filesystem in the sd card) and systemd calls syscall 279 in the middle of boot processes and can even make them and whole os to crash. Armbian user configuration script works in the terminal after root login and terminal is filled with syscall 279 traces. When the os is up and running then systemd stops calling. Without audit=0 systemd calls syscall 279 every second.

All is good now, Debian testing Xfce works fine with sysv init. Only that systemd-logind is crying when login to the system. Typical redhat shitty software works likes this:

[   35.371434] systemd-logind[3921]: Failed to start user service, ignoring: Unknown unit: user@1000.service

[  158.583296] systemd-logind[3921]: Failed to start user service, ignoring: Unknown unit: user@0.service
[  158.616556] systemd-logind[3921]: New session c2 of user root.

Redhat does not know how to use the if statement. It would be easy to check if systemd is running and stop spamming to the logs.  It would be easy to stop calling syscall 279 when audit=0 at boot too. But no programming skills are in redhat.

**Comment by floppym** [comment]
Yes, systemd calls syscall 279, but that does not explain the kernel log spam. My system does not log every time a program issues an invalid system call.

**Comment by debiangamer** [comment]
I wrote that audito=0 works after booting  to the desktop, but not at boot time.
You can make kernel silent by disabling kernel debug and printk in the kernel configuration. However tv boxes use SOC and embedded must be selected and that selects kernel debug.

Symbol: EMBEDDED [=y]
-> General setup
Defined at init/Kconfig:1464
Selects: EXPERT [=y]

Symbol: EXPERT [=y]
Defined at init/Kconfig:1276
Selects: DEBUG_KERNEL [=y]
Selected by: EMBEDDED [=y]

PRINTK is a forced setting, you can not disable it in this kernel.

**Comment by poettering** [comment]
hmm, are you saying the linux kernel logs about all syscalls userspace issues, that aren't available? That appears like a strange kernel choice to me, as it makes compat hard for userspace, if trying the new syscall and falling back has major side-effects.

I just compiled this on x86-64:

```c
#include <sys/syscall.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
        syscall(370);
}
```

370 is a syscall currently not defined. strace shows this syscall returns ENOSYS as it should, and the kernel doesn't log about this, which is different from what you report.

Any chance you can ping your kernel maintainers about that, and ask them why their kernel logs about missing syscalls? It really should just return ENOSYS for those, like the x86-64 kernel does, and not log about them loudly.

Note that 3.13 is the current minimum kernel version we support, so your kernel is in theory among the ones we do focus on.

**Comment by falsovsky** [comment]
I started having this same problem today, on a Orange Pi PC 2 with ArchLinux.
This probably breaks support for a lot of SoC boards that only have older kernels.

Linux OrangePiPC2 3.10.65 #55 SMP PREEMPT Fri Nov 18 16:17:28 CST 2016 aarch64 GNU/Linux

**Comment by noblehng** [comment]
First of all, sorry for posing to a closed issue, I just came across a similar issue yesterday at other situation.

For information, the fault is at the arm64 kernel, which leave over this debug message, and it has already been fixed<sup>[[1]](https://www.spinics.net/lists/arm-kernel/msg630320.html)[[2]](https://github.com/torvalds/linux/commit/532826f3712b607256eb30f92f23d1c604d3fa34)[[3]](https://github.com/torvalds/linux/commit/1962682d2b2fbe6cfa995a85c53c069fadda473e)[[4]](https://github.com/torvalds/linux/commit/5ee39a71fd89ab7240c5339d04161c44a8e03269)</sup> in the 4.17 mainline kernel. So maintainers of various vendor based kernels could backport this fix. For the 3.14 amlogic kernel, this<sup>[[5]](https://github.com/CoreELEC/linux-amlogic)</sup> seems to be the most actively maintained. Anyway, call and check for ENOSYS is a more reliable and clean method for runtime checking unimplemented syscall than comparing kernel version.

# References
\[1\]: https://www.spinics.net/lists/arm-kernel/msg630320.html
\[2\]: https://github.com/torvalds/linux/commit/532826f3712b607256eb30f92f23d1c604d3fa34
\[3\]: https://github.com/torvalds/linux/commit/1962682d2b2fbe6cfa995a85c53c069fadda473e
\[4\]: https://github.com/torvalds/linux/commit/5ee39a71fd89ab7240c5339d04161c44a8e03269
\[5\]: https://github.com/CoreELEC/linux-amlogic
