### ISSUE TITLE
RFE: sd-boot relies on firmware text console support, unlike grub which draws its text manually

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#6301]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233

### Used distribution

> Gentoo Linux

### In case of bug report: Expected behaviour you didn't see

> boot menu using full screen resolution, just like grub does.

### In case of bug report: Unexpected behaviour you saw

> The boot menu covers only a part of the screen, looks like it boots with a lower resolution than what it should boot with. http://i.imgur.com/yReSrd7.jpg

### In case of bug report: Steps to reproduce the problem

> install systemd-boot as the bootloader

If it is not a bug, is there a way to configure this, or is this missing functionality?

**Comment by poettering** [comment]
grub apparently paints everything itself, includes fonts and whatnot for that. sd-boot is much much simpler, and relies on the firmware's font/text console support, which apparently is a bit flakey...

Adding graphics support to sd-boot kinda contradicts its minimal, beautiful design... After all its explicitly not supposed to be a graphics server, but just a minimal text thingy.

**Comment by bl33pbl0p** [comment]
Yes, I agree, also, I figured out this was a firmware issue, because after upgrading my on board firmware to the latest, the screen uses the complete resolution. Hence, closing.
