### ISSUE TITLE
systemd --user service manager loops after a systemctl --user daemon-reexec, if the user dbus-daemon is not running

### ISSUE THREAD

**Issue by Kalsofar** [systemd/systemd#6303]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v234, v233, v232

### Used distribution

Fedora 26, Debian Sid, Debian Stretch

### In case of bug report: Expected behaviour you didn't see

The systemd --user manager re-executing without issues.

### In case of bug report: Unexpected behaviour you saw

systemctl --user daemon-reexec takes longer than usual:

```
[testuser@fedora-test ~]$ time systemctl --user daemon-reexec
real    0m25.048s
user    0m0.002s
sys 0m0.006s

```

Error messages appear in the journal:

```
Jul 06 21:09:05 fedora-test systemd[26]: Reexecuting.
Jul 06 21:09:30 fedora-test systemd[26]: Failed to subscribe to activation signal: Connection timed out
Jul 06 21:09:30 fedora-test systemd[26]: Failed to register name: Connection timed out
Jul 06 21:09:30 fedora-test systemd[26]: Failed to set up API bus: Connection timed out
Jul 06 21:09:31 fedora-test systemd[26]: Looping too fast. Throttling execution a little                

```

### In case of bug report: Steps to reproduce the problem

1. Make sure dbus for user sessions is installed (e.g. dbus-user-session on Debian)
2. Login and stop dbus if it's active (but keep it socket activatable):

```
[testuser@fedora-test ~]$ systemctl --user stop dbus
Warning: Stopping dbus.service, but it can still be activated by:
  dbus.socket
```

3. Re-execute the systemd --user system manager:

```
[testuser@fedora-test ~]$ systemctl --user daemon-reexec 
```

Notes:

- The user dbus.service and dbus.socket (e.g. from dbus-user-session on Debian) needs to be installed, otherwise this problem does not occur.

- The user dbus-daemon should not be running yet. If it's already running then this problem does not occur.

- Stack trace I grabbed while it was spinning:

```
(gdb) bt                                                                                                                                      
#0  0x00007ff3e5864577 in getpid () from /lib64/libc.so.6
#1  0x00007ff3e6bd56e7 in event_pid_changed (e=0x55c0931aa500) at ../systemd/src/libsystemd/sd-event/sd-event.c:496
#2  0x00007ff3e6bd9a0a in sd_event_source_set_enabled (s=0x55c0931c48e0, m=0) at ../systemd/src/libsystemd/sd-event/sd-event.c:1601
#3  0x00007ff3e6bc01a7 in prepare_callback (s=0x55c0931c4e10, userdata=0x55c0931c1490) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3201
#4  0x00007ff3e6bdc3a8 in event_prepare (e=0x55c0931aa500) at ../systemd/src/libsystemd/sd-event/sd-event.c:2355
#5  0x00007ff3e6bdc9d2 in sd_event_prepare (e=0x55c0931aa500) at ../systemd/src/libsystemd/sd-event/sd-event.c:2466
#6  0x00007ff3e6bdd6e0 in sd_event_run (e=0x55c0931aa500, timeout=18446744073709551615) at ../systemd/src/libsystemd/sd-event/sd-event.c:2680
#7  0x000055c091de6c5c in manager_loop (m=0x55c0931aa000) at ../systemd/src/core/manager.c:2287
#8  0x000055c091ddd0a1 in main (argc=4, argv=0x7ffe258e0398) at ../systemd/src/core/main.c:1936
```

**Comment by msekletar** [comment]
Same issue affects PID 1 as well. Also note that after systemd gets into tight loop then tools that strictly require DBus  no longer works, e.g. systemd-run.

I think the problem is that systemd tries to connect to the bus after re-execution, but that attempt fails, as systemd can't start dbus.service while it is trying to connect to it (code for connecting to dbus is synchronous).

I'd say that we should make systemd more robust, so that failed connection attempt doesn't get systemd into tight loop. Another possible solution (possibly simpler) is to skip connection altogether. There is little point in trying to connect to bus when dbus.service is not running. As soon as *some other service* activates dbus.service we will connect to it.

**Comment by msekletar** [comment]
@Kalsofar please have a look at #6773. Btw, I tested the scenario when systemd is running as PID1, but I'd very much appreciate if you could test ```--user``` case

**Comment by Kalsofar** [comment]
Works as expected; tested from master (95441cf2ed2406c00e3e94f1991992e63c2507c9):

```
[testuser@fedora-26-test ~]$ systemctl --user stop dbus    
Warning: Stopping dbus.service, but it can still be activated by:
  dbus.socket
[testuser@fedora-26-test ~]$ systemctl --user daemon-reexec
[testuser@fedora-26-test ~]$ systemctl --user status       
● fedora-26-test
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Fri 2017-09-08 21:24:03 PDT; 3min 26s ago
   CGroup: /user.slice/user-1001.slice/user@1001.service
           └─init.scope
             ├─31 /usr/lib/systemd/systemd --user --deserialize 16
             └─32 (sd-pam)
```

Thank you!
