### ISSUE TITLE
RFE: Add template specifier for path to unit file

### ISSUE THREAD

**Issue by matthijskooijman** [systemd/systemd#6308]
### Submission type
 - Request for enhancement (RFE)

I would like to see one or two extra specifiers to be used in unit files that would expand to:
 - The full path to the current unit file.
 - The full path to the directory the current unit file is in.

This would help to support bits of software that are not installed into a fixed place, without having to hardcode paths into the unit file.

E.g. consider a git clone of a bit of software. I cloned this into `/home/matthijs/foo`, but this could be any other path. To start a daemon from that directory, I'm including a service file into the git repo, that looks like this:

	[Service]
	ExecStart=/home/matthijs/foo/foo-daemon
	User=matthijs

	(more stuff omitted)

After making the git clone, I can set this up using:

	sudo systemctl enable /home/matthijs/foo/foo.service

This makes the needed links in `/etc/systemd` to make this service run.

However, the service file hardcodes the path to the git checkout, which makes it not so suitable for inclusion in the git repository itself.

If, for example, `%d` would refer to the unit file's directory, I would be able to use:

	ExecStart=%d/foo-daemon

and this service file would work regardless of where the git checkout
was made.

**Comment by keszybz** [comment]
Hmm. You could easily have a script in the git repo which would generate the unit file with the right path and call `systemctl enable` for you. I don't see anything *wrong* with your idea, but OTOH, it's such a fringe case that I'm not sure it deserves support in systemd itself.

**Comment by tschoening** [comment]
I have exactly the [same use case](https://superuser.com/questions/1282243/how-to-avoid-an-absolute-path-to-an-executable-in-systemd) and would like to vote for the proposed enhancement as well. A lot of people deploy software using their SCMs, including things like systemd configs. Enhancements for those use case have been [implemented in the past](https://bugzilla.redhat.com/show_bug.cgi?id=955379) already as well.

While of course each and every project could implement custom scripts, this seems like redundant and error prone work to me. systemd already provides the concept of specifiers into which the newly suggested ones would perfectly fit. I have lots of different projects and customers per system, so would most likely implement some different approach, like a system wide dispatcher forwarding `ExecStart` and Co., to ease maintenance of systemd-handling in my environment. Therefore I would need to collect the needed data differently than other scripts, data which ist most likely already available to systemd itself.

So, in my opinion, this is not a fringe case anymore, but instead becomes more and more common and additional format specifiers would make systemd support such use cases better out of the box. And from my understanding, things better/easier working OOB was often used as argument for other discussions as well.

**Comment by fgervais** [comment]
Yes same use-case here

**Comment by keszybz** [comment]
And how would those specifiers expand in drop-ins?

**Comment by ams-tschoening** [comment]
AFAIK there are two forms of drop-ins, one overriding a file completely and the other overriding individual settings. So it depends on how the specifier is defined in the end and which override is used: If a file is overridden completely and the specifier implements the easiest case of resolving to the unit file where it is defined in, do the same with overrides and assume users know what they are doing.

In case of overriding individual settings, I would expect that if the setting containing the specifier is NOT overridden, it resolves to the file in which it is actually specified. If it is overridden, assume the same argument as before and resolve based on the overriding file. Depending on how overriding individual settings is implemented, resolving based on the original file might be difficult of course.

But don't make things too complicated, this is a 99 % vs. 1 %-scenario. In 99 % of the use-cases things won't be overridden and users can write "wrong" unit files anyway for any reason. Drop-ins might simply be not supported well like the whole use-case described in this issue is currently. In the end, even without proper support for drop-ins things like `%d` would be an enhancement to all users of the described use-case.

**Comment by elgow** [comment]
Another vote in favor here. 

For units that are not overridden it's possible to determine the source file path from the `FragmentPath` property.  If a unit is overridden using `systemctl edit --full` then the FragmentPath gives the path of the override file rather than the actual source file path.  In that case the source path becomes unknowable.  It would be good to have specifiers to get the path to the unit source file for the use case described above.

**Comment by sshymko** [comment]
A related feature would be support of executive paths relative to `WorkingDirectory`:
https://www.digitalocean.com/community/questions/trying-to-change-workingdirectory-of-systemd-service-unit

**Comment by elgow** [comment]
I'd like to second and elaborate on what @ams-tschoening said about this. I try to have my enabled units link directly to source files in a git checkout directory that is the deployment. If forced to override the contents of the source file as described by @keszybz then all or part of the source file becomes inoperative. It is MUCH more useful to have symbols (either %x or ${x}), in the source file that get replaced by path components. That's available for the home dir with %h and ${HOME}. Why can't it be provided for the location of the source file as well? As it stands, the .path units are almost useless because so much has to be hard-coded a priori in the source file that the deployment becomes far too brittle.

**Comment by sergei66666** [comment]
Also another way which help reduce errors

```
[Service]
WorkingDirectory=/home/admin/testapp
ExecStart=%wd/app-executable
```

**Comment by jansohn** [comment]
I'm also looking for a way to not having to repeat the working directory path in `ExecStart` and `ExecStop`... It violates the DRY principle IMHO...

    WorkingDirectory=/opt/apache-tomcat
    ExecStart=/opt/apache-tomcat/bin/startup.sh
    ExecStop=/opt/apache-tomcat/bin/shutdown.sh

**Comment by anitazha** [comment]
I'm onboarding @alexlzhu and am proposing he works on a feature `BinaryDirectory=` (name TBD) that will use the specified directories as additional, higher priority look up paths for executables without absolute paths. I think that would cover the use cases here and was something we asked for in ASG 2019 (though we never filed an RFE for it).

**Comment by ams-tschoening** [comment]
How does the new `ExecSearchPath` closes this request? From my understanding one still needs to maintain a hard-coded path, which is NOT what this request is about. It's about the exact opposite, to NOT need to maintain those paths in SCM-checkouts. Just look at the examples:

    ExecStart=%d/foo-daemon
    ExecStart=%wd/app-executable

This should be reopened in my opinion.

**Comment by elgow** [comment]
I agree that the `ExecSearchPath` doesn't solve the problem unless it could be specified with a wildcard indicating the path of the current unit, or the cwd or other non-explicit values.

**Comment by anitazha** [comment]
> specified with a wildcard indicating the path of the current unit, or the cwd or other non-explicit values.

There is %I which you can use to pass arbitrary stuff as the instance name:
```
# service_name@.service
[Service]
ExecStart=foo-binary
ExecSearchPath=%I:/bin:/usr/bin:/your_favorite_dir
```
And then you can run like so: `systemctl start service_name@/path/to/bin`
Which results in the path being: /path/to/bin:/bin:/usr/bin:/your_favorite_dir

But actually looking at this issue again you could have used specifiers and templates to do this even without ExecSearchPath= to pass arbitrary paths:
```
# service_name@.service
[Service]
ExecStart=%I/foo-binary
```

ExecSearchPath= allows you to use drop-in overrides though which is nicer if you already know which paths to use.

If you really want a specifier specifically for working directory though we can reopen but I agree with keszybz  that it's a bit of a fringe use case.

**Comment by elgow** [comment]
If a service is set for auto-start at boot would the `systemctl start service_name@/path/to/bin` persist through a reboot?

**Comment by ams-tschoening** [comment]
> And then you can run like so: systemctl start service_name@/path/to/bin

This looks like an ugly hack.

> [...]but I agree with keszybz that it's a bit of a fringe use case.

Absolutely, one simply needs to ignore the LIKE-votes and comments explaining absolutely valid and pretty standard use-cases. :-/

**Comment by anitazha** [comment]
> If a service is set for auto-start at boot would the `systemctl start service_name@/path/to/bin` persist through a reboot?

Yes if you do `systemctl enable` on it which creates the appropriate symlinks. You need to escape the `/` by replacing with `-`

**Comment by matthijskooijman** [comment]
I would indeed agree that the linked PR does not solve my original request, or even improve it at all (it does solve https://github.com/systemd/systemd/issues/6308#issuecomment-474721948 and https://github.com/systemd/systemd/issues/6308#issuecomment-717867652, but IMHO those are really different problems from the original issue). I would suggest reopening this.

Of course, this is a bit of a fringe case, so closing this as wontfix would be a valid path (I personally would prefer adding the specifier, obviously, but I can see that choices must be made in what to implement and what to leave out), but then I would suggest reopening this and then closing it with a clear wontfix statement, for clarity.

As for the `%I` approach, I had not thought of that. AFAICS it would require renaming the unit file to end with an `@` (to become a template). It would still require the user to specify the full pathname to the unit-file/git checkout but then in a command when enabling the unit, rather than hardcoded in the file. So this could use a git-tracked unit file without modifications indeed. It does not implement the request of this issue, but it does provide a less ideal but IMHO workable alternative for the underlying problem.

> If a service is set for auto-start at boot would the systemctl start service_name@/path/to/bin persist through a reboot?

AFAIU, yes, though you'd need `enable`, not `start` here. For example getty is also managed like this, I have a `getty@tty1.service` symlink in my `/etc/systemd/system/getty.target.wants` which persists this instance argument.

**Comment by keszybz** [comment]
@matthijskooijman (and anyone else who commented): please check if #22195 DTRT for you.

**Comment by matthijskooijman** [comment]
@keszybz Thanks! I haven't tested the PR, but from the documentation it seems like it would indeed fix my case *exactly*. Awesome!

**Comment by 5310** [comment]
@matthijskooijman Did fragment specifiers resolve your use-case in the end? 

I would like to use fragment specifiers in my systemd configs as well, but I can't find any information whatsoever as to what they even _are_ in context of systemd, let alone how to use them. The only mention of fragments related to unit files I can find are in this PR that implements fragment specifiers and the documentation it adds. And that's it. 

Could you please direct me to what you found out about them?

**Comment by matthijskooijman** [comment]
> @matthijskooijman Did fragment specifiers resolve your use-case in the end?

I'm not sure I've actually tested yet, but from what I see from the docs, they should solve my case.

> Could you please direct me to what you found out about them?

They are documented in the systemd.unit manpage, in the "FRAGMENT SPECIFICERS" section.

**Comment by matthijskooijman** [comment]
For future reference, the `%y` and `%Y` specifiers are available from systemd 251 and up.
