### ISSUE TITLE
nspawn: Might fail after live-upgrading from 232->233 in hybrid cgroup mode

### ISSUE THREAD

**Issue by LukeShu** [systemd/systemd#6310]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 232 (as shipped by Parabola; mostly vanilla) / 233 (as shipped by Parabola; from the systemd-stable repo)

### Used distribution

> Parabola (similar to Arch Linux)

### In case of bug report: Expected behaviour you didn't see

> I expected that `systemd-nspawn` would be able to run a shell in a container (1) with systemd 233 installed in the container, (2) using a cgroup namespace, and (3) using a user namespace; IOW, a seemingly innocuous use of nspawn on a kernel with userns enabled.

### In case of bug report: Unexpected behaviour you saw

> nspawn failed because it was unable to mount (create) the `name=systemd` cgroup hierarchy (see below)

### In case of bug report: Steps to reproduce the problem

> 1. Be running systemd 232, with hybrid cgroup mode (`systemd.legacy_systemd_cgroup_controller=false`).
>    a. Don't have previously used `systemd-nspawn` to run a container with all cgroup-v1 hierarchies, or anything else that might create the `name=systemd` cgroup-v1 hierarchy.
> 2. Upgrade to systemd 233 package
> 3. `systemctl daemon-reexec` to live-up update without rebooting
> 4. Try to use `systemd-nspawn` to enter a container with the following attributes
>      a. Has systemd 233 installed in it
>      b. Uses cgroup namespace
>      c. Uses user namespace
> 5. Observe the following output:
```
$ sudo systemd-nspawn -D /var/lib/archbuild/x86_64/luke --private-users=pick
[sudo] password for luke: 
Spawning container luke on /var/lib/archbuild/x86_64/luke.
Press ^] three times within 1s to kill container.
Child died too early.
Selected user namespace base 1383661568 and range 65536.
Failed to mount cgroup on /sys/fs/cgroup/systemd (MS_NOSUID|MS_NODEV|MS_NOEXEC "none,name=systemd,xattr"): Operation not permitted
$ echo $?
1
```

**Comment by LukeShu** [comment]
Explanation of the bug:

With cgns and userns, the mounting of cgroups happens in the inner child.  With these conditions, the inner child does not have permission to create new cgroup hierarchies, only to mount existing ones.  systemd 232 CGROUP_UNIFIED_SYSTEMD did not have a `name=systemd` cgroup-v1 hierarchy, but systemd 233 CGROUP_UNIFIED_SYSTEMD does.  The cgroup-util code correctly handles both cases by differentiating between them with `static bool unified_systemd_v232`.  However, nspawn is oblivious to that bool, and the nuance of CGROUP_UNIFIED_SYSTEMD; and assumes that the `name=systemd` v1 hierarchy exists.

**Comment by keszybz** [comment]
Sorry we didn't get to this in time. We're now at 242, so this doesn't make much sense to fix the issue.
