### ISSUE TITLE
core: RuntuimeDirectory are not removed if the option is changed during the system is running

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#6317]
### Submission type

 - Bug report

### systemd version the issue has been seen with

I do not know. At least the recent snapshot decd79829a02cc5b633e0e6ffcbd08f5c3492cfd has this problem.

### Used distribution

Fedora 26 x86_64.

### In case of bug report: Expected behaviour you didn't see

The directories specified by `RuntimeDirectory=` option are certainly removed when the service is stopped even if the option is changed during the service is running.

### In case of bug report: Unexpected behaviour you saw

The directories specified by `RuntimeDirectory=` option are not removed if the option is changed during the service is running.

### In case of bug report: Steps to reproduce the problem

```
$ systemctl cat hoge.service
# /etc/systemd/system/hoge.service
[Service]
RuntimeDirectory=hoge
ExecStart=/usr/bin/sleep 1h
$ sudo systemctl start hoge.service
$ ls /run | grep hoge
hoge
$ sudo emacs /etc/systemd/system/hoge.service
$ sudo systemctl daemon-reload
$ systemctl cat hoge.service
# /etc/systemd/system/hoge.service
[Service]
#RuntimeDirectory=hoge
ExecStart=/usr/bin/sleep 1h
$ sudo systemctl stop hoge.service
$ ls /run | grep hoge
hoge
```

**Comment by poettering** [comment]
hummm, is it really that clear that the dir should be removed in this case? i mean, with the change you made you basically told systemd: "don't manage the runtime dir for me anymore", and that's kind what happens, no?

**Comment by yuwata** [comment]
Ok, I agree.
