### ISSUE TITLE
udev: IMPORT cmdline does not recognize keys with similar names

### ISSUE THREAD

**Issue by remueller** [systemd/systemd#6330]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v.232

### Used distribution

ubuntu 17.04

### In case of bug report: Expected behaviour you didn't see

Test condition:
1. kernel cmdline = ... rootfstype=ext4 root=/dev/sda1 ...
2. kernel cmdline= ... rootfs=root ...

Expected behavior
--> udev rule IMPORT{cmdline}="root"
1. import key root with value /dev/sda1
2. import nothing, root is value of the key rootfs

### In case of bug report: Unexpected behaviour you saw

1. no imports
2. import root as a flag

**Comment by poettering** [comment]
hmm, what? not sure I grok what you are saying? Can you elaborate?

**Comment by remueller** [comment]
It is easy to understand, please have a look at the parser in udev-rules.c  starting from Line 2040.
The problem here:
Line 2054: pos = strstr(cmdline, key);

In usecase 
1. pos is at rootfs= ..         <<-- this is wrong
2. pos is at ..=root              <<-- this is wrong

It is also easy to fix. A simple while loop and one check.

**Comment by poettering** [comment]
Fix waiting in #6925
