### ISSUE TITLE
/etc/systemd/system/default.target.wants is no longer checked for unit files

### ISSUE THREAD

**Issue by rwmjones** [systemd/systemd#6334]
### Submission type

 - Bug report

> systemd-233-6.fc26.x86_64

> Fedora 26

### In case of bug report: Expected behaviour you didn't see

> The service should be running, and the same service worked fine in Fedora <= 25.

### In case of bug report: Unexpected behaviour you saw

> The service does not start.  It is marked as "inactive (dead)" with no other explanation.

```
$ cat /usr/lib/systemd/system/guestfs-firstboot.service
[Unit]
Description=libguestfs firstboot service
After=network.target
Before=prefdm.service

[Service]
Type=oneshot
ExecStart=/usr/lib/virt-sysprep/firstboot.sh start
RemainAfterExit=yes
StandardOutput=journal+console
StandardError=inherit

[Install]
WantedBy=default.target
```

The service is enabled, but it just never runs.

**Comment by rwmjones** [comment]
```
● guestfs-firstboot.service - libguestfs firstboot service
   Loaded: loaded (/usr/lib/systemd/system/guestfs-firstboot.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```

**Comment by rwmjones** [comment]
```
journalctl |& grep guestfs
```
shows no output.

**Comment by rwmjones** [comment]
```
systemctl list-units |& grep guestfs
```
also shows no output.

**Comment by rwmjones** [comment]
Downstream bug about this: https://bugzilla.redhat.com/show_bug.cgi?id=1469655

**Comment by poettering** [comment]
did you enable the unit? "systemctl is-enabled guestfs-firstboot"?

did you actually boot into the "default.target"? note that if you specify an explitict target to boot into on the kernel cmdline then pulling in the unit by default.target as you are doing it has no effect...

**Comment by rwmjones** [comment]
```
# systemctl is-enabled guestfs-firstboot.service
enabled
```

I'm not AFAIK booting into any particular target.  How do I find out the current target?  There's a long thread here: https://www.centos.org/forums/viewtopic.php?t=54347 where no one manages to work out what the current target is.

**Comment by rwmjones** [comment]
```
# systemctl status default.target
● multi-user.target - Multi-User System
   Loaded: loaded (/usr/lib/systemd/system/multi-user.target; enabled; vendor preset: disabled)
   Active: active since Tue 2017-07-11 12:15:15 EDT; 2min 26s ago
     Docs: man:systemd.special(7)

Jul 11 12:15:15 localhost.localdomain systemd[1]: Reached target Multi-User System.
```

**Comment by rwmjones** [comment]
```
# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-4.11.8-300.fc26.x86_64 root=/dev/mapper/fedora-root ro console=tty0 rd_NO_PLYMOUTH rd.lvm.lv=fedora/root rd.lvm.lv=fedora/swap console=ttyS0,115200 LANG=en_US.UTF-8
```

**Comment by poettering** [comment]
maybe there's some dep cycle that caused the unit's job to be removed from the start transaction? consider having a look at "journalctl -b", and look for your unit name. (i figure we should link the dep cycle fixing up log messages properly with the relevant units, so that "systemctl status" shows that properly)

**Comment by poettering** [comment]
(i filed issue #6336 now, asking for improvements on the logging about dep cycles)

**Comment by rwmjones** [comment]
```
journalctl -b |& grep guestfs
```
shows no output.  Is there something else I should be looking for?

**Comment by poettering** [comment]
@rwmjones an chance you can paste the journalctl -b output somewhere so i can have a look?

the other option is to boot in debug mode (by passing `systemd.log_level=debug` on the kernel cmdline), which should tell you in more detail which units systemd considers, and which ones it does not.

Another command to try is "systemctl list-dependencies default.target" and check if your unit is listed among the deps

**Comment by rwmjones** [comment]
https://paste.fedoraproject.org/paste/gIYTpx6caadvGqa29Xmdsg

**Comment by rwmjones** [comment]
`systemctl list-dependencies default.target` does NOT show the service.

You wrote:
> did you enable the unit?

I suspect this has something to do with it.  We're symlinking the unit offline into `/etc/systemd/system/default.target.wants`:
```
lrwxrwxrwx. 1 root root 49 Jul 11 12:29 guestfs-firstboot.service -> /usr/lib/systemd/system/guestfs-firstboot.service
```
This used to work, but is that sufficient to enable the service with Fedora >= 26?  Because we're doing offline modifications, there's no chance of being able to run `systemctl`.

**Comment by poettering** [comment]
> did you enable the unit?
> I suspect this has something to do with it. We're symlinking the unit offline into /etc/systemd/system/default.target.wants:

"systemctl enable" is just a friendly helper. manipulating /etc/systemd/system directly should be entirely OK and supported.

**Comment by rwmjones** [comment]
journal output with systemd debug enabled on the kernel command line:

https://paste.fedoraproject.org/paste/WG4SrttZkoMJAdZxq7DDVg

This shows:
```
Jul 11 12:33:29 localhost.localdomain systemd-sysv-generator[432]: Ignoring S99guestfs-firstboot symlink in rc2.d, not generating guestfs-firstboot.service.
Jul 11 12:33:29 localhost.localdomain systemd-sysv-generator[432]: Ignoring S99guestfs-firstboot symlink in rc3.d, not generating guestfs-firstboot.service.
Jul 11 12:33:29 localhost.localdomain systemd-sysv-generator[432]: Ignoring S99guestfs-firstboot symlink in rc5.d, not generating guestfs-firstboot.service.
```
but I believe that's irrelevant.  We're writing those files for certain very strange/old guests which don't support systemd or allow you to change the init back to sysv. 

However there are no other references to the firstboot service in that file which is pretty strange.

**Comment by rwmjones** [comment]
BTW there is a two line reproducer in:
https://bugzilla.redhat.com/show_bug.cgi?id=1469655#c1
if you have a recent Fedora and wish to try this yourself.  The fedora-26 version in comment 1 fails.  The (almost identical) fedora-25 version in comment 2 works.

**Comment by poettering** [comment]
> https://paste.fedoraproject.org/paste/WG4SrttZkoMJAdZxq7DDVg

Is that the right link? it shows no debug info, and the kernel cmdline it mentions doesn't contain "systemd.log_level=debug" either?

**Comment by rwmjones** [comment]
No it's not.  Here's a proper paste:

https://paste.fedoraproject.org/paste/Wgkxl9E1qZfFy8FHfUkvPQ

**Comment by poettering** [comment]
hmm, so those logs mention your guestfs service in no way whatsoever... when precisely do you create the symlink? does the symlink point to the current unit file?

Note that systemd will look for units only at the moment the generators finished... if you create the symlink later, systemd is likely not to notice, until the next "systemctl daemon-reload"...

you said "systemctl list-dependencies default.target" doesn't list your service. If you issue "systemctl daemon-reload", does it list it then?

**Comment by rwmjones** [comment]
Well we create the symlink offline before the guest boots.

> you said "systemctl list-dependencies default.target" doesn't list your service. If you issue "systemctl daemon-reload", does it list it then?

It is not shown before or after the `systemctl daemon-reload`.

**Comment by rwmjones** [comment]
It's also not shown (before or after) in the dependencies of `multi-user.target`.

**Comment by rwmjones** [comment]
I don't know what this means or even if it is interesting, but after `daemon-reload`, I'm now seeing systemd say `Collecting` each time I run `systemctl status`:
```
● guestfs-firstboot.service - libguestfs firstboot service
   Loaded: loaded (/usr/lib/systemd/system/guestfs-firstboot.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Jul 11 13:02:15 localhost.localdomain systemd[1]: guestfs-firstboot.service: Collecting.
Jul 11 13:02:28 localhost.localdomain systemd[1]: guestfs-firstboot.service: Collecting.
Jul 11 13:02:43 localhost.localdomain systemd[1]: guestfs-firstboot.service: Collecting.
Jul 11 13:02:56 localhost.localdomain systemd[1]: guestfs-firstboot.service: Collecting.
```

**Comment by rwmjones** [comment]
There's even more in the journal now:
```
Jul 11 13:02:56 localhost.localdomain systemd[1]: Accepted new private connection.
Jul 11 13:02:56 localhost.localdomain systemd[1]: systemd-journald.service: Got notification message from PID 439 (WATCHDOG=1)
Jul 11 13:02:56 localhost.localdomain systemd[1]: Got message type=method_call sender=n/a destination=org.freedesktop.systemd1 object=/org/freedesktop/systemd1/unit/guestfs_2dfirstboot_2eservice interface=org.freedesktop.DBus.Properties member=GetAll cookie=1 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: prefdm.service: Failed to load configuration: No such file or directory
Jul 11 13:02:56 localhost.localdomain systemd[1]: SELinux access check scon=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcon=system_u:object_r:systemd_unit_file_t:s0 tclass=service perm=status path=/usr/lib/systemd/system/guestfs-firstboot.service cmdline=systemctl status guestfs-firstboot: 0
Jul 11 13:02:56 localhost.localdomain systemd[1]: Preset files say disable guestfs-firstboot.service.
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=method_return sender=n/a destination=n/a object=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: prefdm.service: Collecting.
Jul 11 13:02:56 localhost.localdomain systemd[1]: guestfs-firstboot.service: Collecting.
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=2 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=916 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=3 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd-logind[552]: Got message type=signal sender=:1.0 destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=917 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=917 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=4 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=918 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=5 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd-logind[552]: Got message type=signal sender=:1.0 destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=919 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=919 reply_cookie=0 error=n/a
Jul 11 13:02:56 localhost.localdomain systemd[1]: Got disconnect on private connection.
```

**Comment by poettering** [comment]
> I don't know what this means or even if it is interesting, but after daemon-reload, I'm now seeing systemd say Collecting each time I run systemctl status:

systemd will GC away all units that are not referenced by anything. (i.e. unload them.) systemd also implicitly loads all units you invoke operations such as "systemctl status" on. Since nothing has a dep on your unit, "systemctl status" hence will cause the unit to be loaded, and then immediately unloaded again, as after that operation is complete there's no further reason to keep the unit around...

The big issue is to find out why systemd doesn't like the symlink you created though, and why it doesn't create the dep for it...

if you do "systemctl disable" for your service, what does that show? if you then do "systemctl enable" for your service, what does that show? does the symlink look any different before these two commands than after? if you do this, does the unit then show up as a proper dep?

**Comment by rwmjones** [comment]
```
# systemctl disable guestfs-firstboot.service
Removed /etc/systemd/system/default.target.wants/guestfs-firstboot.service.
# systemctl enable guestfs-firstboot.service
Created symlink /etc/systemd/default.target.wants/guestfs-firstboot.service -> /usr/lib/systemd/system/guestfs-firstboot.service
# systemctl list-dependencies default.target |& grep guestfs
```
Nothing is shown by the last command.  The symlink that is created looks exactly the same as before except for a different date.

**Comment by rwmjones** [comment]
Is there something wrong with the unit file itself (I pasted it near the top of this bug report).

**Comment by poettering** [comment]
```
# systemctl enable guestfs-firstboot.service Created symlink /etc/systemd/default.target.wants/guestfs-firstboot.service -> /usr/lib/systemd/system/guestfs-firstboot.service
```

is that ^^^ really the output? There's something wrong with the paths... /etc/systemd should be /etc/systemd/system...

**Comment by rwmjones** [comment]
Sorry, I'm unable to copy and paste from the qemu console so I have to retype everything.  The enable command really said:
```
# systemctl enable guestfs-firstboot.service
Created symlink /etc/systemd/system/default.target.wants/guestfs-firstboot.service -> /usr/lib/systemd/guestfs-firstboot.service.
```

**Comment by rwmjones** [comment]
Have a pic since github seems unable to upload files of any kind ... https://pasteboard.co/GAtckNJ.png

**Comment by poettering** [comment]
hmm, this is all quite puzzling... Does "/usr/lib/systemd/systemd --test" list the unit? if not, can you strace it, and upload the logs that generates somewhere?

**Comment by rwmjones** [comment]
I'm not sure I'm doing this right.  When I run `/usr/lib/systemd/systemd --test` as root it says:
```
Don't run test mode as root.
```
So I created a user account and ran it there, but strace shows that it's only looking at targets in `/usr/lib/systemd/user`.  Not surprisingly in neither case is the `guestfs-firstboot.service` ever read.

**Comment by rwmjones** [comment]
OK I learned about the `--test --system` options.  Still running it as non-root, the strace output is here:
https://paste.fedoraproject.org/paste/LFDy2sGuAwNI7PJeiHqneQ

**Comment by rwmjones** [comment]
It never looks in `/etc/systemd/system/default.target.wants/` at all, instead:
```
open("/etc/systemd/system/default.target", O_RDONLY|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC) = -1 ELOOP (Too many levels of symbolic links)
readlinkat(AT_FDCWD, "/etc/systemd/system/default.target", "/lib/systemd/system/multi-user.target", 99) = 37
open("/lib/systemd/system/multi-user.target", O_RDONLY|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC) = 17
```

**Comment by rwmjones** [comment]
I bisected this to the following commit:
```
2d058a87ffb2d31a50422a8aebd119bbb4427244 is the first bad commit
commit 2d058a87ffb2d31a50422a8aebd119bbb4427244
Author: Franck Bui <fbui@suse.com>
Date:   Tue Jan 24 14:29:57 2017 +0100

    core: don't load dropin data multiple times for the same unit (#5139)
    
    When an alias is loaded, we resolve this alias to its final unit first to load
    the dropin data.
    
    However if the final unit was already loaded, there's no point in reloading the
    dropin data a second time.
    
    This patch optimizes this case.
    
    Also this allows the dropin loading code to assume that only units not yet
    loaded are passed down. This assumption is not yet used but might be in the
    future.
    
    [zj: invert the condition in the if]

:040000 040000 fca9ba713a6db34b03f028f3c87e500e5a5b7bfd aaa2a9d855ca7f5c46edecda2d3e57cfac74ab09 M	src
```

**Comment by rwmjones** [comment]
This commit reverts cleanly on top of the master branch.  To be sure of my analysis I reverted this commit and built systemd from the master branch, and that processes the service file correctly, so I'm very sure that commit 2d058a87ffb2d31a50422a8aebd119bbb4427244 is at fault.

**Comment by rwmjones** [comment]
To test for this:

1. Create `/etc/systemd/system/default.target.wants/`
2. Place a symlink to a unit file in there, eg. a symlink to `sshd.service`
3. Compile systemd from source.
4. Run: `strace -f ./systemd --system --test`

In the strace output, check whether `/etc/systemd/system/default.target.wants/` is opened, and whether the service file is read.  eg. If it's working you should see:
```
open("/etc/systemd/system/default.target.wants", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 16
stat("/etc/systemd/system/default.target.wants/sshd.service", {st_mode=S_IFREG|0644, st_size=372, ...}) = 0
lstat("/etc/systemd/system/default.target.wants/sshd.service", {st_mode=S_IFLNK|0777, st_size=36, ...}) = 0
readlinkat(AT_FDCWD, "/etc/systemd/system/default.target.wants/sshd.service", "/usr/lib/systemd/system/sshd.ser"..., 99) = 36
```
If it's not working it'll ignore this directory entirely.

**Comment by poettering** [comment]
Yeah 2d058a8 appears to be the culprit, and needs fixing.

/cc @fbuihuu

**Comment by fbuihuu** [comment]
@poettering : yes that's a "known" issue you already noticed and reported it, see https://github.com/systemd/systemd/issues/5248.

The handling of the aliases and its dropins is pretty inconsistent with or without 2d058a8 but since loading alias dropins used to work before I'm fine to revert the commit.
