### ISSUE TITLE
resolved's stub DNS server breaks after adding 127.0.0.1 to resolv.conf

### ISSUE THREAD

**Issue by versusvoid** [systemd/systemd#6344]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> resolved's stub DNS server resolves all queries using servers from /etc/resolv.conf

### In case of bug report: Unexpected behaviour you saw

> resolved's stub DNS servers does not resolve domain names answering with "status: NOERROR" to DNS queries

### In case of bug report: Steps to reproduce the problem

1. Setup nameserver (I use BIND) to resolve your local names and run it on 127.0.0.1
2. Write custom /etc/resolv.conf like:
```
nameserver 127.0.0.1
nameserver 192.168.0.1
nameserver 8.8.8.8
search my.lovely.domain
```
3. Setup and start systemd-resolved
4. Query any name from 127.0.0.53:
```
$ dig google.com @127.0.0.53

; <<>> DiG 9.11.1-P3 <<>> google.com @127.0.0.53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30538
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.			IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jul 12 13:28:19 MSK 2017
;; MSG SIZE  rcvd: 39

```
If I remove 127.0.0.1 from /etc/resolv.conf stub resolver starts resolving immediately.

**Comment by poettering** [comment]
What is the precise output of "systemd-resolve --status"?

Could you use tcpdump/wireshark and check which DNS packets are exchanged on the loopback device?

Also, could you run systemd-resolved with the SYSTEMD_LOG_LEVEL=debug env var set, and paste the precise log output one such query generates?

**Comment by versusvoid** [comment]
I changed BIND's config to listen on custom static ip (10.0.0.1) and on it only. Used it in resolv.conf instead of 127.0.0.1. Behavior of systemd-resolved is the same.

Dumps from wireshark and logs from resolved attached. I've tried to resolve host "ya.ru".

[info.zip](https://github.com/systemd/systemd/files/1164477/info.zip)

**Comment by keszybz** [comment]
Sorry we couldn't handle this. There have been a lot of fixes upstream to the stub listener. Please reopen if this is still an issue with either of the two recent releases.
