### ISSUE TITLE
Add support for "Advertised link modes" option in systemd.link

### ISSUE THREAD

**Issue by cshapeshifter** [systemd/systemd#6345]
### Submission type
> Request for enhancement (RFE)

### systemd version the issue has been seen with
> 233.75

### Used distribution
> Archlinux

### RFE
systemd.link should provide parameters to configure advertised link modes. These can be set using ethtool as follows (setting 100baseT/Full, which corresponds to 0x008, in this example):
```ethtool -s enp0s20u2u3 advertise 0x008```
This setting is also automagically configured by ethtool when setting the link speed, i.e.
```ethtool -s enp0s20u2u3 speed 100 duplex full```
There is currently no way to set this in systemd.link

### More background
The only way to configure link speed in systemd.link is to **also disable autonegotiation**, otherwise the speed settings are read-only, i.e.:
```
[Link]
AutoNegotiation=no
Duplex=full
BitsPerSecond=100M
```
But disabling autoneg means that the other side (i.e. the switch) will **default to 10M** unless explicitely configured as well. I don't have control over that switch, though. With ethtool, running
```ethtool -s enp0s20u2u3 speed 100 duplex full```
results in the following config:
```
Settings for enp0s20u2u3:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  100baseT/Full 
	Advertised pause frame use: Symmetric
	Advertised auto-negotiation: Yes
	Link partner advertised link modes:  10baseT/Half 10baseT/Full 
	                                     100baseT/Half 100baseT/Full 
	Link partner advertised pause frame use: Symmetric Receive-only
	Link partner advertised auto-negotiation: Yes
	Speed: 100Mb/s
	Duplex: Full
	Port: MII
	PHYAD: 3
	Transceiver: internal
	Auto-negotiation: on
	Supports Wake-on: pg
	Wake-on: g
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes
```
I.e. the speed is set to 100Mb/s, the advertised speed is also set to 100baseT/Full, yet **autoneg is still enabled**. This is, for me, the only way to set the speed from my end without control over the switch. Autoneg needs to be on, but the advertised link speed must be 100Mb/s

### Why do this at all?
I'm using a Delock 62121 USB 3.0 Gigabit adaptor which is a "ASIX Electronics Corp. AX88179 Gigabit Ethernet" device, which is supported by the ax88179_178a kernel driver and part of many generic Gigabit USB adaptors. Unfortunately, for one reason or another, the device fails on heavy load (see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=335711), [here](https://bugzilla.redhat.com/show_bug.cgi?id=1389548) and [here](https://ubuntuforums.org/showthread.php?t=2089845&page=4&p=12748513#post12748513), but mind that the problem still persists for some people, including myself, even though others report the problem solved. Maybe it was fixed in 3.10 and has regressed, who knows). The only solution is to limit the link speed to 100 to avoid these lock-ups. That said, the option should be added to systemd.link regardless of any solution related to this specific problem.

**Comment by ssahani** [comment]
we have a PR fo this . https://github.com/systemd/systemd/pull/6136

**Comment by yuwata** [comment]
#6136 was merged. Let's close this.
