### ISSUE TITLE
RFE: add support for set-keymap to systemd-firstboot

### ISSUE THREAD

**Issue by tblume** [systemd/systemd#6346]
### Submission type

 - Request for enhancement (RFE)

### Used distribution

openSUSE Tumbleweed

systemd-firstboot can already set the systems locale (e.g. localectl set-locale) but it is missing the feature to set the systems keymap (e.g. localectl set-keymap).
This feature would be especially helpful, because systemd-firstboot can operate without running system services.

If this feature is acceptable for upstream, we will try to implement it.

**Comment by tblume** [comment]
@poettering Just to make sure, there are no objections for this feature?

**Comment by poettering** [comment]
sure, makes sense to add!

**Comment by zilti** [comment]
Oh great - systemd has to be modified for that? That speaks volumes about that piece of, uhh, Software...

**Comment by poettering** [comment]
Closing, #7035 got merged.
