### ISSUE TITLE
test-condition fails when run as non-root system user

### ISSUE THREAD

**Issue by jrtc27** [systemd/systemd#6366]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

Debian

### In case of bug report: Expected behaviour you didn't see

Running test-condition without root privileges as a user in the system range passes.

### In case of bug report: Unexpected behaviour you saw

> Assertion 'r == 0' failed at ../src/test/test-condition.c:396, function test_condition_test_user(). Aborting.

This is because `@system` as a user condition is true if the user is within the system range, but if this is the case, the test asserts that `geteuid()` returned 0, indicating the root user. This is clearly not always true, especially when the build is run by an automated service running as an unprivileged system user.

### In case of bug report: Steps to reproduce the problem

1. Create a system user
2. Run test-condition as that user

Example failure is visible near the bottom of https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=sparc64&ver=234-1&stamp=1499982113&raw=0

**Comment by fsateler** [comment]
Hmm. I guess the condition should be changed to `geteuid() < SYSTEM_UID_MAX`.

**Comment by fsateler** [comment]
PR waiting in #6409 , please test
