### ISSUE TITLE
meson: install target for libraries

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#6372]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> v234

### Used distribution

> Arch Linux

### Request

For Arch Linux we have a split package `subsystems`. Builing with auto-make we had an install target for libraries. Any chance to have that for meson as well? Expected file list:
```
usr/
usr/lib/
usr/lib/libnss_myhostname.so.2
usr/lib/libnss_mymachines.so.2
usr/lib/libnss_resolve.so.2
usr/lib/libnss_systemd.so.2
usr/lib/libsystemd.so
usr/lib/libsystemd.so.0
usr/lib/libsystemd.so.0.19.0
usr/lib/libudev.so
usr/lib/libudev.so.1
usr/lib/libudev.so.1.6.6
```

**Comment by eworm-de** [comment]
Cc @falconindy

**Comment by mbiebl** [comment]
Just curious, what's the use case for this? The binary distros I know use ```make install``` and then split up the install directory into the binary packages as they see fit. Why is an install target needed in Arch?

**Comment by falconindy** [comment]
Laziness? Admittedly, it doesn't save us much, because we still need to locate and delete libraries from the systemd package that the magic target installed to the libsystemd package.

**Comment by eworm-de** [comment]
I always found this useful. But feel free to close with wont-fix, easy to handle this on our own.

**Comment by keszybz** [comment]
I think it would be useful. I would like to have a way to compile part of systemd (probably everything except libraries) with asan, and the libraries without asan. (Installing systemd libs linked to asan seems to break external programs which use those libs.) Having a target could become a basis for that.

So yeah, if somebody submits a patch…

**Comment by poettering** [comment]
hmpf, i hope this doesn't proliferate, but OK. needs a patch though

**Comment by floppym** [comment]
Related meson feature request:

https://github.com/mesonbuild/meson/issues/1682

**Comment by DaanDeMeyer** [comment]
We have meson install tags now for the libraries so I think we can close this
