### ISSUE TITLE
size mount option ignored when expressed in %

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6374]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v233, specifically
https://github.com/systemd/systemd/pull/5255

### Used distribution

Debian
Downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865450

### In case of bug report: Expected behaviour you didn't see

Using size=XX% in mount units should continue to work as it did in previous versions

### In case of bug report: Unexpected behaviour you saw

Using Option=size=70% in a tmp.mount unit resulted in systemd misparsing that statement and /tmp becoming mounted with a size of 4K. The result is a system which fails to boot properly. E.g. gdm will fail to start and constantly respawn.

The change in #5255 broke exiting valid mount units. We should be more careful when breaking backwards compatibility, especially if the results are as bad as in this case.

### In case of bug report: Steps to reproduce the problem

Create a tmp.mount unit containing

```
[Unit]
Description=Temporary Directory (/tmp)
Documentation=man:hier(7)
Documentation=https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
ConditionPathIsSymbolicLink=!/tmp
DefaultDependencies=no
Conflicts=umount.target
Before=local-fs.target umount.target
After=swap.target

[Mount]
What=tmpfs
Where=/tmp
Type=tmpfs
Options=nodev,nosuid,size=10%

[Install]
WantedBy=local-fs.target
```
Then reboot and check that /tmp is now mounted with 4k size:
```
# systemctl show -p Options tmp.mount 
Options=rw,nosuid,nodev,relatime,size=4k
```

**Comment by evverx** [comment]
> The change in #5255 broke exiting valid mount units.

It seems that they have been broken by d107589cd2767c95fb1c79, not #5255.

> Using size=XX% in mount units should continue to work as it did in previous versions

Unfortunately, It doesn't seem to be possible. There was a chance to revert d107589cd2767c95fb1c79 before releasing `v233`, but for some reason [my question](https://github.com/systemd/systemd/issues/5086#issuecomment-272771708) was ignored. Probably, I should have been more specific.
