### ISSUE TITLE
rejected send message by D-Bus from logind

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6375]
### Submission type

 - Bug report
 
### systemd version the issue has been seen with

v234

### Used distribution

Debian sid
dbus 1.10.20-1

Since upgrading from v233 to v234, I get lots of error messages in the journal like this
```
Jul 14 17:14:41 pluto dbus[589]: [system] Rejected send message, 2 matched rules; type="error", sender=":1.1" (uid=0 pid=588 comm="/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.25" (uid=109 pid=1029 comm="/usr/bin/gnome-shell ")
```
and
```
Jul 14 17:14:53 pluto dbus[589]: [system] Rejected send message, 2 matched rules; type="error", sender=":1.1" (uid=0 pid=588 comm="/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.61" (uid=1000 pid=1843 comm="/usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/use")
```
Since I booted the system an hour ago, I got 42 such messages in the journal.

I've filed this against systemd, as I didn't see this with v233.

**Comment by poettering** [comment]
hmm, we haven't change the dbus policy in a while... Any chance you can use "busctl monitor" and figure out what message is precisely causing this?

**Comment by poettering** [comment]
did really only the systemd version change when this showed up? dbus didn't get updated as well?

**Comment by mbiebl** [comment]
Only systemd was updated from 233 to 234

**Comment by mbiebl** [comment]
@poettering can you give me some hints how I can provide the requested information using busctl monitor?

**Comment by mbiebl** [comment]
@poettering I tried to run busctl monitor, but this produced a 3M file. I have no idea where to look for:
https://people.debian.org/~biebl/dbus-reject.txt

**Comment by mbiebl** [comment]
```
‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=107  ReplyCookie=101
  Sender=:1.3  Destination=:1.23
  ErrorName=org.freedesktop.DBus.Error.UnknownMethod  ErrorMessage="Unknown method 'TakeDevice' or interface 'org.freedesktop.login1.Session'."
  UniqueName=:1.3
  MESSAGE "s" {
          STRING "Unknown method 'TakeDevice' or interface 'org.freedesktop.login1.Session'.";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=30  ReplyCookie=107
  Sender=org.freedesktop.DBus  Destination=:1.3
  ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Rejected send message, 2 matched rules; type="error", sender=":1.3" (uid=0 pid=343 comm="/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.23" (uid=116 pid=539 comm="/usr/bin/gnome-shell ")"
  MESSAGE "s" {
          STRING "Rejected send message, 2 matched rules; type="error", sender=":1.3" (uid=0 pid=343 comm="/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.23" (uid=116 pid=539 comm="/usr/bin/gnome-shell ")";
  };
```

**Comment by mbiebl** [comment]
c1 is the session for gdm and I just checked with that this method is there:
```
$ busctl introspect org.freedesktop.login1 /org/freedesktop/login1/session/c1 org.freedesktop.login1.Session  | grep TakeDevice
.TakeDevice                    method    uu        hb 
```

**Comment by mbiebl** [comment]
I was probably a bit pro-active removing the needs-reporter-feedback. In any case, if there is any info I can provide, I'm happy to do so.

**Comment by smcv** [comment]
> `requested_reply="0"`

This typically means one of two things:

* The service (logind) didn't respect the `NO_REPLY` flag
* The service replied twice to the same method call

**Comment by smcv** [comment]
GNOME Shell (or whatever) called the method:

```
â€£ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=101
  Sender=:1.23  Destination=:1.3  Path=/org/freedesktop/login1/session/c1  Interface=org.freedesktop.login1.Session  Member=TakeDevice
  UniqueName=:1.23
  MESSAGE "uu" {
          UINT32 13;
          UINT32 69;
  };
```

logind replied:

```
â€£ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=106  ReplyCookie=101
  Sender=:1.3  Destination=:1.23
  UniqueName=:1.3
  MESSAGE "hb" {
          UNIX_FD 4;
          BOOLEAN false;
  };
```

But then logind replied again:

```
â€£ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=107  ReplyCookie=101
  Sender=:1.3  Destination=:1.23
  ErrorName=org.freedesktop.DBus.Error.UnknownMethod  ErrorMessage="Unknown method 'TakeDevice' or interface 'org.freedesktop.login1.Session'."
  UniqueName=:1.3
  MESSAGE "s" {
          STRING "Unknown method 'TakeDevice' or interface 'org.freedesktop.login1.Session'.";
  };
```

and this is not allowed:

```
â€£ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=30  ReplyCookie=107
  Sender=org.freedesktop.DBus  Destination=:1.3
  ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Rejected send message, 2 matched rules; type="error", sender=":1.3" (uid=0 pid=343 comm="/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.23" (uid=116 pid=539 comm="/usr/bin/gnome-shell ")"
  MESSAGE "s" {
          STRING "Rejected send message, 2 matched rules; type="error", sender=":1.3" (uid=0 pid=343 comm="/lib/systemd/systemd-logind ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.23" (uid=116 pid=539 comm="/usr/bin/gnome-shell ")";
  };
```

**Comment by poettering** [comment]
It appears the method_take_device() mistakenly returns "0", rather than "1", and hence we search for a second method implementation after invoking the first one, and of course can't find any.

Ouch!

**Comment by poettering** [comment]
Fix waiting in #6583. Please give it a whirl!

**Comment by bhack** [comment]
@mbiebl Do you know if this patch was backported to the debian package?

**Comment by mbiebl** [comment]
@bhack as in 232-25+deb9u1 for stretch? Then the answer is no
See https://anonscm.debian.org/git/pkg-systemd/systemd.git/log/?h=stretch

**Comment by mbiebl** [comment]
@bhack keep in mind though, that v232 in stretch is not affected

**Comment by bhack** [comment]
@mbiebl Cause we still not have a new upstream dbus release so I meant to "backport" this fix in the v234 package in testing/sid

**Comment by bhack** [comment]
@mbiebl Also this is the only log entry that seems to slowdown screen unlocking in testing/sid

**Comment by smcv** [comment]
> Cause we still not have a new upstream dbus release

This is not a dbus bug (dbus-daemon is behaving as expected) so it will not be fixed in a dbus release. The upstream release that fixes it should be systemd v235.

> so I meant to "backport" this fix in the v234 package in testing/sid

I'm sure your test results from a locally-built package with that patch applied would be appreciated.

**Comment by bhack** [comment]
Yes was just a typo I meant systemd. I'll try to rebuild test/sid source package with this patch

**Comment by bhack** [comment]
I've created the patched packages and reinstalled. Now the error disappear from the log.
So this issue was non related to the gdm unlocking screen freeze cause the probem it is still here.
