### ISSUE TITLE
"systemctl start" on wildcarded units should generate a friendly error, explaining why that's not supported

### ISSUE THREAD

**Issue by archuserr** [systemd/systemd#6379]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd 233
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid

### Used distribution

arch

It appears you can use wildcards to stop services, but not start them.

Works: `systemctl stop mything*.timer`

Doesn't work: `systemctl start mything*.timer`. It's extra painful because this returns 0 and no error message.

For consistency, it seems like they should both work the same way. If not, the second one should return an error.

**Comment by rwolfson** [comment]
Does adding `--all` work around this issue for you? I believe I hit the same behavior on systemd 232 but adding that flag seems to do the trick.

**Comment by poettering** [comment]
Sorry but we can't really support this. systemd loads units on demand, it never enumerates all possible units from disk, and hence doesn't know the potential list of units that it could ever start, and hence cannot match a wildcard against them. 

And we can't really change that: the way systemd works units might be synthesized during runtime that do not exist on disk (think: a .service instance created by a per-connection socket activation, or a .device unit showing up due to some device being plugging in, or a .mount unit showing up due to some mount point being set up by the user with /bin/mount), and we couldn't possibly know in advance what that might end up being.

Hence, stopping by wildcard is easy: we can just apply the wildcard to all units current loaded/started, and that makes a ton of sense, since in order to be stoppable they need to be started and thus the list we apply the wildcard is necessarily sufficiently complete. But for starting by wildcard things are hard, since for starting them the units would need to be stopped atm, but conceptually *all* units that aren#t explicitly started are stopped, and there are an infinity of those around...

I hope that makes some sense?

Yes, this asymmetry is a bit weird and surprising, but there's some logic behind it...

**Comment by archuserr** [comment]
thanks for the explanation. my complaint is that it returns 0. it should return an error. "wildcards not allowed"

**Comment by archuserr** [comment]
i confirmed the --all flag makes the start command work with wildcards. thanks!

**Comment by zacharyno** [comment]
Warning on systemctl stop calls containing a wildcard would be helpful from
an administrative perspective.

**Comment by poettering** [comment]
adding better logging for this case definitely makes sense. Reopening and renaming accordingly.

**Comment by fthiery** [comment]
Just my 2 cents: the log message may suggest using --all if the user really wants to do this.

**Comment by archuserr** [comment]
I was playing with wildcards again today.

```
systemd 242 (242.29-3-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

Wildcards now work for starting unit files (sometimes). I don't know if this is intentional because the comments above say there's a good reason it doesn't work.

But it's confusing because wildcards only work from ```/etc/systemd/system/```

Works: ```/etc/systemd/system/$ systemctl start abc*.timer```

```~$ systemctl start /etc/systemd/system/abc*.timer``` results in 
```
Failed to start etc-systemd-system-abc0.timer.mount: Unit etc-systemd-system-abc0.timer.mount not found.
Failed to start etc-systemd-system-abc1.timer.mount: Unit etc-systemd-system-abc1.timer.mount not found.
```

Since this issue is still open, I thought I would followup. Additional consistency and error messages would still be helpful.

**Comment by TuningYourCode** [comment]
i think if you switch into the folder your shell will resolve the wildcard.

**Comment by gingerlime** [comment]
Since the other issue I asked at was just closed, I'll copy over my question here. Hope someone can help?

I know this is open for a while, but I'm also bumping into this and starting to bang my head against the wall a bit... 

> Like @tomaskrizek I have a few services using a template, e.g. `sidekiq@batch.service`, `sidekiq@mailer.service` all symlinking to `sidekiq@.service`. I want to be able to stop/start/reload/restart them as a group somehow, without having to specify each individual service...
> 
> I think that using a parent target using `WantedBy` or using `PartOf` kinda works, but then it won't propagate reloads for example... (also tried using `ReloadPropagatedFrom` on the children, which doesn't seem to help, or maybe I did something wrong?)
> 
> Would appreciate some guidance here if someone has some working examples or anything else that could work here...

**Comment by keszybz** [comment]
@gingerlime ReloadPropagatedFrom= should work. Testing with current git:
```console
$ systemctl --user reload.target reload-inst@.service
# /home/zbyszek/.config/systemd/user/reload.target
[Target]

# /home/zbyszek/.config/systemd/user/reload-inst@.service
[Service]
ExecStart=sleep %i
ExecReload=echo "doing nothing!"

[Unit]
ReloadPropagatedFrom=reload.target

[Install]
WantedBy=reload.target
$ systemctl --user enable reload-inst@{1,2,3}
Created symlink /home/zbyszek/.config/systemd/user/reload.target.wants/reload-inst@1.service → /home/zbyszek/.config/systemd/user/reload-inst@.service.
Created symlink /home/zbyszek/.config/systemd/user/reload.target.wants/reload-inst@2.service → /home/zbyszek/.config/systemd/user/reload-inst@.service.
Created symlink /home/zbyszek/.config/systemd/user/reload.target.wants/reload-inst@3.service → /home/zbyszek/.config/systemd/user/reload-inst@.service.
$ systemctl --user start reload.target; sysu reload reload.target
$ journalctl --user-unit=reload.target --user-unit=reload-inst@{1,2,3}
Oct 16 16:58:21 krowka systemd[1934]: Started reload-inst@1.service.
Oct 16 16:58:21 krowka systemd[1934]: Started reload-inst@2.service.
Oct 16 16:58:21 krowka systemd[1934]: Started reload-inst@3.service.
Oct 16 16:58:21 krowka systemd[1934]: Reloading reload-inst@1.service.
Oct 16 16:58:21 krowka systemd[1934]: Reloading reload-inst@2.service.
Oct 16 16:58:21 krowka systemd[1934]: Reloading reload-inst@3.service.
Oct 16 16:58:21 krowka echo[406301]: doing nothing!
Oct 16 16:58:21 krowka systemd[1934]: Reloaded reload-inst@1.service.
Oct 16 16:58:21 krowka echo[406302]: doing nothing!
Oct 16 16:58:21 krowka systemd[1934]: Reloaded reload-inst@2.service.
Oct 16 16:58:21 krowka echo[406303]: doing nothing!
Oct 16 16:58:21 krowka systemd[1934]: Reloaded reload-inst@3.service.
Oct 16 16:58:21 krowka systemd[1934]: Reloaded reload.target.
Oct 16 16:58:22 krowka systemd[1934]: reload-inst@1.service: Succeeded.
Oct 16 16:58:23 krowka systemd[1934]: reload-inst@2.service: Succeeded.
Oct 16 16:58:24 krowka systemd[1934]: reload-inst@3.service: Succeeded.
```

**Comment by gingerlime** [comment]
Thanks a lot @keszybz ! Maybe I overcomplicated some stuff using `PartOf`? I'm not sure... I'll test it on my system and report back.

**Comment by gingerlime** [comment]
sorry for the delay, but I can confirm that this works 👍 thanks again @keszybz !!
