### ISSUE TITLE
SystemD is not running with watch params.

### ISSUE THREAD

**Issue by ijunaid8989** [systemd/systemd#6395]
I have looked at [the official docs for start-up][1], but I failed to replicate my Upstart job to systemd.

Upstart Job:

    description  "evercam_media"
    start on filesystem or runlevel [2345]
    stop on runlevel [!2345]
    limit nofile 1000000 1000000
    
    respawn
    chdir /
    setuid root
    setgid root
    
    exec watch -n1 '/usr/local/bin/run_evercam_media.sh'
    
    post-stop exec sudo pkill beam

I have replicated almost the same while reading the doc files as

    [Unit]
    Description=evercam_media
    [Service]
    User=root
    Group=root
    WorkingDirectory=/
    ExecStart=/bin/sh -ec "exec watch -n1 '/usr/local/bin/run_evercam_media.sh'"
    ExecStopPost=sudo pkill beam
    Restart=always
    
    [Install]
    WantedBy=multi-user.target

But when ever I do `systemctl daemon-reload` and `systemctl status evercam_media.service` I only get the errors as

    ● evercam_media.service - evercam_media
       Loaded: loaded (/etc/systemd/system/evercam_media.service; enabled; vendor preset: enabled)
       Active: inactive (dead) (Result: exit-code) since Tue 2017-07-18 08:41:23 CEST; 12s ago
      Process: 32596 ExecStart=/bin/sh -ec exec watch -n1 '/usr/local/bin/run_evercam_media.sh' (code=exited, status=1/FAILURE)
     Main PID: 32596 (code=exited, status=1/FAILURE)
    
    Jul 18 08:41:22 Ubuntu-1604-xenial-64-minimal systemd[1]: evercam_media.service: Unit entered failed state.
    Jul 18 08:41:22 Ubuntu-1604-xenial-64-minimal systemd[1]: evercam_media.service: Failed with result 'exit-code'.
    Jul 18 08:41:23 Ubuntu-1604-xenial-64-minimal systemd[1]: evercam_media.service: Service hold-off time over, scheduling restart.
    Jul 18 08:41:23 Ubuntu-1604-xenial-64-minimal systemd[1]: Stopped evercam_media.
    Jul 18 08:41:23 Ubuntu-1604-xenial-64-minimal systemd[1]: evercam_media.service: Start request repeated too quickly.
    Jul 18 08:41:23 Ubuntu-1604-xenial-64-minimal systemd[1]: Failed to start evercam_media.
    root@Ubuntu-1604-xenial-64-minimal:/etc/systemd/system# 

As they have mentioned in the docs.. 
`exec` is going to be `/bin/sh 'exec'` So I have tried it as above but it fails. But If I just do this in terminal `exec watch -n1 '/usr/local/bin/run_evercam_media.sh'` Everything gets started.

  [1]: https://wiki.ubuntu.com/SystemdForUpstartUsers#Example_Systemd_service

UPDATE:

I just want to run the sh script everyone 1 second and `Watch` is the tool I have ended with to use.

**Comment by arvidjaar** [comment]
> I just want to run the sh script everyone 1 second

Then simply use systemd timer unit to do it.

**Comment by ijunaid8989** [comment]
I have created a unit as 

```
# foo.timer
[Unit]
Description=Do whatever

[Timer]
OnActiveSec=1
OnUnitActiveSec=1

[Install]
WantedBy=timers.target
```

But how it will run my command?

**Comment by ijunaid8989** [comment]
I have added that timer unit and also 
```
systemctl enable foo.timer
```
the above results in 
```
Created symlink from /etc/systemd/system/timers.target.wants/foo.timer to /etc/systemd/system/foo.timer.
```

But the main question is.. where I am going to tell it that.. this is the command you should run?

**Comment by ijunaid8989** [comment]
also at first place, if the service is not running right.. how A timer will make it run correctly?

**Comment by boucman** [comment]
You need a foo.service unit. Timers will trigger a service with the same name (unless you change that with a Unit= directive)

**Comment by fsateler** [comment]
Hi,

> I have looked at the official docs for start-up, but I failed to replicate my Upstart job to systemd.

This is a bug tracker, and not a support channel. Please ask your question on the systemd list: systemd-devel@lists.freedesktop.org , which is more suited for this type of question.

I'm going to close this issue now. Please ask on the mailing list.

Saludos
