### ISSUE TITLE
DHCP license renewal causes disconnect

### ISSUE THREAD

**Issue by nicolasbock** [systemd/systemd#64]
Disclaimer: this may not be at all related to systemd...

When I run the Juniper Network Connect client (ncsvc) it terminates every time the DHCP license is renewed. It doesn't make a difference whether I specify CriticalConnection=true or false. Since systemd-networkd is managing the NIC and the DHCP license, I am suspecting it as the cause for the ncsvc problem. But then again, correlation is not causation as they say.

The log files of ncsvc are unfortunately rather cryptic. The only information I could extract from them is the following line:

20150603133456.514649 ncsvc[p6870.t6870] rmon.error Route to destination 192.168.1.1 is missing mask 255.255.255.255 with gw 0.0.0.0, metric 1, if_id 0, disconnecting (routemon.cpp:628)

which coincides with the following journal entries:

Jun 03 13:34:55.454967 host NetworkManager[1805]: <info>    address 192.168.1.16
Jun 03 13:34:55.454985 host NetworkManager[1805]: <info>    plen 24
Jun 03 13:34:55.454990 host NetworkManager[1805]: <info>    expires in 300 seconds
Jun 03 13:34:55.455026 host NetworkManager[1805]: <info>    gateway 192.168.1.1
Jun 03 13:34:55.455035 host NetworkManager[1805]: <info>    nameserver '192.168.1.1'
Jun 03 13:34:55.455210 host NetworkManager[1805]: <info>  (wlp6s0): DHCPv4 state changed bound -> bound
Jun 03 13:34:55.456679 host dbus[1799]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jun 03 13:34:55.461372 host dbus[1799]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jun 03 13:34:55.462021 host nm-dispatcher[8295]: Dispatching action 'dhcp4-change' for wlp6s0
Jun 03 13:34:56.514958 host systemd-networkd[1803]: tun0            : lost carrier

Is the DHCP renewal triggering a change in the routing table, which in turn makes ncsvc unhappy?

systemd-218
networkmanager-1.0.2

Thanks for any suggestions

**Comment by arvidjaar** [comment]
> Since systemd-networkd is managing the NIC and the DHCP license

But your log shows that lease renewal is done by NetworkManager, not by systemd-networkd.

**Comment by nicolasbock** [comment]
That's true. Let me me ask this question on the networkmanager mailing list then. Thanks for the help!

**Comment by arvidjaar** [comment]
NM guys accepted responsibility :)
