### ISSUE TITLE
Journal less escalates SIGINT to SIGTERM 

### ISSUE THREAD

**Issue by kgreav** [systemd/systemd#6405]
### Submission type

 - Bug report

### systemd version the issue has been seen with
```
>journalctl --version
systemd 233
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid
```

### Used distribution

> Fedora 26

### In case of bug report: Expected behaviour you didn't see

> Setting SYSTEMD_LESS to exclude "K" should allow interrupt to be sent to LESS (e.g with Ctrl-C)
```
SYSTEMD_LESS="FRSXM" journalctl
# Send SHIFT+F
# Once you see Waiting for data (interrupt to abort) send CTRL-C
# journalctl stays open, stops "following" the file
```

### In case of bug report: Unexpected behaviour you saw

> Journalctl is killed on interrupt even after passing -K to less using SYSTEMD_LESS

### In case of bug report: Steps to reproduce the problem
```
SYSTEMD_LESS="FRSXM" journalctl
# Send SHIFT+F
# Once you see Waiting for data (interrupt to abort) send CTRL-C
# journalctl is kill
```

**Comment by kgreav** [comment]
see also https://serverfault.com/questions/746909/journalctl-stop-following-without-exiting-pager
and https://gist.github.com/chriskuehl/9ab4c74c19f2f4cb883744171335ac44 for a hacky workaround...

**Comment by poettering** [comment]
not sure i follow. Normally when you hit ^C this is delivered to all processes of the foreground process group. And that's both journalctl and less. Are you suggesting journalctl should actively ignore SIGINT in that case?

**Comment by kgreav** [comment]
Yes. Really just want to be able to use less (through journalctl) like it was intended. There are things you can do in less that require an interrupt to stop (follow, or say cancel things like calculating line numbers), that you just can't do in journalctl because ^C doesn't behave the same.
