### ISSUE TITLE
"Programs should perform cleanup and kill themselves with the same signal" - udev doesn't

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6415]
### Submission type

 - Bug report

### systemd version the issue has been seen with

3285baa

### Used distribution

Fedora Linux 26

### In case of bug report: Expected behaviour you didn't see

According to `man system.service`, programs should perform cleanup and kill themselves with the same signal they received.  So we would expect `systemd` programs to do this.

### In case of bug report: Unexpected behaviour you saw

systemd-udev exitted with status 0, when killed with SIGTERM.  This conflicts with the aforementioned `systemd` documentation.

### In case of bug report: Steps to reproduce the problem

```
strace -p $(pgrep systemd-udevd) &
killall systemd-udevd

```
or read https://github.com/systemd/systemd/blob/3285baa/src/udev/udevd.c#L519

---

This is observable, but AFAIK it does not cause any functional defect in udev given the current `systemd-udev.service` unit.

I tested udev and posted this, because I was skeptical _any_ daemon did what the manual says.  After seeing the same thing happen with sshd, and I think apache2, on Debian Stretch.

Because I didn't understand the logic for why systemd accepts exit status 0, as neither indicating failure, nor the service being stopped.  The latter would avoid the issue where an admin issues e.g. `apache2ctl stop`, and doesn't realize that systemd will restart the service.  I see that apache2.service in Debian already has `Restart=on-abort`, however this then means that systemd fails to log when the service exitted.  The time can only be seen in `systemctl status`, which is lost after a reboot.  https://unix.stackexchange.com/questions/379750/how-to-know-exactly-when-a-linux-service-went-inactive

**Comment by smcv** [comment]
> Because I didn't understand the logic for why systemd accepts exit status 0, as neither indicating failure, nor the service being stopped. 

I think this is because in Debian 8, apache2.service had RemainAfterExit=true, which has exactly that effect.

Until recently, apache2.service in Debian was generated from the LSB init script. This was fixed in Debian 9, which uses a native systemd unit.

systemd cannot know whether a LSB init script is meant to be a Type=oneshot, RemainAfterExit=true service (like /etc/init.d/screen-cleanup) or a Type=forking service (like /etc/init.d/apache2); so it has to make some pessimistic assumptions and generate a unit that will work either way, and as a result the units that it generates for LSB init scripts are not great. It cannot do better than this with the information available. If you want to give systemd better information so it can do a better job, then you need to provide a native systemd unit, as the apache2 maintainer did in Debian 9.

**Comment by sourcejedi** [comment]
@smcv side-thread: nope, that's not it.  My apache2 test is on Debian Stretch, which is version 9.  `systemctl cat apache2` shows a nice little native systemd service.

> Because I didn't understand the logic for why systemd accepts exit status 0, as neither indicating failure, nor the service being stopped.

I believe the real reason for this is to support "activated on demand" service daemons, where the daemon also exits after an idle period.  I think this would have been one of the early design goals.  In my mind, the "solution" to this side-thread is to log a `Stopped` message, if and only if the service is not "activated on demand".  (It should also be inhibited if systemd is going to restart the service anyway).

It seems awkward because _dbus_ activation isn't handled inside `systemd`.  I guess you'd have to formalize the `/etc/systemd/system/dbus-*` links.

You could try to detect whether a service is pulled in by a target at boot time, and hence is should not be on-demand.  But that sounds like a hack, that just happens not to be broken by dbus effectively running `systemctl start foo-is-activated-on-demand.service`.  Maybe targets are never on-demand... but I don't think it's correct that a service should be considered on-demand when manually running `systemctl start bar.service`.

**Comment by poettering** [comment]
Hmpf, yeah, we either should drop that bit from the man page or adjust our services to follow this, this is indeed pretty contradictory and deserves fixing.

**Comment by poettering** [comment]
(btw, i am pretty sure not only udevd is affected by this, but most of our daemons)
