### ISSUE TITLE
Uses a relatively short timeout when connecting to D-Bus

### ISSUE THREAD

**Issue by smcv** [systemd/systemd#6418]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234 from upstream, 233 as packaged by Arch Linux

### Used distribution

@hewittc's report was on Arch Linux, but bug seems distro-independent

### Preconditions

* libexpat >= 2.2.1 on an entropy-starved embedded device, such that the kernel random pool takes about 37 seconds to initialize
* https://github.com/libexpat/libexpat/issues/91 and https://bugs.freedesktop.org/show_bug.cgi?id=101858 **not** fixed yet
* systemd starts dbus-daemon about 7 seconds after boot
* dbus-daemon blocks while libexpat calls `getrandom()`, until the random pool is initialized
* About 38 seconds after boot, dbus-daemon wakes up and actually begins to process requests

### Expected behaviour

* pid 1 connects to D-Bus asynchronously, with an arbitrarily long timeout, and eventually succeeds
* logind behaves similarly

### Actual behaviour

* pid 1 times out after about 30 seconds and does not connect to D-Bus
* logind behaves similarly, and exits with error
* When a user logs in, pam_systemd successfully connects to D-Bus (because it has been unblocked now)
* pam_systemd tries to send D-Bus messages to logind
* dbus-daemon cannot signal pid 1 to activate logind, because it is still waiting for pid 1 to connect and take the org.freedesktop.systemd1 well-known name, which will never happen because pid 1 already gave up
* pam_systemd's D-Bus call also times out
* Login takes a long time

**Comment by smcv** [comment]
I intend to address this in dbus-daemon by asking libexpat to not use the CSPRNG (<https://bugs.freedesktop.org/show_bug.cgi?id=101858>), but I think it would be more robust if this failure mode was also mitigated on the systemd side, by using really long timeouts when pid 1 and logind connect to D-Bus. That way, even if dbus-daemon blocks for a relatively long time, the system will eventually reach a functional state, rather than entering a broken state when the timeout is hit.

Other important system services like networkd might benefit from the same treatment.

**Comment by hewittc** [comment]
I observed this behavior with Arch Linux ARM distribution-supplied systemd 233 and self-built 234. Target platforms were the Zedboard and Parallella based on Zynq 7020 SoC with no hardware random source. Kernel used was Analog Devices' fork of Linux 4.6 from https://github.com/analogdevicesinc/linux

**Comment by poettering** [comment]
ouch. And yeah, should be fine to extend the timeout considerably. Patch very welcome.

**Comment by smcv** [comment]
Sorry, I don't have the bandwidth to patch this right now (but I've worked around it in dbus, so it will be less urgent from 1.10.24 onwards).

**Comment by poettering** [comment]
fix waiting in #6813
