### ISSUE TITLE
systemd-resolved does not report the positive validation result (does not respond with AD Bit) on queries with AD-bit set

### ISSUE THREAD

**Issue by cstrotm** [systemd/systemd#6434]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233 

### Used distribution

> Fedora 26

RFC 6840 DNSSEC Implementation Notes, section 5.7, defines the AD-Flag in queries

> 5.7.  Setting the AD Bit on Queries
> 
>   The semantics of the Authentic Data (AD) bit in the query were
>    previously undefined.  Section 4.6 of [RFC4035] instructed resolvers
>    to always clear the AD bit when composing queries.
> 
>    This document defines setting the AD bit in a query as a signal
>    indicating that the requester understands and is interested in the
>    value of the AD bit in the response.  This allows a requester to
>    indicate that it understands the AD bit without also requesting
>    DNSSEC data via the DO bit.

currently, systemd-resolved only validates a DNS(SEC) answers when the DO-Flag has been set in the query. Validation result reporting is not triggered by just sending the AD flag, which is the default in recent versions of "dig".

**Comment by ott** [comment]
So are you suggesting that systemd-resolved treats the DO bit and the AD bit the same or what is the difference?
