### ISSUE TITLE
Regression : systemd-networkd does not get an IPv4 address via DHCP when started at boot

### ISSUE THREAD

**Issue by sbraz** [systemd/systemd#6435]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

Gentoo

### In case of bug report: Expected behaviour you didn't see

systemd-networkd should have obtained an IPv4 address at boot via DHCP

### In case of bug report: Unexpected behaviour you saw

systemd-networkd did not obtain an IPv4 address at boot

### In case of bug report: Steps to reproduce the problem

* Boot the system → nothing happens
* Restart networkd → an IPv4 is obtained

### Additional info ###
The issue was not present with version 233. I believe this is a regression.

Contents of  `/etc/systemd/network/` : just one file `50-dhcp.network` :
```ini
[Match]
Name=en*
 
[Network]
DHCP=yes
```
Boot logs:
```
Jul 23 23:15:43 localhost systemd[1]: Starting Network Service...
Jul 23 23:15:43 localhost systemd-networkd[2060]: Enumeration completed
Jul 23 23:15:43 localhost systemd[1]: Started Network Service.
Jul 23 23:15:43 localhost systemd-networkd[2060]: eth0: Renamed to enp0s31f6
```
After networkd was restarted:
```
Jul 23 23:17:44 localhost systemd[1]: Stopping Network Service...
Jul 23 23:17:44 localhost systemd[1]: Stopped Network Service.
Jul 23 23:17:44 localhost systemd[1]: Starting Network Service...
Jul 23 23:17:44 localhost systemd-networkd[2311]: Enumeration completed
Jul 23 23:17:44 localhost systemd[1]: Started Network Service.
Jul 23 23:17:44 localhost systemd-networkd[2311]: enp0s31f6: IPv6 successfully enabled
Jul 23 23:17:47 localhost systemd-networkd[2311]: enp0s31f6: Gained carrier
Jul 23 23:17:48 localhost systemd-networkd[2311]: enp0s31f6: DHCPv4 address 192.168.1.5/24 via 192.168.1.254
Jul 23 23:17:49 localhost systemd-networkd[2311]: enp0s31f6: Gained IPv6LL
Jul 23 23:17:50 localhost systemd-networkd[2311]: enp0s31f6: Configured
```

**Comment by ghost** [comment]
Same here, on a Gentoo server with sys-apps/systemd-234-r2. At every boot my network interface is down, and I have to manually issue `systemctl restart systemd-networkd` to connect to the internet.

I had to downgrade to sys-apps/systemd-233-r4 in order to avoid this problem.

This is my `/etc/systemd/network/50-wired.network` configuration file:

```
[Match]
Name=enp0s3

[Network]
DHCP=ipv4
```

**Comment by ssahani** [comment]
Not able to reproduce with latest git 
```
systemctl --version
systemd 234
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
```

**Comment by sbraz** [comment]
Maybe it's related to my NIC. I have an Intel adapter with the e1000e driver. What about you, @fturco ?

**Comment by ghost** [comment]
It's a VPS on Vultr. It uses the `virtio_net` kernel module.

```
# lspci | grep Ethernet
00:03.0 Ethernet controller: Red Hat, Inc Virtio network device
```

**Comment by berndf** [comment]
I think I've got the same problem on gentoo with version 234-r2 - e1000e here but I don't think that's the reason. I've filed a bug report:
https://bugs.gentoo.org/show_bug.cgi?id=626146

I saw the message "systemd-networkd[132]: Could not connect to bus: Connection refused" in the logs just before networkd fails. Adding "dbus.service" to "After=" in systemd-networkd.service fixes the problem. Could you try too? I have no idea why gentoo should be special here though...

**Comment by sbraz** [comment]
@berndf I don't have that error in my logs. I pasted all the messages from networkd.
I'll still try the proposed fix.

**Comment by berndf** [comment]
Okay, maybe it's two different things - it seems your systemd-networkd starts "successfully" (at least by status) while here it will fail during boot. Starting it by hand once the system is up works without problems, this is the commonality. I interpreted @fturco to mean that his networkd startup failed too.

**Comment by mutedbytes** [comment]
I am also experiencing this issue, I believe the same as sbraz. I do not have the "Could not connect to bus: Connection refused" message, it seems networkd service starts successfully. After manually restarting systemd-networkd service after boot, network receives DHCP address sucessfully. I am also on Gentoo, with e1000e interface. My config is basically exactly same as fturco, and I started experiencing this problem after update to 234. Adding dbus.service in "After=" does seem to work even thought I'm not getting the dbus error message.

**Comment by yuwata** [comment]
With the latest git snapshot and e1000e driver, I cannot reproduce both problems, and systemd-networkd works fine even if I add `Before=dbus.service`.

**Comment by sbraz** [comment]
I can confirm that making it start after dbus fixes the issue for me. I created a file `/etc/systemd/system/systemd-networkd.service.d/override.conf` which contains:
```ini
[Unit]
After=dbus.service
```
Logs before I added the After= line:
```
Sep 03 17:50:22 localhost systemd-networkd[2138]: Enumeration completed
Sep 03 17:50:22 localhost systemd-networkd[2138]: eth0: Renamed to enp0s31f6
Sep 03 17:50:25 localhost dbus[2196]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Sep 03 17:50:25 localhost dbus[2196]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service not found.
```
Logs after:
```
Sep 03 17:51:34 localhost systemd-networkd[2175]: Enumeration completed
Sep 03 17:51:34 localhost systemd-networkd[2175]: enp0s31f6: IPv6 successfully enabled
Sep 03 17:51:37 localhost systemd-networkd[2175]: enp0s31f6: Gained carrier
Sep 03 17:51:37 localhost dbus[2174]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Sep 03 17:51:37 localhost dbus[2174]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service not found.
Sep 03 17:51:38 localhost systemd-networkd[2175]: enp0s31f6: DHCPv4 address 192.168.1.5/24 via 192.168.1.254
Sep 03 17:51:38 localhost systemd-networkd[2175]: enp0s31f6: Gained IPv6LL
Sep 03 17:51:40 localhost systemd-networkd[2175]: enp0s31f6: Configured
```

I'm not sure what these Avahi-related failures are and if they are relevant to the problem.

**Comment by sbraz** [comment]
I just noticed that now, the "Renamed to" message comes from the kernel and not networkd:
```
Sep 03 17:51:33 localhost kernel: e1000e 0000:00:1f.6 enp0s31f6: renamed from eth0
```

**Comment by ghost** [comment]
I can reproduce this bug with `sys-apps/systemd-235-r1`, too.

**Comment by mutedbytes** [comment]
I am also still seeing this issue on `sys-apps/systemd-235-r1`.

**Comment by ghost** [comment]
It seems I cannot reproduce this problem anymore after upgrading to `=sys-apps/systemd-236`.

**Comment by yuwata** [comment]
OK. Let's close this, as @fturco commented that v236 fixes this issue. If you still find this issue in recent releases, please provide debugging logs and configs. Thank you.
