### ISSUE TITLE
Run a network script on shutdown

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#6437]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

233.75-3

### Used distribution

Archlinux

### In case of bug report: Expected behaviour you didn't see

Ability to send a network request on shutdown

### In case of bug report: Unexpected behaviour you saw

[curl exit code 6 `Couldn't resolve host. The given remote host was not resolved.`](https://gist.github.com/kaihendry/91d4bce024149131e4dce86d93a22e82)

### In case of bug report: Steps to reproduce the problem

https://s.natalian.org/2017-07-24/shut.service.txt and perhaps setup your own bin on https://requestb.in/

**Comment by mbiebl** [comment]
See man systemd.special. If you want to run a script on shutdown which needs to access the network, you should add ```After=network.target```
This will ensure that on shutdown, the service is stopped before the network stack is stopped.

**Comment by mbiebl** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.special.html#network.target :

"
network.target
This unit is supposed to indicate when network functionality is available, but it is only very weakly defined what that is supposed to mean, with one exception: at shutdown, a unit that is ordered after network.target will be stopped before the network — to whatever level it might be set up then — is shut down. It is hence useful when writing service files that require network access on shutdown, which should order themselves after this target, but not pull it in. Also see Running Services After the Network is up for more information. Also see network-online.target described above.

systemd automatically adds dependencies of type After= for this target unit to all SysV init script service units with an LSB header referring to the "$network" facility.
"

**Comment by kaihendry** [comment]
I updated my service as you suggested (I hope):

```
[Unit]
Description=One last thing
After=network.target

[Service]
RemainAfterExit=yes
ExecStop=/usr/bin/curl -X POST -d "downdown=%b" https://requestb.in/13y9rtd1

[Install]
WantedBy=multi-user.target
```
Still I have the same issue:
```
Jul 25 14:25:01 teefour systemd[1]: Stopping One last thing...
Jul 25 14:25:01 teefour curl[24224]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jul 25 14:25:01 teefour curl[24224]:                                  Dload  Upload   Total   Spent    Left  Speed
Jul 25 14:25:01 teefour curl[24224]: [124B blob data]
Jul 25 14:25:01 teefour systemd[1]: shut.service: Control process exited, code=exited status=6
Jul 25 14:25:01 teefour systemd[1]: Stopped One last thing.
Jul 25 14:25:01 teefour systemd[1]: shut.service: Unit entered failed state.
Jul 25 14:25:01 teefour systemd[1]: shut.service: Failed with result 'exit-code'.
-- Reboot --
Jul 25 14:26:56 teefour systemd[1]: Started One last thing.
```

This complexity does make me long for the simpler rc0.d days ...

**Comment by arvidjaar** [comment]
> Control process exited, code=exited status=6

This means `CURLE_COULDNT_RESOLVE_HOST (6)`. It could be that you are using local caching DNS server that is already stopped at this point. If this is indeed the case, you may consider to order your service after `nss-lookup.target`. For quick test you can try using IP directly.

> This complexity does make me long for the simpler rc0.d days

It still had been necessary to order your script against script that stops caching server (assuming you have once). Nothing really changes here.

**Comment by kaihendry** [comment]
I have the same issue with `After=network.target nss-lookup.target` set. :sob:

**Comment by kaihendry** [comment]
Can this bug please be re-opened until a working solution is found? https://s.natalian.org/2017-08-12/shut.service

Same issue upon version 234.11-6

**Comment by Constantin07** [comment]
I'm experiencing the same issue on CoreOS system.
It turns out that the the network service is actually being shut down before the Stop script is executed and not after, no matter what After options are specified ...

```
[Unit]
Description=Data Backup
After=local-fs.target remote-fs.target network-online.target nss-lookup.target
Requires=local-fs.target remote-fs.target network.target
After=some.service
RequiresMountsFor=/data

[Service]
EnvironmentFile=/etc/data.env
ExecStart=/bin/true
ExecStop=/opt/bin/data-backup push $BACKUP_LOCATION

Type=oneshot
Restart=on-failure
TimeoutSec=600

[Install]
WantedBy=multi-user.target
```

It's not clear why this issue has been closed. Can it be re-opened ?

**Comment by mbiebl** [comment]
> I'm experiencing the same issue on Ubuntu system.
> It turns out that the the network service is actually being shut down before the Stop script is executed and not after, no matter what After options are specified ...
> 
> [Unit]
> Description=Data Backup
> After=local-fs.target remote-fs.target network-online.target nss-lookup.target
> Requires=local-fs.target remote-fs.target network.target
> After=some.service
> RequiresMountsFor=/data
> 
> [Service]
> EnvironmentFile=/etc/data.env
> ExecStart=/bin/true
> ExecStop=/opt/bin/data-backup push $BACKUP_LOCATION
> 
> Type=oneshot
> Restart=on-failure
> TimeoutSec=600
> 
> [Install]
> WantedBy=multi-user.target
> It's not clear why this issue has been closed. Can it be re-opened ?

Well, your service file is wrong.

**Comment by Constantin07** [comment]
@mbiebl I tried many combinations and none worked.
Could you please give an example which should work and I will give it a try ?

**Comment by MerlinDMC** [comment]
We're currently trying to test this with the following unit definition:

```
[Unit]
Description=Events
DefaultDependencies=no
Wants=network-online.target
Wants=nss-lookup.target
After=network.target
After=network-online.target
After=nss-lookup.target

[Service]
ExecStart=/usr/bin/curl -XPOST -d "event=startup" https://requestb.in/1nrqfy21
ExecStop=/usr/bin/curl -XPOST -d "event=shutdown" https://requestb.in/1nrqfy21

Type=oneshot
RemainAfterExit=yes
TimeoutSec=2min

[Install]
WantedBy=multi-user.target
```

We see it push out "startup" events but never a "shutdown" event on shutdown, halt, reboot, initiated shutdown via ACPI.

You can take a look at the storage here: https://requestb.in/1nrqfy21?inspect

For easier reproducibility here is the CoreOS ignition config that we're using against the latest stable branch of CoreOS on AWS:

```
{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{"units":[{"name":"event-notification.service","enable":true,"contents":"[Unit]\nDescription=Events\nDefaultDependencies=no\nWants=network-online.target\nWants=nss-lookup.target\nAfter=network.target\nAfter=network-online.target\nAfter=nss-lookup.target\n\n[Service]\nExecStart=/usr/bin/curl -XPOST -d \"event=startup\" https://requestb.in/1nrqfy21\nExecStop=/usr/bin/curl -XPOST -d \"event=shutdown\" https://requestb.in/1nrqfy21\n\nType=oneshot\nRemainAfterExit=yes\nTimeoutSec=2min\n\n[Install]\nWantedBy=multi-user.target\n"}]},"networkd":{},"passwd":{}}
```

@mbiebl It is OK if there is a problem with the unit definition but honestly this seems to be more of a burden than it should be. Can you point us to a solution that will work in this simplified version?

**Comment by mbiebl** [comment]
A simple ```After=network.target``` is sufficient to get the correct ordering, as mentioned in my first reply.
That requires though, that the network configuration system is properly hooked up. Since no details about the network setup have been provided, I can't really help. That said, this is a bug tracker and not a user support forum. Please use the mailing list for that.

**Comment by absop** [comment]
> > I'm experiencing the same issue on Ubuntu system.
> > It turns out that the the network service is actually being shut down before the Stop script is executed and not after, no matter what After options are specified ...
> > [Unit]
> > Description=Data Backup
> > After=local-fs.target remote-fs.target network-online.target nss-lookup.target
> > Requires=local-fs.target remote-fs.target network.target
> > After=some.service
> > RequiresMountsFor=/data
> > [Service]
> > EnvironmentFile=/etc/data.env
> > ExecStart=/bin/true
> > ExecStop=/opt/bin/data-backup push $BACKUP_LOCATION
> > Type=oneshot
> > Restart=on-failure
> > TimeoutSec=600
> > [Install]
> > WantedBy=multi-user.target
> > It's not clear why this issue has been closed. Can it be re-opened ?
> 
> Well, your service file is wrong.

`RequiresMountsFor=/data` does not work, `/data` stills be unmounted before `ExecStop` is executed.
I believe this is a Bug.
