### ISSUE TITLE
networkd: scope for addresses

### ISSUE THREAD

**Issue by mweinelt** [systemd/systemd#6446]
### Submission type

 - Request for enhancement (RFE)

### Description

Allow setting the scope of addresses configured on networks.

### Current Situation
```
[Network]
Addresses=169.254.10.1/30
```

currently results in

```
6: en0.110@en0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:1f:d0:20:a6:04 brd ff:ff:ff:ff:ff:ff
    inet 169.254.100.1/30 brd 169.254.100.3 scope global en0.110
```

### Problem
This makes it eligible for source address selection for routes via that interface, which is undesirable when the addresses are only used as a transfer network.

### Proposal
Add parameter `Scope` to `[Network]` with a value consistent with what iproute2 is offering

```
/sbin/ip addr add 169.254.100.1 dev en0.110 scope link
```
```
% ip addr add help 
[...]
SCOPE-ID := [ host | link | global | NUMBER ]
[...]
```

```
[Network]
Address=169.254.100.1/30
Scope=link
```

with result

```
6: en0.110@en0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:1f:d0:20:a6:04 brd ff:ff:ff:ff:ff:ff
    inet 169.254.100.1/30 brd 169.254.100.3 scope link en0.110
```

**Comment by ssahani** [comment]
It should  be in `[Address]` section.
