### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [systemd/systemd#645]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/systemd/systemd/blob/56bf3853b4aefad31edf8631668446007e2347cb/configure.ac#L33)?

**Comment by falconindy** [comment]
Why would this be useful for software which targets only Linux?

**Comment by elfring** [comment]
Will it become useful to prepare the build scripts for a wider software portability?

**Comment by zonque** [comment]
What kind of portability do you have in mind?

**Comment by elfring** [comment]
Does anybody dare to port components from the systemd software library to more execution environments?

**Comment by zonque** [comment]
If your definition about "more execution environments" refers to other OS than Linux, then no, this is out of scope for the upstream project.
