### ISSUE TITLE
nspawn: `machinectl poweroff` sometimes cannot shut the container down

### ISSUE THREAD

**Issue by LionNatsu** [systemd/systemd#6458]
### Submission type
 - Bug report

### systemd version the issue has been seen with
Container: 234
Host: 232

### Expected behaviour you didn't see
`machinectl poweroff <CONTAINER>` could do the exact thing as `systemctl poweroff` doing

### Unexpected behaviour you saw
Sometimes, some services on container stopped, but the process of shutting down seems... *reversed*, when it came to swap.target or umount.target.

(14:52:31, I launched `machinectl poweroff ciel`)
![screenshot_20170726-161116](https://user-images.githubusercontent.com/6694582/28620478-ab83b81e-723f-11e7-9483-41b7ab1ec967.png)

Eventually, systemd-networkd.service failed, retried some times and dead because there was no D-Bus at that time.

### Steps to reproduce the problem
We are maintaining a building and packaging server which is using systemd-nspawn as our container system. I am not sure how to reproduce it, because it reproduces "sometimes". But I do know how to *stop from reproducing it*: I changed the code of my container manager, from
```
exec.Command("machinectl", "poweroff", Name)
```
to
```
exec.Command("machinectl", "shell", Name, "/bin/systemctl", "poweroff")
```
The issue has disappered since then.

### Reference

> https://www.freedesktop.org/software/systemd/man/systemctl#poweroff
> #### systemctl poweroff
> Shut down and power-off the system. This is mostly equivalent to **start poweroff.target --job-mode=replace-irreversibly**, but also prints a wall message to all users.

> https://www.freedesktop.org/software/systemd/man/machinectl#poweroff%20NAME%E2%80%A6
> #### machinectl poweroff
> Power off one or more containers. This will trigger a reboot by sending SIGRTMIN+4 to the container's init process, which causes systemd-compatible init systems to shut down cleanly.

> https://www.freedesktop.org/software/systemd/man/systemd.html#SIGRTMIN+4
> #### systemd, Signals, SIGRTMIN+4
> Powers off the machine, starts the poweroff.target unit. This is mostly equivalent to **systemctl start poweroff.target**.

Is `--job-mode=replace-irreversibly` the difference?

**Comment by LionNatsu** [comment]
Another example:
https://ja.pastebin.ca/3846954 (full journal)

**Comment by poettering** [comment]
@LionNatsu any chance you can reproduce the output like the last one you provided, but on a container you started with "debug" on the container command line? That way we should be able figure out exactly why the shutdown logic ends up being reversed eventually.

**Comment by poettering** [comment]
Closing due to lack of response.
