### ISSUE TITLE
TEST-01-BASIC fails to boot due to missing init

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#6474]
Since few days ago, CI has failed the "upstream" test on a rather obvious breakage:

```
TEST RUN: Basic systemd setup
+ /usr/bin/qemu-system-x86_64 -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.4.0-87-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.DO8gVm/rootdisk.img -initrd /boot/initrd.img-4.4.0-87-generic -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0   '
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Loading, please wait...
starting version 234
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... Scanning for Btrfs filesystems
done.
Warning: fsck not present, so skipping root file system
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... done.
run-init: /lib/systemd/systemd: No such file or directory
Target filesystem doesn't have requested /lib/systemd/systemd.
run-init: /sbin/init: No such file or directory
run-init: /etc/init: No such file or directory
run-init: /bin/init: No such file or directory
```

[example log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20170727_194513_78db4@/log.gz)

Marking critical as this severely impedes landing other PRs due to breaking CI.

**Comment by keszybz** [comment]
Do you know if this is a bug in the CI scripts or systemd's test/ itself?

**Comment by martinpitt** [comment]
It's an upstream regression. Just take a built tree and run `sudo make -C test/TEST-01-BASIC/ clean setup run`. I'll start bisecting now.

**Comment by martinpitt** [comment]
Just keeping notes; sorry, they are not very useful.

On Fedora when building in mock I get a very similar error in "journalctl" in the hanging initrd:
```
Jul 28 09:33:51 donald systemctl[240]: Failed to switch root: Could not resolve init executable /usr/lib/systemd/systemd: No such file or directory
```
And yet
```
:/# ls -l /usr/lib/systemd/systemd
-rwxr-xr-x 1 root 0 1183248 Jun 22 13:38 /usr/lib/systemd/systemd
```

This is apparently older already. I rewound back to commit 209f4b9e33a79e648d which moved the upstream tests to meson. And yet a later PR (#6411) succeeded just fine.

Earlier commits than 209f4b9e33a79e648d don't work well with meson (running the QEMU tests fails), so bisecting from an earlier point is not very useful.  A lot of PRs in between were merged without waiting for CI or failling tests, so archeology is not very fruitful. Right now it still smells like some odd fallout from the meson switch.

**Comment by martinpitt** [comment]
I was confused - /usr/lib/systemd/systemd is the initrd's systemd. There is no trace of systemd (init or otherwise) in `/sysroot`, so `setup` just plainly forgets to actually install systemd into the root fs. This can actually be seen in the log output of `setup`, there are only bash, pam, blkid etc., but not systemd.

**Comment by martinpitt** [comment]
Some issues:
 * upstream tests now rely on setting `$BUILD_DIR`. `setup` silently succeeds without it (and just not installing systemd then), causing this issue.
 * Other failures (such as ninja not being present or `$BUILD_DIR` being relative) are also silently ignored; looks like there's a good deal of `set -e` missing here. I'll look into that after fixing the first issue.

**Comment by martinpitt** [comment]
The autopkgtest CI failure was not quite due to the missing `$BUILD_DIR`, as that installs the built .debs instead of running `ninja install`. But the seddery for replacing that was expecting `make`, so I 
[generalized that](https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=43566b4f) to work for both 234 and master. I re-ran the tests in #6464. Once they succeed (or at least stop showing *this* bug), I'll close this.

**Comment by martinpitt** [comment]
That did the trick, the tests now work again ([i386 log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20170728_113141_18db5@/log.gz), [amd64 log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20170728_142249_18db5@/log.gz)).

I filed PR #6475 to make the tests more robust and fail more meaningfully.
