### ISSUE TITLE
`systemd` fails to boot with "Cannot determine cgroup we are running in: No medium found" when `tmpfs` is mounted onto `/sys/fs/cgroup/systemd`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#6477]
`systemd` has started failing to boot inside [some containers](https://github.com/lxc/lxc/issues/1669) since https://github.com/systemd/systemd/commit/2977724b09eb997fc8#diff-0d48d4d5663167a0bb6786a4abaddc35L2257 was merged.

Here is a simplified way to reproduce the issue:
```sh
bash-4.3# /usr/lib/systemd/systemd --version
systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
bash-4.3# mount -t sysfs sysfs /sys
bash-4.3# mount -t proc proc /proc/
bash-4.3# mount -t tmpfs tmpfs /sys/fs/cgroup/
bash-4.3# mkdir /sys/fs/cgroup/systemd
bash-4.3# mount -t tmpfs tmpfs /sys/fs/cgroup/systemd
bash-4.3# mkdir /sys/fs/cgroup/systemd/lxc
bash-4.3# mount -o remount,rw /
bash-4.3# mkdir /SUB
bash-4.3# mount -t cgroup cgroup -o none,name=systemd /SUB
bash-4.3# mkdir /SUB/lxc
bash-4.3# echo 1 >/SUB/lxc/cgroup.procs
bash-4.3# mount --bind /SUB/lxc /sys/fs/cgroup/systemd/lxc
bash-4.3# cat /proc/self/cgroup
1:name=systemd:/lxc
bash-4.3# exec /usr/lib/systemd/systemd

Welcome to Ubuntu 16.04!

[  161.003113] systemd[1]: Failed to allocate manager object: No medium found
[!!!!!!] Failed to allocate manager object, freezing.
[  161.006041] systemd[1]: Freezing execution.
```

**Comment by evverx** [comment]
I forgot to mention that this affects kernels that don't support `cgroup2`.

**Comment by graysky2** [comment]
Let me know if there is anything test you want me to with it... ie edit an lxc file to do that manual mount step you mentioned or the like.

**Comment by evverx** [comment]
> I forgot to mention that this affects kernels that don't support cgroup2.

That's correct when `-Ddefault-hierarchy=hybrid` is used. `-Ddefault-hierarchy=legacy` or `systemd.unified_cgroup_hierarchy=no systemd.legacy_systemd_cgroup_controller=yes` can be used to reproduce the issue everywhere.

**Comment by evverx** [comment]
It seems that the following patch might be used to restore the old behaviour:
```diff
diff --git a/src/basic/cgroup-util.c b/src/basic/cgroup-util.c
index 5dea078..d480a9f 100644
--- a/src/basic/cgroup-util.c
+++ b/src/basic/cgroup-util.c
@@ -2415,16 +2415,14 @@ static int cg_unified_update(void) {
                     F_TYPE_EQUAL(fs.f_type, CGROUP2_SUPER_MAGIC)) {
                         unified_cache = CGROUP_UNIFIED_SYSTEMD;
                         unified_systemd_v232 = false;
-                } else if (statfs("/sys/fs/cgroup/systemd/", &fs) == 0 &&
-                           F_TYPE_EQUAL(fs.f_type, CGROUP2_SUPER_MAGIC)) {
-                        unified_cache = CGROUP_UNIFIED_SYSTEMD;
-                        unified_systemd_v232 = true;
                 } else {
                         if (statfs("/sys/fs/cgroup/systemd/", &fs) < 0)
                                 return -errno;
-                        if (!F_TYPE_EQUAL(fs.f_type, CGROUP_SUPER_MAGIC))
-                                return -ENOMEDIUM;
-                        unified_cache = CGROUP_UNIFIED_NONE;
+                        if (F_TYPE_EQUAL(fs.f_type, CGROUP2_SUPER_MAGIC)) {
+                                unified_cache = CGROUP_UNIFIED_SYSTEMD;
+                                unified_systemd_v232 = true;
+                        } else
+                                unified_cache = CGROUP_UNIFIED_NONE;
                 }
         } else
                 return -ENOMEDIUM;
```
.

**Comment by evverx** [comment]
By the way, the code above is incorrect as well as the code that was changed in https://github.com/systemd/systemd/commit/2977724b09eb997fc8#diff-0d48d4d5663167a0bb6786a4abaddc35L2257, because `cgroup2` can be premounted instead of `cgroup`. But, fortunately, nobody seems to use `cgroup2` without cgroup namespaces.

**Comment by graysky2** [comment]
> It seems that the following patch might be used to restore the old behaviour:

Would you like me to build the Arch ARM systemd package using this patch to test?  I now have an SD Card with the "stable" kernel for testing.

EDIT: I built systemd with the included patch on my ODROID-C2.  After updating both the host and lxc running the current stable kernel package (3.14.79-27-ARCH), everything again works as expected.  WIthout the patch, one cannot use lxc at all on this hardware.  See: https://github.com/lxc/lxc/issues/1669

**Comment by TristanCP** [comment]
Is it still in progress ?

**Comment by evverx** [comment]
I suppose the patch above is good enough for the time being, so I could send a PR. The other issues I mentioned can be fixed later. @poettering, is there any chance you could say what you think of it?

**Comment by poettering** [comment]
@evverx patch looks OK to me
