### ISSUE TITLE
systemctl's fallback function talk_initctl() doesn't work for runlevel 0 (shutdown)

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6482]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v234+git-9fcaa574

https://github.com/systemd/systemd/blob/9fcaa574f07c3159281584643b573a80b5c1a843/src/systemctl/systemctl.c#L8156

### Used distribution

Fedora 26

### In case of bug report: Steps to reproduce the problem

I saw two weird things about this code.

1. Actions omitted from the table in `action_to_runlevel()` will default to runlevel 0 (system shutdown).  Both ACTION_DEFAULT and ACTION_EMERGENCY can be directed to this function, and are not in the table.
2. When `action_to_runlevel()` returns runlevel 0 (system shutdown), `talk_initctl()` treats this as a failure.  

The result of the current code is that `talk_initctl()` can send requests for reboot, single user, multi-user or graphical runlevels, but not the runlevel for shutdown.

Replacing the table with a switch/case statement with a `default` would work, but might be a bit verbose.  Another way to write the table would be as a list of (action, runlevel) pairs, which you can iterate through.

**Comment by poettering** [comment]
ouch! the problem i figure is that this code is little used these days, hence bugs lurk forever.

**Comment by sourcejedi** [comment]
From the PR (#6632):

> Hmm, reading this issue again, I am a bit confused... Note that action_to_runlevel() returns '0' for ACTION_HALT and ACTION_POWEROFF, but 0 for unknown actions. '0' equals 48 (since the zero character has ASCII code 48), hence both cases are fully distinguishable.

You're right, I was wrong.  As you said, the code is a bit obscure to access.  Whatever testing I did do, I hadn't justified the PR.
