### ISSUE TITLE
4 or 5 out of 7 targets triggered by SIGRTMIN+X use the wrong job mode

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6484]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v234-git-01a45898f

https://github.com/systemd/systemd/blob/01a45898fce8def67d51332bccc410eb1e8710e7/src/core/manager.c#L2127

### Bug report

1. The correct mode for starting shutdown-type targets is `replace-irreversably`, to guarantee shutdown is not interrupted by the activation of a unit with a conflict.  This is used by `systemctl reboot`, `/dev/initctl`, etc.  But when shutdown targets are triggered by SIGRTMIN+X, the job mode `replace` is used instead.
2. Usually the correct mode for starting runlevel-like targets is `isolate`, to make sure services which don't belong to the target are shut down.  But for `default.target`, job mode `replace` is being used instead.  This differs from the other runlevel-like targets: `rescue.target` and `emergency.target`.  The difference is technically documented in `man systemd`, but no reason is given in either the doc or the code.  If I take time to think about it, I can see that using `start default.target` will most often not cause a problem.  But I can't think of an explanation to add, that would avoid making the reader think about it in the first place.

It might be slightly clearer to move the job mode into `target_table[]` at the same time, similar to `systemctl.c` or `initctl.c`.  Particularly if we needed DEFAULT_TARGET to keep using mode `replace`, and it would make that easier to comment as well.

                        /* Starting SIGRTMIN+0 */
                        static const char * const target_table[] = {
                                [0] = SPECIAL_DEFAULT_TARGET,
                                [1] = SPECIAL_RESCUE_TARGET,
                                [2] = SPECIAL_EMERGENCY_TARGET,
                                [3] = SPECIAL_HALT_TARGET,
                                [4] = SPECIAL_POWEROFF_TARGET,
                                [5] = SPECIAL_REBOOT_TARGET,
                                [6] = SPECIAL_KEXEC_TARGET
                        };

                        /* Starting SIGRTMIN+13, so that target halt and system halt are 10 apart */
                        static const ManagerExitCode code_table[] = {
                                [0] = MANAGER_HALT,
                                [1] = MANAGER_POWEROFF,
                                [2] = MANAGER_REBOOT,
                                [3] = MANAGER_KEXEC
                        };

                        if ((int) sfsi.ssi_signo >= SIGRTMIN+0 &&
                            (int) sfsi.ssi_signo < SIGRTMIN+(int) ELEMENTSOF(target_table)) {
                                int idx = (int) sfsi.ssi_signo - SIGRTMIN;
                                manager_start_target(m, target_table[idx],
    (idx == 1 || idx == 2) ? JOB_ISOLATE : JOB_REPLACE);

**Comment by poettering** [comment]
ouch.

**Comment by fsateler** [comment]
> But for default.target, job mode replace is being used instead. This differs from the other runlevel-like targets: rescue.target and emergency.target. The difference is technically documented in man systemd, but no reason is given in either the doc or the code. If I take time to think about it, I can see that using start default.target will most often not cause a problem. But I can't think of an explanation to add, that would avoid making the reader think about it in the first place.

I think the rationale would be that for `default.target` you want to run a fully functional system. This means you do not want to stop targets (and their related units) that may have been started via hardware discovery, like `bluetooth.target` or `sound.target`.

**Comment by poettering** [comment]
Fix waiting in #6590.
