### ISSUE TITLE
machinectl shell breaks the current TTY session

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#6485]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233 +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

When I invoke `machinectl shell <containername>` and I shut down the container after doing my work with `machinectl stop <containername>` I should be able to use my window manager (i3) normally.

### In case of bug report: Unexpected behaviour you saw

When I invoke `machinectl shell <containername>` and I try to switch some workspaces via i3 with `mod4+<left arrow-key>` or `mod4+<right arrow-key>` this will open a new TTY and seem to have the same effect like doing a `CTRL+ALT+F<1..12>`. 

### In case of bug report: Steps to reproduce the problem

Install an application that uses `mod4` as shortcut for invoking application specific actions and trigger `machinectl shell <containername>`

**Comment by poettering** [comment]
uh, what? are you saying that machinectl interacts with your X11 server and takes away the i3 key grab for "mod4"? machinectl really can't do such things, it doesn't do X11, it only allocates a pty in the container and propagates input/output between that pty and the terminal you invoked it on...

SOmething very fishy must be going on there, and I have no real idea what might be going on here... Are you sure it's really the "machinectl shell" triggreing this?

**Comment by mbiebl** [comment]
Not sure if this downstream bug report might be related/helpful:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867745

**Comment by shibumi** [comment]
@poettering 
I observed this a while now. Seems like it has something todo with `machinectl shell`. Sometimes I can trigger that and sometimes not. I am pretty sure it's `machinectl shell` that triggers this issue. Do you have any idea how I can debug this?

I guess it has nothing todo with i3 and even without i3 I would have the same behaviour when I press `mod4+left` or `mod4+right` (mod4 == 'windows' key)

**Comment by shibumi** [comment]
Hello,
I still have this issue. It happens everytime when I do things with `machinectl`. So Stuff like `machinectl login` or `machinectl shell`.

It's really annoying. Do you know any way to debug this?! I need to restart the whole X-Server to fix this issue.

**Comment by poettering** [comment]
are you starting x with "startx" on a different console than where you logged in? That's not supported in logind's model, i.e. device access is taken away for sessions that are not in the foreground. You can only upgrade your current loging to graphical, staying on the same VT.

is this still an issue?

**Comment by poettering** [comment]
let's close this, due to lack of response, and under the assumption this is not an issue anymore. reopen if this still an issue...
