### ISSUE TITLE
process-util: memory corruption in process renaming

### ISSUE THREAD

**Issue by joukewitteveen** [systemd/systemd#6492]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> at least 233 and 234

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> The process responsible for PAM management is renamed to "(sd-pam)".

### In case of bug report: Unexpected behaviour you saw

> The process name is corrupted to "(sd-pam)TERM=linux" or variations such as "(sd-pamTERM=linux)").

### In case of bug report: Steps to reproduce the problem

    [Unit]
    Description=Testcase for PAM
    
    [Service]
    ExecStart=/bin/sleep infinity
    User=nobody
    PAMName=login

```
$ systemd-cgls
Control group /:
-.slice
├─user.slice
│ ├─user-99.slice
│ │ ├─user@99.service
│ │ │ └─init.scope
│ │ │   ├─1167 /usr/lib/systemd/systemd --user
│ │ │   └─1168 (sd-pam)
│ │ └─session-c6.scope
│ │   ├─1166 /bin/sleep infinity
│ │   └─1173 (sd-pam)TERM=linux
…
```

**Comment by poettering** [comment]
Hmm, any chance you can check the precise contents of /proc/$PID/cmdline of the offending process? I.e. hexdump -C or so?

**Comment by joukewitteveen** [comment]
Nothing unusual there (only printable characters):
```
$ hexdump -C /proc/1173/cmdline 
00000000  28 73 64 2d 70 61 6d 29  54 45 52 4d 3d 6c 69 6e  |(sd-pam)TERM=lin|
00000010  75 78                                             |ux|
00000012
```

**Comment by poettering** [comment]
hmm, there must be something wrong with the PR_SET_MM_ARG_START code in rename_process(), but I am not sure I grok what precisely.

I see one bug in that function though, but I fail to see how it could become visible the way you are seeing it: if rename_process() is called multiple times in a row, we don't update PR_SET_MM_ARG_END properly for any but the first call...

**Comment by joukewitteveen** [comment]
I can't say that I do see why this bug (not updating the end pointer) explains what I am seeing, but fixing the bug makes the issue go away :-).

**Comment by evverx** [comment]
`exec_child` calls `rename_process_from_path` and then it calls `setup_pam`, which creates a child and renames it to `(sd-pam)`. That seems to lead to the issue because `mm` is a static variable pointing to a memory mapping which is inherited across a fork.
