### ISSUE TITLE
networkd: wait for DAD to complete before an address is considered configured

### ISSUE THREAD

**Issue by atomt** [systemd/systemd#650]
systemd-networkd-wait-online.service should wait for IPv6 DAD (Duplicate Address Detection) to complete if DAD is enabled on a address (it is by default)

The kernel do not allow processes to bind to specific IPv6 addresses until DAD for them has completed, making daemons like apache, unbound and sshd to fail on boot if they're set to bind to something different than ::

**Comment by poettering** [comment]
@atomt Any idea how precisely that's indicated by the kernel? i.e. which rtnl option to check for? How is this state visible in the "ip" tool output?

**Comment by bjoe2k4** [comment]
i.e.
`ip -6 addr show dev eth0 scope global tentative`

**Comment by poettering** [comment]
So you are saying that the IFA_F_TENTATIVE flag is what is covered by IPv6 DAD?

If so: when determining the connectivity state we iterate through all IP addresses, and determine their scopes, figuring out the IP address with the "most global" scope. While doing this we skip over addresses with the tentative flag set, ignoring them completely:

https://github.com/systemd/systemd/blob/master/src/network/networkd-link.c#L2151

In other words: if s-n-w-o.s returned early that's an indication that you had at least one IP address assigned with a global enough state. If there are multiple addresses to be assigned, it won't care about the tentative state of any of them, if the is at least one non-tentative one with a scope high enough. 

@atomt do you have multiple IP addresses on that interface? For example, both an IPv4 and an IPv6 address? If so, the IPv4 address (where DAD does not exist) is sufficient to consider the interface routable.

Now, I am pretty sure the current operstate logic is right the way it is. However, for the usecase in s-n-w-o.s we probably want more than just the operstate: i.e. a boolean that indicates if there's currently an operation in progress that tries to get the link into a higher operstate, for example by doing DAD, or by doing DHCP or IPv4LL. @teg, any opinion on this?

**Comment by atomt** [comment]
@poettering Yup, the interface has one IPv4 address and two IPv6 addresses, plus the usual IPv6 Link Local. They are all static, no DHCP/SLAAC.

ifupdown on Debian/Ubuntu waits for up to 6 seconds while for DAD to complete for IPv6. Their implementation is just some shell goop looping ip addr ls though.

**Comment by teg** [comment]
Hm, so the logic is that we do wait for operations in progress _as indicated by networkd_. wait-online has no clue about stuff being in progress (DHCP/...) except for what networkd tells it. That means we will wait for an address with the right scope as @poettering pointed out, but to get things working properly we need to wait for networkd to indicate that a link is ready (which in most cases it already does correctly). However, you are right that in the case of IPv6, networkd will consider the address configured even though it is still in the TENTATIVE state, which is wrong. So the fix here is to improve the address tracking in networkd.

Aside: We could actually have made wait-online wait for DAD even though someone else than networkd has triggered it (as the kernel exposes this information through the TENTATIVE flag), but I think that would be inconsistent as all other such operations (DHCP/ND/IPv4LL as well as ACD, the IPv4 equivalent to DAD) are unknown to the kernel so those could never work without proper userspace integration.
