### ISSUE TITLE
Debian's ifup@.service fights with openvswitch for lifecycle ownership of devices

### ISSUE THREAD

**Issue by shettyg** [systemd/systemd#6507]
### Submission type

 - Bug report
 

### systemd version the issue has been seen with

> 233+upstream20170510-0.master

The above was installed from 
https://launchpad.net/~pitti/+archive/ubuntu/systemd

> The behavior is seen in systemd versions 229 as well as 232.

### Used distribution

> ubuntu zesty

### In case of bug report: Expected behaviour you didn't see

> ....

In my case, I create openvswitch virtual network devices via "/etc/network/interfaces" of ubuntu. A typical simply configuration looks like this:

```
auto br0
allow-ovs br0
iface br0 inet static
    address 192.168.1.1
    netmask 255.255.255.0
    ovs_type OVSBridge
```
When the system boots up the network device openvswitch bridge "br0" gets created. Or you can just run "ifup br0" and the device gets created.

Now, if I delete the bridge and re-create it without much gap in-between the separate events (i.e create and delete) with a mechanism different than "ifupdown" (e.g: ovs-vsctl del-br br0; ovs-vsctl add-br br0), systemd comes in and deletes the bridge (even-though it was re-created).  This is because of a race condition and a likely bug in systemd. My theory is the following.

1. When we run 'ovs-vsctl del-br br0', OVS deletes the bridge.

Relevant log from syslog
```
Aug  1 22:02:25 k8smaster ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl del-br br0
Aug  1 22:02:25 k8smaster kernel: [ 1043.906064] device br0 left promiscuous mode
Aug  1 22:02:25 k8smaster systemd[1]: Stopping ifup for br0...
```

2. When we run 'ovs-vsctl add-br br0', OVS re-creates the bridge

Relevant log from syslog
```
Aug  1 22:02:25 k8smaster ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl add-br br0
Aug  1 22:02:25 k8smaster kernel: [ 1043.967873] device br0 entered promiscuous mode
Aug  1 22:02:25 k8smaster systemd[1]: Found device /sys/subsystem/net/devices/br0.
```

3. Since systemd had gotten a notification that the bridge has disappeared, it runs "ifdown br0".

The bridge gets deleted because of this.

4. systemd now gets a notification that "br0" has re-appeared. So it tries to run "ifup br0".

Relevant log from syslog
```
Aug  1 22:02:25 k8smaster systemd[1]: ifup@br0.service: Bound to unit sys-subsystem-net-devices-br0.device, but unit isn't active.
Aug  1 22:02:25 k8smaster systemd[1]: Dependency failed for ifup for br0.
Aug  1 22:02:25 k8smaster systemd[1]: ifup@br0.service: Job ifup@br0.service/start failed with result 'dependency'.
```

5. But for whatever reason, it decides against completing "ifup br0" and cancels it. (May be the above log helps you and gives a hint?)

6. End result is that we have a disappeared "br0".

### In case of bug report: Steps to reproduce the problem

> Reproduction steps mentioned above.

**Comment by poettering** [comment]
ifup@.service is not a systemd thing, that's a Debian thing. And it sounds very broken if two asynchronous components both race for deleting the same interface. I am not sure what to suggest to you, except that having two components fight asynchronously for the same resources can only fail, in particular if one causes notification of the other, and they are thus interlocked...

I doubt we can help you with this upstream. Please contact the Debian folks...

**Comment by shettyg** [comment]
Thank you for the comment. I will try and read more about ifup@.service. I am  closing this as you think this has nothing to do with systemd. If I find something new, I will re-open it.
