### ISSUE TITLE
Failed to get properties: Connection reset by peer

### ISSUE THREAD

**Issue by ileGITimo** [systemd/systemd#6517]
### Submission type
 - Request for enhancement (RFE)
### systemd version the issue has been seen with
systemd-233-6.fc26.x86_64
### Used distribution
Feddora 26
### In case of bug report: Unexpected behaviour you saw
This is what I get in two of my F26 systems:
  % systemctl --no-pager --user status dbus.service
  Failed to get properties: Connection reset by peer
which gives me no clue where to look.
Google search is quite ambiguous

**Comment by poettering** [comment]
Is there anything in the logs about this?

**Comment by ileGITimo** [comment]
Looking at "journalctl -b 0 -f"  while I issue '--user status dbus.service,  nothing comes out in the journal, only the error message above.  I I do only '--user status' I get an additional error message of "Failed to list units: Transport endpoint is not connected"

If I need to clear the "needs-report-feedback" label, I can't seem to find a way to do it ...

**Comment by ileGITimo** [comment]
It's working today, either fixed itself, or some update did it.  Still have the same systemd, but I do update daily.

**Comment by zanglinjie** [comment]
[root@inspur01 ~]# systemctl status ganesha
Failed to get properties: Connection reset by peer
[root@inspur01 ~]# systemctl status vsftpd
Failed to get properties: Connection reset by peer
[root@inspur01 ~]# systemctl status sysmgt-alarm
Failed to get properties: Connection reset by peer



all systemctl is fail，why？Anybody knows？
