### ISSUE TITLE
sd_bus_add_match doesn't check interface existence

### ISSUE THREAD

**Issue by FedeDP** [systemd/systemd#6530]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Archlinux

### In case of bug report: Expected behaviour you didn't see

> I expect that sd_bus_add_match returns -EHOSTUNREACH if any of interface/path/member does not exist

### In case of bug report: Unexpected behaviour you saw

> sd_bus_add_match returns 1 even if it shouldn't (match is added on a not-existent interface)

### In case of bug report: Steps to reproduce the problem

> Uninstall eg: upower, then add a match on it and check sd_bus_add_match return value

I don't know if this fits in as bug report or as feature request. It would be nice to have a proper check there.
Or is there a standard way to check if an interface does exist?

**Comment by boucman** [comment]
I'm not sure I understand... 

you are adding a match on a non-existant busname, and you expect it to fail ?

you are allowed to add a match on a non-existant bus name... that's a very common thing to do. It will allow to match messages when the name-provider arrives.

I'm pretty sure there is another way to figure out if a name exists...

**Comment by FedeDP** [comment]
Ah thanks I now understand.
I thought that an error code should have been provided anyway, to let dev know that match was added on a not-existent busname. But i jumped the "that's a very common thing to do".

Thank you very much!
