### ISSUE TITLE
Mount unit with 'bind' type does not remounted on parent remount

### ISSUE THREAD

**Issue by av1024** [systemd/systemd#6542]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 229

### Used distribution

> Linux Mint 18.1 (Ubuntu 16.04.2)

### In case of bug report: Expected behaviour you didn't see

> remount bind mounts from (USB) HDD folders to bind points under root after HDD mounted

### In case of bug report: Unexpected behaviour you saw

> The HDD remounted, but bind mounts still unmounted up to manual restart. The bind.automount unit changed to 'Unset' state when parent device unmounted and does not restored automatically. Neither via fstab nor via mount/automount units

### In case of bug report: Steps to reproduce the problem

> 
 * Create mount and automount units from 'real' disk partition to /mnt/hdd. With IdleTimeoutSec option as an example
 * Create mount and automount units for bind /mnt/hdd/folder-1 to /mnt/bind_a (I tried to set Whants/BindsTo/PartOf as part of mount and/or automount without success)
* Install/start automount units
* run `ls /mnt/bind_a` - look at non-empty result
* wait for /mnt/hdd auto-unmounted or restart mnt-hdd.mount
* run systemctl status mnt-bind_a.automount: .automount status will change to `inactive(dead)`:
```
Aug 02 23:54:24 x240 systemd[1]: Set up automount Test bind 1 auto.
Aug 02 23:54:33 x240 systemd[1]: mnt-bind_a.automount: Got automount request for /mnt/bind_a, triggered by 24597 (mc)
Aug 02 23:55:45 x240 systemd[1]: Unset automount Test bind 1 auto.
```
```
#mnt-win.mount
[Unit]
Description=Win7 mount

[Mount]
What=/dev/disk/by-label/Windows7_OS
Where=/mnt/win

[Install]
WantedBy=multi-user.target
```
```
#mnt-win.automount
[Unit]
Description=Win7 mount auto
Requires=local-fs.target

[Automount]
Where=/mnt/win
TimeoutIdleSec=60

[Install]
WantedBy=multi-user.target
```
```
#mnt-bind_a.mount
[Unit]
Description=Test bind 1
#BindsTo=mnt-win.mount
#After=mnt-win.mount
#PartOf=mnt-win.mount

[Mount]
What=/mnt/win/Intel
Where=/mnt/bind_a
Options=bind
Type=none

[Install]
WantedBy=multi-user.target
```
```
#mnt-bind_a.automount
[Unit]
Description=Test bind 1 auto
#BindsTo=mnt-win.mount
#Wants=mnt-win.mount
After=mnt-win.mount
PartOf=mnt-win.mount

[Automount]
Where=/mnt/bind_a

[Install]
WantedBy=multi-user.target
```

**Comment by poettering** [comment]
I am sorry, I don't understand what you are trying to say? Can you explain this again, in the simplest and most generic form possible?

**Comment by av1024** [comment]
Ok.
I have external HDD mounted to /mnt/sda
And several folders, for example /opt/oh, /home, ..., bound to on /mnt/sda/oh, /mnt/sda/home, etc.
The /mnt/sda may be remounted if power failure occurs

I need (re-)mount /opt/oh after /mnt/sda (re-)mounted OR corresponding /opt/oh folder accessed (like autofs)

Issue: The /opt/oh mounted only once at reboot, but never remounted automatically if /mnt/sda remounted

**Comment by poettering** [comment]
please note that bind mounts after they have been made are entirely independent entry points to the same file system than the original mount used to create them. This means, after creating /opt/oh as bind mounts the fact that /mnt/sda is on an automount point is entirely irrelevant for its lifecycle: the new bind mounts point directly to the effective file system, they lose any automount magic. And that's a kernel design choice and is nothing systemd can do anything about it.

Sorry, but systemd can't do what you want to do, because the kernel simply doesn't work that way!

sorry!
