### ISSUE TITLE
systemd-resolved fails to resolve PTR records when link with no gateway exists

### ISSUE THREAD

**Issue by tohojo** [systemd/systemd#6543]
### Submission type
 - Bug report

### systemd version the issue has been seen with

> 234 (Arch pkg ver 234.11-4)

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Querying for a PTR record that does not exist should return an empty (successful) response

### In case of bug report: Unexpected behaviour you saw

> The query returns SERVFAIL and I get a log line like this in the system log:
> `systemd-resolved[27922]: Failed to synthesize gateway hostname PTR RR: No data available`

### In case of bug report: Steps to reproduce the problem

> I have two network devices on the machine, one of which has UseRoutes=false in the [DHCP] section of its .network file. When this device is plugged in, I get the behaviour described above. When I unplug the device, I get the expected reply.

**Comment by poettering** [comment]
Proposed fix waiting in #6946.
