### ISSUE TITLE
journal-remote: ifdef MHD_USE_PEDANTIC_CHECKS looks wrong

### ISSUE THREAD

**Issue by benjarobin** [systemd/systemd#6547]
### Submission type

 - Bug report

### systemd version the issue has been seen with
Git version 010585873454d07625ee962ffa2ef2823624bfbe

### Code review of journal-remote.c

See comment:
https://github.com/systemd/systemd/commit/010585873454d07625ee962ffa2ef2823624bfbe#commitcomment-23503458

Pull request https://github.com/systemd/systemd/pull/6472 of @yuwata

**Comment by yuwata** [comment]
No. I think the code is correct. Please read my reply in #6472.

**Comment by benjarobin** [comment]
I was wrong, see comments... Sorry for the noise
