### ISSUE TITLE
gvariant: unary type is wrongly encoded as empty sequence

### ISSUE THREAD

**Issue by dvdhrm** [systemd/systemd#655]
The unary type `()` is a valid gvariant type (but invalid dbus1 type). According to the spec, it's encoded as 1 byte (padding). However, we encode it as empty sequence (0 bytes). This is wrong and needs to be fixed.

The reason it's encoded as 1 byte is to guarantee that no fixed-size type has a 0 byte encoding (which would violate gvariant requirements).

**Comment by poettering** [comment]
Hmm, should we allow encoding of this at all? I don't see how that could ever be useful...

**Comment by poettering** [comment]
Does our signature validation function even allow that?

**Comment by dvdhrm** [comment]
Fixed by #774.
