### ISSUE TITLE
nspawn: mknod not possible even after enabling it

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#6553]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

openSUSE Tumbleweed 20170730

### In case of bug report: Expected behaviour you didn't see

mknod succeeding.

### In case of bug report: Unexpected behaviour you saw

```
16:21 a4:~ # id
uid=0(root) gid=0(root) groups=0(root)
16:21 a4:~ # mknod blah c 1 1
mknod: blah: Operation not permitted
```

### In case of bug report: Steps to reproduce the problem

```
# cat /etc/systemd/nspawn/a4.nspawn
[Exec]
Boot=on
Capability=CAP_MKNOD

# cat /etc/systemd/system/systemd-nspawn\@a4.service.d/main.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/systemd-nspawn --keep-unit -D /E/machines/a4 -M a4
TasksMax=16384
DeviceAllow=/dev/loop-control
DeviceAllow=/dev/net/tun
DeviceAllow=/dev/fuse

[Install]
WantedBy=multi-user.target

# systemctl start systemd-nspawn@a4
```

**Comment by poettering** [comment]
device node creation is not just controlled via CAP_MKNOD but also via the devices cgroup controller. You need to add DeviceAllow= lines for the relevant device nodes you want to be able to create, and in particular specify "m" for them so that you can actually create the device nodes. Without such whitelisting mknod() is prohibited.

**Comment by nh2** [comment]
For people who pass by in search of making GlusterFS (fuse mounts) works in systemd-nspawn, the correct invocation of `mknod` after setting above `DeviceAllow=/dev/fuse rwm` and `CAP_MKNOD` seems to be `mknod /dev/fuse c 10 229` [as this article shows for gluster](https://archives.flockport.com/build-distributed-storage-nodes-with-lxc-and-gluster/).

Using that, I could successfully mount gluster via fuse.

**Comment by kugel-** [comment]
Hum, with the following .nspawn file (/etc/systemd/nspawn/$name.nspawn) I'm still not able to use mknod inside the container:

```
[Exec]
Boot=yes
Environment=DISPLAY=:0
BindReadOnly=/tmp/.X11-unix
DeviceAllow=/dev/fuse rwm
Capability=CAP_MKNOD
```

What's missing here?

**Comment by bronislav** [comment]
@kugel- `DeviceAllow=/dev/fuse rwm` should go to the service definition not nspawn file

**Comment by kugel-** [comment]
Oh, I don't use a service file but invoke systemd-nspawn directly. Any option here?

**Comment by bronislav** [comment]
Update systemd-nspawn@.service template.

**Comment by bronislav** [comment]
There is some information how to control devise access without systemd.service https://unix.stackexchange.com/a/304253

**Comment by thiagomacieira** [comment]
> How's the template involved when I don't use/start [systemd-nspawn@xxx.service](mailto:systemd-nspawn@xxx.service) at all? Again, I execute systemd-nspawn directly on the command line.

For the record, this is how I managed it. You need to tell systemd-nspawn not to create a new scope and you get that with the {{--keep-unit}} option (so you'll also need {{--register=no}}. This sounds like an abuse, but worked.
```
# systemd-nspawn -M tumbleweed --keep-unit --register=no
Spawning container tumbleweed on /var/lib/machines/tumbleweed.
Press Ctrl-] three times within 1s to kill container.
tumbleweed:~ # mknod /tmp/mem c 1 1
```
