### ISSUE TITLE
Honor OF_COMPATIBLE_* udev event variables

### ISSUE THREAD

**Issue by l1k** [systemd/systemd#6555]
Request for enhancement (RFE), applicable to the latest systemd version (234 as of this writing):

For I2C- and SPI-attached devices, the kernel generates a MODALIAS which looks like "i2c:*name*" or "spi:*name*". Drivers can only be bound to these devices if they declare a `MODULE_DEVICE_TABLE(i2c, ...)` or `MODULE_DEVICE_TABLE(spi, ...)`.

However numerous drivers only declare a `MODULE_DEVICE_TABLE(of, ...)` (OpenFirmware/DeviceTree). One example is <a href="https://github.com/torvalds/linux/blob/master/drivers/gpio/gpio-74x164.c">drivers/gpio/gpio-74x164.c</a>. Such drivers currently cannot be bound automatically to devices if compiled as modules because <a href="https://github.com/systemd/systemd/blob/master/rules/80-drivers.rules">rules/80-drivers.rules</a> only matches drivers to the device based on its `MODALIAS` string, but not based on the `OF_COMPATIBLE_*` strings generated by <a href="https://github.com/torvalds/linux/blob/master/drivers/of/device.c#L304">drivers/of/device.c</a>.

A trivial solution would be to amend rules/80-drivers.rules with something like:
```
ENV{OF_COMPATIBLE_0}=="?*", RUN{builtin}+="kmod load of:N$env{OF_NAME}T$env{OF_TYPE}C$env{OF_COMPATIBLE_0}"
ENV{OF_COMPATIBLE_1}=="?*", RUN{builtin}+="kmod load of:N$env{OF_NAME}T$env{OF_TYPE}C$env{OF_COMPATIBLE_1}"
ENV{OF_COMPATIBLE_2}=="?*", RUN{builtin}+="kmod load of:N$env{OF_NAME}T$env{OF_TYPE}C$env{OF_COMPATIBLE_2}"
ENV{OF_COMPATIBLE_3}=="?*", RUN{builtin}+="kmod load of:N$env{OF_NAME}T$env{OF_TYPE}C$env{OF_COMPATIBLE_3}"
ENV{OF_COMPATIBLE_4}=="?*", RUN{builtin}+="kmod load of:N$env{OF_NAME}T$env{OF_TYPE}C$env{OF_COMPATIBLE_4}"
```

However the number of `OF_COMPATIBLE_*` strings is potentially unlimited and the proper solution would be to iterate over them. It seems the rules language does not permit this as it doesn't support nested variables: We'd need an iterator variable that counts from 0 to `ENV{OF_COMPATIBLE_N}` and calls `kmod load` for each `$env{OF_COMPATIBLE_$env{iter}}`.

Until the rules language is extended by such nested variables, just adding udev rules for, say, 5 `OF_COMPATIBLE_*` strings (as shown above) might be the best solution.

**Comment by poettering** [comment]
Hmm, not sure I follow, but why doesn't openfirmware just generate appropriate modalias lines like everything else?

**Comment by l1k** [comment]
Sorry for not having provided sufficient context.

Historically, I2C and SPI devices were instantiated from machine descriptions e.g. in `arch/arm/mach-*` using <a href="http://elixir.free-electrons.com/linux/latest/ident/i2c_board_info">struct i2c_board_info</a> and <a href="http://elixir.free-electrons.com/linux/latest/ident/spi_board_info">struct spi_board_info</a>. These structures contain a `type` (for I2C) or `modalias` (for SPI) string. The I2C and SPI core prefixes that name with `i2c:` or `spi:` and the resulting `MODALIAS` string is sent to user space. Drivers need to declare a `MODULE_DEVICE_TABLE(i2c, ...)` or `MODULE_DEVICE_TABLE(spi, ...)` to be able to bind to these devices.

When DeviceTree support was added later, backward-compatibility was sought to be achieved by stripping the vendor from the first `compatible="..."` property found in the DeviceTree and fabricating a `MODALIAS` string by prefixing the result with `i2c:` or `spi:`. E.g. `compatible="microchip,mcp3550";` would result in `spi:mcp3550` for an SPI slave. This code lives on until today with the calls to `of_modalias_node()` in <a href="http://elixir.free-electrons.com/linux/latest/source/drivers/i2c/i2c-core.c#L1782">of_i2c_register_device</a> and <a href="http://elixir.free-electrons.com/linux/latest/source/drivers/spi/spi.c#L1624">of_register_spi_device</a>. Originally it was introduced with commits torvalds/linux@612212a3f2f053ea68ce9cd16d3deeca7754e8c9 and torvalds/linux@284b01897340974000bcc84de87a4e1becc8a83d.

One problem with this approach is that apparently products exist which share the same name but are from different vendors. So without the full OF `compatible` string it cannot be unambiguously determined which driver to use.

Another problem is that newer hardware forgoes the historical machine descriptions and relies solely on the DeviceTree. Drivers written for such hardware no longer bother declaring a `MODULE_DEVICE_TABLE(i2c, ...)` or `MODULE_DEVICE_TABLE(spi, ...)`, they only declare a `MODULE_DEVICE_TABLE(of, ...)`. If these drivers are compiled into the kernel, everything is fine. However if they're compiled as a module and systemd-udevd is used, the drivers cannot be bound to devices.

The `MODALIAS` reported by the I2C and SPI core won't be changed to retain backwards compatibility. The expectation is that user space also uses the `OF_COMPATIBLE_*` strings to find matching drivers. The strings are added by <a href="http://elixir.free-electrons.com/linux/latest/ident/of_device_uevent"> of_device_uevent()</a> (originally added with torvalds/linux@eb0cb8a07e320ed3237789cc4f29858338d14d8e).

This is not a theoretical problem: Raspbian ships with a <a href="https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/lib/udev/rules.d/15-i2c-modprobe.rules">custom udev rule</a> to load modules based on the `OF_COMPATIBLE_0` string since many Raspberry Pi peripherals are attached via I2C or SPI and use drivers which only declare a `MODULE_DEVICE_TABLE(of, ...)`.

**Comment by poettering** [comment]
Still not getting it... If the modalias lines are borked it's not udev's job to work around thta, but the kernel's job to fix that... given that modalias strings are only passed through userspace, and are both generated by the kernel (i.e. i.e shown in /sys) and consumed by the kernel (i.e. attached to kmods) it should just fix it's own stuff there, why would userspace mangle things around?

**Comment by l1k** [comment]
There can only be a single `MODALIAS` string per device and its makeup is fixed for I2C and SPI devices to not break backward compatibility. If multiple `MODALIAS` strings are reported by the kernel, <a href="http://lists.infradead.org/pipermail/linux-mtd/2015-November/063542.html">only the last one will be used by kmod</a>. Hence taking advantage of the `OF_COMPATIBLE_*` strings seems to be the only option to pair drivers with devices.

**Comment by poettering** [comment]
> There can only be a single MODALIAS string per device and its makeup is fixed for I2C and SPI devices to not break backward compatibility.

What kind of backward compatibility? Which software consumes these strings, that isn't the kernel itself with its module matches?

Also, the way modalias is designed is that you match against them with wildcards, thus keeping the door open for extending them, simply by adding more fields to the end. Why do you say this can't be made use of here?

**Comment by martinezjavier** [comment]
@l1k I agree with @poettering on this.

User-space is doing the correct thing and shouldn't be changed. It's the kernel that has a broken behavior and should be fixed.

Also, it's not true that the I2C and SPI subsystems OF modalias reporting won't be changed to keep backward compatibility. It's just that when OF support was added to these subsystems, it wasn't done correctly and the MODALIAS logic wasn't changed.

And this had the unfortunate effect of drivers abusing this broken behavior, so all drivers should be fixed before changing it. But that doesn't mean that can't be fixed.

**Comment by poettering** [comment]
Closing. As I understand the kernel folks agree that this should be better fixed on the kernel side.
