### ISSUE TITLE
Add "orientation ignore" property for accelerometers

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#6557]
From Hans:
> -Talked to Bastien about what to do with accelerometers in the base of a
>     clamshell design (mini)laptop the conclusion was that iio-sensor-proxy
>     should create an input-dev for it for games, but otherwise it should be
>     ignored (auto rotation makes no sense on a non-yoga clamshell, esp. if
>     the sensor is not even in the display part).

We should probably add some information about the physical location of the accelerometer in the device, but it might be worth checking whether the ACPI _PLD already contains this information (so we can script this).

CC @jwrdegoede @dsd

**Comment by dsd** [comment]
Is the suggestion here to auto-calculate the mount matrix from _PLD data, or to use a scheme to determine when to ignore the device in iio-sensor-proxy?

**Comment by hadess** [comment]
> Is the suggestion here to auto-calculate the mount matrix from _PLD data, or to use a scheme to determine when to ignore the device in iio-sensor-proxy?

Use the _PLD data to know which of multiple accelerometers to ignore, and which one to auto-create a mount matrix for.

**Comment by mschiu77** [comment]
@hadess we recently got a All-In-One machine (Acer Veriton Z4660G) which detects an accelerometer inside. And from the accelerometer reading, it's interpreted the display is upside-down so the X display is rotated inverted accordingly. For this AIO, maybe we can ignore the accelerometer reading according to the chassis type? Do you need me to post the ACPI data with the _PLD for reference?

**Comment by hadess** [comment]
> For this AIO, maybe we can ignore the accelerometer reading according to the chassis type?

I'd much rather you added a mount-matrix for it.

> Do you need me to post the ACPI data with the _PLD for reference?

If it has any, which I doubt, yes. But that's not going to help if that information isn't exported. We can still make a note of it in the hwdb file though.

**Comment by dsd** [comment]
> Use the _PLD data to know which of multiple accelerometers to ignore, and which one to auto-create a mount matrix for.

I have yet to see any system that has multiple accelerometers. In this case the All-in-one units have a single accelerometer. We will submit the mount matrix to systemd:
```
  ACCEL_MOUNT_MATRIX=1, 0, 0; 0, -1, 0; 0, 0, 1 
```

We also did look at _PLD data but there's no entry for the accelerometer. However there is an _ONT method which looks suspiciously like a mount matrix. We are asking the vendor for clarification.

```
        Device (A_CC)
        {
            Name (_ADR, Zero)  // _ADR: Address
            Name (_HID, "SMO8840")  // _HID: Hardware ID
            Name (_CID, "SMO8840")  // _CID: Compatible ID
            Name (_UID, One)  // _UID: Unique ID
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                Return (0x0F)
            }

            Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
            {
                Name (SBUF, ResourceTemplate ()
                {
                    I2cSerialBusV2 (0x0019, ControllerInitiated, 0x00061A80,
                        AddressingMode7Bit, "\\_SB.PCI0.I2C0",
                        0x00, ResourceConsumer, , Exclusive,
                        )
                })
                Return (SBUF) /* \_SB_.PCI0.I2C0.A_CC._CRS.SBUF */
            }

            Method (_ONT, 0, NotSerialized)
            {
                Return (Package (0x06)
                {
                    One, 
                    Zero, 
                    0x02, 
                    Zero, 
                    Zero, 
                    One
                })
            }
        }
```
