### ISSUE TITLE
LimitNOFILE=ininity defaults to 65535

### ISSUE THREAD

**Issue by zuzzas** [systemd/systemd#6559]
### Submission type
Bug report

### systemd version the issue has been seen with

systemd 234

### Used distribution

Debian Sid

### In case of bug report: Expected behaviour you didn't see

`LimitNOFILE=ininity` sets maximum FD's to 65535. Shouldn't it be equal to `fs.file_max` and/or `fs.nr_open`?

### In case of bug report: Unexpected behaviour you saw

`LimitNOFILE=ininity` sets maximum FD's to 65535.

### In case of bug report: Steps to reproduce the problem

Create any Unit file with `LimitNOFILE=infinity` option in `[Service]` group.

**Comment by zuzzas** [comment]
Of course, I've misspelled 'infinity' and mindlessly copy-pasted it everywhere. My apologies!

**Comment by evverx** [comment]
`systemd` has been reading `nr_open` since 6385cb31ef443be3e0 was merged, so assigning `infinity` to `LimitNOFILE` when `nr_open` is equal to `123456` generally leads to the following:
```sh
3130  setrlimit(RLIMIT_NOFILE, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = -1 EPERM (Operation not permitted)
3130  getrlimit(RLIMIT_NOFILE, {rlim_cur=123456, rlim_max=123456}) = 0
3130  setrlimit(RLIMIT_NOFILE, {rlim_cur=123456, rlim_max=123456}) = 0
```
. It seems that the issue can be closed. Or is there anything else that I might have missed?

**Comment by zuzzas** [comment]
Thank you!
I'll investigate, perhaps, my test case is flawed.

**Comment by poettering** [comment]
Yupp, it appears 6385cb31ef443be3e0 fixed this, which is part of v234. @zuzzas please upgrade!

**Comment by HOSTED-POWER** [comment]
We have the issue on CentOS 7 atm. When we set LimitNOFILE=infinity we can't open more than 65535 files. We set manually to a very high value and that worked.

But could we conclude that newer systemd version will not suffer from this since the change?

**Comment by konstruktoid** [comment]
Verified with `systemd-219-62.el7.x86_64` on `Red Hat Enterprise Linux Server release 7.6 (Maipo)`.

**Comment by HOSTED-POWER** [comment]
Hmm not sure anymore, must have been latest at the time of testing since we update always very quickly.

**Comment by chenqiangzhishen** [comment]
has the same issue, with version `systemd-219-57.el7.x86_64`
so should change the `LimitNOFILE` manually  to a bigger number, such as `1048576`

**Comment by keszybz** [comment]
@chenqiangzhishen please comment here if you can reproduce this with systemd >= 240.
