### ISSUE TITLE
systemd-bootchart is not generating an image when run from init

### ISSUE THREAD

**Issue by ensonic** [systemd/systemd#656]
when running 

```
/lib/systemd/systemd-bootchart --rel
```

I get a svg generated in /run/log. When using it via init I don't.

```
# cat /proc/cmdline 
mem=64M console=ttyS1,115200n8 root=/dev/mmcblk0p2 rw rootwait splash init=/lib/systemd/systemd-bootchart
# journalctl -b | grep -i bootchart
Jan 01 01:00:04 ev3dev kernel: Kernel command line: mem=64M console=ttyS1,115200n8 root=/dev/mmcblk0p2 rw rootwait splash init=/lib/systemd/systemd-bootchart
# cat /etc/systemd/bootchart.conf | grep -v "^#"
[Bootchart]
PlotMemoryUsage=yes
```

Once the system is up and I log in, there is no process with bootchart in the name that is running.

**Comment by ensonic** [comment]
I found that when I extract the svg from journal, that those are truncated:

```
<!--  [288] pss=150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150,150, -->
<!--  [335] pss=273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273, -->
<!--  [355] pss=585,585,585,585,585,585,585,585,585,585,585,585,5
```

I also tried with PlotMemoryUsage=no. But those there from the manual runs (with --rel).

**Comment by ensonic** [comment]
When using bootchat via init, is it waiting for a certain target to be reached or is it also just waiting for N samples to be collected?

**Comment by sofar** [comment]
bootchart doesn't wait for a signal or event. It exits after the sample count has been reached.

**Comment by ensonic** [comment]
So is the presence of the file in /run/log/ the only result of a successful run? Any ideas besides throwing logging into the code that I can do to check whats going on?

**Comment by sofar** [comment]
It writes a message to stdout when it completes, which also ends up in the journal. Any error logging other than that is difficult due to the fact that for most of the early start, there is no place to log (the fs isn't writable) and no log daemon is running yet.

**Comment by ensonic** [comment]
The only thing I get in the log is:

```
journalctl -b | grep bootchart
Jan 01 01:00:04 ev3dev kernel: Kernel command line: mem=64M console=ttyS1,115200n8 root=/dev/mmcblk0p2 rw rootwait splash init=/lib/systemd/systemd-bootchart
```

Do you mind to post what you get for reference? Also I seem to miss something. I now added quite a few log_info() statements into the code, rebuild and run manually. All I get is:

```
journalctl -b | grep -i bootchart
Jan 01 04:07:44 ev3dev kernel: Kernel command line: mem=64M console=ttyS1,115200n8 root=/dev/mmcblk0p2 rw rootwait splash init=/lib/systemd/systemd-bootchart
Jul 31 13:40:39 ev3dev systemd-bootchart[603]: Bootchart created: /run/log/bootchart-20150731-1340.svg
```

The log_info() stuff does not seem to go anywhere. I've tried setting SYSTEMD_LOG_LEVEL=info but its not changing anything.

**Comment by sofar** [comment]
That's it - the "Bootchart created: $file" message is what it outputs once it completes successfully.

**Comment by ensonic** [comment]
Sure, I got that. 

1) So why is it not doing that when I run this as init?
2) Why are none of the log_info() statements show up in the journal (neither when run via init or manually).

**Comment by sofar** [comment]
log_\* is just a macro to printf. Most likely the messages you'd expect are printed out at start, at which they can't go anywhere since there's no journal running.

**Comment by ensonic** [comment]
log_\* are not macros to printf. I really did spend some time to track it down and as far as I understood they go to
https://github.com/systemd/systemd/blob/HEAD/src/basic/log.c#L539
In addition I've said that I also run systemd-bootchart manually once the system was up and neither in that case the log_info message showed up. I'll guess I can only give up on this.

**Comment by sofar** [comment]
looks like log_target then is unset, so it errors out before anything is ever done with the message. It defaults to LOG_TARGET_CONSOLE, but I can't see it actually declared anywhere, although it's symbol is in the binary...

**Comment by usedbytes** [comment]
Did you ever get to the bottom of this? I see the same behaviour (or lack thereof)

**Comment by sofar** [comment]
This issue should be moved to systemd/systemd-bootchart, I suppose, and no, I haven't looked further into it.

**Comment by zonque** [comment]
Yes, please re-open this issue in systemd/systemd-bootchart, the new home for this project. Thanks!
