### ISSUE TITLE
hostnamectl report "Could not set property: Connection timed out" 

### ISSUE THREAD

**Issue by todaygood** [systemd/systemd#6563]
### Submission type
  - Bug report

### systemd version the issue has been seen with
systemd-sysv-219-30.el7_3.9.x86_64
systemd-219-30.el7_3.9.x86_64
systemd-libs-219-30.el7_3.9.x86_64

### Used distribution

centos7.3

### In case of bug report: Expected behaviour you didn't see
Succeed in setting new hostname 

### In case of bug report: Unexpected behaviour you saw

report "Could not set property: Connection timed out" 

### In case of bug report: Steps to reproduce the problem
1.echo "hostnamectl set-hostname cloud-compute-1946.cloud.baby.cn >> /root/hostname.log 2>&1"  >> /etc/rc.local
2. chmod +x  /etc/rc.d/rc.local
3.reboot
4.it failed to set the hostname ,and cat /root/hostname.log:
Could not set property: Connection timed out

**Comment by poettering** [comment]
Please contact your downstream distribution for help. We only track issues in the two most recently released upstream systemd versions here, and that is 233 and 234 at the moment. 219 is waaay to old for this.

Please note that the issue submission form is supposed to make this very clear to save you from this kind of frustration.

**Comment by 467754239** [comment]
Hello, is there a solution to this problem?

**Comment by pabloab** [comment]
If `sudo sysctl kernel.hostname=oldname` return _Read-only file system_ maybe this happen always with a container, for eg. with Proxmox CT/Docker/LXC/LXD.
