### ISSUE TITLE
socket activation: dentry slab cache keeps increasing

### ISSUE THREAD

**Issue by hex2a** [systemd/systemd#6567]
### Submission type
 - Bug report

### systemd version the issue has been seen with

Debian stable/stretch: **232**-25+deb9u1 (stable Kernel: 4.9.30-2+deb9u2)
Debian oldstable/jessie: 230-7\~bpo8+2 (backports Kernel: 4.9.30-2+deb9u2\~bpo8+1)

### Used distribution

> Debian stretch/jessie

### Unexpected behaviour you saw

> When using socket activation, the dentry slab cache usage keeps increasing with each connection 
(even after the connection was closed).

### Steps to reproduce the problem
**1.** create socket/service files:

_/etc/systemd/system/test.socket_
```
[Unit]
Description=test socket

[Socket]
ListenStream=9200
Accept=true

[Install]
WantedBy=sockets.target
```

_/etc/systemd/system/test@.service_
```
[Unit]
Description=test service
After=network.target

[Service]
User=nobody
ExecStart=-/bin/true
StandardInput=socket
```

`systemctl daemon-reload`
**2.**
start socket/service: `systemctl start test.socket`

**3.**
monitor the slab cache usage during testing using `slabtop`
**4.**
simulate ~ 3 connections/s
`timeout 2m sh -c 'while true; do nc 127.0.0.1 9200 & sleep 0.3s; done'`

before:
![image](https://user-images.githubusercontent.com/8384544/29075650-55ffc73e-7c53-11e7-9fb0-bd00decd7f3d.png)

after:
![image](https://user-images.githubusercontent.com/8384544/29075894-251fab4c-7c54-11e7-9592-553ba8bf403e.png)

-----

while this may seem negligible in the test environment, it causes high memory/cache usage in production:

_(graph drops because cache was  freed using `echo 2 > /proc/sys/vm/drop_caches`)_
![image](https://user-images.githubusercontent.com/8384544/29076402-bc3cac40-7c55-11e7-874c-a1f5b1ddae90.png)

_Comparison with xinetd:_  
![image](https://user-images.githubusercontent.com/8384544/29076619-567d549e-7c56-11e7-9a1f-304e6d35ed03.png)

**Comment by zdzichu** [comment]
You shouldn't report issues for version older than most recent and one before here, not before reproducing the issue on the latest systemd code. Distro tracker is a proper place for old versions.

Nevertheless, I've reproduced the issue with systemd-**234**-5.fc27 (on fedora rawhide). During two minutes of connection attempts, dentry slabs went from 815 to 1012 and have not decreased after stopping `test.socket`.

**Comment by evverx** [comment]
The following script can be run to see what exactly calls `__d_alloc`:
```sh
sudo stap -v -e  'probe kernel.function("__d_alloc") { printf("%s:%s\n", $sb->s_type->name$, $name->name$); }'
```
There are many unit names like `test@2-127.0.0.1:9200-127.0.0.1:42300.service`, which is expected because `systemd` generates unit names on the fly and they are kind of unique.

I'm not sure I understand what this issue is about. Do you expect `systemd` to tune the kernel memory allocation?

**Comment by poettering** [comment]
Humm, so what are we supposed to do with this? Caches growing is not precisely a problem, and we don't manage this specific one anyway, it's the kernel.

Are you suggesting we leak some kind of resource? If so, can you be more explicit, on what precisely you think we are doing wrong and should be doing differently?

**Comment by hex2a** [comment]
@evverx https://gist.github.com/hex2a/d9353b22de5b21fca506de0caaf908fc
for comparison xinetd: https://gist.github.com/hex2a/c5aca14b1dece3cb4d95ae684e632f71

While tuning kernel memory allocation is certainly not the purpose of systemd, one wouldn't expect that connections to the socket/service could use several GBs of (slab) cache (which probably leads to eviction of cache entries that are 'useful').

The way systemd handles these connections/starts the service causes a lot of unnecessary cache entries. (see the systemtap gist)

**Comment by evverx** [comment]
@hex2a, `systemd` does much more than `xinetd`, so the difference appears to be expected. If for some reason that overhead is not acceptable, I'd suggest stopping using the socket activation and starting using `xinetd`.

**Comment by poettering** [comment]
I will close this now. This issue doesn't really have anything actionable. As far as I can see we don't actually do anything wrong. systemd has a heavier footprint than xinetd, and in particular on the fs layer, already because cgroupfs is exposed as file system, but also because we look for per-instance drop-in configuration files for each incoming connection. 

We can certainly optimize things a bit, but for that we'd need actionnable data, i.e. information about stuff we do we shouldn't do, and so on. Dumping dentry cache stats here isn't enough for that. 

I hope that makes sense, closing.

**Comment by riking** [comment]
This requires a kernel fix to avoid unbounded cache growth.

**Comment by tuxillo** [comment]
> This requires a kernel fix to avoid unbounded cache growth.

Can you please elaborate?
