### ISSUE TITLE
bootchart man page could simply tell how to retieve the svg from journal

### ISSUE THREAD

**Issue by ensonic** [systemd/systemd#657]
The manpage claims that the svg is stored in the journal: https://github.com/systemd/systemd/blob/6433d440729d22f5954ea1bf9c828bbad04e0838/man/systemd-bootchart.xml#L87-93

Instead of or in addition to showing the MESSAGE_ID and FIELD it could actually tell how to extract it. I've tried a few things like:

```
# journalctl -b -F BOOTCHART >/run/log/bootchart.svg
# grep -c "<?xml" /run/log/bootchart.svg 
6
```

**Comment by sofar** [comment]
yeah, this needs fixing for sure.

**Comment by sofar** [comment]
Does this still work (right after you booted with bootchart enabled?):

'''' journalctl MESSAGE_ID=9f26aa562cf440c2b16c773d0479b518 --field=BOOTCHART -b

**Comment by ensonic** [comment]
That command gives the same truncated output:

```
# journalctl MESSAGE_ID=9f26aa562cf440c2b16c773d0479b518 --field=BOOTCHART -b >/run/log/bootchart1.svg
# journalctl -b -F BOOTCHART --full >/run/log/bootchart2.svg
# ll /run/log/
total 2584
-rw-r--r-- 1 root root 1318923 Jul 30 15:05 bootchart1.svg
-rw-r--r-- 1 root root 1318923 Jul 30 15:05 bootchart2.svg
```

What is puzzling me is:
- the MESSAGE_ID args is hard to discover, I was looking for a flag on journatctl to pass the message id.
- -b should show entries for this boot, but on the svg dump I have 11 concatenated svgs and those are all from my manual invocations, none is from an actual boot.

Finally the svg is always truncated, see systemd/systemd#656

**Comment by sofar** [comment]
Any invocation of systemd-bootchart will dump it's output in the journal. Did you run it manually afterwards?

**Comment by ensonic** [comment]
On previous days I did. But e.g. today I booted a few times, without manually running bootchart. The concatenated-broken svg is the same as what I got from the day where I did run bootchart manually (with -r) to check that it actually works (and to verify the bug fix I send).
