### ISSUE TITLE
sd-bus does not try to connect to dbus-1 socket when access to kdbus is denied

### ISSUE THREAD

**Issue by aineko** [systemd/systemd#6586]
### Submission type
 - Bug report

### systemd version the issue has been seen with
> 234

### Used distribution
> Arch Linux

### In case of bug report: Expected behaviour you didn't see
> Apps can use nss-resolve even when access to /sys/fs is locked down.

### In case of bug report: Unexpected behaviour you saw
> Apps cannot resolve zeroconf-discovered machine names.

When comparing `strace ping some_intranet_host` with /sys/fs available vs. locked down...
1. /sys/fs is available:

    open("/sys/fs/kdbus/0-system/bus", O_RDWR|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    ....
    connect(5, {sa_family=AF_UNIX, sun_path="/var/run/dbus/system_bus_socket"}, 33) = 0
    ....
    // successfully resolves the address

2. /sys/fs is locked down:

    open("/sys/fs/kdbus/0-system/bus", O_RDWR|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
    ....
    // no attempt to connect to "/var/run/dbus/system_bus_socket" and the address is not resolved

I think the bug was introduced in [this commit](https://github.com/systemd/systemd/commit/154429127cb400bf010d41d7dd3ba4ec41b9ffb3) and the fix would be to include EACCES when deciding if kernel address is available:

    else if (b->kernel) {
        r = bus_kernel_connect(b);
        if (r < 0 && !IN_SET(r, -ENOENT, -ESOCKTNOSUPPORT, -EACCES))
            kdbus_available = true;

Probably the same should be done for container_kdbus_available.

### In case of bug report: Steps to reproduce the problem
> Make sure /etc/nsswitch.conf has `resolve` configured:

    hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname

> Lock down /sys/fs and try pinging a zeroconf-ed machine. For example with Firejail:

    firejail --noprofile ping some_intranet_host

**Comment by evverx** [comment]
That code was removed in a132bef0239e6c3f04 a while ago. Is there any chance you could check that everything works well?

**Comment by poettering** [comment]
Sorry, but the kdbus code is now all gone. kdbus wasn't a success ultimately, and we are back a sockets only. Sorry.

**Comment by aineko** [comment]
Great, I am looking forward to see how this works in the next release!
