### ISSUE TITLE
Allow fully disabling systemd-coredump

### ISSUE THREAD

**Issue by nekohayo** [systemd/systemd#659]
I would really like a way to fully disable systemd catching application crashes / core dumps; it grinds my system to a halt with I/O & CPU. I suppose this feature is mostly useful for those who want to use ABRT or similar tools or catch kernel/X crashes, but I don't fit that category and neither do the people I maintain computers for (my aunts certainly won't report crasher bugs :)

I set "storage=None" in /etc/systemd/coredump.conf in the hope that it would disable this feature, but it doesn't; if I force kill evolution (with evolution --force-shutdown) for example, my system will start grinding like mad because there will be two systemd-coredump processes trying to figure out why Evolution "crashed", so I have to kill those two processes too.

At the end of the day, I'd love to have a global "enabled=0" setting in coredump.conf !
Thanks

**Comment by sztanpet** [comment]
just mask the 50-coredump.conf from sysctl.d that sets up systemd-coredump handling for coredumps
see systemd-coredump(8)

**Comment by nekohayo** [comment]
For the record, a while back I also tried putting "kernel.core_pattern = /dev/null" in /etc/systemd/coredump.conf and that didn't work either. That's part of why I'm thinking a new global "enabled/disabled" setting would make sense...

And re @sztanpet: I don't even understand what that means - really, I have no clue what to do when reading your instructions, it's all greek to me. I'm just a desktop user that expects a setting in /etc like the rest of the system, just like the fact that I can edit /etc/selinux/config to have "SELINUX=disabled", for example :)

**Comment by sztanpet** [comment]
make the file `/etc/sysctl.d/50-coredump.conf` a symlink to /dev/null
the original sysctl.d file is in `/usr` (or other distro specific places) but that is package manager territory, so to override them, you place a file with the same name in `/etc` that override the distro settings
this works the same for almost all systemd components

**Comment by poettering** [comment]
See the first paragraph in the systemd-coredump(8) man page, it indicates how to turn off the tool, via the sysctl snippet that @sztanpet mentioned.

**Comment by nekohayo** [comment]
is "man systemd-coredump(8)" a thing? Honest question, I tried that and got nothing, no idea how to access the (8) part. That tells you how much of a casual user I am in the sysadmin side of things. OTOH, I see the (8) at the top when I do "man systemd-coredump", so I assume that's not actually a separate man page/chapter/etc.

So. I _did_ indeed read "man systemd-coredump" before reporting/commenting here, but:
- it only mentioned `/usr/lib/sysctl.d/50-coredump.conf` (not the one in /etc, so that's a bit confusing for starters
- it did not say "replace this by a symlink to /dev/null or remove this file to disable the feature", instead it said it can be "masked"\* or "overridden to use a different setting", and that sounds quite different to me

And I'm still confused after re-reading the manpage and sztanpet's comment, because of the fact that on Fedora 22 I don't even _have_ a /etc/sysctl.d/50-coredump.conf file to begin with, only the systemd coredump.conf file I was initially trying to edit (hence this report):

```
$ locate coredump.conf
/etc/systemd/coredump.conf
/usr/lib/sysctl.d/50-coredump.conf
/usr/share/man/man5/coredump.conf.5.gz
/usr/share/man/man5/coredump.conf.d.5.gz
```

Am I missing something obvious here? Maybe I'm dumb but I feel like the documentation on this is somewhat unclear. And if searches across the net and reading wikis (including the usually excellent Arch wiki**) only gave me misleading information so far, I think that might be an indication for the need of something to improve in that man page (or a clear setting to be added to the conf file... :-)

*: "mask" is a pretty technical term that I'm not familiar with, I've no idea how to do masking. Doing some searches on the internet point to umask, which then gets you digging around to learn about octal/binary/whatever notations and at this point you've lost the casual user (me included) down the rabbit hole... my 2¢
**: https://wiki.archlinux.org/index.php/Core_dump#Using_systemd

**Comment by sztanpet** [comment]
yes, you have to create the file to override the distro provided one,
the mask part is coming from the sysctl.d manual among others, see http://www.freedesktop.org/software/systemd/man/sysctl.d.html the "Configuration Directories and Precedence" section

**Comment by poettering** [comment]
> is "man systemd-coredump(8)" a thing? Honest question, I tried that and got nothing, no idea how to access the (8) part.

Well, that's how man pages are usually denoted on UNIX. Consider typing it into google. It will point you to the right place. Alternatively just type "man 8 systemd-coredump".

**Comment by poettering** [comment]
Read the man page. It says in its first paragraph:

```
Systemd installs /usr/lib/sysctl.d/50-coredump.conf which configures kernel.core_pattern to
invoke systemd-coredump. This file may be masked or overridden to use a different setting 
following normal sysctl.d(5) rules.
```

The "sysctl.d(5)" is how man pages denote hyperlinks. If you browse the man page via we browser you can click on it. In a terminal you can type "man 5 sysctl.d" to get to the same document, where it says:

```
Configuration files are read from directories in /etc/, /run/, and /usr/lib/, in order of precedence.
Each configuration file in these configuration directories shall be named in the style of
filename.conf. Files in /etc/ override files with the same name in /run/ and /usr/lib/. Files in
/run/ override files with the same name in /usr/lib/.

Packages should install their configuration files in /usr/lib/. Files in /etc/ are reserved for the
local administrator, who may use this logic to override the configuration files installed by vendor
packages. All configuration files are sorted by their filename in lexicographic order, regardless of
which of the directories they reside in. If multiple files specify the same option, the entry in the
file with the lexicographically latest name will take precedence. It is recommended to prefix all
filenames with a two-digit number and a dash, to simplify the ordering of the files.

If the administrator wants to disable a configuration file supplied by the vendor, the recommended
way is to place a symlink to /dev/null in the configuration directory in /etc/, with the same
filename as the vendor configuration file.
```

It's all documented in the man pages, please just read them!

**Comment by nekohayo** [comment]
Alright thanks, at least I have a solution/workaround now. Sorry for my confusion, I'm not used to having to go through the system's entrails like that and at some point started doubting if I was missing a big piece of knowledge about the "man" command!

**Comment by Trucido** [comment]
Edit: Sorry I just realized this is a 2 year old necro post but the manuals don't have any useful information on how to actually disable the darn core dumps, only how to set a new location for dumps. Also, systemd seemingly ignores the /etc/systemd/* files for coredump.conf and system.conf and even kernel cmdline systemd.dump_core=no
  
The only thing I found that worked was either symlinking it to /dev/null which breaks package verification/checksums and potentially also future updates in other strange ways, or setting it to |/bin/false  
  
**/etc/sysctl.d/50-nocoredump.conf**
`kernel.core_pattern = |/bin/false`
  
(the name can be anything, it works if that line is anywhere sysctl gets loaded later than the 50-coredump.conf systemd comes with, such as /etc/sysctl.conf or /etc/sysctl.d/99-sysctl.conf)
  
This would have been a whole lot easier if systemd-coredump was like a service unit or something you could mask/disable, or if it actually read it's own config files. Not everyone wants dumps, and attempted dumps was causing one of my older machines to lockup while trying to test new nouveau code. And not even SysRq was doing anything (even though it was enabled). systemd must really want those dumps badly.

**Comment by martyg77** [comment]
Just bashed my head into this same problem.

It would be nice if upstream systemd maintainers understood is users need a reliable, straightforward way to do this when needed.  This is way too complicated, and should not be buried in an obscure paragraph in the man page.

**Comment by niarbeht** [comment]
Consistent, easy-to-understand ways to enable or disable features really should be a priority here.  Systemd-coredump has been giving me trouble for over a year now.  I really don't care _WHY_ my game crashed, _I JUST WANT TO START IT AGAIN_.  Systemd-coredump gets in the way of user experience in a very, very frustrating way.

**Comment by shubham0d** [comment]
The developers has done a really shitty job here. It look like they forget to make a kill switch for this thing. I am trying for a day to stop this thing but it really doesn't stop at all. They have ruined my system and for that all I can say is F*CK YOU DEVS.
