### ISSUE TITLE
systemd-mount wants a valid WHAT parameter for virtual filesystems

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#6591]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

custom : buildroot

### In case of bug report: Expected behaviour you didn't see
( /mountpoint exists)

`systemd-mount -t tmpfs none /mountpoint`

should succeed

### In case of bug report: Unexpected behaviour you saw

`systemd-mount -t tmpfs none /mountpoint`

failed and reported the following error message

`Failed to canonicalize path : no such file or directory`

note that entering a similar line in /etc/fstab works correctly
note that using any existing path instead of _none_ works correctly

**Comment by poettering** [comment]
indeed, we should make that work.
