### ISSUE TITLE
SERVICE_RESULT documentation missing some values

### ISSUE THREAD

**Issue by myrkr** [systemd/systemd#6597]
### Submission type

 - Bug report

### systemd version the issue has been seen with

>233

### Used distribution

> none

### In case of bug report: Expected behaviour you didn't see

> Documentation error, SERVICE_RESULT value "success" for ExecStopPost is undocumented

### In case of bug report: Unexpected behaviour you saw

> The table in https://www.freedesktop.org/software/systemd/man/systemd.exec.html#%24EXIT_CODE implies that SERVICE_RESULT would have the value "exit-code" for a succesful exit of a service unit.

### In case of bug report: Steps to reproduce the problem

> Bug is found in the manpage mentioned above and also found in the man/systemd.exec.xml file contained in the systemd 233 distribution

The source code with the actual values for SERVICE_RESULT:

```
static const char* const service_result_table[_SERVICE_RESULT_MAX] = {
        [SERVICE_SUCCESS] = "success",
	[SERVICE_FAILURE_RESOURCES] = "resources",
        [SERVICE_FAILURE_PROTOCOL] = "protocol",
        [SERVICE_FAILURE_TIMEOUT] = "timeout",
        [SERVICE_FAILURE_EXIT_CODE] = "exit-code",
	[SERVICE_FAILURE_SIGNAL] = "signal",
	[SERVICE_FAILURE_CORE_DUMP] = "core-dump",
        [SERVICE_FAILURE_WATCHDOG] = "watchdog",
        [SERVICE_FAILURE_START_LIMIT_HIT] = "start-limit-hit",
};

```

So it seems that the documentation for start-limit-hit is also missing

**Comment by poettering** [comment]
fix waiting in #6807
