### ISSUE TITLE
resolved: MulticastDNS doesn't seem to be working

### ISSUE THREAD

**Issue by skoehler** [systemd/systemd#6602]
I'm using systemd 234.11 on Arch Linux. It seems that resolved has support for MulticastDNS as defined by RFC 6762. However, even if I set `MulticastDNS=yes` in `/etc/systemd/resolved.conf` and restart systemd-resolved, it doesn't listen on port 5353. The documentation clearly states that `MulticastDNS=yes` implies that systemd runs a full responder and resolver for MulticastDNS.

Note that avahi-daemon is not running. So port 5353 is not blocked.

**Comment by poettering** [comment]
What does "systemctl-resolve --status" say about all this?

**Comment by skoehler** [comment]
`systemd-resolve --status` says `MulticastDNS setting: no` for every interface. I double checked that I have `MulticastDNS=yes` in `resolved.conf`. Also `journalctl -u systemd-resolved` doesn't say anything about MulticastDNS.

**Comment by skoehler** [comment]
Apparently Arch Linux is building systemd from the sources up to commit d52e2bb9c20216972754c054e8534bca28baab66 from systemd-stable.git (see https://archlinuxarm.org/packages/armv7h/systemd/files/PKGBUILD).

**Comment by skoehler** [comment]
Clearly a case of RTFM. The documentation of resolved.conf states 

> Multicast DNS will be enabled on a link only if the per-link and the global setting is on.

So I need it in /etc/systemd/network/ for each link. I wonder however, how I can change the default from `MulticastDNS=no` to `MuticastDNS=yes`.

**Comment by nahuel** [comment]
@skoehler try adding `MulticastDNS=yes` to `/lib/systemd/network/99-default.link`
you can test it using `udevadm test-builtin net_setup_link  /sys/class/net/eth0`  (tested on Debian)

**Comment by skoehler** [comment]
@nahuel that's a link file. Link files support the MulticastDNS option. See https://www.freedesktop.org/software/systemd/man/systemd.link.html for reference.

**Comment by nahuel** [comment]
@skoehler  that link file is special because matches all interfaces (99-**default**.link), so you can set default values for all of them. Try running the `udevadm` line, you will see it being always processed, not mattering the interface you choose.

**Comment by ozw1z5rd** [comment]
Perhaps this helps:

sudo systemd-resolve --set-mdns=yes --interface=wlan0

**Comment by RangerMauve** [comment]
Sorry to necropost. I'm on a steam deck and the `/lib/systemd/network` folder is readonly.

What is the format for the `/etc/systemd/` folder? I'm having trouble figuring out the name to store the config for `wlan0` as well as the format to set MulticastDNS=yes.

**Comment by RangerMauve** [comment]
Seems steamos adds a file which explicitly sets `MulticastDND=no` at `/usr/lib/systemd/resolved.conf.d/00-disable-mdns.conf`.

am I correct that there's no way to override this inside `/etc/systemd/resolved.conf` itself?

**Comment by javidcf** [comment]
> Seems steamos adds a file which explicitly sets `MulticastDND=no` at `/usr/lib/systemd/resolved.conf.d/00-disable-mdns.conf`.
> 
> am I correct that there's no way to override this inside `/etc/systemd/resolved.conf` itself?

I was just dealing with this issue myself, thank you for the pointer about `/usr/lib/systemd/resolved.conf.d/00-disable-mdns.conf`, I thought I was going crazy. 

I got it to work by creating a file `/etc/systemd/resolved.conf.d/99-enable-mdns.conf` with the content:

```
[Resolve]
MulticastDNS=yes
```

**Comment by russdill** [comment]
debian has started doing this for some reason... https://packages.debian.org/sid/amd64/systemd-resolved/filelist

**Comment by javidcf** [comment]
> debian has started doing this for some reason... https://packages.debian.org/sid/amd64/systemd-resolved/filelist

Good find. [Here](https://salsa.debian.org/systemd-team/systemd/-/commit/5e2ba1a04552addd5fb1898d40fa2af392b0cf6b) is the relevant commit: 

> Feedback from users is to prefer breaking mDNS rather than avoiding avahi. Ship a drop-in to disable mDNS by default, so that users relying on mDNS for reachability can hopefully notice it and mask it before upgrading

The commit closes [Debian issue 1098914](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1098914), where the topic is discussed at length. Not having gone through it all, it seems the commit message above summarises the conclusion of the discussion.

**Comment by russdill** [comment]
It's very frustrating to suddenly have numerous network failures due to a package upgrade. Seems like they could have handled it better and made the solution more discoverable.

**Comment by TonyHoyle** [comment]
I just spent a couple of hours thinking I was going crazy until I found that file.  Really stupid to override explicit user configuration silently without warning - they didn't just change the default.
