### ISSUE TITLE
btrfs raid devices referenced by one component's kernel device name in /etc/fstab don't work

### ISSUE THREAD

**Issue by g0tar** [systemd/systemd#6605]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> PLD Linux

### In case of bug report: Expected behaviour you didn't see

> mounted filesystem

### In case of bug report: Unexpected behaviour you saw

> filesystem not mounted due to device timeout

### In case of bug report: Steps to reproduce the problem

- create 2-device btrfs volume
- put old-style device name into fstab (without noauto)

My problem is at least relative to the https://github.com/systemd/systemd/issues/5781 - in fact I suspect the root cause is the same, however I choose to create separate ticket in order not to mix the debug outputs. My configuration is much simpler (doesn't involve device-mapper nor disk labels) and I got the wrong behaviour with almost every system restart.

So, responding the same questions, that were asked there:

- initrd is systemd-less: loads modules, assembles root fs, switches to systemd init; it does NOT mount /srv by itself,
- I can just "mount /srv" from emergency shell, with following result:

<pre>
#  grep /srv /proc/self/mountinfo 
128 20 0:43 / /srv rw,noatime,nodiratime shared:68 - btrfs /dev/sda5 rw,space_cache,subvolid=5,subvol=/
</pre>

<pre>
#  btrfs fi sh /srv
Label: none  uuid: f6731a80-0d5b-4ccc-898a-5da5f8294277
        Total devices 2 FS bytes used 2.82GiB
        devid    1 size 799.51GiB used 4.01GiB path /dev/sda5
        devid    2 size 799.51GiB used 4.01GiB path /dev/sdb5
</pre>

<pre>
# systemctl status dev-sda5.device
* dev-sda5.device - TOSHIBA_HDWD110 5
   Loaded: loaded
  Drop-In: /run/systemd/generator/dev-sda5.device.d
           `-50-device-timeout.conf
   Active: activating (tentative) since Sat 2017-08-12 19:41:37 CEST; 15h ago
   Device: /sys/devices/pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda5
</pre>

<pre>
#  grep sda5 /etc/fstab
/dev/sda5 /srv btrfs   defaults,noatime,nodiratime,device=/dev/sda5,device=/dev/sdb5,x-systemd.device-timeout=10s      0 0
</pre>

<pre>
#  diff <(udevadm info /dev/sda5) <(udevadm info /dev/sdb5) | grep -v *irrelevant*
-E: ID_BTRFS_READY=0
+E: ID_BTRFS_READY=1
-E: SYSTEMD_READY=0
E: TAGS=:systemd:
-E: USEC_INITIALIZED=7302718
+E: USEC_INITIALIZED=7400305
</pre>

<pre>
# dmesg | grep -v *irrelevant*
[Aug11 16:50] Linux version 4.9.40-6 (root@test) (gcc version 6.3.0 20161221 (release) (PLD-Linux) ) #11 SMP PREEMPT Thu Aug 3 21:20:27 CEST 2017
[  +0.009553]  sda: sda1 sda2 sda3 sda4 sda5
[  +0.001150] sd 0:0:0:0: [sda] Attached SCSI disk
[  +0.022107]  sdb: sdb1 sdb2 sdb3 sdb4 sdb5
[  +0.003127] sd 1:0:0:0: [sdb] Attached SCSI disk
[  +0.003632] geninitrd/12757 starting
[  +0.008963] BTRFS: device fsid 17a3de25-6e26-4b0b-9665-ac267f6f6c4a devid 1 transid 10446 /dev/sda2
[  +0.002180] BTRFS: device fsid 17a3de25-6e26-4b0b-9665-ac267f6f6c4a devid 2 transid 10446 /dev/sdb2
[  +0.002048] BTRFS info (device sdb2): disk space caching is enabled
[  +0.001858] BTRFS info (device sdb2): has skinny extents
[  +0.013826] geninitrd/12757 switching root
[  +0.675956] systemd[1]: dev-sda5.device: JobRunningTimeoutSec= is greater than JobTimeoutSec=, it has no effect.
[  +0.369021] BTRFS info (device sdb2): disk space caching is enabled
[  +0.636668] BTRFS: device fsid f6731a80-0d5b-4ccc-898a-5da5f8294277 devid 1 transid 268 /dev/sda5
[  +0.063892] Adding 2097148k swap on /dev/sdb1.  Priority:1 extents:1 across:2097148k FS
[  +0.001980] Adding 2097148k swap on /dev/sda1.  Priority:1 extents:1 across:2097148k FS
[  +0.030984] BTRFS: device fsid f6731a80-0d5b-4ccc-898a-5da5f8294277 devid 2 transid 268 /dev/sdb5
[  +0.175777] EXT4-fs (sdb4): mounting ext3 file system using the ext4 subsystem
[  +0.054428] EXT4-fs (sdb4): mounted filesystem with ordered data mode. Opts: (null)
[  +0.055345] systemd-journald[200]: Received request to flush runtime journal from PID 1
</pre>

<pre>
# journalctl -b | grep -v *irrelevant*
Aug 11 16:50:31 test systemd[1]: dev-sda5.device: JobRunningTimeoutSec= is greater than JobTimeoutSec=, it has no effect.
Aug 11 16:50:31 test kernel: BTRFS info (device sdb2): disk space caching is enabled
Aug 11 16:50:31 test systemd-journald[200]: Journal started
Aug 11 16:50:33 test kernel: BTRFS: device fsid f6731a80-0d5b-4ccc-898a-5da5f8294277 devid 1 transid 268 /dev/sda5
Aug 11 16:50:33 test systemd-fsck[284]: fsck.ext3 doesn't exist, not checking file system on /dev/sdb4.
Aug 11 16:50:33 test kernel: Adding 2097148k swap on /dev/sdb1.  Priority:1 extents:1 across:2097148k FS
Aug 11 16:50:33 test kernel: Adding 2097148k swap on /dev/sda1.  Priority:1 extents:1 across:2097148k FS
Aug 11 16:50:33 test kernel: BTRFS: device fsid f6731a80-0d5b-4ccc-898a-5da5f8294277 devid 2 transid 268 /dev/sdb5
Aug 11 16:50:33 test kernel: EXT4-fs (sdb4): mounting ext3 file system using the ext4 subsystem
Aug 11 16:50:33 test kernel: EXT4-fs (sdb4): mounted filesystem with ordered data mode. Opts: (null)
Aug 11 16:50:33 test systemd-journald[200]: Time spent on flushing to /var is 967.797ms for 822 entries.
Aug 11 16:50:33 test systemd-journald[200]: System journal (/var/log/journal/324de6641e134e769fd85b61ab9d08db) is 0B, max 0B, 0B free.
Aug 11 16:50:41 test systemd[1]: dev-sda5.device: Job dev-sda5.device/start timed out.
Aug 11 16:50:41 test systemd[1]: Timed out waiting for device dev-sda5.device.
Aug 11 16:50:41 test systemd[1]: Dependency failed for /srv.
Aug 11 16:50:41 test systemd[1]: Dependency failed for Local File Systems.
</pre>

Apparently, btrfs-scanned first /dev/sda5 gets ID_BTRFS_READY=0, after that sdb5 gets ID_BTRFS_READY=1, but doesn't update sda5 state. Possible workarounds include:
- delaying sda5 so it gets btrfs-scanned after sdb5,
- changing /dev/sda5 to /dev/sdb5 in fstab (what would happen in regard to /proc/self/mountinfo and sda5 devid==1 lower than sda5 devid==2?),
- mangling /lib/udev/rules.d/64-btrfs.rules to get ID_BTRFS_READY=1 (removing "btrfs ready" builtin? manually setting ID_BTRFS_READY for sda5?) or disabling the wait in systemd itself,
- appending noauto in fstab and creating separate unit mounting /srv the classic way.

However, none of the above looks reliable and the proper solution seems to be making udev to repeat "btrfs ready" builtin for every not-READY device after each consecutive ok-READY device or - at least, for every not-READY device having the same ID_FS_UUID* as consecutive ok-READY.

I find various report regarding this issue dating back to 2015 and still there are problems to cleanly mount btrfs volume via systemd. I guess my problem might be related to duplicated disk/partitions UUIDs (did't investigate this yet), but even so there should be either some graceful way out of this (like proposed above repeating "btrfs ready" builtin) or at least some warning from udev about duplicated UUIDs.

Update:

- as expected, udev creates by-uuid symlink for second device scanned (the one which is ready, as UUID is not available for not-READY btrfs):

<pre>
#  ls /dev/disk/by-uuid | grep sd.5
lrwxrwxrwx 1 root root  10 2017-08-11 16:50 f6731a80-0d5b-4ccc-898a-5da5f8294277 -> ../../sdb5
</pre>

- all my sdb partitions have the same PARTUUIDs as the sda ones, as the entire GPT was cloned by cfdisk dump/restore. I do not however use the PARTUUIDs anywhere explicitly.

Update 2:

I'm wondering if this should be bug report ("filesystem not mounted while being available - with mount -a as a proof") or feature request ("rescan btrfs devices"). The problem appears when nothing calls "btrfs device scan", so the feature requests (all in case of btrfs of course) might be:
- rescan btrfs partitions internally (using internal helper code - in case someone doesn't have btrfs-progs installed at all or something has happened with them),
- do try to mount a filesystem despite being not-READY after timeout,
- after a timeout, print a message with "btrfs device scan" suggestion.

Update 3:

A bit of clarification - "rescan" I've mentioned above is not a real scan in btrfs-terms, but simple udev 'reconsideration', as particular devices are in fact already scanned and known to the kernel. Only udev's property is stuck and causes systemd to wait. Following command unstucks it:

<pre>
udevadm trigger -s block -p ID_BTRFS_READY=0
</pre>

So the only part, that is missing, is something sending change event to sda5 after initializing sdb5. Or, in general, sending change events to all pending devices after any successful one, like directly from 64-btrfs.rules.

**Comment by poettering** [comment]
Let me get this right, the fstab line your are using mentions the fs by the name "/dev/sda5"? That is problematic, as with the current btrfs mounting logic only the "last" appearing device belonging to a btrfs raid setup will be considered "READY". Now, if you mount by UUID that last component will also be the one with the UUID symlink so all is good, but if you reference the fs by the kernel device name of one of its earlier components, then things fall apart quickly.

I am not sure we really should fix anything here in systemd though, and I am not even sure what we could fix here. systemd is not a generic btrfs volume mount manager, and I am not sure we should beef things up on that front too much, after all mounting by kernel name is racy anyway.

My only suggestion on this would be "don't do what you are doing!", even if that sounds dickish... Kernel names aren't stable, you never know what you actually reference until the device showed up, that's why UUIDs for file systems exist. 

Maybe we should extend fstab-generator though to detect this specific case, and at least print a warning if btrfs raid volumes are listed in fstab by their kernel device name. However, I am not sure how we could even detect that a priori, given that the fstab line actually gives no indication whether something is a raid or non-raid btrfs mount...

**Comment by g0tar** [comment]
Since the support for the legacy kernel device names used with btrfs RAID was merged in 0e8856d25ab71764a279c2377ae593c0f2460d8f, this ticket can be closed as resolved.
