### ISSUE TITLE
systemctl enable with an absolute path as argument cannot be used to create template instances

### ISSUE THREAD

**Issue by vishvananda** [systemd/systemd#661]
It is not possible to properly enable a service file that has been symlinked in via systemctl enable.

Take the following example:

``` bash
cat > test.unit <<EOF
[Unit]
Description=Test

[Service]
ExecStart=/bin/sleep infinity

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl link $PWD/test.unit
sudo systemctl enable test.unit # Failed to execute operation: No such file or directory
```

Note that you can enable it by specifying the full path

``` bash
sudo systemctl enable $PWD/test.unit # symlinks from multi-user.target.wants to $PWD/test.unit
```

This links directly to the local file. This strategy doesn't work for templated files:

``` bash
cat > test@.unit <<EOF
[Unit]
Description=Test %i

[Service]
ExecStart=/bin/sleep infinity

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl link $PWD/test.unit
sudo systemctl enable $PWD/test@foo.unit # Failed to execute operation: No such file or directory
```

It seems that it should be able to enable in both cases once it has been linked in without specifying the full path. The enable code could either follow the symlink and link directly to the linked file, or it could just symlink to the symlink and systemd could follow them during startup.

**Comment by poettering** [comment]
The idea was that "link" only makes a unit available in the search paths and "enable" also hooks it in. i.e. "enable" is kind of a superset of "link", as it does the same work if you pass a path, plus some more...

But yeah the template issue you point out is a real issue that this logic cannot cover. Yuck.

**Comment by emamirazavi** [comment]
Why are you putting that unit file there? This is not standard. Add your
favorite unit files to systemd directory located usually in
/etc/systemd/system path(redhat default path). I think it's not a good idea
to manage symlinked path. After all I think systemd can support symlink if
you use it in the systemd directory planned to store unit files.

**Comment by poettering** [comment]
On Wed, 22.07.15 11:49, S.Mohammad Emami Razavi (notifications@github.com) wrote:

> Why are you putting that unit file there? This is not standard. Add your
> favorite unit files to systemd directory located usually in
> /etc/systemd/system path(redhat default path). I think it's not a good idea
> to manage symlinked path. After all I think systemd can support symlink if
> you use it in the systemd directory planned to store unit files.

In general I think we really should ensure that we support in systemd
a scheme nicely where you install a 3rd party unit file somewhere in
/opt or so, and then make it available to systemd with just "systemctl
link" or "systemctl enable", so that 3rd party stuff doesn't litter
/usr (which is private property of the OS vendor), and doesn't add
anything but symlinks to the 3rd party unit files to /etc.

Or in other words: I think what @vishvananda is trying to do is
something we explicitly should support to cover nicely for 3rd party
software, that is neither written by the owner of the machine nor
supplied by the original vendor of the OS but by some 3rd party ISV.

**Comment by emamirazavi** [comment]
Therefore it can be labeled as a feature to implement. Can not it?

**Comment by poettering** [comment]
Well, what @vishvananda pointed out is more than an RFE, since the current logic is not delivering what it was supposed to deliver.

**Comment by keszybz** [comment]
This now works correctly with recent git. There were a bunch of fixes, mostly before v232, so I won't link to specific commits.

Tested:
```
 sudo systemctl link $PWD/test.service
 sudo systemctl enable $PWD/test.service
 sudo systemctl disable $PWD/test.service
 sudo systemctl link $PWD/test@.service
 sudo systemctl enable test@.service
 sudo systemctl enable $PWD/test@.service
 sudo systemctl disable $PWD/test@.service
 sudo systemctl disable test@.service
```
All work as expected.

**Comment by markstos** [comment]
Thank you for this feature!

**Comment by aktau** [comment]
How far did you test the templated versions?

```
 sudo systemctl link $PWD/test@.service
 sudo systemctl enable test@.service
 sudo systemctl enable $PWD/test@.service
 sudo systemctl disable $PWD/test@.service
 sudo systemctl disable test@.service
```

I'm asking in relation to https://github.com/systemd/systemd/issues/3010#issuecomment-399736808, where it seems that for me this does not work (when I have to supply a parameter).

**Comment by keszybz** [comment]
It seems to work with `--root=/` (i.e. on the client side), but not without (i.e. through pid1).

**Comment by elgow** [comment]
Related to this issue, template instances can't be created using aliases to work around this bug. For example

```
~/tryit$ cat serviceB.service
[Unit]
Description=Unit %n

[Service]
Type=oneshot
ExecStart=/bin/echo ExecStart %i go: $${STARTED} 

[Install]
Alias=serviceB@foo.service
Alias=serviceB@bar.service
Alias=serviceBalias.service
```
```
~/tryit$ systemctl --user enable $(pwd)/serviceB.service
Created symlink from /home/me/.config/systemd/user/serviceB@foo.service to /home/me/tryit/serviceB.service.
Created symlink from /home/me/.config/systemd/user/serviceB@bar.service to /home/me/tryit/serviceB.service.
Created symlink from /home/me/.config/systemd/user/serviceBalias.service to /home/me/tryit/serviceB.service.
Created symlink from /home/me/.config/systemd/user/serviceB.service to /home/me/tryit/serviceB.service.
```
```
~/tryit$ systemctl --user list-unit-files
UNIT FILE                    STATE
serviceB.path                linked
LIS_import_failure.service   linked
serviceB.service             enabled
serviceB@bar.service         bad
serviceB@foo.service         bad
serviceBalias.service        enabled
```
So the template instance aliases `serviceB@...` do not get enabled while an alias w/o the `@` does.  If instance aliases would function then this issue could be worked around. In order to allow general use of template instance units, which would be much better than having the feature work in some cases and not others, this issue needs to be fixed.
