### ISSUE TITLE
Inconsistent behavior on out-of-memory condition

### ISSUE THREAD

**Issue by dimitry-ishenko** [systemd/systemd#6613]
`udev_new()` sets errno to negative value:
https://github.com/systemd/systemd/blob/f731ad4456def2badc840dd52e69f2ba243c5155/src/libudev/libudev.c#L99-L103

`udev_device_new()` sets errno to positive value:
https://github.com/systemd/systemd/blob/43ee6a8128dc751943e25c42a490a833904a58b9/src/libudev/libudev-device.c#L219-L223

`udev_monitor_new()` does not set errno:
https://github.com/systemd/systemd/blob/43ee6a8128dc751943e25c42a490a833904a58b9/src/libudev/libudev-monitor.c#L102-L104

`udev_enumerate_new()` sets errno to positive value:
https://github.com/systemd/systemd/blob/f731ad4456def2badc840dd52e69f2ba243c5155/src/libudev/libudev-enumerate.c#L76-L80

**Comment by dimitry-ishenko** [comment]
Further looking into [libudev-monitor.c](https://github.com/systemd/systemd/blob/master/src/libudev/libudev-monitor.c) it needs a few `assert_return_errno()` macros sprinkled throughout.

**Comment by yuwata** [comment]
errno should be positive. libudev.c should be fixed as `errno = ENOMEM`.

**Comment by poettering** [comment]
Yupp, errno should always be positive, and we should only set it if we can't return a negative in return value, because the function prototype doesn't permit it. libudev is borked in this regard.

**Comment by poettering** [comment]
Fix waiting in #6781
