### ISSUE TITLE
nspawn smoke test hangs qemu cpu

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#6614]
### Submission type
 - Bug report

### systemd version the issue has been seen with

234-2ubuntu3

### Used distribution

Ubuntu 17.10 (current in-development release)

### In case of bug report: Expected behaviour you didn't see

In an amd64 qemu machine, systemd-nspawn smoke test using a (nested) VM should pass like it did with v233.

### In case of bug report: Unexpected behaviour you saw

Qemu CPU hangs / systemd fails to shutdown.
```
[  OK  ] Reached target Final Step.
         Starting Power-Off...
[   32.052024] NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd:1]
[   60.052025] NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd:1]
[   88.052029] NMI watchdog: BUG: soft lockup - CPU#0 stuck for 23s! [systemd:1]
```
[nspawn.txt](https://github.com/systemd/systemd/files/1224082/nspawn.txt)

### In case of bug report: Steps to reproduce the problem
```
$ autopkgtest-buildvm-ubuntu-cloud --release artful --arch amd64
$ autopkgtest systemd --apt-upgrade --apt-pocket=proposed=src:systemd --shell-fail -ddd --output-dir logs/ -- qemu ./autopkgtest-artful-amd64.img
```

This test was done with 4.11 kernel and 2.8 qemu. I will redo the test again with 4.12.
It is not reliably reproducible, but every other run exhibits described problem.

**Comment by poettering** [comment]
Well, systemd is userspace and userspace should under no circumstances be able to make the kernel it runs in lock up, regardless if it runs in qemu or not.

(`NMI watchdog: BUG: soft lockup - CPU#0 stuck for 23s!` is a kernel messages indicating a kernel bug. See https://www.suse.com/de-de/support/kb/doc/?id=7017652 for some more info)

There's something wrong between your kernel and your qemu I fear, and needs to be reported to those communities, but we can't do anything about that within the systemd context... sorry.

Closing here. I hope this makes sense.

**Comment by xnox** [comment]
ack, thanks. sorry for the noise.
