### ISSUE TITLE
We should explicitly document that "machinectl --machine=<onemachine> <someverb> <othermachine>" means, and the relationship between the two machines...

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#6621]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233

### Used distribution

> CentOS 7

### In case of bug report: Expected behaviour you didn't see

> `machinectl shell` should use the `--machine` option instead of the first position argument, when `--machine` is provided.

### In case of bug report: Unexpected behaviour you saw

> `machinectl shell` ignores the `--machine` option.

### In case of bug report: Steps to reproduce the problem

Run `machinectl --machine={id} shell /bin/true`:
```
$ machinectl --machine=image-build-cacb4d3e0f06 shell /bin/true
Failed to get shell PTY: No machine '/bin/true' known
```

Calling `machinectl shell {id} /bin/true` works as expected:
```
$ machinectl shell image-build-cacb4d3e0f06 /bin/true
Connected to machine image-build-cacb4d3e0f06. Press ^] three times within 1s to exit session.

Connection to machine image-build-cacb4d3e0f06 terminated.
```

**Comment by lucaswerkmeister** [comment]
I don’t think that’s what the `--machine` option means. That option is common to several systemd tools and means “run the same command on another machine”. So `machinectl -M machine1 shell machine2` should mean “run a shell on `machine1`’s `machine2`”.

**Comment by zealws** [comment]
That's confusing. If that's the intended behavior can we update the `--help` or man page with details?

**Comment by poettering** [comment]
@lucaswerkmeister's explanation is right. But we should probably clarfiy that explicitly in the documentation somewhere.
