### ISSUE TITLE
machinectl shell should respond with non-zero exit code if the command fails

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#6628]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233

### Used distribution

> CentOS 7

### In case of bug report: Expected behaviour you didn't see

> `machinectl shell` should respond with non-zero exit code if the shell command fails

### In case of bug report: Unexpected behaviour you saw

> `machinectl shell` responds with exit code 0 always.

### In case of bug report: Steps to reproduce the problem

```
$ sudo machinectl shell image-build-d5198ede62b8 /bin/false
Connected to machine image-build-d5198ede62b8. Press ^] three times within 1s to exit session.

Connection to machine image-build-d5198ede62b8 terminated.
$ echo $?
0
$ sudo machinectl shell image-build-d5198ede62b8 /bin/true
Connected to machine image-build-d5198ede62b8. Press ^] three times within 1s to exit session.

Connection to machine image-build-d5198ede62b8 terminated.
$ echo $?
0
```

**Comment by zealws** [comment]
Per [this comment](https://github.com/systemd/systemd/issues/5879#issuecomment-299067171) I also tried `systemd-run` which is even worse, because on top of not having the exit code, we also don't have the stdout from the process.

```
$ systemd-run -M image-build-d5198ede62b8 /bin/false
Running as unit: run-u21.service
$ echo $?
0
$ systemd-run -M image-build-d5198ede62b8 /bin/echo 'hello world'
Running as unit: run-u22.service
$ echo $?
0
$ systemd-run -M image-build-d5198ede62b8 /bin/sh -c "/bin/echo 'hello world' >&2"
Running as unit: run-u23.service
$ echo $?
0
```

**Comment by lucaswerkmeister** [comment]
> I also tried `systemd-run` which is even worse

Use `--wait` to wait for the service and include the return code, and/or `--pty` to connect the terminal.

**Comment by poettering** [comment]
@lucaswerkmeister is right. "systemd-run" starts a service in the background. Use "--wait" if you want to wait for it to finish, and "--pty" to get a connection to the stdin/stdout/stderr of the service you are invoking.

Closing, as this all appears to be available already and work correctly.
