### ISSUE TITLE
impossible to override/remove `PIDFile=`-directive in service file

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#6633]
### Submission type

 [x] Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

It should be possible to overwrite/remove the `PIDFile=` directive via `systemctl edit <service>` 
So If I set a `PIDFile=` it should be like the directive would have never exist in the `service` file..

### In case of bug report: Unexpected behaviour you saw

When trying to remove the `PIDFile=`-directive via adding `PIDFile=` to `override.conf` the service doesn't start due to:

`Not an absolute path,`

`systemd-analyze verify <service>.service` states the same:

`/etc/systemd/system/nrpe.service.d/override.conf:2: Not an absolute path, ignoring:`

### In case of bug report: Steps to reproduce the problem

Create a service with PIDFile directive and try to override it and try to remove/blank the `PIDFile=`-directive

**Comment by poettering** [comment]
indeed

**Comment by charles-dyfis-net** [comment]
I believe this issue was reintroduced by f9d04c3c268d1b78450256cc01332a414763d80a; it appears to be present in the Arch package systemd 240.34.

**Comment by CyberLine** [comment]
This also affects Systemd 232 under Debian stretch ...
