### ISSUE TITLE
Makefile missing "check" target and/or CONTRIBUTING out of date

### ISSUE THREAD

**Issue by genpfault** [systemd/systemd#6642]
### Submission type

 - Bug report

### systemd version the issue has been seen with

Current-ish `master`, 850c8bd7b7.

### Used distribution

Debian Stretch, `amd64`.

### In case of bug report: Expected behaviour you didn't see

The 4th bullet-point in the "Posting Pull Requests" section of `CONTRIBUTING.md` alludes to a `check` target but the top-level `Makefile` only has `all` and `install` targets.

**Comment by mbiebl** [comment]
This is by design. The Makefile shim only implements the necessary parts of https://github.com/cgwalters/build-api

**Comment by boucman** [comment]
how about leaving this open as a documentation bug ? if CONTRIBUTING says to run make check and make check doesn't work, CONTRIBUTING needs to be updated...
