### ISSUE TITLE
journalctl with merged logs ignores "-n1" and shows more than one entry

### ISSUE THREAD

**Issue by MartinVerges** [systemd/systemd#6643]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 232
> 234

### Used distribution

> Debian 9 (stretch) up 2 date

### In case of bug report: Expected behaviour you didn't see

> command is expected to only show the last line (option: -n 1) and then follow with new appearing messages (option: -f)

### In case of bug report: Unexpected behaviour you saw

> command starts with a single log line, but outdated (2 days ago) and then shortly after (1-2 Seconds) prints out all history logs.

### In case of bug report: Steps to reproduce the problem

> We have configured systemd-journal-remote on http (no SSL) to receive the logs and save them to /logs (Command: /lib/systemd/systemd-journal-remote --listen-http=0.0.0.0:19531 --output=/logs/) on our other servers, we have configured systemd-journal-upload at /etc/systemd/journal-upload.conf 
>```
>[Upload]
>URL=http://10.21.0.2:19531
>```
>
> The log files are sent to the logging host (10.21.0.2 in our case) and saved to /logs without a problem. We can search the logs, use the units and all that works quite well (lovely update from rsyslog, Thank you!). To execute journalctl with the problem/bug we use the command:
>
> `journalctl -m -D /logs -n 1 -f `
>
> we expect to get the last log from our complete cluster, but instead journalctl write all the existing logs to the console
> The debug output shows that journalctl adds all the logs from /logs 
<pre>
cluster1 / $ SYSTEMD_LOG_LEVEL=debug journalctl -m -D /logs -n 1 -f
Root directory /logs added.
File /logs/remote-10.21.0.107@f9a3fd37ded24aceb9fd2955ab662dfd-00000000001a13ee-0005570b448a5576.journal added.
File /logs/remote-10.21.0.102@6127019b050e4b8d9c4f33836749c050-00000000000d9b45-000556efdebff0ab.journal added.
File /logs/remote-10.21.0.101@91356f8287dc4110b78827209bb961ea-0000000000041dda-000556c65d34a60d.journal added.

... many many more ....

File /logs/remote-10.21.0.103@f8f0c7b4bce94696b5583c6be78abe13-000000000008a4a6-000556ddb1ec575b.journal added.
File /logs/remote-10.21.0.102@6127019b050e4b8d9c4f33836749c050-000000000002c0f7-000556c5a32768f8.journal added.
File /logs/remote-10.21.0.102@6127019b050e4b8d9c4f33836749c050-00000000001050e5-000556fcd1fae5eb.journal added.
File /logs/remote-10.21.0.104@d953de47191b4ef4a479f6875378f5f7-0000000000017c66-000556bc18d8fec1.journal added.
File /logs/remote-10.21.0.106.journal added.
Journal filter: none
Reiterating files to get inotify watches established
-- Logs begin at Mon 2017-08-14 12:59:47 UTC. --
Aug 17 09:10:07 some log message
Aug 17 09:10:07 another message
Aug 17 09:10:07 and so on
</pre>
>current system date is: **_Sat Aug 19 10:17:02 UTC 2017_**

**Comment by poettering** [comment]
Any chance you can provide us with the precise set of journal files you managed to trigger this with? or even better with a minimal set that triggers that? (i.e. make a copy of all files, then remove files one by one until the issue goes away, and restore the last one again)

(if you don't want to make these logs public, maybe it would be OK to just send them to me personally?)

**Comment by MartinVerges** [comment]
Unfortunately I did not save the journal files while the problem occurred. Currently it is working as it should (without a change, maybe due to log rotate) but we try to reproduce it and provide you a test environment and backup the journal files as well.

Is there anything else that we should backup that will help you finding the cause?

**Comment by poettering** [comment]
No, the journal files should suffice.

**Comment by MartinVerges** [comment]
sorry, I'm unable to reproduce it at the moment. I will close the issue and come back (with details) if we trigger it again.
