### ISSUE TITLE
networkd: add option to configure a specific link even if it has no carrier at the moment

### ISSUE THREAD

**Issue by fpeterschmitt** [systemd/systemd#6645]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> Having an interface lxcbr0 up with configured ip address.

### In case of bug report: Unexpected behaviour you saw

> Interface lxcbr0 is down, networkctl says "no-carrier"

### In case of bug report: Steps to reproduce the problem

```
$ cat /etc/systemd/network/lxcbr0.netdev 
[NetDev]
Name=lxcbr0
Kind=bridge
```

```
$ cat /etc/systemd/network/lxcbr0.network 
[Match]
Name=lxcbr0

[Network]
DHCP=no
IPForward=yes
IPMasquerade=yes
Address=10.253.1.254/24
```

```
$ ip a
3: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 16:52:9b:3d:a4:f8 brd ff:ff:ff:ff:ff:ff
```

```
$ networkctl status lxcbr0
networkctl status lxcbr0
● 3: lxcbr0
       Link File: n/a
    Network File: /etc/systemd/network/lxcbr0.network
            Type: ether
           State: no-carrier (configuring)
      HW Address: 16:52:9b:3d:a4:f8
```

Then if i start an LXC container that uses this bridge a veth interface, it goes up with the configured IP address.

I need the interface to go up because i use dnsmasq on this interface only.

**Comment by poettering** [comment]
well, empty bridges don't have a carrier. I figure we should add a way how to tell networkd to configure a specific link even if it has no carrier.

**Comment by ssahani** [comment]
If i get this right we want to set confs in .network files without carrier  like address ?

**Comment by fpeterschmitt** [comment]
Many thanks, it works as expected.
