### ISSUE TITLE
RFE: ability to reload networkd configuration without restarting it

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#6654]
### Submission type

 - Bug report

### systemd version the issue has been seen with
232

### Expected behaviour I didn't see
Systemd-networkd doesn't support the reloading of the network configuration,hence after making the changes in the /etc/systemd/network/*.conf,I can't reload the configuration.

### Unexpected behaviour you saw
I have to restart the systemd-networkd,which is causing 2-3 secs to network to comeup.
Is there any other method apart from restart the systemd-networkd to reload the configuration.
i don't want the network to go for 2-3 secs.
I thought of doing it through RTNETLINK messages but would it be any other recommended method to do the same.

**Comment by poettering** [comment]
Yeah, we really should teach networkd to reload its configuration without a restart

**Comment by ratagupt** [comment]
Does systemd broadcast any signal when it assigns the IP address to the system?The problem which I am facing is, I don't get the intimation when systemd-dhclient completes the DHCP negotiation.
Is there a way through which I can get the notification from systemd?

**Comment by poettering** [comment]
netlink provides notifications for that, and systemd-netword-wait-online can watch for it.

**Comment by ratagupt** [comment]
Thanks Lennart for responding.
Yes it is good, when we are changing the mode of interface from STTATIC to DYNAMIC..that time after restart of systemd-networkd,I can call the systemd-netword-wait-online service..
But how do I get the notification when DHCP lease RENEW happens and system gets newIP address.

The Renew is random.

**Comment by poettering** [comment]
rtnetlink will deliver updates on all IP address changes to you, really

**Comment by ssahani** [comment]
@poettering Could you please describe what we need to do for the reloading part ?

**Comment by purpleidea** [comment]
@poettering Yes please. Reloading would be much appreciated for https://github.com/purpleidea/mgmt/

@jonathangold is working on this for our `net` resource, but we currently have to `restart`.

**Comment by ssahani** [comment]
I think this is implemented with @yuwata 's patch ?

**Comment by flokli** [comment]
@ssahani which patch? A link would help, there are quite a few ;-)

**Comment by yuwata** [comment]
v244 has `networkctl reload` and `reconfigure`.

**Comment by purpleidea** [comment]
@yuwata Awesome! If you can point us to the docs for reconfigure or the commit id that would be awesome! I looked through your commits, but you've been busy, so there were many! Thanks

**Comment by yuwata** [comment]
@flokli and @purpleidea PR #13452 achieves that.

**Comment by ncfavier** [comment]
Why does the provided `systemd-networkd.service` only run `networkctl reload` in `ExecReload`, and not `networkctl reconfigure`? If I understand correctly, both commands are required to get something equivalent to a restart?

**Comment by yuwata** [comment]
`networkctl reload` reloads .network files and reconfigure interfaces if necessary. Hence, it is sufficient.

**Comment by ncfavier** [comment]
What I'm confused about is this part in `networkctl(1)`:

> Note that even if an existing .netdev is modified […], systemd-networkd does not update […] the netdev.

Restarting would update the modified netdevs, right?

**Comment by flokli** [comment]
I'm not sure I understand. If i `systemctl restart systemd-networkd`, i need to remove the netdevs to get it to reconfigure? But `networkctl reload` does it?

**Comment by yuwata** [comment]
.netdev files only used when creating _new_ virtual interfaces. If they already exist, they are not recreated nor updated.

**Comment by flokli** [comment]
Okay, so neither `systemctl restart systemd-networkd`, nor `networkctl reload` can update existing `.netdev`s, but both would create new ones, correct?
