### ISSUE TITLE
Assertion failures are not logged after certain point when starting a service

### ISSUE THREAD

**Issue by topimiettinen** [systemd/systemd#6658]
### Submission type

 - Bug report

### systemd version the issue has been seen with
HEAD

### In case of bug report: Expected behaviour you didn't see

Systemd uses `assert()` in many places to detect internal inconsistencies. However, when starting a service, after some point of execution flow, the output from failed `assert()` does not get logged anymore, probably because `stderr` has been closed as part of preparations for launching the service. The output from failed `assert()` would be precious when debugging a problem or to just realize that there is a problem.

### In case of bug report: Unexpected behaviour you saw

Triggered `assert()` may be found in logs as SIGABRT, but that may also be easily confused with problems with service being launched and not systemd itself.

### In case of bug report: Steps to reproduce the problem

Start a service with `RootImage` that is not encrypted (see #6649).

###

I see a couple of ways how the situation could be improved:

1.  make an `assert()`-like function that can reopen the log and write the message before calling `abort()`
2.  make `stderr` always available for logging
3.  remove `assert()`s and open code similar checks

**Comment by poettering** [comment]
yeah, it's a bit nasty, but I am not sure we can do about this much. we have to close stderr at a certain point, and that point is earlier than we'd like to, due to security frameworks interfering with fds... 

changing assert() all over the place sounds less than ideal, given that we never know which internal helper function we actually call that uses it internally.

Maybe we can change assert() globally to invoke log_open() first, after all that call is idempotent? Such a change should be easy enough and be safe I think...

**Comment by poettering** [comment]
(patch very welcome, of course, as usual, hint hint)

**Comment by topimiettinen** [comment]
It seems we already redefine assert() in macro.h to call log_assert_failed(), so the only thing missing is log_open() there!

**Comment by topimiettinen** [comment]
It could still be possible that assert() does not get redefined because macro.h is not included.
```
$ find . -name '*.c' | xargs grep --files-without-match 'macro\.h' | xargs grep --files-with-matches 'assert(' | wc -l
307
```
Probably most of the matches are false positives or tests.

**Comment by poettering** [comment]
macro.h is included indirectly through most other headers... But yeah, we should really patch everything where macro.h is currently not included neither directly nor indirectly.

**Comment by topimiettinen** [comment]
I made more analysis:

Dependency files tell which files don't include 'macro.h':
```
$ find . -name '*.o.d'|xargs grep --files-without-match macro.h 
./test-bus-vtable@exe/src_libsystemd_sd-bus_test-bus-vtable.c.o.d
./test-coredump-vacuum@exe/src_coredump_test-coredump-vacuum.c.o.d
./test-libudev-sym@exe/src_test_test-libudev-sym.c.o.d
./src/core/core@sta/src_core_load-fragment-gperf-nulstr.c.o.d
./src/shared/systemd-shared-234@sha/ima-util.c.o.d
./src/shared/systemd-shared-234@sha/gunicode.c.o.d
./src/shared/systemd-shared-234@sha/mkdir-label.c.o.d
./src/shared/systemd-shared-234@sha/MurmurHash2.c.o.d
./src/shared/systemd-shared-234@sta/ima-util.c.o.d
./src/shared/systemd-shared-234@sta/gunicode.c.o.d
./src/shared/systemd-shared-234@sta/mkdir-label.c.o.d
./src/shared/systemd-shared-234@sta/MurmurHash2.c.o.d
./src/basic/basic@sta/gunicode.c.o.d
./src/basic/basic@sta/mkdir-label.c.o.d
./src/basic/basic@sta/MurmurHash2.c.o.d
./test-libsystemd-sym@exe/src_test_test-libsystemd-sym.c.o.d
./test-bus-vtable-cc@exe/src_libsystemd_sd-bus_test-bus-vtable-cc.cc.o.d
```

Ignoring the tests and load-fragment-gperf-nulstr. Indeed, the files do not include 'macro.h' at least directly:
```
$ grep macro.h src/shared/ima-util.c src/basic/gunicode.c src/basic/mkdir-label.c src/basic/MurmurHash2.c
```
But they also don't use assert():
```
$ grep assert src/shared/ima-util.c src/basic/gunicode.c src/basic/mkdir-label.c src/basic/MurmurHash2.c
```

So the situation seems to be good.
