### ISSUE TITLE
When sd-bus certificating timeout， systemd has a memleak on sd-bus wqueue

### ISSUE THREAD

**Issue by hexiaowen** [systemd/systemd#6668]
### Submission type

 - Bug report

### systemd version the issue has been seen with

>systemd-219, it seams work wrong in all version

### Used distribution

> CentOS 7.3

### In case of bug report: Expected behaviour you didn't see

> it works fine, do not exist memleak.

### In case of bug report: Unexpected behaviour you saw

> When construct the sd-bus certificating timeout, we find that the state of sd-bus will always be BUS_AUTHENTICATING. Finally，The event callback will be set to disabled. The sd-bus will not be close forever, when a large number of signals come,  systemd has a memleak. RSS gets 13G.

### In case of bug report: Steps to reproduce the problem

> Gdb debug systemd,
Set a breakpoint at bus_socket_process_authenticating,
Hold for more than 25 seconds and then to continue, 
so repeated, we will find a lot of private socket has been in a connected state， and will not close.

**Comment by hexiaowen** [comment]
I have a solution that seems to work fine.

```
diff --git a/src/libsystemd/sd-bus/bus-socket.c b/src/libsystemd/sd-bus/bus-socket.c
index ab56ef4..255ff95 100644
--- a/src/libsystemd/sd-bus/bus-socket.c
+++ b/src/libsystemd/sd-bus/bus-socket.c
@@ -1057,8 +1057,10 @@ int bus_socket_process_authenticating(sd_bus *b) {
         assert(b);
         assert(b->state == BUS_AUTHENTICATING);

-        if (now(CLOCK_MONOTONIC) >= b->auth_timeout)
+        if (now(CLOCK_MONOTONIC) >= b->auth_timeout)  {
+		b->state = BUS_CLOSING;
                 return -ETIMEDOUT;
+	}

         r = bus_socket_write_auth(b);
         if (r != 0)
--
1.8.3.1
```

**Comment by yuwata** [comment]
What do you think about the following.
```
diff --git a/src/libsystemd/sd-bus/sd-bus.c b/src/libsystemd/sd-bus/sd-bus.c
index 261152b9b..94a769b45 100644
--- a/src/libsystemd/sd-bus/sd-bus.c
+++ b/src/libsystemd/sd-bus/sd-bus.c
@@ -2653,7 +2653,7 @@ static int bus_process_internal(sd_bus *bus, bool hint_priority, int64_t priorit
 
         case BUS_AUTHENTICATING:
                 r = bus_socket_process_authenticating(bus);
-                if (IN_SET(r, -ENOTCONN, -ECONNRESET, -EPIPE, -ESHUTDOWN)) {
+                if (IN_SET(r, -ENOTCONN, -ECONNRESET, -EPIPE, -ESHUTDOWN, -ETIMEDOUT)) {
                         bus_enter_closing(bus);
                         r = 1;
                 } else if (r < 0)
```

**Comment by hexiaowen** [comment]
It also work fine.
but it will not return a meaningful  value to event callback. 
 ```
      if (r < 0) {
                if (s->description)
                        log_debug_errno(r, "Event source '%s' returned error, disabling: %m", s->description);
                else
                        log_debug_errno(r, "Event source %p returned error, disabling: %m", s);
        }
```
and there is another way. do a try when timeout, but io_callback is set to disable 

```
diff --git a/src/libsystemd/sd-bus/bus-socket.c b/src/libsystemd/sd-bus/bus-socket.c
index ab56ef4..255ff95 100644
--- a/src/libsystemd/sd-bus/bus-socket.c
+++ b/src/libsystemd/sd-bus/bus-socket.c
@@ -1057,8 +1057,10 @@ int bus_socket_process_authenticating(sd_bus *b) {
         assert(b);
         assert(b->state == BUS_AUTHENTICATING);

-        if (now(CLOCK_MONOTONIC) >= b->auth_timeout)
+        if (now(CLOCK_MONOTONIC) >= b->auth_timeout)  {
+		 b->auth_timeout = now(CLOCK_MONOTONIC) + BUS_DEFAULT_TIMEOUT;
                 return -ETIMEDOUT;
+	}

         r = bus_socket_write_auth(b);
         if (r != 0)
--
1.8.3.1
```

**Comment by hexiaowen** [comment]
This is obviously a bug. Does anyone have a better suggestion? 
In my scenario, this is a serious problem that will lead to a lot of memory leaks.

**Comment by poettering** [comment]
I am not sure I fully grok what you are trying to say. Can you prep a minimal reproducer C program? 

You posted this against 219, which is ancient, and in fact we don't track bugs against such old systemd versions here. Any chance you can retest this against 234, and report back? There's a good chance it is already fixed there.

**Comment by poettering** [comment]
Let's close this now. Please reopen if there's something left to fix please provide a minimal reproducer C tool, and test this against current systemd, please, 219 is really too old!
