### ISSUE TITLE
RFE: journal-remote: determine output filename based on the hostname in the journal entries

### ISSUE THREAD

**Issue by rburchell** [systemd/systemd#6675]
### Submission type

 - Bug report

### systemd version the issue has been seen with
systemd-233, but the issue is still present in upstream git

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

    cat foo | systemd-journal-remote --output . -

should work correctly

### In case of bug report: Unexpected behaviour you saw

It does not:

    For SplitMode=none, output must be a file.

### Cause of the problem

* arg_split_mode defaults to JOURNAL_WRITE_SPLIT_HOST. So far so good.
* "-" is placed into arg_files, for later use as stdin (https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L1476). So far so good.
* This leads to type_a being set, as arg_files is no longer empty. Hmm... https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L1479
* Which then (confusingly, and unconditionally) overwrites arg_split_mode with JOURNAL_SPLIT_MODE_NONE: https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L1495. Ah, that's not good...

This is probably not what we wanted, and this actually breaks one of the manpage's provided examples:

    journalctl -o export | systemd-journal-remote -o /tmp/dir -

**Comment by rburchell** [comment]
The same issue affects `--getter` of course, since it also sets type_a. I think this means that split-mode is totally broken unless you're using HTTP fetching.

**Comment by yuwata** [comment]
I think this is a documentation issue. All your use cases are 'active' mode. The man page systemd-journal-remote(8) states as follows.
```
In case of "active" sources, the output file name must always be given explicitly.
```

**Comment by rburchell** [comment]
I suppose, although I find that to be pretty nonsensical. Why can't I create my own passive service pushing data on stdin? That just means that I need to perform the same splitting to file myself, and use multiple systemd-journal-remote invocations per-split-source.

**Comment by yuwata** [comment]
I may misunderstand your point, but do you want to get splitted outputs even if an input is given by a pipe? If so, in that case, what should determine the output filename? Currently, in the active mode, the name is determined by the url if it is specified.

**Comment by rburchell** [comment]
Right, that's what I was experimenting with. I'm not sure I'll actually do it, as I'm not sure what the real value of splitting journals is.

Anyway, my expectation was, based on the documentation of --split-mode:

    One of none or host. For the first, only one output journal file is used. For the latter, a separate output file is used, based on the hostname of the other endpoint of a connection.

... would be that they'd have been split based on the host information being sent in, e.g. host1.journal, host2.journal, etc.

**Comment by yuwata** [comment]
Do you want journal-remote to determine the filename by the hostname contained in the journal entries sent through a pipe or getter? But it is usual case that the hostname is changed. E.g., when a system boots with an initramfs created by dracut with nohostonly option, initially the hostname is localhost.localdomain, and is changed after the system reads /etc/hostname or gets hostname by dhcp... Anyway, I think this is a RFE, not a bug. The man page fix is already proposed.

**Comment by rburchell** [comment]
For what it's worth I think it's fine to close this unless someone intends to work on it. I probably won't (I'll just stick with a merged journal), and I don't mind it being closed.
