### ISSUE TITLE
systemctl(1): does not reset terminal colours after "--no-pager" is used.

### ISSUE THREAD

**Issue by Head-on-a-Stick** [systemd/systemd#6684]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234.11-8

### Used distribution

> Arch Linux

### Expected behaviour you didn't see

> The foreground colour (`tput`'s _setaf_ option) should be reset after the output.

### Unexpected behaviour you saw

> The foreground colour remained at whatever the last line of the `systemctl` output had been set to.

### Steps to reproduce the problem

> First use `tput setaf 1` to set foreground colour to red.
> Then run `systemctl list-unit-files --state=enabled --no-pager`, the last line is green (for enabled units).
> Note that the prompt and foreground colour have now been set to green rather than returned to red.

**Comment by poettering** [comment]
Indeed! Patch pending in #6688.
