### ISSUE TITLE
RFE: systemd.{service|exec} option for coredump_filter

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#6685]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

231-17.fc25

### Used distribution

fc25

### In case of bug report: Expected behaviour you didn't see

I wanted to exclude private hugepages from core dumps.

The following does achieve this:

<pre>
[Service]
ExecStartPost=/bin/bash -c 'echo $(( $(&lt;/proc/$MAINPID/coredump_filter) & ~(1 &lt;&lt; 4)  )) &gt;  /proc/$MAINPID/coredump_filter'
</pre>

Obviously a low pri RFE as a workaround exists. Up to you if you consider this as core systemd option is neater/useful.

**Comment by poettering** [comment]
Sounds like something useful to have

**Comment by grooverdan** [comment]
thank you @keszybz and @poettering
