### ISSUE TITLE
Implement noswap kernel command line option (for systemd-fstab-generator)

### ISSUE THREAD

**Issue by rhertzog** [systemd/systemd#6686]
This is a RFE. On Debian with sysvinit, you could pass "noswap" and the startup sequence would never call "swapon -a". This was used notably by Kali as part of our "forensic" boot menu entry where we try to limit the amount of changes made to the system since the last use.

Systemd currently doesn't respect that option (or any other similar option). It should be relatively easy to implement something similar in `src/fstab-generator/fstab-generator.c`.

One approach might be to add automatically a `ConditionKernelCommandLine=!noswap` to the generated .swap units.

Another approach might be to check for the kernel command line option directly in the generator and to not generate the units at all. Or to generate them but not in a path where they are dependencies of swap.target.

If you let me know which approach is the one that you want, I can try to prepare a pull request. Also do you want this option to be "noswap" or "systemd.noswap" or both?

**Comment by poettering** [comment]
I figure such a command line option would be OK to have. Not entirely sure about the name though. The kernel command line is primarily the kernel's own thing, and only secondarily userspace territory. Hence for everything we add there we should probably add a "systemd." namespace prefix, just to avoid stepping into the kernel's territory needlessly and possible provoke some name clash or so. 

On top of that, I really don't like "negated" options, i.e. "noswap=no" with its double "no" is just weird. Hence, I'd just call this "systemd.swap=no". Use proc_cmdline_get_bool() or so for parsing this.

Hope that makes sense?

**Comment by rhertzog** [comment]
> Hope that makes sense?

Fine so far. What approach do you prefer? Generating swap units but not enabling them (i.e. not making them dependencies of swap.target)? Or not generating the units at all?

Since you point me to `proc_cmdline_get_bool()` I assume that you rule out adding `ConditionKernelCommandLine=!systemd.swap=no` to the generated units.

Once this is clarified, I can work on a patch but it might take some time as it's not yet on top of my TODO list.

**Comment by poettering** [comment]
> Fine so far. What approach do you prefer? Generating swap units but not enabling them (i.e. not making them dependencies of swap.target)? Or not generating the units at all?

I think the better choice would be to not generate them at all.

**Comment by keszybz** [comment]
I'd prefer to keep backwards compatibility. If debian uses "noswap", then realistically, the name cannot be used for anything for the next ten years without a lot of pain.

**Comment by poettering** [comment]
if this is indeed a widely implemented option name then i figure we can support that name

**Comment by boucman** [comment]
generating them would make it a bit easier for user to reactivate them manually... but that's more a philosophical question than anything...

**Comment by poettering** [comment]
if people ask for them to be disabled they most likely are allergic to systemd managing swap for them. Hence i think we should really stay away as far as we can from swap devices in that case, and that's mean not creating any units for them.
