### ISSUE TITLE
systemd requires dependency does not start

### ISSUE THREAD

**Issue by romfreiman** [systemd/systemd#6687]
Versions:
- systemd219
- centos7.3 
- Kernel: 3.10.0-514.10.2.el7

I have a service named events-agent the Requires docker and After strato-noded. Also, it's enabled.

[root@stratonode0 ~]# grep -r '' /usr/lib/systemd/system/events-agent.service*
/usr/lib/systemd/system/events-agent.service:[Unit]
/usr/lib/systemd/system/events-agent.service:Description=Events Node Agent
/usr/lib/systemd/system/events-agent.service:After=docker.service
/usr/lib/systemd/system/events-agent.service:Requires=docker.service
/usr/lib/systemd/system/events-agent.service:
/usr/lib/systemd/system/events-agent.service:[Service]
/usr/lib/systemd/system/events-agent.service:Type=simple
/usr/lib/systemd/system/events-agent.service:ExecStartPre=-/usr/bin/docker-service-stop.sh events-agent.yml
/usr/lib/systemd/system/events-agent.service:ExecStart=/usr/bin/docker-service-start.sh events-agent.yml events-agent.stratolog
/usr/lib/systemd/system/events-agent.service:ExecStop=/usr/bin/docker-service-stop.sh events-agent.yml
/usr/lib/systemd/system/events-agent.service:
/usr/lib/systemd/system/events-agent.service:Restart=on-failure
/usr/lib/systemd/system/events-agent.service:StartLimitInterval=0
/usr/lib/systemd/system/events-agent.service:TimeoutStartSec=0
/usr/lib/systemd/system/events-agent.service:
/usr/lib/systemd/system/events-agent.service:[Install]
/usr/lib/systemd/system/events-agent.service:WantedBy=multi-user.target
/usr/lib/systemd/system/events-agent.service.d/dependencies.conf:[Unit]
/usr/lib/systemd/system/events-agent.service.d/dependencies.conf:After=strato-noded.service
/usr/lib/systemd/system/events-agent.service.d/watch.conf:[Service]
/usr/lib/systemd/system/events-agent.service.d/watch.conf:StartLimitInterval=0
/usr/lib/systemd/system/events-agent.service.d/watch.conf:StartLimitBurst=0
/usr/lib/systemd/system/events-agent.service.d/watch.conf:RestartSec=5
/usr/lib/systemd/system/events-agent.service.d/watch.conf:Restart=always
/usr/lib/systemd/system/events-agent.service.d/watch.conf:StartLimitAction=none

also, strato-noded service runs few services later after docker.

During the startup, docker fails to start, and I get the following error regrading events-agent service:
Aug 29 10:02:33 localhost.localdomain systemd[1]: Dependency failed for Events Node Agent.
Aug 29 10:02:33 localhost.localdomain systemd[1]: Job events-agent.service/start failed with result 'dependency'.

Please note: it should not even try to run at this point (and indeed no mention of it in journal except from the message above) because strato-noded is still inactive.

Afterwards, after docker successfully started, and strato-noded as well, for an unknown reason events-agent is not autostarted

I have no idea what's going on here - and the only solution that worked for me is to remove 'Requires=docker' from events-agent - although it's wrong.

Thanks

**Comment by poettering** [comment]
Sorry, but this is a bug tracker, not a support forum, and we only track issues with current systemd versions here, and 219 is waaaay to old for that. Please contact your downstream distro or the systemd mailing list for help. The issue submission form is supposed to make clear that this really isn't the place to ask for support and the version limit, to avoid frustration.

Sorry. Closing.
