### ISSUE TITLE
documentation lies about systemd-networkd not removing pre-configured IP addresses from interfaces it manages

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#6693]
I've manage many servers running Debian Stretch around the world in different server parks. The provider of the server hardware usually pre-configures the main ethernet interface using ifupdown and it must stay this way.

Now we had to deploy quite fast some gre tunnels to an important site and thus I've decided to use systemd-networkd to create them. I was a little bit shocked that I've needed to add some eth0.network to add the Tunnel= entries. But the https://www.freedesktop.org/software/systemd/man/systemd-networkd.service.html stated that "Network configurations applied before networkd is started are not removed, and static configuration applied by networkd is not removed when networkd exits"

This sentence is complete nonsense. systemd-networkd removed all the IP addresses from the interface eth0 and now I am basically f\*ck\*d and have a lot of servers which need some kind of manual recovery.

**Comment by ghost** [comment]
The problematic commit seems to 
be https://github.com/systemd/systemd/commit/5e5b137acc7094c9a1b8e7634b426dd445688bf0

**Comment by poettering** [comment]
Ouch. The docs are really wrong on this one. We need to fix that.
