### ISSUE TITLE
RFE: add a restart option that permits explicitly flushing out the fdstore when restarting

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#6697]
right now the fdstore is always passed along when "systemctl restart" is used. Figure out a nice way to make restarts possible that flush out the fdstore between the stop and the start.

**Comment by keszybz** [comment]
`systemctl stop systemd-journald; systemctl start systemd-journald` does the trick. I think this is good enough. This operation is probably only useful for debugging, so I don't think we need to add special support for it.
