### ISSUE TITLE
RFE: Optimizing /tmp/systemd-private* (and possibly other systemd /tmp directories/files)

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#6700]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> `systemd-233-6.fc26.x86_64`

### Used distribution

> `Fedora 26`

Currently systemd creates a directory under /tmp for each service with PrivateTmp which can easily escalate into a mess.

I propose to slightly optimize this behaviour by creating subdirectories under /tmp/systemd-private/*, i.e.
```
                      ┌─/UID-service1.service-XXXXXX
/tmp/systemd-private/─┼─/UID-service2.service-XXXXXX
                      └─/UID-service3.service-XXXXXX
````
It's concievable that systemd might want to use other directories under `/tmp` in which case the best solution would be to create service directories under `/tmp/systemd/private/*`

**Comment by poettering** [comment]
/tmp is not a user facing directory. I am not sure there's much value in rearranging stuff there. That really feelds like a bikeshedding request to me...

**Comment by poettering** [comment]
So, thinking about this I very much against this change, for the reason that it introduces a new guessable name /tmp/systemd-private. If we create that dir as we need it we open up the door to a DoS attack: anything that runs earlier can just create that file (after all /tmp is world-writable) and thus make the name unavailable to the service manager, just stopping it from working. The current approach otoh uses names that always include some random token, so that they (and no prefix of them either) can be guessed ahead of time, thus removing this attack vector.

Yes, we could create the /tmp/systemd-private/ really early on, before any other code runs, and thus ensure PID 1 always owns it, but I am not sure I like that, we should really have fewer magic pre-allocated directories in /tmp, not more.

Sorry, but I think in the light of the fact this is a shared namespace and the problems any such fixed naming creates I am against this and will close this. I hope that makes some sense... Closing.

**Comment by birdie-github** [comment]
Yeat, right, let's wait a few years more before tens of daemons use PrivateTmp and then we'll enjoy a complete mess under /tmp. Strangely no other unix daemon creates multiple temporary directories under /tmp and some of them have been using known names since the inception:

In Fedora 26:
```
.ICE-unix
.X11-unix
.XIM-unix
.esd-$USERID
.font-unix
```

Extra directories in older distros:
```
gconfd-$username
ksocket-$username
orbit-$username
```
Who cares.

**Comment by mbiebl** [comment]
google for "insecure temporary file". You'll find the X11 directories among them...

**Comment by birdie-github** [comment]
@mbiebl 

Are they are still insecure or there were vulnerabilities and they all have been fixed?

Next you will tell me that systemd has never had any vulnerabilities and it cannot even have them. Right. And it's not possible to create the said directory on boot and properly isolate it?

I'm being sarcastic but your comment doesn't warrant anything less than sarcasm.

**Comment by evverx** [comment]
@birdie-github , such a change would make people do a lot of migration stuff and, to be honest, I don't think that "/tmp not being mess" sounds like something meaningful. It would be great if you could clarify what issues you are trying to solve and why you think they should be solved at all. It would also be great if you could be more specific. Thank you.

**Comment by birdie-github** [comment]
@evverx 

There can be no migration from directories whose location is not known in advance and to this date I don't know a single utility which uses/manages/etc. systemd /tmp directories. My issue is that historically each Unix daemon has had just one directory under /tmp and systemd uses many. On a second thought I feel like you may leave everything as is. I'm not going to persist any longer. I just like everything neat and tidy, that's it.

**Comment by evverx** [comment]
I'm not sure whether you consider `systemd-tmpfiles` as an utility managing `/tmp` directories or not, but you could take a look at https://github.com/systemd/systemd/blob/master/tmpfiles.d/tmp.conf where you could probably get some idea of how some home-made scripts traversing `/tmp` for whatever reason might look like.

> My issue is that historically each Unix daemon has had just one directory under /tmp and systemd uses many.

Thank you for the clarification. I see your point.

> On a second thought I feel like you may leave everything as is.

I think leaving everything as is is indeed the best course here.

**Comment by poettering** [comment]
> Strangely no other unix daemon creates multiple temporary directories under /tmp and some of them have been using known names since the inception:

Yes, and they have been traditionally been vulnerable to DoS attacks. On systemd tmpfiles has been used to pre-register these guessable subdirectories of /tmp, before untrusted users may interfere, but this only really works for late boot stuff, as tmpfiles runs relatively late. Moreover, regardless if it can be dealt with like this or not: having to special case these systems is not a good thing, it's a bad thing.

/tmp is the place for temporary directories, where applications put temporary rubbish. It's a shared namespace where apps of many origins drop their stuff. As such it is naturally not the cleanest and best organized place in the world. On top of that, systemd creates one dir for each service there, that's not particularly ugly I think but pretty easy and obvious to understand.

**Comment by poettering** [comment]
> My issue is that historically each Unix daemon has had just one directory under /tmp and systemd uses many.

That is simply not true. For example, one of the most basic commands on UNIX, which is your shell: bash creates a temporary file directly below /tmp for each here document you create, removing it after the command completed. if you create multiple here documents at the same time it will create multiple files there. and not below any subdir.

Sorry, but this assertion of yours is simply not correct.

**Comment by birdie-github** [comment]
@poettering 

> For example, one of the most basic commands on UNIX, which is your shell: bash creates a temporary file directly below /tmp for each here document you create

Bash is not a daemon. User applications may indeed create multiple files and directories in /tmp.
