### ISSUE TITLE
Systemd-udev resetting sysfs entry max_sectors_kb.

### ISSUE THREAD

**Issue by dabrace** [systemd/systemd#6702]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd --version
systemd 228
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN

### Used distribution

SLES12SP3
"Red Hat Enterprise Linux Server 7.4 (Maipo)"

### In case of bug report: Expected behaviour you didn't see

Preservation of the value stored in max_sectors_kb

### In case of bug report: Unexpected behaviour you saw

After setting sysfs entry max_sectors_kb (example echo 8 > /sys/block/sda/queue/max_sectors_kb)
and running sg_logs -t /dev/sda, the value stored in max_sectors_kb is reset to the default.

The rule /usr/lib/udev/rules.d/60-block.rules contains a watch rule that eventually calls sd_revalidate_disk.
This function is what is resetting the max_sectors_kb value.
I was hoping to have udev modified to preserve the value stored in max_sectors_kb because some
users set this value to fine-tune I/O performance.

Here is my trace in udev to the kernel.
-------------------
systemd/src/udev/udevd.c
   manager_new
       manager->fd_inotify = udev_watch_init(manager->udev);
       sd_event_add_io(manager->event, &manager->inotify_event, manager->fd_inotify, EPOLLIN, on_inotify, manager);
           on_inotify (systemd source code: src/udev/udevd.c)
              synthesize_change
                    ioctl --> BLKRRPART
                              ----------------------
                              Start of kernel code.
                              ----------------------
```
                              blkdev_ioctl (block/ioctl.c)
                                   CASE:BLKRRPART: blkdev_reread_part (block/ioctl.c)
                                         _blkdev_reread_part (block/ioctl.c)
                                                rescan_partitions (block/partition-generic.c)
                                                     if (disk->fops->revalidate_disk)
                                                         disk->fops->revalidate_disk(disk);
                                                           ----------------------------------
	                                                   sd driver (drivers/scsi/sd.c
                                                           sd_revalidate_disk
                                                           ----------------------------------
                                                          ` /*
                                                            * Use the device's preferred I/O size for reads and writes
                                                            * unless the reported value is unreasonably small, large, or
                                                            * garbage.
                                                            */
                                                           if (sdkp->opt_xfer_blocks &&
                                                               sdkp->opt_xfer_blocks <= dev_max &&
                                                               sdkp->opt_xfer_blocks <= SD_DEF_XFER_BLOCKS &&
                                                               logical_to_bytes(sdp, sdkp->opt_xfer_blocks) >= PAGE_SIZE) {
                                                                   q->limits.io_opt = logical_to_bytes(sdp, sdkp->opt_xfer_blocks);
                                                                   rw_max = logical_to_sectors(sdp, sdkp->opt_xfer_blocks);
                                                           } else
                                                                   rw_max = min_not_zero(logical_to_sectors(sdp, dev_max),
                                                                                         (sector_t)BLK_DEF_MAX_SECTORS);
                                                   
                                                           /* Combine with controller limits */
                                                           q->limits.max_sectors = min(rw_max, queue_max_hw_sectors(q));

```

### In case of bug report: Steps to reproduce the problem

    ```
For a SCSI device, such as /dev/sda:
       1.  cat /sys/block/sda/queue/max_sectors_kb
       2.  echo "some different value" > /sys/block/sda/queue/max_sectors_kb
       3.  sg_logs -t /dev/sda
       4.  cat /sys/block/sda/queue/max_sectors_kb
```
-----
Real example

[root@trafferth queue]# pwd
/sys/block/sda/queue
[root@trafferth queue]# !echo
echo 128 > max_sectors_kb
[root@trafferth queue]# !cat
cat max_sectors_kb 
128
[root@trafferth queue]# !sg
sg_logs -t /dev/sda
    HP        LOGICAL VOLUME    3.56
Unable to find temperature in either Temperature or IE log page
[root@trafferth queue]# !cat
cat max_sectors_kb 
256

**Comment by poettering** [comment]
not sure what to do this. udev isn't really resetting this, it's the kernel. Have you contacted your downstream distros about this first? It appears to me that this is what the kernel folks have to look into.

**Comment by dabrace** [comment]
I tried to patch the SD driver. But they will not accept my patch. They
suggest a udev rule.

How would I do this?

**Comment by zdzichu** [comment]
Nb. the kernel patch thread starts at http://www.spinics.net/lists/linux-scsi/msg112073.html

**Comment by poettering** [comment]
This is really something the kernel guys should fix. rereading the partition table should not imply that is sysfs variable is reset. udev is *not* resetting this explicitly after all, it's the kernel that does this.

note that udev is not the only one calling this ioctl, all partitioning tools and suchlike do this. Hence, this is going to be reset at various places, and not just due to udev events really.

Let's close this here. I hope this makes sense.

Please bring this up with the kernel folks. And clarify to them that udev is *not* resetting this due to udev rules, but it's the ioctl to reread the part table in itself.

As a local work-around you might be able to set the sysfs attr from an udev rule, after all rereading the partition table should result in udev events after the fact. That way the ioctl would reset the value, but the udev rule would patch it back right after. i.e. udev can be the tape that fixes the kernel's misbehaviour in this case for you. It's super ugly of course, and the kernel really shouldn't do what it is doing in the first place, but it should work as a work-around. And it would fix the ioctl for you even if something else (such as parted/fdisk/…) call it.

Anyway, closing, I hope the above makes some sense.
