### ISSUE TITLE
systemd-update-done service doesn't honor sysconfdir and localstatedir (hardcodes /etc and /var)

### ISSUE THREAD

**Issue by clopez** [systemd/systemd#6716]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> master (git sha1  6c1f72f626355615daee0e5a7ef7044759251a23 )

### Used distribution

> Yocto / poky / open-embedded

###  Description

update-service-done stores/checks for the .updated files always in /etc and /var directories. 
I think it should do that instead on the values given at configure/build time for sysconfdir and localstatedir

Relevant files:
https://github.com/systemd/systemd/blob/6c1f72f626355615daee0e5a7ef7044759251a23/units/systemd-update-done.service.in#L15
https://github.com/systemd/systemd/blob/6c1f72f626355615daee0e5a7ef7044759251a23/src/update-done/update-done.c#L72

**Comment by poettering** [comment]
Sorry, but thisis on purpose, we don#t support these paths to be moved around. We do make certain requirements how the system is set up, and oneis that /etc is named /etc and not /foobar...

Sorry, but I hope that makes some sense.
