### ISSUE TITLE
systemd-resolved stub resolver breaks nsupdate with gssapi

### ISSUE THREAD

**Issue by akarl10** [systemd/systemd#6727]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 234

### Used distribution

> Ubuntu Artful

### In case of bug report: Expected behaviour you didn't see

> nsupdate -g updating the rr on the master dns server

### In case of bug report: Unexpected behaviour you saw

nsupdate -g -d
> update add test.domain.example 900 IN A 10.0.0.1
> 
Reply from SOA query:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id:  13540
;; flags: qr rd ra; QUESTION: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;test.domain.example.                        IN      SOA

Reply from SOA query:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id:  38062
;; flags: qr rd ra; QUESTION: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;domain.example.                     IN      SOA

;; ANSWER SECTION:
domain.example.              3562    IN      SOA     ns1.domain.example. hostmaster.domain.example. 1062 900 600 86400 3600

Found zone name: domain.example
The master is: ns1.domain.example
start_gssrequest
Found realm from ticket: DOMAIN.EXAMPLE
send_gssrequest
Outgoing update query:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id:  62733
;; flags:; QUESTION: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; QUESTION SECTION:
;3545491293.sig-ns1.domain.example. ANY TKEY

;; ADDITIONAL SECTION:
3545491293.sig-ns1.domain.example. 0 ANY TKEY   gss-tsig. 1504345487 1504345487 3 NOERROR 1398 -some very long base64 encoded string- 0

; Communication with 127.0.0.53#53 failed: unexpected error                                                                                                                                                    
could not reach any name server

### In case of bug report: Steps to reproduce the problem

set up a dns server that supports gssapi based rr updates and try to adding/deleting a rr using nsupdate -g (every MS AD deployment meets this requirement)
link /etc/resolv.conf to /lib/systemd/resolv.conf
in /etc/systemd/resolved.conf set DNSStubListener=yes (this is needed since for gssapi based dns updates tcp is used, the base64 encoded gssapi blob is too big for udp.

**Comment by poettering** [comment]
the local DNS stub is a minimal stub that may be used for simple resolves only. For all other operations it will return an error. It is not a full recursive DNS server, and it does not support DNS updates. If you want that, please talk directly to your upstream DNS server, or do not use resolved, as resolved is really not that.


Sorry.

**Comment by akarl10** [comment]
thats sad to hear..
In fact currently I query for the soa record of the guessed zone name, grep the master server and pass that to nsupdate.. not a good solution but currently works.

What would be very cool is if systemd-resolved could register its name in dns similar as it can announce its hostname using lldp and mdns.

Just for understanding what can and can't be done with the stub resolver:
Every query should work that does not depend on the presence (outgoing or incomming) of the additional section inside the query. Is that correct?

**Comment by ott** [comment]
I'm not sure what type of queries nsupdate sends but shouldn't systemd-resolved just forward the queries according to RFC 5625?

**Comment by akarl10** [comment]
Well, I'm not sure if systemd-resolve defines itsef als dns proxy.

nsupdate (or the signature used by nsupdate to sign the update request) depends on the presence of the additional section. Another "problem" is that for finding the master dns server the authority section is also required. systemd-resolved drops it.

ex using systemd-resolved:
````
dig -t a nonexisting.subdomain.abc.google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t a nonexisting.subdomain.abc.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 63924
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;nonexisting.subdomain.abc.google.com. IN A

;; Query time: 135 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Dec 12 17:42:37 CET 2017
;; MSG SIZE  rcvd: 65
````
no authority section that tells me the matching SOA record. If  I query for example 9.9.9.9

````
dig -t a nonexisting.subdomain.abc.google.com @9.9.9.9

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t a nonexisting.subdomain.abc.google.com @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9408
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nonexisting.subdomain.abc.google.com. IN A

;; AUTHORITY SECTION:
google.com.             30      IN      SOA     ns1.google.com. dns-admin.google.com. 178745819 900 900 1800 60

``;; Query time: 96 msec``
``;; SERVER: 9.9.9.9#53(9.9.9.9)``
``;; WHEN: Tue Dec 12 17:44:49 CET 2017``
``;; MSG SIZE  rcvd: 115``
````

I get the master server ns1.google.com

Short: systemd-resolved seems to only forward/understand question and answer sections. Everything else seems to get dropped.

But I see systemd-resolved more as a "authoritative" DNS server that gets its data from many sources (recursive DNS, mDNS, llmnr, own hostname). Its not meant to be talking to "exotic" dns tools that need things beyond resolving A, AAAA, PTR and SRV and maybe TXT.

**Comment by ott** [comment]
I might have misunderstood RFC 2136 but shouldn't DNS UPDATE packets be sent to the primary master of the zone? Why does nsupdate use the local resolver after it found the primary master from the SOA RR of the zone?

**Comment by ott** [comment]
I think systemd-resolved can be seen as a proxy (as defined in RFC 5625) according to RFC 7719.

**Comment by akarl10** [comment]
well, nsupdate would send the dns update request to the primary master,
BUT: nsupdate does the gss/kerberos negotiation over the "local" dns server/systemd-resolved. That is why in this case nsupdate fails (see issue title)

**Comment by ott** [comment]
Can you explain your scenario in more detail? I don't understand it. Why does nsupdate not contact the primary master directly?

**Comment by akarl10** [comment]
I am not a nsupdate tool expert, but as far as I understand/traced the flow is the following:

1. find the SOA / primary master server
1. get the gss ticket/things needed to sign the update (using default dns forwarer)
1. sign the update request and send it to the primary master server

if I tell nsupdate use a specific server (using the server command) EVERYTHING is sent to that server regardless of the SOA record
if I don't, only the SIGNED update command is sent to the master server

in the first example the request that fails is this (step 2):
````
send_gssrequest
Outgoing update query:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62733
;; flags:; QUESTION: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; QUESTION SECTION:
;3545491293.sig-ns1.domain.example. ANY TKEY

;; ADDITIONAL SECTION:
3545491293.sig-ns1.domain.example. 0 ANY TKEY gss-tsig. 1504345487 1504345487 3 NOERROR 1398 -some very long base64 encoded string- 0
````

This is why I think the problem is that systemd-resolved does not forward ADDITIONAL SECTIONs.
In the ANY TKEY blobs the gss/kerberos transaction is flowing.
In ADDITIONAL SECTION the outgoing gss "packets" are embedded and in the ANSWER SECTION the incomming gss "packets" would be.
This requests are only used for getting the information needed to sing the pending update request.

Sure, it would be useful if the ISC guys would start this gss transaction using the primary master server and not the system defined dns server...

**Comment by ott** [comment]
I think this is really a problem of nsupdate. It doesn't even set the RD flag (in accordance with RFC 2930) and RFC 2930 also states that “resolvers are free to ignore any TKEY RRs they receive.” Have you tried this with other resolvers than bind?

**Comment by akarl10** [comment]
no, I only know ISC BIND nsupdate tool that supports RFC 3645.
I've not read every DNS RFC but if an RFC states TKEY RR may be ignored I can try to open a bug report on the ISC bugtracker. They already seam to have a workaround for finding the primary master without needing a authority section, so a fallback using the primary master directly also for the gss things might be a good solution. The thing with the missing RD flag is indeed strange (I've overseen that, but that seems wrong)

**Comment by ott** [comment]
Once you have opened a ticket with ISC, it might make sense to reference it here. ldns-update contacts the server from the SOA MNAME and the other server from the NS RRs of the zone, so perhaps nsupdate is wrong.

**Comment by akarl10** [comment]
https://bugs.isc.org/Public/Bug/Display.html?id=46840

**Comment by marka63** [comment]
The BIND instance being used here is several maintenance releases behind current.  The issue has already been addressed in released versions.

**Comment by poettering** [comment]
> I'm not sure what type of queries nsupdate sends but shouldn't systemd-resolved just forward the queries according to RFC 5625?

Hmm, being a "partial proxy" is something I always wanted to stay away from, since it's really nasty to handle upstream for us: as depending on the requests we actually speak to a very different server, and even differently featured server all feature probing is really really hard, and ultimately is a race to the bottom... 

Now, "partial proxies" are a reality, and I figure being one is a different thing from being a client to one, so maybe we should revisit that, and simply proxy update requests unmodified to upstream.

**Comment by poettering** [comment]
I files an RFE issue requesting such proxy behaviour now: https://github.com/systemd/systemd/issues/7628 so that we look into that eventually.

**Comment by marka63** [comment]
The simplest way to deal with different upstream behaviours when proxying is to use multiple addresses internally and have a one-to-one mapping between the local address and the upstream address.  This also allows down stream clients to see consistent behaviour of the "recursive server".

**Comment by marka63** [comment]
By one-to-one I mean this local address only ever proxies the query to a specific upstream server.  Multiple local addresses can proxy queries to a the same upstream server.  You can make use of this to provide IPv4 servers locally when there there are no IPv4 upstream with a v4 to v6 mapping as well as having a v6 to v6 mapping for the same upstream server.

**Comment by poettering** [comment]
well, resolved routes lookup requests by domain to different servers, and possible to multiple DNS servers attached to multiple interfaces in parallel to "merge" the potentially existing private zones on VPN links and such. It wills also answer some questions on its own, and makes LLMNR and mDNS available this way too. Hence, whatever you do, some requests will be answered by resolved itself or come from some other source and only a subset comes from classic upstream, unicast DNS
