### ISSUE TITLE
Give better error message for hibernate and hybrid-sleep when swap is too small

### ISSUE THREAD

**Issue by nh2** [systemd/systemd#6729]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 229

### Used distribution

> Ubuntu 16.04

### Description

When your swap is too small for your RAM (e.g. 16 GB RAM, 8 GB swap) and you try to hibernate, the error message is not helpful:

```
# systemctl hybrid-sleep
Failed to put system into hybrid sleep via logind: Sleep verb not supported
```

Would it be possible to give a better error message in this case, detailling that there's not enough swap?

**Comment by ciampix** [comment]
Confirm

**Comment by radaczynski** [comment]
same here

**Comment by MrCelticFox** [comment]
+1 to this
