### ISSUE TITLE
`bootctl remove` assertion failure

### ISSUE THREAD

**Issue by rhynix** [systemd/systemd#6753]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v234

### Used distribution

> Arch Linux

### Expected behaviour you didn't see

`bootctl remove` should remove files created by systemd-boot on the EFI system partition and remove systemd-boot from the EFI boot variables.

### Unexpected behaviour you saw

Running `bootctl remove` removes the files created by systemd-boot on the EFI system partition and then crashes with the following message:

```
Assertion 'value' failed at ../systemd-stable/src/shared/efivars.c:272, function efi_set_variable(). Aborting.
```

There were references in the EFI boot variables to systemd-boot that were not removed.

### Steps to reproduce the problem

Having the EFI system partition mounted at `/boot`, I ran:

```
bootctl --path=/boot install
```

Due to some issues selecting the startup disk on a Macbook, I ran the install command once more after a reboot, although I am not sure if this is relevant to the bug. After this, I ran:

```
bootctl --path=/boot remove
```

At this point, the bug should present itself.

### Extra information

The error message leads back to the following assertion: https://github.com/systemd/systemd/blob/6dd0e05c77/src/shared/efivars.c#L272.

Inspecting the backtrace in the generated coredump reveals that this function is called by `efi_remove_boot_option`, which uses `NULL` as the argument for the `value` parameter: https://github.com/systemd/systemd/blob/6dd0e05c77/src/shared/efivars.c#L543

This is probably the cause of the failing assertion.

**Comment by poettering** [comment]
Fix waiting in #6780.
