### ISSUE TITLE
umount /does-not-exist: Can't stat (null): Bad address

### ISSUE THREAD

**Issue by HaleTom** [systemd/systemd#6760]
### Submission type

 - Bug report

### systemd version the issue has been seen with
```
# /usr/lib/systemd/systemd --version
systemd 234
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
```

### Used distribution

Manjaro

### In case of bug report: Expected behaviour you didn't see

A message like: `/does-not-exist is not a systemd mountpoint`

### In case of bug report: Unexpected behaviour you saw

```
# ls -ld /does-not-exist
ls: cannot access '/does-not-exist': No such file or directory
# systemd-mount --umount /does-not-exist
Can't stat (null): Bad address
#
```

### In case of bug report: Steps to reproduce the problem

See above

## Comments
For scripts, it would be really useful to at least have the pathname causing this otherwise obscure error.

**Comment by fsateler** [comment]
I posted a few message improvements in #6768 , please take a look
