### ISSUE TITLE
Inconsistent service state indication from systemctl status

### ISSUE THREAD

**Issue by mikini** [systemd/systemd#6767]
### Submission type

 - Bug report

### systemd version the issue has been seen with

```
$ apt-cache policy systemd
systemd:
  Installed: 229-4ubuntu19
```
I'm posting here in spite of it being experienced on an older than two revisions because this is also a documentation issue that I have confirmed is still present in master branch as per the links below.

### Used distribution

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
### In case of bug report: Expected behaviour you didn't see

A consistent indication from *systemctl status* of whether a service is running or not.

### In case of bug report: Unexpected behaviour you saw

The [mosquitto](http://mosquitto.org/) MQTT broker on one of our servers segfaulted;
`Sep  6 16:17:48 gc-control kernel: [2617126.913439] mosquitto[29805]: segfault at 8 ip 00007f6dc41f1072 sp 00007fff2d3e9f20 error 4 in libwebsockets.so.7[7f6dc41dc000+1f000]`

Where after *systemctl status* showed;
```
sudo systemctl status mosquitto.service 
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2017-08-28 07:09:43 UTC; 1 weeks 2 days ago
     Docs: man:systemd-sysv-generator(8)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
This output exhibits an erroneous green light and confusing state of "Active: active (exited)". Had to dig into source to even [find hints on the exact meaning of the fields of the "Active:" line](https://github.com/systemd/systemd/blob/master/src/systemctl/systemctl.c#L3997); an active_state of "active" and sub_state of "exited".

[man systemctl](https://github.com/systemd/systemd/blob/master/man/systemctl.xml#L943) doesn't mention anything about an active state vs. sub state. A hint is in the [generic description in man systemd ](https://github.com/systemd/systemd/blob/master/man/systemd.xml#L300) that unit's sub states are mapped to five generalized states. However, both explicitly mention that active state ought to have been "failed" if service has experienced "crash" or "exiting with an error" which is indeed the case here.

What is the reasoning behind a service unit being in active_state "active" when it has sub_state "exited"? I see [the mapping](https://github.com/systemd/systemd/blob/master/src/core/service.c#L65) but don't find much logic to it.

### In case of bug report: Steps to reproduce the problem

The condition can be reproduced with mosquitto on Ubuntu 16.04 by just killing the mosquitto process.

```
$ systemctl status mosquitto.service 
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; bad; vendor preset: enabled)
   Active: active (running) since Thu 2017-09-07 18:29:44 CEST; 2s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 22638 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)
    Tasks: 1
   Memory: 1.8M
      CPU: 24ms
   CGroup: /system.slice/mosquitto.service
           └─22650 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Sep 07 18:29:44 hostname systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Sep 07 18:29:44 hostname mosquitto[22638]:  * Starting network daemon: mosquitto
Sep 07 18:29:44 hostname mosquitto[22638]:    ...done.
Sep 07 18:29:44 hostname systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
$ sudo kill 22650
$ systemctl status mosquitto.service 
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; bad; vendor preset: enabled)
   Active: active (exited) since Thu 2017-09-07 18:29:44 CEST; 38s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 22638 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)

Sep 07 18:29:44 hostname systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Sep 07 18:29:44 hostname mosquitto[22638]:  * Starting network daemon: mosquitto
Sep 07 18:29:44 hostname mosquitto[22638]:    ...done.
Sep 07 18:29:44 hostname systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
```
### Further comments

I recognize that mosquitto is not configured as a proper systemd service unit in this setup and that the legacy systemv init scripts are somehow involved in the interaction. Nevertheless it is very confusing and worrying that the state shown by systemctl is not indicative of the actual state of the service.

Also I find the "Active: active" terminology awkward. Why not use the "state" term, using something like "State: Active (running)", or maybe "State: Active (Substate: running)"?

**Comment by poettering** [comment]
The "LSB:" prefix in the service description indicates that your service is not a native systemd services, but a compatibility System V/LSB script. For those systemd can't know whether it is a problem if the main service process exits or not, in fact it cannot even reliably determine what the main service process is, as LSB generally carries not information about that.

Please put together a proper systemd unit file for this (or ask your vendor to do this), only then systemd can properly track the service's lifetime and do the right thing.

Or to say this differently: tracking of service states wasn't available on SysV, and we can't magically add it in if you use SysV services, because we really don't know if your service is a long-running one or not. i.e. on SysV you have short-lived services (like one which just exports some NFS dirs) and long-lived ones (like a web server), and there's no way for systemd to know of which type your specific service is, and hence we assume that the service might not be long-lived and thus a dying process is not an issue, the same way as it wasn't an issue on SysV.

Sorry. Closing.
