### ISSUE TITLE
udev tries to rename 2 groups of onboard nics to eno1/2, instead of eno3/4

### ISSUE THREAD

**Issue by Saruspete** [systemd/systemd#6774]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> RHEL 7.4

### In case of bug report: Expected behaviour you didn't see

> Have all embedded ethernet interfaces having their number as reported by BIOS (eno1, eno2, eno3, eno4).

### In case of bug report: Unexpected behaviour you saw

> The 2 copper NICs are effectively renamed to eno1 / eno2, but the 2 SFP+ NICs tried to be renamed to eno1 / eno2 too. That failed, and left them as eth0, eth1.

### In case of bug report: Steps to reproduce the problem

> Have a hardware with 2 embedded NICs of 2 different types (here, Copper and SFP+) on 2 different PCI bus. In our case, a PowerEdge R740 (Gen 14).

<details>
 <summary># grep rename /var/log/messages</summary>
systemd-udevd: could not rename interface '3' from 'eth1' to 'eno1': File exists
systemd-udevd: could not rename interface '5' from 'eth0' to 'eno2': File exists
</details>

<details>
<summary># dmidecode -t system</summary>
# dmidecode 3.0
Scanning /dev/mem for entry point.
SMBIOS 3.0 present.
                                                                                                                                                   
Handle 0x0100, DMI type 1, 27 bytes
System Information
    Manufacturer: Dell Inc.
    Product Name: PowerEdge R740
    Version: Not Specified
    Serial Number: ???????
    UUID: ????????-????-????-????-????????????
    Wake-up Type: Power Switch
    SKU Number: SKU=NotProvided;ModelName=PowerEdge R740
    Family: PowerEdge
</details>

<details>
  <summary># dmidecode -t baseboard</summary>

Handle 0x2900, DMI type 41, 11 bytes
Onboard Device
    Reference Designation: Integrated NIC 1
    Type: Ethernet
    Status: Enabled
    Type Instance: 1
    Bus Address: 0000:19:00.0
                                                                                                                                      
Handle 0x2901, DMI type 41, 11 bytes
Onboard Device
    Reference Designation: Integrated NIC 2
    Type: Ethernet
    Status: Enabled
    Type Instance: 2
    Bus Address: 0000:19:00.1

Handle 0x2902, DMI type 41, 11 bytes
Onboard Device
    Reference Designation: Integrated NIC 3
    Type: Ethernet
    Status: Enabled
    Type Instance: 3
    Bus Address: 0000:01:00.0
                                                                                                                                                                                    
Handle 0x2903, DMI type 41, 11 bytes
Onboard Device
    Reference Designation: Integrated NIC 4
    Type: Ethernet
    Status: Enabled
    Type Instance: 4
    Bus Address: 0000:01:00.1
</details>

<details>
<summary># lspci -nn | grep Ethernet</summary>
01:00.0 Ethernet controller [0200]: Intel Corporation I350 Gigabit Network Connection [8086:1521] (rev 01)
01:00.1 Ethernet controller [0200]: Intel Corporation I350 Gigabit Network Connection [8086:1521] (rev 01)
19:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ [8086:1572] (rev 01)
19:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ [8086:1572] (rev 01)
</details>

**Comment by poettering** [comment]
Sorry, but we only track issues in the two most current upstream systemd versions here. That's 233 and 234 right now, much newer than 219. We try hard to make that clear in the issue submission form, and in the contribution guidelines, to keep frustration regarding this at a minimum.

Will close this now. For older versions please ping your distro of choice.

Thank you for understanding.

**Comment by Saruspete** [comment]
Ok, case created. somebody paid by RH will have to work on it anyways :)
