### ISSUE TITLE
Spurious "Failed to propagate agent release message" messages on shutdown

### ISSUE THREAD

**Issue by opoplawski** [systemd/systemd#6777]
### Submission type

 - Bug report
### systemd version the issue has been seen with

> systemd-231-17.fc25.x86_64

### Used distribution

> Fedora 25

### In case of bug report: Unexpected behaviour you saw

> On shutdown, we often see messages like this:
> Sep  6 04:16:00 mock1 systemd[1]: Failed to propagate agent release message: Transport endpoint is not connected
> Sep  7 17:57:53 starport systemd: Failed to propagate agent release message: Connection reset by peer

This appears to be a race condition when shutting down the system dbus.  Systemd  is still trying to send messages to the dbus while at the same time shutting it down.

This poses a problem for log monitoring software like logwatch.  The above message looks like an error that should be reported, but it happens on nearly every reboot.

### In case of bug report: Steps to reproduce the problem

> Shutdown the system

**Comment by poettering** [comment]
fix waiting in #6780

**Comment by opoplawski** [comment]
Thanks for the prompt fix!
