### ISSUE TITLE
pam_systemd(sudo:session)

### ISSUE THREAD

**Issue by wimsett67** [systemd/systemd#6782]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd-234

### Used distribution

> linuxfromscratch.org

### In case of bug report: Expected behaviour you didn't see

> Being able to run gparted either directly as root or via the sudo command as a normal user after authentication was granted.

### In case of bug report: Unexpected behaviour you saw

> As root user running gparted from within the latest stable gnome you get the following:

Created symlink /run/systemd/system/-.mount &#8594; /dev/null.
Created symlink /run/systemd/system/boot.mount &#8594; /dev/null.
Created symlink /run/systemd/system/home.mount &#8594; /dev/null.
Created symlink /run/systemd/system/opt.mount &#8594; /dev/null.
Created symlink /run/systemd/system/run-user-1000.mount &#8594; /dev/null.
Created symlink /run/systemd/system/run-user-21.mount &#8594; /dev/null.
Created symlink /run/systemd/system/tmp-xdg\x2dcjg-gvfs.mount &#8594;
/dev/null.
Created symlink /run/systemd/system/tmp.mount &#8594; /dev/null.
Created symlink /run/systemd/system/var-lib-machines.mount &#8594; /dev/null.
Invalid MIT-MAGIC-COOKIE-1 key
(gpartedbin:18772): Gtk-WARNING **: cannot open display: :0
Removed /run/systemd/system/-.mount.
Removed /run/systemd/system/boot.mount.
Removed /run/systemd/system/home.mount.
Removed /run/systemd/system/opt.mount.
Removed /run/systemd/system/run-user-1000.mount.
Removed /run/systemd/system/run-user-21.mount.
Removed /run/systemd/system/tmp-xdg\x2dcjg-gvfs.mount.
Removed /run/systemd/system/tmp.mount.
Removed /run/systemd/system/var-lib-machines.mount.

As a normal user running sudo I get the following:

Sep 08 23:34:08 lfs sudo[18715]: pam_unix(sudo:session): session closed
for user root
Sep 08 23:34:08 lfs sudo[18715]: pam_systemd(sudo:session): Cannot create
session: Already running in a session
Sep 08 23:34:08 lfs sudo[18715]: pam_unix(sudo:session): session opened
for user root by cjg(uid=0)
Sep 08 23:34:09 lfs kernel: audit: type=1006 audit(1504870448.967:10):
pid=18715 uid=0 old-auid=1000 auid=0 tty=tty2 old-ses=2 ses=9 res=1
Sep 08 23:34:08 lfs sudo[18715]:      cjg : TTY=tty2 ; PWD=/home/cjg ;
USER=root ; COMMAND=/usr/sbin/gparted

### In case of bug report: Steps to reproduce the problem

> Please note that the distribution I am using compiles everything from source code with no package manager.

To reproduce this problem you would need to either log onto a normal tty as root and run gparted and you would get that error.  

You could login to the normal gnome desktop and from within gnome terminal su - to root and run gparted and get the same results.  

As a normal user you would need to have it setup so that a password dialog pops up and after successful authentication you would get the same result as above.

This was not the case with systemd-232 that I installed the exact same way last year.  I still have that system and gparted works flawlessly.

Regards,

Christopher.

**Comment by poettering** [comment]
systemd is not involved in X11 cookie authentication, which appears to be your problem. Please contact the X11 community for help, we can't help there.

> Invalid MIT-MAGIC-COOKIE-1 key
> (gpartedbin:18772): Gtk-WARNING **: cannot open display: :0

These bits are the relevant error, the pam_systemd issue may be ignored.

Closing.
