### ISSUE TITLE
systemd tries to execute non-executables under /lib/systemd/system-sleep/

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6787]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867902

man systemd-suspend.service says:
```
    Immediately before entering system suspend and/or hibernation
    systemd-suspend.service (and the other mentioned units, respectively)
    will run all executables in /usr/lib/systemd/system-sleep/ [...]
```
But systemd actually tries to execute the non-executable files in this
directory, too.  Consequently, it fails and spams syslog with permission
denied error messages.  Please fix the documentation/behaviour/my
understanding as appropriate.

**Comment by poettering** [comment]
Fix waiting in #6805
