### ISSUE TITLE
systemd service template with %i / %I in ExecStart not working

### ISSUE THREAD

**Issue by schlitzered** [systemd/systemd#679]
Hey,

i am trying to start some services via systemd service templates.

the directory structure looks like this:

```
# first instance
/home/fts/inst0/fts_inst0 <- this is the executable
/home/fts/inst0/share/user/pid <- this will be the pid file

# second instance
/home/fts/inst1/fts_inst1 <- this is the executable
/home/fts/inst1/share/user/pid <- this will be the pid file
```

so i created this service template:
# /etc/systemd/system/fts@.service

```
  [Unit]
  Description=FTS %I

  [Service]
  PIDFile=/home/fts/%i/share/users/pid

  #Type=forking
  WorkingDirectory=/home/fts/%i
  User=fts
  Group=fts

  TimeoutStartSec=5
  ExecStart=/home/fts/%i/fts_%i

  [Install]
  WantedBy=multi-user.target

```

but whenever i try to start the service i get this:

```
Jul 23 10:25:04 localhost.localdomain systemd[1]: Starting FTS inst0...
-- Subject: Unit fts@inst0.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit fts@inst0.service has begun starting up.
Jul 23 10:25:04 localhost.localdomain systemd[1]: Started FTS inst0.
-- Subject: Unit fts@inst0.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit fts@inst0.service has finished starting up.
-- 
-- The start-up result is done.
Jul 23 10:25:04 localhost.localdomain systemd[2614]: Failed at step EXEC spawning /home/fts/%i/fts_%i: No such file or directory
-- Subject: Process /home/fts/%i/fts_%i could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /home/fts/%i/fts_%i could not be executed and failed.
-- 
-- The error number returned while executing this process is 2.
Jul 23 10:25:04 localhost.localdomain systemd[1]: fts@inst0.service: main process exited, code=exited, status=203/EXEC
Jul 23 10:25:04 localhost.localdomain systemd[1]: Unit fts@inst0.service entered failed state.

```

**Comment by sztanpet** [comment]
this is documented very clearly, see systemd.service(5)

http://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=
`For each of the specified commands, the first argument must be an absolute path to an executable.`

**Comment by maticmeznar** [comment]
@poettering Is this ever going to be fixed? I just spent an hour trying to get a virtually identical scenario to work (i.e., `ExecStart=/home/%i/bin/syncthing`). ExecStart documentation also isn't clear that variables CANNOT be used in an absolute path.

**Comment by sanchezl** [comment]
try:
`ExecStart=/sbin/runuser -l fts -c "/home/fts/%i/fts_%i"`

**Comment by odinho** [comment]
Could we get an actual design decision/reply on this? As in "we explicitly disallow this because [good reasons]", or "we don't do this because it's tricky in code", or even "we just don't implement this yet" (where it should get a issue to be implemented).

I currently use `/usr/bin/time` as 'proxy', but I'd expect such workarounds to be suboptimal. Having this work as expected would make it a lot nicer.

**Comment by evverx** [comment]
@odinho , see https://github.com/systemd/systemd/issues/3061, https://github.com/systemd/systemd/pull/4835

**Comment by odinho** [comment]
@evverx : Oh, fixed 14 days ago. That's awesome, thanks!  Now just wait till this version rolls into distros ;)

**Comment by doublehp** [comment]
Documentation states: Note that the first argument (i.e. the program to execute) may not be a variable.

So, you can do something like "execstart=exec /usr/local/%p" but not "execstart=/usr/local/%p" ... or something like that.

**Comment by odinho** [comment]
@doublehp: Sure, that's also said above.  But this works now.

If the documentation stilll says this after the bug is fixed, we should update it.  I haven't tested the new `systemd` with the fix myself, I'm waiting until I get it in a distro.  Though looking forward to it ;)
