### ISSUE TITLE
DNS settings applied even on a non-first match (Match=*)

### ISSUE THREAD

**Issue by gintautassulskus** [systemd/systemd#6825]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 233
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN default-hierarchy=legacy

### Used distribution

CoreOS 1465.7.0

### In case of bug report: Unexpected behaviour you saw

Consider three configuration files under /etc/systemctl/networkd

10-eth0.network
```
[Match]
Name=eth0
[Network]
Address=x.x.x.x/y
```

10-eth1.network
```
[Match]
Name=eth1
[Network]
Address=k.k.k.k/z
```

80-initial.network
```
[Match]
Name=*
[Network]
DNS=8.8.8.8
DNS=8.8.4.4
```

Networkd does the following:
1. eth0 IP address  (10-eth0.network)
2. eth1 IP addresses  (10-eth1.network)
3. **Unexpected**: sets the DNS servers; they appear in /etc/resolv.conf (80-initial.network) 

### In case of bug report: Steps to reproduce the problem

I expected networkd to skip processing 80-initial.network.
The [docummentation](https://www.freedesktop.org/software/systemd/man/systemd.network.html) says "The first (in lexical order) of the network files that matches a given device is applied, all later files are ignored, even if they match as well".

> …

**Comment by poettering** [comment]
Most likely your distro configures 8.8.8.8 as fallback DNS servers which are used when nothing else is available. Use FallbackDNS= in resolved.conf to override them.

**Comment by gintautassulskus** [comment]
No, that is not the case. I observe the same behaviour when I set DNS=1.2.3.4.

This issue applies only to the DNS setting. Routing or Address options, that are added to "80-initial.network", are ignored as expected.

**Comment by poettering** [comment]
What does "networkctl status -a" say? And What "systemd-resolve --status"?

**Comment by gintautassulskus** [comment]
Found the culprit and it is my fault. 
Should have used "Match=eth*" instead of "Match=*".

_networkctl status -a_
```
● 1: lo
       Link File: /usr/lib64/systemd/network/99-default.link
    Network File: /etc/systemd/network/80-bootstrap.network
            Type: loopback
           State: carrier (configured)
         Address: 127.0.0.1
                  ::1
             DNS: 1.2.3.4
● 8: tun0 (VPN interface)
       Link File: /usr/lib64/systemd/network/99-default.link
    Network File: /etc/systemd/network/80-bootstrap.network
            Type: none
           State: routable (configured)
          Driver: tun
         Address: 10.8.0.1
                  fe80::e8c2:e679:85aa:54f9
             DNS: 1.2.3.4
```

Thanks for your time and sorry for the false alarm.

**Comment by poettering** [comment]
OK, closing again!
