### ISSUE TITLE
systemd in initrd gets confused somehow by valid fstab entry: `/usr /usr none bind`

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6827]
### Submission type

 - Bug report

### systemd version the issue has been seen with

* 233 from distribution package
* 234-git-something

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

Successful boot

### In case of bug report: Unexpected behaviour you saw

P.S. it would also be nice to understand why the ratelimiting hides the critical error message here, if you boot normally with plymouth :).

output without plymouth - this is what it looks like if you use rd.break=mount and exit the emergency shell immediately:

[    8.079020] audit: type=1130 audit(1505406275.452:22): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-emergency comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.083793] audit: type=1131 audit(1505406275.457:23): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-emergency comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.087792] audit: type=1130 audit(1505406275.457:24): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-pre-pivot comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.108360] audit: type=1131 audit(1505406275.484:25): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-pre-pivot comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.111071] audit: type=1130 audit(1505406275.487:26): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-sysctl comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.115082] audit: type=1131 audit(1505406275.491:27): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-sysctl comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.119659] audit: type=1130 audit(1505406275.492:28): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.123429] audit: type=1131 audit(1505406275.492:29): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.125619] audit: type=1130 audit(1505406275.493:30): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-initqueue comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.129700] audit: type=1131 audit(1505406275.493:31): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-initqueue comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.224198] systemd-journald[203]: Received SIGTERM from PID 1 (systemd).
[    8.237367] systemd[1]: No /sbin/init, trying fallback
[    8.239435] systemd[1]: Failed to execute /bin/sh, giving up: No such file or directory
[    8.241750] systemd[1]: Freezing execution.
[    8.242454] systemd: 16 output lines suppressed due to ratelimiting

output with plymouth:

[  OK  ] Stopped dracut pre-udev hook.
[  OK  ] Stopped dracut cmdline hook.
[  OK  ] Closed udev Kernel Socket.
[  OK  ] Closed udev Control Socket.
         Starting Cleanup udevd DB...
[  OK  ] Started Cleanup udevd DB.
[  OK  ] Started Setup Virtual Console.
[  OK  ] Reached target Switch Root.
         Starting Switch Root...
[    2.591975] systemd-journald[203]: Received SIGTERM from PID 1 (systemd).
[    2.603115] systemd: 19 output lines suppressed due to ratelimiting

### In case of bug report: Steps to reproduce the problem

1. `echo "/usr /usr none bind" | sudo tee -a /etc/fstab`
2. `reboot`

if you want to see the specific error message, as described above, my step 3 was to pass `rd.break=mount` on the kernel command line, and then `exit` the emergency shell when it appears.

During runtime, systemd seemed quite happy to start the generated `usr.mount`.

I think I remember seeing someone use this approach to mount a subtree as readonly, which is a weird thing you can do with bind mounts.

**Comment by arvidjaar** [comment]
@sourcejedi 
> it would also be nice to understand why the ratelimiting hides the critical error message here

Does booting with `printk.devkmsg=on` help?

**Comment by sourcejedi** [comment]
Not for learning about the main bug.  Even with kernel options `loglevel=7` or `ignore_loglevel`. It just gets the message about systemd not finding /sbin/init to show up when I booted normally with plymouth, and removes the message about rate-limiting.  Note I didn't enable any extra debugging in systemd for this report.

So it's not clear what the number of suppressed lines means, I've no idea what the extra 16 messages are supposed to be.

I noticed one more message than I quoted above: `kauditd_printk_skb: 11 callbacks suppressed`.  Close the emergency shell, then I get that message, then the flood of audit messages starting with `unit=dracut-emergency` etc.

It sounds like the kernel audit messages might be counted on our account, because the audit messages were generated by PID 1.

It does suggest we're shooting ourself in the foot by having too much written to the logbuffer (thanks to audit?), and at the same time expecting it to relay critical error messages.

Also the initial errors

[ 8.237367] systemd[1]: No /sbin/init, trying fallback
[ 8.239435] systemd[1]: Failed to execute /bin/sh, giving up: No such file or directory

seem really weird as loglevel "warning" IMO, they should be at least errors, but that wouldn't have fixed it.

We can be sure the last three messages we log here only happen once, so what we really want is to write to the console...

looks like we should have been setting `error_message` around https://github.com/systemd/systemd/blob/70b089d7dcd8fa22c86b9852417244701a4523d0/src/core/main.c#L2134

as used later in

                        manager_status_printf(NULL, STATUS_TYPE_EMERGENCY,
                                              ANSI_HIGHLIGHT_RED "!!!!!!" ANSI_NORMAL, "%s, freezing.", error_message);

**Comment by poettering** [comment]
Hmm, I figure we have the general problem here, that bind mounts on itself are probably not handled nicely by systemd right now, since they might create cyclic deps...

**Comment by sourcejedi** [comment]
Hum.  I don't know who I thought was using this / why I thought it must be a valid fstab entry, sorry.  EDIT: I think I was playing with `/usr` as a separate mount to see how that worked, but the easiest thing to try was this non-real-world idea.

I think it's more correct to say that it's a bug the system ends up "freezing", instead of failing nice and visibly when the initramfs was supposed to mount `/sysroot/usr`.  Ideally the emergency shell would appear as well.

I should really have dug out the debug messages or something.

**Comment by poettering** [comment]
> Hum. I don't know who I thought was using this / why I thought it must be a valid fstab entry, sorry.

Oh, this is actually a valid fstab entry, but we don't handle it properly. It's a way to make some path a mount point, which is entirely a valid thing to do, for example to tweak propagation settings and so on.

it's a systemd bug that we don't handle this properly
