### ISSUE TITLE
storage test regression: restarting local-fs.target with luks password prompt causes timeout and dbus failure

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#6834]
A lot of PRs landed today, and some of them (like #6819) were merged with test failures. [until 14 hours ago](https://github.com/systemd/systemd/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed) they were green, now red. The first failure is
```
LUKS device in /etc/fstab ... A dependency job for local-fs.target failed. See 'journalctl -xe' for details.
ERROR
```
This reproduces locally with the [built debs from e. g. PR 6820](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20170914_160700_910ad@/log.gz), so it's not an infra change.

I use this PR to collect more information.

**Comment by martinpitt** [comment]
I added some verbosity (debug journal level and a `journalctl -f`) to the failed test:
```diff
--- a/debian/tests/storage
+++ b/debian/tests/storage
@@ -202,6 +202,11 @@ class CryptsetupTest(FakeDriveTestBase):
     def test_luks_fstab(self):
         '''LUKS device in /etc/fstab'''
 
+        subprocess.check_call(['systemd-analyze', 'set-log-level', 'debug'])
+        p = subprocess.Popen(["journalctl", "-f"])
+        self.addCleanup(p.wait)
+        self.addCleanup(p.terminate)
+
         self.format_luks()
         with open('/etc/crypttab', 'w') as f:
             f.write('%s %s none luks,tmp\n' % (self.plaintext_name, self.device))
```
The resulting log is [here](https://gist.github.com/martinpitt/b5d5a7c08c158f9318dfadd25ef0de6a) and contains a few interesting lines, like a lot of `Failed to add job to manager : Invalid request descriptor`. When the bug happens (during `systemctl restart local-fs.target`), `dbus.service` is (being) stopped, which is the reason why a lot of stuff goes haywire.

**Comment by martinpitt** [comment]
Commit 71e0acccf from PR #6817 (the last one on the closed PR list which was green) is still good (tests succeed locally), bisecting from that.

**Comment by martinpitt** [comment]
Bisecting points to https://github.com/systemd/systemd/pull/6428/commits/f54bcca5c16bea from PR #6428. I confirm that just reverting that one on top of master fixes things, i. e. the second commit in that PR (https://github.com/systemd/systemd/pull/6428/commits/f54bcca5c1) actually seems okay.

This explains all the `Failed to get unit from sysfs name` and `Failed to add job to manager` error messages from the log above. But in doing so, it disrupts the status of existing running services somehow.

**Comment by martinpitt** [comment]
Confirmed on current Debian sid, so it's not just some old dependency on Ubuntu 16.04. I'll look for a manual reproducer on Debian and Fedora in a few hours.

**Comment by poettering** [comment]
Ouch! Sorry for merging this, and falsely accusing the ubuntu CI for being at fault! My fault! Sorry!

@martinpitt a million thanks for tracking this down!

**Comment by martinpitt** [comment]
Manual reproducer, tested on Debian sid. Make *double sure* that `sda` is indeed the device from `scsi_debug`! This simple reproducer just rewrites `crypttab` and `fstab`, so don't do this on any important machine.

```sh
modprobe scsi_debug
sleep 1
echo pass | cryptsetup --batch-mode luksFormat /dev/sda
echo 'cry1 /dev/sda none luks,tmp' > /etc/crypttab
echo '/dev/mapper/cry1 /mnt ext2 defaults 0 0' >> /etc/fstab
systemctl daemon-reload
# should generate /run/systemd/generator/local-fs.target.requires/mnt.mount → ../mnt.mount

systemctl restart local-fs.target
# Please enter passphrase for disk scsi_debug (cry1) on /mnt! → enter "pass"
# now hangs, and journalctl -f is full of stars^Werrors; list-jobs shows dev-mapper-cry1.device as hanging
# eventually it times out and dbus.service stops
```

**Comment by boucman** [comment]
@martinpitt  I have trouble reproducing... I don't know much about cryptsetup so i'm just following your instructions. 

Indeed what you do does block waiting for dev-mapper-cry1.device, but it also hangs that way when the patch is reverted... i'm confused. Can you confirm that your reproduction method works properly once you revert my patch ?

I think I have an idea what's going wrong here, but i'm afraid I'll have to use the autotesters on a PR to test properly...
