### ISSUE TITLE
RFE: support escaped double quotes in RUN and PROGRAM in udev rules

### ISSUE THREAD

**Issue by jonathanunderwood** [systemd/systemd#6835]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with
233

### Used distribution
Fedora 26

### RFE

It would be really useful to support nested and escaped ouble quotes in PROGRAM and RUN directives. For example:

```
PROGRAM!="/usr/bin/sh -c '/usr/sbin/smartctl -l scterc /dev/$parent | grep -q \"not supported\" && exit 0 || exit 1'", 
```
Is pretty much impossible to enact without this support. Nesting single quotes and escaping (i.e. `'\''not supported'\''`) doesn't work in this circumstance.

**Comment by mbiebl** [comment]
Just use a shell script

**Comment by jonathanunderwood** [comment]
Well, obviously using a shell script would work. But, it really would be nicer not to have to maintain  a separate script for simple logic like this.

**Comment by fbuihuu** [comment]
I created https://github.com/systemd/systemd/pull/6890 for this.

**Comment by jonathanunderwood** [comment]
@fbuihuu - many thanks for looking at this and working up the patch, much appreciated!
