### ISSUE TITLE
`systemctl --system daemon-reexec` makes machinectl forget about it's machines

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#684]
I use Archlinux; and it executes `systemctl --system daemon-reexec` after each systemd upgrade. This does have the undocumented side-effect that `machinectl` forgets about any nspawn-container it manages; even while the containers remain running just fine.

```
# machinectl 
MACHINE        CLASS     SERVICE
.............  container nspawn 

5 machines listed.
# systemctl --system daemon-reexec
# machinectl 
MACHINE CLASS SERVICE

0 machines listed.
```

Is this a known issue, or possibly intended?

**Comment by mbiebl** [comment]
Sounds like #376

**Comment by SjonHortensius** [comment]
Yep, I think it's actually a duplicate, the journal does indeed say `Machine xxx terminated` for all machines

**Comment by microcai** [comment]
NO, it has not been fixed. I can still confirm it on systemd-225
