### ISSUE TITLE
Can't rename network interface names

### ISSUE THREAD

**Issue by Alkaris** [systemd/systemd#6848]
### Submission type

 - Bug report

### systemd version the issue has been seen with

>229

### Used distribution

> Linux Mint 18.2

### In case of bug report: Expected behaviour you didn't see

> Can't rename network interface names in UDEV rules.

### In case of bug report: Unexpected behaviour you saw

> Network interface name didn't change to the new name as supplied in UDEV rule

### In case of bug report: Steps to reproduce the problem

> Create a new UDEV rule for USB Wireless device for RTL 8188cuS device,  ie; `70-persistent-net.rules` since it doesn't exist by default in `/etc/udev/rules.d/` in Linux Mint

My created rule;

    SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", SYSFS{address}=="<mac_id_here>", ATTR{dev_id}=="7392:7811", ATTR{type}=="1", KERNEL=="wlx74da383a0e1e", NAME="edi0"

Trying to rename stupid long interface name from `wlx74da383a0e1e` to `edi0`
USB wireless device is an Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter (rtl8188cuS), creating the above udev rule doesn't let me rename the interface to the one I specify. `SYSFS{address}==""` is where I enter the device's own MAC address, I've censored it out just for this post, plus the `ATT{dev_id}=="7392:7811"` is the device USB bus ID obviously.

I have read that if I do `ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules` or `ln -s /dev/null /etc/udev/rules.d/80-net-name-slot.rules` I can override the _"Predictable Interface Names"_, but again, udev rule `80-net-setup-link.rules` or `80-net-name-slot.rules` does not exist by default in Linux Mint, and creating said null pointer udev rule symbolic link does nothing either.

**Comment by floppym** [comment]
It is quite likely that you made a mistake in one of your criteria; please check for typos. Also, make sure that your MAC address matches exactly the value from /sys/class/net/wlx74da383a0e1e/address. I had one user who was convinced it was broken, but it turned out he was using the wrong case for the hexadecimal letters.

> udev rule 80-net-setup-link.rules or 80-net-name-slot.rules does not exist by default in Linux Mint, and creating said null pointer udev rule symbolic link does nothing either.

It that is truly the case, you should ask for help from your linux distro since they must have diverged from the default udev rules shipped with systemd.

**Comment by floppym** [comment]
> SYSFS{address}=="<mac_id_here>"

`SYSFS` is not a valid key name for a udev rule. You probably meant `ATTR{address}`.

**Comment by floppym** [comment]
> KERNEL=="wlx74da383a0e1e"

The kernel will never name your device like this, so this criterion will never match.

**Comment by Alkaris** [comment]
> It that is truly the case, you should ask for help from your linux distro since they must have diverged from the default udev rules shipped with systemd.

I'll have to go ask them yes.

> SYSFS is not a valid key name for a udev rule. You probably meant ATTR{address}.

I wasn't quite sure which to use, and some places say use `ATTR` or `SYSFS` but looks like that must be an older key name that's no longer used.

> The kernel will never name your device like this, so this criterion will never match.

If that's so, then how can I tell the kernel to name the device as I specified? Because it appears like the kernel is responsible for naming the USB Wi-Fi nano device like that, and it's not like I can go to the directory of the interface and rename it because it doesn't allow write access in those directories by anyone, not even root.

**Comment by poettering** [comment]
> If that's so, then how can I tell the kernel to name the device as I specified?

"wlx" is a prefixed used by udev's device naming in the "net_id" builtin. Which won#t take effect if you apply your rule. "wlx" is used for wlan devices with MAC address labelling.

See this:

https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

I'd recommend just dropping in a .link file changing the naming policy to what you want it to be. See https://www.freedesktop.org/software/systemd/man/systemd.link.html for details

Either way, this is not a support forum, but a bug tracker. If you are wondering how to do stuff, please direct your question to the systemd/udev mailing list, please do not use the bugtracker for that, unless you are sufficiently sure that it is a bug, which I think is not the case in this case.

Closing this now hence, thank you for understanding.
