### ISSUE TITLE
TCPSegmentationOffload=false does not disable TSO.

### ISSUE THREAD

**Issue by neheb** [systemd/systemd#6854]
My link file looks like this:

[Match]
Driver=r8152

[Link]
WakeOnLan=off
TCPSegmentationOffload=false
GenericSegmentationOffload=false

While GSO does get disabled, TSO partially gets disabled. here's what i mean:

[mangix@mangix ~]$ ethtool -k enp0s20f0u5u3 | grep seg
tcp-segmentation-offload: on
	tx-tcp-segmentation: off
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: on

tx-tcp-segmentation is what actually gets disabled and not the whole thing.

I looked at the code and it seems that the ethtool names in src/udev/net/ethtool-util.c seems to be old and outdated. For example when running tx-generic-segmentation manually in ethtool this happens:

[mangix@mangix ~]$ sudo ethtool -K enp0s20f0u5u3 tx-generic-segmentation on
Actual changes:
generic-segmentation-offload: on

Normally ethtool is silent. I was going to make a patch fixing this but wanted to hear feedback first.

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

TSO fully off

### In case of bug report: Unexpected behaviour you saw

TSO partially off

**Comment by poettering** [comment]
@ssahani something for you?

**Comment by ssahani** [comment]
tx-tcp6-segmentation is a another feature  code . RFE #6859

**Comment by Mel34** [comment]
There might be a flipped bit in your TSO logic. I've been trying to enable TSO and setting  TCPSegmentationOffload=true actually DISABLED TSO. Man page for systemd.link states

> The TCP Segmentation Offload (TSO) when true enables TCP segmentation offload. Takes a boolean value. Defaults to
           "unset".

Here is my link file:
[Match]
Driver=e1000e
[Link]
Name=enp0s25
TCPSegmentationOffload=false

And ethtool output:
tcp-segmentation-offload: on
        tx-tcp-segmentation: off
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp-mangleid-segmentation: off
        tx-tcp6-segmentation: on
generic-segmentation-offload: on
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]

It would seem that setting it to true disables it and setting it to false enables it, which is not what man page suggests.

**Comment by ssahani** [comment]
No can't reproduce it working as expected.

**Comment by Mel34** [comment]
**testing with TCPSegmentationOffload=false**

cat /etc/systemd/network/10-wired.link 

[Match]
Driver=e1000e
[Link]
Name=enp0s25
TCPSegmentationOffload=false

dmesg | grep e1000e
[    2.062978] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    2.062979] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    2.106374] e1000e 0000:00:19.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    2.199086] e1000e 0000:00:19.0 0000:00:19.0 (uninitialized): registered PHC clock
[    2.290221] e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) d0:50:99:5c:db:ca
[    2.290227] e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
[    2.290254] e1000e 0000:00:19.0 eth0: MAC: 11, PHY: 12, PBA No: FFFFFF-0FF
[    2.291282] e1000e 0000:00:19.0 enp0s25: renamed from eth0
[    4.053964] e1000e: enp0s25 NIC Link is Up 100 Mbps Full Duplex, Flow Control: Rx/Tx

**testing with TCPSegmentationOffload=true**

cat /etc/systemd/network/10-wired.link 

[Match]
Driver=e1000e
[Link]
Name=enp0s25
TCPSegmentationOffload=true

dmesg | grep e1000e
[    2.139662] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    2.139663] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    2.139778] e1000e 0000:00:19.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    2.238925] e1000e 0000:00:19.0 0000:00:19.0 (uninitialized): registered PHC clock
[    2.326804] e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) d0:50:99:5c:db:ca
[    2.326808] e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
[    2.326833] e1000e 0000:00:19.0 eth0: MAC: 11, PHY: 12, PBA No: FFFFFF-0FF
[    2.327345] e1000e 0000:00:19.0 enp0s25: renamed from eth0
[    4.093923] e1000e: enp0s25 NIC Link is Up 100 Mbps Full Duplex, Flow Control: Rx/Tx
[    4.093927] e1000e 0000:00:19.0 enp0s25: 10/100 speed: disabling TSO

ethtool -k enp0s25 | grep offload

tcp-segmentation-offload: off
udp-fragmentation-offload: off
generic-segmentation-offload: on
generic-receive-offload: on
large-receive-offload: off [fixed]
rx-vlan-offload: on
tx-vlan-offload: on
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]

This is on arch testing:
pacman -Qi systemd
Name            : systemd
Version         : 236.0-2
Description     : system and service manager
Architecture    : x86_64
URL             : https://www.github.com/systemd/systemd
Licenses        : GPL2  LGPL2.1
Groups          : base-devel
Provides        : nss-myhostname  systemd-tools=236.0  udev=236.0
Depends On      : acl  bash  cryptsetup  dbus  iptables  kbd  kmod  hwids  libcap  libgcrypt  libsystemd  libidn  lz4  pam  libelf
                  libseccomp  util-linux  xz
Optional Deps   : libmicrohttpd: remote journald capabilities
                  quota-tools: kernel-level quota management
                  systemd-sysvcompat: symlink package to provide sysvinit binaries [installed]
                  polkit: allow administration as unprivileged user [installed]
Required By     : accountsservice  colord  dhcpcd  libinput  libpulse  libwacom  media-player-info  mkinitcpio  netctl  pcmciautils
                  polkit  rtkit  subversion  systemd-sysvcompat  upower
Optional For    : None
Conflicts With  : nss-myhostname  systemd-tools  udev
Replaces        : nss-myhostname  systemd-tools  udev
Installed Size  : 18.77 MiB
Packager        : Christian Hesse <arch@eworm.de>
Build Date      : Mon Dec 18 15:02:39 2017
Install Date    : Mon Dec 18 15:22:03 2017
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature

I personally don't care if you can't reproduce and say it's working as expected, I just know that flipping the bit to FALSE made it work like it's supposed to when the bit it set to TRUE

**Comment by ssahani** [comment]
I am pretty sure this is working with current git.
```tcp-segmentation-offload: on
	tx-tcp-segmentation: on <==========================
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: on

```
```

`` sudo ethtool -k eth0 | grep tcp
tcp-segmentation-offload: on
	tx-tcp-segmentation: off <==============
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: on
```

with
```
[Match]                                                                                                                                                                                                             
MACAddress=28:d2:44:34:6f:89                                                                                                                                                                                        
                                                                                                                                                                                                                    
[Link]                                                                                                                                                                                                              
TCPSegmentationOffload=off 
```

**Comment by Mel34** [comment]
> [Link]                                                                                                                                                                                                              
TCPSegmentationOffload=off 

Is it on/off or is it true/false as per manpage?
Your output has **tx-tcp-segmenation** marked. I'm interested in output for **tcp-segmentation-offload**
My understanding was that TCPSegmentationOffload is supposed to manipulate tcp-segmentation-offload, not tx-tcp-segmentation.

**Comment by andrewchen5678** [comment]
Adding TCP6SegmentationOffload=false solves the issue for me:
cat /etc/systemd/network/0-e100efix.link
```
[Match]
Driver=e1000e

[Link]
TCPSegmentationOffload=false
TCP6SegmentationOffload=false
GenericSegmentationOffload=false
```
ethtool -k eno1  | grep seg
```
tcp-segmentation-offload: off
	tx-tcp-segmentation: off
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: off
generic-segmentation-offload: off
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-tunnel-remcsum-segmentation: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: off [fixed]
```
