### ISSUE TITLE
pid1: Requires= doesn't deactivate service when dependency fails

### ISSUE THREAD

**Issue by johnlinp** [systemd/systemd#6856]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v234

### Used distribution

Arch Linux

### Expected behaviour you didn't see

I created 2 services, `a.service` and `b.service`:

```
# cat a.service
[Service]
ExecStart=/bin/false

# cat b.service
[Unit]
Requires=a.service

[Service]
ExecStart=/bin/sleep 1000
```

where `a.service` is `b.service`'s dependency and `a.service` always fails.

After I do

```
systemctl start b.service
```

I expected to see both `a.service` and `b.service` fail.

### Unexpected behaviour you saw

I saw `a.service` failed, but `b.service` is active and running.

### More words

I asked [a question on StackOverflow about this](https://unix.stackexchange.com/questions/390898/understanding-systemd-requires-option). An answer suggested me to modify `a.service` and `b.service` into this:

```
# cat a.service
[Service]
Type=forking
ExecStart=/bin/false

# cat b.service
[Unit]
Requires=a.service
After=a.service

[Service]
ExecStart=/bin/sleep 1000
```

But I think it breaks what the man page of `systemd.unit(5)` says about `Requires=`:

> Configures requirement dependencies on other units. If this unit gets activated, the units listed here will be activated as well. If one of the other units gets deactivated or its activation fails, this unit will be deactivated.

If the behavior I mentioned in this issue is expected, I think this description of `Requires=` should be modified to be more clear about this case.

**Comment by poettering** [comment]
yupp, we should reword things in that paragraph to make this clearer.

**Comment by johnlinp** [comment]
It seems that the behavior of "`Requires=` deactivating service when dependencies fails" only occur when `After=` is specified. If this is true, I will create a pull request to reword the paragraph. Thanks.

**Comment by poettering** [comment]
> It seems that the behavior of "Requires= deactivating service when dependencies fails" only occur when After= is specified. If this is true, I will create a pull request to reword the paragraph. Thanks.

Yes, that's correct. Please do! Thanks!
