### ISSUE TITLE
machinectl pull-raw fails to get nspawn file

### ISSUE THREAD

**Issue by oneingan** [systemd/systemd#6857]
Bug report
version systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

Ubuntu 17.10 (Artful Aardvark) Daily Build [20170916]

I expect that 'machinectl pull-raw image.raw.xz' get side saved image.nspawn file
but otherwise  try to download image.raw.xz.nspawn file.

1) Generate raw image and nspawn file with mkosi. This create image.raw.xz and image.nspawn
2) Put both files in a web server
3) Try to pull-raw form web server with 'machinectl pull-raw http://webserver/image.raw --verify=no'
4) Raw image gets well but nspawn fails.

**Comment by poettering** [comment]
What's the precise error message/log output you get? Could you paste that, please?

**Comment by oneingan** [comment]
root@vagrant:~# machinectl pull-raw http://16.0.96.20/image.raw.xz --verify=no
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'http://16.0.96.20/image.raw.xz', saving as 'gitea'.
Downloading 298B for http://16.0.96.20/image.raw.xz.nspawn.
HTTP request to http://16.0.96.20/image.raw.xz.nspawn failed with code 404.
Settings file could not be retrieved, proceeding without.
Image already downloaded. Skipping download.
Download of http://16.0.96.20/image.raw.xz complete.
Created new local image 'image'.
Operation completed successfully.
Exiting.

**Comment by poettering** [comment]
Already fixed since 91359193c359180e6f9453a5afa1e68efdf2b064 which is included in 233. Please upgrade or ask your distro to backport the fix.
