### ISSUE TITLE
[systemd-networkd wireless bridging] Association problem

### ISSUE THREAD

**Issue by inattendu** [systemd/systemd#6870]
### Submission type

 - Bug report / help needeed

### systemd version the issue has been seen with

> systemd 234
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

> Parabola Linux up to date (2017-09-19)

### In case of bug report: Expected behavior you didn't see

> My Wireless card must be associated with the access point as if I don't use bridge

### In case of bug report: Unexpected behavior you saw
> journalctl -u wpa_supplicant@wlan0 -f 
> ...
> wpa_supplicant[346]: wlan0: Trying to associate with xx:xx:xx:xx:xx:xx (SSID='yyyy' freq=2462 MHz)
> wpa_supplicant[346]: wlan0: Associated with xx:xx:xx:xx:xx:xx
> wpa_supplicant[346]: wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
> wpa_supplicant[346]: wlan0: CTRL-EVENT-DISCONNECTED bssid=xx:xx:xx:xx:xx:xx reason=3
> wpa_supplicant[346]: wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=2 ssid="yyyy" auth_failures=5 duration=75 reason=CONN_FAILED

### In case of bug report: Steps to reproduce the problem
I'm using a USB dongle tested without bridge : successfully connected to the same SSID. 
> lsusb
> ...
> Bus 001 Device 003: ID 0cf3:9271 Qualcomm Atheros Communications AR9271 802.11n

I'm using the same hardware that the one used by @GreatEmerald so I used the udev rules specified in https://github.com/systemd/systemd/issues/936#issuecomment-157455694 to enable 4addr on the wireless interface.
> cat /etc/udev/rules.d/10-br-wlan.rules 
> ACTION=="add", SUBSYSTEM=="net", ATTRS{idVendor}=="0cf3", ATTRS{idProduct}=="9271", RUN+="/usr/bin/iw dev $name set 4addr on"

I'm using theeses systemd config files : 
- Rename the wireless interface to old name 
> cat /etc/systemd/network/10-wlanusb.link 
> [Match]
> MACAddress=28:24:ff:zz:zz:zz
> 
> [Link]
> Description=Open Hardware Wifi Dongle
> Name=wlan0
- Creating the bridge :
> cat /etc/systemd/network/13-VM-WLAN-BRIDGE.netdev 
> [NetDev]
> Name=br1
> Kind=bridge
- Enslaving wireless interface to the bridge
> cat /etc/systemd/network/21-wlan0.network 
> [Match]
> Name=wlan0
> 
> [Network]
> Bridge=br1
> IPForward=1
- IP configuration
> cat /etc/systemd/network/26-br1.network 
> [Match]
> Name=br1
> 
> [Network]
> DHCP=ipv4

State of systemd-networkd at boot (with another functional bridge on wired-eth)
```networkctl
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 br1              ether              no-carrier  configuring
  3 br0              ether              routable    configured
  4 wwp0s20f0u5i12   wwan               off         unmanaged 
  5 eth0             ether              carrier     configuring
  6 wlan0            wlan               no-carrier  configuring
```

I've found many threads where people mounting ARP-proxying with ebtables as in explained in the [Debian Wiki](https://wiki.debian.org/BridgeNetworkConnections#Bridging_with_a_wireless_NIC) ; but I think that my problem is above as we see in the journalctl from wpa_supplicant. 

I think I will have to play with ebtables to enable my KVM to access the wifi but i think there is a trick i missed before that.

Feel free to ask any more information.

thanks.

**Comment by inattendu** [comment]
I've found the "IPv4ProxyARP" option in the man ; this may replace ebtables ; but this is definitly not the cause of my problem. Anyway i put my config file as I've updated it.
> cat /etc/systemd/network/21-wlan0.network 
> [Match]
> Name=wlan0
> 
> [Network]
> Bridge=br1
> IPForward=1
> IPv4ProxyARP=true

I've made a test ; I can't peer with a hotspot when the 4addr param is enabled on wlan0. 
When i set a simple configuration ( no bridge & DHCP on wlan0 ) it works **only** when I remove this 4addr param but I lose the ability to enslave wlan0 to the bridge.

(following files are my simple configuration that works only without 4addr on wlan0)

> cat /etc/systemd/network/21-wlan0.network 
> [Match]
> Name=wlan0
> 
> [Network]
> DHCP=ipv4
> IPForward=1

Finaly ; this is my wpa_supplicant configuration :
> cat /etc/wpa_supplicant/wpa_supplicant-wlan0.conf 
> ctrl_interface=/var/run/wpa_supplicant
> ctrl_interface_group=0
> eapol_version=2
> ap_scan=1
> fast_reauth=1
> network={
>	ssid="yyyy"
>	psk="*****"
>	priority=1
>}

**Comment by poettering** [comment]
> [Link]
> Description=Open Hardware Wifi Dongle
> Name=wlan0

Note that this is a source of problems. You really shouldn't pick names here from the same namespace the kernel allocates names from, otherwise userspace will race against the kernel on this and it's undefined which side wins. Also see:

https://github.com/systemd/systemd/blob/master/man/systemd.link.xml#L336

**Comment by poettering** [comment]
> wpa_supplicant[346]: wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=2 ssid="yyyy" auth_failures=5 duration=75 reason=CONN_FAILED

Hmm, so networkd doesn't do wifi. And quite frankly I don't see how networkd should be the reason for this error above. It suggests more that there's something wrong with your wpa supplicant configuration.

**Comment by inattendu** [comment]
Hi, 
thank you, I will rename it to "wirelesslan0" and investigate the compatibility between wpa_supplicant & the 4addr param.

**Comment by inattendu** [comment]
Hi ! 

First thing ; I've renamed the wireless interface : 
```
cat /etc/systemd/network/10-wlanusb.link
[Match]
MACAddress=28:24:ff:zz:zz:zz

[Link]
Description=Open Hardware Wifi Dongle
Name=wirelesslan0
```

I've finally paired the wireless card with the AP ; folowing instructions in [this document](https://wireless.wiki.kernel.org/en/users/documentation/iw#using_4-address_for_ap_and_client_mode) and the man of wpa-supplicant, i've modified the wpa_supplicant systemd unit enabled for my wireless card with the '_-b_' flag
> -b br_ifname
> Optional bridge interface name. (Per interface)
``` 
cat /etc/systemd/system/multi-user.target.wants/wpa_supplicant@wirelesslan0.service 
[Unit]
Description=WPA supplicant daemon (interface-specific version)
Requires=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
Before=network.target
Wants=network.target

# NetworkManager users will probably want the dbus version instead.

[Service]
Type=simple
ExecStart=/usr/bin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-%I.conf -i%I -bbr1

[Install]
Alias=multi-user.target.wants/wpa_supplicant@%i.service
```
So the bridge is successfully created : 
```
brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.f699efaa455c	no		eth0
br1		8000.aa2da1c4fed4	no		wirelesslan0
```
The association log :  
```
journalctl -f
systemd[1]: Started WPA supplicant daemon (interface-specific version).
wpa_supplicant[995]: Successfully initialized wpa_supplicant
wpa_supplicant[995]: wirelesslan0: SME: Trying to authenticate with xx:xx:xx:xx:xx:xx (SSID='yyyy' freq=2412 MHz)
kernel: wirelesslan0: authenticate with xx:xx:xx:xx:xx:xx
kernel: wirelesslan0: send auth to xx:xx:xx:xx:xx:xx (try 1/3)
wpa_supplicant[995]: wirelesslan0: Trying to associate with xx:xx:xx:xx:xx:xx (SSID='yyyy' freq=2412 MHz)
kernel: wirelesslan0: authenticated
kernel: wirelesslan0: associate with xx:xx:xx:xx:xx:xx (try 1/3)
kernel: wirelesslan0: RX AssocResp from xx:xx:xx:xx:xx:xx (capab=0x1431 status=0 aid=14)
wpa_supplicant[995]: wirelesslan0: Associated with xx:xx:xx:xx:xx:xx
wpa_supplicant[995]: wirelesslan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
kernel: wirelesslan0: associated
wpa_supplicant[995]: wirelesslan0: WPA: Key negotiation completed with xx:xx:xx:xx:xx:xx [PTK=CCMP GTK=CCMP]
wpa_supplicant[995]: wirelesslan0: CTRL-EVENT-CONNECTED - Connection to xx:xx:xx:xx:xx:xx completed [id=2 id_str=]
kernel: br1: port 1(wirelesslan0) entered blocking state
kernel: br1: port 1(wirelesslan0) entered forwarding state
systemd-networkd[666]: wirelesslan0: Gained carrier
systemd-networkd[666]: br1: Gained carrier
kernel: wirelesslan0: Limiting TX power to 20 (20 - 0) dBm as advertised by xx:xx:xx:xx:xx:xx
```

But, the bridged interface didn't obtain IP via DHCP (time-out);
```
networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 br1              ether              degraded    configuring
  3 br0              ether              routable    configured
  4 wwp0s20f0u5i12   wwan               off         unmanaged 
  5 eth0             ether              carrier     configuring
  6 wirelesslan0     wlan               carrier     configuring


brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.f699efaa455c	no		eth0
br1		8000.aa2da1c4fed4	no		wirelesslan0


iwconfig
wirelesslan0  IEEE 802.11  ESSID:"yyyy"  
          Mode:Managed  Frequency:2.412 GHz  Access Point xx:xx:xx:xx:xx:xx
          Bit Rate=72.2 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=45/70  Signal level=-65 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:1637   Missed beacon:0
```
 I've tryed with and without the IPv4ProxyARP
```
cat 21-wlan0.network 
[Match]
Name=wirelesslan0

[Network]
Bridge=br1
IPForward=1
#IPv4ProxyARP=1
```

When I capture the frame (localy), I can see the br1 DHCP request but no response and no wlan trafic. (no request seen from promiscuous outside capture)

**Comment by yuwata** [comment]
Maybe related #9011.

**Comment by yuwata** [comment]
Not sure, but maybe fixed by setting `ProxyARPWiFi=`.

**Comment by keszybz** [comment]
It's been ages since this was reported and is hopefully fixed since a long time. Please reopen if this still occurs with recently released versions.
