### ISSUE TITLE
Process code=exited, status=237/KEYRING in LXD failing to CHOWN keyring

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#6871]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 234

### Used distribution

Ubuntu

### In case of bug report: Expected behaviour you didn't see

```
$ journalctl -f &
$ systemd-run --uid systemd-network /bin/true
...
Sep 19 16:22:06 systemd-upgrade systemd[1]: run-rcd5a513d4f8741fbb501374e7811df07.service: Main process exited, code=exited, status=0/SUCCESS
...
```

### In case of bug report: Unexpected behaviour you saw

```
Sep 19 16:23:26 systemd-upgrade systemd[381]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Failed at step KEYRING spawning /bin/true: Permission denied
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Failed to send unit change signal for run-r4ea0482f6b03407a834f6a745d37a92a.service: Transport endpoint is not connected
Sep 19 16:23:26 systemd-upgrade systemd[1]: Received SIGCHLD from PID 381 ((true)).
Sep 19 16:23:26 systemd-upgrade systemd[1]: Child 381 ((true)) died (code=exited, status=237/KEYRING)
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Child 381 belongs to run-r4ea0482f6b03407a834f6a745d37a92a.service
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Main process exited, code=exited, status=237/KEYRING
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Changed running -> failed
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Unit entered failed state.
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: Failed with result 'exit-code'.
Sep 19 16:23:26 systemd-upgrade systemd[1]: run-r4ea0482f6b03407a834f6a745d37a92a.service: cgroup is empty
```
### In case of bug report: Steps to reproduce the problem

```
$ lxc launch ubuntu-daily:a keyring-test
$ lxc exec keyring-test bash
$ journalctl -f &
$ systemd-run --uid systemd-network /bin/true
```

### About environment

This is an unprivileged (default) LXD container, and debugging this issue further proves to be difficult.
None of the error messages from setup_keyring() function appear anywhere, as I've tried sprinklinkg `log_error_errno` everywhere and i was unable to retrieve them from journal.

I then wrote a trivial function to (insecurely) write messages to `/tmp/xnox.log` and I made that file world readable and writable.

This revealed that the failure happens at `KEYCTL_CHOWN` call https://github.com/systemd/systemd/blob/master/src/core/execute.c#L2223 which results in `EACCES 13 Permission denied` at that point `getuid|gid()` are zero and uid/gid passed to `keyctl()` are those of `systemd-network`, in my case `101/103`.

I'm not sure what is happening here, or what should happen, as my keyring knowledge is limited. But imho, starting units should not fail. Is it safe to ignore EACCES and return 0, like in a few other error paths in that code? Or should the keyring be cleaned-up and removed first?

**Comment by evverx** [comment]
The same issue seems to have been discussed in https://github.com/systemd/systemd/issues/6281 where a slightly different way to skip `keyctl` was [suggested](https://github.com/systemd/systemd/issues/6281#issuecomment-314508882).

**Comment by poettering** [comment]
Closing as duplicate
