### ISSUE TITLE
PathModified in path activation propagates to containing directory when file is deleted

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#6877]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v232
v234

### Used distribution

Debian stretch
Debian sid

Downstream bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876261

given this setup:

```
   # cat beeponce.service 
   [Unit]
   Description=Beeps
   
   [Service]
   Type=oneshot
   ExecStart=/usr/bin/aplay /tmp/beep.wav
   
   
   # cat beeponce.path 
   [Unit]
   Description=Monitor /tmp/zz
   
   [Path]
   PathModified=/tmp/zz
```

This happens:

```
   touch /tmp/zz   # BEEP!   (ok)
   rm /tmp/zz      # BEEP!   (ok)
   touch /tmp/foo  # BEEP!   (What??)
   touch /tmp/foo  # silence (ok)
   touch /tmp/zz   # BEEP!   (ok)
   touch /tmp/foo  # silence (ok)
```

It looks like systemd is listening to events in the containing directory to
catch if the file is created, and after removing the file it accidentally
triggers on a directory event even if it's not about the file being monitored.

**Comment by mbiebl** [comment]
There's additional surprising behaviour, same test case as my previous
email:

```
touch /tmp/zz   # BEEP (ok)
rm /tmp/zz      # BEEP (ok)
touch /tmp/zz   # Silence (??)
touch /tmp/zz   # BEEP (ok)
rm /tmp/zz      # BEEP (ok)
touch /tmp/zz   # Silence (??)
```

So it looks like after the file being monitored has been deleted,
notification happens when activity happens in the directory for any file
except the one being monitored.

It looks like in that case there is a condition evaluated the wrong way
round.

**Comment by dtardon** [comment]
This seems to work correctly with current master.

**Comment by poettering** [comment]
OK, let's close this. if this resurfacs, reopen please, or file a new issue.
