### ISSUE TITLE
systemd-localed: permission denied

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#6878]
With v234, it seems that systemd-localed fails to open a temporary file in /etc:

> open("/etc/.#vconsole.confVrqjUK", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = -1 EACCES (Permission denied)

Here it can be simply reproduced by changing the vconsole keymap with: `localectl set-keymap fr`

This can be fixed by commenting `CapabilityBoundingSet=` in the unit file.

**Comment by poettering** [comment]
I am a bit puzzled by this. Any chance you can figure out which cap precisely makes this work for you? What's the access mode of /etc itself? do you run any MAC? (apparmor, smack, selinux)?

normally, root even without any caps should be able to create new files in /etc just fine, except if /etc is set to 0555 or so...

**Comment by fbuihuu** [comment]
> What's the access mode of /etc itself?

oops I totally forgot to check the perms of this directory and indeed something changed it to:

> drwxr-xr-x 1 fbui users 3588 Sep 21 13:06 /etc

Sorry for the noise.
