### ISSUE TITLE
systemd-tmpfiles don't work on kernel without support AT_EMPTY_PATH

### ISSUE THREAD

**Issue by shaba** [systemd/systemd#689]
Hi.
We(ALTLinux) are use systemd utils for SysV init too. For example,  rc.sysinit use systemd-modules-load,systemd-sysctl, rc.d/udev use systemd-tmpfiles.
Also, we are use old kernel ( kernel-2.6.32-ovz-042stab108.6) for openvz (with SysV + systemd-utils)
Sinse systemd-v220, after 48b8aaa82724bc2d8440470f414fb0d2416f29c7 commit, systemd-tmpfiles check AT_EMPTY_PATH and show error "Failed to fstat() file /foo: Invalid argument"

strace -P/home -P/srv systemd-tmpfiles --create /lib/tmpfiles.d/home.conf
mkdir("/home", 0755)                    = -1 EEXIST (File exists)
lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/home", O_RDONLY|O_NOFOLLOW|O_NOATIME|O_CLOEXEC|O_PATH) = 3
newfstatat(3, "", 0x7fff188ae9a0, AT_EMPTY_PATH) = -1 EINVAL (Invalid argument)
Failed to fstat() file /home: Invalid argument
close(3)                                = 0
mkdir("/srv", 0755)                     = -1 EEXIST (File exists)
lstat("/srv", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/srv", O_RDONLY|O_NOFOLLOW|O_NOATIME|O_CLOEXEC|O_PATH) = 3
newfstatat(3, "", 0x7fff188ae9a0, AT_EMPTY_PATH) = -1 EINVAL (Invalid argument)
Failed to fstat() file /srv: Invalid argument
close(3)                                = 0

**Comment by zonque** [comment]
Sorry, but 2.6.32 is well over 5.5 years old, we shouldn't work around such ancient versions.

AT_EMPTY_PATH was introduced in v2.6.39, and systemd, including all its components, currently depends on >= v3.7.

**Comment by shaba** [comment]
sorry, this dublicate #421

**Comment by zonque** [comment]
Hmm, what's the relation to #421 here?

**Comment by shaba** [comment]
old kernel without AT_EMPTY_PATH ?

**Comment by zonque** [comment]
I cannot see how #421 is about `AM_EMPTY_PATH`. Confused.

Anyway, if you want to solve this issue for you, you need to carry a patch downstream. Otherwise, I'd strongly suggest to base your system on a much newer kernel version. Relying on such an old kernel is a dead end.

**Comment by poettering** [comment]
@zonque see the comment https://github.com/systemd/systemd/issues/421#issuecomment-120627537 regarding AT_EMPTY_PATH. I think @shaba is right, it's the same issue with too old kernels that we don't support in systemd anymore.

**Comment by zonque** [comment]
Ah, sorry, in the comments. Ok then.
