### ISSUE TITLE
Unintended suspend

### ISSUE THREAD

**Issue by jeremy447** [systemd/systemd#6900]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd 233

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

My Chromebook shouldn't suspend while I'm actively using it

### In case of bug report: Unexpected behaviour you saw

My HP Chromebook 14 (Falco) sometime go to sleep without any reason. I'm on Fedora 26. I ran F23, F24, F25 without any problem in the past. The problem occur with both John Lewis and MattDevo firmware.

It seem that there is fake "Lid closed" event...

> sept. 12 19:59:30 hp systemd-logind[759]: Lid opened.
> sept. 12 19:59:30 hp systemd-logind[759]: Suspending...
> sept. 12 19:59:30 hp systemd-logind[759]: Lid closed.

### In case of bug report: Steps to reproduce the problem

I'm just using the Chromebook with Fedora 26 when it happen. Seem to happen less with JL firmware (only once that week).

Of course my lid can be "broken" and send fake event but as I said it never happened before I installed Fedora 26 and I tried to move the lid in all possible way and I never managed to trigger a "fake" event. 

Anyway these almost instant conflicting event should cancel them out. I mean systemd should wait a little bit (1s ?) before putting the pc into suspend and this for 2 reasons. The first one to avoid unwanted behaviour like this one. The second to prevent the pc to suspend itself if you change your mind (eg. you close the lid to suspend it but reopen it almost instantaneously to continue using it).

So there is a possible bug in systemd (or elsewhere but where ? libinput ?) that trigger these event without any reason and there is a possible improvement to make to handle suspend event.

I also opened a bug against libinput
https://bugs.freedesktop.org/show_bug.cgi?id=102959

Thanks !

**Comment by keszybz** [comment]
If you reopen your lid immediately, what should happen is that the machine just quickly resumes. We don't want to work around hardware or firmware issues. If you have such hardware or firmware, just mark the lid suspend button ignored in logind.conf and suspend manually.

See https://bugzilla.redhat.com/show_bug.cgi?id=1490516 for a similar issue.
