### ISSUE TITLE
systemd-run: Fedora 25 inside Fedora26 host contains incompatibility

### ISSUE THREAD

**Issue by jscotka** [systemd/systemd#6903]
## F-26 systemd version:
 systemd-233-6.fc26.x86_64

### Prepare
```
# mkdir /opt/cont
# dnf -y install --nogpgcheck --setopt=install_weak_deps=False --installroot /opt/cont --allowerasing --disablerepo=* --enablerepo=nc*  --repofrompath nc1,http://ftp.fi.muni.cz/pub/linux/fedora/linux/releases/25/Everything/x86_64/os/ procps-ng systemd dnf fedora-release nc psmisc
# systemd-nspawn --machine=cont -bD /opt/cont &
```
### Reproducer
```
# systemd-run --wait -M cont /bin/bash -c "(/bin/true)"
```
### Actual Output
```
transient service unit: Cannot set property AddRef, or unknown property.
```
### Expected Output
**Have to work well** - backward compatible interface

**Comment by poettering** [comment]
hmm, so newer systemd-run uses a concept old systemd didn't implement, and that's what you are seeing. We generally try to make sure that old clients continue to work with newer API implementations, but the reverse is not true, in particular as you use a the `--wait` option, which cannot be implemented on older systemd without races. 

Or with other words: if you use "--wait" you need to run "systemd-run" against a new systemd version. If you drop that switch it should work fine against an older version too.

Sorry!
