### ISSUE TITLE
Symlinks= in socket units can silently fail

### ISSUE THREAD

**Issue by OhNoMoreGit** [systemd/systemd#6920]
### Submission type

 - Bug report

### systemd version the issue has been seen with

 - v231, though code inspection shows the problem exists in v234

### Used distribution

 - Fedora

### Problem and steps to reproduce

The `Symlinks=` directive in socket units appears to silently ignore all errors when creating symlinks.

For example, take the following units:

```
# cat test.socket
[Socket]
ListenStream=/tmp/test-socket
Symlinks=/tmp/test-symlink-a /tmp/test-symlink-b /tmp/dir/test-symlink-c
```

Then make sure `/tmp/test-symlink-a` and `/tmp/dir/` don't exist, and that `/tmp/test-symlink-b` exists:

```
# rm -f /tmp/test-symlink-* /tmp/dir/
# echo not a symlink >/tmp/test-symlink-b
# ls -l /tmp/test-symlink-* /tmp/dir/test-symlink-*
ls: cannot access '/tmp/dir/test-symlink-*': No such file or directory
-rw-rw-r--. 1 root     root     14 Sep 27 01:39 /tmp/test-symlink-b
```

Finally, start the socket unit:

```
# systemctl daemon-reload
# systemctl start test.socket
```

If we look at what systemd has done:

```
# ls -l /tmp/test-symlink-* /tmp/dir/test-symlink-*
ls: cannot access '/tmp/dir/test-symlink-*': No such file or directory
lrwxrwxrwx. 1 root     root     16 Sep 27 01:41 /tmp/test-symlink-a -> /tmp/test-socket
-rw-rw-r--. 1 root     root     14 Sep 27 01:39 /tmp/test-symlink-b
````

We can see that systemd has successfully created only `/tmp/test-symlink-a`. The other two links failed to be created -- in one case because the filesystem entry already existed, and in the other because the containing directory did not exist.

Furthermore, systemd did not log any warnings or errors. The failed symlinks were silently ignored.

### Possible solutions

I think `Symlinks=` should be handled much like `ListenStream=` and `ListenDatagram=` do with Unix-domain sockets. That is, it should:

 - create parent directories as necessary;
 - attempt the symlink syscall; if that fails with `EEXIST`, attempt to unlink any existing entry and try the symlink again;
 - on any other error, or if the second symlink syscall fails, propagate that error back and cause the unit to fail.

Failing this, we should at least document that symlink creation is best-effort only.

**Comment by poettering** [comment]
yupp, we currently silently ignore if symlinks can't be created. Not entirely sure it should be fatal if we can't create one of the symlinks, but we at least should log about it. 

Also not sure if we should remove files that already exist, except  maybe they already are symlinks or so.

**Comment by poettering** [comment]
Prepped a patch in #6922 now. It doesn't make Symlinks= failing fatal (see commit msg for the reasoning), and it doesn't destroy pre-existing file nodes, but it does everything else you suggested. Please have a look.

**Comment by OhNoMoreGit** [comment]
I would be inclined toward making it fatal, and for it to replace any existing filesystem entries.

First, Symlinks= is the only way to provide multiple names for a socket when the service's software is limited to one listening socket. From the client's perspective, all names for a socket should behave identically. Having some names work and others not could be confusing.

And second, if RemoveOnStop=true is specified, then any of the filesystem entries mentioned by Symlinks= will be unlinked anyway when the socket unit stopped -- whether they're symlinks or not, for that matter. So it's already implied that the symlinks are "owned" by the socket unit.

My particular use case was actually the `/dev/log` link to `/run/systemd/journal/dev-log`. I had a broken initramfs that created `/dev/log` as a real socket, and after switching to the real root filesystem this was not replaced with a link, which meant all syslogging was silently broken.

Anyway, I haven't yet looked through the linked PR. I should be able to test it out soon.

**Comment by poettering** [comment]
> And second, if RemoveOnStop=true is specified, then any of the filesystem entries mentioned by Symlinks= will be unlinked anyway when the socket unit stopped -- whether they're symlinks or not, for that matter.

That's a good point. But I think this is reason to go the other way: make it destructive when RemoveOnStop= is set. See the updated version of the PR
