### ISSUE TITLE
fstab-generator: noauto still adds dependency to {remote,local}-fs.target, docs state otherwise

### ISSUE THREAD

**Issue by ThomasLamprecht** [systemd/systemd#6937]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234 (initially seen on 232, but as its "to old" I tried latest)

### Used distribution

> Proxmox VE (Debian based)

### In case of bug report: Expected behaviour you didn't see

With noauto added to a fstab entry, the remote-fs or local-fs, respectively, target should not get a dependency on this mount, see man systemd.mount:

> With noauto, this mount will not be added as a dependency for local-fs.target or remote-fs.target. This means that it will not be mounted automatically during boot, unless it is pulled in by some            other unit. The auto option has the opposite meaning and is the default.

### In case of bug report: Unexpected behaviour you saw

> \# systemctl show home-tom-shared_dev_vm.automount
> ...
> Requires=-.mount pve-guests.service
> WantedBy=remote-fs.target
> Conflicts=umount.target
> Before=remote-fs.target** home-tom-shared_dev_vm.mount umount.target
> After=-.mount** pve-guests.service
> ...

My mount is in a VM which gets started by pve-guests.service, this services depends on both -fs targets as VMs are backed by a local and/or remote storage.
With the noauto not doing what the docs states this results in a ordering cycle, which systemd breaks in a highly random fashion - instead of e.g., removing the one with the smallest amount of dependency pointing to it, thus reducing the amount of services which could fail to the smallest amount possibly - but that's another problem on itself not directly related to this report.

### In case of bug report: Steps to reproduce the problem

Add a fstab entry with 'noauto', reload systdemd daemon to trigger the fstab-generator and do a systemctl show on the generated unit (unit name can be found quite easily with `systemctl list-unit-files --type automount`) While I used a automount unit this happens to with a mount unit.

As I can workaround this by just circumventing fstab and writing my own mount/automount unit with DefaultDependcies=no it would be still nice that either the behavior is adapted to the docs or vice versa.
Also I'm not sure why the ordering cycle gets even produced, as this is an automount, fstab entry is:
> 192.168.30.57:shared/ /home/tom/shared_dev_vm/ fuse.sshfs nofail,x-systemd.automount,noauto,x-systemd.requires=pve-guests.service,user,idmap=user,follow_symlinks,identityfile=/home/xy/.ssh/id_rsa,allow_other,default_permissions,uid=1000,gid=1000 0 0

**Comment by arvidjaar** [comment]
> With the noauto not doing what the docs states

Well ... you are quoting documentation for `systemd.mount` while show configuration for automount unit. Although man page for `systemd.automount` just refers to `systemd.mount` for `/etc/fstab` options and hence you are right here.

Fact is that "noauto" is ignored for `automount` units, generated from `/etc/fstab`. It probably should not.

**Comment by ThomasLamprecht** [comment]
Hmm, as far as I understood, the _noauto_ option is a general fstab mount option which should tell systemd (or another init system for that matter) to not automatically mount this on systemd startup (or to reach the local/remote-fs targets) but only if another unit pulls it in (or naturally later if a user mounts it manually)

And then there are systemd specific .automount unit types:
> A unit configuration file whose name ends in ".automount" encodes information about a file system automount point controlled and supervised by systemd.
> [...]
> Automount units may be used to implement on-demand mounting as well as parallelized mounting of file systems.

I'd use this for on-demand mounting, as described above, and it also works well for that if I add it on a already booted machine, but the next boot systemd tries to automount it at start (no other unit pulls this in) which fails then as of the dependency cycle.

So, AFAICT, _noauto_ and _.automount_ unit differ quite in semantics - even if there name would suggest otherwise, and if I understand the goals of .automount units they normally even ***should*** be combined.
As it makes not much sense, IMO, to have on-demand mounting if it gets mounted always at boot anyways.
Just trying to explain my rationale here and my understanding of the difference between _noauto_ _.automount_ - you agreed already that this behavior should probably not be the case.

**Comment by ThomasLamprecht** [comment]
If there's agreement from the systemd side on how it really should behave, i.e., if the docs are right or the code, I can also try to assemble a pull request.
Honestly, I hope the docs are right, but I can work with both.

**Comment by michaelolbrich** [comment]
In my understanding, the documentation refers to the mount unit only. What happens to automount units is just not documented.

Also, the current behavior matches a pretty common use-case: lazy mounting filesystems only when they are needed. Changing that now would mean a lot of filesystems are no longer mounted and that will break a lot of existing setups.

I believe the problem is not the activation or ordering of the automount unit before remote-fs. What causes the problem is, that ``x-systemd.requires`` is also applied to the automount unit. I think that is unnecessary and incorrect. After all ``x-systemd.requires`` takes the place of the 'device' that is mounted. And automount units don't depend on the device for very good reasons.

**Comment by poettering** [comment]
documentation fix waiting in #7350
