### ISSUE TITLE
Add a minimum TTL configuration item for broken DNS servers (systemd.resolve)

### ISSUE THREAD

**Issue by perolausson** [systemd/systemd#6945]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Ubuntu 17.04

I have a DNS server which is dishing out responses indicating that the TTL is 0. As it is a hardware device out of warranty I can't resolve this other than replacing the whole unit, which I am reluctant to do.

It would be good, if it was possible to indicate the minimum TTL for a DNS setup in a .network file (eg. /etc/systemd/network/NNN.network and let this minimum TTL be honoured when responses indicate a lower number.

This would yield stability in local private networks where there is a mix of systemd-resolve and non-systemd based servers. At the moment, this causes intermittent problems because systemd-resolve based systems respond to UDP queries but non-systemd systems don't and there is typically a delay seen in getting a response back because the DNS servers respond with answers that are not entered into the systemd cache. I think this is in part one of the reasons why there is so much confusion about erratic behaviour in systemd-resolve based systems.

**Comment by poettering** [comment]
> At the moment, this causes intermittent problems because systemd-resolve based systems respond to UDP queries but non-systemd systems don't and there is typically a delay seen in getting a response back because the DNS servers respond with answers that are not entered into the systemd cache

Can you elaborate on this? I don't really grok what you are saying here?

What do you mean by "systemd-resolve based systems respond to UDP queries"? We only have a local DNS stub, for local programs, talking UDP. Is that what you mean?

TTL=0 according to DNS means that the data shall not be cached, and that's what resolved is doing. For RRs like that resolved should behave no different than the plain libc resolver, as there's no caching done. In which way do you see behaviour here that shouldn't be seen?

**Comment by perolausson** [comment]
What I mean is that if I have a local network like this:

Servers running ubuntu 17.04

serverA
serverB

Servers running older version of ubuntu (not running systemd.resolve or any other DNS):

oldserver

then when running queries on serverA:

case 1: serverB ok
case 2: oldserver not ok, not found or delayed response

I think this is causing in part some of the frustration for people, since they don't understand that in case 1 we get instantaneous response and for case 2 we get delayed responses (or maybe no response due to bugs in systemd).

The reason TTL=0 seems to be a problem is my guess. It gets replies but then doesn't find the answers because it never went into the cache, but I could be wrong.

**Comment by poettering** [comment]
i am sorry, but I am now even more confused what you are trying to say. Can you elaborate?

**Comment by ott** [comment]
I can confirm that systemd-resolved correctly handles answers that contain RR with TTL of 0. I think it is out of scope of a stub resolver to manipulate DNS answers. It's better to use a proper recursive resolver for that. So I'm suggesting to @poettering  to close this issue.
