### ISSUE TITLE
Sandbox: Seccomp: basic syscalls and operations should be allowed inside RootDirectory= RootImage= and container envrionment

### ISSUE THREAD

**Issue by tixxdz** [systemd/systemd#6955]
Submission type: Request for enhancement (RFE)

We should improve our seccomp syscall groups so most basic operations should work inside a new mount namespace and if running as a normal user. Right now systemd has lot of sandbox operations but after some time, it seems that these options are not really user friendly or too technical for our users.

Having multiple seccomp groups can be helpful, but for most users they just want to feel that they are secure and some operations are blocked. If something fails they will just deactivate security.

I am proposing to support a new set of syscall groups `@basic` and `@portable` where these groups are just aliases for some other syscall sets. This schema can be useful when services and apps are run inside sandboxes or namespaces by default, RootImage= is one example. We can control which resource is available inside the sandbox or the environment, how much memory the apps can have etc, so the need to block most of the syscalls is not really justified. Most basic operations should be available by default, the resources that are available on the host can be hidden inside the sandbox, nodes can be made read-only, etc. Of course not everything will be blocked, and there will be always windows for attacks, but users should be able to just use: allow `@portable` or `@basic` syscalls and run their apps instead of having to manually user a long list of technical syscall names or profiles...

The following comments are intended for this PR https://github.com/systemd/systemd/pull/6818 
I missed that PR and it does not make sense to comment on it, so lets just open a new issue and see.

Note: this model will work better when we move to the new model of portable services where we whitelist resources instead of the blacklisting model.

* For syscall `@credentials` instead of creating a new syscall group for them, I would allow them by default, so all or most of the `@credentials` set should be part of the `@default`. There are no real use cases to block such basic syscalls that do not have a deep kernel path, they are abstracted only a couple of lines, so better always allow them. After some research I really think these should be allowed.

* The `@memlock` group should be split in my opinion to two groups:
   `@basic-memory-access` => `{brk, mlock, munlock }`  => most of the time these should be allowed.
   `@memlock` => the rest + `import:@basic-memory-access`  where we automatically import `@basic-memory-access` if it is a whitelist, so users do not have to do anything, otherwise let them set it.

* A new `@basic-ipc` should get the `{pipe, pipe2}`, and then you have:
   `@ipc` => the rest of syscalls + `import:@basic-ipc` same as above.

* A new `@basic-io-event` should get the `{_newselect, eventfd, poll, ppoll, pselect, select}`
  `@io-event` the rest of syscalls + `import:@basic-io-event` same as above.

* A new `@basic-process: {fork, kill, prctl, wait*() }`  basic syscalls of `@process`.
  `@process: {clone, execveat, setns, unshare + import:@basic-process}`
  Restricting unshare, clone should not restrict basic operations such: kill, fork, wait, etc.

* A new `@basic-rw`: {lseek, write*(), read*() families}
* A new `@basic-memory: {mmap, mmap2, munmap}`
* A new `@basic-directory: {chdir, getcwd, fchdir}`
* A new `@basic-file-system: {access, lgetxattr*(), listxattr()*, stat*() family , + import:@basic-directory}`
* A new `@basic-socket-info: {getpeername, getsockname, getsockopt, setsockopt}`
* `@basic-io: {close, dup*(), import:@basic-rw}`
* `@file-system: {syscalls, import:@basic-file-system, import:@basic-io, import:@basic-memory, import:@chown, import:@chmod}`

You get the idea.

Such setup will allow to sandbox lot of programs by just whitelisting the `@basic` that is an alias of other groups, in this case we import all other basic groups, users won't have to tape or write complex profiles, just whitelist `@basic`. Since if you go through glibc and other libraries it will be really hard to get this right, they use and combine lot of syscalls, better group most of the basic syscalls and functionality that most programs require to allow them to work in a namespace environment with RootImage= under `@basic` or `@portable`.

I will update my patches and open PRs. Thank you!

**Comment by tixxdz** [comment]
cc @topimiettinen

**Comment by tixxdz** [comment]
One thing to note is that if sandboxed apps are updated in the future, and the program now starts to use a blocked syscall then things will fail quickly, users may just deactivate things again... this is why a generic group like `@basic` or `@portable` can help here.  

This model is derived from:
https://man.openbsd.org/pledge.2
Chromium sandbox, and how Android apps/permissions are done. However our aim is not to replicate those models but to take the best and combine it with systemd namespaces usage.

systemd may play nicely in Embedded Linux and IoT if we have on top of the new portable service model a new abstracted sandbox model or runtime mode to execute Embedded Linux apps with DynamicUser= + StateDirectory= + CacheDirectory= + systemd lightweight containers with RootImage=.

**Comment by topimiettinen** [comment]
So, for each system call group, there would be a version with basic set with "traditional Unix system calls" and another with an extended set. But do the sets of syscalls made by different services actually match with this kind of basic/extended division? What if the sets would be "common/current" (reflecting current use by libc etc., maybe including a bit larger set) and "exotic" (rarely used, could be old versions too)?

**Comment by topimiettinen** [comment]
With system call groups we could actually have a number of overlapping groups with different profile, this is only limited by maintenance burden and of course having a too large number of groups would make selecting them more difficult instead of helping. For example, group "@network-server" could allow all possible net syscalls, while "@basic-server" would only allow local sockets.

**Comment by tixxdz** [comment]
@topimiettinen 
> So, for each system call group, there would be a version with basic set with "traditional Unix system calls" and another with an extended set.

I would not say for each system call group, but most of them, especially chown() or other write operations on directories owned by apps should be allowed. Instead of "traditional Unix system calls" I may use system calls that do not have side effect or syscalls + context that does not change the outside world of the app.  

> But do the sets of syscalls made by different services actually match with this kind of basic/extended division? What if the sets would be "common/current" (reflecting current use by libc etc., maybe including a bit larger set) and "exotic" (rarely used, could be old versions too)?

I am not sure if I got what you mean here, but common/current also may work, finding the balance can be hard, but the final aim is to make it easy for our users: they should use simple syntax (and not technical syscalls) to describe the sandbox and what is allowed, things should not fail cause the user did not know the name of X syscall...

**Comment by tixxdz** [comment]
> With system call groups we could actually have a number of overlapping groups with different profile, this is only limited by maintenance burden and of course having a too large number of groups would make selecting them more difficult instead of helping. For example, group "@network-server" could allow all possible net syscalls, while "@basic-server" would only allow local sockets.

Indeed, I would recommend to only have the basic ones `@basic-socket-info` as described above, then maybe `@basic-network-io: {accept, bind, connect, listen, recv, send, socket, socketpair, shutdown, + @basic-socket-info}` 

Then `@network-io :{recvmmsg, sendmmsg, socketcall, + import:@basic-network-io}`

To answer your question about `@network-server` for net and  `@basic-server` for local sockets, we should combine abstracted options like `RestrictAddressFamilies=`, maybe add `ACCESS_INTERNET=yes|no` to allow inet and raw sockets. With this schema apps that use unix sockets will continue to work with `@basic` or even `@basic-network-io`

**Comment by poettering** [comment]
So we now have `@system-service`, which is a minimal concept going into the direction of what is requested here. 

I am sure we can add more, but let's discuss those individual. i.e. if there's a good case for a new group, please file an explicit acitonable issue about it, and we'll look into it.

I am am bit afraid of making all this too fine-grained, hence my hope was that `@system-service` covers 90% of the cases. If you disagree, please suggest additional groups as issue, as mentioned above.

Closing this now. Hope that makes sense.
