### ISSUE TITLE
nitpick: `shutdown -H 1` returns a programming error

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6957]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v234-git

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

`Action <polkit action> is not registered` should not occur, it indicates a programming error, unless the system is corrupted, or a downgrade is in progress.

### In case of bug report: Unexpected behaviour you saw

```
$ shutdown -H 1
Failed to set wall message, ignoring: Interactive authentication required.
Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Action org.freedesktop.login1.halt is not registered
$ shutdown -H now
Failed to open /dev/initctl: Permission denied
Failed to talk to init daemon.
```

(the message from the second case is not ideal... at least it mentions permission denied though).

### In case of bug report: Steps to reproduce the problem

Command as above - `$` indicates command run by non-root user.

### Solution?

My easiest suggestion is that the verify_shutdown_creds() call on scheduling a "halt", should be changed to only check for CAP_SYS_BOOT.

I don't know that `halt` is appropriate or particularly useful for unprivileged users.  Current logind does not have a Halt method - which should surely be added if it's appropriate to have a "halt" polkit action, otherwise we'd have a weird situation where `shutdown -H now` works but `systemctl halt` doesn't.

**Comment by poettering** [comment]
Fix pending in the newly pushed version of #6944.
