### ISSUE TITLE
networkd: dummy interface in bridge stuck in "configuring", leading to degraded system

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#6961]
This is a bug in systemd 234 and 232, seen in Debian unstable and Debian stable.

Steps to reproduce:
Take a VM. Configure and enable networkd with the following configuration:
```
[2/587]mh@testsid85:~ $ head -n-0 /etc/systemd/network/*
==> /etc/systemd/network/bridge.netdev <==
[NetDev]
Name=br0
Kind=bridge


==> /etc/systemd/network/bridge.network <==
[Match]
Name=br0

[Network]
DHCP=No

[Address]
Address=2001:db8:150:436c::2/64


==> /etc/systemd/network/dummy1.netdev <==
[NetDev]
Name=dummy1
Kind=dummy

==> /etc/systemd/network/dummy1.network <==
[Match]
Name=dummy1

[Network]
Bridge=br0
DHCP=No

[3/588]mh@testsid85:~ $
```

This is a common use case to force a bridge in "up" state before the first actual user is attached. Otherwise, the addresses configured on the bridge itself do not get useable before the first acutl user is attached.

With this configuration, the dummy interface stays in "carrier/configuring". systemd-networkd-wait-online never returns, with the associated service timing out, leading to the entire system being in "degraded" state.

I tested this on KVM VMs only. It doesnt seem to matter whether the VM has connectivity via a different interface; I tried with an internet-facing ens3 and without (logging in via the serial console). In both cases, the issue showed. Sorry, I didn't test on a physical system.

If you cannot reproduce this; I can give you access to a VM or give you a VM image where the issue shows.

Greetings
Marc

**Comment by devurandom** [comment]
I have the same issue with systemd 234, but without the "dummy" netdev. The bridge itself (without any devices attached) is stuck in "no-carrier / configuring" state. If I manually `ip link delete br0` and then `brctl addbr br0`, it comes up immediately and without further issues.

**Comment by software-artificer** [comment]
```
systemd 233
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN default-hierarchy=hybrid
```
is also affected. Having an ethernet device:
```
# networkctl status eno1
● 2: eno1
       Link File: /usr/lib64/systemd/network/99-default.link
    Network File: /etc/systemd/network/local.network
            Type: ether
           State: carrier (configuring)
            Path: pci-0000:00:19.0
          Driver: e1000e
          Vendor: Intel Corporation
           Model: 82579LM Gigabit Network Connection
      HW Address: XX:XX:XX:XX:XX:XX (Hewlett Packard)
```
with following config:
```
# cat /etc/systemd/network/local.network
[Match]
MACAddress=XX:XX:XX:XX:XX:XX

[Network]
Bridge=lan0
```
leads to endless `configuring` and hence `systemd-networkd-wait-online` times out.

**Comment by fpeterschmitt** [comment]
It seems that this bug has been addressed: https://github.com/systemd/systemd/issues/6645

The new option is called `ConfigureWithoutCarrier` and can be set to `no` or `yes` into the `.network` file, here you want to set it to `yes`. But this is only for `systemd>=235`.

This works for me ;)

**Comment by tomhughes** [comment]
Well no, because the bridge here has carrier and #6645 relates to interfaces that are in a bridge but don't have carrier yet. Here's what mine looks like:

```
● 2: eno1
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/lan.network
            Type: ether
           State: carrier (configuring)
            Path: pci-0000:01:00.0
          Driver: r8169
          Vendor: Realtek Semiconductor Co., Ltd.
           Model: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (Desktop Board D510MO/D525MW)
      HW Address: 00:1c:c0:de:93:7a (Intel Corporate)
```

Which has carrier, and is bound into a bridge, but which networkd thinks is not fully configured.

One problem is that "configuring" maps to three separate states internally but there is no way to tell from the status output which one it is in :-(

**Comment by tomhughes** [comment]
I suspect that https://github.com/systemd/systemd/commit/5971cb9de9 is more likely to fix it.

**Comment by tomhughes** [comment]
Confirmed that rebuilding the F27 systemd with that patch fixes it.

**Comment by ssahani** [comment]
Can we close this then ?

**Comment by Zugschlus** [comment]
I can confirm that systemd 236 in Debian unstable does not show the faulty behavior any more.
