### ISSUE TITLE
Unable to find which specific Python process was killed by Linux OOM killer

### ISSUE THREAD

**Issue by moonlight16** [systemd/systemd#6966]
### Submission type
 - Request for enhancement (RFE)

### systemd version the issue has been seen with
235

### RFE description
(I originally posted this on Stack Exchange: 
https://unix.stackexchange.com/questions/387068/finding-which-specific-python-process-was-killed-by-linux-oom-killer)

I'm trying to figure out which specific Python process or executable was killed by the Linux OOM killer.

In /var/log/messages I get this:

Aug 18 03:19:11 169 kernel: [ 7747]     0  7748  3226957  2875051    5692        0             0 python

(notice it just say name = "python")

and this:

Aug 18 03:19:11 169 kernel: Killed process 7748 (python) total-vm:12907828kB, anon-rss:11500204kB, file-rss:0kB
(again notice it just says the process was "python")

Ideally a log file for the process would have the PID somewhere. But suppose the logs wrapped (or suppose the process doesn't log the PID anywhere).

It would be nice if systemd could print out of the full name in the crash/process table.

i.e. 
Aug 18 03:19:11 169 kernel: [ 7747]     0  7748  3226957  2875051    5692        0             0 /usr/bin/python /usr/lib/python2.7/site-packages/foo.pyc

Alternatively, maybe add the parent PID to the table.

**Comment by poettering** [comment]
systemd is not involved with OOM killing. That's a kernel feature, implemented in the kernel and under the kernel's exclusive control. systemd doesn't get notified, and hence cannot log about it.

Please contact the kernel folks about this for help, we can't really help you. Sorry.
