### ISSUE TITLE
Dropins in /etc/systemd/user for user units appear as DropinPaths in systemctl show but take no effect

### ISSUE THREAD

**Issue by Rudd-O** [systemd/systemd#6982]
### Submission type

 - Bug report

### systemd version the issue has been seen with

231-17.fc25

### Used distribution

Fedora 25

### In case of bug report: Expected behaviour you didn't see

With this:

```
[Unit]
ConditionPathExists=/var/run/qubes-service/syncthing
```

in `/etc/systemd/user/syncthing.service.d/qubes.conf`

The expected behavior is that syncthing user unit does not start with the user session.

I also expected to see ConditionPathExists in the output of systemctl show, like DropInPaths does appear, but ConditionPathExists does not appear.

### In case of bug report: Unexpected behaviour you saw

The unit started with the session.

**Comment by yuwata** [comment]
The version of systemd you use is old. Please read [CONTRIBUTING.md](https://github.com/systemd/systemd/blob/master/.github/CONTRIBUTING.md).
> We only track bugs in the two most recently released versions of systemd in the GitHub Issue tracker. If you are using an older version of systemd, please contact your distribution's bug tracker instead.

Moreover, I do not reproduce the problem with a recent snapshot. I've tested as follows, and the result seems fine.
```
$ systemctl --user cat hoge.service
# /etc/systemd/user/hoge.service
[Service]
Type=oneshot
ExecStart=/usr/bin/echo from service file

# /etc/systemd/user/hoge.service.d/a.conf
[Service]
ExecStart=/usr/bin/echo from drop-in configs
$ systemctl --user daemon-reload
$ systemctl --user start hoge.service
$ systemctl --user status hoge.service
● hoge.service
   Loaded: loaded (/etc/systemd/user/hoge.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/user/hoge.service.d
           └─a.conf
   Active: inactive (dead)

Oct 04 14:33:17 localhost systemd[717]: Starting hoge.service...
Oct 04 14:33:17 localhost echo[16468]: from service file
Oct 04 14:33:17 localhost echo[16469]: from drop-in configs
Oct 04 14:33:17 localhost systemd[717]: Started hoge.service.
```

**Comment by poettering** [comment]
Are you sure you issued "systemctl daemon-reload" after creating that file? What does "systemctl cat …" on the unit file list?

**Comment by Rudd-O** [comment]
It may work from drop in configs for ExecStart but not necessarily for ConditionPathExists.  I will see how my tests go with newer systemd but we can't conclude this isn't broken yet, even on master.

On October 4, 2017 7:38:28 AM GMT+02:00, Yu Watanabe <notifications@github.com> wrote:
>The version of systemd you use is old. Please read
>[CONTRIBUTING.md](https://github.com/systemd/systemd/blob/master/.github/CONTRIBUTING.md).
>> We only track bugs in the two most recently released versions of
>systemd in the GitHub Issue tracker. If you are using an older version
>of systemd, please contact your distribution's bug tracker instead.
>
>Moreover, I do not reproduce the problem. I've tested as follows, and
>the result seems fine.
>```
>$ systemctl --user cat hoge.service
># /etc/systemd/user/hoge.service
>[Service]
>Type=oneshot
>ExecStart=/usr/bin/echo from service file
>
># /etc/systemd/user/hoge.service.d/a.conf
>[Service]
>ExecStart=/usr/bin/echo from drop-in configs
>$ systemctl --user daemon-reload
>$ systemctl --user start hoge.service
>$ systemctl --user status hoge.service
>● hoge.service
>Loaded: loaded (/etc/systemd/user/hoge.service; static; vendor preset:
>enabled)
>  Drop-In: /etc/systemd/user/hoge.service.d
>           └─a.conf
>   Active: inactive (dead)
>
>Oct 04 14:33:17 localhost systemd[717]: Starting hoge.service...
>Oct 04 14:33:17 localhost echo[16468]: from service file
>Oct 04 14:33:17 localhost echo[16469]: from drop-in configs
>Oct 04 14:33:17 localhost systemd[717]: Started hoge.service.
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/systemd/systemd/issues/6982#issuecomment-334054796

--

Rudd-O

http://rudd-o.com/

**Comment by yuwata** [comment]
@Rudd-O That may be logically true. However, still not reproducible with `ConditionPathExists=`.
```
$ systemctl --user daemon-reload
$ systemctl --user cat hoge.service
# /etc/systemd/user/hoge.service
[Service]
Type=oneshot
ExecStart=/usr/bin/echo from service file

# /etc/systemd/user/hoge.service.d/b.conf
[Unit]
ConditionPathExists=/path/to/file/not/exist
$ systemctl --user start hoge.service
$ systemctl --user status hoge.service
● hoge.service
   Loaded: loaded (/etc/systemd/user/hoge.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/user/hoge.service.d
           └─b.conf
   Active: inactive (dead)
$ sudo rm /etc/systemd/user/hoge.service.d/b.conf 
$ systemctl --user daemon-reload
$ systemctl --user start hoge.service
$ systemctl --user status hoge.service
● hoge.service
   Loaded: loaded (/etc/systemd/user/hoge.service; static; vendor preset: enabled)
   Active: inactive (dead)

Oct 04 21:01:19 localhost systemd[650]: Starting hoge.service...
Oct 04 21:01:19 localhost echo[2882]: from service file
Oct 04 21:01:19 localhost systemd[650]: Started hoge.service.
```

**Comment by Rudd-O** [comment]
I'll wait for the update to trickle down to Fedora then.

On October 4, 2017 2:07:10 PM GMT+02:00, Yu Watanabe <notifications@github.com> wrote:
>@Rudd-O That is logically true. However, still not reproducible with
>`ConditionPathExists=`.
>```
>$ systemctl --user daemon-reload
>$ systemctl --user cat hoge.service
># /etc/systemd/user/hoge.service
>[Service]
>Type=oneshot
>ExecStart=/usr/bin/echo from service file
>
># /etc/systemd/user/hoge.service.d/b.conf
>[Unit]
>ConditionPathExists=/path/to/file/not/exist
>$ systemctl --user start hoge.service
>$ systemctl --user status hoge.service
>● hoge.service
>Loaded: loaded (/etc/systemd/user/hoge.service; static; vendor preset:
>enabled)
>  Drop-In: /etc/systemd/user/hoge.service.d
>           └─b.conf
>   Active: inactive (dead)
>$ sudo rm /etc/systemd/user/hoge.service.d/b.conf 
>$ systemctl --user daemon-reload
>$ systemctl --user start hoge.service
>$ systemctl --user status hoge.service
>● hoge.service
>Loaded: loaded (/etc/systemd/user/hoge.service; static; vendor preset:
>enabled)
>   Active: inactive (dead)
>
>Oct 04 21:01:19 localhost systemd[650]: Starting hoge.service...
>Oct 04 21:01:19 localhost echo[2882]: from service file
>Oct 04 21:01:19 localhost systemd[650]: Started hoge.service.
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/systemd/systemd/issues/6982#issuecomment-334134403

--

Rudd-O

http://rudd-o.com/

**Comment by Rudd-O** [comment]
For the record, I rebooted the box.  It was a Qubes TemplateVM.

**Comment by poettering** [comment]
OK, let's close this then here. If you can reproduce this on a current version, and are sure you did "systemctl daemon-reload" as needed, please reopen and provide the requested "systemctl cat" output.

**Comment by Rudd-O** [comment]
Please reopen.  I can reproduce this with systemd 233 in Fedora 26.  Yes of course there was an `intervening systemctl daemon-reload`.

```
# /usr/lib/systemd/user/syncthing.service
[Unit]
Description=Syncthing - Open Source Continuous File Synchronization
Documentation=man:syncthing(1)
Wants=syncthing-inotify.service

[Service]
ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0
Restart=on-failure
SuccessExitStatus=3 4
RestartForceExitStatus=3 4

[Install]
WantedBy=default.target

# /etc/systemd/user/syncthing.service.d/qubes.conf
[Unit]
ConditionPathExists=/var/run/qubes-service/syncthing
```

**Comment by Rudd-O** [comment]
Actually, ignore this.  It's a packaging error in syncthing.
