### ISSUE TITLE
RFE: allow symlinks to block devices in /var/lib/machines

### ISSUE THREAD

**Issue by risen** [systemd/systemd#6990]
### Submission type

> Request for enhancement (RFE)

### Systemd version the issue has been seen with

> v234 (Debian version: 234-3~bpo9+1)

### Used distribution

> Debian GNU/Linux 9 (stretch)

### Enhancement description

I'd like to use LVM2 to create container-specific LVs containing a GPT with (LUKS-encrypted) partitions. And I'd like to control them using `machinectl`, i.e. `machinectl list-images`, `machinectl enable`, etc.

I tried setting this up, and symlinking `/var/lib/machines/containername` to `/dev/vg/containername` or to `/dev/mapper/vg-containername`, but `machined`/`machinectl` doesn't seem to detect them.

I could in theory (auto)mount the filesystem in a directory called `/var/lib/machines/containername`, but then the host would have to do all the work (detecting/setting up the partitions, unlocking LUKS, mounting the filesystem) that `systemd-nspawn` (or `systemd-dissect`) does for me. Also, no need to expose the container filesystem to the host unnecessarily.

So it would be a useful enhancement if symlinks to device nodes/block devices worked.

**Comment by poettering** [comment]
Fix waiting in #6996

**Comment by poettering** [comment]
#6996 got merged. Closing.
