### ISSUE TITLE
systemd.network: allow matching on ID_NET_NAME_ONBOARD and ID_NET_NAME_PATH

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#6995]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232

Sometimes, network interface names are outside our control (imagine automatically installed udev rules), so having a `Name=` `[Mach]` section in a `systemd.network` doesn't catch.

In those cases, it would be helpful to also match via the `ID_NET_NAME_ONBOARD` and `ID_NET_NAME_PATH` names (via a `NameOnboard=` or `NamePath=` key).
 `ID_NET_NAME_MAC` shouldn't be necessary, as matching by mac address is already possible using the `MACAddress=` key.

**Comment by poettering** [comment]
This exists nowadays via the Property= match. Closing.
