### ISSUE TITLE
man: document that turning on randomized MAC addresses in .link files sets the "locally administered" bit in the MAC address

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#70]
There is convenient tool to change MAC address of the interface to arbitrary/random value - see https://github.com/alobbs/macchanger for details. That's handy for security reasons for example.

Seems like such a low-level functionality really belongs to systemd-networkd instead of external which is tricky to integrate into boot process properly.

**Comment by arvidjaar** [comment]
It is already possible.
http://www.freedesktop.org/software/systemd/man/systemd.link.html

**Comment by zabbal** [comment]
Yes, almost: 
- it's unclear if 'locally-administered' bit is set when random MAC address policy applied
- there's no option to randomize only non-vendor part

Generating MAC as completely random string you might easily end-up with non-existent vendor which instead of concealing your identity would act as a big red flag - exactly opposite of what many people would like to achieve. That's why I'd still have to use macchanger but I would really prefer to drop it.

**Comment by teg** [comment]
The locally administered bit is set on random mac addresses. Does that address your concern?

Abusing a vendor prefix by only randomizing the postfix sounds very wrong. It clearly is against the RFC, but more importantly it makes collisions hugely more likely.

**Comment by poettering** [comment]
OK, given @teg's comments I have now turned this into a docuentation issue: i think networkd's vehaviour is alright, but we should document that the "locally administered" bit is properly set in the MAC address.

**Comment by teg** [comment]
I'll add the documentation as that seems uncontroversial. If anyone ( @kaysievers ?) wants to argue that we should allow randomizing the non-vendor part only, please open a separate issue for that. I remain unconvinced though.

**Comment by poettering** [comment]
#106 has bee commited.
