### ISSUE TITLE
cannot run on (old) containers without machine-id

### ISSUE THREAD

**Issue by rickysarraf** [systemd/systemd#700]
So I just noticed this new file /etc/machine-id
I'm not sure which tool creates it but turns out systemd-nspawn has a dependency on it.

I see this issue pop up on my old Ubuntu trusty containers, that were created/used with LXC.

-- Unit machine-trusty\x2dtemplate.scope has begun shutting down.
Jul 24 13:36:11 learner sudo[32424]: pam_unix(sudo:session): session closed for user root
Jul 24 13:36:11 learner systemd[1]: Stopped Container trusty-template.
-- Subject: Unit machine-trusty\x2dtemplate.scope has finished shutting down
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit machine-trusty\x2dtemplate.scope has finished shutting down.
Jul 24 13:36:11 learner kernel: lxcbr0: port 1(vb-trusty-temp) entered disabled state
Jul 24 13:36:11 learner avahi-daemon[1136]: Withdrawing workstation service for vb-trusty-temp.
Jul 24 13:36:11 learner kernel: device vb-trusty-temp left promiscuous mode
Jul 24 13:36:11 learner kernel: lxcbr0: port 1(vb-trusty-temp) entered disabled state
Jul 24 13:36:11 learner NetworkManager[1141]: <info>  (lxcbr0): bridge port vb-trusty-temp was detached
Jul 24 13:36:11 learner NetworkManager[1141]: <info>  (vb-trusty-temp): released from master lxcbr0
Jul 24 13:36:11 learner NetworkManager[1141]: <info>  devices removed (path: /sys/devices/virtual/net/vb-trusty-temp, iface: vb-trusty-temp)
Jul 24 13:36:22 learner sudo[1285]:      rrs : TTY=pts/2 ; PWD=/home/rrs ; USER=root ; COMMAND=/bin/machinectl start trusty-template
Jul 24 13:36:22 learner sudo[1285]: pam_unix(sudo:session): session opened for user root by rrs(uid=0)
Jul 24 13:36:22 learner polkitd(authority=local)[1299]: Registered Authentication Agent for unix-process:1286:9097474 (system bus name :1.170 [/usr/bin/pkttyagent --notify-fd 5 --fallback], o
Jul 24 13:36:22 learner systemd[1]: Starting Container trusty-template...
-- Subject: Unit systemd-nspawn@trusty\x2dtemplate.service has begun start-up
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit systemd-nspawn@trusty\x2dtemplate.service has begun starting up.
Jul 24 13:36:22 learner systemd-nspawn[1290]: Failed to create directory /var/lib/lxc/trusty-template/rootfs/sys/fs/selinux: Read-only file system
Jul 24 13:36:22 learner systemd-nspawn[1290]: Failed to create directory /var/lib/lxc/trusty-template/rootfs/sys/fs/selinux: Read-only file system
Jul 24 13:36:22 learner systemd-nspawn[1290]: /etc/localtime is not a symlink, not updating container timezone.
Jul 24 13:36:22 learner systemd-nspawn[1290]: Failed to read machine ID from /var/lib/lxc/trusty-template/rootfs/etc/machine-id: No such file or directory
Jul 24 13:36:22 learner systemd[1]: systemd-nspawn@trusty\x2dtemplate.service: Main process exited, code=exited, status=1/FAILURE
Jul 24 13:36:22 learner systemd[1]: Failed to start Container trusty-template.
-- Subject: Unit systemd-nspawn@trusty\x2dtemplate.service has failed
-- Defined-By: systemd
## -- Unit systemd-nspawn@trusty\x2dtemplate.service has failed.

-- The result is failed.
Jul 24 13:36:22 learner systemd[1]: systemd-nspawn@trusty\x2dtemplate.service: Unit entered failed state.
Jul 24 13:36:22 learner systemd[1]: systemd-nspawn@trusty\x2dtemplate.service: Failed with result 'exit-code'.
Jul 24 13:36:22 learner sudo[1285]: pam_unix(sudo:session): session closed for user root
Jul 24 13:36:22 learner polkitd(authority=local)[1299]: Unregistered Authentication Agent for unix-process:1286:9097474 (system bus name :1.170, object path /org/freedesktop/PolicyKit1/Authen
2015-07-24 / 13:37:16 ♒♒♒  ☺    

The man page did not mention that as a hard dependency. In the other bug report you mentioned about machinectl's dependency on dbus/systemd inside the container.

For old containers, which may not have systemd, will systemd-nspawn/machinectl support them ?

Infact, the manpage says, 

```
   systemd-nspawn implements the Container Interface[1] specification.

   As a safety check systemd-nspawn will verify the existence of /usr/lib/os-release or
   /etc/os-release in the container tree before starting the container (see os-
   release(5)). It might be necessary to add this file to the container tree manually if
   the OS of the container is too old to contain this file out-of-the-box.
```

**Comment by poettering** [comment]
with --link-journal=no you should be able to make this work. systemd and the journal do require /etc/machine-id, and that's widely documented. You left on the journal support even though you use a non-systemd init system as payload, hence the breakage.

**Comment by kugel-** [comment]
@poettering I tried this on a ubuntu 12.04 image and it still doesn't work

```
# sudo systemd-nspawn --link-journal=no -M precise-server-cloudimg-amd64-root 
Spawning container precise-server-cloudimg-amd64-root on /var/lib/machines/precise-server-cloudimg-amd64-root.
Press ^] three times within 1s to kill container.
Failed to read machine ID from /var/lib/machines/precise-server-cloudimg-amd64-root/etc/machine-id: No such file or directory
```

**Comment by dhamp** [comment]
after creating empty file /etc/machine-id container started normally
 and  /etc/machine-id in container rootfs filled by container uuid

@poettering May be systemd-nspawn should make this actions($touch /etc/machine-id inside container rootfs) itself?

$systemd-nspawn --version
systemd 230
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
