### ISSUE TITLE
core: DynamicUser=yes with User= fails if static uid and gid are different

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#7013]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235 with PR #7003

### Used distribution

Fedora 26 x86_64

### In case of bug report: Expected behaviour you didn't see

`DynamicUser=yes` with `User=` works fine.

### In case of bug report: Unexpected behaviour you saw

`DynamicUser=yes` with `User=` fails if static uid and gid are different.
```
$ id systemd-timesync
uid=989(systemd-timesync) gid=987(systemd-timesync) groups=987(systemd-timesync)
$ sudo systemctl start systemd-timesyncd.service
$ journalctl -b --no-hostname
(snip)
Oct 06 17:25:49 systemd[1]: Starting Network Time Synchronization...
Oct 06 17:25:49 systemd[2066]: systemd-timesyncd.service: Failed to update dynamic user credentials: Invalid or incomplete multibyte or wide character
Oct 06 17:25:49 systemd[2066]: systemd-timesyncd.service: Failed at step USER spawning /usr/lib/systemd/systemd-timesyncd: Invalid or incomplete multibyte or wide character
Oct 06 17:25:49 systemd[1]: systemd-timesyncd.service: Main process exited, code=exited, status=217/USER
Oct 06 17:25:49 systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.
Oct 06 17:25:49 systemd[1]: Failed to start Network Time Synchronization.
(snip)
```
This is caused by https://github.com/systemd/systemd/blob/master/src/core/dynamic-user.c#L471-L473

**Comment by yuwata** [comment]
@poettering What do you think about this? Now PR #7003 is merged. But for compatibility, it is necessary to remove e.g., systemd-timesync user and group if their uid and gid are different. However, for example, fedora prohibit to remove user or group in RPM scripts.

I do not catch why systemd does not support the case of `uid != gid`. If you agree to remove such restriction, I will try to remove it.

**Comment by poettering** [comment]
Hmm, I actually added that check on purpose, because non-matching UID/GID is a really sick idea. But hmm, if this breaks compat, I figure we should drop the check

**Comment by poettering** [comment]
ah, eh, we posted at the exact same time.

Anyway, the restriction should be removed, to make things compatible with Fedora in this regard

**Comment by yuwata** [comment]
@poettering OK. Thank you for your comment.
> non-matching UID/GID is a really sick idea.

Yeah, I agree. But unfortunately, uid and gid corresponding to user and group created by RPM scripts are completely independent, at least on Fedora.

I will try to remove the restriction.

**Comment by fsateler** [comment]
The current restriction makes `DynamicUser` + static UID[1] unusable on debian-based systems. System UIDs and GIDs are allocated in the 100-999 range, but `base-passwd` (which ships the base passwd and group files), comes with the 100 GID allocated for the `users` group. This means that effectively, the system GID range is 101-999. Therefore, by default UID and GID will never match.

[1] That is, where packaging/sysadmin has allocated the relevant user/group names.
