### ISSUE TITLE
set AgeingTimeSec=0 on a bridge is not accepted

### ISSUE THREAD

**Issue by ingo-h** [systemd/systemd#7019]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Debian GNU/Linux 9.1 (stretch)

### In case of bug report: Expected behaviour you didn't see

> ageing_time of a bridge set to 0
> $ cat /sys/class/net/br0/bridge/ageing_time
> 0

### In case of bug report: Unexpected behaviour you saw

> ageing_time of a bridge set to default 30000
> $ cat /sys/class/net/br0/bridge/ageing_time
30000

### In case of bug report: Steps to reproduce the problem

> configure a bridge with AgeingTimeSec=0 in br0.netdev
> $ cat /etc/systemd/network/br0.netdev
> [NetDev]
> Name=br0
> Kind=bridge
> [Bridge]
> AgeingTimeSec=0
>
> $ sudo ip link set dev br0 down && sudo ip link del dev br0
> $ sudo systemctl restart systemd-networkd
>
> Workaround: setting AgeingTimeSec= .000001 (there is a dot) in br0.netdev will result in the expected behaviour /sys/class/net/br0/bridge/ageing_time set to 0

**Comment by ssahani** [comment]
fix is https://github.com/systemd/systemd/pull/7021
