### ISSUE TITLE
systemd-tmpfiles ignores --root when looking up user/group IDs

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#7032]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> v234

### Used distribution

> Arch Linux (but also reproduced on Debian Stretch, systemd v232)

### In case of bug report: Expected behaviour you didn't see

> `systemd-tmpfiles` should use the user/group database within the directory specified with `--root`, if present. More broadly speaking, it should be possible to populate that user/group database with `systemd-sysusers` and then create directories owned by those users with `systemd-tmpfiles`.

### In case of bug report: Unexpected behaviour you saw

> `systemd-tmpfiles` uses the host’s user/group database, which may result in an error if the referenced user/group doesn’t exist, or may accidentally work if the user/group exists with the same ID on the host, or may silently use the wrong ID if the user/group exists with the same name but different ID on the host.

### In case of bug report: Steps to reproduce the problem

> ```bash
> #!/bin/bash
> ((UID)) && { printf >&2 '%s should be run as root\n' "$0"; exit 1; }
> set -ex
> mkdir -p systemd-bug/etc/{sysusers,tmpfiles}.d/
> printf 'u nobody 500 "Nobody" /nobody\n' > systemd-bug/etc/sysusers.d/nobody.conf
> printf 'd /nobody - nobody nobody\n' > systemd-bug/etc/tmpfiles.d/nobody.conf
> systemd-sysusers --root systemd-bug nobody.conf
> systemd-tmpfiles --root systemd-bug nobody.conf --create
> ls -ldn systemd-bug/nobody
> ```
> 
> Run this script as root (or run the commands manually :) ). Inside the empty directory `systemd-bug`, we create a `nobody` user+group with ID 500, and then create its home directory with `systemd-tmpfiles`. But the directory is actually owned by UID+GID 65534 (or whatever else your host’s `nobody` is), not 500 (the new `nobody`).
> 
> (An earlier version of this bug report used the `root` user, but then I discovered that systemd’s `get_user_creds` actually hardcodes information for `root`. I’m not sure if that would have to be changed, because a `root` with a nonzero UID inside the `--root`’s user database is probably in violation of some standard.)

Since the description of the `--root` option of `systemd-sysusers` and `systemd-tmpfiles` is a bit vague, I’m not sure that this is a bug (hence the RFE submission type), but I think it’s unexpected and undesirable. I expect that using `systemd-sysusers` and `systemd-tmpfiles` in conjunction (create a system user and then create its files and directories) should work well, with or without `--root`, but with the current behavior `systemd-tmpfiles` doesn’t see the user that `systemd-sysusers` created.

**Comment by poettering** [comment]
Uh, we do those lookups with libc NSS, and that doesn't really support --root=. Not sure what we can do about that, except document that names are resolved with the local user database...

**Comment by poettering** [comment]
Documentation fix now waiting in #7344.
