### ISSUE TITLE
Timeout does not mark systemd.mount unit as failed

### ISSUE THREAD

**Issue by nh2** [systemd/systemd#7038]
### Submission type

 - Bug report (at least I suspect it's one)

I've written up what I noticed [here](https://github.com/systemd/systemd/pull/4297#issuecomment-334788308) into a proper bug report now.

### systemd version the issue has been seen with

> 234

### Used distribution

> NixOS

### In case of bug report: Expected behaviour you didn't see

When a (fstab-generated, probably doesn't matter) mount unit gets killed by a timeout, it's marked as failed.

### In case of bug report: Unexpected behaviour you saw

It's marked as inactive instead.

### In case of bug report: Steps to reproduce the problem

Create a mount unit for something that takes a while to mount (e.g. a NFS or GlusterFS mount, and you can increase the time it takes by adding extra latency with `tc`) and set a very short mount timeout (e.g. `x-systemd.mount-timeout=1s`).

For example, in my case in `journalctl`:

```
Oct 09 17:16:55 gluster-cluster-1 systemd[1]: glustermount.mount: Mounting timed out. Stopping.
Oct 09 17:16:55 gluster-cluster-1 systemd[1]: glustermount.mount: Mount process exited, code=killed status=15
```

In `systemctl`:

```
# systemctl status glustermount.mount
● glustermount.mount - /glustermount
   Loaded: loaded (/etc/fstab; generated; vendor preset: enabled)
   Active: inactive (dead)
    Where: /glustermount
     What: localhost:/distfs
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
```

**Comment by nh2** [comment]
Note that I cant reproduce this every time. Sometimes it doesn't work, sometimes works correctly, like in this run:

```
# systemctl status glustermount.mount
● glustermount.mount - /glustermount
   Loaded: loaded (/etc/fstab; generated; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2017-10-09 21:14:39 UTC; 43s ago
    Where: /glustermount
     What: gluster-volume-distfs.service.consul:/distfs
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 875 ExecMount=/nix/store/xs46hlm9wy2rgivaklcil6dldvapnw58-util-linux-2.30-bin/bin/mount gluster-volume-distfs.service.consul:/distfs /glustermount -t glusterfs -o backup-volf
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/glustermount.mount

Oct 09 21:14:34 gluster-client-1 systemd[1]: Mounting /glustermount...
Oct 09 21:14:34 gluster-client-1 systemd[1]: Mounted /glustermount.
Oct 09 21:14:39 gluster-client-1 systemd[1]: glustermount.mount: Mounting timed out. Stopping.
Oct 09 21:14:39 gluster-client-1 systemd[1]: glustermount.mount: Mount process exited, code=killed status=15
Oct 09 21:14:39 gluster-client-1 systemd[1]: glustermount.mount: Unit entered failed state.
```

**Comment by poettering** [comment]
Please retry with v235. There's a good chance this all starts working with 235, due to 22af0e5873978efbb3c210dc4c889041c7d56447

**Comment by poettering** [comment]
Anyway, closing this. Please reopen if this is still a problem with 235
