### ISSUE TITLE
man: lack of descriptions of BoundBy= and ConsistsOf=

### ISSUE THREAD

**Issue by johnlinp** [systemd/systemd#7043]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

v235

### Description

I saw `BoundBy=` and `ConsistsOf=` dependencies were mentioned in `systemctl(1)`, but I can't find the detailed descriptions of them anywhere in other documentations. I assume they should have been described in `systemd.unit(5)`?

**Comment by poettering** [comment]
Humm. These are primarily internal deps. They are automatically created as inverse of BindsTo= and PartOf= and cannot be configured directly. The hence aren't really first-class deps. 

That said I figure it doesn't hurt documenting such internal deps too, as they do show up in systemctl show, indeed.

**Comment by johnlinp** [comment]
@poettering Since those dependencies are only for internal use, how about removing them in `systemctl(1)` and describe them with something like "inverse BindsTo=" and "inverse PartOf=" instead?

**Comment by poettering** [comment]
well, even though they are for internal use they actually are interesting to admins too, as they may be used to determine things like "which service is bound to this device?" and things like that.
