### ISSUE TITLE
Assertion failed in sd-dhcp-server.c

### ISSUE THREAD

**Issue by mvduin** [systemd/systemd#7047]
### Submission type

Bug report

### systemd version the issue has been seen with

v234

### Used distribution

debian buster

### Unexpected behaviour you saw

With systemd-networkd debug logging enabled, when the ethernet link goes down I'm seeing:

```
Oct 10 13:41:07 nena systemd-networkd[126]: eth0: Lost carrier
Oct 10 13:41:07 nena systemd-networkd[126]: DHCP CLIENT (0x560f2dc5): STOPPED
Oct 10 13:41:07 nena systemd-networkd[126]: eth0: DHCP lease lost
Oct 10 13:41:07 nena systemd-networkd[126]: NDISC: Stopping IPv6 Router Solicitation client
Oct 10 13:41:07 nena systemd-networkd[126]: Assertion 'server' failed at ../src/libsystemd-network/sd-dhcp-server.c:256, function sd_dhcp_server_stop(). Ignoring.
```

I don't know if it might be related, but on subsequent link up I'm also experiencing "NDISC: Error sending Router Solicitation: Network is unreachable", which does not resolve on restarting networkd (see issue #2365), resulting in loss of IPv6 connectivity.

### Steps to reproduce the problem

My config:
```
[Match]
Name=eth0

[Network]
DHCP=ipv4
IPv6PrivacyExtensions=no
IPv6DuplicateAddressDetection=0
LLMNR=on

[DHCP]
UseDomains=yes
```

The error occurs on link down.

**Comment by mvduin** [comment]
Just to be sure, I've also tested the following config:
```
[Match]
Name=eth0

[Network]
DHCP=yes

[DHCP]
UseDomains=yes
```

Same results.

**Comment by ssahani** [comment]
Fix is #7083

**Comment by mvduin** [comment]
OK, so that error is just harmless noise, thanks!

Do you happen to have any ideas about IPv6 router discovery failing subsequently, resulting in loss of IPv6 connectivity? (apart from link-local)  The same error on restarting networkd (which we also experience) seems to match the longstanding open #2365.  So far the only way I found to recover from this is reboot :/

I'm puzzled though since presumably IPv6 doesn't break this easily for _everyone_ using systemd-networkd.  And yet, if there's something about our setup that's causing it, I have no clue what.  We just have one simple ethernet interface and the pretty trivial network config I showed above.

**Comment by ssahani** [comment]
test with  https://github.com/systemd/systemd/pull/6918. Also please elaborate why this issue exactly occurs ?

**Comment by mvduin** [comment]
I've cherry-picked both patches from your issue-5625 branch and both patches from your issue-7047 branch onto v234 and did some tests with its networkd:

* Toggling link down/up using `ip link` triggered the dhcp-related assertion failed in v234, this error is gone in the patched version. Interestingly, IPv6 remains functional (router advert received).

* Restarting systemd-networkd still results in `NDISC: Error sending Router Solicitation: Network is unreachable` and the Router Solicitation client shuts down, hence no global IPv6 connectivity. (Only the link-local address remains.)

* Pulling the cable and plugging it back in triggered both the dhcp assertion and the router solicitation error in v234.  I can't test the patched version right now since I'm working remotely.

Here's the log output of the patched networkd (and some other useful bits) during boot and the first two tests: https://gist.github.com/mvduin/91253fe06bc86847a80612aa406c16a6
