### ISSUE TITLE
Add coloring to `systemctl status'

### ISSUE THREAD

**Issue by al-caveman** [systemd/systemd#7073]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

235

### Used distribution

Arch Linux

### Enhancement details

The output of `systemctl status` looks like this:

    cavebox~> systemctl status
    ● cavebox
        State: running
         Jobs: 0 queued
       Failed: 0 units
        Since: Wed 2017-10-11 13:45:12 +04; 1 day 3h ago
       CGroup: /
               ├─user.slice
               │ └─user-1000.slice
               │   ├─user@1000.service
       ... etc.

I suggest to apply the same coloring that is already applied with `systemctl status XXXX.service`, consistently. For example, perhaps color `●`, and maybe `running`, in green when everything is ok, as well as other colors for other statuses, in accordance with `systemctl status *.service`.

**Comment by zdzichu** [comment]
But it is colored… maybe something wrong with your terminal?
![image](https://user-images.githubusercontent.com/496236/31564001-9fd83264-b061-11e7-8fa0-aa689f5855b7.png)

**Comment by al-caveman** [comment]
Yes, it's red for `degraded` when, say, a unit fails. However, it is never *green* when all units are successfully operational. Hence, I think, the same coloring policy as one used in `systemctl status xxxx.service` is not applied with `systemctl status` as the latter lacks the green color.

**Comment by boucman** [comment]
just created #7094 to fix this, please test...

**Comment by yuwata** [comment]
Now #7094 is merged. Let's close this.
