### ISSUE TITLE
systemd-logind's IP sandbox breaks nss-nis and suchlike

### ISSUE THREAD

**Issue by jojoax** [systemd/systemd#7074]
### Submission type:  Bug report
After System upgrading (2017-10-12) systemd-235.0-1-x86_64.pkg.tar.xz on Arch Linux, no user X11 Usersession login was possible.

Plasma, XFCE4, Gnome failed, by thorwing a copnnect problem to dbus.
"Could not sync environment to dbus"

### In case of bug report: Expected behaviour you didn't see
Graphical Login with mostly all GUI systems does not work dur connection problem to dbus.

### In case of bug report: Unexpected behaviour you saw
Login in GUI Session took a long time, afterwards it crashed with "dbus connect timeout".

### In case of bug report: Steps to reproduce the problem
Steps to reproduce:
1. Get Home from company server (here a Debian V9 exporting /home the classical, refer arch wiki)

server:/home /home nfs nofail,_netdev,x-systemd.requires=network-online.target,x-systemd.device-timeout=1 0 0
server:/srv/pkg /var/cache/pacman/pkg nfs nofail,_netdev,x-systemd.requires=network-online.target,x-systemd.device-timeout=1 0 0

2. mount User special directories like (this was done due performance issues with kde and thunderbird)
LABEL=pc6root /home/jojo/.config btrfs _netdev,subvol=jojo/config,rw,relatime,space_cache,ssd_spread,ssd,discard,compress=lzo,x-systemd.requires=remote-fs.target 0 0
LABEL=pc6root /home/jojo/.local btrfs _netdev,subvol=jojo/local,rw,relatime,space_cache,discard,ssd,ssd_spread,compress=lzo,x-systemd.requires=remote-fs.target 0 0
LABEL=pc6root /home/jojo/.cache btrfs _netdev,subvol=jojo/cache,rw,relatime,space_cache,ssd,ssd_spread,discard,compress=lzo,x-systemd.requires=remote-fs.target 0 0
LABEL=pc6root /home/jojo/.kde btrfs _netdev,subvol=jojo/kde,rw,relatime,space_cache,ssd,ssd_spread,discard,compress=lzo,x-systemd.requires=remote-fs.target 0 0
LABEL=pc6root /home/jojo/.kde4 btrfs _netdev,subvol=jojo/kde4,rw,relatime,space_cache,ssd,ssd_spread,discard,compress=lzo,x-systemd.requires=remote-fs.target 0 0
LABEL=pc6root /home/jojo/.thunderbird btrfs _netdev,subvol=jojo/email,rw,relatime,space_cache,ssd,ssd_spread,discard,compress=lzo,x-systemd.requires=remote-fs.target 0 0

3- Install NIS Environment to get user auth via nis (refer arch wiki)
- use lightdm and try to login with any user with a standard user session, which is using dbus like plasma, xfce, gnome

... creating the session fails here at 3 sattelite systems.

After downgrading to v234
root@pc6:/var/cache/pacman/pkg# pacman -U systemd-234.11-9-x86_64.pkg.tar.xz systemd-sysvcompat-234.11-9-x86_64.pkg.tar.xz 

Everything was working again.

**Comment by ht990332** [comment]
Same issue here. I may or may not have been able to log onto Gnome once after the update but then it broke.
Downgrading to 234.11-9 made logging into X11 sessions possible again.

**Comment by jojoax** [comment]
@hussamT : Is your setup also NIS + NFS ?

@all:
I recognized also, that during login attempt the tmpfs is NOT to be mounted to /run/user/$UID.
And waiting for dbus there is a long timer before an error / timeout occours.

**Comment by ht990332** [comment]
No, just local.
So it could be a different issue that also regressed in 235. But the symptoms are the same. I could not longer log onto gnome. it would stall trying to login then take me back to the greeter.
What does 'loginctl list-sessions' say after you fail to log into an X11 session?

**Comment by wofferl** [comment]
Same issue. Login today into kde fails with "Could not sync environment to dbus"

I use a NIS+NFS Setup

There is an error related to yp before the session fails.
```
Okt 16 07:59:29 wolfi.intern sddm[372]: Authenticated successfully
Okt 16 07:59:29 wolfi.intern sddm-greeter[1047]: Message received from daemon: LoginSucceeded
Okt 16 07:59:29 wolfi.intern sddm-helper[5912]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
Okt 16 07:59:29 wolfi.intern sddm-helper[5912]: pam_unix(sddm:session): session opened for user nothdurftw by (uid=0)
Okt 16 07:59:29 wolfi.intern systemd-logind[342]: do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted
Okt 16 07:59:54 wolfi.intern sddm-helper[5912]: pam_systemd(sddm:session): Failed to create session: Die Wartezeit für die Verbindung ist abgelaufen
Okt 16 07:59:54 wolfi.intern sddm-helper[5912]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_open_session
Okt 16 07:59:54 wolfi.intern sddm-helper[5912]: pam_kwallet5(sddm:session): pam_kwallet5: final socket path: /tmp/kwallet5_nothdurftw.socket
Okt 16 07:59:54 wolfi.intern sddm-helper[5912]: Starting: "/usr/share/sddm/scripts/Xsession \"/usr/bin/startkde\""
Okt 16 07:59:55 wolfi.intern sddm-helper[7690]: Adding cookie to "/home/nothdurftw/.Xauthority"
Okt 16 07:59:55 wolfi.intern sddm-helper[984]: [PAM] closeSession: Erstellen/Entfernen eines Eintrags für die angegebene Sitzung nicht möglich
Okt 16 07:59:55 wolfi.intern sddm-helper[984]: pam_systemd(sddm-greeter:session): Failed to release session: Die Wartezeit für die Verbindung ist abgelaufen
Okt 16 07:59:55 wolfi.intern sddm-helper[984]: [PAM] Ended.
Okt 16 07:59:55 wolfi.intern sddm[372]: Auth: sddm-helper exited successfully
Okt 16 07:59:55 wolfi.intern sddm[372]: Greeter stopped.
Okt 16 07:59:55 wolfi.intern sddm[372]: Session started
```

After downgrading to 234.11-9 it works again.

**Comment by riesebie** [comment]
Debian sid systemd 235-2 Debian bug [#878625](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878625)

Login as a NIS user with NFS home journalctl tells:
````
systemd-logind[666]: do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted
pam_systemd(login:session): Failed to create session: Connection timed out
````
User is logged in after a while and there is no /run/user/UID

Running Debian's 234-3 from testing runs just fine.

Running a kernel with `CONFIG_CGROUP_BPF is not set` there are no
errors and the NIS user is logged in quite fast. But then systemd
tells:
````
File /lib/systemd/system/systemd-udevd.service:32 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
````

**Comment by fsateler** [comment]
It seems to me that any service that might perform NSS operations can't have `IPAddressDeny=any` , which systemd-login does. Does running 235 with that line removed fix the issue?

**Comment by riesebie** [comment]
I commented `IPAddressDeny=any` in both `systemd-udevd.service` and
`systemd-logind.service`. All runs fine now :-)

**Comment by riesebie** [comment]
Commenting `IPAddressDeny=any` in `systemd-logind.service` only seems to run very well, though.

**Comment by poettering** [comment]
yeah, we run logind in an IP networking sandbox these days. And yes, if you configured a network facing NSS module, then this will cause friction, and NSS lookups will fail. 

Quite frankly, loading a module into every process that implicitly opens it up to network communication, and thus adds a network attack surface to every single process (even to something as insignificant and benign as `ls`) is a questionable choice. I am pretty sure such NSS modules should never talk to the network directly, but do so via a locked down, local daemon that can sanitize communications. Either use nscd or such (which is a basically a generic, caching NSS proxy), or sssd or anything like it.

Anyway, I don't think we should change systemd in this regard now. We should add some docs around this however, and leave it to downstreams to figure whether they want to patch out the sandboxing again. That said, I am pretty sure in the interest of security for the many the nss_ldap, nss_nis packages of this world should probably instead drop-in a unit file extension into /usr/lib/systemd/system/systemd-logind.service.d/ that turns off the sandbox locally where people want to use this stuff.

**Comment by riesebie** [comment]
Installing nscd solved the problem. Asked nis maintainer to put nscd to "Depends" at install time. Thanks for the hint @poettering .

**Comment by mdrslmr** [comment]
I'm running into this issue using a home directory via AFS on an arch linux system. Commenting out the IPAddressDeny=any line helps to login again.

I understand that this has been introduced for security reasons but on my system it creates a core dump (with IPAddressDeny=any active) which is obviously a buggy reaction:

```
systemd-coredump[1038]: Process 446 (systemd-logind) of user 0 dumped core.
Stack trace of thread 446:
     #0  0x00007f930134f246 connect (libc.so.6)     
     #1  0x00007f930137c7ac clnttcp_create (libc.so.6)  
      #2  0x00007f930137e784 __libc_rpc_getport (libc.so.6)
      #3  0x00007f930137c75b clnttcp_create (libc.so.6)  
      #4  0x00007f92fd678787 n/a (libnsl.so.1)
      #5  0x00007f92fd678f14 n/a (libnsl.so.1)
      #6  0x00007f92fd679089 n/a (libnsl.so.1)
      #7  0x00007f92fd67917b yp_match (libnsl.so.1)  
      #8  0x00007f92fd891e63 _nss_nis_getpwuid_r (libnss_nis.so.2)
      #9  0x00007f930131b5d5 getpwuid_r@@GLIBC_2.2.5 (libc.so.6)
      #10 0x00007f930131ad39 getpwuid (libc.so.6)    
      #11 0x0000558c5ea322ce n/a (systemd-logind)
      #12 0x0000558c5ea32a98 n/a (systemd-logind)
      #13 0x00007f9300e7da84 n/a (libsystemd-shared-235.so)
      #14 0x00007f9300e7ee87 bus_process_object (libsystemd-shared-235.so)
      #15 0x00007f9300f0a9e8 n/a (libsystemd-shared-235.so)
      #16 0x00007f9300f0ae04 n/a (libsystemd-shared-235.so)
      #17 0x00007f9300f59730 n/a (libsystemd-shared-235.so)
      #18 0x00007f9300f5996b sd_event_dispatch (libsystemd-shared-235.so)
      #19 0x00007f9300f59aee sd_event_run (libsystemd-shared-235.so)
      #20 0x0000558c5ea20661 n/a (systemd-logind)
      #21 0x00007f9301278f6a __libc_start_main (libc.so.6)
      #22 0x0000558c5ea207da n/a (systemd-logind)
```

**Comment by poettering** [comment]
@mdrslmr do you see anything else in the logs, why it might have dumped core? could this be because the NSS module just hangs and keeps retrying, and systemd's watchdog logic then assumes the process hangs?

Anyway, I am pretty sure that:
1. your nss module should not talk to the network directly
2. your nss module should have some smarter strategy for dealing with networking issues than to just hang

That said, as mentioned this is indeed a compat breakage to some level, but I'd claim it's a good and necessary one.

**Comment by mdrslmr** [comment]
@poettering  Thanks for the quick reply. 

I think it starts with:
```
systemd-logind[446]: do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted
```

There are also some messages about watchdogs. Below I put the logging
messages in reverse order and slightly modified:
```
systemd-coredump[1038]: Process 446 (systemd-logind) of user 0 dumped core.
      Stack trace of thread 446:
      #0  0x00007f930134f246 connect (libc.so.6)
      #1  0x00007f930137c7ac clnttcp_create (libc.so.6)
      #2  0x00007f930137e784 __libc_rpc_getport (libc.so.6)
      #3  0x00007f930137c75b clnttcp_create (libc.so.6)
      #4  0x00007f92fd678787 n/a (libnsl.so.1)
      #5  0x00007f92fd678f14 n/a (libnsl.so.1)
      #6  0x00007f92fd679089 n/a (libnsl.so.1)
      #7  0x00007f92fd67917b yp_match (libnsl.so.1)
      #8  0x00007f92fd891e63 _nss_nis_getpwuid_r (libnss_nis.so.2)
      #9  0x00007f930131b5d5 getpwuid_r@@GLIBC_2.2.5 (libc.so.6)
      #10 0x00007f930131ad39 getpwuid (libc.so.6)
      #11 0x0000558c5ea322ce n/a (systemd-logind)
      #12 0x0000558c5ea32a98 n/a (systemd-logind)
      #13 0x00007f9300e7da84 n/a (libsystemd-shared-235.so)
      #14 0x00007f9300e7ee87 bus_process_object (libsystemd-shared-235.so)
      #15 0x00007f9300f0a9e8 n/a (libsystemd-shared-235.so)
      #16 0x00007f9300f0ae04 n/a (libsystemd-shared-235.so)
      #17 0x00007f9300f59730 n/a (libsystemd-shared-235.so)
      #18 0x00007f9300f5996b sd_event_dispatch (libsystemd-shared-235.so)
      #19 0x00007f9300f59aee sd_event_run (libsystemd-shared-235.so)
      #20 0x0000558c5ea20661 n/a (systemd-logind)
      #21 0x00007f9301278f6a __libc_start_main (libc.so.6)
      #22 0x0000558c5ea207da n/a (systemd-logind)
systemd-logind[1041]: Watching system buttons on /dev/input/event0 (HID 046a:0011)
systemd-logind[1041]: Watching system buttons on /dev/input/event2 (Sleep Button)
systemd-logind[1041]: Watching system buttons on /dev/input/event3 (Power Button)
systemd[1]: Started Login Service.
systemd-logind[1041]: New seat seat0.
systemd[1]: Starting Login Service...
systemd[1]: Stopped Login Service.
systemd[1]: systemd-logind.service: Scheduled restart job, restart counter is at 1.
systemd[1]: systemd-logind.service: Service has no hold-off time, scheduling restart.
systemd[1]: systemd-logind.service: Failed with result 'watchdog'.
systemd[1]: systemd-logind.service: Main process exited, code=dumped, status=6/ABRT
systemd[1]: Started Process Core Dump (PID 1037/UID 0).
systemd[1]: Created slice system-systemd\x2dcoredump.slice.
systemd[1]: systemd-logind.service: Killing process 446 (systemd-logind) with signal SIGABRT.
systemd[1]: systemd-logind.service: Watchdog timeout (limit 3min)!
sudo[1016]: pam_krb5(sudo:setcred): pam_sm_setcred: exit (success)
sudo[1016]: pam_krb5(sudo:setcred): pam_sm_setcred: entry (delete|silent)
sudo[1016]: pam_unix(sudo:session): session closed for user root
sudo[1016]: pam_systemd(sudo:session): Failed to create session: Connection timed out
upowerd[800]: treating change event as add on /sys/devices/pci0000:00/0000:00:1a.1/usb4/4-2/4-2:1.2/0003:046D:C52B.0004/0003:046D:4009.0005/powe
kernel: logitech-hidpp-device 0003:046D:4009.0005: HID++ 2.0 device connected.
sudo[1016]: pam_systemd(sudo:session): Asking logind to create session: uid=0 pid=1016 service=sudo type=tty class=user desktop= seat= vtnr=0 tt
sudo[1016]: pam_systemd(sudo:session): pam-systemd initializing
sudo[1016]: pam_unix(sudo:session): session opened for user root by sel(uid=0)
sudo[1016]: pam_krb5(sudo:setcred): pam_sm_setcred: exit (success)
sudo[1016]: pam_krb5(sudo:setcred): (user afsuser) refreshing ticket cache /tmp/krb5cc_17700
sudo[1016]: pam_krb5(sudo:setcred): pam_sm_setcred: entry (reinit)
sudo[1016]:  afsuser : TTY=tty3 ; PWD=/afs/organization.net/user/d/adsuser ; USER=root ; COMMAND=/usr/bin/pacdiff
sudo[1016]: pam_krb5(sudo:auth): pam_sm_authenticate: exit (success)
sudo[1016]: pam_krb5(sudo:auth): (user afsuser) temporarily storing credentials in /tmp/krb5cc_pam_CdbSq7
sudo[1016]: pam_krb5(sudo:auth): user afsuser authenticated as adsuser@ORGANIZATION.NET
sudo[1016]: pam_krb5(sudo:auth): (user afsuser) attempting authentication as adsuser@ORGANIZATION.NET
sudo[1016]: pam_krb5(sudo:auth): pam_sm_authenticate: entry (silent)
sudo[1016]: pam_unix(sudo:auth): authentication failure; logname=afsuser uid=17700 euid=0 tty=/dev/tty3 ruser=adsuser rhost=  user=adsuser
/usr/bin/gpm[434]: Request on 6 (console 3)
/usr/bin/gpm[434]: *** info [daemon/processrequest.c(42)]:
/usr/bin/gpm[434]: disabling pasting per request from virtual console (3)
/usr/bin/gpm[434]: *** info [daemon/disable_paste.c(28)]:
/usr/bin/gpm[434]: Request on 6 (console 3)
/usr/bin/gpm[434]: *** info [daemon/processrequest.c(42)]:
login[998]: LOGIN ON tty3 BY afsuser
login[998]: pam_krb5(login:setcred): pam_sm_setcred: exit (success)
login[998]: pam_krb5(login:setcred): pam_sm_setcred: entry (reinit)
login[998]: pam_systemd(login:session): Failed to create session: Connection timed out
pulseaudio[846]: E: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possibl

```

**Comment by poettering** [comment]
So, yes, your nss-nis module froze, trying to connect to your server, and then systemd noticed logind hanging due to this, and aborted it and restarted it. So all is actually working the way it should, even if that's surprising. 

Please ask your downstream distribution to either:
1. include a systemd-logind.service.d/ snippet in your nss-nis package that turns off the IP firewalling logic for logind
2. or patching systemd-logind.service for everybody to disable it distro-wide (which I'd really not recommend though, compromising the security for everybody just because for compat of a nowadays pretty niche nss module that does some very questionnable things doesn't sound like the best way out to me)

**Comment by mdrslmr** [comment]
@poettering Ok. So that frozen nss-nis module is ypbind?
And I guess, if I understood your previous reply right, the best would be if ypbind would change in some way.

**Comment by poettering** [comment]
@mdrslmr well, I doubt that NIS/YP still receives a lot of development. However, the simple fact is that today systems are not built that way anymore: inserting a module into every single local process that talks directly to the network is just not that great an idea today.

nscd or sssd might be a good way out for you btw.

**Comment by poettering** [comment]
I added PR #7343 now, which adds a specific note about this to NEWS.

**Comment by imsedgar** [comment]
I want to say that a crash of a system service like systemd-logind in a situation which is predictable is always a bad solution.

systemd-logind may restart in a situation like above, ok, but it should be done in a clean way. It may (depending on log level) log a message about the situation (e.g. no network access allowed for this service, occured in nss / nis ...), and stop and restart without a crash and without a backtrace. The exception should be catched by code as described above, not leaving it to the default handler.

See also https://bugzilla.redhat.com/show_bug.cgi?id=1591509 .

**Comment by poettering** [comment]
@imsedgar it's not precisely "crashing". It's being aborted because it froze in the NSS calls. Yes, that results in a coredump, but that's to make this easy to debug and it's not a normal "crash"...

**Comment by imsedgar** [comment]
@poettering 
In https://bugzilla.redhat.com/show_bug.cgi?id=1591509 systemd-logind is killed by SIGSEGV - that seems to me like a "normal" crash that should never occur.

In https://bugzilla.redhat.com/show_bug.cgi?id=1591510 systemd-udevd is killed by SIGABRT - yes, this may be intended abort, but a coredump is always confusing and alarming system administrators and telling them that there's usually something wrong in the code. If you know that you abort because of a timeout, I think it would be better to tell this the administrator. For debugging, what about an option that can be set somewhere (e.g. in systemd unit file, or some configuration file), that will create a coredump only if the debug flag is set? You may also give a hint in the message how to get a coredump.

**Comment by poettering** [comment]
if you see a segfault (SIGSEGV) then this is a memory corruption most likely and that's never OK. It's unrelated to any watchdog issues or hangs in that case. In that case it appears the nss-nis module is at fault in some way, judging by the linked coredump. Please report this to the nss-nis people

**Comment by poettering** [comment]
> In https://bugzilla.redhat.com/show_bug.cgi?id=1591510 systemd-udevd is killed by SIGABRT - yes, this may be intended abort, but a coredump is always confusing and alarming system administrators and telling them that there's usually something wrong in the code. If you know that you abort because of a timeout, I think it would be better to tell this the administrator. For debugging, what about an option that can be set somewhere (e.g. in systemd unit file, or some configuration file), that will create a coredump only if the debug flag is set? You may also give a hint in the message how to get a coredump.

Well, I am not sure that just leaving udevd hang and thus the system freeze is any better. We send SIGABRT if it it doesn't send the watchdog events often enough so that a stack trace ends up in the logs to make this debuggable. I mean, if udevd or any other service hangs and doesn#t send watchdog events anymore, then there's generally an issue, and you have the choice to accept the hang, and not do anything about it, or to try to recover from it and collect information about it. We opt for the latter.

**Comment by cedric-roux** [comment]
Just for the record, for those of us thinking it is a reasonable idea to have a NIS/NFS home directory and not wanting this stinking piece of shit called systemd, vomited out of some sick brains on this little dirty planet, and facing FUCKING AGAIN this fucking problem after an update of this shitty ubuntu 18.04, the fucking file `systemd-logind.service` where to disable this fucking option `IPAddressDeny=any` has moved from `/usr/lib/systemd/system/systemd-logind.service.d/` to `/lib/systemd/system` because some fucking idiot thinks we losers from the world who are so stupid that we don't give a fucking shit about your fucking ideas of what is a secure system found it amusing to piss us off again by moving their shitty vomit all around the place.

Cannot some sanity enter your brains, for shit's fuck?

Fuck.
