### ISSUE TITLE
Enable Target File Error

### ISSUE THREAD

**Issue by Kolano** [systemd/systemd#7077]
### Submission type
 - Bug report

### systemd version the issue has been seen with

> systemd 229
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

### Used distribution

> Ubuntu 16

### In case of bug report: Expected behaviour you didn't see

> Target enabled without file error.

### In case of bug report: Unexpected behaviour you saw

> Enabling a custom target (via "systemctl enable pass.target") results in a "Failed to execute operation: No such file or directory" error, though the target does seem to be enabled.

### In case of bug report: Steps to reproduce the problem

> Try to enable a target with systemctl

**Comment by keszybz** [comment]
Please report a bug in your distribution. The maintainers there should be able to help you.
Version 229 is too old for upstream, we are currently at 235.
