### ISSUE TITLE
we need to call name_to_handle_at() in a loop if EOVERFLOW happens, and resize the buffer

### ISSUE THREAD

**Issue by jeevarathinam-dhanapal** [systemd/systemd#7082]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd version - 234. Facing this issue in the CoreOS-1520.6.0

> …

### In case of bug report: Expected behaviour you didn't see
new hostname is set

> …

### In case of bug report: Unexpected behaviour you saw
 Ran - hostnamectl set-hostname k8s-worker-1507708889.ops1.srcclr.com
 Getting "Could not set property: Connection timed out"
> …

### In case of bug report: Steps to reproduce the problem

> … hostnamectl set-hostname k8s-worker-1507708889.ops1.srcclr.com

**Comment by poettering** [comment]
most likely that means your dbus-daemon is somehow borked. Either way, without relevant logs there's little we can do. Please check logs if there's anything interesting regarding this issue there. Does "busctl" work and show the hostnamed service being on the bus?

**Comment by ajeddeloh** [comment]
I think this is actually this bug: https://github.com/coreos/bugs/issues/2193 (see also https://github.com/coreos/bugs/issues/2190#issuecomment-336597441) and `hostnamectl` is timing out because `systemd-hostnamed` is failing.

I haven't been able to reproduce this myself yet, but a number of people have encountered it. It's failing in [`setup_namepace()`](https://github.com/systemd/systemd/blob/v234/src/core/namespace.c#L877) because something is getting EOVERFLOW. Given that [these logs](https://gist.githubusercontent.com/parabolic/69f3fae95a4cd26a9cc56ad5071d8a8d/raw/6736a49ec9d428def2f1aab5cf209e72dbd91ab5/gistfile1.txt) (captured with log level debug) don't show any messages from `apply_mount()`, and that the unit doesn't use a `RootImage` or `RootDirectory`, I'd guess it has to be either [this call to `unshare()`](https://github.com/systemd/systemd/blob/v234/src/core/namespace.c#L1042), [this call to `mount()`](https://github.com/systemd/systemd/blob/v234/src/core/namespace.c#L1050), or [this call to `fopen()`](https://github.com/systemd/systemd/blob/v234/src/core/namespace.c#L1092) that's returning EOVERFLOW. 

Note: I'm linking to the v234 source since the error handling around this changed between v235 and v234.

**Comment by poettering** [comment]
@ajeddeloh any chance you can run "strace -f -p 1 -s500" and then reproduce this issue? That should tell us what syscall is at fault – if it is a syscall.

In systemd's own sources there's very little code that sets EOVERFLOW, and I doubt they are relevant here.

**Comment by ajeddeloh** [comment]
I still can't reproduce it, but I'll pass that along.

**Comment by ajeddeloh** [comment]
Relaying from the coreos bug:
Here are the logs of "strace -f -p 1 -s500": https://gist.githubusercontent.com/parabolic/e864d38fe963cc5e58e566075187d3b3/raw/8b2a1065d629b5982495c0b73858843c4e499d76/strage.log

It looks like `name_to_handle_at` is where the EOVERFLOW is coming from. It only happens when `name_to_handle_at` is called on the fd opened for `/mnt`. Looks like the calls are in `src/basic/mount-util.{c,h}`, but nothing looks obviously wrong.

**Comment by poettering** [comment]
EOVERFLOW from name_to_handle_at() has the following meaning according to the man page:
```
       EOVERFLOW
              The handle->handle_bytes value passed into the call was too small.  When this error occurs, handle->handle_bytes is updated to indicate the required size for the handle.

```

**Comment by poettering** [comment]
The docs are crap though. They suggests, that MAX_HANDLE_SZ is the actual maximum size for the buffer, but apparently it isn't...

**Comment by poettering** [comment]
I figure we have to rework name_to_handle_at() invocations to do a resize loop around the handle, given that MAX_HANDLE_SZ is apparently only suitable as start value for such an algorithm, not the boundary... Grrr..

Irony of it all is that we actually don#t care at all about the handle at all... What we are interested in is the mnt_id the call also returns...

**Comment by poettering** [comment]
Fix waiting in #7395

**Comment by poettering** [comment]
@jeevarathinam-dhanapal @ajeddeloh what's the backing file system this is triggered on? overlayfs?

**Comment by poettering** [comment]
Judging by the strace it's a mount point /mnt/efs that is nfs4 that triggers this, actually.

**Comment by poettering** [comment]
Note that this issue

**Comment by poettering** [comment]
Let's reopen this for now, see my comments in https://github.com/systemd/systemd/pull/7395#issuecomment-346405121 — there's something else borked here.

**Comment by poettering** [comment]
I believe a proper fix is now waiting in #7436. PTAL

**Comment by ajeddeloh** [comment]
I just tried cherry-picking the commits from https://github.com/systemd/systemd/pull/7436 and https://github.com/systemd/systemd/pull/7395 and built a fresh Container Linux image with it. It now fails with `Failed to set up mount namespacing: Invalid argument`. I did find out how to reproduce it, at least with Container Linux.

1) Run systemd on an aws ec2 instance
2) setup EFS
3) mount the EFS on `/mnt/<something>` (see the [aws documentation](https://aws.amazon.com/getting-started/tutorials/create-network-file-system/))
4) restart a service that has `ProtectSystem=strict`:
```
systemctl restart systemd-resolved
```
5) It should fail to start.

There shouldn't be anything Container Linux specific about the failure. I was _not_ able to reproduce locally by running an nfs server and client on the same instance. I have only been able to reproduce when mounting EFS.

**Comment by poettering** [comment]
Can you provide an strace of this? i.e. "strace -p 1 -s 500 -f -o log" in one window, then start the service that triggers that with "systemctl start …" in another, and C-c the strace, and paste the relevant bits from the "log" file this created somewhere. The relevant bits is the trace of the code that ran in the child process right before it ended and logged the namespace error message.

**Comment by ajeddeloh** [comment]
Looks like it's happening at the same place. After getting the initial EOVERFLOW it tries again then gets EINVAL. 

```
...
950   openat(AT_FDCWD, "/mnt", O_RDONLY|O_DIRECTORY|O_CLOEXEC|O_PATH) = 4
950   name_to_handle_at(0x4, 0x560b1d032665, 0x560b1d031ad0, 0x7fffe575c204, 0) = -1 EOVERFLOW (Value too large for defined data type)
950   name_to_handle_at(0x4, 0x560b1d032665, 0x560b1d031dd0, 0x7fffe575c204, 0) = -1 EINVAL (Invalid argument)
...
```

**Comment by poettering** [comment]
@ajeddeloh hmm, if you version includes #7436, then that suggests some kernel issue. With that commit in place EOVERFLOW will cause us to ask again, with a buffer the size returned the first time. If that results in EINVAL then this suggests the buffer returned the first time is actually too large or so...

@neilbrown any idea what might be going on there? apparently the NFS4 implementation still doesn't like our name_to_handle_at() invocations: the first invocation gets EOVERFLOW, the second invocation gets EINVAL, even though the buffer is passed in as the one returned by the first call. Documented are only two reasons for EINVAL: invalid flags or too large buffer... It's definitely not invalid flags as we pass those as 0, as the strace above shows, but the size too large would suggest the first name_to_handle invocation lied to us with the size it returned... Any idea?

I am tempted to just tape over this: if n_t_h_a returns EINVAL, fall back to other means...

**Comment by poettering** [comment]
Prepped #7517 now, which tapes over this. @ajeddeloh any chance you can give this a whirl?

@neilbrown i'd still be interested figuring out what really is going on here though...

**Comment by neilbrown** [comment]
This EINVAL almost certainly means that the passed-in size was > MAX_HANDLE_SZ.  This implies that the size returned with EOVERFLOW was larger than MAX_HANDLE_SZ. 
This could happen if an NFSv4 filesystem uses full-size filehandles.  NFSv4 file handles are at most 128 bytes.  Most servers use fewer than 64 bytes.  When you call name_to_handle_at() on an NFS filesystem, the Linux NFS client adds a 3 word (12 bytes) header so if the server filehandle exceeds 116 bytes, name_to_handle_at() will fail to return anything useful.
I suspect Amazon EFS does use 128 bytes filehandles, and I think this is a kernel bug.
I'll submit a patch.

**Comment by poettering** [comment]
@neilbrown ah, excellent. thanks for tracking that down! I guess #7517 is the way to go then, so that we can deal with EINVAL in that case too, and fallback to simpler methods. Thanks!

**Comment by poettering** [comment]
@ajeddeloh any chance you can have a look at #7517 and see if it fixes things for you for good?

**Comment by poettering** [comment]
@neilbrown hmm, regarding the kernel patch you sent: if the new MAX_HANDLE_SZ will eventually show up in userspace, and people recompile their code with it, and use the new MAX_HANDLE_SZ as start value for sizing the file handle structure, then it will consistently result in EINVAL when run on old kernels...

I figure this means the only safe way to use name_to_handle_at() from userspace is either to start with a 0-size file handle or with the original size, but not with the one defined in the headers... This definitely deserves documentation...

**Comment by poettering** [comment]
to protect us against increased MAX_HANDLE_SZ API borkages, I prepped PR #7523. Hope that makes sense.

**Comment by ajeddeloh** [comment]
@poettering sorry for the delay but #7517 does fix it.
