### ISSUE TITLE
nss-myhostname: fails to resolve gateway

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#7084]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v235

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> $ getent ahosts gateway            
> 10.0.0.1     STREAM gateway
> 10.0.0.1     DGRAM  
> 10.0.0.1     RAW

### In case of bug report: Unexpected behaviour you saw

> $ getent ahosts gateway
> $ echo $?
> 2

### In case of bug report: Steps to reproduce the problem

> Install `systemd` `v235` and try to resolve `gateway`.

**Comment by eworm-de** [comment]
Oh, looks like this is expected... Hold on.

**Comment by mbiebl** [comment]
> Oh, looks like this is expected... Hold on.

Yes, unless you distro has compiled systemd with ```-Dcompat-gateway-hostname=true```. The default is ```false```

**Comment by eworm-de** [comment]
Nah, we try to keep upstream settings in Arch. ;)

Wondering if we want to adjust the documentation if compatibility is enabled...
