### ISSUE TITLE
systemd-resolved DNS search only works when *all* domains are marked for search

### ISSUE THREAD

**Issue by wdoekes** [systemd/systemd#7086]
Problems:

* DNS search domains only works when *all* domains on the interface are marked for search.

Forgive me if this has been fixed in the mean time. A quick google search did not turn up any similar problems.

Versions:
```
# dpkg -S /lib/systemd/systemd-resolved
systemd: /lib/systemd/systemd-resolved
# dpkg -l systemd | grep ^ii
ii  systemd        232-21ubuntu5 amd64        system and service manager
```

Yes, I know this is an older systemd, but it's the one in Ubuntu Zesty, so it's used by quite a lot of people. If this has been fixed in a newer systemd I can certainly move this ticket to launchpad. Hopefully with an appropriate patch/changeset.

**Steps to reproduce**

Before VPN:
```
# systemd-resolve --status
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
...

Link 3 (eno1)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 91.194.X.X
                      91.194.X.Y
```
After starting VPN. It pushes the domains, but not search:
```
Link 17 (tap0)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 10.X.X.X
                      10.X.Y.Z
          DNS Domain: ~private.lan
                      ~X.X.10.in-addr.arpa
```
The private.lan queries work:
```
# systemd-resolve test.private.lan | head -n1
test.private.lan: 10.X.X.X

# host test.private.lan
test.private.lan has address 10.X.X.X
# host 10.X.X.X
X.X.X.10.in-addr.arpa domain name pointer test.private.lan.
```
At this point I don't have any domain search, but I *do want it*:
```
# systemd-resolve test
test: resolve call failed: All attempts to contact name servers or networks failed
```
Switching the first `~private.lan` to `private.lan` should make it work:
```
# busctl get-property org.freedesktop.resolve1 /org/freedesktop/resolve1/link/_317 \
    org.freedesktop.resolve1.Link Domains
a(sb) 2 "private.lan" true "X.10.in-addr.arpa" true

# busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 \
    org.freedesktop.resolve1.Manager SetLinkDomains \
    'ia(sb)' 17 2 "private.lan" false "X.10.in-addr.arpa" true

# systemd-resolve --status
...
Link 17 (tap0)
...
          DNS Domain: private.lan
                      ~X.10.in-addr.arpa
...

# systemd-resolve test
test: resolve call failed: All attempts to contact name servers or networks failed
```
*The problem is here. Why does it not search for test.private.lan?*

First when switching *both* search domains (the 2nd `false`), it works:
```
# busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 \
    org.freedesktop.resolve1.Manager SetLinkDomains \
    'ia(sb)' 17 2 "private.lan" false "X.10.in-addr.arpa" false

# systemd-resolve --status
...
Link 17 (tap0)
...
          DNS Domain: private.lan
                      X.10.in-addr.arpa
...

# systemd-resolve test | head -n1
test: 10.X.X.X
```

Thanks for looking into this.

**Comment by poettering** [comment]
Sorry, but 232 is simply too old, and resolved has changed heavily since then. Please retry with 235, before we look into this. Thank you.

**Comment by wdoekes** [comment]
Thanks for the reply. I'll wait for my OS or another reason to upgrade systemd-resolved and test again then. Since everything is packaged together, swapping out just the resolved is not that easy, and I'm not sure which Ubuntu patches are needed to create a Ubuntu-friendly 235-build from vanilla (i.e. more work than I'm willing to put in for this little annoyance).

To be continued at a different time...

**Comment by wdoekes** [comment]
For the record: systemd 234-2ubuntu12.1 (Ubuntu Artful) also suffers from this problem.
