### ISSUE TITLE
Handle change to /etc/machine-id during /run to /var flush

### ISSUE THREAD

**Issue by geissonator** [systemd/systemd#7092]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> v232

### Used distribution

> https://github.com/openbmc

### Feature Request

openbmc mounts the file systems, specifically /etc/machine-id after journald has started.  Because of this, journald generates a machine-id and uses that to create the directory in /run/log/journal/machine-id.  When the "systemd-journal-flush.service" is launched after the file systems are mounted properly, it writes into /var/log/journal/ with that same generated machine-id.  The problem is that the persistent file system mounted over /etc/machine-id has a machine-id that is different then the one create and written by journald.

And then when you use "journalctl" to look at the journal data, it uses the real /etc/machine-id which does not match with what journald is using so you end up getting "No journal files were found".  I can do a workaround where I use journalctl --merge to view the data but that's not really a long term solution.

My proposal with this enhancement request is to put a bit of logic in src/journal/journald-server.c:server_flush_to_var() to check if the /etc/machine-id matches with the already stored one for /run usage.  If it doesn't match, then when moving from /run to /var, it will use the new /etc/machine-id for the directory name.

**Comment by poettering** [comment]
We simply do not support that. The machine id must be available at the moment the initrd to host transition happens and should be considered immutable from that point on. The idea of the machinr id is that it is stable (unlike th hostname for example) and changing it dynamically at runtime defeats the whole idea.

Sorry but this simply not supported and would redefine the machine id in a way that makes it pointless.

Its not just journald that breaks if you make the machine id dynamic. The machind id is used all over systemd and outside of it and you cannot redefine it like this breaking all assumptions about it and thus breaking all kind of software.

Sorry

**Comment by geissonator** [comment]
ok, thanks for the quick feedback, we'll look into other options.
