### ISSUE TITLE
Ellipsis in loginctl --full seat-status seat0 > seatstatus.txt

### ISSUE THREAD

**Issue by ezst036** [systemd/systemd#7095]
- Request for enhancement (RFE)

### systemd version the issue has been seen with

216 and 234

### Used distribution

Manjaro 17, Debian 9, several others

### In case of bug report: Expected behaviour you didn't see

I was expecting to see a text file full of devices without any ellipses.

Additionally, I had hoped to pull this information programmatically, but I also get ellipses with the following python code block:

    import subprocess
    cmd = ["/bin/sh", "-c", "loginctl --full seat-status seat0"]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    for line in proc.stdout.readlines():
        print(line)

**Comment by poettering** [comment]
i am not sure i follow. can you please paste a short excerpt of what you expected and what you got?

**Comment by ezst036** [comment]
Thank you for the prompt reply.

Expected:
/sys/devices/pci0000:00/0000:00:12.0/usb3/3-3/3-3:1.2/0003:046D:C52B.0005/0003:046D:101A.0006/input/input7

Received:
/sys/device...:C52B.0005/0003:046D:101A.0006/input/input7

Short device addresses such as "/sys/devices/pci0000:00/0000:00:13.1/usb6" come out the same in terminal or in the text file.

**Comment by poettering** [comment]
Fix waiting in #7301.
