### ISSUE TITLE
networkd takes more time to setup netif and seems that network-online.target is irrelevant

### ISSUE THREAD

**Issue by djgera** [systemd/systemd#7103]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> I have since long time dnsmasq service on bootup for an wlan interface in ap mode. Always work. IP address is configured via networkd in a static way.

### In case of bug report: Unexpected behaviour you saw

>  Now I upgraded from system 233 to 235 then always fail.

### In case of bug report: Steps to reproduce the problem

> I made a test service file running networkctl status ap1, Wants/After set to network.target (Yes I know, is not a sync point for bootup) or network-online.target. In any case, with 235 the interface shows without an IP address. In any case with 233, interface always gets an IP address. 

Just for reference, the interface is made at startup via udev rule.

```
ATTR{address}=="e8:de:27:4e:63:2b", RUN+="/usr/bin/iw dev wifi1 interface add ap1 type __ap"
ATTR{address}=="e8:de:27:4e:63:2b", RUN+="/usr/bin/ip link set ap1 address e8:de:27:4e:63:2c"
```

Then configured by networkd with:

10-wlan.link
```
[Match]
Type=wlan
[Link]
NamePolicy=
```

20-ap1.network 
```
[Match]
Name=ap1
[Network]
Address=172.16.92.2/28
```

**Comment by draeklae** [comment]
I can confirm this occurs with 235 and not with 234.

**Comment by poettering** [comment]
have you enable systemd-networkd-wait-online.service?

cc @ssahani

**Comment by djgera** [comment]
Yes, enabled (explicit) or via depends does nothing.  Even worse enabling it, make more services fail, ie openvpn fails with operation not permitted on tun device.

**Comment by djgera** [comment]
I just workaround doing band-aided fix by adding a "sleep 1" in the ExecStartPre of the service.
I attached three log files
sd-233.txt systemd-233 (and below) just works, nothing to change. (234 also works but due many other issues I never used it).
sd-235-fail.txt Is the same service file, working all time, but fail with the new 235.
sd-235-band-aid, the workaround service.

[sd-233.txt](https://github.com/systemd/systemd/files/1420478/sd-233.txt)
[sd-235-fail.txt](https://github.com/systemd/systemd/files/1420479/sd-235-fail.txt)
[sd-235-band-aid.txt](https://github.com/systemd/systemd/files/1420480/sd-235-band-aid.txt)

PS: systemd-networkd-wait-online fail in my system after a timeout with "Event loop failed: Connection timed out", but that is another history.

**Comment by djgera** [comment]
systemd 236 still broken with this regression. Still need the workaround of "sleep 2" ("sleep 1" was too low)

what kind of "feedback" is needed?

**Comment by djgera** [comment]
just as feedback: 237 bug present.

I just changed the band-aid workaround using Restart=2

**Comment by poettering** [comment]
So this issue is 7y old now. Let's close this one. if this is still a problem, please open a new issue.
