### ISSUE TITLE
rescue mode and emergency mode won't work when the root account is locked

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#7115]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235 (and many versions before it).

### Used distribution

Debian sid (as well as Debian stretch and Debian buster)

### In case of bug report: Expected behaviour you didn't see

Rescue mode and emergency mode should give me a shell with root permissions.

### In case of bug report: Unexpected behaviour you saw

Rescue mode and emergency mode won't give me any shell. After telling me that the root account is locked, they will only allow me to boot into default mode.

### In case of bug report: Steps to reproduce the problem

For rescue mode:

1. Lock your system's root account, if you haven't already done so.
2. Reboot to GRUB.
3. Start rescue mode.

For emergency mode:

1. Lock your system's root account, if you haven't already done so.
2. Corrupt your /etc/fstab.
3. Reboot.

**Comment by grawity** [comment]
The emergency login prompt is done by `sulogin`, which is part of either "util-linux" or "shadow" – not a systemd component.

**Comment by ghost** [comment]
Some further notes:

* This was mentioned on Github by @marcosfrm [in a comment on issue 5674](https://github.com/systemd/systemd/issues/5674#issuecomment-306068919).
* This is tracked by Debian as [bug 802211](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802211).
* ~~I'm testing [my patch](https://github.com/systemd/systemd/compare/master...rhymoid:sulogin-shell-should-force) right now, which passes the `--force` option to `sulogin` unconditionally.~~ I've submitted PR #7116.

**Comment by ghost** [comment]
@grawity And two years ago, [util-linux added an option to sulogin specifically for this kind of cases](https://github.com/karelzak/util-linux/commit/7ff1162e67164cb4ece19dd809c26272461aa254). The defect is that systemd is not using that option.
