### ISSUE TITLE
systemd with TPM: unable to add image options measurement: Invalid Parameter

### ISSUE THREAD

**Issue by tSte** [systemd/systemd#7118]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235.0-1

### Used distribution

ArchLinux 64, Linux 4.9.56-1-lts and 4.13.6-1

### In case of bug report: Expected behaviour you didn't see

No message

### In case of bug report: Unexpected behaviour you saw

Message before "regular" booting messages (pls, excuse my poor terminology, I am not sure what it is really)
`Unable to add image options measurement: Invalid Parameter`

### In case of bug report: Steps to reproduce the problem

Enable Security option TPM in BIOS (I am on X1 Carbon 2017, TPM 2.0)

**Comment by poettering** [comment]
@haraldh you are the sd-boot/TPM guy

**Comment by radare** [comment]
same issue here with gpd pocket + archlinux

**Comment by sajaysurya** [comment]
Same issue with Arch + 4.13.9-1 Linux

**Comment by ghost** [comment]
Same issue with Arch + 4.13.10-1 Linux, and I also have to boot twice to start my HP ENVY 13-ab016nr.

**Comment by twilbers** [comment]
Same issue with Arch install (kernel: 4.13.9) with MSI GS73VR.

**Comment by illvart** [comment]
Same issue with Arch Linux install. Haha

**Comment by Kitsukai** [comment]
same issue here

**Comment by mattia-b89** [comment]
same here without TPM

**Comment by tSte** [comment]
I was able to "overcome" this using [EFISTUB](https://wiki.archlinux.org/index.php/EFISTUB).

**Comment by ghost** [comment]
@tSte Which bootloader did you use?

**Comment by tSte** [comment]
@vsrch systemd

**Comment by emberquill** [comment]
Same issue here. Using systemd bootloader.

**Comment by haraldh** [comment]
working on it

**Comment by keszybz** [comment]
Reporters, go forth and test ;)

**Comment by tSte** [comment]
@keszybz just updated systemd 235.38-3, ran `bootctl update` and that message is still there... any hints?

**Comment by jakebailey** [comment]
The patch isn't in any release, and hasn't been applied on Arch. The pkgrel bump yesterday is unrelated.

@keszybz I've applied the patch (using Arch's `_backports` list in their package), and the message no longer appears. Thanks for the fix!

**Comment by djpalumbo** [comment]
After updating systemd to version 236.0-2 and running `bootctl update`, the message is no longer appearing for me. FYI, I did not use `_backports`.

**Comment by jamesbvaughan** [comment]
This is also fixed for me on 236.0-2 without `_backports`. Thanks!

**Comment by ghost** [comment]
Hi, for me the issue is not fixed.
systemd version is 236.0-2 and kernel 4.14.7.1-ARCH
already did bootctl update (coming from 235).

**Comment by amerlyq** [comment]
Problem persists, systemd 236.0-3,  4.14.13-1-ARCH

**Comment by mattia-b89** [comment]
Fixed for me.
Since `236.0-2` issue has definitively gone.

**Comment by amerlyq** [comment]
It seems we need to compare at least BIOS of affected users, because this message is still shown on boot. 
Mine BIOS is simplified too much with almost no options at all. By the way, there is no option related to TPM -- maybe current fix works only if such option exists?
```
$ sudo dmidecode -t bios -q
BIOS Information
        Vendor: American Megatrends Inc.
        Version: UX550VD.303
        Release Date: 09/12/2017
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 8192 kB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                BIOS shadowing is allowed
                Boot from CD is supported
                Selectable boot is supported
                BIOS ROM is socketed
                EDD is supported
                5.25"/1.2 MB floppy services are supported (int 13h)
                3.5"/720 kB floppy services are supported (int 13h)
                3.5"/2.88 MB floppy services are supported (int 13h)
                Print screen service is supported (int 5h)
                8042 keyboard services are supported (int 9h)
                Serial services are supported (int 14h)
                Printer services are supported (int 17h)
                ACPI is supported
                USB legacy is supported
                Smart battery is supported
                BIOS boot specification is supported
                Targeted content distribution is supported
                UEFI is supported
        BIOS Revision: 5.12
```

**Comment by haraldh** [comment]
```
# systemctl start tpm2-abrmd
# tpm2_pcrlist 
sha1 :
  0  : e7e2f4ee8ce7bcb8c84aabeadc6d061db7278607
  1  : 0b56d295b1af10425e330f38108e92ff3cab8227
  2  : ddafc483cdcb33046fd3b2cac1dc6f43470d930d
  3  : b2a83b0ebf2f8374299a5b2bdfc31ea955ad7236
  4  : 7fdbbb2fb7b38440ab585445f0be80b04955e206
  5  : 2e6eeadbe2f05f6ae35cfef44a2c2cd3f6b17e85
  6  : b2a83b0ebf2f8374299a5b2bdfc31ea955ad7236
  7  : e508a62497aed3281736af4e386be12aba78ae79
  8  : 22759428e15c3124804398f693da11466b4fe757
  9  : 0000000000000000000000000000000000000000
  10 : 0000000000000000000000000000000000000000
  11 : 0000000000000000000000000000000000000000
  12 : 0000000000000000000000000000000000000000
  13 : 0000000000000000000000000000000000000000
  14 : 0000000000000000000000000000000000000000
  15 : 0000000000000000000000000000000000000000
  16 : 0000000000000000000000000000000000000000
  17 : ffffffffffffffffffffffffffffffffffffffff
  18 : ffffffffffffffffffffffffffffffffffffffff
  19 : ffffffffffffffffffffffffffffffffffffffff
  20 : ffffffffffffffffffffffffffffffffffffffff
  21 : ffffffffffffffffffffffffffffffffffffffff
  22 : ffffffffffffffffffffffffffffffffffffffff
  23 : 0000000000000000000000000000000000000000
sha256 :
```

**Comment by haraldh** [comment]
# cat /sys/class/tpm/tpm0/ppi/version 
1.3

**Comment by haraldh** [comment]
Or with the old chip:
```
$ cat /sys/class/tpm/tpm0/caps 
Manufacturer: 0x49465800
TCG version: 1.2
Firmware version: 6.40
```

**Comment by haraldh** [comment]
Note the same sha1 😄 
```8  : 0ab83e4412b1e553b04e2c835afe1f7af7f4d4ae```
```PCR-08: 0A B8 3E 44 12 B1 E5 53 B0 4E 2C 83 5A FE 1F 7A F7 F4 D4 AE```

**Comment by pavlepredic** [comment]
I still have this issue with systemd 236. Anyone else has it?

**Comment by Nikki1993** [comment]
Present in Solus OS as well since latest update.

**Comment by donRaphaco** [comment]
bfdf8c3bb86f3dbc8e30e7a0a44d2df0c0c05171 didn't fix it for me either, but this little patch did the trick:
```
diff --git a/src/boot/efi/measure.c b/src/boot/efi/measure.c
index be4fea84a..5aaffe8fa 100644
--- a/src/boot/efi/measure.c
+++ b/src/boot/efi/measure.c
@@ -232,8 +232,11 @@ static EFI_STATUS tpm1_measure_to_pcr_and_event_log(const EFI_TCG *tcg, UINT32 p
  */
 static EFI_STATUS trigger_tcg2_final_events_table(const EFI_TCG2 *tcg, EFI_TCG2_EVENT_LOG_FORMAT log_fmt)
 {
+        EFI_PHYSICAL_ADDRESS loc;
+        EFI_PHYSICAL_ADDRESS last_loc;
+        BOOLEAN truncated;
         return uefi_call_wrapper(tcg->GetEventLog, 5, (EFI_TCG2 *) tcg,
-                                 log_fmt, 0, 0, 0);
+                                 log_fmt, &loc, &last_loc, &truncated);
 }
 
 static EFI_STATUS tpm2_measure_to_pcr_and_event_log(const EFI_TCG2 *tcg, UINT32 pcrindex, const EFI_PHYSICAL_ADDRESS buffer,
```
My machine is a xps 13 9360 (TPM set to 2.0).

**Comment by poettering** [comment]
@donRaphaco can you post that as proper PR? then we can merge it and it will get properly attributed to you and all

**Comment by amerlyq** [comment]
Before that can someone acknowledge if that patch is proper solution or
some workaround and does it work for someone else?
