### ISSUE TITLE
Clarify docs for restart behavior

### ISSUE THREAD

**Issue by markstos** [systemd/systemd#7126]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Ubuntu

A user reasonably asks [Is ExecStop run when issuing systemctl restart myUnit?](https://serverfault.com/questions/879078/is-execstop-run-when-issuing-systemctl-restart-myunit).

One assumes  that a "restart" may be equivalent to  "a stop and then a start", but in practice some systems do slightly different things.  So, some suggestions to improve the docs:

 * In `man systemctl`, under the "reload" section, it currently says: "Restart one or more units". If "restart" is implemented as "stop/start", it would be clearer to update the document to say "stop and then start one more units."
 * Also, in `man systemd.service`, where `ExecStop=` is documented, it would be helpful to document if this command as run during a restart command as well a "stop" command.

If the behavior can be confirmed, I can help with a doc-patch.

**Comment by OlafvdSpek** [comment]
Restart being equivalent to stop / start would mean sockets getting destroyed and recreated, potentially having a short time window where a connect would return not found. I don't think it's like that so they wouldn't be equivalent.

**Comment by keszybz** [comment]
Well, it does mean that. If the service open sockets on its own and it does not pass them to pid1 to hold, they will be closed when the service is stopped or restarted.

**Comment by OlafvdSpek** [comment]
I'm talking about the sockets managed by pid1.

**Comment by keszybz** [comment]
The text should probably mention the distinction between start/stop and restart wrt. to fds which are stored in pid1.

**Comment by kylebrandt** [comment]
I am still quite confused (I posted the original linked question).  

For my part, I would _assume_ that the behavior of `restart` would be the same as `stop` followed by `start`.  Assuming I'm normal in that regard, if they are _not_ the same, I think the documentation needs to highlight that they are different with additional information in *how* and *why* they are different. 

Also if they are different, I would expect a future request for a verb that is the equivalent of `start` and `stop`. 

But I guess the most fundamental question I have is, does `restart` == `stop` followed by `start`?

**Comment by fwaechter** [comment]
> does restart == stop followed by start?

No. See (for example): https://lists.freedesktop.org/archives/systemd-devel/2016-January/035585.html

**Comment by markstos** [comment]
Related, I just noticed this related comment from the [TODO file](https://github.com/systemd/systemd/blob/6e2d7c4f131edb19255842cdd4dc199cf8adb5ab/TODO)

> man: the documentation of Restart= currently is very misleading and suggests the tools from ExecStartPre= might get restarted.

I tried searching the source code to pin down the logic but wasn't able to pinpoint where the restart logic is implemented among the various mentions of "restart".

**Comment by pirate** [comment]
Nginx, postfix, and other services use the term `reload` to mean "graceful shutdown and reload of configuration without dropping active connections".  `restart` is almost universally is expected to mean `stop` then `start`.

I think systemd should pick one and stick to it throughout the docs: `reload` if services can do arbitrary reload procedures and keep connections open, or `restart` if it's always a systemctl `stop`+`start`.

**Comment by markstos** [comment]
@pirate `systemd` supports both `reload` and `restart` commands with the generally-expected behaviors. As described above, it sounds there is a bit of naunce with the `restart` command, since related sockets and file descriptors could be managed by either the service (and killed) or by systemd (and not killed). It would also good to be clear about whether the `ExecStop*` directives apply to restarts as well.

**Comment by poettering** [comment]
BTW, the man pages already say that restart mean "stop + start", since 6539dd7c42946d9ba5dc43028b8b5785eb2db3c5

**Comment by OlafvdSpek** [comment]
@poettering So does ExecStop= get executed on restart? And do sockets managed by systemd get removed and recreated?

**Comment by poettering** [comment]
Fix waiting in #7338.
