### ISSUE TITLE
systemd-journal-remote: Indefinite blocking in sd_event_run

### ISSUE THREAD

**Issue by martingh** [systemd/systemd#7130]
I was trying to use systemd-journal-remote/upload to collect journals from different hosts and was seeing timeouts for the journal-upload services, waiting for a response from systemd-journal-remote.  

For its http code systemd-journal-remote is using libmicrohttpd (MHD). MHD is configured to use epoll with an external event loop (sd_event). As the epoll_fd is configured to be edge triggered this means that epoll_wait must not be called on the epoll_fd again until a read or write for the registered fds returns EAGAIN. Otherwise this might result in indefinite blocking. This is exactly what can happen in journal-remote implementation, after returning from `dispatch_http_event()`.

Asking about this on MHDs mailing list [1] Evgeny Grin gave me the information that, when using an external event loop, the return value of `MHD_get_timeout()` should be considered to get a timeout value for the select.

I followed his suggestion in using a timerfd to be passed to systemd's event loop in addition to MHDs fd and update it to the timeout returned from `MHD_get_timeout()`. This solves the issues with blocking systemd-journal-remote I am seeing.

I'd like to see this in official software, could you have a look at the [patch](https://github.com/systemd/systemd/files/1396257/journal-remote-eventloop-timeout.txt) and suggest possible improvements for accepting it?

Thanks, 
Martin
[1] http://lists.gnu.org/archive/html/libmicrohttpd/2017-09/msg00000.html

**Comment by boucman** [comment]
could you submit it as a pull-request ? they are easier to follow and have less risk to be lost than issues with patch attached...

**Comment by martingh** [comment]
PR is here: https://github.com/systemd/systemd/pull/7152

**Comment by martingh** [comment]
Looks like when using SSL the changes are not sufficient and I still see that systemd-journal-upload processes are waiting for a reply from systemd-journal-remote. 

I cannot explain why, is there any difference at the level of event handling between SSL and non-SSL connections?

**Comment by Karlson2k** [comment]
Handling of large blocks with TLS connection in epoll mode was partially broken in 0.9.55.
It was fixed in git master and will be published soon as new release.
As workaround, I could suggest to use 'poll' for 0.9.55.

**Comment by martingh** [comment]
@Karlson2k Can you maybe have a look:

Yesterday I built MHD to test if this would fix it - still no success with TLS connections. What I see is that when a new connection is established `MHD_get_timeout` will set the output parameter to a timeout of 0, but later on it would only return `MHD_NO`.

Thanks for helping on this one!

**Comment by martingh** [comment]
Added PR #7219 to revert the erroneous code of the previous PR.

**Comment by Karlson2k** [comment]
@martingh Did you try a latest master branch from official MHD git?
As I said, we fixed TLS in epoll mode in git. Not yet released.

**Comment by martingh** [comment]
@Karlson2k Yes I built it from git master. Can I maybe collect any (log) output for you?

**Comment by Karlson2k** [comment]
`strace` output could be helpful.

**Comment by martingh** [comment]
@Karlson2k Please find `strace` [here](https://pastebin.com/SMHcrBzJ). 
/lib64/libmicrohttpd.so.12 was replaced with the build from git master. 
I inserted two messages after `MHD_get_timeout`. In this case it always returned `MHD_NO`.

**Comment by Karlson2k** [comment]
@martingh Thanks for report.
Try with updated git version, please..

**Comment by martingh** [comment]
Now it is working properly. Thank you, closing the issue.
