### ISSUE TITLE
systemd-shutdown: code for remounting read-only seems buggy in the face of overmounts

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#7131]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v235 source code

### Bug report

The code for systemd-shutdown tries to remount read-only each mount point in /proc/self/mountinfo.

But it does not account for mounts which are hidden.  And remounting read-only involves passing the existing mount options for the filesystem.  So we could be passing the options for the wrong filesystem.

I think there is a general solution to detect hidden mounts: https://unix.stackexchange.com/questions/398983/check-for-overmount/398985#398985

**Comment by sourcejedi** [comment]
If the code knew not to try remounting hidden mounts, it would make sense to use statvfs() to read the old mount flags, and stop blithely resetting all the other mount flags when remounting readonly.

EDIT: or scratch that and just parse the mount flags, which are broken out as a separate field in the `mountinfo` file that we read.

**Comment by medhefgo** [comment]
Do you have a concrete bug/failure you're hitting or a test case? Also, there's been changes in late shutdown code recently, including parsing mount flags. So I think this can be closed now, right?
