### ISSUE TITLE
systemd-nspawn: missing set_tls syscall in whitelist

### ISSUE THREAD

**Issue by 27o** [systemd/systemd#7135]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Archlinux ARM

### Expected behaviour

Running the container

### Unexpected behaviour

musl-based container:
> Container alpine terminated by signal ILL.

glibc-based container:
> cannot set up thread-local storage: unknown error

### Steps to reproduce the problem

Run any container without options.

### Fix

Runing the containers with `--system-call-filter=set_tls` works fine. So adding set_tls to the allowed syscalls should fix this.

**Comment by zeitgeist87** [comment]
I have the same problem using Arch Linux on a Raspberry Pi 2. The command line parameter `--system-call-filter=set_tls` fixes it. Thanks!

**Comment by AdamSLevy** [comment]
Same problem on up to date Arch Linux Arm on the Marvell Clearfog. Above mentioned CLI option fix works.

**Comment by joeyh** [comment]
Same problem on Debian armel on a Cubietruck with systemd 235. This is a reversion from systemd 234 I think, or maybe upgrading linux to 4.13.0 caused it.

**Comment by poettering** [comment]
Fix waiting in #7297.
