### ISSUE TITLE
[RFE] Differentiate between first restart delay and subsequent delays

### ISSUE THREAD

**Issue by OlafvdSpek** [systemd/systemd#7138]
If a service crashes (for the first time), I'd like it to be restarted as soon as possible, without any delays.
If it crashes / stops again soon after, a delay is probably in order.

However, I don't think there's a way to do this currently. RestartSec controls both delays.

**Comment by poettering** [comment]
I'd say this is pretty much the same as #6129, i.e. iterative control over the restart delay. Let's close this one as duplciate hence. hope that makes sense.

Duplicate of #6129
