### ISSUE TITLE
When use systemctl restart service , cma memory didn't free.

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#7140]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> version 234

### Used distribution

> Yocto build with poky v2.4 ( contain systemd version v234 ) for embedded system

###  In version systemd 232 systemctl stop weston can free CMA:

>  cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          632888 kB
> systemctl restart weston
> cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          632888 kB
>  systemctl restart weston
>  cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          632888 kB
>  systemctl stop weston
>  cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          645096 kB

### In case of bug report: Unexpected behaviour :
 It can only free Cma if I restart dbus.socket and dbus service.

>  systemctl restart weston
> cat /proc/meminfo | grep Cma
>CmaTotal:         671744 kB
>CmaFree:          620536 kB
> systemctl restart weston
> cat /proc/meminfo | grep Cma
>CmaTotal:         671744 kB
>CmaFree:          608184 kB
>systemctl restart weston
> cat /proc/meminfo | grep Cma
>CmaTotal:         671744 kB
>CmaFree:          595832 kB
> systemctl restart dbus.socket
> cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          595832 kB
> systemctl restart dbus
> cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          644944 kB
> systemctl restart weston
> cat /proc/meminfo | grep Cma
> CmaTotal:         671744 kB
> CmaFree:          632888 kB

My weston service as below:
[Unit]
Description=Weston Wayland compositor
After=dbus.service rc.pvr.service

[Service]
ExecStart=/usr/bin/weston-launch -u root -- --idle-time=0 $OPTARGS
ExecStop=/usr/bin/killall -s KILL weston
Type=simple

[Install]
WantedBy=multi-user.target

### In case of bug report: Steps to reproduce the problem

> systemctl restart weston
> cat /proc/meminfo | grep Cma
> systemctl restart weston
> cat /proc/meminfo | grep Cma

Thank you for help me.

**Comment by poettering** [comment]
To be frank, I have no idea what "Cma" is. What makes you think this is an issue with systemd?

**Comment by michaelolbrich** [comment]
@poettering CMA is "Contiguous Memory Allocator" and this is not a systemd problem.

Is rc.pvr.service stopped with D-Bus? I'd guess that this service still uses the CMA memory.

**Comment by poettering** [comment]
Thanks for clearing this up. Let's close this here then!
