### ISSUE TITLE
networkd's "Renamed to eth0" messages are confusing, suggest networkd did something here, but it actually just reports changes done elsewhere

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#7143]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Archlinux

### In case of bug report: Unexpected behaviour you saw

It seems systemd-networkd renames interfaces in exactly the same way as the kernel just did, this is from my journal:

```
kernel: cdc_ether 1-1.6.3:1.0 idrac: renamed from eth0
kernel: tg3 0000:02:00.1 eno2: renamed from eth1
kernel: tg3 0000:02:00.0 eno1: renamed from eth0
systemd-networkd[618]: idrac: Renamed to eth0
systemd-networkd[618]: eth0: Renamed to idrac
systemd-networkd[618]: eno1: Renamed to eth0
systemd-networkd[618]: eno2: Renamed to eth1
systemd-networkd[618]: eth1: Renamed to eno2
systemd-networkd[618]: eth0: Renamed to eno1
```

I end up with `idrac / eno1 / eno2` which is fine

Is this a bug or known behavior?

**Comment by poettering** [comment]
networkd just reports the kernel change, that's all, it doesn't trigger the rename, it's just the messenger here. But yeah, we could probably reword this a bit to make this less confusing.

**Comment by poettering** [comment]
Fix waiting in #7299.

**Comment by yuwata** [comment]
#7299 changes log message, but the spurious behavior is not fixed.
```
Dec 21 14:26:40 kernel: e1000e 0000:00:19.0 enp0s25: renamed from eth0
Dec 21 14:26:40 kernel: iwlwifi 0000:02:00.0 wlp2s0: renamed from wlan0
Dec 21 14:26:45 systemd-networkd[545]: enp0s25: Interface name change detected, enp0s25 has been renamed to eth0.
Dec 21 14:26:45 systemd-networkd[545]: eth0: Interface name change detected, eth0 has been renamed to enp0s25.
Dec 21 14:26:45 systemd-networkd[545]: wlp2s0: Interface name change detected, wlp2s0 has been renamed to wlan0.
Dec 21 14:26:45 systemd-networkd[545]: wlan0: Interface name change detected, wlan0 has been renamed to wlp2s0.
```

**Comment by floppym** [comment]
Maybe you could capture the events udev is seeing when this happens? (udevadm monitor)

**Comment by yuwata** [comment]
@floppym Is it possible during boot process?

**Comment by poettering** [comment]
> #7299 changes log message, but the spurious behavior is not fixed.

well but what is there to fix in systemd? networkd is just the messenger here i figure, it appears you have something else installed that renames the ifaces, no? maybe the debian udev rules that store the name to disk?

**Comment by yuwata** [comment]
Hmm, at least for my environment (Fedora 27), no special udev rules are installed.

**Comment by yuwata** [comment]
Note that changing interface name by `ip` command is logged as expected. This only happens when system boots then udev changes the name.

**Comment by poettering** [comment]
maybe you have some name changes due to the old networking scripts?

There must be something that triggers these renames...

**Comment by poettering** [comment]
So this issue was about the log msg which got fixed. The spurious renames are something else i guess. Might be worth tracking down but this sounds like material for a seperate issue... Lets close this one hence.
