### ISSUE TITLE
[regression] systemctl daemon-reexec breaks logind.

### ISSUE THREAD

**Issue by ht990332** [systemd/systemd#7146]
### Submission type

 - Bug report

### systemd version the issue has been seen with
235

### Used distribution
Arch Linux

Starting with systemd 235, systemctl daemon-reexec breaks systemd-logind.

to reproduce:
1. log onto gnome or tty2 or something.
2. run: systemctl daemon-rexeec as root.
3.log off. and log on again.
4. run: loginctl list-sessions and notice the old stale sessions.
in addition /run/user/user_id/ was not unmounted for the stale sessions.

This was not an issue under 234.

**Comment by ht990332** [comment]
I just downgraded to 234.11 and can confirm this was not in issue in that build.

**Comment by poettering** [comment]
if you do loginctl status on such service, is the scope unit of the session shown?

If you do "systemctl status" on that scope unit, what does it say about it?

**Comment by ht990332** [comment]
loginctl session-status c7
c7 - hussam (1000)
           Since: Thu 2017-10-26 22:24:35 EEST; 5min ago
          Leader: 4362
            Seat: seat0; vc1
         Display: :0
         Service: gdm-password; type x11; class user
           State: closing
            Unit: session-c7.scope

systemctl status session-c7.scope
Unit session-c7.scope could not be found.

**Comment by ht990332** [comment]
I'll git bisect.

**Comment by ht990332** [comment]
It looks like this is what broke it. https://github.com/systemd/systemd/commit/5463fa0a88f95d2002858592578f9bf4e0d2660a
Someone please double check if possible.

**Comment by ht990332** [comment]
I can confirm that reverting that commit fixes the problem for me.

**Comment by poettering** [comment]
thanks a ton for bisecting this. @msekletar?

**Comment by msekletar** [comment]
Problem is that ```manager_connect_bus()``` is called *before* ```manager_coldplug()```. As a last thing in ```service_coldplug()``` we set service state to ```s->deserialized_state```, but before we do that all services are inactive and thus ```try_connect``` evaluates to ```false```. This is the key point I didn't realize.

Also, I didn't catch this in my testing because I was specifically testing scenario from #6303 and in that case, we actually want  ```try_connect``` to be false.

I think we could change the code as follows, 

```C
        try_bus_connect =
                (u && SERVICE(u)->deserialized_state == SERVICE_RUNNING) &&
                (reexecuting ||
                 (MANAGER_IS_USER(m) && getenv("DBUS_SESSION_BUS_ADDRESS")));

```

Or we can just revert https://github.com/systemd/systemd/commit/5463fa0a88f95d2002858592578f9bf4e0d2660a and think about an alternative way to fix #6303.

**Comment by msekletar** [comment]
I pushed proposal from the previous comment in #7205.

**Comment by ht990332** [comment]
Thank you for the fix. Please backport to systemd-stable/235 branch as well if you have time.
And thanks again.
