### ISSUE TITLE
Screen orientation for HP dv7 Pavilion Notebook PC

### ISSUE THREAD

**Issue by skidadpa** [systemd/systemd#7151]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

Ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see

Detected orientation should match laptop orientation

### In case of bug report: Unexpected behaviour you saw

Orientation was incorrect (left/right swapped, normal/upside-down off by 90 degrees)

### In case of bug report: Steps to reproduce the problem

Tilt the laptop :-)

Through experimentation, I was able to find correct settings for ACCEL_MOUNT_MATRIX, which I put into 61-sensor-local.hwdb on my system. You may want to add them to the defaults:

`sensor:modalias:platform:lis3lv02d:dmi:*svn*Hewlett-Packard*:*pn*HPPaviliondv7NotebookPC*`
`ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 0, -1; 0, -1, 0`

**Comment by poettering** [comment]
Please provide a proper patch in a github PR. Thanks.

**Comment by hadess** [comment]
@dsd Did you ever collect those quirks together for HP laptops?

**Comment by skidadpa** [comment]
Sorry -- though I'm quite familiar with git itself, I haven't contributed to GitHub before. I expected that I would need to test the change first, and I don't know much about systemd internals. Presumably the patch would have to be applied to 60-sensor.hwdb, although that doesn't exist on my system so it's presumably compiled in. I was hoping there was someone already collecting this type of information who might appreciate the heads up. Looking in that file again, I see that I should have also at least included the output of udevadm info --export-db in this report. I'll rectify that when I'm able and see what I can do to confirm a proper fix. Should I create a PR with just the details already mentioned?

Meanwhile, I wanted to get the code out there somewhere, since it may stave off others asking the same question. I know my laptop was a popular one. This came about when I upgraded to Ubuntu 17.10 and noticed a new rotation lock button. I didn't even know about the accelerometer tilt-sense feature before that.

**Comment by phomes** [comment]
does the Z value report the correct values? For the two HP laptops I could test on the matrix was:
ACCEL_MOUNT_MATRIX=1, 0, 0; 0, 0, -1; 0, 1, 0

I read somewhere that the accelerometer used in those two (lis3lv02d) is in many HP laptops. It started to be picked up by iio-sensor-proxy about a year ago. I guess only with 17.10 does ubuntu make use iio-sensor-proxy. Anyway, my point is that I expect many HP laptops should be using that matrix.

**Comment by skidadpa** [comment]
Yes, with -1, 0, 0; 0, 0, -1; 0, -1, 0 it responds correctly: monitor-sensor reports normal/bottom-up when the keyboard is facing up/down, right-up/left-up when the right/left edge of the computer is facing up, and does not otherwise change when the top/bottom of the keyboard is up. Since the laptop screen does not open flat (or further than that), this is the only behavior that makes sense.

I'm not sure what type of orientation switching Unity supported by default on regular laptops, but with 17.10, Ubuntu also switched back to Gnome by default.

**Comment by skidadpa** [comment]
Here is the output of udevadm info --export-db
[udevadm.info.txt](https://github.com/systemd/systemd/files/1412481/udevadm.info.txt)

**Comment by skidadpa** [comment]
And here's dmidecode output in case you want to tweak the DMI match rule:
[dmidecode.txt](https://github.com/systemd/systemd/files/1412535/dmidecode.txt)

**Comment by hadess** [comment]
> **I read somewhere that the accelerometer used in those two (lis3lv02d) is in many HP laptops. It started to be picked up by iio-sensor-proxy about a year ago. I guess only with 17.10 does ubuntu make use iio-sensor-proxy. Anyway, my point is that I expect many HP laptops should be using that matrix.**

Yes, we have the problem that all HP laptops which use this interface/driver need quirks because the driver expects orientations that don't match what Windows 8 (and iio-sensor-proxy) use, and we run into the possibility that we're adding quirks in systemd for devices which don't have quirks in the driver, and might break at a later point...

We already discussed that with Daniel, and hopefully he's done some work in that area.

**Comment by retorquere** [comment]
I think I've been bitten by this bug and my screen is now upside down  :( any clues on how to rectify this?

**Comment by poettering** [comment]
Let's close this one, i figure the general problems with the mount matrix for HP laptops can be tracked in a single issue. Let's make that #5160
