### ISSUE TITLE
Unable to suspend with nvidia proprietary drivers

### ISSUE THREAD

**Issue by Yanpas** [systemd/systemd#7155]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235

### Used distribution

Arch

### In case of bug report: Expected behaviour you didn't see

systemctl suspend makes system go asleep

### In case of bug report: Unexpected behaviour you saw

After doing some gpu actions (playing game or watching gpu accelerated video) system doesn't go to sleep. Systemctl suspend outputs the following: `Failed to suspend system via logind: There's already a shutdown or sleep operation in progress`. If I run `systemctl shutdown -f` the system goes suspend first, than I wake it up and it shuts down.

### In case of bug report: Steps to reproduce the problem
There are no exact STR
1. Boot system
2. Suspend it and wake up
3. play some fullscreen video
4. Suspend it again - nothing happens

### sysinfo:
Linux 4.13.7-1-ARCH, xfce DE, lightdm display manager, nvidia 387.12-2 driver (I've tried 384 too) and 1060 card.
dmesg doesn't output any errors.

I've used ubuntu previously with modern driver and old systemd - there were no such problem. As far as I can remember 234 was ok too.

**Comment by poettering** [comment]
Can you test this without proprietary code in the kernel? There's a very good chance that's the cause of the issue, and if so there's very little we can do given the closed source nature of your driver.

**Comment by Yanpas** [comment]
I've tested with nouveau (open source one driver), there is no such bug. I don't know the responsibilities of systemd in this  case. I'll contact Nvidia

**Comment by poettering** [comment]
In that case please contact nvidia for help. We cant really support or fix closed source stuff. Sorry.

**Comment by Yanpas** [comment]
It seems that this issue was closely related to lightdm and light-locker. light-locker switches VT to lightdm's one and suspend action is going on in parallel. Seems nvidia cannot handle this correctly.
