### ISSUE TITLE
Please warn if `net/ipv4/conf/default/promote_secondaries` is not set (with patch)

### ISSUE THREAD

**Issue by mvo5** [systemd/systemd#7163]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

git master (de13433)

### Used distribution 
Ubuntu 17.10

###  Expected behaviour you didn't see

The DHCP code in systemd-networkd relies on the `net.ipv4.conf.{default,all,<if>}.promote_secondaries` sysctl to be set (the kernels default is that it is unset). If this sysctl is not set DHCP will work most of the time, however when the IP address changes between leases then the system will loose its IP. This is fine and systemd ships the needed defaults in 50-default.conf. However some distributions decided to not ship these defaults (Debian is an example and via downstream Ubuntu). 

net.ipv4.conf.default.promote_secondaries

Please consider adding a warning in case this option is not set. I attached a trivial patch. Please let me know if you prefer something more sophisticated - I guess the warning could move into networkd-address.c:address_configure() when update is set to TRUE. But I'm not really familiar with the networkd code so if a more sophisticated version is desired hints about the best place are welcome.

Thanks for your consideration!
 Michael

**Comment by mvo5** [comment]
[0001-networkd-warn-if-promote_secondaries-is-unset.patch.txt](https://github.com/systemd/systemd/files/1406616/0001-networkd-warn-if-promote_secondaries-is-unset.patch.txt)

**Comment by poettering** [comment]
Please submit patches via PR

**Comment by mvo5** [comment]
Thanks for your feedback. I create a PR now: https://github.com/systemd/systemd/pull/7167 and linked back to this issue here.

**Comment by mvo5** [comment]
This is merged with https://github.com/systemd/systemd/pull/7167 now
