### ISSUE TITLE
systemd-detect-virt returns "vm-other" in PV Linux guest on XenServer + AMD

### ISSUE THREAD

**Issue by razvan-cojocaru** [systemd/systemd#7165]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235

### Used distribution

Ubuntu 16

### In case of bug report: Expected behaviour you didn't see

systemd-detect-virt should have returned 'xen'

### In case of bug report: Unexpected behaviour you saw

systemd-detect-virt returned 'vm-other'

### In case of bug report: Steps to reproduce the problem

Simply run systemd-detect-virt.

The problem here is that the CPUID test in `detect_vm_cpuid()` returns 'other' (`sig.text` is empty - all zeroes), and even though the guest is running on top of Xen, the detection attempt stops here, even though `detect_vm_xen()` following it would have been able to tell what hypervisor we're dealing with).

**Comment by poettering** [comment]
if xen is not detected properly detect-virt.c probably needs some tweaks for your virtualizer. Since we don't run Xen ourselves we really require patch submissions to make this work, and cannot really help you beyond sympathizing. :-(

**Comment by andyhhp** [comment]
Xen PV guests (being ring-deprivileged) can't be detected using that method, because CPUID isn't a instruction which typically traps.

On Intel IvyBridge and later, we have CPUID faulting which does allow Xen to fake things up properly (although dom0 is still excluded until I can fix other bugs).

On AMD, Xen can control the Hypervisor bit in CPUID, because MSR_K8_EXT_FEATURE_MASK (0xc0011005) is actually an override, rather than a mask.

The way to find Xen from a PV guest using CPUID is to use `ud2a; .ascii "xen"; cpuid` which Xen's #UD handler will detect specially.  This is the method that Linux PVOPs uses, but you have to be prepared to cope with a SIGILL if you run that code anywhere other than a Xen PV guest.

At a higher level though, why is systemd reinventing this wheel?  Linux already knows which hypervisor it is running under and exposes it via `/sys/`

**Comment by andyhhp** [comment]
Actually, there is a further problem in the probing algorithm.  For a Xen HVM guest with Viridian extensions enabled, it will detect HyperV rather than Xen.  Xen's CPUID leaves deliberately slide along to `0x40000100` so we can advertise both sets of enlightenments.

**Comment by razvan-cojocaru** [comment]
This is the smallest patch that fixes the issue for my AMD PV Xen guest, however it's a workaround, and as Andrew has pointed out above, a simpler and more reliable solution would probably be to just redesign the whole `detect_vm()` function to rely on `/sys/hypervisor/type` if possible (which correctly contains `xen` on said guest).

    diff --git a/src/basic/virt.c b/src/basic/virt.c
    index d8eeb54..fcb088d 100644
    --- a/src/basic/virt.c
    +++ b/src/basic/virt.c
    @@ -102,13 +102,15 @@ static int detect_vm_cpuid(void) {
                             : "0" (eax)
                     );
     
    -                log_debug("Virtualization found, CPUID=%s", sig.text);
    +                if (sig.text[0]) {
    +                        log_debug("Virtualization found, CPUID=%s", sig.text);
     
    -                for (j = 0; j < ELEMENTSOF(cpuid_vendor_table); j ++)
    -                        if (streq(sig.text, cpuid_vendor_table[j].cpuid))
    -                                return cpuid_vendor_table[j].id;
    +                        for (j = 0; j < ELEMENTSOF(cpuid_vendor_table); j ++)
    +                                if (streq(sig.text, cpuid_vendor_table[j].cpuid))
    +                                        return cpuid_vendor_table[j].id;
     
    -                return VIRTUALIZATION_VM_OTHER;
    +                        return VIRTUALIZATION_VM_OTHER;
    +                }
             }
     #endif
             log_debug("No virtualization found in CPUID");

**Comment by poettering** [comment]
> At a higher level though, why is systemd reinventing this wheel? Linux already knows which hypervisor it is running under and exposes it via /sys/

We do check that, but later on:

https://github.com/systemd/systemd/blob/master/src/basic/virt.c#L257

It might suffice to switch this around and first check this before looking for cpuid. Happy to review a PR that makes such a change.

**Comment by razvan-cojocaru** [comment]
Not in the form it's written in:

    r = detect_vm_hypervisor();
    if (r < 0)
            return r;
    if (r != VIRTUALIZATION_NONE)
            goto finish;

since `detect_vm_hypervisor()`  returns `VIRTUALIZATION_XEN` or `VIRTUALIZATION_VM_OTHER` if `/sys/hypervisor/type` is present - so for aything other than `xen` it won't properly identify it. If `/sys/hypervisor/type` is not tied to Xen, we just move the Xen problem to another hypervisor.

**Comment by poettering** [comment]
hmm, so then, here's a different idea: maybe when one detector function returns VM_OTHER, we should proceed with the next one, but remember that we saw VM_OTHER. If another detector then finds something more precise, we should propagate that. But if nothing else finds something precise, we return VM_OTHER after all..

**Comment by razvan-cojocaru** [comment]
That sounds fair. "Other" should mean "we'll settle for this if we can't refine the identification in later code".

**Comment by poettering** [comment]
Closing, since #7171 got merged a while back
