### ISSUE TITLE
systemd complains about the system not supporting BPF/cgroup based firewalling

### ISSUE THREAD

**Issue by Lightn1ng** [systemd/systemd#7188]
- Bug report

systemd 235

Gentoo Linux amd64

Expected no log spam about the system not supporting BPF/cgroup firewalling

Saw the following line spammed in journalctl:

> File /lib/systemd/system/systemd-journald.service:33 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.

Reproduced by simply booting up the system and checking journalctl

**Comment by Lightn1ng** [comment]
Solved by setting `CONFIG_BPF_SYSCALL=y` in the Linux kernel configuration.

**Comment by poettering** [comment]
maybe we should print that message only the first time, and not for each unit we load that has that option set.

**Comment by poettering** [comment]
Fix waiing in #7188

**Comment by dalu** [comment]
```
zgrep CONFIG_BPF_SYSCALL /proc/config.gz 
CONFIG_BPF_SYSCALL=y
```
however
```
Nov 26 09:07:36 hostname systemd[1]: File /lib/systemd/system/systemd-journald.service:33 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Nov 26 09:07:36 hostname systemd[1]: Proceeding WITHOUT firewalling in effect!
Nov 26 09:07:36 hostname systemd[1]: File /lib/systemd/system/systemd-udevd.service:32 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Nov 26 09:07:36 hostname systemd[1]: Proceeding WITHOUT firewalling in effect!
Nov 26 09:07:36 hostname systemd[1]: File /lib/systemd/system/systemd-logind.service:34 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Nov 26 09:07:36 hostname systemd[1]: Proceeding WITHOUT firewalling in effect!
Nov 26 09:07:36 hostname systemd[1]: File /lib/systemd/system/systemd-machined.service:27 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Nov 26 09:07:36 hostname systemd[1]: Proceeding WITHOUT firewalling in effect!
Nov 26 09:07:36 hostname systemd[1]: searchd.service: Supervising process 2716 which is not our child. We'll most likely not notice when it exits.
Nov 26 09:07:36 hostname systemd[1]: File /lib/systemd/system/systemd-coredump@.service:37 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Nov 26 09:07:36 hostname systemd[1]: Proceeding WITHOUT firewalling in effect!
```

**Comment by poettering** [comment]
@dalu also, the relvant option is called  CONFIG_CGROUP_BPF, not CONFIG_BPF_SYSCALL (though that one is required too)

**Comment by ikeydoherty** [comment]
Just to verify, because I'm seeing this in a kernel with both of those options set, would legacy cgroups heirarchy also force the bpf firewall test to fail? Wanna confirm that before I commit to deprecating it in Solus. (Was turned on due to Docker)

**Comment by poettering** [comment]
cgroup/bpf only works on hybrid and unified mode. It won't work on legacy mode.

**Comment by albel727** [comment]
>maybe we should print that message only the first time, and not for each unit we load that has that option set.

What if one wants to know, which units need the feature, in order to decide, whether it's worth to enable it?
