### ISSUE TITLE
RFE: reload-daemon == daemon-reload

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#7191]
### Submission type

 - Request for enhancement (RFE)
### systemd version the issue has been seen with

Please make `systemctl reload-daemon` an alias of `systemctl  daemon-reload`.

The original command does not follow the verb-substantive scheme unlike the majority of other commands like reset-failed, list-timers, set-property, show-environmnent, switch-root.

**Comment by poettering** [comment]
I am not sure I like redundant naming like this.

**Comment by fsateler** [comment]
This would make tab completion for `systemctl reload foo` annoying.

**Comment by barcharcraz** [comment]
I mistakenly type reload-daemon almost every time I want to call daemon-reload. That said it's not like daemon-reload can go away.

**Comment by Shuangistan** [comment]
daemon-reexec shall be involved in this discussion also.

**Comment by keszybz** [comment]
Sorry, but this will just create more confusion. I agree the naming is maybe not perfect, it has grown organically over the years, but adding aliases is just going to make this all harder to remember. This comes up every once in a while, but not that often, and as people get used to systemd they seem to internalize the naming. This kind of decision is always a judgement call, but in this case minimalism and non-redundancy seems more important.
