### ISSUE TITLE
Failed to get D-Bus connection: Unknown error -1

### ISSUE THREAD

**Issue by KeithTt** [systemd/systemd#7192]
I just upgraded debian wheey to jessy, but there is no `systemctl` command, so I installed the `systemd` package manully.

Then the `systemctl` cmd appear  but it reports `Failed to get D-Bus connection: Unknown error -1` when use it.

**Comment by michich** [comment]
Have you rebooted? Are you actually booting with systemd as PID 1?

**Comment by michich** [comment]
Please read https://wiki.debian.org/systemd on how to configure a Debian system to boot with systemd (for once or as the default).

**Comment by KeithTt** [comment]
And I can not connect to the machine with ssh...even if I cold restart the system.

Maybe the sshd did not start?
