### ISSUE TITLE
Cannot bind-mount file with machinectl

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#7195]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233, 235, master

### Used distribution

> CentOS 7, Arch Linux

It would be nice if `machinectl bind` (or potentially a new command `bind-file`?) would support binding files in addition to directories, similar to `systemd-nspawn`'s `--bind` option, which can do either a file or directory.

**Comment by poettering** [comment]
Fix waiting in #7349
