### ISSUE TITLE
buttons on graphic tablet pad don't work

### ISSUE THREAD

**Issue by yuperi** [systemd/systemd#7197]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see

> sudo libinput debug-events show no button press
Please look at https://bugs.freedesktop.org/show_bug.cgi?id=103395#c10

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> connect graphic tablet, then type  sudo libinput debug-events

**Comment by poettering** [comment]
@yuperi sorry, but we can't fix this issue for you. Please provide a hwdb patch instead, and we'll merge it, but we don't have the time nor the hardware to fix this issue for you.

@whot can you help @yuperi figuring out what he needs to do?

**Comment by whot** [comment]
@poettering this was suggested by me to be filed here. Not 100% sure on the best fix yet but I think long-term we need a hwdb for the `ID_INPUT` assignments too for the devices that fall through the cracks. I'll get onto that asap.
