### ISSUE TITLE
systemd-networkd: Default gateway not added when using RoutingPolicyRule

### ISSUE THREAD

**Issue by half-duplex** [systemd/systemd#7200]
### Submission type
Bug report

### systemd version the issue has been seen with
235 (235-2)

### Used distribution
Debian Buster (10)

### Expected behaviour you didn't see
Default gateway present
```
# ip r
default via 10.100.0.1 dev enp0s3
10.100.0.0/24 dev enp0s3 proto kernel scope link src 10.100.0.2
10.101.0.0/24 dev enp0s3 proto kernel scope link src 10.101.0.2
```

### Unexpected behaviour you saw
Default gateway absent
```
# ip r
10.100.0.0/24 dev enp0s3 proto kernel scope link src 10.100.0.2
10.101.0.0/24 dev enp0s3 proto kernel scope link src 10.101.0.2
```

### Steps to reproduce the problem
```
# echo "1   mytable" >>/etc/iproute2/rt_tables
# cat >/etc/systemd/network/test.network <<EOF
[Match]
Name=enp0s3

[Network]
DNS=8.8.8.8
IPv6AcceptRA=no
Address=10.100.0.2/24
Gateway=10.100.0.1
Address=10.101.0.2/24

[Route]
Gateway=10.101.0.1
Table=1

[RoutingPolicyRule]
From=10.101.0.2
Table=1
Priority=500
EOF
```
Commenting the RoutingPolicyRule section results in the default gateway being correctly added.

It's not unlikely I'm misunderstanding something, but I've read the docs I could find and tried every permutation I can think of for how to specify the default route (even adding to Table=254) and nothing is working.

Probably a @ssahani thing.

**Comment by flo-wer** [comment]
You should be able to view the routes with
```
ip route show table 1
ip route show table all
```

**Comment by half-duplex** [comment]
Yes, there is still no default route.
Actually, checking table 1 widens the problem scope: There is no default route on table 1 either. Just like the main table one, it is added as expected if I comment the `RoutingPolicyRule` section.

**Comment by ssahani** [comment]
works for me . Should not affect the gateway as rules are added later than the routes. What are the debug logs ?

**Comment by half-duplex** [comment]
https://gist.github.com/indecisivemal/cab828701c3f30eff275c7ab6f0b4aeb
No "Setting routes" / "Routes set" logged when policy routing used.

**Comment by ssahani** [comment]
@indecisivemal Please try with https://github.com/systemd/systemd/pull/7235

**Comment by half-duplex** [comment]
Appears to work with that patch. Thank you!
