### ISSUE TITLE
`machinectl forget` command?

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#7208]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

I managed to get machined into a bad state by using `machinectl stop` and `btrfs subvolume delete` somehow. I'm not sure exactly how, but I wasn't able to restart my container because machined kept the old container around, so anytime I would start the new one `nspawn` would complain:

```
Oct 28 23:19:11 drcid systemd[1]: Starting Container archon...
Oct 28 23:19:11 drcid systemd-nspawn[8859]: Failed to register machine: Machine 'archon' already exists
Oct 28 23:19:11 drcid systemd-nspawn[8859]: Parent died too early
Oct 28 23:19:11 drcid systemd[1]: archon.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 23:19:11 drcid systemd[1]: archon.service: Failed with result 'exit-code'.
Oct 28 23:19:11 drcid systemd[1]: Failed to start Container archon.
```

I tried combinations of `machinectl {stop,kill,terminate}` to get it to forget about the dead container, but it wouldn't let me restart it. I eventually had to restart `machined` entirely.

It'd be nice to have a `machinectl forget` command which would delete the state in machined for a container, possibly with some kind of sanity check to ensure that the container isn't running or present on disk before deleting the record.

I was using [this systemd service](https://gist.github.com/zfjagann/5176e25a60c4fd9e6fbfe36dec1dde0d) to spawn the container.

**Comment by yuwata** [comment]
What happen if you restart `systemd-machined`, that is, `systemctl restart systemd-machined.service`? I am not sure that your case is the same as mine. But I sometimes have a similar situation, and as a workaround, restarting `systemd-machined` works fine for me.

**Comment by zealws** [comment]
@yuwata That's eventually what I did to fix the issue. This issue is specifically about providing a way to fix this without having to restart machined.
