### ISSUE TITLE
RFE: Allow configuration of timesyncd's max acceptable root distance

### ISSUE THREAD

**Issue by eaglemc** [systemd/systemd#7211]
### Submission type
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 236

### Used distribution

> angstrom, but not distro specific

### Description

In timesyncd-manager.c the maximum allowed root distance is hard-coded as 5 seconds:
~~~
/* Maximum acceptable root distance in seconds. */
#define NTP_MAX_ROOT_DISTANCE           5.0
~~~

It would be good to allow this to be configurable.

Additionally, it was rather difficult to diagnose why time was not synchronizing with my ntp server, so I also would like to suggest changing the line
~~~
log_debug("Server has too large root distance. Disconnecting.");
~~~
to be `log_info` or even `log_warning` and include both the actual and maximum-allowed root distances in the message.

(In my case I have devices on an isolated network and whatever the sole ntp server says the time is has to be the right answer regardless of what the root distances is.  The devices don't have a battery-backed RTC so their time is not anything reasonable if they haven't synced with the ntp server.)

**Comment by yuwata** [comment]
@eaglemc I've created PR #7215. If possible, please test it.

**Comment by eaglemc** [comment]
Thanks for the speedy patch!
I confirmed that `MaxRootDistance` works great.
I'm not sure how thoroughly I can test the other settings (I can't control what the server is doing), but I'll try to do at least some basic checking tomorrow.

**Comment by yuwata** [comment]
Thank you for checking the PR.

**Comment by eaglemc** [comment]
I did check and confirm that values set in the configuration file are being read properly and validated by the new code.

There is a slight thing where if you set the minimum poll interval to greater than 2048 (which seems crazy long, but whatever) and the maximum poll interval to something less than that, the validation code will set the maximum to the default of 2048, which is not less than the minimum.  However looking at how the maximum is used in the code I don't think it actually matters--the maximum is not a "hard" maximum and if the initial value (==minimum value) is greater than the maximum, the poll interval just won't be increased.

**Comment by yuwata** [comment]
Thanks. Updated.

**Comment by BrunoVernay** [comment]
It is still a log_debug message and indeed, it would help (me) to have it log_info or log_warning.
Also there is no way to "force" a NTP synchronization? Once we drifted too far, the only solution is to manually set the time?
