### ISSUE TITLE
Undocumented requirement added for nfs root - /run/initramfs/shutdown

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#7221]
### Submission type

 - Bug report

### systemd version the issue has been seen with

https://github.com/neilbrown/systemd/commit/9cbc4547702aac28466c497f720038b9e2dc510c (in v235)

### Bug

The current documentation I'm aware of, that says where we require `/run/initramfs/shutdown`, is that it's about userspace daemons that provide / (or /usr).

https://www.freedesktop.org/wiki/Software/systemd/RootStorageDaemons/

As of systemd v235, this appears to have become outdated.  Shutdown to initramfs is now additionally required for NFS root.  Because `systemd-shutdown` won't remount `/` as read-only if it is NFS, therefore we rely on the initramfs unmounting it.  Can you confirm that analysis, @neilbrown ? [*]

That would work fine for dracut.  But I think it will break Debian users' NFS root setups though - in principle causing data loss without even an error message.  Debian doesn't have shutdown-to-initramfs AFAICT.  Therefore as well as docs, I would want to see a special case added somewhere in the code, to at least detect the unsupported configuration and... at least try to warn about the data loss.  Something a little noisy that can at least be noticed when you test a new setup.  I would also want to reach out to the Debian maintainers.

**OR**, do we want to revert the commit responsible and think again?  Maybe the plan of forking and setting timeouts (#6598) could make sense for remounting read-only, as well as for unmount?  I don't think we're really expecting to have anything mounted when we reach `systemd-shutdown` (that wasn't mounted by initramfs or kernel).  If there is such, it's already not a clean shutdown.

---

[*] The commit description says

> systemd-shutdown is run after the network is stopped,
> so remounting a network filesystem read-only can hang.
> A simple umount is the most useful thing that can
> be done for a network filesystem once the network is down.

The first assertion seems like a problem, because we have no other system to flush the root filesystem before the network goes down.  However, there is code for this in both Fedora and Debian networking scripts, which attempts to detect NFS root and avoid stopping the network in this case.

**Comment by sourcejedi** [comment]
https://github.com/systemd/systemd/pull/6598#issuecomment-337218705 already seems to suggest that if we can merge #6598, we would be able to revert the commit which caused me to write this issue.

**Comment by neilbrown** [comment]
There is no value in remountng a network filesystem read-only.during shutdown.
It is useful for local filesystems as it might cause the superblock to marked as "clean" so no recovery is needed at reboot, but that does not apply to network filesystems.
The only benefit that remount,ro might provide is to flush out dirty data, and there are calls to sync() before and after the remount/unmount attempts, so that is not a significant issue. (For nfs, remount,ro doesn't even do that - the dirty data is flushed on last close).
Have you observed any concrete problems that might be attributable to this commit, or it is just a theoretical concern?

**Comment by sourcejedi** [comment]
I can categorically deny having observed any NFS system recently.  I hope this isn't too annoying. I think I've seen all the pieces of how unmouting NFS is handled now, but the big picture is not familiar to me.

So the use of MNT_FORCE in systemd-shutdown is less significant than it might appear.  It could theoretically be replaced with MNT_DETACH (conditional on `m->type` being NFS etc).  You would only need shutdown-to-initramfs if some joker had overmounted nfsroot (or nfs `/usr`) over a different filesystem.  In which case you would have needed it anyway.

Thanks, you've cleared up my confusion.  Closed.

---

IOW there are three different ways to block or poll on pending NFS writes.

1. sync
2. remount read-only
3. unmount without MNT_FORCE.  (But not with MNT_FORCE.  In that case, if pending writes would have stopped the unmount, they are cancelled).

`sync()` differs in that a successful return doesn't exclude future write submissions.  But in systemd-shutdown, we exclude user processes from submitting more writes before we call sync(), by virtue of killing them.  (These in turn, should only be processes that have escaped from systemd units with non-default `KillMode`'s, including systemd services generated from LSB scripts).
