### ISSUE TITLE
Failed to start User Manager for UID 21

### ISSUE THREAD

**Issue by Sl0v3C** [systemd/systemd#7222]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234

### Used distribution

> BLFS

### In case of bug report: Expected behaviour you didn't see

> Start the user@ID.service

### In case of bug report: Unexpected behaviour you saw

> Failed all the user@ID.service except root user

### In case of bug report: Steps to reproduce the problem

> Follow the steps of BLFS guide, then reboot, it can login as root but any other user.

**Comment by michich** [comment]
> Follow the steps of BLFS guide

This thing?:
http://www.linuxfromscratch.org/blfs/downloads/stable-systemd/BLFS-BOOK-8.1-systemd-nochunks.html.bz2
It's 771 KiB compressed. Not exactly easy to reproduce steps.

Use journalctl to look for hints why the services are failing.

**Comment by poettering** [comment]
Please provide the precise error messages you are getting, i.e. the relevant log data. Otherwise there's little we can do.

**Comment by Sl0v3C** [comment]
@michich  Yep! It's BLFS 8.1 with systemd.
I checked the journalctl -p debug -b, found below msg:
**Failed to list cached users: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files**
the log as the attachment.
[journal.log](https://github.com/systemd/systemd/files/1429438/journal.log)

**Comment by yuwata** [comment]
> Failed to list cached users: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files

AccountsService is not part of systemd...

I am not sure, but it seems some configuration error in AccountsService, GDM or PAM.
Please contact to BLFS team.

**Comment by Sl0v3C** [comment]
@yuwata @michich @poettering THX anyway!

**Comment by poettering** [comment]
OK, let's close this here. This really doesn't look like any issue with systemd, and the BLFS community appears like the better people to help you with this.
