### ISSUE TITLE
fstrim.timer:6: Failed to parse calendar specification, ignoring: 48hr

### ISSUE THREAD

**Issue by simonbcn** [systemd/systemd#7224]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 235
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> It should recognize that value

### In case of bug report: Unexpected behaviour you saw

> fstrim.timer:6: Failed to parse calendar specification, ignoring: 48hr

### In case of bug report: Steps to reproduce the problem

> I change the frequency with which a timer runs on my system. I specific `[Timer]
OnCalendar=48hr`. The systemd help says this value is correct: https://www.freedesktop.org/software/systemd/man/systemd.time.html but it fails when it starts.

**Comment by michich** [comment]
systemd.time(7) shows the "48hr" syntax as a valid time ***span***, but not as a valid time**stamp** or as a calendar event specification. `OnCalendar` expects a calendar event specifier. Try something like `OnCalendar=Tue,Thu,Sat` or `OnCalendar=*-*-1/2`.

**Comment by simonbcn** [comment]
Please, fix the help page.
