### ISSUE TITLE
allow setting of multicast querier for linux bridge

### ISSUE THREAD

**Issue by zdzichu** [systemd/systemd#723]
For Linux bridge, there's a Multicast Querier setting in the sysfs. It is meant as and ”optimisation”, but in my trials it's needed to have stable multicast operation over the bridge.
It is controlled by writing to sysfs, for example:  
`echo "1" > /sys/devices/virtual/net/br0/bridge/multicast_querier`

Could you consider extending Linux bridge configuration in systemd-networkd?  There should be `MulticastQuerier=true/false` option, which if set, should write to sysfs during bridge configuration.

**Comment by keszybz** [comment]
If it is better to have it on, I'd vote for defaulting to MulticastQuerier=yes.

**Comment by zdzichu** [comment]
In this case it would be turned on in the kernel. But kernel switched to "off" some time ago: http://comments.gmane.org/gmane.linux.network/227120

**Comment by keszybz** [comment]
Pfff. So some networks break when it's on, some break when it's off. Business as usual :)
But you're right, honoring the kernel defaut seems like the right thing to do.

**Comment by poettering** [comment]
Hmm, is there any documentation available explaining the effect of this option? Couldn't find any with a quick google search?

**Comment by zdzichu** [comment]
There is no specific documentation for that; Wikipedia has one paragraph summary: https://en.wikipedia.org/wiki/IGMP_snooping#IGMP_querier

**Comment by ssahani** [comment]
We can't write to sysfs via networkd for  example 
sys/devices/virtual/net/br-test/bridge/multicast_querier

```
open("/sys/devices/virtual/net/br-test/bridge/multicast_querier", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
open("/sys/devices/virtual/net/br-test/bridge/multicast_querier", O_RDONLY|O_CLOEXEC) = 9
fstat(9, {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
```

Which permission we require ?

Now we have 
  (1ULL << CAP_NET_ADMIN) |
   (1ULL << CAP_NET_BIND_SERVICE) |
    (1ULL << CAP_NET_BROADCAST) |
     (1ULL << CAP_NET_RAW));

**Comment by ssahani** [comment]
Coming back to this I just realised NL support has been added to kernel via parameter  
IFLA_BR_MCAST_QUERIER. Will post a patch .

https://patchwork.ozlabs.org/patch/580549/
