### ISSUE TITLE
Bootctl boot menu resolution and centering

### ISSUE THREAD

**Issue by kittydoor** [systemd/systemd#7230]
### Submission type

- Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

bootctl, or in other words systemd-boot, does not seem to support any kind of way to explicitly set resolution. It's behavior changes from machine to machine, but often the detected resolution and placement leads to a smaller than intended and off center (closer to the left side) menu. A config option for the loader would be very beneficial in fixing this manually.

**Comment by poettering** [comment]
Duplicate of #2750.
