### ISSUE TITLE
nspawn: /sys/devices/virtual/net writable inside container

### ISSUE THREAD

**Issue by jessetane** [systemd/systemd#7231]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> arch

I am trying to use nspawn to experiment with some mesh routing protocols. I want to use udev inside containers (rules to update relevant services as network devices come and go) which in turn wants to be able to "cold plug" network devices that are present at boot by writing to `/sys/devices/virtual/net/<interface>/uevent`. I imagined doing this by bind mounting `/sys/devices/virtual/net` before `/sys` was remounted read-only, but can't seem to figure out how to do that given d8fc6a000fe21b0c1ba27fbfed8b42d00b349a4b.

I played with the env var `SYSTEMD_NSPAWN_API_VFS_WRITABLE` which was introduced in 4f086aab52812472a24c9b8b627589880a38696e, but when set to `1` sysfs gets mounted in the outer child which is not what I want. I also considered adapting the flag's possible `"network"` value but wasn't sure if this would align well with the original author's (cc @s-urbaniak) intent.

I hacked up a quick patch [here](https://github.com/jessetane/systemd/commit/42f0f9a9ebb64498c451257ea7c97ae8882908b0) that works, but it's far from ideal and I assume there must be a better way. If having this behavior is even a good idea in the first place I am willing to work on another patch but could use some guidance.

**Comment by tixxdz** [comment]
Actually we always followed the path that device nodes are not fully supported inside nspawn, hence that code.

Why are you using nspawn or a container for this case ? 

Also we have RootImage= and you can combine it with our other options from:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html

You should check all ReadWritePaths=, ReadOnlyPaths=, InaccessiblePaths= , MountAPIVFS=, and maybe you can give it a try and see what options you can use to construct your environment ?

**Comment by jessetane** [comment]
> Actually we always followed the path that device nodes are not fully supported inside nspawn, hence that code.

Right, but virtual network interfaces are an here exception, no? Isn't `/sys/devices/virtual/net` part of sysfs that might actually make sense to support inside containers?

> Why are you using nspawn or a container for this case ?

The point of using containers is to quickly and easily simulate arbitrary network topologies composed of multiple "machines".

**Comment by poettering** [comment]
Running udev in containers is not supported, sorry. The Linux kernel simply doesn't virtualize device management for the purpose of contains, hence if you'd run udev inside a container there'd be constant fighting over the devices. Sorry, but this is nothing we can support...

Anyway, if you use -N the directory is writable out of the box, and otherwise you should just be able to use --bind=/sys/devices/virtual/net so that it gets mounted writable from the host.

Either way, this all voids your warranty. Let's close this hence.
