### ISSUE TITLE
virt: detect QNX by systemd-detect-virt

### ISSUE THREAD

**Issue by Shuangistan** [systemd/systemd#7239]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

- master

### In case of RFE:

- QNX is not detected by systemd-detect-virt

```
#: SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
Found container virtualization none
No virtualization found in DMI
Virtualization found, CPUID=QNXQVMBSQG
Found VM virtualization vm-other
vm-other
```

- The CPUID from QNX is fixed and we could add it to src/basic/virt.c

**Comment by keszybz** [comment]
Yes, that'd be great. Any chance you could submit a PR that implements this? We don't have access to the software. Please refer to aa0c34279ee40bce2f9681b496922dedbadfca19 to see what changes would be necessary.

**Comment by Shuangistan** [comment]
Yeah, it takes some time.

**Comment by Shuangistan** [comment]
Finally the PR is created #8251
