### ISSUE TITLE
Resume from suspend-to-disk with encrypted swap times out at password prompt

### ISSUE THREAD

**Issue by SebastianS90** [systemd/systemd#7242]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> When resuming from suspend-to-disk I expect the system to actually resume the saved state, even if I take a bit longer to enter the luks passphrase.

### In case of bug report: Unexpected behaviour you saw

> The system started with a fresh session and thereby wiped out the saved hibernation state.

### In case of bug report: Steps to reproduce the problem

**Disk setup:**
* `/dev/sda1` efi system partition, also containing `initramfs-linux.img` and `vmlinuz-linux`.
* `/dev/sda2` cryptsetup luksFormat
  * LVM pv
    * LVM vg `vg0`
      * `vg0/root` root partition
      * `vg0/swap` swap partition

**Kernel options** (from systemd-boot):
* `rd.luks.uuid=...` (uuid of `sda2`)
* `rd.luks.options=tries=0,timeout=0`
* `rd.lvm.lv=vg0/root`
* `rd.lvm.lv=vg0/swap`
* `resume=UUID=...` (uuid of `vg0/swap`)
* `root=UUID=...` (uuid of `vg0/root`)
* `rootflags=x-systemd.device-timeout=0`
* `rw`

**mkinitcpio.conf:**
```
HOOKS=(base systemd autodetect modconf block keyboard sd-vconsole sd-encrypt sd-lvm2 filesystems fsck)
```

**Reproduce the issue:**
1. Start the powered off machine. You have unlimited time to enter the luks password (thanks to both timeout settings in the kernel options)
2. Hibernate (suspend to disk)
3. Power on again. Get a coffee. Come back to the password prompt (> 90s have passed)
4. Enter the luks password
5. Without further notice, the system boots a fresh session instead of resuming, thus wiping your suspended state.

The problem happens only when you wait > 90s in step 3, otherwise resuming works fine.

### Detailed analysis
There are two targets:
* `initrd-root-fs.target` *requires* and is *after* `dev-disk-by\x2duuid-ROOTUUID.device` via `/run/systemd/generator/initrd-root-fs.target.d/50-root-device.conf`
  * there is a drop-in `/run/systemd/generator/dev-disk-by\x2duuid-ROOTUUID.device.d/50-device-timeout.conf` that sets `JobRunningTimeoutSec=infinity`
* `sysinit.target` *wants* `systemd-hibernate-resume@dev-disk-by\x2duuid-SWAPUUID.service` via a symlink in `/run/systemd/generator/sysinit.target.wants`
  * `systemd-hibernate-resume@%i.service` *binds to* and is *after* `%i.device`
    * there is no configuration for `dev-disk-by\x2duuid-SWAPUUID.device`, thus falling back to the default of `JobRunningTimeoutSec=90s`

After 90 seconds without password, the following happens:
```
dev-disk-by\x2duuid-SWAPUUID.device: Job dev-disk-by\x2duuid-SWAPUUID.device/start timed out.
Timed out waiting for device dev-disk-by\x2duuid-SWAPUUID.device.
Dependency failed for Resume from hibernation using device /dev/disk/by-uuid/SWAPUUID.
systemd-hibernate-resume@dev-disk-by\x2duuid-SWAPUUID.service: Job systemd-hibernate-resume@dev-disk-by\x2duuid-SWAPUUID.service/start failed with result 'dependency'.
dev-disk-by\x2duuid-SWAPUUID.device: Job dev-disk-by\x2duuid-SWAPUUID.device/start failed with result 'timeout'.
Reached target Local File Systems (Pre).
Reached target Local File Systems.
```

There is no visual feedback for this. The password prompt is still there and when I enter the password, it goes on like this:
```
systemd-cryptsetup[216]: Set cipher aes, mode xts-plain64, key size 256 bits for device /dev/disk/by-uuid/LUKSUUID.
kernel: NET: Registered protocol family 38
systemd[1]: Started Cryptography Setup for luks-LUKSUUID.
systemd[1]: Reached target Local Encrypted Volumes.
systemd[1]: Reached target System Initialization.
systemd[1]: Reached target Basic System.
systemd[1]: Created slice system-lvm2\x2dpvscan.slice.
systemd[1]: Starting LVM2 PV scan on device 253:0...
systemd[1]: Started LVM2 metadata daemon.
systemd[1]: Found device /dev/disk/by-uuid/ROOTUUID.
systemd[1]: Reached target Initrd Root Device.
systemd[1]: Starting File System Check on /dev/disk/by-uuid/ROOTUUID...
systemd-fsck[292]: /dev/mapper/vg0-root: recovering journal
lvm[275]:   2 logical volume(s) in volume group "vg0" now active
systemd[1]: Started LVM2 PV scan on device 253:0.
```
(system starts normally, not resuming the saved state)

### Suggested fix
The important part is the file `/run/systemd/generator/dev-disk-by\x2duuid-ROOTUUID.device.d/50-device-timeout.conf` which sets `JobRunningTimeoutSec=infinity`. This results from the kernel parameter `rootflags` where I specified `x-systemd.device-timeout=0`.

But there is no such configuration option for the swap partition. We would need a similar drop-in specifying the timeout for the swap device.

**Suggestions:**
* Take the same timeout as given in `rootflags=x-systemd.device-timeout=X` for both the root device and the resume/swap device. It is likely that this is what the user actually wants.
* (or) introduce a new kernel parameter `resumeflags` that behaves similar to `rootflags`, but applies the options to the device specified in `resume=` instead of `root=`.

**Ugly workaround:** *(~~Although I have not tried it~~ it works!)*
Manually inject the necessary drop-in into the initial ramdisk, probably in `/etc/systemd/system/${SWAPDEVICE}.device.d/50-device-timeout.conf`. But to do so, you need to explicitly put the swap device name into the initrd image.

**Comment by tomty89** [comment]
Could it actually be because systemd-hibernate-resume@ service is not strictly ordered after the cryptsetup target?

**Comment by SebastianS90** [comment]
@tomty89 unfortunatelly no. I manually added a file `/etc/systemd/system/systemd-hibernate-resume@.service.d/cryptsetup.conf` to my initial ramdisk:
```
[Unit]
After=cryptsetup.target
```

The file is present and read by systemd in initrd (`systemctl show systemd-hibernate-resume@dev-disk-by\x2duuid-SWAPUUID.service` correctly has `cryptsetup.target` in `After=`).

But it does not help, the swap device still times out after 90 seconds such that `systemd-hibernate-resume@...` fails silently.

**Comment by brianjmurrell** [comment]
Given that #12753 only landed for 243 and newer, is there a way to effect this change on 241 (circa Fedora 30)?  Can I add something to my kernel commandline to effect a longer timeout for the luks encrypted swap LV?

**Comment by SebastianS90** [comment]
@brianjmurrell
The default timeout for the root device as well as the resume device is 90 seconds (see `man systemd-system.conf` entry `DefaultTimeoutStartSec`). If you wait longer, than neither booting nor resuming works.

You can modify the root device timeout using the `rootflags=x-systemd.device-timeout=0` kernel parameter (`0` disables the timeout). From systemd 243 onwards, this also sets the resume device timeout. Before version 243 we have the problem described in this issue.

Specifying `resumeflags=` in a version before 243 probably has no effect, and from 243 onwards it is only useful if you actually want different settings for the resume device and the root device.

The workaround for versions before 243 is to place a file `/etc/systemd/system/${SWAPDEVICE}.device.d/50-device-timeout.conf` into the initial ram disk image (not sure how this works on Fedora, on Arch this can be done using the `FILES` setting in `mkinitcpio.conf`) with the following content:
```
[Unit]
JobRunningTimeoutSec=infinity
```
Obviously you have to replace `${SWAPDEVICE}` with the name of your swap device, that depends on what you use for the `resume=` kernel parameter. That makes this workaround ugly, because you have to bake the swap device name into the initrd image instead of just specifying it as kernel parameter.

**Comment by keszybz** [comment]
We should do this automatically. I'm working on a PR.

**Comment by SebastianS90** [comment]
@keszybz What do you want to do automatically?
The problem I described in this issue requires that the timeout for the resume device is smaller than the timeout for the root device. The current systemd (from 243 onwards) automatically defaults the resumeflags to the rootflags, thus the timeout will be the same if not explicitly configured to different values.

The only possible optimization I see is defaulting the device timeout for both root and resume device to 0 (i.e. no timeout) when luks is used. Currently the default timeout is 90 seconds.
