### ISSUE TITLE
RFE - comment for unit addable by systemctl

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#7245]
Hi,

please consider implement a possibillity to add an arbitrary comment to a unit that is displayed with systemctl status _at_ _runtime_. This would greatly ease collaborative system administration since one could give explanation, for example, _why_ a service is turned off at the moment.

Possible usage:
```
systemctl --comment='this system uses socket activated ssh' disable ssh.service
systemctl status ssh.service
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; disabled; vendor preset: ena
   Active: inactive (dead)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/ssh.service
  Comment: this sysetm uses socket activated ssh

systemctl --comment='migrated to new host newweb.example.com' disable apache2@some.site.example
```

**Comment by bl33pbl0p** [comment]
There is [systemd-cat](https://www.freedesktop.org/software/systemd/man/systemd-cat.html).

Example:
`systemd-cat -t ... -p ... echo "migrated to new host newweb.example.com" && systemctl disable ...`

If comments are added, they are then attached to the unit in the journal, which imo would not be nice.

**Comment by poettering** [comment]
The Description= field in unit files could be used for that, no? just override it with .d dropins?

We could even make that dynamically updatable, so that you can do "systemctl set-property foo.service Description=foobar" and so on? Would that work for you?

**Comment by boucman** [comment]
could the substate be used for that somehow ?

**Comment by poettering** [comment]
@Zugschlus so, with #7444 you can dynamically alter the documentation string of a unit:

```
# systemctl set-property foobar.service Description="This is a test"
```

This will be stored on disk, and is thus persistent. As with other properties, you can also make a temporary change only, that is lost on next reboot:

```
# systemctl set-property --runtime foobar Description=Miau
```

And when you don't like it anymore, and want to revert to the original, vendor shipped description (i.e. the one in the unit file itself):

```
systemctl revert foobar.service
```

This should be good enough to cover your usecase no?

I am not too keen of adding a second description field if you so will, but these new semantics should match what you are looking for, no?

**Comment by keszybz** [comment]
#7444 has been merged. Let's close this. Please reopen if this solution does not work for you.
