### ISSUE TITLE
Dell E7570 hwdb dimensions are incorrect disabling edge scrolling

### ISSUE THREAD

**Issue by macrothian** [systemd/systemd#7252]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd-233-7

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

Edge scrolling was working in previous release

### In case of bug report: Unexpected behaviour you saw

Edge scrolling stopped working. 

### In case of bug report: Steps to reproduce the problem

/usr/lib/udev/hwdb.d/60-evdev.hwdb in this version has added the following section:

evdev:name:AlpsPS/2 ALPS DualPoint TouchPad:dmi:bvn*:bvr*:bd*:svnDellInc.:pnLatitudeE7470*
 EVDEV_ABS_00=39:5856:59
 EVDEV_ABS_01=10:1532:29
 EVDEV_ABS_35=39:5856:59
 EVDEV_ABS_36=10:1532:29

Touchpad AlpsPS/2 ALPS DualPoint TouchPad on /dev/input/event7
Move one finger around the touchpad to detect the actual edges
Kernel says:    x [39..5856], y [10..1532]
Touchpad sends: x [29..2930], y [26..1533] /^C

Touchpad size as listed by the kernel: 98x52mm
User-specified touchpad size: 98x52mm
Calculated ranges: 2901/1507

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:AlpsPS/2 ALPS DualPoint TouchPad:dmi:bvnDellInc.:bvr1.17.5:bd07/11/2017:svnDellInc.:pnLatitudeE7470:pvr:rvnDellInc.:rn0T6HHJ:rvrA00:cvnDellInc.:ct9:cvr:*
 EVDEV_ABS_00=29:2930:30
 EVDEV_ABS_01=26:1533:29
 EVDEV_ABS_35=29:2930:30
 EVDEV_ABS_36=26:1533:29

Overriding the provided settings in /etc/udev/hwdb.d/61-evdev-local.hwdb with:

evdev:name:AlpsPS/2 ALPS DualPoint TouchPad:dmi:bvn*:bvr*:bd*:svnDellInc.:pnLatitudeE7470*
 EVDEV_ABS_00=29:2930:30
 EVDEV_ABS_01=26:1533:29
 EVDEV_ABS_35=29:2930:30
 EVDEV_ABS_36=26:1533:29"

Edge scrolling back to normal.

**Comment by whot** [comment]
yeah, on second look the 5856 does indeed look very unusual for an alps pad. @macrothian please submit the change as a PR and I'll merge it.

**Comment by whot** [comment]
wrong button, sorry. re-opening

**Comment by whot** [comment]
github didn't pick up on the cross reference in the subject, but #7263 is the PR for this bug
