### ISSUE TITLE
systemd-run --pipe command without CAP_DAC_* cannot read /dev/stdin if stdin is pipe by other user

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#7254]
## Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> ```sh
> $ echo hi | sudo systemd-run -q --pipe -p DynamicUser=yes cat /dev/stdin
> hi
> ```

### In case of bug report: Unexpected behaviour you saw

> ```sh
> $ echo hi | sudo systemd-run -q --pipe -p DynamicUser=yes cat /dev/stdin
> /usr/bin/cat: /dev/stdin: Permission denied
> ```

### In case of bug report: Steps to reproduce the problem

> `echo hi | sudo systemd-run -q --pipe -p DynamicUser=yes cat /dev/stdin`

or:

> `echo hi | sudo systemd-run -q --pipe -p User=nobody cat /dev/stdin`

or:

> `echo hi | sudo systemd-run -q --pipe -p CapabilityBoundingSet=~'CAP_DAC_READ_SEARCH CAP_DAC_OVERRIDE' cat /dev/stdin`

In the case of `cat`, you can just use `cat -` or `cat`, of course, but there are tools which don’t support that convention and need an explicit file name.

This only happens when stdin is a pipe by another user. For instance, `systemd-run … < /etc/hostname` or `echo hi | systemd-run -p User=$USER …` both work. So I guess there must be something to pipe permissions that I’m not aware of.

**Comment by lucaswerkmeister** [comment]
Actually, this doesn’t seem to be due to the user being dynamic, with `User=nobody` instead of `DynamicUser=yes` I get the same problem.

**Comment by lucaswerkmeister** [comment]
Hm, so after a few iterations of messing with this bug (see the various title changes above), I’ve finally arrived at the realization that this simple command produces the same behavior:

```sh
$ echo hi | sudo -u nobody cat /dev/stdin
cat: /dev/stdin: Permission denied
```

So I guess this isn’t even a systemd bug, just some odd behavior of who’s allowed to read from `/proc/self/fd/0` that I wasn’t previously aware of nor can find any documentation on?

Does anyone know more about this?

**Comment by lucaswerkmeister** [comment]
I think I’ve figured out what happens. The owner of the `/proc/self/fd/0` *symlink* is `nobody` (or whatever user the process runs under), but the owner of the inode it points to is the user that created the pipe, and that’s what matters when trying to open the file.

I’ve submitted a patch against **proc**(5) to the man-pages project which should hopefully clarify this behavior. We could also add something like the following to the `systemd-run` `--pipe` documentation:

> Note that if the service runs as an unprivileged user (e. g. with `DynamicUser=yes`), it may not have permission to reopen the pipes that its standard input, output or error refer to, so using e. g. `/dev/stdin` as filename may not work.

**Comment by lucaswerkmeister** [comment]
The man-pages project patch has been merged ([cgit](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/commit/?id=81c8aeb64903ef6ae45e872bfd46814e6a11bdec)), so I’ll leave it up to you if you want to adapt **systemd-run**(1) as well or just close this issue :)

**Comment by poettering** [comment]
So, as I understand this has little to do with the ownership of the symlink. Instead, this all comes down to whether the file the fd you are referring to can actually be opened again, and what the security restrictions on the original inode are.

So, for example, if fd x is a socket, then opening /proc/self/fd/x will necessary fail, because sockets cannot be opened with open(), but require socket()/connect() and friends. Similar, if x refers to a tty device that is not accessible to your user (for example due to its access mode), then opening /proc/self/fd/x won't work either.

Or to say this differently: opening /proc/self/fd/x is really an open(), it's not just a dup()! If the file fd x refers to wasn't open()able by you in the first place, than opening through /proc/self/fd/x is not gonna work either.

**Comment by poettering** [comment]
And yeah, we should probably document this in our man pages too.

**Comment by poettering** [comment]
Documentation patch waiting in #7317

**Comment by lucaswerkmeister** [comment]
The funny thing is, I saw the note about `/dev/stderr` in the TODO file just yesterday :)
