### ISSUE TITLE
interfaces get renamed even after symlinking /etc/systemd/network/99-default.link to /dev/null

### ISSUE THREAD

**Issue by jayeye** [systemd/systemd#7259]
### Submission type

 - Bug report

### systemd version the issue has been seen with

$ systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

### Used distribution

Ubuntu 16.04.2 LTS server, fully patched.
> …

### In case of bug report: Expected behaviour you didn't see

Per https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/ I created

 $ ls -l /etc/systemd/network/
total 0
lrwxrwxrwx 1 root root 9 Nov  5 23:42 99-default.link -> /dev/null

Upon rebooting, I was expecting the ethernet interface to not be renamed to ens3

> …

### In case of bug report: Unexpected behaviour you saw

The interface was renamed to 
ip link list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT group default qlen 1000

> …

### In case of bug report: Steps to reproduce the problem

Install ubuntu 16.04 LTS 
ln -s /dev/null /etc/systemd/network/99-default.link
reboot

**Comment by mbiebl** [comment]
Have you read /usr/share/doc/udev/README.Debian.gz, specifically
```
    and rebuild the initrd with "update-initramfs -u".
```
udevd is already started in the initramfs. You need to make sure your initramfs is rebuilt and contains the /dev/null symlink as well

**Comment by yuwata** [comment]
Please try to set `net.ifnames=0` in kernel cmdline.

**Comment by poettering** [comment]
Yeah, this really looks as if you didn't update your initrd, and hence the old file is still applied during early boot in the initrd. Closing hence.

if you actually did rebuild the inird, let's reopen this, but your comments suggest you didn't...
