### ISSUE TITLE
Cannot provide socket for other processes when using RuntimeDirectory= with DynamicUser=yes

### ISSUE THREAD

**Issue by djmattyg007** [systemd/systemd#7260]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235

### Used distribution

Arch Linux

### Expected behaviour you didn't see

The announcement blog post for the DynamicUser functionality mentions that you can combine DynamicUser with RuntimeDirectory to provide a socket for other processes to write to:

http://0pointer.net/blog/dynamic-users-with-systemd.html

> The RuntimeDirectory= option may be used to open up a bit the sandbox to external programs. If you set it to a directory name of your choice, it will be created below /run when the service is started, and removed in its entirety when it is terminated. The ownership of the directory is assigned to the service's dynamic user. This way, a dynamic user service can expose API interfaces (AF_UNIX sockets, …) to other services at a well-defined place and again bind the life-cycle of it to the service's own run-time.

I tried to test this with uwsgi and nginx. nginx's worker processes are running as the user and group `http`. This is the service unit for uwsgi:

    [Unit]
    Description=uWSGI service unit
    After=syslog.target

    [Service]
    ExecStart=/usr/bin/uwsgi --ini /etc/uwsgi/myuswgiapp.ini
    ExecReload=/bin/kill -HUP $MAINPID
    ExecStop=/bin/kill -INT $MAINPID
    Restart=always
    Type=notify
    StandardError=syslog
    NotifyAccess=all
    KillSignal=SIGQUIT
    DynamicUser=yes
    Group=http
    SupplementaryGroups=http
    RuntimeDirectory=myuwsgiapp
    UMask=0002

    [Install]
    WantedBy=multi-user.target

uwsgi is configured to create a socket at `/run/myuwsgiapp/uwsgi.sock`, and nginx is configured to write to that path too. The socket is created with the permissions `0775`, and the user and group are `uwsgi` (the dynamic user) and `http`, as expected. However, nginx always generates an error message stating that it does not have permission to write to that path.

I understand that this is because `/run/myuwsgiapp` is a symlink to `/run/private/myuwsgiapp`, and `/run/private` has the permissions `0700` and owned by `root:root`. Perhaps I am going about this the wrong way, but it definitely seems like an intended use-case. Is anyone able to advise where I've gone wrong?

**Comment by yuwata** [comment]
After #6940 is merged, if `DynamicUser=` is set, the directory specified by `RuntimeDirectory=` or their friends cannot be acceessed by non-privileged users. So, in your use case, you cannot use `DynamicUser=`.

@poettering The blog post may need to be rewritten.

**Comment by yuwata** [comment]
Or should we relax the permission of `private` directories? But it breaks the concept intruduced by #6940...

**Comment by yuwata** [comment]
@djmattyg007 As a dirty workaround, other services can access the 'private' runtime directory with `BindReadOnlyPaths=`. See the following example.
```
$ systemctl cat hoge.service
# /etc/systemd/system/hoge.service
[Service]
DynamicUser=1
RuntimeDirectory=hoge
ExecStart=/bin/sh -c 'echo hogehoge > /run/hoge/hoge.txt; sleep 1h'
$ systemctl cat foo.service
# /etc/systemd/system/foo.service
[Service]
DynamicUser=1
BindReadOnlyPaths=/run/private/hoge:/run/foo
ExecStart=/bin/sh -c 'cat /run/foo/hoge.txt'
```

**Comment by poettering** [comment]
Urks, yeah, I broke this. We probably shouldn't do the "private/" symlink stuff for /run. Yuck, I didn't realize the impact in this regard. Bummer.

**Comment by yuwata** [comment]
I've created #7275.

**Comment by djmattyg007** [comment]
Thank you both very much! It's greatly appreciated.
