### ISSUE TITLE
Make systemd-timesyncd NTP poll interval configurable.

### ISSUE THREAD

**Issue by conqp** [systemd/systemd#7262]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch

It would be nice to have the ability to configure the NTP poll interval of systemd-timesyncd via (a new option in) /etc/systemd/timesyncd.conf.

**Comment by yuwata** [comment]
I've proposed that once in PR #7215. Then I got questions like "should we make this configurable at all? How likely are people to adjust any of those settings?" or "how often users will use all these new 5 options ?".

**Comment by yuwata** [comment]
@conqp I've created PR #7268. Please take a look.
