### ISSUE TITLE
Linux system switch iso，iso content is not complete

### ISSUE THREAD

**Issue by neilgen** [systemd/systemd#7269]
### bug
-Bug report
Description of the problem：I install a fedora25 system in the kvm virtual machine. when I switch the iso file, the new iso contents is not complete in the linux file system。But if I reject the mounted iso，then switch the iso，the contents is ok。 
OS：Fedora21 ~ Fedora25 ,or other system like ubuntu
systemd version: 
I have been testing some versions，the version of github id 496068a8288084ab3ecf8b179a8403ecff1a6be8 is no 
problem. the newest version  is still a problem。

**Comment by poettering** [comment]
What is "switch the iso file" supposed to mean? Can you elaboratr please? I have trouble grokking what you are trying to say...

**Comment by neilgen** [comment]
"switch iso file" is changed the cdrom file like CD image file when current cdrom is using. Because I install fedora in virt-manager, so change the CD ROM file in the virt-manager。

**Comment by poettering** [comment]
And what is "the new iso contents is not complete in the linux file system" supposed to mean? In which way "not complete"?

**Comment by neilgen** [comment]
thanks，maybe I says dimness. The files on the CD are viewed with the ls command or file explorer,
There are only a few files, no folders. Fewer files than a CD.

**Comment by poettering** [comment]
Did you unmount the CD before you ejected it?

**Comment by neilgen** [comment]
Yes, this operation will result in the problem。My expectation is that the next time I insert CD, it will be normal。

**Comment by poettering** [comment]
I am sorry, but systemd is not involved in ISO9660 file system support. If the file system appears "incomplete", then systemd is really not involved. What makes you think that systemd has anything to do with this issue at hand?

**Comment by poettering** [comment]
Anyway, I will close this now. systemd is not implementing file systems on its own. If there's a problem with your ISO9660 file system, then that's something to discuss with file system people really, and that's outside of systemd's scope. I hope that makes sense. Closing.
