### ISSUE TITLE
Mem Leak + Dangling Pointer on sd-bus Slot Delete (when compiled with NDEBUG)

### ISSUE THREAD

**Issue by dleeds-cpi** [systemd/systemd#7270]
### Submission type

 - Bug report

### systemd version the issue has been seen with:

master

### Bug

Hashmap entry for node is not removed when assertions are disabled.  This causes memory leak and dangling pointer when slot associated with the node is deleted.

bus-objects.c:1501 bus_node_gc()
`assert(hashmap_remove(b->nodes, n->path) == n);`

### Fix

Never do work inside an assertion!

**Comment by yuwata** [comment]
Thanks. If possible, please test with #7271.

**Comment by dleeds-cpi** [comment]
Will do!

**Comment by poettering** [comment]
ah, oh. Yeah, this should be an assert_se() indeed (which is our flavour of assert() that remains unaffected by NDEBUG).
