### ISSUE TITLE
RemoveIPC, added in v232, is not unit-file-configurable

### ISSUE THREAD

**Issue by weber-martin** [systemd/systemd#7281]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v232 ... master@f5f0dca0ceb0430ffde0ccfe1791ab73bf246c29

### Used distribution

> n/a

### In case of bug report: Expected behaviour you didn't see

Being able to set RemoveIPC option on service units not only via d-bus, but also via setting in the service's unit file.

### In case of bug report: Unexpected behaviour you saw

When setting RemoveIPC option, harvest error message about unsupported option

### In case of bug report: Steps to reproduce the problem

Create a service that uses an explicit RemoveIPC= setting
Use systemd / systemctl to start that unit.
Observe error output in unit log
Observe setting not being applied

### Patch

[sd.txt](https://github.com/systemd/systemd/files/1457466/sd.txt)

**Comment by yuwata** [comment]
@weber-martin Indeed... However, the option is defined in execute.c or dbus-execute.c. So, please do not add in Service section but add this in ExecContext, that is, specify it as `$1.RemoveIPC` in load-fragment-gperf.gperf.m4. Could you submit the revised patch? Or can I submit it?

**Comment by weber-martin** [comment]
I put it under service, because, AFAICT, this option only applies to .service, even though it is documented in man systemd.exec.

From the header, it says, configuration files for services, sockets, mount points and swap devices.
AFAIUI, RemoveIPC though is NOT applicable to sockets, mount points or swap devices.

@yuwata that being said, if you'd rather path it into `$1`, please go ahead. I'm not going to regenerate a one line patch ;) TIA!

**Comment by yuwata** [comment]
@weber-martin Hmm... I've not tested yet, but I guess that many options explained in systemd.exec(5) only work in service units. But anyway, this should be in ExecContext. OK. I will submit the revised patch. Thanks.
