### ISSUE TITLE
Print the processes that are still running when waiting to stop user session

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#7292]
Hi,

One of the common complains that I can see is the fact that sometimes a user session takes a long time to stop on shutdown.

Trouble shooting is quite difficult because it requires you to have enabled the debug-shell before hand.

Could it be possible to print the remaining running processes while systemd is waiting to the user session to stop? Or at least logging that in logs/journald?

**Comment by hifi** [comment]
Could systemd also provide a keyboard shortcut to force shutdown regardless of the background processes not behaving correctly? I'm thinking that would make everyone happy when you can also see the list of processes if you know some program might take a while to cleanly exit or if some doesn't.

We lived with unconditional forced shutdown before systemd and everything was mostly fine and now almost every time I try to reboot I need to wait way too long.

The keys I keep hitting intuitively when waiting are <kbd>Ctrl</kbd>+<kbd>C</kbd>, <kbd>Ctrl</kbd>+<kbd>D</kbd> and <kbd>ESC</kbd>.

Heck, even Windows has an option to force shutdown!

**Comment by poettering** [comment]
hifi: Yeah, systemd has that already. See CtrlAltDelBurstAction=. By default all you need to do is hit Ctrl-Alt-Del 7 times in 2s.

**Comment by hifi** [comment]
@poettering I've tried that but it doesn't force/cancel the wait. It shows the message that it's going to reboot but it will still wait 'till the end.

**Comment by poettering** [comment]
@hifi well, if that doesn't work, then that's something to discuss in an independent issue, not here. Also, please provide log output/screenshot in that case.

**Comment by poettering** [comment]
@hifi well, we currently default to CtrlAltDelBurstAction= to "reboot-force", which means we'll not wait for daemons, but we'll still try to get file systems into a clean state. If you have hanging NFS then that's going to hang too though. You can change the action to "reboot-immediate" to shortcut that too, at the price of dirty file systems after the reboot.

But anyway, this really shouldn't be discussed here, this issue is not about C-A-d

**Comment by poettering** [comment]
I guess this is actually fixed by 3889fc6fc347f0e12070f7b873d065508c8df816
