### ISSUE TITLE
intltool-merge should not be required if polkit support is disabled

### ISSUE THREAD

**Issue by michaelolbrich** [systemd/systemd#7300]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v235

`intltool-merge` is only used to generate policy files, so it is not really needed if policykit support is disabled.

With autoconf it was possible to skip the check by adding `ac_cv_path_INTLTOOL_MERGE=:` to the environment before calling `configure`.

With meson that is no longer possible. I tried to make the check optional like this:
`intltool_merge = find_program('intltool-merge', required : install_polkit)`
However it still fails later for the rules that us it, even though they will never be executed.

I'm not sure how this should be fixed. Wrapping those rules with `if install_polkit` seems rather clumsy: The check is already provided by `install : install_polkit`. What's the best way to handle this?

**Comment by mbiebl** [comment]
I wonder what happened to https://github.com/systemd/systemd/pull/1513 and https://lists.freedesktop.org/archives/systemd-devel/2015-September/034220.html

**Comment by mbiebl** [comment]
I see that other projects made that switch apparently: https://lists.freedesktop.org/archives/modemmanager-devel/2017-September/005764.html

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/pull/1609#issuecomment-171591537
> The required functionality has been implemented in gettext-0.19.7. I'll get back to this Real Soon (tm).

**Comment by keszybz** [comment]
There have also been improvements in the meson i18n support. Somebody would need to have to investigate all the options and update our configuration.
