### ISSUE TITLE
Revert effect of commit e419a0e

### ISSUE THREAD

**Issue by jobol** [systemd/systemd#7311]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> e419a0e..master

### Used distribution

> Ubuntu

### Description

Since commit e419a0e systemd handles SMACK64EXEC to automatically setup  the environment.

I see some issues here:
 - Because Smack is simple, it can be handled correctly in the way introduced by e419a0e. But what for other MAC LSM? Is it compatible with selinux or apparmor? I'm almost sure that the answer is no but I would like a confirmation from experts.
 - The commit introduces a hidden dependency to the executed program file. Because it is hidden it is not explicit and can't be seen in the service file. IMHO, it is harmeful to readability.
 - this is conditional to SMACK_DEFAULT_PROCESS_LABEL

For these reason, I propose to enhance systemd by removing the effect introduced by the commit e419a0e. The benefits are:
 - Same behaviour for all MAC LSM
 - No hidden setting

**Comment by poettering** [comment]
@walyong @cschaufler can you comment?

(I am not a SMACK expert and can't possibly comment on the validity of this request, I rely on your input on this)

**Comment by walyong** [comment]
I think this should be not reverted.

systemd is running privileged SMACK label. SMACK_DEFAULT_PROCESS_LABEL is defined to prevent the systemd children have privileged label.

We have to consider access/exec at the separate side. SMACK64 is used for accessing the file. And SMACK64EXEC is used to set the subject of the process.

When SMACK_DEFAULT_PROCESS_LABEL is defined, we can think below cases:
1. The target exec file has "_" SMACK64 label and none SMACK64EXEC label
There are no differences by e419a0e. The process will run as SMACK_DEFAULT_PROCESS_LABEL subject.
2. The target exec file has "_" SMACK64 label and "foo" SMACK64EXEC label.
2.1. without e419a0e:
The child process(fork() from systemd) set its SMACK subject to SMACK_DEFAULT_PROCESS_LABEL. And the child executes the target file. On this time if SMACK_DEFAULT_PROCESS_LABEL has no rule for "foo" then the execution will be failed.
2.2. with e419a0e:
The child process(fork() from systemd) set its SMACK subject to "foo". And the child is able to execute the target file successfully.

**Comment by cschaufler** [comment]
The behavior as coded is correct. Please do not revert this change. Smack is not SELinux or AppArmor. It works differently, and that is intentional. The SMACK64EXEC behavior is not a "hidden" setting. If you can see the binary file you can see the attribute. Jobal, what problem does this cause?
