### ISSUE TITLE
Line-break support for systemd-boot (RFE-235)

### ISSUE THREAD

**Issue by t14462** [systemd/systemd#7325]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Antergos (Arch)

### In case of bug report: Expected behaviour you didn't see

> title	Antergos
> linux	/vmlinuz-linux
> initrd	/initramfs-linux.img
> options	root=UUID=8d9fc72f-af03-49c6-ab41-b6244d15ba95 rw quiet \\
>  zswap.enabled=1 \\
>  zswap.compressor=lz4 \\
>  zswap.max_pool_percent=34 \\
>  zswap.zpool=z3fold

(Line-break support, with \ before CR/LF)

**Comment by medhefgo** [comment]
I don't think this is necessary. It's undocumented, but using options multiple times will append to the cmdline.
