### ISSUE TITLE
Delegate= has no easy way to set a smaller list

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#7334]
I'm not sure if this is really a problem…, I'm throwing this out here for discussion.

If we have a unit with `Delegate=yes`, to override this, it is necessary to set `Delegate=no` first, and then `Delegate=a b c`. We *could* make it so that if Delegate=yes would be followed by a different Delegate= setting, we'd reset the list before the new assignment. Or we could just document current semantics.

**Comment by boucman** [comment]
I don't know... current semantic seems more consistent with the way systemd usually handle list-type parameters...

**Comment by yuwata** [comment]
As the other options that take lists accept empty string, I think `Delegate=` should also accept empty string, even though its effect is equivalent to `Delegate=no`.

**Comment by boucman** [comment]
yes, Delegates= is a list of controllers, and "yes" is an alias for "all the controllers" so "" become the usualy systemd way of emptying the list

that sounds consistant...

**Comment by yuwata** [comment]
OK. I will propose a patch for that.

**Comment by yuwata** [comment]
I've created PR #7336. Please take a look.

**Comment by yuwata** [comment]
Ah, I misunderstand the code. Assigning empty string has a special meaning now. For the consistency to other options, how about to introduce a new word, e.g. no-controller or something?
