### ISSUE TITLE
user@.service cannot start without a session

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#7339]
When logind registers a user session, it creates `/run/user/<uid>/`.
But when user@.service is started without a session having been created previously, we just set `$XDG_RUNTIME_DIR` from pam_systemd and do nothing else. User manager then fails because it cannot create `/run/user/<uid>/systemd/transient` (but would fail otherwise any, it's just the first thing).

We _could_ create the runtime directory, but then the question arises what the lifetime of user@.service is supposed to be.

My proposal:
- logind starts user@.service when asked too, and when user logs out, stops it unless the user has lingering enabled
- user@.service may be started without a session (and should work).
- let's also add a mechanism to start select user@.service instances during machine start. This would be an extension of lingering that'd allow such users to run "permanent" services under their account. But that's a bigger change, something that requires more discussion.

**Comment by poettering** [comment]
> let's also add a mechanism to start select user@.service instances during machine start. This would be an extension of lingering that'd allow such users to run "permanent" services under their account. But that's a bigger change, something that requires more discussion.

That's excatly "lingering" actually. We start user@.service right at boot for users that have lingering enabled.

**Comment by keszybz** [comment]
We do? OK, I was confused about that.

**Comment by poettering** [comment]
> user@.service may be started without a session (and should work).

So if user@.service is started outside of logind, then logind would allocate the user runtime structure for it, but if the user then logs in and out again, what do we do then? do we terminate the unit again? i.e. if you start user@.service outside of logind's lifecylce management, should logind take possession again as soon as it would start/stop it again?

**Comment by keszybz** [comment]
Yeah, I think so. Basically keep things as they are, but just allow user@.service to be started by hand.

**Comment by boucman** [comment]
how is lingering enabled ? would it be possible to mark user@.service as lingering if it si started manually, but mark it in /run so it disapears at reboot time ?

**Comment by yuwata** [comment]
~~It might be a different problem, but in my case, everything works fine by disabling SELinux on kernel command line.~~ Sorry, my comment seems to be a workaround of a completely unrelated problem.

**Comment by keszybz** [comment]
By creating a file in `/var/lib/systemd/linger`. Yes, adding `/run/systemd/linger` would be an option. But I'm not sure if that's better, in particular because it attaches some additional meaning to simply starting of a service. I'd prefer to keep things as simple as possible.
