### ISSUE TITLE
Service files get `no such file or directory` when they are symlinks

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#734]
I symlink things around in my home directory, but `systemctl --user enable foo.service` says it doesn't exist when it is a symlink in `~/.local/share/systemd/user/foo.service` (everything works if I manually symlink things). If I copy the contents into `foo2.service` as a real file, `systemctl --user enable foo2.service` works. Could symlinks be supported? Or at least the error message be made more useful if there's some problem with that?

**Comment by keszybz** [comment]
It's a long standing bug. https://bugs.freedesktop.org/show_bug.cgi?id=54560 and probably others. Let's not open another bug here.
