### ISSUE TITLE
Ending user session hangs the system

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#735]
When I leave my user session (using `systemctl --user start exit.target`), my session quits, but none of the TTYs work (or at least can be switched to). Is there a way to debug what is going on (SSH still works)?

**Comment by keszybz** [comment]
Can you run journalctl in the ssh session?

**Comment by mathstuf** [comment]
IIRC, the logs for the previous boot just…ended. Not sure if they didn't sync from the reset button being pressed or not. I'll test it out tonight.

**Comment by dvdhrm** [comment]
Please provide more information about your setup. What kind of session do you use? Graphical? Text? What exactly goes wrong _when_? How did you setup look like when everything worked? and so on..

**Comment by poettering** [comment]
Also: are you using kdbus and which version of systemd are you using?

**Comment by mathstuf** [comment]
I login from the TTY into XMonad (which starts automatically upon login since I've converted to `systemd --user`). Upon quitting, the screen goes blank and TTY switching doesn't work. When everything worked _perfectly_? I used `exec startx` and quitting took me back to the login prompt.

I don't have access to the machine right now, but it was up-to-date with Rawhide as of yesterday (modulo poppler and boost broken deps) running with the `-nodebug` kernel repository provided by the kernel maintainers.

**Comment by poettering** [comment]
@mathstuf so you use a session that is "upgraded" from tty mode to graphical mode? Yuck...

Your X process runs as part of the console session, but the WM you start in there is run as child for systemd --user?

Is your X running unprivileged (i.e. uses logind to get unprivileged access to its devices)?

**Comment by mathstuf** [comment]
Yes, TTY -> graphical. No need for a display manager, IMO :/ . Other than not needing to upgrade, does it do any other "magic"?

X is also started as a service, but it is still running as root (I'm guessing [this project](https://github.com/sofar/xorg-launch-helper) is no longer necessary?).

**Comment by dvdhrm** [comment]
Can you run `grep -r CONTROLLER /run/systemd/sessions` while X is running? Also, please show us the unit that starts Xorg.

This really sounds like a bug in your setup and you incorrectly shutdown Xorg.

**Comment by mathstuf** [comment]
Until I get home, here's the unit file:

``` systemd
[Unit]
Description=Xorg server launch helper
Before=xorg.target
Requires=x11-environment.target
Before=x11-environment.target

[Service]
Type=notify
ExecStart=/usr/bin/sh -c "%h/.local/bin/xorg-launch-helper %i -nolisten tcp -noreset vt1"
ExecStartPost=/usr/bin/systemctl --user set-environment DISPLAY=%i
ExecStop=/usr/bin/systemctl --user unset-environment DISPLAY
Restart=always
RestartSec=10

[Install]
WantedBy=xorg.target
```

**Comment by mathstuf** [comment]
There is no `CONTROLLER` output in `/run/systemd/sessions`. I'll try running X directly from the unit and get the journal output here soon.

**Comment by mathstuf** [comment]
OK, so running X directly (using `Type=simple`) makes race conditions between X starting and units with `Requires=xorg.target` because X may not be listening by the time it starts. Hence the `Type=notify` in the launch helper. However, when using it, exiting the session did work. So something is missing from `xorg-launch-helper`. Is there anything obvious missing?

**Comment by mathstuf** [comment]
I've converted X into starting with a socket unit and it quits properly now (and startup is not racy). Unfortunately, it drops to a shell upon quitting. I assume systemd is automatically starting `systemd --user` for me (I only see it in `xinitrc` locally). If so, how do I make it log me out after it quits?

**Comment by mathstuf** [comment]
Also, it seems things aren't quite right :/ . Pulseaudio is reporting only dummy devices, OpenGL can't seem to contact the hardware, and it seems I'm not considered part of the session. There's also no `CONTROLLER` in the session file still.

**Comment by mathstuf** [comment]
OK, things work now. I had missed putting `vt1` as an argument to X in the new units. Still running as root, but that can be looked at later.

**Comment by keszybz** [comment]
@mathstuf can you document your full setup for posteriority?

**Comment by mathstuf** [comment]
Files:
- `default.target.wants/x11-minimal.target`
- `x11-minimal.target.wants/xorg.target`

`xorg.target.wants/xorg@0.service`:

``` ini
[Unit]
Description=Xorg server for display %i
Before=xorg.target
Requires=x11-environment.target
Requires=xorg@%i.socket
After=xorg@%i.socket
Before=x11-environment.target

[Service]
Type=simple
SuccessExitStatus=0 1
# TODO: Fix the hard-coded vt number
ExecStart=/usr/bin/Xorg :%i -nolisten tcp -noreset -verbose 2 -keeptty vt1
ExecStartPost=/usr/bin/systemctl --user set-environment DISPLAY=:%i
ExecStopPost=/usr/bin/systemctl --user unset-environment DISPLAY

[Install]
WantedBy=xorg.target
```

`xorg@.socket`:

``` ini
[Unit]
Description=Xorg server socket for display %i

[Socket]
ListenStream=/tmp/.X11-unix/X%i
```

Files dropped in `x11-environment.target.wants` are all `Type=oneshot`, `RemainAfterExit=yes` services which call `systemctl --user set-environment` and `systemctl --user unset-environment`. Services which need specific ones use `After=` on the specific environment file. X-using units use `After=xorg.target` and `Requires=xorg.target`.

Services required for basic X usage (the window manager, xrdb loading, `setxkbmap` calls, etc.) are `WantedBy=x11-minimal.target` while higher-level services (`xmobar`, `dunst` (notification daemon), etc.) are `WantedBy=x11-standard.target`.

This still runs with X as root however. I haven't looked into why it doesn't drop permissions.

**Comment by mathstuf** [comment]
Also, no `CONTROLLER` in `/run/systemd/sessions/3`.

**Comment by mathstuf** [comment]
Well, here's why `CONTROLLER` is missing and X is root

```
(EE) systemd-logind: failed to get session: PID 27206 does not belong to any known session
```

**Comment by dvdhrm** [comment]
Yes, you cannot use Xorg + logind from within a user-unit. That's a known limitation of the Xorg implementation.

**Comment by mathstuf** [comment]
Seems that it is because of the "bash still runs on the TTY" problem. The `GetSessionByPID` returns an error for anything under the `systemd --user` tree. The login and bash processes at the top return a valid path.

```
root     27171  0.0  0.0  98464  4800 ?        Ss   Jul28   0:00   login -- boeckb
boeckb   27400  0.0  0.0 121932  5404 tty1     Ss+  Jul28   0:00     -bash
boeckb   27186  0.0  0.0  46004  5860 ?        Ss   Jul28   0:01   /usr/lib/systemd/systemd --user
boeckb   27189  0.0  0.0 126556  3020 ?        S    Jul28   0:00     (sd-pam)
root     27206  0.1  0.2 421556 40740 ?        Ssl  Jul28   3:49     /usr/libexec/Xorg :0 -nolisten tcp -noreset -verbose 2 -keeptty vt1
boeckb   27304  0.0  0.0  53868   572 ?        Ss   Jul28   0:00     ssh-agent
boeckb   27307  0.0  0.0 165688   512 ?        Ss   Jul28   0:02     gpg-agent --daemon --write-env-file
boeckb   27334  0.0  0.9 359892 153520 ?       Ss   Jul28   0:16     python3 -m uzbl.event_manager --server-socket /run/user/1000/uzbl/event/socket --pid-file /run/user/1000/uzbl/event/pid --log-file /dev/stderr --no-daemon start
boeckb   27339  0.0  0.0 167148 10904 ?        Ss   Jul28   0:18     /home/boeckb/.xmonad/xmonad-x86_64-linux --resume StackSet {current = Screen {workspace = Workspace {tag = "3", layout = "ModifiedLayout (AvoidStruts {avoidStrutsDirection = fromList [U,D,R,L], avoidStrutsRectCache = Just (fromList [U,D,R,L],Rectangl
boeckb    6235  0.0  0.0 182124 12800 ?        Ss   00:10   0:00       xmonadpropwrite _XMONAD_LOG_0
boeckb    6237  0.0  0.0 182124 12644 ?        Ss   00:10   0:00       xmonadpropwrite _XMONAD_LOG_1
boeckb   27342  0.0  0.0  18208  2660 ?        Ss   Jul28   0:19     /usr/bin/xautolock -detectsleep -noclose
boeckb   27347  0.0  0.0 293944 14112 ?        Ssl  Jul28   0:00     /usr/bin/dunst
boeckb   27370  0.0  0.0  62944  4556 ?        Ssl  Jul28   0:00     /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation
boeckb   27372  0.0  0.3 442140 51004 ?        Ssl  Jul28   0:01     /usr/bin/python3 /usr/bin/udiskie
boeckb   27399  0.0  0.1 221072 22904 ?        Ss   Jul28   1:23     /usr/bin/urxvt256cd --opendisplay
boeckb   27895  0.0  0.0 127932  2984 pts/0    Ss+  Jul28   0:00       tmux
boeckb   27652  0.1  0.0 480368 13828 ?        Sl   Jul28   3:15     /usr/bin/pulseaudio --start --log-target=syslog
boeckb   27898  0.1  0.0 137384 10476 ?        Ss   Jul28   3:59     tmux
boeckb   27905  0.0  0.0 151676 14132 pts/1    Ss   Jul28   0:00       -zsh
boeckb   25978  0.0  0.0 117564  3004 pts/1    S+   Jul29   0:00         /bin/sh /home/boeckb/.local/bin/stream-mpd mpd.dev.benboeckel.net:8080 mpd.ogg
boeckb   31375  1.6  1.1 639944 183320 pts/1   Sl+  08:17   0:21           mpv --cache-secs=1 http://mpd.dev.benboeckel.net:8080/mpd.ogg
boeckb   32641  0.3  0.0 156600 14952 pts/2    Ss   08:33   0:00       -zsh
boeckb     533  0.0  0.0 349928 15444 pts/2    S+   08:35   0:00         journalctl --user-unit=xorg@0.service -b
boeckb     534  0.0  0.0 114752  2392 pts/2    S+   08:35   0:00           less
boeckb     692  0.8  0.0 151688 14020 pts/4    Ss   08:38   0:00       -zsh
boeckb    1035  0.0  0.0 156408  4496 pts/4    R+   08:38   0:00         ps aux -H
boeckb   19090  0.0  0.0 383720  6372 ?        Sl   Jul28   0:00     /usr/libexec/gvfsd
boeckb   26160  0.1  0.1 278128 30448 ?        Ss   Jul29   1:17     /usr/bin/xmobar --screen=0 --add-command [ Run NamedXPropertyLog "_XMONAD_LOG_0" "_XMONAD_LOG" ]
boeckb   26162  0.1  0.1 278128 30512 ?        Ss   Jul29   1:18     /usr/bin/xmobar --screen=1 --add-command [ Run NamedXPropertyLog "_XMONAD_LOG_1" "_XMONAD_LOG" ]
boeckb   26525  0.0  0.0 262080  5512 ?        Sl   Jul29   0:00     /usr/libexec/at-spi-bus-launcher
boeckb   31273  7.1  3.3 1388408 549868 ?      Ssl  08:17   1:31     /usr/lib64/firefox/firefox
boeckb     913  0.1  0.0 417656  8640 ?        Sl   08:38   0:00     /usr/libexec/gvfs-udisks2-volume-monitor
boeckb     918  0.0  0.0 459856  6644 ?        Sl   08:38   0:00     /usr/libexec/gvfsd-trash --spawner :1.332 /org/gtk/gvfs/exec_spaw/0
```

**Comment by mathstuf** [comment]
@dvdhrm Hmm. Is there a tracking bug for that? Is it planned to be fixed?

**Comment by dvdhrm** [comment]
@mathstuf I don't think anyone is working on fixing Xorg. Besides, such development effort should be spent on fixing the wayland compositors, anyway. (IMO!)

**Comment by mathstuf** [comment]
OK. It's not like it's a regression for me (just a NTH). So far there hasn't been a WM implemented for Wayland that would allow me to switch comfortably (tiling, good multimonitor support with independent workspaces per monitor).

Though it is interesting that the entire `systemd --user` process tree is not considered part of my session…

**Comment by dvdhrm** [comment]
> OK. It's not like it's a regression for me (just a NTH). So far there hasn't been a WM implemented for Wayland that would allow me to switch comfortably (tiling, good multimonitor support with independent workspaces per monitor).

I know! A lot more developer effort is needed here. That's why I think we should really stop spending the effort on X11 ;)

> Though it is interesting that the entire systemd --user process tree is not considered part of my session…

`--user` runs **once** per user. However, each user might have multiple sessions running. It is not clear which session such units should belong to (they cannot belong to multiple sessions). Hence, they belong to none.

**Comment by mathstuf** [comment]
Hrm. That's unfortunate. That means I can't have a user unit for a daemon which listens on the system bus for `org.freedesktop.login1.Session` signals (namely `Lock` and `Unlock`) because it can't discover its session path.
