### ISSUE TITLE
logind wiki doc is wrong about "type" field, unaware that "wayland" is a graphical session

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#7351]
### Submission type

 - Bug report

### Bug report

https://www.freedesktop.org/wiki/Software/systemd/logind/

> Type encodes the session type. It's one of "unspecified" (for cron PAM sessions and suchlike), "tty" (for text logins) or "x11" (for graphical logins).

This is not true in practice: graphical logins can also have the type "wayland".  Presumably also "mir".

```
$ busctl get-property org.freedesktop.login1 /org/freedesktop/login1/session/_32 org.freedesktop.login1.Session Type
s "wayland"
```

The in-tree documentation for pam_systemd and sd_session_get_type() allows both "wayland" and "mir" as graphical session types.  Although I'm curious what information x11 v.s. wayland v.s. whatever is supposed to convey, that requires invalidating all docs and implementations (callers of logind shutdown/suspend methods) when a new display protocol is written.

---

(The `systemctl` code was equally unaware of this, which is what I first noticed and had wondered about for some time

https://github.com/systemd/systemd/blob/861f16d/src/systemctl/systemctl.c#L3420

Steps to reproduce: log in as two different users at the same time, on Fedora Workstation 26 (which defaults to Wayland).  `systemctl suspend` will act without warning, even though you didn't pass `--ignore-inhibitors`.  Unless there is a text console login by another user.)</small>

**Comment by poettering** [comment]
I updated the wiki now. Back than it made some sense to expose this, as the "Display" property was supposed to be a useful way to figure out the X11 display for a session. Somehow this is much less interesting today than it was back then, so maybe it wasn't a good idea to add that after all..

Anyway. Fixed the wiki. Closing.

**Comment by sourcejedi** [comment]
Thanks :).
