### ISSUE TITLE
networkd removes static default IPv6 route when RA expires

### ISSUE THREAD

**Issue by jkhsjdhjs** [systemd/systemd#7354]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> networkd not touching statically set routes.

### In case of bug report: Unexpected behaviour you saw

> networkd removes statically set route, leaving the system without IPv6 connectivity.

### In case of bug report: Steps to reproduce the problem

> Create a .network file in /etc/systemd/network, disable dhcp and set an IPv6 address and an IPv6 gateway. Restart networkd and wait till the router advertisement expires.

### Additional Information
>A workaround is to set IPv6AcceptRA=no in the [Network] section.
I found the same bug in the debian bugtracker, too: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867590

**Comment by ssahani** [comment]
Could you provide the debug mode logs showing the exact scenario. I am not able to reproduce it.

**Comment by jkhsjdhjs** [comment]
Yes, enabled debug logging and now waiting for it to remove the route.

EDIT: Here are the full logs since starting systemd-networkd: https://pastebin.com/nKnsDdPP
I'm currently waiting for it to remove the route again to see at which point exactly it happens.

EDIT2: I'm now quite sure that it happens when
`systemd-networkd[26870]: rtnl: received route without ifindex, ignoring` is printed to the logs.

**Comment by ssahani** [comment]
Sorry for late reply any idea who is adding this routes . This happens when we add routes via another tool such as iproute not via networkd and we add to foreign DB and we actually drop them when the interface goes down. I think that would be the situation there. Any Idea How  do I reproduce this ?

It seems the ifindex is not there  (Output interface index)

**Comment by jkhsjdhjs** [comment]
> any idea who is adding this routes

The routes should be added by networkd:

**/etc/systemd/network/eno2.network**
```
[Match]
Name=eno2

[Network]
Address=my-v4-address
Gateway=my-v4-gateway
Address=my-v6-address
Gateway=my-v6-gateway
```

I previously had `sys-apps/net-tools` installed too. I removed it now and the route is still being dropped.
But I noticed something else when running `journalctl -u systemd-networkd | grep 'rtnl'`:
`rtnl: received route without ifindex, ignoring` is first printed when I start networkd. It's printed again exactly 30 minutes later, when the route is removed.

Unfortunately I have no idea how to reproduce this.

EDIT: I guess it's happening 30 minutes afterswards because the router advertisement has a lifetime of 1800 seconds, see line 86 and 90 of [my paste](https://pastebin.com/nKnsDdPP).

**Comment by ssahani** [comment]
When this message
`Nov 18 05:31:36 my-hostname systemd-networkd[26279]: rtnl: received route without ifindex, ignoring`
networkd does not do anything

**Comment by jkhsjdhjs** [comment]
Is it possible that networkd removes the route because the router advertisement expires, receives a new route but ignores it because it has no interface index?

**Comment by ssahani** [comment]
> Is it possible that networkd removes the route because the router advertisement expires

  yes networkd removes them when ra expires. 

> receives a new route but ignores it because it has no interface index?

No when networkd receives a RA it sees which interface it received as networkd works  per interface basis. Then it goes ahead and add the interface number while adding the route. 


>Nov 18 05:31:36 my-hostname systemd-networkd[26279]: rtnl: received route without ifindex, ignoring

The path you talking is **NOT configured via networkd**

**Comment by jkhsjdhjs** [comment]
>>Is it possible that networkd removes the route because the router advertisement expires

>yes networkd removes them when ra expires.

Isn't exactly that the problem? That networkd removes the route because the RA expires, but the route is statically configured and shouldn't get removed?

**Comment by ssahani** [comment]
>Isn't exactly that the problem? That networkd removes the route because the RA expires, but the route is statically configured and shouldn't get removed?

NO NOT AT ALL. Please don't get confused. Why would networkd will remove the static routes when RA expired.    It only removes the routes which are expired that is received from RA.

**Comment by jkhsjdhjs** [comment]
>Why would networkd will remove the static routes when RA expired. It only removes the routes which are expired that is received from RA.

Yes, it should. But that's the problem I'm experiencing.

**Comment by ssahani** [comment]
No that does is not the case at all.

**Comment by yuwata** [comment]
Is this still reproducible with the current git master? If so, please provide a reproducer and debugging logs.
Also, if possible, please test PR #12971. Thank you.

**Comment by jkhsjdhjs** [comment]
Sorry, I don't have the server where I experienced this problem anymore and thus am unable to report whether this is still an issue or not.

**Comment by zoechi** [comment]
I seem to still experience this on a wlan interface on a Raspberry PI.
This doesn't happen on other machines with similar setup (Intel, AMD, wired network)

I should probably create a new issue but I'm still investigating...
