### ISSUE TITLE
nspawn: option to reuse an existing netns

### ISSUE THREAD

**Issue by alban** [systemd/systemd#7361]
### Submission type
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

git master

### Feature request

systemd-nspawn can either reuse the host netns or create a new netns with various configurations. But it does not have any option to reuse an existing netns configured externally.

```
--netns=/var/run/netns/foo
```

My use case is for netns configured by [CNI](https://github.com/containernetworking/cni). CNI is used by several software:
- [Kubernetes](https://github.com/kubernetes/kubernetes)
- [rkt](https://github.com/rkt/rkt)
- [kube-spawn](https://github.com/kinvolk/kube-spawn)
- and more, listed on its website

Currently, rkt normally prepares the netns with CNI and then exec `systemd-nspawn` **without** `--private-network` so that it stays in the prepared netns. But that makes things more difficult for rkt because systemd-nspawn wrongly assumes it is in the host netns and takes wrong assumptions when setting up `/etc/resolv.conf`.

If this feature `--netns=/var/run/netns/foo` is implemented, then code can be simplified in rkt. Also, I am about to write workarounds in kube-spawn for https://github.com/kinvolk/kube-spawn/issues/212 and that would be easier if this option existed.

/cc @iaguis @dongsupark @robertgzr @lucab

**Comment by poettering** [comment]
Makes sense. We want something similar for normal systemd units too, i figure.

That said, "/var/run"??? Is it 2001 or something, eh? ;-) That dir is called "/run" these days...

**Comment by tixxdz** [comment]
Actually yes we need this too in systemd, so I guess the code should be minimal and common, so maybe make it reusable ? in systemd it should work with "ip" tool.

Thanks!
