### ISSUE TITLE
tests fails when systemd.log-level=debug is specified on the kernel command line

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#7362]
```
41/247 hwdb-test                               FAIL     0.47 s
245/247 check-help-udevadm                      FAIL     0.03 s
```
`SYSTEMD_LOG_LEVEL=info ninja -C build test` works OK, so this is not too bad, but it'd be nice to fix at some point.

**Comment by ajeddeloh** [comment]
I think I've hit this as well on CoreOS (with systemd 235), but also with the log level set to debug in `/etc/systemd/system.conf`. I've determined it only happens on first boot, both when setting it via the config file and via the kernel command line. I'm using [Ignition](https://github.com/coreos/ignition) to write `/etc/systemd/system.conf` in the initramfs before `switch_root` occurs. Notably it appears that `systemd-journald` times out when starting.
