### ISSUE TITLE
libqrencode.so.4 not found in Arch mkosi image

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#7367]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> master (83123ab8fd)

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> I should be able to boot an mkosi-created image and test systemd inside it, including running `journalctl`.

### In case of bug report: Unexpected behaviour you saw

> journalctl: error while loading shared libraries: libqrencode.so.4: cannot open shared object file: No such file or directory

### In case of bug report: Steps to reproduce the problem

> ```bash
> mkosi --default .mkosi/mkosi.arch -ifT shell
> # inside the shell
> journalctl
> ```
> (Using mkosi master (systemd/mkosi@fb47b1ffa0), I don’t remember if the `shell` command was in the last release or if it’s newer.)

There is an Arch Linux package [qrencode](https://www.archlinux.org/packages/extra/x86_64/qrencode/), and it contains a `libqrencode.so.4` file, but I don’t seem to have it installed on my host system, so I’m not sure if adding it as a dependency in `mkosi.arch` is the correct solution – perhaps this is an optional feature that should be disabled at build time instead?

**Comment by agners** [comment]
I did notice that too. qrencode is installed at build time, so I would expect that it lands in dependencies.. However, I quickly removed it from there, and then the build failed, so there seems to be something off when qrencode is missing.

**Comment by poettering** [comment]
I figure the mkosi.arch file needs some updating to list the binary package too. After all, when systemd is built from scratch, how else would mkosi/pacstrap know that this built requires libqrencode...

(we usually get away with listing only an incomplete set of deps, as many deps are pulled in by the minimal system anyway, as that includes systemd anyway, but if that version is built without libqrencode, then we need to list explicitly)

A tested PR would be very welcome for this one

**Comment by agners** [comment]
Ok, so adding qrencode to the runtime package list.

Quickly tested the opposite, removing it from the list of packages to install during build. However, that failed:

    ...
    lctl@exe/src_journal_journal-qrcode.c.o' -c ../src/src/journal/journal-qrcode.c
    ../src/src/journal/journal-qrcode.c:21:10: fatal error: qrencode.h: No such file or directory
     #include <qrencode.h>
              ^~~~~~~~~~~~

Which is really weird, since qrencode is set to auto and should detect whether qrencode is installed....

During meson it seems to not really check for it:

    ...
    Library pam_misc found: YES
    Library gcrypt found: YES
    ...

And subsequently is listed in enabled features.

Whereas on my desktop (also ArchLinux)

    ...
    Library pam_misc found: YES
    Native dependency libmicrohttpd found: YES 0.9.55
    Native dependency libcryptsetup found: YES 1.7.5
    Native dependency libcurl found: YES 7.56.1
    Native dependency libidn found: YES 1.33
    Native dependency libiptc found: YES 1.6.1
    Dependency libqrencode found: NO
    Library gcrypt found: YES
    ...

It looks as if meson in the ArchLinux OS image does not properly check for dependencies.
