### ISSUE TITLE
pid1: stopping a unit will stop the units with Requires= on it

### ISSUE THREAD

**Issue by johnlinp** [systemd/systemd#7372]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v235

### Used distribution

Arch Linux

### In case of bug report: Steps to reproduce the problem

1. Create 2 service units:

```ini
# s1.service
[Service]
ExecStart=/bin/sleep 5566
```

```ini
# s2.service
[Unit]
Requires=s1.service

[Service]
ExecStart=/bin/sleep 7788
```

2. `systemctl start s2.service` starts both `s1.service` and `s2.service`

3. `systemctl stop s1.service` stops both `s1.service` and `s2.service`, but I was expecting that it only stops `s1.service`.

### Notes

The document doesn't mention such behavior. It seems that it is similar to `BindsTo=`, but there is a little difference:

- `Requires=`: only `systemctl stop s1.service` will stop `s1.service` and `s2.service`
- `BindsTo`: both `systemctl stop s1.service` and sending `SIGTERM` to the PID of `s1.service` will stop `s1.service` and `s2.service`

If this behavior is expected, I will update the document. If not, let's discuss how should we fix it. Thanks.

**Comment by arvidjaar** [comment]
> The document doesn't mention such behavior.

It does (`man systemd.unit`):

> If one of the other units gets deactivated or its activation fails, this unit will be deactivated.

**Comment by johnlinp** [comment]
Oops, I accidentally deleted the "gets deactivated" part in  #6869. I'll fix it. Sorry for the mistake.
