### ISSUE TITLE
journal/catalog hard codes /usr and /usr/local prefixes

### ISSUE THREAD

**Issue by egtvedt** [systemd/systemd#7374]
[0001-journal-catalog-add-lib-systemd-catalog-to-search-di.patch.gz](https://github.com/systemd/systemd/files/1481840/0001-journal-catalog-add-lib-systemd-catalog-to-search-di.patch.gz)
### Submission type
 - Bug report

### systemd version the issue has been seen with
v235

### Used distribution
Self built embedded Linux.

### In case of bug report: Expected behaviour you didn't see
I expected journalctl to be silent during boot, and at least not print to stderr.

### In case of bug report: Unexpected behaviour you saw
During boot, the following is printed on console:
[   13.896129] journalctl[619]: No items in catalog.

### In case of bug report: Steps to reproduce the problem
Configure systemd with prefix "/"

### Other information
Added a patch for appending /lib/systemd/catalog to search directories. Although, an improvement would be to use the configured PREFIX and have the pre-processor handle adding location directory,

**Comment by poettering** [comment]
Sorry, but this is simply not supported. We support exactly two build modes: either everything is placed in the /usr prefix ("merged-usr"), or most bits are placed in /usr and a few exceptions are placed in / ("split-usr"). We explicitly do not support anything else, in particular not using a prefix of /.

We should probably document that in a clearer way though.

**Comment by poettering** [comment]
Let's close this here. A setup with a prefix of / is not supported, and we now added the missing bits to the documentation to make this clear.

**Comment by egtvedt** [comment]
@poettering: thank you for the feedback. I will take up on your advice and switch over how I build systemd. I am happy with the clarification.
