### ISSUE TITLE
dhcp fails on intel ixgb 10G cards

### ISSUE THREAD

**Issue by jon-proulx** [systemd/systemd#7380]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see

> dhcpv4 configuration of interface

### In case of bug report: Unexpected behaviour you saw

dhcp client get correct address then drops it over and over

```
Oct 23 16:45:24 san-jose systemd[1]: Starting Network Service...
Oct 23 16:45:24 san-jose systemd-networkd[1217]: enp129s0f0: Gained IPv6LL
Oct 23 16:45:24 san-jose systemd-networkd[1217]: Enumeration completed
Oct 23 16:45:24 san-jose systemd[1]: Started Network Service.
Oct 23 16:45:25 san-jose systemd-networkd[1217]: enp129s0f0: Gained carrier
Oct 23 16:45:27 san-jose systemd-networkd[1217]: enp129s0f0: DHCPv4 address 10.30.3.94/24 via 12
Oct 23 16:45:27 san-jose systemd-networkd[1217]: Could not set hostname: The name org.freedesktop
Oct 23 16:45:27 san-jose systemd-networkd[1217]: enp129s0f0: Lost carrier
Oct 23 16:45:27 san-jose systemd-networkd[1217]: enp129s0f0: DHCP lease lost
Oct 23 16:45:29 san-jose systemd-networkd[1217]: enp129s0f0: Gained carrier
Oct 23 16:45:29 san-jose systemd-networkd[1217]: enp129s0f0: DHCPv4 address 10.30.3.94/24 via 12
Oct 23 16:45:29 san-jose systemd-networkd[1217]: Could not set hostname: The name org.freedesktop
Oct 23 16:45:29 san-jose systemd-networkd[1217]: enp129s0f0: Configured
Oct 23 16:45:30 san-jose systemd-networkd[1217]: enp129s0f0: Lost carrier
Oct 23 16:45:30 san-jose systemd-networkd[1217]: enp129s0f0: DHCP lease lost
...repeated forever
```
### In case of bug report: Steps to reproduce the problem

install intel x520 or x540 10G ethernet card ask ask networkd to use dhcp to configure:

```
root@san-jose:~# cat /run/systemd/network/10-netplan-enp129s0f0.network

[Match]
Name=enp129s0f0

[Network]
DHCP=yes

[DHCP]
UseMTU=true
RouteMetric=100
```

### additional information

isc-dhcpclient properly configure interface.

once configured by isc-dhcpclient network recognized config and  dhcpv6 address is then properly configured by networkd (from same dhcp server)

same networkd config  problerly configures integrated 1G NICs on same server as failed 10G NICs properly

**Comment by yuwata** [comment]
Seems related to #6593. What happen if disable `UseMTU=` option?

**Comment by jon-proulx** [comment]
Ah yes, that is what I am seeing.

**Comment by ssahani** [comment]
Could you please try with https://github.com/systemd/systemd/commit/9630068a33812606d295f1b2b02e48d12c3a2b08.

**Comment by keszybz** [comment]
Please try with the latest master.
