### ISSUE TITLE
hostnamed needs a quirk database for chassis type

### ISSUE THREAD

**Issue by afranke** [systemd/systemd#7390]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 233

### Used distribution

Fedora 27

### In case of bug report: Expected behaviour you didn't see

This machine should be detected as a tablet.

### In case of bug report: Unexpected behaviour you saw

This machine is detected as a server.

### In case of bug report: Steps to reproduce the problem

Type `hostnamectl` on a Microsoft Surface Pro (first generation).

**Comment by afranke** [comment]
CCing @hadess as requested.

**Comment by hadess** [comment]
Can you please attach the output of `dmidecode` run as root, as well as get the decompiled `DSDT.dsl` file:
```
# cat /sys/firmware/acpi/tables/DSDT > DSDT.bin
$ iasl -d DSDT.bin
```

**Comment by afranke** [comment]
Here you go.

[dmidecode.txt](https://github.com/systemd/systemd/files/1485937/dmidecode.txt)
[DSDT.zip](https://github.com/systemd/systemd/files/1485938/DSDT.zip)

Had to zip the file or Github wouldn’t accept it.

**Comment by hadess** [comment]
Shows up as a server in dmidecode, which is our preferred method of checking chassis type:

```
Handle 0x0003, DMI type 3, 22 bytes
Chassis Information
	Manufacturer: Microsoft Corporation
	Type: Main Server Chassis
	Lock: Not Present
	Version: 1
	Serial Number: 0
	Asset Tag: 0
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: None
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: 1
	Contained Elements: 0
	SKU Number: Surface_PRO_1
```

@poettering do we have a quirk file for chassis types?

**Comment by poettering** [comment]
@hadess not yet, but we should totally have one. This would not only mean adding a new hwdb file for this, but also making hostnamed actually check it. Patches very welcome, of course

**Comment by zdzichu** [comment]
@afranke, why not report the issue to the manufacturer to have it fixed?

**Comment by hadess** [comment]
> @afranke, why not report the issue to the manufacturer to have it fixed?

This half sounds like a troll.

1) it's Microsoft and they probably don't use this data, or have it correct in another bit of data such as ACPI or even somewhere in the registry
2) It's a Surface Pro 1, they're at Surface Pro 4, how likely are they to update its BIOS?

**Comment by boucman** [comment]
and to complete what @hadess said... even if they fix it the buggy hardware is around, and other manufacturers will probably ship hardware with bugs. having a database to deal with that will streamline the fixing process

**Comment by agx** [comment]
```$ gdbus introspect --system --dest org.freedesktop.hostname1  --object-path /org/freedesktop/hostname1 --only-properties
```

on the librem5 phone gives `''` as chassis type. Would that also be fixed via the hwdb or is there another way to preseed this for all devices already that i'm missing?

**Comment by poettering** [comment]
@agx you could provide an /etc/machine-info with the CHASSIS field set (maybe as a symlink to such a file in /usr, maybe created with tmpfiles.d' C or L, so that you are stateless, but htat's of course ugly. populating this via hwdb would be the much nicer and more correct approach. would love to review a PR for that.

**Comment by hadess** [comment]
> on the librem5 phone gives `''` as chassis type. Would that also be fixed via the hwdb or is there another way to preseed this for all devices already that i'm missing?

Might be worth looking at whether there would be a solution for overriding this for device-tree based machines. The hostnamed code looks in the DMI data, and in the ACPI if not available.

**Comment by agx** [comment]
@hadess the same probem occurs for 'regular' hwdb entries e.g. with `iio-sensor-proxy` properties as in https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/merge_requests/298 - there doesn't seem to be anything using DT, right? Is there any precedence in systems/udev that i missed?

**Comment by hadess** [comment]
> @hadess the same probem occurs for 'regular' hwdb entries e.g. with `iio-sensor-proxy` properties as in https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/merge_requests/298 - there doesn't seem to be anything using DT, right? Is there any precedence in systems/udev not using dmi/acpi that i missed?

They're not the same problem. If the device exists and is loaded, then there's a modalias that hwdb can be used to match against (which means you can export your quirk via hwdb).

The machine however doesn't have a "device" associated to it, unless `CONFIG_DMI_SYSFS` is available and it will populate that info in `/sys` (including a `modalias`, see `/sys/class/dmi/id/modalias`).

Which means you can't match against _machine_ information for DT machines, because it's not exported in `/sys`. There's nothing DMI specific in udev.

In both cases, you'll need to have that data exported from device tree and/or the kernel to `/sys` if you want udev to consume it.

**Comment by agx** [comment]
DT property that can be used https://github.com/devicetree-org/devicetree-specification/pull/45
