### ISSUE TITLE
`systemd-analyze --user plot` works incorrectly, producing arbitrarily wide SVGs.

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#740]
Start-up timestamp of a user instance (userspace_time in struct boot_times) actually may be arbitrarily big. This, because all timestamps are offset by that value, leads to creation of arbitrarily wide SVGs which almost completely consist of blank space.

One may reproduce this locally by restarting the user instance (on a machine with moderate uptime) and running `systemd-analyze --user plot > foo.svg`. I won't link an example SVG here as it may cause an OOM for somebody.

**Comment by EdiDD** [comment]
This still works incorrectly with `systemd-analyze plot > foo.svg`. Starts from firmware there is long nothing to kernel and services are cropped like there is not enough space left on the right side of image.
