### ISSUE TITLE
Mac address change is not getting reflected

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#7410]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with
systemd 232

### In case of bug report: Expected behaviour you didn't see
If I make the change in the network conf link section
for the MACAddress and restart the networkd then new
macaddress should be reflected..
> …

### In case of bug report: Unexpected behaviour you saw
 I didn't see the new MAC. in the out put of ip link or ifconfig. 
> …

### In case of bug report: Steps to reproduce the problem
1) Do the following change in  the network file.
[Match]
Name=eth0
[Link]
MACAddress=XX:XX:XX:XX:XX:XX
2) Restart the networkd
    systemctl restart systemd-networkd
> …

**Comment by ratagupt** [comment]
@poettering @ssahani :- Is it bug or RFE?

**Comment by ssahani** [comment]
apparently you have not brought down the interface. We need to `sudo ip link set dev <interface> down` to do that. Unfortunately networkd does not bring down the interface on it's own.

**Comment by ratagupt** [comment]
Yes same I am doing it but I was expecting that systemd should have taken care of that.Is there any plan where systemd-networkd can do this in future..

**Comment by ssahani** [comment]
I belive we have a rfe for this

**Comment by ratagupt** [comment]
Can you point that or mark it as RFE? seems it same as 6696

**Comment by ssahani** [comment]
yes duplicate of #6696

**Comment by keszybz** [comment]
Duplicate of #6696
