### ISSUE TITLE
systemctl: shutdown does not parse correctly -t option

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#7413]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v235
v232

### Used distribution

Debian sid
Downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882245

### In case of bug report: Expected behaviour you didn't see

Try to reboot the computer with:
``` # shutdown -h -t 5 now```

Shutdown should start immediatly, with a 5s delay before sending the kill
signal.

### In case of bug report: Unexpected behaviour you saw

A shutdown is planned in 5min, and "now" seems to be interpreted as the
message to send to users.

### In case of bug report: Steps to reproduce the problem

```Run shutdown -h -t 5 now```

This regression seems to be a result of https://github.com/systemd/systemd/commit/a4420f

**Comment by poettering** [comment]
Fix waiting in #7459
