### ISSUE TITLE
[machinectl] shell fails for some commands

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#7417]
### Submission type

- Bug Report

### systemd version the issue has been seen with

systemd 235
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

`machinectl shell "$CONTAINER_NAME" /bin/passwd -d root` 

should delete the password of the root user. But opposite happens. When I login into the machine manually it works fine.

### In case of bug report: Unexpected behaviour you saw

The root password will not get deleted as supposed to.

### In case of bug report: Steps to reproduce the problem

Bootstrap an ubuntu container with `debootstrap` (in this case ubuntu xenial 16.04.3).

I used the following command:
```
debootstrap --include dbus,vim,less,tmux,openssl,openssh-server,python xenial  /var/lib/machines/$CONTAINERNAME http://archive.ubuntu.com/ubuntu/ 
```

Then I add `pts/0` to `/etc/securetty/ in the container.
Then I start the machine via `machinectl start $CONTAINERNAME` and try to remove the root password via:
```
machinectl shell "$CONTAINER_NAME" /bin/passwd -d root
````

**Comment by michich** [comment]
Shouldn't it be /usr/bin/passwd instead of /bin/passwd?

**Comment by shibumi** [comment]
@michich 
Damn. You are right. Thanks. Closing this because of stupidity of the bug reporter :)
