### ISSUE TITLE
busctl introspect called on /org/freedesktop/login1 returns ENOENT

### ISSUE THREAD

**Issue by st3r4g** [systemd/systemd#7424]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 235

### Used distribution

> Arch Linux

The command:
`busctl introspect org.freedesktop.login1 /org/freedesktop/login1`
returns `No such file or directory`.
Invocation on other objects like `/org/freedesktop` or `/org/freedesktop/login1/session` works.
The `gdbus` command which invokes the same method works. 
I can reproduce it even booting the live ARCH_201711 iso on the same machine (but only booting in UEFI mode, BIOS mode works).

### Requirements to reproduce

After a discussion in the IRC channel, we came to the conculsion that a system booted with UEFI where `/sys/firmware/efi/efivars/OsIndicationsSupported-*` is missing is likely to be the cause.

**Comment by poettering** [comment]
Ah, thanks for tracking this one down. Fix waiting in #7446. PTAL
