### ISSUE TITLE
PR #7406 breaks systemd --user (assert)

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#7426]
### Submission type

 - Bug report

git master@ 0a5b5115b137698909257ef0e21d7f353a69daa7

### Used distribution

custom , arm, raspberry pi 3, kernel 4.14
```
Nov 23 01:08:56 rpi3 systemd[1]: systemd 235 running in system mode. (+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN default-hierarchy=unified)
```

### In case of bug report: Expected behaviour you didn't see

user units and sessions work

### In case of bug report: Unexpected behaviour you saw

`/usr/lib/systemd/systemd --user` asserts and coredumps

```
Nov 22 23:41:11 rpi3 systemd[1]: user@0.service: Got notification message from PID 298 (READY=1, STATUS=Reached basic.target.)
Nov 22 23:41:11 rpi3 systemd[298]: Assertion 'u' failed at ../../../src/systemd/src/core/unit.c:3770, function unit_active_or_pending(). Aborting.
Nov 22 23:41:11 rpi3 systemd[1]: user@0.service: Got notification message from PID 298 (STATUS=Startup finished in 51ms.)
Nov 22 23:41:11 rpi3 systemd[1]: Received SIGCHLD from PID 298 (systemd).
Nov 22 23:41:11 rpi3 systemd[1]: Child 298 (systemd) died (code=dumped, status=6/ABRT)
Nov 22 23:41:11 rpi3 systemd[1]: user@0.service: Child 298 belongs to user@0.service
```

### In case of bug report: Steps to reproduce the problem

Run `/usr/lib/systemd/systemd --user` from ssh
Run `systemctl --user` - returns `Failed to connect to bus`

### Possible cause:
Here:
https://github.com/systemd/systemd/commit/bfbcf21d75f103e639a7d18691b3f2a334b7e6f7#diff-ab78220e12703ee63fa1e6a2caa16bebR3546
https://github.com/systemd/systemd/commit/bfbcf21d75f103e639a7d18691b3f2a334b7e6f7#diff-ab78220e12703ee63fa1e6a2caa16bebR3551
https://github.com/systemd/systemd/commit/bfbcf21d75f103e639a7d18691b3f2a334b7e6f7#diff-ab78220e12703ee63fa1e6a2caa16bebR3555

The assert here
https://github.com/systemd/systemd/blob/master/src/core/unit.c#L3770
can now fire if manager_get_unit() can't find the target, which happens in my case.
I'm not sure which of the 3 calls to unit_active_or_pending() asserted, I had a stripped release build running when stumbled into this.

### Poor man's patch (fixes the issue for me)
```
diff --git a/src/core/manager.c b/src/core/manager.c
index 33d7aa1cb..0e21e14be 100644
--- a/src/core/manager.c
+++ b/src/core/manager.c
@@ -3543,16 +3543,16 @@ ManagerState manager_state(Manager *m) {

         /* Is the special shutdown target active or queued? If so, we are in shutdown state */
         u = manager_get_unit(m, SPECIAL_SHUTDOWN_TARGET);
-        if (unit_active_or_pending(u))
+        if (u && unit_active_or_pending(u))
                 return MANAGER_STOPPING;

         /* Are the rescue or emergency targets active or queued? If so we are in maintenance state */
         u = manager_get_unit(m, SPECIAL_RESCUE_TARGET);
-        if (unit_active_or_pending(u))
+        if (u && unit_active_or_pending(u))
                 return MANAGER_MAINTENANCE;

         u = manager_get_unit(m, SPECIAL_EMERGENCY_TARGET);
-        if (unit_active_or_pending(u))
+        if (u && unit_active_or_pending(u))
                 return MANAGER_MAINTENANCE;

         /* Are there any failed units? If so, we are in degraded mode */
```

**Comment by yuwata** [comment]
@asavah I've posted your patch as PR #7433. If you do not want to be mentioned as the author of the commit, then I will drop it. Thanks.

**Comment by asavah** [comment]
Thanks
