### ISSUE TITLE
meson: disabling option rpmmacrosdir does not work

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#7427]
### Submission type

 - Bug report

### systemd version the issue has been seen with

master@ 0a5b5115b137698909257ef0e21d7f353a69daa7

### Used distribution

cross-compiling on Ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see

specifiying `-Drpmmacrosdir=no` in meson options should disable installation of rpm macros (obvously not needed on non-rpm distros), as stated here https://github.com/systemd/systemd/blob/master/meson_options.txt#L129
Not a meson expert but I only can see this https://github.com/systemd/systemd/blob/master/meson.build#L97 and no special treatment for the "no" option value as is done for other cases such as eg. zsh completions.

### In case of bug report: Unexpected behaviour you saw

macros are installed to `/usr/no`
configuration summary reports
```
         PAM configuration dir:             /etc/pam.d
         RPM macros dir:                    /usr/no
         modprobe.d dir:                    /usr/lib/modprobe.d
```
### In case of bug report: Steps to reproduce the problem

Build systemd with -Drpmmacrosdir=no

**Comment by yuwata** [comment]
PR #7430 is created for this issue.
