### ISSUE TITLE
Cannot disable private network from nspawn settings file if private users are used

### ISSUE THREAD

**Issue by dato** [systemd/systemd#7429]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Debian testing (buster)

### In case of bug report: Expected behaviour you didn't see

> As per systemd-nspawn(1), it should be possible to override the default options used by the `systemd-nspawn@.service` template unit, without having to modify it.

#4395 was a very welcome addition, and it is now possible to use `-U` without a private network:

```
# systemd-nspawn -U --machine=debian9 ip a
<list of host interfaces visible>
```

However, because of [this early check](https://github.com/systemd/systemd/blob/v235/src/nspawn/nspawn.c#L1105-L1106) in `parse_argv()`, it is not possible to “undo“ the `--network-veth` option from the template file via a settings file like:

```
$ cat /etc/systemd/nspawn/debian9.nspawn
[Network]
Private=no
VirtualEthernet=no
```

This is because the `verify_arguments()` functions [checks for `MOUNT_APPLY_APIVFS_NETNS`](https://github.com/systemd/systemd/blob/c1719d8bc924ed59448616bd748671c5c7a66d93/src/nspawn/nspawn.c#L1216-L1220), and `load_settings()` does not revert the modification to `arg_mount_settings` upon encountering `Private=no`.

### In case of bug report: Unexpected behaviour you saw

> Using the above _debian9.nspawn_ file results in:

```
# systemd-nspawn --private-network -U --settings=override --machine=debian9 ip a
Invalid namespacing settings. Mounting sysfs with --private-users requires --private-network.
```

### In case of bug report: Steps to reproduce the problem

> Please let me know if the above snippets are not enough.

Many thanks for considering.

**Comment by lahwaacz** [comment]
Seems to work fine for me (systemd 246.2, Arch Linux).

**Comment by sfan5** [comment]
Works for me too on `systemd 248 (248.3-2-arch)` but just stumbled upon this on Ubuntu 18.04 which is still on systemd 237.
Sounds like this issue can be closed.
