### ISSUE TITLE
tmpfiles can't replace dirs by symlinks

### ISSUE THREAD

**Issue by mnhu** [systemd/systemd#7447]
### Submission type

Bug report

### systemd version the issue has been seen with

systemd 234
systemd 235

### Used distribution

Arch Linux
Yocto / Custom

### In case of bug report: Expected behaviour you didn't see

Use `systemd-tmpfiles` to create a symlink where a folder already exists. `man 5 tmpfiles.d` says:
```
       L, L+
           Create a symlink if it does not exist yet. If suffixed with + and a file or directory already exists
           where the symlink is to be created, it will be removed and be replaced by the symlink.
```

### In case of bug report: Unexpected behaviour you saw

```
systemd-tmpfiles --remove --create
```
fails with
```
symlink(/tmp/folder, /tmp/link) failed: Is a directory
```
 when configured with this line
```
L+ /tmp/link - - - - /tmp/folder
```

### In case of bug report: Steps to reproduce the problem

```
echo "L+ /tmp/link - - - - /tmp/folder" > /tmp/tmp.conf
mkdir /tmp/link
systemd-tmpfiles --create --remove /tmp/tmp.conf
```

### Further Info

The error message (`symlink(/tmp/folder, /tmp/link) failed: Is a directory`) is wrong. Running `strace systemd-tmpfiles --create --remove /tmp/tmp.conf` reveals that the error originates from `rename()`:
```
symlink("/tmp/folder", "/tmp/link")     = -1 EEXIST (File exists)
readlinkat(AT_FDCWD, "/tmp/link", 0x555aae1ccbd0, 99) = -1 EINVAL (Invalid argument)
getrandom("\x7b\x83\x5e\xf4\xb5\x47\x75\x96", 8, GRND_NONBLOCK) = 8
symlink("/tmp/folder", "/tmp/.#linkb738e54f5b745769") = 0
rename("/tmp/.#linkb738e54f5b745769", "/tmp/link") = -1 EISDIR (Is a directory)
unlink("/tmp/.#linkb738e54f5b745769")   = 0
```

The `rename()` is reached after the first attempt in `tmpfiles.c` fails and the "force-mode" then calls `symlink_atomic()` from https://github.com/systemd/systemd/blob/master/src/basic/fs-util.c#L386

According to `man 3 rename`, overwriting a directory with a (symlink) file is not an error:
```
EISDIR      The new argument points to a directory and the old argument points to a file that is not a directory.
```

**Comment by rsalveti** [comment]
There is already logic to remove the target path in case it is a directory, but the block that handles the removal logic is not yet checking for -EISDIR.

Patch below should cover this use case:
```
--- a/src/tmpfiles/tmpfiles.c
+++ b/src/tmpfiles/tmpfiles.c
@@ -1361,7 +1361,7 @@ static int create_item(Item *i) {
                                         r = symlink_atomic(resolved, i->path);
                                         mac_selinux_create_file_clear();

-                                        if (IN_SET(r, -EEXIST, -ENOTEMPTY)) {
+                                        if (IN_SET(r, -EISDIR, -EEXIST, -ENOTEMPTY)) {
                                                 r = rm_rf(i->path, REMOVE_ROOT|REMOVE_PHYSICAL);
                                                 if (r < 0)
                                                         return log_error_errno(r, "rm -fr %s failed: %m", i->path);
```

**Comment by yuwata** [comment]
@rsalveti Could you submit the patch as a PR?

**Comment by rsalveti** [comment]
@yuwata done!

**Comment by yuwata** [comment]
Thanks.
