### ISSUE TITLE
compilation is failing under Fedora Rawhide x86_64

### ISSUE THREAD

**Issue by fredericlepied** [systemd/systemd#7470]
### Submission type

 - Bug report

### systemd version the issue has been seen with
master branch after commit a0a7ba659842c5ec96fa2b128ba4cc3d70900e0c

> …

### Used distribution

Fedora Rawhide x86_64

> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

Compilation is failing on calendarspec.c

FAILED: src/basic/basic@sta/calendarspec.c.o 
cc  -Isrc/basic/basic@sta -Isrc/basic -I../src/basic -I. -I../ -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-network -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-device -I../src/libsystemd/sd-bus -Isrc/core -I../src/core -Isrc/libudev -I../src/libudev -Isrc/udev -I../src/udev -Isrc/login -I../src/login -Isrc/timesync -I../src/timesync -Isrc/resolve -I../src/resolve -Isrc/journal -I../src/journal -Isrc/systemd -I../src/systemd -Isrc/shared -I../src/shared -I/usr/include/blkid -I/usr/include/uuid -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong -fPIE --param=ssp-buffer-size=4 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -ffunction-sections -fdata-sections -include config.h -O2 -g -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fPIC -pthread -MMD -MQ 'src/basic/basic@sta/calendarspec.c.o' -MF 'src/basic/basic@sta/calendarspec.c.o.d' -o 'src/basic/basic@sta/calendarspec.c.o' -c ../src/basic/calendarspec.c
In file included from ../src/basic/missing.h:1274:0,
                 from ../src/basic/util.h:47,
                 from ../src/basic/calendarspec.h:29,
                 from ../src/basic/calendarspec.c:33:
../src/basic/missing_syscall.h:65:19: error: static declaration of 'memfd_create' follows non-static declaration
 static inline int memfd_create(const char *name, unsigned int flags) {
                   ^~~~~~~~~~~~
In file included from /usr/include/bits/mman.h:45:0,
                 from /usr/include/sys/mman.h:41,
                 from ../src/basic/calendarspec.c:29:
/usr/include/bits/mman-linux.h:125:5: note: previous declaration of 'memfd_create' was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~

Commit https://github.com/systemd/systemd/commit/a0a7ba659842c5ec96fa2b128ba4cc3d70900e0c caused this regression. See full log at http://38.145.33.116/systemd-master/a0/a7/a0a7ba659842c5ec96fa2b128ba4cc3d70900e0c_57d0af03/build.log.gz

**Comment by yuwata** [comment]
Already fix is waiting in PR #7468.

**Comment by yuwata** [comment]
#7468 is merged.
