### ISSUE TITLE
Add new mouse to HWDB (Logitech MX Master 2S)

### ISSUE THREAD

**Issue by arigit** [systemd/systemd#7477]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> … (master)

### Used distribution

> Fedora 27

This is a request to add a new mouse device to the hardware database
I checked https://github.com/systemd/systemd/blob/master/hwdb/70-mouse.hwdb
and there is no entry for it.

Similar and with reference to #3947, @whot 
From: evemu-record

Input device name: "Logitech MX Master 2S"
Input device ID: bus 0x03 vendor 0x46d product 0x4069 version 0x111

From: solaar show
  Device path  : /dev/hidraw2
  USB id       : 046d:c52b
  Protocol     : HID++ 4.5
  Polling rate : 8 ms (125Hz)

DPI is selectable (up to 4000) but defaults to 1000, same as for the older "MX Master".  In the MX Master entry, I suspect the MOUSE_DPI line is wrong (guessing it should be 1000@125, same as for MX Master 2s)

For MX Master 2S, the following applies:

MOUSE_WHEEL_CLICK_ANGLE=15
MOUSE_WHEEL_CLICK_ANGLE_HORIZONTAL=26
MOUSE_WHEEL_CLICK_COUNT=24
MOUSE_WHEEL_CLICK_COUNT_HORIZONTAL=14

**Comment by poettering** [comment]
Any chance you can submit this new addition as proper PR, that we can just merge? That way the addition is properly attributed to you and your name will show up in the release notes and everything!

cc @whot.

**Comment by arigit** [comment]
PR submitted

**Comment by whot** [comment]
Closed via #7487, thanks
