### ISSUE TITLE
systemctl status says unit is disabled when it is enabled

### ISSUE THREAD

**Issue by marcosfrm** [systemd/systemd#7485]
`logrotate.timer` is enabled by default in Arch's package by a symlink:

```
lrwxrwxrwx 1 root root 18 Jul  1 05:47 /usr/lib/systemd/system/timers.target.wants/logrotate.timer -> ../logrotate.timer
```

(no entry in `/etc`)

But `systemctl status` says it is disabled:

```
                                                            vvvvvvvv
* logrotate.timer - Daily rotation of log files
   Loaded: loaded (/usr/lib/systemd/system/logrotate.timer; disabled; vendor preset: disabled)
   Active: active (waiting) since Mon 2017-11-27 14:00:10 -02; 46min ago
  Trigger: Tue 2017-11-28 00:00:00 -02; 9h left
     Docs: man:logrotate(8)
           man:logrotate.conf(5)

Nov 27 14:00:10 arch systemd[1]: Started Daily rotation of log files.
```

When enabled via a symlink in `/etc`, it works as expected:

```
lrwxrwxrwx 1 root root 36 Sep 25 07:26 /etc/systemd/system/timers.target.wants/fstrim.timer -> /usr/lib/systemd/system/fstrim.timer

                                                         vvvvvvv
* fstrim.timer - Discard unused blocks once a week
   Loaded: loaded (/usr/lib/systemd/system/fstrim.timer; enabled; vendor preset: disabled)
   Active: active (waiting) since Mon 2017-11-27 14:00:10 -02; 47min ago
  Trigger: Mon 2017-12-04 00:00:00 -02; 6 days left
     Docs: man:fstrim

Nov 27 14:00:10 arch systemd[1]: Started Discard unused blocks once a week.
```

Arch Linux, systemd 235.

**Comment by poettering** [comment]
what does "systemctl is-enabled fstrim.timer" return?

**Comment by marcosfrm** [comment]
```
$ systemctl is-enabled logrotate.timer
disabled

$ systemctl is-enabled fstrim.timer
enabled
```

The problem is `logrotate.timer`. It is active and was not started by hand. I suppose it is enabled by the symlink in `/usr`.

**Comment by poettering** [comment]
can you paste the precise definition of logrotate.timer? i.e. "systemctl cat logrotate.timer"?

**Comment by marcosfrm** [comment]
```
$ systemctl cat logrotate.timer 
# /usr/lib/systemd/system/logrotate.timer
[Unit]
Description=Daily rotation of log files
Documentation=man:logrotate(8) man:logrotate.conf(5)

[Timer]
OnCalendar=daily
AccuracySec=12h
Persistent=true

[Install]
WantedBy=timers.target
```

**Comment by poettering** [comment]
ah, well, so the unit file should drop its [Install] section if it is enabled statically anyway. As long as that's listed but not actually applied the logic will currently say it's not enabled..

**Comment by marcosfrm** [comment]
But [Install] section is useful if user wants to mask it, no?

BTW, this does not look right:

```
# systemctl mask logrotate.timer 
Created symlink /etc/systemd/system/logrotate.timer -> /dev/null.

$ systemctl status logrotate.timer 
* logrotate.timer
   Loaded: masked (/dev/null; bad)
   Active: failed (Result: resources)
  Trigger: n/a

Nov 27 14:00:10 arch systemd[1]: Started Daily rotation of log files.
Nov 27 16:12:02 arch systemd[1]: logrotate.timer: Unit to trigger vanished.
Nov 27 16:12:02 arch systemd[1]: logrotate.timer: Failed with result 'resources'.

```

**Comment by marcosfrm** [comment]
> But [Install] section is useful if user wants to mask it, no?

Nevermind. systemctl mask does not need [Install]. I will ask Arch folks if they can drop the [Install] section.

**Comment by keszybz** [comment]
Looking at this again, I think current behaviour is wrong. The unit is linked into the target that the [Install] section says it should be linked into. The user doesn't need to care if the symlink is in /etc/ or /usr/lib, either way the effect is identical. I think that the correct rule would be that if all the symlinks specified by the [Install] section are present, we should say that the unit is enabled.

**Comment by marcosfrm** [comment]
@keszybz  Any news?

It is still very confusing.

**Comment by dtardon** [comment]
This seems to work now.
