### ISSUE TITLE
doc: add document for strjoin and strjoina

### ISSUE THREAD

**Issue by johnlinp** [systemd/systemd#7488]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

v235

### Description

At first sight, I did't realize the character "a" in `strjoina()` stands for `alloca()`. I had to look into the code to understand this. Before that, I used `strjoina()` with a `_cleanup_free_` pointer and caused a coredump.

Adding a paragraph to explain the usage/purpose of `strjoin()` and `strjoina()` and the difference between them would really help.

If adding documents in such util functions is acceptable, I will submit a pull request for that. Thanks.

**Comment by keszybz** [comment]
Sure, it is acceptable. It could be in the .h header or in the .c implementation of the function, and you could even add it to CODING_STYLE along with some guidelines where to use each (e.g. alloca should not be used in loops and on unbounded input).

**Comment by keszybz** [comment]
I don't think we need an issue open for this. In general, it's always good to add internal docs for any function, and comments in the .c or .h files. `strjoin` and `strjoina` are not special in this regard. Feel free to submit a PR at any time.
