### ISSUE TITLE
systemd-cgtop can report impossible CPU usage values if cpuacct.usage goes down

### ISSUE THREAD

**Issue by charles-dyfis-net** [systemd/systemd#749]
It is possible for `cpuacct.usage` for a cgroup to go down over time; when this happens, systemd-cgtop can report impossibly large values for CPU used.

```
22:16:49.979231338 systemd-cgtop < read res=12 data=16405214312.
22:17:20.000312480 systemd-cgtop < read res=10 data=781274824.
22:17:20.018068235 systemd-cgtop < write res=248 data=/system.slice/REDACTED.service    1 61445968456.7     8.8M        -        -.
```

61445968456.7% CPU usage is not a reasonable value.

**Comment by poettering** [comment]
how would that happen? Because somebody explicitly resets them? Or what are you saying with this?

**Comment by charles-dyfis-net** [comment]
I have no idea how it happens -- but it is happening, with significant
frequency, in my QA lab.

There's certainly no user intent to perform a reset; I can check for writes
to sysfs files, and will also keep an eye on processes exiting and the like.
