### ISSUE TITLE
SPDX: remove verbose license texts

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#7491]
Now that we already have SPDX headers almost anywhere:

What about stripping the license texts itself?

Seems projects like U-Boot also [went that route](https://lists.denx.de/pipermail/u-boot/2013-July/158480.html)

> Note: From the legal point of view, this patch is supposed to be only
> a change to the textual representation of the license information,
> but in no way any change to the actual license terms. With this patch
> applied, all files will still be licensed under the same terms they
> were before. 

Of course, copyright lines need to be preserved, but we'd get rid of all the redundant information.

The linux kernel also seems to aim at stripping the license texts eventually. Of course, special care needs to be taken to ensure the license text really matches the license refered to in SPDX. (see https://lwn.net/Articles/739183/)

/cc @zbyszek

**Comment by keszybz** [comment]
I'm +1 in general, but I'd prefer to wait until after the release.

**Comment by yuwata** [comment]
Should this be in v237 milestone?

**Comment by flokli** [comment]
I'd say yes. I could open a PR stripping the license texts, but this might have to be rebased very often until merged if new files appear, so lets hear some other opinions first.

**Comment by poettering** [comment]
11a15892230011c331d4e31cdbbd58e8b3dfe4af made this change. Closing.
