### ISSUE TITLE
Make translate systemd easier.

### ISSUE THREAD

**Issue by s8321414** [systemd/systemd#75]
And where can I translate systemd?

**Comment by keszybz** [comment]
See .po files in https://github.com/systemd/systemd/tree/master/po . You can submit pull requests for existing languages and/or add new translations.

**Comment by s8321414** [comment]
Just those .po to translate?But where is their .pot?

**Comment by arvidjaar** [comment]
There are also catalog files for journal messages: https://github.com/systemd/systemd/tree/master/catalog

**Comment by s8321414** [comment]
Someone may want to list all files can be translated :smile:

**Comment by keszybz** [comment]
Well, that's it: .po and the catalog. To get the .pot file:

```
make -C po systemd.pot
```

From that you create po/&lt;lang&gt;.po.

The catalog file does not require any preparation. catalog/systemd.catalog is the source, and you simply create catalog/systemd.&lt;lang&gt;.catalog. See http://www.freedesktop.org/wiki/Software/systemd/catalog/ for a description of the format, or simply look at one of the other translations for inspiration.

**Comment by s8321414** [comment]
OK, thank you!

**Comment by s8321414** [comment]
hmmm, where should I run <code>make -C po systemd.pot</code>?
I run it in the systemd directroy,but it says "make: **\* No rule to make target 'systemd.pot'.  Stop."

**Comment by keszybz** [comment]
On Sun, Jun 07, 2015 at 04:01:23PM -0700, Jeff Huang wrote:

> hmmm, where should I run <code>make -C po systemd.pot</code>?
> I run it in the systemd directroy,but it says "make: **\* No rule to make target 'systemd.pot'.  Stop."

You need to run configure first. Try:
  ./autogen.sh c

After that, 'make -C po systemd.pot' works for me.

**Comment by piotrdrag** [comment]
You can also use GNOME's site to get the POT file: https://l10n.gnome.org/module/systemd/

**Comment by s8321414** [comment]
OK, thank you again!
