### ISSUE TITLE
systemd-nspawn refusing to run just a static binary

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#750]
My use case is run a single statically build golang binary in a container. Is this even possible?

I've tried many things but I keep getting a variation of:

```
Directory /tmp lacks the binary to execute or doesn't look like a binary tree. Refusing.
```

As discussed on https://bbs.archlinux.org/viewtopic.php?id=199995 & my log here: http://ix.io/jXV

That static binary can be built from https://github.com/kaihendry/dc

**Comment by poettering** [comment]
Well, nspawn requires a /usr/bin/ subdir to exist in an OS tree, just as a safety check, to avoid mistakes.

**Comment by kaihendry** [comment]
There is a /usr/bin created by `pacstrap -idc /tmp/dc filesystem`. Where exactly should the static binary reside?

**Comment by poettering** [comment]
I think you just forgot the "-D" on the nspawn cmdline, no?

**Comment by kaihendry** [comment]
```
X1C3:/tmp$ sudo systemd-nspawn -D /tmp/dc
Spawning container dc on /tmp/dc.
Press ^] three times within 1s to kill container.
Timezone Asia/Singapore does not exist in container, not updating container timezone.
execv() failed: No such file or directory
Container dc failed with error code 1.
```

I tried intuitive things like running the static binary /tmp/dc/dc like so `sudo systemd-nspawn -D /tmp/dc/ /tmp/dc/dc`, but then I get `Directory /tmp/dc lacks the binary to execute or doesn't look like a binary tree. Refusing.` again.

**Comment by poettering** [comment]
On Mon, 27.07.15 18:11, Kai Hendry (notifications@github.com) wrote:

> ```
> X1C3:/tmp$ sudo systemd-nspawn -D /tmp/dc
> Spawning container dc on /tmp/dc.
> Press ^] three times within 1s to kill container.
> Timezone Asia/Singapore does not exist in container, not updating container timezone.
> execv() failed: No such file or directory
> Container dc failed with error code 1.
> ```

Well, if you just specify "-D /tmp/dc", then this will invoke a binary
/bin/sh below /tmp/dc (i.e. the full path from the host will be
/tmp/dc/bin/sh.

> I tried intuitive things like running the static binary /tmp/dc/dc
> like so `sudo systemd-nspawn -D /tmp/dc/ /tmp/dc/dc`, but then I get
> `Directory /tmp/dc lacks the binary to execute or doesn't look like
> a binary tree. Refusing.` again.

If the full path is /tmp/dc/dc, then "systemd-nspawn -D /tmp/dc /dc"
should work?

Lennart

## 

Lennart Poettering, Red Hat

**Comment by kaihendry** [comment]
Ah, that works!! http://s.natalian.org/2015-07-28/systemd-nspawn.png

Thank you! Now I need to blog this. :) Update: I illustrate the steps in https://github.com/kaihendry/dc/blob/master/Makefile

Now sure how to get logs out. I.e. the stdout log.

```
 No journal files were found.
 Failed to get journal fields: Cannot assign requested address
```

**Comment by poettering** [comment]
Shell redirection should just work.
