### ISSUE TITLE
journald aborts with an assert

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#7501]
### Submission type

 - Bug report
 
### systemd version the issue has been seen with

git master v235-635-g3235b4e70

### Used distribution

Debian sid

### In case of bug report: Expected behaviour you didn't see

journald not aborting.

### In case of bug report: Unexpected behaviour you saw

```

Nov 29 13:39:33 pluto systemd-journald[269]: Assertion 'n + N_IOVEC_META_FIELDS + (pid_is_valid(object_pid) ? N_IOVEC_OBJECT_FIELDS : 0) + client_context_extra_fields_n_iovec(c) <= m' failed ../src/journal/journald-server.c:773, function dispatch_message_real(). Aborting.
Nov 29 13:39:33 pluto systemd[1]: systemd-journald.service: Service has no hold-off time, scheduling restart.
Nov 29 13:39:33 pluto systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
Nov 29 13:39:33 pluto systemd[1]: Stopped Flush Journal to Persistent Storage.
Nov 29 13:39:33 pluto systemd[1]: Stopping Flush Journal to Persistent Storage...
Nov 29 13:39:33 pluto systemd[1]: Stopped Journal Service.
Nov 29 13:39:33 pluto systemd[1]: Starting Journal Service...
Nov 29 13:39:33 pluto systemd-journald[2440]: Journal started
Nov 29 13:39:33 pluto systemd-journald[2440]: System journal (/var/log/journal/567a68a5c2672114bcf5192d00000008) is 581.0M, max 500.0M, 0B free.
Nov 29 13:39:33 pluto systemd[1515]: Started GNOME Terminal Server.
Nov 29 13:39:33 pluto systemd[1]: Started Journal Service.
Nov 29 13:39:33 pluto systemd[1]: systemd-journald.service: Main process exited, code=killed, status=6/ABRT
Nov 29 13:39:33 pluto systemd[1]: systemd-journald.service: Failed with result 'signal'.
Nov 29 13:39:33 pluto systemd[1]: Starting Flush Journal to Persistent Storage...
Nov 29 13:39:33 pluto systemd[1]: Started Flush Journal to Persistent Storage.
```
### In case of bug report: Steps to reproduce the problem

I'm not sure how to trigger this, but I checked that my journal files are ok according to ```journalctl --verify```

**Comment by evverx** [comment]
If the default values of `RateLimitInterval` and `RateLimitBurst` are used, that `assert` can be triggered by generating more than 1000 messages in 30 seconds with the following command:
```sh
systemd-run yes
```
The issue seems to have been fixed in https://github.com/systemd/systemd/pull/7500.

**Comment by poettering** [comment]
Can you test with #7500 please? I think that should fix everything?

**Comment by mbiebl** [comment]
@evverx, @poettering : the journald crash is gone after pulling the changes in #7500 
But there still seems to be a regression compared to v235. 
This is with v235:
```
Nov 29 20:10:51 pluto systemd-journald[26393]: Suppressed 4499764 messages from run-r73aef5eb7df847df961a1031c2e5d1e2.service
```
This is with git master
```
Nov 29 20:07:32 pluto systemd-journald[18804]: N_DROPPED=5256047
```
All the details are now missing.
Should I file a separate bug report for that?

**Comment by poettering** [comment]
uh, yes, that's a separate issue. Please file a separate one. And let's close this one, given than #7500 fixed it.
