### ISSUE TITLE
Add parameter to `systemctl edit` that creates drop-in file but let's the user start from existing file.

### ISSUE THREAD

**Issue by jmehne** [systemd/systemd#7502]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

Calling `systemctl edit <service>` creates a drop-in called `override.conf` and opens an empty editor, if the file doesn't exist yet. Considering that the simplest use case is overriding a single setting in the service file, it would be convenient to pre-populate the editor with the whole service file to make it easier to make a small change.

I know I can do a similar thing with `edit --full`, create the drop-in directory manually and copy the service file to the drop-in directory, but it would be nice to have a shortcut.

**Comment by YHNdnzj** [comment]
Implemented in https://github.com/systemd/systemd/commit/85c5d313b5c92115f5c77663e736bcf21e99f02f
