### ISSUE TITLE
MemorySwapMax is unknown to systemd-run on unified hierarchy

### ISSUE THREAD

**Issue by cdown** [systemd/systemd#7505]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> CentOS, but also reproduces on Arch Linux

### Steps to reproduce the problem

systemd-run generally works and will set memory limits, but MemorySwapMax is unknown, despite being in systemd.resource-control.

As you can see this works with MemoryMax, and MemorySwapMax is there:
```
% systemd-run -p 'MemoryMax=100M' sleep 120
Running as unit: run-raf285fa0610248dcbf12a19bab8d9f94.service
% cat /sys/fs/cgroup/system.slice/run-raf285fa0610248dcbf12a19bab8d9f94.service/memory.swap.max
max
```

If we try to do this with MemorySwapMax, though:

```
% systemd-run -p 'MemorySwapMax=100M' sleep 120
Unknown assignment MemorySwapMax=100M.
Failed to create bus message: Invalid argument
```

**Comment by poettering** [comment]
Fix waiting in #7444
