### ISSUE TITLE
tmpfiles shouldn't ignore symlinks, but change permission of the link itself

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#7509]
### Submission type
 - Bug report

### systemd version the issue has been seen with
> systemd 235 and [HEAD](https://github.com/systemd/systemd/blob/224b0e7ad0116579f830b7dd387b97c3facb65d9/src/tmpfiles/tmpfiles.c#L672-L673)

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> The manpage for `tmpfiles.d` state: `Recursively set the access mode, group and user, and restore the SELinux security context of a file or directory if it exists, as well as of its subdirectories and the files contained therein (if applicable). Lines of this type accept shell-style globs in place of normal path names. Does not follow symlinks. `
> I would expect `systemd-tmpfiles` to change the permission of the link itself.

### In case of bug report: Unexpected behaviour you saw

> `systemd-tmpfiles` did not change the permissions of the symlinks.

### In case of bug report: Steps to reproduce the problem

> Use the `systemd-tmpfiles` `z` flag on a symlink and you will see it does nothing.
> Removing [this](https://github.com/systemd/systemd/blob/224b0e7ad0116579f830b7dd387b97c3facb65d9/src/tmpfiles/tmpfiles.c#L672-L673) two lines of code, should be enough to fix the issue.

See also:
> Hm, does "does not follow symlinks" mean that we adjust the context/mode/ownership of the symlink itself, or that we refuse to look at the file? I'd think that the former is more useful, but it seems that we implement the latter.
https://github.com/systemd/systemd/issues/4097#issuecomment-249837492

**Comment by poettering** [comment]
hmm, mode is not defined for symlinks, no?

but yeah, the idea is that we operate on the specified objects themselves, and if that's a symlink, that we operate on the symlink.

Given that you already have a patch that is already mostly there, pleas submit it as PR, that way it'll get properly attributed to you and everything!

**Comment by klausenbusk** [comment]
> hmm, mode is not defined for symlinks, no?

Oh, yeh correct. I'm mostly interesting in changing the owner.

> Given that you already have a patch that is already mostly there, pleas submit it as PR, that way it'll get properly attributed to you and everything!

I will :)

**Comment by poettering** [comment]
Fix waiting in #7964.

**Comment by klausenbusk** [comment]
Thanks @poettering :)
