### ISSUE TITLE
ubuntu-ci please request arm64 builds too now

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#7514]
@martinpitt arm64 virtual machines are now available in the ubuntu-ci, please start requesting arm64 triggers too.

I'm not sure how it is all configured =) hopefully this is an ok way to request this.

**Comment by poettering** [comment]
Oh! That's lovely, having arm64 CI would be excellent indeed, as it would be our second non-x86 arch only!

**Comment by martinpitt** [comment]
Before we generally add a webhook for that, let's do a first single test run. I triggered one in PR #7512 (@keszybz , @poettering: If you want to do that too, see https://www.freedesktop.org/wiki/Software/systemd/autopkgtest/ ). I'll be AFK until next Wednesday.

**Comment by martinpitt** [comment]
And nice to see that xenial-amd64 works again, too! I'm not sure if we should move that to artful too. I. e. if we want more diversity vs. not want too much variance.

**Comment by martinpitt** [comment]
FTR, arm64 upstream queue does not yet seem to be processed, @xnox or Iain need to sort that out first.

**Comment by martinpitt** [comment]
Cool, it works! https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful-pitti-systemd-semaphore/artful/arm64/s/systemd-upstream/20171205_225733_53263@/log.gz

@xnox: As the Ubuntu CI cloud is already low on capacity, does  it actually have enough resources to sustain the extra load of running a magnitude of 30x 2 hours systemd upstream tests on arm64?

**Comment by xnox** [comment]
We are planning to have more arm64 capacity available soon.

**Comment by poettering** [comment]
any update on this one? @xnox @martinpitt ?

**Comment by xnox** [comment]
@poettering i believe it is safe to enable arm64. Looking at internal only stats, it is mostly idle and very spiky, the drop-off rates for amd64/arm64 are about the same, with arm64 lately a lot quicker than amd64. Plus if we do exceed our quotas there is the capacity to ask for more quota. Unlike in 2017, we do have per-architecture quotas now. Please enable arm64 tests and I will monitor how it goes.

**Comment by xnox** [comment]
Also, I guess I should finish up fixing ppc64el and s390x tests upstream, to test on those too. If not already, as those have plenty of capacity.

**Comment by martinpitt** [comment]
Thanks @xnox - let's see how it goes then. I [manually triggered](https://www.freedesktop.org/wiki/Software/systemd/autopkgtest/) an arm64 test on PR #10501 , if that becomes green, I'm happy to add a webhook for it.

**Comment by martinpitt** [comment]
It [succeeded](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/arm64/s/systemd-upstream/20181024_175214_0abe5@/log.gz,) nice!

I added a webhook for it. Please let me know if it acts up, then we can investigate and disable it again.

**Comment by martinpitt** [comment]
@evverx : Expected yes, as that's exactly what we've [told it to do](https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/control#L127) - i. e. right now we only run the tests with QEMU on amd64, all other architectures only run the nspawn tests. But when I wrote that, there was no qemu for arm, arm64, or s390x, and even i386 had some problems with systemd's tests. I'm fine with giving this another try, of course!

The [Ubuntu package](https://git.launchpad.net/ubuntu/+source/systemd/tree/debian/tests/control?h=applied/ubuntu/devel#n137) enables a lot more architectures. As the downstream distro gating tests run on the exact same infrastructure, I suppose these are working well enough.

I [enabled](https://salsa.debian.org/systemd-team/systemd/commit/7c79f66f8f0) these now. @evverx , @keszybz , @poettering: If this causes failures/regressions on some architectures, I'm happy to revert (fully or by-architecture), please just yell. (Note that I'm on PTO until next Monday, but @mbiebl can hopefully help, too).

**Comment by evverx** [comment]
I've just turned off the webhook running the tests on arm64 in https://github.com/systemd/systemd/issues/11195. Ideally it would be great to fix https://github.com/systemd/systemd/issues/11104 or skip just that one test but it's unlikely to happen anytime soon I guess.
