### ISSUE TITLE
`systemctl -M … status …` maps process name in `Main PID` to .host

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#7516]
### Submission type
 - Bug report

### systemd version the issue has been seen with

> 232 on Debian 9/stretch
> git/master b39367a1a732ead630345e2cb77a10e8c61bd9b1 on Gentoo

### Used distribution

> Debian 9/stretch
> Gentoo

### In case of bug report: Expected behaviour you didn't see

> `systemctl -M ${machine} status some.service` showing the name of the process within the machine as `Main PID`

### In case of bug report: Unexpected behaviour you saw

> `systemctl -M ${machine} status salt-minion.service` shows as `Main PID` the process name on `.host` instead of what's running inside the machine:
**Seen:**  `Main PID: 22 (ksoftirqd/2)`
**Should be:** `Main PID: 22 (salt-minion)`

### In case of bug report: Steps to reproduce the problem

> Start a systemd-nspawn based machine
> Execute `systemctl -M ${machine} status some.service`
> Check the `Main PID` entry and it's process name

**Comment by poettering** [comment]
urks

**Comment by poettering** [comment]
"Fix" waiting in #7518
