### ISSUE TITLE
systemd-resolved logs all mDNS packets as "Got mDNS UDP packet on unknown scope. Ignoring."

### ISSUE THREAD

**Issue by blsz** [systemd/systemd#7527]
### Submission type

 - Bug report

### systemd version the issue has been seen with
533

### Used distribution
gentoo

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

systemd 233-r6 on a gentoo Gnome desktop reports thousands of journal messages of the type

`systemd-resolved[31705]: Got mDNS UDP packet on unknown scope. Ignoring.`

Based on the output of `tcpdump -i enp2s0 -s0 -vv net 224.0.0.0/4`,  there appears to be an exact correlation between the messages and mDNS UDP packets from other Linux and MacOS devices to "> 224.0.0.251.mdns".  For example

`11:52:09.674941 IP (tos 0x0, ttl 255, id 25683, offset 0, flags [none], proto UDP (17), length 68)
    foo.mdns > 224.0.0.251.mdns: [udp sum ok] 0 PTR (QM)? _googlecast._tcp.local. (40)`

No other multicast packets recorded by the above tcpdump command produce this message.  Avahi daemon is not running locally.

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
Fix waiting in #7551
