### ISSUE TITLE
systemd-journal-gatewayd - does not return proper json format 

### ISSUE THREAD

**Issue by oknozor** [systemd/systemd#7536]
### Submission type

 - Bug report

### systemd version the issue has been seen with

 - 235.38-2 

### Used distribution

 - ArchLinux 

### In case of bug report: Expected behaviour you didn't see

```systemd-journal-gatewayd.service``` does respond with properly formated json. 

### In case of bug report: Unexpected behaviour you saw

I get "Syntax error"  when querying json from http://$myhost/entries?$param with the ```Accept: application/json``` header. 

### In case of bug report: Steps to reproduce the problem

 1. start the service :  ```systemctl start systemd-journal-gatewayd.service```
 1. query for any ***entry*** in a web browser/Postman :  

```
Accept: application/json
GET: http://localhost/entries?_SYSTEMD_UNIT=systemd-journald.service
```

**Comment by keszybz** [comment]
Hmm, this seems to work for me. What command are you using to retrieve? What command are you using to verify json? Please paste some of the invalid output that you get.

**Comment by oknozor** [comment]
Here is my resquest : ```GET: http://localhost/entries?_SYSTEMD_UNIT=systemd-journald.service```

#### Standard output format : 
```
    Oct 29 18:14:44 gomu systemd-journald[192]: Journal started
    Oct 29 18:14:44 gomu systemd-journald[192]: Runtime journal (/run/log/journal
    /a1a6c4eafd854b3ebb5c9f6e1af17f81) is 8.0M, max 796.8M, 788.8M free.
```
no problem here. 

#### Json formated outpout : 

1. with curl (raw output) : 
```
curl --silent -H'Accept: application/json' \
'http://localhost:19531/entries?_SYSTEMD_UNIT=systemd-journald.service' 
```

```
{ "__CURSOR" : "s=843ae59e69524ef1b68e9faa6d51f2fd;i=2a6;b=0aee6e7708c14d1b8025759c60e18d20;          m=17b7c1;t=55cb2a87d810d;x=5e3b3dec75322bbf", "__REALTIME_TIMESTAMP" : "1509297284284685", "__MONOTONIC_TIMESTAMP" : "1554369", "_BOOT_ID" : "0aee6e7708c14d1b8025759c60e18d20", "PRIORITY" : "6", "_MACHINE_ID" : "a1a6c4eafd854b3ebb5c9f6e1af17f81", "_HOSTNAME" : "*********", "SYSLOG_FACILITY" : "3", "SYSLOG_IDENTIFIER" : "systemd-journald", "_TRANSPORT" : "driver", "MESSAGE_ID" : "f77379a8490b408bbe5f6940505a777b", "MESSAGE" : "Journal started", "_PID" : "192", "_UID" : "0", "_GID" : "0", "_COMM" : "systemd-journal", "_EXE" : "/usr/lib/systemd/systemd-journald", "_CMDLINE" : "/usr/lib/systemd/systemd-journald", "_CAP_EFFECTIVE" : "25402800cf", "_SYSTEMD_CGROUP" : "/system.slice/systemd-journald.service", "_SYSTEMD_UNIT" : "systemd-journald.service", "_SYSTEMD_SLICE" : "system.slice", "_SYSTEMD_INVOCATION_ID" : "a8cd780888674a0ab62872afb8a9d401" }
{ "__CURSOR" : "s=843ae59e69524ef1b68e9faa6d51f2fd;i=2a7;b=0aee6e7708c14d1b8025759c60e18d20;m=17b866;t=55cb2a87d81b3;x=a6fa098a86d6eb8a", "__REALTIME_TIMESTAMP" : "1509297284284851", "__MONOTONIC_TIMESTAMP" : "1554534", "_BOOT_ID" : "0aee6e7708c14d1b8025759c60e18d20", "PRIORITY" : "6", "_MACHINE_ID" : "a1a6c4eafd854b3ebb5c9f6e1af17f81", "_HOSTNAME" : "*******", "SYSLOG_FACILITY" : "3", "SYSLOG_IDENTIFIER" : "systemd-journald", "_TRANSPORT" : "driver", "_PID" : "192", "_UID" : "0", "_GID" : "0", "_COMM" : "systemd-journal", "_EXE" : "/usr/lib/systemd/systemd-journald", "_CMDLINE" : "/usr/lib/systemd/systemd-journald", "_CAP_EFFECTIVE" : "25402800cf", "_SYSTEMD_CGROUP" : "/system.slice/systemd-journald.service", "_SYSTEMD_UNIT" : "systemd-journald.service", "_SYSTEMD_SLICE" : "system.slice", "_SYSTEMD_INVOCATION_ID" : "a8cd780888674a0ab62872afb8a9d401", "MESSAGE_ID" : "ec387f577b844b8fa948f33cad9a75e6", "MESSAGE" : "Runtime journal (/run/log/journal/a1a6c4eafd854b3ebb5c9f6e1af17f81) is 8.0M, max 796.8M, 788.8M free.", "JOURNAL_NAME" : "Runtime journal", "JOURNAL_PATH" : "/run/log/journal/a1a6c4eafd854b3ebb5c9f6e1af17f81", "CURRENT_USE" : "8388608", "CURRENT_USE_PRETTY" : "8.0M", "MAX_USE" : "835510272", "MAX_USE_PRETTY" : "796.8M", "DISK_KEEP_FREE" : "1253265408", "DISK_KEEP_FREE_PRETTY" : "1.1G", "DISK_AVAILABLE" : "8346677248", "DISK_AVAILABLE_PRETTY" : "7.7G", "LIMIT" : "835510272", "LIMIT_PRETTY" : "796.8M", "AVAILABLE" : "827121664", "AVAILABLE_PRETTY" : "788.8M" }
```

2. trying to read the json output in  postman (or trying to deserialize the output into an object) :

```Syntax error```

The only url that returns proper Json is ```/machine```, that's because it returns a single json object. 
Since the other urls returns multiple json objects without storing them in an array, they are not readable as json. 

I guess the output shall be an array of comma separated objects as described here http://json.org/ 

Like so : 

```
{
    "content": [
        {
             "key1"  : value1, 
             "key2"  : value2
        }, 
        {
             "key1"  : value3, 
             "key2"  : value4
        }, 
    ]
}
```

**Comment by poettering** [comment]
uh, well. we had so many discussions about whether the json journal output should output a single json object or a stream of json objects, and which one is more correct. Thing is, people don't agree on that. Given the stream character of the output I am pretty sure the stream makes more sense however...

**Comment by oknozor** [comment]
It makes sense indeed. Actually i am trying to build a web application on top of gatewayd i guess i'll have to figure out how to work with the stream :).
