### ISSUE TITLE
No systemd-nspawn usage documentation

### ISSUE THREAD

**Issue by waleedsaud** [systemd/systemd#7537]
There is no docs that introduce how to use systemd-nspawn  and related tools in details.

Is there any intro docs?

**Comment by yuwata** [comment]
See the example section in systemd-nspawn(1). Is it not enough?

**Comment by waleedsaud** [comment]
Hi Yuwata,
The man pages is not clear way for starters like me .
the guide that I am looking for is like zeromq guide  http://zguide.zeromq.org/page:all .

**Comment by keszybz** [comment]
We provide abundant reference documentation, but introductory guides are outside of the scope of the upstream project. Not saying that they are not useful — but this is not the right place to request them.
