### ISSUE TITLE
systemd should load binfmt_misc

### ISSUE THREAD

**Issue by thomasmey** [systemd/systemd#7541]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> …

### Used distribution
Fedora 26

> …

### In case of bug report: Expected behaviour you didn't see

It looks like some of the generators are bash scripts but run before systemd-modules-load.service

systemd should load binfmt_misc to make the generators work correctly.

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

**Comment by boucman** [comment]
what is your use-case ?

**Comment by poettering** [comment]
I think is is a misunderstanding what binfmt_misc is for: it is not necessary to make the she-bang stuff work, i.e. shell scripts with their `#!/bin/sh` line work anyway, and do not need binfmt_misc at all. binfmt_misc is only necessary to make more exotic stuff work, that does not use she-bangs.

**Comment by thomasmey** [comment]
Sorry I meant BINFMT_SCRIPT

**Comment by poettering** [comment]
we don't support systems where that is not compiled in. Sorry.
