### ISSUE TITLE
Do not set `net.ipv4.conf.default.*` (`all.*` is sufficient)

### ISSUE THREAD

**Issue by hvenev** [systemd/systemd#7546]
### systemd version the issue has been seen with

> master

### In case of bug report: Expected behaviour you didn't see

> All real network interfaces have the same value for `promote_secondaries`

### In case of bug report: Unexpected behaviour you saw

> Interfaces that are created before running `sysctl` (usually `lo`, but in my case also ethernet) have `promote_secondaries = 0` (the kernel's default value), whereas those that were initialized later (in my case wireless and tunnels) have `promote_secondaries = 1` (the value in `default`).

### In case of bug report: Steps to reproduce the problem

> Check the value of `net.ipv4.conf.lo.promote_secondaries`

Setting `net.ipv4.conf.default.promote_secondaries` is only affects devices probed after setting it. It also (I think) does not lead to any change in behavior because the kernel seems to be doing the following:

- When a device is created, its `promote_secondaries` is set to `default.promote_secondaries`.

- When deciding whether to promote a secondary address, check the device's `promote_secondaries` and `all.promote_secondaries` is set. If any of them is set, do it.

Systemd sets `all.promote_secondaries` and this is enough (and always works).

The same is true for `rp_filter` and `accept_source_route` - the value stored by systemd in `all` overrides the kernel's default, but the device's specific value can be copied before or after systemd sets `default`, so some interfaces have the old value and some have the new one.

**Comment by poettering** [comment]
cc @mvo5

**Comment by poettering** [comment]
@hvenev any chance you can prep a patch for this?

**Comment by mvo5** [comment]
I have no strong opinion but the request (and the PR) LGTM.

**Comment by yuwata** [comment]
PR #7547 is merged. Let's close this.
