### ISSUE TITLE
RFE: Rename systemd to sysd

### ISSUE THREAD

**Issue by eMPee584** [systemd/systemd#7556]
[systemd 235-3 on Debian GNU/Linux buster/sid]
The name sysd would be 42% (!) shorter, and even is not yet taken by another software project.
Real world case: Sometimes (like in fatrace output) systemd processes' names get truncated.

**Comment by smlb** [comment]
```
alias sysd="systemd"
```

**Comment by aledomu** [comment]
@smlb That doesn't solve the problem that he points about ftrace. Maybe I would go farther and say "sd" except for PID1, which I would leave as-is.

**Comment by poettering** [comment]
I am sorry, but it's too late for that really, the package is too established. Also, it's a bit of a bikeshedding thing, no?

Sorry!

**Comment by eMPee584** [comment]
Fair enough, I wasn't actually being very serious, it's just that all the systemd commands are really chatty to type which has both advantages (clearness of intent) & disadvantages (mo' typin ^^).
Just now I stumbled upon @lzap's work: https://github.com/lzap/systemd-shortcuts#motivation
Maybe this can be officially integrated & shipped with systemd?

**Comment by lzap** [comment]
I can create Fedora packages, there is no need of integrating this into core systemd git I think. Happy New Year!

**Comment by eMPee584** [comment]
but seriously haha, the commands could have been a lot more efficient to type with a sharper base name. This might forever be wasting a lot of keystrokes in the entire future history of computing.
