### ISSUE TITLE
Brightness value not preserved across boots

### ISSUE THREAD

**Issue by P-reducible** [systemd/systemd#757]
I use Gentoo, and they just pushed in a systemd update two days ago.  Problem is: now my screen brightness gets reset to its max every time the system is rebooted.

I'm a little suspicious of the message I got after the update finished:
- Messages for package sys-apps/systemd-218-r3:
-   CONFIG_DEVPTS_MULTIPLE_INSTANCES:   is not set when it should be.
-   CONFIG_FW_LOADER_USER_HELPER:       should not be set. But it is.
- Please check to make sure these options are set correctly.
- Failure to do so may cause unexpected problems.

I complied and changed the kernel settings as requested.  Related or not, this is when the problem started.

**Comment by johannbg** [comment]
This is probably a bug in backlight.c hence it would be good to know which one of those module triggers this and if there is difference in the saved brightness value if there is one or more file residing in the /var/lib/systemd/backlight/ directory after the module has been enabled.

**Comment by P-reducible** [comment]
Jóhann,

I tried changing the two options back (in various combinations), but the problem persisted.  Don't know if this is relevant, but the kernel I'm using is v.3.16.5.

/var/lib/systemd/backlight/ has two files: pci-0000:00:02.0:backlight:acpi_video0, which is several months old, and pci-0000:00:02.0:backlight:intel_backlight which is timestamped with today's date.

**Comment by johannbg** [comment]
Did the kernel get updated ( or something else ) at the same time systemd did? Do both those files contain the same brightness value? ( if not try echoing the correct value in both those file and reboot to see if the brightness value is retained

**Comment by P-reducible** [comment]
1. First, I updated systemd (via emerge --update --deep --with-bdeps=y --newuse world), then tweaked the two kernel settings (see above).
2. pci-0000:00:02.0:backlight:acpi_video0 has the value of 5.

pci-0000:00:02.0:backlight:intel_backlight has the value of 1054.

Should I delete one of these files?

EDIT: at my own (huge) risk, I got rid of the file that had the value of 5 in it, but nothing has changed. The brightness level is being reset to max upon restart anyway.

Please advise further.

**Comment by poettering** [comment]
Do you have multiple GPUs in your system, or only intel?

if you play around with /sys/class/backlight/*/brightness, does everything work correctly? Are all changes you make by echoing into that file applied correctly? How do the two backlight devices interact for you? do both control the screen's brightness correctly?

**Comment by P-reducible** [comment]
Lennart, -

The only graphics card I have is the Intel one.

Echoing into /sys/class/backlight/intel_backlight/brightness works fine within each boot. 

"intel_backlight" is the only subdir in /sys/class/backlight/.  That, to me, means that I've only got one backlight.  That backlight is controlled (correctly, it seems) by GNOME through its brightness control slider.  After the recent systemd update, the slider is always at the rightmost position, INITIALLY.

Do the answers make sense? - Thx 4 your follow up!

**Comment by poettering** [comment]
If you do "systemctl stop systemd-backlight@backlight:intel_backlight.service", then change the brightness, and then issue "systemctl start" on that unit again, does it restore the brightness then?

**Comment by P-reducible** [comment]
The brightness DOES get restored.

PS  Two things seem odd.  The text consoles have the same brightness, no matter what, and the GNOME brightness control does not move to the old position after the daemon gets restarted.

**Comment by poettering** [comment]
I have the suspicion that this is more a kernel problem than a systemd problem gievn the console behaviour you see...

Do you have /var split off or something?

If you do "systemctl status" on the backlight service after boot, do you see it started cleanly?

**Comment by P-reducible** [comment]
You were exactly right. I bumped the kernel from v.3.16.5 to 3.18.16, and the problem vanished. 

I'd request that you guys keep supporting kernel version 3.18 and up for now, if at all possible. V.4 is a bit rough - not all the proprietary driver junk has been updated - I, personally, couldn't get my wireless driver to load.

Thanks for your help!

**Comment by poettering** [comment]
We currently require at least 3.8, and that's probably going to stay that way for a while. That said, driver bugs are driver bugs... By running such an old kernel you will get buggier drivers...
