### ISSUE TITLE
Systemd user script "After=" not working…

### ISSUE THREAD

**Issue by ne0zer0** [systemd/systemd#7577]
- Bug report

### systemd version the issue has been seen with
>235-3

Question: Where can I find which is the latest version of systemd???

### Used distribution
>Debian Sid

### In case of bug report: Expected behaviour you didn't see

> Start user scripts with "After=" option, for suspend, or hibernate, etc…

### In case of bug report: Unexpected behaviour you saw

> Nothing happen…

### In case of bug report: Steps to reproduce the problem

> Tried to write user scripts, like this:

`[Unit]`
`Description=My service`
`After=suspend.target`
`After=sleep.target`
`After=hybrid-sleep.target`
`[Service]`
`ExecStart=/bin/systemctl --user restart other.service`
`[Install]`
`WantedBy=suspend.target`
`WantedBy=sleep.target`
`WantedBy=hybrid-sleep.target`

> Then enter this in a terminal: `systemctl --user enable myservice.service; systemctl start --user myservice.service`.

> Suspend the machine, Resume and nothing happen…

**Comment by poettering** [comment]
This is a bug and RFE tracker, not a support forum. Please contact the systemd mailing list or some other support forum for help if you just have questions. Thank you for understanding.
