### ISSUE TITLE
usage example in man page sd_journal_wait is wrong: duplicate entries

### ISSUE THREAD

**Issue by ibotty** [systemd/systemd#7578]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd-234-9.fc27.x86_64
but applicable to newer versions.

### Used distribution

fedora

### Expected behaviour you didn't see

The example in the man page sd_journal_wait seems wrong. For the following sequence of library calls I get a record twice:
 * sd_journal_next == 1
 * sd_journal_reset_data
 * sd_journal_get_data
 * sd_journal_next == 0
 * sd_journal_wait == APPEND
 * sd_journal_reset_data
 * sd_journal_get_data

When advancing the pointer to the next entry  after `sd_journal_wait` (with `APPEND`) and before `sd_journal_get_data`, I don't get duplicate entries. I could not produce a log stream where I missed an entry, but of course I cannot rule that out.

 * sd_journal_next == 1
 * sd_journal_reset_data
 * sd_journal_get_data
 * sd_journal_next == 0
 * sd_journal_wait == APPEND
 * sd_journal_next == 1
 * sd_journal_reset_data
 * sd_journal_get_data

So in short: is the manpage example missing that part? (Or one could move the block that with sd_journal_get_data inside an else clause).

For clarity below the example from the man page:
```c
#include <stdio.h>
#include <string.h>
#include <systemd/sd-journal.h>

int main(int argc, char *argv[]) {
  int r;
  sd_journal *j;
  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  if (r < 0) {
    fprintf(stderr, "Failed to open journal: %s\n", strerror(-r));
    return 1;
  }
  for (;;)  {
    const void *d;
    size_t l;
    r = sd_journal_next(j);
    if (r < 0) {
      fprintf(stderr, "Failed to iterate to next entry: %s\n", strerror(-r));
      break;
    }
    if (r == 0) {
      /* Reached the end, let's wait for changes, and try again */
      r = sd_journal_wait(j, (uint64_t) -1);
      if (r < 0) {
        fprintf(stderr, "Failed to wait for changes: %s\n", strerror(-r));
        break;
      }
      continue;
    }
    r = sd_journal_get_data(j, "MESSAGE", &d, &l);
    if (r < 0) {
      fprintf(stderr, "Failed to read message field: %s\n", strerror(-r));
      continue;
    }
    printf("%.*s\n", (int) l, (const char*) d);
  }
  sd_journal_close(j);
  return 0;
}
```

**Comment by keszybz** [comment]
I cannot reproduce the error. (On F28, but I don't think it matters.)

How exactly are you running the examples? How are you generating the journal files?

**Comment by ibotty** [comment]
I was running the example with the rust bindings. I don't have a C repro, but I can reproduce without any problems (running fedora 27 though) using rust.

The program can be found in

https://github.com/ibotty/rust-tail-journald/tree/bug-7578-repro

It uses the following branch (which reintroduced the behavior)
https://github.com/ibotty/rust-systemd/tree/bug-7578-repro

You can run the program (having rust installed) with `cargo run` within rust-tail-journald's sources.

**Comment by ibotty** [comment]
BTW: the fix for that behavior can be seen at
 https://github.com/ibotty/rust-systemd/commit/69d1021a07abefb1f20a10a97876ec46b22fb236

And you might want to `grep -v sd_journal_enumerate_data` because that spams the logs.

I might read the C program in the man page wrong, but the documented behavior surely _is_ missing the seek to the new record (as you should see in the trace).

**Comment by ibotty** [comment]
Another note: I trigger the behavior when calling (in my user shell) `logger bug7578-a; sleep 1; logger bug7578-b`.

**Comment by keszybz** [comment]
After a seek that returns 0, the cursor is at "end", so when the new data comes in, no additonal seek should be necessary.

OTOH, journalctl.c does a seek after every `output_journal()`.

I extraced the example from the man page into a separate file (I'll file a PR later). Can you check if you can reproduce the issue with https://github.com/keszybz/systemd/blob/e10761f1c257c46a06600fa4f00dbe772ad28d58/man/journal-iterate-wait.c?

**Comment by keszybz** [comment]
Closing because of lack of response. Please reopen if you can still reproduce the issue (esp. with the extracted program.)

**Comment by ygoe** [comment]
I've also seen this bug. Did the same sequence as the original reporter. I added moving to the next record and that resolved it. Seems like the manpage is indeed wrong.
