### ISSUE TITLE
systemd-boot fails to boot on a Raspberry Pi 3 using U-Boot's UEFI emulation

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#7585]
### Submission type

 - Bug report

### systemd version the issue has been seen with

235

### Used distribution

Debian buster (arm64)

### In case of bug report: Expected behaviour you didn't see

Hi!

I realize that this is probably the very definition of a corner case, but I am currently trying to get systemd-boot to work on a Raspberry Pi 3 using U-Boots UEFI emulation (see [0] for the official documentation and [1-3] for more detailed information). The Raspberry Pi 3 boots from the first MBR partition of a Micro-SD card which must contain a FAT file system with a few special files [4]. Here's what I currently have on that partition:

```
alexander@shepard:/media/alexander/D950-263B$ find -type f | sort | xargs md5sum 
633fdb5ca4824d095d9a33f1fae721f1  ./6122fd6adb744a5eb1f262b2f20628af/4.13.0-1-arm64/initrd
451845468f21e42d4a3bbee35ccb4b59  ./6122fd6adb744a5eb1f262b2f20628af/4.13.0-1-arm64/linux
fd01b240fcc5d4c83560676415081508  ./bootcode.bin
bd076be31a9a652866eb6faa85c91c0c  ./broadcom/bcm2837-rpi-3-b.dtb
bc0f7ef1e86679fa87f6d116575d8a8e  ./config.txt
fbeac908054b0ec7a8bcc9a6ec09c277  ./EFI/BOOT/BOOTAA64.EFI
fbeac908054b0ec7a8bcc9a6ec09c277  ./EFI/systemd/systemd-bootaa64.efi
5a4cf003b93943c4b44058ed9183dc31  ./fixup.dat
bc108de4fbde6b28ac03e73ca5fe7706  ./loader/entries/6122fd6adb744a5eb1f262b2f20628af-4.13.0-1-arm64.conf
5a52a2faae8bc9d3d165e14713429a12  ./loader/loader.conf
bc95aad9eb20575efb4efb1b6a0e209f  ./start.elf
fa1193d1b21c00740945636de1711029  ./u-boot.bin
alexander@shepard:/media/alexander/D950-263B$ 
```

Most of the files come from Debian buster (arm64) packages ([linux](https://packages.debian.org/buster/linux-image-4.13.0-1-arm64), [u-boot-rpi](https://packages.debian.org/buster/u-boot-rpi), and [systemd](https://packages.debian.org/buster/systemd), the firmware files are from the [official repository](https://github.com/raspberrypi/firmware) and the ```config.txt``` [5] contains this:

```
alexander@shepard:/media/alexander/D950-263B$ cat config.txt 
# Enable 64-bit mode
arm_64bit=1

# Start U-Boot
kernel=u-boot.bin
alexander@shepard:/media/alexander/D950-263B$ 
```
However, this doesn't work. Unfortunately, I don't have a serial console available, but I think this screenshot should explain the problem:

![screenshot](https://user-images.githubusercontent.com/8996356/33765031-4f9bcdec-dc17-11e7-876c-3ddf3de31d0d.png)

So, the firmware boots properly, U-Boot gets started, it finds the DTB at the "magic" path, it finds the fallback EFI binary at the expected path (containing systemd-boot), but this then crashes. I'm CCing @agraf here since he wrote most of the U-Boot UEFI code and according to the documentation [0] did test this with systemd-boot's predecessor, gummiboot. At this point I am mostly looking for some sort of statement of whether this setup *should* work at all, rather than an idea of why it doesn't. Any opinions?

Best regards

Alexander Kurtz

[0] https://github.com/u-boot/u-boot/blob/master/doc/README.efi#L269
[1] https://elinux.org/images/6/69/Marrying_U-Boot,_UEFI_and_grub.pdf
[2] https://www.youtube.com/watch?v=qJAkJ3nmWgM
[3] https://www.suse.com/docrep/documents/a1f0ledpbe/UEFI%20on%20Top%20of%20U-Boot.pdf
[4] https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/README.md
[5] https://www.raspberrypi.org/documentation/configuration/config-txt/README.md

**Comment by agraf** [comment]
There's a good chance we're just not implementing protocols that systemd-boot needs. Which version of U-Boot is this? Please try with the latest master, there were a good number of improvements in the last few releases.

If that doesn't help, I guess it's down to debugging where the code fails. I would recommend to do that inside a QEMU environment, so that you don't have to wait for your RPi to boot up ;).

**Comment by poettering** [comment]
Let's close this here. systemd-boot isn't really doing anything fancy, it's after all just a little tool displaying a menu. If the uboot uefi compat stuff isn't sufficient for this, this really needs to be fixed there, as much as I sympathize with this...

I hope that makes sense.

let's close this here hence. If there's really something we are doing but shouldn't do in sd-boot, then please reopen, but otherwise the onus here is in u-boot to fix this...

**Comment by HaleTom** [comment]
This mailing list post suggests this issue may have been resolved:

https://www.mail-archive.com/u-boot@lists.denx.de/msg417817.html
