### ISSUE TITLE
Please, add a D-Bus API to Systemd-networkd

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#7593]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> Any

### Used distribution

> Any

Cockpit Project uses this way to communicate to underlying system parts. Nowadays it uses Network-Manager to manage all the stuff relating net configuration. It would be great if it could use just systemd-networkd. 
Thanks

**Comment by keszybz** [comment]
Easier said than done ;) But that's the plan anyway.

**Comment by tdphette** [comment]
In regards to that plan... is the proposed d-bus API documented anywhere? If a person wanted to contribute to the effort and start implementing things, where should we start?

**Comment by keszybz** [comment]
On Tue, May 08, 2018 at 03:03:09PM +0000, Thad Phetteplace wrote:
> In regards to that plan... is the proposed d-bus API documented
> anywhere? If a person wanted to contribute to the effort and start
> implementing things, where should we start?

No. Designing the interface is probably more work than actually
implementing it. In practice the design and implementation will have
to be interleaved, i.e. start with some basic implementation, adjust
design, rinse, repeat.

If I was to work on this, I'd start with adding API that exposes
various bits of state which are not available currently and are
interesting to users. This should be relatively straightforward and
would be a way to gain familiarity with the code.

Zbyszek

**Comment by nicola-lunghi** [comment]
Hi,
there are updates on this?
and if not there's some other part of systemd that can be looked at to start impementing this?

The feature needed would be:
- display available network interfaces
- see interface status
- set dhcp/ip config
- wifi enable/disable
- wifi start scan
- wifi set ssid/password/certificates

etc...

**Comment by Gigadoc2** [comment]
> * wifi enable/disable
> * wifi start scan
> * wifi set ssid/password/certificates
> * wifi ap?

AFAIK networkd does not handle the "wifi parts" of wifi at all, only the ethernet and IP layer. To use wifi with networkd you need to run something like wpa_supplicant or iwd beside it anyway, and those have dbus interfaces which you you could query.

**Comment by yuwata** [comment]
Some of them are implemented by #12675.

**Comment by arizvisa** [comment]
Seriously, +1 on this. Some "certain" server-oriented distros are explicitly rm'ing systemd-networkd because of a missing dbus API. NetworkManager is garbage because it violates the beauty that is systemd's universal configuration which the devers worked so hard to bring to us.

**Comment by sakego** [comment]
I know systemd folks are hard at work on tons of stuff, but has there been any updates on this?

**Comment by keszybz** [comment]
This is mostly implemented now. networkctl has:
```
  list [PATTERN...]      List links
  status [PATTERN...]    Show link status
  lldp [PATTERN...]      Show LLDP neighbors
  label                  Show current address label entries in the kernel
  delete DEVICES...      Delete virtual netdevs
  up DEVICES...          Bring devices up
  down DEVICES...        Bring devices down
  renew DEVICES...       Renew dynamic configurations
  forcerenew DEVICES...  Trigger DHCP reconfiguration of all connected clients
  reconfigure DEVICES... Reconfigure interfaces
  reload                 Reload .network and .netdev files
```
It is not possible to push *configuration* over dbus, only to tell systemd-networkd to reload changed configuration from disk and bring interfaces up and down. Of course, everything is done over dbus. There is also some wifi integration. Nameservers can be set through resolved bus api. I'll close this now, since pretty much everything that was originally asked is available. Some bits are missing, but it's not clear that networkd should implement them. If you still want more things to be possible over dbus, please open a new ticket and we'll discuss it is should be added.

**Comment by q2dg** [comment]
Thanks. I'll ask in https://github.com/cockpit-project/cockpit/issues/7987 if Cockpit project see these improvements enough to use systemd-netowrkd as a backend instead of NetworkManager.  Thanks
