### ISSUE TITLE
mounts units have stdout/stderr → journal logging disabled currently, we should find a way to fix that

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#7603]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v235-909-g5e8727704

### Used distribution

Fedora 27

### Bug report

```
$ sudo systemctl status /boot --no-pager
● boot.mount - /boot
   Loaded: loaded (/etc/fstab; generated; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2017-12-10 22:45:35 GMT; 2min 31s ago
    Where: /boot
     What: XUUID=f86c55a0-75b1-4a75-96f9-4f63b9a04c83
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 7657 ExecMount=/bin/mount XUUID=f86c55a0-75b1-4a75-96f9-4f63b9a04c83 /boot -t ext4 (code=exited, status=32)

Dec 10 22:45:35 fedora27-vm systemd[1]: Mounting /boot...
Dec 10 22:45:35 fedora27-vm systemd[1]: boot.mount: Mount process exited, co…=32
Dec 10 22:45:35 fedora27-vm systemd[1]: boot.mount: Failed with result 'exit…e'.
Dec 10 22:45:35 fedora27-vm systemd[1]: Failed to mount /boot.
Hint: Some lines were ellipsized, use -l to show in full.
```

But here's what I see if I run the ExecMount manually:

```
$ sudo ExecMount=/bin/mount XUUID=f86c55a0-75b1-4a75-96f9-4f63b9a04c83 /boot -t ext4
mount: /boot: special device XUUID=f86c55a0-75b1-4a75-96f9-4f63b9a04c83 does not exist.
```

That's what I want to see logged.  Something is going wrong.

**Comment by poettering** [comment]
we currently turn off stdout/stderr logging for mount units by default, since that would otherwise mean that all mount units would gain a dep on journald, which we so far wanted to avoid in fear of creating cyclic deps... I am not entirely sure what we can do to improve that.

**Comment by sourcejedi** [comment]
journald only needs /run for storage, and that's excluded from being a mount unit (`systemctl status /run` returns no unit).  Am I missing something?

**Comment by sourcejedi** [comment]
I guess the problem would be at shutdown time; we don't have an inverse of `systemd-journal-flush.service`.

**Comment by sourcejedi** [comment]
Actually I don't see where the dependency cycle would happen, at least not in `systemd-234-9.fc27`.  systemd-journal is just writing /var/log/journal without a formal RequiresMount.  https://github.com/systemd/systemd/issues/867#issuecomment-148349919

So AFAICT the mount units could be changed to log to the journal, and it would not cause any problem.

PS. I think the concept switching back to /run/systemd/journal has a... challenge, w.r.t. ordering.  The obvious implementation would cause a switch back to /run immediately, so people would lose most of the  shutdown messages that have generally been logged to disk.  You want something ugly like an `ExecStopPre` dropin for all of var, var-log, and var-log-journal.mount.

**Comment by sourcejedi** [comment]
For the record, the linked PR was merged in v237, but mount units other than `/` _were_ logged via the journal up until v232.  It was removed in 11222d0fe0b5abb0cef65359b979e0c7f50129f3 in what looks like very much like an oversight, and it was not mentioned in the commit message.
