### ISSUE TITLE
systemd fails to start networkd at the right time and fails to bring up network correctly in nfs/nis context

### ISSUE THREAD

**Issue by jojoax** [systemd/systemd#7604]
### Submission type

Bug report
### systemd version the issue has been seen with
systemctl --version
systemd 235
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution
> Arch Linux Rolling Release, updated at Friday 8th Dec 2017

### In case of bug report: Expected behaviour you didn't see
> Network is sometimes not started correctly, systemd-networkd takes time and systemd does not wait on systemd-networkd-wait-online.service as expected

> dependencies for nis (ypbind) and nfs remote-fs mounts are disobeyed, ypbind is started much to early, but "After=systemd-netword-wait-online.servise" is defined

> if following case nfs mounts are tried - but systemd-networkd-wait-online.service is defined as Dependendcy, "After="
Such mout tries are failing, system is without Adminstrator access unusabel for Login/employees

> shadow.service is also failing, due missing dependecy of nis if system is nis enabled (ypbind.service exists). Changeing this via edit/override fails also, due ypbind.service dependency to systemd-networkd-wait-online.servis is trash, reports false positive

### In case of bug report: Unexpected behaviour you saw
[root@pc4 ~]# systemctl --failed
  UNIT                       LOAD   ACTIVE SUB    DESCRIPTION                                 
● home.mount                 loaded failed failed Besonderer Mount für AXS Server Home       
● var-cache-pacman-pkg.mount loaded failed failed Besonderer Mount für AXS Server Setup      
● shadow.service             loaded failed failed Verify integrity of password and group files

### In case of bug report: Steps to reproduce the problem

> Setup a NIS / NFS Server
> Setup Arch Linux Client, mounting 
> /home from NFS Like this:
> [root@pc4 system]# cat home.mount 
> [Unit]
> After=network-online.target
> After=nfs-client.target
> After=systemd-networkd-wait-online.service
> Description=Besonderer Mount für AXS Server Home
> [Mount]
> What=axn:/home
> Where=/home
> Type=nfs
> Options=rw,rsize=16384,wsize=16384
> TimeoutSec=45s
> [Install]
> WantedBy=multi-user.target

Simply boot.
And see the failure

**Comment by jojoax** [comment]
After a Minute or so manually starting the "failed" service works fine.
> [root@pc4 system]# systemctl start home.mount
> [root@pc4 system]# systemctl start shadow.service
> [root@pc4 system]# systemctl start var-cache-pacman-pkg.mount
> [root@pc4 system]# systemctl --failed
> 0 loaded units listed. Pass --all to see loaded but inactive units, too.
> To show all installed unit files use 'systemctl list-unit-files'.

After manually starting up, the  first time systemd faild services/mounts the queued jobs are not worked down.

i.E.:
[root@pc4 system]# for i in *.mount ; do  systemctl start $i; done
[root@pc4 system]# systemctl restart lightdm.servic
[pc4.log](https://github.com/systemd/systemd/files/1547080/pc4.log)

The system runs fine.
the fstab way for defining nfs based mounts fails in general, see bugreport:
https://github.com/systemd/systemd/issues/1401

**Comment by poettering** [comment]
I am sorry, but could you please contact downstream on this one first? we as upstream have no idea about the deps ypbind sets (and, uh, NIS, is this 1993?), and I don't know what "shadow.service" even is... Given that this issue appears to be about deps issues between ypbind, nfs and mounts I'd very much prefer if downstream could handle this first, and if they think they found a real bug, would escalate this here.

Thank you for understanding

**Comment by jojoax** [comment]
Hi Lennart, 
ypbind is the auth daemon, industrial standard in enterprise setups.
shadow.service is just checking the passwd/shadow files not important. I had mentioned it here because of completeness.

The Bug is:
systemd-networkd and systemd-networkd-wait-online are not korrect on link an fully operational ipv4.
Both services are giving false positive for link & IPv4 ok (ping external possible), so a depended service must fail, like the task starting nfs mounts and/or ypbind.servie.
Those mount requestst are not transmitted to the server due systemd-netword reported a at this time definetely not working network connection false as "working". This is the problem.

Sometimes this setup works flawlessly, why ? 
No idea why, perhaps a timing problem on link auto negotiation, but on this setup link speed and eth parameters are fixed.

My idea is, what is to do, that systemd-networkd ist much more reliabel on detection real operating network ?

**Comment by poettering** [comment]
> ypbind is the auth daemon, industrial standard in enterprise setups.

It was that 25 years ago I figure...

But anyway, please ping downstream first about integration issues between various packages, that's what distributions are for. 

My educated guess is that there are some dep cycles lurking somewhere, in particular given the background in #1401

**Comment by jojoax** [comment]
Ok,  #1401 does not interferr here. Forget about ypbind here.

The **hot point** is, why does **systemd-networkd report false positve "online status"** on really **not operational states**?

All services depending from a operational network must going into fail afterwards, as logged here.

**Comment by poettering** [comment]
so what does "networkctl status -a" say at the point where s-n-w-o reports that network connectivity is ready?

**Comment by jojoax** [comment]
Here a current try:
> # journalctl --boot=0
> ...
> Dez 12 12:13:49 pc4 kernel: r8169 Gigabit Ethernet driver 2.3LK-NAPI loaded
> Dez 12 12:13:49 pc4 kernel: Linux agpgart interface v0.103
> Dez 12 12:13:49 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:49 pc4 kernel: r8169 0000:03:00.0 eth0: RTL8168evl/8111evl at 0xffffae7f41061000, 00:01:2e:5a:72:56, XID 0c900800 IRQ 48
> Dez 12 12:13:49 pc4 kernel: r8169 0000:03:00.0 eth0: jumbo features [frames: 9200 bytes, tx checksumming: ko]
>...
Dez 12 12:13:49 pc4 kernel: i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
Dez 12 12:13:49 pc4 systemd-networkd-wait-online[268]: ignoring: lo
Dez 12 12:13:49 pc4 kernel: [drm] Initialized i915 1.6.0 20170818 for 0000:00:02.0 on minor 0
>...
Dez 12 12:13:50 pc4 systemd-udevd[242]: Process '/usr/bin/ip link set dev eth0 up 'eth0'' failed with exit code 255.

Remark **this should never fail**

> Dez 12 12:13:50 pc4 kernel: input: HDA Intel HDMI HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:03.0/sound/card0/input12
> Dez 12 12:13:50 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:50 pc4 kernel: r8169 0000:03:00.0 eth0: link down
> Dez 12 12:13:50 pc4 kernel: r8169 0000:03:00.0 eth0: link down
> Dez 12 12:13:50 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:50 pc4 kernel: ieee80211 phy0: Selected rate control algorithm 'iwl-mvm-rs'
> Dez 12 12:13:50 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:50 pc4 systemd-udevd[244]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
> Dez 12 12:13:50 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:50 pc4 dbus-daemon[348]: [system] Successfully activated service 'org.freedesktop.ColorManager'
> Dez 12 12:13:50 pc4 systemd[1]: Started Manage, Install and Generate Color Profiles.
> Dez 12 12:13:50 pc4 sh[410]: Kann keine Verbindung aufbauen.
> Dez 12 12:13:50 pc4 sh[410]: Grund: Die Domain wurde nicht zugewiesen
> Dez 12 12:13:51 pc4 colord[458]: failed to get session [pid 401]: Keine Daten verfügbar
> Dez 12 12:13:51 pc4 systemd[1]: Started CUPS Scheduler.
> Dez 12 12:13:51 pc4 systemd[1]: Started Make remote CUPS printers available locally.
> Dez 12 12:13:51 pc4 dbus-daemon[348]: YPBINDPROC_DOMAIN: Domain not bound
> Dez 12 12:13:51 pc4 sh[410]: Kann keine Verbindung aufbauen.
> Dez 12 12:13:51 pc4 sh[410]: Grund: Die Domain wurde nicht zugewiesen
> **Dez 12 12:13:52 pc4 kernel: r8169 0000:03:00.0 eth0: link up**
> Dez 12 12:13:52 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:52 pc4 avahi-daemon[403]: Joining mDNS multicast group on interface eth0.IPv4 with > address 192.168.11.14.
> **Dez 12 12:13:52 pc4 systemd-networkd[264]: eth0: Gained carrier**
> Dez 12 12:13:52 pc4 avahi-daemon[403]: New relevant interface eth0.IPv4 for mDNS.
> Dez 12 12:13:52 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:52 pc4 avahi-daemon[403]: Registering new address record for 192.168.11.14 on eth0.IPv4.
> Dez 12 12:13:52 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> **Dez 12 12:13:52 pc4 systemd-networkd[264]: eth0: Configured**
> Dez 12 12:13:52 pc4 systemd-networkd-wait-online[268]: ignoring: lo
> Dez 12 12:13:52 pc4 systemd-networkd-wait-online[268]: ignoring: wlan0
> Dez 12 12:13:52 pc4 systemd[1]: Started Wait for Network to be Configured.
> **Dez 12 12:13:52 pc4 systemd[1]: Reached target Network is Online.**
> **Dez 12 12:13:52 pc4 systemd[1]: Mounting Besonderer Mount für AXS Server Setup...**
[home.mount.txt](https://github.com/systemd/systemd/files/1551391/home.mount.txt)
> **Dez 12 12:13:52 pc4 systemd[1]: Mounting Besonderer Mount für AXS Server Home...**
[home-fileserver-setup.mount.txt](https://github.com/systemd/systemd/files/1551395/home-fileserver-setup.mount.txt)
And here is the fatal problem: those mounts are failing!

> Dez 12 12:13:54 pc4 systemd[541]: Started Update XDG user dir configuration.
> Dez 12 12:13:54 pc4 systemd[541]: Reached target Default.
> Dez 12 12:13:54 pc4 systemd[541]: Startup finished in 56ms.

but the real state at the "Reached target default" is:
> [root@pc4 ~]# systemctl --failed
>   UNIT                       LOAD   ACTIVE SUB    DESCRIPTION                           
> ● home.mount                 loaded failed failed Besonderer Mount für AXS Server Home 
> ● var-cache-pacman-pkg.mount loaded failed failed Besonderer Mount für AXS Server Setup

And at this time I can check: "networkctl status -a", result below.
[network.txt](https://github.com/systemd/systemd/files/1551426/network.txt)

Changing the home.mount uniti's dependencies "After=" into
> [Unit]
> After=systemd-networkd-wait-online.service
> After=remote-fs-pre.target
> After=nfs-client.target
> After=auth-rpcgss-module.service
> After=rpc-statd-notify.service

**It looks like, it works - for now.**
But the point is whe does the dependency tree on "After=nfs-client.target" not work?
I just defined the nfs-client.target dependencies within the unit file "home.mount".

Using the mechanism without the hard defined *.mount files - just via the automated systemd fstab analysis - does not wor reliable.
It works sometimes, sometimes not, without changes on server or network.

**Comment by poettering** [comment]
> Dez 12 12:13:50 pc4 systemd-udevd[242]: Process '/usr/bin/ip link set dev eth0 up 'eth0'' failed with exit code 255.

Umm, what is this? a udev rule tht invokes "ip"? if you fiddle with the up state of the iface, don't be surprised if s-n-w-o doesn't work as it should anymore...

**Comment by jojoax** [comment]
the problem occours with or without the ip call in udev.
we had to fiddle along to get this company working again. There are about 30 workstations around the server, which all showing the same problem.

Removing the call to the ip tool makes it more worse, than better.
Mostly all other workstations does not deal with "ip" in udev. Sometimes  those with the awfull realtek chip r8169 have, esp. the worst system, which I used for debugging and bug reporting.

**Comment by poettering** [comment]
The networkctl status output is of course only relevant right after s-n-w-o ran. Consider adding an ExecStopPost= line for it to its service.

**Comment by jojoax** [comment]
will do so, right now.
this morning I've got a clear error log out from an other workstation:
> Dez 13 10:12:41 pc5 systemd-networkd-wait-online[284]: Event loop failed: Connection timed out
> Dez 13 10:12:41 pc5 systemd[1]: systemd-networkd-wait-online.service: Main process exited, > code=exited, status=1/FAILURE
> Dez 13 10:12:41 pc5 networkctl[411]: ● 1: lo
> Dez 13 10:12:41 pc5 networkctl[411]:        Link File: /usr/lib/systemd/network/99-default.link
> Dez 13 10:12:41 pc5 networkctl[411]:     Network File: n/a
> Dez 13 10:12:41 pc5 networkctl[411]:             Type: loopback
> Dez 13 10:12:41 pc5 networkctl[411]:            State: carrier (unmanaged)
> Dez 13 10:12:41 pc5 networkctl[411]:          Address: 127.0.0.1
> Dez 13 10:12:41 pc5 networkctl[411]:                   ::1
> Dez 13 10:12:41 pc5 networkctl[411]: ● 2: eth0
> Dez 13 10:12:41 pc5 networkctl[411]:        Link File: /usr/lib/systemd/network/99-default.link
> Dez 13 10:12:41 pc5 networkctl[411]:     Network File: /etc/systemd/network/info.network
> Dez 13 10:12:41 pc5 networkctl[411]:             Type: ether
> Dez 13 10:12:41 pc5 networkctl[411]:            State: no-carrier (configuring)
> Dez 13 10:12:41 pc5 networkctl[411]:             Path: pci-0000:03:00.0
>  Dez 13 10:12:41 pc5 networkctl[411]:           Driver: r8169
> Dez 13 10:12:41 pc5 networkctl[411]:           Vendor: Realtek Semiconductor Co., Ltd.
> Dez 13 10:12:41 pc5 networkctl[411]:            Model: RTL8111/8168/8411 PCI Express Gigabit Ethernet > Controller (Onboard Ethernet)
> Dez 13 10:12:41 pc5 networkctl[411]:       HW Address: 00:1f:d0:92:8d:c1 (GIGA-BYTE TECHNOLOGY CO.,LTD.)
> Dez 13 10:12:41 pc5 networkctl[411]:              DNS: 192.168.11.251
> **Dez 13 10:12:41 pc5 systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.**
> Dez 13 10:12:41 pc5 systemd[1]: Failed to start Wait for Network to be Configured.

** BUG is here **
> ** Dez 13 10:12:41 pc5 systemd[1]: Reached target Network is Online.**

Dez 13 10:12:41 pc5 systemd[1]: home.mount: Directory /home to mount over is not empty, mounting anyway.
Dez 13 10:12:41 pc5 systemd[1]: Mounting Besonderer Mount für AXS Server Home...
...
Dez 13 10:12:41 pc5 systemd[1]: home.mount: Mount process exited, code=exited status=32
> ...
> Dez 13 10:12:44 pc5 kernel: r8169 0000:03:00.0 eth0: link up
> Dez 13 10:12:44 pc5 avahi-daemon[397]: New relevant interface eth0.IPv4 for mDNS.
> Dez 13 10:12:44 pc5 avahi-daemon[397]: Registering new address record for 192.168.11.15 on eth0.IPv4.
> Dez 13 10:12:44 pc5 systemd-networkd[270]: eth0: Configured

of course those mounts must fail, like here logged, becaus those depend on working network

q.e.d.

**Comment by jojoax** [comment]
No Reply ?
Bug is still existin in 236

**Comment by jojoax** [comment]
This systemd destroys my and our Admin Team here the new year's day party.
Thank you, Mr. Poetering

**Comment by poettering** [comment]
Let's close this here. This is something to report to the NIS maintainers of your distro, we can't do much about this upstream. Please work with them, and they will contact us if there's something to fix in systemd upstream or if they need more hooks for proper synchronization. We don#t run NIS upstream and we can't possibly fix this hence, hence it's just not honest to leave this open here. Hope that makes some sense even if disapponting.
