### ISSUE TITLE
don't try to disable IPv6 proxy NDP if IPv6 is not available

### ISSUE THREAD

**Issue by 0xabcdef** [systemd/systemd#7612]
### Submission type

 - Bug report

### systemd version the issue has been seen with

>  systemd 234
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

> Ubuntu 17.10

### In case of bug report: Unexpected behaviour you saw

> A proxy NDP failure message (used with ipv6) while i had ipv6 disabled.

### In case of bug report: Steps to reproduce the problem

>
1) disable ipv6 via /etc/default/grub:
GRUB_CMDLINE_LINUX_DEFAULT='ipv6.disable=1'
2) reboot
3) journalctl _SYSTEMD_UNIT=systemd-networkd.service 
shows '... Cannot configure proxy NDP for interface: No such file or directory'

Can trace the message back to systemd/src/network/networkd-ipv6-proxy-ndp.c
The messages is no big deal.
But maybe there are more places where a check on ipv6 (un)availability is needed.

Regards, Mike

**Comment by poettering** [comment]
/cc @ssahani 

Fix waiting in #7613
