### ISSUE TITLE
User service not loading - cant open display

### ISSUE THREAD

**Issue by Gibbz** [systemd/systemd#7622]
I have a user service thats not loading correctly. Im assuming due to no access the display...
I have enabled the user service with
loginctl enable-linger username
systemctl --user enable tool-slideshow

When i reboot the app doesnt launch. I get the error:
systemd[481]: Started Slideshow Service.
python[514]: Can't open display

But it says its active and running. But the user interface has not displayed.

my service in ~/.config/systemd/user/
[Unit]
Description=Slideshow Service

[Service]
Type=simple
ExecStart=/usr/bin/python /home/bronson/Scripts/tool-slideshow.py

[Install]
WantedBy=default.target

**Comment by fsateler** [comment]
Hi,

This is an issue tracker, and not a support forum. Please ask for support on the mailing list (systemd-devel@lists.freedesktop.org) or on the irc channel #debian-systemd on freenode.

Thanks!
