### ISSUE TITLE
Support disabling cgroup controller within systemd

### ISSUE THREAD

**Issue by cdown** [systemd/systemd#7624]
### Submission type

 - Request for enhancement (RFE)

### Details

In February this year, I along with @htejun identified a performance/latency regression in the cgroup CPU controller. While this issue has subsequently been fixed, for machines not running a new enough kernel, the fix applied has been to disable the CPU controller forcibly with `cgroup_disable=cpu` on the kernel command line inside Facebook.

This presents a problem: to disable or reenable the controller, a reboot is required, but this is quite cumbersome and slow to do for many thousands of machines, especially machines where disabling/enabling a stateful service on a machine is a matter of several minutes.

Currently systemd provides some configuration knobs for these in the form of `[Default]CPUAccounting`, `[Default]MemoryAccounting`, and their ilk. The limitation of these is that Default*Accounting is overrideable by individual services, of which any one could decide to reenable a controller within the hierarchy at any point just by using a controller feature implicitly (eg. `CPUWeight`), even if the use of that CPU feature could just be opportunistic. Since many services are provided by the distribution, or by upstream teams at a particular organisation, it's not a sustainable solution to simply try to find and remove offending directives from these units.

As such, I propose the creation of two new controls:

- Some mechanism to, within systemd, refuse to use a particular controller at all. This could perhaps be in the form of something like `Ignore{CPU,Memory,...}Accounting`, where we disable it per-controller in a manner similar to how `*Accounting` directives do it right now. Since these are directly related to a controller, however, it might also just make sense to not be cgroup-agnostic about it and write `IgnoreCgroupController={cpu,memory,...}`.
- The `Assert{CPU,Memory,...}Accounting` or `AssertCgroupController={cpu,memory,...}` directive, which fails loading a unit if it *really* needs some particular controller to be available.

This would allow systemd users to more effectively work around potential issues encountered during cgroup operation without having to reboot a machine to add `cgroup_disable`.

**Comment by cdown** [comment]
(fyi, I'm planning to write up patches for these, so this is mostly for tracking)

**Comment by poettering** [comment]
hmm, instead of adding new settings for this, maybe we should just beef up DefaultMemoryAccounting= and friends with more values. Right now, it's considered a simple boolean (i.e. something which takes yes/1/on/true or no/0/off/false). I figure we can turn it into an "extended" boolean, i.e. where we first parse it as a boolean, and if that doesn't work we see if the value is either "always" or "never". These two values would then have the effect that what is set within the units would not have any effect anymore, but be fixed to "yes" and "no".

Going this way appears preferable to me, as I'd like to avoid an inflation of settings here, in particular for something is probably more in the territory of "debugging" than the most common of usecases, if you follow what i mean

**Comment by cdown** [comment]
Sounds fine to me. What do you think about `AssertCgroupController`? That seems worth it either way since it could be disabled either by systemd (after these proposed changes) or externally.

For now I'd first just add checks on `cg_mask_supported` and can extend to `Default*Accounting` afterwards

**Comment by poettering** [comment]
adding a Condition/Assert type for controller availability makes sense, not entirely sure about the name though, I don't think "Cgroup" is a proper word... Maybe "AssertControlGroupController"?

**Comment by cdown** [comment]
That's also fine with me. I've drafted the patch and will put it up after testing.

**Comment by cdown** [comment]
(Also, now that in v2 with 4.15+ all controllers except CPU controller have accounting and controlling as one (and CPU accounting in this case is controllerless) it might make sense to eventually start moving `FooAccounting` in favour of `FooController`)

**Comment by cdown** [comment]
Now that #10567 and #7630 are both merged, this can be closed. Thanks for the reviews!
