### ISSUE TITLE
AlpsPS/2 ALPS Glidepoint libinput size hint

### ISSUE THREAD

**Issue by hobbitalastair** [systemd/systemd#763]
I have a touchpad which falls back to libinput's default size value - 69x50mm.
However, the touchpad is actually 74x43mm.

@whot - I'm not sure where this should be filed, since the other touchpad resolution hints seem to be in a libinput file, 90-libinput-model-quirks.hwdb?
Sorry for the noise if this is the wrong place for this bug.

I'm also not sure why the [existing rule](http://cgit.freedesktop.org/wayland/libinput/tree/udev/90-libinput-model-quirks.hwdb#n26) for what appears to be the same touchpad is not picked up, although the touchpad itself is of a different physical size from the one in the rule.

The touchpad is in a Dell Vostro 1510.
The output from udevadm info /dev/input/event11 is (now):

```
P: /devices/platform/i8042/serio1/input/input9/event11
N: input/event11
S: input/by-path/platform-i8042-serio-1-event-mouse
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-1-event-mouse
E: DEVNAME=/dev/input/event11
E: DEVPATH=/devices/platform/i8042/serio1/input/input9/event11
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_PATH=platform-i8042-serio-1
E: ID_PATH_TAG=platform-i8042-serio-1
E: ID_SERIAL=noserial
E: LIBINPUT_ATTR_SIZE_HINT=74x43
E: LIBINPUT_DEVICE_GROUP=11/2/8/200:isa0060/serio1
E: LIBINPUT_MODEL_ALPS_TOUCHPAD=1
E: LIBINPUT_MODEL_FIRMWARE_VERSION=8
E: MAJOR=13
E: MINOR=75
E: SUBSYSTEM=input
E: USEC_INITIALIZED=13600805
```

**Comment by whot** [comment]
as for why it isn't picked up: maybe a typo somewhere? it'd be great if you can figure that out for us, udevadm test /sys/class/input/event11 is your friend here, it displays what happens when you modify the rule file. Or maybe the hwdb isn't picked up?

to have a permanent rule, I'd need your /sys/class/dmi/id/modalias and the min/max ranges for the x/y axes on the device (evemu-describe).

**Comment by hobbitalastair** [comment]
I'm a bit confused as to what is happening here.
After a reboot, libinput-list-devices reports a physical size of 73x51mm - I measure 73x44mm. However, weston's log output says that there are no resolution or size hints for the touchpad, so it assumes a size of 69x50mm.

Udev initially doesn't set the LIBINPUT_MODEL_FIRMWARE_REVISION variable, and hence it does not set the size hint. However, if I trigger the device udev rules again, both LIBINPUT_MODEL_FIRMWARE_REVISION and LIBINPUT_ATTR_SIZE_HINT is set, to 8 and 100x55 respectively.
The message in weston's log then disappears, so I assume that it is using the size set by the hint.

Contents of /sys/class/dmi/id/modalias:
         dmi:bvnDellInc.:bvrA15:bd03/18/2009:svnDellInc.:pnVostro1510:pvrNull:rvnDellInc.:rn0R780K:rvr:cvnDellInc.:ct8:cvrN/A:

evemu-describe output:

```
# EVEMU 1.2
# Input device name: "AlpsPS/2 ALPS GlidePoint"
# Input device ID: bus 0x11 vendor 0x02 product 0x08 version 0x200
# Supported events:
#   Event type 0 (EV_SYN)
#     Event code 0 (SYN_REPORT)
#     Event code 1 (SYN_CONFIG)
#     Event code 2 (SYN_MT_REPORT)
#     Event code 3 (SYN_DROPPED)
#     Event code 4 ((null))
#     Event code 5 ((null))
#     Event code 6 ((null))
#     Event code 7 ((null))
#     Event code 8 ((null))
#     Event code 9 ((null))
#     Event code 10 ((null))
#     Event code 11 ((null))
#     Event code 12 ((null))
#     Event code 13 ((null))
#     Event code 14 ((null))
#   Event type 1 (EV_KEY)
#     Event code 272 (BTN_LEFT)
#     Event code 273 (BTN_RIGHT)
#     Event code 274 (BTN_MIDDLE)
#     Event code 325 (BTN_TOOL_FINGER)
#     Event code 330 (BTN_TOUCH)
#   Event type 3 (EV_ABS)
#     Event code 0 (ABS_X)
#       Value    266
#       Min        0
#       Max     1023
#       Fuzz       0
#       Flat       0
#       Resolution 0
#     Event code 1 (ABS_Y)
#       Value    502
#       Min        0
#       Max      767
#       Fuzz       0
#       Flat       0
#       Resolution 0
#     Event code 24 (ABS_PRESSURE)
#       Value      0
#       Min        0
#       Max      127
#       Fuzz       0
#       Flat       0
#       Resolution 0
# Properties:
#   Property  type 0 (INPUT_PROP_POINTER)
N: AlpsPS/2 ALPS GlidePoint
I: 0011 0002 0008 0200
P: 01 00 00 00 00 00 00 00
B: 00 0b 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 07 00 00 00 00 00
B: 01 20 04 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 02 00 00 00 00 00 00 00 00
B: 03 03 00 00 01 00 00 00 00
B: 04 00 00 00 00 00 00 00 00
B: 05 00 00 00 00 00 00 00 00
B: 11 00 00 00 00 00 00 00 00
B: 12 00 00 00 00 00 00 00 00
B: 14 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
A: 00 0 1023 0 0 0
A: 01 0 767 0 0 0
A: 18 0 127 0 0 0
```

I assume that this translates to 1023x767?

**Comment by whot** [comment]
1023x767  is the range of the x/y axes. Look at the comments, the blurb at the bottom is just the machine-readable bit. the comments are human-readable.

I wonder: does it not set the firmware variable or does it set it but it's not immediately picked up? is this even possible with udev rules? Add this rule between the two existing rules and check what the value of FOO is after boot:

```
KERNELS=="*input*", \
  ENV{ID_INPUT_TOUCHPAD}=="1", \
  ENV{FOO}="> $env{LIBINPUT_MODEL_FIRMWARE_VERSION} <"
```

if it's empty, the firmware version isn't set correctly

**Comment by hobbitalastair** [comment]
FOO contains ">  <", at least until the rules are triggered again.

I don't understand why this happens, since it's after the corresponding rule for 
"importing" from libinput-model-quirks, and it does run, since FOO is set.

Calling

```
/usr/lib/udev/libinput-model-quirks /sys/class/input/event11
```

returns the expected result, ie

```
LIBINPUT_MODEL_FIRMWARE_VERSION=8
```

So it appears that, for some reason, libinput-model-quirks is either not running or not working as it should?
I don't see why it wouldn't run, since the second rule does. :frowning: 

# 

Have I given you all you need for a permanent rule?

**Comment by whot** [comment]
hmm, this is indeed odd. my only guess now is that libinput-model-quirks fails for some reason (and it's built to quietly fail). with a callout, they can print anything and it's added to the env, so you can sprinkle printf statements into the code to check where it fails. I'd say add this line:
printf("DEBUG_LINE_%s_%d=1\n", **func**, **LINE**); before/after error handling, then restart. run udevadm info, and check which ones are present and which ones are missing.

as for the udev rule, yes, I think I have everything. goes into 60-evdev.hwdb and should read:

```
evdev:name:AlpsPS/2 ALPS GlidePoint*:dmi:bvn*:bvr*:bd*:svnDellInc.:pnVostro1510*
 EVDEV_ABS_00=::14
 EVDEV_ABS_01=::18
```

that's rounded up, we only do integer resolutions (xres = 1023/74, yres= 767/43) but close enough.

**Comment by hobbitalastair** [comment]
libinput-model-quirks is bailing out on this:

```
if (udev_device_get_property_value(device, "ID_INPUT_TOUCHPAD")) {
            printf("DEBUG_LINE_%s_%d=1\n", "main", 138);
            handle_touchpad(device);
} else {
            printf("NOT_A_TOUCHPAD=1\n");
}
```

Apparently, the device is not a touchpad... at least not during boot. Although I may have done something wrong here; I haven't done much C programming.
NOT_A_TOUCHPAD is set in the udevadm output, and so is ID_INPUT_TOUCHPAD. The output of udevadm test /path/to/device, however, does not include NOT_A_TOUCHPAD, and has DEBUG_LINE_main_138=1 in the output instead.

I'll try to test the udev rule tomorrow.

**Comment by hobbitalastair** [comment]
The udev rule works, thanks!

**Comment by whot** [comment]
fwiw, the markdown has misinterpreted the underscores, above I wrote:

```
printf("DEBUG_LINE_%s_%d=1\n", __func__, __LINE__);
```

this way the compiler fills in the func name and line number for you and you can just copy/paste it everywhere.

as for the missing ID_INPUT_TOUCHPAD, this is a bit confusing since we don't even call he binary unless this is set. I wonder if there's some race condition we're triggering where the callout has a different udev device than we see in the rules? something like that...

**Comment by whot** [comment]
does it work when you replace udev_device_get_property_value() with prop_value() in main()?

**Comment by hobbitalastair** [comment]
Yes, it does work - although that's built against a slightly more recent version of libinput (a couple of revisions on, anyway).

**Comment by hobbitalastair** [comment]
There's now a [patch](http://lists.freedesktop.org/archives/wayland-devel/2015-August/023791.html) for this on the wayland-devel mailing list.

Any further discussion about the libinput-model-quirks patch probably belongs there, and my first issue is solved, so I'm closing this thread.
