### ISSUE TITLE
Add DHCP relay support to networkd (RFC3046 DHCP Relay Agent Information Option)

### ISSUE THREAD

**Issue by halvors** [systemd/systemd#7650]
### Submission type

 - Request for enhancement (RFE)

> Add new parameter DHCPRelay= to networkd, where user can specify an IP address to relay DHCP requests to. Both for DHCPv4 and DHCPv6. I propose to add this under the [Network] section, next to the DHCPServer= parameter.

### Feature description

The systemd DHCP server which currently doesn’t support the implementation of DHCP Relay Agent Information Option (RFC3046).

This implementation is important in cases where the DHCP server is located elsewhere in the network. Absence of the Relay Agent in such cases would result in impossibility of DHCP configuration in a more complex network environment.

Other advantages of the DHCP Relay Agent implementation include:

- DHCP broadcast replies can be routed to the only specific destination, avoiding, say, the replication of the DHCP reply broadcast onto thousands of access circuits

- The same mechanism used to identify the remote host and may be used as a host identifier by DHCP, and used for parameter assignment. This provides a secure remote ID from a trusted source -- the relay agent.

- A number of issues arise when forwarding DHCP requests from host connecting publicly accessed high-speed circuits with LAN connections at the host. Many of these are security issues arising from DHCP client requests from untrusted sources.  How does the relay agent know to which circuit to forward replies?  How does the system prevent  DHCP IP exhaustion attacks?  This is when an attacker requests all available IP addresses from a DHCP server by sending requests with fabricated client MAC addresses.  How can an IP address or LIS be permanently assigned to a particular user or modem?  How does one prevent "spoofing" of client identifier fields used to assign IP addresses?  How does one prevent denial of service by "spoofing" other client's MAC addresses? All of these issues may be addressed by having the circuit access equipment, which is a trusted component, add information to DHCP client requests that it forwards to the DHCP server.

- The DHCP relay agent option resolves several issues in an environment in which untrusted hosts access the internet via a circuit based public network.  This resolution assumes that all DHCP protocol traffic by the public hosts traverse the DHCP relay agent and that the IP network between the DHCP relay agent and the DHCP server is uncompromised.

Furthermore, Agent Circuit ID and Agent Remote ID sub-options may be added by DHCP Relay Agent which terminates the switched or permanent circuits. 

The Agent Circuit ID sub-option encodes an agent-local identifier of the circuit from which a DHCP client-to-server packet was received. It is intended for use by agents in relaying DHCP responses back to the proper circuit. 

Possible uses of this field include:

- Router interface number

- Switching Hub port number

- Remote Access Server port number

- Frame Relay DLCI

- ATM virtual circuit number

- Cable Data virtual circuit number

The Agent Remote ID sub-option identifies the remote host end of the circuit.  The Remote ID field may be used to encode, for instance:

- a "modem ID" of a cable data modem

- the remote IP address of a point-to-point link

**Comment by halvors** [comment]
Is this something that is being considered?

**Comment by yegor-alexeyev** [comment]
Hi! I think this may be closed now!
