### ISSUE TITLE
systemd-236/src/udev/udev-builtin-net_id.c:550]: (style) Redundant condition

### ISSUE THREAD

**Issue by dcb314** [systemd/systemd#7656]
systemd-236/src/udev/udev-builtin-net_id.c:550]: (style) Redundant condition: If '!bus_id_len', the comparison 'bus_id_len < 8' is always true.

Source code is

       if (!bus_id_len || bus_id_len < 8 || bus_id_len > 9)

maybe better code

       if (bus_id_len < 8 || bus_id_len > 9)

**Comment by poettering** [comment]
Any chance you can prep a fix for this as a PR? That way the fix will be attributed to you and everything!

**Comment by yuwata** [comment]
@dcb314 I've created PR #7739. Could you inform me your name and email address? If I get them, I will set them in the author tag of the commit. (Of course if you want so.)
