### ISSUE TITLE
systemd-236/src/boot/efi/boot.c:169]: (style) Redundant condition

### ISSUE THREAD

**Issue by dcb314** [systemd/systemd#7657]
systemd-236/src/boot/efi/boot.c:169]: (style) Redundant condition: If 'EXPR == ' '', the comparison 'EXPR' is always true.

Source code is

    while (line[first + cursor] && line[first + cursor] == ' ')

maybe better code

    while (line[first + cursor] == ' ')

**Comment by keszybz** [comment]
Yeah. Can you submit a PR with this patch and #7656 ?

**Comment by yuwata** [comment]
@dcb314 I've created PR #7739. Could you inform me your name and email address? If I get them, I will set them in the author tag of the commit. (Of course if you want so.)

**Comment by poettering** [comment]
Fxied by #7739
