### ISSUE TITLE
 systemd: "systemd-analyze plot" fails for root

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#7667]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v235
v236

### Used distribution

Debian sid

Downstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884506

### In case of bug report: Expected behaviour you didn't see

```systemd-analyze plot``` works when run as root.

### In case of bug report: Unexpected behaviour you saw

```
# systemd-analyze plot
Failed to get host information from systemd: Unknown object '/org/freedesktop/hostname1'.
```
### In case of bug report: Steps to reproduce the problem

Switch to root via sudo, or by logging in as root on the console, then run ```systemd-analyze plot```

**Comment by shawnl** [comment]
It works for me when run as root on Ubuntu 17.10 (v234), but not Debian sid.

**Comment by vtal-arch** [comment]
I faced similar issue using Gentoo Linux with systemd-236.

**Comment by vtal-arch** [comment]
systemd-analyze plot
works properly.

sudo systemd-analyze plot
is buggy.

**Comment by keszybz** [comment]
I can reproduce this. This seems to be an issue in dbus daemon. hostnamed is never contacted, the error comes from dbus. @smcv, any ideas?

**Comment by keszybz** [comment]
Never mind. With `sudo` we're doing a private connection, dbus daemon is not involved at all.
