### ISSUE TITLE
copy more devices to nspawn container

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#7669]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234,235

### Used distribution

> arch,centos7

It's be nice if we were able to add to the [list of devices](https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L1515-L1522) that systemd-nspawn copies from the host.

We'd like to do this with `/dev/fuse`, e.g.

Something like `systemd-nspawn ... --copy-device /dev/foo ...`

It may also be helpful to create new devices inside the container that don't exist on the host, although I don't have an example of where this would be useful right now.

**Comment by poettering** [comment]
Well, I'd love to just make fuse available by default, but iirc fuse is still not properly set up for usage in containers, i.e. just making the fuse node available is not safe, as it leaks access on host-side mounts or so, I don't remember the details about that.

If that changes we should just make FUSE available by default. Until then: you can hack around this already if you are willing to ignore the security implications around this. Just use "--bind=/dev/fuse" on the nspawn cmdline, it knows how to deal with device nodes these days.

Hence, I figure what you are asking for already exists, just under a different name. Closing hence.
