### ISSUE TITLE
[236] systemctl --dry-run doesn't work as expected

### ISSUE THREAD

**Issue by jnpkrn** [systemd/systemd#7670]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Fedora Rawhide

### In case of bug report: Expected behaviour you didn't see

> Some information provided on command-line, the target _not_ executed literally.

### In case of bug report: Unexpected behaviour you saw

> E.g. `systemctl --dry-run suspend` will just suspend the machine.

### In case of bug report: Steps to reproduce the problem

> See above

**Comment by rhertzog** [comment]
@keszybz is the author of the commit that added the --dry-run flag:
https://github.com/systemd/systemd/commit/1ae17672a23a48185ac951c884beeeab874df22d

I also got bitten by this bug with Debian's package of systemd 236 (236-3 here).

**Comment by jnpkrn** [comment]
Hmm, with v239, it exhibits the opposite extreme -- doesn't respond in any way,
nothing new appears on the terminal (as expected).

The only exception is with `kexec`, which tells me that `/usr/sbin/kexec` is missing.

I thought I would get some informative output (stop this, start that, etc.).

**Comment by schymans** [comment]
I have the same problem:
```
systemctl --dry-run suspend
```
does not return or do anything. However, if I run the command without `--dry-run`, I get a black screen, have to do CTRL+C and then log in again. Should this issue not be re-opened?

**Comment by schymans** [comment]
I have the same problem:
```
systemctl --dry-run suspend
```
does not return or do anything. However, if I run the command without `--dry-run`, I get a black screen, have to do CTRL+C and then log in again. Should this issue not be re-opened?

**Comment by schymans** [comment]
I have the same problem:
```
systemctl --dry-run suspend
```
does not return or do anything. However, if I run the command without `--dry-run`, I get a black screen, have to do CTRL+C and then log in again. Should this issue not be re-opened?
