### ISSUE TITLE
Failure to Safely Handle Corrupt but non-Essential File Systems... 

### ISSUE THREAD

**Issue by sproggit** [systemd/systemd#7671]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

### Used distribution

Mint Linux 18.3 [Cinnamon Edition, 64-bit] 

### In case of bug report: Expected behaviour you didn't see

Trappable Error Handling

### In case of bug report: Unexpected behaviour you saw

Unrecoverable Error

### In case of bug report: Steps to reproduce the problem

This failure mode concerns hardware configurations which include a shared NTFS volume which can be accessed by both Windows 10 and Linux on the same hardware. If the Windows environment is configured with "Fast Start" [i.e. drive caching] then the NTFS volume can be un-mounted by Windows in an "unsafe" state. This actually occurs quite frequently, because Microsoft regularly apply updates which seem to over-write any user-set disabling of Fast Start. 

The failure mode is that when systemd encounters an NTFS volume in this "unsafe state", it stops the initialisation process and enters emergency mode. Please bear in mind that the volume in question [which in my case is mounted to /dev/local] exists purely to share data between the two OS platforms and is not *required* by either OS. 

Applying the principle of "least surprise", we should expect systemd to attempt to mount the FS, find it in an insecure state, post a warning, and continue to boot. This may not be the case if the volume in question has system dependencies on it, but that is not the case in the example I quote. 

Essentially, systemd is "crying wolf" over an error condition that is not critical and can be easily handled by issuing a warning and continuing. 

To reproduce this failure mode, it will be necessary to build a configuration with i.e. Windows 10 and a Linux build co-located on the same hardware [i.e. using disk partitioning] and with a shared NTFS partition. Have the NTFS partition to be auto-mounted via fstab, i.e. with 

UUID={your volume ID} /media/mountpoint ntfs defaults,umask=007,gid=46 0 1

Enter the Windows environment and use 

Control Panel > Power Options > System Settings to activate "Turn on fast start-up (recommended)". 

Shut down the windows environment. Now attempt to boot into the Linux environment. Systemd will fail when it attempts to mount the "unstable" NTFS partition. 

Removing the "fast-start" option resolves the problem with 100% reliability, so it is very easy to reproduce.

**Comment by boucman** [comment]
does the "nofail" mount option help in your case ?

**Comment by sproggit** [comment]
Hi - thank you for taking the time to post. In this use case I don't think it helps; because the file system is in a known-corrupt state [because Windows 10 now splits critical data sectors between the actual file system itself and the OS swap file area], I don't think I could even trust it in read-only mode. 

In terms of the issue, whilst it's true to say that Microsoft do seem to screw this up on average every 6 weeks or so, I don't consider that to be a major burden, since I don't use Windows so frequently [I just have to have it]. 

For me the issue is that systemd is not handling this failure mode correctly. Specifically, a corruption on a non-essential but mounted-at-boot file system warrants a clear warning and nothing more. It does most assuredly not warrant pushing the system in to "emergency mode". 

Hence [and I am a little concerned I'll be told this is not strictly the case] I have filed this as a bug.

**Comment by sproggit** [comment]
Sorry, just to clarify my previous answer... AFAIK, the "nofail" argument on the mount command basically says, "do not report errors for this device if it does not exist", i.e. it is designed as a handling mechanism for removable drives. In my case the failure mode is that the drive is still present, but reporting itself to be corrupt. So I need systemd to say, "Yo! Corrupted file system over here! I'll just carry on booting you a usable system, so you can check out this problem..." 

As opposed to just failing outright...

**Comment by boucman** [comment]
according to man:systemd.mount nofail means the generated mount unit is Wanted not Required

in other word: systemd will try to mount it, but if the mount fail, it will move on with normal boot. So it really seems to be what you are asking for.

**Comment by sproggit** [comment]
Ah! I am so sorry, I completely misunderstood. When I read your comment recommending that parameter, I went to the man pages for the *mount* command, where I find exactly that parameter with the feature as I described in my response to your suggestion. From your most recent post I now understand that systemd has also implemented the "nofail" argument, but chosen to have it mean something different. 

I was not aware of that option, so I guess I need to go and do some research in to how I might be able to use it. This might be a valid work-around. 

However - and sorry, I do not mean to come across as being argumentative - if this works, we now have two issues, not one. 

First, the original bug remains. What systemd does today *as the default response* is wrong. By default, it should raise a warning and keep going. The fact that you highlight that this option can re-introduce that behaviour shows how, instead of doing the "least surprising thing", systemd is doing an unexpected and unhelpful thing. 

Second, [and I may be wrong here] it looks from your explanation as though systemd makes use of a nofail argument but in doing so has it do something different from the nofail argument of the original Linux "mount" command. This, also, fails the "least surprising thing" test. [ Perhaps I have not fully understood - I will go and research some more]. However, if the "nofail" parameter is used by both "mount" and "systemd", but does different things between these two commands, then there is a fundamental issue here that needs to be resolved. Either systemd adapts it's operation to align with mount, and/or it changes the command parameter name which it uses to provide this functionality. 

As a matter of programming best practice it is dangerous [and IMHO wrong] to have the same parameter to mean two different things like that.

**Comment by poettering** [comment]
File systems listed in /etc/fstab marked as "fail" (the default) cause systemd to halt the boot process for, those marked as "nofail" do not cause that.

Depending on the distro sysvinit systems did or did not use to be this strict about insisting on correct configuration on this, but do note that this setting predates systemd by a long shot. We just enforce it fully.

If a file system is not marked as "nofail" we stop the boot, since proceeding to boot and permitting unprivileged code to run without these file systems around is possibly problematic as directory hierarchies below the relevant mount points are revealed that way that shouldn't be revealed. Moreover, incomplete execution environments possible trigger codepaths in privileged software that shouldn't be triggered (think: revert to default security policies, for example in polkit or so) unless the admin explicitly whitelisted that.

Note that mount always honoured "nofail" like this, however some sysvinit distributions then decided to ignore the mount exit code, after it failed. We are more strict there, but I think for good reasons.

The thinking here is really that more often than not the stuff listed in /etc/fstab is exclusively system-level stuff, such as /var and things, and we simply should not boot without those around by default).

Yes, this has come up before, and yes, some people disagree, but I am pretty sure that security wins in this case, and the behaviour is very logical I think, and covers the typical content of /etc/fstab much better. 

Sorry!

**Comment by sproggit** [comment]
Thanks Lennart,

Now that I better understand the context, I entirely agree with you: I think it is entirely reasonable for systemd to treat all file systems as essential unless the sysadmin explicitly configures the system otherwise. No concern from me on that point. 

However, I absolutely do take issue with the use of "nofail" as a systemd parameter, because this exactly matches a similar-but-different parameter associated with "mount". It would be bad enough if these two uses were not remotely related [at least an average user would be able to immediately spot and understand the discrepancy] but in this case the systemd use is "close but different" to the "mount" use. 

That is inexcusable. 

There are literally *no limit* to the choices that systemd had to use as a command-line parameter for this feature: things like "-quiet", or "-logonly". This would have given systemd all the functionality it needed without introducing easily-avoided confusion. 

Sadly I expect that systemd designers will tell me that there is no intention to change. 

I am grateful that you took the time to respond: thank you.
