### ISSUE TITLE
Screen orientation for Lenovo IdeaPad Miix 320

### ISSUE THREAD

**Issue by jdkbx** [systemd/systemd#7672]
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

Ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see

Detected orientation should match laptop orientation

### In case of bug report: Unexpected behaviour you saw

Orientation was incorrect (left/right swapped, normal/upside-down off by 90 degrees)

### In case of bug report: Steps to reproduce the problem

Tilt the laptop :-)

Through experimentation, I was able to find correct settings for ACCEL_MOUNT_MATRIX, which I put into 61-sensor-local.hwdb on my system. You may want to add them to the defaults:
```
sensor:modalias:acpi:*BOSC0200*:dmi:*:svnLENOVO*:pn80XF:*
 ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1
```

**Comment by poettering** [comment]
Please submit this as regular github PR, so that we can just merge it and this contribution is properly attributed to you, thanks!

cc @hadess

**Comment by jdkbx** [comment]
[Pull request 7707](https://github.com/systemd/systemd/pull/7707)
