### ISSUE TITLE
The assert at src/libsystemd/sd-device/sd-device.c#L681 fails if /sys is a symlink

### ISSUE THREAD

**Issue by urjaman** [systemd/systemd#7676]
### Submission type
 - Bug report

### systemd version the issue has been seen with
Still exists in the current master...

### Used distribution

Arch Linux ARM in a custom userspace container that
has /sys symlinked to /oldroot/sys - ok, i didnt
ask anyone to support this but crashing seems wrong.

### In case of bug report: Expected behaviour you didn't see
Not crashing.

### In case of bug report: Unexpected behaviour you saw
Crashing.

### In case of bug report: Steps to reproduce the problem
Launch spacefm with /sys a symlink to something that
doesnt start with /sys (i suppose).

**Comment by yuwata** [comment]
(I just simply have a question. Why the system makes /sys symlink to real sysfs instead of simply mounting sysfs? Maybe I lack some knowledge about something, but for me it seems very strange.)

**Comment by yuwata** [comment]
@urjaman I've created PR #7740 for this. But I have not tested it works or not. And I do not know this is a right way to fix this... If possible could you test the PR?
