### ISSUE TITLE
systemd-cryptsetup: "Numerical result out of range" on parsing keyfile-offset option

### ISSUE THREAD

**Issue by vladykin** [systemd/systemd#7677]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> systemd-cryptsetup successfully opening LUKS volume according to /etc/crypttab:
```
home	PARTUUID=...	/dev/disk/by-id/...		luks,discard,keyfile-offset=15664672768,keyfile-size=2048
```

Manually checking such config with cryptsetup without systemd wrapper succeeds:
```
cryptsetup -v luksOpen --test-passphrase --key-file=/dev/disk/by-id/... --keyfile-offset=15664672768 --keyfile-size=2048 /dev/disk/by-partuuid/...
```
(I store key in unallocated space after partition. That's why I point to keyfile as /dev/disk/by-id/... and supply a large keyfile-offset.)

### In case of bug report: Unexpected behaviour you saw

> Error message from systemd-cryptsetup and LUKS volume not opened:
```
systemd[1]: Starting Cryptography Setup for home...
systemd-cryptsetup[261]: Failed to parse keyfile-offset=15664672768, ignoring: Numerical result out of range
systemd-cryptsetup[261]: Failed to activate with key file '/dev/disk/by-id/...': Operation not permitted
```

### In case of bug report: Steps to reproduce the problem

> Supply a large keyfile-offset (not fitting in unsigned int) in /etc/crypttab

**Comment by poettering** [comment]
uh, yeah,we currently pass that as unsigned int, yuck.

(The libcryptsetup API is kinda broken there though, as it expects a size_t, which is still 32bit on 32bit systems, and for an on-disk offset that's just broken)

**Comment by keszybz** [comment]
https://gitlab.com/cryptsetup/cryptsetup/issues/359
