### ISSUE TITLE
systemd-nspawn: runnig virtualbox inside it

### ISSUE THREAD

**Issue by sant527** [systemd/systemd#7679]
I have archlinux and systemd-nspawn

```
#  systemd-nspawn --version                                                  
systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

```

I have created an archlinux container and run using:

`sudo /usr/bin/systemd-nspawn --bind=/var/cache/pacman/pkg --bind=/home/shared -bD /srv/container/Mycontainer
`
I have installed virtualbox inside my container.

Now if itry to run virtualbox from the container it says:

```
$ virtualbox
WARNING: The character device /dev/vboxdrv does not exist. Try
sudo /sbin/vboxconfig
and if that is not successful, try to re-install the package.

You will not be able to start VMs until this problem is fixed.
VirtualBox: supR3HardenedMainGetTrustedMain: dlopen("/usr/lib/virtualbox/VirtualBox.so",) failed: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

```

**Comment by mbiebl** [comment]
I'm not sure if VirtualBox actually supports running inside a container.
That said, you obviously need to create your chroot accordingly to have all necessary libraries installed so the software can run.
That's not a problem systemd-nspawn can solve for you.

**Comment by sant527** [comment]
How will systemd-nspawn solve in this case.

**Comment by mbiebl** [comment]
systemd-nspawn will not solve anything in this case as it is not its job to create the chroot.

**Comment by poettering** [comment]
> /dev/vboxdrv

I doubt that virtualbox works inside of containers. That said, if what it takes is making this device node available in containers, then --bind=/dev/vboxdrv on the nspawn cmdline should make it available. No idea if that's sufficient though, and I doubt it's safe.
