### ISSUE TITLE
PID 1 should not stop working on SIGILL/SIGABRT/etc unless the signal came from the kernel or PID 1 itself

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#7680]
### Submission type

- Bug report

### systemd version the issue has been seen with

> systemd 234
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

> Fedora 27

### In case of bug report: Expected behaviour you didn't see

> PID 1 logs `ABRT`, `ILL`, etc signals sent by `kill()` from other processes, but continues normal operation.

### In case of bug report: Unexpected behaviour you saw

> `kill -6 1` as root causes PID 1 to stop working

### In case of bug report: Steps to reproduce the problem

> Run `kill -6 1` as root

**Comment by poettering** [comment]
I am not sure I grok why you want us to ignore these signals? Only privileged clients can send them, it's highly unlikely people send them "by accident", and there's value in being able to send them for testing purposes.

What do you think we should protect against here?

**Comment by DemiMarie** [comment]
@poettering Mostly the case where someone gets put in an emergency shell and doesn’t really know what they should be doing, so they just try to kill everything and hope that PID 1 will do basically a “soft reboot”.  It is worth noting that the current behavior is an improvement over past behavior (PID 1 exit causing a kernel panic).

**Comment by poettering** [comment]
Well, I am not sure this really is something to protect against, it appears quite an exotic situation to me.

**Comment by DemiMarie** [comment]
@poettering On the other hand it is easy to detect this situation – the kernel provides all of the information we need.

**Comment by keszybz** [comment]
I agree with @poettering here that it's pointless to protect against something that cannot happen accidentally and requires full root privileges.
