### ISSUE TITLE
system incorrectly marked as tainted with var-run-bad if /var is on a separate partition

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#7683]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236

### Used distribution

Debian

On a system with /var on a separate partition, the system is incorrectly marked as tainted with
```System is tainted: var-run-bad```

The unmounted /var directory is empty so I guess systemd applies this check before /var has been mounted, which contains a proper /var/run → /run symlink

**Comment by poettering** [comment]
hmm, we actually check this whenever the string is shown or requested. The log message about it is done during early boot however. If you request the string later then it'll be correct in this regard...

The question is how to fix this best. One option would be supress the taint if /var is is entirely empty. Another option wouldbe to delay the log message until at least basic.target is done

**Comment by enihcam** [comment]
The 2nd option sounds reasonable.
