### ISSUE TITLE
Incorrect/unclear documentation on default of NoNewPrivileges=

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#7694]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236 git bf0e0a4df2d41a5631811f7db6b6c1c866c3ed80

### Used distribution

> Gentoo, Kernel 4.14.2

### In case of bug report: Expected behaviour you didn't see

> `NoNewPrivileges=` being set to `yes` when `PrivateDevices=yes`

### In case of bug report: Unexpected behaviour you saw

> `NoNewPrivileges=` defaults to `no`, although `PrivateDevices=yes` should imply `yes`

### In case of bug report: Steps to reproduce the problem

> 1. Create `/etc/systemd/system/privtest.service`:
>     ```INI
>     [Unit]
>     Description=Test for NowNewPrivileges issue
>     
>     [Service]
>     ExecStart=/bin/true
>     Type=oneshot
>     PrivateDevices=yes
>     ```
> 2. Reload: `systemctl daemon-reload`
> 3. Check effective service parameters: `systemctl show privtest | grep -e '\(NoNewPrivileges\|PrivateDevices\)'`:
>     ```
>     PrivateDevices=yes
>     NoNewPrivileges=no
>     ```

### Additional Information

> The [systemd.exec#NoNewPrivileges=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#NoNewPrivileges=) documentation states:
>> Defaults to false, but certain settings force NoNewPrivileges=yes, ignoring the value of this setting. This is the case when SystemCallFilter=, SystemCallArchitectures=, RestrictAddressFamilies=, RestrictNamespaces=, **PrivateDevices=**, ProtectKernelTunables=, ProtectKernelModules=, MemoryDenyWriteExecute=, or RestrictRealtime= are specified.
> 
> This does not reflect what can be observed here - I'd expect `NoNewPrivileges=` to be set to `yes` in case of `PrivateDevices=yes`.

**Comment by yuwata** [comment]
`systemctl show` does not show overridden values. I've added the explanation in PR #7697. Please take a look.

**Comment by eliasp** [comment]
@yuwata thanks a lot - LGTM!
