### ISSUE TITLE
systemd got a SIGFAULT and freeze when mount_load cgroup-cpuset.mount

### ISSUE THREAD

**Issue by hexiaowen** [systemd/systemd#7698]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 219

### Used distribution

> CentOS 7.4

### In case of bug report: Expected behaviour you didn't see

> systemd work fine

### In case of bug report: Unexpected behaviour you saw

> systemd freeze

### In case of bug report: Steps to reproduce the problem

> Cannot reproduce

dmesg:
[2016-01-16 00:00:37][   76.135644] systemd[1]: segfault at 8150 ip 000055bc8a50163a sp 00007ffd80213240 error 4 in systemd[55bc8a41b000+144000]
[2016-01-16 00:00:37][   76.136312] cgroup:cpu is already mounted or /cgroup/cpu busy
[2016-01-16 00:00:37][   76.137858] cgroup:cpuacct is already mounted or /cgroup/cpuacct busy
[2016-01-16 00:00:37][   76.141226] cgroup:memory is already mounted or /cgroup/memory busy
[2016-01-16 00:00:37]Caught <SEGV>, dumped core as pid 27069.
[2016-01-16 00:00:37]Freezing execution.

Program terminated with signal 11, Segmentation fault.
#0  0x00007f8cab3e16e7 in kill () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f8cab3e16e7 in kill () from /lib64/libc.so.6
#1  0x000055bc8a4c4643 in crash.2992 (sig=11) at src/core/main.c:168
#2  <signal handler called>
#3  base_bucket_scan.33968 (h=0x55bc8bfbcca0, idx=16, key=0x55bc8c03ba40) at src/shared/hashmap.c:1218
#4  0x000055bc8a4e8d88 in set_put (s=0x55bc8bfbcca0, key=0x55bc8c03ba40) at src/shared/hashmap.c:1266
#5  0x000055bc8a4fd1f3 in unit_require_mounts_for (u=0x55bc8c03ba40, path=<optimized out>) at src/core/unit.c:3642
#6  0x000055bc8a453b88 in mount_add_mount_links (m=0x55bc8c03ba40) at src/core/mount.c:254
#7  mount_add_extras.61496 (m=m@entry=0x55bc8c03ba40) at src/core/mount.c:501
#8  0x000055bc8a453f08 in mount_load.61514 (u=0x55bc8c03ba40) at src/core/mount.c:547
#9  0x000055bc8a45072f in unit_load (u=0x55bc8c03ba40) at src/core/unit.c:1205
#10 0x000055bc8a450cbe in manager_dispatch_load_queue (m=0x55bc8bf5e940) at src/core/manager.c:1393
#11 0x000055bc8a45b557 in mount_dispatch_io.61307 (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x55bc8bf5e940) at src/core/mount.c:1725
#12 0x000055bc8a4b7240 in source_dispatch (s=s@entry=0x55bc8bf67260) at src/libsystemd/sd-event/sd-event.c:2115
#13 0x000055bc8a4b969a in sd_event_dispatch (e=0x55bc8bf5ee20) at src/libsystemd/sd-event/sd-event.c:2472
#14 0x000055bc8a4946df in sd_event_run (timeout=18446744073709551615, e=0x55bc8bf5ee20) at src/libsystemd/sd-event/sd-event.c:2501
#15 manager_loop (m=0x55bc8bf5e940) at src/core/manager.c:2211
#16 0x000055bc8a43dd30 in main (argc=6, argv=0x7ffd80214258) at src/core/main.c:1791
(gdb) p *(Unit*)0x55bc8c03ba40
$2 = {manager = 0x55bc8bf5e940, type = UNIT_MOUNT, load_state = UNIT_LOADED, merged_into = 0x0, id = 0x55bc8bff3de0 "cgroup-cpuset.mount", instance = 0x0,
  names = 0x55bc8bfe6770, dependencies = {0x0 <repeats 12 times>, 0x55bc8bfe6800, 0x0, 0x55bc8bfe67d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bc8bfe67a0, 0x0},
  requires_mounts_for = 0x55bc8bf6c480, description = 0x55bc8bf74020 "/cgroup/cpuset", documentation = 0x0, fragment_path = 0x0,
  source_path = 0x55bc8c05b860 "/proc/self/mountinfo", dropin_paths = 0x55bc8c03b3c0, fragment_mtime = 0, source_mtime = 0, dropin_mtime = 1452873637031013, job = 0x0,
  nop_job = 0x0, job_timeout = 0, job_timeout_action = 0, job_timeout_reboot_arg = 0x0, refs = 0x0, conditions = 0x0, asserts = 0x0, condition_timestamp = {realtime = 0,
    monotonic = 0}, assert_timestamp = {realtime = 0, monotonic = 0}, inactive_exit_timestamp = {realtime = 0, monotonic = 0}, active_enter_timestamp = {realtime = 0,
    monotonic = 0}, active_exit_timestamp = {realtime = 0, monotonic = 0}, inactive_enter_timestamp = {realtime = 0, monotonic = 0}, slice = {unit = 0x0, refs_next = 0x0,
    refs_prev = 0x0}, units_by_type_next = 0x55bc8c02d6a0, units_by_type_prev = 0x0, has_requires_mounts_for_next = 0x0, has_requires_mounts_for_prev = 0x0,
  load_queue_next = 0x0, load_queue_prev = 0x0, dbus_queue_next = 0x55bc8c050ac0, dbus_queue_prev = 0x0, cleanup_queue_next = 0x0, cleanup_queue_prev = 0x0,
  gc_queue_next = 0x0, gc_queue_prev = 0x0, cgroup_queue_next = 0x0, cgroup_queue_prev = 0x0, pids = 0x0, sigchldgen = 0, gc_marker = 0, deserialized_job = -1,
  load_error = 0, unit_file_state = _UNIT_FILE_STATE_INVALID, unit_file_preset = -1, cgroup_path = 0x0, cgroup_realized_mask = 0, cgroup_subtree_mask = 0,
  cgroup_members_mask = 0, on_failure_job_mode = 1, stop_when_unneeded = false, default_dependencies = true, refuse_manual_start = false, refuse_manual_stop = false,
  allow_isolate = false, ignore_on_isolate = true, ignore_on_snapshot = false, condition_result = false, assert_result = false, transient = false, in_load_queue = false,
  in_dbus_queue = true, in_cleanup_queue = false, in_gc_queue = false, in_cgroup_queue = false, sent_dbus_new_signal = false, no_gc = false, in_audit = false,
  cgroup_realized = false, cgroup_members_mask_valid = false, cgroup_subtree_mask_valid = false}
(gdb) p *(Mount *)0x55bc8c03ba40
$3 = {meta = {manager = 0x55bc8bf5e940, type = UNIT_MOUNT, load_state = UNIT_LOADED, merged_into = 0x0, id = 0x55bc8bff3de0 "cgroup-cpuset.mount", instance = 0x0,
    names = 0x55bc8bfe6770, dependencies = {0x0 <repeats 12 times>, 0x55bc8bfe6800, 0x0, 0x55bc8bfe67d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55bc8bfe67a0, 0x0},
    requires_mounts_for = 0x55bc8bf6c480, description = 0x55bc8bf74020 "/cgroup/cpuset", documentation = 0x0, fragment_path = 0x0,
    source_path = 0x55bc8c05b860 "/proc/self/mountinfo", dropin_paths = 0x55bc8c03b3c0, fragment_mtime = 0, source_mtime = 0, dropin_mtime = 1452873637031013, job = 0x0,
    nop_job = 0x0, job_timeout = 0, job_timeout_action = 0, job_timeout_reboot_arg = 0x0, refs = 0x0, conditions = 0x0, asserts = 0x0, condition_timestamp = {realtime = 0,
      monotonic = 0}, assert_timestamp = {realtime = 0, monotonic = 0}, inactive_exit_timestamp = {realtime = 0, monotonic = 0}, active_enter_timestamp = {realtime = 0,
      monotonic = 0}, active_exit_timestamp = {realtime = 0, monotonic = 0}, inactive_enter_timestamp = {realtime = 0, monotonic = 0}, slice = {unit = 0x0,
      refs_next = 0x0, refs_prev = 0x0}, units_by_type_next = 0x55bc8c02d6a0, units_by_type_prev = 0x0, has_requires_mounts_for_next = 0x0,
    has_requires_mounts_for_prev = 0x0, load_queue_next = 0x0, load_queue_prev = 0x0, dbus_queue_next = 0x55bc8c050ac0, dbus_queue_prev = 0x0, cleanup_queue_next = 0x0,
    cleanup_queue_prev = 0x0, gc_queue_next = 0x0, gc_queue_prev = 0x0, cgroup_queue_next = 0x0, cgroup_queue_prev = 0x0, pids = 0x0, sigchldgen = 0, gc_marker = 0,
    deserialized_job = -1, load_error = 0, unit_file_state = _UNIT_FILE_STATE_INVALID, unit_file_preset = -1, cgroup_path = 0x0, cgroup_realized_mask = 0,
    cgroup_subtree_mask = 0, cgroup_members_mask = 0, on_failure_job_mode = 1, stop_when_unneeded = false, default_dependencies = true, refuse_manual_start = false,
    refuse_manual_stop = false, allow_isolate = false, ignore_on_isolate = true, ignore_on_snapshot = false, condition_result = false, assert_result = false,
    transient = false, in_load_queue = false, in_dbus_queue = true, in_cleanup_queue = false, in_gc_queue = false, in_cgroup_queue = false, sent_dbus_new_signal = false,
    no_gc = false, in_audit = false, cgroup_realized = false, cgroup_members_mask_valid = false, cgroup_subtree_mask_valid = false},
  where = 0x55bc8bf73d50 "/cgroup/cpuset", parameters_proc_self_mountinfo = {what = 0x55bc8bfcd900 "cgroup:cpuset", options = 0x55bc8bf6f580 "rw,relatime,cpuset",
    fstype = 0x55bc8bf6f1f0 "cgroup"}, parameters_fragment = {what = 0x0, options = 0x0, fstype = 0x0}, from_proc_self_mountinfo = true, from_fragment = false,
  is_mounted = true, just_mounted = true, just_changed = true, sloppy_options = false, result = MOUNT_SUCCESS, reload_result = MOUNT_SUCCESS, directory_mode = 493,
  timeout_usec = 90000000, exec_command = {{path = 0x0, argv = 0x0, exec_status = {start_timestamp = {realtime = 0, monotonic = 0}, exit_timestamp = {realtime = 0,
          monotonic = 0}, pid = 0, code = 0, status = 0}, command_next = 0x0, command_prev = 0x0, ignore = false}, {path = 0x0, argv = 0x0, exec_status = {
        start_timestamp = {realtime = 0, monotonic = 0}, exit_timestamp = {realtime = 0, monotonic = 0}, pid = 0, code = 0, status = 0}, command_next = 0x0,
      command_prev = 0x0, ignore = false}, {path = 0x0, argv = 0x0, exec_status = {start_timestamp = {realtime = 0, monotonic = 0}, exit_timestamp = {realtime = 0,
          monotonic = 0}, pid = 0, code = 0, status = 0}, command_next = 0x0, command_prev = 0x0, ignore = false}}, exec_context = {environment = 0x0,
    environment_files = 0x0, rlimit = {0x0 <repeats 16 times>}, working_directory = 0x0, root_directory = 0x0, working_directory_missing_ok = false, umask = 18,
    oom_score_adjust = 0, nice = 0, ioprio = 16384, cpu_sched_policy = 0, cpu_sched_priority = 0, cpuset = 0x0, cpuset_ncpus = 0, std_input = EXEC_INPUT_NULL,
    std_output = 4, std_error = 4, timer_slack_nsec = 18446744073709551615, tty_path = 0x0, tty_reset = false, tty_vhangup = false, tty_vt_disallocate = false,
    ignore_sigpipe = true, user = 0x0, group = 0x0, supplementary_groups = 0x0, pam_name = 0x0, utmp_id = 0x0, selinux_context_ignore = false, selinux_context = 0x0,
    apparmor_profile_ignore = false, apparmor_profile = 0x0, smack_process_label_ignore = false, smack_process_label = 0x0, read_write_dirs = 0x0, read_only_dirs = 0x0,
    inaccessible_dirs = 0x0, mount_flags = 0, capability_bounding_set_drop = 0, capabilities = 0x0, secure_bits = 0, syslog_priority = 30, syslog_identifier = 0x0,
    syslog_level_prefix = true, cpu_sched_reset_on_fork = false, non_blocking = false, private_tmp = false, private_network = false, private_devices = false,
    protect_system = PROTECT_SYSTEM_NO, protect_home = PROTECT_HOME_NO, no_new_privileges = false, same_pgrp = true, personality = 4294967295, syscall_filter = 0x0,
    syscall_archs = 0x0, syscall_errno = 0, syscall_whitelist = false, address_families = 0x0, address_families_whitelist = false, runtime_directory = 0x0,
    runtime_directory_mode = 493, oom_score_adjust_set = false, nice_set = false, ioprio_set = false, cpu_sched_set = false, no_new_privileges_set = false,
    bus_endpoint = 0x0}, kill_context = {kill_mode = KILL_CONTROL_GROUP, kill_signal = 15, send_sigkill = true, send_sighup = false}, cgroup_context = {
    cpu_accounting = false, blockio_accounting = false, memory_accounting = false, cpu_shares = 18446744073709551615, startup_cpu_shares = 18446744073709551615,
    cpu_quota_per_sec_usec = 18446744073709551615, blockio_weight = 18446744073709551615, startup_blockio_weight = 18446744073709551615, blockio_device_weights = 0x0,
    blockio_device_bandwidths = 0x0, memory_limit = 18446744073709551615, device_policy = CGROUP_AUTO, device_allow = 0x0, delegate = false}, exec_runtime = 0x0,
  state = MOUNT_DEAD, deserialized_state = MOUNT_DEAD, control_command = 0x0, control_command_id = _MOUNT_EXEC_COMMAND_INVALID, control_pid = 0, timer_event_source = 0x0,
  n_retry_umount = 0}

**Comment by yuwata** [comment]
Sorry, systemd 219 is too old. Please read [CONTRIBUTING.md](https://github.com/systemd/systemd/blob/master/.github/CONTRIBUTING.md). If you still have the problem in recent version, please re-open this.

**Comment by poettering** [comment]
@hexiaowen yes, please contact your downstream distribution for help on this. We only maintain current versions upstreams
