### ISSUE TITLE
systemd should warn if multiple Group= lines exist within a unit file

### ISSUE THREAD

**Issue by baconwaifu** [systemd/systemd#7700]
- Bug Report

systemd v235
Debian buster, systemd obtained via apt.

Actual: When multiple `Group=` lines are in a single unit file, the last one is used while the rest are *silently* ignored.

Expected: Systemd should at the very least warn that the the unit is malformed, and that preceding `Group=` lines will be ignored; possibly pointing the user towards `SupplementaryGroups=` in the process.

To reproduce: Make a unit with multiple `Group=` lines, check `systemctl status [unit]` for warnings, run the unit, and check the process' groups with `ps -oe pid,comm,supgrp`

**Comment by yuwata** [comment]
This behavior is commonly used and not only for `Group=`.
It is very useful for overriding vendor-provided unit files by drop-in `.conf` files.
So, this is not a bug and not fixed. Sorry.

**Comment by baconwaifu** [comment]
You are indeed correct that this behavior can be seen as useful in some cases. I agree that there shouldn't be a warning if another file contains a second instance of a parameter that overrides the one in the unit file. However, if you are modifying the unit file itself, modifying/removing the original line is not a problem. Multiple lines *in the same file* should trigger warnings.

**Comment by bl33pbl0p** [comment]
Maybe not. How about when an upstream unit ships with two Group= directives such as
> Group=nobody
> Group=nogroup
to use nogroup on debian and its derivatives and nobody on others.

**Comment by yuwata** [comment]
Hmm... Typically, unit files have about 20 or 30 lines at most. So, it is not hard to detect such a failure (?) by the user. Moreover, we cannot judge such a setting is actually a user failure or just a temporal intended setting. More and moreover, there are many settings which takes list of values, e.g. `After=`, and these are usually used several times in the same file. Please see some unit files in your system. Do you think that we should write such settings in one line? This breaks almost all already existing unit files in the world. It is not acceptable. Sorry.

**Comment by poettering** [comment]
I agree with @yuwata, I am not convinced we should complain here. Overriding earlier fields is definitely intended and documented usage and not a reason to complain. Not only do we have drop-in files, but we also have generated or transient unit files that are the combination of various sources, and it's entirely OK and expected that these make use of unit file setting overriding and extending.
