### ISSUE TITLE
systemd-sysctl fails if the kernel is missing NET_SCH_FQ_CODEL

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#7744]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236

### Used distribution

Gentoo
https://bugs.gentoo.org/642192

### Summary ###

If the running kernel does not support NET_SCH_FQ_CODEL, the systemd-sysctl service fails:

```
dic 25 01:32:00 dell-2017 systemd[1]: Starting Apply Kernel Variables...
dic 25 01:32:00 dell-2017 systemd-sysctl[299]: Couldn't write 'fq_codel' to 'net/core/default_qdisc': Input/output error
dic 25 01:32:00 dell-2017 systemd-sysctl[299]: Couldn't write '1' to 'kernel/sysrq', ignoring: No such file or directory
dic 25 01:32:00 dell-2017 systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
dic 25 01:32:00 dell-2017 systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
dic 25 01:32:00 dell-2017 systemd[1]: Failed to start Apply Kernel Variables.
```

It looks like it gets `EIO` when trying to write to `net/core/default_qdisc`.

Could this error be ignored?

**Comment by floppym** [comment]
The kernel seems to return -1 / ENOENT. I wonder where the EIO (Input/output error) is coming from...

```
openat(AT_FDCWD, "/proc/sys/net/core/default_qdisc", O_WRONLY|O_NOCTTY|O_CLOEXEC) = 3
fcntl(3, F_GETFL)                       = 0x8001 (flags O_WRONLY|O_LARGEFILE)
write(3, "fq_codel", 8)                 = -1 ENOENT (No such file or directory)
write(3, "\n", 1)                       = -1 ENOENT (No such file or directory)
close(3)                                = 0
writev(2, [{iov_base="Couldn't write 'fq_codel' to 'ne"..., iov_len=73}, {iov_base="\n", iov_len=1}], 2) = 74
```

**Comment by floppym** [comment]
From a gdb session, it looks like ferror() in fflush_and_check() is reporting an error, but errno is set to 0.
```
(gdb) step
write_string_stream_ts (f=0x555555758290, line=0x55555575c210 "fq_codel",
    flags=WRITE_STRING_FILE_DISABLE_BUFFER, ts=0x0) at ../src/basic/fileio.c:63
63                      struct timespec *ts) {
(gdb) next
65              assert(f);
(gdb)
66              assert(line);
(gdb)
68              fputs(line, f);
(gdb)
69              if (!(flags & WRITE_STRING_FILE_AVOID_NEWLINE) && !endswith(line, "\n"))
(gdb)
70                      fputc('\n', f);
(gdb)
72              if (ts) {
(gdb)
79              if (flags & WRITE_STRING_FILE_SYNC)
(gdb)
82                      return fflush_and_check(f);
(gdb) step
fflush_and_check (f=0x555555758290) at ../src/basic/fileio.c:1147
1147            assert(f);
(gdb) next
1149            errno = 0;
(gdb)
1150            fflush(f);
(gdb)
1152            if (ferror(f))
(gdb)
1153                    return errno > 0 ? -errno : -EIO;
(gdb) print errno
$5 = 0
```

**Comment by floppym** [comment]
Maybe we should have sysctl_write operate on a raw file descriptor to avoid losing the correct value for errno here.

**Comment by floppym** [comment]
I created a couple of PRs, either of which will resolve this issue. I think merging both of them is a good idea.

**Comment by poettering** [comment]
> write(3, "fq_codel", 8) = -1 ENOENT (No such file or directory) write(3, "\n", 1) = -1 ENOENT (No such file or directory)

Hmm, this suggests there's more wrong here actually, as stdio should have merged the two writes into one. It appears to me for some reason "block buffering" is turned off for the FILE*, and we really should correct that...

**Comment by floppym** [comment]
> Hmm, this suggests there's more wrong here actually, as stdio should have merged the two writes into one. It appears to me for some reason "block buffering" is turned off for the FILE*, and we really should correct that...

See #7755. The errno value returned from fputs is being ignored, and fflush_and_check() returns EIO instead.

**Comment by floppym** [comment]
Also, sysctl_write() passes `WRITE_STRING_FILE_DISABLE_BUFFER` to write_string_file, which disables buffering entirely.
