### ISSUE TITLE
systemd-networkd: Huge binary size increase

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#775]
The size of a stripped systemd-networkd binary has increased from 724K (in v222) to 8.8M (in v223).

This appears to be caused by commit 407af9dd8920e5cf4409b818b974a89bc013d5f8 in which a ~1 million element array is defined (ipv6_flowlabel_table).

**Comment by foutrelis** [comment]
cc @ssahani

**Comment by dvdhrm** [comment]
I suspect, this is `ipv6_flowlabel_table`. The only key used is `NETDEV_IPV6_FLOWLABEL_INHERIT`, which evaluates to `0xfffff == 1048575`.

@ssahani, @teg: Can you drop the int-to-string conversion and hard-code it instead? The string-to-int conversion is still fine, though.

**Comment by teg** [comment]
Yikes. @ssahani, you on this?

**Comment by ssahani** [comment]
ohhh .. I will fix it

**Comment by ssahani** [comment]
https://github.com/systemd/systemd/pull/778 added PR

**Comment by dvdhrm** [comment]
Fixed by #778. Thanks!
