### ISSUE TITLE
systemctl auth request in wrong locale

### ISSUE THREAD

**Issue by dimich-dmb** [systemd/systemd#7762]
### Submission type
 - Bug report

### systemd version the issue has been seen with
236

### Used distribution
Arch Linux

### Summary
On authentication request systemctl ignores LC_MESSAGES environment variable and uses LANG instead.

### Unexpected behaviour you saw
$ export LANG=uk_UA.utf8
$ LC_MESSAGES=en_US.utf8 systemctl stop ntpd
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
**Засвідчення потрібно, щоб зупинити «ntpd.service».**
Authenticating as: root
Password:

### Expected behaviour you didn't see
$ export LANG=uk_UA.utf8
$ LC_MESSAGES=en_US.utf8 systemctl stop ntpd
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
**Authentication is required to stop 'ntpd.service'.**
Authenticating as: root
Password:

**Comment by poettering** [comment]
These messages are printed by the PolicyKit agent, which is part of the PolicyKit package, and systemd is not directly involved (all we do is fork off the PK agent if if is available, and kill it when systemctl is done)

Please file a bug against policykit instead, as this needs to be fixed there.

**Comment by poettering** [comment]
(i sympathesize though, as I keep running into this myself actually all the time, but so far it didn't annoy me enough to do something about it. Hence by all means, please file a bug against polkit, and let's get this fixed there for good)

**Comment by dimich-dmb** [comment]
Thank you for the explanation. I'll try to reproduce the bug with pure polkit and report a bug to corresponding freedesktop team.
