### ISSUE TITLE
Failed to transfer image: Cannot set up /var/lib/machines, mkfs.btrfs is missing

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#7776]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux, Kernel 4.14.10

### In case of bug report: Expected behaviour you didn't see

machinectl pulling the TAR image.

### In case of bug report: Unexpected behaviour you saw

`# machinectl pull-tar https://mirrors.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2017.12.01-x86_64.tar.gz`
`Failed to transfer image: Cannot set up /var/lib/machines, mkfs.btrfs is missing`

### In case of bug report: Steps to reproduce the problem

1. Using a non-btrfs filesystem.
2. Not having btrfs-progs installed.
3. Having an empty /var/lib/machines/ directory.

The root filesystem is XFS in this case. I do not have `btrfs-progs` installed. Btrfs support in the kernel is as a module.

`CONFIG_BTRFS_FS=m`
`CONFIG_BTRFS_FS_POSIX_ACL=y`

**Comment by fbuihuu** [comment]
mkfs.btrfs is still needed even if your FS is not btrfs. In that case a loopback file with btrfs will be created and will be mounted on /var/lib/machines.

This in order to take advantage of some features of btrfs (subvolume, quota, ...).

So it's not a bug and you should install mkfs.btrfs.
T

**Comment by boucman** [comment]
Is this properly documented ? the error message is explicit enough that I would not consider that an error, but machinectl does depend on btrfs tools, and this should be somewhere in one of the packager-oriented doc files

Ask your distro, this sounds like a packaging bug for the package containing machinectl

**Comment by fbuihuu** [comment]
machinectl is usually part of the systemd main package. Assuming that a lot of users won't use machinectl at all, it doesn't sound right to put a strong requirement on btrfs-progs package in the systemd package.

**Comment by boucman** [comment]
some distro package machinectl and nspawn separately, thus my question..

**Comment by fbuihuu** [comment]
In this case it might make sense indeed.

**Comment by bl33pbl0p** [comment]
Thanks for the response, I was wondering why it was being used.

It could be documented in the README, since it is required, just as an optional dependency.

**Comment by poettering** [comment]
I think we should probably just drop the logic for this sooner or later. newer xfs has reflinks which isn't as good as proper subvol support but should get us close enough so that the benefits of btrfs there aren't clear enough to do the loop device logic...

**Comment by fignew** [comment]
RHEL/CentOS 8 no longer ship with btrfs-progs (not in epel either)

So nspawn is unusable.
