### ISSUE TITLE
hwdb: Add accelerometer information for WeTab

### ISSUE THREAD

**Issue by csaavedra** [systemd/systemd#7777]
The WeTab's screen is upside down so I think the accelerometor's rotation matrix needs to be added to the hwdb. I'm not sure what the right format for the entry would be nor the correct rotation matrix for a 180 degree rotation, but I'm glad to test this or provide any further info that might be needed.

Output of _udevadm info --export-db_:

> P: /devices/platform/asus_laptop/input/input9
E: ABS=7
E: DEVPATH=/devices/platform/asus_laptop/input/input9
E: EV=9
E: ID_FOR_SEAT=input-platform-asus_laptop
E: ID_INPUT=1
E: ID_INPUT_ACCELEROMETER=1
E: ID_PATH=platform-asus_laptop
E: ID_PATH_TAG=platform-asus_laptop
E: IIO_SENSOR_PROXY_TYPE=input-accel
E: MODALIAS=input:b0019v0000p0000e0000-e0,3,kra0,1,2,mlsfw
E: NAME="Pegatron Lucid Tablet Accelerometer"
E: PHYS="pega_accel/input0"
E: PRODUCT=19/0/0/0
E: PROP=0
E: SUBSYSTEM=input
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:seat:systemd:
E: USEC_INITIALIZED=23746998

> P: /devices/platform/asus_laptop/input/input9/event7
N: input/event7
S: input/by-path/platform-asus_laptop-event
E: DEVLINKS=/dev/input/by-path/platform-asus_laptop-event
E: DEVNAME=/dev/input/event7
E: DEVPATH=/devices/platform/asus_laptop/input/input9/event7
E: ID_INPUT=1
E: ID_INPUT_ACCELEROMETER=1
E: ID_PATH=platform-asus_laptop
E: ID_PATH_TAG=platform-asus_laptop
E: IIO_SENSOR_PROXY_TYPE=input-accel
E: LIBINPUT_DEVICE_GROUP=19/0/0:pega_accel
E: MAJOR=13
E: MINOR=71
E: SUBSYSTEM=input
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: USEC_INITIALIZED=23975417

> P: /devices/platform/asus_laptop/input/input9/js0
N: input/js0
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/platform/asus_laptop/input/input9/js0
E: ID_INPUT=1
E: ID_INPUT_ACCELEROMETER=1
E: ID_PATH=platform-asus_laptop
E: ID_PATH_TAG=platform-asus_laptop
E: IIO_SENSOR_PROXY_TYPE=input-accel
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: USEC_INITIALIZED=23906444

Output of _gdbus introspect --system --dest net.hadess.SensorProxy --object-path /net/hadess/SensorProxy_

> node /net/hadess/SensorProxy {
  interface org.freedesktop.DBus.Properties {
    methods:
      Get(in  s interface_name,
          in  s property_name,
          out v value);
      GetAll(in  s interface_name,
             out a{sv} properties);
      Set(in  s interface_name,
          in  s property_name,
          in  v value);
    signals:
      PropertiesChanged(s interface_name,
                        a{sv} changed_properties,
                        as invalidated_properties);
    properties:
  };
  interface org.freedesktop.DBus.Introspectable {
    methods:
      Introspect(out s xml_data);
    signals:
    properties:
  };
  interface org.freedesktop.DBus.Peer {
    methods:
      Ping();
      GetMachineId(out s machine_uuid);
    signals:
    properties:
  };
  interface net.hadess.SensorProxy {
    methods:
      ClaimAccelerometer();
      ReleaseAccelerometer();
      ClaimLight();
      ReleaseLight();
    signals:
    properties:
      readonly b HasAccelerometer = true;
      readonly s AccelerometerOrientation = 'bottom-up';
      readonly b HasAmbientLight = false;
      readonly s LightLevelUnit = 'lux';
      readonly d LightLevel = 0.0;
  };
  node Compass {
  };
};

**Comment by csaavedra** [comment]
@hadess

**Comment by hadess** [comment]
There are plenty of examples at:
https://github.com/systemd/systemd/pulls?utf8=%E2%9C%93&q=is:pr+accelerometer+

**Comment by poettering** [comment]
Lets close this here. Its not actionable for us as id. Would love to merge a patch for this but we need a submitted patch for this. Hence if you are still interested please prep a pr and we'll review and merge it. Thanks.

**Comment by mindmaster-it** [comment]
Hi
i got it working but i am not good at making a pr.

If somebody wants to do it here is the code

```
#########################################
# Wetab Pegatron accel
#########################################
evdev:input:b0019v0000p0000e0000*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0,-1, 0; 0, 0, 1
```

**Comment by keszybz** [comment]
The modalias match is supposed to match the parent, see the docs at the top of /usr/lib/udev/hwdb.d/60-sensor.hwdb.
