### ISSUE TITLE
xenial-amd64 tests are no longer useful

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#7781]
xenial-amd64 tests are no longer useful, please move that one to artful-amd64 as well.

**Comment by evverx** [comment]
I don't think those tests are no longer useful. Anyway, when I was trying to figure out [why `TEST-13-NSPAWN-SMOKE` had started failing](https://github.com/systemd/systemd/pull/8559#discussion_r176873712), I noticed that `xenial-amd64` tests had been turned off. Would it make sense to close the issue?
