### ISSUE TITLE
Default route from DHCP no longer set after upgrade 235.38 -> 236.0

### ISSUE THREAD

**Issue by thierer** [systemd/systemd#7792]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236.0

### Used distribution

Arch Linux

#### 235.38

```
> ip route
default via 192.168.165.1 dev enp3s0 proto dhcp src 192.168.165.5 metric 1024
192.168.165.0/24 dev enp3s0 proto kernel scope link src 192.168.165.5
192.168.165.1 dev enp3s0 proto dhcp scope link src 192.168.165.5 metric 1024
```

#### 236.0

```
> ip route
192.168.165.0/24 dev enp3s0 proto kernel scope link src 192.168.165.5
```

even though the route is apparently correctly received:

```
> journalctl -b -o cat -u systemd-networkd
Starting Network Service...
Enumeration completed
Started Network Service.
eth0: Interface name change detected, eth0 has been renamed to enp3s0.
enp3s0: IPv6 successfully enabled
enp3s0: Gained carrier
enp3s0: Gained IPv6LL
enp3s0: DHCPv4 address 192.168.165.5/24 via 192.168.165.1
enp3s0: Configured
```
 
### In case of bug report: Steps to reproduce the problem

```
> cat /etc/systemd/network/eth0.network
[Match]
Name=enp3s0

[Network]
DHCP=yes

[DHCP]
UseDomains=true
```

**Comment by ssahani** [comment]
I think you are missing https://github.com/systemd/systemd/pull/7432

**Comment by thierer** [comment]
Do you mean it should be fixed by https://github.com/systemd/systemd/commit/8dc787d185fe60beca3672d8b99f0eb87c80f8fb? But shouldn't that be in 236.0?

**Comment by ssahani** [comment]
yes . But I can't reproduce with current git.

**Comment by thierer** [comment]
Turns out I left out one important piece of information in my bug report, apologies for that: 

In my case the DHCP-Server sets an additional route via DHCP-Option 33 ("Static Route"). When I remove that option, the default route is set.

So https://github.com/systemd/systemd/commit/5f04a209eae0a2a04eb60fd7235b3fcdf3cc81ba does some collateral damage: #5695 is about DHCP-Option 121 ("Classless Static Route"; [RFC 3442](https://tools.ietf.org/html/rfc3442)) but https://github.com/systemd/systemd/commit/5f04a209eae0a2a04eb60fd7235b3fcdf3cc81ba breaks DHCP-Option 33 ("Static Route" from [RFC 2132](https://tools.ietf.org/html/rfc2132)), as routes from both options end up in the same array (`lease->static_route`) and the default route is discarded if any of them is set.

**Comment by ssahani** [comment]
isn't option 33 is deprecated ?

**Comment by thierer** [comment]
Well, RFC 3442 says so, but then again its point is making a case for option 121... I can't see a reason for not using it and it was working just fine for all my clients until systemd 236.0.

**Comment by poettering** [comment]
@ssahani if option 33 is used in the world we need to support it, it's that easy, regardless if deprecated or not.

**Comment by ssahani** [comment]
@poettering yes right but we first loop around and set all the routes . 

@thierer  Could you give me a dnsmasq conf . From the code we are extracting n routes that is all the routes. I cant see how that is happening really ?

**Comment by thierer** [comment]
@ssahani, sure. These entries to `dnsmasq.conf`

```
dhcp-option=option:router,192.168.0.1
dhcp-option=option:static-route,10.2.0.0,192.168.0.10
```

should result in these routes being set

```
default via 192.168.0.1
10.0.0.0/8 via 192.168.0.10
```

Which stopped working in 236, the default route is no longer set.

Sorry if I'm wrong, but your remarks about "looping around" and "extracting all routes" make me suspect you didn't understand the problem:

The problem is **not**, that any of the routes from options "static-route" (33) or "classless-static-route" (121) are not set - they are. (Which is a separate problem, I'll get to that).

The problem is that **if a route is set by option "static-route" (33) the default route set by option "router" (3) is discarded.**

IMHO that's wrong, because [RFC 3442](https://tools.ietf.org/html/rfc3442) only says this should happen when **"Classless Static Route" (121)** is used:

```
If the DHCP server returns both a Classless Static Routes option and
a Router option, the DHCP client MUST ignore the Router option.
```

Which brings me to my second point, because the RFC also states

```
Similarly, if the DHCP server returns both a Classless Static Routes
option and a Static Routes option, the DHCP client MUST ignore the
Static Routes option.
```

That's not happening, which you can test by using 

```
dhcp-option=option:router,192.168.0.1
dhcp-option=option:static-route,10.2.0.0,192.168.0.10
dhcp-option=option:classless-static-route,0.0.0.0/0,192.168.0.1,192.168.1.0/24,192.168.1.1
```

Following the rules of the RFC, this should only set the routes from the "classless-static-route" entry, but in fact the route from "static-route" (to 10.0.0.0/8) is also set.

To summarize, I see 3 problems with the current code:

1. When **only** the DHCP-option "static-route" (3) is provided (but no "classless-static-route" option is present), the route given by DHCP-option "router" (3) should still be used. Current behavior: The route from option 3 is discarded.
2. When the DHCP-option "classless-static-route" (121) is provided, **both routes given by options 3 and 33 should be discarded**. Current behavior: Only the route from option 3 is discarded, the route from option 33 is still used.
3. When any of the routes are discarded, there should be a warning (something like "Classless static route(s) set - ignoring router option as per RFC 3442") to make it easier to understand what's going on. Current behavior: The default route from option 3 is silently ignored.

**Comment by ssahani** [comment]
>Sorry if I'm wrong, but your remarks about "looping around" and "extracting all routes" make me suspect you didn't understand the problem:

The option code 121 and 33 both kept in a array . So we apply them while looping around it .

> When only the DHCP-option "static-route" (3) is provided (but no "classless-static-route" option is present), the route given by DHCP-option "router" (3) should still be used. Current behavior: The route from option 3 is discarded.

No we apply both of them I just added debug logs to test them .


> When the DHCP-option "classless-static-route" (121) is provided, both routes given by options 3 and 33 should be discarded. Current behavior: Only the route from option 3 is discarded, the route from option 33 is still used.

Yes we need to fix it 

> When any of the routes are discarded, there should be a warning (something like "Classless static route(s) set - ignoring router option as per RFC 3442") to make it easier to understand what's going on. Current behavior: The default route from option 3 is silently ignored.

Yes we will add.

**Comment by thierer** [comment]
> The option code 121 and 33 both kept in a array . So we apply them while looping around it .

Yes, but as I wrote, that's not the point...

> When only the DHCP-option "static-route" (3) is provided (but no "classless-static-route" option is present), the route given by DHCP-option "router" (3) should still be used. Current behavior: The route from option 3 is discarded.
> 
> No we apply both of them I just added debug logs to test them.

Really? Did you also check that the default route is actually set?

Because that's not what I'm experiencing, and looking at the code, I can't see how it would work:

This loop iterates through the routes picked up from both ["static-route" (option 33)](https://github.com/systemd/systemd/blob/1142cbd76a1db2adb2c382b76fc0a1c5a97c70cc/src/libsystemd-network/sd-dhcp-lease.c#L450-L492) and ["classless-static-route" (option 121)](https://github.com/systemd/systemd/blob/1142cbd76a1db2adb2c382b76fc0a1c5a97c70cc/src/libsystemd-network/sd-dhcp-lease.c#L495-L543): https://github.com/systemd/systemd/blob/5f04a209eae0a2a04eb60fd7235b3fcdf3cc81ba/src/network/networkd-dhcp4.c#L103-L124 

If at least one route got set by any of these two options, `link->dhcp4_messages` will be > 0, so the code block which sets the default route from option 3 is skipped: https://github.com/systemd/systemd/blob/2de2abad62d4f23f7d9af0c3871f9955896d085c/src/network/networkd-dhcp4.c#L135-L181.

**Comment by ssahani** [comment]
>When only the DHCP-option "static-route" (3) is provided (but no "classless-static-route" option is present), the route given by DHCP-option "router" (3) should still be used. Current behavior: The route from option 3 is discarded.

No we apply both of them I just added debug logs to test them.
Really? Did you also check that the default route is actually set?

I looked at option 3 not option 33 Sorry I misread. Of Course if any of them is there default route won't be applied. That was the commit we did for.

**Comment by thierer** [comment]
> That was the commit we did for.

I don't think so. #5695 ist about ignoring the default route **when option 121 is set** (which makes sense, because option 121 can also be used to set the default route, so the two could be in conflict). But https://github.com/systemd/systemd/commit/5f04a209eae0a2a04eb60fd7235b3fcdf3cc81ba also causes **the default route via option 3 to be ignored if (only) option 33 is set**. Which is neither required by RFC 3442 nor does it make sense, because option 33 can't be used to set the default route.

**Comment by ssahani** [comment]
hmm https://github.com/ssahani/systemd/commit/765b7bcdf9f9c41edc51c6340300fe1ed69d5163 Does this fixes your issue ?

**Comment by thierer** [comment]
I wasn't successful when trying to build a custom package of systemd for Arch, so I can't **test** it, but from looking at the patch I'd say that should be correct.

I still think there should be warnings when routes are discarded, but I'd consider my original issue as fixed. Thanks!
