### ISSUE TITLE
systemd-cryptsetup fails with LUKS2 in early userspace

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#7794]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v236

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Successfully boot the system.

### In case of bug report: Unexpected behaviour you saw

> Boot fails with: "Failed to start Cryptography Setup for \<name\>."

### In case of bug report: Steps to reproduce the problem

> Latest packages are built against `cryptsetup` 2.0.0, which supports new disk layout `LUKS2`. Acting on `LUKS2` requires locking, which is done in `/run/lock/cryptsetup/`. This directory is created by `systemd-tmpfiles-setup.service`, but missing in early userspace. Adding `systemd-tmpfiles-setup.service` to initcpio is not possible due to dependency conflicts (`systemd-tmpfiles-setup.service` is set to start after `local-fs.target`).

**Comment by poettering** [comment]
appears like a bug in libcryptsetup really, I am pretty sure it should be able to create what is missing in /run on-demand when it wants to be compatible with early boot environments...

**Comment by poettering** [comment]
Could you file a bug against libcryptsetup (and link it up here)?

**Comment by eworm-de** [comment]
Reported as [cryptsetup issue 362](https://gitlab.com/cryptsetup/cryptsetup/issues/362).

**Comment by poettering** [comment]
I think they should not use /run/lock at all btw, I doubt there's much value in it. They should just use /run/cryptsetup or so, and place their stuff in there.

**Comment by poettering** [comment]
Anyway, closing this here, as there's nothing much we can do about this here.

**Comment by eworm-de** [comment]
Just a short heads-up: `cryptsetup` upstream decided to switch default path to `/run/cryptsetup/`. As the last element of the path is created as a fallback (and `/run/` exists anyway) this also solves this issue.

**Comment by poettering** [comment]
Excellent! Thanks!
