### ISSUE TITLE
mount: Mounting any file system to a mount point in a directory that is bind mounted to itself will create an inactive mount unit.

### ISSUE THREAD

**Issue by rkolchmeyer** [systemd/systemd#7798]
### Submission type

 - Bug report

### systemd version the issue has been seen with

Observed on 235 and 236.

### Used distribution

I've seen this bug on both Debian buster/sid and Ubuntu 17.10.

### In case of bug report: Expected behaviour you didn't see

When mounting file systems with the 'mount' utility, it's expected that systemd will create an active mount unit associated with the mount point. This does not occur when file systems are mounted to mount points in directories that are bind mounted to themselves. Specifically, an inactive mount unit is created under these circumstances instead of an active mount unit.

### In case of bug report: Unexpected behaviour you saw

When mounting a file system to a mount point in a directory that is bind mounted to itself, systemd will create an inactive mount unit. One consequence of this is that when the file system is unmounted, the associated mount unit is not cleaned up/deleted.

### In case of bug report: Steps to reproduce the problem

In any directory, do the following:
\# mkdir -p bind-test/abc
\# mount --bind bind-test bind-test
\# mount -t tmpfs tmpfs bind-test/abc
\# systemctl list-units --all | grep bind-test  # Observe that the bind-test/abc mount unit is inactive

One consequence here is that unmounting bind-test/abc does not clean up the bind-test/abc mount unit:

\# umount bind-test/abc
\# systemctl list-units --all | grep bind-test  # Observe that the bind-test/abc mount unit still exists

**Comment by yuwata** [comment]
Confirmed.
```
$ mkdir -p /tmp/hoge/abc
$ sudo mount --bind /tmp/hoge /tmp/hoge
$ sudo mount -t tmpfs tmpfs /tmp/hoge/abc
$ cat /proc/self/mounts | grep hoge
tmpfs /tmp/hoge tmpfs rw,nosuid,nodev 0 0
tmpfs /tmp/hoge/abc tmpfs rw,relatime 0 0
tmpfs /tmp/hoge/abc tmpfs rw,relatime 0 0
```
I guess that the last duplicated line causes this problem.
