### ISSUE TITLE
Add support for scancodes emitted on KBC on Alienware systems with Alienware graphics amplifier

### ISSUE THREAD

**Issue by superm1** [systemd/systemd#78]
Some Alienware notebooks and desktops support an external graphics
housing called the "Alienware Graphics Amplifier". It allows the usage
of a larger or more modern graphics card than your gaming PC would
already support.  In order to provide a good experience, systems that
support it can provide notification to the OS via the scancodes on the
the keyboard controller of events related to the cable.

The following 4 events are supported (and the presumed OS response):
- Cable plugged in (An app on the existing display or terminal would
  tell the user to reboot the system to activate)
- Undock cable pressed (An app would let the user know to reboot the
  system to complete undock process; also when supported by GFX driver,
  driver can clean up and work without a reboot)
- Surprise removal of cable (System reboots).

Here's a patch for mapping these events to codes that can be recognized by a keycode Xorg can pick up.

```
From 747fa737562fd176d30ab8a79a82bd43fad06833 Mon Sep 17 00:00:00 2001
From: Mario Limonciello <mario_limonciello@dell.com>
Date: Wed, 27 May 2015 18:55:42 -0500
Subject: [PATCH] Add support for Alienware graphics amplifier

Unplugging and plugging in the cable will create various scancodes
on the keyboard controller.

Userspace within X should be able to interact with these to show
interesting messages. Assign them to generic prog1/prog2.

---
 hwdb/60-keyboard.hwdb | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/hwdb/60-keyboard.hwdb b/hwdb/60-keyboard.hwdb
index 9c7e553..0a0700c 100644
--- a/hwdb/60-keyboard.hwdb
+++ b/hwdb/60-keyboard.hwdb
@@ -144,6 +144,11 @@ evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAcer*:pnAOA*:pvr*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*
  KEYBOARD_KEY_8a=ejectcd

+evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*:pvr*
+ KEYBOARD_KEY_bf=!prog1                                 #graphics amplifier, cable plug-in event
+ KEYBOARD_KEY_c1=!prog2                                 #graphics amplifier, undock-button event
+ KEYBOARD_KEY_c2=!power                                 #graphics amplifier, surprise undock event
+
 ###########################################################
 # Asus
 ###########################################################
-- 
1.9.1
```

**Comment by zonque** [comment]
Could you please submit this as pull request?

**Comment by dvdhrm** [comment]
Merged.
