### ISSUE TITLE
nspawn private users not handled correctly with nftables

### ISSUE THREAD

**Issue by tYYGH** [systemd/systemd#7800]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236.0

### Used distribution

Up-to-date Archlinux (as of 2017-12-31)

### In case of bug report: Expected behaviour you didn't see

`sudo -u exim telnet smtp.bbox.fr 25` should be able to connect.

### In case of bug report: Unexpected behaviour you saw

`sudo -u exim telnet smtp.bbox.fr 25` times out.

### In case of bug report: Steps to reproduce the problem

The setup is such:
* Archlinux host
* Archlinux systemd-nspawn guest (named `seuil3`), launched with the standard `systemd-nspawn@.service` launcher, plus the following drop-in:
```
[Unit]
After=systemd-tmpfiles-setup.service

[Service]
ExecStart=
ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=guest -U --settings=override --machine=%i
TimeoutStartSec=300
TimeoutStopSec=300
```

By changing `-U` with `--private-users=0 --private-users-chown` in the drop-in, the above `telnet` works.

#### Host-specific configuration

`/etc/systemd/nspawn/seuil3.nspawn`:
```
[Exec]
NotifyReady=yes
Capability=CAP_NET_ADMIN

[Files]
Bind=/var/cache/pacman/pkg

[Network]
Bridge=wire
```

`/etc/systemd/network/wired.network`:
```
[Match]
Name=en*

[Network]
Bridge=wire
```

`/etc/systemd/network/bridge.netdev`:
```
[NetDev]
Name=wire
Kind=bridge
```

`/etc/systemd/network/bridge.network`:
```
[Match]
Name=wire

[Network]
IPForward=yes
Address=XXX.XXX.XXX.aaa/mm
Gateway=XXX.XXX.XXX.1
```

Outgoing nftables rules:
```
chain FilterOut {
  type filter hook output priority 0
  policy accept
}
```

#### Guest-specific configuration

`/etc/systemd/network/00-wired.network`:
```
[Match]
Name=host*
Virtualization=container

[Network]
Address=XXX.XXX.XXX.bbb/mm
Gateway=XXX.XXX.XXX.1
LLDP=yes
EmitLLDP=customer-bridge
```

Outgoing nftables rules:
```
chain FilterOut {
  type filter hook output priority 0
  policy drop
  ct state {established, related} accept
  meta oif lo accept
  ip daddr /* LAN, DNS, NTP… */ accept
  …
  meta skuid exim tcp dport 25 accept
}
```

**Comment by poettering** [comment]
Uh, and what do you think nspawn can do about that? I mean, we just use the kernel userns stuff, and don't fiddle at all with nftables ourselves. 

Not sure what you are suggesting us to do differently than we currently do? Have you reported this to nftables upstream?

**Comment by tYYGH** [comment]
Not sure either. I do not know user namespaces enough to see where the problem lies.

At the root of the problem, I suppose that the `skuid exim` part gets translated to `skuid <uid_number>`, and that the number used is the relative in-container number (eg. 79) instead of the absolute system-wide number (eg. 1006108751)…

I gather from your comment, that the problem is rather with nftables, or even maybe the kernel. I’ll try and open a bug report with nftables, first.
Thanks for your quick reply, though :-)

**Comment by poettering** [comment]
Ah, well, they are unlikely to be able to help you. the concept of "skuid" is not really compatible with userns really. nspawn picks the UID to use at first invocation, but nftables wants to enforce its rule earlier than that. Moreover when you specify "exim" as UID it will be looked up on the host user database, which of course is very different from the containers.

Or in other words: the nftables one one hand in combination with UNIX semantics on the other, as well as usern behaviour simply don't allow for what you're trying to do.

Sorry.

**Comment by tYYGH** [comment]
Errr, no ;-)
Here, my nspawn container is an “OS-kind” container, ie. a full Archlinux minus the kernel, but including systemd. So my container boots as any (modern) Linux OS boots.

So indeed, the userns gets decided at launch of the container, and exim’s system-wide “real” UID is known only when this launch occurs. But the guest’s `nftables.service` is launched _by the container_’s init process (systemd), and thus comes after exim’s UID is known.

**Comment by tYYGH** [comment]
For reference: https://bugzilla.netfilter.org/show_bug.cgi?id=1210
