### ISSUE TITLE
Allow udev rules with comments at END of line

### ISSUE THREAD

**Issue by StormyOS** [systemd/systemd#7813]
### Submission type
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

219-30

### Used distribution

CentOS7, RHEL7, Oracle Linux 7 (OL7)

### RFE Text

Although all along, the udev/systemd MAN pages state that comments must be at START of line, the actual CODE, honored remarks to also be placed at END of line, in udev/systemd used in CentOS 5/6, RHEL5/6, OL5/6, etc, remarks "#" are honored at end of line with no errors...

In systemd used in CentOS7, RHEL7, Oracle Linux 7 (OL7) that is no longer the case, and code now blocks such remarks with an error: 

systemd-udevd: invalid key/value pair in file /etc/udev/rules.d/99-test.rules on line 1, starting at character 85 ('#')

For automation tools the ability to place remarks at END of line is a great help, b/c with much more certainty they can modify, add, or remove their (complex) rules, even if it's in a dedicated product file, still sysadmins (Humans) may move rules around, and remarks placed below/above then lose context.

As mentioned above, in all lines of RHEL5 and RHEL6 (and equivalent in other flavors), it was possible to have a "#" as a remark *not* directly at start of line, with one exception with a change of behavior appearing in RHEL5u11 which proposed this patch:

https://bugzilla.redhat.com/show_bug.cgi?id=1172049

The fix/change in RHEL7 should not be too involved (possibly 2-3 line change), in above RHEL5 case it was a 1 line change :)

If this is accepted, then man page should be changed as well.  In many other OS files, like /etc/hosts, fstab, etc. it IS possible to place remarks at END of line and the parsing rules trim them correctly.

**Comment by poettering** [comment]
Let's close this, for the same reasons as #15348
