### ISSUE TITLE
bug: show-environment doesn't properly quote values

### ISSUE THREAD

**Issue by james-lawrence** [systemd/systemd#7822]
arch linux systemd 236

show-environment munges the actual variable outputs. would expect the output to be correctly quoted.

```
cat ~/.config/environment.d/test.conf
TEST_VAR1="foo bar"
echo $(systemctl --user show-environment | grep -i test | xargs)
TEST_VAR1=$foo bar
```

**Comment by poettering** [comment]
This is by design, see 804ee07c13 for an explanation
