### ISSUE TITLE
"Predictable" interface names are different even tho kernel version and lspci is same

### ISSUE THREAD

**Issue by XANi** [systemd/systemd#7840]
Systemd version: 232-25 (debian stable)
Kernel version: 4.9.65-3+deb9u2

The config is pretty much indentical as all of them are under configuration management.
The NIC in question (one that gets detected as  ens1f2/3 on one and  enp5s0f2/3 on other) is also running on same firmware version on both. It is a same server model with NIC put in same PCIe slot in all nodes.
Needless to say it is royal pain in arse to have completely different names for same NIC on same server model when using configuration management as they can't run on same config.

Server A:

    [08:51:50]d1-fw-cache1:~☠ ip link sh
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: ens1f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 8c:7c:ff:20:9e:64 brd ff:ff:ff:ff:ff:ff
    3: ens1f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 8c:7c:ff:20:9e:65 brd ff:ff:ff:ff:ff:ff
    4: enp7s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
        link/ether f8:0f:41:f8:84:ae brd ff:ff:ff:ff:ff:ff
    5: enp7s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
        link/ether f8:0f:41:f8:84:af brd ff:ff:ff:ff:ff:ff

Server B (same model as A):

    [09:07:31]d1-fw-cache3:~☠ ip link sh
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: enp5s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 8c:7c:ff:20:94:32 brd ff:ff:ff:ff:ff:ff
    3: enp5s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 8c:7c:ff:20:94:33 brd ff:ff:ff:ff:ff:ff
    4: enp7s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
        link/ether f8:0f:41:f8:87:42 brd ff:ff:ff:ff:ff:ff
    5: enp7s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
        link/ether f8:0f:41:f8:87:43 brd ff:ff:ff:ff:ff:ff

lspci (no difference between the two):

    00:00.0 Host bridge: Intel Corporation Xeon E5/Core i7 DMI2 (rev 07)
    00:01.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 1a (rev 07)
    00:01.1 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 1b (rev 07)
    00:02.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 2a (rev 07)
    00:02.2 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 2c (rev 07)
    00:03.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 3a in PCI Express Mode (rev 07)
    00:05.0 System peripheral: Intel Corporation Xeon E5/Core i7 Address Map, VTd_Misc, System Management (rev 07)
    00:05.2 System peripheral: Intel Corporation Xeon E5/Core i7 Control Status and Global Errors (rev 07)
    00:05.4 PIC: Intel Corporation Xeon E5/Core i7 I/O APIC (rev 07)
    00:11.0 PCI bridge: Intel Corporation C600/X79 series chipset PCI Express Virtual Root Port (rev 05)
    00:16.0 Communication controller: Intel Corporation C600/X79 series chipset MEI Controller #1 (rev 05)
    00:16.1 Communication controller: Intel Corporation C600/X79 series chipset MEI Controller #2 (rev 05)
    00:1a.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #2 (rev 05)
    00:1c.0 PCI bridge: Intel Corporation C600/X79 series chipset PCI Express Root Port 1 (rev b5)
    00:1c.7 PCI bridge: Intel Corporation C600/X79 series chipset PCI Express Root Port 8 (rev b5)
    00:1d.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #1 (rev 05)
    00:1e.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev a5)
    00:1f.0 ISA bridge: Intel Corporation C600/X79 series chipset LPC Controller (rev 05)
    00:1f.2 SATA controller: Intel Corporation C600/X79 series chipset 6-Port SATA AHCI Controller (rev 05)
    00:1f.3 SMBus: Intel Corporation C600/X79 series chipset SMBus Host Controller (rev 05)
    00:1f.6 Signal processing controller: Intel Corporation C600/X79 series chipset Thermal Management Controller (rev 05)
    04:00.0 RAID bus controller: LSI Logic / Symbios Logic MegaRAID SAS 2108 [Liberator] (rev 05)
    05:00.0 Fibre Channel: Brocade Communications Systems, Inc. 1010/1020/1007/1741 10Gbps CNA (rev 01)
    05:00.1 Fibre Channel: Brocade Communications Systems, Inc. 1010/1020/1007/1741 10Gbps CNA (rev 01)
    05:00.2 Ethernet controller: Brocade Communications Systems, Inc. 1010/1020/1007/1741 10Gbps CNA (rev 01)
    05:00.3 Ethernet controller: Brocade Communications Systems, Inc. 1010/1020/1007/1741 10Gbps CNA (rev 01)
    07:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
    07:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
    09:00.0 PCI bridge: ASPEED Technology, Inc. AST1150 PCI-to-PCI Bridge (rev 02)
    0a:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 21)
    ff:08.0 System peripheral: Intel Corporation Xeon E5/Core i7 QPI Link 0 (rev 07)
    ff:08.3 System peripheral: Intel Corporation Xeon E5/Core i7 QPI Link Reut 0 (rev 07)
    ff:08.4 System peripheral: Intel Corporation Xeon E5/Core i7 QPI Link Reut 0 (rev 07)
    ff:09.0 System peripheral: Intel Corporation Xeon E5/Core i7 QPI Link 1 (rev 07)
    ff:09.3 System peripheral: Intel Corporation Xeon E5/Core i7 QPI Link Reut 1 (rev 07)
    ff:09.4 System peripheral: Intel Corporation Xeon E5/Core i7 QPI Link Reut 1 (rev 07)
    ff:0a.0 System peripheral: Intel Corporation Xeon E5/Core i7 Power Control Unit 0 (rev 07)
    ff:0a.1 System peripheral: Intel Corporation Xeon E5/Core i7 Power Control Unit 1 (rev 07)
    ff:0a.2 System peripheral: Intel Corporation Xeon E5/Core i7 Power Control Unit 2 (rev 07)
    ff:0a.3 System peripheral: Intel Corporation Xeon E5/Core i7 Power Control Unit 3 (rev 07)
    ff:0b.0 System peripheral: Intel Corporation Xeon E5/Core i7 Interrupt Control Registers (rev 07)
    ff:0b.3 System peripheral: Intel Corporation Xeon E5/Core i7 Semaphore and Scratchpad Configuration Registers (rev 07)
    ff:0c.0 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0c.1 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0c.2 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0c.3 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0c.6 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller System Address Decoder 0 (rev 07)
    ff:0c.7 System peripheral: Intel Corporation Xeon E5/Core i7 System Address Decoder (rev 07)
    ff:0d.0 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0d.1 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0d.2 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0d.3 System peripheral: Intel Corporation Xeon E5/Core i7 Unicast Register 0 (rev 07)
    ff:0d.6 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller System Address Decoder 1 (rev 07)
    ff:0e.0 System peripheral: Intel Corporation Xeon E5/Core i7 Processor Home Agent (rev 07)
    ff:0e.1 Performance counters: Intel Corporation Xeon E5/Core i7 Processor Home Agent Performance Monitoring (rev 07)
    ff:0f.0 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Registers (rev 07)
    ff:0f.1 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller RAS Registers (rev 07)
    ff:0f.2 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 0 (rev 07)
    ff:0f.3 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 1 (rev 07)
    ff:0f.4 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 2 (rev 07)
    ff:0f.5 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 3 (rev 07)
    ff:0f.6 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 4 (rev 07)
    ff:10.0 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 0 (rev 07)
    ff:10.1 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 1 (rev 07)
    ff:10.2 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 0 (rev 07)
    ff:10.3 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 1 (rev 07)
    ff:10.4 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 2 (rev 07)
    ff:10.5 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 3 (rev 07)
    ff:10.6 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 2 (rev 07)
    ff:10.7 System peripheral: Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 3 (rev 07)
    ff:11.0 System peripheral: Intel Corporation Xeon E5/Core i7 DDRIO (rev 07)
    ff:13.0 System peripheral: Intel Corporation Xeon E5/Core i7 R2PCIe (rev 07)
    ff:13.1 Performance counters: Intel Corporation Xeon E5/Core i7 Ring to PCI Express Performance Monitor (rev 07)
    ff:13.4 Performance counters: Intel Corporation Xeon E5/Core i7 QuickPath Interconnect Agent Ring Registers (rev 07)
    ff:13.5 Performance counters: Intel Corporation Xeon E5/Core i7 Ring to QuickPath Interconnect Link 0 Performance Monitor (rev 07)
    ff:13.6 System peripheral: Intel Corporation Xeon E5/Core i7 Ring to QuickPath Interconnect Link 1 Performance Monitor (rev 07)

NIC driver (again, no difference):

    [09:07:28]d1-fw-cache3:~☠ dmesg |grep QLo
    [    4.233308] bna: QLogic BR-series 10G Ethernet driver - version: 3.2.25.1
    [    5.509528] QLogic BR-series BFA FC/FCOE SCSI driver - version: 3.2.25.1
    [    5.736490] scsi host1: QLogic BR-series FC/FCOE Adapter, hwpath: 0000:05:00.0 driver: 3.2.25.1
    [    5.749759] scsi host2: QLogic BR-series FC/FCOE Adapter, hwpath: 0000:05:00.1 driver: 3.2.25.1

**Comment by arvidjaar** [comment]
> The config is pretty much indentical as all of them are under configuration management.
The NIC in question (one that gets detected as ens1f2/3 on one and enp5s0f2/3 on other) is also running on same firmware version on both. It is a same server model with NIC put in same PCIe slot in all nodes.

Slot based enumeration (`ensXXX`) is preferred over PCI topology based enumeration (`enpXXX`) if your firmware provides slot information. So your two servers are not identical; firmware behaves differently.

**Comment by XANi** [comment]
Wait, so *upgrading firmware* could change interface naming in system ?
That's horrific

10 sty 2018 2:30 PM "Andrei Borzenkov" <notifications@github.com>
napisał(a):

**Comment by poettering** [comment]
> Wait, so *upgrading firmware* could change interface naming in system ? That's horrific

Yeah, this stuff is only as good as the firmware allows this to be good. The firmware provided ids are supposed to be stable (that's what they are designed for), but the firmware can implement this ultimately in any way it wants, and even randomize them on every boot, contradicting its purpose.

udev uses the data if its available, and better server hw should be good at providing stable ids. Consider complaining to the vendor if the data is crap they provide.

The data udev uses can be looked at in /sys/bus/pci/slots/*/address, which is the firmware data as exposed by the kernel.

Anyway, closing this, as there's little what we can do about this.

**Comment by XANi** [comment]
Did somebody checked how common it is ? From what I've looked:

* some desktop got the "by path" enp* name for onboard one
* other got that correctly
* on one server we have
    * builtin as eno*
    * one PCIe slot as ens*
    * other PCIe slot as enp*
* other ones as in example in the ticket

And that's looking at just few machines out of ~200 (rest is still using old naming, mostly because with only 2 bonded nics eth0/1 are more predictable and easier to script around)

> Anyway, closing this, as there's little what we can do about this.

@poettering how about having only semi-reliable (I mean I hope it is 100% reliable but knowing my luck I'll find an exception...) way of identifying it, by path, be a default one, not 2nd fallback ? 

Because currently first 2 are basically useless once you get to a point where you are managing groups of machines via something like Chef or Puppet and not just "a laptop" and want to have short name for only NIC in the system. 

And there is also the fact that just upgrading firmware can make a server inaccessible because interface names changed and config in system is still for "old" name is horrible and will torment poor souls that do not have HA in their architecture for years to come

**Comment by poettering** [comment]
> @poettering how about having only semi-reliable (I mean I hope it is 100% reliable but knowing my luck I'll find an exception...) way of identifying it, by path, be a default one, not 2nd fallback ?

pci topology can also change if the firmware likes. Since the "stable" firmware slot info only exists for being useful as "stable" markers we generally prefer that. 

You can use a different policy locally if you like, for example name things by MAC or so. See systemd.link(5) for details.

**Comment by poettering** [comment]
> And there is also the fact that just upgrading firmware can make a server inaccessible because interface names changed and config in system is still for "old" name is horrible and will torment poor souls that do not have HA in their architecture for years to come

There's no panacea here. We use the stuff we can use and which was created for this purpose like the firmware specs, but it all breaks down if the firmware is crap.

Sorry, we cannot synthesize stability where there simply are no stable identifiers, because the identifiers which are supposed to be stable are not due to bad firmware.

You can also turn off predictable naming entirely too btw, to return to the status quo ante. For the trivial case, where you only have a single iface this tends to give better results as the iface is always called "eth0"...

**Comment by XANi** [comment]
MAC naming is whole other can of worms as then in configuration management backend, instead of just mapping "this server model have NICs named like this" I'd have to enumerate every single MAC in every single server, then map network config (VLANs/bonds etc) to it.

And it would still break if NIC died and someone replaced it.

> pci topology can also change if the firmware likes. Since the "stable" firmware slot info only exists for being useful as "stable" markers we generally prefer that.

Did you saw it in the wild somewhere (aside from "piece of hardware died and numbers changed") ? I'm wondering if I should plan for that too...

> You can use a different policy locally if you like, for example name things by MAC or so. See systemd.link(5) for details.

Seems like only option. I'll probably try to do it by driver which *might* be good enough as extra NICs we add to servers are usually extra 10Gbit connectivity 

> You can also turn off predictable naming entirely too btw, to return to the status quo ant
e. 

We've had that but after kernel upgrade order at boot changed, making server unbootable. Soo I switched to "new" naming, and here I am...

>For the trivial case, where you only have a single iface this tends to give better results as the iface is always called "eth0"...

Yeah, until you have VM that changes MAC for whatever reason (restore from backup, clone), then you get eth1 after reboot unless you remove persistent udev rules (which we do on VMs for that reason)...

Or just replace machine, move disk to new one, warranty replacement etc.

I've also had one VERY interesting case where (IIRC):

* eth0/1 were builtin
* eth2/3 was first/second interface on 4 port 1Gbit card
* eth4 was first interface on 10Gbit card
* eth5 was second interface on 10Gbit card
* eth6/7 were third/fourth interface on 4 port 1Gbit card (card was basically 2 2 port NICs on same board)

**Comment by floppym** [comment]
> Yeah, until you have VM that changes MAC for whatever reason (restore from backup, clone), then you get eth1 after reboot unless you remove persistent udev rules (which we do on VMs for that reason)...

systemd (and udev) have not supported generation of "persistent rules" for network interfaces for quite some time.

**Comment by poettering** [comment]
> Did you saw it in the wild somewhere (aside from "piece of hardware died and numbers changed") ? I'm wondering if I should plan for that too...

Yes, people have complained about this too.

**Comment by poettering** [comment]
> systemd (and udev) have not supported generation of "persistent rules" for network interfaces for quite some time.

iirc debian patches it back in (which I am very sure is a very bad idea)

**Comment by XANi** [comment]
If by "patches it back" you mean the `70-persistent-net.rules`/`/lib/udev/write_net_rules` then it seems to be gone completely from current stable and by default new install gets the predictable naming
