### ISSUE TITLE
Improve documentation around systemd.journal-fields

### ISSUE THREAD

**Issue by mattes** [systemd/systemd#7841]
### Submission type

 - Request for enhancement (RFE)

[systemd.journal-fields](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html) states: 

> In some cases, fields may appear more than once per entry

I believe this should be clarified further. Which fields exactly can appear more than once?

I'm happy to update the docs, but need some guidance.

**Comment by keszybz** [comment]
Essentially any field. Trusted fields (those starting with "_") will not be added by journald multiple times, but it's possible to craft a journal file that contains them. Normal fields, controlled by the log entry submitter, may be specified multiple times without restrictions.

**Comment by mattes** [comment]
Thanks for the clarification. I see the following categories in the man page. 

* User Journal Fields
* Trusted Journal Fields (prefixed with `_`)
* Kernel Journal Fields (prefixed with `_`)
* Fields to log on behalf of a different program
* Address Fields (prefixed with `__`)

So unless someone crafts a journal file manually, is the following assumption correct?

Expect these fields to be set only once:
* Trusted Journal Fields
* Kernel Journal Fields
* Address Fields

Expect these fields to be set multiple times:
* User Journal Fields
* Fields to log on behalf of a different program
* (Any other fields)


I have a feeling User Journal Fields are usually just set once?

**Comment by mattes** [comment]
I wrote a [systemd-journal-remote](https://github.com/templarbit/systemd-journal-remote/blob/master/journal/entry.go) reader in Go and want to make sure I'm understanding the journald format correctly.

**Comment by keszybz** [comment]
Yes.

(Actually fields with `__` are generated on the fly, so they are singular, even with a crafted file.)

**Comment by mattes** [comment]
Great. I created a PR #8536. Can someone give me feedback on it?

**Comment by poettering** [comment]
#8536 was posted and then later closed. The reason for closing it should also apply to this issue, hence let's close this one too. Hope that makes sense.
