### ISSUE TITLE
systemd-gpt-auto-generator and no automount flag

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#7859]
Clarify in man/systemd-gpt-auto-generator.xml whether it honours the "do not mount attribute" mentioned at https://www.rodsbooks.com/gdisk/gdisk.html, or the "63 | No drive letter (i.e. do not automount)" basic data partition attribute from https://en.wikipedia.org/wiki/GUID_Partition_Table.

The documentation of systemd-gpt-auto-generator is otherwise unclear, whether the only way to disable automounting of a partition is to change its UUID.

**Comment by yuwata** [comment]
Only 60 "read only" and 63 "do not automount" are recognized except for ESP. For ESP, only 1 "ignore the content of the partition and not try to read from it" is used.

**Comment by dilyanpalauzov** [comment]
Thanks for the clarification.  This information shall be included in the documentation.

Moreover man/systemd-gpt-auto-generator says:

> Table 1. Partition Type GUIDs
> Name             |          Explanation
> Root Partition (x86)     |  On 32-bit x86 systems, the first x86 root partition on the disk the EFI ESP is located on is mounted to the root directory /.
> EFI System Partition (ESP) | The first ESP located on the disk the root partition is located on is mounted to /boot or /efi, see below.

This is hard to understand recursive definition: Root is mounted on the system where EFI ESP is located, and  EFI ESP is mounted on the partition, where the root partition is located.  The man page refers to https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/, which states "Note that automatic discovery of the root only works if the boot loader communicates this information to the OS, by implementing the Boot Loader Interface.".  The latter states: To find the partition where EFI ESP was loaded from, the the EFI variable LoaderDevicePartUUID must be set and only sd-boot sets it.

So all in all, systemd-gpt-auto-generator only works when sd-boot is used. and in particular not when the kernel is stared directly by the UEFI, without boot loader.  This shall be included in  man/systemd-gpt-auto-generator so that users do not try to make systemd-gpt-auto-generator running, when not using sd-boot.

**Comment by dilyanpalauzov** [comment]
if there is only one root partition and only one EFI System Partition oartitions, systemd-gpt-auto-generator shall consider them for mounting even if LoaderDevicePartUUID is not set (just because it is clear which EFI System Partition was used, if there is only one).

**Comment by keszybz** [comment]
I'll push a patch that documents the attributes.

> if there is only one root partition and only one EFI System Partition partition, systemd-gpt-auto-generator shall consider them for mounting even if LoaderDevicePartUUID is not set

That's a separate RFE. Maybe open a new issue.

**Comment by dilyanpalauzov** [comment]
i created #8561.

**Comment by dilyanpalauzov** [comment]
Can you also document, that in practice currently this only works with sd-boot, so that users can save their time if they use some different logic.
