### ISSUE TITLE
GetUnitByInvocationID does not return the correct unit object path

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#7867]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

$ busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/systemd_2djournald_2eservice org.freedesktop.systemd1.Unit InvocationID 
ay 16 44 157 241 100 173 133 70 60 164 83 203 31 159 42 207 68
$ busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnitByInvocationID ay 16 44 157 241 100 173 133 70 60 164 83 203 31 159 42 207 68
o "/org/freedesktop/systemd1/unit/systemd_2djournald_2eservice"

### In case of bug report: Unexpected behaviour you saw

$ busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/systemd_2djournald_2eservice org.freedesktop.systemd1.Unit InvocationID 
ay 16 44 157 241 100 173 133 70 60 164 83 203 31 159 42 207 68
$ busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnitByInvocationID ay 16 44 157 241 100 173 133 70 60 164 83 203 31 159 42 207 68
o "/org/freedesktop/systemd1/unit/_32c9df164ad85463ca453cb1f9f2acf44"

The only method available on that object is GetProcesses which does return the correct PID of systemd-journald.

### In case of bug report: Steps to reproduce the problem

same as above

**Comment by poettering** [comment]
the two paths refer to the same object actually, hence everything works the way it should really.

Note that units can have aliases (and often do), hence there are already multiple object paths for the same unit, and the one including the invocation ID is just one more.

Or did I miss what you are trying to say?

**Comment by bl33pbl0p** [comment]
Also, the only method available on the returned object is GetProcesses (afaics).

**Comment by bl33pbl0p** [comment]
Thanks! that makes sense!
