### ISSUE TITLE
man/systemd.journal-fields.xml: _TRANSPORT=stream

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#7870]
man/systemd.journal-fields.xml says:
>  _TRANSPORT= valid transports are audit, driver, syslog, journal, stdout, kernel

and
>  _STREAM_ID= Only applies to "_TRANSPORT=stream"

but _TRANSPORT=stream is not valid.  Likewise for _LINE_BREAK=.

**Comment by poettering** [comment]
BTW, a patch fixing this submitted as PR would be very welcome, and that way things would be properly attributed to you and everything!

**Comment by dilyanpalauzov** [comment]
I don't know how to fix this.

The further:  man/systemd-coredump > Description > 4th paragraph says:
  > By default, <command>systemd-coredump</command> will log the core dump including a backtrace if possible to the journal and store the core dump itself in an external file in <filename>/var/lib/systemd/coredump</filename>.

while man/coredump.conf states for Storage:
> When <literal>external</literal> (the default), cores will be stored in <filename>/var/lib/systemd/coredump/</filename>.

Hence the documentation is unclear, whether the default (external) stores if possible the core dump including a backtrace to the journal.

For coredump.conf.ProcessSizeMax= it is unclear, whether there is a default value of unlimited.

In man/systemd.offline-updates, "The logic", 3rd bullet:
> If so, it (temporarily and for this boot only) redirects (i.e. symlinks) <filename>default.target</filename> to <filename>system-update.target</filename>, a special target that is pulls in the base system (i.e. <filename>sysinit.target</filename> ...

"that is pulls" doesn't sound very English to me.

In man/systemd.link, from the documentation is not evident whether `off` is the default for `WakeOnLan=`.

In man/systemd.preset, section Example shall be called Examples, as it containts more of those, and in man/systemd.link or man/systemd.network the section is called "ExampleS".

**Comment by dilyanpalauzov** [comment]
man/systemd-coredump  and man/coredump.conf still provide contradictionary information on whether by default systemd-coredump will log the core dump including a backtrace if possible to the journal.

**Comment by keszybz** [comment]
I don't think there's a contradiction. "Log to the journal" just means logging about the coredump, not storing the whole core file.

**Comment by dilyanpalauzov** [comment]
man/systemd-coredump says:
> By default, systemd-coredump will log the core dump including a backtrace if possible to the journal and store the core dump itself in an external file in /var/lib/systemd/coredump.

This means, among other things, to store a backtrace to the journal.

man/coredump.conf says:
>  When "external" (the default), cores will be stored in /var/lib/systemd/coredump/.

Does the default include storing a backtrace to the journal?

Does the default ("external") include logging about the coredump in the journal?
