### ISSUE TITLE
Lot of simultaneously running systemd-nspawn containers cause the host to run out of threads

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#7879]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

Fedora 27

### In case of bug report: Unexpected behaviour you saw

After starting approx 120 nspawn containers the system runs into a software limitation.
New ssh connections are refused at one point.
Existing bash sessions create various forms of the same error:

```
pthread_create: Resource temporarily unavailable
/bin/sh: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
```

If the containers can be stopped, the system goes back to a normal state. If not, similar errors prevent any further operation, and the system has to be rebooted.

### In case of bug report: Steps to reproduce the problem

I assume it depends on container load, we observed this at around 3000 tasks reported by top.

**Comment by poettering** [comment]
Uh, well, what's your /proc/sys/kernel/pid_max?

By default on most distros that tunable is set to 32K, and puts a hard limit on the number of processes and threads running on the system.

Also, have you checked how many trheads/processes are reported on the system, and in particular reported on "machines.slice"

```
systemctl set-property -- -.slice TasksAccounting=1
systemctl set-property machine.slice TasksAccounting=1
systemctl status -- -.slice mchine.slice
```

**Comment by LaKing** [comment]
My /proc/sys/kernel/pid_max is 32768 

Currently I have rabout 50 containers running to keep the systems online. So these are the values from a reduced load.

```
● -.slice - Root Slice
   Loaded: loaded
   Active: active since Sun 2018-01-14 00:02:21 CET; 1 day 16h ago
     Docs: man:systemd.special(7)
   Memory: 34.6G
      CPU: 6h 26min 54.714s
   CGroup: /
...

● machine.slice - Virtual Machine and Container Slice
   Loaded: loaded (/usr/lib/systemd/system/machine.slice; static; vendor preset: disabled)
   Active: active since Sun 2018-01-14 00:02:26 CET; 1 day 16h ago
     Docs: man:systemd.special(7)
    Tasks: 11915
   Memory: 17.5G
      CPU: 1h 56min 16.818s
   CGroup: /machine.slice
...
```

A typical container reports something like
```
[root@d250 ~]# systemctl status -- -.slice machine.slice
● -.slice - Root Slice
   Loaded: loaded
   Active: active since Mon 2018-01-15 05:27:44 CET; 11h ago
     Docs: man:systemd.special(7)
    Tasks: 400
   Memory: 496.7M
      CPU: 1min 58.877s

```

In my desperation I was trying to unlimit the system 

```
# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515600
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
the default was 
```
max user processes              (-u) 289807

```
Containers have inside
```
open files                      (-n) 1024
```

But that didn't help.

Also, with about 10 containers, a "too many open files" limitation can be reached quickly, so I have a custom sysctl.conf in my /etc/sysctl.d with: 

```
fs.file-max = 2097152
fs.inotify.max_queued_events = 1048576
fs.inotify.max_user_instances = 1048576
fs.inotify.max_user_watches = 1048576

```

Would it be possible to raise those limits automatically with the number of nspawned containers?
Or should there be a limitation set manually after installation based on the hardware?
How can someone know how many containers the system can handle?

**Comment by LaKing** [comment]
I started a benchmarking test on a small VM. 8G ram, 6CPUs, containers without real load. 

At 80 containers the system got exhausted, while the CPU usage was minimal (0.2% total) the system got unresponsive without any error messages. I guess 8G ram was the culprit here. 

machinectl reports 6017 Tasks

```
● machine.slice - Virtual Machine and Container Slice
   Loaded: loaded (/usr/lib/systemd/system/machine.slice; static; vendor preset: disabled)
   Active: active since Wed 2018-01-17 07:16:30 CET; 58min ago
     Docs: man:systemd.special(7)
    Tasks: 6017
   Memory: 7.1G
      CPU: 51min 21.168s

```
ps aux, and top reported 1710 at the same time
```
top - 08:14:38 up 58 min,  4 users,  load average: 638,73, 490,54, 255,68
Tasks: 1710 total,   1 running, 1612 sleeping,   0 stopped,  13 zombie
%Cpu(s):  2,3 us, 14,6 sy,  1,9 ni, 47,7 id, 31,0 wa,  1,8 hi,  0,7 si,  0,0 st
KiB Mem :  8170528 total,   116872 free,  6992792 used,  1060864 buff/cache
KiB Swap:  8306684 total,        0 free,  8306684 used.   353464 avail Mem 
```

Not sure if relevant, but some containers had a supervisor running nspawn with relative high PIDs, 32670 for example.

The ~120 containers I had running had a real payload, they had web servers with traffic, with some PHP based sites that probably spawn many processes. As far as I understand the pid_max limitation comes from 32 bit CPU's, and it can be safely increased on 64 bit systems. The theoretical maximum is 4194304 for 64 bit.

@poettering Thank you for the hint. I understand the design much better now. Will simply increase pid_max in my sysctl.d file. Thanks!
