### ISSUE TITLE
systemd-networkd should accept a device as default gateway

### ISSUE THREAD

**Issue by drizzt** [systemd/systemd#788]
OpenVZ, by default, configures network inside a container to use a [venet](https://openvz.org/Virtual_network_device) device.

Since it's a point-to-point device (without ARP support) you can't put an IP as default gateway, but you have to add a route using the venet device as default route:
"ip route add default dev venet0"

Actually it's no possible to do that by using systemd-networkd, but you still need to create a sevice to launch the previous command or to use another networking manager.

I think it would be great to add the possibility to do that in systemd-networkd entirely.

**Comment by aaronp24** [comment]
I have the same problem. You can work around it by specifying Gateway=0.0.0.0 for IPv4, but the same trick doesn't seem to work for IPv6. Setting the route fails:
Apr 01 02:02:54 sd systemd-networkd[1097]: venet0          : could not set route: Invalid argument

**Comment by hexum** [comment]
Is there any progress on this bug?
Patch is outdated and it has conflicts with master.
