### ISSUE TITLE
timesyncd cannot start without nss-systemd enabled (and the service's user not registered in /etc/passwd either)

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#7883]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

systemd-timesync being able to start when libnss-systemd is not installed.

### In case of bug report: Unexpected behaviour you saw

systemd-timesyncd exits with: 

> Jan 15 08:58:09 foo systemd-timesyncd[563]: Cannot resolve user name systemd-timesync: No such process
> Jan 15 08:58:10 foo systemd[1]: systemd-timesyncd.service: Main process exited, code=exited, status=1/FAILURE
> Jan 15 08:58:10 foo systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.

### In case of bug report: Steps to reproduce the problem

Install a system where the systemd-timesync user does not exist, and libnss-systemd is not installed.

The problem seems to be that timesyncd tries to resolve the uid and gid of systemd-timesyncd user in order to support being as root and then drop privileges. However, that cannot ever happen when the systemd-timesync user does not exist: if the code is running as root, we are not running under systemd, and if we are not running under systemd then the user won't exist either.

Perhaps the code for supporting starting as root has outlived its usefulness?

**Comment by yuwata** [comment]
As documented in NEWS file, now, timesyncd unit sets `DynamicUser=`. So, libnss-systemd is required. If you want to run timesyncd without systemd, or libnss-systemd, then you need to create user and group systemd-timesync.

**Comment by fsateler** [comment]
> As documented in NEWS file, now, timesyncd unit sets DynamicUser=. So, libnss-systemd is required.

Note that DynamicUser=yes itself does not require libnss-systemd. The dynamic user will be generated, and the only problem would be that any tool that tries to get the name (like `ps`) will simply output a number.

The failure is caused by systemd-timesyncd itself requesting information it doesn't need (when running under systemd it won't drop privileges), and then failing when it can't get it.

**Comment by yuwata** [comment]
I see. OK I will submit a PR.

**Comment by poettering** [comment]
Hmmpf, so on one hand I am pretty sure that running DynamicUser= services without nss-systemd enabled should be considered "unsupported". OTOH I figure we should still handle such misconfiguration gracefully.

i would love to add another taint flag for systems that lack nss-systemd enabled, but I am not sure how we could ever implement that safely...

**Comment by poettering** [comment]
for debugging purposes I am very sure we should keep the setresuid() code in timesyncd btw... it's just so much simpler...

**Comment by fsateler** [comment]
Thank you @yuwata 

@poettering 

> for debugging purposes I am very sure we should keep the setresuid() code in timesyncd btw... it's just so much simpler...

Note that you will need the static user for that use case, otherwise the code will fail as well.
