### ISSUE TITLE
Access resouce-control collector over dbus.

### ISSUE THREAD

**Issue by tonobo** [systemd/systemd#7891]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> latest

### Used distribution

> debian

I'd like to access the collected metrics from resource-control over dbus. Currently i'm unable to find any documentation about it, i only able to fetch the static properties like MemoryMax.

**Comment by poettering** [comment]
There's stuff like "systemctl show -p TasksCurrent foo.service" for get the number of tasks. And there are more such props, such as "MemoryCurrent", "IPIngressBytes", "IPEgressBytes", "IPIngressPackets", "IPEgressPackets", "CPUUsageNSec=". The IO resource control stuff is not covered currently however.

What else are you precisely asking for?

**Comment by poettering** [comment]
Lets close this due to lack of response
