### ISSUE TITLE
Combine InaccessiblePaths with ReadOnlyPaths for a chroot equivalent

### ISSUE THREAD

**Issue by ludovic-gasc** [systemd/systemd#7895]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 236

### Used distribution

> Debian Stretch with Debian backports

### In case of bug report: Expected behaviour you didn't see

With systemd, I can combine ReadOnlyPaths and ReadWritePaths easily in whitelist mode, to block the writes in a folder except a sub-folder.

For example:
```
ReadOnlyPaths=/etc
ReadWritePaths=/etc/bind
```

### In case of bug report: Unexpected behaviour you saw

But now, to my understanding, it's impossible to have the same configuration to block also read access:
```
InaccessiblePaths=/etc
ReadOnlyPaths=/etc/bind
```

I don't think it's a bug but more a technical limitation: to be able to re-mount the folders, you need the parent folder, if I understand correctly the mechanism.

However, it might be interesting to implement a filter pattern, if it's technically possible:
```
InaccessiblePaths=/etc/*
ReadOnlyPaths=/etc/bind
```
The use case is to avoid to maintain a long list of InaccessiblePaths with a list of sub-folders, because it also means it will be necessary to update the blacklist paths each time we add a new daemon, for the case of /etc for example.

With this feature, it means it isn't necessary to create a special chroot folder and rebind all folders in it, nor to be sure that all read access rights are correct for each sub-folder available via the read access.

Thanks for your feedbacks.

**Comment by yuwata** [comment]
This can is done by using `BindPaths=` or `BindReadOnlyPaths=`. For example,
```
$ systemctl cat hoge.service
# /etc/systemd/system/hoge.service
[Service]
ExecStart=/bin/bash -c "ls -la /etc"
BindPaths=/dev/shm:/etc
BindPaths=/etc/systemd
```
```
Jan 17 04:06:21 systemd[1]: Started hoge.service.
Jan 17 04:06:21 bash[31077]: total 0
Jan 17 04:06:21 bash[31077]: drwxrwxrwt 3 0 0  60 Jan 16 19:05 .
Jan 17 04:06:21 bash[31077]: dr-xr-xr-x 1 0 0 142 Nov 17 11:38 ..
Jan 17 04:06:21 bash[31077]: drwxr-xr-x 1 0 0 346 Jan 15 16:05 systemd
```

**Comment by GMLudo** [comment]
Hi @yumata,

Thanks for your comment, it seems the right setting I need for my use case.
I will do tests tomorrow to validate that and close this issue if it's OK.

RegardS..

**Comment by yuwata** [comment]
Yeah, but the previous example is just a workaround. If /dev/shm is not empty, then the service can access files originally stored on /dev/shm. I think we may need to add, e.g, `EmptyDirectory=` or something. systemd already uses such function internally. So, it is not so hard to expose that as a unit option.

**Comment by yuwata** [comment]
@GMLudo I've created PR #7908.

**Comment by GMLudo** [comment]
Hi @yuwata,

Thank you a lot for your awesome work :+1: 
I think you have right, I need to test your configuration suggestion.
I will close this issue when I will test that.

Have a nice week.
