### ISSUE TITLE
Several cgroups not mounted when SELinux is enabled

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#7901]
Hi,

Since 236, all cgroups except `/sys/fs/cgroup/systemd` and `/sys/fs/cgroup/unified` are not mounted when SELinux is enabled (even in permissive) on my machine. Disabling SELinux completely restore these cgroups. (The policy is far from being 100% complete, but it shouldn't matter in permissive mode I believe)

Looking at the recent commits, I've found 8739f23e3c26bbf8b0296421578e56daa63cbf4b that looks suspicious. After reverting this commit the cgroups are back as well.

**Comment by KrissN** [comment]
I will try to reproduce this on my system.

In the meantime, can you check if you see anything suspicious in syslog?

**Comment by bigon** [comment]
@KrissN I don't see anything suspicious in the logs that could explain that.

I'll try to put systemd in debug logging and see if I've more info

**Comment by bigon** [comment]
```
jan 17 16:46:12 valinor systemd[1]: Relabelled /dev, /run and /sys/fs/cgroup in 26.517ms.
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/cpu,cpuacct of type cgroup with options cpu,cpuacct.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/cpu,cpuacct: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/perf_event of type cgroup with options perf_event.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/perf_event: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/devices of type cgroup with options devices.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/devices: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/memory of type cgroup with options memory.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/memory: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/freezer of type cgroup with options freezer.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/freezer: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/cpuset of type cgroup with options cpuset.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/cpuset: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/pids of type cgroup with options pids.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/pids: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/net_cls,net_prio of type cgroup with options net_cls,net_prio.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/net_cls,net_prio: No such file or directory
jan 17 16:46:12 valinor systemd[1]: Mounting cgroup to /sys/fs/cgroup/blkio of type cgroup with options blkio.
jan 17 16:46:12 valinor systemd[1]: Failed to mount cgroup at /sys/fs/cgroup/blkio: No such file or directory
jan 17 16:46:12 valinor systemd[1]: systemd 236 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid)
```

**Comment by KrissN** [comment]
Now, the syslog does shed some light on the matter...

The motivation of commit 8739f23 was the fact that the cgroup filesystem hierarchy was set-up before the SELinux policy was loaded. This resulted in the root cgroup filesystem to be incorrectly labelled. Since it was remounted read-only after having been set-up it was impossible to fix that later once the SELinux policy was loaded.

The log above tells a different story - here the relabelling occurs before the individual cgroup filesystems are mounted. Since the relabelling remounts the root cgroup filesystem back to read-only it is not hard to guess why mounting the remaining cgroup filesystems fails.

Something must have changed in the order of execution. I'll need to investigate what.

**Comment by bigon** [comment]
In git, `mount_setup()` (https://github.com/systemd/systemd/blob/master/src/core/main.c#L2499)  is called before `initialize_runtime()` (https://github.com/systemd/systemd/blob/master/src/core/main.c#L1908) which calls `mount_cgroup_controllers()` (https://github.com/systemd/systemd/blob/master/src/core/main.c#L1933)

So ASAICS, the cgroups are indeed mounted later

**Comment by bigon** [comment]
A bit later in the logs I also find:

```
jan 19 11:37:29 valinor systemd[1]: Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
jan 19 11:37:29 valinor systemd[1]: Unified cgroup hierarchy is located at /sys/fs/cgroup/unified. Controllers are on legacy hierarchies.
jan 19 11:37:29 valinor systemd[1]: Controller 'cpu' supported: no
jan 19 11:37:29 valinor systemd[1]: Controller 'cpuacct' supported: no
jan 19 11:37:29 valinor systemd[1]: Controller 'io' supported: no
jan 19 11:37:29 valinor systemd[1]: Controller 'blkio' supported: no
jan 19 11:37:29 valinor systemd[1]: Controller 'memory' supported: no
jan 19 11:37:29 valinor systemd[1]: Controller 'devices' supported: no
jan 19 11:37:29 valinor systemd[1]: Controller 'pids' supported: no
```

**Comment by KrissN** [comment]
I have tried to reproduce this on my system (Gentoo amd64).

With the original version of systemd, where I developed the patch (233) everything works. Seeing that the reported problem is most likely caused by the `/sys/fs/cgroup` filesystem being mounted read-only I have temporarily modified my patch by removing both `mount(MS_REMOUNT)` lines ([/src/core/mount-setup.c:401](https://github.com/systemd/systemd/blob/master/src/core/mount-setup.c#L401) and [/src/core/mount-setup.c:404](https://github.com/systemd/systemd/blob/master/src/core/mount-setup.c#L404)). The result was failure to apply SELinux labels:
```
systemd[1]: Unable to fix SELinux security context of /sys/fs/cgroup/cpuacct: Permission denied
systemd[1]: Unable to fix SELinux security context of /sys/fs/cgroup/cpu: Permission denied
```

I have installed systemd 236 without any patching from my side (although I must admit for some reason Gentoo devs have patched this version quite heavily) - the result was a properly labelled `/sys/fs/cgroup` directory and no errors in the log.

@bigon, it looks like your cgroup configuration is different in some way and the key to solve this is to understand the difference.

**Comment by bigon** [comment]
On this side, my machine is a pretty standard debian unstable one, no specific configuration regarding cgroups

**Comment by bigon** [comment]
FTR, the kernel here is `Linux valinor 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux`

**Comment by ranjanashish** [comment]
I had been having the same issue since last 2 weeks, and I was unable to run docker on my system. I was unable to figure out what was actually causing the problem. Finally after coming across this issue, and disabling SELinux on my Debian, as suggested by @bigon, the issue finally got resolved.

Thanks @bigon and Thanks everyone for systemd! I love it. <3

Sorry for digressing. @bigon How did you find that SELinux was causing issues? I would love to know this as I would like to debug such issues myself in the future.

**Comment by KrissN** [comment]
I'll try to install Debian over the weekend and reproduce it.

**Comment by bigon** [comment]
@ranjanashish When you have weird issues that nobody else have, it's always SELinux (/me hides)

**Comment by bigon** [comment]
@KrissN Thanks, tell me if you need help with something

**Comment by bigon** [comment]
You need more debugging from my side for this one? I can rebuild systemd with more output if you tell me where to look at

**Comment by bigon** [comment]
Removing that line https://github.com/systemd/systemd/blob/master/src/core/mount-setup.c#L404 (remount `/sys/fs/cgroup` read-only) and the other cgroups are back on my machine.

`/sys/fs/cgroup` is already remounted read-only at the end of `initialize_runtime()` so the remount rw and then remount ro dance seems to be useless for me.

TBH, the patch itself doesn't seems to be needed to me. On my machines (debian unstable), `/sys/fs/cgroup` and its content (even symlinks) end up being labeled as `cgroup_t` even with the patch reverted, not exactly sure why (policy maybe?).

**Comment by KrissN** [comment]
I've finally got time to install Debian unstable and I was able to reproduce this using kernel 4.15.0-1 and systemd-237.

I'll investigate what exactly happens there in what way is the set-up on Debian different from Gentoo.

**Comment by bigon** [comment]
Any news for this?

**Comment by poettering** [comment]
i figure you need to involve some folks who actually know selinux, and we as systemd upstreams don't quite qualify, as we only have a superficial understanding of selinux and require external patch submissions to keep it in shape...

**Comment by bigon** [comment]
@poettering There are two issues here, one is related to cgroup mounting and the other one is (or might be) a SELinux one.

For the 1st issue, AFAICS, the ordering between the code mounting the cgroups and https://github.com/systemd/systemd/commit/8739f23e3c26bbf8b0296421578e56daa63cbf4b has changed, that means that https://github.com/systemd/systemd/commit/8739f23e3c26bbf8b0296421578e56daa63cbf4b tries to remount the cgroups while they are not present yet and then makes /sys/fs/cgroup read-only preventing to mount them later, so revering @KrissN patch is a quick fix for my issue.

For the SELinux part, as said in https://github.com/systemd/systemd/issues/7901#issuecomment-365714679, I'm not sure the patch is needed at all, at least it's not on my machine (debian unstable). AFACT, testing if the patch is needed or not is pretty trivial, just needs check if all the directories in `/sys/fs/cgroup` are labeled with `cgroup_t`. Then we can see why we have difference between distributions and/or policies

**Comment by KrissN** [comment]
Ok, finally got some time to investigate this and the winner is... dracut.

On my Gentoo system I'm using dracut, which starts systemd already. In this case it's the dracut instance that mounts all the cgroup controllers, so by the time the main systemd process is up, all the cgroup hierarchy is already mounted, which means that the ``mount_cgroup_controllers`` function does nothing. In this scenario the cgroup filesystem hierarchy is mounted without SELinux labels and needs to be later relabelled. This is what my patch was for.

On Debian there is no dracut and the main systemd process needs to mount the cgroup filesystems. In this case the filesystems are mounted with the SELinux policy loaded and no relabelling is needed. That was until my patch went in, which assumed that the filesystems are all mounted and remounted everything read-only causing the later call to ``mount_cgroup_controllers`` to go wrong.

I think the easiest and least intrusive way to fix this will be to add some detection in ``mount_setup`` to check if the cgroup root filesystem is mounted read-only or read-write and only remount it back and forth if it is read-only and leave it as-is in the other case.
