### ISSUE TITLE
systemd-tmpfiles-setup.service should downgrade warnings due to EROFS to LOG_DEBUG 

### ISSUE THREAD

**Issue by jernst** [systemd/systemd#791]
See [discussion on mailing list](http://lists.freedesktop.org/archives/systemd-devel/2015-July/033544.html):

```
# /usr/bin/systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev
Failed to create file /sys/devices/system/cpu/microcode/reload: Read-only file system
```

@poettering opined: "We should probably handle this case in a nicer way, and downgrade EROFS error for cases like this."

**Comment by saivert** [comment]
Thanks to this I removed the package linux-firmware in my Arch Linux containers and got rid of this annoyance. This is essentially a question about what belongs in a container or not.

**Comment by keszybz** [comment]
I started looking into this, and downgrading all EROFS errors to debug level does not seem safe. After all people might rely on tmpfiles being executed properly for correctness. For example somebody might add some important tmpfiles snippets and schedule a service After= and Requires= systemd-tmpfiles-setup.service, or created their own tmpfiles service and rely on it reporting an error.

I think the correct solution is to make some of the lines "soft", and silently ignore those on EROFS. In the tmpfiles present in systemd we would mark lines which cannot cause incorrect function and in the worst case will cause some service to fail down the road (if it really needs them and is started).

Proposed syntax: add "-" after the letter:

```
q- /srv 0755 - - -
Q- /home 0755 - - -
```

This would apply to:
- /etc/mtab
- /etc/resolv.conf
- /home
- /srv
- /var/lib/machines
- /var/lib/systemd/coredump
- /var/cache
- /var/spool
- /var/log/journal permissions

and maybe some others. Those are all "nice to have" things which can be legitimately not present in a container or on a trimmed down system.

**Comment by poettering** [comment]
Yeah, such a syntax looks like a good idea, but I'd be more conservative with applying it to the existing rules than you I must say. I'd reduce the list you posted quite a bit. Write access to /var for example, should never ever fail, and hence the tmpfiles lins for anything it really shouldn't either...

**Comment by keszybz** [comment]
With the changes in PR #7419, EROFS would only result in a warning in logs, without causing the whole unit to fail. Is this enough of a solution for you? We could also take it one step further, and only warn about a single read-only mount-point once (make a set for ids, and after each EROFS error, look at the mount_id and either warn about it and add it the set if it wasn't there before, or do nothing).

I think this might be a better solution, more workable, then trying to decide for all tmpfiles configuration files, which lines are "important" and which are not, because that depends a lot on the context.

**Comment by poettering** [comment]
yeah, i guess downgrading those warnings and making the service non-fatal sounds ok

**Comment by poettering** [comment]
@keszybz btw, can we close this bug now? I think we can, right?

**Comment by keszybz** [comment]
Yeah. https://github.com/systemd/systemd/issues/791#issuecomment-346392753 has ideas for enhancements, but I think we're mostly OK now.
