### ISSUE TITLE
please document sd_journal_stream_fd as async-signal-safe, if it is

### ISSUE THREAD

**Issue by smcv** [systemd/systemd#7912]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

236

### Used distribution

Debian

sd_journal_stream_fd(3) is not documented to be async-signal-safe (see POSIX signal-safety(7)), making it unsafe (formally undefined behaviour in POSIX, I think) to call it between fork(2) and the following execve(2).

Last time I looked, the implementation did seem to be async-signal-safe. If so, please consider documenting that it is and will remain so.

dbus-daemon uses sd_journal_stream_fd() to give new stdout, stderr streams to traditional (non-systemd) activated services when running under systemd. However, because sd_journal_stream_fd() is not documented to be async-signal-safe, we call it before forking, so the _PID in the Journal is dbus-daemon's pid. If we knew sd_journal_stream_fd() would continue to be async-signal-safe indefinitely, we could call it in the child process (or in fact the grandchild process) that is going to exec the activatable service, which would make the _PID correct.

**Comment by sourcejedi** [comment]
Pedantry: you need an async-signal-safe function when you want to call it between fork() and exec() _in a program which has multiple threads_.  (No criticism of your real point; this seems reasonable to ask for).

**Comment by keszybz** [comment]
Oops. There's nothing wrong with #7938, but it documents the wrong function ;)
