### ISSUE TITLE
nspawn container vb-network interface naming collisions

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#7918]
### Submission type

 - Request for enhancement (RFE)

When nspawn containers are started where the first 10 characters of the machine are the same, ...
```
systemd-nspawn[12345]: Failed to add new veth interfaces (vb-commonnamed:host0): File exists
```  
.. and the container goes into failure.

As far as I remember this had been discussed here once already, but I could not find the thread.
I would be unhappy to fix this by using a different container name then desired, and can't find any relevant .network  configuration directives. 

Is there a possibility for an option to give interfaces a custom name? 
Or any suggestions for a workaround?

**Comment by carcokaresz** [comment]
Could this issue be fixed?

**Comment by poettering** [comment]
Duplicate of #10721.
