### ISSUE TITLE
Failed to bring loopback interface up: Success

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#7930]
Hi,

With systemd 236 (on debian) and with the debug output enabled, I see:

```
jan 19 11:37:29 valinor systemd[1]: Set hostname to <valinor>.
jan 19 11:37:29 valinor systemd[1]: Failed to add address 127.0.0.1 to loopback interface: Success
jan 19 11:37:29 valinor systemd[1]: Failed to add address ::1 to loopback interface: Success
jan 19 11:37:29 valinor systemd[1]: Failed to bring loopback interface up: Success
```
The failed == success looks a bit weird, this is maybe a bogus error message?

**Comment by poettering** [comment]
yeah, i guess we could improve this debug message to not suggests there was a failure where there is not...

fixing the log message should be trivial
