### ISSUE TITLE
timesyncd: tried to use more than 2 threads

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#796]
systemd-timesyncd tried to violate the NPROC hard limit of 2 (when trying to spawn the resolver). Unfortunately, this only happened once (the first time I booted systemd version 223) and I can't get it to happen again.

Version: 223 (with 6870b4156377 cherry picked).
Non-standard configure flags:

```
      --enable-lz4 \
      --enable-compat-libs \
      --disable-gnuefi \
      --disable-audit \
      --disable-ima \
      --disable-chkconfig \
      --disable-selinux \
      --disable-apparmor \
      --disable-smack \
      --disable-importd \
      --disable-qrencode \
      --disable-microhttpd \
      --disable-bootchart \
      --disable-quotacheck \
      --disable-resolved \
      --disable-efi \
      --disable-firstboot \
      --disable-libiptc  \
      --disable-coredump \
      --disable-terminal \
      --disable-hibernate \
      --disable-nls \
      --disable-utmp \
      --disable-kdbus \
```

Kernel: 4.1.3 (with grsecurity and tomoyo).
Os: Arch Linux

Sorry if this issue is a bit racy...

**Comment by kaysievers** [comment]
Who is seting a "NPROC hard limit of 2"?

**Comment by crrodriguez** [comment]
@kaysievers  us. in timesyncd.c line 117

**Comment by kaysievers** [comment]
Thanks!

https://github.com/systemd/systemd/commit/b506d3141b97d0a3fbda461f4b8d9d64f46408d1
