### ISSUE TITLE
Amazon: Unable to find systemd directory ec2

### ISSUE THREAD

**Issue by FazalHussain** [systemd/systemd#7961]
I am deploying my django application on aws ec2 but i am facing problem finding systemd path

I am on the /etc path 

[ec2-user@ip-xxx-xx-xx-xx etc]$ ls

https://gist.github.com/Fazalcs13/a16f76da1210cbc317b71d15e1f96507

where is systemd directory located???

Your answer will be highly appreciated!!!

**Comment by yuwata** [comment]
Please contact your distribution.
