### ISSUE TITLE
core: mount operations are not waited and system goes to emergency mode

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#7966]
### Submission type

 - Bug report

### systemd version the issue has been seen with

Recent snapshot after #7940 is merged.

### Used distribution

Fedora 27 x86_64

### In case of bug report: Expected behaviour you didn't see

systemd wait(?) mount operations.

### In case of bug report: Unexpected behaviour you saw

After #7940, my system does not boot correctly and goes to the emergency mode. In journal, I found
```
Jan 24 01:06:57 systemd[1]: usr-local-texlive.mount: Mount process finished, but there is no mount.
Jan 24 01:06:57 systemd[1]: usr-local-texlive.mount: Failed with result 'protocol'.
Jan 24 01:06:57 systemd[1]: Failed to mount /usr/local/texlive.
Jan 24 01:06:57 systemd[1]: Dependency failed for Local File Systems.
Jan 24 01:06:57 systemd[1]: local-fs.target: Job local-fs.target/start failed with result 'dependency'.
Jan 24 01:06:57 systemd[1]: local-fs.target: Triggering OnFailure= dependencies.
```
However, the directory is correctly mounted, and
```
$ systemctl status usr-local-texlive.mount
● usr-local-texlive.mount - /usr/local/texlive
   Loaded: loaded (/etc/fstab; generated)
   Active: active (mounted) (Result: protocol) since Wed 2018-01-24 01:06:57 JST; 7min ago
    Where: /usr/local/texlive
     What: /dev/sdb1
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 336 ExecMount=/usr/bin/mount /dev/sdb1 /usr/local/texlive -t btrfs -o defaults,discard,subvol=/texlive (code=exited, status=0/SUCCESS)
```
### In case of bug report: Steps to reproduce the problem

Build recent snapshot including #7940, and reboot.

**Comment by yuwata** [comment]
Note that this randomly occurs. Sometime boots fine, but sometimes not.

**Comment by yuwata** [comment]
\cc @sourcejedi

**Comment by poettering** [comment]
Hmm, this might be caused becuase so far we might possible end up processing multiple waitid() events in one go, before returning to the event loop and thus giving /proc/self/mountinfo processing a chance.

I fixed that bit in #7968 (originally in order to fix #7932), can you check if it makes things work for you?

**Comment by yuwata** [comment]
However, this does occurs not so frequently, unfortunately. So, I may not be possible to judge whether actually the PR fixes this or not. But, anyway, I will test it. Thanks.

**Comment by yuwata** [comment]
With #7968, I have not see this yet in several reboots. Thanks.

**Comment by sourcejedi** [comment]
Thanks to both of you!

I'm amazed this was implemented so quickly / was being worked at the exact same time.
