### ISSUE TITLE
Please support uid:gid in sysusers.d/*.conf

### ISSUE THREAD

**Issue by mvo5** [systemd/systemd#7967]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> git master (as of today)

### Used distribution

> Ubuntu

### RFE

The current sysusers.d mechanism is really nice. However when trying to to use it to (re)create the Debian/Ubuntu passwd file I hit the following issue: sysusers expects the same uid and primary gid. This is not the case for all entries in our passwd file, we have for example: `games:x:5:60:games:/usr/games:/usr/sbin/nologin`. 

One simple fix might be to extend the syntax of the sysusers file to allow: 
```
u name uid:gid geocs
```
This would allow me to write:
```
g games 60 -
u games 5:60 -
```
If the gid is not associated with an existing group this would fail with an error. This would also allow for the use-case when you want to create users but do not want to create a matching group.

If this sounds sensible and there is a chance that a patch for this would get accepted I can look into this. 

Thanks for your consideration!
 Michael

**Comment by poettering** [comment]
Hmm, I think it's a pretty poor choice to assign different UIDs and GIDs for user/group there. But sure, if this is what it takes, sounds like an acceptable patch to megre.

**Comment by mvo5** [comment]
Thanks! I much agree about the poor choice part, unfortunately the debian passwd master file is ancient so very hard to change. I pushed https://github.com/systemd/systemd/pull/7973 with a first version of the patch.

**Comment by yuwata** [comment]
Now #7973 is merged. Let's close this.
