### ISSUE TITLE
Support for blackhole, unreachable, prohibit route types

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#797]
networkd should support setting these special route types in a [Route] section.

One approach would be to add a new config file key RouteType (or just Type).
Another would be to overload the Gateway key to also accept these 3 possible route types.

more info about the types at http://man.devl.cz/man/8/ip-route#sect2

**Comment by gdamjan** [comment]
whatever happened to this commit  	f37e03c ?

**Comment by poettering** [comment]
@ssahani isn't this something for you to pick up maybe?

**Comment by ssahani** [comment]
yes this is also not bound to any interface. I will figure where we will fit this.

**Comment by flo-wer** [comment]
Would still fit in .network as IP rules are also not bound to an interface. If one wants to add this globally, you could still use a [Match] Name=lo or something.

**Comment by ssahani** [comment]
We need to close this as PR is merged.
