### ISSUE TITLE
journalctl --file=<file> exits error with 'Invalid argument' if file does not end in .journal

### ISSUE THREAD

**Issue by smoser** [systemd/systemd#7972]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Ubuntu 18.04

### In case of bug report: Expected behaviour you didn't see

> Expected `journalctl --file=file.txt` to behave the same as `journalctl --file=file.journal`

### In case of bug report: Unexpected behaviour you saw

> `journalctl --file=<file>` requires that &lt;file&gt; end in `.journal`.

### In case of bug report: Steps to reproduce the problem
    $ cp /run/log/journal/*/system.journal out.txt
    $ file out.txt
    out.txt: Journal file, online
    $ journalctl --file=out.txt
    Failed to open files: Invalid argument
    $ echo $?
    1
    $ mv out.txt out.journal
    $ journalctl --file=out.journal | head -n 3
    -- Logs begin at Tue 2018-01-23 13:58:48 EST, end at Tue 2018-01-23 13:58:55 EST. --
    Jan 23 13:58:48 x1 systemd-journald[58]: Runtime journal (/run/log/journal/) is 8.0M, max 796.3M, 788.3M free.
    Jan 23 13:58:48 x1 systemd-journald[58]: Journal started

**Comment by poettering** [comment]
Fix pending in #8013

**Comment by stueja** [comment]
This is an issue again in v242.
```
[jan@brick ~]# sudo cp /var/log/journal/remote/remote-192.168.1.2.journal out.txt
[jan@brick ~]# file out.txt 
out.txt: Journal file, offline
[jan@brick ~]# sudo journalctl -f out.txt
Failed to add match 'out.txt': Invalid argument

```

**Comment by vcaputo** [comment]
```
       -f, --follow
           Show only the most recent journal entries, and continuously print
           new entries as they are appended to the journal.

...

       --file=GLOB
           Takes a file glob as an argument. If specified, journalctl will
           operate on the specified journal files matching GLOB instead of the
           default runtime and system journal paths. May be specified multiple
           times, in which case files will be suitably interleaved.

```

**Comment by stueja** [comment]
Test blindness. Sorry.
