### ISSUE TITLE
Do not derive DNS query timeout from RTT

### ISSUE THREAD

**Issue by ott** [systemd/systemd#7974]
### Submission type
Request for enhancement (RFE)

### systemd version the issue has been seen with

master

### Description

At the moment systemd-resolved measures the RTT of DNS queries and adjusts its query timeout based on the RTT.  This makes only sense for iterative resolvers that query authoritative servers that have their zones in memory or on disk. A stub resolver like systemd-resolved sets the RD bit and forwards the query to an upstream resolver. The upstream resolver then tries to resolve the query under a timeout.

So the resend timeout of systemd-resolved should be _t_ +  _RTT_ where _t_ is the timeout of the upstream resolver and _RTT_ is the network RTT. systemd-resolved would have to measure _RTT_ separately and continously, for example with a query with an empty question section or a query for the SOA RR of the root zone. However, this requires significant changes to systemd-resolved. So it seems best to postpone them until #7617 has been addressed.

At the moment I would suggest to set resend timeout to a fixed value. BIND seems to use a timeout of 10 s, so perhaps 12 s is reasonable value. If we assume that the we are going to retry, it could be less. `DNS_SERVER_FEATURE_RETRY_ATTEMPTS` * `DNS_TIMEOUT_MAX_USEC` = 15 s at the moment. So it should be enough to set the resend timeout to `DNS_TIMEOUT_MAX_USEC`. I have a short patch prepared for this change and can submit a pull request if this change seems reasonable.

**Comment by ott** [comment]
There has been no response on whether a patch would be accepted. I think I will submit a pull request once #8849 has been merged. It might also solve #8451.

**Comment by poettering** [comment]
Yes, please submit a patch, would be happy to review!

**Comment by ott** [comment]
I submitted it as pull request #9264.
