### ISSUE TITLE
Cannot create bond0 with Systemd 236 and kernel 4.12.10 and 4.14.14

### ISSUE THREAD

**Issue by andi8086** [systemd/systemd#7976]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236
(234 works fine)

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

bond0 device existing

### In case of bug report: Unexpected behaviour you saw

bonding driver loaded with mode=0, but
* no /dev/bond0
* /proc/net/bonding empty

### In case of bug report: Steps to reproduce the problem

modprobe bonding mode=0

### Additional Information ###

Since the order of network interfaces is important to my bonding device, I use systemd to run a .sh script which sets up the network. I expect systemd to leave the "ip" command as well as "modprobe" functioning and not messing up with the system!

The unit is:
---------------------------------------------------------------------
```
[Unit]
Description=Quad Link Aggregation Init
Requires=network.target
After=network.target

[Service]
Type=simple
ExecStart=/etc/systemd/system/quadlan.sh
```
---------------------------------------------------------------------
The script is:
---------------------------------------------------------------------
```
### Load bond module (Round Robin)
# 
modprobe bonding mode=0

### Enable link of bond0 device
#
ip link set bond0 up

### Aggregate links
#
ifenslave bond0 enp5s0f0
ifenslave bond0 enp5s0f1
ifenslave bond0 enp6s0f0
ifenslave bond0 enp6s0f1

### Set IP Address
#
ip addr add 192.168.0.36/24 dev bond0

### Set Routing to ZFS Array
#
ip route add 192.168.0.44/32 dev bond0
```

**Comment by yuwata** [comment]
Please read comments in modprobe.d/systemd.conf. By default, systemd disables to create bond0.

**Comment by andi8086** [comment]
Thank you! I would have never found this, as I had no /etc/modprobe.d/systemd.conf.
Now I added one and specifically added
options bonding max_bonds=1
Now it works. How can systemd affect the module load options, if there is no config file in place?

**Comment by poettering** [comment]
it's installed to /usr/lib/modprobe.d/systemd.conf by systemd by default. There might be distros who do not ship this fragment however.

Anyway, closing, as this is fixed upstream, and if this doesn't work downstream then please ping your distro.
