### ISSUE TITLE
Shouldn't a "journalctl -f" use the proper sd_journal_*() APIs to handle file rotation as documented?

### ISSUE THREAD

**Issue by portante** [systemd/systemd#7998]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> master

### Used distribution

> n/a

### In case of bug report: Expected behaviour you didn't see

> code inspection does not appear to show the required `sd_journal_close()/sd_journal_open()` dance as documented at https://www.freedesktop.org/software/systemd/man/sd_journal_process.html#

### In case of bug report: Unexpected behaviour you saw

> A `journalctl -f` continuously tails the journal without leaking rotated journal file descriptors

### In case of bug report: Steps to reproduce the problem

> Create a logging load, observe that no file descriptors are leaked and that the code is not using the documented sequence.

**Comment by portante** [comment]
Here is a gist container a program to create a logging load on journal which results in file rotation, `loader`, and an example C program which shows the sequence necessary to properly tail the journal without duplicates or missing logs.

https://gist.github.com/portante/ff7fb429c6f973aab377f7bb77b0ffdb

**Comment by lnykryn** [comment]
I don't think it is necessary sd_journal_wait takes care of that.

**Comment by portante** [comment]
@lnykryn, I have compiled that example (see below, a cut and paste of what was compiled) and see it leaking file handles.

```
# cc -g2 -o posted_example posted_example.c -lsystemd
#include <stdio.h>
#include <string.h>
#include <systemd/sd-journal.h>

int main(int argc, char *argv[]) {
  int r;
  sd_journal *j;
  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  if (r < 0) {
    fprintf(stderr, "Failed to open journal: %s\n", strerror(-r));
    return 1;
  }
  for (;;)  {
    const void *d;
    size_t l;
    r = sd_journal_next(j);
    if (r < 0) {
      fprintf(stderr, "Failed to iterate to next entry: %s\n", strerror(-r));
      break;
    }
    if (r == 0) {
      /* Reached the end, let's wait for changes, and try again */
      r = sd_journal_wait(j, (uint64_t) -1);
      if (r < 0) {
        fprintf(stderr, "Failed to wait for changes: %s\n", strerror(-r));
        break;
      }
      continue;
    }
    r = sd_journal_get_data(j, "MESSAGE", &d, &l);
    if (r < 0) {
      fprintf(stderr, "Failed to read message field: %s\n", strerror(-r));
      continue;
    }
    printf("%.*s\n", (int) l, (const char*) d);
  }
  sd_journal_close(j);
  return 0;
}
```

**Comment by portante** [comment]
What we need is a way to have those file handles cleaned up when the other documented method of using `poll()` is used.

**Comment by portante** [comment]
So here is a clue: if I run the posted example above first, before any logging load is on the journal, and let the posted example churn through all the exist logs, then place a logging load on the journal, no file handles are leaked.

But if the posted example is not caught up, and file rotation happens, it leaks file descriptors until it does catch up, and then stops leaking them.

**Comment by msekletar** [comment]
> But if the posted example is not caught up, and file rotation happens, it leaks file descriptors until it does catch up, and then stops leaking them.

That happens because ```sd_journal_wait()``` handles inotify rm event and then closes fd associated with deleted file. Looking at your example you don't get to call ```sd_journal_wait()``` until you are caught up and iterated to the end of the journal.

**Comment by msekletar** [comment]
IOW, you have to get out of the iteration loop in order to realize that files are gone so you can clean up the fds.

**Comment by portante** [comment]
But when we do call sd_journal_wait(), we still leak file handles.

What is journalctl -f doing that the posted_example is not or should be doing?

**Comment by msekletar** [comment]
> But when we do call sd_journal_wait(), we still leak file handles.

Please post lsof and gdb output to prove that. This is not what see.

**Comment by lnykryn** [comment]
Well I don't see any leaked fds if I run your code.
My setup:
[root@qeos-14 ~]# while true; do echo baf | systemd-cat; sleep 1; done &
[root@qeos-14 ~]# while true; do kill -SIGUSR2 $(pidof systemd-journald); sleep 5; done &
[root@qeos-14 ~]# ./posted_example > /dev/null &
[root@qeos-14 ~]# strace -p $(pidof posted_example) 2>&1 | egrep 'open|close'

And I see that the fds are closed when the journal files are rotated

**Comment by msekletar** [comment]
> Please post lsof and gdb output to prove that. This is not what we see.

I meant gdb bt output (or pstack) showing posted example in sd_journal_wait() while it has leaked fds (should be visible from lsof output of that process).

**Comment by portante** [comment]
@lnykryn, that example looks like it sleeps once a second.  That means the the posted_example will catch up quickly.  Instead, if you have constant journal rotations happening, 10 MB files used by journal and a high logging rate, then you'll see the leak.

Here is what we are doing:
----
```
# # Docker is configured with journald logging driver
# docker run -d fedora seq -w 9999999999
# ./posted_example > /dev/null &
# watch -n 5 --diff 'ls -l /proc/$(pidof posted_example)/fd/* | grep "deleted"'
```

**Comment by portante** [comment]
Sorry, I should say that it is not leaking open file handles some how, but the clients using `sd_journal-*()` APIs are keeping files open that are on disk.

**Comment by msekletar** [comment]
Ahh, so basically you are always looping on ```sd_journal_next()``` and example never really calls ```sd_journal_wait()``` due to a constat stream of log data input. 

But eventually you should iterate to the end of the journal files you currently know about and once that happens you should eventually call ```sd_journal_wait()``` which in turn calls ```sd_journal_process()``` that  will handle inotify events caused by rotation and refresh your "view" on journal (currently present journal files).

**Comment by portante** [comment]
That does not appear to work.  :(

If you run the above example, you'll see that the `./posted_example` never lets go of those files, they remain on disks, even though they have been deleted.

**Comment by msekletar** [comment]
I am running the reproducer on fresh RHEL-7 VM and except using docker I used ```systemd-cat``` in order to dump ```seq``` output to journal and I don't see any deleted files opened by the example program. I also have strace attached to that process and I see it is doing close+open when journald does rotation. It behaves as I'd expected. Sorry, for not being very helpful.

**Comment by portante** [comment]
If we issued sd_journal_get_fd() right after sd_journal_open, that would
immediately establish the inotify setup, right?

Then a wait later would clean up, I bet.

**Comment by portante** [comment]
Have you tried letting the “seq” fill the journal up and start rotation
before you you run the posted example?

**Comment by portante** [comment]
I changed the "posted_example" to first call `sd_journal_get_fd()` in order to setup the inotify fd.  That seems to work where once the "posted_example" catches up with the end of the journal and calls `sd_journal_wait()`, call the deleted files are cleaned up.

This means one approach to be sure we do this sooner is to periodically call `sd_journal_process()` if we are in that loop.

Thoughts?

**Comment by portante** [comment]
And technically, there is a delay between the `sd_journal_open()` and `sd_journal_get_fd()`, which while small, stills leaves a window where a journal rotation can be leaked.

**Comment by portante** [comment]
So here is one possible solution for the "posted_example" to not leak file descriptors (and for that matter, to have journalctl -f not leak them either):

```
#include <stdio.h>
#include <string.h>
#include <systemd/sd-journal.h>

int main(int argc, char *argv[]) {
  int r;
  sd_journal *j;
  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  if (r < 0) {
    fprintf(stderr, "Failed to open journal: %s\n", strerror(-r));
    return 1;
  }
  r = sd_journal_get_fd(j);
  if (r < 0) {
    fprintf(stderr, "Failed to fetch inotify fd: %s\n", strerror(-r));
    return 1;
  }
  uint64_t count_processed = 0;
  for (;;)  {
    const void *d;
    size_t l;
    r = sd_journal_next(j);
    if (r < 0) {
      fprintf(stderr, "Failed to iterate to next entry: %s\n", strerror(-r));
      break;
    }
    if (r == 0) {
      /* Reached the end, let's wait for changes, and try again */
      r = sd_journal_wait(j, (uint64_t) -1);
      if (r < 0) {
        fprintf(stderr, "Failed to wait for changes: %s\n", strerror(-r));
        break;
      }
      continue;
    }
    r = sd_journal_get_data(j, "MESSAGE", &d, &l);
    if (r < 0) {
      fprintf(stderr, "Failed to read message field: %s\n", strerror(-r));
      continue;
    }
    printf("%.*s\n", (int) l, (const char*) d);
    if (count_processed % 10000 == 0) {
      r = sd_journal_process(j);
      if (r < 0) {
        fprintf(stderr, "Failed to process journal file changes: %s\n", strerror(-r));
        break;
      }
    }
  }
  sd_journal_close(j);
  return 0;
}
```

Notice that we immediately call `sd_journal_get_fd()` right after calling `sd_journal_open()` to minimize the window between the open files and those files that get deleted on rotation after the open but before "get_fd" is called, and notice that we periodically call `sd_journal_process()` every 10,000 or so messages to be sure we clean up file handles if the client has not called `sd_journal_wait()`.

@msekletar, @lnykryn, @nalind, please take a look if you have a chance.

**Comment by portante** [comment]
See also https://github.com/systemd/systemd/pull/8032, which highlights a problem with clients that get "paused" keeping file descriptors open.

**Comment by haraldh** [comment]
We see the same issue with systemd-236-4.git3e14c4c.fc28.x86_64 and https://github.com/varlink/io.systemd.journal/blob/master/src/main.c
```
$ ls -l /proc/5894/fd| wc -l
1023
```

after some ``` sd_journal_open()``` / ```sd_journal_close()```

**Comment by poettering** [comment]
@haraldh hmm, what makes you think that journald is at fault in that example? note that the code isn't really alright, you keep adding and removing invalid fds ("-24") to your epoll. it would make sense tracking down that first, before looking for a journal issue...

**Comment by haraldh** [comment]
@poettering : yeah, sorry, that code is buggy... doesn't close the journal in some cases.

**Comment by poettering** [comment]
#8144 should fix all remaining issues btw. forgot to link this up earlier...
