### ISSUE TITLE
seccomp: systemd passes x86-64 syscall nrs into functions that expect x32 ones, i386 ones, etc.

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8002]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236-663-g6c347d502

### Used distribution

Fedora 27

### In case of bug report: Unexpected behaviour you saw

```
[    8.999775] systemd[433]: Failed to add rule for system call n/a() / 156, ignoring: Numerical argument out of domain
```

### In case of bug report: Steps to reproduce the problem

1.  Boot with `systemd.log_level=debug`
2. Inspect `dmesg -u`. Look at the debug messages for the PID which turns into systemd-journald. (Or just search for "n/a").

### Code analysis

https://github.com/systemd/systemd/blob/7785da68e653adb6ef797ecd15f6aeaf67400237/src/shared/seccomp-util.c#L939

Syscall NR 156 on x86-64 (my OS' native arch) is `_sysctl()`, according to https://filippo.io/linux-syscall-table/

_sysctl() is deprecated ("Do not use this system call!"), so x32 chose to leave the syscall nr 156 unused.  So there's nothing to filter on x32.  We log a message... but is it a real problem?

It's true that x32 syscall NRs were set up to match x86-64 ones.  But systemd doesn't know that.  systemd doesn't have any code which thinks that it's specifically safe to pass x86-64 syscall NRs when we really mean x32 ones.  `seccomp_load_syscall_filter_set_raw()` just loops over each architecture and passes the same NRs for each of them.

---
---

Therefore systemd is also passing the same NR 156 when we set up the i386 seccomp filter.  But [32-bit x86 has completely different system call numbers](http://asm.sourceforge.net/syscall.html).  E.g. NR 156 is `sched_setscheduler()`, not `_sysctl()`.  The syscall NR for `_sysctl()` on 32-bit x86 is 149.

**Comment by sourcejedi** [comment]
Ideally, you want to store the syscalls as "interned" strings.  Unfortunately I don't know if seccomp will allow you access the full set of strings it already has.  E.g. whether `seccomp_syscall_resolve_num_arch()` will round-trip the "negative pseudo syscall number being returned in cases where the given syscall does not exist for the architecture".

**Comment by jgunthorpe** [comment]
I think I just hit this too.. Booting a x32 Debian user space under kvm with systemd 273 and kernel 4.15

I didn't see the warning message (didn't turn up the log_level), just the side effect of broken seccomp setup. The system is non-bootable.

Critical systemd components like journald, logind and udev are all killed with SIGSYS, presumably due to incorrect filtering configuration as described above.

Unfortunately systemd provides zero console debugging for this, basically just 'Failed to start journal' - no hint that it failed to start because it was killed due to SIGSYS. You can only see that from systemctl once the booted, but it won't boot.. Figured it out only via 'debug-shell.service' and 'strace -f -p 1'

For anyone Googling this will hack make systemd bootable on x32:

```sh
grep -r ^SystemCall /lib/systemd/system/ -l | xargs sed --in-place -e 's/^SystemCall/#SystemCall/g'
```

**Comment by sourcejedi** [comment]
Thanks for your confirmation!  I don't think we need any further info, but if you're curious, the specific failure message should be visible in `dmesg` if you boot with `printk.devkmsg=on`... _and_ use the latest systemd, v237, which includes #8025.

**Comment by sourcejedi** [comment]
Ah, I didn't think x32 would break though, I had guessed it would only fail for 32-bit x86 userspace (on 64 bit kernel).  It's possible there's another issue than the one I described.

I'm curious if you remember which system call failed, in the `strace` output.

**Comment by sourcejedi** [comment]
I also had a look at `SystemCallArchitectures=`.  It's handled in our function [seccomp_restrict_archs()](https://github.com/systemd/systemd/blob/7785da68e653adb6ef797ecd15f6aeaf67400237/src/shared/seccomp-util.c#L1530).  The function code baffles me, it doesn't look like it restricts anything at all.

---

The only seccomp action it uses is a constant SCMP_ACT_ALLOW.  So which action does it claim that we take when a disallowed arch is used?  Sending SIGSYS is only one of the possibilities. I can't see any hardcoded default in the libseccomp docs; you have to explicitly say what your default action is.

If there _was_ a hardcoded default action, which denied access to syscalls of archs which were not added to the filter.  Then `seccomp_load_syscall_filter_set_raw()` would not allow any syscalls at all (on x86-64 kernels).  Because it creates a separate filter for each arch supported by the kernel.

Also, `seccomp_init()` is documented as automatically including the native arch.  But we don't take any effort to remove that, before we add the configured list of archs.

**Comment by sourcejedi** [comment]
My initial analysis is wrong.

libseccomp just works like this.  You pass in NRs which may be native or pseudos (negative).  It applies them to each arch which has been added to the filter.  So it must lookup native NRs, as well as pseudo NRs, and convert them correctly for each arch.

The bug is in the debug message only.  I think it needs changing to always pass SCMP_ARCH_NATIVE to seccomp_syscall_resolve_num_arch().

I think we should close this bug and open a new one for the x32 failure reported by @jgunthorpe.

**Comment by sourcejedi** [comment]
Closed as my original issue has been fixed, and we opened a new issue for the report of SIGSYS crashes on x32, which turned out not to be related.
