### ISSUE TITLE
Document the semantics of fd passing in sd-bus

### ISSUE THREAD

**Issue by npmccallum** [systemd/systemd#8003]
I want to create a socketpair() and send one side of it to a remote process. When can I close the fd that I sent to the remote?

I tried to read through the code but ended up down lots of rabbit trails. It appears that the result of `sd_bus_send()` only puts the fd in the message in the output queue. So I figured a call to `sd_bus_flush()` would clear this queue so that I could `close()` the fd. But doing this just appears to break the socket pair.

Some advice here, and even some documentation, would be helpful. Thanks!

**Comment by npmccallum** [comment]
It appears that `sd_bus_flush()` does work, and I can `close()` the fd afterwards. However, I need to call `dup()` on the received fd on the client side. Documentation of the semantics of fd passing in general would be very helpful.

**Comment by poettering** [comment]
You don't have to keep it around at all. When you add it to the bus message it is duplicated (`fcntl(fd, F_DUPFD_CLOEXEC, 3`) and only the copy is kept. Thus, the caller can immediately close the fd it added to the message.

But yeah, we should document that officially somewhere.

**Comment by npmccallum** [comment]
It is onerous to expect the caller to dup() the FD. Can't this be done as part of parsing the response? I recognize this would cause a fd leak in existing implementation. But it would be nice to find a way to improve this.

**Comment by poettering** [comment]
> It is onerous to expect the caller to dup() the FD. Can't this be done as part of parsing the response? I recognize this would cause a fd leak in existing implementation. But it would be nice to find a way to improve this.

hmm? not following? what I was saying is that sd-bus internally duplicates the fd for you when you add it to a message, you don't have to do that.

Are you talking about getting fds out of a message again? In that case we indeed don't dup it for you, it remains member of the message, and if you want to keep it, then you have to dup it yourself.  But I think this behaviour makes a lot of sense, it's much like we handle this for strings too: if you add a string to a message we copy it there, but if you read it out of it we give you an internal ptr that you are supposed to copy on your own if you'd like to keep the data past the lifetime of the sd_bus_message object...

Or what are you saying?

**Comment by npmccallum** [comment]
I was talking about the case of getting the fd out of the message. There are a couple reasons why it is different.

1. You borrow a string from the message and this string is usable. If you borrow the fd, it isn't usable. Therefore you MUST dup().

2. From what I understand, gdbus doesn't require you to dup().

I'm not dogmatic on this point. If you want to keep the existing behavior, so be it. Just can we please document it? :)

**Comment by poettering** [comment]
> You borrow a string from the message and this string is usable. If you borrow the fd, it isn't usable. Therefore you MUST dup().

It's definitely useable I'd say... you only need to dup() it if you'd like to keep it for longer...

But yeah, definitely something to document
