### ISSUE TITLE
Can not disable systemd logging to console

### ISSUE THREAD

**Issue by oxniu** [systemd/systemd#801]
I am using systemd in Debian Jessie, and systemd outputs lots of messages during system boot

Jul 27 00:13:18 Rastes systemd[1]: systemd-tmpfiles-clean.service: main process exited, code=exited, status=1/FAILURE
Jul 27 00:13:18 Rastes systemd[1]: Failed to start Cleanup of Temporary Directories.
Jul 27 00:13:18 Rastes systemd[1]: Unit systemd-tmpfiles-clean.service entered failed state.
Jul 28 00:13:58 Rastes systemd[1]: systemd-tmpfiles-clean.service: main process exited, code=exited, status=1/FAILURE
Jul 28 00:13:58 Rastes systemd[1]: Failed to start Cleanup of Temporary Directories.
Jul 28 00:13:58 Rastes systemd[1]: Unit systemd-tmpfiles-clean.service entered failed state.
.....

I have tried to add kernel arguments to GRUB_CMDLINE_LINUX_DEFAULT like

systemd.log_target=/dev/null systemd.journald.forward_to_console=0 systemd.default_standard_output=null systemd.default_standard_error=null 

but systemd continue to output logging to console.

How to switch off logging into console? Thank you very much.

**Comment by poettering** [comment]
Well, the option would have to be `systemd.log_target=null`, not `systemd.log_target=/dev/null`

The canonical way to turn off boot-time output is to pass `quiet` on the kernel cmdline however, which turns off all logging by systemd itself, as well as the kernel.

But are you sure that it is systemd that forwards those messages? Do you have syslog daemon of some kind running (rsyslog, syslog-ng, traditional syslog)?

**Comment by oxniu** [comment]
Thanks, and I have changed systemd.log_target=null and quiet to kernel cmdline, but the messages still output to console. Then I added more arguments like systemd.journald.forward_to_wall=0, but also failed :(

Yes, I think it is systemd forwarding these messages. I tried to use cmdline like "systemd.log_target=console console=ttyS0,38400" to redirect the output, and the messages gone. I don't have any kind of syslog daemon.

**Comment by poettering** [comment]
maybe it's the kernel that forwards those messages through kmsg? Did you turn that off via `/proc/sys/kernel/printk`?

Do you have ForwardToConsole= set in journald.conf?

**Comment by oxniu** [comment]
Yes, I set kernel.printk = 0 0 0 0 in /etc/sysctl.conf and ForwardToConsole=no in journald.conf, but the output remained.

**Comment by poettering** [comment]
What does "systemctl show -a" output? Can you paste that here? (or on some pastebin and link it here?)

**Comment by oxniu** [comment]
```
$systemctl show -a
Version=215
Features=+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR
Virtualization=vmware
Architecture=x86-64
Tainted=
FirmwareTimestamp=
FirmwareTimestampMonotonic=0
LoaderTimestamp=
LoaderTimestampMonotonic=0
KernelTimestamp=Tue 2015-08-04 18:36:57 CST
KernelTimestampMonotonic=0
InitRDTimestamp=
InitRDTimestampMonotonic=0
UserspaceTimestamp=Tue 2015-08-04 18:36:59 CST
UserspaceTimestampMonotonic=2156435
FinishTimestamp=Tue 2015-08-04 18:37:04 CST
FinishTimestampMonotonic=7741407
SecurityStartTimestamp=Tue 2015-08-04 18:36:59 CST
SecurityStartTimestampMonotonic=2169118
SecurityFinishTimestamp=Tue 2015-08-04 18:36:59 CST
SecurityFinishTimestampMonotonic=2179675
GeneratorsStartTimestamp=Tue 2015-08-04 18:36:59 CST
GeneratorsStartTimestampMonotonic=2335774
GeneratorsFinishTimestamp=Tue 2015-08-04 18:37:00 CST
GeneratorsFinishTimestampMonotonic=2715257
UnitsLoadStartTimestamp=Tue 2015-08-04 18:37:00 CST
UnitsLoadStartTimestampMonotonic=2715951
UnitsLoadFinishTimestamp=Tue 2015-08-04 18:37:00 CST
UnitsLoadFinishTimestampMonotonic=3173953
LogLevel=emerg
LogTarget=null
NNames=159
NFailedUnits=3
NJobs=0
NInstalledJobs=76
NFailedJobs=3
Progress=6.90132e-310
Environment=LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ConfirmSpawn=no
ShowStatus=yes
UnitPath=/etc/systemd/system /run/systemd/system /run/systemd/generator /usr/local/lib/systemd/system /lib/systemd/system /usr/lib/systemd/system /run/systemd/generator.late
DefaultStandardOutput=null
DefaultStandardError=null
RuntimeWatchdogUSec=0
ShutdownWatchdogUSec=10min
ControlGroup=
SystemState=degraded
```

**Comment by poettering** [comment]
systemd 215 is really old. We usually only track more recent versions upstream. Could you please test this with a more modern version and see if the problem persists then?

**Comment by poettering** [comment]
(also, do you use plymouth or so?)

**Comment by oxniu** [comment]
Updated to Version=222 and I did not have plymouth , but the problem persists :-(.

**Comment by elkrejzi** [comment]
Might not be the same issue, but I saw that even with "quiet" kernel option, systemd will start outputting to the screen as soon as it hits an error (in my case, issue with kdbus and disabled systemd units that listen on dbus too). His problem is that systemd-tmpfiles-clean exits with error, and as soon as that happens, systemd will start outputting to console.

**Comment by poettering** [comment]
@elkrejzi You may control that part with the `systemd.show_status=` kernel cmdline option. If set to "auto" (the default) you get the behaviour you describe. You can also set it to "yes" and "no" to turn those messages on or off unconditionally.

**Comment by wodny** [comment]
Hi, I've encountered the same or a similar problem on Debian with systemd 226. A command run from rc.local exits with an error and I am endlessly informed about that fact on every TTY I switch to.

I've found three solutions/workarounds:
1. `systemctl restart systemd-journald` (without any configuration changes),
2. set `MaxLevelConsole=emerg` in journald.conf,
3. set kernel option `console=ttyS0,38400` (not a real solution).

I've also tried other methods mentioned in this thread but they didn't work.

What bothers me is that:
1. setting `ForwardToConsole=no` doesn't have any effect,
2. restarting journald causes it to lose a fd or something so it stops spamming consoles.

Would you agree that `ForwardToConsole` should work without resetting `MaxLevelConsole`?

BTW, how to check current settings of journald (read from all config files and merged)?

**Comment by poettering** [comment]
@oxniu is this still relevant? I notice now in your "systemctl show" output that ShowStatus= is on. This means you get the usual boot-time status output. Turn it off via systemd.show_status=0.

Does that fix your issue?

I'll close this bug, since it is pretty old, and filed against a very old version of systemd as of today. If this is still an issue in current systemd versions and systemd.show_status=0 doesn't fix it, then please reopen or comment.

**Comment by rosslagerwall** [comment]
In case anyone else runs into it, I also had this issue but for a different reason. I'd removed plymouth from the system but not properly regenerated the initramfs. So the file `/run/plymouth/pid` was still being created even though plymouth wasn't really running. This causes `plymouth_running()` to return true and systemd to unconditionally log status messages to the console (see `manage_get_show_status()`).

**Comment by pino-kim** [comment]
This issue is already close,
Anyone who meets the same issue like me, 
I append below kernel parameter and fix it. 
`systemd.show_status=0`

**Comment by jakob-tsd** [comment]
For posterity: You can do this at runtime by sending a signal to pid 1:

    kill -SIGRTMIN+21 1

Docs: https://www.freedesktop.org/software/systemd/man/latest/systemd.html#SIGRTMIN+21
