### ISSUE TITLE
logging is not thread safe v.s. log_close() - and we use threads

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8012]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236-611-g575b300b7

### Used distribution

Fedora 27

### Bug

https://github.com/systemd/systemd/blob/575b300b795b6765d66e0f351d80635c7d3addea/src/basic/log.c#L114

We use threads in a couple of places.  We are missing a massive disclaimer e.g. that if you open a file in that thread, it may be assigned the same file descriptor number that is still in `kmsg_fd`, and following log messages can go to the wrong fd.

In a couple of other places, we use `fork()` instead.  It would be really great if we could forbid the use of threads in PID 1!  And use `fork()` everywhere.

**Comment by poettering** [comment]
> We use threads in a couple of places. We are missing a massive disclaimer e.g. that if you open a file in that thread, it may be assigned the same file descriptor number that is still in kmsg_fd, and following log messages can go to the wrong fd.

There's the implicit assumption that log_open() and log_close() is not called in multi-threaded applications while there are other threads active that do logging. It's only safe to call log_open()/log_close() in single-threaded applications and in in the initialization phase of multi-threaded applications.

PID 1 does issue log_open()/log_close() during runtime. It's thread use is very limited though:

1. automount.c maintains a thread for expiry.
2. execute.c forks off threads for rm_rf()int PrivateTmp= dirs
3. service.c uses asynchronous_close() which forks off a thread for close()ing...

of the list above 1 and 2 do logging...

So yeah, things are a bit racy in this regard, but I am not entirely sure what the best approach there is...

**Comment by poettering** [comment]
i figure the rm_rf() stuff could be moved to a process relatively easily...

the asynchronous_close() can't really be converted, but I guess we could remove all logging for it, it's sooo trivial aftrer all...

**Comment by sourcejedi** [comment]
technically, I suspect asynchronous_close() could be converted.  The reason we're worried about a socket blocking when we close it, is that it may have pending messages to send.  So it is the close of the last fd referring to the socket that will block.

it would require some dance where the child process waits until the parent has closed it's copy of the fd.

**Comment by sourcejedi** [comment]
Admittedly the usual way to dance is using yet another fd (a pipe).  There's an alternative to just have the child pause and the parent send it sigkill or something though.

Keeping trivial threads seems equally acceptable to me though.  The constraint can just be mentioned in a comment.

**Comment by mrc0mmand** [comment]
With https://github.com/systemd/systemd/pull/28123 PID 1 no longer uses any threads, so this can be closed as resolved.
