### ISSUE TITLE
port knocking support for socket activated services

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#802]
Would be nice if instead of simple logic "connection on port X -> start service Y" systemd would be capable of implementing more advanced port knocking type: "connection attempts on ports X1, X2, X3 within N sec. -> start service Y on port X3".

There are some patches for systemd available at https://gnunet.org/knock
More on port knocking: http://portknocking.org/

**Comment by poettering** [comment]
Hmm, sorry, but I think port knocking is clearly outside of the focus of systemd. It shouldn't be too hard however to write a small daemon that does what you want and then activates socket and service unit after the port knocking has been successful.

Sorry.

**Comment by johannbg** [comment]
Just for enlightenment purposes... 

The systemd patch that adds support for this upstream seems relatively clean ( it lacks updates to man page for the type socket options it introduces ). 

It adds configuration flag --enable-tcp-stealth  and introduces two new configuration options to type socket units "TCPStealthSecret" and "TCPStealthIntegrityLen". 

However upstream there are patches to the kernel so this would never be implemented until after those patches have been merged in the upstream kernel.

A package with those patches merged ( systemd-knock  ) seems to have been in circulation in the arch community or arch based distro for a while.

**Comment by zabbal** [comment]
Why that matters at all? There's pretty big piece in systemd merged and enabled by default which does not yet have kernel counterpart upstreamed. It's called kdbus. TCPStealth\* patches could be incorporated the same way.

**Comment by poettering** [comment]
@zabbal well, with kdbus we know for a fact that the people behind it do everything necessary to get it upstream, hence supporting in systemd is just going a bit faster than kernel development itself. I am not sure the port knocking patches are attempted to get upstream into the kernel, no?

**Comment by johannbg** [comment]
This did get submitted upstream and rejected with basically take these changes to
the major transport protocol and discuss that with IETF on the tcpm/tcpinc mailing list where they are actively discuss the TCP stealth topic.
https://lkml.org/lkml/2013/12/11/803

If this ever get merged upstream than this RFE can be revisited but until that happens it remains closed.
