### ISSUE TITLE
logind does not properly recognize that a client is already inside a session.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8021]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

In #7451, 
> logind sessions are mostly bound to the audit session concept, and audit sessions remain unaffected by "su", in fact they are defined to be "sealed off", i.e. in a way that if a process entered a session once, it will always stay with it, and so will its children, i.e. the only way to get a new session is by forking off something off PID 1 (or something similar) that never has been part of a session.

I'm very much in favor of not letting su create a new session, but what follows contradicts assumptions made above.

### In case of bug report: Unexpected behaviour you saw

We do this from gnome-terminal,

```bash
$ loginctl
   SESSION        UID USER             SEAT             TTY             
         2       1000 jkowalski        seat0            tty1            
        c1        989 gdm              seat0            tty7            

2 sessions listed.
$ echo $XDG_SESSION_ID
2
$ su -l root
Password:
# loginctl
   SESSION        UID USER             SEAT             TTY             
         2       1000 jkowalski        seat0            tty1            
        c1        989 gdm              seat0            tty7            

2 sessions listed. 
# echo $XDG_SESSION_ID

# su -l root
Password:
# loginctl
   SESSION        UID USER             SEAT             TTY             
         2       1000 jkowalski        seat0            tty1            
        c1        989 gdm              seat0            tty7            
         3          0 root                              pts/3           

3 sessions listed.
# echo $XDG_SESSION_ID
3
# loginctl user-status root
root (0)
           Since: Sat 2018-01-27 15:42:33 UTC; 52s ago
           State: active
        Sessions: *3
          Linger: no
            Unit: user-0.slice
                  ├─session-3.scope
                  │ ├─4625 su -l root
                  │ ├─4632 -su
                  │ ├─4656 loginctl user-status root
                  │ └─4657 /usr/host/bin/less
                  └─user@0.service
                    └─init.scope
                      ├─4626 /usr/x86_64-pc-linux-gnu/lib/systemd/systemd --user
                      └─4627 (sd-pam)

Jan 27 15:42:33 delta systemd[1]: Created slice User Slice of root.
Jan 27 15:42:33 delta systemd[4626]: Reached target Timers.
Jan 27 15:42:33 delta systemd[4626]: Reached target Paths.
Jan 27 15:42:33 delta systemd[4626]: Starting D-Bus User Message Bus Socket.
Jan 27 15:42:33 delta systemd[4626]: Listening on D-Bus User Message Bus Socket.
Jan 27 15:42:33 delta systemd[4626]: Reached target Sockets.
Jan 27 15:42:33 delta systemd[4626]: Reached target Basic System.
Jan 27 15:42:33 delta systemd[4626]: Reached target Default.
Jan 27 15:42:33 delta systemd[4626]: Startup finished in 18ms.
# su -l root
Password:
# echo $XDG_SESSION_ID

# loginctl
   SESSION        UID USER             SEAT             TTY             
         2       1000 jkowalski        seat0            tty1            
        c1        989 gdm              seat0            tty7            
         3          0 root                              pts/3           

3 sessions listed.
# su -l root
... which ends up being the same for any subsequent invocations.
```
#### The logs

Here, if one tries to login with `su -l root` from within a session for the first time, one gets
```
Jan 27 15:27:21 delta su[4203]: Successful su for root by jkowalski
Jan 27 15:27:21 delta su[4203]: + /dev/pts/3 jkowalski:root
Jan 27 15:27:21 delta su[4203]: pam_unix(su:session): session opened for user root by (uid=1000)
Jan 27 15:27:21 delta su[4203]: pam_systemd(su:session): Cannot create session: Already occupied by a session
```
and rightfully so, because something inside a session should not escape it.

On the second invocation of `su -l root` from the su shell, we instead get a new session and this in the logs.

```
Jan 27 15:28:48 delta su[4234]: Successful su for root by root
Jan 27 15:28:48 delta su[4234]: + /dev/pts/3 root:root
Jan 27 15:28:48 delta systemd[1]: Created slice User Slice of root.
Jan 27 15:28:48 delta su[4234]: pam_unix(su:session): session opened for user root by (uid=0)
Jan 27 15:28:48 delta systemd[1]: Starting User Manager for UID 0...
Jan 27 15:28:48 delta systemd-logind[621]: New session 3 of user root.
Jan 27 15:28:48 delta systemd[1]: Started Session 3 of user root.
Jan 27 15:28:48 delta systemd[4235]: Reached target Paths.
Jan 27 15:28:48 delta systemd[4235]: Starting D-Bus User Message Bus Socket.
Jan 27 15:28:48 delta systemd[4235]: Reached target Timers.
Jan 27 15:28:48 delta systemd[4235]: Listening on D-Bus User Message Bus Socket.
Jan 27 15:28:48 delta systemd[4235]: Reached target Sockets.
Jan 27 15:28:48 delta systemd[4235]: Reached target Basic System.
Jan 27 15:28:48 delta systemd[4235]: Reached target Default.
Jan 27 15:28:48 delta systemd[4235]: Startup finished in 21ms.
Jan 27 15:28:48 delta systemd[1]: Started User Manager for UID 0.
```
However, any subsequent `su -l root` invocations also return the correct message and do not spawn a new login session.

```
Jan 27 15:29:47 delta su[4266]: Successful su for root by root
Jan 27 15:29:47 delta su[4266]: + /dev/pts/3 root:root
Jan 27 15:29:47 delta su[4266]: pam_unix(su:session): session opened for user root by (uid=0)
Jan 27 15:29:47 delta su[4266]: pam_systemd(su:session): Cannot create session: Already running in a session
Jan 27 15:29:52 delta su[4395]: Successful su for root by root
Jan 27 15:29:52 delta su[4395]: + /dev/pts/3 root:root
Jan 27 15:29:52 delta su[4395]: pam_unix(su:session): session opened for user root by (uid=0)
Jan 27 15:29:52 delta su[4395]: pam_systemd(su:session): Cannot create session: Already running in a session
```

Now a few other cases,
```
$ su -l root
Password: 
# loginctl
   SESSION        UID USER             SEAT             TTY             
         2       1000 jkowalski        seat0            tty1            
        c1        989 gdm              seat0            tty7            

2 sessions listed.
# su -l jkowalski
$ loginctl
   SESSION        UID USER             SEAT             TTY             
         2       1000 jkowalski        seat0            tty1            
        c1        989 gdm              seat0            tty7            
         3       1000 jkowalski                         pts/3           

3 sessions listed.
```
Same when logging in to jkowalski and then again to jkowalski, or logging in to jkowalski and then to root.

Not reproducible when doing the double `su -l ...` from an ssh session (that is, from a session scope created by logging in from ssh to the user jkowalski). Key difference is that this time the bash shell `su -l` is invoked from is under a session scope, instead of being under /user-1000.slice/user@1000.service/gnome-terminal-server.service for the bash shell in gnome-terminal, which might be related to the issue at hand.

### In case of bug report: Steps to reproduce the problem

This happens under GNOME and steps are as I described above, but I cannot test it under KDE or something else (but I think it does not matter much). One key thing to note here and probably the root cause of it all is that the `su` process is inside gnome-terminal-server.service which is in turn under user@1000.service which is inside user-1000.slice, and not under session-2.scope which is also inside user-1000.slice, thus it is also not clear if user@1000.service is part of the session or not, and if it isn't, then the first `su` invocation should probably not fail but the second one succeeding in creating a new session (maybe still inheriting attributes from the previous one, and not as pristine, but the user manager starts and it ends up being inside its own user-UID.slice, so equally usable). Not really sure what is happening here.

**Comment by sourcejedi** [comment]
Well spotted.  user@.service runs in a PAM session, `PAMName=systemd-user`.  It is special cased in pam_systemd to not create a logind session, but I think it should have everything else set up including audit.  So we don't want to allow escaping the audit.

**Comment by bl33pbl0p** [comment]
Thanks for looking into this, I'll test the PR tomorrow and report back.

**Comment by bl33pbl0p** [comment]
Seems to work fine now, thanks!
