### ISSUE TITLE
Pass $SERVICE_RESULT, $EXIT_CODE, and $EXIT_STATUS from the failed service to the one invoked with OnFailure= (as different variables, perhaps)

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8022]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

236

### RFE

It would be great if systemd could pass $SERVICE_RESULT, $EXIT_CODE, and $EXIT_STATUS from the service that failed and in turn caused the service configured in OnFailure= to be invoked, probably as $ONFAILURE_SERVICE_RESULT, $ONFAILURE_EXIT_CODE, and $ONFAILURE_EXIT_STATUS so that they do not mask the ones the service's ExecStop{=,Post=} would need themselves. This would be useful in handling the error supplied by the failing service and would allow us to generate more useful messages from the OnFailure= unit.

The current approach taken is to write them to a file with ExecStopPost= and then use that as the EnvironmentFile= for the other unit, and then rm it during the ExecStartPre= phase to not use the stale file for other invocations, but that mixes in badly when the original failing unit is in its own mount namespace and/or writes to a file which disappears after its lifecycle.

Alternatively, I'd like to know if this is already achievable in a generic way, but passing them as variables sounds very useful (and would apply to all processes in the unit invoked with OnFailure=)

**Comment by poettering** [comment]
Fixed by cdebedb4d40277aad62a7734ba920b4033228197
