### ISSUE TITLE
`Travis` seems to be failing to build `systemd` due to strings encrypted with the wrong key

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#8023]
I've just come across https://travis-ci.org/systemd/systemd/jobs/334056679, where the build log contains the following lines:
```sh
$ export tyPD3GTyfVO9K7imQATDdnMY32nkWXmXej8YWo76yA732rTZRZtFAc=[secure]
$ export JItA=[secure]
```
. The most likely reason is that the "secure" strings in `.travis.yml` were encrypted using the key that is different from [the current public key](https://api.travis-ci.org/repos/systemd/systemd/key).

**Comment by evverx** [comment]
According to https://github.com/systemd/systemd/pull/7691#issuecomment-361402333, we seems to be waiting for @CermakM to contact @lnykryn. I'm not sure when it's going to happen, though.

**Comment by CermakM** [comment]
@evverx I talked to @lnykryn and @msekletar quite a while ago and we've discussed what should be done in order to fix this, I believe there were other higher priority issues so they hadn't found time for this yet.

**Comment by CermakM** [comment]
Aight, here is what it takes to generate the correct secure string:

1a. install travis (if applicable) -- `gem install travis`
1. clone the upstream systemd repository
2. issue `travis login --pro` and log in with systemd credentials (this will query api.github.com)
3. issue `travis encrypt COVERITY_SCAN_TOKEN="<token>"` to generate the encryption and pass in the coverity token
4. replace the scure string in the `env` section in the `.travis.yml` file

That's really all that it takes.. I am not part of the systemd organization so I think my GitHub credentials would generate wrong encryption.

**Comment by evverx** [comment]
I think that the main issue is that `DOCKER_USERNAME` and `DOCKER_PASSWORD` should be encrypted too and nobody seems to know what values should be used.

**Comment by CermakM** [comment]
Ah right, good point, forgot about these... Ye, sure, these as well. Again, @lnykryn and @msekletar know what to do.

**Comment by keszybz** [comment]
> issue `travis login --pro` and log in with systemd credentials (this will query api.github.com)

I don't think this is possible. "systemd" is an organization, so it has no credentials. When I log in with my own account "keszybz", I always get "keszybz has not granted Travis CI the required permissions, please log in via travis-ci.com". No matter what I do, I always get this message.

**Comment by keszybz** [comment]
I also tried revoking access for travis-ci to my account and adding it back under https://github.com/settings/applications. No effect.

**Comment by evverx** [comment]
I don't think step 2 above is necessary in this case. `travis encrypt -r systemd/systemd KEY=VALUE` should be enough to encrypt `KEY=VALUE` with the right key.

**Comment by CermakM** [comment]
@keszybz  Seems like you have not set up the systemd repo on Travis CI (Adding the organization to the Travis and granting Travis CI permissions).

You should log in to Travis, in you profile page find `Review and add your authorized organizations. ` and grant Travis the permissions. Then you should be able to use those credentials.

**Comment by evverx** [comment]
By the way, does anybody know what happened to Fedora CI? I guess if it worked, it would be possible to simplify `.travis.yml` by removing everything except for the coverity phase because it seems that there is no need to run the unit tests on Travis and Fedora CI at the same time.

The coverity phase could be used to build an image with `docker build` and run `coverity build upload` without pushing or pulling anything making `DOCKER_USERNAME` and `DOCKER_PASSWORD` unnecessary.

**Comment by evverx** [comment]
Also, I've just found https://scan.coverity.com/travis_ci. Maybe it would be easier to make what is described there work. After all, it's the official way to integrate Coverity and Travis.

**Comment by keszybz** [comment]
OK, see #9137. Can I test it without merging to master?

**Comment by evverx** [comment]
As far as I can see, it's a cron job, which makes it a little harder to test without merging to master. I think removing `if: type = cron` from `.travis.yml` and enabling Travis for every PR temporarily would work. But, according to https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions, Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them, so it seems that the PR should come from `systemd/systemd`.

**Comment by evverx** [comment]
It seems that without `docker push` in the `build docker image` stage, all the subsequent stages will fail. I think if building `systemd` and running the unit tests are really necessary the first three stages could be merged into one where an image would be built and `ninja tests` would be run without intermediate steps requiring that something has been pushed with `docker push`.

**Comment by CermakM** [comment]
Sure it can be merged into one stage, the docker is used as a persistent storage between the stages. However, you'll loose the benefit of running and reviewing all those stages separately, ie. with the separate stages, you can easily check which part of the process failed. With one stage, it'll just be failed stage and you'll have to go through the logs to see which part of the process caused the build to fail.

It is quite easy (and free) to create docker account, so maybe you want to consider even this option and create one for systemd. Up to you.

**Comment by evverx** [comment]
PR #9151 is going to make `DOCKER_USERNAME` and `DOCKER_PASSWORD` obsolete, so I'm closing the issue.
