### ISSUE TITLE
RFE: extend sysusers 'u' line

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#8046]
### Submission type

 - Request for enhancement (RFE)

1. support '-' with gid specification. In this case, uid is chosen in the range automatically. E.g.
```
u username -:300
```
2. support group name instead of gid. E.g.
```
g groupname 300
u username 315:groupname
```
3. support the combination of 1 and 2. E.g.
```
g groupname -
u user1 -:groupname
u user2 -:groupname
```

----------
Note that I do not have any use cases related to this RFE. Hence, please simply ignore/reject this. But if you really want this and have good use cases, then please give me comments. 

@mvo5 What do you think?

**Comment by mvo5** [comment]
I like the proposal, especially point 2 adds greatly to the readability I think.

**Comment by yuwata** [comment]
@mvo5 If you like at least one of them, please implement them :-) Note that I do no know that these are approved by others :-p

**Comment by mvo5** [comment]
[0001-sysuers-support-u-username-300-style-syntax.patch.gz](https://github.com/systemd/systemd/files/1678457/0001-sysuers-support-u-username-300-style-syntax.patch.gz)

First iteration. Happy to make this a proper PR but right now it is build on top of https://github.com/systemd/systemd/pull/8037 and I want to avoid conflicts.

**Comment by boucman** [comment]
@mvo5 you probably want to submit this as a proper PR anyway... if you add [do not merge] in the title and  say in the comment that it must be merged after #8037 there should be no ambiguity...

once the PR is ready, you can change the PR title... github allows you to do that...

**Comment by yuwata** [comment]
@mvo5 ping?

**Comment by mvo5** [comment]
Ups, sorry! Was busy with $dayjob. I pushed the first part now.

**Comment by bl33pbl0p** [comment]
and the same could be done with the gid for completeness's sake?

**Comment by poettering** [comment]
Of this RFE only the group name thing is still missing, right? #14340 is about that, and just that. Hence closing this one in favour of that (I mean, technically #14340 is newer thant this one, and we usually close the newer as duplicate, but given that this one was about multiple things, let's leave the one that is just about one issue instead).
