### ISSUE TITLE
Question -- Activation socket and IPv6

### ISSUE THREAD

**Issue by nuxwin** [systemd/systemd#8049]
Good evening,

Not a bug report but only a question, if not less an RFE.

In activation socket units we can make use of **ListenStream** to listen on whatever interface/port we want to. For instance, dovecot IMAP/POP server is provided with such activation socket:

Not a bug report but only a question.

In activation socket units we make use of ListenStream to listen on whatever interface/port we want to. For instance, dovecot is provided with the following activation socket:

```
[Unit]
Description=Dovecot IMAP/POP3 email server activation socket

[Socket]
#dovecot expects separate IPv4 and IPv6 sockets
BindIPv6Only=ipv6-only
ListenStream=0.0.0.0:143
ListenStream=[::]:143
ListenStream=0.0.0.0:993
ListenStream=[::]:993
KeepAlive=true

[Install]
WantedBy=sockets.target
```
My question: Is there a way to tell systemd trying to listen on IPv6 only when the protocol is available?

**Comment by boucman** [comment]
yes, it's documented in "man systemd.socket"
also, please use the mailing list or IRC channel for support, this is supposed to be only a bug/feature tracker

**Comment by nuxwin** [comment]
@boucman 

Thank you for your answer. I was not aware of the IRC channel. I didn't really searched for it. Sorry.
