### ISSUE TITLE
x32 is broken somehow by the default SystemCallFilter= (or SystemCallArchitectures= ?)

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8060]
Reported by @jgunthorpe in #8002, see https://github.com/systemd/systemd/issues/8002#issuecomment-361766876

### Submission type

 - Bug report

### systemd version the issue has been seen with

v237

### Used distribution

Debian (v?).   x32 architecture.

### In case of bug report: Unexpected behaviour you saw

systemd-journald.service crashed with SIGSYS.  Also logind and udevd.

### In case of bug report: Steps to reproduce the problem

Boot the system.

**Comment by sourcejedi** [comment]
He also reported that clearing `SystemCallFilter=` and `SystemCallArchitectures=` resolved the problem.

Testing journald, I see

```
newfstatat(14, "system@000564184b091e0e-1a20ec920f9e8c1e.journal~", {st_mode=S_IFREG|0640, st_size=8388608, ...}, AT_SYMLINK_NOFOLLOW) = 0
newfstatat(14, "system@000564184b08d576-4a6db66973add9d9.journal~", {st_mode=S_IFREG|0640, st_size=8388608, ...}, AT_SYMLINK_NOFOLLOW) = 0
getdents64(14, /* 0 entries */, 32768)  = 0
close(14)                               = 0
access("/run/systemd/journal/flushed", F_OK) = -1 ENOENT (No such file or directory)
timerfd_settime(12, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=2790, tv_nsec=899326000}}, NULL) = 0
epoll_pwait(6, [{EPOLLIN, {u32=1473392304, u64=1473392304}}, {EPOLLOUT, {u32=1473395376, u64=1473395376}}], 13, -1, NULL, 8) = 2
timerfd_create(CLOCK_BOOTTIME, TFD_CLOEXEC|TFD_NONBLOCK) = 14
close(14)                               = 0
strace: syscall_228(...) in unsupported 64-bit mode of process PID=350
+++ killed by SIGSYS +++
```

syscall_228() on x32 should be `clock_gettime()`.  (And there don't seem to be any previous attempts to call it in the journald process).

journald definitely uses that, it mentions it explicitly in the source.  It's also in our default whitelisted syscalls... and not in any of our blacklist groups (including `@clock`).  systemd-journald.service doesn't blacklist _any_ individual system call by name; it only uses the named groups of system calls.  Searching "clock_gettime", doesn't show any other reference to it in `shared/seccomp-util.c`, `shared/`, or `core/` either.  Weird.

**Comment by sourcejedi** [comment]
Google points out [it's a VDSO making an x86-64 syscall, lol](https://lists.debian.org/debian-ssh/2017/01/msg00006.html).

The solution they used to keep openssh' sandbox working was to enable that specifically.  Maybe not so great for systemd to do... we will want to get an exhaustive list of such syscalls... (and, I guess, check that the kernel agrees this was a bad idea and they won't add any more such usage).

i think it's not too bad if we add some weird exceptions by default, i think it won't be too hard to make sure they get blocked when they are blocked explicitly.  The problem would be if the weird exceptions include some syscall that we didn't want to make part of the default syscall whitelist.

**Comment by jgunthorpe** [comment]
Ah! Interesting. The kernel uses the exact same VDSO with 64 bit and x32 mode, it doesn't even recompile it, just objcopy's to change the ELF ABI tag. Looks like this is deliberate so the VDSO can be a 64 bit program that can access some shared pages mapped > 4G.

It would probably be possible, with some work, for the kernel VDSO to use the x32 syscalls in the x32 VDSO.. With the status-quo I think you can expect it to grow new 64 bit syscalls over time.

Perhaps the simple answer is that SystemCallArchitectures=native for x32 should include both the x32 and x86-64 version of each permitted syscall..

**Comment by poettering** [comment]
We don't (and can't really) test systemd on x32. We hence rely on contributed patches to keep this working. Hence, please make the necessary changes, test them and submit them as PR if x32 is relevant to you.

(even better: provide an x32 CI if you want to be sure this doesn't break again)

**Comment by jgunthorpe** [comment]
Well, I know I don't care enough to try and learn seccomp to fix this.

But I am surprised to hear you say you can't test x32 - maybe the below will help someone to update mkosi?

I was able to get a root filesystem that boots in kvm (this issue aside) with:

```sh
apt-get install -y debootstrap debian-ports-archive-keyring

export DEBIAN_FRONTEND=noninteractive
debootstrap --arch=x32 --keyring=/usr/share/keyrings/debian-ports-archive-keyring.gpg unstable /tmp/distro http://ftp.ports.debian.org/debian-ports/
```

And you can fill it with all the compilers and libraries you need to compile systemd and use it in a container to build systemd.

I'm actually doing this to test another opensource project and kernel component, so I'm kind of in the same boat as systemd..

**Comment by sourcejedi** [comment]
That was my knee-jerk troll reaction also :-P.  Fedora didn't seem to package the debian-ports keyring though, only the main one.  (Solution: run mkosi targetting x32 inside a Debian mkosi image :-P).

I can already test this and was planning to work on it.  I had a debian VM around and making a x32 nspawn container was as straightforward as you say.

**Comment by sourcejedi** [comment]
^ This worked for me.  As poettering says, we're not exactly set up for x32 development, but you were lucky enough to raise your issue while I was confused in the right way :).  And I found another generic systemd bug to report, so that worked out nice.
