### ISSUE TITLE
"systemctl show --property=ListenStream systemd-journald" fails (so does ListenDatagram)

### ISSUE THREAD

**Issue by dkg** [systemd/systemd#8064]
### Submission type
 - Bug report

### systemd version the issue has been seen with
237-1

### Used distribution

debian unstable

i can extract all the properties of a `.socket` unit file listed in `systemctl show` using the `--proprerty=` argument *except* for two:

 * `ListenStream`
 * `ListenDatagram`

here's an example loop showing that those two values are present in the initial `show` output, but empty when requested directly as `--property`: 

```
systemctl show systemd-journald.socket | grep ^Listen
for x in $(systemctl show systemd-journald.socket | cut -f1 -d=); do
   out=$(systemctl show "--property=$x" systemd-journald.socket)
   if [ -z "$out" ]; then
      echo "$x"
   fi
done
```

I would have expected `systemctl show --property=ListenStream systemd-journald` to emit `/run/systemd/journal/stdout`

**Comment by yuwata** [comment]
Indeed...
```
$ systemctl show --property ListenStream systemd-journald.socket
$ systemctl show --property ListenDatagram systemd-journald.socket
$ systemctl show systemd-journald.socket | grep Listen
ListenStream=/run/systemd/journal/stdout
ListenDatagram=/run/systemd/journal/socket
```

**Comment by yuwata** [comment]
Ah, we need to use `Listen`, instead of `ListenStream` or `ListenDatagram`.
```
$ systemctl show --property Listen systemd-journald.socket
ListenStream=/run/systemd/journal/stdout
ListenDatagram=/run/systemd/journal/socket
```

**Comment by yuwata** [comment]
Similar case happens for .path units. E.g.,
```
$ systemctl show cups.path | grep Path
PathExistsGlob=/var/spool/cups/d*
FragmentPath=/usr/lib/systemd/system/cups.path
$ systemctl show --property PathExistsGlob cups.path
$ systemctl show --property Paths cups.path
PathExistsGlob=/var/spool/cups/d*
```

**Comment by yuwata** [comment]
Fix is waiting in #8065.

**Comment by rendaw** [comment]
Since this fix broke my script and it's not clear what path users should take forward, to summarize:

The resolution of this ticket is "Won't fix" - `systemctl show` shows DBus properties and while `Listen` is a property, `ListenStream` and `ListenDatagram` are not.  There's no way to filter those, you gotta write your own awk script.

I think it would be better to keep this open though as a feature request for a way to filter just the Stream or Datagram types since that's presumably what the first post was about.

**Comment by rendaw** [comment]
I am confused, and I agree with most of your points :).

I think the `systemctl show` docs suggest that `*Sec` properties might not exist in favor of `*USec` properties, but that makes the docs little better than a disclaimer.

My comment was mostly based on the linked fix PR discussion, quoting @yuwata: 
> Hmm... `systemctl show -p` does not take unit settings, but takes dbus properties. E.g., it supports `*USec` instead of `*Sec`

**Comment by allisonkarlitskaya** [comment]
Can I at least depend on
    systemctl show cockpit.socket -p Listen --value
as being considered "API stable", then?  Or will it break when/if this bug is fixed?

**Comment by poettering** [comment]
@allisonkarlitskaya actually, this PR got merged, and yes, it cleaned that up... But given that the old behaviour was really broken and nonsensical I think breaking this once to fix it is the better choice than to carry on with the old behaviour.

The line you specified will produce different output on systems before and after this PR. Afterwards a suffix of ` (Stream)` will be shown in that command...

**Comment by poettering** [comment]
@allisonkarlitskaya i would probably suggest to use busctl get-property instead if you need something for shell. The "systemctl show" stuff is a bit too ad-hoc in cases like this one...
