### ISSUE TITLE
Allow passing -p with systemctl -H

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8071]
### Submission type

 - Request for enhancement (RFE)

### RFE

Allow passing the port to connect to with -H, or alternatively, honor something like $SYSTEMD_SSH_COMMAND to be able to pass the ssh command directly through the variable instead of having to extend -H with all options ssh accepts. (Note that one could invoke ssh directly or set the port in .ssh/config, but it would be nicer to not have to do that when instead it could use $SYSTEMD_SSH_COMMAND just like options passed to less are configurable with $SYSTEMD_LESS.)

**Comment by bl33pbl0p** [comment]
I guess the environment variable trick might not be possible since the ssh stuff is part of sd-bus, and I'm not sure env vars are a good idea for stuff like that. I was thinking :port but we allow logging in to remote nested containers (`-H user@host:container1:container2inside1`) so that might not work either.

**Comment by yuwata** [comment]
(Note that `-p` is already used.)

**Comment by bl33pbl0p** [comment]
Yes, I was mentioning -p since that is what ssh itself uses. 

I think there can be two ways to do this, the first could be to use ;port (like varlink does unix:/run/io.systemd.devices;mode=0666 for example) but that would require one to escape ; in the shell (not so much annoyance with varlink since the resolver activates it from the json config).

The other way which looks better to me is to terminate the host:container:container:... expression with a :: and then specify the port. That would be like `-H user@host:c1:c2::2222`.

**Comment by boucman** [comment]
i'm not sure of the exact syntax, but :: is also usde for ipv6 adresses... no risk of collision ?

**Comment by bl33pbl0p** [comment]
Hm. Indeed, I did not really think about that, and now I'm not sure what the best way would be, without adding something like `--port=` just for this (which I'm sure would not mix well with how it is used in sd-bus's sd_bus_open_remote).

Maybe @poettering can suggest something.

**Comment by shawnl** [comment]
> i'm not sure of the exact syntax, but :: is also usde for ipv6 adresses... no risk of collision ?
usually ipv6 addresses are contained within brackets `[]` for this reason
