### ISSUE TITLE
"Failed to open system journal: Invalid argument" mmap

### ISSUE THREAD

**Issue by jwwalton** [systemd/systemd#8074]
on qemu+kvm with 9p as rootfs i see the following twice in dmesg each time (?) something logs.

systemd-journald[123]: Failed to open system journal: Invalid argument

```
14:36:51 recvmsg(3, {msg_name=0x7ffe8e938d60, msg_namelen=128->0, msg_iov=[{iov_base="<13>Feb  2 14:36:51 root: testing", iov_len=24575}], msg_iovlen=1, msg_control=[{cmsg_len=32, cmsg_level=SOL_SOCKET, cmsg_type=SCM_TIMESTAMP, cmsg_data={tv_sec=1517578611, tv_usec=839584}}, {cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=396, uid=0, gid=0}}], msg_controllen=64, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 33 <0.000039>
14:36:51 openat(AT_FDCWD, "/proc/396/comm", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000012>
14:36:51 readlinkat(AT_FDCWD, "/proc/396/exe", 0x55ba3d3315d0, 99) = -1 ENOENT (No such file or directory) <0.000011>
14:36:51 openat(AT_FDCWD, "/proc/396/cmdline", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000017>
14:36:51 openat(AT_FDCWD, "/proc/396/status", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
14:36:51 openat(AT_FDCWD, "/proc/396/sessionid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000021>
14:36:51 openat(AT_FDCWD, "/proc/396/loginuid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000010>
14:36:51 openat(AT_FDCWD, "/proc/396/cgroup", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000008>
14:36:51 access("/run/systemd/journal/flushed", F_OK) = 0 <0.000010>
14:36:51 stat("/var/log/journal", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0 <0.000457>
14:36:51 mkdir("/var/log/journal/", 0755) = -1 EEXIST (File exists) <0.000313>
14:36:51 stat("/var/log/journal/", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0 <0.000320>
14:36:51 mkdir("/var/log/journal/bb1decc783b9441cad0656159a88856d", 0755) = -1 EEXIST (File exists) <0.000366>
14:36:51 openat(AT_FDCWD, "/var/log/journal/bb1decc783b9441cad0656159a88856d/system.journal", O_RDWR|O_CREAT|O_CLOEXEC, 0640) = 22 <0.001867>
14:36:51 fstat(22, {st_mode=S_IFREG|0640, st_size=240, ...}) = 0 <0.000080>
14:36:51 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 22, 0) = -1 EINVAL (Invalid argument) <0.000015>
14:36:51 close(22)                      = 0 <0.000092>
14:36:51 writev(7, [{iov_base="<44>", iov_len=4}, {iov_base="systemd-journald", iov_len=16}, {iov_base="[210]: ", iov_len=7}, {iov_base="Failed to open system journal: Invalid argument", iov_len=47}, {iov_base="\n", iov_len=1}], 5) = 75 <0.000032>
14:36:51 access("/run/systemd/journal/flushed", F_OK) = 0 <0.000014>

```

this is with systemd 237 and archlinux, not sure if it happened on 236 or not. i'm assuming the problem here in 9p rather than something else?

example qemu command line with arch rootfs in /opt/arch (needs 9p stuff in initrd)

`qemu-system-x86_64 -machine q35 -enable-kvm -kernel /opt/arch/boot/vmlinuz-linux -initrd /opt/arch/boot/initramfs-linux.img -smp sockets=1,cores=2 -display gtk -m 2G -nodefaults -no-user-config -no-hpet -device virtio-tablet -vga cirrus -cpu host -fsdev local,security_model=passthrough,id=fsdev0,path=/opt/arch -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -device virtio-net-pci,netdev=net0 -netdev user,id=net0  -append "loglevel=5 earlyprintk root=hostshare rootfstype=9p rootflags=trans=virtio,version=9p2000.L rootwait rw"`

**Comment by vcaputo** [comment]
I have not tested this, but after searching for 'mmap' in https://www.kernel.org/doc/Documentation/filesystems/9p.txt, it appears read-write mmap support requires a 9p caching policy be enabled, and states that by default no caches are used.  Try adding `,cache=mmap` after the `version=9p2000.L`.

**Comment by poettering** [comment]
yeah, this is a limitation of 9p: it doesn't do mmap by default. This is a limiation of 9p really, use a different file system or change the mount options to make this work. mmap() is a pretty basic operation these days, and not only required for journal's internal logic, but ELF loading and whatnot.

Closing hence.
