### ISSUE TITLE
machinectl shell invokes ssh even when -H is incompatible with it.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8076]
### Submission type

 - Bug report

### systemd version the issue has been seen with

237

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

```
$ machinectl shell -H arch@localhost
Shell only supported on local machines.
$ 
```

### In case of bug report: Unexpected behaviour you saw

```
$ machinectl shell -H user@host
Shell only supported on local machines.
user@host's password: 
$ echo $?
1 
```

### In case of bug report: Steps to reproduce the problem

machinectl shell -H [USER@]HOST

**Comment by shawnl** [comment]
AND

`timedatectl set-time jibberish -H HOST`

This is a very pervasive bug, and requires reworking src/basic/verbs.c
