### ISSUE TITLE
(sd-pam) process is a CoW trap.  Garbage data puts unecessary pressure on virtual memory.

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8081]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

code seen in master

### Used distribution

Fedora

### RFE

I've been overloading my RAM a bit lately.

StackOverflow has a [one-liner to print per-process swap usage](https://stackoverflow.com/questions/30481314/how-can-i-know-which-process-is-using-swap).  I notice that `(sd-pam)` can end up with more swap accounted than the parent `systemd` currently has.  Like, almost 2MB!

This is basically all going to be dead memory as far as `(sd-pam)` is concerned.  I think it's got to be copy-on-write pages from PID 1.

>  If the parent is also modifying memory while the child runs, the child will be hosting copies of all the modified memory (copy-on-write). Often the child is performing a sub-task and only uses a subset of that data.
> 
> It's possible for it to be significant with a larger parent process and longer-running child process.

```
$ (echo "COMM PID SWAP"; for file in /proc/*/status ; do awk '/^Pid|VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | grep kB | grep -wv "0 kB" | sort -k 3 -n -r) | column -t | grep -E 'sys|[(]'
systemd-udevd    586    4436   kB
(sd-pam)         2215   3900   kB
(sd-pam)         1023   3896   kB
(sd-pam)         17506  2488   kB
systemd          1      2260   kB
systemd-logind   840    960    kB
systemd          1007   748    kB
systemd-journal  560    656    kB
systemd          2210   652    kB
```

**Comment by sourcejedi** [comment]
As you say pam doesn't fit in to exec_child() very nicely. But `PAMName` seems fairly obscure and IIRC there's at least one other caveat to it. I think we could stop using it if we wanted.  E.g.

    ExecStart=/usr/lib/systemd --user --pam-user=%i

and suggest anyone else consider `runuser` instead.

It's great to have service files declaratively dropping privileges. But maybe we can give up on fitting arbitrary plugins in to the sequence.

**Comment by poettering** [comment]
well, PAM hooks need to be called with privs still, which means we'd either have to give up on all privs dropping in that case on the systemd side or do PAM stuff inside of PID1's pre-exec child...

It's a fucked situation.

**Comment by jriddy** [comment]
> As you say pam doesn't fit in to exec_child() very nicely. But `PAMName` seems fairly obscure and IIRC there's at least one other caveat to it. I think we could stop using it if we wanted. E.g.
> 
> ```
> ExecStart=/usr/lib/systemd --user --pam-user=%i
> ```
> 
> and suggest anyone else consider `runuser` instead.
> 
> It's great to have service files declaratively dropping privileges. But maybe we can give up on fitting arbitrary plugins in to the sequence.

Is this suggested as some kinda workaround for this? Does this involve switching away from `pam_systemd` entirely? We're starting to see this crop up in production from time to time in our Fedora-based VMs when they are under very high load for some time, and nobody is really sure how to get any system to recover from this state, which can lead to data loss for our customers.

**Comment by sourcejedi** [comment]
@bluca systemd-executor handles PAM and should fix this issue now, right?

**Comment by bluca** [comment]
Yes
