### ISSUE TITLE
systemd-run created transient scope units get no $INVOCATION_ID

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8082]
### Submission type

 - Request for enhancement (RFE)

### RFE

Each unit systemd manages gets its own InvocationId, visible in systemctl show -p InvocationID _unit_. `systemd-run --scope` is supposed to be the parent process as documented in the man page, and thus inherits the environment from the caller of the process, but if the caller has no $INVOCATION_ID set (say a shell), the assumption is broken. Although this is desirable, the ones that are not set (and are supposed to be present for all, as documented in systemd.exec) should be passed and set correctly for the scope, however the ones supposed to be passed but already set should remain unotouched (examples being $XDG_RUNTIME_DIR, $XDG_SESSION_ID, $USER, etc). If not others, atleast $INVOCATION_ID should be passed and be visible.

Currently, it ends up being this way.
```
$ systemd-run --user --scope --unit=sleep.scope env | grep INVOCATION_ID
Running scope as unit: sleep.scope
$ echo $?
1
```
From another shell,
```
$ systemctl --user show -p InvocationID sleep.scope
InvocationID=16c64a8c341c443b9cbfe56eaa094711
$
```

**Comment by poettering** [comment]
Fix waiting in #10887
