### ISSUE TITLE
Systemd-networkd VLAN-aware bridge interfaces not working

### ISSUE THREAD

**Issue by thequailman** [systemd/systemd#8087]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Debian Stretch (backports)

### In case of bug report: Expected behaviour you didn't see

> enp7s0f2 joining bridge and passing traffic to VLAN 100 without tagging.  Can ping 10.254.4.1

### In case of bug report: Unexpected behaviour you saw

> enp7s0f2 joins bridge, but no traffic is passed or any MAC addresses learned.  Interestingly enough, DNSMASQ (which is running on that network) complains that it `received a DHCP request on bridge`` interface that doesn't have an IP`.

### In case of bug report: Steps to reproduce the problem

> Use this config:

**10_bridge.netdev**
```
[NetDev]
Name=bridge
Kind=bridge

[Bridge]
DefaultPVID=none
VLANFiltering=yes
```

**20_vl-lan.netdev**
```
[NetDev]
Name=vl-lan
Kind=vlan

[VLAN]
Id=100
```

**21_vl-lan.network**
```
[Match]
Name=vl-lan

[Network]
Address=10.254.4.1/24
VLAN=vl-lan
```

**30_bridge.network**
```
[Match]
Name=bridge

[Network]
VLAN=vl-lan
```

**40_interface.network**
```
[Match]
Name=enp7s0f2

[Network]
Bridge=bridge

[BridgeVLAN]
EgressUntagged=100
PVID=100
VLAN=100
```

**Comment by thequailman** [comment]
For anyone who comes across this same issue in the future, I solved it by changing my configs.  You'll find that this feature is very poorly documented.  To the maintainers, please feel free to use the below as a working example in the docs.

**bridge.netdev**
```
[NetDev]
Name=bridge
Kind=bridge

[Bridge]
DefaultPVID=1
VLANFiltering=yes
```

**bridge.network**
```
[Match]
Name=bridge

[Network]
VLAN=guest
VLAN=lan

[BridgeVLAN]
VLAN=1

[BridgeVLAN]
VLAN=4
```

**enp7.network**
```
[Match]
Name=enp7s0f0 enp7s0f1 enp7s0f3

[Network]
Bridge=bridge
```

**enp7s0f2.network**
```

[Match]
Name=enp7s0f2

[Network]
Bridge=bridge

[BridgeVLAN]
VLAN=4
```

**guest.netdev**
```
[NetDev]
Name=guest
Kind=vlan

[VLAN]
Id=4
```

**guest.network**
```
[Match]
Name=guest

[Network]
Address=10.1.4.1/24
```

**lan.netdev**
```
[NetDev]
Name=lan
Kind=vlan

[VLAN]
Id=1
```

**lan.network**
```
[Match]
Name=lan

[Network]
Address=10.254.1.1/24
```

**Comment by clhodapp** [comment]
It's pretty obnoxious how many times you have repeat yourself with the VLAN numbers. You had to mention `VLAN=4` three times!

It's also interesting that you *didn't* have to re-mention VLAN 1 in `enp7.network`. I'm guessing that's because it's the default VLAN and carries untagged traffic?
