### ISSUE TITLE
60-keyboard.hwdb remove incorrect keys for Logitech  Cordless Wave Pro

### ISSUE THREAD

**Issue by barzog** [systemd/systemd#8095]
### Submission type

 - Request for enhancement (RFE)

### Used distribution
Gentoo
### In case of bug report: Expected behaviour you didn't see
In 60-keyboard.hwdb there is a definition of # Cordless Wave Pro
evdev:input:b0003v046DpC52[9B]*

which in fact not a cordless keyboard but an USB receiver to which different types of keyboard can be connected. So, proposed solution is to completely clean definition evdev:input:b0003v046DpC52B* from there.

I: Bus=0003 Vendor=046d Product=c52b Version=0111
N: Name="Logitech USB Receiver"
P: Phys=usb-0000:00:1d.0-1.8/input1
S: Sysfs=/devices/pci0000:00/0000:00:1d.0/usb4/4-1/4-1.8/4-1.8:1.1/0003:046D:C52B.0005/input/input20
U: Uniq=
H: Handlers=kbd mouse0 event8
B: PROP=0
B: EV=1f
B: KEY=3007f 0 0 83ffff17aff32d bf54444600000000 ffff0001 130f978b17c000 6773fad941dfed 9ed68000004400 10000002
B: REL=1c3
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=046d Product=c52b Version=0111
N: Name="Logitech USB Receiver"
P: Phys=usb-0000:00:1d.0-1.8/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.0/usb4/4-1/4-1.8/4-1.8:1.0/0003:046D:C52B.0006/input/input21
U: Uniq=
H: Handlers=sysrq kbd event9 leds
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff800000000007ff febeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f

### In case of bug report: Unexpected behaviour you saw
In my case I've used Logitech k340 wireless keyboard where no mention keys is present, so I've got following error during system bootup:
[    3.447661] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc00b8, key code 161): Invalid argument
[    3.447665] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc0183, key code 226): Invalid argument
[    3.447667] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc0184, key code 421): Invalid argument
[    3.447670] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc0186, key code 423): Invalid argument
[    3.447673] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc018a, key code 155): Invalid argument
[    3.447675] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc018e, key code 397): Invalid argument
[    3.447677] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc01b6, key code 212): Invalid argument
[    3.447680] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc01bc, key code 430): Invalid argument
[    3.447682] udevd[3334]: Error calling EVIOCSKEYCODE on device node '/dev/input/event8' (scan code 0xc0221, key code 217): Invalid argument

**Comment by keszybz** [comment]
I made this into a PR now.
