### ISSUE TITLE
missing documentation regarding predefined tags in udev rules

### ISSUE THREAD

**Issue by cz172638** [systemd/systemd#81]
as maintainer of package, which distributes udev rules, i didn't found appropriate documentation regarding predefined tags for udev rules.

**Comment by gregkh** [comment]
What specifically are you looking for that is not provided with the example rules?

**Comment by cz172638** [comment]
some comments in example rules, explaining what means uaccess, seat, what is bad usage and what is proper usage of tags.

**Comment by gregkh** [comment]
Everyone wants more documentation, but nothing is "missing" here.  Please provide patches if you see things that could be explained better, but without that, I'm going to close this issue as it does not contain a patch.
