### ISSUE TITLE
systemd-detect-virt fails with "Operation not permitted" under docker

### ISSUE THREAD

**Issue by ozfaro** [systemd/systemd#8111]
### Submission type
 - Bug report

### systemd version the issue has been seen with
> 229

### Used distribution
> Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see
> systemd-detect-virt should show virtual system (e.g. docker) or none

### In case of bug report: Unexpected behaviour you saw
> During apt-get upgrade grub-pc can not install in virtual container (docker) because of systemd-detect-virt fails with "Operation not permitted". 

> Error output:  /var/lib/dpkg/info/grub-pc.postinst: line 299: /usr/bin/systemd-detect-virt: Operation not permitted

> Call of systemd-detect-virt returns: "Operation not permitted"

### In case of bug report: Steps to reproduce the problem

> apt-get update; apt-get upgrade;  systemd-detect-virt

**Comment by poettering** [comment]
What does strace'ing systemd-detect-virt output in such an environment? i.e. what's the actual operation getting EACCES here?

IIRC there are some container environments that explicitly don't want to be detectable, maybe yours is one of them?

**Comment by ozfaro** [comment]
Strace Output: 
```
strace: ptrace_setoptions = 0x11
strace: PTRACE_SEIZE doesn't work
strace: new tcb for pid 23264, active tcbs:1
strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
strace: [wait(0x000100) = 23264] WIFEXITED,exitcode=1
+++ exited with 1 +++
strace: dropped tcb for pid 23264, 0 remain
```

It was working perfectly fine before last nights ubuntu update of systemd. 
I can also reproduce the bug in the official docker containers of ubuntu.

**Comment by poettering** [comment]
That strace output suggests your container manager disallows stracing from inside. Consider tracing it from the outside, or turning on the necessary caps

**Comment by ozfaro** [comment]
I am running into the issue in the official ubuntu:xenial docker image as well.
Steps:
docker run -it ubuntu:xenial /bin/bash
systemd-detect-virt 

- successful

dpkg -s systemd | grep Version

- Version: 229-4ubuntu21
 
`apt-get update; apt-get upgrade`
systemd-detect-virt 

- fails (error see above)

dpkg -s systemd | grep Version

- Version: 229-4ubuntu21.1

**Comment by ozfaro** [comment]
Here is complete log of:
`strace docker run -it systemd_bug /usr/bin/systemd-detect-virt /usr/bin/systemd-detect-virt`

[systemd-detect-virt_errorlog.txt](https://github.com/systemd/systemd/files/1699006/systemd-detect-virt_errorlog.txt)

**Comment by poettering** [comment]
Sorry, I am looking for the strace of systemd-detect-virt only, not of docker itself...

**Comment by ozfaro** [comment]
Just a short update. Running docker in privileged mode solves the problem. I don't know if it is a bug or a wanted behavior. In the previous version the --priviliged mode was not required. 
I have included the strace in the privilegd environment, but as this is working I don't know it helps
[systemd_detect_virt_privileged.txt](https://github.com/systemd/systemd/files/1699814/systemd_detect_virt_privileged.txt)

**Comment by poettering** [comment]
Still, we need the logs in order to say anything...

**Comment by alexswerner** [comment]
I have the same problem and I hope I can supply logs needed. When executing systemd-detect-virt there is nothing in logged in dockerd (even with log level debug). When attaching strace to dockerd i get the following log: [docker_container_strace.txt](https://github.com/systemd/systemd/files/2171349/docker_container_strace.txt). That does not look really helpful to me. How can I obtain more information?

**Comment by filbranden** [comment]
@alexswerner @ozfaro Try using `--cap-add=SYS_PTRACE` when you start the container, otherwise you won't be able to use `strace` inside it.

I can't reproduce your problem with `systemd-detect-virt`, but this works to strace it for me:

```
$ docker run --cap-add=SYS_PTRACE -it ubuntu:16.04 /bin/bash
root@8b79335608d6:/# apt-get update                                                                 
root@8b79335608d6:/# apt-get install strace                                    
root@8b79335608d6:/# strace systemd-detect-virt                                      
execve("/usr/bin/systemd-detect-virt", ["systemd-detect-virt"], [/* 8 vars */]) = 0
brk(NULL)                               = 0x5602a7e51000                                   
...
write(1, "docker\n", 7docker
)                 = 7
exit_group(0)                           = ?
+++ exited with 0 +++
root@8b79335608d6:/#
```

Try the same and report back...

This is on Docker version 18.03.0-ce, build 0520e24.

**Comment by alexswerner** [comment]
I did as you suggested docker --cap-add=SYS_PTRACE and the immediate issue is gone. Without --add-cap=ptrace:
```
/usr/bin/systemd-detect-virt: Operation not permitted
```
with it:
```
none
```
and exit code 1.
Interestingly this does not seem to be the correct exit code. The man page says:  "If a virtualization technology is detected, 0 is returned, a non-zero code otherwise." I think your suggestion of adding the capability maybe hides the original problem. The strace for execution with the added capability: 
[strace.txt](https://github.com/systemd/systemd/files/2180925/strace.txt)

**Comment by filbranden** [comment]
So from the strace, it looks like it's trying to find the container from `/run/systemd/container`, then failing to do so (file does not exist) and then trying to fallback to reading `/proc/1/environ`, which needs CAP_SYS_PTRACE (see the comment.)

Looking at the v229 sources, this fallback is being triggered:

https://github.com/systemd/systemd/blob/v229/src/basic/virt.c#L380

But looking at that code, it seems like it's supposed to do the right thing in that case, just set to "none" and go to finish, so I can't explain why this is happening...

I can't really reproduce the exact situation you're triggering with `/usr/bin/systemd-detect-virt: Operation not permitted`. Can you give more details on it? Which OS are you using outside the container? Are you running on a VM or on a real host? Are you using the ubuntu:16.04 image in your tests?

You might also want to try with a later systemd package to see if that's fixed there. (Even though I'd expect systemd v229 to work correctly there...) This might be a distro issue, so maybe try to report it to Ubuntu?

> The man page says: "If a virtualization technology is detected, 0 is returned, a non-zero code otherwise."

Yes. "none" means no virtualization technology was detected! That's exactly what it said.

**Comment by evverx** [comment]
Could you also try tracing `systemd-detect-virt` from outside the offending container? `docker ps` can be used to get the container id, which in turn can be used to get the PID to trace:
```sh
PID=$(docker container inspect $CONTAINER_ID | jq '.[0].State.Pid')
strace -s500 -v -f -yy -p $PID
```
Once `strace` has started, it will keep track of everything including any attempts to run `systemd-detect-virt`.

**Comment by alexswerner** [comment]
Here: [strace.txt](https://github.com/systemd/systemd/files/2182680/strace.txt). Looks it is going for ptrace.
Environment is: Ubuntu 18.04 as host OS in real hardware and Ubuntu 16.04 in the container.

**Comment by filbranden** [comment]
This last strace you attached ends with `write(1, "none\n", 5)`, so it doesn't reproduce the `Operation not permitted` you originally reported...

**Comment by alexswerner** [comment]
Sorry, i did not pay attention must have submitted the wrong file. Here it is 
[strace.txt](https://github.com/systemd/systemd/files/2184916/strace.txt)
But i do not see where it fails.

**Comment by filbranden** [comment]
This one still ends with:

```
write(1, "none\n", 5none
)                   = 5
exit_group(1)                           = ?
+++ exited with 1 +++
```

In other words, it's printing "none" and exiting with status 1 and not reproducing the `Operation not permitted` you reported.

**Comment by filbranden** [comment]
I still can't reproduce it...

I'm running on a VM, but:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.10.1
 Git commit:    7390fc6
 Built: Wed Apr 18 01:23:11 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   7390fc6
  Built:        Wed Feb 28 17:46:05 2018
  OS/Arch:      linux/amd64
  Experimental: false
$ dpkg -l docker.io
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                                         Version                                     Architecture                                Description
+++-============================================================================-===========================================-===========================================-==============================================================================================================================================================
ii  docker.io                                                                    17.12.1-0ubuntu1                            amd64                                       Linux container runtime
$ docker run -it ubuntu:16.04 /bin/bash
root@3c132f7b77a0:/# systemd-detect-virt
docker
root@3c132f7b77a0:/# rm /run/systemd/container 
root@3c132f7b77a0:/# systemd-detect-virt
kvm
root@3c132f7b77a0:/# 
```

I initially get "docker" because it's registered in `/run/systemd/container`, but then if I remove that file it gets me "kvm" which is the virtualization I'm using (in other words, it detected it correctly.)

It looks like ptrace solved your problem before, so maybe this is related? What is your sysctl set to?

```
$ sysctl kernel.yama.ptrace_scope
kernel.yama.ptrace_scope = 1
```

Can you check whether your versions match mine? Version of Docker (I installed package `docker.io` from Ubuntu repository), version of Ubuntu on the host, etc.

Cheers,
Filipe

**Comment by alexswerner** [comment]
Thanks for the patience.
kernel.yama.ptrace_scope = 1
and I uploaded the same wrong file twice. This should be the correct one now.
[strace.txt](https://github.com/systemd/systemd/files/2185283/strace.txt)

Cheers!

**Comment by filbranden** [comment]
Hmmm...

```
execve("/usr/bin/systemd-detect-virt", ["/usr/bin/systemd-detect-virt"], [...]) = -1 EPERM (Operation not permitted)
```

So it's having trouble executing the binary itself...

```
[pid 10365] access("/usr/bin/systemd-detect-virt", R_OK) = 0
[pid 10365] open("/usr/bin/systemd-detect-virt", O_RDONLY) = 3</usr/bin/systemd-detect-virt>
[pid 10365] read(3</usr/bin/systemd-detect-virt>, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20/\0\0\0\0\0\0@\0\0\0\0\0\0\0\260\201\0\0\0\0\0\0\0\0\0\0@\0008\0\n\0@\0 \0\37\0\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0", 80) = 80
[pid 10365] close(3</usr/bin/systemd-detect-virt>) = 0
[pid 10365] write(2</dev/pts/0>, "bash: /usr/bin/systemd-detect-virt: Operation not permitted\n", 60) = 60
[pid 10365] exit_group(126)             = ?
[pid 10365] +++ exited with 126 +++
```

So the message is:

```
bash: /usr/bin/systemd-detect-virt: Operation not permitted
```

In other words, bash is the one complaining about that...

Do you have something like AppArmor that might be blocking execution of this binary? Maybe check your logs for messages explaining why it's being blocked? Check audit logs if you have any...

Good luck!

**Comment by evverx** [comment]
@filbranden is right. `systemd-detect-virt` didn't even get to start. Although it's certainly possible to track down the source of `EPERM`, it's outside the scope of `systemd`. I'm afraid there's nothing we can do about it.

**Comment by alexswerner** [comment]
OK, i"m fine with working around this problem as well. But i still kept digging and
setting kernel.yama.ptrace_scope to zero or running the container with --security-opt seccomp=unconfined did not help. What did change something was
```
$ cp /usr/bin/systemd-detect-virt ./
$ ./systemd-detect-virt
none
```
That confuses me. Both files have the same md5sum. Same permissions. I think the problem is somewhere else entirely. I attached a new 
[strace.txt](https://github.com/systemd/systemd/files/2185998/strace.txt) for running the copy. The output is none. I must add that I created that docker image from a full virtual machine installation by creating a tar of the root filesystem.

**Comment by evverx** [comment]
It seems that a couple of leftover capabilities was cloned along with everything else (though they shouldn't have been there in the first place: fdd25311706bd32). Could you run `getcap /usr/bin/systemd-detect-virt` to see if there's `cap_sys_ptrace`?

**Comment by evverx** [comment]
Regarding the original issue, it happened because [`systemd.postinst` was fixed just a year ago](https://salsa.debian.org/systemd-team/systemd/commit/bc96cb305226f2130d07fdcc68c704010867156f), which means that `apt-get update` caused the capabilities of `systemd-detect-virt` to be set to `cap_dac_override,cap_sys_ptrace=ep`:
```sh
$ docker run -it ubuntu:16.04 /bin/bash
root@3619efe05877:/# /usr/bin/systemd-detect-virt
docker
root@3619efe05877:/# apt-get update
...
root@3619efe05877:/# (cd /tmp/ && apt-get download systemd)
...

root@3619efe05877:/# ls /tmp/
systemd_229-4ubuntu21.2_amd64.deb

root@3619efe05877:/# dpkg -i /tmp/systemd_229-4ubuntu21.2_amd64.deb
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../systemd_229-4ubuntu21.2_amd64.deb ...
Unpacking systemd (229-4ubuntu21.2) over (229-4ubuntu21.2) ...
Setting up systemd (229-4ubuntu21.2) ...
Initializing machine ID from random generator.
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Operation failed: No such file or directory
...

root@3619efe05877:/# /usr/bin/systemd-detect-virt
bash: /usr/bin/systemd-detect-virt: Operation not permitted

root@3619efe05877:/# getcap /usr/bin/systemd-detect-virt
/usr/bin/systemd-detect-virt = cap_dac_override,cap_sys_ptrace+ep
```

@alexswerner thank you very much for not giving up! Your perseverance has helped a lot.

**Comment by alexswerner** [comment]
And you are very correct if found exactly this situation:
/usr/bin/systemd-detect-virt = cap_dac_override,cap_sys_ptrace+ep

Cool that we found it.
