### ISSUE TITLE
systemd-nspawn with --user options fails (regression 236 -> 237)

### ISSUE THREAD

**Issue by myrkr** [systemd/systemd#8113]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> None, Kernel 4.12 was tested, glibc 2.24

### In case of bug report: Expected behaviour you didn't see

> systemd-nspawn with --user works correctly

### In case of bug report: Unexpected behaviour you saw

> systemd-nspawn with --user options failed to start because the spawn_getent call failed

### In case of bug report: Steps to reproduce the problem

I have defined a container named pcscd located in the sub directory /var/lib/machines/pcscd. I try to start this container with a command line:

systemd-nspawn --machine pcscd /sbin/pcscd -d

The pcscd.nspawn contains the ``User=pcscd`` option.

So the system-nspawn call spawn_getent (which itself calls safe_fork_full) to start the /usb/bin/getent process within the container. After the fork is completed, the following code is run in the child:

````
	if (flags & FORK_DEATHSIG) {
                pid_t ppid;
                /* Let's see if the parent PID is still the one we started from? If not, then the parent                                  
                 * already died by the time we set PR_SET_PDEATHSIG, hence let's emulate the effect */

                ppid = getppid();
                if (ppid == 0)
		        /* Parent is in a differn't PID namespace. */;
		else if (ppid != original_pid) {
                        log_debug("Parent died early, raising SIGTERM.");
                        (void) raise(SIGTERM);
                        _exit(EXIT_FAILURE);
                }
        }
````

This fails on my system. f I remove this check the container is correctly started. The container is also correctly started if I use the ``--user root`` option which avoids this code path.

I added some log_debug statements to the code, the complete diff is available here: [systemd.diff.txt](https://github.com/systemd/systemd/files/1698363/systemd.diff.txt)

The output (including my additional log messages) at the error location is:

````
before_fork: pid 3494 (cached 3494) ppid 0
Successfully forked off '(getent)' as PID 2.
in parent after fork: pid 3494 (cached 3494) ppid 0
Failed to rename process, ignoring: Operation not permitted
after_fork: pid 2 (cached 2) ppid 1
Parent died early, raising SIGTERM.
Failed to resolve user pcscd.
Child died too early.
Bus n/a: changing state RUNNING → CLOSED
````

The identical setup works correctly with systemd 236.

I have both the complete ``SYSTEMD_LOG_LEVEL=debug`` output of the systemd-nspawn call (debug.log) as the strace output of this call (strace.log).

The original pcscd.service file for starting this container and the pcscd.nspawn file are also added as attachment (I had to rename them by adding a txt suffix).

[debug.log](https://github.com/systemd/systemd/files/1698357/debug.log)
[strace.log](https://github.com/systemd/systemd/files/1698358/strace.log)
[pcscd.nspawn.txt](https://github.com/systemd/systemd/files/1698361/pcscd.nspawn.txt)
[pcscd.service.txt](https://github.com/systemd/systemd/files/1698362/pcscd.service.txt)

**Comment by myrkr** [comment]
I noticed that there is no getpid() syscall for the log output ``before_fork: pid 3494 (cached 3494) ppid 0`` so it might be a bug in the version 2.24 of glibc which has some caching for the getpid call. I added a patch to our glibc build which ensures that this caching is not in place and the bug in systemd-nspawn vanished. So it is basically an incompatibility between upstream glibc 2.24 and systemd 237.

Closing this issue here.

**Comment by poettering** [comment]
hmm, but we should definitely work on older glibc, so this actually *is* a bug...

**Comment by poettering** [comment]
I prepped a PR in #8115 that should fix this. Any chance you can give this a whirl?

**Comment by myrkr** [comment]
I have tested your changes from #8115 and they solved the problem.
