### ISSUE TITLE
It looks like -H is broken.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8116]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

-H working properly, as in running the command on the correct host:machine.

### In case of bug report: Unexpected behaviour you saw

```
[root@delta] ~ # systemctl -H user@::1:epsilon status systemd-journald
ssh: Could not resolve hostname ::1:epsilon: Name or service not known
```
epsilon is a local nspawn container which is running and booted.

```
[root@delta] ~ $ systemctl -H user@localhost:epsilon status systemd-journald
Password: 
systemd-stdio-bridge: unrecognized option '--machine=epsilon'
```

### In case of bug report: Steps to reproduce the problem

As described above. This I discovered while trying to find some way to specify the port with -H in https://github.com/systemd/systemd/issues/8071 .

**Comment by shawnl** [comment]
If --machine was never implemented then #8071 is an easy fix.....
