### ISSUE TITLE
Add check for gettext 0.19.7 or later

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8118]
### Submission type

 - Bug report

### Bug report

With gettext versions older than 0.19.7, `msgfmt` doesn’t have the switch `--xml`, and the build fails with the error below.

```
[234/1474] /pkg/python-3.6.4-1/bin/python3.6 /pkg/python-3.6.4-1/bin/meson --internal msgfmthelper ../source/src/login/org.freedesktop.login1.policy.in src/login/org.freedesktop.login1.policy xml /dev/shm/bee-root/systemd/systemd-237-0/source/po --datadirs=/dev/shm/bee-root/systemd/systemd-237-0/source/po
FAILED: src/login/org.freedesktop.login1.policy 
/pkg/python-3.6.4-1/bin/python3.6 /pkg/python-3.6.4-1/bin/meson --internal msgfmthelper ../source/src/login/org.freedesktop.login1.policy.in src/login/org.freedesktop.login1.policy xml /dev/shm/bee-root/systemd/systemd-237-0/source/po --datadirs=/dev/shm/bee-root/systemd/systemd-237-0/source/po
msgfmt: unrecognized option '--xml'
Try `msgfmt --help' for more information.
```

The switch was added in [version 0.19.7](https://abi-laboratory.pro/tracker/changelog/gettext/0.19.8/log.html):

> Version 0.19.7 - December 2015
>
> * Programming languages support:
>   - XML:
>     xgettext can now load custom string extraction rules supplied by
>     consumer projects.  The rules are written in XML, utilizing the
>     Internationalization Tag Set (ITS) standard.  All the existing
>     XML-based language scanners (Glade, GSettings, and AppData) are
>     rewritten using ITS.  In addition, msgfmt now has --xml option to
>     merge translations back to the original XML document.
>
> * Portability:
>   - Improve OS/2 kLIBC support (still not complete)
>   - Remove dependency on expat

**Comment by keszybz** [comment]
#8162 might make this issue moot.

**Comment by keszybz** [comment]
#8202 has been merging, so we don't depend on the gettext version, let's close this.
