### ISSUE TITLE
/run/systemd/user is not read from.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8119]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

systemd's user instance reads units from:
* /run/systemd/user
* .local/share/systemd/user
* .$XDG_RUNTIME_DIR/systemd/user/

as documented in `systemd.unit` man page.

### In case of bug report: Unexpected behaviour you saw

None of these directories are created, nor are they read from when they're created manually and units are dropped inside.

### In case of bug report: Steps to reproduce the problem

Test this with a `systemd --user` instance.

**Comment by poettering** [comment]
well, did you issue "systemctl --user daemon-reload"? we should pick them up then...

We don't create directories we don't need really, and that's a good thing I think. However if we still don't pick them up after a daemon reload, then this would indeed be a bug

**Comment by bl33pbl0p** [comment]
I feel they should be created, since all of those fit in nicely in the vendor/runtime/admin concept, but it's not a major issue if they're not present (just looks a bit odd to me, and non-consistent).

and yes, it works after issuing systemctl --user daemon-reload, but not for /run/systemd/user. For the other two, it seems to work fine (I still think directories for all three, or atleast the ones in /run should be created, but your call).

```
[kowalski@delta] /run/systemd/user $ ls
foo.service
[kowalski@delta] /run/systemd/user $ cat foo.service 
[Unit]
Description=foo

[Service]
ExecStart=/bin/true
[kowalski@delta] /run/systemd/user $ systemctl --user daemon-reload 
[kowalski@delta] /run/systemd/user $ systemctl --user status foo.service
Unit foo.service could not be found.
[kowalski@delta] /run/systemd/user $ systemctl --user start foo.service
Failed to start foo.service: Unit foo.service not found.
[kowalski@delta] /run/systemd/user $ 
```

**Comment by bl33pbl0p** [comment]
I guess needs-reporter-feedback can now be removed.

**Comment by keszybz** [comment]
This should be fixed by 7b6344d35fdbe523fb6eff2fdfa892d7f07ebfa9. Please upgrade to the version, and test with `systemd-analyze --user unit-paths`.

**Comment by bl33pbl0p** [comment]
That isn't in 237 but I'll try the patch and report back.

**Comment by bl33pbl0p** [comment]
works.
