### ISSUE TITLE
NSPAWN container access to host file system fails

### ISSUE THREAD

**Issue by Sybas** [systemd/systemd#8123]
### Submission type

 - Bug report

### systemd version the issue has been seen with

236.81-1 & 237.02

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

I'm not able to access from a nspawn container the host system files anymore after updating my system from version 235.8-1. 

I use .nspawn file in the /etc/systemd/nspawn to create a link to the host system. By ls -l the folder permission is shown as nobody:nobody and I get permission denied when I try to access the folder. When I remove the bind the permission is still nobody:nobody but I'm able to open the folder (with no data).

### In case of bug report: Steps to reproduce the problem

Created a new container to create a link to the same directory, same problem.

**Comment by yuwata** [comment]
At least, could you show us the .nspawn file?

Note that Arch has a issue about nobody users. See, e.g. #7717 or #7906.

**Comment by Sybas** [comment]
This is the configuration for my .nspawn file:

```
[Files]
Bind=/mnt/data/movies:/mnt/movies
Bind=/mnt/data/tvshows:/mnt/tvshows
Bind=/mnt/data/music:/mnt/music
Bind=/mnt/data/ebooks:/mnt/ebooks

[Network]
Bridge=br0
```

**Comment by yuwata** [comment]
Thanks. Then, please give us the permission of these directories. Both from the host and client is favorable.

**Comment by Sybas** [comment]
Sorry for my late response but on the host:

```
drwxrwx---  15 root osheim  16 Nov 30 19:50 ebooks
drwxrwx--- 181 root osheim 181 Nov 30 20:25 movies
drwxrwx---  11 root osheim  11 Nov  8 20:35 music
drwxrwx---  26 root osheim  26 Nov  5 19:24 tvshows
```
And on the client:
```
drwxrwx---  15 nobody nobody   16 Nov 30 19:50 ebooks
drwxrwx--- 181 nobody nobody  181 Nov 30 20:25 movies
drwxrwx---  11 nobody nobody   11 Nov  8 20:35 music
drwxrwx---  26 nobody nobody   26 Nov  5 19:24 tvshows
```
