### ISSUE TITLE
udev: auto re-read partition table makes SCSI disk ro attribute just work once

### ISSUE THREAD

**Issue by lining2020x** [systemd/systemd#8141]
### Submission type
 - Bug report

### systemd version the issue has been seen with
version > systemd-213

### Used distribution
CentOS

### In case of bug report: Expected behaviour you didn't see
>set ro on SCSI disk by "blockdev --setro /dev/sdc" and dd many times, dd operation is alwayes denied

### In case of bug report: Unexpected behaviour you saw
>set ro on SCSI disk by "blockdev --setro /dev/sdc", and dd many times, dd operation is denied just for the first time.

### In case of bug report: Steps to reproduce the problem
keep the SCSI disk unmount. 
1. blockdev --setro /dev/sdc
2. dd if=/dev/zero of=/dev/sdc count=1024
3. dd if=/dev/zero of=/dev/sdc count=1024

**Comment by scott0000** [comment]
Users rely on the readonly attribute  to protect their SCSI disk from being writen by dd-like tools. 
This commit ede3444 use "ioctl(fd,BLKRRPAR)" to re-read partition table. When setting ro on SCSI disk, calling "ioctl(fd,BLKRRPAR)" will make the ro attribute of SCSI disk change to rw again.

**Comment by poettering** [comment]
@scott0000 this appears to be a kernel problem to me. rereaded the partition table should not have an effect on the read-only flag of block devices.

**Comment by scott0000** [comment]
OK, Thanks for replying.

**Comment by scott0000** [comment]
@poettering OK, Thanks for replying.
