### ISSUE TITLE
`journalctl --grep` seems to always return 0 whatever happens

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#8152]
There are scenarios where [`journalctl | grep`](https://salsa.debian.org/systemd-team/systemd/blob/39fc527be06792216417e67648bc55529138207c/debian/tests/boot-smoke#L33) is used to automatically detect possible problems. I can also [imagine](https://github.com/systemd/systemd/pull/8032#issuecomment-364493285) similar scripts in which `journalctl | grep` is wrapped in something like
```sh
set -o pipefail
if journalctl ... | grep ...; then
    exit 1
fi
[ ${PIPESTATUS[0]} -ne 0 ] && exit 1
```
to make sure that `journalctl` successfully reads all data.

I'm happy with scripts like that, but it would probably be useful if `journalctl --grep` were usable in scripts too.

**Comment by keszybz** [comment]
Yeah. `--grep` does nothing to the return code, it just limits which messages are displayed. But it would be useful to mimic grep here.
