### ISSUE TITLE
Virtualization detection via /proc/1/sched no longer works on Linux 4.14+

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#8153]
### Submission type

 - Request for enhancement (I think? I’m not even sure, sorry)

### systemd version the issue has been seen with

> master

I just stumbled across the “container-other” detection in `virt.c`, and then happened to remember a related Linux kernel commit – if I’m not mistaken, torvalds/linux@74dc3384fc7983b78cc46ebb1824968a3db85eb1 (“sched/debug: Use `task_pid_nr_ns` in `/proc/$pid/sched`”, 2017-08-06; first merged in v4.14-rc1, no idea if backported) breaks not only @jessfraz’ `amicontained` tool, but also `systemd-detect-virt` and ` ConditionVirtualization`, because we also look at `/proc/1/sched`:

```c
/* Interestingly /proc/1/sched actually shows the host's PID for what we see as PID 1. Hence, if the PID shown
 * there is not 1, we know we are in a PID namespace. and hence a container. */
r = read_one_line_file("/proc/1/sched", &m);
if (r >= 0) {
        const char *t;

        t = strrchr(m, '(');
        if (!t)
                return -EIO;

        if (!startswith(t, "(1,")) {
                r = VIRTUALIZATION_CONTAINER_OTHER;
                goto finish;
        }
} else if (r != -ENOENT)
        return r;
```

I don’t know if there’s any other way to detect PID namespaces on newer kernels – at least, `amicontained`’s [`HasPIDNamespace`](https://github.com/jessfraz/amicontained/blob/a817de962716dcf6289130ae128a91f5667ba7b7/container/container.go#L83-L95) doesn’t seem to fall back to anything else. Eric Biederman [wrote](https://marc.info/?l=linux-kernel&m=150220597311640&w=2) that “stating the `/proc/pid/ns/pid` files ought to be an easy way”, but could also be “a bit tricky”. Even if there’s no other way to do this, I suppose the comment in the code should be updated to reflect that this was a bug which has since been fixed.

Note that the `/proc/1/sched` code only comes into effect if all other container detections fail, so IIUC it only breaks `container-other` detection, and all well-known container technologies should still be detected. And it seems that PID1 skips this check as well (“we can just check our own environment variable, and that’s authoritative”), so I think `ConditionVirtualization=container` is only broken by this for user managers.

**Comment by poettering** [comment]
> Eric Biederman wrote that “stating the /proc/pid/ns/pid files ought to be an easy way”

I wonder what precisely he means with that tbh... What stat()ing that file tell us about whether we are in the root pidns or in any other?

**Comment by lucaswerkmeister** [comment]
Yeah, I’m not sure either… but I did find one difference: on the systems I could test (Arch with kernel 4.15.1, Debian Jessie with kernel 4.9.65, and Ubuntu Artful with kernel 4.13.0), the device number of an unnamespaced `/proc/1/ns/pid` always seems to be 4, while in a PID namespace it’s a different, higher number, apparently related to the number of (PID?) namespaces. You can try it with these commands:

```sh
stat --format %d /proc/1/ns/pid
sudo unshare --pid --fork --mount-proc stat --format %d /proc/1/ns/pid
```
(Creating a PID namespace requires `CAP_SYS_ADMIN` – if you don’t want to run the second command with full root privileges, you can replace `sudo` with `sudo systemd-run -qt -p DynamicUser=yes -p AmbientCapabilities=CAP_SYS_ADMIN`. (Though I’m not sure if the protections implied by `DynamicUser=yes` are enough to make `CAP_SYS_ADMIN` no longer root-equivalent.))

Of course, if this turns out to be a reliable way to detect PID namespaces, I suppose we should report it to the kernel folks :)

**Comment by lucaswerkmeister** [comment]
By the way, it seems that the `/proc/1/sched` fix apparently hasn’t been backported to Debian Jessie’s kernel at least:
```sh
$ uname -srv
Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
$ sudo unshare --pid --fork --mount-proc sh -c ./systemd-detect-virt
container-other
```
Note that this requires a systemd built from source, because Jessie ships systemd v232 and the `/proc/1/sched` trick was added in v233. (Also, if your `sh` is `bash`, append `; :` or something like that to the `-c` option so that the shell doesn’t `exec` `systemd-detect-virt` without `fork`, because `systemd-detect-virt` must not be PID1.)

**Comment by keszybz** [comment]
FWIW, I get numbers like 57 for the inode number of `/proc/1/ns/pid` on the host. Maybe it's because I have an initramfs? No matter what the reason is, I don't think this can work.

**Comment by jessfraz** [comment]
I ended up doing this as well fwiw :)

**Comment by yummypeng** [comment]
Maybe "detecting if i am in a namespace" is in direct contradiction to the design principles of namespace, because namespace is used to make an isolated environment which anybody inside the environment should not see the resources beyond the scope.

**Comment by poettering** [comment]
The hack to detect via /proc/1/sched was dropped in #17917. #17902 adds a better mechanism, relying on the cgroup hierarchy. 

Let's close this issue, as there's no way we can restore this as it was originally, given it mostly used a kernel bug for our means
