### ISSUE TITLE
shutdown[1]: Failed to wait for process: Protocol error

### ISSUE THREAD

**Issue by Potomac** [systemd/systemd#8155]
### Submission type

 - Bug report

### systemd version the issue has been seen with
237.0-2

### Used distribution
archlinux 64 bits

### In case of bug report: Expected behaviour you didn't see

> no error message should be seen at extinction of the PC

### In case of bug report: Unexpected behaviour you saw

> I see the message : 
shutdown[1]: Failed to wait for process: Protocol error

### In case of bug report: Steps to reproduce the problem
- use archlinux 64 bits
- install the last archlinux package of systemd ( 237.0-2 )
- during the shutdown you will see the message : 
shutdown[1]: Failed to wait for process: Protocol error

see the attached file ( screen capture )

**Comment by Potomac** [comment]
![process_error](https://user-images.githubusercontent.com/1340993/36064813-39fb4330-0e91-11e8-9c33-63a02fb0e394.png)

**Comment by BBBob** [comment]
I meet the same error now!!

**Comment by jigmpatel** [comment]
I have the same issue. Will adding the "shutdown" hook to mkinitcpio.conf help? I am on the 4.15.2 kernel.

**Comment by rbisewski** [comment]
Encountered something identical like this today. Running an up-to-date archlinux 64bit with Linux 4.15.2 and systemd 237.0-2 installed.

The work-around for now appears to edit `/etc/mkinitcpio.conf` and look for the following line:

```
HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)
```

Add the `shutdown` hook like so:

```
HOOKS=(base udev autodetect modconf block filesystems keyboard fsck shutdown)
```

Afterwards, regenerate the initramfs as follows:

```
mkinitcpio -p linux
```

Upon reboot and a 2nd shutdown, the problem seems to go away. The developers (either archlinux or systemd) might want to check to ensure this is a regression or intended behavior.

**Comment by poettering** [comment]
> shutdown[1]: Failed to wait for process: Protocol error

Hmm, there appears to be something wrong with `wait_for_terminate_with_timeout()`, but I am puzzled by what might cause this. @kyle-walker any idea?

This suggests that the mount() child process dies some abnormal death, i.e. SIGSEGV or such... But I don't see how that could ever happen...

**Comment by majster95** [comment]
On a arch linux forum user loqs write a solution. He suggest to mask mkinitcpio-generate-shutdown-ramfs.service, which trigger error. 

[](https://bbs.archlinux.org/viewtopic.php?pid=1767560#p1767560)

**Comment by loqs** [comment]
Perhaps @falconindy or @eli-schwartz can provide insight into the order of events mkinitcpio-generate-shutdown-ramfs.service triggers.  I can only link to the service file which also contains mkinitcpio.
https://git.archlinux.org/mkinitcpio.git/tree/systemd/mkinitcpio-generate-shutdown-ramfs.service and https://git.archlinux.org/mkinitcpio.git/tree/install/sd-shutdown

**Comment by rbisewski** [comment]
Thanks to all of the posters above for their ideas and helpful links :)

I've looked into this a bit more, I think a short term solution is to adjust a single line in the mkinitcpio-generate-shutdown-ramfs.service that only exists in arch-linux.

If the any of the arch-linux devs have time, I wouldn't mind if they took a quick glance at my suggestion. In any event, for current arch users I believe I have a better potential fix.

As mentioned by the poster above, currently the script looks like this:

```
[Unit]
Description=Generate shutdown-ramfs
DefaultDependencies=no
Before=shutdown.target
ConditionFileIsExecutable=!/run/initramfs/shutdown

[Service]
Type=oneshot
# /tmp could be umounted at this point
# use /run as temporary directory
Environment=TMPDIR=/run
ExecStart=/usr/bin/mkinitcpio -A sd-shutdown -k none -c /dev/null -d /run/initramfs
```

Adjusting the last line from `sd-shutdown` to `shutdown` results in a script that looks like the following:

```
[Unit]
Description=Generate shutdown-ramfs
DefaultDependencies=no
Before=shutdown.target
ConditionFileIsExecutable=!/run/initramfs/shutdown

[Service]
Type=oneshot
# /tmp could be umounted at this point
# use /run as temporary directory
Environment=TMPDIR=/run
ExecStart=/usr/bin/mkinitcpio -A shutdown -k none -c /dev/null -d /run/initramfs
```

As far as I can tell the error appears to go away. This also avoids both of the work arounds mentioned here and at the arch forums (e.g. masking or adding initramfs hooks) and allows the script to function as per before.

**Comment by falconindy** [comment]
That's not a fix, it avoids the entire point of the hook.

**Comment by rbisewski** [comment]
I was afraid of that; thanks for your quick reply though.

This `shutdown` I used above is the busybox alternative present as part of mkinitcpio, or something else?

Hmmm... I was hoping for quick solution, but it seems I'll have to look into it a bit more then to get the systemd hook to work again.

**Comment by falconindy** [comment]
> This suggests that the mount() child process dies some abnormal death

Presumably this is the code you're referring to:

```
                if (waitid(P_PID, pid, &status, WEXITED|WNOHANG) == 0) {
                        if (status.si_pid == pid) {
                                /* This is the correct child.*/
                                if (status.si_code == CLD_EXITED)
                                        return (status.si_status == 0) ? 0 : -EPROTO;
                                else
                                        return -EPROTO;
                        }
                }
```

Doesn't it also potentially imply that the process simply exited non-zero? That's far less interesting... Maybe the case of non-zero exit shouldn't be overloaded as EPROTO? Perhaps EOWNERDEAD.

I'm not sure I understand the crux of this bug report -- is this just about an error on the console, or is shutdown/reboot actually impacted functionally?

**Comment by patrick-ausderau** [comment]
@falconindy My machine does not poweroff (stay on showing that error message). I have to hard shut it down. So, impacted functionally.

**Comment by poettering** [comment]
So I prepped #8246 now which should bring back proper logging when umount()/remount() is failing during shutdown, which is pretty likely what is happening here. Would be good if someone with this problem could apply that PR, and reproduce the issue.

Most likely the arch initrd script is somehow causing some mount point to remain busy. No idea why though, but with that PR we should at least know for sure.

**Comment by falconindy** [comment]
As I've mentioned in [other bug reports](https://github.com/systemd/systemd/issues/6314#issuecomment-315096793), the "sd-shutdown" hook merely installs systemd-shutdown as /run/initramfs/shutdown, and executes that on pivot. Arch's home brewed [shell script](https://git.archlinux.org/mkinitcpio.git/tree/shutdown) which is included with the "shutdown" hook doesn't appear to have this problem.

**Comment by mus65** [comment]
I bisected this to commit 4c253ed1cae8b4df72ce1353ee826a4fae399e25 .

With current git (which includes #8246) I get the following on shutdown:
![20180223_192659](https://user-images.githubusercontent.com/1933789/36616045-b3881e2a-18e2-11e8-9b98-e559188a60c4.jpg)

**Comment by philmmanjaro** [comment]
Hmm, `introduce new safe_fork() helper and port everything over` this makes me wonder why so many times I get `fork: Resource temporarily unavailable` on a Ryzen CPU when compiling with all cores a new kernel. May be related or not ...

**Comment by vcaputo** [comment]
@philmmanjaro It's possibly your Ryzen just has enough cores that your parallel make is exhausting the number of processes alotted to your user via rlimit.  Run `ulimit -a` to see your limits, `ulimit -u` is the user processes one.  Generally it can be configured in `/etc/security/limits.conf` or `/etc/security/limits.d` in PAM-enabled systems.

**Comment by poettering** [comment]
> With current git (which includes #8246) I get the following on shutdown:

Hmm, so it appears something keeps those mounts busy...

**Comment by poettering** [comment]
> As I've mentioned in other bug reports, the "sd-shutdown" hook merely installs systemd-shutdown as /run/initramfs/shutdown, and executes that on pivot. Arch's home brewed shell script which is included with the "shutdown" hook doesn't appear to have this problem.

Hmm, so you are saying on Arch PID 1 transitions twice during shutdown, once from the regular pid1 to systemd-shutdown and then a second time to systemd-shutdown which however is a copy of the first, but copied to /run/initramfs/shutdown? And it's the second one that generates these warnings?

**Comment by poettering** [comment]
> Hmm, introduce new safe_fork() helper and port everything over this makes me wonder why so many times I get fork: Resource temporarily unavailable on a Ryzen CPU when compiling with all cores a new kernel. May be related or not ...

Yes, @vcaputo is right, what you are seeing looks very much unrelated, just some kind of fork limit reached, either RLIMIT_NPROC or maybe the TasksMax= value of your session or so.

**Comment by albakham** [comment]
I have the same issue during shutdown.
Inconvenience -> awfull errors on my clear setup 😊

**Comment by albakham** [comment]
I have the same issue during shutdown.
Inconvenience -> awfull errors on my clear setup 😊

**Comment by albakham** [comment]
I have the same issue during shutdown.
Inconvenience -> awfull errors on my clear setup 😊

**Comment by medhefgo** [comment]
> Hmm, so you are saying on Arch PID 1 transitions twice during shutdown, once from the regular pid1 to systemd-shutdown and then a second time to systemd-shutdown which however is a copy of the first, but copied to /run/initramfs/shutdown? And it's the second one that generates these warnings?

You know, it amuses me that every time arch initrd comes up, you are confused/fascinated about how it uses systemd-shutdown instead of some home-brew script.

Meanwhile, I am wondering why any initrd (including dracut as far as I can see) that uses systemd to handle early boot shouldn't also use systemd-shutdown for late shutdown. Imho, you should even gently nudge them to do just that...

**Comment by poettering** [comment]
> Meanwhile, I am wondering why any initrd (including dracut as far as I can see) that uses systemd to handle early boot shouldn't also use systemd-shutdown for late shutdown. Imho, you should even gently nudge them to do just that...

You have a point, @haraldh say something!

**Comment by frostschutz** [comment]
I added it to initcpio's shutdown hook ( `/lib/initcpio/shutdown` ), ran before the `umount -R /oldroot` - which is successful, so `/oldroot` is not busy other than various submounts. So this output is probably not useful?

https://gist.github.com/frostschutz/0d613c1dd2bdd551c557cbde971a6887

Is there a better place to add it? (particularly when not using the shutdown hook as that is when the message occurs)

**Comment by poettering** [comment]
Hmm, so if it's just the submounts, I really do wonder why `/oldroot/sys/fs/cgroup/devices` can't be unmounted... That's just strange...

**Comment by medhefgo** [comment]
Adding a fuser call to  the busybox shutdown hook won't help you if the sd-shutdown version has trouble unmounting stuff.

Maybe systemd-shutdown should list the pids and process names that keep mounts busy when in debug mode.

**Comment by frostschutz** [comment]
I did both shutdown and sd-shutdown (both results in the gist above, about the same though.)

I also tried to strace it just for kicks, but systemd-shutdown kills strace first thing. ;)

**Comment by medhefgo** [comment]
Dis you stuff a fork+exec to fuser into shutdown.c? Cause anything else is most likely useless.

**Comment by haraldh** [comment]
> Meanwhile, I am wondering why any initrd (including dracut as far as I can see) that uses systemd to handle early boot shouldn't also use systemd-shutdown for late shutdown. Imho, you should even gently nudge them to do just that...

Well, dracut disassembles more than systemd-shutdown at shutdown

**Comment by medhefgo** [comment]
> Well, dracut disassembles more than systemd-shutdown at shutdown

You mean this?
https://github.com/dracutdevs/dracut/blob/master/modules.d/99shutdown/shutdown.sh

I don't quite see what dracut is doing that sd-shutdown isn't. And if there were, it most likely should be added to sd-shutdown, no?

**Comment by haraldh** [comment]
dracut modules can install a shutdown hook to be executed here:
https://github.com/dracutdevs/dracut/blob/master/modules.d/99shutdown/shutdown.sh#L92

**Comment by poettering** [comment]
@haraldh i think the key point here is that dracut's shutdown logic should maybe invoke systemd-shutdown as last step again...

**Comment by hussamT** [comment]
Is this something that affects functionality in any way or is it harmless? I'd like to upgrade from 236.81 to 238 today and this is a work machine so I would like to not face regressions.
Thank you.

**Comment by medhefgo** [comment]
I finally found the culprit: https://github.com/systemd/systemd/blame/master/src/core/umount.c#L518

The continue was added with the umount in fork changes. It's trying to handle the error case for remounting the mountpoint read-only, but this is just a precautionary measure, so any errors were originally ignored. Current code will simply skip trying to unmount entirely if it cannot remount read-only (which, apparently, these api file systems don't support?).

Removing the continue solves the immediate issue, but adds other ugliness to output. Since right now every umount failure is logged, we get a few umount errors, even though they will be cleaned up later by sd-shutdown in initramfs.

@poettering I'm not quite sure how to approach this, but I would say we should only debug log umount issues. But if we are running in initrd or if there is no initrd that we will later switch to, we ought to error log instead.
Also, slightly related, should we add a check to skip remounting api filesystems like we do for network filesystems just for future precautions?

@haraldh well, to be quite frank, calling some shutdown hooks isn't exactly rocket science to add to sd-shutdown. And the world could be removed from yet another evil shell script :D

@hussamT The root filesystem is currently left mounted, but in read-only mode. So data loss should not be occurring.

**Comment by hussamT** [comment]
On Tue, 2018-03-06 at 12:56 +0000, Jan Janssen wrote:
> @hussamT The root filesystem is currently left mounted, but in read-
> only mode. So data loss should not be occurring.

Great. That's what I was looking for. In addition, I didn't get an
automatic fsck on reboot after upgrading to 238 so there is indeed no
data loss. Thank you again for the explanation.

**Comment by medhefgo** [comment]
@haraldh  Actually, while reading logs carefully I just now noticed that we actually already have shutdown hooks: https://github.com/systemd/systemd/blob/07a35e846b7986d3c02eca99fa291f6869035c58/src/core/shutdown.c#L451

**Comment by tonylambiris** [comment]
Same issues, Arch on all various hardware I run -- adding shutdown to `/etc/mkinitcpio.conf` appeared to remedy the timeouts.

**Comment by thyeun** [comment]
question about adding ```shutdown``` to ```/etc/mkinitcpio.conf```, will it create another issue or not?

**Comment by kyawthusoe3142** [comment]
This issue is still present in systemd 238.133.  How is this closed?

**Comment by medhefgo** [comment]
Obviously, because it was merged after 238.

**Comment by thyeun** [comment]
=.= because they dont have a proper solution, than the ```close``` solution is the best solution, it happen again on 238.133 latest version that i just upgrade today.

**Comment by poettering** [comment]
@kyawthusoe3142 ask your distro to backport #8429

**Comment by MaxXor** [comment]
@poettering Arch Linux systemd 238.133 includes this PR and the messages still show up on reboot/halt.

**Comment by thyeun** [comment]
@MaxXor, i think what @poettering  asking is every time a new upgrade, each distro have to re-do the backport (fresh re-do) again. Correct me if i'm wrong.

So, it is this is the way of doing things? =.=

**Comment by hussamT** [comment]
Only if https://github.com/systemd/systemd-stable/commits/v238-stable contains does not contain #8429

**Comment by medhefgo** [comment]
@MaxXor Please get your facts right. I only see the memleak patch of my pr was backported.

**Comment by MaxXor** [comment]
@medhefgo Sorry, I didn't notice it was on systemd-stable repo...

**Comment by philmmanjaro** [comment]
@kyawthusoe3142 Please check the [PKGBUILD](https://github.com/manjaro/packages-core/blob/master/systemd/PKGBUILD) from Manjaro. There all needed backport patches are added on top of 238.133-1:

```
_backports=(
  # core: sd-shutdown improvements (#8429) (#8155)
  '0494cae03d762eaf2fb7217ee7d70f615dcb5183'
  '1d62d22d9432d5c4a637002c9a29b20d52f25d9a'
  '3bc341bee9fc7dfb41a131246b6fb0afd6ff4407'
  '8645ffd12b3cc7b0292acd9e1d691c4fab4cf409'
  'e783b4902f387640bba12496936d01e967545c3c'
  '456b2199f6ef0378da007e71347657bcf83ae465'
  # Use libmount in systemd-shutdown, add tests (#8452) 
  '95b862b0540ac24999fdfbd670e8744bb626729a'
  '6fa392bf911ef17caf4c13e839236c8edd11bfaf'
  'a6dcd22976a10d7733de91aca240427c5def1bc9'
  '1fd8edb53aa5894e9b8cbec87376ecce660d3087'
  '71ae04c40081d11cc412d731d59c4a25e6bc5f07'
  # shutdown: Don't limit unmount attempts prematurely (#8469)
  'ac9cea5ba30acbf17fd431a4a4092c4dbee23593'
  # nspawn: wait for network namespace creation before interface setup (#8633)
  '7511655807e90aa33ea7b71991401a79ec36bb41'
)
```

**Comment by thefzsalam** [comment]
It happens to me too on a fresh install of Arch Linux

**Comment by thefzsalam** [comment]
Occasionally, it gets stuck at 
`Reboot: power down`, when I run `shutdown -h now`

**Comment by GopherJ** [comment]
Anyone knows how to update to the version with this fix? This bug nearly caused the death of my computer...when I leave the company I didn’t see this error and it

**Comment by philmmanjaro** [comment]
@GopherJ: at Manjaro we use `_commit='de7436b02badc82200dc127ff190b8155769b8e7'` for `pkgver=239.0` and the following backports:

```
_backports=(
  # resolve
  86b112a315464604f4b40222d8bbd912432d640c
  a5042ec4d7840f79d49688f07bf9bae7203ac50e
  fa6a69d7837f1d5fcd0ba279b51a41a26badaf03
  6da95857c19202120af76871c91a47a0f23aed8d
  b02a7e1aeadda724976290528fb864f99f1e396b
  5a01b3f35d7b6182c78b6973db8d99bdabd4f9c3
  a661dc36f68b5ebb1247a503533f8067ff8c0432
  f43580f17d9977ea330deacc8931982e41a49abf
  cc7d50a5714bc810af51b0c55be12b4f55acc089
  052a85d18859faeb38b01c9bbec560afe226e2a4
)
```

**PKGBUILD** can be found [here](https://gitlab.manjaro.org/packages/core/systemd).

**Comment by loupianche** [comment]
Here, the issue is not fixed... It happens randomly on ArchLinux with the same error message:

![capture d ecran du 2019-03-06 08-54-51](https://user-images.githubusercontent.com/43648060/53864757-9ae4dd80-3fed-11e9-9a71-aaafe827ff09.png)

**Comment by HerroBert** [comment]
And still a problem on Ubuntu 18.04.2.

**Comment by sol8712** [comment]
One year later....
Same issue here on Ubuntu 18.04.02.
It came up after I had barley touched the USB WiFi chip then Network Manager crashed hard and the process could not be killed via terminal. During shutdown it stayed on a system stop for over 10 minutes before finally displaying the error "Failed to wait for process: Protocol error" and in the end had to hold the power button for force restart.

**Comment by johndoe71rus** [comment]
I noticed this behavior on ubuntu 14.04 and kernel 4.15. I tested new kernels from https://kernel.ubuntu.com/~kernel-ppa/mainline/ .First i decided that this is a kernel problem. Because on the same system but with different cores, different behavior. Now on a laptop with a 4.15.5 kernel, I can send the system to hibernate and the power will turn off. But when i turn off system or reboot, the power does not turn off. If I’m not mistaken, then on the 4.14.13 kernel the laptop rebooted and turned off perfectly. Today I tried on this laptop lubuntu 18.04.3 with the kernel 5.2.8 and it did not turn off the power off. Last console message

> Started Show Plymouth Power Off Screen
Starting Power-Off
[... ] systemd-shutdown [1]: Failed to wait for process: Protocol error

**Comment by mort3za** [comment]
I see this error on mint cinnamon 19.3

**Comment by yuriescl** [comment]
Getting this error on Mint 19.3 as well.

**Comment by annchous** [comment]
I have the same problem now 🤠👍
Ubuntu 18.04 and 20.04, LTS versions 
Please god fix it...

**Comment by yuriescl** [comment]
> Getting this error on Mint 19.3 as well.

Issue was fixed after a full system upgrade. I don't know which package fixed it, but nvidia and systemd were included in the list of upgraded packages.

**Comment by keszybz** [comment]
@willfliaw, @annchous, @yuriescl, @mort3za, @sol8712, @johndoe71rus, @loupianche, @thefzsalam, ..., anyone else: please don't report the status in your favourite distro here. This tracker is for **upstream**. We can't know and don't care what the latest version of Ubuntu KDE or Arch is doing: which version of the code it is running, which patches have been applied, what the initrd setup is, or anything else really. And old ticket for an issue fixed upstream two years ago is similar to /dev/null.
