### ISSUE TITLE
[RFE] IWD support for systemd-networkd

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#8157]
### Submission type

 - Request for enhancement (RFE)

## Description

IWD, the new Intel Wireless daemon got its first release now[1].
It has full dbus support and other neat features. 
I would like to suggest IWD support in `systemd-networkd`.

[1] https://www.kernel.org/pub/linux/network/wireless/

**Comment by CosmoJG** [comment]
Is IWD support complete? What remains to be done?

**Comment by shibumi** [comment]
@CosmoJG I guess it hasn't been touched yet. PRs are welcome. Although I have still no idea how this support would look like. The best idea I have is to have a relationship between wireless networks/ESSIDs and the `systemd-networkd` configuration for the wireless device. So I thought about a new segment for the `Match` command.

Something like this:
`/etc/systemd/network/wlp3s0-home.network`
```
[Match]
Name=wlp3s0
ESSID=HOME

[Network]
DHCP=ipv4
DNS=1.1.1.1

[DHCP]
UseDNS=no
```

`/etc/systend/network/wlp3s0-corp.network`
```
[Match]
Name=wlp3s0
ESSID=CORPORATION_WIFI

[Network]
Address=<my fancy static IP at corporation XY>
Gateway=<my fancy gateway for corporation XY>
```

**Comment by shibumi** [comment]
@amishxda should be possible via IWD dbus API. But we would need a new `wireless` target for this, I guess. Because you need to wait for wireless connection until you do all the network stuff.

**Comment by yuwata** [comment]
I've created #12842 for this RFE.

**Comment by johannbg** [comment]
@yuwata wont any systemd networkd integraton with iwd conflict with iwd upstream decision of handling iwd configuration on it's own as in the iwd will manage the DHCP/Static IP assignment? Is it not best to be in contact with iwd upstream @holtmann @denkenz etc to ensure that we dont end up with conflicting implementation which ends up misconfiguration the network and or confuse end users and or incorrect network implementations ( which seems to be the case here with BSSID based on Denis responses upstream )? 

This all boils down with what's the end game here with WIFI support I mean wpa_supplicant is on it's way out in the linux eco system as in it's being replaced with iwd and iwd seems to be intent on being island in the core/baseOS ( read as not part of consolidated core/baseOS platform thus not part of the system/service management framework thou arguably it belongs there ) and wants to manage it's own network configuration so why should there be an implementation of wpa_supplicant/iwd support in any shape or form to begin with, what purpose does it serve and or problem does it solve?

**Comment by zabbal** [comment]
I'd say that having all network configuration (wired and wireless) in a single place is plain convenient. Besides it enables things like setting "Metric=" in a coherent way as well as "[Bridge]" without race-condition.

**Comment by shibumi** [comment]
I have discussed this whole issue with one of the iwd devs. According to him, there should be no issue. Both ways can co-exist, but it's preferred to let iwd do the ip management, because systemd-networkd has not enough information about roaming etc. systemd-networkd would simply re-do DHCP at reconnect, with ip management in iwd the connection will be more stable (at least from the user point of view). On the other hand the feature is very appreciated for QoS, routing, etc.

**Comment by johannbg** [comment]
Why was it preferred to let iwd do the ip management? 

I would think one would probably want to add a switch on either side or both which configures which one is doing the ip management right? ( such "ControlledBy=" configuration switch is needed for more like keepalived etc  )

**Comment by shibumi** [comment]
it's preferred to let iwd do ip management mostly because of roaming and standards like `802.1ai`. Systemd-networkd has not enough information to do roaming of wifi networks and for stuff like `802.1ai` systemd-network is completely the wrong thing.
