### ISSUE TITLE
Keyring sharing for mounts not fixed by #6832

### ISSUE THREAD

**Issue by eternaleye** [systemd/systemd#8159]
### Submission type

 - Bug report

### systemd version the issue has been seen with

The issue is present on systemd >= v233 - specifically, it was introduced in 74dd6b5

### Used distribution

Arch, [NixOS](https://github.com/NixOS/nixpkgs/issues/32279)

### Expected behaviour you didn't see

Mounting an encrypted `bcachefs` filesystem (or an `ecryptfs` filesystem with the keyring already populated) should succeed.

### Unexpected behaviour you saw

Mounting fails.

### Steps to reproduce the problem

1. Run `bcachefs unlock` on the filesystem (possibly in initramfs)
2. Allow systemd to try and mount the filesystem

### Proposed resolution

Add an `x-systemd.keyring-mode=shared` fstab flag, and allow `KeyringMode=shared` in `mount` units.

Possibly infer a default for filesystems known to use this (bcachefs, ecryptfs).

**Comment by poettering** [comment]
hmm, i figure for mount units we should simply share the keyring by default.

**Comment by hyperfekt** [comment]
This problem somehow still occurs on NixOS with version 238 (which was supposed to have fixed the issue if I am not mistaken). See the NixOS issue for details.
