### ISSUE TITLE
systemctl set-property Segmentation fault in message_append_basic.13528 ()

### ISSUE THREAD

**Issue by Nopius** [systemd/systemd#8161]
### Submission type
 - Bug report

### systemd version the issue has been seen with

> 219-42.0.2.el7_4.7

### Used distribution

> Oracle Linux 7.1

### In case of bug report: Expected behaviour you didn't see

> normal run

### In case of bug report: Unexpected behaviour you saw

>  Segmentation fault (core dumped)
Core was generated by `systemctl set-property user-500.slice BlockIODeviceWeight=/dev/vdb 100'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fc775d23831 in __strlen_sse2_pminub () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install systemd-219-42.0.2.el7_4.7.x86_64
(gdb) bt
#0  0x00007fc775d23831 in __strlen_sse2_pminub () from /lib64/libc.so.6
#1  0x00007fc776ec8b29 in message_append_basic.13528 ()
#2  0x00007fc776ecebf9 in bus_message_append_ap ()
#3  0x00007fc776ecf0a5 in sd_bus_message_append ()
#4  0x00007fc776ecfbd8 in bus_append_unit_property_assignment ()
#5  0x00007fc776edb2fd in set_property.3263 ()
#6  0x00007fc776eb6d70 in main ()
(gdb) quit

### In case of bug report: Steps to reproduce the problem

> run as root:  systemctl set-property user-500.slice BlockIODeviceWeight="/dev/vdb 100"
this is qemu-kvm LVS, user-500.slice exists, /dev/vdb device exists (virtual drive inside qemu-kvm)

**Comment by evverx** [comment]
The issue seems to have been fixed in 096a4d53dcafb118.

By the way, I think it would be great to add a link to https://github.com/systemd/systemd/releases to https://github.com/systemd/systemd/blob/master/.github/CONTRIBUTING.md. It seems that the phrase "the two most recently released versions" doesn't help much to find out which versions are meant exactly.
