### ISSUE TITLE
Use gettext instead of inline translations in the .policy files

### ISSUE THREAD

**Issue by gunnarhj** [systemd/systemd#8162]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Ubuntu

### Description

For each "&lt;message&gt;" and "&lt;description&gt;" line meson adds translations to the .policy files:

	<description>Set system locale</description>
	<description xml:lang="be">Усталяваць сістэмную лакаль</description>
	<description xml:lang="be@latin">Ustaliavać sistemnuju lakaĺ</description>
	...

The installed .mo files, which also include the translations, are not actually used at run time.

A better setup would be to state the gettext-domain in the .policy files:

	<description gettext-domain="systemd">Set system locale</description>

and stop meson from adding those inline translations.

I proposed this modification when building systemd on Ubuntu:

	for f in debian/systemd/usr/share/polkit-1/actions/* \
	  debian/systemd-container/usr/share/polkit-1/actions/*; do \
		sed -r -i -e /xml:lang=/d \
		  -e 's/<(message|description)>/<\1 gettext-domain="systemd">/g' $$f; \
	done

but it was considered too 'hackish', and @martinpitt suggested that I'd better propose the change upstream.

This proposal may appear to not change the behavior, but from an Ubuntu POV it does. We offer the translators a possibility to modify and add translations to the downstream .mo files, and currently such efforts won't take effect.

Thanks!
Gunnar Hjalmarsson

P.S. A detail I noticed when working on this is that `src/resolve/org.freedesktop.resolve1.policy.in` is not included in `po/POTFILES.in`. It should probably be added.

**Comment by yuwata** [comment]
Thanks. See #8163.

**Comment by gunnarhj** [comment]
Thanks for addressing my P.S. :)

I have prepared [0001-Gettextize-the-policy-files.patch.gz](https://github.com/systemd/systemd/files/1729320/0001-Gettextize-the-policy-files.patch.gz) which is one way to fix this issue. Looking forward to your feedback.

**Comment by keszybz** [comment]
Wow, this seems to work. Thanks for the patch, I'll submit it as a PR with some further simplifications.

**Comment by gunnarhj** [comment]
@keszybz: Great that you like the idea. I looked at your branch, and [this commit](https://github.com/keszybz/systemd/commit/d72c5205) confuses me. Aren't those files needed to extract the translatable strings from the .policy files when creating the .pot template?

**Comment by mbiebl** [comment]
> @keszybz: Great that you like the idea. I looked at your branch, and this commit confuses me. Aren't those files needed to extract the translatable strings from the .policy files when creating the .pot template?

I did a test-build with PR #8202. It seems it doesn't matter whether we have a local copy of the its files. Those local files are now always ignored. Which in turn means, policykit-1 needs to be installed for ```ninja systemd-pot``` to work properly.
Would there be a way to tell gettext to look for the local copy of the its file?

**Comment by mbiebl** [comment]
btw, this is currently the error message I get when running ```ninja systemd-pot```

```
[0/1] Running external command systemd-pot.
xgettext: warning: file 'src/core/org.freedesktop.systemd1.policy.in.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/hostname/org.freedesktop.hostname1.policy.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/import/org.freedesktop.import1.policy.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/locale/org.freedesktop.locale1.policy.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/login/org.freedesktop.login1.policy.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/machine/org.freedesktop.machine1.policy.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/timedate/org.freedesktop.timedate1.policy.in' extension 'policy' is unknown; will try C
```

But on a closer look, this problem already existed in previous releases

**Comment by gunnarhj** [comment]
@mbiebl: The reason for my attention to those files is that we want to create `systemd.pot` when building for Ubuntu, and we are currently struggling with a proper way to do it. @martinpitt is [disinclined to include policykit-1 in the build dependencies](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1707898/comments/24).

I don't know how you provide updated `.po` files to the translators upstream. Maybe that's unrelated to the build, and in that case you are probably right in that `polkit.{its,loc}` is not needed in the source.

> Would there be a way to tell gettext to look for the local copy of the its file?

I suppose there is a way, but so far I haven't figured out how to do it. (It's probably off topic for this issue.)

Those warning messages look familiar, btw. 😞

**Comment by keszybz** [comment]
@piotrdrag @splantefeve @AsciiWolf : what is your workflow, should the .pot file be in tree?

**Comment by gunnarhj** [comment]
@keszybz wrote:
> what is your workflow, should the .pot file be in tree?

That would have helped if it wasn't for the fact that an additional file with translatable strings (`src/fsckd/fsckd.c`) is created in Debian/Ubuntu through a patch. So we need to create `systemd.pot` at build time in any case.

I think I have found a [solution for Ubuntu](https://launchpadlibrarian.net/357369348/0001-Extract-translatable-strings-from-policy-files.patch), even if I haven't got feedback yet. With that patch committed in Debian, together with the commits which are about to happen upstream as a result of this issue, I think this thing would be sorted out, and the Ubuntu side would be happy. :smile: Can't speak for other distros, though.

**Comment by piotrdrag** [comment]
> @piotrdrag @splantefeve @AsciiWolf : what is your workflow, should the .pot file be in tree?

GNOME’s [Damned Lies](https://l10n.gnome.org/module/systemd/) builds a .pot file for me ([using](https://git.gnome.org/browse/damned-lies/tree/damnedlies/settings.py#n160) .its/.loc files from the upstream polkit git repo, so it doesn’t care for the famous problem of unreleased polkit that’s plaguing distros). It doesn’t need a .pot file to be in tree.

**Comment by keszybz** [comment]
Thank you for the explanations. I think I now understand how this is all supposed to work ;)

I pushed an updated version that keeps `polkit.{its,loc}` and fixes the `systemd-pot` target.

**Comment by piotrdrag** [comment]
Hopefully systemd translations will continue to work on Fedora, which traditionally merges translations to .policy (and .desktop) files.

**Comment by keszybz** [comment]
I tested systemd with those patches (i.e. with unmerged .policy files), and translations appear properly when systemctl is invoked. I didn't actually test the graphical auth dialog, but I expect it to work too, since it's the same policykit code. So, my understanding is that will not break anything in Fedora.

**Comment by mbiebl** [comment]
I also tested the graphical dialogs on GNOME, KDE Plasma and polkit-gnome under openbox. All worked fine with the translations being shipped in the .gmo files. In the  hope that there aren't any tools which parse the policy files directly, I've merged #8202

**Comment by gunnarhj** [comment]
@keszybz wrote:
> I pushed an updated version that keeps `polkit.{its,loc}` and fixes the `systemd-pot` target.

That was an extra bonus, thank you for that! Please note that from an Ubuntu POV it would be great if you could keep it that way also going forward, since it's handy for us when building systemd downstream.

Thanks for fixing this issue so quickly!

**Comment by samy-mahmoudi** [comment]
@gunnarhj : There is indeed a way to control how xgettext and msgfmt search for .its files since the realease of gettext-0.19.8 ([release notes](https://lists.gnu.org/archive/html/info-gnu/2016-06/msg00003.html)).

The search path can be modified by setting environment variables:

1. $GETTEXTDATADIR or GETTEXTDATADIR                                         
2. $GETTEXTDATADIRS                                                          
3. $XDG_DATA_DIRS, where each element is suffixed with "gettext"             
4. $GETTEXTDATADIR or GETTEXTDATADIR, suffixed with PACKAGE_SUFFIX

Source: line 92 of [http://git.savannah.gnu.org/cgit/gettext.git/tree/gettext-tools/src/search-path.c](http://git.savannah.gnu.org/cgit/gettext.git/tree/gettext-tools/src/search-path.c)

However, note that in all cases files should be placed in an "its" directory.

**Comment by gunnarhj** [comment]
@samy-mahmoudi: Yes, but there is a bug which was fixed through [this commit](http://git.savannah.gnu.org/gitweb/?p=gettext.git;a=commitdiff;h=a0cab233) and which was the reason for the difficulties I encountered and mentioned above.
