### ISSUE TITLE
systemd-networkd DHCP search domains option

### ISSUE THREAD

**Issue by skimj** [systemd/systemd#8174]
### Submission type
 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with
> 237.31-1

### Used distribution
> Arch Linux

### Expected/Unexpected behaviour:

> I expected that by enabling `[DHCP]: UseDomains=true` in network configuration, the DHCP client would use DHCP provided search domains. The client only uses DHCP provided search domains if the server specifies this option as "forced"

I think that this can be broken into two parts. First, I think that the DHCP client should always get the search domains option (119). The decision about what to do (or not to do with that information) could be separated.

1. I'm using dnsmasq as the DHCP server. If I use `dhcp-option-force=option:domain-search,example.com` on the server, then `DOMAIN_SEARCH_LIST=example.com` appears in `/run/systemd/netif/leases/2` client lease info. If I use  `dhcp-option=option:domain-search,example.com`, then the lease info file does not contain a `DOMAIN_SEARCH_LIST` entry (the client did not request this option). For comparison, providing the NTP option from the server causes the corresponding entry in the client lease whether the option was "forced" or not. Again, I think the client should always get this information, even if it's not consumed by the network configuration.

2. Setting the `UseDomains=true` network configuration option adds both the domain and the domain-search values to "Search Domains" as reported by `networkctl status` and "DNS Domain" as reported by `systemd-resolve --status` and conversely no such search domains are setup when `UseDomains` is not set (or false). I think that this behavior of combining the domain and the domain-search values is acceptable but then I would expect `UseDomains` to also cause the DHCP client to request the domain-search option from the server (if it isn't always requested per the first section). Alternatively, a new option would need to be provided such as `UseSearchDomains`.

**Comment by piotr-dobrogost** [comment]
I'm observing this issue on Fedora 28 with systemd 238.
What's the current status?

**Comment by MelkorLord** [comment]
Ubuntu Bionic 18.04 with systemd 237

This is highly frustrating as I have to modify my dhcpd.conf globally to get those search domains.

Furthermore, this is quite inconvenient as dhcpd does not allow to "just add an option to requested ones" kind of thing. I end up having to force a hardcoded list of dhcp options like `option dhcp-parameter-request-list 1,3,6,12,15,26,42,121,119;` which I utterly hate :-(

It would be nice to finally get a proper fix on this one.

**Comment by virtualdxs** [comment]
Almost a year since this was last brought up. +1 to this issue. The DHCP spec says that a client should request options they respect, and servers should only send options that were requested by the client. Therefore, systemd-networkd does not work with a DHCP server that follows spec. Any chance of this getting fixed?

**Comment by yuwata** [comment]
Fix is waiting in #13054. But I've not tested the PR yet. So, if possible, please test the PR. Thank you.

**Comment by piotr-dobrogost** [comment]
Just for reference, someone hit this – [Does systemd-networkd / systemd-resolved add search domains specified in DHCP?](https://superuser.com/q/1490670/664)
