### ISSUE TITLE
initrd-cleanup.service does unclean shutdown of services

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8179]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v237

### Used distribution

237

### Bug report

    Description=Cleaning Up and Shutting Down Daemons

but

    ExecStart=@rootbindir@/systemctl --no-block isolate initrd-switch-root.target

it relies on isolate to stop the other units.  AFAIK isolate does not imply any additional ordering constraints.  Therefore services are not guaranteed to have stopped cleanly prior to `systemctl switch-root`, which then sends SIGKILL to all remaining processes.

Edit: have you guessed how confused I am about `isolate` yet?

I'm not sure whether this relates to tradition or not.  My concern would be that services are killed while they are updating something in /run.  The contents of /run carry over across switch-root.

journald is an example of a service where forcibly crashing it creates an observable difference, and which uses /run.  It also could also have consumed a message but not written it to the filesystem yet.  Causing the message to be silently lost.   Although journald is also a special case regarding this issue.  We have been deliberately keeping journald running for initrd-switch-root.target, so a journald-specific change will also be required to avoiding killing journald uncleanly.

## Solution?

In principle we should be able to pull in `shutdown.target` instead, to provide the necessary conflicts and ordering dependencies.  The question is whether this change would break something e.g. that dracut relies on at the moment.

**Comment by sourcejedi** [comment]
Ick.  Or it might be safer for DefaultDependencies=yes to imply Conflicts and Before on initrd-switch-root.target, when we run inside the initrd.

And at least when you read `man systemd.service`, this would mean you'd get a hint that you might want to add them manually when you use DefaultDependencies=no.

**Comment by arvidjaar** [comment]
> My concern would be that services are killed while they are updating something in /run.

There were worse things. Services left over from initrd and not re-run on real root (cannot find issue, there was openSUSE bug report); or e.g. https://github.com/systemd/systemd/issues/4343. The problem is it requires **every** unit in initrd be correctly ordered against switch root.

We already do things differently depending on whether we are in initrd or not, so redefining `DefaultDependencies` may work. What is not nice is hardcoding specific units in systemd binary. Ability to configure default dependencies externally looks more flexible. The initrd could simply install different configuration, that could be easily adapted if needed.

**Comment by sourcejedi** [comment]
Thanks for pointing out the previous issue!  I guess that's the sort of information I was fishing for.

> The problem is it requires *every* unit in initrd be correctly ordered against switch root.

Exactly.  Surely it's right that DefaultDependencies would imply the ordering and conflict with switch-root.

"Not nice" is a fair reaction to hardcoding it, perhaps in ~7 different unit types. Personally I think adding another indirection via config file is worse.  And yet I'm not sure of my approach:

I thought of a hack.  DefaultDependencies orders against (and requires) sysinit.target.  If none of the switch-root units (including the custom cleanup) pull in sysinit.target, then we're shutting that down, so you can order switch-root against it and you're done.

Good news: we're already doing that.  Because initrd-udevadm-cleanup-db.service conflicts with systemd-udevd.service, which is ordered Before=sysinit.target.   Bad news: surely this means people already unwittingly rely on the hack, and it breaks if sysinit.target ever gets pulled in to switch-root.target.

... or if we changed isolate to avoid shutting down units pulled in by devices, but one of those units pulled in sysinit.target.  Which was my hope to tame `isolate` (https://github.com/systemd/systemd/issues/6505#issuecomment-365654950).

So right now I'm giving up on either.  This report doesn't have a specific failure I can point at, so it seems best to close this one.  I can limit myself to touching the journald special case.
