### ISSUE TITLE
networkd: surprising behavior of .network files with lower case name

### ISSUE THREAD

**Issue by wlcrls47** [systemd/systemd#818]
Somewhat related to #717, but different because it's not an empty "[Match]" section, but an empty "Name" variable, since it appears to be case sensitive.

I run a bridged network created by networkd.  In my /etc/systemd/network/br0.network, I mistakenly didn't hit shift as I typed the line "Name=br0", instead typing "name=br0".

It brought down my network.  On that computer, I could ping any (including unassigned) IP address on its subnet, and itself responded to it.  No other computer would work on the subnet, complaining that its IP address is in use/conflict.

I'd suggest making [Match].Name required, but I see on #717 that likely won't happen.

So, instead, I'd suggest:
- Making variable names case insensitive
- Warning on unused variable names (someone types Nmae instead, they get a warning rather than down their subnet)

Due to the severity of an empty [Match] section, or an empty [Match].Name variable, I'd still support the idea of both of these being required.  [Match].Name=all could become valid, if someone really wants to do that.  Either the #717 mistake or this one bringing down an entire subnet is pretty severe.  (I Admit I'm not sure if the #717 user experienced that severity.)

**Comment by keszybz** [comment]
> Making variable names case insensitive

No. Everything is case sensitive in systemd and should stay this way.

> Warning on unused variable names

We are doing that already:

```
Aug 02 13:32:59 laptop systemd-networkd[6602]: [/etc/systemd/network/80-dhcp-en.network:3] Unknown lvalue 'name' in section 'Match'
```

**Comment by poettering** [comment]
I agree with @keszybz. We already warn about unknown config settings in all tools. And we should not be case insensitive, this is UNIX after all. Sorry.
