### ISSUE TITLE
systemd-sysv-install uses ROOT variable from environment for chrooting

### ISSUE THREAD

**Issue by LarsMichelsen** [systemd/systemd#8180]
### Submission type

 - Bug report

### systemd version the issue has been seen with

232

### Used distribution

debian stretch

### Bug report

systemd-sysv-install uses `ROOT` variable from environment when not set via `-r` and tries to execute update-rc.d chrooted to the content of this variable.

I'm am a bit unsure whether or not this really is a bug, but since it was a total surprise for me when I found the cause of the issue and I did not find any documentation about this behaviour, I think this is a bug.

### In case of bug report: Expected behaviour you didn't see

```
root@Klappspaten:/# systemctl enable ssh
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
Created symlink /etc/systemd/system/sshd.service → /lib/systemd/system/ssh.service.
```

### In case of bug report: Unexpected behaviour you saw

When ROOT is e.g. set to /dev/sda1, this issue occurs:

```
root@Klappspaten:/# systemctl enable ssh
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
chroot: cannot change root directory to "'/dev/sda1'": No such file or directory
```

### In case of bug report: Steps to reproduce the problem

Simply set the environment variable and try to enable a service that is also available as SysV-Init-Script

```
root@Klappspaten:/# export ROOT=/dev/sda1
root@Klappspaten:/# systemctl enable ssh
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ssh
chroot: cannot change root directory to "'/dev/sda1'": No such file or directory
```

**Comment by mbiebl** [comment]
This is a downstream issue, /lib/systemd/systemd-sysv-install is not provided by the upstream systemd sources.

**Comment by mbiebl** [comment]
which means, you should file this against the Debian package in the debian bug tracker

**Comment by LarsMichelsen** [comment]
Thanks! Wasn't sure about this, because I could find the problematic script here too:

https://github.com/systemd/systemd/blob/974fdd26261088760ae6932b19491b0ddec5d1fb/src/systemctl/systemd-sysv-install.SKELETON

**Comment by mbiebl** [comment]
Fair point. The skeleton file should probably fixed as well to unset ROOT.
 Please also file this as well downstream though. The probablematic file can be found at
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/systemd-sysv-install

**Comment by LarsMichelsen** [comment]
Debian bug report is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890436
