### ISSUE TITLE
Provides Directive

### ISSUE THREAD

**Issue by virtualdxs** [systemd/systemd#8186]
### Submission type

 - Request for enhancement (RFE)

Apologies if this is a dupe but I couldn't figure out a search that would cover this. 

I'm looking for a `provides` feature, similar to how package managers implement it. Essentially, as an example, suppose `MyDatabaseApp{1..20}` has a line that says `Requires=mysql.service`. But MySQL is deprecated in favor of MariaDB. As of right now (I believe), in order to switch to MariaDB I would need to `systemctl edit` 20 different unit files. My goal is to be able to say in mariadb's unit file `Provides=mysql.service` so anything that depends on mysql works with MariaDB.

**Comment by bl33pbl0p** [comment]
Use `Alias=` in the [Install] section for this purpose while enabling the unit, or just create a symlink with the new name to the old name in the unit search path (so for example `ln -s /etc/systemd/system/mysql.service /usr/lib/systemd/system/mariadb.service`). I know what you are relating this to (BSD like Requires-Provides), but you already have a way to do the same.
