### ISSUE TITLE
systemd-cgtop and systemd-nspawn container infos

### ISSUE THREAD

**Issue by cyayon** [systemd/systemd#8189]
### Submission type

 - Bug report

### systemd version
236 and 237 

### Used distribution
Archlinux (last update)

### Expected behaviour
Even with Accounting enable in /etc/systemd/system.conf and user.conf, the no information about processes inside a nspawn container with systemd-cgtop -M \<containername\>.
/etc/systemd/system.conf
DefaultCPUAccounting=true
DefaultIPAccounting=true
DefaultIOAccounting=true
DefaultBlockIOAccounting=true
DefaultMemoryAccounting=true
DefaultTasksAccounting=true

### Unexpected behaviour
There is only one line in systemd-cgtop -M \<containername\>
/machine.slice/\<containername\>.service
> …
the container is started with command line:
 /usr/bin/systemd-nspawn --network-bridge=br0 --link-journal=guest --keep-unit --boot --directory=\<containerrootpath\> --machine=\<containername\>

thanks.

**Comment by poettering** [comment]
Not sure I follow. Are you running systemd-cgtop on the host or in the container?

**Comment by cyayon** [comment]
I am running from host and i would like to show processes (and resources usage) inside the container

**Comment by poettering** [comment]
on cgroupsv1 controller delegation is not safe, and hence not done by nspawn.

Are you using cgroupsv2 or cgroupsv1? (i.e. the unified hierarchy?)

**Comment by cyayon** [comment]
sorry, but i do not understand what you mean, could you please explain me how to check ?

**Comment by poettering** [comment]
Boot with `systemd.unified_cgroup_hierarchy` on the kernel cmdline which will give you cgroupsv2 support, and delegation of cgroup controllers should be safe, so that containers can manager their own resources. If you don't then you'll get cgroupsv1 instead, where delegation is not safe, and where containers won't get their own resource management.

**Comment by poettering** [comment]
Ping

**Comment by poettering** [comment]
Let's close this due to lack of response
