### ISSUE TITLE
pull-dkr: When pulling from a v2 registry, layer subvolumes get deleted

### ISSUE THREAD

**Issue by petrosagg** [systemd/systemd#819]
According to the documentation of `machinectl pull-dkr`:

```
This command downloads all (missing) layers for the specified container and places them
in read-only subvolumes in /var/lib/machines/. A writable snapshot of the newest layer is
then created under the specified local machine name. To omit creation of this writable
snapshot, pass "-" as local machine name.

The read-only layer subvolumes are prefixed with .dkr-, and thus not shown by list-images,
unless --all is passed.
```

However, if it's pulling from a v2 registry, all layer subvolumes are deleted in the end and only the last writable snapshot is kept. 

https://github.com/systemd/systemd/blob/master/src/import/pull-dkr.c#L492-L504

**Comment by fishface60** [comment]
Not exactly, it imports all the new layers into a temporary subdirectory, it only deletes layers that were produced by that import.
I assume this is for resource management, as otherwise there's no mechanism for cleaning up the intermediate layers.
Personally, I'd prefer having to clean up intermediate layers manually occasionally than every import not sharing progress and backing data, as it did in the repository format v1 code (which appears to be currently unreachable).

**Comment by poettering** [comment]
It appears to me we should really drop those lines you linked. Care to prep a patch for that?

**Comment by petrosagg** [comment]
It's not so simple, I have to take a more careful look.

I compiled without these lines but still doesn't have the expected behaviour. I think it has to do with the fact that docker v2 gives a list of image digests which is different than the list of image IDs that V1 registries used to give.

I'm planning to tackle this issue right after I'm done with the `"-"` local name thing.

**Comment by vito** [comment]
Any update on this or #820? Exacerbated by sporadic failures via #1599 this makes `pull-dkr` pretty painful.

**Comment by philips** [comment]
@vito I would like to see pull-dkr removed from systemd-importd. It is going to be a continuous game of catchup as the docker registry API adds complex crypto and format things like docker notary, etc.

I talked about this a bit in my systemd.conf talk a few weeks ago. After the talk the general consensus is that importd should focus on machine images and that the general community could build a separate component, like [rkt](https://github.com/coreos/rkt), for downloading and running docker/application containers under systemd supervision.

**Comment by vito** [comment]
@philips Ah, that explains the inactivity. It indeed seems like a surprising amount of heavy lifting to include. Thanks for the update!

**Comment by poettering** [comment]
dkr support has been removed a while back. closing
