### ISSUE TITLE
pull-dkr: Local name is ignored if set to "-"

### ISSUE THREAD

**Issue by petrosagg** [systemd/systemd#820]
According to documentation, if `machinectl pull-dkr` is passed `-` as the local name it should omit creation of the final writable snapshot.

The following happens on a system with systemd v223

``` bash
$ machinectl --verify=no --dkr-index-url=https://index.docker.io pull-dkr library/busybox -                                         :(
Enqueued transfer job 1. Press C-c to continue download in background.
Pulling 'library/busybox' with reference 'latest', saving as 'busybox'.
```

According to `pull.c` it should just print `Pulling 'library/busybox' with reference 'latest'` and not create the last writable snapshot. Probably related to #819 
https://github.com/systemd/systemd/blob/master/src/import/pull.c#L282-L300

**Comment by poettering** [comment]
dkr support has been removed  a while back, closing
