### ISSUE TITLE
Logitech M305 missing from udev hwdb

### ISSUE THREAD

**Issue by danmou** [systemd/systemd#8208]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 229

### Used distribution

> Ubuntu 16.04

The Logitech M305 mouse is missing from udev hwdb. I've checked the specs using mouse-dpi-tool. The following lines should be added to `70-mouse.hwdb`:

```
# Logitech M305 Wireless Optical Mouse
mouse:usb:v046dpc52f:name:Logitech USB Receiver:
 MOUSE_DPI=1000@170
```

**Comment by poettering** [comment]
Please submit this as proper PR!
