### ISSUE TITLE
RFE: allow "Gateway=router" in network files

### ISSUE THREAD

**Issue by smurfix** [systemd/systemd#8213]
The problem: I need to configure my client to set up some routes (but **not** the default route) through the gateway it learns from a DHCP reply. Currently there is no way to do that.

Idea: Teach systemd-networkd to accept a `gateway=router` line in `[Route]` sections.

**Comment by ssahani** [comment]
How you do this now ?

**Comment by smurfix** [comment]
`RouteTable=20` in the `[DHCP]` section and creative application of rules and firewall tags.

That works but is not at all easy to debug, as I now pretty much always need to use "ip rule" in addition to "ip route" if I want to debug something. It's also annoying and, since rules are processed sequentially, probably slows down the router, though I did't yet measure by how much.

**Comment by ssahani** [comment]
I can't figure anything. Could you please elaborate ?

**Comment by smurfix** [comment]
OK. To reiterate. Let's say you have a nice DHCP-supported connection to the net. However, you want your default route to go through your Wireguard tunnel. So I need to add a host route that points the other end of my tunnel at the DHCP gateway. Except there is no way to write a `[Route]` entry that says "the destination is whatever DHCP says the gateway is".

My current workaround is to add the default route to a different table, with `RouteTable=42` in the `DHCP` section. I also need to tell Wireguard to tag the outgoing packets with `FwMark=99`. Third, I need to add a `[RoutingPolicyRule]` to direct `FirewallMark=99` to `Table=42`.

This is not obvious to do, and not at all debugging friendly because with this setup I can't just ping the WireGuard gateway to check basic connectivity (the ping packets are unmarked thus would go through the tunnel). Thus I also need an iptables rule to fwmark-tag my ping packets. That's … ugh.

By the way: could you please use either "FwMark" or "FirewallMark" everywhere?!?

**Comment by yuwata** [comment]
> By the way: could you please use either "FwMark" or "FirewallMark" everywhere?!?

Ugh...

**Comment by fpletz** [comment]
I agree that something like this would be very useful. :+1:

@smurfix I'm currently using VRFs for that same use case. You just need to enslave your uplink interfaces to a VRF (`VRF=`), and also set `RouteTable=` in `[IPv6AcceptRA]` if needed, in the network unit. After that a route to the Wireguard peer via the VRF device (without a gateway) in the main routing table is enough to make it work.

**Comment by yuwata** [comment]
@smurfix If possible, could you test PR #14499?

**Comment by smurfix** [comment]
Nice. Will do so later today.
