### ISSUE TITLE
RFE: Dynamically refresh timer unit next elapse when timezone changes

### ISSUE THREAD

**Issue by iainlane** [systemd/systemd#8233]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 237

### Enhancement requested

(Originally posted on [systemd-devel](https://lists.freedesktop.org/archives/systemd-devel/2018-February/040390.html) [reply from @poettering](https://lists.freedesktop.org/archives/systemd-devel/2018-February/040393.html))

I'm working on an alarm program. To allow the program to be shut down between alarms, they are represented as systemd timers using OnCalendar specifications. This mostly works but I think there is one wrinkle remaining - they don't handle timezone transitions but always trigger in the timezone that was in use when they were started.

In addition to alarms, you might also want this to schedule housekeeping tasks or backups to happen in the night. I think the semantics would be something like -

  * When changing timezones, ensure timers will activate at their configured time in the new local timezone.
  * Ignore any activation times that are skipped over due to a timezone change.

I'm not sure, though, what the best way to specify this in a timer unit would be. Perhaps either a new timezone specification "local", or a boolean flag UpdateWithTimezoneChange. "local" or `true` would act like you specified the current timezone, but we would go away and recalculate the time on a timezone change. The difference between specifying "local" and not specifying a timezone, or having the boolean be `true`/ `false` is that the former would have this update-on-change behaviour and the latter would keep the current non-warping behaviour.

I also don't know how we'd get notified of the timezone changing. inotify on /etc/timezone, being careful of symlinks?

**Comment by iainlane** [comment]
> I also don't know how we'd get notified of the timezone changing. inotify on /etc/timezone, being careful of symlinks?

@dbnicholson points out that I mean `/etc/localtime` here.

**Comment by poettering** [comment]
as mentioned on the ML, I think there should be no option for enabling that we follow timezones. We should do this unconditionally really: when you specify no timezone we should track the local timezone and use whatever is set, automatically, as it happens. 

For repeating timers we already adjust the timer events to changed local timezones sooner or later, when we calculate the next time to elapse. I am pretty sure we should make that systematic, and adjust it instantly when the local timezone changes.

**Comment by iainlane** [comment]
Alright, I had thought that this was the designed behaviour so I proposed a way to opt into something else. If it's okay to change it for everybody then we get to avoid deciding on any new syntax, so :+1:.

I'll try to work on a patch soon.

**Comment by poettering** [comment]
Fix waiting in #9121
