### ISSUE TITLE
RFE: More graceful handling of failed RTC.

### ISSUE THREAD

**Issue by oiaohm** [systemd/systemd#8247]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with
Seen with 238 and before.

### In case of bug report: Expected behaviour you didn't see

In case of detecting timerfd/RTC issue switch to a software clock for internal systemd operations either shutdown or reboot.   If reboot have option to boot into kernel with extra command line set being like clocksource=jiffies

### In case of bug report: Unexpected behaviour you saw

The behaviour is fairly much the same as the closed bug
PID1 getting stuck printing "systemd[1]: Time has been changed" continuously #1143

This in it self is not 100 percent bug because some RTC do magically come right after a minute or two they just seam to be upset on power up.   Its that there is not a upper limit where systemd goes the system is stuffed I need to shutdown/reboot.

### In case of bug report: Steps to reproduce the problem

1) Set RTC to invalid value have it lock and then have Linux kernel absolute time requests go wrong and have PID1 sitting printing the same message over and over.
2) Set RTC to a value the Linux kernel you have cannot process like 2038+ on a Linux kernel with 32 bit time and have PID1 sitting printing the same message over and over.. 
Both bite the dust the same way where you are attempting to set a timerfd and its not setting.

Being stuck in a loop the way systemd is at the moment is better than the sysvinit/busybox init boot and have applications do stupid things due to non functional time.   But what systemd is doing is still not the best outcome.

Yes if something as a RTC you wish to use it as it can allow CPU to sleep more and save power but in case of RTC set to invalid value booting with clocksource=jiffies and reset hardware RTC to acceptable value for it can be solution.  Like not all things care if their date is like 1970 something they will work anyhow but  setting in 2038 after 32 bit int fail for time  can cause some defective RTC develops issues just like a 32 bit time Linux kernel.   It is possible to have a 64 bit cpu and a 2038 problem from the hardware RTC.

With systemd service management you need to power effective timers this also means needing to cope with when items like RTC have gone bad gracefully.   Please note when I say gracefully I don't mean keep on running.   I don't know if you can change clocksource under Linux on the fly or if this has to be a reboot.   Having to reboot does show user they have a clear problem.

If it is possible to set clocksource on fly the work around path would be.

1) timerfd exceed number of attempts 
2) if clocksource not jiffies switch to jifflies see if this fixes it if it does report broken RTC
3) if exceed next number of attempts .attempt setting back in time. like june 1970 if configured todo so.   Complain about broken kernel with only 32bit time.  Yes this number 3 option has to be configured by person setting up system as acceptable path this would require to be able to be turned on by Linux Kernel command line possible added as a kernel feature to set RTC/software clock value on boot.
4) If you get to  this shut the system down using relative clocks no point burning power stuck in a never ending loop and its not safe to keep running with system wide clock value not working sanely.

Option 3 also will give logging system a work out and some software issues with every boot having the same times over and over again.   If your embedded software is design to work with invalid local time everything is fine.

**Comment by poettering** [comment]
Modern systems generally do not use the RTC during runtime, but CPU internal clocks. these clocks might be initialized from an RTC eventually, and the RTC might be updated from time to time with the CPU internal clocks, but a flakey RTC will generally not cause continious time jumps of the system clock.

Moreover, even if the RTC would cause such continous time flakiness systemd is not in the business of working around hardware issues. Quirks implemented in software around hardware bugs is OK to have, but the place for that are the drivers (i.e. the kernel), not the software using them.

The bug with "systemd[1]: Time has been changed" has been a software bug in the kernel that has long been fixed there. TFD_TIMER_CANCEL_ON_SET couldn't deal with some corner cases, such as overflowing time_t properly.

We generally avoid working around kernel problems in systemd, when they might as well be fixed there, and are clearly in the territory of *bug* (in contrast to let's say "misdesign"). 

I mean, systemd is just one user of TFD_TIMER_CANCEL_ON_SET, there are others. If the kernel doesn't implement that properly then everybody suffers, not just systemd, and hence fixing it in the kernel is the right approach to make it work for everybody. Working around kernel borkage in systemd will only make systemd work with that, but everything else will remain broken, and you'd have to fix that too.

Anyway, please work with the kernel community to make sure TFD_TIMER_CANCEL_ON_SET is reliable for you, there's really nothing to fix here in systemd. Sorry.

**Comment by oiaohm** [comment]
> flakey RTC will generally not cause continious time jumps of the system clock.

You are looking for particular brand RTC that when they have a low power from the back-up battery  go completely insane.   Either spinning time forward or backwards at about a year in 2 seconds at the worst.    But you hear of people report like clock running twice as faster or running backwards at slower speed more commonly out of them.

> Modern systems generally do not use the RTC during runtime, 

This is right and wrong.       Yes modern systems software calculate time but if they have a hardware RTC they are syncing against it.   When the RTC has gone stupid those sync cause a stack of other failures.   Most general badly timed RTC sync on a functional hardware RTC will at worst cause a once off timerfd issue.  timerfd does have the right to fail to user-space and in kernel saying retry.  So the code in systemd is right to retry that is what is meant to happen.   But being hit by repeated retries something is going wrong.

https://0xax.gitbooks.io/linux-insides/content/Timers/timers-2.html

If you look up how clocksource works.   The hardware RTC will be updating the CPU software clocks the system presumes what is normally correct that the hardware RTC is more correct than cpu calculated time that with dynamic clocking can be quite badly out.

I did a bit more digging there is no mode without rebooting to switch off syncing to hardware clock ok you can change between hardware clocks.     So yes there is a Linux kernel weakness of not being able to to switch to jiffies mode(what is pure software with no syncing any hardware clock)  unless its in the Linux kernel command line.

Yes the kernel command line option to use jiffies is to deal with broken clock.

I see this as a service management problem because hardware clock  failures don't always happen on boot up.   They can happen when you system has been up days/months all to do when the battery on the RTC goes stupid.

Reality is we cannot predict when Hardware RTC is going to go nightmare.

There is a Linux kernel interface to tell the Linux kernel to change clocks.   There is a bug that you cannot change to jiffies mode as it does not appear as available_clocksource when system has found hardware clocks.

Insanely out of control hardware RTC generates the same faults.

On the newer fixed kernels if you can switch to jiffies mode and a RTC has gone insane everything should be ok.   Clock drift may be a little higher than normal and power usage may be higher due to not being able to go into sleeps as long due to having to maintain time.

The reality here the first party to work out that the hardware RTC has gone unstable really does need way to say please change clocksource kernel to jiffies or other clocksources because the current is nuts.   

Changing to the jiffies  the software clock can  does time drift faster than the when the hardware RTC is functional can mean and items like Kerberos authentication can fail due to clock time skew.

So I see this as something that systemd does need to handle.   If the kernel does attempt to address a RTC issue by changing clock source this does need to be informed to service management and the service management may have to decide to either shut the complete system down or shutdown services or increase network time sync frequency to deal with the fact the changed to clock source will have a different clock drift value.

> Moreover, even if the RTC would cause such continous time flakiness systemd is not in the business of working around hardware issues. Quirks implemented in software around hardware bugs is OK to have, but the place for that are the drivers (i.e. the kernel), not the software using them.

This is a case that kernel attempts to work around RTC hardware bug quality of clock can dropped and this will cause other issues.

Time issue the service management and the kernel need to work hand in hand.   systemd detects time issue it need to be able to inform kernel.   Kernel need to be able inform systemd if it had to change clocksource.   Like there is nothing to say that systemd could not have a rule that if using jiffies has to network time sync more to neutralise jiffies higher clock drift rate.

Systemd is starting the users space services and is in charge of userspace services.   Making choices based on what is the current clock at times is required. 

Yes the kernel should do particular things against hardware RTC gone stupid.   But service management need to adjust software in alignment with any major clocksource change not to have other issues.

The problem I am talking about attempting to fix by quirks alone in Linux kernel will result in the likes of Kerberos authentication failures because network time syncing and other things have not adjusted to the fact the hardware RTC has left the building.

Remember this quirk about the hardware RTC going stupid due battery issues means when something is new these problems don't appear and when the hardware RTC has a good battery it does not need a quirk.   And when RTC has gone stupid about the only valid option is disable it.   Once you disable the hardware RTC other service that use to work right may no longer work right due to clock drift. 

So the Linux kernel driver developer for a hardware RTC may never see that RTC with an old battery so may not know that it has a quirk where it time goes stupid.

The reality is not everything can be fixed in kernel space particularly when it comes to clock sources.   A clocksource failure and it side effects means userspace need to change it settings as well.    So we need systemd and kernel to work cooperatively with each other over clocksource handling.
