### ISSUE TITLE
libshared links to libcryptsetup, pulling libcryptsetup into everything

### ISSUE THREAD

**Issue by janhieber** [systemd/systemd#8249]
### Submission type
 - Bug report

### systemd version the issue has been seen with
237.31

### Used distribution
Arch Linux

### In case of bug report: Expected behaviour you didn't see
Should work

### In case of bug report: Unexpected behaviour you saw
Crashes when wrong json lib installed ...

### In case of bug report: Steps to reproduce the problem
Downgrade json-c package to 0.12

I think an init system should not be rendered completely useless just because a JSON library has wrong version. Init system is the one thing that should be robust and designed by KISS.
Solutions? Maybe not using shared libs. Or separation of functionality. I should be able to reboot/shutdown my system even without correct JSON library installed.

I know some will argue with this, but fact is: Wrong JSON rendered my init useless. This should not happen.

**Comment by poettering** [comment]
we do not link against any json library. What makes you think we do? what's the precise error message you see?

**Comment by janhieber** [comment]
On ``reboot`` or ``systemctl reboot``
> systemctl: error while loading shared libraries: libjson-c.so.3: cannot open shared object file: No such file or directory

**Comment by poettering** [comment]
> systemctl: error while loading shared libraries: libjson-c.so.3: cannot open shared object file: No such file or directory

we do not link against json-c. This must be some other library that has a dependency like that, that we might link (or end up linking against, maybe through dlopen()/NSS?) against. 

It might make sense figuring out what precisely is doing that because systemd is not doing that itself.

Use `objdump -p /usr/bin/systemctl |grep NEEDED` to see what systemctl itself links against. Then follow that recursively on the results.

You can alternatively use `ldd` but that's implicitly recursive, hence doesn't really help with figuring out which library precisely pulls in json-c. On Fedora at least "ldd systemctl" shows no dep on json-c, it appears that's some arch-specific thing.

**Comment by janhieber** [comment]
Tracked it down to ``libcryptsetup.so.12`` which linkes against json-c.

OK so maybe this can be closed without solution?

Sorry but I'm just annoyed that some lib
brakes the basics of the init system. Shouldn't this be separated to make it more robust and only link against specific libs where required? But that means splitting up ``libsystemd-shared-237.so`` I guess.

**Comment by poettering** [comment]
hmm, we do link against libcryptsetup.so in some binaries, but there's something fishy as libsystemd-shared.so should  not be among those. @keszybz any idea?

**Comment by janhieber** [comment]
``` bash
 > objdump -p /usr/lib/systemd/libsystemd-shared-237.so |grep NEEDED | awk '{print $3}' | while read line; do echo $line && objdump -p /usr/lib/$line |grep NEEDED; done
libpthread.so.0
25:  NEEDED               libc.so.6
26:  NEEDED               ld-linux-x86-64.so.2
libc.so.6
27:  NEEDED               ld-linux-x86-64.so.2
librt.so.1
21:  NEEDED               libpthread.so.0
22:  NEEDED               libc.so.6
libcap.so.2
19:  NEEDED               libc.so.6
libacl.so.1
21:  NEEDED               libattr.so.1
22:  NEEDED               libc.so.6
libcryptsetup.so.12
21:  NEEDED               libuuid.so.1
22:  NEEDED               libdevmapper.so.1.02
23:  NEEDED               libgcrypt.so.20
24:  NEEDED               libgpg-error.so.0
25:  NEEDED               libargon2.so.1
26:  NEEDED               librt.so.1
27:  NEEDED               libdl.so.2
28:  NEEDED               libjson-c.so.3
29:  NEEDED               libc.so.6
libgcrypt.so.20
21:  NEEDED               libgpg-error.so.0
22:  NEEDED               libc.so.6
libip4tc.so.0
21:  NEEDED               libpcap.so.1
22:  NEEDED               libc.so.6
libseccomp.so.2
21:  NEEDED               libc.so.6
libidn.so.11
21:  NEEDED               libc.so.6
liblzma.so.5
21:  NEEDED               libpthread.so.0
22:  NEEDED               libc.so.6
liblz4.so.1
21:  NEEDED               libc.so.6
libblkid.so.1
23:  NEEDED               libuuid.so.1
24:  NEEDED               libc.so.6
25:  NEEDED               ld-linux-x86-64.so.2
ld-linux-x86-64.so.2
```

**Comment by bramian** [comment]
I'm having this same issue.  I'm a little aghast at seeing a libjson related error preventing me from booting.

**Comment by floppym** [comment]
Your distro should really be testing things before pushing them out to end users.

**Comment by filbranden** [comment]
> hmm, we do link against libcryptsetup.so in some binaries, but there's something fishy as libsystemd-shared.so should not be among those.

Commit 18b5886e562a3702ed8923e568a7555d2ab1880a ("dissect: add support for encrypted images") added a dependency on libcryptsetup to libshared...

**Comment by keszybz** [comment]
Yeah, I looked into this, and the dependency on libcryptsetup is legitimate. We'd have to do a major refactoring to remove it.

**Comment by poettering** [comment]
Hmm, so this dep is valid indeed. Not sure what we can do about it

**Comment by keszybz** [comment]
I guess we should try to reduce linking, but let's mark this as RFE, since there's no bug really here.
