### ISSUE TITLE
Tolerate extended environment variable names

### ISSUE THREAD

**Issue by dvdhrm** [systemd/systemd#826]
Right now, systemd enforces strict rules on environment variable names. We basically follow what POSIX suggests:

```
Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.
```

But POSIX also continues with:

```
Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.
```

We do not allow such characters in environment names. However, since ShellShock bash suffixes exported functions with parantheses:

```
# old way
myfunction=() { echo "hello world" }
# new way
BASH_FUNC_myfunction()=() { echo "hello world" }
```

The strict environment checkers of systemd break `UpdateActivationEnvironment()` in bus-proxy, as updates with such entries are rejected.

**Comment by poettering** [comment]
As discussed over lunch earlier today I think we should filter weird env vars out in bus-proxy, but warn about it, and only pass on the sane env vars to PID 1. This should create enough compat for KDE, without compromising on sanity.
