### ISSUE TITLE
SystemCallFilter=@file-system → Failed to parse system call, ignoring: statx

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#8261]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237 git 774ff9ba69c08d8331c4268059637f289ce059bb

### Used distribution

> Gentoo, Kernel 4.15.4, glibc-2.25

### In case of bug report: Expected behaviour you didn't see

> So far, everything seems to work as expected.

### In case of bug report: Unexpected behaviour you saw

> My [restic](https://github.com/restic/restic) service which contains `SystemCallFilter=@file-system` shows this message in it's status/journal:
> `Feb 23 10:02:58 moria systemd[1]: /etc/systemd/system/restic@.service:20: Failed to parse system call, ignoring: statx`

### In case of bug report: Steps to reproduce the problem

> - Define a `SystemCallFilter=` for a service which contains `@file-system`
> - Reload the service and check its status output

**Comment by poettering** [comment]
Fix waiting in #8280
