### ISSUE TITLE
FT5406 (official raspberry touchscreen) wrong touchscreen resolution

### ISSUE THREAD

**Issue by bahamut657** [systemd/systemd#8272]
- Bug report
ArchlinuxARM, libinput 1.10, kernel 4.14.18-1

FT5406 is recognized by the kernel as 800x600 (while it is 800x480)
Already discussed with @whot 
[https://bugs.freedesktop.org/show_bug.cgi?id=105153](https://bugs.freedesktop.org/show_bug.cgi?id=105153)

It was working with no problem before kernel update.
Seems like a  60-evdev.hwdb patch is needed.
I patch it like so
evdev:name:FT5406*
 EVDEV_ABS_00=2:800:1
 EVDEV_ABS_01=2:480:1
 EVDEV_ABS_35=2:800:1
 EVDEV_ABS_36=2:480:1

**Comment by boucman** [comment]
can you make that a proper pull request ? it's easier to handle...

**Comment by whot** [comment]
I just had another look at the driver that this thing runs (`drivers/input/touchscreen/edt-ft5x06.c`) and it contains the following comment where the x/y axes are set up:
   
     /* Unknown maximum values. Specify via devicetree */

which would indicate that this may be a devicetree issue (which would also explain the change during a kernel update). I'm not overly famiilar with device tree but please do investigate this first. This could be an ArchlinuxARM kernel bug

**Comment by bahamut657** [comment]
So, which next steps? 
Can I post on ArchlinuxARM Forum the issue? 
I've do it 2 weeks ago but none response (and I perform sys upgrade any days with no solution)

**Comment by whot** [comment]
please ping them again. see if you can figure out which kernel version broke it by installing older versions.

**Comment by bahamut657** [comment]
I've re-ping them with a new post in the ArchlinuxARM forum.
Here is the link.
[(https://archlinuxarm.org/forum/viewtopic.php?f=15&t=12605)]

Hoping they resolve the problem soon. I let you now on update

**Thanks to all for the support**

**Comment by poettering** [comment]
Closing this here, as this appears to be a devicetree issue. Please reopen if there's something to fix in hwdb after all. Thanks.
