### ISSUE TITLE
systemd-boot feature request disk and or partition selection for target boot efi file

### ISSUE THREAD

**Issue by KrisKnez** [systemd/systemd#8299]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 237

### Used distribution

> Debian

A feature to allow systemd-boot to select the drive and/or the partition of the target efi file would be very useful.

For someone like me who likes to use systemd-boot instead of GRUB it's a hassle.
I need to copy the Linux kernel executable each time it gets update to the ESP to be up to date.

If I would be able to just tell systemd-boot the partition of the Linux installation it would be much more easier and effective booting and doing hacky scripts to automate the task wouldn't be needed.

**Comment by yuwata** [comment]
On Fedora, such a kernel update task is done by `kernel-install` command. Does Debian not use it? Or, do you want to say that the ESP detection in `kernel-install` does not work?

**Comment by ChrisDoesEverything** [comment]
I've never heard of `kernel-install`.
Does it copy the `vmlinuz` and `initrd.img` into ESP.
If so does it automatically get called after updating the kernel?
This may be a valid solution.

Also, does systemd-boot try to find kernel images on the partition it is installed on or always the ESP?
Installing systemd-boot on the actual partition of the OS and pointing the config to `\vmlinuz` might work but `\vmlinuz` is a symlink and systemd-boot probably doesn't support them.

I'll try it once I get home.

**Comment by yuwata** [comment]
On Fedora, kernel.rpm calls `kernel-install`, the command copies vmlinuz and initrd.img into ESP.
E.g., ESP (mounted on /boot) of my machine has
```
$ tree /boot
/boot
├── xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
│   ├── 4.13.11-300.fc27.x86_64
│   │   ├── initrd
│   │   └── linux
│   ├── 4.15.3-300.fc27.x86_64
│   │   ├── initrd
│   │   └── linux
│   └── 4.15.4-300.fc27.x86_64
│       ├── initrd
│       └── linux
├── EFI
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   └── systemd
│       └── systemd-bootx64.efi
└── loader
    ├── entries
    │   ├── xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-4.13.11-300.fc27.x86_64.conf
    │   ├── xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-4.15.3-300.fc27.x86_64.conf
    │   └── xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-4.15.4-300.fc27.x86_64.conf
    └── loader.conf

9 directories, 12 files
```
I do not manually create or copy the above files. All files are created by `kernel-install` and `bootctl install`.

**Comment by ChrisDoesEverything** [comment]
I can't seem to find an example of how to call `kernel-install`
After installing Debian it doesn't automatically call `kernel-install`

**Comment by poettering** [comment]
This appears to be a downstream issue with packaging kernel-install. We do provide what you are asking for, but it's up to the distributions to integrate that. On Fedora all this pretty much works. If this doesn't on Debian, then please work with the Debian community to either adopt kernel-install too (which would be ideal) or add a similar hookup for sd-boot to Debian's native kernel-install counterpart.

Anyway, closing here, as we already have what you are asking for.
