### ISSUE TITLE
"systemctl reboot" never reboots on 223 with lvm, mdadm raid, btrfs raid

### ISSUE THREAD

**Issue by wlcrls47** [systemd/systemd#831]
"systemctl reboot":
[  OK  ] Reached target Shutdown.
[      ] watchdog watchdog0: watchdog did not stop!
[      ] watchdog watchdog0: watchdog did not stop!
[      ] cgroup: option or name mismatch, new: 0x0 "", old: 0x4 "systemd"
[      ] shutdown[1]: Failed to finalize  DM devices, ignoring
[      ] INFO: task shutdown:1 blocked for more than 120 seconds.
[      ]       Not tainted 4.1.3-1-ARCH #1 
[      ] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
It then repeats the INFO-echo lines forever with 2 minutes in between each set, until I manually hit the power switch.

Fresh arch install, kernel 4.1.3-1, lvm2 2.02.125-1, mdadm 3.3.2-2
I am running lvm
I have an mdadm raid1 of /dev/md0 for swap of 3 LVM logical volumes
I have a btrfs raid1 of 3 LVM logical volumes
I ran "mdadm --detail --scan > /mountpoint/etc/mdadm.conf" during installation
I added "mdadm_udev lvm2" to /etc/mkinitcpio.conf between "block" and "filesystemd" during installation, then ran "mkinitcpio -p linux"
"dmsetup -ls" properly shows all 3 of my LVM logical volumes

**Comment by crrodriguez** [comment]
Please file a bug report on your distribution bugtracker. systemd has nothing to do with this.

**Comment by wlcrls47** [comment]
I'll assume this isn't a systemd issue.  But, I think systemd could be more helpful telling me what's happening.  Even adding "systemd.log_level=debug systemd-log_target=kmsg log_buf_len=1M enforcing=0" to kernel parameters, and creating /usr/lib/systemd/system-shutdown/debug.sh of:

[code]#!/bin/sh
mount -o remount,rw /
dmesg > /shutdown-log.txt
mount -o remount,ro /[/code]

I only get this (from the watchdog part).  With systemd saying during shutdown that it's ignoring the dm finalization, I don't see any hints in here what's "stuck".  Unless it's the assertion issue on line 1, which leaves me having no idea what's going on.

[  759.193902] systemd[1]: Assertion 'r >= 0' failed at src/libsystemd/sd-event/sd-event.c:484, function source_io_unregister(). Ignoring.
[  759.193956] systemd[1]: Hardware watchdog 'iTCO_wdt', version 0
[  759.193969] systemd[1]: Set hardware watchdog to 10min.
[  759.193978] watchdog watchdog0: watchdog did not stop!
[  759.197079] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  759.208390] systemd-udevd[342]: Unload module index
[  759.208454] systemd-udevd[342]: Unloaded link configuration context.
[  759.750116] systemd-journald[294]: Received SIGTERM from PID 1 (systemd-shutdow).
[  759.750126] systemd-journald[294]: systemd-journald stopped as pid 294
[  759.868629] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  759.878623] systemd-shutdown[1]: Hardware watchdog 'iTCO_wdt', version 0
[  759.878867] systemd-shutdown[1]: Unmounting file systems.
[  759.927208] BTRFS info (device dm-5): disk space caching is enabled
[  759.968498] BTRFS info (device dm-5): disk space caching is enabled
[  759.968513] systemd-shutdown[1]: All filesystems unmounted.
[  759.968518] systemd-shutdown[1]: Deactivating swaps.
[  759.968587] systemd-shutdown[1]: All swaps deactivated.
[  759.968591] systemd-shutdown[1]: Detaching loop devices.
[  759.968661] systemd-shutdown[1]: device-enumerator: scan all dirs
[  759.968680] systemd-shutdown[1]:   device-enumerator: scanning /sys/bus
[  759.968715] systemd-shutdown[1]:   device-enumerator: scanning /sys/class
[  759.968780] systemd-shutdown[1]: All loop devices detached.
[  759.968784] systemd-shutdown[1]: Detaching DM devices.
[  759.968808] systemd-shutdown[1]: device-enumerator: scan all dirs
[  759.968819] systemd-shutdown[1]:   device-enumerator: scanning /sys/bus
[  759.968841] systemd-shutdown[1]:   device-enumerator: scanning /sys/class
[  759.970098] systemd-shutdown[1]: Detaching DM 254:5.
[  759.970122] systemd-shutdown[1]: Could not detach DM /dev/dm-5: Device or resource busy
[  759.970126] systemd-shutdown[1]: Detaching DM 254:4.
[  759.970137] systemd-shutdown[1]: Could not detach DM /dev/dm-4: Device or resource busy
[  759.970141] systemd-shutdown[1]: Detaching DM 254:3.
[  759.970151] systemd-shutdown[1]: Could not detach DM /dev/dm-3: Device or resource busy
[  759.970155] systemd-shutdown[1]: Detaching DM 254:2.
[  759.970165] systemd-shutdown[1]: Could not detach DM /dev/dm-2: Device or resource busy
[  759.970168] systemd-shutdown[1]: Detaching DM 254:1.
[  759.970180] systemd-shutdown[1]: Could not detach DM /dev/dm-1: Device or resource busy
[  759.970184] systemd-shutdown[1]: Detaching DM 254:0.
[  759.970194] systemd-shutdown[1]: Could not detach DM /dev/dm-0: Device or resource busy
[  759.970199] systemd-shutdown[1]: Not all DM devices detached, 6 left.
[  759.970203] systemd-shutdown[1]: Cannot finalize remaining DM devices, continuing.
[  759.970800] systemd-shutdown[915]: Spawned /usr/lib/systemd/system-shutdown/mdadm.shutdown as 916.
[  759.970932] systemd-shutdown[915]: Spawned /usr/lib/systemd/system-shutdown/debug.sh as 917.
[  759.974624] BTRFS info (device dm-5): disk space caching is enabled
[  759.974732] systemd-shutdown[915]: /usr/lib/systemd/system-shutdown/mdadm.shutdown succeeded.

**Comment by arvidjaar** [comment]
> I think systemd could be more helpful telling me what's happening.

After the messages you have shown systemd does two things - calls sync() and reboot(). If anything goes wrong here it happens inside kernel and systemd can do nothing about it. Actually it does set hardware watchdog so your system should be reset by it if nothing happens after 10 minutes. If reset does not happen, something in kernel is really screwed up. You should open bug report for kernel (upstream or distro, do not know heavily kernel is patched).

**Comment by poettering** [comment]
This shows that systemd shuts down fine, but there's something wrong with your kernel, as it ends up hanging after systemd transitioned back into your initrd, see the "INFO: task shutdown:1 blocked for more than 120 seconds." line. Please report this to your distro, and probably the kernel. 

Sorry, but there's little we can do about this issue from systemd.
