### ISSUE TITLE
Failed to list units: Access denied

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8326]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

> `systemclt list-units` lists the units.

### In case of bug report: Unexpected behaviour you saw

> The error message `Failed to list units: Access denied`.

### In case of bug report: Steps to reproduce the problem

> Build systemd and install it.

`systemctl status example.service` works though, so it’s very confusing. The output of strace is attached.

[strace.txt](https://github.com/systemd/systemd/files/1772388/strace.txt)

**Comment by poettering** [comment]
Please generate the strace output with `-s1000` or so, so that the dbus datagram data isn't truncated.

Do you use any kind of weird MAC? selinux, …? Are you sure your dbus policy is in order?

**Comment by paulmenzel** [comment]
Please find the non-truncated output attached.

> Do you use any kind of weird MAC? selinux, …? Are you sure your dbus policy is in order?

No SELinux is used. I am not user about the D-Bus policy.

[strace-s-2000.txt](https://github.com/systemd/systemd/files/1775304/strace-s-2000.txt)

**Comment by poettering** [comment]
```
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.218\0\0\4\1s\0'\0\0\0org.freedesktop.DBus.Error.AccessDenied\0\5\1u\0\3\0\0\0\10\1g\0\1s\0\0\7\1s\0\24\0\0\0org.freedesktop.DBus\0\0\0\0008\1\0\0Rejected send message, 4 matched rules; type=\"method_call\", sender=\":1.218\" (uid=5272 pid=28081 comm=\"systemctl list-units \") interface=\"org.freedesktop.systemd1.Manager\" member=\"ListUnitsFiltered\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.systemd1\" (uid=0 pid=1 comm=\"/bin/systemd \")\0", iov_len=421}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 421
```
This suggests that there's something wrong with your dbus policy. Maye you still have the old policy installed, not the one that current systemd drops in?

**Comment by paulmenzel** [comment]
Is there a way to query D-Bus for more verbose information?

The following files with *dbus* in the path are installed.

```
$ sudo bee query systemd-237-0.x86_64 | grep dbus
/etc/systemd/system/dbus-org.freedesktop.resolve1.service//../../../lib/systemd/system/systemd-resolved.service
/etc/systemd/system/dbus-org.freedesktop.network1.service//../../../lib/systemd/system/systemd-networkd.service
/lib/systemd/system/dbus-org.freedesktop.timedate1.service//systemd-timedated.service
/lib/systemd/system/dbus-org.freedesktop.machine1.service//systemd-machined.service
/lib/systemd/system/dbus-org.freedesktop.login1.service//systemd-logind.service
/lib/systemd/system/dbus-org.freedesktop.locale1.service//systemd-localed.service
/lib/systemd/system/dbus-org.freedesktop.import1.service//systemd-importd.service
/lib/systemd/system/dbus-org.freedesktop.hostname1.service//systemd-hostnamed.service
/usr/share/dbus-1
/usr/share/dbus-1/services
/usr/share/dbus-1/services/org.freedesktop.systemd1.service//../system-services/org.freedesktop.systemd1.service
/usr/share/dbus-1/system-services
/usr/share/dbus-1/system-services/org.freedesktop.timedate1.service
/usr/share/dbus-1/system-services/org.freedesktop.resolve1.service
/usr/share/dbus-1/system-services/org.freedesktop.machine1.service
/usr/share/dbus-1/system-services/org.freedesktop.locale1.service
/usr/share/dbus-1/system-services/org.freedesktop.import1.service
/usr/share/dbus-1/system-services/org.freedesktop.hostname1.service
/usr/share/dbus-1/system-services/org.freedesktop.network1.service
/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service
/usr/share/dbus-1/system-services/org.freedesktop.login1.service
/usr/share/dbus-1/system.d
/usr/share/dbus-1/system.d/org.freedesktop.timedate1.conf
/usr/share/dbus-1/system.d/org.freedesktop.resolve1.conf
/usr/share/dbus-1/system.d/org.freedesktop.machine1.conf
/usr/share/dbus-1/system.d/org.freedesktop.locale1.conf
/usr/share/dbus-1/system.d/org.freedesktop.import1.conf
/usr/share/dbus-1/system.d/org.freedesktop.hostname1.conf
/usr/share/dbus-1/system.d/org.freedesktop.network1.conf
/usr/share/dbus-1/system.d/org.freedesktop.systemd1.conf
/usr/share/dbus-1/system.d/org.freedesktop.login1.conf
```

But, let’s close this, and I’ll reinstall the system again, as it seems to work on other systems.

**Comment by dtwilliamson** [comment]
I have two Ubuntu 16.04 VMs that I created at the same time and in the same way. One exhibits the problem and the other doesn't. They both have systemd 229. Neither has systemd-shim 
`sudo dpkg --purge systemd-shim`
`dpkg: warning: ignoring request to remove systemd-shim which isn't installed`

Oddly, when I strace it, it works - no error.

`dennis@one:~$ systemctl list-units --all --full`
`Failed to list units: Access denied`

`dennis@one:~$ sudo strace -vvvf -s 4096 systemctl list-units --all --full 2> /dev/null | head -n 3`
`  UNIT                                                                                     LOAD      ACTIVE   SUB       DESCRIPTION`
`  proc-sys-fs-binfmt_misc.automount                                                        loaded    active   running   Arbitrary Executable File Formats File System Automount Point`
`  dev-disk-by\x2did-ata\x2dQEMU_HARDDISK_QM00001.device                                    loaded    active   plugged   QEMU_HARDDISK`

System two always works:

`dennis@two:~$ systemctl list-units --all --full | head -n 3`
`  UNIT                                                                                     LOAD      ACTIVE   SUB       DESCRIPTION`
`  proc-sys-fs-binfmt_misc.automount                                                        loaded    active   waiting   Arbitrary Executable File Formats File System Automount Point`
`  dev-disk-by\x2did-ata\x2dQEMU_HARDDISK_QM00001.device                                    loaded    active   plugged   QEMU_HARDDISK`

**Comment by teknoraver** [comment]
Same happened here on a Debian 10:
```
root@deepblue:~# systemctl
Failed to list units: Access denied

root@deepblue:~# strace -s1000 -e trace=%network systemctl
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
getsockopt(3, SOL_SOCKET, SO_RCVBUF, [212992], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/systemd/private"}, 23) = 0
getsockopt(3, SOL_SOCKET, SO_PEERCRED, {pid=1, uid=0, gid=0}, [12]) = 0
getsockopt(3, SOL_SOCKET, SO_PEERSEC, 0x55b7ecf4d410, [64]) = -1 ENOPROTOOPT (Protocol not available)
getsockopt(3, SOL_SOCKET, SO_PEERGROUPS, "", [256->0]) = 0
getsockopt(3, SOL_SOCKET, SO_ACCEPTCONN, [0], [4]) = 0
getsockname(3, {sa_family=AF_UNIX}, [128->2]) = 0
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0AUTH EXTERNAL\r\nDATA\r\n", iov_len=22}, {iov_base="NEGOTIATE_UNIX_FD\r\n", iov_len=19}, {iov_base="BEGIN\r\n", iov_len=7}], msg_iovlen=3, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 48
getsockopt(3, SOL_SOCKET, SO_PEERCRED, {pid=1, uid=0, gid=0}, [12]) = 0
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="REJECTED EXTERNAL ANONYMOUS\r\nERROR\r\nERROR\r\nERROR\r\n", iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 50
Failed to list units: Access denied
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7545, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
+++ exited with 1 +++
```

**Comment by teknoraver** [comment]
Solved with `kill -TERM 1`

**Comment by rwagnergit** [comment]
Just witnessed this on RHEL 7

rowagn@glp08auv:~#> cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
rowagn@glp08auv:~#> uname -a
Linux glp08auv 3.10.0-1160.2.2.el7.x86_64 #1 SMP Sat Oct 17 05:06:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
rowagn@glp08auv:~#>

Same error in strace.  Same "solution" - a reboot fixed it.
