### ISSUE TITLE
Need to have a user service register an lxpolkit session when run in systemctl --user mode

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#833]
I would like to run the following vncserver service in the user mode but doing so causes lxpolkit to report "No session for pid xxxx" within the vncserver.

As I understand it, the PAMName=login needs to be present to keep the bug from occurring BUT it needs to paired with a User= directive to work which, fails in user mode.  Any thoughts are welcomed.

```
/home/facade/.config/systemd/user/vncserver@:1.service
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
PAMName=login

# Clean any existing files in /tmp/.X11-unix environment
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/bin/vncserver -fg -geometry 2000x1200 -AlwaysShared -localhost -dpi 100 %i
ExecStop=/usr/bin/vncserver -kill %i

[Install]
WantedBy=multi-user.target
```

**Comment by poettering** [comment]
If you run your X server like this then it won't be attached to any session. If lxpolkit shall work in that mode then it really needs to be fixed to handle this nicely. 

Closing this here now, since there's little we can do from the systemd side on this.

**Comment by poettering** [comment]
(To clarify: this is not really a bug in lxpolkit, But it needs to be fixed in lxpolkit anyway, if it shall be compatible with your mode of operation of using a per-user X server, rather than a per-session one)
