### ISSUE TITLE
centos7，systemd-219，If journalctl is restarted, the docker log can not be written to journald

### ISSUE THREAD

**Issue by xiagujinqiao** [systemd/systemd#8331]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd-219-42.el7_4.4.x86_64

### Used distribution

>  CentOS Linux release 7.2.1511 (Core)

### In case of bug report: Expected behaviour you didn't see

> journalctl is restarted, the docker log can  be written to journald

### In case of bug report: Unexpected behaviour you saw

> journalctl is restarted, the docker log can not be written to journald

### In case of bug report: Steps to reproduce the problem

> 1.systemctl start docker
docker log send to journald and /var/log/messages;
2.systemctl restart systemd-journald
no docker log ,whether in journald or message
3.systemctl restart docker
new docker log write journald and /var/log/messages

**Description**
OS：CentOS Linux release 7.2.1511 (Core)
systemd：systemd-219-42.el7_4.4.x86_64
docker version：docker-ce-17.12.1.ce-1.el7.centos.x86_64
#systemctl show docker | grep SIGPIPE
IgnoreSIGPIPE=yes
Go version:	go1.9.4
If journalctl is restarted, the docker log can not be written to journald.

I guess it is the sigpipe cause of the error
thanks

**Output of `docker version`:**
Client:
Version:	17.12.1-ce
API version:	1.35
Go version:	go1.9.4
Git commit:	7390fc6
Built:	Tue Feb 27 22:15:20 2018
OS/Arch:	linux/amd64

Server:
Engine:
Version:	17.12.1-ce
API version:	1.35 (minimum version 1.12)
Go version:	go1.9.4
Git commit:	7390fc6
Built:	Tue Feb 27 22:17:54 2018
OS/Arch:	linux/amd64
Experimental:	false

**Output of `docker info`:**
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 1
Server Version: 17.12.1-ce
Storage Driver: devicemapper
Pool Name: docker-253:0-203499693-pool
Pool Blocksize: 65.54kB
Base Device Size: 10.74GB
Backing Filesystem: xfs
Udev Sync Supported: true
Data file: /dev/loop0
Metadata file: /dev/loop1
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Data Space Used: 11.8MB
Data Space Total: 107.4GB
Data Space Available: 45.42GB
Metadata Space Used: 581.6kB
Metadata Space Total: 2.147GB
Metadata Space Available: 2.147GB
Thin Pool Minimum Free Space: 10.74GB
Deferred Removal Enabled: true
Deferred Deletion Enabled: true
Deferred Deleted Device Count: 0
Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
seccomp
Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.641GiB
Name: vm-os-centos7
ID: AORO:INMV:6G7P:DJ7N:X2ND:SCNK:XIZJ:ILMW:GMZZ:NJBW:RM2H:UKPF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**Output of `systemctl show docker |grep SIGPIPE`:**
IgnoreSIGPIPE=yes

**Comment by poettering** [comment]
Sorry, but we only track issues in the two most recent upstream releases of systemd here (that's 236, 237 currently). Please contact your downstream distribution for older stuff. 219 is waaaay to old to qualify.

Thank you for understanding
