### ISSUE TITLE
session_device_free(sd) also drops all *other* device fds of that session

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8344]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v237 / master.  Initially seen by code analysis

### Code analysis

```
void session_device_free(SessionDevice *sd) {
        assert(sd);

        if (sd->pushed_fd) {
                const char *m;

                /* Remove the pushed fd again, just in case. */

                m = strjoina("FDSTOREREMOVE=1\n"
                             "FDNAME=session-", sd->session->id);

                (void) sd_notify(false, m);
        }
```

Notice how sd_notify() is passed the id of `sd->session`.  We're not passing PID1 anything more specific.

Therefore, when a device is removed, it looks like we remove *all* fds of that session from the store.

(Unless we're not calling session_device_free() when a device is removed, in which case we are effectively leaking memory.  That would also be a bug).

**Comment by sourcejedi** [comment]
Confirmed.

```
# lsof /dev/dri/card0
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
systemd      1 root  115u   CHR  226,0      0t0 13568 /dev/dri/card0
systemd-l  639 root   23u   CHR  226,0      0t0 13568 /dev/dri/card0
gnome-she 1099  gdm    8u   CHR  226,0      0t0 13568 /dev/dri/card0
gnome-she 1099  gdm   10u   CHR  226,0      0t0 13568 /dev/dri/card0
gnome-she 1099  gdm   12u   CHR  226,0      0t0 13568 /dev/dri/card0
```

then remove a USB device:

```
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
systemd-l  639 root   23u   CHR  226,0      0t0 13568 /dev/dri/card0
gnome-she 1099  gdm    8u   CHR  226,0      0t0 13568 /dev/dri/card0
gnome-she 1099  gdm   10u   CHR  226,0      0t0 13568 /dev/dri/card0
gnome-she 1099  gdm   12u   CHR  226,0      0t0 13568 /dev/dri/card0
```

**Comment by fbuihuu** [comment]
> (Unless we're not calling session_device_free() when a device is removed, in which case we are effectively leaking memory. That would also be a bug).

@sourcejedi IIRC logind doesn't free a device when it is removed. I guess the component which took control of the device is supposed to react accordingly and either release the device or close the session.

**Comment by sourcejedi** [comment]
I think the `logind-device` object gets cleaned up on device removal, and this is propagated to clean up (free) the `logind-session-device`.

Which is good because logind is privileged and the session owner is unprivileged, so we shouldn't rely on their behaviour too much.

**Comment by fbuihuu** [comment]
> @fbuihuu I think the logind-device object gets cleaned up on device removal, and this is propagated to clean up (free) the logind-session-device.

IIRC only PID1 listens for the device removal events not logind.

In my understanding logind relies on the session owner to either release the device or exits (hence close the session).

**Comment by sourcejedi** [comment]
logind listens for remove events as relayed by udev.  Whereas PID1 listens for a disconnect using epoll() on the device fd - this works for sockets, and I _think_ it also does what we want for input devices.
