### ISSUE TITLE
`busctl monitor SERVICE` seems to ignore match rule

### ISSUE THREAD

**Issue by segfault3** [systemd/systemd#8356]
### Submission type
 - Bug report

### systemd version the issue has been seen with

237

### Used distribution

Debian buster (testing)

### Expected behaviour you didn't see

When using `busctl --match=MATCH monitor SERVICE` , I expected the resulting output to be filtered according to the match rule expression `MATCH`. Example for a command I tried: 

    busctl --match "type='signal',path='/org/freedesktop/systemd1/unit/cron_2eservice'" monitor org.freedesktop.systemd1

When I remove the `SERVICE` part (`org.freedesktop.systemd1`), it works as expected.

### Unexpected behaviour you saw

The command seems to print all messages exchanged on the bus, ignoring the provided match rule.

**Comment by segfault3** [comment]
Nevermind, I misunderstood what should be provided by `SERVICE`. It seems expects a systemd service name, not a bus.

**Comment by bouk** [comment]
If anyone else comes across this: the reason is that the monitor argument overrides the match expression. So if you remove the argument after `monitor` it works as expected.
