### ISSUE TITLE
resolved: How to specify “local domain name”?

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8357]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 237

### Used distribution

> Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

> A way to configure the local domain name. From [resolve.conf(5)](http://man7.org/linux/man-pages/man5/resolv.conf.5.html):

>        domain Local domain name.
>               Most queries for names within this domain can use short names
>               relative to the local domain.  If set to '.', the root domain
>               is considered.  If no domain entry is present, the domain is
>               determined from the local hostname returned by gethostname(2);
>               the domain part is taken to be everything after the first '.'.
>               Finally, if the hostname does not contain a domain part, the
>               root domain is assumed.

### In case of bug report: Unexpected behaviour you saw

> No `domain …` entry in `/etc/resolve.conf` with systemd-resolved.

### In case of bug report: Steps to reproduce the problem

> Find a way to add `domain bla` to `/etc/resolve.conf`.
>
> ```
> $ ls -l /etc/resolv.conf
> lrwxrwxrwx 1 root system 37 Mar  5 12:41 /etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf
> ```

**Comment by filbranden** [comment]
Just use `Domains=...` in resolved.conf, which will produce a `search ...`.

In resolv.conf (and the generated stub-resolv.conf), `search` overrides `domain` whenever is set. In other words, using `search` instead of `domain` is more general and is what you should be doing anyways... (See the man page for resolv.conf for a more thorough explanation on `search`.)

Does that address your issue?

**Comment by filbranden** [comment]
Or: Set a fully qualified name in `/etc/hostname` (or using `hostnamectl`) since by default the glibc resolver will take the domain from the hostname if not specified in `resolv.conf`.

**Comment by poettering** [comment]
what specifically do you mean by "domain" in this context? for resolved there's no difference between resolv.conf's "search" and "domain" fields, really, and I am not sure why it should distuingish the two. What precisely are you trying to do? why does the distinction between the two fields matter to you?

**Comment by poettering** [comment]
Closing. I think the distinction between "domain" and "search" in /etc/resolv.conf is mostly historical, and what resolved is doing there is pretty much equivalent, even though we conceptually only support "search", not "domain"

**Comment by earonesty** [comment]
There is a distinction between "search" and "domain" that is quite important.  Ignoring it renders certain configurations impossible.
