### ISSUE TITLE
Certain values from `/etc/sysctl.conf` not loaded by `systemd-sysctl.service`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8360]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Modified Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

> `net.ipv6.conf.all.disable_ipv6 = 1` in `/etc/sysctl.conf` is not applied by `systemd-sysctl.service`.

### In case of bug report: Unexpected behaviour you saw

> ```
> $ more /proc/sys/net/ipv6/conf/all/disable_ipv6
> 0
> ```

### In case of bug report: Steps to reproduce the problem

[The trace from `sudo strace -o strace-systemd-sysctl.txt /lib/systemd/systemd-sysctl` shows that the IPv6 setting is not applied.](https://github.com/systemd/systemd/files/1781193/strace-systemd-sysctl.txt)

> ```
> $ sudo journualctl -u systemd-sysctl.service -b
> -- Logs begin at Mon 2013-04-08 16:01:40 CEST, end at Mon 2018-03-05 15:01:34 CET. --
> Mar 01 20:02:34 keineahnung.molgen.mpg.de systemd[1]: Started Apply Kernel Variables.
> ```

Strangely, putting the value under `/etc/sysctl.conf.d/01-disable-ipv6.conf` works.

Please find the file [sysctl.conf.txt attached](https://github.com/systemd/systemd/files/1781204/sysctl.conf.txt) (with the *txt* suffix for GitHub).

**Comment by floppym** [comment]
`systemd-sysctl` does not read `/etc/sysctl.conf` at all. It only processes entries in the `sysctl.d` directory.

**Comment by paulmenzel** [comment]
Thank you. I misread the manual page. It’s still a surprising change in my opinion.  The symbolic link below fixed it here.

    sudo ln -sf /etc/sysctl.conf /etc/sysctl.d/99-sysctl.conf

**Comment by paulmenzel** [comment]
In my opinion, systemd-sysctl should have checked for the existence of `/etc/sysctl.conf` and output a warning, if it’s present.

**Comment by boucman** [comment]
That link exists here... not sure if my distro created it or systemd itself...

**Comment by l1x** [comment]
> /etc/sysctl.conf /etc/sysctl.d/99-sysctl.conf

Exactly. But we live in a world when the most insane make the decisions and be proud of it.

¯\_(ツ)_/¯

**Comment by l1x** [comment]
> In my opinion, systemd-sysctl should have checked for the existence of `/etc/sysctl.conf` and output a warning, if it’s present.

Exactly. But we live in a world when the most insane make the decisions and be proud of it.

¯\_(ツ)_/¯

**Comment by keszybz** [comment]
Since 04bf3c1a60d82791e0320381e9268f727708f776, distros are supposed to create the symlink. I think we should provide the symlink in the meson.build scripts… If somebody submits a patch to add that, I'd be happy to merge it.
