### ISSUE TITLE
/etc/resolv.conf symlink should not be created if systemd-resolved is not running

### ISSUE THREAD

**Issue by hwoarang** [systemd/systemd#8373]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 238

### Used distribution

> openSUSE Tumbleweed

### In case of bug report: Expected behaviour you didn't see

> systemd should not create the `/etc/resolv.conf -> /run/systemd/resolve/resolv.conf` symlink if `systemd-resolved` is not running.

### In case of bug report: Unexpected behaviour you saw

> `/etc/resolv.conf` symlink was created even though `systemd-resolved` was not running

Fedora uses the following patch to workaround the problem
https://src.fedoraproject.org/rpms/systemd/blob/master/f/0998-resolved-create-etc-resolv.conf-symlink-at-runtime.patch

would it be possible to have it merged upstream?

### In case of bug report: Steps to reproduce the problem

* install latest systemd
* make sure you don't have `/etc/resolv.conf` around
* stop `systemd-resolved`
* reboot system

**Comment by evrardjp** [comment]
👍

**Comment by poettering** [comment]
we just create the symlink if noone else does. Please figure out who is supposed to create the symlink on your OS, and make sure he does so early on. resolved's tmpfiles snippet only creates the symlink if noone else does really, in an attempt to make the best of a broken configuration really.

**Comment by evrardjp** [comment]
I'd only create the symlink in resolved. That doesn't make sense to throw the symlink if systemd-resolved isn't used.

**Comment by evrardjp** [comment]
Shouldn't we just let the packagers do this symlink, so that less code is shipped (it would look less like black magic)?

**Comment by hwoarang** [comment]
@poettering you missed my point I think. The symlink shouldn't be created at all if systemd-resolved is not running. Why would you want to create such a symlink if nothing but systemd-resolved understands it?

**Comment by evrardjp** [comment]
I think we should either include the fedora patch above (because it's smarter), or simply remove the whole linking from the ``tmpfiles.d/etc.conf.m4``. But in the latter, it's more packaging work, which will cause complaints.

**Comment by fbuihuu** [comment]
@poettering one prob with this is that if another network manager is installed afterwards, it will be confused by the already created symlink.

And I still think it's not a good idea for daemons to rely on systemd-tmpfiles to create theirs own paths. If it's the case, daemons should take care of this by their own otherwise the design is fragile and the paths are present for no good reasons (which can be confusing).
