### ISSUE TITLE
DHCP interface seen as "routing-only"

### ISSUE THREAD

**Issue by marcogh** [systemd/systemd#8384]
### Submission type

 - Bug report

###  systemd version:
 
> sytemd 237

### Distribution
> Ubuntu 18.04
### In case of bug report: Expected behaviour you didn't see

> systemd-resolve doesn't resolve dotted names at home. it works in 2 different other offices.
> systemd-resolve resolves `host.lan` names.
> Same empty configuration everywhere, with dhcp.

### In case of bug report: Unexpected behaviour you saw

> systemd-networkd saw my network as 'routing-only' 
> cat /run/systemd/netif/state returns:
`OPER_STATE=routable`

### In case of bug report: Steps to reproduce the problem

My DNS Domain "lan" is prefixed with a '~'

`/etc/resolv.conf` is a link to `../run/systemd/resolve/stub-resolv.conf`

```
$ systemd-resolve --status
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      ...
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 2 (wifi0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 10.33.1.3
                      fe80::fad1:11ff:feb7:4ede
          DNS Domain: ~lan
```

**Comment by poettering** [comment]
So, how did you configure that network interface? with networkd? If so, how does the .network file for it look like? What did you set UseDomains= to?

**Comment by marcogh** [comment]
the interface was configured through gnome-shell -> wireless -> select
network.

the only configuration file is /etc/NetworkManager/system-connections/mywifi

[connection]
id=tatozland
uuid=dcef72b8-wwww-xxxx-yyyy-7d8f4e7ae0f9
type=wifi
permissions=

[wifi]
mac-address=9C:B6:D0:XX:XX:XX
mac-address-blacklist=
mode=infrastructure
ssid=tatozland

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=thepassword

[ipv4]
dns-search=
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto

**Comment by poettering** [comment]
So it appears NM sets the "routing-only" prefix ("~") on your domain hence. Which is an OK thing to do, for security reasons. I figure you can tell NM though not to do that. Either way, resolved is actually doing what it is told here, with the "~" prefix. 

Hence I think there's nothing borked with resolved here, but you might simply need to toggle some option in NM somewhere to not prefix with "~".
