### ISSUE TITLE
Segfault mounting cgroups on ZEN kernel

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#8387]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v238

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Boots fine

### In case of bug report: Unexpected behaviour you saw

> Segfaults in libc after mounting cpuset cgroup

### In case of bug report: Steps to reproduce the problem

Linux ZEN is built with MuQSS (which has a `cpu` cgroup controller but no `cpuacct` one).
--> systemd in initramfs segfaults.

Booting with `systemd.unified_cgroup_hierarchy` avoids the problem.
**Reverting commit 56c8d7444ac212c48443a0d30e42ea279140f96d fixes the problem.**

It appears the issue is that the code at https://github.com/systemd/systemd/blob/56c8d7444ac212c48443a0d30e42ea279140f96d/src/core/mount-setup.c#L256-L267 now creates an array of arrays of string literals, but the code at https://github.com/systemd/systemd/blob/56c8d7444ac212c48443a0d30e42ea279140f96d/src/core/mount-setup.c#L292-L311 expects to manipulate heap-allocated strings.

Downstream bug: https://bugs.archlinux.org/task/57741

**Comment by heftig** [comment]
FWIW, here's a photo of a failed boot:
https://matrix.archlinux.org/_matrix/media/v1/download/matrix.org/vuBrimPJDrNAeSabjxNWAhTG

**Comment by evverx** [comment]
The analysis above seems to be correct. The crash can be reproduced by removing `cpuacct` from `/proc/cgroups` before running `systemd`:
```sh
bash-4.4# grep -v cpuacct /proc/cgroups >CGROUPS
bash-4.4# mount --bind CGROUPS /proc/cgroups
bash-4.4# umount -R /sys/fs/cgroup/
bash-4.4# exec /usr/lib/systemd/systemd
```
, which leads to `free` causing the crash:
```sh
=================================================================
==1==ERROR: AddressSanitizer: SEGV on unknown address 0x56320a25b450 (pc 0x7fbb59a9b225 bp 0x7ffe5ef49480 sp 0x7ffe5ef49430 T0)
==1==The signal is caused by a WRITE memory access.
    #0 0x7fbb59a9b224  (/lib64/libasan.so.4+0x26224)
    #1 0x7fbb59b53482 in __interceptor_free (/lib64/libasan.so.4+0xde482)
    #2 0x56320a077f3c in mount_cgroup_controllers ../src/core/mount-setup.c:303
    #3 0x563209fb743c in initialize_runtime ../src/core/main.c:1825
    #4 0x563209fba424 in main ../src/core/main.c:2370
    #5 0x7fbb5762c009 in __libc_start_main (/lib64/libc.so.6+0x21009)
    #6 0x563209fa8cc9 in _start (/usr/lib/systemd/systemd+0x10acc9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libasan.so.4+0x26224)
==1==ABORTING
```

**Comment by yuwata** [comment]
I've created #8391.
