### ISSUE TITLE
DRM devices opened by logind stay referenced indefinitely by PID 1

### ISSUE THREAD

**Issue by sigmaSd** [systemd/systemd#8393]
### Submission type

 - Bug report

### systemd version the issue has been seen with

>237

### Used distribution

>Archlinux

### In case of bug report: Expected behaviour you didn't see

>nvidia_drm module unloaded successfully

### In case of bug report: Unexpected behaviour you saw

>unable to load nvidia_drm module , still in use by systemd-logind

Hi, 
So basicly this issue #6908 still exists.
I use nvidia-xrun https://github.com/Witko/nvidia-xrun to use my nvidia card on my optimus laptop.
after I finisih I try to unload nvidia_drm module but I it fails , cause Its is in use.

#lsof -n | grep "/dev/dri/card/1"
systemd      1                            root   18u      CHR              226,1      0t0      45611 /dev/dri/card1

**Comment by bl33pbl0p** [comment]
Can you test with 238? Someone reported on reddit that this was infact fixed with 238.

**Comment by sigmaSd** [comment]
I can confirm its fixed with 238 in my case .
