### ISSUE TITLE
Stop hardcoding and blocking customization of mount options

### ISSUE THREAD

**Issue by v-fox** [systemd/systemd#8394]
### Submission type

 - Bug report
(More of "defect of the design", actually)

### systemd version the issue has been seen with

>[current git](https://github.com/systemd/systemd/blob/39f305a901934dfcc064cffd4e419b92d90b02c0/src/core/mount-setup.c#L136)

### Used distribution

> openSUSE

### In case of bug report: Expected behaviour you didn't see

> All fstab and .mount directives working.

### In case of bug report: Unexpected behaviour you saw

> systemd forcing "enough for everyone" kind of mount options.

### In case of bug report: Steps to reproduce the problem

> Use it.

So, I've been trying for a while to change default option for "system" mount such as all tmpfs-based paths, including /dev/shm but had limited luck. Today I was able to force systemd to:
* Stop mounting debugfs by /dev/null symlink for /etc/systemd/system/sys-kernel-debug.mount
* Start mounting tracefs which is safer subset of debugfs by hacky /etc/systemd/system/sys-kernel-tracing.mount
* Mount /tmp as 256MB tmpfs with `huge=advise` option by another hack in /etc/systemd/system/tmp.mount

Because I've tried to migrate my system on exclusive usage of [transparent hugepages](https://www.kernel.org/doc/Documentation/vm/transhuge.txt) I tried to put proper "huge" option (such as 'within_size' and 'advise') for all shm/tmpfs mounts while also limiting their size to make sure that ALL of them + zswap don't amount to more than 50% of RAM instead of each of them having default useless 50% limit. BUT I can't do it for /dev/shm and /run because, as if it were not enough to ignore fstab entries, systemd ignores its own .mount entries because, apparently, those are forbidden "API-mounts" which are forced to have systemd's hardcoded options in [/src/core/mount-setup.c](https://github.com/systemd/systemd/blob/39f305a901934dfcc064cffd4e419b92d90b02c0/src/core/mount-setup.c#L136).

**Comment by poettering** [comment]
fstab mount options for these mount points *are* applied. That is in fact the whole reason why systemd-remount-fs.service exists: it goes through all API VFS in /etc/fstab and issues remount calls to the kernel to ensure the mount options listed are applied, explicitly and only in order to support what you are doing.

Are you saying that systemd-remount-fs.service doesn't work for you?

**Comment by v-fox** [comment]
Huh, I have always seen fstab entries for "system" mountpoints completely ignored. And systemd-remount-fs.service is listed as successfully completed in logs. Or maybe I tried long ago and then commented out these entries in fstab.  I also would want to use such directive in live-cd build. fstab is generated by 'kiwi' live-building toolkit, so writing systemd's .mount-files might still be necessary but journalctl says "dev-shm.mount: Cannot create mount unit for API file system /dev/shm. Refusing."

I will try fstab approach on next reboot and tell how it goes. Can you, just in case, write example .mount-files for /tmp, tracefs (as replacement of debugfs), /dev/shm and /run ? At least their mandatory directives to avoid confusing systemd.

Also, you might be interested to know that using transparent hugepages with default settings in /sys/kernel/mm/transparent_hugepage/khugepaged/* and shm/memfd enabled in pulseaudio makes it stutter and xrun horribly every minute, at least while watching Youtube in Firefox when PA is a JACK client. However, disabling shm/memfd and setting something like
```
/sys/kernel/mm/transparent_hugepage/defrag:always defer [defer+madvise] madvise never
/sys/kernel/mm/transparent_hugepage/enabled:[always] madvise never
/sys/kernel/mm/transparent_hugepage/shmem_enabled:always [within_size] advise never deny force
/sys/kernel/mm/transparent_hugepage/use_zero_page:1
/sys/kernel/mm/transparent_hugepage/khugepaged/alloc_sleep_millisecs:15
/sys/kernel/mm/transparent_hugepage/khugepaged/defrag:0
/sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none:511
/sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_swap:511
/sys/kernel/mm/transparent_hugepage/khugepaged/pages_to_scan:4
/sys/kernel/mm/transparent_hugepage/khugepaged/scan_sleep_millisecs:1

kernel.sched_rr_timeslice_ms=1
vm.compact_unevictable_allowed=1
vm.hugepages_treat_as_movable=1
vm.min_free_kbytes=262144
vm.zone_reclaim_mode=3
vm.vfs_cache_pressure=2
vm.swappiness=100
vm.page-cluster=5
vm.watermark_scale_factor=100
```
fixes stuttering. It mostly because of default "defrag periodically and immediately" and "hold CPU for long while scanning big page chunks". I hope that with 'huge' option on tmpfs/shm it will stop to stutter even with shm/memfd enabled in it. My PC is x86_64 with 16GB RAM + zswap + SSD-swap.

**Comment by v-fox** [comment]
So, I did fstab approach and it, indeed, worked ! Thanks for the advice.
Working .mount would be nice thought. Although it would be a while until I'm going to test out this on livecd builds.

Pulseaudio-on-JACK seems to work fine too. However, it doesn't seem to be creating files in /dev/shm like it used to not long ago even with memfd enabled. Maybe there were more factors in its previous misbehaviour.

**Comment by poettering** [comment]
> I will try fstab approach on next reboot and tell how it goes. Can you, just in case, write example .mount-files for /tmp, tracefs (as replacement of debugfs), /dev/shm and /run ? At least their mandatory directives to avoid confusing systemd.

No, API VFS are not supported as .mount units. Currently the only way to configure mount options for them is by adding an /etc/fstab file. And I think this is unlikely to change.
