### ISSUE TITLE
Allow ordering generators

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8396]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

238

### Used distribution

Exherbo

### RFE
Introduce a scheme to order generators. Currently they are parallel which is desirable in most cases, but sometimes a generator might be buggy or the generated unit might be wrong partially, hence being able to make changes to that generated unit by having an administrator's generator ordered after one makes things really easy (the only other solution in such a case is patching the generator if it is not a script, or having a very early boot service that modifies the units again and then reloads PID1). I have one idea in mind, but ofcourse this can be discussed and improved.

All generators that are not prefixed with a number- are assumed to be 49-foobar. This automatically allows one to name a generator 01-bazbar or 99-foobaz in /etc and order before or after the ones that get executed in parallel (all at 49 since they aren't prefixed). The ones at the same number would run in parallel. Nothing would break, and people can then order the execution sequentially if they desire.

**Comment by poettering** [comment]
Uh. The fact that they are run in parallel is actually on purpose so that people don't start building pipelines where each generator re-processes the output of the one before it. 

Fix bugs where they are. If a generator is broken, fix it, but don't work around it in a later generator... 

Sorry, but I am firmly against this! I hope this makes some sense though...

**Comment by bl33pbl0p** [comment]
People can still run them sequentially by wrapping all in a shell script, and then modifying the units they wrote. I don't know how not allowing to be able to do this explicitly makes things better. The fact that generators are written in C (atleast those with ship with systemd) makes it non-trivial to patch them (you need to then modify the source and compile your own). Note that it is still possible, by masking the generator i want to order mine before or after and calling it whenever i wish from my own generator.

I am all for fixing problems where they are, but this is not always possible, and ordering generators makes all sense to me. Can you list any disadvantages of doing so, given that by default all generators run in parallel as intended anyway and ordering is something only the administrator can configure explicitly.

**Comment by keszybz** [comment]
To "fix" a generator, add a wrapper in `/etc/systemd/system-generators/` or `/usr/local/lib/systemd/system-generators/` that calls the original generator and adjusts it's output as necessary. (It may even call that other generator with a different output directory and only copy some of the generated files to the "real" directory).
