### ISSUE TITLE
OnFailure starts every exit >0 not only when StartLimit is hit

### ISSUE THREAD

**Issue by xundeenergie** [systemd/systemd#8398]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> up to 237-3

### Used distribution

> Debian buster

### In case of bug report: Unexpected behaviour you saw

 A service with OnFailure= and Restart=on-failure starts the unit defined in OnFailure= every time, the startet service failes. 

The manpage says:

> OnFailure=
>            A space-separated list of one or more units that are
> activated when this unit enters the "failed" state. A service unit using
> Restart= enters the failed state only after the
>            start limits are reached.

So the OnFailure-Unit should be only started once, after StartLimit is hit, not every time, the ExecStart failes.

### In case of bug report: Steps to reproduce the problem

Create two Units:
```
# cat test@.service
[Unit]
Description=Testservice notification
OnFailure=notification-telegram@%n.service

[Service]
Type=simple
Restart=on-failure
#RestartSec=2
ExecStart=/bin/%i
SyslogIdentifier=test@%i.service
StartLimitBurst=5
StartLimitInterval=10
```

And the notification-Unit notification-telegram@%n.service

```
# cat notification-telegram@.service
[Unit]
Description=Send failure-notification about %i to telegram

[Service]
User=xundeenergie
ExecStart=/bin/bash -c "/usr/local/bin/ntfy -b telegram send \"FAILED\n$(systemctl status %i)\""
```
When i start the Test-Unit with systemctl start test@false i get 5
Messages in telegram...

The log is:
```
Mär 08 00:31:53 aldebaran systemd[1]: Started Testservice notification.
Mär 08 00:31:53 aldebaran systemd[1]: test@false.service: Main process
exited, code=exited, status=1/FAILURE
Mär 08 00:31:53 aldebaran systemd[1]: test@false.service: Failed with
result 'exit-code'.
Mär 08 00:31:53 aldebaran systemd[1]: test@false.service: Triggering OnFailure= dependencies.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Service hold-off time over, scheduling restart.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Scheduled restart job, restart counter is at 1.
Mär 08 00:31:54 aldebaran systemd[1]: Stopped Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: Started Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Main process exited, code=exited, status=1/FAILURE
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Failed with result 'exit-code'.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Triggering OnFailure= dependencies.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Service hold-off time over, scheduling restart.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Scheduled restart job, restart counter is at 2.
Mär 08 00:31:54 aldebaran systemd[1]: Stopped Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: Started Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Main process exited, code=exited, status=1/FAILURE
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Failed with result 'exit-code'.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Triggering OnFailure= dependencies.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Service hold-off time over, scheduling restart.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Scheduled restart job, restart counter is at 3.
Mär 08 00:31:54 aldebaran systemd[1]: Stopped Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: Started Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Main process exited, code=exited, status=1/FAILURE
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Failed with result 'exit-code'.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Triggering OnFailure= dependencies.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Service hold-off time over, scheduling restart.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Scheduled restart job, restart counter is at 4.
Mär 08 00:31:54 aldebaran systemd[1]: Stopped Testservice notification.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Start request repeated too quickly.
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Failed with result 'exit-code'.
**Mär 08 00:31:54 aldebaran systemd[1]: Failed to start Testservice notification.**
Mär 08 00:31:54 aldebaran systemd[1]: test@false.service: Triggering OnFailure= dependencies.

```

You see, the Unit from OnFailure= is called 5 times, not at the final "Failed to start Testservice notification"-time.

**Comment by poettering** [comment]
Hmm, I am pretty sure this never actually worked the way the docs say. Not sure whether to adjust the docs to the code or vice versa now...

**Comment by xundeenergie** [comment]
I'm sure, there are a bunch of workarounds out there...

   

  I think, the functionality described in the docs is a good  
functionality. systemd trys to start a service more than once, if it  
fails. A service could have some problems to start (especially if it  
needs a webservice, which is not reachable, but a few tries later it  
is...) and then it starts up correct.

OnFailure sounds for a failing unit, not a failing try.

It is a good habit to start a Unit "OnFailing" only if systemd gives  
up trying to start this unit.

I know, it's software, not humans... But if your child tries to ride a  
bike, you do not say on every fall "You are failing". You will only  
say it after a while, if your child is not able to ride its bike...  
then you give up and send your child home its mom... (start the  
OnFailure-Unit).

If you send your child home to mom every failed try, you are not  
working correct. If your child is not able to ride its bike, your  
child is misconfigured. If you will never send it home, and let your  
child the whole day and night and day and night try to ride the bike,  
then you are not well configured...

The same is with systemd. The habit written down in the docs are good  
habits. So let systemd lern to do, how it is described.

:-)

Would be very glad about!

Thank you

Jakob

----- Nachricht von Lennart Poettering <notifications@github.com> ---------
     Datum: Wed, 21 Mar 2018 10:18:51 +0000 (UTC)
       Von: Lennart Poettering <notifications@github.com>
Antwort an: systemd/systemd  
<reply@reply.github.com>
   Betreff: Re: [systemd/systemd] OnFailure starts every exit >0 not  
only when StartLimit is hit (#8398)
        An: systemd/systemd <systemd@noreply.github.com>
        Cc: xundeenergie <jakob@xundeenergie.at>, Author  
<author@noreply.github.com>

> Hmm, I am pretty sure this never actually worked the way the docs  
> say. Not sure whether to adjust the docs to the code or vice versa  
> now...
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       

----- Ende der Nachricht von Lennart Poettering  
<notifications@github.com> -----



Links:
------
[1] https://github.com/systemd/systemd/issues/8398#issuecomment-374889824
[2]

**Comment by rpodgorny** [comment]
...i was about to write something similar but @xundeenergie put it more nicely. ;-)

so, if you're collecting opinions, i agree (with @xundeenergie).

**Comment by rpodgorny** [comment]
the only corner case that comes to my mind is if there is unlimited number of retries (if such thing is even possible in systemd), the unit never enters the failed state but is not started either. -> if you're using onfailure for notifications, you'll never know something is wrong.

**Comment by xundeenergie** [comment]
If restart-tries in StartLimitSec are less then StartLimitBurst... So if Service needs 10 seconds to start/fail, and 10 retries in a minute are allowed... so the service restarts 6 times in a minute, startlimitburst is not hit... Or RestartSec is 10 seconds, StartLimitSec=1m and StartLimitBurst ist 10... the same... The unit never fails, and the service never starts.... Ok... 

BUT

You should watch journal from time to time... then you see this. 
A developer should know his service and set the correct StartLimits... It's the developers job to set this limits, not systemd's job!!!

My oppinion ;-)

**Comment by rpodgorny** [comment]
yeah, i agree. i still think the docs are correct but the code is not. i just wanted to mention corner cases so lennart (or whoever decides this) has all the information.

**Comment by ssstrat11s** [comment]
@poettering, I definitely would add my concurrence that hopefully the code would be updated to match the "spec" of the documentation. I was hoping for this functionality to be present in v219, perhaps undocumented, so I did not need to move heaven and earth to get that updated in my controlled environment. C'est la vie

It's worth noting that the description of `OnFailure` and `Restart` changed to this documentation sometime after v219 (which says nothing about `OnFailure` only applying after `StartLimit`s have been exhausted), but whoever update it forgot to include the code!

**Comment by ssstrat11s** [comment]
> the only corner case that comes to my mind is if there is unlimited number of retries (if such thing is even possible in systemd), the unit never enters the failed state but is not started either. -> if you're using onfailure for notifications, you'll never know something is wrong.

@rpodgorny It's definitely possible - I actually intentionally did this in my environment to see what the behavior was prior to finding this issue.

**Comment by OlliC** [comment]
I found this issue after testing out OnFailure with Telegram notifications like @xundeenergie. 
Because my service is a badly programmed gameserver that segfaults everytime it gets stopped, i thought that was why it entered a failed state. 

So i also think OnFailure should only be triggered when the service really fails and the startlimit hits. 
But one idea would be to add another option like OnRestart or something that would reflect the current behavior.

**Comment by poettering** [comment]
Fix waiting in #9158

**Comment by codemedic** [comment]
Shame that the effective "OnRestart feature" was taken out with this change.

Having an call-back for every restart would have been very useful for generation of some sort of notification to dev team; especially in cases where crashes are rare, but any crash should be looked into as well as restarted automatically.

I am not particularly after reinstating the facility as such, but after finding a solution to the use case mentioned above; i.e ability to run a unit, when ever a service restarts, with some context about the service that crashed.

Is there a way I can achieve this?

**Comment by codemedic** [comment]
@boucman Thanks, let me give that a try

**Comment by ArunVenugopalan** [comment]
We took this patch and applied on top of v237 to get the OnFailure working as documented. This has introduced a side-effect that `systemctl stop <service>` would now trigger OnFailure=. How do we fix this please? 
1. Would going to v239 get the explicit stop requests working as expected (that is not triggering OnFailure=)?  Or
2. If there is any other patch that's relevant to get this going?

**Comment by b1tninja** [comment]
It would be nice if the OnFailureAction behaved similarly

**Comment by cdprashanth** [comment]
Hi,
Can you please let me know if we get dbus signal  also when OnFailure gets triggered.
In my service-monitoring-app, via dbus, i need to know when a service fails-but-will-not-auto-restart.
My qury is :
https://lists.freedesktop.org/archives/systemd-devel/2022-February/047472.html
https://github.com/systemd/systemd/issues/22564
Thanks for help

**Comment by cdprashanth** [comment]
seems like some more fix is needed 
logged https://github.com/systemd/systemd/issues/23599

**Comment by azerum** [comment]
> ExecStopPost= can probably do that. There are multiple env variables ($EXIT_STATUS and co) that can help filter if the exit was an error or a normal exit...

The slight problem with ExecStopPost= though is that it runs a command, while OnFailure= starts a unit

In case the notification command itself fails, chances are restarting it will eventually deliver the notification. Now, you can write a program that retries notifications, and run it with ExecStopPost=, but it doesn't protect that program from accidental failures (e.g. when OOM killer kills it for some reason)

Unit could be restarted
