### ISSUE TITLE
[RFE] Teach systemd-timedated manage alternative NTP implementations

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#8402]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

- master

systemd-timedated used to know how to manage NTP implementations other than systemd-timesyncd. Lately, we started to discuss the possibility that we will revert to the previous behavior due to numerous complaints from users.

**Comment by yuwata** [comment]
I've created PR #8615. Please take a look.
