### ISSUE TITLE
Does systemd support musl libc?

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#8407]
Hi, everyone! I'm asking about musl libc support in systemd. Does it compile against musl libc? Does it work with musl libc?

**Comment by keszybz** [comment]
This came up in the past, see e.g. #7218. In general we prefer our code to be portable, but we will not add stupid workarounds for functionality missing from libc implementations if this functionality should be generally supported. To answer your question: it is possible to compile against musl, possibly with some small patching. None of the main systemd developers use musl, so we can't provide very precise info.

**Comment by protonesso** [comment]
Thanks for answer!
