### ISSUE TITLE
systemd --user might get started too often on server setups

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#8410]
### Submission type

 - Request for enhancement (RFE)

Let's imagine a server, where you have a lot of crontab entries, that fire every second or a remote management sw that uses ton of ssh commands.
On such machine, there would be a lot of sessions created and destroyed quite often for the same user. This would mean that systemd --user instance can be started pretty often and that could have a negative impact on the whole system.

Maybe we should either introduce a mode where user instances are not terminated after a user logs out, or there is a configurable timeout before between user logs out and systemd is terminated.

**Comment by bl33pbl0p** [comment]
> Maybe we should either introduce a mode where user instances are not terminated after a user logs out

This is what linger provides as well as of now, but it also means the user manager is started on boot, maybe something like https://github.com/systemd/systemd/pull/4434 can be introduced that augments the concept of lingering with start-on-boot and start-on-login, where the former is what it does now but the latter only starts the user manager on login and keeps it running even after all sessions of the user have been closed.

**Comment by poettering** [comment]
Fix waiting in #9824.
