### ISSUE TITLE
networkd: RoutingPolicyRule lookup table name

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#8418]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 237

### Used distribution

> ArchLinux

Right now I have a systemd service, which run the following commands:
```
ip rule add from 10.2.0.0/16 table 200
ip rule add from 10.2.0.0/16 to 10.2.0.0/16 table main
```
It configure the rule, so all traffic from `10.2.0.0/16` where dest != `10.2.0.0/16`, goes to the `200` table and everything else use the `main` table.

I can't do the same with `[RoutingPolicyRule]` as `Table=` only accept the table id, not the table name. 
~~I can of course hardcode the `Table=` to the id of the `main` table (32766 at the moment, which I don't know if stable?)~~, but ideally systemd should be able to lookup the id.

**Comment by ssahani** [comment]
Table's are just numbers in kernel interpreted as names by ip route.

**Comment by amishxda** [comment]
ip command accepts both number and name.

So Table= parameter should accept both name and number.

It makes it much easier and also human readable.

**Comment by boucman** [comment]
where do those names come from, if they are not in the kernel ? config files ?

**Comment by amishxda** [comment]
/etc/iproute2/rt_tables

**Comment by amishmm** [comment]
Little OT: but thats an undocumented feature of iproute2 there.

So one can also place the table names in:
**/etc/iproute2/rt_tables.d/*.conf**
