### ISSUE TITLE
Inaccuracy in systemd-socket-proxyd man page

### ISSUE THREAD

**Issue by maxnikulin** [systemd/systemd#8419]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> git master

### Used distribution

> N/A

### In case of bug report: Expected behaviour you didn't see

> Self-consistent accurate examples.

### In case of bug report: Unexpected behaviour you saw

> Misleading configuration example.

### In case of bug report: Steps to reproduce the problem

> Try to configure starting nginx using socket activation accordingly to "simple example"

Please, review the examples in the systemd-socket-proxyd(8) man page.

Example 2 in the "simple example" section has `PrivateTmp=yes`, however this service file does not have `JoinsNamespaceOf`. Due to nginx configured to listen unix socket in the example 3, systemd-socket-proxyd tries to open nginx.sock in its private /tmp though nginx creates the socket in the system-wide tmp directory. It seems that removing `PrivateTmp` will encourage bad practice of using fixed-name files in the "public" /tmp directory.

Maybe it would be better to swap examples and use unix socket in "namespace example".

**Comment by poettering** [comment]
Fix waiting in #8757
