### ISSUE TITLE
systemd-networkd and systemd-resolved - no way to disable DNS= received from DHCPv4 while keeping DNS= from IPv6 RA

### ISSUE THREAD

**Issue by mikken** [systemd/systemd#8420]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Gentoo

My `.network` config:

```
[DHCP]
UseDNS=yes

[IPv6AcceptRA]
UseDNS=yes
```

If I set `UseDNS=false` in `[DHCP]` section, both dynamic IPv4 and IPv6 servers disappear in `systemd-resolved`. In my network IPv6 servers are received from RDNSS.

I expected IPv6 servers to still stay.

**Comment by ssahani** [comment]
Can't reproduce works fine.

**Comment by ssahani** [comment]
Sorry I reproduced it .  fix is https://github.com/systemd/systemd/pull/8836
