### ISSUE TITLE
Meson error with Systemd 238: src/resolve/meson.build:177:20: ERROR: Expecting rbracket got eof

### ISSUE THREAD

**Issue by austons** [systemd/systemd#8421]
### Submission type

 - Bug report (Regression from 237 -> 238)

### systemd version the issue has been seen with

> 238

### Used distribution

> Shedbuilt GNU/Linux (LFS 8.2 Derived)

### In case of bug report: Expected behaviour you didn't see

> Meson successfully configuring Systemd for compilation with Ninja

### In case of bug report: Unexpected behaviour you saw

> Meson configuration failed for Systemd 238 with the following error:
src/resolve/meson.build:177:20: ERROR: Expecting rbracket got eof.
         [libgcrypt,
         ^__________^

### In case of bug report: Steps to reproduce the problem

> Attempt to compile Systemd 238 on armv7l or aarch64 using Meson 0.44.0, 0.44.1 or 0.45.0 (no other versions tested):
mkdir -v build
cd build
meson --prefix=/usr                \
      --sysconfdir=/etc            \
      --localstatedir=/var         \
      -Dblkid=true                 \
      -Dbuildtype=release          \
      -Ddefault-dnssec=no          \
      -Dfirstboot=false            \
      -Dinstall-tests=false        \
      -Dkill-path=/bin/kill        \
      -Dkmod-path=/bin/kmod        \
      -Dldconfig=false             \
      -Dmount-path=/bin/mount      \
      -Drootprefix=                \
      -Drootlibdir=/lib            \
      -Dsplit-usr=true             \
      -Dsulogin-path=/sbin/sulogin \
      -Dsysusers=false             \
      -Dumount-path=/bin/umount    \
      -Db_lto=false                \
      -Dman=false                  \
      .. && \
NINJAJOBS=4 ninja && \
DESTDIR="/var/tmp/shedmake/systemd" ninja install

I've verified that Systemd 237 compiles without error. A complete meson log of the failure is attached:
[meson-log.txt](https://github.com/systemd/systemd/files/1800094/meson-log.txt)

**Comment by keszybz** [comment]
On Sun, Mar 11, 2018 at 05:57:32AM +0000, Auston Stewart wrote:
> ### Submission type
> 
>  - Bug report (Regression from 237 -> 238)
> 
> ### systemd version the issue has been seen with
> 
> > 238
> 
> ### Used distribution
> 
> > Shedbuilt GNU/Linux (LFS 8.2 Derived)
> 
> ### In case of bug report: Expected behaviour you didn't see
> 
> > Meson successfully configuring Systemd for compilation with Ninja
> 
> ### In case of bug report: Unexpected behaviour you saw
> 
> > Meson configuration failed for Systemd 238 with the following error:
> src/resolve/meson.build:177:20: ERROR: Expecting rbracket got eof.
>          [libgcrypt,
>          ^__________^

It looks like your local checkout is corrupted. Please verify that that
file is not truncated.

Zbyszek

**Comment by austons** [comment]
Ugh, my script was still applying a patch from LFS 8.2 intended for Systemd 237 that corrupts this file. My fault for not realizing that. Please close as invalid.
