### ISSUE TITLE
systemd-analyze firmware time compounds with each boot

### ISSUE THREAD

**Issue by polarathene** [systemd/systemd#8422]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Manjaro KDE(latest ISO updated to 11th March 2018)

UEFI + GPT install to SATA SSD. systemd-boot as bootloader. Tried kernels 4.14, 4.15, 4.16.
Intel i5-6500, H170 chipset, motherboard vendor ASRock.

### In case of bug report: Expected behaviour you didn't see

> Accurate firmware time by `systemd-analyze`.

### In case of bug report: Unexpected behaviour you saw

> Firmware time increments/grows/compounds with each boot. Appears to add time since the system was last (re)booted. It does overflow at some point, reported time does not appear to exceed 1 hour.

### In case of bug report: Steps to reproduce the problem

Boot system, check time with `systemd-analyze`, see a result like(loader time is fine, due to manual editing):

```
Startup finished in 9min 39.222s (firmware) + 23.462s (loader) + 315ms (kernel) + 802ms (initrd) + 609ms (userspace) = 10min 4.412s
graphical.target reached after 602ms in userspace
```

`systemctl show -a`, not sure if this is helpful:

```
Version=237
Features=+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN +IDN +PCRE2 default-hierarchy=hybrid
Virtualization=
Architecture=x86-64
Tainted=
FirmwareTimestamp=
FirmwareTimestampMonotonic=602684564
LoaderTimestamp=
LoaderTimestampMonotonic=23462241
KernelTimestamp=Sun 2018-03-11 16:06:06 NZDT
KernelTimestampMonotonic=0
InitRDTimestamp=Sun 2018-03-11 16:06:06 NZDT
InitRDTimestampMonotonic=315455
UserspaceTimestamp=Sun 2018-03-11 16:06:07 NZDT
UserspaceTimestampMonotonic=1118173
FinishTimestamp=Sun 2018-03-11 16:06:07 NZDT
FinishTimestampMonotonic=1727568
SecurityStartTimestamp=Sun 2018-03-11 16:06:06 NZDT
SecurityStartTimestampMonotonic=315668
SecurityFinishTimestamp=Sun 2018-03-11 16:06:06 NZDT
SecurityFinishTimestampMonotonic=315670
GeneratorsStartTimestamp=Sun 2018-03-11 16:06:06 NZDT
GeneratorsStartTimestampMonotonic=329230
GeneratorsFinishTimestamp=Sun 2018-03-11 16:06:06 NZDT
GeneratorsFinishTimestampMonotonic=332053
UnitsLoadStartTimestamp=Sun 2018-03-11 16:06:06 NZDT
UnitsLoadStartTimestampMonotonic=332157
UnitsLoadFinishTimestamp=Sun 2018-03-11 16:06:06 NZDT
UnitsLoadFinishTimestampMonotonic=332665
LogLevel=info
LogTarget=journal-or-kmsg
NNames=213
NFailedUnits=0
NJobs=0
NInstalledJobs=171
NFailedJobs=2
Progress=1
Environment=LANG=en_NZ.UTF-8 LC_ADDRESS=en_NZ.UTF-8 LC_IDENTIFICATION=en_NZ.UTF-8 LC_MEASUREMENT=en_NZ.UTF-8 LC_MONETARY=en_NZ.UTF-8 LC_NAME=en_NZ.UTF LC_NUMERIC=en_NZ.UTF-8 LC_PAPER=en_NZ.UTF-8 LC_TELEPHONE=en_NZ.UTF-8 LC_TIME=en_NZ.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
UnitPath=/etc/systemd/system.control /run/systemd/system.control /run/systemd/transient /etc/systemd/system /run/systemd/system /run/systemd/generator /usr/lib/systemd/system /run/systemd/generator.late
DefaultStandardOutput=journal
DefaultStandardError=journal
RuntimeWatchdogUSec=0
ShutdownWatchdogUSec=10min
ServiceWatchdogs=yes
ControlGroup=
SystemState=running
ExitCode=[unprintable]
DefaultTimerAccuracyUSec=1min
DefaultTimeoutStartUSec=1min 30s
DefaultTimeoutStopUSec=1min 30s
DefaultRestartUSec=100ms
DefaultStartLimitIntervalUSec=10s
DefaultStartLimitBurst=5
DefaultCPUAccounting=no
DefaultBlockIOAccounting=no
DefaultMemoryAccounting=no
DefaultTasksAccounting=yes
DefaultLimitCPU=infinity
DefaultLimitCPUSoft=infinity
DefaultLimitFSIZE=infinity
DefaultLimitFSIZESoft=infinity
DefaultLimitDATA=infinity
DefaultLimitDATASoft=infinity
DefaultLimitSTACK=infinity
DefaultLimitSTACKSoft=8388608
DefaultLimitCORE=infinity
DefaultLimitCORESoft=infinity
DefaultLimitRSS=infinity
DefaultLimitRSSSoft=infinity
DefaultLimitNOFILE=4096
DefaultLimitNOFILESoft=1024
DefaultLimitAS=infinity
DefaultLimitASSoft=infinity
DefaultLimitNPROC=125554
DefaultLimitNPROCSoft=125554
DefaultLimitMEMLOCK=16777216
DefaultLimitMEMLOCKSoft=16777216
DefaultLimitLOCKS=infinity
DefaultLimitLOCKSSoft=infinity
DefaultLimitSIGPENDING=125554
DefaultLimitSIGPENDINGSoft=125554
DefaultLimitMSGQUEUE=819200
DefaultLimitMSGQUEUESoft=819200
DefaultLimitNICE=0
DefaultLimitNICESoft=0
DefaultLimitRTPRIO=0
DefaultLimitRTPRIOSoft=0
DefaultLimitRTTIME=infinity
DefaultLimitRTTIMESoft=infinity
DefaultTasksMax=4915
TimerSlackNSec=50000
```

Presumably this is on my end and systemd is working with what it has. If so, could any BIOS/UEFI setting or kernel parameters remedy the issue, or is it likely buggy firmware doing something incorrectly?(I'm not sure how systemd is accessing the timing information).

I've also tried adding systemd to initrd image, no difference.

**Comment by boucman** [comment]
well, that 'makes sense' as in : it is the actual time between power on and the time the kernel started... the fact that another kernel booted before that is not something we know.

Now, I understand this makes no sense, and we would need a way to differentiate a "first kernel" from  "hot reboot" kernel, but I don't know how to know that.

**Comment by polarathene** [comment]
> Now, I understand this makes no sense, and we would need a way to differentiate a "first kernel" from "hot reboot" kernel, but I don't know how to know that.

Is this how `systemd-analyze` usually behaves when reporting firmware time? loader/kernel/initrd/userspace are all fine. I was under the assumption the firmware time being incorrect unless a cold boot might be firmware bug with my motherboard as I've not seen anyone else with the issue.

I was curious if doing a system restart would be faster than a cold boot, using a timer on my phone it seems to be about 1 second faster but I am not sure if I'm timing it properly. I would start when the sound of fans briefly changed. Firmware times are different based on BIOS settings, especially with FastBoot or UltraFastBoot enabled, the latter I thought might result in faster reboot times vs cold boots.

---

Differentiating the kernel times you'd be able to store the previous firmware time somewhere I guess. I know you can't really tell if it was a cold or warm/hot boot, a command flag might cater to that. However it'd not always be accurate because the firmware time can overflow, so if it's been a while since the last reboot, the delta may not be correct either unless you know when it overflows and use something like ISO 8601 timestamps?

I'm not sure how the firmware time is being sourced, is it provided by the firmware via some efivar? Maybe something like `systemd-analyze time --set-cold-boot`(cold_boot = ISO8601 timestamp after firmware - firmware time), `systemd-analyze time --firmware-delta` (Somehow use cold_boot value with some other timestamp to know what current boots firmware time is?) would work?

> well, that 'makes sense' as in : it is the actual time between power on and the time the kernel started... the fact that another kernel booted before that is not something we know.

I'm not too familiar with how reboots work, the way you say it reminds me of kexec "a mechanism of the Linux kernel that allows booting of a new kernel from the currently running one.".

**Comment by boucman** [comment]
To be completely honest, I have dealt with the innards of systemd-analyze time recently, but the numbers come from PID1 itself and I have no real knowledge of where those times come from

for kernel, initrd and userspace, it's all based on kernel times, which have a 0 at the time the kernel is started, but firmware and loader, i'm not sure... these are the ones we get directly from systemd, so I don't know.

**Comment by poettering** [comment]
Sounds like a firmware bug to me.

We read the ACPI FPDT do get this data. If it's not properly reset during boot there's very little we can do about this I fear. 

There are some ACPI tools available which might help you debug the FPDT data a bit, our code for that is in https://github.com/systemd/systemd/blob/master/src/shared/acpi-fpdt.c#L82.

I fear there's very little else we can help you with upstream here. We could start maintaining a blacklist of some kind in udev to mark your firmware as borked, but I am not too keen on adding that.
