### ISSUE TITLE
wiki page is wrong about the effect of enabling systemd-networkd-wait-online.service etc

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8425]
### Submission type

 - Bug report

### systemd version the issue has been seen with

Wiki page: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

### Used distribution

Fedora

### In case of bug report: Expected behaviour you didn't see

> #### Cut the crap! How do I make network.target work for me?
>
> Well, that depends on your setup and the services you plan to run after it (see above). Many network management solutions provide a way to unconditionally pull in network-online.target, and thus upgrading the effect of network.target to the effect of network-online.target.
>
> If you use NetworkManager you can do this by enabling NetworkManager-wait-online.service:
>
> systemctl enable NetworkManager-wait-online.service
>
> If you use systemd-networkd you can do this by enabling systemd-networkd-wait-online.service:
>
> systemctl enable systemd-networkd-wait-online.service

### In case of bug report: Unexpected behaviour you saw

https://github.com/systemd/systemd/blob/a7df2d1e4349a8c90223d8b7ae339dbad05da503/units/systemd-networkd-wait-online.service.in#L25

(i.e. since the above line does not say `WantedBy=network.target`, the wiki page is incorrect).

**Comment by keszybz** [comment]
Yeah, those wiki pages, they aren't such a great idea. Long-term, it'd be best to move documentation to man pages. Anyway, I updated the page to match status quo.

**Comment by poettering** [comment]
> Yeah, those wiki pages, they aren't such a great idea. Long-term, it'd be best to move documentation to man pages. Anyway, I updated the page to match status quo.

yupp, moving things out of the wiki would be good. Either into man pages or into markdown files in our git.
