### ISSUE TITLE
nspawn: uidshifted root can't access /proc entries

### ISSUE THREAD

**Issue by MorphBonehunter** [systemd/systemd#8427]
### Submission type

 - Bug report
 - Follow up to #3052

### systemd version the issue has been seen with

> 237

### Used distribution

> Arch Linux (4.14.24-1-lts)

### In case of bug report: Expected behaviour you didn't see

> inside nspawn container i should be able to read `/proc/net/ip_tables_names`

### In case of bug report: Unexpected behaviour you saw

> `/proc/net/ip_tables_names` is owned by `nobody`

### In case of bug report: Steps to reproduce the problem

> try to read `/proc/net/ip_tables_names`
> ```
> cat /proc/net/ip_tables_names
> cat: /proc/net/ip_tables_names: Permission denied
> ls -la /proc/net/ip_tables_names
> -r--r----- 1 nobody nobody 0 12. Mär 10:22 /proc/net/ip_tables_names
> ```
According to https://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf-next.git/commit/?id=f13f2aeed154da8e48f90b85e720f8ba39b1e881 this should work.
This fix was integrated into Kernel 4.5 (https://bugzilla.netfilter.org/show_bug.cgi?id=1064#c3), so i think this should also work in nspawn-containers.

**Comment by MorphBonehunter** [comment]
@keszybz / @poettering / @eworm-de:
could it be that the change breaks the `--network-interface` procedure?
Background: I'm on arch linux und upgrade to 238.51 which basically means c58ab03f64890e7db88745a843bd4520e307099b in systemd-stable ans so includes this change.
After Upgrade i can not get the  `--network-interface` option to work until i left out the `-U` (i use the default unit file and override with an nspawn file).
After revert to 238.0 (which means 738ab7502afb7663d9aacdd73e79025aa7cd0a9b) it woks like expected again.

**Comment by keszybz** [comment]
@MorphBonehunter it's possible. Please file a new issue so we can track this properly.

**Comment by filbranden** [comment]
I believe #8633 might fix this... Any chance one of you could test it (or do an initial code review there)?

**Comment by MorphBonehunter** [comment]
I've opened an new Bug Report.
