### ISSUE TITLE
openvpn triggers `systemd-journal` and makes the CPU spike up

### ISSUE THREAD

**Issue by trappedinspacetime** [systemd/systemd#8435]
### Submission type

 - Bug report
 

### systemd version the issue has been seen with

 systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

> …

### Used distribution
Ubuntu 16.04
> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw
While `openvpn` process is running `systemd-journal`  gets CPU hungry and slows down the computer
I also noticed `rsyslogd` process was running.
> …

### In case of bug report: Steps to reproduce the problem
I use the following `vpn` client https://github.com/Dragon2fly/vpngate-with-proxy, when I launch it via `./run tui` within `vpngate-with-proxy` openvpn process starts and `systemd-journal` spikes up.
> …

**Comment by poettering** [comment]
Well, does openvpn log a lot? If so, it's not suprising that the journald starts processing it. What precisely is not working the way it should?

**Comment by poettering** [comment]
Let's close, due to lack of response.
