### ISSUE TITLE
wrong rpath in compiled libraries and binaries

### ISSUE THREAD

**Issue by Char-Aznable** [systemd/systemd#8437]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> CentOS release 6.8 (Final)

### In case of bug report: Unexpected behaviour you saw

> installation failed with: 
/home/aznb/.linuxbrew/Cellar/systemd/238/bin/journalctl: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
```
ldd /home/aznb/.linuxbrew/Cellar/systemd/238/bin/journalctl
        linux-vdso.so.1 (0x00007ffd8bdb2000)
        libsystemd-shared-238.so => /home/aznb/.linuxbrew/Cellar/systemd/238/lib/systemd/libsystemd-shared-238.so (0x00007f3660238000)
        libpthread.so.0 => /home/aznb/.linuxbrew/Cellar/glibc/2.23/lib/libpthread.so.0 (0x00007f366001b000)
        libc.so.6 => /home/aznb/.linuxbrew/Cellar/glibc/2.23/lib/libc.so.6 (0x00007f365fc7b000)
        librt.so.1 => /home/aznb/.linuxbrew/Cellar/glibc/2.23/lib/librt.so.1 (0x00007f365fa73000)
        /home/aznb/.linuxbrew/lib/ld.so (0x00007f366069b000)
        libcap.so.2 => not found
        libgcrypt.so.20 => not found
        libidn.so.11 => not found
        liblzma.so.5 => not found
        libblkid.so.1 => not found
        libmount.so.1 => not found
```
However, ldd on the journalctl in the build directory looks fine:
```
ldd build/journalctl
        linux-vdso.so.1 (0x00007fffc3cf3000)
        libsystemd-shared-238.so => /scratch/tmp/systemd-238/build/src/shared/libsystemd-shared-238.so (0x00007f241c5db000)
        libpthread.so.0 => /home/aznb/.linuxbrew/lib/libpthread.so.0 (0x00007f241c3be000)
        libc.so.6 => /home/aznb/.linuxbrew/lib/libc.so.6 (0x00007f241c01e000)
        librt.so.1 => /home/aznb/.linuxbrew/lib/librt.so.1 (0x00007f241be16000)
        libcap.so.2 => /home/aznb/.linuxbrew/lib/libcap.so.2 (0x00007f241bc10000)
        libgcrypt.so.20 => /home/aznb/.linuxbrew/lib/libgcrypt.so.20 (0x00007f241b8f3000)
        libidn.so.11 => /home/aznb/.linuxbrew/lib/libidn.so.11 (0x00007f241b6c0000)
        liblzma.so.5 => /home/aznb/.linuxbrew/lib/liblzma.so.5 (0x00007f241b49b000)
        libblkid.so.1 => /home/aznb/.linuxbrew/lib/libblkid.so.1 (0x00007f241b253000)
        libmount.so.1 => /home/aznb/.linuxbrew/lib/libmount.so.1 (0x00007f241b001000)
        /home/aznb/.linuxbrew/lib/ld.so (0x00007f241ca3e000)
        libgpg-error.so.0 => /home/aznb/.linuxbrew/lib/libgpg-error.so.0 (0x00007f241aded000)
        libuuid.so.1 => /home/aznb/.linuxbrew/lib/libuuid.so.1 (0x00007f241abe8000)
```

### In case of bug report: Steps to reproduce the problem

> 
meson build \
-Drootprefix=/home/aznb/.linuxbrew/Cellar/systemd/238 \
-Drootlibdir=/home/aznb/.linuxbrew/Cellar/systemd/238/lib \
-Dsysvinit-path=/home/aznb/.linuxbrew/Cellar/systemd/238/etc/init.d \
-Dsysvrcnd-path=/home/aznb/.linuxbrew/Cellar/systemd/238/etc/rc.d \
--prefix=/home/aznb/.linuxbrew/Cellar/systemd/238 \
--libdir=/home/aznb/.linuxbrew/Cellar/systemd/238/lib \
--localstatedir=/home/aznb/.linuxbrew/var \
--sysconfdir=/home/aznb/.linuxbrew/Cellar/systemd/238/etc \
--buildtype=release \
--backend=ninja
ninja -v -j 18 -C build
ninja -v -C build install

I also tried ```export LDFLAGS="-Wl,-rpath,/home/aznb/.linuxbrew/lib"``` before meson build and it gave the same error.

Here's the stdout and stderr from the commands above:

[buildlog.txt](https://github.com/systemd/systemd/files/1805436/buildlog.txt)

**Comment by asavah** [comment]
meson does not respect user supplied rpath and "fixes" it.
https://github.com/mesonbuild/meson/issues/2567

**Comment by keszybz** [comment]
We don't really support anything except installing systemd as /usr/lib/systemd/systemd or /lib/systemd/systemd. So installing somewhere else with rpath set it outside of the scope of what we support. As @asavah said, setting custom rpaths seems to be generic issue (RFE?) with meson, so I'll close this.

**Comment by Char-Aznable** [comment]
@keszybz Is there a way to get around this issue? It seems to me that the installation was testing the binaries and failed. Can I disable the test and install the binaries and use patchelf to set the rpath afterwards?

**Comment by Char-Aznable** [comment]
Hi @filbranden, thanks for pointing this out. But what you describe has been done in my attempts to build systemd, as evidenced by the correct rpath in the binaries inside the build directory (see my post above). I think the issue was generated during ninja install where somehow the rpath was reset.

**Comment by filbranden** [comment]
@Char-Aznable 

Try commenting out this line?

https://github.com/mesonbuild/meson/blob/552916d2d24723ef579ee54b18b8bd7b25328cf8/mesonbuild/scripts/meson_install.py#L374

:-)

Hacky, but it might work for you're trying to do...

**Comment by Char-Aznable** [comment]
@filbranden Oh, I see. There's the corresponding line in systemd's meson.build: ```install_rpath : rootlibexecdir ```, which is set to /home/aznb/.linuxbrew/Cellar/systemd/238/lib/systemd. I resolve the issue by setting install_rpath to something like: /home/aznb/.linuxbrew/Cellar/systemd/238/lib/systemd:/home/aznb/.linuxbrew/lib.

**Comment by Char-Aznable** [comment]
PR #8445 submitted to resolve this issue

**Comment by YuMan-Tam** [comment]
The patch here helped me solved this issue, so I am putting a note here. And thank you for the patch.

https://bugs.archlinux.org/task/57297
