### ISSUE TITLE
`systemctl edit --force` creates drop-in for nonexistent unit

### ISSUE THREAD

**Issue by dobyrch** [systemd/systemd#8449]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v233 - v238

### Used distribution

Arch Linux

### In case of bug report: Unexpected behaviour you saw

Commit 39c38ce1 (v232) introduced the `--force` option to `systemctl edit`, which creates a new unit file if it doesn't already exist.  b3734d98 (v233) modified the behavior of `--force` so that it will only create a new unit if `--full` is also specifed; without `--full`,  `systemctl edit` will create `new_unit_name.service.d/override.conf`.

While the new behavior makes the use of `--full` more consistent, it also allows the creation of a drop-in without a corresponding unit. That could be confusing to users, especially since invoking `systemctl edit` on a new unit (without `--force`) will show:
`Run 'systemctl edit --force new_unit_name.service' to create a new unit.`

### In case of bug report: Expected behaviour you didn't see

`systemctl edit --force` should always create a new unit if it doesn't exist; if it does exist, then `--force` should have no effect and editing can continue normally.

If there is a use case for creating a drop-in without a unit, then the documentation and the hint from `systemctl edit` should be updated to mention that `--force --full` can be used to create a new unit.

### In case of bug report: Steps to reproduce the problem

```
$ systemctl edit --user foo
No files found for foo.service.
Run 'systemctl edit --user --force foo.service' to create a new unit.

$ systemctl edit --user --force foo

$ ls -d ~/.config/systemd/user/foo.service*
/home/dobyrch/.config/systemd/user/foo.service.d
```

**Comment by poettering** [comment]
There are plenty units which do not exist 1:1 as unit files on disk, and I am very sure that the user should be able to create drop-ins for those, if he specifies `--force`. Think .device units. Or .mount units generated from /etc/fstab. Or service instances. Or SysV services. And so on.

It's completely OK to have drop-ins in place without 1:1 matching unit files, hence I am pretty sure the current behaviour makes a lot of sense.

Hope that makes some sense?

**Comment by ugur1yildiz** [comment]
When I try to create new service by 
```shell
sudo systemctl edit --full --force --system ll_xx.service
```
get an error :

```shell
No files found for ll_xx.service.
```


Linux 4.14.256-197.484.amzn2.x86_64

**Comment by mrc0mmand** [comment]
> 

I suspect you're using an old version of systemd. If that's the case, please follow up with your downstream distro. If you see this error with systemd 249 or 250, please open a new issue, so it can be properly looked at.

**Comment by ugur1yildiz** [comment]
You are right mine is 219 :)
