### ISSUE TITLE
Are DNS queries correctly scoped for the interface?

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#8454]
I have anecdotal reports that DNS queries are not correctly scoped per interface, neither for v4 or v6, and specifically not for fe80 v6.

Looking at the code, I see that PKTINFO is set for v4/v6 cases in mDNS and LLMNR, but not for DNS. And neither SO_BINDTODEVICE is set.

Should dns_scope_emit_one, for DNS case, use manager_send, rather than manager_write? with correct PKTINFO supplied?

https://github.com/systemd/systemd/blob/539ad37f18543d436ef9839e6bec20319ada53a2/src/resolve/resolved-dns-scope.c#L195

**Comment by xnox** [comment]
actually, i'm not sure i can reproduce this issue. Even though i do not see bind to device / pktinfo for dns protocol.

**Comment by poettering** [comment]
Actually, DNS is not scoped on purpose, we follow the regular routing table for it, and that on purpose. After all plain DNS is in theory just a regular, global IP protocol, while LLMNR/mDNS in their multicast and link-local structure are inherently a scoped protocol.

It's a compat thing too, DNS never was scoped, hence we don't scope it either.

Of course, this only applies to the traffic we generate and accept, the configuration is still scoped.

(I figure we could add a tweak option for extra security though, that ensures we actually scope the DNS traffic too. Sounds like a useful security feature for VPNs)

**Comment by xnox** [comment]
However, should the `fe80:::%eth0` dns addresses be scoped? and specifically use similar send protocol for those DNS server, as it is done for LLMNR/mDNS? Also what about "dns leaking" should we not try to use the dns configured to interface, via that interface only, and the falllback to global routing?

**Comment by poettering** [comment]
> However, should the fe80:::%eth0 dns addresses be scoped? 

They implicitly are. IPv6 link-local addresses always have to carry the iface index in the struct sockaddr_in6, otherwise the kernel wouldn't even accept them. 

> and specifically use similar send protocol for those DNS server, as it is done for LLMNR/mDNS? Also what about "dns leaking" should we not try to use the dns configured to interface, via that interface only, and the falllback to global routing?

Yeah, one can see that as security feature, but I think it's probably something to opt-in to, as it is a change from classic DNS. Routable IP generally doesn't enforce an interface, and particularly not on incoming traffic (i.e. SO_BINDTODEVICE). If we'd turn that on by default this would probably end up being quite painful, and trigger tons of issues I think.

**Comment by xnox** [comment]
Right, I think it is reasonable to assert that "if one does not want DNS leaks, the default routes should all point inside the VPN", resolved uses default routes, thus traffic goes where the user wants it to go (even if the user is a bit confused, like me).

Thanks for these comments, I think there are no further actions for this "issue".
