### ISSUE TITLE
Bug: Systemd "missing" shutdown + kpanic

### ISSUE THREAD

**Issue by HotelBellaMuerte** [systemd/systemd#8457]
Version: 238.0-**3**
Distro: Manjaro
Kernel: Itsnt important (failed with 416-rc5, 415-9 and 414)
CPU: fx 8350 on asus m5a78
Arch: 64

**how fails**

it appears work fine, but when i turn off (by systemd)  ai got "shotdown hook not avaible" + a kernel panic + a stack trace (of the kernel searching the orphan hook)

**i need shutdown  with case button**     

PD

all appears to be ok with systemd 238.0**-2**

**Comment by sourcejedi** [comment]
Given that you are able to trace this to a difference between two downstream systemd packages, which have the same upstream version number (v238), it feels like you're going to have better luck pointing this out to the people who packaged up that downstream release :).  I.e. report the problem to Manjaro.

If possible, I suggest taking a picture of the kernel panic etc.

I don't see anywhere systemd could have logged such an error from.

Also the only case I know where we cause a kernel panic, is if PID1 exits.  The kernel should be fairly clear about this case. (it says "Attempted to kill init!" before the stack trace).  I'm not aware of the kernel mentioning anything about orphans or hooks, not for a stack trace that would be our fault.

A picture of the error could help clarify these.  It's always useful to have the exact text of the error message!  (Ideally by copy+paste / attached log file, but for kernel panics photos are commonly welcome, for reasons which I hope are obvious :)

**Comment by sourcejedi** [comment]
I've tagged this as needing more info to be on the safe side.  What I'm really hoping is you can get this reported to Manjaro, and they can identify your issue based on the difference between their `-2` and `-3` packages.  If it makes sense to you, you're welcome to close _this_ issue here & now.

**Comment by poettering** [comment]
What's the precise error message you get? Can you paste the exact lines here? or make a screenshot?

systemd does not output such an error message, this is hence most likely caused by something else.
