### ISSUE TITLE
Support tablets / volume keys in systemd-boot's boot menu

### ISSUE THREAD

**Issue by ChrisTucker2000** [systemd/systemd#8466]
### Submission type

Request for enhancement (RFE)

### systemd version the issue has been seen with

238.0-3

### Used distribution

Arch Linux.

### In case of bug report: Expected behaviour you didn't see

With a boot menu, I expect to be able to cycle through options using the Volume Up key, and activate an option using the Volume Down key - that's how my tablet's built-in boot menu works. However, systemd-boot doesn't seem to support this. Pressing one of the volume keys stops the timeout, but doesn't let me navigate the menus, leaving me completely stuck. As it is now, systemd-boot is completely unusable on a tablet except when loading into the default entry.

I would therefore like systemd-boot to support navigation via the volume keys. These are standard on both tablets and phones.

**Comment by medhefgo** [comment]
Wouldn't the standard way to do this volume keys to navigate and power key to select?

**Comment by medhefgo** [comment]
Can you use this patch to identify the keycodes for volume and power keys?
https://github.com/medhefgo/systemd/commit/41690f906cd5a6e74d6addda5a5e25f414597dbc

**Comment by poettering** [comment]
we'd be happy to support that, but withou tknowing the keycodes we can't do much

**Comment by oldherl** [comment]
Hello. I am a user of another tablet (EZpad mini 4s).
I can navigate up/down with volume keys with no problem, but can not confirm to boot on power key.
Using the above medhefgo@41690f9 patch I can recognize the key code for my power key is 0xD0000.
Adding "case 0xd0000:" works well on my tablet.
Could you please add support for it then?

**Comment by poettering** [comment]
hmm @medhefgo 's patch vanished...

is there any hint that the 0xd0000 thing is defined generically, i.e. applies to other devices, too? my google skills didn't reveal anything of relevance there...

**Comment by oldherl** [comment]
> hmm @medhefgo 's patch vanished...
> 
> is there any hint that the 0xd0000 thing is defined generically, i.e. applies to other devices, too? my google skills didn't reveal anything of relevance there...

in systemd/src/boot/efi/console.h:
`
#define KEYPRESS(keys, scan, uni) ((((UINT64)keys) << 32) | ((scan) << 16) | (uni))
`
in /usr/include/efi/efi.h:
`
#define CHAR_CARRIAGE_RETURN            0x000D
`

I believe this is how 0xd0000 comes. Or I maybe wrong.

**Comment by poettering** [comment]
@oldherl so on your device the power key is mapped to ENTER? did I get this right? But we already support that, no?

**Comment by oldherl** [comment]
@poettering No it's not the same as ENTER. Maybe it has different `uni` value.
I didn't try to print out the scan code for my ENTER.

**Comment by poettering** [comment]
hmm, what you said above suggests CARRIAGE_RETURN is the char generated, i assumed that was ENTER. or is it not?

**Comment by poettering** [comment]
(note that sd-boot already looks for both  `KEYPRESS(0, 0, CHAR_LINEFEED)` and `KEYPRESS(0, 0, CHAR_CARRIAGE_RETURN)` and considers both as menu selection keys. Hence what you are asking for should already work.

**Comment by mattpepin** [comment]
This is still not working as of today. Friendly ping ;)

**Comment by mattpepin** [comment]
Also, the Windows/Super key should also trigger the selection.

**Comment by poettering** [comment]
@pcercuei systemd-boot uses UEFI APIs, obviously, not Linux APIs. Which means the Linux driver and which key it sends doesn't really matter to it. What matters is what the uefi firmware tells systemd-boot.

**Comment by pcercuei** [comment]
Ok, I thought it was a small Linux kernel with a payload.

To support @oldherl's setup, you would need ```KEYPRESS(0, CHAR_CARRIAGE_RETURN, 0)```.
On my tablet, I would need ```KEYPRESS(0, CHAR_CARRIAGE_RETURN, CHAR_CARRIAGE_RETURN)``` (tested and working).

I think it would be possible to modify the ```KEYPRESS``` macro to do a bitwise OR of the last two parameters, to cover all of these cases. It doesn't look like it would break anything.

**Comment by keszybz** [comment]
One down, two to go ;) If someone can provide the numbers for the volume up/down keys, it should be fairly easy to include them.

**Comment by mattpepin** [comment]
I would gladly provide the ones for my tablet, but I can't find the patch mentioned above that makes systemd-boot output key codes.

**Comment by keszybz** [comment]
See https://github.com/medhefgo/systemd/commit/41690f9/

**Comment by mattpepin** [comment]
Ok, I added the patch but it doesn't work. When I use the keyboard, the key codes are printed, but the tablet buttons don't output anything. Is there something I'm missing?

**Comment by mattpepin** [comment]
Interestingly, pressing volume+/- and other media keys on a USB physical keyboard does not print anything either. Same for Windows (super) key (which my tablet also has). Regular keys print their respective keycodes.

**Comment by poettering** [comment]
OK, let's close this. We are happy to add support for other keys that make sense, but this is not actionable to us if the firmware doesn't generate keys or if we don't know which key codes those are. If you have new keys to support please report back with the precise key codes to listen for, and we can add them
