### ISSUE TITLE
systemd-sysusers doesn't properly process NIS "+:::::" entry in /etc/passwd

### ISSUE THREAD

**Issue by rudimeier** [systemd/systemd#8467]
When creating new users it does not leave NIS entries like `"+:::::"` at the end of files.
`useradd(1)` would do it correctly. IMHO it's questionable why you don't use `useradd` at all. It also locks the files to not produce garbage on concurrent writes.

See  https://bugzilla.opensuse.org/show_bug.cgi?id=1085062

**Comment by grawity** [comment]
Hmm, do you have actual [locking-related problems](https://github.com/systemd/systemd/blob/master/src/basic/user-util.c#L548) with sysusers, or just mentioning it as an aside?

**Comment by fbuihuu** [comment]
Regarding the NIS issue, I'll prepare a patch.

**Comment by fbuihuu** [comment]
here we go: https://github.com/systemd/systemd/pull/8468

**Comment by rudimeier** [comment]
@grawity
I have just check quickly. It looks like `sysusers` uses different lockfiles than shadow-utils. Thus it's not safe anymore to use all the existing  `shadow-utils` on systems where `systemd-sysusers` is used too.

**Comment by yuwata** [comment]
@rudimeier Could you create a separate issue or RFE for the concern related to the file locking? As this is closed when the PR #8468 is accepted.

**Comment by poettering** [comment]
> IMHO it's questionable why you don't use useradd at all. 

There's no generally accepted implementation of useradd around. Moreover the available implementations generally are not implemented as proper library we could link to.

Also note that glibc actually *does* expose proper APIs for writing these files, see putpwent() and friends, and we *do* make use of that.

> It also locks the files to not produce garbage on concurrent writes.

So do we. We use the same lock file glibc's lckpwdf() API call uses.

In summary, we use official glibc APIs (or equivalents) both for adding users and for locking the database files. If these APIs don't work for you please file a bug against glibc. Thanks!

**Comment by poettering** [comment]
> @grawity
> I have just checked quickly. It looks like sysusers uses different lockfiles than shadow-utils. Thus it's not safe anymore to use all the existing shadow-utils on systems where systemd-sysusers is used too.

Are you saying your shadow-utils packages uses different lock files than glibc's lckpwdf()? If so then this sounds like brokeness in shadow-utils, as lockpwdf() is actually part of glibc's shadow support, see its man page. Please work with shadow-utils and glibc upstreams to ensure they agree on the same lock files then.

**Comment by poettering** [comment]
> There's no generally accepted implementation of useradd around. Moreover the available implementations generally are not implemented as proper library we could link to.

BTW, one more thing: there are implementations of "adduser" around that support backends beyond /etc/passwd (i.e. ldap or samba or such), and we explicitly don't want that. systemd-sysusers is expressly and exclusively about system users and those are stored in /etc/passwd, hence the glibc APIs are the right API to use, and "adduser" is really not.

**Comment by rudimeier** [comment]
On Monday 19 March 2018, Lennart Poettering wrote:
> In summary, we use official glibc APIs (or equivalents) both for
> adding users and for locking the database files. If these APIs don't
> work for you please file a bug against glibc. Thanks!

These APIs work fine for me. They just don't seem to work for you. 
Thanks!

**Comment by rudimeier** [comment]
On Tuesday 20 March 2018, Lennart Poettering wrote:
> BTW, one more thing: there are implementations of "adduser" around

I was talking about "useradd" not adduser.

> that support backends beyond /etc/passwd (i.e. ldap or samba or
> such), and we explicitly don't want that. systemd-sysusers is
> expressly and exclusively about system users and those are stored in
> /etc/passwd, hence the glibc APIs are the right API to use, and
> "adduser" is really not.

Currently also systemd-sysusers does not add a local user 
to /etc/passwd, if it exist already in NIS ... So it does not even what 
*you* think it should do.

**Comment by poettering** [comment]
> These APIs work fine for me. They just don't seem to work for you. Thanks!

uh? again, we *do* use the glibc APIs, and of course they work for me. Not sure what you are saying.

**Comment by poettering** [comment]
> Currently also systemd-sysusers does not add a local user to /etc/passwd, if it exist already in NIS ... So it does not even what *you* think it should do.

uh? we only *add* entries to /etc/passwd. But we *check* also the rest of the user databases before doing this. Hence we are doing exactly what I think it should do.

**Comment by rudimeier** [comment]
On Tuesday 20 March 2018, Lennart Poettering wrote:
> uh? again, we *do* use the glibc APIs, and of course they work for
> me. Not sure what you are saying.

Err, it's your sysusers program which is broken not mine, Why are you 
merging the fix even though you find everything is correct as is?

I'm out of this stupid conversation ...

**Comment by poettering** [comment]
> Err, it's your sysusers program which is broken not mine, Why are you merging the fix even though you find everything is correct as is?

I am explaining why we use glibc's APIs instead of adduser/useradd. That's all. That's entirely independent of dealing with the NIS speciaility of "+:::::", which is fixed now.
