### ISSUE TITLE
Starting backlight:intel_backlight too long with 1.1 seconds

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8479]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> Debian Sid/unstable

### In case of bug report: Expected behaviour you didn't see

> Fast startup.

### In case of bug report: Unexpected behaviour you saw

> `systemd-backlight@backlight:intel_backlight.service` takes 1.1 seconds.

```
[…]
Mar 18 15:09:24.471151 xps139370 kernel: initcall i915_init+0x0/0x59 [i915] returned 0 after 21690 usecs
Mar 18 15:09:24.488907 xps139370 systemd[1]: Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
Mar 18 15:09:24.489664 xps139370 systemd[1]: Starting Load/Save RF Kill Switch Status...
Mar 18 15:09:24.496121 xps139370 systemd[1]: Started Load/Save RF Kill Switch Status.
Mar 18 15:09:24.496829 xps139370 systemd[1]: Started Raise network interfaces.
Mar 18 15:09:24.529578 xps139370 systemd[1]: Created slice system-systemd\x2dbacklight.slice.
Mar 18 15:09:24.530057 xps139370 systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:intel_backlight...
Mar 18 15:09:24.572565 xps139370 systemd[1]: Started Network Time Synchronization.
Mar 18 15:09:24.572661 xps139370 systemd[1]: Reached target System Time Synchronized.
Mar 18 15:09:24.575803 xps139370 systemd[1]: Starting Load/Save Screen Backlight Brightness of leds:dell::kbd_backlight...
Mar 18 15:09:24.579833 xps139370 systemd[1]: Started Load/Save Screen Backlight Brightness of leds:dell::kbd_backlight.
Mar 18 15:09:25.371743 xps139370 systemd-udevd[542]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 18 15:09:25.630875 xps139370 systemd[1]: Started Load/Save Screen Backlight Brightness of backlight:intel_backlight.
Mar 18 15:09:25.631324 xps139370 systemd[1]: Reached target System Initialization.
[…]
```

```
$ systemctl cat systemd-backlight@backlight:intel_backlight.service
# /lib/systemd/system/systemd-backlight@.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Load/Save Screen Backlight Brightness of %i
Documentation=man:systemd-backlight@.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-remount-fs.service
Before=sysinit.target shutdown.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/lib/systemd/systemd-backlight load %i
ExecStop=/lib/systemd/systemd-backlight save %i
TimeoutSec=90s
StateDirectory=systemd/backlight
$ ls -Rl /var/lib/systemd/backlight/
/var/lib/systemd/backlight/:
total 8
-rw-r--r-- 1 root root 4 Mar 18 15:09 pci-0000:00:02.0:backlight:intel_backlight
-rw-r--r-- 1 root root 2 Mar 18 15:09 platform-dell-laptop:leds:dell::kbd_backlight
pmenzel@xps139370:~$ more /var/lib/systemd/backlight/*
::::::::::::::
/var/lib/systemd/backlight/pci-0000:00:02.0:backlight:intel_backlight
::::::::::::::
375
::::::::::::::
/var/lib/systemd/backlight/platform-dell-laptop:leds:dell::kbd_backlight
::::::::::::::
0
```

### In case of bug report: Steps to reproduce the problem

> Install GNU/Linux on Dell XPS 13 9370.

**Comment by yuwata** [comment]
I do not catch what is the problem here. Taking 1.1 sec seems little bit long, but is it 'too' long for you? 
BTW, I note that my system takes 25 ms for that.
```
Mar 18 20:45:25.408695 systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:intel_backlight...
Mar 18 20:45:25.433940 systemd[1]: Started Load/Save Screen Backlight Brightness of backlight:intel_backlight.
```

**Comment by paulmenzel** [comment]
On 03/18/2018 04:24 PM, Yu Watanabe wrote:
> I do not catch what is the problem here. Taking 1.1 sec seems little bit long, but is it 'too' long for you?
> BTW, I note that my system takes 25 ms for that.
> 
> ```
> Mar 18 20:45:25.408695 systemd[1]: Starting Load/Save Screen Backlight Brightness of backlight:intel_backlight...
> Mar 18 20:45:25.433940 systemd[1]: Started Load/Save Screen Backlight Brightness of backlight:intel_backlight.
> ```

It could be a driver bug or a bug with the journal time stamps then. 
Running the command manually on a started system, it finishes after 41 ms.

```
$ time sudo /lib/systemd/systemd-backlight load "backlight:intel_backlight"

real	0m0.041s
user	0m0.010s
sys	0m0.006s
```

**Comment by mbiebl** [comment]
Or maybe just some heavy IO going on in parallel during boot

**Comment by poettering** [comment]
These kind of EC operations can be pretty slow in various drivers, and there's little we can do in userspace about that. systemd-backlight doesn't really do much, besides writing a value to the drivers, hence I see nothing we can do about this. Hence, please bring this to the attention of the driver authors, if you think there's something that needs fixing. I doubt there's anything to fix in systemd-backlight here. Closing this hence. Feel free to reopen if you have strong reason to believe there's actually something wrong with out client side that we need to fix.

**Comment by paulmenzel** [comment]
On 03/20/2018 08:28 AM, Lennart Poettering wrote:
> These kind of EC operations can be pretty slow in various drivers,
> and there's little we can do in userspace about that.

Well, as written, running it manually, it only takes very little time.

> systemd-backlight doesn't really do much, besides writing a value to
> the drivers, hence I see nothing we can do about this. Hence, please
> bring this to the attention of the driver authors, if you think
> there's something that needs fixing. I doubt there's anything to fix
> in systemd-backlight here. Closing this hence. Feel free to reopen if
> you have strong reason to believe there's actually something wrong
> with out client side that we need to fix.

I think, it would be great, if these issue were easier to debug. I still 
do not know if the journal time stamps can be trusted for example, and 
how to debug this further.

Additionally, the question is, if the service should be allowed to hold 
up the boot process, and if the target(?) shouldn’t be changed to 
something else.

**Comment by poettering** [comment]
> I think, it would be great, if these issue were easier to debug. I still do not know if the journal time stamps can be trusted for example, and how to debug this further.

they can't be. logging is asynchronous on linux, and we generate a lot of messages during early boot. Hence they are not useful for more than a rough idea. "systemctl status" on the unit itself is more useful.

> Additionally, the question is, if the service should be allowed to hold up the boot process, and if the target(?) shouldn’t be changed to something else.

That's a valid question. I guess the main reason they are ordered like this is that the display manager is generally started after sysinit, end the backlight should probably be set before.

But I figure we could also drop that ordering dep. Please submit a PR that drops it.
