### ISSUE TITLE
sysctl.d and other files are unconditionally installed to /usr/lib; our docs say this is wrong

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8481]
### Submission type

 - Bug report

### systemd version the issue has been seen with

* source code of git master (`prefixdir` v.s. `rootprefixdir` usage in `/meson.build`).
* 232-25+deb9u1

### Used distribution

Debian 9

### In case of bug report: Expected behaviour you didn't see

> systemd itself is actually completely fine with /usr on a separate file system that is not pre-mounted at boot time.

-- as per https://freedesktop.org/wiki/Software/systemd/separate-usr-is-broken/

This is public documentation, which claims that people will read it because systemd prints a warning about split `/usr` w/o pre-mounting.  (Presently I understand this exists in the form of the taint message logged at boot time).  Therefore I presume it's supposed to be kept up to date.

### In case of bug report: Unexpected behaviour you saw

systemd-sysctl.service has `DefaultDependencies=no` and no explicit dependency on `/usr`.  (Also it is pulled in by sysinit.target.  The docs for which, tell us "System services pulled in by this target should declare DefaultDependencies=no and specify all their dependencies manually, including access to anything more than a read only root filesystem.)

But `50-coredump.conf` is installed to `/usr/lib/sysctl.d/`

There are other files in /usr/lib/systemd which I am also suspicious about...

### In case of bug report: Steps to reproduce the problem

Look at a current Debian system (w/o the non-default adoption of usr merge).  You will see both `/lib/systemd` and `/usr/lib/systemd`.  The directory under `/usr` includes a non-empty `sysctl.d`.

---

Apart from sysctl, the other paths in master `/meson.build` that look suspicious to me are

* `sysusersdir = join_paths(prefixdir, 'lib/sysusers.d')` - systemd-sysusers.service
* `binfmtdir = join_paths(prefixdir, 'lib/binfmt.d')` - systemd-binfmt.service
* `modulesloaddir = join_paths(prefixdir, 'lib/modules-load.d')` - systemd-modules-load.service
* `systemenvgeneratordir = join_paths(prefixdir, 'lib/systemd/system-environment-generators')` - man systemd.environment-generator

Such paths are exported in `systemd.pc`, and in principle in rpm macros.  (Internally, I see only `sysctl.d` and `sysusers.d`).

**Comment by poettering** [comment]
I have reworded that wiki text a bit now, and it now says that "systemd is mostly OK" now only...

That said I figure we could move those files too rootprefixdir. The tools already look there, hence we might as well move the files too. Happy to take a patch for this, if anyone cares...

**Comment by fsateler** [comment]
FWIW, Debian has [officially](https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#late-mounting-usr) declared late-mounted /usr unsupported. With pretty much everyone else having already moved to merged-usr, are there any people left for whom this might be an issue?

**Comment by sourcejedi** [comment]
@fsateler possibly people like me who might not use a system, but weren't tracking that status, and became anxious when they saw the inconsistency.

Possibly there will be more such people, while Debian is slowly making the transition to a merged /usr?

I've written the thing now anyway, so there's a concrete PR #8056 we can decide y/n.  Having discovered this fact for myself half-way through, the commit description already mentioned it :).

> The problem is more that Debian is currently still carrying the /usr split.
> This makes systemd's failure to support mounting /usr quite visible...
> when you look at the installed paths, or the doctored manpages from the
> Debian systemd package.
> 
> **Given that we make this distinction *at all* between installing things to
> `prefixdir` and `rootprefixdir`**, let's make a story for readers which is
> consistent, one which doesn't look like there's a bug, without assuming
> they are up to date on the latest developments.
> 
> How we avoid breaking existing setups
> -------------------------------------
> 
> No extra migration work should be necessary.  While upstream manpages
> pretend the /usr split doesn't exist, in fact when we are built with
> split_usr=true we are looking in both /lib AND /usr/lib for config files.
> So when /usr is pre-mounted, we will read it opportunistically.
> (Also, we do so in such a way that allows a graceful migration.  It
> shouldn't matter if /lib/foo.conf and /usr/lib/foo.conf end up being two
> different aliases of the same file, because only one of them will be read).
>
> A change may be desirable in the Debian package, to include these new
directories in the sed command which doctors their man pages :).

**Comment by sourcejedi** [comment]
@fsateler  The other approach would be for systemd to stop installing it's own stuff separately to /lib and /usr/lib. Only use separate paths for _consuming_ files, installed by people who have not yet migrated to merged-usr thinking. Drop entirely the claim that systemd can support mounting /usr part-way through the boot.  Maybe it's the opportune time to do that?

**Comment by sourcejedi** [comment]
Ah, that's not a good idea, it switches from `/bin/systemctl` to `/usr/bin/systemctl` as poettering pointed out on the PR.

**Comment by mbiebl** [comment]
With my Debian maintainer hat on, I would prefer if the defaults for these directories remained as they are.

While Debian does not have a merged-usr setup yet, we do not really support later-usr mounting anymore, i.e. /usr needs either be on the same partition as / or mounted by the initramfs

https://www.debian.org/releases/stretch/i386/release-notes/ch-information.en.html#late-mounting-usr

That /lib/udev and /lib/systemd are in / has historical reasons. Some day we will eventually move them to /usr as well and I'd rather not have to move /usr/lib/tmpfiles.d to /lib and later back to /usr/lib

**Comment by poettering** [comment]
OK, given that this  move would be primarily done to make Debian-based systems a bit more systematic, and the Debian maintainer doesn't want it, let's not do this.

@sourcejedi I hope that makes sense?

Closing.

**Comment by sourcejedi** [comment]
Absolute agreement on the Debian side.  Flipside below.

I presented this as a conflict I was confused by.  At least at the point tmpfiles got pulled in to this, I agree it has started to sound like too much work.  `systemd-tmpfiles-setup-dev.service` leaves me confused :).

Or rather, I'm left confused about "systemd itself is actually _mostly_ fine with ...".  AFAICT it might currently be a fair assessment, but I think this shows no-one is trying to maintain it.  What people are maintaining is the pre-mounted /usr.  And this distinction will be maintained for some time, measured in Debian release cycles.

I had an idea I held back, to avoid distracting from the main conflict. The doc could be more cautious in how it uses the present tense.  I.e. change the two sentences to

* "systemd itself has actually been fine with /usr on a separate filesystem that is not pre-mounted"...
* "systemd has worked fine with /usr on a separate file system"...

This would bring the initial part of the doc in line, with the "we now just expect /usr to be pre-mounted" under "going forward".
