### ISSUE TITLE
systemd Caught <ABRT>, "Freezing execution", __libc_fatal("*** %n in writable segment detected ***\n") after execute asprintf(&message, "U\002%c%s%n"... in src/core/manager.c

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#8483]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v232
but this code is still unchanged in v238

### Used distribution

Debian
Downstream bug report 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883690

We have a downstream bug report where systemd apparently dies at
```
./core/manager.c:        if (asprintf(&message, "U\002%c%s%n", (int) (strlen(u->id) + 1), u->id, &n) < 0) {
```
with a
```
#6  0x00007f46b4d71c12 in __GI___libc_fatal (message=0x7f46b4e66640 "*** %n in writable segment detected ***\n")
```
It seems this can be caused if FORTIFY_SOURCE is in use, and indeed that flag is set by default in Debian (-D_FORTIFY_SOURCE=2 to be precise)
I found this reference: https://lists.gnu.org/archive/html/bug-gnulib/2007-10/msg00255.html

Any advice how this should be handled?

**Comment by evverx** [comment]
It seems that if `%n` is the last specifier, it could be removed and the return value of `asprintf` could be used instead.

By the way, I haven't been able to reproduce this with a simple program calling `asprintf` compiled with `-D_FORTIFY_SOURCE=2 ` on Fedora with `glibc-2.26-24.fc27`, so either `glibc` has been fixed or it has been patched up.

**Comment by evverx** [comment]
What is more interesting is that I couldn't trigger that crash on `Debian Stretch` either. Does anybody know if there should be anything else apart from `-D_FORTIFY_SOURCE=2` and `%n`?

**Comment by keszybz** [comment]
It's another case of overzealous prohibition of useful features. I doubt that this could stand long, since %n is fairly widely used. So I wouldn't be surprised if it got silently reverted.

> It seems that if %n is the last specifier, it could be removed and the return value of asprintf could be used instead.

If somebody prepares a patch, I'd merge it.

**Comment by evverx** [comment]
`man feature_test_macros` explicitly says that with _FORTIFY_SOURCE set to 2, some more checking is added, but some conforming programs might fail, so failures like this are kind of expected, I think. I didn't know that it is set by default in `Debian` and I'm not exactly sure why.

I suggested the use of the return value of `asprintf` because I though the issue was easily reproducible, but it turns out that `%n` and `_FORTIFY_SOURCE=2` aren't enough to trigger the crash. Even https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883690#15 seems to show that sometimes `systemd` crashes and sometimes it doesn't. I think it would be great to figure out what is happening instead of guessing that `%n` is the culprit.

**Comment by mbiebl** [comment]
I can't reproduce it myself either fwiw and as @evverx mentioned, the original bug reporter doesn't run into this on every boot.

**Comment by evverx** [comment]
It seems that the crash can be reproduced by preventing a program from reading `/proc/self/maps` properly:
```sh
$ cat TEST.c
#include <stdio.h>
#include <stdlib.h>
#include <sys/mount.h>

int main(int argc, char *argv[]) {
        char *s;
        int n;
        if (mount("/dev/null", "/proc/self/maps", NULL, MS_BIND, NULL) < 0)
                return 1;
        if (asprintf(&s, "%n", &n) < 0)
                return 1;
        printf("%s\n", s);
        free(s);
}

$ gcc -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -g -O1 ./TEST.c

$ sudo ./a.out
*** %n in writable segment detected ***
Aborted
```
I don't think the code should be changed at least until the original bug reporter clarify why `/proc/self` was semi-functional.

**Comment by keszybz** [comment]
I get the same result for TEST.c with gcc-8.0.1-0.19.fc28.x86_64.
"Not our bug" :)
