### ISSUE TITLE
ShutdownWatchdogSec does not work as described

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#8484]
### Submission type

 - Bug report

### systemd version the issue has been seen with
230

> …

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see

Hi
I am observing that  ShutdownWatchdogSec   setting in  system.conf

In man page, for ShutdownWatchdogSec    , I see :
" It works as a safety net to ensure that the reboot takes place even if a clean reboot attempt times out. "
I am not clear what is meant by 'clean reboot' and 'times out ' here

For testing, I have set it to 5 sec

++++++++++++++++++++++++++++++
root@re1:~# grep ShutdownWatchdogSec /etc/systemd/system.conf
ShutdownWatchdogSec=5sec
root@re1:~#
++++++++++++++++++++++++++++++

and I have my.service , which on stop will sleep for few minutes

++++++++++++++++++++++++++++++
# cat /etc/systemd/system/my.service
[Unit]
Description="my"

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/true
ExecStopPost=/bin/sleep 3000
Restart=no

[Install]
WantedBy=multi-user.target
++++++++++++++++++++++++++++++

But I dont see hardware watchdog being kicked in.
Is this a bug in ShutdownWatchdogSec ? if not am I missing any config ?

I did some research and found below links which talk about effect of  ShutdownWatchdogSec .

https://utcc.utoronto.ca/~cks/space/blog/linux/SystemdNFSMountShutdown
https://utcc.utoronto.ca/~cks/space/blog/linux/SystemdShutdownWatchdog

as described in above pages, one option seem to be to lower value of   JobTimeoutSec in reboot.target but that solution is still about software watchdog and not about hardware watchdog.

My requirement is to put upper bound time limit of reboot, and once upper limit is reached, i want to kick in hardware watchdog

Could you please let me know how do I achieve this ?

Thanks

> …

### In case of bug report: Unexpected behaviour you saw
ShutdownWatchdogSec does not work as described
> …

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
This is a bug and feature request tracker. If you have questions about systemd please contact the systemd mailing list instead. Thank you.

**Comment by cdprashanth** [comment]
Thanks
This looks to be  a doc bug where d=man pages/docs need update
Thanks
