### ISSUE TITLE
hardware watchdog timeout value getting overwritten when reboot-force happens

### ISSUE THREAD

**Issue by cdprashanth** [systemd/systemd#8485]
### Submission type

 - Bug report

### systemd version the issue has been seen with
230

> …

### Used distribution

> …

### In case of bug report: Expected behaviour you didn't see
I see another issue also wrt hardware watchdog
reboot-force seem to be overwriting the hardware watchdog timeout value.

I have changed  reboot.target to make JobTimeoutSec=5sec
when system boots up i see that hardware watchdog is set to 1 min 4 sec.
but when 'systemctl reboot' timesout , reboot-force is invoked and that is overwriting the 
hardware watchdog timeout value to 4 min.
Is this a bug or I am missing some config?

Thanks

$ grep -i hardware  /var/tmp/j12_systemctl_reboot_jobtimeout5sec_1

Mar 18 23:42:11 re1 systemd[1]: Hardware watchdog 'iTCO_wdt', version 0
Mar 18 23:42:11 re1 systemd[1]: Set hardware watchdog to 1min 4s.
Mar 18 23:42:32 re1 systemd[1]: Set hardware watchdog to 4min.

+++++++

root@bng-evo-ptx5k-c-re1:~$ cat   /lib/systemd/system/reboot.target

[Unit]
Description=Reboot
Documentation=man:systemd.special(7)
DefaultDependencies=no
Requires=systemd-reboot.service
After=systemd-reboot.service
AllowIsolate=yes
#JobTimeoutSec=30min
JobTimeoutSec=5sec
JobTimeoutAction=reboot-force

[Install]
Alias=ctrl-alt-del.target

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
When "reboot-force" is triggered we'll set the kernel watchdog to whatever is configured in ShutdownWatchdogSec= in /etc/systemd/system.conf. Not all watchdog hardware accepts all timeouts though. ShutdownWatchdogSec= defaults to 10min, but most likely your hw doesn't allow such long timeouts, which is possibly why you are seeing it set to 4min which is likely the closest supported value.

**Comment by boucman** [comment]
is there an easy command line tool to know what the hardware watchdog is capable of ? does the kernel know/export that information ?

**Comment by poettering** [comment]
util-linux has "wdctl". but it can't tell you what the supported timeout range is, because the kernel doesn't expose that.
