### ISSUE TITLE
localectl doesn’t rewrite keymap files when config doesn’t change, even if files were deleted in the meantime

### ISSUE THREAD

**Issue by ariasuni** [systemd/systemd#8491]
### Submission type

 - Bug report

### systemd version the issue has been seen with

238

### Used distribution

Arch Linux

### Actual behaviour

If `localectl set-x11-keymap` or `localectl set-keymap` is called two times with the same arguments and that `/etc/X11/xorg.conf.d/00-keyboard.conf` or `/etc/vconsole.conf` is deleted between the two calls, the files are not recreated by localed, leaving the system without keymap configuration.

### Steps to reproduce the problem

```
❯ localectl set-x11-keymap fr
❯ cat /etc/X11/xorg.conf.d/00-keyboard.conf 
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "fr"
EndSection
❯ cat /etc/vconsole.conf 
KEYMAP=fr
❯ rm /etc/X11/xorg.conf.d/00-keyboard.conf
❯ rm /etc/vconsole.conf
❯ localectl set-x11-keymap fr
❯ env LANG=C cat /etc/X11/xorg.conf.d/00-keyboard.conf 
cat: /etc/X11/xorg.conf.d/00-keyboard.conf: No such file or directory
```

The `set-keymap` command has the same problem.

**Comment by yuwata** [comment]
Fix is waiting in #9115.
