### ISSUE TITLE
systemd-ask-password echos password as asterisk (*) chars while decrypting LUKS partition

### ISSUE THREAD

**Issue by rootkea** [systemd/systemd#8495]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 232

### Used distribution

Debian

### In case of bug report: Expected behaviour you didn't see

`systemd-ask-password` should echo nothing by default.

### In case of bug report: Unexpected behaviour you saw

Password gets echoed to screen as asterisk (`*`) characters. Echoing asterisk characters on screen is not at all consistent behavior with the traditional *Nix password handling. Here is the screenshot [0].

### In case of bug report: Steps to reproduce the problem

I have encrypted swap and /home. When the system starts it asks password to
decrypt swap. The password doesn't get echoed at all. Totally expected
behavior.

But then it loads the kernel and `systemd` takes over. And `systemd-ask-password`
(I think as `plymouth` is not installed) asks the password to decrypt /home. And
this time password gets echoed to screen as asterisk (`*`) characters.

[0] https://imgur.com/bC4AF6H

**Comment by poettering** [comment]
press TAB to turn off echoing. Or press "backspace" as first key, which works too.

**Comment by rootkea** [comment]
@poettering Thanks! I know about TAB and BACKSPACE use to turn off the password echo.

The question is shouldn't the echo be turned off by default? i.e. may be use TAB and BACKSPACE to turn *on* the echo. But by default let's keep it off.

This makes the UI consistent with all other password handling in *nix systems e.g. `sudo` etc.

**Comment by poettering** [comment]
> This makes the UI consistent with all other password handling in *nix systems e.g. sudo etc.

well, but giving feedback makes it consistent with password handling almost anywhere else...

Note that boot-time password prompts are a special case: they are often interleaved with other boot-time logging output, hence giving immediate feedback is a good thing, to show that something is happening...

**Comment by rootkea** [comment]
> well, but giving feedback makes it consistent with password handling almost anywhere else...

Yes, you are right. But giving feedback while handling password is a GUI thing.

Almost all (actually, I am unaware of one which doesn't beside `ask-password`) of the CLI tools e.g. `login`, `cryptsetup`, `sudo` etc. have the convention to echo nothing while handling passwords.

> giving immediate feedback is a good thing, to show that something is happening...

Yes, it is. But may be not for the CLI tool handling password. But if desired as a "feature", a key (e.g. TAB) can be configured to turn on the feedback.

I rest my case. ;)

**Comment by poettering** [comment]
> Yes, you are right. But giving feedback while handling password is a GUI thing.

UI is UI. Good UI is good UI. Regardless if console or not. 

Quite frankly I am pretty sure most console tools give no feedback because it requires more work to do, not because it was really a good idea.

**Comment by ilf** [comment]
I second this proposal. By default, console password prompts should not give feedback. A user option to enable that is perfectly fine.

**Comment by kirbyfan64** [comment]
Can you really determine much from password length though? A 15 character length password would take at least a thousand years to crack, and a good 10 character password would take around half a dozen years. If your password's secure, knowing the length won't help too much.

**Comment by ilf** [comment]
@kirbyfan64 Your argument works the other way around, too: If an attacker can obvserve that an entered and accepted password is only a handful of characters, it can be a serious incentive to brute-force it.

But even with 15 or 20 characters: Revealing the exact amount of characters drastically reduces the number of potential combinations.

**Comment by thorsummoner** [comment]
for googlers landing here, sudo's password feedback is toggled with the setting "pwfeedback", https://superuser.com/questions/1404382/disable-feedback-when-typing-password-at-a-sudo-prompt

**Comment by rootkea** [comment]
> I would like to know how to disable password feedback on luks prompt as well

Currently, it seems that there is no way to achieve that permanently. Though you can turn off the echo temporarily each time you enter password on luks prompt by pressing `TAB` or `BACKSPACE`

It would have been great if the default behavior would have been to NOT echo or if the user could permanently set their choice by, say, editing a conf file.

**Comment by suddenlyfleck** [comment]
Neither `TAB` nor `BACKSPACE` works for me using
`Linux XXXX 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

I agree with rookea: It would be great if the default behavior would be to not echo asterisks.

**Comment by keszybz** [comment]
Nowadays if allow people to look over your shoulder when entering a password, then you lost already: a serious attacker can covertly record your hands and keyboard and use machine-learning-enhanced algorithms to recover the password. Determining the password *length* would be even easier, that would be possible even from a sound  recording without direct visibility. So protecting just the display of the length of password on screen doesn't make a big difference.

The current default is a reasonable tradeoff between easy of use and security. But we'd accept a patch to make this configurable if somebody wants to invest their time into this.

**Comment by rootkea** [comment]
> Determining the password _length_ would be even easier, that would be possible even from a sound recording without direct visibility. So protecting just the display of the length of password on screen doesn't make a big difference.

Is "determining the password length from sound recording" more easier than determining the password length by just looking at the display (assuming utility prints `*`s like systemd-ask-password)? It's like saying since "a serious attacker can covertly record your hands and keyboard and use machine-learning-enhanced algorithms to recover the password" why bother having password at all.

Not printing `*`s on terminal is not some unusual, forceful thing to seek. Not printing anything while entering password is a convention followed by nearly each and every command-line utility. Printing `*`s while entering password, OTOH is unusual and forceful.

The unusual thing can be user-configured (if user wants) and shouldn't be default IMHO. So, I strongly feel that `systemd-ask-password` shouldn't print anything by default while entering password but if user wants feedback then it can print *s after accepting `backspace`.

That being said, I'm okay if systemd-ask-password decides to stick with this unusual behavior but at least give user the freedom to configure it. Maybe something like "password-feedback-policy=sane" for no feedback on terminal?

> But we'd accept a patch to make this configurable if somebody wants to invest their time into this.

Glad to hear that. Since you are ready to accept the patch for this issue, can you please open this issue so that the devs can see and submit the patch for the same?

Thanks!

**Comment by suddenlyfleck** [comment]
Short remarks coming to my mind:

1 - In public spaces, there are often cameras. 
2 - visual cues are in some cases easier to obtain than auditory cues. (I.e. I imagine that imaging through a window is easier than sound recording through a window).
3 - auditory attacks require a quite atmosphere. 
4 - Correction of the input with backspace keypresses need to be accounted for in auditory attacks.

I realize that the length of the password shown on the display is not terribly bad and a typical attack scenario will aim for the password itself (not it's length only), but it is a step in the direction of bad things. 
One example, where I can imagine that knowing the exact length of the password could significantly reduce password entropy (but I don't know - just a speculation):

In case of using diceware like passwords (passwords based on wordlists), password entropy can be reduced by neglecting all combinations (and permutations) of words that don't have the known length.

**Comment by keszybz** [comment]
I opened a PR to print "(press TAB for no echo)" at the prompt now.

**Comment by ailie** [comment]
**Systemd reveals the exact password length** to nearby potential-attackers. By default. Wow !...

Your average password is weak anyways, please don't make a BF attack trivial to perform, Systemd :`|

Here's a genius idea: **do not show any feedback while entering passwords**, or at least provide a CL argument for it. You'll gain loads of karma security-wise, and linux-compatibility points. Having to (remember to) press TAB or BkSp all the time people are around is simply a bad joke...

Please reopen this issue ! Systemd v243 is still broken and bleeding...

**Comment by pedro-nonfree** [comment]
For debian 10 I solved the issue removing plymouth to avoid showing the asterisks (no tab or backspace worked, because it was managed by another program), let me put here to help people looking the solution in web searchers: `apt remove plymouth plymouth-label libplymouth4` (or not installing them)

I also took a look on `man systemd-ask-password` and I am surprised to see options such as `--echo` or `--output`, but no option to start in *no echo* mode.

**Comment by bjmgeek** [comment]
I'd like to see an option to show the asterisks.  I'm typing in a 45 character passphrase (so now you all know my passphrase length, good luck), so I'd like some feedback if I type a character twice, or miss one.  I'd be fine with it having no feedback by default, as long as there was a way to configure it.

**Comment by keszybz** [comment]
Anyone who cares about this deeply can submit a PR at any time... Apparently the current default (with the option to disable output by pressing TAB) is good enough for most people.
