### ISSUE TITLE
Cross-compiling produces hundreds of "__NR_statx not defined for your architecture" warnings.

### ISSUE THREAD

**Issue by aduskett** [systemd/systemd#8501]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> master

### Used distribution

> buildroot master

### In case of bug report: Expected behavior you didn't see

> Several hundred __NR_statx warnings

### In case of bug report: Unexpected behaviour you saw

> When cross-compiling against v238 or master, hundreds of warnings "__NR_statx not defined for your architecture" are generated. This is attributed to src/basic/missing_syscall.h line 417.

### In case of bug report: Steps to reproduce the problem

> Download buildroot from www.buildroot.org
> Download the sample defconfig from https://pastebin.com/E54FLg0p
> Place the defconfig in configs/systemd_defconfig
> Type "make systemd_defconfig"
> Remove the file "package/systemd/systemd.hash"
> Run "make systemd"

**Comment by poettering** [comment]
Please supply the missing __NR_statx definitions for your arch as a patch to missing_syscall.h as a PR. It's a matter of looking up the right syscall numbers in the kernel for your arch and adding them to our tree, that's all.

**Comment by poettering** [comment]
#8872 added a couple of more archs for this. Let's close this hence
