### ISSUE TITLE
systemd-bootchart: Document what vertical dashed line in SVG means

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8502]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238

### Used distribution

> Debian Sid/unstable

### In case of bug report: Expected behaviour you didn't see

> An explanation, what the vertical dashed line in the SVG means.

### In case of bug report: Unexpected behaviour you saw

> No explanation.

### In case of bug report: Steps to reproduce the problem

> Start system with `init=/lib/systemd/systemd-bootchart`.

**Comment by poettering** [comment]
Please file this against https://github.com/systemd/systemd-bootchart, thanks!

**Comment by paulmenzel** [comment]
On 03/20/18 16:20, Lennart Poettering wrote:
> Please file this against
> https://github.com/systemd/systemd-bootchart, thanks!

[Done.](https://github.com/systemd/systemd-bootchart/issues/39)
