### ISSUE TITLE
systemd-nspawn creates a /var/lib/machines/ subvolume in a container

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#853]
https://www.youtube.com/watch?v=D2IvmJORD2s&feature=youtu.be

I find it a little alarming to see `systemd-nspawn` creating subvolumes without warning which can be annoying since they can be difficult to delete manually. Why does it need a subvolume on `/var/lib/machines` ? IIUC that's only needed if the container is going to host ANOTHER container which is a little bizarre, no?

**Comment by richardmaw-codethink** [comment]
It's not necessarily bizarre, you could be using nspawn at the top level to virtualize one machine as many, VM-style, and in one of those you could be running application servers which have more stripped-down containers.

**Comment by poettering** [comment]
We try to keep the differences between containers and hosts at a minimum, and want to allow that one can migrate freely between the too,

You may create /var/lib/machine as a dir in advance if you like, in which case tmpfiles will not make it a subvol.

In general: subvols are fully recursive, and we make use of that. machined itself can be used to neatly remove recursive subvols, There's also work going on to add the same logic to the btrfs tools themselves.

I am pretty sure that we should not special case containers here, sorry.
