### ISSUE TITLE
hacking commands miss root login instructions

### ISSUE THREAD

**Issue by pabigot** [systemd/systemd#8538]
docs/HACKING specifies a series of command that include:

        $ sudo mkosi                           # build a test image
        $ sudo systemd-nspawn -bi image.raw    # boot up the test image

Following them presents the developer with a login prompt for an image that, as best I can tell, has no root password.  Having never seen systemd-nspawn before it took some searching to figure out how to set one; the options I've found are:
* put a root password in `mkosi.rootpw`
* `systemd-nspawn -i image.raw passwd`

How is this normally done?  I'd like to get a patch in so this is documented.

**Comment by poettering** [comment]
I do it with "echo foo > mkosi.rootpw", as it makes it much easier when running this multiple times. hence that's probably what we should document.

**Comment by poettering** [comment]
patch that adds that of course very welcome!
