### ISSUE TITLE
Modifiable default of Read-Write, Read-Only or Inaccessible directories

### ISSUE THREAD

**Issue by Jonny007-MKD** [systemd/systemd#854]
Hello,
I really like the idea of using file system namespaces to limit the access to certain directories for specific services.

As far as I understand it the current default is that everything is read-writeable (not regarding user permissions here) and that I can expilicitly make certain directories read-only or inaccessible. As the Read-Only option for one folder overwrites the Read-Write option for a subfolder, the Read-Write option is quite useless, isn't it?

In my opinion it would be better (at least for certain services) to make everything inaccessible except some directories which are then stated in the Read-Only or Read-Write options.

```
InaccessibleDirectories=/
ReadOnlyDirectories=/usr/bin /etc
ReadWriteDirectories=/var/log
```

This method follows the way of thinking when ocnfiguring iptables: block everything and only open some specific ports.

**Comment by richardmaw-codethink** [comment]
It's not that the default is to have everything read-writable, it's that the default is to leave things as they are in the host mount namespace.

So ReadWriteDirectories _is_ useful to make something that is normally read-only, writable to a specific service.

One example would be `/usr` being read-only by default, but a system update service could have `ReadWriteDirectories=/usr` to do a package update, and set `ReadOnlyDirectories=/usr/local` so it doesn't accidentally replace things it shouldn't.

**Comment by richardmaw-codethink** [comment]
I think you could do what you currently want with a blacklist, excepting that you can't use something that is inside an `InaccessibleDirectories=` entry, so you need to make everything else in the directory inaccessible.

```
InaccessibleDirectories=/boot /dev /home /lib /lib64 /media /mnt /opt /proc /root /run /sbin /srv /sys /tmp /usr/include /usr/info /usr/lib /usr/lib64 /usr/libexec /usr/local /usr/man /usr/sbin /usr/share  /usr/src /var/cache /var/db /var/lib /var/lock /var/run /var/spool /var/tmp
ReadOnlyDirectories=/usr/bin /etc
ReadWriteDirectories=/var/log
```

Note that your executable would have to be self-hosted in a layout like this, since you don't have access to `/usr/lib`, and you don't have a `/tmp`.

**Comment by poettering** [comment]
Actually, a setting for a dir does _not_ override the setting for a child dir of it. The reason why ReadWriteDirectories= exists is to allow marking /foo read-only while keeping /foo/bar writable. Are you saying this doesn't work that way for you?

(note that InaccessibelDirectories= cannot be overriden for child dirs, only ReadOnlyDirectroies= can)

**Comment by Jonny007-MKD** [comment]
Ok, I think I got it.
Although I would like to have some "non-greedy" InaccessibleDir which would allow me making a single child directory accessible (so I do not have to specify all other child dirs) I  understand that this is not the way how namespaces work.
I think I will make / ReadOnly and then overwrite this setting for specific dirs.
Thank you for your help and work :)
