### ISSUE TITLE
systemd-setup-tmpfiles startup error when /srv is on read-only fs

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#8566]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v233
v238

### Used distribution

Debian sid
Downstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868159

When / is placed on read-only fs and therefore /srv is read-only during startup
the following error occures:
localhost systemd-tmpfiles[570]: Unable to fix SELinux security
context of /srv: Read-only file system
I tried remounting / rw and executing 'restorecon /srv' but it didn't help -
systemd wants to change the context during startup anyway.
As this is not really an error and does not affect system functionality in any
way this should not be treated as error but as a warning.

**Comment by mbiebl** [comment]
I can reproduce the error, by mounting a partition at /srv readonly:
```
# findmnt /srv 
TARGET SOURCE     FSTYPE OPTIONS
/srv   /dev/sda11 ext4   ro,relatime,data=ordered
```
Then running ```/bin/systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev``` yields
```
chmod() of /srv via /proc/self/fd/3 failed: Read-only file system
# echo $?
1
```

**Comment by poettering** [comment]
A fix is wating in #8583, ptal. Note that it will suppress label change errors only if the label is already correctly in place. If it isn't we'll generate errors as before on EROFS.

Given my limited Selinux/SMACK expertise, and inability to test this thoroughly it would be greatly appreciated if #8583 could be tested

**Comment by poettering** [comment]
> chmod() of /srv via /proc/self/fd/3 failed: Read-only file system

So what you tried trips up on a diffrerent place as the original bug report: in your case the UNIX access mode of /srv doesn't appear to match what tmpfiles lists, which triggers your issue. in the other case selinux appears to be enabled and that relabelling causes the issue. I think the selinux issue is something to fix, but in your case there's a problem which can't be fixed and you get an error about that, which I think is a good thing, and nothing to fix...

**Comment by poettering** [comment]
(note that the chmod()ing logic in tmpfiles will not complain if the access mode already matches what it wants to set. In fact we won't even call chmod() at all in that case...)

**Comment by mbiebl** [comment]
@poettering when trying to reproduce the error I used a directory mount which had the permission 0775. So your guess was spot on. I don't use selinux myself, so I wasn't able to reproduce the exact same setup as the original bug reporter.
