### ISSUE TITLE
Timer do not work correctly.

### ISSUE THREAD

**Issue by Spacewalker2** [systemd/systemd#8568]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v237

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

I try to set a timer ( try OnCalendar=21..23:0,15,30,45 and OnCalendar=21..23:0/15 and even OnCalendar=21:0,15,30,45) that executes every 15 minutes from 21:00 to 23:45 a script but only at 21:00 the script executes. After after this systemctl list-timers shows n/a for the next execution. The next day maybe after a reboot it executes the script at 21:00 again but nothing more.

**Comment by poettering** [comment]
Note that .timer units won't trigger again until the unit to trigger is stopped again. 

Please provide a minimal .timer and .service unit in full that trigger the problem.

**Comment by Spacewalker2** [comment]
Chaning RemainAfterExit from yes to no does the trick. Sorry was my fault.
