### ISSUE TITLE
/dev/disk/by-id showing 'weird" behavior with nvme devices

### ISSUE THREAD

**Issue by rrosatti** [systemd/systemd#8570]
When creating new nvme namespaces, I'm seeing the following behavior in /dev/disk/by-id/:

```
# ls -l /dev/disk/by-id/ | grep nvm
lrwxrwxrwx. 1 root root 13 Mar 24 13:38 nvme-eui.0b03009880cf0400 -> ../../nvme0n1
lrwxrwxrwx. 1 root root 13 Mar 24 13:38 nvme-eui.0b030098a0cf0400 -> ../../nvme0n2
lrwxrwxrwx. 1 root root 13 Mar 24 13:38 nvme-XP400HE30002_ZEM000NX -> ../../nvme0n2
```

What I think it's weird, is the fact that there are two sym links to /nvme0n2. If I create a new namespace, then this last sym link will be pointing to /nvme0n3. 

Is this the correct behavior?

FYI, I'm using systemd version 219 on RHEL 7.4.

Thanks in advance!!

**Comment by poettering** [comment]
Sorry, but we only track issues with the two most current systemd upstream versions here on github, i.e. 237 and 238. Please contact your downstream distribution for issues with older systemd versions. The maintainers will then escalate these issues back to us if there's an issue that applies to current upstream. The submission form should actually have made that very clear.

Thank you for understanding, closing.
