### ISSUE TITLE
systemctl disable does not really disable certain services until after a reboot

### ISSUE THREAD

**Issue by mgrant0** [systemd/systemd#8572]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd version 238-2

### Used distribution

debian-testing

### In case of bug report: Expected behaviour you didn't see

Upon `systemctl restart openvpn`, I expected only the remaining enabled openvpn service to start.  (see below)

### In case of bug report: Unexpected behaviour you saw

BOTH openvpn services started: the enabled one and the disabled one.

### In case of bug report: Steps to reproduce the problem

I created a second config file for openvpn in `/etc/openvpn/server-tcp.conf`.
I enabled it with 

```
systemctl enable openvpn@server-tcp.service
```
I then decided I did not want this service so I stopped and disabled it with

```
systemctl stop openvpn@server-tcp.service
systemctl disable openvpn@server-tcp.service
```

Then I restarted openvpn with `systemctl restart openvpn`, and both the enabled and disabled services started.

It appears that systemd stores these services inside the kernel somewhere.  After a reboot, the disabled service did not restart.

I should not have to reboot the server to disable this service.

**Comment by mbiebl** [comment]
This seems to be a downstream issue. The debian OpenVPN package uses a generator /lib/systemd/system-generators/openvpn-generator, which depending on your configuration, binds all openvpn@ instances to the openvpn.service. Please check your /etc/default/openvpn.

In any case, this is not an upstream issue, so I'm closing this bug report. If you think the openvpn package does not work as you expect, please raise this downstream.
