### ISSUE TITLE
bootctl: set oneshot boot

### ISSUE THREAD

**Issue by lucasdemarchi** [systemd/systemd#8574]
### Submission type

 - Request for enhancement (RFE)

### RFE

systemd-boot currently reads a LoaderEntryOneshot efi variable in order to allow trying booting once to an entry. However there's no way to set it via bootctl or any other systemd-provided command. One can use efivar to set it, but I think a bootctl verb like "bootnext" (borrowing the same verb from efibootmgr) would be best.

**Comment by poettering** [comment]
Yeah, sounds useful

**Comment by poettering** [comment]
Also see #5739 which asks for something very similar

**Comment by poettering** [comment]
This has been implemented as part of #9437. Closing.
