### ISSUE TITLE
Ctrl+c not working within systemd-nspawn with ubuntu 17.04 and upward

### ISSUE THREAD

**Issue by hdorio** [systemd/systemd#8577]
### Submission type

 - Bug report

### systemd version the issue has been seen with

```
~ $ sudo systemd-nspawn --version
systemd 237
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN default-hierarchy=legacy
```

### Used distribution

```
~ $ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.3.0
VERSION_ID=1688.3.0
BUILD_ID=2018-03-09-0448
PRETTY_NAME="Container Linux by CoreOS 1688.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

~ $ uname -a
Linux localhost 4.14.24-coreos #1 SMP Fri Mar 9 04:21:53 UTC 2018 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux
```

### In case of bug report: Expected behaviour you didn't see

> within systemd-nspawn when I press `Ctrl+c`  the current command should be killed

### In case of bug report: Unexpected behaviour you saw

> within systemd-nspawn when I press `Ctrl+c` no `^C` is printed in bash and current command is not killed

#### Steps in Container Linux
```
cat > .toolboxrc
TOOLBOX_DOCKER_IMAGE=ubuntu
TOOLBOX_DOCKER_TAG=17.10
TOOLBOX_USER=root
```
`toolbox`
> then try pressing `Ctrl+c`

#### Steps for ubuntu and systemd 235
`debootstrap --arch amd64 artful ubuntu1710`
`sudo systemd-nspawn --directory="ubuntu1710/"  /bin/bash`
> then try pressing `Ctrl+c`

**Comment by poettering** [comment]
> debootstrap --arch amd64 artful ubuntu1710
> sudo systemd-nspawn --directory="ubuntu1710/" /bin/bash

bash doesn't abort on C-c, that's by design. It never has, and I am pretty sure it shouldn't. 

What are you trying to say?

**Comment by hdorio** [comment]
bash should print `^C` ignore the current line and return to a new prompt

[youtube demo](https://www.youtube.com/watch?v=qzbgV5uttp4)

**Comment by filbranden** [comment]
I can reproduce your issue. The problem is that you're not getting a tty inside systemd-nspawn:

```
myuser@coreos1688 ~ $ toolbox 
Spawning container myuser-ubuntu-17.10 on /var/lib/toolbox/myuser-ubuntu-17.10.
Press ^] three times within 1s to kill container.
-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell
mesg: ttyname failed: No such device
root@coreos1688:~# tty
not a tty
```

But using no .toolboxrc (which pulls in Fedora 27) works just fine...

Not sure what is the problem with Ubuntu 17.10 inside the container... Looking.

**Comment by filbranden** [comment]
Stracing startup on Ubuntu:

```
$ toolbox strace -tt -s 1024 -e openat /bin/bash
...
18:29:12.571419 openat(AT_FDCWD, "/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[No check for /dev/console or anything.]
...
```

Stracing the same on Fedora:

```
$ toolbox strace -tt -s 1024 -e openat /bin/bash
...
18:31:01.470061 openat(AT_FDCWD, "/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
18:31:01.471312 openat(AT_FDCWD, "/dev/console", O_RDWR|O_NONBLOCK) = 3
...
```

So it seems Fedora is falling back to /dev/console if it can't open /dev/tty and Ubuntu isn't...

**Comment by filbranden** [comment]
I don't know if this is responsible for all the problem, but it seems to be at least related:

```
root@ubuntu1710:/# ls -l /proc/$$/fd/
total 0
lrwx------ 1 root root 64 Mar 26 21:58 0 -> /1
lrwx------ 1 root root 64 Mar 26 21:58 1 -> /1
lrwx------ 1 root root 64 Mar 26 21:58 2 -> /1
lrwx------ 1 root root 64 Mar 26 21:58 255 -> /1
```

The same actually happens on Fedora, but for some reason Fedora tools seem to be able to fallback to using /dev/console which works...

**Comment by filbranden** [comment]
So it seems this is the glibc bug:
https://sourceware.org/bugzilla/show_bug.cgi?id=22145

And I believe it was fixed by this commit:
https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=a09dfc19edcbac3f96d5410529b724db0a583879

The Fedora 27 version... Either includes a backport for that fix, or was cut before the commit that seems to have introduced this problem...

So I guess this needs to be fixed in Ubuntu?

Cheers!
Filipe

**Comment by hdorio** [comment]
@filbranden you're absolutely right on 18.04 upgrading libc6 from 2.26 to 2.27 fixed the issue `apt install libc6 libc-bin`

thank you very much

**Comment by poettering** [comment]
Hmm, i wonder if it wouldn't be nicer if we allocated /dev/console as a pty within the container instead of mounting it from the outside. I have the suspicion this would be nicer and it wouldn't have triggered this issue in the first place...

**Comment by filbranden** [comment]
> Hmm, i wonder if it wouldn't be nicer if we allocated /dev/console as a pty within the container instead of mounting it from the outside. I have the suspicion this would be nicer and it wouldn't have triggered this issue in the first place...

+1. I'd be happy to work on a patch for that, but I need some pointers... I do have a reproducer, so in a way I can tell when I'm done :smiley:

**Comment by martinpitt** [comment]
FTR, this sounds very similar to #8704 - logging into a container doesn't get a logind session because of an `ENXIO` on /dev/tty.

**Comment by filbranden** [comment]
I wish I had time to work on @poettering's suggestion:

> Hmm, i wonder if it wouldn't be nicer if we allocated /dev/console as a pty within the container instead of mounting it from the outside. I have the suspicion this would be nicer and it wouldn't have triggered this issue in the first place...

If I had some pointers (where change is needed, hints of what needs to be done, etc.) I'm happy to write a patch and test it. As I mentioned before, I do have a reproducer for it... Cheers!
