### ISSUE TITLE
Does not recognize serial consoles as part of a seat

### ISSUE THREAD

**Issue by fastcat** [systemd/systemd#8582]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 232, confirmed "problem" code present in master

### Used distribution

> Debian, originally reported as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892302

### In case of bug report: Expected behaviour you didn't see

> I expect to be able to log in on a serial console on a headless system (no local video display whatsoever) and have my session recognized as a "seat", and have things that depend on that, such as common policy kit rules, work.

### In case of bug report: Unexpected behaviour you saw

> Serial consoles are never treated as a seat, and thus can never be active, which, among other things, prevents common policy kit rules from working as expected.

### In case of bug report: Steps to reproduce the problem

> Configure a getty on ttyS0.  Log in on it as non-root.  Try to use something which requires a local seat, such as `systemd-inhibit --what=shutdown --mode=block`, observe that the request is denied.

The problem seems to be down to the logic in `get_seat_from_display` in `pam_systemd.c` -- https://github.com/systemd/systemd/blob/2df46112052ee9752ce2d2920ad6184b304c77ed/src/login/pam_systemd.c#L129
That code only recognizes local video terminals as seats, it has no provision for a means to recognize serial consoles as local seats.  It's understandable why serial consoles might not want to be treated as local seats automatically, but at the same time it seems a bug that there is no way to configure them as such.

**Comment by poettering** [comment]
Well, serial and ssh sessions are not considered local, and hence have no local hardware associated with them. The "seat" concept is about managing local hardware, nothing else, and hence it doesn't apply to ssh/serial sessions at all, and really should not. And only on local hardware we can track foreground and background sessions, hence only for those active/inactive really makes sense to track.

PolicyKit should be fine dealing with "seat-less" sessions really, as that is a very common case, given that ssh is managed that way. 

Anyway, closing this, as conceptually I am very sure logind should do the right thing, and your PK rules/PK itself need to make sure they can deal with seat-less (i.e. "virtual") sessions just fine.

I hope that makes sense.

**Comment by fastcat** [comment]
I'm not talking about "my" PK rules, I'm talking about "your" PK rules -- many of the rules shipped with systemd don't work on headless systems because they are all about having a seat.

Really, I'm disputing this statement:
> Well, serial and ssh sessions are not considered local, and hence have no local hardware associated with them.

In some cases, sure, they may not be local, but in other cases they very much can be.  For my case the serial console is every bit as local as a console connected via HDMI.  It just happens to have a _much_ lower bitrate connection between the computer and the display, and the keyboard muxed into that 'display' connection.

**Comment by poettering** [comment]
> I'm not talking about "my" PK rules, I'm talking about "your" PK rules -- many of the rules shipped with systemd don't work on headless systems because they are all about having a seat.

example?

**Comment by fastcat** [comment]
The rules that govern systemd-inhibit are how I found this -- many of the modes require a seat (active or otherwise) to permit a non-root user to invoke.

`dpkg -L systemd | grep -i policy | xargs fgrep --line-number -e '<allow_' -e '<action ' | grep -B1 -A2 'allow_any.no'` suggests that the following actions require a seat directly:

1. org.freedesktop.login1.inhibit-block-shutdown
2. org.freedesktop.login1.inhibit-block-sleep
3. org.freedesktop.login1.inhibit-handle-power-key
4. org.freedesktop.login1.inhibit-handle-suspend-key
5. org.freedesktop.login1.inhibit-handle-hibernate-key
6. org.freedesktop.login1.inhibit-handle-lid-switch
7. org.freedesktop.systemd1.reply-password

I would suggest that the various "key" ones and the lid switch are probably not a concern for a headless unit with only a serial console since it is very unlikely to have any of those keys or a lid switch.  But the block shutdown, block sleep, and reply password seem quite relevant to me.
