### ISSUE TITLE
Unit not triggering 'stop' - despite StopWhenUnneeded=true

### ISSUE THREAD

**Issue by craigphicks** [systemd/systemd#8588]
### Submission type
 - Bug report

### systemd version the issue has been seen with
```
% systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

```
### Used distribution

> _Ubuntu 16.04 LTS_

### In case of bug report: Expected behaviour you didn't see

> Unit doesn't trigger stop despite using 
```
[Unit]
StopWhenUnneeded=true

```
and not being needed.

### In case of bug report: Unexpected behaviour you saw

Service doesn't call stop:

```
# journalctl -u local-iptables-rs
....
-- Reboot --
Mar 27 01:06:51 izu systemd[1]: Starting local-iptables-rs configuration...
Mar 27 01:06:51 izu local-iptables-rs.sh[2007]: Warning: skipping no rules to loadfile /etc/iptables/rules.v4
Mar 27 01:06:51 izu local-iptables-rs.sh[2007]: Warning: skipping no rules to loadfile /etc/iptables/rules.v6
Mar 27 01:06:51 izu local-iptables-rs.sh[2007]: Success: /usr/local/sbin/local-iptables-rs.sh start
Mar 27 01:06:51 izu systemd[1]: Started local-iptables-rs configuration.
-- Reboot --
.....

```

### In case of bug report: Steps to reproduce the problem

local-iptables-rs.service:

```
[Unit]
Description=local-iptables-rs configuration
DefaultDependencies=no
Before=network.target ufw.service local-iptables-rc.service
Wants=systemd-modules-load.service local-fs.target
After=systemd-modules-load.service local-fs.target
StopWhenUnneeded=true

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/local-iptables-rs.sh start
ExecStop=/usr/local/sbin/local-iptables-rs.sh stop

[Install]
WantedBy=ufw.service
WantedBy=multi-user.target
```

Incidentally, there is another unit which works fine, calling both start and stop:

local-iptables-mgr.service:

```
[Unit]
Description=iptables-local-mgr Service
Documentation=
After=network.target local-iptables-rs.service fail2ban.service iptables.service firewalld.service
Before=network-online.target
Wants=local-iptables-rs.service fail2ban.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/local-iptables-mgr.sh start
ExecStop=/usr/local/sbin/local-iptables-mgr.sh stop

[Install]
WantedBy=multi-user.target

```

which runs with this log:

```
# journalctl -u local-iptables-mgr
....
-- Reboot --
Mar 27 01:06:54 izu systemd[1]: Starting iptables-local-mgr Service...
Mar 27 01:06:54 izu local-iptables-mgr.sh[3544]: Success: /usr/local/sbin/local-iptables-mgr.sh
Mar 27 01:06:54 izu systemd[1]: Started iptables-local-mgr Service.
Mar 27 01:08:38 izu systemd[1]: Stopping iptables-local-mgr Service...
Mar 27 01:08:38 izu local-iptables-mgr.sh[3890]: Success: /usr/local/sbin/local-iptables-mgr.sh
Mar 27 01:08:38 izu systemd[1]: Stopped iptables-local-mgr Service.
-- Reboot --
...
```

The only mitigating circumstance I can think of is that the service 

`ufw.service
`

does not specify a stop, and local-iptables-rs.service specifies 
```
[Install]
WantedBy=ufw.service

```
so maybe _local-iptables-rs.service_ is waiting for _ufw.service_ to finish stopping but that never happens? 

For [reference:](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StopWhenUnneeded=)

> StopWhenUnneeded=
> 
>     Takes a boolean argument. If true, this unit will be stopped when it is no longer used. Note that, in order to minimize the work to be executed, systemd will not stop units by default unless they are conflicting with other units, or the user explicitly requested their shut down. If this option is set, a unit will be automatically cleaned up if no other active unit requires it. Defaults to false.

**Comment by poettering** [comment]
Let's close this due to lack of response.
