### ISSUE TITLE
systemd-analyze verify spews wrong error when attempting to remove generator files in /tmp

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#8592]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237-4 (debian), 238 (self-compiled)

### Used distribution

> debian

### In case of bug report: Expected behaviour you didn't see

> systemd-analyze verify default.target should report valid verification errors

### In case of bug report: Unexpected behaviour you saw

> systemd-analyze verify default.target should report valid verification errors but also adds the following line

Attempted to remove disk file system, and we can't allow that.

### In case of bug report: Steps to reproduce the problem

> systemd-analyze verify default.target

After digging a bit in the systemd codebase, this seems due to the manager cleanup code.

systemd-analyze creates adirectory named /tmp/systemd-temporary-XXXX. /tmp is a real, physical directory on my machine

when rm_rf_children is called, for manager cleanup, it has a safety that prevents it from removing physical files unless explicitely told to do so.

I didn't fix myself because the manager init/cleanup code confuses me and I am not sure where to act...

**Comment by matthiasdoering** [comment]
Will we receive an update for Ubuntu 18.04?
I want to use that, but my systems are up-to-date and it do not work today.

**Comment by yuwata** [comment]
The fix is included in v239. Please use v239 or newer.

**Comment by matthiasdoering** [comment]
Yeah, I understand it and could this this in the message above.
Ubuntu 18.04 use systemd v237. 
You will not backport this patch to one of the most used Distros with long-term support?

**Comment by scottschreckengaust** [comment]
https://bugs.launchpad.net/ubuntu-manpage-repository/+bug/1817627

**Comment by kirkins** [comment]
I'm wanting to add this simple service, but I keep getting the error with analyze and it fails to start when I try. Any work around? Also on Ubuntu 18.04.

```
[Unit]
Description=Unison

[Service]
Environment="PATH=/usr/bin/local"
ExecStart=/usr/local/bin/unison bidirsync
#%i
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
```

**Comment by keszybz** [comment]
@kirkins this is not a support forum.

**Comment by boucman** [comment]
/usr/bin/local vs /usr/local/bin in PATH ?

**Comment by kirkins** [comment]
@boucman thanks, it was a mistake. Sorry for posting here @keszybz
