### ISSUE TITLE
Cannot login after boot from hibernation

### ISSUE THREAD

**Issue by qwfy** [systemd/systemd#8597]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemctl --version
systemd 238
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> After boot from hibernation, I expect to see the login screen

### In case of bug report: Unexpected behaviour you saw

> When booted from hibernation, I saw a black screen, with words like "session is broken, unlock is impossible, please loginctl unlock-session c2", after I ctrl + alt + f2 and invoke the loginctl command, the screen would unlock, but window manager has crashed (window border is gone, KDE), so a reboot is still needed.

### In case of bug report: Steps to reproduce the problem

> This often happens if the system is constantly in high load, full cpu, full gpu, full memory, full swap.  At the end of the day, the load would go normal, i.e. barely no load, but the swap some time is still heavy occupied, If I do a hibernation now, the next day, there is a good chance that I would see the above described black screen.

I Googled a bit, there is a thread says this is related of /tmp being full, seems similar.

Is there a log file I can see/attach? journalctl --unit logind gives no error information.

There is GPU hang error in journalctl, I'm not sure this is related:

> Mar 28 07:15:53  kernel: [drm] GPU HANG: ecode 9:0:0xf5613086, in doc-browser [5910], reason: Hang on rcs0, action: reset
Mar 28 07:15:53  kernel: [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Mar 28 07:15:53  kernel: [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
Mar 28 07:15:53  kernel: [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
Mar 28 07:15:53  kernel: [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
Mar 28 07:15:53  kernel: [drm] GPU crash dump saved to /sys/class/drm/card1/error
Mar 28 07:15:53  kernel: i915 0000:00:02.0: Resetting rcs0 after gpu hang
Mar 28 07:15:55  kernel: [drm:gen8_reset_engines [i915]] *ERROR* rcs0: reset request timeout
Mar 28 07:15:55  kernel: i915 0000:00:02.0: Resetting chip after gpu hang
Mar 28 07:15:56  kernel: [drm:gen8_reset_engines [i915]] *ERROR* rcs0: reset request timeout
Mar 28 07:15:56  kernel: [drm:i915_reset [i915]] *ERROR* Failed to reset chip: -5

/sys/class/drm/card1/error is not there after the reboot, I didn't check before the reboot.

**Comment by poettering** [comment]
This very much looks like a kernel issue, something in the hibernation implemenation between the kernel and your graphics driver. Please work with the kernel and downstream folks first, before escalating this to us, as there's nothing actually pointing to a systemd issue in the above.

or to say this differently: before we can investigate a systemd issue, the driver/kernel situation must be in order, as they are the foundation of anything we do.

Thank you for understanding.
