### ISSUE TITLE
systemd-timesyncd executes timesyncs when creating and destroying a Docker container

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#8603]
### Submission type

 - Bug report

I could not find a bugreport here to continue this one https://github.com/coreos/bugs/issues/1707
### systemd version the issue has been seen with

> systemd-238-2-omv2015.0.x86_64

### Used distribution

> OpenMandriva LX and CoreOS

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> each time a docker starts or stops a systemd-timesyncd is restarted

Mar 28 14:03:50 abf.openmandriva.org dockerd[5098]: time="2018-03-28T14:03:50.353923158Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 28 14:03:50 abf.openmandriva.org kernel: veth2de3015: renamed from eth0
Mar 28 14:03:50 abf.openmandriva.org systemd-networkd[1283]: vethbbc1789: Lost carrier
Mar 28 14:03:50 abf.openmandriva.org kernel: docker0: port 16(vethbbc1789) entered disabled state
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Network configuration changed, trying to establish connection.
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Synchronized to time server 91.224.149.41:123 (2.openmandriva.pool.ntp.org).
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Network configuration changed, trying to establish connection.
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Synchronized to time server 91.224.149.41:123 (2.openmandriva.pool.ntp.org).
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Network configuration changed, trying to establish connection.
Mar 28 14:03:50 abf.openmandriva.org kernel: docker0: port 16(vethbbc1789) entered disabled state
Mar 28 14:03:50 abf.openmandriva.org kernel: device vethbbc1789 left promiscuous mode
Mar 28 14:03:50 abf.openmandriva.org kernel: docker0: port 16(vethbbc1789) entered disabled state
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Synchronized to time server 91.224.149.41:123 (2.openmandriva.pool.ntp.org).

### In case of bug report: Steps to reproduce the problem

> …

**Comment by yuwata** [comment]
I've tried to fix this in #8611, but I am not sure it is a right way to fix this. But anyway, I think connecting to a NTP server on every network event is not a good idea.

**Comment by fredbeltrao** [comment]
I'm facing the problem when docker interfaces change.
```
$ systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
[syslog](https://pastebin.com/8DfdeCT3)

**Comment by stefanlasiewski** [comment]
Ubuntu 18.04.5 still ships with systemd v237 and is unlikely to get a newer version. Thus, all Ubuntu 18.04 nodes that run containers will run into this. Can anyone provide a workaround to prevent this situation?

**Comment by tpgxyz** [comment]
@stefanlasiewski Here are possible things you may do:
1. File a bug report for your distribution, so they can update or patch systemd
2. Stop using *buntu in favour of any modern linux distribution that does keep track on systemd
