### ISSUE TITLE
238 - nspawn fails wih veth/macvlan network setup 'File exists'

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#8614]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> Nspawn machine failed to start

### In case of bug report: Unexpected behaviour you saw

> This machine worked fine with 236, but using 238 systemd-nspawn fails, saying:
> `Failed to add new veth interfaces (vb-xxx:host0): File exists`
> 
> After switching from veth to macvlan (without the bridge), I get:
> `Failed to add new macvlan interfaces: Device or resource busy`

### In case of bug report: Steps to reproduce the problem

> Setup where veth interface is connected to a bridge
> 
> ```
> # cat /etc/systemd/nspawn/machine.nspawn 
> [Network]
> Bridge=br-dev
> ```
> 
> Althought my machine-names are shorter than 10 chars, might this be related to #7918 ?

**Comment by qmega** [comment]
I think this is the same as #8599.

**Comment by SjonHortensius** [comment]
Agreed, not sure why I didn't find that.
