### ISSUE TITLE
[RFE] ConditionFileContains or more flexible conditions

### ISSUE THREAD

**Issue by FedericoCeratto** [systemd/systemd#8625]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238

### Requested behaviour

Component: systemd.unit

It's often required to conditionally run a service based on the contents of a configuration file, e.g. the presence of a configuration parameter, or the absence of some sort of "NOT_CONFIGURED_YET" flag.

Sometimes a handful of shell commands are required to parse the configuration file, ignore comments, or check more complex conditions.

Ideally ConditionExec="<commands>" could be introduced. If the command returns an error code the condition is not valid.

Alternatively, ConditionFileContains could check for a string or a regexp in a file.

Thanks

**Comment by boucman** [comment]
I had looked at ConditionExec, more for the case of "run this service only if a given server is reachable" (online backups)

Problem is that Condition* are logically attached to services and adding a ConditionExec would pull in a lot of things (everything needed to run a command, which is quite a lot, and is not part of standard units)

So I moved to implementing a form of ExecStartPre=?<command> syntax that would work like an exact start way, but if the command returns a non-zero code, the unit would be skiped (but not failed)

This way, a timer could retrigger the unit on a regular basis but not do anything if the Pre=? fails without registring that as a failure.

that code is far from ready at this point, though... so I'm mainly posting that so you can follow my train of thoughts...

**Comment by filbranden** [comment]
One pitfall of skipping on non-zero is that if anything goes wrong with the script/program (such as killed by OOM killer, etc.) then you may end up silently skipping a service when that wasn't expected.

**Comment by boucman** [comment]
that would be killed by signal, not return with non-zero error code... anyway, that's not a full blown code yet, just an idea...

**Comment by sbarthelemy** [comment]
systemd 243 (released 2019-09-03) introduced ExecCondition for service units. It seems to fit the OP needs.

**Comment by anitazha** [comment]
Closing as `ExecCondition=` does seem to fit the bill here. Please (re)open the issue if it doesn't.
