### ISSUE TITLE
documentation - systemd.network - IPv6Token= - note behavior with DHCPv6 managed address

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#863]
man 5 systemd.network says only:
IPv6Token=
           An IPv6 address with the top 64 bits unset. When set, indicates the 64 bits interface part of SLAAC IPv6 addresses for this link. By default it is autogenerated.

There should be an additional comment, that when the Managed Address Configuration Flag is set in the router advertisement, and a DHCPv6 server assigns an address to this interface, then the requested IPv6Token will be ignored.

**Comment by keszybz** [comment]
Fixed by eb142d8ec11b4d0dbda882c18da7c859a5919459.
