### ISSUE TITLE
services shouldn't start if there is residual processes left over (in SendSIGKILL=no case)

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#8630]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemctl  --version
systemd 237
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

### Used distribution

Fedora rawhide (in Docker)

### In case of bug report: Expected behaviour you didn't see

A service in Active: deactivating (final-sigterm) (Result: timeout) should not be allowed to restart if PID(s) still exist in the control group.

```
Mar 31 07:48:31 6adbfc4b13bc systemd[1]: Started sleep.service.
Mar 31 07:48:57 6adbfc4b13bc systemd[1]: Stopping sleep.service...
Mar 31 07:50:27 6adbfc4b13bc systemd[1]: sleep.service: State 'stop-sigterm' timed out. Skipping SIGKILL.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: sleep.service: State 'stop-final-sigterm' timed out. Skipping SIGKILL. Entering failed mode.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: sleep.service: Failed with result 'timeout'.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: Stopped sleep.service.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: sleep.service: Found left-over process 122 (sleep) in control group while starting unit. Ignoring.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar 31 07:51:57 6adbfc4b13bc systemd[1]: Started sleep.service.
```

I expected not to see "Ignoring" and to see that as an error.

### In case of bug report: Unexpected behaviour you saw

Restarting the service created a second instance of the process in the same service
```
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: disabled)
   Active: active (running) since Sat 2018-03-31 07:51:57 UTC; 4s ago
 Main PID: 204 (sleep)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           ├─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
           └─204 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
```

### In case of bug report: Steps to reproduce the problem

```
[Service]
ExecStart=/bin/nohup /bin/sleep 3600
KillSignal=HUP
SendSIGKILL=no
```

```
[root@6adbfc4b13bc /]# systemctl start  sleep
[root@6adbfc4b13bc /]# systemctl status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: dis
abled)
   Active: active (running) since Sat 2018-03-31 07:48:31 UTC; 15s ag
o
 Main PID: 122 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           └─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
[root@6adbfc4b13bc /]# systemctl restart  sleep
```

Second window during restart - 1m30s timeout occurred as expected
```
[root@6adbfc4b13bc /]# systemctl  status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: dis
abled)
   Active: deactivating (stop-sigterm) since Sat 2018-03-31 07:48:57 UTC; 1min 2
3s ago
 Main PID: 122 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           └─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600

Mar 31 07:48:31 6adbfc4b13bc systemd[1]: Started sleep.service.
Mar 31 07:48:57 6adbfc4b13bc systemd[1]: Stopping sleep.service...
[root@6adbfc4b13bc /]# systemctl  status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: dis
abled)
   Active: deactivating (final-sigterm) (Result: timeout) since Sat 2018-03-31 0
7:48:57 UTC; 1min 32s ago
 Main PID: 122 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           └─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600

Mar 31 07:48:31 6adbfc4b13bc systemd[1]: Started sleep.service.
Mar 31 07:48:57 6adbfc4b13bc systemd[1]: Stopping sleep.service...
Mar 31 07:50:27 6adbfc4b13bc systemd[1]: sleep.service: 
State 'stop-sigterm' timed out. Skipping SIGKILL.
```

```
[root@6adbfc4b13bc /]# systemctl status sleep
● sleep.service
   Loaded: loaded (/etc/systemd/system/sleep.service; static; vendor preset: disabled)
   Active: active (running) since Sat 2018-03-31 07:51:57 UTC; 4s ago
 Main PID: 204 (sleep)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/docker.service/system.slice/sleep.service
           ├─122 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
           └─204 /usr/bin/coreutils --coreutils-prog-shebang=sleep /bin/sleep 3600
```

While a sleep service can run quite well with two instances the running of multiple database service instances on top of each other creates complicated process mess and relies on internal mechanisms to prevent corruption. Ideally the starting of the service shouldn't be allowed while a residual process is still around. It should be the admin's responsibility to take actions (SIGKILL if necessary) to restore the service to a stopped state before systemd is willing to restart the service.

**Comment by boucman** [comment]
hmm, that's interesting... I can see cases (non-database, obviously) where the service MUST be restarted, and having processes around is ok... So we probably need a way to specify that. 

moreover, in the embedded world there is no admin to take action.

**Comment by grooverdan** [comment]
Good points, lets look at some use cases some more. Forking services like sshd (uses `KillMode=process`) and apache(some modes - `KillMode=mixed`) are good examples where the mainpid gets killed however processes remain perfectly reasonably around to serve existing sessions

Looking at other database service files, https://www.postgresql.org/docs/devel/static/server-start.html (1/2 way down page), seems to be relying on `TimeoutSec=0` to avoid this case. The mariadb case, https://github.com/MariaDB/server/blob/10.3/support-files/mariadb.service.in#L90 is where I originally saw this.

As I understand it, the presence of `SendSIGKILL=no` is one of two ways residual processes would remain (the other being some `KillMode={process|none}`).

The `SendSIGKILL=no` is a good indicator that you want the main process to shutdown cleanly or not at all (plymouth-start, dlm).   `SendSIGKILL=no` "shutdown cleanly" implication would indicate that you don't want a second instance operating on the same resources that the slow original is trying to cleanup.

Other `SendSIGKill=no` cases I've found referencing specific products - SAP (https://answers.sap.com/questions/68268/systemd-configuration-for-startingstopping-sap.html), llvm2 discussion (https://bugs.archlinux.org/task/50420)

Is there a case where `SendSIGKill=no` is used in a way where having other processes around is ok?

If the change in behaviour can occur for just the `SendSIGKill=no` case without negatively impacting anyone (most cases seem to be data protection or no restart) that would be great, however if another option is need that's ok too.

**Comment by grooverdan** [comment]
More real-world status:
<pre>
● mariadb0@0.service - MariaDB @VERSION@ database server (multi-instance)
   Loaded: loaded (/etc/systemd/system/mariadb0@.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb0@.service.d
           └─multi.conf
   Active: activating (start-pre) since Mon 2018-04-02 18:26:37 CDT; 27s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
 Main PID: 111391; Control PID: 148699 (mysql_install_d)
    Tasks: 87
   CGroup: /system.slice/system-mariadb0.slice/mariadb0@0.service
           ├─111391 /usr/sbin/mysqld --datadir=/var/lib/mysql/node0/0 --socket=/var/run/mysqld/mysqld-n0-0.sock
           └─control
             ├─148699 /bin/sh /usr/bin/mysql_install_db --datadir=/var/lib/mysql/node0/0 --socket=/var/run/mysqld/mysqld-n0-0.sock --user=mysql
             ├─148719 /bin/sh /usr/bin/mysql_install_db --datadir=/var/lib/mysql/node0/0 --socket=/var/run/mysqld/mysqld-n0-0.sock --user=mysql
             └─148721 /usr/sbin/mysqld --lc-messages=en_US --bootstrap --silent-startup --basedir=/usr --datadir=/var/lib/mysql/node0/0 --log-warnings=0 --enforce-storage-engine= --socket=/var/run/mysqld/mysqld-n

Apr 02 18:26:37 zaiuslp5 systemd[1]: mariadb0@0.service: Failed with result 'timeout'.
Apr 02 18:26:37 zaiuslp5 systemd[1]: Starting MariaDB @VERSION@ database server (multi-instance)...
Apr 02 18:26:38 zaiuslp5 mysql_install_db[148699]: Installing MariaDB/MySQL system tables in '/var/lib/mysql/node0/0' ...
Apr 02 18:26:38 zaiuslp5 numactl[111391]: 2018-04-02 18:26:38 0 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
Apr 02 18:26:39 zaiuslp5 mysql_install_db[148699]: 2018-04-02 18:26:39 0 [ERROR] RocksDB: Error opening instance, Status Code: 5, Status: IO error: While lock file: ./#rocksdb/LOCK: Resource temporarily unavailab
Apr 02 18:26:39 zaiuslp5 mysql_install_db[148699]: 2018-04-02 18:26:39 0 [ERROR] Plugin 'ROCKSDB' init function returned error.
Apr 02 18:26:39 zaiuslp5 mysql_install_db[148699]: 2018-04-02 18:26:39 0 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
Apr 02 18:26:39 zaiuslp5 mysql_install_db[148699]: 2018-04-02 18:26:39 0 [ERROR] mysqld: Can't lock aria control file '/var/lib/mysql/node0/0/aria_log_control' for exclusive use, error: 11. Will retry for 30 seco
</pre>

<pre>
$ systemctl  cat mariadb0@0.service | egrep -v '^(#|$)'
# /etc/systemd/system/mariadb0@.service
[Unit]
Description=MariaDB @VERSION@ database server (multi-instance)
Documentation=man:mysqld(8)
Documentation=https://mariadb.com/kb/en/library/systemd/
After=network.target
After=syslog.target
[Install]
WantedBy=multi-user.target
Alias=mysql.service
Alias=mysqld.service
[Service]
Type=notify
PrivateNetwork=false
User=mysql
Group=mysql
CapabilityBoundingSet=CAP_IPC_LOCK
ProtectSystem=full
PrivateDevices=true
ProtectHome=true
ExecStartPre=/usr/bin/mysql_install_db $MYSQLD_MULTI_INSTANCE --user=mysql
ExecStart=/usr/bin/numactl --cpunodebind=0 --preferred=0 /usr/sbin/mysqld $MYSQLD_MULTI_INSTANCE
KillSignal=SIGTERM
SendSIGKILL=no
Restart=on-abort
RestartSec=5s
UMask=007
PrivateTmp=false
Environment=MYSQLD_MULTI_INSTANCE=--defaults-group-suffix=.%I
LimitNOFILE=16364
# /etc/systemd/system/mariadb0@.service.d/multi.conf
[Service]
CapabilityBoundingSet=CAP_IPC_LOCK
LimitMEMLOCK=infinity
Environment=MYSQLD_MULTI_INSTANCE="--datadir=/var/lib/mysql/node0/%I --socket=/var/run/mysqld/mysqld-n0-%I.sock"
</pre>

**Comment by poettering** [comment]
While I sympathize with the request, I am not sure we can change this now, this smells like something that'd trip up a ton of people...

Maybe we can add an option for this, though?

**Comment by grooverdan** [comment]
me from previous:
> however if another option is need that's ok too.

**Comment by grooverdan** [comment]
I still haven't though of cases where ```SendSIGKILL=no``` was used and the presence of  ```Exec*``` from difference service starts was the desired behaviour.

What would another option look like? ```ExclusiveService={bool}```?  ```PreventResidualStart={main|child|none}```?  ```StartBareCgroup={bool}```?

**Comment by poettering** [comment]
Hmm, OK, revisiting this, maybe we can get away if we do this check only if SendSIGKILL=yes is set and KillMode= is one of "cgroup" or "mixed"... I guess you are right, this might be sufficiently conditionalized then that this won't create too much incompat issues.

Hmm, so yupp, what about this: we do as you suggest, leave out the new opt-in bool I originally proposed for now, and instead implement a check like this:

If `SendSIGKILL=yes` is set and "KillMode=" is "cgroup" or "mixed" and we detect left-over processes when starting a unit, we'll do a LOG_ERR and refuse starting it. If these conditions do not hold, then we'll still log about it but at LOG_WARN and proceed?

I think that would make sense, right? and cover what you are interested in?

**Comment by grooverdan** [comment]
Thanks for the reconsideration. It would however be:

If ```SendSIGKIll=no``` is set and "KillMode=" is "cgroup" or "mixed" ......(as previous)

This would cover what I'm interested in.

A ```SendSIGKill=yes`` and ```KillMode in (cgroup, mixed)``` should never result in residual processes as far as I can tell.
