### ISSUE TITLE
Sokets and RuntimeDir with correct owner and mode

### ISSUE THREAD

**Issue by arthur-s** [systemd/systemd#8635]
I have an issue with sockets and RuntimeDir. 
veronica.socket:
```
[Socket]
ListenStream=/run/uwsgi/veronica.sock
SocketUser=arthur
SocketGroup=admins
SocketMode=0660

[Install]
WantedBy=sockets.target
```

veronica.service:
```
[Service]
PermissionsStartOnly=True
User=arthur
Group=admins
RuntimeDirectory=uwsgi
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=always
ExecStart=some-command
Restart=always
KillSignal=SIGQUIT
Type=notify
StandardError=syslog
NotifyAccess=all

[Install]
WantedBy=multi-user.target
```
Now, after reloading `systemctl daemon-reload`, I start socket:
```
# systemctl start veronica.socket
# ls -al /run/uwsgi
drwxr-xr-x.  2 root    root   60 апр  1 07:20 .
drwxr-xr-x. 26 root    root  740 апр  1 07:20 ..
srw-rw----.  1 arthur admins   0 апр  1 07:20 veronica.sock
```
note, that RuntimeDir was created with owner root:root
and start service:
```
# systemctl start veronica.service
(it fails).
# ls -al /run/uwsgi                     
drwxr-xr-x.  2 arthur admins  60 апр  1 07:22 .
drwxr-xr-x. 26 root    root  740 апр  1 07:22 ..
-rw-r--r--.  1 arthur admins   6 апр  1 07:22 veronica.pid
```

You can see, that when I started service, RuntimeDir was deleted and created with owner arthur:admins.
I expect, that when I create socket, RuntimeDir must be created with owner and mode, taken from `veronica.service`, and then when I start service, runtime dir must contain veronica.socket and veronica.pid files

**Comment by arthur-s** [comment]
Sorry guys, problem was solved by using another dir for socket:
[Socket]
ListenStream=/run/uwsgi-sockets/veronica.sock

and for service:
[Service]
RuntimeDirectory=uwsgi

Now it works. Issue can be closed I think.

**Comment by fsateler** [comment]
Yeah, the `RuntimeDirectory` lifetime is tied to the service, so you shouldn't use it for things that could predate or outlive the service.

I'll close the issue now.

**Comment by flokli** [comment]
I just ran into this as well, opened https://github.com/systemd/systemd/pull/32503 so hopefully less people will run into it in the future.
