### ISSUE TITLE
Unprivileged systemd container when possible

### ISSUE THREAD

**Issue by antoinetran** [systemd/systemd#8657]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with
> systemd-219-42.el7_4.7.x86_64

### Used distribution

> CentOS Linux release 7.4.1708 (Core)

### Description
This is about improving the systemd experience in a docker container. As specified in #1224 , we need SYS_ADMIN for systemd various need in mount. However, I believe there are many systemd Unit (eg rabbitmq, rundeckd, etc.) that does not require such a mount feature (PrivateMnt etc.). What if for systemd containers that launches Unit not requiring mount, we let them without privilege nor SYS_ADMIN? This is the docker philosophy to provide the minimum of privilege possible as needed. My proposition is, in case of container (systemd already have code to detect such a case), we bypass some Mount detection (see below in code) that causes the issue. If systemd really encounter a Unit that need a mount, it would just crash and this is expected if we don't provide SYS_ADMIN.

###Expected behaviour you didn't see

> Launching /sbin/init works:
```
sudo docker run --cap-add SYS_ADMIN -v /sys/fs/cgroup:/sys/fs/cgroup:ro   --tmpfs /var --tmpfs /run  -ti -e container=docker --rm centos:7 /sbin/init
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +K
MOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to CentOS Linux 7 (Core)!

Set hostname to <94b22574be17>.
Initializing machine ID from random generator.
[  OK  ] Created slice Root Slice.
[  OK  ] Reached target Encrypted Volumes.
[  OK  ] Listening on Journal Socket.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Reached target Swap.
[  OK  ] Created slice System Slice.
         Starting Journal Service...
         Mounting Huge Pages File System...
         Mounting FUSE Control File System...
[  OK  ] Reached target Paths.
         Starting Rebuild Hardware Database...
         Starting Load/Save Random Seed...
[  OK  ] Created slice system-getty.slice.
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Reached target Slices.
[  OK  ] Reached target Local File Systems (Pre).
[  OK  ] Reached target Local File Systems.
         Starting Commit a transient machine-id on disk...
         Starting Rebuild Journal Catalog...
```

### Unexpected behaviour you saw

>  sudo docker run  -v /sys/fs/cgroup:/sys/fs/cgroup:ro   --tmpfs /var --tmpfs /run  -ti -e container=docker --rm centos:7 /sbin/init
"[!!!!!!] Failed to mount API filesystems, freezing."

### Analyze

> I did some strace and this is my analyse:
Without SYS_ADMIN:
name_to_handle_at(AT_FDCWD, "/sys", {handle_bytes=128}, 0x7ffeae9040c0, AT_SYMLINK_FOLLOW) = -1 EPERM (Operation not permitted)
name_to_handle_at(AT_FDCWD, "/dev", {handle_bytes=128}, 0x7ffeae9040c0, AT_SYMLINK_FOLLOW) = -1 EPERM (Operation not permitted)
access("/sys/fs/smackfs/", F_OK)        = -1 ENOENT (No such file or directory)
name_to_handle_at(AT_FDCWD, "/dev/shm", {handle_bytes=128}, 0x7ffeae9040c0, AT_SYMLINK_FOLLOW) = -1 EPERM (Operation not permitted)
name_to_handle_at(AT_FDCWD, "/run", {handle_bytes=128}, 0x7ffeae9040c0, AT_SYMLINK_FOLLOW) = -1 EPERM (Operation not permitted)
name_to_handle_at(AT_FDCWD, "/sys/fs/cgroup/systemd", {handle_bytes=128}, 0x7ffeae9040c0, AT_SYMLINK_FOLLOW) = -1 EPERM (Operation not permitted)
name_to_handle_at(AT_FDCWD, "/sys/fs/pstore", {handle_bytes=128}, 0x7ffeae9040c0, AT_SYMLINK_FOLLOW) = -1 ENOSYS (Function not implemented)
access("/sys/firmware/efi", F_OK)       = -1 ENOSYS (Function not implemented)
open("/dev/console", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOSYS (Function not implemented)
ioctl(4, TCGETS, 0x7ffeae904060)        = -1 ENOSYS (Function not implemented)
ioctl(4, TIOCGWINSZ, 0x7ffeae904100)    = -1 ENOSYS (Function not implemented)
writev(4, [{"[", 1}, {"\33[1;31m!!!!!!\33[0m", 17}, {"] ", 2}, {"Failed to mount API filesystems,"..., 42}, {"\n", 1}], 5) = -1 ENOSYS (Function not implemented)

> With SYS_ADMIN:
name_to_handle_at(AT_FDCWD, "/sys", {handle_bytes=128}, 0x7ffc15b88c00, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)
name_to_handle_at(AT_FDCWD, "/", {handle_bytes=128}, 0x7ffc15b88c04, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)
stat("/sys", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/", {st_mode=S_IFDIR|0755, st_size=18, ...}) = 0
name_to_handle_at(AT_FDCWD, "/proc", {handle_bytes=128}, 0x7ffc15b88c00, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)
name_to_handle_at(AT_FDCWD, "/", {handle_bytes=128}, 0x7ffc15b88c04, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)
stat("/proc", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/", {st_mode=S_IFDIR|0755, st_size=18, ...}) = 0
name_to_handle_at(AT_FDCWD, "/dev", {handle_bytes=128 => 12, handle_type=1, f_handle=0x3e96c45a159b410700000000}, [1183], AT_SYMLINK_FOLLOW) = 0
name_to_handle_at(AT_FDCWD, "/", {handle_bytes=128}, 0x7ffc15b88c04, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)
name_to_handle_at(AT_FDCWD, "/sys/kernel/security", {handle_bytes=128}, 0x7ffc15b88c00, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)
name_to_handle_at(AT_FDCWD, "/sys/kernel", {handle_bytes=128}, 0x7ffc15b88c04, AT_SYMLINK_FOLLOW) = -1 EOPNOTSUPP (Operation not supported)

name_to_handle_at is a syscall blocked by docker-ce > 1.12 and provided by SYS_ADMIN. I guess RedHat maintained docker or docker-latest packages does not implement seccomp or use a less rectricted seccomp profile (https://github.com/justincormack/docker/blob/master/profiles/seccomp/seccomp_default.go).

For docker point of view, this is normal by design, to add at least SYS_ADMIN (that contain this syscall), for systemd.

I looked at systemd code: particularly at https://github.com/systemd/systemd/blob/v238/src/core/mount-setup.c

```

        r = path_is_mount_point(p->where, NULL, AT_SYMLINK_FOLLOW);
        if (r < 0 && r != -ENOENT) {
                log_full_errno(priority, r, "Failed to determine whether %s is a mount point: %m", p->where);
                return (p->mode & MNT_FATAL) ? r : 0;
        }
        if (r > 0)
                return 0;

        /* Skip securityfs in a container */
        if (!(p->mode & MNT_IN_CONTAINER) && detect_container() > 0)
return 0;
```

Do you think we can manage to exclude for container mode as this (move up the container check):

```

        /* Skip securityfs in a container */
        if (!(p->mode & MNT_IN_CONTAINER) && detect_container() > 0)
return 0;

        r = path_is_mount_point(p->where, NULL, AT_SYMLINK_FOLLOW);
        if (r < 0 && r != -ENOENT) {
                log_full_errno(priority, r, "Failed to determine whether %s is a mount point: %m", p->where);
                return (p->mode & MNT_FATAL) ? r : 0;
        }
        if (r > 0)
                return 0;
```

**Comment by antoinetran** [comment]
For reference, link of wiki explanation to change if we accept: https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/

**Comment by poettering** [comment]
Current systemd versions handle gracefully if name_to_handle_at() returns EPERM, see:

https://github.com/systemd/systemd/blob/master/src/basic/mount-util.c#L192

Note that your versions is very old. We only track issues in the two most recent upstream versions here, the issue submission form should have made this very clear. For issues in older versions please contact your downstream distribution, and maybe ask them to backport the newer code.

Alternatively, please test with something more current. if the problem persists report back.

Anyway, afaics current versions handle the problem nicely. Closing hence.
