### ISSUE TITLE
RFE: add WatchdogSignal knob to control what is sent when the watchdog expires

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#8658]
Right now when a watchdog expires systemd sends a SIGABRT to the process, per https://www.freedesktop.org/software/systemd/man/systemd.service.html#WatchdogSec=. It would be useful to make this configurable (e.g. with a new `WatchdogSignal` setting), as e.g. it's not always desirable to cause a coredump (which is one of the side effects of SIGABRT), and a SIGKILL could be preferable in those cases.

**Comment by poettering** [comment]
makes sense
