### ISSUE TITLE
systemd-localed faile to write data in /etc/locale.conf when run inside a container

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#8659]
With systemd v237:

```
# machinectl start tumbleweed
[...]
# localectl set-locale LANG=fr_FR.utf8
Failed to issue method call: Access denied
```

Commenting `CapabilityBoundingSet=` in systemd-localed.service makes this issue go away.

**Comment by poettering** [comment]
hmmm which cap precisely is at fault here?

what kind of container? does it employ userns?

**Comment by poettering** [comment]
is this still an issue? can you strace localed when this happens, to determine what exactly fails?

**Comment by fbuihuu** [comment]
It seems that it's been fixed somehow as I can't reproduce the issue anymore with v246.

So let's close this one.
