### ISSUE TITLE
[sd-bus.h] Memory leak likely in sd_bus_call_method

### ISSUE THREAD

**Issue by aru777** [systemd/systemd#8671]
### Submission type
 - Bug report

### systemd version the issue has been seen with

> 237

```
$ pkg-config --cflags --libs libsystemd --modversion
237
 -lsystemd

```
### Used distribution

> centos 7

### In case of bug report: Unexpected behaviour you saw

In program https://gist.github.com/aru777/42c5bf0c08a9a67537e636107e606d4c#file-likely-leak-c-L46 `sd_bus_unref` should result in freeing of sd_bus object. But that doesn't happen. If you repeat line 46 once more, the leak doesn't happen suggesting that there is a missing `sd_bus_unref` somewhere in the chain of events inside `sd_bus_call_method`.
(the code is a slight modification of the example found here: http://0pointer.net/blog/the-new-sd-bus-api-of-systemd.html)

### In case of bug report: Steps to reproduce the problem
* Build above program with `clang -fsanitize=address -g systemdtest.c -lsystemd`
* Run `ASAN_OPTIONS=detect_leaks=1 ./a.out`
* You would see something like this: https://gist.github.com/aru777/3388f145e9a4c5fe60c51f9e0198f93b

**Comment by evverx** [comment]
@aru777 could you try using `sd_bus_flush_close_unref` instead of `sd_bus_unref`? It should make the leak go away.

**Comment by evverx** [comment]
It seems that not only the documentation should be [updated](https://github.com/systemd/systemd/issues/4846), but also the example at http://0pointer.net/blog/the-new-sd-bus-api-of-systemd.html.

**Comment by aru777** [comment]
Thank you, `sd_bus_flush_close_unref` works.

**Comment by evverx** [comment]
Thank you for checking it out. I'm closing the issue because it seems to be the same as https://github.com/systemd/systemd/issues/4846.
