### ISSUE TITLE
systemd-login sessions remain in closing state after `systemctl daemon-reload`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8672]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

> Session is properly closed even after `systemctl daemon-reload`.

### In case of bug report: Unexpected behaviour you saw

Terminated(?) sessions stay in *closing* state after `systemctl daemon-reload`.

### In case of bug report: Steps to reproduce the problem

After `ssh keineahnung pwd` the command `loginctl list-sessions` does *not* show an additional session.

Do `systemctl daemon-reload`.

`ssh keineahnung pwd`, and `loginctl list-sessions` shows an additional session. Looking at it, it is in state closing.

`systemctl restart systemd-logind` fixes this, and cleans up the sessions.

```
$ loginctl show-session 145
Id=145
User=5272
Name=joey
Timestamp=Fri 2018-04-06 10:32:19 CEST
TimestampMonotonic=234360884068
VTNr=0
Remote=yes
RemoteHost=keineahnung.molgen.mpg.de
Service=sshd
Scope=session-145.scope
Leader=2382
Audit=145
Type=tty
Class=user
Active=yes
State=closing
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
LockedHint=no
$ sudo systemctl restart systemd-logind
$ loginctl show-session 145
Failed to get session path: No session '145' known
```

**Comment by paulmenzel** [comment]
We were not able to reproduce this anymore with systemd 239. No idea, what fixed this.

**Comment by zyga** [comment]
I can reproduce this with systemd 219. It takes aboud 10-20 minutes but it is easy to reproduce.

**Comment by gleventhal** [comment]
I don't think this is fixed in 239, I have huge problems with session leak, and it brings dbus to a crawl.  

` loginctl list-sessions | awk '{ print $1 }' | shuf -n 5000 | xargs -I{} loginctl session-status {} |grep State: | sort | uniq -c
Failed to get session path: No session 'SESSION' known
   4976 	   State: closing
     22 	   State: opening
 rpm -q systemd
systemd-239-58.el8.x86_64
`

Thats 5000 randomly selected sessions, but it's filled the max sessions of 16384 (we bumped because of the leak)

**Comment by gleventhal** [comment]
There are many sessions in /run/systemd/sessions with no associated .ref FIFO file

**Comment by paulmenzel** [comment]
Thank you for your comment. As written, we were not able to reproduce the issue any more, but also moved to systemd v242.

systemd usptream only supports the latest two upstream releases – currently 250 and 251.

If you can reproduce it with one of these two versions, please open a new separate issue. Otherwise it’s up to your distribution support (or somebody else) to analyze and fix the issue.
