### ISSUE TITLE
Allow to configure path for external storage for core dump files

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8690]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238

### Used distribution

> Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

> It should be possible to configure the path were core dump files should be stored. According to `man coredump.conf` that is not possible.

As a workaround a symbolic link can be created.

**Comment by poettering** [comment]
Why doesn't the symlink approach suffice to you?

We generally don't make paths in systemd configurable at runtime, but pick FHS or otherwise "standard" paths for our stuff.

**Comment by paulmenzel** [comment]
It would probably suffice, but having everything configured in the configuration files, and not in several places, makes it easier in my opinion.

Reading [FHS 3.0, 5.8. /var/lib : Variable state information](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html), I say, that doesn’t cover storing core dump files.

**Comment by keszybz** [comment]
FHS only describes things which were there in the 90's. Anything which was invented later needs to be creatively added to this. It seems that /var/lib is the right place for coredumps.

**Comment by paulmenzel** [comment]
On 04/09/18 14:59, Zbigniew Jędrzejewski-Szmek wrote:
> FHS only describes things which were there in the 90's. Anything
> which was invented later needs to be creatively added to this.

Interesting.

> It seems that /var/lib is the right place for coredumps.

Sorry, that conclusion/deduction came just out of the blue. Why do you 
think that?

**Comment by boucman** [comment]
/var : the place we can most safely assume will be writable

/var/lib : private data for an app... yeah, it would fit in a /var/share too, I guess..

anyway man:file-hierarchy has all the details...

**Comment by keszybz** [comment]
The way a directory is selected is that we look at the list of directories in file-hierarchy(7) and FHS. The one that fits the best, or at least the one that seems the least wrong, is selected. In this case /var/lib which is described as "Persistent system data. System components may place private data in this directory." seems to be it.

Also note that this only matters when things are on different partitions. Moving stuff around within a single file system has very little practical consequences. Sometimes /var is split off, but in common setups anything under that is on one partition.

**Comment by keszybz** [comment]
`/var/share` doesn't seem to be a thing.

**Comment by poettering** [comment]
Also, if we add a runtime configurable path for this, then the next one asks for a configurable path for the journal and pretty much everything else. 

Symlinks exist, and I think they are OK to use for purposes like this. Solving this issue with symlinks means that the paths stay stable and portable: any tool, any admins will find the place for coredumps, as the original path is always available.

Hence, I am pretty sure we shouldn't make this configurable during runtime.

**Comment by keszybz** [comment]
I think we're in agreement that this is not needed. Let's close.

**Comment by paulmenzel** [comment]
Am 10.04.2018 um 14:36 schrieb Zbigniew Jędrzejewski-Szmek:
> I think we're in agreement that this is not needed. Let's close.

I am fine with closing this, but *we* is ambigous as I am still no 
convinced, so to clarify, *we* means the systemd core developers, I guess.

**Comment by keszybz** [comment]
Yeah, that's what I meant.

**Comment by 2072** [comment]
I've a crashing process whose core is > 15Gb, I've not enough room on /var/lib.

I've tried symbolic link: systemd complains that my symlink is not a directory and refuse to save the dump:

```
systemd-coredump@7-3923804-0.service: Failed at step STATE_DIRECTORY spawning /lib/systemd/systemd-coredump: Not a directory
systemd[3923806]: systemd-coredump@7-3923804-0.service: Failed to set up special execution directory in /var/lib: Not a directory
```
I've tried mount bind: systemd fails to compute the free disk space properly and abort the dump... `Cannot store coredump of 3691477 (xxx): No space left on device`

The only solution I see is to increase my /var partition to make systemd happy... I wish this setting existed or that a symbolilc link would suffice.

**Comment by Spongman** [comment]
is using symlinks here supposed to work as per the recommendations above?

all i  get is
```
Oct 15 11:31:47 machine.com systemd[1]: Started Process Core Dump (PID 3249612/UID 0).
Oct 15 11:31:47 machine.com systemd[3249613]: systemd-coredump@48-3249612-0.service: Failed to set up special execution directory in /var/lib: Not a directory
Oct 15 11:31:47 machine.com systemd[3249613]: systemd-coredump@48-3249612-0.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-coredump: Not a directory
Oct 15 11:31:47 machine.com systemd[1]: systemd-coredump@48-3249612-0.service: Deactivated successfully.
```
