### ISSUE TITLE
Ubuntu CI doesn't seem to show logs when the "upstream" test fails

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#8693]
I came across https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful-pitti-systemd-semaphore/artful/amd64/s/systemd-upstream/20180407_081138_52363@/log.gz, where the logs hadn't been shown after `TEST-16-EXTEND-TIMEOUT` had failed:
```sh
-rw-r-----+ 1 root systemd-journal 4845568 Apr  7 08:00 /var/tmp/systemd-test.Nq2jqR/journal/59852163a37d458f9d238b65f279b6fa/system.journal
TEST RUN: EXTEND_TIMEOUT_USEC=usec start/runtime/stop tests [FAILED]
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.4klBSJ/build.MGd/debian/test/TEST-16-EXTEND-TIMEOUT'
make: *** [run] Error 1
cp: -r not specified; omitting directory '/var/tmp/systemd-test.Nq2jqR/journal/59852163a37d458f9d238b65f279b6fa'
autopkgtest [08:00:53]: test upstream: -----------------------]
autopkgtest [08:00:53]: test upstream:  - - - - - - - - - - results - - - - - - - - - -
upstream             FAIL non-zero exit status 1
```
My first reaction was to put `-r` in the middle of https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/upstream#L33:
```diff
diff --git a/debian/tests/upstream b/debian/tests/upstream
index 50a7641..c324dc2 100755
--- a/debian/tests/upstream
+++ b/debian/tests/upstream
@@ -30,7 +30,7 @@ for t in test/TEST*; do
         for j in /var/tmp/systemd-test.*/journal/*; do
             [ -e "$j" ] || continue
             # keep the entire journal in artifacts, in case one needs the debug messages
-            cp "$j" "$AUTOPKGTEST_ARTIFACTS/$(basename $t)-$(basename $j)"
+            cp -r "$j" "$AUTOPKGTEST_ARTIFACTS/$(basename $t)-$(basename $j)"
             echo "---- $j ----"
             journalctl --priority=warning --directory=$j
         done
```
, but I'm not sure whether it's the right thing to do because I don't know what `AUTOPKGTEST_ARTIFACTS` is supposed to look like.

@martinpitt, @mbiebl, @xnox could you take a look?

**Comment by martinpitt** [comment]
Thanks @evverx! Committed: https://salsa.debian.org/systemd-team/systemd/commit/368160993f312

`$AUTOPKGTEST_ARTIFACTS` is just a directory that gets tar'ed up as `artifacts.tar.gz`, nothing fancy.

**Comment by evverx** [comment]
@martinpitt thank you very much! Could you also take a look at https://github.com/systemd/systemd/pull/8701#issuecomment-380213302? I'm having trouble thinking of ways to get around https://bugs.launchpad.net/ubuntu/+source/linux-lts-xenial/+bug/1682077.
