### ISSUE TITLE
Unmounting does not work with busybox

### ISSUE THREAD

**Issue by hmvp** [systemd/systemd#8699]
https://github.com/systemd/systemd/blob/c1edab7ad1e7ccc9be693bedfd464cd1cbffb395/src/core/mount.c#L889

The '-c' option is not supported by busybox

In combination with systemd-mount <USB_DRIVE> this will result in a failure every second because of the automount with timeout 1s

```
Apr 10 11:42:32 hostname systemd[1]: run-media-system-USB_DISK.mount: Mount process exited, code=exited status=1
Apr 10 11:42:32 hostname systemd[1]: Failed unmounting USB_DISK 1.
Apr 10 11:42:32 hostname systemd[1]: Failed to expire automount, ignoring: No such device
```

https://bugs.busybox.net/show_bug.cgi?id=10236

**Comment by poettering** [comment]
We require libmount and /bin/mount from util-linux, and that's documented in README. Please use the mount/umount binaries from util-linux or work with busybox upstream to add the necessary compatibility with util-linux.

Thank you for understanding

**Comment by hmvp** [comment]
That is ok, I figured as much. This is mainly for other to find a solution if they have a similar problem. 

I am not going to use util-linux just because of this -c option. It is easier to patch out the option and keep my image smaller

**Comment by poettering** [comment]
we depend on libmount from util-linux anyway. It's not that you can do without util-linux anyway... Are you sure the actual binary from util-linux really cossts you that much that it's worth the effort?

Also note that the implied assumption is that /bin/mount operates on the data libmount reports, and that libmount reflects what /bin/mount changes. If that stuff gets out of sync, then things will break sooner or later...

libmount and util-linux maintain additional metadata about mounts in /run, and i seriously doubt busybox looks there...

**Comment by hmvp** [comment]
Ugh it is an issue in Yocto. The both the busybox version and the util-linux version where actually included but the busybox one is used. Yocto actually separates all util-linux components into separate packages so it is possible to install libmount and not mount.

**Comment by boucman** [comment]
@hmvp please post a patch to yocto adding the proper RDEPENDS on the right util-linux package... so it's fixed upstream.

**Comment by boucman** [comment]
right... there is even a systemd bug to mark as duplicate :P

**Comment by poettering** [comment]
I still am pretty sure you should be careful mixing and matching util-linux libmount and a non-libmount implementation of /bin/mount. I mean, it's of course up to you, but you get to keep both pieces...

**Comment by hmvp** [comment]
@boucman There already is. The active mount binary is chosen using alternative.bbclass and the default (in case of systemd) wrong. In my case I opted to disable the busybox mount.

Anyway, I am now using the util-linux components everywhere.
