### ISSUE TITLE
'PropertiesChanged' not fired when unit finishes

### ISSUE THREAD

**Issue by LadyNamedLaura** [systemd/systemd#87]
I have a simple unit, a program starts it via the bus, and then waits for it to end.
(the current unit is just /bin/sleep 10)

The problem is  that when the unit finishes, the unit gets removed before the ActiveState is set to inactive, making my program unable to reliably detect the finishing of the unit trough PropertiesChanged.

**Comment by poettering** [comment]
Well, if you don't want the unit to be GC'ed that quickly, consider using RemainAfterExit= so that it stays around after exiting, and then stop it explicitly when you really want it to go away.

**Comment by LadyNamedLaura** [comment]
@mezcalero well, I want it to be gc'ed, I no longer care about the unit once it is finished, but I want to know WHEN it is finished, so the order i want is:
unit finishes.
set ActiveState to inactive, and send PropertiesChanged
gc unit
my program picks up propertieschanged and changes the internal state about the fact that the unit is no longer running. (It reads the values from the signal, so no other roundtrip is needed.)

**Comment by poettering** [comment]
I doubt we can ever properly fix that race, and hence if we even should try. I mean, UnitNew does not carry all device properties either, hence you cannot really get access to all properties race-freely anyway when you subscribe to a unit: it might have disappeared already by the time you try to look at it for the first time.

I think if you want to make sure you can always read the props properly, then indicate this explicitly via RemainAfterExit=, and control the state yourself...

That said, I can see that it might make sense to introduce a concept of keeping references units. i.e. a pair of methods Reference() and Unreference(), that allow increasing/decreasing a kind of per-unit reference counter (that is also automatically decreased when a client that called Reference() first disappears from the bus). then, when you start a service, you could first in the reference, then start the unit, and then be sure it won't be GC'ed until you unreferenced it again. Transient units should probably be referenced implicitly by their clients. 

Would that work for you? If so, please post a new feature request issue for that.

**Comment by cdprashanth** [comment]
Even I have same requirement. I am writing a monitoring application to monitor service start and stop.
I am listening to PropertiesChanged signal and query ActiveState.
if state is not 'active' , then I infer that service is not running.
Is this correct way ? if not what is recommended way ?

**Comment by poettering** [comment]
That is the correct way. The "ActiveState" is what you need to watch.

**Comment by cdprashanth** [comment]
thanks.
Do we get new values of property along with PropertiesChanged signal in new version of systemd?
if yes in which version this feature was added ?
In your previous comment you mentione about Reference() and Unreference(),
Is that feature added in systemd ?

As mentionef before,  I am writing a monitoring application to monitor service state.
I am listening to PropertiesChanged signal and query ActiveState. This does not work always.
Some times, unit is unloaded before I query the ActiveState. What is the solution for this ?
