### ISSUE TITLE
`pyparsing` and `evdev` should be installed on Semaphore

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#8702]
Currently `parse-hwdb.py` is skipped on Semaphore. I think it would be useful to run it there so that any errors could be detected as early as possible. It would also be great if the maintainers of `Fedora CI` got `pyparsing` and `evdev` installed so as not to give anyone a false sense that all the tests pass as apparently happened in https://github.com/systemd/systemd/pull/8694.

**Comment by keszybz** [comment]
Semaphore is done.

I'll ping Frederic Lepied about Fedora CI.

**Comment by keszybz** [comment]
Actually I can do this myself, yay!
https://src.fedoraproject.org/rpms/systemd/c/ecd200ba43e8dee79653b17b60c23c2f2dbe4e8c?branch=rpm-master

Should be all good now. Let's close this, and reopen if further changes are necessary.
