### ISSUE TITLE
su fails to create logind session (regression in 238)

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#8704]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> Debian unstable, Fedora 28

Debian runs package tests in LXC, as opposed to our upstream CI which runs tests in VM. Since 238, the [logind test has regressed](https://ci.debian.net/packages/s/systemd/unstable/amd64/):
```
autopkgtest [02:49:55]: test logind: [-----------------------
 * try-restarting systemd-logind
 * daemon is started
 * loginctl succeeds
 * XDG_SESSION_ID=
FAIL: process is not in session cgroup
/proc/self/cgroup:
10:devices:/
9:net_cls,net_prio:/
8:perf_event:/
7:cpu,cpuacct:/
6:cpuset:/
5:memory:/
4:pids:/
3:blkio:/
2:freezer:/
1:name=systemd:/
0::/
   SESSION        UID USER             SEAT             TTY             

0 sessions listed.
Failed to get session path: Caller does not belong to any known session
```

I. e. `$XDG_SESSION_ID` is empty and there is no logind session. Observations:

 * loginctl is empty, no sessions
 * `su - root` should start a PAM session (`lxc-attach` does not), but it gives:
  - journal error: pam_systemd(su:session): Failed to create session: No such device or address
  - strace: `openat(AT_FDCWD, "/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)`
  - the file exists: `crw-rw-rw- 1 root root 5, 0 Apr 10 19:55 /dev/tty`
 * However, starting a session with ssh into the container works fine: that does create a proper logind session

This is not specific to Debian, it can also be demonstrated on Fedora. On Fedora 27 (systemd 234) this works:

```
sudo lxc-create -n f27 -t download -- -d fedora -r 27 -a amd64
sudo lxc-start -n f27
sudo lxc-attach -n f27 -- su - root
[root@f27 ~]# loginctl
   SESSION        UID USER             SEAT             TTY
         2          0 root
[root@f27 ~]# poweroff
```

But when cloning the container and upgrading it to Fedora 28, it doesn't any more:
```
sudo lxc-stop -n f27
sudo lxc-copy -n f27 -N f28
sudo lxc-start -n f28
sudo lxc-attach -n f28
# dnf install -y dnf-plugin-system-upgrade
# dnf system-upgrade -y download --refresh --releasever=28
# dnf system-upgrade -y reboot

# wait for upgrade to complete (will fail, but gets far enough to update systemd to 238)
sudo lxc-attach -n f28 -- journalctl -f 

sudo lxc-attach -n f28 -- su - root
[root@f28 ~]# loginctl
   SESSION        UID USER             SEAT             TTY

[root@f28 ~]# journalctl -b -e
[...]
Apr 10 20:35:17 f28 su[84]: pam_systemd(su-l:session): Failed to create session: No 
such device or address
```

CC @mbiebl

**Comment by martinpitt** [comment]
I also tried this with nspawn, to see if this is specific to LXC. I wanted to start with `mkosi`, but at least the packaged version on Fedora 27 doesn't seem to work:
```
$ sudo mkosi -d fedora --release 28 -t directory -o /tmp/f28 build
[sudo] password for martin: 
Directory, subvolume and tar images cannot be booted.
```
(Same with `--release 27`)

So I booted a standard mock chroot instead:

```
mock -r fedora-28-x86_64 --shell 'echo mockbuild:foo | chpasswd'
mock -r fedora-28-x86_64 -i systemd
sudo systemd-nspawn -b -D `mock -r fedora-28-x86_64 -p`
```
Then log in (mockbuild:foo) and `loginctl` shows a proper login session, and `/proc/self/cgroup` is in `1:name=systemd:/user.slice/user-1000.slice/session-32.scope`. So this works. `ls -l  /dev/tty` looks exactly like in LXC.

**Comment by filbranden** [comment]
BTW to get mkosi to build directory images, you need to disable bootable explicitly. (`--bootable no` should fix it.) Yeah it's quite annoying, I've been working on a possible fix but still haven't found an approach I really liked... Anyways, passing the argument should get you unblocked there.

**Comment by martinpitt** [comment]
@filbranden : Ah, thanks for the hint! However, I'm not blocked by this, mock's chroots work fine too. Next I'll set up a bisect for this (but will take a while, I can't spend much time on this).

**Comment by poettering** [comment]
I wonder if #8577 might be related to this

**Comment by martinpitt** [comment]
@poettering: Indeed it does. It would be quite a coincidence to have two container-related regressions upon /dev/tty. However, #8577 seems to be a bug/fix in glibc, while this one is clearly related to systemd 237 vs. 238 and can be reproduced on Fedora too. But this gives me some more fodder to look into, thanks!

**Comment by martinpitt** [comment]
Actually, I spoke too soon.It does not happen on Fedora 27 (systemd 234, good) but does happen on Fedora 28 (systemd 238, bad). At first sight I thought the [test history](https://ci.debian.net/packages/s/systemd/unstable/amd64/) was a clear indicator of this being a systemd regression, but indeed [glibc 2.27](https://tracker.debian.org/pkg/systemd) hit unstable around the same time as systemd 238, so sheer coincidence. I'll try that glibc patch then.

**Comment by mbiebl** [comment]
glibc in Debian has been updated and now includes https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=a09dfc19edcbac3f96d5410529b724db0a583879

The logind autopkgtest still fails under lxc though:
https://ci.debian.net/data/packages/unstable/amd64/s/systemd/latest-autopkgtest/log.gz

```
autopkgtest [15:51:29]: test logind: [-----------------------
 * try-restarting systemd-logind
 * daemon is started
 * loginctl succeeds
 * XDG_SESSION_ID=
FAIL: process is not in session cgroup
/proc/self/cgroup:
10:perf_event:/
9:net_cls,net_prio:/
8:cpu,cpuacct:/
7:freezer:/
6:memory:/
5:pids:/
4:devices:/
3:cpuset:/
2:blkio:/
1:name=systemd:/
0::/
   SESSION        UID USER             SEAT             TTY             

0 sessions listed.
Failed to get session path: Caller does not belong to any known session
autopkgtest [15:51:30]: test logind: -----------------------]
autopkgtest [15:51:30]: test logind:  - - - - - - - - - - results - - - - - - - - - -
logind               FAIL non-zero exit status 1
autopkgtest [15:51:30]: test logind:  - - - - - - - - - - stderr - - - - - - - - - -
Failed to get session path: Caller does not belong to any known session
```
