### ISSUE TITLE
Support for LLDB in coredumpctl

### ISSUE THREAD

**Issue by refi64** [systemd/systemd#8722]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238.76

### Used distribution

> Arch Linux

[Initial mailing list post](https://lists.freedesktop.org/archives/systemd-devel/2018-April/040636.html) and [reply](https://lists.freedesktop.org/archives/systemd-devel/2018-April/040637.html):

> Hmm, three ideas:
>
> 1. we could add "coredumpctl run" which will extend the command line you have with the path to the unpacked coredump: "coredumpctl run lldb" would then do what you want (at least under the assumption that lldb is fine with just taking the coredump as argument?)
> 
> 2. we could add a --debugger= switch or so similar to what you proposed. Plus a new verb "debug" that is an alias for "gdb", to make it less idiosyncractic for you.
> 
> 3. add support for $SYSTEMD_DEBUGGER or so, which would be like #2 but you could set for your entire login session
>
> Of course any combination of the above would work too.

*Personally*, I'd love to see a combo of 2 and 3, with `$SYSTEMD_DEBUGGER=` setting the default value and `coredumpctl debug --debugger=gdb|lldb` overriding it...

Whatever route is chosen, I'd probably be able to make a PR for it.

**Comment by poettering** [comment]
choice 2 + 3 together make a ton of sense. A PR would be very welcome
