### ISSUE TITLE
RFE: Add 'install' command to systemctl

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#8725]
### Overview

Add an `install` command to systemctl that accepts a unit file and copies it to the appropriate directory.

 - Request for enhancement (RFE)
 - systemd version 215-17+deb8u3
 - Debian 8.3

### Justification

`systemctl` already provides convenience functions for accessing unit files such as `edit` & `show`.  As more software projects begin to include unit files in their repositories, it would be handy to have an `install` command that would copy these files to the appropriate location for the purpose.  `systemd` commands already know where unit files are stored in any environment; this would make adoption of systemd by non-administrator user easier and remove the need for these users to understand systemd internals (I use "internals" here loosely) more than is necessary.  

E.g., on Arch,

* `systemctl install --user <service-file>` would copy the unit to `$HOME/.config/systemd/user`
* `sudo systemctl install <service-file>` would copy the unit to `/etc/systemd/system`

Such that the casual systemd user -- who may perform this activity rarely -- would not need to remember, or spend time figuring out, where systemd stores its files.

### Real-life example

The repository for [Caddy](https://caddyserver.com) comes with an `init/linux-systemd/caddy.service` file. I often deploy caddy in development environments as a non-credentialed user, and while not onerous to do manually, having an `install` command in `systemctl` would make deploying services like this easier -- in much the same way the `edit` command makes working with unit files easier.

**Comment by poettering** [comment]
Do note that we have "systemctl link" already, which does something pretty similar to what you are asking for. Only difference: it symlinks instead of copying. Wouldn't that work for you too?
