### ISSUE TITLE
systemd-networkd DHCP client RouteTable ignored

### ISSUE THREAD

**Issue by darthjysky** [systemd/systemd#8726]
### Submission type
 - Bug report

### systemd version the issue has been seen with

238

### Used distribution

Fedora

### In case of bug report: Expected behaviour you didn't see

[root@gw1 ~]# ip route show table main
default via 192.168.22.1 dev elf0 proto dhcp src 192.168.22.63 metric 1024 
192.168.22.0/24 dev elf0 proto kernel scope link src 192.168.22.63 
192.168.22.1 dev elf0 proto dhcp scope link src 192.168.22.63 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 
[root@gw1 ~]# ip route show table 211
default via 192.168.22.1 dev elf1 proto dhcp src 192.168.22.84 metric 1024 
**192.168.22.0/24 dev elf1 proto kernel scope link src 192.168.22.84** 
192.168.22.1 dev elf1 proto dhcp scope link src 192.168.22.84 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 

### In case of bug report: Unexpected behaviour you saw

[root@gw1 ~]# ip route show table main
default via 192.168.22.1 dev elf0 proto dhcp src 192.168.22.63 metric 1024 
192.168.22.0/24 dev elf0 proto kernel scope link src 192.168.22.63 
**192.168.22.0/24 dev elf1 proto kernel scope link src 192.168.22.84** 
192.168.22.1 dev elf0 proto dhcp scope link src 192.168.22.63 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 
[root@gw1 ~]# ip route show table 211
default via 192.168.22.1 dev elf1 proto dhcp src 192.168.22.84 metric 1024 
192.168.22.1 dev elf1 proto dhcp scope link src 192.168.22.84 metric 1024 
192.168.42.0/24 dev lan0 proto kernel scope link src 192.168.42.1 

### In case of bug report: Steps to reproduce the problem

With multiple interfaces receiving IP from DHCP server

#### First interface .network
[Match]
Name=elf0

[Network]
DHCP=yes

#### Second interface .network
[Match]
Name=elf1

[Network]
DHCP=ipv4
IPForward=true
IPv6AcceptRA=false

[DHCP]
RouteTable=211

**Comment by linxiulei** [comment]
I got same bug as well at v234 (upstream)

**Comment by ssahani** [comment]
I am trying to replicate this 

```
[root@Zeus network]# ls
25-veth.netdev  26-veth.netdev  dhcp-client-ipv4-dhcp-settings1.network  dhcp-client-ipv4-dhcp-settings.network  dhcp-server1.network  dhcp-server.network  l1  rr
[root@Zeus network]# ls -ltr
total 32
drwxr-xr-x. 2 root root 4096 Feb 11 20:20 rr
-rw-r--r--. 1 root root  112 Feb 11 20:21 25-veth.netdev
drwxr-xr-x. 3 root root 4096 Feb 11 20:25 l1
-rw-r--r--. 1 root root   91 Feb 11 21:00 dhcp-server.network
-rw-r--r--. 1 root root   79 Feb 11 21:00 dhcp-client-ipv4-dhcp-settings.network
-rw-r--r--. 1 root root  114 Feb 11 21:12 26-veth.netdev
-rw-r--r--. 1 root root   80 Feb 11 21:12 dhcp-client-ipv4-dhcp-settings1.network
-rw-r--r--. 1 root root   92 Feb 11 21:13 dhcp-server1.network
[root@Zeus network]# cat 25-veth.netdev
[NetDev]
Name=veth99
Kind=veth
MACAddress=12:34:56:78:9a:bc

[Peer]
Name=veth-peer
MACAddress=12:34:56:78:9a:bd
[root@Zeus network]# cat dhcp-server.network
[Match]
Name=veth-peer

[Network]
Address=192.168.5.1/24
Address=2600::1/0
IPv6AcceptRA=no
[root@Zeus network]# cat dhcp-client-ipv4-dhcp-settings.network
[Match]
Name=veth99

[Network]
DHCP=yes
IPv6AcceptRA=no

[DHCP]
RouteTable=211
[root@Zeus network]# cat 26-veth.netdev
[NetDev]
Name=veth100
Kind=veth
MACAddress=12:34:56:78:9a:be

[Peer]
Name=veth-peer1
MACAddress=12:34:56:78:9a:bf
[root@Zeus network]# cat dhcp-client-ipv4-dhcp-settings1.network
[Match]
Name=veth100

[Network]
DHCP=yes
IPv6AcceptRA=no

[DHCP]
RouteTable=211
[root@Zeus network]# cat dhcp-server1.network
[Match]
Name=veth-peer1

[Network]
Address=192.168.5.3/24
Address=2600::1/0
IPv6AcceptRA=no

```

with dnsmasq
```
dnsmasq -8 /var/run/networkd-ci/test-dnsmasq-log-file --log-queries=extra --log-dhcp --pid-file=/var/run/networkd-ci/test-test-dnsmasq.pid --conf-file=/dev/null --interfaceeth-peer --interface veth-peer1 --enable-ra --dhcp-range=2600::10,2600::20 --dhcp-range=192.168.5.10,192.168.5.200 -R --dhcp-leasefile=/var/run/networkd-ci/lease --dhcp-option=26,1492 --dhcp-option=option:router,192.168.5.1 --dhcp-option=33,192.168.5.4,192.168.5.5 -d  -k
```

does this replicate your scenario ?

**Comment by yuwata** [comment]
@ssahani With #11694, I found the route is created by kernel when an address is assigned. Should we update the route after it is added?

**Comment by ssahani** [comment]
> @ssahani With #11694, I found the route is created by kernel when an address is assigned.

yes. address then route.

>Should we update the route after it is added?

Sorry update route after ?

**Comment by yuwata** [comment]
I mean, the route added by kernel is in the main table, so should we update the route to be in the specified table?

**Comment by ssahani** [comment]
> I mean, the route added by kernel is in the main table, so should we update the route to be in the specified table?

yes I think it's doing now too if it's specified .

**Comment by darthjysky** [comment]
@ssahani I built systemd from commit e62a7fea757f259eb330da5b6d3ab4ede46400a2 and 7c20daf69c4411979b7f8902f3601d1cdc56cc07 and both result kernel created route to main table instead of table that I defined.

**Comment by ssahani** [comment]
@darthjysky Could you please post a reproducer ? In that way it's easy to fix.

**Comment by yuwata** [comment]
@ssahani `test-network` already has a reproducer. See 0ae7a66d1a561c2ff1c8314abcdcaeba4f4d0b8b.

**Comment by darthjysky** [comment]
@ssahani 

Add new table to rt_tables:
`echo "211 test" >> /etc/iproute2/rt_tables`

Add .network file for systemd-networkd:
```
[Match]
Name=ens3

[Network]
DHCP=yes

[DHCP]
RouteTable=211

[RoutingPolicyRule]
Priority=32765
Table=211
```

reboot. and you'll get result like:

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:bf:42:3b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.147/24 brd 192.168.122.255 scope global dynamic ens3
       valid_lft 3182sec preferred_lft 3182sec
    inet6 fe80::5054:ff:febf:423b/64 scope link 
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:6b:0f:60 brd ff:ff:ff:ff:ff:ff
    inet 192.168.124.1/24 brd 192.168.124.255 scope global virbr0
       valid_lft forever preferred_lft forever
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:6b:0f:60 brd ff:ff:ff:ff:ff:ff

$ ip rule show
0:	from all lookup local 
32765:	from all lookup test 
32766:	from all lookup main 
32767:	from all lookup default 

$ ip route show table main
192.168.122.0/24 dev ens3 proto kernel scope link src 192.168.122.147
192.168.124.0/24 dev virbr0 proto kernel scope link src 192.168.124.1 linkdown 

$ ip route show table test
default via 192.168.122.1 dev ens3 proto dhcp src 192.168.122.147 metric 1024 
192.168.122.1 dev ens3 proto dhcp scope link src 192.168.122.147 metric 1024 

```
Route **192.168.122.0/24 dev ens3 proto kernel scope link src 192.168.122.147** is still in the wrong table.

**Comment by ssahani** [comment]
Sorry for late reply. What is interesting is networkd is not adding those .  It's ``` proto kernel``` that means kernel has added them. I missed this in first chance. Looking at the code detail I did not find anywhere we doing wrong.

**Comment by yuwata** [comment]
@ssahani So, there is nothing we can do for this issue?

**Comment by ssahani** [comment]
I am not sure we do a control over that.

**Comment by darthjysky** [comment]
This will result broken route for non default routing table, so I've been doing temporary fix for this issue with Pyroute2 script to move that route to correct table. I would imagine that some people would like to see that network route in both, main and custom table but that is not the case in my use case. I'd suggest adding a option to move or copy routes to correct table.

**Comment by ssahani** [comment]
But I am not sure why kernel does it ? Any idea ? These must be something which needs investigation.

**Comment by hvenev** [comment]
For IPv4 the kernel does it in `fib_add_ifaddr` in `net/ipv4/fib_frontend.c` when the flag `IFA_F_NOPREFIXROUTE` is not set on the address. Similarly in IPv6, `inet6_addr_add` adds a prefix route when the flag is not set.

It might make sense to always set `IFA_F_NOPREFIXROUTE` and create prefix routes manually (I think this is what NetworkManager does). There can also be a `RouteTable=` entry in `[Address]` sections that says where the prefix route should go.

**Comment by ssahani** [comment]
we already have it ```PrefixRoute=```

**Comment by yuwata** [comment]
I have created #12818. Though I am not 100% sure that is a right way to 'fix' this.
