### ISSUE TITLE
systemd-machined several vlan

### ISSUE THREAD

**Issue by TerAnYu** [systemd/systemd#8729]
Hello!
I ask to help in a situation:
I have a virtual machine through systemd-machined, in it I need to have 2 networks, **vlan1** + **vlan8**.
On the host were made breeches, **br1** and **br8**, where they lead to the required vlan.
How it is necessary to adjust?
I patched on the host, in the file **/etc/systemd/nspawn/mdns_repeater.nspawn** in the [Network] section, register the second line with the indication Bridge:
```
[Network]
Bridge = br1
Bridge = br8
```
It did not work.
I also tried to make vlan8 in the virtual machine itself via host0 interface - nothing happens.

**Comment by poettering** [comment]
This is not a support forum, but a bug and RFE tracker. Please contact the systemd mailing list for help instead, if you have questions or need help with using systemd.

Thank you for understanding.
