### ISSUE TITLE
clean-ipc.c doesn't check if dir is a mount point and deletes everything on the mount when owner matches

### ISSUE THREAD

**Issue by abma** [systemd/systemd#8733]
### Submission type
 - Bug report

### systemd version the issue has been seen with
 systemd 238

### Used distribution

debian buster

### In case of bug report: Unexpected behaviour you saw

when mounting a network filesystem in /dev/shm, systemd seems to delete files on the network filesystem

### In case of bug report: Steps to reproduce the problem

not sure if this will work, in my case i used cifs mounts:
mkdir /tmp/test
touch /tmp/test/test1
mkdir /dev/shm/mnt
mount -o bind /tmp /dev/shm/mnt

-> see the the contents of /tmp going away

**Comment by abma** [comment]
systemd --version
systemd 238
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Comment by poettering** [comment]
Well, /dev/shm is the place for POSIX shared memory (i.e. the backing for `shm_open()`) . Why are you even mounting something there? I mean, sure, we can make this a bit more robust and not traverse file systems, but I am not sure why you even ran into this, since this appears to be quite a weird use of /dev/shm in the first place.

**Comment by abma** [comment]
> Why are you even mounting something there?
it was the simplest way to mount sth to a subdir of a tmpfs. i guess the answer is: because it can be done.

most docs wrt /dev/shm says that its a tmpfs. nothing about an automatic purge across filesystems.

**Comment by crrodriguez** [comment]
@abma /dev/shm is reserved for posix shm.. since linux kernel developers have unfortunately not implemented shm_open() and shm_unlink as a system calls like on the BSDs.
You should not do anything else there.

**Comment by poettering** [comment]
> it was the simplest way to mount sth to a subdir of a tmpfs. i guess the answer is: because it can be done.

Well, please be careful with mounting arbitrary stuff to arbitrary places. For example, if you decide to overmount /usr/lib64 with a an empty tmpfs you are in big trouble too.

/dev/shm has a clear defined purpose which is shared memory. If you use it for anything else you are pretty much on your own, and you have to fix what you break, basically...

But anyway, we can leave this open as RFE, as a bit of rubestness against such adventurous setups is always a good idea, in particular if it's easy to add...

**Comment by poettering** [comment]
I think we should close this. It's just a really bad thing to do. We might reconsider if we get a patch, but otherwise, I doubt anyone will work at this, it's just too random a hack to do what the reporter did.
