### ISSUE TITLE
journalctl pasting accidental paste

### ISSUE THREAD

**Issue by tekjanson** [systemd/systemd#8736]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with
systemd 236

> …

### Used distribution

issue found on arch linux and BBG debian
> …

### In case of bug report: Expected behaviour you didn't see
lack of input to terminal window
> …

### In case of bug report: Unexpected behaviour you saw
write access to terminal seemed to disappear
> …

### In case of bug report: Steps to reproduce the problem
When i pasted several times while looking at my journal logs using 
journalctl -f i got locked out of input to my terminal
> …

**Comment by keszybz** [comment]
I don't understand what you're trying to say at all.

**Comment by poettering** [comment]
My educated guess is that @tekjanson was surprised that "journalctl -f" appears "stuck" if nothing is logged, and that it's not obvious for the uninitiated to get back to the shell prompt from it.

@tekjanson like in most places on UNIX, you can always hit ctrl-c to terminate the foreground program in your terminal. And that's precisely how you are supposed to exit from "journalctl -f" too...

Closing.
