### ISSUE TITLE
udev: downgrade message when we cannot apply ACLs on a device due to EOENT

### ISSUE THREAD

**Issue by dunca** [systemd/systemd#875]
Hello

I'm getting errors like:
   `systemd-udevd[XXX]:  Failed to apply ACL on /dev/bus/usb/003/004: No such file or directory`
when suspending/resuming. 

It only seems to happen on 224, no problems on 223, 222

Arch, Kernel 4.1.4

**Comment by poettering** [comment]
Any idea what device this is on USB bus 3, device 4?

Most likely this is simply a race, where a usb device pops up and is removed quickly (for example due to a modem mode changing thing), while we try to fix the device perms...

Most likely we should really just downgrade the message to LOG_DEBUG if we see ENOENT, and this is all purely cosmetic.

**Comment by dunca** [comment]
It doesn't seem to show up when using lsusb.
I've noticed that the device no., changes after each suspend. It's now 10, after suspending 4 times.

```
systemd-udevd[1118]: Failed to apply ACL on /dev/bus/usb/003/004: No such fi...
systemd-udevd[1118]: Failed to apply ACL on /dev/bus/usb/003/004: No such fi...
systemd-udevd[1735]: Failed to apply ACL on /dev/bus/usb/003/006: No such fi...
systemd-udevd[1735]: Failed to apply ACL on /dev/bus/usb/003/006: No such fi...
systemd-udevd[1982]: Failed to apply ACL on /dev/bus/usb/003/008: No such fi...
systemd-udevd[2233]: Failed to apply ACL on /dev/bus/usb/003/010: No such fi...
systemd-udevd[2233]: Failed to apply ACL on /dev/bus/usb/003/010: No such fi...
```

If I run lsusb, there's no device that matches, but there's one device whose no. keeps incrementing after resuming. 
`Bus 003 Device 011: ...... Dell Computer Corp.`,

**Comment by poettering** [comment]
Can you paste the full "lusb -v" output for that one device, so that we can see what kind of device that is?

**Comment by dunca** [comment]
Yep, it's the wwan module
`Dell Wireless 5570 HSPA+ (42Mbps) Mobile Broadband Card`

**Comment by poettering** [comment]
ah, ok, then it's modeswitching fallout: the modem pops up as one device and has then be switched to a different mode which causes it to disappear and reapper as a different devices.

Which means the issue is cosmetic and we should just downgrade the message.

**Comment by kaysievers** [comment]
https://github.com/systemd/systemd/commit/8dbf626535136b6fe6e1cf7d4ff251b2f505087c
