### ISSUE TITLE
Systemd 238 breaks memory limitations and accounting on host machine when used inside LXC container

### ISSUE THREAD

**Issue by tears-of-noobs** [systemd/systemd#8761]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> ArchLinux

### In case of bug report: Expected behaviour you didn't see

> Correct memory limitations and accounting through cgroup's on host machine when LXC starts privileged container with systemd 238 inside.

### In case of bug report: Unexpected behaviour you saw

> I use ArchLihux as a host machine for LXC containers, when I create privileged LXC container with memory limit in the configuration file, like this
```
cat /var/lib/lxc/testenv16/config | grep lxc.cgroup.memory
lxc.cgroup.memory.limit_in_bytes = 4294967296
lxc.cgroup.memory.oom_control = 1
```
and  start the container, systemd breaks memory limitations and accounting through cgroup`s on host machine.

What I saw in cgroup's on host machine after start the container
```
cat /sys/fs/cgroup/memory/lxc/testenv16/memory.limit_in_bytes
9223372036854771712
```

When I use stress utility inside container for testing memory allocation I saw strange behavior of memory accounting on host machine - floating values.

Run stress inside container
```
testenv16:~ root# stress -m 1 --vm-bytes 10G
stress: info: [100] dispatching hogs: 0 cpu, 0 io, 1 vm, 0 hdd
```

View accounting on host machine
```
 ~ # for i in {1..20}; do; cat /sys/fs/cgroup/memory/lxc/testenv16/memory.usage_in_bytes; sleep 0.5; done;
7041781760
7938052096
8843890688
9755365376
10660024320
3795841024
592605184
1510502400
2421059584
3340529664
4262752256
5167935488
6110998528
7108194304
8107356160
9092231168
10081169408
8886611968
168939520
1175965696
```

### In case of bug report: Steps to reproduce the problem

> 

* Install ArchLinux
* Install lxc (2.1 or 3.0)
* create rootfs for container with systemd 238 on board 
* create configuration file with memory limitations for LXC container
```
lxc.cgroup.memory.limit_in_bytes = 4294967296
lxc.cgroup.memory.oom_control = 1
```
* start LXC coniner (lxc-start -n container_name)
* view limits in cgroup's on host machine
```
cat /sys/fs/cgroup/memory/lxc/container_name/memory.limit_in_bytes
```

**Comment by poettering** [comment]
Hmpf, sorry, but LXC is placing its cgroups at the root of the tree, and it *really* shouldn't do. That way systemd and lxc are stepping on each others toes, and this can never work correctly.

LXC really should fix this properly, and do its stuff inside a delegated unit only (i.e. a service or scope unit with Delegate=yes set). 

What it needs to do is documented, and has been for a long time. It#s really up to LXC to actually implement this.

Do note that most of the semantics for cgroups handling are not systemd's invention btw, it stems from the kernels cgroupsv2 work, i.e. the "single writer" and "no processes in inner nodes" paradigm. 

Anway, there's nothing to fix here really. LXC shouldn't write to the top of the cgroup tree. If it does, all bets are off and things can only fail. 

Also, on cgroupsv1 delegation of controllers is not safe, and container managers should generally avoid doing that.

**Comment by poettering** [comment]
Closing this here, please work with the LXC community on this. Thank you for understanding.

**Comment by poettering** [comment]
Documentation for the cgroup APis and in particular delegation you find here:

https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/
