### ISSUE TITLE
RFE: Delete oldest logs if full

### ISSUE THREAD

**Issue by Gunni** [systemd/systemd#8772]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 219

### Used distribution

> CentOS Linux release 7.4.1708 (Core)

### Description

When the logs exceed the limits set in `SystemMaxUse` or `SystemKeepFree`, have an option to make systemd just delete the oldest journal files and keep on logging new entries.

Maybe log a high priority warning in the systemd-journald log about having done that.

### Reasons for feature

When i set up a centralized log server a few days ago, i missed the part "journald will stop using more space" and just configured `SystemMaxUse=1E` and `SystemKeepFree=10.0G` and assumed journald would log until only 10G were free on disk and then discard the oldest logs.

I then configured monitoring to alert me if this disk usage is reached so i could just increase disk space on the vm until `MaxRetentionSec=3 month` is reached and system would be in "equilibrium".

But journald just stops logging when the limit is reached and **all new log entries are silently discarded**.

Running `journalctl --vacuum-size=100G` brought size usage down to 100GB **but logging did not resume until i restarted the journald service itself**.

I have "solved" it for now using a timer that runs the vacuum command regularly but that feels very hacky.

**Comment by poettering** [comment]
Uh? When the journal hits the size limit it will vacuum what's already written and that means deleting the oldest data first.


> I have "solved" it for now using a timer that runs the vacuum command regularly but that feels very hacky.

The "vacuum" command is supposed to be "journalctl --vacuum-size=100G"? That's the precisely the same code that runs when journald tries to write a log entry to disk and finds the disk space limits being hit. 

> But journald just stops logging when the limit is reached and all new log entries are silently discarded.

If that's what happens that'd be a bug.

That said, we only track issues with the two most recent systemd upstream versions here (which currently means v237+v238). v219 is 3years old already, it doesn't qualify. The issue submission form should have made this very clear actually... For evertything older than v237 please contact your downstream distribution folks instead, they help you.

Thank you for understanding!
