### ISSUE TITLE
Specify if blank lines are allowed in `/etc/os-release`

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8773]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238

Currently, it’s not specified if blank lines are allowed in [``/etc/os-release`][1]. See [GStreamer bug report */etc/os-release parser fails on comments or empty lines*](https://bugzilla.gnome.org/show_bug.cgi?id=795346) as background.

[1]: https://www.freedesktop.org/software/systemd/man/os-release.html
[2]: https://bugzilla.gnome.org/show_bug.cgi?id=795346

**Comment by poettering** [comment]
True. We should document that. And I think we should allow them
