### ISSUE TITLE
Don't fallback to Google DNS

### ISSUE THREAD

**Issue by Kleshni** [systemd/systemd#8782]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

238.76

### Used distribution

Archlinux.

---

Leaking private data to Google when the user doesn't even know about it, is the Windows way.

See these discussions:

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1449001
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761658v

Google NTP service should also be removed from the default configuration for the same privacy reasons, though it has much lower impact than directing all DNS queries to Google. Google DNS is completely unacceptable.

**Comment by kirbyfan64** [comment]
For the sake of discussion, I guess CloudFlare's would be considered more acceptable? 

That being said, don't most ISPs use their own DNS servers that are just as bad privacy-wise? If someone really wants privacy, they'll have to configure it anyway.

**Comment by boucman** [comment]
This is about NTP, not DNS. Default DNS can already be easily replaced at compile time.

Do keep in mind that, unlike DNS, NTP would probably stay the default for most systems... which means redirecting a large amount of requests towards whoever becomes the default. So whoever is selected needs to have the capacity to support whatever trafic this change redirects...

**Comment by kirbyfan64** [comment]
Ah, whoops... I misread it when you had said "Google NTP service should *also* be removed".

**Comment by poettering** [comment]
Which servers are used (or any at all) as a fallback is a compile-time as well as a runtime option. If you don't like the upstream defaults, then please work with downstream to pick different options or make the choices locally in your configuration files.

We think it's very much in the interest of users to make things "just work", but we are fully aware that downstreams and users might want to make different choices there, hence it's configurable at every level. From upstream we just default to good, working defaults.

Hence, please tlak you your distro, or just use FallbackDNS= in resolved.conf to adjust things to whatever you like. In either case it doesn't matter what upstream does there...

Thank you for understanding.

**Comment by etale-cohomology** [comment]
Why is systemd helping Google in their effort to spy on all the world's people?
