### ISSUE TITLE
How to execute a scp command  before reboot or shutdown?

### ISSUE THREAD

**Issue by hwypengsir** [systemd/systemd#8791]
### Used distribution

>debina9

I want to upload file before reboot or shutdown.
1.From my vps to vps
vim  /etc/systemd/system/upload.service
[Unit]
Description=upload files into my vps 
Before=shutdown.target  reboot.target
Requires=network-online.target
After=network.target 

[Service]
ExecStart=/bin/true
ExecStop=/bin/bash /home/upload.sh  

[Install]
WantedBy=multi-user.target

vim  /home/upload.sh    
/usr/bin/scp -P 22   -i /home/.ssh/id_rsa   /home/wp.bak   root@remote_ip:/home

systemctl  enable upload

It is verified that wp.bak can uploaded from my vps1 to vps2 at reboot.
2.From pc at home to vps
ssh credential has been established between my pc at  home and vps.  
Same setting as case1.

journalctl -u upload 
Started upload files into my vps.
ssh: connect to host xxxxxxxxxx port 22: Network is unreachable
lost connection

How to fix?

**Comment by poettering** [comment]
This is not a support forum but a bug and feature request tracker, and the submission form really is supposed to make that clear. Please refer to the systemd mailing lists if you need help or have questions using systemd. Thank you for understanding.
