### ISSUE TITLE
`Found ordering cycle on _SERVICE_` loops due to `local-fs.target` with `Requires` instead of `Wants` for mounts generated from `/etc/fstab`

### ISSUE THREAD

**Issue by Airgunster** [systemd/systemd#8804]
### Submission type

 - Bug report

### systemd version the issue has been seen with
>```
># systemctl --version
>systemd 219
>+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
>```

### Used distribution
> ```
> # cat /etc/*release
> CentOS Linux release 7.4.1708 (Core)
> NAME="CentOS Linux"
> VERSION="7 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"
> 
> CentOS Linux release 7.4.1708 (Core)
> ```

### In case of bug report: Expected behaviour you didn't see

> All local mounts (dependencies) are defined for `local-fs.target` with `Wants` parameter.

### In case of bug report: Unexpected behaviour you saw

> All all local mounts are defined for `local-fs.target` with `Requires` parameter instead of `Wants` parameter.

### In case of bug report: Steps to reproduce the problem

> 1. Add NFS mount into `/etc/fstab`, example
>         ```server.domain:/      /mnt/test      nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0```
> 2. Add local mount with dependency on NFS mount, example,
>         ```/mnt/some_other_mount/     /mnt/test/media/      none bind,rw 0 0```

Example of `/etc/fstab`,
```
#
# /etc/fstab
# Created by anaconda on Mon Nov 27 22:04:35 2017
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=2f15c101-f516-4ee8-a4b7-89ad880610db /                       xfs     defaults        0 0

server.domain:/         /mnt/test       nfs4  nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0
/mnt/some_other_mount/  /mnt/test/medi  none  bind,rw 0 0
```

Could you please have a look? This looks as quite dangerous behavior as it can delete start job for the following services/targets,
```
        systemd-journal-catalog-update.service
        systemd-machine-id-commit.service
        systemd-tmpfiles-setup.service
        rhel-import-state.service
        systemd-update-done.service
        auditd.service
        network.service
        nfs-config.service
        local-fs.target
```

Thanks a lot in advance.

**Comment by Airgunster** [comment]
N.B. This issue can be corrected by `nofail` option in `/etc/fstab` file for all local shares, example of `/etc/fstab` with correction,

```
#
# /etc/fstab
# Created by anaconda on Mon Nov 27 22:04:35 2017
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=2f15c101-f516-4ee8-a4b7-89ad880610db /                       xfs     defaults        0 0

server.domain:/         /mnt/test       nfs4  nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0
/mnt/some_other_mount/  /mnt/test/medi  none  nofail,bind,rw 0 0
```

With `nofail`, all local mounts will be only wanted (`Wants` parameter), not required (`Requires` parameter) by `local-fs.target`. This means that units listed in `Wants` parameter will be started if the configuring unit is (i.e. it will not create a loop as with `Requires` parameter where if this unit gets activated, the units listed here will be activated as well (which will produce the loop)).

**Comment by Airgunster** [comment]
Attached output of `journalctl -alb` for bad ([journalctl-alb_bad.log](https://github.com/systemd/systemd/files/1943421/journalctl-alb_bad.log), default behavior), and good ([journalctl-alb_good.log](https://github.com/systemd/systemd/files/1943420/journalctl-alb_good.log), with `nofail` option) scenarios.

**Comment by poettering** [comment]
First of all, we only track issues with current systemd versions here, and 219 is many years old already. The issue submission is supposed to be very clear about that.

Secondly, if you have questions or need help, please refer to the systemd mailing list, not the this bug and feature request tracker. This too should have been made clear by the submission form.

Finally, if you want to mount local resources into network mounts they semselves need to be ordered after network mounts, because they essentially become that since networking needs to be up first, and shutdown only after mounts like this go down again. You can mark any mount in fstab as a network mount by appending the `_netdev` pseudo mount option to them.

But anyway, this is not the right place to discuss this, if you have further question please contact the mailing list. Thank you for understanding.
