### ISSUE TITLE
How to get  notify when the service is restart?

### ISSUE THREAD

**Issue by Amyyum** [systemd/systemd#8811]
Hello ，I want to know that how can I get  any notifies when the service is auto restart?
Thank you very much.

**Comment by boucman** [comment]
This is not a support forum, so i'll be brief... monitor dbus events coming from systemd itself.

If you want a complete explanation, pleas go to IRC or the mailing list, which is the proper place for user support

**Comment by poettering** [comment]
Yupp, this is a bug and feature request tracker, not a support forum. Please refer to the system mailing list if you need help or have questions about systemd. Thank you for understanding.

**Comment by Amyyum** [comment]
Thanks for you patience. I would like to ask another question that how can I use the systemd sd_notify function? If I can use it by creating a socket and send infomation to systemd though it? If it can do ,how can I get the ip and socket of sd_notify? @poettering @boucman

**Comment by yuwata** [comment]
Please use the mailing list...
