### ISSUE TITLE
RFE/RFC: Implement MemorySwapMax= for cgroup v1

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#8814]
I'm attempting to "backport" https://github.com/systemd/systemd/commit/96e131ea091f748780776b81b7163f8084ed8244 for cgroup v1, see WIP pull request at https://github.com/lnykryn/systemd-rhel/pull/202. I would like to implement the same in upstream. The only problem that I can see now is the semantics of "memory.swap.max" in v2 versus "memory.memsw.limit_in_bytes" in v1. In the WIP patch linked above, I'm simply adding the value specified in MemorySwapMax= to the MemoryLimit= already provided and writing it into "memory.memsw.limit_in_bytes". Sure, it doesn't map 1:1, but, in my opinion, is a good enough approximation.

Please, let me know what the preferred way to implement this would be.

**Comment by poettering** [comment]
I am not sure this really translates this easily. @htejun any chance you can comment on this?

**Comment by htejun** [comment]
I can't see anything critically broken but it's a workaround with significant subtleties which aren't easy to document. In some cases, this would make general sense and people will be happy with it, but in others, it'll do something completely unintended. To me, while I can understand why this can be attractive, it seems like the cost of possible confusions would be higher than the benefits.
