### ISSUE TITLE
systemd-tmpfiles should provide way to dump current tmpfiles configuration

### ISSUE THREAD

**Issue by jrollins** [systemd/systemd#8818]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238

### Used distribution

> debian

### Request for enhancement

It would be really useful if systemd-tmpfiles had a way to dump the current configuration.  Given that the configuration files are spread all over the system, and they can override each other, it's very difficult to know what the current configuration is.

Something like "systemd-tmpfiles --dump" that dumped all currently applied configurations would be very very useful.

Thanks!

**Comment by keszybz** [comment]
See #8824.

**Comment by poettering** [comment]
#8824 has been merged. Closing.
