### ISSUE TITLE
sd-dhcp-client.c:1404:<unknown-fcn>: code should not be reached

### ISSUE THREAD

**Issue by pnedkov** [systemd/systemd#8831]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238.76

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> libsystemd-network crashes. The computer loses all network connectivity. It happens almost every night when I am not using the computer.

### In case of bug report: Unexpected behaviour you saw

> Apr 19 19:04:26 plamen NetworkManager[861]: <error> [1524189866.8547] libsystemd: Assertion 'client->request_sent <= time_now' failed at src/systemd/src/libsystemd-network/sd-dhcp-client.c:1404, function client_set_lease_timeouts(). Aborting.
Apr 19 19:04:26 plamen NetworkManager[861]: **
Apr 19 19:04:26 plamen NetworkManager[861]: ERROR:src/systemd/src/libsystemd-network/sd-dhcp-client.c:1404:<unknown-fcn>: code should not be reached
Apr 19 19:04:27 plamen systemd[1]: NetworkManager.service: Main process exited, code=dumped, status=6/ABRT
Apr 19 19:04:27 plamen systemd[1]: NetworkManager.service: Failed with result 'core-dump'.
Apr 19 19:04:27 plamen nm-openvpn[16009]: event_wait : Interrupted system call (code=4)
Apr 19 19:04:27 plamen nm-openvpn[15986]: event_wait : Interrupted system call (code=4)
Apr 19 19:04:27 plamen nm-openvpn[15986]: SIGTERM[hard,] received, process exiting
Apr 19 19:04:27 plamen systemd[1]: NetworkManager.service: Service hold-off time over, scheduling restart.
Apr 19 19:04:27 plamen systemd[1]: NetworkManager.service: Scheduled restart job, restart counter is at 1.
Apr 19 19:04:27 plamen systemd[1]: Stopped Network Manager.
Apr 19 19:04:27 plamen systemd[1]: NetworkManager.service: Found left-over process 16006 (nm-openvpn-serv) in control group while starting unit. Ignoring.
Apr 19 19:04:27 plamen systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Apr 19 19:04:27 plamen systemd[1]: NetworkManager.service: Found left-over process 16009 (openvpn) in control group while starting unit. Ignoring.
Apr 19 19:04:27 plamen systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Apr 19 19:04:27 plamen systemd[1]: Starting Network Manager...
Apr 19 19:04:27 plamen nm-openvpn[16009]: SIGTERM[hard,] received, process exiting
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.4053] NetworkManager (version 1.10.6-3, Arch Linux) is starting... (after a restart)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.4054] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 20-connectivity.conf)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.4114] manager[0x5593512f3040]: monitoring kernel firmware directory '/usr/lib/firmware'.
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8827] hostname: hostname: using hostnamed
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8827] hostname: hostname changed from (none) to "plamen"
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8831] dns-mgr[0x55935130b930]: init: dns=default, rc-manager=symlink
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8838] manager[0x5593512f3040]: rfkill: WiFi hardware radio set enabled
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8838] manager[0x5593512f3040]: rfkill: WWAN hardware radio set enabled
Apr 19 19:04:27 plamen systemd[1]: Started Network Manager.
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8993] settings: loaded plugin keyfile: (c) 2007 - 2016 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list.
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.8996] settings: loaded plugin iBFT: (c) 2014 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list. (/usr/lib/NetworkManager/libnm-settings-plugin-ibft.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9148] keyfile: new connection /etc/NetworkManager/system-connections/rockdc-TCP4-1194-plamen (d1955e6b-41d9-485f-bcc9-e5bc756926e3,"rockdc-TCP4-1194-plamen")
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9241] keyfile: new connection /etc/NetworkManager/system-connections/dc-udp-50001-plamen (6b4198ce-f49d-4fd3-b86b-3080f67f7ef5,"dc-udp-50001-plamen")
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] manager: rfkill: WiFi enabled by radio killswitch; enabled by state file
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] manager: rfkill: WWAN enabled by radio killswitch; enabled by state file
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] manager: Networking is enabled by state file
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] dhcp-init: Using DHCP client 'internal'
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] Loaded device plugin: NMBondDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] Loaded device plugin: NMBridgeDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] Loaded device plugin: NMDummyDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9252] Loaded device plugin: NMEthernetDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9253] Loaded device plugin: NMInfinibandDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9253] Loaded device plugin: NMIPTunnelDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9253] Loaded device plugin: NMMacsecDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9254] Loaded device plugin: NMMacvlanDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9254] Loaded device plugin: NMPppDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9254] Loaded device plugin: NMTunDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9254] Loaded device plugin: NMVethDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9255] Loaded device plugin: NMVlanDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9255] Loaded device plugin: NMVxlanDeviceFactory (internal)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9351] Loaded device plugin: NMTeamFactory (/usr/lib/NetworkManager/libnm-device-plugin-team.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9355] Loaded device plugin: NMOvsFactory (/usr/lib/NetworkManager/libnm-device-plugin-ovs.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9377] Loaded device plugin: NMWwanFactory (/usr/lib/NetworkManager/libnm-device-plugin-wwan.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9386] Loaded device plugin: NMBluezManager (/usr/lib/NetworkManager/libnm-device-plugin-bluetooth.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9390] Loaded device plugin: NMWifiFactory (/usr/lib/NetworkManager/libnm-device-plugin-wifi.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9418] Loaded device plugin: NMAtmManager (/usr/lib/NetworkManager/libnm-device-plugin-adsl.so)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9418] device (lo): carrier: link connected
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9418] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9418] device (enp0s25): carrier: link connected
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9422] manager: (enp0s25): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9452] keyfile: add connection in-memory (41322d38-6234-3009-88dd-81e7f365704d,"Wired connection 1")
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9452] settings: (enp0s25): created default wired connection 'Wired connection 1'
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9455] keyfile: add connection in-memory (7080dfd1-6ef6-4e73-b802-e378ebe788d6,"enp0s25")
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9485] device (enp0s25): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9485] device (enp0s25): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9485] device (enp0s25): Activation: starting connection 'enp0s25' (7080dfd1-6ef6-4e73-b802-e378ebe788d6)
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9518] ovsdb: Could not connect: No such file or directory
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9552] device (enp0s25): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9552] device (enp0s25): state change: prepare -> config (reason 'none', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9552] device (enp0s25): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9552] device (enp0s25): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9552] device (enp0s25): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9585] device (enp0s25): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9585] manager: NetworkManager state is now CONNECTED_LOCAL
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9618] device (enp0s25): Activation: successful, device activated.
Apr 19 19:04:27 plamen NetworkManager[11302]: <info>  [1524189867.9652] manager: startup complete
Apr 19 19:04:29 plamen NetworkManager[11302]: <info>  [1524189869.2990] manager: NetworkManager state is now CONNECTED_GLOBAL
Apr 19 19:19:29 plamen NetworkManager[11302]: <info>  [1524190769.2875] manager: NetworkManager state is now CONNECTED_LOCAL
Apr 19 19:19:57 plamen NetworkManager[11302]: <info>  [1524190797.8932] connectivity: (enp0s25) timed out

### In case of bug report: Steps to reproduce the problem

> I don't have exact steps to reproduce. It always happens on its own during the night when I am not working on the computer. The network is completely lost. The problem emerged for the first time on April 19, 2018 when I upgraded to Linux 4.16 and VirtualBox 5.2.10.

**Comment by poettering** [comment]
sorry, but this is something the networkmanager folks need to look into. The copied the code into their sources, which is fine, but it kinda voids the warranty. There might be some bug lurking in our upstream version too, but it looks like there's something wrong with the event loop code on their side.

Hence, please talk to the networkmanager folks instead.

**Comment by pnedkov** [comment]
OK, thanks. I was not sure whether the problem is in systemd or networkmanager.
