### ISSUE TITLE
device flags logic is borked

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#8832]
Just a tracker so that we fix the fall-out from #8675 fully (see #8798 for details)

**Comment by keszybz** [comment]
Copying the relevant part from https://github.com/systemd/systemd/pull/8798#issuecomment-384762471:
> The "DEVICE_FOUND_UDEV_DB" flag shouldn't be there.

> I am not sure I grok everything fully, but I think we might not need to serialize the flag set at all, and always use what the kernel reports, but then when we notice that the new flag set is not in sync with the unit state enum we enqueue another state change, but do that in a defer event. That means that after deserialization we'll initially be in the old state, but pretty soon on react to the new state, and thus trigger the usual deps...

**Comment by poettering** [comment]
working on this now...

**Comment by poettering** [comment]
Fix waiting in #9200 now.
