### ISSUE TITLE
document nss-resolve and that it's necessary for resolved to do its work

### ISSUE THREAD

**Issue by a-darwish** [systemd/systemd#884]
Hi,

Using the pure systemd-networkd and systemd-resolved network configuration facilities, the system cannot resolve any DNS queries. The system is able to resolve DNS queries _only when_ using the `nameserver` command of `resolv.conf(5)`.

Systemd version (latest Arch Linux rolling release):

```
$ init --version
systemd 223
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN
```

Local ethernet card setup:

```
$ cat /etc/systemd/network/ethernet.network 
[Match]
Name=en*

[Network]
Address=192.168.1.3/24
Gateway=192.168.1.1
DNS=8.8.8.8
```

Fallback DNS setup:

```
$ cat /etc/systemd/resolved.conf
[Resolve]
DNS=8.8.8.8
FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
```

systemd-networkd logfile:

```
$ systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2015-08-06 00:52:20 EET; 34s ago
     Docs: man:systemd-networkd.service(8)
  Process: 258 ExecStart=/usr/lib/systemd/systemd-networkd (code=exited, status=0/SUCCESS)
 Main PID: 258 (code=exited, status=0/SUCCESS)
   Status: "Shutting down..."

Aug 06 00:51:48 darwish-pc systemd[1]: Starting Network Service...
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: Enumeration completed
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: enp2s0: Renamed to eth0
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: wlp3s7: Renamed to wlan0
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: eth0: Renamed to enp2s0
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: wlan0: Renamed to wlp3s7
Aug 06 00:51:48 darwish-pc systemd[1]: Started Network Service.
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: enp2s0: Gained carrier
Aug 06 00:51:48 darwish-pc systemd-networkd[258]: enp2s0: Configured
```

systemd-resolved logfile:

```
$ systemctl status systemd-resolved
● systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2015-08-06 00:51:48 EET; 1min 46s ago
     Docs: man:systemd-resolved.service(8)
 Main PID: 260 (systemd-resolve)
   Status: "Processing requests..."
   CGroup: /system.slice/systemd-resolved.service
           └─260 /usr/lib/systemd/systemd-resolved

Aug 06 00:51:48 darwish-pc systemd[1]: Starting Network Name Resolution...
Aug 06 00:51:48 darwish-pc systemd-resolved[260]: Using system hostname 'darwish-pc'.
Aug 06 00:51:48 darwish-pc systemd[1]: Started Network Name Resolution.
```

Internet connection test:

```
$ ping -c 3 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=63.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=62.6 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=62.5 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 62.583/62.777/63.142/0.258 ms
```

DNS Query test:

```
$ ping google.com
ping: unknown host google.com
```

BUT after modifying `/etc/resolv.conf` with the same configuration above:

```
$ vi /etc/resolv.conf
nameserver 8.8.8.8
```

everything works correctly afterwards, and DNS queries are resolved as expected.

```
$ ping -c1 google.com
PING google.com (213.158.163.118) 56(84) bytes of data.
64 bytes from host-213.158.163.118.tedata.net (213.158.163.118): icmp_seq=1 ttl=59 time=28.9 ms
```

Is this an expected behavior? The official Systemd documentation seems to imply that no fiddling with `resolv.conf(5)` is necessary for a working network setup.

Thanks a lot,
Darwish

**Comment by mischief** [comment]
@ASDarwish did you put `resolve` in `/etc/nsswitch.conf`?

**Comment by mischief** [comment]
@ASDarwish every program that you want to use resolved for dns needs to know about nss. if the program doesn't have nss support, or nss isn't configured right, it won't work.

**Comment by a-darwish** [comment]
@mischief
Nope, no `resolve` in `/etc/nsswitch.conf`:

```
$ cat /etc/nsswitch.conf 
passwd: files
group: files
shadow: files

publickey: files

hosts: files dns myhostname
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```

**Comment by a-darwish** [comment]
@mischief @zonque Hmmm, unless I'm missing something obvious, the necessity of NSS and/or `/etc/nsswitch.conf` wasn't mentioned in any of the `systemd-networkd(8)`, `systemd-resolved(8)`, `systemd.network(5)` or `resolved.conf(5)` manpages. The documentation there gave a powerful impression that I would just need to modify `/etc/systemd/netowrk/*.network` and `/etc/systemd/resolved.conf` files and a _system-wide_ network setup shall be operational as expected after a networkd/resolved restart.

So must I keep the resolv.conf `nameserver` entry as is for a working DNS? Would you also accept a Pull Request making this issue more clear in the documentation? Thanks.

**Comment by poettering** [comment]
Hmm?

@ASDarwish the way resolved is hooked into hostname look-ups is via NSS, configured via /etc/nsswitch.conf. Your distro really should have patched that when you installed systemd with resolved enabled. All that's necessary is to make sure the hosts line in the file looks like this:

```
hosts: files resolve myhostname mymachines
```

Specifically, "dns" needs to be replaced by "resolve".

/etc/resolv.conf OTOH should be a symlink to /run/systemd/resolve/resolv.conf which is where resolved writes out a compat resolv.conf.

This has been tersely documented in NEWS, but we should add a proper man page for nss-resolve and reference it from the resolved man page. Will change this bug now to become about that.

**Comment by a-darwish** [comment]
@poettering Excellent. Things indeed do work as expected after configuring nss _and_ creating the /etc/resolv.conf symbolic link.

After knowing this, I'm refactoring resolved code a bit now to detect the case of an `/etc/resolv.conf` without any nameserver entries and without the file itself being a symbolic link to `/run/systemd/resolv/resolv.conf`, and warn the user accordingly. Thanks!

**Comment by poettering** [comment]
I am not sure it's worth detecting that. I think network management solutions such as NetworkManager will create the file without nameservers if there is not network connection, and we should accept that without warning...
