### ISSUE TITLE
systemd-detect-virt sometimes misdetects Xen VMs as Microsoft Hyper-V

### ISSUE THREAD

**Issue by okdana** [systemd/systemd#8844]
### Submission type

- Bug report

### systemd version the issue has been seen with

237

### Used distribution

Ubuntu 18.04 (Bionic)

### Expected behaviour you didn't see

`systemd-detect-virt` should always detect Xen VMs as `xen`

### Unexpected behaviour you saw

`systemd-detect-virt` sometimes detects Xen VMs as `microsoft`

### Details

It appears that XenServer guests sometimes report their hypervisor ID as `Microsoft Hv` instead of the expected `XenVMMXenVMM`. [This posting](https://www.redhat.com/archives/virt-tools-list/2011-August/msg00126.html) on a Red Hat mailing list suggests that it does this for compatibility with Windows guests, but the exact circumstances under which it happens elude me. I have several Ubuntu 16.04 and 18.04 guests on the same Xen host, and it only happens for some of them.

Here is a comparison of two of those guests:

```
guest1 % lsb_release -sr; uname -r
18.04
4.15.0-20-generic
guest1 % SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
Virtualization Xen found in DMI (/sys/class/dmi/id/sys_vendor)
Virtualization found, CPUID=XenVMMXenVMM
Virtualization XEN, found /sys/hypervisor/properties/features with value 00002705, XENFEAT_dom0 (indicating the 'hardware domain') is not set.
Found VM virtualization xen
xen
```

```
guest2 % lsb_release -sr; uname -r
18.04
4.15.0-20-generic
guest2 % SYSTEMD_LOG_LEVEL=debug systemd-detect-virt
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
Virtualization Xen found in DMI (/sys/class/dmi/id/sys_vendor)
Virtualization found, CPUID=Microsoft Hv
Found VM virtualization microsoft
microsoft
```

I diffed 237's `virt.c` against what's in `master` right now and it doesn't look like anything would have changed there, so i suspect the behaviour is the same in 238.

I also have an Ubuntu 16.04 machine (using systemd 229) where the CPUID reports Microsoft, but `systemd-detect-virt` detects it correctly anyway. That version of systemd doesn't seem to support `SYSTEMD_LOG_LEVEL` so i can't see why it works there and not on the other one. Could be just the order of operations changed.

Anyway, it seems like systemd should treat the `Microsoft Hv` hypervisor ID as unreliable in some cases. There are several other clues on these Microsoft-reporting guests that point to them actually being Xen-based:

* DMI reports `Xen` for the vendor/manufacturer and `HVM domU` for the product name
* `/proc/xen` exists
* `/sys/hypervisor/type` reports `xen` (edit: apparently not always)

**Comment by poettering** [comment]
I prepped a fix for this in #8859. But given that I don't run I Xen I can't really test this. hence would be excellent if you could give this a whirl, and report back on the PR, so that we can merge this knowing this works?
