### ISSUE TITLE
machinectl shell should allow non-PTY connections

### ISSUE THREAD

**Issue by dw** [systemd/systemd#8850]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

HEAD

### Used distribution

Ubuntu

### In case of bug report: Expected behaviour you didn't see

Ability to connect a pipe, socketpair or similar to the newly spawned, containerized process. Only available IO primitive is PTY with fixed-size 2-4kb buffers that are unsuitable for bulk IO, and where escape sequences are interpreted to enact disconnection.

### RFE

Expose the ability to connect via a pipe (64KB default buffer, F_SETPIPE_SZ configurable) or socketpair (SO_SNDBUF/SO_RCVBUF configurable) to support tools that need bulk raw IO over the channel.

This is necessary for http://mitogen.readthedocs.io/en/latest/ where the (Python) IO loop becomes inefficient when many iterations are required for bulk transfer. TTY buffer sizes are not configurable and generally tiny on every OS including Linux, and as low as 1KB on BSD.

For e.g. a 1024MB file transfer, 262k loop iterations and context switches are required given a 4KiB buffer, dropping to 8192 iterations with a 128k buffer. File transfer is not the only use case, and even file transfer is not limited to transfers from the host into the container, or from the host's parent connection to a child connection proxied via the container -- a general mechanism for bulk data is needed.

For now I'm planning to use "machinectl status" to get the leader PID and introspect enough of that process's namespace state to essentially reimplement "machinectl shell"

**Comment by dw** [comment]
It seems `systemd-run` either allows spawning a background task, or specifying -t, which looks equivalent to what `machinectl` supports. I could potentially use `systemd-run` after stashing a socket inside the container's filesystem, and using a shell snippet to wire things up, but really what I'd like is just a clean stdio channel as if I were talking to a process on the local system

**Comment by lucaswerkmeister** [comment]
`--pipe` was added in v235.

**Comment by dw** [comment]
Ah, damn! Looking at the wrong machine. This is exactly what I need. Thanks :)

**Comment by lucaswerkmeister** [comment]
Hooray \o/
