### ISSUE TITLE
Backslashes lost in EnvironmentFile, not tested

### ISSUE THREAD

**Issue by jaraco** [systemd/systemd#8857]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 229, master

### Used distribution

> Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

> Backslashes in variable values in EnvironmentFile should appear in values to align with expectation from other .env files like Docker; tests should capture this expectation.

### In case of bug report: Unexpected behaviour you saw

> Backslashes were silently discarded. Tests [don't capture this expectation](https://github.com/systemd/systemd/blob/7a9a0c05d45a9a8cdd43a0dfabded7a9495a1fbc/src/test/test-execute.c#L448).

### In case of bug report: Steps to reproduce the problem

> On Ubuntu 16.04 using older systemd, I created an env file with a password containing a backslash. For example:

```
SYSTEM_PASSWORD=s7@o8\p=@us$0!
```

The underlying process gets a value with the backslash omitted.

Although I haven't had time to verify this behavior is still observed in the latest releases, I suspect it is as there's no test in place to capture this expectation. I can work around the issue, but I wanted to register it here so it could be addressed. It's possible the behavior has been corrected in later versions but just isn't tested by the tests. I suggest the tests should include several lines to ensure that all characters are included literally.

**Comment by poettering** [comment]
Well, the env files are supposed to be roughly shell compatible, i.e. that we implement a limited subset of shell that would work the same way in the shell as it would work for us. i.e. we want that people can source in env files into their shell scripts and they'll work the same way as they do if systemd reads them in.

Now if I paste what you suggested into a shell script like this one:

```sh
#!/bin/sh

SYSTEM_PASSWORD=s7@o8\p=@us$0!

echo "$SYSTEM_PASSWORD"
```
And run it, then I get this output:

```
s7@o8p=@uskkk.sh!
```

i.e the `\` is removed by the shell. 

Now if we have the choice of being compatible with the shell or with docker in this regard I think the shell is much more relevant, and most likely Docker should fix their logic on this too...

Hence, I don't think there's anything to fix here? I hope that makes sense?

**Comment by poettering** [comment]
That said, we could certainly add more testing on this.

**Comment by jaraco** [comment]
In [this forum post](https://forums.docker.com/t/environmentfile-compatibility-with-shell-and-systemd/51252), I propose that Docker adopt the more traditional syntax for the environment file to harmonize these two files.

**Comment by csghuser** [comment]
@jaraco I've run into this, can you explain how you was able to work around this? I've tried quotes, but in situation it doesn't seem to be working.
