### ISSUE TITLE
Predictable network interface naming failures for unpredictable hardware

### ISSUE THREAD

**Issue by fordpref** [systemd/systemd#8871]
- Bug report

### systemd version the issue has been seen with

> All Versions

### Used distribution

> Ubuntu and Debien (but those are just two I run into normally)

### In case of bug report: Expected behaviour you didn't see

> Predictable Network Interface Naming failures

### In case of bug report: Unexpected behaviour you saw

> Slight or drastic changes in network interfaces require manual reconfiguration of networking by the root user.  Changing out a hardware NIC results in a new NIC name and will require manual reconfiguration of the system configuration files for either DHCP or static network configurations.  Likewise, moving Virtual machines between virtualization platforms requires manual reconfiguration of the system by root at the destination.  Previously, new or replaced network hardware was auto-configured (albeit unpredictably for eth0, etc) and initialized for DHCP (if configured that way).  This is obviously not a desired action in some environments, but there are many instances where it is and root access is not desired at the destination.

### In case of bug report: Steps to reproduce the problem

> Move a VIrtual Machine (distribution is your choice) with a network interface (e1000 is good) to a another virtualization platform (e1000 under KVM for instance).  The VM should be considered a drop in place system that should auto configure network devices and DHCP for an address and root access is not desirable at the destination (unskilled personnel, untrusted personnel, etc).  The change in hardware will result in a Predictable Network Interface name change, and current networking configurations will be invalidated.  A new name will be configured, but the system will be unusable on the network until a root user logs in (or breaks in), finds the new network name, reconfigures the network configuration files, and restarts networking/reboots the system.  Alternatively, passing flags to the kernel in the /etc/default/grub file to disable predictable device naming, running update-grub will revert the system back to the previous generation init environment for networking and resolve the problem of hardware changes and allow for portability of the system.  If there is a way to configure systemd to use predictable naming and still allow for auto-dhcp of all new interfaces (portability) I have been unable to find it.  I've tried to be constructive here so if this is already addressed my apologies. Constructive and informative response would be appreciated if I'm in error here.  Thank you

**Comment by arvidjaar** [comment]
> configure systemd to use predictable naming and still allow for auto-dhcp of all new interfaces (portability) I have been unable to find it

This is up to your distribution network configuration framework. NetworkManager will automatically configure interfaces unless explicitly prevented.

I still fail to understand what bug on systemd side you report here.

**Comment by poettering** [comment]
> If there is a way to configure systemd to use predictable naming and still allow for auto-dhcp of all new interfaces (portability) I have been unable to find it.

Well, systemd-networkd certainly allows that. It's designed around the concept of allowing a single .network file to be applied for as many matching network devices as you like. See the second example in the systemd.network(5) man page about this.

That said, not all distros use networkd, and supporting a concept like this is up to the network management solution used. Please work with your downstream distribution and your network management solution to add a concept like that if it is missing.

There's little we can do about this from upstream otherwise, and it's not clear to me what the supposed bug this issue is about is supposed to be. Closing hence.
