### ISSUE TITLE
`boot-and-services` seems to fail sometimes because output to stderr is considered a failure

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#8880]
I came across https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful-pitti-systemd-semaphore/artful/s390x/s/systemd-upstream/20180501_233835_09a60@/log.gz and https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful-pitti-systemd-semaphore/artful/s390x/s/systemd-upstream/20180501_060918_09f4c@/log.gz where `boot-and-services` had failed because `systemctl status` had printed
```
Failed to dump process list, ignoring: Unit systemd-nspawn@c1.service not loaded
```
to `stderr`.

It seems that either `allow-stderr` should be added to https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/control#L68 or the output of https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/boot-and-services#L244 should be redirected to `stdout`.

@martinpitt could you take a look?

**Comment by xnox** [comment]
Well... stderr messages is considered an error by default. And it sounds reasonable that one should be able to start & stop an nspawn container, on an Ubuntu KVM instance without stderrors, no?! We really should not be having error messages by default, all the time. Otherwise, it becomes pointless noise that everyone will ignore.

**Comment by evverx** [comment]
As far as I can tell, the test not only launches a container but also tries to get its status via `systemctl status` after stopping it. It's expected that `systemctl` sometimes prints an error message to `stderr` if the service has been garbage-collected.

**Comment by filbranden** [comment]
Would it be reasonable to redirect stderr to stdout with `2>&1` for the particular commands where we expect stderr to be benign?

**Comment by filbranden** [comment]
Main issue I can think of (with `2>&1`) is if `systemctl` wants to *really* return an error... But in that case, I imagine it will exit with a non-zero code, which should be enough to break execution of the script and signal enough of a failure elsewhere... (In other words, I think that would be fine.)

I have a Salsa account, I may look into sending a patch there. Will post the URL here if I do. (But if someone else wants to jump in, go for it, I might not have time for this until next week or later...)

**Comment by evverx** [comment]
It'd be great if you could send a patch. Thank you!

Given that the test has been failing for about three months, I guess we aren't in a hurry. Honestly, I've got used to it and start to panic if it doesn't fail :-)

**Comment by evverx** [comment]
I don't think so, but even if we could, it would inherently cause TOCTOUs. Depending on what the test is supposed to test, it could probably be replaced with something like:
```sh
$(systemctl show --property A --value <unit>) == $expected
journalctl -u <unit> -b
```

**Comment by filbranden** [comment]
Perhaps one option would be checking for ENOENT [here](https://github.com/systemd/systemd/blob/v239/src/systemctl/systemctl.c#L4335,L4350) and skipping the log message... Not sure if that makes sense though.

That code in tests/boot-and-services seems to be doing a lot of checks, parsing the output and even checking for a specific exit code 3, so it doesn't sound to me like redirecting stderr into stdout would be *that* bad... (hmmm, except that the `self.assertNotIn('failed', out)` now depends on proper case, since this warning message `Failed ...` will now appear in stdout...)

**Comment by evverx** [comment]
Interestingly, why is `show_cgroup_and_extra` used only if `unit_show_processes` returns `-EBADR`? It seems to me that it could be used as a fallback whenever r < 0 and the return value could be ignored or, at least, because it's closer to cgroups, it would be more useful that what is returned from `unit_show_processes`.

**Comment by evverx** [comment]
In general, I agree that the idea of skipping the log message (which doesn't seem to be useful or actionable) makes sense. Bumping up the log level to debug would probably work too.

**Comment by evverx** [comment]
Having said that, I have no idea what `systemctl status` is supposed to test and still think that explicit checks like `$(systemctl show --property ... --value) == $expected` along with `systemctl status` (if it's really needed) would make more sense.

**Comment by mbiebl** [comment]
@martinpitt maybe you can chime in here

**Comment by evverx** [comment]
I'm also wondering why this happens only on `s390x`. It could be that by removing `systemctl status` or skipping the log message we're just going to hide the real issue. I'm tempted to say that I'd let the test fail until somebody figured out why that failure is much more likely to happen there. We've already reach the point where the test is ignored, so this doesn't sound as unreasonable as it was three months ago.

**Comment by martinpitt** [comment]
Post-holiday backlog.. So what should we do there? I'm happy to redirect stderr to stdout in the systemctl call in [that test](https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/boot-and-services#L246), to ignore the "not loaded" warning, if that's still the right thing to do?

**Comment by evverx** [comment]
@martinpitt thank you for taking a look! Having reread the thread, I think it would be better to downgrade the warning in `systemctl` to the debug level or drop it altogether because, frankly, it doesn't seem to be very helpful. I mean, I personally have no idea how to react to getting "Failed to dump process list". It seems a bit scary, but doesn't really matter, I think.

**Comment by evverx** [comment]
I can't remember what this issue is about but I think it can be closed.
