### ISSUE TITLE
Add sector-size parameter to crypttab for volumes encrypted with plain mode

### ISSUE THREAD

**Issue by ifranzki** [systemd/systemd#8881]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> any

### Used distribution

> any

### Description

Since commit 19a1852e4bf9146f41386e8f32072d7dd25595f1 cryptsetup plainOpen supports the **--sector-size** option to use larger block sizes.  Unfortunately **crypttab** does not support to specify the sector-size parameter for plain mode.  Without this, volumes encrypted in plain mode and a non-default sector size could not be opened automatically during system startup via crypttab. Can the support for the sector-size parameter be added to systemd's crypttab handling code?

**Comment by jsynacek** [comment]
Could you please post a link to that commit? I can't see it in the systemd code base.

**Comment by ifranzki** [comment]
I don't have a commit for this.
This is an RFE, requesting that support for the sector size is added by someone.

**Comment by jsynacek** [comment]
> Since commit 19a1852e4bf9146f41386e8f32072d7dd25595f1
Link to this one.

**Comment by ifranzki** [comment]
That commit is in the crypsetup repository on gitlab:
https://gitlab.com/cryptsetup/cryptsetup/commit/19a1852e4bf9146f41386e8f32072d7dd25595f1
