### ISSUE TITLE
Ip address deleted when dhcp renegotiation if gateway is not in the same network

### ISSUE THREAD

**Issue by jorgelon** [systemd/systemd#8888]
### Submission type

- Bug report

### systemd version the issue has been seen with

> 237 and 238

### Used distribution

> coreos  stable 1688.4.0 and  1688.5.3. also coreos alpha
> ubuntu 18.04 (systemd 237) without netplan. (systemd-networkd only)

### Environment: Vmware. Cloud provider: 1and1 / Arsys
The gateway is not part of the vm network
example:
ip from dhcp: 10.10.10.10/32
gateway: 10.255.255.1

### In case of bug report: Expected behaviour you didn't see

> When the dhcp renegotiation is done the ip address and route are mantained

### In case of bug report: Unexpected behaviour you saw

> When the dhcp renegotiation is done the ip address and route are deleted from the interface
**localhost.localdomain systemd-networkd[382]: ens192: Removing address: 10.10.10.10/32 (valid for 0)**

### In case of bug report: Steps to reproduce the problem

>The vm starts and gets the ip and routes. all works good but networkd throws an error
**ens192: Could not set DHCPv4 route: Network is unreachable**

When the dhcp renegotiation comes 12 hours later i can see in the logs that **the ip address is removed from the interface** and the vm looses the connectivity
Probably the dhcp client thinks it cannot reach the gateway. No dhcp requests observed in the dhcp server logs

It was working in previous releases of systemd and coreos. Also in previous ubuntu LTS releases

The only workaround I have found is to ignore the routes received via dhcp and add then manually. 

[Match]
Name=ens192

[Route]
Destination=10.255.255.1/32
Scope=link

[Route]
Gateway=10.255.255.1
GatewayOnlink=yes

[Network]
DHCP=yes

[DHCP]
UseRoutes=false

**Comment by jorgelon** [comment]
related coreos issue https://github.com/coreos/bugs/issues/2404

**Comment by ssahani** [comment]
What I don't figure out why there is no address 
```
ens192: Updating address: /32 (valid for 12h) <=======================HERE
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=18 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

Can you attach a tcpdump  explaining the logs

**Comment by jorgelon** [comment]
We have done a tcpdump this way

tcpdump -vvv -i ens192 port 67 or port 68 -e -n

but no dhcp traffic observed when networkd remove the ip address . no dhcp petitions logged in the dchp server

ens192: Removing address: X.X.X.X/32 (valid for 0)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=22

**Comment by ssahani** [comment]
well is the DHCP lease expired or something ? Please run in ```SYSTEMD_LOG_LEVEL=debug``` and tcpdump  with it so that we can figure what is going on .

**Comment by jorgelon** [comment]
yes, the lease expires

the systemd debug log level shows that 3 lines only.

as i said "no dhcp traffic observed when networkd remove the ip address . no dhcp petitions logged in the dchp server"

**Comment by yuwata** [comment]
Is it reproducible with the current git master?
Note that `networkd` has now more debugging logs, so even if this is not fixed, testing with the current git master helps us. Thank you.

**Comment by jorgelon** [comment]
I have created the systemd-networkd debug droppin file. I will tell you soon the new logs

**Comment by jorgelon** [comment]
This is the initial negotiation and later ip removal

Jul 10 09:23:45 localhost systemd[1]: Starting Network Service...
Jul 10 09:23:45 localhost systemd-networkd[652]: Bus bus-api-network: changing state UNSET → OPENING
Jul 10 09:23:45 localhost systemd-networkd[652]: Added inotify watch for /run on bus bus-api-network: 2
Jul 10 09:23:45 localhost systemd-networkd[652]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Jul 10 09:23:45 localhost systemd-networkd[652]: Bus bus-api-network: changing state OPENING → WATCH_BIND
Jul 10 09:23:45 localhost systemd-networkd[652]: Failed to open configuration file '/etc/systemd/networkd.conf': No such file or directory
Jul 10 09:23:45 localhost systemd-networkd[652]: timestamp of '/etc/systemd/network' changed
Jul 10 09:23:45 localhost systemd-networkd[652]: timestamp of '/run/systemd/network' changed
Jul 10 09:23:45 localhost systemd-networkd[652]: eth0: New device has no master, continuing without
Jul 10 09:23:45 localhost systemd-networkd[652]: eth0: Flags change: +MULTICAST +BROADCAST
Jul 10 09:23:45 localhost systemd-networkd[652]: eth0: Link 2 added
Jul 10 09:23:45 localhost systemd-networkd[652]: eth0: link pending udev initialization...
Jul 10 09:23:45 localhost systemd-networkd[652]: eth0: Saved original MTU: 1500
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: New device has no master, continuing without
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: Link 1 added
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: link pending udev initialization...
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: Saved original MTU: 65536
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: Adding address: ::1/128 (valid forever)
Jul 10 09:23:45 localhost systemd-networkd[652]: lo: Adding address: 127.0.0.1/8 (valid forever)
Jul 10 09:23:45 localhost systemd-networkd[652]: rtnl: received address with invalid family 129, ignoring
Jul 10 09:23:45 localhost systemd-networkd[652]: rtnl: received address with invalid family 128, ignoring
Jul 10 09:23:45 localhost systemd-networkd[652]: Enumeration completed
Jul 10 09:23:45 localhost systemd[1]: Started Network Service.
Jul 10 09:23:46 localhost systemd-networkd[652]: eth0: Interface name change detected, eth0 has been renamed to ens192.
Jul 10 09:23:46 localhost systemd-networkd[652]: Got inotify event on bus bus-api-network.
Jul 10 09:23:46 localhost systemd-networkd[652]: Added inotify watch for /run on bus bus-api-network: 2
Jul 10 09:23:46 localhost systemd-networkd[652]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Jul 10 09:23:46 localhost systemd-networkd[652]: Got inotify event on bus bus-api-network.
Jul 10 09:23:46 localhost systemd-networkd[652]: Added inotify watch for /run on bus bus-api-network: 2
Jul 10 09:23:46 localhost systemd-networkd[652]: Added inotify watch for /run/dbus on bus bus-api-network: -1
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: udev initialized link
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Link state is up-to-date
Jul 10 09:23:46 localhost systemd-networkd[652]: Virtualization VMware Virtual Platform found in DMI (/sys/class/dmi/id/product_name)
Jul 10 09:23:46 localhost systemd-networkd[652]: Virtualization found, CPUID=VMwareVMware
Jul 10 09:23:46 localhost systemd-networkd[652]: Found VM virtualization vmware
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: found matching network '/usr/lib64/systemd/network/yy-vmware.network'
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Setting address genmode for link
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Bringing link up
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Flags change: +UP +LOWER_UP +RUNNING
Jul 10 09:23:46 localhost systemd-networkd[652]: LLDP: Started LLDP client
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Started LLDP.
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Gained carrier
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Acquiring DHCPv4 lease
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): STARTED on ifindex 2
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): DISCOVER
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Could not bring up interface: Invalid argument
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): OFFER
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): REQUEST (requesting)
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): received message was not an ACK, ignoring
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): ACK
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): lease expires in 11h 59min 58s
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): T2 expires in 10h 29min 57s
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): T1 expires in 5h 59min 59s
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: DHCPv4 address 10.5.100.21/32 via 10.255.255.1
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Updating address: 10.5.100.21/32 (valid for 12h)
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Could not set DHCPv4 route: Network is unreachable
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Failed
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): STOPPED
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: udev initialized link
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: Link state is up-to-date
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: found matching network '/usr/lib64/systemd/network/yy-vmware.network'
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: Ignoring link-local autoconfiguration for loopback link
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: Ignoring DHCP clients for loopback link
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: Setting address genmode for link
Jul 10 09:23:46 localhost systemd-networkd[652]: lo: Configured
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Ignoring udev move event for device.
Jul 10 09:23:46 localhost systemd-networkd[652]: Got inotify event on bus bus-api-network.
Jul 10 09:23:46 localhost systemd-networkd[652]: Added inotify watch for /run on bus bus-api-network: 2
Jul 10 09:23:46 localhost systemd-networkd[652]: Added inotify watch for /run/dbus on bus bus-api-network: -1
[...]
ul 10 09:23:47 localhost systemd-networkd[652]: Bus bus-api-network: changing state WATCH_BIND → AUTHENTICATING
Jul 10 09:23:47 localhost systemd-networkd[652]: Bus bus-api-network: changing state AUTHENTICATING → HELLO
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=or>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=or>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=or>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedes>
Jul 10 09:23:47 localhost systemd-networkd[652]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1 path=n/a interface=n/a member=n/a coo>
Jul 10 09:23:47 localhost systemd-networkd[652]: Bus bus-api-network: changing state HELLO → RUNNING
Jul 10 09:23:47 localhost systemd-networkd[652]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interf>
Jul 10 09:23:47 localhost systemd-networkd[652]: Got message type=signal sender=org.freedesktop.DBus destination=:1.1 path=/org/freedesktop/DBus interface=org.fre>
Jul 10 09:23:47 localhost systemd-networkd[652]: Got message type=signal sender=org.freedesktop.DBus destination=:1.1 path=/org/freedesktop/DBus interface=org.fre>
Jul 10 09:23:47 localhost systemd-networkd[652]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1 path=n/a interface=n/a member=n/a coo>
Jul 10 09:23:47 localhost systemd-networkd[652]: Successfully acquired requested service name.
Jul 10 09:23:47 localhost systemd-networkd[652]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.1 path=n/a interface=n/a member=n/a coo>
Jul 10 09:23:47 localhost systemd-networkd[652]: Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.log>
Jul 10 09:23:47 localhost systemd-networkd[652]: ens192: Adding address: fe80::250:56ff:fe10:4456/64 (valid forever)
**Jul 10 21:23:49 localhost systemd-networkd[652]: ens192: Removing address: 10.5.100.21/32 (valid for 0)**
Jul 10 21:23:49 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedes>
Jul 10 21:23:49 localhost systemd-networkd[652]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus>

**Comment by ssahani** [comment]
```
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Could not set DHCPv4 route: Network is unreachable
Jul 10 09:23:46 localhost systemd-networkd[652]: ens192: Failed
Jul 10 09:23:46 localhost systemd-networkd[652]: DHCP CLIENT (0xdaec2c70): STOPPED
```

Is this the correct information your DHCP server is sending ?

**Comment by jorgelon** [comment]
That information is in the client side. The dhcp server does not receive any petitions when the client tries to renew the ip

**Comment by ssahani** [comment]
DHCP client getting these informations from your server and networkd is not able to configure .

**Comment by yuwata** [comment]
This should be already fixed in v249 or newer. Closing. Feel free to request to reopen this page, if you can still reproduce the issue in a recent release.
