### ISSUE TITLE
systemd is failing to compile on Fedora Rawhide CI

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#8896]
Since yesterday `systemd` has been failing to compile on Fedora Rawhide CI:
```sh
Has header "/usr/include/efi/x86_64/efibind.h": NO
src/boot/efi/meson.build:64:8: ERROR:  Problem encountered: gnu-efi support requested, but headers were not found
A full log can be found at /builddir/build/BUILD/systemd-239/x86_64-redhat-linux-gnu/meson-logs/meson-log.txt
```
It seems that `gnu-efi-devel` is no longer installed there.

The full log can be found at http://38.145.33.116/systemd-pr/02/2f/022fa82a8b6fa954a9eaf7620f598f18760e0e8a_dev/build.log.gz.

**Comment by yuwata** [comment]
From gnu-efi-3.0.8-3.fc29 many file paths are changed...
https://src.fedoraproject.org/cgit/rpms/gnu-efi.git/commit/?id=8e03d4aabe7ff47b452e080fa5b38bf95236b6c1

**Comment by evverx** [comment]
@yuwata thank you for spotting this change in `gnu-efi`. I figure `gnu_efi_arch` used in `meson.build` should be a set of possible alternatives, that is `x86_64` and `x64` instead of `x86_64`, and `aarch64` and `aa64` instead of `aarch64`. `boot/efi/meson.build` could iterate over those alternatives and fail if nothing is found.
