### ISSUE TITLE
journal compression very inefficient

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#8903]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

```
# systemctl --version
systemd 238
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

### Used distribution

Debian sid

Today, the topic of how much space the journal takes up in comparison to a plain text log file, came up on IRC. It was mentioned that the journal stores more meta-data but this shouldn't matter much, as the journal uses compression internally. 

For testing purposes, I used an existing journal file, and recompressed it again, using xz and lz4 (lz4 being the default compression iirc):

```
# du -hs user-1000.journal*
63M	user-1000.journal
11M	user-1000.journal.lz4
1,9M user-1000.journal.xz
```

So it looks like the compression we use is applied  extremely inefficient.

**Comment by mbiebl** [comment]
As I undestand it, user-1000.journal should already be compressed internally using lz4:
```
# grep Comp /etc/systemd/journald.conf
#Compress=yes
```

**Comment by mbiebl** [comment]
```
File Path: /var/log/journal/567a68a5c2672114bcf5192d00000008/user-1000.journal
File ID: 3b871b70c7c8484d9dddbb23ae8a2cf9
Machine ID: 567a68a5c2672114bcf5192d00000008
Boot ID: 8446cf9a5d754ee6a3e8e611dd8186ff
Sequential Number ID: 5c1837ea9014462aa3e4da561fb7ea0c
State: ONLINE
Compatible Flags:
Incompatible Flags: COMPRESSED-LZ4
Header size: 240
Arena size: 65535760
Data Hash Table Size: 113777
Field Hash Table Size: 333
Rotate Suggested: no
Head Sequential Number: 1478307 (168ea3)
Tail Sequential Number: 1576981 (181015)
Head Realtime Timestamp: Tue 2018-05-01 01:09:40 CEST (56b18f2cb9674)
Tail Realtime Timestamp: Fri 2018-05-04 20:01:36 CEST (56b651c6a2942)
Tail Monotonic Timestamp: 5h 15min 54.697s (469c9bcc5)
Objects: 102004
Entry Objects: 67456
Data Objects: 25835
Data Hash Table Fill: 22,7%
Field Objects: 44
Field Hash Table Fill: 13,2%
Tag Objects: 0
Entry Array Objects: 8667
Disk usage: 62.5M
```

**Comment by evverx** [comment]
I don't think the issue is different from https://github.com/systemd/systemd/issues/5285, so perhaps it would make sense to continue the discussion there.

**Comment by mbiebl** [comment]
Ok, fair enough
