### ISSUE TITLE
shutdown ignores --no-wall while canceling a pending shutdown

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#8904]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v232
v238

### Used distribution

Debian

Downstream bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897938

Executing ```/sbin/shutdown --no-wall -c``` sends a broadcast message.  I would expect the broadcast message to be skipped when passing --no-wall.

**Comment by ctso** [comment]
Will this be backported to stretch?

**Comment by mbiebl** [comment]
@ctso I consider this just a minor nuisance, so it's most likely not worth a backport to stretch.

**Comment by ctso** [comment]
Without going into any detail as to why, I know that many of my co-workers would disagree.
