### ISSUE TITLE
please document much more clearly that IPv6 routing advertisements are not handled by the kernel if networkd is used

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#8906]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

Originally reported against v229 but still seems valid with v238

### Used distribution

Debian

From the downstream bug report at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815582 

I just found out the hard way that systemd-network has decided not to
rely on 15 years old and tested IPv6 implementation of the Linux
kernel but to implement their own handling of incoming IPv6 router
advertisements.

The wording in systemd.network(5), for example in the section for
IPv6AcceptRouterAdvertisements, is carefully avoiding this fact and
was probably crafted to leave people in belief that this option would
only set athe accept_ra setting. The comments in networkd-link.c
suggest that accept_ra is actually always set to 0,

It is obviously the case that networkd has its own handling of
incoming IPv6 Router Advertisements. One blatant flaw of this will be
subject of a different bug report due soon.

**Comment by halvors** [comment]
@mbiebl Are you sure that systemd-networkd does this? Documentation says it's just setting the "accept_ra" kernel setting isn't it? If it is reimplementing this, that is something that surly needs to be removed.

**Comment by mbiebl** [comment]
@halvors this is a verbatim copy from the downstream bug report. You'd probably need to ask the original bug submitter as I was merely forwarding it.

**Comment by halvors** [comment]
@mbiebl Thanks :)

**Comment by poettering** [comment]
docfix waiting in #11989
