### ISSUE TITLE
How can I study systemd?

### ISSUE THREAD

**Issue by ouyangxx10** [systemd/systemd#8908]
Who can give me some advices to study sytemd?

I searched the info on the Internet and found that there was very little information about sytemd. I didn't know how to start learning systemd.  Even in the github of systemd, can not get more info.

1. I want to know that how does systemd replace init to start the whole system?
2. How can I know the starting point of systemd code?
3. How can I porting the systemd to the embedded linux?
4. How can get the help info about the systemd code?

thanks,

**Comment by mbiebl** [comment]
Hi,

this is a bug tracker and not a user support forum. Please use different channels like the mailing list https://lists.freedesktop.org/mailman/listinfo/systemd-devel or IRC (#systemd on freenode) instead.
