### ISSUE TITLE
networkd: Invalid default route not removed when given a different gateway via DHCP

### ISSUE THREAD

**Issue by roothorick** [systemd/systemd#8910]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Ubuntu Server 18.04

### In case of bug report: Expected behaviour you didn't see

> A badly-behaved cable modem initially served a 192.168.100.2/24 address with a gateway of 192.168.100.1. networkd created an appropriate default route. Shortly afterwards (must have been a very short lease time), the ISP's actual DHCP server rejected that lease and served a new one on a public IP, with an appropriate gateway. The default route via 192.168.100.1 should have been deleted and a new one created in its place.

### In case of bug report: Unexpected behaviour you saw

> A default route for the new gateway was appended beneath the old one, leaving the system still trying to route outbound traffic to 192.168.100.1 despite no longer having an interface configured on the 192.168.100.0/24 network.

### In case of bug report: Steps to reproduce the problem

> Offer a lease with one gateway, then reject (NAK) the subsequent renewal and serve a different IP, subnet, and gateway. Retain carrier link throughout this process.

**Comment by ssahani** [comment]
Please attach logs and the output which should make debugging much easier.

**Comment by yuwata** [comment]
@roothorick Fix is proposed in #10471. If possible, please test the PR.
