### ISSUE TITLE
`systemctl poweroff/reboot --force` (or at least the dbus equivalent) isn't unmounting rootfs cleanly?

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8912]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd-238-7.fc28.1.x86_64

### Used distribution

Fedora 28

### In case of bug report: Expected behaviour you didn't see

Following a forced shutdown, filesystems are clean, and fsck reports them as such on the following boot.

I'm not naive enough to think this would always work, but I feel it is wrong for this to be failing consistently  on what is a pretty straightforward Fedora system. I have a single spinning hard drive. Root filesystem is ext4 on LVM.  I have no other block devices in `lsblk`. I am not using any network filesystems. I was not using any MTP mounted device or anything else which would have required FUSE.

I happen to have a self-bind mount on `/mnt`. EDIT3: the unclean unmounts definitely pre-date this bind mount.

### In case of bug report: Unexpected behaviour you saw

    systemd-fsck[461]: /dev/mapper/alan_dell_2016-fedora: recovering journal

following the forced shutdown.  This applies to the root filesystem only; it does not apply to my /home or /boot filesystems which are also ext4.

### In case of bug report: Steps to reproduce the problem

1. Run Fedora Workstation, use offline updates from the GUI as they arise, which use pk-offline-update (packagekit).
2. Check journalctl logs for the above fsck message (e.g. `journalctl /usr/lib/systemd/systemd-fsck`), and match them against e.g. `journalctl /usr/libexec/pk-offline-update`.

/home and /boot are definitely mounted by the system. I don't know why they're not affected. This is consistent even when the set of updates inclues a new kernel, which is written to /boot.

---

On Fedora, PackageKit offline updates have a bug where it uses a forced shutdown, instead of a graceful shutdown. On both Fedora 27, and Fedora 28, this has caused a fsck of the root filesystem (only) on subsequent boot. I don't think this should happen, even with the forced shutdown.

https://bugzilla.redhat.com/show_bug.cgi?id=1564462

Some more detailed evidence of unclean unmount on Fedora 28 is available at https://unix.stackexchange.com/questions/441511/does-recovering-journal-prove-an-unclean-shutdown-unmount

EDIT: My historical fsck logs are annoying to look at.  Before upgrading to F28 - systemd v234 in Fedora 27 was also not cleanly unmounting the root filesystem anyway. https://bugzilla.redhat.com/show_bug.cgi?id=1554943 . EDIT2: but the logs seem to include a time before systemd v234, where unclean unmounts only happen during PK offline updates.  The unclean unmount (of rootfs only) seems to happen consistently in this case.

---

Analysis note. Although a graceful shutdown of a Fedora LVM root system will involve a shutdown initramfs, this does not apply to a forced shutdown. The reason is that if you look at `dracut-shutdown.service`, /run/initramfs is only populated during the graceful shutdown of services. (I also noticed that on a VM with rootfs on a partition instead of LVM, dracut does not create `/run/initramfs/.need_shutdown`, and then `dracut-shutdown.service` doesn't populate `/run/initramfs` for shutdown).

**Comment by sourcejedi** [comment]
Turns out the root filesystem cannot be remounted read-only because it is still in use (i.e. EBUSY).  See photo below.

It sounds a little similar to another bug affecting this system, I guess we'll learn more if the other one gets fixed... https://bugzilla.redhat.com/show_bug.cgi?id=1575376

I note that plymouth is not one of the packages that was upgraded in this last offline update. Confirmed by looking at the journal logs from pk-offline-update, and the information which gnome-software shows about the last offline update.

![wp_20180507_012](https://user-images.githubusercontent.com/14057/39701818-7d6479b4-51fa-11e8-9ed1-1b78ab523182.jpg)

**Comment by poettering** [comment]
There's nothing much we can do here. Plymouth is keeping this busy, and it explicitly excludes itself from the killing spree we do at the end to ensure the mounts aren't busy, by doing argv[0][0] = '@'.

This really needs to be fixed in plymouth i guess. It either needs to stop excluding itself from the killing spree (which I understand they don't really want as that means flickering screen output, which is the whole point of ply to make pretty), or they need to make sure it reexecs itself or so whenever plymouth or any library it uses or any other files it keeps pinned are updated. (or alternatively, and probably safe would be if it would just reexec itself unconditionally during shutdown, and during boot).

But yeah, I don't think there's anything we can or should do about this from the systemd side. It's plymouth which needs to fix that...

**Comment by poettering** [comment]
hmm, if should probably log to dmesg directly if it masks itself as argv[0][0] == '@' process... After all, doing that makes you in many ways more like a kernel thread, independent of userspace, and in that case you really should make sure you don't keep files pinned on the host fs, and in particular not writable...
