### ISSUE TITLE
Type=dbus service needs option for session bus services

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#892]
Currently, `Type=dbus` is unsuitable for things like notification daemons because `BusName=` is expected to appear on the system bus, but `org.freedesktop.Notification` is meant for the session bus.

**Comment by poettering** [comment]
Hmm? no... Type=dbus services with BusName= set should watch the user bus for the systemd user instance and the session bus for the systemd system instance. Are you saying that that's not what you are seeing?

**Comment by mathstuf** [comment]
#891 would help debugging this ;) . I did have to change a user service from dbus to simple due to a timeout though. I'll try and switch it back tonight. Is a dbus-1/…/foo.service file required for it to work at all? Would also be good for the docs and error message if so.

**Comment by mathstuf** [comment]
Using `Type=dbus` and `BusName=org.freedesktop.Notifications`:

```
% qdbus
:1.19
 org.gtk.vfs.Metadata
:1.2
 im.pidgin.purple.PurpleService
:1.3
:1.4
 org.PulseAudio1
 org.freedesktop.ReserveDevice1.Audio0
 org.pulseaudio.Server
:1.41
 org.gtk.Private.UDisks2VolumeMonitor
:1.43
:1.6
 org.gtk.vfs.Daemon
:1.8
 org.a11y.Bus
:1.92
:1.93
:1.96
 org.freedesktop.Notifications
:1.97
org.freedesktop.DBus
```

Log:

```
Aug 07 19:44:47 bronto-burt systemd[6093]: Stopping Dunst notification daemon...
Aug 07 19:44:47 bronto-burt systemd[6093]: Stopped Dunst notification daemon.
Aug 07 19:44:47 bronto-burt systemd[6093]: Starting Dunst notification daemon...
Aug 07 19:46:17 bronto-burt systemd[6093]: dunst.service: Start operation timed out. Terminating.
Aug 07 19:46:17 bronto-burt systemd[6093]: Failed to start Dunst notification daemon.
Aug 07 19:46:17 bronto-burt systemd[6093]: dunst.service: Unit entered failed state.
Aug 07 19:46:17 bronto-burt systemd[6093]: dunst.service: Failed with result 'timeout'.
```

**Comment by mathstuf** [comment]
Tried again with a better `dbus-1` service file:

`.local/share/dbus-1/services/org.freedesktop.Notifications.service`:

``` ini
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/bin/dunst
SystemdService=dunst.service
```

`.local/share/systemd/user/dunst.service`:

``` ini
[Unit]
Description=Dunst notification daemon
Requires=xorg.target
After=xorg.target

[Service]
Type=dbus
BusName=org.freedesktop.Notifications
ExecStart=/usr/bin/dunst
```

**Comment by mathstuf** [comment]
Oh, same result with these units: a timeout.

**Comment by chmorgan** [comment]
I'm seeing the same here with systemd 219, that Type=dbus isn't working correctly with user services.

**Comment by kamathba** [comment]
Same problem with systemd 222, switching it to type notify and using sd_notify worked.

**Comment by smcv** [comment]
`Type=dbus` works fine for user-services that are D-Bus session services on Debian testing/unstable with the `dbus-user-session` package installed, so I think this is some configuration issue in whatever OS you're using. `gnome-terminal-server`, `xdg-desktop-portal`, `flatpak-session-helper`, `evince`, `mpDris2` are among the user-services for which it definitely works for me.

This is not going to work if `systemd --user` can't or doesn't connect to your D-Bus session bus (aka user bus). I don't see `org.freedesktop.systemd` in [the list of owned names above](https://github.com/systemd/systemd/issues/892#issuecomment-128860808), which suggests that systemd has not succesfully connected to that bus; if it hasn't connected, then it is clearly not going to notice that dunst has claimed its bus name.

How, exactly, are you running `dbus-daemon --session`? On which OS distribution? What is your `$DBUS_SESSION_BUS_ADDRESS`?

If you are using the same setup as Debian with the `dbus-user-session` package, Fedora and Arch Linux, then you should have a socket `$XDG_RUNTIME_DIR/bus` with socket activation from `dbus.socket`, which starts `dbus.service` on connection attempts; and `systemd --user` should be connecting to that socket and requesting the `org.freedesktop.systemd` name.

> Type=dbus services with BusName= set should watch the user bus for the systemd user instance and the session bus for the systemd system instance.

I assume that was meant to say: should watch the user bus (aka session bus, `dbus-daemon --session`) for the systemd user instance (`systemd --user`), and the **system** bus (`dbus-daemon --system`) for the systemd system instance (pid 1).

**Comment by mathstuf** [comment]
Here is my `dbus.service`:

```systemd
[Unit]
Description=D-Bus System Message Bus
Wants=environment.target
After=environment.target
After=dbus-env.service
Requires=dbus.socket

[Service]
ExecStart=/usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation
ExecReload=/usr/bin/dbus-send --session --print-reply --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig

[Install]
WantedBy=x11-standard.target
Also=dbus.socket
```

`dbus-env.service`:

```systemd
[Unit]
Description=DBus Environment
Wants=environment.target
Before=environment.target
BindsTo=dbus.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS=unix:path=%t/dbus/user_bus_socket
ExecStop=/usr/bin/systemctl --user unset-environment DBUS_SESSION_BUS_ADDRESS

[Install]
WantedBy=environment.target
```

`dbus.socket`:

```systemd
[Unit]
Description=D-Bus System Message Bus Socket
BindsTo=dbus.service

[Socket]
ListenStream=%t/dbus/user_bus_socket

[Install]
WantedBy=x11-standard.target
```

**Comment by smcv** [comment]
> Here is my `dbus.service`

Let me guess, you got that from <https://github.com/sofar/user-session-units>? Those units are not a product of either the systemd maintainers or the dbus maintainers, although some of them acted as a useful prototype for what was later merged into dbus.

dbus 1.10 or later, built with `--enable-user-session`, obsoletes those units by providing its own. These use the socket that systemd assumes, namely `%t/bus`.

**Comment by mathstuf** [comment]
No, I had written many of these up before many user units got written (2009 or 2010 IIRC?), but only started using them in 2012 or so. I use these rather than upstream because I do the `environment.target` setup for managing environment variables and to ensure they are all set before services which may need them start up (it'd be nice if systemd would have standard targets for things like that so that in the user session services can start with a full environment).

So if I use `%t/bus` things should work? Isn't that a bug? I'll look in more detail what is different from upstream's units.

**Comment by smcv** [comment]
> I use these rather than upstream

In most cases I would recommend using drop-ins (`dbus.service.d/local.conf`) rather than overriding upstream units completely.

I would also recommend tracking whether the upstream projects that you rely on already have their own solutions to issues you encounter, and if not, upstreaming your solutions if applicable.

> So if I use `%t/bus` things should work? Isn't that a bug?

Is it a bug for `systemd --user` to have trouble with situations that are outside what it supports? I would say it isn't.

You're effectively acting as your own OS integrator here, so it's your responsibility to make everything integrate, either by configuration or patching, or by changing aspects of your design to sync up with upstream (the same choices and actions that distributors like Debian and Red Hat need to make).

**Comment by smcv** [comment]
I think this is misconfiguration, rather than a systemd bug. Can this be closed?

Or if not, please clarify what implementable behaviour change by systemd would resolve this?

The only way I can see that those units could work would be if, when systemd --user received new environment variables, it checked whether DBUS_SESSION_BUS_ADDRESS had changed, and if so, it connected to the new address to provide activation services. I think it would be reasonable to say that this is too complicated for too little benefit, and you should use %t/bus as your session (user) bus socket, like dbus upstream does since 1.10.

**Comment by mathstuf** [comment]
Yep, sorry for not reporting back. I've since updated by DBus socket to be `%t/bus` and I now see `org.freedesktop.systemd1` on the bus now, so if I notice failures in `Type=dbus` from here on out, I'll reopen (I had converted all of them to `Type=simple` in the meantime).

**Comment by sofar** [comment]
LOL. Sorry. @smcv made me chuckle. :)
