### ISSUE TITLE
Broken link on journal-remote.conf online doc

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#8921]
### Submission type

 - Bug report

### systemd version the issue has been seen with

Any. Online documentation issue.

### Used distribution

 Any. Online documentation issue.

### In case of bug report: Unexpected behaviour you saw

Description paragraph on https://www.freedesktop.org/software/systemd/man/journal-remote.conf.html has broken link on  ```systemd-journal-remote.service(8)```, which doesn't exist (returns 404).

On main page: https://www.freedesktop.org/software/systemd/man/index.html there is the list, related to ```systemd-journal```:

```
systemd-journal-gatewayd(8) — HTTP server for journal events
systemd-journal-gatewayd.service(8) — HTTP server for journal events
systemd-journal-gatewayd.socket(8) — HTTP server for journal events
systemd-journal-remote(8) — Receive journal messages over the network
systemd-journal-upload(8) — Send journal messages over the network
systemd-journald(8) — Journal service
systemd-journald-audit.socket(8) — Journal service
systemd-journald-dev-log.socket(8) — Journal service
systemd-journald.service(8) — Journal service
systemd-journald.socket(8) — Journal service
```

### In case of bug report: Steps to reproduce the problem

1. Open https://www.freedesktop.org/software/systemd/man/journal-remote.conf.html
2. Try to open current link ```systemd-journal-remote.service(8)``` in ```Description``` paragraph.
3. Get 404.
4. File the bug-report in systemd git. :)

**Comment by yuwata** [comment]
#8922 is merged. Let's close this.
