### ISSUE TITLE
udevadm: -d --debug doesn't bring udev realm debug output

### ISSUE THREAD

**Issue by Shuangistan** [systemd/systemd#8931]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v234, sorry currently no Meson on my place.
> I checked the code, there is no significant changes since v234 on this part.
> I would appreciate if someone can test this on the newest version.

> #7666 seems not having fixed the problem here.

### Used distribution

> customized.

### In case of bug report: Expected behaviour you didn't see

> without define udev_log="debug" in udev.conf

$ udevadm --debug test /devices/pci0000:00/0000:00:02.0/drm/card0
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Load module index
Created link configuration context.
Reading rules file: /lib/udev/rules.d/60-block.rules
Reading rules file: /lib/udev/rules.d/60-cdrom_id.rules
..
GROUP 44 /lib/udev/rules.d/50-udev-default.rules:34
GROUP /etc/udev/rules.d/.rules:18
MODE 0660 /etc/udev/rules.d/.rules:18
handling device node '/dev/dri/card0', devnum=c226:0, mode=0660, uid=0, gid=
preserve permissions /dev/dri/card0, 020660, uid=0, gid=
preserve already existing symlink '/dev/char/226:0' to '../dri/card0'
ACTION=add
DEVNAME=/dev/dri/card0
DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0
DEVTYPE=drm_minor
MAJOR=226
MINOR=0
SUBSYSTEM=drm
USEC_INITIALIZED=5021837610
Unload module index
Unloaded link configuration context.

### In case of bug report: Unexpected behaviour you saw

> The debug output is missing.

$ udevadm --debug test /devices/pci0000:00/0000:00:02.0/drm/card0
calling: test
version 234
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

=== trie on-disk ===
tool version:          234
file size:         7433623 bytes
header size             80 bytes
strings            1901791 bytes
nodes              5531752 bytes
Found container virtualization none.
created empty file '/run/udev/data/c226:0' for '/devices/pci0000:00/0000:00:02.0/drm/card0'
ACTION=add
DEVNAME=/dev/dri/card0
DEVPATH=/devices/pci0000:00/0000:00:02.0/drm/card0
DEVTYPE=drm_minor
MAJOR=226
MINOR=0
SUBSYSTEM=drm
USEC_INITIALIZED=3919043962

### In case of bug report: Steps to reproduce the problem

> 
Probably the line 106 here
https://github.com/systemd/systemd/blob/master/src/udev/udevadm.c
shall be
    log_set_max_level_realm(LOG_REALM_UDEV, LOG_DEBUG);
instead of
    log_set_max_level(LOG_DEBUG);

**Comment by yuwata** [comment]
I cannot reproduce this with recent git snapshot.
It seems that meson.build adds `-DLOG_REALM=LOG_REALM_UDEV` for all udev related commands.
Also, `test` and `test-builtin` udev commands always set log level `LOG_DEBUG`. So, at least, `--debug` option does not change the outputs of these commands.
Could you test with the recent snapshot?

**Comment by keszybz** [comment]
I tested this here, and it works fine too. There were bugs in this area, but afaik they were all fixed. Please reopen if you can reproduce with a recent version.
