### ISSUE TITLE
RFE: use RestrictNamespaces=yes in systemd-resolved.service ?

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8949]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd-238-7.fc28.1.x86_64

### Used distribution

Fedora

### In case of bug report: Expected behaviour you didn't see

`RestrictNamespspaces=yes` in output of `systemctl cat systemd-resolved`

### In case of bug report: Unexpected behaviour you saw

`systemctl cat systemd-resolved` shows no usage of RestrictNamespspaces=

### In case of bug report: Steps to reproduce the problem

systemctl cat systemd-resolved

---

I didn't find any discussion of _using_ `RestrictNamespaces=` in the issue tracker (for any of the builtin systemd services).

It seems to me, restricting user namespaces is one of the most straightforward wins for being able to reduce "attack surface" with a seccomp filter.  In particular, `resolved` is interested in service confinement because it is a network service.

I didn't find this in TODO either. Posted as RFE for now. I don't know how systemd-resolved works, and have not yet reviewed it to see if it uses namespacing features somehow.

**Comment by poettering** [comment]
hmm, and networkd is missing it too...
