### ISSUE TITLE
Clarify what clients should do when SD_JOURNAL_INVALIDATE is received

### ISSUE THREAD

**Issue by richm** [systemd/systemd#8963]
**Is your feature request related to a problem? Please describe.**
The man page https://www.freedesktop.org/software/systemd/man/SD_JOURNAL_INVALIDATE.html says this:
"If SD_JOURNAL_INVALIDATE, journal files were added or removed (possibly due to rotation). In the latter event, live-view UIs should probably refresh their entire display"

What does this mean in the context of a background daemon process like rsyslog that uses the journal apis: https://github.com/rsyslog/rsyslog/blob/master/plugins/imjournal/imjournal.c#L507

**Describe the solution you'd like**
A detailed description in the man page of what exactly SD_JOURNAL_INVALIDATE means and what clients should do in this case.
An example of some code a log reading application should use when sd_journal_wait/sd_journal_process returns SD_JOURNAL_INVALIDATE - get cursor if possible, write cursor to a backing save file, close the journal, open the journal, load saved cursor, seek to saved cursor position.

**Describe alternatives you've considered**
None

**Comment by poettering** [comment]
There are two PRs filed that are supposed to fix this: #9124 and #9060.
