### ISSUE TITLE
add legend for systemd-analyze plot graphic somewhere

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#8970]
Execute in terminal `'systemd-analyze plot > systemd-analyze_output.svg'`  then edit the file in web browser. As noticeable the **overall time output** is attached to a **pattern** which is **not part of the specification** (sample).

![kuvakaappaus 2018-05-11 13-24-13](https://user-images.githubusercontent.com/26058215/39922406-41892962-551f-11e8-996b-0723490ac7c1.png)

The _legend_ is located far from its expected **practical location** which is to be found **just after** the very lines related to 'systemd-analyze' outputs. But mainly  the legend lacks **comprehensive descriptions**  attached to their respective **short-term-descriptions**. For instances, what are currently '_Activating_',  '_Active_',  '_Deactivating_'... and so on?

![kuvakaappaus 2018-05-11 13-26-21](https://user-images.githubusercontent.com/26058215/39922710-96c7bc26-5520-11e8-987f-1721c2316439.png)

**Comment by poettering** [comment]
I am not sure we need to include longer explanations in the SVG, but I figure it would be fine to add some docs about he meanings to the man page

**Comment by Ricky-Tigg** [comment]
Information at the right place an only when needed. Added in newspapers; indeed you can add it. It looks like so much adding 'some docs' in man page. Just let me know when an SVG file happened to be rendered in man page and will be soon for sure.
