### ISSUE TITLE
logind restart support broke again. somehow.

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8976]
## systemd version the issue has been seen with

systemd-238-7.fc28.1.x86_64

## Used distribution

Fedora 28

## Expected behaviour you didn't see

PID 1 has /dev/dri/card0 open. (Yes, [seriously](https://unix.stackexchange.com/questions/431982/what-could-be-using-6gb-of-my-swap)).

## Unexpected behaviour you saw

PID 1 does not have /dev/dri/card0 open

## Steps to reproduce the problem

* Fedora Workstation 28
* Boot
* Log in to GNOME

This is good so far, and we can verify it. /dev/dri/card0 is open in PID 1.

* `sudo lsof -p | grep dev` and `sudo lsof -p | grep dri`

Now switch to VT6 using ctrl+alt+f6.  Log in and try again at the resulting shell.

* `sudo lsof -p | grep dev` and `sudo lsof -p | grep dri`

at this point /dev/dri/card0 is closed. You can also switch back to your GNOME login (ctrl+alt+f2), and you will see that /dev/dri/card0 is not re-opened in PID 1.

This is a regression since Fedora 27. I have a Fedora 27 VM which does not show the above behaviour, and a Fedora 28 VM which does.

This yet again breaks the support for restarting logind. It's not possible to test that straighforwardly, because no-body is actually using that support. Restarting logind causes both X and gnome-shell to die.

**Comment by sourcejedi** [comment]
This might be some combination of a regression in Fedora, and SELinux.

The Fedora 28 VM (and my laptop) have SELinux in enforcing mode. Booting F28-VM with `enforcing=0` appeared to "fix" the problem. However booting F27-VM with enforcing=1 did not trigger the problem. Neither did the problem exhibit after installing systemd 238-git-something to F27-VM and rebooting.

However nothing appears in "Selinux Troubleshooter", and there seems to be nothing relevant in the audit log.  So it is a "dontaudit" rule or something more subtle.

I have reported it against the selinux policy package in Fedora. https://bugzilla.redhat.com/show_bug.cgi?id=1577498

**Comment by keszybz** [comment]
@sourcejedi what was the final resolution here? I see the bugzilla bug is also closed…

**Comment by sourcejedi** [comment]
1. #8992 "service: FileDescriptorStoreMax should also imply NotifyAccess".

    That is, my test results in the VM were complicated because at some point I commented out `WatchdogTimeoutSec=3m` in `systemd-logind.service`. This caused `NotifyAccess` to revert to the default `none`, so it was completely impossible to pass FDs to PID 1.
2. I think I started writing this up for v238 / F28 because I didn't understand the behaviour as matching one of the previous failure modes I'd seen. But actually, I think what I was seeing was just an aspect of a bug I fixed, which unfortunately for me got merged after v238.

   > I think the VT switch caused gnome-shell to release input devices (ReleaseDevice method in logind dbus API). This causes logind to remove the FD for the device.
   >
   > So this is most likely affected by the issue #8344 "session_device_free(sd) also drops all other device fds of that session" . A fix is merged for systemd v239.
   >
   > I confirmed this by testing a pre-release version of systemd, which included the fix.

   https://unix.stackexchange.com/a/443714/29483
