### ISSUE TITLE
systemd drops connection after bad introspection call

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#8978]
```console
$ systemd-analyze log-level debug
$ busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/dbus_e2socket<TAB>
Failed to introspect object /org/freedesktop/systemd1/unit/dbus_e2socket of service org.freedesktop.systemd1: Remote peer disconnected
$ systemctl
(hangs)
```
in the logs:
```
May 12 21:16:47 krowka systemd[1]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=48 reply_cookie=0 signature=s error-name=n/a error-message=n/a
May 12 21:16:53 krowka systemd[1]: Got message type=method_call sender=:1.173 destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/dbus_e2socket interface=org.freedesktop.DBus.Introspectable member=Introspect cookie=2 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
May 12 21:16:53 krowka systemd[1]: Sent message type=error sender=n/a destination=:1.173 path=n/a interface=n/a member=n/a cookie=49 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Unit name dbus�socket is neither a valid invocation ID nor unit name.
May 12 21:16:53 krowka systemd[1]: Failed to process message type=method_call sender=:1.173 destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/dbus_e2socket interface=org.freedesktop.DBus.Introspectable member=Introspect cookie=2 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a: Unit name dbus�socket is neither a valid invocation ID nor unit name.
```
The most obvious error is that we write non-utf8 to logs. `journalctl --all` is needed to show the logs.

But the more important thing is that we drop the dbus connection.

**Comment by keszybz** [comment]
`systemctl daemon-reexec` "fixes" the connection. `kill -SIGUSR1 1` doesn't.

**Comment by yuwata** [comment]
Hmm. I can reproduce this with 7cfcb25, but cannot with c1110f6. But I cannot find any difference between them... With what snapshot do you reproduce this?

**Comment by keszybz** [comment]
I'm not sure ;( I installed from some recent git but I'm not sure about the version. But it seems that reproduction is not 100% reliable. I now installed v238, and I see:
```console
# busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/dbus_2esocket org.freedesktop.systemd1.Unit SubState 
s "running"
# busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/dbus_e2socket org.freedesktop.systemd1.Unit SubState 
Remote peer disconnected
# busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/dbus_e2socket org.freedesktop.systemd1.Unit SubState 
(hangs)
```
This is probably a better reproducer and it shows that the bug is not recent.

**Comment by yuwata** [comment]
BTW, why writing non-utf8 causes dbus disconnection? I do not understand why #8981 partially fixes this...

**Comment by keszybz** [comment]
> why writing non-utf8 causes dbus disconnection

I tried to figure it out, but I didn't see any failure on systemd side. Maybe it's in the dbus daemon?

> `busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/dbus_e2socket <TAB>Failed to introspect object /org/freedesktop/systemd1/unit/dbus_e2socket of service org.freedesktop.systemd1: Unit name dbus\342socket is neither a valid invocation ID nor unit name.`

That's because we didn't redirect errors from `busctl introspect` to `/dev/null`. I now pushed another commit to do that.

**Comment by yuwata** [comment]
Hmm, if so, then I think the escaping should be done in `sd_bus_error_set()`.
