### ISSUE TITLE
systemctl not able to su -c  to locked account

### ISSUE THREAD

**Issue by mbijeesh** [systemd/systemd#8989]
User  test has  /sbin/nologin   shell. 
-----------------------
#Systemd unit file for Test
[Unit]
Description=Test Service
After=syslog.target network.target

[Service]
Type=simple

Environment=TEST_HOME=/usr/local/test
Environment=JAVA=/usr/java/test/bin/java

WorkingDirectory=/apps/test
ExecStart=/apps/test/bin/startup.sh
ExecStop=/apps/test/bin/stop.sh

UMask=0002

[Install]
WantedBy=multi-user.target

Note: Below is the startup script . 
### cat /apps/test/bin/startup.sh
PATH=/sbin:/usr/sbin:/usr/bin
export PATH
export TEST_HOME=/usr/local/test
export JAVA=/usr/java/test/bin/java

/bin/su - test -s /bin/bash -c "cd $TEST_HOME; $JAVA -jar ABC.jar &" && echo " " > /dev/null
## 
Please Note: As root user, I can able to run the script  /apps/test/bin/startup.sh   from command line without any issue. 

Just wonder why the script giving error while  running from systemctl. 

Error: 
 systemd[1]: Started Test.
 systemd[1]: Starting Test ..
 su[4710]: pam_unix(su-l:auth): auth could not identify password for [test]
 su[4710]: FAILED SU (to test) test on none
 startup.sh[4707]: Password: su: Permission denied
 systemd[1]: my-test.service: main process exited, code=exited, status=1/FAILURE
 systemd[1]: my-test.service: control process exited, code=exited status=1
 systemd[1]: Unit my-test.service entered failed state.
 systemd[1]: my-test.service failed.

**Comment by keszybz** [comment]
There is a problem with formatting of your report, various commands seem to have been interpreted as markdown. So I don't see the `su` command in the unit file, but guessing based on the logs you posted, `su` *is* started, runs PAM do determine if it should allow the action, and this fails and `su` throws an error. This means that your PAM configuration does not allow this.

My recommendation would be get rid of any `su` invocations from the unit file, and just use User= directly. Much cleaner and simple and more reliable.

**Comment by mbijeesh** [comment]
HI keszybz, 
Thanks for your response.  I modified  the formatting.   
The unit file calls the script   /apps/test/bin/startup.sh  and this script contains the line  "su - test" . Interesting thing is  I can run the  script from command line without any issue. 

For PAM , do you  have any known method to enable su  to a locked user ( user with /sbin/nologin) ?

**Comment by keszybz** [comment]
It works here:
```console
$ grep ladvd /etc/passwd
ladvd:x:47:47:LLDP/CDP sender for UNIX:/run/ladvd:/sbin/nologin
$ sudo systemd-run su - ladvd -s /bin/bash -c 'echo HERE'
Running as unit: run-r056bce245e6043bb8ae44469539532f9.service
$ journalctl
...
HERE
...
```
