### ISSUE TITLE
systemd-nspawn: Howto share directory with container?

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#899]
In Docker there is VOLUME or run -v to map directories between host and container. I need something like that too and I haven't found how you do that in systemd-nspawn.

Of course I tried `ln -s /var/lib/machines/arch/root` and `sudo chmod -R a+rx /var/lib/machines/` but the permissions always get updated/fixed by systemd at a guess. Or am I supposed to use `chattr` or something?

**Comment by rumpelsepp** [comment]
- http://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--bind=
- http://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--overlay=

**Comment by richardmaw-codethink** [comment]
I'm not sure raising an issue is the best way to get a question answered.

There's `--bind-ro` if you just want your container to be able to read the directory from the host, or `--bind` if you want the container to be able to write into it.

There's also `--overlay` and `--overlay-ro` for if you want to make the directory a union of multiple layers.

This is all documented in the man page.

**Comment by kaihendry** [comment]
Well, I looked through the man page but didn't make the connection. :disappointed:  I think I have it working now with:

```
cat /etc/systemd/system/systemd-nspawn@arch.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth --machine=%I --bind /home/hendry/root:/root/share
```

If it could be made more succinct, like can I append to ExecStart? Please let me know.

**Comment by rumpelsepp** [comment]
I really think the right place for support is the mailing list. :)

**Comment by poettering** [comment]
Yes, please use the mailing list for questions like this.

(To answer your question though: I intend to add support for `.nspawn` files that may be used to configure settings for nspawn, and that will automatically searched for -- using the usual search path logic, looking for the files in /etc/systemd/nspawn as well as in /var/lib/machines.)
