### ISSUE TITLE
Add ConditionSystemRamLessThen= (and MoreThen=) statement support

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#8990]
At the GNOME performance hackfest, one thing which are discussing is getting a GNOME session to run well in  1G RAM, one thing which came up is that enabling ZRAM helps a lot.

It would be nice to be able to have a .service file to automatically enable ZRAM on low RAM systems.

Which would require a ConditionSystemRamLessThen=2G statement, or something similar.

Assuming you (systemd upstream) are open to adding something like this, I'm willing to take a shot at implementing this. If we go that route it would be good to agree on the syntax before I implement this.

**Comment by lucaswerkmeister** [comment]
How does this play together with virtualization, e. g. if systemd is running in a container with memory limits? For the ZRAM use case, I assume you’d use `ConditionVirtualization=!container` anyways.

**Comment by mbiebl** [comment]
This inflation of Condition* makes me cringe. We already have way too many imho, 22 if I'm counting correctly.
https://www.freedesktop.org/software/systemd/man/systemd.directives.html#ConditionACPower=

**Comment by ramcq** [comment]
Perhaps from a distro perspective a less invasive way to achieve similar would be a generator which does it's own checking (whatever it wants) and enables a low memory target if conditions are met?

**Comment by poettering** [comment]
> How does this play together with virtualization, e. g. if systemd is running in a container with memory limits? For the ZRAM use case, I assume you’d use ConditionVirtualization=!container anyways.

So we already have an internal API called physical_memory() that when run in a container will read the container's cgroup memory limit instead. I guess for a container that's as "physical" a memory limit can get...

**Comment by poettering** [comment]
so i am not totally opposed to adding a condition for this, however two things:

1. It should be a bit more generic, i.e. support more than <=. We already have ConditionKernelVersion= that supports a number of different comparison operators, and I figure we should model this after those semantics.

2. I actually think @ramcq's idea is much nicer, and that way we wouldn't have to add to the inflation of condition types. I tiny C generator that pulls in zram under the right conditions sounds preferable to me and shouldn't be much slower.

That said, I am not strictly against adding a new condition for this. The code would be trivial, we have the right helpers internally already (i.e. the mentioned physical_memory() call).

**Comment by poettering** [comment]
Fix waiting in #12030
