### ISSUE TITLE
[RPi] [Raspbian] Incompatibility between current "systemd" and "raspi-copies-and-fills"

### ISSUE THREAD

**Issue by MichaIng** [systemd/systemd#8991]
**systemd version the issue has been seen with**
> 238

**Used distribution**
 > Raspbian Buster on RPi2

**Expected behaviour you didn't see**
With current [raspi-copies-and-fills](https://github.com/bavison/arm-mem) installed, `systemd-udevd` and with it all other systemd services (journald, timesyncd, ...) should run/start as expected.

**Unexpected behaviour you saw**
Systemd services fail to (re)start:
```
systemd-udevd[10856]: /lib/systemd/systemd-udevd: error while loading shared libraries: /usr/lib/arm-linux-gnueabihf/libarmmem.so: cannot restore segment prot after reloc: Operation not permitted
systemd-timesyncd[26811]: /lib/systemd/systemd-timesyncd: error while loading shared libraries: /usr/lib/arm-linux-gnueabihf/libarmmem.so: cannot restore segment prot after reloc: Operation not permitted
```

**Steps to reproduce the problem**
1. Install current `systemd` (234-238 at least, 232 works fine) and current `raspi-copies-and-fills` on RPi Raspbian, or simply upgrade to/use Raspbian Buster.
2. Do NOT reboot (will fail to boot: `[FAILED] Failed to start udev Kernel Device Manager`), just see systemd services failing to restart.

**Further reference**
- https://raspberrypi.stackexchange.com/questions/72594/failed-to-start-udev-kernel-device-manager
- https://github.com/bavison/arm-mem/issues/8

**Further info**
- I am not sure if this is something that need/can be fixed on systemd side or arm-mem side, so I thought it's best to report on both. Maybe it's also about the distro maintainers?
- I am not too experienced with compiling and don't expect it to be the issue, thus did not test to recompile arm-mem on the affected system. As said I first watched the error when apt dist-upgrading from Raspbian Stretch to Buster.

**Comment by L00ki82** [comment]
Can confirm. Especially the "Do NOT reboot" part. Very annoying.

**Comment by MichaIng** [comment]
@L00ki82 
> Especially the "Do NOT reboot" part.

Luckily I did not run into this. Systemd errors should be always handled BEFORE doing reboot.

**Comment by poettering** [comment]
Sorry, but this really looks like a toolchain issue with your distribution, i.e. a bug in the way they link their stuff? It's almost certainly not a systemd upstream issue as we just invoke the distro's linkers, and if they spit out .sos that don't work it's really on the distributions.

Please ping the distros about this, and let them escalate this back to us in the unlikely case there's actually something borked in this regard in upstream systemd. Hope that makes sense.
