### ISSUE TITLE
Error changing net interface name eth0 to eno1: File exists (on Lenovo ThinkStation P710)

### ISSUE THREAD

**Issue by haubi** [systemd/systemd#8994]
**systemd version the issue has been seen with**
> git master as of commit 8d29bef6b

**Used distribution**
 > Gentoo Linux, using systemd-udev only (not the full systemd).

**Expected behaviour you didn't see**
 > Predictable network interfaces names, probably `eno1` and `eno2`.

**Unexpected behaviour you saw**
 > One of "eth0" or "eth1" (toggling per boot) fails to be renamed to "enoX".
<pre>
# dmesg | grep eth
[    5.415874] e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) 6c:0b:84:aa:de:d2
[    5.416666] e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
[    5.417467] e1000e 0000:00:19.0 eth0: MAC: 11, PHY: 12, PBA No: FFFFFF-0FF
[    5.652896] igb 0000:08:00.0: added PHC on eth1
[    5.654403] igb 0000:08:00.0: eth1: (PCIe:2.5Gb/s:Width x1) 6c:0b:84:aa:de:d3
[    5.655196] igb 0000:08:00.0: eth1: PBA No: 000300-000
[    5.659213] r8169 0000:09:00.0 eth2: RTL8168e/8111e at 0xffffb501c7379000, 00:e0:4c:99:50:7b, XID 0c200000 IRQ 61
[    5.659981] r8169 0000:09:00.0 eth2: jumbo features [frames: 9200 bytes, tx checksumming: ko]
[   23.374715] igb 0000:08:00.0 eno1: renamed from eth1
[   23.396297] r8169 0000:09:00.0 enp9s0: renamed from eth2
[   23.396306] udevd[5910]: Error changing net interface name eth0 to eno1: File exists
[   23.396322] udevd[5910]: could not rename interface '2' from 'eth0' to 'eno1': File exists
</pre>

**Steps to reproduce the problem**
This is on a Lenovo ThinkStation P710, which happens to have these ethernet controllers installed:
<pre>
# lspci | grep Ethernet
On Board:
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection (2) I218-LM (rev 05)
08:00.0 Ethernet controller: Intel Corporation I210 Gigabit Network Connection (rev 03)
In a PCIe slot:
09:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
</pre>

The kernel drivers in use are `e1000e`, `igb` and `r8169`, respectively.

**Comment by floppym** [comment]
Can you provide the output of udevadm info for each device? For example:
```
udevadm info /sys/class/net/eno1
udevadm info /sys/class/net/eth0
udevadm info /sys/class/net/enp9s0
```

**Comment by haubi** [comment]
<pre>
# udevadm info /sys/class/net/eno1
P: /devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/eno1
E: DEVPATH=/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/eno1
E: ID_BUS=pci
E: ID_MODEL_FROM_DATABASE=I210 Gigabit Network Connection
E: ID_MODEL_ID=0x1533
E: ID_NET_NAME_MAC=enx6c0b84aaded3
E: ID_NET_NAME_ONBOARD=eno1
E: ID_NET_NAME_PATH=enp8s0
E: ID_OUI_FROM_DATABASE=Universal Global Scientific Industrial Co., Ltd.
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_VENDOR_ID=0x8086
E: IFINDEX=3
E: INTERFACE=eno1
E: MAJOR=0
E: MINOR=0
E: SUBSYSTEM=net
E: USEC_INITIALIZED=23503517
</pre>
<pre>
# udevadm info /sys/class/net/eth0
P: /devices/pci0000:00/0000:00:19.0/net/eth0
E: DEVPATH=/devices/pci0000:00/0000:00:19.0/net/eth0
E: ID_BUS=pci
E: ID_MODEL_FROM_DATABASE=Ethernet Connection (2) I218-LM
E: ID_MODEL_ID=0x15a0
E: ID_NET_NAME_MAC=enx6c0b84aaded2
E: ID_NET_NAME_ONBOARD=eno1
E: ID_NET_NAME_PATH=enp0s25
E: ID_OUI_FROM_DATABASE=Universal Global Scientific Industrial Co., Ltd.
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_VENDOR_ID=0x8086
E: IFINDEX=2
E: INTERFACE=eth0
E: SUBSYSTEM=net
E: USEC_INITIALIZED=23503532
</pre>
<pre>
# udevadm info /sys/class/net/enp9s0
P: /devices/pci0000:00/0000:00:1c.4/0000:09:00.0/net/enp9s0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.4/0000:09:00.0/net/enp9s0
E: ID_BUS=pci
E: ID_MODEL_FROM_DATABASE=RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
E: ID_MODEL_ID=0x8168
E: ID_NET_NAME_MAC=enx00e04c99507b
E: ID_NET_NAME_PATH=enp9s0
E: ID_OUI_FROM_DATABASE=REALTEK SEMICONDUCTOR CORP.
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Realtek Semiconductor Co., Ltd.
E: ID_VENDOR_ID=0x10ec
E: IFINDEX=4
E: INTERFACE=enp9s0
E: MAJOR=0
E: MINOR=0
E: SUBSYSTEM=net
E: USEC_INITIALIZED=23583535
<pre>

**Comment by floppym** [comment]
It seems like the firmware on that system is reporting two onboard NICs with the same index (1). I'm not sure how to further diagnose that.

As a workaround, you could remove `onboard` from the default `NamePolicy` setting, which should cause udev to use the `ID_NET_NAME_PATH` value instead. Just copy `/lib/systemd/network/99-default.link` to `/etc/systemd/network/99-default.link`, and remove the word `onboard`.

**Comment by yuwata** [comment]
So, should we tag this 'not-our-bug'?

**Comment by arvidjaar** [comment]
@haubi 

Could you show output of `dmidecode -t 41`?

**Comment by haubi** [comment]
<pre>
$ dmidecode -t 41
# dmidecode 3.1
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0050, DMI type 41, 11 bytes
Onboard Device
        Reference Designation:  GbE Controller
        Type: Ethernet
        Status: Enabled
        Type Instance: 1
        Bus Address: 0000:00:19.0

Handle 0x0051, DMI type 41, 11 bytes
Onboard Device
        Reference Designation:  GbE2 Controller
        Type: Ethernet
        Status: Enabled
        Type Instance: 1
        Bus Address: 0000:08:00.0
</pre>

**Comment by arvidjaar** [comment]
Well, `Type Instance` is supposed to be unique between all entries of the same `Type`. This is really a bug in your system firmware.

**Comment by haubi** [comment]
Accepted, and I can live with whatever workaround here, thanks a lot!
Still one question remains:
Is it possible for udev to detect this bug upfront?
If yes, I'd love to see some log message like "your system firmware has this or that bug, look for a workaround here and there".
Or even better, automagically drop `onboard` from the `NamePolicy` setting, with log message for the reason not using the `enoX` interface names.

**Comment by haubi** [comment]
Forwarded to https://bugzilla.kernel.org/show_bug.cgi?id=199813
