### ISSUE TITLE
systemd-nspawn: --pivot-root should work with --directory (useful for OSTree)

### ISSUE THREAD

**Issue by elboulangero** [systemd/systemd#8995]
**Is your feature request related to a problem? Please describe.**

I use `systemd-nspawn` to run an OSTree deployment. The documentation suggests:

    # systemd-nspawn -b -i ~/image.raw \
          --pivot-root=/ostree/deploy/$OS/deploy/$CHECKSUM:/sysroot \
          --bind=+/sysroot/ostree/deploy/$OS/var:/var

Which works great. However my rootfs is not in an image, but in a directory, so I use a similar command but I use the `-D` argument instead of `-i`, and it breaks.

    # systemd-nspawn -b -D ~/image \
          --pivot-root=/ostree/deploy/$OS/deploy/$CHECKSUM:/sysroot \
          --bind=+/sysroot/ostree/deploy/$OS/var:/var
    Directory ~/image doesn't look like an OS root directory (os-release file is missing). Refusing.

Looking into the code, it looks like nspawn tries to validate the root directory before executing the pivot root, so it can't work. See https://github.com/systemd/systemd/blob/8d29bef6b5f33e2387f52af11140b1a259d971cf/src/nspawn/nspawn.c#L3925.

**Describe the solution you'd like**

So I'd like this command to work :)

One straight-forward possibility could be to disable this check in case the pivot-root option is used.

Another (better?) option could be to do the check in the pivot-root directory rather than the arg_directory.

Any thought on that? I can submit a patch if you tell me how you'd prefer this to be done.

**Comment by elboulangero** [comment]
You're right about mounting directly the actual root with `--directory`. However...

    # systemd-nspawn -D image/ostree/deploy/${OS:?}/deploy/${CHECKSUM:?}.0
    Spawning container 1676cc9ad3839149545d98e8d262754188b04ab2f451214002a4a64c7a694d98-d9a90988fcb65f57 ...
    Failed to register machine: Invalid machine name

What happens is a bit silly, it just happens that the OSTree actual root is a directory with a long long name, and it's not suitable as a machine name. So we need the additional `--machine` option.

    # systemd-nspawn --machine ostree -D image/ostree/deploy/${OS:?}/deploy/${CHECKSUM:?}.0
    IT WORKS !

Still interested in a patch? It would improve usability a bit, but we can also live without, up to you.

**Comment by poettering** [comment]
Yeah, the `--machine=` thing is a good point.

So yes, would love to take a patch that fixes things so that we validate the OS tree that is located at the concatenation of the paths referenced by --directory= and --pivot-root= if the latter is set. That should fix everything for you, right?

**Comment by poettering** [comment]
#9049 is merged now. Closing. Thanks!

**Comment by elboulangero** [comment]
Thanks!
