### ISSUE TITLE
I use systemd through nbd, boot card does not move in the switch-root, nfs also exist in this way

### ISSUE THREAD

**Issue by bbbest** [systemd/systemd#8999]
**systemd version the issue has been seen with**
> ...
Not get it.

**Used distribution**
 > …
My idea is to use an external file system after Linux boot, systemd is very powerful, but I did not find how to use this.
I used qemu-nbd to mount the qcow2 file system in centos7. When I started, systemd killed all the processes and sockets, including the nbd process, so the boot turned up a problem in switch-root. "block nbd0: Attempted send on Closed socket".

**Expected behaviour you didn't see**
 > …
Can mount external file system normally and boot.

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
1. Modify the kernel file Add modprobe nbd in the dracut-initqueue script, and qemu-nbd -c /dev/nbd0 /dev/mapper/work/nbd0p1;

2.mount /dev/nbd0p1 /sysroot, where /dev/nbd0p1 is a qcow2 file system;

3. Restore the kernel file and put it back;

4. boot stopped at the switch-root, open the debug information found error: "block nbd0: Attempted send on Closed socket".

**Comment by bbbest** [comment]
@yuwata 
The problem is described in the title, I use systemd through nbd, boot card does not move in the switch-root, nfs also exist in this way

**Comment by bbbest** [comment]
@yuwata 
My idea is to use an external file system after Linux boot, systemd is very powerful, but I did not find how to use this

**Comment by yuwata** [comment]
@bbbest Please fill the all questions in the template...

**Comment by yuwata** [comment]
@bbbest 
> I don't know if this is a bug, but I can't find a solution

Then, please use our mailing list. This is an issue tracker, not support forum.

**Comment by bbbest** [comment]
OK! Get it. Thank you.

**Comment by bbbest** [comment]
@yuwata 
I filled the all questions in the template
