### ISSUE TITLE
networkd fails to setup bond when mode doesn't support packets_per_slave

### ISSUE THREAD

**Issue by mstarostik** [systemd/systemd#90]
systemd-networkd tries to set packets_per_slave on a bond netdev even if its mode doesn't support it.  This leads to the device not being created:

trunk (uninitialized): option packets_per_slave: mode dependency failed, not supoorted in mode 802.3ad(4)

The man page says PacketsPerSlave option "has effect only in balance-rr mode".  That's right, but in addition to that networkd must not try to set it (even to networkd's default) in other modes.

Kludgy workaround: specifying a value > 65535 in the .netdev file will skip setting the option.

**Comment by teg** [comment]
Thanks for the report. Does the attached PR fix things for you as expected?

**Comment by mstarostik** [comment]
Yes, it does. Thanks!
