### ISSUE TITLE
Respect unit file loading priorities while following Symlinks (RFE)

### ISSUE THREAD

**Issue by a-darwish** [systemd/systemd#902]
Hi everyone,

We were hit by this problem badly in our Yocto distribution image building process. For boot time optimizations, we load the `bluetoothd` daemon (and the kernel modules it requires) only using bus-activation.

The D-Bus service file for the unit looks like:

```
$ cat /usr/share/dbus-1/system-services/org.bluez.service 
[D-BUS Service]
Name=org.bluez
Exec=/bin/false
User=root
SystemdService=dbus-org.bluez.service
```

Naturally, the Yocto system image also have the following symbolic-link by default:

```
ls -l /etc/systemd/system/dbus-org.bluez.service 
/etc/systemd/system/dbus-org.bluez.service -> /lib/systemd/system/bluetooth.service
```

Then, we add our own version of `bluetooth.service` under /etc/systemd/system. Sysmted correctly detects that we've overriden the service:

```
$ systemd-delta
[OVERRIDDEN] /etc/systemd/system/bluetooth.service → /lib/systemd/system/bluetooth.service        

--- /lib/systemd/system/bluetooth.service                                                         
+++ /etc/systemd/system/bluetooth.service                                                         
@@ -1,11 +1,13 @@                                                                                 
 [Unit]                                                                                           
 Description=Bluetooth service                                                                    
+Wants=bluetooth-init.service                                                                     
+After=bluetooth-init.service                                                                    

 [Service]                                                                                  
 Type=dbus                                                                                  
 BusName=org.bluez                                                                          
+ExecStartPre=/opt/script/load_bluetooth_modules.sh                                         
 ExecStart=/usr/sbin/bluetoothd -n                                                          

 [Install]                                                                                        
-WantedBy=bluetooth.target                                                                  
 Alias=dbus-org.bluez.service                                                               
```

[ Yes, a drop-in would've been better, but this is outside the scope of this RFE :-) ]

Now when our bluetooth.service get activated over D-Bus, systemd actually loads `/lib/systemd/system/bluetoolth.service` instead of our own version under `/etc`.

While this seems a little bit in contradiction with the `systemd.unit(5)` documentation:

```
Unit files are loaded from a set of paths determined during compilation,
described in the two tables below. Unit files found in directories listed
earlier override files with the same name in directories lower in the list.
```

It indeed goes _in line_ with the same documentation stating that:

```
Unit file may include an "[Install]" section, which carries installation information
for the unit. This section is not interpreted by systemd(1) during runtime. It is
used exclusively by the enable and disable commands of the systemctl(1)
tool during installation of a unit
```

This leads to inconsistent situations: activating the service using `$ systemctl start bluetooth` leads to different behavior from activating the same service from over D-Bus (!)

Given such inconsistencies, shouldn't systemd unit file loading priority schemes (`/etc` then `/run` then `/lib`) be respected in all cases, _regardless of the file system symbolic links state_?

If this RFE is possible from a technical and runtime ABI perspective, this should provide:
- Consistent behavior between different unit activation methods: manual based (`systemctl start`), bus-based (`dbus-*.service`), run-time unit directives based (`Requires=`, `Wants=`), and static time didrectory based (`*.wants/`, `*.requires/`) activation, regardless of the filesystem symbolic links state
- More synchronization with the dynamic nature of Unit files and supporting tools like `systemd-delta`
- Less room for hard-to-find configuration bugs
- Not having to do `systemctl disable` then `systemctl enable` after adding an /etc unit file that overrides the `[Install]` section

Thank you,

**Comment by keszybz** [comment]
Still the same with v235, yikes.

**Comment by keszybz** [comment]
This should be fixed by 0c062fd3eb3988822ffcf1f87c45f7c168fe92ef. If not, please holler.

**Comment by mbiebl** [comment]
@keszybz I came here because of #4917 still being an issue with v242.
Either this bug report should be reopened or #4917 is a separate issue in which case #4917 should be reopenened.

**Comment by keszybz** [comment]
I think #11972 has the same underlying issue. I have a patchset half-ready for it, I'll try to submit it for review in the next few days, and then we can see if any problems remain.

**Comment by mbiebl** [comment]
@keszybz ok, great. Please notify me when you submit that PR. I'm happy to test if it fixes my test case.
