### ISSUE TITLE
resolved uses synthethic ".local" PTR answers where DNS server supplied ones existed

### ISSUE THREAD

**Issue by Prototik** [systemd/systemd#9037]
**systemd version the issue has been seen with**
> 238.76

**Used distribution**
 > ArchLinux x86_64

I have setup with 2 machines (kenny & eric), both uses absolutely same network configuration, dns entries fetched via dhcp. `domain` entry (aka `search` in resolv.conf) retrieved also via dhcp.  
I got very strange responses via resolved proxy, but correct from upstream servers:
```
kenny $ systemd-resolve --status | grep 'DNS Servers'
         DNS Servers: 10.0.0.1
kenny $ dig +noall +answer -x 10.0.0.30 @10.0.0.1
30.0.0.10.in-addr.arpa.    86400    IN    PTR    kenny.local.
kenny $ dig +noall +answer -x 10.0.0.30 @127.0.0.53
30.0.0.10.in-addr.arpa.    30       IN    PTR    kenny.
```
```
eric $ systemd-resolve --status | grep 'DNS Servers'
         DNS Servers: 10.0.0.1
eric $ dig +noall +answer -x 10.0.0.40 @10.0.0.1 
40.0.0.10.in-addr.arpa.    86400    IN    PTR    eric.local.
eric $ dig +noall +answer -x 10.0.0.40 @127.0.0.53
40.0.0.10.in-addr.arpa.    30       IN    PTR    eric.
```
Probably I missed something, but from my point of view resolved should work only like caching server and don't modify answers at all.

**Expected behaviour you didn't see**
 > resolved answers should matches upstream server

**Unexpected behaviour you saw**
 > answers doesn't match

**Comment by poettering** [comment]
Hmm, so ".local" is the mDNS domain, resolved will never resolve that via unicast DNS by default. Also note that resolved synthesizes RRs for the local hostname/addresses if needed.

I am not entirely sure what your setup is like, please provide the full "systemd-resolve --status" output. Also, turn on debug logging in resolved (for that, add `Environment=SYSTEMD_LOG_LEVEL=debug` to its unit file as drop-in via `systemctl edit systemd-resolved` in the `[Service]` section and restart it), and provide the exact logs this results in on lookup.

**Comment by Prototik** [comment]
`.local` isn't mDNS domain but regular zone, managed by upstream server. I think main problem that
> resolved synthesizes RRs for the local hostname/addresses if needed

but "if needed" broken here - upstream server able to handle this requests.

Both servers have same `systemd-resolve --status` [output](https://pastebin.com/Ns0E4HnT)

**Comment by poettering** [comment]
so this is always going to be messy: .local is the mdns domain as per IANA:

https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml

if you use it for unicast DNS then this is always going to be a mess, but that's really the fault of the local setup

We do provide some limited support for looking up domains in .local if you tell resolved to explicitly route .local to unicast DNS via the search domain/route domain logic, but for the local IP addreses/hostname I am pretty sure we should always synthesize things anyway.

The thing is that whatever you do, you'll get a mixture of mDNS and classic DNS anyway if you use .local.

Or in other words: I think ew should just be honest, this is not something we are going to address. it's a problematic setup, but i don't think resolved should try to work around it more than it already does.
