### ISSUE TITLE
hwdb API

### ISSUE THREAD

**Issue by ForTheReallys** [systemd/systemd#9048]
I've just run across hwdb for the first time and it (although a bit confusing at first) was exactly the solution I was looking for.  However, I would like to be able to interact with it using some sort of API and couldn't seem to find anything that would allow me to read or edit hwdb.bin programatically.  Would this be a possibility in the future with libsystemd?

**Comment by boucman** [comment]
could you detail your use-case a bit more ?

**Comment by poettering** [comment]
libudev already contains an API for accessing hwdb directly. Note however that usually apps wouldn't do that, and instead simply rely on the fact that the data from the hwdb is already attached to the devices automatically, and hence can just use the usual device property API for that.
