### ISSUE TITLE
Add support for alternate debuggers to coredumpctl

### ISSUE THREAD

**Issue by nmiell** [systemd/systemd#9056]
`coredumpctl` has a `gdb` subcommand that invokes gdb. I'd like to be invoke other debuggers e.g. lldb or ddd, etc.

I suggest that the `gdb` subcommand be renamed to `debug`, a `--debugger=` option be added that allows the user to specify which debugger to use, and the addition of some way to configure the default debugger per-user.

**Comment by nmiell** [comment]
oh, this was added a month ago.

**Comment by yuwata** [comment]
Already implemented by c5896b6a8cfcfd1b94f25450a96a1411384f1108 (#8744).
