### ISSUE TITLE
Export the inotify event type as an environment variable

### ISSUE THREAD

**Issue by thedrow** [systemd/systemd#9066]
**Is your feature request related to a problem? Please describe.**
I want to be able to react only to certain inotify events.
Right now the oneshot service I'm triggering when a path changes runs when a file is deleted which is not desirable.
I want to run the oneshot service only when files are created.

**Describe the solution you'd like**
Since I think I'd rather avoid extending the path unit I want systemd to export an environment variable containing the type of inotify event that triggered the oneshot service related to that path unit.
The oneshot service can decide what to do based on the event that occurred.

**Describe alternatives you've considered**
I considered extending the syntax of the path unit file but it seems unnecessary (and harder to implement).

**Comment by poettering** [comment]
Well, activation is coalesced, which means multiple subsequent events might result in a single invocation. What would you tell the service in that case?

**Comment by thedrow** [comment]
The latest event. If a file was deleted and then recreated and we want to react only when a file is created that makes sense.
Alternatively, export all coalesced events separated by ',' and let the user decide.

**Comment by thedrow** [comment]
@poettering What do you think?

**Comment by poettering** [comment]
This is necessarily racy, as we'd always have to coalesce all queued events on activation and would lose everything after the activation is queued until the triggered service's dependencies are being fulfilled, the service starts up, runs and shuts down again. 

I am not convinced that we should add such necessarily racy interfaces

**Comment by thedrow** [comment]
[Watchman](https://facebook.github.io/watchman/) coalesces events of a single type.
If you think that this behavior is more correct, that's fine but it will take far more work to implement.
It means we need to create more types for specific file system events such as FileOpened, FileClosed etc.

**Comment by keszybz** [comment]
I agree that the environment interface is not very appealing. systemd.path was always more about starting a service lazily, and less about providing an accurate response for multiple triggers. In particular the service that is started, will always be started just once, so even if it is short running, if an another event came in quickly, it'd necessarily have to be ignored (or cached somehow in systemd, but there is no limit to how many events can come in, so it's also not very appealing). All in all, such detailed handling of inotify events is not something that should be done in pid1. Instead, it should be handled by the service itself.

**Comment by elgow** [comment]
I want to second/upvote this issue. Not having any indication of either the type of event or the file that triggered it severely limits the usefulness of the systemd.path mechanism. Almost any form of coalesced event info would be better than no info at all.

**Comment by pHiney** [comment]
I'd like to upvote this too.

As incron and inotify tools, et al are in EPEL, they are not available to some of us.

Having the file(s) that triggered it and the event would be useful. Perhaps as a "Specifier" for us to pass to the script.

I've been experimenting today and using a PathChanged, the script triggers when i delete the files too.

So if I had a script to process incoming files, I would need to move them out of the incoming directory for processing at the first instance, so any subsequent calling of the script won't try to reprocess the same files.

So with that in mind, if I don't know what files triggered the script, then I'm going to move all files, possibly including files that are still being copied in.

Coming from the precision of incron, this seems too airy fairy.
I note your comment about "starting a service lazily" and I don't need instantaneous, just the understanding of which files were responsible for the trigger.

Testing today revealed it triggered every three files but sometimes four (a "for" loop, copying ks_post.log to unique filenames). 

I'm aware of your concerns about things becoming racy but if someone abuses this for /var/log, they deserve what they get.

In our situation; files are coming in, in an async fashion, sometimes in multiples. I have to program for the worst condition. If I need to "sleep" to do time comparisons on a file to establish if it's available, then I may as well use cron and run minutely.

If there is way to do this already, please let me know.

Thanks for Your consideration.

**Comment by thedrow** [comment]
> All in all, such detailed handling of inotify events is not something that should be done in pid1. Instead, it should be handled by the service itself.

User services don't run on PID 1 as far as I know.

**Comment by keszybz** [comment]
I think we could export the triggering event. This would be "race free" in the sense that there's a single event that caused **us** to start the service. I don't think we should do any coalescing, because that is complicated and creates too many problems.

I'd be happy to review a patch if somebody writes it ;)

**Comment by thedrow** [comment]
So we shouldn't use this feature for anything important? Is that what you're saying?
I don't see how this feature is useful at all without coalescing. What are its usecases?

**Comment by pHiney** [comment]
Unless incron (and any supporting package) is picked up by RedHat and brought into the fold, the main usecase is "incron". One file, one instantiation of the script.service.

but with or without coalescing, the script still needs to know what file(s) triggered the event.

And if it shouldn't be running as pid 1, then why is the service there ?

**Comment by keszybz** [comment]
Well, it'd be useful for *some* cases. The general story with inotify-style notifications is that there *always* a possibility of losing events, so there's the implementation must always be prepared to restart processing if the event queue overflows. This would be just a more extreme case of this, where the overflow would occur immediately on the second event. How much of a problem that would be depends a lot on the service: I can imagine that for example a printing service could immediately start printing the first job, and while the hardware is busy, figure out at leisure what the other jobs, if any, will be.
