### ISSUE TITLE
globbing syntax for "systemctl start" ignores enabled instantiated units unless `--all` is supplied

### ISSUE THREAD

**Issue by dkg** [systemd/systemd#9080]
**systemd version the issue has been seen with**
238-4

**Used distribution**

debian buster+unstable

There is a `kresd@.service` template.    Here's a transcript of me enabling units that are not subsequently started by `systemctl start 'kresd@*.service'`:

```
0 root@alice:~# systemctl --all | sed 's/[[:space:]]\+/ /g' | grep kresd | grep service
 kresd@1.service loaded active running Knot DNS Resolver daemon 
0 root@alice:~# systemctl enable kresd@2.service
Created symlink /etc/systemd/system/multi-user.target.wants/kresd@2.service → /lib/systemd/system/kresd@.service.
0 root@alice:~# systemctl --all | sed 's/[[:space:]]\+/ /g' | grep kresd | grep service
 kresd@1.service loaded active running Knot DNS Resolver daemon 
 kresd@2.service loaded inactive dead Knot DNS Resolver daemon 
0 root@alice:~# systemctl start 'kresd@*.service'
0 root@alice:~# systemctl --all | sed 's/[[:space:]]\+/ /g' | grep kresd | grep service
 kresd@1.service loaded active running Knot DNS Resolver daemon 
 kresd@2.service loaded inactive dead Knot DNS Resolver daemon 
0 root@alice:~# 
```

I would have expected that after the invocation of `start`, `kresd@2` would have also been running.

**Comment by dkg** [comment]
i'm seeing the same behavior on debian stable with systemd `232-25+deb9u3`, if that matters.

**Comment by dkg** [comment]
from #6379, it looks like `start` works if i add the `--all` parameter.  thanks to @grawity  for the pointer.

Why wouldn't this be the default behavior if there is a templated wildcard glob?

**Comment by dkg** [comment]
also, the documentation for `--all` in `systemctl(1)` doesn't mention that it has this special power.

**Comment by poettering** [comment]
What are you precisely trying to do here? I mean, the globbing for start is conceptually very questionnable anyway, as it will only deal with loaded units, not with what is available on disk, which might be much more. I figure we should print a big fat warning about this when people make use of this for the "start" word...

(This is different for "stop" and "reload" and all the other words, since they generally operate on already loaded units, while "start" will load stuff from disk if needed)

**Comment by tomaskrizek** [comment]
The idea is to start all instances of a service that were enabled prior to issuing the start command.

We use this approach in Knot Resolver, where users may want to have `nproc` instances running. Using `systemctl start --all 'kresd@*.service'` is then a shorthand they can use to start the instances that have been enabled, but not started yet.

The use-case is described in the *Multiple instances* section of [`kresd.systemd.7`](https://gitlab.labs.nic.cz/knot/knot-resolver/blob/master/doc/kresd.systemd.7).

**Comment by grawity** [comment]
I still suggest that you should use a target for this. Then you'll be able to just start the `.target` unit:

    multi-user.target
    └─ kresd.target
       ├─ kresd@foo.service
       └─ kresd@bar.service

(The services should have `[Install] WantedBy=kresd.target`, while the target itself should – I think – be enabled statically via /lib.)

**Comment by gingerlime** [comment]
I know this is open for a while, but I'm also bumping into this and starting to bang my head against the wall a bit... 

Like @tomaskrizek I have a few services using a template, e.g. `sidekiq@batch.service`, `sidekiq@mailer.service` all symlinking to `sidekiq@.service`. I want to be able to stop/start/reload/restart them as a group somehow, without having to specify each individual service...

I think that using a parent target using `WantedBy` or using `PartOf` kinda works, but then it won't propagate reloads for example... (also tried using `ReloadPropagatedFrom` on the children, which doesn't seem to help, or maybe I did something wrong?)

Would appreciate some guidance here if someone has some working examples or anything else that could work here...

**Comment by keszybz** [comment]
Let's continue the discussion in #6379.
