### ISSUE TITLE
Please change default net.ipv4.tcp_ecn to 1

### ISSUE THREAD

**Issue by SimonIremonger** [systemd/systemd#9087]
Following on from closely related issue #5090 https://github.com/systemd/systemd/issues/5090 that was merged in systemd --

Since systemd has taken-up enabling fq_codel queueing by default, I would like the closely-related matter of ECN on outgoing connections enabled similarly.
This, appears to be the 'final part of the puzzle' of bufferbloat-fixes so far as I can see, allowing active-queue-management systems like fq_codel to 'mark' parkets on congested-queues, rather than draopping packets to indicate congestion.

Back in 2000's there were issues with network kit having TCP-option-ordering and ECN-intolerance issues, but these issues have long since virtually-disappeared, the kernel has enabled SACK, DSACK, and gained ECN-intolerance-fallback (enabled by default), many of us have turned on ECN for years, and it is high-time we started doing so to 'complete' bufferbloat-implementation, essentially.  [1] below bufferbloat notes  and [2] below recent apple-adoption presentation.

Ultimately, I would like is for the kernel upstream to enable fq_codel and ecn queueing in the kernel by default, but enabling especially ECN in end-hosts running systemd would be a huge bonus to ECN-adoption in the short-term.

[1] https://www.bufferbloat.net/projects/bloat/wiki/Linux_Tips/
[2] https://www.ietf.org/proceedings/98/slides/slides-98-maprg-tcp-ecn-experience-with-enabling-ecn-on-the-internet-padma-bhooma-00.pdf

**Comment by SimonIremonger** [comment]
(correction #5090 wasn't a merged-change per-se, was a different merge to get fq_codel enabled via systemd, but anyway, ECN-query still stands...).

**Comment by poettering** [comment]
Could you prep a PR?

**Comment by phomes** [comment]
A trivial patch is waiting in #9143.
Changing the default in the kernel would be better, but perhaps doing it here will help prove that the problems are resolved.

**Comment by SimonIremonger** [comment]
I agree entirely about amending in the kernel eventually, but that 'somebody needs to just-do-it, wider-deployment and see for the time-being'!.   Ubuntu similarly sound interested to try out tcp_ecn on 18.10 (non-LTS) for the same reasons.  I may then see what I can get into debian.

The text proposed is essentially fine, I agree.  Thankyou for agreeing!.  If we get complaints they will likely be along the lines of "very slow connectivity" due to the tcp_ecn_fallback mechanism activating...

p.s.  TRANSPIRES that a likely later bufferbloat improvement is to default tcp_congestion_control to bbr, but this should not be done until the BBR implementation is confirmed responsive to notifications from ECN [I should ask some questions in the relevant group]...
Ultimately all 3 (fq_codel, tcp_ecn, bbr) should become default upstream with any luck.  There is also a 'cake' qdisc being worked on for gateway-routers connected to upstream-ISP-modems, but thats' not for general-purpose-machines yet aiui!.

**Comment by ivanbaldo** [comment]
Note that bbr should be used with fq not fq_codel AFAIK.

**Comment by SimonIremonger** [comment]
Apparently this was down to fq_codel not implementing pacing in thp ast, I got the impression this was also fixed, but fair-point noted,  BBR needs checking for BOTH fq_codel and ECN compatibility before recommending for deployment...

**Comment by middleagedman** [comment]
Enabling this by default caused my download speeds to drop significantly, from 300Mbit/s to 50Mbit/s.  I had to set it back to 0.  I have an ASUS RT-3200 router.  This happened on 2 different devices, so I don't know if this was a good idea

**Comment by SimonIremonger** [comment]
middleagedman:  Bear in mind ECN is usually enabled on inbound connections by default, so any bug in the ASUS firmware can be triggered even without outbound ECN.
I notice there have been a lot of firmware-updates for this RT-3200 router, please do try updating to latest and trying again -- if this does not fix it, do raise issue with ASUS support about this.
I did eventually get Draytek to acknowledge a worse ECN-intolerance issue a decade or so ago, an these things seem to have been long-since fixed.

**Comment by middleagedman** [comment]
Thanks.. Yes I have my router actually updated to the latest Merlin firmware for the  rt-3200, so that could be an issue for some reason.

**Comment by SimonIremonger** [comment]
@middleagedman 
Please test with some completely-different-router to confirm the problem is/isn't the router/firmware rather than up the chain in ISP.
Then post what you can here about the details of router or ISP that proved to be the problem:-
https://www.reddit.com/r/linux/comments/933vys/is_tcp_ecn_still_a_problem_today/
I'll try to collate responses into bufferbloat wiki eventually.

**Comment by SimonIremonger** [comment]
@middleagedman
Has this been sorted on your AsusWRT-Merlin these days?
My suspicion is that "flow offloading" wasn't working and you are experiencing software-handled data-flow...

**Comment by mrc0mmand** [comment]
> When should this topic be re-opened, and what needs doing in terms of Linux ECN fallback/adaptability ?

Opening a new issue/RFE would be a first good step, with some justification (why it should be re-enabled, have the outstanding issues been resolved, what needs to be done if they haven't, etc.). Having a discussion in an issue that's several years old usually leads nowhere.
