### ISSUE TITLE
udev reports HID device's idVendor/idProduct with USB, but not with BT connection 

### ISSUE THREAD

**Issue by hzulla** [systemd/systemd#9101]
**systemd version the issue has been seen with**
>237

**Used distribution**
 >Ubuntu 18.04

**Expected behaviour you didn't see**
 > The PS3 gamepad will connect with a Linux computer either [via USB](https://github.com/torvalds/linux/blob/7fbb6157630f2ba6ee355689061f9596b84373ef/drivers/hid/hid-sony.c#L3038) or [via Bluetooth](https://github.com/torvalds/linux/blob/7fbb6157630f2ba6ee355689061f9596b84373ef/drivers/hid/hid-sony.c#L3048) - the kernel driver for this HID device uses the same HID idVendor/idProduct combination to identify it.
> I would expect a udev rule with `ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0268"` to match this device when connected with USB or Bluetooth.

**Unexpected behaviour you saw**
 > The rule mentioned above will match when the device is connected via USB, but not when it is connected via Bluetooth. I can only use `ATTRS{name}=="Sony PLAYSTATION(R)3 Controller"` to match for both connection types, but the expected `idVendor/idProduct` values of 0x054c/0x0268 are only matched with USB.
> This is unfortunate, as the `ATTRS{name}` attribute is less specific. Some vendors use identical names for different products, this includes Sony where two different devices both share the name `"Sony Interactive Entertainment Wireless Controller"`.

**Steps to reproduce the problem**
> - Connect a PS3 gamepad controller via USB.
> -  `udevadm info -a -n /dev/input/js0` and you will find `ATTRS{name}=="Sony PLAYSTATION(R)3 Controller"` and the `idVendor/idProduct` values of 0x054c/0x0268.
> - Now connect the same gamepad via Bluetooth.
> -  `udevadm info -a -n /dev/input/js0` and you will find `ATTRS{name}=="Sony PLAYSTATION(R)3 Controller"`, but the device's `idVendor/idProduct` values are nowhere to be seen.

**Comment by hzulla** [comment]
Output of `udevadm info -a -n /dev/input/js0` on my machine
- connected via USB: [udev-sony-usb.txt](https://github.com/systemd/systemd/files/2044163/udev-sony-usb.txt)
- connected via Bluetooth: [udev-sony-bluetooth.txt](https://github.com/systemd/systemd/files/2044164/udev-sony-bluetooth.txt)

**Comment by hzulla** [comment]
Also tested with Raspbian (systemd 232), same behaviour there.

**Comment by poettering** [comment]
Well, idVendor and idProduct are the kernel's sysfs device attribute file names. Are you sure that bluetooth devices even expose these concepts under these names?

udev doesn't make up sysfs attributes, it just exposes what the kernel provides. Please ping the kernel community about this hence.

Or are you saying udev is not exposing things properly that the kernel provides under the same names on both busses?

**Comment by hzulla** [comment]
I'll have to check on that. What I can tell you is that the hid drivers use these concepts to probe devices [via USB](https://github.com/torvalds/linux/blob/7fbb6157630f2ba6ee355689061f9596b84373ef/drivers/hid/hid-sony.c#L3038) and [via Bluetooth](https://github.com/torvalds/linux/blob/7fbb6157630f2ba6ee355689061f9596b84373ef/drivers/hid/hid-sony.c#L3048) - so at least these values are used internally for both busses.

**Comment by hzulla** [comment]
Yes, apparently bluetooth devices do not export these values to sysfs. I have thus [reported this to Bugzilla](https://bugzilla.kernel.org/show_bug.cgi?id=199885), in the hope that the bluetooth maintainers find it a feature worth implementing.

**Comment by poettering** [comment]
OK, let's close this here then.

**Comment by hzulla** [comment]
Thanks for clarifying.

**Comment by hzulla** [comment]
Okay, an update. The values are there. It appears that drivers/input/input.c creates a sysfs subdirectory "id" which is then populated with the values I want to match against.

But unless I misunderstand things, udev cannot match against these.

What is the proper way to address this? Should udev allow matching against values in subdirectories (maybe only subdirectories named "id") or is this something that should be changed in input.c?

**Comment by poettering** [comment]
ATTRS{} takes relative paths as arguments which may contain subdirs if that's needed.

**Comment by hzulla** [comment]
Thanks. But then it appears that `udevadm info` is incomplete or misleading. It says to the user:

> Udevadm info starts with the device specified by the devpath and then
> walks up the chain of parent devices. It prints for every device
> found, all possible attributes in the udev rules key format.
> A rule to match, can be composed by the attributes of the device
> and the attributes from one single parent device.

...but then fails to report "all possible attributes" because some of those possible attributes hide behind a subdirectory.
