### ISSUE TITLE
journalctl -f  doesn't work if system clock is turned back after reboot

### ISSUE THREAD

**Issue by faithlesstomas** [systemd/systemd#9108]
**systemd version the issue has been seen with**

238

**Used distribution**

Debian stable/testing/unstable

**Expected behaviour you didn't see**

`journalctl -f / --follow` should follow new entries in journal

**Unexpected behaviour you saw**

When the last journal entry is _in the future_ w.r.t. running machine time after reboot `journalctl -f` doesn't really follow new entries in the journal until the time in current boot reaches the time of last entry from previous boot.  

Side note: 
Also if one runs journalctl with no options, one can see that new entries don't vanish, they just appear in different positions (according to their time), separated by **--Reboot--** statement.

Simple workaround is to run journalctl with boot option, which will show only last boot: `journalctl -f -b`.

**Steps to reproduce the problem**

1. Stop journal service.
1. Change/rewind machine local time to some in some past time (e.g. with `timedatectl`).
1. Reboot.
1. Run `journalctl -f` 
1. Generate some journal entries.

**Note:** This issue is strictly related to https://github.com/systemd/systemd/issues/6213.

**Comment by poettering** [comment]
Well, the journal interleaves log data based on timestamps. It prefers to use monotonic clock timestamps over wallclock timestamps but that only works if the log data originates from the same boot. Now, in your case you reboot, hence the wallclock timestamps is what matters, and if that is reset then the interleaving will be done according to the reset times, which is what you see...

I am not sure there's much we can or should do about that. I mean, we don't require that the realtime clock really is correct, but we do require that it doesn't jump backward, i.e. is strictly monotonic, and we do provide concepts to make sure it is (see timesyncd, which will store a timestamp file on disk, using it to guarantee monotonicity of the clock even on systems that have no battery buffered RTC). Such a requirement is not particularly exotic btw, it's built into tons of UNIX tools, i.e. many tools require monotonically increasing timestamps, for example build systems or MTA/MUAs require mtimes that work.

**Comment by faithlesstomas** [comment]
First of all, I wouldn't say that this issue is a duplicate of #662 - it only covers one aspect of this issue, i.e. problem with boot ordering, but this issue is more about faulty `journalctl -f`having trouble with non-monotonic time between boots. Same source of the problem does not make two issues the same, right? 

But anyway, going back to the solution of the issue...
In the world of embedded systems, it's sometimes necessary to jump with the time back and forth, e.g. for test purposes. So, If you say that there's not much to do because journal require RTC to be monotonic in the machine, I would say that this should be redesigned - logging system, or its API or displaying program can't rely on this assumption. End user should be allowed to do what he wants with the system clock and logging system should deal with it gracefully, not mentioning it should follow the principle of least surprise.

This issue isn't a complaint about API, but maybe it should, as it was in #6213, since both issues seems to originate from same problem: i.e. requirement of having monotonic machine time, shouldn't it?
