### ISSUE TITLE
Need help with keyboard script

### ISSUE THREAD

**Issue by jeremy447** [systemd/systemd#9109]
Hello,

I use a script to configure the keyboard of my HP Chromebook 14 but it doesn't work anymore with Fedora 28.

$ sudo localectl set-x11-keymap fr chromebook 
Failed to set keymap: Specified keymap cannot be compiled, refusing as invalid.

Do you know what's wrong with it ? https://pastebin.com/fbgrQsq7

Thank you !

**Comment by yuwata** [comment]
I cannot reproduce this with Fedora 28 x86_64 with recent git snapshot. The `localectl` command you specified works fine for me. If I understand correctly, the script modifies the data given by xkeyboard-config.rpm. It may break the database.
