### ISSUE TITLE
kdbus breaks GPaste gnome-shell extension

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#912]
When the session is using kdbus, the GPaste gnome-shell extension is broken. It does not update itself when the gpaste-daemon state changes (e.g. on copy to clipboard) nor does it react to accelerators.

This seems to be because the extension isn't receiving any of the broadcast signals from gpaste-daemon.

gnome-shell 3.16.3
gpaste 3.16.2.1
systemd v224
kdbus 63c8e2f (kdbus: fix wrong message size on 32bit)

**Comment by Keruspe** [comment]
Which version of gdm do you use?

There was an issue in gdm < 3.17 where it would spawn a dbus-daemon even if you were running kdbus and there was a split and all actors didn't receive all messages.

works fine here with kdbus branch 4.1, linux 4.1.5, systemd git, gnome-shell 3.17.4

**Comment by heftig** [comment]
GDM 3.16.2, and already patched for this issue.

**Comment by heftig** [comment]
@Keruspe: I think the DBus interaction is in libgpaste, and so the shell extension and the other clients (e.g. gpaste-ui) all use the same daemon tracking code?

The shell and the daemon are definitely on the same bus.

**Comment by Keruspe** [comment]
They all use the same tracking code but they might have a different environment though.

You should try to monitor signals with e.g. busctl

**Comment by heftig** [comment]
Updated kdbus to 917ee9c62. Now attempts to select history cause log messages:

```
systemd-bus-proxyd[1137]: Failed to forward message we got from local: uid=1000 gid=1000 message=method_return destination=:1.1258 path=n/a interface=n/a member=n/a: Invalid slot
```

The monitor also shows that no method_return is transmitted for the Select call.

**Comment by heftig** [comment]
I didn't have any luck with the latest systemd and kdbus, either.

**Comment by heftig** [comment]
systemd v225 + latest kdbus (with raised match limit) seem to have solved the issue.
