### ISSUE TITLE
is-enabled reports bad status for runtime enabled units

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#9122]
```
# systemd --version
systemd 238
...
# systemctl is-enabled bluetooth.service 
disabled
# systemctl --runtime enable bluetooth.service
Created symlink /run/systemd/system/dbus-org.bluez.service → /usr/lib/systemd/system/bluetooth.service.
Created symlink /run/systemd/system/bluetooth.target.wants/bluetooth.service → /usr/lib/systemd/system/bluetooth.service.
# systemctl is-enabled bluetooth.service
enabled
```

I would have expected "enabled-runtime" here instead of "enabled".

**Comment by fbuihuu** [comment]
I took a look at the code but I must admit that I'm confused.

For example, simply creating a dummy symlink like the following seems to confuse the tool:

```
# ln -sf /usr/lib/systemd/system/rsyslog.service /etc/systemd/system/bluetooth.service
# systemctl is-enabled bluetooth.service 
enabled
```
It searchs for symlinks in /etc/systemd/system/* whereas the symlinks for enabling services are in *.wants.d/ or *.requires.d/

Also the tool seaches for symlinks in /etc/systemd/system.control which doesn't seem correct.

**Comment by fbuihuu** [comment]
Another weird case:

```
$ find /run/systemd/generator/ -name var-spool.mount
/run/systemd/generator/var-spool.mount
/run/systemd/generator/local-fs.target.requires/var-spool.mount
$ systemctl is-enabled var-spool.mount
generated
```
"generated" doesn't tell if  the unit is enabled or not which is the main goal of "is-enabled".

**Comment by keszybz** [comment]
I prepped a PR for the first issue.

The second issue, I don't think is valid. The docs say:
> The unit file was generated dynamically via a generator tool. …  Generated unit files may not be enabled, they are enabled implicitly by their generator.

And indeed, 'systemctl enable' and 'systemctl disable' have no effect on such units. It seems this is working as designed.

**Comment by fbuihuu** [comment]
I don't understand what "enabled implicitly" exactly means but if you take the fstab-generator, generated mount units are not always enabled (when "noauto" is used).

**Comment by keszybz** [comment]
The units which are generated with "noauto" cannot be enabled because they don't have an [Install] section.. They can only be started directly, or pulled in through a dependency.

**Comment by fbuihuu** [comment]
In that case "static" seems more appropriate, no ?

I mean 'systemctl is-enabled' always returns "generated" for mount units generated by the fstab-generator even if they're statically enabled.
