### ISSUE TITLE
`EXTEND_TIMEOUT` test is flaky

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#9123]
See e.g. https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/amd64/s/systemd-upstream/20180529_133849_d59f0@/log.gz
from #9119.

**Comment by poettering** [comment]
Maybe we should simply extend all the timeouts in the test? I have the suspicion that this is just caused because we stopped using nested KVM and thus the VMs are extremely slow now

**Comment by poettering** [comment]
hmm, yes we can make it nspawn only pretty easily, maybe that's indeed an quick solution...
