### ISSUE TITLE
IPv6 point-to-point link stuck in state "configuring"

### ISSUE THREAD

**Issue by olavmrk** [systemd/systemd#9130]
**systemd version the issue has been seen with**
237 (237-3~bpo9+1)

**Used distribution**
Debian Stretch

**Expected behaviour you didn't see**
Interface state configured

**Unexpected behaviour you saw**
Interface state remains in state "configuring"

**Steps to reproduce the problem**

Add a simple network configuration file `/etc/systemd/network/eth0.network`:

```
[Match]
Name=eth0

[Address]
Address=2001:db8::20
Peer=2001:db8::10/128
```

Then restart systemd-networkd.

The interface is apparently configured, and the link works, but systemd-networkd shows its state as "routable (configuring)":

```
$ sudo networkctl status eth0
● 2: eth0
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/eth0.network
            Type: ether
           State: routable (configuring)
            Path: acpi-VMBUS:01
          Driver: hv_netvsc
      HW Address: 00:1d:d8:b7:86:9c (Microsoft Corporation)
         Address: 2001:db8::20
                  fe80::21d:d8ff:feb7:869c
```

The link works; I can ping and SSH across to the peer.

```
$ ip address show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1d:d8:b7:86:9c brd ff:ff:ff:ff:ff:ff
    inet6 2001:db8::20 peer 2001:db8::10/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::21d:d8ff:feb7:869c/64 scope link 
       valid_lft forever preferred_lft forever
```

```
$ ip -6 route
2001:db8::10 dev eth0 proto kernel metric 256  pref medium
2001:db8::20 dev eth0 proto kernel metric 256  pref medium
fe80::/64 dev eth0 proto kernel metric 256  pref medium
```

The log from networkd is available here:
[networkd-log.txt](https://github.com/systemd/systemd/files/2052825/networkd-log.txt)

I noticed that it was trying to send some router solicitations:

> NDISC: Started IPv6 Router Solicitation client
> NDISC: Sent Router Solicitation, next solicitation in 3s
> NDISC: Sent Router Solicitation, next solicitation in 8s

Thinking that this may be the problem, I tried disabling `IPv6AcceptRA`:

```
[Match]
Name=eth0

[Network]
IPv6AcceptRA=no

[Address]
Address=2001:db8::20
Peer=2001:db8::10/128
```

However, the interface remains in state configuring. The log file is available here:
[networkd-log-no-ra.txt](https://github.com/systemd/systemd/files/2052849/networkd-log-no-ra.txt)

**Comment by poettering** [comment]
something for you @ssahani?

**Comment by ssahani** [comment]
from initial debugging I figure 
we set
```
  /* Consider address tentative until we get the real flags from the kernel */
-        address->flags = IFA_F_TENTATIVE;
```
so in link_check_ready()  if 
```
adress_is_ready(const Address *a) {
        if (a->family == AF_INET6)
                return !(a->flags & IFA_F_TENTATIVE);
```
it never sets to configured if kernel does not push any update

**Comment by ssahani** [comment]
@olavmrk could you test with  #9130 please.

**Comment by olavmrk** [comment]
@ssahani Thank you for looking into this bug!

I didn't find an easy way to build a Debian package directly from that commit, however backporting the commit and rebuilding the existing Debian package with that change was relatively straightforward.

From my testing, #9174 appears to fix the problem. After switching back and forth between packages with and without the fix, I can see that installing the packages with the fix result in the link being shown as "routable (configured)", while installing the packages without the fix results in "routable (configuring)".

**Comment by ssahani** [comment]
@olavmrk  could you please test the latest PR

**Comment by olavmrk** [comment]
@ssahani I have tested the latest version of #9174 now, and it works for me. The interface is shown to be in state "routable (configuring)" for around 10-15 seconds, and then the state changes to "routable (configured)".

(This is with the same caveat as last time -- in order to build a Debian package of it, I had to backport the patch to v239 of systemd.)

**Comment by ssahani** [comment]
thanks for testing out @olavmrk . After setting the address we are queering again after 5 sec to kernel to know the state of the address.

**Comment by olavmrk** [comment]
@yuwata: Did you close this issue by accident? From [your comment in #11232](https://github.com/systemd/systemd/pull/11232#issuecomment-449603056) I believe that pull request does not actually fix the problem for IPv6?

**Comment by yuwata** [comment]
Oops. Sorry.
