### ISSUE TITLE
TEST-13-NSPAWN-SMOKE fails

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#9139]
**systemd version the issue has been seen with**
v238, master

**Used distribution**
Ubuntu 18.04 LTS (bionic), Ubuntu cosmic

**Expected behaviour you didn't see**
 TEST-13-NSPAWN-SMOKE passes

**Unexpected behaviour you saw**
 ```
+ systemd-nspawn --register=no -D /var/lib/machines/unified-no-cgns-no-api-vfs-writable-yes --network-namespace-path=/run/netns/nspawn_test /bin/ip a
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Spawning container unified-no-cgns-no-api-vfs-writable-yes on /var/lib/machines/unified-no-cgns-no-api-vfs-writable-yes.
Press ^] three times within 1s to kill container.
Path /run/netns/nspawn_test doesn't refer to a network namespace
[FAILED] Failed to start Testsuite service.
See 'systemctl status testsuite.service' for details.
```

**Steps to reproduce the problem**
```
cd test/TEST-13-NSPAWN-SMOKE && make
```

**Comment by evverx** [comment]
A similar issue has been fixed in https://github.com/systemd/systemd/pull/8559. Could you check that  your master contains https://github.com/systemd/systemd/commit/29f74559d4dc6ea41232233d32f1a92bcee43626?

**Comment by xnox** [comment]
Let me check. I was going to say bisect yields 77f9fa3b8ea46c27e5a5e9270f71bf1b4000c3e0 which does smell like https://github.com/systemd/systemd/pull/8559 should have fixed all the things.

**Comment by xnox** [comment]
Yeap, all is good.
