### ISSUE TITLE
resolved unusable as a system mdns resolver

### ISSUE THREAD

**Issue by CosmicToast** [systemd/systemd#9140]
**Is your feature request related to a problem? Please describe.**
Resolved cannot be used as a system-wide mdns resolver for the following reasons:
1. resolved does not automatically perform mdns/llmnr resolution (e.g in nss_resolve)
2. systemd-resolved does not automatically perform mdns/llmnr (e.g in `systemd-resolved some.local`)
3. systemd-resolved uses llmnr when possible, avoiding mdns (as far as I can tell, this is a problem in multi-network environments, where the gateway will be performing avahi reflection).

To best illustrate this feature, consider the following example:
```sh
systemd-resolve -p mdns some.local
# => some.local: some-ip%iface

systemd-resolve -i iface some.local
# => some.local: some-ip%iface

grep hosts /etc/nsswitch.conf
# => hosts: files mymachines mdns4 resolve myhostname
# note: full stack here without any returns for debugging

systemd-resolved some.local
# => some.local: resolve call failed: 'some.local' not found

getent hosts some.local
# => (return 2)

ping some.local
# => ping: some.local: Name or service not known

pgrep avahi
# => (return 1)
# note: goal being to use resolved as the mdns resolver, not avahi

systemd-resolve --status
# relevant lines:
# Link X (iface)
# Current Scopes: LLMNR/IPv4 LLMNR/IPv6 mDNS/IPv4 mDNS/IPv6
# MulticastDNS setting: resolve
# note: disabling LLMNR makes no difference
```

The expectation (with resolved clearly successfully handling the mdns call), of course, is for all of these to succeed (except maybe `systemd-resolved some.local`).

**Describe the solution you'd like**
Add a new nss module (`nss_resolve_mdns`), which will perform mdns-specific resolution as a replacement for `nss_mdns(_minimal)(_{4,6})`.

**Describe alternatives you've considered**
Other possibilities include:
- modifying nss_resolve to also resolve mdns
- modifying systemd-resolve to automatically attempt mdns resolution when the zone is `.local` (or whatever is configured in resolved.conf - requires a new configuration option) (assuming that's a similar interface to what nss_resolve uses)

**Notes**
It is entirely possible that there is already support for this.
However, I could not find any documentation mentioning it, nor a related nss module.
If this is actually supported, please consider this RFE to be towards documenting this use-case.

**Comment by xnox** [comment]
For completeness sake, what is your systemd release version number & the OS in use?

**Comment by poettering** [comment]
> resolved does not automatically perform mdns/llmnr resolution (e.g in nss_resolve)

hmm, it doesnt? it should be, and that works here?

**Comment by poettering** [comment]
note that llmnr is only done for single-label names, while mdns is only done for names ending in .local. i.e. if you have two machines a and b, then ping b from a as "ping b" to use llmnr, and "ping b.local" to use mdns

**Comment by 5paceToast** [comment]
> For completeness sake, what is your systemd release version number & the OS in use?
```sh
systemctl --version
# => systemd 238
# +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid
```
These specific examples are on an updated Arch Linux system, but I've ran into this on ubuntu and gentoo (amongst others). The Arch system just happens to be the one where I'm interested of removing avahi :)

> hmm, it doesnt? it should be, and that works here?

As per my example, it doesn't - a shortened version (of just the related lines):
```sh
grep hosts /etc/nsswitch.conf
# => hosts: files mymachines resolve myhostname

systemd-resolve -p mdns some.local
# => some.local: ip%iface

systemd-resolve some.local
# => some.local: resolve call failed: 'some.local' not found

ping some.local
# => ping: some.local: Name or service not known
```

However, it's good to know that this functionality is intended to work.

To eliminate other bugs...
- There is a local dns server (on the gateway), but `.local` is not a zone on it.
- The only "unusual" part about my setup I can think of is that I have two macvlan devices instead of a single interface (due to legacy support of what previous admins have done). However, I only have one of them doing mdns/llmnr resolution, and it's turned off everywhere else.
- I'm using systemd-networkd for my interface configuration, and can provide (censored) versions thereof (if it's needed)

**Comment by 5paceToast** [comment]
After looking through some details, dhcp was pushing `local` as a search domain, and that's what was preventing resolve from performing the usual check - after removing that (legacy option, I suspect) everything works as expected.

I had no idea that could possibly interfere, but looking at #8852, this seems to be intended behavior.
As such, it may make sense to document that behavior, and/or edit the "Current Scopes" status report (if `.local` is being ignored anyways, maybe it shouldn't claim mDNS as working (note: I'm not aware of how `resolve`'s internal works, so this last bit may not be relevant)).

Either way, if this documentation/scope-edit makes sense, it should be done in another bug.
Sorry for the time-waster.
