### ISSUE TITLE
I got confused by `man 7 daemon` about "ensure that the daemon can never re-acquire a [controlling] terminal again"

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#9164]
**systemd version the issue has been seen with**
systemd-238-8.git0e0aa59.fc28.x86_64

**Used distribution**
Fedora 28

---

I was trying to work on icinga2, and `man 7 daemon` (provided by systemd) confused me. It seems to be telling developers that if they follow these instructions, they do not have to worry about passing O_NOCTTY to open().  But this only applies when following the list of steps given for SysV.  It does not apply to the instructions for a "new-style" daemon under systemd.  If you write a daemon which can run under systemd without forking, the daemon still needs to use O_NOCTTY when opening a user-specified logfile (because the user could specify `/dev/tty-foo`).

> 6\. In the child, call setsid() to detach from any terminal and create an independent session.
> 7\. In the child, call fork() *again*, to ensure that the daemon can never re-acquire a terminal again.

This is from the list of steps for SysV daemons.  But then we read

> For developing a new-style daemon, none of the initialization steps
> recommended for SysV daemons need to be implemented. New-style init
> systems such as systemd make all of them redundant.

I think I was misled by this last sentence. systemd does not ensure that a _new-style_ daemon can never re-acquire a terminal again.  Actually, new-style daemons under systemd end up as session leaders (SID = PID), and can re-acquire a terminal.

```
$ ps -efj
UID        PID  PPID  PGID   SID  C STIME TTY          TIME CMD
root         1     0     1     1  0 May10 ?        00:06:44 /sbin/init
...
root       185     1   185   185  0 May10 ?        00:09:48 /lib/systemd/systemd-journald
```

```
$ systemctl cat test
# /etc/systemd/system/test.service
[Service]
Type=simple
ExecStart=/bin/sh -c "exec cat </dev/tty10 >/dev/tty10"

$ systemctl status test
● test.service
   Loaded: loaded (/etc/systemd/system/test.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2018-06-01 11:28:41 BST; 1min 35s ago
 Main PID: 12173 (cat)
    Tasks: 1 (limit: 4915)
   Memory: 180.0K
   CGroup: /system.slice/test.service
           └─12173 cat

Jun 01 11:28:41 alan-laptop systemd[1]: Started test.service.

$ ps -ejf
UID        PID  PPID  PGID   SID  C STIME TTY          TIME CMD
...
root     12173     1 12173 12173  0 11:28 tty10    00:00:00 cat
```

I also confirmed that switching to tty10 and pressing Ctrl+C stops this `cat` process.

---

I'm not sure how this confusion can be prevented... because it seems a bit fundamental to how `man 7 daemon` is structured. And yet, I don't expect systemd would change its behaviour to double-fork when starting services, I think it would work but it's too weird.

Sorry not to have a suggestion yet, but I did think about it for a bit.

---

It might be slightly better to just remove the second fork, and any mention of re-acquiring a controlling terminal, but...

If we remove mention of re-acquiring a controlling terminal, I'm not sure we could even rely on a SEE ALSO to mention it for us.  Because all references I can think to add, would appear to contradict the manpage in other areas.

I thought I read some comments about the structure of `man 7 daemon` before...  I struggle a bit.  You would think there would be common examples of the SysV code, or well-known reference code you could follow along with, but they're too hard to find as there's too many "wrong" examples.  I particular it's rare to see a pipe being used as the manpage says. (Including in systemd-udevd, which still has a code path to daemonize, for whatever reason).

I think the pipe trick is mainly needed because you can't fork after starting threads. Hence it's not needed in a completely traditional unix daemon...

E.g. Kerrisk's "The Linux Programming Interface" seems to cover both SysV style daemons and threads without mentioning the pipe trick.  Which is probably needed to fully report service readiness when combining the two.

**Comment by floppym** [comment]
> You would think there would be common examples of the SysV code, or well-known reference code you could follow along with, but they're too hard to find as there's too many "wrong" examples.

I think many daemons in the wild simply don't report status correctly on startup. On boot, you see a message that says they started OK, but then they fail a second later.

**Comment by floppym** [comment]
> I think the pipe trick is mainly needed because you can't fork after starting threads. Hence it's not needed in a completely traditional unix daemon...

How else would you pass status information from the daemon process to its grandparent?

**Comment by sourcejedi** [comment]
> I think many daemons in the wild simply don't report status correctly on startup. On boot, you see a message that says they started OK, but then they fail a second later.

I wouldn't be surprised, I'm sure I've seen it happen.

In a sense, that's a problem that systemd could choose not to solve. If SysV daemon _foo_ doesn't report properly when it fails due to a config file mistake? I think it's quite clear that it's poorly implemented, and that there are other services that manage to do better.

Sure, the reason I found this bug is I looked for an authoritative explanation of how to daemonize, tried to use this one, and found it misleading. So I would be happy to have an authoritative, free explanation. Unfortunately I don't have a positive suggestion how this one can be fixed.

In case no-one else can think how to make the systemd doc clear, I would actually prefer not to have an explanation that I get misled by, installed on my computer by the init system :).

> >  I particular it's rare to see a pipe being used as the manpage says. (Including in systemd-udevd, which still has a code path to daemonize, for whatever reason).

[...]

> How else would you pass status information from the daemon process to its grandparent?

[\<eliza>](https://en.wikipedia.org/wiki/ELIZA)Why do you think you need to pass status information from the daemon process to it's gradparent?

https://github.com/systemd/systemd/blob/v238/src/udev/udevd.c#L1730

**Comment by floppym** [comment]
As you have already pointed out, udevd does not follow the procedure for sysv daemons, probably because its maintainers don't care very much about supporting it that way.

**Comment by sourcejedi** [comment]
The point is it reads the config before daemonizing. So if there's a config error, it's reported correctly.

Why do you think you need to pass status information from the daemon process to it's grandparent?

**Comment by sourcejedi** [comment]
ah, I was assuming `udev_parse_config()` did something useful and would cause failure. Reality might be a bit different :). But I'm sure I've seen this approach, you init the configuration first, only then do you daemonize.

**Comment by sourcejedi** [comment]
Sorry, I'm being stupidly hostile.

I think the strategy with a pipe is a decent idea. But the manpage seems to say this strategy is required, without citing reasons. It makes it harder for me to confirm the manpage - and specifically to confirm any specific change to the manpage, which would have clarified the TTY issue I'm reporting here.

**Comment by poettering** [comment]
docfix waiting in #9164

**Comment by sourcejedi** [comment]
#9164 is this issue, the docfix is in #11989 :-).  Looks decent, thanks.

FWIW, JdeBP mentioned that his `service-manager` avoids calling `setsid()` in the first place, so that service processes are not session leaders by default.  I would think that could work for our services.  E.g. `getty@.service` explicitly sets `TTYPath=/dev/%i` ; `rescue.service` sets `StandardInput=tty-force` ;  and those settings could imply `setsid()`.  I have no idea whether that would be good, whether it might break some third-party service, etc.

https://unix.stackexchange.com/questions/447275/does-systemd-not-protect-processes-against-acquiring-a-controlling-terminal/447319#447319

**Comment by poettering** [comment]
actually, there's code in systemd for not doing setsid() already, but we do not expose this behaviour currently. All processes forked off on behalf of .mount units use this functionality, because the automount logic needs it for robustness: automount cannot be triggered by processes of the process group of whoever establishes the automount units, and hence we need to make sure that /bin/mount is invoked from the same process group (and hence same setsid() session) as PID 1 since PID 1 established the automounts.

but dunno, I am a bit afraid of breaking compat with that. I think running everything in the same setsid() session as PID 1 is less than ideal. And if we don#t want that but still want to make O_NOCTTY redundant, the only option would be to create a new setsid() session for each service but then fork again and let the session master die, so that the session is an orphan. But that'd be quite ugly too, to do for every single service on the system
