### ISSUE TITLE
Add systemd feature and systemctl (?) option to assign started unit and it's deps to specified seat

### ISSUE THREAD

**Issue by alxchk** [systemd/systemd#9168]
**The problem.**

During first login systemd creates user instance of systemd. This instance itself is not assigned to any seat.
Any process which started using systemd will not belong to any seat.

``` 
> loginctl session-status  
Could not get properties: Caller does not belong to any known session
```

Thus it will not be able (at least) to properly use polkit.

**Feature request.**

To add feature to assign unit (or dependency) to the seat where systemctl tool (or parent dependency) executed.

**Comment by poettering** [comment]
Uh, no. First of all the "loginctl" command you show shows that your process is not part of a session, this is entirely unrelated to whether there is a seat assigned or not.

More importanly though, I am very sure that PolicyKit should not derive its access decisions on session membership of the calling process (or even the assignment of a seat to the session of calling process), but instead make its decisions on whether the calling process' user has any suitable sessions at all. This not only makes more conceptual sense (as the session itself as a non-kernel object sucks for making security decisions, and UIDs are much more suitable for that instead, and how things were always done on UNIX). It also matches how desktops these days start their process: from a singleton systemd instance, that is not directly part of any session, but shared by all of the user's active sessions.

Anyway, please bring this up with the PolicyKit maintainers. In systemd there's little we can or should change (already as assigning a seat to some session or a process to some session are both privileged operations, and a --user instance (which is unprivileged) couldn't do that anyway...)

**Comment by poettering** [comment]
I hope this makes sense... Let's close this here...

**Comment by alxchk** [comment]
> More importanly though, I am very sure that PolicyKit should not derive its access decisions on session membership of the calling process (or even the assignment of a seat to the session of calling process), but instead make its decisions on whether the calling process' user has any suitable sessions at all. 

Well, it works this way of course. But it also can distinguish (inter)active user and make different decisions then. Polkit was just an example. Processes which started by systemd are not belong to any session, so this loginctl stuff became pretty useless.

After more than 5 years :D of patching systemd I decided to give up and use upstream approach to user sessions. I like idea of using systemd to manage my user's processes but it works quite bad with all this "seats", "sessions" and other stuff, because of single instance architecture. I understand that RH mainstream is not really interested in this, because they do use DM which do some kind of session management. But why to create additional entity, if systemd can do that better?..
