### ISSUE TITLE
Coverity poor match for ASSERT_SIDE_EFFECT (on assert_se)

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#9183]
I think most of the Coverity false positives are `ASSERT_SIDE_EFFECT` whenever `assert_se` is used.

Latest report had 3 of them, for example:

```c
*** CID 1391439:  Incorrect expression  (ASSERT_SIDE_EFFECT)
/src/fuzz/fuzz-journal-remote.c: 59 in LLVMFuzzerTestOneInput()
53             /* Out */
54     
55             r = sd_journal_open_files(&j, (const char**) STRV_MAKE(name), 0);
56             assert_se(r >= 0);
57     
58             if (getenv_bool("SYSTEMD_FUZZ_OUTPUT") <= 0)
>>>     CID 1391439:  Incorrect expression  (ASSERT_SIDE_EFFECT)
>>>     Assignment "dev_null = fopen("/dev/null", "we")" has a side effect.  This code will work differently in a non-debug build.
59                     assert_se(dev_null = fopen("/dev/null", "we"));
60     
61             for (mode = 0; mode < _OUTPUT_MODE_MAX; mode++) {
62                     if (!dev_null)
63                             log_info("/* %s */", output_mode_to_string(mode));
64                     r = show_journal(dev_null ?: stdout, j, mode, 0, 0, -1, 0, NULL);
```

Can we _teach_ Coverity that `assert_se` doesn't ignore side effects? It seems that whenever they match a `/assert/i` in regular expression, they assume it has a problem with side effects...

I wish it would at least be able to *look* inside the definition of `assert_se` and notice that it's not a problem with it.

One alternative would be to rename `assert_se` to something else that doesn't include `assert` in its name... But I think teaching Coverity to do the right thing would be better.

I didn't find many docs for Coverity online... So wondering if anyone else in the project knows more about it or knows how best to get some support on it to try to fix this one?

Cheers,
Filipe

**Comment by filbranden** [comment]
@CermakM Can I please get [Admin access](https://scan.coverity.com/projects/systemd?tab=members) to Coverity?

I found some instructions to use a command such as `cov-make-library model.c` to teach Coverity about our macros and functions, but to do that I need to download the software and it tells me I need Admin in a project to be able to download...

Thanks!
Filipe

**Comment by CermakM** [comment]
@filbranden This is not only my call to decide.

cc @keszybz @lnykryn

**Comment by keszybz** [comment]
@filbranden I couldn't "upgrade" your role (there's a pull-down menu, but the changes I make there have no effect whatsover afaict), so I removed and added you back. You should have gotten an "invitation".

@yuwata → the same for you.

**Comment by evverx** [comment]
@keszybz could you send me an invitation too? It was a little bit hard to debug `coverity.sh` without the ability to load coverity.

**Comment by keszybz** [comment]
@evverx done.

**Comment by yuwata** [comment]
Thanks. I got the invitation.

**Comment by filbranden** [comment]
Yes, this worked, thanks for the invitation!

I'll see if I can fix the recurring issue we have with `assert_se(...)` then... Thanks!

**Comment by filbranden** [comment]
Ok, so I think I found where this can be set...

In [this page](https://scan.coverity.com/projects/systemd?tab=analysis_settings#) there's a "Modeling File" section where we can upload a file that Coverity will use to override function definitions in analysis.

Looking at that section right now, it's possible to view the current model file, which is:

```c
size_t fread(void *ptr, size_t size, size_t nmemb, int *stream) {
                    __coverity_panic__();
               }
```

I really don't understand why that is there... I'm somewhat inclined to remove that, since it doesn't make much sense...

I think what we need to add there (for `assert_se`) is:

```c
#nodef assert_se
void assert_se(int expr) {
    if (!expr)
        __coverity_panic__();
}
```

I'm assuming this might be enough to "teach" Coverity about what `assert_se` is/does. I'm not 100% positive this will help with `ASSERT_SIDE_EFFECT`, but I'm guessing it should be OK to give this a try and see if it helps, otherwise maybe post a message in forums to see if they have a better suggestion.

For the record, here is the [documentation on models](https://scan.coverity.com/models), which might come handy in the future...

**Comment by kdudka** [comment]
@filbranden I do not think that `#nodef` in a model file would take any effect because model files are used during analysis whereas `#nodef` takes effect during compilation.  So I tried to put it to `$COV_ROOT/config/user_nodefs.h` but it did not take any effect either.  Finally, I was able to suppress those false positives by passing `^assert_(return|se)$` to the `macro_name_lacks` option of the `ASSERT_SIDE_EFFECT` checker.  But I am not sure if there is any way to specify checker options while using scan.coverity.com.

**Comment by filbranden** [comment]
Thanks @kdudka !

It seems this configuration is done in an XML coverity.config file, correct?

Is that file passed to the analyzer or to `cov-build`? We do control the `cov-build` call, so we could pass a `--config` to it...

Cheers,
Filipe

**Comment by filbranden** [comment]
As an aside, removing the `fread` from the model file uncovered a new Coverity defect (in `networkctl.c`):

```
10. tainted_data_transitive: Call to function le64toh with tainted argument u returns tainted data.
CID 1393254 (#2 of 2): Untrusted value as argument (TAINTED_SCALAR)
11. tainted_data: Passing tainted variable le64toh(u) to a tainted sink.
```

So I imagine it was added for that reason... (Though I don't think that's the right approach there.)

I'll look further into this defect, see why Coverity thinks it's a problem and see if we can fix it in a better way.

Cheers,
Filipe

**Comment by filbranden** [comment]
Yeah, FB178872 is also known as @filbranden 😄 

Let's see if they suggest something, but looks like scan.coverity.com is not prepared to handle this...

One option would be to rename these two functions so they don't include "assert" in the name, like maybe `check_se` (or, in that case, is `se` even needed in the name?) and `check_return` perhaps?

It's a bit unfortunate to have to change the code to cater to these tools... But maybe keeping "assert"'s meaning as a no-side-effect is not such a bad idea...

**Comment by filbranden** [comment]
Let's not do this one...

After #9223 perhaps we could take the plunge and make these just work on the current context. I'll prepare a PR for that.

**Comment by filbranden** [comment]
Sorry, closed by mistake.

**Comment by filbranden** [comment]
So #9629 seems to fix the ASSERT_SIDE_EFFECTS... \o/

The other recurring false positive we have in Coverity is "Missing break in switch" for most of the *.gperf files. It turns out the C source generated by gperf is marked with `/*FALLTHROUGH*/` to placate linters, but Coverity is not too happy about that still...

Anyways, it's not like we're going to fix gperf somehow and I think we can trust its output... So I'm leaning towards adding an expression matching *.gperf files and have those excluded from Coverity analysis. In fact, I'm going to do that right now.

After that is done, we'll have 24 open issues remaining and some of those might be because of my test run not having linked to all the libraries... Let's allow it to run undisturbed for a few days, afterwards I'll try to see how many of the remaining are still false positives and which might still need addressing...

Cheers!
Filipe
