### ISSUE TITLE
There seems to be something wrong with coverity.sh on Travis CI

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9186]
Travis has started to schedule cron jobs which are supposed to upload analysis results to Coverity daily. For some reason `coverity.sh` can't seem to find `python`:
```
travis_time:end:0afe1d48:start=1528135313165223102,finish=1528135320102762589,duration=6937539487
[0K
[32;1mThe command "docker exec -it travis_coverity_scan sh -c "CFLAGS='-D_Float128=long\ double' meson cov-build -Dman=false"" exited with 0.[0m
travis_time:start:0005b540
[0K$ docker exec -it travis_coverity_scan coverity.sh build
[33;1mNote: COVERITY_SCAN_PROJECT_NAME and COVERITY_SCAN_TOKEN are available on Project Settings page on scan.coverity.com[0m
[33;1mCoverity Scan configured to run on branch master[0m
/usr/local/bin/coverity.sh: line 40: python: command not found
/usr/local/bin/coverity.sh: line 44: python: command not found
[33;1mCoverity Scan analysis NOT authorized until .[0m

travis_time:end:0005b540:start=1528135320110574909,finish=1528135320628943260,duration=518368351
[0K
[32;1mThe command "docker exec -it travis_coverity_scan coverity.sh build" exited with 0.[0m
travis_time:start:0344b892
[0K$ docker exec -it travis_coverity_scan coverity.sh upload
[33;1mNote: COVERITY_SCAN_PROJECT_NAME and COVERITY_SCAN_TOKEN are available on Project Settings page on scan.coverity.com[0m
[33;1mCoverity Scan configured to run on branch master[0m
/usr/local/bin/coverity.sh: line 40: python: command not found
/usr/local/bin/coverity.sh: line 44: python: command not found
[33;1mCoverity Scan analysis NOT authorized until .[0m
```

The full log can be found at https://api.travis-ci.org/v3/job/387913818/log.txt.

**Comment by filbranden** [comment]
I'm not an expert on Travis or Coverity...

But did you look into setting this up using:

```
addons:
  coverity_scan:
    ...
```

See the "travis.yml" section in the [Coverity docs for Travis](https://scan.coverity.com/travis_ci).

**Comment by evverx** [comment]
Thank you. Yes, I once suggested using the addon in https://github.com/systemd/systemd/issues/8023#issuecomment-393221475, but the suggestion seems to have been ignored, so I assumed that it had been decided that the rest of https://github.com/systemd/systemd/pull/7691 should be kept. In theory, it should have been easier to fix `.travis.yml` than set up everything from scratch. In practice, I'm not so sure now.

**Comment by evverx** [comment]
I'm reopening the issue because `coverity.sh` is still broken. I'm wondering if it's ever worked.

@keszybz @msekletar @CermakM it would be great if you could take a look at https://travis-ci.org/systemd/systemd/jobs/388035560.

In case you didn't see the last notification from `coverity`, I'll leave it here:
>  Your request for analysis of systemd/systemd  is failed.
    Analysis status: Failure
    Please fix the error and upload the build again.

>    Error details:
    The build uploaded has been only partially compiled. We recommend at least 85% capture success to avoid false-positives during analysis. As per last few lines of cov-int/build-log.txt, the percentage of compilation units ready for analysis is 2% which is less than the expected 85%

**Comment by evverx** [comment]
Could it be that coverity doesn't support gcc 8?

**Comment by evverx** [comment]
When gcc 7 was used to build `systemd` in https://github.com/systemd/systemd/pull/9190, coverity was able to find [839 C/C++ compilation units (99%) ready for analysis](https://travis-ci.org/systemd/systemd/builds/388103656#L2555), which seems to be much better compared to [19 C/C++ compilation units (2%)](https://travis-ci.org/systemd/systemd/jobs/388035560#L2293). Maybe Fedora 27 could be used until Coverity starts supporting gcc 8.

**Comment by evverx** [comment]
I still have no idea why `coverity.sh upload` failed with the misleading error message ["Coverity Scan upload failed: Build successfully submitted"](https://travis-ci.org/systemd/systemd/builds/388103656#L2572), though. Probably the response from coverity should be printed so that the script would be easier to debug.

**Comment by CermakM** [comment]
@evverx the reason I did not use travis addons is that they could not be triggered by cron .. Back then, I opened a PR for that: https://github.com/travis-ci/travis-ci/issues/8671

Now, since Travis is used exclusively for Coverity, it should be doable.

As far as the error is concerned, this is most likely error somewhere during the compilation, when coverity might not be ready for the new gcc and does not catch the compilation units. We've dealt with similar problems in the past, maybe @msekletar or @kdudka can remember (and help) with this. The upload will fail if there are less than 85% units caught (this is from the API side to limit upload traffic, it won't let u upload it)

**Comment by keszybz** [comment]
I can confirm that coverity fails with F28 (gcc-8.1). I think we should just switch to using F27. We don't care about the compiler version too much, and maybe coverity will get fixed later on without us having to do anything. @evverx can you amend #9190 to be mergeable?

**Comment by keszybz** [comment]
> I can confirm that coverity fails with F28 (gcc-8.1).

But F28 with downgraded gcc (gcc-7.3.1-5.fc27.x86_64), still fails ("19 C/C++ compilation units (2%) are ready for analysis"). So the problems with coverity are not about the compiler, at least not only.

**Comment by evverx** [comment]
@keszybz I've updated #9190. `coverity.sh` still needs fixing, but I guess it could be done later.

**Comment by keszybz** [comment]
@evverx actually I think I've got it figured out now. It's just the _Float64/_Float64x/... defines that are missing. I'll submit a PR shortly.

**Comment by evverx** [comment]
I've just merged the PR and turn the daily cron job again. It should be enough to get coverity working in the sense that analysis results will be sent to coverity daily.

**Comment by evverx** [comment]
@keszybz I'm sorry I overlooked your comment and was quick to merge the PR. Anyway, it's better to fix something that works somehow :-)

**Comment by evverx** [comment]
The job has just finished: https://api.travis-ci.org/v3/job/388181046/log.txt. Everything is fine except that `coverity upload` exited with 1 making the build red, which is a false positive, of course, and can be ignored at least for now.
