### ISSUE TITLE
inserted module 'ip_tables'

### ISSUE THREAD

**Issue by ninja-** [systemd/systemd#919]
can't get rid of this in any way. what's wrong with the logger?

**Comment by ninja-** [comment]
could anyone please fix this by moving https://github.com/systemd/systemd/blob/9db81db06b2dc1779c6f94bc62694511c03a78a1/src/core/main.c#L1444 up at least before https://github.com/systemd/systemd/blob/9db81db06b2dc1779c6f94bc62694511c03a78a1/src/core/main.c#L1414 ?

**Comment by zonque** [comment]
Could you open a PR with this modification, describing your rationale for it? It's easier to discuss changes this way. Thanks!

**Comment by ninja-** [comment]
@zonque the mentioned debug message breaks the 'silent' mode. at the time kmod is loaded, the logging level hasn't been set from kernel arguments yet. the function which sets the logging level -         log_parse_environment() - should be called earlier to fix this issue.

looks like a one-line fix to me but I can open a pull request as well

**Comment by zonque** [comment]
Yes, please do. I'm not quite sure what you're proposing …

**Comment by ninja-** [comment]
@zonque

**Comment by poettering** [comment]
We should really just downgrade the log message in question from LOG_INFO to LOG_DEBUG, and that's it. Happy to take a patch for that.

**Comment by ninja-** [comment]
nice one thanks. I hope to test it at home :)
