### ISSUE TITLE
Cube i7 Stylus rotation info

### ISSUE THREAD

**Issue by rubensa** [systemd/systemd#9195]
There are different **Cube i7 Stylus** generations.

Those are identified with the printed serial code sticker on motherboard (Printed serial code on casing is not always true)

Order of Model (Old - New):

- W
- WA
- WWA
- WN(I8WN)
- I8L(With W on casing)

I own a **I8L** generation so the hw identification for my model does not work.

```bash
# cat /sys/class/dmi/id/sys_vendor
Cube
# сat /sys/class/dmi/id/product_name
i8-L
```

To fix the orientation for my device I had to create the file **/etc/udev/hwdb.d/61-sensor-local.hwdb** with the following content:

```
# Cube i7 Stylus I8L Model
sensor:modalias:acpi:KIOX000A*:dmi:*:svnCube:pni8-L:*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 1, 0; 0, 0, 1
```

In **hwdb/60-sensor.hwdb** there is an entry like these:

```
# Cube i7 Stylus
sensor:modalias:acpi:KIOX000A*:dmi:*:svnCube:pni7Stylus:*
 ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 1, 0; 0, 0, 1
```

Please, add the Cube i7 Stylus I8L Model to **60-sensor.hwdb** to avoid the need for **61-sensor-local.hwdb**.

PS:  I can make a pull request if needed.

**Comment by poettering** [comment]
Please post a proper PR adding this entry. Thanks.

cc @hadess

**Comment by rubensa** [comment]
Done: https://github.com/systemd/systemd/pull/9207

**Comment by poettering** [comment]
Closing as #9207 has been merged now.
