### ISSUE TITLE
Resolved uses stale split-DNS cached entries

### ISSUE THREAD

**Issue by guss77** [systemd/systemd#9196]
**Is your feature request related to a problem? Please describe.**

My company uses a split-DNS setup to allow direct access to serves that are available in a local network or over VPN, while the same entry resolves to a firewall access point when outside the local network.

When I start my laptop when connected to the local network and access a local server, systemd-resolved caches the local (non-routable) IP address of the server. If I then disconnect from the local network and switch to a public network, the system continues to try to resolve the server name to the local address - which the browser then fails to connect to,

**Describe the solution you'd like**

When SystemD detects a network change, it should flush the DNS cache, or at least clear all non-routable IP addresses.

**Describe alternatives you've considered**

1. Running `sudo systemd-resolve --flush-caches` manually - this is very tedious
2. Write a user SystemD D-BUS activated one-off service that calls `systemd-resolve` to flush cache - I couldn't figure out which D-BUS event to listen to.

**Comment by poettering** [comment]
Please have a look at #9236. I am pretty sure it fixes your issue.
