### ISSUE TITLE
HP ZBook Studio G4 - Wireless key

### ISSUE THREAD

**Issue by farsx** [systemd/systemd#9219]
**Is your feature request related to a problem? Please describe.**
Wireless switch isn't mapped correctly on HP Zbook Studio G4 laptop.

**Describe the solution you'd like**
Add the following lines on 60-keyboard.hwdb to handle rfkill soft block (LED stays off though):

```
# ZBook Studio G4
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHP:pnHPZBookStudioG4:pvr*
 KEYBOARD_KEY_f8=wlan                                   # Wireless HW switch button
```

**Comment by keszybz** [comment]
Hi, please submit this as a pull request.

**Comment by farsx** [comment]
PR #9220
