### ISSUE TITLE
[networkd] link file in /etc/systemd/network/ doesn't overwrite the default link file

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#9227]
**systemd version the issue has been seen with**
 systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
A link file in /etc/systemd/network/ should overwrite the default link file.

**Unexpected behaviour you saw**
link files in /etc/systemd-networkd/ will be ignored

**Steps to reproduce the problem**
I have an interface called `ens160`. I setup the following files for it:
`ens160.link`
```
[Match]
OriginalName=ens160

[Link]
MTUBytes=9000
```
`ens160.network`
```
[Match]
Name=ens160

[Network]
Address=xxx.xxx.xxx.99/27
Gateway=xxx.xxx.xxx.126
DNS=xxx.xxx.xxx.5
DNS=xxx.xxx.xxx.6
DNS=xxx.xxx.xxx.138
Domains=xxx.xxx.xxx xxx.xxx.xxx
VXLAN=vxlan1309
```

`networkctl status ens160` says:
```
...
    Link File: /lib/systemd/network/99-default.link
 Network File: /etc/systemd/network/ens160.network
...
```

seems like the link file in /etc/systemd/network/ gets ignored.

Note: If I try to set the MTU in a seperate link section directly in the network. It works! (but only after a reboot.. and this is a clearly regression to the ifup/ifdown tools where the value will be applied without rebooting it). Setting `ip link set ens160 MTU 9000` works btw as well without problem.

`ens160.network  with LINK section`
```
[Match]
Name=ens160

[Link]
MTUBytes=90000

[Network]
Address=xxx.xxx.xxx.99/27
Gateway=xxx.xxx.xxx.126
DNS=xxx.xxx.xxx.5
DNS=xxx.xxx.xxx.6
DNS=xxx.xxx.xxx.138
Domains=xxx.xxx.xxx xxx.xxx.xxx
VXLAN=vxlan1309
```

Another Note: Setting the MTU of 9000 to the physical interface should set the MTU of the connected vxlan interface to 8950 automatically (this is was /etc/network/interfaces does. This doesn't seem to apply to vxlan interfaces created by systemd.. why?)

**Comment by floppym** [comment]
Also, I don't think matching on `OriginalName=ens160` will work since the kernel never uses that name.
```
       OriginalName=
           A whitespace-separated list of shell-style globs matching the
           device name, as exposed by the udev property "INTERFACE". This
           cannot be used to match on names that have already been changed
           from userspace. Caution is advised when matching on kernel-assigned
           names, as they are known to be unstable between reboots.
```

**Comment by shibumi** [comment]
@floppym 
1. Even with 10-ens160.link it doesn't work. Maybe this have todo with `OriginalName=ens160`
```
P: /devices/pci0000:00/0000:00:15.0/0000:03:00.0/net/ens160
E: DEVPATH=/devices/pci0000:00/0000:00:15.0/0000:03:00.0/net/ens160
E: ID_BUS=pci
E: ID_MM_CANDIDATE=1
E: ID_MODEL_FROM_DATABASE=VMXNET3 Ethernet Controller
E: ID_MODEL_ID=0x07b0
E: ID_NET_DRIVER=vmxnet3
E: ID_NET_LINK_FILE=/lib/systemd/network/99-default.link
E: ID_NET_NAME_MAC=enx005056b0c42c
E: ID_NET_NAME_PATH=enp3s0
E: ID_NET_NAME_SLOT=ens160
E: ID_OUI_FROM_DATABASE=VMware, Inc.
E: ID_PATH=pci-0000:03:00.0
E: ID_PATH_TAG=pci-0000_03_00_0
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=VMware
E: ID_VENDOR_ID=0x15ad
E: IFINDEX=2
E: INTERFACE=ens160
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/ens160
E: TAGS=:systemd:
E: USEC_INITIALIZED=1902386
```

udevadm shows `INTERFACE=ens160`? So shouldn't be everything alright?

Btw when I set the Link directly in the network file it works (but only after a reboot). Why is systemd-networkd not applying the changes directly?

**Comment by poettering** [comment]
checking on OriginalName is not going to work on a name such as ens160, as that is a name udev will asign to it. Use some other match instead.

Either way, let's close this, as this appears to be local misconfiguration, and the pitfalls are even documented. Closing.

**Comment by shibumi** [comment]
Well I have fresh boxes here and at none of them I can set the MTU without rebooting.. normally this should apply with `systemctl restart systemd-networkd`..
