### ISSUE TITLE
networkd: optionally derivce DHCP DUID from DMI product ID or /etc/machine-id

### ISSUE THREAD

**Issue by olifre** [systemd/systemd#9228]
**Is your feature request related to a problem? Please describe.**
Current issue: In automated deployments, machines usually undergo at least two, often three, of the following stages:
1. Bare-metal discovery boot. 
2. Boot into a net-installer environment. 
3. Boot into final OS. 
Usually, there's also (0), i.e. the machine's OS before reinstallation. 

All these stages have different DUIDs. It's impossible to assign an IPv6 address with DHCPv6 which will be valid throughout all those stages. When assigning based on MAC address, the issue worsens since a valid lease issued for one of the stages prevents generation of leases in the next stages. 

**Describe the solution you'd like**
Implementing RFC 6355 and ideally even defaulting to that. 
RFC 6355 defines a universially unique ID / GUID, which should be the same for all DHCP clients on a given host. 
No matter whether a DHCP server then assigns by UUID-DUID or MAC address, it will "just work". 
That's already implemented in other DHCP clients, e.g. dhcpcd, and considered for ISC dhcp (dhclient), but seems to be still missing from systemd-networkd. 

**Describe alternatives you've considered**
All alternatives involve either:
- Writing hackish hooks running 'somewhere' to explicitly destroy leases between the stages on the DHCP server (not possible in all environments, violates lease time guarantees). 
- Hacking a DHCP server to violate other RFCs and assign an address to multiple different DUIDs. 
These alternatives are not really an option.

**Comment by olifre** [comment]
For the implementation in dhcpcd, check out:
https://roy.marples.name/git/dhcpcd.git/patch/?id=71981cab0e41ea2833489bc51307611727276aff
For the issue in ISC DHCP, check out:
https://bugs.isc.org/Public/Bug/Display.html?id=47732

**Comment by yuwata** [comment]
So, you mean here is, when `ClientIdentifier=duid` and `DUIDType=uuid` are set, then the default value of `DUIDRawData=` should be set by /sys/class/dmi/id/product_uuid ?

**Comment by yuwata** [comment]
If I remember correctly, some PXE boot rom generate UUID from mac address, and product_uuid is not used.

**Comment by yuwata** [comment]
Also, the access mode of /sys/class/dmi/id/product_uuid is `400`, so `networkd` cannot use it.

**Comment by olifre** [comment]
> So, you mean here is, when ClientIdentifier=duid and DUIDType=uuid are set, then the default value of DUIDRawData= should be set by /sys/class/dmi/id/product_uuid ?

Yes. 



> If I remember correctly, some PXE boot rom generate UUID from mac address, and product_uuid is not used.

Yes - those are the old ones not yet implementing RFC 6355. Newer ones should use DUID-UUID, and you can find e.g. UEFI TianoCore already does that:
https://github.com/tianocore/edk2/blob/d69e8a7b79bdfb282f35616d3030f02934d6271e/NetworkPkg/Dhcp6Dxe/Dhcp6Utility.c#L67



> Also, the access mode of /sys/class/dmi/id/product_uuid is 400, so networkd cannot use it.

For this, surely a fix can be found (something like `systemd-machine-id-setup` could extract it and store it in a place readable for `systemd-networkd`), or systemd can query SMBIOS 3.0 directly. Or we have to take this to the kernel to change the unix permissions on it. But that's a rather technical issue with the way systemd is implemented and not a conceptual one, so I'll leave it to you.

**Comment by poettering** [comment]
So what's this issue precisely about? Is this a request to optionally populate the DUID from the DMI product UUID? fimware metadata like that is notoriously crappy and more often not set properly than it is. I guess this could be an option, but it can't ever be the default, already because client tracking is a privacy issue.

There's /etc/machine-id, which is generally of better quality, and more reliable. It might be worth exploring that instead of in addition to. And I am also pretty sure it would make sense to derive the DUID through a hash from those in order not to reveal the low-level identifiers directly, but some subsystem specific ID instead.

Anyway, making this an option would definitely be OK.

**Comment by olifre** [comment]
> There's /etc/machine-id, which is generally of better quality, and more reliable. It might be worth exploring that instead of in addition to.

`/etc/machine-id` can not be used to implement RFC 6355 since it's generated on install or first boot ("when first needed"). . 
RFC 6355 is about a GUID which is consistent for any client and OS on a given machine. As you can note, Tianocore and dhcpcd already have this issue solved. 

A hashed variant of`/etc/machine-id` can already be used when specifying `DUIDType=vendor`. But as I said, this is a totally different approach. 

The issue this is about is encountered in any automated deployment in a DHCPv6-IPv6-only environment. The following is happening right now:
- A machine PXE-boots using a client DUID derived as described in RFC 6355 (as shown in the Tianocore example). The DHCPv6 server assigns a lease which may be based on the presented MAC address or DUID-UUID and is, in any case, bound to the presented DUID. 
- The netinstaller starts, runs e.g. `systemd-networkd`, which creates a different DUID on the fly, and the DHCPv6 server does not offer a new lease, since a lease has already been handed out to the very same host and is still valid. 
- The machine does not have IPv6 connectivity and can not install until the old lease has expired. 
- The problem is repeated when the machine boots into the final system. 

The only clean approach to solve this is a GUID / DUID-UUID which is globally unique across all dhcp client implementations. 

The only alternative is to supersede the original DHCPv6 RFCs so the server can hand out multiple leases for a single host based on something else than a DUID.

**Comment by yuwata** [comment]
I've tried to implement the feature in #9406. If possible, please test it. Thank you.

**Comment by olifre** [comment]
> If possible, please test it. Thank you.

Thanks a lot! I tried just now to test on Ubuntu 18.04 applying the patch against systemd, but failed miserably since the version shipped with Ubuntu was too old. 
I'll try again with Debian Sid, but have to create a VM first, so no promises on the timescale.

**Comment by uli42** [comment]
So this has been closed. But has it been merged?

**Comment by alexshpilkin** [comment]
@uli42 Yes. The notification mentioning #9406 above means that pull request #9406 closing this bug has been merged. (Whether the result has been released is another question.)

**Comment by uli42** [comment]
@alexshpilkin Ah, thanks, I had misinterpreted the reference to #9406 (thinking it was the same number as the issue).
