### ISSUE TITLE
Tunnels with Kind=gre and IPv6 addresses cause assertion failure

### ISSUE THREAD

**Issue by alexshpilkin** [systemd/systemd#9234]
**systemd version the issue has been seen with**
> Git commit systemd@866e6b7a of Jun 1

**Used distribution**
 > Arch Linux x86-64

**Expected behaviour you didn't see**
 > systemd-networkd refuses to create `Kind=gre` tunnels with `Local` and `Remote` set to IPv6 addresses

**Unexpected behaviour you saw**
 > systemd-networkd aborts with an assertion failure:
 > ```
> Assertion 'IN_SET(t->family, AF_INET, AF_UNSPEC)' failed at ../systemd/src/network/netdev/tunnel.c:118,  function netdev_gre_fill_message_create(). Aborting.
> ```
**Steps to reproduce the problem**
- Create a netdev file as follows, setting `LOCALv6` and `REMOTEv6` to IPv6 addresses:
```
[NetDev]
Name=NAME
Kind=gre
[Tunnel]
Local=LOCALv6
Remote=REMOTEv6
```
- Instruct systemd-networkd to bring the tunnel up by creating a drop-in for a managed interface:
```
[Network]
Tunnel=NAME
```
- Start or restart systemd-networkd. **CAUTION:** You will lose all network connectivity.

**Comment by poettering** [comment]
something for you, @ssahani ?

**Comment by ssahani** [comment]
gre is expecting ipv4 address https://wiki.linuxfoundation.org/networking/tunneling
