### ISSUE TITLE
Failed to connect to bus: Connection refused

### ISSUE THREAD

**Issue by alimp5** [systemd/systemd#9248]
Greetings!
Also I reported this issue to Dbus team:
https://bugs.freedesktop.org/show_bug.cgi?id=106874

**systemd version the issue has been seen with**
> systemd is already the newest version (238-5)
> xfce4 is already the newest version (4.12.4)   [my  default environment is based on XFCE-4]
> dbus is already the newest version (1.12.8-2)
> dbus-1-doc is already the newest version (1.12.8-2)
> dbus-java-bin is already the newest version (2.8-9)
> dbus-test-runner is already the newest version (16.10.0~bzr100+repack1-2)
> dbus-tests is already the newest version (1.12.8-2)
> dbus-user-session is already the newest version (1.12.8-2)
> dbus-x11 is already the newest version (1.12.8-2)
> dbus-cpp-bin:i386 is already the newest version (5.0.0+18.04.20171031-1)
> dbus-cpp-dev-examples:i386 is already the newest version (5.0.0+18.04.20171031-1)
> libdbus-cpp-dev:i386 is already the newest version (5.0.0+18.04.20171031-1)

**Used distribution**
 > Kali Linux RaspberryPi-3-B  [upgraded to latest changes via `sudo apt-get dist-upgrade`.
> root@kali: uname -a
> Linux kali 4.9.59-v7_Re4son-Kali-Pi+ #1 SMP Wed Feb 14 20:50:28 CST 2018 armv7l GNU/Linux

**Unexpected behaviour you saw**
> root@kali: systemctl --user
> Failed to connect to bus: Connection refused
> root@kali: systemctl --user list-units
> Failed to connect to bus: Connection refused

 > I got below error in a window:
`Unable to connect to socket /run/user/0
....... bus: connection refused`
image links:
https://imgur.com/a/2MOGG1O
https://imgur.com/a/Y4Sm3bK

**Steps to reproduce the problem**
i was working on runlevel-3 (command-line mode interface) in Kali Linux [on Raspberry-Pi_3B] and I want to do something in GUI-mode (runlevel-5). before upgrading Kali to last version I hadn't any problem. but now i have it. ;/

How to fix it ?

**Comment by poettering** [comment]
This suggests your distribution doesn't invoke systemd --user for logins. This is generally a distribution issue though. hence please contact your downstream distribution first, and let them escalate this to us if there's really an upstream issue. Thank you for understanding.
