### ISSUE TITLE
Lack of machine-readable output option for timedatectl

### ISSUE THREAD

**Issue by stewartadam** [systemd/systemd#9249]
**Is your feature request related to a problem? Please describe.**
With timedatectl as the canonical way to set/retrieve system time information, it should also provide a machine-readable option output for scripts. `systemctl` offers machine-readable output via either by `systemctl show` (instead of `systemctl status`) or via the `--output=json` option. timedatectl has no equivalent option, requiring use of sed, awk and/or cut to extract information out of timedatectl which is brittle and subject to breakage should timedatectl ever change its output format.

**Describe the solution you'd like**
Support `timedatectl show` command displaying machine-readable information equivalent to what is displayed in `timedatectl status`, and/or add an `--output` option supporting machine-readable outputs, such as JSON.

**Describe alternatives you've considered**
Using a combination of grep/cut/sed/awk to parse out what I need from the human-readable output of `timedatectl status`.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/systemd/systemd/issues/9249#issue-330947159

@stewartadam, is there a reason that you describe the ability to output as JSON and the `show` subcommand to be mutually exclusive? I ask because `hostnamectl status --json=pretty` exists, but not `timedatectl status --json=pretty`, which appears inconsistent.

**Comment by stewartadam** [comment]
I'm not sure I understand - my request was to add machine-parsable output (JSON or otherwise). `timedatectl show` has been since added with the key=value machine-readable format.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/systemd/systemd/issues/9249#issuecomment-2356935083

@stewartadam, I came to this tracker to request JSON output support (since I can use standard tooling if that's implemented) and noticed that this issue phrased the addition of non-JSON and JSON key-value output as mutually exclusive. I'd like to know why, since if it was deliberate, it prevents my request being implemented.

**Comment by stewartadam** [comment]
Not mutually exclusive, those were just examples of ways you can get machine-readable output with `systemctl` :)
