### ISSUE TITLE
logind: Handling of ata_bay "dock" devices

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#9251]
**Is your feature request related to a problem? Please describe.**

I'm tinkering with an old, WinXP-era, Fujitsu Lifebook laptop. It implements hotplugging for its IDE CD-ROM bay through a "dock" device:

    /sys/devices/platform/dock.0
        modalias = acpi:LNXIOBAY:
        type = ata_bay
        docked = 1
        flags = 32

(Apparently that's [a standard feature of ACPI_DOCK](https://cateee.net/lkddb/web-lkddb/ACPI_DOCK.html), and is also used for old-style battery bays.)

Because of this, logind thinks that the laptop is always docked and ignores lid events, even though that's not what the device represents. (There's an actual dock port too, but I think it's shown by a different device.)

**Describe the solution you'd like**

If possible, logind should ignore docks with `type=ata_bay` or `type=battery_bay` sysfs attributes.

(If not... well, the laptop _is_ old and not for daily use, so I won't care too much.)

**Describe alternatives you've considered**

I'm currently using `HandleLidSwitchDocked=` in logind.conf.

**Comment by poettering** [comment]
Hmm, so does that "dock" device show up as input device with an SW_DOCK switch? If so I figure the best approach would be to add a udev rule that drops the "power-switch" udev tag from it. That shozuld be pretty straightforward. A minor patch to `70-power-switch.rules` that filters out ata/battery bay input devices. Any chance you can cook something up for that? wuld be happy to merge that upstream

logind only checks the docked state though two ways: the SW_DOCKED input switches and count of "external displays". It has no specific support for "dock" devices.

**Comment by grawity** [comment]
Hmm, right, I found the input device that shows SW_DOCKED and it's completely unrelated – belongs to the `fujitsu-tablet` driver actually, which appears to be exposing the real dock status.

I wonder if the driver needs `INVERT_DOCK_STATE_BIT` for this model (I don't have a real dock to verify against, unfortunately...)
