### ISSUE TITLE
audit logs generated by "auditctl -m <msg>" don't appear in the journal

### ISSUE THREAD

**Issue by boucman** [systemd/systemd#9258]
**systemd version the issue has been seen with**
> systemd 238
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > debian testing

**Expected behaviour you didn't see**
 > run "journalctl -f _TRANSPORT=audit" in a terminal
> run (as root) "auditctl -m test" on another terminal

An audit trace should appear in the journal  

note that the audit trace seem to be generate by the kernel, the trace can be found in the auditd log

I also tried stopping auditd in case there was a conflict between it and journald, but the problem seems to still be there

**Unexpected behaviour you saw**
 > no message in the journal

**Steps to reproduce the problem**
see above.

This might be a documentation problem, if journald filters out some messages but I did not find any trace of that in journald's documentation

**Comment by poettering** [comment]
do any auditd messages appear at all in the journal? maybe debian turned off journald's audit importing?

**Comment by boucman** [comment]
yes, lots of other messages do... SECCOMP, systemd's own service-start traces etc...

**Comment by poettering** [comment]
how do the messages look like that are sent to audit? do you see them arriving at journald if you strace it?

**Comment by boucman** [comment]
----
time->Tue Jun 12 21:38:41 2018
type=USER msg=audit(1528832321.932:31): pid=15224 uid=0 auid=1000 ses=3 msg='test exe="/sbin/auditctl" hostname=pattern addr=? terminal=pts/0 res=success'

And I do see the following in the strace

recvmsg(4, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000001}, msg_namelen=128->12, msg_iov=[{iov_base={{len=156, type=AUDIT_USER, flags=0, seq=0, pid=0}, "\x61\x75\x64\x69\x74\x28\x31\x35\x32\x38\x38\x33\x32\x34\x35\x31\x2e\x36\x36\x34\x3a\x37\x34\x29\x3a\x20\x70\x69\x64\x3d\x31\x35"...}, iov_len=24575}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=0, uid=0, gid=0}}], msg_controllen=32, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 156

so yes, it is received... (I can generate a more complete strace if you want, but I didn't see anything relevant around that area...)

**Comment by boucman** [comment]
I think I see what's going on...

journal/journald-audit.c line 462 says

        /* Below AUDIT_FIRST_USER_MSG theer are only control messages, let's ignore those */
        if (nl->nlmsg_type < AUDIT_FIRST_USER_MSG)
                return;

now, looking at /usr/include/linux/audit.h

#define AUDIT_USER		1005	/* Message from userspace -- deprecated */
#define AUDIT_FIRST_USER_MSG	1100	/* Userspace messages mostly uninteresting to kernel */

so it's a deprecated but still used message... not sure where to go from here. fix it in journald ? report to auditd ? both ?

**Comment by boucman** [comment]
any direction ? can write a patch if supporting the deprecated message is considered a good idea...
