### ISSUE TITLE
RFE: Suspend-To-Disk after reaching timeout in Suspend-To-RAM state (delayed hibernation)

### ISSUE THREAD

**Issue by Yanpas** [systemd/systemd#926]
Very useful feature, let me larify what I mean:
You have portable device (for example notebook), you suspend it and you want to save your battery, so after several hours it turns on to hibernate to disk and shuts down. So it's like suspend to both, but hibernation is delayed, and device after writing RAM to disk powers off and doesn't consume any power
There are already workaround scripts, so it will be good to implement it
https://www.gonzalomarcote.com/2014/going-from-suspend-into-hibernate-after-some-amount-of-time-on-debian-jessie-aka-suspend-sedation/

**Comment by poettering** [comment]
I am not sure how this is supposed to work... How would we tell the machine to come back from suspend when the battery is running empty? I mean, the system is suspended then, we cannot check that...

Or do you want this to be controlled purely by time? This sounds really racy... When coming back from a suspend, how would we know we are just coming back to get back into hibernaton, or because the user resumed the machine (in which case we really should not)? This sounds like something superficially useful, but when looking at it I don't see how this could really work...

**Comment by Yanpas** [comment]
I think control only by time is pretty enough. AFAIR it's Windows default behavior, so it's useful (your notebook won't discharge fully if you closed the lid and left it for some hours).
I think that checking whether the user or rtc timer woked up the system  - is comparing time of system being suspended. If it is less then timer was set to - then it was user or wake-on-lan or anything else, if it's equal or more then timer - then goto hibernate.
There is already working script for V-Init (description says that couple of modifications will allow to use it with systemd) http://askubuntu.com/questions/12383/how-to-go-automatically-from-suspend-into-hibernate

```
#!/bin/bash
# For other Linux distributions that use systemd, this should still work if you place the script in /usr/lib/systemd/system-sleep instead of /etc/pm/sleep.d. Also, replace the "/usr/sbin/pm-hibernate" command with "systemctl hibernate".
# Script name: /etc/pm/sleep.d/0000rtchibernate
# Purpose: Auto hibernates after a period of sleep
# Edit the "autohibernate" variable below to set the number of seconds to sleep.
curtime=$(date +%s)
autohibernate=7200
echo "$curtime $1" >>/tmp/autohibernate.log
if [ "$1" = "suspend" ]
then
    # Suspending.  Record current time, and set a wake up timer.
    echo "$curtime" >/var/run/pm-utils/locks/rtchibernate.lock
    rtcwake -m no -s $autohibernate
fi

if [ "$1" = "resume" ]
then
    # Coming out of sleep
    sustime=$(cat /var/run/pm-utils/locks/rtchibernate.lock)
    rm /var/run/pm-utils/locks/rtchibernate.lock
    # Did we wake up due to the rtc timer above?
    if [ $(($curtime - $sustime)) -ge $autohibernate ]
    then
        # Then hibernate
        rm /var/run/pm-utils/locks/pm-suspend.lock
        /usr/sbin/pm-hibernate
    else
        # Otherwise cancel the rtc timer and wake up normally.
        rtcwake -m no -s 1
    fi
fi
```

Also Debian Wiki article https://wiki.debian.org/SystemdSuspendSedation

**Comment by poettering** [comment]
What's the timeout windows uses?

On Linux we have no API for querying the resume cause. Patching around this sounds like a gigantic hack... Especially as RTC-based wakeups are not really reliable on many systems... On such systems where the RTC wakeup is missed and the user resumes the machine manually later on the system will immediately go to hiberantion, which is clearly not a good idea.

Sorry, but I am really not convinced this could be any more than a gigantic hack.

Please before looking into something like this, let's at least get a proper API into the kernel that reports the precise wakeup reason to userspace. If we have that, then we can consider hooking this up from userspace. Will close this for now, as I don't think we should hack something up like this without proper kernel support for such a logic.

**Comment by Yanpas** [comment]
Timeout on Windows is 160 minutes and customizable. OK, I've created a ticket for linux https://bugzilla.kernel.org/show_bug.cgi?id=102991
