### ISSUE TITLE
system.slice swappiness is inconsistent with vm.swappiness sysctl

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#9276]
**systemd version the issue has been seen with**
> 238

**Used distribution**
 > CentOS 7

**Expected behaviour you didn't see**
 > if the vm.swappiness sysctl is set, memory.swappiness in system.slice should match it

**Unexpected behaviour you saw**
 > memory.swappiness in system.slice is the kernel default (60 in our case) rather than whatever is set in sysctl.conf

**Steps to reproduce the problem**
This only applies to systems on cgroup1 with `MemoryAccounting` enabled. In cgroup1, when the memory controller is enabled slices will inherit their `memory.swappiness` setting from their parent, and ultimately from the `vm.swappiness` sysctl. systemd applies sysctl settings with the `systemd-sysctl` service, which is run inside `system.slice`, which gets created before it's ever run, which means `system.slice`'s `memory.swappiness` will be set to the kernel default (as sysctl haven't had a chance to get applied yet). 
We found this when we started noticing swapping on a number of production hosts that had `vm.swappiness=0`. The current workaround we came up with is this override for `systemd-sysctl.service`:
```
[Service]
ExecStartPost=/bin/find /sys/fs/cgroup -mindepth 2 -maxdepth 2 -name memory.swappiness -exec /bin/sh -c 'sysctl -n vm.swappiness > "{}"' \;
ExecStartPost=/bin/find /sys/fs/cgroup -mindepth 3 -maxdepth 3 -name memory.swappiness -exec /bin/sh -c 'sysctl -n vm.swappiness > "{}"' \;
ExecStartPost=/bin/find /sys/fs/cgroup -mindepth 4 -maxdepth 4 -name memory.swappiness -exec /bin/sh -c 'sysctl -n vm.swappiness > "{}"' \;
ExecStartPost=/bin/find /sys/fs/cgroup -mindepth 5 -maxdepth 5 -name memory.swappiness -exec /bin/sh -c 'sysctl -n vm.swappiness > "{}"' \;
ExecStartPost=/bin/find /sys/fs/cgroup -name memory.swappiness -exec /bin/sh -c 'sysctl -n vm.swappiness > "{}"' \;
```
Why the multiple `find`s? Because we found that unless these are updated top to bottom, the operation is racy and services can still come up with the incorrect setting. I'm open to suggestions for a less horrible way to do this, but this works for now.

I'm not sure what should be done in systemd to fix this, if anything. In theory, we could special-case `systemd-sysctl` and ensure it runs in a dedicated cgroup before `system.slice` is ever created. We could also implement a version of this hack inside systemd itself, or add a `DefaultMemorySwappiness` knob to system.conf and a per-unit `MemorySwappiness`. Given that this is all v1 specific, I'm not terribly keen on any of these, but at the very least this behavior should be documented somewhere.

Credits to @midom for spotting the issue in the first place and to @hejun for helping troubleshoot.

**Comment by poettering** [comment]
i figure you mean @htejun ?

**Comment by poettering** [comment]
i guess sysctls and cgroups don't mix too well... 

swappiness is a cgroupsv1-only feature, iirc? if it has a future on cgroupsv2 one way out would be to properly expose it as setting... but if it has no future, then i don't think we should do that. @htejun could you comment?

**Comment by htejun** [comment]
It's a cgroup1 only thing and badly implemented. cgroup2 makes sure that nothing does persistent attribute inheritance because of issues like this. I think it'd be worthwhile to document and maybe add a workaround but I don't think systemd needs to add support for the knob at this point.

**Comment by poettering** [comment]
hmm, i think the best approach might be to document somewhere (not entirely sure where though) that people should drop in two things when they want to alter the swappiness: a sysctl file as you did, but also a tmpfiles.d/ snippet that uses the "w" line type to write the swappiness into systemd.slice's attribute early on. with both in place things should be good again.

(in fact, just using a tmpfiles.d/ drop-in and also using it to write the sysctl might be preferable)

**Comment by davide125** [comment]
Given that this is pretty non-obvious and hard to discover, it's worth considering if it would make sense to ship a workaround by default (gated only to cgroup1 hosts of course). I like the idea of using a `tmpfiles.d` dropin, but it does require storing the desired value for swappiness in two places (as I don't think there's an easy way to read the sysctl configs from there). It might be easier to just do a simplified version of the `ExecStartPost` hack that just updates `system.slice`.

**Comment by olifre** [comment]
I share the dislike of duplicating the same information. 

To spell it out, that would mean to drop a file into `tmpfiles.d`, which contains:
```
w   /sys/fs/cgroup/memory/system.slice/memory.swappiness -    -    -    -   10
```
to set swappiness to 10, correct? 
Is it guaranteed that `tmpfiles` runs before child cgroups are created for the `system.slice`?

**Comment by olifre** [comment]
For those finding this thread via a search engine (e.g. because they are hit by the very same systemd bug), it seems that workaround works as described. 

It would still be interesting to learn if there is a guarantee that `tmpfilesd` runs early enough...

**Comment by boucman** [comment]
I'm not a cgroup expert, but my understanding is that cgroup contstraints are propagated unconditionnaly to children, so changing swapiness after the fact shoud work, so it doesn't matter if tmpfiles run after a child is created

But again my understainding of cgroup is limited, so feel free to prove me wrong...

**Comment by olifre** [comment]
> But again my understainding of cgroup is limited, so feel free to prove me wrong...

I think this is different for the `memory.swappiness` setting when `use_hierarchy` is on. At least, when I adjust the `memory.swappiness` on the `system.slice` manually, it is not inherited to running childs, but only to new ones. 
I believe that's why the `find`-trick described above is needed. Emulating that with `tmpfilesd` would only work if it runs before any children of `system.slice`... 
It seemed to work in a first test of mine, though, but I wonder whether that can be relied upon.

**Comment by njaard** [comment]
This workaround makes `vm.swappiness` apply to systemd-managed services. How can I set a specific swappiness with systemd? All the documented approaches have no effect?

**Comment by njaard** [comment]
Can we get comprehensive documentation on how to set swappiness for systemd managed processes and also for specific values for systemd processes?

**Comment by Werkov** [comment]
Hi @njaard. systemd doesn't support setting swappiness on the per-unit basis. (You may find cgroup v2 `MemoryLow=` a useful substitute for your use case.)

**Comment by keszybz** [comment]
I'll cose this. Back in 2018, if somebody wrote a patch, it would have been worthwhile to merge it. This didn't get fixed for v245, so in the best case scenario a fix could be released for v246 somewhere in the middle of the year, and I don't want to merge a hacky workaround for v1 at this point. Please use the hack from https://github.com/systemd/systemd/issues/9276#issuecomment-442514543 if you need to persist on v1 and encounter this issue.

**Comment by vbendel** [comment]
I know this is closed for a long time already, but after testing the tmpfiles approach, it seems it's still racy with other services:
~~~
[root@localhost ~]# cat /etc/tmpfiles.d/swappiness.conf 
w	/sys/fs/cgroup/memory/system.slice/memory.swappiness	-	-	-	-	10
w	/sys/fs/cgroup/memory/user.slice/memory.swappiness	-	-	-	-	10
w	/sys/fs/cgroup/memory/init.scope/memory.swappiness	-	-	-	-	10

[root@localhost ~]# cat $(find /sys/fs/cgroup/memory -name memory.swappiness) | sort -n | uniq -c
     67 10   // some got the '10'
      1 30   // global cgroup
     45 60   // some still at default
~~~

A better approach IMHO is simply to bruteforce change the memory.swappiness on all existing cgroups, ideally right at boot, specifically 'After=systemd-sysctl.service'.

I drafted the following and seems to work OK (definitelly better than tmpfiles :D):
~~~
[root@localhost ~]# cat /usr/bin/cgroup_swappiness_set.sh 
#!/bin/sh

CGROUP_V1_MEMORY_DIR=$(mount | grep "^cgroup .*memory" | cut -d ' ' -f 3)

if [ -z $CGROUP_V1_MEMORY_DIR ]; then
	exit -22  # EINVAL
fi

GLOBAL_SWAPPINESS=$(cat /proc/sys/vm/swappiness)
for cg in $(find $CGROUP_V1_MEMORY_DIR -name memory.swappiness); do echo $GLOBAL_SWAPPINESS > $cg ; done

## EOF

[root@localhost ~]# cat /usr/lib/systemd/system/swappiness_fix.service 
[Unit]
Description=Set all existing -v1 memory cgroups to global vm.swappiness
After=systemd-sysctl.service

[Service]
Type=oneshot
ExecStart=/usr/bin/cgroup_swappiness_set.sh

[Install]
WantedBy=multi-user.target
~~~

Even better would be to ensure that it's set in "pre-order" fashion wrt filesystem structure.

**Comment by Geass-LL** [comment]
Hello, I have encountered the same problem. However, I think this issue is not only limited to the cgroup's memory.swappiness. Some processes have already been started before `systemd-sysctl.service` is launched, and for these processes, the kernel parameters configured by `systemd-sysctl.service` may not take effect. Therefore, can we move up the `systemd-sysctl.service` to start as the first service, and then pull up the related services of `sysinit.target` afterwards?

@keszybz @poettering

**Comment by Werkov** [comment]
> not only limited to the cgroup's memory.swappiness. 

What is an example of such a sysctl?

**Comment by Geass-LL** [comment]
> > not only limited to the cgroup's memory.swappiness.
> 
> What is an example of such a sysctl?

`net.unix.max_dgram_qlen`  controls the maximum length of a datagram socket receive queue. The queue length of socket created before systemd-sysctl.service is `10`, while after systemd-sysctl.service it will be `512`. (I configured net.unix.max_dgram_qlen = 512 in sysctl.conf)

**Comment by poettering** [comment]
systemd bumps the af_unix dgram qlen to 512 during early initialization anyway, and has done so since quite some time. Since 19854865a877a3a4fa3d04550c15a99c0e1187ff (8 years ago!).

if your service relies on sysctls being in effect it should orer itself after systemd-sysctl.service.

also, please do not post support questions on long closed bugs, that's not good style.
