### ISSUE TITLE
Network interface stuck in state "configuring" on a VM with two NICs, DHCP, and the secondary NIC configured with

### ISSUE THREAD

**Issue by MichaelSteffens** [systemd/systemd#9289]
**systemd version the issue has been seen with**
v237

**Used distribution**
 Ubuntu server 18.04 OpenStack cloud image

**Expected behaviour you didn't see**
`networkctl -a` should report all interfaces as "configured" and systemd-networkd-wait-online should complete successfully, once all interface are operational.

**Unexpected behaviour you saw**
`networkctl -a` reports secondary interface (ens4) as "configuring" forever and systemd-networkd-wait-online fails after timeout.

**Steps to reproduce the problem**

Both NICs are supposed to retrieve IP address and MTU from DHCP. In order to avoid duplicate default route and and other settings from DHCP, which are supposed to be unique, I have disabled them all for the secondary interface. The configuration works well, as far as NIC setup is concerned. I can SSH in and use both NICs properly, but only after waiting the timespan used by systemd-networkd-wait-online to time out as result of the wrong status.

/etc/systemd/network/10-ens3.link
```
[Match]
MACAddress=fa:16:3e:7e:d0:0d

[Link]
Name=ens3
WakeOnLan=off
```

/etc/systemd/network/10-ens3.network
```
[Match]
MACAddress=fa:16:3e:7e:d0:0d
Name=ens3

[Network]
DHCP=ipv4

[DHCP]
UseMTU=true
RouteMetric=100
```

/etc/systemd/network/10-ens4.link
```
[Match]
MACAddress=fa:16:3e:13:4a:99

[Link]
Name=ens4
WakeOnLan=off
```

/etc/systemd/network/10-ens4.network
```
[Match]
MACAddress=fa:16:3e:13:4a:99
Name=ens4

[Network]
DHCP=ipv4

[DHCP]
UseDNS=false
UseDomains=false
UseHostname=false
UseNTP=false
UseMTU=true
UseRoutes=false
UseTimezone=false
```

**Comment by yuwata** [comment]
This is already fixed by 223932c786ada7f758a7b7878a6ad2dae0d1e5fb. So, please try to use v239 or recent snapshot. If your issue still exists, please provide relevant logs of networkd with `SYSTEMD_LOG_LEVEL=debug` environment, and reopen this. Thank you.
