### ISSUE TITLE
systemd-cryptsetup: fails to mount LUKS volume that is a file (not a device)

### ISSUE THREAD

**Issue by lorenzhs** [systemd/systemd#9308]
**systemd version the issue has been seen with**
> systemd 238
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian unstable (sid)

**Expected behaviour you didn't see**
 > LUKS volume at `/path/to/luksvolume` (it's a file, not a device) should be mounted at boot

**Unexpected behaviour you saw**
 > Mounting the LUKS volume fails. I have to switch to the console and `systemctl restart systemd-cryptsetup@foo.service` manually. This succeeds and works around the issue, but has to be done at every boot.

`/etc/crypttab`:
```
foo /path/to/luksvolume /etc/luks-keys/foo nofail,discard,luks
```

Log, including the manual restart of the systemd-cryptsetup unit:
```
$ journalctl -b -1 -u systemd-cryptsetup@*
-- Logs begin at Fri 2016-04-01 10:13:18 CEST, end at Fri 2018-06-15 08:55:34 CEST. --
Jun 14 09:34:24 i10pc82 systemd-cryptsetup[375]: Set cipher aes, mode xts-plain64, key size 256 bits for device /path/to/luksvolume.
Jun 14 09:34:26 i10pc82 systemd-cryptsetup[375]: Failed to activate with key file '/etc/luks-keys/foo': Invalid argument
Jun 14 09:35:33 i10pc82 systemd[1]: systemd-cryptsetup@foo.service: Main process exited, code=killed, status=15/TERM
Jun 14 09:35:33 i10pc82 systemd[1]: systemd-cryptsetup@foo.service: Failed with result 'signal'.
Jun 14 09:35:33 i10pc82 systemd[1]: Stopped Cryptography Setup for foo.
Jun 14 09:35:33 i10pc82 systemd[1]: Starting Cryptography Setup for foo...
Jun 14 09:35:33 i10pc82 systemd-cryptsetup[1172]: Set cipher aes, mode xts-plain64, key size 256 bits for device /path/to/luksvolume.
Jun 14 09:35:35 i10pc82 systemd[1]: Started Cryptography Setup for foo.
```

**Steps to reproduce the problem**
> Happens at every boot. Haven't tried reproducing on another machine, but I would suppose that this would happen for every LUKS volume that is a file rather than a device.

**Comment by lorenzhs** [comment]
Unit file, if that helps:
```$ systemctl cat systemd-cryptsetup@foo.service
# /run/systemd/generator/systemd-cryptsetup@foo.service
# Automatically generated by systemd-cryptsetup-generator

[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
IgnoreOnIsolate=true
After=cryptsetup-pre.target
RequiresMountsFor=/etc/luks-keys/foo
RequiresMountsFor=/path/to/luksvolume

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
KeyringMode=shared
ExecStart=/lib/systemd/systemd-cryptsetup attach 'foo' '/path/to/luksvolume' '/etc/luks-keys/foo' 'nofail,discard,luks'
ExecStop=/lib/systemd/systemd-cryptsetup detach 'foo'
```

**Comment by JohannesBuchner** [comment]
Is this the same bug as  #1541?

**Comment by lorenzhs** [comment]
I saw that but I don't think it's the same issue. My workaround is to `systemctl restart systemd-crytsetup@foo.service`, so it's obviously supported by the `systemd-cryptsetup` logic. It's just that something isn't there yet when that unit is started during boot. The `RequiresMountsFor` is there, though.

If I understand your bug correctly, the LUKS filesystem mounts, but the filesystem *inside* it doesn't? For me, the LUKS filesystem doesn't mount correctly during boot. Sounds like a different issue.

**Comment by arvidjaar** [comment]
> The `RequiresMountsFor` is there, though.

It works only if `systemd` is aware of mount units that lead to this path. Apparently this information is missing initially. Without seeing your actual configuration of mountpoints it is impossible to make any guess as to why it happens. Output of `systemctl show systemd-cryptsetup@foo.service` and `systemctl cat systemd-cryptsetup@foo.service` immediately after it failed may give some hints.

**Comment by lorenzhs** [comment]
The output of systemctl cat is in my comment above. Both the LUKS volume and key file are on the root file system, as per the same comment. I can’t provide the output of systemctl show until next week, sorry.

**Comment by poettering** [comment]
hmm, this error msg is writted showing th result of the crypt_activate_by_keyfile_offset() call, i.e. it's an error generated by libcryptsetup, and not one by systemd-cryptsetup itself. 

It's EINVAL, which is pretty generic. My educated guess though is that this might be casue by some crypto module being missing. When does this fail? During the initrd? When does this work? Much later, when the system is fully up? If so, it might simply be that some crypto module is missing in the initrd, or has not been loaded yet.

**Comment by medhefgo** [comment]
In src/basic/crypt-util.c we forward cryptsetup logs using debug level. So maybe you can get something specific when you boot with debug logging.

We should probably translate cryptsetup log levels there so people get better information on errors...

**Comment by lorenzhs** [comment]
I booted with `debug log_buf_len=16M`, the log file is here: https://4z2.de/systemd_9308_debug_log.txt -- the crypttab entry's name is actually `lorenz` (instead of `foo`) and the path is different, too. Renaming everything would just end up breaking something.

**Comment by lorenzhs** [comment]
Ah, kernel config in case it helps: (it's a stock Debian unstable kernel): http://4z2.de/config-4.16.0-2-amd64.txt

Not sure when exactly the failure occurs.

**Comment by medhefgo** [comment]
> Jun 25 12:44:56 i10pc82 systemd-cryptsetup[354]: Attaching loopback device failed (loop device with autoclear flag is required).

So for some reason libcryptsetup fails to setup the loopback device. This smells like something is going wrong with loopback kernel module autoloading... Does booting with modules_load=loop fix this?

**Comment by lorenzhs** [comment]
Booting with `modules_load=loop` indeed fixes the issue, thank you!

Does that mean the issue is with `tmpfiles` not creating `/dev/loop-control` early enough, or is it an issue with Debian's `util-linux`? It sounds vaguely related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754411 (2014)

**Comment by medhefgo** [comment]
I think we're missing a dependency on systemd-tmpfiles-setup-dev.service which is responsible for creating loop-control afaiks. In your logs it seems to be created after we try cryptsetup.

Can you try adding "After=systemd-tmpfiles-setup-dev.service" in the Unit section of the service? Copying the generated unit into /etc/systemd/system and editing it should do. And then boot without the kernel option of course.

**Comment by lorenzhs** [comment]
Nope that does not work. From the logs:
```
-- Reboot --
Jun 26 12:38:08 i10pc82 systemd-cryptsetup[363]: Set cipher aes, mode xts-plain64, key size 256 bits for device /path/to/luksvolume.
Jun 26 12:38:10 i10pc82 systemd-cryptsetup[363]: Failed to activate with key file '/etc/luks-keys/foo': Invalid arg
Jun 26 12:39:30 i10pc82 systemd[1]: systemd-cryptsetup@foo.service: Main process exited, code=killed, status=15/TER
Jun 26 12:39:30 i10pc82 systemd[1]: systemd-cryptsetup@foo.service: Failed with result 'signal'.
Jun 26 12:39:30 i10pc82 systemd[1]: Stopped Cryptography Setup for foo.
Jun 26 12:39:30 i10pc82 systemd[1]: Starting Cryptography Setup for foo...
Jun 26 12:39:30 i10pc82 systemd-cryptsetup[1127]: Set cipher aes, mode xts-plain64, key size 256 bits for device /path/to/luksvolume.
Jun 26 12:39:32 i10pc82 systemd[1]: Started Cryptography Setup for foo.
```
and
```
-- Reboot --
Jun 26 12:38:10 i10pc82 systemd[1]: Starting Create Static Device Nodes in /dev...
Jun 26 12:38:10 i10pc82 systemd-tmpfiles[408]: [/usr/lib/tmpfiles.d/postgresql.conf:2] Line references path below legacy directory /var/run/, updating /var/run/postgresql → /run/postgresql; please update the tmpfiles.d/ drop-in file accordingly.
Jun 26 12:38:10 i10pc82 systemd-tmpfiles[408]: [/usr/lib/tmpfiles.d/xpra.conf:3] Line references path below legacy directory /var/run/, updating /var/run/xpra → /run/xpra; please update the tmpfiles.d/ drop-in file accordingly.
Jun 26 12:38:10 i10pc82 systemd[1]: Started Create Static Device Nodes in /dev.
Jun 26 12:40:09 i10pc82 systemd[1]: Stopped Create Static Device Nodes in /dev.
```

**Comment by medhefgo** [comment]
Silly me, an After= dependency is needed too.

**Comment by lorenzhs** [comment]
Ah yes, that does the trick. With the `After=` dependency, it works. Thanks @medhefgo!

**Comment by poettering** [comment]
can you send a patch fixing this for good?

**Comment by lorenzhs** [comment]
The generated unit with #9436 is:
```sh
$ ./systemd-cryptsetup-generator foo a b
$ cat foo/systemd-cryptsetup@foo.service
# Automatically generated by systemd-cryptsetup-generator

[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
IgnoreOnIsolate=true
After=cryptsetup-pre.target
RequiresMountsFor=/etc/luks-keys/foo
RequiresMountsFor=/path/to/luksvolume
Requires=systemd-tmpfiles-setup-dev.service
After=systemd-tmpfiles-setup-dev.service

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
KeyringMode=shared
ExecStart=/lib/systemd/systemd-cryptsetup attach 'foo' '/path/to/luksvolume' '/etc/luks-keys/foo' 'nofail,discard,luks'
ExecStop=/lib/systemd/systemd-cryptsetup detach 'foo'
```
