### ISSUE TITLE
Dropping copyright lines from frequent contributors

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#9320]
Information about who contributed to which file is already covered by `git log` and `git blame` much better. The "copyright by" lines that added manually are often out of date and just unnecessary boilerplate. In particular, all works are covered by copyright without any explicit notice since the 1971 Berne Convention.

Following #9274 and #9302, I'd like to drop the remaining "Copyright" lines. Explicit permission from all "owners" of such a line is requested. There is a long tail of names with just one or a few entries, and getting an answer from all those people would be hard, so I'm targeting just the more frequent contributors for now. **If you are OK with dropping *your* copyright line, please say so in this ticket.**
(And If you're *not* OK, also please say so, so we can keep track.) **I'll prepare a patch once there's enough answers.**

/cc @teg, @kaysievers, @ssahani, @phomes, @dvdhrm, @ronnychevalier, @zonque, @bluetech, @michich, @haraldh, @titanous, @rojkov, @yuwata, @shawnl, @intelfx 

[I used
```sh
git grep -h 'Copyright' | sed -r -n 's/.*Copyright.*[0-9,-]+\s*(.+)\s*($|<).*/\1/p'|sort|uniq -c|sort -g
```
but it's counting is terribly broken.]

**Comment by intelfx** [comment]
> If you are OK with dropping your copyright line, please say so in this ticket

Yes, I'm of course fine with that.

**Comment by ronnychevalier** [comment]
On Mon, Jun 18, 2018 at 10:38 AM Zbigniew Jędrzejewski-Szmek
<notifications@github.com> wrote:
>
> Information about who contributed to which file is already covered by git log and git blame much better. The "copyright by" lines that added manually are often out of date and just unnecessary boilerplate. In particular, all works are covered by copyright without any explicit notice since the 1971 Berne Convention.
>
> Following #9274 and #9302, I'd like to drop the remaining "Copyright" lines. Explicit permission from all "owners" of such a line is requested. There is a long tail of names with just one or a few entries, and getting an answer from all those people would be hard, so I'm targeting just the more frequent contributors for now. If you are OK with dropping your copyright line, please say so in this ticket.

Ok for me

**Comment by rojkov** [comment]
I'm OK.

**Comment by teg** [comment]
I'm ok

**Comment by zonque** [comment]
Sure, go ahead!

**Comment by dvdhrm** [comment]
Sure.

**Comment by michich** [comment]
I am OK with this.

**Comment by titanous** [comment]
Sure.

**Comment by ssahani** [comment]
ok

**Comment by yuwata** [comment]
Ok.

**Comment by keszybz** [comment]
@bluetech, @davidstrauss, @dbuch, @victorenator, @sebth, @pabigot, @michaelolbrich @Mic92, @zx2c4, @flokli, @filbranden, @falconindy, @rhatdan, @martinpitt ?

**Comment by poettering** [comment]
Hmm, reopening, because afaics we are still lacking some responses.

**Comment by falconindy** [comment]
Ack.

**Comment by flokli** [comment]
Sure, ACK.

**Comment by pabigot** [comment]
OK.

**Comment by martinpitt** [comment]
ACK (I don't care about these lines really)

**Comment by rhatdan** [comment]
ACK

**Comment by victorenator** [comment]
OK

**Comment by filbranden** [comment]
OK with me.

**Comment by Mic92** [comment]
ok.

**Comment by dbuch** [comment]
Ok

**Comment by haraldh** [comment]
ok

**Comment by sebth** [comment]
OK.

**Comment by keszybz** [comment]
@mbiebl, @gregkh,  @mvollmer, @keybuk, @maximlevitsky, @hreinecke, @marineam, @zx2c4, @andir, @mlankhorst, @joshtriplett, @jsynacek ?

**Comment by keszybz** [comment]
@philips ?

**Comment by mbiebl** [comment]
sure

**Comment by andir** [comment]
OK for me.

**Comment by michaelolbrich** [comment]
ok

**Comment by philips** [comment]
Fine by me @philips

**Comment by maximlevitsky** [comment]
Fine with me too.

Best regards,
      Maxim Levitsky

**Comment by keybuk** [comment]
No.

**Comment by piotrdrag** [comment]
Sure, OK.

**Comment by mvollmer** [comment]
Ok.

**Comment by keszybz** [comment]
Most copyright lines were dropped. A few remain, either for authors who refused or didn't reply. Let's close this.

**Comment by Conan-Kudo** [comment]
I'm okay with this for everything but `macros.systemd.in` and `triggers.systemd.in` files, since these files have to be copied out for people to use it in packaging, and so it's decoupled from the source tree.
