### ISSUE TITLE
SYSTEMD_WANTS= is not honored anymore

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#9323]
```
$ cat /etc/udev/rules.d/debug-rdma.rules 
KERNEL=="vdb", ENV{SYSTEMD_WANTS}+="rdma-hw.target"
$ reboot
...
$ systemctl status sys-devices-pci0000:00-0000:00:05.0-virtio2-block-vdb.device rdma-hw.target
● sys-devices-pci0000:00-0000:00:05.0-virtio2-block-vdb.device - /sys/devices/pci0000:00/0000:00:05.0/virt
   Loaded: loaded
   Active: active (plugged) since Mon 2018-06-18 12:00:10 CEST; 1min 16s ago
   Device: /sys/devices/pci0000:00/0000:00:05.0/virtio2/block/vdb

● rdma-hw.target - RDMA Hardware
   Loaded: loaded (/etc/systemd/system/rdma-hw.target; static; vendor preset: disabled)
   Active: inactive (dead)
```

Restoring v238 makes the bug go away. The regression is probably due to https://github.com/systemd/systemd/pull/9200.

**Comment by fbuihuu** [comment]
BTW tested with master at 4b650021751ccd404dcb329ef5e312c8a93f7ce2

**Comment by poettering** [comment]
Any chance you can provide a reproducer that involves hardware normal people might have? i.e. something i can easily reproduce on my laptop without anything fancy?

**Comment by keszybz** [comment]
Yep, I can reproduce this easily with systemd-239-0.1.git4b65002.fc29.x86_64.

**Comment by poettering** [comment]
how precisely did you reproduce it? did you add your udev rule to the initrd?

@fbuihuu did you add your udev rule to the initrd? did the device appear during the initrd already, or during later boot? does your initrd run systemd?

do you see the dep in place in "systemctl show" on the device unit after boot?

my educated guess is that the udev rule was not in effect in the initrd and the device showed up then. We'd then not trigger the dep again. And I'd argue rightfully so actually...

**Comment by poettering** [comment]
hmm, so i am pretty sure my theory is correct. I have tested a couple of things, and they indicate it is right, for example a device that shows up after the initrd transition (i used /dev/loop0 for that as i can easily schedule its creation myself) correctly pulls in its deps.

 Question is if this is something we should do anything about. There are two options:

1. Leave it the way this is, reflecting the rule that serialization+deserialization should not pull in any deps then possibly available in a new and changed configuration.

2. Decide that "switch-root" is something different from "daemon-reload", and thus in that case we should trigger all deps now configured again.

(3. There's also possibly a third option, somewhere in the middle where we trigger deps again only for .device units bot not for the other unit types)

I think am pretty strongly leaning towards option 1 though. And option 3 is really fricking ugly.

**Comment by fbuihuu** [comment]
Well 2. is the behavior systemd had always implemented so far so changing this at this point doesn't sound a good idea especially since now all services (and all theirs deps) that needs to be triggered when a device pops up have to be included in initrd.
