### ISSUE TITLE
Unclear documentation of coredumpctl MATCH

### ISSUE THREAD

**Issue by stbergmann** [systemd/systemd#9324]
At least with systemd-238-8.git0e0aa59.fc28.x86_64 and with current sources, `man coredumpctl` states in section "MATCHING":
```
       MATCH
           General journalctl predicate (see journalctl(1)). Must contain an equals sign ("=").
```
but the journalctl man page doesn't explain what a "journalctl predicate" would be (there is no mention of "predicate" on that page).

**Comment by kirbyfan64** [comment]
FWIW I believe it's referring to the journalctl match syntax (in the second paragraph of the man page's *description* section).
