### ISSUE TITLE
systemd.service documentation on TimeoutStopSec is incorrect

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#9325]
This is reproducible with the current master (commit 98008caa94a7aca76297ecdca86a23f460386429).

The current systemd.service man page say:
> Configures the time to wait for stop. If a service is asked to stop, but does not terminate in the specified time, it will be terminated forcibly via SIGTERM, and after another timeout of equal duration with SIGKILL (see KillMode= in systemd.kill(5)).

What actually happens is that the SIGTERM is issued **immediately** after the stop command is issued. If that for some reason doesn't terminate the process, then after the timeout specified in TimeoutStopSec=, the process is sent a SIGKILL.

Reproducer:
1) \# cat example.c
```
#include <stdio.h>
#include <unistd.h>
#include <signal.h>
int main (int argc, char **argv) {
    signal(SIGTERM, SIG_IGN);
    sleep(300);
}
```
2) \# cat test-unit.service
```
[Unit]
Description=Test timeout
[Service]
Type=simple
ExecStart=/usr/local/bin/example
TimeoutStopSec=20
```
3) Copy the compiled example to /usr/local/bin, run the test unit.
4) Attach gdb to the service's process and run `systemctl stop test-unit`.
5) Observe that the SIGTERM is sent immediately. After 20 seconds, SIGKILL follows.

**Comment by arvidjaar** [comment]
> after the stop command is issued

Service needs to have `ExecStop` command for this to be effective. Otherwise the only way to "ask service to stop" is to send it signal. So this is really documentation issue. `TimeoutStopSec` defines max time each `ExecStop*` command may take. If any of them times out, subsequent commands are skipped and service gets `SIGTERM`.
