### ISSUE TITLE
'systemd-mount --owner' fails with unrecognized mount option

### ISSUE THREAD

**Issue by occivink** [systemd/systemd#9327]
**systemd version the issue has been seen with**
238

**Used distribution**
 arch linux

**Unexpected behaviour you saw**
Running:
`systemd-mount --owner occivink /dev/sdc1 ~/usb`
fails. journalctl mentions: 
`Unrecognized mount option "gid=1000(null)" or missing value`

**Expected behaviour you didn't see**

The disk is mounted properly.

**Steps to reproduce the problem**

Run the command mentioned above with appropriate user and block device. Note that manually specifying the uid and gid like so:
`systemd-mount --options uid=1000,gid=1000 /dev/sdc1 ~/usb`
works as expected.

The only difference between the two generated .mount files is this line
`Options=uid=1000,gid=1000(null)` <- --owner case
`Options=uid=1000,gid=1000` <- --options case

Note that the same issue is reproducible if `WHERE` is not specified.

**Comment by yuwata** [comment]
Fix is waiting in #9329.

**Comment by occivink** [comment]
Thanks!
