### ISSUE TITLE
journald frequently core dumps

### ISSUE THREAD

**Issue by phw** [systemd/systemd#933]
I have experienced this for a while now, journald suddenly crashes and it seems it causes my whole user session (running under gnome-shell) to crash, too. Just happened again with systemd 224 under Arch Linux, but I had similar crashes with earlier versions of systemd but I cannot say for sure in which release it started. I have suspected that this happens when journald clean the log files as it often happened when my `/var` partition (10GB, ext4) was pretty full, but on the latest crash it had still 2.3 GB of space available.

Here is the output of journald:

```
Aug 11 20:29:38 zoidberg systemd-journal[2224]: Permanent journal (/var/log/journal/) is currently using 120.0M.
                                                Maximum allowed usage is set to 995.1M.
                                                Leaving at least 1.4G free (of currently available 2.2G of space).
                                                Enforced usage limit is thus 840.9M.
Aug 11 20:29:38 zoidberg systemd[1]: systemd-journald.service: Main process exited, code=dumped, status=6/ABRT
Aug 11 20:29:38 zoidberg systemd[1]: systemd-journald.service: Unit entered failed state.
Aug 11 20:29:38 zoidberg systemd[1]: systemd-journald.service: Failed with result 'core-dump'.
Aug 11 20:29:38 zoidberg systemd[1]: systemd-journald.service: Service has no hold-off time, scheduling restart.
Aug 11 20:29:38 zoidberg systemd[1]: Stopped Flush Journal to Persistent Storage.
Aug 11 20:29:38 zoidberg systemd[1]: Stopping Flush Journal to Persistent Storage...
Aug 11 20:29:38 zoidberg systemd[1]: Stopped Journal Service.
Aug 11 20:29:38 zoidberg systemd[1]: Starting Journal Service...
Aug 11 20:29:38 zoidberg kernel: traps: gnome-shell[2303] trap int3 ip:7f76faa7fac0 sp:7ffd7e6faff0 error:0
Aug 11 20:29:38 zoidberg systemd-coredump[2215]: Detected coredump of the journal daemon itself, diverted to /var/lib/systemd/coredump/core.systemd-journal.0.61a3878b4ca348389d84605680cfee34.201.1439317759000000.lz4.
Aug 11 20:29:38 zoidberg systemd[1]: Stopping User Manager for UID 1000...
Aug 11 20:29:38 zoidberg systemd[1]: Stopped User Manager for UID 1000.
Aug 11 20:29:38 zoidberg systemd[1]: Removed slice user-1000.slice.
Aug 11 20:29:38 zoidberg systemd-journal[2224]: Journal started
Aug 11 20:28:18 zoidberg polkitd[562]: Operator of unix-session:c2 successfully authenticated as unix-user:phw to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.77 [systemctl start mongodb.service] (owned by unix-user:phw)
Aug 11 20:28:18 zoidberg systemd[1]: Started High-performance, schema-free document-oriented database.
Aug 11 20:29:38 zoidberg systemd[1]: Started Journal Service.
Aug 11 20:28:18 zoidberg polkitd[562]: Unregistered Authentication Agent for unix-process:1716:6091 (system bus name :1.76, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.utf8) (disconnected from bus)
Aug 11 20:29:07 zoidberg systemd[1]: systemd-journald.service: Watchdog timeout (limit 1min)!
Aug 11 20:28:51 zoidberg obexd[1892]: OBEX daemon 5.33
Aug 11 20:29:38 zoidberg systemd-logind[532]: Removed session c2.
Aug 11 20:29:36 zoidberg gnome-session[954]: WARNING: Lost name on bus: org.gnome.SessionManager
Aug 11 20:29:38 zoidberg systemd[934]: Stopped target Default.
Aug 11 20:29:36 zoidberg gnome-session[954]: WARNING: App 'gnome-settings-daemon.desktop' exited with code 1
Aug 11 20:29:38 zoidberg systemd[934]: Stopped target Basic System.
Aug 11 20:29:37 zoidberg polkitd[562]: Unregistered Authentication Agent for unix-session:c2 (system bus name :1.57, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.utf8) (disconnected from bus)
Aug 11 20:29:38 zoidberg systemd[934]: Stopped target Sockets.
Aug 11 20:29:37 zoidberg gnome-session[954]: WARNING: App 'gnome-shell.desktop' exited with code 1
Aug 11 20:29:38 zoidberg systemd[934]: Reached target Shutdown.
Aug 11 20:29:38 zoidberg gdm-password][856]: pam_unix(gdm-password:session): session closed for user phw
Aug 11 20:29:38 zoidberg systemd[934]: Stopped target Timers.
Aug 11 20:29:38 zoidberg systemd[936]: pam_unix(systemd-user:session): session closed for user phw
Aug 11 20:29:38 zoidberg systemd[934]: Starting Exit the Session...
Aug 11 20:29:38 zoidberg systemd[934]: Stopped target Paths.
Aug 11 20:29:38 zoidberg systemd[934]: Received SIGRTMIN+24 from PID 2312 (kill).
Aug 11 20:29:38 zoidberg systemd-coredump[2306]: Process 2303 (gnome-shell) of user 1000 dumped core.
```

A core dump file `/var/lib/systemd/coredump/core.systemd-journal.0.61a3878b4ca348389d84605680cfee34.201.1439317759000000.lz4` got written, but I am not sure whether it is usable. `coredumpctl list` doesn't show it (but the one for the later gnome-shell crash is available).

Might be related to #917, but from the symptoms I cannot say for sure.

**Comment by poettering** [comment]
well, journald's own backtraces are not included in the journal (i mean, it's the journal that crashed after all...), hence you need to access them directly to get a stacktrace, the "coredumpctl" will not work for this special case (as it just queries the journal searching for coredumps...).

However, there's one problem: you have enabled lz4 compression for coredumps, but that's not really supported and there are no command line tools that can decompress that format. Please turn off lz4 compression (either by turning off lz4 when building systemd, or by editing coredump.conf), and then regenerate the coredump. Finally, use gdb to extract the stacktrace from the coredump file.

**Comment by phw** [comment]
Thanks for the feedback. Looks like lz4 was the default on my system, I have now disabled compression. Unfortunately this issue is not easy to reproduce as it happens often enough to be annoying, but so far I have found no reliable way to trigger it. Will post back once I know more.

**Comment by poettering** [comment]
Closing, due to lack of response. Feel free top reopen if the issue resurfaces.

**Comment by phw** [comment]
Great. Funnily I just thought about closing this one today myself.

Despite this happened frequently before I reported it's running fine ever since. Quite possible this was fixed in some upgrade if whatever component was causing this.

**Comment by danielschonfeld** [comment]
I am not sure these are the same bug but I can say we experience the same symptoms on CoreOS... https://github.com/coreos/bugs/issues/334

So far no real feats about what's causing it tho I have a feeling its something during fsync on disks that are slow in the cloud

**Comment by poettering** [comment]
@danielschonfeld we increased the watchdog timeout in the most recent version, which should hopefully help with slow fsync(). To identify whether a crash is of this kind, please look at the backtrace, verify it was triggered due to SIGABRT and that no assert() invocation of any kind is in the backtrace. If so, it's almost certainly one of the watchdog timeout issues due to fsync() being slow. 

The stacktrace should also usually show that execution is in code shortly after fsync(). As the syscall itself is non-interruptible, it won't show in the backtrace, but the code immediately after usually should be in there.
