### ISSUE TITLE
DHCPServer: forward any configured DNS servers

### ISSUE THREAD

**Issue by wvh** [systemd/systemd#9347]
Hello,

I'm trying to get systemd-networkd to forward my system's DNS servers to systemd-nspawn virtual machines by means of the internal `DHCPServer`. Both host and virtual machines are running systemd-networkd and systemd-resolved. The host uses NetworkManager but delegates dns to systemd-resolved; `systemd-resolve --status` shows DNS servers for the link interface. The systemd-nspawn machines receive leases but those don't contain any DNS servers so they use the default (8.8.8.8 and friends). This bug report / request is about getting the host system's DNS servers into the virtual machines.

I checked the code in networkd-link.c, function `link_push_uplink_dns_to_dhcp_server`, and I think only statically defined DNS servers and those DNS servers that come from systemd dhcp enabled links are copied. There's no debugging output inside that function to see which path the code takes or which servers get added, but I assume it's none.

If so, this is a feature request to enable forwarding *any* configured DNS servers for that network device or even the host system DNS servers (those under "Global" in systemd-resolve output) to the internal DHCP server and clients, even if the devices or DHCP are not managed by systemd directly.

Otherwise, this is a bug report about networkd failing to forward DNS settings to DHCP clients.

Here is debugging output from systemd-networkd, showing that the DNS server information is copied to the internal DHCP server:

```
Jun 20 10:28:30 arch systemd-networkd[27979]: Copying DNS server information from enp0s31f6
Jun 20 10:28:30 arch systemd-networkd[27979]: DHCP SERVER: STARTED
Jun 20 10:28:30 arch systemd-networkd[27979]: vz-machines: Offering DHCPv4 leases
Jun 20 10:28:30 arch systemd-networkd[27979]: vz-machines: Setting addresses
Jun 20 10:28:30 arch systemd-networkd[27979]: vz-machines: Updating address: 10.0.0.1/24 (valid forever)
Jun 20 10:28:30 arch systemd-networkd[27979]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_366 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=95 reply_cook[...]
Jun 20 10:28:30 arch systemd-networkd[27979]: vz-machines: Addresses set
Jun 20 10:28:30 arch systemd-networkd[27979]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_366 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=96 reply_cook[...]
Jun 20 10:28:30 arch systemd-networkd[27979]: DHCP SERVER: DISCOVER (0xcc0e7ccd)
Jun 20 10:28:30 arch systemd-networkd[27979]: DHCP SERVER: OFFER (0xcc0e7ccd)
Jun 20 10:28:30 arch systemd-networkd[27979]: DHCP SERVER: REQUEST (selecting) (0xcc0e7ccd)
Jun 20 10:28:30 arch systemd-networkd[27979]: DHCP SERVER: ACK (0xcc0e7ccd)
```

And here is the output from systemd-resolve for that host device; notice the DNS server(s):
```
# systemd-resolve --status enp0s31f6
Link 2 (enp0s31f6)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 128.214.20.30
          DNS Domain: lib.helsinki.fi
```

Here is a lease from the virtual machine (I used dhclient to get this one), note there are no name servers:
```
lease {
  interface "host0";
  fixed-address 10.0.0.242;
  option subnet-mask 255.255.255.0;
  option routers 10.0.0.1;
  option dhcp-lease-time 3600;
  option dhcp-message-type 5;
  option dhcp-server-identifier 10.0.0.1;
  option unknown-101 "Europe/Helsinki";
  renew 3 2018/06/20 07:58:52;
  rebind 3 2018/06/20 08:22:20;
  expire 3 2018/06/20 08:29:50;
}
```

And here is the (pretty default) .network file for the virtual system, with `UseDNS` explicitly enabled:
```
[Match]
Virtualization=container
Name=host0

[Network]
DHCP=ipv4
LinkLocalAddressing=yes
LLMNR=true
LLDP=yes
EmitLLDP=customer-bridge

[DHCP]
UseDNS=yes
UseTimezone=yes
UseHostname=yes
```

The host is an up to date Arch Linux system:
```
systemd 238
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by poettering** [comment]
so the issue is casued because resolved picks up DNS server information from all kinds of sources, including networkd and NetworkManager, but networkd never picks up DNS server information back from resolved. 

I wonder if we can find a conceptually sane way to hook this up, but this kind of bi-directional loop between resolved and networkd makes all my mental alarm bells ring. i.e. we really shouldn't create a feedback loop where networkd feeds into resolved which feeds back into resolved.

**Comment by htot** [comment]
I have a similar problem, but a different conclusion. I have an eth up link and wlan down (wifi AP gateway with nat, using hostapd). On start, on wlan the dns server is copied (same as in the above log) then dhcp server is started. Then, eth receives its config through dhcp client.

My conclusion is: dns server info is copied at the time when there is none yet available.

Now I could solve this probably by delaying wlan dhcp server to after eth link is established. But what we actually would want is wlan to be independent of eth and gateway running it's own relaying dns server. In such a way that without up link, at least the gateway's dns would hold registered wlan clients addresses.

**Comment by htot** [comment]
Now checking the code if find it surprising that in the log "Copying DNS server information from" is not followed by "Failed to set DNS server for DHCP server, ignoring".

This may be caused by [networkd-link.c#L1154](https://github.com/systemd/systemd/blob/7a3bc5a8e52acbaf68cad61aa96b5f7093adc005/src/network/networkd-link.c#L1154), link_push_uplink_dns_to_dhcp_server() returns 0 when nothing found.

**Comment by elmarco** [comment]
Still there, and that's making systemd-nspawn more difficult to use when NM is used on the host.
link_push_uplink_dns_to_dhcp_server() is called correctly, but sd-nd is unaware of its dns configuration.

@poettering would it be possible to add another fallback in this case on resolve1.Manager.DNS dbus property? Or is this still an alarming feedback loop you talked about?
