### ISSUE TITLE
KEY_102ND wrongly mapped on MSI gs65

### ISSUE THREAD

**Issue by akshit-sharma** [systemd/systemd#9361]
**systemd version the issue has been seen with**
> systemd 237

**Used distribution**
 > Linux version 4.15.0-23-generic (buildd@lgw01-amd64-055) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 (Ubuntu 4.15.0-23.25-generic 4.15.18)

**Expected behaviour you didn't see**
 > KEY_102ND is wrongly mapped. It should behave same as KEY_BACKSLASH.

**Unexpected behaviour you saw**
 > KEY_102ND prints "<" and ">" with shift.

**Steps to reproduce the problem**
I have a MSI gs65. It has an extra key between <Space> and <Alt Gr>. That key is same as KEY_BACKSLASH but for some reason, it behaves as "<" and ">" with shift. How can I change it and send a pull request for the same ?

Thank you

**Comment by poettering** [comment]
I figure this can be closed as #9390 has been merged.
