### ISSUE TITLE
Add a parameter equal to ConfigurationDirectory

### ISSUE THREAD

**Issue by aledomu** [systemd/systemd#9362]
**Is your feature request related to a problem? Please describe.**
I'm making a service unit file for an app whose config location isn't fixed, so I have to indicate it in `ExecStart`. I'd like to specify the `ConfigurationDirectory` value and reuse that location in other unit directives so it follows that value.

**Describe the solution you'd like**
A systemd unit parameter that takes the value of `ConfigurationDirectory`. `%c` for example. Maybe this could be done to the other `*Directory` directives as well?

**Describe alternatives you've considered**
None apart from dealing with the duplication.

**Comment by yuwata** [comment]
Please see the comment in https://github.com/systemd/systemd/commit/03fc9c723cfc59467a7fccc305f34273f8564b25.

**Comment by yuwata** [comment]
BTW, I guess you can use template unit, e.g, foo@path.service, then use %i at both ExecStart= and ConfigurationDirectory=. Or, name the service e.g. foo-path.service, then use %j. See systemd.exec(5).

**Comment by poettering** [comment]
One thing we should really add is that when ConfigurationDirectory= is set we implicitly add an env var for each invoked process, i.e. $CONFIGURATION_DIRECTORY= or so (or maybe $SERVICE_CONFIGURATION_DIRECTORY, i.e. something that is unlikely to clash with any existing env var used by something else). And similar for RuntimeDirectory= and so on. In case multiple ConfigurationDirectory= lines are used we should probably concatenate the resulting paths with ":" separators.

With that in place your process could then check these env vars to figure out where to read its data from. Given that we do minimal env var replacement in ExecXYZ= lines you could also use that directly in those lines then.

**Comment by aledomu** [comment]
@yuwata Ok, I didn't knew the parser interpreted everything in a serial fashion. I could use a template unit as you said, but the problem is that I can't take the absolute path that ConfigurationDirectory chose when running the service.

@poettering I initially thought about env vars but there is the risk of name clashes, as you say. Beware there are other init systems which create their own env vars as well. Runit uses `$SVC_` as a prefix, for example. I think something like "$SDSVC_" might be less likely to clash. Anyway, if unit parameters are broken for this case, then I see env vars as the way to go.

**Comment by yuwata** [comment]
@aledomu If you are interested in, please test #10059. Thank you.

**Comment by aledomu** [comment]
Neat. Thanks!
