### ISSUE TITLE
Accept data size / hash offset in veritysetup generator

### ISSUE THREAD

**Issue by charles-dyfis-net** [systemd/systemd#9364]
Configuring dm-verity via the upstream `veritysetup` tool allows the filesystem data and supporting hash tree to be present inside the same partition or loopback file. Presently, this is not possible when using the systemd veritysetup generator, as the data-blocks and hash-offset arguments cannot be provided.

It would be helpful to have additional arguments to support this use case. If we were to stay close to upstream, this might be two separate arguments:

- `systemd.verity_root_data_size=...` - The size in bytes; error if specified and not a multiple of block size. (This is proposed as an equivalent to the veritysetup `--data-blocks` option, albeit using a value in bytes for consistency).
- `systemd.verity_root_hash_offset=...` - A byte offset to the beginning of the hash tree inside the location specified by `systemd.verity_root_hash` (proposed as an equivalent to the veritysetup `--hash-offset` option).

It would also be reasonable to accept a single size and use it for both purposes, if and when the same device is passed in both data and hash positions.

**Comment by charles-dyfis-net** [comment]
...some context: My actual intent here involves a loopback-mounted root filesystem from a single file (containing a squashfs filesystem, followed by verity metadata, followed by a signed footer). Thus, in and of itself, this ticket doesn't go so far as to address my full use case -- which requires mounting the parent filesystem, loopback-mounting the file from which the root filesystem and its metadata is to be read, and *then* invoking either `systemd-veritysetup` or `veritysetup` to mount the intended root before pivoting into it -- but it's a start.

**Comment by poettering** [comment]
btw, if you opt to put a GPT disk label on that image, you can just use `/usr/lib/systemd/systemd-dissect --mount` for mounting such an image. It will take a disk image, dissect its GPT metadata and then mount what's in it, optionally with Verity if there is. All this requires is that the GPT metadata is correctly set up, for example the GPT partition ids need to match the verity root hash and you need to specify the root hash with `--root-hash` on the command line.

In fact, systemd-nspawn supports exactly this too.

**Comment by charles-dyfis-net** [comment]
Interesting. That led me down a rabbit hole after which I'm considering abandoning my not-yet-publicly-documented local container format in favor of a GPT disk image as created by mkosi; the only major piece that appears to be missing is having a footer with an OpenPGP-signed copy of the verity root hash (or otherwise a means of validating it at mount time without needing to repackage the kernel in a new signed EFI binary with a different command line every time one ships a new root).

Would want to add some ability to tune mksquashfs options to favor casync-friendliness over size, but that's all very doable.

**Comment by poettering** [comment]
so "machinectl pull-raw" will already verify detached gpg signatures stored on the server for you. All that's necessary is to place the signature next to the raw image file with the suffix ".gpg"

**Comment by bluca** [comment]
> Interesting. That led me down a rabbit hole after which I'm considering abandoning my not-yet-publicly-documented local container format in favor of a GPT disk image as created by mkosi; the only major piece that appears to be missing is having a footer with an OpenPGP-signed copy of the verity root hash (or otherwise a means of validating it at mount time without needing to repackage the kernel in a new signed EFI binary with a different command line every time one ships a new root).
> 
> Would want to add some ability to tune mksquashfs options to favor casync-friendliness over size, and think about image reproducibility, but that's all very doable.

@charles-dyfis-net FYI in v246 there's now support for root hash signatures as enforced by the kernel dm-verity subsystem - if you have the public key in the trusted keyring, you can have a smime der format bare signature and it will be used automatically by nspawn. systemd-veritysetup supports it too, but I couldn't manage to make dracut work on Debian to try the verity generator in the initrd as well to verify that it works as expected.

**Comment by poettering** [comment]
This has been implemented a while back in 14de7ef914167ed08af6c0fb283e91f25e68b60f and 0bbf7a842a3feb4952415d82d2b469f5c5d91836

Closing.
