### ISSUE TITLE
systemd-udevd: ignore /dev/drbdX

### ISSUE THREAD

**Issue by rck** [systemd/systemd#9371]
**Is your feature request related to a problem? Please describe.**
I work for LINBIT who maintains DRBD ("RAID1 over network"), an in-upstream-kernel block device based replication technology. `systemd-udevd` opens every `/dev/drbdX` several times. On one hand there is no reason to do that, DRBD is always controlled by some other component in the architecture (e.g., pacemaker, virtualization,...). DRBD also has a feature called "auto promote". Usually DRBD devices are "Primary" on one node and "Secondary" on all others. Opening DRBD devices RO on multiple nodes is possible in newer DRBD versions, but still, you are not allowed to switch a node to "Primary" as long as there are RO openers. To keep this short, I stop here, but I can elaborate on more cases where udev really does not help DRBD devices if required. All in all there really is no need for udev to touch DRBD devices at all, in some scenarios it is even cumbersome. We are a "special unicorn" like "md" and "dm". 

**Describe the solution you'd like**
There are basically two solutions, this one would be good enough for us. Would you accept a patch like this? Of course I would collect Signed-offs from my fellow kernel devs:

```
diff --git a/src/udev/udevd.c b/src/udev/udevd.c
index da266bf03..9c9931a03 100644
--- a/src/udev/udevd.c
+++ b/src/udev/udevd.c
@@ -414,6 +414,7 @@ static void worker_spawn(Manager *manager, struct event *event) {
                         if (!streq_ptr(udev_device_get_action(dev), "remove") &&
                             streq_ptr("block", udev_device_get_subsystem(dev)) &&
                             !startswith(udev_device_get_sysname(dev), "dm-") &&
+                            !startswith(udev_device_get_sysname(dev), "drbd") &&
                             !startswith(udev_device_get_sysname(dev), "md")) {
                                 struct udev_device *d = dev;

```

**Describe alternatives you've considered**
An alternative would be to generalize such a blacklist, and let the admin control it via a config file. Given that there are a limited number of technologies that intentionally want to be ignored by `systemd-udevd` I'm not sure if that would be worth it.

**Comment by poettering** [comment]
please provide this a proper patch as a PR.

Also, given that the if check is pretty long now it would be appreciated to convert the device test predicate into a small function of its own:

```c
static bool shall_lock_device(struct udev_device *dev) {
        const char *sysname;

        if (!streq_ptr("block", udev_device_get_subsystem(dev)))
                return false;
   
        sysname = udev_device_get_sysname(dev);
        return !startswith(sysname, "dm-") && …
…
}

…

if (!streq_ptr(!streq_ptr(udev_device_get_action(dev), "remove")) &&
        shall_lock_device(dev) {
…

}
```
you get the idea.
