### ISSUE TITLE
Register a global OnFailure unit

### ISSUE THREAD

**Issue by AMDG2** [systemd/systemd#9373]
**Is your feature request related to a problem? Please describe.**
I would like to be able to send alerts through xmpp and/or email whenever a unit failed. So I will only have to write one unit and one program to handle alerts and notifications of a crashed long-running service (like apache, mariadb) and timer service (like letsencrypt renewal).

**Describe the solution you'd like**
I would like to register a global `OnFailure=` unit so every unit where it is not specified this global handler is triggered when a failure occurs.

This unit would be a one shot unit which will be instantiated for each other failed unit with the name of the failed unit.

If the global failure handler unit failed it is not called again.

**Describe alternatives you've considered**
I have considered some monitoring applications but they doesn't integrate very well with systemd. I also feel that my proposal is much simpler to deploy and easier on resources than having another service polling for failure using some systemd/journald magic to know about failures.

My solution doesn't replace a full monitoring system but allows to get near real-time alerts with little overhead.

**Comment by AMDG2** [comment]
I was digging a bit in systemd source code and discovered that we may register multiple `OnFailure=` dependencies for a specific unit it let me rethink about my proposal. So I would like to extend and give more detail to my proposal.

# Proposal

The administrator can set global `OnFailure` unit list like this:

```ini
# In /etc/systemd/system.conf file
[Manager]
DefaultOnFailure=global-on-failure.service
```

This will add the `global-on-failure.service` dependency to every unit. When a unit fails, the `OnFailure` dependencies are called. If one `OnFailure` unit depends on `network.target` (for example) and this dependency is not satisfied, it should not start. 

Then in a unit file, one can discard any default `OnFailure` dependencies like that:

```ini
[Unit]
DefaultOnFailure=false
OnFailure=my-own-on-failure-handler.service
```

# Implementation ideas

To implement this we can do it like that:

- [ ] Add `DefaultOnFailure` dependency list to `Manager` struct: `on_failure_dependencies`
- [ ] Add a method to `Manager` to start the on failure dependencies: `manager_start_on_failure(Unit * u)`
- [ ] In `unit_start_on_failure` call `manager_start_on_failure` if `OnFailureJobMode` is not `isolate`

I may be able to implement those 3 points, but I have no clue on how and where to load the `DefaultOnFailure` list from the config file to the `Manager` struct. I would do it the same way as it is done for the unit dependencies, but I wasn't able to find/understand the code which is responsible of this.

## How the DefaultOnFailure units will know which unit fails

In `manager_start_on_failure` the units are started with the following new environment variables:

- `FAILED_UNIT_NAME` like `mariadb.service`
- `FAILED_UNIT_PIDS` maybe?
- `FAILED_UNIT_EXIT_CODE` if possible?

This list of environment variables can be extended without breaking existing setup. If some values needs to be removed it can break existing setup.

## What to do on failure of an DefaultOnFailure unit

It should be removed from the manager dependency list.

I don't see any other issue which can block this implementation. Let me know what you think !

**Comment by poettering** [comment]
This is now possible, with #13743. closing.
