### ISSUE TITLE
Need a flag in .service to indicate if service restart is needed after resume from sleep/hibernate

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#9391]
**Is your feature request related to a problem? Please describe.**

Many services do not work after sleep/resume, for example, Avahi. There is a bug in Avahi to track this, but i don't really think this is an ad-hoc case. 

**Describe the solution you'd like**
If systemd could support restart service after resume, many services would be benefited from it. We need a flag in .service to indicate if service restart is needed after resume from sleep/hibernate

**Describe alternatives you've considered**

**Comment by keszybz** [comment]
I don't think the place for this is in systemd. It should be fairly easy to implement a template service which take a service name as the instance argument and does the restart for it.

**Comment by poettering** [comment]
Yes, systemd is not the place to work around issues in other software. We do provide proper APIs for getting notified when suspend/hibernation happens, so the software in question can all be fixed, it's a just a matter of hooking that. Moreover we provide various ways to hack around this (as @keszybz) suggested, hence I really don't think we should add anything new here.
