### ISSUE TITLE
systemd-networkd issue with LXC networking 

### ISSUE THREAD

**Issue by satishdotpatel** [systemd/systemd#9392]
**systemd version the issue has been seen with**

systemd 219

**Used distribution**
 
CentOS 7

**Expected behaviour you didn't see**
 
I am instaling openstack-ansible and part of installation it use LXC to deploy application, i have setup systemd-networkd  /etc/systemd/network configuration to setup all BOND+VLA+Bridge etc.. everything working great life is good, but problem is my lxc container can't ping outside world (public network).

Fun start here, if i un-install systemd-netword and move back to legacy style config ifcfg-* then everything works even container can ping outside world (Example 8.8.8.8)

It seem this is some kind of bug in systemd-networkd 

**Unexpected behaviour you saw**
 > … explained in post

**Steps to reproduce the problem**
I have mentioned this in details above

**Comment by yuwata** [comment]
Please see the note in the template.
> **NOTE:** Do not submit bug reports about anything but the two most recently released systemd versions upstream!

Please test with the recent version. If the problem still exists in the recent version, then please provide detailed settings, e.g., /etc/systemd/network/*.conf, and relevant logs of networkd. Thank you.

**Comment by satishdotpatel** [comment]
CentOS 7 doesn't have upgraded version available  :(
