### ISSUE TITLE
systemctl no longer allows unmask in combination with --runtime

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#9393]
**systemd version the issue has been seen with**

v239

**Used distribution**

Debian

Our CI system found a regression in systemd, which now triggers a failure in the policykit package:
https://ci.debian.net/data/autopkgtest/testing/amd64/p/policykit-1/496874/log.gz

policykit uses ```systemctl mask --runtime``` to create a temporary mask in /run during package upgrades. This temporary mask is removed after the package upgrade using
```systemctl unmask --runtime```. Seems systemctl no longer allows that and it fails now:

```
# systemctl mask --runtime polkit.service
Created symlink /run/systemd/system/polkit.service → /dev/null.
...
# systemctl unmask --runtime polkit.service
--runtime cannot be used with unmask
```
This is a regression over v238, where this worked as expected

**Comment by mbiebl** [comment]
/cc @keszybz  Afaics, this was introduced by 4910b35078ad24dcbc63f372b2fee087640201d0

I think it is useful to have control over which mask is removed. I.e. if I say ```systemctl unmask --runtime``` only the one in /run should be removed.
With the changes above, always all masks are removed. This is not what we want e.g. in the polkit package.
The point of runtime masking/unmasking is to disable dbus activation while the package is in an inconsistent state.
But if the admin has decided to mask the package (in /etc) and we would call ```systemctl unmask``` now, we would throw away those admin changes, which is bad.
I liked the symmetrical behaviour better as it was more predictable.

**Comment by mbiebl** [comment]
@keszybz any thoughts on this issue?

**Comment by utezduyar** [comment]
What is the final word on this? We are trying to bring in yocto master systemd and stumbled on this problem. By masking dbus activation services, we disable/enable bunch of services. We could change our code to drop --runtime from unmask commands but before doing that we would like to know the final decision.

**Comment by utezduyar** [comment]
This is announced @ https://github.com/systemd/systemd/blob/master/NEWS#L83

**Comment by mbiebl** [comment]
@keszybz your input on this would be appreciated.
If I now create a runtime mask via ```systemctl mask --runtime``` and want to remove that again later, without throwing away any admin changes that were done in /etc, what I'm supposed to do now? Use ```rm -f /run/...``` directly?

**Comment by mbiebl** [comment]
Needless to say, that I find the new behaviour very unintuitive. 
If ```systemctl disable/unmask``` is supposed to handle both /run and /etc, it would have been better imho if  a new switch like ```--all``` or so would have been used for that.
