### ISSUE TITLE
Mixing calls to service and direct calls to init.d script confuse systemd

### ISSUE THREAD

**Issue by pryland** [systemd/systemd#94]
On a fresh server with a fairly simple legacy init.d script, a setup process launches the service using "service name start" which works.  However, before doing anything else, if the service is restarted using "/etc/init.d/name restart" it doesn't work.  The log says:

> Jun 08 12:29:04 instance0 sudo[5158]: pdr : TTY=pts/0 ; PWD=/home/pdr ; USER=root ; COMMAND=/etc/init.d/instance0 restart
> Jun 08 12:29:04 instance0 sudo[5158]: pam_unix(sudo:session): session opened for user root by pdr(uid=0)
> Jun 08 12:29:05 instance0 instance0[5173]: Starting Magnolia instance0 instance: instance0 **(already running)**.

Subsequent calls to either then work as expected and this used to work before upgrading to Debian jessie.

After changing our scripts to consistently use the service script, everything now works.

**Comment by michich** [comment]
I am not sure how this is handled in Debian, but in Fedora init scripts start by sourcing /etc/rc.d/init.d/functions, which contains hacks to redirect the operations through systemctl.
In any case, this is a matter of downstream distro integration, not an upstream systemd bug.

**Comment by mbiebl** [comment]
you'll have to source /lib/lsb/init-functions for this to work properly

**Comment by pryland** [comment]
The script does indeed source /lib/lsb/init-functions already.

**Comment by poettering** [comment]
It's not sufficient to pull in the init-functions, you actually have to use the subroutines that are defined by it, too.

Most likely your init script simply does not make use of these functions. In that case, please ping the authors of that init script at your distribution, and ask them to make use of them instead.

**Comment by martinpitt** [comment]
For Debian it actually should be sufficient, and it is. `/lib/lsb/init-functions` sources `/lib/lsb/init-functions.d/40-systemd` which diverts direct calls to the init scripts to the corresponding `systemctl <command> <service>.service` if `<service>.service` exists.

**Comment by poettering** [comment]
Either way, it's something the distros/init script authors have to figure out, this is unlikely something we could or should fix in systemd.

**Comment by pryland** [comment]
It is a bespoke init script based largely on the tomcat one, which I can attach if anyone's interested.  However, I've found the problem.  I had the following in the script, just before sourcing /lib/lsb/init-functions:

```
if [ `id -u` -ne 0 ]; then
  echo "$0: Please run me as root" >&2
  exit 1
fi
```

I understand now that for init scripts this is unnecessary, non-standard and indeed the cause of this issue.  Returning another exit code would be better, but removing these lines I think is the correct thing to do.

I guess it was being run as non-root to get the status and getting exit code 1 which makes it think that it's not running.

**Comment by dparasam** [comment]
For me, here's the scenario (on Debian 8.2): 
- "/etc/init.d/abc status" shows as running and "service abc status" shows as active (running)
- run /etc/init.d/abc stop
- "/etc/init.d/abc status" shows as stopped however "service abc status" still shows as active (running), and so running "service abc start" doesn't work as it sees the service (falsely) as already running.

At this point, I have no abc.service native systemd unit file installed, so I suppose that the systemd compatibility layer is kicking in.

Could someone suggest what the best way to reflect the status of a service with systemd after having /etc/init.d/<service> to start or stop it?

In the above case, if I do "service abc stop", things go back to normal, although this particular command is a no-op as the service abc is already stopped.

Is there a better way?

**Comment by martinpitt** [comment]
@dparasam: That sounds like your `/etc/init.d/abc` does not source `/lib/lsb/init-functions` at the top.

**Comment by dparasam** [comment]
Yes, it doesn't.  Here's some of details about the scenario.
- mypackage-1.0.deb shipped only SysV-init script /etc/init.d/abc and uses "/etc/init.d/abc action" in all the packager scripts
- mypackage-1.1.deb ships both SysV-init script /etc/init.d/abc AND systemd unit file abc.service, and my-package-1.1.deb uses "service abc action" for invoking service actions in all its packager scripts
- when upgrading from mypackage-1.0.deb to mypackage-1.1, I get a problem when mypackage-1.0->prerm runs "/etc/init.d/abc stop" and then mypackage-1.1->preinst runs "service abc start" (this last command fails to start the service due to the inconsistency)

I'm trying to "fix" the upgrade path, so changing the old my-package-1.0.deb->prerm script doesn't work for me as it's already in the wild.

**Comment by martinpitt** [comment]
@dparasam: dpkg has "preinst" scripts which you can use to clean up after broken old package's prerm/postrm.

**Comment by dparasam** [comment]
Correct, that's the reference to mypackage-1.1->preinst above.  What exactly do you suggest I try to do in mypackage-1.1->preinst?  I can't repair old mypackage-1.0->prerm in there as the mypackage-1.0->prerm script runs "before" mypackage-1.1->preinst during an upgrade.  So instead my work-around/fix was to run "service abc stop" iff /etc/init.d/abc status says the service is already stopped - in mypackage-1.1->preinst.
