### ISSUE TITLE
systemd-boot: please don't assume embedded cmdline ends with newline

### ISSUE THREAD

**Issue by elboulangero** [systemd/systemd#9401]
**Is your feature request related to a problem? Please describe.**

I'm using systemd-boot to boot an UEFI combined image (ie. a bundle containing stub + os-release + cmdline + kernel + initrd).

I generated the kernel cmdline with something like `echo -n "console=ttyS0" > cmdline`, then I embed this file in an UEFI bundle with something like `objcopy --add-section ...`.

The issue is this particular line in `efi/boot.c`: https://github.com/systemd/systemd/blob/c9dce41d1b8f574e45f0dc2f73323213cae16460/src/boot/efi/boot.c#L1602

As you can see, this is the code that gets the embedded cmdline. It assumes that there is a termination character and removes it (`szs[1] - 1`).

This works if you created the cmdline file with `echo "whatever" > cmdline`, as echo will append a newline. However if you use `echo -n "whatever" > cmdline`, there's no termination characters (no newline, no `\0`, nothing), and in this case the code is wrong, as it removes the last character of the command-line.

**Describe the solution you'd like**

Would it be better to check the value of the last character, and remove it only if it's something like `\n`, `\r`, or `\0`? Would you accept such a patch?

**Comment by keszybz** [comment]
I wrote a simple patch for this. Can you verify that it works for you?

**Comment by elboulangero** [comment]
Thanks, patch tested and approved :+1:
