### ISSUE TITLE
SystemD networkd inside Debian 8  Unprivileged LXC container preventing packages from being installed

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9405]
**unprivileged** LXC **jessie** container with systemd 232

Opening this issue for reference so people will find the solution and not get burned for 3 days like i did

Creating an **unprivileged** LXC Debian **jessie**  container and trying to install `ssh` makes the container hang on generation of the ssh keys. Running `top` shows `systemd-networkd` at 100% CPU

The solution is to stop the `systemd-networkd` service that blocks the whole container from working properly.

**Comment by poettering** [comment]
Uh, as the issue submission form should make very clear: this is an upstream issue and bug tracker of systemd and only focussing on the two most recent versions of systemd. Which is 239 and 238 at this moment. For everything older, please ping your downstreams. Thank you for understanding.

**Comment by laerus** [comment]
Uh, it's okay, i just ignored the note, this is for search engines and people coming across the broken systemd 232 and systemd-networkd.
