### ISSUE TITLE
networkd - support for MTU on tun/tap devices

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9407]
**systemd version the issue has been seen with**
> 238 (in the LXC container)

**Used distribution**
 > host ubuntu 4.15.0-23 (being a VPS on a KVM hypervisor with `virtio` driver)
 > container archlinux
 > lxc 3.0.1

**Expected behaviour you didn't see**
 > MTU set for `tap`

**Unexpected behaviour you saw**
 > MTU configured for tap, ignoring

**Steps to reproduce the problem**
tap.netdev
```
[NetDev]
Name=tap0
Kind=tap
MTUBytes=9000
```
(re)start `networkd`

---
The integer for `MTUBytes=` does not matter, it always produces
> systemd-networkd[883]: tap0: MTU configured for tap, ignoring

And when being enslaved into a bridge
> systemd-networkd[1884]: tap0: Saved original MTU: 1500

and thereby dictating the bridge's MTU with the `bridge` being inherent of the smallest MTU integer of its enslaved devices.

**Comment by yuwata** [comment]
Currently, it seems setting `MTUBytes=` for tun or tap is not supported. https://github.com/systemd/systemd/blob/99d4345b30d8cfee899bc8fb9eca9db4da7dd00b/src/network/netdev/tuntap.c#L139-L149
Also, the man page systemd.netdev(5) says
> MTUBytes=
The maximum transmission unit in bytes to set for the device. The usual suffixes K, M, G, are supported and are understood to the base of 1024. This key is not currently supported for "tun" or "tap" devices.

**Comment by ssahani** [comment]
tuntap does not use the netlink interface to set MTU use.

tap0.network
```
[Match]
Name=tap0

[Link]
MTUBytes=2000
~~~

**Comment by yuwata** [comment]
Ah, I see. So, should we close this?

**Comment by n8v8R** [comment]
I am afraid it is unfortuntely not working in the setup described at the original post. Not sure whether that might be due the lxc unpriviliged container environment a/o a different version of `systemd` a/o a different distro.

The log, after the change in the config and a restart of `networkd`:

> tap0: Link 2 added
> tap0: Link state is up-to-date
> tap0: found matching network '/etc/systemd/network/ovpn_tap.network'
> tap0: Started LLDP.
> tap0: Enslaving by 'br0'
> br0: Enslaving link 'tap0'
> tap0: netdev has index 2
> tap0: **Saved original MTU: 1500**
> tap0: Flags change: +LOWER_UP
> tap0: Joined netdev
> tap0: Configured
> tap0: Flags change: -LOWER_UP
> tap0: Set link
> tap0: Flags change: -RUNNING
> tap0: Lost carrier
> tap0: State is configured, dropping config

**Comment by yuwata** [comment]
```
$ cat 25-bridge.netdev
[NetDev]
Name=br0
Kind=bridge

$ cat 25-bridge.network
[Match]
Name=br0

[Network]
DHCP=ipv4

$ cat 25-tap.netdev
[NetDev]
Name=tap0
Kind=tap

$ cat 25-tap.network
[Match]
Name=tap0

[Network]
Bridge=br0

[Link]
MTUBytes=9000

$ cat 25-eth.network 
[Match]
Name=en*

[Network]
Bridge=br0
```
With the above config. I get
```
$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP mode DEFAULT group default qlen 1000
    link/ether 78:84:3c:03:f9:5c brd ff:ff:ff:ff:ff:ff
3: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 4c:0f:6e:f0:f6:61 brd ff:ff:ff:ff:ff:ff
6: tap0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9000 qdisc fq_codel master br0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 76:f8:ad:f2:74:e0 brd ff:ff:ff:ff:ff:ff
7: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2e:7a:01:8f:b2:32 brd ff:ff:ff:ff:ff:ff
```
It seems MTU is correctly set.

**Comment by yuwata** [comment]
I've tested that on Fedora 28 with recent git snapshot.

**Comment by n8v8R** [comment]
So different distro, perhaps different kernel and different systemd version. 

I am not sure why closing it when it is not working?

**Comment by keszybz** [comment]
@n8v8R only latest systemd version is supported, backporting fixes is left to distributions. And the kernel and distro versions shouldn't matter here. That said, if you can reproduce the issue with systemd-239, we should reopen and investigate.

**Comment by n8v8R** [comment]
Got it sorted now after realzing that `systemctl restart systemd-networkd` been producing

> systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted

which is owed to the environment/nature of an unpriviliged lxc container...
