### ISSUE TITLE
networkd - tap device lost carrier

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9408]
**systemd version the issue has been seen with**
> 238 (in the LXC container)

**Used distribution**
 > host ubuntu 4.15.0-23 (being a VPS on a KVM hypervisor with `virtio` driver)
 > container archlinux
 > lxc 3.0.1

**Expected behaviour you didn't see**
 > tap dev to be online

**Unexpected behaviour you saw**
 > Flags change: -LOWER_UP
> Flags change: -RUNNING
> Lost carrier

**Steps to reproduce the problem**
***tap.netdev***
```
[NetDev]
Name=tap0
Kind=tap

[Tap]
MultiQueue=yes
VNetHeader=yes
```
***tap.network***
```
[Match]
Name=tap0

[Network]
Bridge=br0
```
(re)start `networkd`

---
Trying as I might the `tap` dev goes offline and there is nothing apparent in the logs or otherwise indicating the cause

> systemd-networkd[3529]: tap0: loaded tap
> systemd-networkd[3529]: tap0: Created
> systemd-networkd[3529]: tap0: Flags change: +UP +RUNNING +MULTICAST +BROADCAST
> systemd-networkd[3529]: tap0: Link 3 added
> systemd-networkd[3529]: tap0: Link state is up-to-date
> systemd-networkd[3529]: tap0: found matching network '/etc/systemd/network/ovpn_tap.network'
> systemd-networkd[3529]: tap0: Started LLDP.
> systemd-networkd[3529]: tap0: Enslaving by 'br0'
> systemd-networkd[3529]: br0: Will enslave 'tap0', when ready
> systemd-networkd[3529]: tap0: netdev has index 3
> systemd-networkd[3529]: tap0: Saved original MTU: 1500
> systemd-networkd[3529]: tap0: Link does not request DHCPv6 prefix delegation
> systemd-networkd[3529]: br0: Enslaving link 'tap0'
> systemd-networkd[3529]: tap0: Flags change: +LOWER_UP
> systemd-networkd[3529]: tap0: Joined netdev
> systemd-networkd[3529]: tap0: Configured
> systemd-networkd[3529]: tap0: **Flags change: -LOWER_UP**
> systemd-networkd[3529]: tap0: Set link
> systemd-networkd[3529]: tap0: **Flags change: -RUNNING**
> systemd-networkd[3529]: tap0: **Lost carrier**
> systemd-networkd[3529]: tap0: State is configured, dropping config

---
***`networkctl`***

> IDX LINK             TYPE               OPERATIONAL SETUP
>  1 lo               loopback           carrier     unmanaged
>  2 br0              bridge             routable    configured
>  3 tap0             ether              no-carrier  configured
> 96 eth0             ether              carrier     configured
> 
> 4 links listed.

***`networkctl status tap0`***

> ● 3: tap0
>        Link File: n/a
>     Network File: /etc/systemd/network/ovpn_tap.network
>             Type: ether
>            State: no-carrier (configured)
>       HW Address: aa:76:59:49:5f:97

***`ip -d l ls tap0`***

> 3: tap0: <**NO-CARRIER**,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br0 **state DOWN** mode DEFAULT group default qlen 1000
>     link/ether aa:76:59:49:5f:97 brd ff:ff:ff:ff:ff:ff promiscuity 1
>     tun
>     bridge_slave **state disabled** priority 32 cost 100 hairpin off guard off root_block off fastleave off learning on flood on port_id 0x8002 port_no 0x2 designated_port 32770 designated_cost 0 designated_bridge 8000.6e:d6:4c:32:b2:be designated_root 8000.6e:d6:4c:32:b2:be hold_timer    0.00 message_age_timer    0.00 forward_delay_timer    0.00 topology_change_ack 0 config_pending 0 proxy_arp off proxy_arp_wifi off mcast_router 1 mcast_fast_leave off mcast_flood on neigh_suppress off group_fwd_mask 0x0 group_fwd_mask_str 0x0 vlan_tunnel off addrgenmode eui64 numtxqueues 256 numrxqueues 256 gso_max_size 65536 gso_max_segs 65535

**Comment by n8v8R** [comment]
After a reboot of the lxc container it appears to be in some kind of configuring limbo

***`networkctl status tap0`***

> ● 2: tap0
>        Link File: n/a
>     Network File: /etc/systemd/network/ovpn_tap.network
>             Type: ether
>            State: no-carrier **(configuring)**
>       HW Address: 66:4b:42:d5:ec:04

---
> systemd-networkd[49]: tap0: loaded tap
> systemd-networkd[49]: tap0: Created
> systemd-networkd[49]: tap0: Flags change: +MULTICAST +BROADCAST
> systemd-networkd[49]: tap0: Link 2 added
> systemd-networkd[49]: tap0: Link state is up-to-date
> systemd-networkd[49]: tap0: found matching network '/etc/systemd/network/ovpn_tap>
> systemd-networkd[49]: tap0: Enslaving by 'br0'
> systemd-networkd[49]: br0: Enslaving link 'tap0'
> systemd-networkd[49]: tap0: netdev has index 2
> systemd-networkd[49]: tap0: Saved original MTU: 1500
> systemd-networkd[49]: tap0: Joined netdev
> systemd-networkd[49]: tap0: Bringing link up
> systemd-networkd[49]: tap0: IPv6 successfully disabled
> systemd-networkd[49]: tap0: Flags change: +UP
> systemd-networkd[49]: tap0: Started LLDP.
> systemd-networkd[49]: tap0: Set link

**Comment by skrilladeville** [comment]
Thank you
