### ISSUE TITLE
Allow mlock by default under systemd-nspawn

### ISSUE THREAD

**Issue by tmds** [systemd/systemd#9414]
**Is your feature request related to a problem? Please describe.**
.NET Core does not run under systemd-nspawn because it uses mlock.
Similar issue for rubygem-mongo: https://github.com/rpm-software-management/mock/issues/186

**Describe the solution you'd like**
Allow mlock and related under systemd-nspawn by default.

**Describe alternatives you've considered**
?Make .NET Core work without mlock, if feasible.

CC @omajid @msekletar @tixxdz

**Comment by mikhailnov** [comment]
mongodb also fails without mlock() ("Failed to mlock: Cannot allocate locked memory"), but I agree that it is not problem of systemd-nspawn

**Comment by mikhailnov** [comment]
Not `@mlock`, but `@memlock`
