### ISSUE TITLE
Allow Instantiated Units to be Enabled Via Presets

### ISSUE THREAD

**Issue by Bubblemelon** [systemd/systemd#9421]
## Feature Request

We would like systemd presets to enable instantiated services.

### Problem Overview:

In reference to this thread: [Instantiaed services in presets](https://lists.freedesktop.org/archives/systemd-devel/2015-August/033837.html)

1. Service templates can only instantiate one service unit and,

2. this unit needs to be enabled manually using systemctl (not through the .presets file).

This is the issue is related to:  
[Ignition Bug #2241](https://github.com/coreos/bugs/issues/2241)

### Suggested Solution: 

These ideas were from the above thread, and I want to note that this thread was dated back in 2015.

1. Have `DefaultInstance=` accept a list of instances, and not just one. This is indirectly related to presets but this is nice to have.

2. To enable mulitple instances of a service, the .preset file should be able to take the format of: 
    
    `enable foo@.service bar0 bar1 bar2`

There was a suggested work-around using sysmlinks via the `Alias=` directive:  

```
[Install]
Alias=multi-user.target.wants/bar0@foo.service
multi-user.target.wants/bar1@foo.service ...
```

### Question:

Is there any particular reason why the presets file did not take the suggested format initially and would consider the alias work-around instead?

**Comment by Bubblemelon** [comment]
Please reopen :smile:

**Comment by Bubblemelon** [comment]
cc: @ajeddeloh 

What do you think ?

**Comment by cgwalters** [comment]
It feels like this one depends on the outcome of the discussion in https://github.com/systemd/systemd/issues/9476 - if we end up doing something that doesn't look like preset files, it'd make sense to have it support templated units.

**Comment by ajeddeloh** [comment]
@cgwalters I think the two are actually independent. This is something that could be useful on it's own. While instantiated units were originally for things that varied per machine (e.g. network interface names) which don't make sense to have presets entries for, there's no reason they couldn't be used for other use cases.

One example might be having a unit for something like [coreos-metadata](https://github.com/coreos/coreos-metadata) which grabs metadata for from various cloud providers. It could have a preset entry that instantiates it for each cloud, allowing the same unit to be used for each cloud image and only having the presetfile change. i.e. you'd have `coreos-metadata@aws` or `coreos-metadata@gce` enabled based on whatever cloud you're running on.

Note: on Container Linux we read from a kernel command line argument to determine what platform we're on, this was just an example of how it could be done differently.

If we do end up doing something else for #9476, it makes sense to support instantiated units there as well, but there's still value in doing it here.

**Comment by keszybz** [comment]
I think this is quite reasonable. The discussion stalled back in 2015, but not because of any disagreement, but because nobody picked up the work.

**Comment by peterbaouoft** [comment]
@keszybz, thank you for your previous response. Cheryl(@Bubblemelon) and I collaboratively wrote the following: (same as the email sent)

As a first time contributor, we would really appreciate your help in clarifying some implementation details.

This is our proposed solution so far, in the following steps:

1:  In `unit_file_preset_all`, before calling `preset_prepare_one`, check if the service file is a valid service and a templated unit.

If it is a templated unit e.g. foo@.service,  then check from the preset database(using `query_presets`) to see if a rule like “enable foo@.service bar0 bar1 bar2” exist.

If it does, 3 instances of foo@bar0.service, foo@bar1.service and foo@bar2.service will be returned as an array.

2: Use the returned array to loop through all of the returned instance names. (i.e: foo@bar0.service etc).  At the end, each name will be fed into a function `preset_prepare_one`.

We are open to your thoughts and suggestions on the above. Thank you very much for your time. 


This is our implementation in pseudo code:

```
char **preset_array; /* store number of units name e.g: xx@a.service xx@b.service */

/* The function below tests a: if the unit is valid

* b: if it is valid and not a templated unit, return current unit name in array

* c: if it is a templated unit, and multiple instances of the unit was specified in the preset file,

* return all instance names in an array e.g: foo@bar0.service foo@bar1.service etc */

r  = find_matching_presets(scope, de->d_name, &plus, &minus, presets, NULL, 0, &preset_array)

STRV_FOREACH(iter, preset_array) {

        /* we don't pass changes[] in, because we want to handle errors on our own */

        r = preset_prepare_one(scope, &plus, &minus, &paths, *iter, presets, NULL, 0);

        if (r == -ERFKILL)

                r = unit_file_changes_add(changes, n_changes,

                                          UNIT_FILE_IS_MASKED, *iter, NULL);

        else if (r == -ENOLINK)

                r = unit_file_changes_add(changes, n_changes,

                                         UNIT_FILE_IS_DANGLING, *iter, NULL);

        else if (r == -EADDRNOTAVAIL) /* Ignore generated/transient units when applying preset */

                continue;

        if (r < 0)

                return r;

        }

}
```

**Comment by keszybz** [comment]
First of all, `unit_file_preset_all` is used by `systemctl preset-all`. You need to hook into the call stack lower, so that paths from `systemctl preset` is affected too.

Second, `preset_prepare_one` calls `query_presets` internally. It seems wrong to query the preset database twice, apart from being inefficient, it can lead to complicated semantics. Instead, I think `query_presets` should optionally returns a `strv` of instance names to enable. Then you have just a single question and single answer.

**Comment by Bubblemelon** [comment]
Closing this issue since [PR #9901](https://github.com/systemd/systemd/pull/9901) has been merged :smile: Thanks @peterbaouoft and @keszybz ! :tada:
