### ISSUE TITLE
bootctl command line check for `systemd-boot install` state is missing

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#9428]
**systemd version the issue has been seen with**
> master

**Used distribution**
 > Ubuntu 18.10 (devel)

**Expected behaviour you didn't see**
 > $ bootctl is-installed

should be available as a commend

**Unexpected behaviour you saw**
 > $ bootctl status

is the only subcommand available, but is not machine parsable

**Steps to reproduce the problem**

I'm thinking of integrating bootctl update & kernel-install with the default kernel packages on Ubuntu, however to do so safely, I do need to check whether or not, bootctl was installed & enabled. That way maintainer scripts could check if bootctl is installed in ESP and update loader entries / update systemd-boot in ESP, only if it was already installed.

I'm thinking that `bootctl is-installed` should be available as a command, but not sure about the semantics of it. Something like `[ -d $(bootctl -p)/EFI/systemd ]` ? or maybe something more sophisticated is needed?

I'm looking something akin to the semantics of `is-system-running`, `is-enabled`. Something to call from scripts, ideally without any stdout/stderr, with return codes as indicators whether or not to call e.g. "bootctl update".

**Comment by poettering** [comment]
> I'm thinking of integrating bootctl update & kernel-install with the default kernel packages on Ubuntu, however to do so safely, I do need to check whether or not, bootctl was installed & enabled. That way maintainer scripts could check if bootctl is installed in ESP and update loader entries / update systemd-boot in ESP, only if it was already installed.

That would be excellent to support in Ubuntu!

And yes, we can totally add "is-installed". That said, the boot loader spec is somewhat independent of systemd-boot and hence it would probably make sense to condition the install scripts differently. For example, testing if a "loader" dir exists in the ESP sounds like a simple test that could work too, and it leaves the door open to other boot loaders implementing the spec (fedora patched through a number of them to support the spec).
