### ISSUE TITLE
Automatic code review by LGTM

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9430]
[LGTM](https://lgtm.com/) analyzes every commit pushed to master, but it's also possible to use LGTM as [a continuous integration tool to analyze code in pull requests](https://lgtm.com/help/lgtm/using-lgtm-analysis-continuous-integration). @poettering @keszybz is there any chance you could turn it on at https://lgtm.com/projects/g/systemd/systemd/ci/? I'd do it myself, but I don't have admin permissions.

**Comment by poettering** [comment]
I made you an admin now on github. Can you check if that works?

**Comment by evverx** [comment]
Thank you. I've just turned the hook on. I'm going to create a test PR to see if it works all right.

**Comment by evverx** [comment]
Judging by https://github.com/systemd/systemd/pull/9434, everything seems to be fine. I haven't turned the automatic comments off, so apparently I'll bother people introducing new alerts with messages like https://github.com/systemd/systemd/pull/9434#issuecomment-400390782. We could always switch them off it they are too annoying.

**Comment by filbranden** [comment]
Looks good.

A suggestion would be to perhaps register a separate account such as `systemd-bot` etc. and then sign up for LGTM notifications with it, so we can easily tell they're coming from a bot...

But the way this now works is probably fine, it's easy to tell that's the case...

**Comment by evverx** [comment]
There is https://github.com/orgs/systemd/people/systemd-build-scans, which probably could be used as a general-purpose bot. On the other hand, my comments doesn't usually look much different from those ones, so it's totally fine by me :-)

**Comment by poettering** [comment]
Excellent! Thanks a million for setting this up. Much appreciated!

**Comment by evverx** [comment]
No problem. I have to say that the team behind @lgtmhq have made the integration so smooth that all I needed to do was to press a couple of buttons in the right order, so kudos to them for making it possible!

**Comment by samlanning** [comment]
@evverx Thanks for the kind words! Let us know if you have any suggestions at any point.

**Comment by poettering** [comment]
@samlanning are you working on lgtm? We'd very much appreciate if lgtm would start to grok the `%1$` expansion that POSIX printf() defines. it's currently the number issue lgtm falsely detects in our tree. If lgtm would understand the true meaning of that this would be more than excellent. 

But besides that, great work on lgtm, we have now fixed a number of issues discovered by it!

**Comment by evverx** [comment]
@poettering the issue has already been reported in https://github.com/lgtmhq/lgtm-queries/issues/44 and is likely to be fixed soon.

**Comment by samlanning** [comment]
@poettering That is correct. And as @evverx says, it should be fixed soon. The fix is in our master and should hopefully be deployed to lgtm.com this week (should all tests pass).

**Comment by poettering** [comment]
@samlanning @evverx excellent! thanks!

**Comment by evverx** [comment]
@samlanning LGTM seems to have started to show the alerts that were active on Feb 20, 2018 on [the overview page](https://lgtm.com/projects/g/systemd/systemd/):
![screen shot 2018-07-05 at 07 59 10](https://user-images.githubusercontent.com/10195800/42303441-f6e7268a-8029-11e8-9df4-0c6e6a3f7e67.png)

Could it be that something is out of sync with the master branch?

**Comment by aibaars** [comment]
@evverx LGTM seems to have gotten confused by a github-webhook request originating from https://github.com/systemd/systemd/pull/8227 and reset the view to 20 Feb. We're investigating what happened. Apologies for the inconvenience.

**Comment by evverx** [comment]
@aibaars it's all right. Thank you for looking into this.

**Comment by evverx** [comment]
I've just noticed that the active alerts have got back to normal. In addition, the "printf" false positives have disappeared and the grade is A+ now. [![Language Grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/systemd/systemd.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/systemd/systemd/context:cpp) Thank you!

**Comment by evverx** [comment]
@aibaars @samlanning  LGTM seems to have reverted to Apr 30, 2018:
![screen shot 2018-07-06 at 18 49 53](https://user-images.githubusercontent.com/10195800/42388300-be30bfde-814d-11e8-9d36-57667182dcd0.png)

Judging by the date, it was most likely caused by https://github.com/systemd/systemd/pull/8862. Let me know if there is anything I can do to help debug it further.

**Comment by evverx** [comment]
@pabigot as far as I know, GitHub stores all the requests and responses sent and received by the hook, which I think generally should be enough to restore the order of the events. Plus LGTM has already been fixed, so I'd say that It'd be totally fine to push the update. Thank you.

**Comment by aibaars** [comment]
@pabigot @evverx Thanks for reporting this and helping us diagnose the problem. LGTM should behave a bit better now.

LGTM got confused when it received webhook requests from pull-requests that were created before systemd turned on code review integration. Whenever you updated one of the older pullrequests (for example a label or reviewer change) LGTM would receive a webhook and go "hey I'v not seen this PR before, therefore it must be new, and wrongly update the alerts".
