### ISSUE TITLE
LogLevel vs log_level vs --log-level

### ISSUE THREAD

**Issue by harridu** [systemd/systemd#9439]
systemd has several naming schemes for the same configuration option, e.g.

	LogLevel	(/etc/systemd/system.conf)
	--log-level	(systemd command line)
	log_level	(kernel command line)

There are *many* more options like this. IMHO thats bad practice. It is confusing, error-prone and has no advantage.

It would be a huge improvement if systemd defines a common naming scheme for options, and sticks with it.

**Comment by yuwata** [comment]
It is too late to change the naming scheme... Sorry.

**Comment by filbranden** [comment]
Also note that there's consistent within each configuration file.

Options in system.conf and other config files are all CamelCase.

Command-lines for userland commands are always --words-separated-by-dashes which is the common convention there.

Kernel command-lines typically use words_with_underscores, so we're following that convention there.

The three examples above are simply a translation of the same concept ("log level") into the different naming conventions (two of which were out of our control to begin with.)

**Comment by poettering** [comment]
Yes @filbranden is right, we didn't come up with these naming schemes, we just use what's commonly used already in the specific place, and translate our concepts to the scheme appropriate. If you want to fix all this I figure you have to rework much more than systemd...

Also, I find this somewhat useful actually, as it suggests the context of some option. i.e. by saying "--log-level" I already know it's probably a command line switch you are talking of, and so on.
