### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [systemd/systemd#944]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html) in functions like the following.
- [journal_file_close](https://github.com/systemd/systemd/blob/dade37d403f1b8c1d7bb2efbe2361f2a3e999613/src/journal/journal-file.c#L172)
- [message_free](https://github.com/systemd/systemd/blob/37286ade90619bbce3a445dd3dcabe5d8ba21342/src/libsystemd/sd-bus/bus-message.c#L123)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/) to find more update candidates?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by zonque** [comment]
Please open a PR that fixes the issues you detected. Thanks.
