### ISSUE TITLE
RFE: --force option for `machinectl copy-to/copy-from` 

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#9441]
**Describe the solution you'd like**
It would be nice to have the option to overwrite a file with the copy-to/copy-from feature. Currently we are not able to overwrite a file in a container:
```
 % sudo machinectl copy-to work .zshrc /home/chris/.zshrc                                                              
Failed to copy: File exists
```

What I suggest is something like this:
```
 % sudo machinectl copy-to work .zshrc /home/chris/.zshrc --force    
```

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/24080
