### ISSUE TITLE
systemd-firstboot does not support all the features of the *ctl tools

### ISSUE THREAD

**Issue by DamienRobert** [systemd/systemd#945]
This is a feature request:
the *ctl tools like timedatectl, localectl and hostnamectl are very usefull but they need a running systemd, so they can't be used when preparing a bootable image. Systemd-firstboot is supposed to solve that, but it does not have all the features of the *ctl. For examples:
- setting the pretty hostname (from hostnamectl)
- setting the keymap and x11-keymap (from localectl)

Currently to run these tools to prepare a boot image for these extra settings I need to do a full `systemd-nspawn -b` running a custom service calling my settings. Hence this feature request. It would be nice if either systemd-firstboot would learn these features (but they can arguably seen as too specialised for this tool), or (better IMHO) if the *ctl tools could work (on the file level) even if they can't connect to systemd's bus.

**Comment by poettering** [comment]
Note that #7035 implements the keymap part now.

**Comment by poettering** [comment]
I guess we can close that as firstboot can set the hostname and keymap these days.
