### ISSUE TITLE
/etc/resolv.conf should symlink to /run/systemd/resolve/resolv.conf when the stub DNS server is disabled

### ISSUE THREAD

**Issue by tomelliff** [systemd/systemd#9450]
When using the systemd-resolved stub server with private DNS servers upstream and running Docker containers on the default Docker bridge network Docker is unable to use the stub DNS server (it won't listen to requests from the 172.17.0.0/16 range that Docker uses) and so falls back to using the 8.8.8.8 Google DNS server.

I've tried disabling the stub resolver using `DNSStubListener=no` in `/etc/systemd/resolved.conf` but `/etc/resolv.conf` still symlinks to the stub server config (`../run/systemd/resolve/stub-resolv.conf`) even though it's no longer running.

I _can_ just change the symlink but it's surprising to not have resolved realise it shouldn't be pointing DNS requests at the stub server when it is disabled.

**Describe the solution you'd like**
When disabling the stub DNS server (implemented in https://github.com/systemd/systemd/commit/1ae43295751fc235e7f93719a635a5b06f3ac09b) it should also change the symlinked resolv.conf to point to the non stub resolver so things don't try to use the non-running stub server at 127.0.0.53.

**Describe alternatives you've considered**
There are workarounds to force Docker to use different DNS servers directly instead of trying and failing to use what's in `/etc/resolv.conf` (`docker run --dns [PRIVATE DNS SERVER IP HERE] ...` or set the default DNS in `/etc/docker/daemon.json`) but this probably shouldn't need to be done and the latter option causes me issues when I bake the config into images before running them in places that have different DNS servers (different VPCs in AWS that have different VPC local Route53 endpoints).

**Comment by tomelliff** [comment]
I was considering filing this as a bug but no one else seems to be being bitten by this and I don't know how other people are using the `DNSStubListener=no` override.

@dm0- do you know how people are handling things when running other DNS services locally? Do the other services hijack `/etc/resolv.conf`? I'd have to use dnsmasq (or equivalent) listening on 0.0.0.0/0 or at least 172.17.0.0/16 as well or just fall back to directly using the remote DNS server provided by DHCP.

**Comment by floppym** [comment]
Maintaining `/etc/resolv.conf` is generally the sysadmin's job. The only systemd component that actually updates it is the tmpfiles snippet in `/usr/lib/tmpfiles.d/etc.conf`, it it only creates a symlink if /etc/resolv.conf does not exist.

**Comment by dm0-** [comment]
@tomelliff I don't have any data on how users configure their local DNS servers, but I'd imagine they are pointing the symlink at `/run/systemd/resolve/resolv.conf` if they're using DHCP or .network configuration, otherwise just writing a regular file at `/etc/resolv.conf`.  In the case of CoreOS where the stub listener is disabled by default for clusters to run their own DNS services, the tmpfiles configuration was modified to point at the legacy `resolv.conf` from resolved by default.

**Comment by tomelliff** [comment]
Okay thanks all, looks like I was wrong about my assumption that systemd was responsible for setting the symlink to the `stub-resolv.conf` although it does surprise me slightly. I can't find anything in /usr/lib that references the symlink so I guess it must originally be set by Canonical in the AMI's I'm basing from.

**Comment by fermulator** [comment]
I suppose this is related to #10298
