### ISSUE TITLE
Failed to reinstall systemd after accidental deletion of systemd-generator.xxxxxx files in /tmp

### ISSUE THREAD

**Issue by minizbie** [systemd/systemd#9454]
**systemd version the issue has been seen with**
204-5ubuntu20.28

**Used distribution**
Ubuntu 14.04.5 LTS"

**Expected behaviour you didn't see**
> 
**Unexpected behaviour you saw**
> systemd
Failed to set up the root directory for shared mount propagation: Operation not permitted
Failed to create root cgroup hierarchy: Permission denied
Failed to allocate manager object: Permission denied

> systemctl status
Failed to issue method call: Access denied

**Steps to reproduce the problem**
sudo rm -rf systemd-generator.*

Sorry I am linux newbie, and whilst i was cleaning up i foolishly removed a directory called systemd-generator.lAIFDc in /tmp. and after that systemd stopped working.

I tried apt-get remove systemd and apt-get autoremove systemd and apt-get install systemd again. Both the uninstall and install reported no errors. systemd is now  broken and I don't know how to fix it.

Please help!

**Comment by yuwata** [comment]
Sorry, this is not a support forum, but an issue and rfe tracker.

I recommend to try to boot with rescue mode, or cleanly re-install the OS.
