### ISSUE TITLE
Fedora CI seems to be broken

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9456]
I'm not sure what has happened to Fedora CI, but it appears to have been broken for over 10 days.

Unfortunately, links in PRs pointing to 404 pages like http://38.145.33.116/systemd-pr/a5/ce/a5ce193e9b359ad19d9d3b270d85370c02c2eefc_dev/rpmbuild.log aren't very helpful in debugging, so it's hard to figure out what's going on.

@keszybz is there any chance you could take a look?

**Comment by lucab** [comment]
I'm not sure whether related or not, but trying to [update](https://github.com/coreos/coreos-overlay/pull/3310#issuecomment-401500412) ContainerLinux to systemd-v239 our CI is also encountering random DBus-related failures:
 * one when creating a user session after SSH login: `user@500.service: Failed with result 'protocol'`
 * another one when [ignition](https://github.com/coreos/ignition/blob/v0.26.0/internal/systemd/systemd.go#L25) is trying to reach over DBus: `dbus: authentication protocol error`

**Comment by keszybz** [comment]
I bugged Frederic Lepied about it (he's really the person who set this up), and he says that
> from time to time, copr is failing. I can't really do anything about it...

I can't do anything about this quickly. We can disable it again, but I'd prefer to keep the red "x" to bug people to figure out what is going on there. I'm not sure how often it is just copr failing, and how often it is something that we could actually fix.

**Comment by evverx** [comment]
@keszybz thank you. Fedora CI appears to have been fixed.

@lucab Fedora CI just builds `systemd` and then runs the unit tests, so it seems very unlikely that it can even trigger the issues you mentioned earlier. Could you open a new issue so that it would be possible to track them properly?

**Comment by evverx** [comment]
@lucab it's totally unrelated, but I've just noticed that we have a hook that tries to send data to http://rkt-ci-jenkins.core-os.net/jenkins/github-webhook/ with no success. I was wondering if you know what that could be. Do you think it would be safe to turn it off?

**Comment by lucab** [comment]
@evverx yes, it can be safely turned off, that jenkins does not exist anymore.

**Comment by keszybz** [comment]
I deleted that webook now.
