### ISSUE TITLE
Systemctl enable failing with template unit file

### ISSUE THREAD

**Issue by tranceitionalMynd** [systemd/systemd#946]
I have a VMware vm on which systemctl enable is failing every time with template unit files. The error message is "Failed to issue method call: No such file or directory". I also have VirtualBox vms which have similar software (they are on kernel 3.10.0-229.11.1.el7.x86_64), which do not have this problem.  Please let me know if you need any more information.

Kernel: 3.10.0-229.el7.x86_64
OS: CentOS Linux release 7.1.1503 (Core)
Platform: VMware ESXi Version 5.1.0
Hardware: Dell PowerEdge R710

systemctl --version
systemd 208
+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ

find /etc/systemd/system/ -name _asdf_
/etc/systemd/system/asdf@.service

find /usr/lib/systemd/system/ -name _asdf_ | wc
      0       0       0

cat /etc/systemd/system/asdf@.service
[Service]
ExecStart=/bin/sh
[Install]
WantedBy=multi-user.target

sestatus; whoami; systemctl enable asdf@jklm; echo $?
SELinux status:                 disabled
root
Failed to issue method call: No such file or directory
1

journalctl -xn | tail -n 1 | awk -F: '{ print $4$5 }'
Failed to get unit file state for asdf@jklm.service No such file or directory

**Comment by poettering** [comment]
Is that file a symlink maybe?

**Comment by poettering** [comment]
Actually, 208 is _really_ old, please report this issue to your downstream distro, we do not track such old bugs upstream, but only the most recent versions. Sorry!
