### ISSUE TITLE
Gamepads: identification of player number

### ISSUE THREAD

**Issue by hzulla** [systemd/systemd#9464]
Hello,

please let me know if the following feature is desired for udev/systemd.

I helped implement the following functionality as an udev rule [for the Debian package 'joystick'](https://salsa.debian.org/debian/joystick/merge_requests/1) and [was told on the linux-input mailing list](https://marc.info/?l=linux-input&m=152908132602075&w=2) that systemd may be the better place. 

![gamepad-leds](https://user-images.githubusercontent.com/1705654/42038138-7faf9c8a-7aea-11e8-9ab9-5c975844dc43.jpg)

Gamepad users need to know which gamepad is used for which player. Many gamepads come with LEDs that will identify the gamepad number to the user.

* The [PS3 gamepad](https://en.wikipedia.org/wiki/DualShock#DualShock_3) and the [Nintendo Wiimote](https://en.wikipedia.org/wiki/Wii_Remote) feature four individual LEDs.
* The [PS4 gamepad](https://en.wikipedia.org/wiki/DualShock#DualShock_4) shows the device number using different colors.
* The [XBox gamepad](https://en.wikipedia.org/wiki/Xbox_360_controller) sports a ring with four LEDs.

The Linux drivers for XBox and PS gamepads both use their own internal device enumeration. Thus, if you connect two XBox controllers, they will identify as gamepad 1 and 2 to the user, but if you then connect two PS3 controllers, they will again identify as gamepad 1 and 2 because it's a different driver handling them, despite being the third and fourth joystick device of the system.

So it seems to be better to control these LEDs from a udev rule.

If you think it is and want to see this implemented, please guide me briefly on how to properly do this. The Debian package mentioned above uses [a shell script](https://salsa.debian.org/hanno-guest/joystick/blob/feature/new-js-set-enum-leds/utils/js-set-enum-leds) and calls it [based on the device id or driver](https://salsa.debian.org/hanno-guest/joystick/blob/feature/new-js-set-enum-leds/debian/joystick.udev), but I assume that this isn't the proper way to go for inclusion in systemd/udev.

Thanks.

**Comment by poettering** [comment]
hmm, so this is about assigning player ids as soon as a gamepad is plugged in? and that's supposed to be stable even, i.e. everytime we boot up the same gampad shell get the same number? and the id range is small, i.e. just 0…4?

How is the gamepad id passed to the gamepad? through some input LED api?

I'd probably write a tiny singleton service, that is pulled in through udev rules (i.e. rules that match the gamepad, and use a SYSTEMD_WANTS property to pull it in). This service would assign numbers in a first-come-first-serve basis, and if stability is required stores that to /var/lib somewhere (could be as simple as maintaining one symlink /var/lib/gamepadd/<id> which would point to the udev device path `ID_PATH` for the device). It would stick around as long as there are gamepads around, and exit as soon as all are gone. Everytime a gamepad shows up it searches through those symlinks, and if it finds a matching one writes the ID into it. If no matching symlink is around it would find the lowest ID which currently has no device plugged and use that replacing the symlink with its own. 

That said, I don't think this would be the right fit to place into systemd itself, but maybe there's some suitable package for this somewhere. Maybe @whot, @hadess, @jwrdegoede have a suggestion?

**Comment by hadess** [comment]
It's the player number, as in, this pad is player 1, this one is player 2. Those will be stable during use, not across reboots.

I'm the one that mentioned that this could live in systemd, at least somewhere upstream-ish. It obviously shouldn't be written in shell though.

**Comment by poettering** [comment]
if the assignment doesn't have to be persistent, then things become a lot simpler, as we need no state on /var. That means it's sufficient to have a callout from the udev rules rather than an asynchronously started service. If it that's easy we could probably just ship it along with systemd, provided it can be dumbed down enough an is just one more callout.

**Comment by hzulla** [comment]
Can you give me an example functionality in systemd/udev where I can learn how this is done, so that I can learn from it?

**Comment by poettering** [comment]
Here's an example for a simple udev 'builtin':

https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-btrfs.c

Your code would be similar to that I figure

**Comment by hzulla** [comment]
Ok. Will try.

**Comment by hzulla** [comment]
May take some time due to the upcoming holidays, but will report back when I have something to show. Thanks.
