### ISSUE TITLE
network config file - [Match] by AccessPointName, AccessPointMAC

### ISSUE THREAD

**Issue by amishmm** [systemd/systemd#9466]
Hello,

I would like to have an ability to do a [Match] in .network file to match wireless AccessPoint (by Name or MAC)?

The reason is I go to 2-3 companies (plus home/friend's home wifi).

2 places dont have DHCP server ON; on wifi router but asks to set pre-defined static IP.

Other places have DHCP active.

So my idea is to have three .network files, as follows:

**File: 50-wlan0-c1.network.**
```
[Match]
# this is wifi adapter MAC (not AP MAC)
MACAddress=00:11:22:33:44:55
AccessPointName=company1-AP-Name

[Network]
Address=192.168.1.55/24
Gateway=192.168.1.1
```

**File: 50-wlan0-c2.network**
```
[Match]
MACAddress=00:11:22:33:44:55
AccessPointMAC=company2-AP-MAC

[Network]
Address=192.168.2.28/24
Gateway=192.168.2.10
```

**File: 51-wlan0-dhcp.network**
Anything else on DHCP (50 processed before 51)
```
[Match]
# this is wifi adapter MAC (not AP MAC)
MACAddress=00:11:22:33:44:55

[Network]
DHCP=yes
```

Android and iOS both allow to set IP address per AP. I think Windows allows it too. (not sure though)

Please consider the feature request.

Thank you.

PS: initially posted on Mailing list:
https://lists.freedesktop.org/archives/systemd-devel/2018-June/040910.html

**Comment by yuwata** [comment]
Not sure, but is `AccessPointMAC=` is necessary? I think `AccessPointName=` sounds sufficient. If so, #12842 is sufficient, though the name of the implemented new setting is `SSID=`.

**Comment by amishmm** [comment]
Umm, often I go to places where AP name is factory default. (like Dlink, Netgear etc)

So matching by MAC address (of AP) makes it easy.

**Comment by yuwata** [comment]
OK. I've added a commit to support MAC address of AP (BSSID). If possible, please test the PR. Thank you.

**Comment by amishmm** [comment]
Thank you very much. Your commit mentions that it works only for wpa_supplicant.

Is it work in progress for IWD or IWD Dbus does not provide way to fetch BSSID? In that case I will file RFE with IWD to add BSSID property.

Thank you again.

**Comment by yuwata** [comment]
> Is it work in progress for IWD or IWD Dbus does not provide way to fetch BSSID?

IWD currently does not provide BSSID on DBus. Also, `iwctl` does not show BSSID.

> In that case I will file RFE with IWD to add BSSID property.

Yes, please. Thank you.

**Comment by amishmm** [comment]
> In that case I will file RFE with IWD to add BSSID property.

IWD has added this in their TODO (Support Diagnostics interface)

Commit: https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/?id=b89e0c975681132990608f42a212d3777b379ba4

For transparency I am also giving a link to reply by IWD developer who is kind of against this.

**Personally I do not agree with his views at all.** (in my follow up mail)

https://lists.01.org/pipermail/iwd/2019-June/006469.html

Now we need to wait till this is implemented.

**Comment by yuwata** [comment]
#13142 was merged.
