### ISSUE TITLE
Documentation: networkctl OPERATIONAL state

### ISSUE THREAD

**Issue by neophob** [systemd/systemd#9474]
**Is your feature request related to a problem? Please describe.**
networkctl show the OPERATIONAL state of each interface. However I could not find a definition of the states. (check man page and https://wiki.freedesktop.org/www/Software/systemd/)

**Describe the solution you'd like**
Documentation of each state, for example what defines "routable". Does Systemd does a ping to the gateway? Or does it try to connect somehow to the internet (DNS, NTP..)

**Comment by keszybz** [comment]
Duplicate of #575.
