### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by RXCE** [systemd/systemd#9482]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Not relevant

**Expected behaviour you didn't see**
 > GDPR Compliance

**Unexpected behaviour you saw**
 > GDPR Issues.
 
The systemd project is experimenting and working with various ideas that have privacy ramifications. This includes the work in systemd-resolved and systemd-timesyncd that creates a possibility for disclosure of personal information to Google or similar providers through default code paths. The data remitted such as client IP addresses, subdomains containing usernames or unique IDs, banking domains and similar data may be considered personal data under the GDPR and other EU law. 

I'm not a lawyer here but by creating these mechanisms and choosing Google (or whatever provider) as a default processor, the systemd project and its developers could possibly be considered (at least under my interpretation) as "data controllers" as per the GDPR definition: "natural or legal person [...] alone or jointly with others [...] determines the purposes and means of the processing of personal data" (Article 4), Which while the systemd project doesn't handle the data, it does make determinations on the "how" and "why" that data is processed in that manner and third parties it is disclosed to.

Given the decisions to implement these mechanisms in this manner have been made freely by systemd developers on their own, and not the distributions that utilize systemd, compliance seems to rest upon the systemd maintainers.

I understand that these methods are for user convenience, and that the options are offered in configuration files and as compile time options, but this may be insufficient for compliance due to the plain-language and express opt-in consent requirements of the GDPR. There may be other obligations I'm overlooking as well.

With this in mind, two questions come to mind:

- What are the plans to make systemd GDPR compliant and/or to demonstrate compliance?
- Does systemd or a representing maintainer have Data Processing Agreements with Google or plans to obtain DPAs?

**Steps to reproduce the problem**
Not relevant

**Comment by keszybz** [comment]
GDPR regulates the processing by an individual, a company or an organisation of personal data. Systemd developers (even if we could consider ourselves an organization), do not process any personal data. We just provide the software, and other people and organizations use this software, possibly to process personal data. This is entirely out of our control, so GPDR does not apply to us in any way.

**Comment by RXCE** [comment]
@keszybz Thank you for your response,

> GDPR regulates the processing by an individual, a company or an organisation of personal data. Systemd developers (even if we could consider ourselves an organization), do not process any personal data.

While you are correct that the systemd developers do not process personal data, this is only a part of the picture. There's an entire other side of the GDPR I feel you're overlooking here.

The GDPR makes distinctions between "data controller" and "data processor" for precisely this reason. A controller doesn't necessarily have to process personal data themselves, but are still responsible on the basis that they determine the purpose of data processing and determine how the data is to be processed. It requires that those who release software to obtain consent, enable consent to be withdrawn, to provide privacy policies and to careful on who they choose for providers for the features of their software.

This is expressly designed so that developers and vendors can't release privacy-impacting applications and simply outsource liability to others and leave consumers high and dry by blaming someone else as is common in privacy problems.

As per organization status, the GDPR does not seem to require incorporation to be binding. 

> We just provide the software, and other people and organizations use this software, possibly to process personal data. This is entirely out of our control, so GPDR does not apply to us in any way.

The EU officials realized that groups and organizations responsible for infringing upon privacy are notorious offenders of outsourcing liability. So they introduced the concept of "joint controllers" (https://gdpr-info.eu/art-26-gdpr/) where you don't pass absolute controller liability, you just gain a kind of "partner". Your decisions still make you (and now potentially those who offer your software) potentially liable. This is to create a "chilling effect" on adopting privacy-problematic platforms.

If the systemd developers are concluding that the GDPR doesn't apply to them, then distributions should be made aware that they're potentially joint controllers with a project that may cause them GDPR liability so they can decide whether they should continue to use systemd.

**Comment by RXCE** [comment]
While you are correct that the systemd developers do not process personal data, this is only a part of the picture. There's an entire other side of the GDPR I feel you're overlooking here.

The GDPR makes distinctions between "data controller" and "data processor" for precisely this reason. A controller doesn't necessarily have to process personal data themselves, but are still responsible on the basis that they determine the purpose of data processing and determine how the data is to be processed. 

This is by design.

It's a known quantity that developers and vendors who are irresponsible with their user privacy will often outsource liability through bureaucratic means and leave users with little recourse. Due to these industrial-scale abuses by many companies and groups alike. The GDPR essentially treats the venue that systemd uses ("we just provide software") as a loophole to be closed so that software creators are forced to include privacy into their programs and to more carefully engage with and vet their providers of choice.

What other people do with systemd is irrelevant to systemd's own compliance.

If the systemd developers are really concluding that the GDPR doesn't apply to them, then distributions should be made aware that they're potentially joint controllers with a project that may cause them GDPR compliance issues (and the associated liability) so they can decide whether they should continue to use systemd.

**Comment by evverx** [comment]
@RXCE your interpretation of the GDPR is very interesting. Thank you for sharing it. But could you please stop keeping posting and removing your comments? I'll lock the conversation if that happens again.

**Comment by keszybz** [comment]
After reading about this a bit more and looking at the legal text, I don't think this applies to us at all. Our software can either be compiled and used by individuals directly, and any such use is explicitly excluded from GDPR as a personal activity, or it can be installed on behalf of someone else, in which case they have full control over the compile-time and run-time configuration. I don't see any reason to consider that any shared data processing takes place.

**Comment by poettering** [comment]
@RXCE please contact the downstream distributions using systemd first. if they agree with you that there's a problem they will escalate this back to us, and we'll look into that. Other than that we are not lawyers and what you are doing here smells a lot like trolling to us, in particular as your github account is anonymous and appears to have been created two days ago just for this. Please understand that we neither have the education, interest nor time to entertain legal questions with you.
