### ISSUE TITLE
add an option to respect inhibitor locks also for root users

### ISSUE THREAD

**Issue by ryran** [systemd/systemd#949]
Inhibitor locks are awesome. While one user is in the middle of something, we can prevent some non-root user with console access from rebooting, sleeping, shutting down. Awesome.

Unfortunately, the vast majority of server installations never have physical logins; it's most common that users only login over ssh. So:
1. Users login over ssh
2. Non-root users don't get magic power to reboot over ssh; therefore, non-root users understand that they always need root access to reboot
3. So non-root users always use su/sudo to reboot the machine, making inhibitor locks useless

See where I'm going with this? What if we could also warn root users that try to, e.g., reboot when block-locks are present? Use case:
1. Multiple users have sudo access
2. One user uses `sudo systemd-inhibit` to start some important process that should not be interrupted ... or maybe they're simply doing package-management operations
3. Another user comes in, runs into an issue and decides to `sudo reboot` but instead of rebooting, thankfully, the command errors out with a warning and explanation (with hint that `systemctl reboot --ignore-inhibitors` could be used)

Of course you can use `/run/nologin` to prevent new logins, but that doesn't help if someone has already su'd over to root. It just doesn't cover enough cases. This is a valid new feature that would be welcomed by many sysadmins.

---

I work for Red Hat Support and I can tell you that it's not uncommon for someone with sudo access to reboot a machine that's doing something important. systemd's inhibitor locks could help with that problem ... but not in their current form unfortunately.

So, assuming you see value in what I'm suggesting, let's talk about solutions. We could make inhibitors infinitely more useful to server admins by doing one of the 2 following things.
1.  Simply remove the `if (geteuid() == 0)` check in systemctl's **`check_inhibitors()`**
   - I'll submit a pull request momentarily with this change.
   - I haven't tried to build systemd with this change, but presumably this would make it so that trying to run `reboot` or `poweroff` or `shutdown` or `systemctl reboot` (etc etc) as root would fail with the same warning that non-root users get.
   - I could see some folks making the argument that scripted shutdowns as root should always succeed or that root should always be able to do what they want and teaching folks to use `-i` or `--ignore-inhibitors` is just too big of a change. From a teacher/trainer, sysadmin, and support tech perspective, I say pooh pooh but if that's how the developers feel, what about:
2. Make root-user systemctl actions that would override an inhibitor trigger a warning and a countdown timer, e.g., something silly like "Inhibitor lock present: ....; Ctrl-c in the next 10 seconds to cancel"
   - To be clear, in this scenario, the original action would still happen unless Ctrl-c was pressed, so scripted executions wouldn't need to be affected. Actually, I just noticed the `if (!on_tty())` check ... hmmm.
   - Personally, I would much rather we just start socializing the idea that if root REALLY wants to SHUTDOWN NOW they should use `-i`. To that end, we could also enable the `-i` and `--ignore-inhibitors` option for `reboot`, `poweroff`, `shutdown`, etc. I'll submit a simple pr momentarily that does this.

Thanks for reading!

**Comment by ajblum** [comment]
+1 I'm a sysadmin and I can see the value in this proposal.

**Comment by johannbg** [comment]
Think this through and have that RHEL support carried that patch downstream if they so much desire

**Comment by jscalf** [comment]
This would be a useful change for users with hundreds, if not thousands, of sysadmins, users, operators, (aka 'devops' as they say now), etc, who interact with thousands of servers and can't always be sure what is running and who is running it. These servers have multiple users with root access and they can and do "step on each others toes". This would enable them to have more protection against the unfortunate situation where their work is disrupted by a well meaning colleague who they might not even know, in another geographical location, even, who is trying to complete their own schedule of work. Many organizations these days have regular reboot sessions, this would easily allow exceptions. I work with many such user-bases and have seen the use-case this addresses first-hand. 

Full disclosure: I do work with Ryan. But my opinions are my own.

**Comment by poettering** [comment]
I see the benefit of this, bug just changing the default behaviour of this would probably not be well recieved across the community, since many scripts invoke these binaries, and admins/users would probably be really annoyed if the commands in those scripts would just stop working...

Maybe we can make this an option. For example, mybe add a logind.conf option would this or so.

**Comment by ryran** [comment]
Thanks @poettering for the response. I hope to do something like you described here and in the pr.

In the mean time I wrote a stand-alone tool in python to achieve the same result .. and more.
- [reboot-guard: Block systemd-initiated poweroff/reboot/halt until configurable condition checks pass](https://github.com/ryran/reboot-guard)

**Comment by n-st** [comment]
Is this still on the to-do list?

**Comment by poettering** [comment]
I guess #2680 covers this issue too, let's close this one hence.
