### ISSUE TITLE
WorkingDirectory=/foo/. and WorkingDirectory=/foo/.. fail: Access denied

### ISSUE THREAD

**Issue by AlexanderKurtz** [systemd/systemd#9498]
**systemd version the issue has been seen with**

```
# systemctl --version
systemd 238
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
# 
```

**Used distribution**

Debian Buster

**Expected behaviour you didn't see**

I expect the following unit files to work, since ```systemd.exec(5)``` doesn't say anything about ```WorkingDirectory=``` to only accept fully resolved paths:

```
# cat /etc/systemd/system/foo.service 
[Service]
ExecStart=/bin/true
WorkingDirectory=/tmp/.
# cat /etc/systemd/system/bar.service 
[Service]
ExecStart=/bin/true
WorkingDirectory=/tmp/..
```

**Unexpected behaviour you saw**

Both service files fail to start:

```
# systemctl daemon-reload
# systemctl start foo
Failed to start foo.service: Access denied
See system logs and 'systemctl status foo.service' for details.
# systemctl start bar
Failed to start bar.service: Access denied
See system logs and 'systemctl status bar.service' for details.
# 
```

Manually resolving the ```WorkingDirectory=``` paths makes things work, but why is this necessary?

**Steps to reproduce the problem**

See above

**Comment by filbranden** [comment]
Duplicate of #9107, fixed by #9149 and I'm fairly positive this is included in v239.

I know this fixes the `/.` case, not 100% sure about the `/..` case, can you please check and update this issue if you think the `/..` case is still unclear?

**Comment by AlexanderKurtz** [comment]
Regarding the ```/foo/.``` case: Yes, this is a duplicate of #9107 and it's fixed in systemd 239:

```
# systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
# cat /etc/systemd/system/foo.service 
[Service]
ExecStart=/bin/true
WorkingDirectory=/tmp/.
# systemctl daemon-reload
# systemctl restart foo
# 
```

Regarding the ```/foo/..``` case:

```
# cat /etc/systemd/system/foo.service 
[Service]
ExecStart=/bin/true
WorkingDirectory=/tmp/..
# systemctl daemon-reload
# systemctl restart foo
Failed to restart foo.service: Unit foo.service has a bad unit file setting.
See system logs and 'systemctl status foo.service' for details.
# journalctl -u foo
-- Logs begin at Tue 2018-07-03 19:53:25 CEST, end at Tue 2018-07-03 19:59:05 CEST. --
Jul 03 19:54:33 shepard systemd[1]: Started foo.service.
Jul 03 19:54:44 shepard systemd[1]: /etc/systemd/system/foo.service:3: WorkingDirectory= path is not normalized: /tmp/..
Jul 03 19:58:01 shepard systemd[1]: Started foo.service.
Jul 03 19:58:19 shepard systemd[1]: Started foo.service.
Jul 03 19:59:05 shepard systemd[1]: /etc/systemd/system/foo.service:3: WorkingDirectory= path is not normalized: /tmp/..
# 
```

**Comment by filbranden** [comment]
So also with v239 I think at least the message is clear about it... No longer "Access denied" but now "path is not normalized" with a reference to the path, line in the config and the option itself... I think that was part of the fix (logging this explicitly, with helpful pointers of where this needs to be fixed in the config.)

I think at this point this is intended behavior.

Should we close?

**Comment by AlexanderKurtz** [comment]
Alright, closing this then! I might send a PR to update the documentation though, but this is independant of the issue here!
