### ISSUE TITLE
238 - as root, when/why is systemd-tty-ask-password-agent spawned?

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#9507]
**systemd version the issue has been seen with**
> 238.133

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > `systemctl restart service` should work

**Unexpected behaviour you saw**
> `systemctl restart service` hangs, `ps` shows it is waiting for `/usr/bin/systemd-tty-ask-password-agent --watch`; but I'm root on that machine and there shouldn't be any need to request extra permissions
 > This has happened to me intermittently over the years, but recently it seems to have started happening more often. How should I work around this? Can I debug this somehow ? Sometimes it completes after a few minutes (while I'm waiting, doing nothing), sometimes it times out.

**Comment by keszybz** [comment]
systemd-tty-ask-password agent is probably waiting for a password for a disk or similar. When you run sytemctl, the open password requests are handled. You can check if this is the case with `systemd-tty-ask-password-agent --list`.

It will not do that if not running from a tty, or if `--no-ask-password` is given.

I understand that this is surprising, but designing the right behaviour is complicated:
- it is good if systemd immediately ask for a password which is needed to complete an operation (e.g. you say 'sudo systemctl start /encrypted', and immediately get a prompt)
- it is good if the system was waiting for a password, and it catches the attention of an admin, even accidentally, and is then able to proceed
- it is bad if an admin action unexpectedly blocks on an unrelated password query
But because of the asynchronous nature of systemd jobs, distinguishing cases 1 and 3 is hard. It is not possible to say that a password is unrelated to current job, even if the query was already open when current job was started. Because of the asynchronous nature of systemd, something else might have requested some other transaction that also involves this step, and *not* answering the query might block the latest job too.

**Comment by poettering** [comment]
anyway, long story short if "systemctl restart foobar" fails to work, then this has almost certainly not something the password agent is involved in.

**Comment by poettering** [comment]
@keszybz no. systemctl doesn't care about the password agent and what it does much beyond starting it. systemctl does care about systemd jobs to finish though, and possibly there might be some job that needs a password to complete. So there might be some transitive blocking, but certainly no immediate blocking...

**Comment by keszybz** [comment]
Ah, OK. `systemd-logind/start` depends on `basic.target`, which in turns depends on any mounts and such. So I guess it's a bit surprising, but OK. Maybe we should add some text to systemctl(1) ?

**Comment by SjonHortensius** [comment]
Thanks for your extensive replies, I'm trying to understand what's happening. 

> systemd-tty-ask-password agent is probably waiting for a password for a disk or similar. When you run sytemctl, the open password requests are handled. You can check if this is the case with systemd-tty-ask-password-agent --list.

I actually have a machine where I can reliably reproduce this issue. However, executing `--list` returns nothing. This is my service definition (a default elasticsearch service):

```
[Service]
Type=forking
RuntimeDirectory=elasticsearch
PIDFile=/run/elasticsearch/%I.pid

Environment=JAVA_HOME=/usr/lib/jvm/default-runtime
Environment=CONF_DIR=/etc/elasticsearch/%I
EnvironmentFile=-/etc/default/elasticsearch

WorkingDirectory=/usr/share/elasticsearch

User=elasticsearch
Group=elasticsearch

ExecStart=/usr/bin/elasticsearch -d \
            -p /run/elasticsearch/%I.pid \
            -E path.conf=${CONF_DIR}

LimitNOFILE=65536
LimitMEMLOCK=infinity

Restart=on-failure
SendSIGKILL=no
TimeoutStopSec=0
SuccessExitStatus=143
```

Running `systemctl restart` on this process will hang for a few minutes (while I see `systemd-tty-ask-password-agent` getting started, but `--list` in another terminal returns nothing) until it reaches a timeout:

```
Job for elasticsearch@xxx.service failed because a timeout was exceeded.
See "systemctl status elasticsearch@access_logs.service" and "journalctl -xe" for details.
```

Is there any other way to debug why `systemd-tty-ask-password-agent` gets started ? I'll look into creating a small testcase

**Comment by keszybz** [comment]
Ah, OK, so my guess was completely wrong and @poettering was right. It's just waiting for elasticsearch to double-fork, and it's not happening correctly. Sorry, we can't help you with elasticsearch.

**Comment by SjonHortensius** [comment]
So if e/s doesn't fork, `systemctl` hangs waiting for a password entry 'somewhere' I can't see ? I have a reproducibel testcase btw:

```
[Unit]
Description=systemd-issue-9507

[Service]
Type=forking
PIDFile=/run/test.pid

ExecStart=/bin/sh -c '/bin/systemd-issue-9507 &'

LimitNOFILE=65536
LimitMEMLOCK=infinity

Restart=on-failure
SendSIGKILL=no
TimeoutStopSec=0
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

where `/bin/systemd-issue-9507` contains
```
#!/bin/sh
set -ue

echo $$ >/run/elasticsearch/test.pid
sleep 0.5
exit 143
```

**Comment by SjonHortensius** [comment]
Okay, so to summarize, it seems`systemd-tty-ask-password-agent --watch` always runs alongside `systemctl` whenever invoked, this is not an indication of it waiting for anything.
The reason `systemctl` seemed to hang was simply that it was waiting for the unit to start, and since that failed, it was retrying it a few more times with increasing timeouts.

Maybe `systemctl` could be a bit more verbose when invoked, eg. it could output that starting failed and it will try again, like it currently logs in the journal.

anyway, not a bug

**Comment by woky** [comment]
I'm hitting this issue too, often when restarting docker or lxd. Turns out that it waits on network-online dependency:
```
Mar 25 19:15:49 localhost systemd-networkd-wait-online[33643]: Event loop failed: Connection timed out
```

**Comment by anujchougule** [comment]
Hello @poettering @keszybz ,

Is the bug resolved? I am still facing the same issue on my embedded project with **_Systemd version 243_** when I try to start below sample service **_across containers_**.

```
[Unit]
Description=Protect Performance Test Service

[Service]
ExecStart=/bin/true
ProtectControlGroups=yes
ProtectHome=yes
ProtectKernelModules=yes
ProtectSystem=strict
Type=oneshot
```
When I try to run above service, it takes _~7-8 seconds_ to start. I tried analyzing this with **_ltrace_** & found that ask password agent is getting hung for those many seconds. I even tried giving _--no-ask-password_ option while starting service but still the function **ask_password_agent_open** getting called from inside ask_password_agent_open_if_enabled() despite of check available for --no-ask-password.

```
int ask_password_agent_open_if_enabled(BusTransport transport, bool ask_password) {

        /* Open the ask password agent as a child process if necessary */

        if (transport != BUS_TRANSPORT_LOCAL)
                return 0;

        if (!ask_password)
                return 0;

        return ask_password_agent_open();
}
```
Please suggest.

**Comment by keszybz** [comment]
@woky, @anujchougule See https://github.com/systemd/systemd/issues/9507#issuecomment-404078079 for a good explanation how this bug was resolved. Don't post about unrelated issues in a two-year-old bug.
