### ISSUE TITLE
systemd-tmpfiles: create and remove in wrong order

### ISSUE THREAD

**Issue by thkukuk** [systemd/systemd#9508]
**systemd version the issue has been seen with**
237

**Used distribution**
openSUSE Tumbleweed

**Expected behaviour you didn't see**
The manual page for systemd-tmpfiles states:
   For example, during boot the following command line is executed to
  ensure that all temporary and volatile directories are removed and
  created according to the configuration file:

  systemd-tmpfiles --remove --create

The expected and most logical behavior is, that at first the old stuff is removed and afterwards a clean structure is created.

**Unexpected behaviour you saw**
At first, the new files are created and only afterwards the other ones are deleted. This requires pretty complex regex expressions for the cleanup to not by accident delete the new stuff.

**Steps to reproduce the problem**
Create a simple config with:
d /var/tmp/test
d /var/tmp/test/important
R /var/tmp/test

Create a directory /var/tmp/test with several files in it. 

Run "systemd-tmpfiles --remove --create test.conf". Afterwards, /var/tmp/test and /var/tmp/test/important don't exist. Expected behavior is, that all other files in /var/tmp/test are removed (including important directory), and a new /var/tmp/test/important directory is created.

**Comment by fbuihuu** [comment]
Perhaps said slightly differently:

systemd-tmpfiles-setup.service uses:

`ExecStart=/usr/bin/systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev`

Notice the order of the options: "--create --remove", which means that the following tmpfiles snippet:

```
d /var/tmp/test
d /var/tmp/test/important
R /var/tmp/test
```

wont work as expected since after rebooting /var/tmp/test won't exist since --remove is passed after --create.

According to systemd-tmpfiles(8) man page:

>        It is possible to combine --create, --clean, and --remove in one invocation. For example, during
>        boot the following command line is executed to ensure that all temporary and volatile
>        directories are removed and created according to the configuration file:
> 
>            systemd-tmpfiles --remove --create

--remove should take effect before --create.

**Comment by fbuihuu** [comment]
Hmm I just looked at the code and it seems that the order of the options doesn't matter: it's always done in "--create --remove --cleanup" order.

So either the code is broken or the man page is wrong.

**Comment by poettering** [comment]
Uh, tmpfiles is not an interpretor for an imperative programming language. It supposed to be a tool that *declaratively* lists what should and should not be there during boot.

If you have two lines "d" and "R" for the same dir, then this is simply invalid configuration as you say "this dir should exist" and "this dir should not exist" at the same time, and that can't really work. If we don't detect this now, and don't complain about it, then that's a bug we should fix it. 

Now, if I grok your usecase correctly, then "D" plus nested "d" is what you actually should be using. I am not sure this works correctly either though right now, but if it doesn't, then we should totally fix...

**Comment by thkukuk** [comment]
On Sat, Jul 07, Lennart Poettering wrote:

> Uh, tmpfiles is not an interpretor for an imperative programming language. It
> supposed to be a tool that declaratively lists what should and should not be
> there during boot.
> 
> If you have two lines "d" and "R" for the same dir, then this is simply invalid
> configuration as you say "this dir should exist" and "this dir should not
> exist" at the same time, and that can't really work. If we don't detect this
> now, and don't complain about it, then that's a bug we should fix it.
> 
> Now, if I grok your usecase correctly, then "D" plus nested "d" is what you
> actually should be using. I am not sure this works correctly either though
> right now, but if it doesn't, then we should totally fix...

"D", "d" and "C" together work, but that the behavior of "D" is
different than of "R" or "r" is quite confusing.

  Thorsten


-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & CaaSP
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by poettering** [comment]
I guess this really should print more clear error messages, and could need explicit mention in the man page.

**Comment by poettering** [comment]
I posted #10538 which should comprehensively fix this.

After all I figured we should do clean-up first and creation second, as suggested. Hence we now strictly do removal first (and remove children before parents) and creation second (where we create parents before children). I think this should settle the issue.
