### ISSUE TITLE
systemd-run -p IPAddressDeny=any does not stop network in systemd-nspawn

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9513]
**systemd version the issue has been seen with**

v239

**Used distribution**

Debian sid
Filed as downstream bug report at [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903025](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903025)
I reported the above issue to the Debian Bug Tracking System and Michael Biebl requested me to report it here.

**Expected behaviour you didn't see**

`systemd-run -t -p "IPAddressDeny=any" ping -c 1 192.168.1.1` normally generates `ping: sendmsg: Operation not permitted`.

**Unexpected behaviour you saw**

When we run the above command in `systemd-nspawn -b -M some-machine`, it generates
```
64 bytes from 192.168.1.1: icmp_seq=1 ttl=255 time=0.305 ms
```

By the same reason, `IPAddressDeny=any` has no effect in the systemd service configuration files inside a systemd container. The protection mechanism by `IPAddressDeny=any` does not work at all inside a systemd container. This failure of protection seems potentially dangerous...

**Steps to reproduce the problem**

On the host linux the versions of systemd and systemd-nspawn are both 239. On the guest linux the version of systemd is also 239. Linux kernel package version is 4.16.16-2~bpo9+1.

**Comment by poettering** [comment]
the cgroup bpf stuff that IPAddressDeny= needs is currently not available for delegation to less privileged code. This is a kernel limitation. Hopefully a future kernel will support this sooner or later.

This limitation is documented, actually, see the last paragraph on the option in the man page:

https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#IPAddressAllow=ADDRESS%5B/PREFIXLENGTH%5D%E2%80%A6

**Comment by poettering** [comment]
Let's close this here though as there's little we can do about this until the kernel starts supporting this, and it is documented the way it is.

**Comment by pmartycz** [comment]
> Note that these settings might not be supported on some systems (for example if eBPF control group support is not enabled in the underlying kernel or container manager). These settings will have no effect in that case. If compatibility with such systems is desired it is hence recommended to not exclusively rely on them for IP security.

Why be so lenient here? Shouldn't unit fail to start when it's not possible to restrict access according to its definition?

**Comment by boucman** [comment]
@pmartycz no, the problem with that approch is that a service file can't be reused on multiple systems and the only way to have portable service files is to disable all security feature.

The main people writing service files are
* upstream packagers (which want their service to run everywhere)
* Distro packagers (which have a smaller sense of "everywhere" but still need to think of custom-kernels and stuff like that)

So being strict on security-related options have the opposite effect of what you want : people would not use the feature in large deployment.

Systemd does warn you in the logs when it can't use a security feature because the systemd doesn't support it, though

**Comment by pmartycz** [comment]
Hi. Thanks for the clarification. I understand the rationale although it comes with drawbacks. Like use cases where you *really* want prevent service from accessing network (which it will) and therefore need to be strict. Seems a matter of systemd's perspective is that it views those settings as only hardening measures not security *per se*.

I didn't notice any warning in journal on service start. Might be present in newer systemd version (mine is 245)

**Comment by ialvata** [comment]
I'm currently using a Ubuntu Server 24.04 VirtualBox VM, and it seems that this issue of IPAddressDeny still occurs.

**Comment by WGH-** [comment]
Kernel limitations are understandable, but at least a log warning would be useful, I think.
