### ISSUE TITLE
systemd-sysusers what the feature (WTF) ?

### ISSUE THREAD

**Issue by Direnol** [systemd/systemd#9514]
**Is your feature request related to a problem? Please describe.**
Hello, I'm a beginner developer from Eltex in Russia. I'm interested in the questions:
1) Is there any possibility to implement to add and remove users/groups via systemd-sysusers ? 
2) And where is systemd-sysusers.service?  (Or why it is in man)
3) Can I sync uid:gid on different machines

**Describe the solution you'd like**
1) Maybe add the enable / disable analog that is in the services
2) :-)
3) If it's impossible, then rewrite or throw exception with question: rewrite or ignore

**Comment by poettering** [comment]
This is a bug and feature request tracker, not a support forum. Please direct support requests to the systemd mailing list instead. Thank you for understanding.

https://lists.freedesktop.org/mailman/listinfo/systemd-devel
