### ISSUE TITLE
systemd.network(5) does not have IPVLAN explanation

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9520]
**systemd version the issue has been seen with**

239

**Used distribution**

Debian Unstable

**Expected behaviour you didn't see**

`man systemd.network` should have `IPVLAN=` item like `MACVLAN=`

**Unexpected behaviour you saw**
 
We don't see `IPVLAN=` by `man systemd.network`.

**Steps to reproduce the problem**

`man systemd.network`

**Comment by ryutaroh-matsumoto** [comment]
Michael, thank you!
I thought it was undocumented as IPVLAN is not yet in
the latest online webpage...
https://www.freedesktop.org/software/systemd/man/systemd.network.html
