### ISSUE TITLE
RFE: openssl instead of gnutls

### ISSUE THREAD

**Issue by igor-raits** [systemd/systemd#9531]
It would be nice if there would be build-time switch to use openssl instead of gnutls. The main reason for this is that systemd is part of most of the systems. Also it is part of the buildroot in Fedora for instance.

With recent work on DNS-over-TLS in v239, systemd-resolved started to link against gnutls which added gnutls/nettle into the buildroot. This means that buildroot contains more than 1 crypto library which slows down things and generally could increase problems with security.

If you are interested, I could look into adding buildtime switch for openssl.

**Comment by keszybz** [comment]
IIRC, the last time our thinking was that gnutls is required by various other stuff anyway, and even if we managed to wean systemd off it, it would still be pulled in by that other stuff, so it wasn't worth the effort. I have no idea how much work $subject would be, but if it doesn't make the code ugly, I think it'd be a welcome thing.

**Comment by keszybz** [comment]
On F28, `dnf repoquery --whatrequires openssl --alldeps --qf %{name}|sort -u|wc -l` returns 73, and 275 for gnutls, FWIW.

**Comment by ignatenkobrain** [comment]
Because it is openssl-libs and not openssl.

```
⋊> /u/s/c/registry sudo dnf repoquery --whatrequires openssl-libs --alldeps --qf "%{name}" -q | sort -u | wc -l                                                                                            17:15:53
856
⋊> /u/s/c/registry sudo dnf repoquery --whatrequires gnutls --alldeps --qf "%{name}" -q | sort -u | wc -l                                                                                                  17:15:57
229
```

RPM, cURL, libssh/libssh2, librepo, drpm, coreutils, git-core, libarchive, wpa_supplicant depend on openssl

**Comment by keszybz** [comment]
Ah, right. So yeah, looking at the gnutls list, apart from systemd, there's a few important packages there, like qemu, libvirt, samba, emacs, gnome-terminal, wget, but those are all "leaf" packages. It would be very welcome to allow systemd to link to openssl indeed.

**Comment by poettering** [comment]
I'd very much welcome this change. openssl tends to be better supported these days.

**Comment by ignatenkobrain** [comment]
Note that openssl and gpl plays well for core system libraries/progs. IANAL, but that's what is written in Fedora wiki for licensing.

**Comment by mbiebl** [comment]
Fedora might consider openssl a system library, but that opinion is not universally shared among distributions.
