### ISSUE TITLE
[networkd] Not possible to set stricter user permission files for systemd-networkd files

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#9535]
**systemd version the issue has been seen with**
> systemd 239
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

Systemd 237 has introduced support for the wireguard vpn protocol. The `netdev` file for the wireguard device contains secrets for the server and the clients. (private key of the server + public keys of the clients). On a single user system this is no problem, but on a bigger system with multiple users this is clearly an information leak. It would be nice to have the possibility to set the permission `600` for these files, but this doesn't seem to be possible due to restrictions in `systemd-networkd`. I see multiple options here:

- create an own group/user for systemd-networkd
- run systemd-networkd as root and allow setting 600 for certain files (I don't like this option)
- move the secrets in a separate secret file (we would still have a permission problem, I guess..)

**steps to reproduce**
Error message of `systemd-networkd: 
```
Jul 08 18:01:39 kurisu.nullday.de systemd-networkd[8533]: Could not load configuration files: Permission denied
```
What I did:
```
root kurisu /etc/systemd/network 18:00:58 
❯ ls -la
.rw-r--r--  93 root 23 Feb  2016 ens3.network
.rw-r--r-- 262 root 22 Feb 19:24 wg0.netdev
.rw-r--r--  81 root 22 Feb 19:25 wg0.network
root kurisu /etc/systemd/network 18:01:00 
❯ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 52:54:82:ec:f2:e2 brd ff:ff:ff:ff:ff:ff
    inet 37.120.168.88/22 brd 37.120.171.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:82ff:feec:f2e2/64 scope link 
       valid_lft forever preferred_lft forever
3: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.0.0.1/24 brd 10.0.0.255 scope global wg0
       valid_lft forever preferred_lft forever
root kurisu /etc/systemd/network 18:01:04 
❯ chmod 600 wg0*
root kurisu /etc/systemd/network 18:01:17 
❯ ls
ens3.network  wg0.netdev  wg0.network
root kurisu /etc/systemd/network 18:01:18 
❯ ls -la
.rw-r--r--  93 root 23 Feb  2016 ens3.network
.rw------- 262 root 22 Feb 19:24 wg0.netdev
.rw-------  81 root 22 Feb 19:25 wg0.network
root kurisu /etc/systemd/network 18:01:19 
❯ systemctl restart systemd-networkd
Job for systemd-networkd.service failed because the control process exited with error code.
See "systemctl status systemd-networkd.service" and "journalctl -xe" for details.
root kurisu /etc/systemd/network 18:01:27 
❯ chmod 640 wg0*
root kurisu /etc/systemd/network 18:01:35 
❯ systemctl restart systemd-networkd
Job for systemd-networkd.service failed because the control process exited with error code.
See "systemctl status systemd-networkd.service" and "journalctl -xe" for details.
root kurisu /etc/systemd/network 18:01:39 
❯ chmod 644 wg0*
root kurisu /etc/systemd/network 18:01:44 
❯ systemctl restart systemd-networkd
root kurisu /etc/systemd/network 18:01:50 
❯ ls
ens3.network  wg0.netdev  wg0.network
root kurisu /etc/systemd/network 18:01:51 
❯ ls -la
.rw-r--r--  93 root 23 Feb  2016 ens3.network
.rw-r--r-- 262 root 22 Feb 19:24 wg0.netdev
.rw-r--r--  81 root 22 Feb 19:25 wg0.network
root kurisu /etc/systemd/network 18:01:54 
```

**Comment by yuwata** [comment]
Another option:
- set `StateDirectory=systemd/network` and locate secure configs under /var/lib/private/systemd/network, and create symlinks to the configs in /etc/systemd/network.

When DynamicUser= is enabled, then the private directory cannot be accessed by non-privileged users. Thus, we can safely hide secure info.

**Comment by yuwata** [comment]
Or,
- set `SupplementaryGroups=adm` or `wheel` and adds reading permission to the secure configs.

**Comment by shibumi** [comment]
@yuwata Thanks. I guess this hack solves the issue. Feel free to close this issue.

**Comment by yuwata** [comment]
@shibumi I've added an explanation of the hack in #9574. PTAL.

**Comment by klausenbusk** [comment]
> create an own group/user for systemd-networkd

There is already a `systemd-network` group, which is how I solved the issue on my Arch systems.
```
chown root:systemd-network wg0.netdev
chmod 640 wg0.netdev
```

**Comment by shibumi** [comment]
@yuwata sorry for the circumstances :) I think @klausenbusks solution is the better choice.
