### ISSUE TITLE
user-runtime-dir@XXX.service fails with 'No such user XXX'

### ISSUE THREAD

**Issue by ChenQi1989** [systemd/systemd#9541]
systemd 239

It seems that it's possible that the user is deleted before stopping user-runtime-dir@xxx.service.

The commands are executed via ssh by script.
useradd test1
su -c id test1
su -c 'rpm -qa' test1
userdel test1

And checking `systemctl --failed', the following unit fails.
● user-runtime-dir@1000.service loaded failed failed /run/user/1000 mount wrapper

Related logs are as below.
Jul 09 02:45:38 qemux86-64 systemd-logind[119]: New session c2 of user test1.
Jul 09 02:45:39 qemux86-64 systemd[349]: Startup finished in 1.072s.
Jul 09 02:45:40 qemux86-64 systemd-logind[119]: Removed session c2.
Jul 09 02:45:41 qemux86-64 systemd-timesyncd[103]: Timed out waiting for reply from 216.239.35.12:123 (time4.google.com).
Jul 09 02:45:43 qemux86-64 systemd-logind[119]: New session c3 of user test1.
Jul 09 02:45:45 qemux86-64 systemd[362]: Startup finished in 1.066s.
Jul 09 02:45:47 qemux86-64 systemd-logind[119]: Removed session c3.
Jul 09 02:45:50 qemux86-64 systemd-user-runtime-dir[373]: No such user "1000"

Below is a simple script to reproduce the problem. (Assume target ip is 192.168.7.16.)

#!/bin/sh

ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; useradd test1'
ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; su -c id test1'
ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; su -c "rpm -qa" test1'
ssh -o StrictHostKeyChecking=no root@192.168.7.16 'export PATH=/usr/sbin:/sbin:/usr/bin:/bin; userdel test1'

**Comment by yuwata** [comment]
I cannot reproduce this. With Fedora 28, `su` does not create a new session for user `test1`. What OS do you use in qemu?

**Comment by yuwata** [comment]
I've created PR #9543 for this, but I am not sure it fixes your issue...

**Comment by ChenQi1989** [comment]
I'm using yocto. The su command is from the shadow package. (https://github.com/shadow-maint/shadow)

**Comment by yuwata** [comment]
If possible, could you test #9543?

**Comment by ChenQi1989** [comment]
I've tested the #9543 , it does fix the problem. Thanks.

**Comment by yuwata** [comment]
Thank you for testing this. Let's wait reviews.
