### ISSUE TITLE
Use the same system bus socket address as D-Bus

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#9547]
Calling just `systemd-239/meson` prints:
```
         D-Bus policy directory:            /usr/share/dbus-1/system.d
         D-Bus session directory:           /usr/share/dbus-1/services
         D-Bus system directory:            /usr/share/dbus-1/system-services
```
https://dbus.freedesktop.org/doc/dbus-daemon.1.html says:

> On Unix, the standard session service directories are:
> - *directory*/dbus-1/services for each directory in XDG_DATA_DIRS, where XDG_DATA_DIRS defaults to /usr/local/share:/usr/share (see the XDG Base Directory Specification): these locations are specified by the D-Bus Specification. The defaults are suitable for software installed locally by a system administrator (/usr/local/share) or for software installed from operating system packages (/usr/share). Per-user or system-wide configuration that sets the XDG_DATA_DIRS environment variable can extend this search path to cover installations in other locations, for example ~/.local/share/flatpak/exports/share/ and /var/lib/flatpak/exports/share/ when flatpak(1) is used.

Why does dbus-daemon by default handle both /usr/local/share/dbus-1/services and /usr/share/dbus-1/services, but systemd by default handles only the latter?

**Comment by yuwata** [comment]
Currently, dbus related directories must be specified by the meson options `-Ddbuspolicydir=`, `-Ddbussessionservicedir=`, or `-Ddbussystemservicedir=`.
It may be possible to automatically obtain the dbus related directories from dbus-1.pc file, though I am not sure we should use it...

**Comment by dilyanpalauzov** [comment]
For all the software people want to complie, I expect that `meson && ninja install`, `./configure && make install` and `cmake && make install` has sensitive defaults, that glues everything together and the system just runs, except there are compelling reasons why it should be more complicated for the users than this.

Insisting of not having reasonable defaults loses users' time.

Please ensure that after `dbus-1.12.x/configure && make install`and `systemd-240/meson && ninja install`, dbus glues magically with systemd, and the system just runs.

**Comment by yuwata** [comment]
Hmm, now I am confused. I noticed that it seems that both /usr/share/dbus-1 and /usr/local/share/dbus-1 works fine. So, I expect that 

> `dbus-1.12.x/configure && make install` and `systemd-240/meson && ninja install`

work fine, no? If no, could you specify problems...

**Comment by yuwata** [comment]
```
         D-Bus policy directory:            /usr/share/dbus-1/system.d
         D-Bus session directory:           /usr/share/dbus-1/services
         D-Bus system directory:            /usr/share/dbus-1/system-services
```
Note that these are just install destinations of dbus related files. These are not used when building binaries.

**Comment by dilyanpalauzov** [comment]
How is the default --address for busctl determined?

**Comment by yuwata** [comment]
The default addresses are e.g., /run/dbus/system_bus_socket. it is independent of the dbus _configuration_ directories.

**Comment by dilyanpalauzov** [comment]
Calling `dbus-1.12.8/configure` prints:
```
        System bus socket:        /usr/local/var/run/dbus/system_bus_socket
        System bus address:       unix:path=/usr/local/var/run/dbus/system_bus_socket
```
and puts in dbus-1.pc:
```
system_bus_default_address=unix:path=/usr/local/var/run/dbus/system_bus_socket
```
Does systemd use this address, when D-Bus uses it and if not, do D-Bus and systemd still work together?

**Comment by floppym** [comment]
> Please ensure that after dbus-1.12.x/configure && make installand systemd-240/meson && ninja install, dbus glues magically with systemd, and the system just runs.

This sequence cannot work properly. dbus must be built after systemd is built/installed, since dbus-daemon uses several functions from libsystemd (`sd_listen_fds`, `sd_notify`).

Possibly the dbus configure script should be updated to automatically set the default socket path to `/run/dbus/system_bus_socket` when systemd support is enabled.

**Comment by dilyanpalauzov** [comment]
If I remember correctly, I had the problem, that after I did `./dbus-1.12.x/configure && make install` and `meson && ninja install` in some unreconstructible order I couldn't login, except as root.  I hope there is consensus that this configuration should work in some order.

I had installed a distribution and then replaced the packages one by one with self-compiled code. So systemd was there, and probably its .h and .pc files were also installed and it was possible to install self-compiled dbus, having systemd coming from the distribution.  I agree that either systemd or dbus fixes the address of the system bus and the other software has to respect it, the latest after it is reconfigured, recompiled and reinstalled.

* Wouldn't it be wise, if `systemd-240/meson` prints the address of the system-dbus it is going to use when XDG_RUNTIME_DIR or DBUS_SYSTEM_BUS_ADDRESS are not set?

Either dbus/configure or systemd/meson set the default system bus address, possibly by passing a parameter to the build-configuration-system, and the other software respects the value.  Which package shall decide on this?

Is the dbus session bus address relevant for systemd, and is its address well-fixed, so that the discrepancies are only for the session bus address?

**Comment by floppym** [comment]
I don't agree with the notion that building low level system components without providing any configuration options should be expected to produce a fully working system.

**Comment by dilyanpalauzov** [comment]
> I don't agree with the notion that building low level system components without providing any configuration options should be expected to produce a fully working system.

Alright, lets make things intentionally complex, selecting bad defaults, so that builing (low level) system is difficult and people who can do it get better paid!  Later high-level software shall also take over this approach, as there is no reason why low-level software can insists on explicit parameters to work, but high-level software may not.

Do you have other ideas what on low-level should be made harder to get right than it is now, appart from the session D-Bus address?

Is there any documentation stating that systemd and D-Bus need explicitly to be coordinated in order to get common idea for the session bus address?

**Comment by floppym** [comment]
> Alright, lets make things intentionally complex, selecting bad defaults

Making the system bus path configurable actually makes things more complex for developers, and for sysadmins. I don't really see a benefit. I already suggested changing the dbus configure script to match systemd's assumptions.

> Is there any documentation stating that systemd and D-Bus need explicitly to be coordinated in order to get common idea for the session bus address?

My guess is that this is undocumented. It would definitely make sense to document how systemd expects dbus to be configured, possibly in the README file.

> Is the dbus session bus address relevant for systemd, and is its address well-fixed, so that the discrepancies are only for the session bus address?

I think the recommended approach for the session bus is to configure dbus with `--enable-user-session`. In this case, the session bus is really a "user" bus, and will always be created under `/run/user/$UID/bus` via the `user/dbus.socket` unit.

For normal session buses, I don't think systemd cares about them at all.

**Comment by yuwata** [comment]
> `system_bus_default_address=unix:path=/usr/local/var/run/dbus/system_bus_socket`

Not tested, but this does not work with systemd, as I already said that systemd hard coded the path `/run/dbus/system_bus_socket`. Of course, if you manually create symlink to /run at /usr/local/var/run, then I expect it works.

I am not sure that the requirement of the path to the dbus socket is explicitly documented, but at least, (if I remember correctly), we have documented somewhere that `/var/run` should be a symlink to `/run`. Moreover, I think, `/var` should be the right and only place to store some persistent data of daemons. So, setting `/usr/local/var` by default seems very bad idea at least for me...

**Comment by dilyanpalauzov** [comment]
Moved to D-Bus: https://bugs.freedesktop.org/show_bug.cgi?id=107192

**Comment by filbranden** [comment]
It seems to me the trouble you're running into is due to using the default prefix of `/usr/local` when building DBus...

If you pass `--prefix=/usr` to DBus's `configure` invocation, everything might start working as expected...

Yes, perhaps this is unfortunate, but there are reasons for it and for why DBus might want to keep this explicit, still defaulting to `/usr/local` unless explicitly specified...

Anyways, just a side comment, I hope it's helpful... Good luck!

**Comment by dilyanpalauzov** [comment]
Is the system bus address used by default by systemd fixed to `/run/dbus/system_bus_socket` or it depens on some paramers like -Dprefix ?  How can the address be reconstructed using systemd.pc?

**Comment by dilyanpalauzov** [comment]
Thanks Filipe for your advice.  I want to achive that others don't run in this trouble.

**Comment by dilyanpalauzov** [comment]
Will extending the documentation of systemd to suggest creating the symlinks `/usr/var/run`, `/usr/run/`, `/usr/local/var/run` and `/usr/local/run` to `/run` mess something?

**Comment by floppym** [comment]
> Is the system bus address used by default by systemd fixed to /run/dbus/system_bus_socket or it depens on some paramers like -Dprefix ?

The path is fixed. It is defined here.

https://github.com/systemd/systemd/blob/v239/src/basic/def.h#L39

**Comment by filbranden** [comment]
> Will extending the documentation of systemd to suggest creating the symlinks `/usr/var/run`, `/usr/run/`, `/usr/local/var/run` and `/usr/local/run` to `/run` mess something?

I believe those paths are mostly an artifact of how autoconf handles paths and prefix.

That has nothing to do with systemd, really... It's more about how DBus ends up generating these bogus paths (through its autoconf setup.)

IMO, those paths make no sense and should not be generated at all.

I think what would be more appropriate is for DBus's autoconf to *always* use `/run` regardless of what its `--prefix` is.

But that's up to DBus, not systemd...

I think there's nothing wrong with what systemd is doing here.

And about DBus, maybe they have a valid usecase to using separate `/run`s, perhaps if you're running multiple system instances (perhaps one for testing a new version in your system? developers might do that?) that they have a useful use case there...

Perhaps you should ask DBus why they are defaulting to a `/usr/local/var/run` path that doesn't make much sense? And whether they want to fix that and document that? After all, `/run` is the tmpfs where all control operations happen in modern filesystems (and systemd documents that!) and `/var/run` is the only traditional location where this used to exist, so it's the only one that should need a symlink...

I hope that helps. In any case, this is really starting to get off-topic for here...

Cheers,
Filipe

**Comment by poettering** [comment]
So, systemd only supports /usr as build prefix. This is documented in README explicitly.

We generally drop all files we install into the right paths relative to the used prefix, and that includes dbus stuff. You need to make sure to use a common prefix for dbus and systemd hence. I will extend the README comment in order to clarify that.

Yes, automake/autoconf will use nonsensical paths if you just use --prefix. It's a mess, but this nothing we can fix in systemd really. I wish automake/autoconf wouldn't default to such paths, but we can't fix their project really. I mean, we don't even use automake/autoconf ourselves at all.

It is generally assumed that folks who put together distros are aware about this autoconf/automake idiosyncrasies, and fixing the situation is entirely outside of systemd really.

Closing this here. Pleas take this up to automake/autoconf, and ask them to use more sensible defaults, after all their defaults don't match what a single distro does, but are entirely bogus right now. That said, YMMV, the project appears a bit undermaintained, if I look at the past years.

Hope this makes sense.

**Comment by filbranden** [comment]
I think it's possible the fix (or workaround) might be in DBus' autoconf/automake scripts. They could simply default to always using `/run` regardless of `--prefix`.

I think we used to do that in systemd before we switched to building with Meson.

In any case, like you said, distro maintainers usually know dealing with autoconf/automake is a pain and they typically already know what to do about it... I think at this point no one really has expectations that things will just work without overriding paths or prefix etc.

(So probably not even worth getting DBus involved in changing that.)

**Comment by dilyanpalauzov** [comment]
D-Bus perspective is explained at https://bugs.freedesktop.org/show_bug.cgi?id=107192 .

Distributions put their stuff under /usr, users put their (possibly the same) stuff under /usr/local, so thatdistributuin updates don't modifications made by the user.

In this regard, why not installing systemd by default under /usr/local, so that users can run systemd compiled by theirselves or systemd comming from the distribution?  It s a matter of passing the right init to the kernel.  This will also solve the difference with D-Bus.

**Comment by dilyanpalauzov** [comment]
/usr/local vs is /usr is not about user stuff, it is about who changes/overwrites the software - the operating system vendor or the user.  The provided explanation implies that the user cannot compile himself systemd and prevent that the OS-vendor overwrites it during an update.  At the same time it is not clear, why it shall not be possible for systemd to be compiled and installed by the user.  I think even libc defaults to /usr/local.

It would be better, if no  software considers itself special and, depending of the origin - os vendor or user - installs itself with the appropriate prefix.

**Comment by dilyanpalauzov** [comment]
Please extend the README concerning D-Bus' prefix to state, that the purpose of passing prefix=/usr to D-Bus is to ensure that the system bus addresses used by systemd and D-Bus coincide.

**Comment by poettering** [comment]
> /usr/local vs is /usr is not about user stuff, it is about who changes/overwrites the software - the operating system vendor or the user. The provided explanation implies that the user cannot compile himself systemd and prevent that the OS-vendor overwrites it during an update. 

Yes, this is not supported. systemd is not something users install, but a core component of the OS shipped by the vendor. If you replace systemd on your own you basically build your own OS. Which is entirely fine of course, but in that case you really should know what you are doing.

Hence sorry, but what you are doing is explicitly not something we are interested to support. That shouldn't necessary stop you doing whatever you want to do, but I hope it makes clear we have little interest in changing anything in this regard.

> Please extend the README concerning D-Bus' prefix to state, that the purpose of passing prefix=/usr to D-Bus is to ensure that the system bus addresses used by systemd and D-Bus coincide.

There are more reasons than that. For example dbus' activation files need to be at the right place and so on. I doubt there's any value in being to specific here...

**Comment by dilyanpalauzov** [comment]
My reading of https://dbus.freedesktop.org/doc/dbus-daemon.1.html is that both /usr/local/share/dbus-1/system-services and /usr/share/dbus-1/system-services are checked for dbus' activation files, so it is only about the system bus address.

Why users can/have mechanisms to install kernel and libc, independent from the os-vendor, but not systemd?  Or users can have libc and kernel compiled from the user and from the os-vendor co-exist, but systemd compiled from the os-vendor cannot co-exist with systemd compiled by the user?  Why is systemd more special than kernel and libc?

**Comment by zlk12142** [comment]
bluealsa: E: Couldn't obtain D-Bus connection: Could not connect: No such file or directory
My dbus is installed in /opt/bluez instead of the default path.
Therefore, an environment variable called DBUS_SYSTEM_BUS_ADDRESS must be set according to the DBUS_SYSTEM_BUS_DEFAULT_ADDRESS value in config.log from the compiled dbus-1.15.8 source folder.

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/opt/bluez/var/run/dbus/system_bus_socket
/opt/bluez-alsa/bin/bluealsa -p a2dp-source -p hsp-ag &

"bluealsa: W: Couldn't create storage directory: No such file or directory" can be solved by "mkdir -p /opt/bluez-alsa/var/lib/bluealsa"
