### ISSUE TITLE
SLAAC on VRF interfaces connected to the same network get routes wrong

### ISSUE THREAD

**Issue by RoadRunnr** [systemd/systemd#9552]
**systemd version the issue has been seen with**
> 237-3ubuntu10

**Used distribution**
 > Ubuntu 18.04

**Config**

vrf-red.netdev:
```
[NetDev]
Name=red
Kind=vrf

[VRF]
Table=100
```
red.network:
```
[Match]
Name=red
```

vrf-blue.netdev:
```
[NetDev]
Name=blue
Kind=vrf

[VRF]
Table=101
```

blue.network:
```
[Match]
Name=blue
```

ens224.network:
```
[Match]
Name=ens224

[Network]
VRF=red
DHCP=no
Address=172.20.16.90/24
```

ens256.network:
```
[Match]
Name=ens256

[Network]
VRF=blue
DHCP=no
Address=172.20.16.91/24
```

**Expected behaviour you didn't see**

IPv6 network routes for interfaces bound into the VRF should only be installed in the VRFs routing table, not in the main table.

**Unexpected behaviour you saw**
 
IPv6 routes for VRF interfaces leaking into the main table:
```
$ ip -6 route
local ::1 dev lo proto kernel metric 256 pref medium
2001:470:7720:16::/64 dev ens256 proto ra metric 1024 pref medium
2001:470:7720:16::/64 dev ens224 proto ra metric 1024 pref medium
2001:470:7720:16::/64 dev ens192 proto ra metric 1024 pref medium
default proto ra metric 1024 
	nexthop via fe80::250:56ff:fea0:6a0a dev ens256 weight 1 
	nexthop via fe80::250:56ff:fea0:6a0a dev ens224 weight 1 
	nexthop via fe80::250:56ff:fea0:6a0a dev ens192 weight 1 
```

```
$ ip -6 route show vrf red
fe80::/64 dev ens224 proto kernel metric 256 pref medium
ff00::/8 dev ens224 metric 256 pref medium
```

```
$ ip -6 route show vrf blue
fe80::/64 dev ens256 proto kernel metric 256 pref medium
ff00::/8 dev ens256 metric 256 pref medium
```

**Steps to reproduce the problem**

* have two network interfaces connected to the same network segment
* have IPv6 SLAAC enable on that network segment
* configure VRFs (see above)
* restart networkd
* check main routing table, IPv6 routes for interfaces bound into VRFs should not be present in main table

**Comment by poettering** [comment]
Hmm, can you check with something newer than 237? This VRF code did recieve various fixes in later versions

**Comment by andir** [comment]
@roadrunnr when did the interfaces come up? I suspect they could have been up before they were enslaved in the VRF?

**Comment by RoadRunnr** [comment]
@andir I did reboot the system. Afterwards I couldn't ssh to it because of the duplicate IPv6 routes. That was actually the reason I notice the problem.

I have found a workaround in the meantime. Adding an entry

```
[IPv6AcceptRA]
RouteTable=101
```

to the interface to be enslaved into the VRF with the right table id fixes the issue.

**Comment by toanju** [comment]
In case an a device is enslaved into a VRF this has to be done automatically, so yes. Details can be found here: https://www.kernel.org/doc/Documentation/networking/vrf.txt

**Comment by yuwata** [comment]
Does #11698 help this issue?
