### ISSUE TITLE
systemctl edit template: Failed to get load state: Unit name is neither a valid invocation ID nor unit name.

### ISSUE THREAD

**Issue by Hello71** [systemd/systemd#9554]
**systemd version the issue has been seen with**
systemd 239

**Used distribution**
Arch Linux

**Steps to reproduce the problem**
1. `systemctl edit bitlbee@.service`

(note: /usr/lib/systemd/system/bitlbee@.service is a valid service file)

**Expected behaviour you didn't see**
editor is opened. 

**Unexpected behaviour you saw**
error is printed and editor is not opened.

**Comment by Hello71** [comment]
I think b74df547a90a794ca75eea99238b9ae14a562720 does not work right for editing templates.

**Comment by glebchek** [comment]
Run into that as well when tried to edit systemd-nspawn@

**Comment by 20NE** [comment]
This issue still exist 
systemd 239.0-2

**Comment by 20NE** [comment]
Thanks for reply.
