### ISSUE TITLE
New feature: Command start/stop/restart print also status of the service

### ISSUE THREAD

**Issue by waldauf** [systemd/systemd#9557]
**Describe the solution you'd like**
If I _start/stop/restart_ some service I would like to know its status. That means I have to type next command for displaying status of service. Is it possible to write something like _start**us**_/_stop**us**_/_restart**us**_/ (it comes from _stat**us**_). For example I type `systemctl startus docker` and this command starts docker and displays status of the docker service on the screen.

**Comment by sourcejedi** [comment]
You can tell if `systemctl` succeeded, as it will print no error message. `systemctl` waits for the operation to complete, so it will detect startup failure.  (Unless the service fails after it declares itself started, but then there is nothing we can do).

Or, do you have more information about why you like to know service status after you start/stop/restart it?

**Comment by waldauf** [comment]
I understand what you say. But when you are linux admin you should check your every step which you do. I'm starting different services per day and would like to check them - how long takes the time to start, are there all parameters/options, which sub-process are started, cgroups slices, ... and every time I have to type "status" command. I would like if there will be possibility to do it in one command.

That's the same like when something went wrong. For example starting telegraf service:
```
# systemctl start telegraf-kafka.service
# echo $?
0
#
# systemctl status telegraf-kafka.service
● telegraf-kafka.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/etc/systemd/system/telegraf-kafka.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2018-07-11 13:49:09 CEST; 13s ago
     Docs: https://github.com/influxdata/telegraf
  Process: 4470 ExecStart=/usr/bin/telegraf -aaa -config /etc/telegraf/telegraf-kafka.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 4470 (code=exited, status=0/SUCCESS)

Jul 11 13:49:08 tick systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
#
```
... I know you can write it's about how is written app return code or unit file... but you cannot fix everything. As I wrote for me is better to check everything wham I'm starting.

**Comment by sourcejedi** [comment]
Thank you, this is helping to explain why you want this.  Your example doesn't 100% confirm this as a solution.  Does it work how you want if you run

    # systemctl start telegraf-kafka.service && systemctl status telegraf-kafka.service

Because you might actually be relying on the seconds it takes you to type the command, in order for the service to terminate :).

**Comment by waldauf** [comment]
Thank for your quick replay. Yes I know about your example. In fact, better is:
```
srvc="telegraf-kafka.service"; systemctl start ${srvc}; systemctl status ${srvc}
```
But you have to always replace service name. That's really annoying and boring. :]] Yes, you can create aliases, function, scripts... but you need to do it on every server. New service means new alias on all servers... brrrr don't want to do it everywhere.  That's why I'm asking for these feature.

**Comment by sourcejedi** [comment]
I am asking you if this actually works as a prototype, in the example you gave.

If the service exits 1 second after it reports itself as started - which is what the timestamps in your example output _look_ like - then, it does not help you to run `systemctl status` immediately after `systemctl start`.  It will show that the process was still running - but a second later, it will have exited.

**Comment by waldauf** [comment]
In this case, I suggested, is not so much important to see start result as soon as possible (although I believe it could be important for many people - as you wrote). I mean it more general - just see output after start/whatever service. Hope I clarified it.

**Comment by waldauf** [comment]
I'm thinking about my suggestion and may be will be better some parameter to display status after run command. For example start: `systemctl start telegraf [--printstatus|-ps --printstatusfollow|-psf]` where 

- _-ps_ ... print status of service after run command,
- _-psf_ ... print status and follow output after run command. 

... just results of my thinking about it and try to suggest some solution. :]

**Comment by filbranden** [comment]
Probably related, from the [TODO](https://github.com/systemd/systemd/blob/7b0fce617c48eda32b2d4e04b5f0e4376e8c0106/TODO#L38,L41) file:

> add "systemctl start -v foobar.service" that shows logs of a service
> while the start command runs. This is non-trivial to do without
> races though, since we should flush out all journal messages before
> returning from the "systemctl stop".

**Comment by waldauf** [comment]
It looks similar as I suggested. 

IMHO is for administrator important to see output of start/stop/restart command after enter it without requirement of type new command.

**Comment by waldauf** [comment]
Yesterday I had to replace NetworkManager by _netctl_ manager. I have new systemd service called "netctl@mschapv2_ethernet". When I started this service it returned me RC=0, but after displaying status of service I saw problem with network interface. 

That's next example where I would like to see output of start/stop/restart command immediately after run it.

**Comment by sourcejedi** [comment]
You're not giving enough information in this example either.  You need to show that the bad status or log message, occurs *before* the "Started" message.  You would not gain from modifying `systemctl` to show the status immediately after the "Started" message, if the service hasn't gone bad at that point.  It may be going bad in the time it takes for you to type `systemctl status`.

**Comment by waldauf** [comment]
@sourcejedi Thank you for your response. You're right it could be as you wrote. I tried to simulate my example again but it's not possible any more. Short story - in company where I'm working were some changes in network and on DHCP server and I had problem with assigning new IP address - that's why I had to use netctl instead NetworkManager. I think they fixed problem because I get new IP without any problem. I'll think about next example.

**Comment by waldauf** [comment]
Unexpectedly became a reality... I tried to connect to network with `netctl`:
```
$ sudo systemctl start netctl@mschapv2_ethernet
$ echo $?
$ 0
```
... it took 3.6 seconds.

Then I typed `status` command and got:
```
sudo systemctl status netctl@kb_mschapv2_ethernet
● netctl@mschapv2_ethernet.service - Networking for netctl profile mschapv2_ethernet
   Loaded: loaded (/usr/lib/systemd/system/netctl@.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-08-06 10:34:27 CEST; 20s ago
     Docs: man:netctl.profile(5)
  Process: 10443 ExecStart=/usr/lib/netctl/network start mschapv2_ethernet (code=exited, status=1/FAILURE)
 Main PID: 10443 (code=exited, status=1/FAILURE)

Aug 06 10:34:03 jenpockej network[10443]: enp0s31f6: DHCP lease expired
Aug 06 10:34:03 jenpockej dhcpcd[10533]: enp0s31f6: DHCP lease expired
Aug 06 10:34:03 jenpockej dhcpcd[10533]: enp0s31f6: soliciting a DHCP lease
Aug 06 10:34:27 jenpockej network[10443]: timed out
Aug 06 10:34:27 jenpockej dhcpcd[10533]: timed out
Aug 06 10:34:27 jenpockej dhcpcd[10533]: dhcpcd exited
Aug 06 10:34:27 jenpockej network[10443]: DHCP IPv4 lease attempt failed on interface 'enp0s31f6'
Aug 06 10:34:27 jenpockej network[10443]: Failed to bring the network up for profile 'mschapv2_ethernet'
Aug 06 10:34:27 jenpockej systemd[1]: netctl@mschapv2_ethernet.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 10:34:27 jenpockej systemd[1]: netctl@mschapv2_ethernet.service: Failed with result 'exit-code'.
```

**Comment by waldauf** [comment]
New example with Kafka - I added commented lines just for better readability:
```
$ time sudo systemctl start kafka && echo $? && time sudo systemctl status kafka -l --no-pager
# 1. command - start service:
sudo systemctl start kafka  0.01s user 0.01s system 86% cpu 0.026 total

# 2. command - echo RC:
0

# 3. command - status service:
● kafka.service - Kafka publish-subscribe messaging system
   Loaded: loaded (/usr/lib/systemd/system/kafka.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-08-06 11:51:31 CEST; 11ms ago
  Process: 17360 ExecStart=/usr/bin/java -Xmx1G -Xms1G -server -XX:+UseCompressedOops -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSScavengeBeforeRemark -XX:+DisableExplicitGC -Djava.awt.headless=true -Xloggc:/var/log/kafka/kafkaServer-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dkafka.logs.dir=/var/log/kafka -Dlog4j.configuration=file:/etc/kafka/log4j.properties -cp /usr/share/java/kafka/* kafka.Kafka /etc/kafka/server.properties (code=exited, status=1/FAILURE)
 Main PID: 17360 (code=exited, status=1/FAILURE)

Aug 06 11:51:31 jenpockej systemd[1]: Started Kafka publish-subscribe messaging system.
Aug 06 11:51:31 jenpockej kafka[17360]: Unrecognized VM option 'UseParNewGC'
Aug 06 11:51:31 jenpockej kafka[17360]: Error: Could not create the Java Virtual Machine.
Aug 06 11:51:31 jenpockej kafka[17360]: Error: A fatal exception has occurred. Program will exit.
Aug 06 11:51:31 jenpockej systemd[1]: kafka.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 11:51:31 jenpockej systemd[1]: kafka.service: Failed with result 'exit-code'.
sudo systemctl status kafka -l --no-pager  0.00s user 0.02s system 83% cpu 0.027 total
```

**Comment by sourcejedi** [comment]
I'm not sure what you're trying to say. Do you want to close this?  Or are you just acknowledging that so far, it looks like none of the examples that frustrate you would have been solved by showing the status on the instant after "Started ..."? (but you think there are other possible examples that might be?)

For the netctl one, you should find the "Started" if you look back further in the log. (`journalctl -b -u netctl@kb_mschapv2_ethernet` or so).  It seems fairly clear the dhcpcd process took over 20 seconds to fail.  Your start command took less than that.  Clearly the netctl service is clearly written to run (and fail) asynchronously.

**Comment by waldauf** [comment]
You're right - netctl is bad example (because DHCP timeout). 

What I'm trying to show you is - where you're a system administrator you welcome the opportunity of displaying status after  start/... commands. For example the Kafka service I mentioned. I don't know how to difficult is implement into systemd.

**Comment by sourcejedi** [comment]
> So far, it looks like *none* of the examples that frustrate you would have been solved by `systemctl` showing the status on the instant after the `Started ...` message was logged

If you would like to open a separate tracking issue as an RFE, showing your support for the specific TODO item in https://github.com/systemd/systemd/issues/9557#issuecomment-404264825 , please feel free.  (And you can mention if you like `startus` as a command, better than `start -v`).

This thread seems to be discussing multiple problems which would *not* be solved by https://github.com/systemd/systemd/issues/9557#issuecomment-404264825 .  I have looked at each log carefully and I can't see what *systemd* could do that would make you happier about this :-).

Of course if you have any example where systemd doesn't do what we think it is supposed to, we would be very interested to hear about it.  In that case I would recommend reporting a new issue to detail the new example and explain exactly how systemd mis-behaves.  I would also suggest re-reading this thread first, i.e. my comment on each example, when writing your explanation.
