### ISSUE TITLE
systemd-sleep should respect RESUME= on the kernel cmdline

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#9559]
**systemd version the issue has been seen with**

v239

**Used distribution**
 
Debian sid
Originally filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902416

In the referenced downstream bug report a user reported, that after the upgrade to v239, his system no longer resumes from hibernate.
It turned out that he had multiple swap partitions. The configured swap partition is not the larger one in his case.
The commit https://github.com/systemd/systemd/commit/17c40b3a8fbfb797110c88d749bd5 changed systemd-sleep to always pick the largest swap partititon.

If a user explicitly has configured a swap partition via the ```RESUME=``` kernel command line or by changing /sys/power/resume this should take precedence. Picking the largest one in case of multiple swap partitions should only be a fallback. 

cc @superm1

**Comment by superm1** [comment]
I'm onboard with if `RESUME=` set on kernel command line to not do anything but I disagree that changing `/sys/power/resume` manually should be kept.  The reasoning being is that swaps can be dynamically loaded and removed and if someone pre-configures `/sys/power/resume` incorrectly to a swap that no longer exists it can still be fixed up by systemd.

**Comment by poettering** [comment]
I tend to agree with @superm1: we should respect explicit user configuration (such as RESUME=), but the sysfs file is not really user configuration, it's simply an API.

**Comment by mbiebl** [comment]
Having support for ```RESUME=``` would not automatically fix existing user setups. How do you intend to deal with that? I think 17c40b3 should be reverted until this regression has been fixed.

**Comment by zachsmith** [comment]
@mbiebl, This issue should be fixed with the merge of https://github.com/systemd/systemd/pull/12760 which will now honour the value of `/sys/power/resume`.

**Comment by mbiebl** [comment]
@zachsmith Does that only apply if a swapfile is used? If so, I don't see how this issue is fixed given that the original bug reporter uses swap partitions.

**Comment by zachsmith** [comment]
@mbiebl if the user has set a swap partition as the device in `/sys/power/resume`, that will be used above any swapfile. The other bug was related to using swapfiles on Btrfs and having `resume_offset=` ignored. The fix added support for both `resume=` and `resume_offset=` (both required for swapfiles) so I believe it should resolve this issue, too. The logic goes like this:

* if the user has `/sys/power/resume` && `/sys/power/resume_offset`, they have correctly configured a swapfile - use that.
* else if the user has only set `/sys/power/resume`, they have correctly configured a partition, use that.
* else if the user has only set `/sys/power/resume_offset` but not `/sys/power/resume`, log a debug message and ignore the offset and continue to the next condition.

* finally, if the user has requested hibernate and has not correctly configured `/sys/power/resume` and `/sys/power/resume_offset`, try and determine the correct configuration by inspect `/proc/swaps`.

https://github.com/zachsmith/systemd/blob/64602c843beb228be919e5f0639427b60d589ec6/src/sleep/sleep.c#L159-L183

**Comment by mbiebl** [comment]
@zachsmith thanks for the clarification. The approach you outlined above looks reasonable to me.
