### ISSUE TITLE
Shutdown or reboot hangs because dbus.service was stopped too early by systemd

### ISSUE THREAD

**Issue by kfiz** [systemd/systemd#9565]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > System shouldn't hang at shutdown or reboot 

**Unexpected behaviour you saw**
 > System hangs 2min almost always at shutdown or reboot 

**Steps to reproduce the problem**
Log in to user account at graphical target. Execute `systemctl reboot` or `shutdown -h now`

This bug was already documented years ago at the systemd-devel mailing list:

https://www.mail-archive.com/systemd-devel@lists.freedesktop.org/msg13345.html

I have been having exactly the same symptoms for a while now. Some service under my `user@.service` instance is trying to query dbus, but dbus.service has been shutdown earlier by systemd. Has there been a fix to this in the meantime? If so that fix is not working on my machine.

Best 

Doro

**Comment by poettering** [comment]
Fix waiting in #9617
