### ISSUE TITLE
`plymouth.enable=0` causes "Start request repeated too quickly" for systemd-vconsole-setup.service

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#9568]
**systemd version the issue has been seen with**
v239-120-g0fad72fae

**Used distribution**
 Fedora 28

**Expected behaviour you didn't see**
systemd-vconsole-setup.service is started once only during boot.

**Unexpected behaviour you saw**
"Start request repeated too quickly" for systemd-vconsole-setup.service

**Steps to reproduce the problem**

Boot with `plymouth.enable=0` in the kernel command line.

`plymouth-start.service` depends on `systemd-vconsole-setup.service`. If you boot with `plymouth.enable=0`, a `Condition` on the plymouth unit will stop it from reaching the active state.  But the plymouth unit ends up being repeatedly started for some reason, so `systemd-vconsole-setup.service` is started repeatedly.  This causes it to fail with "Start request repeated too quickly".

At a guess, it is repeatedly re-activated when a service is dynamically activated e.g. due scoket activation or a specific device appearing, and the activated service pulls in plymouth-start.service via sysinit.target.  I guess this can happen during boot while sysinit.target has not finished activating yet.

## Solution?

It seems like `systemd-vconsole-setup.service` is missing `RemainAfterExit=yes`. Adding that avoided the error during boot.

I also wonder if we can avoid the repeated activations (I counted 13?) in the first place though. These would be really annoying if the service in question failed each time, for example. Maybe we could compare timestamps between the start job for `sysinit.target`, and the last modification to sysinit.target's dependencies, and avoid re-activating its dependencies based on that?

---

The other weirdness that I noticed with `systemd-vconsole-setup.service`, is that it *only* seems to be pulled in by plymouth-start.service. I can't find any other unit which pulls it in (and it has no [Install] section). I guess sysinit.target should have a static dependency on it (in `sysinit.target.wants/`).  I think systemd-ask-password-console.service should probably pull it in as well.

**Comment by yuwata** [comment]
C.f. #3742, especially https://github.com/systemd/systemd/pull/3742#issuecomment-236089127.

**Comment by sourcejedi** [comment]
Thanks!  That makes a lot of sense.  Looks like we eventually stopped pulling in `systemd-vconsole-setup.service`, but plymouth also needs updating to stop pulling it in.

So the main issue here is not our bug, let's just close it. As you might guess I have looking at plymouth code; I will send plymouth a patch.

**Comment by qiangzhao** [comment]
Hi @sourcejedi :
Sorry for a quick question, just in curious: How did you find the plymouth unit ends up being repeatedly started? Do you use some command or have found any logs?

Because plymouth-start.service has conditions like: "ConditionKernelCommandLine=!plymouth.enable=0", So I suppose that the plymouth should not restart at this scenario.

**Comment by sourcejedi** [comment]
@qiangzhao I must have been looking at the system log ("journal").

I guess what happened is that `Condition*` is tested just before the plymouth unit would be started. 

Therefore, if *something* tries to repeatedly start the plymouth unit, all the *dependencies* of the plymouth unit will be started again. If the dependencies were still active, that's fine, we won't need to restart them. But there was a problem because this dependency (`systemd-vconsole-setup`) was a one-shot unit that did not use `RemainAfterExit=yes`.

**Comment by qiangzhao** [comment]
@sourcejedi :
Thank you so much for the detailed reply. 
In this way, I guess the root cause of this problem is the thing that tries to repeatedly start the Plymouth unit. Maybe a limitation of "Condition *= ..." can avoid these meaningless restarts,  but it will also prevent the necessary retry of the plymouth-start unit in some scenarios.
So I suppose the fix should not happen inside Plymouths' units. the fix should find the "thing" and stop it to restart the Plymouth. 
I'm looking forward to your great comments.  thank you!

**Comment by sourcejedi** [comment]
@qiangzhao sorry, this next reply is probably *too* detailed :-).

As far as I can tell, this issue started happening because `RemainAfterExit=yes` was removed from `systemd-vconsole-setup.service`.  It was removed because the way it is used by `systemd` project (specifically `systemd-udev`) did not need it anymore.  But plymouth is still using it the old way, so it causes this issue...

I did not manage to send a patch to plymouth, or tell anyone about this.

---

In general, I got stuck when I was looking at plymouth, so I was not sure what it *should* do. If someone has time and energy, they might find some way to make improvements :-P.

Plymouth (in Fedora Linux) can support this new feature: the console stays in graphics mode for the whole boot process. https://fedoraproject.org/wiki/Changes/FlickerFreeBoot

I *think* flicker-free-boot does not work properly with vconsole-setup, due to an old limitation of the kernel. The kernel ioctls to change the console font, do not work if the console is in graphics mode instead of text mode...

Testing just now on Fedora Linux 31:

1. Edit `/etc/vconsole.conf`. Change the FONT= line to an obvious different size font, e.g. `drdos8x14`.
2. Log in on a text console (e.g. ctrl+alt+f6).
3. `startx /usr/bin/xterm`
4. Move the cursor inside the xterm and run `systemctl restart systemd-vconsole-setup`
5. `exit`

Actual result -> Current text console font is the same size as it was before. No error messages are logged.

6. Staying on the text console, run `systemctl restart systemd-vconsole-setup`.

Actual result -> Current text console changes font size.

---

Additionally, you can't set the font on a text console if the console has not yet been allocated :-). To start with, only `/dev/tty1` is allocated. When a new console is allocated, it copies the font from the current console.

During plymouth "flicker free boot", the current console is always in graphics mode.  So I *think* it breaks the font setting system of vconsole-setup.

I thought removing the kernel limitation would not be very easy. If I remember correctly, the limitation is a feature of the internal interface for the different text console drivers. Specifically, it makes things easy for the old VGA text console driver.
