### ISSUE TITLE
systemctl enable aborts on first non existing unit

### ISSUE THREAD

**Issue by DamienRobert** [systemd/systemd#9581]
This is more a RFE than a bug:

When calling `systemctl enable nonexisting.service existing.service`, I get
Failed to enable unit: Unit file nonexisting.service does not exist.

However when calling `systemctl disable nonexisting.service existing.service`, 
the existing symlink for existing.service is removed.

But then `systemctl enable nonexisting.service existing.service` won't reenable 'existing.service' because of the earlier error, so enable is not symmetric with disable.

**Comment by George359** [comment]
> This is more a RFE than a bug:
> 
> When calling `systemctl enable nonexisting.service existing.service`, I get
> Failed to enable unit: Unit file nonexisting.service does not exist.
> 
> However when calling `systemctl disable nonexisting.service existing.service`,
> the existing symlink for existing.service is removed.
> 
> But then `systemctl enable nonexisting.service existing.service` won't reenable 'existing.service' because of the earlier error, so enable is not symmetric with disable.

**Comment by George359** [comment]
Factory

**Comment by mrc0mmand** [comment]
This seems to work as expected in v255:
```
# systemctl is-enabled systemd-homed
enabled
# systemctl disable foo systemd-homed
Failed to disable unit: Unit file foo.service does not exist.
# systemctl is-enabled systemd-homed
enabled
# systemctl disable systemd-homed
Removed "/etc/systemd/system/sockets.target.wants/systemd-userdbd.socket".
Removed "/etc/systemd/system/multi-user.target.wants/systemd-homed.service".
Removed "/etc/systemd/system/dbus-org.freedesktop.home1.service".
Removed "/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service".
# systemctl enable foo systemd-homed
Failed to enable unit: Unit file foo.service does not exist.
# systemctl is-enabled systemd-homed
disabled
```
