### ISSUE TITLE
rework dynamicuser allocation logic to gracefully handle if we can't take the /etc/passwd lock if the user already exists

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#9583]
**systemd version the issue has been seen with**
systemd-239-2.fc29.x86_64

**Used distribution**
Fedora Rawhide

**Expected behaviour you didn't see**
systemd-networkd (and other services using `DynamicUser=`, such as systemd-resolved) starts and works fine.

**Unexpected behaviour you saw**
```
Jul 13 11:10:58 rawhide.libvirt systemd[1]: Starting Network Service...
Jul 13 11:10:58 rawhide.libvirt audit[717]: AVC avc:  denied  { write } for  pid=717 comm="(networkd)" name=".pwd.lock" dev="dm-0" ino=656097 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file permissive=0
Jul 13 11:10:58 rawhide.libvirt systemd[717]: systemd-networkd.service: Failed to update dynamic user credentials: Permission denied
Jul 13 11:10:58 rawhide.libvirt systemd[717]: systemd-networkd.service: Failed at step USER spawning /usr/lib/systemd/systemd-networkd: Permission denied
Jul 13 11:10:58 rawhide.libvirt systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=217/USER
Jul 13 11:10:58 rawhide.libvirt systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Jul 13 11:10:58 rawhide.libvirt systemd[1]: Failed to start Network Service.
```

**Steps to reproduce the problem**
Just start systemd-networkd with the default setup of a Fedora Rawhide, with SELinux enabled.

**Comment by filbranden** [comment]
So there are a few problems here...

1. First is that this is being blocked by SELinux policy, perhaps this could be addressed? But that entails having an `init_t` process (systemd) be able to manage passwd files and SELinux is basically about preventing that type of thing from happening...<br>
If we wanted to do that, we could update https://github.com/fedora-selinux/selinux-policy to include `auth_manage_passwd(init_t)` in `policy/modules/admin/usermanage.te` but, again, that's a potential gaping security hole, so I think it would be questionable... /cc @wrabcak who can perhaps comment here.

2. Second is that even if we add `systemd-network` user to `/etc/passwd`, it will still try to grab the lock. Maybe we should first check whether the user already exists and not even try to add it in that case? I understand there's a race condition there, but in that case we could do the check twice, second time with the lock held to see if the user still doesn't exist and we still need to add it.

3. Third problem is that when we get the -EPERM here we don't really fail gracefully. The only way I managed to start systemd-networkd here was to disable `DynamicUser=no` with a drop-in. Even with the user already added to /etc/passwd.<br>
The [code](https://github.com/systemd/systemd/blob/v239/src/core/dynamic-user.c#L455,L460) checks for -EROFS (/etc is read-only) and acts gracefully in that case, but not when it gets this -EPERM (which might be due to security policy.)<br>
True, -EPERM could mean something different, so it's not as clear-cut here... And ideally we would want to prevent the AVC from even being logged in this case... But perhaps more graceful handling of this case would be good to have.

Anyways, I'll probably start seeing if I can find a good solution for (2) here, since I think that might be the most straightforward way forward.

Regarding (1), perhaps using a separate binary (systemd-useradd?) to manage /etc/passwd would be a good solution, since then there's a SELinux transition involved and it's way more contained than allowing `init_t` as a whole to manage that file...

Cheers,
Filipe

**Comment by doverride** [comment]
Probably futile. I believe system already needs access to raw storage for its RootImage= functionality. If it can write raw disk then all bets are off.

**Comment by doverride** [comment]
Regardless, This is the wrong place for this report. It should go to selinux-policy at bugzilla.redhat.com.

**Comment by filbranden** [comment]
Sounds good, I'll file a bug at bugzilla.redhat.com and probably send a PR to fedora-selinux too.

I still think systemd should bypass trying to lock the passwd file if the user it's about to create already exists, so there's a point to this bug here...

**Comment by zdzichu** [comment]
Downstream bug is already filed: https://bugzilla.redhat.com/show_bug.cgi?id=1559281

**Comment by filbranden** [comment]
So about fixing (2) here, I'm looking at the code and it's not completely clear here why we're grabing the lock to /etc/passwd. I guess it's because we're about to allocate a new user/userid so we want to avoid any races with tools like useradd, etc.

So I'm trying to figure out how to best avoid that lock. I think it's probably safe in the case where we have DynamicUer=yes but also User=... set. But then only in the case where that user already exists.

Would it be fine in that case to just check it with `getpwnam()` and be done with it?

@poettering Can you please comment? Do you think we can skip that lock in some specific situation where everything is already in place?

Cheers,
Filipe

**Comment by poettering** [comment]
> I guess it's because we're about to allocate a new user/userid so we want to avoid any races with tools like useradd, etc.

correct

**Comment by poettering** [comment]
> @poettering Can you please comment? Do you think we can skip that lock in some specific situation where everything is already in place?

well, it's supposed to fix the race where two pieces of code register the same user a the same time: we take the lock, check if the user exists, and only if it doesnt, we create it, and then release the lock.

We handle EROFS gracefully as we know that in that case "adduser" won't be able to add users, hence we don't need to protect ourselves against that. (i.e. EROFS is generally understood to mean "filesystem not writable", to anyone.) It's a tiny bit sloppy still, since like systemd other components which are not like adduser might add users too, and we won't synchronize against that here in this case.

Handling EPERM is a completely different case however: EPERM just means *we* can't access the lock, but it says little about others. Hence we treat this fatally, as the race would still be there: somebody else might create the user we'd like to create right when we are creating it...

(This is a real problem btw, for example, if we now readd the networkd users and friends to sysusers.d/ again, then it will be PID1's DynamicUser= logic that's going to race against systemd-sysusers for the same name, hence we really should be careful and synchronize things)

I'd be happy to use a different lock file btw, if everybody just could agree on one. Using a lock in /etc for this is less than ideal anyway, it would be much better placed in /run, as it is a runtime object, and would allow us to synchronize things properly an any setup. Unfortunately however changing it is kinda hard, as it is exposed through glibc lckpwdf(). 

If you want to allow systemd to acquire the lock, but not change /etc/passwd with selinux then my natural suggestion would be to use two separate labels for that.

**Comment by poettering** [comment]
> Do you think we can skip that lock in some specific situation where everything is already in place?

hmm, i figure this would make sense: i.e. try to acquire the lock, and if it fails instead of propagating the flag, let's check if the user exists already and use it if it exists. If it doesn't, then fail for good, propagating the original error.

**Comment by wrabcak** [comment]
Hi All, 
Sorry for late reply, I was on vacation. 

I had a discussion with @msekletar  about this and there is no need for systemd to write to /etc/passwd, systemd just needs to create to /etc/.pwd.lock. As @poettering  already mentioned, we should use two different SELinux labels, one for /etc/passwd and one for lock file. This will be fix in selinux-policy. I see it as risky fix, I would prefer fix in systemd. Also, it looks like you would like to change it in systemd code and move the lock file to /run .

Lennart, 
What is your opinion here? Will systemd use different lock file? 

Thanks,
Lukas.

**Comment by filbranden** [comment]
Lock file in /run only works if everyone who's using that lock starts using it in /run...

I'm still planning a somewhat graceful fallback in systemd (in case the user already exists, created by tmpfiles) but long term it seems to me we'll need a better solution, better integration with SELinux.

What's worse? systemd pid 1 (init_t) being allowed to write to passwd_file_t? Or create a new group for the lock? Or possibly use an external helper (not init_t) that should be able to perform operations of registering the new users?

**Comment by wrabcak** [comment]
> What's worse? systemd pid 1 (init_t) being allowed to write to passwd_file_t? 

Why should we allow it, if systemd doesn't really needs it? It seems to me just to hide the issue.

> Or create a new group for the lock? 

passwd_file_t is base and security label, all domains accessing this file for writing/creating could also create aj lock file, creating new label and splitting label for lock file and for passwd could bring regression and I would like to avoid this situation.

> Or possibly use an external helper (not init_t) that should be able to perform operations of registering the new users?

Best solution from my POV.

**Comment by filbranden** [comment]
@wrabcak So I tried to solve this using an external tool, so I introduced a `systemd-pwdlock` that would grab the lock to `/etc/.pwd.lock` and pass the open FD back to systemd, which could hold it until it's done with it.

Code in systemd is [here](https://github.com/filbranden/systemd/commit/644672bcb3ae6eacef1b469d870ef8328b6d5ee1) and the associated selinux-policy change is [here](https://github.com/filbranden/selinux-policy/commit/93594a6d339a5642d7b8f607225250ab450813bc).

With this approach, I'm running into some trouble, though... When I pass the open FD back to systemd (running on context init_t), SELinux will trigger an AVC for `{ write }` on passwd_file_t, even though systemd did not really open the FD or even did any write operations on it... From [this thread](http://selinux.tycho.nsa.narkive.com/Wuy62nIx/selinux-security-and-passed-file-descriptors), looks like that's expected...

I tried to work around it by changing the context of the "FD object" (I thought that's what `fsetfilecon`) but I didn't realize it was actually touching the context of the `/etc/.pwd.lock` file instead... 😞I guess at some point while running in permissive mode I ended up changing the context of the file, which made me think the approach was working, when in fact it wasn't...

So, @wrabcak, do you have a suggestion of a way to accomplish that? Without having to just allow init_t to access passwd_file_t?

Also, @poettering, want to take a look if you like this approach? (Assuming there's a way to accomplish this in SELinux...)

Let me know if you think there's a way... Otherwise, should we proceed with allowing init_t to access passwd_file_t? I can send you a PR for that in selinux-policy...

Cheers,
Filipe

**Comment by kirbyfan64** [comment]
Question: is there a "good" workaround for this? Manually changing the context of some file? Right now I just used `systemctl edit` and set `DynamicUsers=false` on the services that weren't starting...

**Comment by mskarbek** [comment]
@kirbyfan64 it is either what you described or adding SELinux module that allows access to the `passwd` file:
```
# cat systemd-dynamicuser.te 
module systemd-dynamicuser 1.0;

require {
	type init_t;
	type passwd_file_t;
	class file write;
}

#============= init_t ==============
allow init_t passwd_file_t:file write;
```

**Comment by kirbyfan64** [comment]
@mskarbek Thanks!

**Comment by filbranden** [comment]
@wrabcak, @poettering, what do you suggest we do about this?

If we should just allow init_t to grab the lock, then fedora-selinux/selinux-policy#220 solves that (@wrabcak can you please review?)

My [attempt to solve this using an external tool](https://github.com/filbranden/systemd/commit/644672bcb3ae6eacef1b469d870ef8328b6d5ee1) didn't really work, because I wrote a tool (`systemd-pwdlock`) that opens the lock file and passes the FD back to systemd, but SELinux blocks init_t from even receiving that FD through a socket, since it needs the same policy for it...

One possible (but more ambitious) attempt would be to have more of this dynamic user setup run as a separate binary... For instance, `unit_setup_dynamic_creds()`. I believe this is a larger surgery though, not sure how easy that would do... From my tracing this code, it seems to me that the dynamic user part is already happening on a forked process, so maybe it wouldn't be that bad to do an `exec()` there and pass some info to it?

Anyways, let me know if you're willing to explore the external binary approach. Otherwise, can we go ahead with fedora-selinux/selinux-policy#220 please?

Cheers!
Filipe

**Comment by wrabcak** [comment]
I made decision that, I'll allow it in SELinux policy to write to all files labeled as passwd_file_t. Fix will be part of next builds of selinux-policy. Will add links to this thread.

**Comment by wrabcak** [comment]
Links with fix:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1135126
https://koji.fedoraproject.org/koji/buildinfo?buildID=1135130

**Comment by eclipseo** [comment]
>Links with fix:
>https://koji.fedoraproject.org/koji/buildinfo?buildID=1135126
>https://koji.fedoraproject.org/koji/buildinfo?buildID=1135130

Still not working as expected with this fix. I still get errors when DynamicUser is tryng to create the /var subdirectories when using for example:

```
DynamicUser=yes
CacheDirectory=dnscrypt-proxy
LogsDirectory=dnscrypt-proxy
RuntimeDirectory=dnscrypt-proxy
```
Here the raw error:
```
Raw Audit Messages
type=AVC msg=audit(1534174797.410:3350): avc:  denied  { create } for  pid=3634 comm="(pt-proxy)" name="dnscrypt-proxy" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=0

Hash: (pt-proxy),init_t,var_t,dir,create
```

To solve all the errors I added this module:

```
module my-ptproxy 1.0;

require {
	type var_t;
	type passwd_file_t;
	type init_t;
	type var_log_t;
	class file { create write };
	class dir { create setattr };
	class lnk_file { create getattr read };
}

#============= init_t ==============
allow init_t passwd_file_t:file { create write };
allow init_t var_log_t:dir { create setattr };
allow init_t var_log_t:lnk_file { create getattr read };
allow init_t var_t:dir { create setattr };
allow init_t var_t:lnk_file create;
```

But I think this should work out of the box when using DynamicUser.

**Comment by wrabcak** [comment]
Updated selinux-policy with following Allow rules:
#============= init_t ==============
allow init_t passwd_file_t:file { create write };
allow init_t var_log_t:dir { create setattr };
allow init_t var_log_t:lnk_file { create getattr read };
allow init_t var_t:dir { create setattr };
allow init_t var_t:lnk_file create;

**Comment by doverride** [comment]
On Tue, Aug 21, 2018 at 05:32:32AM -0700, Lukas Vrabec wrote:
> Updated selinux-policy with following Allow rules:
> #============= init_t ==============
> allow init_t passwd_file_t:file { create write };
> allow init_t var_log_t:dir { create setattr };
> allow init_t var_log_t:lnk_file { create getattr read };
> allow init_t var_t:dir { create setattr };
> allow init_t var_t:lnk_file create;
> 

A couple of suggestions:

1. add equivalence rules to maintain consistenct labels between for example /var/log/ and /var/log/private

/var/cache/private /var/cache
/var/lib/private /var/lib
/var/log/private /var/log

2. adjust all interface for var_cache, var_log, and var_lib to allow the caller to read the lnk file that points to the private dirs

> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/9583#issuecomment-414657502

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
On Tue, Aug 21, 2018 at 05:32:32AM -0700, Lukas Vrabec wrote:
> Updated selinux-policy with following Allow rules:
> #============= init_t ==============
> allow init_t passwd_file_t:file { create write };
> allow init_t var_log_t:dir { create setattr };
> allow init_t var_log_t:lnk_file { create getattr read };
> allow init_t var_t:dir { create setattr };
> allow init_t var_t:lnk_file create;

Looks like you forgot /var/lib?

> 
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/9583#issuecomment-414657502

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wrabcak** [comment]
@doverride 

I'm not sure what you mean by second point:
adjust all interface for var_cache, var_log, and var_lib to allow the caller to read the lnk file that points to the private dirs

Could you create PR or explain? 

THanks,
Lukas.

**Comment by doverride** [comment]
On Tue, Aug 21, 2018 at 10:58:32AM -0700, Lukas Vrabec wrote:
> @doverride 
> 
> I'm not sure what you mean by second point:
> adjust all interface for var_cache, var_log, and var_lib to allow the caller to read the lnk file that points to the private dirs
> 
> Could you create PR or explain? 

Take for example:

interface(`files_search_var_lib',`
	gen_require(`
		type var_t, var_lib_t;
	')

	search_dirs_pattern($1, var_t, var_lib_t)
')

I would add here:

files_read_var_lib_symlinks($1)

Because lets say you have "myapp" that has a StateDirectory and you want to provide an interface to that content like so

interface(`myapp_read_var_lib',`
	gen_require(`
		type var_t, var_lib_t;
	')

        allow $1 myapp_var_lib_t:file read_file_perms;
	allow $1 myapp_var_lib_t:dir list_dir_perms;
	allow $1 myapp_var_lib_t:lnk_file read_lnk_file_perms;
        files_search_var_lib($1)
')

Then callers of myapp_read_var_lib() will automatically be able to read the /var/lib/myapp symlink that points to /var/lib/private/myapp

You will not have to explicitly have to add files_read_var_lib_symlinks everytime it applies to a statedir in "/var/lib/private", it will automatically be allowed.

> 
> THanks,
> Lukas.
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/9583#issuecomment-414765720

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by msekletar** [comment]
@wrabcak what is the status of the selinux-policy changes?

**Comment by wrabcak** [comment]
@msekletar added patches based on recommendation from @doverride

**Comment by eclipseo** [comment]
@wrabcak Preliminary test of selinux-policy-3.14.1-41.fc28 seems to have solved my issues. Thanks!

**Comment by wrabcak** [comment]
@eclipseo  Thans for testing! I added few more allow rules to make that dynamicuser will work with SELinux in enforcing state.

**Comment by filbranden** [comment]
Confirmed that this is fixed with a recent selinux-policy (running selinux-policy-3.14.3-2.fc30.4.noarch on Rawhide in my case and this is working.) Thanks @wrabcak !
