### ISSUE TITLE
nss-systemd's getpwent sets errno to ENOENT

### ISSUE THREAD

**Issue by fishilico** [systemd/systemd#9585]
**systemd version the issue has been seen with**
> v209

**Used distribution**
 > Arch Linux (package systemd 239.0-2)

**Expected behaviour you didn't see**
When using a `getpwent()` loop in a C program, I expect it to end without setting errno if the enumeration was successful. Here is a C program which illustrates such a loop:
```c
#include <sys/types.h>
#include <pwd.h>
#include <errno.h>
#include <stdio.h>

int main(void)
{
    struct passwd *pw;
    errno = 0;
    setpwent();
    while ((pw = getpwent()) != NULL) {
        printf("%d: %s\n", pw->pw_uid, pw->pw_name);
    }
    printf("getpwent errno = %d (%m)\n", errno);
    endpwent();
    return 0;
}
```

**Unexpected behaviour you saw**
The C program shows "getpwent errno = 2 No such file or directory" (`errno` 2 is `ENOENT`). This suggests an error happened, even though everything else seems to work fine.

If nss-systemd is removed from `/etc/nsswitch.conf`, `errno` remains 0.

**Steps to reproduce the problem**
* Configure `/etc/nsswitch.conf` to use `nss-systemd` for `passwd` ("`passwd: files mymachines systemd`")
* Write the C program into a file.
* Compile it using `gcc` for example.
* Run it and watch for the resulting "`getpwent errno = ...`" line.

**Additional information**
`errno` is set to `ENOENT` in `_nss_systemd_getpwent_r` when there are no more entries to enumerate: https://github.com/systemd/systemd/blob/de7436b02badc82200dc127ff190b8155769b8e7/src/nss-systemd/nss-systemd.c#L780-L784

This issue has also been reported to glibc's bug tracker (https://sourceware.org/bugzilla/show_bug.cgi?id=23410). It has been categorized as invalid because:
> NSS_STATUS_NOTFOUND is not an error condition and the nss module must not modify errno.

Therefore it seems that statement `*errnop = ENOENT;` needs to be removed from `_nss_systemd_getpwent_r` and `_nss_systemd_getgrent_r`. What is your opinion on this matter?

**Comment by yuwata** [comment]
Thank you. I've created #9587.

**Comment by bigon** [comment]
Hello,

Are we sure this is fixed in 240?

I still get `getpwent errno = 22 (Invalid argument)` when running the test case in the initial report
