### ISSUE TITLE
[IPv6Prefix] adds empty prefixes to RA's if Prefix= option is not set.

### ISSUE THREAD

**Issue by halvors** [systemd/systemd#9589]
**systemd version the issue has been seen with**
> 237 (But not fixed in newer versions either)

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
 > When adding [IPv6Prefix] networkd does not check if "Prefix=" also is set before using it as a prefix.

**Unexpected behaviour you saw**
 > When adding [IPv6Prefix] section without the Prefix= line in it, a prefix with zero as addresss is added to RA's. The prefix seen is ::/64 which does not make sense.

**Steps to reproduce the problem**
Add this config to an interface:
[Network]
IPv6PrefixDelegation=yes (Or static)

[IPv6Prefix] (With no parameters or atleast not the "Prefix=" one)

**Comment by halvors** [comment]
To clearify, a simple check for address part of prefix not being zero before adding it to RADV should do the trick.

**Comment by poettering** [comment]
Fix waiting in #11010.
