### ISSUE TITLE
allow building resolved, but not nss-resolve via a build-time switch

### ISSUE THREAD

**Issue by nicola-lunghi** [systemd/systemd#9596]
Hi all, 
I have this problem:

in my system we are using libmusl so systemd-resolved is not present but we are using systemd to configure the network interface via *.network files.

How can I hook up a script to update the resolv.conf file from systemd?

I explain better.
My network is configured with DHCP

```
[Match]
Name=eth0

[Network]
DHCP=ipv4
```

How can I get from DHCP the information regarding the dns server and from those write a resolv.conf file?
Can I launch the resolvconf package from systemd?
There are parameters that can I get from systemd regarding interface name and dns server that I get from DHCP?

Thanks
Nick

**Comment by poettering** [comment]
systemd-resolved manages /etc/resolv.conf for you. If you want this to work, then you really need to install resolved. 

We don't support musl explicitly, but I don't see why resolved shouldn't work too with musl if you made networkd work?

**Comment by nicola-lunghi** [comment]
Hi
thank you for your response.
I'm building systemd in Yocto with libmusl
(I'm not very familiar with all the libc libraries that's why I'm asking)
the recipe is here

http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_237.bb?h=master

the problem in building with libmusl is all the references to the include file <nss.h>

as stated here
https://wiki.musl-libc.org/future-ideas.html#mDNS-and-alternate-hostname-database-backends

musl doesn't have the include file <nss.h>.

This file is actually included in 

```
src/basic/nss-util.h:#include <nss.h>
src/nss-myhostname/nss-myhostname.c:#include <nss.h>
src/nss-mymachines/nss-mymachines.c:#include <nss.h>
src/nss-resolve/nss-resolve.c:#include <nss.h>
src/nss-systemd/nss-systemd.c:#include <nss.h>
```

Is that file really used?
what about the nss-utils.h header?

**Comment by yuwata** [comment]
I am not sure but I guess systemd-resolved can be built without the headers, as systemd-resolved does not include nss-util.h or nss.h. If you want to use resolvconf and build with musl, then I suggest that patch meson.build or something to build systemd-resolved without nss modules.

**Comment by nicola-lunghi** [comment]
I managed to build it with this patch


```
From 7ebcea5054d11f28c9a6601c6613bcef741df576 Mon Sep 17 00:00:00 2001
From: Nicola Lunghi <nicola.lunghi@jci.com>
Date: Mon, 16 Jul 2018 17:32:55 +0000
Subject: [PATCH] systemd-resolve: fix build with musl

musl doesn't provide nss.h and the symbol
NETDB_INTERNAL and NETDB_SUCCESS.
define those symbol to permit compilation of systemd-resolved

Signed-off-by: Nicola Lunghi <nicola.lunghi@jci.com>
---
 src/basic/nss-util.h          | 19 +++++++++++++++++++
 src/nss-resolve/nss-resolve.c |  7 ++++++-
 2 files changed, 25 insertions(+), 1 deletion(-)

diff --git a/src/basic/nss-util.h b/src/basic/nss-util.h
index 4fc676395..111834d62 100644
--- a/src/basic/nss-util.h
+++ b/src/basic/nss-util.h
@@ -22,7 +22,26 @@
 
 #include <grp.h>
 #include <netdb.h>
+#ifdef __GLIBC__
 #include <nss.h>
+#else
+#include <stdint.h>
+enum nss_status {
+    NSS_STATUS_TRYAGAIN = -2,
+    NSS_STATUS_UNAVAIL,
+    NSS_STATUS_NOTFOUND,
+    NSS_STATUS_SUCCESS,
+    NSS_STATUS_RETURN
+};
+/* Data structure used for the 'gethostbyname4_r' function.  */
+struct gaih_addrtuple {
+    struct gaih_addrtuple *next;
+    char *name;
+    int family;
+    uint32_t addr[4];
+    uint32_t scopeid;
+};
+#endif
 #include <pwd.h>
 #include <resolv.h>
 
diff --git a/src/nss-resolve/nss-resolve.c b/src/nss-resolve/nss-resolve.c
index fe6ce4cbb..67ce1d9ea 100644
--- a/src/nss-resolve/nss-resolve.c
+++ b/src/nss-resolve/nss-resolve.c
@@ -20,7 +20,12 @@
 
 #include <errno.h>
 #include <netdb.h>
-#include <nss.h>
+#ifndef NETDB_INTERNAL
+#define NETDB_INTERNAL (-1)
+#endif
+#ifndef NETDB_SUCCESS
+#define NETDB_SUCCESS (0)
+#endif
 #include <stdlib.h>
 #include <string.h>
 
-- 
2.17.1


```

**Comment by poettering** [comment]
I'd be willing to merge a patch that adds a meson build time option for disabling all nss-resolve and nss-mymachines individually. With that you could simply turn off nss-resolve for your build but get the rest of resolved

**Comment by nicola-lunghi** [comment]
Hi
thanks.
I am not very familiar with systemd source code that patch that I've posted could cause some problem?
If you add a build switch could be very useful. Could this impact the systemd-resolve functionality?
Thanks
Nick

**Comment by nicola-lunghi** [comment]
also is nss.h really necessary?

**Comment by poettering** [comment]
@nicola-lunghi well, afaik musl doesn't support NSS. And hence there's no point at all in building nss-resolve at all. With your patch you are building an nss module that you cannot use as musl would never bother with it. Hence I offered to merge a patch that makes building nss-resolve optional, so that you can leave resolved on but turn off nss-resolve.

In general, we focus on glibc only, as that really defines Linux' API. We expect that alternative libcs maintain compatibility on their own towards glibc, and will not merge work-arounds into the systemd codebase, when the correct fix is to adjust the altnerative libc to match glibc's apis. However, what we are willing to do is merge build system changes so that building nss-resolve as a whole is optional, and you simply turn it off at the time you call "meson". This would as a side-effect make things work on musl for you, as suddenly it doesn't matter at all whether musl defines the NSS interfaces or not, as the whole module is not built anymore...
