### ISSUE TITLE
systemd unmounts home directory

### ISSUE THREAD

**Issue by JohRest** [systemd/systemd#9608]
**systemd version the issue has been seen with**
> the most recent version of systemd I received from the Arch Linux core repos has the problem that I have to manually mount the /home directory (is on own /dev/sdb1 part) the umount -a succeeds without problems. I checked journalctl output, and I can see that systemd mounts /home normally as it should, but later on it states that it unmounted it. And the messages are no error messages, but info messages; as it is something it does normally and is not considered an error.

If wanted I can share the output of journalctl on my system.

**Used distribution**
 > Arch Linux (current)

**Expected behaviour you didn't see**
 > /home directory should be mounted at boot up

**Unexpected behaviour you saw**
 > /home is unmounted and no one can log in due to its absense.

**Steps to reproduce the problem**
basic arch installation with /home (btrfs) on a separate disk

**Comment by poettering** [comment]
Please provide relevant logs of the mounting and unmounting, ideally with debug logging enabled (i.e. with systemd.log_level=debug on the kernel cmdline). Otherwise there's nothing we can do.

**Comment by JohRest** [comment]
Hallo Lennart,

anbei das Log. Ich hoffe es nützt was.

[bootlog-laptop.txt](https://github.com/systemd/systemd/files/2201701/bootlog-laptop.txt)

**Comment by JohRest** [comment]
ah, one more thing...

I did not had this behaviour with previous systemd versions. but as arch keeps a dense update frequency I receive newer versions recently...

Cheers
Johannes aus München

**Comment by arvidjaar** [comment]
`/home` was mounted during boot

`Jul 17 14:55:08 laptopJohannes systemd[1]: home.mount: Changed mounting-done -> mounted`

But then unmounted because device apparently disappeared

```Jul 17 14:55:10 laptopJohannes systemd[1]: dev-disk-by\x2dlabel-p_home.device: Changed plugged -> dead
Jul 17 14:55:10 laptopJohannes systemd[1]: home.mount: Trying to enqueue job home.mount/stop/replace```

a lot of other devices briefly change stated `plugged -> dead -> plugged` at the same time. I cannot say from logs why it happened.

**Comment by JohRest** [comment]
I saw that too.

If I do a mount -a then it's mounted with no problem. Also I have the situation of having /var mounted on a separate disk.. but I have no idea if this is related in any fashion.

Probably not.

I'm thinking about installing an older version of systemd with my arch system to see if that solves it...

As being said, my system worked without problems for some time, then it started to show this problem.

**Comment by JohRest** [comment]
I just downgraded the systemd version, but still the /home directory needs to be mounted manually afterwards...

Perhaps this is some sort of hardware issue... I can live with that and I just run that command one for every day...

Thanks anyway folks!

**Comment by poettering** [comment]
hmm, "laptop-mode.service" is restarted all the time. What is that service? do things work if you turn that service off? there's some coincidence there that the device disappears when that service gets reloaded... But dunno...

What does "udevadm info /dev/sdb1" say right after the mount disappeared?

**Comment by JohRest** [comment]
interesting…
laptop-mode.service is part of the laptop mode tools intended to increase battery life, see https://wiki.archlinux.org/index.php/Laptop_Mode_Tools

I'm working with my other workstation and I don't have access to the laptop at the moment (will take an hour or so) but as soon as I have access I will a) disable the service and b) run the suggested command…

I will post the outcome.

**Comment by JohRest** [comment]
So access is back. Here's the outcome of the command...

[udevadm.txt](https://github.com/systemd/systemd/files/2203026/udevadm.txt)

And afterwards I've disabled the laptop-mode-tools package. 

AND: the /home drive magically is back again!

I will test more reboots and see whether this was accidental, but I think you solved it!

I do not know exactly what caused this, but I operate the laptop mostly with AC power on, so there will be no difference in running the toolset anyway.

Thanks Lennart!

**Comment by boucman** [comment]
can you paste laptop-mode.service ?

**Comment by mbiebl** [comment]
@boucman The code can be found at https://github.com/rickysarraf/laptop-mode-tools

**Comment by filbranden** [comment]
Haha 1,300 lines of shell script, what could ever go wrong...

It has a [timer unit](https://github.com/rickysarraf/laptop-mode-tools/blob/1.72.2/etc/systemd/laptop-mode.timer) to keep restarting it every 2.5 minutes... So that might explain why it's restarting all the time.

**Comment by JohRest** [comment]
year, I removed the package entirely from the disk. So there's no other way to this…

but the /home directory keeps unmounting; so laptop mode tools was not the cause. 

I don't know what's causing this, to be honest. Manual mounting always works, so the hardware in itself is fine. perhaps I'll reformat everything and start over from scratch…

**Comment by JohRest** [comment]
did another test… I changed the order in fstab of /var and /home mounting… 

the first couple of tests showed promising results, as /home came back again.

I will monitor this and do a couple of boot procedures today...

**Comment by Entkenntnis** [comment]
I have the same problem: A separate data-partition specified in fstab is mounted on boot and unmouted immediately afterwards. This behaviour started with the latest systemd-update from arch repo.

**Comment by Entkenntnis** [comment]
[Discussion on Arch Forum](https://bbs.archlinux.org/viewtopic.php?id=238554)
Current fix: downgrade lvm2 to 2.02.177

**Comment by JohRest** [comment]
hm, as far as I know I do not have lvm2 in use… well, if that fixes this for you; I'm glad that it did… !

**Comment by jbg** [comment]
I have this problem or a variant of it. Fresh install of Arch Linux, `/home` on an md raid1 formatted with ext4 and listed in fstab like this:

```
UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx	/home   	ext4      	rw,relatime	0 2
```

Upon boot, `/home` is not mounted until I log in locally. Attempting to log in over SSH without being logged in locally at the time fails because it cannot read `~/.ssh/authorized_keys`. `/home` is unmounted as soon as I log out locally, even if I am currently logged in via SSH.
