### ISSUE TITLE
Resource control in a grand child of system.slice partially fails

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9623]
**systemd version the issue has been seen with**

239-5 in Debian testing

**Used distribution**

Debian testing

**Expected behaviour you didn't see**

Assume the unified cgroup hierarchy. Prepare `system-child.slice` and `system-child-child.slice` in `/etc/systemd/system` as follows, and run `systemctl start system-child-child.slice`.

```
# systemctl cat system-child.slice system-child-child.slice
# /etc/systemd/system/system-child.slice
[Unit]
After=system.slice
Wants=system.slice

[Slice]
Slice=system.slice
#TasksMax=10000
#CPUQuota=90%

# /etc/systemd/system/system-child-child.slice
[Unit]
After=system-child.slice
Wants=system-child.slice

[Slice]
Slice=system-child.slice
TasksMax=10000
CPUQuota=50%
```

I expect that `cpu.max` and `pids.max` in `/sys/fs/cgroup/system.slice/system-child.slice/system-child-child.slice` have reasonable values.

**Unexpected behaviour you saw**

```
# cd /sys/fs/cgroup/system.slice/system-child.slice/system-child-child.slice
# cat pids.max
10000
# cat cpu.max
cat: cpu.max: No such file or directory
```

I wonder if this issue is another symptom coming from the same root cause as [9578](https://github.com/systemd/systemd/issues/9578). In [9578](https://github.com/systemd/systemd/issues/9578) no controller is enabled at `/sys/fs/cgroup/user.slice/user-$UID.slice` and two symptoms are somewhat different. This issue was produced on a Debian testing virtual machine mentioned [here](https://github.com/systemd/systemd/issues/9578#issuecomment-405100786).

**Steps to reproduce the problem**

See above. Some additional information are as follows:

```
# systemctl status --full system-child.slice
● system-child.slice
   Loaded: loaded (/etc/systemd/system/system-child.slice; static; vendor preset: enabled)
   Active: active since Tue 2018-07-17 15:59:08 UTC; 18min ago
    Tasks: 0
   Memory: 0B
   CGroup: /system.slice/system-child.slice

Jul 17 15:59:08 debian-testing systemd[1]: Created slice system-child.slice.
# systemctl status --full system-child-child.slice
● system-child-child.slice
   Loaded: loaded (/etc/systemd/system/system-child-child.slice; static; vendor preset: enabled)
   Active: active since Tue 2018-07-17 15:59:08 UTC; 18min ago
    Tasks: 0 (limit: 10000)
   Memory: 0B
   CGroup: /system.slice/system-child.slice/system-child-child.slice

Jul 17 15:59:08 debian-testing systemd[1]: Created slice system-child-child.slice.
```

OK, the above seems fine... But

```
# systemctl show -p CPUQuota -p TasksMax -p CPUAccounting -p TasksAccounting system-child-child.slice
CPUAccounting=no
TasksAccounting=yes
TasksMax=10000
```

* `system-child-child.slice` does not have `CPUQuota` property.
* [`CPUQuota` in systemd.resouce-control](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#CPUQuota=) says _Implies "CPUAccounting=true"._, but `CPUAccounting` is not implied and remains false...

**Comment by ryutaroh-matsumoto** [comment]
I set `systemd.log_level=debug` to the kernel command line and grep'ed `Failed to enable controller`. Related errors to this issue is only

```
Jul 17 21:53:01 debian-testing systemd[1]: Failed to enable controller cpu for /system.slice/system-child.slice (/sys/fs/cgroup/system.slice/system-child.slice/cgroup.subtree_control): No such file or directory
```

This means that systemd fails to add the CPU controller to the parent slice `system-child.slice`, while probably successes to add the Tasks controller to `system-child.slice`. The reason behind success of Tasks and failure of CPU is that `system.slice` enables the Tasks controller and disables the CPU controller acccording to `DefaultTasksAccounting=yes` and `DefaultCPUAccounting=no`. I guess that `cg_enable_everywhere()` in `basic/cgroup-util.c` may have to see controllers of its ancestors also and enable ancestors' controllers if necessary.

**Comment by ryutaroh-matsumoto** [comment]
I have verified that this behavior happens even if we can add the CPU controller by `echo +cpu >/sys/fs/cgroup/cgroup.subtree_control` unlike [9733](https://github.com/systemd/systemd/issues/9733).

**Comment by poettering** [comment]
So, this too is a effect of the same cgroup realization problems as #9512 I am very sure, let's hence close this one too as duplicate.
