### ISSUE TITLE
changing .netdev files and restarting has no effect if interface already exists

### ISSUE THREAD

**Issue by OtherSystems** [systemd/systemd#9627]
**systemd version the issue has been seen with**
> 239-5

**Used distribution**
 > debian stretch & debian sid

**Expected behaviour you didn't see**
 > when restarting systemd-networkd, the vlan does not reconfigured. When changing the vlan id in the .netdev file and restarting, the vlan on the interface stays the same.

**Steps to reproduce the problem**

setup a vlan using systemd-networkd
restart systemd-networkd and confirm vlan is created (ip -d link show)
change vlan id in the .netdev file of the vlan
restart systemd-networkd
observe the vlan id on the interface is still the intial vlan id and not the new one (ip -d link show)

**Comment by poettering** [comment]
networkd uses .netdev files only to create network devices that are missing, and that's it. If you delete the vlan manually, then it should be set up again correctly

**Comment by yuwata** [comment]
Please use `networkctl delete INTERFACE` and `networkctl reload`.

**Comment by mweinelt** [comment]
Please implement recreation of netdevs if their parameters mismatch. It is annoying, because it very easily goes unnoticed.

**Comment by lukas2511** [comment]
This also affects the wireguard configuration using systemd-networkd

Every time I want to add new peers or add new allowed ip ranges to existing peers I have to completely delete the wireguard interface and let systemd-networkd create it again. This disrupts existing connections on that interface, which makes it really annoying.

**Comment by grahamc** [comment]
This issue makes bonds a bit tricky. One of the default side-effects of loading the `bonding` kernel module is getting a `bond0` "for free" in `balance-rr` mode.

A somewhat typical solution to this is to set some modprobe options to make bond0 the type you want. For example: `options bonding mode=802.3ad`. However, this makes the first bond a special case configuration-wise.

Another option is to set the misnamed "max_bonds" option to zero to disable the creation of bond0 altogether: `options bonding max_bonds=0` and then correctly create the bond in userspace.

I just wanted to call out that NixOS is considering applying a patch which sets the default "max_bonds" to 0 at compile time: https://github.com/NixOS/nixpkgs/pull/161281. This fits with our philosophy (and I think systemd's philosophy) of declarative configuration more nicely, at the expense of diverging from upstream's behavior.

**Comment by yuwata** [comment]
We already provides `options bonding max_bonds=0`. See https://github.com/systemd/systemd/blob/db9ecf050165fd1033c6f81485917e229c4be537/modprobe.d/systemd.conf.

Note, I am slowly working on this RFE, and WIP PR is #22557.

**Comment by grahamc** [comment]
Thanks for the reference @yuwata, we've evidently missed this in our integration and are resolving that in https://github.com/NixOS/nixpkgs/pull/161391. I appreciate it!

**Comment by mjt0k** [comment]
> Upd of [this](https://github.com/systemd/systemd/issues/9627#issuecomment-954780114) solution
> wg syncconf wg0server <(sed -e 's/WireGuardPeer/Peer/g' -e 's/WireGuard/Interface/g' -e '/NetDev/d' -e '/Name/d' -e '/Kind/d' -e '/Description/d' -e '/RouteTable/d'  /etc/systemd/network/wg0server.netdev)
> ```

A nice hack. It doesn't work when using PrivateKeyFile= though, - need to read that file and change the keyword to PrivateKey= .
