### ISSUE TITLE
removing VLAN= from .network file and restarting systemd-networkd doesn't remove vlan from interface

### ISSUE THREAD

**Issue by OtherSystems** [systemd/systemd#9628]
**systemd version the issue has been seen with**
> 239-5

**Used distribution**
 > debian sid

**Expected behaviour you didn't see**
 > when removing the VLAN= line from a .network file, that the vlan gets removed from that interface.

**Unexpected behaviour you saw**
 > when removing the VLAN= line from the .network file for an interface, the vlan device did not get removed from the interface when restarting systemd-networkd

**Steps to reproduce the problem**
create a vlan in a .netdev file
add vlan to an interface by adding a VLAN=<vlanname> line its .network file
restart systemd-networkd
see vlan being added to the interface (ip link show)
remove VLAN= line from .network file of the interface
restart systemd-networkd
observe the vlan still being present on the interface (ip link show)

**Comment by ryutaroh-matsumoto** [comment]
[The manual page of systemd-networkd](https://www.freedesktop.org/software/systemd/man/systemd-networkd.service.html) says

> This also means that when configuration is updated and systemd-networkd is restarted, netdev interfaces for which configuration was removed will not be dropped, and may need to be cleaned up manually.

I think what you reported is exactly the documented behavior.

**Comment by OtherSystems** [comment]
You are correct. Initially it seemed unintuitive, but I can see the value of leaving manually configured stuff on it's own.

Sorry about that :)
