### ISSUE TITLE
[systemd-networkd] DHCPv6 client fails to set ipv6 address upon resume from suspend or upon carrier loss and restore

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#963]
systemd 224

Normally, with systemd-networkd DHCP and  DHCPv6, like dhcpcd, if the carrier on an interface is lost, or if the system is suspended, then the DHCP and DHCPv6 configured IP addresses for the interface are explicitly removed.  And when the system resumes, or the carrier is restored, then systemd-networkd DHCP and dhcpcd DHCPv6 will explicitly solicit and configure IPv4 and IPv6 addresses.

But not so with systemd-networkd DHCPv6.  Setting "DHCP=yes" in the .network configuration file, upon resume from suspend, where the IPv6 address is lost with vltime expired, the IPv6 address is not restored on resume.  And, if the carrier is lost, the - then useless - IPv6 address is not removed.  Also, particularly, if the IPv6 address is removed manually or expires, and the carrier restored - for instance, plugging in the ethernet cable - then the IPv6 address is not restored.

This is especially a problem if the IPv6 address is the only address on a machine, in which case, remote access will be lost, and manual intervention will be required.

I assume that this is an oversight in the new systemd-networkd DHCPv6?

**Comment by teg** [comment]
Yup, this is definitely a bug. @pfl any chance you could take a look?

**Comment by pfl** [comment]
Yep, it's a bug. I'll take a look.
