### ISSUE TITLE
ubuntu1604 reboot.target: Job reboot.target/start timed out

### ISSUE THREAD

**Issue by yshchm** [systemd/systemd#9632]
**systemd version the issue has been seen with**
> systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

**Used distribution**
 > Ubuntu 16.04.4 LTS

**Expected behaviour you didn't see**
 > reboot: Restarting system

**Unexpected behaviour you saw**
 >   **reboot has a probability hang 30min and print following on the console ** 
      [ TIME ] Timed out starting Reboot
      [ !!  ] Forcibly rebooting as result of failure.
      [ 1951.311897] systemd-shutdown[1]: Failed to finalize  DM devices, ignoring
      [ 1952.114204] reboot: Restarting system

**Steps to reproduce the problem**

1 /proc/cmdline
  BOOT_IMAGE=/vmlinuz-4.4.116 root=/dev/mapper/ubuntu--vg-root ro systemd.log_level=debug console=tty0 console=ttyS2,38400n8 net.ifnames=0 biosdevname=0

2 journal for reboot timeout
[ubuntu1604_debug_reboot_stuck_201807171739.txt](https://github.com/systemd/systemd/files/2204057/ubuntu1604_debug_reboot_stuck_201807171739.txt)

3 The output of a systemd dump
[systemd-analyze_dump.txt](https://github.com/systemd/systemd/files/2204079/systemd-analyze_dump.txt)

4  I found there is only "Stopping /etc/rc.local  Compatibility", there isn't "Stopped /etc/rc.local  Compatibility";  following is my /etc/rc.local
[rc.local.txt](https://github.com/systemd/systemd/files/2204093/rc.local.txt)

**Comment by poettering** [comment]
Sorry, but we only track issues in the two most recent upstream releases here, i.e. 238 and 239 currently.

For anything older please contact your downstream distribution, they will help you.

Thank you for understanding
