### ISSUE TITLE
Systemctl --all includes non-installed services

### ISSUE THREAD

**Issue by fabienduhamel** [systemd/systemd#9637]
Hi.

I have a question about how `systemctl --all` works.
Generally, services can specify `After=some.service` to start after these services. A service I installed (Grafana Server) describes it below:

```
# grafana-server.service
[Unit]
Description=Grafana instance
Documentation=http://docs.grafana.org
Wants=network-online.target
After=network-online.target
After=postgresql.service mariadb.service mysql.service

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/sbin/grafana-server                                                  \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}


LimitNOFILE=10000
TimeoutStopSec=20
UMask=0027

[Install]
WantedBy=multi-user.target
```

Postgre, MariaDB and MySQL are not installed on my machine. Although Grafana could run without these services, the command `systemctl --all | grep mariadb.service` shows:

```
* mariadb.service     not-found inactive dead      mariadb.service
```

When I comment `After=postgresql.service mariadb.service mysql.service`, then `systemctl daemon-reload`, `systemctl --all | grep mariadb.service` does not show any output anymore.

I'm currently creating alerts based on Prometheus, which uses `systemctl --all` to notify a non-running service. The problem is: why does `systemctl --all` display non-installed services?

Is this behaviour correct?
Is there any other command available to exclude non-installed services?

**Comment by saleemrashid** [comment]
Does adding `--state=loaded` help? You can find all the possible values with `systemctl --state=help`.

**Comment by fabienduhamel** [comment]
Exactly what I need. Thank you for the answer.
