### ISSUE TITLE
kernel 4.16 and later require a udev rule for host-managed SMR disks

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#9639]
I'm forwarding a bug report from Fedora bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1584298:

Jeff Moyer 2018-05-30 12:16:23 EDT

Description of problem:
As of kernel version 4.16, host-managed Shingled Magnetic Recording (SMR) disks work best with the deadline or mq-deadline I/O schedulers.  Other schedulers will likely result in I/O errors due to out-of-order writes within a zone.

The block layer maintainer has indicated that the issue should be addressed via udev rules, not in the kernel.  It is expected that this limitation will be lifted in some future version of the kernel, but it's not know which.

See this thread for more details:
  https://marc.info/?t=152728308600002&r=1&w=2

A proposed rule would look something like the following:

ACTION=="add|change", KERNEL=="sd[a-z]",
ATTRS{queue/zoned}=="host-managed", ATTR{queue/scheduler}="deadline"

I'm not sure that action line is 100% correct.  We want to match all scsi disks, and I'm not sure if that rule would include, for example, sdaa.

We probably also need to clone this bug for all releases that include 4.16 kernel (at least f28 for sure).

**Comment by poettering** [comment]
Hmpf. as usual: udev is not supposed to be something where we just get data from the kernel and write it back to the kernel. They can do that much nicer in the kernel itself. Maybe it might be OK to pass something like this to userspace if userspace could and would actually enhance it in some way with data or logic only userspace posses or so (for example hwdb data, or so). However, in a case where we do no such thing and just stupidly echo a fixed value back into the kernel when we see some other value passed to use from the kernel, then udev is *not* it. We have refused such patches in the past, and I think we should do this again.

I mean, old userspace is not going to be updated with this anyway, so doing this in an udev rule is not really fixing much anyway. If kernel folks care about compat with old userspace (and to my knowledge they do, it's kinda Linus' mantra, no?), then they should just solve this internally.

**Comment by poettering** [comment]
Also, udev is not a dumping ground where it is already clear now that it has no future. We only really add new stuff if it's likely it's going to stay around.

If they want this stuff, then they should carry it, i.e. I am very sure this should be reassigned to the kernel RPM in fedora, and they can carry the udev rule for it, it really doesn't have to be systemd, and definitely not systemd upstream. The burden should be on the kernel folks to deal with this, and remove it when they fixed their stuff...

**Comment by keszybz** [comment]
True, the kernel package seems like a better place for this. Let's close this one.
