### ISSUE TITLE
`busctl call`-ing methods that are marked NO_REPLY

### ISSUE THREAD

**Issue by hal0** [systemd/systemd#9651]
Is there any reason `busctl call ...`-ing methods marked as `NO_REPLY` causes `busctl` to hang instead of returning immediately or after a timeout?

**Comment by poettering** [comment]
I figure you mean methods marked with the `org.freedesktop.DBus.Method.NoReply` annotation? Or what are you saying?

Which service is this?

busctl doesn't introspect methods before issuing method calls, hence it doesn't know about the annotation. If you are calling a function like that use `--expect-reply=no` to tell busctl not to wait for a reply.

busctl should time out any method call after 25s. If that doesn't work, then that'd be a bug.

**Comment by hal0** [comment]
Completely missed that flag. That makes sense. Thank you!
