### ISSUE TITLE
systemd not setting HOME environment variable for a dynamic user

### ISSUE THREAD

**Issue by flixman** [systemd/systemd#9652]
**systemd version the issue has been seen with**
> 238

**Used distribution**
 > Debian testing

**Expected behaviour you didn't see**
 > HOME variable is set by systemd for the invoked process.

**Unexpected behaviour you saw**
 > HOME is not set, when the unit file sets the user to be dynamic.

**Steps to reproduce the problem**
1. Create a unit file with the following contents:

   User=dynuser
   DynamicUser=true
   RuntimeDirectory=test
   LogsDirectory=test
   StateDirectory=test
   ProtectSystem=strict
   ProtectKernelTunables=true
   ProtectControlGroups=true

2. Start the service and check the environment of the main process (cat /proc/\<main proc. pid\>/environ). HOME is not set.

**Business case**
I am using this service file to run a backup service that wakes up, sends some files via SSH, and dies. Therefore, I need this service to have a HOME folder where I can store the .ssh folder, with SSH keys and so. I have tried setting the HOME env variable by an Environment directive (pointing to the state directory) on the service file, but has not worked.

**Comment by poettering** [comment]
Adding `Environment=HOME=%S/test`  should work, at least on current versions...

I just tried this command line here:

```c
systemd-run -p DynamicUser=1 -p StateDirectory=xyz -p Environment=HOME=/var/lib/xyz -p WorkingDirectory=/var/lib/xyz -t /bin/sh
```

And it worked fine. Doesn't it work for you?

**Comment by flixman** [comment]
You are right, and this works. By running your command I am getting a shell with a proper HOME being set, and I see now that the problem really is that, when running any ssh command, I get the following message:

    ssh testmachine
    No user exists for uid 65428

I will try to find out this one. Thank you!

**Comment by poettering** [comment]
> ssh testmachine No user exists for uid 65428

You are invoking that from a DynamicUser=1 user? if you see that error it appears that the nss-systemd NSS provider is not properly installed and listed in /etc/nsswitch.conf. 

Does "getent passwd `id -u`" work?

**Comment by flixman** [comment]
Nope :( does not work

**Comment by poettering** [comment]
Then, make sure that nss-systemd is properly listed in /etc/nsswitch.conf. See the man page:

https://www.freedesktop.org/software/systemd/man/nss-systemd.html

Quite frankly, Debian really should do that by default anyway, it's really a requirement for dynamic users to work.

**Comment by mbiebl** [comment]
@flixman Is libnss-systemd installed? It's currently a Recommends of systemd, i.e. installed by default unless you explicitly have disabled the installation of Recommends

**Comment by poettering** [comment]
hmm no idea about the ssh thing, but this appears outside of the scope of systemd now...

did you reopen this issue by accident? anything left to discuss here inside the systemd scope in this bug?

**Comment by flixman** [comment]
yeah: I reopened it because, although closed, we were still discussing. I guess this is finished on the systemd side, indeed. Thank you for your help :) !

**Comment by simonello** [comment]
> Adding `Environment=HOME=%S/test` should work, at least on current versions...
> 
> I just tried this command line here:
> 
> ```c
> systemd-run -p DynamicUser=1 -p StateDirectory=xyz -p Environment=HOME=/var/lib/xyz -p WorkingDirectory=/var/lib/xyz -t /bin/sh
> ```
> 
> And it worked fine. Doesn't it work for you?

where would I add this to?  Which file?
