### ISSUE TITLE
RFE: Save service start/running time info from the initrd for systemd-analyze

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#9662]
Currently even if the initrd is using systemtd, as it is e.g on Fedora, the output of systemd-analyze plot will only contain a single long bar for the initrd.

It would be nice if on pivot to the real root systemd could save the statistics from the initrd, so that both initrd and normal services are individually shown  in systemd-analyze plot output.

**Comment by yuwata** [comment]
@jwrdegoede Could you test #9687?
