### ISSUE TITLE
udev shows too unspecific error message

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#9678]
**systemd version the issue has been seen with**

Originally filed against udev 175 but the code is still the same in 239

**Used distribution**
 
Debian sid
Downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670843

The following is copied verbatim from this bug report:

on system boot, I occasionally get the following error message

udevd[359]: missing file parameter for attr

Unfortunately, I have no idea which of my udev rules files is causing the
problem, and the error message is entirely pointless without that information.
It should at least contain the filename and line number.

**Comment by yuwata** [comment]
I hope 4cade7a15b9af5b628c2ae9d0f3e9cefbe4ef4bf improves the log. Let's close this.
