### ISSUE TITLE
network interface  naming broken

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#9688]
**systemd version the issue has been seen with**

v239

**Used distribution**

Debian sid
Originally filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904198

This is copied verbatim from the downstream bug report:
"
After upgrading from 238-5 to 239-1 or higher my network setup breaks.

Basically all interfaces which do NOT have a mac-address (like tun devices, sit-tunnels, etc) are now matched by the first .link file which matches on the mac-address and udev tries to rename them all to this name (in this case netint)

The log shows for all of them:

systemd-networkd[768]: rename6: Interface name change detected, rename6 has been renamed to sit0.
systemd-networkd[768]: sit0: Interface name change detected, sit0 has been renamed to rename6.

As netint is already in use they all end as renameX...

For devices which have a mac-address all works fine (like hardware ethernet devices, tap devices etc).

Downgrading to udev 239-5 und libudev1 239-5 fixes the problem.

A setup like the following one should be able to reproduce this problem:

10-netint.link:
```
[Match]
MACAddress=00:01:2e:77:a5:45

[Link]
Name=netint
WakeOnLan=off
```

mytun.netdev:
```
[NetDev]
Name=mytun
Kind=tun

[Tun]
```

You then should see log entries like
systemd-networkd[768]: rename6: Interface name change detected, rename6 has been renamed to mytun.
systemd-networkd[768]: mytun: Interface name change detected, sit0 has been renamed to rename6.

and further lines like

kernel: rename6: renamed from mytun
systemd-udevd[280]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
systemd-udevd[280]: Could not set WakeOnLan of mytun to off: Operation not supported

There will be now device mytun but instead be a renameX.
"

I could reproduce the problem by creating such a link file and creating a tun device using ```ip tuntap add tun0 mode tun```.

**Comment by arvidjaar** [comment]
Should be fixed in 25ea58d37385af27301b7ad25e985eb15f421614

**Comment by yuwata** [comment]
Yeah, it is already fixed.

**Comment by mbiebl** [comment]
Thanks @yuwata  and @arvidjaar
