### ISSUE TITLE
systemd-networkd-wait-online should have an option to wait until any 1 of multiple interfaces are online.

### ISSUE THREAD

**Issue by mshunshin** [systemd/systemd#9714]
systemd-networkd-wait-online.service has an option to wait until 1 or more specified interfaces are configured, or by default waits until all interfaces it manages are configured.

It does not have an option to wait until any one of all (or specified) interfaces are configured.

This would be useful for servers that have multiple ports, all are left to auto-configure, but only one will ever be plugged in.

man page is here showing this limitation:
https://www.freedesktop.org/software/systemd/man/systemd-networkd-wait-online.service.html

Perhaps add an option:
--wait-for-first-interface

**Comment by conqp** [comment]
I second this feature request and want to point out, that the documentation therefor is misleading:

https://www.freedesktop.org/software/systemd/man/systemd-networkd-wait-online.service.html
> By default, it will wait for all links it is aware of and which are managed by systemd-networkd.service(8) to be fully configured or failed, and for at least one link to gain a carrier.

This could be read as if systemd-network-wait-online succeeds per default if "at least one link" gained a carrier, which is **not** the case:

```$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 00:30:18:cc:4a:50 brd ff:ff:ff:ff:ff:ff
3: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:30:18:cc:4a:51 brd ff:ff:ff:ff:ff:ff
    inet aaa.bbb.ccc.ddd/24 brd aaa.bbb.ccc.255 scope global dynamic enp4s0
       valid_lft 3574sec preferred_lft 3574sec
    inet6 fe80::230:18ff:fecc:4a51/64 scope link 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none 
    inet eee.fff.ggg.hhh/16 brd eee.fff.255.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::dfbf:ba42:ef26:7f20/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
$ /usr/lib/systemd/systemd-networkd-wait-online
ignoring: tun0
Event loop failed: Connection timed out
/usr/lib/systemd/systemd-networkd-wait-online -i enp4s0
ignoring: lo
ignoring: tun0
ignoring: enp3s0
```

**Comment by yuwata** [comment]
I've created PR #12160 for this RFE. If possible, please test the PR. Thank you.
