### ISSUE TITLE
journalctl SYSLOG_FACILITY=kern|kernel does not work, and similar

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#9716]
One can query syslog things, but one must use the numeric syslog facility numbers.

it would be nice if one could specify SYSLOG_FACILITY=kern or kernel, by name, rather than by numbers.

similarly for other syslog facilities, e.g. auth, daemon, cron etc.

I guess this can be implemented in the journalctl client to translate those words into integers.

**Comment by rfc1036** [comment]
Facilities are still very useful in some cases when multiple units log stuff about the same event which should be read together. An example is mail.* receiving entries from Postfix, various milters and Dovecot for each delivered message.
