### ISSUE TITLE
CI fails with boot-and-services FAIL stderr: Failed to dump process list for 'systemd-nspawn@c1.service', ignoring: Unit systemd-nspawn@c1.service not loaded.

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#9723]
Lately, the Ubuntu CI fails quite often in the boot-and-services autopkgtest with
```
FAIL stderr: Failed to dump process list for 'systemd-nspawn@c1.service', ignoring: Unit systemd-nspawn@c1.service not loaded.
```
Recent example:
https://github.com/systemd/systemd/pull/9720#issuecomment-408040339

**Comment by evverx** [comment]
It's a known issue: https://github.com/systemd/systemd/issues/8880. I'm closing it as a duplicate.
