### ISSUE TITLE
doc/systemd.syntax: definition and possible values of boolean data type

### ISSUE THREAD

**Issue by LionNatsu** [systemd/systemd#9735]
**Is your feature request related to a problem? Please describe.**
I was confused about what values systemd can accept for a boolean field in configuration files.
In the documentation of units and components, I found yes, no, true, false, y, n, on, off ... I was not sure whether they share one parser or use different parsers which are not compatible with each other.

Fortunately, they share one parser.
https://github.com/systemd/systemd/blob/4d7293f07c5059f4a0f458b62669763facc39f9e/src/basic/parse-util.c#L21-L30

Manual of "systemd.syntax"(https://www.freedesktop.org/software/systemd/man/systemd.syntax.html), I can only find the description of the basic `key=value` format, and how to deal with long lines. BTW, can it be `key = value`?

**Describe the solution you'd like**
I think we should add these possible values into the documentation of systemd.syntax .
Currently, `1/0`, `yes/no`, `y/n`, `true/false`, `t/f`, `on/off` are supported for boolean fields.

**Describe alternatives you've considered**
Enforcing configuration files all to use "true/false"? No, this idea looks bad.

**Comment by yuwata** [comment]
Currently, the explanation about boolean value is in systemd.unit. Yeah, I think the explanation should also in systemd.syntax.
