### ISSUE TITLE
systemd-nspawn should refuse running off the host's root fs

### ISSUE THREAD

**Issue by mrp1234567** [systemd/systemd#9739]
**systemd version the issue has been seen with**
> ...systemd 237

**Used distribution**
 > …Cross compiled systemd for Yocto Embeeded Linux

**Expected behaviour you didn't see**
 > … systemd-nspawn should be able to load multiple containers from the same rootfs directory
**Unexpected behaviour you saw**
 > … systemd-nspawn throws the error "Directory Tree /x/y/z... is Currently Busy"
**Steps to reproduce the problem**
Download a minimal rootfs directory tree
Create a container using the command "systemd-nspawn -b -D /pathto rootfs directory/"
First container starts 
Start another container using the same command, systemd-nspawn fails with error "Directory Tree /x/y/z... is Currently Busy"

**Comment by lucaswerkmeister** [comment]
I don’t think this is something `systemd-nspawn` should support – having more than one system run on the same directory tree is probably asking for trouble.

However, you can run more than one instance of the same image with the `--ephemeral` switch, which creates  temporary copy of the image and runs that – then there’s no risk of a conflict. You can even start ephemeral copies of an image that already has a non-ephemeral container running on it.

**Comment by poettering** [comment]
@lucaswerkmeister is right, it's highly problematic running multiple systems simultaneously off the same image if that image is not read-only for all of them, as linux images are generally not built to allow such a simultaneous use and the systems will interfere with each other's data.

And yes, the fact that nspawn currently allows such a thing for the host image is problematic, and we should remove that I figure.

And yes, `--ephemeral` is the way to go, but it's slow if the underlying fs doesn't support reflinks...

I will now rename this item suggesting we disallow running nspawn off the host image even once

**Comment by patlollamahipal** [comment]
@lucaswerkmeister @poettering Thanks for the inputs

btw I am not using the host root directory for containers, i have separate rootfs from which I am trying to create two containers.

**Comment by Bischoff** [comment]
New title of this issue does not reflect the issue.
