### ISSUE TITLE
systemd inside docker for mac, startup gets stuck trying to bring up dev-sda1.device, help with investigation

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#9740]
## systemd version the issue has been seen with
systemd 232
(Also reproduced on systemd 239.)

## Used distribution
Debian Stretch (inside the docker container)
(Also reproduced on Debian unstable.)

## Steps to reproduce the problem
This seems to happen inside a container in [Docker for Mac](https://www.docker.com/docker-mac). The bug itself is not in systemd itself, but some help debugging this issue would be appreciated here, in particular understanding why this is timing out and whether there is something that could be done in udev to help alleviate the issue.

In order to reproduce it, build a container based on Debian Stretch that boots systemd when executed, with a Dockerfile like this:

```dockerfile
FROM debian:stretch
RUN apt-get update && apt-get -y install systemd systemd-sysv udev bash
ENTRYPOINT [ "/sbin/init", "--log-target=console" ]
ENV container docker
STOPSIGNAL SIGRTMIN+3
```

(Also reproduced when using `FROM debian:unstable`, which pulls in systemd 239.)

Then build it with this command (on the directory where the Dockerfile is):

```shell
$ docker build -t test_systemd:v1 .
```

Then start the container, using:

```shell
$ docker run --rm -t --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN --security-opt seccomp:unconfined --privileged --name test_systemd test_systemd:v1
```

On a separate shell, attach to the container, get a shell in it, using this command:

```shell
$ docker exec -it test_systemd /bin/bash
```

Then check that dev-sda1.device is activating:

```
root@9801ec1f2fad:/# systemctl status dev-sda1.device
● dev-sda1.device - /dev/sda1
   Loaded: loaded
   Active: activating (tentative) since Sat 2018-07-28 02:55:49 UTC; 46s ago
   Device: /sys/devices/pci0000:00/0000:00:02.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

It gets stuck at this point, and startup completes with timeout after 90s:

```
dev-sda1.device: Job dev-sda1.device/start timed out.
dev-sda1.device: Job dev-sda1.device/start failed with result 'timeout'.
Startup finished in 1min 30.093s.
```

This device seems to be starting due to the bind mounts of files in /etc, such as resolv.conf:

```
root@9801ec1f2fad:/# grep /dev/sda1 /proc/self/mountinfo 
477 424 8:1 /docker/containers/9801ec1f2fad3d520f4079f429c8ca189a9af32bb17c8acb25bf9e173248e2a5/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/sda1 rw,stripe=1024,data=ordered
478 424 8:1 /docker/containers/9801ec1f2fad3d520f4079f429c8ca189a9af32bb17c8acb25bf9e173248e2a5/hostname /etc/hostname rw,relatime - ext4 /dev/sda1 rw,stripe=1024,data=ordered
479 424 8:1 /docker/containers/9801ec1f2fad3d520f4079f429c8ca189a9af32bb17c8acb25bf9e173248e2a5/hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,stripe=1024,data=ordered
```

Output of `df` shows the device too, same as root device:

```
root@9801ec1f2fad:/# df / /dev/sda1 
Filesystem     1K-blocks    Used Available Use% Mounted on
overlay         61252420 1691032  56420220   3% /
/dev/sda1       61252420 1691032  56420220   3% /etc/hosts
```

Journal logs for `/dev/sda1` show:

```
root@9801ec1f2fad:/# journalctl /dev/sda1
-- Logs begin at Sat 2018-07-28 02:55:49 UTC, end at Sat 2018-07-28 02:55:52 UTC. --
Jul 28 02:55:49 9801ec1f2fad kernel: pci 0000:00:02.0: [8086:2821] type 00 class 0x010601
Jul 28 02:55:49 9801ec1f2fad kernel: pci 0000:00:02.0: reg 0x24: [mem 0xc0002000-0xc00023ff]
Jul 28 02:55:49 9801ec1f2fad kernel: pci 0000:00:02.0: reg 0x30: [mem 0x00000000-0x000007ff pref]
Jul 28 02:55:49 9801ec1f2fad kernel: pci 0000:00:02.0: BAR 6: assigned [mem 0xc0003000-0xc00037ff pref]
Jul 28 02:55:49 9801ec1f2fad kernel: ahci 0000:00:02.0: version 3.0
Jul 28 02:55:49 9801ec1f2fad kernel: ahci 0000:00:02.0: can't derive routing for PCI INT A
Jul 28 02:55:49 9801ec1f2fad kernel: ahci 0000:00:02.0: PCI INT A: no GSI
Jul 28 02:55:49 9801ec1f2fad kernel: ahci 0000:00:02.0: SSS flag set, parallel bus scan disabled
Jul 28 02:55:49 9801ec1f2fad kernel: ahci 0000:00:02.0: AHCI 0001.0300 32 slots 6 ports 6 Gbps 0x1 impl SATA mode
Jul 28 02:55:49 9801ec1f2fad kernel: ahci 0000:00:02.0: flags: 64bit ncq sntf ilck stag pm led clo pio slum part sxs apst 
Jul 28 02:55:49 9801ec1f2fad kernel: scsi host0: ahci
Jul 28 02:55:49 9801ec1f2fad kernel: scsi 0:0:0:0: Direct-Access     ATA      BHYVE SATA DISK  001  PQ: 0 ANSI: 5
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: Attached scsi generic sg0 type 0
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: [sda] 124999680 512-byte logical blocks: (64.0 GB/59.6 GiB)
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: [sda] 4194304-byte physical blocks
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: [sda] Write Protect is off
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
Jul 28 02:55:49 9801ec1f2fad kernel: sd 0:0:0:0: [sda] Attached SCSI disk
```

There are also some logs for ext4 there:

```
root@9801ec1f2fad:/# journalctl | grep EXT4
Jul 28 02:55:49 9801ec1f2fad kernel: EXT4-fs (sda1): couldn't mount as ext3 due to feature incompatibilities
Jul 28 02:55:49 9801ec1f2fad kernel: EXT4-fs (sda1): couldn't mount as ext2 due to feature incompatibilities
Jul 28 02:55:49 9801ec1f2fad kernel: EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
```

And udevadm info for the device and the partition:

```
root@9801ec1f2fad:/# udevadm info /dev/sda
P: /devices/pci0000:00/0000:00:02.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
N: sda
S: disk/by-id/ata-BHYVE_SATA_DISK_BHYVE-3049-FEB8-27ED
S: disk/by-path/pci-0000:00:02.0-ata-1
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:02.0-ata-1 /dev/disk/by-id/ata-BHYVE_SATA_DISK_BHYVE-3049-FEB8-27ED
E: DEVNAME=/dev/sda
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
E: DEVTYPE=disk
E: ID_ATA=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_BUS=ata
E: ID_MODEL=BHYVE_SATA_DISK
E: ID_MODEL_ENC=BHYVE\x20SATA\x20DISK\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_TABLE_UUID=35e13f4f
E: ID_PATH=pci-0000:00:02.0-ata-1
E: ID_PATH_TAG=pci-0000_00_02_0-ata-1
E: ID_REVISION=001
E: ID_SERIAL=BHYVE_SATA_DISK_BHYVE-3049-FEB8-27ED
E: ID_SERIAL_SHORT=BHYVE-3049-FEB8-27ED
E: ID_TYPE=disk
E: MAJOR=8
E: MINOR=0
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=8194208919

root@9801ec1f2fad:/# udevadm info /dev/sda1
P: /devices/pci0000:00/0000:00:02.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
N: sda1
S: disk/by-id/ata-BHYVE_SATA_DISK_BHYVE-3049-FEB8-27ED-part1
S: disk/by-partuuid/35e13f4f-01
S: disk/by-path/pci-0000:00:02.0-ata-1-part1
S: disk/by-uuid/42a6a870-19f3-4b98-8d34-da49f3d84f64
E: DEVLINKS=/dev/disk/by-id/ata-BHYVE_SATA_DISK_BHYVE-3049-FEB8-27ED-part1 /dev/disk/by-uuid/42a6a870-19f3-4b98-8d34-da49f3d84f64 /dev/disk/by-partuuid/35e13f4f-01 /dev/disk/by-path/pci-0000:00:02.0-ata-1-part1
E: DEVNAME=/dev/sda1
E: DEVPATH=/devices/pci0000:00/0000:00:02.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
E: DEVTYPE=partition
E: ID_ATA=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_BUS=ata
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_FS_UUID=42a6a870-19f3-4b98-8d34-da49f3d84f64
E: ID_FS_UUID_ENC=42a6a870-19f3-4b98-8d34-da49f3d84f64
E: ID_FS_VERSION=1.0
E: ID_MODEL=BHYVE_SATA_DISK
E: ID_MODEL_ENC=BHYVE\x20SATA\x20DISK\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_PART_ENTRY_DISK=8:0
E: ID_PART_ENTRY_FLAGS=0x80
E: ID_PART_ENTRY_NUMBER=1
E: ID_PART_ENTRY_OFFSET=8192
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_SIZE=124991488
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_UUID=35e13f4f-01
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_TABLE_UUID=35e13f4f
E: ID_PATH=pci-0000:00:02.0-ata-1
E: ID_PATH_TAG=pci-0000_00_02_0-ata-1
E: ID_REVISION=001
E: ID_SERIAL=BHYVE_SATA_DISK_BHYVE-3049-FEB8-27ED
E: ID_SERIAL_SHORT=BHYVE-3049-FEB8-27ED
E: ID_TYPE=disk
E: MAJOR=8
E: MINOR=1
E: PARTN=1
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=8194212970
```

BTW, [bhyve](https://en.wikipedia.org/wiki/Bhyve) (which appears in the device serial) seems to be the virtualization technology used by Docker for Mac under the hood.

Running `systemctl start dev-sda1.device` reproduces the problem, it gets stuck.

## Workaround

This helps get the system to complete the boot quicker:

```
root@9801ec1f2fad:/# systemctl mask dev-sda1.device
Created symlink /etc/systemd/system/dev-sda1.device → /dev/null.
```

## Questions

* Why does `systemctl start dev-sda1.device` hang? What is systemd trying to do while starting that unit that is causing it to get stuck?

* Is udev involved at all in this process? Or will devices systemd discovers from parsing mountinfo (assuming this is how it's being started) bypass udev logic?
  - Assuming udev is involved, would it be possible to block this device through udev? And, if so, would it be worth considering adding a general rule for "bhyve"?

* The journal doesn't seem to have any messages that explain the behavior... Do we need more logging here?

* Is masking the unit an appropriate approach here? Or are there better workarounds to recommend here?

As mentioned, any help troubleshooting this would be appreciated. I'm happy to post more command output (since I expect not many would care about reproducing this particular environment.)

/cc @BenTheElder who reported this issue to me.

**Comment by zdzichu** [comment]
You must have /dev/sda1 embedded in some configuration file. `/etc/fstab`? `/etc/crypttab`? Maybe somewhere in kernel command line?

**Comment by BenTheElder** [comment]
`/etc/fstab` has no entries and `/etc/crypttab` doesn't exist. `/proc/cmdline` contains:

`BOOT_IMAGE=/boot/kernel console=ttyS0 page_poison=1 vsyscall=emulate panic=1 root=/dev/sr0 text`

There are entries in `/etc/mtab` for:
```
/dev/sda1 /etc/resolv.conf ext4 rw,relatime,stripe=1024,data=ordered 0 0
/dev/sda1 /etc/hostname ext4 rw,relatime,stripe=1024,data=ordered 0 0
/dev/sda1 /etc/hosts ext4 rw,relatime,stripe=1024,data=ordered 0 0
```

FWIW, I wouldn't exactly expect this to be a supported use case, but short of this issue `systemd` handles it pretty easily :-)

---
For anyone else encountering this, the full workaround I'm currently using is:
```
RUN systemctl mask dev-sda1.device dev-sr0.device
``` 
The xhyve emulated cd-rom drive otherwise gives a similar issue occasionally.

---

Other non-functional workarounds I tried include:

- Add a `99-zz-my.rules` file with a rule matching on the device model. With `udevadm` I could see that the extra env key I added was applied to `/dev/sda1`, but setting `TAG-="systemd"`, `ENV{SYSTEMD_READY}="0"` etc. 
  - I couldn't find a working field + value to prevent the device unit. Perhaps I missed something.

- Prepending a rule to the `systemd.rules` to skip them:
`RUN sed -i '1s/^/SUBSYSTEM=="block", ENV{ID_MODEL}=="BHYVE_SATA_DISK", ENV{ZZ}="skipped" GOTO="systemd_end"\n/' /lib/udev/rules.d/99-systemd.rules && cat /lib/udev/rules.d/99-systemd.rules`
  - like the `TAG-="systemd"` rule this did remove the systemd tag in udev, but not the device unit.

- removing all udev rules ¯\\\_(ツ)\_/¯
`RUN rm -rf /etc/udev/rules.d/`
  - this clearly left nearly all fields unset in `udevadm`, but did not prevent the device unit.

----

I'm fairly happy with the masks as a workaround, but I'd appreciate any suggestions here. 

In particular I'd love to get a better understanding of why these device units are created. I've pored over all of the docs I can find, and my reading of [systemd.device](https://www.freedesktop.org/software/systemd/man/systemd.device.html) suggested that removing the systemd tag in the udev rules might prevent these device units from being created, but I haven't had any success there.

I'm also curious as to what the .device start job actually does, any pointers there would be appreciated.

**Comment by filbranden** [comment]
So I'm guessing these devices will show up from the logic in [`mount_setup_existing_unit()`](https://github.com/systemd/systemd/blob/v239/src/core/mount.c#L1454) which parses `/proc/self/mountinfo` and creates `.mount` units for the mounts that appear that.

That code is probably trying to create the units for the three bind mounts, then looking at the device they're on (`/dev/sda1`) and adding an implicit dependency to `dev-sda1.device`. I mean, I didn't check this directly, but from my understanding of how this works, that's what I'd expect would happen.

I'm not really sure which code is behind device startup that would make `systemctl start dev-sda1.device` hang... Any ideas?

**Comment by poettering** [comment]
please provide debug logs.

Do note that systemd skips /etc/fstab handling in containers. For that to work it checks whether it is running in a container, which is done by looking for the $container env var being set. Did you check if that works?

**Comment by filbranden** [comment]
> please provide debug logs.

Debug logs here in this gist: https://gist.github.com/filbranden/2a0e1fe136324c9c28789965fc17ef81

I used this Dockerfile:

```dockerfile
FROM debian:unstable
RUN apt-get update && apt-get -y install systemd systemd-sysv udev bash
ENTRYPOINT [ "/sbin/init", "--log-target=console", "--log-level=debug" ]
ENV container docker
STOPSIGNAL SIGRTMIN+3
```

In other words, the one change here was to add `"--log-level=debug"` as an argument to `/sbin/init` to enable debug logging. If you needed something else, please let me know what else...

I also started from `debian:unstable` in order to get systemd v239.

> Do note that systemd skips /etc/fstab handling in containers.

fstab is empty... I was referring to parsing `/proc/self/mountinfo` to look at dynamic mounts instead. (Not sure if that's what you were referring to... Or if you were talking about `systemd-fstab-generator`, which I would agree is definitely not involved here.)

> For that to work it checks whether it is running in a container, which is done by looking for the $container env var being set. Did you check if that works?

Yes. You can see in the Dockerfile we're passing `ENV container docker`.

I also confirmed that running `systemd-detect-virt` says `docker`.

When running with this image (probably because of systemd v239 in Debian Unstable), I didn't get startup to hang, presumably because whatever is bringing `/dev/sda1` is doing so after startup is complete. With the older Debian, it seems we hit that more often. In any case, `systemctl status dev-sda1.device` shows it's trying to start. In my gist I have a collection of that command 6 minutes into the container, shows it's still trying to start.

Thanks!
Filipe

**Comment by poettering** [comment]
@filbranden systemd is set up by default to bypass device management if /sys is read-only. This is documented in https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/. My educated guess is that docker folks don't care for that and make /sys writable to container payloads?

If you make it read-only, do things work then?

**Comment by filbranden** [comment]
So you're correct in that this container has `/sys` mounted read-write, but I haven't traced back to exactly why it is getting mounted read-write.

A simple `docker run -it debian:unstable /bin/bash` gets a container with `/sys` mounted read-only.

Ok, so we can start looking from there and try to understand what is making `/sys` read-write and try to fix that instead.

I think it is possibly because we're starting it with `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` which bind mounts `/sys/fs/cgroup`, so perhaps it's making `/sys` writable to ensure it can create that subdirectory (?).

In any case... Can you explain why the `.device` unit is getting stuck starting in the container? What code actually runs for `systemctl start dev-sda1.device`? What can we look into to see why it's failing to start?

Thanks!
Filipe

**Comment by filbranden** [comment]
Small update: it seems `--privileged` is what's causing `/sys` to be mounted read-write...

**Comment by filbranden** [comment]
And on some more testing...

Using `-v /sys:/sys:ro --privileged` does not work to mount /sys read-only.

Using `--privileged -v /sys:/sys:ro` works to mount /sys read-only.

We haven't yet looked into whether mounting /sys read-only will have other impacts we didn't anticipate, but I think that's a possible fix.

So: you're saying `/sys` in containers should be *always* read-only, even if the container is supposed to be "privileged"? Are there any valid use cases where the container *should* (or might want to) have access to a writable `/sys`?

**Comment by poettering** [comment]
Yes, systemd's current protocol is that if /sys is read-only then device management is turned off. If it's writable then it assumes that it shall manage devices, i.e. udev starts, .device nodes appear and deps on them. These semantics have been documented since a long time.

If docker would just follow this protocol, things would just work... It's a pity they don't, as the semantics at least to me are pretty simple and obvious. 

In general, the idea that containers can modify host settings, though writable /sys and similar is just horrible if you ask me. So, I'd discount the whole concept quite frankly: containers should not get device access, and hence never writable access to /sys or suchlike...

If docker wanted they could even permit write access to /sys and still follow systemd's protocol: simply create bind mounts for all relevant subtrees of /sys, and make them writable, while making /sys itself read-only. In fact, nspawn does something like that: because we want to make certain aspects of /sys entirely invisible to containers we mount /sys as tmpfs, and then mount only the less security-relevant subtrees below it, but in our case of course only in read-only fashion.

**Comment by BenTheElder** [comment]
Thank you all. `docker run --privileged ...` makes some poorly documented changes to the mounts which happens to include rw `/sys`. Ensuring `/sys` is read-only leaves things working as intended, I apologize for missing the docs related to this earlier. 


I'd be curious to know what caused the device units to hang, but otherwise I think we should close this now. I apologize again, thank you very much for the quick and detailed responses.

**Comment by filbranden** [comment]
Just to close the loop on this one...

The device is pulled by `device_found_node()` which gets events from `/proc/self/mounts`, see [this comment](https://github.com/systemd/systemd/blob/v239/src/core/device.c#L1048) about putting the device in "tentative" state.

The device will then stay in "tentative" state until udev sends an event about finding the device, see [this comment](https://github.com/systemd/systemd/blob/v239/src/core/device.c#L646) for more details.

So even though udev is started inside the container and `/sys` is writable, it will not really send an event about this device. (Not 100% sure why.) But this should at least explain large part of what was happening here...

Read-only `/sys` is the proper solution here.

Cheers,
Filipe

**Comment by poettering** [comment]
> I'd be curious to know what caused the device units to hang, but otherwise I think we should close this now. I apologize again, thank you very much for the quick and detailed responses.

My educated guess, not knowing what docker precisely does: For device units to actually become "active" in systemd, udev needs to have probed them and marked them as good. To determine that access to the udev db is required, i.e. some files in /run/udev. Those aren't available in your container presumably, hence no device ever shows up as active. 

Anyway: don#t waste too much thoughts about all of this: managing devices from a container can only end up in failure. We do not support that. and it's going to break everywhere, as the kernel isn't ready for that, and neither is udev/systemd.

**Comment by kghost** [comment]
I don't think Read-only /sys is the proper solution, it is just another work-around or lazy solution.

As more and more features added to the sysfs, it will be a limitation to restrict read-only sys.

The proper solution should ignore those devices found in the `/proc/self/mounts` when in container environment.

@filbranden  please re-open the issue
