### ISSUE TITLE
Unable to bring up interface, udev renaming occurs after network managing tries to "up"

### ISSUE THREAD

**Issue by Siggemada** [systemd/systemd#9741]
Newly installed Ubuntu server 18.04.1
Removed netplan; apt-get install ifupdown

Interface is not supposed to have IP. Exact same config on Ubuntu 18.04 works.

/etc/network/interfaces:
auto enxe46f13f38973
allow-hotplug enxe46f13f38973
iface enxe46f13f3d4dd inet manual
pre-up ifconfig $IFACE up
post-down ifconfig $IFACE down

syslog:
Jul 28 09:53:17 host sh[656]: Unknown interface enxe46f13f38973
Jul 28 09:53:17 host kernel: [    4.311259] ax88179_178a 4-4:1.0 enxe46f13f38973: renamed from eth0
Jul 28 09:53:18 host systemd-networkd[602]: eth0: Interface name change detected, eth0 has been renamed to enxe46f13f38973.

Tried this workaround:
crontab -e
@reboot /sbin/ifconfig enxe46f13f38973 up

works intermittently, so no solution.

Tried: 
/etc/network/interfaces:
auto enxe46f13f38973
allow-hotplug enxe46f13f38973
iface enxe46f13f3d4dd inet static
pre-up ifconfig $IFACE up
post-down ifconfig $IFACE down

together with crontab seems to be working but not pretty.

**Comment by poettering** [comment]
/etc/network/interfaces is not read or processed by systemd. It's an ubuntu/debian thing. Please contact your downstream distro for help hence, given that both netplan and this file are purely ubuntu concepts.

Thank you for understanding
