### ISSUE TITLE
Incorrect description of the "enabled" state

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#975]
[`systemctl(1)`](http://www.freedesktop.org/software/systemd/man/systemctl.html#is-enabled%20NAME...) says:

> "enabled" - Enabled through a symlink in .wants directory (permanently or just in /run).

I have the unit file:

``` sh
$ systemctl cat hola.service
# /lib/systemd/system/hola.service
[Unit]
Description=Hola Service

[Service]
Type=oneshot
ExecStart=/bin/echo hola
RemainAfterExit=yes

[Install]
Alias=HOLA.service
```

``` sh
$ systemctl enable hola.service
Created symlink from /etc/systemd/system/HOLA.service to /lib/systemd/system/hola.service

$ systemctl is-enabled hola.service
enabled
```

The state is `enabled` but I don't have a symlink in `.wants` directory.

``` sh
$ systemctl list-dependencies --reverse hola.service
hola.service
```

```
$ systemd --version
systemd 219
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

**Comment by arvidjaar** [comment]
> "enabled" - Enabled through a symlink in .wants directory (permanently or just in /run).

Current upstream manual page says `This will create a number of symlinks as encoded in the [Install] sections of the unit files.` Yes, "enabled" is probably misleading but that is unlikely to change now.

> The state is enabled but I don't have a symlink in .wants directory.

Why do you expect them? You did not specify any WantedBy in your unit definition.

**Comment by evverx** [comment]
> Why do you expect them? 

I don't expect them.

**Comment by evverx** [comment]
> Current upstream manual page says This will create a number of symlinks as encoded in the [Install] sections of the unit files.

You quote [this](http://www.freedesktop.org/software/systemd/man/systemctl.html#enable%20NAME...) section.
I quote [this](http://www.freedesktop.org/software/systemd/man/systemctl.html#is-enabled%20NAME...) section.

**Comment by arvidjaar** [comment]
Right.

https://github.com/systemd/systemd/pull/980

**Comment by evverx** [comment]
@arvidjaar , thanks.
But:

``` sh
$ systemctl cat hola.service
# /lib/systemd/system/hola.service
[Unit]
Description=Hola Service

[Service]
Type=oneshot
ExecStart=/bin/echo hola
RemainAfterExit=yes
```

```
$ ln -s /lib/systemd/system/hola.service /etc/systemd/system/multi-user.target.wants/hola.service
$ systemctl daemon-reload
$ systemctl is-enabled hola
enabled
```

i.e. I don't have an `[Install]` section in the unit file. But I have a symlink in `.wants` directory.
