### ISSUE TITLE
Failed to create temporary file for coredump, read-only file system.

### ISSUE THREAD

**Issue by pauldotknopf** [systemd/systemd#9756]
**systemd version the issue has been seen with**

237

**Used distribution**

Yocto Sumo

**Expected behaviour you didn't see**

Create a coredump on segfault.

**Unexpected behaviour you saw**

```
ul 30 08:54:14 evo4k-e6872f kernel: ClearApp[803]: segfault at 0 ip 000000000042bcb0 sp 00007ffcd4915f18 error 6 in ClearApp[400000+868000]
Jul 30 08:54:14 evo4k-e6872f kernel[359]: ClearApp[803]: segfault at 0 ip 000000000042bcb0 sp 00007ffcd4915f18 error 6 in ClearApp[400000+868000]
Jul 30 08:54:14 evo4k-e6872f systemd[1]: Started Process Core Dump (PID 804/UID 0).
Jul 30 08:54:14 evo4k-e6872f systemd-coredump[805]: Failed to create temporary file for coredump /var/log/coredump/core.ClearApp.0.54a13c5624ad4ed6b3: Read-only file system
Jul 30 08:54:14 evo4k-e6872f systemd-coredump[805]: Process 803 (ClearApp) of user 0 dumped core.
Jul 30 08:54:14 evo4k-e6872f systemd[1]: clearapp.service: Main process exited, code=dumped, status=11/SEGV
Jul 30 08:54:14 evo4k-e6872f systemd[1]: clearapp.service: Failed with result 'core-dump'.
Jul 30 08:54:15 evo4k-e6872f systemd[1]: clearapp.service: Service hold-off time over, scheduling restart.
Jul 30 08:54:15 evo4k-e6872f systemd[1]: clearapp.service: Scheduled restart job, restart counter is at 5.
Jul 30 08:54:15 evo4k-e6872f systemd[1]: Stopped MedX ClearApp.
Jul 30 08:54:15 evo4k-e6872f systemd[1]: clearapp.service: Start request repeated too quickly.
Jul 30 08:54:15 evo4k-e6872f systemd[1]: clearapp.service: Failed with result 'core-dump'.
Jul 30 08:54:15 evo4k-e6872f systemd[1]: Failed to start MedX ClearApp.
```

**Steps to reproduce the problem**

My environment is involved (considering it's embedded Linux/Yocto), so let me try to give as much context as I can.

I am on an embedded Linux setup. I mount a squashfs with a writable overlay (using overlayfs) and then chroot into it, transfering control to systemd.

My ```/proc/sys/kernel/core_pattern``` is ```|/lib/systemd/systemd-coredump %P %u %g %s %t %c %e```. If I set the core_pattern to ```/tmp/cores/core.%e.%p.%h.%t```, it works. So, it is def something with systemd.

My file system is correct/clean. It is not corrupted in anyway (```fsck``` comes back clean). I've even patched systemd to try to write the coredumps to a thumbdrive, still got the same issue.

I added the following lines to ```fileio.c``` to get more info about the error.

```c
fd = open(tmp, O_CREAT|O_EXCL|O_NOFOLLOW|O_NOCTTY|flags, 0640);
if (fd < 0) {
        log_error("Couldn't open: %d: %s", fd, tmp); // this is new
        return -errno;
}
```
I get this output.

```
Couldn't open: -1: /run/media/Pauls/.#core.ClearApp.0.7833dca6d3354c0e959b366df731bf9f.879.15329633730000000f174d1155a09d96
```

I wrap the same exact ```open``` command from userspace with the same paths/attributes, and it works as expected.

```
int fd = open("/run/media/Pauls/.#core.ClearApp.0.7833dca6d3354c0e959b366df731bf9f.879.15329633730000000f174d1155a09d96", O_CREAT|O_EXCL|O_NOFOLLOW|O_NOCTTY|O_RDWR|O_CLOEXEC, 0640);
```

Is there something about the context in which Linux invokes that core dumper that gives me this "Read-only" error message?

**Comment by pauldotknopf** [comment]
> StateDirectory= i.e. /var/lib/systemd/coredump/

This was the problem. We used to run systemd 234 with patches to drop coredumps at ```/var/log```, which is a binding to a persisted drive. After the update to 237, this error popped up.

I reverted our patch to coredump to ```/var/lib/systemd/coredump```, and it worked!

With that said, my ```/var/lib/``` directory is entirely RAM/temporary. I need the coredumps to persist (to ```/var/log```). Is it possible to have multiple state directories?

**Comment by poettering** [comment]
oh well, you void your warranty if you patch around in these things, you should know that...

Instead of patching this or changing the unit files I'd recommend to simply use a bind mount to make your local path available under the standard, upstream path. 

Anyway, closing, as this appears to be a downstream issue.
