### ISSUE TITLE
systemd-tmpfiles does not accept numeric uid/gid

### ISSUE THREAD

**Issue by aTanW** [systemd/systemd#9767]
Problem arise when there is need to create batch of directories for, for example, VMs. There is no real users, but files must belong to VM.

Please, add this standard functionality to user->uid mapping code.

**Comment by poettering** [comment]
tmpfiles accepts numeric UID/GID specifications just fine. It currently insists that there's a user entry for the item existing.

What does your setup look like? Do you specify the numeric UID of a user that doesn't exist?

**Comment by aTanW** [comment]
> Do you specify the numeric UID of a user that doesn't exist?
Yes, I do.

Here is lots of 'unprivileged' lxc VMs, each have shifted by 65535 root id from some base value. VMs are dynamically created and on-demand started.

The job is to make some fs resources, mounted into VMs, using tmpfiles. But it refuses to create resources when unexistent user ID specified in .conf file.

**Comment by poettering** [comment]
Fix waiting in #9783

**Comment by aTanW** [comment]
Wow! Thanx for that quick fix!
