### ISSUE TITLE
Make signing EFI-wrapped kernels automatic

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#978]
It's currently difficult to use sd-boot with EFI secure boot enabled because there are no automated ways to create a signing key, enroll it to the system and then sign the installed kernels with that key.

I would expect a typical installation process to be something like:
- disable secure boot to boot system using an sd-boot enabled boot media
- perform installation
- installer would ask a systemd-provided helper to create (or reuse?) a signing key, sign the installed kernel with it, and enroll the key into the system's firmware
- after rebooting, the user could re-enable secure boot

We could also avoid disabling secure boot by booting using shim/grub and a signed kernel, and still use sd-boot as the "bootloader" after installation.

**Comment by microcai** [comment]
2015-08-17 19:55 GMT+08:00 hadess notifications@github.com:

> It's currently difficult to use sd-boot with EFI secure boot enabled because there are no automated ways to create a signing key, enroll it to the system and then sign the installed kernels with that key.
> 
> I would expect a typical installation process to be something like:
> 
> disable secure boot to boot system using an sd-boot enabled boot media
> perform installation
> installer would ask a systemd-provided helper to create (or reuse?) a signing key, sign the installed kernel with it, and enroll the key into the system's firmware
> after rebooting, the user could re-enable secure boot

you can't enroll the key without enable secure boot first. you must
enable secure boot, and then enroll the key from within the UEFI setup
utility.

**Comment by msekletar** [comment]
> We could also avoid disabling secure boot by booting using shim/grub and a signed kernel, and still use sd-boot as the "bootloader" after installation.

In order to put the platform to setup mode (when you can freely enroll new keys) you have to either disable secure boot somewhere in BIOS utility menu and select setup mode, AFAIK, there is no standard interface for doing this. Alternatively you can do this by enrolling your own Platform key (PK), from secure mode, however new key must signed with private part of old PK (authorized update). That is not realistic, because currently enrolled PK is owned by HW vendor which sold you your computer.

**Comment by poettering** [comment]
@msekletar as mentioned earlier, it's not worse having to go to the BIOS setup utility to enable setup mode, than having to go the BIOS and enable boot from USB. People who are technically savvy enough to do the latter and install their new OS, should not have problems to do the former as well. I think it's completely fine to tell users:

1) Before installation, enable USB booting and SecureBoot Setup mode in your BIOS
2) After installation, disable both again.

For Fedora it's just a few lines of docs more on this page:

https://docs.fedoraproject.org/en-US/Fedora/22/html/Installation_Guide/chap-booting-the-installation.html

**Comment by msekletar** [comment]
@poettering sure, I was just trying to point out that booting with shim+grub from DVD/USB would get us exactly nowhere. As you said it, we can't do anything without disabling secure boot first.

Also 2) point you mentioned is not necessary, once Platform key is reset then system should automatically transition to user mode so there should be no need to go to the firmware again and enable secure boot.

**Comment by mirh** [comment]
> After installation, disable both again.

This is not really possible on many newer (lazy) OEM systems. 

> As you said it, we can't do anything without disabling secure boot first.

Linux foundation [preloader](https://blog.hansenpartnership.com/linux-foundation-secure-boot-system-released/) doesn't require anything you mentioned to make live-cd boot tbh. 

And asking user to roll out/add/having to handle their own key seems quite overcomplicated anyway (especially for people barely tech savy enough to know how to boot from usb)
Besides, I'm not sure any specific installer is systemd business?

This issue should be focused on automatizing self-signing for advanced users (I mean, the only ones that will ever want to tinker with openssl) imo. 
I think a good mechanism (triggered by bootctl update or install) could work like
```
if (SecureBoot-efivar exists)
    if (SecureBoot-efivar is set enabled)
        if (efitools is installed && sbsigntools is installed)            // or sbupdate?
            if (/root/secure-boot/ has some key inside)
                then do-stuff-to-sign-new-systemd-boot-image
```
Then, I guess also auto-signing kernel images (that have a .conf entry in loader?) could be added, wanting.
