### ISSUE TITLE
RFE: read generated entropy and add to kernel entropy - systemd-user-random-seed.service

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#9797]
systemd-random-seed.service is nice but what about introducing systemd-user-random-seed.service?

What should systemd-user-random-seed.service do?

If file /var/lib/systemd/user-random-seed exists (up to user to create [1]) systemd-user-random-seed.service should in essence "`cat /var/lib/systemd/user-random-seed > /dev/random`". This should happen before (or after) systemd-random-seed.service is executed (or perhaps even systemd-random-seed.service / /lib/systemd/systemd-random-seed could handle this).

If file /var/lib/systemd/user-random-seed does not exists, just do nothing.

Purpose? Improve entropy quality.

----

[1] Later Linux distribution installers could ask the user to enter gibberish using their keyboard and/or do mice movements to record user entropy.

**Comment by poettering** [comment]
I am not sure I follow? Where would /var/lib/systemd/user-random-seed come from? And which component make sure it's changed on every boot?

**Comment by adrelanos** [comment]
> Where would /var/lib/systemd/user-random-seed come from?

Initially, up to the user to create. Probably very few security enthusiasts would use it.

In future: possible that linux distribution installers encourage users to provide entropy (to fill up /var/lib/systemd/user-random-seed) by typing random letters on the keyboard and/or doing random mouse movements.

> And which component make sure it's changed on every boot?

It's not changed on every boot. It stays the same.

When would this be useful? Assume a threat model where all hardware entropy sources to be completely broken/predictable or at least predictable enough so that there is no actual entropy. (This is more likely inside VMs.)

As I understand the kernel developers "feel free to add any entropy even a continuous stream of zeros, entropy can never get worse, only better". So in worst case, the quality of the entropy stays as is. In best case (very good chance luck) the entropy is improved.

In case all hardware entropy sources to be completely broken/predictable or at least predictable enough, systemd-user-random-seed.service may be good enough to sufficiently seed the entropy pool so there is actual entropy rather than fully predictable.

**Comment by poettering** [comment]
> In future: possible that linux distribution installers encourage users to provide entropy (to fill up /var/lib/systemd/user-random-seed) by typing random letters on the keyboard and/or doing random mouse movements.

/dev/urandom is seeded by kbd/mouse events internally in the kernel anyway, there's no need to do this again from userspace.

> And which component make sure it's changed on every boot?
> 
> It's not changed on every boot. It stays the same.

That's not useful, that basically means the machine comes up with the same random pool on every single boot. The random pool  is not supposed to contain guessable data, but it becomes very much guessable data if we come up with the same data every time. 

Sorry, but this won't improve the situation at all.

Moreover, `/var/lib/systemd/random-seed` is where systemd saves the random seed, you might as well just add your data there. Alternatively, a single line shell script with a service file can do what you are asking for, no?

Sorry, but I am not convinced this something to add to systemd. I am not seeing why this would improve things, nor that it wouldn't be something that could be added downstream...

Sorry.
