### ISSUE TITLE
systemd-timesyncd does not work on RO filesystem

### ISSUE THREAD

**Issue by lesto** [systemd/systemd#9804]
**Is your feature request related to a problem? Please describe.**
i am creating a read only filesystem to have a more reliable machine in case of powerloss. The time syncronization fails as it fails to set up "special execution directory /var/lib" and at step "STATE_DIRECTORY spawning"

**Describe the solution you'd like**
A clear way to know witch folder/file i need to bind to tmpfs to make time sync (and eventually other services) works

**Describe alternatives you've considered**
Also an overlayFS with a read/write partition can be considered; in that case would be nice to have a fstab mount option to "format" the partition in case of error

**Comment by yuwata** [comment]
Please see the discussions and suggestions in #9296.
