### ISSUE TITLE
systemd-networkd: Automatically generate DUID for DUIDType=link-layer

### ISSUE THREAD

**Issue by klada** [systemd/systemd#9805]
**Is your feature request related to a problem? Please describe.**

When deploying IPv6 in enterprise networks the clients are usually required to obtain their IPv6 address through DHCPv6 with their link layer address. For ethernet networks this will be the MAC address.

systemd-networkd already supports this scenario, but it's configuration is rather unflexible and static. Right now you need these lines in such environments:
```
[DHCP]
DUIDType=link-layer
# Provide static ethernet link layer addres
DUIDRawData=00:01:50:7b:9d:aa:bb:cc
```

The problem here is that you need to hard-code the MAC address in the *.network files, which is very unflexible and hard to manage.

**Describe the solution you'd like**

I see two possibilities here:

1. Allow omitting `DUIDRawData` entirely and automatically generate the appropriate DUID for `DUIDType=link-layer`, derived from the MAC address. I think this would actually be what the user expects.
2. When using dhclient6 in enterprise environments you also need a custom configuration for specifying the correct client-id. However dhclient allows this syntax: `send dhcp6.client-id = concat(00:03:00, hardware);`. It would be nice if alternatively a similar syntax could be implemented für `DUIDRawData`, so we don't have to hard-code the device's MAC address in the *.network files any more.

**Comment by yuwata** [comment]
Sounds reasonable for me.

**Comment by yuwata** [comment]
I will try to implement this on top of #9406.

**Comment by yuwata** [comment]
I've implement this in #9406. If possible, could you try the PR?

**Comment by klada** [comment]
@yuwata Wow, you are fast.  I've switched to your branch and removed the `DUIDRawData` from my config.

systemd-networkd tries to build a client identifier based on the MAC address now, but unfortunately the identifier is wrong. Right now the automatically generated DUID is padded with too many zeroes before the actual MAC adress, so the actual link-layer address is cut off. This is a capture from the DHCPv6 request, which illustrates the problem (see Link-layer address):


```
Frame 178: 130 bytes on wire (1040 bits), 130 bytes captured (1040 bits) on interface 0
Ethernet II, Src: LcfcHefe_aa:bb:cc (50:7b:9d:aa:bb:cc), Dst: IPv6mcast_01:00:02 (33:33:00:01:00:02)
Internet Protocol Version 6, Src: fe80::527b:9dff:fed5:3ba5, Dst: ff02::1:2
User Datagram Protocol, Src Port: 546, Dst Port: 547
DHCPv6
    Message type: Solicit (1)
    Transaction ID: 0xa46744
    Rapid Commit
        Option: Rapid Commit (14)
        Length: 0
    Identity Association for Non-temporary Address
        Option: Identity Association for Non-temporary Address (3)
        Length: 12
        Value: 667b932a0000000000000000
        IAID: 667b932a
        T1: 0
        T2: 0
    Fully Qualified Domain Name
        Option: Fully Qualified Domain Name (39)
        Length: 6
        Value: 0104746f6675
        0000 0... = Reserved: 0x00
        .... .0.. = N bit: Server should perform DNS updates
        .... ..0. = O bit: Server has not overridden client's S bit preference
        .... ...1 = S bit: Server should perform forward DNS updates
        Client FQDN: demo-client
    Option Request
    Client Identifier
        Option: Client Identifier (1)
        Length: 10
        Value: 0003000100000000507b
        DUID: 0003000100000000507b
        DUID Type: link-layer address (3)
        Hardware type: Ethernet (1)
        Link-layer address: 00:00:00:00:50:7b
    Elapsed time
```

**Comment by klada** [comment]
Your updated PR #9406 is now working properly for me. No more manual MAC address needed for `DUIDType=link-layer`. Good job :+1:
