### ISSUE TITLE
systemctl edit doesn't handle Ctrl-Z well

### ISSUE THREAD

**Issue by lilydjwg** [systemd/systemd#9806]
**systemd version the issue has been seen with**
> systemd 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > after Ctrl-Z systemctl edit is put into background and I can continue to use the shell

**Unexpected behaviour you saw**
 > after Ctrl-Z systemctl edit is still in foreground, while the editor has been put into background

**Steps to reproduce the problem**
* systemctl edit *some-unit*
* <kbd>Ctrl-Z</kbd>

**Comment by stueja** [comment]
Same for me, just right now. Any workaround?

**Comment by ronnyadsetts** [comment]
Just been bitten by this on Debian Buster (systemd 241-7~deb10u1). Irritating.

Had to use kill -9 on the "systemctl edit" process which is a bit harsh...

**Comment by stueja** [comment]
And again.

**Comment by poettering** [comment]
@stueja would love to review a patch for this!

**Comment by floppym** [comment]
Copy/pasting my analysis here so it's easier to find:

When we call `safe_fork` with `FORK_RESET_SIGNALS|FORK_DEATHSIG` and `FORK_WAIT` is set, the following sequence happens:

1. The parent blocks all signals, and calls fork.
2. The parent calls `wait_for_terminate_and_check` to wait for the child terminate.
3. The child unblocks signals and execs the editor.
4. The child receives `SIGTSTP` (Ctrl-Z), and stops.
5. The parent receives `SIGTSTP`, but all signals are still blocked so the signal isn't processed.
6. The user is left with an unusable terminal.
7. If the user sends `SIGCONT` to the child, the editor resumes.
8. When the child exits, the parent resumes, and unblocks signals.
9. The parent finally processes the `SIGTSTP` signal, and the user is returned to the shell prompt with the parent process in the background.

A fix is waiting in #14853.
