### ISSUE TITLE
systemd-networkd sets wrong default routes on boot 

### ISSUE THREAD

**Issue by jojoax** [systemd/systemd#9810]
**systemd` version the issue has been seen with**
> 239

**Used distribution**
 > arch linux rolling release

**Expected behaviour you didn't see**
 > **correct working default gateway setup** on the **real interface** as configured in /etc/systemd/network/01-ens3.network:

```
[match]
Name=ens3

[Network]
Address = x.y.z.235/29
Gateway = x.y.z.233
DNS = 8.8.8.8
IPv6AcceptRA=no
LinkLocalAddressing=no
```

**Unexpected behaviour you saw**
 > wrong default route on lo interface, which will **never** work
 > **wrong default route setup on "lo", double default route setup on real ens3 and lo interface**
> direct after boot:
>  # route -n
Kernel IP routing table
Desitnation          Gateway          Genmask             Flags       Metric       Ref    Use    Iface
0.0.0.0                  x.y.z.233          0.0.0.0                  UG          0               0        0        lo
0.0.0.0                  x.y.z.233          0.0.0.0                  UG          0               0        0        ens3
x.y.z.232               0.0.0.0             255.255.255.248  U             0               0        0        ens3

Solving the Problem on runtime:
 # route del default lo
All is running fine

**Steps to reproduce the problem**
setup a static /29 network in a fresh arch linux system, boot the system

**Comment by yuwata** [comment]
I cannot reproduce this. Could you show all .network files?

**Comment by jojoax** [comment]
Cloed - Typo in [{match] -> [Match]  section. Sryy, Error between Screen and keyboard    :(
