### ISSUE TITLE
Reduce log message for IP usage of stopped units

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#9816]
**Is your feature request related to a problem? Please describe.**

After enabling `DefaultIPAccounting=yes`, my log messages start looking like this:

> NetworkManager-dispatcher.service: Consumed 10ms CPU time, received 0B IP traffic, sent 0B IP traffic               
> geoclue.service: Consumed 39ms CPU time, received 0B IP traffic, sent 0B IP traffic                                 
> systemd-timedated.service: Consumed 24ms CPU time, received 0B IP traffic, sent 0B IP traffic                       
> systemd-localed.service: Consumed 30ms CPU time, received 0B IP traffic, sent 0B IP traffic                         
> systemd-hostnamed.service: Consumed 28ms CPU time, received 0B IP traffic, sent 0B IP traffic                       
> pacman-update.service: Consumed 841ms CPU time, received 10.2M IP traffic, sent 188.2K IP traffic                   
> systemd-tmpfiles-clean.service: Consumed 11ms CPU time, received 0B IP traffic, sent 0B IP traffic                  
> NetworkManager-dispatcher.service: Consumed 9ms CPU time, received 0B IP traffic, sent 0B IP traffic                
> NetworkManager-dispatcher.service: Consumed 8ms CPU time, received 0B IP traffic, sent 0B IP traffic                
> pacman-update.service: Consumed 13.559s CPU time, received 334.4M IP traffic, sent 5.6M IP traffic                  
> NetworkManager-dispatcher.service: Consumed 6ms CPU time, received 0B IP traffic, sent 0B IP traffic                
> NetworkManager-dispatcher.service: Consumed 5ms CPU time, received 0B IP traffic, sent 0B IP traffic                
> NetworkManager-dispatcher.service: Consumed 5ms CPU time, received 0B IP traffic, sent 0B IP traffic                

Personally, I find that a bit verbose… not consuming any IP traffic is the norm for most services (in fact, many of them are sandboxed to prevent any networking), so I would prefer to spend a bit less log message real estate on them. (This might become more relevant in the future, if other kinds of accounting are also to be included in this message.)

**Describe the solution you'd like**

I would like the common case of “0B ingress, 0B egress” to be summarized more tersely, e. g.

> Consumed … CPU time, no IP traffic

**Describe alternatives you've considered**

It’s perfectly acceptable to do nothing and keep the status quo, of course, since this is just a minor cosmetic suggestion :)

**Comment by poettering** [comment]
sounds like a good idea.
