### ISSUE TITLE
Support of Aiptek Hyperpen 12000U needs hwdb entries

### ISSUE THREAD

**Issue by dermoench42** [systemd/systemd#9834]
Running a current Gentoo Linux / Gnome / systemd-238-r7 I tried to get my Aiptek Hyperpen to work.
The Kernel module loads fine, dmesg / lsusb told me everything is ok. But xinput complains about a missing resolution on the aiptek device, and therefor ignoring it.

lsusb:
Bus 001 Device 002: ID 08ca:0010 Aiptek International, Inc. Tablet

After digging a bit on libinput and hardware detection I found a toolset evemu, and did a evemu-describe on the aiptek device. It gives me: 
[evemu-Aiptek-Hyperpen12000U.txt](https://github.com/systemd/systemd/files/2270771/evemu-Aiptek-Hyperpen12000U.txt)

There are entries for x and y dimensions, both resolutions are 0. The sensor field on the tablet  is marked with a little orange line in the dimensions 300mm width and 225mm height. The x max of 5999 results in an x resolution of 20/mm and the y max of 4499 in an y resolution of 20/mm.

Then I tried to setup a a file /lib64/udev/hwdb.d/61-evdev.hwdb with:
```
#########################################
# AIPTEK
#########################################

# Hyperpen 12000U
evdev:input:b0003v08CAp0010*
 EVDEV_ABS_00=::20
 EVDEV_ABS_01=::20
```
Rebooting, the aiptek device is detected without xinput errors.
```
muli ~ # xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Natural® Ergonomic Keyboard 4000	id=11	[slave  pointer  (2)]
⎜   ↳ Logitech Trackball                      	id=14	[slave  pointer  (2)]
⎜   ↳ Kensington      Kensington USB/PS2 Orbit	id=15	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Microsoft Natural® Ergonomic Keyboard 4000	id=10	[slave  keyboard (3)]
    ↳ VF0700 Live! Cam Chat HD: VF070         	id=12	[slave  keyboard (3)]
    ↳ Aiptek                                  	id=13	[slave  keyboard (3)]
    ↳ Microsoft Natural® Ergonomic Keyboard 4000	id=16	[slave  keyboard (3)]
```
But it is shown as slave keyboard, which confuses me. It seems to me, that my hdb entry isn't fully correct yet, or there are additionally rules/informations needed.
So I'd like to know what would be correct - and propose to include the entries in the hwdb database file. 
The coresponding libinput issue is
https://gitlab.freedesktop.org/libinput/libinput/issues/107

And to the end: Aiptek Hyperpen Devices IDs are available under other brands, e.g. see https://bugs.freedesktop.org/show_bug.cgi?id=103476

Many thanks,

ervin

**Comment by whot** [comment]
The change looks good, do you mind submitting this as a PR though? That's one button-click away from being merged then ;)

**Comment by f0k** [comment]
I have an Aiptek Hyperpen 6000U, with the same error ("event20 - Aiptek: libinput bug: missing tablet capabilities: resolution.Ignoring this device."), and tried to follow the same steps as @dermoench42.

`lsusb | grep Aiptek` gives me:
```
Bus 002 Device 009: ID 08ca:0020 Aiptek International, Inc. APT-6000U Tablet
```

`sudo evemu-describe /dev/input/event20` gives me (truncated to the interesting parts):
```
# EVEMU 1.3
# Kernel: 4.15.0-118-generic
# DMI: dmi:bvnLENOVO:bvrJBET71WW(1.35):bd09/14/2018:svnLENOVO:pn20BWS11H00:pvrThinkPadT450s:rvnLENOVO:rn20BWS11H00:rvr0B98417PRO:cvnLENOVO:ct10:cvrNone:
# Input device name: "Aiptek"
# Input device ID: bus 0x03 vendor 0x8ca product 0x20 version 0x100
# Supported events:
[...]
#   Event type 3 (EV_ABS)
#     Event code 0 (ABS_X)
#       Value        0
#       Min          0
#       Max       2999
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 1 (ABS_Y)
#       Value        0
#       Min          0
#       Max       2249
#       Fuzz         0
#       Flat         0
#       Resolution   0
[...]
```
So it has fewer pixels than the 12000U (2999x2249), but it's also smaller; I also get a resolution of 20 px/mm for both dimensions.

Happy that the solution was so easy, I created a `/etc/udev/hwdb.d/61-evdev-aiptek.hwdb` file (I'm on Ubuntu) with the following:
```
# Hyperpen 6000U
evdev:input:b0003:v08CAp0020*
 EVDEV_ABS_00=::20
 EVDEV_ABS_01=::20
```
Basically the same as @dermoench42's one, but using a product ID of 0x20 instead of 0x10. I ran `sudo udevadm hwdb --update` and checked that I get back the settings with `systemd-hwdb query evdev:input:b0003:v08CAp0020`. I even rebooted to be sure.

Unfortunately, it seems the setting is not getting picked up. I still get the same error, and `sudo evemu-describe /dev/input/event20` still lists a resolution of 0. Is my `evdev:input:b0003:v08CAp0020*` selector wrong? I'd like to get it to work and send a PR to hwdb as well.

<details><summary>Output of `udevadm info /dev/input/event20`:</summary>

```
P: /devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/input/input22/event20
N: input/event20
S: input/by-id/usb-AIPTEK_APT-6000U-event-mouse
S: input/by-path/pci-0000:00:14.0-usb-0:3:1.0-event-mouse
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-id/usb-AIPTEK_APT-6000U-event-mouse /dev/input/by-path/pci-0000:00:14.0-usb-0:3:1.0-event-mouse
E: DEVNAME=/dev/input/event20
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/input/input22/event20
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_MOUSE=1
E: ID_INPUT_TABLET=1
E: ID_MODEL=APT-6000U
E: ID_MODEL_ENC=APT-6000U
E: ID_MODEL_ID=0020
E: ID_PATH=pci-0000:00:14.0-usb-0:3:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_1_0
E: ID_REVISION=0100
E: ID_SERIAL=AIPTEK_APT-6000U
E: ID_TYPE=hid
E: ID_USB_DRIVER=aiptek
E: ID_USB_INTERFACES=:030102:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=AIPTEK
E: ID_VENDOR_ENC=AIPTEK
E: ID_VENDOR_ID=08ca
E: LIBINPUT_DEVICE_GROUP=3/8ca/20:usb-0000:00:14.0-3
E: MAJOR=13
E: MINOR=84
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=1256443736
E: XKBLAYOUT=de
E: XKBMODEL=pc105
```
</details>

**Comment by whot** [comment]
> `sudo udevadm hwdb --update`

don't use that, it has a different behaviour to the preferred `systemctl-hwdb update` and some obvious-looking hwdb matches don't apply because of that (legacy) behaviour.

> evdev:input:b0003:v08CAp0020*

Drop the colon before `v`

**Comment by f0k** [comment]
>> sudo udevadm hwdb --update
>
> don't use that, it has a different behaviour to the preferred `systemctl-hwdb update`

All right! Should be `systemd-hwdb update`, though.

>> evdev:input:b0003:v08CAp0020*
>
> Drop the colon before v

Oh boy... I was expecting something like that and just couldn't see it. :eyes: Thanks a lot! PR coming!
