### ISSUE TITLE
DNSSEC validation should not fail for TLDs without DS records

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#9840]
**systemd version the issue has been seen with**
systemd 239
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 `systemd-resolved` should just ignore TLDs without DS records.

**Unexpected behaviour you saw**
It's impossible to resolve the domain `mailchi.mp` due to missing DS records for the TLD.

 `Aug 09 13:28:14 motoko.nullday.de systemd-resolved[500]: DNSSEC validation failed for question mailchi.mp IN A: failed-auxiliary`

**Steps to reproduce the problem**

Set `DNSSEC` on `yes` in `/etc/systemd/resolved.conf` and try to resolve `mailchi.mp`:
`sudo resolvectl query mailchi.mp`

**Note: Yes, I know I could set dnssec on allow-downgrade. But in my opinion this should work even with dnssec=yes**

**Comment by yuwata** [comment]
Could you give us any relevant RFCs?

**Comment by shibumi** [comment]
https://tools.ietf.org/html/rfc4033 and https://tools.ietf.org/html/rfc4035.

I am not a DNS expert, so don't take my word as gold, but in my opinion a dns query should only fail if the dnssec entry is invalid. If there is no dnssec entry for the domain due to a missing ds record this should be just ignored. In other words: "If there is nothing to check for validation, it should just resolve without issues"

Here is a simple example. As you can see the `de` zone has a `dnskey` entry. This entry is missing for the `mp` zone. So there should be just no dnssec validation for this zone and `systemd-resolved` should not fail to resolve the domain even with `dnssec=yes` in `resolved.conf`. Or am I wrong? 
```
❯ dig de DNSKEY 

; <<>> DiG 9.13.0 <<>> de DNSKEY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14083
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;de.				IN	DNSKEY

;; ANSWER SECTION:
de.			7143	IN	DNSKEY	256 3 8 AwEAAZhRBibUdE26jR57oKbr1PERY3GTV1JPLtGvkcJ9B83VtJN34r5C P/kYDxti/t9/dmaxtPTD+Arj9Ka+IyMnFEbYvoGjPHLTaQVKliE8F08Y 2RB4ivFCuZXc9CPlAA5UbSehUUAqwlHc9B7LCoy3kgOkvk7xmJZ9+nPm cwBMQpZp
de.			7143	IN	DNSKEY	257 3 8 AwEAAaZEsxM26e8MgLuWsLAeRd7BzNdJjvhfGbqQ1xxtYd4TPPqYr7Qc K9Em18VyYEnjqXOqVWBuOhCWnrijP5GiumIliap+LerHjTk3QCgim1qv w3k7UFOgwMe8yOl7hghG8Nbgw6UnVfmUD71TaGSwj1C5EO2guiXZkFPU p2UzmUmoe5EWwtzCni7L0RDl5MaRVhjUBEkPrAVI603GDTuwtRKZLTiy fc3Qmq/u83/6Knxot5pHp3reRcsp0vk2G+RQubgDKsmaXCql4mPzR911 Di68vwbBfSyLZ0EOwVkrO7VJgr/RJJ37JlydfQfGmQ3Dkvw1h8ifZhRC 8oOkv8ynUXM=

;; Query time: 13 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Aug 09 13:59:46 CEST 2018
;; MSG SIZE  rcvd: 455
```

```
❯ dig mp DNSKEY

; <<>> DiG 9.13.0 <<>> mp DNSKEY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56657
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;mp.				IN	DNSKEY

;; AUTHORITY SECTION:
mp.			300	IN	SOA	ns1.nic.mp. support.get.mp. 1 86400 7200 604800 300

;; Query time: 294 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Aug 09 13:59:21 CEST 2018
;; MSG SIZE  rcvd: 87
```

**Comment by yuwata** [comment]
> I am not a DNS expert

Neither am I :-p
Anyway, thank you for the references.

**Comment by shibumi** [comment]
@yuwata ok according to this analysis here: http://dnsviz.net/d/mailchi.mp/dnssec/ is `systemd-resolved` acting correctly, because there exists no `AA-flag` for the domain `mailchi.mp`. Therefore it gets the status `insecure` and therefore `systemd-resolved` fails to query. I am going to close the issue.. sorry for the noise. `systemd-resolved` behaves correctly here, I guess.
