### ISSUE TITLE
"systemd-analyze dump" output broken for LimitNOFILE* properties (239 regression)

### ISSUE THREAD

**Issue by mk-fg** [systemd/systemd#9846]
**systemd version the issue has been seen with**
> 239
> [note: was not present in systemd-238]

**Used distribution**
 > ArchLinux x86_64

**Expected behaviour you didn't see**
 > `systemd-analyze dump` and corresponding dbus output have LimitNOFILE and LimitNOFILESoft properties, correctly prefixed and formatted.
 > Quick test command: `systemd-analyze dump | grep LimitNOFILE` (empty output with 239)

**Unexpected behaviour you saw**
 > These unit properties are present in the output, but are broken - printed with tab character after "Limit" and not before, e.g. `Limit\tNOFILE: 4096` on a line instead of `\tLimitNOFILE: 4096`.

**Steps to reproduce the problem**

- Make sure systemd-239 is used (problem wasn't present with systemd-238): `systemctl --version` => 239

- Run `systemd-analyze dump | less +/NOFILE`, weird output in question should be scrolled into view.

**Comment by yuwata** [comment]
Fix is waiting in #9847.

**Comment by mk-fg** [comment]
Thank you!
