### ISSUE TITLE
systemd-fsck assumes fsck.* has the -a option; fsck.exfat does not

### ISSUE THREAD

**Issue by scolby33** [systemd/systemd#9849]
**systemd version the issue has been seen with**
 > ```sh
 > $ systemctl --version
 > systemd 239
 > +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid
 > ```

**Used distribution**
 > Arch
 > ```sh
 > Linux cobalt 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux
 > ```

**Expected behaviour you didn't see**
 > - `systemd-fsck` fails to fsck an ExFAT filesystem.
 > - `systemd-fsck` doesn't exit with an error code when this failure is encountered

**Unexpected behaviour you saw**
 >  ```sh
 > $ sudo journalctl -b -u systemd-fsck*
 > *snip*
 > Aug 10 02:02:30 cobalt systemd[1]: Starting File System Check on /dev/disk/by-uuid/10DF-38AB...
 > Aug 10 02:02:30 cobalt systemd-fsck[1023]: fsck.exfat: invalid option -- 'a'
 > Aug 10 02:02:30 cobalt systemd-fsck[1023]: Usage: fsck.exfat [-V] <device>
 > Aug 10 02:02:30 cobalt systemd-fsck[1023]: exfatfsck 1.2.8
 > Aug 10 02:02:30 cobalt systemd[1]: Started File System Check on /dev/disk/by-uuid/10DF-38AB.
 > *snip*
 > ```
**Steps to reproduce the problem**
 > Use `systemd-fsck` on an ExFAT-formatted filesystem.

The problem appears to be [here](https://github.com/systemd/systemd/blob/8595102d3ddde6d25c282f965573a6de34ab4421/src/fsck/fsck.c#L404).

A command line like `/sbin/fsck -a -T -l -M [-C fd] /dev/disk/by-uuid/...` is assembled. `-T`, `-l`, `-M`, and `-C` are fine, since they are handled by `/sbin/fsck` itself. `-a`, however, is passed through to `fsck.*` and `fsck.exfat` (a symlink to `exfatfsck` 1.2.8 on my system) doesn't have the `-a` option; in fact, the only option it has is `-V` to print the version.

**Comment by scolby33** [comment]
Initial discussion on the Arch Forums: https://bbs.archlinux.org/viewtopic.php?id=239364

**Comment by poettering** [comment]
I am pretty sure that this is something to fix in fsck.exfat... *all* other fsck implementations support that. 

I mean there's a certain baseline fsck implementations need to support, and I am pretty sure "-a" is not unreasonable to expect, the same as taking a device node as first parameter isn't unreasonable to expect.

Hence, please ping the fsck.exfat maintainers about this, I am sure they'd be willing to add at least some compatibility support.

**Comment by poettering** [comment]
> The way it is now, as far as systemd is concerned, systemd-fsck@my-exfat-disk finished successfully, which is not the case.

return values from fsck are not just a simple "0 is success; != 0 is failure". instead they are a bit mask, and bit 1 means "error corrected", i.e. if fsck exits with error "1" then this is not a failure but just means "i fixed something" and hence won't cause systemd-fsck to fail as a whole.

I hope this explains this.

Closing, as this is really somehting mkfs.exfat needs to implement properly... It should support both -a and the exit codes correctly. For the meanings of the bits, see the fsck(8) man page.
