### ISSUE TITLE
networkd config files are missing from interface stability table

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#9850]
https://www.freedesktop.org/wiki/Software/systemd/InterfaceStabilityPromise/ and https://www.freedesktop.org/wiki/Software/systemd/InterfacePortabilityAndStabilityChart/ should be updated for any recent changes.

**Comment by keszybz** [comment]
@poettering you mentioned recently that you're working on converting some wiki pages to markdown. Where those two on your list by any chance?

**Comment by poettering** [comment]
i have converted the discoverable partition spec as part of #14390, but that's all i did so far. I did not start working on anything else.

**Comment by poettering** [comment]
@keszybz hmm, do you intend to add these now that the stability stuff got migrated to markdown?

**Comment by keszybz** [comment]
Not in the immediate future. If you have a spare moment to do that, that'd be great.
