### ISSUE TITLE
Hole in `ProtectSystem=` etc. due to mount propagation

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#9857]
**systemd version the issue has been seen with**
v238

**Used distribution**
Fedora Workstation 28

**Expected behaviour you didn't see**
`ProtectSystem=strict` "ensures that any modification of the ... local mounts is prohibited for the service" - `man systemd.exec`

**Unexpected behaviour you saw**
Local mounts can be modified, if the mount is created after the service is started.

(And I noticed that `ProtectSystem=strict` or `ProtectHome=read-only` do not imply `After=home.mount`. So this hole could be triggered by the normal boot process).

**Steps to reproduce the problem**

1. `systemctl cat systemd-resolved | grep ProtectSystem=strict`
2. `systemctl start systemd-resolved`
3. `eval "$(systemctl show -p MainPID systemd-resolved)"`
4. `nsenter --mount -t $MainPID touch /mnt/a`
5. `mount tmpfs -t tmpfs /mnt`
6. `nsenter --mount -t $MainPID touch /mnt/a`

Observed behaviour on v238:

* step 4 fails with "Read-only file system"
* step 6 succeeds.

**Fixing this problem**

I would say the "hole" in ProtectSystem= is unfixable.  See next section.

I think the bug is in the documentation for `ProtectSystem=`, suggesting it does something that it cannot.  Currently the documentation mentions the "hole" only in `ReadOnlyPaths=`.

At the very end of `ProtectSystem=`, it mentions that "The same restrictions regarding mount propagation and privileges apply as for `ReadOnlyPaths=`".  But, where `ReadOnlyPaths=` does mention "restricting access with these options does not extend to submounts of a directory that are created later on", the word "mount propagation" is not mentioned.  And `ReadOnlyPaths=` mentions another restriction in terms of "mount propagation", so the "hole" could even be overlooked.

It might be clearer to say "This setting cannot ensure protection in all cases. In general it has the same limitations as ReadOnlyPaths=, see below."

IMO: it is easy for users to expect the "restriction" regarding privileges, that privileged services could be able to remount the directory read-write.  But mount propagation is not as obvious to users.  Mount propagation is not as widely understood, and the "hole" it causes is more unusual.

It seems non-obvious that systemd would provide a `ProtectHome=read-only` option, that does not work when home directories are encrypted (see `pam_ecryptfs`), or stored on a network filesystem... (network filesystems are mounted after `basic.target`)

Maybe the documentation for `ProtectSystem=strict` already mentions the `netfs` case, with the word "local" in "ensures that any modification of the ... local mounts is prohibited".  But it does not seem very clear.  And it seems inaccurate, because it also doesn't protect mounts made at runtime like automounts or user mounted disks, even if they are local mounts.

**Why the "hole" cannot be fixed**

We cannot disable propagation of mount changes into the service namespace. It is needed, to allow ejecting removable media which was mounted in the main namespace.

So far, Linux only supports enabling or disabling this propagation.  We can't allow unmounts to propagate without also allowing mounts to propagate.

EDIT: You can also avoid daemons seeing user mounts at all e.g. by running users as `PrivateMounts=yes`.  The problem is this breaks expected behaviour with `mount`, `sudo mount`, etc.  This might be interesting to admins who want to harden multi-user systems.  It would also make sure not to leave user mounts after logout, if `KillUserProcesses=yes` is set in logind.

**Comment by yuwata** [comment]
Note that such a 'hole' is already commented at `bind_remount_recursive_with_mountinfo()`.

**Comment by yuwata** [comment]
BTW, are there any documents about the conditions that new mounts propagates to slave mount namespaces. Though, I may not correctly understand the potential issue or propagation of mount namespaces.

**Comment by yuwata** [comment]
Or, in other words, does the issue also affects units which have `RootDirectory=/RootImage=`?

**Comment by sourcejedi** [comment]
* [shared-subtree.txt](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt)
*  `man mount_namespaces` also mentions it.

I think RootDirectory= is affected but maybe not as much in practical use.  If a service uses `RootDirectory=/usr/lib/my-chroot`, it could be affected if someone mounts something underneath `/usr/lib/my-chroot`.  Or underneath a source path which the service used `BindPaths=` on.  (Implication: `BindPaths=/x:/y:norbind` is a bit holey as well.  I think it is best to avoid `:norbind` in most cases because this seems likely to cause confusion).

**Comment by sourcejedi** [comment]
Edited to add: I noticed that, e.g. `ProtectHome=yes` does not imply `After=home.mount`. So this hole could be triggered by the normal boot process.

**Comment by yuwata** [comment]
Yeah, I have concerned that after hearing this issue.
Especially, NFS /home is mounted usually late in the boot process. So, at least, networkd is easily affected by this, though I have not tested that yet.

**Comment by mbiebl** [comment]
@sourcejedi If I'm not mistaken, this might be necessary when users provide certificates which can reside in their home directory (think of VPN or WPA-Enterprise connections)

**Comment by poettering** [comment]
I wished the kernel would allow mount propagation where MS_RDONLY is automatically added to new propagated mounts. That would solve the problem properly

**Comment by poettering** [comment]
Fix waiting in #10569
