### ISSUE TITLE
systemctl escaping '*' in the unit name in buck operation 

### ISSUE THREAD

**Issue by Jamesits** [systemd/systemd#9862]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > Arch Linux

**Steps to reproduce the problem**
1. Create a demo service with minimal config:
```
# /etc/systemd/system/foo@.service
[Unit]
Description=Foo

[Install]
WantedBy=multi-user.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/echo foo%I
```

2. Enable one unit of our great `foo@.service`
```shell
sudo systemctl enable foo@1.service
```

3. Disable all the `foo@.service` units
```shell
sudo systemctl disable 'foo@*.service'
```

**Expected behaviour you didn't see**
In systemd v238, the disable command returns without error, and the `foo@1.service` unit is in disabled status.

**Unexpected behaviour you saw**
In systemd v239:
```
sudo systemctl disable 'foo@*.service'
Invalid unit name "foo@*.service" was escaped as "foo@\x2a.service" (maybe you should use systemd-escape?)

sudo systemctl status 'foo@1.service'
● foo@1.service - Foo
   Loaded: loaded (/etc/systemd/system/foo@.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```

Thus `sudo systemctl disable 'foo@*.service'` is not working anymore. However, `sudo systemctl disable foo@.service` seems to be working. 

I got a user report from https://github.com/Jamesits/systemd-named-netns/issues/11. I've searched for systemd's release notes but cannot find an entry reflecting this behavior change, so I guess this is maybe a bug.

**Comment by filbranden** [comment]
So I took a look at this, and I can't really reproduce that "in systemd v238, the disable command returns without error, and the `foo@1.service` unit is in disabled status."

I mean, the command returns without error, that part is OK... But I don't think the unit gets disabled. Can you double check that?

I'm not saying we shouldn't fix this (maybe we should), but just wanted to point out this doesn't seem to be a regression (at least from v238), so maybe we should turn this into an RFE...

Cheers,
Filipe

**Comment by filbranden** [comment]
Just tried this on systemd 233 on Debian Stretch, same behavior... No logs or error messages, but the units do *not* get disabled when using the wildcard...

**Comment by Jamesits** [comment]
@filbranden Yes, I can confirm on systemd 234 the command will return 0 but no unit is disabled.
