### ISSUE TITLE
file system namespace service options not working with user sessions

### ISSUE THREAD

**Issue by DamienRobert** [systemd/systemd#9870]
I don't know if this is a bug, a user error, or a rfe.

On archlinux with systemd-239, I tried to use ProtectHome=yes on a user service, but it does not seems to be working:
$ cat /run/user/1000/systemd/user/test.service
[Unit]
Description=test

[Service]
ProtectHome=true
ExecStart=/usr/bin/sh -c ls ~
$ systemctl --user start test.service
$ systemctl status test.service
=> This shows my files in $HOME, while I was expecting due to ProtectHome=yes that the ls would show nothing. (Checking `systemctl --user show test.service`, we do have ProtectHome=yes)

Likewise, `systemd-run --user -t -p ProtectHome=tmpfs zsh` launches a shell with full access to my Home.

So it seems like ProtectHome does not work for user sessions, so I guess other namespace mount operations like ReadOnly... neither. Is it because the systemd-user session has not enough privileges to create new namespaces mount? If so then maybe this could be specified in `man systemd.exec`. Otherwise (if this is not due to a user error), consider this as a rfe: this would be very useful to isolate user processes without being root.

**Comment by sourcejedi** [comment]
not yet merged: https://github.com/systemd/systemd/pull/9852/commits/a9ee242ce4691f0df204315923dbda9adef2482d

> Note that many of these sandboxing features are gracefully turned off on
    systems where the underlying security mechanism is not available. For example, <varname>ProtectSystem=</varname>
    has no effect if the kernel is built without file system namespacing or if the service manager runs in a container
    manager that makes file system namespacing unavailable to its payload.

Maybe this text should be extended to mention systemd "user instances", or however we want to call `systemd --user`.

**Comment by DamienRobert** [comment]
@boucman: ok this is what i thought, the systemd user session has not enough privilege to change file system namespacing. So maybe you could consider my request as a rfe then: before dropping root privileges to run as a user, maybe systemd could retain the capability to configure file system namespaces? I don't know how feasible this is.

Systemd provides great container like capabilities to isolate system processes, it would be great if the same would work for user processes, a la firejail/bubblewrap.

**Comment by boucman** [comment]
@DamienRobert I'm not good enough at kernel, but it is likely that this can't be done without giving users "too much" privileges... 

But my educated guess would be that this needs some sort of kernel support before systemd can expose the corresponding knobs to user instances...

**Comment by poettering** [comment]
Yeah, namespacing needs privs, this is nothing we can support for unpriv users with current kernels...

**Comment by poettering** [comment]
Fix waiting in #10569
