### ISSUE TITLE
Mounting is done in the private namespace with MountFlags=shared

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#9873]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Ubuntu 18.10 dev

**Expected behaviour you didn't see**
 > "cat /proc/mounts" should list the mounted device while "cat /proc/_pid_of_systemd_udevd/mounts" should not list the mounted device.

**Unexpected behaviour you saw**
 > "cat /proc/mounts" did not list the mounted device while "cat /proc/_pid_of_systemd_udevd/mounts" did list the mounted device.

**Steps to reproduce the problem**
Set MountFlags=shared in the [Service] section of systemd-udevd.service and mount a device from an udev rule.

Some additional information: Normally I have the file /etc/systemd/system/systemd-udevd.service.d/mount_flags.conf with the content
>[Service]
MountFlags=shared

but for simplicity I added MountFlags=shared to systemd-udevd.service and restarted it to test if it fails too.

**Comment by sourcejedi** [comment]
In case you're not aware, there's a recent `NEWS` item about `PrivateMounts=yes`. I expect you can work around this by forcing `PrivateMounts=no`.

**Comment by Sworddragon** [comment]
I guess PrivateMounts sort of replaces MountFlags then. In any case disabling private mounts does indeed revert to the expected behavior.
