### ISSUE TITLE
30-systemd-environment-d-generator hangs on battery

### ISSUE THREAD

**Issue by kamiyaa** [systemd/systemd#9877]
**systemd-239, gentoo linux, linux-4.18**
After logging into tty0, `30-systemd-environment-d-generator` hangs and 1 core goes to 100%.
Bash prompt never shows up.

I do not have the following directories:
 - `~/.config/environment.d/`
 - `/run/environment.d/`
 - `/etc/environment.d/`

And the only contents inside `/usr/lib/environment.d/` is `99-environment.conf` which is a symlink to `/etc/environment` which just contains:
```
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#
```

https://www.freedesktop.org/software/systemd/man/environment.d.html#

**Comment by poettering** [comment]
/cc @keszybz 

if you run /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator from the cmdline, does that finish quickly or does that hang too?

**Comment by poettering** [comment]
Are you saying the generator binary operates differently depending on whether your systems is plugged into AC or runs from battery? that would be very weird indeed?

**Comment by kamiyaa** [comment]
Yes. I managed to fix it by uninstalling consolekit though.

**Comment by poettering** [comment]
Ok closing then. If this reappears, please run the commands above. I can't see why CK would have any effect on this...
