### ISSUE TITLE
239; port 4433 and Invalid TCP Flag

### ISSUE THREAD

**Issue by inverse-ion** [systemd/systemd#9878]
**systemd version the issue has been seen with**
> 239
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > … Arch Linux 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > … Connect to port 4433 to establish remote SonicWALL VPN, or a connection on port 4433 when attempting to wget target address.

**Unexpected behaviour you saw**
 > … Could not connect to SonicWALL VPN on port 4433, or wget the index.html on the target port, but could access server behind target firewall on port 443.

Local firewall monitoring packets would show packets dropped due to Invalid TCP Flag
Example:
```
*Packet number: 259*
Header Values:
 Bytes captured: 60, Actual Bytes on the wire: 60
Packet Info(Time:08/15/2018 23:36:36.160):
 in:X0*(interface), out:--, DROPPED, Drop Code: 23(Invalid TCP Flag), Module Id: 25(network), (Ref.Id: _4257_txGsIboemfJqQlu), 1:1)
Ethernet Header
 Ether Type: IP(0x800), Src=[xx:xx:xx:xx:xx:xx], Dst=[yy:yy:yy:yy:yy:yy]
IP Packet Header
 IP Type: TCP(0x6), Src=[aaa.aaa.aaa.aaa], Dst=[bbb.bbb.bbb.bbb]
TCP Packet Header
 TCP Flags = [RST,], Src=[59992], Dst=[4433], Checksum=0x8720
Application Header
 Not Known
Value:[0]
Hex and ASCII dump of the packet:
 c0eae474 718cd43d 7ef3f203 08004500 00283da1 40004006 *...tq..=~.....E..(=.@.@.*
 541bc0a8 a8084261 fe01ea58 11512085 637d0000 00005004 *T.....Ba...X.Q .c}....P.*
 00008720 00000000 00000000                            *... ........            *
```

**Steps to reproduce the problem**
From archlinux-2018.08.01-x86_64.iso (systemd 239):
wget https://bbb.bbb.bbb.bbb:4433
--2018-08-17 00:04:07--  https://bbb.bbb.bbb.bbb:4433/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Connecting to bbb.bbb.bbb.bbb:4433...

... never connects

From archlinux-2018.07.01-x86_64.iso (systemd 238):
wget https://bbb.bbb.bbb.bbb:4433
--2018-08-17 00:07:50--  https://bbb.bbb.bbb.bbb:4433/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Connecting to bbb.bbb.bbb.bbb:4433... connected.
...

From Arch Linux local installation:
sudo pacman -Syyuu
... then downgraded systemd-239.0-2-x86_64 to systemd-238.133-4-x86_64
sudo reboot
Problem doesn't present itself after downgrading systemd and a reboot.

**Comment by filbranden** [comment]
This is probably due to systemd 239 enabling ECN by default, which happened with 
PR #9143, see the update to the [NEWS file](https://github.com/systemd/systemd/blob/v239/NEWS#L294).

You can confirm that by disabling it temporarily on your Arch Linux box:

```
$ sudo sysctl net.ipv4.tcp_ecn=0
```

Some articles on the internet suggest that some Sonicwall products might be broken and not be able to recognize ECN properly.

ECN is not happening on Linux only, it's happening in other OSs, so probably the best course of action is to report the issue to SonicWALL, assuming you have a support contract with them. Also maybe check if there are firmware updates for your VPN, which might have solved this already.

**Comment by inverse-ion** [comment]
That was it exactly, thank you very much. I'll get things worked out with SonicWALL, in the mean time I'm going to leave tcp_ecn on my Arch desktop set to 2.

**Comment by SimonIremonger** [comment]
@inverse-ion  Have SonicWALL reported this fixed at their-end now?

**Comment by inverseion** [comment]
> @inverse-ion Have SonicWALL reported this fixed at their-end now?

Nothing reported, I have set up several new workstations since 2018 and haven't needed to adjust for it. Either the SonicWALL NetExtender application was updated, or a firmware update on the firewall itself took care of it.
