### ISSUE TITLE
Allow to disable/enable services even if systemd isn't running as PID 1

### ISSUE THREAD

**Issue by thedrow** [systemd/systemd#9889]
**Is your feature request related to a problem? Please describe.**
I encountered this problem while developing an image using mkosi which runs systemd as PID 2 inside a nspawn container.
See https://github.com/systemd/mkosi/issues/262

**Describe the solution you'd like**
Even when `systemd` is not currently running or running as PID 2, `systemctl enable foo` should work as expected and no error message should appear.

**Describe alternatives you've considered**
I can create the symlinks to `/etc/systemd/system/whatever.target.wants/` myself. It's just that the UX is surprising.

**Comment by lucaswerkmeister** [comment]
`systemctl` has a `--root` option to operate on the file system directly without talking to the daemon.

**Comment by poettering** [comment]
@lucaswerkmeister is right, systemctl should be smart enough to detect when it is run outside of a systemd environment, and will in that case do its operation client side. You can force this by dooing --root=… or by doing setting the env var SYSTEMCTL_INSTALL_CLIENT_SIDE to 1. 

I am wonderng though why the auto-detection of this didn't work. What systemd version is running inside the container? What's the precise error of systemctl you see? If you set SYSTEMD_LOG_LEVEL=debug as env var for systemctl, anything interesting?

This is really something that should "just work". If it doesn't there's some bug somewhere...

**Comment by thedrow** [comment]
I will gather all the required information once I'll be at the customer's site since I don't have access to that environment remotely.

**Comment by poettering** [comment]
Ok. Lets close this. If this is still a problem with current systemd and you cAn reproduce the issue then by all means reopen and we can look into figuring out why the autodetection didnt work
