### ISSUE TITLE
LinkLocalAddressing=no regressed somewhere between v237 and v239

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#9890]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > Ubuntu Cosmic (18.10) devel

**Expected behaviour you didn't see**
 > eth0 device should *not* have any ipv6 LL address

**Unexpected behaviour you saw**
 > eth0 device *has* ipv6 LL address

**Steps to reproduce the problem**
```
$ cat 10-netplan-ens3.link 
[Match]
MACAddress=52:54:00:15:e0:3c

[Link]
Name=ens3
WakeOnLan=off

$ cat 10-netplan-ens3.network 
[Match]
MACAddress=52:54:00:15:e0:3c
Name=ens3

[Network]
DHCP=ipv4
LinkLocalAddressing=no

[DHCP]
UseMTU=true
RouteMetric=100
```

with above config, with v237 eth0 does *not* gain ipv6ll, but with v239 it does.

Starting to bisect, as nothing obvious has changed.

**Comment by yuwata** [comment]
I am not sure but 44b598a1c9d11c23420a5ef45ff11bcb0ed195eb may cause this.

**Comment by xnox** [comment]
@yuwata @ssahani @keszybz

The https://github.com/systemd/systemd/commit/44b598a1c9d11c23420a5ef45ff11bcb0ed195eb is the culprit after a more complete git bisect.

I did bisect between v239 and v237, rebuilding systemd-netwokrd and systemd-udevd, replacing these two and also providing matching rpath libsystemd-shared-X.so for systemd-networkd, rebooting the VM with the config shown in the bug description and observing if there is (bad) or isn't (good) ipv6LL address on the interface.

https://github.com/systemd/systemd/commit/44b598a1c9d11c23420a5ef45ff11bcb0ed195eb is the first bad commit, rebuilding full systemd package in ubuntu with just that commit reverted, results in working system again with LinkLocalAddressing=no honored.

I'm not sure if it was necessory to update both netwokrd & udevd, but it does seem that said commit above has a side-effect of no longer honoring LinkLocalAddressing=no. And I do understand that reverting said commit re-introduces https://github.com/systemd/systemd/issues/9254 .

I guess I should be adding more debugging info to see how/where/why the ipv6ll setting is ignored by mistake, or maybe not getting disabled as it should be....

**Comment by xnox** [comment]
BTW this defect was caught by https://netplan.io/ test-suite that validates that various networking setups can be correctly brought up with either networkd or networkmanager backends.

**Comment by xnox** [comment]
In master, MTU handling has been changed a bit. I was going to cherrypick those patches to see if they improve/fix this issue as well.

**Comment by xnox** [comment]
Ok, with MTU fixes from master cherrypicked, this still looks broken to me.

**Comment by henryptung** [comment]
@xnox If you're talking about master, [link_enable_ipv6 is still being called during link_set_mtu](https://github.com/systemd/systemd/blob/master/src/network/networkd-link.c#L1331). That, I think, is fundamentally wrong, because `link_set_mtu` isn't always called.

**Comment by xnox** [comment]
@henryptung i agree that it is very odd that `link_set_mtu` may enable ipv6, especially when not asked to do so at all....

**Comment by henryptung** [comment]
@ssahani Any thoughts here? Not sure any of us understand the rationale of the change moving `link_enable_ipv6` to `link_set_mtu`, so may need your help here.

**Comment by ssahani** [comment]
Could you please try with https://github.com/systemd/systemd/pull/11423

**Comment by xnox** [comment]
@ssahani still bad.

With that pull request applied, with .network setting LinkLocalAddressing=no, fe80 address is still gained, which is bad.

Can you explain what the code is doing? It appears to be checking `link_ipv6ll_enabled()` and forcing ipv6ll on, but I see no code there that parses `.network -> [Network] -> LinkLocalAddressing=no` at that point. Thus at link_up time the code must not force enable LinkLocal addressing. Or at some later point when .network is parsed, it should well turn IPv6 LinkLocal off, no?

**Comment by xnox** [comment]
@ssahani https://github.com/ssahani/systemd/commit/158d98817f757e2a5904930a49d542acf324f8cc looks good! netplan test suite passes, and doing minimal reproducer is also good (no ipv6 link local address setup).

**Comment by xnox** [comment]
Please pull that into master.

**Comment by yuwata** [comment]
If possible, please test #11423. Now I think it works fine.
