### ISSUE TITLE
nspawn exposes /proc/sysrq-trigger as RW to containers

### ISSUE THREAD

**Issue by tkolo** [systemd/systemd#9891]
**systemd version the issue has been seen with**
> 229, both on host and in container

**Used distribution**
 > ubuntu 16.04 LTS, both on host and in container

**Expected behaviour you didn't see**
 > guest/container should be denied to write to /proc/sysrq-trigger file

**Unexpected behaviour you saw**
 > `echo b > /proc/sysrq-trigger` in guest restarts the host, assuming sysrq-trigger file is enabled in the first place of course

**Steps to reproduce the problem**
1. On host `# sysctl -w kernel.sysrq=1`
2. On guest `# echo b > /proc/sysrq-trigger`

I'd expect that
- /sys
- /proc/sys
- /proc/sysrq-trigger
- /proc/irq
- /proc/bus
are all mounted read only, unless specified otherwise by parameters and/or .nspawn configuration file.
Some of them are mounted read only I think (/sys, for instance), not all though.

**Comment by evverx** [comment]
According to https://github.com/systemd/systemd/blob/master/.github/CONTRIBUTING.md#filing-issues
> We only track bugs in the two most recently released versions of systemd in the GitHub Issue tracker. If you are using an older version of systemd, please contact your distribution's bug tracker instead.

The two last versions of systemd are `238` and `239`.

By the way, 920a7899ded27 and d4b653c589fc are included in `239`, so it would be great if you could give it a try.
