### ISSUE TITLE
RFE: Add support for "systemctl reboot --bootloader-menu"

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#9896]
Currently it is possible to ask systemd to reboot into the firmware setup menu by doing: "systemctl reboot --firmware-setup".

Some desktop oriented distributions configure their bootloader to not show a menu during boot (by default), but sometimes it is still useful for the user to be able to get the boot menu. I'm working on implementing something similar to what Windows does where pressing shift while clicking the reboot option in the Windows shutdown menu will reboot into Windows boot/rescue menu, see:
https://wiki.gnome.org/Design/OS/BootOptions
And here is the GNOME backend for the UI discussed there:
https://gitlab.gnome.org/GNOME/gnome-session/merge_requests/6

Note that there is a FIXME in there for the actual implementation of asking the bootloader to show the menu and I've a very hack-ish patch to implement this for Fedora:
https://gitlab.gnome.org/jwrdegoede/gnome-session/commit/ef291f6a9d28bb7d8d7448a1278e72d77c49b8d8
Note only the second system("/usr/bin/pkexec ...") in there is related to this RFE.

The goal of this RFE is for systemd to support entering the bootloader menu by doing:  "systemctl reboot --bootloader-menu" or directly calling the equivalent dbus API.

The idea here would be that when this request is made to systemd, systemd will first start a special system-request-bootloader-menu.target target , in which bootloaders can drop oneshot services which do the necessary magic for that specific bootloader, and then after starting that target systemd reboots the system as it would do normally.

**Comment by jwrdegoede** [comment]
Any chance we could get some movement on this? This is blocking implementation of:
https://wiki.gnome.org/Design/OS/BootOptions

Which is mostly ready to go;
https://gitlab.gnome.org/GNOME/gnome-session/merge_requests/6  and:
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/199

Except that we need a bootloader agnostic mechanism to ask systemd to reboot into the bootloader-menu.

**Comment by hadess** [comment]
> Any chance we could get some movement on this?

I don't think you'll get movement any time soon if there isn't an MR to review.

**Comment by poettering** [comment]
I'd be willing to work on this, but first #10174 + #9437 should be merged, otherwise the base is a bit too shaky...

Regarding implementation: i think a simple solution could be taking inspiration how the "boot param" logic is implemented: when the shutdown is initiated logind should write out a quick file to /run. It would then be up to some grub supplied service to maybe read that during shutdown and do the right things... that way, logind doesn't need any plugin logic itself, which i'd very much prefer...

logind would of course natively also do EFI variable stuff and I'd very much propose on EFI systems to use that instead...

**Comment by jwrdegoede** [comment]
On 11-10-18 14:49, Lennart Poettering wrote:
> Regarding implementation: i think a simple solution could be taking inspiration how the "boot param" logic is implemented: when the shutdown is initiated logind should write out a quick file to /run. It would then be up to some grub supplied service to maybe read that during shutdown and do the right things... that way, logind doesn't need any plugin logic itself, which i'd very much prefer...

Having a .service check for a file under /run sounds reasonable,
I guess that file would be added to /lib/systemd/system/reboot.target.wants
and then would have something like:

ConditionPathExists=/run/systemd/shutdown/show_bootloader_menu

That sounds like a simple and easy to use interface, I like it :)

**Comment by poettering** [comment]
@jwrdegoede i filed a PR #10495 now, implementing what you are asking for. Would be thankful for a review.
