### ISSUE TITLE
Manage sysctl requirements between services

### ISSUE THREAD

**Issue by aledomu** [systemd/systemd#9902]
**Is your feature request related to a problem? Please describe.**
Sometimes I have to install some programs that need some sysctl tweaks for them to work or at least optimize. It would be nice if systemd could automatically manage this.

**Describe the solution you'd like**
A way to specify on unit files (just services?) the range of values that are required for the app/service to work or get optimized, so they can be mandatory or optional. Then systemd would warn if there is some conflict but the services can still run fine or just refuse to run if there is any hard requirement (at this point the question is how we decide which service to stop?).

I don't want to go deep into the details because I realize this might be difficult to plan/design, but if done right it may be a nice addition that enhances the portable services stuff.

**Describe alternatives you've considered**
Nothing comes to my mind.

**Comment by boucman** [comment]
isn't that what man:sysctl.d does ? If a package installs a drop-in  file there, does it do what you want ?

**Comment by aledomu** [comment]
Most of the time that's enough, but sometimes the problem comes when two services have conflicting requirements but they can be solved if you specify a range of values instead of a fixed value (or when deploying a portable service, although maybe there's already a mechanism for this that I don't know). It's somewhat the same problem as manually ordering the old initscript files.

**Comment by poettering** [comment]
well, sysctl is a messy interface, simply not designed with interdependencies or multiple writers in mnind, and every single sysctl exposes different semantics. systemd is not the place to work around messy interfaces really. We do provide basic sysctl.d support, but I am very sure we shouldn't be smarter than that, after all this would mean providing an individual IPC API for changing each and every sysctl, that adds the smarter logic (as daemons might want to adjust things dynamically), and all that sounds extremely hard to push for politically. Moreover if such a thing makes sense then it could better live in the kernel itself (i.e. the kernel should provide better apis that sysctl in the first place)

Either way, I am very sure this shouldn't be attempted by us. sysctl is basically a turd, and doing anything more than we do for it in userspace is polishing a turd, ultimately...

The in-kernel logic for various sysctls is really awful in most cases and very much not obvious. For example one of the most well known sysctl is probably /proc/sys/net/ipv4/ip_forward, but it propagates in such weird ways to the per-interface /proc/sys/net/ipv4/conf/XYZ/forwarding as well as to 
/proc/sys/net/ipv4/conf/all/forwarding and /proc/sys/net/ipv4/conf/default/forwarding that is a royal mess, nobody really groks anymore. Moreover the handling of the same tunable for ipv6 is completely different even, and not much better.

This all makes me very sure that sysctl is an interface that we should stay away as much as possible, and only apply minimal changes when we really must, and primarily consider it exclusive ownership of the admin...

I hope this makes some sense.

Closing. Sorry!

**Comment by aledomu** [comment]
> We do provide basic sysctl.d support, but I am very sure we shouldn't be smarter than that, after all this would mean providing an individual IPC API for changing each and every sysctl, that adds the smarter logic _**(as daemons might want to adjust things dynamically)**_.

I thought it could be enough with numerical ranges indicated in the `.service` file and some sort of priority system, but for dynamic adjustments... yeah, pretty much that. At best it would end up being a half-baked solution for just a few cases where it's useful mostly for optimization.

> Moreover if such a thing makes sense then it could better live in the kernel itself (i.e. the kernel should provide better apis that sysctl in the first place)

Completely agree. That's the _right_ way.

> Closing. Sorry!

Actually this was more a question about viability than a request, so nevermind. Thanks for clearing it up!
