### ISSUE TITLE
Symlinks are now installed as dangling symlinks instead of regular files....

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#9906]
meson master breaks systemd installations

https://github.com/mesonbuild/meson/issues/4069

./test/basic.target is now installed as a dangling symlink to a non-existant ../units/basic.target, instead of a regular file, this thus breaks running as installed tests.

Not sure if this is a meson bug/regression, or a meson feature and we need to change our sources instead....

**Comment by xnox** [comment]
I think all of these are affected:

```
./usr/lib/systemd/tests/testdata/timers.target
./usr/lib/systemd/tests/testdata/sysinit.target
./usr/lib/systemd/tests/testdata/sockets.target
./usr/lib/systemd/tests/testdata/shutdown.target
./usr/lib/systemd/tests/testdata/basic.target
./usr/lib/systemd/tests/testdata/test-path/sysinit.target
./usr/lib/systemd/tests/testdata/test-path/paths.target
./usr/lib/systemd/tests/testdata/test-path/path-modified.service
./usr/lib/systemd/tests/testdata/test-path/path-makedirectory.service
./usr/lib/systemd/tests/testdata/test-path/path-existsglob.service
./usr/lib/systemd/tests/testdata/test-path/path-exists.service
./usr/lib/systemd/tests/testdata/test-path/path-directorynotempty.service
./usr/lib/systemd/tests/testdata/test-path/path-changed.service
./usr/lib/systemd/tests/testdata/test-path/basic.target
```

**Comment by xnox** [comment]
This is a workaround i managed to come with.... but imho this issue is a regression in meson if i have to do this, cause this is very un-mesonic.

```
diff --git a/test/meson.build b/test/meson.build
index 826e684e59..4afa730e3e 100644
--- a/test/meson.build
+++ b/test/meson.build
@@ -192,15 +192,24 @@ if conf.get('ENABLE_RESOLVE') == 1
         '''.split()
 endif
 
+cp_cmd = 'cp @0@ $DESTDIR/@1@'
+
 if install_tests
         foreach file : test_data_files
                 subdir = file.split('/')[0]
                 if subdir == file
                         subdir = ''
                 endif
-
-                install_data(file,
-                             install_dir : testsdir + '/testdata/' + subdir)
+                # because install_data is broken, and instead of copying test
+                # files as real files into target dir it now copies them as
+                # dangling symlinks, if the source file is a symlink to another
+                # file in the tree
+                src = meson.current_source_dir() + '/' + file
+                target = testsdir + '/testdata/' + subdir
+                meson.add_install_script('sh', '-c',
+                                         mkdir_p.format(target))
+                meson.add_install_script('sh', '-c',
+                                         cp_cmd.format(src, target))
         endforeach
 endif
 

```

**Comment by xnox** [comment]
so upstream fixed up regression, but they want to change the behaviour in the future.

Can we somehow drop the symlinks in the source tree? and start copying files around into the build tree? or like at least install from a real file -> target, rather than the symlink -> target?

**Comment by yuwata** [comment]
It seems that the meson change is reverted. Is it ok to close this?

**Comment by xnox** [comment]
@yuwata no, because future meson will again start copying those things as symlinks. It has been reverted, and changed to a warning / depreciation notice.

We should not use files which are symlinks as "sources" if we want to install things into target as real files. So maybe we should copy files from units dir into built-tree and then install. Or use the real source to install from. As far as I can see there is no flag in meson to say "resolve and copy this thing as a regular file, even though it is a symlink in my source tree, to somewhere else".

**Comment by yuwata** [comment]
Indeed. I found the following warning:
```
Warning: trying to copy a symlink that points to a file. This will copy the file,
but this will be changed in a future version of Meson to copy the symlink as is. Please update your
build definitions so that it will not break when the change happens.
```
