### ISSUE TITLE
IOReadBandwidthMax with path says "Path ... is not a device file in /dev"

### ISSUE THREAD

**Issue by rwmjones** [systemd/systemd#9908]
**systemd version the issue has been seen with**
> systemd-238-9.git0e0aa59.fc28.x86_64

**Used distribution**
 > Fedora

**Expected behaviour you didn't see**
 > IOReadBandwidthMax is supposed to work with a path, but does not.

**Unexpected behaviour you saw**
 > An error instead of working

**Steps to reproduce the problem**

$ systemd-run --user --pipe -p IOReadBandwidthMax="/var/tmp 1K" echo hello
Failed to start transient service unit: Path IOReadBandwidthMax specified in /var/tmp= is not a device file in /dev

**Comment by yuwata** [comment]
I think this is already fixed by the commit 9d5e9b4add4d22dedc9d3286bfae9687a2a7c641, which is included in v239.
