### ISSUE TITLE
udev: ID_FS_TYPE missing for CD/DVD

### ISSUE THREAD

**Issue by maggu2810** [systemd/systemd#991]
The ID_FS_TYPE key is not set for sr0 (CD/DVD drive) on my system.

<pre>ls /dev/sd[a-z][0-9] /dev/sr[0-9] | while read DEV; do udevadm info -q all -n ${DEV}; done | grep -e DEVNAME -e ID_FS_TYPE</pre>

It is set for my hard discs:

<pre>
E: DEVNAME=/dev/sda1
E: ID_FS_TYPE=vfat

E: DEVNAME=/dev/sda2
E: ID_FS_TYPE=swap

E: DEVNAME=/dev/sda3
E: ID_FS_TYPE=btrfs

E: DEVNAME=/dev/sda4
E: ID_FS_TYPE=crypto_LUKS
</pre>

But missing for my optical drive.

<pre>
E: DEVNAME=/dev/sr0
</pre>

**Comment by poettering** [comment]
is there a CD in the drive?

What does this print? `udevadm test-builtin blkid /sys/class/block/sr0`?

**Comment by maggu2810** [comment]
The CD has been in the drive.
I am really sure. ;-)

But now (sure, a lot of reboots have been done) it is working.
Same drive, same optical disc.

Sorry, will report again if I could reproduce the situation.

Will use "udevadm test-builtin blkid ..." then.
