### ISSUE TITLE
RFE: After= and Requires= for .network files

### ISSUE THREAD

**Issue by aTanW** [systemd/systemd#9918]
Simple example: bunch of GRE and IPIP interfaces, all of them going over IPSec. In current situation here is no way to fire up tunnels **after** IPSec links are set up using only systemd configuration.

As for me, it is desirable to include After= and Requires= clauses to systemd.network files with functionality like in unit files.

I understand, that subsystems are different, but can systemd-networkd be "client" of systemd? :-)

**Comment by keszybz** [comment]
A different approach has been implemented: a request queue (added in 19d9a5adf0c1a6b5a243eea0390f6f6526d569de) is used to execute various bits of configuration only after the prerequisites have been met. So instead of explicit ordering, the ordering is managed automatically by networkd.

I'm not sure if GRE and IPIP tunnels are handled using the request queue already.

@yuwata?

**Comment by yuwata** [comment]
@aTanW Could you provide more detailed example? How do you configure IPSec?

**Comment by aTanW** [comment]
IPSec in kernel configured by IKE daemon, that fires up as a normal system service by systemd. It establishes SAs with peers, and after that I bring up GRE interfaces with that peers in IKEd's event scripts with help of "ip" tool.
It is the "right way" to have all network configuration in one place, here it is under systemd-networkd control. But how to hold configuraion of GREs until IKE daemon startup, or, even, until IKEd's event script gets executed, where we can send some signal to systemd-networkd?

**Comment by poettering** [comment]
So I guess we have this now via:

```
Requires=systemd-wait-online@<iface>.service
After=systemd-wait-online@<iface>.service
```

**Comment by aTanW** [comment]
Sorry, but there still no way to bring up interfaces after (depending on) (successful) service startup with systemd-networkd functionality, i.e. using only systemd-networkd configs for them.
