### ISSUE TITLE
Overridden unit in /etc not used when .wants/ symlink points to /usr/lib

### ISSUE THREAD

**Issue by bernhardschmidt** [systemd/systemd#9921]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > Debian Unstable

**Expected behaviour you didn't see**
 > openvpn@.service in /etc/systemd/system, but a generator links an instance in .wants to /lib/systemd/system. I would have expected the unit in /etc to be used anyway.

**Unexpected behaviour you saw**
 > The old unit in /lib used for the instance pulled in by the generator, but the one in /etc used for other instances

**Steps to reproduce the problem**

See https://lists.freedesktop.org/archives/systemd-devel/2018-August/041196.html

I've been sent here by the great systemd maintainers in Debian for
clarification. The situation was observed on systemd v239 on Debian
unstable.

On src:openvpn we have recently gotten a bug report about local
modifications of the openvpn at .service file in /etc being ignored when
the instance is started by the systemd generator, because the generator
unconditionally links to the file in /lib/systemd and does not check for
the presence of a modified file in /etc/systemd

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905392

My first instinct was that this could not be true, as it would be the
complete opposite to my expectations as regular systemd user, where
overriding something in /etc (either by copying and modifying the
.service file, or by adding dropins in .service.d) is adhered to by all
systemd management commands. But I can reproduce this in a sid container
(please ignore the activating/failed status below, openvpn in the
container could not create a tun device, just look at the path to the
unit and to the ExecStart line

```
/etc/openvpn# openvpn --genkey --secret static.key
/etc/openvpn# head test1.conf
dev tun
ifconfig 10.1.0.1 10.1.0.2
secret static.key

# cp /lib/systemd/system/openvpn\@.service /etc/systemd/system
# sed -ri 's:ExecStart=.+$:ExecStart=/bin/sleep 10:'
/etc/systemd/system/openvpn\@.service

# reboot

# systemctl status openvpn at test1.service
● openvpn at test1.service - OpenVPN connection to test1
   Loaded: loaded (/lib/systemd/system/openvpn at .service;
enabled-runtime; vendor preset: enabled)
[...]
  Process: 231 ExecStart=/usr/sbin/openvpn --daemon ovpn-test1 --status
/run/openvpn/test1.status 10 --cd /etc/openvpn --config
/etc/openvpn/test1.conf --writepid /run/openvpn/test1.pid (code=exited,
status=1/
 Main PID: 231 (code=exited, status=1/FAILURE)

# systemctl start openvpn at test2.service
# systemctl status openvpn at test2.service
● openvpn at test2.service - OpenVPN connection to test2
   Loaded: loaded (/etc/systemd/system/openvpn at .service; disabled;
vendor preset: enabled)
  Process: 334 ExecStart=/bin/sleep 10 (code=exited, status=0/SUCCESS)
```

So openvpn at test1.service (that is .wants by the generator) is using the
shipped configuration, but any other instance is using the version in
/etc as expected.

```
/run/systemd/generator/openvpn.service.wants# ls -la
lrwxrwxrwx 1 root root  36 Aug 13 23:54 openvpn at test1.service ->
/lib/systemd/system/openvpn at .service
```

The proposed fix indeed changes this by checking the existence of the
file in /etc first and symlinking to this, but I would not have expected
the logic for overriding configuration in /etc necessary to be
implemented in each and every generator.

Are my expectations wrong? Is this a bug somewhere?

Note that adding something to
/etc/systemd/system/openvpn at .service.d/override.conf IS taken into account

```
   Loaded: loaded (/lib/systemd/system/openvpn at .service;
enabled-runtime; vendor preset: enabled)
  Drop-In: /etc/systemd/system/openvpn at .service.d
           └─override.conf
```

It's just the whole copy-and-edit override that doesn't work.

**Comment by poettering** [comment]
See my reply here:

https://lists.freedesktop.org/archives/systemd-devel/2018-September/041317.html

**Comment by arvidjaar** [comment]
@keszybz 
But the statement was that unit full file path does not matter as long as unit exists in normal search path - i.e. full file path is ignored anyway.

Actually I vaguely remember that links to links were actively rejected, so behavior is intentional.

Is there any way to show the final unit definition such link resolves to? That would help to reduce confusion.

**Comment by keszybz** [comment]
I don't understand. The target of the symlink is **not** ignored in the snippet I pasted. The two units clearly show different `FragmentPath`.

**Comment by arvidjaar** [comment]
I cannot reproduce it in systemd 237 (openSUSE Tumbleweed) so it must be some recent regression:

```
10:/usr/lib/systemd/system # vi template@.service
10:/usr/lib/systemd/system # systemctl enable template@1.service
Created symlink /etc/systemd/system/parent.target.wants/template@1.service → /usr/lib/systemd/system/template@.service.
10:/usr/lib/systemd/system # cp template@.service /etc/systemd/system
10:/usr/lib/systemd/system # vi /etc/systemd/system/template@.service 
10:/usr/lib/systemd/system # systemctl enable template@2.service
Created symlink /etc/systemd/system/parent.target.wants/template@2.service → /etc/systemd/system/template@.service.
10:/usr/lib/systemd/system # systemctl show -p FragmentPath template@1.service template@2.service template@3.service
FragmentPath=/etc/systemd/system/template@.service

FragmentPath=/etc/systemd/system/template@.service

FragmentPath=/etc/systemd/system/template@.service
10:/usr/lib/systemd/system # ll /etc/systemd/system/parent.target.wants/
total 12
lrwxrwxrwx 1 root root 37 Sep 15 14:45 child.service -> /usr/lib/systemd/system/child.service
lrwxrwxrwx 1 root root 41 Sep 15 14:48 template@1.service -> /usr/lib/systemd/system/template@.service
lrwxrwxrwx 1 root root 37 Sep 15 14:49 template@2.service -> /etc/systemd/system/template@.service
10:/usr/lib/systemd/system # 
```
