### ISSUE TITLE
error: storage size of ‘sx’ isn’t known

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9931]
Bit of history I'm running the commands in the LFS manual detailed here: http://www.linuxfromscratch.org/blfs/view/systemd/general/systemd.html

Output from lfs build: (running ninja)

[1/1077] Compiling C object 'src/basic/basic@sta/xattr-util.c.o'.
FAILED: src/basic/basic@sta/xattr-util.c.o
cc  -Isrc/basic/basic@sta -Isrc/basic -I../src/basic -I. -I../ -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-network -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-device -I../src/libsystemd/sd-bus -Isrc/core -I../src/core -Isrc/libudev -I../src/libudev -Isrc/udev -I../src/udev -Isrc/login -I../src/login -I../src/time-wait-sync -Isrc/timesync -I../src/timesync -Isrc/resolve -I../src/resolve -Isrc/nspawn -I../src/nspawn -Isrc/journal-remote -I../src/journal-remote -Isrc/journal -I../src/journal -Isrc/systemd -I../src/systemd -Isrc/shared -I../src/shared -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/libmount -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -include config.h -fPIC -pthread -fvisibility=default -MMD -MQ 'src/basic/basic@sta/xattr-util.c.o' -MF 'src/basic/basic@sta/xattr-util.c.o.d' -o 'src/basic/basic@sta/xattr-util.c.o' -c ../src/basic/xattr-util.c
../src/basic/xattr-util.c: In function ‘fd_getcrtime_at’:
../src/basic/xattr-util.c:145:22: error: storage size of ‘sx’ isn’t known
         struct_statx sx;
                      ^~
../src/basic/xattr-util.c:145:22: warning: unused variable ‘sx’ [-Wunused-variable]
[6/1077] Compiling C object 'src/libsystemd/systemd_static@sta/sd-netlink_rtnl-message.c.o'.
ninja: build stopped: subcommand failed.

Could not find the definition of the struct in any of the source.. 

line 143 of this https://github.com/systemd/systemd/blob/master/src/basic/xattr-util.c is producing this error "error: storage size of ‘sx’ isn’t known" - any
                ideas how i can fix this?

**Comment by yuwata** [comment]
Could you provide the version of glibc and systemd?

**Comment by yuwata** [comment]
`struct_statx` is defined in src/basic/missing_syscall.h, and it is already included by xattra-util.c through missing.h. So, I guess the kernel header you use does not provide `struct statx`. Please check kernel version.

**Comment by js3263854** [comment]
Linux 4.18.0 #1 SMP Tue Aug 21 12:36:08 AEST 2018 x86_64 GNU/Linux
systemd-239
glibc-2.27

**Comment by js3263854** [comment]
OK I think its because of the patch provided and different glibc version (my bad)

**Comment by yuwata** [comment]
Could you provide WANT_LINUX_STAT_H entry in config.h in build directory?

**Comment by yuwata** [comment]
Ah, I see, LFS provides a patch for statx. The patch seems not necessary for recent snapshot. See 75720bff62a84896e9a0654afc7cf9408cf89a38 and 9c869d08d82c73f62ab3527567858ce4b0cf1257.

**Comment by yuwata** [comment]
Please re-open this issue if the commits I mentioned does not work.
