### ISSUE TITLE
CAP_LINUX_IMMUTABLE does not seem to work

### ISSUE THREAD

**Issue by aaronovz1** [systemd/systemd#9937]
**systemd version the issue has been seen with**
237

**Used distribution**
Yocto Sumo

**Expected behaviour you didn't see**
Able to remove FS_IMMUTABLE_FL flag using FS_IOC_SETFLAGS with a service that has CapabilityBoundingSet and AmbientCapabilities set to CAP_LINUX_IMMUTABLE. The file with the immutable flag is an EFI variable under /sys/firmware/efi/efivars.

**Unexpected behaviour you saw**
Permission denied error

**Steps to reproduce the problem**
The following code is used to try remove the immutable flag so that the EFI variable can be updated by an application:
```
bool removeImmutableFlag(const std::string& variable_path)
{
    int32 fd = open(variable_path.c_str(), O_RDONLY);

    if (fd < 0)
    {
        return false;
    }

    unsigned long current_attrs;

    if (ioctl(fd, FS_IOC_GETFLAGS, &current_attrs) == -1)
    {
        close(fd);
        return false;
    }

    if (!(current_attrs & FS_IMMUTABLE_FL))
    {
        return true;
    }

    unsigned long mutable_attrs = 0;

    mutable_attrs = current_attrs & ~(unsigned long)FS_IMMUTABLE_FL;

    close(fd);

    fd = open(variable_path.c_str(), O_RDONLY);

    if (fd < 0)
    {
        return false;
    }

    if (ioctl(fd, FS_IOC_SETFLAGS, &mutable_attrs) == -1)
    {
        close(fd);
        return false;
    }

    close(fd);

    return true;
}
```

**Comment by aaronovz1** [comment]
No it does not succeed in either cases. I need to add the capabilities to the unit file so the service has permissions to remove the immutable flag. It does not work though. I have used other capabilities flags on other services and they do work (ie. CAP_NET_BIND_SERVICE).

**Comment by sourcejedi** [comment]
If it does not succeed running without the `*Cap*` directives *and running as the effective default `User=root`*, then there is nothing `systemd` can reasonably change to make it succeed.  You did not show me the full unit file, and based on my fuzzy understanding of capabilities I had guessed that you were running it as `User=root`.  Apologies for any misunderstanding.  Please clarify the issue report.

Alternatively, you could perhaps reproduce an error when running a simple test service with `ExecStart=/usr/bin/chattr -i`, then inspect the provided capabilities using `ExecStart=/usr/bin/capsh --print`. If they are different than they should be, that would make a good issue report.

**Comment by aaronovz1** [comment]
The service is not run as root, if it were run as root I wouldn't need to set capabilities. The entire reason for needing the caps is to prevent running a service with root privileges, but allow one small piece of escalated privileges. In this case I need to be able to remove the immutable flag temporarily on an EFI variable so I can update its contents. Using `chattr -i` as root on the command line works as expected, but again that requires being root user.

This is a simplified version of my unit file:
```
[Unit]
Description=MyService
Requires=network.target
After=network.target dbus.service gpsd.service ModemManager.service NetworkManager.service
RequiresMountsFor=/media/sdcard

[Service]
Type=notify
NotifyAccess=main
ExecStart=/opt/myapp
WatchdogSec=30s
Restart=on-failure
StartLimitInterval=5min
StartLimitBurst=4
StartLimitAction=none
User=bob
Group=bob
TimeoutStartSec=30
RestartForceExitStatus=1
WorkingDirectory=/opt
CapabilityBoundingSet=CAP_LINUX_IMMUTABLE
AmbientCapabilities=CAP_LINUX_IMMUTABLE

[Install]
WantedBy=multi-user.target
```

**Comment by sourcejedi** [comment]
If the suggested `capsh` test is inconvenient, can you show `/proc/$PID/status` for the running service process? I think we can interpret it with `capsh --decode` regardless of the system architecture.

Is it possible to test `User=root`, `ExecStart=/usr/bin/chattr +i /path/to/a/file` or similar, with the rest of the settings the same?  That would simplify a couple of possible factors.

It is possible for operations to be denied based on SELinux context. It is possible for a root command line to run in a different SELinux context to systemd services. SELinux was (is?) available for Yocto. https://bugzilla.yoctoproject.org/show_bug.cgi?id=1609

**Comment by aaronovz1** [comment]
SELinux is not being used.

Here 's is the output from /proc/$PID/status:
```
Name:	Main
State:	S (sleeping)
Tgid:	987
Ngid:	0
Pid:	987
PPid:	1
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	128
Groups:	20 29 44 46 70 995 998 1000 
NStgid:	987
NSpid:	987
NSpgid:	987
NSsid:	987
VmPeak:	 3353288 kB
VmSize:	 3353288 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  136040 kB
VmRSS:	  132900 kB
VmData:	 2950964 kB
VmStk:	     560 kB
VmExe:	   61580 kB
VmLib:	  153920 kB
VmPTE:	    1292 kB
VmPMD:	      24 kB
VmSwap:	       0 kB
Threads:	104
SigQ:	0/7374
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000001000
SigCgt:	0000000180000002
CapInh:	0000000000000200
CapPrm:	0000000000000200
CapEff:	0000000000000200
CapBnd:	0000000000000200
CapAmb:	0000000000000200
Seccomp:	0
Cpus_allowed:	f
Cpus_allowed_list:	0-3
Mems_allowed:	1
Mems_allowed_list:	0
voluntary_ctxt_switches:	525
nonvoluntary_ctxt_switches:	235

```

Here is the capsh output for the non-root user:
```
Current: =
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=1000(dss)
gid=1000(dss)
groups=20(dialout),29(audio),44(video),46(plugdev),70(shutdown),995(systemd-journal),998(netdev),1000(dss)
```

Thanks

**Comment by sourcejedi** [comment]
> CapEff:	0000000000000200

    $ capsh --decode=0000000000000200
    0x0000000000000200=cap_linux_immutable

So the capability is passed down as desired.

Then I would expect this is the only problem:

> In order to change the inode flags of a file using the
       FS_IOC_SETFLAGS operation, the effective user ID of the caller must
       match the owner of the file, or the caller must have the CAP_FOWNER
       capability.

**Comment by aaronovz1** [comment]
Ugh can't believe I missed that bit of documentation! That resolved the problem. Thank you!
