### ISSUE TITLE
ENOMEM when trying to filter different system call sets with different error numbers

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#9939]
**systemd version the issue has been seen with**
v239, v237

**Used distribution**
 Arch, Debian

**Expected behaviour you didn't see**
I was trying to debug a `SystemCallFilter` and thought assigning different error numbers to the different system call sets in the filter would be a good way to discover which system call was actually tripping up my service (hoping that it would log the returned errno to the journal).

**Unexpected behaviour you saw**
Bizarrely, systemd reported an error “cannot allocate memory” when restarting the service, and this error remains visible in the `systemctl status` output as well (the service seems to be running, but the “loaded” status is “error (Reason: Cannot allocate memory)”). Both of the systems I’ve reproduced this on have plenty of free memory.

**Steps to reproduce the problem**
```sh
sudo systemd-run -p 'SystemCallFilter=~@cpu-emulation:EPERM @debug:ENOENT' true
sudo systemd-run -p 'SystemCallFilter=~@clock:EPERM @privileged:ENOENT' true
```
The particular error numbers don’t matter (`EPERM` and `ENOENT` are 1 and 2, but you can also use 42 and 1337 if you feel like it), but assigning the same error number to both sets makes the error go away. This also doesn’t seem to be tied to any particular system call set, but some combinations will produce the same error and other won’t.

I tried to debug this, but didn’t get very far. Even at `systemd-analyze log-level debug`, these two log messages are directly consecutive:

```
systemd[1]: run-raf052eefe10b4d00b21b5803452ffa08.service: Failed to load configuration: No such file or directory
systemd[1]: Sent message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=org.freedesktop.DBus.Error.NoMemory error-message=Cannot allocate memory
```

The first is normal for `systemd-run` services as far as I can tell, and the second already signals the error. `strace`ing PID1 also doesn’t turn up anything interesting. The only conclusion I can draw from that is that the error *probably* doesn’t happen when actually applying the seccomp filter, because that’s the very very last step in `exec_child`, and if we actually got that far I would expect to see a lot more debug log messages. So I assume this error happens when *parsing* the directive. Probably.

**Comment by lucaswerkmeister** [comment]
I managed to debug this with `gdb` in a container and traced it to the following block:

https://github.com/systemd/systemd/blob/56663345dfb1dd3ff23cac5fbc955aba54477efa/src/shared/seccomp-util.c#L1055-L1062

This assumes that OOM is the only reason why the `hashmap_put` might fail, but in fact it returned `-17` = `-EEXIST`, which `strerror`s to “File exists” but here means “entry already in hashmap with different value”.

It turns out that on my system (AMD64), `seccomp_syscall_resolve_name` returns the same ID (-10191) for two different syscalls: `switch_endian`, which is in `@cpu-emulation`, and `sys_debug_setcontext`, which is in `@debug`. Both are architecture-specific, but beyond that I can’t make sense of seccomp’s ID – presumably the fact that it’s negative is meant to indicate that the syscall is not available on the current architecture, but the two syscalls do not have the same system call number on their respective architectures as far as I can tell (`__NR_switch_endian` is 363, `__NR_sys_debug_setcontext` is 256), and in fact they’re both specific to the *same* architecture, PowerPC.

Anyways… two possible fixes (non-exclusive):

1. Don’t even bother putting fake negative syscall numbers into any hashmap. (Since we’re talking about parse-time behavior here, this means you won’t be able to see these discarded syscalls in `systemctl show`, but as their IDs aren’t unique anyways, the current behavior isn’t useful either.)

2. Don’t treat `EEXIST` or other errors as `ENOMEM`.

I’ll submit a pull request.

---

Side note – debugging this required some degree of extra trickery that was not laid out in the `HACKING.md` document, so a `DEBUGGING.md` would be useful IMHO (see also [here](https://github.com/systemd/systemd/blob/56663345dfb1dd3ff23cac5fbc955aba54477efa/TODO#L205) and [here](https://twitter.com/FiloSottile/status/1033103575977668608)). I’ll try to submit a pull request for that as well, but if I forget, someone else please do it :)

**Comment by lucaswerkmeister** [comment]
> beyond that I can’t make sense of seccomp’s ID

Apparently these are called “pseudo syscall numbers”, and if I read [`seccomp.h.in`](https://github.com/seccomp/libseccomp/blob/8ad3638ea9023c3948976dfadebd1554380a31c9/include/seccomp.h.in) correctly, there are only two pairs where syscalls share the same pseudo number – `__PNR_spu_run = __PNR_subpage_prot = -10189` and `__PNR_sys_debug_setcontext = __PNR_switch_endian = -10191`.

Is this just a bug in libseccomp, where they accidentally assigend the same ID multiple times, perhaps due to merge mixups or whatever? (I suppose it doesn’t really matter for us, since we’ll still have to work around it, but perhaps someone with more understanding of the subject would like to report it to them.)

**Comment by lucaswerkmeister** [comment]
And by the way, my second reproducer –
```sh
sudo systemd-run -p 'SystemCallFilter=~@clock:EPERM @privileged:ENOENT' true
```
– is not libseccomp’s fault, because `@privileged` includes `@clock`. That still raises the question of how to tell the user that they requested different error numbers for the same system calls – “File exists” isn’t any better than “Cannot allocate memory” as a message for this case.

**Comment by lucaswerkmeister** [comment]
Pull request submitted, see #9942. I also reported the issue upstream at seccomp/libseccomp#125, because after looking a bit more into these pseudo syscall numbers, I’m pretty sure this is a bug.

**Comment by keszybz** [comment]
Fixed in https://github.com/systemd/systemd/commit/a5404992cc7724ebf7572a0aa89d9fdb26ce0b62.

**Comment by lucaswerkmeister** [comment]
A final postscript:

> I was trying to debug a `SystemCallFilter` and thought assigning different error numbers to the different system call sets in the filter would be a good way to discover which system call was actually tripping up my service (hoping that it would log the returned errno to the journal).

It turns out the information I needed was in the journal all along, I was just blind, apparently.

> audit[7053]: SECCOMP auid=4294967295 uid=998 gid=998 ses=4294967295 pid=7053 comm="pyzor" exe="/usr/bin/python2.7" sig=31 arch=c000003e **syscall=141** compat=0 ip=0x7f085ec6abf7 code=0x0

(In fact it’s logged twice, once with `_TRANSPORT=audit` and once with `_TRANSPORT=kernel`.) You just need to turn the syscall number (141) back into a name (`setpriority` on amd64, consult the kernel sources). Perhaps this helps someone else as well…
