### ISSUE TITLE
systemd-networkd:  Ignoring foo.netdev.d/*.conf

### ISSUE THREAD

**Issue by ko-zu** [systemd/systemd#9940]
**systemd version the issue has been seen with**
> systemd 239
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

also confirmed with systemd 237 on ubuntu bionic

**Used distribution**
 > archlinux

**Expected behaviour you didn't see**
 > foo.netdev.d/override.conf overrides respective foo.netdev

**Unexpected behaviour you saw**
 > foo.netdev.d and its contents were ignored
for older versiion (systemd 237) systemd-networkd with ` SYSTEMD_LOG_LEVEL=debug` emit something like
> Aug 25 20:51:50 uw3 systemd-networkd[2631]: Ignoring /etc/systemd/network/wg0.netdev.d, because it's not a regular file with suffix .netdev

**Steps to reproduce the problem**

Setup .netdev and netdev.d overrides.
```
# cat /etc/systemd/network/dummy-test.netdev
[NetDev]
Name=dummy-test
Kind=dummy
MACAddress=11:11:11:11:11:11

# cat /etc/systemd/network/dummy-test.netdev.d/override.conf
[NetDev]
MACAddress=22:22:22:22:22:22
```
then 
```
# systemctl restart systemd-networkd
# ip link show dummy-test
3: dummy-test: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 11:11:11:11:11:11 brd ff:ff:ff:ff:ff:ff
```

**Comment by yuwata** [comment]
Fix is waiting in #10928.
