### ISSUE TITLE
[systemd-resolved] allow for domain-specific upstream DNS

### ISSUE THREAD

**Issue by Yujah** [systemd/systemd#9944]
Ubuntu 18.04 / Mint 19 switched to systemd-resolved from dnsmasq and lost a feature in the process. I have a private domain registered with OpenNIC under its .dyn TLD and could with dnsmasq specify the OpenNIC servers as e.g. "server=/dyn/185.121.177.177" -- generally, as "[/domain1[/domain2[...]]]server" -- so as to have the server be contacted for the mentioned domains only.

With systemd-resolved I have now added OpenNIC's servers to /etc/systemd/resolve.con:DNS= but although it's a minor issue can not do likewise. Practically it's mostly relevant in the context of typo's I guess, but the dnsmasq feature does make general sense. Maybe something for systemd-resolved to consider?

**Comment by antoinefaure** [comment]
This demand is similar to this one : https://github.com/systemd/systemd/issues/5573
Such a feature would be greatly appreciated IMHO

**Comment by yrro** [comment]
I think #11050 will do what you want?

**Comment by poettering** [comment]
Closing as duplicate of #5573
