### ISSUE TITLE
switch_root() doesn't reliably log errors

### ISSUE THREAD

**Issue by jameysharp** [systemd/systemd#9963]
**systemd version the issue has been seen with**
> 238

**Used distribution**
 > NixOS

**Expected behaviour you didn't see**
 > I created a custom initrd and a couple different squashfs root filesystems to experiment with. I configured the initrd to boot with systemd and used the example units that systemd distributes, symlinking default.target to initrd.target. I didn't create directories for the /proc, /dev, /sys, and /run mounts in the root filesystem, which caused `switch_root()` to fail.
>
> I'd have expected to see error messages from switch_root failing, like these:
>
> ```
> Failed to mount /sys to /sysroot/sys: No such file or directory
> Failed to switch root, trying to continue: %m
> ```

**Unexpected behaviour you saw**
 > Even when passing `debug` on the kernel command line, these were the only error messages I saw:
>
> ```
> [  !!  ] Failed to execute /sbin/init
> [  155.046531] systemd[1]: No /sbin/init, trying fallback
> [  155.046987] systemd[1]: Failed to execute /bin/sh, giving up: No such file or directory
> [!!!!!!] Failed to execute fallback shell, freezing.
> ```
>
> Because switch_root failed, systemd tried to run /sbin/init from the initrd instead of from /sysroot, which also seems like it might be a bug, but at any rate the lack of earlier error messages meant I spent way too long flailing at the wrong problem.
>
> I only finally got the expected error message about failing to move the /sys mount when I switched from running
>
> ```
> systemctl switch-root /sysroot
> ```
>
> to running
>
> ```
> systemctl switch-root /sysroot /sbin/init
> ```
>
> but looking at the code I don't see any reason why that should have made a difference. And I have never seen the "Failed to switch root, trying to continue" message that I see in the source code.

**Comment by poettering** [comment]
hmm, we can certainly always improve logging output. 

That said, is this with debug logging on or without (i.e. systemd.log_level=debug on the kernel cmdline)?

**Comment by jameysharp** [comment]
As I recall, I tried `systemd.log_level=debug` on the kernel command line, and when that didn't help I tried just `debug`. According to my notes above, the output I included in this issue is with `debug` by itself.

**Comment by poettering** [comment]
With 7c764d45997721705e43ac66fbb5a56747d00d40 in particular we should have pretty accurate logging these days. Assuming this is solved.
