### ISSUE TITLE
DHCPv6 PD over PPP connections

### ISSUE THREAD

**Issue by freswa** [systemd/systemd#9971]
**Is your feature request related to a problem? Please describe.**
It's related to #7582 and #481. While the DHCPv6 PD support has been pulled recently (tm) and works pretty well over non-ppp networks, it's not usable over ppp connections since the IPv4 and IPv6 information are transmitted within the PPP handshake and applied to the interface by pppd.
Whenever systemd-networkd is activated for the ppp interface to allow DHCPv6 PD it automatically removes assigned IPv4 addresses and routes.

**Describe the solution you'd like**
I'd like to be able to run DHCPv6 PD over ppp interfaces either by some minor integration of pppd into systemd (to catch the information needed to configure the interface correctly from the ppp handshake) or by implementing ppp completely.

**Describe alternatives you've considered**
I don't really see alternatives here. Maybe switching to NetworkManager or do the IPv6 PD by some legacy software? :-(

**Comment by freswa** [comment]
I looked into the patch @teg created which is pretty basic, but I'd like to push this forward since ppp is a big thing at least for German DSL providers and also because I'd like to try systemd development.
So what kind of implementation would be acceptable for you? According to #481 we don't want to have PPP support in systemd.
So would an adapter to pppd be a better fit? @poettering

**Comment by pfl** [comment]
In issue #9745 @vanaf has enabled DHCPv6 prefix delegation via an upstream PPP connection. Can this issue be solved following @vanaf's setup?

**Comment by vanaf** [comment]
I'am using fedora network-scripts for ppp connections. All other connections are managed by networkd. 

Here is my networkd config for ppp connections:

```
[van@rpi3_plus ~]$ cat /etc/systemd/network/ppp.network 
[Match]
Type=ppp

[Network]
DHCP=ipv6
IPv6AcceptRA=yes

[DHCP]
CriticalConnection=yes
ForceDHCPv6PDOtherInformation=yes
```

**Comment by freswa** [comment]
Thanks @vanaf.
So with CriticalConnection=yes it's possible to run DHCPv6 over ppp. Great :+1: 
But I don't get a response to my DHCPv6 request on the ppp connection with networkd. Though networkd-dhcpv6 works perfectly with my cableprovider.

To get a DHCPv6 response I need to use WIDE-DHCPv6 for the ppp connection.
I tried to set and unset ForceDHCPv6PDOtherInformation but no luck. Will compare DHCPv6 requests to get an idea what's wrong.

**Comment by pfl** [comment]
Not getting any prefixes may also be due to #10257.

**Comment by freswa** [comment]
I just found the time to create the dump. Found out DHCPv6 works with v242. Will reopen if problem occurs again.
