### ISSUE TITLE
system environment generator for existing env requires a reboot to take effect

### ISSUE THREAD

**Issue by mvo5** [systemd/systemd#9972]
**systemd version the issue has been seen with**
> 237 but it was also reproduced on master

**Used distribution**
 > Ubuntu 18.04 but also tested it on fedora-28

**Expected behaviour you didn't see**
 > I created a system environment generator that modifies PATH. After installing it I did a daemon-reload and also a daemon-reexec but subsequent runs of "systemd-run --unit testenv env" would only show the original PATH. Adding new environments did work however. After a full reboot I got my modified path. To reproduce I created:
```
#!/bin/sh

set -e

if [ "$(id -u)" != "0" ]; then
    echo "please run this as root"
    exit 1
fi

GENERATOR="/usr/lib/systemd/system-environment-generators/9999-test.sh"

echo "Install systemd-environment-generator and testing PATH handling with it"
mkdir -p "$(dirname $GENERATOR)"
cat > "$GENERATOR"<<'EOF'
#!/bin/sh
echo "PATH=$PATH:/foobar"
echo "OTHER_ENV=$PATH:/canary"
EOF
chmod +x "$GENERATOR"

echo "Reloading systemd"
systemctl daemon-reexec

echo "Running test env"
systemd-run --unit testenv env
journalctl -u testenv | grep -E '(PATH|OTHER_ENV)'

echo "Cleaning up"
rm -f "$GENERATOR"
```
> Running this yielded an unmodified PATH but OTHER_ENV was fine.

**Unexpected behaviour you saw**
 > That a reload or reexec would pick up the changes. Or a documentation update that explains that a reboot is required.

Poking a bit and discussing with @xnox it looks like manager_reload() serializes the state, runs the environment generators and then de-serializes the state. It looks like this de-serialization overrides the results from running the environment generators. So either the generators need to run later or again after the state got de-serialized. I will play with this theory a bit.

**Comment by poettering** [comment]
yupp, looks fishy and should really be fixed i guess

**Comment by keszybz** [comment]
A generator needs to take care to filter out duplicate values. This is true even when the generator is started a single time, e.g. if it appends something, it needs to check if that value is not already present in the environment. Generators should be idempotent. We probably need to clarify that in the documentation.

**Comment by poettering** [comment]
Hmm, I wonder what the right approach here is. i.e. we have env vars from at least six sources:

1. configured with `DefaultEnvironment=` in /etc/systemd/system.conf
2. passed in from the kernel cmdline with `systemd.setenv=`
3. our own bits, i.e. PATH and locale settings
4. the stuff from the environment generators
5. the serialization of a previous run
6. whatever the user set during runtime with "systemctl set-environment"

Currently they are applied in the above order, and this means environment generator can override 1-3 and get overriden by 5-6. Moreover, changes accumulate forever, as anything set will be serialized forever, and only gets flushed out when it is explicitly requested with "systemctl unset-environment"... THis is quite ugly I think... Moreover, stuff unset with "systemctl unset-environment" will be set again after a reload.

I have the suspicion that we should track things in three separate env blocks: the stuff from 1-3 in one, then the stuff from 4, and finally the stuff from 6. And only the stuff from 6 gets serialized/deserialized. The stuff from 1-4 can be (and is already) regenerated in all reload cycles. 

Moreover I figure we should probably refuse "systemctl unset-environment" on variables that are set by anything other than "systemctl set-environment" (or its serialization), as unsetting this would not survive a reload anyway and thus would be quite confusing.

We should do all that probably in a fashion that is invisble to the client, i.e. that even though we store the env blocks separately they are merged transparently whenever the user gets to see them.

**Comment by poettering** [comment]
A fix along the lines described above is now pending in #10594
