### ISSUE TITLE
Fedora CI seems to have been broken for a couple days

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9978]
In every PR I have taken a look at this week (https://github.com/systemd/systemd/pull/9969, https://github.com/systemd/systemd/pull/9974, https://github.com/systemd/systemd/pull/9957 and some more) Fedora CI failed with the "internal error". The links in the PRs point to 404 pages like http://38.145.33.116/systemd-pr/a7/8f/a78fe281601c0cb0bb020c190fb46d149dc373bb_dev/rpmbuild.log, which basically makes it impossible to figure out what's going on.

**Comment by yuwata** [comment]
#9456...

**Comment by evverx** [comment]
It makes me think that Fedora CI isn't maintained actively and can be safely turned off until a bash script or something like that is updated/written that can handle errors more gracefully because, frankly, simply posting links to nowhere doesn't seem to be the best feedback possible.

**Comment by yuwata** [comment]
Yeah, I agree with you.

**Comment by keszybz** [comment]
I reached out to Frederic Lepied, he's just back from vacation, so hopefully he'll be able to look into this.

**Comment by fredericlepied** [comment]
Working on it. It was an issue with the certificate for Copr but now the cloud we are using seems to have trouble. I'll update the status as soon as it's fixed.

**Comment by evverx** [comment]
Thank you for taking a look. If I understand correctly, the issue causing the most recent failures is being fixed, but I'm wondering what will happen next time Fedora CI stops working? Would it be possible for it to send notifications directly to the maintainers via email/slack/telegram/... so that we could avoid this chain of people redirecting messages to each other until they get to the intended recipients? Also, judging by the "internal error" messages, the webhook can distinguish the failures of the unit tests from everything else. Could it not mark PRs as "failed" if failures are of internal origin? I don't think that new contributors (who don't know that the CI fails more often than not and can be ignored) are very happy to get the red cross as soon as they posted their PRs.

**Comment by evverx** [comment]
I've also just learnt that Fedora CI aren't set up to run regression tests like the ones I added in https://github.com/systemd/systemd/pull/9996. If for whatever reason, it will be decided not to turn it off, it would be great to make that work. It would also be nice to run `test-udev.pl` and `test-execute`, which are currently skipped. I figure it's because they has to be run as `root`.

**Comment by evverx** [comment]
Just to be clear, I personally think that Fedora CI should be turned off because it tends to create more problems than it solves. I, frankly, don't understand why everybody else seems to put up with this abandoned piece of testing infrastructure. Half a year ago I was making fun of it (which I'm not proud of, I'm sorry), but at the same time I had some hope that the situation would improve. I obviously was wrong.

**Comment by evverx** [comment]
Apparently, it has started to work. Next time it breaks I'll just ignore it. I'm closing the issue. I hope the questions I asked will be eventually answered, though.
