### ISSUE TITLE
--pty was never actually implemented in systemd-run

### ISSUE THREAD

**Issue by gleventhal** [systemd/systemd#9987]
**systemd version the issue has been seen with**
> .v 219

**Used distribution**
 > CentOS 7

**Expected behaviour you didn't see**
 > --pty should behave as -t in systemd-run, but I looked at src/run/run.c and it appears it was accidentally left out.

**Unexpected behaviour you saw**
 > Error when substituting --pty for -t

**Steps to reproduce the problem**
systemd-run --pty --quiet cat /etc/hosts

**Comment by filbranden** [comment]
systemd v219 is just too old, we only support the latest versions.

This was introduced as `--tty` but only fixed to `--pty` in systemd v230 (see commit 5cfde70c6e7c8afcd2c9cdb3505301c3e6cde6da which fixed it.)

You can try to ask your distro to backport this patch, but I doubt that'll work, especially considering you can just use `-t` which will work...

Closing this issue as it's been fixed already.
