### ISSUE TITLE
logind.CanSuspendThenHibernate returns success, trying to actually do suspend-then-hibernate fails

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#9988]
I'm seeing $subject on a Bay Trail tablet where dmesg says the following about the rtc:

[    2.597524] rtc_cmos 00:00: registered as rtc0
[    2.597529] rtc_cmos 00:00: no alarms, y3k, 242 bytes nvram
[    2.964475] rtc_cmos 00:00: setting system clock to 2018-08-31 21:29:15 UTC (1535750955)

Notice the "no alarms", gnome-settings-daemon does a logind.CanSuspendThenHibernate call to see if hibernate-then-suspend can be used, this returns true on this device despite the "no alarms" in dmesg.

When g-s-d then asks logind to suspend-then-hibernate this fails like this:

Aug 31 21:30:18 localhost.localdomain systemd-sleep[2237]: Failed to write '1535761817' to /sys/class/rtc/rtc0/wakealarm: Input/output error
Aug 31 21:30:18 localhost.localdomain systemd[1]: systemd-suspend-then-hibernate.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 21:30:18 localhost.localdomain systemd[1]: systemd-suspend-then-hibernate.service: Failed with result 'exit-code'.
Aug 31 21:30:18 localhost.localdomain systemd[1]: Failed to start Suspend; Hibernate if not used for a period of time.
Aug 31 21:30:18 localhost.localdomain systemd[1]: Dependency failed for Suspend; Hibernate if not used for a period of time.
Aug 31 21:30:18 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-suspend-then-hibernate comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Aug 31 21:30:18 localhost.localdomain systemd[1]: suspend-then-hibernate.target: Job suspend-then-hibernate.target/start failed with result 'dependency'.
Aug 31 21:30:18 localhost.localdomain systemd[1]: sleep.target: Unit not needed anymore. Stopping.
Aug 31 21:30:18 localhost.localdomain systemd[1]: Stopped target Sleep.
Aug 31 21:30:18 localhost.localdomain systemd-logind[757]: Operation 'sleep' finished.

This causes the tablet to wakeup again immediately when the power-button is pressed to suspend the device.

**Comment by lucaswerkmeister** [comment]
If I’m reading the kernel source correctly, the message “no alarms” and the `EIO` error are generated in case of `!is_valid_irq(cmos->irq)`. The same condition also guards reads from the ` wakeup` file, as far as I can see, so perhaps logind should try to perform a read from the file to determine whether wakeups are supported or not.

Can you check what `cat /sys/class/rtc/rtc0/wakealarm` reports on this tablet?

**Comment by lucaswerkmeister** [comment]
(systemd’s `can_s2h` function already tries to `access` the `wakeup` file in `W_OK` mode, but it looks like that’s not enough to guarantee that the file actually supports writing. Perhaps this also depends on the RTC driver.)

**Comment by jwrdegoede** [comment]
"cat /sys/class/rtc/rtc0/wakealarm" reports nothing on this tablet, it results in a direct EOF / return to commandline (same as a "cat /dev/null").

**Comment by lucaswerkmeister** [comment]
Hm… do you know if there are any other ways to detect the non-availability of alarms on that device, other than the equivalent of `journalctl -k --grep '^rtc.*no alarms'`? :/
