### ISSUE TITLE
/run/user/{userid} wrong SELinux context

### ISSUE THREAD

**Issue by cgzones** [systemd/systemd#9993]
**systemd version the issue has been seen with**
> $ systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian sid

**Expected behaviour you didn't see**
 > `/run/user/{USERID}` labeled as `user_runtime_t` as defined by policy

**Unexpected behaviour you saw**
 > labeled as `tmpfs_t`

Maybe the same as #257, but somehow systemd is directly creating the directory, not systemd-logind (was that changed?)

With a `type_transition initrc_t tmpfs_t:dir user_runtime_t;` I can change the label, but that's sub-optimal and too generic (affects all tmpfs).

**Comment by sourcejedi** [comment]
systemd-logind doesn't create it anymore because it was split out to a helper (which is executed inside a systemd unit).  So that's a good suspect to look at.  The selinux code was kept, but maybe something's gone wrong.  https://github.com/systemd/systemd/commit/a9f0f5e50104fc5cc511aa10007f7f8b8366fed8#diff-80908f307d95f113443f1717ab9e7199

**Comment by sourcejedi** [comment]
Did you notice this as a regression from a previous point in Debian unstable, or was this the first time you've relied on this feature?

**Comment by sourcejedi** [comment]
I notice `src/login/user-runtime-dir.c` does not call `mac_selinux_init()`.

Are you able to test a patch?

```
diff --git a/src/login/user-runtime-dir.c b/src/login/user-runtime-dir.c
index 9f2c594a0..6d6f2b49a 100644
--- a/src/login/user-runtime-dir.c
+++ b/src/login/user-runtime-dir.c
@@ -10,6 +10,7 @@
 #include "mount-util.h"
 #include "path-util.h"
 #include "rm-rf.h"
+#include "selinux-util.h"
 #include "smack-util.h"
 #include "stdio-util.h"
 #include "string-util.h"
@@ -162,6 +163,12 @@ int main(int argc, char *argv[]) {
         log_parse_environment();
         log_open();
 
+        r = mac_selinux_init();
+        if (r < 0) {
+                log_error_errno(r, "Could not initialize labelling: %m\n");
+                return EXIT_FAILURE;
+        }
+
         if (argc != 3) {
                 log_error("This program takes two arguments.");
                 return EXIT_FAILURE;
```

**Comment by cgzones** [comment]
It worked *somehow* back in the days with systemd-logind, but I just found a SELinux transition `type_transition systemd_logind_t tmpfs_t:dir user_runtime_t;`, so probably the issue was just hidden. 

p.s.: Thanks for the path, I'll test it

**Comment by cgzones** [comment]
Thanks a lot, the patch fixes my issue.
